### ISSUE TITLE
How DocPad does plugin conventions. 

### ISSUE THREAD

**Issue by mikeumus** [serverless/serverless#1000]
Hello everyone,

This isn't an issue with Serverless but just a opportunity for discussion. I hope it's alright to post this here. 

I just started working with Serverless and noticed there was no naming convention for Serverless plugins. At DocPad we follow the convention: `docpad-plugin-name`. 

Including "docpad-plugin" in our plugin's package.json's keywords allows for easy linking to all docpad plugins on npm: 
- https://www.npmjs.com/browse/keyword/docpad-plugin
- https://www.npmjs.com/browse/keyword/serverless-plugin :disappointed: 

This is most clear what a docpad plugin is versus what's maybe some other related module, but isn't necessarily a plugin. 

Many of the Serverless plugins do follow the convention: `serverless-name-plugin`, however this is harder to parse if needed and less grammatically correct. But then some serverless plugins are free to roam wild like: `serverless-meta-sync`, `serverless-offline`, `serverless-runtime-streamline`. 

My favorite Serverless plugin so far, `serverless-plugin-cronjob` has got it. :+1: 

Another thing that docpad does is if in the plugin's package.json it has a version of >= 2.0.0 it automatically gets loaded instead of developers having to require the step of adding plugins to a config file (the json file of Serverless). You can disable and config DocPad plugins still easily enough from `docpad.coffee`. 

Lastly, this convention allows us to have the simple cli plugin install command:
  `docpad install pluginname`
*Note this isn't the full name (`docpad-plugin-name`) it's simply the "name" part. 

I'm not saying this is definitive best practice on plugin naming conventions but is one approach to plugin convention that's working for us. See DocPad Plugin docs here: http://docpad.org/docs/plugin-write/

I hope this is helpful and I'm open to discussion on this with everyone. 

Best,
_Mike_

**Comment by dherault** [comment]
I like this idea. We do have [a registry](http://justserverless.github.io/serverless-registry/), but it is not as famous as npm's and I'm not even sure it's in the docs.

Applying it would mean the depreciation of most plugins (including depreciation messages, etc...), but hey, Serveless is still in beta :monkey:!

**Comment by mikeumus** [comment]
Plugin registry, very cool. 

I don't think it has to beat out NPM,
 just a nice concise home for Serverless plugins which looks like it's already accomplishing! +1

**Comment by pmuens** [comment]
Plugin registry collaborator here. I too think that we should have an alternative way to look for Serverless related PlugIns. NPM is just bloated with non serverless related packages when you search.

I try to add every PlugIn in the registry. I've also proposed some kind of Serverless PlugIn manger which manages the PlugIns for you and uses NPM in the background.
(See here: https://github.com/serverless/serverless/pull/650)

This way you could do `serverless plugin add <creator>:<plugin-name>`. Maybe we'll adopt something like that in the future.

**Comment by flomotlik** [comment]
We're going to work more on this in #1722

**Comment by mikeumus** [comment]
Gitbook does it this way too: 
- https://github.com/GitbookIO/plugin#how-gitbook-plugin-works
