### ISSUE TITLE
Support creating Graviton-based arm64 Lambda Functions

### ISSUE THREAD

**Issue by astuyve** [serverless/serverless#10025]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Lambda can now run on [arm64-based graviton](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) processors, which are cheaper.
It's available on the AWS Console, along with documentation: https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html?icmpid=docs_lambda_help

Documentation is now out for CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-architectures

### Proposed solution (optional)
In 2.x provider arch should be *optional* and default to `x86_64`.
In 3.x it should be required (since picking the wrong default could cause issues with either choice for users migrating from other frameworks).

At provider level
```yaml
provider:
  name: aws
  architecture: arm64 # or x86_64
```

Per function (overrides provider if both are present):
```yaml
  hello:
    handler: handler.hello
    architecture: arm64 # or x86_64
    events:
      ...
 ```

**Comment by davetownsend** [comment]
@astuyve probably makes sense at provider level as well if you just want to opt in for all functions in the service.

e.g.

```yaml
provider:
  arch: arm64 # or x86_64
```

**Comment by stephenbawks** [comment]
Would it be a required parameter or would one be default?

**Comment by astuyve** [comment]
@davetownsend - Yeah, like env vars. Updated.
@stephenbawks - I propose optional for 2.x, since it'd be a breaking change otherwise. For 3.x - required.

**Comment by stephenbawks** [comment]
> @davetownsend - Yeah, like env vars. Updated.
> @stephenbawks - I propose optional for 2.x, since it'd be a breaking change otherwise. For 3.x - required.

Be nice if you can set them at the provider and at the function level in case you wanted to have two different functions work two different arch's.

**Comment by astuyve** [comment]
Yup, that's what it says - provider level default with function level overrides.

**Comment by astuyve** [comment]
It's late for both @medikoo and @pgrzesik - I'm sure they'll have more thoughts to add. But it looks like CloudFormation support is available now/soon, since this has landed in [CDK](https://github.com/aws/aws-cdk/commit/b3ba35e9b8b157303a29350031885eff0c73b05b)

**Comment by andymac4182** [comment]
Comments from AWS https://twitter.com/edjgeek/status/1443337744319721487 that it is being released over the next day.

**Comment by medikoo** [comment]
@astuyve great thanks for the proposal! We definitely should have that in.

For now I believe we should wait until details on CF side will clarify, having that we should be ready to go

**Comment by pgrzesik** [comment]
Thanks a lot for the proposal @astuyve - it's definitely something that would be great to have supported by the Framework.

I'm not sure about one thing from the proposal, which is making that setting required for new major version. I think for a lot of new users it can be a bit confusing to specify something that they might not really understand/care about and if `x86_64` will still be the default on CloudFormation level, I would keep it as default on Framework level too, to reduce one extra required property. 

Btw - there are no CF docs yet, but seems like the support is already there - CDK version that supports it already has been released: https://github.com/aws/aws-cdk/commit/b3ba35e9b8b157303a29350031885eff0c73b05b

**Comment by idaviderock** [comment]
Yeap! no docs yet. But with CDK you can take a look how it is working. It is an array of values `x86_64`, `arm64`.
CF output:
```json
    "MyLambda": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": ... ,
        "Role":  ... ,
        "Architectures": [
          "arm64",
          "x86_64"
        ],
        "Handler": ... ,
        "Runtime": ...
      },
    }
```

So, it is not one possible value. The function can run on both platforms. But like everyone said, it is better to wait for docs to be clear about it.

If you urge to use it you can declare inside the `resources` and let serverless merge the config, like this.

```yaml
resources:
  Resources:
    {_LAMBDA_RESOURCE_NAME_}LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Architectures:
          - arm64
```
Change {_LAMBDA_RESOURCE_NAME_} with your lambda resource name.

**Comment by pgrzesik** [comment]
Hello @idaviderock :wave: Even though it's a list, I don't think it's possible to deploy function with both architectures at the same time by specifying it as a list with more than one item. I'm honestly even not sure how useful that would be as it's not determined anywhere then what arch an actual invocation would use - I believe it's just how the underlying API looks like and we've seen multiple instances where someone is a list in CloudFormation but it accepts at most a single item. Also, in console you can only select one architecture, not both. 

Additionally, it's not only about property on `AWS::Lambda::Function` resource, but it also touches layers, which can have supported architectures specified. 

Given the above, I think it would be best to wait for official CF documentation before trying to figure it out from incomplete information.

**Comment by idaviderock** [comment]
Yeap! Let's wait! :)

**Comment by JamesKyburz** [comment]
@pgrzesik agreed, it's a radio button the aws console.

**Comment by mnapoli** [comment]
SAM CLI released support for that feature, I'm not sure if CF docs are up yet. As soon as they are I think we'll be 👍  to move forward.

I read something curious in SAM CLI:

https://github.com/aws/aws-sam-cli/pull/3316/files#diff-cb9f15cef0511cbc8b0210b10e29c76a7db84068d5791e1dd57134b70d684114R22-R25

It seems multiple values of architecture are intentionally supported for a Lambda function? For a layer I get it, but I don't understand why for a Lambda function. It seems the validation is done only for the first item:

https://github.com/aws/aws-sam-cli/pull/3316/files#diff-1c170f50ddb575edcdc1a9390e69115c4f4be0b151486d57a09cd83f67924b88R371-R374

Maybe they are following the same pattern as CloudFormation so that it's "future compatible"? (just in case something magical happens in the future that could support multiple architectures?)

**Comment by medikoo** [comment]
> Maybe they are following the same pattern as CloudFormation so that it's "future compatible"? (just in case something magical happens in the future that could support multiple architectures?)

@mnapoli we observe such pattern in many different options on the AWS side. I think it's because they by no means want to be breaking, and they follow quite strict (cross-language) schemas. I assume that if there's the slightest chance they may want support for multiple values in the future, then from a start they settle on the type that allows that, as changing that later is a no go.

In Framework we settle on singular property in such case, as it's cleaner, and also Framework design allows switching support from _singular_ to _mutliple_ (with backward compatibility) without a big friction.

**Comment by mnapoli** [comment]
> In Framework we settle on singular property in such case, as it's cleaner, and also Framework design allows switching support from singular to mutliple (with backward compatibility) without a big friction.

💯 agree with that. Simple first, with room for more complexity later.

**Comment by astuyve** [comment]
Docs are out now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-architectures

Looks like it's a list of 1 - Eric Johnson mentioned they are keeping their options open for the long term.

**Comment by medikoo** [comment]
Having the docs, internally we agreed to release support for it on Monday

**Comment by medikoo** [comment]
Internally, for setting name, we've decided to go with `architecture`  instead of `arch`. I've updated the proposal in top description
