### ISSUE TITLE
More docs for monolithic case needed

### ISSUE THREAD

**Issue by markstos** [serverless/serverless#1007]
In particular, I couldn't find docs about mapping multiple endpoints to a single handler.

What communicates to the handler which endpoint has been called?

The doc section on "Monolithic" links to the a GraphQL project which has only one endpoint, making it a poor example of a typical monolithic app.

For developers coming from Express, it's a natural to think about how an Express app might be designed with a single 'server' with several URLs that are handled by it.

**Comment by dperjar** [comment]
Does anyone have something like this running, and can you describe what your s-function.json looks like until the docs are improved?

**Comment by flomotlik** [comment]
We're going to do more example on this in the future. Closing here for now as we have concrete plans for this already in place
