### ISSUE TITLE
Environment variables default to variable name

### ISSUE THREAD

**Issue by Borfswitch** [serverless/serverless#1008]
If an environment variable is not set in the *s-variables.json* file, I would expect the value of that environment variable to be undefined when deployed. Instead, the value of the environment variable becomes `${variableName}`.

The value of the environment variable also becomes `${variableName}` if you set the environment variable to `false` or `null` in the s-variables.json file.

**Comment by HyperBrain** [comment]
(1) I agree that this behavior is a bit unexpected. At least a warning is emitted during deploy.

(2) Currently only string types are accepted for variables. I remember that there is already a task to support other types, like objects or arrays (but do not remember the issue number).

**Comment by eahefnawy** [comment]
@HyperBrain FYI I already pushed an enhancement for variables to accept any data type, not just a string. So it should work. 😊

**Comment by HyperBrain** [comment]
@eahefnawy :-D Great! I think that will make lots of people happy. Maybe you can link the commit or issue here.

**Comment by eahefnawy** [comment]
It was a while back actually, but here's the new LOCs:
https://github.com/serverless/serverless/blob/master/lib/utils/index.js#L343-L352

**Comment by eahefnawy** [comment]
@Borfswitch thanks for reporting this, I think you're right. It should be explicitly falsey.

**Comment by andylibrian** [comment]
I got another issue with these LOCs:

https://github.com/serverless/serverless/blob/master/lib/utils/index.js#L343-L352

When I have 

```javascript
{
  "maintenance": false
}
```

in my `_meta/variables/s-variables-common.json`, I got:

```
WARNING: This variable is not defined: maintenance
```

And the env var unexpectedly contains '${maintenance}' string, that evaluates to true (the opposite of what is expected). The same goes with 0.

**Comment by flomotlik** [comment]
This issue is resolved in the latest version of Serverless
