### ISSUE TITLE
V 0.5.2 - some folder in third party module are not deploying

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#1009]
recently i have tried [fb](https://github.com/node-facebook/facebook-node-sdk) package to deal with Facebook.in local it is working fine.

when i am trying to deploy lambda function using `sls function deploy functionname - t` i am not able to upload all folder of `fb` module... in my case it  is `combined-stream`.

i faced following error

`Error: Cannot find module 'combined-stream'`

please check images for more detail

`_tmp dir fb module image tried with -t flag with function deploy`

![tmp_dir_fb](https://cloud.githubusercontent.com/assets/17105608/14558646/36232a84-0321-11e6-9a0b-94e5eb001934.png)

my `node_modules/fb` folder

![node_modules_dir_fb](https://cloud.githubusercontent.com/assets/17105608/14558668/53c8218e-0321-11e6-9abc-6f96e60e6480.png)

**Comment by HyperBrain** [comment]
Can it be that this is another NPM 3.xx issue? I also use the fb module and for me it works. What version of NPM are you using?

**Comment by nirmalgoswami** [comment]
@HyperBrain i am using npm `v2.14.12`

**Comment by nirmalgoswami** [comment]
@HyperBrain which npm version are you using ?

**Comment by HyperBrain** [comment]
same as you - 2.14.12.

**Comment by nirmalgoswami** [comment]
@eahefnawy is there any chance to fix this ?

**Comment by nirmalgoswami** [comment]
@HyperBrain @eahefnawy Thanks for your time,this issue was related to `excludePatterns` property.

i have added `.bin` in `excludePatterns` so this issue has been solved by removing `.bin` from `excludePatterns` property

**Comment by eahefnawy** [comment]
Yikes that was a tough one! Good find! Thanks for letting us know @nirmalgoswami 😊
