### ISSUE TITLE
Stage naming needs validation and maybe specific transformations

### ISSUE THREAD

**Issue by boushley** [serverless/serverless#101]
It looks like you can only currently use stage names that are lowercase alphanumeric. Due to the mix of services consuming these names and some [`toLowerCase` calls](https://github.com/jaws-framework/JAWS/blob/546cd9cb31936682449a8b937cfc9a9c700b3044/lib/commands/deploy_api.js#L686) in different commands.

It looks like currently CloudFormation requires names to be alphanumeric w/ dash (no underscore)
API Gateway stage names are alphanumeric w/ underscore (no dash)

So it looks like we have a few options:

1. Enforce that stage names are alphanumeric and all lowercase. By just adding some validation to `jaws new` (project and stage) we could gloss over many of these issues.
2. Audit code that handles stage names and ensure we don't have any `toLowerCase` calls, and then we should be safe to use alphanumeric mixed case.
3. Write an abstraction around stage names that allows dash or underscore internally, and then converts the stage name for AWS services to the other for AWS services that don't support that special character. (It looks like dashes are supported most places, and the API Gateway stage name restriction is a bit odd)

I'd love to open a PR resolving this issue, but I've seen requests to hold off for the time being in other issues.

Let me know if this is something you'd be open to a PR for.

**Comment by boushley** [comment]
I also think it's interesting to see how others are using stage name.

I ran into this because I'm working in a team environment and was trying to setup a stage as `boushley-dev`. That blew up at the point of deploying to API Gateway so I switched to `boushley_dev`. That blew up when creating the CloudFormation Template. So I switched to `boushleyDev` which blew up when `jaws deploy api` couldn't find the stage because of the `toLowerCase` call.

**Comment by ac360** [comment]
@boushley Great find!  You're close to this issue, which option do you prefer?  Option 1 sounds simplest.

I'm currently thinking about changing the naming convention for all JAWS resources, so this is timely.  I'm also thinking about giving each JAWS project a unique ID and including it in the names of all JAWS-related resources on AWS, as opposed to using the project's name which we're doing currently.  This way, people can change the name of their projects at any time.  The downside is that when you are reviewing your resources in the AWS console, you will only see IDs and not project names.  

Please hold off on a PR   We're making major changes until we release the V1 Beta on Monday (9/14).

**Comment by boushley** [comment]
@ac360 I think option 1 would be good enough for now. Option 3 would be a great solution, but especially for the stage this project is at I don't think the work to benefit ratio is high enough.

Glad to hear the 9/14 date again... after the comments in the V1 Google doc I wasn't sure :)

On the idea of a unique ID that's a tough one. When looking at my AWS resources it is super handy to see which ones are from which projects. I would understand making something like stage a unique ID that the user doesn't control (guess that's a reasonable fourth option). At the same time from my time working in AWS on CloudFormation I understand how painful it is to deal with users changing the name of something. My guess is you're going to get complaints either way.

I have more thoughts on the unique ID thing, should I put them here or as comments on the JAWS v1.0.0 Google Doc?

**Comment by boushley** [comment]
@ac360 Also, I keep forgetting to say it, Thanks! This project is fantastic! When I saw API Gateway released I was super excited about this possibility and instantly wanted something like this. I'm excited this project is so far along!

**Comment by ac360** [comment]
@boushley Please put everything in the V1 Google doc for now.  Comment everywhere you need to.  Your opinions are good ones.  The V1 doc is a bit behind, but I will update it tonight.

Thanks for your support.  I'm working full-time on this.  V1 is going to be a game-changer.  Hopefully JAWS will save all of us developers tons of money, tons of devops time, and then we will be forced to do other things with our lives, like go outside (I've forgotten what that's like).

**Comment by boushley** [comment]
@ac360 hopefully you can become re-acquainted with the outdoors soon.

If there's any way I can help, let me know. I understand how time consuming it is to spin someone up on a project though, so if you're heads down until v1 beta hits, I totally understand.

**Comment by ac360** [comment]
@boushley Def heads down until Monday.  At that point, we're going to seek everyone's input and throw out some features we need but didn't get to, in case anyone wants to implement them.

**Comment by fantapop** [comment]
option 1 would have been pretty sweet ;-)
