### ISSUE TITLE
V 0.5.5 -- doing sls function run breaks the terminal session

### ISSUE THREAD

**Issue by DHNCarlos** [serverless/serverless#1010]
Every time I run a function locally using `sls function run <function>`, my terminal session breaks. No output is visible and the only time the terminal screen updates, is when I press enter. The current solution I've found is to close the terminal and open a new one. Which of course doesn't solve it fully because doing another function run breaks it again.

Using bash on Ubuntu 15.10.

This issue did not occur on Serverless v0.4.*

All other commands seem to be unaffected, so far seems to be only happenening with the `function` command.

**Comment by eahefnawy** [comment]
Hmmm I tried to reproduce this today but I wasn't able to. It seems to be working pretty instantly. is there any thing specific about your code/environment we should know of that might be relevant?

Also is this happening with the `function run` only or all `function` commands?

**Comment by kristiandreher** [comment]
I also experience this issue with 0.5.5. However it only happens if I don't use the -s option. With the -s option it run fine.

**Comment by eahefnawy** [comment]
@kristiandreher hmmm do you get prompted to choose a stage if you don't specify the `-s` option?

**Comment by kristiandreher** [comment]
@eahefnawy Yes, it is after that prompt that the terminal session behave strange. (By the way, I am using bash on Ubuntu 14.04).
For other commands (like function deploy) the prompt to select stage works fine.

**Comment by DHNCarlos** [comment]
@eahefnawy I tried @kristiandreher with the `-s` defined and then `function run`, the terminal works properly. I tested with a clean sls 0.5.5 project that has one stage and without `-s` option, the terminal works fine.

The terminal crash seems to happen when there are multiple stages and not defining `-s` option.

**Comment by jordanmack** [comment]
Confirmed on a clean Ubuntu 15.10 virtual machine. Using the `reset` command after the problem fixes it.

```
username@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
username@ubuntu:~$ node -v
v5.11.1
username@ubuntu:~$ sls -v
0.5.5
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
