### ISSUE TITLE
V 0.5.2 excludePatterns bug related function name

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#1011]
suppose you have two function `userNameFirst` and `userNameLast`

`s-function.json` of `userNameLast`

```
"handler": "user/userNameLast/handler.handler",
 "custom": {
    "excludePatterns": [
         "userNameFirst"
    ]
```

got error
`ENOENT: no such file or directory, open 'E:\wamp\www\project\_meta\_tmp\userNameLast@1460727320197\user\userNameLast\_serverless_handler.js'`

Issue is - excludePatternes skipping by checking first word `userName` it should skip folder using exact same folder name not like foldername%

checked by using `-t` flag with `function deploy` i am not able to find `user/userNameLast` folder in `tmp` directory

**Comment by flomotlik** [comment]
@nirmalgoswami we're currently reimplementing this including the meta folder and so this issue will be resolved automatically by then. I'm closing here for now as we will address it.
