### ISSUE TITLE
Deploy everything *except* Lambda packages

### ISSUE THREAD

**Issue by ronkorving** [serverless/serverless#10113]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I'm trying to identify where development of my stack could (at least in theory) benefit from speedups.

One thing I noticed is that I have quite a bit of extra CloudFormation resources in my serverless.yml, and during periods where I'm exclusively dealing with infra, not Lambda code, I waste a lot of time staring at my machine packaging up function code and its dependencies.

### Proposed solution (optional)

It could be quite a time-saver, if I could make `sls deploy` simply not bother with the package-step and get on with rolling out the CloudFormation template. For example an `--ignore-package` flag for `sls deploy` for example. Or just like how there is `deploy function`, maybe there could be a `deploy infra`.

**Comment by olingern** [comment]
I also was looking for something like `serverless deploy function -f functionName` for DynamoDB or to somehow omit lambda uploads that are taking ~1 minute for a very small Go project.

<img src="https://user-images.githubusercontent.com/1470297/138013278-0ba189e2-a599-4911-972e-4c4ef63d47af.png" height=120 />

In this example, I actually didn't change any code in my Lambda functions but everything is being repackaged and uploaded.
