### ISSUE TITLE
Rename nodejs runtime to nodejs0.10 for sls v0.6

### ISSUE THREAD

**Issue by dherault** [serverless/serverless#1013]
Hello all,

I'm rewriting serverless-offline to support any runtime (and any provider in a near future) and I noticed this:
- Lambda exposes two Nodejs runtimes: `nodejs` and `nodejs0.10`
- Serverless exposes two Nodejs runtimes as well: `nodejs` and `nodejs4.3`

So here is my suggestion: either remove Node 0.10 from Serverless 0.6 (I vote for that), or make it so the real `nodejs` runtime points to Node 4.3 and keep Node 0.10 under some alias (like `nodejs0.10`).

A bit obvious, but thanks for reading!

**Comment by eahefnawy** [comment]
@minibikini was just suggesting that as well :)

**Comment by flomotlik** [comment]
We now use the runtime that AWS provides as well, so more flexibility.
