### ISSUE TITLE
$input.params always an unparsed string

### ISSUE THREAD

**Issue by TCMiranda** [serverless/serverless#1014]
Is there a reason why all params related mapping from the template is being exported as a string?

Ex: 
Defining the endpoint `GET /foo/{arg}`

Requesting `/foo/value`

With the defined template:
```json
{
  "apiRequestTemplate": {
    "application/json": {
      "pathParams" : "$input.params().path"
    }
  }
}
```

When accessed from `event.pathParams`, resolves to

    {arg=value}

Not a json, and as I managed to understand, it is not possible to extract the json value, is it?

Thanks!

**Comment by simoami** [comment]
Experiencing the same issue. Values are returned in an unusable form and the examples listing  `"$input.params().header"` as valid example are misleading. 

Here's what you get:

```
"test": "{Accept=application/json, Accept-Encoding=gzip, deflate, sdch, br, Accept-Language=en-US,en;q=0.8,fr;q=0.6,ru;q=0.4, CloudFront-Forwarded-Proto=https, CloudFront-Is-Desktop-Viewer=true, CloudFront-Is-Mobile-Viewer=false, CloudFront-Is-SmartTV-Viewer=false, CloudFront-Is-Tablet-Viewer=false, CloudFront-Viewer-Country=US, Content-Type=application/json, Host=bty1a4k1a7.execute-api.us-east-1.amazonaws.com, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36, Via=1.1 14f603c905dd45ba5c6093eee54dbdc4.cloudfront.net (CloudFront), X-Amz-Cf-Id=G0KKTnn4U0MNqX5ci7v_ivpNMpQ1TCfihpNXW8rHevGCwCILE9CU0A==, X-Forwarded-For=207.38.163.143, 205.251.250.115, X-Forwarded-Port=443, X-Forwarded-Proto=https}",
```

Notice the `=` sign for assignments and the lack of proper quoting of values.

**Comment by TCMiranda** [comment]
@simoami Another thing to add, is that even the commas aren't escaped.
```
{ Accept-Encoding=gzip, deflate, sdch, br, Accept-Language=en-US }
```

**Comment by simoami** [comment]
@TCMiranda Yes, the *only* way to get all `path` values is to use a `s-templates.yaml` with the following content:

```
apiRequestTemplate:
  application/json: |
    {
      "pathParams": {
        #foreach($param in $input.params().path.keySet())
        "$param": "$util.escapeJavaScript($input.params().path.get($param))"
        #if($foreach.hasNext),#end
        #end
      }
```

**Comment by flomotlik** [comment]
We're currently changing the way templates are handled in V1, so closing this issue here.
