### ISSUE TITLE
Native ES6 Functions in Node 4.3.x (V8 Javascript Engine) Not Accessible -- Must downgrade from es2015-node4 to es2015 full transpile to ES5

### ISSUE THREAD

**Issue by n8sabes** [serverless/serverless#1016]
**UPDATE: See post below and related.**

- - - - Original Post - - - -

I just updated to sls 5.5 and node4.3 runtime. My code uses the `import` keyword which requires the inclusion of es2015-node4 to fill missing ES6 features gaps.

Using the following `s-function.json` "custom" definition, deployment and remote function execution work fine (`sls function run funcName -d`).

```
	"custom": {
		"excludePatterns": [],
		"optimize": {
			"exclude": [
				"aws-sdk"
			],
			"transforms": [
				{
					"name": "babelify",
					"opts": {
						"presets": [
							"es2015-node4"
						]
					}
				}
			]
		}
	},
```

However, local execution fails (`sls function run funcName`). As a result of further investigation, it appears that local execution does not apply babel transform logic (which is required for full ES6 support).

To prove the theory, I bogus-ified the "custom" node and ran `sls function run funcName`. No errors were reported, verifying the transforms are not applied which ultimately cause an `Unexpected reserved word` error when executed.

```
	"custom": {
		"excludePatterns": [],
		"optimize": {
			"exclude": [
				"aws-sdk"
			],
			"transforms": [
				{
					"name": "bogus__babelify",
					"opts": {
						"presets": [
							"bogus__es2015-node4"
						]
					}
				}
			]
		}
	},
```

Is there a different way to require local function execution to apply transforms (to get the missing ES6 features)?

Note: At first glance, it appeared that #446 was related, but this is the reverse issue and moreover a matter of not getting transforms applied upon local execution.

**Comment by rajington** [comment]
So `serverless-optimizer-plugin` does not run when testing locally, you can see that here: https://github.com/serverless/serverless-optimizer-plugin/blob/master/index.js#L45

`serverless-runtime-babel` however does do some stuff on run:
https://github.com/serverless/serverless-runtime-babel/blob/master/lib/RuntimeBabel.js#L55

**Comment by n8sabes** [comment]
@rajington, thanks for the input. I'm not seeing `serverless-runtime-babel` execute in a nodejs4.3 runtime project. Are you aware of an sls nodejs4.3 example anywhere?

As for the big picture, would like to get this working to support unit testing of functions locally, prior to deployed unit tests.

**Comment by n8sabes** [comment]
**This issue also affects deployment making it impossible to deploy natively optimized code in Lambda Node 4.3.x w/ [V8 Javascript Engine](https://developers.google.com/v8/).**

Being forced to fallback to `es2015` unnecessarily transpiles a lot of ES6 logic that is natively supported in the Node 4.3.x Lambda (V8) Execution Environment. For deployment (code size and speed), `es20515-node4` makes the most sense for ES6-based solutions.

See: [serverless/serverless-runtime-babel#16](https://github.com/serverless/serverless-runtime-babel/issues/16)
See: [serverless/serverless-optimizer-plugin#44](https://github.com/serverless/serverless-optimizer-plugin/issues/44)

**Comment by flomotlik** [comment]
We've completely removed babel or optimizer support from V1 for now, we might bring it back at some point.
