### ISSUE TITLE
support caching for query string parameters

### ISSUE THREAD

**Issue by theburningmonk** [serverless/serverless#1017]
I don't seem to be able to specify that a query string parameter should be cached. I can add it via the `endpoints` section in my `s-function.js` but there doesn't seem to be a way to set the `Caching` flag to true.

```
"requestParameters": {
    "integration.request.querystring.query": "method.request.querystring.query"
},
```
![image](https://cloud.githubusercontent.com/assets/546969/14582443/f0c8f61c-03fc-11e6-8aef-3f2b197f09b6.png)

**Comment by theburningmonk** [comment]
The same problem exists for query path too, if I choose to use request path instead of query string parameter:

```
"path": "user/search/{query}",
"method": "GET",
"type": "AWS",
```

![image](https://cloud.githubusercontent.com/assets/546969/14582514/07d58dfa-03ff-11e6-9869-46d4de5c13a2.png)

**Comment by eahefnawy** [comment]
Interesting!!!! Thanks for pointing that out!

**Comment by HyperBrain** [comment]
@theburningmonk @eahefnawy According to the Serverless source code, setting the endpoint's `cacheKeyParameters` (array) and `cacheNamespace` (string) properties should create/set the caching to enabled. The properties are sent directly to the APIG REST API internally.
Could you check if you have defined these in your `s-function.json`?

```
        cacheKeyParameters:     _this.endpoint.cacheKeyParameters || [],
        cacheNamespace:         _this.endpoint.cacheNamespace     || null,
```

**Comment by theburningmonk** [comment]
Thank you, didn't realise that 👍 

That said though, AWS hasn't done a good job with [documenting](http://docs.aws.amazon.com/apigateway/api-reference/resource/integration) what these parameters are supposed to do.

After some fiddling around, something like this seems to do the trick:
```
"requestParameters": {
    "integration.request.querystring.query": "method.request.querystring.query"
},
"cacheKeyParameters": [
    "method.request.querystring.query"
],
```

**Comment by theburningmonk** [comment]
I did some more experiments, and [what I did](http://theburningmonk.com/2016/04/serverless-enable-caching-on-query-string-parameters-in-api-gateway/) to enable caching for querystring parameters didn't work for request path parameters. Any idea how it's supposed to work?

**Comment by HyperBrain** [comment]
I have to check this locally. Will try tomorrow.

**Comment by theburningmonk** [comment]
@HyperBrain were you able to take a look at this?

**Comment by christian-fei** [comment]
@HyperBrain any news?

**Comment by scotty-p** [comment]
@HyperBrain was there any update/workaround/fix to this for v0.5.5?

**Comment by HyperBrain** [comment]
@scotty-p I don't think so. Also I did not have time to investigate further into this as the time I was able to spent into contributions was quite little.

**Comment by jaxxreal** [comment]
Any news?

**Comment by Ch3ck** [comment]
Ran into this same issue today, wonder what you have to set on the "cacheNamespace" field
