### ISSUE TITLE
APIG cache configuration should be documented in SLS docs

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#1021]
APIG caching can be configured with the `cacheKeyParameters` and `cacheNamespace` endpoint properties in the `s-function.json`. The Serverless documentation currently is missing these parameters in the paragraph **Endpoint configuration** as well as in the `s-function.json` sample.

These should be documented properly (especially as AWS themselves are no good documenters).

Also mentioned in task #1017

**Comment by flomotlik** [comment]
As we're reimplementing a lot of this and the configuration will change this might not be necessary in the future, but we'll see.

**Comment by flomotlik** [comment]
tracked in #1597
