### ISSUE TITLE
Add DisableRollback option configuration for Stack Create and Update operation

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#10235]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Since August 2021, Cloudformation `create` and `update` operations accept an additional parameter that modifies its behavior in case of a `CREATE_FAILED` or `UPDATE_FAIL` event occurs. The default behavior of Cloudformation is to rollback to previous configuration, thus deleting resources that have been successfully created up to the errors. The new `DisableRollback` parameter enables keeping the state of previously provisioned resources when an operation fails.

[Feature release blog post](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-cloudformation-troubleshoot-errors/)

----

[Create operation parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#API_CreateStack_RequestParameters)
> **DisableRollback**
Set to true to disable rollback of the stack if stack creation failed. You can specify either DisableRollback or OnFailure, but not both.

----

[Update operation parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html#API_UpdateStack_RequestParameters)
> **DisableRollback**
Preserve the state of previously provisioned resources when an operation fails.

---

This is especially useful in development environment where fast iteration prevails over stack stability. This of course should not be used in production environments. 

### Proposed solution (optional)

Implement a new `provider.disableRollback` option to allow the use of this behavior

**Comment by pgrzesik** [comment]
Hey @fredericbarthelet :wave: Thanks for the proposal. I'll bring this topic up internally and will let you know :+1:
