### ISSUE TITLE
S3 event  not calling lambada function

### ISSUE THREAD

**Issue by koolkarni** [serverless/serverless#1024]
"events": [{
      "name": "ImagesUpload",
      "type": "s3",
      "config": {
        "bucket": "vegme-dev-images",// is my bucket name 
        "bucketEvents": ["s3:ObjectCreated:*"],
        "enable":true
      }
    }

My Handler code : 

'use strict';
console.log('Loading function');

let aws = require('aws-sdk');
let s3 = new aws.S3({ apiVersion: '2006-03-01' });

module.exports.handler = function(event, context) {
  console.log('Received event:', JSON.stringify(event, null, 2));

   // Get the object from the event and show its content type
   const bucket = event.Records[0].s3.bucket.name;
   const key = decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, ' '));
   const params = {
       Bucket: bucket,
       Key: key
   };
   s3.getObject(params, (err, data) => {
       if (err) {
           console.log(err);
           const message = `Error getting object ${key} from bucket ${bucket}. Make sure they exist and your bucket is in the same region as this function.`;
           console.log(message);
           callback(message);
       } else {
           console.log('CONTENT TYPE:', data.ContentType);
           callback(null, data.ContentType);
       }
   });
};

**Comment by flomotlik** [comment]
@koolkarni can you check in at our [Gitter Chat room](https://gitter.im/serverless/serverless) with this questions? I will close the issue here for now.
