### ISSUE TITLE
No way to set contentHandling (example in docs is wrong and no workaround)

### ISSUE THREAD

**Issue by rgalanakis** [serverless/serverless#10266]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using the example here: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#binary-media-types

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          request:
            contentHandling: CONVERT_TO_TEXT
          response:
            contentHandling: CONVERT_TO_TEXT
```

If I deploy, I get these warnings:

```
Serverless: Warning! You're using the AWS_PROXY in combination with a request configuration in your function "app". Only the request.parameters, request.schema, request.schemas configs are available in conjunction with AWS_PROXY. Serverless will remove this configuration automatically before deployment.
Serverless: Warning! You're using the AWS_PROXY in combination with response configuration in your function "app". Serverless will remove this configuration automatically before deployment.
```

This does not allow contentHandling to be set and base64 content returned from the Lambda cannot be transformed into binary data. It appears that serving binary files from serverless via Lambda and Api Gateway is totally broken.

### Service configuration (serverless.yml) content

```yaml
# serverless.yml

service: myapp

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  logs:
    restApi: True
  apiGateway:
    binaryMediaTypes:
      - 'image/jpeg'
      - 'image/gif'
      - 'image/png'
      - 'image/x-icon'
      - 'multipart/form-data'
      - 'text/css'
      - 'text/html'
      - 'text/jsx'
      - 'application/javascript'

functions:
  app:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          request:
            contentHandling: CONVERT_TO_TEXT
          response:
            contentHandling: CONVERT_TO_TEXT
```

### Command name and used flags

serverless deploy

### Command output

```shell
bash-3.2$ SLS_DEBUG=* make deploy-dev
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.66.2")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221".
            While it is highly encouraged to upgrade to new algorithm, you can still use the old approach by setting "provider.lambdaHashingVersion" to "20200924".
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [AWS sts 200 0.622s 0 retries] getCallerIdentity({})
Serverless: Warning! You're using the AWS_PROXY in combination with a request configuration in your function "app". Only the request.parameters, request.schema, request.schemas configs are available in conjunction with AWS_PROXY. Serverless will remove this configuration automatically before deployment.
Serverless: Warning! You're using the AWS_PROXY in combination with response configuration in your function "app". Serverless will remove this configuration automatically before deployment.
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.279s 0 retries] describeStacks({ StackName: 'lasttweetinaws-dev' })
Serverless: [AWS cloudformation 200 0.188s 0 retries] describeStackResource({
  StackName: 'lasttweetinaws-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.187s 0 retries] listObjectsV2({
  Bucket: 'lasttweetinaws-dev-serverlessdeploymentbucket-1e8jyh92zhnvc',
  Prefix: 'serverless/lasttweetinaws/dev'
})
Serverless: [AWS s3 200 0.121s 0 retries] headObject({
  Bucket: 'lasttweetinaws-dev-serverlessdeploymentbucket-1e8jyh92zhnvc',
  Key: 'serverless/lasttweetinaws/dev/1637750603831-2021-11-24T10:43:23.831Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 200 0.172s 0 retries] getFunction({ FunctionName: 'lasttweetinaws-dev-app' })
Serverless: Uploading CloudFormation file to S3...
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.66.2 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```

**Comment by rgalanakis** [comment]
Also to clarify, I get the same behavior whether I use `CONVERT_TO_TEXT` or `CONVERT_TO_BINARY`, I know what's in that example is wrong for my use case so I want to make clear the issue has nothing to do with that.

**Comment by pgrzesik** [comment]
Hello @rgalanakis - thanks for submitting your issue - did you try setting the `integration` explicitly? It might be the case that the example is wrong but the logic in the Framework doesn't have a bug

**Comment by rgalanakis** [comment]
If I use `integration: lambda`, I don't get the warning- but I end up needing to configure a number of other things I haven't figured out yet. Is this expected behavior? contentHandling only works with lambda integration, not the default lambda-proxy, and the example in the docs is extremely incorrect/incomplete?

**Comment by rgalanakis** [comment]
So here is how binary files works.

```yaml
provider:
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  app:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
```

And then in your lambda, whenever `isBase64Encoded: true` is returned by the Lambda, API Gateway will decode it back into binary, and return it to the client.

If you're using `serverless-http`, you'll want to use something like this:

```js
// These will be base64 encoded when returned from Lambda -> APIGateway.
// Because provider.apiGateway.binaryMediaTypes is "*/*",
// we'll always decode the lambda's base64 back into
// a binary response whenever the Lambda response
// is base64 encoded.
const BINARY_CONTENT_TYPES = [
  "image/jpeg",
  "image/gif",
  "image/png",
  "image/x-icon",
  "multipart/form-data",
];

// Using binary: true is broken, see https://github.com/dougmoscrop/serverless-http/issues/222
module.exports.handler = serverless(app, { binary: BINARY_CONTENT_TYPES });
```

Similarly for other web framework -> serverless wrappers.

The frustrating part is there are so many mismatches that can go wrong, with no clear indication of what the solution.

This is not explained holistically anywhere- not in AWS docs, not in Serverless docs, not in serverless-http, nowhere. Figuring this out required comprehensively understanding API Gateway, Serverless's integrations, and digging into how serverless-http works. This to me largely defeats the purpose of using SLS over working with the provider directly.

The SLS documentation is both wrong, in the sense that the example YAML is invalid, and unclear, in the sense that, there are two ways to do this:

- Using lambda-proxy (default) integration as I described, and
- Using lambda integration, specifying many more details, like explicit content handling

The existing docs are worse than no docs because they propose a third, invalid option: lambda-proxy integration with explicit content handling.

In the end, the solution makes perfect sense, and is in line with API Gateway design/docs, Serverless design/docs, and serverless-http's design/docs (though there is a bug there I filed in their repo). But these docs (at the very least, and probably the UX of using binary files entirely, insofar as SLS wants to abstract it) desperately needs to be revisited with the eyes of a normal customer/user, who doesn't have a comprehensive understanding of API Gateway, Serverless, and Lambda. I have built a dozen serverless projects and many dozens of web servers and this was incredibly difficult to figure out.

**Comment by pgrzesik** [comment]
Thanks for sharing @rgalanakis - I'm personally not very familiar with the inner workings of APIG when it comes to handling binary data, but if I understand correctly, the settings you presented in the comment below will be working effectively if you set `isBase64Encoded: true` in your response, correct? If that's the case, then definitely the docs needs an upgrade. As for the last part - do you have any specific ideas on what should be improved when it comes to binary data handling to make it easier to set it up?

**Comment by medikoo** [comment]
@rgalanakis great thanks for rising this up.

Indeed is a mess, and we definitely should improve our documentation  My findings are as follows:

- `binaryMediaTypes` is necessary if you want to return binary from lambda proxy integrations, but it's optional (still, complete rules are not clear to me) in non-proxy integrations. What's interesting in non-proxy integrations setting `*/*` is invalid and will always result with 500 (no hint on that in AWS docs, and even API Gateway execution logs, which just vaguely state "configuration error").
- `http.response.contentHandling` is specific to non-proxy integrations. Framework shows a warning, but it'll probably be better if it crashes with a more meaningful message. 
- With Node.js runtime, binaries can be sent only as base64 for strings, and it's why we need, `CONVERT_TO_BINARY` to be configured on the response if we respond in Lambda directly with base64 string. Having that and providing `response.headers.Content-Type: "'image/jpeg'"`, make things work (in non-proxy integration case), and then `binaryMediaTypes` setting is not needed.

Summarising AWS is a mess, and Serverless Framework failed in that case to help, making things additionally worse by promoting a totally invalid example.

I believe an improvement would be to provide two sections in our doc one dedicated to how to set up binary media types with proxy integrations and the other how to setup with non-proxy integrations.  @mnapoli what do you think?

**Comment by mnapoli** [comment]
@medikoo that sounds good!

One question: I've personally always used the proxy integration, I would expect that to be the default for every project.
Is there any reason/use case for documenting things for "non-proxy integration" scenarios? If we focused only on the most popular way to use API Gateway + Lambda that would be less effort here, and also simpler for users (one way to follow). I'm not suggesting to remove the existing documentation, just talking about this specific problem here.

**Comment by rgalanakis** [comment]
@medikoo thank you so much for that investigation! It means a lot that the team jumped on this quickly. It would be great to have the proxy use case documented.

As a user of several years, the only reason I even knew of the non-proxy integration was trying to understand the warning the framework was giving me, and how to get binary media to work. The reason I could not get it to work, I believe, came down more to not understanding (and taking the time to understand) the AWS side, than confusion with serverless. The non-proxy documentation maps reasonably well to APIG. It would be nice to have an example of how to configure it for serving binary media (maybe in the 'lambda integration' section and not the 'binary media' section?), but I agree with @mnapoli that proxy is the main case- I could even see promoting both as confusing, since most of us don't even know about the non-proxy integration.

**Comment by medikoo** [comment]
> I would expect that to be the default for every project. Is there any reason/use case for documenting things for "non-proxy integration" scenarios?

@mnapoli that's a very good point, and I fully agree that it's best if users just use proxy-integration, and do not bother with non-proxy (we even recommend such an approach in our docs). 

One issue with not documenting non-proxy integration though, is that we have some Framework specific settings for handling binary in those integrations (I think whole `http.response` section applies just to them). So it sort of equals to deprecating it (hiding it under the carpet)

**Comment by mnapoli** [comment]
> One issue with not documenting non-proxy integration though, is that we have some Framework specific settings for handling binary in those integrations (I think whole http.response section applies just to them). So it sort of equals to deprecating it (hiding it under the carpet)

Honestly that sounds fine by me not to invest time creating documentation for that case. If someone in the community wants to contribute a paragraph about that, that's great, but I don't think we should require that/do that right now. If necessary we could also add a small comment in the code to explain that the feature isn't documented (so that if anyone uses it/sees in the code, it's a bit more obvious). But that's just a random idea.

**Comment by simlu** [comment]
This ticket should be re-opened and the docs further updated.

The problem is that setting
```
provider:
  apiGateway:
    binaryMediaTypes:
      - '*/*'
```
will also encode all client requests as binary. This should be detailed in the docs at the very least.

Using the lambda integration is the only way to enable binary support while 
- not requiring the client to send the correct accept header
- not impacting other endpoints

Amazon sucks. But hiding the imposed complexity in the docs just leads to more work.

Here is a related SO answer: https://stackoverflow.com/questions/41037026/aws-api-gateway-binary-output-without-accept-header#answer-41356125

**Comment by mnapoli** [comment]
@simlu what would you add to the documentation?

**Comment by simlu** [comment]
@mnapoli Something along the lines of

> Note that adding `*/*` to `binaryMediaTypes` is necessary to serve binary content independent of the client `Accept` header. 
> ❗ This setting causes `body` on all ApiGateway events to be base64 encoded (see `isBase64Encoded`).

**Comment by obaqueiro** [comment]
Too bad this was closed. We are seeing this bug as well, but trying to add a custom header (Content-Security-Policy) at a response, when using an endpoint with AWS_PROXY:

```
    - http:
        path: '{proxy+}'
        method: ANY
```

Seeing the error:
```
Warning: You're using the AWS_PROXY in combination with response configuration in your function "add". Serverless will remove this configuration automatically before deployment.
Warning: You're using the AWS_PROXY in combination with response configuration in your function "pay". Serverless will remove this configuration automatically before deployment.
Warning: You're using the AWS_PROXY in combination with response configuration in your function "get". Serverless will remove this configuration automatically before deployment.
Warning: You're using the AWS_PROXY in combination with response configuration in your function "create". Serverless will remove this configuration automatically before deployment.
Warning: You're using the AWS_PROXY in combination with response configuration in your function "create". Serverless will remove this configuration automatically before deployment.
...
```

Also there is an unanswered Q by someone else: https://github.com/serverless/serverless/discussions/11942  with the same issue but for `Cross-Origin-Embedder-Policy` headers.
