### ISSUE TITLE
Allow for optional environment variables

### ISSUE THREAD

**Issue by perrin4869** [serverless/serverless#10279]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

This issue is related to https://github.com/serverless/serverless/issues/3491
Currently, setting something like:

```yml
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MYVAR: ${env:MYVAR, null}
```

Will result in `MYVAR` being set to the string `"undefined"` when `process.env.MYVAR` is not present. I think that by explicitly setting `null` when no value is found, the intent is for this environment variable to not be present in the final lambda.

### Proposed solution (optional)

Environment variables that are set to allow `null` explicitly should not be present in the final lambda.

#### Implementation proposal

_(Added by maintainers)_

Serverless Framework clear all null values from the CF template (we allow those values in general logic, but before sending template to AWS we remove them, as it's not supported value type on CF side).

It happens here:
https://github.com/serverless/serverless/blob/d52526bb6059ce20eba341c29ad5a2373c238624/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.js

However, it clears nulls only from top-level properties, when actually we need to traverse all properties deeply. (environment variable settings are located at `Properties.Environment[VAR NAME]`).

**Comment by medikoo** [comment]
@perrin4869 thanks for the report. That's a great call, indeed internals should just ignore `null` values. PR with a fix is welcome!

**Comment by perrin4869** [comment]
@medikoo Nice, thanks! Yeah I'll try to look into this :)
The variable parsing code is not the easiest to walk through though ><;;

**Comment by medikoo** [comment]
@perrin4869 I think issue is not in variables parsing, but in how internally we handle `provider.environment` configuration, when there are properties with `null` value.

**Comment by KrishnaSolo** [comment]
@medikoo Hi! I was wondering if this issue/feature is still relevant. 

My friend and I went through the code and were thinking of adding a fix in [resolve.js](https://github.com/serverless/serverless/blob/master/lib/configuration/variables/resolve.js#L148). The file hosts the function `resolveVariable` which is where the variables get resolved to the actual value or default value. We were thinking of adding a small fix at the [end of the function](https://github.com/serverless/serverless/blob/master/lib/configuration/variables/resolve.js#L221). The fix would check if the property path included `environment` and the value resolved to null. If the check was true, we would throw an error. 

The reasoning we had for modifying this file is that, this is where all the variables get resolved before being added to the `provider.environment` config.

Just wanted to get your thoughts before making a pr!

**Comment by perrin4869** [comment]
Throwing an error wouldn't be a good solution i think. Sometimes the variables are optional, and it is useful to have a way to disable adding them altogether...
It would be more useful to filter out the environment variable instead.

I think I did make the necessary changes to produce the correct CF template, but I didn't yet have time to look into how to add regression tests... 
The resolve route might be better though, because it would enforce the behavior across, for example, in serverless-offline

**Comment by medikoo** [comment]
@KrishnaSolo @perrin4869 As I check there's no issue in variable resolver.

Issue is that `null` value for environment variable setting in configuration is not ignored.

As I've checked problem lies in logic in which we clear all `null` values from the CF template (we allow those values in general logic, but before sending template to AWS we remove them, as it's not supported value type on CF side).

Check:
https://github.com/serverless/serverless/blob/d52526bb6059ce20eba341c29ad5a2373c238624/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.js

It strip nulls but only from top level `Properties`, when I believe we need to traverse all properties deeply. (environment variable settings are located at `Propeties.Environment[VAR NAME]`)

**Comment by KrishnaSolo** [comment]
@medikoo Ah I see, that is a lot cleaner! Just to clarify, should we strip null at **all levels** or just strip null at the `environment` level for the pr? My assumption would be at all levels since as you pointed out AWS does not allow for it, but want to make sure.

**Comment by medikoo** [comment]
> should we strip null at all levels or just strip null at the environment level for the pr?

@KrishnaSolo yes, at all levels :)

**Comment by GurmeharS** [comment]
@medikoo Hi, worked on this with @KrishnaSolo and a few friends as a part of a class assignment to contribute to an open source project.

Submitted a PR here: #10304, please let me/us know what you think!

Thanks 😄

**Comment by perrin4869** [comment]
@KrishnaSolo @GurmeharS thank you so much!

**Comment by perrin4869** [comment]
@medikoo If the null values are inside a `substack` created by `serverless-plugin-split-stacks`, this PR unfortunately doesn't remove those values, because they both work on the `aws:package:finalize` phase... do you have any idea what a good solution would be here?

**Comment by medikoo** [comment]
@perrin4869 in such case it's `serverless-plugin-split-stacks` that's responsible for removing those `null` values. Please open issue at its bug tracker

**Comment by jack-c-tang** [comment]
We found a side effect of this change. I open a discussion for it: https://github.com/serverless/serverless/discussions/10649
Suggestions to support `null` properties for CFN transforms and macros are welcome.
