### ISSUE TITLE
Not all AWS regions supported

### ISSUE THREAD

**Issue by maafk** [serverless/serverless#10298]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Based on [botocore](https://github.com/boto/botocore) documentation, there are two AWS partitions not addressed within the Serverless Framework

- [AWS ISO (US)](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L16723_L16744)
- [AWS ISOB (US)](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L17212_L17230)

There are three regions represented in these partitions that could use some representation within the framework

### Proposed solution (optional)

Include regions in `lib/plugins/aws/provider.js`, and adjust `lib/plugins/aws/utils/getS3EndpointForRegion.js` to get the appropriate S3 endpoints

**Comment by maafk** [comment]
Bad wording on my part. There are two partitions that represent 3 regions that #10299 includes.

Missing regions are [here](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L16738), [here](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L16741) and [here](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L17227).

**Comment by medikoo** [comment]
@maafk thanks for explanation, will look into PR!
