### ISSUE TITLE
[customRole] should get ARN automagically (from variable?)

### ISSUE THREAD

**Issue by BerndWessels** [serverless/serverless#1031]
I need custom roles for most of my lambda functions.

It seems that at the moment the only way to do that is to manually put the ARN into the `s-function.json` `customRole` property.

But that means manual work every time after the role got created. It would be better if I could add the creation of the role in the `s-resources-cf.json` and retrieve the ARN from the `Outputs` and point the `customRole` to it.

Is there already a way to do that or can you please add it as an important enhancement?

Thanks
Bernd

**Comment by JamieCressey** [comment]
+1

**Comment by JamieCressey** [comment]
In actual fact, I think you can. `s-resources-cf.json` already outputs the default role ARN as `IamRoleArnLambda`, so you just need to add your new role into the outputs section:

```
        "YourNewIamRoleLambda": {
            "Description": "ARN of your new lambda IAM role",
            "Value": {
                "Fn::GetAtt": [
                    "YourNewIamRoleLambda",
                    "Arn"
                ]
            }
        }
```

**Comment by BerndWessels** [comment]
@JamieCressey yes you are kind of right.
`Fn::GetAtt` actually only works in `s-resources-cf.json` and can be used to add additional output variables.
In `s-function.json` you can then use them like this `"customRole": "${iamRoleArnLambdaAuthUserSignIn}"`.

There are 2 problems I have with this.
1. Since I have a lot of these output variables the `s-resources-cf.json` becomes pretty messy and error prone.
2. Since these output variables are stored in the `_meta` folder and that folder does not get checked into Git, you cannot share a project with existing resources via Git with your colleagues.

**Comment by JamieCressey** [comment]
I'm with you on making it simpler. I tend to restrict my Lamba functions to roles which only have the necessary permissions, rather than a one for all approach.

As for point 2, I think meta sync covers that requirement: https://github.com/serverless/serverless-meta-sync.

**Comment by BerndWessels** [comment]
@JamieCressey thanks, yes I am testing the meta sync plugin at the moment to see if it will work in an enterprise environment with 200 developers working on the same dev and prod environment.

**Comment by flomotlik** [comment]
@BerndWessels we're currently planning out V1 of Serverless including much better support for environment variables. Happy to chat sometime about your needs there.

This issue should definitely be solved.

**Comment by BerndWessels** [comment]
@flomotlik Great thanks. Are there docs about the changes you are going to make for V1? Would like to give some input or even some contributions.

**Comment by flomotlik** [comment]
@BerndWessels sorry for the delayed response here. If you look through the issues and milestones in this repo or on our blog you can find all of this. This issue is also resolved through Cloudformation
