### ISSUE TITLE
Remove installDependencies from Runtime and subclasses

### ISSUE THREAD

**Issue by mhahn** [serverless/serverless#1032]
https://github.com/serverless/serverless/search?utf8=%E2%9C%93&q=installDependencies

is never actually invoked anywhere.

It seems from reading through some other issues that serverless does not actually manage any dependencies and only does this via uploading the content within the handler directory specified.

if this is the case, i think these methods should be removed because they're confusing. also, happy to help with the documentation to make this clear.

**Comment by flomotlik** [comment]
Thanks for reporting this. We're currently reimplementing a lot of our system and this is a good time to remove them. I'm not sure yet when this is going to happen exactly though. I'll put this into our backlog to come back to it in the future.
