### ISSUE TITLE
Tests: Refactor test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#10331]
_Most of the tests that currently cover core functionalities depend heavily on (and sometimes test) internal implementation characteristics. While they should be testing whether the given implementation produces desired outcome (treating its implementation more as a black box)._

_Current state of things is problematic for eventual internal improvements and refactors which occasionally we want to introduce, as in most of such cases proposed improvements need to be accompanied with counterproductive numerous updates to tests which are covering otherwise not altered functionalities ._

_At some point, we've introduced a new (black box based) way of testing the internals. It's through `runServerless` utility, which allows us to create a natural (as in real-world) `serverless` instance, and inspect the produced outcome for chosen command. More details here: https://github.com/serverless/serverless/tree/master/test#unit-tests_

--- 

This is issue is about refactoring [test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js](https://github.com/serverless/serverless/blob/654c50792ace1ee675fe5d6843faaafe1179bc25/test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js) to `runServerless` based variant.

It's needed, so we cleanly move forward with https://github.com/serverless/serverless/issues/8396

To make refactor relatively easy:
- Spec for new tests is fully defined and is already committed in the context of [test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js](https://github.com/serverless/serverless/blob/654c50792ace1ee675fe5d6843faaafe1179bc25/test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js) file. It's in the scope of this _describe_ block: https://github.com/serverless/serverless/blob/654c50792ace1ee675fe5d6843faaafe1179bc25/test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js#L116-L185
- Each test slot indicates which test it is about to replace
- It is indicated where (and how many) exactly `runServerless` runs are expected to happen, against which fixture and command they should be based
- Necessary hints are provided

With the refactor [test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js](https://github.com/serverless/serverless/blob/654c50792ace1ee675fe5d6843faaafe1179bc25/test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js) file should be removed completely

**Comment by eli6** [comment]
Hello, I would like to try this as my first issue, would that be ok?

**Comment by medikoo** [comment]
@eli6 that'll be great. We look forward the PR!
