### ISSUE TITLE
Fn::GetAtt not working in s-function.json

### ISSUE THREAD

**Issue by BerndWessels** [serverless/serverless#1034]
Hi
I think `customRole` is not very useful when we can't use `Fn::getAtt` instead of a hardcoded `ARN`.

This would be much better:

    "customRole": {
        "Fn::GetAtt": [
          "IamRoleLambdaAuthUserSignUp",
          "Arn"
        ]
      },

I can make a PR once someone tells me how to enable the usage of `Fn:getAtt` in `s-function.json`.

It should be easy to change, it is most likely in `CodeDeployLambda.js

     193:      Role:         _this.functionPopulated.customRole ? _this.functionPopulated.customRole : _this.project.getVariablesObject(_this.evt.options.stage, _this.evt.options.region).iamRoleArnLambda, /* required */

**Comment by HyperBrain** [comment]
In my opinion everything related to CF functionality should belong to the `s-resources-cf.json`. Couldn't you just get your custom role name as _OutputVar_ in your CF template? Then it will be automatically added to your project variables and can be referenced like this: `"customRole": "${myCustomRoleName}"`

**Comment by BerndWessels** [comment]
@HyperBrain That would do to, even though it feels a bit clumsy having to declare all these output values - but would be a good enough workaround for a start.

Checking the code

    193:      Role:         _this.functionPopulated.customRole ? _this.functionPopulated.customRole : _this.project.getVariablesObject(_this.evt.options.stage, _this.evt.options.region).iamRoleArnLambda, /* required */

and just having tried `"customRole": "${myCustomRoleName}"` which failed

    Serverless:   auth-user-signin: 1 validation error detected: Value '${IamRoleArnLambdaAuthUserSignIn}' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+  
    Serverless:   auth-user-signup: 1 validation error detected: Value '${IamRoleArnLambdaAuthUserSignUp}' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+  
    C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };

I guess it needs a bit of work to add this feature.

I will try to make a PR for that unless you guys think there is another solution!?

**Comment by BerndWessels** [comment]
@HyperBrain Oh wow, that's weird. I just figured why `"customRole": "${MyCustomRoleName}"` failed.

In `s-resources-cf.json` I have

    "Outputs": {
        "MyCustomRoleName": ...

But in `s-variables-dev-useast1.json` it created

    "myCustomRoleName": ....

So to it camelized the variable name.

So `"customRole": "${MyCustomRoleName}"` fails
but `"customRole": "${myCustomRoleName}"` succeeds.

Which means everything is goodish and you can close this issue.

Just find it weird that it camelizes the output variable names. Is that intended? Might need some documentation.

**Comment by HyperBrain** [comment]
@BerndWessels Yes, now I remember. It was indeed me who introduced the camelization... Maybe it wasn't the greatest idea as I myself also stumbled over that.

**Comment by HyperBrain** [comment]
PS: you can close the issue as you are its owner ;-)

**Comment by BerndWessels** [comment]
@HyperBrain OK, I am happy for now, thanks.
