### ISSUE TITLE
Cognito sync events

### ISSUE THREAD

**Issue by aexmachina** [serverless/serverless#1035]
Is it possible to use Serverless to create and manage a Lambda function with [Cognito Sync Trigger](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-events.html) event source?

**Comment by eahefnawy** [comment]
We currently don't directly support Cognito as an event source, however that only means that you can't use Serverless to manage/deploy this event source config. What Serverless can do for you now is manage the lambda function and logic that will handle that event, and then you can attach that event source in other means (maybe CF?!)

Hope this helps 😊

**Comment by aexmachina** [comment]
Thanks @eahefnawy. Any tips or suggestions on how I'd do that with CF would be really appreciated, both by me (I'm a CF noob), and by others who may have the same need in the future. Thanks!

**Comment by eahefnawy** [comment]
Yikes, I just researched this. It seems that Cognito is not supported as CF templates. So you can't do it with CF. However I think u can do it manually with the AWS Console.

Sorry about that, I hope we can make this easier for you in the future 😞

**Comment by aexmachina** [comment]
No worries, thanks for investigating.​

**Comment by HyperBrain** [comment]
Just tested with the console. It seems not possible to select a lambda alias as event target. Only the lambda (I think $LATEST) is connected.

**Comment by flomotlik** [comment]
We are interested in Cognito support in the future, but its not on our immediate timeline. As it looks like @HyperBrain and @eahefnawy answered the question I'm going to close this one.
