### ISSUE TITLE
Member must have length less than or equal to 51200 (CF template is too large after upgrading)

### ISSUE THREAD

**Issue by dannypaz** [serverless/serverless#10352]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After upgrading from 2.59 to 2.69, I started receiving errors on one of my services ` 1 validation error detected: Value <MY SUPER RIDICULOUS LARGE CF TEMPLATE> at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200`. Is there a work around to allow me to upload the CF template to s3 to get around this limitation? Can anyone point me to the code change that changed how templates were uploaded?

I need the changes in 2.69 because it fixes s3 bucket issues w/ deleting stacks AND fixes non-existent s3 bucket issues

### Service configuration (serverless.yml) content

```yaml
n/a
```

### Command name and used flags

sls deploy

### Command output

```shell
n/a
```

### Environment information

```shell
2.69.0
```

**Comment by medikoo** [comment]
@dannypaz please respect all issue template questions. We cannot diagnose the problem unless we have complete answers to all questions

**Comment by dannypaz** [comment]
@medikoo this is probably better off as a Q. going to move it there
