### ISSUE TITLE
References to context.done() should be replaced by callbacks

### ISSUE THREAD

**Issue by ddehghan** [serverless/serverless#1036]
References to the old way of calling context should be changed to the new 4.3 runtime way. As a newbie to Serverless it caused a lot of confusions. 

```
// Old way (Node.js runtime v0.10.42).
context.done(null, 'Success message');
// New way (Node.js runtime v4.3).
context.callbackWaitForEmptyEventLoop = false;
callback(null, 'Success message');
```

Keep up the great work guys.

**Comment by Whoaa512** [comment]
Just a note, it should be `callbackWaitsForEmptyEventLoop`. Where `Wait` has an `s`

**Comment by flomotlik** [comment]
@ddehghan I was only able to find this in this [one nodejs.js file]( https://github.com/serverless/serverless/blob/master/lib/templates/nodejs/nodejs.js)

This file is still targeting older versions of Node so we have to use the old syntax. Or did you mean in another file? I will close this issue for now as it seems to me this isn't really a bug, but please let me know and reopen in case this is a misunderstanding on my part.
