### ISSUE TITLE
Custom resource generation upgrade from node 12 to 14

### ISSUE THREAD

**Issue by bxjw** [serverless/serverless#10374]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

In serverless 3, it looks like custom resources [will still be generated in node 12](https://github.com/serverless/serverless/blob/013c740025f1903d38cb30cb3eec67a4e47c28c6/lib/plugins/aws/customResources/index.js#L177). Since we are planning to continue using a custom EventBridge, we'd like this to be upgraded before node 12 hits end of life.

### Proposed solution (optional)

Update the runtime to nodejs14.x

**Comment by medikoo** [comment]
@bxjw that's a good point. We'll be happy to accept a PR against v3 branch that adjusts that!

**Comment by bxjw** [comment]
thanks, done! and uh sorry about the closed PRs, accidentally junked up my commit history
