### ISSUE TITLE
sls region remove - spinner doesn't stop even though action has finished executing

### ISSUE THREAD

**Issue by EchoZulu** [serverless/serverless#1039]
os windows7
sls 0.5.5 (without packages)

I have eu-central regions with lambdas, endoints and two stages (dev/prod).
Then I create new region with one stage (prod).

Finaly when I try to remove new region, process never ends and serverless keep running.
(CloudFormation is successfully deleted)

> sls region create
Serverless: Select an existing stage for your new region:
    1) dev
  > 2) prod
Serverless: Select a new region for your stage:
  > us-east-1
    us-west-2
    eu-west-1
    eu-central-1
    ap-northeast-1
Serverless: Creating region "us-east-1" in stage "prod"...
Serverless: Deploying resources to stage "prod" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully deployed "prod" resources to "us-east-1"
Serverless: Successfully created region "us-east-1" within stage "prod"

> sls region remove
Serverless: Select an existing stage:
    1) dev
  > 2) prod
Serverless: Removing region "us-east-1" in stage "prod"...
Serverless: Removing functions in "prod" from the following regions: us-east-1
Serverless: Removing endpoints in "prod" to the following regions: us-east-1
Serverless: Removing endpoints in "prod" to the following regions: us-east-1
Serverless: Removing endpoints in "prod" to the following regions: us-east-1
Serverless: ------------------------
Serverless: Failed to remove the following functions in "prod" from the following regions:
Serverless: us-east-1 ------------------------
Serverless:   test: Cannot read property 'id' of undefined
Serverless:   root-test: Cannot read property 'id' of undefined
Serverless: Removing resources from stage "prod" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully removed "prod" resources from "us-east-1"
Serverless: Successfully removed region "us-east-1" within stage "prod"
Serverless: /

**Comment by eahefnawy** [comment]
hmmm interesting ... it's probably just the loading spinner that we forgot to stop, not the process itself. So I wouldn't worry if resources and region is indeed removed in AWS.

Will look into it. Thanks for reporting! 😊

**Comment by eahefnawy** [comment]
@EchoZulu I just tried to reproduce this, but wasn't able to :/ ... is this still an issue for you? Maybe it's because you're on windows? Although I don't think OS should matter in this case.

I'd highly appreciate it if you could try to reproduce again. Maybe in a brand new project and stage?

Thanks a lot for keeping patient with us @EchoZulu 😊

**Comment by pmuens** [comment]
Thanks for reporting @EchoZulu 
I just tried to reproduce the bug but was not successful (Windows 7 x86 machine, Serverless v0.5.5).
@EchoZulu Would be really great if you can try to reproduce it again.

/cc @eahefnawy

**Comment by EchoZulu** [comment]
os Windows 7 x64, sls -v 0.5.5
Still keep spinning

Actions: 
> sls project create
> cd sls-empty-test
> sls function create 
> sls dash deploy     (into eu-central-1)
> sls region create   ( eu-west-1)
> sls region remove   ( eu-west-1 )

Complete log:

>
>> sls -v
>0.5.5
>
>echoZ@echoZ02 C:\_test_labs
>> sls project create
>
>Serverless: Initializing Serverless Project...
>Serverless: Enter a name for this project:  (serverless-s1v23a) sls-empty-test
>Serverless: Enter a new stage name for this project:  (dev) dev
>Serverless: For the "dev" stage, do you want to use an existing Amazon Web Services profile or create a new one?
>  > Existing Profile
>    Create A New Profile
>Serverless: Select a profile for your project:
>  > proj-aws-admin
>Serverless: Creating stage "dev"...
>Serverless: Select a new region for your stage:
>    us-east-1
>    us-west-2
>    eu-west-1
>  > eu-central-1
>    ap-northeast-1
>Serverless: Creating region "eu-central-1" in stage "dev"...
>Serverless: Deploying resources to stage "dev" in region "eu-central-1" via Cloudformation (~3 minutes)...
>Serverless: Successfully deployed "dev" resources to "eu-central-1"
>Serverless: Successfully created region "eu-central-1" within stage "dev"
>Serverless: Successfully created stage "dev"
>Serverless: Successfully initialized project "sls-empty-test"
>
>
>> cd sls-empty-test
>
>echoZ@echoZ02 C:\_test_labs\sls-empty-test
>> sls function create
>Serverless: Enter a new function name to be created in the CWD:  test
>Serverless: Please, select a runtime for this new Function
>  > nodejs4.3
>    python2.7
>    nodejs (v0.10, soon to be deprecated)
>Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
>  > Create Endpoint
>    Create Event
>    Just the Function...
>Serverless: Successfully created function: "test"
>
>echoZ@echoZ02 C:\_test_labs\sls-empty-test
>> sls dash deploy
>
>
>Serverless: Select the assets you wish to deploy:
>    test
>      function - test
>      endpoint - test - GET
>    - - - - -
>  > Deploy
>    Cancel
>
>Serverless: Deploying the specified functions in "dev" to the following regions: eu-central-1
>Serverless: ------------------------
>Serverless: Successfully deployed the following functions in "dev" to the following regions:
>Serverless: eu-central-1 ------------------------
>Serverless:   test (sls-empty-test-test): arn:aws:lambda:eu-central-1:648208177669:function:sls-empty-test-test:dev
>
>Serverless: Deploying endpoints in "dev" to the following regions: eu-central-1
>Serverless: Successfully deployed endpoints in "dev" to the following regions:
>Serverless: eu-central-1 ------------------------
>Serverless:   GET - test - https://yywzotxl8f.execute-api.eu-central-1.amazonaws.com/dev/test
>
>echoZ@echoZ02 C:\_test_labs\sls-empty-test
>> sls region create
>Serverless: Select a new region for your stage:
>    us-east-1
>    us-west-2
>  > eu-west-1
>    ap-northeast-1
>Serverless: Creating region "eu-west-1" in stage "dev"...
>Serverless: Deploying resources to stage "dev" in region "eu-west-1" via Cloudformation (~3 minutes)...
>Serverless: Successfully deployed "dev" resources to "eu-west-1"
>Serverless: Successfully created region "eu-west-1" within stage "dev"
>
>echoZ@echoZ02 C:\_test_labs\sls-empty-test
>> sls region remove
>Serverless: Select a region to remove:
>    eu-central-1
>  > eu-west-1
>Serverless: Removing region "eu-west-1" in stage "dev"...
>Serverless: Removing functions in "dev" from the following regions: eu-west-1
>Serverless: Removing endpoints in "dev" to the following regions: eu-west-1
>Serverless: ------------------------
>Serverless: Failed to remove the following functions in "dev" from the following regions:
>Serverless: eu-west-1 ------------------------
>Serverless:   test: Cannot read property 'id' of undefined
>Serverless: Removing resources from stage "dev" in region "eu-west-1" via Cloudformation (~3 minutes)...
>Serverless: Successfully removed "dev" resources from "eu-west-1"
>Serverless: Successfully removed region "eu-west-1" within stage "dev"
>Serverless: /

**Comment by flomotlik** [comment]
@EchoZulu is this only happening for region remove?
