### ISSUE TITLE
SLS does not distinguish btw. method and integration request parameters

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#1042]
AWS API Gateway distinguishes between method and integration parameters. I will explain the two so that there is a common understanding:

#### Method request parameters
Method request parameters are parameters that are received from the caller of the endpoint and may be path, query or header parameters, depending on the mechanism how they are sent. In APIG REST API these are named as `method.request.{type}.{name}`. They only define the INPUT side of the method.

#### Integration request parameters
Integration request parameters are parameters that are sent to the integration (backend) that it called from APIG. In APIG REST API these are named `integration.request.{type}.{name}`. They only define the OUTPUT side of the APIG (towards the endpoint of the defined integration, may it be lambda, a proxied URL or an AWS service).

### Use in APIG
As they define different things, both kinds of parameters can be combined depending on the use case you have. Therefore the APIG REST API lets you define them independently.
On creation of a method the `requestParameters` property defines the method request parameters and specifies if the parameter is mandatory or not.
If you have a Lambda type integration that's all you need, as Lambdas do not accept parameters but only a body. For other integration types (like HTTP proxy or AWS services) that accept parameters (headers,query or path) the request parameters can be mapped to integration parameters.

### Handling in Serverless
Serverless does not support exactly the Lambda case when defining request parameters as well as it does not support declaring parameters as optional.

#### Example: Lambda call with parameter (here: testparam)
If you have en endpoint, that should accept a query parameter, your APIG definition should only have a method request parameter defined: `method.request.querystring.testparam` and no integration parameter as we will put the received parameter into the POST body via a template mapping.

The problem now is, that we cannot define a pure method parameter with serverless. The `s-function.json` allows only parameter mappings through the use of the `requestParameters` template, e.g.
```
      "requestParameters": {
        "integration.request.querystring.testparam": "method.request.querystring.testparam"
      }
```
Of course that allows us to intercept the parameter with `$input.params('testparam')` in our mapping template, but as a parameter mapping is created, the parameter is also sent out when the POST is submitted. Also in the console you see the useless parameter.

The second problem is, that you cannot define optional parameters with that approach.

### Demanded change
Serverless should distinguish between method and integration parameters (request as well as response) and should support rqeuired/optional flags for the method request parameters.

### Possible solution
A non breaking change should be preferred in my opinion, that would allow a smooth transition to a correct implementation.
The `requestParameters` property could be reused, so that the existing configurations still work, and the transitioned definitions just added.

```
      "requestParameters": {
          "method": {
             "method.request.querystring.requiredparam": true,
             "method.request.querystring.optionalparam": false
          },
          // This is optional: here we map the incoming param to a header on the output side
          "integration": {
            "integration.request.header.requiredparam": "method.request.querystring.requiredparam"
          }
      }
```

The `method` and `integration` objects can be missing for endpoints without parameters, or for method only parameters only method could be there.

Comments welcome

**Comment by eahefnawy** [comment]
wow I love it when you open an issue! Always organized and easy to understand 😊 ... I think the solution you proposed makes the most sense. Hmmm I wonder why we didn't do that from the beginning!

**Comment by flomotlik** [comment]
Not an issue any more in V1 due to Cloudformation deployment. Closing
