### ISSUE TITLE
AWS Custom Resource Lambda still using NodeJS 12.x (NodeJS v12 is EOL 2022-04-30)

### ISSUE THREAD

**Issue by hberes** [serverless/serverless#10432]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The custom resource lambda (*-custom-resource-apigw-cw-role) created automatically via serverless has a hardcoded runtime of "nodejs12.x":

https://github.com/serverless/serverless/blob/f8937723967537eb0c0b739b50c5861386722393/lib/plugins/aws/customResources/index.js#L177

NodeJS v12 is EOL on 2022-04-30:

https://nodejs.org/en/about/releases/

It would be nice if this lambda runtime was configurable via serverless.yml (or leveraged the configured provider runtime) so applications weren't dependent on a new serverless release.  However, at a minimum, the runtime should be updated to nodejs14.x ahead of v12 EOL.

This currently blocks completely upgrading to NodeJS v14.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.70.0 (local)
Plugin: 5.5.2
SDK: 4.3.0
Components: 3.18.1
```

**Comment by medikoo** [comment]
@hberes in v3 branch (to be published by end of this month), it's already bumped to `nodejs14.x` -> https://github.com/serverless/serverless/blob/7cd71b9a789bbac4cadf53de38951bfd179265cc/lib/plugins/aws/customResources/index.js#L177
