### ISSUE TITLE
Endpoint deploy should also support function names as "names" parameter

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#1044]
### Problem
Currently `sls endpoint deploy <names>` only supports the endpoint resource's path as name parameter. E.g. if you have a resource `/v1/tickets/{ticketnumber}` where GET is linked to lambda `getTickets` it is only allowed to specify `sls endpoint deploy /v1/tickets/{ticketnumber}~GET` to deploy the GET method.

If you follow a strict "separation of concerns" and security based approach where you have one lambda that handles all retrievals of data (with the permissions set accordingly) for multiple APIG paths and one lambda that handles data writes for these paths, you would like to specify the lambda name as endpoint name in the deploy command, to have all APIG paths deployed that refer to the redeployed lambda if you did some changes.

### Example
Let's have the following system definition:
```
/v1/tickets/{ticketnumber}
    GET -> getTicketsLambda
    DELETE -> changeTicketsLambda
/v1/tickets
    GET -> getTicketsLambda
    POST -> changeTicketsLambda
```

If we now apply changes to the `changeTicketsLambda` we would of course like to redeploy all endpoint methods that refer to the lambda. With the current implementation we have to remember or lookup all paths where the lambda is used and redeploy them each manually.
If you have an API with a lot of endpoints I'd bet that you miss one! (Of course you can redeploy the whole API, but for testing changes on a `test` stage every developer involved would kill you if he has to redeploy everything - and maybe overwrite other endpoints in the stage where other people are currently working on). 

### Proposal
A more failsafe approach here would be that you can just `sls endpoint deploy changeTicketsLambda` and Serverless would redeploy the methods `/v1/tickets/{ticketnumber}~DELETE` and `/v1/tickets~POST`.

Comments welcome

**Comment by HyperBrain** [comment]
CC @eahefnawy, @ac360

**Comment by eahefnawy** [comment]
Agreed! 👍 👍

**Comment by emotional-engineering** [comment]
Please look, will it be able to solve the issue?
https://github.com/emotional-engineering/serverless/commit/283d26a0e56d00ff8015d569c7a0acba2f58dfed

**Comment by flomotlik** [comment]
@HyperBrain the approach we want to do in the future with using Cloudformation to set up the API Gateway and functions would resolve this? Because we don't have a separate endpoint deploy any more?

**Comment by HyperBrain** [comment]
Yes, could work. Nevertheless there might be the need of some virtual linkage to trigger a redeploy of the affected endpoints only. But for now this is not necessary,
