### ISSUE TITLE
ssm nested variable interpolation/reference does not work for with 'opt' prefix

### ISSUE THREAD

**Issue by bitsofinfo** [serverless/serverless#10446]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.1.0
     Framework Version:         2.70.0 (local)
     Plugin Version:            5.5.2
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

I'm doing a `serverless deploy --package packages/my-test-app-mp-po_0.0.3_qa__999122_us-west-2 --stage qa --region us-west-2`

serverless.yaml in the package:
```
  apiKeys:
    - name: ${self:service.name}-${opt:stage, 'dev'}-apiKey
      value: ${ssm:/aws/reference/secretsmanager/${self:service.name}/${opt:stage}/apiKey}
```

error message:
```
 Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.apiKeys.0.value": Value not found at "opt" source
```

**Comment by medikoo** [comment]
@bitsofinfo can you please prepare a minimal test case that doesn't involve any plugins and reproduce that issue. We also need a complete `serverless.yml` content as requested in a template.

Simplest form of testing that resolution works without plugins will be `sls print` command
