### ISSUE TITLE
Reconcile event name generation

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#1045]
`sls event deploy -s [stage] -r [region] -a`
and
`sls event remove -s [stage] -r [region] -a`

generate event names differently.  deploy appends the stage name (great!).  remove does not.

potential relevant project state: there are many functions but only one defined event.

**Comment by eahefnawy** [comment]
Nice catch!!!

**Comment by eahefnawy** [comment]
@erikerikson I just pushed a fix for the schedule event remove that should fix this. I think schedule events is the only one affected by this. Could you confirm? 😊

**Comment by erikerikson** [comment]
Confirmed fixed in latest.  Thanks @eahefnawy !
