### ISSUE TITLE
Report project-specific plugins in the help screen

### ISSUE THREAD

**Issue by akalra** [serverless/serverless#1047]
This came out of the discussion of #657 -- since core plugins and project-specific plugins appear visually identical in the contexts and actions displayed in the help screen, there's some concern that new users might not know where to ask for help for specific challenges they're having.

Keep in mind that the way plugins are loaded is changing:
https://github.com/serverless/serverless/pull/968/commits/5b8d249d807e44698c0d11da231cc01d2372666d

Thanks!

Ankur

**Comment by akalra** [comment]
I've a potential implementation in my branch: https://github.com/akalra/serverless/tree/report-loaded-plugins

This looks like this in the classic UI: 
![image](https://cloud.githubusercontent.com/assets/509798/14764455/3b11b34c-0986-11e6-9502-c26d54cdce39.png)

And like this in the new UI proposed in #1064:
![image](https://cloud.githubusercontent.com/assets/509798/14764462/a93ddbb6-0986-11e6-9baa-995a2c8b8258.png)

Thoughts?

Ankur

**Comment by eahefnawy** [comment]
could we maybe color all the plugin contexts/actions in green or red and just have a message that says "actions in green are installed plugins" or something like that. What we have above is nice, but it doesn't tell the user which command belongs to each custom plugin. What you think?

**Comment by akalra** [comment]
Hi @eahefnawy -- 

We can, but I'm not actually sure that's really that useful. This was discussed briefly in #657 with @pmuens -- I feel that coloring context/action by provider (core vs plugin) isn't that useful a distinction to the user unless they're looking for help with it. For day-to-day use, it might just be a visual distraction.

Open to exploring alternatives. My current perspective is that the contexts/actions screen is _your palette of things you can do_ , and where they come from (written by serverless team and shipped in core, written by serverless team but not shipped in core, written by someone else entirely, etc) is not that meaningful to _getting stuff done_.

The only caveat is if one of them isn't working, we want to make sure you ask for support in the right places. So the idea of the single line in the help screen is that it is enough to trigger your memory about whether your action is from core or not.

But totally open to alternative perspectives here. Thoughts?

Ankur

PS: Coloring actions/contexts by core/plugin will require refactoring some things, since the code today doesn't treat them any differently (and in particular, doesn't remember which contexts/actions comes from where).

**Comment by pmuens** [comment]
Really like the decent mentioning of the installed PlugIns.

I too think that coloring of the commands might be a little bit distracting and unclear for users who don't know what the coloring means. But I also think that a separation between core and PlugIn commands might be interesting.

I would propose to separate core functionality and PlugIn commands in the way the at first the core commands are shown, followed by a small space and then the PlugIn commands.

**Comment by eahefnawy** [comment]
@pmuens that might be a bit hard for plugins that adds actions to existing context. ie. `sls endpoint deploy` is core while `sls endpoint <whatever>` is not.

I think @akalra is right, maybe we don't need that specially if it's gonna be complex in code since as @akalra we don't really know which commands are from where.

**Comment by pmuens** [comment]
@eahefnawy Yep. That was something I was not thinking about.

I would suggest smth. like this:

```
endpoint ............ deploy, remove
dash ............ deploy, summary
stage ............ create, remove
...
----------------------------------
Project specific plugins loaded: foo, bar
endpoint ............ baz
```

So that you have the separation of serverless commands and plugin commands.

Hope that this outlines the idea correctly.

**Comment by akalra** [comment]
Hey folks --

Looking to move forward here, what would you suggest as the best way to come to a resolution here? Do we need to loop in more folks, or get on a call, or something else?

I've no horse in this race, but I do want to write the code for whatever we settle on and move on to the next thing ;)

Thanks!

Ankur

**Comment by eahefnawy** [comment]
@akalra I think what you have now is great! I don't see a reason to make it more complex. Thanks a lot for your contribution 😊 

Sorry for the late reply. Hope you had a great weekend!
