### ISSUE TITLE
"Cannot find module 'esbuild'" error when installing `aws-nodejs-typescript` template

### ISSUE THREAD

**Issue by ThomasAribart** [serverless/serverless#10470]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When installing the `aws-nodejs-typescript` template, after running `yarn sls deploy`, I get the following error:

```
Cannot find module 'esbuild'
```

I simply fixed it by installing esbuild, but it hampers the dev experience.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by medikoo** [comment]
@ThomasAribart I assume you've used `sls create`. If that's the case it doesn't do `npm install` which is needed for templates that require dependencies to be installed.

Note we no longer recommend `sls create` for new projects setup. Instead please use `sls` interactive setup, it ensures that dependencies are installed and retrieves templates from https://github.com/serverless/examples/ repository

**Comment by ThomasAribart** [comment]
Yes I did use `sls create` but did run `npm install` as well :)

**Comment by medikoo** [comment]
@ThomasAribart that's a good point, it's just `serverless-esbuild` that was added, but `esbuild` is needed  as well.

We'll be happy to accept PR that adds that (although we're about to treat those templates as deprecated)

**Comment by pgrzesik** [comment]
Looks like recently `serverless-esbuild` plugin changed the approach and now has `esbuild` in `peerDependencies`: https://github.com/floydspace/serverless-esbuild/commit/11d8726997fb4ddbade1dee455af895ef0ba56b7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 

I think it should work fine with `npm@7` but indeed can cause troubles for `npm@6` and lower.

**Comment by iaforek** [comment]
I can confirm same issue.

My environment:
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
```

**Steps to reproduce**:

```
sls create -t aws-nodejs-typescript
npm install
sls deploy
```

GIves: `Error: Cannot find module 'esbuild'`

Additionally:

> Note we no longer recommend sls create for new projects setup. Instead please use sls interactive setup, 

Running just `sls` gives me following options (note **no** typescript in the list):

```
 What do you want to make? (Use arrow keys)
❯ AWS - Node.js - Starter 
  AWS - Node.js - HTTP API 
  AWS - Node.js - Scheduled Task 
  AWS - Node.js - SQS Worker 
  AWS - Node.js - Express API 
  AWS - Node.js - Express API with DynamoDB 
  AWS - Python - Starter 
  AWS - Python - HTTP API 
  AWS - Python - Scheduled Task 
  AWS - Python - SQS Worker 
  AWS - Python - Flask API 
  AWS - Python - Flask API with DynamoDB 
  Other
```

Interestingly, when selecting `Other` I get 

```
Run “serverless create --help” to view available templates and create a new project from one of those templates.
```
