### ISSUE TITLE
How to install serverless command on arm64 arch (for e.g Apple M1 Devices)

### ISSUE THREAD

**Issue by rishabhtexau** [serverless/serverless#10477]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I was trying to install the server less command on my M1 Mac but it was throwing an erro
<img width="1080" alt="Screenshot 2022-01-10 at 12 03 23 PM" src="https://user-images.githubusercontent.com/97147902/148726162-57a2d450-8948-41cc-ab2f-8e7a4e2adc57.png">
r

### Proposed solution (optional)

You have to just release a version for arm64 devices.

**Comment by pgrzesik** [comment]
Hello @rishabhtexau - this has been addressed but the script wasn't update - I'm on it, thanks for reporting

**Comment by pgrzesik** [comment]
Hello @rishabhtexau - it should be fixed now
