### ISSUE TITLE
how to start with existing project.

### ISSUE THREAD

**Issue by smkamranqadri** [serverless/serverless#1049]
when i share my code with other person and how do they auth and deploy because when they deploy it gives below errors.

Serverless: Choose a Region in this Stage: 
/usr/local/lib/node_modules/serverless/lib/utils/cli.js:386
      if (Select.state.choices[Select.state.index - 1].action
                                                      ^

TypeError: Cannot read property 'action' of undefined
    at ReadStream.keypressHandler (/usr/local/lib/node_modules/serverless/lib/utils/cli.js:386:55)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKey (/usr/local/lib/node_modules/serverless/node_modules/keypress/index.js:406:12)
    at ReadStream.onData (/usr/local/lib/node_modules/serverless/node_modules/keypress/index.js:48:14)
    at emitOne (events.js:90:13)
    at ReadStream.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at TTY.onread (net.js:534:20)

**Comment by Josh-a-e** [comment]
how exactly have you "shared" your code? via a git repo? it may well be due to the `_meta` folder not getting committed (as it's often full of secrets): http://docs.serverless.com/docs/project-structure#section-meta-data .

I guess it's up to you whether or not you want them to be able to use the same AWS account as you (then give them your secrets) or if you want your collaborator to just share the code (have them generate their own secrets).

**Comment by smkamranqadri** [comment]
yes they have their own id & key. also share with github.

so how do they get start. because all of the cmds are suppose to create project/ function.

**Comment by theburningmonk** [comment]
The way we have approached this in our team is to:
* check in the _meta folder
* any sensitive info (API keys, connection strings, etc.) in the env vars are encrypted using a KMS key in that account
* developers are added as key users for that key so they can run the code locally
* in the `s-resources-cf.json`, give the Lambda function permission to kms:decrypt
* in the handler code, where appropriate it'll decrypt (the first time) and store the sensitive info in a variable outside the handler so it's cached

**Comment by stefanullinger** [comment]
Maybe the [Meta Sync](https://github.com/serverless/serverless-meta-sync) plugin can help?

**Comment by smkamranqadri** [comment]
noted with thx.
