### ISSUE TITLE
Failing yarn audit 

### ISSUE THREAD

**Issue by samjarman** [serverless/serverless#10497]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When using the latest `serverless`, a run of `yarn audit fails, citing this advisory: https://www.npmjs.com/advisories/1004946  
![Screen Shot 2022-01-13 at 1 31 59 pm](https://user-images.githubusercontent.com/343172/149255526-79789c58-e70b-4cf2-9594-cb5f6fd85b81.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.71.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```

**Comment by samjarman** [comment]
@medikoo thanks for the reply. Is 3.0.0 a big upgrade? Will it be backported to 2.x?

**Comment by medikoo** [comment]
> @medikoo thanks for the reply. Is 3.0.0 a big upgrade? Will it be backported to 2.x?

@samjarman it's not a big upgrade, most services should work as they work (just ensure all deprecations warnings are addressed).

At this point we do not plan to backport this change to 2.x (note in v2 it's mostly caused by Component CLI being one of the dependencies, in v3 it's not the case)

**Comment by samjarman** [comment]
Awesome, thank you! I'll keep an eye out :)

**Comment by medikoo** [comment]
As a side note v3 was released on Jan 27th 2022, and v2 (which shared the issue) is no longer maintained
