### ISSUE TITLE
pnpm fails to install latest serverless version

### ISSUE THREAD

**Issue by lvkins** [serverless/serverless#10508]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

PNPM fails to install latest serverless version with the following output:

```
│ internal/modules/cjs/loader.js:888
│   throw err;
│   ^
│ Error: Cannot find module 'boxen'
│ Require stack:
│ - /ws/testproj/node_modules/.pnpm/serverless@2.71.0/node_modules/serverless/scripts/postinstall.js
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
│     at Module.require (internal/modules/cjs/loader.js:957:19)
│     at require (internal/modules/cjs/helpers.js:88:18)
```

This happens for latest `serverless` version, there's no such issue for version `2.43.1` so it switched back to the old version temporarily. 

I also tried clearing the cache and removing `node_modules` completely, however the error still occurs. 

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

`pnpm install --filter=testproj1`

### Command output

```shell
N/A
```

### Environment information

```shell
serverless: 2.71.0
node: 14.17.0
```

**Comment by medikoo** [comment]
@lvkins it must be an issue with your setup, or bug in pnpm. Note that `boxen` is listed as one of the dependencies: https://github.com/serverless/serverless/blob/427920ee0fc1c98109c0b673c794baac1cc5caf7/package.json#L35

**Comment by lvkins** [comment]
Thank you. I will forward this to pnpm team instead.
