### ISSUE TITLE
Changing API endpoint "method" leaves old method in API Gateway

### ISSUE THREAD

**Issue by franz-josef-kaiser** [serverless/serverless#1051]
### Steps to reproduce

1. Create a new function

         $ sls function create functions/foo
         Serverless: Please, select a runtime for this new Function
           > nodejs4.3
             python2.7
             nodejs (v0.10, soon to be deprecated)

2. Create a corresponding endpoint alongside in the same run

         Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
           > Create Endpoint
             Create Event
             Just the Function...
        Serverless: Successfully created function: "foo"

3. Now deploy the function `sls function deploy functions/foo`
4. Open your new function folder named `functions/foo`
5. Open the `s-functions.json` file
6. Change `"endpoints" : "method"` from `"GET"` to `"POST"`
7. Deploy the function **again** `sls function deploy functions/foo`
8. Head over to your AWS API Gateway console, take a look at your project

### Expected behavior

Changing the `method` (or any other parameter) of a function removes the _old_ parameter and introduces the new one. 

1. Introduce new one
2. Confirm that everything is ok
3. Clean up and remove old status

### Actual behavior

You have to go in and clean up manually. That is unexpected as things are changed locally (and not added) and the _new version_ got deployed.

### Environment

Servless: v0.5.5

**Comment by eahefnawy** [comment]
@franz-josef-kaiser thanks for reporting this. We have couple of "remove" actions to help you clean up your project. The most relevant one for you now is `sls endpoint remove`. We generally don't like "automatically removing" anything from your AWS account unless you explicitly say so with `sls remove <whatever>`. You can think of it as an "are u sure you want to delete xyz?" message 😉

**Comment by franz-josef-kaiser** [comment]
@eahefnawy Thanks for the explanation. The _"Are you sure you want to delete X {locally|remote}?"_ message still would be a great addition. _feature request!_

**Comment by eahefnawy** [comment]
ooooh so you mean after you run `sls endpoint deploy` you want a confirmation message? interesting!! yeah even in the docs I put a "DANGER" alert for this command haha

**Comment by franz-josef-kaiser** [comment]
@eahefnawy very close :) I actually hoped for both: Get the question, make a decision to delete/leave untouched, then execute. With a default on of overwrite/delete.

Shall I rewrite the original issue or open a new one with a reference here?

**Comment by eahefnawy** [comment]
Let's open a new one!
