### ISSUE TITLE
Serverless support for auto discovery of functions and resources declarations from different YML file than root serverless.yml

### ISSUE THREAD

**Issue by alsenydiallo** [serverless/serverless#10529]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Running serverless deploy to build and deploy my projects is working without any error; however it is not including any of the project code

* What did you expect should have happened?
I expect the webpack to package all code, this worked previously while on `serverless@1.67.0` , `"serverless-webpack": "^5.3.5",` and `"webpack": "^5.64.4",` 

Needed to update serverless due to `Receiving TypeError: Cannot read property 'stepFunctions' of undefined since 3.0.0 release` [Issue Link](https://github.com/serverless-operations/serverless-step-functions/issues/454)

As a result I updated the following packages 
```

npm install --save-dev serverless@2.71.0
npm install --save-dev webpack@5.65.0
npm install --save-dev serverless-webpack@5.6.0
npm install --save-dev dotenv-webpack@7.0.3

```

## Expected output
```

Serverless: Copying existing artifacts...
Serverless: Setting artifact for function 'createAccount' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'updateAccount' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountById' to '.serverless/app-backend-api.zip'
....
Serverless: Setting artifact for function 'getAccountActivityById' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountStatements' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountStatementsById' to '.serverless/app-backend-api.zip'

```

* What was the config you used?

```
const path = require('path');
const slsw = require('serverless-webpack');
const WebpackPermissionsPlugin = require('./webpack-permissions.plugin');
const nodeExternals = require('webpack-node-externals');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const Dotenv = require('dotenv-webpack');

const entries = {};
Object.keys(slsw.lib.entries).forEach((key) => (entries[key] = ['./source-map-install.js', slsw.lib.entries[key]]));
console.log(entries);
console.log(slsw.lib.entries);
const destPath = path.join(__dirname, '.webpack');
module.exports = {
  entry: entries,
  output: {
    libraryTarget: 'commonjs',
    path: destPath,
    filename: '[name].js',
  },
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  mode: slsw.lib.options.stage === 'local' ? 'development' : 'production',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // we use webpack-node-externals to excludes all node deps.
  // You can manually set the externals too.
  externals: [nodeExternals({ modulesDir: path.resolve(__dirname, './node_modules') })],
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        loader: 'ts-loader',
        exclude: [/\.(test|e2e)\.ts$/],
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
    plugins: [new TsconfigPathsPlugin.TsconfigPathsPlugin({ configFile: path.resolve(__dirname, './tsconfig.json') })],
  },
  optimization: {
    minimize: false,
  },
  plugins: [
    new Dotenv(),
    new CopyWebpackPlugin({
      patterns: [{ from: 'bin', to: 'bin' }],
    }),
    new WebpackPermissionsPlugin(),
  ],
};

```
source-map-install.js content 

`require('source-map-support').install();`
`"source-map-support": "^0.5.21"`

## Project Structure 

```
╰─$ tree -L 1
.
├── README.md
├── api
│   ├── account
│ ...
│   ├── user_signup
│   └── waitlist
├── bin
│   └── mediainfo-curl
├── docker-compose.yml
├── env.yml
├── errors
│   ├── http
│   ├── index.ts
│   └── runtime
├── helper
│   ├── currencies.ts
│   ├── environment.ts
│   ├── error-handler.ts
│   ├── helper.ts
│   └── logger.ts
├── interfaces
│   ├── account.interface.ts
│ ...
│   └── user-data.interface.ts
├── jest.config.js
├── kms_key.yml
├── models
│   ├── DynamoDB
│   └── QLDB

├── node_modules
├── package-lock.json
├── package-lock.json
├── package.json
├── serverless
│   ├── functions
│   └── resources
├── serverless.yml
├── services
│   ├── account.service.ts
│ ...
│   └── user-data.service.ts
├── sonar-project-build.properties
├── sonar-project.js
├── sonar-project.properties
├── source-map-install.js
├── test-report.xml
├── tests
│   └── api_tests
├── tsconfig.json
├── webpack-permissions.plugin.js
└── webpack.config.js
```

## Work around solution
Explicitly defined handler code in `config file`
```
...
module.exports = (async () => {
  const entries = {
    'api/account/handler': ['./source-map-install.js', './api/account/handler.ts'],
    'api/cross-river-bank/handler': ['./source-map-install.js', './api/cross-river-bank/handler.ts'],
    'api/merchants/handler': ['./source-map-install.js', './api/merchants/handler.ts'],
    'api/notifications/handler': ['./source-map-install.js', './api/notifications/handler.ts'],
    'api/plaid/handler': ['./source-map-install.js', './api/plaid/handler.ts'],
    'api/qldb-tables/handler': ['./source-map-install.js', './api/qldb-tables/handler.ts'],
    'api/recipients/handler': ['./source-map-install.js', './api/recipients/handler.ts'],
    'api/requests/handler': ['./source-map-install.js', './api/requests/handler.ts'],
    'api/transactions/handler': ['./source-map-install.js', './api/transactions/handler.ts'],
    'api/user-data/handler': ['./source-map-install.js', './api/user-data/handler.ts'],
    'api/user-profile/handler': ['./source-map-install.js', './api/user-profile/handler.ts'],
    'api/user-signup/handler': ['./source-map-install.js', './api/user-profile/handler.ts'],
    'api/waitlist/handler': ['./source-map-install.js', './api/waitlist/handler.ts'],
  };
  console.log(entries);
  const destPath = path.join(__dirname, '.webpack');
  const accountId = await slsw.lib.serverless.providers.aws.getAccountId();
...
```

Explicitly define `functions and resources` in serverless.yml file

```
...
	
functions:
  - ${file(./foo-functions.yml)}
  - ${file(./bar-functions.yml)}

	
resources:
  - ${file(./foo-resources.yml)}
  - ${file(./bar-resources.yml)}

...
```

## Additional Data

* ***Serverless-Webpack Version you're using***: "^5.6.0"
* ***Webpack version you're using***: "^5.65.0"
* ***Serverless Framework Version you're using***: "^2.71.0"
* ***Operating System***: Mac OS Big Sur Version 11.4
* ***Stack Trace (if available)***:

### Proposed solution (optional)

Considering all the research that I have done, my conclusion is that the solution currently available is to
- Declare all your resources on the serverless.yml file 
- or reference then on the serverless.yml with the format `${file(...js)}`

I think the Serverless Team should look into adding this feature `splitting your functions and resource declaration into different folder or .yml file`

the plugin "serverless-dir-config-plugin" had provided solution to this but it is now broken since I updated to "serverless": "^2.71.0".
This is mentioned on the **serverless-dir-config-plugin** [website](https://www.serverless.com/plugins/serverless-dir-config-plugin) that this could happen.

Quote from **serverless-dir-config-plugin**

> Warnings
> Serverless.js doesn't provide hooks to append to the config file. This plugin ends up making some assumptions to work.
> 
> Currently the framework loads all the plugins before it does anything. This allows the plugin to look for the files and append them to the configuration before anything happens.
> 
> After the configuration is loaded all the variables get resolved. The plugin monkeypatches this process so it can add in function names once the variables are all set.
> 
> This means that right now the way the plugin works is very fragile. If the Serverless.js changes the way they load things - this plugin will break. I am hoping that after confirming that this plugin is useful I will submit a PR that looks at giving plugins access to the hooks that I'm basically inventing

* Any plan for serverless to provide a way to separate your functions declaration and resource from the main serverless.yml file ? a feature similar to what **serverless-dir-config-plugin** provided - [See Here](https://www.serverless.com/plugins/serverless-dir-config-plugin)

**Comment by pgrzesik** [comment]
Hello @alsenydiallo - thanks for reporting. 

When it comes to issue with `webpack`, you should report them directly at `serverless-webpack` repository instead of here. 

As for the functionality provided by `serverless-dir-config-plugin`. At the moment there are no plans to introduce anything similar to what it provides. I will bring it up during internal meeting but I believe this is the first time someone suggests a solution like this.
