### ISSUE TITLE
How to disable showing stacktraces upon function errors?

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#1052]
Stacktraces are ideal during development, however is it possible to disable these when an uncaught exception is raised via the API in a production stage as they could potential expose sensitive data?

I think logging to CloudWatch is still fine, but the end user should be removed from such errors.

**Comment by HyperBrain** [comment]
You can "transform" the error coming from the Lambda in your APIG responseTemplate, so that the user outside of APIG does not see any stacktrace, but maybe get an HTTP error status code.

**Comment by flomotlik** [comment]
Yup I think this should definitely be resolved. Imho the best way going forward would be a Serverless wrapper that catches all exceptions and makes sure something sensible is returned.

**Comment by flomotlik** [comment]
This is done in V1 now. Closing

**Comment by DawnImpulse** [comment]
Hey @flomotlik , can you please redirect me to any doc/blog on  how to do that as I am unable to find any relevant content. Thanks
