### ISSUE TITLE
Custom error handling?

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#1053]
Are there any docs on custom error handling? I have an exception which raises messages such as "A name is required." and I have added the following to my `s-function.json` file:

```
        "404": {
            "selectionPattern": "^\"A .* is required.\"$",
            "statusCode": "404"
        },
```

Using regexr.com the above pattern matches correctly. However errors are still coming through as full stacktraces with a 200 response code. Ideally I'd like to return something like:

```
{ "error: "${error_message}" }
```

Is there something obvious I have missed?

**Comment by flashsnake-so** [comment]
I am not an expert.  But what happen if you remove \"

**Comment by flomotlik** [comment]
@JamieCressey have you found a solution to this already? I will close this issue as it will be resolved by an implementation for the other issue you opened. Would be great to get an update.
