### ISSUE TITLE
File lookup with >9 lookups inside causes Excessive variables nest depth error

### ISSUE THREAD

**Issue by steven-xaroth** [serverless/serverless#10549]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm using a file lookup to a js file that, depending on a few ENV vars, includes other files. It does this by calling resolveVariable(`file(<path>)`).

What happens is that while resolving this file, it tries to resolve the variables inside this file. This used to be fine until 2.68.0.

If I understand the code correctly, it's chaining the lookups inside the file as part of the resolution for the file import. It loops over each lookup inside the file, and does a --counter  for each lookup. This means that at the 10th lookup, counter will be 0, and `resolveInternalResult` will be called with a nestTracker of 0, which fails the entire tree.

This is related to https://github.com/serverless/serverless/commit/63d54e1537e10ae63c171892edd886f6b81e83f6

reproduction repo: https://github.com/steven-xaroth/repro-serverless-var-depth

### Service configuration (serverless.yml) content

see attached reproduction repo: https://github.com/steven-xaroth/repro-serverless-var-depth

### Command name and used flags

see attached reproduction repo: https://github.com/steven-xaroth/repro-serverless-var-depth

### Command output

```shell
Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "custom": Excessive variables nest depth
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.1
     Framework Version:         2.72.1 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.0
     Components Version:        3.18.2
```

### Environment information

```shell
Framework Core: 2.72.1 (local)
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2
```

**Comment by medikoo** [comment]
@steven-xaroth please include a reproduction example. It's hard to say anything without that.

Otherwise, variables resolver has intentional infinite (or absurdly deep) recursion prevention, to avoid process hangs (it's nicer to crash than to hang without feedback)

**Comment by medikoo** [comment]
Also you've marked that you're relying on the latest version, while it's not the case. Please upgrade to latest version

**Comment by steven-xaroth** [comment]
> Also you've marked that you're relying on the latest version, while it's not the case. Please upgrade to latest version

Repo: https://github.com/steven-xaroth/repro-serverless-var-depth

Yes, I was testing multiple versions to figure out where this was originating from. The attached test case repo uses the latest version of serverless.
