### ISSUE TITLE
Function code generation, minus deployment

### ISSUE THREAD

**Issue by allenhartwig** [serverless/serverless#1055]
It would be ideal to be able to generate lambda function code without actually deploying it. `serverless function deploy $func -t` allows for the tmp to be preserved, but still requires the produced code to be deployed to lambda. I'm proposing a new flag of `-p` or `--package-only` to limit the deploy to only code generation (`-t` would be implied).

**Comment by hollanddd** [comment]
At first glance it looks as if there is a call to `CodePackageLambda` made from within `CodeDeployLambda`. These seem to be tightly coupled together. My first thought is that any attempt to do a dry run would need to make a call to pacakgeLambda outside the context of deployLambda

**Comment by HyperBrain** [comment]
DeployLambda can handle and validate parameters by itself. So if a --dry or whatever parameter has been set, Deploy could just return a resolved lambda

**Comment by hollanddd** [comment]
The desire is for a package to be built in the same way that `-t` would work and the only real difference would be to skip the part where sls provisions and deploys. The call to package the lambda is nested inside `_deployCodeByRegion()`. As far as I know there is no way to package functions into `_meta/_tmp` without calling `_deployCodeByRegion()`. Am I approaching this the wrong way? I appreciate any insight you can provide.

**Comment by HyperBrain** [comment]
Ok, you're right it is `FunctionDeploy -> CodePackageLambda -> CodeDeployLambda`.
*But* The actual packaging is done within `Runtime.build()`. So a feasible solution would be to have something that just executes _Runtime.build_. Maybe a `serverless function package` would be better than modifying the existing deploy and obfuscation the control flow.
The `package` action would run the build regardless of the funtion runtime selected, and would be usable for everything.
@eahefnawy What's your opinion about that? I think it's also straight from an architectural point of view.

**Comment by eahefnawy** [comment]
That's an interesting use case! Using Serverless as a lambda package generator, not just a deployer. Is there a particular reason you don't want to deploy via Serverless? (we'd love some feedback to help us improve 😊 )

From an implementation point of view, just like you guys mentioned it might be a bit difficult to accomplish at the current state of the code. However mabye we can have it in v1 since we'll **almost** do a complete rewrite of the framework. But I guess it depends on how critical this functionality is needed.

I like @HyperBrain suggestion to have it as a separate action with `sls function package`. A plugin maybe?

**Comment by allenhartwig** [comment]
The use case arose when I was playing with adding the Optimizer and Webpack plugins and trying to verify what code was generated from Serverless. It resulted in many deployed versions of my code to AWS that weren't necessary for the testing I was doing.

**Comment by hollanddd** [comment]
Same use case as @allenhartwig. I was playing with the Optimizer plugin I wanted to make sure that my shared files were making it into the archive. I fully intend to push using serverless and want this primarily for debugging. A plugin might work. My only request is that the resulting package from `sls function package` is equal to the resulting package of `sls function deploy -t`

**Comment by allenhartwig** [comment]
Would it be possible to have `_deployCodeByRegion()` exit early, after package generation/prior to deployment, if the -p flag is present (or instigated with the `package` argument)?

**Comment by HyperBrain** [comment]
@allenhartwig The `package` command would be the most feasible way as everything else, like modifying the existing workflow would be very hard to keep stable (especially when you work with early exits) and might leave the project state undefined.
I will try to get a plugin ready, as @eahefnawy suggested. Really like that idea.

**Comment by eahefnawy** [comment]
@HyperBrain Awesome!! Thanks a lot! 😊

**Comment by HyperBrain** [comment]
@allenhartwig @eahefnawy @affablebloke Published -> `serverless-package-plugin` version 1.0.0

This initial version just does exactly what `function deploy` does, but without deploying. So the packaged functions (if you use no param or --all) are left in meta/_tmp.
Currently I'm thinking of moving them to `meta/packages` or adding a special `--dest` switch to put them somewhere else. Then they also should be structured like (`/packages/{region}/{function name}`) to get rid of the random numeric extension.
I will create an issue in the plugin (https://github.com/HyperBrain/serverless-package-plugin) to discuss the final functionality. Nevertheless the now provided basic functionality should be good for the beginning.

**Comment by eahefnawy** [comment]
@HyperBrain Sweeeeet!! Awesome stuff! Gonna add it to the list of plugins!

Thanks a lot! 😊

**Comment by flomotlik** [comment]
@allenhartwig this will definitely added to the core of Serverless in the future. We're currently discussing changes to our Plugin system that will make this much simpler.

@HyperBrain thanks again for your numerous contributions.

I will close this issue as this feature is already in our plan and will be tracked in a separate issue in the future.
