### ISSUE TITLE
Custom Authorizer Not Working -- Erring on Endpoint Deployment

### ISSUE THREAD

**Issue by allenhartwig** [serverless/serverless#1056]
I'm having issues getting a custom authorizer to work (SVS v0.5.5) with the endpoint deployment constantly erring with `Invalid authorizer id specified. Setting the authorization type to CUSTOM requires a valid authorizer.`

The custom authorizer is getting created in AWS API Gateway, however, its incomplete, not providing a Region or a Lambda Function. 

My setup is as follows:
`/functions/auth/validate/s-function.json`
```
{
	"name": "AuthValidation",
	"description": "Authentication validation function for cco api requests (${stage})",
	"runtime": "nodejs4.3",
	"handler": "index.handler",
	"authorizer": {
		"type": "TOKEN",
		"identitySource": "method.request.header.Authorization"
	},
	"timeout": 3,
	"memorySize": 256,
	"custom": {
		"excludePatterns": [],
		"optimize": true
	},
	"environment": "$${authEnvironmentTemplate}"
}
```
`/functions/helloworld/s-function.json`
```
{
	"name": "Hello",
	"description": "My first lambda in project ${project} on stage ${stage}",
	"runtime": "nodejs4.3",
	"handler": "index.handler",
	"timeout": 3,
	"memorySize": 256,
	"custom": {
		"excludePatterns": [],
		"optimize": true
	},
	"endpoints": [
		{
			"path": "hello",
			"method": "GET",
			"authorizationType": "CUSTOM",
			"authorizationFunction": "AuthValidation",
			"apiKeyRequired": false,
			"requestParameters": {},
			"requestTemplates": {
				"application/json": ""
			},
			"responses": {
				...
			}
		}
	]
}
```

**Comment by HyperBrain** [comment]
@allenhartwig 
You have to add the _method.request.header.Authorization_ mapping to your endpoint also. I ran into that too.
```
requestParameters: {
  "integration.request.path.Authorization": "method.request.header.Authorization"
}
```
And it is imüportant to map it to "path" in integration. Otherwise Lambda will complain.

**Comment by allenhartwig** [comment]
I'm still receiving the error. Would you be able to provide some more detailed examples of your implementation?

**Comment by laardee** [comment]
@allenhartwig here is an example how I implemented the authorizer https://github.com/laardee/serverless-authentication-boilerplate 
Authorizer function is in the authorization folder and test-token/test-token uses it. Check if your files differs from those some way.

**Comment by allenhartwig** [comment]
After a handful of slight tweaks from your codebase @Iaardee, I was able to get it working -- not sure exactly what fixed it. However, while it does work now, I find it odd that the Custom Authorizer in AWS API console still looks like its not configured correctly: https://www.dropbox.com/s/udopy0qsum1s100/Screenshot%202016-04-28%2013.40.37.png?dl=0

**Comment by laardee** [comment]
@allenhartwig yes I have the same issue, but I think it is more of an AWS console than Serverless issue. The function name isn't displayed because stage is used in authorizerUri that defines which function is used and AWS console cannot handle those, e.g.
`arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:xxxxxx:function:serverless-authentication-boilerplate-authorize:dev/invocations` has `:dev` before `/invocations`.

**Comment by flomotlik** [comment]
@allenhartwig were you able to resolve this? In V1 of the framework we're also going to add better custom authorizer support. As this is already in the plan for the next version I will close this issue (I'm currently going through our Issues and closing the ones that are either resolved or will be implemented in the future already to get our issues a bit cleaned up)

**Comment by avish-3pg** [comment]
@allenhartwig can you please share your working sample of s-function.json for lambda custom authorizer as I am facing issues in the same? Thank you.

**Comment by allenhartwig** [comment]
After further complications with limitations around authorizers, and overall dismal performance of Lambda behind a VPC, I abandoned the architecture.

**Comment by avish-3pg** [comment]
@allenhartwig sorry to hear that, if you may please share the some details on your learning's especially around authorizers limitations, it would really help make informed decisions. Thank you.
