### ISSUE TITLE
Add support for new AWS Region ap-southeast-3 Jakarta

### ISSUE THREAD

**Issue by clample** [serverless/serverless#10578]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS has recently added a new region ap-southeast-3 Jakarta. It would be great if serverless could support this.

Currently, `sls deploy` will fail to deploy ap-southeast-3 with:
```
"Serverless:   at 'provider.region': should be equal to one of the allowed values [us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-west-1, us-west-2, af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-north-1, eu-south-1, eu-west-1, eu-west-2, eu-west-3, me-south-1, sa-east-1]
```

A related issue is https://github.com/serverless/serverless/issues/10298

**Comment by medikoo** [comment]
@clample great thanks for openning that, A PR with update is welcome!

**Comment by jeremycare** [comment]
Hi @medikoo,

I'm on it.

Should the region be added to the dashboards too?
I can see the list of regions supported in the [dashboard.md](https://github.com/serverless/serverless/blob/master/docs/guides/dashboard.md#supported-runtimes-and-regions) but it doesn't match the list in the [provider.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider.js) file.

Should I update the dashboard.md to match the list in the provider.js?

**Comment by medikoo** [comment]
> Should I update the dashboard.md to match the list in the provider.js?

Dashboard documents lists regions supported by our Dashboard internally, it should be updated only by our maintainers who need to first secure support for a given region. Therefore let's leave that one intact

**Comment by clample** [comment]
Thank you @jeremycare !
