### ISSUE TITLE
Endpoint "method" change shall change in API Gateway on demand

### ISSUE THREAD

**Issue by franz-josef-kaiser** [serverless/serverless#1058]
> Follow up on #1051 – feature request

### Current behavior

Currently, when changing an endpoints `method`, the change does not get reflected in the API Gateway. In the AWS console you will find an _additional_ method that needs to get **deleted manually**. 

### Where the change happens

Inside `<functions>/<function_name>/s-function.json`:

```json
"endpoints"   : [ {
	"method" : "POST",
} ]
```

### Desired behavior

**Feature Request:** 

1. Ask if the old endpoint for this `method` should get cleaned up when calling `endpoint` or `dash`
1. Provide a flag to allow passing in a predefined answer for automated deployments, like `-y|--yes` or `-o|--overwrite` or `-f|--force`

**Reason:** Manually cleaning up is odd as you have to go and log in. This makes it hard to pull up and down a project without touching the AWS UI, which would be necessary to automated things from for e.g. your CI service, your build and deployment servers, etc. _The_ goal with automated "provisioning" always is to not get in touch with any UI in the process.

Also it is quite strange to have "left over" endpoints hanging around where you have no definition locally in any file. For collaborators this is unexpected as this would force them to look at each and every point in the whole stack to get a full picture of what is going on. It is also quite tough to keep track of things in just the AWS console.

### Steps to reproduce

1. Create a new function

         $ sls function create functions/foo
         Serverless: Please, select a runtime for this new Function
           > nodejs4.3
             python2.7
             nodejs (v0.10, soon to be deprecated)

2. Create a corresponding endpoint alongside in the same run

        Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
           > Create Endpoint
             Create Event
             Just the Function...
        Serverless: Successfully created function: "foo"

3. Now deploy the function `sls function deploy functions/foo`
4. Open your new function folder named `functions/foo`
5. Open the `s-functions.json` file
6. Change `"endpoints" : "method"` from `"GET"` to `"POST"`
7. Deploy the function **again** `sls function deploy functions/foo`
8. Head over to your AWS API Gateway console, take a look at your project

The actual question should be between step _7_ and _8_ – unless there's no overwriting/automation defined.

    Serverless: You have changed an Endpoint method. Would you like to retain or delete the old method?
        > Delete old Method
          Retain old Method
    Serverless: Successfully delete Endpoint method: "POST" from Endpoint "foo"

**Comment by eahefnawy** [comment]
@franz-josef-kaiser First off I LOVE your well-written issues!! Big thanks for that!

I'm 100% with u for this feature. I believe it's a much better user experience. Do you think we only need to do this for the `method` property of the endpoint? or any other property? Cause it might be really hard to sort of "diff" between your deployed endpoint and the changes you've made in all the properties.

**Comment by franz-josef-kaiser** [comment]
> First off I LOVE your well-written issues!! Big thanks for that!

np. Just writing issues like I want them to be written for myself.

> Do you think we only need to do this for the method property of the endpoint?

Honestly, I have no idea as I just started with _serverless_. As a user I would assume that **everything** that can be _set_ via serverless definitions, should be able to get _changed_ via sls as well. At least the "endgoal" I hope to see here is that _serverless_ handles the full stack for me and allows me automating the provisioning of all AWS services that I need from some CI server.

I am not sure how well things will work out when function over function gets added for each special case in the [`EndpointDeployApiGateway`](https://github.com/serverless/serverless/blob/7e378aca785bafa337215c80d8a600562ee8298f/lib/actions/EndpointDeployApiGateway.js) class (which I assume is the one handling it). Maybe it would be better to start building up a `Command` pattern with only a dedicated `Invoker` and `Receiver` injected there, and `Command*`s added on demand depending on whatever a `DiffParser` might return.

Hope that helps.

**Comment by emotional-engineering** [comment]
Please look:
https://github.com/emotional-engineering/serverless/commit/6daa286d4aa001714ef0d4a57749c10b912cbcdd
https://github.com/emotional-engineering/serverless/tree/endpoint_removal

Added the ability to delete endpoints, that are deployed, but doesn't exist locally. Maybe it can help in some cases.

Now it works with the "dash deploy".

```
Serverless: Select the assets you wish to deploy:
    someUsefulFunction
      function - someUsefulFunction
      endpoint - someUsefulFunction - GET
      x endpoint removal - someUsefulFunction - DELETE
      x endpoint removal - someUsefulFunction - POST    
    - - - - -
  > Deploy
    Cancel
```

**Comment by flomotlik** [comment]
@franz-josef-kaiser for V1 we're planning to move endpoint management into CloudFormation, so this will be updated automatically then when changing any methods. This should lead to a much cleaner infrastructure as nothing needs to be removed any more.

**Comment by franz-josef-kaiser** [comment]
> […] we're planning to move endpoint management into CloudFormation, so this will be updated automatically then when changing any methods.

@flomotlik Could you please elaborate?

**Comment by flomotlik** [comment]
In the next version of serverless we're going to manage all resources we can through Cloudformation. Cloudformation allows to define resources in JSON files, upload those and they make sure that your current infrastructure conforms to the JSON file.

When you change anything in that JSON config file they will update resources accordingly, or remove them if they are no longer present in the config. This way it will automatically resolve those issues and the AWS infrastructure will match your configuration file easily.

**Comment by franz-josef-kaiser** [comment]
@flomotlik Can you please cross link this issue as duplicate of ticket _X_ (I can not find any related issue)? Thanks in advance. Just want to make sure this one is not lost, but can be closed.

**Comment by flomotlik** [comment]
@franz-josef-kaiser there isn't really any particular issue that implements this, its simply working by default through our API Gateway implementation and CloudFormation. Here are the docs for this: https://github.com/serverless/serverless/tree/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway
