### ISSUE TITLE
Bug with verbose flag v3.0.1

### ISSUE THREAD

**Issue by duy9403** [serverless/serverless#10616]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When deploying projects to AWS on Serverless version 3.0.1, if the deploy command has the verbose flag `-v` then serverless doesn't deploy but just prints the version of installed serverless.
 
Similar to [issue #7944](https://github.com/serverless/serverless/issues/7944)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy -v

### Command output

```shell
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.0
```

### Environment information

```shell
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.0
```

**Comment by medikoo** [comment]
@duy9403 `-v` is no longer recognized as the shortcut for `--verbose` as it collides with the same shortcut for `--version`.

There was a deprecation warning configured for that, and this change also is communicated in the changelog

**Comment by medikoo** [comment]
To further clarify, for verbose logging you need to use `--verbose`, but also note that how we log messages in v3, changed significantly, and we also have the _debug_ level

**Comment by duy9403** [comment]
@medikoo Thank you for info.

Closing issue.
