### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by nick-zh** [serverless/serverless#10619]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When i do an `sls deploy` i get:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AwsDeploy.ensureValidBucketExists (../node_modules/serverless/lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js:79:31)
```
When i console.log `getTemplate` result from that offending line
```
    const getTemplateResult = await this.provider.request('CloudFormation', 'getTemplate', {
      StackName: stackName,
      TemplateStage: 'Original',
    });
```
I get the following result:
```
{
  ResponseMetadata: { RequestId: 'fc222942-8359-11ec-9cba-6b39c714db34' },
  TemplateBody: '',
  StagesAvailable: []
}
```

### Service configuration (serverless.yml) content

```yaml
using a very minimal ts file, that has worked in 2.x projects
```

### Command name and used flags

sls deploy

### Command output

```shell
✖ Stack my-lambda failed to deploy (12s)
Environment: linux, node 14.17.6, framework 3.1.0 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AwsDeploy.ensureValidBucketExists (/my-lambda/node_modules/serverless/lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js:79:31)
```

### Environment information

```shell
Framework Core: 3.1.0 (local)
Plugin: 6.0.0
SDK: 4.3.0
```

**Comment by pgrzesik** [comment]
Hello @nick-zh - thanks for reporting and sorry you've run into trouble. Would you be able to provide a small reproducible example for this issue? It would help a lot with debugging.

**Comment by nick-zh** [comment]
Yes i can try, i was checking also if i maybe reported prematurely and downgraded to `2.65.0` again (pervious version i used)
and now i am getting:
```
Serverless Error ----------------------------------------
  Resource ServerlessDeploymentBucket does not exist for stack
```
So maybe i missed something on my side, i will further investigate, sry about this

**Comment by nick-zh** [comment]
@pgrzesik sry for the confusion, i found that i had a cloudformation project in the status `IN_REVIEW` not exactly sure what happened there, but once i cleaned that up, i was able to deploy.
