### ISSUE TITLE
Onboarding: improve output for services already set up

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10611]
### Use case description

(initially reported via Steven's screen recording)

When a service is already set up and uses Serverless Dashboard, the `serverless` command outputs the following:

```
$ serverless

? Do you want to deploy now? (Y/n)
```

This can be confusing when you are not sure whether all is setup and you read this section in the "Getting started" guide:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/720328/151840876-ed4b1043-658c-4530-9d3a-a293102f825b.png">

We could instead print something like this:

```
$ serverless

Your service is configured with Serverless Dashboard and is ready to be deployed.

? Do you want to deploy now? (Y/n)
```

WDYT?

**Comment by medikoo** [comment]
@mnapoli Adding note as you propose, looks as very good idea to me

**Comment by pgrzesik** [comment]
Agreed, I think it's a good idea 👍
