### ISSUE TITLE
Issue while upgrading Serverless version with @3.0.1 and @3.0.0

### ISSUE THREAD

**Issue by SaitejaChavva** [serverless/serverless#10614]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Issue while upgrading the Serverless version with @3.0.1 and @3.0.0
Hi Team,

I was facing issue while upgrading Serverless version with @3.0.1 and @3.0.0.
PFB snapshot's of error message
serverless@3.0.1
image

In jenkins-deploy phase, we are facing below issue while upgrading the serverless version

19:42:13 Environment: linux, node 12.14.1, framework 3.0.1 (local), plugin 6.0.0, SDK 4.3.0
19:42:13 Credentials: Local, environment variables
19:42:13 Docs: docs.serverless.com
19:42:13 Support: forum.serverless.com
19:42:13 Bugs: github.com/serverless/serverless/issues
19:42:13
19:42:13 Error:
19:42:13 When external API Gateway resource is imported via "provider.apiGateway.restApiId", property "provider.tracing.apiGateway" is ineffective.
19:42:13
19:42:13 3 deprecations found: run 'serverless doctor' for more details
19:42:13 make: *** [Makefile.deployServerless:25: deploy] Error 1
[Pipeline] }
[Pipeline] // withFolderProperties
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // maskPasswords
[Pipeline] createSummary
[Pipeline] sh (hid

serverless@3.0.0
image

13:36:30 Environment: linux, node 12.14.1, framework 3.0.0 (local), plugin 6.0.0, SDK 4.3.0
13:36:30 Credentials: Local, environment variables
13:36:30 Docs: docs.serverless.com
13:36:30 Support: forum.serverless.com
13:36:30 Bugs: github.com/serverless/serverless/issues
13:36:30
13:36:30 Error:
13:36:30 When external API Gateway resource is imported via "provider.apiGateway.restApiId", property "provider.tracing.apiGateway" is ineffective.
13:36:30
13:36:30 3 deprecations found: run 'serverless doctor' for more details
13:36:31 make: *** [Makefile.deployServerless:25: deploy] Error 1
[Pipeline] }
[Pipeline] // withFolderProperties
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // maskPasswords
[Pipeline] createSummary

Please give me any suggestions and do the needful, to fix the issue

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
npm install --save-dev serverless@3.0.1
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> serverless@3.0.1 postinstall C:\Users\M1055983\Documents\GitHub\eos-enterprise-owner-services\node_modules\serverless
> node ./scripts/postinstall.js

Serverless Framework successfully installed!

To start your first project run “serverless”.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\@serverless\dashboard-plugin\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN serverless-plugin-aws-alerts@1.4.0 requires a peer of serverless@^1.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN serverless-plugin-split-stacks@1.9.3 requires a peer of serverless@1 but none is installed. You must install peer dependencies yourself.
npm WARN serverless-prune-plugin@1.6.0 requires a peer of serverless@1 || 2 but none is installed. You must install peer dependencies yourself.
npm WARN serverless-webpack@5.5.4 requires a peer of serverless@1 || 2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ serverless@3.0.1
added 8 packages from 5 contributors, removed 170 packages, updated 5 packages, moved 2 packages and audited 1916 packages in 40.238s

99 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by medikoo** [comment]
@SaitejaChavva  please read the error message, it explains well where's the problem

**Comment by SaitejaChavva** [comment]
13:36:30 Error:
13:36:30 When external API Gateway resource is imported via "provider.apiGateway.restApiId", property "provider.tracing.apiGateway" is ineffective.
13:36:30
13:36:30 3 deprecations found: run 'serverless doctor' for more details
13:36:31 make: *** [Makefile.deployServerless:25: deploy] Error 1

**Comment by SaitejaChavva** [comment]
above comment was the issue, Im unable to get it

**Comment by medikoo** [comment]
@SaitejaChavva sorry I don't understand your point. Can you elaborate? Have you read the error message? Do you have problems understanding it?

**Comment by SaitejaChavva** [comment]
@medikoo Yes error message is clear, But how to fix the issue, I need suggestion's

**Comment by medikoo** [comment]
> But how to fix the issue, I need suggestion's

Remove `provider.tracing.apiGateway` setting from configuration

**Comment by SaitejaChavva** [comment]
Thanks @medikoo
