### ISSUE TITLE
VPC setting in s-function.json is not working

### ISSUE THREAD

**Issue by DawoonC** [serverless/serverless#1064]
Serverless v0.5.5

I've set my IAM policy as described in here: https://github.com/serverless/serverless/issues/629#issuecomment-184472421

And set my `s-function.json` as following syntax:
~~~
{
  ...
  "vpc": {
    "securityGroupIds": ["sg-xxxxxxxx"],
    "subnetIds": [
      "subnet-xxxxxxxx",
      "subnet-yyyyyyyy"
    ]
  }
}
~~~

However, it seems this does not effect vpc setting on AWS Lambda when I deploy with `sls dash deploy` command.
Everything else is deployed fine, but only vpc setting is not applied to the deployed function.

Can anyone might tell me what am I missing here? :(

**Comment by tobyhede** [comment]
From memory I also had to add the `AWSLambdaVPCAccessExecutionRole` Policy to my Lambda IAM Role?

**Comment by HyperBrain** [comment]
Add this statement to your `s-resources-cf.json`:

            {
              "Effect": "Allow",
              "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface"
              ],
              "Resource": "*"
            }

**Comment by DawoonC** [comment]
@hyperbrain I already did add those statements and deployed resource.

@tobyhede thx I'll try it :)

**Comment by flomotlik** [comment]
@DawoonC which VPC is it connected to now?

**Comment by DawoonC** [comment]
Sorry I haven't updated this issue.
It turned out that there were duplicate `vpc` configuration in my `s-function.json` file.
I added the configuration at the middle, but there was also default blank `vpc` configuration at the bottom.
So I guess the bottom default one overwrote my configuration.

Sorry I didn't close the issue sooner.
Thanks :)

**Comment by flomotlik** [comment]
Ok, great it works, thanks for reporting back and closing. Let us know if any other issues come up
