### ISSUE TITLE
ESM plugin support

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#10645]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

ESM plugin support allows use of pure ESM package for plugin development.

for example:

```javascript
export default class MyPlugin {
  constructor() {
    // ...
  }
}
```

### Proposed solution (optional)

[Dynamic import](https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_import_expressions) can be used for that purpose.

**Comment by pgrzesik** [comment]
Hello @frozenbonito - thanks a lot for the proposal. After further investigation, it seems like in Node v12 the dynamic import is "experimental" and became stable only in Node 14 release: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#ecmascript-modules-----experimental-modules-flag-removal

As we're currently supporting Node v12, we cannot accept support for functionalities that might not be well supported in Node 12 or emit warnings when they're used. I think we will have to wait for dropping Node 12 support before introducing such change. 

cc @medikoo

**Comment by frozenbonito** [comment]
@pgrzesik 

> After further investigation, it seems like in Node v12 the dynamic import is "experimental" and became stable only in Node 14 release:

No, it's not accurate.
Native ES Modules (and dynamic import) has become stable in Node v12.22.0.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#es-modules

Also see History in following:

https://nodejs.org/docs/latest-v12.x/api/esm.html

**Comment by frozenbonito** [comment]
As a safer way, we can introduce a new flag to enable this feature into serverless.yml.

**Comment by mnapoli** [comment]
@frozenbonito we aim to support versions below v12.22, which means not all v12 support this feature.

**Comment by medikoo** [comment]
Node v12 started to be LTS with v12.13.0, and this is the base we aim to support. Nonetheless, I think this can be supported via a _progressive enhancement_ like approach

In v12 which supports ESM, when we attempt to require ESM module, we get an error with `ERR_REQUIRE_ESM` code. Having that we may fallback to `import` (which is safe to be used in a controlled way in all v12 versions), and that way via recovery logic we can provide support to ESM plugins.

I think it's not that difficult to add. It'll require reconfiguring one internal function to async (which feels safe at quick glance).

One quirk will be, that processing given service will work differently with v12.13.0, where we cannot load ESM at all, and in latest v12, but I think that's fine

**Comment by frozenbonito** [comment]
@medikoo 
Thank you for your comment.

> In v12 which supports ESM, when we attempt to require ESM module, we get an error with ERR_REQUIRE_ESM code. Having that we may fallback to import (which is safe to be used in a controlled way in all v12 versions), and that way via recovery logic we can provide support to ESM plugins.

Great idea!
I would like to work on this issue that way, is that OK?

**Comment by pgrzesik** [comment]
Thanks a lot for additional clarification @frozenbonito - I didn't notice that it was accepted later as a nonexperimental feature 👍 

I like the suggestion that @medikoo proposed and if we can ensure such fallback without causing any issues for users that do not use ESM-based plugins then that would be perfect 👍
