### ISSUE TITLE
Integrate serveless with AWS VAULT

### ISSUE THREAD

**Issue by rogerioefonseca** [serverless/serverless#10644]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

today I started using serveless and in the beginning, I tried to use it with my existing accounts that are all configured with [AWS-VAULT ](https://github.com/99designs/aws-vault).

But after trying I figured that it does not work with AWS-VAULT and I had to hardcode the KEY and SECRET into my terminal using the command:
`serverless config credentials`

### Proposed solution (optional)

Would be nice if the **serverless** could work with AWS-VAULT to keep it more secure working with SESSION_TOKENS and not needing to hardcode secrets in any plain text.
Not sure totally sure how to deal with that but it would be nice to have an option in the configure that could tell serverless to work with VAULT and STS
`config config credentials --provider aws --profile serveless` --type STS

Again, I'm super new using this framework and I still did not read the code, and I'm sorry if this is something that is somehow already covered with another alternative.

**Comment by pgrzesik** [comment]
Hello, what exactly is not working for you? Using `aws-vault exec <profile> -- sls <command>` should work just fine or are you experiencing something different?

**Comment by rogerioefonseca** [comment]
> Hello, what exactly is not working for you? Using `aws-vault exec <profile> -- sls <command>` should work just fine or are you experiencing something different?

My bad, It is working, nothing to do with aws-vault!

I just realize something that I do not know if it is being done by design, but
even with the region configured inside the AWS PROFILE, when I try to deploy it, it still keeps using the us-east-1 region.
![image](https://user-images.githubusercontent.com/17765109/153347195-9cc13a7c-1fa6-4be5-a931-2c37fa6dee77.png)

![image](https://user-images.githubusercontent.com/17765109/153347276-e91cd408-d09d-45c8-a313-d47901d4de8c.png)

And that is the reason why my authentication was not working, so in the end, I needed to hardcode the region in my serverless.yaml.

**Comment by pgrzesik** [comment]
Hello @rogerioefonseca - you have to specify region explicitly in your framework configuration or via cli option, it does not pick up the region based on your aws profile.

**Comment by rogerioefonseca** [comment]
Yep, thanks a lot, so in the end, there is no issue. ;)

**Comment by pgrzesik** [comment]
Thanks @rogerioefonseca - I'm going to close this one
