### ISSUE TITLE
Hold deployment until initialisation of DynamoDB's GSI is ready

### ISSUE THREAD

**Issue by martinezpl** [serverless/serverless#10666]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Today I've added a GSI to existing Dynamo table by defining it in serverless.yml, added some code that queries the GSI and deployed the service. 
For a few minutes after deployment the queries to GSI weren't going through, causing runtime errors.

`ClientError An error occurred (ValidationException) when calling the Query operation: Cannot read from backfilling global secondary index`

I believe backfilling means filling the GSI with data, so deployed code did not work until the index was filled. Naively or not, I expected the framework to hold the function updates until that GSI is ready.

### Proposed solution (optional)

There is a metric called [OnlineIndexPercentageProgress](https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/application-performance-management/20-2/implementing-agents/infrastructure-agent/Amazon-Web-Services-Monitoring/Supported-Services-AWS/AWS-DynamoDB-Service.html) available in AWS/DynamoDB namespace of CloudWatch API. [Seems like the same API is already used to access Lambda metrics](https://github.com/serverless/serverless/blob/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/aws/metrics.js#L89). 

Currently there is a pretty straight-forward work-around for this; deploy the yaml first and after making sure the GSI is ready, deploy the code changes in the functions. So I guess two questions that it leaves are:

1. Is it feasible to have the mentioned metric as a condition for continuing with function updates?
2. Is it worth the effort, granted there're work-arounds?

**Comment by pgrzesik** [comment]
Hello @martinezpl, thanks a lot for reporting. It seems like a specific request related to a resource (DynamoDB) that is not "natively" supported by Framework, but rather as a part of `Resources` section where Framework supports raw CloudFormation. Given that, I don't see a clear path on how we could nicely support it in the Framework at this point. I believe the best way to potentially support such conditions would be via a dedicated plugin.

**Comment by mnapoli** [comment]
It could also maybe be worth asking for such a feature to the AWS CloudFormation team (since all deployments go through CloudFormation, and it seems that creates an unstable setup). They may have some feedback about that use case too.

**Comment by martinezpl** [comment]
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1075
