### ISSUE TITLE
Unable to deploy lambdas using serverless VPC feature. 

### ISSUE THREAD

**Issue by JeanLebrument** [serverless/serverless#1067]
Hello,

I tried to deploy my lambdas on a new stage using `serverless` and I had this error: 

```
Serverless: Deploying the specified functions in "staging" to the following regions: eu-central-1  
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "staging" to the following regions:  
Serverless: eu-central-1 ------------------------  
Serverless:   login-post: Your access has been denied by EC2, please make sure your function execution role have permission to CreateNetworkInterface. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.  
``` 

However, I followed your guidelines and added the following role policy to the IAM group `developer` where all my team belong to.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface"
            ],
            "Resource": "*"
        }
    ]
}
```

Here is how we work: 
Each developer has a specific stage and I manage the staging and production stages. 

I can't deploy the lambda functions to the `staging` stage due to the above errors and even one of my developers couldn't deploy the same lambda functions on its dedicated stage neither. The other developers successfully deployed on their specific stages with the exact same configuration. 

Any suggestion?

**Comment by sellers** [comment]
These are cross linked and closed - I'm confused?
