### ISSUE TITLE
Profile region set in ~/.aws/config should used when --aws-profile or AWS_PROFILE are set

### ISSUE THREAD

**Issue by iokiwi** [serverless/serverless#10681]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

If `--aws-profile` or `$AWS_PROFILE` are specified, serverless appears to pick up credentials from `~/.aws/credentials` fine but does not respect the region configured for the profile as specified in `~/.aws/config`

For example:

Given the following profile configuration

`~/.aws/credentials`
```ini
[profile foo]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```
`~/.aws/config`
```ini
[profile foo]
region = ap-southeast-2
```

Running serverless deploy defaults to `us-east-1` unless `-r` or `--region` are specified as options.

```
$ export AWS_PROFILE=foo
$ serverless deploy

Deploying app to stage dev (us-east-1)

✖ Stack app-dev failed to deploy (5s)
Environment: linux, node 16.13.0, framework 3.2.0, plugin 6.0.0, SDK 4.3.1
Credentials: Local, "foo" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Stack [app-dev] does not exist
```

It's given me an error because it's looking in us-east-1 because I forgot to pass an option for `--region` in addition to `AWS_PROFILE`

### Proposed solution (optional)

If `$AWS_PROFILE` or `--aws-profile` are specified then serverless should respect any profile configuration in `~/.aws/config`

**Comment by pgrzesik** [comment]
Hello, thanks for reporting @iokiwi and sorry you've run into trouble. This seems like a duplicate (or similar issue) of https://github.com/serverless/serverless/issues/4838 and it's also tracked as a part of bigger initiative: https://github.com/serverless/serverless/issues/9290. No ETA for now though. I'm going to close this one for now but if you feel like we should keep this open, please let me know.

**Comment by iokiwi** [comment]
No worries, apologies for the duplication. I tried several search terms and didn't find a match.

All the best,
