### ISSUE TITLE
Only one S3 events per bucket for each function possible

### ISSUE THREAD

**Issue by kristiandreher** [serverless/serverless#1068]
It is not possible to configure multiple S3 events for the same bucket for a function.
If `serverless dash deploy` to deploy the configuration below only Event2 is deployed, however Serverless reports that everything was deployed successfully.
Mulitple events for different buckets works fine.

I am using Serverless v0.5.5.

```
  "events": [
    {
      "name" : "Event1",
      "type": "s3",
      "config": {
        "bucket": "test-bucket",
        "bucketEvents": ["s3:ObjectCreated:*"],
        "filterRules": [
          {
            "name": "prefix",
            "value": "prefix1"
          }
        ]
      }
    },
    {
      "name" : "Event2",
      "type": "s3",
      "config": {
        "bucket": "test-bucket",
        "bucketEvents": ["s3:ObjectCreated:*"],
        "filterRules": [
          {
            "name": "prefix",
            "value": "prefix2"
          }
        ]
      }
    }
  ]
```

**Comment by eahefnawy** [comment]
I may be missing something obvious here, but dont they look like duplicate events? If u want to support more `bucketEvents`, can't you do that in a single serverless event? (by adding to the `bucketEvents` array)

**Comment by kristiandreher** [comment]
What I am trying to do is to trigger the lambda when an S3 key is created with the prefix "prefix1" or "prefix2", but not for other prefixes (like "prefix3").

**Comment by flomotlik** [comment]
Have you tried adding both filter rules into one event?

```
{
      "name" : "Event1",
      "type": "s3",
      "config": {
        "bucket": "test-bucket",
        "bucketEvents": ["s3:ObjectCreated:*"],
        "filterRules": [
          {
            "name": "prefix",
            "value": "prefix1"
          },
          {
            "name": "prefix",
            "value": "prefix2"
          }
        ]
      }
    }
```

**Comment by kristiandreher** [comment]
Yes, it is not possible to have two prefix rules in a filter rule.

```
Serverless: Deploying events in "dev" to the following regions: eu-west-1  
Serverless: Failed to deploy events in "dev" to the following regions:  
Serverless: eu-west-1 ------------------------  
Serverless:   Event1: Cannot specify more than one prefix rule in a filter. 
```

**Comment by flomotlik** [comment]
Yup the current implementation interacting with S3 doesn't allow it. We're currently starting work on V1 that will resolve this because we're setting up everything through cloudformation and allow you to add your own resources in cloudformation. Maybe going through setting up your bucket and the notification rules and point them to the lambda that is running migth be an otpion.

**Comment by kristiandreher** [comment]
OK. Looking forward to V1. :smiley: 
For now I work around the issue by having two different lambdas.

**Comment by flomotlik** [comment]
Ok cool, I will close this issue for now as its going to be resolved with V1 in the future

**Comment by jaydeep17** [comment]
Is it possible now? 🤔

**Comment by pmuens** [comment]
@jaydeep17 yes, you can do the following (the bucket names should be unique...):

```yml
# serverless.yml

# ... some other stuff here

functions:
  hello:
    handler: handler.hello
    events:
      - s3: my-first-bucket
      - s3: my-second-bucket
```

Take a look here for more information: https://serverless.com/framework/docs/providers/aws/events/s3/

**Comment by Kowsalya-t** [comment]
I am still getting the issue:
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  Only one S3 Bucket can be configured per function.  In "my lambda" you're attempting to configure "my bucket1" and "my bucket 2" at the same time.

 Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.13.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

I thought this was fixed. Am I missing something here ??
