### ISSUE TITLE
serverless to check for functions at runtime for functions added by plugins even if the serverless.yml doesn't have functions

### ISSUE THREAD

**Issue by Shereef** [serverless/serverless#10695]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

https://github.com/icarus-sullivan/serverless-plugin-modularize/issues/16

In my `serverless.yml` I have no functions
via plugin the functions are added at runtime
the `serverless@3.2.0` is not deploying those functions because it didn't find any in the `serverless.yml`

### Proposed solution (optional)

serverless to check for functions at runtime for functions added by plugins even if the serverless.yml doesn't have functions

**Comment by Shereef** [comment]
@pgrzesik I debugged it myself. the plugin did set the functions correctly but serverless didn't deploy them for some reason.

I don't know what to do to persuade you, however, I'd appreciate if someone took a look at it.

FYI, the plugin was working up until a point in serverless v2 history but some change on the serverless side.

Anyways, I am living with the workaround I discovered but it would be nice to have it work without workarounds

Thanks for all your work @pgrzesik

**Comment by pgrzesik** [comment]
What is the workaround you mention? Are you able to provide a minimal reproducible example? Maybe the plugin is injecting the functions at the wrong time?

**Comment by Shereef** [comment]
https://github.com/Shereef/modularize-issue

It's listed at the top of the issue mentioned above

the workaround is to add any function to the root serverless.yml and then everything works

**Comment by pgrzesik** [comment]
Thanks for sharing @Shereef - this looks like an issue that should be handled on the plugin side in order to work properly.
