### ISSUE TITLE
Verbose flag misinterpreted as version flag in deploy command

### ISSUE THREAD

**Issue by lfarrel6** [serverless/serverless#10707]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

According to the serverless docs, both `-v` and `--verbose` are supported to enable verbose logging on the deploy command. Since v3, only `--verbose` correctly enables verbose logging, `-v` simply logs the current version information.

Running the deploy command with `-v` on serverless@2.72.2 behaves as expected (run in a non-serverless environment as actual deployment is irrelevant in this case):
```
> sls deploy -v
 Serverless Error ----------------------------------------
 
  This command can only be run in a Serverless service directory. Make sure to reference a valid config file in the current working directory if you're using a custom config file
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.1
     Framework Version:         2.72.2
     Plugin Version:            5.5.4
     SDK Version:               4.3.1
     Components Version:        3.18.2
 

```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy -v

### Command output

```shell
Framework Core: 3.2.1
Plugin: 6.0.0
SDK: 4.3.1
```

### Environment information

```shell
Framework Core: 3.2.1
Plugin: 6.0.0
SDK: 4.3.1
```

**Comment by pgrzesik** [comment]
Hello @lfarrel6 - the behavior has been changed in v3 release (see the breaking changes under CLI section: https://github.com/serverless/serverless/blob/main/CHANGELOG.md#-breaking-changes). Do you still see the reference that `-v` is an alias for verbose in docs? If so, could you please link it so we can fix it? Thanks in advance

**Comment by lfarrel6** [comment]
Ah, I missed that - thank you @pgrzesik. 

There is still a reference on the [Lambda deploy page](https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy). I haven't looked through the rest of the docs, but at a quick glance it's also mentioned on [remove](https://www.serverless.com/framework/docs/providers/aws/cli-reference/remove) and [rollback](https://www.serverless.com/framework/docs/providers/aws/cli-reference/rollback).

**Comment by pgrzesik** [comment]
Thanks, I created a PR that should improve that: https://github.com/serverless/serverless/pull/10710
