### ISSUE TITLE
Input is duplicated on pressed, copied and pasted in the profile creation prompt

### ISSUE THREAD

**Issue by charpeni** [serverless/serverless#1071]
### Version & platform

- OS X El Capitan 10.11.4
- zsh 5.2
- Node v5.10.1
- NPM 3.8.3
- serverless@0.5.5

#### Other dependencies
- async@1.5.2
- aws-sdk@2.3.8
- babel-eslint@6.0.4
- bcrypt-nodejs@0.0.3
- eslint@2.9.0
- eslint-config-airbnb@8.0.0
- eslint-plugin-import@1.6.1
- eslint-plugin-jsx-a11y@1.0.4
- eslint-plugin-react@5.0.1
- lodash@4.11.2
- moment@2.13.0
- mongo@0.1.0
- mongodb@2.1.18
- node-env-file@0.1.8
- request@2.72.0
- serverless-runtime-babel@0.0.6

### Expected behaviour

On running this command : `serverless stage create -s johndoe -r us-east-1`. 

- It should allow me to type it from keyboard or copy paste it without degrade the input.
- It should allow me to type my profile.

### Actual behaviour

- When you type something, the character is duplicated.
- When you copy paste the string is duplicated instead of character.
- On delete, it will remove 2 characters.
- I can't type my profile name.
- The _Enter_ key is also duplicated, that's why I got invalid secret key after submitted the access key and I can't type my profile since the key is sent twice.

### Steps to reproduce
![issue-serverless](https://cloud.githubusercontent.com/assets/7189823/15050306/fddaa184-12c0-11e6-8c48-99c2b8ff1002.gif)

`ServerlessError: Stage ncharpentier already exists` is normal.

**Comment by flomotlik** [comment]
@charpeni thanks for the very detailed report! I wasn't able to replicate so far, is the same issue happening on another shell? If its happening across shells could you check with a different node version?

**Comment by charpeni** [comment]
I just tested with node v4.4.4, It happened the same behaviour.

The same thing happened on the Ubuntu (with default bash) of a coworker. @plbrault Can you describe your environment and test with node 4 ?

**Comment by plbrault** [comment]
I had the same bug with Node 5.9.1 and bash 4.3.11 on Ubuntu 14.04, but I cannot reproduce it anymore.

**Comment by flomotlik** [comment]
Thanks for reporting, we've completely removed interactive mode in V1, so this issue should not happen any more
