### ISSUE TITLE
Custom authorizer does not use custom name

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#1072]
### Problem
Custom authorizers in AWS APIG are single instances (one authorizer has one name and one target function). Therefore it is not possible to have different authorizers for different stages.
The solution is, to define custom function names for the authorizer functions, that include the stage names (`${project}-myAuthorizer-${stage}`).
If you now try to reference the authorizer in an endpoint definition, the endpoint deploy does not use the custom function name, but the generic one only. That leads to the authorizer definition having the same name for all stages (deploy of other stage will just overwrite the authorizer) *and* what is even more critical: The referenced function in the authorizer definition references the generic name, which leads to a non-working deployment.

### Proposal
Custom authorizers should be named by the function's custom name on deployment (if set) and the `authorizerUri` property should be set to the custom name too.

**Comment by theburningmonk** [comment]
In AWS blog's [example](https://aws.amazon.com/blogs/compute/introducing-custom-authorizers-in-amazon-api-gateway), the authorizor function will use the methodArn to work out the stage and region, pushing the complexity to the authorizor function instead.

![image](https://cloud.githubusercontent.com/assets/546969/15074209/a1606dd2-1395-11e6-8401-4af3f1114b37.png)

What do you think of their approach?

**Comment by flomotlik** [comment]
In V1 custom authorisers are simply other methods, so they follow the same naming standard as other functions. closing this issue therefore.
