### ISSUE TITLE
Very old documentation

### ISSUE THREAD

**Issue by drc-gcoakley** [serverless/serverless#10728]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The documentation site https://serverless.readme.io/ lists the latest version as 0.5.0. It seems that this is an old site kept as a reference for those that might still be using the old version. That is fine but, since the documentation only seems to go to the new domain http://serverless.com. The old one should have a note that it is no-longer maintained and a where later versions' documentation can be found.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by mnapoli** [comment]
Hi, there is this mention in the home page of those old docs:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/720328/154850393-3d36bc09-dbd4-45d5-b65c-f4e9ac514640.png">

**Comment by pgrzesik** [comment]
Hey @drc-gcoakley - as @mnapoli mentioned, the docs you're referring to are addressing only older versions of serverless and there's a note about that. The intention is to keep it as some users are still using these old Framework versions. I'm going to close this ticket for now but if there's anything to add, we can reopen it 👍
