### ISSUE TITLE
Failed to deploy. AWS provider credentials not found

### ISSUE THREAD

**Issue by mlichlundia** [serverless/serverless#10729]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi, all! I was trying to deploy my application, but I get this error.
I`ve filled my aws credentials andit seems all files are ok. If somebody faced this problem pleasee reply

![image](https://user-images.githubusercontent.com/88280435/154851154-1e4f55ae-4623-43bd-a70b-eb706d1c61d4.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --verbose 

### Command output

```shell
Error:
AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
```

### Environment information

```shell
Framework Core: 3.2.1 (local) 3.2.1v (global)
Plugin: 6.1.0
SDK: 4.3.1
```

**Comment by pgrzesik** [comment]
Hello @mlichlundia - it looks like more of a Q&A than a bug report so I'm going to close this one for now. I'll respond in the related discussion topic.
