### ISSUE TITLE
[Release] Missing packages for version 2.72.3 assets

### ISSUE THREAD

**Issue by nikitajz** [serverless/serverless#10743]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi Team,

Seems there is something wrong with the release process and actual packages are missing in 2.72.3 (only source code available)
https://github.com/serverless/serverless/releases

![image](https://user-images.githubusercontent.com/12535180/155191628-e6a9e1dd-c00d-4a69-951f-4bc4803cd309.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
All (linux, windows)
```

**Comment by pgrzesik** [comment]
Thanks for reporting @nikitajz - I'm looking into it

**Comment by pgrzesik** [comment]
This has been addressed - the script failed due to a hiccup of Github - thanks a lot for reporting once again @nikitajz 🙇

**Comment by nikitajz** [comment]
@pgrzesik thanks for fixing this quickly!
