### ISSUE TITLE
.NET 6 runtime for Serverless Framework 2.*

### ISSUE THREAD

**Issue by oscarwest** [serverless/serverless#10767]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Like this: https://github.com/serverless/serverless/pull/10757

This way we don't have to upgrade major release for all of our applications at once.

### Proposed solution (optional)

Add the enum and release a 2.* minor

**Comment by mnapoli** [comment]
Hi @oscarwest, at the moment our plan is to include enhancements and new features in the v3 branch only. Is there a blocker for you to upgrade to v3?

**Comment by oscarwest** [comment]
Hello,

No, there are no blockers in the v2 -> v3 upgrade path that we can identify. Some of our microservices have successfully migrated. Our concern is that some services might be using plugins that will break.

Basically we want to bump to .NET 6 ASAP without having to mess with the infra too much.

**Comment by pgrzesik** [comment]
Hello @oscarwest - as @mnapoli outlined, we don't intend to backport such features to v2 release, but honestly in case of .NET 6 runtime, it's only about schema validation, so if you're okay with a warning and don't rely on schema validation, you can specify the runtime not .net6 and it should work just fine on v2 as well

**Comment by oscarwest** [comment]
@pgrzesik That's good to know, thank you.
Do we need to change https://www.serverless.com/framework/docs/configuration-validation settings or is the default schema validation just a warning in the case of the runtime enums?

**Comment by pgrzesik** [comment]
By default it's just a warning. Given that workaround, I'm going to close this issue.
