### ISSUE TITLE
Add support for serverless.yml importing cjs files

### ISSUE THREAD

**Issue by perrin4869** [serverless/serverless#10775]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Right now inside `serverless.yml`, we cannot import from a `cjs` file:

```yml
foo: file(./my-module.cjs:omg)
```

### Proposed solution (optional)

This should work similarly to:

```yml
foo: file(./my-module.js:omg)
```

**Comment by pgrzesik** [comment]
Thanks @perrin4869 🙇
