### ISSUE TITLE
Failed to copy files from template when trying to create project

### ISSUE THREAD

**Issue by ac5tin** [serverless/serverless#10793]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I tried to create new project based on the `aws-go-mod` template but is met with this error `Error: EISDIR: illegal operation on a directory, copyfile`

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls create -t aws-go-mod -p sls_alerter

### Command output

```shell
Environment: linux, node 17.6.0, framework 3.7.1, plugin 6.1.5, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: EISDIR: illegal operation on a directory, copyfile '/tmp/examples/legacy/aws-go-mod' -> '/home/austin/Documents/go/sls_alerter453dc34cfed5e9d1'
```

### Environment information

```shell
Framework Core: 3.7.1
Plugin: 6.1.5
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @ac5tin - I've tried to reproduce and it works correctly on my side. Does the problem persist for you or it was a one time thing?

**Comment by webdevops-os** [comment]
Hi I have the same problem.

serverless create --template google-nodejs --path gcp-function
Environment: linux, node 16.13.2, framework 3.7.1 (standalone), plugin 6.1.5, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: EISDIR: illegal operation on a directory, copyfile '/tmp/examples/legacy/google-nodejs' -> '/home/code/gcp-functionadf92eba300543ab'

**Comment by pgrzesik** [comment]
Thanks @ac5tin and @webdevops-os - I believe I've found the problem and I'm working on addressing it 👍
