### ISSUE TITLE
Mock AWS SDK for faster tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1079]
This package might help:
https://github.com/dwyl/aws-sdk-mock

http://stackoverflow.com/questions/26243647/sinon-stub-in-node-with-aws-sdk

**Comment by pmuens** [comment]
Mocking is done with the help through `sinon`.

**Comment by vamsiampolu** [comment]
I would like to mock a single method in a specific part of the AWS SDK using jest, I cannot find the putObject method on the S3 constructor. Whenever I invoke S3.prototype.putObject, it is always undefined.

The package aws-sdk-mock has not worked for me. Please have a look at this question:

https://stackoverflow.com/questions/49187464/mocking-aws-sdk-s3putobject-instance-method-using-jest
