### ISSUE TITLE
Assets 3.7.5

### ISSUE THREAD

**Issue by davirodr** [serverless/serverless#10852]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

the assets in the new version (3.7.5) is missin
![Captura de Tela_selecionar área_20220314173443](https://user-images.githubusercontent.com/28634365/158259156-237e45eb-2d45-4d2b-afd1-824180be64ed.png)
![Captura de Tela_selecionar área_20220314173737](https://user-images.githubusercontent.com/28634365/158259489-5a4fdf09-51e6-4518-a553-4657353545dc.png)
![Captura de Tela_selecionar área_20220314173755](https://user-images.githubusercontent.com/28634365/158259497-b995e491-9778-4d35-91fa-face3555e03c.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.7.4 (standalone)
Plugin: 6.1.5
SDK: 4.3.2
```

**Comment by vladgolubev** [comment]
I confirm this is a bug. 3.7.5 is missing. Please publish it

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2672  100  2672    0     0  38413      0 --:--:-- --:--:-- --:--:-- 38724

 Installing Serverless!

 Downloading binary for version 3.7.5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   657  100   657    0     0   6997      0 --:--:-- --:--:-- --:--:--  7064
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Could not download binary. Is the version correct?

Exited with code exit status 22
CircleCI received exit code 22
```

**Comment by Brady-Walker** [comment]
It seems the [serverless circle orb](https://circleci.com/developer/orbs/orb/circleci/serverless-framework) always pulls latest. Hoping its a quick fix so we can get CI back online without making too many changes🤞

**Comment by medikoo** [comment]
@davirodr great thanks for reporting. It's fixed now. We'll introduce a patch today, so such issues are avoided in a future
