### ISSUE TITLE
Deploying with Installation of custom CloudFormation resources - EACCES: permission denied

### ISSUE THREAD

**Issue by pags** [serverless/serverless#10889]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless isn't able to install custom CF resources (apparently needed for event bridge support) due to fs perm issues.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
Serverless: Installing dependencies for custom CloudFormation resources...

  Error --------------------------------------------------

  Error: EACCES: permission denied, mkdir '/tmp/tmpdirs-serverless/aef8'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.2
     Framework Version:         2.1.1
     Plugin Version:            4.5.1
     SDK Version:               n/a
     Components Version:        3.7.5
```

### Environment information

```shell
Framework Core: 2.1.1
Plugin: 4.5.1
SDK: n/a
Components: 3.7.5
```

**Comment by medikoo** [comment]
@pags please upgrade to the latest version of the Framework (in v3 event bridge by default no custom resources are used for event bridge deployment)
