### ISSUE TITLE
Support for customizable Ephemeral Storage Size

### ISSUE THREAD

**Issue by fpusch** [serverless/serverless#10899]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS has just announced [configurable ephemeral storage sizes of up to 10GiB](https://aws.amazon.com/about-aws/whats-new/2022/03/aws-lambda-configure-ephemeral-storage/) and it would be great if this could be included in the serverless lambda configuration just like the memory configuration is.

**Comment by pgrzesik** [comment]
Hey @fpusch - thanks a lot for bringing that up and nice to see this finally being supported in AWS Lambda. Looking at docs, it seems like it uses `EphemeralStorage` config in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-ephemeralstorage). 

As for the setting in the Framework, I think it might make sense to follow similar naming scheme and go with:

```
functions:
  hello:
    ...
    ephemeralStorageSize: <value>
```

what do you think? 

cc @mnapoli @medikoo

**Comment by mnapoli** [comment]
@fpusch we're working on it 👍

**Comment by fpusch** [comment]
Sweet thanks for the lightning fast support 👍
