### ISSUE TITLE
starting sls offline having issue 

### ISSUE THREAD

**Issue by itskris84** [serverless/serverless#10893]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

while starting the the 'sls offline' oi am getting below issue 

[nodemon] starting `sls offline`
Environment: darwin, node 16.13.2, framework 3.8.0 (standalone), plugin 6.1.6, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Could not locate the bindings file. Tried:
 → /Users/abc-node-services/node_modules/deasync/build/deasync.node
 → /Users/abc-node-services/node_modules/deasync/build/Debug/deasync.node
 → /Users/abc-node-services/node_modules/deasync/build/Release/deasync.node
 → /Users/abc-node-services/node_modules/deasync/out/Debug/deasync.node
 → /Users/abc-node-services/node_modules/deasync/Debug/deasync.node
 → /Users/abc-node-services/node_modules/deasync/out/Release/deasync.node

### Service configuration (serverless.yml) content

```yaml
-
```

### Command name and used flags

yarn start

### Command output

```shell
-
```

### Environment information

```shell
-
```

**Comment by pgrzesik** [comment]
Hey @itskris84 - this seems to be an issue of the `serverless-offline` plugin, please report it at the plugin's repository. Additionally, I would recommend trying to reinstall the `serverless-offline` as it looks like a potential issue with your installation. I'm going to close this ticket and let's continue discussion in plugin's repo.

**Comment by skauffmann** [comment]
Hi,

I have had a similar issue and I fixed it by excluding the `deasync` module from webpack with `serverless-bundle` :

``` serverless.yml
custom:
  bundle:
    externals:
      - deasync
```
