### ISSUE TITLE
Python3.9 Support

### ISSUE THREAD

**Issue by alimcmaster1** [serverless/serverless#10905]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

serverless deploy 

with provider.runtime: python3.9

Results in:
```
Error:
Error: spawn python3.9 ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

Apparently 3.9 is supported.

https://forum.serverless.com/t/python-3-9-support/16178

Ref: https://github.com/serverless/serverless/issues/10797

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless-deploy

### Command output

```shell
N/A
```

### Environment information

```shell
3.7.4
```

**Comment by pgrzesik** [comment]
Hello @alimcmaster1 👋 Python3.9 is supported in the version you're using - based on the information you provided it's hard to judge what is causing issues for you. Could you share a minimal reproducible example of the bug you're experiencing? Are you using some plugin like `serverless-python-requirements`?

**Comment by AratioD** [comment]
I am facing same issue in GH actions and I am using this `serverless-python-requirements`

Environment: linux, node 16.15.1, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: spawn python3.9 ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by alimcmaster1** [comment]
> update: I got this solved. You have to have same python version everywhere. Otherwise GH action cannot find that.
> 
> I am facing same issue in GH actions and I am using this `serverless-python-requirements`
> 
> dependencies: ├── serverless-plugin-lambda-dead-letter@1.2.1 ├── serverless-plugin-log-retention@2.0.0 ├── serverless-python-requirements@5.4.0 └── serverless@3.19.0
> 
> error: Environment: linux, node 16.15.1, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2 Credentials: Local, environment variables Docs: docs.serverless.com Support: forum.serverless.com Bugs: github.com/serverless/serverless/issues Error: Error: spawn python3.9 ENOENT at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:478:16) at processTicksAndRejections (node:internal/process/task_queues:83:21)

Thanks! Could you articulate what you mean by same Python version everywhere? And what exactly you did to fix this issue! Appreciate the help @AratioD

**Comment by AratioD** [comment]
Hi, @alimcmaster1 

I changed my `pyproject.toml --> python = "^3.10.3"`  to values below -->

```
serverless.yml --> runtime: python3.9
pyproject.toml --> python = "^3.9.11"
GH actions release.yml --> 
- name: Set up Python 3.9
   uses: actions/setup-python@v2
   with:
     python-version: 3.9
```

My error in GH actions --> **Error: spawn python3.9 ENOENT**
ENOENT --> It's an abbreviation of Error NO ENTry (or Error NO ENTity), and can actually be used for more than files/directories. 

In my understanding this means that serverless cannot find correct Python runtime

https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html
Latest supported Python runtime is now 3.9.x

I ended up an outcome if I want to use GitHub actions for Serverless deployment everything Python related need to be `3.9.x`. Manual deployment through AWS connection I had no issues with Python `3.10.x`

**Comment by pgrzesik** [comment]
Thanks for sharing your solution @AratioD - this is not a problem with Framework directly so I think we can close this issue now
