### ISSUE TITLE
Incorrect Route 53 hosted zone chosen when attempting to create a custom domain name

### ISSUE THREAD

**Issue by piersatdoshii** [serverless/serverless#10918]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We appear to have hit a bug in how serverless automatically selects the appropriate hosted zone for some requested domain names. Specifically, when two domains exist, say `live.mydomain.com` as well as `mydomain.com`, and our configuration calls for creating of a custom name of `lambda-live.mydomain.com`, serverless selects the `live.mydomain.com` incorrectly when attempting to create the A record. We discovered this after adding the new `live.mydomain.com` zone, and redeploying our lambda. Best guess, the code that does a lookup of the correct hostname is using regex and failing to escape periods, the first of which then matches `-` incorrectly.

We were able to temporarily workaround the issue in this instance by explicitly specifying `hostedZoneId` as the ID of `mydomain.com` to force that zone to be used.

### Service configuration (serverless.yml) content

```yaml
service: sample-lambda

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-iam-roles-per-function

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!package*'
    - '!sample_data/**'
    - '!tests/**'
    - '!functions/**'
    - '!output.json'

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.7
  baseDomain: ${env:BASE_DOMAIN, "mydomain.com"}
  legacyBaseEnvDomain:
    live: "location-${env:OUR_ENV}.${self:custom.baseDomain}"
    other: "location.${self:custom.baseDomain}"
  legacyCertificateName:
    live: "*.mydomain.com"
    other: "*.${self:custom.baseDomain}"
  customDomains:
    - rest:
        domainName: "${self:custom.legacyBaseEnvDomain.${sls:stage}, self:custom.legacyBaseEnvDomain.other}"
        basePath: ''
        stage: ${env:OUR_ENV}
        certificateName: "${self:custom.legacyCertificateName.${sls:stage}, self:custom.legacyCertificateName.other}"
        createRoute53Record: true
        securityPolicy: tls_1_2
  region:
    default: "ap-southeast-2"
frameworkVersion: '3'

provider:
  name: aws
  region: ${self:custom.region.${sls:stage},self:custom.region.default}
  stage: ${sls:stage}

  environment:
    OUR_ENV: "${sls:stage}"
```

### Command name and used flags

OUR_ENV=live BASE_DOMAIN=mydomain.com serverless create_domain --stage live

### Command output

```shell
11:34:24  > OUR_ENV=live BASE_DOMAIN=mydomain.com serverless create_domain --stage live
11:34:24  

11:34:32  Environment: linux, node 12.22.9, framework 3.1.1 (local), plugin 6.0.0, SDK 4.3.1
11:34:32  Docs:        docs.serverless.com
11:34:32  Support:     forum.serverless.com
11:34:32  Bugs:        github.com/serverless/serverless/issues
11:34:32  
11:34:32  Error:
11:34:32  Error: Unable to create domain 'location-live.mydomain.com':
11:34:32  Failed to UPSERT A Alias for 'location-live.mydomain.com':
11:34:32  [RRSet with DNS name location-live.mydomain.com. is not permitted in zone live.mydomain.com., RRSet with DNS name location-live.mydomain.com. is not permitted in zone live.mydomain.com.]
11:34:32      at ServerlessCustomDomain.<anonymous> (/tmp/workspace/sample-lambda/lambda/node_modules/serverless-domain-manager/dist/src/index.js:189:23)
11:34:32      at Generator.throw (<anonymous>)
11:34:32      at rejected (/tmp/workspace/sample-lambda/lambda/node_modules/serverless-domain-manager/dist/src/index.js:6:65)
11:34:32      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.1.1 (local) 3.7.4v (global)
Plugin: 6.0.0
SDK: 4.3.1
```

**Comment by pgrzesik** [comment]
Hello @piersatdoshii - it seems like an issue related directly with `serverless-domain-manager` plugin functionality. This issue tracker is intended for core Framework features - could you please move your issue to the plugin's repository and continue discussion there? Thanks in advance 🙇 

I'm going to close this one
