### ISSUE TITLE
Use serverless rollback (and sls deploy list) in more verbose way :) 

### ISSUE THREAD

**Issue by omerinvia** [serverless/serverless#10913]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Want to flag out that this is another approach of solving https://github.com/serverless/serverless/issues/9931
we are having a gitlab-ci process which include serverless deploy and we want to implement a fast rollback option (since the packaging process can take crucial time :) )
right now we are rollbacking to the -1 version (based on a script) which is good.. but we want to have more verbose way..

### Proposed solution (optional)

sls.yml
```
provider:
  deployment:
      metadata:
          commit_sha1: ${env:commit_sha1}
```

store it under the s3 object user-defined metadata

present sls metadata during the `serverless deploy list`

🎊

**Comment by mnapoli** [comment]
Hi, thanks for the suggestion! We could even discuss something like `sls deploy --deployId=...`? In any case, it might be worth continuing the discussion in #9931 instead of a new issue? (else this suggestion will not be visible there)

**Comment by omerinvia** [comment]
yes sore, closing this one, adding my thoughts there..
