### ISSUE TITLE
Running serverless deploy -v outputs the version instead of making it verbose

### ISSUE THREAD

**Issue by jmonte-sph** [serverless/serverless#10921]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Framework Core: 3.10.2
Plugin: 6.2.0
SDK: 4.3.2

running `serverless deploy -v` prints the version instead of making the display verbose. **Why does it have to alias --version in the latest version?**

**Past Versions Behavior:**
<img width="1233" alt="Screenshot 2022-04-01 at 12 26 17 PM" src="https://user-images.githubusercontent.com/46807283/161194880-57133be2-8055-4b63-a4a0-eff0677a0d9c.png">

**Actual:**
<img width="485" alt="Screenshot 2022-04-01 at 12 25 33 PM" src="https://user-images.githubusercontent.com/46807283/161194796-477bea0d-ef6a-49d3-ad44-fd1ce22dbe05.png">

**Expected:**
<img width="890" alt="Screenshot 2022-04-01 at 12 25 29 PM" src="https://user-images.githubusercontent.com/46807283/161194810-8a4ef2f1-4736-41a3-8c95-6f0e89f23cfc.png">

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy -v

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.10.2
Plugin: 6.2.0
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @jmonte-sph - it's not a bug - it has been listed as a breaking change for V3 - https://github.com/serverless/serverless/blob/main/CHANGELOG.md#-breaking-changes. 

The reason for that decision is to avoid ambiguities where `-v` was treated differently in different context e.g. running `sls -v` printing version and `sls deploy -v` turning on verbose logging. Now it is standardized and `-v` always means printing version.
