### ISSUE TITLE
SNS Events deploying multiple bindings

### ISSUE THREAD

**Issue by dijitalmunky** [serverless/serverless#1092]
Not sure if this is actually a bug or a feature request.  However, here is what I encountered today:

1. I upgraded my project (which had been deployed already) to serverless 0.5.x
1. I added `customName`s to all of my functions which were different than the names the previous version of SLS I was using had deployed them under.
1. When I deployed my SNS event based functions, things were executing twice (I could tell because my event based lambdas send out emails).

Upon further inspection I found that the SNS Topic had 2 subscriptions instead of the one I had expected.  One subscription was for the lambda that was deployed under the pre-0.5.x name, the other for the lambda deployed under the new `customName` in SLS 0.5.x.

I believe that there should be an option added to `s-function.json` that allows you to specify that you want all subscriptions to be overwritten or not.  My opinion would be that by default this flag is turned on.  However, I can see potential for some people to want to be able to manage other subscriptions outside of SLS.

**Comment by flomotlik** [comment]
We're going to switch to full Cloudformation setup for infrastructure (including SNS) in the future. This issue should be removed automatically then as Cloudformation will take care of it automatically. I will close this issue as we already have plans to resolve this.

Happy to reopen if there is a way where this wouldn't be resolved.
