### ISSUE TITLE
Cannot install serverless plugin from npm organization

### ISSUE THREAD

**Issue by christhomas** [serverless/serverless#10925]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In many examples of how to use plugins and those with organizations, the following yaml syntax is described

```
plugins:
  - @antimatter-studios/serverless-aws-env-endpoint
```

however, this leads to serverless outputting an error like this

```
ServerlessError: Cannot parse "serverless.yml": bad indentation of a sequence entry in "/www/serverless.yml"
6 | plugins:
development_1  |    7 |   - @antimatter-studios/serverless-aws-env-endpoint ....
```

the error appears to be because of the @ symbol which is used in npm modules to denote that this npm module belongs to an organization. For example, installing the plugin above is done by running 

`yarn add @antimatter-studios/serverless-aws-env-endpoint` 

which is correct and yields the plugin installed as expected. 

Now, before somebody jumps in and suggests to quote the string instead. I've already done that and it makes that specific error go away, but now there is a different error in it's place.

```
plugins:
  - "@antimatter-studios/serverless-aws-env-endpoint"
```

and the error now changes to this

```
ServerlessError: Serverless plugin "@antimatter-studios/serverless-aws-env-endpoint" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n @antimatter-studios/serverless-aws-env-endpoint" to install it.

at /www/node_modules/serverless/lib/classes/PluginManager.js:202:19
```

so my question is, how do people install plugins which are defined as part of an npm module and how are they configured, because I can't use the explained syntax because of the first error and I can't use the suggested quotes I also found described on various internet forums because of the second problem.

but I'm assuming that you can do it, since there are hundreds of plugins that appear to be using this syntax. Am I missing something obvious?

if I publish this module to npm without the organization and use it, the plugin works. So it appears the only problem is that this plugin is defined as part of an npm organization. So I have double checked this

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
> serverless --version
Framework Core: 1.67.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3
```

**Comment by mnapoli** [comment]
```yaml
plugins:
  - "@antimatter-studios/serverless-aws-env-endpoint"
```

Is the correct syntax. Regarding the other error:

> Serverless plugin "@antimatter-studios/serverless-aws-env-endpoint" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n @antimatter-studios/serverless-aws-env-endpoint" to install it.

That means that `serverless` cannot `require('@antimatter-studios/serverless-aws-env-endpoint')` -> do you know why that is not working?

TBH I'm not familiar with NPM organizations, is your package installed in `node_modules`?

**Comment by pgrzesik** [comment]
As @mnapoli outlined - you have to specify such plugins with strings quoting, otherwise it's not interpreted properly in yaml. 

Using scoped packages should change anything - if you see that error, make sure that you actually installed the plugin.

Additional note - you're using a heavily outdated version of the Framework - I highly recommend upgrading it to one of the recent releases.

**Comment by christhomas** [comment]
I've made this comment on another thread where this comment about the framework was made also, I don't understand how to change this since I'm running a recent version of serverless

```
> cat package.json | jq .dependencies
{
  "serverless": "^3.10.2"
}

> serverless --version
Framework Core: 1.67.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3
```

So what do I need to do to upgrade this? or what exactly do you mean by outdated version of framework? You mean that it should be what version? It's currently 1.67.0 right?

But if I've got serverless 3.10 installed, which is very recent. Then how can this be installing such an outdated version  of the framework and how I can change this?

**Comment by christhomas** [comment]
ok, the output above is actually misleading. I was wondering why am I with the latest version, yet when I run --version, I get a really outdated version and the problem is that I've accidentally installed a global version of the serverless cli and a yarn version. So the above information was being displayed for the globally installed version. 

So I uninstalled that, then I ran it again, but this time under yarn
```
> yarn serverless --version
yarn run v1.16.0
warning package.json: License should be a valid SPDX license expression
$ /Users/christopherthomas/projects/auth-service/node_modules/.bin/serverless --version
Framework Core: 3.10.2 (local)
Plugin: 6.2.1
SDK: 4.3.2
```

incidentally, this is the version which is being used in the container, which is where I've got the problem I had displayed. Sorry for the mixup, but that was a red herring. I still have the problem, despite having a newer version installed

**Comment by pgrzesik** [comment]
Thanks @christhomas - could you paste the output you get with the error under the newly installed version?

**Comment by christhomas** [comment]
ok, this is a little embarrassing but I noticed a git commit on this software which added node_modules to the volumes of a docker container we use to run the software and as a result, even though yarn was installing the package, the contents of that directory was being ignored and overwritten by a version from when the container was built, before the package was installed. Removing this volume mount solved the problem. So it was a configuration issue

**Comment by pgrzesik** [comment]
No worries @christhomas - happy to hear you've been able to resolve your issue 💯
