### ISSUE TITLE
invoking long running function retries it multiple times 

### ISSUE THREAD

**Issue by kuba-gaj** [serverless/serverless#10935]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We have a long-running function that adds records to the queue.
When running it with `sls invoke -f addToTheQueue` all looks normal but we can see in cloudwatch and in our logs that function is called 4 times in total every 2 minutes resulting in the same lambda populating queue running 4 instances. We also noticed that each invocation has different `awsRequestId`

We solved it temporarily by setting `reservedConcurrency` to one but it is not ideal (we may want to run the same lambda with different parameters) and it feels like a hack.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls invoke --stage dev --function addToTheQueue

### Command output

```shell
Expected output from invocation of a lambda
```

### Environment information

```shell
Framework Core: 3.10.1 (local)
Plugin: 6.2.0
SDK: 4.3.2
```

**Comment by KillDozerX2** [comment]
This might be aws cli doing auto retry, which is the expected behaviour.
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-configure

**Comment by KillDozerX2** [comment]
You can disabling it with AWS_MAX_ATTEMPTS env var set to 0.

**Comment by pgrzesik** [comment]
Hello @kuba-gaj - the issue is caused by the fact that default timeout of AWS SDK calls that is used in `invoke` is equal to 2 minutes. You can override it by setting `process.env.AWS_CLIENT_TIMEOUT` to higher value (in seconds).

**Comment by kuba-gaj** [comment]
Yes that worked, thank you

**Comment by unhyif** [comment]
> 안녕하세요@kuba-gaj`invoke`- 이 문제는 사용된 AWS SDK 호출의 기본 시간 제한이 2분이라는 사실로 인해 발생합니다 . `process.env.AWS_CLIENT_TIMEOUT`더 높은 값(초 단위)으로 설정하여 이를 재정의할 수 있습니다 .

Hi, is it second or millisecond? I'm confused

**Comment by unhyif** [comment]
> Hello @kuba-gaj - the issue is caused by the fact that default timeout of AWS SDK calls that is used in `invoke` is equal to 2 minutes. You can override it by setting `process.env.AWS_CLIENT_TIMEOUT` to higher value (in seconds).

@pgrzesik Hi, is it in second or millisecond? I'm confused

**Comment by pgrzesik** [comment]
Hey @unhyif 👋 Sorry, I think it's actually milliseconds and I made a mistake in my previous message there. 

Relevant part of the code can be found here: https://github.com/serverless/serverless/blob/d09dc6592fab1b8577daa3699373729340a7241d/lib/aws/request.js#L73
