### ISSUE TITLE
Unable to install plugins with latest version

### ISSUE THREAD

**Issue by ivaylopivanov** [serverless/serverless#10959]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Creating a ticket for the following discussion as nobody answered there https://github.com/serverless/serverless/discussions/10924

The issue cannot be reproduced with version 3.11.0. Important note, the issue is not related to the plugin itself. The same error is for other plugins too.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls plugin install -n serverless-offline --stage local

### Command output

```shell
$ sls plugin install -n serverless-offline --stage local
✖ npm ERR! code MODULE_NOT_FOUND
  npm ERR! Cannot find module './install.js'
  npm ERR! Require stack:
  npm ERR! - /snapshot/serverless/node_modules/npm/lib/npm.js
  npm ERR! - /snapshot/serverless/node_modules/npm/lib/cli.js
  npm ERR! - /snapshot/serverless/node_modules/npm/bin/npm-cli.js
  npm ERR! 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /Users/foo/.npm/_logs/2022-04-11T11_27_14_912Z-debug.log
  
Environment: darwin, node 16.14.2, framework 3.12.0 (standalone), plugin 6.2.1, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `node /snapshot/serverless/node_modules/npm/bin/npm-cli.js install --save-dev serverless-offline@latest` Exited with code 1
    at ChildProcess.<anonymous> (/snapshot/serverless/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:687:12)
```

### Environment information

```shell
Framework Core: 3.12.0 (standalone)
Plugin: 6.2.1
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
This should be fixed with next release. Also note that it only affects standalone distribution.

**Comment by ivaylopivanov** [comment]
Thank you @pgrzesik For when is the next released planned / expected?

**Comment by pgrzesik** [comment]
Most likely sometime this week - in the meantime you can use 3.11.0 standalone version - it should work fine there
