### ISSUE TITLE
Refactor Test Project to Test Service

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1099]
- [ ] Rename test_utils.js to TestService.js
- [ ] Wrap TestService logic into a class so that you create a test service with: let testService = new TestService();
- [ ] Refactor TestService logic to reflect the new dir structure
- [ ] Convert the test project dir structure to our new test service dir structure

**Comment by pmuens** [comment]
Is this still necessary?

**Comment by pmuens** [comment]
Not necessary anymore as out test suite does most of it's job in memory.
