### ISSUE TITLE
Use serverless framework with AWS IoT Greengrass

### ISSUE THREAD

**Issue by xmariopereira** [serverless/serverless#10991]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hi,

Would be interesting to use Serverless framework with AWS IoT Greengrass.

Context: AWS IoT Greengrass allows to run aws lambdas on devices locally at the edge.

**Comment by pgrzesik** [comment]
Hello @xmariopereira - could you please clarify more deeply, what exact features would you like Framework to support in order to support Greengrass well?

**Comment by xmariopereira** [comment]
Now that I reread what I requested, a lot of information is missing. Thanks for the reply, and please accept my apologies. 

I will add which features/things I have in mind in a bit.

**Comment by pgrzesik** [comment]
No worries @xmariopereira 🙌 Let us know when you have more details about how such support could look like
