### ISSUE TITLE
CloudwatchLogs as an actions while creating IoT rule Resource 

### ISSUE THREAD

**Issue by raoSHAFQAT** [serverless/serverless#11020]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

CloudwatchLogs are not supported while adding actions under IoT rule.
![image](https://user-images.githubusercontent.com/13718269/165675679-68b03ad2-b018-421f-911e-661b9b7f959d.png)

### Proposed solution (optional)

Kindly suggest way around or whether this is a missing feature .

**Comment by raoSHAFQAT** [comment]
Hi @pgrzesik . I am creating IoT Rule using serverless and needs to add 3 actions.
1- Republish
2- Lambda
3- CloudwatchLogs 
When i add CloudwatchLogs under IoT Rule Actions , I encounter above error.

**Comment by pgrzesik** [comment]
Hey @raoSHAFQAT - could you please propose how it should look like in Framework config? Also, I see the error is coming from some VSCode plugin, right? What error does the Framework itself produce when you try to configure it?

**Comment by raoSHAFQAT** [comment]
![image](https://user-images.githubusercontent.com/13718269/165732878-b9851ee1-243f-4967-99f0-5ca442df0e21.png)
Previously, i was not able to add CloudwatchLogs as an action, now its working and being recognized. Seems like VS code plugin issue. Thanks @pgrzesik

**Comment by pgrzesik** [comment]
Thanks for sharing @raoSHAFQAT - I'm going to close this issue then
