### ISSUE TITLE
Use chais expect throughout test suite

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1102]
Use chais `expect` rather than `assert` as it's more human readable.

**Comment by flomotlik** [comment]
Is this a specific task that we need to implement or do you want to have a discussion about it? If this is a specific task can you rename to "change assert to expect syntax" throughout our test suite so its more actionable. If its just to start a discussion I'm all for it.

**Comment by pmuens** [comment]
I just wanted to hear your thoughts. Are there some edge cases `assert` is superior in comparison to `expect`. For me I really like readability of code and `expect` helps a lot here.

Maybe @eahefnawy can also say smth. about it.

**Comment by eahefnawy** [comment]
There's also `should` not just `expect` ... I think both of these are pretty opinionated. what I've found is that `assert()` is more common for most people, it's even common across programming languages, this was the reason why went with `assert()` (we asked this question before).

I'd vote to keep `assert()` ... at least till we find a more solid reason to use something else...ie if `expect()` has specific new useful methods

**Comment by pmuens** [comment]
@eahefnawy valid points! I'll look into it a little bit more!

**Comment by flomotlik** [comment]
I'll close this issue as we're going to document our testing style in the future and its handled in another issue #1097
