### ISSUE TITLE
"package.json does not exist in _meta/_tmp" error on API Gateway

### ISSUE THREAD

**Issue by anthonybarsotti** [serverless/serverless#1103]
I'm trying to deploy my first Serverless application and I've created a function in a directory called parks within a parent directory called api that is in the root of my project. I have a lib directory in the same api directory that uses the sqlite3 npm module to pull data from a sqlite db that I have in the lib directory. However, once it's deployed to AWS, the endpoint throws the following error:

`{"errorMessage":"package.json does not exist at /Users/username/Sites/serverless-example/_meta/_tmp/parks@1462995121981/node_modules/sqlite3/package.json","errorType":"Error","stackTrace":["Object.<anonymous> (/var/task/parks/_serverless_handler.js:1:1579)","Object.s.2../trace (/var/task/parks/_serverless_handler.js:1:3630)","i (/var/task/parks/_serverless_handler.js:1:611)","/var/task/parks/_serverless_handler.js:1:662","Object.s.1.sqlite3 (/var/task/parks/_serverless_handler.js:1:824)","i (/var/task/parks/_serverless_handler.js:1:611)","/var/task/parks/_serverless_handler.js:1:662","Object.s.45.../lib (/var/task/parks/_serverless_handler.js:4:663)","i (/var/task/parks/_serverless_handler.js:1:611)"]}`

I managed to copy the _tmp directory inside _meta while deploying though and that package.json definitely exists in the correct path.

**Comment by anthonybarsotti** [comment]
Just FYI I had been using the serverless-optimize-plugin to uglify and minify the function. Removing that causes a different error:

`{"errorMessage":"Cannot find module '/var/task/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'","errorType":"Error","stackTrace":["Module.require (module.js:353:17)","require (internal/module.js:12:17)","Object.<anonymous> (/var/task/node_modules/sqlite3/lib/sqlite3.js:4:15)","Module._compile (module.js:409:26)","Object.Module._extensions..js (module.js:416:10)","Module.load (module.js:343:32)","Function.Module._load (module.js:300:12)","Module.require (module.js:353:17)"]}`

**Comment by flomotlik** [comment]
Hi @anthonybarsotti  looks like its trying to set an absolute path here. For these kinds of questions can you post them in [our Gitter room](https://gitter.im/serverless/serverless). People are great at giving help there.

**Comment by xavicolomer** [comment]
@anthonybarsotti did you solve it? I have a similar problem.

**Comment by maazmk** [comment]
any info about the solution, i am having the same issue.
