### ISSUE TITLE
Unable to make a initialise a serverless app

### ISSUE THREAD

**Issue by inceptionabhishek** [serverless/serverless#11047]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After running serverless 
its showing like this
```
$ serverless
Running "serverless" from node_modules
Environment: win32, node 14.16.0, framework 3.16.0 (local) 3.16.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Attempted to run an interactive setup in non TTY environment.
If that's intended, run with the SLS_INTERACTIVE_SETUP_ENABLE=1 environment variable
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless

### Command output

```shell
$ serverless
Running "serverless" from node_modules
Environment: win32, node 14.16.0, framework 3.16.0 (local) 3.16.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Attempted to run an interactive setup in non TTY environment.
If that's intended, run with the SLS_INTERACTIVE_SETUP_ENABLE=1 environment variable
```

### Environment information

```shell
Framework Core: 3.16.0 (local) 3.16.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @inceptionabhishek - could you please provide a bit more details on how you're trying to run it? Based on the message, you're trying to run interactive setup in non-interactive environment - is that the case?

**Comment by inceptionabhishek** [comment]
yes! How to fix it?

**Comment by pgrzesik** [comment]
Why are you trying to run it in non-interactive environment? It won't really be functional, as it asks you a few questions along the way, to which you won't be able to provide answers.

**Comment by vamo089** [comment]
run the command in **windows powershell**

**Comment by anas1179** [comment]
what was the fix @inceptionabhishek ?

**Comment by Alan-Graton** [comment]
@anas1179 Run the `serverless` command with CMD or Windows Powershell instead of Bash
