### ISSUE TITLE
How to add external npm modules

### ISSUE THREAD

**Issue by taptip** [serverless/serverless#1104]
Hi,

I have seen similar existing issues but I can't seem to make it work. I would like your advice if what im doing is right.
This is what my folder structure looks like:
```
.
├── admin.env
├── functions
│   └── geospatial
│       └── get_bounding_coordinates
│           ├── event.json
│           ├── handler.js
│           └── s-function.json
├── _meta
│   ├── resources
│   │   └── s-resources-cf-dev-uswest2.json
│   └── variables
│       ├── s-variables-common.json
│       ├── s-variables-dev.json
│       └── s-variables-dev-uswest2.json
├── node_modules
│   └── geopoint
│       ├── geopoint.js
│       ├── index.js
│       ├── LICENSE
│       ├── package.json
│       ├── README.md
│       └── test
│           ├── test.accessors.js
│           ├── test.bounding.js
│           ├── test.constructor.js
│           ├── test.conversions.js
│           └── test.distance.js
├── package.json
├── s-project.json
├── s-resources-cf.json
└── s-templates.json
```

First on the root of my project folder, I ran "npm install geopoint --save". it added `"dependencies": {    "geopoint": "^1.0.1"  }` on package.json. It also added the npm_modules folder and its contents. 

In functions/geospatial/get_bounding_coordinates/handler.js, i declared `var geopoint = require('geopoint');`

The error is that lambda returns:
```
{
  "errorMessage": "Cannot find module 'geopoint'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/handler.js:2:16)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}
```

Is there something wrong with my implementation?

**Comment by HyperBrain** [comment]
In your s-function.json you have to specify your handler as `functions/geospatial/get_bounding_coordinates/handler.handler`. This will set the function root to the directory containing the `node_modules`. From my experience it is better to have the function root in a subfolder of the project, as otherwise all serverless plugins will be also packaged.

**Comment by taptip** [comment]
Hi! Thank you very much for the answer! It worked! What do you mean by setting the function root in the subfolder? is it forexample putting the node_modules folder and package.json file under functions folder?

**Comment by flomotlik** [comment]
Hi @taptip would be great if we could move this discussion into our [Gitter chat](https://gitter.im/serverless/serverless) so we can have support questions there. We will make our documentation a lot better to cover this in the future.

I will close the issue for now to mark it as resolved.
