### ISSUE TITLE
Node 16 Runtime Support (AWS)

### ISSUE THREAD

**Issue by edm00se** [serverless/serverless#11052]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Following the efforts in aws/aws-lambda-base-images#14, the node 16 runtime should now be available via `nodejs16.x`. Attempting to deploy it gives an "Invalid configuration encountered" warning.

**Comment by pgrzesik** [comment]
Thanks for reporting @edm00se - we already have a PR open (https://github.com/serverless/serverless/pull/11049), but let's wait for an official AWS release before we finalize it.

**Comment by edm00se** [comment]
@pgrzesik perfect thanks.
