### ISSUE TITLE
Shrink README Hero Image

### ISSUE THREAD

**Issue by fny** [serverless/serverless#1105]
![Serverless](https://raw.githubusercontent.com/serverless/serverless/master/other/img/serverless_framework_readme_fire.gif)

It's extremely annoying to scroll across that massive image every time I need to glance at the README. It eats up the whole screen of my 13" Macbook Pro. If I get carpal tunnel from repeatedly scrolling past that bad boy, I might have to call a lawyer. 😉 

![screen shot 2016-05-11 at 11 17 38 pm](https://cloud.githubusercontent.com/assets/346068/15203126/97d18c96-17ce-11e6-866d-0a9ac6ac8002.png)

Also, loading the README with a slow connection is ***brutal***. Why force people to download a 2.85 MB file just to see a repo on Github? I've often chuckled at the irony of waiting 5-6 seconds to download a lightening bolt when sitting behind a 500 kbps line. 😝

**Comment by flomotlik** [comment]
Thanks for reporting, agreed we've maybe made this a little too big :D

**Comment by olzaragoza** [comment]
I can help with this issue.  I scaled the dimensions of the main image to 888px wide to match the max width of the GitHub README.md preview so the overall look wouldn't change.  Is this good for a pull request?

| branch | original size | reduced size | preview |
|---|:---:|:---:|:---:
| master | 2919 kB | 536 kB | [resize-gif-master](/olzaragoza/serverless/tree/resize-gif-master) |
| v1.0 | 4156 kB | 998 kB | [resize-gif-v1.0](/olzaragoza/serverless/tree/resize-gif-v1.0) |
