### ISSUE TITLE
serverless-cloudflare-workers plugin can't use `'${cf:...}' variable resolution after upgrading to Serverless v3

### ISSUE THREAD

**Issue by alfaproject** [serverless/serverless#11068]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- Maybe.

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a service in my stack that deploys a Cloudflare worker using the `serverless-cloudflare-workers` plugin referenced https://www.serverless.com/plugins/serverless-cloudflare-workers

One of my variables for the Serverless configuration is
```
provider.environment.LAMBDA_WS_URI = '${cf:lambda-api-${self:provider.stage}.ServiceEndpointWebsocket}';
```

Which basically gets the CloudFormation stack output from another service that is using AWS.

This all works fine on Serverless v2 but after upgrading to Serverless v3, I get this error:
```
Unrecognized configuration variable sources: ""
```

I've added some logging and it looks like that provider plugins is not able to resolve `self` or even `cf`. I've tried to add it manually but I don't think I know what I'm doing, no matter what I try, something else breaks.

I know the plugin is outdated but it's been working fine for our needs and I don't mind making a local patch if it's an obvious 1 line fix. I'm sure it's something easy that I'm missing but I don't know enough about Serverless architecture to fix it myself, either the plugin or the framework itself ):

### Service configuration (serverless.yml) content

```js
{
  service: 'cloudflare-proxy',
  provider: {
    name: 'cloudflare',
    config: {
      accountId: '...',
      zoneId: '...',
    },
    environment: {
      AWS_REGION: '${self:provider.region}',
      // If I comment out the next line, then the deployment works again,
      // but obviously will miss the most important variable of this service ):
      LAMBDA_WS_URI: '${cf:lambda-api-${self:provider.stage}.ServiceEndpointWebsocket}',
    },
  },
}
```

### Command name and used flags

serverless deploy

### Command output

```shell
Environment: darwin, node 14.17.5, framework 3.17.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Unrecognized configuration variable sources: ""

1 deprecation found: run 'serverless doctor' for more details
```

### Environment information

```shell
Framework Core: 3.17.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
> - [X] Yes, I'm using the latest version

@alfaproject That's not true, please upgrade

**Comment by alfaproject** [comment]
@medikoo that was on purpose because I wanted to show that the issue was caused by upgrading to v3. I've actually tested all versions after v3 was released and all of them show the same issue including the very latest one which I just updated to again and also updated my original post with said version. Sadly, none of the versions after 3.0.0 work ):

**Comment by medikoo** [comment]
Also please see this comment:

```
1 deprecation found: run 'serverless doctor' for more details
```

This indicates that your configuration might be broken (configuration validation errors also are displayed there). So best is to first address all remarks as pointed by `sls doctor`, and confirm whether that fixes the issue on your side

**Comment by alfaproject** [comment]
Yes, I just double checked and I'm back on the very latest version.

It looks like the `cf` variable resolution is only added if the provider is 'aws': https://github.com/serverless/serverless/blob/main/scripts/serverless.js#L660

If I change to `providerName === 'aws' || providerName === 'cloudflare'` then the variable resolution works but then I get another error:
```
Environment: darwin, node 14.17.5, framework 3.17.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.ts: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.LAMBDA_WS_URI": Value not found at "cf" source
```

The deprecation error is for another plugin, and I've disabled it now to reduce the noise:
```
1 deprecation triggered in the last command:

CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessDeleteLoggroups for "stage", "region"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More info: https://serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA_V3
```

**Comment by medikoo** [comment]
@alfaproject thanks for the clarifications. I assume that the issue here is that cloudflare plugin (which doesn't seem listed in above configuration. why?) was not updated for v3. What is the name of this plugin?

**Comment by medikoo** [comment]
I see now in title of issue you mention `serverless-cloudflare-workers plugin`

**Comment by alfaproject** [comment]
Yes, it's kind of abandoned. I tried updating locally so that I can submit a patch or a fork but I still couldn't get it to work and hence why I landed here asking if it's a bug or what do I need to do. I've seen all documentation for Serverless plugins but I don't find anything obvious on how it shouldn't work as is to begin with ):

**Comment by alfaproject** [comment]
Alright, I'll wait a bit until that fix and report back but are you saying that we can't fetch a CloudFormation output from another provider? So, I can't get a CF output variable from another stack that uses AWS provider?

This used to be possible and it's how we setup the Cloudflare gateway to proxy the AWS one in our stack. If that's not going to be possible anymore, so you suggest another alternative to pass a CloudFormation output to another stack that doesn't use AWS?

**Comment by alfaproject** [comment]
For now, I applied this patch in our CI pipeline and together with all env variables that we have setup, it seems to have unblocked me:
```patch
diff --git a/node_modules/serverless/scripts/serverless.js b/node_modules/serverless/scripts/serverless.js
index e2c0b25..195b4fd 100755
--- a/node_modules/serverless/scripts/serverless.js
+++ b/node_modules/serverless/scripts/serverless.js
@@ -658,7 +658,7 @@ processSpanPromise = (async () => {
         }

         // Register AWS provider specific variable sources
-        if (providerName === 'aws') {
+        if (providerName === 'aws' || providerName === 'cloudflare') {
           // Pre-resolve to eventually pick not yet resolved AWS auth related properties
           processLog.debug('resolve variables');
           await resolveVariables(resolverConfiguration);
```

I'll try to get our update to v3 sorted out and maybe find some time to learn about the variable resolvers and see if I can get the CF plugin to work as before without patching Serverless itself. Again, any pointers are welcome. I'm guessing I can copy the CF variable resolver from the AWS plugin and try to go from there

**Comment by medikoo** [comment]
>  Again, any pointers are welcome. I'm guessing I can copy the CloudFormation variable resolver from the AWS plugin and try to go from there

You should configure those missing sources as plugin variable sources: https://www.serverless.com/framework/docs/guides/plugins/custom-variables And you can reuse our resolver functions. You can see how they're configured in the Framework here: https://github.com/serverless/serverless/blob/3b50294f2c5de40c5aa5155fec66734dec30ef7c/scripts/serverless.js#L687-L689

**Comment by alfaproject** [comment]
I've now made my own executors to manage Cloudflare workers using NX, so I no longer need this. Feel free to close

PS: the Cloudflare workers plugin is still in your blog and your official documentation, but that plugin has been abandoned for years: https://www.serverless.com/framework/docs/providers/cloudflare/guide/intro
