### ISSUE TITLE
Cannot read property getALlStages of undefined on project remove

### ISSUE THREAD

**Issue by orasis** [serverless/serverless#1106]
serverless v0.5.5 on node v4.4.0 on Ubuntu

serverless project remove serverless-starter/
Serverless: Removing project...  
/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'getAllStages' of undefined
    at ProjectRemove._removeAllStages (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/actions/ProjectRemove.js:83:34)
    at ProjectRemove.projectRemove (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/actions/ProjectRemove.js:59:19)
From previous event:
    at /home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

- Before you open an issue, please check if a similar issue already exists or has been closed before.
- If you're more interested in a real-time conversation with our community, join us in [our offical Gitter room](https://gitter.im/serverless/serverless)
- Make note of the labels that we add to your issue, these labels could represent the status of the issue (ie. in progress, resolved, released...etc)

### When reporting a bug, please be sure to include the following:
- [ ] A descriptive title
- [ ] What version of Serverless you're using, and the platform(s) you're running it on
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] If you're facing Errors, make sure to provide the full Error stack

### When requesting a new feature or enhancement, please be sure to include the following:
- [ ] The reason why you think this new feature will help you and help other users as well
- [ ] The reason why you think this new feature is relavent to the Serverless Framework (within scope)
- [ ] If you're familiar with our codebase, I'd be really helpful to share some design ideas on how to implement it, or better yet, open a PR!

### When you want to start a discussion, please note the following:
- [ ] Discussion issues are genearlly low priority for the core team, but we still love to be involved.
- [ ] Please Make sure there's no similar issue discussing the same matter.
- [ ] Please keep the discussion light and ego free. Share all your thoughts but be friendly. We're all here to learn from each other :)
- [ ] If you want to ask a direct how-to question, please make sure you checked the docs carefully and didn't find the answer there.

**Comment by NoxHarmonium** [comment]
I was reproducing this crash but it was my fault, although the error message could be clearer.

First I created a project inside of an existing repo. Then when I wanted to remove it, I misunderstood that the project was created in a subfolder and so I tried removing the project from the parent folder like this `serverless project remove new-project` which resulted in this crash. When I changed into the project directory and ran `cd new-project && serverless project remove` it removed it successfully.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
