### ISSUE TITLE
Support Node 16

### ISSUE THREAD

**Issue by achuinard** [serverless/serverless#11070]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

nodejs16.x is rolling out on AWS this week. While it hasn't been announced publicly, the runtime is available, and a public announcement is expected soon. Updating my serverless.yml to the following:

```
provider:
  name: aws
  runtime: nodejs16.x
```

Results in the following error when calling my HTTP function:

```
Warning: Warning: found unsupported runtime 'nodejs16.x' for function 'myAuthorizer'
Authorization function returned an error response: (λ: myAuthorizer)
```

If I flip the runtime back to `nodejs14.x` everything works no problem (even if actually using node 16 to run serverless).

How can this get fixed?

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  runtime: nodejs16.x
```

### Command name and used flags

serverless offline start

### Command output

```shell
Warning: Warning: found unsupported runtime 'nodejs16.x' for function 'myAuthorizer'
Authorization function returned an error response: (λ: myAuthorizer)
```

### Environment information

```shell
Framework Core: 3.17.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@achuinard Framework supports Node.js v16, it's `serverless-offline` that does not, although they merged support recently -> https://github.com/dherault/serverless-offline/pull/1396 it was just not published yet

**Comment by achuinard** [comment]
Thanks for the quick response @medikoo.

**Comment by medikoo** [comment]
@achuinard can we close it?

**Comment by glimmbo** [comment]
I'm running serverless offline 8.8.0 and it still says nodejs16.x is unsupported. 🤷‍♂️

**Comment by pgrzesik** [comment]
@glimmbo If you're experiencing issues with Node 16 please report at `serverless-offline`. I will close this issue as Framework core supports Node 16

**Comment by jpascoe** [comment]
this is still happening form me using latest version of serverless
          npm install -g serverless

at 'provider.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]

**Comment by jpascoe** [comment]
https://www.serverless.com/framework/docs/guides/upgrading-v3

Service configuration
The default Lambda runtime has changed from NodeJS 12 to NodeJS 14, given this is now the default runtime recommended by AWS.

**Comment by jpascoe** [comment]
Is the documentation out of date or is NodeJS 16 not supported yet

**Comment by pgrzesik** [comment]
Hey @jpascoe - which part of the documentation are you referring to? Node 16 is supported, in v3 release there was a change of default runtime from Node 12 to Node 14, but nothing prevents you from setting Node 16 as your preferred runtime.

**Comment by LaTrita97** [comment]
I'm receiving that alert too @pgrzesik.

I have to upgrade the `runtime` from `nodejs12.x` to `nodejs16.x`, but I receive this alert from the console: 
`Warning: Invalid configuration encountered at 'provider.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]`

I'm using version `3` of the framework, but I'm not able to deploy the functions with `nodejs16.x`, what can I do?

**Comment by medikoo** [comment]
> I'm using version 3 of the framework,

@LaTrita97 what does `serverless --version` show?

**Comment by LaTrita97** [comment]
@medikoo 

```
Framework Core: 3.10.2 (local) 3.10.2 (global)
Plugin: 6.2.0
SDK: 4.3.2
```

Yesterday I noticed that if I deploy all the Lambda functions with `sls deploy`, in spite off the alert message, all the functions come deployed with the runtime nodejs16.x.

But if I try to deploy one single function with `sls deploy -f functionName`, it doesn't work.

Am I wrong something?

**Comment by medikoo** [comment]
@LaTrita97 Ensure to rely on latest release (it's v3.22.0)

**Comment by LaTrita97** [comment]
Ok thanks @medikoo.
I'll update the version, likely this is the problem.

**Comment by LaTrita97** [comment]
@medikoo I'm having some problems upgrading serverless to the latest version.

The current version is this
```
Framework Core: 3.10.2 (local) 3.10.2 (global)
Plugin: 6.2.0
SDK: 4.3.2
```

I'm running in the console `npm install -g serverless@3.24.1` but after the upgrade, if I run `serverless --version` the result printed is
```
Framework Core: 3.10.2 (local) 3.10.2 (global)
Plugin: 6.2.0
SDK: 4.3.2
```

Could you please help me to figure out what I'm doing wrong?

PS. I also tried to run `npm install -g serverless` and `npm install -g serverless@3.24.1 --force`, but they didn't work out.

**Comment by medikoo** [comment]
@LaTrita97 what `which serverless` is returning?

**Comment by medikoo** [comment]
Nonetheless, you can ensure an upgraded version for a given service by installing it locally via `npm install serverless`

**Comment by LaTrita97** [comment]
The command `sudo npm install -g serverless@3.22.0` is returning this:
```
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)

added 1 package, removed 4 packages, changed 402 packages, and audited 404 packages in 26s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by LaTrita97** [comment]
@medikoo thank you I've just successfully upgraded the framework locally, but I still continue to don't understand why doesn't work globally
