### ISSUE TITLE
Calling APIGatewayV2 using `serverless.providers.aws.request`

### ISSUE THREAD

**Issue by DianaIonita** [serverless/serverless#11101]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to call the APIGatewayV2 API via the Serverless Framework within a plugin.
I'm currently doing that like so:

```ts
await serverless.providers.aws.request('APIGatewayV2', 'updateStage', params, stage, region);
```

That fails with this error:

```
TypeError: Service is not a constructor
    at ...\node_modules\serverless\lib\aws\request.js:112:12
    at ...\node_modules\memoizee\lib\configure-map.js:61:24
    at ...\node_modules\serverless\lib\aws\request.js:180:26
    at persistentRequest (...\node_modules\serverless\lib\aws\request.js:148:20)
    at Object.promiseGenerator (...\node_modules\serverless\lib\aws\request.js:179:5)
    at Queue._dequeue (...\node_modules\promise-queue\lib\index.js:153:30)     
    at ...\node_modules\promise-queue\lib\index.js:109:18
    at new Promise (<anonymous>)
    at Queue.add (...\node_modules\promise-queue\lib\index.js:94:16)
    at awsRequest (...\node_modules\serverless\lib\aws\request.js:178:38)      
    at AwsProvider.request (...\node_modules\serverless\lib\plugins\aws\provider.js:1595:60)
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.18.1 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @DianaIonita - thanks a lot for reporting and sorry you've run into trouble here. 

I've looked into the issue and I found two problems:
1. The proper service name should be `ApiGatewayV2` - you're using `APIGatewayV2` 
2. The `request` method signature is a bit different than the one you're currently using - it's not a cause of this problem but can produce unexpected results along the way. Below you can find a gist from the code with description of the supported args

```

  /**
   * Execute an AWS request by calling the AWS SDK
   * @param {string} service - Service name
   * @param {string} method - Method name
   * @param {Object} params - Parameters
   * @param {Object} [options] - Options to modify the request behavior
   * @prop [options.useCache] - Utilize cache to retrieve results
   * @prop [options.region] - Specify when to request to different region
   */
  async request(service, method, params, options) {
```

Please let me know if the issue still persist.

**Comment by DianaIonita** [comment]
Hi @pgrzesik,

That worked, thank you very much for your help!

**Comment by pgrzesik** [comment]
Hey @DianaIonita - I'm happy to hear it helped 🙌 Thanks for all your work for the Serverless Framework community 🙇
