### ISSUE TITLE
Recoverable error occurred (Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.), sleeping for ~4 seconds. Try 1 of 4

### ISSUE THREAD

**Issue by victorbianconi** [serverless/serverless#11131]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

```
Uploading service file.zip file to S3 (20.81 MB)
Recoverable error occurred (Connection timed out after 120000ms), sleeping for ~6 seconds. Try 1 of 4
```

I've looked up this error and it's not a new bug, but all the solutions I've seen are for Mac OS and not windows. I tried setting the AWS timeout through `set AWS_CLIENT_TIMEOUT=300000` but it did not work and I'm still getting the error. 

Any idea how to fix this? It's really bothering me especially since from my understanding this keeps adding the bills to AWS even if it fails.

I started getting this problem since when I installed the aws-sdk package and created a function that's supposed to be triggered by an S3 bucket upload.

This is the reference in the .yaml file:

```
functionName:
     handler: src/functions.functionName
     events: 
       - s3:
          bucket: bucketName
          event: s3:ObjectCreated:*
```

This is the function:

```
const functionName = async (e, context) => {
  const aws = require("aws-sdk");
  const s3 = new aws.S3({
    region: "us-east-1",
  });

  console.log(e["Records"][0]["s3"]);

  const sourceBucket = e["Records"][0]["s3"]["bucket"]["name"];
  const sourceKey = e["Records"][0]["s3"]["object"]["key"];

  s3.getObject({ Bucket: sourceBucket, Key: sourceKey }, function (err, data) {
    if (err) {
      const error = new HttpError(err, 500);
      return JSON.stringify(error);
    } else {
      const buffer = data.Body;
      console.log(buffer);
      return {
        body: JSON.stringify(data),
        statusCode: 200,
      };
    }
  });
};

```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Uploading service file.zip file to S3 (20.81 MB)
Recoverable error occurred (Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.), sleeping for ~4 seconds. Try 1 of 4
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hey @victorbianconi - if it's an existing error, please let's not duplicate the issue - could you please report your problem under the original issue? Thanks in advance. 

As for the `set AWS_CLIENT_TIMEOUT=300000` - what do you mean by "it did not work"? It didn't increase the timeout? Was the environment variable actually set during the `sls deploy`?

**Comment by pgrzesik** [comment]
I'm closing this issue and let's continue it in the existing issue for this problem
