### ISSUE TITLE
Use Jest for testing

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1114]
I was curious about your opinions on [Jest](https://facebook.github.io/jest/).

It seems to be very powerful as it's extensible, fast, has automocking (based on the `require` statements) and a built in code coverage analysis.

It runs Jasmine under the hood. Do you think Mocha.js might (in combination with Istanbul) be sufficient or is Jest a better solution?

**Comment by flomotlik** [comment]
I don't have enough insight into the upside of Jest in comparison to Mocha. I don't feel we have a big issue with Mocha.js at the moment.

Imho we shouldn't spend time on researching it at the moment. If you have a clear list of upsides that you can list in less than 5 minutes it would be interesting, but if we need to dig deep to really find what kind of upside it would bring I don't think its worth it.

**Comment by pmuens** [comment]
Ok. Unfortunately I have no deep knowledge of it either. Just stumbled upon it while looking through my bookmarks.

Let's just stick with Mocha.js for the moment as it's already setup and serves us well.
