### ISSUE TITLE
Kinesis - StartingPosition / StartingPostionTimestamp

### ISSUE THREAD

**Issue by padupe** [serverless/serverless#11148]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Paremeter `StartingPosition` does not accept all available options:
```
AT_TIMESTAMP, TRIM_HORIZON, or LATEST
```

Cannot pass parameter `StartingPositionTimestamp` in `serverless.yaml` to Kinesis event.
This limitation generates an error in the lambda build process.

### Proposed solution (optional)

Allow the parameter to be informed, to allow the configurations presented in the documentation to be performed.
https://docs.amazonaws.cn/en_us/lambda/latest/dg/with-kinesis.html#services-kinesis-params

**Comment by pgrzesik** [comment]
Hello @padupe - thanks a lot for reporting and sorry you've run into trouble here. We'd love to support that property and we'd be more than happy to accept a PR that adds support for it. 🙌
