### ISSUE TITLE
[Invoke local aws] Support for ES modules

### ISSUE THREAD

**Issue by borge-bardo-adsk** [serverless/serverless#11143]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Now that AWS lambda [supports ES modules](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/), it would be nice that the `invoke local` for AWS also supports ES modules.

Currently, running `invoke local` for AWS lambda with a ES module ("type": "module" in package.json) will throw the following error:

```bash
✖ Error [ERR_REQUIRE_ESM]: require() of ES Module .build/src/handlers/handler.js from node_modules/serverless/lib/plugins/aws/invoke-local/index.js not supported.

  Instead change the require of handler.js in node_modules/serverless/lib/plugins/aws/invoke-local/index.js to a dynamic import() which is available in all CommonJS modules
```

### Proposed solution (optional)

Change line 813 in [invoke-local](https://github.com/serverless/serverless/blob/main/lib/plugins/aws/invoke-local/index.js#L813) from:

```js
const handlersContainer = require(pathToHandler);
```

to

```js
const handlersContainer = await import(`${pathToHandler}.js`);`
```
The file extension is [mandatory for node](https://nodejs.org/api/esm.html#mandatory-file-extensions), and not sure if it's ok to hard code it as `.js`, or if it needs to be more dynamic to support `.mjs`or other extensions. Any thoughts?

**Comment by pgrzesik** [comment]
Hello @borge-bardo-adsk 👋 Thanks a lot for your proposal here. I agree it would be great to support ESModules in invoke local. The proposed solution, however, shouldn't use `import` in all cases, and instead just fallback to it when we deal with ESM. 

As for the second part of the question - I'm honestly not sure - we could potentially have a fallback to `.js` and `.mjs` I believe. 

If someone would be interested in working on this, we'd be happy to accept a PR, but let's first agree on the implementation details.

cc @mnapoli

**Comment by borge-bardo-adsk** [comment]
Great. So I guess for the first part, we could wrap the `require` in a try/catch and check for error code. Something like:
```js
let handlersContainer;
try {
   handlersContainer = require(pathToHandler);
} catch (err) {
   if (err.code === "ERR_REQUIRE_ESM") {
      handlersContainer = await import(`${pathToHandler}.js`);
   } else {
      throw err;
   }
}
```
Or is there a smarter way to detect this without try/catch that you know of?

For the second part, maybe the safest way would be to look for the actual handler file in the folder and use that when importing. So we have the name without extension, so we could just check if the folder contains a file with that name with either `.js` or `.mjs` extension. WDYT?

And I'm happy to create a PR for this when we decide on the approach.

**Comment by pgrzesik** [comment]
Hey @borge-bardo-adsk - the approach you've proposed there looks very good, we already use a similar pattern for supporting esm-based plugins (see https://github.com/serverless/serverless/blob/main/lib/utils/import-module.js). 

As for the second part, that also sounds good to me. We can also ignore `mjs` in first iteration and just always assume `*.js` and improve further if we get reports from people that `*.mjs` is not supported.

**Comment by borge-bardo-adsk** [comment]
Perfect. I'll make a PR for a first version as soon as time permits.

**Comment by pgrzesik** [comment]
Awesome, feel free to reach out if you have any questions @borge-bardo-adsk 👍

**Comment by borge-bardo-adsk** [comment]
Hi, I finally got around to make a PR. I currently have an issue with eslint. The target is set to `ecmaVersion: 2019` which do not allow dynamic imports. Needs to be at least `ecmaVersion: 2020`. Any advice on how to proceed?

**Comment by pgrzesik** [comment]
Hey there 👋 As for the PR - that sounds great! However, you might want to wait for https://github.com/serverless/serverless/pull/11203 to get merged as it adds recognition for `.cjs` file extension, probably in the same place as you're adding ESM support. 

For the problem with eslint, we already have it setup for a few files that call `import` - please see here: https://github.com/serverless/serverless/blob/f5786d80acf417a92d8ab07714fdfd8e3d654a61/package.json#L111-L141

**Comment by borge-bardo-adsk** [comment]
Thanks for the answer and heads-up. I rebased from `main ` so it includes the `.cjs` support and created a new [PR](https://github.com/serverless/serverless/pull/11212) that should resolve this issue. Looks like the PR need an approval to run the pending checks though.

**Comment by NemoStein** [comment]
> We can also ignore `mjs` in first iteration and just always assume `*.js` and improve further if we get reports from people that `*.mjs` is not supported.

We need `.mjs` support: https://github.com/serverless/serverless/issues/11308#issuecomment-1366781871 (or a serverless-esbuild fix)

**Comment by borge-bardo-adsk** [comment]
I added a suggestion to add `.mjs` support in https://github.com/serverless/serverless/issues/11308#issuecomment-1719297694 @pgrzesik Are you able to take a look? I'm happy to set up a PR if the suggested way makes sense.

**Comment by borge-bardo-adsk** [comment]
Or maybe @medikoo ?

**Comment by medikoo** [comment]
@borge-bardo-adsk I'm no longer with Serverless Inc, and I have no rights to push any work here forward. AFAIK it's @Mmarzex and @ac360 which are handling community contributions now

**Comment by borge-bardo-adsk** [comment]
Ok, thanks for letting me know. And sorry to bother.
