### ISSUE TITLE
Reimplement plugin system

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1116]
For V1 we want to reimplement the Plugin system for a cleaner setup:

- [x] Main Plugin system to load plugins from serverless.yml config (not managing serverless.yml config parsing here)
- [x] Setting up commands and subcommands inside of the plugin infrastructure
- [x] Defining parameters to hand to the plugin contructor
- [x] Loading Lifecycle Events from each command
- [x] Loading Hooks from each plugin
- [x] Validating match of Lifecycle Events and provided hooks
- [x] Addition of before/after lifecycle events
- [x] Executing Lifecycle Events for each plugin (with return or promise)

Open Questions:
- [x] Accessing the Serverless instance from the plugin

**Comment by pmuens** [comment]
@flomotlik could you explain this in detail:

> Define CLI configuration inside of the Command
