### ISSUE TITLE
New Serverless architecture

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1118]
- [x] Plugin Management - #1116 
- [x] Service Configuration - #1121 
- [x] Serverless Glue System - #1122
- [x] CLI configuration - #1123

@flomotlik @eahefnawy Here's the rough overview:

## Serverless.js
```
import CLI from './CLI';
import Config from './Config';
import YamlParser from './YamlParser';
import PluginManagement from './PluginManagement';
import Utils from './Utils';
import Service from './Service';

class Serverless {
  constructor(userInput) {
    this.instances = {};

    // Attach all instances so that we can pass the serverless instance around and have access to all other classes (might be useful for Plugin authors)
    this.instances.cli = new CLI(this);
    this.instances.config = new Config(this);
    this.instances.yamlParser = new YamlParser(this);
    this.instances.pluginManagement = new PluginManagement(this);
    this.instances.utils = new Utils(this);
    this.instances.service = new Service(this);

    this.instances.config.loadConfig();
    this.instances.service.loadService(this.instances.config.config);

    this.instances.pluginManagement.loadPlugins(this.instances.service.pluginNames);

    this.instances.pluginManagement.runCommand(userInput);
  }
}
```

## PluginManagement.js
```
import Utils from './Utils.js';

class PluginManagement {
  constructor(Serverless) {
    this.Serverless = Serverless;
    this.plugins = [];
    this.commands = [];
    this.events = [];
  }

  addPlugin(Plugin) {
    this.plugins.push(Plugin);

    this.loadCommands(Plugin);
    this.getEvents(Plugin);
  }

  loadPlugins() {
    loadCorePlugins();
    loadServicePlugins();
  }

  loadCorePlugins() {
    const utils = new Utils();
    const corePlugins = utils.readFileSync(../plugins.Plugins.json).plugins;

    corePlugins.forEach((Plugin) => {
      this.addPlugin(new Plugin())
    });
  }

  loadServicePlugins() {
    const servicePlugins = this.config.getConfig().plugins;

    servicePlugins.forEach((Plugin) => {
      this.addPlugin(new Plugin());
    });
  }

  loadCommands(Plugin) {
    this.commands.push((new Plugin()).commands);
  }

  getEvents(commands, availableCommands, prefix) {
  }

  runCommand(command) {
  }

  // public getters
  getCommands() {
    return this.commands;
  }

  getPlugins() {
    return this.plugins;
  }
}
```

## CLI.js
```
class CLI {
  constructor(Serverless) {
    this.Serverless = Serverless;
  }

  parseCommands(argv) {
    const commands = argv._;
    const options = argv.keys;
  }
}
```

## Service.js
```
import YamlParser from './YamlParser';

class Service {
  constructor(Serverless) {
    this.Serverless = Serverless;
    // holds functions, plugins, ...
    this.functions = [];
    this.pluginNames = [];
  }

  loadService(servicePath) {
    const yamlParser = new YamlParser();

    const serverlessYaml = yamlParser.parse(path.join(servicePath, 'serverless.yaml');
    const serverlessEnvYaml = yamlParser.parse(path.join(servicePath, 'serverless.env.yaml');

    // loop through the returned object and attach functions, plugins etc.
  }
}
```

## Config.js
```
class Config {
  constructor(Serverless) {
    this.Serverless = Serverless;
    this.config = {}
  }

  loadConfig(config) {
    // load the config here
    this.config = config;
  }

  // public getters
  getConfig() {
    return this.config
  }
}
```

## YamlParser.js
```
class YamlParser {
  constructor(Serverless) {
    this.Serverless = Serverless;
  }
}
```

## Utils.js
```
class Utils {
  constructor(Serverless) {
    this.Serverless = Serverless;
  }
}
```

**Comment by flomotlik** [comment]
Good job so far, here a few thoughts:

>The serverless instance uses YamlParser to load the service plugins (live inside serverless.yaml) and the core plugins

I don't think the Serverless class should have any knowledge around the YAML parser. The Serverless class should tell the Config class to load the config ( this.config.loadConfig() ) but shouldn't know if its yaml or anything else. The config class itself then simply loads the config (from serverless.yml) and provides access to all its attributes. This makes sure the Serverless class is really only responsible as the glue between the different systems and doesn't have any unnecessary logic and we can easily swap out implementations of the config parser is its just used in Config.js


>The loaded plugins are stored inside the PluginManagement class (plugins array, also contains everything plugin related such as commands and events)

Plugins and all their configuration should absolutely be stored in PluginManagement, but they should also be loaded there. Imho Plugin Management is the only place that knows about plugins, how they are loaded and executed and handles it themselves. Serverless then simply instructs the PluginManagement to load the plugins including the core plugins and plugins defined in the serverless.yml ( this.pluginManagement.loadPlugins(this.config.plugins) ). This makes sure everything that deals with loading plugins, plugin management and running plugins is stored in there.


>The arguments the user entered are passed into the CLI instance (CLI.runCommand() alongside the events and the plugins)

I don't think we need to pass all that data into the CLI. Basically what the CLI does is taking ARGV, loading the commands and arguments handed to the cli and Validating against the cli config of the respective command. Once its validated it simply hands back a config object to Serverless that has all that configuration and can be used when running the commands

> The runCommand() execute the correct hooks

I think this should also be in PluginManagement. Basically the CLI should really only do interaction between the User and a data object that can be used in other parts of the system. If we implement running the actions and lifecycle management inside the CLI class we strongly bind the CLI and the way we run plugins together.

So something like 
```
this.instances.pluginManagement.runCommand([ARRAY_OF_COMMANDS], {CLI Arguments})
```

The PluginManagement instance should already have access to Serverless and can pass it to the Plugin (so we should probably introduce a Plugin class that people can inherit from with a Constructor that sets this up in a Plugin automatically)


The main idea with my comments is that we make sure every class really only concerns with one particular problem and we make sure everything is done properly inside that class.

**Comment by eahefnawy** [comment]
Sounds good. One note is that the Config class handles **Serverless config** not Service config, so this data won't be in `serverless.yaml`. It just handles things like:

```js
let config = {
  interactive: true,
  servicePath: <path-to-service>
}
```

The Plugin class however will need access to `serverless.yaml` to load project plugins. I'd rather have the Service class handle loading the `serverless.yaml` file using the Parser (including plugins array), and then the Plugin can access this array from there

**Comment by flomotlik** [comment]
Ah ok thats good to know. Service class loading the serverless.yml and providing that config data to the Rest (the same way I mentioned above with Config) is fine for me.

**Comment by eahefnawy** [comment]
oh one more thought ... we'll also need to include the **classes** not just **instances** of the our classes. This is to make it easy for Plugin authors to init any class based on their requirements. Historically we've let them do this by simply requiring the files from our codebase, but this has been hacky because we have to provide them with our "Serverless Path" and it also introduced some minor issues with windows (since path is treated differently there).

So we figured we'll have everything they need ready in the main Serverless instance

**Comment by flomotlik** [comment]
@eahefnawy Do you have a use case for this? I'm not sure what people would specifically use this for in plugins and I'd rather only implement this once we have clear use cases for specific implementations.

**Comment by eahefnawy** [comment]
a plugin the creates a function needs to Init a new Function class for example. Even we will be using this same interface to Init a new `Service` class when writing the `create` plugin

**Comment by flomotlik** [comment]
Yes there are definitely specific classes we want to give people access to, just not all of them and we should expand that list once we know people need it imho

**Comment by eahefnawy** [comment]
@flomotlik to your last thought about getting back to extending a Plugin class so that plugin authors would have access to CLI commands and options, after thinking it through with @pmuens ... I don't think we'll need that. Plugin authors already have access to these using the Serverless instance (which is the glue that ties everything together). So a plugin author could just say:

```
      class PluginMock {
        constructor(serverless) {
          this.commands = {
            test: {
              usage: 'test usage',
            },
          }
        }
      }

options = serverless.instances.cli.options
commands = serverless.instances.cli.commands
```

**Comment by ac360** [comment]
Quick suggestion to change the name `PluginManagement` to `PluginManager` so that it's more grammatically correct, clear and short.

**Comment by ac360** [comment]
Also, let's get rid of the `instances` object.  It sticks out to me as unusual and excessive for node programming.

Separation of concerns/encapsulation of logic is implicit in class architecture.  Whether instances of those classes are in an object/array entitled `instances` makes no difference.

What is different is the amount of excessive/annoying typing required with `instances`:
`this.instances.pluginManagement.runCommand()`

This is much more readable:
`this.pluginManager.runCommand()`

**Comment by pmuens** [comment]
Good feedback. Just renamed the `PluginManagement` to `PluginManager` as it's really more descriptive.

**Comment by pmuens** [comment]
Just want to share an update about the current architecture. We can get rid of the `instances` object etc. (as already mentioned). But this is how it works right now.

@flomotlik @ac360 @eahefnawy @nikgraf 

```
// lib/Serverless.js
import CLI from './CLI';
import Config from './Config';
import YamlParser from './YamlParser';
import PluginManagement from './PluginManagement';
import Utils from './Utils';
import Service from './Service';

class Serverless {
  constructor() {
    this.instances = {};

    // Attach all instances so that we can pass the serverless instance around and have access to all other classes (might be useful for Plugin authors)
    this.instances.config = new Config(this);
    this.instances.yamlParser = new YamlParser(this);
    this.instances.pluginManager = new PluginManager(this);
    this.instances.utils = new Utils(this);
    this.instances.service = new Service(this);

    this.instances.cli = new CLI(
      this,
      this.instances.config.interactive,
      this.instances.service.getAllStages(),
      this.instances.service.getAllRegionsInStage
    );

    // load config
    this.config = this.instances.config.loadConfig();
    // load service
    this.service = this.instances.service.loadService(this.config);
    // load all plugins
    this.instances.pluginManager.loadPlugins(this.service.getPluginNames());
    // processCommands will check if the user has entered "help" or "version"
    // and will return with the corresponding CLI action. Otherwise it'll create an 
    // array with the commands the user has entered (e.g. ['greet']) which is then passed
    // to the runCommand method
    this.commandsToBeProcessed = this.instances.cli.processCommands();

    // check if there are any commands which should be processed
    if (this.commandsToBeProcessed.length) {
      this.instances.pluginManager.runCommand(this.commandsToBeProcessed);
    }
  }
}
```

**Comment by HyperBrain** [comment]
I remember that there was demand in some issue for having the `serverless help` command succeed, even if there is a syntax error in any configuration file. Using this implementation would not solve the issue, as the instances are initialized before the commands are processed, does it? Nevertheless it's questionable if such a behavior is generally needed.

**Comment by pmuens** [comment]
Good point. I think we can make this work in this implementation. Right now we get the parameters in `processCommands()` and check if they contain `help` or `version` (or nothing). We might implement this logic here.

An array with the commands will be created if there's no single command like `help` or `version`. This array gets passed to the `runCommand()` method of the `PluginManager`.

**Comment by pmuens** [comment]
YAAU (Yet another architecture update):

Then command execution is now separated in an own method (before that it was directly inside the constructor). This way one needs to initialize serverless and call `runCommand()` after that. This separation makes unit testing (where oftentimes a serverless instance is used) way easier and makes more sense IMHO.

```
// lib/Serverless.js
import CLI from './CLI';
import Config from './Config';
import YamlParser from './YamlParser';
import PluginManagement from './PluginManagement';
import Utils from './Utils';
import Service from './Service';

class Serverless {
  constructor() {
    this.instances = {};

    // Attach all instances so that we can pass the serverless instance around and have access to all other classes (might be useful for Plugin authors)
    this.instances.config = new Config(this);
    this.instances.yamlParser = new YamlParser(this);
    this.instances.pluginManager = new PluginManager(this);
    this.instances.utils = new Utils(this);
    this.instances.service = new Service(this);

    this.instances.cli = new CLI(
      this,
      this.instances.config.interactive,
      this.instances.service.getAllStages(),
      this.instances.service.getAllRegionsInStage
    );

    // load config
    this.config = this.instances.config.loadConfig();
    // load service
    this.service = this.instances.service.loadService(this.config);
    // load all plugins
    this.instances.pluginManager.loadAllPlugins(this.service.getServicePlugins());
    // processCommands will check if the user has entered "help" or "version"
    // and will return with the corresponding CLI action. Otherwise it'll create an 
    // array with the commands the user has entered (e.g. ['greet']) which is then passed
    // to the runCommand method of the PluginManager instance
    this.commandsToBeProcessed = this.instances.cli.processCommands();
  }

  runCommand() {
    // check if there are any commands which should be processed
    if (this.commandsToBeProcessed.length) {
      this.instances.pluginManager.runCommand(this.commandsToBeProcessed);
    }
  }
}
```

**Comment by pmuens** [comment]
YAAU (Yet another architecture update):

Renamed the `runCommand` method to `run` (because it processes `commands` and `arguments`). `commandsToBeProcessed` is change to `inputToBeProcessed` to reflect the changes mentioned above.

// lib/Serverless.js
import CLI from './CLI';
import Config from './Config';
import YamlParser from './YamlParser';
import PluginManagement from './PluginManagement';
import Utils from './Utils';
import Service from './Service';

class Serverless {
  constructor() {
    this.instances = {};

    // Attach all instances so that we can pass the serverless instance around and have access to all other classes (might be useful for Plugin authors)
    this.instances.config = new Config(this);
    this.instances.yamlParser = new YamlParser(this);
    this.instances.pluginManager = new PluginManager(this);
    this.instances.utils = new Utils(this);
    this.instances.service = new Service(this);

    this.instances.cli = new CLI(
      this,
      this.instances.config.interactive,
      this.instances.service.getAllStages(),
      this.instances.service.getAllRegionsInStage
    );

    // load config
    this.config = this.instances.config.loadConfig();
    // load service
    this.service = this.instances.service.loadService(this.config);
    // load all plugins
    this.instances.pluginManager.loadAllPlugins(this.service.getServicePlugins());
    // Input will check if the user has entered "help" or "version"
    // and will return with the corresponding CLI action. Otherwise it'll create an 
    // array with the commands and an object with the argumentsthe user has entered 
    // which is then passed to the run method of the PluginManager instance
    this.inputToBeProcessed = this.instances.cli.processInput();
  }

  run() {
    // check if there are any commands which should be processed
    if (this.inputToBeProcessed.commands.length) {
      this.instances.pluginManager.run(this.inputToBeProcessed.commands, this.inputToBeProcessed.args);
    }
  }
}

**Comment by pmuens** [comment]
YAAU (Yet another architecture update):

The instances object just got removed.

```
// lib/Serverless.js
import CLI from './CLI';
import Config from './Config';
import YamlParser from './YamlParser';
import PluginManagement from './PluginManagement';
import Utils from './Utils';
import Service from './Service';

class Serverless {
  constructor() {

    this.config = new Config(this);
    this.yamlParser = new YamlParser(this);
    this.pluginManager = new PluginManager(this);
    this.utils = new Utils(this);
    this.service = new Service(this);

    this.cli = new CLI(
      this,
      this.config.interactive,
      this.service.getAllStages(),
      this.service.getAllRegionsInStage
    );

    // load config
    this.config = this.config.loadConfig();
    // load service
    this.service = this.service.loadService(this.config);
    // load all plugins
    this.instances.pluginManager.loadAllPlugins(this.service.getServicePlugins());
    // Input will check if the user has entered "help" or "version"
    // and will return with the corresponding CLI action. Otherwise it'll create an 
    // array with the commands and an object with the options the user has entered 
    // which is then passed to the run method of the PluginManager instance
    this.inputToBeProcessed = this.cli.processInput();
  }

  run() {
    // check if there are any commands which should be processed
    if (this.inputToBeProcessed.commands.length) {
      this.pluginManager.run(this.inputToBeProcessed.commands,
          this.inputToBeProcessed.options);
    }
  }
}
```

**Comment by pmuens** [comment]
I'll just add a link to the `Serverless.js` file which is basically the file which is discussed here.

This way this issue will always be up to date:
https://github.com/serverless/serverless/blob/v1.0/lib/Serverless.js

**Comment by franz-josef-kaiser** [comment]
@pmuens only when you add a link to a blob:

https://github.com/serverless/serverless/blob/4c65d79f3cff4fefb2476042a227705f8d9f483f/lib/Serverless.js

**ProTip:** Press _Y_ when viewing a file to update the Url to point to the blob/ commit.
