### ISSUE TITLE
HTTP request schema validation not working in the typescript starter

### ISSUE THREAD

**Issue by Edwinny** [serverless/serverless#11186]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When creating the a new project using the aws-nodejs-typescript template, request validation is not working. The README states:

**Test your service**

This template contains a single lambda function triggered by an HTTP request made on the provisioned API Gateway REST API `/hello` route with `POST` method. The request body must be provided as `application/json`. The body structure is tested by API Gateway against `src/functions/hello/schema.ts` JSON-Schema definition: it must contain the `name` property.

- requesting any other path than `/hello` with any other method than `POST` will result in API Gateway returning a `403` HTTP error code
- sending a `POST` request to `/hello` with a payload **not** containing a string property named `name` will result in API Gateway returning a `400` HTTP error code
- sending a `POST` request to `/hello` with a payload containing a string property named `name` will result in API Gateway returning a `200` HTTP status code with a message saluting the provided name and the detailed event processed by the lambda

However amending the provide mock to not include the 'name' parameter and then running the provided invoke command will still return a 200 rather than the 400 quoted above.

Additionally, updating all packages to latest doesn't resolve the issue

### Service configuration (serverless.yml) content

```yaml
N/A (just create the starter and use as-is - only modifying the mock to remove the required 'name' parameter)
```

### Command name and used flags

yarn sls invoke local -f hello --path src/functions/hello/mock.json

### Command output

```shell
yarn run v1.22.19
$ D:\Development\foo\node_modules\.bin\sls invoke local -f hello --path src/functions/hello/mock.json
{
    "statusCode": 200,
    "body": "{\"message\":\"Hello undefined, welcome to the exciting Serverless world!\",\"event\":{\"headers\":{\"Content-Type\":\"application/json\"},\"body\":{\"foo\":\"Frederic\"},\"rawBody\":\"{\\\"foo\\\": \\\"Frederic\\\"}\"}}"
}
Done in 2.70s.
```

### Environment information

```shell
$ sls --version
Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2

(Windows)
```

**Comment by Edwinny** [comment]
Hey @pgrzesik  - I haven't tried on a deployed version, but the same behaviour happens when using the sls offline plugin (not sure if that's expected to work?).

They do have a bug that sounded similar to this which was resolved a couple of weeks ago, so I assume request validation _should_ work via their plugin?
https://github.com/dherault/serverless-offline/issues/1331

**Comment by pgrzesik** [comment]
I _think_ it should work for `serverless-offline`, but if you're seeing similar behavior then you might want to report a bug at `offline` repository.

**Comment by pgrzesik** [comment]
Thanks a lot for sharing that @Edwinny - do you think we can close this issue?

**Comment by Edwinny** [comment]
Definitely :thumbsup:
