### ISSUE TITLE
Serverless CLI defaults to Tencent Regardless of Region (Living in SEA (PH) )

### ISSUE THREAD

**Issue by tistisman** [serverless/serverless#11198]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The issue is, we are outside china, yet the CLI defaults to tencent, setting up the Environment Variable in Windows doesn't work either
![image](https://user-images.githubusercontent.com/74032291/176695489-33563217-714e-4f5b-a0fd-a0181c2b3127.png)

and adding env just out right breaks the code
SERVERLESS_PLATFORM_VENDOR=aws
![image](https://user-images.githubusercontent.com/74032291/176696030-cb281893-596e-4b1d-9c8f-1f5be9e7fc36.png)

installing the component also doesn't work

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless

### Command output

```shell
serverless
 当前未检测到 Serverless 项目，是否希望新建一个项目？ No
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
Tencent CLI: 3.21.6 (binary)
```

**Comment by pgrzesik** [comment]
Hello @tistisman - are you by any chance using `China Standard Time` as your timezone? That's how we're handling the triage process.

**Comment by medikoo** [comment]
> The issue is, we are outside china, yet the CLI defaults to tencent, setting up the Environment Variable in Windows doesn't work either

Detection is based on timezone set on the computer. You may be outside of China but if your computer has the Clock set to Chinese region you'll have this default.

You can override this by e.g.  `SLS_GEO_LOCATION=eu` 

> SERVERLESS_PLATFORM_VENDOR=aws

This is components specific flag, it only differentiates between Tencent components engine and AWS components engine which was removed from the Framework (hence the message)

**Comment by tistisman** [comment]
> 

I'll going to do it now and check

**Comment by tistisman** [comment]
> Hello @tistisman - are you by any chance using `China Standard Time` as your timezone? That's how we're handling the triage process.

yes I'm using the timezone of HK, I'll try to change it now and check

**Comment by tistisman** [comment]
> Hello @tistisman - are you by any chance using `China Standard Time` as your timezone? That's how we're handling the triage process.

your solution work thank you very much

> > The issue is, we are outside china, yet the CLI defaults to tencent, setting up the Environment Variable in Windows doesn't work either
> 
> Detection is based on timezone set on the computer. You may be outside of China but if your computer has the Clock set to Chinese region you'll have this default.
> 
> You can override this by e.g. `SLS_GEO_LOCATION=eu`
> 
> > SERVERLESS_PLATFORM_VENDOR=aws
> 
> This is components specific flag, it only differentiates between Tencent components engine and AWS components engine which was removed from the Framework (hence the message)

I haven't tried adding the env since changing my time works,

thank you

**Comment by pgrzesik** [comment]
@tistisman you can also follow suggestion from @medikoo - that way you don't need to change your timezone 👍
