### ISSUE TITLE
Include cold start duration in http API Gateway timeout computation 

### ISSUE THREAD

**Issue by CorentinDoue** [serverless/serverless#11222]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

## Current behaviour

Using **httpApi** events, the timeout of the http API Gateway route is computed from the function timeout:

https://github.com/serverless/serverless/blob/8d4bf4fbfdf79950e92ad4fbb171f6fa15b11886/lib/plugins/aws/package/compile/events/http-api.js#L618

Indeed the API gateway timeout cannot exceed 30 s and must be greater than the lambda timeout to avoid getting a 503 with a successful lambda execution. 

## Issue

The cold start of the lambdas is not considered. 

I recently had a bug on one of my projects: a lambda deployed with the default timeouts (6s for lambda and 6,5s for API Gateway) took 5s to execute and had a cold start of 2s. The lambda execution time was below its timeout the process went well, but the API Gateway sent back a 503 because the service lambda took a total of 7s to complete the task.  

### Proposed solution (optional)

1. **behave as the integration with API Gateway v1**
 
   **http** events don't set the timeout of the API Gateway integration. The default timeout is used, [it's the maximum value: 29s](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration.html#cfn-apigateway-method-integration-timeoutinmillis)

   => Remove the definition of the property `TimeoutInMillis` of the API gateway integration (and the no more needed computation line) => [the default value of 30s will be applied](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-timeoutinmillis).

https://github.com/serverless/serverless/blob/8d4bf4fbfdf79950e92ad4fbb171f6fa15b11886/lib/plugins/aws/package/compile/events/http-api.js#L633-L635
 
2. **add the maximum cold start time**

  The maxium cold start is 10s. (I didn't find this in the official AWS doc but found it in [this interesting article](https://medium.com/@david.alvares.62/cold-start-can-you-run-code-for-free-with-serverless-aws-lambda-19fad4c8ff8e)) 

  Add these 10s to the computation

https://github.com/serverless/serverless/blob/8d4bf4fbfdf79950e92ad4fbb171f6fa15b11886/lib/plugins/aws/package/compile/events/http-api.js#L618

I prefer the first proposition to keep the two API gateway integration as close as possible. WDYT?

**Comment by mnapoli** [comment]
Hi, thanks for opening this, that makes a lot of sense.

I would also go with option 1, I see no added value to having a timeout set on API Gateway _and_ Lambda: that can only create problems by duplicating the same information.

We'll wait for @pgrzesik's perspective before merging #11223, but I'll go ahead and review it in the meantime.

**Comment by medikoo** [comment]
Having the timeout set on lambda was to improve DX, and minimize the possibility of a scenario when the function succeeds but the request fails - such scenarios are very confusing, as they are not clearly communicated by AWS, and it's hard to deduct what happened (at least that was the case at the time of implementation, maybe it's improved now).

Indeed, a cold start breaks the arithmetic here. Still, if I understand correctly, in the worst case, we'll see the same error as we would see when no timeout is configured. So the only downside here is that our DX improvement didn't apply as intended.

I definitely wouldn't try to add a 10s margin here, as cold start affects just the first (non-provisioned) invocation, and reduced timeout is likely to become a real issue for the following invocations.

I think it's good to keep things the way they are unless things have changed on the AWS side, and a scenario where lambda succeeds and the request fails is well communicated, and clear upfront.

**Comment by CorentinDoue** [comment]
> Having the timeout set on lambda was to improve DX, and minimize the possibility of a scenario when the function succeeds but the request fails

@medikoo, it actually does the contrary. Indeed **no API GW timeout specified** = **default API GW timeout** = **maximum API GW** = **30s**. 

The current computed API GW timeout is always lower than those 30s. So it creates some situation where the lambda succeeds but the API GW returns a 503 which could have been avoided if the API GW timeout were 30s. It happened to me last month and happened to one of my colleagues 3 months ago.

**Comment by medikoo** [comment]
> So it creates some situation where the lambda succeeds but the API GW returns a 503 which could have been avoided if the API GW timeout were 30s

@CorentinDoue Thanks for further clarifications, Indeed I mixed function timeout with endpoint timeout. 

In such case I totally agree, it doesn't make much sense to set a timeout on API Gateway, as setting such doesn't prevent anything (just risks observing the issue you've approached).

Great thanks for raising that 👍
