### ISSUE TITLE
Implement Main CLI integration

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1123]
The Main CLI system will drive parsing Arguments, validating them and providing that configuration to the rest of the system

**Comment by flomotlik** [comment]
Testing for the CLI class should also be done with node-suppose as described in #1084

**Comment by pmuens** [comment]
Closed with

https://github.com/serverless/serverless/pull/1177
https://github.com/serverless/serverless/pull/1173
https://github.com/serverless/serverless/pull/1170
https://github.com/serverless/serverless/pull/1144
