### ISSUE TITLE
lint-staged throwing errors on pre-commit hook

### ISSUE THREAD

**Issue by pjmattingly** [serverless/serverless#11249]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

On pre-commit, `lint-staged` throws:

```
husky > pre-commit (node v12.22.12)
file:///home/peter/dev_personal_development/serverless/node_modules/lint-staged/lib/index.js:112
    if (runAllError?.ctx?.errors) {
                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
husky > pre-commit hook failed (add --no-verify to bypass)
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by pjmattingly** [comment]
I traced the issue to:

```
package.json
...
"lint-staged": "^13.0.3",
...
```

The new lint-staged version (@13) states it drops support for node 12:

```
v13
Since v13.0.0 lint-staged no longer supports Node.js 12. Please upgrade your Node.js version to at least 14.13.1, or 16.0.0 onward.
```

see: https://www.npmjs.com/package/lint-staged

Thus when attempting to commit with node 12, issues arise naturally. The solution then is capping `lint-staged` at version 12 until Serverless can be moved to a higher node version. I have submitted a pull-request here: #11250

**Comment by pgrzesik** [comment]
Hey @pjmattingly - thanks a lot for catching that and reporting. After thinking about it for a while, I think we should be okay with keeping it in `v13` - it's only a `devDependency` that is used for development purposes and does not impact Node 12 compatibility from the perspective of a user. The only situation where that becomes a problem is where a maintainer wants to use Node 12 while doing a commit locally but I think it's a minor inconvenience that can be addressed by upgrading Node version. Sooner or later we're going to drop Node 12 support anyway as it's already EOL. 

The only thing that could be useful then to clarify is to specify that during development, you should be using at least Node 14. 

What do you think @medikoo?

**Comment by pjmattingly** [comment]
> The only thing that could be useful then to clarify is to specify that during development, you should be using at least Node 14.

Sure I'll make a minor change and shoot a PR.

Thanks!

**Comment by pjmattingly** [comment]
done, see: https://github.com/serverless/serverless/issues/11249

**Comment by pgrzesik** [comment]
Thanks, closing this one

**Comment by medikoo** [comment]
@pjmattingly @pgrzesik, this upgrade was intentional. I've assumed that it's fine for all dev dependencies (which do not play part in running unit tests) to support at minimum the current Node.js LTS version.

**Comment by taoliu12** [comment]
check your node -v to make sure it is greater than the required version for lint-staged
