### ISSUE TITLE
Serverless doesn't seem to work with TypeScript 4.7

### ISSUE THREAD

**Issue by gtamas** [serverless/serverless#11242]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

My app works fine with Serverless and TS 4.6.x, but after upgrading to TS 4.7 (latest), I get this when running "serverless print" :

"Cannot load "serverless.ts": Initialization error: Error: Debug Failure. False expression: Non-string value passed to ts.resolveTypeReferenceDirective, likely by a wrapping package working with an outdated resolveTypeReferenceDirectives signature. This is probably not a problem in TS itself."

I'm using Node 14.18 and these:

├── @serverless/typescript@3.19.0
├── serverless@3.21.0
├── serverless-offline@8.8.1
└── typescript@4.7.4

It seems TS 4.7 is not supported? 

### Service configuration (serverless.yml) content

```yaml
const serverlessConfiguration: AWS = {
  service: "app",
  frameworkVersion: "3",
  configValidationMode: "error",
  plugins: [

  ]
}
```

### Command name and used flags

serverless print

### Command output

```shell
nvironment: linux, node 14.18.2, framework 3.21.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot load "serverless.ts": Initialization error: Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
```

### Environment information

```shell
Framework Core: 3.21.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hey @gtamas - what version of `ts-node` do you have installed? Did you try upgrading it?

**Comment by gtamas** [comment]
Yes tried and that solved it. Thx

**Comment by gtamas** [comment]
I've installed the latest 10.9.1. It worked fine after that, so your problem must be different. Do you also have @serverless/typescript? Maybe you need to update that too.

**Comment by gmicek** [comment]
`npm install -D ts-node@latest` solved it for me (aka upgrading ts-node)
