### ISSUE TITLE
${aws:accountID} breaks when you try to deploy local

### ISSUE THREAD

**Issue by NSerbin** [serverless/serverless#11260]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When you try to attach Policies using the `iam.role.managedPolicies` and put the ARN, if u use the $(aws:accountId} and try to deploy it locally it breaks because cant resolve the accountId

This is an example
`iam:
  role:
    name: ${param:environment}-${param:vertical}-${param:service}-${param:process}-role
    managedPolicies:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      - 'arn:aws:iam::${aws:accountId}:policy/${param:environment}-${param:vertical}-core-a'
      - 'arn:aws:iam::${aws:accountId}:policy/${param:environment}-${param:vertical}-growth-b'
      - 'arn:aws:iam::${aws:accountId}:policy/${param:environment}-${param:vertical}-core-c'
      - 'arn:aws:iam::${aws:accountId}:policy/${param:environment}-${param:vertical}-core-d'
`

### Proposed solution (optional)

put an optional like we use in params or in CLI .....

**Comment by pgrzesik** [comment]
Hello @NSerbin - thanks for reporting and sorry you've run into trouble. Could you clarify what do you exactly mean by "deploy it locally"?

**Comment by NSerbin** [comment]
Yes!

Well, as I said when I wanna do offline tests (previously to deploy in our environments ), we used the serverless offline plugin this one, tried to deploy and cant recognizes the `${aws:accountId}`.

If this `${aws:accountId}` can have an optional like the `stage` or `region`.. I can make something like `${opt:accountId,'local'}`
or a different way to process it..

I tried with params and didn't work.

The only way I found is using environment vars with gitlab CI but this isn't a choice for us....

**Comment by pgrzesik** [comment]
Hey @NSerbin, thanks a lot for the clarification. I see how that can be a problem, I'm going to close this issue as it's the same problem as reported here: https://github.com/serverless/serverless/issues/11263 and it concerns a wider-range of variable sources. Let's continue discussion there
