### ISSUE TITLE
Lambda policies include logs:CreateLogStream even when disableLogs is true

### ISSUE THREAD

**Issue by perrin4869** [serverless/serverless#11264]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

This looks like an unintended effect.
When using [`disableLogs: true`](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#functions) for a function in `serverless.yml`, the CF entry for its log group is skipped. However, the function will still create a `LogGroup` when executed because it [has the `logs:CreateLogGroup`](https://github.com/serverless/serverless/blob/bb37f4fe75ff5234fae48ada433cd52ddf51cb91/lib/plugins/aws/package/lib/iam-role-lambda-execution-template.json#L24) action allowed.
I am not sure what a fix would look like, because `disableLogs` is present at a function level, and the IAM role is present at the stack level, however...

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.21.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

Edit: It would be a breaking change, but maybe these default policies should be removed and left up to individual users to add individually as they see fit? I do think most users would want them enabled though, so not sure

**Comment by perrin4869** [comment]
https://yellowdesert.consulting/2019/09/28/cloudwatch-logs-preventing-orphaned-log-groups/

**Comment by pgrzesik** [comment]
Hey @perrin4869, thanks a lot for reporting. Did you experience that issue yourself? When logs are disabled, we're additionally adding an explicit deny for `logs:PutLogEvents` - is the group created if the function cannot put log events?

**Comment by perrin4869** [comment]
Yeah, I experienced it myself.
Oh, I see! I didn't notice the explicit deny... but yeah, the `LogGroups` are created anyways. I guess an additional `deny` on `log:CreateLogGroup` would be required then?

**Comment by perrin4869** [comment]
hm... maybe it is related to the fact that it is using the `AWSLambdaVPCAccessExecutionRole` policy, which has an `Allow` on `logs:CreateLogGroup`, actually?

**Comment by perrin4869** [comment]
Sorry, I see what happened! I had removed the `Deny` policy because was causing the deployment to fail due to it making the policy become too big (it applied to over 50 lambdas). So sorry, this was a problem on my end!

**Comment by pgrzesik** [comment]
No worries, thanks a lot for clarification @perrin4869. I'm happy you were able to resolve your issue 🙌
