### ISSUE TITLE
TypeError: CloudFormation is not a constructor function

### ISSUE THREAD

**Issue by pjmattingly** [serverless/serverless#11281]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When attempting to setup integration testing, the following error is shown:

```
TypeError: CloudFormation is not a constructor function
    at module.exports (/home/peter/dev_personal_development/serverless/node_modules/type/lib/resolve-exception.js:12:14)
    at module.exports (/home/peter/dev_personal_development/serverless/node_modules/type/constructor/ensure.js:18:9)
    at resolveClientData (/home/peter/dev_personal_development/serverless/node_modules/@serverless/test/aws-request.js:31:11)
    at awsRequest (/home/peter/dev_personal_development/serverless/node_modules/@serverless/test/aws-request.js:41:41)
    at /home/peter/dev_personal_development/serverless/scripts/test/integration-setup/index.js:209:30
    at Object.<anonymous> (/home/peter/dev_personal_development/serverless/scripts/test/integration-setup/index.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

Looking closer at the call stack.

index.js
```
describeResponse = await awsRequest('CloudFormation', 'describeStacks', {
  StackName: SHARED_INFRA_TESTS_CLOUDFORMATION_STACK,
});
```

aws-request.js
```
const instance = getClientInstance(...resolveClientData(clientOrClientConfig));

--

return [ensureConstructor(clientOrClientConfig), {}];
```

ensure.js
```
return resolveException(value, errorMessage, options);
```

In ensure.js this code returns false, which results in the exception:
```if (is(value)) return value;```
where `is()` tests if `value` is a function which it clearly isn't, as in `index.js` a string is passed in.

Checking the dependencies `CloudFormation` isn't installed by default, but installing it does not change the error.

I was hoping to run integration testing to resolve #11267.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
npm run integration-test-setup

> serverless@3.21.0 integration-test-setup /home/peter/dev_personal_development/serverless
> node ./scripts/test/integration-setup/index.js

ℹ serverless Starting setup of integration infrastructure...
ℹ serverless Checking if integration tests CloudFormation stack already exists...

/home/peter/dev_personal_development/serverless/node_modules/essentials/index.js:21
                throw reason;
                ^

TypeError: CloudFormation is not a constructor function
    at module.exports (/home/peter/dev_personal_development/serverless/node_modules/type/lib/resolve-exception.js:12:14)
    at module.exports (/home/peter/dev_personal_development/serverless/node_modules/type/constructor/ensure.js:18:9)
    at resolveClientData (/home/peter/dev_personal_development/serverless/node_modules/@serverless/test/aws-request.js:31:11)
    at awsRequest (/home/peter/dev_personal_development/serverless/node_modules/@serverless/test/aws-request.js:41:41)
    at /home/peter/dev_personal_development/serverless/scripts/test/integration-setup/index.js:209:30
    at Object.<anonymous> (/home/peter/dev_personal_development/serverless/scripts/test/integration-setup/index.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@3.21.0 integration-test-setup: `node ./scripts/test/integration-setup/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless@3.21.0 integration-test-setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peter/.npm/_logs/2022-07-26T05_56_05_890Z-debug.log
```

### Environment information

```shell
sls --version
Framework Core: 3.21.0
Plugin: 6.2.2
SDK: 4.3.2
```
```

**Comment by pgrzesik** [comment]
Hey @pjmattingly, thanks for reporting. It seems like it has been omitted when upgrading `awsRequest`. I've published a PR that should address this issue.

Side note: Please be careful with maintaining the integration test infra on your own, it can become expensive due to provisioning of a Kafka cluster

**Comment by pjmattingly** [comment]
Thanks, I'll get the latest and try again.

Related to running integration testing, @medikoo had asked me to as per [#11267 ] (https://github.com/serverless/serverless/pull/11267#pullrequestreview-1049588145). If there's a potential cost associated, would it be possible to run an integration testing on this branch on the Serverless side?

**Comment by pgrzesik** [comment]
Hey @pjmattingly - I think that might be harder to achieve, @medikoo do you know if we ever did something like that, where we allow people to run integration tests on our infra?

**Comment by medikoo** [comment]
@pjmattingly I think it shouldn't be problematic to run integration tests in scope of own account, and assuming you'd tear down infra after doing that, I think cost should be neglible.

Nonetheless if you want to avoid setting up infra, you can run all tests that do not depend on it via:

```
npx mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check --max-workers=20 "test/integration/{*.test.js,aws/*.test.js}"
```


And that already provides enough coverage here I think

**Comment by pjmattingly** [comment]
Great! Thanks, I'll give that a try.

Then also, if this works, would you mind if I added something to integration testing about this? I'm guessing someone else might like to do the testing without risking cost.

**Comment by pjmattingly** [comment]
A small modification here. In the [test README](https://github.com/serverless/serverless/blob/main/test/README.md#aws-integration-tests) we have this note:

```
AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=xxx npm run integration-test-run-all
```

And so we have to add the environment variables to the npx run in the same way:

```
AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx npx mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check --max-workers=20 "test/integration/{*.test.js,aws/*.test.js}"
```

However, these environment variables (`AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY`) **have to be valid.** That is, even though these integration tests might not appear to touch AWS proper, authentication seems to take place anyway, even if nothing is ran on the AWS side.

Otherwise strange errors crop up:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

```
ServerlessError: The security token included in the request is invalid.
```
```
UnrecognizedClientException: The security token included in the request is invalid.
```

```
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

etc.
