### ISSUE TITLE
Http Api (API Gateway v2) docs are not rendering properly in the docs site

### ISSUE THREAD

**Issue by KillDozerX2** [serverless/serverless#11290]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When going through the docs for Http Api (API Gateway v2), these aren't rendering properly in the serverless docs site. 

Result
![Screenshot 2022-07-28 at 12 16 24 PM](https://user-images.githubusercontent.com/29596786/181438974-e792b19b-3169-4352-8e38-14c92aeb59ef.jpg)
 
I don't think this is just an issue with me since other event docs are rendering properly.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by pgrzesik** [comment]
Hey @KillDozerX2 - we are aware of the problem and are currently looking for a solution. Let's keep any discussions, if needed, in this issue: https://github.com/serverless/serverless/issues/11291

**Comment by KillDozerX2** [comment]
Understood, sorry for creating a duplicate. I tried searching through issues to see if there were any duplicates but couldn't find one.

**Comment by pgrzesik** [comment]
No problem @KillDozerX2 - there was one other report and some other comments and I just decided to create a single issue to track progress 👍

**Comment by mnapoli** [comment]
FYI this should all be fixed now.
