### ISSUE TITLE
function run bug - Python

### ISSUE THREAD

**Issue by telson** [serverless/serverless#1129]
Serverless run fails where python interpreter doesn't.  The problem is with returned JSON.  If the returned JSON is manually stringified, it succeeds.

```bash
$ sls function run
Serverless: Running MusicTableEditor...
Serverless: -----------------
Serverless: Failed - This Error Was Thrown:
Serverless: SyntaxError: Unexpected end of input
```

Yet the code completes successfully when run outside serverless:
```bash
$ python handler.py
Operation is: scan
{u'Count': 1, u'Items': [{u'Album Title': u'An Honest Mistake (UK)', u'Artist': u'The Bravery', u'stared': True, u'SongTitle': u'An Honest Mistake', u'Year': Decimal('2005')}], u'ScannedCount': 7, 'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': 'xxx'}}
```

Outside of serverless, the returned dictionary is successfully represented as a string.  Stringifying it in the handler enables serverless to succeed. 

```bash
$ tail -n8 handler.py
    #return operations[operation](kwargs)               # Raises error 
    return str(operations[operation](kwargs))           # Succeeds 

if __name__ == '__main__':
    with open('event.json', 'r') as f:
        data = json.load(f)
        print(handler(data, None))
```

**Environment**
- serverless@0.5.5
- OS X: 10.11.4
- python: 2.7.11

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by woodlandh** [comment]
I realize this is closed, but for documentation's sake I've encountered this bug as well. Casting as a string was a successful work-around for me, too.

* serverless@0.5.6
* OS X 10.11.5
* python 2.7.11
