### ISSUE TITLE
Issue with rendering documentation

### ISSUE THREAD

**Issue by pgrzesik** [serverless/serverless#11291]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I decided to create a catch-all issue for current issues with documentation rendering. We are aware of the problem and are looking for a solution and will keep everyone posted.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by mnapoli** [comment]
All good, it was a webflow bug that is now fixed 👍
