### ISSUE TITLE
Please run "serverless deploy" to deploy your service

### ISSUE THREAD

**Issue by taminhhieu31gl** [serverless/serverless#11296]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [ ] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello team, currently when I try to run command "serverless deploy function ...", I'm facing this issue below
  _**The function "XXXXXXXX" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.**_
Can team help me resolve it?

My Environment Information 
---------------------------
     Operating System:          linux
     Node Version:              10.24.1
     Framework Version:         1.68.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sudo serverless deploy --verbose -s dev function -f XXXX -c XXXX.yml

### Command output

```shell
The function "XXXXXXXX" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.
```

### Environment information

```shell
Framework Core: 1.68.0
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```

**Comment by pgrzesik** [comment]
Hey @taminhhieu31gl, I'm sorry, but you're on a heavily outdated version of the Framework, and you still marked that you're using the latest version. Why is that?

**Comment by taminhhieu31gl** [comment]
Hi @pgrzesik , because I'm not sure that this issue from serverless version. I need some suggestion before I update to latest, I'm confused that if it impact to my system

**Comment by pgrzesik** [comment]
I would recommend updating to the latest version. Also, it doesn't seem to be an issue, in error message it clearly says that you didn't yet deploy the service and it asks you to do `serverless deploy` first before you can deploy only specific functions. Did you have a chance to try that? I'm going to close the ticket for now, let me know if the problem is different.
