### ISSUE TITLE
Add node16x to the allowed runtimes for aws

### ISSUE THREAD

**Issue by chanan** [serverless/serverless#11309]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS now supports node 16, however serverless will throw an error if runetime is set to node16x. Removing configValidationMode: error will change the error to a warning which will allow the deploy to finish successfully.

### Proposed solution (optional)

Add "nodejs16.x" to the allowed runtime

**Comment by medikoo** [comment]
@chanan it's a while we recognized `node16.x` runtime in a configuration: 

https://github.com/serverless/serverless/blob/fb8852e2e893e0f0b98cc54fcab01883aad13239/lib/plugins/aws/provider.js#L598

Ensure to rely on the latest version

**Comment by chanan** [comment]
Sorry, I thought i just updated to latest but I didn't. My bad.
