### ISSUE TITLE
sls --debug command not launching node debugger

### ISSUE THREAD

**Issue by jesucarr** [serverless/serverless#1132]
I'm using the plugin `serverless-offline` to run my API locally. I'm also using `serverless-runtime-babel` to use ES6. When I try to run sls in debug mode with the `--debug` flag, it only outputs some logs to the console. I would expect it to work as the node `--debug` flat, that it will launch a debugger in default port 5858, to which I can attach a debugging tool (and set breakpoints, etc.) like [node-inspector](https://github.com/node-inspector/node-inspector) or [VS Code](https://code.visualstudio.com/).

Are there plans to make possible debugging (breakpoints, etc.) with `serverless-offline` and `serverless-runtime-babel` for the next version?

**Comment by aheissenberger** [comment]
I use this to debug local:
`node-debug $(type -p serverless) function run XXX`

this should work with `serverless-offline` too but I have not tested it

**Comment by flomotlik** [comment]
@jesucarr we're not sure yet how serverless-offline and our development for offline tooling will work in the future. We're currently discussing this internally and will take this into consideration. For now I'll close this issue.

**Comment by rupakg** [comment]
@eslamhefnawy I want to do exactly what @jesucarr wants to do? sls --debug to internally run node with debugger on 5858. This issue was closed a year ago but is there new solution or workaround in place?

**Comment by HyperBrain** [comment]
@rupakg You can run serverless with the node debugger activated as you can do with any other node app, i.e. run `node --inspect <serverless binary> ...` and node will automatically run and enable the debugger and print the url that you can use with Chrome to debug. Additionally you can add `--debug-brk` to break on entry or add some `debugger()` commands to your code.

We install serverless locally with our projects as dev dependency which makes it even more convenient:
`node --inspect --debug-brk node_modules/serverless/bin/serverless offline`.

**Comment by mymail4blogs** [comment]
I am trying in windows and getting error
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list

**Comment by rahul-sivalenka-wtc** [comment]
> I am trying in windows and getting error
> basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
> ^^^^^^^
> 
> SyntaxError: missing ) after argument list

I got the same. Is there a solution for this in Windows?

**Comment by ManuelMos** [comment]
> > I am trying in windows and getting error
> > basedir=$(dirname "$(echo "$0" | sed -e 's,,/,g')")
> > ^^^^^^^
> > SyntaxError: missing ) after argument list
> 
> I got the same. Is there a solution for this on Windows?

Same here. Any solutions so far?

**Comment by JoePercy-Capp** [comment]
@mymail4blogs @rahul-sivalenka @ManuelMos 

Try changing `./node_modules/.bin/serverless` to `node_modules/serverless/bin/serverless`?

**Comment by therealgaryj** [comment]
That worked for me @JoePercy-Capp 👍

**Comment by ameliep0032** [comment]
I'm working on windows and trying to use this script:
   "sls:debug": "SET SLS_DEBUG=* && node --inspect ./node_modules/.bin/sls invoke local --function NotificationService --stage development --path "
   
and having this issue:
`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
                 ^^^^^^^`
where the underlining ^ is under dirname. 

Still getting the same message as others here:
SyntaxError: missing ) after argument list

Any thoughts on how to resolve it?
