### ISSUE TITLE
Support self-hosted RabbitMQ as event source

### ISSUE THREAD

**Issue by j-adamczyk** [serverless/serverless#11335]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently only AmazonMQ (AWS managed RabbitMQ) is supported as an event source for Lambda ([relevant question in discussions](https://github.com/serverless/serverless/discussions/11327)) Support for self-hosted instances should be added to Serverless Framework, similarly to Kafka (both AWS-managed and self-hosted versions are already supported).

### Proposed solution (optional)

Existing AmazonMQ  implementation in Serverless can be used as a starting point.

**Comment by pgrzesik** [comment]
Hey @j-adamczyk - I think there might be some misunderstanding in the discussion. I don't think this ticket makes a lot of sense currently as it's impossible to implement it until AWS explicitly adds support for self-hosted rabbit MQ instances. That was the same case with Kafka - there's a totally different event type for self-hosted Kafka instances and it wasn't possible to provide an implementation before AWS introduced it on their side.

cc @mnapoli

**Comment by j-adamczyk** [comment]
@pgrzesik by self-hosted I mean running RabbitMQ just on EC2 instances. It is indeed possible currently, as I'm running this setup with Kubernetes and RabbitMQ Cluster Operator. Is this not the same with Kafka - "self-hosted" meaning Kafka cluster on EC2 instances?

**Comment by j-adamczyk** [comment]
@pgrzesik oh, I see now, the AWS itself does not support self-hosted RabbitMQ as event source at all. Sorry for the confusion.

**Comment by pgrzesik** [comment]
No worries @j-adamczyk 👍 That's exactly the case - AWS does not support self-hosted RabbitMQ instances, but it might change in the future as it was the case with Kafka.
