### ISSUE TITLE
Add support for naming EventBridge resources

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/serverless#11360]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

In environments where a naming scheme is strictly defined, there needs to be the potential to specify a custom name so that it properly fits in the naming scheme.

### Proposed solution (optional)

Support for a name property is added (same property as what's used for other function events) and, where the RuleName variable is defined in lib/plugins/aws/package/compile/events/event-bridge/index.js, the first option used is the custom name passed in, and in cases where that isn't present, the fallback is the existing logic that's been added.

I have draft changes locally to add this feature in, but wanted some sign-off to ensure that there wasn't a parallel effort for this sort of feature elsewhere

**Comment by ROSeaboyer** [comment]
Bumping this issue up; any thoughts on this either way?

**Comment by medikoo** [comment]
@ROSeaboyer sorry for not looking into it earlier. This proposal looks good to me. Can you reopen the PR and ensure it's up to date with `main` branch?

**Comment by ROSeaboyer** [comment]
@medikoo No worries; reopened as #11690
