### ISSUE TITLE
Serverless v1 using NodeJS 12.x for AWS Custom Resource Lambda

### ISSUE THREAD

**Issue by icholy** [serverless/serverless#11368]
### Is there an existing issue for this?

Same as #10432 but for v1

### Use case description

The v1 branch of serverless uses the `nodejs12.x` runtime for aws custom resource lambdas. Starting November 14th 2022, AWS will no longer allow deploying lambdas using `nodejs12.x`. This will make it impossible to deploy projects without updating to serverless v2.

### Proposed solution (optional)

Update the v1 branch to use `nodejs14.x` for the custom resource lambdas.

**Comment by medikoo** [comment]
@icholy v1 is no longer maintained, please upgrade to v3

**Comment by icholy** [comment]
Our teams are in the process of migrating, but we might not hit the deadline. There does seem to be some precedent for backporting changes https://github.com/serverless/serverless/commits/v1

**Comment by icholy** [comment]
If you're no longer accepting changes to v1, that should be made clear in the [README](https://github.com/serverless/serverless/blob/v1/README.md)

**Comment by medikoo** [comment]
@icholy v1 is officially deprecated for a long time: https://www.npmjs.com/package/serverless/v/1.83.3

**Comment by dazza-codes** [comment]
What about serverless v2, which is also impacted by this.

**Comment by medikoo** [comment]
> What about serverless v2, which is also impacted by this.

It's also no longer maintained, please upgrade to v3
