### ISSUE TITLE
`serverless function run` does not show Python output when running locally

### ISSUE THREAD

**Issue by chuckus** [serverless/serverless#1137]
Behavour I expect:
For the simple lambda
```python
from __future__ import print_function

import json
import logging

log = logging.getLogger()
log.setLevel(logging.DEBUG)

def handler(event, context):
    log.debug("Received event {}".format(json.dumps(event)))
    print("The quick fox jumps over the lazy frog")
    return {}
```
and I run `serverless function run`, that I expect to see
```
Serverless: Running test...  
The quick fox jumps over the lazy frog
Serverless: -----------------  
Serverless: Success! - This Response Was Returned:  
Serverless: {}  
```

What I actually see:
The print message is missing.
```
Serverless: Running test...  
Serverless: -----------------  
Serverless: Success! - This Response Was Returned:  
Serverless: {}  
```

Output to stdout works for nodejs functions, but it would be ideal if this was the same case for Python functions as it would be extremely helpful for debugging.

serverless: 0.5.5
Python: 2.7.11
OS: Ubuntu 16.04
Node: 6.1.0

**Comment by godd9170** [comment]
+1

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
