### ISSUE TITLE
Issue While Extracting Serverless Framework YAML Parser

### ISSUE THREAD

**Issue by giusepperaffa** [serverless/serverless#11371]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have been trying to run the JavaScript code proposed in 2019 by @jacktuck in [#3318](https://github.com/serverless/serverless/issues/3318#issuecomment-503064800) within my environment. This is the simplified code (instrumented with three `console.log` commands to facilitate the analysis) that I have executed directly in my Linux shell after including it in a file (`node javascript-code.js`):
```
const fs = require('fs')
const path = require('path')
console.log('*** Before serverless import ***')
const Serverless = require('/usr/lib/node_modules/serverless');
console.log('*** After serverless import ***')
const sls = new Serverless();
console.log('*** After sls instance creation ***')
```
The line of code that is causing problems is where `new Serverless()` is (see command output).

**Note**:  The issue that I am reporting seems to be similar to the one documented [here](https://github.com/artilleryio/artillery/issues/1398#issue-1196497556), where the user shows the same error when running `slsart deploy`. However, in my case **no deployment** of any kind is involved, and I am **not** using [Artillery](https://github.com/artilleryio/artillery).      

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
*** Before serverless import ***
*** After serverless import ***
/usr/lib/node_modules/serverless/node_modules/type/lib/resolve-exception.js:14
	throw error;
	^

TypeError: undefined is not an array
    at module.exports (/usr/lib/node_modules/serverless/node_modules/type/lib/resolve-exception.js:12:14)
    at module.exports (/usr/lib/node_modules/serverless/node_modules/type/array/ensure.js:15:25)
    at new Serverless (/usr/lib/node_modules/serverless/lib/serverless.js:86:22)
    at Object.<anonymous> (/home/giuseppe/Desktop/serverless-framework-parser/javascript-code.js:6:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

### Environment information

```shell
====================
Serverless Framework
====================
Framework Core: 3.17.0
Plugin: 6.2.2
SDK: 4.3.2

======================
Additional Information
======================
OS: Ubuntu Linux 20.04
node version: v16.15.0
npm version:8.5.5
```

**Comment by medikoo** [comment]
@giusepperaffa it's not a bug. 2019 solution referred to v1 version of the Framework. While currently there's v3

**Comment by giusepperaffa** [comment]
@medikoo Thanks a lot for pointing that out. From what you said then, we cannot expect the [2019 solution](https://github.com/serverless/serverless/issues/3318#issuecomment-503064800) by @jacktuck to work with recent versions of the Serverless Framework. I will close this issue then, but, if my conclusion is incorrect, please get in touch. Thank you.

**Comment by giusepperaffa** [comment]
Closed, as it is not a bug. See above explanation provided by @medikoo.
