### ISSUE TITLE
Bucket name in exception within `ensure-valid-bucket-exists`

### ISSUE THREAD

**Issue by rca** [serverless/serverless#11387]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I'm working on a project where I got this error:

```
'ServerlessError: Could not locate deployment bucket. Error: The specified bucket does not exist\n    at AwsDeploy.ensureValidBucketExists [...]
```

The `deploymentBucket.name` value in the serverless.yaml file is set to an interpolated string; something like`serverless.${aws:accountId}.deploys`.  Since it's an interpolated string, it's not clear what the resulting bucket name is going to be.

### Proposed solution (optional)

I [created a patch](https://github.com/serverless/serverless/compare/main...rca:serverless:patch-1) that simply adds the bucket name to the exception and the error was immediately more useful:

```
      } catch (err) {
        throw new ServerlessError(
          `Could not locate deployment bucket: ${this.bucketName}. Error: ${err.message}`,
          'DEPLOYMENT_BUCKET_NOT_FOUND'
        );
      }
```

Per the PR contribution guidelines, I'm opening this issue prior to opening a PR.  Is this a satisfactory patch to contribute?

Thanks.

**Comment by medikoo** [comment]
@rca Great thanks for suggestion. Proposed patch looks good, we look forward the PR!

**Comment by rca** [comment]
Great, thanks @medikoo; PR #11389 opened.
