### ISSUE TITLE
Plugins that use plugins give error: Plugin is missing a setup function

### ISSUE THREAD

**Issue by robblovell** [serverless/serverless#11388]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Describe the bug

When attempting to use a serverless plugin that uses an external framework which itself uses plugin objects with functions in its configuration, an error `Plugin is missing a setup function` occurs. This appears to be a capability missing when using serverless.js or serverless.ts configuration files.

With the serverless-esbuild plugin, it uses the esbuild framework. The esbuild framework can use plugins that use objects in its configuration. These functions are filtered out by the serverless framework yielding the error:

✘ [ERROR] [plugin hello] Plugin is missing a setup function

I am raising this here because it might not be a problem with the esbuild plugin, but a larger issue with the serverless framework and plugins that use plugins with function configurations. Below, the helloPlugin's setup function is filtered out when passed to the esbuild framework, causing the esbuild framework to complain about a missing setup function for its plugin. 

It appears that the serverless configuration filters out functions in the configuration and causing this issue. Is it possible that some sort of unmarshalling/marshalling is doing this? 

If the serverless.js is converted to serverless.yml, a function cannot be given to the plugin through the configuration. Which makes sense because now the yaml can't specify a function in the helloWorld plugin configuration. So, this appears to be a use case for serverless configuration using javascript or typescript files and hasn't been raised before because most configuration is done through yaml files.

See: https://github.com/floydspace/serverless-esbuild/issues/359 for an extensive diagnosis of the issue using serverless-offline for testing.

## Example
esbuild helloPlugin.js
--------------
```
const helloPlugin = {
  name: 'hello',
  setup(config) {
    console.log('Hello World')
  },
}

exports.helloPlugin = helloPlugin;
```
app.js
--------------
```
const api = (event, context, callback) => {
  console.log('Hello from the custom Lambda!')
  return callback(null, {
    statusCode: 200,
    body: "Hello World!"
  })
}
exports.api = api
```
serverless.js
--------------
```
const { helloPlugin } = require('./helloPlugin')

const serverlessConfiguration = {
  frameworkVersion: '3',
  service: 'hello-world',
  plugins: [
    'serverless-esbuild',
    'serverless-offline',
  ],
  custom: {
    esbuild: {
      entryPoints: ['app.js'],
      platform: 'node',
      target: 'node16',
      bundle: true,
      outdir: '.esbuild/.build',
      plugins: [helloPlugin], // this line causes the problem.
    },
    'serverless-offline': {
      host: "localhost",
      httpPort: 3005
    },
  },
  provider: {
    name: 'aws',
    runtime: 'nodejs16.x',
  },
  functions: {
    'hello-world': {
      handler: 'app.api',
      events: [{
        http: {
          path: 'hello',
          method: 'get',
        },
      }],
    }
  }
}
module.exports = serverlessConfiguration
```

### Service configuration (serverless.yml) content

```yaml
N/A example given in the issue description
```

### Command name and used flags

serverless offline start

### Command output

```shell
serverless offline start                                                                                                                            [22/09/14| 9:47AM]
✘ [ERROR] [plugin hello] Plugin is missing a setup function

    /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:798:16:
      798 │           throw new Error(`Plugin is missing a setup function`);
          ╵                 ^

    at handlePlugins (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:798:17)
    at Object.buildOrServe (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:2109:14)
    at build (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:1956:51)
    at bundleMapper (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/serverless-esbuild/dist/bundle.js:69:50)
    at /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/p-map/index.js:57:28

Environment: darwin, node 16.16.0, framework 3.21.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Build failed with 1 error:
/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:798:16: ERROR: [plugin: hello] Plugin is missing a setup function
    at failureErrorWithLog (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:1143:18
    at /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:1138:9
    at /Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/robblovell/Code/opensource/plugin-missing-setup-function/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
(base) ➜  javascript git:(feature/workaround) ✗ node esbuild.config.js                                                                                                                              [22/09/14| 9:48AM]
Hello World {
```

### Environment information

```shell
serverless --version                                                                                                                                      [22/09/14| 9:52AM]
Framework Core: 3.21.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by robblovell** [comment]
Example repo: https://github.com/robblovell/plugin-missing-setup-function

**Comment by icholy** [comment]
The setup function is being removed here: https://github.com/serverless/serverless/blob/1c7e77ea8b0ac61e1114f3dc5d81bcb88e12b625/lib/configuration/read.js#L193-L203

**Comment by kaykhan** [comment]
Also having the same issue, any updates on what can be done?

**Comment by ericrav** [comment]
@kaykhan The solution is to use an external file to export the plugins array as documented here: https://github.com/floydspace/serverless-esbuild#esbuild-plugins

Because the Serverless configuration has to be serializable, you can pass a string filename to `plugins` which is loaded by `serverless-esbuild`:

```js
// serverless.js
{
  custom: {
    esbuild: {
      plugins: "esbuild.plugins.js"
    }
  }
}
```

```
// esbuild.plugins.js
const helloPlugin = {
  name: 'hello',
  setup(config) {
    console.log('Hello World')
  },
}

module.exports = [helloPlugin];
```

**Comment by robblovell** [comment]
I have validated that this works:
```
// serverless.js
...
  custom: {
    esbuild: {
      entryPoints: ['app.js'],
      platform: 'node',
      target: 'node16',
      bundle: true,
      outdir: '.esbuild/.build',
      plugins: "esbuild.plugins.js",  // Reference the plugins in the external file here
    },
    ...
  },
...
```
The external file that loads the plugins:
```
// esbuild.plugins.js
const {helloPlugin} = require("./helloPlugin");
module.exports = [helloPlugin];
```
