### ISSUE TITLE
Serverless incorrectly warns that `ResponseHeadersPolicyId` as a CloudFront behaviour property is invalid

### ISSUE THREAD

**Issue by benheymink** [serverless/serverless#11397]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless complains that ResponseHeadersPolicyId isn't a valid attribute but CloudFormation documentation states that it's a valid part of the cache behaviour.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-responseheaderspolicyid

It looks like the schema for CloudFront events is missing this field: 

https://github.com/serverless/serverless/blob/11b7a05fd3db362003412484245cc55bfab70181/lib/plugins/aws/package/compile/events/cloud-front.js#L85

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --stage common --param="account=preprod"

### Command output

```shell
❯ serverless deploy --stage common --param="account=preprod"
Running "serverless" from node_modules
✔ serverless-better-credentials: credentials resolved from env: AWS_*

Warning: Invalid configuration encountered
  at 'functions.originRequest.events.0.cloudFront.behavior': unrecognized property 'cachePolicy'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
❯ serverless --version
Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@benheymink great thanks for reporting!
