### ISSUE TITLE
Logs arguments now require --function and --functionName

### ISSUE THREAD

**Issue by nigelsim** [serverless/serverless#11399]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In 2.8.0 I could get function logs using `serverless logs -f myfunction`. On upgrading to 3.22.0 I now have to do `serverless logs --function myfunction --functionName myfunction`.

Looking at the help output, it appears that if I use `-f` it should set both `--function` and `--functionName` at the same time.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless logs -f myfunction

### Command output

```shell
$ serverless logs -f myfunction
Environment: linux, node 14.18.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Serverless command "logs" requires "--function" option. Run "serverless logs --help" for more info
```

```
$ serverless logs --function myfunction
Environment: linux, node 14.18.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Serverless command "logs" requires "--functionName" option. Run "serverless logs --help" for more info
```

```
$ serverless logs --functionName myfunction
Environment: linux, node 14.18.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Serverless command "logs" requires "--function" option. Run "serverless logs --help" for more info
```
```


### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@nigelsim thanks for report, still I'm not able to reproduce that. Are you using any plugins (can you complete `serverless.yml` section in your report) ?

<img width="727" alt="Screenshot 2022-09-20 at 11 23 12" src="https://user-images.githubusercontent.com/122434/191220730-36386b0b-5c05-4c48-b326-4a43c789a614.png">

**Comment by nigelsim** [comment]
Thanks for looking into this @medikoo. I do have a plugin in there:

```
plugins:
  - "@dronedeploy/dronedeploy-cli"
```

This is my first time with `serverless` and I didn't expect the plugin to be hooking into the logging. I'm going to assume that's actually where the issue is, as I can see there is some code in there to use the `logs:logs` hook.

```
class DroneDeployLogs {
  constructor(serverless, options) {
...
    this.commands = { 
      logs: {
        lifecycleEvents: ['logs'],
        options: {
          functionName: {
            shortcut: 'f',
            type: 'string',
            required: true,
            usage: 'Name of function to display logs for.'
          },
          tail: {
            shortcut: 't',
            required: false,
            usage: 'Display logs\' tail continuously.'
          }
        },
        usage: 'Display function logs.',
      }   
    };  

    this.hooks = { 
      'logs:logs': () => this._showFunctionLogs()
    };  
  }
...
```
