### ISSUE TITLE
Plugin not getting log instance when added with `serverless.pluginManager.addPlugin(...)`

### ISSUE THREAD

**Issue by icholy** [serverless/serverless#11412]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [ ] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have an internal plugin which is used to add/configure other plugins used across our services. Something along the lines of this:

``` js
const WarmupPlugin = require("serverless-plugin-warmup");

class MyPlugin {
    constructor(serverless) {
        this.serverless = serverless;
        this.hooks = {
            initialize: () => this.init(),
        }
    }

    init() {
        this.serverless.pluginManager.addPlugin(WarmupPlugin);
    }
}

module.exports = MyPlugin;
```

This works fine in v2, but when upgrading to v3 the `WarmupPlugin` is not getting a logger instance. Specifically, the third constructor parameter is an empty object here. 

https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/847b45cc675e8f12ea439b68283417feab562ef9/src/index.js#L33

This results in an exception being thrown when the logger methods are called. Digging a bit deeper, it appears that no `pluginUtils` are passed when the plugin wasn't directly specified in the `serverless.yml` file.

https://github.com/serverless/serverless/blob/b95c7496ec4a49aef756692a1ef59b61e2d95d4b/lib/classes/plugin-manager.js#L87-L91

I was able to work around this by defining that property before calling `addPlugin`. However, I don't want to have to rely on implementation details. 

``` js
Object.defineProperty(WarmupPlugin, "_serverlessExternalPluginName", {
    value: "serverless-plugin-warmup",
    configurable: true,
    writable: true,
});
```

Looking at other plugins, it appears that other people have ran into this problem. For example, the domain manager plugin wraps the passed logger and falls back to their own logger if it's missing:

https://github.com/amplify-education/serverless-domain-manager/blob/82b5142b0a8c5267089324e9fca4e3112739fe5c/src/globals.ts#L57-L85

What's the correct course of action here? I am unable to find documentation on using the `pluginManager.addPlugin` method.

### Service configuration (serverless.yml) content

```yaml
service: proj-provider-calendar-proj

plugins:
  - "@icholy/serverless-plugin-bug"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x

functions:
  catchall:
    handler: lambda.handler
    timeout: 20
    events:
      - http:
          path: /
          method: any
          cors: true

custom:
  warmup:
    default:
       enabled: true
       prewarm: true
       events:
         - schedule: cron(0/5 0-7 ? * MON-FRI *)
```

### Command name and used flags

npx sls package

### Command output

```shell
Packaging proj-provider-calendar-proj for stage dev (us-east-1)
Environment: linux, node 14.18.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read property 'notice' of undefined
    at WarmUp.configureWarmer (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless-plugin-warmup/src/index.js:198:14)
    at /home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless-plugin-warmup/src/index.js:102:49
    at Array.map (<anonymous>)
    at WarmUp.initializeWarmers (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless-plugin-warmup/src/index.js:102:8)
    at PluginManager.runHooks (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:564:20)
    at async PluginManager.spawn (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async PluginManager.runHooks (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:565:9)
    at async PluginManager.run (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/lib/serverless.js:174:5)
    at async /home/icholy/src/github.com/company/proj/api/platform2/company.provider.calendar.proj/node_modules/serverless/scripts/serverless.js:771:9

```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by icholy** [comment]
@medikoo a plugin which calls `serverless.pluginManager.addPlugin(plugin);`. The first code block in the issue contains a minimal example.

**Comment by medikoo** [comment]
@icholy I believe it can be easily fixed if we replace `if (Plugin._serverlessExternalPluginName) { ` with `if (isRegisteringExternalPlugins) {`

As I look at the codebase now, it seems to me, that `Plugin._serverlessExternalPluginName` was meant to address very same use case as `isRegisteringExternalPlugins` which is designed better.

Adding `Plugin._serverlessExternalPluginName` was most likely not necessary.

PR with a fix is welcome!

**Comment by icholy** [comment]
@medikoo that's not enough because `@serverless/utils/log#getPluginWriters` will throw an exception if the provided name isn't a string. I need a way to pass a name to `getPlugin`.

``` js
this.serverless.pluginManager.addPlugin(MyPlugin, { name: 'my-plugin' });
```

**Comment by icholy** [comment]
The `pluginManager` property an undocumented/private api which should not be used by plugins. However, there is a hacky work-around (which could stop working at any minor release):

``` js
MyPlugin._serverlessExternalPluginName = "my-plugin";
this.serverless.pluginManager.addPlugin(MyPlugin);
```
