### ISSUE TITLE
Add python3 support

### ISSUE THREAD

**Issue by reubano** [serverless/serverless#1141]
python3 has now been out for 8 years and will soon overtake python2 as the language of choice for new packages.

**Comment by c-knowles** [comment]
It's worth noting AWS Lambda does not support v3 yet - http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html.

**Comment by reubano** [comment]
Good point... one can hope.

**Comment by c-knowles** [comment]
AWS took their sweet time to update the version of nodejs but hopefully now they have support multiple versions for one language they are geared up to do it a bit quicker, fingers crossed.

**Comment by flomotlik** [comment]
With V1 of the framework the specific language version is irrelevant for us as we can simply pack any language really. We do want to support python 3 in the future as well, as soon as Lambda supports it. Closing this issue for now as its currently not possible.

**Comment by tom-zeit** [comment]
@flomotlik  - I tried to deploy python 3.4 in version 1.4, but it doesn't seem to work, as it says that only python3.4 is not supported :
`Value python3.4 at 'runtime' failed to satisfy constraint:`

Can you clarify how is it possible to deploy a python3.4 package?
Thanks!

**Comment by pmuens** [comment]
Hey @tom-zeit right now AWS Lambda only supports the Python 2.7 runtime (see http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

Additionally you can always find different examples (such as this Python example: https://github.com/serverless/examples/tree/master/aws-python-simple-http-endpoint) in the examples repository: https://github.com/serverless/examples

**Comment by Cretezy** [comment]
https://aws.amazon.com/releasenotes/5198208415517126

**Comment by bsamuel-ui** [comment]
Also, @dschep and I just updated `serverless-python-requirements` to handle python 3.
