### ISSUE TITLE
Documented property is not yet released

### ISSUE THREAD

**Issue by jrdavenport** [serverless/serverless#11432]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The Serverless package has functionality documented on the `master` branch, such as `consumerGroupId` in `docs/providers/aws/events/kafka.md`, which has not been released since being merged nearly 2 months ago.

The last Serverless release was `3.22.0` on `16th Aug 2022`. Please can a new version be released containing all of the improvements since the last release? It looks as if there are ~9 commits which are waiting to be released.

Thanks,
James

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
3.22.0
```

**Comment by medikoo** [comment]
@jrdavenport v3.23.0 was just released

**Comment by jrdavenport** [comment]
Thanks @medikoo !
