### ISSUE TITLE
AWS_CONFIG_FILE is not used

### ISSUE THREAD

**Issue by mentos1386** [serverless/serverless#11443]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to use AWS_CONFIG_FILE env variable to use custom path for aws config file. Aws cli works, but serverless is complaining that my profile "doesn't seem to be configured".

It seem to be reported in but ignored:
* https://github.com/serverless/serverless/issues/10248
* https://github.com/serverless/serverless/pull/8354

Running `aws sts get-caller-identity` works fine.

The environment variables set are. Some are present, but empty (which shouldn't cause any issues).
```bash
$ env  | grep AWS
AWS_PROFILE=<redacted>
AWS_REGION=us-east-1
AWS_DEFAULT_PROFILE=<redacted>
AWS_SECRET_ACCESS_KEY=
AWS_CONFIG_FILE=/home/<redacted>/projects/<redacted>/.workspace/runtime/config/aws-config
AWS_ACCESS_KEY_ID=
```

### Service configuration (serverless.yml) content

```yaml
service: device-manager

provider:
  name: aws
  runtime: nodejs16.x

functions:
  guard:
    handler: dist/apps/guard/main.js
```

### Command name and used flags

npx serverless invoke --verbose --function guard

### Command output

```shell
Environment: linux, node 16.16.0, framework 3.23.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
AWS profile "<redacted>" doesn't seem to be configured
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.23.0 (local) 3.23.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by mentos1386** [comment]
Another relevant PR https://github.com/serverless/serverless/issues/9290 which might address this.

**Comment by medikoo** [comment]
@mentos1386 let's group all the AWS credential resolution reports at https://github.com/serverless/serverless/issues/9290

I'm going to close it as duplicate
