### ISSUE TITLE
Serverless tries to remove unused role

### ISSUE THREAD

**Issue by j-adamczyk** [serverless/serverless#11451]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I used to have IAM roles created by Serverless Framework, called `events-dev-eu-central-1-lambdaRole`. I replaced it with manually created roles `dev-event-processing-deployment-role` (for deploy) and `dev-event-processing-execution-role` (for execution):
```
  iam:
    # role assumed by account, Jenkins and CloudFormation to deploy resources
    deploymentRole: dev-event-processing-deployment-role

    # Lambda execution role
    role: dev-event-processing-execution-role
```

I expected Serverless to just use a new role and do not touch the old one - it should have no knowledge about it. However, upon deploy I get an error:
```
Error:
DELETE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
API: iam:DeleteRolePolicy User: arn:aws:sts::590463175157:assumed-role/dev-event-processing-deployment-role/AWSCloudFormation is not authorized to perform: iam:DeleteRolePolicy on resource: role events-dev-eu-central-1-lambdaRole because no identity-based policy allows the iam:DeleteRolePolicy action
```

This can be reproduced with any toy example: create "hello world" function with autogenerated IAM role, replace with manually created one without `iam:DeleteRolePolicy`, try to update.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
Deploying events to stage dev (eu-central-1)

✖ Stack events-dev failed to deploy (75s)
Environment: linux, node 18.6.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "dev" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
DELETE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
API: iam:DeleteRolePolicy User: arn:aws:sts::590463175157:assumed-role/dev-event-processing-deployment-role/AWSCloudFormation is not authorized to perform: iam:DeleteRolePolicy on resource: role events-dev-eu-central-1-lambdaRole because no identity-based policy allows the iam:DeleteRolePolicy action
```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@j-adamczyk by referencing _external_ role you've stated that there's no need for Serverless to create one for you, and it's the reason it was removed from the deployment stack (in result removed after deployment).

**Comment by j-adamczyk** [comment]
Ok, but I do not want it to be deleted. It is still used by other Serverless deployments, just not by this particular one, that's why this is a problem. Even if I have Serverless permissions, it still would not be able to delete this role, as it is in use by other services. I don't think that this is the right behavior, as this way there is no way (at least that I know of) to use Serverless for this, but rather I have to fix all of this manually.

**Comment by medikoo** [comment]
> Ok, but I do not want it to be deleted. It is still used by other Serverless deployments, just not by this particular one, that's why this is a problem

This role should not be used by anything outside of the created stack. I think the problem here is, that you've created a dependency that should not exist, and CF stack is not aware of.

**Comment by j-adamczyk** [comment]
Ok, I see that now, thank you
