### ISSUE TITLE
Empty string environment variable value treated as missing

### ISSUE THREAD

**Issue by webpepper** [serverless/serverless#11455]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

If an environment variable is defined but is empty, Serverless reports it as 'Value not found at "env" source'.

The value _is_ found, it's just that value happens to be an empty string.

If in my .env file I have

```env
FOO=
```
How the environment variable is populated is irrelevant, the issue is in the framework code that checks it.

Logically, this should work. `fooValue` should get the value of `''` (empty string).
```yml
custom:
  fooValue: ${env:FOO} 
```

Instead this happens:

```
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "custom.fooValue": Value not found at "env" source
```

This following works but is strange:  an empty string is used as a default value if the value happens to be an empty string 🤯 

```yml
custom:
  fooValue: ${env:FOO, ''} 
```

The problem is this line: https://github.com/serverless/serverless/blob/main/lib/configuration/variables/sources/env.js#L24

Instead of 

```js
if (!process.env[address])
```

it should be 

```js
if (typeof process.env[address] === 'undefined')
```

### Service configuration (serverless.yml) content

```yaml
service: fooTest

custom:
  fooValue: ${env:FOO} 

provider:
  name: aws
```

### Command name and used flags

FOO= npx sls package  

### Command output

```shell
Environment: darwin, node 16.15.1, framework 3.23.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "custom.fooValue": Value not found at "env" source
```

### Environment information

```shell
Framework Core: 3.23.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@webpepper Internal implementation assumes that _empty_ string is as if env var was not set, but that's probably not right.

It can be fixed here: https://github.com/serverless/serverless/blob/c5ca9b78faef8bc6c23b215f847dc4383b8165e7/lib/configuration/variables/sources/env.js#L24-L25 

PR with a fix is welcome!
