### ISSUE TITLE
Dependecy Issue - Cannot find type definition file for 'keyv'. For version 4.2.0

### ISSUE THREAD

**Issue by azmicirit** [serverless/serverless#11458]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Type definition missing for 4.2.0

This error occures after I try to build my typescript project just before deploy it via Serverless Framework

```
Cannot find type definition file for 'keyv'.
--
115 | The file is in the program because:
116 | Entry point for implicit type library 'keyv'
```

Serverless: 2.72.3
Environment: AWS CodeBuild (ubuntu)

It's dependency issue of Serverless framework both of v2 and v3 which are dependant on got@11.8.5.
Even if I update serverless to v3, it requires got@11.8.5 which is dependant on @types/keyv and causes same error.

I requested to publish this module back here. https://github.com/jaredwray/keyv/issues/528
https://www.npmjs.com/package/@types/keyv

I tried to force increase got version in package.json with overrides method but got this error 

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ../node_modules/got/dist/source/index.js from ../node_modules/serverless/lib/utils/eventuallyUpdate.js not supported
```
I believe it is ESM module integration fault.

### Proposed solution (optional)

Could we increase version of got module in Serverless v2 and v3 together and make it ESM module compatible?

**Comment by medikoo** [comment]
1. Please use the bug report template to report bugs
2. You're relying on an outdated Serverless Framework version, which we no longer support
3. Issue seems specific to the plugin and not the Serverless Framework

**Comment by azmicirit** [comment]
it was node version issue (v14 doesn't support ESM modules I guess). I'm closing this question.
