### ISSUE TITLE
"npm install -g serverless" fails on node 19.x - postinstall.js module not found

### ISSUE THREAD

**Issue by cforce** [serverless/serverless#11467]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

postinstall.js module not found

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
➜ npm install -g serverless
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)
npm ERR! code 1
npm ERR! path /root/.nvm/versions/node/v19.0.0/lib/node_modules/serverless
npm ERR! command failed
npm ERR! command sh -c -- node ./scripts/postinstall.js
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '/root/.nvm/versions/node/v19.0.0/lib/node_modules/serverless/scripts/postinstall.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-24T14_41_22_714Z-debug-0.log
```

### Environment information

```shell
windows 10 , node 19.0.0m
```

**Comment by medikoo** [comment]
@cforce I cannot reproduce that:

<img width="1053" alt="Screenshot 2022-10-25 at 10 56 23" src="https://user-images.githubusercontent.com/122434/197730284-6e442acd-067a-4c1c-bd18-fa3c86815168.png">

**Comment by cforce** [comment]
for v16.18.0 is works, just not for 19.0.0.
Executed on 5.10.16.3-microsoft-standard-WSL2, Ubuntu 22.04.1 LTS

**Comment by medikoo** [comment]
It might be some bug on npm side which is specific to Windows. Have you tried reporting it to npm?

**Comment by cforce** [comment]
Switched to nvm and upgraded to latest node 19.2.0 to overcome the problem

**Comment by cforce** [comment]
Okay, found the solution. Better no run under root or allo0w if know what your are doing
```
npm config set user 0
npm config set unsafe-perm true
```

**Comment by Ahamisi** [comment]
Reduce your node version to probably a lower version...... I.e from node v18 to node v16

**Comment by hardgui** [comment]
i tried to use "npm install -g serverless --force" and it worked
