### ISSUE TITLE
Refactor plugin loading when running tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1147]
Right now we use the `--serverless-integration-test` parameter to check if the call of `serverless` is run as a test (e.g. an integration test --> https://github.com/serverless/serverless/blob/dev/tests/integration/Serverless.js#L25-L31).

This looks like this:

```
serverless test integration --serverless-integration-test
```

This parameter is used as a switch to modify the `serverless` instance:
https://github.com/serverless/serverless/blob/dev/bin/serverless#L19-L22

However it's not 100% clean and should be refactored.

Other solutions might be:
1. Add a configuration so that one can replace the `plugins.json` file with an own file
2. TBD

Here are the corresponding commits which introduced the issue:
https://github.com/serverless/serverless/commit/93a23ccd9e39a0f8ab5f0247a9b856459e4de535
https://github.com/serverless/serverless/commit/7f95047a5c0905e7c54eafa7ecdec7da5cbd9263
https://github.com/serverless/serverless/commit/fb33a1412fdcf07ae2060b709fefbe7f3eeaff70

**Comment by flomotlik** [comment]
@pmuens still an issue?

**Comment by pmuens** [comment]
Nope @eahefnawy has resolved this with a new test inside the `PluginManager` class test.
