### ISSUE TITLE
Kafka: Customize ConsumerGroupId

### ISSUE THREAD

**Issue by nick-zh** [serverless/serverless#11481]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

For `events:kafka` it seems it is possible to customize `ConsumerGroupId` this would be highly preferable for monitoring so you can have meaningful names for your consumers

### Proposed solution (optional)

add a new attribute to the `events:kafka` object `consumerGroupId`

**Comment by medikoo** [comment]
@nick-zh is this about some new configuration functionality as introduced by AWS?

**Comment by nick-zh** [comment]
correct, it was introduced in [August](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-lambda-consumer-group-ids-msk-kafka-event-sources/) so now we are able to [customize this](https://aws.amazon.com/blogs/compute/using-custom-consumer-group-id-support-for-the-aws-lambda-event-sources-for-msk-and-self-managed-kafka/) and it would be great if serverless would support the new `ConsumerGroupId` :heart:

**Comment by medikoo** [comment]
@nick-zh ok, we're open for PR then!

**Comment by nick-zh** [comment]
Terribly sorry not sure how i missed this, i see that it should already be supported (https://github.com/serverless/serverless/issues/11432)
