### ISSUE TITLE
Issues deploying from windows machines

### ISSUE THREAD

**Issue by contractorwolf** [serverless/serverless#1149]
I am working on a project with Serverless version 0.5.5 (on a windows 10 machine) and I have noticed issues deploying on 2 of my windows machines.  On my mach I had never seen this issue but now I am working on a prototype idea at work hence the windows boxes (I am a .NET dev at work).  When I am deploying on my windows machines sometime the deployment spinner spins and never stops. I have seen it happen on two different machines now, and I have to kill the terminal to stop it.  Is there some issue running the deployment on windows?

**Comment by contractorwolf** [comment]
Is this project DEAD? no one responding to issues????

**Comment by flomotlik** [comment]
@contractorwolf sorry for the VERY late reply on this. The project is actually very alive and we've been working fully focused on a complete rewrite for V1 of the framework.

With V1 we've also completely removed the spinner as this typically leads to huge issues and this should be resolved now. We're also going through Cloudformation now so stability has greatly improved there. I'm going to close this issue as we've fixed the specific problem. Again sorry for the late reply.

**Comment by contractorwolf** [comment]
@flomotlik no worries, I found that the best resource for quick questions on serverless was the gitter board here:
https://gitter.im/serverless/serverless

In case anyone else seems to be having an issue like this:
My issue actually turned out to be because of the handler path (in s-functions) for my functions folder included the root folder which created an endless recursion when trying to deploy.  I moved the functions folder in my project so that it now lives in an src folder so that my project looks like this:
[project root]/src/functions

so that the path in my s-functions.json can include a path like this:
"handler": "functions/content/searchcontent/handler.handler"
without accidently including the build and deploy folder

I found this because I think looked in the _meta/_tmp folder and saw thousands of subfolders (on my windows machine).

**Comment by flomotlik** [comment]
@contractorwolf yup that subfolder stuff is also resolved now, as we don't have the _meta folder any more and just completely remove this issue from the beginning in V1
