### ISSUE TITLE
3.24.0 getting 326Unauthorized request: Either org token is invalid, or org token is not supported for this command (run the command as logged-in user instead)

### ISSUE THREAD

**Issue by jinman** [serverless/serverless#11500]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We upgraded to 3.24.0 and it started giving 

326Unauthorized request: Either org token is invalid, or org token is not supported for this command (run the command as logged-in user instead)

Is this deprecated? We are using the old Serverless dashboard.

### Service configuration (serverless.yml) content

```yaml
org:
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
326Unauthorized request: Either org token is invalid, or org token is not supported for this command (run the command as logged-in user instead)
```

### Environment information

```shell
[Container] 2022/11/04 15:45:18 Running command sls --version
Framework Core: 3.24.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@jinman can you show the output with `--debug="*"` flag ? Especially last lines with the stack trace

**Comment by medikoo** [comment]
I just have made successful deployment with Dashboard (with v3.24.0) so I will need a bit more details

**Comment by medikoo** [comment]
Also it'll be good to have full `serverless.yml`. Deployments to dashboard require `app` setting as well

**Comment by medikoo** [comment]
Ok, I think I got it reproduced. Fix is coming. Thanks for report
