### ISSUE TITLE
API Logs not showing up in dashboard, everything is under the Invocations tab.

### ISSUE THREAD

**Issue by nostromoJohn** [serverless/serverless#11508]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

## Description
When I deploy a python HTTP API, I don't see anything in the API Requests tab on the dashboard, only in the Invocations tab. 

## Details
I am using an AWS provider that is not the default provider for the account, which is managed through the stage configuration. I am on the latest version of serverless V3 (3.24.1 at time of writing).

## How to reproduce
To remove my code and dependencies as a factor, I managed to reproduce this issue just by using a serverless template, without editing anything. 

I ran ```serverless --org=<my org> --app=aws-python-http-api --name=aws-python-http-api --template=aws-python-http-api``` and deployed that to stage "dev" immediately (The same non-default provider I used for my code)

After the deploy finished, I sent a request to the API using my browser and recieved the intended response:

 ``` 
"message": "Go Serverless v3.0! Your function executed successfully!",
  "input": {
    "version": "2.0",
    <...>
      "x-forwarded-proto": "https"
    },
    "requestContext": {
      <...>
      },
      "requestId": "bU2tFi_aoAMEV4A=",
       <...>
      "timeEpoch": 1667984160383
    },
    "isBase64Encoded": false
  }
}
```

When looking at the serverless dashboard, this is what came up:
![image](https://user-images.githubusercontent.com/99584217/200785538-52eae5a8-f25a-490b-aae5-3439f8290ee3.png)

Note that there is 1 invocation (my request) and 0 API requests, despite the invocation being an API request.
Looking directly at CloudWatch, I see 2 log groups:

![image](https://user-images.githubusercontent.com/99584217/200785868-cc5f90e3-7bec-4df6-96d9-69d2c705e949.png)

Within these groups I can even find the API logs for Serverless Dashboard:

![image](https://user-images.githubusercontent.com/99584217/200786325-32dd0b12-6af1-4490-8a83-03d9da7c0854.png)

However I can't see them in the dashboard itself.

## Conclusion

This seems to be an issue with the monitoring configuration of serverless, perhaps a permission error?

### Service configuration (serverless.yml) content

```yaml
org: <my-org>
app: aws-python-http-api
service: aws-python-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```

### Command name and used flags

serverless --org=<my org> --app=aws-python-http-api --name=aws-python-http-api --template=aws-python-http-api

### Command output

```shell
N/A (default output)
```

### Environment information

```shell
Framework Core: 3.24.1 (local) 3.15.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by nostromoJohn** [comment]
OK, done

**Comment by Sbrjt** [comment]
How did you resolve it?
