### ISSUE TITLE
Improvement yaml merge

### ISSUE THREAD

**Issue by GetOnMyLvl97** [serverless/serverless#11523]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello!
I've been running production workloads with serverless for almost thee years now. 
One thing that can be improved is getting rid of 
```
Warning: Invalid configuration encountered
at root: unrecognized property 'CORS'
```
when you create YAML merges.

e.g. I have several lambda functions in the YAML which need to use the same cors/auth config etc. 
For this, I created a YAML merge. https://yaml.org/type/merge.html
```
CORS: &CORS
  cors:
    origin: '*'
    headers:
      - Content-Type
      - value2
      - etc.
```
so If it's a YAML merge don't add it to unrecognised 

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.24.1 (local) 3.24.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@GetOnMyLvl97 problem is that result template contains unrecognized properties.

You can create such properties at `custom` block, but not at the root.

**Comment by GetOnMyLvl97** [comment]
Ahhh yes. Makes sense. I didn't think about the custom properties. 
thank you for you fast answer!!
