### ISSUE TITLE
Add support for new AWS Region eu-central-2 Zurich

### ISSUE THREAD

**Issue by t4nz** [serverless/serverless#11525]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS has recently added a new region eu-central-2 Zurich. It would be great if serverless could support this.

Currently, sls package and sls deploy will fail with error message:

`"Serverless:   at 'provider.region': should be equal to one of the allowed values ...`

### Proposed solution (optional)

Include eu-central-2 region in lib/plugins/aws/provider.js at line 1186 under eu-central-1 entry

**Comment by medikoo** [comment]
@t4nz I believe it was added with https://github.com/serverless/serverless/pull/11524

It'll be published with next release
