### ISSUE TITLE
Support AWS - UAE Region

### ISSUE THREAD

**Issue by drmnasr** [serverless/serverless#11522]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS has launched it's new region (UAE) me-central-1, so far this is not supported in serverless deployment. While attempting to deploy, other than the warning regarding region support, the following error is returned:
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::Lambda::Url]

**Comment by medikoo** [comment]
@drmnasr indeed region is missing in this list: https://github.com/serverless/serverless/blob/20d79a2876875f73755ccae4e1e2c2a9c02c9ad7/lib/plugins/aws/provider.js#L1164-L1192

And we'd welcome the PR to add it.

Still I don't think it's the reason behind the fail on your side (By default Framework just issues warning if not recognized) region is used), It might be that this region is limited in some way and it's the reason for failure on your side.
