### ISSUE TITLE
some serverless commands add local node_modules folder which break deployment 

### ISSUE THREAD

**Issue by yxdunc** [serverless/serverless#11538]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After installing with --template-url option or after installing python-requirements plugin (`serverless --template-url https://github.com/serverless/examples/tree/v3/aws-python-rest-api-with-pymongo`) I get an error when running `serverless deploy` which I don't get on a vanilla python project.

```
✖ Stack api-dev failed to deploy (0s)
Environment: darwin, node 19.0.1, framework 3.25.0 (local) 3.24.1v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "default" provider (https://app.serverless.com/ro8in/apps/ai-content-creator/api/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: spawn python3.8 ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
➜  api git:(prod) ✗
```

I noticed that those two commands have the side effect of installing node_modules in the project directory. Only when deleting any local node files and folders the deployment start working again.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags
```shell
serverless deploy
```
### Command output

```shell
✖ Stack api-dev failed to deploy (0s)
Environment: darwin, node 19.0.1, framework 3.25.0 (local) 3.24.1v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "default" provider (https://app.serverless.com/ro8in/apps/ai-content-creator/api/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: spawn python3.8 ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
➜  api git:(prod) ✗
```

### Environment information

```shell
Framework Core: 3.25.0
Plugin: 6.2.2
SDK: 4.3.2
```

serverless installed with `npm install -g serverless` on OSX 12.3.1

**Comment by medikoo** [comment]
@yxdunc Mentioned template [requires npm dependencies](https://github.com/serverless/examples/blob/16e8e74164aff8e60ddd8ce2c35192ba1f730deb/aws-python-rest-api-with-pymongo/package.json#L8) to be installed, and it's the reason `node_modules` is created

**Comment by yxdunc** [comment]
@medikoo thanks for your quick response. I assumed that npm dependencies were required for those two commands.

The issue is that running those commands shouldn't break deployment or at the very least the error message should be way more instructive.

Any idea how I can fix deployment once I have the local npm dependencies ?

**Comment by medikoo** [comment]
@yxdunc fact that `node_modules` is created shouldn't affect the visibility of `python3.8` binary. If that's the case, it looks as some issue specific to your configuration

**Comment by yxdunc** [comment]
Thanks for your message made me realize the default `serverless.yaml` I got was set to python3.8 whilst I only have python3.9 in my virtual env.

So it was indeed an error on my side. Though, I do think the CLI could benefit from better error reporting such as:
`We could find Python 3.8 in your local environment. Make sure python3.8 is installed by running: `python3.8 --versi
on`

I could open a PR to add the error message. WDYT ?

**Comment by medikoo** [comment]
@yxdunc definitely! PR is welcome
