### ISSUE TITLE
The standalone install is broken

### ISSUE THREAD

**Issue by 1ed** [serverless/serverless#11603]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I use the standalone version in CI and my machine as well, but it is broken now. Could someone fix it, please? Thanks!

https://www.serverless.com/framework/docs/install-standalone

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

```
curl -o- -L https://slss.io/install
```

### Command output

```shell
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>UnavailableForLegalReasons</Code>
	<Message>Due to your account is arrears, it is unavailable until you recharge.</Message>
	<Resource>/install.sh</Resource>
	<RequestId>NjM5ODdjYmJfMjZjNTFjMDlfMmJlY18zYTZhZDE2</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTVhZmNjOGRhMDFhODRkMDI4YmJmYmQyZDI5OGM4MzJlNjEwMGUxN2UzYWIzZTMyMjE4MjEyMzRkNjdmZWI2ZmU=</TraceId>
</Error>
```

### Environment information

```shell
Framework Core: 3.22.0 (standalone)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@1ed great thanks for reporting! Fixed now

**Comment by joaogoulart-vigil** [comment]
This issue is affecting the circle CI orb for serverless

https://github.com/CircleCI-Public/serverless-framework-orb/issues/40
