### ISSUE TITLE
Typo "GiHub" on https://www.serverless.com/framework/docs/tutorial

### ISSUE THREAD

**Issue by e-loughlin** [serverless/serverless#11616]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

There's a typo on https://www.serverless.com/framework/docs/tutorial. 
It says "GiHub". 

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by medikoo** [comment]
@e-loughlin thanks for reporting. PR with a fix is welcome. Documentation source is here: https://github.com/serverless/serverless/blob/main/docs/tutorial.md

**Comment by e-loughlin** [comment]
@medikoo - I read through the contributing documentation, and tried to push up a branch to create a PR.

However, I keep getting this error:

> ERROR: Permission to serverless/serverless.git denied to e-loughlin.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

How do I get permissions?

**Comment by e-loughlin** [comment]
@medikoo Nevermind. Got it resolved by using a fork.

Maybe that should be explained in the contributing section.

PR: https://github.com/serverless/serverless/pull/11617

**Comment by medikoo** [comment]
@e-loughlin yes in all cases PR's should be submitted through forks. It'll be a huge security issue if anyone have access directly to repositoru
