### ISSUE TITLE
Configuration did not change. Configuration update skipped

### ISSUE THREAD

**Issue by maour** [serverless/serverless#11614]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have some eventBridge rules for my AWS lambda defined in index.ts like this.

```
export default {
  handler: `${handlerPath(__dirname)}/handler.main`,
  events: [
    {
      eventBridge: {
        eventBus: "busname",
        pattern: {
          'detail-type': [
            "eventold",
            "newaddedeventname"
          ],
          source: [
            "user"
          ]
        }
      }
    },
```

Adding **newaddedeventname** does not affect redeployment and still getting

_Code did not change. Function deployment skipped. (1s)
Configuration did not change. Configuration update skipped. (1s)_

Using --force also will only cause code deploy and eventBridge rules stays the same in AWS.

Only removing the function and redeploying it will update it.

I expect these pattern changes to be detected without bringing function down and deploy again.

Having these package versions
    "serverless": "^3.25.1",
    "serverless-esbuild": "^1.33.2",
    "serverless-offline": "^12.0.1",
    
Thanks.

### Service configuration (serverless.yml) content

```yaml
Serverless.ts


const serverlessConfiguration: AWS = {
  service: 'appname',
  frameworkVersion: '3',
  plugins: ['serverless-esbuild', 'serverless-offline'],
...
```

### Command name and used flags

sls deploy functionname

### Command output

```shell
Running "serverless" from node_modules

Deploying function functionname to stage beta (eu-central-1)

Code did not change. Function deployment skipped. (1s)
Configuration did not change. Configuration update skipped. (1s)
```

### Environment information

```shell
Linux.

Running "serverless" from node_modules
Framework Core: 3.25.1 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@maour `serverless deploy function` is limited to Lambda deployment, it doesn't redeploy resources associated with the events. Trying to follow with such will turn as too complex and after it'll have to end with full CF stack redeployment.

Still I believe UX on our side could be improved, and we can add in such case a note:

_If you made changes to the configuration and expected them to be deployed it most likely means that they can only be applied with a full service deployment._

PR with such update is welcome!

**Comment by rmidhun23** [comment]
Hi @medikoo 
I would like to work on this if you don't mind. Thanks

**Comment by medikoo** [comment]
@rmidhun23 that'll be great! We look forward

**Comment by zhaoyi0113** [comment]
@medikoo can you be more specifc about `it doesn't redeploy resources associated with the events`? If I change a configuration on `events`, like 

```
functions:
...
events: [
        {
          stream: {
            type: 'dynamodb',
            arn: 'xxx',
            startingPosition: 'LATEST',
            parallelizationFactor: 10,
          },
        },
      ],
```

I can see `serverlesss` does update the `events` configuraiton. It only skips deployment if there was an error to deploy previously which left the stack status as roll back completed.

so I don't understand why serverless can't update that configuration in such condition.

**Comment by medikoo** [comment]
@zhaoyi0113 it refers to `deploy function` command, which deploys only functions (events are not covered). you need full `deploy` to deploy events

**Comment by zhaoyi0113** [comment]
> @zhaoyi0113 it refers to `deploy function` command, which deploys only functions (events are not covered). you need full `deploy` to deploy events

I am using `sls deploy` command. Is it `deploy function`? What is `full deploy`?

**Comment by medikoo** [comment]
In this case, this issue is irrelevant to you. `deploy` and `deploy function` are different commands, and this issue is about `deploy function`
