### ISSUE TITLE
Provide feature to install serverless plugins direct from serverless.yml

### ISSUE THREAD

**Issue by Rishang** [serverless/serverless#11627]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently we have to install serverless plugin via providing its name in cli as:

```bash
serverless plugin install --name serverless-cloudflare-workers
```

but same detail is present in my serverless yml file

```yaml
plugins:
  - serverless-cloudflare-workers
```

### Proposed solution (optional)

We can use the `serverless.yml` as source of required plugin dependenct just like we have package.json for npm

expect outcome:

Here this command will read list of plugins of serverless and install them
```
$ serverless plugin install

- Installing serverless-cloudflare-workers

Done.
```

**Comment by medikoo** [comment]
@Rishang `serverless plugin install --name <plugin-name>` is dedicated to add new plugins (before you have them listed in `serverless.yml` and `package.json`). It'll add a plugin to `serverless.yml` and run `npm install <plugin-name>` (which will ensure it lands in `package.json`.

Having that, if you want to later re-setup service, it's `npm install` that will do what you ask for (it'll ensure all plugins as listed in the `plugins` section are installed as naturally they also should be listed in `package.json`)

**Comment by Rishang** [comment]
yes, but if i am adding new plugin, it will only work after mentioning in serverless.yml, so if there is an option to install plugins via mentioning it in `serverless.yml` it will be easier as it will reduce a little effort

**Comment by medikoo** [comment]
> yes, but if i am adding new plugin, it will only work after mentioning in serverless.yml,

No, to add plugin just run `serverless plugin install --name <plugin-name>` and everything handled (unless you use not common configuration format .e.g. `js` or `ts`, or resolve `plugins` section dynamically - then indeed `plugin install` won't extend `plugins` section)
