### ISSUE TITLE
Integrated AWS Scheduled Event configuration

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1163]

**Comment by mikelax** [comment]
According to [the docs ](http://docs.serverless.com/docs/function-configuration) under the event section it looks like schedule accepts either a rate or cron expression. Is this not the case?

I could not get the following expression to work:  cron(0/15 * * * * *)
Error message was:  
```
Serverless: Deploying events in "prod" to the following regions: us-east-1
Serverless: Failed to deploy events in "prod" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   quarterHourCheck: Parameter ScheduleExpression is not valid.
Serverless:
Serverless: Run this again with --debug to get more error information...
```
I ended up changing to: rate(15 minutes) 
but I would still like to see the cron expression working.

**Comment by skleinei** [comment]
This should work: 
`cron(0/15 * * * ? *)`

**Comment by mthenw** [comment]
@skleinei it's already reported in https://github.com/serverless/serverless/issues/2781
