### ISSUE TITLE
Support SnapStart for Websocket and Scheduled executions

### ISSUE THREAD

**Issue by rnielsen** [serverless/serverless#11662]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When snapStart:true is turned on for a function, the "snapstart" alias is used when calling the lambda from the events "http", "stream" and "sqs"  but the $LATEST version is used for "websocket" (and the associated authorizer) and "scheduled" events so the SnapStart feature isn't used.  There may be other unsupported events but these are the ones I have noticed.

I can work around this by overriding the CloudFormation in resources/extensions but it seems like it should be supported natively.

### Proposed solution (optional)

When using snapStart:true on a function, all events attached to that function should invoke the "snapstart" alias.

**Comment by medikoo** [comment]
@rnielsen this looks as a bug, that should be fixed. We should resolve correct alias in case of websocket as we do in case of other type of events. PR's welcome!
