### ISSUE TITLE
Add interactivity to CLI

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1166]
The current CLI is a very basic implementation based on the old CLI. Interactivity was completely removed in the current implementation. This should be added later in a new version of the CLI.

The new CLI should be based on a bulletproof CLI library (such as Vorpal).

https://github.com/dthree/vorpal

**Comment by flomotlik** [comment]
I like that we don't have interactivity. Maybe reopen later on but for now imho its good the way it is
