### ISSUE TITLE
Use !Ref inside string interpolation

### ISSUE THREAD

**Issue by henrypenny** [serverless/serverless#11688]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I would like to be able to use `!Ref` inside string interpolation.

I'll like to be able to do something like this:

```
custom:
  customVar: ${env:CUSTOM_VAR, !Ref MyResource}

```

### Proposed solution (optional)

Perhaps this syntax could look something like this:

```
custom:
  customVar: ${env:CUSTOM_VAR, !ref(MyResource)}

```

**Comment by medikoo** [comment]
@henrypenny `!Ref` is YAML specific short form syntax. You can use it in `serverless.yml` where it is supported by YAML, and I believe it's not recognized if it's a part of a string (it has to be a standalone value as `foo: !Ref`)

I don't think it's a good idea to introduce `!ref` as another variable source, as (1) it mimicks YAML specific thing, while variable sources are not YAML specific, (2) variable resolver supports only `a-z` chars in variable source names (we cannot start variable source name with `!`).

Currently you can achieve same via:

```yaml
custom:
  customVar: ${env:CUSTOM_VAR, self:custom.ref}
  ref: !Ref MyResource
```

However, if you'd prefer to contain CF reference in var declaration, then currently it cannot be done.
However if you use JSON form of `Ref` (as YAML's `!Ref` cannot work in strings) and take into account eventual support for `jsonParse` variable source extension (which is not implemented, but we eventually could welcome it via PR), then it could be written as:


```yaml
custom:
  customVar: ${env:CUSTOM_VAR, jsonParse('{"Ref":"MyResource"}')}
```

**Comment by henrypenny** [comment]
That's exactly the answer I was looking for - thank you. Is this mentioned in the documentation somewhere that I missed?

**Comment by medikoo** [comment]
> Is this mentioned in the documentation somewhere that I missed?

There's general documentation on variables which documents `self:` source https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-serverlessyml

**Comment by henrypenny** [comment]
Many thanks.
