### ISSUE TITLE
SLS should be able to create AWS::Scheduler::Schedule events

### ISSUE THREAD

**Issue by joelwalden** [serverless/serverless#11680]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

The schedule event type creates an EventBridge event, which should be able to take an EventBus option from the serverless config. Currently there is no way to override the default event bus for scheduled events.

### Proposed solution (optional)

Adding the `eventBus` option to the `schedule` event type, which would bring the functionality in line with EventBridge events.

**Comment by medikoo** [comment]
@joelwalden thanks for proposal. Currently Framework creates `AWS::Events::Rule` resources, which looks as: https://github.com/medikoo/test-serverless/blob/63af5ec6b2ee933b3c8882fb915a0b2e0a80dd3f/.serverless/cloudformation-template-update-stack.json#L167-L183

How would `eventBus` option influence it?

**Comment by joelwalden** [comment]
@medikoo 

> How would `eventBus` option influence it?

There are account-wide limits on rules per bus; this would allow devs who hit the limit to use the `schedule` option instead of having to redo configs to use `eventBridge` (as the `eventBridge` config option allows for a custom `eventBus`). It would be a good quality of life change, but there are workarounds as described.

**Comment by medikoo** [comment]
@joelwalden, thanks for your response. It's still not perfectly clear to me what you propose. Specifically, what changes to the currently generated CF template are you proposing if `eventBus` option is present?

**Comment by joelwalden** [comment]
@medikoo Sorry, I was unclear. After doing more research this solution will not work, as you can only create schedule rules on the default bus. Currently SLS will fail if creating an AWS::Events::Rule with a schedule expression on a non-default bus (returns a CloudFormation error). So, the proposed solution is instead of creating an `AWS::Events::Rule` for a schedule, we should be creating an `AWS::Scheduler::Schedule` resource, which has higher account limits. As a result of my research, the issue is invalid. Would you like me to create a new one or rename?

Does that make sense? That the `schedule` option should be creating `AWS::Scheduler::Schedule`? The docs are here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html

**Comment by medikoo** [comment]
> As a result of my research, the issue is invalid. Would you like me to create a new one or rename?

Let's rename this issue.

>  instead of creating an AWS::Events::Rule for a schedule, we should be creating an AWS::Scheduler::Schedule resource,

Can we do it without introducing a breaking change for existing services?

**Comment by joelwalden** [comment]
> > As a result of my research, the issue is invalid. Would you like me to create a new one or rename?
> 
> Let's rename this issue.

Done

> 
> > instead of creating an AWS::Events::Rule for a schedule, we should be creating an AWS::Scheduler::Schedule resource,
> 
> Can we do it without introducing a breaking change for existing services?

Two options:
1) We can have the existing `schedule` option create the `Scheduler::Schedule` template in CF, which is functionally the same and takes the same parameters, but is not subject to account limits. It would not require any changes in existing configs (IE, it would be non breaking); however, we would have to check for existing `Event::Rule` resources and remove them before adding the `Scheduler::Schedule` resources in order to no have duplication. This makes SLS itself more complex.

2) We can create a new config option (proposed: `scheduler`, but this is similar to `schedule` and might be confusing) that creates the appropriate `Scheduler::Schedule` resource which would allow devs who hit the account limits to easily migrate. This is the simplest option, but duplicates a lot of functionality.

Willing to take input as to the best option to proceed with, and I can start working on some test cases.

**Comment by medikoo** [comment]
> however, we would have to check for existing Event::Rule resources and remove them before adding the Scheduler::Schedule resources in order to not have duplication. This makes SLS itself more complex.

But wouldn't that be taken care by the CF deployment automatically? It'll remove resources that are no longer listed in stack

**Comment by medikoo** [comment]
@joelwalden do all the options of the current `schedule` event implementation can be applied with the same effect if we switch to `Scheduler::Schedule`?

**Comment by joelwalden** [comment]
@medikoo Yes, the only difference between the two implementations is that `Scheduler::Schedule` can only take a single `Target`, whereas the `Event::Rule` can take multiple. However, SLS is only using a single `Target` anyway so this does not affect our usage. In addition, `Scheduler::Schedule` adds the ability to set a custom schedule expression timezone (optional so it does not break existing configs), so it would be an additional enhancement in that regard.

**Comment by joelwalden** [comment]
@medikoo Actually, the `Target` implementation is slightly different between the two as well. `Scheduler::Schedule` target cannot take the `InputTransformer` or `InputPath` params; so that would break configs that use those

**Comment by medikoo** [comment]
@joelwalden does it mean that `Scheduler::Schedule` option would be more limited?

**Comment by joelwalden** [comment]
@medikoo Yes, you would only be able to pass `Input` and not `InputTransformer` or `InputPath`. It might be possible to replicate that functionality in SLS, but that would take further research and I'm not confident it's possible for the Transformer

**Comment by medikoo** [comment]
@joelwalden I think best option to go with that is to add `method: eventBus|scheduler` option (with `eventBus` as being default), and if `method: scheduler` is set, configure event via `AWS::Scheduler::Schedule` resource. WDYT?

**Comment by joelwalden** [comment]
@medikoo That sounds good to me; I think that makes the most sense to not break existing configs

**Comment by medikoo** [comment]
@joelwalden PR's welcome!

**Comment by drboyer** [comment]
Thanks for this issue and PR @joelwalden - I was just running into a situation where I wanted to use EventBridge Schedules in my Serverless Framework project! Two things:

1. I left a review comment on your PR (#11707) about potentially generating an execution role instead of requiring that a `roleArn` be provided. (There is a small chance I misinterpreted how that code works, please correct me if I did.)
2. [a broader question] Would we open to eventually adding support for other Schedule properties? There are a number of other exciting features available with EventBridge Schedules that I'd love to be able to easily integrate into my Serverless project including:
  * setting a ScheduleGroup (it's okay to me if this is not automatically created by Serverless)
  * Setting a Timezone for the ScheduleExpression (via the `ScheduleExpressionTimezone` property in CloudFormation)
  * Configuring a Retry Policy
  * Configuring a Dead Letter Queue if messages can't be delivered
