### ISSUE TITLE
@serverless/platform-client Axios Proxy

### ISSUE THREAD

**Issue by zijam** [serverless/serverless#11702]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm using serverless cli behind a company proxy, everytime I run `sls` command without any subcommand it will fail, looks like there is no configuration in serverless.yml to setup proxy settings for axios client used by @serverless/platform-client.

Currently I have fixed the problem by hardcoding proxy setting in `node_modules/.pnpm/@serverless+platform-client@4.3.2_supports-color@8.1.1/node_modules/@serverless/platform-client/src/utils.js` Line 46
```
  try {
    const HttpsProxyAgent = require("https-proxy-agent");
    requestOptions.proxy = false
    const httpsAgent = new HttpsProxyAgent({secureProxy: false, host: "proxy_host", port: "proxy_port"})

    const axios = Axios.create({httpsAgent});
    // const axios = Axios.create();
    const res = await axios(requestOptions);
    return res.data;
```

### Service configuration (serverless.yml) content

```yaml
"N/A"
```

### Command name and used flags

sls

### Command output

```shell
vscode ➜ /workspaces $ sls 
Running "serverless" from node_modules
Environment: linux, node 18.13.0, framework 3.26.0 (local) 3.26.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error
    at Object.request (/workspaces/node_modules/.pnpm/@serverless+platform-client@4.3.2_supports-color@8.1.1/node_modules/@serverless/platform-client/src/utils.js:70:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.get (/workspaces/node_modules/.pnpm/@serverless+platform-client@4.3.2_supports-color@8.1.1/node_modules/@serverless/platform-client/src/metadata.js:11:10)
    at async Object.isApplicable (/workspaces/node_modules/.pnpm/serverless@3.26.0/node_modules/serverless/lib/cli/interactive-setup/dashboard-login.js:54:53)
    at async module.exports (/workspaces/node_modules/.pnpm/serverless@3.26.0/node_modules/serverless/lib/cli/interactive-setup/index.js:69:22)
    at async /workspaces/node_modules/.pnpm/serverless@3.26.0/node_modules/serverless/scripts/serverless.js:795:36 {
  statusCode: 503,
  name: undefined,
  details: null,
  url: 'https://api.serverless.com/core/meta'
}
```

### Environment information

```shell
vscode ➜ /workspaces $ serverless --version
Running "serverless" from node_modules
Framework Core: 3.26.0 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@zijam it's interesting to see an error without a message. Also do you rely on Serverless Dashboard?

**Comment by zijam** [comment]
@medikoo no i'm not using Serverless Dashboard, just started using Serverless Framework.

The error message is 
```
 statusCode: 503,
 name: undefined,
 details: null,
 url: 'https://api.serverless.com/core/meta'
```

**Comment by medikoo** [comment]
Thanks for reporting, I've introduced workaround here: https://github.com/serverless/serverless/pull/11712

While Dashboard integration will not work with a proxy it wouldn't crash the onboarding step
