### ISSUE TITLE
Add support for Lambda RuntimeManagementConfig property

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/serverless#11704]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS launched [Runtime Management Controls](https://aws.amazon.com/about-aws/whats-new/2023/01/runtime-management-controls-aws-lambda/) recently, with CloudFormation support (not documented, but available in a RuntimeManagementConfig object property, with keys of UpdateRuntimeOn and RuntimeVersionArn.

### Proposed solution (optional)

Add a new property to both the `provider` section and for each function called `runtimeVersion`. This could either be "Auto", "FunctionUpdate", or a runtime ARN. If a runtime ARN is passed in, UpdateRuntimeOn is passed in as "Manual" and the Arn is passed in on the RuntimeVersionArn property. As always, if this is specified on the function, that overrides what's given in the provider section.

**Comment by medikoo** [comment]
@ROSeaboyer great thanks for openning that. Indeed it's an important addition from AWS, which ideally we should support as soon as we can.

I think the proper name for this property would be `runtimeManagmentMode` with values as `auto`, `onFunctionUpdate`, and `manual`.

PR's welcome!

**Comment by ROSeaboyer** [comment]
@medikoo That makes sense; for manual, we also require a runtime ARN to pass in, so would that just be an additional property called `runtimeArn`?

**Comment by medikoo** [comment]
@ROSeaboyer maybe let's support following:

```yaml
runtimeManagment: auto | onFunctionUpdate
# or
runtimeManagment:
  mode: manual
  arn:  ... 
```

**Comment by ROSeaboyer** [comment]
@medikoo That makes sense; I opened up #11715 to add this
