### ISSUE TITLE
Add support for !If Cloudformation Function for Schedule Event Rates

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/serverless#11713]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have a couple of cron-based lambda functions that I need to start at different times based off of what environment is being deployed. Right now, there isn't a way for me to do this without merging with a statement from the Resources section.

### Proposed solution (optional)

Alter the schema configuration to add `awsCfIf` as a possible option for the schedule, both for the syntax of a schedule just being a rate and for the rate field in the more granular schedule object

**Comment by medikoo** [comment]
@ROSeaboyer any property which is passed as is to CF template and is not processed in any other way in the Framework can be defined with support for CF intrinsic functions. 

If that's the case in those situations, prepare a PR we'll be happy to take it.

**Comment by ROSeaboyer** [comment]
@medikoo Gotcha; PR up in #11714
