### ISSUE TITLE
How to define multi-line Mapping Templates?

### ISSUE THREAD

**Issue by carlhunterroach** [serverless/serverless#1171]
In my s-function.json I'd like to set my "requestTemplates" values. My Mapping Template code can be ~25 lines long so I'd like to point my requestTemplates value to a file containing a Velocity Template rather than convert my 25 lines into a 1-liner.

What's the recommended way to achieve this?

**Comment by mharris717** [comment]
I believe s-templates can be expressed with a yml file (instead of a json), and that yml file can have multi line templates which you can reference from places like s-function. Not sure if that is in the docs or not. Hope this is of help.

**Comment by HyperBrain** [comment]
file extension should be .yaml :-)

**Comment by carlhunterroach** [comment]
I'll give that a go.
Perhaps a warning about json needs to be added to the docs?
