### ISSUE TITLE
Wrong Error: No file matches include / exclude patterns

### ISSUE THREAD

**Issue by Dhyey** [serverless/serverless#11716]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

when I use this in the serverless.yml file

```
functions:
  myFunction:
    handler: functions/myFunction/myFunction.myFunction
    package:
      patterns:
         - "!**"
        - "functions/myFunction/**"
```

I used to be able to package just the files from functions/myFunction folder in the package for that particular lambda function. And documentation here also confirms this: https://www.serverless.com/framework/docs/providers/aws/guide/packaging

But now it just throws error:
```
Environment: darwin, node 18.12.1, framework 3.27.0, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns
```

Please help

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless package

### Command output

```shell
Environment: darwin, node 18.12.1, framework 3.27.0, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns
```

### Environment information

```shell
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by Dhyey** [comment]
Sorry for false positive
I had some other issue in the project that caused this!
Closing this issue. Please ignore it

**Comment by nireld** [comment]
What did cause that?

**Comment by Dhyey** [comment]
@nireld It would sound silly but folder of that function got deleted by mistake!
