### ISSUE TITLE
Node.js code-splitting by function

### ISSUE THREAD

**Issue by chrispytoes** [serverless/serverless#11723]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I'm using the `serverless-plugin-typescript` plugin so I'm not sure if this has to do with that, but I've noticed that all my functions under the same application have the exact same package size, even though they have very different dependencies.

Why doesn't each handler compile separately to produce an optimized `node_modules` for each function? Is there a way to make it do this? It feels weird to me to package the ENTIRE app into every single function. The total size multiplies every time you add another function.

**Comment by medikoo** [comment]
@chrispytoes there are a lot of open issues on that matter.

FIrstly you already have a `package: individually` option, which, while not providing you with smart bundling, allows you to define exclude/include patterns per function.

Concerning anything smarter please check: https://github.com/serverless/serverless/issues/6580 (note it's a pinned issue). Unfortunately, currently we do not have the resources to work actively on that, so there's no ETA

I'm closing this as duplicate
