### ISSUE TITLE
Environment variables of type Array?

### ISSUE THREAD

**Issue by picsoung** [serverless/serverless#1172]
Today I wanted to use the environment variable mechanism to store an array and be able to retrieve in my code.

So in my `s-function.json` under `environment` property I added my variable:

```
“MY_VARIABLE": [
      {
        “name”:”value”
      }
 ]
```

in my `handler.js` I was trying to access `process.env.MY_VARIABLE` but it was not working.
printing it was giving me `[object Object]` and `typeof process.env.MY_VARIABLE = string`

`Object.keys(process.env.MY_VARIABLE)` was not more successful.

With the help of @Josh-a-e on gitter, he pointed to https://github.com/serverless/serverless/blob/b89200769695680106e9a3e8929a868da3f30156/lib/RuntimeNode43.js#L28
and https://github.com/serverless/serverless/blob/bf2810a7592ee593881b07842a661610a2908062/lib/Runtime.js#L52

Seems to come from the way the EnvVars are retrieved and merged.

what do you think?
Thanks

**Comment by DavidTanner** [comment]
I just published https://www.npmjs.com/package/serverless-variable-objects to address this issue.  Because the variables are placed on process.env, they are turned into strings using .toString().  This plugin will turn them into strings first using JSON.stringify() before they are added to process.env.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by diosney** [comment]
This is still happening. Please, some contributor can you look into it so a native workaround is made? Like replacing the toString for toJson, for objects, for instance.

Thanks!

**Comment by bramhoven** [comment]
This issue is still present but a simple workaround can be done using the javascript config files.
Let's say my yaml config file looks like this:
```yml
branchRouting:
  route: prefix
  routes:
    - master: prod
    - dev: staging
```

We can use a javascript config file to export that value to a json string: 
```js
const yaml = require('js-yaml');
const fs   = require('fs');
const conf = yaml.safeLoad(fs.readFileSync('./serverless.conf.yml', 'utf8'));

module.exports.branchRoutes = () => {
  console.log(JSON.stringify(conf.branchRouting.routes))
  return JSON.stringify(conf.branchRouting.routes)
}
```

I hope this issue is fixed soon, but for now you can use this workaround.
