### ISSUE TITLE
excludeDevDependencies seems to not working as expected

### ISSUE THREAD

**Issue by simon-tannai** [serverless/serverless#11742]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello 👋

I'm working on a monorepository project. That's mean I have only one huge package.json with a 2Gb `node_modules` directory.
To optimize the size of my apps, which are running on AWS Lambda, I'm building it with `esbuild`.

In most of cases, I have no any NPM module needed in production.
But, I'm still needing the `devDependencies` to build and run serverless commands on my CI/CD.

First of all, I'm installing the dependencies. Then, I'm copying it into the builded app directory. Finaly, I'm running `serverless` commands to package and deploy the app.

The issue is the `sls package` is producing an heavy `.serverless` package: all dependencies are present into this package (+2Gb).

Despite the `excludeDevDependencies` set to `true` and an empty `dependencies` attribute into the `package.json`, all the content of `node_modules` is included into the `.serverless` package.

`my-app/package.json`:
```json
{"name":"my-app","version":"0.0.1","main":"./index.cjs","devDependencies":{},"dependencies":{}}
```
File tree:
```text
- index.js
- node_modules
- package.json
- serverless.base.ts
- serverless.ts
```

How to fix this issue ?

### Service configuration (serverless.yml) content
`serverless.base.ts`:
```typescript
import type { AWS } from '@serverless/typescript';

export const baseServerlessConfig: Partial<AWS> = {
  frameworkVersion: '3.27.0',
  plugins: ['serverless-offline', 'serverless-plugin-lambda-insights'],
  package: {
    exclude: ['yarn.lock'],
    excludeDevDependencies: true,
  },
  provider: {
    name: 'aws',
    runtime: 'nodejs18.x',
    stage: process.env.NODE_ENV,
    region: 'eu-west-3',
    environment: {
      NODE_ENV: process.env.NODE_ENV as string,
    },
    iam: {
      role: {
        statements: [
          {
            Effect: 'Allow',
            Action: ['lambda:InvokeFunction'],
            Resource: '*',
          },
        ],
      },
    },
    logRetentionInDays: process.env.NODE_ENV === 'production' ? 5 : 1,
  },
};
```

`serverless.ts`:
```typescript
import type { AWS } from '@serverless/typescript';
import * as dotenv from 'dotenv';
import { baseServerlessConfig } from './serverless.base';

if (process.env.NODE_ENV === 'development') {
  dotenv.config({ path: `${__dirname}/.env.${process.env.NODE_ENV}` });
}

const envConfig = {
  memorySize: {
    development: 256,
    staging: 128,
    production: 512,
  },
  timeout: {
    development: 600,
    staging: 30,
    production: 120,
  },
  lambdaInsights: {
    development: false,
    staging: false,
    production: true,
  },
  schedule: {
    control: {
      development: 'rate(1 minute)',
      staging: 'rate(2 minutes)',
      production: 'rate(2 minutes)',
    },
  },
};

const serverlessConfiguration: Partial<AWS> = {
  ...baseServerlessConfig,
  service: 'my-app',
  custom: {
    ...baseServerlessConfig.custom,
    'serverless-offline': {
      host: '0.0.0.0',
      lambdaPort: 9922,
    },
  },
  functions: {
    'control': {
      handler: './index.handleControl',
      timeout: envConfig.timeout[process.env.NODE_ENV],
      memorySize: envConfig.memorySize[process.env.NODE_ENV],
      lambdaInsights: envConfig.lambdaInsights[process.env.NODE_ENV],
      events: [{
        schedule: envConfig.schedule.control[process.env.NODE_ENV],
      }],
    },
  },
};

serverlessConfiguration.provider.environment = {
  ...serverlessConfiguration.provider.environment,
};

module.exports = serverlessConfiguration;
```

### Command name and used flags
```shell
sls package
```

### Command output

```shell
✔ Service packaged (67s)
```

### Environment information

```shell
Framework Core: 3.27.0 (local) 3.25.1 (global)
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@simon-tannai I believe it's not working as you have `devDependencies` empty in package.json. AFAIK stripping of dev depencies works via resolving them from that field and filtering them out

**Comment by simon-tannai** [comment]
@medikoo I did a new test by including `devDependencies` and add a single `dependencies`:
```json
{
  "name": "my-app",
  "version": "0.0.1",
  "main": "./index.cjs",
  "devDependencies": {
    "@nrwl/esbuild": "15.6.3",
    "@nrwl/eslint-plugin-nx": "15.6.3",
    [...]
    "ts-prune": "0.10.3",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "nanoid": "3.1.31"
  }
}
```

I extracted the content of the `.serverless`, it's less heavy but stay huge.
Output of `du -sh -- *  | sort -rh` command:
```text
1,2G	node_modules
8,5M	index.js
4,0K	serverless.base.ts
4,0K	package.json
```

Inside the `node_modules`, I have not any development dependency but I have all dependencies of my monorepository project.

Finally, it seems `serverless` is only ignoring `devDependencies` but is copying everything else into the package ?

**Comment by medikoo** [comment]
> Finally, it seems serverless is only ignoring devDependencies but is copying everything else into the package ?

Yes, it is the desired behavior. We filter only packages that are confirmed to be dev dependencies

**Comment by simon-tannai** [comment]
Ok, thanks @medikoo . I'll find another workaround ✌️
