### ISSUE TITLE
sls dash deploy does not warn if more than one stage defined

### ISSUE THREAD

**Issue by alshamma** [serverless/serverless#1174]
Using sls 0.5.5 on OS X 10.11.5. Only plugin is serverless-cors-plugin. 

I just added a second stage, named "prod". The first is "dev". When I run dash deploy, it does not tell me I need to specify a stage. When I ran sls dash deploy, it deployed to "prod".

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
