### ISSUE TITLE
Ability to deploy GatewayAPI to one region and Lambda functions to another region

### ISSUE THREAD

**Issue by tuanmh** [serverless/serverless#1175]
Hi guys, thanks for a great framework, you save my day! 
I'm currently trying to figure out a way to deploy Endpoints to one region and Lambda functions to another region. For example, Endpoints to Singapore region (`ap-southeast-1`) and Lambda functions to Tokyo (`ap-northeast-1`). 

I have tried: `serverless region create` but got this error: `Invalid region. Lambda not supported in ap-southeast-1`, this is correct but seems it only checks for Lambda supported region instead of Gateway API supported region. 

Any guide or help on this would be really appreciated. Thanks again!

**Comment by Christoph-Schabert** [comment]
+1 also require this feature to deploy only the  function to different region

**Comment by tuanmh** [comment]
> I'm currently trying to figure out a way to deploy Endpoints to one region and Lambda functions to another region. For example, Endpoints to Singapore region (ap-southeast-1) and Lambda functions to Tokyo (ap-northeast-1).

This looks technically a design flaw but it's the case in Australia where AWS does not neither support Lambda and API Gateway. They have support  API Gateway in Singapore: our closest region, and both Gateway and Lambda in Japan.

**Comment by flomotlik** [comment]
@tuanmh @Christoph-Schabert at the moment there isn't really a way to do this as all deployments are region specific. The same applies for V1 that we're currently working on.

Is it possible to have API Gateway in one region and trigger a function in another region? Didn't know that was possible. Could you link me to the docs there and describe your use case in more detail?
