### ISSUE TITLE
Serverless package fail with aws-sdk's version upgraded to 2.1315.0

### ISSUE THREAD

**Issue by obrcnh** [serverless/serverless#11753]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Today I deploy the AWS Lambda as usual, and I find the problem as follows.

``` 
error     (node:9129) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

I find out the problem caused by aws-sdk upgrading to version 2.1315.0. But version 2.1313.0 works well. So what's the problem caused?

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless package

### Command output

```shell
×  error     (node:3792) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Environment information

```shell
Framework Core: 3.26.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by f00f** [comment]
I get the same message, but it's not treated as an error:

```
(node:32728) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `serverless --trace-warnings ...` to show where the warning was created)
```

`serverless --trace-warnings` does not work for me:

```
Error:
Detected unrecognized CLI options: "--trace-warnings".
```

Environment: win32, node 16.16.0, framework 3.27.0 (local) 3.27.0v (global), plugin 6.2.3, SDK 4.3.2

**Comment by jameshartt** [comment]
This I believe is that Serverless framework using the AWS SDK for JavaScript v2 under the hood. AWS themselves are putting the v2 sdk into maintenance mode, thus the error when using the latest v2 AWS SDK. I imagine moving over the AWS SDK v3 is not very straightforward. Lots of different design decisions and probably some very tedious work to get it to move over.

**Comment by DavidWells** [comment]
Pinning to v2.1311.0 "fixed" this issue for our cli using aws-sdk. Ref https://twitter.com/DavidWells/status/1626321488742862848

https://github.com/aws/aws-sdk-js/commit/720bc9ff1bf3be5c4478365fef1fc98be70a5d76

Pretty aggressive deprecation message from AWS here 😅

**Comment by eliasbrange** [comment]
v3 was released over two years ago. It might be time to upgrade.

**Comment by kuhe** [comment]
To suppress the maintenance mode message from the AWS SDK for JavaScript, run this code snippet either before you import the AWS SDK or in the same context.

```js
const AWS = require('aws-sdk');
require("aws-sdk/lib/maintenance_mode_message").suppress = true;
```

```js
import AWS from "aws-sdk";
import message from "aws-sdk/lib/maintenance_mode_message.js";
message.suppress = true;
```

**Comment by obrcnh** [comment]
> To suppress the maintenance mode message from the [AWS SDK for JavaScript v2](https://github.com/aws/aws-sdk-js), run this code snippet either before you import the AWS SDK or in the same context.
> 
> ```js
> const AWS = require('aws-sdk');
> require("aws-sdk/lib/maintenance_mode_message").suppress = true;
> ```
> 
> ```js
> import AWS from "aws-sdk";
> import message from "aws-sdk/lib/maintenance_mode_message.js";
> message.suppress = true;
> ```

I try it but it doesn't work well. It seems it doesn't cover the value of suppress. Where do I make a mistake?

**Comment by medikoo** [comment]
@kuhe we will welcome PR that adds this instruction.

Concerning upgrade to v3. It's doable but breaking to some plugins which rely on [`provider.sdk`](https://github.com/serverless/serverless/blob/54e7af915f367d77fa24507a47f89fdb2068f19d/lib/plugins/aws/provider.js#L224), as obviously this property will have to be removed.

We will welcome PR that upgrades to v3 but behind a flag (e.g. `provider.sdkVersion: 3`)

**Comment by kuhe** [comment]
@obrcnh what is your runtime environment? This is an emitted warning via `process.emitWarning`. Do you or `serverless` have an event listener that interacts with that warning channel?

**Comment by obrcnh** [comment]
```
Framework Core: 3.26.0
Plugin: 6.2.2
SDK: 4.3.2
```

@kuhe My runtime environment is above. I try to watch the warning event listener but it doesn't emit. Instead if I watch the event in the file `maintenance_mode_message.js`, it's OK.

**Comment by et304383** [comment]
https://github.com/aws/aws-sdk-js/issues/4354

I created a ticket to the AWS team to at least provide a way to disable this incredibly annoying warning message.

**Comment by jader-moura** [comment]
I was facing the same error, it was my approach to lead with the problem:

`
import { readFileSync } from "fs";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";


const s3 = new S3Client({
  region: process.env.NEXT_AWS_REGION,
  credentials: {
    accessKeyId: process.env.NEXT_AWS_ACCESS_ID || '',
    secretAccessKey: process.env.NEXT_AWS_SECRET_KEY || '',
  },
});

export const s3Upload = async (filePath: string, fileOriginalname: string) => {
  const fileName = `${new Date().getTime()}_${fileOriginalname}`;
  const fileContent = readFileSync(filePath);

  try {
    const command = new PutObjectCommand({
      Bucket: process.env.NEXT_AWS_S3_BUCKET || "",
      Key: fileName,
      Body: fileContent,
    });
    await s3.send(command);
    console.log('File uploaded successfully.');
  } catch (err) {
    console.error(`Error uploading file to S3: ${err}`);
  }
};

`
It was enough to solve my problem, I hope that's going to help everyone.

**Comment by robinth91** [comment]
@medikoo Still getting this issue with `3.30.1`. So its not resolved with https://github.com/serverless/serverless/pull/11769. Please reopen this issue.
