### ISSUE TITLE
AWS CloudWatch Logs Tag Based Authorization Update

### ISSUE THREAD

**Issue by mgerlach** [serverless/serverless#11762]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

See https://github.com/serverless/serverless/discussions/11605

### Proposed solution (optional)

Wherever IAM permission logs:CreateLogGroup is granted or mentioned, also include logs:TagResource

**Comment by medikoo** [comment]
@mgerlach thanks for openning. PR's welcome!

**Comment by mgerlach** [comment]
@medikoo I'm on it ... Made changes, but one test failing for some reason that I need to figure out.

**Comment by mgerlach** [comment]
@medikoo I'd appreciate some help with this test: 
https://github.com/serverless/serverless/blob/main/test/unit/lib/plugins/aws/deploy/index.test.js#L1136

which fails if I add the `logs:TagResource` permission to this line:
https://github.com/serverless/serverless/blob/main/lib/plugins/aws/package/lib/iam-role-lambda-execution-template.json#L24

It looks like serverless attempts an unexpected deployment here, presumably because due to the addition of the permission, the serverless-state.json file generated by `serverlss package`  now has a sha256 hash different from the one mocked in the test.

What's the best way to adapt the test to the addition?

**Comment by medikoo** [comment]
@mgerlach I believe it's the correct way. Those hashes are hardcoded, reflecting the current state of basic templates, so if anything changes, they should be updated.

Probably it'll be nicer to automate this hash generation, but I'd address that in separate PR
