### ISSUE TITLE
Rely on passed through serverless instance when accessing data in classes?

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1178]
Right now some of the classes access data with the help of the attached Serverless instance.

Should we keep this pattern or e.g. require necessary code at the top of the class?

Here's a simple example:
```
// VERSION 1

// file: servereless.js
const loadedPlugins = this.pluginManager.getPlugins();

CLI = new cli(loadedPlugins);

// file: cli.js
constructor(plugins) {
  this.plugins = plugins;
}

- - -

// VERSION 2

// file: servereless.js
CLI = new cli(this);

// file: cli.js
constructor(serverless) {
  this.serverless = serverless;
  this.plugins = serverless.pluginManager.getPlugins();
}
```

Version 1 doesn’t care where the plugins come from (it just needs the plugins array).
Version 2 in contrast has a dependency on the implementation of serverless. If we e.g. change plugin loading and put it into utils we have to update every file where the `pluginManager` instance is used.

**Comment by flomotlik** [comment]
@pmuens is this still an issue?

**Comment by pmuens** [comment]
Depends. I would keep this closed as the explicit requiring is impossible to do everywhere (I'm also more in favor of using the `serverless` object inside the code.
