### ISSUE TITLE
Support for the latest AWS Lambda Node 18.x runtime & AWS SDK 3.x

### ISSUE THREAD

**Issue by richard-stafflink** [serverless/serverless#11786]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Request for support for the latest Node LTS and AWS SDK for use on AWS Lambda

AWS Lambda now has support for Node 18.x + AWS SDK 3.x:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Someone has asked this question, but it's all tumbleweeds:
https://forum.serverless.com/t/support-for-nodejs18-x-and-aws-sdk-v3/18399/2

**Comment by herebebogans** [comment]
You can deploy node 18 to lambda with

```
provider:
   runtime: 'nodejs18.x'
```
sdk v3 is now bundled with node 18 lambda runtime - so you can exclude it from packaging step.

**Comment by richard-stafflink** [comment]
@herebebogans but I'm not aware of Serverless supporting Node 18 - or am I missing something?

**Comment by herebebogans** [comment]
I'm not sure exactly what you mean by supporting. You need minimum node 12 for serverless itself.

You can deploy to any AWS supported runtime including node 18.

**Comment by richard-stafflink** [comment]
Confirmed! it works, thank you both for your help.

**Comment by xyclos** [comment]
What is the actual solution for this? Our serverless.yaml file has:

```
runtime: nodejs18.x
```

our package.json file has:

```
"serverless": "^3.33.0",
```

When our service deploys, it tries to use node 12.22.11

We were previously using `runtime: nodejs16.x`, and it worked. There are multiple issues about this on the forums and here, and yet no definite solution.

I've also reached out to serverless support twice now without any response.

Any help would be greatly appreciated.
