### ISSUE TITLE
Cannot use ${name} in path

### ISSUE THREAD

**Issue by edupre** [serverless/serverless#1179]
I created this config for CRUD deployment: 

<pre>
{
  "name": "users",
  ...
  ,
  "endpoints": [
    {
      "path": "${name}",
      "method": "GET",
      ...
    },
    {
      "path": "${name}/{id}",
      "method": "GET",
      ...
    },
    {
      "path": "${name}",
      "method": "POST",
      ...
    },
    {
      "path": "${name}/{id}",
      "method": "PUT",
      ...
    },
    {
      "path": "${name}/{id}",
      "method": "DELETE",
      ...
    }
  ],
  ...
}
</pre>

I only have to change the name to deploy a new ressource.

**Bug: if I want to deploy several ressources, it only deploys endpoints for the first one.**

For instance:
>  products
      function - products
      endpoint - ${name} - GET
      endpoint - ${name}/{id} - GET
      endpoint - ${name} - POST
      endpoint - ${name}/{id} - PUT
      endpoint - ${name}/{id} - DELETE
    users
      function - users
      endpoint - ${name} - GET
      endpoint - ${name}/{id} - GET
      endpoint - ${name} - POST
      endpoint - ${name}/{id} - PUT
      endpoint - ${name}/{id} - DELETE

Deploys:
> Serverless: Successfully deployed endpoints in "dev" to the following regions:
Serverless: eu-west-1 ------------------------
Serverless:   GET - ${name} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products
Serverless:   GET - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
Serverless:   POST - ${name} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products
Serverless:   PUT - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
Serverless:   DELETE - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
Serverless:   GET - ${name} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products
Serverless:   GET - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
Serverless:   POST - ${name} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products
Serverless:   PUT - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
Serverless:   DELETE - ${name}/{id} - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/products/{id}

It even fails if I only want to deploy the second ressource with these error messages:

> Serverless: Failed to deploy endpoints in "dev" to the following regions:
Serverless: eu-west-1 ------------------------
Serverless:   GET - ${name}: Function not found: arn:aws:lambda:xxx
Serverless:   GET - ${name}/{id}: Function not found: arn:aws:lambda:xxx
Serverless:   POST - ${name}: Function not found: arn:aws:lambda:xxx
Serverless:   PUT - ${name}/{id}: Function not found: arn:aws:lambda:xxx
Serverless:   DELETE - ${name}/{id}: Function not found: arn:aws:lambda:xxx

Is it possible to replace ${name} in the path before deployment ?

Thanks.

sls v0.5.5
Ubuntu 14.04.3 LTS

**Comment by HyperBrain** [comment]
What you defined is a path parameter in your url, not a Serverless variable.
Within the path declaration of a function the notation "${xxx}" means a parameter that will be made available in your APIG endpoint. As the notation is the same as with Serverless variables, it is not possible to do that.

**Comment by edupre** [comment]
Thanks for your fast reply.

I understand but when I use ${name} in the description, it is replaced.

<pre>
{
  "name": "users",
  "runtime": "nodejs4.3",
  "description": "Serverless CRUD for ${name}",
...
</pre>

In my AWS console I can see: `Serverless CRUD for users`

Why is it replace in the description and not in the path ?
Is it replaced by serverless or by APIG ?

**Comment by HyperBrain** [comment]
It is not replaced in the path property because the ${xxx} there has a different meaning => url param! These are handled by APIG.
The other *variable* references in the other properties are replaced by Serverless.

**Comment by edupre** [comment]
Maybe I'm wrong but {xxx} is an url param, not ${xxx}.
Don't you think that it could be usefull to ban _${xxx}_ in the path if _xxx_ is a variable ?

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
