### ISSUE TITLE
Explain limitations of Lambda

### ISSUE THREAD

**Issue by lorensr** [serverless/serverless#1182]
In readme or docs, for those coming to serverless who are unfamiliar with lambda. Eg:
- can't ssh in, can't install software
- can't keep in-memory cache, eg session data

**Comment by mikelax** [comment]
Maybe just a link to the [AWS Lambda FAQ](http://aws.amazon.com/lambda/faqs/) page? It's a pretty good start of what lambda is and limitations and simple guidelines.

**Comment by jordanmack** [comment]
I would recommend just linking to the appropriate AWS pages as well. That's going to be the most up to date place for information as AWS continues to update their service.

In the future, once Serverless supports multiple platforms, then it might be more appropriate to create some kind of a table that shows the unique differences between the supported platforms.

**Comment by flomotlik** [comment]
@lorensr yup this definitely makes sense to include in the new V1 docs. Set it as a goal for V1 and documentation. Which pages would you link to and where in the docs?

**Comment by lorensr** [comment]
Since the FAQ is pretty long, I would directly mention the few largest things like those above (perhaps they're the same for the other provers?), then link to FAQ for each provider for more limitations/info.

Somewhere in the introduction, so I know whether this library is a fit for me. Backstory or Overview?

**Comment by flomotlik** [comment]
Going to close this as we redid our docs recently and really focus on the framework and link to AWS docs where appropriate
