### ISSUE TITLE
Bug in UI

### ISSUE THREAD

**Issue by abhinav2712** [serverless/serverless#11828]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Its basically a fault in the UI of this particular section in which the numbers are just touching the above buttons which looks quite odd. 
Assign me this issue, I cant fix this 

![image](https://user-images.githubusercontent.com/68495520/225784574-53d12d35-cf44-47ec-8ee9-41aa475f522b.png)
Happy Hacking

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
serverless
```

**Comment by medikoo** [comment]
@abhinav2712 great thanks for reporting. It should be fixed now
