### ISSUE TITLE
Problems that occur when Serverless deploy is forcibly terminated

### ISSUE THREAD

**Issue by archepro84** [serverless/serverless#11852]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

![스크린샷 2023-03-23 오전 9 15 45](https://user-images.githubusercontent.com/49636918/227067660-ab3fce46-4f91-4ede-8448-501f931cff2e.png)  

![스크린샷 2023-03-23 오전 9 21 56](https://user-images.githubusercontent.com/49636918/227067873-d506ec57-46a2-4483-a021-456205c6bcff.png)  

![스크린샷 2023-03-23 오전 9 17 12](https://user-images.githubusercontent.com/49636918/227067667-5bab7973-80a4-482c-a47f-384e68d8bbbf.png)

There is a problem that the CloudFormation stack is created abnormally when serverless-cli is forcibly terminated in the “Creating CloudFormation stack” process after executing `Serverless deploy`.

This is not only an abnormal creation, but also causes an error message such as `*Stack [SERVICE_NAME] does not exist*` when the `serverless deploy` command is executed again.

To solve this problem, there is a way to directly connect to AWS CloudFormation and remove the abnormally created stack, or manually remove the abnormal stack through the `serverless remove` command. I don't think this is an intuitive solution, and when I execute the serverless deploy command, I think it is correct to automatically delete stacks with abnormal status in the process of searching CloudFormation's stacks.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Deploying prac-websocke to stage dev (ap-northeast-2)

Packaging
Excluding development dependencies for service package
Retrieving CloudFormation stack
Deployment bucket not found. Updating stack to include deployment bucket definition.
Ensuring that deployment bucket exists
Creating new change set.

✖ Stack prac-websocke-dev failed to deploy (8s)
Environment: darwin, node 18.12.1, framework 3.28.1, plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Stack [prac-websocke-dev] does not exist
```

### Environment information

```shell
Framework Core: 3.28.1
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@archepro84 thanks for openning that. So you're suggestion is to attempt to remove the stack in case of abnormal state.

Which states would you assume as "abnormal"?

**Comment by archepro84** [comment]
<img width="1029" alt="2023-03-23 4 34 16" src="https://user-images.githubusercontent.com/49636918/227135839-40c57056-1afe-4ca6-b31b-69967c4a637b.png">
<img width="1027" alt="스크린샷 2023-03-23 오후 4 34 22" src="https://user-images.githubusercontent.com/49636918/227135940-1a63a8a5-93d1-4133-8cc6-1cb56c2f5792.png">

@medikoo 
When the `serverless deploy` command is executed, it would be better to view the state in which the stack of AWS CloudFormation has only been created as an abnormal state.

As in the state in which Stack's Events and Resources are not registered.

For example, like the current image, _**prac-websocket-dev**_ Stack is in the `REVIEW_IN_PROGRESS` state, and no Events or Resources are registered, so it can be seen as an abnormal stack state.

**Comment by archepro84** [comment]
Sorry, I clicked the wrong assignment button. 🥲

It is also a good criterion that the condition has been maintained for a long time.
When executing `serverless deploy`, if the stack of AWS CloudFormation that already exists is as follows, it would be better to consider it as an abnormal state.

1. Maintain `REVIEW_IN_PROGRESS` status for a long time
2. Events do not exist
3. Resource does not exist

In addition, it would be nice to add a condition to recognize that the stack is in an abnormal state.

**Comment by medikoo** [comment]
@archepro84 I think best solution for that is to abort with user friendly message if on deployment stack is in `REVIEW_IN_PROGRESS` e.g.:

_Service cannot be deployed as the CloudFormation stack is found to be in the "REVIEW_IN_PROGRESS" state. This may signal either that stack is currently deployed by a different entity, or that the previous deployment failed and was left in an abnormal state, in such case you can mitigate the issue by running "sls remove"_

WDYT?

**Comment by archepro84** [comment]
As you said, rather than forcibly removing Stack from serverless, it seems more correct to share the current situation with users through messages.

It seems so good!
