### ISSUE TITLE
Hard dependency on correct YAML file extension in Service class

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1186]
Right now the Service class has a "hard" dependency on the correct file extension (must be `.yaml`).

Would be great to support `.yml` as well.

https://github.com/serverless/serverless/blob/v1.0/lib/classes/Service.js#L39

**Comment by HyperBrain** [comment]
If both are supported it also had to define a priority if someone has both files (yaml and yml) in parallel or at least bail out with an appropriate error message.

**Comment by pmuens** [comment]
Good catch. Not quite sure if we should force the user to use just one name (e.g. only support `.yaml` as this is the "official" standard) so that we don't have to deal with those situations.
