### ISSUE TITLE
AWS Lambda response streaming for function urls

### ISSUE THREAD

**Issue by grakic** [serverless/serverless#11906]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS recently released support for [response streaming](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/) accessible through Lambda Function URLs.

To utilize this new integration, `AWS::Lambda::Url` includes an optional property, `InvokeMode`. When the Lambda Function URL invoke mode is set to `RESPONSE_STREAM`, the Lambda function handler will be invoked using the new InvokeWithResponseStream API.

While Serverless Framework can provision AWS::Lambda::Url, it is not exposing InvokeMode property.

### Proposed solution (optional)

Expose optional `url.invoke: 'buffered' | 'response_stream'` property in Lambda Function URL configuration mapping to [AWS::Lambda::Url InvokeMode property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-url.html).

Shorter name and lowercase values are matching `authorizer` that maps to the AuthType property.

**Comment by stevestorey** [comment]
I think that the Serverless SDK wrapper will need to be updated to notice that the overall handler should be wrapped via `awslambda.streamifyResponse` otherwise the AWS runtime doesn't know that you want that behaviour (and the wrapper will need to therefore process the context and stream differently)

**Comment by grakic** [comment]
I am not familiar with Serverless SDK but would not this be handled by [serverless/dashboard-plugin](https://github.com/serverless/dashboard-plugin) based on invoke mode defined in this PR?

**Comment by medikoo** [comment]
@grakic Great thanks for openning that. I like the proposed solution, I would just use `invokeMode` instead of just `invoke` as it feels to ambiguous. In case of `authorizer`, this one reflects authorizer configurations in other parts of the service config where it can be rich object configuration or simply`aws_iam` instruction.

Will look shortly into proposed PR

**Comment by grakic** [comment]
@medikoo Thanks, code updated to use `invokeMode: 'BUFFERED' | 'RESPONSE_STREAM'`.

**Comment by harounansari-cj** [comment]
Is there a work around for this until the PR is out?

**Comment by grakic** [comment]
@harounansari-cj You can overwrite CloudFormation template via [resources](https://www.serverless.com/framework/docs/providers/aws/guide/resources) adding snippet to your serverless.yml file where `HelloLambdaFunctionUrl` is normalized name of your Lambda URL resource.

```
resources:
  Resources:
    HelloLambdaFunctionUrl:
      InvokeMode: RESPONSE_STREAM
```

To see the resource name for your project, either run `serverless package` and find "Lambda::Url" resource in generated `.serverless/cloudformation-template-update-stack.json` file, or review existing CloudFormation stack deployed in AWS.

**Comment by alramalho** [comment]
In which version is this availalbe in `aws-cdk-lib`?

I'm using the latest (`2.85.0` as the time of writing) and it does not recognize the `invokeMode` in the lambda config, contrary to what the [docs say](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html)

```
Property 'InvokeMode' does not exist on type ...aws-cdk-lib/aws-lambda
```

**Comment by MBtea** [comment]
@alramalho try upgrade cdk version to ```2.115.0``` which will export ```InvokeMode```

**Comment by ibrahimjelliti** [comment]
I am using `invokeMode: RESPONSE_STREAM` in functions but it's not available in the cloud formation json
