### ISSUE TITLE
Remove automatic servicePath detection

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1192]
https://github.com/serverless/serverless/pull/1187 introduced automatic servicePath detection.

This might confuse users. Serverless should only check in the CWD for the `serverless.yaml` file and throw an error otherwise.

**Comment by flomotlik** [comment]
This is done already @pmuens ? I'll close this issue, if its already removed don't answer and I'll consider this done

**Comment by pmuens** [comment]
Unfortunately not done yet... Reopening.

**Comment by pmuens** [comment]
Resolved with https://github.com/serverless/serverless/pull/1882
