### ISSUE TITLE
python3.10 support

### ISSUE THREAD

**Issue by relsunkaev** [serverless/serverless#11921]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS just released support for the python3.10 lambda runtime, would be nice to add support for it.

<img width="1006" alt="Screenshot 2023-04-17 at 11 42 13 PM" src="https://user-images.githubusercontent.com/35545693/232593805-11769670-709c-4308-b058-666d5bdd7746.png">

**Comment by yeyeric** [comment]
I see that a PR was made, thanks @t3yamoto
Should we expect quick delivery or is there a planning line weekly release or something ?
Thanks

**Comment by t3yamoto** [comment]
@yeyeric 
Hi, This is my first contribution, so I'm not sure about releases. We can deploy it as it is now, though We get warnings.
Thanks.

**Comment by yeyeric** [comment]
thanks, I thought it was blocking

**Comment by joshorr** [comment]
@t3yamoto I seem to be getting an error when I use `runtime: python3.10`, is there a way to make this a warning so I can use python3.10 in the mean time? I would love to know!

Here is the error I am currently getting:

```
Error:
Configuration error at 'provider.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]
```
