### ISSUE TITLE
Support for Java17 as runtime for AWS Lambda functions

### ISSUE THREAD

**Issue by debae** [serverless/serverless#11937]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Java17 is now also supported by AWS as runtime : https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/ 
We should have this option as well in the supported runtimes of serverless framework

### Proposed solution (optional)

Add java17 as option in the enum : https://github.com/serverless/serverless/blob/bc99c2c516b03f005c3f8447b796306336c9275e/lib/plugins/aws/provider.js#L620 
add the option in : 
https://github.com/serverless/serverless/blob/bc99c2c516b03f005c3f8447b796306336c9275e/lib/plugins/aws/invoke-local/index.js#L269
Update documentation about snapstart since this also supports Java17 : https://github.com/serverless/serverless/blob/54e7af915f367d77fa24507a47f89fdb2068f19d/docs/providers/aws/guide/functions.md#L446

**Comment by debae** [comment]
You can assign this issue to me , I'm working on a PR right now.

**Comment by mike-022** [comment]
Hey, has this been rolled out into a release?

**Comment by benrhine** [comment]
Agreed, do we have an expected release date on this? As I'm building a new service for work and we would prefer to be on the latest lts

**Comment by moia-lars** [comment]
> Agreed, do we have an expected release date on this? As I'm building a new service for work and we would prefer to be on the latest lts

It was released on may 17th https://github.com/serverless/serverless/releases/tag/v3.31.0
