### ISSUE TITLE
Security Question

### ISSUE THREAD

**Issue by aliatsis** [serverless/serverless#1194]
Hi, I have a few quick questions:

1. Where is the lambda code stored in AWS when deployed by serverless?
2. Is the code encrypted at rest? (If not, can it be?)
3. How secure are environment variables sourced from the _meta directory since they are ultimately packaged within the zipped lambda package that is uploaded?

Thanks in advance!

**Comment by flomotlik** [comment]
1. The deployment artefact is stored in S3 during deployment, then AWS picks it up and stores it in their internal system
2. not by default and AWS doesn't provide this directly. You might be able to work around it, but thats going to be tough.
3. In V1 we're planning a different approach with environment variables, you can read more in #472 

I suppose this is for Financial Data Compliance reasons? You can also reach out to me via flo@serverless.com, happy to help with any questions. Going to close this issue now here as its more of a support request.

**Comment by aliatsis** [comment]
@flomotlik thanks for the help! Yes, at some point I will need to be PCI compliant.
