### ISSUE TITLE
--region options does not help to update aws service endpoint when we try to deploy

### ISSUE THREAD

**Issue by nminhquang** [serverless/serverless#11961]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi Team

As company policy, I'm not allowed to access aws service endpoints like s3.amazonaws.com, lambda.amazonaws.com, ssm.amazonaws.com ...
But I'm allowed to access service region endpoints: s3.eu-central-1.amazonaws.com, lambda.eu-central-1.amazonaws.com, ...
So I tried to set **--region** in sls command to deploy but it failed:
**sls deploy --config serverless.yml --stage $ENV_NAME --region $AWS_DEFAULT_REGION --verbose**
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
(node:36) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
**Serverless: [AWS ssm 403 0.034s 0 retries] getParameter({ Name: '/abc-dev-sg-id', WithDecryption: true })
Serverless: [AWS ssm 403 0.056s 0 retries] getParameter({ Name: '/abc-dev-lambda-kms-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.019s 0 retries] getParameter({ Name: '/abcl-dev-subnet-id-2', WithDecryption: true })
Serverless: [AWS ssm 403 0.03s 0 retries] getParameter({ Name: '/abc-dev-subnet-id-1', WithDecryption: true })
Serverless: [AWS ssm 403 0.018s 0 retries] getParameter({ Name: '/abc-dev-lambda-role-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.031s 0 retries] getParameter({ Name: '/abc-dev-sqs-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.024s 0 retries] getParameter({
  Name: '/aws/reference/secretsmanager/acs-dev-euc1-abc-dbpass-application',
  WithDecryption: true
})**

It tried to get secret value from secret manager but it is rejected by firewall rule

I assume that --region which not help to update service endpoint to region endpoint

Please correct me if i'm wrong

Thanks alot

### Service configuration (serverless.yml) content

```yaml
"N/A"
```

### Command name and used flags

sls deploy --config serverless.yml --stage $ENV_NAME --region $AWS_DEFAULT_REGION --verbose

### Command output

```shell
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
(node:36) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
**Serverless: [AWS ssm 403 0.034s 0 retries] getParameter({ Name: '/abc-dev-sg-id', WithDecryption: true })
Serverless: [AWS ssm 403 0.056s 0 retries] getParameter({ Name: '/abc-dev-lambda-kms-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.019s 0 retries] getParameter({ Name: '/abcl-dev-subnet-id-2', WithDecryption: true })
Serverless: [AWS ssm 403 0.03s 0 retries] getParameter({ Name: '/abc-dev-subnet-id-1', WithDecryption: true })
Serverless: [AWS ssm 403 0.018s 0 retries] getParameter({ Name: '/abc-dev-lambda-role-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.031s 0 retries] getParameter({ Name: '/abc-dev-sqs-arn', WithDecryption: true })
Serverless: [AWS ssm 403 0.024s 0 retries] getParameter({
  Name: '/aws/reference/secretsmanager/acs-dev-euc1-abc-dbpass-application',
  WithDecryption: true
})**
```

### Environment information

```shell
serverless@2.72.2
```

**Comment by nminhquang** [comment]
I also tried with latest serverless version(3.30.1) but it still failed:
$ sls deploy --config serverless.yml --stage $ENV_NAME --region $AWS_DEFAULT_REGION --verbose
(node:35) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Environment: linux, node 14.21.3, framework 3.30.1, plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.kmsKeyArn": Forbidden,
  - Cannot resolve variable at "custom.db_secret": Forbidden,
  - Cannot resolve variable at "provider.vpc.securityGroupIds.0": Forbidden,
  - Cannot resolve variable at "provider.vpc.subnetIds.0": Forbidden,
  - Cannot resolve variable at "provider.vpc.subnetIds.1": Forbidden,
  - Cannot resolve variable at "functions.Producer.role": Forbidden,
  - Cannot resolve variable at "functions.Consumer.role": Forbidden,
  - Cannot resolve variable at "functions.Consumer.events.0.sqs.arn": Forbidden,
  - Cannot resolve variable at "resources.Resources.InvokeConsumerFunctionPermission.Properties.SourceArn": Forbidden

**Comment by medikoo** [comment]
@nminhquang I'm closing this one as it's not readable. Please fully respect the template (providing the answer to __all__ questions in full) and report the issue only if you really rely on the latest version
