### ISSUE TITLE
Test our CF deployment assumptions

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1196]
- [x] If we protect a certain resources via Stack Policies, would any updates to that resource cause the entire stack deployment to **fail** or it'll just **skip** that particular update silently? 
- [x] Does lambda use the code from the S3 bucket we specified in CF or copy it somewhere safe? (so that we can safely delete the bucket)

**Comment by eahefnawy** [comment]
## CloudFormation Stack Policy Test
### Reasons to Test
We want to test deploying functions via CloudFormation proposal. But because we can't attach a zip file for the lambda function in the CF stack, we need to first deploy the stack with empty code, then deploy the code via Lambda API. We'll then remove the function resources from the stack so it wouldn't overwrite the deployed code with blank code. However if we do that, the function resource will be deleted altogether. So instead, we want to protect the function resource to not be updated with blank code and instruct CF to skip any updates to that function resource via Stack Policies.

### The Assumption
We're assuming that we can set a stack policy on the function resource that would protect the resource from being updated **without causing the entire stack to fail**. Simply skipping updating that function resource.

### The Test
To test this, I created a simple stack that creates 2 S3 buckets. I then added a stack policy that prevents updates to the first S3 bucket but allows update to the second. After the stack and resources are created, I updated the stack by updating the first and second bucket.

**Desired Behavior** The second bucket gets updated, while the first one is protected and not updated. The first bucket should simply be skipped because it denies updates from the stack policy.

**Actual Behavior:** The entire stack update failed. CF threw an error stating that "Update failed because we're trying to update a protected resource". CF didnt even attempt to update the second bucket/resource.

<img width="1199" alt="screen shot 2016-05-27 at 4 47 31 pm" src="https://cloud.githubusercontent.com/assets/2312463/15611870/a72bf7a2-242c-11e6-95f8-da8ec8226c67.png">

### Conclusion
Stack Policies are used only to protect valuable resources (ie. production database) from being updated **accidently**. It was never meant to control deployment processes. As such we can't depend on it to protect our functions from being overwritten with blank code

**Comment by eahefnawy** [comment]
## Create Simple S3 Stack Test
I tried to create an S3 bucket via CF, and it took exactly 26 seconds for the bucket to be created. Way to long for our needs and using the API would be much faster.

**Comment by mhahn** [comment]
I haven't been thoroughly following this issue, and this might be off base,
but it could be possible to leverage AWS CF Custom Resources to handle the
lambda deployment which would let you define everything within the
cloudformation template but customize how you deploy the lambda function.

You can see an example of where @ejholmes has done this with empire:
-
https://github.com/remind101/empire/blob/master/server/cloudformation/cloudformation.go
- https://github.com/remind101/empire/pull/855

In the above case it relies on the empire server being set up to process
custom resource requests, but I think you could use a lambda function as a
"builder" of other lambdas?

Just a thought I had while reading through your description. I'm also on a
phone or I would try and give more details.

**Comment by eahefnawy** [comment]
Thanks for sharing @mhahn ... we're currently investigating the best/fastest way to deploy lambda and what you suggested looks interesting! Looking it up...

**Comment by flomotlik** [comment]
@mhahn yup thought about that as well, the only Issue I currently see with this approach is that we have to deploy a Lambda function first to then deploy the CF stack, which would mean we have resources out of the CF stack. This would make it hard to delete.
