### ISSUE TITLE
iamRoleArnLambda property missing from _meta/variables/s-variables-${stage}-${region}.json after project init

### ISSUE THREAD

**Issue by psiniemi** [serverless/serverless#1197]
When doing ```sls project init``` for a project that has it's resources already deployed (in a clean checkout or after ```git clean -fdx```), the initialization doesn't get the iamRoleArnLambda from the existing stack and subsequent endpoint deployments fail with the message:
```
Serverless:   GET - ${function}: Cannot read property 'replace' of undefined
```

The following diff would fix 0.5.5 version:
```
diff --git a/lib/actions/ResourcesDeploy.js b/lib/actions/ResourcesDeploy.js
index 5572eea..aa285b4 100644
--- a/lib/actions/ResourcesDeploy.js
+++ b/lib/actions/ResourcesDeploy.js
@@ -303,7 +303,7 @@ module.exports = function(S) {
 
             // No updates are to be performed
             if (e.message == 'No updates are to be performed.') {
-              return 'No resource updates are to be performed.';
+              return aws.request('CloudFormation', 'describeStacks', {StackName: stackName}, stage, region);
             }
 
             // If does not exist, create stack
```

**Comment by eigenhombre** [comment]
We are getting bit by this one today :-(.  Would love to see the fix for this get released!

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
