### ISSUE TITLE
Allow AWS Lambda function events[].stream.consumer to be explicitly set to false

### ISSUE THREAD

**Issue by mjdickinson** [serverless/serverless#11988]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Right now the configuration schema allows the `consumer` property of a Kinesis stream event handler to be `undefined`, `true`, or the ARN of an existing lambda function.  This makes it a pain to enable/disable enhanced fanout using a stage variable.  It should be possible to explicitly set the property to 'false' to disable enhanced fanout.

### Proposed solution (optional)

Actually pretty simple - just allow `false` in the config schema.

**Comment by medikoo** [comment]
@mjdickinson simply set it to `null`

**Comment by mjdickinson** [comment]
Thanks for taking the time to reply @medikoo.

The problem is I can't set it to `null` using a variable, because that results in a variable resolution error.

My use-case is this: I want to not use enhanced fanout in dev stages to save some cost.  But I do want it in staging and production stages.  Any pointer on how that can be achieved is welcome.

For the last couple of years we've had a hack using the **_serverless-plugin-ifelse_** plugin to exclude the `consumer` node from the config if it is set to `false`.  But it's a bit flaky and I'd like to remove it.

**Comment by medikoo** [comment]
> The problem is I can't set it to null using a variable, because that results in a variable resolution error.

You can do it, just use `null` as a fallback (clarify an intention to resolve with `null` if previous variable source doesn't provide a value. e.g. ${env:FOO, null}`

**Comment by mjdickinson** [comment]
Thanks, it works.  That is a handy trick.
