### ISSUE TITLE
Build failure after Serverless v3.32.0 release

### ISSUE THREAD

**Issue by nelsonlazar** [serverless/serverless#12000]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Build failure with below error after v3.32.0 release

`Resource handler returned message: "The provided execution role does not have permissions to call CreateNetworkInterface on EC2`

It looks like "IamRoleCustomResourcesLambdaExecution" role needs to have "AWSLambdaVPCAccessExecutionRole" policy after v3.32.0 release.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by franciszabala** [comment]
Probably cause by this fix [https://github.com/serverless/serverless/pull/11985](url)
for this bug [https://github.com/serverless/serverless/issues/11856](url)

Current fix is to revert back to 3.31.0. Will now practice version locking

**Comment by nelsonlazar** [comment]
Yeah, version lock to previous version worked for us, but looking for permanent fix here.

**Comment by medikoo** [comment]
@Lokesh-Jawale apparently #11985 introduced regression

**Comment by medikoo** [comment]
Sorry for trouble, will revert https://github.com/serverless/serverless/pull/11985 now, and issue a new release
