### ISSUE TITLE
Add PluginStore class to enable plugin to plugin communication

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1200]
Plugins should be able to communicate between each other.

Direct dependencies between plugins (e.g. access the functionality of a plugin inside another plugin with the help of `this.serverless.pluginManager.plugins.[pluginName].foo()`) introduces tight coupling as function names or the implementation might change.

It would be great to have a place where plugins can store information during runtime. This can be done with the help of a `PluginStore` class the plugin can use to add information inside the `PluginStores` object (something similar is done [here](https://github.com/serverless/serverless/blob/fd6adee562b6aec3fced9e2e15dc1363615de57f/lib/plugins/awsCompileFunctionsToResources/awsCompileFunctionsToResources.js#L132-L169) where the `service.resource.aws` property is used to store compiled function resources.

The stored information is automatically namespaced so that plugins who give keys the same name won't overwrite each other.

Here's a simple proposal which shows how this might work:

```javascript
// PluginStore.js
class PluginStore {
  constructor() {
    this.store = {};
  }

  setValue(key, value) {
    // automatically extract the plugins name
    this.store[pluginName].key = value;
  }

  getValue(pluginName, key) }
    return this.store[pluginName][key];
  }
}

// FooPlugin.js
class FooPlugin {
  constructor(serverless) {
    this.serverless = serverless;

    this.serverless.pluginStore.setValue('greeting', 'hello world!');
  }
}

// BarPlugin.js
class BarPlugin {
  constructor(serverless) {
    this.serverless = serverless;

    // set inside the constructor for demonstration purpose
    // might also e.g. be used inside a hook which is run after FooPlugin runs
    this.greeting = this.serverless.pluginStore.getValue('FooPlugin', 'greeting');
  }
}
```

@HyperBrain Does this solve the problem you face when you want to exchange data between plugins?

**Comment by HyperBrain** [comment]
@pmuens Yes, it should be solved by that. Maybe we even could create a Plugin base class, thet automatically aggregates the PluginStore object. Each plugin should then be inherited from the Plugin base class. This would decrease the chance of mis-implementations and mis-use of the PluginStore.
What do you thing about that?

**Comment by pmuens** [comment]
@HyperBrain Thank you for your feedback.
That could also be an idea as it makes it more transparent that this is possible / how it's possible.
We'll tinker a little bit around and see what solution is the nicest.

**Comment by pmuens** [comment]
Notes by @HyperBrain (sent via Gitter):

- Create Plugin base class
- This will also handle namespacing

```
class Plugin {
  constructor(pluginName) {
    this._pluginStore = new PluginStore(pluginName);
  }

  get pluginStore() {
  }
  ...
}
```

**Comment by flomotlik** [comment]
Not sure if we need this any more. Imho maybe at some point, but would close the issue until this comes up again.
