### ISSUE TITLE
Missing support of Ruby 3.2 runtime (new runtime available at AWS Lambda for Ruby)

### ISSUE THREAD

**Issue by jschulenklopper** [serverless/serverless#12025]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Starting from June 7, 2023, a new Ruby runtime version for AWS Lamba is available, "ruby3.2". See https://aws.amazon.com/blogs/compute/ruby-3-2-runtime-now-available-in-aws-lambda/ for the news release.

Running `sls info` in a project that refers to the `ruby3.2` runtime in the `provider` section of the `serverless.yml` returns:
> Warning: Invalid configuration encountered at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, ruby2.7]

Fortunately, the functions can be deployed, and are working in a Ruby 3.2 runtime container. So, it's only an inconvenience (and a no-longer-applicable-warning) and not a problem.

### Service configuration (serverless.yml) content

```yaml
n/a
```

### Command name and used flags

serverless info

### Command output

```shell
Warning: Invalid configuration encountered at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, ruby2.7]
```

### Environment information

```shell
Framework Core: 3.32.2
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@jschulenklopper thanks for reporting. PR that adds new runtime to config is welcome!

**Comment by medikoo** [comment]
@jschulenklopper ah.. yes, I also forgot about that. It'll be published with next release
