### ISSUE TITLE
Release v3.33.0 release build got stuck

### ISSUE THREAD

**Issue by chenrui333** [serverless/serverless#12043]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

the 3.33.0 release build got stuck
![image](https://github.com/serverless/serverless/assets/1580956/4e9f3854-c1dd-4a33-932c-d50b082e0ceb)

### Service configuration (serverless.yml) content

```yaml
n/a
```

---

relates to https://github.com/Homebrew/homebrew-core/pull/134994

**Comment by medikoo** [comment]
@chenrui333 we're aware of that problem

**Comment by chenrui333** [comment]
Thanks @medikoo!

**Comment by medikoo** [comment]
v3.33.0 was just released
