### ISSUE TITLE
team@serverless.com doesnt work?

### ISSUE THREAD

**Issue by contractorwolf** [serverless/serverless#1207]
I tried to send an email here: team@serverless.com and the email got bounced back to me with this message:

We're writing to let you know that the group you tried to contact (team) may not exist, or you may not  have permission to post messages to the group. A few more details on why you weren't able to post:
 
* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/serverless.com/bin/topic.py?topic=25838.

Thanks,

serverless.com admins

**Comment by flomotlik** [comment]
fixed it in the README. Team@ is only for internal communication.
