### ISSUE TITLE
Serverless fails on importing serverless library in Python2.7

### ISSUE THREAD

**Issue by mynameismevin** [serverless/serverless#1209]
- What version of Serverless you're using, and the platform(s) you're running it on?

0.5.5 on OS X.

- What packages or other dependencies you're using?

None
- The behavior you expect to see, and the actual behavior

Expected Python to work out of the box, actual behaviour was Python not importing the library module.

- If you're facing Errors, make sure to provide the full Error stack
```bash
% curl -v -XGET https://kqquekhfw6.execute-api.us-west-2.amazonaws.com/beta/validation
*   Trying 52.84.24.115...
* Connected to kqquekhfw6.execute-api.us-west-2.amazonaws.com (52.84.24.115) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.execute-api.us-west-2.amazonaws.com
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> GET /beta/validation HTTP/1.1
> Host: kqquekhfw6.execute-api.us-west-2.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Content-Length: 65
< Connection: keep-alive
< Date: Tue, 31 May 2016 15:54:35 GMT
< x-amzn-RequestId: f8f9cb5e-2747-11e6-b463-153261bd2243
< X-Cache: Miss from cloudfront
< Via: 1.1 5b51f6e8f38342d63beb93a0db7a392b.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: xMECtMFpLnVPcW7a6xxOHjOAKWwEhQonGMXwgQlff_qa5m4j6wmqyQ==
<
* Connection #0 to host kqquekhfw6.execute-api.us-west-2.amazonaws.com left intact
{"errorMessage": "Unable to import module '_serverless_handler'"}%
```

Function code:
```python
from __future__ import print_function

import json
import logging
import os
import sys

# load other libraries into the runtime path.
here = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(here, "../"))

# import loaded libraries.
import lib

log = logging.getLogger()
log.setLevel(logging.DEBUG)

def handler(event, context):
    log.debug("Received event {}".format(json.dumps(event)))
    return lib.reports()

```

The `lib.reports()` function just loads a json file and returns it.

**Comment by mynameismevin** [comment]
I think I found the problem. I'm not a Javascript guy, so I'm not sure I could really fix it, sorry.

```javascript
/**
     * Get Handler
     */

    getHandler(func) {
      return path.join(path.dirname(func.handler), "_serverless_handler.handler").replace(/\\/g, '/');
    }

    /**
     * Add ENV Vars In-line
     * - Adds a new handler that loads in ENV vars before running the main handler
     */

    _addEnvVarsInline(func, pathDist, stage, region) {
      return this.getEnvVars(func, stage, region)
        .then(envVars => {

          const handlerArr = func.handler.split('.'),
            handlerDir = path.dirname(func.handler),
            handlerFile = handlerArr[0].split('/').pop(),
            handlerMethod = handlerArr[1];

          let loader = ['import os, sys'];
          loader = loader.concat(_.map(envVars, (value, key) => `os.environ['${key}'] = str('${value}')`));
          loader.push('here = os.path.dirname(os.path.realpath(__file__))');
          loader.push('sys.path.append(here)');
          loader.push(`from ${handlerFile} import ${handlerMethod}`);

          return fs.writeFileAsync(path.join(pathDist, handlerDir, '_serverless_handler.py'), loader.join('\n'));
        });
    }
```

It looks like when `RuntimePython27.getHandler()` is called, it's not checking s-function.json to see if there is a separate handler configuration, so when the function is invoked, it's setting the function's handler to be `_serverless_.handler`, when really it should be `handler.handler` (I left it as the default).

**Comment by bomatson** [comment]
+1 having this problem

**Comment by mmoutenot** [comment]
It actually looks like it is supposed to move it to `_serverless_handler`

> Here is what happens when you deploy your Function's Code:

> Your regular handler file is replaced by one that Serverless adds titled _serverless_handler, which contains your Function's Environment Variables in-lined in the code.

That doesn't explain why it isn't working. I am running into the same problem with the starter python project (https://github.com/alexcasalboni/serverless-starter-python)

**Comment by wbaelen** [comment]
I think the error occurs when the dependencies are not uploaded. What is the handler name in your `s-function.json`? If it doesn't have a path which includes your dependencies then that could be the issue.
Did you install them into the `vendored` directory?

**Comment by zallek** [comment]
I had the same problem.

The problem was that **some dependencies were not included in the distribution directory**.
I solve the thing by updating my `excludePatterns`.
```JSON
"custom": {
  "excludePatterns": [
    ".git",
    "node_modules/eslint"
  ],
},
```
to
```JSON
"custom": {
  "excludePatterns": [
    ".git/",
    "node_modules/eslint"
  ],
},
```
Indeed patterns patterns seems to not work as we could expect: `".git"` was preventing the dist to include folders name `github` and a file name `github.js`.

Is it a bug ? maybe excludePatterns should require to define patterns in a more restrictive way.

Though in the building step, when creating `_serverless_handler.handler`, if something check that function dependencies exist in the dist folder, it **should return an explicit error** when some are missing.

**Comment by alexcasalboni** [comment]
Hi guys,

I have updated the README [here](https://github.com/alexcasalboni/serverless-starter-python).

The import error occurs only if you don't pip install your Python dependencies.

You can find a more detailed explanation [here](https://github.com/alexcasalboni/serverless-starter-python/issues/2).
