### ISSUE TITLE
Integration test for AWS integration

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1212]
To make sure our basic AWS integration works well we have to set up an integration test that walks through the following steps:

* Create a new service with the create command locally
* Deploy the service to AWS
* Invoke the Service and validate it ran correctly (e.g. check Log message or similar)
* Update the Service with new code
* Invoke the Service and validate it ran correctly (e.g. check Log message or similar)
* Remove the Resources from AWS
* Validate everything was removed and properly cleaned up

This integration test will make sure we're not breaking our AWS integration in a major way.

**Comment by pmuens** [comment]
Open questions:
- How do we handle credential mgmt. for CI tool such as Travis-CI?
- Way to skip this test / only run when requested to do so

**Comment by flomotlik** [comment]
1) We can use encrypted environment variables inside travis: https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

Those are not made available to Pull Requests from other repos so we can use they keys there.

2) I do want to run the build for every branch (especially our internal ones) so we make sure its definitely running. We can make sure it runs only in CI by default thought so its not constantly run on your local system (which would also fail)
