### ISSUE TITLE
AWS Event Bridge Scheduler support

### ISSUE THREAD

**Issue by fcappi** [serverless/serverless#12121]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently serverless framework support creating EventBridge rules that can be used to trigger scheduled tasks.

AWS also have a specific service inside EventBridge called "Scheduler" that provide extend capabilities than rules.

The goal here is to suggest and discuss the support for EventBridge Scheduler.

Reference:
EventBridge schedule via rules(Currently supported): https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html
EventBridge Schedules(Currently NOT supported): https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduler.html

**Comment by fcappi** [comment]
Already supported, check end of page

http://serverless.com//framework/docs-providers-aws-events-schedule

**Comment by qurfy** [comment]
Even with `"method": "scheduler"`, I still see EventBridge rule but not scheduler. Relevant section from serverless.ts file
```
events: [
    {
      schedule: {
        method: "scheduler",
        description: "Exports data for test region",
        name: "exportTestData",
        rate: ["rate(24 hours)"],
        enabled: true,
      },
    },
  ],```

**Comment by qurfy** [comment]
Is `AWS EventBridge Scheduler` feature fully supported? when I use `method: scheduler`, I get `Resource handler returned message: "Invalid request provided: The execution role you provide must allow AWS EventBridge Scheduler to assume the role.` Error when I run `sls deploy`

**Comment by Tsingis** [comment]
Yup this is not good and idea at all.
