### ISSUE TITLE
Upgrade Custom Resource functions to use Node.js 18

### ISSUE THREAD

**Issue by michalf-kainos** [serverless/serverless#12133]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Node.js 16 is going out of support (security support ends on 11 Sep 2023).

The Lambda function for custom resources have nodejs16 runtime hardcoded: https://github.com/serverless/serverless/blob/d0e3056b77ba295adb87ceeca9a49a26b315f083/lib/plugins/aws/custom-resources/index.js#L165-L179

In multiple projects Lambda functions using unsupported nodejs version would be highlighted as security risk.

### Proposed solution (optional)

Update customResourceFunction.runtime to `nodejs18.x `

**Comment by doblinger-extron** [comment]
Relates to https://github.com/serverless/serverless/issues/12116

**Comment by ptitkosmos** [comment]
I suggest to retrieve the runtime provide by the user in the serverless template : 
```
provider:
  runtime: nodejs18.x
```

**Comment by mikeprimm** [comment]
Just got notices from AWS on end-of-support for node 16 runtime - end of standard support is 11 Mar 2024 (deprecated support ending 11 Apr 2024).  I'd suggest move fixed value to nodejs 20.x (or use the runtime from the provider->runtime setting, as suggested by @ptitkosmos ).

**Comment by janik6n** [comment]
Also relates to issue #12265

**Comment by gavinjohnson-crowdcube** [comment]
"Starting August 15, 2024, you will no longer be able to update existing functions using the Node.js 16 runtime." is the killer.  So in 8 months in cases where the custom resources are used, unless something is changed then serverless framework will simply fail.  You'll no longer be able to deploy. 😨 

Seriously thinking it's time to migrate away. 🤔

**Comment by NickMainAtPI** [comment]
Is there any hope of a fix for this issue being merged? Or should my team spend our time before August 15th migrating our lambda infrastructure to another solution?...

**Comment by Mmarzex** [comment]
Hi everyone, sorry we've been slow to respond here. This change will be available in the Serverless v4 beta that will be releasing within the next week.

**Comment by sarangpatel** [comment]
@Mmarzex I hope next week. For time any hacky solution please provide?

**Comment by noumanbhatti** [comment]
does somebody found any hack to this ?

**Comment by ofek-kenbi** [comment]
@noumanbhatti @sarangpatel
I have a very ugly hack but at least it's working.
Patch the "node_modules/serverless/lib/plugins/aws/custom-resources/generate-zip.js" file using something like [patch-package](https://www.npmjs.com/package/patch-package).
The edited file:
```
'use strict';

/* This files patches serverless generate-zip.js to include aws-sdk in the custom-resources lambda
   This is to resolve issue where aws-sdk is not included in node.js runtime >= 18.x
   This is a temporary fix until serverless framework fix this issue:
   https://github.com/serverless/serverless/issues/12133 */
const path = require('path');
const fse = require('fs-extra');
const getTmpDirPath = require('../../../utils/fs/get-tmp-dir-path');
const createZipFile = require('../../../utils/fs/create-zip-file');
const ensureArtifact = require('../../../utils/ensure-artifact');
const safeMoveFile = require('../../../utils/fs/safe-move-file');
const childProcess = require('child_process');
const util = require('util');

const exec = util.promisify(childProcess.exec);

const srcDirPath = path.join(__dirname, 'resources');

const artifactName = 'custom-resources-patched.zip';

module.exports = async () => {
  const resultPath = await ensureArtifact(artifactName, async (cachePath) => {
    const tmpDirPath = getTmpDirPath();
    const tmpInstalledLambdaPath = path.resolve(tmpDirPath, 'resource-lambda');
    const tmpZipFilePath = path.resolve(tmpDirPath, 'resource-lambda.zip');
    const cachedZipFilePath = path.resolve(cachePath, artifactName);
    await fse.copy(srcDirPath, tmpInstalledLambdaPath);
    console.log("Patching custom-resource lambda....");
    await fse.writeJSON(path.join(tmpInstalledLambdaPath, 'package.json'), { name: "custom-resources", dependencies: { "aws-sdk": "2.1553.0" } });
    await exec('npm install', { cwd: tmpInstalledLambdaPath });
    await createZipFile(tmpInstalledLambdaPath, tmpZipFilePath);
    await safeMoveFile(tmpZipFilePath, cachedZipFilePath);
  });
  return path.resolve(resultPath, artifactName);
};
```

The edited script will install aws-sdk before creating the custom-resources lambda zip file.
Then you will have aws-sdk as part of your lambda.

**Comment by gupta-abhi26** [comment]
Hey @Mmarzex, any updates on the release ?

**Comment by smiley717** [comment]
> Hi everyone, sorry we've been slow to respond here. This change will be available in the Serverless v4 beta that will be releasing within the next week.

When is the ETA of this? June is not so far away from now.

**Comment by bitsofinfo** [comment]
This won't be backported into 3.x? Concerned having to force move to a new major (especially a beta SLS) version will bring more risk rather than just having SLS 3.x patched for this change...

**Comment by gavinjohnson-crowdcube** [comment]
v4 alpha looks to be out now https://github.com/serverless/serverless/tree/v4.0

**Comment by gavinjohnson-crowdcube** [comment]
Looks like the custom resource upgrade to node20.x is in it as well https://github.com/serverless/serverless/commit/bd8cef3ff6d34d3b14cb8f667553eef13e075a99

**Comment by MatthiasBoehm87** [comment]
Is there any chance that this will be backported into 3.x? There isn't much time left until AWS will deny a lambda update completely, and then we won't be able to deploy our projects anymore.

**Comment by NickMainAtPI** [comment]
Any updates on this, especially considering the lack of full V4 rollout at this point?

**Comment by metafounder** [comment]
I am also interested in updates on this.

**Comment by pd-alex** [comment]
It would be great to hear an update on this.
The AWS cut-off date is approaching.

**Comment by wesyoung** [comment]
this seems to work:

- add `- lambda-update-deprecated-runtime` to your plugin section in `serverless.yml`
- mkdir `.serverless_plugins` add the js below to `.serverless_plugins/lambda-update-deprecated-runtime.js`
- run `sls package` and `vi .serverless/cloudformation-template-update-stack.json` to verify you see node20 in the right place:

```
"Handler": "api-gateway-cloud-watch-role/handler.handler",
        "MemorySize": 1024,
        "Runtime": "nodejs20.x",
        "Timeout": 180,
       ...
```

ref: https://serverlesscode.com/post/customizing-serverless-with-plugins/

(i rlz the general guidance right now is a little wonky, hth... ty for those that have supplied examples thus far!)

```
'use strict';

class LambdaUpdateDeprecatedRuntime {

  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;
    this.provider = 'aws';

    this.hooks = {
      'before:package:finalize': this.afterCompileEvents.bind(this),
    };
  }
  afterCompileEvents() {
    let key = 'CustomDashresourceDashapigwDashcwDashroleLambdaFunction'
    let resources = this.serverless.service.provider.compiledCloudFormationTemplate.Resources;
    if (key in resources && resources[key].Properties.Runtime == 'nodejs16.x') {
      this.serverless.cli.log("Fixed CustomDashresourceDashexistingDashs3LambdaFunction runtime from `nodejs16.x` to `nodejs20.x`");
      resources[key].Properties.Runtime = 'nodejs20.x'
    }
  }
}

module.exports = LambdaUpdateDeprecatedRuntime;

```

**Comment by jonasduever** [comment]
Thanks @wesyoung! But that would mean that [this](https://github.com/serverless/serverless/pull/12146#issuecomment-1716183178) is not true? (Would surprise me to be honest.)

> However we can't just increment the runtime version. These custom resource handlers use aws-sdk v2 which is not bundled with node18 lambda functions. In order to change this, you'd need to update the custom resource handlers to use v3 of the AWS SDK.

**Comment by wesyoung** [comment]
> Thanks @wesyoung! But that would mean that [this](https://github.com/serverless/serverless/pull/12146#issuecomment-1716183178) is not true? (Would surprise me to be honest.)
> 
> > However we can't just increment the runtime version. These custom resource handlers use aws-sdk v2 which is not bundled with node18 lambda functions. In order to change this, you'd need to update the custom resource handlers to use v3 of the AWS SDK.

maybe- it makes the error (notice) go away for stacks that are already created. i'll guess i'll have to destroy and rebuild a stack to test (?)

**Comment by wesyoung** [comment]
> > Thanks @wesyoung! But that would mean that [this](https://github.com/serverless/serverless/pull/12146#issuecomment-1716183178) is not true? (Would surprise me to be honest.)
> > > However we can't just increment the runtime version. These custom resource handlers use aws-sdk v2 which is not bundled with node18 lambda functions. In order to change this, you'd need to update the custom resource handlers to use v3 of the AWS SDK.
> 
> maybe- it makes the error (notice) go away for stacks that are already created. i'll guess i'll have to destroy and rebuild a stack to test (?)

@jonasduever i think you're right, you can deploy the change to get rid of the notice, but if you try to delete and then re-create that part of the stack (the logs section), CF hangs for a good 30-40min and then fails, which highlights your point i think. guess we're stuck... 

(gofundme donation to serverless ? it's hard running a biz on opensource sometimes... :))

**Comment by xoapit** [comment]
It should be fixed by https://github.com/serverless/serverless/pull/12146 but the maintainer did not review and merge it :(

**Comment by bradwood** [comment]
:yawning_face:

**Comment by ac360** [comment]
We just released the beta of Framework v4 which contains updating the custom resources runtimes. Looking into the work involved in maintaining this for V3. We're watching the AWS deadline.

**Comment by bradwood** [comment]
It does indeed have "connotations".  Note this also:

![image](https://github.com/serverless/serverless/assets/3472045/8b9d00a5-aebd-415e-aeeb-a66fb8337cf5)

**Comment by jeffrey1226** [comment]
> @noumanbhatti @sarangpatel I have a very ugly hack but at least it's working. Patch the "node_modules/serverless/lib/plugins/aws/custom-resources/generate-zip.js" file using something like [patch-package](https://www.npmjs.com/package/patch-package). The edited file:
> 
> ```
> 'use strict';
> 
> /* This files patches serverless generate-zip.js to include aws-sdk in the custom-resources lambda
>    This is to resolve issue where aws-sdk is not included in node.js runtime >= 18.x
>    This is a temporary fix until serverless framework fix this issue:
>    https://github.com/serverless/serverless/issues/12133 */
> const path = require('path');
> const fse = require('fs-extra');
> const getTmpDirPath = require('../../../utils/fs/get-tmp-dir-path');
> const createZipFile = require('../../../utils/fs/create-zip-file');
> const ensureArtifact = require('../../../utils/ensure-artifact');
> const safeMoveFile = require('../../../utils/fs/safe-move-file');
> const childProcess = require('child_process');
> const util = require('util');
> 
> const exec = util.promisify(childProcess.exec);
> 
> const srcDirPath = path.join(__dirname, 'resources');
> 
> const artifactName = 'custom-resources-patched.zip';
> 
> module.exports = async () => {
>   const resultPath = await ensureArtifact(artifactName, async (cachePath) => {
>     const tmpDirPath = getTmpDirPath();
>     const tmpInstalledLambdaPath = path.resolve(tmpDirPath, 'resource-lambda');
>     const tmpZipFilePath = path.resolve(tmpDirPath, 'resource-lambda.zip');
>     const cachedZipFilePath = path.resolve(cachePath, artifactName);
>     await fse.copy(srcDirPath, tmpInstalledLambdaPath);
>     console.log("Patching custom-resource lambda....");
>     await fse.writeJSON(path.join(tmpInstalledLambdaPath, 'package.json'), { name: "custom-resources", dependencies: { "aws-sdk": "2.1553.0" } });
>     await exec('npm install', { cwd: tmpInstalledLambdaPath });
>     await createZipFile(tmpInstalledLambdaPath, tmpZipFilePath);
>     await safeMoveFile(tmpZipFilePath, cachedZipFilePath);
>   });
>   return path.resolve(resultPath, artifactName);
> };
> ```
> 
> You will also need to patch the serverless/lib/plugins/aws/custom-resources/index.js file and update the version to 18/20.

@ofek-kenbi 

Thank you. You saved me.

**Comment by austencollins** [comment]
Our commitment to maintaining V3 for critical security and bug fixes through 2024 stands. We'll upgrade this next week.

**Comment by austencollins** [comment]
This is in progress..

**Comment by Mmarzex** [comment]
Hi everyone, thank you for your patience, this is now supported in a new v3 release, specifically [v3.39.0](https://www.npmjs.com/package/serverless/v/3.39.0), it is available on NPM now.

**Comment by smiley717** [comment]
Outstanding news! @Mmarzex

**Comment by abhijeet-toptal** [comment]
any plans to upgrade to node 20+?

**Comment by dls314** [comment]
> any plans to upgrade to node 20+?

@abhijeet-toptal

If you don't depend on serverless framework features that requires custom resources — API gateway logging, s3 buckets as lambda event sources, perhaps others — then the quickest path in serverless framework < 4 is to just use a runtime string like `runtime: nodejs22.x` in your serverless.yml file. The command line will produce warnings (don't use warnings as errors), but your lambda functions will be deployed with the newer runtime version.

If you do depend on something that requires the custom resources, then this comment up thread is probably the easiest method for support - https://github.com/serverless/serverless/issues/12133#issuecomment-2070902296 (thanks to @wesyoung for the post)

**Comment by bradwood** [comment]
@dls314 are you saying that serverless 3 is now no longer being maintained? Just, for the avoidance of doubt?

**Comment by dls314** [comment]
> [@dls314](https://github.com/dls314) are you saying that serverless 3 is now no longer being maintained? Just, for the avoidance of doubt?

I'm not affiliated, just reporting what worked for me.

**Comment by jonasduever** [comment]
> [@dls314](https://github.com/dls314) are you saying that serverless 3 is now no longer being maintained? Just, for the avoidance of doubt?

Yes, v3 is not maintained anymore by the official Serverless team/project.
If you don't want to upgrade to v4, there is a nice drop-in replacement fork, though: https://github.com/oss-serverless/serverless (I hope I'm allowed to post this here. Otherwise, let me know.)
The issue above is _not_ solved there but I bet it will be in time, see https://github.com/oss-serverless/serverless/pull/59#issuecomment-2838177803
