### ISSUE TITLE
Resource with id 'null' has more than one variable component as a direct child: [{price_list}, {price}]

### ISSUE THREAD

**Issue by orasis** [serverless/serverless#1216]
v0.5

Very minor issue, but thought you should be aware.

My use case is that I'd like to do GET requests like so:

GET /{product_id}/0.99,1.99,2.99

and POSTs like so:

POST /{product_id}/1.99

{ viewed: true } 

I'm guessing API Gateway doesn't like having one referred to as GET {product_id}/{price_list} and the other as POST {product_id}/{price} since they collide to the same space.

Ideally this would work as is, but I can work around this by just keeping the variable name the same, but it makes my code a bit less self-explanatory.

Here is my s-function.json endpoints:

  "endpoints": [
    {
      "path": "{product_id}/{price_list}",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": { "integration.request.path.product_id": "method.request.path.product_id",
                              "integration.request.path.price_list": "method.request.path.price_list"},
      "requestTemplates": { "application/json": { "product_id": "$input.params('product_id')",
                                                  "price_list": "$input.params('price_list')"} },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {
            "application/json;charset=UTF-8": "Empty"
          },
          "responseTemplates": {
            "application/json;charset=UTF-8": ""
          }
        }
      }
    },
    {
      "path": "{product_id}/{price}",
      "method": "POST",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": { "integration.request.path.product_id": "method.request.path.product_id",
                              "integration.request.path.price": "method.request.path.price"},
      "requestTemplates": {
        "application/json": {
          "method": "$context.httpMethod",
          "body": "$input.json('$')",
          "product_id": "$input.params('product_id')",
          "price": "$input.params('price')"
        }
      },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {
            "application/json;charset=UTF-8": "Empty"
          },
          "responseTemplates": {
            "application/json;charset=UTF-8": ""
          }
        }
      }
    }

  ],

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
