### ISSUE TITLE
Enhance cli variables list function to list stage scoped variables

### ISSUE THREAD

**Issue by mikelax** [serverless/serverless#1217]
In #873 a PR was created to add support for `sls variables list` by @HyperBrain 
After selecting a stage, the variables are displayed broken down by region. 
I have several variables that are defined at the stage level, ie. in the s-variables-dev.json file as opposed to s-variables-dev-useast1.json.

The values defined in the stage file are not displayed, only the ones defined at the region level. 
This command is really useful, having full support will make it easier to manage variables. 

*NOTE* - There is an option for `--all` but this still only lists variables by region in all stages.

**Comment by HyperBrain** [comment]
I fixed this already and it is committed in the master branch. All 3 levels (project, stage, region) are handled correctly now, even the creation of a variable can specify where to create it, As soon as there is a new bugfix release, the fix will be integrated.
