### ISSUE TITLE
Lambda function does not show api endpoins and event sources

### ISSUE THREAD

**Issue by vkkis93** [serverless/serverless#1221]
Hello everybody,
In my s-function.json I have array of endpoints and events.
When I am  deploying endpoint and events  , I don't see these API endpoints and events sources on lambda  page, but API GATEWAY has endpoints and  CloudWatch has rules (schedule)

How I can solve it ?

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
