### ISSUE TITLE
When packaged individually. serverless state json overwrites package location.

### ISSUE THREAD

**Issue by MichaelBellBOM** [serverless/serverless#12246]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We have a process where we create a deployment artefact.
e.g. `sls package --staging prod --package api-location-prod`
We then store the deployment in our artefact store.
We have a deployment pipeline that will download and deploy the package.
`sls deploy --staging prod --package deploy/artefact`

If the individually is set to false (default) then this will work correctly.
However if individually is set to true.  Then it will overwrite the location for the zip file for packaged function with the `artefact` value from the serverless-state.json.

I get the error `No location_suburbs.zip provided`

So in the `serverless-state.json` we have
```
    "functions": {
      "location_suburbs": {
        "handler": "api_location/location_handler.location_handler",
        "description": "Finds the location from a geohash.",
        "layers": {
          "$ref": "$[\"service\"][\"provider\"][\"compiledCloudFormationTemplate\"][\"Resources\"][\"LocationUnderscoresuburbsLambdaFunction\"][\"Properties\"][\"Layers\"]"
        },
        "role": "LogBasicRole",
        "timeout": 11,
        "memorySize": 1024,
        "package": {
          "patterns": [
            "!*",
            "!*/**",
            "api_location/*",
            "data/suburbs.sqlite",
            "data/wave_coverage.sqlite",
            "data/timezones.sqlite",
            "./*.so*"
          ],
          "artifact": "/home/jenkins/workspace/AusBOM_api-location_main/api-location-prod/location_suburbs.zip"
        },
```
Some debugging shows that the artifact value is overwriting the package value.  And it cannot find "/home/jenkins/workspace/AusBOM_api-location_main/api-location-prod/location_suburbs.zip" which is not where I expect it to be looking for the artifact.

Similar to https://github.com/serverless/serverless/issues/9015 but this is more general and the ticket has not seen any updates in over a year.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls --conceal --stage 'prod' --package deploy/artefact

### Command output

```shell
Deploying api-location to stage prod (ap-southeast-2)



× Stack api-location-prod failed to deploy (0s)

Environment: linux, node 18.17.0, framework 3.35.2 (local), plugin 7.0.3, SDK 4.4.0

Credentials: Local, environment variables

Docs:        docs.serverless.com

Support:     forum.serverless.com

Bugs:        github.com/serverless/serverless/issues



Error:

No location_suburbs.zip file found in the package path you provided.

Error: Command failed with exit code 1

    at ChildProcess.<anonymous> (/home/jenkins/workspace/digital-microService-deploy_main/api-location/node_modules/serverless-bom-composed-vars/bin/sls-composed:21:39)

    at ChildProcess.emit (node:events:514:28)

    at maybeClose (node:internal/child_process:1091:16)

    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

script returned exit code 1
```

### Environment information

```shell
Framework Core: 3.35.2 (local)
Plugin: 7.0.3
SDK: 4.4.0
```

**Comment by czubocha** [comment]
Hey @MichaelBellBOM, thanks for reporting this. It should now be resolved in [v4.4.17](https://github.com/serverless/serverless/releases/tag/v4.4.17). Feel free to reach out if you encounter any further issues.
