### ISSUE TITLE
On stack creation, check CF API rather than IAM var

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1224]
currently we're checking the IAM var to detect whether the stack is created before or not, but that doesnt capture the edge case where the stack is deleted from the AWS console.

As an enhancement we should check the CF API to see whether the stack actually exists or not. This will make the promise chain a bit complex, we could figure away around it.

**Comment by pmuens** [comment]
Resolved with https://github.com/serverless/serverless/pull/1411
