### ISSUE TITLE
Please Add il-central-1 to Serverless deploy

### ISSUE THREAD

**Issue by asamprabin** [serverless/serverless#12240]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Warning: Invalid configuration encountered
  at 'provider.region': must be equal to one of the allowed values [us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-iso-east-1, us-iso-west-1, us-isob-east-1, us-west-1, us-west-2, af-south-1, ap-east-1, 
ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ap-southeast-3, ap-southeast-4, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-central-2, eu-north-1, eu-south-1, eu-south-2, eu-west-1, eu-west-2, eu-west-3, me-central-1, me-south-1, sa-east-1]

Learn more about configuration validation here: http://slss.io/configuration-validation

### Proposed solution (optional)

Please Add il-central-1 to Serverless deploy

**Comment by Mmarzex** [comment]
@asamprabin `il-central-1` has been available since version `3.35.0`. Please upgrade to that version or later.
