### ISSUE TITLE
Only a single s3 event can be added per bucket/s-function.json

### ISSUE THREAD

**Issue by tvalletta** [serverless/serverless#1225]
On serverless v0.5.5 running on node v4.2.3

When I define an event of type s3, it works. If I define multiple events on the same bucket within the s-function.json file, only the last one is added. There are no errors in the console.

e.g. This works: (subset of s-function.json)
```json
...
"events": [{
  "name": "imageEvent",
  "type": "s3",
  "config": {
    "bucket": "com.domain.dev",
    "bucketEvents": [ "s3:ObjectCreated:*" ],
    "filterRules": [{
      "name": "prefix",
      "value": "folder/subfolder/image-folder"
    }]
  }  
}]
...
```

e.g. This does not work. Only the last event is created: (subset of s-function.json)
```json
...
"events": [{
  "name": "imageEvent",
  "type": "s3",
  "config": {
    "bucket": "com.domain.dev",
    "bucketEvents": [ "s3:ObjectCreated:*" ],
    "filterRules": [{
      "name": "prefix",
      "value": "folder/subfolder/image-folder"
    }]
  }  
}, {
  "name": "pdfEvent",
  "type": "s3",
  "config": {
    "bucket": "com.domain.dev",
    "bucketEvents": [ "s3:ObjectCreated:*" ],
    "filterRules": [{
      "name": "prefix",
      "value": "folder/subfolder/pdf-folder"
    }]
  }  
}]
...
```

I expected to have two events created, but only the last one exists. If I deploy the first one, it will overwrite the second, but I cannot get both.

**Comment by lukas-gitl** [comment]
I'd be very interested in a solution for this as well.

**Comment by flomotlik** [comment]
This is resolved in V1
