### ISSUE TITLE
Support for nodejs20 runtime

### ISSUE THREAD

**Issue by jrestrepo-azimut** [serverless/serverless#12259]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS released support for nodejs20 runtime for Lambda Functions. However, Serverless v3.36.0 (latest stable version) doesn't support creation of Lambda Functions with that runtime. 

### Proposed solution (optional)

Add support for nodejs20

**Comment by Mmarzex** [comment]
Node20 is supported in framework version 3.37
