### ISSUE TITLE
Indeterminate bash shell state when running function having multiple stages

### ISSUE THREAD

**Issue by jedatu** [serverless/serverless#1226]
### Runtime Environment
- Apple MacBook Pro with Yosemite 10.10.5 
- Serverless 0.5.5
- Node v6.2.0

### Expectation vs. Actual
Expect to run `sls function run` and return to a stable command line.  However, when running a function where two "stages" are present, the shell is in an indeterminate state.  The text is not visible when typing into the shell, but pressing `enter` executes the command.  Simply pressing `enter` will present the command prompt on the same line in the console.
![image](https://cloud.githubusercontent.com/assets/171668/15732968/6854d860-284f-11e6-944d-b5af1b641e87.png)

### Steps to Reproduce
1. `sls project create -c true` (name it sample)
2. `cd sample`
3. `sls function create test`
4. `sls stage create -c true` (name it test)
5. `sls function run test` (choose the dev or test stage and press `enter`)
6. After test has run, press `enter` to observe that the shell is in an indeterminate state
7. Type `reset` and press `enter` to restore the shell

### Possible Workaround
- Pass the region and stage to the command `sls function run -r us-east-1 -s dev`  
- Wrap the command like so `>>>(sls function run)`.

### Gitter Discussion
- https://gitter.im/serverless/serverless?at=574f5750a78d5a256e3a0d9d

**Comment by erikerikson** [comment]
As per submitter, this does not reproduce if stage is provided as an argument to the command

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
