### ISSUE TITLE
What Are the Most Important Modules That Are Needed?

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#123]
I know you guys worked on a basic users module, but how about a small list of modules that are essential to build the JAWS ecosystem? what's the highest priority functionality do you think is needed at this point?

Maybe create a markdown file with that list, and have the community PR their ideas of the lambdas modules they'd like to have?

**Comment by ac360** [comment]
Let's get it going in this Issue.  In the next few days, I'll move it to [a wish list located here](https://github.com/awsm-org).

Below are themes.  People are going to want various expressions of these themes (this one uses SES, this one uses Mailchimp).  But, imagine a world where all of this stuff is already written in aws-modules ready for lambda deployment(!!!)

* **Users/Sessions CRUD** - Bonus if you include sign on via popular 3rd party services (e.g., Github)
* **Analytics/Event Functions** - Captures common user events
* **Image functions** - Resize, filters, etc.
* **Twilio functions** - Send SMS
* **Email - Transactional** email functions (e.g., receipt, welcome, where you been?)
* **Email - Marketing** - Blasting html emails to many addresses for dirt cheap via Lambda + SES
* **Stripe Webhook Handlers**
• **Slack Webhook handlers**
* **Webhook handlers for all the things** 
* **3rd Party Authentication Handlers** - Pre-built authentication with the most popular peeps.

**Comment by eahefnawy** [comment]
Awesome! that should be enough to get the ball rolling! But I thought we already have Users/Sessions CRUD?!

**Comment by ac360** [comment]
I have to rewrite it slightly for aws-module format.  But it's one of those aws-modules that will implemented several ways.  Of interest, is doing it with AWS Cognito too.  We're making one change to the aws-module dir structure today, after that, we should be good to get going.

**Comment by eahefnawy** [comment]
oh I see! it seems that AWSM is a completely separate entity from JAWS. So I'm guessing the whole jaws.json format will be replaced with awsm.json? Or in other words, I should follow the structure provided in the AWSM repo, is that correct?

**Comment by ac360** [comment]
@eahefnawy Yes, JAWS projects will have a jaws.json in their root folders, but all aws-moodules will have awsm.jsons in their modules.  The dir structure in the AWSM repo will change slightly today, but I don't think it will affect your development at all.

Also, adding another list item to my list above.

**Comment by ac360** [comment]
@eahefnawy Ok, we're done with the module structure:  https://github.com/awsm-org/awsm

**Comment by eahefnawy** [comment]
woooo! Awesome! looking into it!

**Comment by eahefnawy** [comment]
haha I like the hand gesture in the logo

**Comment by ac360** [comment]
@eahefnawy Thanks!  We're currently building [an aws-module that provides essential JAWS utilities](https://github.com/jaws-framework/jaws-core-js) which will be the first example.  It's a bitt different since it doesn't actually have any lambda functions or endpoints, it consists only of code meant to be shared across other aws-modules in a JAWS project.

**Comment by DoWhileGeek** [comment]
+1 Stripe webhooks

**Comment by eahefnawy** [comment]
interesting, I was just about to ask how env vars should be handled in aws modules! Should I expect that the env vars that are needed for the module will be provided by the developer? I think the JAWS framework has a way to handle that, right?

Also, what about node modules? according to AWS Lambda docs, the node modules folder should be in the root directory of the lambda. However, since a lot of the AWS modules will have multiple lambdas that probably share the same node modules, maybe it should be in the lib directory instead?

I'm currently working on twilio awsm cause it seemed the easiest to start experimenting with, and I faced both of these questions. I'll get to Stripe next once I wrap my head around it.

**Comment by ac360** [comment]
@eahefnawy Put environment variables that your awsm expects in the "lambda" properties in awsm.json files.  You can see [an example here](https://github.com/awsm-org/awsm/blob/master/awsm.json).  It's up to the user to set those.  But that is where you specify which ENVs your awsm needs.

In the [awsm README's Structure section](https://github.com/awsm-org/awsm#structure) you can see that the node_modules should be at the awsm's root.  When your lambda function is packaged, it recreates the aws_module structure, with your lambda in a subfolder (just like the module is).  We recommend putting your node_modules in the awsm root and not the lib folder.  Node/NPM knows to look up a few parent directories to fetch node_modules so this will work best.

Twilio is going to be so sweet!
