### ISSUE TITLE
add default stage and region config

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1232]
We regularly need to pass stage and region params in our CLI commands which makes them longer and tedious to type. We should have a default stage and region set in the config to make those params optional.

**Comment by pmuens** [comment]
Yep good idea! After tinkering around on the console I agree with you that commands should be as short as possible!

**Comment by pmuens** [comment]
Is also discussed in https://github.com/serverless/serverless/issues/1328

**Comment by pmuens** [comment]
Already implemented in the current system.

Will be even more accessible once https://github.com/serverless/serverless/pull/1834 is merged.
