### ISSUE TITLE
recursive creation of _tmp on Windows during sls dash deploy

### ISSUE THREAD

**Issue by hakenmt** [serverless/serverless#1235]
I'm running version 0.5.5 on Windows 10 1511 with node.js version 5.6.0.

Say I have a folder structure like
```
ProjectRoot
|--s-templates.json
|-- _meta
|-- functions
    |--s-templates.json
    |--MyFunction1
        |--handler.js
        |--s-function.json
        |--s-templates.json
```

In the s-function.json file, my handler is defined as 
```
"handler" : "functions/MyFunction1/handler.handler"
```
so that it includes the functions parent folder.

When I run `sls dash deploy`, the _tmp folder in _meta gets recursively added to each function folder placed in the top level tmp. If the handler is just defined as "handler.handler" then it only includes the MyFunction1 folder, and everything works.

**Comment by piohhmy** [comment]
+1 Seeing this too...

**Comment by SimpleSimonC** [comment]
I'm also having this problem

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
