### ISSUE TITLE
 Deployment Failure with Python 3.12.2

### ISSUE THREAD

**Issue by dtosato** [serverless/serverless#12393]
### What version of Serverless Framework are you using?

Environment: linux, node 20.11.1, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.3, SDK 4.5.1

### Issue description / feedback

Hello,

I'm trying to deploy a Serverless application with the command `sls deploy --stage dev`, but I'm encountering an error. Here's the output:

```sh
Running "serverless" from node_modules
Learn more about configuration validation here: http://slss.io/configuration-validation
Deploying app to stage dev ([MASKED])
× Stack app failed to deploy (5s)
Error: `python3.12 -m pip install -t /root/.cache/serverless-python-requirements/7ab86e80d83d47528eb312bf591c1034c163c43ce6971064e081c2c91ef62537_x86_64_slspyc -r /root/.cache/serverless-python-requirements/7ab86e80d83d47528eb312bf591c1034c163c43ce6971064e081c2c91ef62537_x86_64_slspyc/requirements.txt --cache-dir /root/.cache/serverless-python-requirements/downloadCacheslspyc` Exited with code 1
    at ChildProcess.<anonymous> (/builds/app/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

Any help resolving these issues would be greatly appreciated.

**Comment by dtosato** [comment]
Hello, is serverless still alive?

**Comment by ac360** [comment]
Hi @dtosato the AWS Lambda `python3.12` runtime is available only in Serverless Framework V4, which you can find here:

https://github.com/serverless/serverless/tree/v4.0
