### ISSUE TITLE
Integrate with AWS Cloudformation Change Sets

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1242]
Change sets provide a user with the ability to see all differences a specific deployment would do to their Cloudformation stack. This is important for local development and debugging, but also for detailing steps in the Continuous delivery pipeline where it needs to happen as a batch operation.

**Comment by flomotlik** [comment]
Imho nice to have feature in the future, never heard a user say they want it therefore closing

**Comment by satoshun00** [comment]
Imho this is cool feature if `serverless deploy --noDeploy` shows change-set result.

Usecase:

- For CI workflow, I can mark test as failure if a change-set reports `FAILED` status
- I can prevent unexpected down-time caused by resource deletion

**Comment by kgriffiths** [comment]
This would be a great feature to have
