### ISSUE TITLE
Getting error with Serverless Deploy in Github Action

### ISSUE THREAD

**Issue by emon-gain** [serverless/serverless#12459]
### Issue description

I am facing error when i try to deploy my serverless lambda function into aws with github action i am getting an unknown error. I am using aws sdk v3 packages in my code. Here is the error

Deploying stripe-payment to stage local (eu-west-1)
Bundling with Webpack...
ERROR in ../../@aws-sdk/credential-provider-ini/dist-es/resolveAssumeRoleCredentials.js 18:48-77
Module not found: Error: Can't resolve '@aws-sdk/client-sts' in '/home/runner/work/Backend.Service.Payment/Backend.Service.Payment/node_modules/@aws-sdk/credential-provider-ini/dist-es'
 @ ../../@aws-sdk/credential-provider-ini/dist-es/resolveProfileData.js 2:0-99 [12](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:13):8-27 13:15-43
 @ ../../@aws-sdk/credential-provider-ini/dist-es/fromIni.js 2:0-58 6:11-29
 @ ../../@aws-sdk/credential-provider-ini/dist-es/index.js 1:0-26 1:0-26
 @ ../../@aws-sdk/credential-provider-node/dist-es/defaultProvider.js
 @ ../../@aws-sdk/credential-provider-node/dist-es/index.js 1:0-34 1:0-34
 @ ../../@aws-sdk/client-ses/dist-es/runtimeConfig.js 3:0-97 28:72-97
 @ ../../@aws-sdk/client-ses/dist-es/SESClient.js [13](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:14):0-73 18:26-44
 @ ../../@aws-sdk/client-ses/dist-es/index.js 1:0-28 1:0-28
 @ ../../../src/service/sendEmail.js 2:0-66 4:19-28 26:22-38
 @ ../../../src/service/webhook.service.js 4:0-63 63:25-46 68:10-19 92:23-44 97:8-17 109:23-44 113:8-17 138:23-44 [14](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:15)2:8-17
 @ ../../../src/webhook/webhook.js 4:0-116 23:12-22 28:19-35 32:19-37 36:19-39
 @ ../../../src/index.js 4:0-50 65:25-38

ERROR in ../../@aws-sdk/credential-provider-web-identity/dist-es/fromWebToken.js 6:63-92
Module not found: Error: Can't resolve '@aws-sdk/client-sts' in '/home/runner/work/Backend.Service.Payment/Backend.Service.Payment/node_modules/@aws-sdk/credential-provider-web-identity/dist-es'
 @ ../../@aws-sdk/credential-provider-web-identity/dist-es/index.js 2:0-31 2:0-31
 @ ../../@aws-sdk/credential-provider-node/dist-es/defaultProvider.js
 @ ../../@aws-sdk/credential-provider-node/dist-es/index.js 1:0-34 1:0-34
 @ ../../@aws-sdk/client-ses/dist-es/runtimeConfig.js 3:0-97 28:72-97
 @ ../../@aws-sdk/client-ses/dist-es/SESClient.js 13:0-73 18:26-44
 @ ../../@aws-sdk/client-ses/dist-es/index.js 1:0-28 1:0-28
 @ ../../../src/service/sendEmail.js 2:0-66 4:19-28 26:22-38
 @ ../../../src/service/webhook.service.js 4:0-63 63:25-46 68:10-19 92:23-44 97:8-17 109:23-44 113:8-17 138:23-44 142:8-17
 @ ../../../src/webhook/webhook.js 4:0-116 23:12-22 28:19-35 32:19-37 36:19-39
 @ ../../../src/index.js 4:0-50 65:25-38

ERROR in ../../@aws-sdk/token-providers/dist-es/getNewSsoOidcToken.js 3:41-75
Module not found: Error: Can't resolve '@aws-sdk/client-sso-oidc' in '/home/runner/work/Backend.Service.Payment/Backend.Service.Payment/node_modules/@aws-sdk/token-providers/dist-es'
 @ ../../@aws-sdk/token-providers/dist-es/fromSso.js 4:0-58 56:38-56
 @ ../../@aws-sdk/token-providers/dist-es/index.js 1:0-26 1:0-26
 @ ../../@aws-sdk/credential-provider-sso/dist-es/resolveSSOCredentials.js 1:0-74 10:33-52
 @ ../../@aws-sdk/credential-provider-sso/dist-es/fromSSO.js 4:0-64 34:[15](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:16)-36 50:15-36
 @ ../../@aws-sdk/credential-provider-sso/dist-es/index.js 1:0-26 1:0-26
 @ ../../@aws-sdk/credential-provider-node/dist-es/defaultProvider.js
 @ ../../@aws-sdk/credential-provider-node/dist-es/index.js 1:0-34 1:0-34
 @ ../../@aws-sdk/client-ses/dist-es/runtimeConfig.js 3:0-97 28:72-97
 @ ../../@aws-sdk/client-ses/dist-es/SESClient.js 13:0-73 18:26-44
 @ ../../@aws-sdk/client-ses/dist-es/index.js 1:0-28 1:0-28
 @ ../../../src/service/sendEmail.js 2:0-66 4:19-28 26:22-38
 @ ../../../src/service/webhook.service.js 4:0-63 63:25-46 68:10-19 92:23-44 97:8-17 109:23-44 113:8-17 138:23-44 142:8-17
 @ ../../../src/webhook/webhook.js 4:0-1[16](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:17) 23:12-22 28:19-35 32:19-37 36:19-39
 @ ../../../src/index.js 4:0-50 65:25-38

× Stack stripe-payment-local failed to deploy (7s)
Environment: linux, node 18.20.2, framework 3.38.0, plugin 7.2.3, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

ERROR in ../../@aws-sdk/token-providers/dist-es/getSsoOidcClient.js 3:36-70
Module not found: Error: Can't resolve '@aws-sdk/client-sso-oidc' in '/home/runner/work/Backend.Service.Payment/Backend.Service.Payment/node_modules/@aws-sdk/token-providers/dist-es'
 @ ../../@aws-sdk/token-providers/dist-es/getNewSsoOidcToken.js 1:0-54 4:32-48
 @ ../../@aws-sdk/token-providers/dist-es/fromSso.js 4:0-58 56:38-56
 @ ../../@aws-sdk/token-providers/dist-es/index.js 1:0-26 1:0-26
 @ ../../@aws-sdk/credential-provider-sso/dist-es/resolveSSOCredentials.js 1:0-74 10:33-52
 @ ../../@aws-sdk/credential-provider-sso/dist-es/fromSSO.js 4:0-64 34:15-36 50:15-36
 @ ../../@aws-sdk/credential-provider-sso/dist-es/index.js 1:0-26 1:0-26
 @ ../../@aws-sdk/credential-provider-node/dist-es/defaultProvider.js
 @ ../../@aws-sdk/credential-provider-node/dist-es/index.js 1:0-34 1:0-34
 @ ../../@aws-sdk/client-ses/dist-es/runtimeConfig.js 3:0-97 28:72-97
 @ ../../@aws-sdk/client-ses/dist-es/SESClient.js 13:0-73 18:26-44
 @ ../../@aws-sdk/client-ses/dist-es/index.js 1:0-28 1:0-28
 @ ../../../src/service/sendEmail.js 2:0-66 4:19-28 26:22-38
 @ ../../../src/service/webhook.service.js 4:0-63 63:25-46 68:10-19 92:23-44 97:8-[17](https://github.com/GainHQ/Backend.Service.Payment/actions/runs/8921184696/job/24500759485#step:8:18) 109:23-44 113:8-17 138:23-44 142:8-17
 @ ../../../src/webhook/webhook.js 4:0-116 23:12-22 28:19-35 32:19-37 36:19-39
 @ ../../../src/index.js 4:0-50 65:25-38

webpack compiled with 4 errors
Error:
Webpack compilation error, see stats above
Error: Process completed with exit code 1.

### Context

N/A

**Comment by BG687** [comment]
I am also getting a similar error when building - this started yesterday: 

`node_modules/@aws-sdk/token-providers/dist-cjs/index.js:50:79: ERROR: Could not resolve "@aws-sdk/client-sso-oidc"`

**Comment by ryanbell1997** [comment]
I'm getting a similar-ish problem, suddenly my GHA is failing as it cannot find /serverless-iam-roles-per-function. This has been working fine for me the whole time, I have 
```
plugins:
  - serverless-iam-roles-per-function

```
At the top of my serverless.yml and I've added a special build step to ensure it's installed...
Not sure if they're connected, but seems suss.

**Comment by emon-gain** [comment]
I have fixed it with installing aws sdk client sts and client oidc. I had to install it manually to resolve this.
