### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1247]
In this epic we're collecting tasks for improved Python Support in V1

- [x] Make Packaging mechanism more generic and move it into a separate plugin to support Java (see https://github.com/serverless/serverless/pull/1494)
- [x] Add a way to create template for different languages, runtimes and tools through `serverless create` (see https://github.com/serverless/serverless/pull/1536 and https://github.com/serverless/serverless/pull/1537)
- [x] Create template for Python
- [x] Create documentation outlining Python Support and how to set it up

**Comment by pmuens** [comment]
Done with #1554

**Comment by godd9170** [comment]
@flomotlik where can I find the documentation outlining the python support?

I'm looking to take all the `site packages` within my virtualenv and ensure they're included at the root of the zip file that gets deployed.

**Comment by flomotlik** [comment]
@godd9170 There isn't really anything in particular to Python support in Serverless. You can create a new Service from a Python Template, but after that you just build a normal Lambda function, we'll package it and upload.

What is currently not obvious is that you need to install your pip dependencies in the same folder as your service, so they get properly packaged. We definitely want to put that as an example into the template at some point.

**Comment by godd9170** [comment]
Exactly @flomotlik thanks.

What I've done in the meantime is create a separate `virtualenv` for each of my services and maintain a `requirements.txt` file as I build it. Similar to a `package.json` & `node_modules` relationship I suppose.

The `virtualenv` actually lives inside the service directory and I'm able to use it's `site-packages` in my zipped lambda functions by ensuring that the following is included first thing in my `handler.py` header:

```
import sys
sys.path.insert(0, './venv/lib/python2.7/site-packages/')
```

The obvious ugliness with this is that the entire `virtualenv` gets zipped into the service when all I really need are those site packages. What would be awesome is if they were copied out into the root of the service directory and the rest was ignored on deployment. Then I wouldn't need to alter my python path and all the useless v`virtualenv` baggage would be omitted. Thoughts?

**Comment by flomotlik** [comment]
Couldn't you use include/exclude for that, e.g. exclude the whole virtualenv and only include the site-packages subfolder?

**Comment by flomotlik** [comment]
https://github.com/serverless/serverless/blob/master/docs/01-guide/10-packaging.md

**Comment by godd9170** [comment]
@flomotlik ah! thanks for that bit of docs. I couldn't figure out how to get that working, and it's zipping like a charm now. Anyone who is curious here's what mine looks like:

```
package:
  include:
    - venv/lib/python2.7/site-packages
  exclude:
    - venv
```

**Comment by alexef** [comment]
@godd9170 should this be part of the documentation?

**Comment by godd9170** [comment]
@alexef I don't think so. It's pretty hacky being that I have to modify the python path.

**Comment by jong-eatsa** [comment]
+1 waiting for official support and tutorial in Python

**Comment by flomotlik** [comment]
Python is already supported and there is a template for a python service in
the create plugin.


On 11 November 2016 at 23:22:35, Jong Kim (notifications@github.com) wrote:

+1 waiting for official support and tutorial in Python

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/serverless/serverless/issues/1247#issuecomment-260069458>,
or mute the thread
