### ISSUE TITLE
Serverless Does Not Authenticate (Inconsistent Errors, related v4 / latest npm package)

### ISSUE THREAD

**Issue by isikhi** [serverless/serverless#12495]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

As you can see when I try to login with serverless v4.x, this error happened.. When i switch to v3.x there is no error with same command and same credentials. I set issue description latest v3 release but I am using v4 because of npm package look like latest. If it(v4.x) is latest not i guess there is misversioning about latest tag on npm repo.

### Service configuration (serverless.yml) content

```yaml
N/A
(you can assume just basic crud app)
```

### Command name and used flags

sls config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY

### Command output

```shell
$ sls config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
✖ Not authenticated
Error: Not authenticated
    at PlatformEventClient.publishEventBatches (file:///root/.serverless/releases/4.0.21/package/dist/sf-core.js:22:21257)
    at file:///root/.serverless/releases/4.0.21/package/dist/sf-core.js:9[91](https://gitlab.com/vivosens/it/ml/sip/vivoo-urine-test/-/jobs/6904804479#L91):2062
    at async route (file:///root/.serverless/releases/4.0.21/package/dist/sf-core.js:991:1497)
    at async Object.run2 [as run] (file:///root/.serverless/releases/4.0.21/package/dist/sf-core.js:991:5209)
    at async Object.handler (file:///root/.serverless/releases/4.0.21/package/dist/sf-core.js:991:8150)
For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
  ```
```


### Environment information

```shell
4.0.21
```

**Comment by Mmarzex** [comment]
Hi @isikhi . In v4 we no longer have the config command. Instead you can manage all of that using the `serverless` command and it will take you through configuring your credentials.

**Comment by isikhi** [comment]
Oh okay. I didn't noticed it. Thanks closing the issue.

**Comment by j-fulbright** [comment]
Been cool if v4 wasn't stealth released today.

**Comment by Mmarzex** [comment]
@j-fulbright We released the v4 beta today. You are still able to use past versions if you need by setting the version in your package.json

**Comment by Rhaal** [comment]
I understand the need for a company to make revenue, if it wants to stay afloat, but:
  1. You performed a stealth release of a software part of many toolchains
  2. This change requires, for many companies, moving to a paid subscription - which will require a sign-off on a budget of some sort

What would you think if Node.js required a paid subscription for companies building CLI tools? Exactly.

Therefore, please convey my utmost disesteem to whomever thought this way of release would solidify the image of Serverless, Inc. as a solid business partner.

Source:
![image](https://github.com/serverless/serverless/assets/35896/00e0f926-9099-4f76-b4f5-ced3531c4c2c)
