### ISSUE TITLE
Serverless cannot use role configured in `~/.aws/config

### ISSUE THREAD

**Issue by AntonOellerer** [serverless/serverless#12491]
### Issue description

I wrote a serverless function which is deployed during CI/CD by a gitlab runner.
We have a custom role for deploying which is configured in ~/.aws/config`, and the runner can assume it based on its EC2 instance:
```
[profile staging]
role_arn = arn:aws:iam::xxx:role/yyy
credential_source = Ec2InstanceMetadata
```

When I try to deploy the function, specifying `--aws-profile=staging`, I get the following error

```
after:package:createDeploymentArtifacts
× Stack zzz failed to deploy (8s)
Environment: linux, node 20.13.1, framework 3.38.0 (local), plugin 7.2.3, SDK 4.5.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
AWS profile "staging" doesn't seem to be configured
```
Is there any way for serverless to use the profile configured in `~/.aws/config`?

### Context

```
Framework Core: 3.38.0 (local) 3.38.0 (global)
Plugin: 7.2.3
SDK: 4.5.1
```

**Comment by Mmarzex** [comment]
Hi @AntonOellerer , We just released the beta of framework v4, which has revamped how we handle AWS credentials so now your configuration will work if you upgrade to v4.

**Comment by AntonOellerer** [comment]
Thank you very much, those are great news!
