### ISSUE TITLE
V4 in CI is requesting a login

### ISSUE THREAD

**Issue by kpconnell** [serverless/serverless#12504]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

npm install -g serverless causes sls deploy to request login. 

### Service configuration (serverless.yml) content

```yaml
x
```

### Command name and used flags

x

### Command output

```shell
x
```

### Environment information

```shell
x
```

**Comment by Mmarzex** [comment]
@kpconnell framework v4 now requires login, you will need to sign in to use it.

**Comment by kpconnell** [comment]
in a CI?  I looked through the documentation about how to do that and there
is multiple document redirects,  zero information.   This is a nonstarter.
We'll use 3.x as long as we can and then switch to something else.

**Comment by Mmarzex** [comment]
@kpconnell you have to provision an access key or license key and set it as an environment variable, check the [upgrade doc](https://serverless.com/framework/docs-guides-upgrading-v4) for more information.

**Comment by kpconnell** [comment]
"Serverless Framework Version 4 seeks to avoid breaking changes and
disruptions for existing Services using the aws provider. Our commitment is
to provide a stable and consistent framework, as we have strived to do for
almost a decade."

LOL

**Comment by FunctionalWorm** [comment]
I appreciate this is a small team and needs to survive. This does look like a breaking change to me though.
Perhaps a warning in the CLI first before introducing a breaking change would have made the transition smooth.

**Comment by Dan-Wood** [comment]
> @kpconnell you have to provision an access key or license key and set it as an environment variable, check the [upgrade doc](https://serverless.com/framework/docs-guides-upgrading-v4) for more information.

Why would someone already using serverless 4 look at an upgrade doc to see that they need a license key all of a sudden?

**Comment by richard-stafflink** [comment]
I had too add this at the start of our CI script, but it's a pain for just using the CLI:
```bash
export SERVERLESS_ACCESS_KEY="___ACCESS_KEY_REDACTED_____"
```

**Comment by garethmcc** [comment]
Hi folks. More information about authenticating whether in a headless or non-headless environment can be found in the docs here: https://www.serverless.com/framework/docs/guides/upgrading-v4

**Comment by ac360** [comment]
> I appreciate this is a small team and needs to survive. This does look like a breaking change to me though.
Perhaps a warning in the CLI first before introducing a breaking change would have made the transition smooth. 

Thanks for the suggestion. We'll add more in the docs on this.

Otherwise, to continue using V3 in automated deployments, specify a version in the global install:

```
npm install -g serverless@3.38.0
```

**Comment by MikeDabrowski-EQM** [comment]
> Otherwise, to continue using V3 in automated deployments, specify a version in the global install:
> 
> ```
> npm install -g serverless@3.38.0
> ```

And then here https://github.com/serverless/serverless/issues/6230#issuecomment-2124470445 

Installing 3.38.0 pulls in other v4 packages. For some 3.38.0 helps for others (us included) it does not work at all.

@ac360 How can we stay on v3 and not have to sign in?

**Comment by thetumper** [comment]
Is there no concern from the team that these changes in v4 will alienate long-time proponents of the Serverless Framework?  Please consider that among many peers, there is still the attitude that "Serverless is niche"..."why don't you use SAM, directly from AWS"?  This doesn't help bolster my arguments about the advantages of Serverless....   :(

**Comment by j-fulbright** [comment]
v4 was announced long ago with these changes, but the stealth release with no warning/no docs or "on this day, we will release it", is pretty terrible.  If this was any other software that did this, it would be immediately added to roadmap to move away from it (and we actually are).

**Comment by richard-stafflink** [comment]
Ditto @j-fulbright, We added a TODO to remove serverless, after this less-than-ideal developer experience too

**Comment by mcat-ee** [comment]
This is really disappointing and is going to impact me advocating the use of the framework - this means to distribute my OSS projects based on Serverless i'd need to include 'sign up for a product just to deploy the project'.

I'll keep my eyes peeled for a login-less fork or a suitable alternative (I don't really want to migrate to pure CloudFormation but again, this is a blocker in me being able to distribute self-hostable projects with minimal friction)

**Comment by keaeriksson** [comment]
While I think it does make sense to require a key to enable Serverless monitoring, CI/CD and secrets offering, I don't think it makes sense to require it for simply deploying a project using the CLI. A change like this will mean we will be looking at alternatives like CDK to deploy our projects.
