### ISSUE TITLE
V4 - No LICENCE file

### ISSUE THREAD

**Issue by richard-stafflink** [serverless/serverless#12507]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

There is no LICENCE file, no copyright, .... Is this project open domain now?

Everyone using these sources will need to know how it will affect their App.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by ac360** [comment]
The original license will be restored shortly.

**Comment by ac360** [comment]
https://github.com/serverless/serverless/commit/16e3ca1b369440b384f76ff4926bf6b23a6abc0c
