### ISSUE TITLE
V4 - Ignores Serverless Framework version installed local and always uses globally installed version

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#12519]
### Issue description

If I have Serverless Framework V.4 installed globally and install Serverless Framework local to a service using "npm install --save-dev serverless@3", when I run "serverless --version" it always references Serverless Framework V.4 and never executes the locally pinned version.

### Context

N/A

**Comment by garethmcc** [comment]
No. The local version was detected automatically.

**Comment by garethmcc** [comment]
Here is a loom to demonstrate it more clearly: https://www.loom.com/share/7e69d7615e6140f0aaa5f47d8975a0f2?sid=693d5cbd-1d47-4169-baf9-71f632ee950c

**Comment by Mmarzex** [comment]
This is resolved now. New installs will include the fix for this. For users experiencing this issue, they just need to run a `serverless update` to get the new version.
