### ISSUE TITLE
V4 - Improve warning/behavior if users are using the wrong Node.js version

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#12516]
### Issue description

We're still seeing a lot of the wrong Node.js version used with V4. We need to better inform users about this, and especially in CI/CD environments

### Context

n/a

**Comment by Mmarzex** [comment]
Updated to not allow running on versions that are lower than Node version 18. Can be verified using a fresh install or running a `serverless update` and then trying to run a command using an older Node version.
