### ISSUE TITLE
Improve CI/CD process support in Serverless

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1251]

**Comment by johncmckim** [comment]
Can you share any plans for this? Two of the difficulties I have found are the metadata sync and co-ordination of the `resources`, `function`, `event` and `endpoint` commands. 

If you're new to serverless, missing metadata can easily catch you out. The serverless-meta-sync plugin works well, but there's no reference to it in the docs.

It would be nice if there was a single `project deploy` command that would co-ordinate a full deployment and rollback on failure. It would be even better if it was possible to deploy a new production environment and update a DNS record (or use weighted DNS) to bring users over to the new version.

**Comment by flomotlik** [comment]
Regarding Metadata: I don't like the meta folder and want to work on providing an env.serverless.yml that you can commit into your repo that has either no secrets and we do a separate secrets file or you have encrypted secrets in there.

Another idea for secrets management is to store them in a DynamoDB encrypted through KMS and only store an ID in the env file so when the lambda launches we get the keys for your stage and region from Dynamo, decrypt them with KMS and use the right keys. This way nothing secret is stored in your repo or can be accessed during the build process.

Regarding Deployment: We switched to Cloudformation on the v1.0 branch and reimplemented the deploy step completely. As its all one CF stack now this makes it much easier to deploy and manage your operations. You can even add your own CF resources that we will deploy with all the CF Resources we create for you automatically. Much cleaner and easier to remove.

**Comment by johncmckim** [comment]
@flomotlik deployment all in CloudFormation sounds really good.

I like the ideas for Metadata too. I do really like how Travis and Appveyor have secure variables in YAML. I think it's a reasonably common scenario to have multiple AWS accounts (Prod, Test, Dev). How would the KMS setup work in this situation?

**Comment by jthomerson** [comment]
@flomotlik can we get a little more information on the v1 CF changes? Do you mean that functions, end points, and events all get merged with my s-resources.json and deployed as on formation?

**Comment by flomotlik** [comment]
@jthomerson we're going to release more info very very soon, here you can get a view of the new docs: http://v1.docs.serverless.com

And yes all resources necessary in a stack (custom resources and resources we need to create for your functions) will be deployed as one Cloudformation stack. We've removed the s-resources.json file and its all in one config file now (although you can split this up easily in any way you want to)
