### ISSUE TITLE
Build is breaking with 4.0.23

### ISSUE THREAD

**Issue by ntripathi1995** [serverless/serverless#12512]
### Issue description

<img width="1436" alt="Screenshot 2024-05-22 at 4 01 05 PM" src="https://github.com/serverless/serverless/assets/138026695/3f6ae0f5-f489-44a6-9c5b-0172abb6116a">
Build is breaking after release 4.0.23

### Context

4.0.23

**Comment by Mmarzex** [comment]
Hi @ntripathi1995 that error is most likely because your pipeline is using an outdated node version. I'd recommend upgrading it to the most recent LTS which is node20
