### ISSUE TITLE
V4 - Ignores frameworkVersion property set in serverless.yml file

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#12518]
### Issue description

If you attempt to deploy with v4 installed and your serverless.yml happens to contain the frameworkVersion property set to a version less than 4, deployment continues regardless. A simplified config below demonstrates the property that is ignored.

### Context

service: new-service
org: yourorg
app: yourapp
frameworkVersion: '3'

**Comment by ac360** [comment]
Let's do this after variable resolution, in the beginning of the Framework runner.

**Comment by ac360** [comment]
Fixed in https://github.com/serverless/serverless/releases/tag/v4.0.30
