### ISSUE TITLE
Confusing v4 messages after v3 deploy

### ISSUE THREAD

**Issue by slootjes** [serverless/serverless#12526]
### Issue description

After doing a deploy, I now get this message in v3.38.0:

> This service is safe to upgrade to a v4 Serverless Framework release
> Run "npm install serverless@^4.0.24" to upgrade
> Check: https://github.com/serverless/serverless/releases/tag/v4.0.0 for list of all breaking changes

Several confusions from my end:
- No indication that v4 is currently beta
- The link to the v4.0.0 tag is broken
- Safe to upgrade, does this guarantee it doesn't break then? How sure can it be about this?

### Context

Running "serverless" from node_modules
Framework Core: 3.38.0 (local) 3.38.0 (global)
Plugin: 7.2.3
SDK: 4.5.1

**Comment by ac360** [comment]
Thanks for the heads up on this. We'll fix that shortly.

**Comment by ac360** [comment]
We've removed all confusing messages
