### ISSUE TITLE
The latest release broke install.sh on v3

### ISSUE THREAD

**Issue by arsham-f** [serverless/serverless#12522]
### Issue description

`install.sh` on v3: https://github.com/serverless/serverless/blob/v3/scripts/pkg/install.sh

By default, it will detect the latest version on line 62:

```
TAG=`curl -L --silent https://api.github.com/repos/serverless/serverless/releases/latest 2>&1 | grep 'tag_name' | grep -oE "v[0-9]+\.[0-9]+\.[0-9]+"`
```

The regex expects the latest version number to start with a `v`. However the release that was just posted (https://github.com/serverless/serverless/releases/tag/4.0.24) does not have the `v` prefix. So this script is crashing.

### Context

N/A

**Comment by ac360** [comment]
Thanks @arsham-f. We're removing the release to fix that script, ensuring it only points to v3 release and not v4 releases,

**Comment by ac360** [comment]
This fixed the issue temporarily. Fixing the script next to avoid this in the future and unblock Github releases

**Comment by arsham-f** [comment]
Thank you. Confirmed it's working now.
