### ISSUE TITLE
V4 how to login in a non-interactive way?

### ISSUE THREAD

**Issue by skhaz** [serverless/serverless#12534]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have the command "serverless deploy" in my CI/CD pipeline.

I have upgraded to version 4, and now it requires login, which is a bummer.

I tried to log in, but it's interactive! This totally breaks CI/CD automation.

Please fix this, or I won't be able to use it anymore.

```
Run serverless deploy

(node:16[8](https://github.com/chatbotfacil/serverless/actions/runs/9220235145/job/25366832683#step:6:9)4) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

✖ You must sign in or use a license key with Serverless Framework V.4 and later versions. Please use "serverless login".
```

### Proposed solution (optional)

Implement a token-based authentication using environment variables that is seamless to use, or else I believe you will lose users.

Large companies use CloudFormation directly.

**Comment by LorenzoRogai** [comment]
@skhaz https://www.serverless.com/framework/docs/guides/upgrading-v4

<img width="938" alt="image" src="https://github.com/serverless/serverless/assets/1665768/b821e1f8-2ffd-4cf7-b857-7de9666d3072">

**Comment by ac360** [comment]
This is documented in the upgrading guide.

**Comment by Jimbolino** [comment]
> Your shouldn't need to login before deploying when using an access key.

Thnx, this was the problem :)

First i read this:
```
You must sign in or use a license key with Serverless Framework V.4 and later versions. Please use "serverless login".
```
So i added the `serverless login` (because i dont have a license key)


Then i read:
```
You can authenticate via Access Key by signing in to Serverless Framework Dashboard when prompted by the CLI or running serverless login. [...] create a new Access Key for CI/CD use, and save it as the SERVERLESS_ACCESS_KEY environment variable in your CI/CD pipeline.
```

So i added the `SERVERLESS_ACCESS_KEY`, but didn't realize the `serverless login` is for interactive login ONLY, and either an access key OR license key can be used with the `serverless deploy` command

---

Now i'm stuck at the following:
```
Error: Resolver provider bref is not supported
```
For now i think its best for me to lock to v3: https://github.com/brefphp/bref/issues/1815

**Comment by austencollins** [comment]
@Jimbolino It looks like the original issue was fixed, and now the second issue you reported here regarding the `provider` is also fixed as of [this release](https://github.com/serverless/serverless/releases/tag/v4.0.35)

**Comment by Lavkush3411** [comment]
I faced similar issue when setting up ci/cd using github serverless and aws lambda, but adding env variable SERVERLESS_ACCESS_KEY to the workflow file along with aws credentials resolved the issue.

`      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS access key ID
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS secret access key
          AWS_REGION: ${{ secrets.AWS_REGION }} # AWS region, e.g., us-east-1
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          serverless deploy  # Run the Serverless deploy command`
