### ISSUE TITLE
Sort plugins by name when running serverless --help

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1257]

**Comment by svdgraaf** [comment]
I had some time to burn, made a PR, I see the build failed because of timeout, can someone restart it? :)

**Comment by pmuens** [comment]
Awesome @svdgraaf! You totally rock 🎸 !

Will restart the build. Thanks for that 🎉

**Comment by pmuens** [comment]
Will be done with https://github.com/serverless/serverless/pull/1768
