### ISSUE TITLE
Serverless command "offline" not found

### ISSUE THREAD

**Issue by krisalay** [serverless/serverless#12578]
### Issue description

I am getting the error:
Environment: linux, node 20.14.0, framework 3.39.0 (local), plugin 7.2.3, SDK 4.5.1
Docs: [docs.serverless.com](http://docs.serverless.com)
Support: [forum.serverless.com](http://forum.serverless.com)
Bugs: [github.com/serverless/serverless/issues](http://github.com/serverless/serverless/issues)

Error:
Serverless command "offline" not found. Run "serverless help" for a list of all available commands.

### Context

I am using

```
"serverless": "^3.39.0",
"serverless-dotenv-plugin": "^6.0.0",
"serverless-esbuild": "^1.52.1",
"serverless-offline": "^13.6.0",
```

**Comment by NicoHinderling** [comment]
@austencollins would maintenance of https://github.com/dherault/serverless-offline ever be taken over or at least have direct support by the serverless company itself?

I've finally completed my experimental migration project (serverless3 -> 4 & npm -> pnpm) and the only two blocking things left are:
1. local handlers not working for serverless4 (https://github.com/serverless/serverless/issues/12621) 🙏
2. serverless-offline not working for serverless4 (https://github.com/dherault/serverless-offline/issues/1800)

Seems like they are looking for maintainers and I imagine that supporting offline functionality is pretty important for other developers too

**Comment by eahefnawy** [comment]
@NicoHinderling Have you tried using the new `serverless dev` command for local development? If you did, I'm curious to know what serverless-offline solves that dev mode doesn't 🤔 (other than actually being offline with no internet connection)

**Comment by NicoHinderling** [comment]
> @NicoHinderling Have you tried using the new `serverless dev` command for local development? If you did, I'm curious to know what serverless-offline solves that dev mode doesn't 🤔 (other than actually being offline with no internet connection)

I just tried it out and I agree that `serverless dev` does seem like it would speed up iterative development when using "dev", but:
1. Right now I share our dev environment with several other engineers, so I don't want to use dev directly all the time. Being able to use it offline is really convenient for this.
2. I actually dealt with an outage recently where I control + C'd a deploy to our biggest service's dev environment and it totally broke our cloudformation. I had to delete everything and re-create it from the ground up, so particularly for that service, I'd probably not bother using `serverless dev` altogether given how fragile it apparently is

**Comment by eahefnawy** [comment]
@NicoHinderling Thanks for that feedback! That's really helpful.

You could also do `sls dev --stage local` or `sls dev --stage nico`, wouldn't that solve both issues?

**Comment by NicoHinderling** [comment]
> @NicoHinderling Thanks for that feedback! That's really helpful.
> 
> You could also do `sls dev --stage local` or `sls dev --stage nico`, wouldn't that solve both issues?

these still involve deploying, which also increases our number of resources for that service. We've been hitting the limit recently, but I agree that could be a potential alternative for others

**Comment by eahefnawy** [comment]
Hmm yeah, that is a good point 🤔

**Comment by DorianMazur** [comment]
@krisalay Can you check with serverless-offline v14?
