### ISSUE TITLE
Serverless V4 deployment Error

### ISSUE THREAD

**Issue by vyshnavitblr13** [serverless/serverless#12577]
### Issue description

When using the command in gitlabci.yml `sls prune -n 3 --stage staging --debug` , I am facing the following error

`Option “stage” is of type “undefined” but expected type “string”.
ServerlessError3: Option “stage” is of type “undefined” but expected type “string”.`

**Comment by czubocha** [comment]
Hello @vyshnavitblr13. Thank you for reporting this issue. We have identified the problem and will include the fix in the next release.

**Comment by vyshnavitblr13** [comment]
The issue seems fixed. Thank you!
