### ISSUE TITLE
Documentation is not updated about the v3

### ISSUE THREAD

**Issue by LorenzoRogai** [serverless/serverless#12582]
### Issue description

https://www.serverless.com/framework/docs/guides/upgrading-v4 states "Serverless Framework V.3 will continue to be maintained via critical security and bug fixes through 2024"

However this is not being reflected in actual changes. There are many security issues/bug fixes (breaking) still open (with also PRs ready to be merged already created by contributors)

Example:

https://github.com/serverless/serverless/issues/12482
https://github.com/serverless/serverless/issues/12481
https://github.com/serverless/serverless/issues/12422
https://github.com/serverless/serverless/issues/12434
https://github.com/serverless/serverless/issues/12442

Could you please review the situation or update the documentation to reflect the actual expectations?

Thank you

**Comment by austencollins** [comment]
We have a major release for V.4 scheduled this week. We'll begin patching afterward.
