### ISSUE TITLE
Menu Overlap Issue in Documentation

### ISSUE THREAD

**Issue by erados** [serverless/serverless#12596]
### Issue description

When you expand the documentation menu, part of the code snippets from the documentation rise above the menu, obscuring it.

![Screenshot_20240614_040524_Chrome](https://github.com/serverless/serverless/assets/19205043/d208eb82-8989-460e-b29b-d35ee3d4a21e)
![Screenshot_20240614_040527_Chrome](https://github.com/serverless/serverless/assets/19205043/76fbde97-e363-4f24-a02f-88e57939f6cb)

### Context

I am using Chrome on Samsung S22+, Android.

**Comment by austencollins** [comment]
Thanks for reporting. We have a better docs experience coming shortly. We'll look into this in the interim.

**Comment by austencollins** [comment]
Should be fixed
