### ISSUE TITLE
Define conventions / best practices for Plugin development

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1259]
Plugins should have a convention to follow (e.g. `FooBar` for the classname). Furthermore we should provide a best practices guide to make it easier for devs to develop plugins.

**Comment by flomotlik** [comment]
@pmuens do you think the current plugin docs cover this?

**Comment by pmuens** [comment]
Yes. Also stumbled upon this one today. I think that the current docs cover this and we might want to add more details about some conventions in our https://github.com/serverless/community-plugins repository.

**Comment by flomotlik** [comment]
Ok then I'll close here for now. We'll add more docs in the community repo, but that should be in those issues.
