### ISSUE TITLE
Cannot parse 'serverless.ts' after upgrading to v4

### ISSUE THREAD

**Issue by vastamaki** [serverless/serverless#12604]
### Issue description

After updating to version 4, it appears that esbuild no longer includes my helper functions and other functions declared in a separate file. This issue has arisen with a new project, and upon reviewing the source code, it seems there is no way to provide an esbuild configuration for building the serverless.ts file, which I believe would resolve the problem.

The specific error message is as follows:
`Could not read the config file at path '/REDACTED/serverless.ts' due to this error: Cannot parse 'serverless.ts': Build error: Cannot find package 'functions/index' imported from /REDACTED/.serverless/serverless.js.`

### Context

N/A

**Comment by austencollins** [comment]
Thanks for reporting @vastamaki. We're looking into this.

**Comment by garethmcc** [comment]
@vastamaki You can just run any serverless command such as `serverless --version` and the new version should be auto-installed

**Comment by austencollins** [comment]
@vastamaki The Framework will auto-update. The npm module only contains the installer/updater, but we have fixed it so the npm version still syncs w/ Framework verssion.

**Comment by czubocha** [comment]
Closing as fixed in [v4.1.5](https://github.com/serverless/serverless/releases/tag/v4.1.5)
