### ISSUE TITLE
V4.1.0: Error fetching release: EACCES: permission denied, open /usr/local/lib/node_modules/serverless/node_modules/.bin/serverless-darwin-amd64-0.0.2

### ISSUE THREAD

**Issue by lawiet47** [serverless/serverless#12608]
### Issue description

The serverless configuration errors out in our production with : `Error fetching release: EACCES: permission denied, open '/usr/local/lib/node_modules/serverless/node_modules/.bin/serverless-darwin-amd64-0.0.2'`. After running the sudo npm install -g serverless command, everytime a serverless command is executed, it has returned this error. I had to ping the serverless version to `@3.38.0` to make the error go away. 

### Context

I can't even run serverless support because of the error I described above. I am using the `serverless@4.1.0`, `node@v16.18.0` and `npm@8.19.2`

**Comment by austencollins** [comment]
Thanks for reporting @lawiet47. We're looking into this. Can you try again with Node.js version 18 or greater?

**Comment by lawiet47** [comment]
I tried with `node@18.12.0`. Now I am receiving `Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/serverless/node_modules/.bin'`

**Comment by Mmarzex** [comment]
Hi @lawiet47 Looking at the issue it is most likely because you attempted to use sudo with npm install. In general you should never do that. I'd recommend running `npm install -g` or using a package.json in your project directory with `serverless` as a dev command.
