### ISSUE TITLE
Visualize plugin lifecycles

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1260]
It would be great to have a command to visualize the order in which all the plugins run (to see which plugins hook into which other plugin hooks) and their respective lifecycle events.

This makes debugging / developing plugins way easier.

@dougmoscrop was already kind enough to start an implementation in #2821 which can be revived to add this.

Especially interesting is the discussion which started recently [here](https://github.com/serverless/serverless/pull/2821#issuecomment-303668731)

**Comment by dougmoscrop** [comment]
Depending on what you're looking for, my PR might help with this: https://github.com/serverless/serverless/pull/2133/files#diff-1a6cb15a7aef359bf1fabed7982e4af3R17

The hooks object could be map/reduced to display the info.

Could you give a sample output you'd like to see? I could add it to that PR.

**Comment by flomotlik** [comment]
Putting this into 1.3 and hoping for somebody to pick this up. Should be pretty straight forward

**Comment by pmuens** [comment]
Reopening this one since it would be an essential feature for plugin developers.

See the recent discussion in the PR from @dougmoscrop [here](https://github.com/serverless/serverless/pull/2821#issuecomment-303668731) for more info about the feature.

**Comment by HyperBrain** [comment]
For now I created a lifecycle cheat sheet that shows the current lifecycle events in order for all Serverless commands. https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406

**Comment by pmuens** [comment]
Thanks for creating and sharing that @HyperBrain 💯 👍

**Comment by pmuens** [comment]
Closing this since it's a stale issue and @HyperBrain made a great cheat-sheet for this. Furthermore adding the `Debug` flag also enables this.
