### ISSUE TITLE
Missing Package @serverlessinc/sf-core

### ISSUE THREAD

**Issue by Anubhav-Chauhan3367** [serverless/serverless#12607]
#### Description

Hi,

I encountered an issue while trying to install dependencies. The `@serverlessinc/sf-core` package is not found in the npm registry, leading to an error during `npm install`.

#### Error Message

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverlessinc%2fsf-core - Not found
npm ERR! 404
npm ERR! 404 '@serverlessinc/sf-core@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

#### Steps to Reproduce

1. Fork the repository
2. Run `npm install`

#### Additional Information

The package `@serverlessinc/sf-core` is referenced in multiple files, indicating its importance to the codebase. Can you provide guidance on where to find this package or if it's available in a different branch? Any help or instructions would be greatly appreciated.

Thank you!

---

Here's a summary of the affected files:

- `commands/plugin-install.js`
- `commands/plugin-uninstall.js`
- `lib/aws/request.js`
- `lib/classes/cli.js`
- `lib/classes/config-schema-handler/index.js`
- `lib/classes/config-schema-handler/resolve-ajv-validate.js`
- `lib/classes/plugin-manager.js`
- `lib/classes/service.js`
- `lib/cli/render-help/command.js`
- `lib/cli/render-help/general.js`
- `lib/cli/render-help/generate-command-usage.js`
- `lib/cli/render-help/options.js`
- `lib/cli/write-service-outputs.js`
- `lib/plugins/aws/custom-resources/index.js`
- `lib/plugins/aws/deploy-list.js`

Thanks again for your assistance!

Best regards,
Anubhav Chauhan

**Comment by austencollins** [comment]
Hi @Anubhav-Chauhan3367 it looks like you are trying to install via the repo, rather than NPM. Please install the NPM module instead via `npm i serverless -g`

**Comment by rohendra** [comment]
@austencollins I want to get the latest code in main branch as it addresses issue #12799 faced my me.

How do I install directly from repo if the required changes are not yet published to npm registry?

**Comment by alexw23** [comment]
Trying to develop the package and getting this error. How does one contribute to this package as you need to call `npm install`?
