### ISSUE TITLE
V4: Default deploymentMethod 'direct' or 'changesets' 

### ISSUE THREAD

**Issue by gsavvidis96** [serverless/serverless#12629]
### Issue description

In [Serverless.yml Reference docs](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml) it states 

> Method used for CloudFormation deployments: 'changesets' or 'direct'. Optional. (default: changesets)

While in [Deploying to AWS docs](https://www.serverless.com/framework/docs/providers/aws/guide/deploying#deployment-method) it states

> Direct deployments are faster and have no downsides (unless you specifically use the generated change sets). They will become the default in Serverless Framework 4.

So is `deploymentMethod: direct` needed when using serverless v4, or is default?

**Comment by skierkowski** [comment]
@gsavvidis96 Thanks for reporting and sorry for the confusion. I'll get clarification on this and get the docs updated soon.

**Comment by Mmarzex** [comment]
@gsavvidis96 Sorry for the confusion here, we did indeed mean to change this to `direct`. This has been merged on our end and will be released in the next few days.
