### ISSUE TITLE
[v4] Unable to use basic cli functionality like help without aws credentials

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12630]
### Issue description

When trying to use basic cli functionality like help without aws credentials I get and error:
```
npx sls --help                


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers
```

### Context

Serverless Framework Version: 4.1.5
Service Path: /Users/kamil/work/Phoenix
Service Config File: serverless.yml
Service Name: phoenix
Service Runtime: nodejs20.x
Service Stage: staging
Service Region: eu-west-1
Command: --help

**Comment by kdybicz** [comment]
Hey @austencollins! Got your point, though... one might argue that seeing this issue when you want to get some `--help` because you're having problems, that's probably not a great user experience 😅

**Comment by kdybicz** [comment]
I had a similar issue when my AWS env was set up but the SSO token was expired, I could not view `--help` as I use `ssm:` in my `serverless.yml`.

**Comment by DorianMazur** [comment]
Related to https://github.com/dherault/serverless-offline/issues/1800

**Comment by czubocha** [comment]
Closing this issue as AWS Credentials are no longer required unless needed by commands, plugins, or Serverless Framework Variables.
