### ISSUE TITLE
ESBuild plugin support (Serverless 4)

### ISSUE THREAD

**Issue by tombarton** [serverless/serverless#12654]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

We're currently in the process of migrating to SLS 4 and deprecating our use of the serverless-esbuild plugin. This decision is mainly driven by our desire to utilize the revamped "dev" mode, which doesn't appear to work with the serverless-esbuild plugin (I can raise a separate issue around this if required). However, we currently rely on two features of the serverless-esbuild plugin that aren't supported natively in SLS 4:

1. Plugins

We currently use an ESBuild plugin to upload our source maps to [Sentry](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/esbuild/) as part of our production deployments. We could investigate migrating to using the Sentry CLI to upload our sourcemaps, but since this functionality is already provided, it doesn't seem worth the risk.

2. `packagerOptions`

We currently use packager options to install various packages with specific architectures. This is more of a nice-to-have feature, as we can achieve a similar result by utilizing Lambda layers.

--

Are there any plans to support ESBuild plugins in SLS 4?

**Comment by eahefnawy** [comment]
@tombarton I added support for esbuild plugins in PR https://github.com/serverless/serverless/pull/12662 and it will be included in the next release 🚀

**Comment by tombarton** [comment]
Amazing, thanks @eahefnawy 🔥

**Comment by eahefnawy** [comment]
@tombarton This is now released in [v4.1.12](https://github.com/serverless/serverless/releases/tag/v4.1.12)
