### ISSUE TITLE
Unable to Disable esbuild in Serverless 4.1.11

### ISSUE THREAD

**Issue by angela83** [serverless/serverless#12672]
### Issue description

``I want to deploy my application using serverless-plugin-typescript
I tried disabling ESBuild by including the following in serverless.yml 

`build:
  esbuild:
    bundle: false`

however I still get the error to disable it when I try to deploy

`Serverless now includes ESBuild and supports Typescript out-of-the-box. But this conflicts with the plugin 'serverless-plugin-typescript'.
You can either remove this plugin and try Serverless's ESBuild support builtin, or you can set 'build.esbuild' to false in your 'serverless.yml'.`

Is there another way to disable ESBuild to be able to use serverless-plugin-typescript?

Thanks

### Context

# Service Overview
- Serverless Framework Version: 4.1.11
- Service Config File: serverless.yml
- Service Name: api
- Service Runtime: nodejs16.x
- Service Stage: production
- Service Region: eu-west-1
- Command: deploy --stage production
- Error Code: PLUGIN_TYPESCRIPT_CONFLICT

## Error Stacktrace
```
at PluginManager.addPlugin (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:854:65)
at file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:854:1435
at Array.forEach (<anonymous>)
at PluginManager.loadAllPlugins (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:854:1413)
at async Serverless.init (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:861:9760)
at async runFramework (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:909:880)
at async route (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:920:16046)
at async Object.run2 [as run] (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:920:16444)
at async run3 (file:///C:/Users/xx/.serverless/releases/4.1.11/package/dist/sf-core.js:920:17704)
```

**Comment by Mmarzex** [comment]
@angela83 You can disable esbuild support by setting esbuild to false like so,

```yaml
build:
  esbuild: false
```

Is there a reason you want to continue to use the typescript plugin vs this built in support?

**Comment by angela83** [comment]
I am getting the following error with v4.1.11 and the built in support, that's why I want to test with esbuild disabled instead of reverting to an older version of serverless

`"ENOENT: no such file or directory, open '/var/task/xxx'"`

**Comment by eahefnawy** [comment]
@angela83 we would really appreciate if you could tell us more information on that error because this is clearly a bug. What file/directory is not found? Is that an aws sdk client?

**Comment by angela83** [comment]
@eahefnawy I am deploying an aws api gateway with lambda functions. I do have this bit of code in the serverless.yml file

`package:
  include:
    - src/x.key`

using v4.1.11 with the built in support I was getting the error `"ENOENT: no such file or directory, open '/var/task/x.key'"` when testing as if the file didn't get bundled and pushed.
When I disabled esbuild I started getting this error`EMFILE: too many open files` when attempting to deploy.
In the end I gave up and used a lower version of serverless to be able to deploy without any issues using serverless-plugin-typescript. I had some time constraints to deploy and didn't want to spend more time trying to make 4.1.11 work

**Comment by eahefnawy** [comment]
@angela83 I see. We no longer support `package.include`. Could you try using `patterns` instead? 

https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#package

**Comment by eahefnawy** [comment]
@angela83 I'll be closing this. Feel free to reopen if you still feel there is an issue to resolve.

**Comment by malebolgia** [comment]
> ```yaml
> build:
>   esbuild: false
> ```

In my case it won't compile my handlers typescripts causing issue

✖ Error: Cannot find module 'myhandler'

I need to re-install  ```serverless-plugin-typescript``` .

**Comment by williamavasquez** [comment]
im having a smiliar issue. When I run the `serverless-plugin-typescript` my application runs, but when I move completly to v4 and remove the plugin, I get:

Error: Cannot find module './dynamoDbFunctions'
Require stack:
- /Users/williamvasquez/Development/ooi/dol-ui-ivr-wrapper/src/shared/stopOrphanedTaskFunctions.js
- /Users/williamvasquez/Development/ooi/dol-ui-ivr-wrapper/src/jobs/minutelyJob.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/williamvasquez/Development/ooi/dol-ui-ivr-wrapper/src/shared/stopOrphanedTaskFunctions.js:4:5)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/williamvasquez/Development/ooi/dol-ui-ivr-wrapper/src/shared/stopOrphanedTaskFunctions.js',
    '/Users/williamvasquez/Development/ooi/dol-ui-ivr-wrapper/src/jobs/minutelyJob.js'
    
for context dynamoDbFunctions is a TS file.

**Comment by karmseveeratjisc** [comment]
I'm seeing a possibly related issue, with:

``` 
build:
  esbuild: 
    bundle: false
```

no node_modules are included in the zip file and the package.json is included multiple times:

```
      479  2024-11-20 16:15   package.json
      217  2024-11-20 16:15   handler.js
      426  2024-11-20 16:15   handler.js.map
      479  2024-11-20 16:15   package.json
      224  2024-11-20 16:15   handler2.js
      433  2024-11-20 16:15   handler2.js.map
```
   
   
for this serverless.yml :
```
service: sls4test

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

build:
  esbuild: 
    bundle: false

functions:
  hello:
    handler: handler.hello
  goodbye:
    handler: handler2.goodbye

```


I can force the node_modules in using

```
package:
  patterns:
    - 'node_modules/**'
```
But then that includes **_everything_** in node_modules making the zip too big
