### ISSUE TITLE
Validate existing options centrally so plugins don't have to do it themselves

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1268]
Plugins currently check for specific options themselves which leads to duplicated code in all of them. To make sure going forward this code duplication doesn't happen we'll implement a centralized way to configure and validate the options that users can hand to the cli

**Comment by pmuens** [comment]
Might be related to https://github.com/serverless/serverless/issues/1262

**Comment by flomotlik** [comment]
Duplicate of #1262 , closing
