### ISSUE TITLE
V4 - Version Pinning

### ISSUE THREAD

**Issue by austencollins** [serverless/serverless#12692]
Serverless Framework V.4 ships an installer via NPM and automatically updates its core binary itself, rather than using NPM for version management. Removing the reliance on NPM for version management helps us move the Framework toward a distributable binary, which is easier for non Node.js users. But, we need to re-implement version management/pinning to give users back control over when to update major, minor and patch versions.

We'll do this via the `frameworkVersion` property within `serverless.yml`. It should use standard semver syntax for specifying a specific version, or a range of versions. It will not error if the version is not installed. Instead it will auto-download and use the specified version before the command is run..

**Comment by austencollins** [comment]
ETA this week.

**Comment by NicoHinderling** [comment]
came in handy pretty fast! haha 😆 seems like it's working for `4.1.17` though

**Comment by austencollins** [comment]
We're rolling this out now. It's usable via the `frameworkVersion` property:

```
# serverless.yml

frameworkVersion: '4.1.17'
```

@NicoHinderling Yeah, we're tracking down an [issue](https://github.com/serverless/serverless/issues/12719) in `4.1.18` currently. Fortunately, using this feature, we can disable versions with known issues (e.g. we just did this for `4.1.18`), and install the closest possible working versions.
