### ISSUE TITLE
Installing plugins 

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12700]
### Issue description

Installing Serverless plugins with `serverless plugin install` reformats the whole `package.json` file to a single line.

### Context

# Service Overview
- Serverless Framework Version: 4.1.16
- Service Path: /Users/work/project
- Service Config File: serverless.yml
- Service Name: project
- Service Runtime: nodejs20.x
- Service Stage: development
- Service Region: eu-west-1

## Command
plugin install --name serverless-associate-waf

**Comment by skierkowski** [comment]
@kdybicz I tried to reproduce this issue on a project using the same version, and the `package.json` was updated as expected. Do you have any more details on repro steps?

**Comment by kdybicz** [comment]
not sure if the fact the project is managed with `yarn` makes a difference here 🤔 Besides that not really, I'm able to recreate the problem in 100% cases 🤷🏼

**Comment by kdybicz** [comment]
I'm reproducing it also on this simplified `serverless.yml` with `yarn serverless plugin install --name serverless-associate-waf`:
```
{
  "name": "project",
  "version": "5.0.0",
  "private": true,
  "main": "handler.js",
  "type": "commonjs",
  "engines": {
    "node": ">=20.9"
  },
  "keywords": [],
  "devDependencies": {
    "serverless": "^4.1.15",
    "serverless-associate-waf": "^1.2.1",
    "serverless-domain-manager": "7.3.8",
    "serverless-offline": "^13.6.0",
    "serverless-plugin-canary-deployments": "^0.8.0",
    "serverless-stage-manager": "^1.0.5"
  },
  "packageManager": "yarn@1.22.19+sha1.4ba7fc5c6e704fce2066ecbfb0b0d8976fe62447",
  "overrides": {
    "serverless-associate-waf": {
      "serverless": "$serverless"
    },
    "serverless-domain-manager": {
      "serverless": "$serverless"
    },
    "serverless-plugin-canary-deployments": {
      "serverless": "$serverless"
    },
    "serverless-stage-manager": {
      "serverless": "$serverless"
    },
    "serverless-offline": {
      "serverless": "$serverless"
    }
  }
}
```

**Comment by skierkowski** [comment]
Thanks for the details. I was finally able to reproduce the issue locally, even without using yarn. We'll dig into this some more and update.

**Comment by eahefnawy** [comment]
@kdybicz This is now fixed and released 👌
