### ISSUE TITLE
Documentation links not working correctly

### ISSUE THREAD

**Issue by SampsonM** [serverless/serverless#12702]
### Issue description

In the framework docs there are two issues making learning difficult.

The link to a markdowns GitHub location does not work and shows the following;
`https://github.com/serverless/serverless/edit/main/docs/[object%20Object].md`

And the next page button at the bottom always shows the user a button to the Intro page, not the actual next page.

**Comment by austencollins** [comment]
Thanks @SampsonM We're on it.

**Comment by walidelnozahy** [comment]
@SampsonM Thanks for reporting, these issues have been fixed.
