### ISSUE TITLE
Endoint variable path: Cannot read property 'getFunction' of undefined

### ISSUE THREAD

**Issue by georgepoenaru** [serverless/serverless#1272]
I need a variable endpoint base path for each stage. For this reason I defined a variable in **s-variables-dev.json** So it looks like this:

```
{
  "stage": "dev",
  "basePath":"api/v1"
}
```

Now I create a new default function with a new endpoint and I set the path like this:

```
...
"endpoints": [
    {
      "path": "${basePath}/auth"
...
```

Now I run 

> sls endpoint deploy

And i get this error:

```
Failed to deploy endpoints in "dev" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   GET - api/v1/auth: Cannot read property 'getFunction' of undefined

ServerlessError: Endpoint could not be found: undefined#undefined
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Builder._validateAndPrepare (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:141:45)
    at Builder.build (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:70:20)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:54:22)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

Note, the function it's the default one. No change at all, only the endpoint path is modified.

If I hardcoded the path it does successfully deploy:

```
...
"endpoints": [
    {
      "path": "api/v1/auth"
...
```

Any idea ?

Thank you

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
