### ISSUE TITLE
MFA is not working with sls offline 

### ISSUE THREAD

**Issue by simaqsous** [serverless/serverless#12727]
### Issue description

In my aws account we have MFA enforced for users 
I have full admin policy and I can confirm that I can get the SSM parameters, yet when I run 
```
sls offline start --stage beta --region us-east-1 --reloadHandler
```
I get the following 

```
Cannot resolve serverless.yml: Variables resolution errored with:
samstudio-new:dev:
   - Cannot resolve variable at "custom.accountId": User: arn:aws:iam::XXXX:user/some-user is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:XXXX:parameter/some-parameter with an explicit deny in an identity-based policy,
```

# Service Overview
- Serverless Framework Version: 4.1.19

Above is a summary report of your last Serverless Framework command.

**Comment by czubocha** [comment]
Hi @simaqsous, I noticed this error is coming from Serverless Framework v3. I assume you have v3 installed locally in the project. Could you try removing it and running the project using v4?

**Comment by simaqsous** [comment]
@czubocha Hello, i tried that now I am getting this 
Failed to resolve variable '/XX' with resolver 'ssm' and provider 'aws': AccessDeniedException: User: arn:aws:iam::XX:user/simaqsous is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:XX:parameter/XX with an explicit deny in an identity-based policy (RESOLVER_RESOLVE_VARIABLE_ERROR)

**Comment by czubocha** [comment]
Hey @simaqsous
I looked into this issue, and to make MFA work with the Serverless Framework, you’ll need to follow [the official AWS guidelines](https://repost.aws/knowledge-center/authenticate-mfa-cli) on using an MFA token to authenticate access to AWS resources through the AWS CLI.

In short, you need to get short-term credentials with MFA
```
aws sts get-session-token --serial-number arn-of-the-mfa-device --token-code code-from-token
```
and then export credentials to environment variables
```
export AWS_ACCESS_KEY_ID=example-access-key-as-in-previous-output
export AWS_SECRET_ACCESS_KEY=example-secret-access-key-as-in-previous-output
export AWS_SESSION_TOKEN=example-session-token-as-in-previous-output
```
This is required if you’re using an AWS user directly without assuming any role. The Serverless Framework currently doesn’t support MFA prompts, but [we’re planning to implement](https://github.com/serverless/serverless/issues/12559) the same behavior as the AWS CLI, which asks for an MFA code if you’re assuming a role using an AWS profile, as shown in this `.config` file example:
```
[profile mfa-user]
role_arn=arn:aws:iam::123456789012:role/your-role
credential_source=Environment
mfa_serial=arn:aws:iam::123456789012:mfa/mfa-device
region=eu-west-1
```
Let me know if this solves your problem.

**Comment by simaqsous** [comment]
Thank you, I will keep an eye on this feature
