### ISSUE TITLE
Allow Serverless Dev to work with Apollo Server AWS_PROXY integration.

### ISSUE THREAD

**Issue by Matthewharrisak** [serverless/serverless#12730]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When running `serverless dev` command with Serverless Framework v4 and Apollo Server v4, requests to the Apollo Server result in CORS errors. Notably, this issue does not occur when Apollo Server is deployed, only when running in development mode.

**Steps to Reproduce:**

1. Set up a new project with Serverless Framework v4.
2. Install Apollo Server v4.
3. Configure Apollo Server within the Serverless Framework.
4. Run the `serverless dev` command.
5. Make a request to the Apollo Server endpoint.

**Expected Behavior:**

Requests to Apollo Server should succeed without any CORS errors, both in development mode and when deployed.

**Actual Behavior:**

Requests to the Apollo Server in development mode result in CORS errors. However, when the Apollo Server is deployed, it handles requests without any CORS issues.

**`package.json `Depencies**

```
  "dependencies": {
    "@apollo/datasource-rest": "^6.3.0",
    "@apollo/server": "^4.10.4",
    "@as-integrations/aws-lambda": "^3.1.0",
    "graphql": "^16.9.0",
    "lodash": "^4.17.21"
  },
  "devDependencies": {
    "serverless": "^4.1.6",
    "typescript": "^5.5.2"
  }
```

**Comment by eahefnawy** [comment]
Hi @Matthewharrisak thanks for reporting this. I'll look into it.
