### ISSUE TITLE
AWS Lambda Python 3.9 and above

### ISSUE THREAD

**Issue by sergiogonzalez-momo** [serverless/serverless#12732]
### Issue description

```
s:main: Invoking function locally
s:invokeLocalDocker: Invoking function locally (and 1 more task)
s:invokeLocalDocker: Invoking function locally (and 1 more task)
s:invokeLocalDocker: Invoking function locally (and 1 more task)
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 66B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/lambci/lambda:python3.12
#2 ERROR: docker.io/lambci/lambda:python3.12: not found
------
 > [internal] load metadata for docker.io/lambci/lambda:python3.12:
------
Dockerfile:1
--------------------
   1 | >>> FROM lambci/lambda:python3.12
--------------------
ERROR: failed to solve: lambci/lambda:python3.12: failed to resolve source metadata for docker.io/lambci/lambda:python3.12: docker.io/lambci/lambda:python3.12: not found
unknown: Invoking function locally
```
Looks like there is no image in the dockerhub for lambci/lambda:python3.12, just 3.8. Is there a way to fix that with the last python version that AWS is using?

### Context

serverless support --summary

(node:1141382) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.19
- Service Config File: serverless.yml
- Service Name: <function>
- Service Runtime: python3.12
- Service Stage: dev
- Service Region: <region>
- Command: invoke local --function <function>
- Error Code: DOCKER_IMAGE_BUILD_FAILED

## Service Path
~/work/<function>

## Error Message
Failed to build docker image (exit code 1})

## Error Stacktrace
```
at AwsInvokeLocal.buildDockerImage (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:851:1095)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 1)
at async AwsInvokeLocal.invokeLocalDocker (file://~.serverless/releases/4.1.19/package/dist/sf-core.js:851:2537)
at async PluginManager.runHooks (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:854:9296)
at async PluginManager.invoke (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:854:10066)
at async PluginManager.run (file://~.serverless/releases/4.1.19/package/dist/sf-core.js:854:10790)
at async Serverless.run (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:861:10442)
at async runFramework (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:909:2314)
at async route (file://~/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16304)
```

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: <user>
# "service" is the name of this project. This will also be added to your AWS resource names.
service: <function>
provider:
  name: aws
  runtime: python3.12
functions:
  <function>:
    handler: handler.lambda_handler
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue

**Comment by czubocha** [comment]
This was addressed by https://github.com/serverless/serverless/pull/12754
