### ISSUE TITLE
env files not loading based on the stage

### ISSUE THREAD

**Issue by demian85** [serverless/serverless#12760]
### Issue description

Can someone please explain why v4 is not loading my .env files as before? 
It is now always loading `.env` file regardless of the stage.
When using stage `dev`, the file `.env.dev` has always been loading for me. But now it doesn't work like that and `.env` is the only one loading.
The docs are not clear either. It states that the naming convention for env files is `[stage].env`, which has never been the case. I've always used `.env.[stage]`.

I'm not setting `useDotEnv: true` since it is now the default behavior.

### Context

N/A

**Comment by czubocha** [comment]
Hey @demian85, thank you for reporting this issue.

You’re correct - there’s a typo in the current docs. The correct naming convention should be `.env.[stage]`, not `[stage].env` We’ll get that updated.

Both `.env.[stage]` and `.env` files should be loaded as expected. However, we noticed that variables defined in `.env.[stage]` are not overriding those in the `.env` file which seems to be the issue you’re encountering. Could you confirm if that’s the case on your end? We’re aware of this issue and will be addressing it in the next release.

We’ll also be updating the documentation to provide more clarity on how env file loading works in detail.

**Comment by demian85** [comment]
Yes, that's correct. Plain `.env` files seem to have precedence over the others, it seems.

**Comment by czubocha** [comment]
Hey @demian85, the fix has been released in [v4.1.23](https://github.com/serverless/serverless/releases/tag/v4.1.23). Feel free to test it out.
