### ISSUE TITLE
Missing esbuild Dependency Prevents Project Build in Serverless v.4.2.5

### ISSUE THREAD

**Issue by morozow** [serverless/serverless#12787]
### Issue description

Environment:
- Framework Version: Serverless v.4.2.5
- Operating System: MacOS 14.1.1 (23B81)
- Node Version: v20.9.0
- Package Manager: Yarn

Description:
There is a critical issue in Serverless Framework version 4.2.5 where the project fails to build due to the missing `esbuild` dependency in the build service. This problem prevents any progress on project development as the build process cannot be completed.

Steps to Reproduce:
1. Set up a new Serverless project or use an existing one that targets v.4.2.5.
2. Run the build command specific to your setup (e.g., serverless deploy or a custom build script).
3. Observe that the build process fails with errors related to `esbuild`.

Expected Behavior:
The build process should complete without errors and the `esbuild` dependency should be correctly integrated within the framework’s build service.

Actual Behavior:
The build process fails, outputting errors indicating that the `esbuild` dependency is missing.

Temporary Workaround:
Executing `yarn install` directly in the version release directory of the Serverless project temporarily resolves the issue by manually adding the missing `esbuild` dependency.

Requested Action:
Please integrate `esbuild` as a dependency in the upcoming patches or releases to prevent build failures. This fix is critical for maintaining seamless operation and development experience using the Serverless Framework.

### Context

N/A
Reason: content exceeds terminal length limit

**Comment by austencollins** [comment]
@morozow Thanks for the report. Looking into this now..

**Comment by Mmarzex** [comment]
@morozow Thanks for the report. Unfortunately I am unable to reproduce this issue in a fresh install, esbuild installs correctly and works. Could you try deleting the `.serverless` directory in your home directory and try re-running serverless?

**Comment by morozow** [comment]
@Mmarzex I have completely cleaned up my system to eliminate any unused files or configurations that could potentially cause conflicts previously. This approach seems to have resolved the issue effectively as I am no longer experiencing the problem.

Additionally, I would like to provide some background information that may be relevant to your investigation into the matter. Throughout my usage of Serverless I have systematically upgraded and used each release starting from version `3.33.0` and I've also tested the second version like `2.72.0` in case I'm right and others. I believe I have accurately followed the version sequence, as each of these releases is stored within the `~/.serverless/releases` directory on my system. This directory has historically contained each version, which might assist in pinpointing any potential discrepancies or issues related to specific releases.

Please let me know if there are any specific logs, configurations or further details I can provide to assist with your ongoing analysis of this issue.
