### ISSUE TITLE
serverless deploy --stage dev - UPDATE_ROLLBACK_FAILED

### ISSUE THREAD

**Issue by h3roic** [serverless/serverless#12798]
### Issue description

I am trying to execute a deployment to my dev environment on AWS using the Serverless Framework. Running command on powershell: 

-serverless deploy --stage dev

**When doing so I am getting this error:**
-  Serverless Error ----------------------------------------

  Stack:arn:aws:cloudformation:us-east-1:167476023579:stack/zzxadmin-api-dev/405cbfa0-9013-11ea-9c73-0e0e50fbc697 is in UPDATE_ROLLBACK_FAILED state and can not be updated.

### Context

**On my AWS console Cloudformation Stack info:**

UPDATE_ROLLBACK_FAILED
Detailed status
-
Status reason
The following resource(s) failed to update: [ZzxadminLambdaFunction, WarmUpPluginDefaultLambdaFunction, AuthorizerLambdaFunction, LoginLambdaFunction].

**Events:**

-logical ID: zzxadmin-api-dev Status: | UPDATE_ROLLBACK_FAILED | - | Status reason: The following resource(s) failed to update:   [ZZxadminLambdaFunction, WarmUpPluginDefaultLambdaFunction,   AuthorizerLambdaFunction, LoginLambdaFunction].
-- | -- | -- | --

logical ID: WarmUpPluginDefaultLambdaFunction Status: | UPDATE_FAILED | - | Status reason: Resource update cancelled
-- | -- | -- | --

Logical ID: | LoginLambdaFunction Status: | UPDATE_FAILED | - | Status reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 13acd42d-06e9-4a3b-841f-dd70f74eecf8)" (RequestToken: 18543860-776d-e497-e6bf-40c90819132c, HandlerErrorCode: InvalidRequest)

Logical ID: | AuthorizerLambdaFunction Status: | UPDATE_FAILED | - | Status reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 4d73d326-efb0-4094-abfa-0fb1f9d9a69d)" (RequestToken: 5889bc56-9f22-ef91-efcf-b8449a8ad673, HandlerErrorCode: InvalidRequest)

Logical ID: | ZzxadminLambdaFunction Status: | UPDATE_FAILED | - | Status reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: caef1dca-e349-432b-9a27-762c11b5861e)" (RequestToken: 50a06e65-a52e-aa23-2016-c9d6e11600d9, HandlerErrorCode: InvalidRequest)

**What has been done:**

Through the console and the AWS CLI I have tried continuing the rollback: 

- aws cloudformation continue-update-rollback --stack-name

- I've updated my nodejs version my serverless.yml file to nodejs16.x and updated all functions (nodejs version 16.x)

- I've updated the nodejs runtime on my Lambda to nodejs16.x

Still getting the same error.

**Comment by skierkowski** [comment]
@h3roic This appears to be an issue with CloudFormation getting into an inconsistent state due to the use of the deprecated Node version. Having said that, you may want to check out [this article from AWS on this issue](https://repost.aws/knowledge-center/cloudformation-update-rollback-failed).
