### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by rebeckaelin** [serverless/serverless#12803]
### Issue description

out of nowhere I got this error message in my terminal:

✖ request to https://core.serverless.com/api/bff/ failed, reason: Hostname/IP does not match certificate's altnames: Host: core.serverless.com. is not in the cert's altnames: DNS:*.c2.us-east-1.airflow.amazonaws.com
Error: request to https://core.serverless.com/api/bff/ failed, reason: Hostname/IP does not match certificate's altnames: Host: core.serverless.com. is not in the cert's altnames: DNS:*.c2.us-east-1.airflow.amazonaws.com

i have tried another computer (a brand new one) installing, uninstalling serverless. not when i go to set it up i get this error after i've written a name for my new project. 

it started in an existing project where everything ran smoothly and then i added a sortkey and globalsecondaryindexes and then everything went south..

**Comment by Mmarzex** [comment]
@rebeckaelin that sounds like something on your local machine is overwriting the certificate chain. Our certs for that domain are active and are handled in ACM. So I'd check to make sure your machine trusts the AWS roots.

**Comment by rebeckaelin** [comment]
ok, the thing is that i bought a brand new computer today and the same issue occured.. any ideas how i check so that my machine trust the roots? because it just happened over night that i got this error :S

**Comment by Mmarzex** [comment]
@rebeckaelin If you actually just open the url `https://core.serverless.com/api/bff/` in a browser do you get SSL issues there?

**Comment by rebeckaelin** [comment]
i could not reach the page. but a massive thanks anyway since you pointed me in the right direction. what solved the issue? restart your router. haha OMG, spent hours on this. now i know, always restart EVERYTHING!
