### ISSUE TITLE
Support `provenance` for docker BuildKit

### ISSUE THREAD

**Issue by vicary** [serverless/serverless#12808]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When using the new BuildKit system, previously `docker buildx` and currently replacing `docker build`, custom images built for Lambda must be built with both `platform` and `provenance` CLI options.

Otherwise AWS will throw an error message similar to this one: `The image manifest or layer media type for the source image <ecr_arn> is not supported.`, which indicates a multi-arch manifest being generated despite a `platform` option already restricts the architecture of the underlying image. `--provenance=false` must be specified to stop BuiltKit from generating said manifest.

### Proposed solution (optional)

Alongside `ecr.images.*.platform` added in #10237, support a new boolean option `ecr.images.*.provenance`.

**Comment by ermi-ltd** [comment]
+1 on this, its become a blocker for us too.

**Comment by czubocha** [comment]
Hey everyone, the `provenance` config option has just been released in [v4.4.17](https://github.com/serverless/serverless/releases/tag/v4.4.17) ([docs](https://www.serverless.com/framework/docs/providers/aws/guide/functions#referencing-container-image-as-a-target)). Let us know if you have any feedback or run into further issues!

**Comment by tomkat-cr** [comment]
`--provenance=false` saved the day. Thanks

**Comment by Philrobots** [comment]
For those building your Docker image using Github Actions or another CD pipeline

Add 

```
BUILDX_NO_DEFAULT_ATTESTATIONS=1
```

Docs:

By default, BuildKit v0.11 and later adds [provenance attestations](https://docs.docker.com/build/metadata/attestations/slsa-provenance/) to images you build. Set BUILDX_NO_DEFAULT_ATTESTATIONS=1 to disable the default provenance attestations.

Link:

https://docs.docker.com/build/building/variables/#buildx_no_default_attestations
