### ISSUE TITLE
[v4] License key expiry date

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12819]
### Issue description

I've noticed that the license key you generated is a JWT token. And it has an expiry date set to one year, ie:
```
{
  "subscriptionId": "yyyyyyyyy-aaaaa-bbbb-ccccc-xxxxxxxxx",
  "orgId": "yyyyyyyyy-aaaaa-bbbb-ccccc-xxxxxxxxx",
  "iat": 1725969425,
  "exp": 1757505425,
  "iss": "app.serverless.com"
}
```

Would that mean we need to have a License Key rotation mechanism in place to be able to use Serverless v4, ie. deploy services, after a year since the original License was generated?

### Context

Serverless Framework v4

**Comment by skierkowski** [comment]
@kdybicz No, the `exp` is not used for license key validation. Having said that, we plan on adding an improved experience for license key management in the future so you can more easily expire and rotate license keys. Is that something you'd be interested in; if so, what is your use case for that?

**Comment by kdybicz** [comment]
@skierkowski I believe our use case is fairly straightforward: generate a dedicated key for each service we deploy and remove it when no longer needed. Having to rotate that key would be a bit annoying. So I'm afraid that I will not be able to provide you with any really interesting use cases 🤷🏼‍♂️

**Comment by kdybicz** [comment]
We have multiple teams managing one or more services each, and sometimes they share responsibilities over the same service. We're used to managing keys per service, as this keeps things more organized and easier to maintain in the long term. Usually, we have a dedicated person or a team that has permissions to manage the keys.

> Also, why are license keys best managed per service, as opposed to one global key, or one per team, or per user, etc?

I would say it's because it's somewhere in between the constant security vs convenience struggle.

**Comment by skierkowski** [comment]
I'm going to close this issue out. We're planning on implementing your [other request](https://github.com/serverless/serverless/issues/12818), and when we release that we'll also release doc updates with more details about the License Keys (like the fact that they don't expire).
