### ISSUE TITLE
[v4] Provide a license key via serverless.yml property

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12818]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

We're using `SSM:` to provide secrets to the service we're building. It would make sense for us to store the Serverless license key inside the AWS Parameter Store and set it inside `serverless.yml` instead of using the `SERVERLESS_LICENSE_KEY` env property.

**Comment by skierkowski** [comment]
That's a really interesting use case. I could see someone doing that with other variable resolvers, like storing the License Key in HashiCorp Vault and using the [`${vault}` resolver](https://www.serverless.com/framework/docs/guides/variables/hashicorp/vault) to retrieve it. I'll take this into consideration for upcoming feature work.

**Comment by kdybicz** [comment]
That would be amazing, thank you!

**Comment by czubocha** [comment]
@kdybicz starting with [v4.4.5](https://github.com/serverless/serverless/releases/tag/v4.4.5) it's now possible to provide the License Key using `licenseKey` field in the config. See the docs [here](https://www.serverless.com/framework/docs/guides/license-keys). Feel free to let us know if you have any other ideas for improvements.
