### ISSUE TITLE
Define new deploy lifecycles / update awsDeploy plugin to use new lifecycle events

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1282]
Things such as `compileFunctions` or `compileEvents` should be triggered with the help of an own lifecycle event so that e.g. event related plugins can live inside an own plugin.

**Comment by pmuens** [comment]
Here are some notes when we start the implementation of the `awsS3EventSource` plugin:

- We cannot define new hooks inside the `awsDeploy` plugin as it only reacts to hooks and has no own commands
- (hence) We need to define the new hooks inside the `deploy` plugin
- Events are always bound to functions so it might make sense to treat and compile them together (otherwise we'll loop over the functions, to compile the functions and afterwards loop over the functions to compile the events the function can have)
- CloudFormation makes it pretty straight forward to implement this feature

Here's a proposal:
add a `compile` lifecycle inside the `deploy` plugin:

```
this.commands = {
      deploy: {
        usage: 'Deploy Service.',
        lifecycleEvents: [
          'compile',
          'deploy',
        ],
      },
    };
```

Move the `compileFunctions` code from the `awsDeploy` plugin to the new `awsCompile` plugin.
Inside of this plugin we can add functionality to compile the function and the event sources for this function.

/cc @flomotlik @eahefnawy

**Comment by flomotlik** [comment]
I think we should keep the compile function and compile events functionality separate so in the future we can even swap out specific event configuration syntax for more complex setups easily.

I would add the following lifecycle events:

* compileFunctions
* compileEvents
* deploy

so that events can bind easily into it and others can also build new events if they want to and hook into the compileEvents lifecycle event. If we strongly bind this into a compile hook it will be really hard for others in the future to implement more event support.

**Comment by pmuens** [comment]
@flomotlik sounds good!
Here's the PR which implements this: https://github.com/serverless/serverless/pull/1284

Additionally here are some remarks / thoughs I had during development:
- We really need the `PluginStore` soon to make plugin to plugin communication easier / more convenient. Right now I use the `serverless.service` object to do data exchange between the plugins but this feels wrong / not that easy to pick up for other contributors
- We should maybe spend some time on refactoring after we've added all the necessary functionality for v1. Feels like the code is a little bit entagled
- Some code may be DRYed out (tests are a good place where we might want to use `sinon` mocks rather than our own as they repeat often and make reading the tests quite hard)

**Comment by pmuens** [comment]
Here's an overview of the new lifecycles which will be added while working on this issue (#1284 is the corresponding PR).

- `initializeResources` --> Create resource configuration in Service object and add Provider specific necessary resource elements (e.g. S3 deployment Bucket for AWS)
- `createProviderStacks` --> Create necessary stack or provider resources on provider (e.g. deploy S3 bucket before a later update; deploys all necessary stack resources)
- `compileFunctions`
- `compileEvents`
- `deploy` --> updates the relevant plugins and functions and deploys them

**Comment by pmuens** [comment]
Done with #1284
