### ISSUE TITLE
No up to date JSON Schema Anywhere

### ISSUE THREAD

**Issue by kferrone** [serverless/serverless#12831]
### Issue description

No way to get autocomplete. 

Not one vscode extension supports v4 schema. Simply search serverless on the vscode market and you'll see. 

The [json schema store](https://www.schemastore.org/json/) is out of date: 
https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json

Please update this or make a new one please.

**Comment by skierkowski** [comment]
@kferrone At the moment we do not provide a supported JSON Schema. The schema [you referenced](https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json) is graciously maintained by the community; I'd recommend reaching out to them about the updates.
