### ISSUE TITLE
Layer/package path not working properly with Serverless Compose

### ISSUE THREAD

**Issue by aburroughs97** [serverless/serverless#12845]
### Issue description

Using `path` in a `serverless.yml` file to give the location of a layer or package artifact fails when trying to run `serverless deploy` using serverless compose. It seems to be looking for the artifact in two different places, first at the service level and then at the root of the project (where it can't find it).

I've included our directory structure below. We are using a shared service to house a few lambda layers, starting with a `common` one. Its code is defined in `services/shared/layers/common/*`, so in our `services/shared/serverless.yml` file we set the layer `path` to `layers/common` (the path relative to the serverless file). I would expect this to look for that path relative to the `serverless.yml` file, which it does....._sort of_.

When running `serverless deploy` at the root, I get the following error:

```
✖ shared
    Cannot read file C:\Users\alexb\source\repos\serverless-path-issue\layers\common\foo.js due to: ENOENT: no such file or directory, open 'C:\Users\alexb\source\repos\serverless-path-issue\layers\common\foo.js'
```

Serverless seems to be able to find `foo.js` in the correct place since it is referenced by name in the error, but at some point down the line it begins looking for `layers/common/foo.js` at the _root_ of the project instead of relative to the `services/shared/serverless.yml` file. At the root level it should be looking for `services/shared/layers/common/foo.js`

## Steps to reproduce:
1. Initialize a project with the following directory structure, foo.js can be anything you'd like
```
serverless-compose.yml
services/
  shared/
    serverless.yml
    layers/
      common/
        foo.js 
```

4. Add the following to `services/shared/serverless.yml`
```yml
service: shared

layers:
  common:
    path: layers/common
```

5. Add the following to `serverless-compose.yml`
```yml
services:
  shared:
    path: services/shared
```

6. Run `serverless deploy` at the root

### Items of Note:
1. If you navigate into the `services/shared` folder and run `serverless deploy` there it works with no issues
2. I've attempted to solve this using different types of paths (`./layers/common`, `services/shared/layers/common`, etc.) and what I've included above seems to be the closest to working. Every other option I've tried doesn't ever seem to find `foo.js` 
3. I ran into a similar issue when trying to use a `zip` artifact for a lambda go function. In this case, we were building the function and putting the zip artifact into a `bin` folder. After running `serverless deploy` I saw an issue similar to the one I'm seeing now, it seemed to be looking at the relative path first and then at the root. The only way I could get the deployment to work was to duplicate the `bin` folder so it existed at both the root and the service level. Something like:
```
bin/
services/
  service-a/
    bin/
  serverless.yml
serverless-compose.yml
```
```yml
functions:
  service-a:
    package:
      artifact: bin/foo/foo.zip
```
If I removed either `bin` folder the deployment would fail. I suspect a similar solution would work for this issue, but I'm not sure it's feasible long-term

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.4
- Command: support --summary true

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue

**Comment by czubocha** [comment]
Hi @aburroughs97, thanks for reporting this. We're looking into it.

**Comment by czubocha** [comment]
@aburroughs97 the fix has been shipped in [v4.4.5](https://github.com/serverless/serverless/releases/tag/v4.4.5). Feel free to let us know if you run into any more issues.

**Comment by danielvijge** [comment]
@czubocha When packaging a layer the folder names in the zip file are not correct.

I have the following folder structure:
```
-- layer
  \-- ext-dependencies
    \-- java
      \-- lib
        \-- {many *.jar files}
  -- serverless.yml
```
In serverless.yml `path` is set to `ext-dependencies`.

When doing the packaging from compose the files in the zip file have a top level folder called `encies`.
So extracting the zip file has this folder structure:
```
-- encies
  \-- java
    \-- lib
      \-- {many *.jar files}
```
When doing the packaging from within the layers folder, the zip file has this folder structure:
```
-- java
  \-- lib
    \-- {many *.jar files}
```
Because the jar files are zip'ed in an additional top level folder, the lambda functions cannot find it in the layer, and all functions fail to execute.

**Comment by schammah** [comment]
@aburroughs97 was it fixed for you?
using `4.4.18` and still has this error with compose
