### ISSUE TITLE
CLI can't start

### ISSUE THREAD

**Issue by vmurin** [serverless/serverless#12847]
### Issue description

Following error occurs on CLI start

`Could not find a valid version to run` 

No any other debug information is provided.
Tried with latest (4.4.4) and 4.0.35 versions - the same result
Node reinstalled, serverless reinstalled.
The same error message comes if I try to start binary directly.
Binary name: serverless-linux-amd64-0.0.2

### Context

N/A

serverless: 4.4.4
OS: WSL2
Node: 20.18.0 installed via nvm

**Comment by austencollins** [comment]
Thanks for reporting @vmurin. We're looking into this now.

**Comment by austencollins** [comment]
Fix in the works...

**Comment by austencollins** [comment]
A fix has been rolled out. Please let us know if you continue to see the issue @vmurin. No update should be necessary.

**Comment by austencollins** [comment]
@vmurin Others have confirmed the fix in #12846 We're standing by in case anything else arises. We apologize for the inconvenience.

**Comment by vmurin** [comment]
@austencollins I can confirm it too. Thank you! 🙏🏻
