### ISSUE TITLE
Error "Could not find a valid version to run"

### ISSUE THREAD

**Issue by viniciushvsilva** [serverless/serverless#12846]
### Issue description

Getting "Could not find a valid version to run" when running any command with serverless.

Was using mac 13.5, then tried updating to Sequoia, but didn't change anything.

Serverless installed version 4.4.4

Reproduction:

```
npm i -g serverless
serverless
```

**Comment by brettdh** [comment]
Same here, even with `frameworkVersion: 4.4.0` pinned in `serverless.yml` and `~/.serverless/releases/4.4.0` already present on my machine. Seems like a critical ops issue on the Serverless end.

Is it time to consider abandoning auto-updates yet? It's caused us nothing but pain and we don't want it.

**Comment by NicoHinderling** [comment]
Me too... @austencollins this is a little shocking. I remember working with you guys to specifically add the `frameworkVersion` field to the serverless.yml file and yet this has still happened.

This is crazy considering the risk for an auto CI system

**Comment by austencollins** [comment]
Thanks for reporting @viniciushvsilva. We're looking into this now.

**Comment by brettdh** [comment]
FWIW the workaround in #12784 (modifying `metadata.json` to have a recent timestamp) did not appear to help in this instance.

**Comment by austencollins** [comment]
Fix incoming...

**Comment by austencollins** [comment]
A fix has been rolled out. Please let us know if you continue to see the issue @viniciushvsilva and @NicoHinderling.

**Comment by NicoHinderling** [comment]
looks like we're back @austencollins thanks for the fast turn around

**Comment by NicoHinderling** [comment]
@austencollins just curious, how was this possible? I thought the version pinning would be the fail safe against this happening? 😅

**Comment by austencollins** [comment]
The Framework version locally on your machine is fine. But on initialization, the Framework checks our Releases API to look for new releases, ensure the current version is usable, ensure the current version has no security issues, etc. Unfortunately, we pushed a minor bug to our Releases API and the CLI did not handle that error scenario correctly. We fixed the API and identified where to improve the CLI in this scenario, letting it fall back to using the target version without qualms.

**Comment by austencollins** [comment]
Going to close this now @viniciushvsilva. We're standing by in case anything else arises. We apologize for the inconvenience.

**Comment by kieran-bellew** [comment]
@austencollins any particular reason your testing (CICD integration testing or e2e maybe?) didn't pick this up? We like to use latest version in our docker pipelines for deployments, so this was quite disruptive to our ones migrated to your paid v4 offerings.

**Comment by d192122** [comment]
@austencollins this appears to be happening again. Started around 1230 eastern today.

**Comment by austencollins** [comment]
@d192122 I'm unable to recreate. Just went through fresh installation, changing across a dozen versions, using the latest version. Please include more info about your system and targeted framework version.

**Comment by d192122** [comment]
I may have jumped the gun. But interesting symptom. I had an error in an arn value. THe output from sls was same as Friday's issue 'Could not find a valid version to run'

**Comment by kramsha00** [comment]
Facing the same error today after installing serverless domain manager. 

`
"serverless-esbuild": "^1.52.1",
    "serverless-http": "^3.2.0",
    "serverless-offline": "^14.0.0"
`

`"serverless-domain-manager": "^7.4.0",`

Any idea whats the cause and how to resolve this?
