### ISSUE TITLE
Add ability to specify Cloudwatch log group retention policy in function definition

### ISSUE THREAD

**Issue by mikelax** [serverless/serverless#1285]
When a Lambda function is created an implicit Cloudwatch log group is also [created](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-functions.html) with the lambda function name. 

I would like to be able to specify the _Expire Events After_ value in the s-function definition file. We know the name of the Cloudwatch Group because of the lambda name. The AWS CLI for [put-retention-policy](http://docs.aws.amazon.com/cli/latest/reference/logs/put-retention-policy.html) can be used for this purpose. 

Here is an potential snippet: 
```json
"cloudwatch": {
  "log-groups": {
    "retention-in-days": 14
  }
}
```

**Comment by flomotlik** [comment]
You should be able to set this through custom resources in V1.0

**Comment by ctindel** [comment]
@flomotlik Can you show an example of how to do this?  I tried googling "serverless cloudwatch retention" and this ticket is the only thing that comes up.

**Comment by flomotlik** [comment]
@ctindel this PR will help solve this: https://github.com/serverless/serverless/pull/1944

**Comment by rsshilli** [comment]
I'm still super confused how I change the log retention period.

**Comment by ctindel** [comment]
@rsshilli https://github.com/serverless/serverless/issues/2653
