### ISSUE TITLE
[v4] Unable to start serverless-offline

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12855]
### Issue description

When trying to start Serverless service locally I'm getting below error and the app crashes...
```
For help, see: https://nodejs.org/en/docs/inspector
Error: Get "https://install.serverless.com/releases.json": dial tcp [2600:9000:21a1:4800:4:yyyy:ttt:xxx]:443: connect: no route to host
```

### Context

Serverless v4.4.4

**Comment by skierkowski** [comment]
@kdybicz Is this still an issue? We had an incident with that service on Friday but it was quickly resolved.

**Comment by kdybicz** [comment]
Nope, the issue was solved in minutes. Fortunately, I was not deploying to prod, but testing stuff locally.
