### ISSUE TITLE
Error: gzip: invalid header

### ISSUE THREAD

**Issue by RafaelRViana** [serverless/serverless#12861]
### Issue description

I am getting this error any server less command.

For example 
serverless —version
serverless support
serverless deploy

### Context

My project was working correctly, I didnt make any relevant change. Now I can't deploy it anymore. I get this error "Error: gzip: invalid header". 
Doing more tests I discovered it happens with any command using serverless cli.

**Comment by tsmith1024** [comment]
Seeing this as well right now -- any command fails with `Error: gzip: invalid header`

Had previously deployed my project a few days ago.

**Comment by trevor-e** [comment]
Yep seeing this too, basically unable to do anything via the CLI right now.

I notice it happens right after `Updating...` shows up in the CLI output.

**Comment by Mmarzex** [comment]
Sorry you guys are running into this. I'm unfortunately not able to reproduce. Could you try removing the `.serverless` folder that is in your home directory and trying your commands again?

**Comment by RafaelRViana** [comment]
I already made this test, but didnt solve. Reinstall serverless cli might solve?

**Comment by RafaelRViana** [comment]
I didnt find this issue in any other forum in the internet.
But found this issue from June https://github.com/serverless/serverless/issues/12719.

It may have happened again?

**Comment by Mmarzex** [comment]
@RafaelRViana If it was the issue you referenced we would have known right away as it would be failing for all users and our internal checks would have failed for that matter. 

Are you pinning to a specific version of the framework in your `serverless.yml`'s `frameworkVersion` property? If you are what version? And if you aren't could you try pinning to a previous version like `4.4.4`?

**Comment by trevor-e** [comment]
In my project I have `frameworkVersion: '4.1.17'`. I tried updating to a newer version like `4.4.4` and still have the issue. I also tried deleting the `.serverless` folder.

**Comment by trevor-e** [comment]
Seems like it might be related to PNPM?
```
➜  myProject git:(telkins/my-branch) ✗ sls --version

Serverless ϟ Framework

 • 4.4.4

➜  myProject git:(telkins/my-branch) ✗ pnpm exec sls --version
Error: gzip: invalid header
```
but if I don't run via pnpm then my project modules don't load correctly.

**Comment by Mmarzex** [comment]
Very strange @trevor-e not sure why that would matter but we have not tested with pnpm so it is possible. For now I'd recommend to use the global version and pin versions using the `frameworkVersion`. We will have to verify pnpm support and see if there is something we need to do to make that work.

**Comment by RafaelRViana** [comment]
In Slack channel, other folks were facing same issue, they recommended:

```
npm cache clear --force
npm remove -g serverless
npm install -g serverless
```

I tried here and it solved. But no idea, why it happened.

**Comment by gotchipete** [comment]
> In Slack channel, other folks were facing same issue, they recommended:
> 
> ```
> npm cache clear --force
> npm remove -g serverless
> npm install -g serverless
> ```
> 
> I tried here and it solved. But no idea, why it happened.

Same issue here, this fix worked for me, tx!

**Comment by john-tach** [comment]
> > In Slack channel, other folks were facing same issue, they recommended:
> > ```
> > npm cache clear --force
> > npm remove -g serverless
> > npm install -g serverless
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried here and it solved. But no idea, why it happened.
> 
> Same issue here, this fix worked for me, tx!

+1

**Comment by tsmith1024** [comment]
Remove/reinstall fix above worked here too -- thank you! 🎉

**Comment by ecappa** [comment]
Same here...


> > > In Slack channel, other folks were facing same issue, they recommended:
> > > ```
> > > npm cache clear --force
> > > npm remove -g serverless
> > > npm install -g serverless
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I tried here and it solved. But no idea, why it happened.
> > 
> > 
> > Same issue here, this fix worked for me, tx!
> 
> +1

+1 
here too....

**Comment by ABDULALMAS** [comment]
> Same here...
> 
> > > > In Slack channel, other folks were facing same issue, they recommended:
> > > > ```
> > > > npm cache clear --force
> > > > npm remove -g serverless
> > > > npm install -g serverless
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I tried here and it solved. But no idea, why it happened.
> > > 
> > > 
> > > Same issue here, this fix worked for me, tx!
> > 
> > 
> > +1
> 
> +1 here too....

worked for me too

**Comment by LeonardoLopesFilho** [comment]
thank you very much from Brazil!!

**Comment by Mmarzex** [comment]
Sorry that this happened to folks, we are looking into it and I'm going to lock conversation for now. Please add a new issue if you think a new problem has arisen.
