### ISSUE TITLE
[Bug]: Dark/Light Mode Toggle Malfunctioning in Documentation

### ISSUE THREAD

**Issue by SidGit195** [serverless/serverless#12873]
### Issue description

While reading the documentation, the dark mode toggle works fine initially when switching from light to dark mode. However, switching back from dark mode to light mode does not work correctly on the first attempt. It only switches properly after toggling a second time.

https://github.com/user-attachments/assets/686ae7d1-a3c9-4426-b9cd-efda95b4cb15

**Comment by eahefnawy** [comment]
Thanks for reportin @SidGit195 ... we'll look into it 👍

**Comment by walidelnozahy** [comment]
@SidGit195 This issue has been fixed. Thanks for reporting!
