### ISSUE TITLE
[v4] Updating a plugin from v3 to v4 and encountering issues to resolve custom variables and validation

### ISSUE THREAD

**Issue by hrzbrg** [serverless/serverless#12883]
### Issue description

Hi Serverless Team,
in our company we built a custom plugin to align and ease some configuration. On v3 this worked quite well using a custom variable source called `sflx`. Now I started modifying the plugin to make it ready for v4 (specifically 4.4.6) and encounter 2 problems. 

## First Issue
The `resolveVariable` way of accessing `sls:stage` does not work anymore. I've snipped out a bit of the involved code below. It tells me that `Failed to resolve variable 'account' with resolver 'sflx' and provider 'sflx': TypeError: arg.resolveVariable is not a function`. Mind that the below code is not a complete executable minimal example of the problem, just snippets.

```
class OmniPlugin implements ServerlessPlugin {
	configurationVariablesSources: Record<'sflx', VariableResolver> = {
		sflx: SFLXResolver(),
	}
	log: ServerlessPlugin.Logging['log']
	serverless: ServerlessPatched
	options: Serverless.Options
	hooks: ServerlessPlugin.Hooks

	constructor(...)
...

export function SFLXResolver(): VariableResolver {
	return {
		async resolve(arg) {
			switch (getVariable(arg.address)) {
				case 'account': {
					log('resolveVariable is of type ' + typeof arg.resolveVariable)
					const stage: string = await arg.resolveVariable('sls:stage')
					return { value: environmentToAccount(stage) }
				}
...

export type VariableResolver = {
	resolve: (arg: {
		address: string
		params: [string]
		options: Record<string, unknown>
		resolveVariable: (address: string) => Promise<string>
	}) => Promise<{ value: string }>
}
```

## Second Issue
We use the plugin to configure a shared deployment bucket. The bucket name uses one of the variables from the custom variable scope as follows:
```
	configureDeploymentBucket(): void {
		const providerBucketConfiguraton = {
			name: 'sflx-${sflx:environment}-rest-of-the-name-redacted',
		}
		this.serverless.extendConfiguration(['provider', 'deploymentBucket'], providerBucketConfiguraton)
	}
```
With v4 now this errors I guess because the regex validation happens on the string `sflx-${sflx:environment}-rest-of-the-name-redacted` and not on the result of the templating.
```
Configuration error: 
     at 'provider.deploymentBucket.name': must match pattern "(?!^(\d{1,3}\.){3}\d{1,3}$)(^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$)"
```

I would be glad if you could point me at a solution direction. Getting this plugin to work with v4 will greatly speed up our migration to v4.

**Comment by mishabhi** [comment]
Yes I can confirm I also had similar issue. To fix this I have been using fixed version 4.4.2 for `frameworkVersion`

**Comment by czubocha** [comment]
Hey @hrzbrg, we're looking into it.

**Comment by hrzbrg** [comment]
Any insights from your side?

**Comment by czubocha** [comment]
Apologies for the delayed response. We’ve identified and addressed both issues, so your setup should work properly in the next version. We’re planning to release it next week.

**Comment by hrzbrg** [comment]
Thanks @czubocha so far the above issues have been resolved but we ran into another issue 😓 
The plugin configures standard settings for Vault like:
```
configureVault(): void {
  const vaultSetup = {
	  type: 'vault',
	  address: 'https://our-vault-address.com',
	  version: 'v1',
	  path: 'services/data',
  }
  this.serverless.extendConfiguration(['stages', 'default', 'resolvers', 'vault'], vaultSetup)
}
```
To give people convenience to just get variables like `VAULT_EXAMPLE: ${vault:someservice/${sls:stage}/database/data.ENDPOINT}`

However it seems that the resolution of Vault variables happens before the configuration is extended with my `vaultSetup`. Is that so?

**Comment by czubocha** [comment]
> However it seems that the resolution of Vault variables happens before the configuration is extended with my vaultSetup. Is that so?

Yes, it works that way.
