### ISSUE TITLE
Unable to get proper deployment ID from ApiGatewayDeployment${sls:instanceId}

### ISSUE THREAD

**Issue by stryker-sk** [serverless/serverless#12891]
### Issue description

I need to make several stages in API gateway due to the deployment changing the usage plan that was manually setup. When I try to create multiple API gateway stages, it fails due to the depends on resource not picking up the value for `ApiGatewayDeployment${sls:instanceId}` correctly.

### Context

version: 4.4.7

**Comment by czubocha** [comment]
Hey @stryker-sk, thanks for reporting. We'll include the fix in the next release.

**Comment by czubocha** [comment]
Hey @stryker-sk, the fix has been released in [v4.4.8](https://github.com/serverless/serverless/releases/tag/v4.4.8.). Give it a try and let us know if you’re still experiencing any issues.

**Comment by stryker-sk** [comment]
Awesome, thank you so much 🙏
