### ISSUE TITLE
sls:instanceId returning different values

### ISSUE THREAD

**Issue by rserro** [serverless/serverless#12894]
### Issue description

I use a .js resource file so that I can set up a dynamic resource key. It was working on V3 but not it is returning different values when sls:instanceId is used in the .yml files vs when it is used in the .js files.

serverless.yml resources:
![Screenshot 2024-10-28 at 15 11 37](https://github.com/user-attachments/assets/1ae5985b-34ed-4869-babe-a47867d49cce)

.yml
![Screenshot 2024-10-28 at 15 09 59](https://github.com/user-attachments/assets/1c643219-d1eb-4980-99b7-5c2d69212379)

.js
![Screenshot 2024-10-28 at 15 09 46](https://github.com/user-attachments/assets/a41dea57-3f15-4992-87e6-d4fe9d31baf5)

Distinct instanceId on DependsOn vs Resources:
![Screenshot 2024-10-28 at 15 06 41](https://github.com/user-attachments/assets/23593900-c10c-4124-8a4b-5a8c1ec137f3)

### Context

sls v4

**Comment by czubocha** [comment]
Hey @rserro, thanks for reporting this. It’s already been noted in [issue #12891](https://github.com/serverless/serverless/issues/12891). We’ll include the fix in the next release.
