### ISSUE TITLE
jaws module delete <module>

### ISSUE THREAD

**Issue by DoWhileGeek** [serverless/serverless#129]
I've been playing with the new v1 (woo) features, and I've been creating some stupid stub modules, and I was hoping there would be a delete/remove command, but there wasn't. Is there any chance of this happening?

**Comment by ac360** [comment]
@DoWhileGeek Good idea!  I just put it in the Road Map for v1.1

**Comment by DoWhileGeek** [comment]
Neat!

**Comment by slajax** [comment]
:+1: it would be also great if we could undeploy individual endpoints and lambdas as well.

**Comment by slajax** [comment]
This additional suggestion might be a bit out of scope for this issue as the focus here is on module deletion and I'm thinking a bit broader. Would it be good to also deal with a situation where someone might (for whatever reason) delete a part of the deployment from within the aws console and not the jaws cli?

Should jaws support syncing changes down that might happen out of the context of the cli project? Would not doing this leave the local project in a broken state with orphaned references to resources that do not exist in aws?

It seems like a simple solution if they delete an endpoint or function would be that you can just redeploy them but what if for example, someone deletes the cloud formation stack through the console? Is this easily regenerated through the cli in the same way the endpoints and functions appear to be? I wasn't clear on this when I tried to go clean up after test deploying a hello world and it seemed like after I deleted the resources from AWS I could not easily redeploy or configure them from the CLI without going through the whole jaws create setup again, which would be less then ideal, if that is the only solution.

**Comment by DALDEI** [comment]
+1 for delete module
+1 for delete project

**Comment by dcrockwell** [comment]
+1 for delete everything

**Comment by DoWhileGeek** [comment]
+1 for delete everything

**Comment by zerocooljs** [comment]
+1 for delete everything
