### ISSUE TITLE
Serverless Deployment Access Denied Failures

### ISSUE THREAD

**Issue by ChrisFord-Ovo** [serverless/serverless#12908]
### Issue description

Hey 
We have just noticed that deployments via serverless deploy have started failing during the initializing phase with the following error

`
Access denied when accessing /serverless-framework/state/s3-bucket SSM parameter and serverless-framework-state-xxxx-xxxx-xxx-xxxx-xxxxxxxxx S3 bucket. Please check your permissions and try again. You have the following options:
• Ensure you have permission to create SSM and S3 resources.
• Use the "state" field to specify an existing S3 bucket.
• Manually create the S3 bucket and SSM parameter.

For more details, please refer to the documentation: https://slss.io/compose-state

Original error: An error occurred while fetching the SSM parameter "/serverless-framework/state/s3-bucket":
`

We arent using a custom s3 bucket for holding state, and as far as i am aware nothing has changed with our IAM permissions.
Deployments were working fine until about 2 or 3 hours ago, I noticed that a new release got rolled out so tried bumping this new version - we were on v4.4.7 - but no luck.  Can you suggest what we might try to troubleshoot / whether its related to the recent releases

Thanks

**Comment by ChrisFord-Ovo** [comment]
Looking into this error further it seems like during deployment the system is trying to access a resource that doesnt exist - or atleast i cant see it 

> Original error: An error occurred while fetching the SSM parameter "/serverless-framework/state/s3-bucket": User: arn:aws:sts::xxxxxxx:assumed-role/xxxxx/xxxx@xxxxx is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:xxxxxxxx:parameter/serverless-framework/state/s3-bucket with an explicit deny in a service control policy

And looking at the recent releases in 4.4.8 there was a feature change around state

**Comment by zhangyb** [comment]
I’m experiencing the same issue. The latest version (4.4.9) seems to default to the us-east-1 region for SSM getParameter, which is causing the problem.

**Comment by ChrisFord-Ovo** [comment]
Thanks for responding @czubocha.  It might be worth considering this as 4.5.0 version or having this fact clearer in the release notes.  I get most users wont have restrictions on regions - particularly us-east-1 - so wont affect them, but it will affect some and there is no obvious indicator in the release notes there could be a issue, I only noticed due to timings.

**Comment by ChrisFord-Ovo** [comment]
Hi @czubocha, we are trying to add a custom state bucket in our serverless.ts config however we are getting a error saying " Invalid configuration encountered at root: unrecognized property 'state'" does this recent PR merge resolve this?  https://github.com/serverless/serverless/pull/12909

**Comment by czubocha** [comment]
@ChrisFord-Ovo Yeah, we're going to release it in a few minutes.

**Comment by s-emerson-kaluza** [comment]
Hey - When specifying an existing S3 bucket as per the state docs I get the below error:

`Error: An error occurred while checking versioning for bucket "XXbucketNameXX": An error occurred while checking versioning for bucket "XXbucketNameXX": The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

It would be great to have a worked example of this change that is breaking to those of us that can't deploy in the US region. Thanks

**Comment by czubocha** [comment]
Hey @s-emerson-kaluza, you need to add the `region` of your bucket to your state config like this:
```
state: my-s3-state-resolver
stages:
  default:
    resolvers:
      my-aws-account:
        type: aws
        my-s3-state-resolver:
          type: s3
          region: eu-west-1
          bucketName: my-custom-state-bucket
```
We'll be adding this case to the State docs shortly.

**Comment by czubocha** [comment]
@ChrisFord-Ovo [v4.4.10](https://github.com/serverless/serverless/releases/tag/v4.4.10) has just been released so you encounter the error anymore.

**Comment by ChrisFord-Ovo** [comment]
I have been look up a little bit about the credential config and I am not sure this guide is right - or I am looking in the wrong place - but https://github.com/serverless/serverless/blob/main/docs/providers/aws/guide/serverless.yml.md#general-settings indicates I can populate resolver inside provider, but I dont think thats a available field - maybe out of date doc?

**Comment by czubocha** [comment]
@ChrisFord-Ovo Sorry for the inconvenience. It seems like the issue arises when the custom state resolver is used in combination with `ssm`, `s3`, or `cf` variables in the configuration.
We’re aiming to release a fix for this on Monday.
For now, you can either
* add `provider.profile` field to use that AWS profile as credentials resolver OR
* prepend all `ssm`, `s3` and `cf` variables with the resolver name (in your case, `awsAccount`). For example, change from `${ssm:example-param}` to `${awsAccount:ssm:example-param}`)OR
* pin the Framwork version using `frameworkVersion` field (see [docs](https://www.serverless.com/framework/docs/providers/aws/guide/services#version-pinning))

> Either way it seems like now we have to define a custom state resolver we now also have to change how our aws credentials get set?

When you have only one `aws` resolver set in `stages` block and you don't have `provider.profile` set, the resolver from `stages` block automatically becomes the credential resolver for deployment. If you want to use another configuration (e.g. another profile) you can
* add `provider.profile` OR
* add another resolver to the `stages` block and specify it using the `provider.resolver` field to select it as the credential resolver for deployment.

To learn more see [the docs here](https://www.serverless.com/framework/docs/providers/aws/guide/credentials#using-resolvers-to-specify-deployment-credentials).

> Out of interest why is the default region for the state buckets us-east-1? Cant it just use the region the stack is deployed in?

The state bucket is shared across all services deployed in the account. This design minimizes the number of additional resources created and simplifies sharing state between services in the account (even across regions) without requiring extra lookups to locate the state store for a specific service. The issue isn’t just the bucket itself but also the SSM parameter where the bucket details are stored. While you could technically put your own bucket details (from your region) into the parameter, the Serverless Framework only checks the SSM in the `us-east-1` region, so this wouldn’t resolve your problem

**Comment by kdybicz** [comment]
This is a breaking change for me too. Fortunately, version pinning seems to work now, and sticking to 4.4.7 seems to be viable workaround for me for now.

**Comment by dekpient** [comment]
We have a problem in the same area, so I think I'll add to this ticket but let me know if I should create a new one.

We've been using our own deployment bucket (managed by our serverless plugin) with a bucket policy that enforces encryption. This causes the put request for `state.json` to fail at the end of each deploy. We cannot relax the policy for compliance reasons.

Will serverless support encryption for the state bucket? Is there a way to disable this state thing (since we're not using it yet) so the deploy doesn't fail? Are we missing something that will fix this issue? Please advice. Thanks.

We've downgraded to 4.4.7 for now. For references, please find the bucket policy, the relevant bits from serverless.yml and the tail end of the deploy logs (from v4.4.11) below:

Bucket policy:
```
{
    "Version": "2012-10-17",
    "Id": "Policy",
    "Statement": [
        {
            "Sid": "EnforceEncryptionMethod",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": [
                "arn:aws:s3:::<BUCKET_NAME_REDACTED>",
                "arn:aws:s3:::<BUCKET_NAME_REDACTED>/*"
            ],
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": [
                        "AES256",
                        "aws:kms"
                    ]
                }
            }
        },
        {
            "Sid": "ForceSSLOnlyAccess",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::<BUCKET_NAME_REDACTED>",
                "arn:aws:s3:::<BUCKET_NAME_REDACTED>/*"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
}
```

We want to use the same bucket for deployment and state storage, so we've tried to define the resolver in serverless.yml according to the doc.

```
state: stateBucketResolver

stages:
  default:
    resolvers:
      awsAccount:
        type: aws
        stateBucketResolver:
          type: s3
          bucketName: ${self:custom.deploymentBucket.name}

provider:
  # .... other things
  deploymentBucket:
    name: ${self:custom.deploymentBucket.name}
    serverSideEncryption: AES256
```

Artifacts uploads and CloudFormation stack deploys successfully, but putting the state.json fails at the end.

```
// ... omitted earlier logs
s:sls:lifecycle:command:invoke:hook: [112]   > aws:deploy:finalize:cleanup
s:sls:lifecycle:command:invoke:hook: [110] > deploy:finalize
✔ Service deployed to stack <NAME> (171s)
endpoints:
  // ... REDACTED
functions:
  // ... REDACTED
Stack Outputs:
  // ... REDACTED
s:main: Finishing
s:core:meta: saving meta record to global .serverless directory.
s:core:meta: saving meta record to global .serverless directory.
s:cli-error-handler: AccessDenied: User: <ARN_REDACTED> is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::BUCKET_NAME_REDACTED/services/traditional/<CFN_STACK_REDACTED>/state/state.json" with an explicit deny in a resource-based policy
    at throwDefaultError (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:88:8019)
    at file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:88:8293
    at de_CommandError (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:186:271685)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:77:25128
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:183:6041
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:88:27574
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:186:106697
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:182:495877
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:182:496431
    at async file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:76:14543
    at async storeDataInS3 (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:186:472634)
    at async Aws.storeData (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:186:994343)
    at async Object.putServiceState (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:983:7843)
    at async runFramework (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:980:3234)
    at async route (file:///Users/<username>/.serverless/releases/4.4.11/package/dist/sf-core.js:1010:14784)
```

**Comment by qmenchaca** [comment]
After experiencing some sudden pipeline failures, I was eventually led here. Without any warning either.

We deploy out our application via Bitbucket pipelines and an IAM user. It makes sense to me that the user deploying via serverless ought to have base IAM permissions to be authorized to access certain resources. It looks like set-up of this predates me during my time at this company.

Digging further through your documentation, it doesn't look like there is a principle-of-least-privilege IAM permission defined anywhere. (If it is defined it certainly is not anywhere obvious.) The recommended ways to set up credentials with Serverless is to either create a new CloudFormation stack from scratch or to use AWS Organizations:

https://www.serverless.com/framework/docs/providers/aws/guide/credentials#production-configuration

Organizations seems like complete overkill for this situation, not to mention something some devs may not even be authorized to do in their professional role. And without any guidance on IAM permissions to grant to roles and policies, you are asking your users to either engage in frustrating trial-and-error or to give very insecure blanket "*" permissions to a lot of services. This seems like a pretty dangerous thing to ask of people using this service.

Can I please be linked a clear list of principle-of-least-privilege IAM permissions serverless requires for deployment so my organization can get our app deployed again?

(I do acknowledge my tone here can be construed as overly aggressive, and I do apologize, I just did not expect to spend as much time on getting our application deployed today, and to still not have a clear path forward on it at the end of the workday is less than ideal.)

**Comment by kdybicz** [comment]
I'm still trying to understand why a patch version introduced such a breaking change. Is this a bug or a feature?

The error you can see below is caused only by a change from Serverless v4.4.7 to Serverless v4.4.12. I'm not using any custom resolvers, and as far as I know, I was not using any means to store the "state" as until now, this doesn't seem to be needed.

Due to my company security policies, I was the "lucky one" mentioned by @qmenchaca to find the "principle-of-least-privilege"-like IAM permissions set on my own. It was then shared across the company. Now, due to state-related changes the deployment and rollback processes of a buch of apps running SLS in my org is failing.

Due to the same company security policies, I doubt if we could get permissions to `ssm:PutParameter` as that would pose an extra security risk, as we're using Parameter Store to keep important information that could be read but shouldn't be possible to be overwritten by the app.

```
Deploying "project" to stage "staging" (eu-west-1)
✖ Stack project-staging failed to deploy (0s)


✖ Access denied when accessing /serverless-framework/state/s3-bucket SSM parameter and serverless-framework-state-xxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbb S3 bucket. Please check your permissions and try again. You have the following options:
• Ensure you have permission to create SSM and S3 resources.
• Use the "state" field to specify an existing S3 bucket.
• Manually create the S3 bucket and SSM parameter.

For more details, please refer to the documentation: https://slss.io/compose-state

Original error: User: arn:aws:sts::abcdabcdabcd:assumed-role/AWSReservedSSO_xzy_abcdefabcdefabcdef/user@somedomain.com is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-east-1:abcdabcdabcd:parameter/serverless-framework/state/s3-bucket with an explicit deny in an identity-based policy
```
