### ISSUE TITLE
Support for Node22 runtime

### ISSUE THREAD

**Issue by faradaytrs** [serverless/serverless#12914]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Node 22 runtime is already available on AWS:
<img width="1191" alt="Screenshot 2024-11-22 at 10 02 38" src="https://github.com/user-attachments/assets/572fd677-2378-4116-a4d9-590a1a2fb917">
But it's still not available in serverless:
<img width="470" alt="Screenshot 2024-11-22 at 10 03 20" src="https://github.com/user-attachments/assets/2dca02e8-1bd1-4787-8c0b-107f1874dd10">

**Comment by acommodari** [comment]
Would this also be backported to sls v3?
