### ISSUE TITLE
Bug in packaging zip-service.js leading to all dependencies being packaged

### ISSUE THREAD

**Issue by ThrowsException** [serverless/serverless#12911]
### Issue description

I noticed when upgrading to v4 my deploys started to fail due to the packaged zip file being incredibly large exceeding 300MB. Digging deeper it appeared that devDependencies were not being excluding noticing packages like jest and sinon were included in the packaged node_modules

in v3 everything seemed to work fine so I dug into trying to find some deltas and stumbled on a refactor of zip-service.js back in April where it the child process was changed from using bluebird to promisify https://github.com/serverless/serverless/commit/158f644cd0099f1a0405b66a63e0d70af35b1a6b#diff-8043dc7aef36d77d3f63c572c183eb39e6af9b71f84bfc9fef1db9110a448cc6R19

I believe this is causing a silent error because this change means that `childProcess.execAsync` is no longer a function instead `childProcess` becomes the promise but it looks like this code was never changed and the .`catch`  around this operations is swallowing the error with Promise.resolve https://github.com/serverless/serverless/blob/main/lib/plugins/package/lib/zip-service.js#L221-L222

It looks like unit tests may be giving false positives as well since the tests stubs `childProcess.execAsync`
https://github.com/serverless/serverless/blob/main/test/unit/lib/plugins/package/lib/zip-service.test.js#L138

**Comment by HzrdIRL** [comment]
I can confirm, we are also experiencing this same issue with v4. if we use the `packages: external` configuration then we get no `node_modules` and if we use `patterns` to bring them in, we get the entire dev dependencies (which we didn't in v3)

**Comment by czubocha** [comment]
The issue has been resolved, and the fix is included in [v4.4.13](https://github.com/serverless/serverless/releases/tag/v4.4.13). Thank you for providing detailed information - it was very helpful. Let us know if you encounter any further issues.

**Comment by ThrowsException** [comment]
@czubocha thanks for addressing this. some initial tests with 4.4.13 look good. bundle size has shrunk dramatically from < 4.4.13
