### ISSUE TITLE
[v3] Node 22 support

### ISSUE THREAD

**Issue by acommodari** [serverless/serverless#12922]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

We would like to also be able to use node 22 on serverless v3

**Comment by throrin19** [comment]
No worries with version 3 of serverless: I've been able to publish my lambdas in node22.x on AWS

**Comment by kabo** [comment]
With
```yaml
provider:
  runtime: nodejs22.x
```

I'm getting
```
Error:
AssertionError [ERR_ASSERTION]: not a supported runtime
    at new AssertionError (node:internal/assert/assertion_error:454:5)
    at assertIsSupportedRuntime (/opt/atlassian/pipelines/agent/build/node_modules/serverless-esbuild/dist/helper.js:249:15)
    at EsbuildServerlessPlugin.getBuildOptions (/opt/atlassian/pipelines/agent/build/node_modules/serverless-esbuild/dist/index.js:245:47)
    at EsbuildServerlessPlugin.init (/opt/atlassian/pipelines/agent/build/node_modules/serverless-esbuild/dist/index.js:127:34)
    at initialize (/opt/atlassian/pipelines/agent/build/node_modules/serverless-esbuild/dist/index.js:60:22)
    at PluginManager.run (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/plugin-manager.js:598:65)
    at async Serverless.run (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/serverless.js:179:5)
    at async /opt/atlassian/pipelines/agent/build/node_modules/serverless/scripts/serverless.js:819:9
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java21, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, nodejs20.x, provided, provided.al2, provided.al2023, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]
```

But reading the error message again this seems to be an issue with serverless-esbuild more than anything else...

Can confirm, after upgrading serverless-esbuild to v1.54.6 it works again
https://github.com/floydspace/serverless-esbuild/releases/tag/v1.54.6

The invalid configuration warning from serverless is just a warning.

**Comment by sebekz** [comment]
While it works, it would be great if we could eliminate warnings so that we don't learn to ignore them. I personally find that getting comfortable with warnings leads to warning fatigue, where we might miss important ones later. 

It would be great to know whether having Node 22 officially supported and listed in the valid runtimes is planned. That would mean a great deal for teams that aren't ready to migrate to v4 yet.

**Comment by throrin19** [comment]
I'm agree with @acommodari

**Comment by kabo** [comment]
Yup, having the same issue as @DemonICOLI on node v22.12, v22.11 works fine.

**Comment by throrin19** [comment]
@kabo, same here. There is a dedicated issue for this : https://github.com/serverless/serverless/issues/12936

**Comment by eudoroolivares2016** [comment]
I still have the issue running
`   "serverless": "^3.39.0",
    "serverless-esbuild": "^1.54.6",` on node `22.12`

**Comment by austencollins** [comment]
We're not adding any new features to V.3 and have moved onto V.4.

**Comment by slootjes** [comment]
The fork of v3 supports v22 just fine: https://github.com/oss-serverless/serverless so I recommend using that instead.

**Comment by throrin19** [comment]
@austencollins this is not a new feature, Since 22.12 it does not works but works correctly before.

**Comment by jackie1santana** [comment]
Just run `npm i serverless@3.40.0` & your problems will go away. You'll be able to run Node 22.

**Comment by serverlesspolska** [comment]
> Just run `npm i serverless@^3.40.0` & your problems will go away. You'll be able to run Node 22.

the warning still remains

**Comment by Mmarzex** [comment]
Hi everyone, 3.40.0 was release to fix an issue blocking you from running framework v3 when your local node version was `22.12`. For the updated runtime for Lambda, you will need to update to v4.
