### ISSUE TITLE
S3 deployment bucket gets created in the default us-east-1 region even if another region is specified. (V4)

### ISSUE THREAD

**Issue by reubenporterjisc** [serverless/serverless#12923]
### Issue description

I am specifying region `eu-west-1` and relying on the default state bucket config. When running a serverless deploy I noticed a new bucket was created in `eu-west-1` but also another bucket was created in `us-east-1` which I can only assume is a bug? I have double checked my config and there is no reference to `us-east-1` anywhere.

**Comment by reubenporterjisc** [comment]
I've also noticed that if an s3 bucket doesn't exist then it is not automatically created, even though it's specified in the docs:

https://www.serverless.com/framework/docs/guides/deployment-bucket#1-deploying-a-new-service

**Comment by czubocha** [comment]
Hey @reubenporterjisc the bucket you saw in `us-east-1` was the State bucket. We've reverted the use of [State](https://www.serverless.com/framework/docs/guides/state) for individual Serverless Framework services in version [v4.4.13](https://github.com/serverless/serverless/releases/tag/v4.4.13). State is now created and used only when using Compose, so in your case, nothing should be created in `us-east-1` anymore. The bucket created in your region (`eu-west-1`) is the deployment bucket mentioned in the [docs you referenced](https://www.serverless.com/framework/docs/guides/deployment-bucket#1-deploying-a-new-service).

**Comment by reubenporterjisc** [comment]
Hey, thanks for the reply @czubocha. Then how come when I manually deleted the bucket, it was automatically created again in `us-east-1` by serverless when doing a deploy to `eu-west-1`?

**Comment by czubocha** [comment]
Could you confirm that you’re using the latest version of the Framework? Additionally, how are you specifying the deployment region?
