### ISSUE TITLE
ap-south-2 region not supported

### ISSUE THREAD

**Issue by chuganilokesh** [serverless/serverless#12953]
### Issue description

while using ap-south-2 region it gives error as below: 

runtime: nodejs18.x

  "dependencies": {
    "aws-sdk": "^2.1410.0",
    "replay-aws-dlq": "^1.0.1",
    "serverless-iam-roles-per-function": "^3.2.0"
  }
  
  npx serverless@3 deploy

at 'provider.region': must be equal to one of the allowed values [us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-iso-east-1, us-iso-west-1, us-isob-east-1, us-west-1, us-west-2, af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ap-southeast-3, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-central-2, eu-north-1, eu-south-1, eu-south-2, eu-west-1, eu-west-2, eu-west-3, me-central-1, me-south-1, sa-east-1]

**Comment by czubocha** [comment]
Hey @chuganilokesh, could you confirm you’re using at least [v3.35.0](https://github.com/serverless/serverless/releases/tag/v3.35.0)? This version introduced support for the `ap-south-2` region.
