### ISSUE TITLE
Support for ap-southeast-5

### ISSUE THREAD

**Issue by Jroon94** [serverless/serverless#12955]
### Issue description

Serverless does not seem to support the AWS region `ap-southeast-5` (Malaysia) which was released in August
the serverless.yml file warns `Value is not accepted` when attempting to set region, and deploying results in 
```
ServerlessError2: An error occurred: HttpApi - null (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException
```

### Context

I'm running version 4.4.16

**Comment by czubocha** [comment]
Hi @Jroon94, it seems that AWS has not yet released AWS API Gateway v2 (HTTP API) in the `ap-southeast-5` region. This is the reason you’re encountering `BadRequestException`.

Here’s a comparison from the API Gateway Console:
* Malaysia (`ap-southeast-5`):
![image](https://github.com/user-attachments/assets/c9bb8952-dbcd-47c7-8bd6-16fbdc825b6a)

* London (`eu-west-2`):
![image](https://github.com/user-attachments/assets/37e937a1-ad01-45c7-a815-2d79fe51d577)
