### ISSUE TITLE
Warning about Node22 runtime in 3.40.0

### ISSUE THREAD

**Issue by lucas-implanta** [serverless/serverless#12963]
## Is there an existing issue for this?
Not that I found, but related to this solved <a href="https://github.com/serverless/serverless/issues/12936#issuecomment-2549292037" target="_blank">issue</a>

## Priority
Likely very low, it's not a bug, but I don't think it should be a warning

## Use case description
Using Node 22.x with Serverless 3.40.0 gives the following warning during the deploy process running `serverless deploy`

```
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java21, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, nodejs20.x, provided, provided.al2, provided.al2023, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]
```
  
But, as stated in <a href="https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html" target="_blank">Aws lambda runtimes</a> docs, the nodejs22.x is currently supported as a lambda runtime.

## Proposed solution 

Perhaps updating this enum with the missing value:
<a href="https://github.com/serverless/serverless/blob/v3.40.0/lib/plugins/aws/provider.js" target="_blank">provider.js</a>

### Context

N/A

**Comment by czubocha** [comment]
Hey @lucas-implanta, we're not adding new runtimes to v3. Support for Node 22 was introduced in [v4.4.12](https://github.com/serverless/serverless/releases/tag/v4.4.12)

**Comment by 300LiterPropofol** [comment]
> Hey [@lucas-implanta](https://github.com/lucas-implanta), we're not adding new runtimes to v3. Support for Node 22 was introduced in [v4.4.12](https://github.com/serverless/serverless/releases/tag/v4.4.12)

Hey! I am wondering do you mean that V3 will not be maintained and updated anymore? So everyone needs to switch to the paid tier of V4 eventually?
