### ISSUE TITLE
Apply Resources naming convention to compiled Lambda functions

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1303]
https://github.com/serverless/serverless/pull/1302 shows the new "naming convention" for created resources. This makes it easier to understand what the resource is generated for (and which relate to each other) when looking at the generated CF template.

It would be great if we maybe also add a `Function` or `Lambda` to the function resource we compile.

So we have `helloLambda` or `helloFunction` instead of `hello` in the Resources section. This way everything follows the same pattern.

This might also mean that we have to update the aws related plugins (although it might not be that hard to refactor).

**Comment by flomotlik** [comment]
Still an issue?

**Comment by pmuens** [comment]
No. I don't think so. We could look into this more in #1627
