### ISSUE TITLE
event deploy failure does not throw error

### ISSUE THREAD

**Issue by jeffastorey** [serverless/serverless#1306]
When there is an event deployment failure, an error is not thrown - only an error message is printed. This is a problem for CI builds since the build will still succeed. An example of an error message is `Configurations overlap. Configurations on the same bucket cannot share a common event type`. Function deploy does throw an error, which is preferable. Event deploy failures should be treated the same way.

**Comment by flomotlik** [comment]
In V1 as everything is deployed through Cloudformation it will cover all of those issues properly.
