### ISSUE TITLE
cannot install npm project with git:// protocol

### ISSUE THREAD

**Issue by jeffastorey** [serverless/serverless#1307]
Trying to install a project such as `serverless project install git://<my-git-repo>` fails, even though `npm` can install handing projects this way. The initial errors occur when trying to symlink directories - errors like `Error: ENOENT: no such file or directory`.

When I look in the directory where I tried to install the project, I see a folder named `git://` was created, which is not what should be happening.

**Comment by flomotlik** [comment]
@jeffastorey we haven't yet created this in V1.0 for installing other projects so I'm closing. Not sure yet how we're going to support this in the future.
