### ISSUE TITLE
Bitcoin donations

### ISSUE THREAD

**Issue by DoWhileGeek** [serverless/serverless#131]
I love this project, and want to see it thrive, so I was wondering if the organization could add a bitcoin address that folks like me could send our monetary thanks to.

What do you guys think?

**Comment by eahefnawy** [comment]
+1

**Comment by dekz** [comment]
Also JAWS stickers that can be purchased! (on stickermule)

**Comment by DoWhileGeek** [comment]
+1

**Comment by doapp-ryanp** [comment]
Thank you very much for the support. We will work on adding one.  Also, we are in process of setting up a teespring campaign.  Stay tuned..
