### ISSUE TITLE
TimeoutError: Missing credentials in config version 0.5.5

### ISSUE THREAD

**Issue by imhassan** [serverless/serverless#1310]
I am getting Missing Credentials when run my function locally. 

`$ sls function run message_to_sqs
Serverless: Running message_to_sqs...  
error: Fail Send MessageTimeoutError: Missing credentials in config
Serverless: -----------------  
Serverless: Failed - This Error Was Returned:  
Serverless: undefined  
Serverless: undefined  
`

But I can upload and deploy this same function successfully. 

`$ sls function deploy message_to_sqs
Serverless: Deploying the specified functions in "prod" to the following regions: us-west-2  
Serverless: ------------------------  
Serverless: Successfully deployed the following functions in "prod" to the following regions:   
Serverless: us-west-2 ------------------------  
` 

Anything that I am missing , please help. It was working perfect a day before.

**Comment by lucasam** [comment]
I am having similar issues regarding to DynamoDB access.

All configs like region and credentials are missing when using function run command.

Apparently the call to dynamodb is not running with the same credentials of the lambda function or the lambda itself is not under any role at all.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
