### ISSUE TITLE
JSON files should have newline character at the end of the file

### ISSUE THREAD

**Issue by jthomerson** [serverless/serverless#1321]
All JSON files written by SLS do not have a newline character at the end of the file. In many git repos, this is considered a whitespace error. I feel like all files written by the project should end with a newline character since that's the POSIX standard. That's described well here: http://stackoverflow.com/a/729795/1011988

I'm using SLS version 0.5.5

**Comment by pmuens** [comment]
Good feedback! Thank you. I would also vote to add a newline character for each file!
