### ISSUE TITLE
Project Init Should Not Rewrite Existing JSON Files

### ISSUE THREAD

**Issue by jthomerson** [serverless/serverless#1322]
I created a project using `sls project create`, and then modified the created JSON files to do the following:

 1. make the indentation match our internal indentation standards (three spaces over the default two that SLS uses)
 2. add a newline character to the end of all files that we commit to our repo (see #1321)
 3. remove unnecessary parameters where the value in the config file was the same as the default or the parameter is otherwise unnecessary

Then I cloned that repo on another workstation and was going to initialize my `_meta` folder by using `sls project init`. The first step that `init` does is apparently rewriting all of my committed JSON files - function configs, templates files, even project.json. This seems entirely unnecessary. It reverts the changes that mentioned above.

For example, this is a snippet of output from `git diff --ignore-all-space` after running `sls project init` and then cancelling it at the first prompt.

```
index efa5912..34ca03e 100644
--- a/src/functions/categories/s-function.json
+++ b/src/functions/categories/s-function.json
@@ -2,9 +2,15 @@
   "name": "v1-categories",
   "runtime": "nodejs4.3",
   "description": "Categories data endpoint",
+  "customName": false,
+  "customRole": false,
   "handler": "categories/Categories.handler",
   "timeout": 2,
   "memorySize": 128,
+  "authorizer": {},
+  "custom": {
+    "excludePatterns": []
+  },
   "endpoints": [
     {
       "path": "v1/categories/{LangCode}",
@@ -30,5 +36,9 @@
     }
   ],
   "events": [],
-   "environment": "$${standardApiEnvironment}"
+  "environment": "$${standardApiEnvironment}",
+  "vpc": {
+    "securityGroupIds": [],
+    "subnetIds": []
+  }
 }
\ No newline at end of file
```

And here's a list of all the files that it changed (note that I replaced actual function names for the sake of privacy, but this is representative of every function).

```
        modified:   package.json
        modified:   s-project.json
        modified:   s-resources-cf.json
        modified:   s-templates.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-templates.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
        modified:   src/functions/one-of-my-functions/s-function.json
```

I don't see any reason that `init` should modify any file - it should be reading from those files, but not writing them.

**Comment by jonascheng** [comment]
I encountered same issue, and it's annoyed to me. In my case, it became worse not just change indentation but also revise cloudfront cache behavior.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
