### ISSUE TITLE
Do not force project.json project name and s-project.json name to match

### ISSUE THREAD

**Issue by jthomerson** [serverless/serverless#1323]
It seems unnecessary to enforce that the project name in s-project.json be the same as package.json. I shouldn't necessarily need to publish under npm (the purpose of package.json) with exactly the same name that I create the resources in AWS with (the purpose of the name in s-project.json).

Tangentially, it's strange to me that SLS rewrites package.json at all since package.json is a file for NPM, not SLS. It should maybe *read* values from package.json, but not necessarily *write* anything there. Can that be considered?

**Comment by mikelax** [comment]
I agree with this. I can't think of a reason why `package.json` would need to be modified at all by any sls commands.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
