### ISSUE TITLE
Ability to add cloudwatch alarms to Lambda events

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#1329]
CloudWatch provide Invocations, Duration, Errors and Throttles metrics for Lambda events, which, depending on how you use Serverless may prove to be worthy items to alert on.

```
"cloudwatch_alerts": [
  {
    "type": "string", # Duration, Errors and Throttles
    "calculation": ''string', # avg, min, max, sum
    "interval": "string", # 1min, 5min, 15min, 1hr, 6hr, 1day
    "duration": {
      "type": "string", # relative, absolute
      "from": "string", # x min/hour/day
      "to": "string" # x min/hour/day
    }
  }
]
```

**Comment by flomotlik** [comment]
You should be able to do this in V1 through custom resources.

**Comment by kkozmic-seek** [comment]
Hey

Is any of that in RC1. I can't find any documentation regarding logging/alerting.

**Comment by flomotlik** [comment]
@kkozmic-seek we don't have built in support for it yet, but you can create it through custom resources: https://github.com/serverless/serverless/blob/master/docs/01-guide/06-custom-provider-resources.md

Basically this: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html

**Comment by schickling** [comment]
This plugin by @johncmckim seems like a great way to do it :)
https://github.com/ACloudGuru/serverless-plugin-aws-alerts

**Comment by pmuens** [comment]
> This plugin by @johncmckim seems like a great way to do it :)
> https://github.com/ACloudGuru/serverless-plugin-aws-alerts

Yes, that should do the trick! Thanks for sharing @schickling 👍
