### ISSUE TITLE
Add random test order / automatic tests detection

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1337]
Currently we have an `all.js` file which contains all the tests in ordern.

However tests should be independent from each other. It would be great to add the functionality to run tests in a random order and auto discover them so that we don't have to require them by manually (and therefore don't miss a test).

**Comment by colbywhite** [comment]
Just as FYI for the next dev who comes along this, it appears there is work going to add a `--order random` option to mocha (mochajs/mocha#902). Then you could just add that into your `npm test` command. (I was kind of surprised that wasn't already in there.)

**Comment by pmuens** [comment]
A quick update on this one: Will be resolved once #2716 is merged.

**Comment by pmuens** [comment]
Closing this as #2716 has just been merged
