### ISSUE TITLE
Make sure we can load both `.yaml` and `.yml` extensions

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1342]
Right now we only support loading of `.yaml` files.

`.yaml` is the "official" file extension but it's more common to have `yml` files. We should switch all our templates files and docs to `.yml` but also support `.yaml` files.

- [x] docs
- [x] templates

**Comment by pmuens** [comment]
Might be related to https://github.com/serverless/serverless/issues/1186

**Comment by eahefnawy** [comment]
Okay I just tested this .... JSON-REF works whether we're referencing a `.yaml` or `.yml` ... we just need to update our codebase to support both when loading our core config files.

**Comment by pmuens** [comment]
Awesome. Additionally I would suggest to make `.yml` the default (rename all our template files etc.).

**Comment by pmuens** [comment]
Will be closed with #1618
