### ISSUE TITLE
pass a static string as request parameter

### ISSUE THREAD

**Issue by simoami** [serverless/serverless#1346]
I have a function that handles 2 routes (multi method function). The paths are:
/users/list (GET) - fetches a list of users
/users/{id} (GET) - fetches a specific user by id

I'd like for the function to know which route triggered it. Notice that in this case the http method is GET for both, so that's not sufficient to identify the origin.

My first thought is to pass a static string in each endpoint's requestParameters. Like so:

```
"endpoints" : [
  { 
    "path": "users/list",
    "method": "GET",
    "requestParameters": {
      "integration.request.body.method" : "'listUser'"
    },
    ...
  },
  { 
    "path": "users/{id}",
    "method": "GET",
    "requestParameters": {
      "integration.request.body.method" : "'getUser'"
    },
    ...
  }
]
```  

According to the [AWS docs](http://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#mapping-request-parameters), supplying a static value is supported, however I get an error on deployment:
```
GET - users/{id}: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: 'getUser'] 
```

Any ideas?

**Comment by jackrk** [comment]
Static values are only allowed for path/querystring/header parameters on the Integration Request. The 'body' location can be used when mapping from the incoming body to an outgoing parameter like 'method.request.body.foo' -> 'integration.request.header.foo'. Sounds like you want to build a mapping template for the integration. You can set static values in templates or inject request parameters there.

**Comment by simoami** [comment]
An example config for those would be greatly appreciated. What I did in the time being is add an internal router in the lambda function to identify multiple get routes

**Comment by simoami** [comment]
Any other hints?

**Comment by flashsnake-so** [comment]
why don't do this in request template mapping?

```js
...
"requestTemplates": {
    "method" : "STATIC_VALUE"
}
...
```

**Comment by archi0112** [comment]
> method

Why do you have method as the name? 

I tried in Yaml with this format and it worked:

```
RequestParameters:
      integration.request.header.Authorization: "'Static_value'"
```
