### ISSUE TITLE
Request Payload replaces `event` in lambda handler function

### ISSUE THREAD

**Issue by cspeer** [serverless/serverless#1349]
Serverless Version: 0.5.6

I just created a new project with https://github.com/serverless/serverless-starter exactly as described in the README. Then deployed it to AWS and called the `single` endpoint with a `POST` request at:
https://chr5ky4fej.execute-api.us-east-1.amazonaws.com/dev/single

The response was exactly as expected:
```json
{
  "message": "Your Serverless function ran successfully via the 'POST' method!"
}
```

However, if I pass along a valid json string as simple as `{}` the response is as follows:
```json
{
  "message": "Your Serverless function ran successfully via the 'undefined' method!"
}
```
(Notice it says "'undefined' method!")

So, I poked around a little and what I found was that in case a raw json string is passed along, the `event` attribute from the lambda handler function is no longer an event object, it becomes the parsed version of the json string.

Is this a bug or expected behaviour?

Thanks,
Chris

**Comment by eahefnawy** [comment]
@cspeer thanks for reaching out. The serverless-starter project is pretty outdated at this point, and we're not planning to update it until we release v1.0. That's probably the issue.

Sorry about that :/

**Comment by cspeer** [comment]
No worries. I was confused that the event object can hold so different information depending on the request data. And since I experienced this "problem" in one of my own projects as well I think this is a serverless issue rather than one of the starter project. As soon as I send some payload along the `event` object no longer holds the information set by `requestTemplates`.

So, is there a roadmap for v1.0? :)

**Comment by cspeer** [comment]
So, this is a real issue now.
I'm building a REST API, thus for example PUT /Customer/{some-customer-id} with the following `requestTemplates`:
```json
{
"application/json": {
      "id": "$input.params('id')",
      "payload": "$input.json('$')"
    }
}

should give me an `event` object of roughly:
```json
{ "id": "{some-customer-id}", "payload": "{the-payload-i-sent-along}" }
```
, right?
But it doesn't :(
`event` now only holds whatever the payload is.

**Comment by cspeer** [comment]
Forget it... I'm an idiot. I forgot to set the request type. Thus the passthrough kicked in and my mapping was ignored, obviously. So, never mind.
