### ISSUE TITLE
function1: Function not found

### ISSUE THREAD

**Issue by sean-hill** [serverless/serverless#1350]
After trying to deploy my first function I get this issue after running `serverless dash deploy`:

    Serverless: Deploying endpoints in "dev" to the following regions: us-west-2
    Serverless: Failed to deploy endpoints in "dev" to the following regions:
    Serverless: us-west-2 ------------------------
    Serverless:   GET - function1: Function not found: arn:aws:lambda:us-west-2:049840008342:function:glance-lambda-function1:dev
    Serverless:
    Serverless: Run this again with --debug to get more error information...

I'm not exactly sure what the issue is here?

**Comment by sean-hill** [comment]
It's because I didn't deploy the function, just the endpoint 👊

**Comment by sul4bh** [comment]
@sean-hill can you please describe how you fixed this? I ran into the same issue.

**Comment by sul4bh** [comment]
@pmuens yes, I am using serverless 1.

Here is my error message:

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (52.33 KB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: SendUnderscoretoUnderscorecircleciLambdaFunction
     - Function not found: arn:aws:lambda:us-east-1:873922865494:function:placelocalci-prod-send_to_circleci.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.3.0
```

I was able to deploy to `prod` after removing both `dev` and `prod` stages using `sls remove`

I will try to recreate this issue and file a bug report if I am able to.

**Comment by pmuens** [comment]
@sul4bh thanks for getting back.

Yes, it would be great if you could re-open another issue if you face this bug again! 👍
