### ISSUE TITLE
Remove namespacing in generated CloudFormation resources

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1357]
We've introduced some namespacing rules for generated CloudFormation resources in https://github.com/serverless/serverless/pull/1302

However they are tedious and not that easy to follow. We need to refactor those namings to make them shorter and less a convention.

**Comment by codepreneur** [comment]
Please dont introduce any more breaking changes...

**Comment by eahefnawy** [comment]
@codepreneur we're still in Alpha, breaking changes are unavoidable and expected :)

**Comment by flomotlik** [comment]
@pmuens is this still an issue?

**Comment by pmuens** [comment]
No. We'll discuss this in #1627
