### ISSUE TITLE
Remove unnecessary tmp filesystem usage in tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1362]
Some tests (such as `updateStack.js` in `aws/deploy`) rely on the temporary file system to write the `serverless.yaml` file to it.

This might be necessary for some / few tests but should be removed whenever possible (to speed up testing and don't pollute the users machine with unnecessary files and folders).

**Comment by eahefnawy** [comment]
@pmuens I think the OS takes care of removing tmp dirs after couple of days or something ... I guess that's why the method is called `os.tmpdir()`.

**Comment by pmuens** [comment]
Yes. True. When I was reviewing https://github.com/serverless/serverless/pull/1352 I saw some usage to write e.g. `serverless.env.yaml` and `serverless.yaml` to the file system to reference e.g. `environment` variables where a mock object would also do the trick.

Just want to make sure that we go with mock objects whenever possible to speed things up a little bit.
