### ISSUE TITLE
sls events deploy leaves AWS Lambda function in inconsistent state

### ISSUE THREAD

**Issue by assaflavie** [serverless/serverless#1373]
After deploying a Lambda function via sls 0.5.6 (in a VPC, if that matters), I tried to deploy a cron event for it using the following in `s-function`:

```
  "events": [
    {
      "type": "schedule",
      "name" : "cron_event",
      "config": {
        "schedule": "rate(5 minutes)",
        "enabled": true
      }
    }
  ],
```

Afterwards, AWS Lambda's web console refused to show the event sources for that function (it showed an error box). Removing the event via sls did not change things. The Lambda function was effectively "broken" and I could not get it to clean up its internal state until I deleted it and recreated it.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
