### ISSUE TITLE
Add logResult to evt.data.result in FunctionRun

### ISSUE THREAD

**Issue by plbrault** [serverless/serverless#1398]
In the `_runDeployed` method of the `FunctionRun` action, I think `logResult` should be added to `evt.data.result` when available, so it can be used by plugins to extract useful information about the function execution (ex: get the billed duration).

I can create a pull request for that.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
