### ISSUE TITLE
Clean up contributor files

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1399]
The contributor files and experience could be a bit better:

* CONTRIBUTING.md:  This is overwritten.  Excessive words should be cut, and simple bullet points should be emrbaced.
* ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md:  These aren't currently templates.  Templates would be more useful because the user knows what to write and where to write it.

**Comment by pmuens** [comment]
Resolved with https://github.com/serverless/serverless/pull/1400
