### ISSUE TITLE
Problem deploying new endpoints of a different resource - method not created

### ISSUE THREAD

**Issue by jodagm** [serverless/serverless#140]
I created a clean jaws project
```
jaws new module users list
jaws dash (deployed both lambda & endpoint)
```

opened API GW console and saw the new endpoint
/users/list

```
jaws new module organizations list
jaws dash (deployed new lambda & endpoint)
```

opened API GW console and saw that only /organizations resource was created, without the list method.

then I tried the following:
1) deleted the API from the console
2) deleted restApiId from the project's jaws.json

deployed bother lambdas and endpoints again.
now I see the /organizations/list but  /users has no methods

**Comment by ac360** [comment]
@jodagm Thanks for this.  I'm going to implement some API Gateway improvements tomorrow, this is on my list.

BTW:  You've been very helpful reporting issues.  It's appreciated :)

**Comment by jodagm** [comment]
Thanks @ac360 
You are working 24/7 on this framework, I'm working 24/7 on building a production system based on it ;-)

**Comment by ac360** [comment]
Found the issue.  JAWS isn't trained to handle APIG resources with the same path (2 "list" resources).  Fixing it now.

**Comment by jodagm** [comment]
Awesome!
Thank you for letting me now.
