### ISSUE TITLE
Add support for more config options for APIG

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1408]
Right now our API Gateway support only takes a `method` and `path` options, which is pretty simple. For practical APIs however we might need the following APIG features:

- [ ] [Response & Request VTL Templates](https://github.com/serverless/serverless/issues/1593)
- [x] [CORS](https://github.com/serverless/serverless/issues/1596)
- [x] [API Keys](https://github.com/serverless/serverless/issues/1595)
- [x] [Custom Authorizers](https://github.com/serverless/serverless/issues/1594)
- [ ] [~~Caching~~](https://github.com/serverless/serverless/issues/1597)
- [x] [Proxy](https://github.com/serverless/serverless/issues/1598) (via CF)

**Comment by flomotlik** [comment]
This can be closed as we have a separate task for the one missing thing.
