### ISSUE TITLE
Add additional information which service needs a subscription

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1415]
I thought I activated all I need to deploy a Serverless service. I'm still getting this error and don't have an idea on the next steps.

Some information on which service I'm missing would be useful.

```
➜  my-app git:(v1.0) ✗ ../bin/serverless deploy                                
  Serverless Error ---------------------------------------
 
     OptInRequired: The AWS Access Key Id needs a subscription for the service
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
```

**Comment by eahefnawy** [comment]
for better UX, we can catch the error message and add to it the exact service we're trying to use and notify the user that they need to activate it.

**Comment by Savalas** [comment]
I am having the same issue. Figured that I would attach to this issue instead of creating a new one. 

It would be helpful to know what I need to OptIn to

  Serverless Error ---------------------------------------
 
 
  Error --------------------------------------------------
 
     ServerlessError: OptInRequired: The AWS Access Key Id
     needs a subscription for the service
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.

**Comment by flomotlik** [comment]
Adding docs for this in #1904 so during provider setup people will make sure that they have a credit card set up and they can find this specific error message in the docs. Don't think we need to put more time into it than the docs.

**Comment by ifyoumakeit** [comment]
In my case, it was finishing the EC2 setup that removed the error. I already had a credit card on file.

**Comment by flomotlik** [comment]
@ifyoumakeit not sure what the "EC2 setup" is? Could you elaborate, as it would be super helpful to know other ways how this might go wrong.

**Comment by ifyoumakeit** [comment]
Somehow, despite having billing information and multiple S3 buckets in use for a couple of years, I had never finished the "Amazon Web Services Sign Up" for this account.

![image](https://cloud.githubusercontent.com/assets/3998604/18057238/17c6ee5a-6ddd-11e6-855d-d234fb78fcd7.png)

Opening up https://console.aws.amazon.com/ec2/ (and probably some other services) re-kicked off that sign up process and got me past the Serverless error.

**Comment by flomotlik** [comment]
Aaaaaah ok, thats good to know. I think they changed this at this point where you're simply not able to get through to any service without finishing this setup. So I assume this is a problem for older accounts only.

**Comment by gechleng** [comment]
I have finished this setup, but I still get the error the same thing. Does it have other way to solve it?

**Comment by chathurank** [comment]
I'm getting the same error. I have completed setting up the billing and I have deployed Lambda functions through the AWS management console. But when I run `serverless deploy` on my mac I'm getting this error.

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  ServerlessError: The AWS Access Key Id needs a subscription for the service

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.3
     Serverless Version:     1.25.0
```

Are there any other reasons that might cause this error?

**Comment by Abdul-majid-ashrafi** [comment]
ServerlessError: The AWS Access Key Id needs a subscription for the service 

getting error.
How can I deploy from free tier account?

**Comment by douglas-mason** [comment]
I recently ran into this issue.  This was a new account and it was verified.  I had to go into dynamobDB and create a dummy table.  After I did that, I was able to deploy.  I think by creating the table it associated the account with a subscription service.
