### ISSUE TITLE
Print out app id, stage, region(s) after deploy

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1416]
This would be super useful to for one have confirmation that my last action worked as expected, but also helps a great deal to continue further. 

```
➜  my-app git:(v1.0) ✗ ../bin/serverless deploy
```

@pmuens @eahefnawy what would be also very interesting is a plugin with commands to get out the APIs and other basic, but interesting information about my deployed apps …

**Comment by flomotlik** [comment]
This is a duplicate of #1468 , closing here and we'll keep discussing it there. Completely agree on this though.
