### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1436]
It would be great to implement Go support (maybe through a shim).

**Comment by license2e** [comment]
Seems like it would be easy as a plugin..

Examples:
http://blog.0x82.com/2014/11/24/aws-lambda-functions-in-go/

**Comment by pmuens** [comment]
Yes. We're about to add it with the help of a Shim.

Thanks for the link!

**Comment by license2e** [comment]
@pmuens I have this template ready to go pending the merge of https://github.com/serverless/serverless/pull/1644

**Comment by pmuens** [comment]
Great @license2e! We'll review #1644 ASAP and merge it soon!

Maybe @mthenw can chime in here as he's also working on a Serverless Go plugin!

**Comment by license2e** [comment]
Oh awesome, @mthenw let me know how I can help... Or if you want to schedule a quick hangout collaborate on this...

**Comment by license2e** [comment]
@pmuens @mthenw I submitted a pull request: https://github.com/serverless/serverless/pull/1680

**Comment by pmuens** [comment]
Damn @license2e you totally rock 🚀 💃 

Thank you for this awesome contribution (and all the other things you've done!) 🎉

**Comment by flomotlik** [comment]
Closing this issue for now as Go support is currently not possible on AWS without some hacky workaround and I don't think we want to move there at the moment. We can reopen once Go becomes available natively on AWS.
