### ISSUE TITLE
Wrongly named lambda function in API gateway method setup

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#1437]
I managed to setup and deploy lambda function `keboola-developer-portal-auth` but when I deploy endpoint to API gateway, I see in aws console (in Integration Request section) it is connected to lambda function `keboola-developer-portal-auth:${stageVariables.functionAlias}` and API calls do not work. It looks like there should be something different from `${stageVariables.functionAlias}`, probably `dev` stage but I don’t know where to specify it further. `sls endpoint deploy` command tells me "Deploying endpoints in "dev" to the following regions: us-east-1” so I guess the stage is set right. Am I missing something or might it be a bug?

I use serverless 0.5.6 with npm package cognito-helper to handle user auth with Cognito.

**Comment by gregorskii** [comment]
+1

**Comment by JakubMatejka** [comment]
@gregorskii You mean, you added `"functionAlias": "dev"` to s-variables file in `_meta/variables`? This doesn't work for me too.

**Comment by gregorskii** [comment]
When I run it from the application gateways page it requires me to type in dev as a stage variable.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
