### ISSUE TITLE
Better support for nested commands

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1445]
Nested commands (such as `serverless deploy function`) are not properly supported ATM.

Some of the logic only handles a maximum of two level deepness (there are `TODO` comments in the source code to find those parts more easily).

We should implement recursive lookups there to support any level of command deepness.

**Comment by pmuens** [comment]
Related to #1276

**Comment by flomotlik** [comment]
Imho 2 levels are fine, no need for more. Makes sure we don't end up with something like 

`serverless look at this shitty long command that nobody understands --whatever blabla`
