### ISSUE TITLE
Print a . while loading (instead of implementing a spinner)

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1446]
We should append a `.` in the terminal while Serverless is loading / doing it's thing (e.g. deploy a CloudFormation stack) instead of printing a message each time.

**Comment by pmuens** [comment]
This might help with the implementation:
http://stackoverflow.com/a/11600998

Otherwise we can print a `.`, use the readline module to see how many `.` are already printed (e.g. 4) and then just add another `.` and repeat. This way we don't have to keep variable to store how many `.` are already printed..

**Comment by flomotlik** [comment]
So for a first simple implementation we could create a short method that prints a message first and then in a defined timeframe prints . . . . . .

So e.g.

```
Waiting for Cloudformation deployment . . . . . . . . . . . . . . . 
```

What do you guys think about this? @tobyhede would be interesting to get your opinion

**Comment by flomotlik** [comment]
Imho this should work for the implementation: process.stdout.write(chalk.yellow('.'));

**Comment by pmuens** [comment]
Sounds like a good, minimalistic solution! 👍

**Comment by eahefnawy** [comment]
Yep that should work 💃
