### ISSUE TITLE
Support for all cloudwatch event rules, not just scheduled

### ISSUE THREAD

**Issue by JSeed** [serverless/serverless#1450]
It would be nice if serverless had support for all cloudwatch event rules, as api calls can be really useful event sources for lambda functions.
I have taken a look at the code for scheduled events, and it looks like it would require minimal modifications.  To create a non-scheduled event source, you simply supply a EventPattern parameter instead of (or as well as) the scheduled expression.  This pattern could be set in s-function.json, just as schedule expressions are currently handled.  
Since it it such a small change (at least at first glance), I am prepared to make a PR, but would appreciate some advice on how to approach the change.
~~In my opinion, It wouldn't make much sense for the event type to continue to be called 'scheduled' if this support is implemented, but I fear that changing it to 'cloudwatch' would break existing implementations.  
We could simply include another event type for event patterns, but it would essentially be a complete copy of EventLambdaScheduled with a few lines changed, which seems silly.~~  
_Edit: After taking a closer look at how event types are handled it seems that multiple event types can be mapped to the same subAction.  This means that EventLambdaSchedule could be renamed to EventLambdaCloudwatch (or whatever name is deemed appropriate) without breaking existing implementations._  

Any thoughts?

**Comment by pmuens** [comment]
Hey @JSeed 
Thank you for your feedback and your research! Really appreciate it.
We're currently working on Serverless v1 (https://github.com/serverless/serverless/tree/v1.0) where we've already implemented some event sources and are listening for user feedback on what else events should be supported. Your feedback is a perfect fit here.

I put it on the v1 milestone so we can look into it during v1 development.

I'd also encourage you to download v1 alpha and test it out. We've implemented a new plugin system which makes event implementation quite easy.

**Comment by JSeed** [comment]
Took a quick at v1, looks like some good stuff!  
It's worth noting that this issue also applies to v1, with the cloudwatch events being limited to scheduled (though my approach to solve this is probably no longer valid).

**Comment by pmuens** [comment]
Thank you for the feedback! We're added it to the v1 milestone so that we can come back to this when we'll implement more event sources.

**Comment by JSeed** [comment]
Out of curiosity are you guys open to PRs on the v1 stuff?
I have a lot of experience with event sources from previous projects, I may be able to help out with a few

**Comment by pmuens** [comment]
Absolutely! Would be awesome if you could submits PRs!

We have a documentation for developing plugins you may look into: https://github.com/serverless/serverless/tree/v1.0/docs/developing-plugins

This way you can add new events easily!

**Comment by flomotlik** [comment]
Closing this specific issue, but we'd love to have more event support either through plugins or documentation in custom resources.
