### ISSUE TITLE
DRY out supported providers array

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1454]
Right now we have the same array with supported provider twice in our code.
The first time it's in the service class, the second time it's int he create plugin.

It's used to check if the provider is supported. This array should be made globally available so that we only have to update it at one place if a new provider will be added.

**Comment by eahefnawy** [comment]
We can put it in the AWS SDK file (along with valid regions), but that would cause a dependency on the create/service files to AWS, and we wanted to avoid that. We can also keep it in the Utils, but then again we agreed we shouldn't mention anything about providers in the core. So I got a little stuck here.

Open for suggestions...

**Comment by pmuens** [comment]
Good and valid points points!

What i meant was this array https://github.com/serverless/serverless/blob/v1.0/lib/plugins/create/create.js#L51-L53

Thought it was duplicated in the `Service.js` class until I realized it wasn't today.
So it's not relevant anymore!

Sorry for the confusion.
