### ISSUE TITLE
Reduce size of coreBucket (only store X function .zips)

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1456]
Right now the function will be zipped and uploaded to the S3 bucket every time a `serverless deploy` is issued. We should only upload changed functions and only keep e.g. the last 10 versions.

**Comment by codepreneur** [comment]
does that mean `serverless-optimizer-plugin` wont be needed anymore?

**Comment by pmuens** [comment]
Will be resolved with #1477

**Comment by pmuens** [comment]
@codepreneur In case of bucket cleanup yes. But we'll just remove old functions upon deployment. Using Babel / exclude logic etc. won't be supported. At the end of v1 we'll look at all the plugins and rewrite the so that they work with the new v1 plugin system.

**Comment by codepreneur** [comment]
@pmuens do you have an estimate on when Babel / exclude logic will be supported (either natively or via a plugin)?

**Comment by pmuens** [comment]
@codepreneur unfortunately not now. We'll revisit our plugins soon after the initial implementation of v1 is finished. We'll post updates as issues.
