### ISSUE TITLE
Make coreBucket name unique

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1458]
The coreBucket name now includes the region, stage and name of the service. We might also introduce a timestamp (or the account number) so that names won't collide as S3 bucket names should be globally unique.

**Comment by pmuens** [comment]
Turns out that a timestamp is a bad solution for this one as it's not predictable.

We need to use the `bucketName` in different plugins (e.g. in the `deploy` but also in the `remove` plugin). A timestamp makes it impossible to recreate the correct bucket name.

@eahefnawy Any ideas on this one? Should we add some AWS account information here which is ensured that we can access it?

**Comment by pmuens** [comment]
We could use the CloudFormation "Output" property to get the bucket name. This way we can use a timestamp in the name which might be unpredictable but unique.

**Comment by pmuens** [comment]
We'll be adding a timestamp to the name of the `coreBucket`.

We'll then use `describeStack` to get the bucketName back (this is e.g. used in thw AWS `deploy` and `remove` plugin). There's no need for an output parameter as we'll have access to the stack information with the help of `describeStack` anyway.

**Comment by pmuens** [comment]
@eahefnawy @flomotlik 
Just finished the renaming of the bucket. I've created a `getCoreBucketName` method inside the `AWS SDK file`. Works like a charm except one thing. Here's how the deployment works and the problem it introduces:

1. Serverless will read the Core CloudFormation template from the file system
2. A unique coreBucket name will be created (`serviceName-stage-region-timestamp`)
3. Serverless will does it's thing and deploys everything

Now let's pretend we've changed something and want to redeploy:

1. Serverless will read the Core CloudFormation template from the file system
2. A unique coreBucket name will be created (`serviceName-stage-region-timestamp`)
...
And here's the problem. It will create a new timestamp (because the time of the redeploy is different than the one of the initial deployment).
Serverless will therefore create a new core bucket (because the timestamp introduces a new name).

So we could not add a timestamp or something random. It needs to be predictable so that we can always recreate the core bucket name.

An idea would be to add the AWS account number or something other (which is predictable) to the `coreBucket` name.

Any ideas?

**Comment by danhumphrey** [comment]
How about a user specified namespace? I know you want to avoid configuration, but maybe it's warranted in this instance?

**Comment by pmuens** [comment]
@danhumphrey thank you for your input.

We've decided to let Amazon pick the bucket name for us. This ensures that the bucket name will always be unique and that we don't run into the issues described above.

You can see the corresponding changes in the PR #1544

**Comment by flomotlik** [comment]
@danhumphrey you mean letting the user specify the bucket name? Definitely something we want to do in the future (and very easy for us to implement). We mainly want to learn more about this from users to better understand your specific needs before we move on the implementation. Could you describe what the reasons would be for you to set up a specific bucket name and what your internal policies are?

**Comment by pmuens** [comment]
Implemented with https://github.com/serverless/serverless/pull/1544

Feel free to continue the discussion about it!
