### ISSUE TITLE
Check Resource names / keys before merging them into the CloudFormation template

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1459]
Resources with the same name will overwrite resources which were previously added in the deployment process.

We should throw an error that two Resource keys cannot have the same name / key.

**Comment by eahefnawy** [comment]
Is there a usecase for this? when did you face this issue? Imo I think we should strive on making our resource names just unique. Keeping track of **all** the resources logical keys that we add will be challenging, specially that most of them are influenced by how users name their functions/APIG paths & methods...etc

**Comment by pmuens** [comment]
Yes. This might be just a minor tweak but could be helpful if we throw a corresponding error.

I faced the issue when I reused a resource name from the CloudFormation template while adding custom provider resources through the services resource section.

**Comment by pmuens** [comment]
Done with full merging support (corresponding PR is: https://github.com/serverless/serverless/pull/1844)
