### ISSUE TITLE
Documentation on how to deploy to another stage and region

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1460]
Documentation regarding deployment to another `stage` and `region` is not available right now.

It should be added to make it more understandable what needs to be done to deploy somewhere else.

**Comment by pmuens** [comment]
Should be done after / alongside #1467

**Comment by bart-blommaerts** [comment]
Also, when creating a new service, using the default AWS region from ~/.aws/config. Similar to ~/.aws/credentials.

**Comment by eahefnawy** [comment]
Resolved with [PR 1668](https://github.com/serverless/serverless/pull/1668)
