### ISSUE TITLE
Serverless info plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1468]
It would be e.g. interesting to get resource related information such as the URL to the Api Gateway or other information printed out on the console after a successful deployment.

**Comment by ac360** [comment]
Huge +1 on this.  Deploying is very underwhelming right now.  Would love to see something like this:

```
endpoints:
POST - users/create

functions:
usersCreate: functionARN...

resources:
dynamoDbTable

```

**Comment by eahefnawy** [comment]
That's beautiful @ac360 ! of course this list will just reflect `serverless.yaml` and `serverless.env.yaml` since we don't have a way to "partially" deploy something. But it's a nice summary.

**Comment by pmuens** [comment]
Great! We could implement this with the help of CloudFormation "Outputs"

**Comment by flomotlik** [comment]
Yup agreed in general and on the specific point @ac360 was making about this being a separate plugin. It could simply hook into the after deployment phase and also provide a separate command to list all those output variables, so you don't actually have to run deployment to see them.

Then each compile event plugin could simply add corresponding output variables and you get a nice overview on everything. Super helpful for APIG endpoints for example.

@bennybauer looks like you've already started implementing this?

**Comment by pmuens** [comment]
🎉  really like the idea of having this in an encapsulated plugin! That's a really powerful way to show the related configuration and we can extend it easily later on without having to touch the core codebase.

**Comment by bennybauer** [comment]
@flomotlik yeah, I started writing something, but I should re-implement most of it with the "Outputs" approach as @pmuens suggested.

**Comment by flomotlik** [comment]
@bennybauer awesome, if you need any help with anything let us know. Happy to help or give feedback, also on an in-progress PR if you want to share early or share your design choices in here.
