### ISSUE TITLE
Remove iamRoleArnLambda

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1469]
Remove the reference to the `iamRoleArnLambda` as it's not needed anymore (was used to check whether the stack was successfully deployed).

**Note:** The AWS account number should be kept as many users have requested it.

**Comment by eahefnawy** [comment]
We currently need the AWS account number to construct the Lambda Uri. However, another way to do it without the account number is to use CF join function. Something like:

```
"Uri" : {"Fn::Join" : ["", [
                  "arn:aws:apigateway:",
                  {"Ref" : "AWS::Region"},
                  ":lambda:path/2015-03-31/functions/",
                  {"Fn::GetAtt" : ["${serviceName}-${
            stageName}-${functionName}", "Arn"]}, "/invocations"
                ]]},
```
