### ISSUE TITLE
Configuration re-use

### ISSUE THREAD

**Issue by whatupdave** [serverless/serverless#147]
There's a lot of repeated configuration throughout a JAWS project in the various JSON files. For example I have a multiline RequestTemplate that I need in multiple modules. It would be awsm if I could define that once and reuse it.

Personally I like the approach that webpack uses by allowing configuration to be javascript files that can require other files. An example webpack config might look like this:

```
module.exports = require("./makewebpackconfig")({
  hotServer: true
});
```

You can see with that approach you could completely DRY up those files and be able to do funky things like load my own code and introspect it. For example I could look at the directory names my handlers are in and map those to the right HTTP method for that action.

**Comment by joostfarla** [comment]
Swagger uses this thing called JSON Reference. Could this be a solution?

More info: http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-02

**Comment by doapp-ryanp** [comment]
We went JSON because JAWS is going to (soon) support all languages that Lambda does (more coming out soon).  @joostfarla that sounds very intriguing.  I will take a look.

**Comment by flomotlik** [comment]
In the new version of Serverless that we will release over the next months we'll unify the configuration in one file.
