### ISSUE TITLE
Possibility to specify template on service creation

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1470]
The user should be able to create a service based upon a template like this:
`serverless create --name my-service --template aws-java-maven` or this: `serverless create --name my-service --template aws-node43`.

**Note:** This also implies that Services are runtime bound (one service only supports one runtime)

The templates should live in our core framework (might be moved to somewhere else such as an own npm package later on).

Here's an example of the directory structure:
```
templates
  |__aws-node43
  |__aws-node
  |__aws-python
  ...
```

The syntax for subfolder is `PROVIDER-LANGUAGE-BUILDTOOL` (where BUILDTOOL isn’t necessary for each language, but e.g. necessary for java).

Each template folder also includes `serverless.yaml` and `serverless.env.yaml`.

**Aside:** Templates might also be "installed" with the help of a `gitUrl` later on so that users can point the template option to their repository when they don't want to go with core ones.
The serverless command name might change to something different like `serverless scaffold` or `serverless install`.

Related to: https://github.com/serverless/serverless/issues/1452

Corresponding PR is: https://github.com/serverless/serverless/issues/1470

**Comment by pmuens** [comment]
I think that this issue needs to be resolved until we can jump in the implementation of different programming languages / providers.

/cc @eahefnawy @flomotlik

**Comment by flomotlik** [comment]
Agreed, Imho goal for next week.

**Comment by pmuens** [comment]
Sounds good. Added it to the weekly goals.

@eahefnawy would you jump on this (as you already had an implementation in mind the other day) or should I take it?

**Comment by flomotlik** [comment]
@pmuens Sorry I might have been unclear, imho we should implement this in the next sprint, so starting on Tuesday

**Comment by pmuens** [comment]
Yep. Updated the weekly goals accordingly.

Notice that we should discuss https://github.com/serverless/serverless/issues/1517 before starting this one.

**Comment by pmuens** [comment]
@eahefnawy the service now has a `runtime` property you should be aware of (see https://github.com/serverless/serverless/pull/1536).

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1537
