### ISSUE TITLE
The ${project} variable

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [serverless/serverless#1474]
The documentation uses at several points the variable ```${project}```. But in my project, when I use this variable I get:

```
Serverless: WARNING: This variable is not defined: project  
```

What could I be missing? This is my s-project.json:

```
{
  "name": "my-project-name",
  "custom": {},
  "plugins": ["serverless-offline"]
}
```

I am on fedora 24 running serverless 0.5.6

**Comment by mikelax** [comment]
How did you create the project? did you initialize it such that you have an _meta folder? If so, there should be a file created in an _meta/variables folder called s-variables-common.json. 

It should have a single attribute defined called project with a value of the project name. Once that file/attribute is present things should work for you.

**Comment by RudolfVonKrugstein** [comment]
Mmmh, I have this in ```_meta/variables/s-variables-common.json```

```
{
  "project": "<my-project-name>"
}
```

So this is already there, or? And I get the warning ...

**Comment by mikelax** [comment]
@RudolfVonKrugstein that looks like the correct value for the common variables file. 
Do you want to paste a snippet of where you are using the `${project}` variable? 

You can not use it directly in your actual lambda / js code. In order to do that you must an environment variable. You should be able to reference it as:  `process.env.SERVERLESS_PROJECT`

**Comment by RudolfVonKrugstein** [comment]
I use it in the root ```s-templates.json```:

```
{
  "functionName": "${project}-${stage}-${name}",
}
```

And then in the ```s-function.json```:

```
  "customName": "$${functionName}",
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
