### ISSUE TITLE
Error provisioning cloudformation

### ISSUE THREAD

**Issue by tobyhede** [serverless/serverless#1475]
Version: 1.0.0-alpha.1

Following the alpha docs, I receive the following on `deploy`

```
An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [coreBucket, IamRoleLambda]. . Delete requested by user.
```

There are no further details or error stack.

I have confirmed my AWS profile credentials have AdministratorAccess to AWS.

**Comment by pmuens** [comment]
Hey @tobyhede 
Could you check the name of your service? Our naming pattern for the core bucket includes the service name, the stage and the region. Some other guy might already used the same service, region and stage name.

We're about to change that in an upcoming version.

Thanks for reporting and sorry for the inconveniences.

**Comment by tobyhede** [comment]
Ah ... good catch.

**Comment by codepreneur** [comment]
Bucket names have to be globally unique. I was getting this error constantly until I made sure that my bucket name is unique. Then the error disappeared
