### ISSUE TITLE
"serverless" should trigger help

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1479]
When I run plain `serverless` with no command, nothing happens.  In V.0, this showed the help screen.  I grew used to this behavior and liked it.  Could we bring this back?

**Comment by pmuens** [comment]
Thanks for reporting.
Sure! Just pushed it in our TODO list.

**Comment by bennybauer** [comment]
Seems like it's already solved in v1 branch

**Comment by pmuens** [comment]
@bennybauer We close them once they are finished. What @ac360 meant is that the help should pop up when you simply enter `serverless` (without the `--help` or `-help` option).

Is this working for you?

**Comment by bennybauer** [comment]
@pmuens sorry, it doesn't work. I can take it if you're not on it yet (I'm looking for some simple stuff to get involved in the code).

**Comment by pmuens** [comment]
@bennybauer That would be great! Here's the CLI code https://github.com/serverless/serverless/blob/v1.0/lib/classes/CLI.js#L59-L84 (which is used here https://github.com/serverless/serverless/blob/v1.0/lib/Serverless.js#L68) will check if the help should be displayed. I think a simple if statement should be sufficient.

Let me know if you have any further questions. And thanks for jumping in on this!

**Comment by bennybauer** [comment]
@pmuens whoops, committed the fix to the same PR. Do you want me to revert and create another  branch in my repo and new PR?

**Comment by pmuens** [comment]
@bennybauer Thanks for the PR 🎉 

No worries! We've got you covered!

**Comment by ac360** [comment]
You rock, @bennybauer.  Thx :)

**Comment by pmuens** [comment]
Done on https://github.com/serverless/serverless/pull/1580
