### ISSUE TITLE
add awsm module versioning support to module cmd

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#148]
I'd like to leverage the release functionality of github as a initial way to manage awsm module versioning. the `jaws module install/update` command needs to be enhanced to accept versions and utilize github release url's to find said version.

**Comment by ac360** [comment]
:+1:

**Comment by joostfarla** [comment]
I've been thinking about this. Some key module features I'm missing atm:

* A way to define AWSM dependencies in the project configuration (probably jaws.json). This would allow one to bind to specific versions or version ranges (Semver compatible) of vendor packages. This would also remove the need to include vendor packages in a project (these could by ignored by version control).

* The "module install" and "module update" commands should resolve the latest stable version (or accept a version as an argument) and auto-add this to jaws.json. This could be a Github release, but you would probably want to support other VCS platforms as well. For Git or SVN, this would mean this would be based on tags. Next step could be a central registry, which makes version resolving easier and would eliminate the need to work with static URL's.

* A command to auto-install or update all underlying dependencies (Node or not), which were specified before. For example when I'm making a fresh clone of a project repo and want to install all modules  (defined in jaws.json) including underlying dependencies.

These features could have some impact on the project structure as-is (for example, split vendor modules from project modules). But I guess it's too early to discuss this for now.

The above is inspired by known module systems like NPM and Composer.

I'm looking forward to your thoughts and I'm happy to help wherever I can!
