### ISSUE TITLE
List plugins in help screen in alphabetical order

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1480]
Listing the plugins in the help screen is great.  Could we sort them by alphabetical order so we can read them more easily?

**Comment by pmuens** [comment]
Good idea. Yes that shouldn't be too hard. Should we keep it the way it is (flat list) or should we display them in another way? I'm not sure how this might look like if you have services with many plugins.

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1768
