### ISSUE TITLE
We changed the VPC config online & on a redeploy it's not reset

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1488]
This is v1 alpha. I believe we should overwrite all settings to make sure the serverless.yaml can be seen as a single source of truth.

What do you think?

**Comment by eahefnawy** [comment]
👍

**Comment by flomotlik** [comment]
@nikgraf you mean when you go through the UI, set VPC up and then redeploy serverless should overwrite the VPC setting?

Imho thats surprising to users and I would not do it. If serverless doesn't have any VPC config we shouldn't mess with it. Maybe people use a couple of tools or want to try something.

I'll close this issue for now. If I misunderstood your request and you meant something else lets reopen.
