### ISSUE TITLE
Deploy, keep and use several versions of the same lambda

### ISSUE THREAD

**Issue by gtennis** [serverless/serverless#1490]
##### Benefits:

* As mobile developer, I always need my backend guys to maintain two versions at a time. Because deployment of ios mobile app takes from 2 - 7 work days, and you don't want to block website frontend team's work, therefore they usually proceed and use the most latest APIs. However, for mobile we always need to have previous-safe api version. 
* Having two versions gives flexibility in case of critical error. You could rollback to previous version.
* Here's Amazon's article on that: https://aws.amazon.com/blogs/compute/tag/versioning/

##### Drawbacks:

* Unless it would hugely over complicate the whole configuration...

**Comment by gtennis** [comment]
Also, even Amazon forces us to use their API versions:

  var s3 = new AWS.S3({apiVersion: '2006-03-01'}); 

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Comment by pmuens** [comment]
Thanks for reporting this. We're about to add lambda versioning and will consider this when developing versioning.

**Comment by gtennis** [comment]
Thanks, awesome!

**Comment by pmuens** [comment]
Closing this one as we're discussing it in https://github.com/serverless/serverless/issues/1457
