### ISSUE TITLE
Add automatic excludes / presets for different programming languages when packaging

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1495]
We should provide automatic excludes for common, not necessary files.

We can create own plugins which will hook into the `before:deploy:createDeploymentPackage` to set the `service.package.exclude` values.

Is also discussed in https://github.com/serverless/serverless/issues/1486

**Comment by ac360** [comment]
@pmuens When #1442 is implemented, plugins will be installed in the service directory, so they will be zipped with the entire service.  However, they are dev dependencies, so they don't need to be in the final zip.  How can plugins be automatically excluded from the packaging process?  

Not sure if this is best, but perhaps plugins should always be installed as npm dev dependencies and we could read that in the packaging process and exclude those listed dev packages?

**Comment by pmuens** [comment]
Hmm. That's a good point.

Maybe we can match the name in the services `plugins` definition with the names inside the `package.json` file to see which ones are plugins and which ones are normal dependencies.

Adding them as a `dev-dependency` would work as well but I assume that users will forget it / don't know it and therefore "litter" the deployment package.

**Comment by flomotlik** [comment]
We are defining common exclude/include patterns now through the template files, so we don't need to define that automatically. Imho this would also lead to pretty surprising results for users imho. In case we do need this still for something please reopen.
