### ISSUE TITLE
first-service documentation - bucket name in AWS

### ISSUE THREAD

**Issue by krol3** [serverless/serverless#1498]
* Check if an Issue already exists for this
* Add the relevant label(s)
* Be kind :)
If you try to create in the AWS console, S3 service with the name generated "first-service-dev-us-east-1", to the first service documentation. It will generate the error

I attach the image, with a simple word like "service: service1", It will generate a {"BucketName":"service1-dev-us-east-1", and it's working with success!!!!

I attach an image of the error.

Regards, Carol

![screenshot from 2016-07-06 20 09 50](https://cloud.githubusercontent.com/assets/8355621/16637515/ea668a5c-43b5-11e6-99b6-f09e2e915686.png)
Bug Report Template -----------------------------------------------

##### Stack-Trace (Optional):

Serverless: Checking stack creation progress...
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [coreBucket, MyBucket]. . Delete requested by user.

Feature Request Template ------------------------------------------

##### Benefits:

* Benefit one...

##### Drawbacks:

* Drawback one...

##### Additional Details:
The cloud template in AWS : 

{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application's resources outside of Lambdas and Api Gateway","Resources":{"coreBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketName":"first-service-dev-us-east-1"}},"IamRoleLambda":{"Type":"AWS::IAM::Role","Properties":{"AssumeRolePolicyDocument":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"]},"Action":["sts:AssumeRole"]}]},"Path":"/"}},"IamPolicyLambda":{"Type":"AWS::IAM::Policy","Properties":{"PolicyName":"dev-first-service-lambda","PolicyDocument":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents"],"Resource":"arn:aws:logs:us-east-1:*:*"}]},"Roles":[{"Ref":"IamRoleLambda"}]}}},"Outputs":{"IamRoleArnLambda":{"Description":"ARN of the lambda IAM role","Value":{"Fn::GetAtt":["IamRoleLambda","Arn"]}}}}
Discussion template  ----------------------------------------------

**Comment by pmuens** [comment]
Thanks for reporting!

Related to https://github.com/serverless/serverless/issues/1458

**Comment by pmuens** [comment]
@krol3 we've implemented a new naming in https://github.com/serverless/serverless/pull/1544

This should solve your problem.
Let us know if you face this issue again!
