### ISSUE TITLE
Keep last X service .zip files in S3 bucket

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1504]
Right now all the service files are removed from the S3 bucket when the deploy is triggered (in the `cleanup` method in `awsDeploy`). We should keep a fixed amount of .zip files so that a user has a backups of old deploys and can still access them.

How many should we keep? I would vote for 5.

Any thoughts @eahefnawy @flomotlik ?

**Comment by flomotlik** [comment]
5 sounds good to me. Are they (or we in the tooling) able to roll back a Version without the file being in S3? That would be interesting for our Rollback strategy.

**Comment by pmuens** [comment]
I'll jump on this one since it's just a few lines of code. Should be PRable once https://github.com/serverless/serverless/pull/1494 is merged.

**Comment by pmuens** [comment]
Resolved with #1519
