### ISSUE TITLE
Any way to set "Authorization" in AWS Gateway with V1.0alpha

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [serverless/serverless#1509]
Is there a way I can enable Authorization in AWS Gateway with v1.0alpha, or do I have  to use v0.5.6 if I need this?

**Comment by pmuens** [comment]
Hey @RudolfVonKrugstein we've started with an implementatton of the basic features for API Gateway. Stuff such as VPC and Custom authorizers will be added soon: https://github.com/serverless/serverless/issues/1408

**Comment by RudolfVonKrugstein** [comment]
@pmuens Cool! Thanks for the Reply. While I am in the process of asking, will API Gateway Mapping templates also be added soon?

**Comment by pmuens** [comment]
@RudolfVonKrugstein Yes sure. We'll add that as well!

**Comment by eahefnawy** [comment]
@RudolfVonKrugstein FYI support for Custom Authorizers has been added in [this PR](https://github.com/serverless/serverless/pull/1620). Hasn't been merged or released yet :)
