### ISSUE TITLE
Get Multi-Region Deployment Working

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#151]
Currently, you can't deploy to multiple regions from JAWS dash, only one at a time.  However, the lambda and endpoint deployment code was all written for this to be possible.  The dash just needs to be fixed.

**Comment by GDownes** [comment]
Is this now possible? The issue has been closed with no explanation.

**Comment by eahefnawy** [comment]
@GDownes we dropped the CLI dashboard in Serverless. So now we only support deploying to each region one at a time.

Do you feel the need to deploy to multiple regions/stages concurrently? If so could you please open a new feature proposal issue to discuss this? 😊  This issue is very outdated
