### ISSUE TITLE
Better test coverage for AWS event plugins

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1511]
Right now we don't test if the variables the user sets (e.g. the `topic_name` in the `SNS` plugin) are present in the generated CloudFormation resource. We should aim for a better test coverage here.

- [ ] S3
- [ ] SNS
- [ ] API Gateway
- [ ] Schedule

**Comment by flomotlik** [comment]
is this still an issue @pmuens ?

**Comment by pmuens** [comment]
Should be mostly resolved with https://github.com/serverless/serverless/pull/1771

**Comment by flomotlik** [comment]
Closing this one then, so we can merge the PR and be done
