### ISSUE TITLE
Allow users to set their own deployment bucket without creating one in the CF stack

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1513]
Users should be able to provider their own `coreBucket` rather than to use the `coreBucket` which is generated by Serverless on initial deployment.

**Comment by ac360** [comment]
Nice.  Also, btw the term `coreBucket` confused me at first.  `core` feels like a new concept being introduced.  `serviceBucket` doesn't diverge and helps us maintain conceptual consistency and simplicity.

**Comment by eahefnawy** [comment]
@ac360 agreed. We probably should also include the service name in the bucket name, at least to make it unique.

**Comment by ac360** [comment]
@eahefnawy I'm not sure what the buckets are called (haven't seen the source).  But I was just referring to the property name in the `serverless.yml`.  Actually, this should probably go in `serverless.env.yml`.

**Comment by nhumphreys** [comment]
I missed this ticket when searching for my problem, glad its on the radar. 

I think there is also a need to store in the bucket the files with a prefix of the service-name-region-stage combo, this is so the existing remove S3 files step can also continue to function as expected.

We have a need for this now, so I'll start a PR with the re-factoring i've done already, hopefully it can be a basis for the ticket unless work has already began @pmuens ?

**Comment by pmuens** [comment]
@nhumphreys great 👍 
Thanks for jumping in on this! There's currently no implementation in progress for this issue so feel free to open a PR so we can start the discussion 🎉 

I'll mark this issue as `in-progress`.

Just drop a line here once the PR is out so that we can look into it together.
Just let us know if you face any challenges during the implementation / have questions!

**Comment by kennu** [comment]
I tested Serverless 1.0.0-beta2 and immediately ran into problems with the S3 bucket created by CloudFormation. I could not delete the CF stack because the bucket was not empty.

I strongly recommend not creating S3 resources with CloudFormation, because the stacks easily get into conflicted states when removing and recreating them. User is forced to wait for a long time and clean up S3 manually.

**Comment by pmuens** [comment]
Hey @kennu thanks for pointing in that direction. We're about to add a "force switch" to the CLI so that you can force removal by running `serverless remove --force` https://github.com/serverless/serverless/issues/1609

This way the user has to be proactive to remove all the resources and won't remove anything by accident.

**Comment by kennu** [comment]
I think it will be a problem for new users who try out Serverless, delete their project, and then try to delete the resources manually from AWS. If the S3 bucket has been created by CloudFormation, it will cause them problems and a bad feeling about Serverless.

**Comment by nhumphreys** [comment]
Does anyone have an opinion... Would it be better to take the approach of deleting the S3 Bucket from the Base template json, or instead remove it at runtime if a custom bucket is specified? I can go either way

**Comment by pmuens** [comment]
@nhumphreys would suggest to use the custom resources section to overwrite the `ServerlessDeploymentBucket` Resource.

any other thoughts @flomotlik ?

**Comment by flomotlik** [comment]
@nhumphreys @pmuens what you can do at the moment is remove the ServerlessDeploymentBucket from the Resources section and overwrite CF Output where we store the Bucket name because that one is used by our deployment command to know where to push artifacts to.

But it still will have a lot of problems, e.g. we're limiting the deployed versions in your bucket to 5 versions at the moment. This means that every deployment would remove the deployment of another service (not that big of a deal probably, but still a potential issue).

So I think its technically possible to do it by changing the CF template at the moment, you'll just run into different problems I'd assume and it will not be a good experience until the deployment bucket support isn't fully implemented inside of Serverless.

@nhumphreys whats the reason that you want to remove the bucket from the service?

**Comment by nhumphreys** [comment]
@pmuens thanks, i'll take another look there.

@flomotlik We don't want a bucket created for every project, region and stage combination.

To solve the 5 versions issue i was going to namespace the deployment items with a prefix, then the cleanup job would be using that prefix and respect other project and stage combos. It can continue to trash everything in the bucket, but it will do it on a prefix namespace instead.

**Comment by andymac4182** [comment]
What is wrong with a bucket for each one @nhumphreys ? They don't cost money and from what I understand from AWS there isn't a hard limit on the number you can have. 

It works really well for me personally because it means when I am giving this to a new developer they only have to worry about custom resources not deployment ones and Cloudformation + SLS handles everything for you.

**Comment by kennu** [comment]
@andymac4182 The default limit is 100 buckets per AWS account and you're going to run out pretty soon, if you need one for each _microservice_ deployed. (You need them for other things too, like each website.)

So people developing lots of stuff will end up having to request service limit increases from Amazon all the time, becoming stuck with development until they're approved. I don't think it's a good match with how AWS is intended to work.

From the other point of view, I agree with the approach that a service should be "self contained", including the S3 bucket. AWS is just currently not designed that way so there is a conflict between the principle and what's practical.

**Comment by kennu** [comment]
Having said that, I realize I've never actually asked AWS for a large bucket limit increase, say maybe 1000 buckets. Maybe it's possible? The process is a little intimidating (they ask you for motivation why you need the increase), so it doesn't seem like you should do it "just in case".

**Comment by nhumphreys** [comment]
@andymac4182 Buckets don't cost money until you put something in them, that's fine but that's not the point. The argument in a corporate environment becomes "Why do we need so many buckets?" or "Why is my S3 console littered with heaps of these buckets with weird names?"
But it totally works if you are operating on a team scale of < 5 members on a few serverless projects. 

I'm not suggesting that the current use of 1 bucket for each project, region and stage combo be removed. I want to make it possible to use just one bucket for all serverless deploys.

For developers doing development stage serverless projects you might not have them use ```ServerlessDeploymentBucket``` but instead have them use a sandbox AWS account and let it go and create the bucket automatically.

eg:

We've ran into the 100 bucket limit even on our AWS sandbox account that the devs play with, for the general user running a few serverless projects they probably won't hit this issue, sure requesting more buckets is relatively easy, but why bother AWS support if you don't have to?

**Comment by kennu** [comment]
I would also view this through eyes of an outsider, whose development process is not yet centered around Serverless. If there is a general impression that Serverless requires you to request more buckets from AWS, there will be higher friction for adoption.

**Comment by flomotlik** [comment]
I'm all in favor of this getting implemented, I'm not sure if its going to happen soon from us, but if somebody has time to contribute we'd be very interested. The way I see it happening would basically be through a `deployment_bucket` configuration parameter in the provider section of the service. There are a few things we need to keep in mind though:

1. What error message is thrown if the bucket doesn't exist
2. When you have one bucket for deploying multiple services old versions will be deleted very quickly, so the remove old versions action should probably be bound to a specific service/stage combination so we don't just remove other services deployments
3. Buckets need to be in the same region as the lambda functions for deployment. This has to be made VERY clear in the docs with good examples on how to use our Variables configuration to make this work.

And I'm sure more issues come up once this is in implementation phase. But yeah definitely a +1 on me for getting this started.

**Comment by erikerikson** [comment]
We can't create buckets here so supplying the bucket we have rights to use will be necessary.

**Comment by pmuens** [comment]
Done with #2189 /cc @flomotlik
