### ISSUE TITLE
Always include _ instead of separate functions when using lodash

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1515]
Right now we have a mixture of lodash usage.

Sometimes we include the necessary functions like this:

```
const forEach = require('lodash').forEach;
```

Sometimes we include everything like this:

```
const _ = require('lodash');
```

We should always use the latter as it makes development easier (no need to manage / update different requires when switching used functionality). Furthermore it's directly visible that we use a FP library such as lodash when we use `_` as nearly everyone does.

**Comment by flomotlik** [comment]
Imho this can be a small task for the next beta. Should be fast and simple to fix

**Comment by svdgraaf** [comment]
I have some time to burn, will start on this

**Comment by flomotlik** [comment]
@svdgraaf 

 ![Noice](https://media4.giphy.com/media/HggxGlGAWFkbK/200_s.gif)

**Comment by pmuens** [comment]
Will be done with https://github.com/serverless/serverless/pull/1769
