### ISSUE TITLE
Rename coreBucket to something more expressive

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1516]
The naming `coreBucket` should be renamed to `serviceBucket` as state here: https://github.com/serverless/serverless/issues/1513#issuecomment-231286368

**Comment by flomotlik** [comment]
Imho it should be something more expressive like `ServerlessDeploymentBucket` or something similar. In the Output Variable we can then also use `ServerlessDeploymentBucketName`

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1545
