### ISSUE TITLE
Add runtime property to Service / Function in service?

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1517]
We need a way to specify a runtime (As stated in https://github.com/serverless/serverless/issues/1470) so that we can compile the correct resources.

The question is if one service should be bound to a runtime (Add a `runtime` property in the `Service.js` class) or if one function should have a runtime property?

How should we implement this? Should this be a necessary property the user has to define in the `serverless.yaml` file (like already done with the `provider` property or should we auto detect the runtime (e.g. look into the code / the handler)?

What are your thoughts @eahefnawy @flomotlik ?

**Status:** Done --> (https://github.com/serverless/serverless/pull/1536)

**Comment by flomotlik** [comment]
> so that we can compile the correct resources

Do you mean automatically creating include/exclude rules? Imho that should be something we can solve through the tempting. E.g. if you have a Java project we add the src folder automatically to your excludes. I don't think the packaging mechanism should have built-in exclusions depending on the language is this is more surprising than simply adding include/excludes through the tempting. Then they are in the serverless.yml and no surprise.

We do need it for setting it in the runtime attribute of the function of course.

**Comment by pmuens** [comment]
Yep. Agree. We should do this in the templates (another plugin for this would be overkill).

**Comment by pmuens** [comment]
Ok. The proposal is that one runtimes should be used throughout the whole service (they are service bound). We can add function bound runtimes later on.

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1536
