### ISSUE TITLE
New, provider specific documentation structure

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1522]
We need a better documentation structure as we support more and more providers with provier specific functionality.

The documentation should be concise, short and independent. Furthermore it should feel like a guide when one reads through it form start to finish.

Here's something @ac360 and @eahefnawy came up with:

```
Quick Start:

Concepts:
   - Services
   - Functions
   - Events
   - Resources
   - Plugins

AWS:
   - Functions
   - Events
     - S3
     - Schedule
     - HTTP
   - Resources
   - Environment
     - Stages
     - Regions
     - Vars
   - Workflow
   - Examples
Azure:
  - ...
Google:
  - ...

Contributing

About
```

**Comment by flomotlik** [comment]
closing this for now. We have to discuss it this month and will come back to this issue
