### ISSUE TITLE
Improve Multi-Provider Implementation

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1529]
In V.1, the provider support is implemented in a way that causes a few problems and sets a bad example for how other providers should design their integration.  Great multi-provider support is our big goal of V.1, and we need to fix this to achieve that goal.
##### Problems:

The AWS SDK, and a utility class we've wrapped it in to make it more convenient to use within the Serverless Framework, is in the root of the `aws` folder, which contains multiple AWS plugins.  This is an anti-pattern which causes the following problems:
- Plugins should be completely independent, except for their shared reliance on the main Serverless instance.  However, all of the AWS plugins are currently sharing this additional AWS SDK utility class, which breaks their independence.  This is causing all of the AWS plugins to be built as an aggregate unit, which complicates testing and breaks separation of concerns.
- No external plugins will be able to access this useful AWS SDK utility class.  Instead, external plugins that want to work with AWS will be forced to rewrite the SDK and Framework config and utility logic, causing unnecessary redundancy and overhead when writing a custom plugin for AWS.  Our big goal is to make the Framework easily extensible.  If this pattern is continues and is followed by other providers, their SDKs and utility methods will also be inaccessible to external plugins, who will want access to that logic for convenience. 
- If external plugins cannot access the SDK, they will each have to include it as their own dependency.  Imagine a service with 10 AWS plugins, each with the AWS SDK as a dependency.  This will result in slower installs, larger file sizes and SDKs that have different versions
- Putting the AWS SDK and utility class in its own plugin makes it easier to move that out of the core, and require it only when it's necessary in the service.  Many users may not want this in the core, if they are using another provider.
- Each provider SDK and utility plugin can now be versioned.  This helps services continue using the provider SDK they were designed around, instead of the version shipped within the Framework or another plugin.
##### Proposed Solution:
- Keep each Provider SDK & utility class wrapper in their own plugin.
- Allow the Provider plugins to add their class to the main Serverless instance via a `setProvider()` method on instantiation, so Serverless gets the provider logic before any commands/hooks fire.
- Allow all other plugins to get the provider logic via a `getProvider()` method.

Now, any external plugin can call `getProvider()` to get the SDK and utility wrapper, and start using it right away.  Like this:

```
let provider = serverless.getProvider('aws');
provider.doSomething();
```

/cc @eahefnawy @pmuens

**Comment by flomotlik** [comment]
I agree we need to make the AWS SDK Wrapper accessible to others, but I don't think we should move plugins out of the aws subfolder. This separation into different providers makes the plugin folder a lot more accessible and understandable imho and if we move it to separate folders inside the plugin folder we'll easily lose track of everything. We've already been there and thats why we decided to set it up in a different way now.

I'm at the moment also not totally happy with the SDK as its still a bit magic with what its doing and we should at some point take another look at the SDK to make it nice and accessible to others. E.g. how its using variables from the serverless.env.yml isn't exactly how I want it to be.

Going by our very tight deadlines I don't think this is really a large issue at the moment though. Users can easily build integrations with AWS through their own plugins, the AWS SDK itself is available and in my opinion we have much larger issues we need to resolve first (e.g. Language support, Offline Plugin support, Better Documentation, ...). So I think this needs another look, but I would only do this after we've gone through other things like the above mentioned first.

**Comment by ac360** [comment]
@felixrieseberg, @bnookala, @mattpodwysocki, @timfpark, @jthomas, could you gents please take a glance at this and see if this is something pattern is useful for all providers?

**Comment by jthomas** [comment]
The [OpenWhisk SDK](https://www.npmjs.com/package/openwhisk) provides all the features I've needed for the OpenWhisk provider plugins. Plugins `require('openwhisk')` this directly, rather than depending on a single class like AWS.

They do share a utility class to manage constructing the OpenWhisk client with credentials automatically pulled from the user's environment shared by the separate plugins. This could be wrapped up as the "provider" plugin and shared in the API above.

**Comment by ac360** [comment]
Thanks for your feedback, @jthomas.  I've looked at your implementation and it seems very much like the proposed pattern would work better for you, for all of the reasons above.  We definitely want people to make their own OpenWhisk plugins to extend what they can do with it, within the Framework, and they are likely going to want easy access to the utility class you are including.
