### ISSUE TITLE
Own package for integration tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1532]
We should create an own package dedicated to integration testing (like @flomotlik mentioned).

This way we can test all the different templates, create complex services etc.
Those test may be run every night.

**Comment by flomotlik** [comment]
Potential test cases, please add more ideas (/cc @eahefnawy , @ac360 ):

* Create every available template and deploy it
* Create every available event type, deploy it and make sure it works as expected

**Comment by flomotlik** [comment]
Implemented in new separate repo
