### ISSUE TITLE
Edit/Add IAM role permissions

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1535]
Users need to have the ability to edit or add the default IAM role permissions that we create via CF. Basically a way to add to this array:
https://github.com/serverless/serverless/blob/v1.0/lib/templates/core-cf.json#L25

##### Use Case
Lambda function that is trying to call `putMetricData` of CloudWatch. So the IAM role that is assumed by the lambda needs the `cloudwatch:PutMetricData` permission.

**Comment by flomotlik** [comment]
Imho the best way to implement would be to have an `iam_statements` Array in the provider config parameter. Users can then add their own IAM Statements that we simply add to the IAM statements in [core-cf.json](https://github.com/serverless/serverless/blob/990d7c5a089c2047cdd342fca88f6c006c53c4c3/lib/plugins/aws/deploy/lib/core-cf.json#L30)

```
provider:
  iamRoleStatements:
    - "Effect": "Allow",
       "Action": 
          - "something:SomethingElse"
       "Resource": "arn:aws:logs:${region}:*:*"
    - "Effect": "Allow",
       "Action": 
          - "different:VeryDifferent"
       "Resource": "arn:aws:logs:${region}:*:*"
```

This is definitely complex for beginners, but IAM is simply complex and building an abstraction that would suffice for both beginners and make experts happy is imho basically impossible.

The nice thing here is that people can also use Ref syntax of Cloudformation for the Resource section for example. So they build very focused Policies

**Comment by mthenw** [comment]
I like that. Solves my problems :)

**Comment by estahn** [comment]
@flomotlik In my opinion this doesn't need to cater towards beginners.

**Comment by pmuens** [comment]
Solved with #1749

**Comment by mthenw** [comment]
Is it christmas today?

**Comment by jeffski** [comment]
Was banging my head against the wall trying to get this to work for about an hour then realised it was merged to master but is not in the beta1 version.

Got it installed and working by installing using:

```
npm install -g git+https://github.com/serverless/serverless.git
```

**Comment by pmuens** [comment]
@jeffski thank you for the pointer on how to install from master!

This issue was resolved with https://github.com/serverless/serverless/pull/1749 and will be available in beta.2!

**Comment by kennu** [comment]
I'd like to comment that the default generated serverless.yml should contain instructions/template on how to add IAM permissions. Granting some permissions is the first thing you need to do in almost any project on AWS.

Previously, this was rather easy by editing s-resources-cf.json and adding some policy statements to the existing policy.

**Comment by flomotlik** [comment]
@kennu agreed, opened #1923 for this

**Comment by nicka** [comment]
I like that's it get's clear to the user how to configure IAM roles/policies. But why don't we add it to the custom resources key? It feels like we don't have a clear distinction on how we would like to configure certain resources within the framework. 

TBH I think everything inside the `functions` key is perfectly fine since it can relate to multiple providers and is core to the framework. My concern is that the more custom keys we're going to add(like `iamRoleStatements`) the more people need to find how it get's merged into the final CloudFormation template.

**Comment by flomotlik** [comment]
@nicka imho things like extending roles is common enough that we should have something beyond just custom resources. I'm trying to mostly apply the 80/20 Role, so the 80% of use cases that are super common and typically involve the same things should have a built in way to do things. Extending your Role to be able to access other services imho definitely falls under this rule.
