### ISSUE TITLE
Module version mismatch. Expected 46, got 48.

### ISSUE THREAD

**Issue by uqutub** [serverless/serverless#1539]
Am using **htmltopdf** npm module, it gives error after sls function deploy,
but when am trying to use sls function run it works fine. 

_complete error:_

```
{
  "errorMessage": "Module version mismatch. Expected 46, got 48.",
  "errorType": "Error",
  "stackTrace": [
    "Object.Module._extensions..node (module.js:434:18)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/lib/node_modules/grpc/src/node/src/grpc_extension.js:38:15)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)"
  ]
}
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by dhildebrandt** [comment]
I'm seeing with another stack (electron stuff) so I doubt this is particular to serverless.
