### ISSUE TITLE
Can't resolve JSON-REF

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1543]
It has been reported that referencing JSON/YAML files using the JSON-REF feature is not working. We weren't able to reproduce the issue, but it needs further investigation. cc/ @flomotlik

**Comment by ac360** [comment]
An optimal time to get rid of it and roll our own :D

It doesn't solve all of our goals (e.g., extending an existing object), it looks goofy and a JSON standard in YAML is so confusing!!!

**Comment by flomotlik** [comment]
@ac360 We've checked and the JSONRef looks like its working completely fine, not sure why its been reported as failing, maybe error in the docs (though I couldn't find any). I agree in principle that we should have a different syntax that we own, I would just push that out to a later stage as we can easily introduce this in addition to JSON-Ref (although we would have to support both then)

**Comment by eahefnawy** [comment]
I think Issue #1699 was the issue that prompted this. Turned out the resources are just not structured correctly.

Closing...
