### ISSUE TITLE
Package plugin ignores path containing 'serverless'

### ISSUE THREAD

**Issue by kid** [serverless/serverless#1549]
##### Serverless Framework Version: 
1.0.0-alpha.1

##### Operating System: 
Mac OS X 10.11.5

##### Expected Behaviour:
Imagine the following folder structure:
```
my-service
├── handler.js
├── node_modules
│   └── my-serverless-plugin
├── package.json
├── serverless.env.yaml
└── serverless.yaml
```
I expect `my-serverless-plugin` folder to be included in the uploaded archive unless explicitly excluded.

##### Actual Behaviour:
The `my-serverless-plugin` is not included because the default exclude list contains the string `.serverless`, but this is compiled to a regular expression where `.` means any character, so any path containing `serverless` will be excluded.

##### Proposed solution:
Instead of using regular expression, use `String#indexOf`(see #1550)
Another solution could be to use something like [sindresorhus/globby](https://github.com/sindresorhus/globby) and have a syntax like `.gitignore` files.

**Comment by pmuens** [comment]
Wow! Great find!

Thanks for reporting.

**Comment by pmuens** [comment]
Done with #1550
