### ISSUE TITLE
Updating APIG method from get to post doesn't get reflected on AWS stage page

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1551]
After deploying an APIG get method, and then changing it in `serverless.yaml` to be a post method and deploying, AWS stage page still shows that it's a GET method, even though the method page says that it's POST.

**Comment by pouledodue** [comment]
The stages page is not updated when I add a new method...
I must do "sls remove" and then "sls deploy" to make sure the stages page is updated

**Comment by flomotlik** [comment]
This was fixed recently for new deployments, we still have an issue when removing APIS and we're talking to AWS about it
