### ISSUE TITLE
Save method doesn't work for Endpoint

### ISSUE THREAD

**Issue by kherkeladze** [serverless/serverless#1558]
http://docs.serverless.com/docs/project#section-updating-and-saving-data

It works in 0.4 but not in the latest version.
I think it's a very useful especially in plugin development.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
