### ISSUE TITLE
Tracking of anonymized usage information

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1559]
We should track the usage of the framework to understand how our users work with it.
This way we can derive and prioritize future features easier.

/cc @flomotlik @eahefnawy @ac360 @nikgraf @mthenw 

Follow the implementation here: https://github.com/serverless/serverless/pull/1568

**What should be done:**

- Use [Segment](http://www.segment.io) and their to track stuff
- Data should be anonymized
- Users should be prompted if they want to enable tracking

**Implementation ideas:**

- We can use hashed strings to anonymize data but make it able to put it into relation as well
- Use the Segment.io [Node.js SDK](https://github.com/segmentio/analytics-node) to track events
- The "turn tracking on / off" should be implemented with the help of a plugin
  - The plugin will simply write a `track-me` file in a directory to keep track whether the user has enabled tracking or not
- How to track inside the framework
  - *Idea 1:* Use a `trackable` class the other core Serverless classes can extend. Everything tracking related lives there
  - *Idea 2:* Use `before:x:y` hooks to only track the plugin usage (but what about errors etc.?) --> Upside is a clear separation of concerns (user may later on uninstall this plugin)

**Questions:**

- Forward the tracking data to Google Analytics and / or RedShift?
- What should we track?
  - Entered commands
  - Used plugins

**Worth to check out:**

- How the Atom editor tracks usage behavior: https://github.com/atom/metrics
- https://github.com/yeoman/insight
- https://github.com/iriscouch/traceback
- https://github.com/RuntimeTools/appmetrics

**Comment by flomotlik** [comment]
A few ideas for things to be tracked:

* Loaded Plugins
* Provider of the current service
* Operating System
* Current Version of Serverless
* Number of functions in the service
* Number of Events in the Service
* Executed command including which plugin the command came from
* Unique ID for this particular user that we create the first time the command runs (this might be controversial as we're tracking them directly)

**Comment by pmuens** [comment]
Here's how we'll implement it (/cc @flomotlik):

The first step is to gather useful information such as `operating system`, `used plugins`, `entered commands` and `Serverless version`.

Serverless will track automatically. However the user can disable it with the help of the `serverless tracking off` command.

A plugin will be developed which offers the enable / disable tracking functionality. It'll write a `do-not-track` file inside the Serverless home directory when the user enters `serverless tracking off`. This fill will be removed when the user enter `serverless tracking on`.

In `lib/Serverless.js` we'll implement a simple `if` check if this file exists. A `track()` method which lives inside the `Utils` class will be called if the file is present. All the tracking logic will be handled there.

Furthermore we need good documentation to show our users what and how we track the behavior.

The first implementation which will happen for the Alpha2 release will not include session handling. Future updates might introduce this possibility. We can then check if a user file was generated on the machine and print a warning when users use Serverless for the first time that we're about to track them when it's not present.

**Comment by flomotlik** [comment]
@pmuens sounds great, looking forward to it!

**Comment by pmuens** [comment]
@flomotlik Basic tracking is implemented (see last commit in #1568).

However tracking is extremely slow and blocks the entire CLI. Tried to modify the `flush` configs according to their docs but had no success.
Even tried to just send 1 event (and put everything in this event). There's no performance gain when doing this. It's as slow as sending multiple events.

However we'll get all the data this way.

So there are two open questions:

1. How can we make this faster?
2. How do we deal with the write key (right now it's XXXXXX in the commit). One would set this through an env variable which is obviously not practical here. Don't want to put it in the repo. Maybe we can set it right before we push the new version to npm?

Any thoughts on those to points?

**Comment by worldsoup** [comment]
@pmuens It would also be nice to track project level data (i.e. how many developers are working on a project? how often is it deployed? how many lambdas does it consist of). Can we do that?

**Comment by flomotlik** [comment]
@worldsoup we can track how many functions are part of this service, but not beyond what we have locally. We only have whatever is available in the local config, so number of developers and how often its deployed is also not really available. We might be able to build those profiles by combining the data in some of our analytics tools, but that will give us a rough overview and won't be exact.

We basically don't have any project level info directly, only one-time execution information

**Comment by pmuens** [comment]
@worldsoup good ideas! Some of those are already considered / implemented!

@flomotlik @eahefnawy 
I've debugged this tracking stuff with Segment and found a way how we can speed things up. I've replaced their node-package with `node-fetch` and use a plain HTTP call directly to their API which is way faster than going through the package.

However it still disrupts the UX a little bit. Furthermore we'll get all the information inside one large `track` call instead of separate ones (likes it's implemented beforehand) because multiple HTTP calls will slow everything down.

What we also need to consider here is that the speed might suffer even more if the user uses a slow internet connection / is not connected at all.

Here's a speed comparison so that you can see how it looks like in the wild (not that smooth as it's .gif but you only need to take a look at when the CLI processing returns and the user is able to enter the next command):

*Without tracking enabled:*
![f0e4bmnoza](https://cloud.githubusercontent.com/assets/1606004/16874516/e7c0be4a-4a99-11e6-89ee-da4c4e627fac.gif)

*With tracking enabled:*
![iykc0knofg](https://cloud.githubusercontent.com/assets/1606004/16874532/09ceabaa-4a9a-11e6-8825-532a633b3ded.gif)

**Comment by pmuens** [comment]
Ok. Resolved the issues with the latest push. It now has a timeout of 1 second (after that the HTTP request will be terminated). Additionally it will always fail silently so that the user won't see strange error messages e.g. when he has no internet connection.

**Here are some benchmarks:**
*Aside: I ran the this on my MacBook Pro with a DSL 16.000 internet connection (on the countryside 🐄 ):*

`serverless --help` (not inside a service)
- 758ms
- 786ms
- 788ms
- 830ms
- 778ms

`serverless --help` (inside a service)
- 755ms
- 760ms
- 834ms
- 812ms
- 766 ms

**Comment by shortjared** [comment]
Please make this OPT IN not OPT OUT. I'm more than happy to "allow anonymized tracking to help improve the product" when asked, but i want to know it's happening. 

In addition, plugin authors need to very much understand exactly what this does. some plugins by their nature may be running commands with sensitive data, and i want to be sure that isn't shipped off to tracking systems.

**Comment by pmuens** [comment]
Hey @shortjared 
thank you for your comment about this.
We're very concerned about privacy and don't track any sensitive information about users or projects the users are working on.

We also don't track any data specific to plugins.

Right now we track the following things:
- Entered command(s) (​*not the options the user has entered*​)
- Operating system
- Loaded plugins
- Serverless version
- Number of functions inside your service
- Total number of events inside your service
- Provider of your service
- If the command was executed inside a service

The blog post and the docs reveal more information about why we track, how we track and what we track:

- http://blog.serverless.com/serverless-v1-0-alpha-release-2/
- https://github.com/serverless/serverless/tree/v1.0/docs/usage-tracking

We're about to revamp the whole documentation and would add pointers to the tracking system whenever needed so that tracking is transparent and understandable for users, plugin authors and contributors.

Thanks again for your concern!

**Comment by shortjared** [comment]
Thanks for the clear response. Perhaps consider an explicit disclaimer, or disable / enable question at service creation.

I am not too worried about tracking as a whole and plan to enable it for most projects, but explicitly being told it is happening and being given the option to opt out fosters more trust.

**Comment by flomotlik** [comment]
@shortjared at the moment disable/enable works across the whole system. We've thought about being able to enable/disable it per project but it would simply add more config to the service.

But yeah agreed imho on project creation, help output or similar it should be openly presented
