### ISSUE TITLE
Add docs for API Gateway universal velocity template

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1561]
We're currently using a great API Gateway velocity template:
https://github.com/serverless/serverless/blob/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L49-L78

Unfortunately it's not documented anywhere.

**Comment by pmuens** [comment]
Closed with #1662

**Comment by sid88in** [comment]
@pmuens I am trying to add current date time in request mapping stage using VTL but I get empty values

Explained here at the end: https://forums.aws.amazon.com/thread.jspa?messageID=786918&#786918

Any help?
thanks
Sid
