### ISSUE TITLE
Add default runtime when no runtime is provided in serverless.yaml

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1565]
Each service has a hard dependency on a runtime from now on.

We should add a fallback for a default runtime (e.g. `nodejs4.3`) which will be used if no runtime property is provided in the services `serverless.yaml` file so that old projets won't break.

A warning should be shown on the console that the default runtime will be used.

The only concern I have with this is that it'll only affect alpha1 users (because each service will have a runtime starting with alpha2) and that we have a hard dependency on AWS with this because Azure, IBM or Google might use different runtime names. So not sure if it's worth implementing.

Related to #1567

**Idea:** move the validation logic outside the `Service` class and validate it inside the AWS plugins (the default runtime setting should also live there) as it's AWS related.

What do you think @flomotlik @eahefnawy ?

**Comment by flomotlik** [comment]
As mentioned in #1567 I think we should include a nested config object that can have any provider specific config in it and we can then also add validation in plugins to make sure this is actually available.

**Comment by pmuens** [comment]
Resolved with #1641
