### ISSUE TITLE
Get AWS accountId for API Gateway method compilation with the help of an OutputVariable

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1566]
Right now we get the accountId in a "not that awesome" way (see https://github.com/serverless/serverless/blob/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L37-L44).

We can update it once https://github.com/serverless/serverless/pull/1540 is merged.

**Comment by flomotlik** [comment]
Can't we simply use a Ref instead? Not sure why we have to build the ARN ourselves in a Cloudformation template @pmuens

**Comment by pmuens** [comment]
Yep. Thanks!

Good idea! I'll look into it.

**Comment by eahefnawy** [comment]
[Resolved in this PR](https://github.com/serverless/serverless/pull/1682)
