### ISSUE TITLE
Add support for multiple commands on same level

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1570]
The current plugin implementation forbids it to have mutliple commands on the same level. Here's an example how this looks like. We should discuss if we want to support this (might make the whole `PluginManager` logic a little more complicated.

```
this.commands = {
      foo: {
        lifecycleEvents: [
          'foo',
        ],
        commands: {
          one: {
            lifecycleEvents: [
              'one',
            ],
          },
          two: {
            lifecycleEvents: [
              'two',
            ],
          },
        },
      },
    };
```

**Comment by flomotlik** [comment]
So basically its not possible two have 2 subcommands? This is something we should probably resolve at some point.

**Comment by flomotlik** [comment]
@pmuens just to make sure it is not possible at the moment to have 2 subcommands in the same plugin?

**Comment by pmuens** [comment]
You can have 2 subcommands in the same plugin but not in the same `commands` definition.

So

```
this.commands = {
      foo: {
        lifecycleEvents: [
          'foo',
        ],
        commands: {
          one: {
            lifecycleEvents: [
              'one',
            ],
          },
        },
      },
    };
```

works whereas

```
this.commands = {
      foo: {
        lifecycleEvents: [
          'foo',
        ],
        commands: {
          one: {
            lifecycleEvents: [
              'one',
            ],
          },
          two: {
            lifecycleEvents: [
              'two',
            ],
          },
        },
      },
    };
```

won't.

**Comment by flomotlik** [comment]
The first example is what I mean. At the moment its not possible to define `serverless deploy function` and `serverless deploy assets` for example in the same plugin (or at all really). So then this needs to be fixed

**Comment by pmuens** [comment]
Yep, exactly 💯

**Comment by dougmoscrop** [comment]
This should be fixed now!

**Comment by pmuens** [comment]
Done with #2133 /cc @flomotlik
