### ISSUE TITLE
Feature: Use Node.js instead JSON Templates

### ISSUE THREAD

**Issue by ccorcos** [serverless/serverless#1571]
There's this complicated JSON template stuff going on -- why not just use Node.js instead an export a serializable JSON object? Then everything can be reused using code instead of another DSL. And as a bonus, you can add comments (which you cant in JSON)!

**Comment by flomotlik** [comment]
@ccorcos you mean in request templates? Are you working with 0.5.x or 1.0 of the framework?

**Comment by ccorcos** [comment]
Just reading the docs: http://docs.serverless.com/docs/templates-variables

**Comment by flomotlik** [comment]
@ccorcos yup thats completely different in the latest V1 that we're currently working on. Basically you have one serverless.yml for your whole service and you can access environment variables with a simple ${} notation.

As this has already changed I'm going to close this issue for now, would be interesting to get your feedback on the new system. You can take a look at v1.docs.serverless.com

**Comment by ccorcos** [comment]
YAML is a bit nicer on the eyes for this kind of stuff. Looks good to me -- but I'm concerned about more complex orchestration. If you have 10 different services that all need to be connected and coordinated together with configurations that depend on each other, it seems a lot easier to do this with a programming language rather than a templating language. That way you can require what ever you want, iterate through things, and generate the configurations you need.

For what its work, at work we use Jinja2 to template Salt YAML configuration files...

**Comment by flomotlik** [comment]
@ccorcos yup agreed, we're still discussing how orchestration of separate services that depend on each other should be done in the best way. We're not sure yet, there are a lot of different options basically and we'll keep exploring them in issues here going forward.

**Comment by ccorcos** [comment]
Awesome. I'd love to see what you guys come up with.
