### ISSUE TITLE
Documentation on how to run two versions of Serverless on same machine

### ISSUE THREAD

**Issue by mt-sergio** [serverless/serverless#1572]
Hi guys,
I'm using for some production projects sls@0.4 but now I would like to start using sls@alpha on a new one.
Any tip to handle it easily?
Thanks!

**Comment by mt-sergio** [comment]
My solution:
```
$ sls -v 
0.4.2
$ npm install serverless@alpha # no global !
$ alias slsx="~/repo/mt-ssu/node_modules/.bin/sls"
# slsx -v
1.0.0-alpha.1
```

**Comment by pmuens** [comment]
@mt-sergio thanks for sharing!

Might be interesting to put something like this in the docs (/cc @flomotlik @eahefnawy)

**Comment by flomotlik** [comment]
Yup. @mt-sergio Yeah don't think there is really any other way to do this.

**Comment by pmuens** [comment]
Thanks again @mt-sergio. We've added a reference to the docs (see #1655)
