### ISSUE TITLE
Fix cannot read "OutputVariable" of undefined error

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1574]
Our integration tests fail quite often recently.

It has something todo with the way we get the name of the services S3 bucket during deployment.

**Comment by pmuens** [comment]
This bug breaks our integration tests. The strange thing is that I am absolutely not able to recreate this issue on my local machine (I ran the integration test a bunch of times without issues).

Maybe it has something todo with AWS permissions to read the bucket name or something similar?

/cc @flomotlik @eahefnawy

**Comment by flomotlik** [comment]
@pmuens can you link to a build where this has happened? Happy to look into it

**Comment by pmuens** [comment]
@flomotlik Sure. Here's an example build that failed: https://travis-ci.org/serverless/serverless/jobs/144476250

**Comment by pmuens** [comment]
The solution to the problem is that a new service should be created (rather than using the old service creation we've done in alpha 1 (See https://github.com/serverless/serverless/issues/1615 and https://github.com/serverless/serverless/issues/1614).

We need to update our integration tests to reflect the recent changes of alpha 2.

**Comment by pmuens** [comment]
Should be solved with https://github.com/serverless/serverless/pull/1639

**Comment by pmuens** [comment]
Unfortunately it's still not resolved completely. We need to investigate further if the S3 bucket e.g. needs some time to be created until it's globally accessible (and can be displayed in the `Output` section.

**Comment by pmuens** [comment]
I think I found the cause why the integration test fails.

The integration test uses the `aws-nodejs` template. This template has one name `aws-nodejs` and is not changed during deployment. This means that if one tests has failed we have a stack with the exact name already present while the other Stack is deployed. This makes e.g. the Stack checking process which checks if the stack will be updated think that it's already updated and the bucketName is available (but it's not / the wrong bucketName). Overall the whole process fails.

We need to ensure that there's no old CloudFormation stack available or cleanup by hand.

/cc @flomotlik @eahefnawy

**Comment by pmuens** [comment]
Should be resolved with #1657
