### ISSUE TITLE
Use S3 event name and lambda functiuon instead of ARN

### ISSUE THREAD

**Issue by jeffski** [serverless/serverless#1575]
I've been setting up an S3 event to trigger a lambda function - i.e. I added an event like this to my s-function file:
```
"events": [
    {
      "name" : "MyLambda",
      "type": "s3",
      "config": {
        "bucket": "myBucket",
        "bucketEvents": ["s3:ObjectCreated:*"],
        "filterRules" : [
          {
            "name": "suffix",
            "value": ".jpg"
          }
        ]
      }
    }
  ]
```

When the Event is created and I view it in the S3 console the name of the Event is a long random AWS id string and the selected Lambda function is an ARN instead of the actual function name.

While everything works the way it should, a nice to have feature would be the name of the event as specified in the s-function file (benefit: it is easier to read and identify) and for the selected function to be the actual function name (benefits: it's easier to read/identify and also it will now show up on the triggers tab on the Lambda function console page).

**Comment by flomotlik** [comment]
Hi @jeffski , thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
