### ISSUE TITLE
Update / rename lifecycleEvents of deploy plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1577]
The `lifecycleEvents` of the `deploy`plugins should be renamed to be less specific but more broadly defined so that the naming will "work" for all providers.

`createDeploymentPackage` --> `createDeploymentArtifacts`
`createProviderStacks` --> `TBD`

- [ ] Update docs
- [ ] Update all plugins which uses those lifecycles

**Comment by flomotlik** [comment]
Imho we should do that in the next beta release, so its all prepared before the full release. Should be easy to do anyway.

**Comment by pmuens** [comment]
Yep. Good idea. Maybe we should also evaluate other providers before doing that...

**Comment by flomotlik** [comment]
Imho that would be a lot of guesswork as we don't really know where providers are going and what is necessary. If we take the current lifecycle events and make them a bit more generic maybe we should be in a good place imho.

**Comment by pmuens** [comment]
This are the lifecycle events we currently have:

```
'initializeResources',
'createProviderStacks',
'createDeploymentPackage',
'compileFunctions',
'compileEvents',
'deploy',
```

IMHO we can keep most of them. Anyway here are my proposals for name changes:

```
'initializeResources', --> 'initialize'
'createProviderStacks', --> 'setupProviderConfiguration'
'createDeploymentPackage', --> 'createDeploymentArtifacts'
'compileFunctions',
'compileEvents',
'deploy',
```

/cc @flomotlik @eahefnawy

**Comment by flomotlik** [comment]
looks good @pmuens . If you could create a PR that can go out

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1824
