### ISSUE TITLE
Error on deploy `consumed` by SError

### ISSUE THREAD

**Issue by sielay** [serverless/serverless#1583]
##### Serverless Framework Version: 

0.5.6

##### Operating System: 

OSX

##### Expected Behavior: 

ServerLess error expect first parameter to be as string, so you can print out `err.message`.

##### Actual Behavior: 

Error handler pass whole original error to ServerLess error constructor

##### Stack-Trace (Optional):

https://github.com/serverless/serverless/blob/master/lib/actions/ResourcesDeploy.js#L241

**Comment by flomotlik** [comment]
Hi @sielay , thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by sielay** [comment]
@flomotlik got it, btw is programatic API changing hugely in 1.0?
