### ISSUE TITLE
Community Repository

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1584]
As discussed in #1525 we want to create a Community Repository that allows trusted Contributors to build plugins in a common repository while we guarantee to the community that we have some level of involvement in those Plugins, make sure there is a certain level of quality in place and we follow certain common specifications (e.g. common syntax checking, testing strategy, ...).

Furthermore this should make it very easy for the community to explore available plugins that are of great quality as we can point them to this repo and potentially expose that as a website as well with docs.

My proposal is to create a **serverless/serverless-community-plugins** repository. This repository will contain subfolders for every plugin and will run through the tests of every plugin upon each merge. It will also contain a common style check to make sure all plugins follow the same standard used in Serverless.

I don't think going with Submodules is the best solution here, as this would still lead to many different repos being around and make it much harder for us to have some level of involvement in the development of those plugins. Its also not feasible to implement standards that are shared between all plugins if they aren't in the same repository.

Following are some of the Downsides of this approach:

* Issues are opened in one repository for all plugins:
This will suck a bit and we need to make sure that we have good labelling in place and great maintainers that can make sure issues are routed to the right people. We can definitely help with that but need community involvement on these as well

* Builds take longer and impact each other
Bad or unstable tests could easily impact other plugins and how other people could contribute to plugins. Again this is painful, but imho its better to have one set of standards across all plugins and take this risk than splitting it up into separate repos where no standards can be enforced. And we need to be extra strict on high quality tests and code review here, which benefits everyone.

If we see in the future that we want to spread it out further we can do that, but lets get to this problem first I think.

/cc @eahefnawy @ac360 @worldsoup @pmuens @rajington @ryansb

**Comment by ac360** [comment]
@flomotlik +1 for the proposed structure.  My only suggestion is a simpler name for the repo:

* serverless/plugins

**Comment by eahefnawy** [comment]
@flomotlik does that mean if I write a custom plugin, it won't live in its own repo (on my profile), and I have to PR all files of this plugin to this shared repo? If so, I think that's not super great. I think most plugin authors will want to showcase their plugins along their other projects/repos on their Github profile/portfolio for more credit and acknowledgment.

Maybe @pmuens [awesome-serverless](https://github.com/JustServerless/awesome-serverless) repo is the community repo we need? Maybe we should just make it an official serverless repo?

**Comment by rajington** [comment]
I'm  fine with either approach, but would submodules like in [this repo](https://github.com/getpelican/pelican-plugins) be better @eahefnawy?

I think the main concern with submodules is that I could release 'serverless-alexa-plugin', then there could be some breaking change, and sls wouldn't be able to instantly push a fix in my repo without my involvement. Is that right?

**Comment by flomotlik** [comment]
This is now created in https://github.com/serverless/community-plugins
