### ISSUE TITLE
Programatic API in 1.0

### ISSUE THREAD

**Issue by sielay** [serverless/serverless#1587]
##### TLDR:

Is there stabilised programatic API of version 1.0 as it was in 0.5?

##### Discussion:

I am working on IDEish shell over serverless. I started by wrapping 0.5, but since incoming changes are huge, I'd like to ask:

 * Do you work on any IDEish tools?
 * Are you planning to expose not CLI bound API?
 * Are there any API docs?

Thanks

**Comment by flomotlik** [comment]
The way we think about our API going forward is basically allowing you to trigger commands and lifecycle events through the API and then plugins can react to it. I'd love to talk a little bit more about your plans though at first. We're going to be at a Teambuilding all of next week, but how about the week after? Didn't find an email online, but can you send me one to flo@serverless.com and we can set something up.

**Comment by sielay** [comment]
Will mail you in the moment. Will also open source some work of mine (for those who worry that we'll plan taking over the world via email) once I cleanup nasty comments in my code.

**Comment by flomotlik** [comment]
This is interesting in the future, but no current goal so I'm closing this issue
