### ISSUE TITLE
Cloudfront ForwardedValues.Headers isn't supported in s-resources-cf.json

### ISSUE THREAD

**Issue by jonascheng** [serverless/serverless#1589]
##### Serverless Framework Version: 
0.5.6

##### Operating System: 
Ubuntu Trusty

##### Expected Behavior: 
Should not remove "Headers" from s-resources-cf.json
            "ForwardedValues": {
              "Headers": ["Authorization"],
              "QueryString": "true"
            },

##### Actual Behavior:
After executing ```sls resources deploy``` and then "Headers" is removed.
I found this issue by checking CloudFormation template from AWS Console.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
