### ISSUE TITLE
Best approach for reducing ZIP size uploaded to AWS

### ISSUE THREAD

**Issue by Cabsy** [serverless/serverless#1591]
Hi Guys,

I have been using serverless for a few weeks now and its proven extremely helpful when it comes to managing lambda code and deploying to AWS. I am in the process of writing an API and I'm going through a refactor stage. I have just noticed that for each lambda function my entire project is uploaded. I was wrongly under the assumption that serverless would look at my requires and automagically include all relevant files and exclude the stuff I don't use. I really need to make sure that functions are as efficient and small as they can be while making sure I keep DRY. Would anyone be so kind as to help me out with some advice, I've been trying the serverless-optimizer-plugin but I'm a bit disheartened as it doesn't seem to work for me / my setup.

My folder structure is as follows is shown on the screenshot attached

if you take address for example the s-function handler points to foundation/addresses /handler.handler. This leads to everything being included. However I would not necessarily require the modules under main and users and node_modules so I would like to exclude them from the ZIP for addresses as they just bloat the file size.

Any help would be mostly appreciated!
![serverless](https://cloud.githubusercontent.com/assets/20018843/16903808/580f8266-4c80-11e6-82c6-19dfa6d1c36a.png)

**Comment by tengis** [comment]
@Cabsy i think you can do that on v1.0 https://github.com/serverless/serverless/blob/v1.0/docs/understanding-serverless/serverless-yaml.md

Please have a look **package** config

**Comment by codepreneur** [comment]
@tengis what about minification? when will `serverless-optimizer-plugin` will be integrated into V1?

**Comment by tengis** [comment]
@codepreneur I'm not sure. Project contributors will answer that question.

**Comment by flomotlik** [comment]
@codepreneur @tengis not sure yet about serverless-optimizer inside of Serverless Core with V1. Discussion currently happening in #1653

Closing this issue as this specific one is solved with include/exclude as @tengis already linked to.
