### ISSUE TITLE
creating-a-service.md documents using --template rather than --provider and --name for 1.0.0-alpha.1

### ISSUE THREAD

**Issue by ellucianBret** [serverless/serverless#1601]
Serverless Framework Version: 1.0.0-alpha.1
Operating System: Mac OSX 10.11.5

Expected Behavior: Create new Serverless service as documented in creating-a-service.md. As documented it shows "serverless create --template aws-nodejs"

Actual Behavior: Serverless Error -- This command requires the --name option. Please pass it through. :)

Change create-a-service.md to show it as: "server less create --name <service name> --provider aws"

**Comment by eahefnawy** [comment]
@ellucianBret you're :) ... We've updated the docs before releasing these changes. We will release Alpha 2 very soon and this will no longer be an issue.

Thanks for reaching out! 😊

**Comment by pmuens** [comment]
Closing this issue as alpha2 was released recently. Thanks for reporting @ellucianBret !
