### ISSUE TITLE
Catch Errors for Tracking

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1604]
##### Feature Request:

Catch Error when you can't read/write to install location of serverless to disable tracking
##### Benefits:
- No errors thrown to users when disabling tracking

/cc @pmuens

**Comment by flomotlik** [comment]
@pmuens we're already catching when exceptions are thrown during tracking correct?

**Comment by pmuens** [comment]
Tracking will be run and processed, but we don't mark the failed command as an error inside of the tracking.

**Comment by horike37** [comment]
@flomotlik 
When you execute `serverless tracking -d`, it generates the `do-not-track` file in serverless core.
I want to send a PR that throw an error when it fails to create the file. Does this sound good?

**Comment by flomotlik** [comment]
That sounds great. Sorry for the delay on answering this.

**Comment by horike37** [comment]
@flomotlik 
I implemented this. Cloud you review it?

**Comment by mthenw** [comment]
@flomotlik do we still need if we are using home dir?

**Comment by flomotlik** [comment]
Yup, while its probably not going to happen, when it happens its really bad and it would mean tracking is enabled without the ability or knowledge to disable.

**Comment by pmuens** [comment]
The functionality which will create the file in `Utils.js` already has a Pokémon exception handling (https://github.com/serverless/serverless/blob/master/lib/classes/Utils.js#L162). The plugin might need another one as the files are renamed there (https://github.com/serverless/serverless/blob/master/lib/plugins/slstats/slstats.js#L36-L54).

**Comment by mthenw** [comment]
@pmuens there is already PR for that. Could you review? https://github.com/serverless/serverless/pull/2313

**Comment by pmuens** [comment]
Yes, will do today

**Comment by pmuens** [comment]
Done with #2313
