### ISSUE TITLE
Track how many of which events are inside serverless.yaml

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1605]
It would be really valuable to get the event name and the count (how often it's used inside the service).

E.g. like `s3: 10x, http: 5x`.

/cc @eahefnawy @flomotlik

**Comment by eahefnawy** [comment]
Nice! we can take that to the next level and track lots of other properties too for BI. We can answer the following Qs:

- What's the most used runtime?
- What's the average number of functions per service?
- What's the average size of a service?
- How often do users use custom plugins?
- How complex is an average `serverless.yaml` file?
- What's the most used region? and what's the average number of stages?
- a lot more....

**Comment by pmuens** [comment]
Closed with #1625
