### ISSUE TITLE
Save tracking information locally and only sync when X trackings are stored locally

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1606]
The trackings should be stored locally and only send when the queue is "full". This way tracking would be more efficient on the users machine.

/cc @flomotlik @eahefnawy

**Comment by flomotlik** [comment]
Which issue are we resolving with this? Is tracking taking too long for people?

**Comment by pmuens** [comment]
This does not resolve any specific issue. It was just a proposal for an improvement we discussed recently. The segment package does the same behind the scenes.

Maybe even not worth the effort (so it can be closed if not relevant).

**Comment by eahefnawy** [comment]
That's interesting! It'd help with the lag, but it wouldn't provide realtime analytics.

**Comment by pmuens** [comment]
Yes. And we have more data to get over the wire. Note sure if we can nest the data in a good way so that we only have one request with one large object but it's also easy to analyze.

**Comment by eahefnawy** [comment]
hmmm I really like that ... do you think this "data dump" will be reliable? could it be manipulated somehow? we're gonna have to maintain a tiny local database though. Maybe we can just send a json/yaml file, but not sure if that works with Segment. This file is also a good way for the users to see exactly what kinda data will be shared and optionally not send it.

**Comment by flomotlik** [comment]
Imho adding local database or local storage introduces a large complexity and I don't really think this is an issue right now. I would keep it in mind in the future if we see that people have a problem with it, but don't think we should explore this further at the moment until we actually know its an issue

**Comment by pmuens** [comment]
Yep. Agree with @flomotlik. More a kind of "nice to have" feature.
