### ISSUE TITLE
Add Kinesis stream event source

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1608]
Kinesis stream support is an often heard requirement.

We should make it possible for the user to add an own ARN in the event syntax.

/cc @flomotlik @eahefnawy @mthenw

**Comment by pmuens** [comment]
@mthenw could you give some feedback what you would need here?

**Comment by mthenw** [comment]
As AWS SDK requires Kinesis stream ARN and starting position there is no need to make string version.

**Comment by mthenw** [comment]
There is a separate CF resource for creating mapping http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html. 

So creating only event source mapping is easier than creating both mapping and Kinesis stream.

**Comment by flomotlik** [comment]
Ok so basically I think we can have 2 different implementations here. When you provide an ARN we will not create a stream for you, but simply create the event mapping and thats all. If you do not provide an ARN we will create the Stream for you. This way the following 3 use cases are possible:

1. Create Stream and Lambda function for me so I don't have to care about anything
2. Create Stream through custom resources, but lambda function normally for more config options
3. Create Stream completely separately, but lambda function normally

Sounds pretty good imho

**Comment by mthenw** [comment]
Yeah, that was my original idea. 

I'm thinking is we should be symmetric with other event sources. If we create SNS topic maybe we should also create Kinesis stream. And if someone wants only event source mapping we should suggest custom resources.

Not sure if predictability will not suffer here.

**Comment by flomotlik** [comment]
Hmmm, we could simply start with a good docs page first and then see if and how we want to integrate this directly? I'm not sure we fully understand how people are using or want to use Kinesis integration in Serverless, so docs might be a good first step and then go from there (e.g. Add to the docs that people should reach out when they use kinesis with Serverless so we can learn more)

**Comment by mthenw** [comment]
There is already note about that
> Note: This list will be updated constantly as we're adding more and more event sources in the future. Just open up an issue if you have any wishes regarding event support.

https://github.com/serverless/serverless/blob/v1.0/docs/guide/overview-of-event-sources.md

**Comment by pmuens** [comment]
I get the value of writing the docs first to evaluate if users need this.

But IMHO building a plugin which builds some kind of wrapper around the raw EventSourceMappings and only supports existing kinesis setups at first (without creating one if it's not present) is more valuable and less complex because users might already be familiar with event definitions in their functions and maybe less experienced with the `resources` section.

Seems like the DynamoDB event source is really requested by the community (https://github.com/serverless/serverless/issues/1441) so we can start there and after finishing that work on the plugin for Kinesis Streams which should be quite similar.

**Comment by flomotlik** [comment]
@pmuens I agree that its interesting and important to have support for it, the only question for me is if we have enough understanding how it should work to build a good first iteration of it or if we should try to get more feedback first from potential users and put that into the documentation as well, so if people are using it through the docs link to a specific Github issue where they can chime in with their ideas for the plugin

**Comment by pmuens** [comment]
Alright. Sounds reasonable. I'll add the corresponding docs for Kinesis streams and DynamoDB streams via `EventSourceMappings` and link to this issues in the docs so that we can discuss the implementation details with the community!

**Comment by flomotlik** [comment]
Awesome. @mthenw your feedback on the eventual docs would be super helpful as well

**Comment by pmuens** [comment]
Add docs how one can set this up in https://github.com/serverless/serverless/pull/1751

**Comment by oliversommer** [comment]
feedback from a potential user: IMO the approach mentioned by @flomotlik makes sense. For me these aspects are relevant: 1) use ARN of existing stream to map existing kinesis stream or 2) define stream in resources which then also creates the kinesis stream. I would love to have this. 
Just to be sure: there no possibility yet to define a kinesis/lambda event mapping when both are defined and created through sls?

**Comment by flomotlik** [comment]
@oliversommer definitely possible. You can simply use Ref or GetAtt in the ARN section. 

>Note: You can also create the stream in the resources.Resources section and use Fn::GetAtt to reference the Arn in the mappings EventSourceArn definition.

**Comment by pmuens** [comment]
Done with #2250 /cc @flomotlik
