### ISSUE TITLE
Capture errors statistics

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1610]
Right now error won't be tracked at all. We should add a way to track those to see what went wrong and how we can fix the bug.

/cc @flomotlik @eahefnawy

**Comment by DavidWells** [comment]
Lets do this!!!!!!!! 

@pmuens we have a sentry account for error tracking.

@nikgraf has used the sentry node SDK with the serverless-dashboard

 Lets get this wired up! =)

**Comment by pmuens** [comment]
Sounds good!

Seems like we need to do it somewhere [here](https://github.com/serverless/serverless/blob/bc1fb6a86aa4fabb9fb84179b22adb7920bc6a6e/lib/classes/Error.js#L52-L95) (since it's configured globally [here](https://github.com/serverless/serverless/blob/bc1fb6a86aa4fabb9fb84179b22adb7920bc6a6e/bin/serverless#L12)).

Seems like this isn't too hard to implement.
