### ISSUE TITLE
Ctrl+Enter deploy hotkey does not work in OS X

### ISSUE THREAD

**Issue by mkgalloway** [serverless/serverless#1611]
##### Serverless Framework Version: 
v0.5.6
##### Operating System: 
OS X 10.11.4
##### Expected Behavior:
In `dash deploy`, `ctrl + enter` should "immediately deploy selected" items, as the help message implies. 
##### Actual Behavior:
Pressing enter toggles the selected/not selected state of the current item, but does not move the cursor to the next item.

Presumably, this is due to https://github.com/serverless/serverless/blob/master/lib/utils/cli.js#L391 only checking for `enter` while the key is named `return` in OS X (and the Keypress library differentiates between the two).

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
