### ISSUE TITLE
Deploying on 1.0.0-alpha.2 is impossible (Cannot read property 'OutputValue' of undefined)

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1614]
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16957918/5000e39c-4dd6-11e6-992c-025c0b8bf7f5.png)

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16957856/05b7959c-4dd6-11e6-95ed-21d3acb43d5f.png)

Does anyone know how can I downgrade back to alpha.1?

**Comment by eahefnawy** [comment]
Thanks for the quick report @codepreneur 👍 ... I just tried to reproduce but wasn't able to. Is that a fresh serverless service?

looking at the code, it seems that for some reason the stack does not exist. Is there something specific about your service that might be relevant?

**Comment by codepreneur** [comment]
@eahefnawy if you want to reproduce the issue here is all the code that I am trying to deploy

![image](https://cloud.githubusercontent.com/assets/3421858/16958906/7d066700-4dda-11e6-8463-00d18ab95688.png)

**Comment by eahefnawy** [comment]
is it the same service you've been using before updating to Alpha 2?

**Comment by codepreneur** [comment]
This service deploys perfectly with Alpha 1, but throws this error with Alpha 2 and I think this issue is to do with this particular variable `serverlessDeploymentBucketName` that gets created when creating a service from scratch with alpha 2 but is not created with alpha 1

**Comment by eahefnawy** [comment]
Yep exactly. This is a breaking change in Alpha 2. So services created with Alpha 1 won't work with Alpha 2. What you can do is remove the service (maybe with Alpha1) and deploy it again with Alpha2. This way the stack should be updated to work with Alpha 2

**Comment by codepreneur** [comment]
Another problem with this, is that its impossible now to remove existing Alpha 1 services/lambdas and have to be done manually via AWS console...

**Comment by activescott** [comment]
is there a tag or a known commit hash for alpha1 so we can back up and remove without resorting to AWS console?

**Comment by ianserlin** [comment]
We diagnosed this by finding a bad CloudFormation stack with our service's name in the AWS console. In our case, the stack's status was `DELETE_FAILED`.

To fix: Either manually deleting the stack before trying to re-deploy, and/or renaming your service in `serverless.yml` from what it currently is (here's the aws nodejs template's default: `service: aws-nodejs`) to something new (for example `service: mycustomservice`) fixed the issue by disassociating our service with the bad cloudformation stack so that we could deploy again.

**Comment by flomotlik** [comment]
This should be resolved with #1638
