### ISSUE TITLE
Removing a service with 1.0.0-alpha.2 CLI gets stuck

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1617]
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

To not get stuck

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16961129/13360132-4de4-11e6-8f16-498c48d4734f.png)

Although resources are removed when I login to AWS console and check. You can replicate this bug by simply creating a new service and then removing it.

**Comment by codepreneur** [comment]
I think the issue might have been fixed:

![image](https://cloud.githubusercontent.com/assets/3421858/17176526/0807488a-5405-11e6-8e7d-ea88cd27161b.png)

**Comment by pmuens** [comment]
@codepreneur thanks for getting back!

You can specify that the DynamoDB will persist even if you remove it through CloudFormation (to keep the data). Maybe that's the reason why the table is still there.

**Comment by codepreneur** [comment]
Yeah, I think thats the reason @pmuens
