### ISSUE TITLE
Replace node-zip package with plain js-zip package

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1621]
Right now we use `node-zip` as our zipping package. However `node-zip` is "outdated" and uses `js-zip` under the hood. We should switch to plain `js-zip` so that we always get the latest features and have more functionality of zipping.

**Comment by chris-olszewski** [comment]
I would be interested in working on this.

**Comment by pmuens** [comment]
Awesome! 👍 

I'll mark it as `in-progress` let me know if you need any help along the way. The main zipping functionality can be found in the `package` plugin.

**Comment by pmuens** [comment]
Done with #1759
