### ISSUE TITLE
Organize & Refactor CF Logical Ids

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1627]
CF logical Ids naming standards are not super organized and not very predictable. Specially with APIG. It contains numbers and other variables, which is sometimes necessry, but sometimes it's not.

We should take another look at it and reorganize/refactor it now that we have a clear picture on which resources need to be referenced using this logical Id and make sure they're following a predictable pattern.

cc/ @pmuens @flomotlik

**Comment by pmuens** [comment]
Yes. Good idea! I too dislike the current convention which is also not that easy to understand (I have to look it up every time I work on a new plugin).

Here are related issues:

- https://github.com/serverless/serverless/issues/1357
- https://github.com/serverless/serverless/issues/1303

**Comment by pmuens** [comment]
Closing this one as the discussion happens in https://github.com/serverless/serverless/issues/1869
