### ISSUE TITLE
serverless remove does not work with Alpha 1 projects even if I add serverlessDeploymentBucketName

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1628]
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16986546/037da4fc-4e7f-11e6-9e7c-6d51c39dcd69.png)

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16986561/156e056c-4e7f-11e6-82cb-f0e673e4095a.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/16986590/4211f6fa-4e7f-11e6-852d-e38d0d75f3e8.png)

The bucket name that I add is basically the same one that was being used by Alpha 1

So the only way to migrate from Alpha 1 to Alpha 2 right now, is start a completely new project from scratch and copy paste everything.

**Comment by pmuens** [comment]
Hey @codepreneur I'm closing this once since we've already released beta.2 and the bug should have been resolved since then.

Reopen an let us know if you still face the issue! 💯
