### ISSUE TITLE
serverless deploy does not work with Alpha 1 projects even if I add serverlessDeploymentBucketName

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1629]
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16986900/0fafa20a-4e81-11e6-9df0-4311b62b88ce.png)

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/16986906/207121fe-4e81-11e6-9264-efe7427dd485.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/16986590/4211f6fa-4e7f-11e6-852d-e38d0d75f3e8.png)

The bucket name that I add is basically the same one that was being used by Alpha 1

So the only way to migrate from Alpha 1 to Alpha 2 right now, is start a completely new project from scratch and copy paste everything.

**Comment by codepreneur** [comment]
@pmuens @eahefnawy is this going to be fixed? I think ability to migrate projects is quite important

**Comment by pmuens** [comment]
@codepreneur Thanks for reporting this!

The error is already fixed in the v1.0 branch (with the help of this PR: https://github.com/serverless/serverless/pull/1639) and will be available in the beta we'll release soon.

Please let us know if this is still an issue!
