### ISSUE TITLE
Binary permissions issue (executable)

### ISSUE THREAD

**Issue by svdgraaf** [serverless/serverless#1630]
##### Serverless Framework Version: 
1.0

##### Expected Behavior:
Binaries are not uploaded as-is, executables are not accessible

##### Actual Behavior:
The zipping of the binaries ignores the file permissions, resulting in non-executable binaries on Lambda. As was also the issue with the non-alpha version (see: https://github.com/serverless/serverless/issues/960)

I'm working on a PR (simple fix), will update this issue with the PR.

**Comment by svdgraaf** [comment]
PR is: https://github.com/serverless/serverless/pull/1631

**Comment by pmuens** [comment]
@svdgraaf thank you for that! Great to have you here!
