### ISSUE TITLE
quickstart deploys fails e.message.split is not a function

### ISSUE THREAD

**Issue by ChristianDavis** [serverless/serverless#1632]
##### Serverless Framework Version: 
1.0.0-alpha.2
##### Operating System: 
Win 10
##### Expected Behavior:
Deploy
##### Actual Behavior:
Error
e.message.split is not a function

##### Additional Details:
This came from following the quickstart directly, and it suggests: 
For debugging logs, run again after setting SLS_DEBUG env var.

But, quickstart docs doesn't have any further directions on this, or where logs would be found (if set correctly)

**Comment by ChristianDavis** [comment]
AWS default profile wasn't setup correctly. After following http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html, 
got past this error

**Comment by skurilyak** [comment]
I ran into the same issue. I would consider adding AWS setup instructions to the Serverless documentation
