### ISSUE TITLE
Multi Worded keys in YAML files should not be camelCased

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1637]
camelCasing YAML keys is unconventional. We should switch to either an underscore or a dash between words.

**Comment by rajington** [comment]
I vote for hyphens (kebab-case). It seems to be a slightly more popular choice in YAMLs, and it matches well with `us-east-1` and plugin names like `serverless-optimizer-plugin` which would also appear in sls YAMLs.

**Comment by eahefnawy** [comment]
@rajington agreed!

**Comment by pmuens** [comment]
Hmm. This is not an easy one.

After working on https://github.com/serverless/serverless/pull/1663 I would say that we keep the `camelCase` naming. Custom resources would introduce this anyway. And a mixture of different styles is not that great IMHO.

Any thoughts?

/cc @flomotlik

**Comment by eahefnawy** [comment]
@pmuens great point about custom resources logical Ids! AWS in general has some restrictions on using hyphens that might become annoying.

Yeah I think @pmuens is right. I think it's better if we use camelCasing to avoid such issues.
