### ISSUE TITLE
Need ability to add additional mapping templates for request templates

### ISSUE THREAD

**Issue by activescott** [serverless/serverless#1640]
##### Feature Request:

Requesting the ability to add additional request templates. I want to trigger the mapping template for a new request content-type. In this case `Content-Type: application/scim+json`. 

##### Benefits:
This is necessary to implement the standardized REST-based SCIM APIs (brief example at https://tools.ietf.org/html/rfc7644#section-3.3)

Since there is no way to specify the request/mapping template, it will end up loosing the headers and I need the Authorization header at least.

##### Drawbacks:

* Complexity in serverless.yaml? 
* AWS-specific events in serverless.yaml?

FYI: Currently the relevant code is at https://github.com/serverless/serverless/blob/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L98

**Comment by activescott** [comment]
similarly, will need response templates: http://stackoverflow.com/questions/31329495/is-there-a-way-to-change-the-http-status-codes-returned-by-amazon-api-gateway

**Comment by eahefnawy** [comment]
Thanks for reaching out @activescott ... It's an interesting use case you have there. We're currently discussing supporting this [in issue 1593](https://github.com/serverless/serverless/issues/1593), but we're not super sure about the exact needs/use cases.

Could you please add your thoughts there? 😊 ... It'll help us push this forward and support it for you :)

**Comment by flomotlik** [comment]
This is very related to #1593 so I'm going to close this issue here, but we'll keep it in mind when doing the detailed planning on that feature. Definitely want that for one of our next releases.
