### ISSUE TITLE
Rename stage to Environment

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1643]
@erikerikson raised an interesting point in https://github.com/serverless/serverless/issues/1486#issuecomment-233804824 

Currently we're using Stage as a name for dev,QA,production setup. While this does follow the API Gateway naming convention, typically when talking about QA/DEV/Production you would use the name environment.

This is quite a big change (not just in code, but in how we named things so far). What do you guys think about changing this (in a backwards compatible way)?

@serverless/team @erikerikson @HyperBrain

**Comment by pmuens** [comment]
`environment` sounds good although I'm more familiar with the name `stage` (having a `testing`, a `development` and a `production` stage).

We have to make sure that we don't confuse the users with this `environment` as it's used at least twice when we make the change (`environment` variables and the renaming of `stage` to `environment`).

**Comment by eahefnawy** [comment]
To emphasize on @pmuens point, we also refer to stages/regions/serverless-vars collectively as environment (hence: `serverless.env.yaml`) ... imo this change might be confusing and I'm still not sure it's worth the effort. And I don't think the term `stage` is just an APIG convention. I've been familiar with the concept for years now and I think many users are.

**Comment by HyperBrain** [comment]
For me it really does not matter in the end if it is named environment or stage. I worked for companies using both. The difference in my opinion is, that stage makes clear that you have a step-wise movement of builds or artifacts through different levels of stability. Environment is more the configuration of the system where the actual code runs on.

**Comment by flomotlik** [comment]
Yeah @HyperBrain @eahefnawy @pmuens agree with you guys, this probably introduces more pain than its worth right now. Imho we shouldn't do this.
