### ISSUE TITLE
Add better documentation for custom resources section in serverless.yaml

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1646]
We should add better documentation on how to use the custom resources section (as described [here](https://github.com/serverless/serverless/issues/1598#issuecomment-233387991)) so that users know that they can use anything CloudFormation can do without having to wait for us to implement a plugin for it.

**Comment by eahefnawy** [comment]
We can do that by giving an example on supporting APIG Proxy as you mentioned. This way we'll let users know how to set up proxy and add custom resources at the same time 😉

**Comment by svdgraaf** [comment]
I'll see if I can create some documentation for this, I was working with custom resources anyway :)

**Comment by pmuens** [comment]
@svdgraaf That would be awesome!

You're such a great help!
Glad to have you in our community! 🎉

**Comment by svdgraaf** [comment]
I just started to work on the custom resources documentation, but then I found this page: https://github.com/serverless/serverless/blob/v1.0/docs/guide/custom-provider-resources.md

Doesn't that already describe how to setup the custom resources (proxy?)

**Comment by svdgraaf** [comment]
btw: can't we use an easier resource id than`RestApiApigEvent` for the apigateway resource? Something like `ServerlessApiGateway` or even `RestApigateway`?

**Comment by pmuens** [comment]
@svdgraaf Yes. We're planning to make the resource names easier / less verbose https://github.com/serverless/serverless/issues/1627

**Comment by eahefnawy** [comment]
@svdgraaf yep the proxy resource docs was added a day ago as an example and docs for proxy support. Feel free to PR a second (maybe simpler?) example if you got something in mind 😊

**Comment by svdgraaf** [comment]
@eahefnawy yes, I made an example which adds a proxy endpoint to a regular serverless apigateway, so you can proxy just one request for Example. I'll create a PR for it.

**Comment by pmuens** [comment]
@svdgraaf That's great! Looking forward to it!

**Comment by svdgraaf** [comment]
I added a S3 bucket example, and removed some (unnecessary) fields from the Proxy example, see the PR

**Comment by eahefnawy** [comment]
Thanks @svdgraaf 👍

**Comment by pmuens** [comment]
Awesome @svdgraaf you really rock 🎸 !
