### ISSUE TITLE
Make service name unique

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1647]
The service name is currently derived from the template we use to create the service.

This is problematic because two services who are created from the same template share the same name which yields to problem when deploying because the CloudFormation stack has the name of the service.

Service / CloudFormation stack names should have a unique value (like the serverlessDeploymentBuckt) so that they won't collide.

Relate issue #1563 

Should be done when https://github.com/serverless/serverless/pull/1644 is merged

**Comment by flomotlik** [comment]
Imho we can solve this by:

* Add a note to the serverless.yml that gets created to change the name
* Print a message to CLI to change the name after create

**Comment by pmuens** [comment]
Done like mentioned above with https://github.com/serverless/serverless/pull/1673
