### ISSUE TITLE
Event rule is not created and there is no error message

### ISSUE THREAD

**Issue by johnsgp** [serverless/serverless#1651]
Serverless Framework Version: 0.5.5
Operating System: Windows 10

**Expected Behavior**: When two functions have the same "event" of type "schedule" and both have the same "name", either both event rules should be created in AWS or there should be an error message when running **sls event deploy**.  The s-function.json files both contain:

```
  "events": [
    {
      "name": "schedule",
      "type": "schedule",
      "config": {
        "schedule": "cron(0/1 * ? * * *)",
        "enabled": true
      }
    }
  ]
```

**Actual Behavior**: There is no error message but only one event rule is created.  The output is:

Serverless: Deploying events in "dev" to the following regions: eu-west-1
Serverless: Successfully deployed events in "dev" to the following regions:
Serverless: eu-west-1 ------------------------
Serverless:   schedule (schedule event)
Serverless:   schedule (schedule event)

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
