### ISSUE TITLE
Add Serverless function based deployment plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1652]
This plugin should make it able to deploy separate functions (instead of the whole service).

**Comment by pmuens** [comment]
Here's a proposal which outlines possible implementation details:

**The deploy plugin**
We add a new subcommand to the `deploy` plugin (`serverless deploy function`).
Additionally we add corresponding lifecycle events.

**The package plugin**
The `package` plugin will be extended so that it can hook into the lifecycle events of the `deploy` plugin (the lifecycles of the `deploy:function` command).

It will have 3 additional hooks:

1. `before:deploy:function:createDeploymentPackage` --> Create a directory and copy the function into it so that the package plugin can zip it
2. `deploy:function:createDeploymentPackage` --> cd into the directory with the function and zip it
3. `after:deploy:deploy` --> Remove the temporary `.serverless` directory and previously created function directory

**Open Questions**
Right now the following happens when a user enters `serverless deploy`:
The `AWS deploy` plugin will hook into the lifecycle events of the `deploy` plugin and create the stack, compile the functions, compile the events, upload the services .zip file and update the stack.

We need to update only the corresponding function when the user enters `serverless deploy function --function foo`. So no need to create the stack etc. Where do we get the stack from. Do we fetch it with the help of the AWS API?

What if the stack is not yet deployed? This implementation enforces the user to always run `serverless deploy` before he can run `serverless deploy function --function foo`.

How do we deal with the .zip files in the bucket? Should the .zip files have a different naming schema? Because if we don't introduce another naming schema and the user deploys only functions 6 times the whole service won't work because the services .zip files which includes all the functions will be automatically removed and only the ones with the single function will be kept.

Feels like there are many brittle parts here. Seems like a bigger task.
Do you guys have any other ideas how we can implement it?

/cc @flomotlik @eahefnawy

**Comment by eahefnawy** [comment]
Yikes this change doesn't go very well with our current implementation.

Does this plugin only deploys the specified lambda function, without the associated events, just for the sake of "invoking a remote/deployed function"? If that's the case then I'm not sure how much value that will provide for developer experience during development.

Testing the individual deployed function doesn't guarantee that it'll work when it's integrated with the entire service and its event sources. Personally, I'd rather just cover the function code with local unit tests, and if there's something wrong with the handler layer (which should be rare), it'll covered by regular stage deployment.

@serverless/vip do you guys think this would provide value for you during development?

**Comment by flomotlik** [comment]
The value I see in having this separate deployment function would really be to have a simple way to say while you're developing locally and after you've set up a stage for you to deploy to in your provider you can very simply and quickly update specific functions. This makes it faster for you to iterate and test things in the live system that you wouldn't really be able to test locally in a nice way.

Having to go through the whole `serverless deploy` would just be a bit slow. The deployment through `serverless deploy` is imho fast for what it does (deploying the whole system and making sure all resources are in place) but when you know all resources are in place and you just want to update this piece of code running in this function its a bit much.

And we could simply use the `update-function-call` method of AWS that pushes it directly to AWS without having to go through S3.

**Comment by HyperBrain** [comment]
@flomotlik Nevertheless we should not forget to update the artifacts on S3 too, even if the code is actually uploaded via the API. That makes sure that everything stays consistent.

**Comment by flomotlik** [comment]
@HyperBrain imho this would make the deployment process longer. This update is really only for quick deployment during development, so we want to keep it as short as possible. It should imho be very clear that this is a bit of a more advanced tool and if you only deploy one function, but the code that is deployed is also deployed in another function you might introduce issues (and you should be able to deploy to multiple functions at once, e.g. `serverless deploy function --function a --function b`).

So definitely not a tool for production deployment or potentially even staging. Its really geared towards providing you with a good and fast experience when you just want to get this one code update into your personal development stage to click through the website or infrastructure and test it in a more real life environment.

Consistency is imho not a goal here. For anything that should be consistent and work guaranteed together with resources and traceability for the whole service the `serverless deploy` command should be used.

**Comment by HyperBrain** [comment]
Agree. Maybe it would then be good to have a global configuration where you can prohibit this functionality for a specific stage. Having it allowed for every stage will lead to developers just "overwriting" deployed functions in e.g. production what is very dangerous.

**Comment by flomotlik** [comment]
@HyperBrain imho that is authorisation that should be handled through e.g. IAM. We should make it very clear in our docs (and potentially when executing) that this is a potentially dangerous command that could lead to inconsistencies. But there isn't really anything we can do to prevent people from deploying into a specific environment if they have the IAM authorisation to do so. Any config we put in place in the serverless.yml could easily be overwritten and the person could deploy.

So its definitely also a Team culture thing in my opinion.

**Comment by pmuens** [comment]
Alright. Then we don't need to go through CF at all. I like the idea that this plugin is only used for fast testing deployments.

To sum this up:

- The user enter `serverless deploy function --function foo --function bar`
- This will overwrite the function code of `foo` and `bar` with the current one
- It goes directly through the AWS SDK API (not CloudFormation / S3)
- It will error out if the function is not yet deployed (the user has not run `serverless deploy` before)
- We should add docs which outline how this should be used / that this is a more advanced ("dangerous") action
- We can control if the user can update a function this way via IAM (can be added later on)

Is this correct? If yes, then I'll start the implementation phase.

**Comment by flomotlik** [comment]
@pmuens sounds great, please get started on this

**Comment by erikerikson** [comment]
@flomotlik I think @HyperBrain had a great and easy to implement suggestion.  To use this feature you must define a reserved variable for the stage.  If it isn't defined, the plugin can just report a message that the variable must be defined for the stage instead of running.  A culture of responsibility and discipline is always key but the point is to guard against unintended mistakes despite culture.

**Comment by flomotlik** [comment]
@erikerikson I do see the point of making unintended mistakes really really hard, but imho having to add different keys every time I want to deploy a single function would be cumbersome and my assumption is that people would very quickly move to simply adding them for all functions by default to make it less cumbersome and the guard against unintended consequences is gone again.

One thing we could implement (in case we see this issue come up) is a custom config attribute like "allow-direct-push" in the provider config, so e.g. the AWS single function deployment plugin could check that config parameter and if its set to false then you simply can't deploy directly. This would at least stop people from doing it and they would have to think twice and actively work around this to deploy directly.

I'm still not sure if this isn't an issue we can capture through good docs and clear warnings though (and imho we should definitely do this as a first step and see if people run into this problem)

**Comment by erikerikson** [comment]
Hmm...  What you're describing is different than what I was thinking - sorry for not being more clear.  :)  I was assuming it would be a stage-wide setting so that you could set yourself up to do this in your dev/ci/whatever-you-call-it stage and maybe your private dev env stage but not anywhere else and especially not prod.

I definitely agree that per-function enablement wouldn't produce a good ux.

This all said, it's not a high priority to me, @HyperBrain's suggestion just made sense to me.

**Comment by johncmckim** [comment]
@erikerikson @HyperBrain like protected branches on Github. Even if it's not on by default, the ability to turn that on for a stage would be important.

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1696
