### ISSUE TITLE
Replace default integration request template with AWS standard one

### ISSUE THREAD

**Issue by fridaystreet** [serverless/serverless#1664]
* Check if an Issue already exists for this
* Add the relevant label(s)
* Be kind :)

Feature Request Template ------------------------------------------

##### Feature Request:
Replace the integration request template that gets added to methods with the standard 'Method Request Passthrough' template. Or provide a way to override the default easily
##### Benefits:
All available information is included, some is missing from the current one. Also I tried to update the template in the API console to get access to the extra info like resourcePath and could not get it to work. I raised a support ticket with AWS and after a few days of looking in to it, they advised to use the standard template which worked. 
* Benefit one...

##### Drawbacks:
Can't think of any
* Drawback one...

##### Additional Details:
Here's the standard template

See http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
 This template will pass through all parameters including path, querystring, header, stage variables, and context through to the integration endpoint via the body/payload

#set($allParams = $input.params())
{
"body-json" : $input.json('$'),
"params" : {
#foreach($type in $allParams.keySet())
    #set($params = $allParams.get($type))
"$type" : {
    #foreach($paramName in $params.keySet())
    "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
        #if($foreach.hasNext),#end
    #end
}
    #if($foreach.hasNext),#end
#end
},
"stage-variables" : {
#foreach($key in $stageVariables.keySet())
"$key" : "$util.escapeJavaScript($stageVariables.get($key))"
    #if($foreach.hasNext),#end
#end
},
"context" : {
    "account-id" : "$context.identity.accountId",
    "api-id" : "$context.apiId",
    "api-key" : "$context.identity.apiKey",
    "authorizer-principal-id" : "$context.authorizer.principalId",
    "caller" : "$context.identity.caller",
    "cognito-authentication-provider" : "$context.identity.cognitoAuthenticationProvider",
    "cognito-authentication-type" : "$context.identity.cognitoAuthenticationType",
    "cognito-identity-id" : "$context.identity.cognitoIdentityId",
    "cognito-identity-pool-id" : "$context.identity.cognitoIdentityPoolId",
    "http-method" : "$context.httpMethod",
    "stage" : "$context.stage",
    "source-ip" : "$context.identity.sourceIp",
    "user" : "$context.identity.user",
    "user-agent" : "$context.identity.userAgent",
    "user-arn" : "$context.identity.userArn",
    "request-id" : "$context.requestId",
    "resource-id" : "$context.resourceId",
    "resource-path" : "$context.resourcePath"
    }
}

Discussion template  ----------------------------------------------

**Comment by fridaystreet** [comment]
A little further testing and it seems you can't actually override the serverless template even if you specify an AWS resources update json. For example, I have an updated PostMethodApigEvent0 resource in a json file that adds Status code responses and templates for those status codes. It also defines an alternative integration request template. All of the other settings get applied to the cloudformation template, but the integration request template is being ignored and is always the serverless one.

**Comment by fridaystreet** [comment]
Worked out that the source and destination objects in the merge statement could be deemed as the wrong way round. The template is the source object and is being applied over the top of any custom resources that have been defined. This means any customisation to the resources that you might want to do, like custom request templates or apply a custom authorizer, are being overwritten by the default templates every time.

I'm happy to submit a pull request if the change can be accepted?

**Comment by flomotlik** [comment]
This is very related to #1593 so I'm going to close this issue here, but we'll keep it in mind when doing the detailed planning on that feature. Definitely want that for one of our next releases.
