### ISSUE TITLE
variables used in json refs are not replaced before refs are resolved to objects 

### ISSUE THREAD

**Issue by fridaystreet** [serverless/serverless#1665]
* Check if an Issue already exists for this
* Add the relevant label(s)
* Be kind :)

Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
alpha
##### Operating System: 
linux mint 18
##### Expected Behavior:
Given a yaml config of 
resources:
    Resources:
        $ref: ${myFilePathVar}

Would expect the variable to be replaced and the reference resolved to an object
##### Actual Behavior:
lib/classes/Service.js parses the refs in the yaml file before it replaces the variables with values from env file.

##### Stack-Trace (Optional):

Discussion template  ----------------------------------------------

##### Discussion:
Could be resolved something like this around line 217 of Services.js. However I can't get this to work as it throws an error about not being able to find utils. See stack trace below

`                 val = replaceall(variableSyntax, value, val);`
`                //just after the line above`
`                if (variableName.indexOf('file--')) {`
`                  val = that.serverless.utils.readFileSync(val).toString();`
`                }`

This would allow you to specificy a variable name like ${file--my-cf-json-variable}

TypeError: Cannot read property 'utils' of undefined
    at /usr/lib/node_modules/serverless/lib/classes/Service.js:218:72
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/classes/Service.js:168:42)
    at walker (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:190:22)
    at /usr/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)
    at /usr/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)
    at /usr/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)

**Comment by eahefnawy** [comment]
@fridaystreet this is intentional because we want to also support populating variables that are defined in your CF templates. If we do it the other way around, you'll be able to have the file path as a variable, but you will not be able to reference variables inside your template. So we had to make a tiny sacrifice 👼

**Comment by eahefnawy** [comment]
@fridaystreet FYI there's an ongoing discussion on changing how stages/regions/variables works. You might find it insightful:
https://github.com/serverless/serverless/issues/1707

Closing this one for now ... Thanks for opening this up 😊

**Comment by fridaystreet** [comment]
yep makes sense, thanks for the heads up :-)
