### ISSUE TITLE
Unable to set array type variable via CLI

### ISSUE THREAD

**Issue by ssemyonov** [serverless/serverless#1669]
I'm working on some automation around deployment of serverless projects with VPC-enabled functions. In my setup every stage is deployed to a separate VPC, therefore I need to specify ```subnetIds``` variable at the stage level.
I'm trying to achieve that using CLI command ```serverless variables set --type stage --stage qa7 --key subnetIds --value ["subnet-11111111","subnet-22222222"]```, however this command results in variable being treated as a string: ```"subnetIds": "[subnet-11111111,subnet-22222222]"``` (additionally, nested quotation marks are removed).

Is there a way to set array type variable from CLI to avoid modifying *s-variables-qa7.json* directly? 

##### Expected Behavior:
Variable is set as array: ```"subnetIds": ["subnet-11111111","subnet-22222222"]```

##### Actual Behavior:
Variable is set as a string: ```"subnetIds": "[subnet-11111111,subnet-22222222]"```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
