### ISSUE TITLE
Make aws_modules part of the search path

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#168]
What would really work is putting `aws_modules` in the search path for `npm` when deploying/running.

This would make it possible to do this:

`var myAwsumObject = require('myAwsumModule').something;`

So no need to do: 

`var myAwsumObject = require('./../../myAwsumModule').something;`

**Comment by ac360** [comment]
Can npm do this?  The other problem is that we use browserify for optimizing lambdas and browserify would also have to be trained to do this, which may not be possible.

**Comment by remicastaing** [comment]
You have to overwrite some method used by require to do that. It is no more possible to add other require path.
Before running browserify you would have to copy the required files in the right place.

**Comment by jwulf** [comment]
It doesn't use $NODE_PATH from the environment? 

It looks like it does: https://github.com/substack/node-browserify/issues/72
