### ISSUE TITLE
sls remove fails if IamRoleLambda has at least one policy attached

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1689]
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

to completely remove sls project via cloudformation

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17196428/84fee814-545c-11e6-922a-2490d671a48e.png)

and: 

![image](https://cloud.githubusercontent.com/assets/3421858/17196455/ad4a4e12-545c-11e6-98cd-87a43e03ffdb.png)

and then when you manually detach the policy and run `sls remove` again, it fails again, because the first deletion was only partial

![image](https://cloud.githubusercontent.com/assets/3421858/17196585/b22ddce0-545d-11e6-9695-a3b94ec2e510.png)

Expected behaviour or a bug?. @pmuens ? @eahefnawy ?

**Comment by pmuens** [comment]
Hmm. This is a strange bug. We've removed the IamRoleArnLambda with a recent PR (do you run Serverless from the v1.0 branch).

Might this cause the error @eahefnawy?

**Comment by eahefnawy** [comment]
@codepreneur how do you attach your policy? as a custom resources in `serverless.yml`? or using AWS console? If AWS console then this error is expected, because removing the role doesn't include removing the attached policy (because it's not in the CF template). But I think it should work if you have it defined as a CF resource in `serverless.yml`

**Comment by codepreneur** [comment]
@eahefnawy using AWS console, will try defining it as CF resource and report back.

**Comment by eahefnawy** [comment]
@codepreneur FYI we just added a new way to add policy statements. [check this issue for more info](https://github.com/serverless/serverless/issues/1535). So this should not be an issue anymore. Closing 🙌 

Thanks for reporting! 😊
