### ISSUE TITLE
Document how to use SLS_DEBUG env var

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1690]
The CLI shows that the user can use SLS_DEBUG to get a stack trace when an error occurred. However it's not shown how he can enable it.

We should add a comment next to the error message that the user can enable it by exporting the `SLS_DEBUG` variable.

**Comment by mthenw** [comment]
Instead of adding documentation maybe we should remove it :)
https://github.com/serverless/serverless/issues/1720

**Comment by pmuens** [comment]
Yep. Really like the ideas outlined in #1720. `SLS_DEBUG` really feels tedious...

**Comment by flomotlik** [comment]
Imho we should document this here first and then have #1720 as a potential contribution from the community. Its not as important right now in my opinion to put resources into it, but would be really nice to have.

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1729/

**Comment by olegZastavnyi** [comment]
Where is this document located ?

**Comment by pmuens** [comment]
@olegZastavnyi you can find it here: https://github.com/serverless/serverless/tree/master/docs#running-in-debug-mode

**Comment by olegZastavnyi** [comment]
@pmuens Thanks

**Comment by molinto** [comment]
When is it in the docs please?

$ serverless invoke local --function myfunction --path test/myfunction.json

```
Cannot read property 'local' of undefined
For debugging logs, run again after setting SLS_DEBUG env var.

```

**Comment by pmuens** [comment]
@molinto Seems like it's missing in the docs. Thanks for mentioning this! 👍 
Reopening it so that it will be added again soon!

You can use `export SLS_DEBUG=true` and then run again.

**Comment by molinto** [comment]
Ran this:
```
export SLS_DEBUG=true
```

Then got this in console:

```
  Type Error ---------------------------------------------
 
     Cannot read property 'local' of undefined
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'local' of undefined
    at PluginManager.validateOptions (/home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:54:57)
    at PluginManager.run (/home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:82:10)
    at Serverless.run (/home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/lib/Serverless.js:83:33)
    at /home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/bin/serverless:18:50
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/bin/serverless:10:28
    at Object.<anonymous> (/home/sharry/.nvm/versions/node/v4.6.0/lib/node_modules/serverless/bin/serverless:19:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.

```

**Comment by mannharleen** [comment]
For anyone wanting a quick answer, in windows use:
set SLS_DEBUG=*

**Comment by christopher-howard** [comment]
To only show SLS_DEBUG output for one command execution, run in terminal:
SLS_DEBUG=* <command>

For example I ran:
SLS_DEBUG=* serverless deploy

**Comment by Bookrage001** [comment]
and in windows power-shell 
`$env:SLS_DEBUG="*"`

**Comment by 47arathore** [comment]
For me this works

> To only show SLS_DEBUG output for one command execution, run in terminal:
> SLS_DEBUG=* commandhere
> 
> For example I ran:
> SLS_DEBUG=* serverless deploy

For me also this works with a bit of modification > set SLS_DEBUG=* && sls create_domain
