### ISSUE TITLE
Optionally remove core-cf requirement for creating an S3 Bucket

### ISSUE THREAD

**Issue by nhumphreys** [serverless/serverless#1693]
##### Feature Request:

Remove/make optional the requirement for a distinct S3 bucket for deployment of every project + stage + region configuration 

##### Benefits:

Maintain existing functionality, but give users the option to choose a bucket and or prefix in which the zip payloads would sit.

The main driver for this is that by default AWS has a limit of 100 S3 buckets, you can ask for a service increase but this is not a long term solution.

Another driver behind this is to have CI/CD integration in which the project stack has been created by a PowerUser first. Then the CD system uses the checked in configuration and stack discovery to then perform lower risk operations like: update lambda code and api gateway stages etc, but not have create IAM access and be able to create and destroy buckets

##### Drawbacks:

core-cf.json would need to change:

- A conditional for bucket creation and parameter passing from project config OR
- injection of S3 resource and Output Resource CFN config based on project config
- initializeResources would need to inject the params OR
- inject the S3 resource if in default mode
- bucket.js would need to be respectful of a non-managed bucket and also
- restrict itself to deleting the project prefix and not the entire contents of and the bucket

##### Additional Notes:

Hopefully that makes sense and the approach would not be insane, but if there is another way to override this behaviour with plugins then that would be great, but I get the feeling this would touch some core SDK parts and not be possible.

I am happy to contribute work on a PR for this soon, to get a couple of projects over the line.

**Comment by flomotlik** [comment]
Thanks for the feedback @nhumphreys , this is also targeted in #1513 

Closing this one for the other one
