### ISSUE TITLE
Options passed via shortcuts don't seem to be available during variable population

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1709]
@svdgraaf  mentioned in Issue #1704 that options passed via shortcuts (mainly stage/region) are not available in the Service class during variable population.

Will investigate this further.

cc/ @flomotlik @pmuens

**Comment by pmuens** [comment]
I think it's implemented in this PR: https://github.com/serverless/serverless/pull/1711

**Comment by fridaystreet** [comment]
I think this is a related issue. when using -s instead of --stage everything apart from the actual function names seems to work. function names still default to dev

eg. sls deploy -s prod

Results in lambda function names with dev instead of prod. using --stage works correctly

**Comment by pmuens** [comment]
@fridaystreet thanks for reporting!

We've recently updated the code where the `functionName` is generated (as it was unreliable before). The current Serverless version from the master branch should resolve your problem. (here's the PR which fixed that: https://github.com/serverless/serverless/pull/1753).

Let me know if you still face the issue!

**Comment by pmuens** [comment]
Closing this one since it should be resolved in the latest Serverless version.

Let us know if this is still an issue and we'll reopen!
