### ISSUE TITLE
Params and Query String is only available in get method

### ISSUE THREAD

**Issue by smkamranqadri** [serverless/serverless#1713]
Params and Query String in only available in get method, when i use post or put method it gives the undefined.

**Comment by flomotlik** [comment]
Hi, thanks for using the Serverless Framework. In the Github Issues here we try to only cover bugs or new feature discussions. Anything that is more a support question would be better asked in [our forum](http://forum.serverless.com). We're happy to help out in the forums to make sure you have a great experience there.

**Comment by smkamranqadri** [comment]
Thx
