### ISSUE TITLE
Refactor PluginManager code to support deeply nested commands

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1716]
We should refactor the `PluginManager` class to support deeply nested commands (infinitely nested commands) as outlined in https://github.com/serverless/serverless/pull/1715

This can be done via e.g. recursions etc.

Right now only maximal 2 level deep commands are support (and the code is repetitive).

/cc @eahefnawy @flomotlik

**Comment by flomotlik** [comment]
Imho not necessary. 2 levels are imho more than enough currently. If we need more we'll wait for the feedback.
