### ISSUE TITLE
Add support for external templates

### ISSUE THREAD

**Issue by license2e** [serverless/serverless#1717]
##### Feature Request:

Add support for third-party templates. 

##### Benefits:

* Separate repos for templates
* Allows for more boilerplate/template code

##### Drawbacks:

* None

##### Additional Details:

Something like:
`serverless create --template=github.com/<user>/serverless-golang-template`

Note: originally suggested by @mthenw: https://github.com/serverless/serverless/pull/1712#issuecomment-236551798

**Comment by flomotlik** [comment]
Yup I definitely like this feature. Its something that has come up before. I don't know if we have the time to implement it ourselves any time soon though, but I'll add the help-wanted label
