### ISSUE TITLE
Move functionName generation to central place

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1718]
Currently the functionName can be custom or is created out of the `service` name, the `stage` and the function `name`. This name-Generation should be done at a central place and re-used / accessed in the different plugins (e.g. invoke, deploy / complie function, single function deployment, etc.).

See comments here: https://github.com/serverless/serverless/pull/1696 for more details

**Comment by eahefnawy** [comment]
Resolved with #1753
