### ISSUE TITLE
Let single function deployment extend package plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1719]
Right now we create a new instance of the `package` plugin in the "deploy single function" plugin.

The "deploy single function" plugin should extend the "package" plugin to make it easier to re-use the "package" plugins functionality.

**Comment by tobyhede** [comment]
👋 Attempting this one.

**Comment by tobyhede** [comment]
So ... comment in the PR suggests subclassing may not be the right approach.

**Comment by pmuens** [comment]
Thanks for taking the time to jump into this one @tobyhede!

I'll look into the PR as well.

**Comment by pmuens** [comment]
Closing this since it's a stale issue and not planned anymore.

Thanks @tobyhede for your contribution!
