### ISSUE TITLE
Establish Community Plugin Repository

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1722]
We should have an official repository where we list all the custom plugins the community authored. A plugins directory.

cc/ @pmuens @flomotlik

**Comment by pmuens** [comment]
Great. Here are some questions we might want to answer:
- How should the structure look like?
- What are the initial plugins we can post there?
- Do we keep v0.5 and v1 plugins there?
- Do we add a static GitHub hosted website where we can make it searchable (like this one: https://justserverless.github.io/serverless-registry/)?

**Comment by eahefnawy** [comment]
> How should the structure look like?

I vote for keeping it as simple as possible, just a list of plugins with one line description just like we had in the README. With a quick intro for the repo.

> What are the initial plugins we can post there?

We currently don't have any plugins for v1, so it'll probably be empty for now.

> Do we keep v0.5 and v1 plugins there?

I don't think it should include v0 as we're slowing deprecating it (ie. moving v1 into master). 

> Do we add a static GitHub hosted website where we can make it searchable

imo that's an overkill right now. We don't even have any plugins for v1 right now.

**Comment by pmuens** [comment]
But this repo will contain the whole code, right?
I understood it that this repo is a repository which includes community plugins where dedicated community collaborators maintain them and make sure that they'll stick to a specific quality standard.

I would also not include v0 plugins as they'll mess everything up. v0 will be deprecated anyway.

**Comment by eahefnawy** [comment]
> I understood it that this repo is a repository which includes community plugins where dedicated community collaborators maintain them and make sure that they'll stick to a specific quality standard.

oh you're right, I forgot about this one. I imagine the list will simply link to the internal plugin folder in the repo.

**Comment by gladkikhartem** [comment]
Today I've came up with an idea and wanted to share it with you.
The idea is to be able to integrate other's people endpoints in your project instantly from npm module. So from user user will just npm install the endpoint he needs and add it to the "plugin" or "endpoint" list in s-project.json and endpoint will be available for him.
for example: 
npm install --save serverless-lib-jsonToXml   
and add to s-project.json 
"endpoints": [
    "jsonToXml" :  {
      "location" :  "/endpoint path/",
       .................... some endpoint specific data, apiKeys, configs, settings etc...
     }
]
This will slightly increase code reuse between developers. 
It could be implemented the same way as plugins, but will be called "endpoints". We could use the same code for both plugins and endpoints with small changes.

**Comment by pmuens** [comment]
@flomotlik any updates on this one? Do you need help there?

**Comment by pmuens** [comment]
The repository for the community plugins can be found here:

https://github.com/serverless/community-plugins

**Comment by nicka** [comment]
The project needs an example plugin to get people started 👍 Some use cases on how to hook into sls actions.

**Comment by flomotlik** [comment]
@nicka created an issue for that: #1868

**Comment by nicka** [comment]
Perfect!!!

Verstuurd vanaf mijn iPhone

**Comment by flomotlik** [comment]
This is now started here with a README: https://github.com/serverless/community-plugins
