### ISSUE TITLE
Move variableSyntax property into the default property in serverless.yml

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1728]
currently `variableSyntax` property is at the highest level of `serverless.yml` … we should move it to `defaults` along with stage and region because it’s provider agnostic and it’s basically about overwriting the default variable syntax.

- [x] Move `variableSyntax` property into `defaults` object
- [x] Add docs for `variableSyntax`

cc/ @flomotlik @pmuens

**Comment by flomotlik** [comment]
Do we even need that feature? Is that something thats an issue for people, or can we simply remove it (or leave it undocumented?) Or was this born out of a specific use case you guys had in the past?

**Comment by flomotlik** [comment]
Ok, trying to think of other ways to solve this, but anything from only replacing when there is actually a specific value present to changing the regex to allowing you to ignore it on specific strings just makes things even more complex.

Lets do this. @johncmckim if you have any feedback on this very much appreciated

**Comment by johncmckim** [comment]
@flomotlik my initial thought was a feature to escape the variable i.e. `$${clientId()}` with regex using a negative lookbehind `(?<!\$)\${([\s\S]+?)}`. The escaped variables could then be fixed on a second pass i.e. match `\$(\${([\s\S]+?)})` and remove first `$`.

An alternative would be to not touch missing variables and leave them as is. However, I'm not sure whether or not this would lead to other issues, but it seems likely.

The custom variable syntax is more flexible and I assume less complex to implement.

**Comment by flomotlik** [comment]
>my initial thought was a feature to escape the variable i.e. $${clientId()} with regex using a negative lookbehind (?<!\$)\${([\s\S]+?)}. The escaped variables could then be fixed on a second pass i.e. match \$(\${([\s\S]+?)}) and remove first $

Yeah I thought about different ways of escaping it as well, but I think it will simply lead to other issues in the future when somebody wants to use $${} for something. So we'd be constantly pushing this out. The only real "solution" to this would be to have a ridiculously complex syntax that nobody would use, but that kind of defeats the purpose :D

> The custom variable syntax is more flexible and I assume less complex to implement

Yup we basically have that implementation already. From a user perspective is that a sufficiently good way to change the variable replacement for you? Would you need this regularly in various places or is it only something you need in one service? Just want to make sure this is only something that happens rarely.

**Comment by johncmckim** [comment]
@flomotlik So far I have only seen this issue with the new AWS IoT CloudFormation resources. In the small project I am working on now I have a IoT service, Web backend service and chat backend service. I only have to update the `variableSyntax` for the IoT service.

I think this is a reasonable user experience, if it is well documented. The solution is very easy to implement. In the end whether I use `${foo}` or `${{bar}}` isn't that important.

If this solution isn't well documented that could lead to frustration. It may even be worth adding help into the cli error message. This would allow people who hit this issue but haven't read the docs to identify the solution quickly.

**Comment by johncmckim** [comment]
Btw, if this is an easy-pick I'm happy to create a PR for it.

**Comment by eahefnawy** [comment]
@johncmckim thanks for pitching in. Feel free to get started on it 😊 ... It's tagged for our next release. If you face any issues or have any questions, just ping us! ☺️

**Comment by pmuens** [comment]
Will be done with https://github.com/serverless/serverless/pull/1764
