### ISSUE TITLE
Serverless response/request models for the API endpoints  

### ISSUE THREAD

**Issue by nickchisiu** [serverless/serverless#1734]
##### Feature Request:

Add current https://www.npmjs.com/package/serverless-models-plugin as native sls feature . I think that in order to be fully-aligned with the sls best practices the plugin should be modified to support s-models.json|yml for different  functions as different files like s-function.json|yml does which serverless-models-plugin currently I'm aware supports only a single  s-models.json|yml file stored in the main project root directory ( that file gets huge when you add more models for API endpoints ). So I suggest to modify the serverless-models-plugin to be welded in the sls core and I would be more than happy to implement it if this get accepted :) 
##### Benefits:
- API gateway will act as a reliable API documentation tool similar to Swagger documentation ( at least AWS can offer that )
- engineers will know how to consume an API service deployed with sls
- will enforce users to send only payloads to the API gateway specific to the models ( this can be prototyped as a validation feature too )
- having request and response models for every API endpoint would be really nice :)

**Comment by kfloz** [comment]
@flomotlik I know there is quite a lot of discussion on swagger at the moment.  is there at least in the mean-time roadmap support for API endpoint models?  Even if in serverless.yml instead of swagger, would love this feature natively.  Is this plug-in upgraded to serverless v1.0.0?

Thanks!

**Comment by flomotlik** [comment]
At the moment we don't plan to implement model support ourselves, but I know that there are some efforts under way by contributors to get this in. I'm totally open to getting this in, we're just not going to work on it ourselves so I'm closing here for now.

**Comment by tchock** [comment]
We wrote a plugin to add models support to Serverless v1. 
https://github.com/9cookies/serverless-aws-models

Hope this helps the people wanting to automatically add models to the generated API Gateway methods :)

**Comment by dkobia** [comment]
@tchock thanks for the plugin, it was incredibly useful.

**Comment by cdichiara** [comment]
@tchock you're a lifesaver man, thank you!
