### ISSUE TITLE
Improve AWS credential handling, documentation and onboarding

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1736]
For users without prior knowledge of AWS its hard to understand how to get credentials in place to get started with using AWS.

This negatively influences the onboarding experience as users don't really know how to even get started. We need to have better documentation and potentially a simple onboarding command that could either set credentials or validate them.

Tasks:
- [ ] Improve documentation on AWS documentation
- [ ] Discuss onboarding command that could help with credentials

**Comment by DavidWells** [comment]
something like:
```
sls setup --provider aws --key XYZ --secret ABC
```

1. this checks the `.aws/credentials` exist
2. if it exists, it checks for for [default] credentials block and then adds it if it doesn't exist
2a. doesn't exist create `.aws/credentials`, then run 2.

Basically a wrapper for this process https://github.com/serverless/serverless/blob/v1.0/docs/guide/provider-account-setup.md

The `sls setup` command is meant to streamline EVERY part of the external provider setup process we can to get users **TTFD** (Time to first deploy ©) as quick as possible. 

(some stuff like creating initial IAM role in AWS are out of our control)

Related: https://github.com/serverless/serverless/issues/1727

**Comment by ac360** [comment]
Proposed Doc Structure:

```
Quick Start: (this section is provider agnostic and very concise and just lists the commands)
     - Installing Serverless
     - Creating Services
     - Deploying Services
     - Invoking Functions
     - Removing Services

Core Concepts:
     - Services
     - Functions
     - Events
     - Resources
     - Environment (stages, regions & vars)

Configuration Guide:
    - AWS Config
        - serverless.yaml
            - Functions
            - Events
                - S3 Events
                - Schedule Events
                - HTTP Events
            - Resources
        - serverless.env.yaml
        - handler.js
    - Azure Config

Custom Plugins:
     - Installing Plugins
     - Creating Plugins
```

**Comment by ac360** [comment]
@DavidWells +1 Later, we can see if people want to persist other profiles with this command too.  But right now, keeping it simple and focused on only creating the `default` profile will help a lot.

**Comment by pmuens** [comment]
I really like the `serverless setup`command. Additionally I would make this work in a way that it will be automatically run when the user enters another command but has not yet setup his credentials.

E.g. he enters `serverless create`. Then Serverless will check if the credentials are setup and if not will prompt the setup steps. This way the user has not to run the `setup` process by hand.

Here's a link to another issue which discusses a new doc structure we've talked about the other day https://github.com/serverless/serverless/issues/1522

**Comment by ac360** [comment]
RE: current docs - At the moment, I'm trying hard to find how VPC support works in `serverless.yml`, but it's not obvious where to look.  I've clicked around for a few minutes now.  No luck.

**Comment by estahn** [comment]
@ac360 Here is some documentation: https://github.com/serverless/serverless/blob/v1.0/docs/guide/deploying-a-service.md#deploying-vpc-configuration-for-lambda

This will not work since the Iam Role doesn't have the necessary permission. I assume this isn't fully supported by serverless yet.

> The Lambda function execution role must have permissions to create ENIs. AWS Lambda provides a permissions policy, AWSLambdaVPCAccessExecutionRole, with permissions for the necessary EC2 actions (ec2:CreateNetworkInterface, ec2:DescribeNetworkInterfaces, and ec2:DeleteNetworkInterface) that you can use when creating a role. You can review the policy in the IAM console.
>
> Source: http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

**Comment by ac360** [comment]
Thank you, @estahn.  I found it.  The point is just to demonstrate that there is no obvious place to look.  Sticking VPC config into the deploying a service section is confusing.  There should be one place to look to see all AWS config details for `serverless.yml`.  Much easier to maintain too.

**Comment by estahn** [comment]
@ac360 I agree.

**Comment by chalfant** [comment]
Please consider also accepting the environment variable-based configuration of credentials in the same manner as the AWS CLI and SDKS. This helps those of us who use the Secure Token Service to assume roles in other accounts.

See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment

**Comment by estahn** [comment]
@ac360 Should we create a separate ticket for the Iam Role issue?

**Comment by flomotlik** [comment]
@chalfant we do support this. We're using the official AWS Node SDK and it should pull those environment variables: https://github.com/serverless/serverless/blob/master/docs/guide/provider-account-setup.md Let us know in case this doesn't work

**Comment by flomotlik** [comment]
@estahn there is an issue created for it in #1535 

I've just moved this up in priority so we can get this up and running fast. Shouldn't be too hard I think

**Comment by chalfant** [comment]
@flomotlik Excellent. I'll give it a try.

**Comment by nicka** [comment]
What about multi profile support? Atm it's only possible to use the `default` profile right?

**Comment by flomotlik** [comment]
@estahn @chalfant We've just implemented custom IAM policy support on master: https://github.com/serverless/serverless/pull/1749

@nicka you can use `--profile` to use a different profile that is defined in your ~/.aws/credentials file

**Comment by nicka** [comment]
@flomotlik Awesome 🍻

**Comment by flomotlik** [comment]
@nicka sorry I mixed something up there, we don't currently have --profile in the framework. Here you can see the implementation for aws where it selects the profiles. You can set them through the default environment variables though.

Would be interesting to have --profile support as well, shouldn't be too hard. Probably just looking for the profile option and if its set use that one.

**Comment by nicka** [comment]
@flomotlik I see! 

Confirmed, it works when I specify an `AWS_PROFILE` environment variable. This could also be part of the proposed `.env` support within #1707.

**Comment by samdj** [comment]
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

Currently profiles are not used when configured in the `serverless.env.yml`
```yml
stages:
  dev:
    vars:
      profile: test
```
It is injected currently as such `new AWS[service]({ region: "ap-southeast-2", profile: "test" )`.

Seems like you need to actually do it this way:
```js
var credentials = new AWS.SharedIniFileCredentials({profile: 'work-stuff'});
AWS.config.credentials = credentials;
```

**Comment by pmuens** [comment]
Hey @samdj thanks for chiming in!

Yes, we're currently rethinking the whole environment variable handling in this issue:
https://github.com/serverless/serverless/issues/1801
Happy to have your feedback on this one!

Furthermore there's a feature in the making which makes it easier to switch between profiles:
https://github.com/serverless/serverless/issues/1787
(Also happy to have your feedback here!)

Hope that makes everything a little bit more clear. Otherwise just drop a line 👍

**Comment by rowanu** [comment]
Hey guys, just noticed this ticket. @samdj's comment is related to the issue I raised separately #1940. I will plan to update the docs at the same time (just updating my fix to work with new variables) and hopefully address this issue too.

I'm not sure about @DavidWells' comment on new functionality - I don't Serverless should be modifying files outside of the service directory on principal (like `.aws/credentials`). It would also require the logic to be much more complicated (e.g. what if a profile with the same label but different credentials already exists - do you overwrite them?, etc)

**Comment by erikerikson** [comment]
Hey All.  I've implemented a PR (#2229) that provides credential configuration either directly using key/secret/token or via a profile.  These can be provided on a broad or stage-specific basis through serverless.yml or environment variables.

Please take a look and let me know what you might like to have changed.

I didn't implement a cli flag for credentials or profile but that or any other credential ingest method would be easy to add in.

**Comment by pmontrasio** [comment]
I followed the instructions and after this ([here](https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/01-setup.md#setting-the-aws-api-key--secret))

    export AWS_ACCESS_KEY_ID=...
    export AWS_SECRET_ACCESS_KEY=...
    serverless deploy

I got 

  Serverless Error ---------------------------------------
 
     This command can only be run inside a service directory
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

The guide didn't explain what a service directory is yet and how to create a service. That is misplaced and should go after the "Creating a service" step.

**Comment by pmontrasio** [comment]
There is a possible source of mistakes [here](https://github.com/serverless/serverless/blob/master/docs/01-guide/05-event-sources.md#updating-our-code). The new code uses ```callback``` and the old one uses ```cb```. I copy and pasted only the body of the function and got an error, because the function declaration still had ```cb```. I had to look into the logs on AWS to realize what was going on. I suggest to use the same name everywhere. ```callback``` is better than ```cb``` so you could change it into the ```handler.js``` generated by default by ```serverless create```.  

```

```

**Comment by erikerikson** [comment]
Hi @pmontrasio - Thanks for noticing this oversight!  Do the changes in https://github.com/serverless/serverless/pull/2295 address your concern sufficiently?

**Comment by pmontrasio** [comment]
Yes, I think that would be fine.

It's nice to see that you're caring about documentation this much.

**Comment by awolden** [comment]
Hey Guys,

Instead of creating new issue, I will just drop in on this discussion. It would also be nice to have some documentation on what IAM policies serverless requires. Right now it is easiest to use a role that allows everything, and it would be nice to able to tighten up the role that serverless is executed with.

**Comment by flomotlik** [comment]
Closing this issue for now as we've done major steps forward on this and future issues will be more specific
