### ISSUE TITLE
deploy is not creating API Gateway resource

### ISSUE THREAD

**Issue by patrickbrandt** [serverless/serverless#1737]
##### Serverless Framework Version: 
1.0.0-alpha.2

##### Operating System: 
Mac OSX Yosemite v 10.10.5

##### Expected Behavior: 

when I run a `serverless deploy` command with the following configuration:

![image](https://cloud.githubusercontent.com/assets/11197026/17343807/8ab17bda-58cd-11e6-915f-55fb5b8b3709.png)

The corresponding API Gateway endpoint is created in my AWS account (GET /ping)

##### Actual Behavior: 

Nothing is created in API Gateway, but the corresponding "ping" Lambda function is created and deployed.

**Comment by shortjared** [comment]
For a workaround... trying going into API Gateway in the console and hit the deploy... seems that cloudformation will "update the api" but not actually deploy to a stage more than once.

![image](https://cloud.githubusercontent.com/assets/1689118/17345778/a7baf56e-58d5-11e6-91f1-3671bd261e2f.png)

**Comment by wedgybo** [comment]
I think it's an issue with your spacing on the events list. It needs to be just two spaces. I had the same issue first time around.

https://github.com/serverless/serverless/issues/1648

**Comment by patrickbrandt** [comment]
That was it! I applied spacing rules per issue #1648:

![image](https://cloud.githubusercontent.com/assets/11197026/17372042/2651d2d6-5970-11e6-9120-ee362d4eaed2.png)

The API Gatweay resources were created and the dev stage was deployed on `serverless deploy`

Thank you.

**Comment by patrickbrandt** [comment]
I just updated to beta from alpha. This issue appears to be resolved in beta. The following yaml will create and deploy two API Gateway endpoints and requisite functions as expected:

![image](https://cloud.githubusercontent.com/assets/11197026/17375121/bc4a0256-597d-11e6-9acd-05d94cc0e27a.png)
