### ISSUE TITLE
aws updateStack.js fails because validStatuses does not include UPDATE_ROLLBACK_IN_PROGRESS

### ISSUE THREAD

**Issue by bijoutrouvaille** [serverless/serverless#1745]
##### Serverless Framework Version: 
1.0.0-beta.1

##### Operating System: 
El Capitan
##### Description:
Updating a service using `serverless deploy` results in failure,

```
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...

  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to create: [ResourceApigEventHello1Hello1,
     ResourceApigEventHello2Hello2].
     The following resource(s) failed to update: [hello1,
     hello2].

  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [ResourceApigEventHello1Hello1, ResourceApigEventHello2Hello2]. The following resource(s) failed to update: [hello1, hello2].
    at .../serverless/lib/plugins/aws/deploy/lib/updateStack.js:56:33

```

updateStack.js checks if `validStatuses` contains `stackStatus`, which happens to be `UPDATE_ROLLBACK_IN_PROGRESS` while `validStatuses` is comprised of `UPDATE_COMPLETE,UPDATE_IN_PROGRESS,UPDATE_COMPLETE_CLEANUP_IN_PROGRESS`

Is that a bug?

**Comment by bijoutrouvaille** [comment]
So I've removed the deployment, re-deployed and the error went away. This happened when I upgrade from v1 alpha to beta, so that might have something to do with the problem.

I've done more testing with the beta, updating configuration for different parameters, and did not experience a problem again.

**Comment by flomotlik** [comment]
@bijoutrouvaille this is almost certainly a regression in our API Gateway setup as described in #1752 . I'll close this for now, if you have more info or if this is a separate issue from the one reported in the other issue let us know. Thanks for reporting
