### ISSUE TITLE
Append to existing Environment Variables

### ISSUE THREAD

**Issue by eL0ck** [serverless/serverless#1746]
Setting new environment variables works great.  However it seems impossible to UPDATE and existing variable.

Is there an equivalent to:

``` bash
export PATH=/new/path:${PATH}
```

I'm using python2.7 for my functions, so the lambda function gets deployed with the following line in the `_serverless_handler.py`:

``` bash
os.environ['TEST_VAR'] = str('/new/path:${TEST_VAR}')
```

... which obviously fails.

I would prefer not to use a dummy handler which finishes the job of setting up the environment for the lambda function. e.g:

``` bash
os.environ['TEST_VAR'] = "{}:{}".format('flojo', os.environ.get('TEST_VAR'))
```

Perhaps this is semi-related to: [Issue 1172](https://github.com/serverless/serverless/issues/1172)

**Comment by flomotlik** [comment]
@telson for which version of Serverless is this problem happening?

**Comment by telson** [comment]
This isn't a problem so much as a feature request @flomotlik .  Its clear that those implementing this functionality in `sls` intended it to be used to set new environment variables only.

I'm using `v0.5.6` but I'm sure this the case in all versions.

Perhaps this could be implemented by sub-categorising  the `environment` object in `s-function.json` like so:

```bash
  "environment": {
    "set": {
      "SERVERLESS_PROJECT": "${project}",
      "SERVERLESS_STAGE": "${stage}",
      "SERVERLESS_REGION": "${region}"
    },
    "append": {
      "SOME_PATH": "some/new/path"
    },
    "unset": [
      "ENV_VAR_TO_CLEAN_1",
      "ENV_VAR_TO_CLEAN_2,"
    ]
  },
```

**Comment by mthenw** [comment]
Closing as this issue relates to 0.* version. Env vars feature for 1.* is discussed here https://github.com/serverless/serverless/issues/1455.
