### ISSUE TITLE
.aws credentials/config filename bug

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#1748]
Documentation states that you may run "aws configure" to add the credentials file. However aws adds ./aws/config file instead of ./aws/credentials file which results Error: ServerlessError: TimeoutError: Missing credentials in config. 

It seems Serverless expects that the file is  ./aws/credentials so it needs to be renamed. 

Either this should be fixed to documentation or sls should use the config file the aws-cli generates.

**Comment by flomotlik** [comment]
@pmuilu AWS creates 2 different config files, the credentials and config file according to their docs: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files

We're not using the credentials file directly, but let the aws sdk deal with it.

Your aws-cli version is pretty outdated. Could you update and try again as I suppose that this is the problem. I'm going to close this issue for now as I think updating the cli and trying again should resolve this, if it doesn't please let us know and we can reopen.
