### ISSUE TITLE
Setup and use Code Climate / Refactor complexities in code

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1760]
Additional to Coveralls we could setup Code Climate which also analyses security, code duplication and other things.

Maybe worth to checkout and add
https://codeclimate.com

/cc @eahefnawy @flomotlik

**Comment by flomotlik** [comment]
Would add it at a later stage. Imho at the moment not high priority and codebase is generally good enough that we won't get enough out of CodeClimate. I think its generally a great tool though. We can come back to it in the future when we put more time into static analysis of the codebase.

**Comment by pmuens** [comment]
Before releasing v1 we should investigate complex methods and refactor the code accordingly.

Reopening this issue to reflect that.

/cc @eahefnawy @flomotlik

**Comment by flomotlik** [comment]
Imho we shouldn't do this with V1. The code is fine at this point and adding more tasks will delay V1. We should do it afterwards.

**Comment by dougmoscrop** [comment]
For what it's worth, the serverless codebase was one of the easiest I've ever encountered in terms of navigating and working with. Huge 👍 to y'all.

On the other hand there were some pretty gnarly methods in PluginManager (see LOC reduction here: https://github.com/serverless/serverless/pull/2133 -- that adds features but also kills almost double the code it touches).

If it's not too hard, adding some analysis could help.

**Comment by pmuens** [comment]
Related to #2722

**Comment by pmuens** [comment]
Closing this one to keep the issue count low. Not sure if it's super beneficial right now.
