### ISSUE TITLE
Allow dynamic linked libraries in project

### ISSUE THREAD

**Issue by telson** [serverless/serverless#1763]
Currently I have all libs in the top level serverless project `lib/` so that it gets onto the LD_LIBRARY_PATH in lambda as `/var/task/lib`.

Ideally serverless would append my `lib/` to the `LD_LIBRARY_PATH `

**Comment by flomotlik** [comment]
@telson I'm not sure if its possible for us to set LD_LIBRARY_PATH ourselves on Lambda. Do you have some documentation how this would work? Going by the AWS forum here it looks like only AWS can do this: https://forums.aws.amazon.com/thread.jspa?messageID=706158

**Comment by telson** [comment]
@flomotlik It certainly seems that the only way to do it and have the linker read the changes is to start a new process. 

I'm fine with using a top level `lib/` for now
