### ISSUE TITLE
Add serverless test plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1765]
It would be awesome if one could run `serverless test` to e.g. test the HTTP endpoint (or other services) so that tools such as Postman are not necessary and the developer can stay inside his terminal and the Serverless framework during development.

/cc @ac360 @flomotlik @eahefnawy

**Comment by hassankhan** [comment]
+1, it always seemed "hacky" before, would be great to have an officially-endorsed solution.

**Comment by pmuens** [comment]
@hassankhan thanks for your reply. Do you have any specific functionality you would like to have in this test plugin? What do you want to test exactly?

**Comment by hassankhan** [comment]
Ideally, I'd love to have a simple Mocha + Chai setup, with something that mocks the AWS-SDK and allows me to pass in a custom `event` and `context`.

Optionally, it could allow for running a test against the deployed function.

**Comment by mthenw** [comment]
Actual implementation is discussed in https://github.com/serverless/serverless/issues/2531
