### ISSUE TITLE
Cannot read property type 'match' of undefined

### ISSUE THREAD

**Issue by nergmada** [serverless/serverless#1767]
##### Serverless Framework Version: V1.0 (modified)
see this [link](https://github.com/Smeb/serverless/pull/2) to see how the code has changed
##### Full details
So a few days ago a colleague of mine filed a pull request here with user defined templates [(see here)](https://github.com/serverless/serverless/pull/1694)

This basically allows us to map Twilio requests which behave in such a way where they send info in a form encoded format.

We've been using my colleagues repo changes as our serverless in our package.json (i.e. basically we're using the template modification). His code runs fine and deploys and redeploys as expected.
I've made a slight modification (see [this pull request to his repo](https://github.com/Smeb/serverless/pull/2)) 

basically it hard codes in our error messages into the JSON that is used with cloud formation to set up our API gateway. It specifies a set of error codes to match using regex and then responds with those error messages.

Now this code deploys for the first time fine, but subsequent redeploys fail, to be specific they fail in the  ```serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\methods.js```
at line 41 where serverless tries to get the AWS Account Number. Upon testing with console.logs I found that .getVariables() was returning an empty JSON (e.g. { }) here:
```
console.log(this.serverless.service
            .getVariables(this.options.stage, this.options.region)) // prints '{}'
```
#### So to summarise
1. First deploy works fine, and prints a full JSON object on that console log and also correctly prints the AWS Account Number
2. Second deploy onwards fails miserably crashing after printing 'Zipping Service' and does not print an AWS Account number and prints .getVariables as an empty JSON

I realise that this isn't your code, and the way it's been modified means it's not even remotely in your scope to be adopted, but is there any reason where specifying additional responses for both integration and method may make redeploys fail?

**Help much appreciated, thank you!**

**Comment by flomotlik** [comment]
@pmuens on master we've moved away from getting the account number ourselves and are instead using Cloudformation for that correcT? This might be the issue here.

**Comment by pmuens** [comment]
Yes, we've removed the accountNumber functionality and now using Ref to get it.

@nergmada what version of Serverless do you use exactly?

/cc @eahefnawy

**Comment by nergmada** [comment]
1.0.0-alpha.2 is my current version number according to ```sls --version```

I can look at maybe trying to pull the master code into mine?

**Comment by flomotlik** [comment]
@nergmada I think installing the beta should help since this was merged before we released the beta. Could you try with beta and if that still fails with master branch?

**Comment by nergmada** [comment]
@pmuens @flomotlik this has fixed our issue. Thank you very much for your help.
