### ISSUE TITLE
CLI unable to clean/destroy projects

### ISSUE THREAD

**Issue by marklawlor** [serverless/serverless#177]
The CLI is is unable to clean/destroy projects. This action must be manually performed though the AWS console.

If a clean method is created, it would be nice to have two versions. A soft clean that tears down the cloud-formation/API-gateway but leaves the ENV vars intact, and a hard clean that destroys everything.

**Comment by eahefnawy** [comment]
+1

**Comment by ac360** [comment]
+1 Coming soon!  My AWS account for testing JAWS is completely bloated with project remnants.

**Comment by joemocha** [comment]
:+1:

**Comment by eahefnawy** [comment]
Serverless v0.5 now have `sls project remove` action! Closing...

**Comment by jlsjonas** [comment]
as this isn't in the command list, the new command is `sls remove`; in case you changed your region you'll have to revert this change to be able to use the command
