### ISSUE TITLE
Allow setting ARN for IAM Role to point to previously created Role

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1772]
##### Feature Request:

As discussed in #351 we should allow users to set a custom ARN that points to an IAM role they want to use as the execution role for Lambdas.

##### Benefits:

* User can define one IAM Role across various services

##### Drawbacks:

* Users need to set different ARNs depending on the stage or account they deploy to, so variable handling becomes important

##### Additional Details:

Example:

```
provider:
  iamRoleARN: <Your ARN>
```

**Comment by atonse** [comment]
@flomotlik Are you currently working on this? I've hit this issue where I'd like to share the IAM role across all the lambda functions in one particular app.

**Comment by flomotlik** [comment]
@atonse at the moment nobody is actively working on this. We would love to have this implemented, but got a few other higher priority things to implement at first. You could probably do this through custom resources at the moment and overwriting the execution role through custom resources.

We're very open to contributions on this though if somebody is interested in jumping in on this :)

**Comment by horike37** [comment]
@flomotlik
I implemented #1975 . Please check my PR.

**Comment by sielay** [comment]
Absolutely essential feature +1

**Comment by flomotlik** [comment]
#1975 was just merged. Thanks @horike37 for the great PR!

**Comment by asantibanez** [comment]
Thanks for implementing this! Was looking for it today!

Is the role definition also available per function?
