### ISSUE TITLE
Allow success status codes other than 200.

### ISSUE THREAD

**Issue by benjaminabbitt** [serverless/serverless#1776]
##### Feature Request: 

Allow success status codes other than 200.

##### Benefits:

* Allow more correct/descriptive status codes.
* e.g. My CQRS application takes commands and really should return 202s when it accepts commands.

##### Drawbacks:

* More code to maintain

##### Additional Details:

Make the response optional, defaulting a success to 200.

**Comment by flomotlik** [comment]
We're looking into more support for this in #1593 . Definitely want this to be possible.

**Comment by flomotlik** [comment]
This is very related to #1593 so I'm going to close this issue here, but we'll keep it in mind when doing the detailed planning on that feature. Definitely want that for one of our next releases.
