### ISSUE TITLE
No permissions created for Authorizer functions that don't have http end points 

### ISSUE THREAD

**Issue by fridaystreet** [serverless/serverless#1784]
##### Serverless Framework Version: 
1.0.0-beta1 (current master branch)

##### Operating System: 
Locally: Linux mint 18

##### Expected Behavior:

Following permission resource is created for the lambda function used by the Authorizer even if it doesn't have an http events defined
```
"myFunctionApigPermission":
{
    "Type":"AWS::Lambda::Permission",
    "Properties":
    {
      "FunctionName":
      {
        "Fn::GetAtt":
        [
          "myFunction","Arn"
        ]
      },
      "Action":"lambda:InvokeFunction",
      "Principal":"apigateway.amazonaws.com"
    }
  }
```
##### Actual Behavior:
The permission resource is only created for functions that have http events attached.

##### Stack-Trace (Optional):
Error from testing Authorizer in AWS console

Sat Aug 06 06:47:36 UTC 2016 : Execution failed due to configuration error: Invalid permissions on Lambda function
Sat Aug 06 06:47:36 UTC 2016 : Execution failed due to configuration error: Authorizer error
Sat Aug 06 06:47:36 UTC 2016 : AuthorizerConfigurationException

Discussion template  ----------------------------------------------

**Comment by andymac4182** [comment]
@fridaystreet Is this still an issue for you on beta2? I am using beta2 and it is working correctly for me.

**Comment by fridaystreet** [comment]
@andymac4182 yeah it's working ok now thanks. Apologies for not updating the issue
