### ISSUE TITLE
[Critical Bug] Timeout settings do not update on aws console after first deploy

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1795]
##### Serverless Framework Version: 

```
1.0.0-beta.1
```

Well to be more accurate I am on `master` and this commit: `d1942f4937a85823f6f7deb9094bd32a4acdea`

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

Lambda function timeout settings update on aws console

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17493609/01749bfa-5da9-11e6-9617-b770ab09ea73.png)

I deployed first with no defaults
then added the following to the `serverless.yml` file:

```
defaults:
  stage: dev
  region: us-east-1
  memory: 1024
  timeout: 300

```

and aws console did not update

 @pmuens ? @eahefnawy ? @wedgybo ?

**Comment by pmuens** [comment]
@codepreneur thanks for reporting this one!

We've recently changed from `memory` to `memorySize` (as CloudFormation also calls it `MemorySize`). Unfortunately our documentation needs some ❤️  (it will get it the upcoming weeks).

Sorry for the inconveniences 🙈 

Could you check if this does the trick? Thanks in advance. And thanks again for reporting...

**Comment by codepreneur** [comment]
@pmuens its not the `memory` thats the problem, its the `timeout` :) is it `timeoutSize` then ?

**Comment by mbokman** [comment]
Hi @codepreneur I had the same issue.

I resolved it by setting these below ```provider:``` instead of ```defaults:``` like this:

```
provider:
  name: aws
  runtime: nodejs4.3
  timeout: 3
  memorySize: 512
```

**Comment by pmuens** [comment]
@codepreneur Sorry for that.

Shees. Sorry for that 😆  it was late last night 🌃 

@mbokman is correct. It was moved from `defaults` to `provider` recently as those settings are now provider specific.

**Comment by flomotlik** [comment]
@pmuens @codepreneur we had a few issues recently where we updated things and didn't make it clear that they were moved or wrote deprecation messages into it. This will change going forward. So if a config element is expected at one place and we're moving it we'll load it from both places at first but print a future deprecation message
