### ISSUE TITLE
Does invoking the same Lambda multiple times executes them in parallel?

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#180]
I think I read that it does in the docs, but I just wanna make sure it's true from your experience.

The reason I'm asking is because of a recent AWSM I wrote. [awsm-mailer](https://github.com/eahefnawy/awsm-mailer) lets you to send emails by invoking the Lambda. It can be used for transactional emails, but i'm not so sure about mass mailing for marketing (millions of emails),

I'm thinking maybe if the user just invoked the Lambda for each email, all emails will send in parallel, which would be awesome. If not, what do you think would be needed to handle such a huge scale task. Maybe we'll need SQS? Could we even use multi threading with Lambdas?

**Comment by ac360** [comment]
@eahefnawy Hmm...  Here are some thoughts:

A lambda can invoke another lambda (or multiple) from within itself.  There may need to be an orchestrator lambda, which fires off other lambdas to perform the task.  The orchestrator lambda needs to be able to save the state of its operations to dynamodb, since lambdas can only run for 60 seconds.  The orchestrator lambda should run and fire off tasks until they complete, or if 50 seconds gone by, it should save the state of its task to dynamodb, and call a new orchestrator lambda function, which continues the work until it is done.  This pattern likely needs to be established for many lambda functions.

Beware the perils of infinite scalability here!  If your orchestrator lambda function does not stop, it may go on forever...

Or, if the email services takes an array of emails.  Maybe keep it simple and have the lambda accept an array of emails via POST and it sends those.  The orchestration could be handled on the client-side.

**Comment by shortjared** [comment]
@eahefnawy If you haven't already seen it, this is a somewhat relevant architecture / discussion from https://blogs.aws.amazon.com/bigdata/post/Tx3KH6BEUL2SGVA/Building-Scalable-and-Responsive-Big-Data-Interfaces-with-AWS-Lambda

![Lambda Architecture](https://cloud.githubusercontent.com/assets/1689118/10196023/a3a6908c-675e-11e5-97a6-22cf7b301ba7.png)

**Comment by eahefnawy** [comment]
thanks a lot guys, that's really helpful! About tracking the state, do you think [AWS SWF](https://aws.amazon.com/swf/) could do the trick?

from their docs, it seems that's what it's made for! or maybe misunderstood it?

**Comment by binoculars** [comment]
You might be better off with [mailchimp](http://mailchimp.com/) for mass emails--probably cheaper and easier for you.

**Comment by shortjared** [comment]
Lambda / SES is much cheaper at scale than something like mailchimp.

There are solutions out there like [sendy.co](https://sendy.co) which are self-hosted and leverage SES... however to send millions of emails, you need fairly beefy machines to get any decent amount of send rate and beefy machines ain't cheap to have running. I think lambda may have a use case here, but I'd argue it's actually harder the reign in lambdas to not exceed send rates then to try and meet send rates.

**Comment by binoculars** [comment]
Lambda / SES = $0.10 per 1,000 emails + Lambda cost + Outgoing Bandwidth (plus the labor of having to make your own system and maintain it)
MailChimp =  $240 for unlimited emails for 50,000 subscribers.

They're different pricing models, but I think around the million email mark you're probably better off with MailChimp, IMHO.

**Comment by sagivo** [comment]
@eahefnawy what did you end up doing? i'm at the same place now and still looking for a good way to send mass emails using lambda.

**Comment by neoadventist** [comment]
@sagivo @eahefnawy how do you invoke a lambda from within a lambda?

**Comment by pmuens** [comment]
@neoadventist there are multiple ways. You could e.g. use `SNS` as a mediator (which makes the call async) or initiate an SDK call from within the Lambda function (that would be a sync call).

**Comment by neoadventist** [comment]
@pmuens thank you! I don't understand how using the SDK from within the Lambda function would make it a sync call. Could you explain? 

I see this example: https://github.com/serverless/examples/blob/68a0e4382d1a64e7547a9599cb807470c6918514/aws-node-recursive-function/handler.js

**Comment by pmuens** [comment]
> @pmuens thank you! I don't understand how using the SDK from within the Lambda function would make it a sync call. Could you explain?

when invoking you're passing in `context.done` from the main function as the second parameter which will be evaluate once the `invoke` finishes. This way your main function waits until the `lambda.invoke` call finishes and calls the callback (`context.done` in that case).

That's what I mean with "synchronous".

```javascript
lambda.invoke(params, context.done);
```

With `SNS` you could just pipe in some data and SNS will take care of the invocations. So basically "fire and forget".

**Comment by HyperBrain** [comment]
@pmuens @neoadventist You also can use the Lambda event based invocation by setting `InvocationType: "Event"` in the invoke params.
This will have the same effect as using SNS manually. The invoke returns immediately and the AWS backend will try to execute the call 3 times asynchronously in the backend. If the call does not succees after all tries, it will post a message to the Lambda's dead letter queue (DLQ).

**Comment by pmuens** [comment]
> @pmuens @neoadventist You also can use the Lambda event based invocation by setting InvocationType: "Event" in the invoke params.
This will have the same effect as using SNS manually. The invoke returns immediately and the AWS backend will try to execute the call 3 times asynchronously in the backend. If the call does not succees after all tries, it will post a message to the Lambda's dead letter queue (DLQ).

Nice! Didn't know that. Thanks for sharing @HyperBrain 👍
