### ISSUE TITLE
I need help with running and testing existing serverless project

### ISSUE THREAD

**Issue by codingmaven** [serverless/serverless#1802]
##### Operating System:  ubuntu

Hi,

I am currently working on existing code generated with serverless framework.
Can you help me how I can run function locally and test?
Is there any way to run the function locally?

serverless function run create-dash-participants

I tried this to run function locally but I got error

Serverless Error: Missing stage

**Comment by flomotlik** [comment]
@codingmaven you probably have to deploy to this specific stage first, but as we've moved all of our development to V1.0 we can't give any further support for 0.5 issues here in Github. You can check out our Gitter chat at chat.serverless.com.
