### ISSUE TITLE
Caching based on requested path in amazon apigatework giving me " Invalid parameter name specified"

### ISSUE THREAD

**Issue by ryan-wong** [serverless/serverless#1806]
Serverless Framework Version: 0.5.6

Operating System: MAC and amazon

Expected Behavior: sls dash deploy my endpoint and lambda and I check off request path caching, I should not get Invalid parameter name specified

##### Actual Behavior: I get Invalid parameter name specified

Stack-Trace (Optional): No

 Additional Details:

I've deployed a project from scratch twice now and I have this issue.

Basically, I have 2 request path variables accountId and configId. I tested locally it works. Once I deploy and set the request path caching, it give me that error. Query parameter cache works. 

When I create the endpoint from scratch on amazon apigateway and link it to the lambda function I deploy from serverless project, it allows me to set the request path cache variable.

I've tried to do the stuff on stackoverflow to fix this but no luck. I've lost 1 week trying to fix this.

Here is my s-function.json

<pre>
{
  "name": "getApp",
  "runtime": "nodejs4.3",
  "description": "Serverless Lambda function for project: videa-client-config",
  "customName": false,
  "customRole": false,
  "handler": "handlers/api/getApp/handler.handler",
  "timeout": 50,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": []
  },
  "endpoints": [
    {
      "path": "account/{accountId}/app/{configId}",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": {
          "accountId": "$input.params('accountId')",
          "configId": "$input.params('configId')"
        }
      },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {
            "application/json;charset=UTF-8": "Empty"
          },
          "responseTemplates": {
            "application/json;charset=UTF-8": ""
          }
        }
      }
    }
  ],
  "events": [],
  "environment": {
      "SERVERLESS_PROJECT": "${project}",
      "SERVERLESS_STAGE": "${stage}",
      "SERVERLESS_REGION": "${region}",
      "MONGO_HOST": "${mongoDatabaseHost}",
      "DATABASE": "${database}",
      "PORT": "${port}",
      "AUTH_SOURCE": "${authSource}",
      "DOCUMENT_VERSION": "${documentVersion}",
      "RELATION_VERSION": "${relationVersion}",
      "PASSWORD_HASH_SECRET": "${passwordHashSecret}",
      "HASH_ALGORITHM": "${hashAlgorithm}",
      "TOKEN_DURATION": "${tokenDuration}",
      "DEFAULT_USER_ROLE": "${defaultUsersRole}",
      "EXTRA_OPTIONS": "${extraOptions}"
    },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  },
  "vpcConfig": {
      "SubnetIds": [
      ],
      "SecurityGroupIds": [
      ]
  }
}
</pre>

Here is my s-resources-cf.json

<pre>
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application's resources outside of Lambdas and Api Gateway",
  "Resources": {
    "IamRoleLambda": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com",
                  "apigateway.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "IamPolicyLambda": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "${stage}-${project}-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:${region}:*:*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambda"
          }
        ]
      }
    }
  },
  "Outputs": {
    "IamRoleArnLambda": {
      "Description": "ARN of the lambda IAM role",
      "Value": {
        "Fn::GetAtt": [
          "IamRoleLambda",
          "Arn"
        ]
      }
    }
  }
}
</pre>

**Comment by pmuens** [comment]
Hey @ryan-wong thanks for reporting this!

Unfortunately we're not support Serverless v0.5 anymore. We've just release the beta of Serverless v1 you can find on the `master` branch.

You can install it with `npm install -g serverless@beta`.

Transition to use Serverless v1 should be straight forward (you can get more information on how Serverless works in the [docs](http://github.com/serverless/serverless/docs).

Let me know if you need any help there!

**Comment by theburningmonk** [comment]
Hi, I can't find examples of how to enable path parameter caching in the 1.X docs, can anyone point me to an example?

**Comment by pmuens** [comment]
Hey @theburningmonk thanks for reaching out.

Unfortunately I don't have any examples at hand. Could you maybe open up a post at http://forum.serverless.com/ or Gitter so that it gets more exposure? Thanks 👍
