### ISSUE TITLE
Feature Request: Per Function Custom IAM roles

### ISSUE THREAD

**Issue by danhumphrey** [serverless/serverless#1807]
##### Feature Request: Per Function Custom IAM Roles

At present, custom roles can only be defined at the service level (#1749), which I don't believe is granular enough. Individual functions should allow for individual roles.
##### Benefits:
- Improved security
##### Drawbacks:
- Complexity, however, users could ignore this and choose the per service approach

**Comment by pmuens** [comment]
Hey @danhumphrey thanks for this one! Good idea.

I would propose to implement the same fallback we're about to implement with the `package` per function functionality (see here: https://github.com/serverless/serverless/issues/1777). So you can basically implement it on a per-service level or per-function level.

What do you think about this @flomotlik @eahefnawy

**Comment by danhumphrey** [comment]
Hi @pmuens thanks for the quick response.

I think the fallback option is perfect - function role is used if defined, otherwise, service role is applied. :)

Looping in @ac360 who responded to my question about this on Gitter.

**Comment by Christoph-Schabert** [comment]
Hello @danhumphrey 
We are using this Approach in sls 0.5.

We generate for each function a own policy with [Troposphere](https://github.com/cloudtools/troposphere) 

The problem currently is that we have to generate the resource template before we can deploy the serverless resources.
It would be awesome if serverless would support this out of the box.

**Comment by flomotlik** [comment]
Yup I like this feature. I've also added the help-wanted label. I'm not sure how fast we're going to get around to implementing this, but we'd love to have it in if somebody is able to provide a PR for it

**Comment by mpaf** [comment]
I would add that those roles should be also part of the serverless cloudformation stack - that is you should be able to reference the custom resources you define, which you don't know the ARN beforehand. You can then deploy the service across AWS accounts for e.g. without any hardcoding of ARNs.

**Comment by eL0ck** [comment]
Is this issue on the way to being closed @erikerikson? 

due to your work here: #2073

**Comment by erikerikson** [comment]
Ooh.  I missed this when I wrote up #1895.    Thanks for bringing it to my attention @eL0ck.

Yes, I believe #2073 resolves this issue.  The caveat depends on what one takes to be in this feature request.  I think immediately upon having role per function rights capabilities that we're going to want to condense the roles and do a few other things to make life more terse.

For example, I believe having something like `inheretsFrom` as an attribute that causes a role to copy the referenced role and merge its own specification over top of the copied role would be a very easy and helpful first option.

I believe the SLS team may be more creative about this on the other hand (managing this sort of stuff for us) and I wouldn't want the implementer to to have their hands tied.

**Comment by flomotlik** [comment]
@erikerikson I really like this PR as a first step as it allows users to define custom resource Roles, but also gives us the ability to expand in the future, e.g. define statements in the function->role definition directly, inherit from service role (or potentially another one) and also automatically extend a specific role with policies to talk to specific resources that are created for that role.

All in all a really great start so users can have very tight control and we can add more features in the future.
