### ISSUE TITLE
spawn npm ENEONT when deploying a function. v: 0.5.6

### ISSUE THREAD

**Issue by maorinka** [serverless/serverless#1815]
I'm getting this error when deploying a function: spawn npm ENEONT 
When deploying an endoint everything goes fine, it happens only with functions

As I understand the error, it means it can't find the process it tries to run. But doen't tell which..

##### Operating System: windows 8

![image](https://cloud.githubusercontent.com/assets/6322954/17556305/95171e28-5f1b-11e6-9d6b-9c1423dc26e7.png)

**Comment by pmuens** [comment]
Hey @maorinka thanks for reporting.
Unfortunately we're not supporting v0.5 anymore and have switched the master branch to v1.

The transition to v1 should be straight forward (take a look at the [docs](https://github.com/serverless/serverless/tree/master/docs) to read how the new Serverless works).

Let me know if you need any help there.
