### ISSUE TITLE
Node modules no longer resolving in nested folders

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#1819]
##### Serverless Framework Version: 
v1.0.0-beta1.1
##### Operating System: 
MacOSX
##### Expected Behavior:

When zipping function for `sls deploy` resolve any require calls in code to the root `node_modules` directory

##### Actual Behavior:

https://gitter.im/serverless/serverless?at=57abf847d7087a017faadc40

>has anything changed in v1.0.0-beta1.1 in regards to modules within folders?
I have a root level /node_modules, then /myfolder/handler.js (with a handler) function
in serverless.yml the function points to myfolder/handler.handler, and it works fine in v1.0.0-beta1
but now in beta1.1 it can't find that module, plus any require statements in handler.js aren't resolving

I am seeing this as well. I had to temporarily resolve by manually installing a new `node_modules` folder into my nested directory

![image](https://cloud.githubusercontent.com/assets/532272/17579404/fc307ce8-5f49-11e6-9b7a-906c90d8a9bf.png)

**Comment by pmuens** [comment]
Hey @DavidWells thanks for reporting!

The actual behavior is that Serverless will zip up the whole service directory starting at the level where the `serverless.yml` file is defined. Folders outside the service are not considered.
In your case the content inside the `newsletter` directory will be archived (therefore the outer `node_modules` is not considered.

**Comment by DavidWells** [comment]
Would it make sense to recursively look up a couple directories to try and resolve the modules (like standard node behavior?

This would make it so people could take service approach OR include a service within a project.

** Example A **, a single project

Lets say, I have a static site with a contact form and the directory structure looks like:
```
/* mono repo */
/src # site files
/service # lamdba function with node dep
package.json # dependancies for site and the lambda service
```
In this example, I can clone down the project and install dependancies once and also deploy the service via an npm script

** Example B ***, with site and service broken into two projects:
```
/* site repo */
/src # site files
package.json # dependancies for site
```
```
/* contact service repo */
handler.js # lamdba function with node dep
serverless.yml
package.json # dependancies the lambda service
```

In example B, I have to clone down both projects and manage them individually, (which is microservice approach + recommended, but extra overhead for some users)

**Comment by pmuens** [comment]
Yes, sharing code between services would be really valuable.
Thanks for the in-depth description here 👍 .

I'd like to link to this issue https://github.com/serverless/serverless/issues/1512 where we've discussed the requirement in detail. TLDR is that the developer should use npm packages to share code between services.

**Comment by DavidWells** [comment]
Word. Thanks for the link. =)

The only way for a sub-folder to install a module and `node_modules` folder in the correct place is for that subfolder to have it's own package.json. (which is fine but is extra work)

I'm just saying we could look up directory/directory/directory/etc... to see if the module being `require('moduleName')` exists in the parent `node_modules` folder and if so, zip it with the lamdba and deploy.

Then people could have a single `npm i` command for projects like this:
```
1. install with `npm i`
2. Deploy lambda service XYZ with `npm run deploy` (which runs `cd service && sls deploy`) 
```

[Here is a video explanation](http://www.screencast.com/t/57LCfqdz) of what I mean http://www.screencast.com/t/57LCfqdz  

Again this goes slightly against the pure service approach but it should be pretty straight forward to check if the required module exists in the parents node_modules folder

**Comment by DavidWells** [comment]
Or perhaps a field in `serverless.yml` to specify where to grab/resolve the node_modules, but this approach makes the user have to think about the extra step

**Comment by flomotlik** [comment]
@DavidWells the issue with going out of the current service folder is that it leads to potentially unexpected behaviour. E.g. in the top folder you've installed different versions of a dependency or included other files.

One thing I could see us doing in the future is allowing you to add paths to the include statement that are not in the same folder, so you could specifically say "include this path into my lambda deployment"

The problem there is once we start letting people deploy other services they just download this is a huge security risk. Basically anyone could include anything from the users file system and upload somewhere (same issues applies when installing and using plugins that are not part of the core)

**Comment by flomotlik** [comment]
As we're not planning to change this anytime soon and want to keep open issue number low I'm going to close this one. Code sharing is an important topic we need to tackle through docs, but I don't think Serverless itself should include code from other places than the working directory or subfolders at the moment.

**Comment by ivysnia** [comment]
what about hoisted node modules in monorepo/yarn workspaces? 
checking parent folders for node_modules is [default nodejs behaviour].(https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)
and it does work fine with serverless-offline, but packaged service doesn't have node_modules from package.json dependencies, since they're installed by yarn in the workspaces root node_modules.
it is really not feasible to manually manage multi level dependencies by using `serverless.yml` configuration with `package: include: ...`, as you'd need to define whole dependency tree and manually update it.

**Comment by xianny** [comment]
Bumping as I'm running into the same issue. I have a yarn/monorepo project, trying to package and publish one of the packages to AWS Lambda.

**Comment by steverob** [comment]
Has anyone solved this? Essentially I'm trying to have a monorepo for multiple services with a shared top level `node_modules` and `package.json`.

Trying to figure out how to get `sls package` to resolve deps to the parent node_modules folder.
