### ISSUE TITLE
Where can I find the lambda function and API gateways created by serverless

### ISSUE THREAD

**Issue by ChenLi0830** [serverless/serverless#1827]
I think this is more of a general question than a real issue. 

I want to customize the API gateways created by serverless using AWS console while I can't seem to find them. **I can only see the gateways I created using the console**. Does anyone know how to find them or make them accessible through AWS console?

Thanks!

**Comment by merrickfox** [comment]
@ChenLi0830 did you figure this out? I would also like to know. I created a new IAM user and fed these keys to serverless and deployed the basic hello stuff, when I log in to AWS console as this user I don't see the functions in the lambda section or the API gateway. I do however see the bucket in S3.

**Comment by ChenLi0830** [comment]
@merrickfox Sorry I haven't figured it out yet. I'll let you know if I do.

**Comment by ac360** [comment]
Hi guys, make sure you are looking in the region that the Framework deployed to (by default its us-east-1).  They should be there in the Lambda, API Gateway and CloudFormation dashboards.

**Comment by ChenLi0830** [comment]
Aha, of course, the region! I always forget about it. 
@ac360 Thanks a lot for the help!

**Comment by ChenLi0830** [comment]
Closing the issue.

**Comment by ChenLi0830** [comment]
@merrickfox 

> Hi guys, make sure you are looking in the region that the Framework deployed to (by default its us-east-1). They should be there in the Lambda, API Gateway and CloudFormation dashboards, if you are looking in the correct region. IAM and S3 resources are treated globally by AWS that's why those are showing up. But Lambda, API Gateway and almost everything else is deployed on one region at a time.
