### ISSUE TITLE
deploy rollback documentation

### ISSUE THREAD

**Issue by davidjnelson** [serverless/serverless#1829]
##### Feature Request:

Document how rollbacks for deploys work.
##### Benefits:
- Rollbacks are crucial to using serverless in a heavily trafficked production environment.  There appears to be support but I can't find a doc on it.
##### Drawbacks:
- It will take some effort to write the doc.
- There may be more work to do on the rollback process itself, which could lead to more effort.
##### Additional Details:

I looked here for docs:

https://github.com/serverless/serverless/blob/master/docs/guide/deploying-a-service.md

**Comment by pmuens** [comment]
@davidjnelson thanks for reporting.

You might also want to read through this issue which discusses versioning and rollbacks https://github.com/serverless/serverless/issues/1457

Specifically this answer by @flomotlik https://github.com/serverless/serverless/issues/1457#issuecomment-238842239

Would love to hear your thoughts on this one so feel free to join the discussion there and describe how you'd like to have rollback support implemented.

**Comment by awolden** [comment]
I have been evaluating serverless for use in a very large scale production system, but the documentation around versioning and rollbacks seems conflicting. In general, I think it would be great to have more clarity on how versioning and rollbacks work in serverles.

**Comment by seanohollaren** [comment]
I'll chime in and say I'd really love to see support for rollbacks as well.  I'm currently evaluating serverless for use in our pipeline (and really liking what I've seen) but the lack of rollback support/documentation is an issue for us.

**Comment by flomotlik** [comment]
We recently released the rollback command, so this is now possible.
