### ISSUE TITLE
Implement custom Resource Merging fully and document it

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1833]
##### Feature Request:
Custom resources from resources.* (including Outputs or the Description) should be merged into the Cloudformation template with a deep merge. If you want to change configuration for a function or any other resource that serverless create you have to be able to set additional configuration parameters for that resource without having to copy the whole resource to the custom resources section

Custom resource config takes precedence over existing resources we create

##### Benefits:

* Allows people more control over the created resourcs

##### Drawbacks:

* People might accidentally overwrite stuff

**Comment by pmuens** [comment]
Will be done with https://github.com/serverless/serverless/pull/1844
