### ISSUE TITLE
Deploy issues on Windows/Linux

### ISSUE THREAD

**Issue by miltador** [serverless/serverless#1835]
##### Expected Behavior:
On Windows:
 - correct path to ```lib/index.js```

On Linux:
 - correct permissions to published files

##### Actual Behavior:
Assuming the following service structure (same as in docs):
```
users
  |__ lib                   // contains logic
  |__ users.js              // single handler file, requires lib
  |__ serverless.yml
  |__ serverless.env.yml
  |__ node_modules
  |__ package.json
```
With the above structure I have one entry point (handler) - ```users.js``` where I require my module ```lib```. In the ```lib``` folder I have the only file - ```index.js``` which exports some function that I use in ```users.js```.

On Windows:
 - After deployment I added some logging code to output the structure of files on the server and what I got was that path to my ```lib/index.js``` file was actually ```/var/task/users/lib\\index.js```, where ```/var/task/users/``` is the root directory. Notice that path to ```index.js``` is invalid, it has ```\\```. That's why my Lambda function fails with ```Couldn't find module './lib'```.
Therefore deploy on Windows is currently broken.

On Linux:
 - After deployment Lambda function, a call to it results in error ```Error: EACCES, permission denied```. I think it's not obvious that you should set the permissions you want to your local files to get them on server side.

**Comment by flomotlik** [comment]
We recently merged #1863 so this problem should be fixed. For a more general JSzip resolve we're waiting to merge your PR in the future.
