### ISSUE TITLE
command "project" not found, Run "serverless help"

### ISSUE THREAD

**Issue by harighub** [serverless/serverless#1841]
Serverless Error - command "project" not found,

##### Serverless Framework Version: 
1.0.0-beta.1.1
##### Operating System: 
Ubuntu 16.04 LTS
##### Expected Behavior:

1) I've installed serverless framework using below command:
sudo npm install serverless -g
I had to run the above command with sudo, otherwise there were permission issues.
2) trying to create a project using command "serverless project create"

##### Stack-Trace (Optional):
Getting below error:

 Serverless Error ---------------------------------------
 
     command "project" not found, Run "serverless help" for
     a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

**Comment by danhumphrey** [comment]
@harighub I'm not sure why you thought you had to use the 'project' keyword, but take a look at the guide or the quick start:

serverless create --template aws-nodejs

**Comment by danhumphrey** [comment]
https://github.com/serverless/serverless/blob/master/docs/guide/creating-a-service.md

**Comment by pmuens** [comment]
Hey @harighub 
We rewrote Serverless from scratch and have deprecated v0.5.

Serverless v1 has no "project" concept but a new "service" concept. My assumption is that you've visited docs.serverless.com which includes docs for the old Serverless version.

As @danhumphrey mentioned the new docs are her in the repository. You might want to start with the guide to see how the new Serverless v1 works: https://github.com/serverless/serverless/blob/master/docs/guide

Let me know if you need any additional help!

**Comment by harighub** [comment]
Thanks all, now I was able to create a project using template option. sls create --template aws-python

**Comment by woss** [comment]
can you please update docs here https://serverless.readme.io/ or just remove it :)

**Comment by HyperBrain** [comment]
The 0.5 serverless version is still in use for legacy projects (even if there's no actual development happening anymore there) and the page explicitly shows only the old versions:
![image](https://user-images.githubusercontent.com/5524702/35682138-efea90c6-075f-11e8-92c0-db33b46a7322.png)

@woss But you're right 👍 At least a prominently placed link to the current version should be added there and some description that these docs are only for the legacy version.

@serverless/team Can you take care of that?
