### ISSUE TITLE
It would be nice if we can improve function configuration @ serverless.yml

### ISSUE THREAD

**Issue by harighub** [serverless/serverless#1843]
It would be nice if we can improve function configuration @ serverless.yml

##### Serverless Framework Version: 
1.0.0-beta.1.1

##### Operating System: 
Ubuntu 16.04 LTS

##### Actual Behavior:
I've tried to configure a event source for my serverless function, it appears be that a space ' ' after "-" and after ":" is mandatory. I believe it would be nice if we can eliminate such restriction for configuration. 
Eg:

functions:
  hello:
    handler: handler.hello
    events:
      - http: ==> Notice there is a space between - and http
         path: greet ==> Notice there is a spce between : and greet
         method: get

##### Stack-Trace (Optional):

  Serverless Error ---------------------------------------
 
     Invalid APIG method "path:greet" in function "hello".
     AWS supported methods are: get, post, put, patch, options,
     head, delete.
 
  Stack Trace --------------------------------------------
 
ServerlessError: Invalid APIG method "path:greet" in function "hello". AWS supported methods are: get, post, put, patch, options, head, delete.
    at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:56:19
    at Array.forEach (native)
    at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:15:29
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:2654:24)
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4380:18
    at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:8634:14)
    at AwsCompileApigEvents.validate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:14:7)

**Comment by openback** [comment]
That's due to the [YAML Spec](http://www.yaml.org/spec/1.2/spec.html#id2759963), so I don't think you're going to get your wish :P

**Comment by flomotlik** [comment]
@harighub as @openback already mentioned that is YAML syntax that we can't change. We do plan to support JSON in the future as well.
