### ISSUE TITLE
SLS remove failed, now SLS deploy won't work

### ISSUE THREAD

**Issue by merrickfox** [serverless/serverless#1845]
```
➜  lambda sls remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking stack removal progress...
........
  Serverless Error ---------------------------------------

     An error occurred while removing the stack

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

And now if I try and deploy

```
lambda sls deploy
Serverless: Zipping service...

  Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

Also trying the remove command again:

```
lambda sls remove
Serverless: Getting all objects in S3 bucket...

  Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

version: serverless@1.0.0-beta.1.1

Logs of the initial failure:
![alt text](http://i.imgur.com/ORWqRXV.png "error")

I've now read: https://github.com/serverless/serverless/issues/1689 and https://github.com/serverless/serverless/issues/1535
Wondering how to just reset and start over and attach role policies through serverless?

**Comment by ianserlin** [comment]
easiest way is to just change the name of your service from (what I think you named it) `workremote` to something else and get a whole new stack.

**Comment by flomotlik** [comment]
@merrickfox you can attach custom statements to the default IAM role that gets created:
https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-iam-role-statements

**Comment by flomotlik** [comment]
I'm going to close this issue as it seem it has to do with other Resources being attached manually? If there is a larger underlying bug please let me know and I'll reopen.
