### ISSUE TITLE
Include stage reference in AWS body mapping template

### ISSUE THREAD

**Issue by patrickbrandt** [serverless/serverless#1849]
### Feature Request:

Add a reference to $context.stage in the API Gateway body mapping template:

```"stage": "$context.stage"```

##### Benefits:

* There will be a run-time stage reference available to Lambda functions to load different environment configurations as required (via ```event.stage```).

##### Additional Details:

This provides a quick way to deploy environmentally-aware functions until issue #1455 is completed.

I've already forked and updated the appropriate file; see pull request #1850

**Comment by pmuens** [comment]
Hey @patrickbrandt thanks for reporting and fixing this 🎉 !

I'll look into the PR ASAP.

**Comment by pmuens** [comment]
Will be done with #1850
