### ISSUE TITLE
Install process hangs on void credentials file

### ISSUE THREAD

**Issue by remicastaing** [serverless/serverless#185]
I intentionally cleared (not removed) the credentials file and the process hanged at Select an AWS profile for your project:
![cap 2015-10-01 a 23 35 10](https://cloud.githubusercontent.com/assets/1715952/10234651/5cecdbc2-6896-11e5-8006-edcf8e10cc72.jpg)

**Comment by remicastaing** [comment]
I could PR something like that: if the credentials file exists, adding another choice below the profile to create another profile.
```
JAWS: Select an AWS profile for your project: 
  > default
  > create a new profile
```

**Comment by ac360** [comment]
Hmm it should prompt for API Keys instead.  I think it's a simple fix @remicastaing
