### ISSUE TITLE
shrinkwrap includes a few devDependencies, causing unnecessary warnings for users

### ISSUE THREAD

**Issue by jokeyrhyme** [serverless/serverless#1854]
##### Serverless Framework Version: 

`npm ls -g serverless`: serverless@1.0.0-beta.1.1

##### Operating System: 

macOS Sierra public beta

##### Expected Behavior:

- `npm install -g serverless@beta` should not generate any warnings

- ideally, only dependencies should be installed, not devDependencies

##### Actual Behavior:

`npm install -g serverless@beta` (as directed by quick start instructions) results in the following warnings:

> npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
> npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.

**Comment by jokeyrhyme** [comment]
It may be related, but certain `npm` operations on my computer now dump out lots of warnings about serverless:

npm ERR! peer dep missing: eslint@^2.9.0, required by eslint-config-airbnb-base@3.0.1
npm ERR! peer dep missing: eslint-plugin-import@^1.7.0, required by eslint-config-airbnb-base@3.0.1
npm ERR! extraneous: assertion-error@1.0.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/assertion-error
npm ERR! extraneous: caller-id@0.1.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/caller-id
npm ERR! extraneous: concat-stream@1.5.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/concat-stream
npm ERR! extraneous: contains-path@0.1.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/contains-path
npm ERR! extraneous: damerau-levenshtein@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/damerau-levenshtein
npm ERR! extraneous: deep-eql@0.1.3 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/deep-eql
npm ERR! extraneous: diff@1.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/diff
npm ERR! extraneous: doctrine@1.2.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/doctrine
npm ERR! extraneous: escodegen@1.8.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/escodegen
npm ERR! extraneous: escope@3.6.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/escope
npm ERR! extraneous: eslint-config-airbnb-base@3.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/eslint-config-airbnb-base
npm ERR! extraneous: eslint-import-resolver-node@0.2.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/eslint-import-resolver-node
npm ERR! extraneous: espree@3.1.6 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/espree
npm ERR! extraneous: file-entry-cache@1.2.4 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/file-entry-cache
npm ERR! extraneous: fileset@0.2.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/fileset
npm ERR! extraneous: formatio@1.1.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/formatio
npm ERR! extraneous: get-caller-file@1.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/get-caller-file
npm ERR! extraneous: globals@9.9.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/globals
npm ERR! extraneous: growl@1.9.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/growl
npm ERR! extraneous: handlebars@4.0.5 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/handlebars
npm ERR! extraneous: has-flag@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/has-flag
npm ERR! extraneous: ignore@3.1.3 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/ignore
npm ERR! extraneous: imurmurhash@0.1.4 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/imurmurhash
npm ERR! extraneous: inquirer@0.12.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/inquirer
npm ERR! extraneous: is-resolvable@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/is-resolvable
npm ERR! extraneous: jade@0.26.3 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/jade
npm ERR! extraneous: json-stable-stringify@1.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/json-stable-stringify
npm ERR! extraneous: jsx-ast-utils@1.3.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/jsx-ast-utils
npm ERR! extraneous: lcov-parse@0.0.6 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lcov-parse
npm ERR! extraneous: lodash.cond@4.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lodash.cond
npm ERR! extraneous: lodash.endswith@4.1.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lodash.endswith
npm ERR! extraneous: lodash.find@4.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lodash.find
npm ERR! extraneous: lodash.findindex@4.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lodash.findindex
npm ERR! extraneous: log-driver@1.2.4 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/log-driver
npm ERR! extraneous: lolex@1.3.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lolex
npm ERR! extraneous: lru-cache@2.7.3 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/lru-cache
npm ERR! extraneous: nopt@3.0.6 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/nopt
npm ERR! extraneous: os-locale@1.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/os-locale
npm ERR! extraneous: pkg-dir@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/pkg-dir
npm ERR! extraneous: pkg-up@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/pkg-up
npm ERR! extraneous: pluralize@1.2.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/pluralize
npm ERR! extraneous: progress@1.1.8 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/progress
npm ERR! extraneous: read-pkg-up@1.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/read-pkg-up
npm ERR! extraneous: request@2.74.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/request
npm ERR! extraneous: require-directory@2.1.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/require-directory
npm ERR! extraneous: require-main-filename@1.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/require-main-filename
npm ERR! extraneous: require-uncached@1.0.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/require-uncached
npm ERR! extraneous: set-blocking@2.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/set-blocking
npm ERR! extraneous: sigmund@1.0.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/sigmund
npm ERR! extraneous: strip-json-comments@1.0.4 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/strip-json-comments
npm ERR! extraneous: table@3.7.8 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/text-table
npm ERR! extraneous: to-iso-string@0.0.2 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/to-iso-string
npm ERR! extraneous: type-detect@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/type-detect
npm ERR! extraneous: underscore@1.7.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/underscore
npm ERR! extraneous: underscore.string@2.4.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/underscore.string
npm ERR! extraneous: user-home@2.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/user-home
npm ERR! extraneous: util@0.10.3 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/util
npm ERR! extraneous: which@1.2.10 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/which
npm ERR! extraneous: which-module@1.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/which-module
npm ERR! extraneous: wrap-ansi@2.0.0 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/wrap-ansi
npm ERR! extraneous: y18n@3.2.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/y18n
npm ERR! extraneous: yargs-parser@2.4.1 /Users/ron/.nvm/versions/node/v6.3.1/lib/node_modules/serverless/node_modules/yargs-parser

**Comment by jokeyrhyme** [comment]
Ooooo, nice work. :)

**Comment by oliverturner** [comment]
@flomotlik I'm seeing this behaviour resurface on serverless@1.3

node: 7.2.0
npm: 4.0.3

**Comment by pmuens** [comment]
@oliverturner thanks for commenting! We've already pushed a fix and the next version (1.4) shouldn't have it! 👍

**Comment by oliverturner** [comment]
@pmuens that's awesome! thanks for the info: much appreciated.
