### ISSUE TITLE
request: use configured AWS region instead of "us-east-1" by default

### ISSUE THREAD

**Issue by jokeyrhyme** [serverless/serverless#1855]
- related: #1707, #1736 

##### Feature Request:

- `serverless create --template aws-nodejs` should be aware of the default region set via `aws configure` or environment variables

- currently, it always puts an entry for "us-east-1" in the serverless.env.yml file, instead of something better

- if all else fails, falling back to the default "us-east-1" would still make sense

##### Benefits:

- 1 less thing that a user needs to change

##### Drawbacks:

- could be error prone? could be tricky?

**Comment by jokeyrhyme** [comment]
Just noticed that region also needs to be properly set in serverless.yml, too.

**Comment by jokeyrhyme** [comment]
Even if I change all occurrences of "us-east-1" in all default files to "ap-southeast-2", I still get the following error from `serverless deploy`:

> Region "us-east-1" doesn't exist in stage "dev"

Not sure where this is coming from

**Comment by danielkoo** [comment]
This is probably the same as what I ran into; if you haven't uncommented the following it would assume the dev stage uses us-east-1:

> defaults:
>   stage: dev
>   region: ap-southeast-2

**Comment by jokeyrhyme** [comment]
I made sure that I uncommented it, but it's possible that I got the indenting wrong or something. I'll give this another try later this week.

**Comment by flomotlik** [comment]
@danielkoo @jokeyrhyme we're currently changing our stage/region handling and include variables in #1834 and discussed in #1801 . This should sole many of those issues you've just mentioned as we're not going to expect you to set a specific region at all any more by default.

**Comment by jokeyrhyme** [comment]
@flomotlik awesome! Thanks! I look forward to giving it a try. I'm really liking everything about Serverless so far. Great work!

**Comment by flomotlik** [comment]
@jokeyrhyme if you're interested you can absolutely check out the branch and give it a spin. We're looking for feedback on this anyway at the moment before we merge.

**Comment by jokeyrhyme** [comment]
I can confirm that it was user error prevention me from explicitly setting the region, previously.

I'll take a look over the next few days to see how the branch improves things, if I can.

**Comment by danielkoo** [comment]
I'll have a play with the branch as well, cheers @flomotlik

**Comment by eahefnawy** [comment]
Closing this as it'll be fixed with #1834 

Thanks everyone! 🙌
