### ISSUE TITLE
Support Existing SNS Topic Resources when Adding Function Events

### ISSUE THREAD

**Issue by jarosser06** [serverless/serverless#1861]
Feature Request Template ------------------------------------------

##### Feature Request:
Support existing SNS Topic Resources when adding function events. Right now you can either specify the Topic ARN which allows you to use an existing topic but doesn't add the lambda function as a subscription when you do it that way. It would be helpful if the event code tried to use an existing SNS Topic resource and just modified the subscriptions to add the lambda function.

##### Benefits:
This would allow someone to add the SNS topic to the resources list and specify an SNS Topic Policy resource as well and still wire everything up so the subscription gets added.

##### Drawbacks:
This would make the Event code a little more complex since it would need to determine if an existing resource already exists for the SNS topic.

##### Additional Details:
My use case is the one described above, I need to add an SNS Topic Policy  but I am unable to do so if I let the event code create the resource since everything under resources executes before the lambda functions are added. If I do add it in the resources and specify an ARN for the event then I still need to go in after the fact and subscribe the function to the SNS topic.

**Comment by flomotlik** [comment]
@jarosser06 we recently changed how custom resource merging works and now custom resources are merged after the function and event resources are created. So you can overwrite or add to what we've been creating.

Existing SNS Topics can also be used through the ARN syntax.

I think this merge change should cover this use case, so I'm closing this issue. In case it doesn't please let me know and I'll reopen: https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-provider-resources
