### ISSUE TITLE
Implement Plugin Template that can be used with the Create plugin

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1868]
##### Benefits:
- Easy way for users to create new plugins
##### Additional Details:

`serverless create -t plugin` should create all the files necessary to create a new plugin. At the moment we're not loading any plugins from a local directory, so plugins that are in the current folder aren't used. We probably have to change some internals for this as well

**Comment by andymac4182** [comment]
It would be great if Serverless supported loading of plugins from outside the `node_modules` folder. We will have a few plugins that are being tested or for how a single project is set up. It would be great if these could be included as part of the package. My guess is that you could add a convention of a `plugins` folder similar to the node_modules one. https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L187

**Comment by andymac4182** [comment]
@flomotlik Were you thinking a default stubbed plugin that has a few events as examples or do you think it should include an example of commands as well?

**Comment by flomotlik** [comment]
Both command and events, but you already set this up anyway :D. Good job there.

**Comment by flomotlik** [comment]
Implemented and merged
