### ISSUE TITLE
Shell completions

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#187]
would be really cool once jaws is more stable, if someone could create shell completions for 
-  fish
-  bash
-  zsh
- others...

**Comment by binoculars** [comment]
:+1: especially for zsh. I'll start looking at this. All credible CLI tools need this.

**Comment by doapp-ryanp** [comment]
I'm a huge fish guy - so any extra attention you could pay to it i'd appreciate :)

**Comment by binoculars** [comment]
I'm looking over the docs for shell completion and it's not easy. It's going to be a steep learning curve for me. Maybe an opportunity to build tooling around it (secondary priority). If anyone has good tutorials, videos, info, or suggestions to get it started, I would definitely appreciate that.

**Comment by binoculars** [comment]
Found this guide for zsh: http://wikimatze.de/writing-zsh-completion-for-padrino/

**Comment by yyolk** [comment]
Anyone already on bash?

:fish:

**Comment by flomotlik** [comment]
We'd love to have shell completion. If somebody is interested to look into it please let us know, in the meantime I'm going to close this issue

**Comment by davidgf** [comment]
Hey guys, I built a really simple bash completion script. It supports all commands, function's subcommands and also completes function names. I'm not a shell scripting expert and it could (and should) be improved. For example, to find out function's names, it performs a `find` from the current directory (you can guess what would happen if that directory is the `/`) and doesn't exclude directories where we certainly know there won't be any function (`node_modules`, etc.). If anybody is willing to contribute to fix those glitches, or to add more subcommands, you can find the gist [here](https://gist.github.com/davidgf/5bd76141aa70f9ed4d8f716851e68830)

**Comment by danielesegato** [comment]
I created a fork of @davidgf bash autocomplete script that fix the `find .` problem, you can find it [here](https://gist.github.com/danielesegato/d4088ae0a1e67ba827cb0d8846038971)

**Comment by danielesegato** [comment]
@flomotlik shouldn't the issue be re-opened?
You had the contribution from @davidgf and now my fork.

**Comment by flomotlik** [comment]
@danielesegato yup agreed, just reopened. I'm not sure if we're going to release it with our old 0.x releases, but it would be great for our new V1 of the service. The commands changed a bit, but it should be easy to change once all of the commands we're implementing for V1 are in place. Thanks for the contribution

**Comment by danielesegato** [comment]
@flomotlik great to hear that.

Since my last message I've added support to all the current command in my fork but I think it still have room for improvements, for instance:

- does not autocomplete options (like --help)
- if you start writing - and then tab it gives an error
- miss autocompletion for third parameters in most commands (the only one supported is `function`)
- surely many other things I'm not even aware of

**Comment by flomotlik** [comment]
@danielesegato does this work with the new V1 stuff as well? Would be great to have this and put it in the docs.

**Comment by danielesegato** [comment]
@flomotlik I haven't tried V1 yet.
If the CLI API is the same then yes, it works.

I'll try tomorrow if I can and let you know

**Comment by danielesegato** [comment]
@flomotlik well apparently not, the script has to be rearranged because the CLI API is different

```
$ sls help
Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

create ................... Create new Serverless Service.
deploy ................... Deploy Service.
deploy function .......... Deploys a single function from the service
invoke ................... Invokes a deployed function.
info ..................... Displays information about the service.
logs ..................... Outputs the logs of a deployed function.
remove ................... Remove resources.
tracking ................. Enable or disable usage tracking.

Plugins
AwsInvoke, Create, Deploy, Invoke, Info, Logs, Remove, Tracking, AwsDeploy, Package, AwsInfo, AwsLogs, AwsRemove, AwsCompileFunctions, AwsCompileScheduledEvents, AwsCompileS3Events, AwsCompileApigEvents, AwsCompileSNSEvents, AwsDeployFunction
```

The script currently produce this:

```
$ sls <tab>
dash       endpoint   event      function   help       plugin     project    region     resources  stage      variables
```

So no, the current script doesn't work with v1

**Comment by jordanmack** [comment]
I'm a little late to the party on this one, but I just saw the issue. I had a 95% completed version ready way back in April. I already ran into several of the problems @danielesegato mentioned, and rectified them in my version.

I had e-mailed Austen about it, but he never responded so it just kind of sat there, and I had to move on to other projects. It hasn't been worked on since then, so it is not yet v1.0 compatible.

From my e-mail to Austen on April 3rd:
```
Serverless Bash Tab Completion is ready for an early look when you have some time. I've been using it daily, and it works well. Below is a URL to the manual installation instructions, and development notes. Automatic installation is the last significant feature I still need to look into.

http://bit.ly/1pVX34q
```

**Comment by flomotlik** [comment]
@danielesegato @jordanmack yup the new version uses a completely new CLI (pretty much reimplemented everything including the commands)

@jordanmack sorry for the delayed response there, but thanks for putting the time into it.

**Comment by colbywhite** [comment]
I started playing around with getting a zsh completion file with v1.0 of the CLI. Got pretty far. 

https://gist.github.com/colbywhite/18f1a0a82f1dd2a7725253ddc6557aca

The main thing I'm stuck on is handling the `sls deploy` and the `sls deploy function` subcommand. I'm not a zsh-completion ninja so that's been tripping me up. If anyone has any feedback, please let me know.

**Comment by flomotlik** [comment]
At the moment we don't plan to put resources into Shell completion, so I'm going to close this issue for now. If somebody is interested on working this ping me please.
