### ISSUE TITLE
Are Serverless docs up to date? 

### ISSUE THREAD

**Issue by lexakozakov** [serverless/serverless#1871]
Hello,

Is Serverless documentation up to date? I've managed to install the lib and create a new project from nodejs template. It works. 

I've started to read docs from http://docs.serverless.com/v0.5.0/docs and no one command works. I did't find any "s-project.json" file into the project as well. 

Could you please share any link with full documentation and examples? 

Thank you so much.

**Comment by lexakozakov** [comment]
@pouledodue You are right. I've installed Serverless beta version. Where could I find the docs (except [that one](https://github.com/serverless/serverless#documentation))?

I need to create an Authorizer function to integrate Amazon Cognito user Pool with Api Gateway. And I'm not aware how/where to create a new Custom Authorizer in API Gateway. 

Any help and example is deeply appreciated.

**Comment by pouledodue** [comment]
for fast answer you may ask on the gitter channel

**Comment by chris-olszewski** [comment]
@lexakozakov the docs currently reside on Github [here](https://github.com/serverless/serverless/tree/master/docs) and then in different plugin directories e.g. [here](https://github.com/serverless/serverless/tree/master/lib/plugins/deploy)

**Comment by flomotlik** [comment]
docs.serverless.com is now pointing to the latest V1 docs (DNS cache might take a bit until its changed). Thanks for reporting!
