### ISSUE TITLE
Validate/fix file permissions when creating deployment zip

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#1872]
##### Feature Request:

We had a weird problem today which caused one Python module import to fail. Basically what we got was "Unable to import module 'handler': No module named 'hooks'" -error. 

'hooks' module definitely was inside the deployment package and locally all tests passed. 

After some furious debugging, it seems that all the .py files should have a+r file permission or otherwise importing will fail on AWS Lambda and it's very hard to debug why it happens. For some reason this one file didn't have this permissions. 

So I suggest that this should be validated or permissions in the deployment ZIP file should be set correctly.

**Comment by pmuens** [comment]
Hey @pmuilu thanks for reporting!

This issue might be related to: https://github.com/serverless/serverless/issues/1860, https://github.com/serverless/serverless/pull/1857 and https://github.com/serverless/serverless/pull/1863

**Comment by flomotlik** [comment]
@pmuilu is that happening on a windows machine? Could you install the latest master with `npm install -g serverless/serverless` and test with that? On windows this should work fine now.

**Comment by pmuilu** [comment]
@flomotlik Nope, Linux machine. I was able to get it work after just fixing the permission for that one specific file.

**Comment by flomotlik** [comment]
Ok then I'll close this issue
