### ISSUE TITLE
1.0.0-beta.2 makes it impossible to enable CORS on an existing endpoint (which previously had CORS enabled manually)

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1883]
##### Serverless Framework Version: 

```
1.0.0-beta.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

to enable CORS

##### Actual Behavior:

Since CORS support finally came out in beta I thought I am going to switch from manually enabled CORS to `serverless` enabled cors.

So naturally, I went through all of my endpoints and added `cors: true` like so:

![image](https://cloud.githubusercontent.com/assets/3421858/17732742/32d6e9f0-646b-11e6-8692-052abf85e93a.png)

then `sls deploy` gave me this:

![image](https://cloud.githubusercontent.com/assets/3421858/17732725/1cd4a17e-646b-11e6-9a59-2089b8539c69.png)

and then `cloudformation` gave me this

![image](https://cloud.githubusercontent.com/assets/3421858/17732777/64741596-646b-11e6-8873-b42aecc86dbd.png)

Ok, I thought, maybe I just need to do a fresh redeploy so I removed all `cors: true` and `sls deploy`'ed again (succesfully):

![image](https://cloud.githubusercontent.com/assets/3421858/17732812/8ca398fc-646b-11e6-8cda-1070b384111d.png)

and `cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17732878/d99941f2-646b-11e6-976d-40a20849cee0.png)

Great! I thought to myself despite the fact that all CORS resources were still available in aws console:

![image](https://cloud.githubusercontent.com/assets/3421858/17732910/fdaa635a-646b-11e6-903e-7f09edacecb9.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/17732919/0a559084-646c-11e6-9950-28dcf8738467.png)

I figured, if I add `cors: true` now everything should work splendidly, but..

![image](https://cloud.githubusercontent.com/assets/3421858/17732975/482ba6aa-646c-11e6-89d3-4527938a3b41.png)

and `cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17732969/4193f3d8-646c-11e6-9106-cdcde0a766fd.png)

OK, I thought surely removing the whole endpoint and adding it again with cors would definitely work, right ?

Not a chance...

this removed endpoint entirely (from aws console too):

![image](https://cloud.githubusercontent.com/assets/3421858/17733481/bcc8bcd0-646e-11e6-9705-6e03d0a02afd.png)

got me here:

![image](https://cloud.githubusercontent.com/assets/3421858/17733503/ddef185a-646e-11e6-80ec-9b3d9725abf7.png)

Then this:

![image](https://cloud.githubusercontent.com/assets/3421858/17733512/e6b52556-646e-11e6-9e49-394b970dbd5c.png)

got me here:

![image](https://cloud.githubusercontent.com/assets/3421858/17733525/ff3e62b8-646e-11e6-9836-439329db4f17.png)

aws console:

![image](https://cloud.githubusercontent.com/assets/3421858/17733548/1b84b620-646f-11e6-8832-aae30303c48e.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/17733558/272a5b1a-646f-11e6-9c66-cd1f4563f044.png)

And this finally fixed the issue.

**Comment by codepreneur** [comment]
Closing.

**Comment by flomotlik** [comment]
I'm not sure I'm following, but is this an issue or not? My assumption is that if CORS is enabled already on the endpoint than adding our Cloudformation stuff will have issues

**Comment by codepreneur** [comment]
@flomotlik that is exactly the issue here. It seems to be a general theme around `serverless`. I posted some issues few weeks ago with the same problem like #1677 where @svdgraaf explained how it is a CF issue and not `serverless` hence me closing this issue.

**Comment by flomotlik** [comment]
Yup got what you mean. Merging existing resources into Serverless is definitely something complex going forward. Some events already give you the ability to add an ARN instead of us creating a resource ourselves so that helps. But if you want to have all the resources managed through CF in the Serverless service then you somehow have to get those resources.

Basically as long as they are created as custom resources and are part of the same CF stack that makes things a lot easier. I'm not sure yet if there is a way to change the logical but make CF aware that its still the same resource. If its in the same CF stack we can at least do something about it. If the resources were created externally I don't think we can move them into the CF stack easily.

I don't think there is something specifically actionable in the issue so I'll close it, but its definitely something to be aware of going forward.
