### ISSUE TITLE
Show failed Events from Cloudformation deployment if deployment fails

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1885]
Feature Request:

Benefits:

* Making it easier for users to see what is the specific issue that happens
* Allowing us to get better bug reports as people can directly post the issues

##### Drawbacks:

* Makes the error log longer

**Comment by nicka** [comment]
As talked about in #1818.

Can't we just tail the CloudFormation deployment events during the deployment? With some nice `chalk` colors like the AWS CloudFormation console shows it for `CREATE_IN_PROGRESS`, `UPDATE_IN_PROGRESS`, `DELETE_IN_PROGRESS`, etc. Would totally skip the need to have the AWS console open.

**Comment by flomotlik** [comment]
Missed that one. Duplicate of #1818 so closing
