### ISSUE TITLE
Create Tmpdir in a better way than with Date

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1887]
Currently in our tests and in the serverless application itself we're creating tmpdirs or any kind of random variable by creating a new Date and converting it to string. This is a MASSIVE code duplication and Date is also not a great entity to use for Random strings.

We should remove that reliance on Date completely and move to something more random and provide randomising methods in the test suite and application itself

**Comment by pmuens** [comment]
Resolved with #1936
