### ISSUE TITLE
Package artefacts are not renamed which means the CF template doesn't change and no deployment happens

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1892]
**Serverless Framework Version:** Master 

**Operating System:** Any

**Expected Behaviour:**

When you run `serverless deploy` and have an artefact defined we should create a new and random name for the artefact (and use the same name as we do when creating our own artefact) and upload with that name to S3. Then when we update the CF template it is properly changed and a Redeploy happens.

**Actual Behaviour:**

The CF template isn't changed as the name of the artefact stays the same so no deployment happens and an error is thrown

**Comment by pmuens** [comment]
Will be solved with https://github.com/serverless/serverless/pull/1906
