### ISSUE TITLE
V.1 ES6 babel setup ?

### ISSUE THREAD

**Issue by andyfenelon** [serverless/serverless#1894]
can't see any information on this for V.1

first query, the optimizer plugin seems to be erroring ?
```
plugins:
  - serverless-optimizer-plugin
```

is giving this error 

>   Type Error ---------------------------------------------
>  
>      Class extends value undefined is not a function or null
>  
>      For debugging logs, run again after setting SLS_DEBUG env var.
>  
> 

second, how would this v.0 code be be set up for the transforms in v.1? cant see any info in the doc's on how transforms, unless i've missed it?
v.0 code in /function/ s-function.json how to port this to v.1 ?
```
"custom": {
  "excludePatterns": [],
  "optimize": {
    "exclude": [
      "aws-sdk"
    ],
    "transforms": [
      {
        "name": "babelify",
        "opts": {
          "presets": [
            "es2015"
          ]
        }
      }
    ]
  }
},
```

thanks.

**Comment by DavidWells** [comment]
There is a new webpack plugin for es6 that works with v1 https://github.com/serverless/community-plugins/issues/2

**Comment by andyfenelon** [comment]
nice.
