### ISSUE TITLE
Empower Users to Employ a Rights Management Strategy that Works for Them

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#1895]
If you see:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/functions/index.js#L136

The code there currently being

```
      newFunction.Properties.Role = { 'Fn::GetAtt': ['IamRoleLambda', 'Arn'] };
```

This requires that user's rights management strategy be subsumed by the limited "single bubble per stage" approach that is less secure and blocks adoption for some (at least us).

We should probably discuss lots of solutions rather than the first thing that occurs to me but it appears that the value `'IamRoleLambda'` could be the default value for a role attribute that could be applied to the provider (like current behavior) and/or functions to optionally (and potentially partially) override or specify it on a per function basis.  The value of the role attribute would be the name of a resource.

**Comment by flomotlik** [comment]
Imho there are 2 different things we can do around this:

1. Allow users to create per function IAM roles as discussed in #1807
2. Allow users to set ARNs for the role (for the whole service or per function) so they can create roles in a separate deployment and simply point to those roles #1772

Due to the new variable syntax ( #1834 ) it should also be easy to have different ARNs for different stages as you can inject them through config files, environment variables, ...

@erikerikson would that fulfil your needs there? Any other ideas or use cases that are not covered there? Imho both of these are pretty simple to implement thanks to the CF deployment (so hopefully somebody in the community can jump in as there a lot of stuff to do in general :D )

**Comment by erikerikson** [comment]
Thanks @flomotlik.

#1807 is exactly the strategy we've been accomplishing here with a parallel system that we've enabled using customRole (the feature requested in #1772) in `0.3? < v < 0.6`.

The framework could reimplement those old capabilities but I think the ideal circumstance for us is that we can sunset our custom role management and begin to use SLS capability for role creation.  That will require sufficient flexibility and expressibility in the framework which gets me to my next point.

I've previously expressed and long felt that the framework should be unopinionated about rights provisioning (and naming) strategies.  The "use a role for all lambdas in the service" or "use different roles for each lambda in the service" rights management strategies should really be two different instantiations of the rights provisioning capability implemented by the framework.  Similarly any default naming strategies should be an instantiation of the more general (and never hard coded) name assignment/management capability provided by the framework.

I suspect that the biggest challenge would be that (assuming an AWS context) the input to the lambda CFT definition would need to be a reference to the as yet unnamed (due to CFT postfixes) role.  It seems this could be simplified from a framework perspective if the specifically unique rights of each lambda's role were pushed into the function definitions themselves and used to specialize a service template role that users could define (in order to override the default iamRoleLambda [in the AWS case] role).

Your link to #1834 could possibly provide a means of accomplishing this if it were augmented to allow reference to the generated elements within the CFT.

There's been a lot of disruptions in scripting this so please accept my apologies if it's not entirely cogent.

**Comment by erikerikson** [comment]
Maybe I am missing that something like `self.resources.Resources.[myResource].arn` is enabled by #1834?

@eahefnawy, is that dreaming^

**Comment by eahefnawy** [comment]
@erikerikson yep you can access all sub properties of any custom resource as long as u have it in the file on disk.

**Comment by flomotlik** [comment]
@erikerikson @eahefnawy just to clarify only the elements in your serverless.yml are available. `self.resources.Resources.[myResource].arn` will not be available (unless you set it specifically) as this is only populated in Cloudformation.

**Comment by flomotlik** [comment]
>Your link to #1834 could possibly provide a means of accomplishing this if it were augmented to allow reference to the generated elements within the CFT.

You mean referencing beyond CF Ref syntax? Or how would you think the config should look?

**Comment by erikerikson** [comment]
Thanks @eahefnawy and @flomotlik - What @flomotlik said is not available is exactly the thing that  I suspected would be easy to think about.  It would require that the reference be translated into a CFT reference statement and I didn't actually expect it to be available.

I'm probably overthinking this.  Here's what I would expect it to look like:
```
defaults:
  role: { 'Fn::GetAtt': ['myDefaultRole', 'Arn'] }

functions:
  func0:
    #role: # not set as it uses the default role
  func1
    role: { 'Fn::GetAtt': ['myVpcRole', 'Arn'] }
  func2
    role: { 'Fn::GetAtt': ['myCustRole', 'Arn'] }

resources:
  Resources:
    myDefaultRole:
      Type: AWS::IAM::Role
      RoleName: MyDefaultRole
      Properties:
        Path: /my/default/path
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:${region}:${accountId}:log-group:/aws/lambda/${lambdaName}*:*:*
    myVpcRole:
      Type: AWS::IAM::Role
      RoleName: MyVpcRole
      Properties:
        Path: /my/default/path
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:${region}:${accountId}:log-group:/aws/lambda/${lambdaName}*:*:*
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: *
    myCustRole:
      Type: AWS::IAM::Role
      RoleName: MyCustRole
      Properties:
        Path: /my/cust/path
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:${region}:${accountId}:log-group:/aws/lambda/${lambdaName}*:*:*
                - Effect: Allow
                  Action:
                    - cloudwatch:PutMetricData
                  Resource: *
```

**Comment by erikerikson** [comment]
Of importance would be that the IamRoleLambda role would only be created if a function was discovered for which a provided/defined(?) role was not supplied.

**Comment by flomotlik** [comment]
@erikerikson you can already achieve what you've configured, with the exception that IAMRoleLambda will still be created.

The plan for per function IAM Roles is to achieve exactly what you configured here, we're creating an IAM role for every function that has statements configured and if all of them have them configured (or they point to some externally created Role) we don't create a service role.

And if you want to change that role in any way you can add custom resources that will be merged with the role as we're also currently making sure the LogicalNaming is good in #1869 

So it sounds to me like we're on the same page here? Or do you see any discrepancies with this?

**Comment by erikerikson** [comment]
@flomotlik is that on a branch other than master?  I've been reading through the code and that is why I opened this in the first place.

Do you see IamLambdaRole as necessary or are you just communicating the current state?  A requirement for IamLambdaRole prohibits adoption here.

Logical naming sounds nice but I'm still wrapping my head around the new world that's been created.

**Comment by erikerikson** [comment]
Incidentally, I think I would prefer the following revision.  It assumes that custom roles will be merged with the default role in order to increase the terseness of specification.

```
defaults:
  role: { 'Fn::GetAtt': ['myDefaultRole', 'Arn'] }

functions:
  func0:
    #role: # not set as it uses the default role
  func1
    role: { 'Fn::GetAtt': ['myVpcRole', 'Arn'] }
  func2
    role: { 'Fn::GetAtt': ['myCustRole', 'Arn'] }

resources:
  Resources:
    myDefaultRole:
      Type: AWS::IAM::Role
      RoleName: MyDefaultRole
      Properties:
        Path: /my/default/path
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:${region}:${accountId}:log-group:/aws/lambda/${lambdaName}*:*:*
    myVpcRole:
      Type: AWS::IAM::Role
      RoleName: MyVpcRole
      Properties:
        Path: /my/vpc/path
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: *
    myCustRole:
      Type: AWS::IAM::Role
      RoleName: MyCustRole
      Properties:
        Path: /my/cust/path
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - cloudwatch:PutMetricData
                  Resource: *
```

**Comment by erikerikson** [comment]
What I described [here](https://github.com/serverless/serverless/issues/1895#issuecomment-241823253) seems to comprise two changes.  The first is the original point of this issue.  The other is an inheritance capability for specifying a base role and combining its definition with other roles to enable greater terseness in role definition.  I will PR the former first and we can discuss the desirability of the second separately.

**Comment by flomotlik** [comment]
@erikerikson With the *first* point you mean setting up a separate Role per function?

**Comment by erikerikson** [comment]
Exactly @flomotlik.  Working on tests now.

**Comment by erikerikson** [comment]
Well... in our specific case anyway.  I'm attempting to implement it so that any strategy (including a hybrid of shared and individual) can be used.

**Comment by eL0ck** [comment]
Sorry to come in late with this @erikerikson! 

What do you see as the advantage of using the ARN?  

Why not:
`iamRole: myDefaultRole`
rather than:
`iamRoleARN: { 'Fn::GetAtt': ['myDefaultRole', 'Arn'] }`

----------

Addressing your point about inheriting from parent roles in [#1807](https://github.com/serverless/serverless/issues/1807#issuecomment-246093005) (You suggest an `inheretsFrom` parameter)

Why not always generate a role per function (e.g `IamRoleFunc1` rather than `IamRoleLambda`) and allow the user to specify policies.  Something like:

```
service: new-service
provider:
  name: aws
  iamPolicies: # If not specified, gets the default log access already in place
    - IamPolicyDefault  

functions:
  func0: # automatically assume new role 'IamRolefunc0'
    iamPolicies: 
      - default
      - IamRoleDDBread
      - IamRoleS3write
    ...
  func1: #  assumes 'IamRolefunc1'
    iamPolicies: 
      - default
      - IamRoleDDBwrite
  func2: # assumes 'IamRolefunc2'
    # No policies specified, inherits provider default  policy
    ...
```

This would reduce complexity of CFN Template under `resources` and allow the user to specify only the `PolicyDocument` part  once, regardless of how many functions use it.

Again, sorry.  This is about 24 days late.

**Comment by erikerikson** [comment]
personally, @eL0ck, I'd have preferred to do something like:
`role: myRole`
which I would expect to translate in the generated CFT into:
`{ 'Fn::GetAtt': ['myRole', 'Arn'] }`

I stuck with `iamRoleARN` despite the non-convention-compliant name and the rest of it because when I dug into the code `iamRoleARN` was already in use and it seemed like it would be clumsy to have `iamRoleARN` *and* `role`.  In the final representation, the lambda CFT requires an ARN for that attribute.  I wouldn't mind shifting that.  An additional consideration is that I am guessing the part of the original justification is that it allows for the use of roles that aren't defined within the service's CFT (i.e. it is declared in the console or via a different CF stack) which would enable some workflows that were previously blocked.

So long as we're only talking about the default permissions behavior (which is outside of the scope of this issue and the associated PR), then I think it would be really sensible to have a per-lambda role.  As is, we do a bit of extra work to make that happen and I would assert it is something everyone should take advantage of.  It does create a larger number of roles and policies.  Therefore it increases risks of running into account policy and role count limits.

That said, the biggest reason I created this issue is that the default IAM approach used by SLS isn't accepted by our modified AWS environment.  Specifically: we don't allow individual developers to create policies.  Instead we only allow roles with inline policies to be created.  I wouldn't want to pave the way for my own use case while blocking another exotic flavor of IAM management.

As for provider agnosticism, while I am mostly familiar with AWS, I suspect that the declaration of rights and the use of roles (etc.) is actually very provider specific so that a generic cross-provider role would just hide very provider specific naming and usage details that are necessary and would thereby be more of a hinderance than a savings.

**Comment by jthomerson** [comment]
Just to follow up on @erikerikson I also have never been a fan of `iamRoleARN` as it's a weird naming pattern.

**Comment by flomotlik** [comment]
Closing this discussion issue as we're implementing different other tasks to get this released now.
