### ISSUE TITLE
Update artifact deployment process

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1898]
The current artifact deployment process works as follows:

Create a .zip file with the content of the Serverless service, timestamp it and upload it to the S3 bucket. Also remove other versions of this file so that only 5 are kept.

However https://github.com/serverless/serverless/pull/1886 introduced the CloudFormation template storing in the S3 bucket.

The CloudFormation template is currently stored on the root level and is overwritten / not versioned on each deploy.

However versioning should be done for both, the .zip file and the CloudFormation template.

The Proposal is to do the following on deployment (brought up by @flomotlik):

> How about for every deployment we create a separate directory and put the zip file and the CF template in that directory? Then the logic for removing old versions would simply be order directories by name (Imho directory should have a mix of timestamp and readable date, e.g. 141264711231-2016-08-18-15:48:32) so that it can be easily ordered by the first part of the timestamp but its still human readable.

> And the Zip file and CF template in each directory could have the same name and if we want to add more artefacts in the future thats simple (e.g. nested stacks)

**Comment by flomotlik** [comment]
Gogogo :D

**Comment by pmuens** [comment]
Resolved with https://github.com/serverless/serverless/pull/1906
