### ISSUE TITLE
Add --name option to create plugin

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1902]
##### Feature Request:

With `serverless create -t aws-nodejs --name my_service` you should be able to automatically overwrite the name of the created service

##### Benefits:

* Make it easier for users to set the name and not run into an issue when the name is set to the default name

# Linked Issues:
* #1616

**Comment by mrlamroger** [comment]
Would love feedback on the possible approaches here https://github.com/serverless/serverless/pull/1910

**Comment by pmuens** [comment]
Closing this as a PR (#1910) was opened for this one. We'll continue the discussion there.
