### ISSUE TITLE
cf-stack and api-gateway resources be called ${stage}-${serviceName} when deploy a sls-service

### ISSUE THREAD

**Issue by rogemita** [serverless/serverless#1907]
when I deploy a sls-service then the CloudFormation stack prefixes the stage into the resource name, the same applies to the api-gateway which it creates, for example in serverless.yml says "service: hello" then when the cf-stack created it is called dev-hello and if you set up some endpoint also the api-gateway is called dev-hello, I think it is a redundancy because api-gateway has stage behaviours inside. Should it be called "hello" without the "${stage}-" prefix?

Serverless Framework Version: v1-beta2
Operating System: irrelevant
Expected Behavior: cf-stack and api-gateway resources be called like service name without stage prefix

**Comment by flomotlik** [comment]
Thanks @rogemita for reporting. This is something we're going to address with #1834 and #1869 in the near future. As we already got issues around it I'm going to close this one but its referenced in the other issues.
