### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by dsshap** [serverless/serverless#1912]
##### Discussion:

HI SLS Team,

We are currently running a rather large serverless application. We would like to make the move to v1 once it is released. Is there a plan to release an upgrade guide for those coming from 0.5.6?

From what i have followed, there are several breaking changes, so it would be useful to describe all those changes to make the transition as seamless as possible.

Thanks and keep up the great work!

**Comment by flomotlik** [comment]
@dsshap yup we definitely plan to have docs in place to make it easier for you to switch over to the latest version. There are currently a few things in the pipeline that will still change things quite a bit like #1834 but once they are out we'll focus more on docs to make this easy.

**Comment by dsshap** [comment]
Thanks @flomotlik 

Looking forward to the upgrade!

**Comment by dsshap** [comment]
@flomotlik any ideas on when this guide will be available?

**Comment by flomotlik** [comment]
@dsshap sorry for the delay, yup will be available very soon. Basically everything changed though. Its a complete reimplementation so it kind of is a completely new tool for the most part.

**Comment by mthenw** [comment]
Migration info can be found in docs:  https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/v0_to_v1.md#how-to-upgrade-from-0x-to-1x
