### ISSUE TITLE
deploy can't find modules node_modules

### ISSUE THREAD

**Issue by matt-filion** [serverless/serverless#1914]
* Check if an Issue already exists for this: **none found.**
* Add the relevant label(s): **I don't seem to have permission (or don't know how).**
* Be kind :)

Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
1.0.0-beta.2

##### Operating System: 
Windows 10

##### Expected Behavior:
sls deploy should package up my project, and deploy to lambda. When I invoke lambda anything in node_modules should be found using require('name-of-module')

##### Actual Behavior:
sls deploy packages everything up, when I invoke the function the module cannot be found. When i re-zip up the package with 7zip, everything works as expected. To be clear, i download the deployed code from lambda, unzip it, re-zip it (without making changes) and it now works. 

I've seen this before, when using zip algorithms that lambda didn't like. I cannot recall the problem or solution at this time.

##### Stack-Trace (Optional):
```
{
    "errorMessage": "Cannot find module 's3-db'",
    "errorType": "Error",
    "stackTrace": [
        "Module.require (module.js:353:17)",
        "require (internal/module.js:12:17)",
        "Object.<anonymous> (/var/task/handler.js:4:15)",
        "Module._compile (module.js:409:26)",
        "Object.Module._extensions..js (module.js:416:10)",
        "Module.load (module.js:343:32)",
        "Function.Module._load (module.js:300:12)",
        "Module.require (module.js:353:17)"
    ]
}
```

**Comment by pmuens** [comment]
Hey @matt-filion thank you for reporting this. We've recently added a fix which should resolve this problem (see https://github.com/serverless/serverless/pull/1863).

Could you install the newest Serverless version via `npm install serverless/serverless` to see if it's resolved?

Thanks!

**Comment by matt-filion** [comment]
That fixed the issue. I had upgraded earlier in the day using `npm upgrade serverless -g`.
