### ISSUE TITLE
Upload zip with "Reduced Redundancy"

### ISSUE THREAD

**Issue by ortreum** [serverless/serverless#1916]
Due to saving money at the bleeding edge serverless should upload the versioned zip files to S3 with the "Reduced Redundancy" flag enabled. It would save 50% of S3 storage costs.

_serverless.yml_
provider:
    name: aws
    runtime: nodejs4.3
    s3upload: none|reduced|full # default = reduced
    glacier: 100|1 year # = move all files older than the 100th version or 1 year to glacier

Michael

**Comment by flomotlik** [comment]
Hi @ortreum , thanks for bringing this up. We've implemented auto-cleaning of old deployment files, so only 5 will stay inside of the bucket at any time. This already makes sure that the costs stay basically nothing for the deployment artefacts so we don't really want to introduce any additional cost saving mechanism which could be a potential issue for some deployments (even though its relatively unlikely to be an issue at any time).

As we don't plan to implement it at the moment I'm going to close, but if we get back to it at some point we'll pick it up from here. Thanks for bringing this up!
