### ISSUE TITLE
Add stage name to API in API Gateway

### ISSUE THREAD

**Issue by Nopik** [serverless/serverless#192]
I'm working with a number of stages (basically 1 stage per developer), and naming N APIs in the Gateway with identical names is extremely confusing there (as API Gateway UI isn't perfect yet, either). I would love to see stage name added to the API name.

**Comment by ac360** [comment]
:+1:

**Comment by ac360** [comment]
This is a quick fix but it brings up a more important issue.  

Right now, JAWS doesn't use API Gateway's staging mechanism.  Instead, it makes a separate REST API for each stage/region in your project.  

To use API Gateway's staging functionality and to be aligned with how AWS works, JAWS will need to be changed in these ways:

* JAWS need to creates 1 REST API only per project region
* JAWS will need a way to save regional REST API IDs in jaws.json
* JAWS then needs to create deployments for each stage in the regional REST API

**Comment by Nopik** [comment]
Yeah, having 1 API with multiple stages could be even better ;)

**Comment by doapp-ryanp** [comment]
I think we should not circumvent the APIG staging mechanism that is in place today
