### ISSUE TITLE
Included 3rd party python modules are failing to import

### ISSUE THREAD

**Issue by charlierm** [serverless/serverless#1925]
##### Serverless Framework Version: 
1.0.0-beta.2

##### Operating System: 
Windows 10 Enterprise

##### Expected Behavior: 
Python modules included in the root directory are zipped into the package and successfully imported when function is invoked.

##### Actual Behavior:
This is a truly bizarre issue :fearful: 

I have a simple serverless project with a single python handler using a pip installed module (requests). After running `serverless deploy` and invoking the function the module fails to load with: 
`Unable to import module 'handler': No module named requests` 

I downloaded the deployed package, the structure was as expected:
```
serverless_project
│   handler.py
│   requests # Installed with pip install requests -t .
```

I then tried manually zipping and updating the lambda package, this worked!

I unzipped both zip files and diffed them, they were identical. 

I am utterly confuzzled. 
[zipped_by_me.zip](https://github.com/serverless/serverless/files/430878/zipped_by_me.zip)
[zipped_by_serverless.zip](https://github.com/serverless/serverless/files/430880/favourites-lambda-api-1471890231650.zip)

[Added the project as a gist](https://gist.github.com/charlierm/d25c02a424af60a7653e7307ac7b2c8c)

Any help appreciated! Thanks :+1:

**Comment by pmuens** [comment]
Hey @charlierm thanks for reporting. This. We've just pushed a fix for windows users the other day.

Could you install the latest release form the master branch via `npm instlal -g serverless/serverless`? This should resolve your problem!

**Comment by charlierm** [comment]
@pmuens I've updated to the latest release and it's resolved the problem. 

I'm guessing it relates to #1872.

Thanks for your help :+1:

**Comment by pmuens** [comment]
@charlierm great!

FYI here's the PR which resolved the issue: https://github.com/serverless/serverless/pull/1863
