### ISSUE TITLE
Serverless 0.5.6 docs no longer avaialable

### ISSUE THREAD

**Issue by marioatlp** [serverless/serverless#1928]
There are many people who implemented/implementing serverless based on the 0.5.6 branch. After the most recent push of the beta 2 for the v1 branch all the links now point to the new documentation and there is no apparent or obvious way to recall the old documentation page(or github branch if there is one).

**Comment by pmuens** [comment]
Hey @marioatlp thanks for pointing that out.

The old documentation lives here: https://serverless.readme.io/v0.5.0/docs

We need to update our README.md file to point to the correct docs links. I'll do that in a second.

**Comment by pmuens** [comment]
@marioatlp just pushed a fix: https://github.com/serverless/serverless/pull/1932

Thanks for reporting this!
