### ISSUE TITLE
Resources in Serverless.yml

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#1933]
I have several Lambda functions that are taking care of trigger events for various AWS services (for example Cognito Sync Trigger). I have tried to create custom resource json which seem to do what I want, however I've bumped to few "conceptual issues" and I'm not sure what is "serverless-way" to handle these or is there any.

1. If I have Lambda function that requires permissions e.g. I need to define that "Principal" cognito-sync.amazonaws.com should be able to "Lambda:Invoke" a function I've deployed with SLS. This works fine if I've already deployed the functions. However this does not work if I create the environment from scratch as SLS is deploying these permissions before the functions. So what happens is that CloudFormation panics as it can't find the functions mentioned in the permission json and goes to rollback mode (which btw quite often fails which is a bit concerning). What is the correct way to handle this? Currently I just comment out the Resources for the first deployment. 

2. Some CloudFormation resource statements fail if the resource for example already exist. They work fine for the first deployment but subsequent deployment will fail as the item already exist. I understand that there are some tricks that could be done in CloudFormation template but is this something that Serverless should take care of?

**Comment by flomotlik** [comment]
@pmuilu Can you upgrade to the latest Beta 2 or master. We've implemented a new way resource merging works that should resolve these merging issues. I'll close for now as this is a resolved problem on master.

**Comment by pmuilu** [comment]
Ok thanks, I was using beta 2 from last night. But yeah. I'll see whether master fixes this.

**Comment by flomotlik** [comment]
You might have to add DependsOn relationships as well. I think Ref typically takes care of this automatically, but if not make sure you're adding DependsOn to all of your custom Resources so the functions are created and the custom resource depends on the function to be created. http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html
