### ISSUE TITLE
Download Serverless service via git URL form the command line

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1938]
It would be great if one can download a Serverless service via a git url form the command line.
This way one can directly download and deploy pre-existing services (e.g. an auth service) without going through `git clone` or "download zip".

It's basically the same like we already do with the templates except that the template is a full service which is accessible through git.

Something like `serverless create --gitUrl <gitUrl>`.

Not sure if it should live in the `create` plugin or if a new plugin should be introduced here.

/cc @serverless/core @worldsoup

**Comment by worldsoup** [comment]
This is a feature I'd love to use! The main two use cases for me would be:

1. downloading some example services that the Serverless team provides as part of on-boarding 
2. downloading services submitted by 3rd party developers that help me easily use their service

**Comment by ac360** [comment]
+1000  I'm currently in favor of `install` instead of `create`.  Also, we've already written this code in V.0 (though we ended up taking it out for other reasons) and it's in there if you need something to reference.  I believe Ian Strom Taylor has a nice lib for downloading and unzipping from git, which works with branches, etc.

```
sls install <gitUrl>
```

**Comment by ac360** [comment]
Also, we spoke with @flomotlik and this is definitely a priority.

**Comment by pmuens** [comment]
Great. Thanks @ac360 for the pointers. Just moved it to the beta.3 milestone as it shouldn't be that hard to implement.

Maybe we should also introduce a `community-services` repository which is similar to the `community-plugins` where other Serverless developers can explore pre-written services (e.g. an auth-Service)?

**Comment by flomotlik** [comment]
What would be the extent of this feature? Would it only download and store the specific service in a local directory, should it deploy it as well potentially?

Are we going to deal with updating this service as well? How about building the artefacts for deployment (especially across language)?

Just want to make sure we have a common understanding of what this feature should do.

**Comment by ac360** [comment]
IMO, for now, all it should do is download a zip from Github, and unzip the directory.  Later, we can investigate auto-deploying in this one command, which is an interesting idea.

At the moment, our goal is to get the bare minimum of this feature implemented so that the community can start building services ASAP.  

Also, we're going to learn a lot.  We really have no idea how this is going to go.  Let's get minimal 'download from github' working, then observe what happens, and what people want.

**Comment by pmuens** [comment]
Yep. I understood it in a way that I simply provide a gitUrl and the repo is cloned on my local machine so that I can do smth. like

`serverless install --service git@github.com:serverless/serverless-authenticator.git`

`cd serverless-authenticator`

`serverless deploy`

And have an authentication service up and running. I know one can say "well do a simple git clone" but the idea is that the user does everything with the Serverless CLI and we can extend it later on with some extra features and people are already familiar with that.

(I also like Austens .zip integration. So we might also support both).

After this MVP we can see how we might extend it.

**Comment by flomotlik** [comment]
I'm fine with implementing (mostly cause it won't take a lot of time at the moment) but thinking about it more I don't really think this is going to lead to any proliferation of services being built by users. Its a very thin layer on top of git clone and not something like a service registry that users can explore. 

Without putting very serious effort into making sure more people build services, we have something like a service registry (or a service repo) and we have a lot of partnerships and marketing in place I don't think this feature will make any difference. So as it won't take a lot of time we can implement it, but I'd also like to know what the plan for marketing/evangelism and other activities are that will make sure we have a lot service to choose from.

**Comment by flomotlik** [comment]
@ac360 @worldsoup @DavidWells what would be next steps there on making sure that we get more services by providers in place, especially from marketing/evangelism? I don't think simply implementing this functionality will move the needle a lot without other follow up tasks including marketing/evangelism to really push for more services being built.

If we don't have specific tasks planned there I would push this back a bit until we're going to tackle more of the services ecosystem beyond just the dev side.

**Comment by license2e** [comment]
The issue #1717 can be closed in favor of this one.

**Comment by andymac4182** [comment]
This would be great if as part of installing you could provide answers to questions that would populate items that are specific to your environment. This would mean that a service could define a set of variables that were required and the user could fill them in to allow for a ready to go service. This would be great for something like LambdAuth to allow people to get a good auth workflow working straight away and allow you to customize it once it is ready to go.

**Comment by pmuens** [comment]
Done with the help of the `install` command /cc @flomotlik
