### ISSUE TITLE
Cognito user pool authorizer

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#1949]
Can I set Cognito user pool authorizer for http endpoint? Documentation deals with custom authorizers defined by name
(https://github.com/serverless/serverless/blob/85f4084e6b0fd4a6d763ace8cd0db82817bbc712/lib/plugins/aws/deploy/compile/events/apiGateway/README.md#http-setup-with-custom-authorizer) or arn. The Cognito user pool authorizer does not have lambda function nor arn so I don't know how to proceed.

**Comment by flomotlik** [comment]
You should probably be able to set it through custom resources, by simply adding/overriding the template with everything you need for Cognito user pool? Currently we don't have it implemented in the framework, but you can extend and overwrite the CloudFormation template by adding resources to resources->Resources in the serverless.yml file

**Comment by JakubMatejka** [comment]
Uh, ok, I'll try that. It looks like a lot of custom hacking for someone who hasn't used Cloud Formation yet but this seems like a good opportunity to start, right? ;o) Anyway, if there is some support for Cognito in SLS in future, it will be much appreciated. Thanks.

**Comment by flomotlik** [comment]
Yup more support is definitely planned in the future. One thing I overlooked though is that Cognito isn't supported by CF at the moment I think. At least going through the docs doesn't show anything and I don't remember any recent updates on this.

**Comment by flomotlik** [comment]
Will close this issue for now as we can't do it through CF and will come back to it once CF supports it.

**Comment by johnf** [comment]
It looks like CF does support referring to an existing authorizer. Which means at least you can create it manually and then refer to it. Not optimal but means at least I can use the functionality. Implemented in #2141
