### ISSUE TITLE
Support Stack Policies

### ISSUE THREAD

**Issue by DanielRuskin1** [serverless/serverless#1952]
##### Feature Request:

Support [Stack Policies](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html#protect-stack-resources-protecting) on CloudFormation stacks.  

##### Benefits:

* Allows for safely defining non-transient resources (e.g. an RDS instance).  Without policies, updating resources can trigger deletions (which could lead to loss of data, e.g. RDS data/snapshots).

##### Additional Details:

You can set a policy by passing in a `StackPolicyURL` to the [Create Stack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html) API.

It seems like this should be a fairly simple feature.  I'd be happy to open a PR when I get some time, if you guys think it's worth doing.

**Comment by flomotlik** [comment]
Yup thats definitely an interesting feature and we would accept the PR. Could you post a description of how you would plan to do the implementation in detail? Just want to make sure we all agree on it in the design phase before starting much of the coding.

**Comment by nicka** [comment]
Yes this is definitely needed! Experienced first hand the drama that could happen without a stack policy ☺️

**Comment by DanielRuskin1** [comment]
Thanks @flomotlik.  I'm thinking I'd do this:

1. Update the custom resources yml definition to look like this:

```
stack:
  template:
    Resources:
      $ref: foo/bar.json
  policy: 
    $ref foo/bar.json
```

2. Add a `uploadCloudFormationPolicy` method to the deploy lifecycle, before `uploadCloudFormationTemplate`: https://github.com/serverless/serverless/blob/e13abdc6c04b02f1b36627b0daed5707b5352b75/lib/plugins/aws/deploy/index.js#L26.  This will check if the yml config to see if a stack policy is specified and, if so, upload it to S3.
3. Update `https://github.com/serverless/serverless/blob/e13abdc6c04b02f1b36627b0daed5707b5352b75/lib/plugins/aws/deploy/lib/updateStack.js#L19` to pass in a `StackPolicyURL` when updating the stack with the user-provided resources.  Do not pass in the `StackPolicyURL` when creating the stack, as the user-provided resources will not be present (so the stack policy could be irrelevant).
4. Update `https://github.com/serverless/serverless/blob/e13abdc6c04b02f1b36627b0daed5707b5352b75/lib/plugins/aws/deploy/lib/mergeCustomProviderResources.js` to look at the new `this.serverless.service.stack.template` parameter.

^ Let me know how this looks.  I'm not too familiar with this codebase yet, so definitely possible I missed something here.

**Comment by flomotlik** [comment]
This looks great, the only change that I would do is put `policy` into `provider->policy` instead of updating the custom resources definition. Imho stack policies are a more advanced feature and shouldn't imho be mixed here with the general resources. Other than that though this looks great!

**Comment by DanielRuskin1** [comment]
Sounds good, I'll do that + open a PR in the next few days.

**Comment by DanielRuskin1** [comment]
Was going to start work on this today, but looks like it's been implemented! https://github.com/serverless/serverless/pull/2158
