### ISSUE TITLE
Travis CI builds fail when zipping the service

### ISSUE THREAD

**Issue by wedgybo** [serverless/serverless#1954]
##### Serverless Framework Version: 
1.0.0-beta.2
##### Operating System: 
Linux
##### Expected Behavior:
Deployed stage via travis CI build server
##### Actual Behavior:
Travis kills the build with the following error message

Full build here - https://travis-ci.org/mallzee/serverless-boilerplate-service/builds/154659803

```
Serverless: Zipping service...
Killed
```

![](https://www.dropbox.com/s/ep9tz68ywzdhdrp/Screenshot%202016-08-24%2018.56.14.png?dl=1)

##### Discussion:

This message is typical when a build uses up more than the allowed memory, ~3Gb according to the doc. You can see from the image that amount of memory usage is peaking pretty high! Looking into it there's an open issue about zipping lots of files using the library. https://github.com/Stuk/jszip/issues/227

I've had a quick play at replacing the library with archivejs as I wasn't getting any better results using the JSZip nodestream setup and it's dropped the consumed memory on my build to the following.

![](https://www.dropbox.com/s/m74r3jawi7ilc9c/Screenshot%202016-08-24%2019.17.49.png?dl=1)

I wanted to see if others had come across this problem, as I can't be the only one deploying from travis that has a reasonable sized node_modules folder.

You can see the sample project here https://github.com/mallzee/serverless-boilerplate-service

I think there's another win to be made by replacing node_modules with a version run with npm install --only=production

**Comment by pmuens** [comment]
Good catch @wedgybo thanks for reporting!

This is definitely something we need to look at.

There's a new plugin around the corner which optimizes the service before deploying https://github.com/nfour/serverless-build-plugin Maybe something in that area might also help here.

**Comment by flomotlik** [comment]
@wedgybo just to make sure your assumption is this is due to node_modules having tons of files in there?

**Comment by wedgybo** [comment]
That's my thinking from what I've read about JSZip. It's not the file size that's the issue, just the volume of files. So on my example repo https://github.com/mallzee/serverless-boilerplate-service/blob/master/package.json That still fails to deploy due to the amount of files generated by the dev dependencies it's trying to package up. Which it shouldn't be anyway, but that's another issue.

I have got the memory consumption down a ton by switching to archivejs and you can see it on this branch https://github.com/mallzee/serverless/commits/archivejs-replacing-jszip Once I've confirmed I can get a travis build working for it I'll raise a PR for you guys to have a gander over.

**Comment by pmuens** [comment]
Awesome @wedgybo!
Thanks for investigating. Looking forward to the PR!

**Comment by wedgybo** [comment]
No worries. Happy to help when I get the time as I believe this will solve a lot of things I'm looking to put right with our AWS deployments :)

It would be good to know if the plan to adopt the plugin is happening soon as I've not tested that out soon. But if it's based on JSZip I'd guess it will have the same issue? If it's coming real soon I'll jump onto it.

**Comment by wedgybo** [comment]
So with my branch I get a successful build. Time for that PR

![](https://www.dropbox.com/s/hq3hffo6w1t52ww/Screenshot%202016-08-25%2018.24.04.png?dl=1)

**Comment by pmuens** [comment]
Done with #1961
