### ISSUE TITLE
Custom Stack Tags (for 1.x)

### ISSUE THREAD

**Issue by puug** [serverless/serverless#1956]
##### Feature Request:

Looks like the feature used to exist on 0.5.x, but no longer for 1.x

https://github.com/serverless/serverless/issues/965

**Comment by flomotlik** [comment]
@puug yup that looks like a nice feature. Added a help-wanted-easy label if somebody can pick it up. We won't get to it ourselves anytime soon as we need to get a few other things done first, but if somebody picks it up and proposes an implementation we're open to it.

**Comment by horike37** [comment]
So `${stage}` tag can use in Serverless.yml and custom_resources.json?

**Comment by flomotlik** [comment]
We're currently still working on the details of the variable syntax in #1834

**Comment by WooDzu** [comment]
Would an top-level equivalent of `resourcesStackTags` variable do the job?
If so, I'll be happy to help on this one.

On a similar subject, there is also a stack policy that can be used to prevent delete/replacements to stack resources like databases
```
{
  "Statement" : [
  {
    "Effect" : "Deny",
    "Principal" : "*",
    "Action" : ["Update:Replace", "Update:Delete"],
    "Resource" : "*",
    "Condition" : {
      "StringEquals" : {
        "ResourceType" : ["AWS::RDS::DBInstance"]
      }
    }
  }
}
```
What are you thoughts on supporting this?

**Comment by flomotlik** [comment]
@WooDzu I think this should go into the provider config -> `provider->stackTags` and `provider->stackPolicy`
