### ISSUE TITLE
Local context attributes do not match lambda ENV.

### ISSUE THREAD

**Issue by harakiro** [serverless/serverless#1962]
context.functionName should be a string.

To reproduce create a lambda function that logs typeof context.functionName.

Run it via sls function run
then deploy and run it in AWS.

Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
0.5.6

##### Operating System: 
Mac OSX, likely NA

##### Expected Behavior:
The context object of the locally running function should at least be the same data types as the one in the lambda execution environment.

##### Actual Behavior:
Serverless overloads the context object with its own context, which even makes use of the AWS context attributes (functionName). However, locally IE (sls function run func1) typeOf context.functionName == object, where as it should be a string representing the lambda function name.

**Comment by pmuens** [comment]
Hey @harakiro thanks for reporting this.
Unfortunately we're not supporting Serverless v0.5 anymore as we've moved forward to implement Serverless v1. Transition to the new version should be straight forward (you can read more about it in the [docs](http://docs.serverless.com).

Let us know if you have any additional questions!
