### ISSUE TITLE
Attempting to return context causes circular error.

### ISSUE THREAD

**Issue by harakiro** [serverless/serverless#1963]
My lambda function (for testing) returns the context object as part of the response. This executes fine in the AWS environment. However, when running locally it causes a circular reference error and fails to run.

This could be fixed by adding the following code to the lambda environment simulation code:
var util = require('util');

Then wrap the response in util.inspect() before calling JSON.stringify().

Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
0.5.6
##### Operating System: 
Mac OSX, likely n/a
##### Expected Behavior:
Function to print my context object and return successfully

##### Actual Behavior:
Circular reference error.

**Comment by pmuens** [comment]
Hey @harakiro thanks again for reporting.
We've moved on and are not supporting Serverless v0.5 anymore.

[Here](http://docs.serverless.com) are the docs which should help you to switch to the new Serverless v1.

Let us know if you have questions along the way!
