### ISSUE TITLE
iamRoleArnLambda and authorizationType configuration with v1.0

### ISSUE THREAD

**Issue by parthaMyndbee** [serverless/serverless#1969]
I am just looking similar configuration through yaml

1. How to I say serverless to use a specific role for all / each of my lambda function ? Which I used to do in 0.5 by configuring  s-variables-stage-region.json and the "iamRoleArnLambda": "arn:aws:iam::<account>:role/XYZ" 
2. How do I configure the endpoint to use IAM authorization ? Again using v 0.5 I do that by "authorizationType": "AWS_IAM" in s-function.json.

TIA

**Comment by parthaMyndbee** [comment]
#1772

**Comment by flomotlik** [comment]
At the moment we don't provide support or improvements for 0.5, we're only focusing on V1. #1772 was implemented in #1975 and the feature is now available in master.
