### ISSUE TITLE
deploy fails with unhelpful error message when service name is not a valid CF stack name

### ISSUE THREAD

**Issue by fiducioso-dan** [serverless/serverless#1973]
# This is a Bug Report

## Description

I created a new serverless.yml with `service: my_func`. 

Attempting `serverless deploy`:
```
  Error --------------------------------------------------
 
     ServerlessError: ServerlessError: 1 validation error
     detected: Value 'my_func-dev' at 'stackName' failed
     to satisfy constraint: Member must satisfy regular expression
     pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 ```

The error message is very hard to understand. My problem was fixed by replacing the `_` with `-` but parsing that error message is not a pleasant experience.

This is similar to #1931 but that issue is for the naming of the resources inside the stack. This issue is about the name of the stack itself.

## Additional Data

* ***Serverless Framework Version you're using:***
1.0.0-beta.2
* ***Operating System:***
Ubuntu 16.04, node 4.5.0

**Comment by flomotlik** [comment]
Thanks @fiducioso-dan for reporting. this is definitely a bug and by default we should remove all characters that aren't valid before deploying to CF.

**Comment by flomotlik** [comment]
Maybe we should also add this to the template files for AWS, @fiducioso-dan would that have helped if there was a comment above the name or in the name saying exactly which characters are allowed?

**Comment by danielkoo** [comment]
Hi @flomotlik 
Just a newbie having a look: would lib/plugins/aws/deploy/lib/createStack.js be the best place to make this change? Or somewhere earlier? I am guessing different providers would have different naming conventions, this would be AWS-specific.

**Comment by flomotlik** [comment]
@danielkoo yup we have the getStackName method but its not used in every action yet (create, update, remove, ...). It needs to be refactored so every class is using this central method so we can easily refactor in the future. The info plugin does a nice job there for example.

**Comment by DavidWells** [comment]
I also encountered with bug and had to google it. 

Lets fix this error message
