### ISSUE TITLE
Variables with numeric values cause unexpected results

### ISSUE THREAD

**Issue by seliger** [serverless/serverless#1974]
# This is a BUG REPORT

## Description

I added a variable with a numeric value like so:

`sls variables set -t stage -s prod -k accountid -v 1234567890`

This completed successfully. I then referenced that variable inside my s-resources-cf.json file, something like this:

```
{
  "Resource": [
      "arn:aws:dynamodb:${region}:${accountid}:table/Ratings",
      "arn:aws:dynamodb:${region}:${accountid}:table/Ratings/index/*",
      "arn:aws:dynamodb:${region}:${accountid}:table/UserFeedback",
      "arn:aws:dynamodb:${region}:${accountid}:table/UserFeedback/index/*",
      "arn:aws:dynamodb:${region}:${accountid}:table/UserProfiles",
      "arn:aws:dynamodb:${region}:${accountid}:table/UserProfiles/index/*"
  ]
}
```

The goal being to replace hard coded values for region and account number with variables. Running the diff command as such:

`sls resources diff`

Any line that had the numeric value would be COMPLETELY replaced by the numeric value, instead of the value being replaced in the middle of the line. 

![image](https://cloud.githubusercontent.com/assets/861931/18029577/b785f7c6-6c69-11e6-8fb7-2e16041a93fb.png)

This image demonstrates the unexpected result.

There are no errors or stack traces. Except that later deploys fail because the generated resources manifest is corrupt.

The only way to work around this issue is to manually edit the variables json file and put double quotes around the numeric value, forcing it to be a string. (Had previously thought that adding the quotes on the command line would fix it -- forgot that I had hand edited the file...)

Similar or dependent issues:
* None that I could find

## Additional Data

* ***Serverless Framework Version you're using:*** 0.5.6
* ***Operating System:*** Ubuntu 16.04 x86_64
* ***Stack Trace:*** None
* ***Provider Error messages:*** None

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
