### ISSUE TITLE
Add refactoring and conversion from 0.5.x to 1.0.x to docs

### ISSUE THREAD

**Issue by franz-josef-kaiser** [serverless/serverless#1979]
This is a very short request: Please add some docs or some mapping scheme for people who already have a running 0.5.x (or prior) setup and want to convert to the new version as the change is a _breaking_ and _non backwards compatible_ upgrade.

**Comment by mthenw** [comment]
Hey, 

the doc that we've added recently might be helpful https://github.com/serverless/serverless/blob/master/docs/v0-v1-comparison.md#how-to-upgrade-from-0x-to-1x.
