### ISSUE TITLE
`SLS deploy` needs to check if directory has config file

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#1980]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Serverless hangs and says that stuff is happening when running deploy in the wrong folder.

This was an issue caused by me. =) but should be a UX improvement

![image](https://cloud.githubusercontent.com/assets/532272/18071048/65bbd15a-6e07-11e6-90ea-f48ce539214e.png)

* What did you expect should have happened?

It should warn me that there is no `serverless.yml` file present and fail gracefully and not get stuck on `zipping service...`

## Additional Data

* ***Serverless Framework Version you're using:*** 1.0.0-beta.2

**Comment by danielkoo** [comment]
Hi @DavidWells 
What does one need to reproduce this? If I run this in an empty dir, or if I rename my serverless.yml to e.g. serverless.yml2, I get this:

`$ sls deploy
 
  Type Error ---------------------------------------------
 
     Path must be a string. Received null
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
`

**Comment by flomotlik** [comment]
@DavidWells this should not be happening anymore as we've removed the ability to traverse the file tree up. In the future this feature could lead to exactly these issues if you had a serverless.yml in a parent folder. Closing for now unless you can still reproduce this feature with the latest master.
