### ISSUE TITLE
Custom Authorizer default header should be Authorization instead of Auth

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#1983]
# This is a Bug Report

## Description

The default header for custom authorizers seems to be "Auth": 
https://github.com/serverless/serverless/blob/7715c014fd34fc9b48401231c16ffe6c2467eed3/lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js#L30
https://github.com/serverless/serverless/blob/7715c014fd34fc9b48401231c16ffe6c2467eed3/lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js#L47

I think the default header should be "Authorization" like it is in AWS API Gateway, and in the HTTP protocol in general. When it's called "Authorization", it will be included all kinds of defaults like CORS configurations and CloudFront headers, making life easier.

**Comment by flomotlik** [comment]
Yup that sounds good, added it to the next milestone and a help-wanted-easy label if somebody picks it up for a PR before us.
