### ISSUE TITLE
Plugins: Command nesting breaks existing (incl. core) commands

### ISSUE THREAD

**Issue by oipat** [serverless/serverless#1987]
# Bug Report

## Description

For bug reports:
* Command nesting in plugins breaks existing commands.

The second example and description in https://github.com/serverless/serverless/blob/master/docs/developing-plugins/building-plugins.md#user-content-command gives me the understanding that nesting commands, even the core commands, is possible.

I tried deploying and using the exact plugin that was presented in the example (I only changed deploy to invoke to make it easier to test. With deploy the issue is similar):
```javascript
'use strict';

class MyPlugin {
  constructor() {
    this.commands = {
      invoke: {
        lifecycleEvents: [
          'resources',
          'functions'
        ],
        commands: {
          single: {
            lifecycleEvents: [
              'resources',
              'functions'
            ],
          },
        },
      },
    }
  }
}

module.exports = MyPlugin;
```

I then created a package.json with "test-plugin" as the name and configured it to serverless.yml:
```yml
plugins:
  - test-plugin
```

When the plugin is enabled, I get the following output from sls/serverless command (see the invoke ones):
```
$ sls

Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

create ................... Create new Serverless Service.
deploy ................... Deploy Service.
deploy function .......... Deploys a single function from the service
info ..................... Displays information about the service.
invoke ................... Invokes a deployed function.
logs ..................... Outputs the logs of a deployed function.
invoke ................... undefined
invoke single ............ undefined
remove ................... Remove resources.
tracking ................. Enable or disable usage tracking.
```

So the problem is that the plugin breaks the existing description for invoke command. And the bigger issue is that the 'sls invoke' command cannot be used anymore:

```
$ sls invoke -f getPosts
 
  Serverless Error ---------------------------------------
 
     The command you entered was not found.
     Did you
     spell it correctly?
 
  Stack Trace --------------------------------------------
 
ServerlessError: The command you entered was not found.
     Did you spell it correctly?
    at PluginManager.run (/Users/tapio/.nvm/versions/node/v4.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:100:13)
    at Serverless.run (/Users/tapio/.nvm/versions/node/v4.5.0/lib/node_modules/serverless/lib/Serverless.js:77:33)
    at /Users/tapio/.nvm/versions/node/v4.5.0/lib/node_modules/serverless/bin/serverless:18:50
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

```

When I comment out the 'invoke' object in the plugin code, 'sls invoke' works again.

* What did you expect should have happened?
New command created: 'sls invoke single' while 'sls invoke' would have still been functional. 'sls' command should have not produced additional description for the 'sls invoke' command, only for the core command.
* What was the config you used?
Described in the error description.
* What stacktrace or error message from your provider did you see?
See error description.

Similar or dependent issues:
I started investigating this due to the issue in serverless-mocha-plugin: https://github.com/SC5/serverless-mocha-plugin/issues/28

## Additional Data

* ***Serverless Framework Version you're using:***
1.0.0.beta.2
* ***Operating System:***
OSX 10.11.6
* ***Stack Trace:***
See error description
* ***Provider Error messages:***
N/A

**Comment by dougmoscrop** [comment]
This should be fixed!

**Comment by pmuens** [comment]
Done with #2133 /cc @flomotlik
