### ISSUE TITLE
Default request template breaks with unescaped principalId

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#1991]
# This is a Bug Report
## Description

I just tested that the current 1.0 default template will break if you put JSON in principalId (generated by a custom authorizer), because the template does not escape the string.

In this case the principalId value is `{"id":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx" ... }` (some fields omitted).

```
Endpoint request body after transformations: { "body": {}, "method": "GET", "principalId": "{"id":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx"
Endpoint response body before transformations: {"Type":"User","message":"Could not parse request body into json: Unexpected character ('i' (code 105)): was expecting comma to separate OBJECT entries\n at [Source: [B@116ae07a; line: 5, column: 34]"}
```

I don't know if it's possible to escape strings in API Gateway templates. There's no guarantee what might be in principalId, so this seems pretty problematic.

Similar or dependent issues:
- #1593
## Additional Data
- **_Serverless Framework Version you're using: 1.0-beta.2**_

**Comment by kennu** [comment]
I noticed that there is a new way to pass multiple attributes from custom authorizers to Lambda functions via `$context.authorizer.claims['property-name']`.

http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html#apigateway-enable-cognito-user-pool

Perhaps that will make it unnecessary to use the "json-in-principalId" hack? Has anybody tried it, or does it only work with User Pools?

**Comment by flomotlik** [comment]
@kennu is this still an issue in the latest release? I assume as we didn't change anything here.

**Comment by kennu** [comment]
@flomotlik I have started migrating projects to use the Lambda-proxy default, so this is not particularly important for me at this time. I'm counting on the Lambda-proxy event structure being the standard default baseline in the future.

**Comment by kennu** [comment]
@flomotlik I have started migrating projects to use the Lambda-proxy default, so this is not particularly important for me at this time. I'm counting on the Lambda-proxy event structure being the standard default baseline in the future.

**Comment by flomotlik** [comment]
Then I'm closing for now
