### ISSUE TITLE
Support YAML event input for CLI "serverless invoke"

### ISSUE THREAD

**Issue by gwsii** [serverless/serverless#1994]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved
Allows user to specify a event.yml instead of event.json as test event input.

* If there is additional config how would it look
No additional config. The event.json file is already hard-coded, this would add the event.yml as an alternative.

* Which command should this be running for
Same as before: `sls invoke blah`

Similar or dependent issues:

## Additional Data

* Would like for v1.0
* Windows7

**Comment by gwsii** [comment]
Working on delivering this feature sometime this week.

**Comment by dougmoscrop** [comment]
This seems to already work with --path=foo.{json|yml|yaml}

what actually doesn't work is --data={json}

I think also supporting stdin would be nice, so like

`cat foo.json | serverless invoke -f -` or something.

**Comment by flomotlik** [comment]
yup there is an issue discussing STDIN: #2211 

As this already works I'm closing here.
