### ISSUE TITLE
Create a new template which creates a AWS Node TypeScript project

### ISSUE THREAD

**Issue by StefH** [serverless/serverless#1997]
# This is a Feature Proposal
## Description
- Create a new template **aws-nodets** which will initialize an AWS Node project based on TypeScript 2.x

**Comment by flomotlik** [comment]
Typescript would itself need some additional compile step to run to work on Lambda correct?

**Comment by andymac4182** [comment]
This looks like the perfect use case for https://github.com/serverless/serverless/issues/1938 as there could be a community templates repo with various extended templates. Similar to https://github.com/stoffern/serverless-es6-example

**Comment by StefH** [comment]
yes I know that example project.

I'm currently also creating a typescript based aws-lambda project.
However I run into some small issues like this one: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10956

And I still need to figure out how to add webpack to my project. I'll see if I can create a working github project.

**Comment by StefH** [comment]
First working Serverless AWS Lambda TypeScript project (no webpack yet), can be found at https://github.com/StefH/serverless-aws-lambda-typescript-examples

Please try this and provide feedback.

**Comment by flomotlik** [comment]
Closing this here for now as we won't add it to core.

**Comment by pietrasiak** [comment]
I've created some example with typescript and offline local development support. It's based on `serverless-webpack` and `serverless-offline` - you can check it out here: https://github.com/pietrasiak/serverless-typescript-starter

**Comment by franciscocpg** [comment]
Done in https://github.com/serverless/serverless/pull/4058
