### ISSUE TITLE
Cron job support with Lambda?

### ISSUE THREAD

**Issue by siong1987** [serverless/serverless#2]
https://alestic.com/2015/05/aws-lambda-recurring-schedule/ - this will be cool.

**Comment by pchaganti** [comment]
This would be pretty cool to do with JAWS +1

**Comment by hj1980** [comment]
That's cool! Also, I was chatting with a colleague today about this, and another way might be to use the AWS billing reports hitting a S3 bucket to trigger Lambda..

**Comment by ac360** [comment]
:+1: I will be putting this on the JAWS Road map which will be published this weekend.  Thank you!

**Comment by ac360** [comment]
:+1: @siong1987 I'm aware of the solution you linked to.  Also, I believe AWS is working on this and soon it might be a native feature for lambda (!!!).  Not sure when they are going to release it, but I think we're going to wait until after re:Invent to look into this.

**Comment by binoculars** [comment]
This is a heavily requested feature and has been brought up in the AWS forums: [It would be awesome if we could schedule lambda functions](https://forums.aws.amazon.com/thread.jspa?threadID=172506) and [Scheduled Tasks](https://forums.aws.amazon.com/thread.jspa?threadID=175871)

Another option options is to use the SWF ([see the docs page](http://docs.aws.amazon.com/amazonswf/latest/developerguide/lambda-task.html)). @alestic has the most convenient solution so far IMHO. It's pretty inconvenient to have write Ruby or Java just to get something to go off on a timer. I've thought about IFTTT's [Date and Time](https://ifttt.com/date_and_time) but haven't explored the viability of it yet.

**Comment by siong1987** [comment]
@ac360 awesome!

**Comment by apaatsio** [comment]
AWS Lambda now supports scheduled functions. It supports cron syntax, too.

Announcement: https://aws.amazon.com/blogs/aws/aws-lambda-update-python-vpc-increased-function-duration-scheduling-and-more/
Documentation: http://docs.aws.amazon.com/lambda/latest/dg/getting-started-scheduled-events.html

**Comment by jordanmack** [comment]
Is this issue closed now that Serverless supports events?

**Comment by eahefnawy** [comment]
@jordanmack yep!
