### ISSUE TITLE
Upload lambda function based on stage 

### ISSUE THREAD

**Issue by bhushankumarl** [serverless/serverless#2001]
Need to upload lambda function based on staging in different bucket. 

e.g If stage is 'dev' than lambda function should able to upload to 'serverless-dev', If stage is 'prod' than lambda function should able to upload to 'serverless-prod' based on user requirement.

**Comment by andymac4182** [comment]
serverless currently uploads the service zip file to a bucket that is related to the relevant stage. Are you talking about creating a bucket for the lambda to save files to from the function?

**Comment by flomotlik** [comment]
At the moment we don't plan to add this feature, but there is another bug open discussing this, so I'm going to close here: https://github.com/serverless/serverless/issues/1513
