### ISSUE TITLE
[Feature] Automatic versioning and releasing

### ISSUE THREAD

**Issue by stoffern** [serverless/serverless#2004]
# This is a Feature Proposal
## Description

Better commits described after a correct standard.
No more incomplete or mismatch in NPM - github versioning.
Version documentation is correctly setup by default

Add Commitizen
Add Semantic releasing
## Additional Data

[commitizen](https://github.com/commitizen/cz-cli)
[semantic-release](https://github.com/semantic-release/semantic-release)

**Comment by flomotlik** [comment]
Hi, thanks for sending this in, could you update the issue to follow our template: https://github.com/serverless/serverless/blob/master/.github/ISSUE_TEMPLATE.md

It helps us a lot to better understand the use case and prioritise then.
