### ISSUE TITLE
0.5 - parse error message + provide responseParameter

### ISSUE THREAD

**Issue by rafaljanicki** [serverless/serverless#2006]
Serverless version: 0.5.6

Hi,

In my project, besides regular HTTP codes, I also return errors + body with JSON using the context.fail(JSON.stringify(response)) and following responseTemplate:

~~~~
"responseTemplates": {
      "application/json": "#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))\n{\"message\":\"$errorMessageObj.Message\", \"correlationId\": \"$errorMessageObj.correlationId\"}"
    }
~~~~

However, I'd also like to add a variable to responseParameters as I do this in "regular" responses:

~~~~
"method.response.header.Access-Control-Allow-Origin": "integration.response.body.theVariable"
~~~~

How can I do this as I can't access any variable in body besides the errorMessage?

Best regards,
Rafal

**Comment by flomotlik** [comment]
Hi @rafaljanicki, thanks for reporting this, but at the moment we're not working on 0.5.x at all any more and rewrote the whole system with 1.0. It allows everything you mentioned in your report (now in master, soon to be released).
