### ISSUE TITLE
Keeping last 5 lambda zip files should only be ran on successful deploy

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2011]
# This is a Bug Report
## Description

When a deploy fails past 5 times the bucket has been cleaned up and Cloudformation is unable to rollback. 

For bug reports:
- What went wrong?
  Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
- What did you expect should have happened?
  It should only remove previous artifacts from s3 after a successful deploy

I believe https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/index.js#L51 should be moved below https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/index.js#L57
and https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js#L9 will need to be changed to 5 since its after the code has been uploaded. Would be great if this was customisable as well.
## Additional Data
- **_Serverless Framework Version you're using:**_
  1.0.0-beta2
- **_Operating System:**_
  Windows

**Comment by WooDzu** [comment]
Hi @andymac4182 did you manage to to restore your stack without recreating it?

**Comment by andymac4182** [comment]
Yeah. I manually created the folder and uploaded the zip. @WooDzu

**Comment by WooDzu** [comment]
Nice one! How did you find the folder name as it is not included in the CF events error?

**Comment by andymac4182** [comment]
If you check the CloudFormation template in the UI you can see the location it is looking

**Comment by mthenw** [comment]
Fixed with https://github.com/serverless/serverless/pull/2564
