### ISSUE TITLE
Suggestion : Add greenkeeper bot to this repository to automatically keep dependencies up-to-date

### ISSUE THREAD

**Issue by StefH** [serverless/serverless#2012]
# This is a Feature Proposal
## Description
- Always up-to-date npm dependencies by using automatic process (greenkeeper)

**Info:**
See https://greenkeeper.io/

Usage:
Three simple commands: Open your terminal, and

```
npm install -g greenkeeper
greenkeeper login
```

Your browser will open and ask you to log in to GitHub. Please do that.
Then, inside the repo you want to keep up to date, do

`greenkeeper enable`

and you’re done! Your first greenkeeper PR will arrive shortly!

**Comment by flomotlik** [comment]
Thanks for the proposal, at the moment we don't want to add any additional CI tooling.
