### ISSUE TITLE
Store CF template files in .serverless folder during deployment

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2016]
# This is a Bug Report

## Description

When running `serverless deploy` the CF templates are not stored in the .serverless folder. This means you have to run `serverless deploy --noDeploy` when you want to get the templates. By default the templates should be created in the `.serverless` folder any time you run deploy, be it with our without `--noDeploy`

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***: latest master

**Comment by danielkoo** [comment]
Hi @flomotlik 
I'd like to have a go at this. Do I need to do anything other than start work on my fork?

**Comment by flomotlik** [comment]
Nope thats cool. Should be relatively simple as the functionality works in noDeploy mode already, just want the same files to be created when noDeploy is configured or not. Thanks for jumping on this!

**Comment by danielkoo** [comment]
PR created, please review when you're ready :)

**Comment by danielkoo** [comment]
Do I need to write anything for the 'Write documentation' part?

**Comment by flomotlik** [comment]
@danielkoo one quick comment about adding a sentence to the deploy cli docs. Other than that this looks great, thanks for looking into it!

**Comment by danielkoo** [comment]
OK, comment added - thanks!

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/2138
