### ISSUE TITLE
Path name and similar Variable Names collide in Cloudformation

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2021]
# This is a Bug Report

## Description

When you set up a path and a variable path in the http event the names might clash and one of them gets overwritten:

```
events:
  - http: get users/{variable}
  - http: get users/variable
```

The problem is that naming of the CF resource simply removes {} so the path looks the same when creating the CF resource name. We should change it to `UsersVariableVar` and `UsersVariable` so they are separate.

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***: master
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dougmoscrop** [comment]
I'm pretty sure this has been fixed. However, I added a test against the specific case in my PR: https://github.com/serverless/serverless/pull/2262

**Comment by flomotlik** [comment]
@dougmoscrop yup I've actually fixed this recently: https://github.com/serverless/serverless/pull/2201 :)
