### ISSUE TITLE
Centralise CF resource naming

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2022]
# This is a Feature Request
## Description

At the moment the CF Logical ID names are not created in a centralised utility function, but separately wherever they are added. Basically we have String concatenations all over the Codebase. We have to centralise this in a utility function that simply gets the different parts of the name and then assembles it correctly.

Similar or dependent issues:
- 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by erikerikson** [comment]
I am working this.  I see it as a precursor to allow naming customization.

**Comment by erikerikson** [comment]
It hurts a little, working this

**Comment by flomotlik** [comment]
Yup I can imagine. Thanks for taking it on!

**Comment by erikerikson** [comment]
#2257 should be ready for review.
