### ISSUE TITLE
Refactor method.js file for cleaner code

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2025]
# This is a Feature Proposal
## Description

methods.js (`lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js`) in the APIG Event is way too complicated at this point and needs to be refactored to run in separate functions or even separate modules/files to have cleaner code. This will also make future feature implementations a lot easier

Similar or dependent issues:
- 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by wedgybo** [comment]
I could take a look at this when I'm working on the custom codes PR. Or would you rather it was separate?
