### ISSUE TITLE
DX: Rework color codes and log printing

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2026]
# This is a Feature Proposal
## Description

At the moment color codes used for Serverless output is inconsistent as we're using yellow for normal output and warnings. We should change this to have clear log and warning methods that users can call and we color code it appropriately then.

Similar or dependent issues:
- 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by anreved** [comment]
@flomotlik, I'd be happy to help out on this one.  My first though was to create a new file under `lib/classes` called `Logger.js` ([see this gist](https://gist.github.com/anreved/c73d83a040399ae8bb0ecd74c63fdec9.js)).  This would have methods to both log messages to the console (log, info, debug, warn, error) as well as get styled messages for when you need to combine multiple styles in a single line.

Basically, it delegates to `chalk

A usage example:
```javascript

const logger = require('./Logger');

logger.info('Welcome to Serverless!');
logger.debug('This is a debug message');
logger.warn('This is a warning message');
logger.error('This is an error message');
```

![image](https://cloud.githubusercontent.com/assets/4683137/18283714/92f1609e-7434-11e6-8df2-1e3a6392b636.png)


You could also add additional styles to the end of any log method:

```javascript
logger.info('Welcome to Serverless!', 'bold');
logger.debug('This is a debug message', 'dim');
logger.warn('This is a warning message', 'underline');
logger.error('This is an error message', 'bold.bgWhite');
```

![image](https://cloud.githubusercontent.com/assets/4683137/18283793/00513e5c-7435-11e6-8946-5e780e17b832.png)


Let me know if this is what you had in mind.

**Comment by flomotlik** [comment]
Yeah pretty much this :D. The only change I would do is instead of using 'bold' or 'dim' define constants in the logger for it. A little more cumbersome, but waaaay easier to change in the future.

```
logger.info('Welcome to Serverless!', logger.BOLD);
```

or something along those lines. Maybe instead of specifics like BOLD we set something like logger.EMPHASIS so its less descriptive, but yeah whatever we can figure this out in the future.

Also makes log levels relatively easy in the future. Great job, thanks for jumping on it so quickly.

**Comment by mthenw** [comment]
# `serverless deploy`

Currently:

![deploy_now](https://cloud.githubusercontent.com/assets/455261/19263365/44013382-8f9c-11e6-8d2c-268da98f37e2.png)

IMO:
- `Serverless:` prefix is not needed 
- `...` is helpful only if it's animated and indicate long operations
- we should use standard color for default output logs
- I don't find `Service information` helpful. For sure it's helpful in case of APIG and maybe for outputting functions' ARNs. 

Proposition
- default output (`--log-level info`)

![deploy_new](https://cloud.githubusercontent.com/assets/455261/19263931/0159447c-8f9f-11e6-8a46-6e878de0de99.png)

- `--log-level debug`

![deploy_debug](https://cloud.githubusercontent.com/assets/455261/19263572/4079a842-8f9d-11e6-932c-8242f569b9ea.png)

@flomotlik @eahefnawy @pmuens @rowanu thoughts?

**Comment by mthenw** [comment]
# Errors

- current

![error_now](https://cloud.githubusercontent.com/assets/455261/19266660/e04dbaa4-8faa-11e6-9754-863c33d3a870.png)

IMO:

- error should be red
- it should be printed without any headers
- info about support concise

## Proposition

![error_new](https://cloud.githubusercontent.com/assets/455261/19266695/0e982674-8fab-11e6-86ce-3a26a995dc91.png)

**Comment by flomotlik** [comment]
>Serverless: prefix is not needed

I tend to agree there.

>`--log-level debug`

@mthenw the CF event output should not be part of  because its not debugging information, but verbose output. Slightly different thing, but having to set the debug log level for getting the CF event output would mean you get to see a lot of other stuff as well.

>... is helpful only if it's animated and indicate long operations

I disagree there. We need to give users some feedback because without feedback they might thing something got stuck, when it only takes a while. We definitely need to keep some visual feedback there.

>we should use standard color for default output logs

That makes sense. I'd like to see it once just to know exactly how it looks and also to think about how this would potentially help with branding, because we need to make sure that branding is still strong in that output imho.

>I don't find Service information helpful. For sure it's helpful in case of APIG and maybe for outputting functions' ARNs.

The service info definitely helps especially people who just start using Serverless. I don't think we should remove it, but we need to make sure going forward that it doesn't get too long.

**Comment by mthenw** [comment]
> I disagree there. We need to give users some feedback because without feedback they might thing something got stuck, when it only takes a while. We definitely need to keep some visual feedback there.

Right now those dots are showing progress only during "Updating Stack" in every other case they are just appended.

# Proposition no. 2

- removed `endpoint` field if no endpoint is deployed 
- remove service name because it might be obvious

![error_new](https://cloud.githubusercontent.com/assets/455261/19272164/c831f49a-8fc7-11e6-9066-1a7a06c28714.png)

**Comment by rowanu** [comment]
* Definitely get rid of `Serverless` on each line - I've just run a Serverless command, so it's reasonable to expect it will be giving me output. Anything to bring line length down.
* I would expect the service info to be shown after an `sls info` command, but not after an `sls deploy` - it seems strange to mix structured log lines with unstructured text, and I've had issues with tools doing it in the past when using them with automated build/deployment processes.

**Comment by flomotlik** [comment]
>Right now those dots are showing progress only during "Updating Stack" in every other case they are just appended.

Aaaah ok. Not that big of a deal in create because that is fast, but should probably be changed at some point in create as well.

> remove service name because it might be obvious
>I would expect the service info to be shown after an sls info command, but not after an sls deploy - it seems strange to mix structured log lines with unstructured text, and I've had issues with tools doing it in the past when using them with automated build/deployment processes.

I think having the name there and general info, while a little bit more info, just makes it clear to users what gets deployed. While its less important for more experienced users having this information helps beginners imho because it makes it clear what has happened as part of the deployment and you have a simple way to check things after deployment without having to run a separate command.

@rowanu would be interesting which issues you ran into there.

> Definitely get rid of Serverless on each line - I've just run a Serverless command, so it's reasonable to expect it will be giving me output. Anything to bring line length down

I think that makes sense, but would like to get @ac360 opinion as he added those in the past and to understand the full reason behind it.

**Comment by rowanu** [comment]
> @rowanu would be interesting which issues you ran into there.

If I'm parsing up my build output and pushing it to a centralised logging platform (e.g. CW Logs, ELK, etc) then mixing structured/unstructured output is a pain. I like it when my commands produce consistent, focused output and I can chain commands together to get the exact output I want (i.e. Unix philosophy).

Totally agree that it's a more advanced use-case. I want logging for debug purposes - what went wrong and where. This is a similar but distinct use-case from verbose output - so beginners know what just happened/what the framework just did for them. Not sure what the solution is 🙃

**Comment by flomotlik** [comment]
>If I'm parsing up my build output and pushing it to a centralised logging platform (e.g. CW Logs, ELK, etc) then mixing structured/unstructured output is a pain. I like it when my commands produce consistent, focused output and I can chain commands together to get the exact output I want (i.e. Unix philosophy).

Would be interesting to get more specific use cases you have in mind there so we can see how we support them.

> Totally agree that it's a more advanced use-case. I want logging for debug purposes - what went wrong and where. This is a similar but distinct use-case from verbose output - so beginners know what just happened/what the framework just did for them

Agreed the option of proper machine readable log output would definitely be interesting, but it won't become the default. Default output will at least from my current perspective always be focused on human readers (and to some degree human readers in CI systems). This will help many users with onboarding and make Serverless a lot more approachable. Thats one of the areas where a tradeoff goes more in the beginner direction (many other areas we're tending more towards advanced users)

**Comment by pmuens** [comment]
Closing this for now since the current color schema won't be changed in the near future.
