### ISSUE TITLE
How to use verbose deploy?

### ISSUE THREAD

**Issue by chenleo** [serverless/serverless#2031]
The -v or --verbose seems give the same output message, is it the right way to use as:

```
sls deploy  -v
```

or

```
sls deploy --verbose
```

**Comment by rowanu** [comment]
These are both the same command - just with long or short arguments. See the output of `sls deploy -h`.

**Comment by flomotlik** [comment]
yup both should work, though they are still not released yet, releasing right now

**Comment by pameck** [comment]
Is this available in 1.0.2 ? It doesn't seem to have any effect if I add `-v` or `--verbose` when  running `sls deploy`

**Comment by buggy** [comment]
@pameck Can you upgrade to 1.0.3 (the latest version)? Both `sls deploy -v` and `sls deploy --verbose` work for that version.

**Comment by brianjd** [comment]
Currently experiencing the same with 1.7.0.

**Comment by pmuens** [comment]
@brianjd So `serverless --verbose` does not work in v1.7.0?

**Comment by pmuens** [comment]
Just tested it and it works on my machine... @brianjd could you open up a new issue with steps to reproduce if it still persists?

Thanks!

**Comment by brianjd** [comment]
Sorry, it works.  I was trying to debug a really long service zip upload (I actually thought serverless was hanging).  I started to see output from the CloudFormation stage when the upload unexpectedly completed.

**Comment by pmuens** [comment]
Great! Thanks for the update @brianjd 👍
