### ISSUE TITLE
Is there a way to change the deployment limits?

### ISSUE THREAD

**Issue by chenleo** [serverless/serverless#2032]
According to the official document:

http://docs.aws.amazon.com/lambda/latest/dg/limits.html

Lambda function deployment package size is 50MB

and

Size of code/dependencies that you can zip into a deployment package is 250MB

Is there a way to change or increase the default size in serverless.yml ?

**Comment by rowanu** [comment]
Nope, as mentioned in the link you included:

> Functions that exceed any of the limits listed in the previous limits tables will fail with an exceeded limits exception. These limits are fixed and cannot be changed at this time.
