### ISSUE TITLE
serverless deploy bug - Member must satisfy regular expression pattern

### ISSUE THREAD

**Issue by JeevanThandi** [serverless/serverless#2036]
serverless deploy shows this error:  
Error --------------------------------------------------

```
 ServerlessError: ServerlessError: 1 validation error
 detected: Value 'serverlessTest.-dev' at 'stackName'
 failed to satisfy constraint: Member must satisfy regular
 expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*

 For debugging logs, run again after setting SLS_DEBUG env var.
```

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

```
 Please report this error. We think it might be a bug.
```

**Comment by mthenw** [comment]
@JeevanThandi is it still and issue for you? What versions are you running? Could you paste your `serverless.yml`?

**Comment by mthenw** [comment]
Closing as it's probably no longer an issue. @JeevanThandi just let me know and I will reopen it.

**Comment by RafalWilinski** [comment]
I've just also encountered this issue:
```
Serverless: Creating Stack…

  Serverless Error ---------------------------------------

     1 validation error detected: Value null at 'tags.1.member.value'
     failed to satisfy constraint: Member must not be null
```

My serverless.yml: https://github.com/netguru/Octoguru/blob/master/master/serverless.yml

**Comment by flomotlik** [comment]
@RafalWilinski when running with `SERVERLESS_DEBUG=true` set in the environment what is the stacktrace?
