### ISSUE TITLE
Question : is it possible to run a local function wihout any valid AWS credentials?

### ISSUE THREAD

**Issue by StefH** [serverless/serverless#2042]
# This is a Question

## Description

When just using dummy values for AWS Access Key ID and AWS Secret Access Key, I cannot execute the function just local ?
```bash
Serverless Error ---------------------------------------

     The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

Is there a way to fake or generate these credentials for testing purpose?

## Additional Data

* ***Serverless Framework : 1.0rc1***
* ***Operating System : windows 10***

**Comment by rowanu** [comment]
Nope, `serverless invoke` is only remote execution only (for now). The [serverless-offline](https://github.com/dherault/serverless-offline) plugin will do what you want. Make sure to use the [serverless_v1 branch](https://github.com/dherault/serverless-offline/tree/serverless_v1).

**Comment by StefH** [comment]
Thanks for this response.
For this moment, I'll use the simpler https://www.npmjs.com/package/run-local-lambda for running locally.

**Comment by rowanu** [comment]
Good to know - been meaning to check that out as well.

**Comment by StefH** [comment]
Also this one works fine:
https://github.com/Max-Kolodezniy/aws-lambda-local
