### ISSUE TITLE
Request to add changelog

### ISSUE THREAD

**Issue by orthodoc** [serverless/serverless#2051]
## This is a Proposal 
(Affecting the contributing devs and otherwise!)
Include a `Changelog.md` and link it to every release to intimate the changes and features introduced with every release.

## Description
With rapid development, several features are being introduced in serverless with each release. Often, some of these changes are **`Breaking Changes`** that are incompatible or make previous versions unusable of ineffective. It is very difficult for a developer to keep track of these changes and has to resort to asking questions at the forum or at gitter.

Suggest to use [commitizen](https://github.com/commitizen/cz-cli) and [conventional-changelog](https://github.com/commitizen/cz-conventional-changelog). These two packages will aid in structuring commit messages and generate a `Changelog` based on these messages.

The latter can be modified to suit serverless needs.

Understand that no formal 'github releases' have happened, though tagging and npm packages have been released. Also notice that release earlier to v0.5 had release notes, they are missing for the more recent ones. Think that release notes are most useful for incremental changes as they are happening right now.

**Comment by flomotlik** [comment]
Thanks @orthodoc for bringing this up. Proper Changelogs will definitely be part of future releases after V1. Basically the blogposts we launch are Changelogs at this point, but after V1 we'll introduce them!

Thanks for mentioning those tools, will definitely look into them to set up this process. Very helpful!

**Comment by mthenw** [comment]
Closing as changelog is in place https://github.com/serverless/serverless/blob/master/CHANGELOG.md.
