### ISSUE TITLE
Discussion: Adding Redundancy/High Availability to AWS Lambda / Serverless

### ISSUE THREAD

**Issue by j0rd** [serverless/serverless#2069]
While I understand this is not related to serverless, I figured I'd ask here.

I've created a Shopify CarrierService using serverless v0.5. Essentially what that is something that calculates shipping costs for orders. I use this on multiple stores and it's been great.

Problem is AWS Lambda occasionally dies for couple hours at a time. When this happens, my customers are not able to receive shipping costs, and thus can not finish their orders. When this happens I lose thousands of dollars and so do others using my service for their stores.

With that said and the larger question for people using serverless is how could one build in redundancy / high availability when using AWS Lambda.

Just figured I'd toss this over to the community to gather suggestions.

**Comment by flomotlik** [comment]
@j0rd this discussion topic would be better suited for our forum at http://forum.serverless.com . We want to make sure that our issue tracking is really only for bugs or specific feature requests and want to move general discussion into the forum. Would be great if you could open that up there and then link back to it from here so people can find the thread in the future.
