### ISSUE TITLE
self: referencing doesn't work in external files

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2076]
# This is a Bug Report / Feature Proposal

## Description

For bug reports:
* What went wrong? Referencing a self variable inside of an external file returns `undefined`
* What did you expect should have happened? Load the value from the current external file
* What was the config you used?

### serverless.vars.yml
```
testingVariableSyntax: dev
currentStage: ${self:testingVariableSyntax}
```
### serverless.yml
```
custom: ${file(./serverless.vars.yml)}
```

* What stacktrace or error message from your provider did you see?
Variables were throwing as undefined

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

### serverless.vars.yml - working
```
testingVariableSyntax: dev
currentStage: ${self:custom.testingVariableSyntax}
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: Master
* ***Operating System***: Windows 10
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by eahefnawy** [comment]
@andymac4182 `self` was never meant to represent any current file, it just represents the `serverless.yml` file. This way you can access the Service config **from any file**.

So this is by design :)

**Comment by andymac4182** [comment]
@eahefnawy Might be better to name it something else then. To me `self` is the file I am currently working on. Should there be a way to access variables from the current file?

**Comment by flomotlik** [comment]
@andymac4182 you can load it into the custom field:

```
custom:
  fileconfig: ${file(my-custom-file)}
  currentStage: ${self:custom.fileconfig.testingVariableSyntax}
```

**Comment by andymac4182** [comment]
@flomotlik You just demonstrated the issue I ran into. The file being loaded doesn't know where it is going to be in the `serverless.yml` tree so you can't reference other variables in the file being loaded. I have added `custom.` to the start of all my references and that solved the problem but if I move it to another part of the tree then they all will break.

**Comment by flomotlik** [comment]
Sorry I wasn't clear enough in my example. The example itself is part of a full serverless.yml. Basically any variable reference of self always has to start at the root of the serverless.yml so its always an absolute, not a relative path that needs to be set up.

And I do think thats a feature, not a bug because we want to have one configuration file for your service. While for convenience and overview its possible to move specific parts of the config file to other files, it is still being treated as one large file.

We should probably add this to the documentation to make it clearer.

**Comment by andymac4182** [comment]
Thanks. I will plan around that when splitting areas into their own files.
