### ISSUE TITLE
respect AWS_DEFAULT_REGION env vars

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2078]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

It's a env var used by aws cli, IMHO it's worth to support it if `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are already supported.

**Comment by flomotlik** [comment]
Opened #2151 to fix region handling in general, closing here.
