### ISSUE TITLE
Do not load plulgins that do not match provider?

### ISSUE THREAD

**Issue by dougmoscrop** [serverless/serverless#2084]
# This is a (Feature Proposal)

## Description

I was wondering if it would make more sense to perform [this check](https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L92) while loading plugins, and simply do not load a plugin instead of skipping its hooks?

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1
* ***Operating System***: OS X 10.11.6

**Comment by flomotlik** [comment]
Yup agreed. Basically loading the plugin config and rejecting it right away in case the provider doesn't match? Or do you have another idea how to implement it?

**Comment by dougmoscrop** [comment]
Yeah... I refactored the PluginManager code to support and fix the command nesting stuff, and I'll call this out when I open the PR too, so you can see what I was thinking.

**Comment by dougmoscrop** [comment]
This is implemented!
