### ISSUE TITLE
Node modules can't be loaded from the AWS Lambda zip code deployed

### ISSUE THREAD

**Issue by marjanSterjev** [serverless/serverless#2086]
Hi,
I’m facing a problem with the Serverless zip created. The node modules included therein can’t be resolved.

Environment:
------------------------------------
Serverless version: 1.0.0-beta.2
OS: Windows 10

Description:
------------------------------------
In the root service folder I’m installing node module. For example:

npm install async --save

In the Node.js handler file I’m loading the installed module with:

var async = require(‘async’);

Let’s install the service after that with:

serverless deploy

The Lambda function execution (Test from AWS Console for example) fails with an error that the module can’t be loaded.

When I look at the zip archive created, I can see that all folders (node_modules for example) do not have any attributes (D for example). All files in the zip has ‘rw’ attributes set. Grunt AWS Lambda plugin for example produces zip file where all folders has ‘D’ attribute set, the files have ‘rwx’ attributes set on them. If I manually unzip and zip after that (with 7Zip for example), the zip can be successfully manually deployed. 

It seems the problem is with the zip file.

**Comment by andymac4182** [comment]
Have you tried the latest rc1?

**Comment by marjanSterjev** [comment]
Hi, I've just tried the rc1. It seems the packaging issue is resolved (was it an issue?).

However, I'm seeing more problems in this release like:

1. Checking stack create progress never ends
2. Checking stack update progress never ends
3. External resource file (Cloud Formation JSON) can't resolve references to functions defined in serverless.yml. This was working in the beta2 release.

**Comment by flomotlik** [comment]
@marjanSterjev yup that packaging issue was resolved recently.

> Checking stack create progress never ends
Checking stack update progress never ends

Can you run with `serverless deploy -v` and post the output.

>External resource file (Cloud Formation JSON) can't resolve references to functions defined in serverless.yml. This was working in the beta2 release.

Can you post the config you used to reference that external file and how exactly you want to reference the function?

**Comment by marjanSterjev** [comment]
@flomotlik 
The serverless deploy command trace:

```
serverless deploy -v
Serverless: Creating Stack...
Serverless: Checking Stack create progress...

  Serverless Error ---------------------------------------

     getaddrinfo ENOENT cloudformation.us-east-1.amazonaws.com:443

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

```

The Lambda function object is referenced the following way:

```
"CreateObjectLambdaDevAlias" : {
    "Type" : "AWS::Lambda::Alias",
    "DependsOn" : "CreateObjectLambda",
    "Properties" : {
        "FunctionName" : { "Ref" : "CreateObjectLambda" },
        "FunctionVersion" : "$LATEST",
        "Name" : "Dev"
    }
}
```

The function handler in serverless.yml is defined with:

```
functions:
  CreateObjectLambda:
    handler: handler.createObject
```

**Comment by flomotlik** [comment]
> getaddrinfo ENOENT cloudformation.us-east-1.amazonaws.com:443

This is a Network issue where it can't correctly talk to the AWS API. Are there issues in your network where you can't talk to Cloudformation, or the 443 port is blocked?

As this does not seem to be a specific bug in Serverless directly I'm going to close this issue. If that problem still persists can you open in https://forum.serverless.com as we try to collect all user questions that aren't bugs there.

**Comment by marjanSterjev** [comment]
@flomotlik 
It seems the network was not the real reason. That was some temporary error.
The real issue is in the file **monitorStack.js** and the line therein:

`const monitoredSince = new Date();`

My computer clock was 2 minutes ahead. Under those circumstances the variable eventInRange:

`const eventInRange = (monitoredSince < event.Timestamp);`

was always false, producing that way an infinite check loop.

The monitor was working in beta2, so probably this logic changed in the meantime. Maybe you should not refer to the local computer time, just compare the event timestamps received.

**Comment by flomotlik** [comment]
@marjanSterjev Interesting, thats definitely a bug. The monitor behaviour did indeed change recently. Marking as a bug to make sure we're tackling this in the future.

**Comment by flomotlik** [comment]
At the moment as the timing didn't come up regularly in other issues I don't think we'll resolve this anytime soon, so closing here. We might fix that at some point in the future.
