### ISSUE TITLE
BUG: http event validator fails

### ISSUE THREAD

**Issue by eL0ck** [serverless/serverless#2089]
# Bug Report
## Description
- What went wrong?
  Incorrect http event configuration in `serverless.yml` can pass without error or return an unintended error.
- What did you expect should have happened?
  Errors thrown with helpful message
#### Config

```
functions:
  ping:
    handler: light_functs/handlers.ping
    events:
      - http:
          path: ping
#         method: get
```
#### Stacktrace

```
$ sls deploy -n
Serverless: Packaging service...

  Type Error ---------------------------------------------

     Cannot read property 'toLowerCase' of undefined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/minmac/Code/serverless-fork/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:16:39
    at Array.forEach (native)
    at /Users/minmac/Code/serverless-fork/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:10:29
    at /Users/minmac/Code/serverless-fork/node_modules/lodash/lodash.js:4738:15
    at baseForOwn (/Users/minmac/Code/serverless-fork/node_modules/lodash/lodash.js:2879:24)
    at /Users/minmac/Code/serverless-fork/node_modules/lodash/lodash.js:4707:18
    at Function.forEach (/Users/minmac/Code/serverless-fork/node_modules/lodash/lodash.js:9011:14)
    at AwsCompileApigEvents.validate (/Users/minmac/Code/serverless-fork/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:9:7)
    at AwsCompileApigEvents.tryCatcher (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromiseCtx (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/promise.js:603:10)
    at Async._drainQueue (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/minmac/Code/serverless-fork/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.
```

Code at `lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:35` looks to be written to handle it but errors at line `16`
#### Config

```
functions:
  ping:
    handler: light_functs/handlers.ping
    events:
      - http:
#          path: ping
#         method: get
```
#### Output

```
$ sls deploy -n
Serverless: Packaging service...
Serverless: Did not deploy due to --noDeploy
```

Deploys without any event. Seems inconsistent given attempts to catch incomplete http event config in `validate.js`

Feature proposals:
- Fix and return insightful errors
## Additional Data
- **_Serverless Framework Version you're using**_:  master f3e288be2e52c5df7bf828c54c54ebeeab82cb3e
- **_Operating System**_: OS X 10.11.16

**Comment by josh9254** [comment]
@eL0ck I have the same problem, could you help me please? Because when i used your modifications, appears 
-- error Empty http event in function --

**Comment by eL0ck** [comment]
@josh9254 

- What do you get with the published version (`1.0.0-rc.1`) ?
- Post your `serverless.yml`

**Comment by josh9254** [comment]
I use version 1.0.0-rc.1

-- my serverless.yml --

service: kboard-interaction # NOTE: update this with your service name

provider:
  name: aws # Set the provider you want to use, in this case AWS
  runtime: python2.7 # Runtime used for all functions in this provider
  vpc:
      securityGoupIds:
        - security_group_ids
      subnetIds:
        - subnet_ids

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            
# you can overwrite defaults here
defaults: 
  stage: dev # Set the default stage used. Default is dev
  region: us-west-2 # Overwrite the default region used. Default is us-east-1
# you can add packaging information here
environment: {
      "SERVERLESS_PROJECT": "${project}",
      "SERVERLESS_STAGE": "${stage}",
      "SERVERLESS_REGION": "${region}",
      "MONGO_HOST": "${mongo_host}",
      "MONGO_PORT": "${mongo_port}",
      "MONGO_DB": "${mongo_db}",
      "REDIS_HOST": "${redis_host}",
      "REDIS_PORT": "${redis_port}",
      "REDIS_PASSWORD": "${redis_password}",
      "PUSHER_APP_ID": "${pusher_app_id}",
      "PUSHER_KEY": "${pusher_key}",
      "PUSHER_SECRET": "${pusher_secret}",
      "PUSHER_CHANNEL": "${pusher_channel}"
    }

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  createrange:
    handler: api.create_range.handler.handler
    description: SLS Function for create range for conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: create_range
          method: post
      - sns: 
          topicName: "${env:sns_topic_name_create_range}"
          displayName: KaBoard
  finishrange:
    handler: api.finish_range.handler.handler
    description: SLS Function to finish range in conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: finish_range
          method: post
  getstatus:
    handler: api.get_status.handler.handler
    description: SLS Function for get status from conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: "{interaction_id}/status"
          method: get
  interactionoff:
    handler: api.interaction_off.handler.handler
    description: SLS Function to turn off a conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: interaction_off
          method: post
  interactionupdate:
    handler: api.interaction_update.handler.handler
    description: SLS Function for update the interaction info
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: interaction_update
          metod: post
  prizeliberate:
    handler: api.prize_liberate.handler.handler
    description: SLS Function for liberate prize in conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_create_range}" 
          displayName: KaBoard
      - sns: 
          topicName: "${env:sns_arn_winner_tweet}"
          displayName: KaBoard
  prizeupdate:
    handler: api.prize_update.handler.handler
    description: SLS Function for update the prize info
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events:
      - http:
          path: prize_update
          method: post
  reassignwinner: 
    handler: api.reassign_winner.handler.handler
    description: SLS Function for reassign a winner to a prize
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - http:
          path: reassign_winner
          method: post
  filtertweets: 
    handler: worker.filter_tweets.handler.handler
    description: SLS Lambda to filter tweet's to conquest active
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
  publishtweet:
    handler: worker.publish_tweet.handler.handler
    description: SLS Lambda for publish tweet to winner
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_winner_tweet}" 
          displayName: KaBoard
  savewinner:
    handler: worker.save_winner.handler.handler
    description: SLS Lambda for save winner in MongoDB and notify the client
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_winner_tweet}"
          displayName: KaBoard
  updateprogress:
    handler: worker.update_progress.handler.handler
    description: SLS Lambda to update progress of active conquest
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_partaker_tweet}"
          displayName: KaBoard
  writetweets:
    handler: worker.write_tweets.handler.handler
    description: SLS Lambda function for create list of tweets"
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns:
          topicName: "${env:sns_topic_name_partaker_tweet}"
          displayName: KaBoard

**Comment by josh9254** [comment]
@eL0ck 

I use version 1.0.0-rc.1

-- my serverless.yml --

service: kboard-interaction # NOTE: update this with your service name

provider:
  name: aws # Set the provider you want to use, in this case AWS
  runtime: python2.7 # Runtime used for all functions in this provider
  vpc:
      securityGoupIds:
        - security_group_ids
      subnetIds:
        - subnet_ids

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            
# you can overwrite defaults here
defaults: 
  stage: dev # Set the default stage used. Default is dev
  region: us-west-2 # Overwrite the default region used. Default is us-east-1
# you can add packaging information here
environment: {
      "SERVERLESS_PROJECT": "${project}",
      "SERVERLESS_STAGE": "${stage}",
      "SERVERLESS_REGION": "${region}",
      "MONGO_HOST": "${mongo_host}",
      "MONGO_PORT": "${mongo_port}",
      "MONGO_DB": "${mongo_db}",
      "REDIS_HOST": "${redis_host}",
      "REDIS_PORT": "${redis_port}",
      "REDIS_PASSWORD": "${redis_password}",
      "PUSHER_APP_ID": "${pusher_app_id}",
      "PUSHER_KEY": "${pusher_key}",
      "PUSHER_SECRET": "${pusher_secret}",
      "PUSHER_CHANNEL": "${pusher_channel}"
    }

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  createrange:
    handler: api.create_range.handler.handler
    description: SLS Function for create range for conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: create_range
          method: post
      - sns: 
          topicName: "${env:sns_topic_name_create_range}"
          displayName: KaBoard
  finishrange:
    handler: api.finish_range.handler.handler
    description: SLS Function to finish range in conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: finish_range
          method: post
  getstatus:
    handler: api.get_status.handler.handler
    description: SLS Function for get status from conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: "{interaction_id}/status"
          method: get
  interactionoff:
    handler: api.interaction_off.handler.handler
    description: SLS Function to turn off a conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: interaction_off
          method: post
  interactionupdate:
    handler: api.interaction_update.handler.handler
    description: SLS Function for update the interaction info
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events: 
      - http:
          path: interaction_update
          metod: post
  prizeliberate:
    handler: api.prize_liberate.handler.handler
    description: SLS Function for liberate prize in conquest
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_create_range}" 
          displayName: KaBoard
      - sns: 
          topicName: "${env:sns_arn_winner_tweet}"
          displayName: KaBoard
  prizeupdate:
    handler: api.prize_update.handler.handler
    description: SLS Function for update the prize info
    memorySize: 1024 # Optional, default is 1024
    timeout: 6 # Optional, default is 6
    events:
      - http:
          path: prize_update
          method: post
  reassignwinner: 
    handler: api.reassign_winner.handler.handler
    description: SLS Function for reassign a winner to a prize
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - http:
          path: reassign_winner
          method: post
  filtertweets: 
    handler: worker.filter_tweets.handler.handler
    description: SLS Lambda to filter tweet's to conquest active
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
  publishtweet:
    handler: worker.publish_tweet.handler.handler
    description: SLS Lambda for publish tweet to winner
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_winner_tweet}" 
          displayName: KaBoard
  savewinner:
    handler: worker.save_winner.handler.handler
    description: SLS Lambda for save winner in MongoDB and notify the client
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_winner_tweet}"
          displayName: KaBoard
  updateprogress:
    handler: worker.update_progress.handler.handler
    description: SLS Lambda to update progress of active conquest
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns: 
          topicName: "${env:sns_topic_name_partaker_tweet}"
          displayName: KaBoard
  writetweets:
    handler: worker.write_tweets.handler.handler
    description: SLS Lambda function for create list of tweets"
    memorySize: 1024 # Optional, default is 1024
    timeout:  6 # Optional, default is 6
    events:
      - sns:
          topicName: "${env:sns_topic_name_partaker_tweet}"
          displayName: KaBoard

**Comment by eL0ck** [comment]
I mean the problem is almost certainly your indentation.  YAML is all about indentation.

e.g 

```
events:
  - http:
    path: reassign_winner
    method: post
```
is not equal to:
```
events:
  - http:
      path: reassign_winner
      method: post
```

Maybe next time use code tags.

**Comment by josh9254** [comment]
ok, let me see!
