### ISSUE TITLE
looking for Python rockstar

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#209]
With the [announcement](https://aws.amazon.com/blogs/aws/aws-lambda-update-python-vpc-increased-function-duration-scheduling-and-more/) of Python 2.7 support for AWS Lambda, we are looking for a python rockstar to code up the initial Python implementation in the JAWS framework.

Anyone willing to help out here or know someone who would be a good candidate? FWIW we already got a JAVA guy.

@shortjared @dekz @Nopik @boushley @joostfarla know anyone?

**Comment by eahefnawy** [comment]
I'm a little offended you didn't mention me :P ... I'm a full time Pythonist at [Yellow](http://yellowpay.co) and I'm willing to dig into this.

Perfect timing btw! I'm currently browsing the repo, sniffing for some work to do ;)

**Comment by doapp-ryanp** [comment]
Sry @eahefnawy I just took the [top 4](https://github.com/jaws-framework/JAWS/graphs/contributors) contributors... didn't intentionally leave you out :)

We will be in touch soon!

**Comment by eahefnawy** [comment]
haha yeah I know. Just kidding :)

Awesome, I'll be waiting.

**Comment by shortjared** [comment]
@eahefnawy I'm happy to support on this one if you are interested. Our team is mostly Pythonist, so we'll be making heavy use of Python Lambda.

**Comment by eahefnawy** [comment]
Perfect! Let's do it! the more the merrier!

**Comment by Nopik** [comment]
I'm pythonist myself, though the current project I'm using Jaws is in node.js, so thats my primary focus now, too. Yet, I'm available for short tasks, like code review, architecture discussions, maybe some hotfixing etc.

**Comment by sixlettervariables** [comment]
If/when #230 lands the initial work on this is pretty easy (mustache for the handler, zipping the source directory).

**Comment by ac360** [comment]
Thanks guys.  We'll reach out to you in about a week to get the ball rolling.

**Comment by DoWhileGeek** [comment]
Any progress on this? Im super excited about this feature.

**Comment by doapp-ryanp** [comment]
Sorry - the plugin architecture has taken a bit longer than expected. Getting close - prob another week or so. Once this next version of Jaws is released, we will be reaching out for help.

**Comment by kristianperkins** [comment]
Is this still on the cards?  I'm interested in a framework for managing python lambdas but it seems this and #230 are on the backburner atm.

**Comment by c-knowles** [comment]
I think this enhancement is done since the python 2.7 runtime has been supported since [0.2.1](https://github.com/serverless/serverless/releases/tag/v0.2.1). Check [the docs](http://docs.serverless.com/docs/backstory) for more details.

**Comment by kristianperkins** [comment]
Oh cool I totally missed that.  I expected it to have been in the README if it was implemented.

**Comment by flomotlik** [comment]
@kristianperkins yup we're updating our docs and README to include this properly in the future.
