### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Bilal-S** [serverless/serverless#2092]
Path
serverless/docs/01-guide/02-creating-services.md
refers to serverles.yml on this line:

Line 32
Each *Serverless service* configuration is managed in the [`serverless.yml`](./serverless-yml.md) file. The main responsibilities of this file are:

There is no: serverless.yml documentation at the moment it results in 404

**Comment by helloniklas** [comment]
All doc links seem broken for me, goes to 404, https://github.com/serverless/serverless/tree/master/01-guide

**Comment by medampudi** [comment]
i think i am also going to up this issue.. a lot of the documentation is not wired correctly.. Great docs but need to get it in order.

**Comment by flomotlik** [comment]
This is fixed now and we resolved a lot of link issues in Github.
