### ISSUE TITLE
README.md links not working

### ISSUE THREAD

**Issue by nurous** [serverless/serverless#2095]
# This is a Bug Report

## README.md links not working

* What went wrong?
404 pages when clicking on links from README.md that is displayed when viewing https://github.com/serverless/serverless

* What did you expect should have happened?
Clicking link "Guide to Serverless" at "https://github.com/serverless/serverless" should have gone to "https://github.com/serverless/serverless/docs/01-guide/README.md" instead of "https://github.com/serverless/docs/01-guide"

* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #2092

## Additional Data

* ***Serverless Framework Version you're using***:
https://github.com/serverless/serverless/tree/30448615b542d5673d011b22c98974c772b8610b
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by flomotlik** [comment]
Thanks for reporting and the PR. It looks like this was also a bug in Github today, because some links are now working properly again. We're moving our Docs hosting out of Github soon, so then everything should be fine in the future. Thanks for reporting and sending the PR!
