### ISSUE TITLE
Feature: errors should print current used Node version and Serverless version

### ISSUE THREAD

**Issue by robertkowalski** [serverless/serverless#2109]
# This is a Feature Proposal

## Description

For feature proposals:
* The Serverless CLI should print the current used Node version and Serverless version in case of an error. This makes life easier for the user and the maintainers.

Example:

![screen shot 2016-09-12 at 23 48 50](https://cloud.githubusercontent.com/assets/298166/18454227/805154a8-7943-11e6-8aff-1b14dc8c9c50.png)

Btw: we can print the whole **additional data** field from the issue template ready for copy & paste. The stack trace is available anyway and we can get the platform with `require('os').platform()`

One question: any reason to just print the stacktrace with the environment variable? 

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1
* ***Operating System***: OS X
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by flomotlik** [comment]
@robertkowalski this is a great idea (including the OS as well sounds awesome).

Regarding the Stacktrace it would just make the whole error very long and confusing. But what would be cool is if we could see the location where the error was thrown, so file/line number. That itself would help a lot and we don't necessarily need to print the whole Stacktrace in the error message.

**Comment by nicka** [comment]
That would be really useful indeed!

**Comment by flomotlik** [comment]
Looks like @horike37 is already working on this. @horike37 could you leave a quick message here just so we know this is in progress?

Also thanks for jumping on this so fast!

**Comment by horike37** [comment]
The Coveralls issue occurred as a result of none test code.

https://github.com/serverless/serverless/tree/master/tests/classes
I expected to exist a test code file of `lib/classes/Error.js`, but It is not exist.

What to you would if there is intention ?
If there is no special meaning it. I think to make `tests/classes/Error.js`.

**Comment by pmuens** [comment]
Done with #2122 /cc @flomotlik
