### ISSUE TITLE
sls can't handle any commands if option is missing

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#2112]
If I have ${opt:stage} defined in my serverless.yml, even --version gives me an error:

 sls --version
 
  Serverless Error ---------------------------------------
 
     Trying to populate non string value into a string for
     variable ${opt:stage}. Please make sure the value of
     the property is a string.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

Version: 1.0rc1

**Comment by andymac4182** [comment]
Do you have a default for the location for where you are using ${opt:stage}? If you don't it will return `undefined` which isn't a string.

**Comment by pmuilu** [comment]
Yes I'm aware of that option but IMO it shouldn't block commands like --version or --help.

**Comment by andymac4182** [comment]
This appears to be the same as https://github.com/serverless/serverless/issues/2041

**Comment by pmuilu** [comment]
Dupe
