### ISSUE TITLE
DX: Print message that an update is available if user runs Serverless command with an outdated version

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2118]
# This is a Feature Proposal
## Description

It would be great if we could print a message on the console that an update is available whenever the user runs a command with an outdated Serverless version.

Shoutouts to @mthenw who brought this up! 👍 

/cc @flomotlik @eahefnawy

**Comment by andymac4182** [comment]
It would be great if this was ignored when running from a git clone.

**Comment by andymac4182** [comment]
Did you want this to check against NPM or Github as to what is the latest version?

**Comment by pmuens** [comment]
@andymac4182 thanks for your feedback! Good ideas here (as usual).

I would check against npm because people will install it through npm (at least most of the people will do this I think).

What do you guys think? Should we do the check with each and every command or only if the user runs e.g. `serverless deploy` (only on the `deploy` command).

**Comment by andymac4182** [comment]
I was thinking of 1st command of the day. Just store a temporary file that has the last checked date so it doesn't slow down all the commands. Once there is an update it would be good to store that fact in the temporary file and include that if there is any errors and possibly as the last line after each command.

**Comment by pmuens** [comment]
👍 Really like that idea! This way we can do the check on whatever command the user has entered without totally slowing down each and every subsequent command! Pretty cool.

**Comment by andymac4182** [comment]
Should this show the user the latest version or the latest version inside their major version? Should it show beta/rc updates or just stable? It might be worth letting people pick a beta/stable track and use that to find the latest update. 

## Beta track
* Beta Updates
* Stable Updates

## Stable Track
* Stable Updates

**Comment by pmuens** [comment]
Hmm. I would prefer to display messages only when stable release are available (Have seen that behavior in other CLI tools as well).

Another idea would be that we print a slightly different message if a preview is available so that the user knows that it's an unstable version.

**Comment by flomotlik** [comment]
I would keep this simple for now. Imho the people who really want to use beta or preview updates are following serverless so closely that they should see this anyway (and we'll make it very obvious when we release alpha/beta/rc). Everyone who just wants to use Serverless stable would be confused, so we would optimise for a small minority of people over confusing the large majority of users.

So imho simply checking if the current version is the same as the current stable release would be great and if we want to introduce a preview section in the future we could do that as well. Also checking once a day makes total sense to me.

**Comment by hassankhan** [comment]
We could potentially use [update-notifier](https://www.npmjs.com/package/update-notifier) to do the heavy lifting.

**Comment by brianneisler** [comment]
Seems like a very quick change. Adding this to the 1.16 milestone.
