### ISSUE TITLE
Feature Proposal: Create Log Groups for lambda functions as part of Cloudformation

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2126]
# This is a Feature Proposal

## Description
When creating the functions in the cloudformation template it would be ideal if the relevant log groups were created as well. 

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This would allow for setting a retention policy on the logs to help with costs. It also would allow for hooking up of a subscription to handle alerting and processing of logs. This is hard at the moment due to the fact that the log groups are only created after the lambda has executed once. It will also mean the log groups can be cleaned up as part of `sls remove` where they are being left there currently clogging up the interface.
* If there is additional config how would it look

```
{
    "Type" : "AWS::Logs::LogGroup",
    "Properties" : {
        "LogGroupName" : "/aws/lambda/${FunctionName}"
    }
}
```
It would be simple to add it around https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/functions/index.js#L170 

## Additional Data

* ***Serverless Framework Version you're using***: Master
* ***Operating System***: Win
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by eahefnawy** [comment]
👍 💯 totally agree! Requiring at least a single invoke to create the log group kinda sucks and causes some unneeded error handling.

Also, if I understand this correctly, are you saying that when users `serverless remove` (which of course removes the lambdas), those lambda log groups would NOT be removed?! Interesting!!!! Never noticed that before.

**Comment by andymac4182** [comment]
This has been started to be implemented in https://github.com/serverless/serverless/pull/1944
