### ISSUE TITLE
Warn when incorrect format for additional IAM Role Statements causes them not to be included

### ISSUE THREAD

**Issue by ianserlin** [serverless/serverless#2132]
# Bug Report
## Description

When using a `$ref` to include additional IAM Role Statements for a service, if the `$ref`'d file is not in the correct format (i.e. an array including more role statements), the role statements you are attempting to include are silently not included.

This may also happen when not using `$ref` and simply including incorrectly formatted statements in the `yml` directly.
- What went wrong?

Incorrectly formatted role statements were silently not included in the final composed CloudFormation template.
- What did you expect should have happened?

For the CLI to throw an error or warning that the role statements would not be included.
- What was the config you used?

Example `serverless.yml`

``` yml
service: myfancyservice
runtime: nodejs4.3
provider:
  name: aws
  iamRoleStatements:
    $ref: ./roleStatements.json
```

Example incorrect `roleStatements.json`:

``` json
{
  "IamPolicyLambdaInvocationAndDynamoDBStream": {
    "Type": "AWS::IAM::Policy",
    "Properties": {
      "PolicyName": "iam-policy-lambda-dynamo-${opt:stage}",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "lambda:InvokeFunction"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "dynamodb:*"
            ],
            "Resource": "*"
          }
        ]
      },
      "Roles": [
        {
          "Ref": "IamRoleLambda"
        }
      ]
    }
  }
}
```

Example correct `roleStatements.json`:

``` json
[
  {
    "Effect": "Allow",
    "Action": [
      "lambda:InvokeFunction"
    ],
    "Resource": "*"
  },
  {
    "Effect": "Allow",
    "Action": [
      "dynamodb:*"
    ],
    "Resource": "*"
  }
]
```
- What stacktrace or error message from your provider did you see?

None by default.

Issue presents itself when the lambda is executed. If you add an event mapping which depends on these policies then CloudFormation will throw an error when creating the stack, if you do not have that, it will not throw an error.
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.0-rc1
- **_Operating System**_: OS X 10.11.6
- **_Stack Trace**_: N/A
- **_Provider Error messages**_: none

**Comment by flomotlik** [comment]
Thanks for reporting, sorry for the delay on answering, this should definitely be fixed through some validation.

**Comment by imaman** [comment]
working on a solution

**Comment by pmuens** [comment]
@ianserlin thanks for reporting! 👍 
@imaman thanks for jumping into this! 💯 

I reviewed the code and added a few comments!
