### ISSUE TITLE
CORS to cover also other status codes

### ISSUE THREAD

**Issue by riccardo-89** [serverless/serverless#2134]
**Feature Proposal**

I have noticed that when I receive a status code different from 200 in the browser, CORS do not behave as expected, in version 0.5 I add cors headers to response template also for the other status codes and they started to be covered (but 403), since serverless is doing thing under the hood for response integration it would be nice that as default "cors: true" these would be covered automatically.

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0 rc1
* ***Operating System***: MacOS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by aaronwhite** [comment]
@riccardo-89 why did you close this? I may be running into a similar issue w/ custom responses.... did you find a way around it?
