### ISSUE TITLE
CF stack deployment displays output for all resources

### ISSUE THREAD

**Issue by lxjuly** [serverless/serverless#2135]
# This is a Feature Proposal
## Description
- When `serverless` finishes deployment, it will print out the service information: endpoints and functions. However, currently it does not print out resource information of custom defined AWS resources such as the URL of an RDS instance.
- There should be no additional configuration needed, it should be available by default.
## Additional Data
- **_Serverless Framework Version you're using**_:
  `1.0.0-rc1`
- **_Operating System**_:
  `Mac OS X El Captain`
- **_Stack Trace**_:
  None
- **_Provider Error messages**_:
  None

**Comment by andymac4182** [comment]
Are you looking for their ARN or something in particular for each resource?

**Comment by lxjuly** [comment]
@andymac4182 Not just ARN but all output key/value pairs returend from cloudformation. e.g. I defined `JDBCConnectionString` as one of the output value for my RDS stack as follows:
```json
"JDBCConnectionString": {
      "Description" : "JDBC connection string for database",
      "Value" : { "Fn::Join": [ "", [ "jdbc:postgresql://",
        { "Fn::GetAtt": [ "pgDB", "Endpoint.Address" ] },
        ":",
        { "Fn::GetAtt": [ "pgDB", "Endpoint.Port" ] },
        "/",
        { "Ref": "DBName" }]]}
    }
```
I should be able to retrieve the JDBC connection string from the output of `sls deploy`.

**Comment by eahefnawy** [comment]
IMO the `serverless info` plugin or deployment summary should just provide the most essential info about your Service. If we allow all outputs in there (keeping in mind that some outputs are just long ID strings), the overall output on the terminal would be very messy and would defeat the purpose of the "summary" achieved by the info plugin.

Would love to see a `serverless outputs` plugin though 😉

**Comment by andymac4182** [comment]
Since outputs are an AWS thing should the command be something more like `sls aws outputs` ?

**Comment by eahefnawy** [comment]
@andymac4182 good point! 👍

**Comment by lxjuly** [comment]
@andymac4182 I think a separate command makes sense but in that way we should treat the outputs from `sls deploy` carefully. For example, adding hints to them so that the user knows there is additional info from the deployment and in order to retrieve the additional info he/she will issue `sls aws outputs` command. Or maybe add an option `-output verbose` to the `sls deploy` command to display all outputs of the deployment.

**Comment by msl-kabo** [comment]
If I have for example:
```yaml
Resources:
    IAMUserKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: { "Ref": "MyUser" }
Outputs:
    Description: secret key
    Value: { "Fn:GetAtt": ["IAMUserKey", "SecretAccessKey"] }
```
The secret key won't be retrievable later, it has to be displayed or saved immediately.

**Comment by svdgraaf** [comment]
I created a plugin for this, https://www.npmjs.com/package/serverless-plugin-stack-outputs

It will append your stack outputs when you call `sls info --verbose` or `sls deploy --verbose`. You can also just get the outputs through `sls info outputs`

**Comment by lxjuly** [comment]
@svdgraaf That's neat! Thanks!

**Comment by andymac4182** [comment]
@svdgraaf Any chance of submitting that back as PR so no need for extra plugins?

**Comment by flomotlik** [comment]
@svdgraaf I think it would be great to have this under the verbose option of info and deployment!

**Comment by svdgraaf** [comment]
Ok, I'll start to work on that :)

**Comment by svdgraaf** [comment]
@flomotlik Done ^^ 😄
