### ISSUE TITLE
Feature Proposal: Ability to specify just to include handler file when packaging individually

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2139]
# This is a Feature Proposal
## Description

When using something like `serverless-webpack` or similar the only part that needs to be packaged up normally is the handler file. Ideally I would like to be able to tell the packaging to just get that file instead of having to exclude everything and include that one file. 

For feature proposals:
- What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Simple packaging when using a build pipeline with serverless
- If there is additional config how would it look

```
package:
  individually: handler-only
```
## Additional Data
- **_Serverless Framework Version you're using**_: master
- **_Operating System**_: Win
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by flomotlik** [comment]
You can do that with globbing now and only include the handler.
