### ISSUE TITLE
Cannot set variableSyntax

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless#2143]
# Bug Report
## Description

For bug reports:
Unable to set `variableSyntax`. I have set the `variableSyntax` property as below:
```
provider:
  variableSyntax: '\${{([\s\S]+?)}}'
```
This is to enable me to use the AWS IoT SQL functions. This was working in beta.2. But, now I get the following error:

<img width="1024" alt="variablesyntax" src="https://cloud.githubusercontent.com/assets/1297227/18549060/860d68f2-7b8f-11e6-9d53-b12c640b960e.png">

I added some logging to my fork (see screenshot above). I found that `Variables.js` is created before the `load` method in `Service.js` is called. The end result is that the `variableSyntax` is always set to the default value and cannot be set in `serverless.yml`

*Suggested Fix*
In `Variables.js`, set `variableSyntax` in `#populateService()` rather than in the constructor.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1
* ***Operating System***: OSX
* ***Stack Trace***: See screenshot above
* ***Provider Error messages***: See screenshot above

Happy to send a PR if you would like. Should be an easy fix.

**Comment by eahefnawy** [comment]
thanks @johncmckim ... feel free to PR 😊
