### ISSUE TITLE
Feature Proposal: tail logs on invoking functions from command line

### ISSUE THREAD

**Issue by koraytaylan** [serverless/serverless#2145]
# This is a Feature Proposal

## Description

When running deployed functions from command line, it would be handy if it tails the logs while waiting it to finish executing. So we could easily see what's going on instead of tracking them from cloudwatch.

**Comment by andymac4182** [comment]
@koraytaylan This was added recently. There is a `-v` option.

**Comment by koraytaylan** [comment]
@andymac4182 i got excited for a moment and
tried it immediately as follows,
serverless invoke -f myFunction -v
Doesn't work though.

**Comment by andymac4182** [comment]
Sorry @koraytaylan I miss read that as deploying.

**Comment by koraytaylan** [comment]
Hmmm it turns out the proper option was -l not -v

However it still waits until execution is completed. I wonder if that's possible to gather them as they appear...

**Comment by rowanu** [comment]
I think it would depend if you want to receive the output of the function you've invoked still - due to the lag in CW Logs, you'd end up having a mishmash of log messages and function output (and then more log messages) if you did the "live" tailing of the logs.

**Comment by eahefnawy** [comment]
hmmm why don't use tailing with `serverless logs` instead? you can then invoke in a different shell and see the updates live on the logging shell. You're gonna have to do that anyway even if we had tailing with invoke because tailing steals the entire session and you'll need a different shell anyway.

so I personally don't see a need for that ☺️

**Comment by eahefnawy** [comment]
I think this is pretty much resolved 😊 ... Closing
