### ISSUE TITLE
Feature: serverless create -t should list available templates

### ISSUE THREAD

**Issue by robertkowalski** [serverless/serverless#2155]
# This is a Feature Proposal

## Description

For feature proposals:
* As a user I want to quickly see which templates are available / the template for S3 is named

current output:

```
$ serverless create -t

  Serverless Error ---------------------------------------

     This command requires the --template option / -t shortcut.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

proposed output:

```
$ serverless create -t

  Serverless Error ---------------------------------------

     This command requires the --template option / -t shortcut.

     Usage:

     serverless create -t <templatename>

     Available templates:

     template A, template b, S3, Nodejs-AWS

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1
* ***Operating System***: OS X
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by andymac4182** [comment]
Would just outputting the usage from the command solve this for you? Here is the current usage output for the create command. https://github.com/serverless/serverless/blob/master/lib/plugins/create/create.js#L31

If so it should just be a matter of adding the usage to https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L63

This would solve this issue for all commands not just the `create` command.

**Comment by andymac4182** [comment]
Implemented as noted above
```
  Serverless Error ---------------------------------------

     This command requires the --message option / -m shortcut.
     Usage: Specify the message you want to deploy (e.g.
     "--message 'My Message'" or "-m 'My Message'")
```

**Comment by kennu** [comment]
I stumble into this every time I'm creating a new Serverless 1.0 project, because I can't remember the template name.

**Comment by mthenw** [comment]
Already fixed. Current error looks like this:

```
     This command requires the --template option / -t shortcut.
     Usage: Template for the service. Available templates:
     "aws-nodejs", "aws-python", "aws-java-maven", "aws-java-gradle"
     and "aws-scala-sbt"
```
