### ISSUE TITLE
Switch docs from docs.serverless.com to serverless.com/framework/docs

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2167]
# This is a Feature Proposal

## Description

Thanks to the great work by @DavidWells we have the docs now in `serverless.com`. Before we're moving the dns and everything else over to them though we want to make sure to get some community opinion and feedback and see if you guys have any ideas for potential improvements or see problems.

So take a look at our [new documentation](http://serverless.com/framework/docs), let us know in this issue if there is anything you'd think we can improve or things you specifically like.

/cc @serverless/vip 

Similar or dependent issues:
* #2164

**Comment by WooDzu** [comment]
As folks will go ahead migrating from 0.5 to 1.0 imho the docs should mention migration steps and highlight areas that are still missing, custom response status codes for instance.

**Comment by WooDzu** [comment]
Additionally, I found the left sidebar a little chaotic as it does not match the contents in main area, not even sure if it is supposed to.
![sls-sidebar](https://cloud.githubusercontent.com/assets/2228236/18667496/21eecf14-7f31-11e6-9f5a-7de0444bba8a.png)

**Comment by kennu** [comment]
I've browsed the new documentation quite a few times. While I think it has quite good coverage, I found it difficult to find clear descriptions of serverless.yml configuration sections ("what exactly can I put in this YAML key"). The main documentation page does not mention serverless.yml in any way, and none of the section topics seem to cover it (Quick Start Guide, Core Concepts, CLI Reference, Providers, Extending Serverless, Contributing to Serverless).

There also seems to be some mismatch between those topics and the left-sidebar index, which looks similar but is not quite the same (Guide, Providers, Cli reference, Extending serverless, Usage Tracking).

**Comment by bennybauer** [comment]
The `docs` link in the https://serverless.com/ black box still points to the old documentation
![pasted_image_20_09_2016__2_16_pm](https://cloud.githubusercontent.com/assets/3007059/18668233/f53033f8-7f3c-11e6-8267-e5339afc0f2d.jpg)

**Comment by flomotlik** [comment]
@bennybauer yup we haven't switched it over yet. This is not officially released yet, we want to make sure you guys can give us some feedback before it actually goes out to the whole community.

**Comment by erikerikson** [comment]
Great changes.  Had wondered when and how this would happen.

The lack of search is a bit of a bummer but I imagine that'll come over time and we can fall back to google in the meanwhile.

Lastly, will the docs page that hosts the MDs be committed?  (did I simply fail to find it/them?)

**Comment by pmuens** [comment]
@erikerikson thanks for the feedback 👍 

@DavidWells is working on more great improvements here! Not sure if the docs project is open source. Maybe @DavidWells can shed some light into this!

**Comment by flomotlik** [comment]
https://github.com/serverless/site

Am 23.09.2016 06:50 schrieb "Philipp Muens" <notifications@github.com>:

**Comment by DoWhileGeek** [comment]
I agree with @kennu, There absolutely needs to be reference documentation on every minute detail of `serverless.yml`.

**Comment by flomotlik** [comment]
@kennu @DoWhileGeek yeah we've removed the full `serverless.yml` overview because the specific providers can have very different configs. What I'm currently thinking about is adding a serverless.yml example config that shows all the high level non-provider specific config areas and then links to the provider specific docs for the specific options that are available there. So you can see the general layout of a serverless.yml, but we don't do it in a way that is too specific.

**Comment by DoWhileGeek** [comment]
@flomotlik Omitting the provider specifics sounds like the right thing to do. Although, while you don't exactly say it, it sounds like you're describing an overview, not a reference. We need reference material.

I look at the docs, and I see a lot of getting started/quick-start/overview docs, but I feel uneasy wielding all this power in production without an exhaustive user's manual.

**Comment by flomotlik** [comment]
@DoWhileGeek we have documentation for every config parameter for AWS here: https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/README.md

Generally every parameter that is available should be documented. In case there is something you feel is missing please let us know!

**Comment by DoWhileGeek** [comment]
@flomotlik Wow, this is everything I've been wanting! Am I blind, or is it impossible to find just by surfing the docs on serverless.com?

**Comment by flomotlik** [comment]
@DoWhileGeek Its there (https://serverless.com/framework/docs/providers/aws/) but the way we link to it and tell people to find it just isn't in a good place yet imho. Its not visible enough on the main site and the Call to Action to read it should be stronger.

**Comment by kennu** [comment]
I think there is some dissonance between what the reader needs ("what can I put in serverless.yml?") and how the developers see the project (number of separate modules that are intentionally kept very separate). My advice would be to put the needs of the reader before everything else when thinking how to structure the docs.

**Comment by lorenzos** [comment]
My two cents: I find confusing (if not disturbing) the fact that links in the sidebar do not math the title in the page, nor the HTML `<title>`.

For example, clicking **Setting up Events** loads to the **Event sources** page, with `<title>` as **Setting up Events for your functions**. It's wuite the same for every page :smiley: 

For the rest, it looks good, surely better that the docs for 0.4/0.5 release. I just read it all, and it's very clear. Maybe the fact that you guys have dramatically steamlined the framework itself, helped a lot. Kudos for that! :+1:

**Comment by DoWhileGeek** [comment]
+1 @lorenzos
