### ISSUE TITLE
DX: Add Questionaire to Onboarding, docs and different way to test onboarding

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2168]
# This is a Feature Proposal
## Description

At the moment we don't have any way to track or understand how easy our onboarding process is for users. We have to fully rely on asking people or tracking issues that come up through the forum, gitter or our issues. This might lead to a warped view because users who have not been able to go through the first onboarding and didn't deploy a service might not even talk to us at all.

To make sure we get better insights into this we want to add different messages throughout the onboarding process so we get that feedback from users.

Ideas we could do:
- Add onboarding questionaire link to Serverless Error message so people give us quick feedback when they get blocked
- Adding contact email to Error so they reach out
- Add questionaire to Docs Guide (at the end of the guide, at the provider setup page, ...) to communicate with users.
- Do an onboarding study with different groups of people
  - Users that have no AWS experience
  - Users with AWS experience, but who haven't use serverless or Lambda in the past
  - Users with AWS experience, who haven't used serverless in the past but where serverless is used at their company
- ???

Similar or dependent issues:
- #2160

**Comment by flomotlik** [comment]
@worldsoup lets discuss this soon and then add this to an appropriate milestone

**Comment by worldsoup** [comment]
@flomotlik yep, I just created a new survey and was thinking we could show a link to it after a user runs their nth command.

**Comment by pmuens** [comment]
Closing this issue since we've implemented the feature request in different ways.
