### ISSUE TITLE
Windows CloudFormation Handler Location Slashes

### ISSUE THREAD

**Issue by TheConnMan** [serverless/serverless#217]
After running `jaws module create` on Windows and trying `jaws run` I get a the following error:

> Error: Cannot find module 'C:\Users\Me\myproject\aws_modules\message\post/aws_modules\message\post\handler.js'

The single forward slash appears to be messing up what I guess to be a find in the module's absolute path to decide if the **aws_modules** suffix needs to be added.

After replacing `lambda.cloudFormation.Handler` from **awsm.json** under `aws_modules/message/post` with forward slashes instead of double back slashes it works. Running jaws from both the Windows command line and Babun yields the same results for both scenarios.

**Comment by TheConnMan** [comment]
After a little research I found this is an issue in the `jaws module create` call. The path on Windows machines is joined using double backslashes in [this module_create](https://github.com/jaws-framework/JAWS/blob/2fa7d9158490c27a7de033949f920c65510207fc/lib/commands/module_create.js#L180) line.

**Comment by sixlettervariables** [comment]
Could use `path.posix.join` to enforce POSIX file conventions.

**Comment by eahefnawy** [comment]
Thanks for reporting this guys. We've cleaned our codebase from any "linux assumptions" with the path specifically as much as we could. We still keeping an eye on it through this trello card:
https://trello.com/c/q5bSdU4P/133-windows-fixes-use-path-sep-wherever-is

Closing for now...
