### ISSUE TITLE
Advanced Guides broken link

### ISSUE THREAD

**Issue by aottenwess** [serverless/serverless#2171]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
 * https://serverless.com/framework/docs/guide/README.md#advanced-guides link is broken
* What did you expect should have happened?
 * link takes me to the advanced guides
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by andymac4182** [comment]
Where was the link?

**Comment by aottenwess** [comment]
Sorry, should've included that. Found under the **What's Next?** header at this link: https://serverless.com/framework/docs/guide/removing-services/

**Comment by andymac4182** [comment]
Thanks. 👍  I will fix it shortly

**Comment by andymac4182** [comment]
Found a few other links that were like this that I have fixed in #2172

**Comment by mthenw** [comment]
Already fixed.
