### ISSUE TITLE
Add Access-Control-Allow-Credentials for CORS settings

### ISSUE THREAD

**Issue by TaichiHo** [serverless/serverless#2182]
# This is a Feature Proposal
## Description

Right now I am developing a cross origin resource sharing (CORS) application which requires sharing cookies. The server is required to return the Access-Control-Allow-Credentials header set to true to allow this. While there is way to set headers, methods and origins with serverless, there is no easy way of setting the allow-credentials header. Will have to go to aws console to enable this which is a headache for maintenance. 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by IIapad0ks** [comment]
+

**Comment by str3tch** [comment]
+1, is there a fix for this anywhere?

**Comment by fruffin** [comment]
I needed that as well and now have an experimental version working for me.
I'll polish it a bit, write the tests and start the PR

**Comment by str3tch** [comment]
ha, I also have a rough and ready version too. need to polish it a lot, so you might beat me to it. Will be good to compare approaches

**Comment by fruffin** [comment]
Ready for review
Works on my machine! ;-)
