### ISSUE TITLE
lodash is not explicitly required

### ISSUE THREAD

**Issue by technicool** [serverless/serverless#2184]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
  * Saw the error `Cannot find module 'lodash/object/assign'` when creating a new project
* What did you expect should have happened?
  * Should have seen yellow SERVERLESS letters with new app created
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Steps taken:

    > npm install --save-dev serverless@1.0.0-rc.1
    > ./node_modules/.bin/serverless create --template aws-nodejs
    
    Error:
      Cannot find module 'lodash/object/assign

Then, to remedy:

    > npm install --save-dev lodash
    > ./node_modules/.bin/serverless create --template aws-nodejs
    
    Successfully created service with template: "aws-nodejs"

## Additional Data

* ***Serverless Framework Version you're using***: stock 1.0.0-rc.1
* ***Operating System***: Mac OS X 10.10.3
* ***Stack Trace***: No stack, only message asking to report bug
* ***Provider Error messages***: N/A

**Comment by andymac4182** [comment]
Does this work when installing serverless globally?

**Comment by eahefnawy** [comment]
@technicool I can't reproduce this. Do you have any hint why this was happening for you and how we can fix it?

**Comment by technicool** [comment]
This machine has enough junk on it that I'm guessing it is a combination of other packages installed. And, it's not happening again. I'll close out the bug.
