### ISSUE TITLE
Support for Asymmetric (Public Key) JWT Validation

### ISSUE THREAD

**Issue by cancan101** [serverless/serverless#22]
Modify [this](https://github.com/servant-app/JAWS/blob/8ec4ddd99f14dd6e6bb2ba61765e529f055aba48/lib/middleware/middleware_incoming.js#L53) to support alternative validation schemes: https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback.

**Comment by ac360** [comment]
@cancan101  Thank you.  Your input has been especially helpful.  I'm publishing a JAWS Road Map this weekend.  This will be in there.

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by AnalogJ** [comment]
Hey @ac360 I noticed that you removed this from the v1.0 milestone. Does that mean integrated JWT support won't be coming any time soon?

**Comment by flomotlik** [comment]
@AnalogJ going forward you do not have to rely on the serverless middleware and could use any JWT compatible library or tooling for your lambda functions. We are looking into potential authentication in our future SDK, but don't have specific plans yet. For the time I'll close this issue as we will be tracking this separately if we plan to integrate this directly into serverless, but you can absolutely use JWT already in your V1.0 lambdas.
