### ISSUE TITLE
npm not installing aslant as peer dependency

### ISSUE THREAD

**Issue by criticalmash** [serverless/serverless#2203]
# This is a Bug Report

## Description

NPM Warnings encountered when installing serverless@1.0.0-rc.1 on node v4.5.0 (npm v2.15.9)

It appears that the downloading of peer dependencies won't be supported in future versions of npm. I originally tried to install this package with node 6.6.0 but the peer dependency would not install.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #2187 - this one seems to be about the linter as well

## Additional Data

* ***serverless@1.0.0-rc.1***:
* ***OS X El Capitan v10.11.6***:

```sh
npm WARN peerDependencies The peer dependency eslint@^3.3.1 included from eslint-config-airbnb-base will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-import@^1.13.0 included from eslint-config-airbnb-base will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by rowanu** [comment]
None of these warnings are for the Serverless project itself - there are no `peerDependencies` in the Serverless [`package.json`](https://github.com/serverless/serverless/blob/master/package.json).

There is nothing that can be done.

**Comment by dougmoscrop** [comment]
The warnings are "for" serverless:

```
(serverless) -> dep (A) -> peerDep (B)
            \-> dep (B) <----- if serverless does not have this for all peerDeps of its deps/devdeps* it will break on npm@3
```
It sounds like you checked and there are no missing deps. 👍 

Also Travis is running on 6.2 (npm 3+) so I think it would catch any problems.

**Comment by flomotlik** [comment]
@criticalmash @rowanu @dougmoscrop I'm not sure if there is something actionable we can do here? Let me know if you think there is something we can change to either make the message go away or to make sure we're not running into issues with this in the near future? Closing for now unless we come up with something actionable. 

Thanks for reporting @criticalmash !
