### ISSUE TITLE
the hello world 'serverless deploy' deployment fails

### ISSUE THREAD

**Issue by bder** [serverless/serverless#2215]
## Bug Report

Template does not deploy successfully.

$ serverless create --template aws-python --path hello-world
$ cd hello-world
$ serverless deploy
## Description

the hello world 'serverless deploy' deployment fails
## Stack trace

Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

```
 An error occurred while provisioning your stack: HelloLambdaFunction
 - The role defined for the function cannot be assumed
 by Lambda..
```
## Additional Data
- **_Serverless Framework Version you're using**_:
  1.0.0-rc.2
- **_Operating System**_:
  Mac OS X Version 10.11.6

**Comment by camhart** [comment]
This is also happening to me when I attempt to use a "schedule" event.

Serverless Framework Version:
1.0.0-rc.2

Operating System:
Windows 10

**Comment by flomotlik** [comment]
@bder do you have full admin rights to set up the role? Just tried the same with the current master and I can deploy and invoke the python example without any issue. Can you run the whole deployment with `-v` so we see more details?

**Comment by camhart** [comment]
@flomotlik @bder While I was getting this error yesterday, I have not changed anything but the error has gone away.  Maybe it was something on AWS's side?

**Comment by mthenw** [comment]
@bder do you still get this error?

**Comment by BenKowalski** [comment]
I'm getting the same error. It worked for like 10 deploys and suddenly it doesn't work anymore. I run "serverless deploy -v":

`Serverless: Packaging service...
Serverless: Removing old service versions...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - aws-nodejs-dev
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - InviteLambdaFunction
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - aws-nodejs-dev
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - InviteLambdaFunction
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - aws-nodejs-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - aws-nodejs-dev
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: InviteLambdaFunction
     - CloudFormation cannot update a stack when a custom-named
     resource requires replacing. Rename aws-nodejs-dev-invite
     and update the stack again..`

**Comment by ac360** [comment]
@BenKowalski Are you using v1.03?

**Comment by BenKowalski** [comment]
It's 1.0.2.

**Comment by mthenw** [comment]
@BenKowalski could you try again after upgrading to 1.0.3?

**Comment by mthenw** [comment]
Closing for now.

**Comment by VisheshMad** [comment]
I am getting the same error !! I tried below command and the process stops at first line it self.

command:` "serverless deploy --stage production --region us-east-1"`
output: 
`vishesh@home:~/serverless$ serverless deploy --stage production --region us-east-1
Serverless: Packaging service...
vishesh@home:`

**Comment by pmuens** [comment]
@VisheshMad thank you for your comment.

Could you please share the whole error message you get and the config you've used (including the Framework and Node version)? 👍 Thanks in advance.

**Comment by VisheshMad** [comment]
Sorry, i made this mistake. I was running one folder behind of serverless.yml location. Thanks !!!

**Comment by pmuens** [comment]
> Sorry, i made this mistake. I was running one folder behind of serverless.yml location. Thanks !!!

No worries! Glad to hear that the issue has been resolved.

**Comment by Sandeepjagadeesh** [comment]
Hi, 

I too have a same problem while deploying 
$sls deploy --verbose

After this command it takes time and outputs as:

Serverless:Packing service...

And followed by list of errors , please help me out

![error](https://user-images.githubusercontent.com/16860759/28240945-17ae65a0-6950-11e7-8940-b9ecfcad7068.png)

**Comment by pmuens** [comment]
Hey @Sandeepjagadeesh thanks for commenting 👍 

What Serverless, Node and Windows version are you running? How does your `serverless.yml` file look like?

**Comment by hraban** [comment]
This happened to me just now. Turned out there was already an IAM role "hello-something-something" which was conflicting with the deploy. The solution was resolved after logging in to the IAM console, clicking roles, finding that role and manually deleting it. (It was probably vestigial from someone else running this helloworld example a long time ago.)

**Comment by Afsalkp321** [comment]
[](url)
![auth-issue](https://user-images.githubusercontent.com/115461886/206830022-4b2668d3-f8d1-4d97-b32d-1190e92b01b9.png)

**Comment by Afsalkp321** [comment]
Hello i was trying to deloy seerverless helloworld function.I coud easily deploy function untill iam getting some health issue from aws.But even after solving the issue i couuld not create lamda function both manually and serverless way,plaes help me
