### ISSUE TITLE
Scala Support

### ISSUE THREAD

**Issue by meagonqz** [serverless/serverless#2217]
# This is a Feature Proposal

## Description

Add a template for scala projects using sbt to create a java 8 lambda.
`sls create --template aws-scala-sbt --path <path>` following the Hello World example of the existing java templates but in scala.

I've already implemented this because we intend to use it internally at Localytics.

Similar or dependent issues:
* #682

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.2+
* ***Operating System***: OS X Yosemite 10.10.5

**Comment by flomotlik** [comment]
Great stuff, thanks for contributing!

**Comment by flomotlik** [comment]
Btw we'd love to chat with you at Localytics to understand your use cases a little more. Could you reach out to flo@serverless.com if thats interesting to you. We also got a few other products planned and would love to get your feedback on it.

**Comment by pmuens** [comment]
#2218 Implements that /cc @flomotlik
