### ISSUE TITLE
Other provider values (than aws) are not supported

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2226]
# This is a Bug Report

## Description

If I switch the provider property in my `serverless.yml` file from e.g. `aws` to `ibm` or `google` I get the error message that this provider is not supported and I should chosse from a list with supported providers (supported providers include `ibm` and `google`).

**Comment by dougmoscrop** [comment]
Also fixed in https://github.com/serverless/serverless/pull/1858/files#diff-acf6b4e1fa4c84f14b7ff2a8c512e228R80
