### ISSUE TITLE
Managing corporate proxies

### ISSUE THREAD

**Issue by Ninir** [serverless/serverless#223]
Hey JAWS team!

While this project is reallllyyyy amazing, I'm kind of breaking my teeth with corporate proxies, and ways to deploy via jaws dash. The error I get is:

```
{ [NetworkingError: connect ECONNREFUSED 
...

```
I was used to declare this on my Mac:

```bash
declare -x http_proxy="http://IP:PORT"
declare -x https_proxy="http://IP:PORT"
```

which is fine with NPM, Bower, and all these kind of package managers.

I also tried to add env vars in the .env file (as with HTTP_PROXY and HTTPS_PROXY), but this does nothing, or at least I'm not doing it the right way :smile:.

Do you guys have a hint for me please? :)

**Comment by DanDiac** [comment]
You set env variables per Stage and Region using this command:
jaws env set [stage] [region] [varname] [varvalue]

Then you use it with process.env.varname

**Comment by Ninir** [comment]
@DanDiac This is exactly the point: I can't in my case, as it requires to go to the network :/
When running the command, it tries to get the env file from s3, thus throwing the same `NetworkingError`.

It is a particular issue of proxies that is handled by other binaries

**Comment by sixlettervariables** [comment]
@Ninir, if I'm understanding you correctly you need the `aws-sdk` calls to use a configured proxy. In this case, [JAWS would need to supply the proxy to the AWS SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Configuring_a_Proxy).

In [`./lib/utils/aws.js` there is a place to make that happen for the SDK](https://github.com/jaws-framework/JAWS/blob/master/lib/utils/aws.js#L31):
```js
module.exports.configAWS = function(awsProfile, awsRegion) {

  // Check Profile Exists
  this.profilesGet(awsProfile);

  // Set Credentials
  AWS.config.credentials = new AWS.SharedIniFileCredentials({
    profile: awsProfile,
  });

  // Set Region
  AWS.config.update({
    region: awsRegion,
  });
};
```
The irony is that I can't get to GitHub behind my corporate firewall to make the pull request!

**Comment by Ninir** [comment]
@sixlettervariables Do you want me to send it in your name?

**Comment by sixlettervariables** [comment]
@Ninir, matters not on the name.

**Comment by emrobi** [comment]
Any chance this is coming soon? I'm happy to test in my environment.

**Comment by ac360** [comment]
Working on it right now @emrobi  :)  Coming in V0.5

**Comment by connaryscott** [comment]
does this work in 5.1.0?   
```
serverless env set  --region us-east-1 --stage services --key http_proxy --value "${http_proxy}"
serverless env set  --region us-east-1 --stage services --key https_proxy --value "${http_proxy}"
```

other than the above, what else might I be missing if this can work?
