### ISSUE TITLE
Include/exclude packages is not working

### ISSUE THREAD

**Issue by marcelpanse** [serverless/serverless#2231]
This is a Bug Report

For bug reports:
- What went wrong?
  The deployable zip file contains every single dir in the folder tree
- What did you expect should have happened?
  Only folders should be included that obey the include/exclude rules

I tried multiple combinations of excludes only, includes only and per-project includes/excludes. Every time the entire folder and all subfolders end up in the zip file. 
- What was the config you used?
  https://gist.github.com/marcelpanse/6cc6149910f52e9b7e98724192d86779
- What stacktrace or error message from your provider did you see?
  N/A
## Additional Data
- **_Serverless Framework Version you're using**_:
  1.0.0-rc.2
- **_Operating System**_:
  OSX 10.11.6

**Comment by rowanu** [comment]
Related #2071 and #2194.

**Comment by mthenw** [comment]
Closing this one as this issue is already discussed in https://github.com/serverless/serverless/issues/2231.
