### ISSUE TITLE
Bug: UPDATE_ROLLBACK_FAILED due to S3 errors: The specified key does not exist

### ISSUE THREAD

**Issue by WooDzu** [serverless/serverless#2239]
# This is a Bug Report

I attempted to `sls deploy` 4 times, however, due to issues with the generated CloudFormation template (not relevant) the stack did not even get into `UPDATE_IN_PROGRESS` eg. never started updating. Upon each of these attempts a new ServerlessDeploymentBucket folder was created and one was removed by `lib/plugins/aws/deploy/lib/cleanupS3Bucket.js` routines.

After fixing the original CF template syntax issue, I attempted to deploy for the 5th time but the ServerlessDeploymentBucket folder which contained THE LAST WORKING .zip did not exist anymore since it was deleted.

My Serverless stack is now stuck in UPDATE_ROLLBACK_FAILED with the following errors:

![sls-rollback-failed](https://cloud.githubusercontent.com/assets/2228236/18947110/0afd99cc-8632-11e6-9621-f3a34106d802.png)
and I can't think of how to get it back and the right track. Since the ServerlessDeploymentBucket hasn't got versioning enabled I will need to figure out another way to restore the working zip and force to continue the rollback. I think I should be able to do that by generating the working zip by hand and looking onto the logs of AWS Config/CloudTrial for the name of the folder recycled/removed by serverless. Although it seems fixable it uncovers a nasty issue in Serverless.

* What went wrong?

Sls stack stuck in UPDATE_ROLLBACK_FAILED 

* What did you expect should have happened?

An update should have rolled back to a working version stored in S3 zip.

* What was the config you used?

(not relevant I think)

* To reproduce:

1. Make intentional syntax or reference error in CloudFormation template
2. Deploy it +4 times (CF should refuse the updates due to template errors)
3. Fix the CF template error
4. Deploy again

* What stacktrace or error message from your provider did you see?

```
api.flow_1          | Serverless: Packaging service...
api.flow_1          | Serverless: Removing old service versions...
api.flow_1          | Serverless: Uploading CloudFormation file to S3...
api.flow_1          | Serverless: Uploading service .zip file to S3...
api.flow_1          | Serverless: Updating Stack...
api.flow_1          |  
api.flow_1          |   Serverless Error ---------------------------------------
api.flow_1          |  
api.flow_1          |      Stack:arn:aws:cloudformation:eu-central-1:xxxxxxxxxxxxx:stack/xxxxxxxxxxxxx-test/969dbd20-7c1b-11e6-b292-503f2ad2e536
api.flow_1          |      is in UPDATE_ROLLBACK_FAILED state and can not be updated.
api.flow_1          |  
api.flow_1          |   Stack Trace --------------------------------------------
api.flow_1          |  
api.flow_1          | ServerlessError: Stack:arn:aws:cloudformation:eu-central-1:xxxxxxxxxxxxx:stack/xxxxxxxxxxx-test/969dbd20-7c1b-11e6-b292-503f2ad2e536 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
api.flow_1          |     at Response.<anonymous> (/api/node_modules/serverless/lib/plugins/aws/index.js:72:20)
api.flow_1          |     at Request.<anonymous> (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
api.flow_1          |     at Request.callListeners (/api/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
api.flow_1          |     at Request.emit (/api/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
api.flow_1          |     at Request.emit (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
api.flow_1          |     at Request.transition (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
api.flow_1          |     at AcceptorStateMachine.runTo (/api/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
api.flow_1          |     at /api/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
api.flow_1          |     at Request.<anonymous> (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
api.flow_1          |     at Request.<anonymous> (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
api.flow_1          |     at Request.callListeners (/api/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
api.flow_1          |     at Request.emit (/api/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
api.flow_1          |     at Request.emit (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
api.flow_1          |     at Request.transition (/api/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
api.flow_1          |     at AcceptorStateMachine.runTo (/api/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
api.flow_1          |     at /api/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
api.flow_1          |  
api.flow_1          |   Get Support --------------------------------------------
api.flow_1          |      Docs:          docs.serverless.com
api.flow_1          |      Bugs:          github.com/serverless/serverless/issues

```

## Workaround

After fixing the rollback I am going to add a few extras to ServerlessDeploymentBucket resource to enable versioning to avoid this issue in the future.

## Proposal

In a short therm plan the hardcoded constant `directoriesToKeepCount` should be raised to at least 20 or more.
Ultimately Sls could attempt to keep track of the last successful deployment and ensure that its corresponding zip is not deleted from ServerlessDeploymentBucket

## Additional Data

* ***Serverless Framework Version you're using***: RC2
* ***Operating System***: ubuntu
* ***Stack Trace***: (see above)
* ***Provider Error messages***: The specified key does not exist

**Comment by WooDzu** [comment]
Sorry for not checking the existing issues properly. It has already been reported in #2011
Please close it or leave as it might contains valuable details for somebody.

I am unable to restore the last working folder with zip and template since I can't find the folder name in CloudTrail logs, it will need to end up with removing and recreating the whole stack, which I was trying to avoid since it includes CloudFront distribution which takes over half an hour to deploy.

**Comment by andymac4182** [comment]
If you check the CloudFormation template in the UI you can see the location it is looking

**Comment by WooDzu** [comment]
Soo obvious :+1:  Thanks, I feel like an angry baby now :baby_bottle: after removing the stack

**Comment by andymac4182** [comment]
No worries. It takes a little time to get your head around AWS :)
