### ISSUE TITLE
Better displaying for command help

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2241]
# This is a Feature Proposal
## Description

Plugins can have nested sub-commands and can be even composed out of other plugins (see PR #2133 for the implementation about merging of commands / options).

However the old help displaying for a specific command (e.g. when you run `serverless deploy --help`) is not designed to display the whole variety of usage in a correct way. E.g. your options which might be only valid for nested commands.

Now all the commands are displayed followed by all available options.

Here's a screenshot which shows how the current implementation looks like:

![bildschirmfoto 2016-09-29 um 13 48 45](https://cloud.githubusercontent.com/assets/1606004/18972152/e1ccadd4-864c-11e6-8ead-41018bc4390b.png)

**Comment by tobyhede** [comment]
Any thoughts on what this should look like?

**Comment by pmuens** [comment]
Hey @tobyhede thanks for chiming in!

Not directly. Right now I think it would be sufficient if we simply display only the options which are available and not all who share the same `root` plugin.

**Comment by pmuens** [comment]
Closing since there've been a bunch of fixes to the `PluginManager` and the CLI in the past. Furthermore the current help screen is sufficient.
