### ISSUE TITLE
Docs link to tracking function is 404

### ISSUE THREAD

**Issue by ryansb** [serverless/serverless#2244]
# This is a Bug Report

## Description

In the docs, there's a mention of serverless [performing user tracking](https://serverless.com/framework/docs/usage-tracking/), and that the code for the tracking is available, but the link to the code is broken on the page. 

The correct link is: https://github.com/serverless/serverless/blob/master/lib/classes/Utils.js#L145

**Comment by akshatgoel** [comment]
I am new to the project and would love to contribute. I think I can start with this issue but not sure if linking to line number in code base is a future proof way to do this. Thoughts?

**Comment by mthenw** [comment]
Fixed in https://github.com/serverless/serverless/pull/2362.
