### ISSUE TITLE
Detect CI / CD systems

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2259]
# This is a Feature Proposal

## Description

It would be great to detect if the current system Serverless runs on is a CI / CD system as this makes it easier to understand the real world usage of Serverless.

We could implement this with the help of the environment variables the CI / CD systems export. For example Travis-CI exports a variable called `CI=true` (see: https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables).

**Comment by colbywhite** [comment]
Is this simply for tracking? Or is there something that could be done when in that mode? My initial thought was you could disable interactive input in CI mode, but SLS doesn't have any to my knowledge. Maybe just be more verbose in CI mode? But that may be presumptuous. 

For reference, [codeship](https://documentation.codeship.com/continuous-integration/set-environment-variables/) also uses `CI=true`.

**Comment by pmuens** [comment]
@colbywhite thanks for the comment.

The first idea was to just use this for tracking. But your proposal is also very interesting!

Yes interactivity is not available in Serverless to make work with CI / CD systems easier 👍

**Comment by pmuens** [comment]
Done with #2440 /cc @worldsoup
