### ISSUE TITLE
Support Resource only Services

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless#2267]
# Feature Proposal
## Description

There are use cases where developers might want to deploy a service that only contains Cloud Formation (CF) resources. Use cases for this include:
* A VPC service to be used by multiple services
* Many-Many SNS topics that cannot be owned by one particular service
* IoT services that trigger lambda's in other services rather than itself

Developers could deploy that via a custom CF template themselves. But they would have to write scripts to manage that deployment and support stages.

This should be a really easy feature to implement. Simply replace this block in `Service.js` line 61

``` js
if (!serverlessFile.functions) {
    throw new SError('"functions" property is missing in serverless.yml');
}
```
with
``` js
if (!serverlessFile.functions) {
    serverlessFile.function = [];
}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.2
* ***Operating System***: Mac OSX

**Comment by dougmoscrop** [comment]
This is an interesting take on the idea, because you could then have an 'infrastructure' service. You could even go as far as to have one service depend on another, which would maybe make the outputs of the one service available to the dependent service... I like it.

**Comment by Christoph-Schabert** [comment]
I like it too

**Comment by WooDzu** [comment]
In first instance before I tried serverless I had thought that this was actually it's main purpose and could split my long CF templates into readable pieces.

**Comment by johncmckim** [comment]
@flomotlik @pmuens @eahefnawy what do you think? I'm happy to implement this if you think it's a good idea.

**Comment by flomotlik** [comment]
@johncmckim yup sounds good to me

**Comment by johncmckim** [comment]
Thanks @flomotlik I'll create a PR 🔜

**Comment by kurtmaile** [comment]
An excellent idea!
