### ISSUE TITLE
Unrecognized CLI options are silently ignored

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#2282]
# This is a Bug Report
## Description

The Serverless command line appears to silently ignore unrecognized options, causing confusion and potentially dangerous results.

It should instead show an error message and abort the command when an unsupported/invalid option is specified.

Example case in #1787: Serverless silently ignores any --profile option, so deployment goes to the default profile, which could be any random AWS account.

**Comment by mthenw** [comment]
@eahefnawy answering your comment from https://github.com/serverless/serverless/issues/2550#issuecomment-256862189. IMHO we should provide additional delimiter for custom Serverless Variables. `--` similar to npm and other tools

```
serverless deploy -v -- --customOpt
```

That way we can validate cli params and support custom options for Serverless Variables.

**Comment by eahefnawy** [comment]
@mthenw oh yeaaah! nice one!!! 👍

**Comment by andymac4182** [comment]
This explains why I was having issues. @mthenw's solution would be a nice simple solution.

**Comment by medikoo** [comment]
Addressed with https://github.com/serverless/serverless/pull/9171

**Comment by kennu** [comment]
Awesome @medikoo :-)
