### ISSUE TITLE
Many documentation errors

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2307]
Many documentation pages have "serverless project ..." examples throwing off us newbies.

When people report those issues, respondents in other tickets direct them to https://github.com/serverless/serverless/blob/master/docs/guide

As of today, that link is a 404

What is the definitive source of current doco?

**Comment by rowanu** [comment]
https://serverless.com/framework/docs/

**Comment by chris-hailstorm** [comment]
Confirmed.  It would be helpful to retire some of the older docs from the web when you can -- they still turn up in a lot of Google searches.
