### ISSUE TITLE
Improve Tests for getCredentials

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2308]
## Description

Currently we're mocking the data returned by getCrednetials, which makes the tests irrelevant. We need to think of a way around that so that we can test credentials without exposing the actual keys.

[Check this PR for more info](https://github.com/serverless/serverless/pull/2294)

cc/ @flomotlik @pmuens

**Comment by pmuens** [comment]
#2820 added some great tests to cover this. Closing...
