### ISSUE TITLE
CLI should emit a shark attack on error

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#231]
`~~~~~~~~\o/~~~~~/\~~~~~~~`

**Comment by eahefnawy** [comment]
+1 :dancer:

**Comment by ac360** [comment]
This is absolutely going in.  @jwulf, you are brilliant, as always. :100:

**Comment by chopj** [comment]
+1

**Comment by eahefnawy** [comment]
Our awesome shark is now dead :sob: :sob:
