### ISSUE TITLE
serverless

### ISSUE THREAD

**Issue by AndreiD** [serverless/serverless#2311]
### something is not clear...

I was thinking that serverless means "without a server", but you're clearly using one :) 

so why the stupid name people ?

**Comment by flomotlik** [comment]
Its about Serverless Teams, not Serverless People. We discussed this actually today and will add a section for this into our README so everyone can understand.

**Comment by ac360** [comment]
I understand the confusion, @AndreiD.

"serverless" as a term is about as technically accurate as the “cloud” is technically accurate.

Servers do exist.  In fact, it takes a lot of servers to build a serverless computing platform, like AWS Lambda. 

But in our world, though servers exist, the developer does not have to think about them, and the term "serverless" encapsulates that experience perfectly.  

That experience is what we seek to provide with the Framework.  Hence the name.
