### ISSUE TITLE
Docs for serverless.yml

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2314]
There is no single place where user can find all possible fields and values. There is https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-nodejs/serverless.yml but it's pretty messy imho. Main problems:
- it's not clear how can I override provider setting
- it's not clear what are the defaults
- I guess it's intended for beginners but there are things like `resources` or `package.artifact` which are pretty advanced

Of course some values are provider specific and should be described in provider's docs.

**Comment by perl5punk** [comment]
I agree with the above comment, also it doesn't make it easy to validate whether or not there is a likely issue with code or where a syntax or usage is incorrect.

I've been attempting to tune a package and ensure I'm excluding node_modules which are only for development/tests but no matter what I've tried it doesn't exclude them.

It would be nice if it at least covered each of the sections, for example mentioned that include/exclude uses glob/minimatch without having to dig through the source code. That said, I don't believe exclude/include is working correctly.

**Comment by mthenw** [comment]
https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md
