### ISSUE TITLE
Speed up deploy time by uploading only changed files

### ISSUE THREAD

**Issue by polvoazul** [serverless/serverless#2325]
My deploy is starting to take too long. I have many dependencies that I cant do without, and it is a hassle that everytime i change one line I need to upload 30MB of stuff.

I suggest that we setup a folder inside a bucket for each service, and we use aws sync to upload only the deltas to the s3. Then, serverless would invoke a simple lambda, the "bootstraper", that would zip everything into one file to be consumed by cloudformation.
I guess this would speed up considerably our deploy times.

What do you guys think?

**Comment by dougmoscrop** [comment]
I'm just a user but I think this would be way too complicated. If there are changes to the plugin lifecylces/system that could facilitate a plugin that does some magic differential stuff, I think that's fair.

Alternatives:

- Split in to more granular functions / services if you can
- Try using WebPack?
- Do your deploys via a CI server (such as Travis or CircleCI) which is going to a faster upstream?

**Comment by pmuens** [comment]
Hey @polvoazul thanks for opening this up! 👍  💯 

@zaubernerd opened up a similar issue. Let's continue the discussion there!
