### ISSUE TITLE
Create .gitignore file in every template and add .serverless to it

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2343]
# This is a Feature Proposal

## Description

Having to add the .gitignore yourself after creating a project is tedious, we can simply do that. Adding the .serverless folder by default also makes sure no issues come up with it being commited.

Similar or dependent issues:
*

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by franckbrignoli** [comment]
Hey Florian,

Even if it's a very small feature, IMO it would make more sense to simply use the [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by nicka** [comment]
@flo I would be willing to add this! Do we have any other preffered stuff we want to ignore by default?

**Comment by pmuens** [comment]
Maybe some node_modules / meta stuff?

**Comment by horike37** [comment]
@pmuens 

What is “meta stuff”?

I want to suggest and PR as follows:

1. Get Node.gitignore
2. Add .serverless to it
3. Move it into .gitignore in the template

What do you think?

**Comment by pmuens** [comment]
@horike37 "meta stuff" is basically stuff package managers leave there (e.g. when using Python, Java, Scala etc.). Because `node_modules` only affects Node.js users.

**Comment by horike37** [comment]
Oh, that's right. Users are not only Node.js  user.
I think to  .gitignore add list as follow
```
# Node package directories
node_modules
jspm_packages

# Python distribution / packaging
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Java Package Files
*.jar
*.war
*.ear

# Serverless Framework directories
.serverless
```

**Comment by horike37** [comment]
I sent PR it. Please check it.

**Comment by nicka** [comment]
👍

**Comment by lynnaloo** [comment]
It looks like this is complete. Close issue?

**Comment by pmuens** [comment]
Thanks @lynnaloo ! Yes, that's done. Closing this now /cc @flomotlik
