### ISSUE TITLE
is serverless v1.0 not support RDS and node_module?

### ISSUE THREAD

**Issue by frengkys** [serverless/serverless#2357]
hey its really great to play with serverless v1.0,
 but i wonder is serverless is not support RDS mysql ? and 
node module ? 
if serverless support RDS, how to setting it up ?
thanks abudantly

For bug reports:
is serverless v1.0 just support DynamoDB database

**Comment by WooDzu** [comment]
Serverless relies on AWS sdk that is exposed to Lambda functions which (at least in JavaScript mode) does not provide a RDS/mysql driver. You will need to install one into node_modules as described here http://stackoverflow.com/questions/31809890/can-aws-lambda-connect-to-rds-mysql-database-and-update-the-database and use serverless to package it and upload with your code.

Please note that this is a great question for StackOverflow or Serverless forum. Github should be used for reporting issues

**Comment by frengkys** [comment]
ahhh thankyou and sory for wrong site to post
