### ISSUE TITLE
Failures in CF log, but no rollback after update to 1.0.2

### ISSUE THREAD

**Issue by bdruth** [serverless/serverless#2360]
# This is a (Bug Report / Feature Proposal)

## Description
Updated to 1.0.2 from 1.0.0-rc1, tried a deploy (no changes otherwise), verbose CF log output indicated failures from trying to delete (why!?!) S3 bucket, but no rollback was triggered?

For bug reports:
* What went wrong? _Serverless uploaded CF template that caused CF to attempt to delete my bucket_
* What did you expect should have happened? **No attempt to delete my bucket**
* What was the config you used?
```
functions:
  myFirst:
    handler: lib/my_first.myFirst
    events:
      - s3: mybucket
  mySecond:
    handler: lib/my_second.mySecond
  myThird:
    handler: lib/my_third.myThird
  myFourth:
    handler: lib/my_fourth.myFourth
```
* What stacktrace or error message from your provider did you see?
```
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - my-service-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MyFirstLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MySecondLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MyThirdLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MyFourthLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MySecondLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MyFourthLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MyFirstLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MyThirdLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - UPDATE_IN_PROGRESS - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - UPDATE_COMPLETE - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - my-service-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - DELETE_FAILED - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - DELETE_IN_PROGRESS - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - DELETE_FAILED - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - DELETE_IN_PROGRESS - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - DELETE_FAILED - AWS::S3::Bucket - S3BucketMybucket
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - my-service-dev
Serverless: Stack update finished...
```

Similar or dependent issues:
* didn't find any

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.2
* ***Operating System***: macOS Sierra
* ***Stack Trace***: n/a
* ***Provider Error messages***: see above

**Comment by bdruth** [comment]
It looks like between 1.0.0-rc1 and 1.0.2, the CF templates generated for the 'create' and 'update' stack have switched around their contents a bit.

**Comment by pmuens** [comment]
@bdruth thanks for reporting!

We've implemented a fix for the `monitorStack` method so that errors are reported in a better way (https://github.com/serverless/serverless/pull/2367).

Furthermore this issue might be related to https://github.com/serverless/serverless/issues/2364 (we've updated the way the deployment buckets work).

**Comment by bdruth** [comment]
Not sure I see that ... this isn't a deployment bucket.

**Comment by flomotlik** [comment]
@bdruth could you show us the S3Bucket config from the currently deployed CF template (you can get that from the console) and the one that will be deployed with the new template (`serverless deploy --noDeploy`)

**Comment by bdruth** [comment]
Working on this.

**Comment by flomotlik** [comment]
@bdruth this is almost certainly an issue with the bug that was fixed in https://github.com/serverless/serverless/pull/2385 Could you try installing from master and redeploying? I'll close for now and can reopen in case this comes up again.

**Comment by bdruth** [comment]
from 1.0.0-rc.1 https://gist.github.com/bdruth/e15c44c2667eea019c7b5f8e1bba6d12
from 1.0.2 https://gist.github.com/bdruth/10e0899902bf6d64652ff95af7d6186f

I will install from master as see what I can see.

**Comment by bdruth** [comment]
Most excellent, that seems to have fixed it, thank you!
