### ISSUE TITLE
Bug: v1.0 removal fails with bucket error

### ISSUE THREAD

**Issue by tobyhede** [serverless/serverless#2364]
# This is a Bug Report

## Description
Attempting to remove a function that was created with the last release candidate, the remove fails with the error:
```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
Serverless: Deployment failed!
Serverless Error
 ---------------------------------------
     An error occurred while provisioning your stack: ServerlessDeploymentBucket
     - The bucket you tried to delete is not empty.
```

## To reproduce

serverless create --template aws-nodejs
serverless deploy
serverless remove

## Additional Data

OS:                 darwin
Node Version:       4.3.2
Serverless Version: 1.0.0

**Comment by pmuens** [comment]
@tobyhede thanks for reporting! Yes, unfortunately this is a breaking change between RCs and v1.

To resolve this you need to remove it manually. After that if you redeploy with v1 you should be good to go.

Here's the PR which introduced that:
https://github.com/serverless/serverless/pull/2189

**Comment by tobyhede** [comment]
Cool, closing this.
