### ISSUE TITLE
New kinesis syntax not working

### ISSUE THREAD

**Issue by yeehaa123** [serverless/serverless#2365]
# This is a (Bug Report / Feature Proposal)
## Description

For bug reports:
- What went wrong?
  When I tried to convert my kinesis event mappings to the new syntax, like this:

`````` yaml

  extract:
    handler: extract/index.handler
    events:
      - stream:
          arn:
            Fn::GetAtt:
              - BookmarksStream
              - Arn

I got the following error "EventSourceArn.split is not a function"

Looking at the source code, I get the impression that this feature simply has not been implemented yet. However, it is already referenced in the docs here:

https://serverless.com/framework/docs/providers/aws/events/streams/

* What did you expect should have happened?

The cloudformation GetAtt should have resolved into a valid arn

* What was the config you used?

```yaml

  extract:
    handler: extract/index.handler
    events:
      - stream:
          arn:
            Fn::GetAtt:
              - BookmarksStream
              - Arn

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.0.2 

* ***Operating System***:

linux (kubuntu)
* ***Stack Trace***:

TypeError: EventSourceArn.split is not a function
    at functionObj.events.forEach.event (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:82:47)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:20:28)
    at Array.forEach (native)
    at AwsCompileStreamEvents.compileStreamEvents (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/lib/classes/PluginManager.js:151:50)
    at tryCatcher (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/yeehaa/.nvm/versions/node/v6.8.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)

* ***Provider Error messages***:

EventSourceArn.split is not a function
``````

**Comment by pmuens** [comment]
Hey @yeehaa123 thanks for reaching out!
This is definitely a bug.

The solution right now is to only use ARNs instead of using `Fn::GetAtt`.

We'll look into this!

**Comment by yeehaa123** [comment]
Hi Philipp,


Thanks for the quick reply.

yes, I already went back to that. Let me know, if you need help with solving this. I could attempt to make the PR if you give me a short hint on how to implement it (or give me a link to another place in the code where you resolve the FN:GetAtt...

Thanks for all the awesome work. This project is amazing!

JH

**Comment by kurtmaile** [comment]
Hi I got this issue as well - just to clarify, when you say 'The solution right now is to only use ARNs' can you elaborate please with example?

thanks!

**Comment by pmuens** [comment]
@kurtmaile Here's the link on how to setup streams with ARNs:
https://serverless.com/framework/docs/providers/aws/events/streams/

@yeehaa123 Thanks for offering help here! Let me shed some more light into this bug:

The bug is a problem with the cause that we treat DynamoDB and Kinesis streams equally. For the CloudFormation we need the type (`dynamodb` or `kinesis` and the name of the stream). That's where it breaks as we're currently extracting that information from the ARN (and cannot access it from the `Fn::GetAtt`).

**Comment by yeehaa123** [comment]
@pmuens okay, got it. But I'm not sure how to proceed here. As far as I can see, there are two possible solutions:

1. The stream type needs to be passed in explicitly like this:

`yaml
- stream:
    type: dynamodb
    arn: ...

or this

`yaml
- db-stream:
    arn:...

2. The ARN gets somehow resolved earlier. I'm not quite sure if that's even possible, because cloudformation then needs to be called twice somehow.

Obviously, 2 seems the better option here, but I am unsure how to approach this.

The fact that db-streams need the timestamp at the end does not make things easier either....

**Comment by pmuens** [comment]
@yeehaa123 thanks for getting back. Yes, those are basically two valid options. It all comes down to the naming of the `ResourceLogicalId`. We don't need the type or the name of the string for the stream itself. Only for the resource name.

@eahefnawy will tackle this bug so he might have an idea how we can proceed here. Personally I'd like to keep it as it is and let Serverless auto detect the stream. Otherwise we might have a problem with the string syntax where we only provide the ARN and don't have a way to pass the type.

**Comment by yeehaa123** [comment]
@pmuens Thanks!

@eahefnawy let me know if you need any feedback on this

**Comment by erikerikson** [comment]
The docs at https://serverless.com/framework/docs/providers/aws/events/streams/ continue to declare that the object notation can be used:

```
functions:
  compute:
    handler: handler.compute
    events:
      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1901T00:00:00.000
      - stream:
          arn:
            Fn::GetAtt:
              - MyKinesisStream
              - Arn
```

**Comment by pmuens** [comment]
Thanks @erikerikson.

Yes, this is still something which needs to be fixed (docs and code) ASAP!

**Comment by fleeco** [comment]
Ah ha!  This one was a bit painful ha.  Updating the documentation would make me feel like I'm not going insane :)

My (super hoodrat) workaround was to create a custom variable with the first part of my kinesis shard ARN, then prepend it with the stage. (and make sure the streams are also named that way)

Works, but going to take a stab at doing a PR :)

**Comment by pmuens** [comment]
Just PRd a tiny doc update which removes the `Fn::GetAtt` usage. https://github.com/serverless/serverless/pull/2962

**Comment by erikerikson** [comment]
Thanks @pmuens.  I still pine for this (e.g. `Fn::ImportValue`).  😄

**Comment by ryansb** [comment]
Also hitting this. The logical name could be, instead of `function+type+streamName` could be `function+type+table/stream` where table/stream is either:

1. The stream name (extracted with regexes as-is now)
2. The logical table or stream ID grabbed from the `Fn::GetAtt` statement
3. In the case of `Fn::ImportValue` the name of the variable in the ImportValue statement

That way, all the ways of specifying a stream in CFN (hardcoded, GetAtt, and ImportValue) can be properly named. Right now, the naive naming is [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js#L206-L212).

**Comment by ryansb** [comment]
Here's a sample patch:

```{diff}
diff --git a/lib/plugins/aws/deploy/compile/events/stream/index.js b/lib/plugins/aws/deploy/compile/events/stream/index.js
index d18b53f..f0969b7 100644
--- a/lib/plugins/aws/deploy/compile/events/stream/index.js
+++ b/lib/plugins/aws/deploy/compile/events/stream/index.js
@@ -78,8 +78,16 @@ class AwsCompileStreamEvents {
                 .Error(errorMessage);
             }
 
-            const streamType = EventSourceArn.split(':')[2];
-            const streamName = EventSourceArn.split('/')[1];
+            const streamType = event.stream.type || EventSourceArn.split(':')[2];
+            if (typeof EventSourceArn === 'string') {
+                const streamName = EventSourceArn.split('/')[1];
+                // we need to add quotes to the string if it's not a GetAtt or other expression
+                EventSourceArn = `"${EventSourceArn}"`;
+            } else if (EventSourceArn['Fn::GetAtt']) {
+                const streamName = EventSourceArn['Fn::GetAtt'][0];
+            } else if (EventSourceArn['Fn::ImportValue']) {
+                const streamName = EventSourceArn['Fn::ImportValue'];
+            }
 
             const lambdaLogicalId = this.provider.naming
               .getLambdaLogicalId(functionName);
@@ -99,7 +107,7 @@ class AwsCompileStreamEvents {
                 "DependsOn": ${dependsOn},
                 "Properties": {
                   "BatchSize": ${BatchSize},
-                  "EventSourceArn": "${EventSourceArn}",
+                  "EventSourceArn": ${EventSourceArn},
                   "FunctionName": {
                     "Fn::GetAtt": [
                       "${lambdaLogicalId}",
```
