### ISSUE TITLE
APIG 'Model'

### ISSUE THREAD

**Issue by kurtmaile** [serverless/serverless#2376]
# This is a Feature Proposal
## Description

For feature proposals:

Ability to include JSON schema 'models' for provisioning an API, and define individual endpoint requests & responses with a selected Model. 

As an individual model (e.g 'Customer) can be reused across multiple endpoints (e.g getCustomer, searchCustomers, updateCustomer, ), one file (e.g serverless-models.json - dont think APIG supports YAML model definitions yet) should contain _all_ unique model resources for the API (of the serverless service), and then each can be referred in the serverless.yml file

response:
   model: Customer

There is wider discussion on Swagger, but this is in a holding pattern indefinitely.  Models are very important to be integrated ASAP, even if the approach shifts with wider Swagger decision.
## Additional Data

Cheers

**Comment by 4ossiblellc** [comment]
I assume that Request or Response Models are not supported in version 1.6.1 or above yet.

**Comment by pmuens** [comment]
Hey @4ossiblellc you can use the request / response configuration with the `lambda` integration type: https://serverless.com/framework/docs/providers/aws/events/apigateway#lambda-integration

**Comment by pmuens** [comment]
Closing this issue since there are plugins available which should resolve the problem:

- https://github.com/9cookies/serverless-aws-documentation
- https://www.npmjs.com/package/serverless-plugin-model
