### ISSUE TITLE
Cannot override AuthorizerResultTtlInSeconds any more

### ISSUE THREAD

**Issue by WooDzu** [serverless/serverless#2378]
# This is a Bug Report

## Description

I have been using resource override to disable authorizer's cache completely:

```yaml
resources:
  Resources:
    PrivateAuthorizeUserApiGatewayAuthorizer:
      Properties:
        AuthorizerResultTtlInSeconds: 0
```

It no longer works and generates the following:

cloudformation-template-create-stack.json:

```json
{
    "PrivateAuthorizeUserApiGatewayAuthorizer": {
      "Properties": {
        "AuthorizerResultTtlInSeconds": 0
      }
    }
}
```
cloudformation-template-update-stack.json

```json
{
    "PrivateAuthorizeUserApiGatewayAuthorizer": {
      "Properties": {
        "AuthorizerResultTtlInSeconds": 300,
        "AuthorizerUri": "REDACTED",
        "IdentitySource": "method.request.header.Cookie",
        "Name": "privateAuthorizeUser",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "Type": "TOKEN"
      },
      "Type": "AWS::ApiGateway::Authorizer"
    }
}
```

**NOTE:** Additionally I noticed that `cloudformation-template-create-stack.json` is now full of resources where previously it only created `ServerlessDeploymentBucket`. Is this intentional or sign of a broader issue?

For bug reports:
* What went wrong? Resource property overridden property in `cloudformation-template-create-stack.json` in stead of `cloudformation-template-update-stack.json`
* What did you expect should have happened? Resource property should be overridden in `cloudformation-template-update-stack.json`
* What was the config you used? See above.
* What stacktrace or error message from your provider did you see? None, all smoothly deployed

Similar or dependent issues:
* not found

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.2#master
* ***Operating System***: Ubuntu 16
* ***Stack Trace***: none
* ***Provider Error messages***: none

**Comment by eahefnawy** [comment]
@WooDzu thanks for reporting...this is known bug ... [check this comment for more info](https://github.com/serverless/serverless/issues/2359#issuecomment-253775785)

Fix coming soon 😊

**Comment by flomotlik** [comment]
Closing as its a duplicate and will be resolved.
