### ISSUE TITLE
Rely on .gitignore / .npmignore to exclude files from npm package

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2381]
# This is a Feature Proposal

## Description

Right now we rely on the `files` array in `pacakge.json` to ensure that all relevant files are included in the published npm package. While this reduces the files size dramatically it also introduces the problem that we might miss something there and a release will be broken (even with our release checklist in place).

IMHO a better way would be to include everything by default and filter out files / folders which should not be included with `.npmignore` / `.gitignore`.

**Comment by mthenw** [comment]
I personally like current approach because we are 100% what is sent to NPM.

**Comment by pmuens** [comment]
Closing this one as I agree that whitelisting makes more sense for us after rethinking it a little bit.
