### ISSUE TITLE
Extend monitorStack method with status array so that CLI correctly exits in verbose mode

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2382]
# This is a Feature Proposal
## Description
#2367 introduced a fix for a critical bug where an error was not thrown if the stack gets into a `*_FAILED` status.

If the user uses the `--verbose` flag Serverless will show all the CloudFormation stack statuses even if the stack fails and exits after the stack get's into a "finsihed" state and then throws the first error encountered. However the CLI will only exit if the status is something like `*_ROLLBACK_COMPLETE`. We should extend this in a way that it's an array of statuses where the CLI should exit so that it won't hang if it got into e.g. a `UPDATE_ROLLBACK_FAILED` status.

**Comment by flomotlik** [comment]
@pmuens is this still a bug or only accidentally open?

**Comment by pmuens** [comment]
This bug is still there. I'll work on it soon.

**Comment by pmuens** [comment]
Should be fixes in the latest release.
