### ISSUE TITLE
Deploying a Lambda with "builder": false ZIPs up the wrong directory

### ISSUE THREAD

**Issue by pwagener** [serverless/serverless#239]
To reproduce this problem with v1.3.3 on OS X (Yosemite) and NodeJS v0.12.7:

1.  Create a new project:  `jaws project create`
2.  Create a new module in that project `jaws module create widgets make`
3.  Edit `aws_modules/widgets/make/awsm.json` and change the `lambda.package.optimize.builder` from `"browserify"` to `false`.
4.  Deploy the `widgets/make` Lambda via `jaws dash`
5.  Test the Lambda via the AWS Console

The result is an error like:

```
{
  "errorMessage": "Cannot find module 'aws_modules/widgets/make/handler'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._resolveFilename (module.js:338:15)",
    "Function.Module._load (module.js:280:25)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)"
  ]
}
```

----
Work-around:

If you look through the `jaws dash`  output, you'll see where it generated the `package.zip` file.  Unzipping that file, you'll see the structure of the ZIP is wrong:

```
$ unzip package.zip 
Archive:  package.zip
  inflating: node_modules/.env       
  inflating: node_modules/.gitignore  
  inflating: node_modules/README.md  
  inflating: node_modules/admin.env  
  inflating: node_modules/jaws.json  
  inflating: node_modules/package.json  
  inflating: node_modules/aws_modules/widgets/awsm.json  
  inflating: node_modules/aws_modules/widgets/make/awsm.json  
  inflating: node_modules/aws_modules/widgets/make/event.json  
  inflating: node_modules/aws_modules/widgets/make/handler.js  
  inflating: node_modules/aws_modules/widgets/make/index.js  
  inflating: node_modules/cloudformation/dev/us-east-1/lambdas-cf.json  
  inflating: node_modules/cloudformation/dev/us-east-1/resources-cf.json  
  inflating: node_modules/node_modules/jaws-core-js/.npmignore  
  inflating: node_modules/node_modules/jaws-core-js/README.md  
  inflating: node_modules/node_modules/jaws-core-js/awsm.json  
... and so on ...
```

The work-around is to zip up the contents of the `node_modules` directory and deploy that instead.

**Comment by Giaco9** [comment]
+1!
There is an automated way for do this?

**Comment by joostfarla** [comment]
Just submitted a PR which fixes this!

**Comment by kennu** [comment]
I ran into this same issue just now when I tried to disable optimization for a module.
