### ISSUE TITLE
Looking For A React Rockstar For The New JAWS Dashboard

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#240]
The difference between JAWS and traditional frameworks is that JAWS has config files in separate folders, whereas traditional frameworks are able to centralize configuration information (e.g., routes.js), which is more convenient.  The reason JAWS works the way it does is because Lambda is deployed and isolated at the function level and not the application level.  Therefore, we need to have separate files for each Lambda.  We could create those files dynamically from single, centralized files, but Lambda development comes in many different shapes and forms and we don't want to do too much "magic", or we risk alienating a lot of Lambda use-cases.

However, what we can do is offer a slick dashboard that centralizes information for developers.  We've been trying to build this in the JAWS command line interface, but command line interfaces are limited.  They are a bit buggy across OS's and there just isn't much room.  Instead, we'd like to ship a dashboard with JAWS that runs in the browser.

The new JAWS dashboard will be powered by a local server and it should show up when someone runs `jaws dash`.  By running locally, it will have access to your JAWS project files.  Clicking features on the UI can affect your project files.

We'd like to build this new web dashboard in tools the community is familiar with, so that everyone can add the features they want.  React has had positive hype for a while now, [and it's still strong](https://twitter.com/tjholowaychuk/status/653645678367801344).  So, we'd like to build the new JAWS Dashboard in React.

The problem is, I'm not a React developer (I'm still hanging on to Angular v1).  Neither is @doapp-ryanp.  We're looking for someone who is a decent React developer to set up the boilerplate for this dashboard and incorporate best practices from the beginning, which the community can extend.

Here are the requirements so far: 

* **Single page application architecture**
* **Architect the first page** - We need one page that lays down a foundation which we can extend and replicate for future pages.  This page will feature a summary of your project and a list your project's API Gateway Endpoints and Lambdas.
* **Router mechanism for future pages**
* **Koa Powered Back-end** - We can build this.  It will feature an API to edit your project files.
* **Keep It Simple** - Use easy-to-understand technologies so that the JAWS community can easily understand and contribute.

Eventually, we'll expand this Dashboard to feature all types of neat testing and monitoring widgets.  For now, we're just looking for someone who can get us started in the right direction :)

Please respond here if you're interested.  I'll open up a branch next week for this.

**Comment by ac360** [comment]
@sosana @mcwhittemore @mbreton @remicastaing

**Comment by eahefnawy** [comment]
interesting! why not have a native app powered by [electron](http://electron.atom.io) and maybe [photon](http://photonkit.com)?

It seems that the functionality we need are more "native".

**Comment by ac360** [comment]
Interesting @eahefnawy.  That tech is super cool but I'm not sure if it will be adopted by the community as much as a React browser-based app would.

**Comment by SOSANA** [comment]
Regarding browser based react, wondering if we should do a basic app without a flux implantation. So many options for flux. The hottest implentation of flux changes by the week. I personally like reflux but right now redux is what all the cool kids are using. Mean while relay and falcor looks promising.

**Comment by eahefnawy** [comment]
@ac360 oh yeah valid point.

**Comment by mcwhittemore** [comment]
@ac360 So the first thing you are looking for is a single page that displays a bunch of data for lambda functions? Is this a simple list of your functions? What kind of info would we want to show?

We should probs do this in its own repo and let the CLI install it.

@SOSANA I think we should use a flux based setup. Stores can be a good way to let outside devs interact with the data of the application. This means that the core team can make sure all the data ever wanted is accessible via stores and extension builders can focus on better ways to show that data. Flux frameworks are always coming and going though... so we'd most likely want to pick that most basic option to help limit the pain of people thinking their pet-flux implementation will solve this projects problems. Does that seem right to you?

**Comment by ac360** [comment]
@SOSANA I dunno this is your area of expertise :)

@mcwhittemore I'm going to make a mock-up this weekend with minimum requirements for the first page.  Keep in mind, the first page may end up to be the most complicated page in the application.  I'm sure the feature list will grow, so it needs to be architected in a very extendable way.  Your opinion on Stores sounds good.  ATM, I think this is going to be eventually included in JAWS core, but everything in JAWS is being refactored as a plugin, and this dashboard will also be a plugin.  This allows people to replace it with something custom, if they want.

In the interim, let's settle on the basic scaffolding and the tools involved.  I can't speak to Flux/Reflux/Redux because I am not familiar with them, so I need your expert opinions.  What is simple, lightweight, popular and user-friendly for everyone?

[I've created a new repo for the Dashboard](https://github.com/jaws-framework/jaws-dashboard)  Eventually, this will get merged into jaws core.  But let's use this separate repo for now.  If anyone wants to kick off the process, please submit PRs.  Please try to coordinate efforts in this thread so that there is no overlap.

**Current TODO:**  Create a full-stack app with Koa on the back-end and React on the front-end.  Don't worry about the Koa back-end, focus on the best boilerplate for the front-end via React.  Whatever is simple, lightweight, popular and user-friendly for everyone.

Also, anyone recommend a lightweight UI framework?  I've used Bootstrap.  How is Bootstrap 4?  Any new options?

**Comment by marclar** [comment]
I've had good experiences with these two:

- React boilerplate: https://github.com/erikras/react-redux-universal-hot-example 
- UI framework: http://semantic-ui.com/

**Comment by remicastaing** [comment]
@ac360, I have absolutely no experience with react. I can help out on the back end (I took a look at koa last year, but stayed with express).

**Comment by chrillo** [comment]
There is a react bootstrap implementation https://react-bootstrap.github.io/components.html as well as a material design framework that I quite like http://material-ui.com/#/components/cards (might be too opionated in terms of design though). 

In terms of flux / data flow, I highly recommend https://github.com/rackt/redux it seems to be the clear winner out of the many flux implementations that are out there and is the most likely to stay. For anyone interested in the topic these 2 javascript jabber episodes https://devchat.tv/js-jabber/181-jsj-the-evolution-of-flux-libraries-with-andrew-clark-and-dan-abramov & https://devchat.tv/js-jabber/179-jsj-redux-and-react-with-dan-abramov are good sources of information

**Comment by jakelodwick** [comment]
Are React Rockstars the only option? I know a React Folk Singer with incredible stage presence...

**Comment by mrjjwright** [comment]
An alternative to Redux and Flux in general is MObservable which has react integration as well.  It's dead simple and powerful and creates great React performance out of the box.  Redux is awesome too but MObservable is just straightforward simple code goodness.

https://github.com/mweststrate/mobservable

**Comment by kevinold** [comment]
@ac360 I'd love to help. I prefer a React and Redux setup. Let me know how I can get involved

**Comment by ac360** [comment]
@kevinold @mrjjwright @chrillo @jakelodwick @marclar @mcwhittemore @SOSANA 

Let's go with **React** and **Redux**.  If you would like to do a PR with the initial scaffolding, please say so in this thread.  As of right now, the opportunity is open to anyone...

**Comment by kevinold** [comment]
@ac360 Absolutely, I'll get the PR ready in the next few days and will see if I can get the local server read from some mock file system objects.  At the least I can get us a basic React UI setup powered by Redux.

**Comment by ac360** [comment]
@kevinold Awesome!  This weekend, I'm going to prepare some mock-ups for the dashboard.  These will be posted in the Issues section of this repo for comment.

**Comment by shortjared** [comment]
To weigh in on this @eahefnawy raised http://electron.atom.io/ and http://photonkit.com as options. It might be worth re-evaluating those options. It seems like to some extent this bypasses needing to maintain a separate node backend and react frontend as your Redux actions would be directly responsible for filesystem ops. Global state would be fairly easy to maintain with a Redux store.

**Comment by shortjared** [comment]
To weigh in on this... @eahefnawy raised http://electron.atom.io/ and http://photonkit.com as options. I was rethinking this area and also kept coming back to those being a solid potential option. It might be worth re-evaluating those options. It seems like to some extent this bypasses needing to maintain a separate node backend and react frontend as your Redux actions would be directly responsible for filesystem ops. Global state would be fairly easy to maintain with a Redux store.

**Comment by shortjared** [comment]
To weigh in on this... @eahefnawy raised http://electron.atom.io/ and http://photonkit.com as options. I was giving some thought to this area and also kept coming back to those being a solid potential option. It might be worth re-evaluating those options. https://github.com/kitematic/kitematic is a beautiful example of a utility (Docker CLI) wrapping app using Electron & ReactJS.

It seems this bypasses needing to maintain a separate nodejs backend process and ReactJS frontend. Your Redux actions would be directly responsible for filesystem ops and cutout the middleman. Global state would be fairly easy to maintain with a Redux store, cutting out some weirdness that could happen between a more distinct backend server process and localhost GUI. It also seems like it would simplify the whole installation process for users (although I don't see that being quite as huge of a problem since the audience is very much developers).

The biggest downsides I see is that it would make it harder to port to/have a centrally hosted solution that would orchestrate a larger organizations JAWS apps. The base React Components, however, would still be largely reusable.

**Comment by ac360** [comment]
@shortjared Remind me to discuss this with you when we next chat.  Let's dig into how this could work.

**Comment by doapp-ryanp** [comment]
Maybe this is obvious, but when `jaws dash` is run, a node http server listening on localhost (port TBD and configurable by user) should be launched.  The server side node code needs to interface with JAWS via the node bindings - not via the CLI (so dont call the jaws cli from the node server to do thigns like lambda deploy, call the JS methods directly).  

I think the `jaws dash` should be modeled after [`fish_config`](http://fishshell.com/docs/current/commands.html#fish_config).  Its actually what gave me the idea to do a localhost web based `jaws dash`.

I think using websockets to give realtime feedback is also a requirement.

Any work done on this should be done in the v1.4 branch correct @ac360 ?  Doing it against master would be wasting time since there is a big internal refactor in the upcoming v1.4.

**Comment by kevinold** [comment]
I've submitted a PR for this https://github.com/jaws-framework/jaws-dashboard/pull/3 with an initial React, Redux scaffold.

I've left basic interactions from the generator this is from for initial reference.  Once we have a design for the dashboard, that can be updated into index.html.  A suggestion I have is to use the SB Admin 2 template (http://startbootstrap.com/template-overviews/sb-admin-2/)

**Comment by eahefnawy** [comment]
@kevinold awesome PR! But just to clear things up, where does Atom fit into this? Is that some sort of an extension to Atom? If that's the case why not just create an Atom package?

Using your approach or using an Atom package makes total sense, considering that our dashboard is **project specific**, and it might be hard to build a stand alone Electron app to manage JAWS projects. Atom already gives us complete realtime access to project files.

With an Atom package, we could just open our JAWS project in Atom and fire up our package, which would include a complete UI for managing this project's lambdas, and any other project specific functionality (env vars...run locally...etc). Of course a big disadvantage is that we'll tie our users to Atom, which is not very cool!

Would love to get your thoughts on this! Maybe this is the approach you're taking and I'm just not aware of it?! ;)

**Comment by kevinold** [comment]
@eahefnawy Hey!  Sorry, see this PR: https://github.com/jaws-framework/jaws-dashboard/pull/4  After speaking with @ac360 I realized there was a need for an Electron based approach.  We reverted my original PR and have this new one applied which is a customized electron-react-boilerplate so that we can have React, Redux and Electron out of the gate!  Give it test using the README instructions.

**Comment by eahefnawy** [comment]
Yep that's actually the PR I'm talking about! But never mind :) I was stupidly looking at this repo instead: [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) 
It references Atom in it's README file, hence my confusion.

I just tested it. Awesome work there :+1:

**Comment by davidjnelson** [comment]
@ac360 Hey Austen - were you ever able to post the mockups?  Thanks!
