### ISSUE TITLE
CloudFormation error not detected during deploy

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#2401]
# This is a Bug Report
## Description

I have some custom resources defined but deployment always gets stuck on "Checking Stack create progress..." and is hanging indefinitely. Finally it crossed my mind to look to CF console and the stack creation failed but Serverless obviously didn't find it.

Here are screenshots from the console:

<img width="1390" alt="stack_detail" src="https://cloud.githubusercontent.com/assets/215660/19412823/3184600a-931e-11e6-93e7-d00849f57c33.png">

<img width="1364" alt="stack_detail" src="https://cloud.githubusercontent.com/assets/215660/19412825/508ea19a-931e-11e6-945b-a5658b28eb3e.png">

And one from my terminal:

<img width="338" alt="1__jakub_jakubs-macbook-pro-2____keboola_dp__zsh_" src="https://cloud.githubusercontent.com/assets/215660/19412841/99307374-931e-11e6-9aa7-2174fdefb7d1.png">
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: macOS 10.12
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by RayBenefield** [comment]
Same problem that I have it hangs and doesn't detect when the CF stack has completed.

 - ***Serverless Framework Version you're using:*** 1.0.2
 - ***Operating System:*** OS X El Capitan 10.11.6
 - ***Template***: aws-nodejs

I just started a new project like 20 minutes ago.

**Comment by jordanmack** [comment]
I hit this problem a couple times also. CloudFormation sometimes just messes up. When Serverless can't recover, the quick fix is to just login and delete the failed CloudFormation stack manually. The next time you deploy it will recreate everything.

**Comment by marcelocbf** [comment]
I was coming here to report just that. In my situation, I had a problem with my Cloudformation template and it failed the first time. I checked the console fixed the problem and tried to redeploy the resources which failed early with

 
```
 Serverless: Packaging service...
  
   Serverless Error ---------------------------------------
  
      The specified bucket does not exist
  
   Get Support --------------------------------------------
      Docs:          docs.serverless.com
      Bugs:          github.com/serverless/serverless/issues
  
   Your Environment Infomation -----------------------------
      OS:                 darwin
      Node Version:       4.4.3
      Serverless Version: 1.0.2

``` 

I "believe" the problem happens with the code below on the createStack.js file, as the .describeStackResources() call in this case returns the associated resources even for a deleted (rolled back) stack as the docs says. So, as there is no check for the resources.ResourceStatus which, in my case, returned DELETE_COMPLETE it returns 'alreadyCreated' and it probably fails later on when it needs the ServerlessDeploymentBucket

```
  createStack() {
    const stackName = ${this.serverless.service.service}-${this.options.stage};

    this.serverless.service.provider
      .compiledCloudFormationTemplate = this.loadCoreCloudFormationTemplate();

    return BbPromise.bind(this)
      // always write the template to disk, whether we are deploying or not
      .then(this.writeCreateTemplateToDisk)
      .then(() => {
        if (this.options.noDeploy) {
          return BbPromise.resolve();
        }

        return this.sdk.request('CloudFormation',
          'describeStackResources',
          { StackName: stackName },
          this.options.stage,
          this.options.region)
          .then(() => BbPromise.resolve('alreadyCreated'))
          .catch(e => {
            if (e.message.indexOf('does not exist') > -1) {
              return BbPromise.bind(this)
                .then(this.create);
            }

            throw new this.serverless.classes.Error(e);
          });
      });
  },

```

**Comment by RayBenefield** [comment]
> I hit this problem a couple times also. CloudFormation sometimes just messes up. When Serverless can't recover, the quick fix is to just login and delete the failed CloudFormation stack manually. The next time you deploy it will recreate everything.

In all of my cases where it failed, the stack was actually updated successfully, so instead, I just wait a couple seconds and manually check if it is done. Not really a major problem, but still a drop in productivity.

**Comment by pmuens** [comment]
Hey altogether, we've pushed a fix recently which should resolve this.

Could you install the latest Serverless release and try again? Thanks!

**Comment by mthenw** [comment]
@JakubMatejka let us know if it's still an issue. Closing for now.
