### ISSUE TITLE
Where does "sls info" data come from after lambdas have been deleted?

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2408]
I found "sls remove" couldn't do its work because I had manual IAM policies set up that I needed to remove manually (that's fine).  Then I decided to manually remove the lambdas, CW logs / events, and IAM roles / policies -- harmless in my disposable experiment environment.

Now when I run "sls info", I still get info about the old functions:

```
$ sls info --stage dev

Service Information
service: xxxxx
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  xxxxx-dev-fire: arn:aws:lambda:us-east-1:455463828340:function:xxxxx-dev-fire
  xxxxx-dev-run: arn:aws:lambda:us-east-1:455463828340:function:xxxxx-dev-run
```

These functions no longer exist -- I manually deleted them.

Where does "sls info" get this data, and how I can clean that as well?

Thanks

**Comment by rowanu** [comment]
The info comes from the CloudFormation stack that is created to deploy the services resources. Ideally you shouldn't be editing resources created by Serverless manually. You'll probably need to delete/redeploy your service to see the changes (assuming you've removed the functions from your `serverless.yml` too).
