### ISSUE TITLE
Support Bitcoin for donation!

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#241]
Your donation page through Square doesn't seem to support cards from certain countries. In my case: Egypt!

I think Bitcoin would be more suitable for a global community of developer! :)

**Comment by ac360** [comment]
@eahefnawy Do you have any recommendations for great Bitcoin donation tools?  I'm going to look into Coinbase.

**Comment by eahefnawy** [comment]
Coinbase is all you need! Just get the QR code image of your address, and put it README, and you're golden!

You'll be able to withdraw your cash from Coinbase easily (since you're in the US)
