### ISSUE TITLE
Implicit wildcard added to exclude 

### ISSUE THREAD

**Issue by jsnowacki** [serverless/serverless#2414]
# This is a Bug Report / Feature Proposal

Not sure if this is a bug or a feature, but for sure it is a bit counterintuitive behaviour.
## Description

I have data folder I wanted to exclude form the package, so I defined exclude as follows:

``` yaml
exclude:
    - data
```
- What went wrong?
  - This works as `data*` (or even `*data*`, I haven't tried it that much) and excludes all the files that contains string `data`, even from places like requirements. 
- What did you expect should have happened?
  - At most it should exclude all the files or folders that match exactly `data`. If this was a design assumption, this should be documented better, though, implicit wildcards are not that typical.
- What was the config you used?
  - As above
- What stacktrace or error message from your provider did you see?
  - Not related with the exclusion directly, but I had files missing in the requirements, which took some time to track down.
## Additional Data
- **_Serverless Framework Version you're using**_:
  1.0.0-rc.2
- **_Operating System**_:
  Windows 10 and Ubuntu 14.04 LTE

**Comment by mthenw** [comment]
Closing this one as it's already discussed in https://github.com/serverless/serverless/issues/2414.
