### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2415]
https://serverless.com/framework/docs/framework-statistics/

All relative links pointing to repo are 404. 

@DavidWells @pmuens

**Comment by mthenw** [comment]
@DavidWells should we use relative or absolute links in `.md`?

**Comment by pmuens** [comment]
While this makes total sense to not introduce a separate build step to resolve the paths I still find the replacement of relative paths with absolute paths ugly.

We should keep an eye on this issue while going forward and maybe introduce a separate build / resolve step if we keep adding those kind of links.

/cc @DavidWells
