### ISSUE TITLE
Parameterize API Gateway HTTP method on `jaws module create`

### ISSUE THREAD

**Issue by chrisbaldauf** [serverless/serverless#242]
Currently, when the `jaws module create` command is run, the API Gateway HTTP method is hard coded to "[GET](https://github.com/jaws-framework/JAWS/blob/master/lib/commands/module_create.js#L177)". I'd like to add a `--method` parameter to the module_create command that allows the user to specify one of the supported API Gateway methods (currently DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT). 

Example usage: `jaws module create foo bar --method POST`

I have some other ideas for additional parameters to the module create method, but I'd like to start here to get to know the codebase. 

If you'd be open to such a feature, I'd be happy to start working on a PR.

**Comment by eahefnawy** [comment]
our commands are getting really complex, we'd like to minimize the options as much as possible. So to make a POST enabled function, `s-function.json` should be fine.

Thanks for suggesting, and really sorry for the delayed reply :)
