### ISSUE TITLE
Can't deploy new function using sls deploy function -f fname before run sls deploy

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#2437]
# This is a (Bug Report)

## Description

when i run `sls deploy -v` i got following error

```
Serverless Error ---------------------------------------

     Connection timed out after 120000ms

  Stack Trace --------------------------------------------

ServerlessError: Connection timed out after 120000ms

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 win32
     Node Version:       6.3.0
     Serverless Version: 1.0.2

```

I know that this is occur because now my service is bigger and contain more files and folder before like node module.my internet is little slow but i was serverless 0.5 user.i cant find any difficulty with serverless `0.5` with current internet speed.

than i tried to deploy specific function using `serverless deploy function -f fname`

than i got following error

```
 The function "fname" you want to update is not yet deployed.
     Please run "serverless deploy" to deploy your service.
     After that you can redeploy your services functions
     with the "serverless deploy function" command.

```

that means i cant deploy new function direct. every time i need to run `sls deploy` before deploy new functions.

why it is like that in serverless `1.0` , it should be like `0.5` . it is very hard time with `1.0`

it should upload new function using `serverless deploy function -f fname` whenever we will create new function

**Comment by flomotlik** [comment]
@nirmalgoswami can you run `SLS_DEBUG=true sls deploy -v` again so we can see the full exception output and print it here.

The best way forward would be to split up your service into several smaller services to make sure they are small enough to be deployed. Other than that there isn't really a lot we can do.

**Comment by flomotlik** [comment]
As this isn't a bug in our system I'm closing here.

**Comment by nirmalgoswami** [comment]
here is trace to deploy new function using `sls deploy function -f register -v`
```
 Serverless Error ---------------------------------------

     The function "register" you want to update is not yet
     deployed. Please run "serverless deploy" to deploy your
     service. After that you can redeploy your services functions
     with the "serverless deploy function" command.

  Stack Trace --------------------------------------------

ServerlessError: The function "register" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.
  at sdk.request.catch (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deployFunction\index.js:53:13)
  at tryCatcher (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
  at Promise._settlePromiseFromHandler (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:510:31)
  at Promise._settlePromise (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:567:18)
  at Promise._settlePromise0 (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:612:10)
  at Promise._settlePromises (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:687:18)
  at Async._drainQueue (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:138:16)
  at Async._drainQueues (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
  at Immediate.Async.drainQueues (C:\Users\Onew\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
  at runCallback (timers.js:566:20)
  at tryOnImmediate (timers.js:546:5)
  at processImmediate [as _immediateCallback] (timers.js:525:5)


  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 win32
     Node Version:       6.3.0
     Serverless Version: 1.0.2
```

to reproduce this issue please deploy service first than make new function than deploy only newly created function

**Comment by nirmalgoswami** [comment]
@flomotlik i am big fan of serverless framework.i was very happy while using `0.5` version of serverless.i want to make `1.0` even better so i am trying to find time to post issue

why we need to deploy same service again after making new function everytime ? is it good practice ? it should be like `0.5`

**Comment by flomotlik** [comment]
We moved deployments of functions into Cloudformation. `serverless deploy function` is really only a helper to be able to deploy functions faster into an already created environment to be faster during development, its not meant to deploy new functions.

The main decision why we moved to CF for deployment was so we have a cleaner and atomic way to deploy (which also makes our Code a lot easier)

**Comment by yogesh-mhaskule404** [comment]
I am facing same issue.  The function "function_name" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command. Is there any way to deploy new function and it's endpoint in same service, without using **sls deploy**
