### ISSUE TITLE
Obsolete Wiki content should be removed

### ISSUE THREAD

**Issue by staceymoore** [serverless/serverless#2446]
# This is a Documentation issue

## Description

The wiki at https://github.com/serverless/serverless/wiki contains obsolete info about JAWS. Given the new docs setup, the wiki should probably be turned off altogether by an admin. Since the docs are editable, is there any need for a wiki?

If you want to disable it, go to settings for the repo; under "options" uncheck the the box next to "wikis" in the features section.

For bug reports:
n/a

For feature proposals:
n/a

Similar or dependent issues:
n/a

## Additional Data
n/a

**Comment by flomotlik** [comment]
good find, disabled the Wiki.
