### ISSUE TITLE
Deploy function not executing webpack and deploys bogus ES6 functions

### ISSUE THREAD

**Issue by n8sabes** [serverless/serverless#2453]
v1.0.2 `sls deploy function -f funcName` does not run webpack and deploys bogus (incomplete) functions that are missing imported code. `sls deploy` works correctly and deploys all functions build as defined in config.

Is this a v1.0.2 function deployment bug, or is there a way to force single-function deployment to properly execute build instructions defined in `serverless.yml` and `webpack.config.js`?

Also, `sls deploy function -f funcName` should support `-noDeploy` option.

**Comment by flomotlik** [comment]
@n8sabes this sounds like a bug in webpack and they might not be integrating this into the lifecycle of the `deploy function` command. Can you open up a bug over there please.

> Also, sls deploy function -f funcName should support -noDeploy option

`deploy function` is really only a convenience method, for anything that really should show you the whole deployment process and output the general deploy is the better option. At this point we don't plan to implement --noDeploy to `deploy function`

**Comment by n8sabes** [comment]
Thanks @flomotlik. Did you mean serverless-webpack project or webpack? It seems that `sls deploy function` is not executing the serverless-webpack build logic at all, but happy to open issue and reference here.

**Comment by n8sabes** [comment]
Thanks @flomotlik. I've opened the issue with the serverless-webpack project.

It's important to figure this out as deploying a single function is much faster than a whole deployment process, especially in large projects. It would also be useful to see what 'deploy function' is actually building via `-nodeploy` as a sanity check (just like 'deploy'), but I defer to the team's priority list.
