### ISSUE TITLE
version 1.0.2 causing a 502 on CloudFront

### ISSUE THREAD

**Issue by flameoftheforest** [serverless/serverless#2457]
Version 1.0.2 causes HTTP 502 Error when API is triggered.

The event object is also different from version version 1.0.0 (event.method has become event.HttpMethod and event.body is a string instead of a JSON)

**Comment by jch254** [comment]
I'm experiencing this as well

**Comment by flameoftheforest** [comment]
i suggest using 1.0.0-rc02

**Comment by jch254** [comment]
Right on, locked in to 1.0.0-rc02

**Comment by flomotlik** [comment]
@flameoftheforest @jch254 you can get the old behavior by changing to the `lambda` integration type: https://serverless.com/framework/docs/providers/aws/events/apigateway/

We changed the defaults after AWS came out with their Lambda proxy a few days before the 1.0 release.

**Comment by jch254** [comment]
Great thanks so much @flomotlik 👍

**Comment by DianaIonita** [comment]
I was running into this with v1.1.0 - my issue was that the response object was not properly formatted. This is what the docs say it should be:

`exports.handler = function(event, context, callback) {
    const response = {
      statusCode: 200,
      headers: {
        "x-custom-header" : "My Header Value"
      },
      body: JSON.stringify({ "message": "Hello World!" })
    };

    callback(null, response);
};`
