### ISSUE TITLE
Use *.test.js pattern

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2464]
# This is a Feature Proposal

## Description

https://github.com/serverless/serverless/pull/2431 already started the transition to the *.test.js pattern for test files. This way we can add globs in the `mocha` test script and don't need an `all.js` file where we list all the tests.

Test files should live on the same level as the files which are tested. Furthermore they should share the same name (they only add a `.test.js` extension). This way one can easily find the test file and the file which contains the to be tested functionality.

This way we also don't miss test files in the future as they're automatically detected.
Furthermore the main code and test files are near to each other which makes it easy to find the test file.

**Note:** I moved the proposal for the descriptive file names into an own issue (https://github.com/serverless/serverless/issues/2641).

**Comment by flomotlik** [comment]
Imho index.js is pretty much never necessary, even with several files as there is always a better name, e.g. a name that is close to the plugin or what it does!

**Comment by nikgraf** [comment]
@pmuens you don't even need the *.test.js pattern for test files. Simply run every file inside a folder `tests` should be good enough or do I miss something?

**Comment by pmuens** [comment]
Yes, we could do that as well. But I like it when the file and the test file are near to each other (like it's done here: https://github.com/serverless/serverless/tree/master/lib/classes) and not nested inside of directories which makes navigating around more painful.

**Comment by nikgraf** [comment]
ahh you would place them right next to each of the files. looks good to me as well. In both ways we should make sure they are ignored when publishing the package. Is that currently the case?/cc @flomotlik

**Comment by pmuens** [comment]
Oh yes, that's a good catch. I think they are not excluded right now as the whole lib directory is bundled (https://github.com/serverless/serverless/blob/master/package.json#L34-L42).
