### ISSUE TITLE
CloudFormation Outputs limit reached

### ISSUE THREAD

**Issue by Titozzz** [serverless/serverless#2466]
# This is a Bug Report

## Description
I'm migrating from sls 0.5.6 to v1.
First API, had no problem cause it only has 55 functions, but my other one has got 70 😞 

* What went wrong?
Serverless error deploying 70 lambdas in one project.

* What was the config you used?
I'm using serverless-scriptable-plugin to create the artefact to upload after I used babel.

* What stacktrace or error message from your provider did you see?

```
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

     Template format error: Outputs count 71 is greater than
     max allowed 60

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 win32
     Node Version:       5.6.0
     Serverless Version: 1.0.2

```

## Additional Data
When i look inside my cloudformation file I can effectively see 71 outputs : 1 bucket && 70 lambdas

**Comment by flomotlik** [comment]
@Titozzz Are you able to split this into separate services? With the move from 0.x to 1.0 we wanted to set up the system in a way where you have separate services with fewer functions in them than in 0.5.

Its definitely possible to write a quick plugin that simply removes those outputs, but it would probably be easier to simply break up the app into separate services if possible.

**Comment by Titozzz** [comment]
What is the point in settings theses outputs ? I have no idea what they are used for

**Comment by j** [comment]
@Titozzz out of curiosity.. how long does it take you to push updates to a service this large?  Are you just deploying a single function or the whole thing?

**Comment by Titozzz** [comment]
With serverless 0.5.6 was something like 1h30.
With serverless 1.0 it upload the same bundle for all my functions so about 2 min 😄

**Comment by flomotlik** [comment]
@Titozzz we use the outputs for log statements mostly. At this point the best thing you can do is write a small and simple plugin that removes those outputs before the deployment: https://serverless.com/framework/docs/extending-serverless/

Basically we store the Cloudformation template in a JS object in the serverless class and when deploying compile it and deploy. You can simply edit it to make that go away. We won't be able to fix this soon by ourselves as its an edge case and we need to prioritise other things higher for now.

I'm going to close the issue as its not going to be resolved at the moment but happy to keep the conversation going here.

**Comment by Titozzz** [comment]
https://github.com/Brigad/serverless-remove-cf-outputs-plugin

I can't see the deploy function list after the success but i guess it's normal... Seems to work ok
