### ISSUE TITLE
1.0.2 does not include symlinks in service zip file

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2472]
My workers are Python so I usually need to build a "vendor" directory within my Serverless project so the libraries can be imported at runtime.  This has worked very well in v1.0.0-rc.2.

My approach has been to use multiple vendored directories so they can be included or not in a reusable way across projects.  My current project has 3 such directories, one of which is a normal directory, and the other two of which are either symlinked entirely (whole directory points elsewhere) or have contain individual libraries that are symlinked in.

Deploying in v1.0.2, the normal directory is now included in the deployment zip file, but the two variations of symlinked directories are not.  Vendoring in this way is critical since Lambda does not provide every needed library module.  Inconvenient to have ti copy & synch many files.

Is there a reason symlinked directories should be excluded -- was it intentional?

Thanks

**Comment by pmuens** [comment]
@chris-hailstorm thanks for reporting! You're right. There's already a PR which brings back including of files and adds symlinks as well: https://github.com/serverless/serverless/pull/2266

**Comment by 5inline** [comment]
@pmuens This doesn't seem to be included in the recent 1.0.3 release. Is it planned for an upcoming release?

**Comment by pmuens** [comment]
This is now available thanks to @jonsharratt and his PR #2266
