### ISSUE TITLE
BREAKING - Support packaging and deploying artefacts as separate steps

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless#2473]
# Feature Proposal
## Description

For CI / CD scenarios it is common to package and deploy software as separate steps. The package step generates artefacts and the deploy steps deploys those artefacts to different environments. This allows for scenarios like environment promotion ect.

At this stage we sort of have a package step with `sls deploy --noDeploy`. We might need to consider adding a command like `sls package` that performs the same task. I remember [the discussion](https://github.com/serverless/serverless/pull/1808) around the naming of `--noDeploy`. Having a separate command was discussed then.

The missing step is a `sls deploy --package ./package.zip`. This would deploy the package that had been created earlier.

Similar or dependent issues:
- #2460 - This covers the same code base. We should wait until that issue is resolved first.
## Additional Data
- **_Serverless Framework Version**_: 1.0.2

**Comment by gertjvr** [comment]
Love this idea. we where thinking about how to resolve this.

# Scenarios for us:

We use [Teamcity](https://www.jetbrains.com/teamcity/) for running tests and compiling / building assets. These assets are then package and promoted to be deployed with [Octopus Deploy](https://octopus.com/). During deployment OD replaces tokens injected at build time with configuration for the environment its deploying too.

Making the assets a first-class citizen would make deployments repeatable and controlled.

**Comment by nicka** [comment]
@johncmckim Thanks for documenting the issue. One thing I would like to be clarified though.

>The missing step is a sls deploy --package ./package.zip. This would deploy the package that had been created earlier.

Would this also take in account the generated CloudFormation templates from an earlier build phase? I'm not really sure if including the templates is really that important though(since they will be autogenerated). Also including the templates would make it provider specific again, while --package should be common among providers.

**Comment by gertjvr** [comment]
@nicka it very important for us that nothing changes to the artifacts after they are generated and packaged. As the promotion path requires consistent / unchanged artifacst. As I mentioned in my comment OD will replace tokens injected into the artifacts. if you regenerated them these replaced tokens might get reset.

**Comment by nicka** [comment]
@gertjvr I'm working on a feature proposal [#2477](https://github.com/serverless/serverless/issues/2477) for the use of CloudFormation Change Sets. Since I think it could be two separate deploy arguments.

**Comment by johncmckim** [comment]
@nicka it should include CF but it should also support other providers. This is how I think it should work

## Examples
### Scenario 1 - separate package and deploy
1. `sls package` generates the required files. For example:

```
|_ .serverless
  |_ cloudformation-template-create-stack.json
  |_ cloudformation-template-update-stack.json
  |_ your-service.zip
```

2. These files are zipped and stored as an artefact `artefact.zip`. This can be done by CI or could be done by serverless
3. `sls deploy --package artefact.zip` skips the package process, extracts the package to `.serverless` and deploys `.serverless` 

### Scenario 2 - normal and deploy
1. `sls deploy` generates the required files in `.serverless` and deploys `.serverless`

## More thoughts
The implementation I am thinking of is not provider specific. It merely works which `.serverless` in different ways.

The reason why I would go with this is that as @gertjvr says, the package should not change between environments (except for environment variables).

I'm open to suggestions for improving this.

**Comment by nicka** [comment]
@johncmckim Thanks for elaborating on this, sounds and reads 👍

**Comment by flomotlik** [comment]
@johncmckim interesting proposal. I'll have to think this through a bit and will come back with my opionion then in the next days.

**Comment by gertjvr** [comment]
Any update on this discussion?

**Comment by lmammino** [comment]
I am also interested in knowing if there is a plan to develop and release these feature.

**Comment by flomotlik** [comment]
I just created 3 different new issues after a little more discussion that should solve this by creating a separate build command and documenting how to use the variable system to make this work.

We need to further discuss during the implementation of those issues how we're dealing with CF templates, if those are created during the build process as well and then just handed to the deploy command, so the deploy command really only deploys but does not do any further building of artifacts.

**Comment by massimocode** [comment]
This would be awesome. I've been trying to deploy on the train and the packaging takes like 2 minutes. By the time it's done, my connection is lost!

**Comment by jthomerson** [comment]
Just adding my vote for the ability to do separate build / deploy steps. I think the one-stop deploy that we currently have is great for developers working on their workstation, but we are accustomed to our CI server building an artifact and then using other automation tools for deploying that built artifact, guaranteeing that exactly what was tested is what is deployed.

**Comment by lascarayf** [comment]
+1 
Extra:
- Add deploy from s3 bucket 
- Add deploy from stage. Ej. copy the staging stage into production

**Comment by gertjvr** [comment]
Is someone working on this?

**Comment by pmuens** [comment]
@gertjvr yes, @eahefnawy is currently working on it!

Furthermore there's @HyperBrain great work with the entrypoint PR (https://github.com/serverless/serverless/pull/3327) and the CI / CD plugin (https://github.com/HyperBrain/serverless-cicd) which implements just that.
