### ISSUE TITLE
Service Discovery

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2483]
# This is a Discussion
## Description

One of the fundamental problems to solve when you build a large micro-service infrastructure is service discovery. How do you make it easy for services to find each other, get the appropriate rights to talk to each other and make this possible across different stages. Maybe during development you want a few services to be shared by everyone, but other services should be deployed independently for each developer so they can easily iterate on it. Of course service discovery should never be hardcoded into the application as deployment would become a nightmare in that case.

To solve this issue we're working with AWS on making it easy to configure your services to find each other. We'll implement a simple syntax to define dependencies and through our upcoming SDK allow you to easily communicate between services, use Resources defined in other services and even include your preexisting infrastructure in your Serverless services easily.
Similar or dependent issues:
## Fundamental questions to answer
- How to describe dependencies between services
- How to discover services that run in a separate environment
- Where to store service discovery data
- Should service discovery be static during deployment or dynamically change after deployment as well
## Similar or dependent issues:
- Service Composition: #2481

**Comment by clearly** [comment]
One of the large use cases for Service Discovery is not necessarily for the public interface of services but instead having an up-to-date *current state* view of the infrastructure for a service. This was necessary when a node (consumer) participating in the implementation of the service could no longer service a request provided by a client (producer) and the client needed to discover a new node within the service implementation that could satisfy the request.

The observation I have is this type of use case seems to be based off of assumptions around legacy infrastructure where constructing globally highly available scaled-out services was either significantly prohibitive or impossible or meta data about the service needs to be provided; all of which are standard capabilities provided with AWS Lambda architecture and AWS services framework. It is now possible to **easily** software define services that use DNS as a public interface for discovery that **never goes down** especially with a Lambda architecture. DNS has been providing service discovery for over 30 years and I am having a hard time convincing myself why using it isn't even more applicable in a serverless architecture.

**Using DNS here are some ideas regarding the fundamental questions**

1. How to describe dependencies between services
Metadata in serverless.yml description bound to DNS endpoint handles. Optimizations gained by particular DNS naming conventions.

2. How to discover services that run in a separate environment
Metadata in serverless.yml description bound to DNS endpoint handles. Optimizations gained by particular DNS naming conventions.

3. Where to store service discovery data
The source of truth is the cloud provider's persistence so why would that be replicated to another store? 

4. Should service discovery be static during deployment or dynamically change after deployment as well.
I am a fan of the staging mechanisms implemented by API Gateway whereby environment stages are described by URI prefixes (qa, dev, staging, prod). To me it seems like these would be statically defined but referred to dynamically during build cycles for stages of CICD promotion.

**Comment by pmuens** [comment]
Closing this one for now to keep the issue count low.

Upcoming Serverless versions will provide ways to solve this problem.

**Comment by olivierlemasle** [comment]
Hi @pmuens,
Is Service Discovery still on Serverless roadmap or has it been implemented? I didn't find anything in the docs...

**Comment by mrjomp** [comment]
@flomotlik @pmuens @olivierlemasle 
This needs to be reopened great part of breakthrough micro services with serverless depends on service discovery.

**Comment by OJFord** [comment]
@pmuens Do now-upcome versions of Serverless provide ways to solve this problem?

It might be one of those things I just can't find without knowing the feature name search-term in advance, but all I can find is this issue, and 'service composition' issue #2481. Cheers.
