### ISSUE TITLE
Service Communication

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2484]
# This is a Discussion
## Description

Once you build a large micro-service infrastructure communication between those services can become complicated. You might not want every service to be able to talk to every other service, you might want to invoke specific services whenever one finishes or simply send out an event and have other services react to that event automatically and asynchronously.
## Communication issues to solve

Following are a couple of use cases we think need to be solved by the Serverless Framework. To support them the Framework will automatically create resources in your AWS account and connect the functions to those resources with the help of our upcoming SDK. E.g. when you configure a service to be able to raise an event we will create a SNS topic that other services can easily subscribe to through a simple serverless syntax.
- Send out Async events through code and have other services subscribe to these events and run functions
- Listen to a function starting or finishing (including success/failure) and run a follow up function
  - e.g. after the SaveUser function has finished successfully you want to send out an email
- Call a another function synchronously from your code and do something with the result
- Call another function async from your code

Another part of this service communication in the future will be communication across different providers.
## Similar or dependent issues:
- #12345

**Comment by johncmckim** [comment]
Two of the problems to solve with be message contracts and large payloads.

**Message Contracts**
When sending messages between systems, the contract between the producer and consumer must be stable. If the consumer starts receiving unexpected messages, it won't be able to process them and should error.

But producers will need to change message formats as things change. To support this consumers need to be upgraded to support multiple message types before the consumer changes.

To facilitate this, messages should have metadata and the payload. The metadata for each message should have a type and possibly version. This will allow consumers to accept and reformat messages as required.

It would be good if the SDK could help abstract this. It will be a common problem that everyone needs to solve.

**Large Payloads**
SNS has a payload size of 256KB. For messages that are too large, this should store it in Dynamo or S3 and send a reference to the event in the payload.

Helping wit this. If the SDK is open source, I'd love to contribute. It's something I'm going to need soon and I'd rather avoid building our own system.

// cc @gertjvr who spoke to me about these issues originally

**Comment by nicka** [comment]
Let's move 👍 http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html

**Comment by pmuens** [comment]
Closing this one for now to keep the issue count low. Furthermore we've recently introduce cross-service communication.

Upcoming Serverless versions will provide other ways to solve this problems.

**Comment by s1mrankaur** [comment]
@pmuens  Really keen on this.  " cross-service communication" : Can you point me to the correct resource. Also, does serverles framework take care of deploying the downstream microservices first?
