### ISSUE TITLE
Lambda fails with 'unable to import module' and 'Cannot find module '_process'' errors

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#249]
Deploying from El Capitan with Node.js 4.1.2.

This bug seems to be the cause: https://github.com/substack/node-browserify/issues/1277

**Comment by jwulf** [comment]
I changed `insertGlobalLets` to `insertGlobalVars` in `DeployLambda.js` and that fixed it for me.

**Comment by jgdenoo** [comment]
+1
