### ISSUE TITLE
Refactor create plugin to be provider independent

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2498]
# This is a Feature Proposal
## Description

While working on multi provider support I found that in the `create` plugin we store all the templates for all the providers we support. It would be great if we can refactor this and make the main `create` plugin provider independent and add the corresponding provider related templates in the `lib/plugins/<provider>/create` plugin.

**Comment by ac360** [comment]
Providers will exist outside of the core as separate installable plugins.  Plugins can only be installed in Services.  In the proposed approach, how would you run create, if you have nowhere to install the Provider plugin first, which contains the create command?

**Comment by pmuens** [comment]
Yes, that could not be done going this way of installing provider related plugins in the service after it was created.

But how would an external provider integration look like if the programmer is not able to touch the Serverless core codebase?

The only thing that caught my attention was the baked in nature of provider related information in the Serverless core. I would find it great if the Serverless core could be independent on it's own by just providing the core plugins like `deploy`, `remove` etc. without having any dependency on providers (and their logic).

**Comment by flomotlik** [comment]
@pmuens How is the create plugin dependent on the provider? While we have templates for AWS in there now, we could easily add templates for other providers as well correct?

The only downside is that at the moment those templates are hardcoded so if somebody implements a provider as a plugin they can't easily add those templates to the create plugin. While an inconvenience its not too bad at the moment and if we really need to we can easily make this better by plugins being able to provide their own templates and somehow register them (but that should be something we do once we need it and I don't think we'll need it soon)

**Comment by pmuens** [comment]
Just wanted to get get the discussion going as we're facing this exact problem with the current Google Cloud Functions implementation (see #2568).

We could add the template to the core of Serverless. However the Google Cloud Functions support should be provided as a separate set of plugins.

IMHO the template should be shipped in the plugin and not in the core so we should provide a way for plugin developers (and provider integrators) to hook into the create plugin so that the template for the corresponding provider can be created without putting it into the core Serverless codebase by submitting a PR.

/cc @ac360 @flomotlik @eahefnawy

**Comment by pmuens** [comment]
Closing this since it's stale and not an issue per se.
