### ISSUE TITLE
passing a number as a cli option errors

### ISSUE THREAD

**Issue by tjmcewan** [serverless/serverless#2500]
# This is a Bug Report

## Description

If I pass a number as a cli option like this:

`sls deploy --account 999123456`

or this:

`sls deploy --account '999123456'`

or this:

`sls deploy --account "999123456"`

I get this error:

```
Trying to populate non string value into a string for
variable ${opt:account}. Please make sure the value
of the property is a string.
```

I use it for string interpolation like this:

`iamRoleARN: arn:aws:iam::${opt:account}:role/lambda_full_access`

Is there a way to pass a number as a string?  Thanks!

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.2
* ***Operating System***: OSX 10.11.6
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by tjmcewan** [comment]
For anyone experiencing the same issue, my workaround is to double quote the number in some way.  eg. `sls deploy --account "'999123456'"`

**Comment by flomotlik** [comment]
thanks for reporting. Yup this looks like we should allow strings or numbers to populate into a place where a string can be accepted.

**Comment by horike37** [comment]
@flomotlik 
I fixed. Please review it.
