### ISSUE TITLE
Question: Is there a way to set up HTTP headers?

### ISSUE THREAD

**Issue by jrivera294** [serverless/serverless#251]
Hi. first of all, congrats for this project, it's an awesome idea, looks really promising.

My question, I can't find a way to set up the HTTP request headers for the API gateway endpoints. It's not implemented?

There is a way to put a http request header on the event.json to make a jaws run and test it?

Regards.

**Comment by joemocha** [comment]
Look at your aws_modules/FOO/BAR/awsm.js
Set your RequestParameters as below
```
     "RequestParameters": {
        "integration.request.header.x-access-token": "method.request.header.x-access-token"
      },
```

**Comment by theopak** [comment]
To expand on the above answer: in `./aws_modules/{lambdaName}/{endpointName}/asm.js` you can define HTTP headers to add to the response for a given endpoint. (AWS API Gateway calls this "Method Response" and "Integration Response".) 

For example, you can enable CORS by using this value in asm.js for `apiGateway.cloudFormation.Responses.default.responseParameters`:

```json
"responseParameters": {
  "method.response.header.Access-Control-Allow-Origin": "'*'",
  "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization'",
  "method.response.header.Access-Control-Allow-Methods": "'GET,POST'"
},
```

After you make the change in the file just `$ jaws deploy endpoint` or use `$ jaws dash`.

**Comment by jrivera294** [comment]
Thank you very much, It worked, maybe it can be added to the tutorials =)

**Comment by jrivera294** [comment]
Well, I thought the tests were successful but when I take a closer look, I saw that the lambda code are not receiving anything on the event object. Locally with the jaws run command it works, but when I upload it, event return {}.

This is my request parameter:
"integration.request.header.x_mail_list_client_id": "method.request.header.x_mail_list_client_id"

In the code i'm trying to acces it with event.x_mail_list_client_id.

@joemocha Can you show me an example of how to get this header on the code?

**Comment by dekz** [comment]
[This endpoint](https://github.com/dekz/awsm-users/blob/master/awsm/list/awsm.json#L33) pulls out an `Authorization` header.

**Comment by radhomero** [comment]
As @dekz indicated, here is an example, with the POST body data included:
```json
"RequestTemplates": {
        "application/json": "{\"data\": $input.json('$'), \"yourHeader\":\"$input.params('x_mail_list_client_id')\"}"
      },
```
```js
//in your lambda:
postBody = event.data;
header = event.yourHeader;
```

**Comment by jrivera294** [comment]
@radhomero it works, thank you very much. My problem was caused because I was putting the headers on the RequestParameters instead of the request templates like @joemocha was suggesting. 

Noob questions: What's the difference between your method and the @joemocha method? Why this method works locally but not when I upload it to aws?

**Comment by radhomero** [comment]
@jrivera294 actually both actions are required: 1. Set your RequestParameters to create the integration. 2. Set the RequestTemplates to bring the request parameter into your Lambda event.
