### ISSUE TITLE
CF / Kinesis limitations

### ISSUE THREAD

**Issue by yeehaa123** [serverless/serverless#2512]
# This is a Feature Proposal
## Description

For bug reports:
- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

For feature proposals:
- What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
- If there is additional config how would it look

My stack is growing, and I'm running into some cloudformation limitations. Specifically, my new deployments are failing because I have more than 5 kinesis streams. Would it be possible to add a feature to have this detected and maybe add some dependsOn statements in the generated cf template? Or is there an easier workaround that I'm missing?

Similar or dependent issues:
- #12345
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by flomotlik** [comment]
@yeehaa123 could you post the output why its failing and an example how the CF template looks now and how it should look with your proposal?

**Comment by yeehaa123** [comment]
@flomotlik Thanks for getting back to me about this 

The error I get, is an LimitExceededException on CreateStream, and a subsequent rollback. As mentioned [here](http://docs.aws.amazon.com/kinesis/latest/APIReference/API_CreateStream.html). AWS only supports  by streams being in the create state at the same time, and my stack is exceeding that limit.

I solve it now, by commenting out half my stack during the first run and do uncomment it for a second run, but that's far from ideal

My serverless.yml looks like this now: 

https://gist.github.com/yeehaa123/b4b915e6772c47e6031cb525f9dbecdf

It refers to this streams.yml file where my streams are actually defined:

https://gist.github.com/yeehaa123/116458004e0f76f53013c787fa2afed8

I'm not quite sure, how the solution should look like exactly, but the only option I see is to include a [DependsOn attribute](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html) on some (or all) of the streams, so that cloudformation does not create them all at once.

That being said, my knowledge of cloudformation / serverless is not as deep as yours, so there may be other solutions too.

**Comment by yeehaa123** [comment]
This is the exact error btw: This request would have exceed the limit on the number of streams that can simultaneously be in CREATING or DELETING for the account 774182433398. Limit: 5.

**Comment by yeehaa123** [comment]
@flomotlik I also contacted AWS about this issue. They suggest the following:

Hi JH,

Thank you for contacting AWS technical support.

Since you already know that this is a limitation of the CreateStream API (http://docs.aws.amazon.com/kinesis/latest/APIReference/API_CreateStream.html), the best way to tackle this limitation in CloudFormation is to use the DependsOn attribute in such a way that you are creating Streams in batches of 5. For example, the first 5 Streams does not depend on anything, but the next 5 should depend on all the previous 5. This way we are making sure that only 5 streams are getting created in parallel.

We do recommend the use of DependsOn Attribute over having to comment and update your stack twice as the former method is more manageable and fully automated. I am afraid there is no other way in CloudFormation to tackle the limitations of the underlying resource APIs.

I hope this helps. Please let me know if you have any questions or concerns and I would be happy to help.

Best regards,

Neel P

**Comment by dougmoscrop** [comment]
@yeehaa123 You could do this yourself right? In your `streams.yml` you could add DependsOn?

I would expect that if severless is creating the stream, it should need to understand this limitation and address it. But inside "custom resources" I am skeptical of making the tool try to be smart/clever and adjust things. 

When this PR lands: https://github.com/serverless/serverless/pull/2488 I would expect it not to understand this, since it's just subscribing, but if you have the ability to *create* the stream, I would expect serverless to include the DependsOn.

Just my two cents.

**Comment by pmuens** [comment]
Closing this one for now since we've pushed lots of updates for the `stream` event in the past and it seems to be something on AWS end.

Feel free to re-open / add info about this if the problem still persists.

**Comment by prmichaelsen** [comment]
I encountered this issue again, could we reopen?
```
This request would have exceed the limit on the number of streams that can simultaneously be in CREATING or DELETING for the account 088851503611. Limit: 5. (Service: AmazonKinesis; Status Code: 400; Error Code: LimitExceededException; Request ID: d95b9c6e-763a-3c30-8f60-421bd45af357)
```
Happy to use `DependsOn` as a workaround, but it doesn't feel like the true solution. I agree that CloudFormation should understand the requirements of the APIs it's calling and handle its calls appropriately.

**Comment by learnersm** [comment]
I encountered the same issue, and i dont think this will be solved by using DependsOn:

reason : DependsOn ensures that the resourceX is created only after resourceY is created. But still resourceY will be in CREATING state in cloudformation. If there are > 5 such streams in creating state, the deployment will fail (with or without using depends on).

The solution is to somehow create kinesis resources in batches of 5, not more.

**Comment by xmiao2** [comment]
Encountered the same issue. IMO customers should be able to specify all the streams that are needed, and the streams should /eventually/ be created. Customers should not have to worry about creation details and come up with workarounds like DependsOn; all those should be handled by Cloudformation.
