### ISSUE TITLE
Browserify doesn't like winston

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#253]
Running a lambda on AWS with `winston` and `winston-paperly`, I get this:

```
"errorMessage": "ENOENT, no such file or directory '/private/var/folders/hw/zsjsyc8s3gz3yzfschg7qdhw0000gn/T/lBglListenPushover@1445265929934/node_modules/winston/node_modules/pkginfo/lib'",
```

**Comment by jwulf** [comment]
From here: https://github.com/ajbrown/angular-loggly-logger/compare/97fecdf56043...8f19153de0eb

It looks like if there is no `main` defined in `package.json` of a package in the dependency tree, or if the `main` is defined with no file extension (for example: `"main": "index"`), then browserify will consume the file path and inject it into the bundle, rather than resolving the referenced code.

The solution for me was to go through all the packages that caused an exception like that, and modify the `package.json` to something that resolves.

**Comment by jwulf** [comment]
Also, winston dynamically requires files, which is not supported by browserify.

Trying this solution here: http://stackoverflow.com/questions/21642398/compiling-dynamically-required-modules-with-browserify

**Comment by jwulf** [comment]
Also, browserify doesn't like relative paths on the `main` - so it consumes `lib/index.js`, but not `./lib/index.js` (and also not `./lib/index`)

**Comment by jwulf** [comment]
Browserify doesn't handle the dynamic generation of lazy-loading getters in winston's `transports.js`. It's elegant, but too dynamic for browserify.

**Comment by jwulf** [comment]
```
$ cat bundled.js | grep /var
}).call(this,"/private/var/folders/hw/zsjsyc8s3gz3yzfschg7qdhw0000gn/T/lBglPost@1445546526911/node_modules/awsm-logger/node_modules/bunyan-loggly/node_modules/loggly/node_modules/request/node_modules/form-data/node_modules/mime")
}).call(this,"/private/var/folders/hw/zsjsyc8s3gz3yzfschg7qdhw0000gn/T/lBglPost@1445546526911/node_modules/awsm-logger/node_modules/bunyan-loggly/node_modules/loggly/node_modules/request/node_modules/hawk/lib")

}).call(this,"/private/var/folders/hw/zsjsyc8s3gz3yzfschg7qdhw0000gn/T/lBglPost@1445546526911/node_modules/awsm-logger/node_modules/winston/node_modules/pkginfo/lib")
```

**Comment by jwulf** [comment]
Even with this adjusted, `hawk`, `mime`, and `form-data` don't browserify because of the `fs` dependency.

**Comment by jwulf** [comment]
I'm getting around it now by using the `exclude` and `includepath` in `awsm.json`:

```
  "exclude": [
          "aws-sdk",
          "winston",
          "hawk",
          "mime"
        ],
        "includePaths": [
          "node_modules/awsm-logger/node_modules/winston",
          "/node_modules/awsm-logger/node_modules/winston-loggly/node_modules/loggly/node_modules/request/node_modules/hawk/",
          "node_modules/awsm-logger/node_modules/winston-loggly/node_modules/loggly/node_modules/request/node_modules/form-data/node_modules/mime"
        ]
```

**Comment by mhahn** [comment]
spent awhile trying to figure out what was wrong with my function and then came across this. it's pretty painful to be using a standard node library and then have it fail for one of these reasons.

**Comment by Vadorequest** [comment]
Is it compatible now? It's been 2-3 years and I'm thinking about using Winston for my Serverless app.
