### ISSUE TITLE
Document AWS API Keys/Usage Plans inconsistent behavior

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2539]
Our hero @svdgraaf got some valuable info from AWS support team about API Keys & Usage Plans. The conclusion is that AWS confirmed some bugs and outdated docs. We should add those to our docs (even before they do 😛 )

```
Sorry to hear that you are having issue with API gateway using CloudFormation.

The reason that you are experiencing this error is that you have eenabled"Usage Plan" in your account. Once you enable "Usage Plan", the "old" way of associating API key will not work. Without Usage Plan [1], you perform the following tasks to create API key for your API Gateway: 
1. Create an API key.
2. Enable it on specific API methods.
3. Deploy the API to a stage. 
4. Associate the key with the API stage.
5. Distribute the key to your customers and ask them to supply it in calls to the enabled API methods.

Above steps are the steps CFN follows to associate the API key to API methods. However, as I mentioned, these steps no longer work in your account since you have "Usage Plan" enabled. WITH Usage Plan, you will need follow the steps in the follow link to set up API keys: https://urldefense.proofpoint.com/v2/url?u=http-3A__docs.aws.amazon.com_apigateway_latest_developerguide_api-2Dgateway-2Dapi-2Dusage-2Dplans.html&d=DQICaQ&c=9g4MJkl2VjLjS6R4ei18BA&r=2dPqsGzLsM5X1Sc2gkAF8unhoC3OwUJgq5TTSOU3Vug&m=dnu_7fL5s8WeCyL3ftm_ptZiSfuM4V3RdDVzsU-CKqk&s=cOD8xbgr4L0e9fJpISFfpxaX0RJGp_wudKLjeTNZsV8&e= . I will need check with our service team engineer regarding API keys with Usage Plan, and see if there is a way associating the key using CFN.

- Why doesn't CF given any errors, but doesn't deploy correctly?
This is probably a bug. I will let our service team engineers know about this.

- Is there a way to associate the api keys with a usage plan through CF?
I have performed couple tests in my lab, and I was not able to associate the key using CFN. I will escalate this issue. As for now, please manually associate your API key as you have done.

- Can you perhaps switch this account to the non-usage plan functionality like with our other accounts?
I do not have permissions to make this change. I will escalate this issue to our service team, and see if they can revert your account back to the "non-usage plan"

Q: " Also, the ApiKey resource, doesn't return the actual value (as stated in the documentation), but return the CloudFormation LogicalId, which makes some sense, but now there is no way to fetch the Api Key value directly from CF, see this quote from the docs:

> Ref: When the logical ID of this resource is provided to the Ref intrinsic function, Ref returns the API key, such as AbCdEfG01234567890ExampleKey." "

I was able to reproduce the issue. I need more time to look into this issue. Thanks.

I will work with both CloudFormation service team and API Gateway service team to get this issue fixed. Thank you for your patience!
```

Thanks again @svdgraaf ☺️ 🙌

**Comment by svdgraaf** [comment]
I -finally- got a confirmation back from AWS concerning this issue:

> I was able to get a definite answer from our service team engineers. They confirmed that CloudFormation is not supporting API key with Usage Plan at this moment. This feature request has already been submitted to our development team. As a workaround for now, you will need to associate the key manually using web console. 
> 
> In addition, regarding your question "the ApiKey resource, doesn't return the actual value (as stated in the documentation), but return the CloudFormation LogicalId", this is a bug in CloudFormation. Our service team engineers are currently working on this issue. Thank you for your patience!

so *sigh*

**Comment by pmuens** [comment]
@svdgraaf thanks for the follow-up! 👍 

I just got the TODO to check again on my list today. Sad that it's not added yet though...

**Comment by dennisoverbeeke** [comment]
Our crazy Siberian also found this... Waiting for a fix because our Jordan guy accidently pressed the button to enable the plans

**Comment by edmofro** [comment]
CloudFormation are now supporting usage plans: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html

**Comment by pmuens** [comment]
@edmofro thanks for the update 👍 

The last time I checked there was no possibility to connect an API Key with a usage plan. Unfortunately it seems like this is still not possible 😞

**Comment by svdgraaf** [comment]
@pmuens correct, there still is no way to connect them. Also, connecting them manually through the api (or by hand), will result in problems when you try to delete or update the Stageplan later, as it will complain that there is still a key connected to the plan (outside of CloudFormation), and the stack deletion/update will fail :(

**Comment by pmuens** [comment]
Thanks for the detailed feedback @svdgraaf !

Oh damn. Hopefully they'll update CloudFormation with that feature soon (we had to turn off our "API Keys" integration tests because the way how API Keys work was not deterministic)...

**Comment by pmuens** [comment]
Just a quick update. Usage plan support was dropped recently:

https://aws.amazon.com/de/about-aws/whats-new/2017/03/aws-cloudformation-supports-authoring-templates-with-code-references-and-amazon-vpc-peering/

**Comment by edmofro** [comment]
@pmuens sorry, but in that link I can't see any mention of dropping support for usage plans? From what I can gather they have added a new UsagePlanKey resource, but not deprecated the current UsagePlan - see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-supported-resources.html

**Comment by pmuens** [comment]
@edmofro Thanks for your response.

They've just introduced the `AWS::ApiGateway::UsagePlanKey` property which makes it possible to connect an API key to a usage plan --> http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplankey.html

This should make it possible to use API keys programmatically again.

**Comment by edmofro** [comment]
Haha no prob, my misunderstanding - I took it to mean "deprecating support for"

**Comment by pmuens** [comment]
> Haha no prob, my misunderstanding - I took it to mean "deprecating support for"

TBH it was pretty confusing. Even for me after reading it this morning.

"Note to self: More ☕️ next time..."

**Comment by pmuens** [comment]
Closing for now to keep the issue count low. Furthermore it seems like this feature will be supported in the near future.
