### ISSUE TITLE
Move API Gateway CloudFormation into a proper CF file using custom resource

### ISSUE THREAD

**Issue by benkehoe** [serverless/serverless#254]
I love that JAWS uses a fake CloudFormation syntax for API Gateway. But I think it would be better to handle it as a [custom CloudFormation resource type](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html), and handle it directly through CloudFormation. JAWS could maintain a singleton Lambda function (i.e., not per-project) to deploy API Gateway endpoints using the existing syntax (this would get invoked by CloudFormation when the template using the custom resource is deployed). This Lambda function could be used by other software to deploy API Gateway endpoints through CloudFormation as well.

**Comment by cagataygurturk** [comment]
Hi, where is the documentation of this fake CloudFormation syntax? Thanks.

**Comment by aletheia** [comment]
+1 for the documentation
