### ISSUE TITLE
Allow invoking functions from the same service by default

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2548]
# This is a Feature Proposal
## Description

By default IAM role should include statements for invoking functions from the same service. It shouldn't require adding entry in iamStatements.

**Comment by eahefnawy** [comment]
+1 that makes sense 👍

**Comment by flomotlik** [comment]
I'm not so certain that this should be available by default. If we add those by default we definitely need a way to turn this automatic behaviour off, because for larger teams adding to an IAM role is a potentially large issue.

**Comment by mthenw** [comment]
@flomotlik hmm, but it's only about calling functions from the same service

**Comment by flomotlik** [comment]
Yup, but we got people for example who added dozens of functions to the same service. That could easily blow up the IAM template a lot, and sometimes users might not want functions to be able to call other functions, even in the same service. When it comes to IAM we need to give users very close control over what we're automatically adding and by default we should only be adding what is actually necessary. Through the new Communication proposals we've been thinking about and working on we should have a pretty straight forward way to define this for users.

**Comment by pmuens** [comment]
Closing this as #2608 will cover this!
