### ISSUE TITLE
Fix Programmatic Support

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#255]
There are two outstanding issues that prevent JAWS from being used programmatically:

* It is context aware in CLI mode, but has no idea where the project folder is located in programmatic mode.
* Getting credentials is impossible because it doesn't know where the project is and therefore the project's `admin.env`.  Further, some actions are meant to be run outside of a project anyway and still need access to AWS credentials (e.g., ProjectCreate).

To fix both of these, I propose the following changes:

* Allow a `projectPath` attr to be included in the JAWS instance config object.
* Allow `apiKeys` or `profile` to be included in the JAWS instance config object

The flow looks like this:

* JAWS is instantiated
* Checks if interactive
* Checks if within a project.  If `projectPath` is set, it overrides.
* Checks for `admin.env`.  If `apiKeys` or `profile` is set, it overrides.

Lastly, I suggest we not configure the AWS SDK included with JAWS via profile and only do it via API Keys for simplicity.  We can grab the API Keys either from the profile or from the `config` object, and using them we only have to configure the AWS SDK to be set one way.

**Comment by ac360** [comment]
Hmm, @doapp-ryanp is there a specific reason we are updating the profile every time we interact with the AWS SDK included in JAWS.  Could we not set the AWS SDK credentials once when JAWS is instantiated and only update the region?

**Comment by doapp-ryanp** [comment]
When doing programatic consumption, code does not need to locate `admin.env` all it needs to do is set the env var `ADMIN_AWS_PROFILE` and the JAWS code [will use it](https://github.com/jaws-framework/JAWS/blob/es6-modular/lib/Jaws.js#L43).  I propose we change this env var to `JAWS_ADMIN_AWS_PROFILE` to be more clear and to namespace.

I went with the profile over keys, as AWS suggests doing it this way, and if we give them the profile they handle the rest.  With that said I'm ok going keys if we still expose just the profile to end users as that is much easier to manage and understand (and we handle the complexity of parsing the keys out of the file)

For locating the project, I like the idea of adding projectPath to the jaws instance config object.  If its not passed, Jaws.js will try to detect it correct?

No reason that I can think of that we are updating the profile every time.

**Comment by ac360** [comment]
Ok.  I definitely like the `JAWS_ADMIN_AWS_PROFILE` env var change.

Yes, jaws will detect project path if it is not provided in config object.  

Ok, let's remove the profile param from all `JawsAws` methods.  And provide one method to set it.

I disagree with providing only `profile` as the option.  I feel `profile` is restrictive because it is looking for a local file in a specific place.  I have a feeling JAWS will be used programmatically in lots of different contexts, possibly wrapped in lots of different tools.  Allowing API Keys in the JAWS instance config is a very common pattern.  I'd like to allow either api keys or profile in instance config.  One or the other can be used.  I've looked into it and this will require only minimal changes.

**Comment by doapp-ryanp** [comment]
sounds good. I have made the env var name change.
