### ISSUE TITLE
DX: serverless create support for git urls

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2574]
# This is a Feature Proposal

Right now `serverless create` supports fixed set of templates. I think git urls should be supported there. It can be helpful for teams/companies in which there is defined default bootstrap project. 

Also it can be solution for adding more customized templates to the core (e.g. https://github.com/serverless/serverless/issues/1997).

**Comment by pmuens** [comment]
Do you mean that this should also be moved into create? Because we already have the `install` command for it.

**Comment by mthenw** [comment]
Oh yeah, I forgot about `install`. But that's kinda confusing because I actually not installing anything. 

Maybe there should be only one command `serverless create -t (git url or defined template)`. And `install` could be used in some future features.

**Comment by ac360** [comment]
@mthenw I suggested the same when the `create` command was initially designed.  Templates is an extra concept that doesn't need to exist.  There are only Services.

**Comment by pmuens** [comment]
Yes. We separated the commands as the `create` plugin should be refactored before we add the "install" command to it.

**Comment by medikoo** [comment]
It was addressed with https://github.com/serverless/serverless/pull/4133
