### ISSUE TITLE
Rollback requested by user

### ISSUE THREAD

**Issue by whatsdis** [serverless/serverless#258]
So I can't create any project because even if I delete it from the CF dashboard, it just comes back from the dead.

JAWS: Select a region for your project:
  > us-east-1
    us-west-2
    eu-west-1
    ap-northeast-1
JAWS: Select an AWS profile for your project:
  > default
JAWS: Creating CloudFormation Stack for your new project (~5 mins)...
JAWS: - { StackId: 'arn:aws:cloudformation:us-east-1:3948384923:stack/dev-wl
-NybGxMxZe-r/ba32434-32b1-33a-8ec1-50f98270ag',
  StackName: 'dev-wl-NybGxMxZe-r',
  Description: 'wl-NybGxMxZe resources',
  Parameters:
   [ { ParameterKey: 'aaProjectName',
       ParameterValue: 'wl-NybGxMxZe' },
     { ParameterKey: 'aaNotficationEmail',
       ParameterValue: 'you@yourapp.com' },
     { ParameterKey: 'aaStage', ParameterValue: 'dev' },
     { ParameterKey: 'aaJawsBucket',
       ParameterValue: 'jaws.dev.useast1.wl.io' },
     { ParameterKey: 'aaDefaultDynamoRWThroughput',
       ParameterValue: '1' },
     { ParameterKey: 'aaDataModelStage', ParameterValue: 'dev' },
     { ParameterKey: 'aaProjectDomain',
       ParameterValue: 'mydomain.com' } ],
  CreationTime: Tue Oct 20 2015 22:22:37 GMT-0700 (Pacific Daylight Time),
  StackStatus: 'ROLLBACK_IN_PROGRESS',
  StackStatusReason: 'The following resource(s) failed to create: [JawsBucket, I
amRoleApiGateway, IamRoleLambda]. . Rollback requested by user.',
  DisableRollback: false,
  NotificationARNs: [],
  Capabilities: [ 'CAPABILITY_IAM' ],
  Outputs: [],
  Tags: [ { Key: 'STAGE', Value: 'dev' } ] }
{ [JawsError: Something went wrong while createing your cloudformation]
  name: 'JawsError',
  message: 'Something went wrong while createing your cloudformation',
  messageId: undefined }

**Comment by whatsdis** [comment]
basically once you created a project, you can't use the same project name again, even if you delete it and it disappears from CF. strange.

**Comment by theopak** [comment]
I wonder if the jaws deployment command could also print out the exact resource or permission that causes a cf failure.

- We know when a CloudFormation create/update API call fails because the response has `StackStatus: 'ROLLBACK_IN_PROGRESS'`, and jaws prints that to the cli. 
- You can manually debug this to find the first event that caused all other resources to get rolled back. Go to the CloudFormation web ui, click the Stack, and look at the Events tab. The oldest event that has the status `CREATE_FAILED` is the one that caused the failure.

**Comment by whatsdis** [comment]
well fellas, it's working now on Ubuntu, but definitely trouble on Windows 7. I'm going to leave this one open in case someone else runs into the same problem

My solution: Ditch windows, and do it on Ubuntu.

**Comment by theopak** [comment]
Hmm. 

Well, as far as I can tell there's no way to use [awscli](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html) to output the _first_ failure, but if you encounter an error then you can use this command to list all events. The output is JSON and could be parsed to return the value of `ResourceStatusReason` for the first event where `ResourceStatus` is "CREATE_FAILED": 

    $ aws --profile=default cloudformation describe-stack-events --stack-name=<stack-name>

**Comment by theopak** [comment]
When the jaws ES6 refactor is done, it would be cool to use this to describe cloudformation failures. I'd be happy to do it myself. :smile: 

The "ResourceStatusReason" value is actually very helpful most of the time! Here's part of a real failure I got while going through an was tutorial:

```bash
$ aws --profile=theopak cloudformation describe-stack-events --stack-name=myvoteapp
{
    "StackEvents": [
    { … },
    {
        "StackId": "arn:aws:cloudformation:us-east-1:178157223430:stack/myvoteapp/ab396d30-7355-11e5-8420-507bb903ae0a", 
        "EventId": "DynamoDBAggregatesTable-CREATE_FAILED-2015-10-15T15:59:22.263Z", 
        "ResourceStatus": "CREATE_FAILED", 
        "ResourceType": "AWS::DynamoDB::Table", 
        "Timestamp": "2015-10-15T15:59:22.263Z", 
        "ResourceStatusReason": "VoteAppAggregates already exists in stack arn:aws:cloudformation:us-east-1:178157223430:stack/my-demo-app/e113b380-7354-11e5-a811-50d5018a1236", 
        "StackName": "myvoteapp", 
        "ResourceProperties": "{\"ProvisionedThroughput\":{\"WriteCapacityUnits\":\"1\",\"ReadCapacityUnits\":\"1\"},\"TableName\":\"VoteAppAggregates\",\"AttributeDefinitions\":[{\"AttributeType\":\"S\",\"AttributeName\":\"VotedFor\"}],\"KeySchema\":[{\"KeyType\":\"HASH\",\"AttributeName\":\"VotedFor\"}]}\n", 
        "PhysicalResourceId": "", 
        "LogicalResourceId": "DynamoDBAggregatesTable"
    }
  ]
}
```

**Comment by whatsdis** [comment]
still happening on windows 7. unable to create a new project as it says ROLLBACK.

works fine on Ubuntu.

**Comment by eahefnawy** [comment]
As of Serverless v0.5 we have a new `sls project remove` and `sls resources remove` actions...This should solve the issue :)
