### ISSUE TITLE
Add integration test for Kinesis & DynamoDB events

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2580]
We need an integration test that covers creating Kinesis & DynamoDB events to make sure the basic functionality is working. We can add more specific integration tests as we move forward.

**Comment by pmuens** [comment]
Just a quick note: We need to merge the support to use Streams w/o ARNs first otherwise the test cannot be automated.

**Comment by pmuens** [comment]
Closing this since it's quite stale and our integration test strategy has changed over time.

**Comment by eahefnawy** [comment]
thanks @pmuens ... wow 2016! 😄
