### ISSUE TITLE
resultTtlInSeconds defaults to 300 when set to 0

### ISSUE THREAD

**Issue by tepez** [serverless/serverless#2587]
# This is a Bug Report

## Description

* What went wrong?

`resultTtlInSeconds` defaults to 300 when set to 0.

This is oviously due to [this line](https://github.com/serverless/serverless/blob/f817933909cb524dcde729348bf229ae355e15ac/lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js#L54
) (since 0 is falesy...)

**Comment by flomotlik** [comment]
Yup thats a bug that needs to be resolved. Thanks

**Comment by horike37** [comment]
@flomotlik 
I fixed it. Please review.

**Comment by OlegRakovitch** [comment]
Facing same issue. Hope suggested bug fix will be merged soon.
