### ISSUE TITLE
Project-wide Lambda build settings

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#260]
I've written an awsm logging library for JAWS Lambdas that uses a promise to finish the logging before the lambda terminates the context. It supports various transports, including winston. Winston dynamically requires files. To browserify this, the `bulkify` transform is needed in the project dependencies and also in the `awsm.json` for each lambda that uses the logging library.

Is there a way to specify the bulkify transform at a project level? Or to specify it for those lambdas that `require` my logging module?

**Comment by flomotlik** [comment]
@jwulf sorry for the late reply, I'd love to chat how to integrate this if you're still up for it. I'm going to close the issue for now, please feel free to open if you want to talk about it more.
