### ISSUE TITLE
Failing unit tests won't cause build to fail

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2603]
# This is a Bug Report

## Description

Brought up by @andymac4182 in #2127. The build currently reports a success even if tests are failing. Here's an example: https://travis-ci.org/serverless/serverless/jobs/172833144

**Comment by mthenw** [comment]
Yeah, I noticed that also. Failing unit test has been fixed in https://github.com/serverless/serverless/pull/2599.

**Comment by mthenw** [comment]
I will try to figure out why TravisCI is not failing.

**Comment by andymac4182** [comment]
Not sure if it helps @mthenw It also passes correctly on my machine as well. It is exiting with Code 0.

**Comment by mthenw** [comment]
So far I found that tests from this commit https://github.com/serverless/serverless/commit/0df8cbc60e3d7c3ff278d6e8eb5ccbda2cb0a0b4 are causing this bug.
