### ISSUE TITLE
Profile the Serverless tool and optimise if necessary

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2609]
# This is a (Bug Report / Feature Proposal)

## Description

When running Serverless it feels like the tool is getting slower. To make sure that we're not making it too slow over time we should start profiling serverless and implement integration tests to make sure it doesn't get too slow.

Tool:
- https://nodejs.org/en/docs/guides/simple-profiling/

Similar or dependent issues:
- #1080

**Comment by pmuens** [comment]
Just created a complexity report for the current version in `master`:

https://gist.github.com/pmuens/088191b7477d289d80647fa4ac39c415

/cc @serverless/core

**Comment by pmuens** [comment]
Just used the v8 profiling toolset to analyze Serverless.

The commands used were `node --prof bin/serverless` and `node --prof-process isolate-0xXXXX-v8.log > profiling.txt`

Here's the output: https://gist.github.com/pmuens/f37f767df7e53b1816b088f2a0680af1

**Comment by pmuens** [comment]
Opened up another, dedicated issue (#2722) for that.

**Comment by pmuens** [comment]
Closing this one as we'll open new, separate issues for the optimization steps.
