### ISSUE TITLE
"Optimize exclude" excludes package from bundle entirely.

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#261]
http://stackoverflow.com/questions/32707970/how-do-you-bundle-aws-sdk-js-into-a-jaws-optimized-package

I tried this in the es6-modular branch, and on AWS my lambda errored out saying the module I excluded couldn't be found.

**Comment by bugeats** [comment]
I can confirm that while inspecting the .zip archive as deployed (in the jaws bucket), there is no `node_modules` dir, or any hint of the excluded modules.

It appears that excluded modules are not included at all.
