### ISSUE TITLE
Does not update new files included via symlinked directory

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2615]
# This is a Bug Report

## Description

My serverless functions are in Python.  I package additional directories of python libraries that aren't provided by Amazon Linux. The easy way to do this is via symlinks.

My structure looks like this:

```
serverless.yml
(other project files)
app-packages/
    local-libs/
    copied-libs/
    linked-libs/ --> /Users/USER/.virtualenvs/PROJECT/lib/python2.7/site-packages
````

Note the last item is a symlink.  This all works well.  The problem is when a file that's reached via the symlinked dir changes, Serverless does not update it in the zip file that's uploaded to AWS.

It appears Serverless is selective about updating the zip file -- maybe doesn't update files or directories that appear to be unchanged?  When any other file changes, Serverless reflects that change in the zip file.  However files on the other side of the symlink that change are not being updated unless I manually touch the symlinked directory.

* What did you expect should have happened?

All files under the project structure, whether normal files, symlinks to files, normal directories, symlinks to directories and so on -- should be updated in the zip file whenever they change.

Maybe Serverless isn't resolving links when walking the tree to look for changes?

* What was the config you used?
v1.1.0

* What stacktrace or error message from your provider did you see?
N/A

## Additional Data

* ***Serverless Framework Version you're using***: v1.1.0
* ***Operating System***: OSX
* ***Stack Trace***: N/A
* ***Provider Error messages***:

**Comment by pmuens** [comment]
@chris-hailstorm Thanks for reporting. 👍 

Could you try this again with the recent master?

We've pushed some fixes for the zipping in the past which should consider and follow symlinks again.

**Comment by mthenw** [comment]
@chris-hailstorm let us know if it's still an issue. 

Closing for now.
