### ISSUE TITLE
Add ability to wire up log subscriptions to a function

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2621]
# This is a Feature Proposal

## Description

Should this be part of the framework? https://github.com/TicketSolutionsPtyLtd/serverless-plugin-cloudwatch-logging-subscriptions

This plugin sets up the relevant subscriptions to route the logs to a single function. This is the next feature after implementing cfLogs. 

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Better logging integration / experience
* If there is additional config how would it look

Automated feature for https://github.com/serverless/serverless/pull/2618

**Comment by flomotlik** [comment]
So basically what you want to be able to do is pipe logs into a function for further analysis?

**Comment by blackevil245** [comment]
@andymac4182 my thought is on the same track as well. I'm planning to do 2 things with the plugin:
1) Include a setting file into the plugin. The file will basically be a manager for lambda log chaining. This is triggered with CL commmand
2) The file with have an option to hook up to `after:deploy:function` and register all deployed functions

**Comment by andymac4182** [comment]
@flomotlik We use this currently to pipe the logs into Seq for log tracking with our existing logs from our full system to allow for correlation across multiple platforms. This allows you to write a function to analyse the logs or forward to other systems quite easily. Now that we are including the LogGroups as part of the CloudFormation this is quite simple.  The only change I have left to add to the current plugin is the ability to specify the ARN to invoke instead of using a function in the existing stack. 

@blackevil245 The plugin we wrote handles number 2 with the relevant permissions as well. Personally using a separate command doesn't work as well as including in Cloudformation since it won't be cleaned up nicely when removing the stack. Also it requires you to remember to set it up for each new project where including in the CloudFormation will ensure the same set up is used in all environments.

**Comment by blackevil245** [comment]
@andymac4182 i think the plugin you propose is working well if we want to have all logs stream coming to a single lambda, where as in the serverless context it would not make much sense to pipe everything to 1 function. Having the possibility to choose multiple destination is the key of flexibility. E.g. you can pipe a number of lambda into Slack message poster, and pipe others to graph builder etc

**Comment by andymac4182** [comment]
Thanks for that feedback @blackevil245 I have fixed up the code to allow specifying the log handler per function. 

This also lines up with the start of supporting Cloudwatch Logs from https://github.com/serverless/serverless/issues/1409

**Comment by yonahforst** [comment]
@andymac4182 - I'm struggling with a similar problem. I want to have unified logging across my microservices so that I can track a request as it propagates through the system. 

I experimented with`bunyan` and `winston` but there were a few problems. They are heavy and they keep the process alive until it times out (they are async and queue messages).

Do you have a readme that describes how to use the plugin? Also, I can't use the same logging function across multiple serverless services, can I? (each one would require it's own `LogHandlerLambdaFunction`, right?

**Comment by pmuens** [comment]
Closing this issue since it's stale. Furthermore we've added support for CloudWatch logs as an event source.

**Comment by dougmoscrop** [comment]
Sorry to necro an issue, but I just released https://github.com/dougmoscrop/serverless-plugin-log-subscription which can help with unified logging. You need to set up Kinesis (and say, a Lambda->Elasticsearch), and a CloudWatch Logs Destination. This will produce an ARN that you give to my plugin. This will cause your functions logs (across services, accounts, etc.) to go to one Kinesis stream, which you can then centrally index.

The "unified logging" infrastructure part is separate, and I may open source that once I get it cleaned up (but you can start from "Creating a CloudWatch Logs Destination")

**Comment by pmuens** [comment]
Great @dougmoscrop! Thanks for following-up with the link to the really useful plugin! 👍
