### ISSUE TITLE
DynamoDB/CF - Subscriber limit exceeded: Only 10 tables can be created,  updated, or deleted simultaneously

### ISSUE THREAD

**Issue by prabhatsharma** [serverless/serverless#2622]
I was trying to create 24 DynamoDB tables using serverless.yml when I got below error. How do I circumvent this?

Serverless: Checking Stack update progress…
.................................................................Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: TestUserTable
     - Subscriber limit exceeded: Only 10 tables can be created,
     updated, or deleted simultaneously.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.6.0
     Serverless Version: 1.1.0

**Comment by flomotlik** [comment]
This seems to be a general issue with Cloudformation, Here is a workaround in the AWS forum: https://forums.aws.amazon.com/thread.jspa?threadID=167996

**Comment by prabhatsharma** [comment]
I tried adding dependson but it still does not solve

resources:
  Resources:
    DevUserTable: 
      Type: "AWS::DynamoDB::Table"
      DependsOn: DevPolicyTable
      Properties:         
        AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "b1-dev-user"
    DevPolicyTable: 
      Type: "AWS::DynamoDB::Table"
      DependsOn: DevClaimTable
      Properties: 
        AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "b1-dev-policy"

**Comment by samcorcos** [comment]
Curious. I ran into the same issue. 

I have 16 tables that need to be provisioned. When I ran my initial deployment (with `-s dev`) on a fresh region with no existing data, the deployment went fine.

Then, when I ran the deployment again with `-s production`, I got the CloudFormation error about half-way through the `Serverless: Checking Stack update progress...` phase.

```
    An error occurred while provisioning your stack: vehiclesTable
     - Subscriber limit exceeded: Only 10 tables can be created,
     updated, or deleted simultaneously.
```

But since it worked the first time, I thought I'd try deploying again with the same settings (`-s production`)... and sure enough, it worked. No idea why it would fail the first time and work the second time, but that's what happened.

So in case anyone else runs into this problem, just try your deployment again and it might work for inexplicable reasons 😄

**Comment by HyperBrain** [comment]
@samcorcos What you could try to do is, to make the table resources dependent on each other by adding a DependsOn definition. This will lead to CF creating the tables one after the other and not simultaneously.

The only problem I see with that is, that the dependencies might not make any sematic sense, but it would be worth a try.

**Comment by aspiers** [comment]
@HyperBrain That was already tried as noted above by @prabhatsharma and didn't work.  I wonder if there was maybe an ordering issue with the way it was tried though.  I'll try it myself and report back.

**Comment by aspiers** [comment]
As [mentioned](https://github.com/serverless/serverless/issues/3744#issuecomment-307040193) in #3744 which is a duplicate of this, another solution is to create a support request with AWS asking them to increase the limit on your account.
