### ISSUE TITLE
Add config credentials command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2623]
# This is a Feature Proposal

## Description

An easy onboarding process for new users is one of the most important features as the first interaction with Serverless might affect the developers opinion about Serverless in the long term.

One of the difficult steps to set Serverless up is credential handling. Each cloud provider does it differently. We should help the users setting up Serverless for their specific cloud provider to enable a smooth and fast onboarding experience / time to first deploy.

@ac360 already did an implementation int he PR https://github.com/serverless/serverless/pull/2160. We should follow up on this and get this in as we're about to support multiple cloud providers soon.

**Comment by pmuens** [comment]
Closing this as it's a duplicate of #1736

**Comment by pmuens** [comment]
Reopening this one!

**Comment by micha-LEAP** [comment]
Documentation references this plugin and command, yet it is not available in the default installation.
https://serverless.com/framework/docs/providers/aws/cli-reference/config/

**Comment by pmuens** [comment]
@micha-LEAP thanks for the question. This feature will be available in Serverless v1.3.0 which we'll release soon!
