### ISSUE TITLE
plugin dev: `options.stage` and `options.region` not computed

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#2631]
Making a plugin, my plugin's constructor gets an `options` parameter that always has a `stage` and `region` attribute.  This is cool, but when I don't specify the stage or region as a cli param the value of these attributes is `undefined`.

I therefore have to always apply this logic at the beginning of my plugin:

```javascript
class SlsMyPlugin {
  constructor(serverless, options) {
    this.serverless       = serverless;
    this.options          = options;

    //I think this should be handled by the sls framework before calling my constructor
    this.options.stage  = this.options.stage
      || (this.serverless.service.defaults && this.serverless.service.defaults.stage)
      || 'dev';
    this.options.region = this.options.region
      || (this.serverless.service.defaults && this.serverless.service.defaults.region)
      || 'us-east-1';
...
}
```

Is there a reason why this logic is not pre-applied before calling a plugin's constructor?

**Comment by pmuens** [comment]
Hey @doapp-ryanp thanks for brining this up.

I too faced this issue this morning. Furthermore I don"t find it intuitive to have the services config in the `options` object.

I would assume that it's the other way around --> options are passed through end e.g. in the config or the service config (e.g. one can access the region via `this.serverless.config.region`).

/cc @eahefnawy @flomotlik

**Comment by ac360** [comment]
Ran into this issue as well!

**Comment by nikgraf** [comment]
Ran into this issue as well, I will bring it up at the internal discussions this week!

**Comment by juanjoDiaz** [comment]
Is there any plan to fix this?
I guess that it's not even possible since the variables are not even resolved when the plugin constructor is called?

**Comment by dschep** [comment]
use `serverless.provider.getStage()` and `serverless.provider.getRegion()` instead of `options` which is only CLI options.
