### ISSUE TITLE
Command for creating function

### ISSUE THREAD

**Issue by mpuittinen** [serverless/serverless#2634]
# This is a Feature Proposal

## Description

Add a command to add a new function for your service. e.g.

`sls create function -f myfunction -h myfunction/handler.handle`

would create a new function `myfunction` with a handler function handler in `myfunction/handler.js` and enter the definition to `serverless.yml`.

Motivation is to ease creation of functions (editing the yml file is prone to errors) and streamline development lifecycle (e.g. creation of test cases for the new functions using serverless-mocha-plugin).

Similar or dependent issues:
* none

**Comment by mpuittinen** [comment]
I'm working on this and will submit a PR (hopefully soon)

**Comment by laardee** [comment]
Is `-f myfunction` only for naming the function? Then `-n` / `--name` could be better.

**Comment by mpuittinen** [comment]
@lardee I went with -f since it is the option used also by `deploy function` (and `serverless-mocha-plugin` command invoke test). This can be easily changed if `-n` is preferred.

**Comment by laardee** [comment]
This is just my opinion, but in those cases `-f` refers to function, not its name, and when new service is created `-n` is used for naming the service.

**Comment by rowanu** [comment]
What about other runtimes?

I'm not sure optimising for something that might only happen a handful of times in a service's lifetime is worth the effort/loc per runtime...

**Comment by mpuittinen** [comment]
Other runtimes were left out at this stage due to limited experience with those (and our own interests are mainly with node.js). It should be straightforward for anyone with experience to add support (templates) for the other runtimes.

**Comment by mpuittinen** [comment]
FYI. This functionality has now been incorporated into [serverless-mocha-plugin](https://github.com/SC5/serverless-mocha-plugin). The true value is not just creating functions but creating functions, tests, and anything related automatically. I'll remove it from there if this gets incorporated into the core serverless framework.

**Comment by nikgraf** [comment]
I left a longer explanation here why we believe this should be an external plugin: https://github.com/serverless/serverless/pull/2639#issuecomment-265465808

@mpuittinen I really like your idea of establishing a best practice together with the mocha plugin. You should blog about it as well. I would share & promote it. Nevertheless I believe it's too opinionated for the core at the moment.
