### ISSUE TITLE
AWS CloudFormation diff command

### ISSUE THREAD

**Issue by nicka** [serverless/serverless#2636]
# This is a Feature Proposal

## Description

For feature proposals:
* It would be nice if you could diff your local generated CloudFormation template against the deployed one before actually deploying an update
* Example command `sls diff`

I'm currently working on a plugin over at [serverless-plugin-diff](https://github.com/nicka/serverless-plugin-diff). My question is, do you want this in the core of the framework or rather as a separate plugin?

**Comment by nicka** [comment]
**Update:** I released it as a plugin [GitHub](https://github.com/nicka/serverless-plugin-diff)  [NPM](https://www.npmjs.com/package/serverless-plugin-diff)

Let me know if we would still like to add this to the core of the framework. Otherwise I'll submit a PR for the list of plugins :+1:

**Comment by flomotlik** [comment]
I do think a diff command is a great first step for this. My plan for this is to also integrate with ChangeSets, so you can know exactly what the plan is that CF will execute. While a diff is helpful it doesn't show the whole picture of what will happen when you deploy something.

**Comment by nicka** [comment]
@flomotlik Fully agree on this! As you know, I do want to start working on the Change Sets issue #2477
