### ISSUE TITLE
Usage of sinon and mocha toolings for tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2643]
# This is a Feature Proposal

## Description

Our current test codebase could be improved so that we e.g. use sinon sandboxes (rather than restoring our stubs by hand) or mocha helpers (e.g. to fake a "waiting 5 seconds" command).

This also means that we should use `beforeEach` and `afterEach` more wisely for independent test setups and cleanups.

**Comment by gertjvr** [comment]
Also evaluate [JEST](https://facebook.github.io/jest/) iy has a lot of these libraries built in and there snapshot testing is amazing to guarantee that you generate the same cf json as previously

**Comment by pmuens** [comment]
Closing since our tests started to incorporate such toolings.
