### ISSUE TITLE
Feedback on the new documentations site

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#265]
Hey beautiful people!

Over the past few days, I've been working on improving and migrating our docs to [readme.io](https://readme.io). It'll probably be released officially with the release of the next version of JAWS. 

Here's the new site: [jaws.readme.io](https://jaws.readme.io)

It's not complete yet, almost there! But I'd like to get your feedback before I move forward. Specifically...

* The navigation and the overall organization of the website. Does it make sense? is there a better way you think it should be structured?
* Can you think of any other info that we need to include in our docs?

Feedback from peeps new to JAWS is **especially helpful**, since we're trying to make it as easy as possible to get started with JAWS fast!

Let me know what you guys think!

**Comment by binoculars** [comment]
@eahefnawy Great work on the readme.io site. It's clean and makes sense.

One thing I would add is how to test AWSMs before publishing (for module developers)--at least unit testing. Integration testing can be done by deploying to dev. Also testing for those who install published modules--as sanity check to make sure it does what it is supposed to do.

Again, the site looks fantastic. Thanks for putting it together. :smile:

**Comment by eahefnawy** [comment]
+1 will do ... that fits perfectly in the "workflow" page

**Comment by marklawlor** [comment]
I introduced some friends to JAWS this week, these suggestions come straight from questions that asked me:

* **Documenting the ApiGate fake Cloud-formation Template**: This is custom to JAWS and really needs to be documented
* **Better AWSM Documention**: AWSM has a couple of hidden options that are not documented ( eg. babel & browserify transforms)
* **Examples of common issues**: Things lik "How do I setup CORS" and "How do I give my lambda DynamoDB policies" 
* **Mocking AWS services for testings**: Continuing on from @binoculars idea, but have more depth articles. Have examples showing how to use DynamoDB Local (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html)
* **Deploying Resources**: Examples on how to setup resources like DynamoDB / Kinesis streams to be included in the CloudFormation template

**Comment by eahefnawy** [comment]
@marklawlor thatnks that's perfect! and I do agree, the awsm docs is especially hard to keep track of. There's a lot going on in there.

**Comment by eahefnawy** [comment]
Alright! I've made some major edits to the new site, and I think it's awesome...for now 😅

Here's the tiny details that's left:

* detailed plugins docs
* detailed errors docs
* add API gateway config docs, and improving lambda config docs (`lambda.awsm.json`)
* documenting how API endpoints are deployed
* document how to add/deploy resources as @marklawlor suggested.
* improve the "workflow" page with examples, and testing tips
* improve the FAQs page with **tons** of Q/A about JAWS, how to use it, and common issues. Similar to AWS FAQs. It's kinda an alternative way to view the docs.
* add more "best practices" tips

I think it would be better if I leave those for the next version of JAWS. I feel reluctant to dig deep into the JAWS codebase at this point since it'll all go to waste in a few days with the massive refactoring @ac360 and @doapp-ryanp are doing. Once that checks out, I can dig for more detailed info to put up on the docs site.

Let me know what you guys think.

**Comment by aletheia** [comment]
Cool job!
We just started moving our lambdas to JAWS (after re:invent) a best explaination about how to create a service from A to Z would be great. If you prefer hosting a live coding session / webinar, I could then translate into docs with examples. I am very excited about JAWS and would be helpful in making this great project being successful!

**Comment by aletheia** [comment]
Another thing is quite unclear are cryptic comments in code about the impossibility of using node modules in AWSMs. Being more clear about limitations and how to circumvent them would be great.

**Comment by eahefnawy** [comment]
We'll be having real world project tutorials hopefully by the next release of JAWS. This should clear things up a little bit. Thanks for your suggestions and stay tuned! ;)

**Comment by dsshap** [comment]
@eahefnawy I mentioned this in gitter earlier, but adding an opinionated test examples would be helpful, also include steps to get dynamodb running locally.

**Comment by eahefnawy** [comment]
great idea! will do! ;)
