### ISSUE TITLE
Incorporate BRFS

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#266]
Context: Browserify is used to concat and flatten the .js for the lambda. However, the primary purpose of Browserify is to make code available for the browser environment. This places constraints on what it can compress. JAWS deployed lambdas with optimization using browserify will not run on AWS Lambda if they contain code that will not run in a browser.

Issue:Browserify cannot concatenate files that will not run in the browser. The modules `os` and `fs` are problematic. 

Solution:  You can also make browserify replace `require('fs')` with `browserify-fs` using

`browserify -r fs:browserify-fs`

https://www.npmjs.com/package/browserify-fs

**Comment by marklawlor** [comment]
I think is will be available soon, as the functionality is there in Optimise->Transform AWSM.json option (https://github.com/jaws-framework/JAWS/blob/master/lib/commands/deploy_lambda.js#L631-L633) but this code doesn't appear to be available in the build on NPM.

**Comment by theopak** [comment]
Possibly related: What about using something other than awsm.json `lambda.package.optimize.builder: "browserify"`? 

I'd love to use webpack with JAWS. This dev's blog post is a nice explanation of why: "Webpack takes an entry module, reads the entire dependency tree, and bundles it all together as a single file (assuming a simple configuration). We are going to do this for the backend as well." — http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by binoculars** [comment]
@theopak :+1: for webpack

**Comment by bugeats** [comment]
I've already run into several modules that can't be bundled only because they use `fs.readFileSync`. Some use of [substack/brfs](https://github.com/substack/brfs) would fix this.

**Comment by dcrockwell** [comment]
+1 for webpack

**Comment by yyolk** [comment]
Browserify allows you to pack for when it will be run in node. 

The `--node` option achieves this from the cli

from `browserify --help advanced`:

```
  --node

    Alias for --bare and --no-browser-field.
```

It can also be used as a module by enabling the options that `--node` enables, and is already part of the deploy process: https://github.com/jaws-framework/JAWS/blob/2fa7d9158490c27a7de033949f920c65510207fc/lib/commands/deploy_lambda.js#L603-L675
