### ISSUE TITLE
Document how to set an artifact in the package config dynamically through the variable system

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2661]
# This is a Feature Proposal

## Description

If users want to build artifacts for deployment by themselves they can set the artifact option in the packaging config through the variable syntax (and in the future thanks to #2657 even fully dynamically). This allows to separate the build and deployment of artifacts easily.

We need to document this.

Similar or dependent issues:
* #2659
* #2473
* #2660

**Comment by pmuens** [comment]
The current variable system docs should be sufficient enough to solve the described problem.
