### ISSUE TITLE
Fix displaying of endpoints (in info plugin) when using root paths (/)

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2671]
# This is a Bug Report

## Description

The displaying of endpoints need a slight update so that root endpoints (`/`) are displayed correctly. (the corresponding code can be found in the `info` plugin).

![bildschirmfoto 2016-11-08 um 16 21 38](https://cloud.githubusercontent.com/assets/1606004/20104963/39dfb050-a5d0-11e6-8b5c-7b16a3cccf58.png)

**Comment by laardee** [comment]
@pmuens, PR is ready for review https://github.com/serverless/serverless/pull/2684
