### ISSUE TITLE
Add npm scripts for slStats

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2674]
# This is a Feature Proposal

## Description

We should add npm scripts for slStats so that the whole CLI usage lifecycle can be seen (as @mthenw brought up)

/cc @serverless/team

**Comment by pmuens** [comment]
@serverless/team I need some feedback here.

IMHO we should also make a call to `logStat` and not only generate the uuid. Calling `logStat` will ensure that we know that Serverless was installed.

However IMHO we cannot capture this event through the current schema (https://github.com/serverless/serverless/blob/master/lib/classes/Utils.js#L296-L338) as it's not yet a usage but just an installation.

Should we introduce a new schema for the installation? How should the data look like?

**Comment by worldsoup** [comment]
@pmuens would a new schema break our existing schema? as long as that doesn't happen I don't really have an opinion.

**Comment by pmuens** [comment]
@worldsoup hmm. Yes, a second schema would make the queries a little bit harder.

The problem is that our current schema only covers cases where an actual Framework usage is considered (e.g. information about the service, the invoked command, etc. are captured) but this schema cannot be used if an installation via npm should be captured (because it's not an actual usage and we don't have information about the entered command or the service). I'll brainstorm a little bit about different solutions how we might solve this problem...
