### ISSUE TITLE
With so many updates being pushed out, what about some sort of updater?

### ISSUE THREAD

**Issue by Fourfingerz** [serverless/serverless#2675]
# This is a Feature Proposal

I was just discussing with my coworker about this. I been working on a Serverless v1.02 project and returned to update the lambdas when I noticed that it has jumped two versions to v1.10.

How viable would it be to have some sort of CLI updater where it will upgrade the Serverless version and suggest line by line updates to your serverless.yml or handlers if there are any breaking changes? 

Similar or dependent issues:
* # n/a

## Additional Data

* ***Serverless Framework Version you're using***: v1.02
* ***Operating System***: OSX El Capitan
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by WooDzu** [comment]
Thumbs up. This would generally improve update experience. Ember.js has similar mechanism for diffing blueprints which is a lifesaver.

**Comment by rowanu** [comment]
This sounds like a lot of work for very small pay-off.

Given you can now [pin your service to a specific version](https://serverless.com/framework/docs/providers/aws/guide/version/) and the project is using [semver](http://semver.org/), you can be confident there aren't any breaking changes in minor version changes, there's little benefit in a "hand-held upgrade" and *lots* of ways automated changes to `serverless.yml` can go wrong.

**Comment by JamieCressey** [comment]
Just a decent changelog would be a start :)

**Comment by rowanu** [comment]
You mean like on the [releases page](https://github.com/serverless/serverless/releases)?

**Comment by pmuens** [comment]
Hey @Fourfingerz thanks for raising this issue! 👍 

I get the idea and the upsides but IMHO updating through npm is a little bit more reliable / convenient. We're about to add support for "An update is available" messages (see https://github.com/serverless/serverless/issues/2118).

From now on we're also using the GitHub versions and changelogs again so that you can see what has changed.

**Comment by pmuens** [comment]
Closing this since we're tracking the status in https://github.com/serverless/serverless/issues/2118
and a CHANGELOG.md file was added.
