### ISSUE TITLE
ApiKey ID is the same as the key itself

### ISSUE THREAD

**Issue by orasis** [serverless/serverless#2677]
I'm not sure if this is intentional or not, but, when I use the serverless ApiKeys configuration option, it generates a key on API gateway that has the same ID as the key itself.

When generating an API Gateway key through the AWS console, the ID of the key is different than the key itself.  

I'm filing this bug in case there is a security problem with having the ID of the key exposed.

To check this, go to the API Gateway console, click on "Api Keys".  Click on the key itself.  It will show an "ID" field and a "API Key" field.  With serverless these fields are the same.

**Comment by pmuens** [comment]
Hey @orasis thanks for bringing this up! 👍  💯 
We had the exact same issue (/cc @eahefnawy) and think it is related to the recently introduced "usage plans" for API Gateway.

So this behavior is a feature / bug on AWS end (see: https://github.com/serverless/serverless/issues/2539 and https://github.com/serverless/serverless/issues/2450).

Closing this one as we're discussing this in the other issues.

/cc @flomotlik
