### ISSUE TITLE
Exposing variables for stdlib

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2680]
There is PR in stdlib repo with basic `call` function (https://github.com/serverless/sdk-nodejs/pull/9). This function assumes that there is env variable in following format:
```
SERVERLESS_SERVICE = <service name>
SERVERLESS_FUNC_<service name>_<function name>_ARN = <function arn>
```
for each function deployed in the same service. Those vars have to be exposed by the framework.

**Comment by pmuens** [comment]
Closing this since we're currently not actively working on stdlib.
