### ISSUE TITLE
Support AWS_SHARED_CREDENTIALS_FILE environment variable

### ISSUE THREAD

**Issue by stevecaldwell77** [serverless/serverless#2694]
# This is a Feature Proposal

## Description

When I use the AWS CLI tool, I leverage the $AWS_SHARED_CREDENTIALS_FILE environment variable so I can keep my work and personal credentials separate.  It would be great if Serverless paid attention to this envar too.

## Additional Data

 * http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#the-shared-credentials-file
 * See PR #2695

**Comment by pmuens** [comment]
Should be doable now since it was merged with #2820
