### ISSUE TITLE
Cloud Formation Resource Dependencies: Function, Role and Policy

### ISSUE THREAD

**Issue by marjanSterjev** [serverless/serverless#2697]
There is a problem when we deploy function that shall run on AWS VPC (subnets and security groups specified). In most of the cases deployment fails because of missing permission required for creating EC2 network interfaces. However, _ec2:DescribeNetworkInterfaces_, _ec2:CreateNetworkInterface_ and _ec2:DeleteNetworkInterface_ are specified as additional **iamRoleStatements**.

It seems the problem is **concurrency** and **parallel** creation of several resources.

If we investigate the CloudFormation template created, we can see (assuming we have Hello Lambda function inside):

- The function **HelloLambdaFunction** references the role **IamRoleLambdaExecution**
- The policy **IamPolicyLambdaExecution** references the role  **IamRoleLambdaExecution**.

The creation of the **HelloLambdaFunction** and **IamPolicyLambdaExecution** goes in parallel.
If **HelloLambdaFunction** creation goes first, it will use the role **IamRoleLambdaExecution** before the policy is actually attached to that role and the whole stack creation process fails (insufficient permission, can’t create EC2 Network Interface). 

Occasionally it can succeed, but that behavior is totally random. In order to avoid this problem we must specify explicit **DependsOn** statements in the template. The **Function** shall depend on the **Policy** and **Policy** on the **Role**.  Stack  creation with explicit dependencies set on goes smoothly without any problems.

**Comment by patrickbrandt** [comment]
I'm still seeing this error (using latest version of sls): 
![image](https://cloud.githubusercontent.com/assets/11197026/21618407/be3b33ec-d1b8-11e6-99b0-e7bac80b0603.png)

From the Stack events log:  
![image](https://cloud.githubusercontent.com/assets/11197026/21618435/de125e7a-d1b8-11e6-9d51-20abb6def2ef.png)

my serverless.yml file is here: https://github.com/C0k3/session/blob/development/serverless.yml

**Comment by pmuens** [comment]
Oh snap! Thanks for reporting @patrickbrandt!

What happens if you re-deploy the stack? Does it succeed after that?
There might be still some kind of timing issue with permissions /cc @nicka

**Comment by patrickbrandt** [comment]
@pmuens yes, I removed my comment since I found another open issue that addresses what I'm seeing: https://github.com/serverless/serverless/issues/2780

If I re-deploy the stack after the first (failed) deployment, everything works. I've noticed too that I sometimes get failures and sometimes don't - indicating some kind of race condition.

**Comment by pmuens** [comment]
@patrickbrandt thanks for getting back! 👍 

Yes, that's currently a problem, but @nicka already submitted a PR which should resolve this: https://github.com/serverless/serverless/pull/2983
