### ISSUE TITLE
deploy only api gateway endpoint of newly created function in a service

### ISSUE THREAD

**Issue by Dhyey** [serverless/serverless#2698]
I have made a service named authentication in which I have functions named signup, signin, refresheToken etc. 

Now when I create a new function in this service. I added function name and event etc in serverless.yml

At this point I always have to deploy everything again, can we add a feature in cli where we can only deploy api gateway endpoint of this new function only?

**Comment by pmuens** [comment]
Hey @Dhyey thanks for opening this issue 👍 

We've build everything on top of CloudFormation and the whole service is the unit of deployment. This ensures that the stack you've deployed is always consistent and predictable. Right now there's no plan to add partial stack resource deployments.

We've added a functionality that you can e.g. deploy only functions (`serverless deploy function`). However this should only be used during development and not in production as this might also yield to an inconsistent stack / unexpected behavior.

/ccing @eahefnawy and @flomotlik for further comments.

**Comment by flomotlik** [comment]
As @pmuens already mentioned we're built on cloudformation so this feature is currently not possible and I also don't really want to implement it as it removes atomicity from a deployment, so you can't be sure that the deployment actually did everything it should (or we would have to implemtn this)
