### ISSUE TITLE
Improve "Invoke Local"

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#2700]
# Problem
We've added `invoke local` with the goal of emulating Lambda as best as it can, so that developers can use it to speed up their workflow.

We tried to get an MVP of local support in ASAP, and succeeded.  However, it missed a few critical pieces:  

**1 - `invoke local` behaves differently than `invoke`**

**2 - `invoke local` does not include the environment variables available in AWS Lambda**

**3 - `invoke local` does not support our other runtimes**

# Solution

### 1

This is already being fixed by @horike37 in PR #2620.

### 2

We should create a function that collects the ENV vars before the local invocation happens.  Here are the missing ENV vars.  We have enough information to find/create most of their values locally.

`LAMBDA_TASK_ROOT`
`LAMBDA_RUNTIME_DIR`
`AWS_REGION`
`AWS_DEFAULT_REGION`
`AWS_LAMBDA_LOG_GROUP_NAME`
`AWS_LAMBDA_LOG_STREAM_NAME`
`AWS_LAMBDA_FUNCTION_NAME`
`AWS_LAMBDA_FUNCTION_MEMORY_SIZE`
`AWS_LAMBDA_FUNCTION_VERSION`
`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`
`AWS_SESSION_TOKEN`

### 3

To easily support other languages, we should use a child process whenever we do a local invocation.  We can pass the above environment variables into that child process as an option, since that's easily supported by Node.js.

Keep in mind, the function can be long-running.  Using a callback with the child_process via something like `exec` may not be recommended, since log statements should appear whenever they are logged to `stdout`.  `on('data')` [may be preferred](https://nodejs.org/api/child_process.html#child_process_child_process)

**Note:** A lot of this functionality was already written in V.0 and is a good reference: https://github.com/serverless/serverless/blob/8239e9ca030bfbfa3e8c3f3a9d90aa6af6aec83b/lib/RuntimePython27.js

**Comment by pasviegas** [comment]
Question, in the next release will be possible to invoke other runtimes? like java/scala?

**Comment by brunobelotti** [comment]
I'm trying **invoke local** right now: I noticed it ignores the specified AWS profile in _serverless.yaml_ (`profile: bbb-dev`) and uses the default one `test-cli` (which, in my case, doesn't have access to a SNS topic, hence the invocation fails).

`
message: 'User: arn:aws:iam::*******:user/test-cli is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:*******:bbb-test',
`

Is that a known issue or am I doing something wrong?
_NB: Just to be clear: if I invoke it remotely, everything works._

**Comment by ajagnanan** [comment]
Is it possible to have the event.json file configurable per function? So instead of using the -p option when using the command e.g sls invoke local -f functionName -p src/functionName/event.json, the -p part would be configured somewhere in serverless.yaml

**Comment by pasviegas** [comment]
Hey, could someone help me. In the next release will be possible to invoke other runtimes? like java/scala?

**Comment by pmuens** [comment]
Hey @pasviegas we're currently working on Python (https://github.com/serverless/serverless/issues/2862) and Java (https://github.com/serverless/serverless/issues/2864) support.

Python support should be in place for the next release. Java support is a little bit trickier and we're currently looking for people brave enough to jump into this. Feel free to add your thoughts in the issues!

**Comment by volphy** [comment]
Can we leverage SAM Local (CLI):
https://github.com/awslabs/aws-sam-local#invoke-functions-locally
?

SAM Local is currently in beta but it already looks promising.

**Comment by pmuens** [comment]
Hey @volphy thanks for commenting 👍!

We've just release the `serverless run` command which will spin up a flexible and powerful local development environment. Feel free to give it a spin and provide feedback!

You just need to update to the latest version of the Serverless Framework and run `serverless run` inside your service.

You can read more about it in our docs: https://serverless.com/framework/docs/platform/commands/run/

**Comment by volphy** [comment]
`serverless run`  looks good but according to the docs only NodeJS 6.3+ is supported at the moment.

Are there plans to support Java 8 in near future?

**Comment by pmuens** [comment]
> serverless run looks good but according to the docs only NodeJS 6.3+ is supported at the moment.

> Are there plans to support Java 8 in near future?

Thanks for your comment @volphy 👍

Yes, `serverless run` is quite new and we're planning to add more support (e.g. Python, Java and other runtimes) soon.

Quick question: Which version of Node.js are you currently running on your local machine?

**Comment by volphy** [comment]
Most of my Lambda functions are developed in Java 8, some in Python 2.7.

I do not use NodeJS for Lambda functions development.

**Comment by pmuens** [comment]
> Most of my Lambda functions are developed in Java 8, some in Python 2.7.

> I do not use NodeJS for Lambda functions development.

Gotcha! Thanks for the feedback @volphy 👍.

Support for other runtimes is definitely on our radar!

**Comment by RafalWilinski** [comment]
@volphy I'm working on it: https://github.com/serverless/serverless/issues/2864.

**Comment by pmuens** [comment]
> @volphy I'm working on it: #2864.

Thanks for the update @RafalWilinski 👍. Really excited about this one.
