### ISSUE TITLE
'role' is ignored when setting a custom IAM role

### ISSUE THREAD

**Issue by evanstachowiak** [serverless/serverless#2706]
# This is a (Bug Report / Feature Proposal)
Bug

## Description
Specifying a role at either the provider level or in a function was ignored. I specified an arn of a role that I created outside of serverless, but the default Lambda execution role was applied to my function.

I checked out master and ran serverless directly and this issue seems to be fixed. Not sure what was changed between the versions, but wanted to point out this issue in 1.1.0 and make sure it stayed resolved in the next version release.

* ***Serverless Framework Version you're using***:
1.1.0
* ***Operating System***:
macOS 10.12.1
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by awolden** [comment]
Is there an eta for when Serverless will be published again to include this fix?

**Comment by rowanu** [comment]
https://github.com/serverless/serverless/milestone/16

**Comment by mthenw** [comment]
Fixed in 1.2.
