### ISSUE TITLE
DX: Only re-deploy Lambda function if code actually changes

### ISSUE THREAD

**Issue by ZauberNerd** [serverless/serverless#2710]
# This is a Feature Proposal

## Description
We could limit deployment / creation of new lambda functions, by checking if the lambda function did actually change.
Proposal:
- variant one: hash the contents of the zipfile / use hash as file name and check if file already exists on s3.
- variant two (prerequisite: shrinkwrap.json or yarn.lock): check if all dependencies are locked (see prerequisites) and then run a hash on the lockfile + source code to be used as file name and only upload the zip file if the hash does not already exist on s3.
- variant three: just run a hash on package.json and source code as zip file name (doesn't have the guarantees of proposal nr.1 (predictable transient dependencies), but might still be a viable solution).
- variant four: leverage existing vcs to get the last hash of a specific service folder / file to verify that it did not change.
I think variant one would be most viable and work for every language.

Similar or dependent issues:
* #2325

**Comment by hauboldj** [comment]
An alternative to version one would be to add the hash of the zipfile as metadata on the s3 object. Then just call headObject on the newest file in s3 to see if the current zip is different than the last one.
