### ISSUE TITLE
aws-java-gradle produces flawed zip file

### ISSUE THREAD

**Issue by imaman** [serverless/serverless#2711]
# This is a Bug Report

## Description
when the function created by aws-java-gradle is invoked it fails with a ClassNotFoundException.

Below [1] you can see a full transcript of the session. However, the TL;DR of the "steps to reproduce" is as follows:

- create a fresh "aws-java-gradle" project.
- build it (via gradle)
- deploy it
- invoke the function

Output ("What went wrong?")
```
{
    "errorMessage": "Class not found: hello.Handler",
    "errorType": "class java.lang.ClassNotFoundException"
}

```
Expected output ("What did you expect should have happened?")
```
{
    "message": "Go Serverless v1.0! Your function executed successfully!",
    "request": {}
}

```

* What was the config you used?
plain config created by aws-java-gradle (as of v1.1.0) unchanged

## Additional Data

* serverless version: v1.1.0
* ubuntu

[1] Full session transcript:

```
$ mkdir problem
$ cd problem
$ sls create -t aws-java-gradle
Serverless: Generating boilerplate…
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.1.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-java-gradle"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name
$ gradle build
Starting a Gradle Daemon (subsequent builds will be faster)
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:assemble
:buildZip
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 7.204 secs
$ gradle build && sls deploy  && sls invoke -f hello
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:buildZip UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.187 secs
Serverless: Deprecation Notice: Starting with the next update, we will drop support for Lambda to implicitly create LogGroups. Please remove your log groups and set "provider.cfLogs: true", for CloudFormation to explicitly create them for you.
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3 (7.9 MB)…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
.....
Serverless: Stack update finished…

Service Information
service: aws-java-gradle
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  aws-java-gradle-dev-hello: arn:aws:lambda:us-east-1:196625562809:function:aws-java-gradle-dev-hello

{
    "errorMessage": "Class not found: hello.Handler",
    "errorType": "class java.lang.ClassNotFoundException"
}


```

**Comment by imaman** [comment]
The root cause is two fold:
- the zip file is in the wrong structure: it contains a lib/ folder which is not needed at all + it bloats the size of the file
- the file should be strictly a Jar file (aws is strict about it). Unfortunately, gradle Jar task actually creates a Zip file

suggested course of action:
change the build.gradle file such that it creates a Jar file via an Exec task. This Jar should contain only the classes under build/classes/main

**Comment by imaman** [comment]
Here's a possible solution: https://github.com/imaman/serverless/commit/1cf1c62c6a516d56fd1902fe6057825bb73d123b

Discussion:
A better solution would be to fix gradle's Jar task such that it generates a fully complaint Jar file. However, this is likely to take some time. If we wait for this, everybody using the aws-java-gradle template will run into time consuming cycles of trying to figure out what is wrong with the out-of-the-box (straighforward) configuration provided by the aws-java-gradle template. I, for one, have wasted a couple of days on this. I believe this is a poses a major obstacle for java-over-gradle people who want to evaluate sls and is likely already hindering adoption within this community.

**Comment by pmuens** [comment]
Hey @imaman thanks for taking the time to deeply investigate it!

Briefly looked over your solution (thanks for that!). What are the downsides of using your solution? Seems like the out of the box solution is broken anyway so nobody is able to use it 😬.

**Comment by bbilger** [comment]
sorry for adding my 2 cents to this discussion but since my framework ([jrestless](https://github.com/bbilger/jrestless)) works just fine the way serverless deploys Java functions right now and it is depending on the way it works, I wanted to add some comments, here:
1) a zip file is a totally valid deployment artifact for AWS Lambda functions: http://docs.aws.amazon.com/lambda/latest/dg/create-deployment-pkg-zip-java.html (and the task "buildZip" in the example's build.gradle is doing exactly what it's supposed to do)
2) "it contains a lib/ folder which is not needed at all" this is just wrong since this folder contains the external dependencies and those are indeed needed!
3) I cannot reproduce your problem neither with serverless v1.1.0, v1.2.1 nor v.1.4.0.
So what's your gradle version (gradle -v)? I just tested it with 3.2.1 but I never ran into any issues with 3.x.

**Comment by mthenw** [comment]
Hey @imaman, thanks for reporting.

I verified against master version and I can't reproduce it neither.

Thanks @bbilger for help.

**Comment by jccpdev** [comment]
@mthenw I am running into this problem when I try to re-deploy an updated function using this command.
`serverless deploy function -f "function name"` any ideas of what can be going on?

**Comment by bbilger** [comment]
re-deploying individual Java functions does not work out-of-the-box as far as I know, maybe this helps: https://github.com/serverless/serverless/issues/2946#issuecomment-280183207

**Comment by hello-josh** [comment]
The zip task is broken. Adding `dirMode 0777` and fixing `configurations.runtime` to `configurations.runtimeClasspath` fixes it
```
    dirMode 0777
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
```
