### ISSUE TITLE
Golang support based on eawsy/aws-lambda-go

### ISSUE THREAD

**Issue by cristim** [serverless/serverless#2712]
# This is a Feature Proposal

### What is the use case that should be solved ### 

* [aws-lambda-go](https://github.com/eawsy/aws-lambda-go) is a shim-less way to run Go code in AWS Lambda, with near-zero overhead. The Go code gets cleverly built in such a way that allows it to be loaded by the Python runtime:
  * the go compiler can build Go code that can be loaded as a shared object by anything that can load native shared object files.
  * that particular shared object that happens to also use the [Python native extensions](https://docs.python.org/2/extending/extending.html) so it can then be exposed to the Lambda Python runtime as  Python module
  * its handler method (actually backed by code written in Golang) can be executed directly by the Python runtime.

The build is done in a [Docker container](https://github.com/eawsy/aws-lambda-go/tree/master/_docker), which could potentially be reused by Serverless for a relatively easy integration, so it would add a dependency on Docker for this particular case.

### If there is additional config how would it look ###
`runtime: go`

**Comment by yvele** [comment]
[aws-lambda-go-net](https://github.com/eawsy/aws-lambda-go-net) is also quite sexy :metal:

**Comment by yvele** [comment]
PS: Note that there is also a [aws-lambda-go-net](https://github.com/eawsy/aws-lambda-go-net) layer for HTTP

**Comment by jeberly** [comment]
More interesting now that re:invent came and went without golang support.

**Comment by pmuens** [comment]
I agree!

/cc @mthenw @nikgraf @eahefnawy

**Comment by eahefnawy** [comment]
We discussed this today, and we don't have the capacity to implement this atm. But if someone would like to implement it into an external plugin, that'd be awesome and we'd be happy to feature it! 🙌

**Comment by yunspace** [comment]
hi folks, was quite interested in this also. I managed to get a simple serverless hello example to work with `aws-lambda-go`. Code is here https://github.com/yunspace/serverless-golang. It's actually quite straight forward, the python signatures matches exactly with the golang func. Haven't tried anything fancy like API Gateways or DynamoStreams.

But since that library is being deprecated upon the release of go 1.8 in Feb, I then made an attempt to use their latest `aws-lambda-go-shim`. And it didn't work as expected. Will raise an issue and let you know how it goes.

**Comment by yunspace** [comment]
hey @cristim the error I got was `Cannot use handler with invalid signature`. The full project is in a branch here https://github.com/yunspace/serverless-golang/tree/aws-lambda-go-shim and I've raised https://github.com/eawsy/aws-lambda-go-shim/issues/3 to track this

**Comment by cristim** [comment]
It turns out you forgot to update the import path.

**Comment by yunspace** [comment]
I've merged @cristim's PR into master and it's working for a simple hello world. Trying it out on API Gateway now

**Comment by yunspace** [comment]
Got API Gateway integration to work too now. Just via standard input events like all other sls services. I had a quick look into `aws-lambda-go-net` library but it adds too much latency having to start up a whole standalone webserver for each lambda. Might try some event streams next.

Not sure if it's worthwhile making a plugin out of this, who knows if AWS will officially support golang this year. But if they do, the golang code should be pretty compatible still. Anyway I'll try present this at the Sydney serverless meetup and get a few more folks using this.

**Comment by fsenart** [comment]
@yunspace `aws-lambda-go-net` does not start up new servers, in fact it is pretty optimized for Lambda through a custom fully shared socket mock. In term of latency it is just as fast as a more conventional handlers. 
PS: we are about to release a new version of it to support eawsy/aws-lambda-go-shim as for the moment it works with eawsy/aws-lambda-go and you will also be able to do all initialization in the init function of the handler.

For compatibility with a future support by AWS, eawsy/aws-lambda-go-shim provides a 100% compatible "signature" with all other official runtimes. So I think that your plugin will be portable de facto. Only build cinematic can change as issues like golang/go#17150 will be resolved and would deprecate the use of Docker for builds.

For the rest, so excited to see your plugin for serverless and thrilled to hear from Sydney folks ;)

**Comment by yunspace** [comment]
Thanks @fsenart for clarifying, looking forward to checking out `aws-lambda-go-shim-net` when it's out!

**Comment by cristim** [comment]
My [fork](https://github.com/cristim/serverless-golang) of [serverless-golang](https://github.com/yunspace/serverless-golang) was recently updates to the latest build of eawsy/aws-lambda-go-shim and is now based on eawsy/aws-lambda-go-net, providing an easy migration path to golang users.

**Comment by pmuens** [comment]
Thanks for the plugin and the discussion about this feature in general.

Our current plan is to only support official Lambda runtimes since Serverless is used in enterprise setups and needs to be reliable.

Pretty sure that AWS will add some more runtimes soon.

I'll close this issue for now. Feel free to continue the discussion.

**Comment by cristim** [comment]
@pmuens would you be willing to add a community-supported template at https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates which would allow early adopter users to get started with this?

For the name I was thinking of something like `community-supported-aws-golang-net`, and it would contain a README making it clear that it's a community-provided template and that the golang payload is not officially supported by Serverless nor AWS, and that any questions should be directed to the authors of this shim.

This was initially raised at https://github.com/yunspace/serverless-golang/issues/5

**Comment by pmuens** [comment]
@cristim thanks for getting back.

The core template of the Serverless Framework should only contain runtimes which are 100% supported by AWS since business depend and trust on them.

However we can add an example to the [examples repository](https://github.com/serverless/examples) and promote it so that users can install it via `serverless install`.

**Comment by OrKoN** [comment]
AWS now supports Go. Is the support for Go in Serverless tracked/documented somewhere?

**Comment by yunspace** [comment]
The PR is to get the go template into `sls create`. However you can already use the go template using `sls install` by following the steps here: https://serverless.com/blog/framework-example-golang-lambda-support/
