### ISSUE TITLE
Automatically deploy all resources

### ISSUE THREAD

**Issue by cagataygurturk** [serverless/serverless#272]
Is there any jaws dash option that permits automatically re-deploy all endpoints and lambdas on all regions?

I need a non-interactive way to deploy all stack for continous deployment. (Using travis, deploying to dev, acceptance tests, if passes deploy to production)

**Comment by Nopik** [comment]
Just been through this today myself ;)

```
jaws tag -a lambda
jaws tag -a endpoint
jaws deploy -t lambda $JAWS_STAGE
jaws deploy -t endpoint $JAWS_STAGE
```

**Comment by eahefnawy** [comment]
As an update for Serverless v0.5, you can do this with `sls function deploy -a` and `sls endpoint deploy -a`
