### ISSUE TITLE
Add support for directories in url of install command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2721]
# This is a Feature Proposal

## Description

It would be great to have the possibility to point to a directory when installing a service through the `install` command (rather than only supporting the URL to the whole git repository).

/cc @ac360

**Comment by horike37** [comment]
If you upload Serverless project files to a http endpoint, you can install as follow

```
serverless install <http endpoint>
```
Does this sound good?

**Comment by pmuens** [comment]
Sounds good. The idea is that something like this would work:

```
serverless install https://github.com/serverless/examples/tree/master/rest-api-with-dynamodb
```

**Comment by laardee** [comment]
@horike37, hi, did you start to implement this?

**Comment by horike37** [comment]
@laardee laardee
I have not started implementing it yet. However, I think that I will finish the implementation next week and send PR.

**Comment by laardee** [comment]
Great 👍 this is a nice feature - I was about to refactor one of my repos, but with this feature I dont have to :smile: In github, can you download a zip from certain path of the repository or do you have to download whole thing first?

**Comment by pmuens** [comment]
@horike37 thanks for jumping into this! 💯  🎉 

Also curious how you plan to implement this. Do you know about any specific package which supports this?

**Comment by horike37** [comment]
@laardee 
It isn't possible to download a specific directory by zip. I first downloaded the whole and then left the necessary parts.

@pmuens 
Sorry. I have no idea about a specific package.

Please check it. thanks!

**Comment by pmuens** [comment]
@horike37 awesome!!!

Thank you very much! 👍  💯
