### ISSUE TITLE
Deprecate and remove cfLogs config

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2725]
# This is a Feature Proposal

## Description

In v1.1.0 (https://github.com/serverless/serverless/releases/tag/v1.1.0) we've introduced the `cfLogs` config as a solution to not introduce breaking changes when removing old CloudFormation logs.

We should deprecate this config soon and enable auto log removal by default.

**Comment by michael-dev2rights** [comment]
Currently there's a notice:

'''
Serverless: Deprecation Notice: Starting with the next update, we will drop support for Lambda to implicitly create LogGroups. Please remove your log groups and set "provider.cfLogs: true", for CloudFormation to explicitly create them for you.
'''
when running without that flag.  Shouldn't the notice be changed _before_ the option is deprecated?
'''

**Comment by pmuens** [comment]
Hey @michael-dev2rights thanks for bringing this up 👍 

We've removed this notice with v1.2 and will deprecate it in an upcoming release but notice developers so that they are aware of that.
