### ISSUE TITLE
Allow deletion of stage?

### ISSUE THREAD

**Issue by yaochen** [serverless/serverless#273]
I was just playing around with the commands and created a random stage name. Now whenever I do "jaws dash" this invalid stage name always appears on the list under "Choose a stage:".

Example:

JAWS: Dashboard for project "Test"
 -------------------------------------------
 Project Summary
 -------------------------------------------
    Stages:
       dev us-east-1
       asdf us-east-1
    Lambdas: 3
    Endpoints: 3
 -------------------------------------------
 Select Resources To Deploy
 -------------------------------------------
    test/test1
    - - - - -
  >   Deploy Selected -->
JAWS: Choose a stage:
  > 1) dev
    2) asdf

Is it possible to remove "asdf" completely? I've deleted the folder from the cloudformation folder manually before attempting dash.

**Comment by yaochen** [comment]
after looking a bit through the files, i found that the stage info is in the jaws.json.

so technically i can delete stages manually.

**Comment by doapp-ryanp** [comment]
Yep this is on my internal todo list, just not high priority. Would be cool to get a PR from someone on this after our upcoming next release.

**Comment by cangoektas** [comment]
@yaochen @doapp-ryanp, is it possible that this feature got implemented but someone forgot to close this issue? I'm currently on 0.4 and there is a working "stage remove" options:

```
➜  17:55:09 serverless-nkxpqj sls stage create
Serverless: Enter a new stage name for this project:  abc
Serverless: Select a region for your new stage:
  > us-east-1
    us-west-2
    eu-west-1
    ap-northeast-1
Serverless: Creating stage "abc"...
Serverless: Creating region "us-east-1" in stage "abc"...
Serverless: Deploying resources to stage "abc" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully deployed "abc" resources to "us-east-1"
Serverless: Successfully created region "us-east-1" within stage "abc"
Serverless: Successfully created stage "abc"
➜  17:56:04 serverless-nkxpqj sls stage remove
Serverless: Select a stage to remove:
  > 1) abc
    2) dev
Serverless: Removing stage "abc"...
Serverless: Removing region "us-east-1" in stage "abc"...
Serverless: Removing resources from stage "abc" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully removed "abc" resources from "us-east-1"
Serverless: Successfully removed region "us-east-1" within stage "abc"
Serverless: Successfully removed stage "abc"
➜  17:56:15 serverless-nkxpqj
```

**Comment by ac360** [comment]
@cangoektas Thanks :)
