### ISSUE TITLE
Serverless deploy same name error

### ISSUE THREAD

**Issue by ducmaxime** [serverless/serverless#2730]
Hi , When I try to deploy my prject I have this error : 
Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceUsersEmailVar
     - Another resource with the same parent already has
     this name: {email}.

Any Idea ?

**Comment by pmuens** [comment]
@ducmaxime thanks for reporting!

Could you please provide a little bit more feedback on this one? How can re reproduce it?

**Comment by mthenw** [comment]
@ducmaxime let us know if it's still an issue. Closing for now.
