### ISSUE TITLE
Support for array notation syntax in lambda proxy query params

### ISSUE THREAD

**Issue by rochdev** [serverless/serverless#2734]
Right now for a lambda proxy, passing query parameters such as `?foo[]=bar&foo[]=baz` results in the following:

```json
"queryStringParameters": {
  "foo[]": "baz"
}
```

While this is technically correct according to the W3C spec, it would still be nice if the array notation was supported. Even though it's not an official standard, it's become a de facto standard used in most modern web frameworks.

(Please note that I am not sure of the feasibility of this feature since I am not familiar with AWS mapping template syntax)

**Comment by pmuens** [comment]
Thanks for the suggestion @rochdev 

Closing this to keep the issue count low. Furthermore it seems correct according to the W3C spec.
