### ISSUE TITLE
Documentation - Can't run unless in 'services' directory

### ISSUE THREAD

**Issue by kennyk65** [serverless/serverless#2735]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?  Followed instructions at https://serverless.com/framework/docs/providers/aws/examples/hello-world/node/, but got immediate error on step 1, "This command can only be run inside a service directory"
* What did you expect should have happened?  If there is a prerequisite step, should be listed.  
* What was the config you used?  Config?  Don't know.  Just started working with this template 10 minutes ago.
* What stacktrace or error message from your provider did you see?
  Serverless Error ---------------------------------------
 
     This command can only be run inside a service directory
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.1.0

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by kennyk65** [comment]
Looks like the bit that is missing is to create a service first.  Something like this can be added:  serverless create --template aws-nodejs --path myService

**Comment by kennyk65** [comment]
Also, the later steps were off.  The command to run was:

sls invoke --function hello

And the result was:

{
    "statusCode": 200,
    "body": "{\"message\":\"Go Serverless v1.0! Your function executed successfully!\",\"input\":{}}"
}

**Comment by pmuens** [comment]
Good catch @kennyk65 👍 

could you open a PR to add those missing steps?

**Comment by pmuens** [comment]
Just saw the PR! Thanks for that @kennyk65 💯

**Comment by feedm3** [comment]
I just had this problem and found out that I had a typo in my `serverless.yml` filename

**Comment by pmuens** [comment]
Thanks for sharing @feedm3 👍

**Comment by jpforsyth** [comment]
Whilst obvious for some, can I suggest adding a note to the docs (https://serverless.com/framework/docs/providers/aws/guide/services/) outlining the need to 'cd' into the service directory before  running the deploy command, e.g. cd /<path_to_my>/myService to prevent the "This command can only be run inside a service directory" error.

**Comment by pmuens** [comment]
Thanks for the feedback @jpforsyth 👍

I agree. Would you be open to PR a change to the docs? Otherwise we can update the docs accordingly.
