### ISSUE TITLE
Add integration test for --noDeploy without credentials or internet connection

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2739]
# This is a Feature Proposal

## Description

#2651 should be covered by an integration test.

**Comment by laardee** [comment]
@pmuens, is this already assigned to someone? If not, I think I could take this - after all, it was my PR 😄. Should the test be implemented somewhere here  https://github.com/serverless/serverless/blob/master/tests/integration/simple-integration-test.js?

**Comment by pmuens** [comment]
@laardee thanks for taking this one! 👍 

It should live here https://github.com/serverless/serverless/tree/master/tests/integration/aws/general as it's an AWS specific test and not event related. Let me know if you need any help! 💯

**Comment by pmuens** [comment]
Was recently done with #2855
