### ISSUE TITLE
"iamRoleARN" example missing from docs; use of "role" for that purpose appears to be out of date

### ISSUE THREAD

**Issue by bcx** [serverless/serverless#2744]
# This is a Bug Report 

## Description

documentation bug.

I am finding (after cargo culting a serverless.yaml file I found in a forum thread) that if you use a Role ARN to specify a Lambda IAM Role, you must use the key `iamRoleARN`, rather than the key `role`.

The example given in the docs here: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/iam.md

appears to be out of date.

## Additional Data

     OS:                 darwin
     Node Version:       7.1.0
     Serverless Version: 1.1.0

**Comment by ajagnanan** [comment]
TY!! this works. Refer to #2707 #2706

**Comment by pmuens** [comment]
Hey @bcx thanks for raising this issue. 👍 

Could you pull the recent version from `master` and test it again as we've removed the `iamRoleARN` recently and replaced it with `role`. Thanks in advance!

**Comment by pmuens** [comment]
Closing this one as we've release Serverless v1.2.0 which should cover this (see this comment in the PR for this issue: https://github.com/serverless/serverless/pull/2745#issuecomment-262225940)!

Thanks again for bringing this up. Let us know if this issue is still a problem!
