### ISSUE TITLE
S3 should use Server Side Encryption (SSE)

### ISSUE THREAD

**Issue by shortjared** [serverless/serverless#276]
Adding this issue to make note of something we should be thinking about, which is best practices around storing env variables in S3. We should be using (and probably enforcing) [Server Side Encryption](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html). Secure by default.

Current bucket resource in the jaws.json template
```
"JawsBucket" : {
      "Type" : "AWS::S3::Bucket",
      "Properties" : {
        "AccessControl" : "Private",
        "BucketName" : {
          "Ref": "aaJawsBucket"
        }
      },
      "DeletionPolicy" : "Retain"
    }
```

Bucket Policy to enforce SSE on all PUTS
```
{
   "Version":"2012-10-17",
   "Id":"PutObjPolicy",
   "Statement":[{
         "Sid":"DenyUnEncryptedObjectUploads",
         "Effect":"Deny",
         "Principal":"*",
         "Action":"s3:PutObject",
         "Resource":"arn:aws:s3:::YourBucket/*",
         "Condition":{
            "StringNotEquals":{
               "s3:x-amz-server-side-encryption":"AES256"
            }
         }
      }
   ]
}
```

**Comment by doapp-ryanp** [comment]
Very good idea. When you do a `getObject()` will SDK for node auto decrypt?

**Comment by shortjared** [comment]
Fairly certain it's server side only. It decrypts on the getObject() request before it flies across the wire. I guess "encrypted at rest" is another way to put it.

**Comment by jason-riddle** [comment]
Curious as to why this was closed? At my organization, we have a strict policy of requiring every S3 Bucket be encrypted and to only allow encrypted uploads.

**Comment by Mutley5000** [comment]
Agreed.  Can't see anywhere this has been implemented.

**Comment by pmuens** [comment]
@Mutley5000 thanks for reaching out. 👍 

This feature is not yet supported. This issues seems to be outdated.

Current discussions are happening in https://github.com/serverless/serverless/issues/2888
