### ISSUE TITLE
Docs: Tracking feature Docs Removed

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#2762]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? I searched the docs for "tracking"
* What did you expect should have happened? I expected to see the documentation related to the automated usage tracking Serverless performs
* What was the config you used? N/A
* What stacktrace or error message from your provider did you see? N/A

Similar or dependent issues:
* N/A

## Additional Data

* ***Serverless Framework Version you're using***: https://docs.serverless.com, Nov 21st @ 3:32p PST
* ***Operating System***: Chrome on OSx
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Hey @erikerikson thanks for reporting this! 👍 

The `Tracking` plugin was renamed to `Stats` a while back. The documentation can be found here: https://serverless.com/framework/docs/providers/aws/cli-reference/slstats/

**Comment by erikerikson** [comment]
Sorry about that.  Thanks for sorting me out @pmuens!

**Comment by pmuens** [comment]
Nah never mind @erikerikson 💯 

Great that you have raised this issue as it might be interesting for others as well 👍
