### ISSUE TITLE
Enhance environment variables

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2764]
This is an issue to continue the discussion about environment variables we had in #2673.

**Comment by pmuens** [comment]
@andymac4182:

> It would be great if there was an easy way to add a reference to a function for when you are invoking them.

**Comment by pmuens** [comment]
@stevecrozz:

> In the example configuration above, is the word 'environment' standing in for an example environment name? For instance, would there be a section in here for staging and production?

What I'm used to doing is creating a dotenv file ala https://github.com/bkeepers/dotenv. This is a pretty common way of doing things and there are bindings that more or less do things this way for any language you might want to use. The property of this approach that most strongly appeals to me is that environment-specific configuration can go in an environment specific file. If I have a team and only some of the team members are working on the staging environment, I can share with those team members a .env.staging file and all they need to do is drop it in the project root (usually gitignored). I can't tell if this use case is accounted for in the proposal, but if the idea is that everything should be mixed into one big yaml file or segmented into separate files based on something other than the environment, then it would not be meeting my particular needs.

I'd also be interested to hear more about use case 3 above. I don't understand where that is going.

My main use case, and this seems pretty common, is that I have a service dependency (for example stripe.com). I want to run with a test token in my staging environment and a live token in my production environment. So I need to set STRIPE_TOKEN=test-xyz or STRIPE_TOKEN=live-xyz depending on the current environment.

**Comment by braahyan** [comment]
I agree that being able to supply a file full of the environment variables would probably be a good enhancement.

Having different files for different stages should be achievable right now with what is already in serverless. Below works for something similar to what is described above.

```yml
service: streaming-bi
provider:
  name: aws
  runtime: python2.7
  cfLogs: true

functions:
  api:
    handler: handler.handler
    environment:
      TEST_ENV: ${file(${opt:stage, self:provider.stage}.yml):statusCallbackUrl}

```

**Comment by braahyan** [comment]
The biggest question around environment variables is probably whether you want variables loaded from a file to take precedence over variables defined in the serverless.yml. Second biggest question would be format, ie: do we use the .env formatting, or YML for the storage.

**Comment by wamoyo** [comment]
Amazon has environment variables for Lambda functions:

![aws-env-vars](https://cloud.githubusercontent.com/assets/1170326/20582077/bb478bc2-b1ab-11e6-8cf6-7fd90a8c8989.png)

It would be great to have a terminal command like `serverless environment` or `sls env` that allows you to set environment variables for lambda functions. This would be pretty priceless for me. I use environment variable keys in my code, and they reference test API keys and such locally, and live API keys in my production stages. Helps me test things locally, and push to production without changing any code. Also keeps sensitive credentials out of any files.

**Comment by purplecones** [comment]
Hi, I'm trying to figure out how to use environment variables with Serverless but can't find a clear way of doing it.

I have 
```
provider:
  name: aws
  runtime: nodejs4.3
  environment:
    ABC: testVar
```
set but when I console.log `process.env`, I don't see env variable `ABC`.

In the past, I think version ~0.5, you were able to set env variables with with the cli at a per stage level. How can I accomplish the same with 1.4?

**Comment by pmuens** [comment]
Closing this since it seem like the current environment variable implementation is sufficient enough.
