### ISSUE TITLE
Keys of `event.headers` should be lower cased

### ISSUE THREAD

**Issue by Sharaal** [serverless/serverless#2765]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
The keys of `event.headers` entries are case sensitive. 
e.g. Some browsers like Chrome send headers with a capital letter like "Origin", some other browsers like Firefox send as like "origin".

* What did you expect should have happened?
Like [node http](https://nodejs.org/api/http.html#http_message_headers) the keys should be lower cased because the http spec say the keys care case insensitive.

## Additional Data

* ***Serverless Framework Version you're using***: ^1.1.0
* ***Operating System***: MacOS, AWS Lambda

## Workaround

```javascript
const headers = {};
for (const key in event.headers) {
  headers[key.toLowerCase()] = event.headers[key];
}
event.headers = headers;
```

Additionally if its important not having a braking change its maybe a good idea to keep the original keys in the object and only add the values to the lowercased keys:

```javascript
for (const key in event.headers) {
  event.headers[key.toLowerCase()] = event.headers[key];
}
```

**Comment by pmuens** [comment]
@dragonprojects thanks for reporting!

That makes sense. I move it to the v2 milestone since this introduces be a breaking change for existing users.

**Comment by dougmoscrop** [comment]
Could we make it non-breaking by setting the lower case version and leaving the existing case version?

**Comment by pmuens** [comment]
@dougmoscrop thanks for your feedback 👍 

Can you give an example how this might look like in practice? Thanks!

**Comment by dougmoscrop** [comment]
instead of:

```javascript
const headers = {};
for (const key in event.headers) {
  headers[key.toLowerCase()] = event.headers[key];
}
event.headers = headers;
```

just:

```javascript
for (const key in event.headers) {
  event.headers[key.toLowerCase()] = event.headers[key];
}
```

**Comment by Toosick** [comment]
@dougmoscrop Your lowercase doesn't work. Use reduce if you want. I choose Lodash. Here is the method I choose:
```js
event.headers = _.transform(event.headers, (result, val, key) => {
  result[key.toLowerCase()] = val
})
```

**Comment by sharaal** [comment]
@dougmoscrop @Toosick 
If using `Object.keys()` a `for ... of` is needed, then it also works without the need of lodash.

e.g.:
```javascript
const headers = Object.keys(event.headers);
for (const key of headers) {
  event.headers[key.toLowerCase()] = event.headers[key];
}
```

**Comment by Toosick** [comment]
@dougmoscrop Yeah I should of just mentioned it should of been a for of. Let me edit mine.

**Comment by HyperBrain** [comment]
I would use lodash, as it takes care of everything:
```
const loweredHeaders = _.reduce(event.headers, (res, value, key) => _.set(res, _.toLower(key), value), {});
```
This is (1) more compact and (2) safe agains any invalid data. Additionally lodash is most likely faster than the native functionality.

**Comment by sharaal** [comment]
I edited my post to mention both versions. 
I don't want to decide which version (`for ... in`, `Object.keys` or lodash) is better, that's a decision for the contributors, so I added the simplest version just as an example for the wanted outcoming result. :)

**Comment by Toosick** [comment]
@Sharaal I like the not breaking change workaround. Smart.

**Comment by dougmoscrop** [comment]
Sorry, this is about the Lambda function code itself, like @Toosick pointed out; so there's not much serverless can do without getting in to injection/wrapping - which could be a thing, maybe, but not my call but it should never bundle lodash, it should be native js.

If that were the case, I think some HTTP headers can exist multiple times (or at least, do in practice), but API Gateway can't handle it, so people send through different casings. This reduce/fold should merge them in to an array or something.

**Comment by rkcf** [comment]
If you are looking for a workaround in python and you are utilizing requests in your function there is a custom dict implementation to solve this exact issue.  https://github.com/requests/requests/blob/v1.2.3/requests/structures.py#L37

**Comment by smithgraeme** [comment]
@jml6m Do you have Lambda Proxy Integration turned _off_ (in the API Gateway setup)? When it's _on_, Lambda should get an event payload (with headers at event.headers, I just double checked this), but if it's off API Gateway does some mapping/preprocessing that could be mapping things with the structure you're seeing.  See https://medium.com/@lakshmanLD/lambda-proxy-vs-lambda-integration-in-aws-api-gateway-3a9397af0e6d (or AWS' documentation) for more info.

**Comment by alexreg** [comment]
Progress update on this?

**Comment by medikoo** [comment]
I believe this will require an introduction of some extra lambda wrapper (Serverless will have to inject some custom code into lambda) through which decoration of headers could be achieved.

So it can't be achieved cleanly, and (with exception to our [monitoring service](https://dashboard.serverless.com/)), currently there's no other Framework feature that works like that.

**Comment by medikoo** [comment]
Closing due to reasons mentioned in https://github.com/serverless/serverless/issues/2765#issuecomment-523042063

Even if we would consider providing and implementing an aid like that, this will not be bundled with a Framework, but provided as external package/utility
