### ISSUE TITLE
node-uuid module is deprecated

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2767]
ditch the `node-uuid@1.4.7` deprecated module:

```
Eslams-MacBook-Pro:serverless eslam$ npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
...
```

**Comment by pmuens** [comment]
Just looked into this one.

We use `uuid` but `coveralls` uses `request` which uses `node-uuid`:

```
serverless@1.2.0 /app
`-- coveralls@2.11.15
  `-- request@2.75.0
    `-- node-uuid@1.4.7 
```

I've looked into the most recent coveralls version which still uses `request@2.75.0` so we have to wait until `coveralls` updates their `request` dependency (which already has the fix).

**Comment by pmuens** [comment]
Just looked at it again. Still no version bump:

https://github.com/nickmerwin/node-coveralls/blob/master/package.json#L37
https://github.com/nickmerwin/node-coveralls/issues/133

**Comment by pmuens** [comment]
Moving to 1.6 since `node-coveralls` is still not updated...

**Comment by pmuens** [comment]
It happened!!! 🎉 

https://github.com/nickmerwin/node-coveralls/blob/master/package.json#L37
