### ISSUE TITLE
SNS handler timeout

### ISSUE THREAD

**Issue by shauntrennery** [serverless/serverless#2769]
My SNS event hander is timing out. 

Handler signature is:
`processText: (event, context, callback) =>...`

I'm calling the callback as follows:
`callback(null, {event: event})`

     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.2.0

**Comment by pmuens** [comment]
Thanks for opening this up @shauntrennery 👍 

Could you provide more information / the actual code of your function and your handler function code so that we can take a more in-depth look at it?

Thanks!

**Comment by shauntrennery** [comment]
Thanks @pmuens - Big fan of the platform. It's been a pleasure working with it.

My handler logic executes as expected and the console.log as seen below prints out an expected [Function]. The CloudWatch logs report a timeout thou. I picked up this issue as my handler was being called repeatedly. I assume a successful handler callback will remove the SNS message.

from serverless.yml:
```
processText:
    handler: message.processText
    timeout: 30
    events:
      - sns: message-text
```

from message.js:
```
processText: (event, context, callback) => {
    let params = utils.extractParams(event.Records[0].Sns.Message, ['appId', 'toUserId', 'fromUserId', 'message', 'customTagRow'])

    if (params) {
      xandgo.bulkMessage(params.appId, params.toUserId, params.fromUserId, params.message, params.customTags, (err, requestId) => {
        console.log(callback)
        
        if (err) {
          callback(err)
        } else {
          callback(null, {event: event})
        }
      })
    } else {
      callback(new Error('Invalid input parameters.'))
    }
  },
```

**Comment by shauntrennery** [comment]
I have a hunch that it might be related to this line in the Amazon documentation:

> When the callback is called (explicitly or implicitly), AWS Lambda continues the Lambda function invocation until the Node.js event loop is empty.

http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

**Comment by pmuens** [comment]
@shauntrennery thank you very much for your kind words! Really appreciate it 👍  💯 

I could not find anything related to the timeout looking at your code.
I think it might really something related to the event loop.

/cc @eahefnawy @nikgraf

**Comment by shauntrennery** [comment]
After reviewing my entire function along with all it's dependencies, it turns out that the issue is due to a old native notification library opening a HTTP connection to post to an API endpoint and not closing it.

I've replaced the dependency with a newer version and redeployed. Function completes as expected now.

Thank you for all the help on this issue.

**Comment by pmuens** [comment]
Great to hear that you've resolved this one @shauntrennery!

Thanks for posting the solution for your problem here so that others can find it as well.

**Comment by shauntrennery** [comment]
Turns out the actual issue was related to Firebase. I needed to close the connection to the realtime database before completing the function.

`firebase.database().goOffline()
`

http://stackoverflow.com/a/37858899
