### ISSUE TITLE
Out of sync clock can cause deploy to freeze at "Checking Stack update progress..."

### ISSUE THREAD

**Issue by shortjared** [serverless/serverless#2776]
# This is a Bug Report

## Description

On an `sls deploy` the process would get to "Checking Stack update progress..." and hang indefinitely. The actual deploy and cloudformation updates were successful, however no events were ever displayed in the console.

In a CI system this blocks all future steps in the pipeline, and causes an annoyingly long failure.

There were no error outputs, it just hung for awhile until the process was timed out.

I was very suspicious because I was able to deploy from my local machine, and we realized this issue plagued only some of the CI deploys, and it was flaky.

Turns out that it was a clock based issue. The CI clock was 45 seconds in the future which prevented a quickly updating stack from ever polling a single stack event. NTP syncing the CI server clock fixed this issue immediately for all our CI deploys.

### Similar or dependent issues:
* #2115 

### Potential Fixes:

Maybe an easy fix is to look backwards at least a couple minutes (within the range of AWS signatures still being valid)?

**Comment by shortjared** [comment]
https://github.com/serverless/serverless/blob/3b58ec3332563c7a2b6848edf61de528df3dbc07/lib/plugins/aws/lib/monitorStack.js#L23

`monitoredSince.setSeconds(monitoredSince.getSeconds() - 5);` Does look backwards 5 seconds. Still not enough to catch our ~ 1 minute out of sync.

**Comment by shortjared** [comment]
Was researching how long signatures on aws signed requests are... from http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html

> **Protect against potential replay attacks**
In most cases, a request must reach AWS within five minutes of the time stamp in the request. Otherwise, AWS denies the request.

**Comment by pmuens** [comment]
@shortjared any updates on this one?

Not sure if this is an issue directly related to Serverless as it assumes that the clock is synced correctly...

**Comment by mattcorey** [comment]
+1 to this one -- I don't mind that Serverless (or more likely CloudFormation) depends on clocks to be synced correctly -- the AWS API is highely sensitive to clock drift.  My problem here is that Serverless didn't provide any feedback on the issue, and we spent a few weeks on-and-off trying to figure this out.  I happened to notice the clock issue on the server this morning, setup ntpd properly, and things are now working fine.

I expect the CloudFormation is emitting an error of some sort in this situation -- Serverless should be catching it, and displaying it to the user.

**Comment by connaryscott** [comment]
I have also been troubleshooting this for a VERY long time

**Comment by bjfletcher** [comment]
I've had this problem. :/

We need a better algorithm for working out which events are old & not relevant to the current deployment.

**Comment by pmuens** [comment]
Closing this because we're currently tracking the status of this in https://github.com/serverless/serverless/issues/2691

WIP PR will be submitted in a few minutes.
