### ISSUE TITLE
Cron syntax rejected

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2781]
# This is a Bug Report

## Description

In serverless.yml, for one function, my events section is this:
```
        events:
            - schedule:
                rate: cron(55 7-23 * * * *)
```

When I attempt to deploy, I get this error:
```
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: AlertEventsRuleSchedule1
     - Parameter ScheduleExpression is not valid..
```

This AWS doco page seems to indicate this syntax is OK:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html

## Additional Data

* ***Serverless Framework Version you're using***:  1.1.0
* ***Operating System***:  OSX Sierra

**Comment by chris-hailstorm** [comment]
The same error results when the final "*" is removed

**Comment by pmuens** [comment]
Thanks for reporting @chris-hailstorm 👍 

This issue is related to https://github.com/serverless/serverless/issues/2344

**Comment by mthenw** [comment]
Hey @chris-hailstorm 

cron expression is wrong, because 

>You can't specify the Day-of-month and Day-of-week fields in the same Cron expression. If you specify a value in one of the fields, you must use a ? (question mark) in the other.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
