### ISSUE TITLE
Add testing section to credentials section of documentation 

### ISSUE THREAD

**Issue by wamoyo** [serverless/serverless#2783]
# This is a documentation suggestion

## Description

It would be nice to have a tiny section at the end of the credentials page of the documenation that shows users how to test their credentials. `serverless info` would do the trick. These 'Hello World' type of confirmations that things are working smoothly go a long way : )

**Comment by pmuens** [comment]
Thanks for the suggestion @wamoyo 

Closing this one for now since it's not high prio right now and we want to keep the issue count low.
