### ISSUE TITLE
Display "custom" stack outputs always in info

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2788]
# This is a Feature Proposal

## Description

https://github.com/serverless/serverless/pull/2253 introduced a way to display "custom" stack outputs in the `info` CLI output. However this is only shown when one runs the corresponding command in the `--verbose` mode. It would be valuable to show this always (even if one does not use `--verbose`).

**Comment by mhodgson** [comment]
I agree with this. It took me a lot of snooping on GitHub and in the code to eventually determine what is done with those outputs. One small tweak I'd recommend is to NOT log the outputs that are added and used by Serverless. I think this should help reduce clutter but avoid confusion about where/when Outputs are logged.

**Comment by pmuens** [comment]
Closing this one. This PR comment: https://github.com/serverless/serverless/pull/3416#issuecomment-295133210 explains why.
