### ISSUE TITLE
APIG Endpoint Integration Request 'Invoke with caller credentials'

### ISSUE THREAD

**Issue by alexwillingham** [serverless/serverless#279]
Hi! 

I'd like to configure a JAWS APIG endpoint to have 'Invoke with caller credentials' (a nice little checkbox in the UI) enabled on a resource's integration request.  The APIG API docs http://docs.aws.amazon.com/apigateway/api-reference/resource/integration/ specify, 'To require that the caller's identity be passed through from the request, specify the string arn:aws:iam::*:user/*' (for the credentials field).  

I see that JAWS currently specifies null for credentials due to a bug: https://github.com/jaws-framework/JAWS/blob/master/lib/commands/deploy_endpoint.js#L685 (which I should mention appears to be resolved).  What would be the consequences of me setting my regionJson.iamRoleArnApiGateway to the above string ?  

Am I off-base to suggest making api integration request credentials configurable in the lambda awsm.json?

**Comment by vlamic** [comment]
Would be nice to have this back configurable

**Comment by fuyu** [comment]
Bump it up. Can we expect this option be back anytime soon?
BTW, thanks for your hard work guys.

**Comment by alexwillingham** [comment]
@ac360 Thank you!! https://github.com/serverless/serverless/commit/c61e7c3c90704f523895597a086cdc011cd32e6b  Closing.
