### ISSUE TITLE
Mitigating AWS Lamdbda limits

### ISSUE THREAD

**Issue by austinrivas** [serverless/serverless#28]
I'm sure you have already seen this [AWS Lambda Limits](http://docs.aws.amazon.com/lambda/latest/dg/limits.html).

I see the 1.5Gb total limit, and 50mb deploy limits as huge problems for the current deploy script.

Some things that I believe can help mitigate the impact of these limits are:

* Implementing a build pipeline to minify the packaged source, [here is a great example in Gulp](https://medium.com/@AdamRNeary/a-gulp-workflow-for-amazon-lambda-61c2afd723b6)
* Using webpack or another compile time bundler to avoid copying external node_modules

Please correct me if I missed something, just trying to look ahead and identify areas that I might be able to contribute.

- Austin

**Comment by ac360** [comment]
@austinrivas These are great suggestions.  You've been active with this project and it's much appreciated. 

This weekend I'm going to publish the JAWS Road Map which will identify priorities for everyone to focus on.  The Road Map will include your suggestions.  Please know that I will be publicly acknowledging all contributors everywhere JAWS has a presence (e.g., in the repo, on the website, etc.).  Hopefully, we will assemble an awesome team to build the ultimate server-less framework.

**Comment by doapp-ryanp** [comment]
In a pull request I have coming hopefully today, it will partially address the 50mb deploy limit. You will be able to setup file/dir ignores on a function by function basis in the lambda.json metadata file for each function.  I'm of course open to other ideas, just want to prevent you from spending time on solving the problem if you end up liking my solution.

**Comment by ac360** [comment]
@doapp-ryanp Awesome, this sounds super useful.  Can't wait to see it.

**Comment by doapp-ryanp** [comment]
addressed in https://github.com/jaws-stack/JAWS/pull/42

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by eahefnawy** [comment]
AWS recently pumped up the limit to 75GB ... Closing this for now.
Thanks guys! :blush:
