### ISSUE TITLE
API Gateway’s Authorizer for Cognito User Pools

### ISSUE THREAD

**Issue by izogain** [serverless/serverless#2806]
# This is a Feature Proposal

## Description
API gateway supports authentication using Cognito user pool.  This avoids creating a custom authorizer using a lambda function.  Integrating user pools authorizer  within Serverless would make authentication easier for those using AWS cognito.
[Cognito API gateway](http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html)
[AWS announcement ](https://aws.amazon.com/blogs/aws/amazon-cognito-your-user-pools-now-generally-available/)
[API gateway cloudformation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-type) : authorizer for cognito type : COGNITO_USER_POOLS
Thank you.

**Comment by gertjvr** [comment]
There is an existing PR #2141 to allow us to start implementing this.

**Comment by izogain** [comment]
Thank you, i will look into it.
