### ISSUE TITLE
included devDependencies causes warning when installing

### ISSUE THREAD

**Issue by mifi** [serverless/serverless#2811]
# This is a Bug Report

## Description

`npm install -g serverless`

```
└─┬ serverless@1.2.1 
...........
  ├── escope@3.6.0 
  ├── UNMET PEER DEPENDENCY eslint@^3.3.1
  ├── eslint-config-airbnb-base@5.0.3  extraneous
  ├── eslint-import-resolver-node@0.2.3 
  ├── UNMET PEER DEPENDENCY eslint-plugin-import@^1.13.0
  ├── espree@3.3.2 
..........

npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint@^3.3.1 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
```

eslint-config-airbnb-base shouldn't be included in the first place? (in the publish)

It seems eslint-config-airbnb-base is referenced in npm-shrinkwrap.json. Maybe it needs to be re-generated from scratch?
`rm npm-shrinkwrap.json && rm -rf node_modules && npm install && npm shrinkwrap`

Similar or dependent issues:
* #1854

## Additional Data

* 1.2.1
* OSX Sierra

**Comment by dougmoscrop** [comment]
I don't even think they should check in their shrinkwrap; they should produce it during CI or whatever steps release. so they can `npm prune --production` before `npm shrinkwrap`.
