### ISSUE TITLE
report error when we cannot delete a network interface

### ISSUE THREAD

**Issue by brianbegygr** [serverless/serverless#2830]
So I found out about this from our AWS account manager when I exceeded quota.

Running serverless deploy with the VPC, SecurityGroupIds, and SubnetIds defined seems to create a new network interface on each deploy, but doesn't clean up old, unused network interfaces.    

This is happening in 1.1.0.

Is this a known issue?

**Comment by laardee** [comment]
Hi @brianbegygr, does your execution role have `ec2:DetachNetworkInterface` and `ec2:DeleteNetworkInterface` permissions?

**Comment by brianbegygr** [comment]
Good catch, it did not.  Once it has permissions, it seems to clean up after itself.

However, I would have expected it to report an error when it couldn't do so.  

Is it appropriate to put a feature request in for "report error when we cannot delete a network interface?"

**Comment by nicka** [comment]
@braahyan PR #2983 will add the correct IAM VPC permissions by default 👍

**Comment by braahyan** [comment]
@nicka  I think you mean @brianbegygr, but this is great!

**Comment by nicka** [comment]
@braahyan Sorry 😊

**Comment by brianbegygr** [comment]
It's ok.  I'm happy about it too!  :)
