### ISSUE TITLE
invoke passes dictionary to Python lambda, APIG passes string

### ISSUE THREAD

**Issue by wxs** [serverless/serverless#2833]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
`sls invoke` passes a dictionary to the lambda, 

* What did you expect should have happened?
SLS invoke should be equivalent to actually calling through API gateway via HTTP. Instead, through API gateway I receive a string representing my query body, and through invoke I receive a dictionary.

Here's a decorator I have to wrap every handler with:

```
def parse_json_body(func):
    def wrap(event, context):
        # HTTP/API Gateway request will arrive as str
        # whereas SLS invoke arrives as a dict
        # here's hoping this isn't necessary in future
        body = event.get('body', {})
        if isinstance(body, basestring):
            body = json.loads(body)
        event['body'] = body
        return func(event, context)
    return wrap

@parse_json_body
def foo_handler(event, context):
    pass
```

* ***Serverless Framework Version you're using***:
1.2.1

* ***Operating System***:
Mac OS X 10.11.6

**Comment by wxs** [comment]
Realizing this is probably a feature, not a bug, since it allows non-JSON request bodies.

Instead, I'll change the JSON that gets input to invoke to have its body be an escaped string.

**Comment by pmuens** [comment]
Hey @wxs we've recently updated invoke so that it parses JSON strings into JSON --> see https://github.com/serverless/serverless/pull/2701/files

Could you pull from the recent master and try again? Thanks!

**Comment by pmuens** [comment]
@wxs thanks for the response.
That's good to know. We're already planning to support invoke with HTTP endpoints.

`invoke` only works with direct requests to lambdas (not through API Gateway). This way we had to parse the JSON first.

**Comment by dzimine** [comment]
This IS a problem: 

My Lambda function expects a JSON string and converts the string to dict (python, but doesn't matter). There's a number of cases when it is so, like @wxs mentioned, StepFunction is yet another case where Lambda may be called with string representation of JSON. 

Currently, if the string recognized as JSON, [it is automatically converted to JSON](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invoke/index.js#L57-L58). 

Please provide an opt-out to pass a JSON string as string. https://github.com/serverless/serverless/blob/master/lib/plugins/invoke/invoke.js#L38-L40 

Thank you!

**Comment by pmuens** [comment]
@dzimine thanks for the comment. I just opened up an issue (https://github.com/serverless/serverless/issues/3788) to track that.
