### ISSUE TITLE
Extend serverless config credentials to modify and remove credentials

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2838]
# This is a Feature Proposal

## Description

Like it's discussed here: https://github.com/serverless/serverless/pull/2160#issuecomment-263356657.

**Comment by mthenw** [comment]
We shouldn't modify files that are managed by other tools. One-time setup is acceptable IMHO, but not modifications.

**Comment by pmuens** [comment]
Good point @mthenw 

/cc @ac360 @eahefnawy @nikgraf @DavidWells

**Comment by pmuens** [comment]
Yes, removal and modification might be too risky. Adding it to improve onboarding is ok though...
