### ISSUE TITLE
Make sure the `config` command is not displayed in the command list

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#2839]
# This is a (Bug Report / Feature Proposal)

## Description

The config command does nothing since we only support config credentials for now.

## Additional Data

* ***Serverless Framework Version you're using***: latest master
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
I would propose to rename this to `commands w/o implementation shouldn't show up in help`.

We should update the `PluginManager` so that commands without an implementation are not displayed.

**Comment by nikgraf** [comment]
I can work on this tomorrow so you can focus on the metrics plugin.

@mthenw @eahefnawy any objections doing this?

**Comment by dougmoscrop** [comment]
Shouldn't this already be the case?

https://github.com/serverless/serverless/blob/master/lib/classes/CLI.js#L75

**Comment by mthenw** [comment]
Not exactly sure why it shouldn't show up in command list. It's command as any other.

**Comment by pmuens** [comment]
Yes, but it has no implementation.

It is basically a "dead" command.

**Comment by mthenw** [comment]
Yeah, but if we'll remove that how user will know about this command?

**Comment by pmuens** [comment]
This issue discusses the following problem we have right now.

We've just introduced the `serverless config credentials` command. This command is basically a composition of a main command `config` and a subcommand `credentials`.

We only have an implementation for the combination of the main command and the subcommand (`config credentials`) but not one for the main command (`config`). However the `serverless help` command shows both which might confuse the user.

**Comment by mthenw** [comment]
Oh now i understand! Make sense!

**Comment by nikgraf** [comment]
I thought a bit more about it this morning. This could be quite confusing when people develop plugins and just add a command. What if we only hide `config`? It's kind of a special case since we don't want anyone to implement it, but safe it for future usage.

**Comment by pmuens** [comment]
That's true. Could be really confusing for plugin devs. What if we mark it with an `*` as `<not-implemented>` or just leave the description of the help as `<not-implemented>` or something like that?

**Comment by paradigmist** [comment]
I can't use the config command to setup aws credential, is this issue relate to hiding config command?

**Comment by pmuens** [comment]
@paradigmist we'll release v1.3 soon which features the `serverless config credentials` command!

**Comment by paradigmist** [comment]
@pmuens Thanks for your info. Looking forward to the update!

**Comment by dougmoscrop** [comment]
Just to be clear, the command gets hidden when it has no *lifecycle events*, not when it has no *hooks*. If you run a command with no hooks, it prints an error 'there are no hooks'. Maybe that message should be changed to 'There are no plugins that implement the command {x}' or something.
