### ISSUE TITLE
BREAKING - Move slstats to config command

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2843]
# This is a Feature Proposal

## Description

Now we have `config` root command. IMHO it will be better to move `slstats` command there to have clearer api: 

```
serverless config stats
```

It's a breaking change.

**Comment by nikgraf** [comment]
This is good!

**Comment by pmuens** [comment]
Yep sounds like a good idea!

**Comment by pmuens** [comment]
This will be replaced with the `.serverlessrc` file @DavidWells is working on. Closing...
