### ISSUE TITLE
metrics command returning metrics for service

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2846]
# This is a Feature Proposal

## Description

`serverless metrics` (without `-f`) should return aggregated metrics for whole service (all functions in service).

```
$ serverless metrics
December 1, 2016 10:34 AM - December 2, 2016 10:34 AM

Invocations: 19
Throttles: 12
Errors: 1
Duration (avg.): 92ms
```

**Comment by pmuens** [comment]
This looks like a good improvement! Maybe we should add an `All functions combined` or something like that where usually the function name appears if you run this command with a `--function` option.

**Comment by nikgraf** [comment]
I like it. Since we gathering all the data for all the functions I would propose we show data for functions separately. In addition we can add 99th percentile if it's already exposed to the API:

```
December 5, 2016 7:47 PM - December 6, 2016 7:47 PM

All functions
Invocations: 19
Throttles: 12
Errors: 1
Duration (avg.): 92ms
Duration (99th.): 92ms

serverless-simple-http-endpoint-dev-currentTime
Invocations: 0 
Throttles: 0 
Errors: 0 
Duration (avg.): 0ms
Duration (99th.): 92ms

serverless-simple-http-endpoint-dev-createTodo
Invocations: 0 
Throttles: 0 
Errors: 0 
Duration (avg.): 0ms
Duration (99th.): 92ms
```

**Comment by mthenw** [comment]
hmm, IMHO when `-f` is not specified we should show only 

```
December 5, 2016 7:47 PM - December 6, 2016 7:47 PM

All functions
Invocations: 19
Throttles: 12
Errors: 1
Duration (avg.): 92ms
Duration (99th.): 92ms
```

**Comment by pmuens** [comment]
I like and see the value of showing all functions but IMHO it can get pretty confusing if you have many functions. So showing only the stuff for "All functions" might be easier to grasp.

**Comment by pmuens** [comment]
So should we start with @mthenw proposal?

Would start the implementation if everyone is fine with that and submit a PR where we can discuss the implementation details.

**Comment by pmuens** [comment]
Just pushed a PR (#2922) which implements @mthenw proposal
