### ISSUE TITLE
Versioning Documentation

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless#2848]
# Feature Proposal

## Description

The new cli command `config` sounds great.  Except it doesn't appear to have been released with version `1.2.1` and below.  A good chunk of documentation is a bit into the future.

Should a new person see the docs today, they'll be confused when they download the lastest version of serverless and see that a command that's documented, does not work.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: OSX

**Comment by pmuens** [comment]
Closing this since we've added the current version number to the docs page: https://serverless.com/framework/docs/
