### ISSUE TITLE
add C# service template

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2858]
# This is a Feature Proposal

## Description

More about C# programming model http://docs.aws.amazon.com/lambda/latest/dg/dotnet-programming-model.html

**Comment by jimmyp** [comment]
I have a PR nearly ready for this, will put forward something in the next few days.

It's a C# template with a single api triggered handler with the signature `public Response Hello(Request request)` and has a matching integration test as per the rest of the templates.

I had to add a bash build script as creating the zip package from C# source requires multiple commands to package restore, build and then zip (with the correct paths).

I haven't read the contributions guide yet which is really the only thing stopping me from submitting the PR.

Should there be a build file for windows too?

**Comment by mthenw** [comment]
> Should there be a build file for windows too?

We can start with linux only version IMHO.

**Comment by jimmyp** [comment]
Dope, I just had a read and the contribution guide is pretty straightforwards, so I'm just waiting for the integration tests to finish and I'll submit.

I think it's worth putting some thought into the developer experience, I just threw the handler and project.json manually in a text editor, but I think most C# devs use a little more tooling than that? So might be worth considering a template that will match their expectations?

I'd rather get something in and working before we bother with niceties like that though.

**Comment by jimmyp** [comment]
I have the following todo's outstanding:

- [ ] Write documentation
- [ ] Fix linting errors

when I run npm run lint I don't really get much output:

`~/dev/serverless [csharp_dotnetcore_template|✔]
23:11 $ npm run lint

> serverless@1.3.0 lint /Users/jim/dev/serverless
> eslint .
`

What should I be expecting?

Also what kind of documentation should I write? Just something like these?

https://serverless.com/framework/docs/providers/aws/examples/hello-world/node/
https://serverless.com/framework/docs/providers/aws/examples/hello-world/python/#hello-world-python-example

**Comment by pmuens** [comment]
@jimmyp thanks for jumping into this one!

I think the `eslint` output is fine (no issues) if you don't see anything in red on the console...

**Comment by jimmyp** [comment]
Happy to help. Keen to do an fsharp one next :)
