### ISSUE TITLE
Anyway to use Env vars or something like it in template creation?

### ISSUE THREAD

**Issue by malkomalko** [serverless/serverless#286]
First of all, JAWS is the cats pajamas.  In reading over cloud formation docs and using jaws for a while, I'm wondering how you would go about using an envVar or something else to not have a dynamic value for something like an RDS DB NAME.

Any thoughts on this?

Also, do other top level CF keys like "Parameters" get merged in to resources.cloudFormation?  Or just ApiGatewayIamPolicyDocumentStatements, LambdaIamPolicyDocumentStatements and Resources?

Cheers!

**Comment by shortjared** [comment]
Do you mean, were you to create an RDS Resource in CloudFormation, how could you make it so it wouldn't have the -78w3lkjslksf stuff at the end? That is not possible to get a static name in the context of CloudFormation. CloudFormation does that for resource tracking / state management.

As far as the other top level CF keys.
https://github.com/jaws-framework/JAWS/blob/ad1bcd9dccaf56fb1afbf336b6e18688116fffa4/lib/commands/postinstall.js#L164-L219

Looks like it is just ApiGatewayIamPolicyDocumentStatements, LambdaIamPolicyDocumentStatements and Resources.

Parameters may not be a bad add though.

**Comment by eahefnawy** [comment]
we've introduced the concept of variables to fix this issue. [Here's the docs for more info](http://docs.serverless.com/docs/templates-variables)
