### ISSUE TITLE
Invoke Local: Python Support

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2862]
We'd love to add support for Python in invoke local. The way this would work is to spawn a child process that runs a python binary `bin/invoke-local-python` that would handle this local invocation.

Our hero @ryansb [wrote this functionality in v0.5.6](https://github.com/serverless/serverless/blob/8239e9ca030bfbfa3e8c3f3a9d90aa6af6aec83b/lib/RuntimePython27.js) but was dropped during the big transition to v1. Would be awesome if we bring it back 😊 . It'd be great help for us if someone could jump on this so we'd include it in the next release.

Related: #2700, #2864

cc/ @serverless/vip

**Comment by bennybauer** [comment]
@ryansb are you already on it?

**Comment by WooDzu** [comment]
Just a little suggesion or maybe a warn on this one as it is worth noting that Python lambda might be an virtualenv package with binaries copiled for AWS Linux which brings up a lot of additional challenges to invoke locally.

**Comment by ryansb** [comment]
Yup, working on it. I'll have a first patch around the end of the week.

**Comment by eahefnawy** [comment]
This won't make it to v1.4.0 ... Moving to next release 😊

**Comment by eahefnawy** [comment]
Won't make it in the v1.5 release either #help_wanted 😊

**Comment by danlg** [comment]
@ eahefnawy Invoke Local for Python would be very useful ! Please reopen the case and schedule it for next release. Thanks

**Comment by pmuens** [comment]
@danlg thanks for your comment.

Local invocation for Python runtimes has been added in the meantime.
