### ISSUE TITLE
Lambda VPC support?

### ISSUE THREAD

**Issue by malkomalko** [serverless/serverless#287]
It looks like vpc support will be dropping later this year and will allow for more support through things like RDS.  Is this on the roadmap?

**Comment by justingreenberg** [comment]
from what i understand, lambda/VPC setup will be a two-step process:

1.  VPC:  create security group to accept inbound lambda traffic and attach it to target subnet
2.  Lambda:  specify VPC, subnet and security group, and attach IAM role (EC2 stuff)

on the Lambda side of things, jaws could use a flag on `module create` to enable VPC support and query user for resource info (if the targets are available—VPC, subnet and security group). then attach whatever IAM roles EC2 requires during setup. likewise, it will be possible to retroactively attach VPC to existing lambdas, so similar functionality could be included in a `module update` command

how do you see VPC setup fitting into JAWS workflow?

**Comment by doapp-ryanp** [comment]
We will for sure be putting Lambda VPC support into JAWS when its released. I personally need it, so it will be a high priority.

With that said, I think its too early to speculate how it will be integrated into JAWS.  My hunch is it wont be supported in CloudFormation out of the gate, which will be a pretty big bummer.

Stay tuned.

**Comment by JamieCressey** [comment]
+1

**Comment by krzysu** [comment]
+1

**Comment by eahefnawy** [comment]
VPC support is now available in Serverless v0.5 :blush:
