### ISSUE TITLE
Availability during deployment

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2876]
This is a question.

We have a normal dev/test cycle for our Serverless services & functions.  Availability isn't a main concern in the earlier stages, but is important for updates once we've reached production.

When we run "sls deploy", at when does the current/old function become unavailable and when does the new function become available? Is there ever a moment in time that an inbound request can't be fulfilled because the service as a whole or individual function is in an in-between state?

Ideally the old version would be available until the nanosecond the new function is available.

**Comment by pmuens** [comment]
Great question! Pinging our @serverless/vip team which has great experience using Lambda in production!

**Comment by johncmckim** [comment]
My understanding is that Lambda doesn't go down during a deploy. But during a deploy you could be served by either the new or old function.

From the [FAQs](https://aws.amazon.com/lambda/faqs/)

> Q: Do my AWS Lambda functions remain available when I change my code or its configuration?
> Yes. When you update a Lambda function, there will be a brief window of time, typically less than a minute, when requests could be served by either the old or the new version of your function.

If this is an problem for you, you should designing your lambda functions so that it can process both the old and new events.

**Comment by erikerikson** [comment]
John is correct.  Note that you may see increased latencies due to cold starts during the transition but this is an artifact Amazon can and is likely to solve for over time.

**Comment by mthenw** [comment]
Exactly, Lambda deployments are eventually consistent.
