### ISSUE TITLE
Cannot find module 'uuid'

### ISSUE THREAD

**Issue by anzileiro** [serverless/serverless#2877]
{
  "errorMessage": "Cannot find module 'uuid'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/handler.js:8:14)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}

**Comment by pmuens** [comment]
@anzileiro thanks for raising this issue. Could you provide a little bit more information how we can reproduce this?

Is this something you face when you use the Serverless CLI tool or is this something in your Lambda / Service?

**Comment by mthenw** [comment]
@anzileiro could you use issue template that we provided?
