### ISSUE TITLE
Centralize Provider Default Values

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2883]
We have some duplication in setting the defaults of some provider specific variables. For example [memorySize](https://github.com/serverless/serverless/search?l=JavaScript&q=1024&utf8=%E2%9C%93).

We should centralize all those default variables in the provider module, or wherever would make sense to tune down on duplication.

**Comment by medikoo** [comment]
https://github.com/serverless/serverless/issues/8107 proposes to keep such settings in `serlveress.baseConfiguration`.

Closing this in favor of #8107
