### ISSUE TITLE
Add support for bitbucket to install command

### ISSUE THREAD

**Issue by morlenefisher** [serverless/serverless#2889]
# This is a  Feature Proposal

## Description
This is a Feature Proposal

Description

It would be great to have the ability to install from public bitbucket repositories as well as github ones.

* currently only github.com repositories are supported
* looking at the install.js there would need to be modifications in the url construction
* would also be good but not urgent to be able to download alternative branches

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #2721

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1/1.3

**Comment by pmuens** [comment]
Thanks for the suggestion @morlenefisher 👍 

Closing since we're currently only supporting GitHub URLs. However this can be easily achieved with a separate plugin.
