### ISSUE TITLE
Serverless doesn't properly wait for deployment to finish in case there is a nested stack

### ISSUE THREAD

**Issue by tgjorgoski** [serverless/serverless#2898]
# This is a Bug Report

## Description

* What went wrong?
I used resources part of serverless.yml to include a nested stack from a cloudformation file located on s3. I also set the usual serverless resources to be dependent on this stack... Something like this:

~~~~
resources:
  Resources:
    outsideStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: 'https://xxx.s3.amazonaws.com/user-pool-client.cform'
    IamRoleLambdaExecution:
      DependsOn:
        - outsideStack
~~~~
Everything deploys fine, the nested stack deploys first, and the default iam role and the functions only after that. However the problem is that serverless command returns immediately after the *nested stack* is completed, and doesn't wait for the whole stack to finish. 
One can see this in two ways:
-By observing that even the serverless command is finished, the deployment is still going on in aws CloudFormation console.
-If the stack is created for the first time, the `functions` and `endpoints` report is empty, even there are functions with API Gateway endpoints defined in serverless.yml

* What did you expect should have happened?
For serverless command to wait for the whole stack to finish, and only then return ids of all created endpoints and functions.

* What was the config you used?
AWS

* What stacktrace or error message from your provider did you see?
No stacktrace, everything seemed fine, just empty result:

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***:MacOS Sierra 
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by tgjorgoski** [comment]
It seems changing line 51 of monitorStack.js from:

~~~~
if (event.ResourceType === 'AWS::CloudFormation::Stack' ) {
~~~~
to:
~~~~
if (event.ResourceType === 'AWS::CloudFormation::Stack' 
    && event.StackId === event.PhysicalResourceId) {
~~~~

fixes it as only in the case of the nested stack those are different (StackId being the whole stack, and PhysicalResourceId being the nested stack)

**Comment by pmuens** [comment]
@tgjorgoski sounds good! Could you provide a PR?

That would be awesome!

**Comment by tgjorgoski** [comment]
@pmuens , sure, though I've never done PR to github, so would probably need some help.
I created branch locally, however when I try to push it, I get this:
~~~~
> git push origin fix-deployment-with-nested-stack
ERROR: Permission to serverless/serverless.git denied to tgjorgoski.
fatal: Could not read from remote repository.
~~~~

**Comment by pmuens** [comment]
Hey @tgjorgoski sure thing. At first you need to fork Serverless and then create a branch in your fork. After that you submit a pull request from your fork to the official Serverless repository.

Here's a guide on how to do that:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

Let us know if you need any further help! Together we make it 💪
