### ISSUE TITLE
set charset in the content type response in the APIG method resposne

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#290]
Currently jaws defaults the APIG method response to `application/json`.  It needs to be `application/json;charset=UTF-8` otherwise you will run into encoding issues on the response.

![image](https://cloud.githubusercontent.com/assets/1036546/10984157/376a63da-83dd-11e5-9c41-f336e7147e28.png)

**Comment by eahefnawy** [comment]
@doapp-ryanp this issue is pretty old. Do you still feel this change is necessary considering all of our changes over the past few months?

**Comment by doapp-ryanp** [comment]
Yep its still needed.  Currently and APIG endpoint deployed with serverless v 0.5 produces a content-type header without the charset:

`Content-Type: application/json`

If charset is omitted, the default is `ISO-8859-1`.  See the [W3C](https://www.w3.org/International/articles/http-charset/index) doc about how important it is to explicitly set the charset parameter.  Its very straight forward.  

Specifically:

> A Unicode encoding such as UTF-8 is a good choice for a number of reasons.

**Comment by eahefnawy** [comment]
Oh so if I understand this correctly, we just need to change this line:
https://github.com/serverless/serverless/blob/master/lib/Endpoint.js#L39

to: 
`_this.responses['default']['responseTemplates']['application/json;charset=UTF-8'] = '';`

does that make sense?

Thanks for the tip 😊

**Comment by doapp-ryanp** [comment]
Yup I think that should do it

**Comment by doapp-ryanp** [comment]
Actually no, it needs to be in the response model (not response template) per my screenshot above. I think it can be in the response template as well.

I can't figure out how to set the empty response model via serverless templates - keep getting an error. Any ideas?

```
...
"apiDefault200Response": {
    "statusCode": "200",
    "responseParameters": {
      "method.response.header.Access-Control-Allow-Origin": "'*'"
    },
    "responseModels": {
      "Empty":"application/json;charset=UTF-8"
    },
    "responseTemplates": {
      "application/json;charset=UTF-8": ""
    }
  }
...
```

**Comment by doapp-ryanp** [comment]
OK got it, here is what it looks like:

```
...
"apiDefault200Response": {
    "statusCode": "200",
    "responseParameters": {
      "method.response.header.Access-Control-Allow-Origin": "'*'"
    },
    "responseTemplates": {
      "application/json;charset=UTF-8": ""
    },
    "responseModels": {
      "application/json;charset=UTF-8": "Empty"
    }
  }
...
```

**Comment by eahefnawy** [comment]
thanks @doapp-ryanp you're awesome! 😊 ... Final question though, I might be wrong, but isn't this configuration allows for CORS to be enabled?

```
    "responseParameters": {
      "method.response.header.Access-Control-Allow-Origin": "'*'"
    },
```

If that's so, does that mean we don't need the CORS plugin anymore? (it seems super easy to enable CORS this way!) and do you really think we should enable it by default?

If not, then what does it do exactly?

**Comment by laardee** [comment]
@eahefnawy, CORS plugin adds `OPTIONS` preflight endpoint for resources also. Of course you defined `OPTIONS` endpoint manually, but using the plugin is easier.

**Comment by eahefnawy** [comment]
@doapp-ryanp alright, I just pushed your suggestion in 5e370c760f185b7e49cc6de46aed1bb69d6b80e8. Could u take a look and see if it makes sense. I'm testing it now :)

@laardee thanks for the clarification I forgot about the `OPTIONS` endpoint 😊

**Comment by eahefnawy** [comment]
Awesome! It works! Thanks a lot @doapp-ryanp ... Finally closing this aging issue 😊 
<img width="712" alt="screen shot 2016-04-12 at 7 22 43 pm" src="https://cloud.githubusercontent.com/assets/2312463/14459760/006daf48-00e4-11e6-95f2-b8413969eeed.png">

**Comment by doapp-ryanp** [comment]
@laardee this my be personal pref but I much prefer manually defining my `OPTIONS` endpoints. Much more flexible and easy to do via templates. See https://github.com/joostfarla/serverless-cors-plugin/issues/22 for more reasoning.

**Comment by doapp-ryanp** [comment]
@eahefnawy sorry just saw this:

> If that's so, does that mean we don't need the CORS plugin anymore? (it seems super easy to enable CORS this way!) and do you really think we should enable it by default?

Yes, this means the CORS plugin is no longer needed. Lots of benefits going this way. See https://github.com/joostfarla/serverless-cors-plugin/issues/22
