### ISSUE TITLE
Add F# service template 

### ISSUE THREAD

**Issue by jimmyp** [serverless/serverless#2900]
# This is a Feature Proposal

## Description

Much like #2858 except using F#

**Comment by jimmyp** [comment]
I'm happy to jump on this one too

**Comment by jimmyp** [comment]
I've seen the cleanup PR #2896 so assume I'll just implement along the lines of the final product for csharp?

**Comment by jimmyp** [comment]
I would like to see the csharp released first so I can tweak any rough edges on the developer experience. When would that happen?

**Comment by pmuens** [comment]
@jimmyp thanks for opening this one! 👍 

Would be awesome if you could provide a F# service template! I think @mthenw is done with his refactoring PRs?!

**Comment by mthenw** [comment]
@jimmyp c# template will be released with 1.4 version, next week. IMHO there is no need to wait for that, you can provide PR right a way if you want.

I removed build script to reduce confusion.

**Comment by jimmyp** [comment]
No worries, I might take a crack this weekend. Thanks guys.

**Comment by jimmyp** [comment]
Actually I'll need to think about the type signature of the handler a bit.
How to angle deserialisation and such. Any suggestions welcome!

**Comment by jimmyp** [comment]
I wont get to this until the new year now, if anyone else is keen happy to step aside

**Comment by pmuens** [comment]
@jimmyp thanks for the update! No need to hurry 👍

**Comment by pmuens** [comment]
Thanks for opening @jimmyp 

Closing this for now since #3044 was opened and worked on in #3045
