### ISSUE TITLE
API Gateway issue when query string has single quote

### ISSUE THREAD

**Issue by konstantinvlasenko** [serverless/serverless#2901]
# This is a Bug Report

## Description

* What went wrong?
Having issue by passing a single quote as part of my query string parameter value. The issue is because of this line of code https://github.com/serverless/serverless/blob/cb9f8187e14c333d6a521b8f05ea3e07de126f3e/lib/plugins/aws/deploy/compile/events/apiGateway/lib/method/integration.js#L111

From [AWS documentation](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html):

> This function will turn any regular single quotes (') into escaped ones (\'). However, the escaped single quotes are not valid in JSON. Thus, when the output from this function is used in a JSON property, you must turn any escaped single quotes (\') back to regular single quotes ('). 
`$util.escapeJavaScript(data).replaceAll("\\'","'")`
* What did you expect should have happened?
I would expect the following fix:
```
#set ( $k = $util.escapeJavaScript($key) )
#set ( $v = $util.escapeJavaScript($map.get($key)).replaceAll("\\'", "'") )
"$k":"$v"
```
## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: Windows 7

**Comment by pmuens** [comment]
@konstantinvlasenko thanks for reporting 👍 

Seems to be related to this one: https://github.com/serverless/serverless/pull/2808
