### ISSUE TITLE
'invoke local' ignores the AWS profile specified in serverless.yaml

### ISSUE THREAD

**Issue by brunobelotti** [serverless/serverless#2903]
# This is a Bug Report

## Description

The **invoke local** command ignores the AWS profile specified in _serverless.yaml_ (`profile: bbb-dev`) and uses the default one `test-cli` (which, in my case, doesn't have access to a SNS topic, hence the invocation fails).

`
message: 'User: arn:aws:iam::*******:user/test-cli is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:*******:bbb-test',
`

If I invoke it remotely (i.e. omitting the `local` option), everything works.

_Is that a known issue or am I doing something wrong? Thanks! :)_

## Additional Data

* ***serverless version: 1.3.0***:
* ***Mac OS X 10.11.6***:

```
  Authorization Error ------------------------------------

     User: arn:aws:iam::xxxxxxxxxxx:user/test-cli is not
     authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:xxxxxxxx:bbb-test

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.3.0
```

**Comment by eahefnawy** [comment]
@brunobelotti thanks for reporting. You're right, this is an issue. But I think the only way to fix it is to set the API keys env vars locally based on the profile you provided to really emulate lambda credentials, because we don't really have access to your actual lambda code (which might even use other profile on its own).

But I'm not sure it would be a good idea to mess with your local aws keys env vars. Got any other ideas?

Also, I think a quick fix for you is to explicitly use the credentials you want inside the lambda code. But I understand this is not at all convenient.

**Comment by brunobelotti** [comment]
Hi @eahefnawy, thank you for your time.
Yep, you are right: now that I think about it, it makes perfect sense.

An explanation to the "_later myself_" (and others possible viewers of this issue): the code is running on the local machine, as a "normal" Nodejs app, so there is no way to specify the profile used by the _aws-sdk_ inside the code, which will eventually fall back to the default user in the AWS credentials file (unless otherwise "_forced_" with one of the above mentioned methods).
During _live_ invocations, on the other hand, AWS set the proper user (or role) on the fly.

The best way, IMHO, is using one env var with a profile name (not the credentials directly), and then refer to it into the code. 

The [AWS official suggested way](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html) is setting  ```AWS_PROFILE```, like so:

 ```$ AWS_PROFILE=user-name node index.js```

Do you think it makes sense to _promote_ this as the default behaviour of the framework, and set the profile specified in the ```serverless.yaml``` file just before running Nodejs?
Didn't really dig into the code yet, so I'm unaware of the technical challenges, but if you think it's doable and you point me in the right direction, I could certainly take a look. :)

**Comment by pmuens** [comment]
Hey @brunobelotti thanks for your reply. The code for `invokeLocal` can be found here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js

Maybe we can add a quick note in the docs about invoke local and AWS profile usage...

**Comment by brunobelotti** [comment]
I finally found the time to write an update! :)

Setting the env var `AWS_PROFILE` (on the machine or in the stage env var in `serverless.yaml`) works (and it could also be a nice `--profile` option for invoke local).

I took a look at the code, and injecting the `AWS_PROFILE` should be doable, but that doesn't address the problem fully (nor adding a `--profile` parameter).

Unfortunately, `AWS_PROFILE` is **ignored** in the *"real lambda environment”* (i.e. `invoke lambda` or via API Gateway), because in the background `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set with the a temporary pair for the IAM execution role (and they are prioritised by the `AWS.Config()` ).

I thought a lot about this issue, and the only solution I found to have a “reproducible” environment, is the following:

  - create a separate policy for the lambda execution role (instead of inline like now)
  - create a new, specific IAM user
  - attach the policy to both role and user, so that it's shared
  - retrieve the key/secret pair of the user and store them somewhere (`~/.aws/credential` profile?)
  - set and automatically inject the `AWS_PROFILE` during the `invoke local`

I tested 99% of this and it works, but automate the process is a completely different matter (although probably possible and, IMHO, pretty important to make `invoke` and `invoke local` consistent in the long term, security and permission wise).

(Disclaimer: I only thought about the js SDK, but should be pretty similar with all SDKs).

Thoughts, anyone?
Is it worth it to write an entirely different, new issue (as requested enhancement)?

I also wrote an addendum for the documentation, take a look:

----------------

## Resource permissions

Lambda functions assume an *IAM role* during execution: the framework creates this role, and set all the permissions provided in the `iamRoleStatements` section of `serverless.yaml`. 

Unless you explicitly state otherwise, every call to the AWS SDK inside the lambda function is made using this role (a temporary pair of key/secret is generated and set by AWS as environment variables, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).
  
When you use `lambda invoke local`, the situation is quite different: the role isn't available (the function is executed on your local machine), so unless you set a different user directly in the code (or via a key pair of environment variables), the AWS SDK will use the default profile speficied inside you AWS credential configuration file.

Take a look to the official AWS documentation (in this particular instance, for the javascript SDK, but should be similar for all SDKs):

- [http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html)
- [http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-lambda.html](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-lambda.html)

Whatever approach you decide to implement, **be aware**: the set of permissions might be (and probably is) different, so you won't have an exact simulation of the *real* IAM policy in place.

----------------


Do you think it's clear enough? Any suggestion?
Is it all right including links to official AWS docs?

I have a pull request ready for the docs, let me know if you want me to change something or go for it. :)

**Comment by pmuens** [comment]
Thanks for the very detailed updated @brunobelotti ! 👍 

/ccing @eahefnawy here!

**Comment by silvexis** [comment]
I chased around what I thought was an odd bug for a few hours today because I mistakenly assumed `invoke local` would use the profile specified in my serverless.yaml. I'd like to strongly put in a vote for a `--profile` option for `invoke local` to make it explicit what profile will be used for local execution or by default pick up the profile from serverless.yaml because that's more likely to be the right profile you want to use vs. leaving it to whatever your default profile is. 

To avoid further confusion in the future It might also be useful for `invoke local` to inform the user of what profile or user is us being used for execution and warn them that local permissions can likely  differ from those used once deployed

**Comment by klunejko** [comment]
Might be a good idea to at least mentioned in the docs. 

Just wasted close to an hour trying to figure out why invoke local wasn't using the specified credentials.

https://serverless.com/framework/docs/providers/aws/guide/credentials/

Thanks to Bruno for the env hint. Right now I'm using the following:

`provider:
  environment:
    AWS_PROFILE: profile-from-credentials-file`

**Comment by brunobelotti** [comment]
Hey @pmuens, I think @klunejko is right, so I added a short warning in the doc (PR #3289).
Can you please check if it's relevant and the text? (BTW, thank you for the last PR corrections: I have no idea how I can still manage to leave so many mistakes after reading it 30 times!) :)
Cheers!

**Comment by pmuens** [comment]
Hey @brunobelotti thank you very much for the doc updates! Much appreciated!

Just reviewed and merged them.

> BTW, thank you for the last PR corrections

You're welcome! Thank you for taking time to improve the project 🍻

**Comment by pmuens** [comment]
Closing this for now since an update to the docs was done recently.

**Comment by qrimp** [comment]
Old topic, however, for those still looking for a solution, I got my AWS_PROFILE to work using the env option in the launch.json as so:
            "env":{"SLS_DEBUG":"*","AWS_PROFILE":"profile-name"}

FULL launch.json example:
{
    "version": "0.2.0",
    "configurations": [        
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/node_modules/serverless/bin/serverless",
            "args": [
                "invoke",
                "local",
                "-f",
                "yourFunctionName",
                "-d",
                "{}"
            ],
            "env":{"SLS_DEBUG":"*","AWS_PROFILE":"profile-name"}
        }
    ]
}

----------------
I could not get it to work using the environment variable in the serverless.yml as indicated by klunejko above, but thank you sir for pointing me in this direction!
