### ISSUE TITLE
`sls create` overwrites existing Python/JS files in directory

### ISSUE THREAD

**Issue by ryansb** [serverless/serverless#2909]
# This is a Bug Report

## Description

When running `sls create -t aws-python` in a directory where a `handler.py` file already exists the file is overwritten with the base handler. This isn't the behavior I expected, and could result in losing code if the file isn't checked into version control yet (which it wouldn't be, if you're just beginning a project).

I propose having the `sls create` command check if a file exists before overwriting it, to avoid overwriting files that users have already created. Additionally, it would be nice to print out a message along the lines of `The file [name] already exists, and sls will not overwrite it. Move the file and try again if you want sls to write a new [name]`

Similar or dependent issues:
* #2388 (similar)

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: Linux
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by aysark** [comment]
I can work on this.

**Comment by pmuens** [comment]
Closed with #3048
