### ISSUE TITLE
AWS Lambda Environment Variables support

### ISSUE THREAD

**Issue by konstantinvlasenko** [serverless/serverless#2913]
# This is a Feature Proposal

## Description

We want to use serverless --noDeploy feature to pass a package to Jfrog Artifactory. And then to be able to deploy to several different AWS Accounts from there. We'll use "Fn::Import" approach for these variables. So we'll get true stage independent deployment package.

For feature proposals:
* Pass connection configuration for RDS MySQL trough [AWS Lambda Environment Variables](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html)
Right now I am using **connect.json** as part of my serverless deployment. But I want to move this configuration out of deployment package to[ AWS Lambda Environment Variables](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html)

If I got it right current serverless version (see below) doesn't support this feature.

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0

**Comment by mthenw** [comment]
@konstantinvlasenko env vars support has been released with 1.2 version. You can read more about that here https://serverless.com/blog/serverless-v1.2.0/.
