### ISSUE TITLE
VPC and SecurityGroup not set on Deploy

### ISSUE THREAD

**Issue by vchan2002** [serverless/serverless#2925]
I am not sure whether this is related to all of the threads that's related to the VPC issues that that been discussed.

Rather than seeing a error that complains about not having sufficient rights, the function deploys properly, but none of the VPC or Security group settings gets passed on to the Lambda function.

provider:
  name: aws
  runtime: python2.7
  role: {ARN of role}
  vpc:
    securityGroupIds:
      - {SG}
    subnetIDs:
      - {SUBNET1}
      - {SUBNET2}
 
I already have an IAM role that has the Lambda rights and I wish not to create new ones for every function.

What am I doing incorrectly?

**Comment by elad** [comment]
@vchan2002 just came across this, too. Did you solve it?

**Comment by patrykcieszkowski** [comment]
Weird. It doesn't work, while being set under `provider`. Does just fine, if you set it to individual functions on it's own.

**Comment by pmuens** [comment]
Hmm. Strange. @patrykcieszkowski could you share your `serverless.yml` file so that we can reproduce this and look into it?

**Comment by patrykcieszkowski** [comment]
@pmuens I'm really sorry for bringing the mess, and for such a late reply. I completely forgot about commenting here. The issue wasn't caused by Serverless, it was my VPC config. :) But thank you for your time anyway!

**Comment by pmuens** [comment]
Thanks for getting back @patrykcieszkowski 👍 

No worries! Thanks for sharing the solution to the problem! I hope everything is fine again.
