### ISSUE TITLE
serverless.yml in aws-java-template should include documentation about integration:lambda

### ISSUE THREAD

**Issue by heapifyman** [serverless/serverless#2938]
When using `aws-java-maven` template, it seems that one has to add `integration: lambda` to the http events definition. Otherwise the API Gateway stuff won't be set up correctly and calling the HTTP Gateway endpoint as shown in the getting started video will not succeed.

Some information about this should be added to the comments in the generated serverless.yml and ideally, it should also be mentioned in the documentation or getting started videos.

Interestingly, `integration: lambda` setting does not seem to be required when using the nodejs template.

Tested with serverless 1.3.0

**Comment by bbilger** [comment]
IMO the Java examples are just outdated and they should be updated to use lambda-proxy integration (since this is the default now) like the JavaScript example does. See: http://forum.serverless.com/t/api-gateway-inst-created-ok-in-java-project/551

**Comment by pmuens** [comment]
@bbilger yes, that would be definitely awesome.

Could you provide an update for this so that the `LAMBDA-PROXY` integration is used? Would be awesome if you could PR something for that 💯

**Comment by bbilger** [comment]
@pmuens
 I'll try to find some time for this next week but I can't promise anything.

**Comment by pmuens** [comment]
@bbilger great! No hurry. 👍 

Let us know if you need any help!

**Comment by bbilger** [comment]
@pmuens 
I updated the Java templates: https://github.com/serverless/serverless/pull/2971
Let me know if you have any doubts.

**Comment by pmuens** [comment]
Thanks for the PR @bbilger ! 👍 

Will look into it today!
