### ISSUE TITLE
Don't create bucket referenced in event if same name appears in Resource:

### ISSUE THREAD

**Issue by funkybob** [serverless/serverless#2939]
# This is a Feature Proposal

## Description

Currently when an event involves s3, the bucket is implicitly created.

However, if the bucket is already defined in the resources clause, you wind up with a duplicate create error.

It would be nice if the events compiler could check if such a bucket exists first, before trying to create it.

**Comment by asprouse** [comment]
Same issue #2717 there is an open PR to fix #2750

**Comment by pmuens** [comment]
Closing this as we're tracking the progress in https://github.com/serverless/serverless/issues/2717
