### ISSUE TITLE
Package level artifact usage broken when using "serverless deploy function"

### ISSUE THREAD

**Issue by jros2300** [serverless/serverless#2946]
# This is a Bug Report

## Description

If you're using Java8 as the runtime and you deploy a funtion with "serverless deploy function --function xxx" a zip file is created and deployed as the function, instead of the jar file created with Maven/Gradle

It should use the jar file created with Maven/Gradle and avoid the compile phase.

## Additional Data

* 1.3.0
* mac
* error running the function (it's a zip file and not the jar with the classes)

## Workaround

For now I've workaround it adding the same artifact name to all the functions
   package:
      artifact: target/endesa-${opt:stage, self:provider.stage}.jar
This way in the packageService.js line 75, the build of the zip file is skipped, it should be skipped in any case with we're using java8 as runtime and use the global artifact parameter.

**Comment by eahefnawy** [comment]
@jros2300 thanks for reporting. It seems that you already got the fix figured out, we'd love a PR if you could 😊 

> It should use the jar file created with Maven/Gradle and avoid the compile phase.

Just to be clear, this is just an enhancement, right? so in both cases `sls function deploy` works, but uploading jar would be a little faster?

**Comment by jros2300** [comment]
@eahefnawy, that's only a workaround, if you don't specify the package inside the function it creates a zip file and upload the zip to the lambda code (and it fails because lambda for Java is expecting a jar). In the packageService.js line 75 it should check if the runtime is java and avoid the zip creation.

**Comment by pmuens** [comment]
We just got some updates (and fixes) for the Java templates with this PR: https://github.com/serverless/serverless/pull/2971

If one uses those templates then everything should be good.

I agree that Serverless should somehow detect if it should zip up everything or do something else (like creating a `.jar`)

I'd not recommend to change something in `packageService` as this is provider (and therefore runtime) independent.

**Comment by bbilger** [comment]
Cannot check what the code (function deploy) actually does BUT
The PR won't fix this issue.
IMO: for Java (and other non-JS runtimes?) serverless should not (try to) package anything but use the artifact built by Maven or Gradle.
This can either be an (Uber-) jar or a zip. The zip generated by Gradle, however, is different from the one serverless is trying to package here.

**Comment by selectedpixel** [comment]
Also having this issue.

**Comment by talawahtech** [comment]
This is definitely a bug and it affect a new project created with serverless **1.7** using the **aws-java-maven** template . When trying to deploy an individual function serverless just packages up the entire source code directory and uploads everything, including uncompiled code. This will trigger a class not found error when AWS Lambda attempts to call the handler.

It think serverless should default to using the top-level package/artifact that is already defined. As a workaround I used had to add a package/artifact entry to my function as well to get it working:

```
service: myservice

provider:
  name: aws

package:
  artifact: target/myservice-dev.jar

functions:
  myFunction:
    handler: com.company.MyHandler
    package:
          artifact: ${self:package.artifact}
```

It simply references the top level artifact name that was already defined, which is the jar file compiled by maven.

**Comment by selectedpixel** [comment]
The other bummer about this is that it uploads every package and every dependency due to the maven shade plugin. This seems like a pretty standard convention with JAVA as I spent some time try to figure out how to create individual jar files per function with only the necessary dependencies and there wasn't a really great solution. The downfall is that I have to upload the 22mb package for every change. Seems like this should go faster, but it takes about a minute or two every time even with 5mb up.

**Comment by puug** [comment]
Just came across this and tried the workaround mentioned by @talawahtech but to no avail. Looking at https://github.com/serverless/serverless/blob/07f837ddb67a40cee3e0c6b238e165023b4b7725/lib/plugins/package/lib/packageService.js#L68 it appears it no longer respects supplying an artifact entry at the function.package level?

**Comment by pmuens** [comment]
@puug how does your `serverless.yml` look like?

AFAIK we've tested all the cases during the transition from `deploy --noDeploy` to `package`, right @eahefnawy (at least according to our list --> https://github.com/serverless/serverless/issues/3467).

Maybe something was changed in the meantime 🤔

**Comment by eahefnawy** [comment]
@puug we still support packages at the function level. Maybe there's an issue with Java/Jar specifically?

I don't have any experience with Java so I won't be able to confirm that though

**Comment by pmuens** [comment]
@eahefnawy have you tested package artifact support at the function level when using `serverless deploy function`? I haven't done that when testing the `package` / `deploy` separation.

**Comment by puug** [comment]
@pmuens @eahefnawy thanks for the quick replies. My `serverless.yml` pretty much mirrored the one @talawahtech pasted, referencing the project level package artifact. And yes, tested via `deploy function -f myFunction` - it uploads the project zip rather than my built artifact via maven/gradle (which does work with a vanilla `deploy`).

**Comment by pmuens** [comment]
Thanks for getting back @puug 

So it seems that `deploy function` is broken when using package artifacts at the function level.

/cc @eahefnawy 🔝

**Comment by javierros** [comment]
Hi, I've seen a modification in the file serverless/lib/plugins/package/lib/packageService.js (https://github.com/serverless/serverless/blob/21b6037d05020a6e4a6ec54cc77dcf5899f4f8d0/lib/plugins/package/lib/packageService.js)

In the function packageFunction we should have this piece of code:

if (funcPackageConfig.artifact) {
      functionObject.artifact = funcPackageConfig.artifact;
      return BbPromise.resolve(funcPackageConfig.artifact);
}

It used to be in the version 1.10, but it was deleted, can it be added again?

**Comment by pmuens** [comment]
@javierros thanks for looking that up 👍 

/cc @eahefnawy 🔝

**Comment by chammond75** [comment]
Fwiw I also ran into this problem and saw that AWS documentation had some guidelines for a groovy function to add to your build.gradle:

task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtime
    }
}

That seemed to package things appropriately for me. Hope this is helpful for others.

**Comment by shreyaskn** [comment]
Any update on this issue ? 
It seems the issue still persists.

**Comment by pmuens** [comment]
Closing this issue since it's quite old and we've fixed this in subsequent releases. Please update Serverless to use the most recent version.

Feel free to re-open if this is still an issue.
