### ISSUE TITLE
Response Templates don't cater for error messages with newlines

### ISSUE THREAD

**Issue by JoeStanton** [serverless/serverless#2950]
An error message such as the following:

```json
{
  "errorMessage": "[500] Value of \"{\n  contactUsURL,\n  featuredBlogPosts\n}\" violates contract.\n\nExpected:\nHomePageProps\n\nGot:\n{\n  contactUsURL: void;\n  featuredBlogPosts: {\n      slug: string;\n      category: string;\n      title: string;\n      author: {\n        role: string;\n        name: string;\n      };\n    }[];\n}",
}
````

Will not trigger the [500 error regex](https://github.com/serverless/serverless/blob/570d23d9669ee4dc29bf544a86eb9d45e30bee62/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js#L26), as `.` does not match `\n` characters. Instead, the regex could be expanded to `(\n|.)*(\[500\])(\n|.)*`, for example.

Do you think this should be fixed in Serverless or we should strip any possible `\n`'s from exceptions?

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: Mac OS X

**Comment by pmuens** [comment]
Hey @JoeStanton thanks for bringing this up!

I just PRed a change based on your proposal: https://github.com/serverless/serverless/pull/2991

Could you look into it and see if it fixes your problem! Thanks
