### ISSUE TITLE
Option to not update functions when deploying

### ISSUE THREAD

**Issue by hauboldj** [serverless/serverless#2951]
# This is a Feature Proposal

## Description

Add option --cftOnly / -c  Deploy cloudformation template without updating lambda functions to the deploy command.

Sometimes I'm iterating on the just the cloudformation resources without updating function code. Perhaps I'm making Dynamodb tables or updating roles or whatever. Having to deploy the functions everytime and wait for new functions and versions adds extra time.

Similar or dependent issues:
* #2710

**Comment by mthenw** [comment]
Another solution (IMHO preferable) would be built-in support for detecting changes in functions. We shouldn't zip/upload functions code if there was no changes there.

**Comment by nicka** [comment]
@mthenw That would be an awesome feature!

**Comment by goncaloneves** [comment]
Having both will be the best scenario because I want to be able to deploy roles/resources without any functions and vice-versa.

What I am doing now is having resources files outside SLS.

**Comment by pmuens** [comment]
Closing this as we're discussing this in https://github.com/serverless/serverless/issues/2710
