### ISSUE TITLE
Can only use Python functions in top level packages

### ISSUE THREAD

**Issue by dschep** [serverless/serverless#2956]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? Specifying a handler like `package.module.function` doesn't work. Both `package.function` and `module.function` work. 
* What did you expect should have happened? I expect it to work.
* What was the config you used? https://github.com/dschep/serverless-python-submodule-error/blob/master/serverless.yml
* What stacktrace or error message from your provider did you see?
```
[:serverless-python-submodule-error] master ± http https://xjjzrrrepj.execute-api.us-east-1.amazonaws.com/dev/users/create_package_module
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Thu, 15 Dec 2016 13:44:39 GMT
Via: 1.1 8bcdfe5c699ee9a81d92de5e160d9563.cloudfront.net (CloudFront)
X-Amz-Cf-Id: mT2PfZe_gFUL5nWmge_TjSuJkLm5ZiwdO_rT-3Z6rH1oKxUChmwE2Q==
X-Cache: Error from cloudfront
x-amzn-RequestId: 9fc05e72-c2cc-11e6-be09-d75262277c8c

{
    "message": "Internal server error"
}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: Ubuntu 16.10

**Comment by mthenw** [comment]
AFAIK it's AWS Lambda limitation. There is nothing really that we can do with that.

**Comment by dschep** [comment]
Thanks for the quick response @mthenw, I couldn't find anything about it in AWS's docs so figured I'd ask.

**Comment by big-kahuna-burger** [comment]
Try ```package/module.hello``` in serverless yaml. Should work.

**Comment by dschep** [comment]
omg. Thanks @big-kahuna-burger!

**Comment by stiteler** [comment]
thank you @big-kahuna-burger.  Aaaaannnd now I'm hungry
