### ISSUE TITLE
Google Cloud Functions support

### ISSUE THREAD

**Issue by stephenhandley** [serverless/serverless#2960]
There is mention on the homepage of supporting Google Cloud Functions, but I can't see anything in the docs and it looks like there are mainly placeholders in the code for Google / Azure and other non-AWS providers. Can you please share some information about roadmap / issues around supporting GCF?

**Comment by ac360** [comment]
Hi Stephen, This is in progress.  Check it out here:  https://github.com/serverless/serverless-google-cloudfunctions

**Comment by stephenhandley** [comment]
@ac360 Awesome thx!
