### ISSUE TITLE
Catching exceptions as per documentation doesnt seem to work

### ISSUE THREAD

**Issue by bassbump** [serverless/serverless#2968]
You describe it here as 
https://serverless.com/framework/docs/providers/aws/events/apigateway#using-status-codes

    callback(new Error('[404] Not found'))

But this keeps replying 200 either way

    Serverless: Failure: [404] Not found
    Serverless: Replying 200

I can't get it to work, is this feature actually working as described?

**Comment by pmuens** [comment]
Hey @bassbump!
Thanks for raising this issue.

What integration type are you using (`LAMBDA` or `LAMBDA-PROXY`)?

Could you maybe share some more handler code so that we can see how you exactly raise the error?

**Comment by bassbump** [comment]
LAMBDA-PROXY, basically something like this

    module.exports.hello = function(event, context, callback) {
       callback(new Error('[404] Not found'))
    };

**Comment by bassbump** [comment]
I mean it's not really a big deal, I can just set statusCode manually in the response. Maybe this feature for simplicity sake should just be removed and docs adjusted?

**Comment by pmuens** [comment]
Hmm. strange that it's not working.
We'll try to reproduce this bug.

Just out of curiosity: Could you switch to the `LAMBDA` integration type and test if that works?

**Comment by pmuens** [comment]
The status code feature is only available when using the `LAMBDA` integration type.

When using the `LAMBDA-PROXY` integration you need to set the status code manually in the response (like you've already done).

PRs for a doc update a highly welcomed 👍 😸

**Comment by eahefnawy** [comment]
imo the docs are fine. The status codes with square brackets feature is covered in the "Lambda Integration" section only, which should imply that it's only available with that integration only. @bassbump any reason why you thought otherwise?

If it'd be helpful for you and other users, maybe a small note about that in the "Lambda Integration" section would be helpful.

**Comment by bassbump** [comment]
You are right, for some reason I looked over that. This can be closed I guess.

**Comment by pmuens** [comment]
Ok. So a more obvious separation of the sections might be helpful.

Thanks for the feedback @bassbump!

**Comment by gemabarni** [comment]
Just ran into the exact same problem that @bassbump did. Also haven't realized while reading the docs that this is already the `LAMBDA` integration section. +1 for the more obvious separation.
