### ISSUE TITLE
EC2 Error Code: InvalidGroup.NotFound. The security group does not exist.

### ISSUE THREAD

**Issue by jokeyrhyme** [serverless/serverless#2973]
# This is a Bug Report

## Description

* What went wrong?

`serverless deploy` failed with an error, for a project using a pre-existing VPC

* What did you expect should have happened?

`serverless deploy` should have completed without error

* What was the config you used?

My serverless.yml defines `provider.vpc.securityGroupIds` to a single security group, and `provider.vpc.subnetIds` to multiple security groups

* What stacktrace or error message from your provider did you see?

>Serverless: Packaging service...
>Serverless: Uploading CloudFormation file to S3...
>Serverless: Uploading service .zip file to S3 (23.9 MB)...
>Serverless: Updating Stack...
>Serverless: Checking Stack update progress...
>...............................................................Serverless: Deployment failed!
> 
>  Serverless Error ---------------------------------------
> 
>     An error occurred while provisioning your stack: RedactedLambdaFunction
>     - Error occurred while DescribeSecurityGroups. EC2 Error
>     Code: InvalidGroup.NotFound. EC2 Error Message: The
>     security group 'sg-redacted' does not exist.
> 
>  Get Support --------------------------------------------
>     Docs:          docs.serverless.com
>     Bugs:          github.com/serverless/serverless/issues
> 
>  Your Environment Information -----------------------------
>     OS:                 darwin
>     Node Version:       6.9.2
>     Serverless Version: 1.4.0

Similar or dependent issues:
* n/a

## Additional Data

`aws ec2 describe-security-groups --group-ids sg-redacted` (executed from the same terminal session with the same environment variables as `serverless deploy`) confirms that the security group exists

`aws ec2 describe-subnets --subnet-ids subnet-redacted subnet-redacted` confirms that the subnets exist

Comparing the output from these commands confirms that they all belong to the same VPC

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: macOS Sierra 10.12.3 Beta (16D12b)
* ***Stack Trace***: see above
* ***Provider Error messages***: see above

**Comment by jokeyrhyme** [comment]
I feel this was likely caused by confusion on my part regarding the AWS_DEFAULT_PROFILE variable used by `aws`, and the AWS_PROFILE variable used by `serverless`.

I've run into other issues since getting the profiles correct, but they are likely unrelated to this.

I'll re-open if I have anything relevant / on-topic to add.

**Comment by mikefrancis** [comment]
Can we re-open this? I am having the same problem.

If I use the `aws-cli` I can see the security group fine; when running `serverless deploy` I get:

```bash
..........Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: RedactedFunction
     - Error occurred while DescribeSecurityGroups. EC2 Error
     Code: InvalidGroup.NotFound. EC2 Error Message: The
     security group 'sg-redacted' does not exist.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.6.0
     Serverless Version: 1.5.1
```

**Comment by jokeyrhyme** [comment]
Maybe it's worth making `serverless` honor the same profile environment variable as `aws` ? Deprecate the different variable name?

**Comment by pmuens** [comment]
Thanks for getting back @jokeyrhyme will add the `enhancement` label.

**Comment by mikefrancis** [comment]
Ok - not sure if this related to what you said @jokeyrhyme but I've got it working now.

Serverless doesn't seem to use my default region (where the VPC is) as listed in `~/.aws/config` so was trying to deploy to the Serverless default region `us-east-1`.

Would be awesome if Serverless would honour this file or maybe make it mandatory to provide a `region` in your config? Just some ideas.

**Comment by Wardevour** [comment]
I had the same error and was able to fix this by setting region in serverless.yml. I assume it had to be the same region as the RDS instance I wanted my functions to have access to.

**Comment by diegotry** [comment]
I think including which region is trying to find the security group would help to debug the issue.

**Comment by Wardevour** [comment]
I believe the default was us-east-1. I believe the resources, I was attempting to give my functions access to, we're in an instance in us-east-2. Could that have been my problem?

**Comment by pmuens** [comment]
Closing this since the issue is quite stale and we published newer versions in the past which should address this issue.

Feel free to re-open if this is still a problem.

**Comment by yen-shi** [comment]
- What went wrong?
`serverless deploy --aws-profile assumed_role` failed with an error, for a project using a pre-existing VPC.

- What did you expect should have happened?
`serverless deploy --aws-profile assumed_role` should have completed without error.

- What was the config you used?
My serverless.yml defines provider.vpc.securityGroupIds to a single security group, and provider.vpc.subnetIds to three security groups.

- What stacktrace or error message from your provider did you see?

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service MossService.zip file to S3 (72.05 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................
Serverless: Operation failed!
Serverless: View the full error output: 
 
  Serverless Error ---------------------------------------
 
  An error occurred: SchedulerLambdaFunction - Error occurred while DescribeSecurityGroups. EC2 Error Code: InvalidGroup.NotFound. EC2 Error Message: The security group 'sg-3cfe0674' does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 6741f2d1-5ca3-4eb0-8148-4db53275a43b).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.10.0
     Framework Version:         1.61.0
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0


# Additional Data
I have also tried these two commands to confirm both security group and subnets exist.
`aws ec2 describe-security-groups --group-ids <sg-id> --profile assumed_role`
`aws ec2 describe-subnets --profile assumed_role --subnet-ids subnet-redacted subnet-redacted`

Serverless Framework Version you're using:
```
Framework Core: 1.61.0
Plugin: 3.2.7
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```
Operating System: macOS Mojave 10.14.5
Stack Trace: see above
Provider Error messages: see above

**Comment by dnlsyfq** [comment]
similar issue here. 

when i check
```
aws ec2 describe-security-groups --group-ids
```
![lambda2](https://user-images.githubusercontent.com/23475708/108405774-79be3b80-725c-11eb-8398-8d7aa900b6ba.PNG)


the custom security group exist but when i tried to deploy it said 

![lambda1](https://user-images.githubusercontent.com/23475708/108405796-7f1b8600-725c-11eb-989b-1e714e9404e2.PNG)

but then when I included the default security group in the list . the error gone ! strange and I able to deploy the code

![lambda3](https://user-images.githubusercontent.com/23475708/108405809-8478d080-725c-11eb-9b3f-a1a5cf85fa44.PNG)

**Comment by skjortan23** [comment]
I am having the same issue. 

my security groups exists and its still failing.

**Comment by dnlsyfq** [comment]
@skjortan23 u need to include the default security group as well . both default and custom SG need to included in my case .

**Comment by pgrzesik** [comment]
Hello @skjortan23 :wave: What Serverless Framework version are you using?

**Comment by skjortan23** [comment]
% serverless --version
Framework Core: 1.67.0
Plugin: 3.6.1
SDK: 2.3.0
Components: 2.22.3

**Comment by skjortan23** [comment]
> @skjortan23 u need to include the default security group as well . both default and custom SG need to included in my case .
Hm no luck tried with adding the default group as well. not finding that one either...
and the regions seems right since the error log is in the right region.
`Serverless: Operation failed!
Serverless: View the full error output: https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#`

**Comment by pgrzesik** [comment]
Thank you - it's a bit outdated version - do you have the ability to upgrade to the latest version? It would help us diagnose if it wasn't fixed in the meantime. You can also provide a minimal reporoducible example - I'll be happy to test it out on my side and see if I'm running into the same issue.

**Comment by CharlieBrownCharacter** [comment]
I'm facing the same issue. I have added a default security group (to be able to connect to my RDS) and 3 subnets:

```yml
...
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: xxxxx
  region: us-west-2
  # Imports all the enviromental variables in `env.prod.yml` file
  environment: ${file(./env.prod.yml)}
  vpc:
    securityGroupIds:
      - sg-48118334
    subnetIds:
      - subnet-c33d44b9
```

Now when I run `npx serverless deploy --config serverless.prod.yml --verbose` I get:

```
Serverless: Operation failed!
Serverless: View the full error output: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A359163713835%3Astack%2Faws-node-scheduled-cron-project-dev%2F86728bb0-7157-11ec-af3e-06f982a1d46b
 
 Serverless Error ----------------------------------------
 
  An error occurred: NotifyTodoScheduleOccurrencesLambdaFunction - Resource handler returned message: "Error occurred while DescribeSecurityGroups. EC2 Error Code: InvalidGroup.NotFound. EC2 Error Message: The security group 'sg-48118334' does not exist (Service: Lambda, Status Code: 400, Request ID: b508831a-14cd-4bc5-928f-5cdf8aa50cc4, Extended Request ID: null)" (RequestToken: 3bd2a9b8-a147-6959-5ec8-ff2be3210866, HandlerErrorCode: InvalidRequest).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.1
     Framework Version:         2.70.0 (local)
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1

```

When I run `aws ec2 describe-security-groups --group-ids sg-48118334` I get

```json
{
    "SecurityGroups": [
        {
            "Description": "default VPC security group",
            "GroupName": "default",
            "IpPermissions": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0",
                            "Description": "Only allow traffic from the EC2 instance"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "OwnerId": "359163713835",
            "GroupId": "sg-48118334",
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "VpcId": "vpc-f67b509e"
        }
    ]
}

```

Any thoughts on something I might be doing wrong @pgrzesik ?

**Comment by mikemcg52** [comment]
Was there ever a resolution on this?  I'm running into the same issue.  Confirm that the SG exists in the console, specifying the correct region.  Running framework 2.72 which I believe is current (or very close).

**Comment by pgrzesik** [comment]
I've tried to reproduce but I'm not able to - is there anything specific about your configuration? Could you provide a minimal reproducible example ?

**Comment by mikemcg52** [comment]
Thank you.  You solved the problem!  In going through my config file to get a minimal example I realized I was using the wrong profile setting.  That would do it.

Thanks again and sorry for the noob error.  :-(

**Comment by pgrzesik** [comment]
No worries, I'm happy you were able to resolve the problem @mikemcg52 🙌
