### ISSUE TITLE
Adding serverless-s3-crud to the README

### ISSUE THREAD

**Issue by tscanlin** [serverless/serverless#2987]
# This is a Feature Proposal

Adding serverless-s3-crud to the README

## Description

I made a service similar to serverless-crud but using s3 rather thank dynamoDB. Would you consider adding it to the README? https://github.com/tscanlin/serverless-s3-crud

Why is this useful?

For certain types of data a file system is a much better way to go than a database. Also dyanamodb currently has a 400K object limit and s3 can store much larger sizes. Happy to provide more reasons here if needed.

**Comment by pmuens** [comment]
Hey @tscanlin!
Great service! Good job!

You could simply create a PR and add it to this section: https://github.com/serverless/serverless/blob/master/README.md#services-v10

We'll merge it right away!
