### ISSUE TITLE
HTTP request / response parameters for APIG autogenerated SDK

### ISSUE THREAD

**Issue by nachoab** [serverless/serverless#2990]
# This is a Feature Proposal

## Description

Here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js#L95

http.request and http.response are deleted when integration = 'AWS_PROXY', but this parameters still serves a purpose: it allows me to download the automatically generated API SDK from APIG, which filters query parameters and only allows the one configured in your http request, so if I don't specify what parameters will be passed, I just can't use it.

This is a fragment of APIG code:

```
{
queryParams: apiGateway.core.utils.parseParametersToObject(params, []),
}
```

`queryParams` will be an empty object unless the second parameter is an array with all parameter names, which is automatically generated from http.request.parameters.method.request.querystring[parameterName]

What is the reason to delete them?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I want to use the automatic js SDK from APIG with querystring parameters in my functions.
http://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#mapping-request-parameters

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dougmoscrop** [comment]
Ahh, I added the code to delete them. The reason is that there's a lot more configuration inside `request` and `response` than just parameters and that was causing problems.

What we could do instead is pull off the parameters for request/response, warn if there's *other* keys set, and pass those up.

**Comment by pmuens** [comment]
Closing since this is intentional and a solution will be discussed in #2882
