### ISSUE TITLE
Native support for nested stacks

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2995]
# This is a Feature Proposal

## Description

Serverless and `serverless.yml` in particular should support Nested stacks so that developers can compose their service out of multiple CF stacks and therefore e.g. circumvent the CloudFormation limits. This may also speed up deployment in general.

This is based on the insightful discussions in https://github.com/serverless/serverless/issues/2387

Please comment and talk about use cases so that we can define the best solution.

**Comment by davestone** [comment]
39 lambda functions, few DynamoDB, S3, etc and I've hit this issue on the day I'm meant to be launching. What can I elaborate on to add to a use case to help?

**Comment by dougmoscrop** [comment]
Is there a reason you're trying to deploy so much at once? The atomicity of deployment is, as far as I've ever experienced, somewhat of an illusion and often times I have stacks get in to bad states. The smaller the surface area for that the better IMHO.

**Comment by rowanu** [comment]
Nested CFN stacks have *never* resulted in happy endings in my experience.

It's usually used as a work-around for things that should really be modularised, especially now that cross-stack references are a thing.

I have also never see nested stacks improve deployment times - at the end of the day you're using it in this scenario to deploy/update more resources, which will only take more time.

**+1 Cross-Stack References FTW**

**Comment by tgjorgoski** [comment]
Not sure if this will be helpful in your decision, but currently we are successfully using CFN nested stacks within Serverless to create some Cognito related resources (User and Federated Identity Pools + some DynamoDB tables). We developed that CFN script separately (in JSON), and seemed cleaner to keep it separate (vs. the alternative of transform to YML and then copying everything into the serverless file). We weren't worried about the limits at the time, but that sounds as another reason for doing it this way.

The inclusion in resources part of serverless, looks something like this:
```
    cognitoFormStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: 'https://s3-${self:custom.myRegion}.amazonaws.com/###path###/cognito-resources.cform'
```

The only two issues we encountered were:
1. #2898  (which should be fine after the fix) , and...
2. we wanted to keep the nested CFN script (`cognito-resources.cform`) as part of the project, and upload it to S3 along other resources in the process of deployment. 

To be able to do this second thing I wrote a plugin connected to the before:deploy:deploy hook.
What the plugin does is 
a) gets everything from "nested-stacks" subfolder and uploads it along the other resources to the deployment folder. (we keep CFN script there) and 
b) searches within `this.serverless.service.resources` , and replaces any `###path###` string within any `TemplateURL` path with the actual path where the deployment happened.

As you can see it is not very clean solution and we can never be sure if the following serverless update breaks our plugin, so it would be nice if serverless supported something out of the box to address this use case.

**Comment by pmuens** [comment]
Just posting the proposal from @MatheusVellone here which was brought up in https://github.com/serverless/serverless/issues/3411#issuecomment-295260575 (thanks for that 👍 )

```
I'm not very experienced with CF stacks, so sorry if what I'm about to say isn't an option.

What if we could do something like this in our serverless.yml ?

functions:
    fn1:
        ...
        stackGroup: A
    fn2:
        ...
        stackGroup: A
    fn3:
        ...
        stackGroup: B
This would put fn1 and fn2 in CF stack A, and fn3 in CF stack B.
This allow users to have full control over stack grouping plus removing the need to develop an algorithm to do the splitting automatically and also solves the problem for big APIs.

And also, if at least one function have stackGroup attribute, all of them should have it too, so the grouping can be done
```

**Comment by jagdish-176** [comment]
I have created nested stack for our project at https://github.com/jagdish-176/serverless-nested-stack
based on my resources used, this helped me to split stack in 3 parts , resolved my issue of 200 CloudFormation resource limit.

**Comment by pmuens** [comment]
Wow. That's super nice! Thanks for creating @jagdish-176 👍 💯

Could you PR this to our `plugins` repository as well (for a better discoverability)? Thanks in advance!

https://github.com/serverless/plugin

**Comment by Rukenshia** [comment]
Is there any update on an official solution? The plugin is not working for me (heap errors when uploading the artifacts). We have a pretty big API Gateway by now and are basically rendered unable to deploy anything because of the resource limitations.

**Comment by dougmoscrop** [comment]
Have you tried my plugin?

**Comment by Rukenshia** [comment]
@dougmoscrop you mean https://github.com/dougmoscrop/serverless-plugin-split-stacks ? I'll give it a try, thanks for the heads up!

**Comment by dougmoscrop** [comment]
yep!

**Comment by dbligh** [comment]
@jagdish-176 thanks for sharing your plugin, I was able to get this working pretty nicely to reduce my resource count.

**Comment by abdennour** [comment]
Guys, you may need to check out : https://aws.amazon.com/blogs/devops/continuous-delivery-of-nested-aws-cloudformation-stacks-using-aws-codepipeline/

Good luck!

**Comment by oscarr-reyes** [comment]
Any updates on this issue?

I am soon to hit the limit and i would like to find a solution before i get to it. I haven't tried any of the mentioned plugins but i would like to see if there is anything being worked on related to this before i jump into using one of those plugins.

In my opinion i believe it's best to leave the stack naming and selection to the developer since there can be many strategies for different scenarios, say for instance in my case:

i am not making use of `API Gateway` but i have created an implementation to trigger the functions from ALB rules, for all of this i had to create role, lambda permission, target group for each function, and this is without mentioning the other resources i am using (like db instance, cognito userpool, cognito app client, s3 buckets..)

in this case i would split the stack into 3 stacks

- main (iam)
- api (lambda, target group, permission)
- storage (s3, database, s3 permission)

i believe we would have to find a way to group those resources to their desired stack without altering the `Resources` object in the final deployment file

**Comment by hughneale** [comment]
@oscarr-reyes I gave up with this due to AWS's limit for cloud formation. We ended up just breaking our application up into logical components (which has actually made deployment easier) as you've described with your 3 stacks. Not helpful I know. Just wanted to weigh in a little.

**Comment by dougmoscrop** [comment]
Just another shameless plug if you are going to use separated stacks (as opposed to nested stacks) I made serverless-plugin-bootstrap which manages a dependant stack separate from the main one, we put things like queues and tables and other persistent stuff in it, it also provide a terraform-like diff of the changes and uses changesets to apply the changes

**Comment by medikoo** [comment]
Closing for reasons mentioned here: https://github.com/serverless/serverless/issues/2387#issuecomment-662567921
