### ISSUE TITLE
Deploy errors on first deploy to a stage when adding `deploymentBucket` to existing service

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#3004]
# This is a Bug Report

## Description
After adding `deploymentBucket` to an already-deployed service that previously used the default setting, the first deploy takes much longer than it should, and the following error is displayed multiple times in the console output:

```
CloudFormation - DELETE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - DELETE_FAILED - AWS::S3::Bucket - ServerlessDeploymentBucket
```

Eventually the deploy seems to complete successfully regardless of these errors.

This issue happens on the first deploy to any stage after adding `deploymentBucket`, but subsequent deploys to a stage work as expected without any errors.

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: OSX 10.11.6

**Comment by volodymyrrudyi** [comment]
I confirm the issue is still here (1.24.1)

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
