### ISSUE TITLE
[BUG] Unable to run `serverless deploy` command on macOS Sierra

### ISSUE THREAD

**Issue by WendySanarwanto** [serverless/serverless#3025]
When I run `serverless deploy -s <stage> -r <region` or `serverless deploy`  commands on my macbook which runs macOS Sierra (for deploying a simple hello world created by `serverless create`), the command stuck at `Serverless: Checking Stack create progress ...`. 
![image](https://cloud.githubusercontent.com/assets/18456618/21477813/7ecfb982-cb80-11e6-9390-28a4a33422b4.png)

When I check it in AWS web console, I noticed that the cloud formation setting was in there and its process status is CREATE_COMPLETED. However, no lambda function & API Gateway were created.

Environments:
- Mac OS Sierra 10.12
- Serverless 1.3 & 1.4
- NodejS version 4.3.2 & 6.9.1
- AWS-CLI version 1.11.34

**Comment by horike37** [comment]
@WendySanarwanto
Is the CloudFormation stack running in AWS web console?
When it is displayed CREATE_COMPLETED, the CloudFormation stack should be running

**Comment by WendySanarwanto** [comment]
Yes it was, @horike37 Until it was completed. However, it does not create Lambda function and its API Gateway Endpoint.

**Comment by horike37** [comment]
The CF Stack is running as the capture, but it does not create Lambda function and its API Gateway Endpoint. Correct?
<img width="942" alt="2016-12-26 19 18 53" src="https://cloud.githubusercontent.com/assets/1301012/21480469/9cb7aa66-cba0-11e6-9228-685e208d549b.png">

**Comment by WendySanarwanto** [comment]
Hello @horike37 

> The CF Stack is running as the capture, but it does not create Lambda function and its API Gateway Endpoint. Sounds good?

Yes, that's the issue that happened in my macbook air that runs latest version of macOS Sierra. 

> I want to know if the CF stack is up on your local as well as on the AWS management console as follow.

This is the detail view of the CF which did not create the expected Lambda function and API Gateway endpoint. 

![image](https://cloud.githubusercontent.com/assets/18456618/21487255/e8231c4c-cbff-11e6-8bf1-bbbbcc1564d8.png)

I created the basic serverless project using `serverless create` command. this time, I did it in my Ubuntu 16.04 machine. The command finished successfully: i could see the lambda  & the endpoint. Here is the screenshot of its CF:

![image](https://cloud.githubusercontent.com/assets/18456618/21487268/2d856484-cc00-11e6-97ab-5e5d326112c5.png)

![image](https://cloud.githubusercontent.com/assets/18456618/21487277/753238c0-cc00-11e6-89c9-200abb495ee8.png)

**Comment by horike37** [comment]
Thank you for the detail @WendySanarwanto! I just understood.
Please give me as follow
- Contents of your serverless.yml
- All of the stack trace of CF in your macOS Sierra.

I use macOS Sierra too, but work fine. I will test by using your serverless.yml.

**Comment by WendySanarwanto** [comment]
Hello @horike37 

> Contents of your serverless.yml

service: putItemsDemo

![image](https://cloud.githubusercontent.com/assets/18456618/21489220/d29c8dcc-cc22-11e6-83d3-db0c838f2376.png)

>All of the stack trace of CF in your macOS Sierra.

I assume the `stack trace` here are displayed lines of message when running `serverless deploy` command and get stuck. 

![image](https://cloud.githubusercontent.com/assets/18456618/21489282/8feb5674-cc23-11e6-94c1-1eb3df6c2e4c.png)

Logs on AWS CloudFormation's page:

![image](https://cloud.githubusercontent.com/assets/18456618/21489476/0de451e6-cc26-11e6-854f-70fc59344617.png)

Also, I downgraded the `aws-cli`'s version to `1.10.1` , similar to `aws-cli` in my ubuntu desktop. 
![image](https://cloud.githubusercontent.com/assets/18456618/21489289/afe4d90a-cc23-11e6-8186-501a6a5d425e.png)

My macOS sierra's info

![image](https://cloud.githubusercontent.com/assets/18456618/21489492/3c5de4c4-cc26-11e6-9337-a52241ec0adf.png)

> I use macOS Sierra too, but work fine. I will test by using your serverless.yml.

May i know the version of `aws-cli`, `node.js`, `serverless` that you had in your macOS sierra machine ?

**Comment by pmuens** [comment]
Hey @WendySanarwanto thanks for reporting and @horike37 thanks for helping out!

It seems like Serverless aborts after the stack creation process. So no "update stack" kicks in.

What happens if you deploy the service from scratch with `serverless deploy` and then deploy it again with `serverless deploy`? The second deploy should tell AWS to update the stack (and therefore create the functions).

**Comment by WendySanarwanto** [comment]
Hello @pmuens,

> What happens if you deploy the service from scratch with serverless deploy and then deploy it again with serverless deploy? The second deploy should tell AWS to update the stack (and therefore create the functions)

> Another question I have is what happens after the "Checking Stack update progress..." because that's the step where Serverless tells AWS to update the stack. Does it hang there or does it succeed on the command line?

These are steps that I did to answer these questions:

1. I created a new serverless project

![image](https://cloud.githubusercontent.com/assets/18456618/21583612/a955fed0-d0c3-11e6-88c2-61e852eda853.png)

2. I went into the created project's folder and run `npm init` command inside.

![image](https://cloud.githubusercontent.com/assets/18456618/21583632/a30bfac4-d0c4-11e6-8db1-2653a944c457.png)

3. I edited the `serverless.yaml` file as follow:

![image](https://cloud.githubusercontent.com/assets/18456618/21583647/1d43a4fe-d0c5-11e6-9c02-dc7ce233e460.png)

4. I ran `serverless deploy` command and wait the process for 15 minutes but it seemed hang in there. It did not finish until I pressed `CTL+C`.  

![image](https://cloud.githubusercontent.com/assets/18456618/21583658/a847dd4a-d0c5-11e6-9c2a-d25fa74ee5a0.png)

![image](https://cloud.githubusercontent.com/assets/18456618/21583689/3cd922ce-d0c7-11e6-8adc-3d176f9790ea.png)

5. After I pressed `CTL+C` in prior step, I re-run `serverless deploy` command again. It displayed more messages but hung at `Checking Stack update progress ...` message

![image](https://cloud.githubusercontent.com/assets/18456618/21583738/bdadd2a4-d0c8-11e6-83c7-9c5c15f2a4cd.png)

However, when checking the cloudFormation's logs, I noticed more log messages which indicate that deployment is succeed.

![image](https://cloud.githubusercontent.com/assets/18456618/21583748/12359d34-d0c9-11e6-9c50-f09c65c039cf.png)

![image](https://cloud.githubusercontent.com/assets/18456618/21583750/18f0da44-d0c9-11e6-941f-d2c66cdb4551.png)

Then, I went to AWS Lambda's and API Gateway's console pages and I confirmed that the lambda has been deployed.

![image](https://cloud.githubusercontent.com/assets/18456618/21583756/64311b04-d0c9-11e6-9409-c46a86e9cd15.png)

![image](https://cloud.githubusercontent.com/assets/18456618/21583763/af57b548-d0c9-11e6-8084-6a2178205064.png)

However, the command line is still hung ( did not finish properly)

**Comment by pmuens** [comment]
@WendySanarwanto thanks for the detailed step-by-step guide on how to reproduce this.

Seems like the stack monitoring method is broken... We'll look into it!

**Comment by pmuens** [comment]
Can confirm it. Just ran into the same issue today. Tried to reproduce it, but was out of luck...

**Comment by ZouMingxin** [comment]
We encountered the same problem when we use the 'serverless deploy' on Bamboo (Ubuntu image) with the latest Serverless version. It would stop at the exact step @WendySanarwanto.

**Comment by vgi-minami** [comment]
Did you check the OS time setting?
If the time setting is inaccurate, I encountered the same problem.

**Comment by ebahsini** [comment]
+1 @vgi-minami -- also, sls deploy --verbose to check where it hangs

**Comment by pmuens** [comment]
Yep. We've confirmed that this is a clock drifting issue. A WIP PR is already available at #3200.
