### ISSUE TITLE
Function not found error

### ISSUE THREAD

**Issue by briguy202** [serverless/serverless#3028]
# This is a Bug Report

## Description
Since upgrading from Serverless 1.1.0, we have been encountering an error stating "Function not found" when creating a new stack.  We have tried both Serverless 1.3.0 and 1.4.0 and are encountering the issue with both.  We also tried Serverless 1.2.1 and do NOT encounter the issue with that version, so it appears to be something introduced with 1.3.0.

The interesting thing is that we see in our Cloudformation events log that the Lambda function that the version is reporting doesn't exist is created successfully earlier on in the log:

![image](https://cloud.githubusercontent.com/assets/3893897/21532607/c7a7575a-cd1f-11e6-8a3d-64ac980bb04f.png)

Based on the error line stating that it is creating an AWS::Lambda::Version resource, it seems like this must be related to the versioning support added in 1.3.0.

For bug reports:
* What went wrong?
We are receiving a "Function not found" error
* What did you expect should have happened?
It should succeed.
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/1350

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: OSX
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by briguy202** [comment]
Very strange ... without changing code at all, we simply redeployed the same package out to AWS and it worked this time.  The only difference was that we noticed some functions weren't being deleted properly when rolling back the stack, so we manually removed all Lambda functions before redeploying.  It appears it may have been something going on within AWS.

**Comment by pmuens** [comment]
@briguy202 Thanks for reporting and thanks for getting back with the solution. 👍 

What's really interesting is that it worked with Serverless v1.2.1. Our goal is to follow strict semver so we shouldn't have introduced some breaking changes while getting from 1.0 to 1.4.

We'll look a little bit more into this as it really seems to be related to the versioning of Lambdas although the introduction shouldn't break existing functions (might be really something on AWS end...). Glad to hear that everything works now.

**Comment by ldadams** [comment]
@briguy202 @pmuens - I am seeing the same issue today but I have not yet been able to work around it.  Also at least one other person mentioned seeing this today.

I wiped everything out and still can't deploy.  It appears the versioned function is attempting to reference the a function that does not exist or hasn't been created yet.

**Comment by pmuens** [comment]
Hey @ldadams ! Thanks for reporting that this is still an issue. 👍 

We'll look into it today and keep you posted in #3050
