### ISSUE TITLE
Add support for custom context fields in custom authorizers

### ISSUE THREAD

**Issue by endymion00** [serverless/serverless#3031]
# This is a Feature Proposal

## Description

I've recently seen that the custom authorizer template for node.js in Amazon console includes a new feature that allows to pass key-value items via the $context object.
Because custom authorizers have a very poor support for sending custom responses to the client this is a very interesting feature because the integration backend can analyze a custom field inside $context object and respond to clients in different ways (custom authorizers only support to respond 401 Unauthorized by calling callback( 'Unauthorized') or 403 Forbidden when retuning a deny policy this way callback(null, thisIsAPolicy).
In case of the policy is allow the backend method on APIGW is called.

Here is the documentation. See param $context.authorizer.<property>
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference

As I see serverless framework integration request template does not expose this object to the backend method because is perfoming this: 
`"principalId": "$context.authorizer.principalId" `
so a solution will be to create another field that includes the other keys inside $context.authorizer
Examples: 
```
"authorizerKeys": {
"myCustomKey1": "ssss"
"myCustomBoolean": true
}

"authorizerKeys": {
"statusCode": "403"
"message": "Token is expired"
}

```
For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I'm using JWT in custom authorizers and I need to return to clients a custom error message when tokens are not valid (i.e.: 'Token Expired' or 'Invalid Token'). This is not possible because when the only option is to return the aforemention 401 Unauthorized or 403 Forbidden.

With the new feature a custom authorizer can generate an allow policy, then the backend method is called and the first thing it could do is to check if $context.authorizer.<my_own_key> says that the token is expired or not valid.

This is only a specific use case but this feature could be used for performing other actions in the backend method. 

* If there is additional config how would it look

From node.js custom authorizer blueprint:

```
             // new! -- add additional key-value pairs
            // these are made available by APIGW like so: $context.authorizer.<key>
            // additional context is cached
            /*
            authResponse.context = {
                key: 'value', // $context.authorizer.key -> value
                number: 1,
                bool: true,
            };
            */
            // authResponse.context.arr = ['foo']; <- this is invalid, APIGW will not accept it
            // authResponse.context.obj = {'foo':'bar'}; <- also invalid
            return callback(null, authResponse);


```
Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Closing since this issue is quite old and we've added lots of features to custom authorizers in the past.

Feel free to re-open if this is still not possible.
