### ISSUE TITLE
Minor feature proposals & improvements for AWSInvokeLocal plugin

### ISSUE THREAD

**Issue by breath103** [serverless/serverless#3036]
# This is a Feature Proposal
This is a few feature proposal for AWSInvokeLocal plugin.

## Description

**1. Added support js file that has export as an data input**
- if you have complicated form of JSON body to send, this could be really complicated since we can't really "Generate" json now. we could just run command for generating json file and call `invoke local`, but i felt like since it could be more natural to just support `.js` file has `module.exports` also, since we have `require` which supports both .json / .js anyway

**2. You can specify the location of handlers, such as `"/dst"`**
- this might seem controversial, (and i'd love to fix this from outside of this plugin!) but there is no way to specify extra servicePath for severless. for example i'm using Typescript with serverless, which gives me seperated `src` and `dst` folders. (as you can guess, `dst` is js transpiled). in this case, deploying is not a problem since serverless supports `package.artifact`, (which could be just dst.zip, easily) but for invoke-local there is no such thing. so that it's impossible to use invoke-local unless totally change the directory structure.
i guess this could be more cleanly, solved by adding `package.handlerPath` on `serverless.yml` but since that's even bigger change, and not sure this would be really needed other than invoke-local command.

**3. Support `context.done(err, result)`**
- check [reference](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html#nodejs-prog-model-oldruntime-context-methods) (search context.done)

**4. Show JSON.parse result if `Content-Type = "application/json"`**
- this could be also vary i guess, but if you configured AWS lambda as proxy (which is default these days) and serve responses, you'll see
    ```
    {
        "statusCode": 200,
        "headers": {
            "Content-Type": "application/json"
        },
        "body": "{\"result\": true, \"message\": "Whatever"} 
    }
    ```
    , not 
    ```
    {
        "statusCode": 200,
        "headers": {
            "Content-Type": "application/json"
        },
        "body": {
            "result": true,
            "message": "whatever"
        }
    }
    ```

i guess it could be more safer by checking is the function use `lambda-proxy` or not.

**Comment by mthenw** [comment]
> 1. Added support js file that has export as an data input

we recently introduced stdin support for `invoke` so you can do something like 

```
node inputDataGenerator.js | serverless invoke local -f hello
```

**Comment by breath103** [comment]
@mthenw that make sense also. hm.. one question is, did you guys left the -p (or --data) option for backwards compatibility only?

**Comment by pmuens** [comment]
Closing this issue since @breath103 was kind enough to submit a PR to enhance local invocation 👏
