### ISSUE TITLE
JAWS project using one S3 bucket for all stages by default

### ISSUE THREAD

**Issue by domderen** [serverless/serverless#304]
Currently by default JAWS project creates new AWS S3 bucket to store configuration for each of the projects stages. It keeps the versioned Lambdas there, as well as the environment variables etc. 

It is possible to overwrite this behaviour, and keep the configurations for all stages inside a single bucket by defining the aaJawsBucket variable to be the same for all stages. It requires some manual work around creating proper directories inside that bucket, but JAWS is able work with a single bucket and store there all configuration.

I wanted to propose to make such behaviour a default one, where a single bucket is used for the whole JAWS project, instead of having separate ones for each stage. AWS S3 has a default limit of 100 buckets per account, which some people hit rather quickly when they work with JAWS and they are using S3 for non-JAWS related stuff. Additionally it makes the management of the buckets a bit easier, having a single one for a project.

**Comment by ac360** [comment]
:+1: Looking into this right now for `v1.4`

**Comment by ac360** [comment]
@domderen This will be the default behavior in `v1.4`.  Thanks :)  Also, we should chat some time.  Will you email me at austen@jawsframework.com?  I'd love to talk to you about our internal Road Map.

Cheers!
