### ISSUE TITLE
Serverless creates .npmignore instead of .gitignore

### ISSUE THREAD

**Issue by simplesteph** [serverless/serverless#3051]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Creating a template in python using `serverless create` doesn't create the appropriate `.gitignore`. 

```
$ serverless create --template aws-python --path test
$ cd test/
$ ls -a 
.               ..              .npmignore      handler.py      serverless.yml
$ cat .npmignore
# Distribution / packaging
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Serverless directories
.serverless
```

* What did you expect should have happened?
I don't believe this should have been a `.npmignore` but a `.gitignore`. 
See this PR https://github.com/serverless/serverless/pull/2375 

* What was the config you used?
See above

* What stacktrace or error message from your provider did you see?
No error just a wrong naming

## Additional Data

* ***Serverless Framework Version you're using***:
1.4.0
* ***Operating System***:
mac os x
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by vladgolubev** [comment]
Interesting. There is `.npmignore` published to npm indeed: https://unpkg.com/serverless@1.5.0/lib/plugins/create/templates/aws-nodejs/

**Comment by vladgolubev** [comment]
So this an official behaviour of npm. It will rename all `.gitignore` to `.npmignore` on publishing.

https://github.com/npm/npm/issues/3763

It can be fixed by creating an empty `.npmignore`. 

> Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.
