### ISSUE TITLE
[BUG] Deploy error: CloudFormation - CREATE_FAILED - AWS::Lambda::Version - HelloLambdaVersion

### ISSUE THREAD

**Issue by abeauvois** [serverless/serverless#3052]
Following instructions in the docs https://serverless.com/framework/docs/providers/aws/guide/services 

Image:
![screen shot 2017-01-04 at 00 49 25](https://cloud.githubusercontent.com/assets/309368/21627540/d9073cec-d218-11e6-9abf-e3890b71d065.png)

then got an error when run `serverless deploy -v` commands on my macbook which runs macOS Sierra.

Image:
![screen shot 2017-01-04 at 00 49 52](https://cloud.githubusercontent.com/assets/309368/21627563/fe80eec8-d218-11e6-954e-4402cfa842cf.png)

Curiously I don't have this error with `serverless deploy -s dev -r us-east-1`

Image:
![screen shot 2017-01-04 at 01 01 04](https://cloud.githubusercontent.com/assets/309368/21627627/677be9f0-d219-11e6-8863-753cf7e7adee.png)

Environments:

Mac OS Sierra 10.12
Serverless 1.4
NodejS version 5.6.0

**Comment by corotchi** [comment]
Exactly the same issue i experience

**Comment by pmuens** [comment]
Hey @abeauvois thanks for reporting! 👍 

Sadly others are also experiencing this issue. We'll look into it today!
I'll close this one as we're tracking progress in this issue:https://github.com/serverless/serverless/issues/3050
