### ISSUE TITLE
npm script issues - Installing from github vs. npm

### ISSUE THREAD

**Issue by paulSambolin** [serverless/serverless#3055]
# This is a Bug Report

### Updated Issue
I originally believed my problem was related to the directory structure and build commands of AWS Codebuild.  But I was also installing the package directly from your Github page like so:
`npm install -g https://github.com/serverless/serverless`

Upon switching back to:
`npm install -g serverless`

It installed!  (edit the npm package doesn't contain the scripts below) See below for some backgound thinking about the issue.  Now I am thinking that the npm scripts should work properly wether no matter the download location or OS, but am unsure if this is a problem with serverless or npm, so posting the issue here first for reference

Sls Version: 1.4
OS: AWS Codebuild Ubuntu - nodejs config 
Error Messages:
```
npm ERR! serverless@1.4.0 postinstall: `node /usr/local/lib/node_modules/serverless/scripts/postinstall.js`
npm ERR! Failed at the serverless@1.4.0 postinstall script 'node /usr/local/lib/node_modules/serverless/scripts/postinstall.js`
```

### Background of issue
We are using AWS codepipeline&codebuild CI/CD to deploy our serverless services.  A catch of using Codebuild is that every command is run from the root directory so if you need to run a command in a subdirectory you need to change directories and run the command in one line

Does not work:
```
cd subdirectory
node scripts/postinstall.js
```

Works:
```
cd subdirectory && node scripts/postinstall.js
```

My particular problem occurs from this [commit]( https://github.com/serverless/serverless/commit/daa223a2fc8f7a9afa538f576e59f8a49ca82d8f)

I believe it is because codebuild executes the npm script in the root directory of Codebuild, not the root directory of serverless.  If someone has some suggestions I would gladly attempt an implementation.

**Comment by pmuens** [comment]
Thanks for bringing this up @paulSambolin !

I can confirm this bug and will provide a fix 💯

**Comment by paulSambolin** [comment]
@pmuens That was fast :)

**Comment by pmuens** [comment]
@paulSambolin should be good to once the failed integration test is resolved.

Thanks for the very detailed description! Was extremely helpful 👍 ! Really appreciate it!

In the meantime you can check it by running:

```
npm install -g https://github.com/serverless/serverless#add-pre-and-post-install-scripts-to-package-files
```

Sorry for the long branch name 😬 😆

**Comment by paulSambolin** [comment]
@pmuens, thanks a ton! I will let you know how it goes

**Comment by paulSambolin** [comment]
Installed flawlessly, that is all I could ask for :) Thank you very much

**Comment by pmuens** [comment]
Great! Thanks again for reporting! Should be in master today 👍

**Comment by pmuens** [comment]
@paulSambolin merged into master! :-)
