### ISSUE TITLE
Install a serverless service from a private repo

### ISSUE THREAD

**Issue by skilledDeveloper** [serverless/serverless#3059]
When I try `sls install --url https://github.com/my-private-repo` I get the folloowing error:
```
  H T T P Error ------------------------------------------
     Response code 404 (Not Found)
```
Looks like Serverless cannot download the repo for obvious reasons.
Is there any plan to support this somehow?

**Comment by pmuens** [comment]
Hey @skilledDeveloper yes, Serverless currently only supports installation of public repos.

We have yet no plans to support this in the near future but contributions are highly welcomed!

**Comment by skilledDeveloper** [comment]
How about this:
Instead of downloading the repo zip file, we clone the repo (i.e. `git clone`) somewhere in `/tmp` and do the rest?

**Comment by brianneisler** [comment]
Slightly modeling off of NPM might make sense here. http://stackoverflow.com/questions/28728665/how-to-use-private-github-repo-as-npm-dependency

**Comment by pmuens** [comment]
Closing since https://github.com/serverless/serverless/issues/3059#issuecomment-271042309 should help resolving the issue.
