### ISSUE TITLE
Serverless ignores path argument which starts with a digit

### ISSUE THREAD

**Issue by vladgolubev** [serverless/serverless#3063]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

When I create a new project from template it ignores my `--path` param if it starts with a digit.

```bash
$ serverless create --template aws-nodejs --path 123
```

```bash
$ ls -a
$ .  ..  handler.js  .npmignore  serverless.yml
```

* What did you expect should have happened?

I expected that template will be created in a dir I provided, even if it starts with a digit. 

```bash
$ ls -a
$ .  ..  123
```

* What was the config you used?

All default.

* What stacktrace or error message from your provider did you see?

No error stacktrace.

Similar or dependent issues:
* haven't found

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: Ubuntu 16.10
* ***Stack Trace***: no
* ***Provider Error messages***: no

After looking into sources, I guess the reason is here:

```js
const boilerplatePath = this.options
      .path && this.options.path.length ? this.options.path : null;
```

**Comment by pmuens** [comment]
Nice catch! Thanks for reporting and providing a fix @vladgolubev 👍
