### ISSUE TITLE
Serverless metrics outputs incorrect average function duration

### ISSUE THREAD

**Issue by vladgolubev** [serverless/serverless#3066]
# This is a Bug Report

#### What went wrong?
My functions never executed longer than 800 ms, but serverless says average time is 831 ms.

#### What did you expect should have happened?
I expected to see a real metrics

#### What was the config you used?
Not applicable.

#### What stacktrace or error message from your provider did you see?
No error message.

Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.0
* ***Operating System***: Ubuntu 16.10
* ***Stack Trace***: none
* ***Provider Error messages***: none

I cloned the latest `master` branch locally to add some `console.log`s to see what's the problem.

**awsMetrics.js**
```diff
      _.forEach(metrics, (metric, index) => {
+        console.log(`--- ${index} function`);
        _.forEach(metric, (funcMetric) => {
          if (funcMetric.Label === 'Invocations') {
            invocations += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else if (funcMetric.Label === 'Throttles') {
            throttles += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else if (funcMetric.Label === 'Errors') {
            errors += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else {
+            funcMetric.Datapoints.forEach(point => {
+              console.log(moment(point.Timestamp).format('YYYY-MM-DD'), '-', point.Average.toFixed(2));
+            });
            duration += reduceDatapoints(funcMetric.Datapoints, 'Average');
          }
        });
      });
```

which produced the output:

```bash
$ ~/serverless/bin/serverless metrics --startTime 10d --stage prod
--- 0 function
2017-01-01 - 247.40
2016-12-29 - 129.54
--- 1 function
2016-12-28 - 575.13
2017-01-01 - 255.61
2016-12-29 - 186.05
2017-01-02 - 284.15
2016-12-31 - 186.15
--- 2 function
2017-01-01 - 102.32
2016-12-29 - 102.07
2017-01-02 - 222.01
2016-12-31 - 97.99
--- 3 function
2016-12-29 - 565.32
2017-01-02 - 371.52
Service wide metrics
December 27, 2016 9:26 PM - January 6, 2017 9:26 PM

Invocations: 725 
Throttles: 0 
Errors: 0 
Duration (avg.): 831.3125ms

```

So it's visible that something is wrong in calculating the average. After looking forward I found that we sum together milliseconds from every day and divide them by `metrics.length` i.e. by number of functions. But we don't take into account CloudWatch can return data by several Periods in a given timespan.
Hence I looked into this already, I'll prepare a fix.

**Comment by pmuens** [comment]
Nice catch @vladgolubev thanks for working on the fix! 👍
