### ISSUE TITLE
Postinstalling private NPM module gives ENOENT error

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#307]
I'm trying to install a private NPM AWSM module (@username/packagename) and getting an error:

    $ npm install '@username/packagename'
    $ jaws postinstall '@username/packagename' npm

    { [Error: ENOENT, lstat '/Users/kennu/Projects/projectname/aws_modules/@username']
      errno: -2,
      code: 'ENOENT',
      path: '/Users/kennu/Projects/projectname/aws_modules/@username' }

Not sure why JAWS wants to access aws_modules/@username, since it actually creates aws_modules/modulename, where modulename is not the npm package name, but "name" attribute from awsm.json.

PS. The actual module seems to get installed despite the error message. The awsm.json goes into place and is migrated to CloudFormation.

**Comment by ac360** [comment]
Thanks @kennu , we'll look into this :)

**Comment by eahefnawy** [comment]
we ditched postinstall in favor of the new `sls module install` action. Closing...
