### ISSUE TITLE
DX: No error/warning when missing include in serverless.yml

### ISSUE THREAD

**Issue by cdmcmahon** [serverless/serverless#3072]
# This is a Bug Report

## Description

In order to avoid packaging up unnecessary code in each lambda, we use the individual packaging functionality defined in `serverless.yml` by 
```yaml
package:
  individually: true
```

This is great and we love the functionality, however when it comes to testing/production parity it has created problems. Our tests only ensure that an import in a source file has the correct path within our repository, not that the file exists within `serverless.yml`'s include on either the global or especially function level. Is there a way to make serverless throw an error or minimally produce a warning when deploying with a missing an include?

Also if anyone has any other ways to test this other than being sure to hit lambdas after deploying, I'd love to know.

## Additional Data

* ***Serverless Framework Version you're using***:  1.2.1

**Comment by cdmcmahon** [comment]
One solution in the meanwhile is using the [serverless-webpack plugin](https://github.com/elastic-coders/serverless-webpack) to bundle your lambdas

**Comment by HyperBrain** [comment]
But be sure to use `3.0.0-rc.2` of the plugin as version 2 does not yet support individual packaging correctly.

**Comment by cdmcmahon** [comment]
Good to know. Is that necessary though? Could I simply move all my includes into the global serverless.yml include and webpack would bundle each lambda with only the necessary code?

**Comment by HyperBrain** [comment]
No. you can turn off module packaging completely but then you'll end up without modules. The benefit with webpack is, that webpack tells the plugin which modules are needed/referenced after optimizing the code, so any manual interference is not possible or does not make sense at all.
E.g. you have 2 handlers one uses a big module, one not. With individual packaging the first one will have it bundled, the second one not, which is good in terms of cold start times.
You even can bundle node-modules themselves (by using the node-externals package and whitelisting the ones to bundle). Then the benefit is even bigger, as unused code in the module is removed and all 2nd level dependencies too, that are used by the removed code.

**Comment by pmuens** [comment]
Thanks for opening @cdmcmahon 👍

I'll close this issue for now since it got quite stale and the `package` configuration is quite feature-rich, covering most of the cases. Feel free to re-open if you think that this issue is still a problem.
