### ISSUE TITLE
Native Code Compilation

### ISSUE THREAD

**Issue by dcrockwell** [serverless/serverless#308]
Hey everybody. We've run into a blocking issue where we need to use the `mysql2` package in a lambda, but it requires building the native code, which won't work if we pre-build it in our development machine's architecture.

Last night I attempted to integrate both `lambda-packager` and `thaumaturgy` into JAWS, and found it to be prohibitively difficult compared to replicating lambda deployment with `gulp` tasks.

I hear 1.4 has a plugins system that could help with this.

**Comment by ac360** [comment]
Hi @dcrockwell we are aware of this issue and we are working on it.  Either plugins can do this or we can do it natively.  We'll probably make it available as a plugin first, so we can leverage some of the great work done by `thaumaturgy, lambda-packager, etc.`.  The new plugin system is incredibly powerful and it's going to resolve tons of issues.  It even processes lambda deployments concurrently (as well as their plugins).

**Comment by dcrockwell** [comment]
Excellent. I would like to see less features integrated into the core, and more integrated via plugins. This would allow us to both integrate with `thaumaturgy`, and `lambda-packager`, and (possibly?) `jaws-packager`. Same for `browserify`, as well. It would allow `webpack` instead for instance.

Plus there are benefits in delegating work to other teams.

Either way, can't wait to get my hands on the plugins system. :)

**Comment by ac360** [comment]
@dcrockwell Yes!  This is one of many reasons why we have taken so long to do this plugin architecture.  I agree browserify should be moved to a plugin as well.  We'll do this in 1.4.1, likely.  The way the plugin architecture is written will make this very easy.

**Comment by kennu** [comment]
I ran into this issue in my first JAWS project (trying to get bcrypt native code to work). It would be nice to be able to run custom deployment steps to work around any unexpected issues. E.g. I would probably add a small custom step to build the bcrypt module with Docker and inject the Linux version to the Lambda zip.

**Comment by gregpardo** [comment]
Has this been handled yet in serverless? I was wondering about integrating ffmpeg into my lambda containers and this was the only thread I've seem something similar discussed.

**Comment by dherault** [comment]
Hi, is this solved by Serverless 0.5 or optimize-plugin or any plugin ? Thanks.

**Comment by dcrockwell** [comment]
@ac360 I've just completed an alpha of a working remote npm packages for lambda: https://github.com/FreeAllMedia/akiro

It can probably be turned into a serverless plugin fairly easy to solve this issue.

**Comment by dherault** [comment]
@dcrockwell Thanks I'll check it out!

**Comment by flomotlik** [comment]
Would you be able to build those dependencies outside of Lambda (e.g. CI) and then simply have Lambda pick that up in the zip file? For the next iteration of Lambda we want to build in an easier way to include more artifacts into the zip we create, so you can build those artifacts and ship them to lambda.

**Comment by jokeyrhyme** [comment]
@flomotlik are there more details for the resolution of this issue available somewhere? I tested this in 1.0.0-beta.1 and I was still seeing macOS binaries from my local machine end up in Lambda, instead of the desired Linux equivalents.

Is it still desirable to have this addressed within serverless? Or is this considered an exercise for the reader? :)

**Comment by flomotlik** [comment]
@jokeyrhyme I don't think we'll implement anything specifically for this in the short to medium term, as it comes with a lot of complexity. Basically when you deploy from a OSX machine, but want to compile native code for Linux it can either be possible through cross-compilation, or Serverless would have to set up some infrastructure for you that compiles your applications there.

Basically we want Serverless to really only pick up locally what you've prepared in your CI/CD or build process and deploy it. So e.g. compiling specific binaries or installing binaries and putting them in the local directory so they can be deployed is something that should be happening in the users build.

For the specific problem of building binaries for deployment on OSX to Lambda there are 2 options:

1. Deploying to production through Linux based CI/CD process. This is in my optionin the preferred process because deployment to prod should always be automated (I've built CI/CD systems SaaS in the past so I might be slightly biased here)
2. You have a build script that starts a docker container and builds the binaries in the docker container and shares them with the host system to deploy then (or deployment happens inside of Docker as well)

With either one of those you should be able to create those binaries pretty easily. Can't stop myself from plugging Codeship here, but all the other SaaS CI/CD products should be able to accomplish the same (e.g. TravisCI or CircleCI) or your own Jenkins.

**Comment by kennu** [comment]
Just to share my own Docker solution. I currently add a custom "install" script to any package.json that needs a Linux-specific binary for Lambda:

    "install": "[ -e node_modules/sharp/build/Release/sharp.node ] || docker run --rm -v $PWD:/data -w /data node:4 npm install sharp"

I then remove the dependency ("sharp" in this case) from package.json and let the install script install it via Docker. Installation goes into the mounted node_modules folder.

This works pretty smoothly nowadays. Docker is available as a native application for Mac/Windows (https://www.docker.com/products/docker). No need to install VirtualBox or do any folder mappings, etc. Only complication occurs if you need to switch between Linux and macOS versions to run locally.

**Comment by jokeyrhyme** [comment]
@kennu I made a Node.js script that is effectively quite similar: https://gist.github.com/jokeyrhyme/d57097a491aa5ecaf27532d057d72461
I noticed that `npm rebuild` is often all that is required, although deleting node_modules first is sometimes more reliable

**Comment by DrJid** [comment]
My apologies, I'm pretty green to all of this. I'm attempting to compile sequelize and the pg-native package from my mac on to lambda for PostgresSQL which brought me to this page.. @jokeyrhyme How exactly can I use your script? Will I have to set up Docker locally on my machine as well?

Or perhaps, @flomotlik any direction to set up a linux based CI from a complete beginner's perspective would be super appreciated!

**Comment by jokeyrhyme** [comment]
@DrJid 

1. save the "docker-npm.js" script somewhere

2. `cd` to your Serverless project (same directory that contains serverless.yml)

3. `node path/to/docker-npm.js` to have the Linux versions of native modules installed

4. `serverless deploy` as normal

**Comment by trjstewart** [comment]
I am also trying to get `pg-native` to work on lambda. I have tried the solution outlined above by @jokeyrhyme, resulting in the following error:
```json
{
  "errorMessage": "libpq.so.5: cannot open shared object file: No such file or directory",
  "errorType": "Error",
  "stackTrace": [
    "Object.Module._extensions..node (module.js:434:18)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "bindings (/var/task/node_modules/bindings/bindings.js:76:44)",
    "Object.<anonymous> (/var/task/node_modules/libpq/index.js:1:108)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/pg-native/index.js:1:75)",
    "Module._compile (module.js:409:26)"
  ]
}
```

Did you have any success getting it to work @DrJid?

_If it's any relevance; I am running ubuntu 16.04, serverless 1.6.1, and node 6.5_

**Comment by ffxsam** [comment]
Has anyone had any luck getting `sharp` to work with Serverless?

I don't think you need Docker at all. This seems to build the proper binary in `node_modules`:

```
$ npm_config_platform=linux npm_config_arch=x64 yarn add sharp
[...]
$ file node_modules/sharp/build/Release/sharp.node
node_modules/sharp/build/Release/sharp.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a9140d680f0584b72956a98fb96067659b722c9b, stripped
```

The problem is, as soon as I run `sls deploy`, it seems to rebuild the packages for Mac:
```
$ sls deploy
$ cd .serverless
$ unzip upload-processor.zip
$ file node_modules/sharp/build/Release/sharp.node
node_modules/sharp/build/Release/sharp.node: Mach-O 64-bit bundle x86_64
```

Any advice?

**Comment by ffxsam** [comment]
Boom, got it! I added this to my `serverless.yml`:

```yaml
custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - npm_config_platform=linux npm_config_arch=x64 yarn add sharp
```

Works like a charm!

**Comment by dazzlersa** [comment]
Hi, 
How would I implement the -script for an npm package?
Based on my question here:
https://github.com/Apollon77/node-mbus/issues/90
