### ISSUE TITLE
invoke local failing (Windows)

### ISSUE THREAD

**Issue by spf3000** [serverless/serverless#3093]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by spf3000** [comment]
The invoke local function does not work and reports a possible bug on a windows machine, even though the same code works on a mac.  See error message


λ serverless invoke --function product --data '{"productId":"p1234"}'
{
    "errorMessage": "The product does not exists"
}

  Error --------------------------------------------------

     Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       7.3.0
     Serverless Version: 1.5.0

**Comment by pmuens** [comment]
@spf3000 thanks for reporting.

The error message

```
The product does not exists
```

is not a Serverless error message. It seems like it's raised by your application (do you check for products anywhere in your code)?

**Comment by pmuens** [comment]
Closing this since it seems to be a problem in the functions code and not in Serverless.

Feel free to reopen it if the problem persists.
