### ISSUE TITLE
Request: Cleaner support for IAM

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#3104]
**This is a Feature Proposal**

**Description**
I wanted to make a formal request for more integrated IAM support. I used the workaround successfully:
[http://forum.serverless.com/t/solved-api-gateway-how-to-set-authorization-in-method-request-to-aws-iam/175/7](url)
So I know you guys know that people are using it ... I just couldn't find a formal request here in github, so I thought I'd request it. My apologies if this is a repeat.

**What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.**
Finding some well-integrated way to indicate which HTTP events require AWS IAM authentication. It's the equivalent to the action you take in the AWS Console to activate IAM:
[https://aws.amazon.com/premiumsupport/knowledge-center/iam-authentication-api-gateway/](url)
By setting `authorizationType` to `AWS_IAM`.

**If there is additional config how would it look**
I trust you guys to integrate it with your other authorization flags.

**Similar or dependent issues:**
[http://forum.serverless.com/t/solved-api-gateway-how-to-set-authorization-in-method-request-to-aws-iam/175/7](url)

**Additional Data**
**Serverless Framework Version you're using**:
v1.5
**Operating System**:
Windows 10 x32, Node 6.9.2

**Comment by pmuens** [comment]
Thanks for reporting @cdichiara 

Closing this issue since Serverless v1.14 will introduce support for t`AWS_IAM`.

**Comment by cdichiara** [comment]
Great news, thanks!
