### ISSUE TITLE
Camel Case Consistency 

### ISSUE THREAD

**Issue by selectedpixel** [serverless/serverless#3108]
When creating an API Gateway event and defining parameters the value for query strings to be generated is 'querystrings'. In other situations like this the value follows camel case formatting. For example, when generated custom status codes the value is 'statusCodes'.  Also, when I was using the incorrect formatting of 'queryStrings' I was getting no feedback that this was an incorrect value. 

This is a rather small issue, but it seems like the formatting should be consist from value to value.

**Comment by pmuens** [comment]
Thanks for the suggestion @ghost!

We're tracking a refactoring of the naming in another issue, so I'll close this one. Some other parts of this naming are on AWS an we can't change them.
