### ISSUE TITLE
Hello World packaging artifact file path case incorrect on Ubuntu

### ISSUE THREAD

**Issue by daves0** [serverless/serverless#3109]
# This is a Bug Report

## Description

When deploying the Hello World example in C# from my Ubuntu machine, the deploy failed with the error "ENOENT: no such file or directory, open 'bin/Release/netcoreapp1.0/publish/deploy-package.zip'".  Note the upper-case R in Release in that path.

Upon inspection, the serverless.yml file created via the command

serverless create --template aws-csharp --path (mypath)

contained the following artifact: line under package:

 artifact: bin/Release/netcoreapp1.0/publish/deploy-package.zip

You will note the upper-case letter R in Release in that path, that matches the error message.  On my hard drive the actual file path contains a LOWER-case r .. it is, in fact, bin/release/netcoreapp1.0/publish/deploy-package.zip.  Since Ubuntu is a case-sensitive operating system, this is what is causing the error.

As a fix, I have changed the casing of Release to lower, and the deploy now succeeds.  Please verify all path casing in your .Net support, as even though Windows is not case sensitive, other OS's are and .Net is cross-platform.

Similar or dependent issues:
none that I could find

## Additional Data

This is in Serverless Framework 1.5.0, running on Ubuntu 16.04.

**Comment by FLGMwt** [comment]
I might have introduced this merging some changed into a feature branch of mine. Taking a look.

**Comment by pmuens** [comment]
Closed with #3112
