### ISSUE TITLE
feature to power-wash and start over

### ISSUE THREAD

**Issue by swarthout** [serverless/serverless#311]
I was wondering if there was currently a way to effectively "power-wash" the aws resources required for a jaws project and deploy your project as if you were creating it from the beginning?  I am having trouble with artifacting in my aws resources and it would be nice to start fresh some times.

**Comment by DoWhileGeek** [comment]
I believe this is more or less covered by #129, and its already on the backlog.

**Comment by eahefnawy** [comment]
we now have `sls project remove` action to solve this issue :)
