### ISSUE TITLE
Environment variables cannot contain a comma

### ISSUE THREAD

**Issue by petemill** [serverless/serverless#3118]
# This is a Bug Report

## Description

* *What went wrong?*
   After setting an environment variable to "myvar,withcomma" for a function in serverless.yml, an error occurs when deploying using the command `serverless deploy`
* *What did you expect should have happened?*
   No error, and the environment variable attached to the lambda function intact
* *What was the config you used?*
  ```yml
  functions:
    myFunc:
       environment:
          MY_VAR: myvar,withcomma
  ```
* *What stacktrace or error message from your provider did you see?*
   ```
    An error occurred while provisioning your stack:MyFuncLambdaFunction
     - 1 validation error detected: Value at 'environment.variables'
     failed to satisfy constraint: Map value must satisfy
     constraint: [Member must satisfy regular expression
     pattern: [^,]*].
    ```

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.0
* ***Operating System***: darwin (node 6.9.4)

**Comment by pmuens** [comment]
Hey @petemill thanks for opening this issue.

Environment variables can only contain alphanumeric characters (see http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html --> Rules for **Naming Environment Variables**), therefore commas are not allowed.

**Comment by cove** [comment]
I'm running into this when the env var name is indeed valid, but the value of the env var contains commas. I don't seem to see in the aws doc that there are restrictions on the values preventing commas. Maybe the check is too broad in sls?
