### ISSUE TITLE
Serverless forum doesn't use SSL

### ISSUE THREAD

**Issue by brettneese** [serverless/serverless#3123]
# This is a feature proposal

## Description
The Serverless forum doesn't use SSL. The Serverless forum should use SSL, especially since it requires logging in via GitHub oAuth. It's 2017.

Alternatively -- and this would be simpler for me as a developer -- simply direct people to use GitHub issues to ask questions. It's much easier to manage fewer lines of communication. 

Currently there are at least 3 channels to request support, and many questions could possibly be turned into documentation improvement issues, anyhow.

## Similar or dependent issues:
N/A

## Additional Data
N/A

**Comment by pmuens** [comment]
Thanks for mentioning that @brettneese 

/cc @DavidWells @mthenw

**Comment by DavidWells** [comment]
Updating our discourse account to support SSL. It's a 'premium' feature over there
