### ISSUE TITLE
Different lambdas having different roles

### ISSUE THREAD

**Issue by vlamic** [serverless/serverless#313]
Hi,

First of all - I love JAWS framework. Thank you guys for awesome work!

I have a question regarding lambdas a roles. I have created a few awsm modules and cannot figure out a way to have different roles for different modules. Is there a way to do it? I have modified my resources-cf.json files to create all required roles which were successfully created after `jaws deploy resources` command. I have also added an additional parameter "aaLambdaRoleArnUser" to `lambdas-cf.json`. However, after I run a deploy command `jaws deploy lambdas` my "aaLambdaRoleArnUser" parameter is removed and lambdas are not getting my role set. Any help would be appreciated.

Best,
Vlad

**Comment by eahefnawy** [comment]
as of Serverless v0.5, you can add `customRole` to `s-function.json` allowing each lambda to have its own role :)
