### ISSUE TITLE
Dependency cannot import another dependency

### ISSUE THREAD

**Issue by joshg111** [serverless/serverless#3139]
Sorry for the poor title, I'm not sure how else to describe this issue.

I'm using latest version of ubuntu 16.04 i think. 

The error from aws lambda log is as follows:
Unable to import module 'handler': No module named zope.interface

Also, I can run this locally without any issues, all dependencies seem to be resolving successfully. 

Inside my handler.py I import the following packages. Scrapy is one of the modules which I depend on which is found in ./vendored.

```python
import os
import sys

here = os.path.dirname(os.path.realpath(__file__))
#sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./craigslist_sample"))

#from vendored.twisted.internet import reactor
from scrapy.crawler import CrawlerProcess
from scrapy.crawler import CrawlerRunner
from scrapy import signals
from craigslist_sample.spiders.test import MySpider
from scrapy.utils.project import get_project_settings
import argparse
import logging
import json
import time
```

In handler.py I import the scrapy module found in ./vendored. The following is my tree structure at a depth of 2. This structure is exactly what serverless deploys and is what's inside zip file I found in the s3 bucket.

.
├── craigslist-kbb.zip
├── craigslist_sample
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── items.py
│   ├── items.pyc
│   ├── pipelines.py
│   ├── pipelines.pyc
│   ├── settings.py
│   ├── settings.pyc
│   └── spiders
├── handler.py
├── INSTALL.txt
├── items.jl
├── log.log
├── scrapy.cfg
├── try.py
└── vendored
    ├── appdirs-1.4.0.dist-info
    ├── appdirs.py
    ├── appdirs.pyc
    ├── attr
    ├── attrs-16.3.0.dist-info
    ├── cffi
    ├── cffi-1.9.1.dist-info
    ├── _cffi_backend.so
    ├── constantly
    ├── constantly-15.1.0.dist-info
    ├── cryptography
    ├── cryptography-1.7.1.dist-info
    ├── cssselect
    ├── cssselect-1.0.1.dist-info
    ├── easy_install.py
    ├── easy_install.pyc
    ├── enum
    ├── enum34-1.1.6.dist-info
    ├── idna
    ├── idna-2.2.dist-info
    ├── incremental
    ├── incremental-16.10.1.dist-info
    ├── ipaddress-1.0.18.dist-info
    ├── ipaddress.py
    ├── ipaddress.pyc
    ├── lxml
    ├── lxml-3.7.2.dist-info
    ├── OpenSSL
    ├── packaging
    ├── packaging-16.8.dist-info
    ├── parsel
    ├── parsel-1.1.0.dist-info
    ├── pkg_resources
    ├── pyasn1
    ├── pyasn1-0.1.9.dist-info
    ├── pyasn1_modules
    ├── pyasn1_modules-0.0.8.dist-info
    ├── pycparser
    ├── pycparser-2.17.dist-info
    ├── pydispatch
    ├── PyDispatcher-2.0.5.dist-info
    ├── pyOpenSSL-16.2.0.dist-info
    ├── pyparsing-2.1.10.dist-info
    ├── pyparsing.py
    ├── pyparsing.pyc
    ├── queuelib
    ├── queuelib-1.4.2.dist-info
    ├── scrapy
    ├── Scrapy-1.3.0.dist-info
    ├── service_identity
    ├── service_identity-16.0.0.dist-info
    ├── setuptools
    ├── setuptools-34.0.2.dist-info
    ├── six-1.10.0.dist-info
    ├── six.py
    ├── six.pyc
    ├── twisted
    ├── Twisted-16.6.0.dist-info
    ├── w3lib
    ├── w3lib-1.16.0.dist-info
    ├── zope
    ├── zope.interface-4.3.3.dist-info
    └── zope.interface-4.3.3-py2.7-nspkg.pth

54 directories, 27 files

It seems that aws lambda is able to import resolve the scrapy module found in handler.py, but I'm guessing scrapy eventually leads to and import of this zope.interface dependency module. For some reason this one is not getting resolved. Aws lambda has no line number in the logs for me to check exactly where the import issue is. 

From handler.py I have included the ./vendored directory to my path variable as you can see in the code i pasted above. 

I noticed this file zope.interface-4.3.3-py2.7-nspkg.pth. Contents below. It seems to set some path variable. Perhaps this is the issue? Or perhaps I could try setting a python path environment variable? Perhaps there is some option i can add to the serverless.yml file which will help resolve package dependencies? Also, I just installed serverless a few days ago with the command npm install -g serverless. I noticed there were some issues reported regarding package dependency resolution, and the fix was in a more recent build. Should I try moving to a later version of serverless? What's the command for that?

```python
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('zope', types.ModuleType('zope'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
```

**Comment by pmuens** [comment]
Hey @joshg111 thanks for opening.

Could you please provider your `serverless.yml` and your `handler.py` file? Thanks 👍

**Comment by joshg111** [comment]
serverless.yml
```yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: craigslist-kbb # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

package:
  artifact: /home/joshg111/z1.zip

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-1

functions:
  hello:
    handler: handler.entry_point
    events:
       - http:
           path: cars
           method: get
```

handler.py
```python
import os
import sys

here = os.path.dirname(os.path.realpath(__file__))
#sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./craigslist_sample"))

#from vendored.twisted.internet import reactor
from scrapy.crawler import CrawlerProcess
from scrapy.crawler import CrawlerRunner
from scrapy import signals
from craigslist_sample.spiders.test import MySpider
from scrapy.utils.project import get_project_settings
import argparse
import logging
import json
import time

TRANSMISSION = {'automatic': '2', 'manual': '1'}

def setup_crawler(url_list, args):
    settings = get_project_settings()
    crawler = CrawlerProcess(settings)
    print "setup_crawler before"
    crawler.crawl('craigs', url_list, args)
    print "setup_crawler"
    crawler.start()

def build_craigs_url(args):
    base_url = "http://sandiego.craigslist.org/search/cto?sort=date&hasPic=1&auto_title_status=1&auto_fuel_type=1"
    make_model_list = args.make_model
    min_price = str(args.min_price)
    max_price = str(args.max_price)
    min_year = str(args.min_year)
    max_year = str(args.max_year)
    min_miles = str(args.min_miles)
    max_miles = str(args.max_miles)

    url_list = []
    print("\nmake_model_list = " + str(make_model_list))
    for make_model in make_model_list:
        url = base_url
        if args.transmission:
            url += "&auto_transmission=" + TRANSMISSION[args.transmission]

        url += "&min_price=" + min_price + "&max_price=" + max_price + "&auto_make_model=" + make_model + "&min_auto_year=" + min_year + "&max_auto_year=" + max_year + "&min_auto_miles=" + min_miles + "&max_auto_miles=" + max_miles

        url_list.append(url)

    return url_list

def get_args():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter, description="Find deals on craigslist cars by comparing the price to kelley blue book.")
    parser.add_argument("make_model", nargs='*', default=["toyota+camry"], help="The make model of the cars. Models are optional. Ex: Honda Nissan+Altima toyota+land+cruiser+wagon. This example will search on all Honda's, Nissan Altimas, and Toyota land cruiser wagon's")
    parser.add_argument("-e", "--excess_price", type=int, default=15, choices=xrange(100), metavar="[0-99]", help="The maximum percentage the craigslist price can exceed the kelley blue book price.")
    parser.add_argument("--min_price", type=int, default=0, help="The minimum price of the car.")
    parser.add_argument("--max_price", type=int, default=11000, help="The maximum price of the car.")
    parser.add_argument("--min_year", type=int, default=2000, help="The minimum year of the car.")
    parser.add_argument("--max_year", type=int, default=2014, help="The maximum year of the car.")
    parser.add_argument("--min_miles", type=int, default=0, help="The minimum number of miles on the car.")
    parser.add_argument("--max_miles", type=int, default=140000, help="The maximum number of miles on the car.")
    parser.add_argument("--transmission", choices=["automatic", "manual"], default="automatic", help="The transmission type of the car.")

    args = parser.parse_args()
    return args

def entry_point(event, context):
    print "here = " + here
    args = get_args()
    url_list = build_craigs_url(args)

    # setup_crawler(url_list, args)
    #
    # print "\n\nspiders finished crawling\n\n"
    # time.sleep(4)
    #
    # f = open("items.jl", 'r')
    # body = {
    #     "message": f.read()
    # }
    #
    # f.close()

    response = {
        "statusCode": 200,
        "body": str(url_list)
    }

    # response = {
    #     "statusCode": 200,
    #     "body": json.dumps(body)
    # }

    return response


# if __name__ == "__main__":
#     print sys.path
#     print entry_point(None, None)
```

**Comment by joshg111** [comment]
Problem solved. Turns out creating a blank __init__.py file in the ./vendored/zope directory fixed the issue. You can reference the following article, and look at the second solution. 

http://stackoverflow.com/questions/7816799/getting-py2exe-to-work-with-zope-interface

**Comment by pmuens** [comment]
Awesome! Thanks for responding and sharing the solution!

I'll then close this issue. 👍
