### ISSUE TITLE
jaws module create - awsm.json not synchronized to CloudFormation?

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#315]
Sorry if I'm missing something obvious here. When I create a new module using

    jaws module create xxx yyy

a top level awsm.json file is created for the module (xxx). But I don't see any JAWS command that would apply the changes made to this awsm.json into the main CloudFormation templates under cloudformation/*. Is it supposed to happen automatically when I deploy?

    jaws deploy resources

Or should I be running some kind of merge command first before deploying?

**Comment by eahefnawy** [comment]
You're right, currently `sl resources deploy` only deploys the template from the cloudformation dir. We'll be working on making it better by getting all the resources from all modules and update all.

**Comment by eahefnawy** [comment]
you can track the progress on this issue in this trello card:
https://trello.com/c/ocV3GDiZ/151-resources-refactor-currently-being-worked-on-in-the-resources-branch-check-this-card-s-description-for-more-information
