### ISSUE TITLE
npmjs package page not showing readme

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3157]
# This is a [Minor] Bug Report

https://www.npmjs.com/package/serverless

The package pages doesn't feature a readme:

![image](https://cloud.githubusercontent.com/assets/571200/22387223/6a11adde-e48f-11e6-9422-352dad7c1859.png)

One would probably be desirable.

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by paulSambolin** [comment]
Hey @erikerikson, I think the solution to this is to add the following line to the package.json

```javascript
"homepage": "https://github.com/serverless/serverless#readme"
```

**Comment by erikerikson** [comment]
Thanks @paulSambolin!  Pardon my ignorance 😄

**Comment by erikerikson** [comment]
Hmm...  All the documentation seems to indicate that you just need a README.md at the root of the project.

There is an issue filed against the wrong repository (Google led me here):
https://github.com/npm/npm/issues/15585
An incident report:
http://status.npmjs.org/incidents/tj3qsythtgg8
And, the bug the npm team is using to track this matter:
https://github.com/npm/registry/issues/118

**Comment by pmuens** [comment]
Thanks for reporting!

/cc @eahefnawy

**Comment by eahefnawy** [comment]
hmmm this must be a new update by npm. I've seen our README there previously many times.

Thanks for the tip @paulSambolin ... will add that line 😊

**Comment by erikerikson** [comment]
This remains a problem.  Not sure that it should be closed.

**Comment by pmuens** [comment]
Thanks for getting back @erikerikson!

@eahefnawy reached out to the npm support via E-Mail 📧

**Comment by erikerikson** [comment]
https://github.com/npm/registry/issues/120#issuecomment-276157329

**Comment by erikerikson** [comment]
Apparently, there's a version of NPM that fails to include README.md

**Comment by pmuens** [comment]
Nice @erikerikson ! Thanks for asking and opening up the issue at `npm`!

**Comment by pmuens** [comment]
Reopening this and ccing @eahefnawy here!

**Comment by erikerikson** [comment]
All sorted now.  The README is showing.  @eahefnawy was updating your npm the resolution?

**Comment by pmuens** [comment]
@erikerikson yes, updating npm resolved the issue (the support suggested that as well).

Thanks for getting in touch with the npm team! 👍

**Comment by erikerikson** [comment]
Awesome, thanks.  Wanted to follow up :D

**Comment by rouzwelt** [comment]
I just published a package and README.md is not showing, it is definitely present in the package, but it is not showing in the front page, any idea what is causing the issue and how to fox it?

I have tried removing the README and then add it again and publish again, didnt work,
tried 2 different versions of npm for publishing and it didnt work either

**Comment by fwouts** [comment]
I'm seeing the same issue.

I published a new version of https://www.npmjs.com/package/@previewjs/screenshot, and it clearly has a README.md (seen in the "Code" tab) but it's not shown. It was shown on v0.0.1 which I published yesterday, so I'm assuming this is an issue on the NPM website today.

**Comment by sijakret** [comment]
> I just published a package and README.md is not showing, it is definitely present in the package, but it is not showing in the front page, any idea what is causing the issue and how to fox it? here is the package https://www.npmjs.com/package/codemirror-rainlang
> 
> I have tried removing the README and then add it again and publish again, didnt work, tried 2 different versions of npm for publishing and it didnt work either

i have the exact same issue!

**Comment by cristicretu** [comment]
> > I just published a package and README.md is not showing, it is definitely present in the package, but it is not showing in the front page, any idea what is causing the issue and how to fox it? here is the package https://www.npmjs.com/package/codemirror-rainlang
> > I have tried removing the README and then add it again and publish again, didnt work, tried 2 different versions of npm for publishing and it didnt work either
> 
> i have the exact same issue!

Me too! Seems to be an issue from npm.

**Comment by seyacat** [comment]
Someties shows and sometimes not

**Comment by alphonse92** [comment]
Still happening!

**Comment by alphonse92** [comment]
I submited a new issue here: https://github.com/npm/cli/issues/6346

**Comment by rafalzawadzki** [comment]
Just happened to me too, on a new package!

**Comment by chancesmith** [comment]
It seems to resolve itself over time.

**Comment by tripolskypetr** [comment]
FYN that s**t happened again. Why don't stop making any changes in source code if it worked well? For me all microsoft doing on VSCode and NPM is budget looting

**Comment by joshdavenport** [comment]
I saw no README on a just published package for about 15 minutes, then I installed the package in a project and it appeared - guessing this is a caching thing.

**Comment by tripolskypetr** [comment]
I created an issue in NPM BugTracker and asked them to roll back that "feature" https://github.com/npm/cli/issues/6360. It real nasty because breaks google indexing

**Comment by dandv** [comment]
https://www.npmjs.com/package/search-modal also doesn't show the README from its repo, what's going on?

**Comment by char0n** [comment]
https://www.npmjs.com/package/@swagger-api/apidom-core doesn't show README as well.

**Comment by mmorper0** [comment]
> https://www.npmjs.com/package/@swagger-api/apidom-core doesn't show README as well.

It just happened to me as well with a package I just published, it looks like it takes a bit of time from publishing until it's displayed. For me, now it's working as expected.

**Comment by matallui** [comment]
Experiencing the same issue with `@rtco/peer`

**Comment by Pranshu321** [comment]
Experiencing the same issue npm package : https://www.npmjs.com/package/filtering-package

**Comment by polioan** [comment]
same :( https://www.npmjs.com/package/typescript-notion-formulas

**Comment by prateek0103** [comment]
We're facing the same issue here: https://www.npmjs.com/package/@customerglu/react-web-sdk

Our previous version's README.md was rendering just fine, and even if you check the repo, it has README.md in root, we've also waited over an hour for the cache to be updated, but to no avail. What's the fix for this?

**Comment by panzi** [comment]
Same issue here: https://www.npmjs.com/package/@panzi/carbon-client
Waited 40 minutes and there's still no README displayed. It worked up until now!

**Comment by AshleyDawson** [comment]
Same issue here: https://www.npmjs.com/package/@htfn/cli

Readme was uploaded correctly: https://www.npmjs.com/package/@htfn/cli?activeTab=code 

(seemed to just stop working after I pushed some very minor updates yesterday)

**Comment by sneakylenny** [comment]
Got the same issue: https://www.npmjs.com/package/vite-plugin-json5

Just published a patch, good to see I'm not the only one

**Comment by wattsjay** [comment]
Me too for [za-inflation](https://www.npmjs.com/package/za-inflation)

**Comment by whitespaca** [comment]
Same: [https://www.npmjs.com/package/excel-database](https://www.npmjs.com/package/excel-database)

It was working fine until yesterday, but starting today it suddenly stops working.

**Comment by simnalamburt** [comment]
Same issue here: https://www.npmjs.com/package/slate-irc-parser
