### ISSUE TITLE
Integrate AWS's documentation features for API Gateways

### ISSUE THREAD

**Issue by mrfishy** [serverless/serverless#3158]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Amazon provides a [mechanism for storing documentation for API Gateway APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api.html). While it is good to have a place to store documentation, the documentation must be entered either as [hand-crafted JSON into the API Gateway Console](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api-quick-start-with-console.html), or uploaded as [JSON via a REST API](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api-quick-start-with-restapi.html#api-gateway-documenting-api-quick-start-with-restapi-add-content-to-api). Once deployed, it can be downloaded as a [Swagger file with Amazon extensions](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api-quick-start-publishing.html#api-gateway-documenting-api-publishing-export-documentation-version). At the time of this writing I have not been able to find any tooling or support that makes using these documentation facilities feasible or very useful in a production environment.

It would be great if Serverless could support documenting APIs, ideally making Amazon's documentation capability actually useful.  

I would like to request a feature that behaves similarly to the [raml-serverless plugin](https://github.com/andrewcurioso/raml-serverless), but which would:

1. Allow documentation to be embedded in the serverless.yml file, directly associating each API element with its documentation;
1. Support the extraction of the API documentation from the serverless.yml file into _standard_ Swagger,  RAML, or some other format that can then be processed to produce clean, usable, human-readble documentation
1. Support the AWS API documentation mechanism, associating each documentation  part with the appropriate API element

The last point would be nice-to-have, but the feature could still be extremely valuable without it.

---------------
* If there is additional config how would it look

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by mykemd** [comment]
What about this plugin?
https://github.com/9cookies/serverless-aws-documentation

**Comment by mrfishy** [comment]
@mykemd Thank you for the pointer!  This looks promising.

**Comment by pmuens** [comment]
Closing this for now since there's a plugin available which does the trick.
