### ISSUE TITLE
Adopt GitFlow

### ISSUE THREAD

**Issue by dcrockwell** [serverless/serverless#316]
Hey, everybody.

If the project adopted [gitflow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/), it would be possible for others to explore development branches for purposes of familiarizing and contributing documentation, with less chance of hitting unfinished code as only completed feature branches are merged into develop. develop always then has a working version of whatever is in development, even if there are multiple teams working on it.

Each feature would get its own branch, then merge into a develop branch from which releases are created from.

It would also facilitate easy hotfixes and master deploys.

It may seem complicated at first, but it's a very simple system to use in practice.

**Comment by binoculars** [comment]
:+1: I've used it. Makes life way easier even for one person.

**Comment by sielay** [comment]
https://github.com/jaws-framework/JAWS/issues/310

**Comment by obie** [comment]
+1

**Comment by ac360** [comment]
Hi @obie, I was just reading your [awesome Medium post](https://medium.com/in-pursuit-of-serverless-architecture/what-if-we-didn-t-need-an-app-server-anymore-f5b6586c58f4#.7c2vslujs) which @kevinold referred me to.  Nice work on that article and welcome to the JAWS community.  You already have some fans here :)

@dcrockwell You are absolutely right.  We will be adopting this.  On Monday (12/7), we will be making some big changes.  One of those changes will be to adopt GitFlow.  Thanks for recommending this.  We're trying to do everything right and it's great contributors like you guys :)  Looking forward to hearing your feedback on Monday!
