### ISSUE TITLE
CloudFormation issue in sls v1.6

### ISSUE THREAD

**Issue by skilledDeveloper** [serverless/serverless#3168]
It looks like sls tries to recreate an existing log group and it fails:

```
sls deploy -s dev
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (16.02 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: MyFuncLogGroup
     - /aws/lambda/myfunc-dev-myfunc already exists.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.6.0
```

Same configuration was working just fine in v1.5.

**Comment by dannycohn** [comment]
Please read the 1.6.0 release notes, they explain this and what to do to resolve it

**Comment by skilledDeveloper** [comment]
Just saw https://github.com/serverless/serverless/releases/tag/v1.6.0
The question is, if there is a breaking change why don't you increase the major version?

**Comment by dannycohn** [comment]
I imagine it's because while it breaks existing deployments, if only temporarily, it is not a change to the api itself. The same code can be used in 1.6.0 as in 1.5.1. You just need to redeploy it or clean up the log groups first

**Comment by skilledDeveloper** [comment]
These kind of breaking changes makes sls less reliable in real production environments. I have locked down to major version 1 and I expect it to always work with all minor changes.

**Comment by dannycohn** [comment]
I'll let the maintainers defend their decision when they come online in a few hours, but since you can easily maintain your existing code and installation by simply backing up and then deleting your old log groups, it doesn't seem like a real breaking change to me.

**Comment by skilledDeveloper** [comment]
Also, if I have 100 deployments, does it mean I have to go delete/rename their log group manually?

**Comment by dannycohn** [comment]
Yes. It would be nice if someone wrote a script to handle this for you and contributed to the community. Sadly I cannot volunteer due to time constraints.

**Comment by skilledDeveloper** [comment]
Another thing:
You can easily remove log group if the service is in prod and receiving high traffic.
The moment you delete it, it gets created again.

**Comment by horike37** [comment]
@skilledDeveloper 
Just released the plugin to delete all log groups in serverless.yml.
https://github.com/horike37/serverless-delete-loggroups

This may be useful for you.

**Comment by vladgolubev** [comment]
@horike37 thanks for the plugin! Just removed my log groups.

But unfortunately, deployment now fails with new error:

```
     An error occurred while provisioning your stack: IamPolicyLambdaExecution
     - Template error: LogGroup /aws/lambda/********
     doesn't exist.
```


So before it was: **log group already exists**, and now error is **log group doesn't exis**t. Kinda funny :sweat_smile:

**Comment by vladgolubev** [comment]
Okay, so for me the reason was this CloudFormation error - https://github.com/serverless/serverless/issues/2614#issuecomment-275957310

After renaming deployment is successful!

**Comment by skilledDeveloper** [comment]
How about the issue I mentioned above? 
https://github.com/serverless/serverless/issues/3168#issuecomment-276249144

**Comment by garethmcc** [comment]
I have a similar problem to @skilledDeveloper . My running API has a large amount of traffic going to it and as soon as I manually delete the implicitly created log file its get recreated implicitly by traffic. Right now I need to deploy additional changes to my service and I cannot rename the service because it will also alter the URL of my API Gateway endpoints.

Is there perhaps some other solution, such as turning logs off?

**Comment by pmuens** [comment]
Thanks for the reply @garethmcc 👍 

Hmm 🤔 yes, I believe the best option right now is to disable logs during the transition...

@eahefnawy do you have any other thoughts or recommendations?

**Comment by eahefnawy** [comment]
@garethmcc @pmuens yeah I think temporary disabling logs during the transition is probably the best approach. If not, some sort of a blue/green deployment setup might work.

**Comment by garethmcc** [comment]
@pmuens How would you do that?

Ultimately I ended up adding a name parameter to each function in my serverless.yml in order to have new log files get created.

**Comment by tyrsius** [comment]
@dannycohn 
>I imagine it's because while it breaks existing deployments, if only temporarily, it is not a change to the api itself. The same code can be used in 1.6.0 as in 1.5.1. You just need to redeploy it or clean up the log groups first

That is not how semver works. If upgrading from 1.5.1 to 1.6.0 causes the CLI to throw errors then its a breaking change. Semver doesn't just cover the API, it covers the *actual operation of the program*. If you release a breaking change you should bump the major version.

The callous attitude towards breaking changes and "just delete production and redeploy" should worry everyone seriously considering using serverless. These guys don't seem to care what they break, or when.

**Comment by pmuens** [comment]
Closing this stale issue for now.

FWIW we've re-adopted the `semver` versioning rules a long time ago. More information regarding that can be found in our [`VERSIONING.md`](https://github.com/serverless/serverless/blob/master/VERSIONING.md) file.

**Comment by tommedema** [comment]
This issue still seems to occur where LogGroups are not being removed, even though the console log says they are, they are still visible in the AWS console. This causes re-deployments to fail.

https://github.com/dougmoscrop/add-custom-resource/issues/4

**Comment by AnthonyWC** [comment]
I got a similar error when I changed my stage name; the error message is worked slightly different as it complains about the Log group exists in stack:

```
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: DefaultLogGroup - /aws/lambda/lambda-** already exists in stack arn:aws:cloudformation:us-east-*******:stack/lambda-*****/952b8b50-5f88-**********.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.11.2
     Serverless Version:     1.27.3
```

The plugin from @horike37 doesn't help in this case since the log group itself doesn't actually exist but exists in the stack.  The only solution I've found so far that worked was to delete the stack itself. :/

**Comment by hemanthvaddi** [comment]
Hi, I'm also facing this error. it is mentioned that, to avoid this error we need to set `cfLogs: true` 
where should i set this flag?

**Comment by rafaeldasilva** [comment]
Serverless Error ---------------------------------------

  An error occurred: <Lambda_Name>LogGroup - Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/lambda/<LogGrup_Name>"}' already exists." (RequestToken: ***************************, HandlerErrorCode: AlreadyExists).

  Stack Trace --------------------------------------------

ServerlessError: An error occurred: <Lambda_Name>LogGroup - Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/lambda/<LogGrup_Name>"}' already exists." (RequestToken: ***************************, HandlerErrorCode: AlreadyExists).
    at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:121:33
From previous event:
    at AwsDeploy.monitorStack (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12)
    at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:28
From previous event:
    at AwsDeploy.update (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:8)
From previous event:
    at AwsDeploy.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:35)
From previous event:
    at AwsDeploy.updateStack (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:113:33)
From previous event:
    at AwsDeploy.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
    at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:464:55
From previous event:
    at PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.spawn (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:484:17)
    at AwsDeploy.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
    at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:464:55
From previous event:
    at PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:116:33
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Serverless.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:103:74)
    at /usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js:44:32
    at /usr/local/share/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:144:16
    at /usr/local/share/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:156:23)
From previous event:
    at /usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js:44:10
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js:30:6
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js:71:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           12.20.1
     Serverless Version:     1.47.0
