### ISSUE TITLE
API Gateway timeout after 30 seconds

### ISSUE THREAD

**Issue by joshg111** [serverless/serverless#3171]
It seems aws api gateway has a timeout of 30 seconds. I am getting the following error message: "Endpoint request timed out". I don't think there is any way to increase the api gateway timeout. I can run my aws lambda function within the aws lambda console and everything works fine. It just takes about 120 seconds to complete.

1. Is there another event that allows for lambda to run for longer period time while keeping a simple request/response like model?
2. Is there a way to increase api gateway timeout?
3. I guess I could create a schedule event that will run every hour or so, and just cache data in a database, then requests could be satisfied much faster than 30 seconds. This model is not ideal though.

**Comment by pmuens** [comment]
Hey @joshg111 thanks for asking the question.

Is there any way you could split up your Lambda into multiple smaller ones and chain them together?

**Comment by joshg111** [comment]
I could split it up, but it would kinda defeat the purpose of the framework I use. Thanks for the thought tho.

**Comment by paullegrand** [comment]
@joshg111 , were you ever able to resolve this issue? I'm having a similar issue, where my function takes ~45 seconds to run through the whole thing, and splitting it up would kinda defeat the purpose. Thanks

**Comment by DavidTPate** [comment]
For context, this is a limitation imposed by [AWS for API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html). Here's the specific part:

> Integration timeout - 30 seconds for all integration types, including Lambda, Lambda proxy, HTTP, HTTP proxy, and AWS integrations.

**Comment by paullegrand** [comment]
Is there any way to get around that, other than splitting my function up into multiple smaller functions and then chaining them together?

**Comment by pmuens** [comment]
> Is there any way to get around that, other than splitting my function up into multiple smaller functions and then chaining them together?

@paullegrand AFAIK there's currently no other way. You could ask the AWS support if they increase the limit, but I'm not sure if they'll do it.

I'd still advice to use the fan-out pattern since this kind of architecture is a natural fit for such scenarios.

**Comment by manoharreddyporeddy** [comment]
Some of "Why" the "Endpoint request timed out" error occurs at all:

1. API Gateway hits Lamda, but Lamda does not load/ fails to load/ crashes at the first hit (small crashes the server running lambda), then API Gateway waits and timesout with above error

2. API Gateway hits Lamda, Lamda has a for loop that does not end at all, (possibly you are adding elements at the end of array that you are looping, etc.) then API Gateway waits and timesout with above error

**Comment by RK1987** [comment]
I have written a dummy aws function and let that sleep for 40 secs and called the same through API and lambda alone also. Lambda alone works fine. But when called through API it times out. IT is clear that API times out in 30 seconds. Lambda gives a configurable way for timeout. But need to find similar for API gateway to increase the time frame.

**Comment by HyperBrain** [comment]
@RK1987 As already referenced above, http://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-limits states that the limit cannot be increased - in the meantime it even shows 29 seconds instead of 30.

**Comment by RK1987** [comment]
Ok, then what is the benefit of able to configure the  lambda  timeout for
5 mins max, when the API gateway is not capable of waiting more than 30
secs.

**Comment by RafalWilinski** [comment]
@RK1987 Lambda can be plugged to other event emitters, e.g. SQS queue, then it's not limited to 30 secs.

**Comment by manoharreddyporeddy** [comment]
In my comment above, I did the same thing, unintentionally, some one wrote an infinite loop.

From here: http://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-limits
> Resource or Operation: Integration timeout
> Default Limit: 29 seconds for all integration types, including Lambda, Lambda proxy, HTTP, HTTP proxy, and AWS integrations.
> Can Be Increased: No

That means, you cannot increase that timeout.

The lambda can run for 5 minutes
but this can't be through the apigateway,
it can be done using events, for example, you can use automated schedule using CloudWatch Event
This means, you dont require to hit via a URL (apigateway is not needed), just have a scheduler via CloudWatch Event

Hope that helps.

**Comment by RK1987** [comment]
In our application, we have defined in such a way that, all data fetching is done via lambda and APIs are exposed for them,those APIs will be consumed in the UI . So some of the lambda execution takes more time(than 29secs) and UI API request ends with request timeout, finally no data to show in the UI. Not sure whether all the lambda that we have created can be reduced with in 29 secs. :(

**Comment by RafalWilinski** [comment]
@RK1987 You can try using AWS X-Ray to debug your Lambdas and see why it takes so much time. This might be useful: https://www.npmjs.com/package/serverless-plugin-tracing

**Comment by hjpulkki** [comment]
One thing you can try is to increase **Memory Size** in the lambda function configuration. This will also increase the processing power (and maybe even networking?), so your lambda function might be able to perform the task in the required 30 seconds. This solved my issue, at least temporarily.

I guess one way around this could also be to asynchronously send the request to another lambda function (with a 5 minute timeout) for processing. The results could then be stored to somewhere else, and fetched later from the API gateway.

**Comment by Vadorequest** [comment]
The API Gateway limit should be explained in the docs. 30 secs for lambda tops, more for SQS, etc.

**Comment by joshg111** [comment]
I think I have a workaround. Instead of using api gateway you can just use aws sdk to call `invoke()` which will invoke your lambda function. I need to test this, but I think the timeout will no longer be bounded by 29 seconds.

**Comment by manoharreddyporeddy** [comment]
@joshg111  yes, and that is what https://github.com/serverless/serverless/issues/3171#issuecomment-343473568 is confirming. We did the same, it works. Best of luck.

**Comment by kushagrasahni93** [comment]
I wonder, who decided the timeout to be 29 seconds or 30 seconds whatever, and how he decided this number?

**Comment by AmbatiramanjaneyaReddy** [comment]
i have also same problem,sending notifications to users with 1 min gap.But my request timeout and give response like your endpoint is timedout.

**Comment by jayshao** [comment]
Does anyone know if the new ALB timeout is longer? Documentation seems unclear

**Comment by dschep** [comment]
@jayshao, ALB has no timeout, so you're only limited by your lambda's timeout!

**Comment by khaledosman** [comment]
I'm having the same issue, but my code runs fine.. It only started timing out after I integrated amazon DAX as a cache for DynamoDB (to improve performance.. the irony), For this to work I had to set the VPC in the serverless.yml file to match my newly created DAX cluster.. I heard this can have high cold start times.. but now it's timing out.. Any ideas/recommendations?

**Comment by alecbw** [comment]
Adding to this thread, which looks pretty abandoned:

You can get around the 30s API Gateway limit while still exposing an endpoint by setting
`async=True` in your function's serverless.yml section. Asynchronous invocations return an API Gateway response ~immediately, and are no longer beholden to the 30s limit (instead, up to 900s Lambda limit). 

An alternate way, referenced by joshg111 above, is to use the AWS boto3 library to LambdaInvoke the Lambda you want from another Lambda. (in python, it's `from boto3 import client as boto3_client`). You can then expose a helper Lambda via API Gateway with a 30s timeout that simply invokes the Lambda you care about. You'll still need some way to return data to the caller - you can look at e.g. a queue, a db write, webhooks, etc. 

Here's a simplified version of my lambda invoke wrapper if anyone's curious:

`def invoke_lambda(param_dict, function_name, invocation_type):  
lambda_client = boto3_client('lambda')
  invoke_response = lambda_client.invoke(FunctionName=function_name,
                                         InvocationType=invocation_type, 
                                         Payload=json.dumps(param_dict))
  if invocation_type.title() == 'Event':
    return invoke_response.get("StatusCode"), None 

  elif invocation_type.title() == 'RequestResponse':
    string_response = invoke_response["Payload"].read().decode('utf-8')
    return json.loads(string_response) `


@ the serverless folks - you expose a warning in the sls deploy process (even in non-verbose) around 30s that is not disabled with async=True (e.g. `Serverless: WARNING: Function hellow-rodl has timeout of 900 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.`). Can you change that?

**Comment by Vadorequest** [comment]
@alecbw Could you provide a doc link regarding `async: true` option? Never heard of that. Thank you!

**Comment by alecbw** [comment]
https://serverless.com/framework/docs/providers/aws/events/apigateway#using-asynchronous-integration

Can confirm it works as described. Sample fxn:

```
  hello-world:
    handler: handlers/hello_world_handler.lambda_handler
    timeout: 900             
    events:
      - http:
          path: /hello_world
          method: get
          private: true
          async: true 
```

**Comment by Vadorequest** [comment]
It's a bit different than what I thought, but it's still nice to know. Thanks for the link!

It doesn't solve the timeout issue when waiting for a result, but it does help when we don't care about the return value.

**Comment by adeshp17** [comment]
I am facing similar issues where my waiter function is practically useless. lambda still times out everytime after 29 seconds no matter how much I force it to delay.

**Comment by jyotirmay123** [comment]
> @HyperBrain Ok, then what is the benefit of able to configure the lambda timeout for 5 mins max, when the API gateway is not capable of waiting more than 30 secs.

You can invoke lambdas individually without relying on API Gateway.

**Comment by kayletiu** [comment]
> https://serverless.com/framework/docs/providers/aws/events/apigateway#using-asynchronous-integration
> 
> Can confirm it works as described. Sample fxn:
> 
> ```
>   hello-world:
>     handler: handlers/hello_world_handler.lambda_handler
>     timeout: 900             
>     events:
>       - http:
>           path: /hello_world
>           method: get
>           private: true
>           async: true 
> ```

Has anyone got this to work? I'm getting a mapping expression error when putting async: true in my serverless.yml

**Comment by u-l-y** [comment]
> > https://serverless.com/framework/docs/providers/aws/events/apigateway#using-asynchronous-integration
> > Can confirm it works as described. Sample fxn:
> > ```
> >   hello-world:
> >     handler: handlers/hello_world_handler.lambda_handler
> >     timeout: 900             
> >     events:
> >       - http:
> >           path: /hello_world
> >           method: get
> >           private: true
> >           async: true 
> > ```
> 
> Has anyone got this to work? I'm getting a mapping expression error when putting async: true in my serverless.yml

Yes, it works, I guess you have something else going on in your code

**Comment by berabulut** [comment]
My function was working offline but was time outing online. Adding this to handler fixed my problem.

`context.callbackWaitsForEmptyEventLoop = false;`

**Comment by boratanrikulu** [comment]
I've just implemented a way to handle this situation.  
You can use it as plug-n-play to increase timeout limit.
Here: [AWS API Gateway Timeout Increaser][1]

  [1]: https://github.com/zeoagency/aws-api-gateway-timeout-increaser

**Comment by Ang3** [comment]
We can do this manually on API gateway: https://aws.amazon.com/about-aws/whats-new/2017/11/customize-integration-timeouts-in-amazon-api-gateway/?nc1=h_ls
Unfortunatly, I didn't found a way to configure this timeout with serverless.

Hope it will help.

**Comment by zeke-john** [comment]
Are there any updates on this?

**Comment by pgrzesik** [comment]
Nope @zeke-john - that's a hard limitation of API Gateway. You might consider using Lambda URLs which do not have this limitation or architecting your use case in a more asynchronous way.

**Comment by nezort11** [comment]
> Nope @zeke-john - that's a hard limitation of API Gateway. You might consider using Lambda URLs which do not have this limitation or architecting your use case in a more asynchronous way.

Right, replacing API Gateway with Lambda Function URLs  will solve the issue https://www.serverless.com/blog/aws-lambda-function-urls-with-serverless-framework
