### ISSUE TITLE
CloudWatch logs are not created in 1.6

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#3174]
# This is a Bug Report

## Description

When I deploy my service, the logs are not created. I think it is because of this piece of code: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/mergeIamTemplates.js#L18-L27 which in my case prematurely terminate the function on line 27 because of the if conditional on line 19 - I have defined custom role for lambda functions (i.e. I have `provider.role` in my serverless.yml, see https://github.com/keboola/developer-portal/blob/master/serverless.yml#L35). Why is there this code? I don't really understand it's reason.

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.0
* ***Operating System***: macOS 12.12
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by eahefnawy** [comment]
@JakubMatejka thanks for reporting. You're right, I think this is a bug. This is a legacy line from when we were handling logging implicitly before. But should be changed. I'll look into it asap

**Comment by eahefnawy** [comment]
@JakubMatejka I just fixed this in PR #3213 ... Could you try it out and let me know if it solves your issue so we can include it in the next release next week?

**Comment by JakubMatejka** [comment]
@eahefnawy Works well for me, thank you. 

Ooh no, but I just exceeded CF limit on resources count. ;o/ But it's not problem of this issue, of course. ;o)
