### ISSUE TITLE
Passing around a team fails to deploy

### ISSUE THREAD

**Issue by kevindiamond** [serverless/serverless#3177]
We have a large team that is just starting to work on using Serverless for deployments.

We seem to run into an issue where if someone has deployed once, the next person to try and deploy to the same place always fails. All teammembers have the same rights on the AWS Account and are attempting to deploy to the same AWS Account and Region.

We end up having to go in and manual clear things out for someone else to work on it.

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.0
* ***Operating System***: Mac OS X
* ***Stack Trace***:
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (3.86 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - locations-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLocationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLocationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLocationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ReadLocationLogGroup
CloudFormation - UPDATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodLocationOptions
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - CreateLocationLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - UpdateLocationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLocationLogGroup
CloudFormation - UPDATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodLocationSlugVarOptions
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - DeleteLocationLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - ReadLocationLogGroup
CloudFormation - UPDATE_FAILED - AWS::ApiGateway::Method - ApiGatewayMethodLocationOptions
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - ListLocationLogGroup
CloudFormation - UPDATE_FAILED - AWS::ApiGateway::Method - ApiGatewayMethodLocationSlugVarOptions
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - locations-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodLocationOptions
CloudFormation - UPDATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodLocationSlugVarOptions
CloudFormation - UPDATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodLocationSlugVarOptions
CloudFormation - UPDATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodLocationOptions
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - locations-dev
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteLocationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdateLocationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ListLocationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ReadLocationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateLocationLogGroup
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - locations-dev
Serverless: Deployment failed!

* ***Provider Error messages***:
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: CreateLocationLogGroup
     - /aws/lambda/locations-dev-createLocation already exists.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.1.1
     Serverless Version: 1.6.0

**Comment by jpicornell** [comment]
The same problem is happening to me. It seems it's something of the last sls versions. The problem happened on a windows. I'm configuring to work on the same project at a windows machine. 

After installing the serverless version 1.5.1 on the windows machine it works as it should be, so it seems is a bug introduced somwhere in between 1.5.1 and 1.6.1.

Please don't hesitate on asking for any aditional information or any aditional test I can run on my machine.

Thank you,

**Comment by pmuens** [comment]
Thanks for reporting @kevindiamond and @jpicornell 👍 

That's really bad. So it seems like it has something todo with the log groups. We've changed the way logGroups are created in 1.6 can you confirm that you've removed the old log groups after migrating from 1.5 to 1.6?

Here's the link to the CHANGELOG: https://github.com/serverless/serverless/blob/master/CHANGELOG.md#cloudwatch-logs-are-created-explicitly

Otherwise that might be the problem.

**Comment by kevindiamond** [comment]
I confirmed that after deleting manually the log groups and doing it again things worked. So it definitely was related to the breaking change in 1.6.

**Comment by degroote22** [comment]
I could reproduce the issue aswell.
It works on 1.5.1 and it doesn't work on 1.6.1.

**Comment by pmuens** [comment]
Yes, the solution to this problem is to remove the old log groups and then re-deploy. After that everything should be working smoothly. Sorry for the inconveniences...

**Comment by RPDeshaies** [comment]
@pmuens I'm experiencing this issue right now on `v1.26.1`.

When I deploy to `--stage dev` it works

But if I try to deploy to `--stage stage` it breaks.

If I try to re-deploy to `--stage dev` it works again

If I delete the old log group, it will get recreated again and I'm gonna the same issue, no ?

**Comment by RPDeshaies** [comment]
BTW I've always been on `v1.26.1` so, has this issue happened again ?
