### ISSUE TITLE
Access array elements in external files

### ISSUE THREAD

**Issue by paulSambolin** [serverless/serverless#3179]
# This is a Feature Proposal
It might also just be my lack of understanding of yaml and other tech
## Description
Importing a file like so grabs the entire json object:
```yaml
custom: ${file(./jsonObject.txt)}
```

Accessing a property of the json object works as described in the docs:
```yaml
${self:custom.prop}
# returns the value of prop, if prop is an array, returns the array
```

but fails when prop is an array and I attempt to access an element
```yaml
${self:custom.prop[0]}
# return the string '${self:custom.prop[0]}'
```

**Comment by pmuens** [comment]
Closing since this issue is quite old and we've updated our Serverless Variables system a lot in the past.

Feel free to re-open if this is still a problem.
