### ISSUE TITLE
Cloudwatch log files exist but empty when VPC configured

### ISSUE THREAD

**Issue by nford** [serverless/serverless#3181]
# This is a Bug Report

## Description

When I add a VPC configuration to the provider, my CloudWatch logs are created but contain no events. I verified by removing the CPV configuration to check and it's definitely related. 

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-2
  profile: default
  vpc:
    securityGroupIds:
      - sg-whatever # security group exists
    subnetIds:
      - subnet-whatever # private subnet exists
...

## Additional Data

* ***Serverless Framework Version you're using***:
1.6.0
* ***Operating System***:
Mac 10.2
* ***Stack Trace***:
None
* ***Provider Error messages***:
None

**Comment by konstantinvlasenko** [comment]
@nford By default your resources (EC2 instances, Lambdas) inside a private subnet  do not have access to internet. CloudWatch is required Internet Access service for your subnet. For them to be able to write into CloudWatch - your need to configure NAT gateway inside your public network.
https://aws.amazon.com/blogs/aws/new-access-resources-in-a-vpc-from-your-lambda-functions/

**Comment by nford** [comment]
Well, the reason I opened the issue is that I actually _had_ already created the NAT gateway (though manually, not through the serverless.yml), which enabled log groups to be created, but not the events. I gave up for the evening and the next day tried the deploy again and the log events were being written. Not sure what happened there!
