### ISSUE TITLE
Can't use ${region} or ${accountId} in serverless.yml

### ISSUE THREAD

**Issue by dannycohn** [serverless/serverless#3185]
# This is a Bug Report

## Description

When trying to reference the ${accountId} and ${region} variables in my serverless.yml, I get the following error message:

```
Invalid variable reference syntax for variable region.
You can only reference env vars, options, & files. You
can check our docs for more info.
```

I assumed that you could use them because of the documentation found [here](https://serverless.com/framework/docs/providers/aws/guide/iam/#one-custom-iam-role-for-all-functions)

My serverless.yml file:

```
service: test
provider:
  name: aws
  runtime: nodejs4.3
resources:
  Resources:
    MyRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: cloudWatchLogging
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource:
                  - arn:aws:logs:${region}:${accountId}:log-group:/aws/lambda/*:*:*
functions:
  hello:
    handler: handler.hello
```

## Additional Data

* ***Serverless Framework Version you're using***:
1.6.1
* ***Operating System***:
MacOS
* ***Stack Trace***:
```
  Serverless Error ---------------------------------------
 
     Invalid variable reference syntax for variable region.
     You can only reference env vars, options, & files. You
     can check our docs for more info.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.6.0
     Serverless Version: 1.6.1
```

**Comment by dannycohn** [comment]
@mnehinger  @aottenwess

**Comment by pmuens** [comment]
Thanks for reporting @dannycohn 👍 

That seems to be an error in the docs, since the variable syntax is slightly different --> https://serverless.com/framework/docs/providers/aws/guide/variables/

So you could e.g. use a gitignored file to store and read from those variables or read them with the help of a JavaScript function.

**Comment by dannycohn** [comment]
So accountid isn't available automatically? I'd rather not have to load it from a file and instead have serverless resolve it when it creates the stack template, so that my  code isn't account-specific

**Comment by andymac4182** [comment]
@dannycohn I believe these are the variables you are attempting to use http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

**Comment by dannycohn** [comment]
I was able to use the pseudo-parameters to accomplish what I needed. Thanks @andymac4182. I wont close this issue because I know you want to track the need to update the docs.

**Comment by pungoyal** [comment]
In case someone else comes hunting until the docs are updated: use `${!Ref AWS::AccountId}` in your `serverless.yml`

**Comment by HyperBrain** [comment]
@pungoyal You can use it like this:
```
     Resources:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'log-group:/aws/lambda/*:*:*'
```

**Comment by samjeffress** [comment]
There's a plugin that gives this functionality too that I'm using - https://www.npmjs.com/package/serverless-pseudo-parameters. I found it pretty handy and meant I didn't have to use the cloudformation syntax directly

**Comment by lems3** [comment]
Adding a comment because it seems some part of the doc have not been updated on the bottom of the page.
https://serverless.com/framework/docs/providers/aws/guide/iam/

**Comment by pmuens** [comment]
> Adding a comment because it seems some part of the doc have not been updated on the bottom of the page.

Thanks for bringing this up @lems3 👍

Could you open up a PR with the necessary changes (since you brought this up and it's your contribution) or should we update the docs accordingly?

**Comment by lems3** [comment]
Done. Sorry for the delay, I never submitted PR on projects outside of mine.

**Comment by pmuens** [comment]
> Done. Sorry for the delay, I never submitted PR on projects outside of mine.

No worries! Thanks for takin the time to PR the change @lems3 👍
