### ISSUE TITLE
Use Fn::ImportValue for deploymentBucket property

### ISSUE THREAD

**Issue by konstantinvlasenko** [serverless/serverless#3188]
# This is a  Feature Proposal

## Description

It is nice that we have now the option to specify a serverless **deploymentBucket** property. This helps you to control which AWS S3 Bucket serverless will use for functions zip artifacts. This works nice as long as you have a predictable  **deploymentBucket** name. In our case we create this  **deploymentBucket** by using different CloudFormation template and we treet it as a cattle and not a pet. So we don't named it. Hardcoded string inside a serverless.yml doesn't work for us.

For feature proposals:
* Ability to specify a **deploymentBucket** property by using the intrinsic function [Fn::ImportValue](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html)

* We do have right now an implementation of generic **resolveExportValue** function for awsProvider.js. And we are using it in configureStack.js

**Comment by konstantinvlasenko** [comment]
Hi @pmuens , finally my (PR)[https://github.com/serverless/serverless/pull/3189] passed all the checks.
I think I covered all the possible success and failure scenarios. There are: + 4 tests for AwsProvider#resolveExportValue()  and + 1 test for #configureStack

**Comment by konstantinvlasenko** [comment]
Plus one more change (test provided) https://travis-ci.org/serverless/serverless/builds/198463893
This to ensure that we are resolving bucket name correctly while **sls remove**

**Comment by hatch** [comment]
Why is this closed? I'm still unable to set the deploymentBucket property by using the intrinsic function Fn::ImportValue. This being broken adds a lot of complexity and mental overhead because I can't use the functions that work everywhere else on this field of serverless.yml.
