### ISSUE TITLE
Cognito User Pool Authorizer does not return CORS header Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by rsshilli** [serverless/serverless#3191]
# This is a Bug Report

## Description
I'm using the Cognito user pool authorizer support (#2141) and it works great except for this bug.  Thank you @johnf.  I also just want to say that I'm not entirely sure this bug is something in serverless as opposed to in Amazon's Cognito authorizer.  I'm using the lambda-proxy integration.

* What went wrong?
When I login the next morning and my user token has expired, the 401 HTTP code that's returned from the Cognito authorizer doesn't have the Access-Control-Allow-Origin HTTP header.  That means that I see the following in my browser console:

        XMLHttpRequest cannot load https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/myproject/projects/list. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://cherrycirclesoftware.com' is therefore not allowed access. The response had HTTP status code 401.

That means that my javascript can't know to redirect back to my login page to ask them to login again.

For bug reports:

* What did you expect should have happened?

I expected the response to have an 'Access-Control-Allow-Origin: *" header 

* What was the config you used?

Here's the excerpt from my serverless.yml file:

    projects_list:
      handler: projects/projects_handler.list
      events:
        - http:
            path: projects/list
            method: get
            authorizer:
              arn: arn:aws:cognito-idp:us-east-1:201111111111:userpool/us-east-1_GfXXXXXXX
          cors: true

* What stacktrace or error message from your provider did you see?

The response in chrome's network panel is:

    {"message":"Identity token has expired"}

But my javascript function doesn't receive that.  It receives a failure with the following JSON:

    {"readyState":0,"status":0,"statusText":"error"}

Similar or dependent issues:
* #2141

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.1
* ***Operating System***: Windows 10

**Comment by johnf** [comment]
@rsshilli Is that your exact YAML? the ```cors``` line isn't lined up right. It should line up with ```authorizer```. So I don't think CORS is being applied in this case. When you go into the console does your resource have an OPTIONS method?

**Comment by rsshilli** [comment]
Sorry about that.   I had the cors line lined up with the "authorizer:" line 2 lines above it.  Here it is correctly:

    projects_list:
      handler: projects/projects_handler.list
      events:
        - http:
            path: projects/list
            method: get
            cors: true
            authorizer:
              arn: arn:aws:cognito-idp:us-east-1:201111111111:userpool/us-east-1_GfXXXXXXX

I've tried adding the cors: true to line up with the "arn:" line too but I get the same errors.  

Also, yes, when I go into the console my resource has an OPTIONS method.  If I click on "Method Response" or "Integration Response", only 200 is defined.  I've tried to define 401 in there but the "Integration Response" won't let me and adding 401 to the "Method Response" doesn't have any effect :-(.

**Comment by rsshilli** [comment]
While we're thinking about this, it would be great if 502 errors also came back with the CORS headers.  That happens when there's an error in my Lambda function, which isn't often, but I'd like to be able to display a proper "Call support" kind of error for that.

**Comment by johnf** [comment]
@rsshilli Can you add ```integration: lambda```  between ```method``` and ```cors``` and seeif the problem goes away?

I have a feeling this issue has nothing to do with the cognito authirizer but is related to the lamba proxy integration

**Comment by johnf** [comment]
https://devstufftoremember.wordpress.com/2016/10/26/cors-api-gateway-lambda-proxy/ seems to confirm

But irrespective of that, it looks like their still is an issue with the authorisation. It seems to happen before any of the API gateway config is hit, which means it won't ever contain any origin headers.

@rsshilli So in particular with cognito, my approach to this is to never hit the API without having confirmed I have valid cognito credentials. For example

``` javascript
import { CognitoUserPool } from 'amazon-cognito-identity-js';

const poolData = {
  UserPoolId: 'us-east-1_Gxxxxx',
  ClientId: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
};

const userPool = new CognitoUserPool(poolData);

export const getSession = () => new Promise((resolve) => {
  const cognitoUser = userPool.getCurrentUser();
  
  if (cognitoUser == null) {
    return resolve(null);
  }
  
  return cognitoUser.getSession((err, session) => {
    if (err) {
      return resolve(null);
    }

    return resolve(session); 
  });
});


export const isValidSession = () => {
  const sessionPromise = getSession().then((session) => {
    if (!session) {
      return false;
    }

    return session.isValid(); 
  });
  
  return sessionPromise;
};  

const loggedIn = await cognito.isValidSession();

if (!loggedIn) {
    window.location.href = '/login'
};
```

**Comment by pmuens** [comment]
Hey @rsshilli / @johnf thanks for working on a solution to fix the problem 👍 

I'll close this issue for now since the initial problem was resolved. Feel free to continue the discussion and re-open if you need anything else.

**Comment by pmuens** [comment]
Whoops. That was too early.

Reopening after reading carefully through the whole thread.

@rsshilli does you function where you use `cors` return the correct headers? You need to return them via code if you use the integration `lambda-proxy` (which is the default one) https://serverless.com/framework/docs/providers/aws/events/apigateway/

Otherwise you can use the `integration: lambda` like @johnf mentioned. This way you don't need to set them via code (Serverless will take care of that).

**Comment by rsshilli** [comment]
Wow, thanks for the quick responses guys.  I really appreciate it.

@johnf Adding `integration: lambda` had no effect, surprisingly.  I like your work around for checking to see if the session is valid.  I was hoping to not need the cognito JS on every page but I guess there's no way around that. It's not that big of a deal, really.

@pmuens Yes, when called normally my lambda function returns all the proper headers.  It works great as along as the user has a valid session (ie. Cognito doesn't get in the way before my lambda is called).

**Comment by rsshilli** [comment]
I'm starting to think this is Amazon's bug?  If the headers come from their code, don't they need to set them? I can't think of any security issues around telling the world that this person can't login.

**Comment by johnf** [comment]
I think there are two key issues here.

Firstly, lambda-proxy doesn't return CORS headers for you, you have to explicitly set them in your lambda function.

Secondly, the Cognito Authorizer and probably the others as well, seem to run early on in the API gateway process. i.e somehting before any of the API gateway stuff is returning the 403/401. This means that you have no hope of getting CORS headers with lambda-proxy as it never hits your code and I don't think you get any headers with plain lambda either since I doubt you get to the integration response of API gateway if you haven't hit the event path.

Anyone want to rise this as a bug with AWS? Otherwise I can do so in the next few days.

**Comment by rsshilli** [comment]
Well, I submitted it, but I suspect they'll ignore it since I'm on the Basic Support plan.  It's Case ID 2081980611.

**Comment by rsshilli** [comment]
@pmuens  Can you please re-open this issue?  It's not solved (yet).  I don't seem to have access to re-open it.

**Comment by pmuens** [comment]
Sure @rsshilli ! Re-opening as it's not resolved yet...

**Comment by rsshilli** [comment]
OK.  I've figured out this is a known issue with the AWS API Gateway:

https://forums.aws.amazon.com/thread.jspa?messageID=764127&#764127

I guess there's not much we can do about it until they fix it.  In the meantime I recommend that we pile on to that issue and ask for a fix.

**Comment by pmuens** [comment]
Thanks for the update @rsshilli 👍 

I'll close this issue for now as it's not solvable by the Serverless team. Everyone who reads this: Please read through and respond to the forum thread linked by @rsshilli above 🔝

**Comment by ratbeard** [comment]
Looks like aws just added this: https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-api-gateway-enables-customization-of-error-responses/ 💃

**Comment by manV** [comment]
@ratbeard If you have solved this issue, can you please comment how did you do it? Lambda-proxy doesn't support response templates, it seems there is no way to achive this.

**Comment by pmuens** [comment]
Hey @manV thanks for your comment and opening up the separate issue to track that 👍!

Just wanted to leave a reference to the issue by @manV here so that others who stumble upon this issue can find it: https://github.com/serverless/serverless/issues/3896.

**Comment by lyndon-howie** [comment]
I can confirm that manually configuring the API Gateway Responses as mentioned above by @ratbeard and @manV works to return the correct access control headers (I modified the "Unauthorized [401]" which worked for expired or missing/invalid token, but there may be other cases?).
It doesn't appear to be supported in cloud formation yet, but it can be modified via the API Gateway REST API...perhaps that's an option?

**Comment by pmuens** [comment]
Hey @lyndon-howie thanks for commenting and thanks for looking into solutions for this 👍 

> It doesn't appear to be supported in cloud formation yet, but it can be modified via the API Gateway REST API...perhaps that's an option?
> Should this issue be re-opened now that it's possible to be fixed?

Currently we're focused on solutions around CloudFormation since it allows us to deploy, update and remove stacks in a consistent way. Mixing this with other API methods could result in inconsistencies if e.g. the deployment fails whereas the other API call succeeded.

We should definitely re-open this issue once AWS added support for this via CloudFormation.

**Comment by vamcs** [comment]
Are there any updates on this?

Thanks for the solution, by the way! It would be nice avoiding having to set this header manually in the console though.

**Comment by rsshilli** [comment]
You don't need to set the header manually through the console any more.  I solved this problem by putting my custom API Gateway headers in its own CF file.  Then I delete that stack, run serverless to update my Lambdas, and then reapply the that stack to add the right things back to API Gateway.  This system has been running pretty flawlessly for us for about a year.

**Comment by jeremywhittington** [comment]
> You don't need to set the header manually through the console any more. I solved this problem by putting my custom API Gateway headers in its own CF file. Then I delete that stack, run serverless to update my Lambdas, and then reapply the that stack to add the right things back to API Gateway. This system has been running pretty flawlessly for us for about a year.

Could you explain how you would do this? I am running into this error now.

**Comment by vamcs** [comment]
> > You don't need to set the header manually through the console any more. I solved this problem by putting my custom API Gateway headers in its own CF file. Then I delete that stack, run serverless to update my Lambdas, and then reapply the that stack to add the right things back to API Gateway. This system has been running pretty flawlessly for us for about a year.
> 
> Could you explain how you would do this? I am running into this error now.

There's an example in this related thread: https://github.com/serverless/serverless/issues/3896
