### ISSUE TITLE
Feature Proposal: deprecate CloudFormation in favor of direct API calls to improve dev iteration 

### ISSUE THREAD

**Issue by cove** [serverless/serverless#3194]
# This is a Feature Proposal

## Description

For feature proposals:
* I'd like to propose that sls switch from using CloudFormation to making direct AWS API calls to deploy and update AWS resources since it's faster, esp. when developing.
* The code, deploy, test cycle can be minutes between iterations due to CloudFormation. This slows down development, and I don't feel is in the spirit of serverless which is lightweight and quick. 
* CloudFormation's initial intention was to be a tool for initial setup and infrequent updates, and wasn't envisioned as being in the middle of a development iteration loop, hence performance wasn't a big factor in its design. So I don't think it's the right tool for this use case.
* You can use the sls local invoke, however that's not the same as testing with the actual AWS resources, and there are differences still (e.g. env var LAMBDA_FUNCTION_NAME wasn't set for me locally, Lambda sets it once deployed however). That could be fixed of course, however that doesn't seem like a long term sustainable model, and I believe there would always be a period of time when it's out of sync with the cloud provider after a change.
* My sense is that Apex's model of just calling the APIs directly performs well, for a hello world example a deploy is ~5 seconds for me vs. often minutes with sls.
* That's all I got :)

Similar or dependent issues:
* NA

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: Ubuntu
* ***Stack Trace***: Example of a local invoke error that doesn't happen in AWS:
```Traceback (most recent call last):
  File "/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 60, in <module>
    result = handler(event, FakeLambdaContext())
  File "./handler.py", line 61, in run
    sender = foobar('aws.{0}.{1}.'.format(STAGE,REGION))
  File "./foobar/__init__.py", line 27, in __init__
    self.source = source or os.environ["LAMBDA_FUNCTION_NAME"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__

    raise KeyError(key)
KeyError: 'LAMBDA_FUNCTION_NAME'
```
* ***Provider Error messages***: NA

**Comment by konstantinvlasenko** [comment]
I don't like this proposal. We are using sls deploy --noDeploy to generate artifacts and templates. And then our AWS CodePipeline uses them as part of CI/CD. Locally you can use **sls deploy function** to spedup your process. It uses exactly what you need - direct API calls w/o CloudFormation.

**Comment by cove** [comment]
@konstantinvlasenko I didn't realize CloudFormation was linked into other workflows. Looks like sls deploy function is faster, but having two deployment modes with the same command seems error prone to me, and it's not documented in the utility output. Maybe there's a story on the command line interface commands to make the mode clearer. Hum.

**Comment by konstantinvlasenko** [comment]
Just for reference https://serverless.com/framework/docs/providers/aws/guide/deploying#deploy-function

**Comment by konstantinvlasenko** [comment]
@cove Yes. We are using serverless for big application which contains a lot of serverless apps in it. We do have CI/CD automated by using Code Pipeline, CloudFormation, CodeBuild. W/o this feature we are doomed :)

**Comment by cove** [comment]
@konstantinvlasenko oh yeah, I checked the website after you mentioned that, but I think to avoid context switching it's better if it's in the cli tool output too. Sort of thinking that the pipeline use case there could be a different command... would be interested to know what others thoughts are.

**Comment by konstantinvlasenko** [comment]
@cove Just realized that you might package all you **npm dependencies** (including **dev**). If exclude them -> it may speedup process a bit. https://serverless.com/framework/docs/providers/aws/guide/packaging/

**Comment by konstantinvlasenko** [comment]
@cove One more suggestion. Exclude aws-sdk from packaging. It is already pre-installed in AWS Lambda environment. This actually will speedup your deployment.

**Comment by cove** [comment]
hey @konstantinvlasenko thanks for the tips here! I think that those would help however cloudformation still introduces lengthy delays. I was talking to the lambda team earlier this week and they are aware of it, since they have the same issues with [SAM](https://github.com/awslabs/serverless-application-model). It seems like if it were easy to speed up, then someone would have done it already, so maybe down the line they'll be able to make improvements. 

out of curiosity, how are you testing your changes? are you running them locally? or waiting for a deployment on every iteration?

**Comment by andymac4182** [comment]
@cove We are using `serverless-offline` and starting on https://github.com/gertjvr/serverless-docker as another test. Doing local testing gets us most of the way to a working system and do some final testing on lambda for the things we can't mock out. We use https://github.com/spulec/moto running in docker to emulate a lot of the AWS services to help as well.

**Comment by tobyhede** [comment]
I am a -1 to this, CFN means we can build a nice CD pipeline. 

@cove I've found that I don't need to deploy that frequently. The actual lambda functions are just functions that return a bunch of data, so you can isolate those. Judicious use of mocking and clear separation of concerns gets me most of the way, and then I do some integration tests against actual dynamodb tables in development. These tests are not in my main suite as the latency is higher (still in 100s of ms so not terrible).

**Comment by pmuens** [comment]
Thanks for the suggestion @cove 👍 

Right now Serverless v1 is build from the ground up to rely on CloudFormation. Currently there are no plans for v1 to move to direct SDK usage / API calls.

We'll keep this valuable feedback in mind while laying out the groundwork for the future of the framework!
