### ISSUE TITLE
Not authorized to perform: cloudformation:DescribeStackResources

### ISSUE THREAD

**Issue by EasonWang01** [serverless/serverless#3199]
# This is a (Bug Report / Feature Proposal)
not sure,maybe about config.
## Description

<img width="1128" alt="2017-02-07 11 57 27" src="https://cloud.githubusercontent.com/assets/11001914/22677324/a4bfcd8a-ed2c-11e6-87b1-e0e4a6801087.png">

I got the message like above picture,which point might missing?Thanks for reply.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by EasonWang01** [comment]
ok,the solution is need to add `AdministratorAccess` to user permission.

But not sure is it ok for production.

**Comment by sunnypatel** [comment]
Shouldn't have to give `AdministratorAccess` though right?

**Comment by pmuens** [comment]
@EasonWang01 @sunnypatel yes, `AdministratorAccess` is the best permission setup for development. 

However you might want to narrow the permissions down for production. There's an issues which discusses the potential setup here: https://github.com/serverless/serverless/issues/1439

**Comment by JimTheMan** [comment]
I am also having issues with permissions... Even after adding ""AdministratorAccess" I still get the error, `is not authorized to perform: cloudformation:DescribeStacks on resource:`

:(

**Comment by laneschmidt** [comment]
I am getting this error as well, none of the fixes seemed to work.

**Comment by natralalalia** [comment]
Any updates on this?

**Comment by jraut** [comment]
See answer in https://github.com/serverless/serverless/issues/5306

**Comment by valentinoPereira** [comment]
Even i am facing this issue after removing _CloudformationAdministrator_ access rule. But I can't understand why am I facing this error even though my user has _AWSLambdaFullAccess_ permissions in the IAM.

Following is how the _AWSLambdaFullAccess_ policy json looks like:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudformation:DescribeChangeSet",
                "cloudformation:DescribeStackResources",
                "cloudformation:DescribeStacks",
                "cloudformation:GetTemplate",
                "cloudformation:ListStackResources",
                "cloudwatch:*",
                "cognito-identity:ListIdentityPools",
                "cognito-sync:GetCognitoEvents",
                "cognito-sync:SetCognitoEvents",
                "dynamodb:*",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "events:*",
                "iam:GetPolicy",
                "iam:GetPolicyVersion",
                "iam:GetRole",
                "iam:GetRolePolicy",
                "iam:ListAttachedRolePolicies",
                "iam:ListRolePolicies",
                "iam:ListRoles",
                "iam:PassRole",
                "iot:AttachPrincipalPolicy",
                "iot:AttachThingPrincipal",
                "iot:CreateKeysAndCertificate",
                "iot:CreatePolicy",
                "iot:CreateThing",
                "iot:CreateTopicRule",
                "iot:DescribeEndpoint",
                "iot:GetTopicRule",
                "iot:ListPolicies",
                "iot:ListThings",
                "iot:ListTopicRules",
                "iot:ReplaceTopicRule",
                "kinesis:DescribeStream",
                "kinesis:ListStreams",
                "kinesis:PutRecord",
                "kms:ListAliases",
                "lambda:*",
                "logs:*",
                "s3:*",
                "sns:ListSubscriptions",
                "sns:ListSubscriptionsByTopic",
                "sns:ListTopics",
                "sns:Publish",
                "sns:Subscribe",
                "sns:Unsubscribe",
                "sqs:ListQueues",
                "sqs:SendMessage",
                "tag:GetResources",
                "xray:PutTelemetryRecords",
                "xray:PutTraceSegments"
            ],
            "Resource": "*"
        }
    ]
}
`

So as per this rule, I already have the `cloudformation:DescribeStackResources` permission. 

Serverless team please resolve this issue.

**Comment by lordcoppetti** [comment]
Like @valentinoPereira mentions.
I'm having the same issue despite testing all the above policies.
Still get `not authorized to perform: cloudformation:DescribeStacks` when having the policy added.

Even with the gist: https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8
