### ISSUE TITLE
UX Improvement: Make deploy function easier

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3204]
Can't tell you how many times I type  `sls deploy -f functionName` and forget the word function... and then have to wait for the whole stack to update.

Can we alias `sls deploy -f functionName` to `sls deploy function -f functionName` as a quick UX win?

So if a user types `sls deploy -f lolCatz` it will only deply the `lolCatz` function?

**Comment by horike37** [comment]
I always mistake the same too..
+1

**Comment by shortjared** [comment]
This could be an interesting UX win. I will say I've retrained my muscle memory around some bash aliases... `alias sdf="serverless deploy --function $1"` then I can just `sdf functionName`. Saved me some time here and there.

**Comment by pmuens** [comment]
Nice idea!

IMHO nested commands (more than one level deep) are always kind of hidden and might be something to get rid off altogether.

**Comment by iliasbhal** [comment]
+1 very nice idea
you are right ! because `sls deploy function -f functionName` is not that intuitive ...

**Comment by DavidWells** [comment]
@pmuens would this be hard to implement?

**Comment by pmuens** [comment]
> Would this be hard to implement?

AFAIK we can leverage the latest plugin enhancements (the new entrypoints added by @HyperBrain ) to implement this in a backwards compatible / non-breaking way. But I need to look into this in more depth.

**Comment by DavidWells** [comment]
Bump. Can we please get this in?

Has users at last nights meetup complain about slow deploys and are unaware of `sls deploy function` probably due to its verbosity

**Comment by DavidWells** [comment]
@pmuens @HyperBrain any blockers to getting this implemented?

Seems like a quick easy UX win.

**Comment by HyperBrain** [comment]
@DavidWells Should be an easy one from the implementation side too.

If the `deploy` plugin encounters a `--function` option, it could just `.spawn('deploy:function')` and skip the rest of the deploy plugin. That should work seamlessly.

@pmuens Should I do a PR tomorrow? My estimation for the fix is about 30-60 minutes max 😄

**Comment by pmuens** [comment]
Great! Thanks for pinging @DavidWells 👍

> If the deploy plugin encounters a --function option, it could just .spawn('deploy:function') and skip the rest of the deploy plugin. That should work seamlessly.

That sounds like a good implementation plan!

> @pmuens Should I do a PR tomorrow? My estimation for the fix is about 30-60 minutes max 😄

@HyperBrain that would be super nice! Thanks in advance!
