### ISSUE TITLE
Go language

### ISSUE THREAD

**Issue by pfeodrippe** [serverless/serverless#321]
I've seen that you can launch a Go process 
https://aws.amazon.com/lambda/faqs/?nc1=h_ls

How could I use Go in a Jaws project?

**Comment by dtimberlake** [comment]
Check out this blog post:

http://blog.0x82.com/2014/11/24/aws-lambda-functions-in-go/

**Comment by pfeodrippe** [comment]
Thanks, I've already seen this post, so I was thinking there were some elegant way to deploy it.

I'll use it, thanks again =)

**Comment by eahefnawy** [comment]
That's a super interesting hack! :+1: ... AWS made a poll on twitter a while back on the next language support for Lambda (Ruby vs Go) and the majority chose Go...so am guessing go is coming very soon ;)

**Comment by dtimberlake** [comment]
Unfortunately, there isn't a good way to deploy Go code quite yet on Lambda. However, it's encouraging that they are thinking about us Gophers -> https://twitter.com/awscloud/status/659795641204260864.

**Comment by jwulf** [comment]
@dtimberlake have you seen https://github.com/mweagle/Sparta?

**Comment by flomotlik** [comment]
We definitely want to support Go as soon as its launched on Lambda directly. I don't think we'll support Go before that though.
