### ISSUE TITLE
Problem deploying to a stage named 'test'

### ISSUE THREAD

**Issue by acbarnett** [serverless/serverless#3216]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I have written a two small lambda functions and have successfully deployed them to environments named 'dev',
'live', 'wombats', etc. using "serverless deploy -s dev"
Attempting to deploy to an environment named "test" using "serverless deploy -s test" does not successfully deploy.
* What did you expect should have happened?
A lambda function named second-serverless-build-test-getTime should have been created.
* What was the config you used?

      service: second-serverless-build

      frameworkVersion: ">=1.1.0 <2.0.0"

      provider:
        name: aws
        runtime: nodejs4.3
        region: us-west-2

        getTime:
          handler: demos/time.time
          events:
            - http:
                path: getTime
                method: get
                cors: true

        reverse:
          handler: demos/string.reverse
          events:
            - http:
                path: getReverse
                method: post
                cors: true

* What stacktrace or error message from your provider did you see?

        me@darklinear:~/project_dir$ serverless deploy --stage test
        Serverless: Packaging service...
        Serverless: Uploading CloudFormation file to S3...
        Serverless: Uploading service .zip file to S3 (182.2 KB)...
        Serverless: Updating Stack...
        Serverless: Checking Stack update progress...
        .....Serverless: Deployment failed!
         
          Serverless Error ---------------------------------------
         
             An error occurred while provisioning your stack: ReverseLambdaFunction
             - Function not found: arn:aws:lambda:us-west-2:963294089710:function:second-serverless-build-test-reverse.
         
          Get Support --------------------------------------------
             Docs:          docs.serverless.com
             Bugs:          github.com/serverless/serverless/issues
         
          Your Environment Information -----------------------------
             OS:                 linux
             Node Version:       5.2.0
             Serverless Version: 1.6.1
     

Similar or dependent issues:
???

## Additional Data

* ***Serverless Framework Version you're using***:
Serverless 1.6.1
* ***Operating System***:
Tested on Ubuntu 14.04
* ***Stack Trace***:
* See Above
* ***Provider Error messages***:
* See Above

**Comment by pmuens** [comment]
Hey @acbarnett thanks for reporting. 👍 

Can you try to disable function versioning with and re-deploy your service?

```yml
provider:
  versionFunctions: false
```

Might be related to: https://github.com/serverless/serverless/issues/3050

**Comment by pmuens** [comment]
@acbarnett have you tested it with the opt-out for function versions?

**Comment by pmuens** [comment]
Closing this for now since it's stale and we've updates Serverless in the meantime.

Let us know if you still face this issue and we'll reopen...
