### ISSUE TITLE
UX: Improve log group error

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3221]
This error is not helpful. Can we explain what is happening here and how exactly people can fix it?

`sls deploy` gave me this vague error.

```
  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: GithubWebhookListenerLogGroup
     - /aws/lambda/serverless-status-board-prod-githubWebhookListener
     already exists.
```

![image](https://cloud.githubusercontent.com/assets/532272/22796486/50dcd3b4-eeaf-11e6-98ac-7b62b6fc5b03.png)

**Comment by DavidWells** [comment]
A picture is worth a thousand words

![image](https://cloud.githubusercontent.com/assets/532272/22796671/1266d912-eeb0-11e6-84bb-71dab304b693.png)

We should explain the error and that people need to go into cloudwatch logs and manually delete them.

**Comment by pmuens** [comment]
Closing since newer version of Serverless auto-remove / manage log groups so this error shoulnd't pop up anymore...
