### ISSUE TITLE
VPC settings Cannot be assigned by variables

### ISSUE THREAD

**Issue by kevindiamond** [serverless/serverless#3223]
When using variables in the VPC definition in serverless.yml such as:

vpc:
      securityGroupIds:
        - ${self:custom.prod_sg_a}
        - ${self:custom.prod_sg_b}
      subnetIds:
        - ${self:custom.prod_subnet_a}
        - ${self:custom.prod_subnet_b}

serverless throws the following error in deployment:

Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: LambdaFunction
     - Value of property SecurityGroupIds must be of type
     List of String.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.1.1
     Serverless Version: 1.6.1

Should be able to use variables (including nested variables) to support deployment across different accounts and therefore different VPCs.

**Comment by andymac4182** [comment]
I am using variables for this but its with 1.3. Do you have your exact `serverless.yml` file? I will find the method I am using and post the example.

**Comment by kevindiamond** [comment]
Thanks! That seemed to do the trick. Must be setting the variable as a list rather than a list of variables. Or something like that. Appreciate the help!

**Comment by steezeburger** [comment]
I'm getting this same error. I only have one security group. 

I've tried both

```
provider:
  name: aws
  runtime: nodejs6.10
  vpc:
    securityGroupIds:
      — "sg-abcdefg1"
    subnetIds:
      — "subnet-abcdefg1"
      — "subnet-abcdefg2"
```

AND

```
provider:
  name: aws
  runtime: nodejs6.10
  vpc:
    securityGroupIds: "sg-abcdefg1"
    subnetIds:
      — "subnet-abcdefg1"
      — "subnet-abcdefg2"
```

Is this just a yaml thing?
