### ISSUE TITLE
no endpoint created from deploy from sample

### ISSUE THREAD

**Issue by nothingtoseeherehub** [serverless/serverless#3234]
# This is a (Bug Report / )

## Description
server deploy results in no endpoint being created from a freshly created aws ami-
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
 . ~/.nvm/nvm.sh
   nvm install 4.4.5
npm install -g serverless

serverless create --template aws-nodejs --path my-service

serverless deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (583 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........
Serverless: Stack update finished...
Service Information
service: my-service
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None  <--- should be an endpoint here, and none is displayed, nor is any created --confirmed via console
functions:
  my-service-dev-hello
[ec2-user@ip-172-31-26-163 my-service]$ 

For bug reports:
* What went wrong?
no endpoint was created
* What did you expect should have happened?
I expected an endpoint to be created 
* What was the config you used?
fresh aws ami -- steps to recreate pasted in above
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* --- similar to  https://github.com/serverless/serverless/issues/2010

## Additional Data

* ***Serverless Framework Version you're using***:

* ***Operating System***:
 uname -a
Linux ip-172-31-26-163 4.4.41-36.55.amzn1.x86_64 #1 SMP Wed Jan 18 01:03:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @nothingtoseeherehub thanks for reporting.

Could you please look into the AWS console if the API Gateway setup is available there? This way we can validate if the endpoint is not created on AWS or if it's just a displaying problem of the `info` plugin.

Furthermore you might want to run `serverless deploy -v` to get a verbose output during deployment. This will show you what will be created behind the scenes.

**Comment by nothingtoseeherehub** [comment]
I thought I indicated in the first post, there is no api gateway created in the console.  In any event.  Here is the verbose output.  This time from a aws-python generated boiler plate
[ec2-user@ip-172-31-26-163 mypyt]$ serverless create --template aws-python
Serverless: Generating boilerplate...
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.6.1
 -------'

Serverless: Successfully generated boilerplate for template: "aws-python"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name
[ec2-user@ip-172-31-26-163 mypyt]$
[modified service name here]
serverless deploy -v  [with account numbers changed]
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (639 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - aws-pworld-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersion7KjZyGXCZacXA5c84PxsPFcJVu20s2qLeZ92Svkd9os
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersion7KjZyGXCZacXA5c84PxsPFcJVu20s2qLeZ92Svkd9os
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersion7KjZyGXCZacXA5c84PxsPFcJVu20s2qLeZ92Svkd9os
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - aws-pworld-dev
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersion4CuMAEG9DtF0g1ofphk4edxhmztF8BVwvEMdhB5ldyM
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - aws-pworld-dev
Serverless: Stack update finished...
Service Information
service: aws-pworld
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  aws-pworld-dev-hello

Stack Outputs
HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:1234567890:function:aws-pworld-dev-hello:2
ServerlessDeploymentBucketName: aws-pworld-dev-serverlessdeploymentbucket-qzoff37ejyhp

[ec2-user@ip-172-31-26-163 mypyt]$ 

-- I have confirmed API does get generated when using serverless.xml from https://github.com/bni/binary-test, walking through differences from working-app with sample-generated now to determine which option(s) 'break' the generation of endpoint

**Comment by nothingtoseeherehub** [comment]
The autogenerated serverless.yml created from waking through the steps directly on the serverless.com video of   serverless create --template aws-nodejs   followed by serverless deploy  do NOT create an endpoint  because there is no 'events' entry uncommented.
for example
events:
#      - http:
#          path: users/create
#          method: get

---Manually adding the event, then the api will get generated.  Without manually adding the event, it will not. --- I'm not certain now, if this is a bug, or an intended behavior.  But if it is an intended behavior, then it means that all the 'flashy introduction' videos for serverless.com need to be rewritten, because they can no longer be replicated by newcomers to the project without manual intervention [and knowledge that newcomers won't yet have]

**Comment by pmuens** [comment]
@nothingtoseeherehub thanks for getting back.

Not having a HTTP endpoint by default is an intended behavior.

The video out there are quite outdated. Thanks for pointing us in that direction. We'll look into it.

**Comment by AndrewVu0203** [comment]
I only have 3 endpoints created, the PUT DELETE endpoints and functions prod-update, prod-delete is not showing up on my Terminal.

**Comment by nbsbhat** [comment]
good info @nothingtoseeherehub 👍
