### ISSUE TITLE
obj must be an Array or an Object

### ISSUE THREAD

**Issue by zeta-o** [serverless/serverless#3235]
Hi Guys, I'm newbie in serverless. Follow the tutorial trying to create a service, I created first the folder and created a serverless.yml file too. After that I tried to run **serverless create --template aws-python --path PythonLambda** but the CLI showed me the message:

Type Error ---------------------------------------------

     obj must be an Array or an Object

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.5.0
     Serverless Version: 1.6.1

Regards and thanks for your wonderful work!

**Comment by pmuens** [comment]
Hey @zeta-o thanks for reporting. Could you enable stack traces with the help of environment variables `export SLS_DEBUG=*` (on UNIX machines) so that we can see the exact stack trace?

Thanks 👍

**Comment by pmuens** [comment]
Any update on this one @zeta-o ?

**Comment by Ascendzor** [comment]
Hello, I removed my `serverless.yml` and then it all started working.

Hope that helps!

**Comment by pmuens** [comment]
Closing this one since it's stale and @Ascendzor provided a possible fix for it.

Let us know fi you still face this issue and we'll reopen...

**Comment by gDelgado14** [comment]
How is removing `serverless.yml` a fix if a serverless project requires a `serverless.yml` file to exist?

**Comment by pmuens** [comment]
I think the problem was that @zeta-o created a `serverless.yml` file manually and then created a template with the `create` command.

Seems like this caused the error since a `serverless.yml` file was already presetn.
