### ISSUE TITLE
Allow support for authentication types in HTTP endpoints (e.g. for AWS Cognito and IAM)

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#3238]
## Problem
Currently the HTTP event definitions imply authentication type *NONE* for AWS endpoints with the possibility to attach custom authorizers as authentication/authorization mechanism only.
If you're using AWS Cognito, AWS IAM or a combination of both to authorize users, you have to have the endpoints protected by AWS V4 signatures. Technically this has to be done by setting the AuthorizationType parameter to *AWS_IAM*.
Not only the default is set to *NONE* in the current implementation, but also it is only possible to change the authorization type by overriding it in a separate CF resources definition which implies that you have to specify the SLS auto-generated endpoint method id. This is not practical.

## Possible solution
Add support for an `AuthorizationType` property to the events.http definition which can be set to the allowed AWS authorization type values, e.g. NONE, AWS_IAM, ...
There should be also some sanity checking, e.g. any given value should be ignored or a warning should be shown, if you combine a custom authorizer with anything other than NONE.

**Comment by hassankhan** [comment]
Any progress on this? Would be lovely to have this working without having to manually specify for each resource

**Comment by arabold** [comment]
Also see #3518
