### ISSUE TITLE
Is there an IRC/Gitter/chat channel for JAWS/Serverless?

### ISSUE THREAD

**Issue by LukeSwart** [serverless/serverless#324]
I tried `#jaws` and `#serverless` on Freenode, but I found empty rooms. I also tried searching "jaws" and "serverless" on Gitter's explore menu, but I still get nothing. It seems like there is a vibrant community for this project, but where is it?

Basically, I am referring to [the docs](https://serverless.readme.io/docs/configuring-aws), but I have a few questions/feedback. If there is no channel, should I take these questions to `#npm` instead?

**Comment by joostfarla** [comment]
Hi @LukeSwart!

There is a Gitter channel here: https://gitter.im/serverless/serverless

As far as I know there is no IRC channel.

**Comment by LukeSwart** [comment]
Great, thanks!

Closing this issue.
