### ISSUE TITLE
[Feature-Request] Undo everything created in serverless.yml file

### ISSUE THREAD

**Issue by QuantumInformation** [serverless/serverless#3241]
Sometimes you  configure the settings incorrectly and you create a bunch of arn's on AWS. Would be nice to be able to roll back everything from a yml file.

**Comment by QuantumInformation** [comment]
Could it be as simple as smth like: `aws cloudformation delete-stack --stack-name my-project` ?

**Comment by QuantumInformation** [comment]
I tried `aws cloudformation delete-stack --stack-name quantumjs-dev --region us-west-2`, but it left my Lambda functions intact.

**Comment by laardee** [comment]
Hi @QuantumInformation, did you already try with `sls remove`?

**Comment by QuantumInformation** [comment]
wow, that does it!
