### ISSUE TITLE
[example request] A series on an app with user login/reg flow

### ISSUE THREAD

**Issue by QuantumInformation** [serverless/serverless#3242]
Building on scope videos on YouTube, I think it would be great for a series on how to make a full app with user login/reg flow with AWS Cognito. This would be the silver bullet for me using serverless for just about everything.

**Comment by laardee** [comment]
@QuantumInformation, Hi, I've prepared authentication example service that uses OAuth, https://github.com/laardee/serverless-authentication-boilerplate, but if you need to use Cognito for login this example won't help you. I'm working on Cognito Federated Identities implementation, but it's not ready yet. If you only need to log in with e.g. Google credential and save user info to DB or Cognito User Pool you may find some tips.

**Comment by QuantumInformation** [comment]
Thanks for this, I will defo be looking at it!

**Comment by pmuens** [comment]
Hey @QuantumInformation thanks for opening and @laardee for proposing the `authentication` boilerplate. 👍 

We've moved all our examples to the examples repository:

https://github.com/serverless/examples

It would be nice to open up an issue there so that we have everything in the examples repo.

**Comment by QuantumInformation** [comment]
Roger that!

**Comment by QuantumInformation** [comment]
@laardee looking fwd to hear if Cognito is used in any example of auth, as I would like to keep my whole stack in AWS.
