### ISSUE TITLE
Cannot read property 'stage' of undefined

### ISSUE THREAD

**Issue by BoomTown** [serverless/serverless#3245]
https://github.com/serverless/serverless/compare/v1.6.1...v1.7.0#diff-271ef5d492727880dcac1b94a86c878dL218

perhaps caused an issue.   ?   serverless deploy -v  now gives me error

    Cannot read property 'stage' of undefined

**Comment by pmuens** [comment]
Hey @BoomTown thanks for reporting!

Could you please point to the commit you think broke it? The link you posted points to the comparison of `v1.6.1` and `v1.7.0`.

Thanks! 👍

**Comment by pmuens** [comment]
Is this still a problem @BoomTown ?

Could you please provide steps on how to reproduce it? Thanks!

**Comment by pmuens** [comment]
Closing this one since it's stale and we've updated Serverless in the meantime.

Let us know if this is still an issue and we'll reopen...
