### ISSUE TITLE
Error: spawn java ENOENT

### ISSUE THREAD

**Issue by chrisbennettdev** [serverless/serverless#3247]
# This is a (Bug Report)

## Description
  Everytime I try to start serverless using the below command I get the same error. My JDK is updated to 1.8 and JAVA_HOME is set to that. I can't figure out how to fix this issue?

For bug reports:
* What went wrong?
Trying to run this command: sls dynamodb start --stage local -P 8001

* What did you expect should have happened?
local dynamodb to start running

* What was the config you used?
* What stacktrace or error message from your provider did you see?

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.7

* ***Operating System***:
macOS Sierra

* ***Stack Trace***:

Error: spawn java ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

* ***Provider Error messages***:
events.js:160
      throw er; // Unhandled 'error' event
      ^

**Comment by darthtrevino** [comment]
Have you tried running `sls dynamodb install`? This downloads the DynamoDb libs you need.

**Comment by tvilot** [comment]
`sls dynamodb install` solved this issue for me. Thanks!

**Comment by SeunLanLege** [comment]
I have this same issue,

i'm on a mac, my java_home path is set and i've run `sls dynamodb install`

still getting this error

**Comment by kalote** [comment]
Same here in a docker environment (circleCI)

**Comment by ozbillwang** [comment]
I fixed this to install java in alpine image:

    apk --update add openjdk7-jre

But still can't start the dynamodb-local and serverless-offline in container. 

@kalote 

Did you try to start local dynamodb and serverless offline in container successfully?

**Comment by kalote** [comment]
Hey @ozbillwang ,

Yes, i've been able to do it successfully => https://github.com/kalote/circleci-node8-sls-jre

You can use this image in your circleCI build, or you can also get it from hub.docker, use it as a base image, and install your app with it.

I've been able to start local dynamodb + serverless offline with it.

Ping me if you need more information.

**Comment by ozbillwang** [comment]
Thanks, @kalote  👍 

I used your image and successfully start local dynamodb and serverless offline in the container. Furtherly, I add features to build and push the new `image:tag` with latest serverless release. 

```
$ docker run --rm -it -v $(pwd):/opt/app -v ~/.aws:/root/.aws -v ~/.ssh:/root/.ssh svls/serverless:1.24.1 bash
bash-4.3# sls plugin install -n serverless-dynamodb-local
bash-4.3# sls plugin install -n serverless-offline
bash-4.3# sls dynamodb install
bash-4.3# sls offline start -r us-east-2 --noTimeout --corsDisallowCredentials false &
bash-4.3# npm run test
```

https://github.com/serverless-lambda/docker-serverless

**Comment by kalote** [comment]
@ozbillwang for running test locally with sls offline, I use:

```bash
bash# sls offline start --exec "npm run test"
```

Which method do you think it's better?

**Comment by stnmtz** [comment]
Got the same error, and fixed it: I forgot to install Java ;)
Fetch JDK from http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html , install it and don't forget to restart your cmd on Windows.

**Comment by juvaly** [comment]
I'm encountering the same error on Windows, both from Powershell and Ubuntu bash.

`sls dynamodb install` finished successfully, but that did not solve the problem.

On windows I have JRE installed:
```
>java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

On ubuntu I have OpenJDK v1.8.0 installed:
```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode
```

**Comment by baleksandr48** [comment]
`sudo apt install default-jdk` helped me for ubuntu. (user `sudo apt install default-jre` for mint)
