### ISSUE TITLE
Add autocompletion to CLI

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3248]
# This is a Feature Proposal

## Description

**Brought up by @DavidWells**

This is table stakes for a pleasant CLI experience.

It should be rather quick to implement and would be very nice UX win and something to promote.

There are 2 parts:

Command name autocompletion
Partial command matching (nice to have but do second)

## 1. Command name autocompletion

Here is a package to help https://www.npmjs.com/package/omelette. The `p-s` package uses this and it's amazing https://github.com/kentcdodds/p-s#global-installation

**Examples:**

```
sls d[TAB] 
# autocompletes `sls deploy`
```

```
sls deploy f[TAB] 
# autocompletes `sls deploy function -f`
```

```
sls deploy function -f he[TAB] 
# autocompletes `sls deploy function -f hello`
```

## 2. Partial command matching (optional but nice)

Automatically resolve partial matching commands for a super fast CLI experience.

Using something like https://www.npmjs.com/package/prefix-matches. Also used by `p-s` CLI tool by Kent https://github.com/kentcdodds/p-s/blob/master/package.json#L33

**Examples:**

`sls d[ENTER]` will resolve to `sls deploy`

`sls deploy f -f hello[ENTER]` will resolve to `sls deploy function -f hello`

**Leave `sls remove` alone**, we don't want people accidentally tearing down stacks

---

Similar or dependent issues:
#187

**Comment by DavidWells** [comment]
great minds think alike! https://github.com/serverless/serverless/issues/3254

**Comment by pmuens** [comment]
😄 👍
