### ISSUE TITLE
deploy error: "ENFILE: file table overflow"

### ISSUE THREAD

**Issue by robbiehanson** [serverless/serverless#3253]
# This is a Bug Report

## Description

Serverless v1.7.0 fails to deploy my project with the following error:
```
Serverless: Packaging service...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '/Users/robbie/Programs/4thA/server/serverless/node_modules/lodash/README.md'
    at Error (native)
```

The specific file it crashes on changes just about everytime I try to deploy. E.g. if I run it again it might say:
```
Serverless: Packaging service...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '/Users/robbie/Programs/4thA/server/serverless/node_modules/lodash/partial.js'
    at Error (native)
```

I downgraded to serverless v1.6.0 and I'm not having any issues. So it's definitely something that has changed in v1.7.0.

My yml file contains 6 functions, and I have around 8 dependencies. (Most every dependency is included in each of the 6 functions.) What's interesting is that 6 seems to be the magic number to make it crash. That is, if I comment out any 1 of the 6 functions (to give us a total of only 5), it works just fine. But with all 6 it will crash every single time.

## Additional Data

* ***Serverless Framework Version you're using***: 1.7.0
* ***Operating System***: macOS 10.12.3
* ***Node Version***: 4.7.3

**Comment by pmuens** [comment]
@robbiehanson thanks for reporting! 👍 

Might be related to https://github.com/serverless/serverless/issues/3249

**Comment by ShaunEgan** [comment]
I have just installed Optimize and am getting the same error:

```
Serverless: Optimize: starting engines
Serverless: Optimize: xxx
Serverless: Optimize: xxx
Serverless: Packaging service...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '/Users/shaunegan/xxxx/node_modules/core-js/fn/number/is-finite.js'
    at Error (native)
```

**Comment by duanefields** [comment]
For what it's worth, it's happening to me too with a very simple project, included here as a reproducible case

https://github.com/duanefields/ReactCounter/tree/serverless

**Comment by duanefields** [comment]
I saw the same errors and the same behavior, but it turns out there were some typos in the JS handler. Fixing those fixed everything. Though it sounds like the syntax errors aren't checked at deployment time in 1.6 (they get a runtime error executing the lamda) but are in 1.7 , so maybe that's wha's happening in other instances too....

**Comment by FreeWillaert** [comment]
Had the same issue, and also here, downgrade from 1.7.0 to 1.6.1 resolved the issue - for now.

I'm confident that there are no syntax errors in my handler file. Any other possible causes?

**Comment by pmuens** [comment]
Hey @FreeWillaert what version of Node are you using?

This bug seems to be related to #3249

**Comment by FreeWillaert** [comment]
Hi,
I use node v4.3.2 (as on lambda).
Using graceful-fs indeed solves it for now - but that hotfix would be great :)
tnx!

**Comment by pmuens** [comment]
@FreeWillaert thanks for the update about this. Fix should be shipped soon!

**Comment by maor** [comment]
Getting the same error. Thanks for all efforts put towards resolving this!

**Comment by pmuens** [comment]
Hey everyone! We just released Serverless v1.8 which has a fix for a related issue (#3249).

Could you please check the new version and see if this issue still persists? Thanks! 👍

**Comment by aidanbon** [comment]
Verified v1.8 fix this packaging problem. Thanks for the AWSome framework!

**Comment by iliasbhal** [comment]
YEAH ! v1.8 fix this packaging problem. Thanks so much !

**Comment by robbiehanson** [comment]
Verified the fix works for me too. Thank you!

**Comment by maor** [comment]
Yup looking good! Thanks for fixing!

**Comment by pmuens** [comment]
Great! Thanks to everyone for testing it out!

**Comment by ShaunEgan** [comment]
Can confirm, works for me now too. Thank you!

**Comment by brianfoody** [comment]
Popped up for me and I just had to re-run the deploy. Random.
