### ISSUE TITLE
DX: Add autocomplete to CLI 

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3254]
In an effort to speed up development and improve developer experience, it's high time we add autocompletion to the CLI.

It should be rather quick to implement and would be very nice UX win.

**There are 2 parts:**

1. Command name autocompletion
2. Partial command matching (nice to have but do second)

## 1. Command name autocompletion

Here is a package to help https://www.npmjs.com/package/omelette. The `p-s` package uses this and it's amazing https://github.com/kentcdodds/p-s#global-installation

**Examples:**

```
sls d[TAB] 
# autocompletes `sls deploy`
```

```
sls deploy f[TAB] 
# autocompletes `sls deploy function -f`
```

```
sls deploy function -f he[TAB] 
# autocompletes `sls deploy function -f hello`
```

## 2. Partial command matching (optional but nice)

Automatically resolve partial matching commands for a super fast CLI experience.

Using something like https://www.npmjs.com/package/prefix-matches. Also used by `p-s` CLI tool by Kent https://github.com/kentcdodds/p-s/blob/master/package.json#L33

**Examples:**

`sls d[ENTER]` will resolve to `sls deploy`

`sls deploy f -f hello[ENTER]` will resolve to `sls deploy function -f hello`

**Leave `sls remove` alone**, we don't want people accidentally tearing down stacks

---

Lets make this happen!

**Comment by DavidWells** [comment]
bump

**Comment by pmuens** [comment]
A related issue can be found here: https://github.com/serverless/serverless/issues/187

**Comment by DavidWells** [comment]
**Prefix matching package:** https://www.npmjs.com/package/prefix-matches

Example: `sls d` will resolve to `sls deploy`

Also used by https://github.com/kentcdodds/nps

**Autocompletion package**: https://www.npmjs.com/package/omelette

**Comment by HyperBrain** [comment]
Would this also work with commands added by plugins - I mean "d" would be ambiguous as soon as some plugin adds another command beginning with "d", like "describe".

**Comment by DavidWells** [comment]
@HyperBrain yeah if there are conflicting paths it will show the options and the user would need to continue typing `d` might match `deploy` & `describe` so they would need to type `dep` [tab] to match deploy

**Comment by HyperBrain** [comment]
Cool 👍

**Comment by DavidWells** [comment]
@eahefnawy sounds like `yargs` package also supports autocompletion now https://twitter.com/kentcdodds/status/864877967104557056
