### ISSUE TITLE
Would you prefer to have a known issues list or for users to submit issues?

### ISSUE THREAD

**Issue by michaelwills** [serverless/serverless#326]
Instead of bombarding the serverless crew with things that are known, would a known issues list in the README be more helpful until this initial transition is complete?

Two examples:

* Lambda functions deploy but don't create API endpoints
* `sl function run` errors with `TypeError: Cannot read property 'lambda' of undefined`

**Comment by cagataygurturk** [comment]
Write this into s-function.json file
 
{
"cloudFormation": {
    "lambda": {
      "Function": {
        "Properties": {
          "Description": "Autoscales web stack responding to alarms",
          "Handler": "handler.handler",
          "MemorySize": 128,
          "Runtime": "nodejs",
          "Timeout": 300
        }
      }
    }
  },
 "functions": {
// The rest of the file
 }
}

**Comment by cluda** [comment]
Isn't that exactly what the issue tracker is for? Managing the known issues.

**Comment by michaelwills** [comment]
Yes it is, but they _just_ switched over to this. I didn't know if they have a preference.

**Comment by eahefnawy** [comment]
Bombard us as much as you want @michaelwills :wink: ... am currently cleaning up the issue list. But having a separate issue for each "issue" is best for communication.
