### ISSUE TITLE
Support for Fission - FAAS for Kubernetes

### ISSUE THREAD

**Issue by FGRibreau** [serverless/serverless#3268]
This ticket is there to start a conversation, if others are also interested... :) https://github.com/fission/fission

**Comment by robcleghorn** [comment]
+1

**Comment by yosriady** [comment]
+1

**Comment by pmuens** [comment]
Thanks for opening @FGRibreau 👍

Closing this issue since the great @ssudake21 worked on a plugin in the meantime 🔝.
