### ISSUE TITLE
Integrate tests in deployment process

### ISSUE THREAD

**Issue by DanDiac** [serverless/serverless#327]
Is there a way to force unit tests execution before starting the deployment process .

The way I imagine this working would be like this:
> jaws dash
> choose lambdas to deploy
> tests run for each lambda that was selected to be deployed
> if tests exit with success, continue deploy
> if tests generate errors, stop deployment

If there isn't an "official" way to do it, did anybody created a personalised system that does this? Or would this feature be included in the new release?

Thank you.

**Comment by eahefnawy** [comment]
This is exactly why we created the plugin architecture for Serverless. You can add pre/post hooks for ever action (ex. deploying functions). We're still working on the docs (docs.serverless.com), so currently there's not much info on how to create plugins, but we'll have it ready in the next few days ;)

**Comment by michaelwills** [comment]
`TestPluginCustom.js` shows it pretty well.

**Comment by DanDiac** [comment]
Thank you! I'm eager to try this as well.
