### ISSUE TITLE
Return code coverage back to proud 100%

### ISSUE THREAD

**Issue by zerkella** [serverless/serverless#3275]
# This is a tech debt issue

## Description

With time the [code coverage](https://coveralls.io/github/serverless/serverless) has slightly deteriorated, and not all the lines in the code are run during the tests execution. The current coverage is 97% - which is still a great number. But it would be much better to have complete coverage and make each line to be executed at least once.

This issue is open as a formal ticket for the subsequent PR I'm preparing.

## Additional Data

* ***Serverless Framework Version you're using***: latest `master` branch

**Comment by pmuens** [comment]
Thanks for opening @zerkella 👍 

Closing this issue since the corresponding PR was closed as well. The reason for closing can be fond [here](https://github.com/serverless/serverless/pull/3276#issuecomment-283585713).
