### ISSUE TITLE
DX: Shrink Git Repo & speed up cloning

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3287]
Cloning down serverless takes much longer than it should. (git repo is like 75MB)

I suspect there are large image assets (gifs) from previous versions weighing down git history.

I propose we blow them away.

https://github.com/tj/git-extras/blob/master/bin/git-obliterate

"Make cloning great again" ™

**Comment by pmuens** [comment]
Good idea.

Yes, there are some large gifs for all the different releases.

**Comment by dougmoscrop** [comment]
there's also `git clone --depth` which is a workaround

**Comment by pmuens** [comment]
Thanks for sharing @dougmoscrop 👍

**Comment by DavidWells** [comment]
We need to `git-obliterate` all the old images and stuff.

Just had another complaint "This is broken" from how slow it was to clone the repo.

**Comment by DavidWells** [comment]
Still a problem when cloning down the repo... It takes a while.

Lets remove the old (large) images

**Comment by pmuens** [comment]
Thanks for opening @DavidWells 👍

I'll close this issue for now since there are no plans to work on this right now.
