### ISSUE TITLE
Add args option to plugins

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3288]
# This is a Feature Proposal for adding args option to plugins

## Description
Currently, serverless does not support command arguments. You can only supply options which creates a poor developer experience in some cases. 

### What is the use case that should be solved. 
Allow for the use of arguments in commands. This should be done through the plugins in the following format.

```
'use strict';

class FooPlugin {
  constructor(serverless, options, args) {
    this.serverless = serverless;
    this.options = options;
    this.args = args;

    this.commands = {
      foo: {
        lifecycleEvents: [
          'bar'
        ],
        args: {
          bar: {
            usage: 'Specify your level of bar',
            required: true
          }
        }
      },
    };

    this.hooks = {
      'foo:bar': this.fooFunction.bind(this)
    }
  }

  fooFunction() {
    console.log('Foo function: ', this.args.bar);
  }
}

module.exports = FooPlugin;
```

**Comment by pmuens** [comment]
Closing since this issue is quite old and we're not planning to update our own CLI implementation in the foreseeable future.
