### ISSUE TITLE
Error: Cannot find module '../lib/Serverless'

### ISSUE THREAD

**Issue by maclennann** [serverless/serverless#329]
Serverless has a lot of case-sensitivity issues within `requires`.

The most-obvious is in [https://github.com/serverless/serverless/blob/master/bin/serverless#L9](bin/serverless) where it `require('../lib/Serverless')`, but the file is called `serverless.js`. As I go through and fix them I find more and more.

I'll try to work my way through them and file a PR but I just wanted to get the issue opened in case anyone else wants it.

```javascript
09:12 $ serverless
module.js:338
    throw err;
    ^

Error: Cannot find module '../lib/Serverless'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/nmaclennan/.nvm/versions/node/v4.1.2/lib/node_modules/serverless/bin/serverless:9:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by michaelwills** [comment]
Weird. The link to the code was rewritten. The text was correct but the link wrong.

https://github.com/serverless/serverless/blob/master/bin/serverless#L9

Wondering if this is a OS X case insensitive issue.

**Comment by maclennann** [comment]
It is almost certainly a case sensitivity issue. I'm walking through the code now fixing each error I run into. I'm 3 or 4 deep into them right now and I just got the main help to finally load. Hopefully that's all of them.

**Comment by michaelwills** [comment]
Interesting code quality issue. Not sure of a way to ensure capitalization automatically although a CI server with tests can help catch this.

**Comment by doapp-ryanp** [comment]
@maclennann @ac360 uses OSX (which as I'm sure you know is case insensitive but preserves case for display).  Are you going to submit a PR with fixes for the requires?

My guess is these type of mistakes will fade/go away as a more formal release process is put in place by the Serveless team.

**Comment by maclennann** [comment]
Yep, I'm on Linux and I figured it was a 'developed-on-OSX' issue. I'm about to file a PR for this. I've got a few failing tests after fixing it that I just need to make sure were failing beforehand or figure out what I did to break them.

I'm curious what your CI process is. It seems like it would be pretty cheap to just npm test on a Linux box on travis or some such even if your "real" process happens elsewhere. That should catch things like this (for the parts of the code that are exercised in your tests, anyway). You can also convert an OSX HFS+ volume to be case-sensitive, I think, but that has always struck me as a bad idea so I've never tried it.

**Comment by michaelwills** [comment]
@maclennann you'll need to set up a `.env` to get tests to pass. I haven't gotten  that far yet.

https://github.com/serverless/serverless/blob/974c6258bb2c0758b86ccc07bcfc3f4353e38f37/tests/config.js

We use drone 0.4 on a Digital Ocean docker image. Very flexible,  still has rough edges, but a good community and _very_ responsive dev folks.

**Comment by maclennann** [comment]
@michaelwills Yeah, I just found that config file. I'm a little afraid that if I set these, the tests are going to actually touch my AWS account (given that it isn't just using dummy-defaults), and I'd prefer if it didn't.

**Comment by michaelwills** [comment]
@maclennann you should join the gitter channel even if you can't read all of it. There have been a good deal of discussion, planning, thinking-out-loud conversations happening.
