### ISSUE TITLE
Serverless variable opt:stage undefined when using default stage

### ISSUE THREAD

**Issue by skbogner** [serverless/serverless#3293]
# This is a Bug Report

## Description
The serverless variable opt:stage is undefined when not specifically specifying it using the --stage cli option.

* What went wrong?
As described.

* What did you expect should have happened?
I would have expected the STAGE variable to be populated with the default stage.

* What was the config you used?
Here's the serverless.yml:
```yml
...
stage: dev
...
environment:
  STAGE: ${opt:stage}
...
```

CLI:
```
sls invoke local -f function_name // STAGE = undefined
sls invoke local -f function_name --stage dev // STAGE = dev
```

* What stacktrace or error message from your provider did you see?
Doesn't apply.

## Additional Data

* ***Serverless Framework Version you're using***: 1.7.0
* ***Operating System***: OS X

**Comment by andymac4182** [comment]
If you look at the example from https://serverless.com/framework/docs/providers/aws/guide/variables#overwriting-variables if you use the syntax `${opt:stage, self:provider.stage}` that will provide what you are looking for I think.

**Comment by pmuens** [comment]
Thanks for helping @andymac4182 👍 

That should do the trick. Closing. Let us know if the problem still exists...
