### ISSUE TITLE
Error: ENFILE: file table overflow, open '.../node_modules/browserify/test/tr_once/main.js'

### ISSUE THREAD

**Issue by 4ossiblellc** [serverless/serverless#3301]
# This is a (Bug Report / Feature Proposal)
When I try to deploy the latest version to the server, I am getting this error:

```sh
  WARNING: You are running v1.7.0. v1.8.0 will include the following breaking changes:
    - Will replace IamPolicyLambdaExecution resource with inline policies -> https://git.io/vDilm
    - "sls info" will output the short function name rather than the lambda name -> https://git.io/vDiWx

  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.

Serverless: Packaging service...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '../node_modules/browserify/test/tr_once/main.js'
```

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:

Similar or dependent issues:
#3253

## Additional Data

* ***Serverless Framework Version you're using ***: 1.7.0
* ***Operating System***: mac osx 10
* ***Stack Trace***: 
```sh
  WARNING: You are running v1.7.0. v1.8.0 will include the following breaking changes:
    - Will replace IamPolicyLambdaExecution resource with inline policies -> https://git.io/vDilm
    - "sls info" will output the short function name rather than the lambda name -> https://git.io/vDiWx

  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.

Serverless: Packaging service...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open '../node_modules/browserify/test/tr_once/main.js'
```
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @4ossiblellc thanks for opening!

What was the problem? How did you resolved it?

**Comment by 4ossiblellc** [comment]
Cannot resolve the problem. I saw the same problem was opened. So, I closed this issue. The only way is to rollback to 1.6.1.

Btw, nice work on the team. I have been using this framework from 0.5.x.

**Comment by pmuens** [comment]
Thanks for the kind words @4ossiblellc and for the update about this issue!

Yes, we're seeing this error since 1.7. We're on it 💯 

Just pasting the similar issue (where we'll track progress) in here once again: https://github.com/serverless/serverless/issues/3253
