### ISSUE TITLE
Support Runtime Babel in Invoke Local

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#3302]
# This is a ( Feature Proposal)

## Description

For feature proposals:

Support Runtime Babel in Invoke Local.

Similar or dependent issues:
* #3087

Its possible or hard to do it? I'll try to search about it and make a PR.

Thanks.

**Comment by pmuens** [comment]
Thanks for opening @marckaraujo 

This feature should be added to the corresponding babel plugin repository since the core of Serverless doesn't support Babel.
