### ISSUE TITLE
Zipping --> Switch back to read stream

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3311]
# This is a Feature Proposal

## Description

In #3310 we've moved away from the `fs.createReadStream` to a `fs.readFileSync` to read all the files for the zipping process.

This is a step backwards as the memory consumption will peak again (we've tackled the issue beforehand in #3220 ).

We should get back to the read stream while preventing bugs such as #3249.

**Comment by pmuens** [comment]
Closing since lots of changes have been made to the zipping functionality.

**Comment by insanetron75** [comment]
This issue is continuing for us in a Jenkins Pipeline.  Around 50% of the time the build will fail because of this this.

We are on version 1.46.1
