### ISSUE TITLE
Support colloquial region names

### ISSUE THREAD

**Issue by robbiehanson** [serverless/serverless#3317]
# This is a Feature Proposal

## Description

We're currently working on a system that's deployed to multiple regions, and I find it difficult to remember every region name. For example:

"What's Oregon again? Is it 'us-west-1' or 'us-west-2'?"
"What's Tokyo again? Is it 'ap-northeast-1' or 'ap-northeast-2'?"

It seems a bit tedious and error-prone, especially when most people refer to these regions by their colloquial/informal name. E.g.: "oregon", "tokyo", etc.

I think it would be a great feature if these names could be supported in serverless.

```
$ serverless deploy --function someFunction --region oregon --stage dev
```

**Comment by johncmckim** [comment]
I'm not sure that is a good idea. It introduces extra complexity, but how useful is it and how hard is it actually to use `us-east-1` ect.

@robbiehanson have you considered wrapping the `sls deploy` commands in a shell script to make it easier?
