### ISSUE TITLE
Extract yaml parser to a separate package and include it on the nodejs template

### ISSUE THREAD

**Issue by mariogintili** [serverless/serverless#3318]
# This is a Feature Proposal

## Description

I think it would be great to be able to access the serverless config directly from my application code, just in case I need to reference some of the settings I've laid out there.

Using a plain YAML parser is not enough as the `serverless.yml` file is evaluated, i.e: `${env:SOME_BAR}` or `${self:whatever}`.

I'm definitely going to extract it as a library but I think it would be a nice feature to have in the `nodejs` template 😄 .

My particular use case is the following:

I'm leveraging AWS's `CloudFormation` to specify the schema of my dynamoDB database. This is specified on the `serverless.yml` file - however under dev and test mode I would like to set up the same config on my local instance. And it would be nice to have a setup where:

```js
// please note some of this APIs are fake and only illustrative
const configParser = require('serverless/yaml-parser');
const appConfig     = configParser('serverless.yml');
const dynamodb     = require('dynamodb');

if (process.env.APP_ENV !== "production") {
  dynamoDb.createTables(appConfig['resources']['Resources']['AppDynamoDbTable']);
}
```

**EDIT** would include extracting this code too https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L123

**Comment by andymac4182** [comment]
You could import your variables from json or js and then you will be able to just import them direct into your code no parser required. https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files

**Comment by mariogintili** [comment]
@andymac4182 Right, but there's an [entire idiom](https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L9-L269) around the `serverless.yml` file - Wouldn't it be nice for users to be able to have read-only access from within the app code without any setup?

**Comment by andymac4182** [comment]
By including this and the ability to read cloudformation into your file this blurs the lines between the responsibilities of your code vs the responsibilities of the framework. Personally for the feature you are referring to I would see that implemented as a plugin not in your application code. 
A plugin will have access to all the variables you are referring to and can hook up with other plugins like `serverless-offline` or `serverless-docker` to set up these resources prior to your code executing. It would actually be great to have a plugin that read the cloudformation and set up as much as it can against `dynamoDb local` or `moto` https://github.com/spulec/moto to be sort of a `cloudformation-local` plugin which would help everyone doing this sort of offline dev and you wouldn't need to include that code throughout ever one of your applications and functions.

**Comment by mariogintili** [comment]
> By including this and the ability to read cloudformation into your file this blurs the lines between the responsibilities of your code vs the responsibilities of the framework

How so? How else am I going to reference variables specified there...which might be required arguments on constructors for things in my code, like a parametised database URL based on an environment or region

I genuinely can't see how you wouldn't want this to be a feature of the framework. Being able to reference config files from your app code is a really common feature in a lot of frameworks

- Rails's config object: http://guides.rubyonrails.org/configuring.html
- Ember's env object: http://stackoverflow.com/questions/26403334/how-to-pass-api-keys-in-environment-variables-to-ember-cli-using-process-env
- Django's config object: https://docs.djangoproject.com/en/1.10/topics/settings/#using-settings-in-python-code


List goes on and on and I'm happy to open an RFC for it - is that the process to suggest new features? we should let the community decide 😄

**Comment by andymac4182** [comment]
Personally the difference between the example config files that you provided are that they are a single configuration file for the application. The example you provided is deployment related which is why I suggested a plugin might be a more fitting location for that use case. I personally prefer to keep my deployment files and configuration files separate.  I set up my deployment process to provide variables for use in my code using the lambda environment variables. This provides me a single immutable package of code that can be promoted through environments using the environment variables feature of lambda to encrypt and provide the different settings for each environment. Locally dotenv https://www.npmjs.com/package/dotenv is a nice way to load these in with a plugin in serverless https://www.npmjs.com/package/serverless-plugin-dotenv that can write out the variables from your `serverless.yml` for you.

**Comment by mariogintili** [comment]
> The example you provided

is not the only example out there;

So who gets to decide what's a potential feature for serverless and what's not? Given we differ, but I know some people that agree with me 😄

**Comment by edsamonte** [comment]
I would love to have this features as well. This is useful for me to be used with Mocha Unit Test. As noted [here](https://serverless.com/framework/docs/providers/aws/guide/testing/), we should decouple our application's logic from the provider code. With Mocha, we test our business logic BUT the problem is configurations are set via process.env which are defined on serverless.yml. It would be best if we can load the serverless.yml from Mocha then just override the necessary values (i.e. DB settings for testing). Setting the variables like the database settings via command line are somewhat tedious for this use case.

Just my two cents.

**Comment by HyperBrain** [comment]
Just something for discussion: Having the resolved serverless.yml in the sources might impose a security issue. While the normal deploy resolves the variables and puts them into environment variables, these can be secured (feature of AWS Lambda) by using KMS. This is especially useful if you set credentials. The variables themselves are likely retrieved from protected SSM variables by using `${ssm:xxx}` in your serverless.yml. So at any time, the decrypted variables are only available at runtim (build process and lambda).
If you now expose the resolved serverless.yml as part of your service you'd expose all protected variables as plain strings without any further encryption - they will become part of your static code.

**Comment by adrianpanicek** [comment]
I would love this to be able to build dynamic router based on function configurations

**Comment by pmuens** [comment]
Closing since this is quite and old issue and there's `yaml-boost` and other packages which can be used here.

**Comment by j3pic** [comment]
I have a use-case for this feature: Somebody wrote a `serverless.yml` and embedded custom keys that encode documentation. I'd like to extract this information, but `serverless.yml` isn't really YAML, so I can't parse it with a standard YAML parser such as Ruby's (it barfs on that `{ Fn::GetAtt: ... }` nonsense). 

I'd sooner write a parser from scratch than resort to manually moving this data into JSON files.

**Comment by jacktuck** [comment]
yaml-boost didn't really work for me, it didn't evaluate variables.

I did this instead
```
const fs = require('fs')
const path = require('path')
const Serverless = require('serverless');
const sls = new Serverless();

(async function () {
  const x = await sls.yamlParser.parse('./serverless.yml');

  sls.variables.loadVariableSyntax()

  sls.variables.service = {
    service: x.service.name,
    provider: x.provider,
    custom: x.custom,
  }

  sls.variables.options = {}

  const result = await sls.variables.populateObject(sls.variables.service.provider.environment)
  const formatted = Object.entries(result).map(([k, v]) => `${k}=${v}`).join('\n');

  fs.writeFileSync(path.join(__dirname, '.env'), formatted)
})();
```

**Comment by JarnoRFB** [comment]
There also is https://github.com/nicolasdao/sls-config-parser which might help with some usecases described here.
