### ISSUE TITLE
Error when using commas in environment variables.

### ISSUE THREAD

**Issue by justinmchase** [serverless/serverless#3322]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I am putting a comma in an environment variable and it is saying its invalid.
Error:
> Invalid characters in environment variable

* What did you expect should have happened?
Comma is a valid value for a variable, I would expect this to not be an error. e.g.:

```
$ DEBUG=info,error node . # no error, process.env.DEBUG === 'info,error'
```

* What was the config you used?
```
environment:
  - DEBUG: info,error
```

* What stacktrace or error message from your provider did you see?
```
[11:33:43] Starting 'deploy-push-feeds'...

  WARNING: You are running v1.7.0. v1.8.0 will include the following breaking changes:
    - Will replace IamPolicyLambdaExecution resource with inline policies -> https://git.io/vDilm
    - "sls info" will output the short function name rather than the lambda name -> https://git.io/vDiWx

  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.

Serverless: Packaging service...

  Serverless Error ---------------------------------------

     Invalid characters in environment variable
```

## Additional Data

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.7.0
```

**Comment by justinmchase** [comment]
Never mind, I'm dumb. Turns out it was the presence of the leading `-`
```
- DEBUG: info,error
```

It should be:
```
environment:
  DEBUG: info,error
```

**Comment by garrows** [comment]
I put dashes in my environment variable and got this. Rookie move on my part.

**Comment by rcwestlake** [comment]
thank you @justinmchase!!!

**Comment by ed-sparkes** [comment]
I need a dash in my environment variable, how would one escape it?

**Comment by justinmchase** [comment]
@ed-sparkes I think you can use the array literal syntax:

```
environment:
  - "DEBUG=info,error"
  - "EXAMPLE-ENV-VAR=withdashes"
```
