### ISSUE TITLE
Remove hard setting of us-east-1 region in service

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3332]
# This is a Bug Report / Feature Proposal

## Description

The `Service` class has a hard setting of `us-east-1` as the default region. However this is a problem with multi provider support since not all providers have a `us-east-1` region.

E.g. after this PR was merged (https://github.com/serverless/serverless-google-cloudfunctions/pull/43/files) it was not possible to deploy w/o specifying a region since it defaults to `us-east-1` (which is not available in the Google Cloud).

**Comment by HyperBrain** [comment]
Maybe a good solution would be to make the default region provider dependent - in serverless.provider.naming there could be a `getDefaultRegion()` function that will return the default provider for the current provider.

**Comment by pmuens** [comment]
Good suggestion @HyperBrain 👍 

Seems like we already have smth. like that in place: https://github.com/serverless/serverless/blob/6ae698359ec701b90ee6c0b327b69c3847f38ddf/lib/plugins/aws/provider/awsProvider.js#L193-L200

**Comment by pmuens** [comment]
AFAIK this has been removed in the past. Closing...
