### ISSUE TITLE
Deployment eu-west-2 with schedule, Resource is not supported in this region.

### ISSUE THREAD

**Issue by vanerleo** [serverless/serverless#3337]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Deployment to eu-west-2 , with **events : schedule** results in " **Resource is not supported in this region.**
* What did you expect should have happened?

* What was the config you used?
  check-missing-certificate:
    handler: task-check-missing-certificate.handler
    events:
      - schedule: rate(20 minutes)
* What stacktrace or error message from your provider did you see?
 _An error occurred while provisioning your stack: CheckDashmissingDashcertificateEventsRuleSchedule1
     - Resource is not supported in this region._

## Additional Data

* ***Serverless Framework Version you're using***:
     Node Version:       6.9.5
     Serverless Version: 1.8.0
* ***Operating System***:
mac
* ***Stack Trace***:
CloudFormation - CREATE_IN_PROGRESS - AWS::Events::Rule - CheckDashmissingDashcertificateEventsRuleSchedule1
CloudFormation - CREATE_FAILED - AWS::Events::Rule - CheckDashmissingDashcertificateEventsRuleSchedule1
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - tasks-v1-prod
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - AttemptsDashwithDashmissingDashdocumentsLambdaFunction
----------

    "CheckDashmissingDashcertificateEventsRuleSchedule1": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "ScheduleExpression": "rate(20 minutes)",
        "State": "ENABLED",
        "Targets": [
          {
            "Arn": {
              "Fn::GetAtt": [
                "CheckDashmissingDashcertificateLambdaFunction",
                "Arn"
              ]
            },
            "Id": "check-missing-certificateSchedule"
          }
        ]
      }
    },
    "CheckDashmissingDashcertificateLambdaPermissionEventsRuleSchedule1": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "CheckDashmissingDashcertificateLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "events.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "CheckDashmissingDashcertificateEventsRuleSchedule1",
            "Arn"
          ]
        }
      }
    },
* ***Provider Error messages***:

**Comment by andymac4182** [comment]
Have you checked if you can manually create a schedule in that region?

**Comment by vanerleo** [comment]
i have and you can.

**Comment by andymac4182** [comment]
If you look in CloudFormation does it give you any extra information as to why the create failed on the schedule?

**Comment by vanerleo** [comment]
same thing,
The following resource(s) failed to create: [CheckDashmissingDashcertificateEventsRuleSchedule1].

CREATE_FAILED	AWS::Events::Rule	CheckDashmissingDashcertificateEventsRuleSchedule1	Resource is not supported in this region

**Comment by andymac4182** [comment]
I would contact AWS as it appears that they might not of enabled that feature of CloudFormation in that region.

Does it work if you deploy to another region?

**Comment by vanerleo** [comment]
yep, it does

**Comment by andymac4182** [comment]
Definitely sounds like a AWS issue then.

**Comment by vanerleo** [comment]
others reporting :
https://github.com/buildkite/elastic-ci-stack-for-aws/issues/249
