### ISSUE TITLE
Module Create fails --- `ServerlessError: Must be in a Serverless project`

### ISSUE THREAD

**Issue by rossmcf** [serverless/serverless#334]
I've created a serverless project in `~/code/injest`. I've `cd`'d into the directory and run `serverless module create`. The output looks like this:

    injest/  > serverless module create -m productImport -f productIngest
    { [ServerlessError: Must be in a Serverless project] name: 'ServerlessError', messageId: 12 }

**Comment by ac360** [comment]
Thanks we'll fix asap! :+1:

**Comment by rossmcf** [comment]
Sorry! It looks as though I'd cd'd into an empty directory created after a first attempt at creating a project. When I tried again, serverless created the project with a suffix.

There's nothing to fix, although it could be a little clearer.

**Comment by ac360** [comment]
@rossmcf Let me know if you have suggestions on how to make it clearer :)  We don't want people overwriting projects, so we auto add the suffix.
