### ISSUE TITLE
Support for webtask.io as an infrastructure provider

### ISSUE THREAD

**Issue by tonyxiao** [serverless/serverless#3345]
I can't seem to find any documentation for whether webtask.io can be a infrastructure provider for running serverless functions. Is there support for webtask in serverless?

**Comment by pmuens** [comment]
Hey @tonyxiao thanks for opening the issue!

Currently we have no "official" support for Webtask. However it's pretty easy to integrate them as an infrastructure provider. You would do this through our plugin system: https://serverless.com/framework/docs/providers/aws/guide/plugins/

Are you interested in getting an integration with webtask off the ground?

Here's a list with officially supported provider plugins:
- https://github.com/serverless/serverless-openwhisk
- https://github.com/serverless/serverless-azure-functions

**Comment by tonyxiao** [comment]
Actually I just realized webtask doesn't allow you to use custom npm modules. So it's likely going to be hard to use with serverless. Maybe something like stdlib would be more appropriate actually. In any case this ticket isn't relevant anymore feel free to close.

**Comment by pmuens** [comment]
Thanks for looking into it @tonyxiao 👍 

I'll close it for now, but feel free to reopen or continue the discussion if you find any way webtask could be integrated.
