### ISSUE TITLE
Serverless Python2.7 Support

### ISSUE THREAD

**Issue by ryansb** [serverless/serverless#335]
This issue is for discussion on adding support for writing modules in Python, please add your thoughts and any components you know will need changing to add support.

**Comment by ac360** [comment]
Right now, many of the Actions in Serverless are language specific.  For example:

`FunctionRunLambdaNodeJs`
`CodePackageLambdaNodeJs`
`CodeDeployLambdaNodeJs`

We'd like to follow this convention and create specific Actions for the new languages we will bring on.  Those Actions will still be written in Node.js, to provide a consistent interface for plugin authors, but they can call scripts written in other languages.  We can put those in the `bin` folder.

**Comment by ryansb** [comment]
That's reasonable - I'll try to stick to Node without adding other binaries to keep the core all in one language, but for package install and such I may need to use Python scripts.

**Comment by ryansb** [comment]
#373 is in progress for this.
