### ISSUE TITLE
configuration for # of builds to keep uploaded

### ISSUE THREAD

**Issue by ryan-dyer-sp** [serverless/serverless#3352]
# This is a Feature Proposal

## Description
- I would like an option within the serverless.yml to be able to specify the number of artifacts we keep in the s3bucket.  Specifically from a code perspecitve allow the cleanupS3Bucket.js to support a config other than 5.  And preferably be able to disable the call to cleanupS3Bucket entirely with a config value of 0.

## Additional Data

* ***Serverless Framework Version you're using***: 1.8
* ***Operating System***: Ubuntu

**Comment by pmuens** [comment]
Closing this for now since this would introduce a breaking change.

A plugin could be written which manages / cleans-up the bucket after each deployment.
