### ISSUE TITLE
Interpolate yaml vars prior to validating frameworkVersion, provider, etc. 

### ISSUE THREAD

**Issue by stephenhandley** [serverless/serverless#3356]
Currently frameworkVersion and provider cannot be referenced via file yaml variables because validation appears to be run prior to interpolation. Would be more convenient if all interpolation happened prior to validation, or at least if documentation mentioned that limitation.

**Comment by goncaloneves** [comment]
Facing this same issue today when having this scenario:
```
config/common.yml
services/1/serverless.yml
services/2/serverless.yml
...
````

In `common.yml` I have all common variables (frameworkVersion, plugins, custom, provider...) and `frameworkVersion` and `provider` break using `${file(../../config/common.yml):frameworkVersion}`.

**Comment by andymac4182** [comment]
If framework version wasn't evaluated before then you could end up with weird other errors if the format of variables changes. Not sure if the provider one is affected by this since they are plugins.

**Comment by goncaloneves** [comment]
@andymac4182 I don't know the extend of damage moving validation later.

I had a peak into the code, seems that this is what is happening:
1. `init()` options are loaded [here](https://github.com/serverless/serverless/blob/v1.9.0/lib/Serverless.js#L61) and validated in `Service class` [here](https://github.com/serverless/serverless/blob/v1.9.0/lib/classes/Service.js#L53-L86)
2. `run()` variables get set with `Variables` class [here](https://github.com/serverless/serverless/blob/v1.9.0/lib/Serverless.js#L85)

**Comment by pmuens** [comment]
Closing this issue since it's quite stale and changing the current behavior would result in a breaking change. We'll re-visit this issue when working on `v2`.
