### ISSUE TITLE
Serverless Module System

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#336]
What has me most excited about the "serverless, function-containerized architecture", is the promise of creating re-usable modules containing pre-written code that can be shared, downloaded and deployed, instantly.  AKA, pre-written Lambdas that accomplish certain tasks that are ready to deploy.

I tried to get this going with AWSM (AWS-Modules), where the modules would use language-specific package managers (e.g., npm) as the delivery mechanism, but the developer/user experience was too complicated and this was keeping me up at night.  

In Serverless, we're changing how modules work...

Here are the goals:
* Multi-language support - Each module has a `runtime` property which designates the runtime of all functions within the module.  Node.js, Python and Java should be able to fit in the same module architecture.
* Unmodifiable core - Module's core code should be untouchable.  If the module is updated by its author, Serverless Project owners can do an update to update only that code, without affecting any of the custom Lambda code they have written around it.
* Modifiable on the surface - Because a Serverless Project is comprised of only module's, Project authors need to be able to write custom logic in those modules.  
* Create and publish from within your project - It would be wonderful if you could easily create and publish modules from within the project you are working on.

Here is how we are trying to reach those goals:

Every Serverless Module looks like this:
```
module
   functionOne
   functionTwo
   lib
   package
```

The function folders contain your Lambda handlers and any custom code you wish to include in them.  The `lib` folder contains reusable, custom business logic that can be required throughout your application.  The `package` folder contains modular/untouchable code that can be required throughout your application.  When you run `$ serverless module update`, only the package folder is replaced, leaving the custom code in your functions and `lib` folder.

There is a lot we'd like to do with the `package` folder.  Before we go heavy into that directions, does anyone have suggestions or concerns?

**Comment by mrtj** [comment]
As far as I understand, serverless uses a simply decentralized way of referencing reusable modules via github URLs. This is cool because we do not have dependency towards a central repo, but makes somewhat difficult for developers to explore existing modules. AWSM had a quick "poor man's" solution to this issue via https://github.com/awsm-org/awsm/blob/master/registry.json. Could we think about something similar or better also for serverless modules?

**Comment by eahefnawy** [comment]
We're gonna build a module registry soon for Serverless Modules where you'll be able to publish and explore Serverless Modules published by our awesome community. Stay tuned :wink:
