### ISSUE TITLE
Support custom target path inside ZIP file when packaging

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless#3366]
For packaging it would be nice if we could specify the target location in side the ZIP location.  I haven't figured out how to do this short of defining a custom packaging script.

# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I'm using python (w/virtual environment) and deploying with serverless.  Currently the serverless packaging features does not allow me to specify the target location in the zip file requires me to create a custom packaging script.

Here is my project structure.
```
./serverless.yml
./src/my_lambda.py
./src/core/other_file.py
/venv/lib/python2.7/site-packages/*
```

I need a package ZIP file with the following structure:
```
./my_lambda.py
./core/other_file.py
./{all pip packages from site-packages in root}
```

My use case is two fold:

1.   python virtual environment dependencies (for a local environment) are in a deep nested path but for lambda they are required at the package root in the ZIP.  [See lambda docs](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html)
2.  I would like to keep a cleaner project structure so I would like to keep the `serverless.yml` file out of the `./src` directory. 

* If there is additional config how would it look

I would propose some additional syntax that allows you to specify the target location in the package ZIP file for each include statement.  

I'm not sure what the best syntax might be but here is one idea.

```YAML
package:
  exclude:
    - tests/**

  include:
    - source: src/**
      target: ./

    - source: $VIRTUAL_ENV/lib/python2.7/site-packages/**
      target: ./

  artifact: path/to/my-artifact.zip
```
For `include` statements.  Define these as either `string | object {source,target}`
If include statement is an object `source` property defines the source glob statement as normal, but `target` specifies the desired destination location within the zip file.  In the example I am targeting the root of the zip file.

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @gmetzker 

related to https://github.com/serverless/serverless/issues/3060

**Comment by jrasillo** [comment]
@gmetzker FWIW I got around this problem by using pip install -r requirements.txt -t <target directory>,
that way I can include the installed libraries in the root of my packaged zip and satisfy dependencies within my code.

**Comment by bweigel** [comment]
@gmetzker I don't know if there is still interest in this, but I have some plugin-code that can do the thing that is discussed here (including packaging custom python dependencies). It is not very pretty yet, but we do use it in production. If you (or others) are interested I am more than happy to open source it (been planning to anyway).

**Comment by pmuens** [comment]
> @gmetzker I don't know if there is still interest in this, but I have some plugin-code that can do the thing that is discussed here (including packaging custom python dependencies). It is not very pretty yet, but we do use it in production. If you (or others) are interested I am more than happy to open source it (been planning to anyway).

Thanks for getting back @bweigel 👍

That would be super nice! Could you also PR this to https://github.com/serverless/plugins

**Comment by bweigel** [comment]
Thanks for getting back so quick @pmuens ! I will PR, when I release it.

**Comment by bweigel** [comment]
I have released the plugin. You can find it here: https://github.com/hypoport/serverless-custom-packaging-plugin. I hope this will help some of you. Please let me know, if there are issues. 

I have issued a PR in the Serverless Plugins repo, too.

Cheers

**Comment by pmuens** [comment]
@bweigel Thanks for releasing and PRing to the "plugin" repository 👍 🎉

**Comment by pawelad** [comment]
It would be really great to have this functionality in core, as it's a very (citation needed) popular practice to have Python packages inside `src/` directory and not in the repository root.

And if that's the case - so the package lives in `src/foo/baz.py`, but you want to import stuff with `from foo import bar` - you have to either move `serverless.yml` into `src/` and call it from there (👎 ) or explicitly add `src/` to Python path so AWS Lambda knows where to look for `foo` (also 👎  but better...?):

```
# in src/foo/baz.py

from foo import bar  # import error, since the file path from Lambda root is src/foo/baz.py

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))

from foo import bar  # works now!
```

**Comment by pmuens** [comment]
Thanks again for opening @gmetzker 👍

I'll close this issue for now since it got quite stale. Furthermore @bweigel worked on a plugin to address this --> https://github.com/serverless/serverless/issues/3366#issuecomment-323724362

**Comment by ronaldour** [comment]
I still think this should be part of the core functionality as this is really common usecase on lambda

**Comment by Fran-Rg** [comment]
For python dev, the solution is explained in details here: https://medium.com/@nate_mitchell/serverless-packaging-user-defined-python-modules-41808776eae0

A bit sad that 4 years aren't enough to provide developers with a non plugin solution.

**Comment by jbsilva** [comment]
Still no native way to do this?
