### ISSUE TITLE
Serverless should throw error when resolution of a variable crashes

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#3367]
_Note:  This report was initially about throwing an error if non existing file is referenced in a variable. It was updated to cover all failed variable resolution cases_

Ideally we should fail unconditionally whenever resolution of a variable from a source crashes.
Note that _fallbacks_ should be applied if no value was resolved (`null` or `undefined`), but not when resolution crashes.

Cases it should cover (by variables scope):
- `file`:  Pointing non existing file
- `cf`, `s3`, `ssm`: Inability to retrieve the data (network or authentication error)
- `env`: Not set environment variable

--- 

Proposed implementation

1. Introduce a configuration option: `unresolvedVariablesNotificationMode` with two possible options `'warn'` (default) and `'error'` (In  v2 we will make `'error'` a default)
2. Throw on unresolved variables if `unresolvedVariablesNotificationMode` is set to `'error'`
3. Introduce a following deprecation log if there are unresolved variables in a service, and service configuration doesn't contain `unresolvedVariablesNotificationMode`:

```
Unresolved variable references will be communicated with a thrown error, starting from next major 
```

See https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations for info on how to configure deprecations

**Comment by exoego** [comment]
This issue seems adressed.
A warning like `A valid file to satisfy the declaration '${./file.js:key}' could not be found.`  for non-existing files was implemented in PR #3208.

Is it OK to change the behavior to throwing error ?

IMHO, error (and abort) is preferrable. Since warning can be missed or ignored by developers easily.

**Comment by eahefnawy** [comment]
@exoego thanks for jumping in! That sounds good, just keep in mind that we have support for overwrites `${./file.js:key, 'dev'}` which might not work if we throw an error. But I think we can work around it with some try/catch or something.

**Comment by exoego** [comment]
@eahefnawy 
I am considering to open a PR in which `serverless` throw error whenever any of variable syntax is not resolved and no fallback found. 
Not only `${file}` but other syntaxes also should get aborted if not resolved.
I believe such change helps users to avoid deploying broken service.

Similar user demands.
https://github.com/serverless/serverless/issues/5053 (`${file}`)
https://github.com/serverless/serverless/issues/5369 (not specified but I assume every variable syntax)

**Comment by pmuens** [comment]
After thinking through this I'm not sure if we can introduce this sinc it would result in a breaking change (although it might be the desired and "correct" behavior).

**Comment by exoego** [comment]
Yes this is "breaking" change.

But IMHO current behavior is error-prone.
I believe fixing these drastically improve DX by preventing deploying broken services and unifying behavior of all variable syntaxes.

**Comment by exoego** [comment]
But I also understand breaking changes should wait until major version up.
I hope v2 is coming soon and I am pleased to contribute for that.

**Comment by medikoo** [comment]
I've updated main description with implementation proposal

**Comment by medikoo** [comment]
PR is welcome!

**Comment by noxasaxon** [comment]
I agree this is needed, and if backwards compatibility is more important then it would be nice to either put this behind a --flag or allow users to specify Raise Error as the fallback variable when it doesn't exist.

It would make things more tedious for people that want errors, but it's better than nothing.
I can't even write a plugin that might address this because plugins are loaded long after SSM checks are made

**Comment by medikoo** [comment]
@noxasaxon have you read my proposal? Also PR that implements it, is very welcome
