### ISSUE TITLE
Cannot get correct value from external yaml

### ISSUE THREAD

**Issue by yoyeung** [serverless/serverless#3369]
# This is a Bug Report

## Description

For bug reports:
Cannot get correct value from serverless.yml

Similar or dependent issues:
This is my sample.yml
```
optimize:
  debug: true
  global: false
```
This is my serverless.yml

```
custom:
  config: ${file(./config/sample.yml)}
```

inside the plugin code is using 
```
console.log(this.serverless.service.custom.config);
```
i will have '${file(./config/sample.yml)}' <---this more than the config which inside the sample.yml

## Additional Data
OS:                 darwin
Node Version:       7.6.0
Serverless Version: 1.8.0

**Comment by vkkis93** [comment]
Hi @yoyeung .
Do you still have a problem ?
Because I tested it and it works very well.

**Comment by dschep** [comment]
@yoyeung are you trying to access that value in the constructor of your plugin? Unfortunately, the variables aren't resolved at that time, but they are during lifecyclehooks later. See docs: https://serverless.com/framework/docs/providers/aws/guide/plugins#serverless-instance
>Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

**Comment by yoyeung** [comment]
@vkkis93 let me close it. 
Thanks
