### ISSUE TITLE
Update Variable File not found warning message

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3379]
https://github.com/serverless/serverless/blob/640dce90baea4588a96bacec26e6891b2e3aae67/lib/classes/Variables.js#L265

Log message isn't clear enough and is causing user pain:

![image](https://cloud.githubusercontent.com/assets/532272/24058518/955f4aa6-0b08-11e7-98d7-f26e67fe49a1.png)

Will update it shortly

**Comment by pmuens** [comment]
👍 Thanks for reporting and working on it!

**Comment by LeBlaaanc** [comment]
I'm getting this despite the parameter existing. Am I mistaken how this works? I'm playing around reading presets out of a typical .babelrc file.

`A valid file to satisfy the declaration 'file(./.babelrc):presets' could not be found.`

.babelrc
`{
  "presets": ["es2015", "stage-0"]
}`

serverless.yml
`
custom:
  serverless-offline:
    port: 4000
    prefix: ${opt:stage, self:provider.stage}
    babelOptions:
      presets: ${file(.babelrc):presets}
`

**Comment by pmuens** [comment]
Hmm. Not quite sure if arrays are supported when loading configs from external files.

Do you know more @eahefnawy ?

**Comment by sethkor** [comment]
Try adding .json to the end of the file (i.e. .bablerc.json)

For what it's worth I was running into similar trivalities and got it working for a yaml file and a json file when specifying an events array:

sls-dev.yml
```
events:
  - schedule:
     rate: rate(1 minute)
```

sls-dev.json
```
{
  "events": [{
    "schedule" : {
      "rate" : "rate(1 minute)"
    }
  }]
}
```

**Comment by pmuens** [comment]
Thanks for the comment @sethkor 👍

> Suggest the serverless doc be updated to note file extension is mandatory when reading variables from files.

Do you want to PR the change to the doc (since you brought this up) or should we take care of that?

**Comment by sethkor** [comment]
@pmuens Sorry what does PR mean?  Proof Read?

**Comment by pmuens** [comment]
Thanks for commenting @sethkor 👍

> @pmuens Sorry what does PR mean? Proof Read? I'm happy to help out.

Great! PR means ["Pull Request"](https://help.github.com/articles/about-pull-requests/). So the basically the question is if you'd like to make the changes and send it over or if we should take care of it 😊.

**Comment by sethkor** [comment]
First time for everything, leave it with me and ill have a crack.

**Comment by sethkor** [comment]
@pmuens I've made the changes in my local repository but can't push it to git hub in order to create a pull request do to a permissions issue.  What to do next?

**Comment by horike37** [comment]
@sethkor 
Did you push to serverless repository directly? You need to fork from the serverless repository into your github account once, then will fix on your repository and send pull request to serverless repository

**Comment by sethkor** [comment]
Thanks @horike37, Ill give it a shot.

**Comment by sethkor** [comment]
@horike @pmuens First time for me doing this, please let me know if it is OK.  Im glad to continue to contribute to the docs as I find small tidbits.  Should I raise issues first for even the smallest updates, say typos?

**Comment by horike37** [comment]
Nice work @sethkor :blush:
>Should I raise issues first for even the smallest updates, say typos?

No need. It's ok to send PR without raising a new issue when updating doc slightly.

**Comment by pmuens** [comment]
> @horike @pmuens First time for me doing this, please let me know if it is OK. Im glad to continue to contribute to the docs as I find small tidbits. Should I raise issues first for even the smallest updates, say typos?

Great! Thanks for the PR @sethkor 🎉 👍 . As @horike37 said, there's no need to open up a separate issue if you just fix some typos or rephrase / rework some docs.

Opening an issue is mainly to discuss larger code / doc changes in advance so that we can get to a consensus and the contributors time is not wasted when the PR needs to be updated because of some disagreements.
