### ISSUE TITLE
Add Docs for Custom Artifact feature

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3381]
# This is a Bug Report

## Description

[In the code, you can supply a pre-packaged artifact for your lambda](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/functions/index.js#72).

The use of this feature is discussed here and marked as a valid bug:
https://github.com/serverless/serverless/issues/2837

This feature is not documented in the [function docs](https://serverless.com/framework/docs/providers/aws/guide/functions/) or the "[comprehensive serverless.yml](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)" example.

Documenting this feature will support users in taking advantage of it.

**Comment by sethkor** [comment]
FYI this feature is broken in v1.18: #4015 
Agreed it should be documented better, the zip created natively by serverless is just to bloated.

**Comment by pmuens** [comment]
Closing since this is quite an old issue and we've updated the docs in the meantime --> https://serverless.com/framework/docs/providers/aws/guide/packaging/
