### ISSUE TITLE
Confusing version tags in git

### ISSUE THREAD

**Issue by apaatsio** [serverless/serverless#339]
Current version is 0.0.7 so the git tags are quite confusing. One could think that the newest version is v1.3.3

```
$ git tag
v0.0.1
v0.0.2
v0.0.3
v0.0.4
v0.0.5
v0.0.6
v0.0.7
v0.9.1
v0.9.2
v0.9.3
v1.0.0
v1.0.1
v1.1.0
v1.2.0
v1.2.1
v1.2.2
v1.3.0
v1.3.1
v1.3.2
v1.3.3

**Comment by ryansb** [comment]
This should be resolved now (on a fresh clone)

```
% git tag
v0.0.5
v0.0.6
v0.0.7
```

Of course, if you have an old checkout, I don't know that the tags will be deleted. You can try `git pull --prune` but I don't know that deletes tags. Otherwise, a reclone should fix it.

**Comment by ac360** [comment]
@apaatsio These should be gone on a fresh git clone, like @ryansb said.  Sorry about this :)

**Comment by apaatsio** [comment]
Looks good :+1:
