### ISSUE TITLE
invoke CLI doesn't accept bash named pipe as event input file (-p)

### ISSUE THREAD

**Issue by lavie** [serverless/serverless#3392]
# This is a Bug Report

Passing an event file to `invoke local` does not work when the file name is passed via a bash named pipe.

e.g. 

`sls invoke local my-function -p <(echo '{ }')`

fails with the error `The file you provided does not exist.`.

## Additional Data

* ***Serverless Framework Version you're using***: 1.9
* ***Operating System***: OSX

**Comment by pmuens** [comment]
Closing since this issue is quite old and we made some changes to `invoke local` in the past.

Feel free to re-open if this issue is still around...
