### ISSUE TITLE
'serverless' is not recognized... CLI tool not found on windows

### ISSUE THREAD

**Issue by diit** [serverless/serverless#3393]
# This is a Bug Report

## Description
When executing the `serverless` command on a windows 10 env, which previously worked - command not found. Reinstall did not help, restart did not help.

For bug reports:
* What went wrong?
Unable to use CLI tool, command not found - generic windows error given
* What did you expect should have happened?
Run command
* What was the config you used?
N/A
* What stacktrace or error message from your provider did you see?
'serverless' is not recognized as an internal or external command,
operable program or batch file.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
N/A
* If there is additional config how would it look
N/A
Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***:
1.9.0
* ***Operating System***:
Windows 10
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
'serverless' is not recognized as an internal or external command,
operable program or batch file.

**Comment by diit** [comment]
For some external reason my npm binary directory was not in my path, adding the following line to my PATH solved the above issues.

`C:\Users\<USER_NAME>\AppData\Roaming\npm\`

**Comment by HyperBrain** [comment]
@diit I use nvm-windows (the Windows port of the node version manager, https://github.com/coreybutler/nvm-windows) on my Windows 10. It works great and takes care of the path settings, even when you switch node versions.

Just install the node versions you need with `nvm install <version>` and switch them with `nvm use <version>`.

**Comment by GJS153** [comment]
[This one](https://stackoverflow.com/questions/40384979/after-installing-serverless-on-windows-10-i-cant-run-serverless-at-the-comma) might be a better solution

**Comment by satejsarker** [comment]
adding  the path in the environment variable will be solve the issue 
C:\Users\<user>\$APPDATA\npm\

**Comment by shashikumarsingh1** [comment]
When i run $npm install serverless , i was getting this issue but when i run $npm install -g serverless . it's working fine for me.

**Comment by NagRaj48** [comment]
> [This one](https://stackoverflow.com/questions/40384979/after-installing-serverless-on-windows-10-i-cant-run-serverless-at-the-comma) might be a better solution

Even though I added %AppData%\npm into the env PATH, the issue has not yet been resolved. Any alternative for this?

**Comment by TrickSumo** [comment]
In case someone face the same problem in future:-

1. Add "C:\Users\<USER-NAME-HERE>\AppData\Roaming\npm" to PATH variable and then run "serverless"
2. If that does not work, use command (Windows):- "C:\Program Files\nodejs\node.exe" "C:\Users\<USER-NAME-HERE>\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js"

**Comment by somyaranjan007** [comment]
I don't have npm follder in "C:\Users<USER-NAME-HERE>\AppData\Roaming\npm"
