### ISSUE TITLE
Include more useful boilerplate in csharp template

### ISSUE THREAD

**Issue by jimmyp** [serverless/serverless#3395]
# This is a Feature Proposal

## Description

When creating a serverless template for aws-csharp there is always a fair amount of work still to do before you have a template you can be productive in. This includes things like, adding unit tests
and configuring an IOC container.

Here is an example of a csharp template my organisation has created as a result of this kind of boiler plate being missing, it is a good example of the kinds of things I would like to include in the aws-csharp template https://github.com/PageUpPeopleOrg/serverless-dotnetcore-template

I'd wager many people create a template like this which has obvious downsides like not being able to take advantages of improvements made in the framework.

I was tempted to include this in the original template #2858 but I wasn't quite convinced it was necesarry. After using the template in anger I now am. This kind of boiler plate is just a fact of life in csharp.

**Comment by jimmyp** [comment]
@pmuens I'd be keen to understand peoples thoughts on this. I have some time sponsored by my company to work on this next week and I'm conscious it might be something that requires some discussion first?

**Comment by pmuens** [comment]
@jimmyp nice. Thanks for taking the time to improve this!

Yes, discussing this before jumping into an implementation is a good idea.

IMHO the template should be as slim as possible. So adding a bunch of stuff which is not 100% necessary shouldn't be done. If there's a need for a huge boilerplate with dozens of functionality then it might be a better idea to use the `install` command to download it.

It should be possible to deploy right away (except for the bundling step for `.Net` code) after creating a new service with a core template.

Does anyone of the @serverless/vip developers use a `.Net` template? If so what is missing / should be added to work with it on a professional level?

**Comment by jimmyp** [comment]
Yeah I figured that would be the stance. I think the main things to add would be a test project (you never want your tests deployed) and an ioc container. The rest can be added by other means (packages, install, plugins).

I wasn't across the install command though. I will look into that and come back here tomorrow and talk about whether that fulfils the need.

Would be interested in hearing others thoughts in the meantime though?

**Comment by johncmckim** [comment]
@jimmyp I think that an IoC container + Tests might be overreach by the framework. Serverless should decide whether you use `AutoFac` and `XUnit` or `ninject` and `NUnit`.

You can however, go and create your own opinionated yeoman generator or boilerplate to create templates for yourself and your team.

**Comment by andymac4182** [comment]
Since there are so many various ways to use .net inside of lambda it would be ideal to keep the initial template as simple as possible with a large list of example projects that show possible ways to implement it.

**Comment by jimmyp** [comment]
I do understand the sentiment.

Could you guys suggest some ways you'd use the framework that wouldn't
benefit from unit tests and an IOC container?

**Comment by andymac4182** [comment]
It isn't that they wouldn't benefit its more that people are very opinionated as to which IoC and which testing framework you should use. Since serverless is a deployment framework not a .net framework it isn't opinionated and personally shouldn't be taking a stance on that.

**Comment by jimmyp** [comment]
I see.

I guess I'm not very opinionated on them so I didn't think it'd be a big
deal to just use one of each of the most popular.

It's a shame to have to repeat this kind of boilerplate every time you spin
something new up. Or go to the effort of maintaining a whole seperate
example/plugin/etc

**Comment by andymac4182** [comment]
You can maintain your own one quite easily that would allow something similar to new using the install command https://serverless.com/framework/docs/providers/aws/cli-reference/install/

**Comment by pmuens** [comment]
Closing this one since the goal of the core templates is to be lean and easy to start with. A potential solution would be to define an own boilerplate and install it via `serverless install` as mentioned above.

Thanks everyone for participating in this conversation!
