### ISSUE TITLE
Improvements to csharp documentation

### ISSUE THREAD

**Issue by jimmyp** [serverless/serverless#3396]
# This is a Feature Proposal

## Description

The dotnet core tooling and sdk are versioning quickly and often making breaking changes. The aws-csharp template depends on specific versions of the sdk and tooling. The documentation doesn't include this info anywhere.

I propose an update to the docs, probably in the csharp hello world example just after the serverless installation guide, that instructs on how to get the right version of the sdk and tooling installed.

**Comment by pmuens** [comment]
@jimmyp thanks for opening! That sounds like a nice addition.

Maybe we can also add this to the F# template after it's merged: https://github.com/serverless/serverless/pull/3045

**Comment by pmuens** [comment]
Closing this for now since our examples (in `serverless/examples`) and the template itself have been updated in the past.
