### ISSUE TITLE
Allow AWS Node js v6.10

### ISSUE THREAD

**Issue by lteacher** [serverless/serverless#3397]
# This is a Feature Proposal

## Description

Hi,

AWS [released support for Node v6.10](https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/) 

Probably I'm super quick because it was just announced today. Anyway thought I could just add this issue in case anyone didn't notice that announcement.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Allow the use of nodejs6.10 in `serverless.yaml`

* If there is additional config how would it look

```yaml
provider:
  name: aws
  runtime: nodejs6.10
```

**Comment by lteacher** [comment]
Looking briefly with no deep knowledge, maybe its just the invoke local which does the explicit check? aside from potential doc changes.

**Comment by eahefnawy** [comment]
Thanks @lteacher ... we were just discussing this internally. You can already start using v6 right away just like you described. I tried it out and it's working. Is it not working for you?

**Comment by eahefnawy** [comment]
The question we currently have is whether this should be the default runtime or not. What you think?

**Comment by owendall** [comment]
👍

**Comment by lteacher** [comment]
Hey @eahefnawy. Yeah I think it looks ok but just the `invoke local` functionality was checking and failing. Ref #3403.

Dunno about the default. Thinking its a better choice even though just added because LTS for v4 is ending next month anyway.

**Comment by eahefnawy** [comment]
Yep we def need that PR! (Thanks @assaflavie 😊 )

**Comment by buggy** [comment]
@eahefnawy Would it be worth changing the -t option from aws-nodejs to aws-nodejs4 then adding an aws-nodejs6 option? This would allow people to easily chose the version they want and save future discussions about the default version. At this stage we don't know how long Amazon is going to continue supporting Node 4 even once official support for the LTS has finished.

**Comment by pmuens** [comment]
> Would it be worth changing the -t option from aws-nodejs to aws-nodejs4 then adding an aws-nodejs6 option?

Good idea. I'd also like to drop the default property for `runtime` and would make it mandatory because there are so many different runtimes and why do we default to `node.js` instead of `python` (Obvious, but valid question)...

**Comment by shavo007** [comment]
this in the next release guys?

**Comment by buggy** [comment]
@shavo007 You can use Node 6.10 now. Just change the `runtime` in your `serverless.yml` to `node6.10`. The rest of this issue for a future release.

**Comment by shavo007** [comment]
@buggy thanks for quick response, as always

**Comment by duncanfinney** [comment]
@buggy I'm getting a validation error when I try to use 6.10. It says it's not a valid value.

**Comment by buggy** [comment]
@duncanfinney Doh! That you have been `runtime: nodejs6.10`

**Comment by marckaraujo** [comment]
@pmuens this should not be closed with the 1.10 release?

**Comment by pmuens** [comment]
Yes. Thanks @marckaraujo 👍 

The deprecation plan to deprecate `nodejs4.3` as the default runtime can be found here: https://github.com/serverless/serverless/issues/3405
