### ISSUE TITLE
JAWS REST API: Multi-Region/Cross-Region Replication (Out of the box?)

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#34]
**This thread is for discussing changes in API Gateway, Lambda, etc., and how JAWS supports Multi-Region/Cross-Region Replication.**

If the JAWS REST API can come out-of-the-box with cross-region replication of your Lambda functions to reduce network latency, it will be incredible.  Imagine, instant cross-region replication of your REST API and you only pay for when it's used via AWS Lambda (!!!).

However, the tools JAWS uses are still new and rapidly evolving (i.e., Lambda, API Gateway), and there is no clear way to do this (yet).  

So, we have to figure this out.  Here are the puzzle pieces...

* First, we want one REST API URL that can route requests to JAWS resources (Lambdas) with the lowest network latency.  I'm not sure how to do this yet.  [AWS Route 53 has latency-based routing](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-latency).  But, I haven't seen/researched how we can configure this to API Gateway.

* Also, [API Gateway now allows you to pass in more context variables to your Lambda functions](https://forums.aws.amazon.com/thread.jspa?threadID=206192).  This is useful.

Thoughts?

**Comment by ac360** [comment]
Updated.

**Comment by austinrivas** [comment]
using API gateway to pass context information into the lambda is huge, I'd like to see how that works but the link you provide is behind aws auth.

**Comment by ac360** [comment]
@austinrivas 

From the AWS Developer Forums...

          Hi, 

          The following context variables are now available in mapping templates. Not the exact solution you wer looking for, but some of that information will be available now. The main part missing would be the full hostname part, but the apiId, stage, and resourcePath are useful for determining path that calls the Lambda function.
                    
          $context.stage
          $context.apiId
          $context.resourcePath
          $context.resourceId
          $context.httpMethod
          
          This will be documented in greater detail soon. 
          
          Thanks,
          Jack

**Comment by austinrivas** [comment]
Great, now we just need to find a way to tie that into your middle-ware and aws config, I'll take a crack at it later today. Thanks for reaching out to the aws team btw, seem like they have been really supportive.

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by ivawzh** [comment]
Wondering where the document is? People mentioned it could be possible by setting up route53 latency routing with API Gateway - https://forums.aws.amazon.com/thread.jspa?threadID=220478. Would love to know your opinions.

**Comment by ivawzh** [comment]
Hi @ac360 I am wondering where the document is? People mentioned it could be possible by setting up route53 latency routing with API Gateway - https://forums.aws.amazon.com/thread.jspa?threadID=220478. Would love to know your opinions.

**Comment by nickalto** [comment]
Looks like this is now possible with Lambda@Edge http://docs.aws.amazon.com/lambda/latest/dg/lambda-edge.html

**Comment by pmuens** [comment]
Thanks for the update @nickalto 👍 

@horike37 just opened up an issue for this a few days ago: https://github.com/serverless/serverless/issues/3944 🎉
