### ISSUE TITLE
Conflicts with between best practices and documentation / cli defaults

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#340]
Best practices say to use camelCase while docs and defaults use hyphenation

[Documention](http://docs.serverless.com/docs/project-create) 

    serverless project create -n my-project -d my-project.com

CLI

    Serverless: Enter a project name:  (serverless-VyslzfWrg)

**Comment by eahefnawy** [comment]
ooh! You're right! thanks for bringing that up! We're still working on perfecting the docs :wink:

**Comment by visualasparagus** [comment]
for sure, just thought I'd mention it.

**Comment by eahefnawy** [comment]
:+1:

**Comment by ac360** [comment]
Fixed in c0f974f025c9b92bad43303c17e01ef72a63a189  Thanks @visualasparagus!!!!!
