### ISSUE TITLE
Add Cognito event source

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3400]
# This is a Feature Proposal

## Description

Add a `cognito` event source.

**Note:** Other event sources (Issues and their PRs) are captured in #1409

**Comment by horike37** [comment]
CloudFormation has not supported `Cognito` yet.
Waiting for it.

**Comment by pmuens** [comment]
Thanks for the quick update on this @horike37 👍

**Comment by marvinpinto** [comment]
Quick update: [Cognito is now supported by Cloudformation](https://aws.amazon.com/about-aws/whats-new/2017/04/amazon-cognito-now-supported-by-aws-cloudformation).

**Comment by horike37** [comment]
Thank you for the info @marvinpinto!
Unfortunatly, it might has not supported for congito sync trigger..

**Comment by HyperBrain** [comment]
@horike37 It seems to have: the `CognitoEvents` property of the `AWS::Cognito::IdentityPool` should be usable to set the different triggers. Although badly documented it seems that it is a map which maps events (e.g. the CogSync event) to targets (e.g. a Lambda function Arn).

**Comment by horike37** [comment]
Thank you for letting me know @HyperBrain. I didn't notice it.
I will work on this in a few days

**Comment by hassankhan** [comment]
If this is added, would this support Lambda events for both Identity and User Pools?

**Comment by horike37** [comment]
@hassankhan 
Thank you for this comment.
Identity only. User Pools has not supported Lambda events.

**Comment by hassankhan** [comment]
I might be mistaken, but doesn't [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-lambdaconfig) refer to events such as `preSignup` etc.?

**Comment by horike37** [comment]
@hassankhan 
We have been discussing about Cognito sync trigger event as follow on this issue.
http://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html#supported-event-source-cognito event 

>doesn't this refer to events such as preSignup etc.?

Maybe this is a little different than an event source for Lambda.

**Comment by hassankhan** [comment]
Ahh okay, it seems I was mistaken; what I'm looking for is a Lambda "trigger" rather than an event source.

**Comment by wmagda** [comment]
Any update on when cognito events will be supported?

**Comment by pmuens** [comment]
@wmagda it seems like there's currently only identity support for cognito via CloudFormation (see here: https://github.com/serverless/serverless/issues/3400#issuecomment-300380530).

Maybe @horike37 knows more about a potential proposal for an event integration 😬 .

**Comment by horike37** [comment]
Thank you for the pinging @wmagda and thank you for the mentioning @pmuens :smile:

We still haven't decided the schedule to release cognito events feature yet.
I will work on this, but I am busy in this week, so haven't started yet.(I am not full time developer for the Framework)

I may be going to work on this after next week, Please give me a little time :sweat_smile:

>BTW. The next step would be a quick proposal how this event integration could look like.

Yes,  rights!

**Comment by pmuens** [comment]
@horike37 thanks for the response!

> I will work on this, but I am busy in this week, so haven't started yet.(I am not full time developer for the Framework)

Absolutely no worries! Don't wanted to hurry you here. Glad to have you as a contributor who is brave enough to do this in his free time 💪 💯 . Just wanted to do a quick check since you were the one who already looked into it.

**Comment by hassankhan** [comment]
Hi @horike37 any chance you had a look at integrating Cognito Sync events? 😁

**Comment by horike37** [comment]
Thank you for pinging @hassankhan 
Sorry, I definitely said I will do but there is another something I want to do on the framework for now. Therefore I have relegated to the event to a lower priority.

Then, you could take care of that instead of me if you want.

**Comment by hassankhan** [comment]
Thanks! That was my plan, I didn't want to duplicate effort though 👍

**Comment by horike37** [comment]
Great! Thanks!

**Comment by eahefnawy** [comment]
Closing this outdated issue. We got support for Cognito! 💯 

https://serverless.com/framework/docs/providers/aws/events/cognito-user-pool/
