### ISSUE TITLE
Deprecate and remove simple string-based http event representation

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3402]
# This is a Feature Proposal

## Description

The current string representation of the `http` event (`http: GET myPath`) is super limiting and nearly always useless (because most of the time you need `CORS` support anyway).

The string representation should be removed. Here are the necessary steps:

- [ ] Update the docs
- [ ] Log a message when someone is still using the string representation
- [ ] Add a note about the change in the list of breaking changes
- [ ] Remove support after ~x updates to the framework

Refs #2718

/cc @eahefnawy @DavidWells @brianneisler

**Comment by patil16nit** [comment]
Hello @pmuens, I am new the node js environment and want to contribute for `Serverless`
Based on the above requirements, I have created the [pull request](https://github.com/serverless/serverless/pull/3408).
Kindly, review the pull request and let me know if there is any misunderstanding in requirements.

**Comment by pmuens** [comment]
Really nice @patil16nit 👍 

Thanks for contributing and welcome to our community! 🎉 

We'll review your PR and get back to you soon (this feature is currently not scheduled for a release, but will be included in one of the upcoming versions).

Thanks again and let us know if we can assists you with anything!

**Comment by pmuens** [comment]
Closing this one in favor of #3486. More information can be found here: https://github.com/serverless/serverless/pull/3408#issuecomment-295137090
