### ISSUE TITLE
S3 not in cloudformation template?

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#341]
Is there a reason the S3 bucket isn't part of cloudformation resources described in resources-cf.json?

**Comment by ac360** [comment]
@visualasparagus Yes, a separate stack of CF resources is spun up for each Stage in your Project.  If we created an S3 bucket for each, it would clutter peoples' S3, which has a hard limit of 100. 

We used to have this but everyone complained at bucket overload :(

**Comment by visualasparagus** [comment]
Makes sense. One S3 bucket is created per region though, correct?

**Comment by apaatsio** [comment]
Just a note here that the limit of 100 buckets in S3 is a soft limit, not a hard limit.

>By default, you can create up to 100 buckets in each of your AWS accounts. If you need additional buckets, you can increase your bucket limit by submitting a service limit increase. 
-- http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by ac360** [comment]
@apaatsio Right :)

**Comment by ac360** [comment]
@visualasparagus Yes, one bucket is created per region because we deploy your AWS Resources via CloudFormation templates in the S3 bucket and CF requires a Bucket in the region that the CF stack is being deployed in :\
