### ISSUE TITLE
Support deploy function to kubeless

### ISSUE THREAD

**Issue by ngtuna** [serverless/serverless#3410]
Hi,

I open this issue for discussing the way to have `serverless deploy` to Kubeless provider.
https://github.com/bitnami/kubeless

Will update soon with a proposal.

**Comment by pmuens** [comment]
Hey @ngtuna should we keep this issue here or can we close it since the implementation already started?

**Comment by ngtuna** [comment]
Yeah we should close this. Thanks

**Comment by pmuens** [comment]
Thanks @ngtuna 👍
