### ISSUE TITLE
project create with -c flag still creates S3 bucket

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#343]
I would expect that the S3 bucket is not created if I run `serverless project create -c`

**Comment by eahefnawy** [comment]
`-c` is short for cloudformation, it just for not creating the cloudformation stack cause it takes a long time. S3 is pretty quick!

**Comment by visualasparagus** [comment]
ok, that makes sense, but isn't 100% apparent with the existing documentation a my assumption was the `-c` flag was to only set the project up locally and leave AWS untouched. 

I would say don't create the S3 either, otherwise, every time I create a project on the command line I end up creating S3 buckets. It's also maybe is convenient that you actually see all of your resources in the `resources-cf.json` and when you delete the cloudformation that it also deletes the S3 bucket (if it's empty of course).

Just a thought.

**Comment by ac360** [comment]
@visualasparagus Good suggestion :+1: We'll put this on the Road Map since it seems more intuitive.

**Comment by erikerikson** [comment]
+1
Despite knowing that it was short for cloud formation, I had a similar expectation.  While I can do what I want in my sandbox, for the corporate account bucket creation permissions are not granted.  This fails the project creation process.  Thereby, without an account where I have bucket creation rights, I can't create a project.
For the record, even if I had the permissions, I would just delete the bucket and modify the config to point at my pre-created bucket anyway.

**Comment by ac360** [comment]
@visualasparagus @erikerikson Thanks for the input everyone.  This feature is now implemented in f38264a296d81334f866cd4cc3f2815b5488b376 and it will be available in `v0.1.1` scheduled for release today.
