### ISSUE TITLE
Add yarn support for alpha plugin detection

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3430]
# This is a Feature Proposal

## Description

Right now only `npm` is supported for the globally installed plugin. This should be changed so that `yarn` is considered when the `npm` lookup fails.

**Comment by ZeeCoder** [comment]
I'd love to see Yarn support too.
But I have both npm and yarn installed, so I don't think automatically detecting the package manager would work.
Instead, I'd rather make it opt-in, like the way travis does it. (somewhere in the yml config)

**Comment by pmuens** [comment]
Closing since `alpha` was discontinued and npm is still the no 1 package manager for Node.js.

**Comment by rdsedmundo** [comment]
@pmuens what exactly was the decision on closing this? Yarn is much more reliable than NPM on my experience. NPM can randomly change your lockfile from one day to other, has a worse `link` system, and throws random errors from time to time. Not to mention that NPM is releasing major versions every time for fixing their bugs, which is not always easy to upgrade (recall the lockfiles I just mentioned). NPM team archived their GitHub repository with 2000 of issues and started a separated forum to report issues, ignoring a lot of problems that were reported by the users.

Yarn + Yarn Team also has its problems of course, but it's way more reliable than NPM.

I wouldn't make this default for sure, nor a failover if NPM is not available, but I think it's fine adding an option to the `yml` that controls the package manager to be used and enables Yarn usage.

I'm available for submitting a PR adding its support.
