### ISSUE TITLE
Can't deploy to azure 

### ISSUE THREAD

**Issue by DDeme** [serverless/serverless#3434]
Serverless: Packaging service...
Serverless: Logging in to Azure
 
  Error --------------------------------------------------
 
     clientId must be a non empty string.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.10.1
     Serverless Version: 1.10.1

**Comment by pmuens** [comment]
Hey @DDeme thanks for opening and trying the Azure provider plugin! 👍  🎉 

Unfortunately this repository is the Framework core. Could you pleas re-open this issue in the Azure provider plugin repo: https://github.com/serverless/serverless-azure-functions/issues

That's where the Azure Functions team triages Issues and PRs.

Thank you very much!
