### ISSUE TITLE
Default tests in aws-nodejs template

### ISSUE THREAD

**Issue by samcorcos** [serverless/serverless#3436]
# This is a Feature Proposal

I propose we add a testing framework and a single unit test by default.

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Right now, the `aws-nodejs` template does not come with any tests. Many frameworks come with a default test configuration that run a simple unit test with `npm test` to make it easier for newbies to start writing tests. 

This would require the addition of something like `jest` and `babel-jest` to `package.json` and a single file that runs a unit test on the `hello` function.

I'm happy to put together a PR for this since I've had to add a testing framework every time I generate a new Serverless project. Let me know if there's any interest.

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by rowanu** [comment]
While I like the idea of having tests, the dependencies you're proposing are non-trivial - [jest](https://github.com/facebook/jest/blob/master/package.json) has a few dependencies...

How do you propose

**Comment by dougmoscrop** [comment]
I'm a soft -1 on this since it's opinionated and 'incomplete' as far as omitting [dev]dependencies goes.

I thought we had support for generating from a URL template? There's no need to scaffold off of 'hello world' every time! Set up a repo with your fully functional skeleton instead?

**Comment by pmuens** [comment]
Hey @samcorcos thanks for opening.

I'm also not 100% sure if we should add this here. I agree, that it's quite opinionated and adds a bunch of boilerplate code.

The core templates should be as lean as possible so that one can get started quickly and is not overwhelmed.

**Comment by samcorcos** [comment]
@rowanu Perhaps we could use a testing framework that doesn't require as many dependencies? I find myself using `serverless-plugin-include-dependencies` and `serverless-plugin-optimize` on every package, but that's a good point. We definitely wouldn't want our dev dependencies bundled.

@dougmoscrop Unfortunately I think adding tests is necessarily opinionated (in JavaScript at least), so there would be no way around that. I hadn't heard of support for generating from a URL template. Can you elaborate on that? Is that in the docs?

@pmuens That's reasonable. I'm not aware of any way to write tests in JavaScript without being opinionated, so perhaps we should just accept that it will not be possible to add tests to the JS boilerplate.

**Comment by pmuens** [comment]
Thanks for the response @samcorcos 👍 

What about the option to add a more complex template to the [examples](https://github.com/serverless/examples) repository where users can see how testing Lambdas could look like. Furthermore they can download this example and go from there.

**Comment by samcorcos** [comment]
@pmuens That works. What kinds of things do you think people would be interested in test examples for? DynamoDB calls? Normal Lambda functionality? Any other services?

**Comment by lteacher** [comment]
A better idea might be to increase support for template plugins or to install globally a template from somewhere.

**Comment by pmuens** [comment]
> @pmuens That works. What kinds of things do you think people would be interested in test examples for? DynamoDB calls? Normal Lambda functionality? Any other services?

I think these blog posts will give a good insight into real world testing:

- https://serverless.com/blog/cicd-for-serverless-part-1/
- https://serverless.com/blog/cicd-for-serverless-part-2/
- https://serverless.com/blog/tdd-serverless/

I would start out with Unit tests for Lambda. After that I think DynamoDB and maybe some integration test for a complete API built atop of API Gateway is interesting since AFAIK those are some of the really often used services.

> A better idea might be to increase support for template plugins or to install globally a template from somewhere.

We currently have an `install` command so that you ca install services / templates from GitHub URLs. But I agree. Maybe it's a good idea to bake this right into create so that you can specify an arbitrary URL rather than a template name and it will install this template from the remote resource.

**Comment by pmuens** [comment]
Closing this one since testing setup is opinionated. Furthermore this feature can be moved to a boilerplate so that the core template is lean.

Thanks for proposing @samcorcos 👍
