### ISSUE TITLE
Serverless badge is broken.

### ISSUE THREAD

**Issue by gertjvr** [serverless/serverless#3439]
# This is a Bug Report

## Description

[![serverless](http://public.serverless.com/badges/v3.svg)](http://www.serverless.com) has been broken for a while, on this repos [README.md](https://github.com/serverless/serverless/blob/master/README.md) and my plugin [README.md](https://github.com/serverless-community-labs/serverless-plugin-simulate/blob/master/README.md)

**Comment by pmuens** [comment]
Thanks for opening @gertjvr 👍 

Yes, we've also seen this problem and pushed a fix. It's showing the correct badge in this issue, the Serverless Framework repo and your plugins repo so I'll close the issue.

Maybe you need to refresh with clearing your cache. After that it should show up again.

**Comment by gertjvr** [comment]
Thanks for taking the time to closing my issue but its still broken for me and other users.

<img width="917" alt="screen shot 2017-04-04 at 11 08 12 pm" src="https://cloud.githubusercontent.com/assets/1691062/24657966/9eef5264-198b-11e7-8e3e-fbabc5d8c2e3.png">

<img width="871" alt="screen shot 2017-04-04 at 11 05 57 pm" src="https://cloud.githubusercontent.com/assets/1691062/24657938/8ac47e54-198b-11e7-8203-503e88137894.png">

**Comment by gertjvr** [comment]
@pmuens ^

**Comment by pmuens** [comment]
Hmm. That's really strange. Here's what I see when I use Chrome in incognito mode

![bildschirmfoto 2017-04-04 um 17 42 48](https://cloud.githubusercontent.com/assets/1606004/24665609/35e1a11e-195e-11e7-8626-22cf9cf54adc.png)

I cleared my cache and tested with Safari as well and everything is fine on my end.

**Comment by gertjvr** [comment]
I have done the same, and viewed it a cross three different computers, windows and mac all show the same broken links.

**Comment by pmuens** [comment]
Thanks for getting back! I cannot access the `.svg` in my end as well.

Reopening...

/cc @DavidWells @ac360

**Comment by dschep** [comment]
relevant? https://github.com/serverless/assets/issues/2

**Comment by pmuens** [comment]
Thanks for the link @dschep 👍 

Correct. The `assets` repo is basically the right place for this. I'll close this here since this issue will be tracked over there....
