### ISSUE TITLE
`sl` command tramples existing tools

### ISSUE THREAD

**Issue by ryansb** [serverless/serverless#345]
There's already an `sl` command on many Linux installs - is it too late to name the CLI tool "serverless" and maybe allow users to alias it to `sl`?

**Comment by mansam** [comment]
Seconding this. `sl` is going to result in a lot of accidental executions of this command when people mean `ls`, which is incidentally the very reason there's already an `sl` command.

**Comment by doapp-ryanp** [comment]
+1 to renaming command to `serverless`

**Comment by ryansb** [comment]
Clarification: this is just about *removing* the `sl` command from the binaries [here](https://github.com/serverless/serverless/blob/master/package.json#L31-L32), since the package already provides the `serverless` command.

**Comment by eahefnawy** [comment]
you can already use `serverless` (ex. `serverless project create`) ... that's the official command, we've added 'sl' just as a handy shortcut. We've thought about aliasing instead, but we figured it's one extra step for the user. But now since it's conflicting, hmmm maybe that would be a good idea!

**Comment by ac360** [comment]
We could simple change the shortcut.  Any suggestions?

We decided upon `sl` because it doesn't require moving your fingers very much.  These offer a similar experience with more keystrokes:

`sls`
`slss`

**Comment by doapp-ryanp** [comment]
My vote would be to remove `sl` and not create another.  I think most devs now a days are on a system with tab completion and/or quick shell history lookup so `se<tab>` is a net 0 gain on less keystrokes. If everyone wants an alias my vote would be `sls`
