### ISSUE TITLE
Wrong cloud formation version in IAM docs

### ISSUE THREAD

**Issue by piohhmy** [serverless/serverless#3450]
# This is a Bug Report

## Description
The IAM docs at https://serverless.com/framework/docs/providers/aws/guide/iam/ in multiple places show `Version: '2017'`. The version *should* be '2012-10-17'.  The examples as documented won't deploy as the version isn't valid.  

I looked at the markdown file at https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/iam.md to fix it but it shows the correct version? 

How can we get this changed in the live docs?

**Comment by pmuens** [comment]
@piohhmy thanks for reporting.

🤔 The doc are rebuilt every time something new is merged into `master`. So this should be fixed once a change to this file was merged.

/cc @DavidWells

**Comment by piohhmy** [comment]
I briefly checked out the git history for that file and didn't see any references to `2017`.  How are the docs deployed?  Could be something there that is transforming dates?

**Comment by pmuens** [comment]
Hmm. Thanks for the response @piohhmy 

The docs are being build every time we merge smth. into master. We use Netlify for this. Not sure what happened here. Could it be that the markdown parser messes smth. up here @DavidWells ?

**Comment by toots** [comment]
Would be nice to fix that, just got the bite myself.

**Comment by pdaryani** [comment]
closing since this issue has been resolved: https://serverless.com/framework/docs/providers/aws/guide/iam/
