### ISSUE TITLE
API Gateway and Lambda is experiencing technical problems in US-EAST-1

### ISSUE THREAD

**Issue by Andriy-Kulak** [serverless/serverless#3452]
So this is more of a broad question, but I ran into the following scenario...
It turns out Amazon's API Gateway and Lambda is experiencing technical problems in US-EAST-1 region.

![screen shot 2017-04-10 at 10 07 05 pm](https://cloud.githubusercontent.com/assets/12179976/24889855/882ce240-1e3a-11e7-8224-fe45250a0e7a.png)

I wonder what do professional developers that manage large applications do when the Amazon resources they are using are currently down in a specific region (in this case US-EAST-1)? Is there a way to switch with relative ease your API gateway and Lambda functions from one region to another?

 At the moment my lambda functions are experiencing the following:
- I get an “Internal Server error” message and 5+ seconds of loading (when typically the functions finish under 200ms during regular operation)
- if I try to hit the POST route from my app, I get a CORS error (even though I enables CORS according to your docs)
- the requests that do return a 200 OK takes too long. I am talking about 3-6 seconds for a request that should typically finish in 200ms.

**Comment by jaikdean** [comment]
If the application's uptime it crucial enough to warrant the effort, then you would typically deploy it to multiple regions and control which region(s) are active via DNS.

Depending on the architecture of the application, there can be a lot of things to consider when doing this and a lot of effort involved. A simple example would be ensuring a database remains in-sync across regions.

**Comment by Andriy-Kulak** [comment]
Thanks for the tip!
