### ISSUE TITLE
Azure --noDeploy is ignored

### ISSUE THREAD

**Issue by truztee** [serverless/serverless#3458]
# This is a Bug Report

## Description
Using serverless deploy with azure functions does not honor --noDeploy option

For bug reports:
* What went wrong?
The command still upload the package to Azure even with noDeploy specified

* What did you expect should have happened?
The command will only create the package file on the local machine

## Additional Data
Serverless: Packaging service with compiled files...
Serverless: Logging in to Azure
Serverless: Looking for deployed functions that are not part of the current deployment...
Serverless: Creating resource group: import-channel-rg
Serverless: Creating function app: import-channel
Serverless: Waiting for Kudu endpoint...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: importJob event: eventHubTrigger
Serverless: Packaging function: importJob
Serverless: Syncing Triggers....Response statuscode: 200
Serverless: Running Kudu command del package.json...
Serverless: Uploading pacakge.json ...
Serverless: Running Kudu command npm install --production...
Serverless: Successfully created Function App
* ***Serverless Framework Version you're using***:
1.10.2
* ***Operating System***:
Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @truztee thanks for opening 👍 

This is an Azure related issue. The implementation needs to be done in the `Azure` provider plugin. Could you please open up an issue over there --> https://github.com/serverless/serverless-azure-functions/issues

Thanks in advance!

Just a heads up: We're about to introduce the new `package` command so `--noDeploy` is no longer supported in the future.
