### ISSUE TITLE
Java integration should support Maven

### ISSUE THREAD

**Issue by raptortech-js** [serverless/serverless#346]
Hey,

The last time I touched this project was several weeks ago. At the time, someone had a pull request for Java support, but it hadn't been integrated. I tried it out, but I realized it was basically unusable for me because of the project structure Serverless (then JAWS) requires. I hear Java support is coming soon. It would be awesome if it could integrate with the way I use Java. At the very least, it would have to allow for the standard Maven project structure and integrate with the Maven build process. I would love it if I could do all the configuration through the Maven POM file and Java annotations.

Currently I annotate my code with JAX-RS and a couple of Swagger-specific annotations to describe the API to export, then use Swagger to automatically generate swagger.json from the Java annotations, and then feed that into the [AWS API Gateway Importer](https://github.com/awslabs/aws-apigateway-importer). It would be awesome to use Serverless instead, but to do that Serverless needs to conform to Java standards, not the other way around.

I'm sorry if this is rambly, confusing, and/or not really a single issue.

**Comment by cagataygurturk** [comment]
You can see my newest project which is a JAX-RS implementation with full maven support:
https://github.com/cagataygurturk/lambada

It lacks documentation for now but this week I'll publish the preliminary documentation and an example application.

**Comment by flomotlik** [comment]
In the next release of Serverless we're going to make sure to support all the different tools you would need for Java, Python and Node development so you can build your applications with Maven and we're picking up your JARs and uploading them to Lambda.
