### ISSUE TITLE
In-depth testing of package / deploy command separation

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3467]
We've recently merged the separation of `package` and `deploy` into master (see: https://github.com/serverless/serverless/pull/3344)

This issue should be used to keep track of and coordinate all the tests we're about to do so that we can make sure that it's non-breaking and can be shipped with `v1.12`.

The following is a list with all the different tests. Please add all the different cases you can think of as a comment. We'll update it constantly so that it always reflects the status quo.

**Aside:** Maybe worthwhile to translate the test cases into different integration tests later on!

---

### `serverless package`

- [x] `package.path`
- [x] `package.individually`
- [x] `function.package.individually`
- [x] `package.artifact`
- [x] `function.package.artifact`
- [x] Command usage without `--package`
- [x] Command usage with `--package`

### `serverless deploy`

- [x] `package.path`
- [x] `package.individually`
- [x] `function.package.individually`
- [x] `package.artifact`
- [x] `function.package.artifact`
- [x] Command usage without `--package`
- [x] Command usage with `--package`

### `serverless deploy function`

- [x] Re-Deployed single function

### Provider integrations

- [x] Google Cloud Functions provider plugin
- [x] Azure Functions provider plugin
- [x] OpenWhisk provider plugin

### Other plugins

- [x] serverless-aws-alias
- [x] serverless-webpack

### Misc

- [x]  Deploy service other than Node.js (used the `aws-java-maven` template)
- [x]  Run `npm run simple-integration-test suite`
- [x]  Run `npm run complex-integration-test`
- [x]  Run Docker-based integration tests (`./tests/templates/test_all_templates`)
    - Succeeds (somehow). Not sure what’s going on though…
- [x] Using `provider.deploymentBucket` (see [here](https://github.com/serverless/serverless/pull/3344#issuecomment-293709359))
- [ ] **BROKEN** Extensive use of variable system (see [here](https://github.com/serverless/serverless/issues/3509))

## Notes

- `package` command will override existing directories with path parameter (this is destructive and might cause problems)

---

/cc @brianneisler @eahefnawy @HyperBrain

**Comment by HyperBrain** [comment]
@pmuens Please put a ✝️  (cross - I did not find the symbol you used) at serverless-webpack plugin as long as I have not fixed the issue. It uses package.artifact during the package phase, so I have to make that available with the correct value at that time.

**Comment by pmuens** [comment]
Thanks for the update @HyperBrain (I'll update the description of the symbols real quick...).

BTW. The Google Cloud Functions plugin has the same problem since it also tries to access `package.artifact` --> `body: fs.createReadStream(this.serverless.service.package.artifact),`

**Comment by HyperBrain** [comment]
@pmuens Fix for the `package.artifact` is in #3469 . Please check also with the Google plugin. I tested it with the webpack and alias plugin already. It should be merged as soon as possible :)
I will fix the deploymentBucket issue next.
