### ISSUE TITLE
S3 bucket naming

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#348]
What's the reason S3 buckets are prefixed with `serverless.`?

**Comment by eahefnawy** [comment]
Just to make the name unique to your serverless projects. We imagine that you probably have non serverless related buckets.

**Comment by visualasparagus** [comment]
Ok, got it.

I would suggest having ‘serverless.<region>' be suffixes then, so the bucket names sort together alphabetically. Not sure if this is possible at this point or not.

**Comment by visualasparagus** [comment]
disregard my previous comment. i didn't quite understand that the bucket is for all serverless projects within a region.domain.
