### ISSUE TITLE
New Python 3 support on AWS

### ISSUE THREAD

**Issue by Cretezy** [serverless/serverless#3482]
# Feature Proposal

## Description

Amazon just launched Python 3 support on AWS: https://aws.amazon.com/releasenotes/5198208415517126

What are the steps towards `serverless` support Python 3?

**Comment by dschep** [comment]
I saw that too so I just went ahead and added support, its a pretty minor change :smile:

**Comment by Cretezy** [comment]
Great! https://github.com/serverless/serverless/pull/3483
