### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Leomel** [serverless/serverless#3487]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
@Leomel thanks for opening.

Could you please update the title to be more descriptive and fill out the issue template so that we know where you need help?

Thanks!

**Comment by pmuens** [comment]
Closing this one since it looks like it was opened by accident...
