### ISSUE TITLE
serverless project create project domain validation throwing an error with certain domain names

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#349]
It seems that domains with more than 3 components are seen as invalid.

    Serverless: Enter a project domain (used for serverless regional bucket names):  (myapp.com) test.myapp.mydomain.com
    error:   Invalid input for Enter a project domain (used for serverless regional bucket names): 
    error:   Please enter a valid domain

**Comment by eahefnawy** [comment]
Great find! we will make our regex validation more flexible :wink:
