### ISSUE TITLE
Add support for Lambda tagging

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3490]
# This is a Feature Proposal

## Description

AWS has recently introduced Lambda tagging support which makes it possible to group Lambda functions and e.g. search by groups in the console.

The framework should support Lambda tagging. Here are the corresponding docs: http://docs.aws.amazon.com/lambda/latest/dg/tagging.html

Unfortunately it seems like CloudFormation has no support for it just yet: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by eahefnawy** [comment]
One thing to keep in mind is that it's AWS specific, although one could argument that lots of function properties are currently AWS specific too.

Personally, I don't see much value there

**Comment by pmuens** [comment]
> One thing to keep in mind is that it's AWS specific

We could prefix the parameter with `aws-tag` (which is proposed strategy to still support provider specific configs):

```yml
functions:
  foo:
    handler: index.handler
    aws-tag: client1
```

> Personally, I don't see much value there

Me neither. It would be maybe helpful if you could then filter your logs by tags. Not sure if this is possible with the current implementation.

**Comment by j0k3r** [comment]
We use tags in AWS to be able to have a global view of how much it cost per environment. For example, we tag everything related to production with the tag `Production` (ie: CloudFormation, EC2, S3, Route53, VPC, etc.) and we are able to tell how much the production cost us. Same behavior with the staging / dev / sandbox env.

That's why I'm :+1: for that feature.

**Comment by xoakx** [comment]
+1 for cost tracking

**Comment by robgodfrey-ft** [comment]
In addition to cost attribution, I find tagging is also important to identify ownership of resources. For example node.js v0.10 for AWS lambda functions is due to become EOL on 30th April and will cease to work after that date. Identifying ownership and ensuring the runtime is upgraded to a supported node version in large accounts is problematic without tags to indicate ownership.

**Comment by shayoosh** [comment]
Since AWS released lambda tagging, we manually tagged all of our functions, mainly for cost analysis enhancement. Would be great if the offered features weeks be supported in the future.

**Comment by pinalbhatt** [comment]
+1 for cost tracking

**Comment by maximede** [comment]
As of today, AWS allows to set tags on lambda via cloudformation

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by pmuens** [comment]
Nice! Thanks for letting us know @maximede 👍

**Comment by brianneisler** [comment]
@pmuens @eahefnawy providers like Azure also offer tagging. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags

Personally, this seems like a pretty generic feature that will also fit well in to the Serverless Platform. I think we should make this feature a first class citizen and then leave it up to the other provider implementations to convert it.

Therefore, I would suggest an implementation like this...
```yaml
functions:
  foo:
    handler: index.handler
    tags:
      key1: value1
      key2: value2
```

**Comment by pmuens** [comment]
@brianneisler I like the proposal. Simple and easy to use.

Great to have it as a first-class property.

Will look into it today!

**Comment by xoakx** [comment]
Personally I updated to serverless 1.11.0 (frameworkVersion: "1.11.0")
In **provider** section I use **stackTags** and all my tags go to each lambda defined in **function** section
```yaml
provider:
  name: aws
  stackTags: 
    Tag1 : MyTag1
    Tag2 : MyTag2
```
But it's true, I can't define a specific tag for a lambda
