### ISSUE TITLE
Add support for AWS x-ray on AWS Lambda

### ISSUE THREAD

**Issue by Kosta-Github** [serverless/serverless#3495]
AWS has added support for `X-ray` on `Lambda`: https://aws.amazon.com/blogs/aws/aws-x-ray-update-general-availability-including-lambda-integration/

would be a nice feature the enable that support from within the `serverless.yml` file by allowing to set the required `enable active tracing` option for the `lambda function`:

![image](https://cloud.githubusercontent.com/assets/2526664/25229942/9d71ec96-25d2-11e7-80b9-2fa8f307fc74.png)

**Comment by soda0289** [comment]
Not sure if it can be set via CloudFormation. But using the api/cli the option is called `tracingConfig` and has two options `Active` or `PassThrough`
http://docs.aws.amazon.com/lambda/latest/dg/API_TracingConfig.html

**Comment by hideokamoto** [comment]
Unfortunately,CloudFormation not support X-ray on Lambda for now yet...
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by balmasi** [comment]
I'm not sure it's actually necessary to have CF support for X-ray. Why can't you just use the application code like the example?

**Comment by pmuens** [comment]
Yes, you could do that without the need for CloudFormation.

There are some convenience wrapper packages like https://github.com/nicka/aws-sdk-plus-xray which makes working with it a little bit nicer.

**Comment by Kosta-Github** [comment]
you could without that, but then you are only be able to trace stuff from the start of the execution of your lambda function. enabling it also on the CF level would also add tracing/timing information about the actual lambda function warmup time before the execution actually started...

**Comment by vanerleo** [comment]
looks like an intresting plugin
https://github.com/AlexanderMS/serverless-plugin-tracing

**Comment by vladgolubev** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/06/aws-cloudformation-now-supports-amazon-emr-security-configurations-aws-lambda-and-aws-x-ray-integration-amazon-cloudwatch-percentile-redshift-resource-tagging-and-other-coverage-updates/


Looks like CloudFormation support is here!

**Comment by pmuens** [comment]
Thanks for the update @vladgolubev 👍 

Looks like @e-r-w already PRed the feature! 🎉 We'll review this PR ASAP.

**Comment by shavo007** [comment]
+1 just to try out!

**Comment by MattHirdler** [comment]
Any ETA on when we can see this? would love it for my current project.

**Comment by pmuens** [comment]
@MattHirdler thanks for getting back 👍

Could you give #3742 a spin? We're currently facing problems with the permissions Serverless should setup automatically.

**Comment by MattHirdler** [comment]
Will do!

**Comment by pmuens** [comment]
> Will do!

Thanks for that @MattHirdler 👍

**Comment by kaihendry** [comment]
Made a video of serverless with X-ray enabled: https://www.youtube.com/watch?v=mHWiiumL0X4

Bit underwhelming really and you need:

```
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: "*"
```

**Comment by pmuens** [comment]
Hey @kaihendry. Thank you very much for recording the video 💯 

We already got a PR open which would do everything automatically for you (see: https://github.com/serverless/serverless/pull/3742).

The only problem we currently face is that for some users the permissions for the Lambda function won't be set. Maybe you could give the PR a spin and see if it works on your machine?!

Thanks again for recording the video as it helps lots of people to set this up 👍

**Comment by dashmug** [comment]
Any update on this?

**Comment by pmuens** [comment]
> Any update on this?

Thanks for getting back @dashmug 👍

I'll cross-link two comment from the respective PR here which describe the current situation (in summary we're still waiting on AWS to fix a bug on their end):

- https://github.com/serverless/serverless/pull/3742#issuecomment-313257833
- https://github.com/serverless/serverless/pull/3742#issuecomment-317594621

**Comment by nalbion** [comment]
@kaihendry I've posted on the AWS forum about trace method/IP/url etc not showing up in the list:

https://forums.aws.amazon.com/thread.jspa?threadID=265808&tstart=0

**Comment by sid88in** [comment]
```Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: GraphqlLambdaFunction - The provided execution role does not have permissions to call PutTraceSegments on XRAY.
```

**Comment by softprops** [comment]
Any update on this?

**Comment by marcfielding1** [comment]
Yeah I was wondering about this, I currently have a "roll my own" type x-ray thingy, are we still waiting for AWS?

**Comment by kbariotis** [comment]
This [plugin](https://github.com/alex-murashkin/serverless-plugin-tracing) works like a charm guys.

**Comment by brandon-dacrib** [comment]
Any chance I could get this to work with the java8 runtime? docs? I am using the aws-scala-sbt template and I have tried a few things with no luck so far.

**Comment by agtcovert** [comment]
Any word on when this will be merged?  We have a need for it, and serverless-plugin-tracing doesn't seem to work for us.

**Comment by incolor2** [comment]
Will X-Ray Tracing in api gateway also be included in this?

**Comment by dfens1** [comment]
any updates?

**Comment by bharathkv** [comment]
Hi,
We are expecting API Gateway-X-Ray CloudFormation support end of November. 

Regards,
Bharath

**Comment by vladgolubev** [comment]
CloudFormation supports X-Ray for API Gateway: https://aws.amazon.com/about-aws/whats-new/2018/11/aws-cloudformation-coverage-updates-for-amazon-secrets-manager--/

> AWS::ApiGateway::Deployment
In the StageDescription property type, use the TracingEnabled property to specify whether active tracing with X-ray is enabled for this stage.

> AWS::ApiGateway::Stage
Use the TracingEnabled property to specify whether active tracing with X-ray is enabled for this stage.

**Comment by mikeblakeney** [comment]
using X-ray with lambdas and serverless could be done by overriding the function in the serverless yaml with the appropriate configuration until x-ray is supported in serverless.

https://serverless.com/framework/docs/providers/aws/guide/resources/#override-aws-cloudformation-resource

**Comment by denisolvr** [comment]
Using the plugin serverless-plugin-tracing on serverless 1.35.1 without no issue guys. Thanks guys! 🎉

**Comment by jeffbski** [comment]
serverless-plugin-tracing worked great for me with serverless@1.37.1
