### ISSUE TITLE
JAWS:  Multiple Environment Support

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#35]
**This thread is for the discussion of how JAWS handles multiple environments**

JAWS must have support for multiple environments.  Let's discuss the optimal way to do this...

Things to consider:

* For the JAWS REST API:  API Gateway uses **stages** for specifying different environments.  

* [The stage variable is now available in API Gateway's mapping templates](https://forums.aws.amazon.com/thread.jspa?threadID=206192&tstart=0).  Though, I'm not sure if they are merely parsing the request path.  If this is the case, then those variables may break when using a custom domain name.  Ultimately, these can be used to request AWS resources that are scoped by environment.

* Are there different Lambda functions for each environment, or do all environments share the same Lambda functions and merely swap out the resources they use?

**Comment by austinrivas** [comment]
might be worth setting up a route 53 domain to test out your theory

**Comment by doapp-ryanp** [comment]
addressed in https://github.com/jaws-stack/JAWS/pull/42

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.
