### ISSUE TITLE
Plugin system should support npm packages

### ISSUE THREAD

**Issue by Nopik** [serverless/serverless#350]
If I want to write SL plugin and ask people to use it, how do I deliver it to them? Currently I can ask them to clone the repo locally and then add path into the plugin list.

I would love to be able to publish npm package, ask people to add it to their package.json and just put pkg name in the plugins.

**Comment by ac360** [comment]
This is our intention, we just haven't tested an external plugin yet, so we still have to fine-tune the installation process.  

What I think may be cleanest is to have a plugins folder that contains a package.json, which `s-project.json` can read from.  In that plugins folder will be a package.json and its node_modules folder.  I just put this on our Road Map and I'm going to test it out right now.  I'm concerned there my be strange loading issues.

What do you think about all of this @Nopik?

**Comment by Nopik** [comment]
It seems that some package.json with its respective npm install should be there. Plugins folder might be good place, up to you.
