### ISSUE TITLE
Remove --noDeploy support

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3510]
# This is a Feature Proposal

## Description

We've updated `--noDeploy` option to call `serverless package` behind the scenes (see: #3517) in order to keep it backwards compatible.

We should deprecate and remove this in one of the upcoming releases.

/cc @eahefnawy @brianneisler

**Comment by srikanna** [comment]
Will there be an alternative if --noDeploy is deprecated?

**Comment by srikanna** [comment]
unable to use "serverless package" it does not recognize the command option. is it supposed to work?

**Comment by pmuens** [comment]
@srikanna thanks for reaching out!

Yes, the `package` command will be the replacement for the `--noDeploy` option. We'll release the `package` command in `v1.12` tomorrow.

**Comment by brianneisler** [comment]
@pmuens since deprecation of this is a breaking change, we'll have to move this to the v2 release.

**Comment by pmuens** [comment]
Yes, that sounds reasonable! Thanks for updating @brianneisler 👍

**Comment by pmuens** [comment]
Closing since this is a stale issue which would result in a breaking change. v2 won't support `--noDeploy` anyways.
