### ISSUE TITLE
Referencing external config files using ${file()} fails and breaks Cloudformation template

### ISSUE THREAD

**Issue by ubaniabalogun** [serverless/serverless#3511]
# This is a Bug Report

#### What Went Wrong
PR #2842 indicates that it is possible to configure a service by referencing external resource files in `serverless.yml` as such

```
service: service-name

provider:
  name: aws
  runtime: python2.7

resources:
  - ${file(./dynamodb.yml)}
```

However, the above configuration yields an error and results in the JSON object located at  `.serverless/cloudformation-template-update-stack.json` being populated with the individual characters of the literal string `${file(./dynamodb.yml)}`

Here’s the error message that is returned:
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading function .zip files to S3...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

     Invalid template property or properties [22, 10, 11,
     12, 13, 14, 15, 16, 17, 18, 19, 0, 1, 2, 3, 4, 5, 6,
     7, 8, 9, 20, 21]

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.1.1
     Serverless Version: 1.11.0
```

and here’s what the `.serverless/cloudformation-template-update-stack.json` file looks like as a result
```
{
  "0": "$",
  "1": "{",
  "2": "f",
  "3": "i",
  "4": "l",
  "5": "e",
  "6": "(",
  "7": ".",
  "8": "/",
  "9": "d",
  "10": "y",
  "11": "n",
  "12": "a",
  "13": "m",
  "14": "o",
  "15": "d",
  "16": "b",
  "17": ".",
  "18": "y",
  "19": "m",
  "20": "l",
  "21": ")",
  "22": "}",
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    }
  }
}
```

#### What did you expect should have happened?
The reference `${file(./dynamodb.yml)}` should have caused the Serverless Framework to load the YAML config in dynamodb.yml and use that to configure resources.

#### What was the config you used?
see description

####  What stacktrace or error message from your provider did you see?
see description

Similar or dependent issues:
* #2828

## Additional Data
* ***Serverless Framework Version you're using***: 1.11.0
* ***Operating System***: Mac OS X El Capitan 10.11.6

**Comment by ubaniabalogun** [comment]
Hey, @pmuens 
I'd like to take a swing at fixing this bug. Can you point me in the right direction? Any idea what code is causing it?

**Comment by pmuens** [comment]
Hey @ubaniabalogun thanks for jumping into this!

I believe it must be somewhere here in the `Variables` class: https://github.com/serverless/serverless/blob/6cca16764df1b9d43c9981642c259bd97063e93a/lib/classes/Variables.js#L173-L231

One thing to keep in mind is that @eahefnawy is currently reworking the variable system behind the scenes so it might be helpful to coordinate with him on this. Eslam also wrote the whole Variable system so he knows how this works!

**Comment by mt-sergio** [comment]
I migrated today from 1.8 to 1.12.1 and I found this bug too :(.
If I copy & paste the code inside `serverless.yml` it works fine.

**Comment by jrasillo** [comment]
I just tested this on 1.13.0 and it works 👍

**Comment by mt-sergio** [comment]
I tested 1.13.0 and variables were not replaced...
serverless.yml:
```
resources:
  Resources: ${file(serverless-resources.yml)}
```

serverless-resources.yml:
```
myKmsKeyAlias:
  Type: 'AWS::KMS::Alias'
  Properties:
    AliasName: 'alias/${self:service}-helloworld'
    TargetKeyId:
      Fn::GetAtt:
        - 'myKmsKey'
        - 'Arn'
```

`$ sls package`
-->
`        "AliasName": "alias/${self:service}-helloworld",`

**Comment by dougmoscrop** [comment]
@mt-sergio you are right but this is actually a different bug.  the original bug applied to the resources section, this bug has come up and causes *all* file-based variables to fail as far as I can tell.

**Comment by dougmoscrop** [comment]
@ubaniabalogun sorry about that, my initial implementation was naive. I've fixed this and added validation/tests against regression.
