### ISSUE TITLE
Avoid Listing Providers (e.g. AWS-only)

### ISSUE THREAD

**Issue by geoffreywiseman** [serverless/serverless#3512]
There's at least one place where the documentation still says Serverless is AWS-only, which is isn't:
https://serverless.com/framework/docs/providers/aws/guide/credentials/

Someone should take a pass through and find these issues and correct them. Any page that isn't meant to serve as a reference for what providers are supported should probably avoid listing them explicitly to avoid needing these updates on an ongoing basis.

**Comment by pmuens** [comment]
Thanks for mentioning @geoffreywiseman 👍 

That's correct. Seems like the docs are a little bit outdated.

**Comment by geoffreywiseman** [comment]
I don't mind taking a crack at it, sending a pull request.

**Comment by pmuens** [comment]
Awesome! Thanks @geoffreywiseman 👍

**Comment by geoffreywiseman** [comment]
To be honest, the one I found was almost the only AWS-only reference still left. Didn't know what to do about the info plugin descriptions in the other providers -- couldn't find corresponding information. Is there anything like `azure:info:validate` etc?  If not, I'll submit a PR with changes, but it'll be very small.

**Comment by pmuens** [comment]
> If not, I'll submit a PR with changes, but it'll be very small.

That sounds good! Such PRs are always welcomed (no matter how small they are).

I'm not sure if there are any other references in the docs. Maybe we can just fix them as we find them. 👍
