### ISSUE TITLE
serverless package does not work.

### ISSUE THREAD

**Issue by srikanna** [serverless/serverless#3515]
# This is a (Bug Report / Feature Proposal)

## Description

command "serverless package or sls package" does not work..

For bug reports:
* What went wrong?
command "serverless package or sls package" does not work..

* What did you expect should have happened?
should create deployement packages  in default .serverless folder.. 

* What was the config you used?
* What stacktrace or error message from your provider did you see?
sls package
 
  Serverless Error ---------------------------------------
 
     Command "package" not found, Run "serverless help" for
     a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.5
     Serverless Version: 1.11.0

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.11.0
* ***Operating System***:
mac OS sierra  - 10.12.4
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
@srikanna thanks for reporting.

`serverless package` will be released in Serverless v1.12.0 tomorrow. You could try the recent version of Serverless from `master` to use it today (note that `master` is not meant to be used in a production environment).

**Comment by srikanna** [comment]
bump. hoping for an update on v1.12.0 release date?

**Comment by pmuens** [comment]
@srikanna will be release in the next couple of hrs. 🎉
