### ISSUE TITLE
deploying from a pre packaged templates

### ISSUE THREAD

**Issue by srikanna** [serverless/serverless#3525]
deploying from pre packaged templates using the command below is not working..

Step 1:
serverless package --stage prod --path templates/prod

Result: Templates in .serverless folder 
Expected result: Templates in templates/prod folder.

So I moved all the artifacts from .serverless/* to templates/prod/ 

Step 2: Tried to deploy using this command..

serverless deploy --path templates/prod

Result: created another set of templates in .serverless/ directory. And deployed these templates.

Expected result: Deploy using the templates in the pre-packaged folder templates/prod

Am I missing something?

Using v1.12.0

**Comment by HyperBrain** [comment]
The parameter is `--package` not `--path` to reference an artifact directory. Could you try with that?

**Comment by srikanna** [comment]
Nope that didnt work either

**Comment by HyperBrain** [comment]
The `serverless package` command with the `--package` option creates a `serverless-state.json` file in the artifact directory. This file is part of the artifacts as well as the cf template json files and must be available in the folder.

**Comment by srikanna** [comment]
Great. all works well. Thanks for the input!
serverless package --stage staging -p ./templates/beta
serverless deploy --stage staging --package ./templates/beta

**Comment by pmuens** [comment]
Glad to hear that it's working @srikanna 👍 

@HyperBrain thanks for helping here!

**Comment by jml6m** [comment]
For some reason, I'm still getting the `No serverless-state.json file found in the package path
 you provided.` error even though I see the file exists in the directory I'm passing to `--package`

**Comment by ostov** [comment]
The serverless package command with the --package option creates a serverless-state.json with absolute path. This is useless fo CI when you have to create artifacts and archive in build job and then restore in deploy job workspace. Of course you can use "sed" before run sls. But why absolute path?

**Comment by Idanatcox** [comment]
Thanks @ostov  based on your feedback I've managed to solve this issue #4188 #5297 
I don't understand why an absolute path is necessary (or being used at all) it's not a good practice.
simply removing the line with the abolute path reference in the state json fixed the problem
Here is what i ended up doing I hope it will help others. this method ensures the package can be deployed anywhere.

**Build**
```
yarn version --new-version $MAJOR_VERSION.$MINOR_VERSION.$BUILD_NUMBER
yarn install
sls package --package dist
sed -i '/Part_of_Path_To_Remove/d' ./dist/serverless-state.json
tar -czf $ARTIFACT_ID-$MAJOR_VERSION.$MINOR_VERSION.$BUILD_NUMBER.tar.gz dist
```

**Deployment**
```
wget tar.gz
tar zxvf ...
sls deploy -s dev -p dist
```
