### ISSUE TITLE
Http Event - Every Request

### ISSUE THREAD

**Issue by Knaackee** [serverless/serverless#3536]
I would like to build a Single Page Application. 

1. Is it possible to set a http event for accepting "every" path ?

I know that i can do something like `/{paramOrSomething}` to catch 
```
- /
- /home
- /about
```

but for nested routes i need something like

```
- /member/{paramOrSomething}
- /member/something/{paramOrSomething}
```

is there a more elegant solution?

2. Is it possible to specify route parameters and conditions?

I don't find information in the docs.

Thx!

**Comment by Knaackee** [comment]
I found a solution. Using` {path+}` worked.

```
events:
  - http:
    path: /{path+}
```

**Comment by pmuens** [comment]
Awesome! Thanks for sharing @Knaackee 👍 

Great to hear that it has been resolved...
