### ISSUE TITLE
Describe resources and policies inside the s-module and s-function files

### ISSUE THREAD

**Issue by firasalmanna** [serverless/serverless#354]
Hello guys, first of all, thank you for this great work.

I have few ideas to implement in Serverless that could make it COOLER.

1-  Having each modules' requirements inside of it (resources and policies), and modifying the `sl resources deploy` command so it will collect all resources and policies from each module and create the `resources-cf` file automatically, then deploying it to AWS.

2- Having each functions policies inside the `s-function` file, and modifying the `sl function deploy` command so it will automatically create these functions` policies and link them together in AWS

**Comment by eahefnawy** [comment]
@firasalmanna we're actually planning to do it exactly this way. Thanks for suggesting. Checkout this Trello card and feel free to add any comments:
https://trello.com/c/ocV3GDiZ/151-resources-refactor-currently-being-worked-on-in-the-resources-branch-check-this-card-s-description-for-more-information
