### ISSUE TITLE
Serverless Progress

### ISSUE THREAD

**Issue by nzchicken** [serverless/serverless#3540]
Look, it doesn't get said enough, you guys do an awesome job building stuff to make our lives as developers a whole lot better. I've been using serverless from back in the alpha days - writing far too much JSON, and now to the time of YAML everywhere. It's great to see the community that you have all fostered, and it's awesome to see the progress. Keep up the great work team.

Because it's fun to know what you have enabled people to do: I recently built an app using serverless as a back end. I have created a secure authentication mechanism which proxies requests off to a salesforce server to get the authentication details (password hash, salt, etc). It issues a JWT token to the client, who then uses that in future requests, which enables the user to request other resources. In other words, I've built a giant Salesforce license dodge (it's not void any terms.... i think), and it costs cents per month to use. Having to actually write this inside AWS console, and/or writing an express server that would do this without making a huge mess - would have been a pain in the ass. Serverless makes it simple!

I know this is a bit inappropriate to raise an issue, but it just needed to be done. This issue is getting closed straight away of course.

# This is a Feature Proposal

## Description
Keep doing awesome work

Use case:
Being productive

Addition config:
More of you guys being awesome

## Additional Data

* ***Serverless Framework Version you're using***: 1.11.0
* ***Operating System***: Mac OS x
* ***Stack Trace***: Error occured in productivity.js. Root cause: serverless being too good
* ***Provider Error messages***: 101 - Too productive, not enough time procrastinating

**Comment by pmuens** [comment]
Wow! Thank you so much for the feedback @nzchicken ! 💯 🎉 

It's super valuable and awesome to hear such success stories. Furthermore it's great to hear that the things we do here provide real value and help people succeed.

Thank you so much for this! Great to have you in the Serverless community.

**Comment by eahefnawy** [comment]
@nzchicken You just got me super motivated! 😊 ... Thanks a lot for your kind words!
