### ISSUE TITLE
Failure to Create Resource Using !Ref 

### ISSUE THREAD

**Issue by IamGabrielWu** [serverless/serverless#3545]
Hello
I'm trying to create resource, but i got error as below. Does serverless framework here support !Ref ?

`PS D:\code-repository\gabrielcv\cvservice> serverless deploy

  Y A M L Exception --------------------------------------

     unknown tag !<!Ref> in "D:\code-repository\gabrielcv\cvservice\serverless.yml"
     at line 159, column 32:
                RestApiId: !Ref
     api
                                   ^

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.9.1
     Serverless Version: 1.10.2
`

``

**Comment by HyperBrain** [comment]
The "!" notation is not supported currently in `serverless.yml`. You have to use the object based `Ref` notation.
```
myProp:
  Ref: myRefId
```

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍 

Yes, that's currently not supported. We track the progress in this related issue: https://github.com/serverless/serverless/issues/3184

Thanks for opening @IamGabrielWu
