### ISSUE TITLE
Exclude by default the packages that exist on the external environment

### ISSUE THREAD

**Issue by hwernstrom** [serverless/serverless#3546]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
When doing the package and deploy, have the default packages that already exist on the external environment exclude by default. 

For example, when I test locally I need to install the aws packages. The global install doesn't seem to work. I need to type in the packages for exclude when there are a lot of packages aws uses. This would create a small deployment and a faster load time to AWS.

* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.11.0
* ***Operating System***: Windows 10
* ***Stack Trace***: Enhancement request
* ***Provider Error messages***:

**Comment by DavidTPate** [comment]
@hwernstrom Could you please fill out the bug report/feature request above?

**Comment by pmuens** [comment]
@hwernstrom thanks for opening!

Could you provide a little bit more context / explanation around the problems you face? I'm not sure if I understood it correctly. Thanks!

**Comment by hwernstrom** [comment]
I wan the zip files that get uploaded to s3 to be a small as possible for fastest deployment. If I run local test I need the ec2 node modules install in the node_modules folder. I might have other external libraries in there. I would like for the serverless deployer to recognize that a node_module library already exists on the lambda envirnoment by default and exclude it from the package zip for deploy. I know I can list all those into the exclude but ec2 has a lot of modules that it uses and it is a lot of excludes.

**Comment by pmuens** [comment]
Gotcha.

So you want that Serverless will exclude the `aws-sdk` module from the bundle when the service is deployed to AWS, correct?

This issue is related to https://github.com/serverless/serverless/issues/2709 so I'm closing this one for now as we can continue the discussion over there.

Thanks for opening @hwernstrom 👍
