### ISSUE TITLE
SLS deploy broken for project without function

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3547]
# This is a Bug Report

## Description

Attempting to deploy a function-free serverless.yml results in a failure.  The failure complains that no package (e.g. foo.zip) is available.

This issue effects 1.12 but not pre-1.11.

For bug reports:
* What went wrong?
Error: `No ingress-stream.zip file found in the package path you provided.`
Deployment did not proceed.

* What did you expect should have happened?
Deployment of [the well-formed and correct] CloudFormation stack would occur.

* What was the config you used?
https://github.com/Nordstrom/hello-retail-workshop/blob/master/Lesson1_HelloRetailStream/ingress-stream/serverless.yml

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.12
* ***Operating System***: all
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for reporting @erikerikson 👍 

/cc @eahefnawy @HyperBrain

**Comment by HyperBrain** [comment]
Yeah. Good point. I think we check for existence of an artifact name on deploy (exactly: in `extendedValidate`) that seems not to be set in case there are no functions defined. Imo we could losen the check and allow an unset artifact name only, and exactly only if no functions are defined (i.e. `getAllFunctions()` returns an empty array/object).

**Comment by silver2k** [comment]
This also occurs when using something like the Webpack plugin which seperates the deployables to individual packages.

**Comment by HyperBrain** [comment]
@silver2k I tested the package and deploy with the webpack plugin (serverless-webpack) and we also use it in our production CI/CD with Serverless 12.1. Works as expected, even with "--package" on separate server agents.

**Comment by silver2k** [comment]
Weird - using the exact same setup, I am seeing the following
In a project called "test" using `serverless-plugin-webpack` to create individual packages.
with `sls package -p dist`
I get a folder containing:
cf templates
serverless state json
and 1 zip file per configured event in serverless.yml i.e.:
getThing.zip
postThing.zip

calling `sls deploy -p dist` I see:

`No test.zip file found in the package path you provided` 

Which is absolutely true - but not helpful.

**Comment by silver2k** [comment]
Just realised I'm using a different webpack plugin than you are!

**Comment by HyperBrain** [comment]
Ok. Yes there are two of them - we chose serverless-webpack, because it also has webpack 2 support in the meantime and even works perfectly with serverless-offline and its own local run implementation.

**Comment by tobyhede** [comment]
This is pertinent to my interests as we have some services that use serverless but not functions (deploying via containerless plugin to ecs). 

I am happy to jump in and address this. 

I was thinking that if no functions are defined, we print a warning, but allow the deploy to go through. 

If functions are defined, but the packages are empty then keep the current behaviour and failing - in this case it is possible that the developer has misconfigured package globs or paths or something else is going on.

**Comment by silver2k** [comment]
That sounds reasonable to me.
At the moment I am working around the issue with a `touch projectname.zip`
to trick it.
So anything is better than that.
