### ISSUE TITLE
Update Azure Documentation to setup credentials

### ISSUE THREAD

**Issue by pragnagopa** [serverless/serverless#3555]
# This is a (Bug Report / Feature Proposal)
Documentation update
## Description
Instructions to setup Azure credentials [here](https://github.com/serverless/serverless/blob/master/docs/providers/azure/guide/credentials.md) needs to updated to match latest [npm package](https://www.npmjs.com/package/serverless-azure-functions)
For bug reports:
* What went wrong?
Azure plugin is now updated to support interactive logging. Documentation needs to updated to reflect new changes.
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pragnagopa** [comment]
@lostintangent  - npm package with interactive login support is now published. Please update the documentation here.

**Comment by Alber70g** [comment]
Interactive login support isn't working. It hangs on `Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: XXXXXXXX` after logging in in the browser. Anything to do about this?

**Comment by pmuens** [comment]
@Alber70g thanks for commenting!

Could you please open up an issue in the Azure Functions Provider Plugin repo where the development of the Azure integration takes place: https://github.com/serverless/serverless-azure-functions/issues

Thanks 👍

**Comment by pmuens** [comment]
Closing this issue since credentials setup docs can be found here: https://serverless.com/framework/docs/providers/azure/guide/credentials/
