### ISSUE TITLE
Windows: Uploaded binaries cannot be executed

### ISSUE THREAD

**Issue by mattisdada** [serverless/serverless#3557]
Attaching a binary file to the project on the Windows platform should behave similarly to Linux, in which that given the correct permissions on the file it should be executable by the Lambda server (or similar Serverless binary compatible server)

A workaround for this issue is to use Bash for Windows to zip the project (with the file given 777) and upload manually
* What did you expect should have happened?
The file attached should be executable by Lambda (or similar Serverless binary compatible server)

Although I expect it to be executable the way Windows defines what is/is not executable is different to Linux, so the permissions on the file may be harder to utilise, a proposed idea is to have a configuration file marking files/folders as executable
* What was the config you used?
N/A
* What stacktrace or error message from your provider did you see?
`[Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn'` when trying to launch the process

Similar or dependent issues: #1631

### Proposed solution

_(Added by maintainers after investigating the matter)_

1. As proposed below in https://github.com/serverless/serverless/issues/3557#issuecomment-315525767 by @ilanc, when packaging on Windows ensure each packaged file is executable (as we're packaging for environment with already properly restricted access, so there seems no risks in doing that)
File permissions are setup here: https://github.com/serverless/serverless/blob/03940254385e138eb40f2f25bd56fcdbee0c3a22/lib/plugins/package/lib/zipService.js#L105-L109

2. Revert tweak introduced here https://github.com/serverless/serverless/pull/5813 for golang runtime. It's hacky and obsolete with above solution

PR's welcome!

**Comment by HyperBrain** [comment]
Is this really something that can be done without adding much techical debt? I think an operating system that has no knowledge of UNIX access permissions cannot be mapped easily to UNIX.

The above mentioned idea, specifying rights for folders might open severe security issues as the executable bit as well as the world-readable/writable would be applied without control. How much AWS will pretend that the Lambda environment is safe itself, copying files/folders without proper permissions there is a risk.

Imo deployments that require special UNIX specific access rights should be done on a compatible system (e.g. developing locally on Windows, but leaving the infrastructure - CI/CD - on a Linux based machine). As Git supports umask flags it is no problem to have the binaries checked in correctly on Windows systems and checked out and handled correctly on the build server.

Just my 2 cents.

**Comment by mattisdada** [comment]
I completely agree with you, but having to build on a foreign system without a workaround feels pretty gross and mandating more complex build/deployment for it to work is painful (whereas right now you can just start working on something small and simple and get it up and running easily)

I'd say the way executable are currently being handled is equally insecure as right now it is unclear what the  `serverless deploy` command is doing, if I was working on a developer machine to do my deployments, I would often have "looser" file permissions than I would on a normal build server/production environment, it would be easy to accidentally introduce something as too permissive

My proposed idea would be more to make everything non-executable (even if in the system it is 777 or similar) unless specified in the config, if worried you could even remove globbing and just have listed files

For example:
```
package:
  include:
    - some-shared-lib.js
    - sox
   executable:
    - sox
```
It would make deployments more consistent regardless of the operating system running the deployment, and in general going out of your way to make something more permissible is generally more secure (if that is a concern)

**Comment by viperscape** [comment]
I am using the [WSL](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/) to build my executable, and had to install zip within wsl, then build the zip with the executable which preserves the rwx flags. Why doesn't lambda take in tars? I like the above approach of having an executable subfolder, maybe labeled 'bin'.

**Comment by adieuadieu** [comment]
I'd like to engage with the Serverless community on this issue. This issue has come up in the [serverless-chrome](https://github.com/adieuadieu/serverless-chrome/issues/21) project from developers deploying from Windows. We have a thread tracking the issue as it relates to the project [here](https://github.com/adieuadieu/serverless-chrome/issues/21), but we're a bit stuck. Our solutions so far:

- Provide a Docker image to deploy from — equal parts cool and lame
- [Hack](https://github.com/adieuadieu/serverless-chrome/issues/21#issuecomment-315477858) Serverless' zipService.js to chmod files as executable when added to the zip during packaging. This one is perhaps relevant to this Issue thread—if we knew when we should set the file as executable. Kind of what what @mattisdada is [suggesting](https://github.com/serverless/serverless/issues/3557#issuecomment-299165189).

What's the community's opinion on adding a `package.executable` configuration options to `serverless.yml`?

**Comment by ilanc** [comment]
Windows file permissions don't have rwx like unix does. So there's always a problem when you zip on windows and try unzip to unix and want a certain permission mode to result. In particular windows gets the exec permission wrong, so zipping unix binaries on windows and unzipping on unix gives you non-executable binaries. Most zip libraries have encountered this in the past - see [archiver](https://github.com/archiverjs/node-archiver/issues/136), [JSZip](https://github.com/Stuk/jszip/issues/194), [gulp-zip](https://github.com/sindresorhus/gulp-zip/issues/38) - and have their own workarounds.

In `serverless-chrome`'s case you need `serverless-chrome.zip\headless-chrome\headless_shell` to be unzipped into a lambda with +x permissions. With the existing serverless code (and windows pokey permission system) you wind up with rw- i.e. 666 (or perhaps 644). My hack was to make serverless set the file permission on _all files_ inserted into the zip to have 777 permissions. It means that all of these will be rwx inside the lambda:
* serverless-chrome.zip\handler.js
* serverless-chrome.zip\headless-chrome\headless_shell
* serverless-chrome.zip\headless-chrome\libosmesa.so

This isn't a problem in `serverless-chrome`'s case but it may impact other serverless apps which need to preserve permissions. NB Given that you cannot set unix file permissions on a windows dev machine I would say that anyone who is using windows as a dev platform doesn't have this requirement.

Hence the quickest hack for windows dev and deployment seems to be to have a check in `serverless\lib\plugins\package\lib\zipService.js` to say:
1. if unix - then use file permissions normally
2. else if windows - always set to 777

Summary:
* As things currently stand with serverless - you can't use windows as your development platform whenever you have unix executables to deploy (like headless_shell)
* Using the proposed hack - windows dev is possible but all files will have exec permission even when they're not executable. AFAIK this doesn't seem to cause any problems.

**Comment by HyperBrain** [comment]
@ilanc I agree with your evaluation above.

> Using the proposed hack - windows dev is possible but all files will have exec permission even when they're not executable. AFAIK this doesn't seem to cause any problems.

This is true, but there is an additional important point. Having 777 as permissions for all files will not just enable the execution permission, but will make all files **world writable**! Even if it doesn't case any problems it is imo a severe security issue. If anyone manages to get into one of AWS Lambda host servers with read permissions, he would be able to replace your files and add some "custom" behavior, completely without the need to become root.

My opinion is, that there should be nothing implemented into a deployment framework that opens that door. If you need to change permissions explicitly, you should use a operating system that implements them properly in the same way it is implemented on the target operating system (which is AWS Linux for Lambda).

@adieuadieu Having a configuration option in serverless.yml would be a solution, but it should only allow setting single files explicitly. Anything that might change permissions of everything if used wrongly should be avoided.

**Comment by ilanc** [comment]
I think if someone gets remote access to your lambda you've got bigger problems to worry about than whether the handler.js is writable. That said you could just as easily default to 744 instead of 777.

**Comment by ilanc** [comment]
BTW this appears to be the solution which docker uses, when building docker images on my windows box i get the following warning:
```
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

**Comment by ilkka** [comment]
What sort of help is desired here? To me the Docker workaround of just writing everything with `rwxr-xr-x` sounds quite reasonable.

Also, another possible mitigation for this is working (at least partly) in Windows Subsystem for Linux. This is slightly less encumbering than having to pop over into a VM, but if your code lives in WSL you lose the ability to use any GUI editors on it.

**Comment by Agrumas** [comment]
Some kind of workaround is really needed because `go` applications can not be used if deployed using win.
Execution fails: `{ "errorMessage": "fork/exec /var/task/bin/main: permission denied", "errorType": "PathError" }`
`executable` option is good but not flexible I would suggest `mode`:
```yaml
package:
  include:
    - some-shared-lib.js
    - sox
  mode: 0744 # change mode for all files
  mode: 
    0644:
      - sox # change mode per file
```

**Comment by lcharbon** [comment]
Had this issue deploying from a Mac through a network drive that does not support permissions.

**Comment by billmcknight1953** [comment]
Is there an actual solution for the problem of uploading go binaries from Windows to AWS.  I too am getting the error` { "errorMessage": "fork/exec /var/task/bin/main: permission denied", "errorType": "PathError" }`.  My executables permissions inside the zip is rw, whereas the file's permission outside of the zip is rwx.

**Comment by crsepulv** [comment]
There is a workaround for this issue rather than "deploy using a linux machine"?

For now, I move the file from /var/task/ to /tmp because on /tmp i can change permissions and execute the files. I have to do it on every invokes because /tmp is ephemeral, this brings a lot of overhead.

**Comment by martamius** [comment]
+1, I am also running into this issue.

**Comment by martamius** [comment]
Amazon provides a tool for zipping the files on a windows machine so they work in lambda. Could serverless just be modified to use this tool when zipping on windows? 
https://github.com/aws/aws-lambda-go

**Comment by billmcknight1953** [comment]
In the end I used https://github.com/rayhaanq/win-go-zipper,  a zipper written in go, but which compiles to an EXE.  This zipper gives the right permissions.  This means that I first build  the lambdas and then zip each.  Finally when I deploy them  with  serverless.yml,  I use artifacts. For example 

  myfunction:
    package:
      artifact: myfunction.zip  
    handler: bin/......

**Comment by ilanc** [comment]
We just fiddled the permissions in our app code on startup. There were some tricks (I can't remember - it's been a while) - IIRC you can only change files in `/tmp` so you may have to copy the file there in order to change permissions. In our case we were copying files off S3 first anyway.

```js
    var options = { encoding: 'binary' };
    if (executable) {
      log.info('Setting "' + src + '" as executable');
      options.mode = 16832;
    }

    fs.writeFileSync(dst, fileContents, options);
```

**Comment by ChristopherBrand** [comment]
My solution to this issue was to create a Docker container and a small PowerShell command to manage its instantiation. I run the command from within my Serverless Framework Golang projects in Windows and it instantiates a full Ubuntu 18.04 environment for me. You can find the project at https://github.com/ChristopherBrand/serverless-golang

**Comment by jordansissel** [comment]
I hit this as well. Windows 10, serverless 1.28.0

```
# Have to build by hand because I don't have `make` on Windows.
> echo $Env:GOOS
linux
> go build -ldflags="-s -w" -o bin/world .\world\
> go build -ldflags="-s -w" -o bin/hello .\hello\

# Deploy, so far so good...
> serverless deploy
... successful ...

# But cannot run it:
> serverless invoke -f hello -l
{
    "errorMessage": "fork/exec /var/task/bin/hello: permission denied",
    "errorType": "PathError"
}
...
```

**Comment by CbrandVendini** [comment]
@jordansissel you don't need to change anything. Just use my serverless-golang project it spins up an environment in docker that lets you build and deploy serverless golang projects.

https://github.com/ChristopherBrand/serverless-golang

**Comment by ChristopherBrand** [comment]
@jordansissel you don't need to change anything. Just use my serverless-golang project it spins up an environment in docker that lets you build and deploy serverless golang projects.

https://github.com/ChristopherBrand/serverless-golang

**Comment by afkhalid** [comment]
@ilac
How you accomplished this 

>> My hack was to make serverless set the file permission on all files inserted into the zip to have 777 permissions.

can you clarify in steps how this can be achieved?

**Comment by ChristopherBrand** [comment]
There is no hack required. My docker solution above gives you a command line that is 100% compatible with serverless deployments.

**Comment by afkhalid** [comment]
Thanks @ilanc so much for your quick reply. @ChristopherBrand Thanks so much, it's will be widely used on our organization and I dont want to add additional overhead of have to install docker and include other packages as all of our packages get validated by FDA, thanks so much.

**Comment by emlyn-Resn** [comment]
I've just implemented a work-around (that I thought might be useful to someone), using Lambda [Layers](https://serverless.com/framework/docs/providers/aws/guide/layers/).

If you can create your layer package artifact zip, on a non-windows system,  it will preserve the permissions.  Then you can deploy the raw zip file eg..
```yaml
layers:
  layerOne:
    package:
      artifact: layerSource.zip
```

Previously I was doing the copy-to-temp trick, but this feels much nicer.  Also added bonus of not having to redeploy you binaries every time.

**Comment by dschep** [comment]
So, for golang support (#5813) I partially did this. Maybe that code can be extended to read from a list of files in `package.executables`(or something) to `chmod +x` while zipping.

**Comment by thasmo** [comment]
It would be nice to see configuration options to define executable permissions/modes as suggested by @mattisdada and @Agrumas so deployment from Windows works too. I'm currently working on a node.js lambda which uses `headless-chrome`, which fails to run on AWS because of this issue.

**Comment by dschep** [comment]
another thought... is there a nodejs native equivalent of linux's `file` command that could tell us that a file is a 64 bit linux ELF binary? I think it'd be reasonable to add execute bits while zipping on windows to all appropriate linux binaries.

**Comment by thasmo** [comment]
@dschep Not sure something exists natively, but I've found [`node-elf`](https://github.com/sifteo/node-elf). Not sure it provides the bits needed to determine ELF binaries.

**Comment by lbindal** [comment]
I am having issue with something similar, not sure if it is relevant
https://stackoverflow.com/questions/62105095/httpie-command-from-aws-lambda-python3-8

**Comment by kavukcutolga** [comment]
It's sad to see that issue is not resolved for 3 years

**Comment by medikoo** [comment]
I've outlined an implementation proposal in main readme, through which we should tackle this issue finally.

PR's welcome!

**Comment by scadu** [comment]
@medikoo considering the issue is opened for a while already, I'll take a chance to work on this.

**Comment by medikoo** [comment]
@scadu that'll be great! I believe many users are waiting for this
