### ISSUE TITLE
Fix "Cannot read property 'path' of undefined" error in unit test suite

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3559]
# This is a Bug Report

## Description

Currently we're getting an error in out unit tests (see this build: https://travis-ci.org/serverless/serverless/jobs/228828787#L1079).

It seems like smth. is off with our async promise handling.

**Comment by helenyau0** [comment]
Hi there! I would like to take this on if it's okay. I have read the contributing guidelines.

**Comment by pmuens** [comment]
Awesome 🎉 ! Thanks for reaching our @helenyau0 👍 

Let us know if you need any help!
