### ISSUE TITLE
Support for Serverless.JSON 

### ISSUE THREAD

**Issue by kuashe** [serverless/serverless#3566]
# This is a Feature Proposal
JSON support as Serverless config file (Serverless.json instead of Serverless.YML)
## Description

* Using YML feels awkard , most of the usage of lambda are done with NodeJS and Node mostly uses JSON file for configuration (Webpack, Grunt , package.json etc....)
Using YML doesn't feel right
* Most examples provided by AWS for cloudformation are using JSON ( examples here 
[AWS Labs](https://github.com/awslabs)

Similar or dependent issues:

This feature was already proposed but got lost in the different release [Optionnal Serverless.JSON](https://github.com/serverless/serverless/issues/1900)

**Comment by HyperBrain** [comment]
AWS currently changes its CF documentation to contain both JSON and YAML snippets, e.g. http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

YAML has a lot of advantages over JSON, e.g. using comments, assigning multiline strings to a property in a readable way.

According to the YAML specification (see http://yaml.org/spec/1.2/spec.html#id2759572):

> YAML can therefore be viewed as a natural superset of JSON, offering improved human readability and a more complete information model. This is also the case in practice; every JSON file is also a valid YAML file.

So, imo, there is no point of explicitly supporting JSON. If the parser is compliant it should be possible to write the serverless.yml as plain JSON and everything should continue to work.

**Comment by DavidWells** [comment]
> Using YML feels awkward

I felt this too when starting to use serverless. A solid IDE with yaml support / indentation support does wonders here. I recommend atom for all your yaml needs =)

Ultimately though, I agree with @HyperBrain. YAML is much more flexible than JSON (even if it is harder to parse / write to with all those comments)

@kuashe if you want to use JSON, you can do so with something like https://www.npmjs.com/package/json2yaml and compile that down to YAML before running `sls deploy`

here is an example of how that would work in package.json

```json
{
  "scripts": {
      "predeploy": "json2yaml ./serverless.json > ./serverless.yml",
      "deploy": "serverless deploy",
   }
}
```

**Comment by pmuens** [comment]
@kuashe thanks for the proposal 👍 

I agree with @HyperBrain and @DavidWells here.

YAML is really a pain sometimes du to its idiosyncrasies.
However it provides some very cool enhancements which are not supported in plain JSON.

We had some plans to support JSON in the Serverless core but abandoned it due to technical debt and lack of interest within the community.

A solution could be to provide this via a plugin. Where the JSON is parsed into YAML and vice versa. Shouldn't be too hard to pull off.

**Comment by HyperBrain** [comment]
@pmuens There is no need for a plugin at all! As I wrote in my comment above, a JSON file is a valid YAML in any case (per definition).
You just have to write a JSON service definition and save it as `serverless.yml`. If the contents are valid JSON it will work out of the box. Here is a test I did with the JSON service definition:

Contents of the `serverless.yml`:
```
{
  "service": "sls-test-project",
  "provider": {
    "name": "aws",
    "runtime": "nodejs4.3",
    "stage": "dev",
    "region": "us-east-1",
    "memorySize": 512,
    "timeout": 15,
    "vpc": {
      "securityGroupIds": [
        {
          "Fn::ImportValue": "${self:custom.networkStack}-PrivateSG"
        }
      ],
      "subnetIds": [
        {
          "Fn::ImportValue": "${self:custom.networkStack}-PrivateSubnet1"
        },
        {
          "Fn::ImportValue": "${self:custom.networkStack}-PrivateSubnet2"
        }
      ]
    },
    "iamRoleStatements": [
      {
        "Effect": "Allow",
        "Action": [
          "dynamodb:*"
        ],
        "Resource": [
          {
            "Fn::Join": [
              "/",
              [
                {
                  "Fn::Join": [
                    ":",
                    [
                      "arn:aws:dynamodb",
                      {
                        "Ref": "AWS::Region"
                      },
                      {
                        "Ref": "AWS::AccountId"
                      },
                      "table"
                    ]
                  ]
                },
                {
                  "Ref": "TestDynamoDbTable"
                }
              ]
            ]
          }
        ]
      }
    ],
    "stackTags": {
      "environment": "${opt:stage, self:provider.stage}",
      "application": "${self:service}",
      "product": "something"
    },
    "environment": {
      "SERVERLESS_PROJECT_NAME": "${self:service}",
      "SERVERLESS_PROJECT": "${self:service}",
      "SERVERLESS_STAGE": "${self:custom.stage}",
      "SERVERLESS_REGION": "${self:custom.region}",
      "TEST_TABLE_NAME": {
        "Ref": "TestDynamoDbTable"
      }
    }
  },
  "plugins": [
    "serverless-offline",
    "serverless-webpack",
    "serverless-plugin-warmup",
    "serverless-aws-alias"
  ],
  "custom": {
    "stage": "${opt:stage, self:provider.stage}",
    "region": "${opt:region, self:provider.region}",
    "networkStack": "stashimi-${self:custom.stage}",
    "newService": "${self:}",
    "dev": {
      "testvar": "test-${self:custom.stage}"
    },
    "prod": {
      "testvar": "test-${self:custom.stage}"
    },
    "webpack": "./webpack.lambda.config.js",
    "webpackIncludeModules": true
  },
  "functions": {
    "testfct1": {
      "description": "Echo function echoes alias",
      "handler": "handlers/testfct1/handler.handle",
      "warmup": true,
      "events": [
        {
          "http": {
            "method": "GET",
            "path": "/func1"
          }
        }
      ]
    }
  },
  "resources": {
    "Resources": null,
    "Outputs": null
  }
}
```

This works as expected... It would be picky to just build a plugin for existing functionality just because I do not like the file extension 😕
