### ISSUE TITLE
Add project level support for .serverlessrc

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3573]
# This is a Feature Proposal

## Description

PR #3558 recently added support for a `.serverlessrc` file at the global level. We should also add support for this file at the project level. Project level values should supersede global values if they both exist.  This feature will be useful for the upcoming Serverless Platform release to allow users to specify different accounts for different projects if necessary.

**Comment by dougmoscrop** [comment]
if you just use `rc` to load it it does the lifting for you as well as supporting environment variables, command lines, etc.

**Comment by brianneisler** [comment]
Awesome! Thanks for the great tip @dougmoscrop!

**Comment by brianneisler** [comment]
This was introduced with the login command #3558. Closing...
