### ISSUE TITLE
DX: Cleaner stack traces

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3577]
This is an idea for cleaner stack traces pointing directly to where errors exist.

https://github.com/sindresorhus/clean-stack

```js
console.log(error.stack);
/* Before
Error: Missing unicorn
    at Object.<anonymous> (/Users/sindresorhus/dev/clean-stack/unicorn.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
*/
```

```js
console.log(cleanStack(error.stack));
/* After
Error: Missing unicorn
    at Object.<anonymous> (/Users/sindresorhus/dev/clean-stack/unicorn.js:2:15)
*/
```

I'm playing around with this idea right now. 

I would love to hear feedback from the community.

Any potential downsides to this?

**Comment by pmuens** [comment]
Nice idea! Most of the time I'm also staring at the traces struggling to figure out where it breaks...

We've recently changed stack traces to be longer based on @erikerikson request in https://github.com/serverless/serverless/pull/3149

Maybe we could have the best of both worlds and enable short stack traces by default and long stack traces through a config / env var.

**Comment by DavidWells** [comment]
Yeah maybe the default is 

- showing shorter clean stack traces for every error
- showing verbose (infinite traces https://github.com/serverless/serverless/issues/3579) with the `SLS_DEBUG` on

**Comment by pmuens** [comment]
@DavidWells that sounds like a good plan to me 👍

**Comment by erikerikson** [comment]
Interesting.  The problem that drove me to enable long stack traces is that the first portion of the trace was often completely uninformative due to the use of promises.  Specifically, it never gave me the serverless framework code that I needed for context to understand the bug and/or to start debugging from.  Perhaps the short version could be produced by searching the long stack trace for the first entry that is actually serverless framework or plugin code (as opposed to dependency code) to provide that value without the verbosity?

**Comment by erikerikson** [comment]
The notion ^ would be that our code would try to identify the relevant error and if our implementation doesn't cover your case, you can use SLS_DEBUG to enable a full listing so you can use your more capable and general purpose brain.

**Comment by eahefnawy** [comment]
@DavidWells what you think of this?
https://github.com/AriaMinaei/pretty-error

**Comment by DavidWells** [comment]
@eahefnawy I'm more of a fan of https://github.com/sindresorhus/clean-stack b/c its what is used for ultra simple error logs in the ava testing CLI https://github.com/avajs/ava#magic-assert

https://github.com/avajs/ava/blob/master/package.json#L111

**Comment by eahefnawy** [comment]
@DavidWells agreed. clean-stack is a lot simpler. I like the format of pretty-errors though, I wish we could mix them together somehow! 😅

**Comment by medikoo** [comment]
Closing as it was probably addressed in best possible way with https://github.com/serverless/serverless/pull/6502

Now we show stack traces only for programmer errors (so unexpected crashes that in all cases signal a bug) or when user has set `SLS_DEBUG`.
In all other cases we show only error message which is expected to be meaningful enough (if it's not it's an error reporting bug)
