### ISSUE TITLE
DX: Bump stack trace limit to infinity

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3579]
# This is a Feature Proposal

## Description

Our stack traces in our error reports are often partial traces because the default in node is a measly 10 lines. It seems acceptable to incur the performance cost of bumping our stack trace limit to Infinity so that our stack traces are complete when an error occurs. This will give us much better error reporting with the recent addition of error tracking in PR #3564 and help users deliver better traces when reporting errors/bugs.

```
Error.stackTraceLimit = Infinity;
```

**Comment by pmuens** [comment]
👍 

Refs https://github.com/serverless/serverless/issues/3577 and https://github.com/serverless/serverless/pull/3149

**Comment by DavidWells** [comment]
I think raven (aka sentry tracking) will take care of this for us: https://github.com/getsentry/raven-node/blob/514159d8b2bf173ed70beafba786a1087c7ceaa5/index.js#L10

**Comment by pmuens** [comment]
Should we rely on the sentry package here? Or should we also add this config explicitly in Serverless so that it's still around if we decide to e.g. change the error reporting package.

**Comment by HyperBrain** [comment]
The current sentry configuration only sets up the default global exception handler anyway (with raven.initialize()). This captures unhandled exceptions by default, but not unhandled rejections. If you want to propagate unhandled rejections to Sentry too, you'd have to explicitly enable the unhandled rejection handler in raven:
https://docs.sentry.io/clients/javascript/usage/#promises

You have to define/overwrite the Bluebird unhandled rejection handler explicitly and call `Raven.captureException()` in there.
