### ISSUE TITLE
Intro video is out of date.

### ISSUE THREAD

**Issue by richburdon** [serverless/serverless#3588]
# This is a (Bug Report / Feature Proposal)

Bug

## Description

the intro video seems out of date: 

1). an event file isn't created (just handler.js and serverless.yml)
sls create -t aws-nodejs

2). the deploy command doesn't create an endpoint.
sls deploy function -f hello

Service Information
service: aws-nodejs
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  hello: aws-nodejs-dev-hello

3). the "get started" link dumps you into a huge learning curve that had me exit for when I have a weekend free.

## Additional Data

1.13.0
OS/X 10.12.4

**Comment by pmuens** [comment]
Thanks for the pointer @richburdon 

Closing this for now since we're working on an update regarding this.
