### ISSUE TITLE
"Cannot read property 'LogicalResourceId' of null" (export in use)

### ISSUE THREAD

**Issue by adrienjt** [serverless/serverless#3589]
# This is a Bug Report

## Description

I created a stack with CloudFormation Outputs in the resource section of the serverless.yml. The outputs are in use by another stack. When I run `serverless remove -v`, I get the following error message:
`Cannot read property 'LogicalResourceId' of null`
The expected message (the one shown in the CloudFormation console) would be:
`Export my-output-export-name cannot be deleted as it is in use by my-other-stack`

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1

**Comment by pmuens** [comment]
Interesting. Thanks for openign @adrienjt 

I assume you use `Fn::ImportValue` to import the `Output` in another stack, right?

**Comment by adrienjt** [comment]
Yes, that's correct. And I understand that protects the export from deletion. It's just the error message that's incorrect and confusing.
This is one of a few errors (which unfortunately I can't recall in detail) where I've had to look at the CloudFormation log directly to understand what was going on.

**Comment by pmuens** [comment]
@adrienjt thanks for the feedback.

Yes, error messages are really a DX issue. We're currently working on some fixes to improve the overall DX / UX.

**Comment by medikoo** [comment]
This specific error was fixed with https://github.com/serverless/serverless/pull/7665

Otherwise we already have error handling significantly improved with https://github.com/serverless/serverless/pull/6502 and https://github.com/serverless/serverless/pull/7335

Closing
