### ISSUE TITLE
DX: Add stage and region support for create command

### ISSUE THREAD

**Issue by bluszcz** [serverless/serverless#3597]
Can't find a way to create the stack in other region than eu-east-1. 

I tried to create projects using various options, following https://en.wikipedia.org/wiki/Principle_of_least_astonishment and 

```serverless create --region eu-west-1 --template aws-python3``` but this created project in the us-east-1.

When I try to change it later - 

```
(p3) ➜  rafal serverless info

  Serverless Error ---------------------------------------

     Stack with id aws-python3-dev does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.5.0
     Serverless Version: 1.12.1

(p3) ➜  rafal
```

**Comment by pmuens** [comment]
@bluszcz thanks for opening 👍 

You can overwrite the region setting in the `serverless.yml` file (see: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/#serverlessyml-reference) or through the option when deploying (e.g. `serverless deploy --region: eu-west-1`).

Please let us know if this resolves your problem. Thanks!

**Comment by bluszcz** [comment]
I think that your solution answers "how to deploy in other region" than "how to create in other region". How I can make serverless create directly creating stack in other region?

**Comment by dougmoscrop** [comment]
create doesn't create the stack, it creates the local source files with no region specified (so the region is default -- us-east-1). you have to deploy the service first.

`create` could maybe have been better named `new` or `init`

I think you are doing this:

```
serverless create [...]
serverless info
```

you need to do either:

```
serverless create [...]
serverless deploy --region eu-west-1
serverless info --region eu-west-1
```

or

```
serverless create [...]
{{ edit serverless.yml file to set provider.region to 'eu-east-1' as new default region }}
serverless deploy
serverless info
```

**Comment by pmuens** [comment]
Closing this stale issue for now.

Thanks @dougmoscrop for jumping in and providing more context on the overall process Serverless uses behind the scenes. That should explain a lot.

@bluszcz thanks for bringing this up 👍
