### ISSUE TITLE
Specifying multiple methods for an endpoint of a function is broken

### ISSUE THREAD

**Issue by Nopik** [serverless/serverless#360]
Try to register single function as `hello/world` `GET` and `POST` endpoints.

**Comment by ac360** [comment]
:+1: This is a priority.  Will get this handled ASAP.  After looking at the issue, we will need to change the `s-function.json` slightly so that the endpoints property is an array.

**Comment by eahefnawy** [comment]
fixed! closing...

**Comment by zuhair-naqvi** [comment]
Can you please publish this to NPM? Can't do anything useful without it!
