### ISSUE TITLE
Add flag / config to disable CLI colors

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3608]
# This is a Feature Proposal

## Description

Some users have problems with the colored Serverless output on their terminal since they e.g. use background colors or other enhancements.

We should add a CLI flag or config variable where users can opt out of CLI coloring and everything will be just displayed in white.

Originally brought up by @schickling (thanks for that 👍)

**Comment by kyanh-huynh** [comment]
our serverless command is executed by cicd tool, and there is no reason to have color in log files. please have an option to disable color.

**Comment by pmuens** [comment]
> our serverless command is executed by cicd tool, and there is no reason to have color in log files. please have an option to disable color.

Thanks for the feedback @kyanh-huynh 👍. Do the colors make it harder / impossible to read the log output?

**Comment by HyperBrain** [comment]
@pmuens This is also true for us. In the logs of your build servers it is a bit annoying that the log files are polluted with non-readable characters.

Implementation hint: As far as I know, `chalk` is used in Serverless, so just setting `chalk.enabled = false` on the required module should do the trick for all outputs as each require just loads the cached node module. I would propose a `--no-color` switch.

**Comment by RafalWilinski** [comment]
Is it just me or is it already implemented? Can't find `no-color` in code, though. This might be related to my shell settings, can anyone confirm?

![screen shot 2017-09-13 at 16 30 23](https://user-images.githubusercontent.com/3391616/30383055-0c791e52-98a1-11e7-975b-be5610453dc5.png)

**Comment by HyperBrain** [comment]
Just did a fulltext search in `./lib` and did not find any occurence.

**Comment by RafalWilinski** [comment]
I also couldn't find anything in source code but I've just tried again with casual `bash` in `Terminal.app` and it works exactly the same. 🤔

**Comment by RafalWilinski** [comment]
Seems that https://github.com/chalk/supports-color#info which is `chalk` direct dependency "obeys the `--color` and `--no-color` CLI flags".

**Comment by pmuens** [comment]
Thanks for the feedback @HyperBrain and thanks for looking into this @RafalWilinski 👍

I like that! Look like it's a simple fix 💪!

**Comment by brianneisler** [comment]
Seems like we just need to document this feature. Other than that seems
like this is already working.
