### ISSUE TITLE
Automate release process through CI system

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3610]
# This is a Feature Proposal

## Description

Our release process which is written down [here](https://github.com/serverless/serverless/blob/master/RELEASE_CHECKLIST.md) should be automated through e.g. a CI system which tests everything and then published to `npm` when a new tag is released.

This will make the release process less manual and error-prone.

/cc @brianneisler @eahefnawy

**Comment by brianneisler** [comment]
Setup the serverless-main npm account to publish and update icon on npm
