### ISSUE TITLE
Remove provider validation in Service.js file

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3611]
# This is a Feature Proposal

## Description

Since more and more 3rd party providers write plugins to integrate with Serverless we should definitely remove the `provider` property validation in the `Service.js`file ([here](https://github.com/serverless/serverless/blob/43925a373e243d48567914c33622841e037ab212/lib/classes/Service.js#L82)).

Otherwise we need to get PRs for each and every provider we support and this would slow down the whole process and may cause demotivation in the long run.

Originally brought up by @alexellis and @ngtuna

/cc @brianneisler @eahefnawy

**Comment by alexellis** [comment]
Thanks - it would also be good to have some provider-level documentation as for the time-being it's primarily aimed at generic plugins. A provider against a stubbed-out/fake http endpoint would be ideal.

https://github.com/alexellis/faas/issues/71

**Comment by pmuens** [comment]
Nice! Thanks for the feedback @alexellis 👍

**Comment by sebgoa** [comment]
Definitely +1 on this as we now have a plugin for github.com/kubeles/kubeless

**Comment by sebgoa** [comment]
@pmuens what do you want to see for this issue ? Our provider is getting into a reasonable shape. We can add it to the list for the verification, or we can help remove the verification.

If you tell us what you want we can probably help.

It is weird for us to write kubeless functions with `provider: google` :)

**Comment by pmuens** [comment]
Hey @sebgoa thanks getting back 👍 

I'd say that we simply remove the check for the provider in the `Service.js` file.
It's really annoying that you guys have to choose from one of the existing provider definitions.

The only important thing to keep in mind is that the provider plugin should stick to the provider name to keep it consistent.

@sebgoa do you want to PR the change or should I remove it?

**Comment by sebgoa** [comment]
@pmuens it might be faster if you have time to do it :)

**Comment by pmuens** [comment]
> @pmuens it might be faster if you have time to do it :)

Alright. Sure thing @sebgoa 👍 

Just PRed the necessary change with https://github.com/serverless/serverless/pull/3941

/cc @alexellis @ngtuna
