### ISSUE TITLE
IAM Group and Role?

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#362]
Is it an error that both an IAM group and an IAM role are created per project (and per stage)?

**Comment by thedevkit** [comment]
+1

You definitely need the roles, but I don't see the need to create groups without users known ahead of time.

**Comment by visualasparagus** [comment]
Yes, it seems like an unnecessary IAM resource to me. Anyone know if this is required for anything?

**Comment by ac360** [comment]
Thanks @visualasparagus This will be removed in `v0.1.0`.  BTW - I really appreciate your support and feedback @visualasparagus :)
