### ISSUE TITLE
Deploy with --package option not working when using relative path

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3621]
# This is a Bug Report

## Description

`serverless deploy -p foo` is not working (the package directory is not considered during deployment).

Steps to reproduce:

1. Run `serverless deploy`
2. Copy `.serverless` directory and rename it to `foo`
3. [**optional:** (just used to showcase that Serverless doesn't care): Open up the update CloudFormation template and enter some weird characters so that it's invalid JSON]
4. Run `serverless deploy -p foo`
5. Serverless will start the deployment and immediately returns w/o monitoring the stack update process

**Comment by HyperBrain** [comment]
@pmuens  Could be solved by calling the CF template validation stack function just before beginning to start the stack update. AWS proposes this procedure to ensure that templates are usable upfront.

See here for the CF REST API: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html

**Comment by pmuens** [comment]
@HyperBrain that sounds like a good plan.

Don't know if the description is misleading but the main problem is that Serverless won't pick up the package directory I specify with `-p`. So for some reason Serverless immediately starts and finishes the "Update Stack" process and the directory is not considered during deployment.

**Comment by HyperBrain** [comment]
@pmuens Ok. I think for the `-p` bug there is already an entry (`--package` works). Maybe we should track the invalid JSON issue here (I think this is indeed an issue).

**Comment by pmuens** [comment]
> I think for the -p bug there is already another issue entry (--package works)

Thanks for the pointer. I'll try this again with `--package` to see if it works. Unfortnuately I couldn't find the other, related issue.

> Maybe we should track the invalid JSON issue here (I think this is indeed an issue)

I've just opened up another issue for that --> #3635

**Comment by pmuens** [comment]
Ok. So it looks like this bug has been resolved in the meantime.

Following the steps in the description I'm no longer able to reproduce it. I'll close this since it's no longer a problem 🎉

/cc @eahefnawy 

**Aside:** Not sure how this exactly works behind the scenes, but it looks like Serverless copies my `foo` directory and renames it to `.serverless` which is then used for deployment (because I can see the same syntax errors in the artifacts of the `.serverless` directory which I introduced on purpose in the artifacts of the `foo` directory).

**Comment by HyperBrain** [comment]
@pmuens Exactly. Under the hood the artifact (package) directory is a persisted .serverless directory, which is used to resume the deploy operation from a previous package operation by copying it to .serverless first.

So your (broken?) artifacts will be reused and seeing the syntax error is expected in that case.

PS: We use the package mechanism since it exists without issues on our CI/CD servers.

**Comment by pmuens** [comment]
That makes sense!

Thanks for the clarification @HyperBrain 👍. Also great to hear that it's battle-tested 💣.
