### ISSUE TITLE
clear

### ISSUE THREAD

**Issue by simonhjoerg** [serverless/serverless#3628]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
@simonhjoerg thanks for opening.

Seems like you've submitted the Issue report a little bit too early.

Could you fill out the Issue form? Thanks!

**Comment by simonhjoerg** [comment]
yeaah was browsing issues and ended up opening one by accident :)

Ill close this off, move along nothing to see here

**Comment by pmuens** [comment]
@simonhjoerg thanks for the clarification! 😄 

Let us know if you face any problems / need help...
