### ISSUE TITLE
Deploy on another stage fails when api key is present

### ISSUE THREAD

**Issue by shatgupt** [serverless/serverless#3631]
# This is a (Bug Report / Feature Proposal)
Bug
## Description
I had an API deployed on dev stage with api keys. When I tried to deploy the same api with stage prod, it failed with error:
```
...
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
CloudFormation - CREATE_FAILED - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
...
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
...
Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayApiKey1
     - dev-key already exists in stack arn:aws:xxxx
```

Serverless should skip creating keys if they exist.

## Additional Data
```
OS:                 linux
Node Version:       6.10.3
Serverless Version: 1.12.1
```

**Comment by HyperBrain** [comment]
Seems that account key logical ids are account global.
@eahefnawy We should add a randomizer to the api key in a similar way as it is done with the `ApiGateway::Deployment` resources.

**Comment by shatgupt** [comment]
I had a config like:
```
apiKeys:
    - dev-key
```
Figured out that I can use:
```
apiKeys:
    - ${self:provider.stage}-key
```

But I think bug still applies if I want to have same keys.

**Comment by HyperBrain** [comment]
@shatgupt As a workaround your solution should work. Nevertheless it should be solved in SLS so that name clashes are prevented at the root.

**Comment by pmuens** [comment]
Thanks for reporting @shatgupt and thanks for jumping in @HyperBrain 

We have this whole API Key topic on our TODO-List since it's currently broken due to lack of "full CloudFormation support".

Right now you can create the key but cannot associate it to a usage plan (we've disabled our integration tests for that because of this). Although this might have changed since the last time we looked into it.

**Comment by pmuens** [comment]
Closing since this issue is quite old and there's a potential workaround in the thread.

Additionally we published lots of new versions with fixes which should address this. Feel free to re-open if this is still a problem.

**Comment by chrisdpeters** [comment]
FYI, I prefer using the `--stage production` key in the CLI to deploy to production. My version of the workaround had to look like this:

```yaml
apiKeys:
    - ${opt:stage}-key
```

**Comment by ftruzzi** [comment]
How do you make the above workarounds work when you have to set your endpoints private and therefore associate usage plans to your API keys?

You would have to do e.g.

```yaml
  apiKeys:
    - ${opt:stage}-key
  usagePlan:
    - ${opt:stage}-key:
        throttle:
          burstLimit: 200
          rateLimit: 1000
```

but AFAIK you can't use variables in keys. Any ideas? Maybe this issue is worth reopening?
