### ISSUE TITLE
DX: Validate CloudFormation JSON before deploying

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3635]
# This is a Feature Proposal

## Description

It would be nice if the `JSON` of the `CloudFormation` file is validate before deploying (as brought up by @HyperBrain in https://github.com/serverless/serverless/issues/3621#issuecomment-301887425).

This way we can save the roundtrip to AWS and display a more user-friendly error message.

**Comment by DavidWells** [comment]
Yes please!

We need to validate cloud formation and known serverless properties to save on this slow feedback loop from remote errors

This will speed up development cycles tremendously

**Comment by hassankhan** [comment]
I've created a WIP branch [here](https://github.com/hassankhan/serverless/tree/validate-cf-template-locally), does this seem to be what you guys had in mind?

**Comment by pmuens** [comment]
Super nice! Thanks for the PR @hassankhan 👍

**Comment by hassankhan** [comment]
Will do later tonight! 👍
