### ISSUE TITLE
Sls remove fails when custom domain with base path mappings used in APIG

### ISSUE THREAD

**Issue by shatgupt** [serverless/serverless#3638]
# This is a (Bug Report / Feature Proposal)
Bug
## Description
I tried to remove a stage which had a custom domain with base path mappings used in API Gateway. It failed with error:
```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
Serverless: Deployment failed!

Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayRestApi
     - Deleting RestApi xxxxx failed. Please remove
     all base path mappings related to the RestApi in your
     domains: abc.xyz.com.
```
I understand that may be Serverless doesn't yet support removing base path mappings, so I removed the base path mappings myself from AWS console. Now running `sls remove` fails complaining S3 bucket doesn't exist:
```
Serverless: Getting all objects in S3 bucket...

Serverless Error ---------------------------------------

     The specified bucket does not exist
```
So now I can't cleanly remove my stack.
## Additional Data
```
Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.10.3
     Serverless Version: 1.12.1
```

**Comment by dougmoscrop** [comment]
My plugin will remove (and create) the base path mapping for you https://github.com/dougmoscrop/serverless-plugin-custom-domain

**Comment by pmuens** [comment]
Thanks for linking the plugin @dougmoscrop 👍 

> I'm not sure if serverless should remove things that it didn't create?

Serverless should always manage only the resources which can be found in the generated CloudFormation stack, but nothing more. Otherwise the stack representation might get out of sync with the actual deployment.

The `BasePathMapping` could be added via the resource section with this AWS CloudFormation template: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-basepathmapping.html

This way it will be merged into the generated template and Serverless will take care of the creation and removal.

**Comment by lirantal** [comment]
@pmuens agree that sls should only remove what it is responsible for, but I would expect the deploy/remove to be idempotent, so even if it failed on the api gateway base mapping stuff which was removed manually by the user, the next `sls remove` invocation should continue with removing the service even though it doesn't find the s3 bucket which is the first step that it fails on.

**Comment by pmuens** [comment]
Closing since this is a stale issue and there are solutions (via plugins) available.

Futhermore, as stated above Serverless is only responsible for the resources it directly managed. Everything externally is out of the scope for the Framework.
