### ISSUE TITLE
Expose a `IS_LOCAL` environment variable if running via `sls invoke local`

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#3639]
# This is a Feature Proposal

## Description

When testing code locally it is sometimes important to know whether the code is ran locally or in the AWS Lambda environment. The three main reasons for us are:
* Typically we enable long stack traces for Bluebird in our code. However, if our Lambda function is ran via `sls invoke local` this isn't possible and crashes with a `Error: cannot enable long stack traces after promises have been created` (which is caused by Serverless also using Bluebird promises). When testing code locally I have to comment out that section in our code! 😱 
* Our errors are typically reported to [Sentry](https://sentry.io), a third party service for error tracking. We never want to collect errors raised in a local developer environment. 
* We often use a local Redis server when running code locally, as our real services are hidden inside of a VPC.

A possible workaround would be to create a dedicated "local" stage and have specific configuration for that. Certainly an option, but sometimes I'd prefer a way of quickly checking in code if my function runs locally or on AWS. Hence my suggestion: **Introduce a new `IS_LOCAL` or `SERVERLESS_INVOKE_LOCAL` environment variable** that is only set when the code is invoked via `sls invoke local`. This would be similar to the [Serverless Offline Plugin](https://github.com/dherault/serverless-offline) which sets `IS_OFFLINE`.

This would enable code like this:
```js
if (process.env.IS_LOCAL) {
  console.log("Running locally!");
}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2

**Comment by DavidWells** [comment]
I like this!

Are there any potential downsides/clashes this can run into?

Also, eventually we will need to support this in multiple runtimes (Python, Java etc). Any thoughts on how we can achieve this?

**Comment by HyperBrain** [comment]
@DavidWells Already achieved 😸 . My PR just sets the variable in the common environment setter of the invoke local command. That will affect any AWS invoke local invocation - so to say all runtimes.

**Comment by pmuens** [comment]
Awesome! Thanks for working on this @HyperBrain 👍

**Comment by HyperBrain** [comment]
> I have also explicitly set BLUEBIRD_LONG_STACK_TRACES=1 in my env vars.

I think you have to enable long stack traces only if _not_ running locally, because `serverless invoke local` already does that. So, you should put the variable assignment into a condition `!IS_LOCAL`.
