### ISSUE TITLE
Feature Requests (aka questions, wishes and ideas)

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#364]
Before I put down these thoughts, I do want to say that this project is **GREAT** and I've been anxiously awaiting JAWS version 1.4 / Serverless version 0.1. Thanks for the amazing work! I hope these ideas and thoughts don't make it seem otherwise.

**1- CORS** allow CORS support per module by adding a CORS object to the `s-module.json`. This could create an OPTIONS method with a Mock Integration Request and Integration Response Headers. Similar to what the console does with the 'Enable CORS' button for an endpoint.

**2- MOCKS** allow inclusion of Mock Integration requests via the `s-function.json` in order to quickly stub a project via API Gateway while development continues.

**3- SWAGGER** possibility to generate a Swagger description of the API for documentation and distribution. would require additional fields in the `s-function.json` file though and could be cumbersome I suppose.

**4- COMPLEX RESOURCES** is it or will it be possible to generate multiple endpoints for the same function or nested resources? so for instance module user, function GET /user, GET /user/login, GET /user/{username} or function POST /user, POST user/createWithArray, etc (see http://petstore.swagger.io/)

**Comment by Nopik** [comment]
4) It is possible to define multiple endpoints for 1 lambda, in the `s-function.json` just define many keys for `endpoints`.

**Comment by visualasparagus** [comment]
by multiple endpoints you mean GET/POST/OPTIONS/PUT/DELETE for the same url or also for variations on the same url (for example /user) such as user/login, user/createWithArray?

**Comment by eahefnawy** [comment]
@visualasparagus yep you can now set any number of methods for the same endpoint. `s-function.json` is super flexible right now.

We'll definitely add CORS support, and maybe mocking. As for Swagger, I'm still not sure at this point.

Thanks for pointing all that out!

**Comment by visualasparagus** [comment]
Thanks!

Seems like Swagger is better left as a plugin anyway.

**Comment by joostfarla** [comment]
CORS support is available in a plugin I just released: https://github.com/joostfarla/serverless-cors-plugin

**Comment by madmod** [comment]
👍 
I personally really like mock requests to create simple dynamic HTML and javascript with velocity templates. It gives me some dynamic content with stage variables and user context and a pretty rich template language without the cost and latency of a lambda function to render it. Right now deploying these along with the rest of my Serverless endpoints is a pain. (really makes me appreciate Serverless 😉 )

**Comment by HyperBrain** [comment]
@madmod You can deploy SLS endpoints as MOCK endpoint types and serve the content via `s-templates.yaml` in a way that you also can easily use and embed VTL. Just set the endpoint.type to "MOCK" and responseTemplates to the template you defined, e.g. "$${myTemplate}"

**Comment by madmod** [comment]
@HyperBrain Excellent thanks!

**Comment by flomotlik** [comment]
Thanks for all the feedback in this issue. We're currently looking into which features we want to support in the next version of Serverless and this definitely helps a lot. I'm going to close this issue for now, but it did influence our planning which we will release soon.
