### ISSUE TITLE
Remove "traverse" package and use lodash utils where traverse was used

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3641]
# This is a Feature Proposal

## Description

#3504 includes the last pieces of code which rely on the `traverse` package.

While this package has no dependencies it should be removed (last update was 5 years ago --> https://github.com/substack/js-traverse) and the code should be refactored so that lodash utilites are used.

**Note:** `traverse` was recently replaced in the `Variables.js` file. The new implementation can be found here: https://github.com/serverless/serverless/blob/f4f2cf99af27098bd0444bc7b918e0d468a65ec6/lib/classes/Variables.js#L48-L61

**Comment by eahefnawy** [comment]
Thanks @exoego 🙌
