### ISSUE TITLE
Contributing / Development docs

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3651]
# This is a Feature Proposal

## Description

I'm a first-time contributor, and on the surface I'm not 100% sure of where to start. It would be awesome if there was some documentation on the internal architecture of Serverless and how all the (internal) plugins hook into Serverless' lifecycle.

**Comment by pmuens** [comment]
Awesome! Thanks for the feedback @hassankhan 👍 

I agree. That's always smth. I'm also looking for when trying to contribute to an OSS project.
We should definitely get a doc out there which also includes a roadmap, etc. We're already working on that BTW.

Regarding plugin I'd say that the docs are currently the best way to understand the plugin system:

https://serverless.com/framework/docs/providers/aws/guide/plugins/

You might also want to take a look into the source code with Sourcegraph to browse through all the code and understand the relations: https://sourcegraph.com/github.com/serverless/serverless

`bin/serverless` is basically the entrypoint where you should start.

I'll add a `needs-feedback` label since others might face the same problems and have some feedback what this document should include.

**Comment by horike37** [comment]
just an idea, it would be great if there is a picture about execution flow with code of Serverless.
This may make it easy for beginers to understand code.

**Comment by hassankhan** [comment]
@horike37 stole the words from my mouth, the plugins documentation that @pmuens linked is great for developing plugins as external NPM packages, but they're not great at documenting the internal flow of Serverless.

**Comment by HyperBrain** [comment]
Hmmm. I think code execution flow is only the first half of the way. The second and maybe more important part is the lifecycle and event graph. Due to the hook and lifecycle system (that the plugins implement and provide) the code execution graph would not necessarily help.

**Comment by hassankhan** [comment]
@HyperBrain Its that sort of explanation that isn't really mentioned anywhere in the docs. After browsing the source, I'm beginning to understand it. There a bunch of other things such as the compiled CF template, how the provider is selected etc. that just aren't that clear without a fair bit of time spent digging through code.

**Comment by HyperBrain** [comment]
Yes, you're right. I think all this basic stuff, that controls the SLS framework should be doc'd in a separate section, another one digging into the provide specific plugins (including an overview of the specific mechanisms used - like the compiled CF template).

So it should be something like this:
```
I. The framework - show how the basic framework works, from initializing, through loading the service and the plugins, the providers, up to starting the plugin/command selected.

II.  Docs for each provider
II.a. Overview - General information about how the provider will use the service data, build and deploy the artifacts, handles rollback, etc.
II.b. Lifecycle/Commands/Events - Detailed description of every command implemented by the provider with lifecycle graphs and declared events that can be hooked by other commands/plugins.
```

That's just a very rough idea, and there may be lots of subsections needed within the different main topics.

**Comment by hassankhan** [comment]
Also perhaps something like:

```
III.a. Unit Tests - Explain that unit tests should cover generating CF resource templates (generally).
III.b. Integration Tests - Explain how these are set up and run.
```

**Comment by DavidWells** [comment]
This is a great idea! I struggle sometimes with what hooks are available and when exactly they run.

Reviving these:
- https://github.com/serverless/serverless/issues/3671 
- https://github.com/serverless/serverless/pull/2821

**Comment by hassankhan** [comment]
Would also be nice to get some documentation regarding making AWS requests using `this.provider.request`, a big thanks to @HyperBrain for clueing me in.

**Comment by DavidWells** [comment]
Another comment on what hooks run when etc. 

> I did start to look into what it might take to write a plugin recently, but got bogged down by trying track down documentation around lifecycleEvents, and figuring out what I needed to hook into/override. #3464 (comment) via @iadknet 

Maybe it's time to revisit https://github.com/serverless/serverless/pull/2821

**Comment by DavidWells** [comment]
Visual documentation/output for where plugin hooks run can be very useful as a plugin author. 

This is somewhat related example from a wordpress theme engine https://genesistutorials.com/visual-hook-guide/.  It illustrates where third party devs can run/output code. Granted not a CLI tool but you get the idea.

**Comment by HyperBrain** [comment]
The **Serverless Lifecycle Cheat Sheet** is here: https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406

**Comment by medikoo** [comment]
We've improved documentation on internals and how to contribute in last months.

Check:
- [Framework Anatomy](https://github.com/serverless/serverless/blob/master/docs/anatomy.md)
- [How to contribute](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#how-to-contribute-to-serverless)
- [How to write tests](https://github.com/serverless/serverless/blob/master/test/README.md)

We also have pending other documentation organization improvements:
- https://github.com/serverless/serverless/issues/8085
- https://github.com/serverless/serverless/issues/8097

I'm going to close it, still we're open for any further specific suggestions and PR's that bring tem!
