### ISSUE TITLE
Provide partial local environment across providers

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3652]
# This is a Feature Proposal

## Description

https://github.com/serverless/serverless/pull/3642 Adds support for the `IS_LOCAL` environment variable during local invocations. However due to the nature of the invoke local implementation it's currently only available when using the `aws` provider.

The setting of the `IS_LOCAL` environment variable should be moved to the general `invoke local` plugin so that it's available across providers.

Thanks to @DavidWells and @HyperBrain who discussed this in https://github.com/serverless/serverless/pull/3642#issuecomment-302490452

**Comment by HyperBrain** [comment]
@pmuens You can assign this one to me - I will implement it in the next days then.

**Comment by pmuens** [comment]
@HyperBrain great! 🎉  Thanks for jumping into that!

I'll assign you. Looking forward to the PR!
