### ISSUE TITLE
Should empty array trigger warning?

### ISSUE THREAD

**Issue by dougmoscrop** [serverless/serverless#3655]
# This is a Question

## Description

https://github.com/serverless/serverless/blob/ddb99af627276d39858433f88b54608038e7b461/lib/classes/Variables.js#L343

`typeof []` === 'object' so this causes empty arrays to trigger a warning. Intended? Or worth a check for `!Array.isArray`)?

## Additional Data

* ***Serverless Framework Version you're using***: latest (Master)

**Comment by HyperBrain** [comment]
If this is not intended I would use lodash for the check and check for `_.isPlainObject() && !_.isEmpty()`. This would not be true for arrays then.

**Comment by pmuens** [comment]
Thanks for opening @dougmoscrop 👍 

🤔 not sure if this is intended. @eahefnawy do you know more?

**Comment by antogyn** [comment]
I use empty arrays sometimes in my config (e.g. for api keys on a particular environment) and I couldn't find a workaround for this warning.

**Comment by fivepapertigers** [comment]
I'm running into the same problem as @antogyn, specifically for API keys. More generally, an empty object or an empty array is often intentional, but we have our CI setup to fail on serverless warnings, because null or undefined values usually are not.

**Comment by alaz** [comment]
I am running into the same problem. I have

```
custom:
  aliases:
    dev: [ ]
    production: [ 'prod.domain.tld' ]
```

to populate CloudFront `Aliases` like so `Aliases: ${self:custom.aliases.${self:provider.stage}}`. And hence I see this warning in `dev` stage.

**Comment by medikoo** [comment]
I believe it was addressed with https://github.com/serverless/serverless/pull/6554
