### ISSUE TITLE
New HTTP/HTTP_PROXY integrations should not set default mapping templates

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#3658]
# This is a Bug Report

### Overview

The newly introduced APIG integration types HTTP and HTTP_PROXY are used, to forward requests
to HTTP endpoints, with or **without** APIG mapping.
The latter (which is the most common use case for these integration types) is not possible
with the current implementation, because Serverless (master branch) unconditionally adds
its default mapping templates to the endpoint.

### Sample

Set up an HTTP integration type endpoint, with https://sample.url/myfwd as target.
We assume here, that the target URI only can cope with `x-www-form-urlencoded` data,
and our endpoint just should delegate to this URI.

If you now call our endpoint with `Content-Type: x-www-form-urlencoded` the target
endpoint will receive the data as JSON, because SLS added a mapping for this content type,
that converts it to JSON. As a consequence the call is rejected by the target endpoint.

The expectation is, that with a default deployment of HTTP and HTTP_PROXY endpoints
no mapping templates are set on the endpoint method. In this case mappings should
only be set in place, if the user explicitly adds some to the endpoint definition.

### Solution

Serverless should not add any default mapping templates in case one of the HTTP or 
HTTP_PROXY integrations are selected. This will send the incoming request unchanged 
to the target endpoint - as is expected.

The other integration types are ok with default templates as they guarantee that a lambda
endpoint will work, regardless what you throw at it.

## Additional Data

* Serverless Framework Version: **current master**

**Comment by HyperBrain** [comment]
CC @eahefnawy

**Comment by arabold** [comment]
Yes, that was an oversight in my previous PR which added `http` and `mock`. Once a mapping template is set (in this case the `x-form-urlencoded`) its transformation will be applied and cannot be disabled via Serverless. The only way seems to _not_ set any default mappings by default as @HyperBrain suggests.
