### ISSUE TITLE
Allow Lambda CloudFormation Outputs to be exported

### ISSUE THREAD

**Issue by dstainer** [serverless/serverless#3661]
# This is a Feature Proposal

## Description

I would like the ability to export output variables generated during a deploy. In my specific situation, I'd like the ability to export the <lambdaFunctionName>LambdaFunctionQualifiedArn out as a stack variable for other cloud formation templates to use. 

For my use case, I'm specifically trying to get access to the fully qualified ARN with the version for reference in other resources maintained by another CloudFormation stack, hence the ability to export.

### Example

For example, assume my Lambda function is called HelloWorld. After the deploy you'd have the following output name and value

Name: <code>HelloWorldLambdaFunctionQualifiedArn</code>
Value: <code>arn:aws:lambda:&lt;region&gt;:&lt;aws-account-id&gt;:function:hello-world:10</code>

I would like the ability to export the value referenced by <code>HelloWorldLambdaFunctionQualifiedArn</code> variable from the stack.

As far as configuration goes you could do something like the following:

<pre>
functions:
  usersCreate: # A Function
    handler: users.create # The file and module for this specific function.
    description: My function # The description of your function.
    output: (this would be an optional configuration piece)
       export: true/false (default would be false)
       exportName: a String that allows for variable substitution, it could be defaulted 
       to stackName-stage-variable name or something like that as well
    ...
</pre>

Similar or dependent issues:
* Did not find similar/dependent issues

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2
* ***Operating System***: N/A
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Hey @dstainer thanks for opening!

You can use the resources section and append your own CloudFormation outputs you could then re-import via `Fn::ImportValue`.

Here's a link to our docs which show you how to do that: https://serverless.com/framework/docs/providers/aws/guide/resources/

That should solve your problem.

**Comment by dstainer** [comment]
Hi @pmuens. Thank you for responding to this issue. 

I'm not sure I'm understanding your suggestion completely. So I'm aware that you can create your own outputs in the resources section, and as a result you can have those outputs exported. 

But I'm not sure I understand how you would be able to export an output that was generated during the compilation/packaging of the function itself, that you don't have easy access to. Does that make sense? 

I'm going to see if I can do it via a plugin approach, I'll let you know the results.

Again thanks for responding!
Derek

**Comment by arabold** [comment]
The function ARNs are automatically exported as `<service>-<stage>-<function>-LambdaFunctionArn` as far as I know. So this can be imported in other projects easily. You also have access to the resources Serverless creates internally and can reference those. The respective Lambda function name is `<Function>LambdaFunctionArn`, e.g. something like `Ref:HelloWorldLambdaFunctionArn`.

The reason I'm not sure if the export is a built-in feature of Serverless is that we're using the [Serverless Alias Plugin](https://github.com/HyperBrain/serverless-aws-alias). It might be a feature of that.

**Comment by pmuens** [comment]
@arabold thanks for jumping in! 👍 

@dstainer the comment by @arabold above 🔝 explains how this could work. You can fin the table with all the resource logical ids [here](https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference).

**Comment by phstc** [comment]
Unfortunately, I couldn't follow the example 🐼

In my case I want to export the APIGW ServiceEndpoint, something like `https://123.execute-api.us-east-1.amazonaws.com/dev/` instead of a specific function ARN. How can I do that in the `serverless.yml/Resources/Outputs`?

**Comment by JustinTArthur** [comment]
@dstainer's original inquiry was for the qualified ARN (i.e. with version). This is often required in CloudFormation templating of CloudFront distributions. @pmuens, your suggestion doesn't solve how to refer to or infer this as far as I know. The logical IDs table you linked states name template as `{normalizedFunctionName}LambdaVersion{sha256}`, but doesn't document how one might get that sha256 within serverless.yml if it's even possible.

Unless this use case is covered somewhere, I don't think this should have been closed. This was also request by a few people in #2240, which was closed for unknown reasons.

**Comment by nford** [comment]
@pmuens this issue should not be closed, @dstainer could you re-open it? And if you found a solution please share. I am having this issue trying to export a layer to another service stack.

**Comment by ankon** [comment]
I hit this issue now as well, and didn't see any obvious change since this was filed that would give me a predictable name for either an output or the version so that I could create the output.

But, I managed to write a small plugin that seems to work:

```js
/**
 * @implements {import('serverless/classes/Plugin')}
 */
class ExportQualifiedFunctionArnsPlugin {
	/**
	 *
	 * @param {import('serverless')} serverless
	 */
	constructor(serverless) {
		this.serverless = serverless;
		this.provider = this.serverless.getProvider('aws');

		this.hooks = {
			'before:aws:package:finalize:mergeCustomProviderResources': async () => {
				// For all known functions that have a versionLogicalId: Export a ref to that.
				for (const functionName of this.serverless.service.getAllFunctions()) {
					const functionObject = this.serverless.service.getFunction(
						functionName,
					);
					if (!functionObject.versionLogicalId) {
						// No version for this function configured
						continue;
					}
					const outputName = `${this.provider.naming.getLambdaLogicalId(
						functionName,
					)}QualifiedArn`;
					if (!this.serverless.service.resources.Outputs) {
						this.serverless.service.resources.Outputs = {};
					}
					if (outputName in this.serverless.service.resources.Outputs) {
						// Output with this name exist, keep it.
						continue;
					}
					this.serverless.service.resources.Outputs[outputName] = {
						Value: {
							Ref: functionObject.versionLogicalId,
						},
					};
				}
			},
		};
	}
}

module.exports = ExportQualifiedFunctionArnsPlugin;
```

**Comment by yehonadav** [comment]
> I hit this issue now as well, and didn't see any obvious change since this was filed that would give me a predictable name for either an output or the version so that I could create the output.
> 
> But, I managed to write a small plugin that seems to work:
> 
> ```js
> /**
>  * @implements {import('serverless/classes/Plugin')}
>  */
> class ExportQualifiedFunctionArnsPlugin {
> 	/**
> 	 *
> 	 * @param {import('serverless')} serverless
> 	 */
> 	constructor(serverless) {
> 		this.serverless = serverless;
> 		this.provider = this.serverless.getProvider('aws');
> 
> 		this.hooks = {
> 			'before:aws:package:finalize:mergeCustomProviderResources': async () => {
> 				// For all known functions that have a versionLogicalId: Export a ref to that.
> 				for (const functionName of this.serverless.service.getAllFunctions()) {
> 					const functionObject = this.serverless.service.getFunction(
> 						functionName,
> 					);
> 					if (!functionObject.versionLogicalId) {
> 						// No version for this function configured
> 						continue;
> 					}
> 					const outputName = `${this.provider.naming.getLambdaLogicalId(
> 						functionName,
> 					)}QualifiedArn`;
> 					if (!this.serverless.service.resources.Outputs) {
> 						this.serverless.service.resources.Outputs = {};
> 					}
> 					if (outputName in this.serverless.service.resources.Outputs) {
> 						// Output with this name exist, keep it.
> 						continue;
> 					}
> 					this.serverless.service.resources.Outputs[outputName] = {
> 						Value: {
> 							Ref: functionObject.versionLogicalId,
> 						},
> 					};
> 				}
> 			},
> 		};
> 	}
> }
> 
> module.exports = ExportQualifiedFunctionArnsPlugin;
> ```
> 
> EDIT: Available through npm as [serverless-plugin-export-qualified-arns](https://www.npmjs.com/package/serverless-plugin-export-qualified-arns).

there's no usage example in your plugin, for exporting/importing

**Comment by ankon** [comment]
> there's no usage example in your plugin, for exporting/importing

@yehonadav Thanks for the feedback. I'm not exactly sure what example you mean here, could you maybe [open an issue for the plugin itself](https://github.com/Collaborne/serverless-plugin-export-qualified-arns/issues/new). This way we don't pollute the discussion here for the feature request in serverless itself.
