### ISSUE TITLE
DX: Throw an error if no serverless.yml present

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3662]
# This is a Feature Proposal

## Description

If no `serverless.{yaml|yml|json}` is found in the directory where `sls deploy` is run, then it would be helpful to get an error message saying that.

**Comment by horike37** [comment]
SlS error messages may be wholly not user-frendly..
#3347 is also related to one.

I think that the error message format has not been integrated yet, and should shows those based on the same scheme.
