### ISSUE TITLE
Support custom endpoint URLs for AWS provider

### ISSUE THREAD

**Issue by temyers** [serverless/serverless#3663]
# This is a Feature Proposal

## Description

The AWS CLI supports using `--endpoint-url` when issuing commands.  This feature is useful for overriding the defaults, for example in conjunction with [atlassian/localstack](https://github.com/atlassian/localstack) for local development.

This would provide additional support for integration testing on a local machine.

For example, if a function receives an SNS event X, performs some processing, and publishes a new SNS event Y, unit testing can test the processing code.  However a higher level BDD scenario is not supported:
```
Scenario: event X
When event X is sent
Then event Y should be created
```

Similar or dependent issues:
This is similar to the [Serverless Offline Plugin](https://github.com/dherault/serverless-offline), but would provide a language agnostic solution.

## Additional Data

To run against a custom endpoint you could use:

```
serverless deploy --endpoint-json file://local-endpoint.json
```

Where `local-endpoint.json` contains:
```
{
    "awslambda": "http://localhost:4574",
    "cloudformation": "http://localhost:4581",
    "dynamodb": "http://localhost:4569",
    "kinesis": "http://localhost:4568",
    "redshift": "http://localhost:4577",
    "route53": "http://localhost:4580",
    "s3": "http://localhost:4572",
    "ses": "http://localhost:4579",
    "sns": "http://localhost:4575",
    "sqs": "http://localhost:4576"
}
```

**Comment by pmuens** [comment]
Thanks for opening @temyers 

IMHO this should be added to the local emulator plugin and not be a part of core since we don't have local service support in the core.

**Comment by temyers** [comment]
> the local emulator plugin
Could you point me to what you're referring to?

**Comment by pmuens** [comment]
My bad. Sorry @temyers .

I thought you're using https://github.com/dherault/serverless-offline to emulate everything locally.

I think this addition would be a nice fit for a plugin which can be used in combination with localstack.

**Comment by temyers** [comment]
Thanks for the clarification @pmuens.

Wanted to check there wasn't a different plugin I wasn't aware of.  

Can you override a core command using a plugin?

I'll create a PR to demonstrate what I'm thinking.

**Comment by HyperBrain** [comment]
@temyers Actually you can overwrite a core command. If you do not prepend your hook with `before:` or `after:`, it will replace the command. But **I strongly recommend against such a practice**, as chances are very high that you'll break the framework - you'll disable all sub lifecycles invoked by the core command as well as every side-effect that other plugins might rely on.

**Comment by temyers** [comment]
Thanks @HyperBrain.

Having done some more investigation, I should be able to do everything required in a plugin.

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍 

> Having done some more investigation, I should be able to do everything required in a plugin.

That's great to hear @temyers! Let us know if you face any roadblockers or need some help there.

I'll close this issue for now. It would be great if you could come back once the plugin is done / under development so that others can look into it as well!

**Comment by temyers** [comment]
I've done an initial push to: https://github.com/temyers/serverless-localstack

This is still very much a WIP, and the example isn't fully working yet.  
But I wanted to push to give early visibility.

**Comment by gertjvr** [comment]
https://github.com/serverless-community-labs/serverless-plugin-simulate supports localstack wih a docker-compose file.

**Comment by pmuens** [comment]
Great! Thanks for sharing @temyers 🎉 👍 

Thanks for the update on the simulate plugin @gertjvr 👍 Was not aware that this also provides support for `localstack` 💯

**Comment by kbariotis** [comment]
> IMHO this should be added to the local emulator plugin and not be a part of core since we don't have local service support in the core.

@pmuens why is local service support needed here? e.g. I would just like to deploy a service using serverless directly to localstack, so I would write:

`REGION=eu-central-1 AWS_ENDPOINT_URL=localhost:4581 sls deploy`

and the start my tests. Makes sense?

**Comment by kbariotis** [comment]
> IMHO this should be added to the local emulator plugin and not be a part of core since we don't have local service support in the core.

@pmuens why is local service support needed here? e.g. I would just like to deploy a service using serverless directly to localstack, so I would write:

REGION=eu-central-1 AWS_ENDPOINT_URL=localhost:4581 sls deploy

and the start my tests using the local environment too. Makes sense?

**Comment by pmuens** [comment]
Hey @kbariotis thanks for commenting 👍 

Have you tried the `localstack` / `emulate` plugin which is linked above?

That should make it possible to use the feature discussed in this issue.

**Comment by kbariotis** [comment]
@pmuens yes but they seem a bit more than what I think I need. I want to target serverless to the localstack's cloudformation instance. Then I will inject localstack's URLs to aws-sdk through env variables so my tests are pointing to localstack. After that, I will reset env variables and serverless will deploy to AWS's infrastructure. What do you think?

**Comment by pmuens** [comment]
> I want to target serverless to the localstack's cloudformation instance. Then I will inject localstack's URLs to aws-sdk through env variables so my tests are pointing to localstack. After that, I will reset env variables and serverless will deploy to AWS's infrastructure. What do you think?

@kbariotis that sounds like a feasible solution to the problem 👍!

Right now Serverless does not support a config parameter to use a different CloudFormation instance. However this could be achieved with the help of a custom plugin which modifies / mocks the `aws-sdk` calls to the new, locally running instance (however that's just one way to do it). The source for that should be in the `localstack` project / `serverless-localstack` plugin.

Do you know if you could modify the usage of the CloudFormation service via AWS SDK and `env` variables?

**Comment by Can-Sahin** [comment]
any update on this ? Because none of the libraries above are now maintained.

**Comment by liepumartins** [comment]
Sorry for digging this up.

@kbariotis did You manage to achieve this?

I am also looking for an option to direct all serverless deploy operations to a dedicated (not localhost) localstack server in a manner that only endpoint url/port is different from the real aws.

The plugin serverless-localstack is not suitable as it requires the localstack present on deployer system.
