### ISSUE TITLE
functions with dot in name

### ISSUE THREAD

**Issue by StephanPraetsch** [serverless/serverless#3665]
Hi there,

you must handle dots in function names. AWS does not allow them.

How to reproduce

> serverless create --template aws-java-maven --path my-lambda-sls
> cd my-lambda-sls/
> sed -i 's/hello:/hello.test:/' serverless.yml 
> mvn clean package
> serverless deploy -v

ends in 

> Serverless: Packaging service...
> Serverless: Uploading CloudFormation file to S3...
> Serverless: Uploading artifacts...
> Serverless: Updating Stack...
>  
>   Serverless Error ---------------------------------------
>  
>      Template format error: Resource name Hello.testLogGroup
>      is non alphanumeric.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Forums:        forum.serverless.com
>      Chat:          gitter.im/serverless/serverless
>  
>   Your Environment Information -----------------------------
>      OS:                 linux
>      Node Version:       6.9.1
>      Serverless Version: 1.13.2`

Best regards

**Comment by HyperBrain** [comment]
@pmuens I think this can be solved by changing the name normalization functions in `naming`. They should just normalize dots away to create compliant logical ids.

**Comment by pmuens** [comment]
@HyperBrain that sounds like a good plan to me 👍

**Comment by HyperBrain** [comment]
One thing that just came to my mind - the dot in the name has to be replaced with something else. Otherwise there might be name clashes. Here an example:
```
Function: hello.test
=> With dots just removed: helloTest (would conflict with a helloTest function)
=> Better: helloDotTest
```

**Comment by pmuens** [comment]
@HyperBrain nice catch! Yes, we should definitely do that. 👍 

We already implemented such a replacement for another use case AFAIK. It makes sense to replicate that here...

**Comment by danielchang** [comment]
Hello,
I'm getting the same error on version 1.20.0

`The CloudFormation template is invalid: Template format error: Resource name Services.function.method.getLogGroup is non alphanumeric.`

It would be great if we can have a fix there.

Thanks in Advance

**Comment by pmuens** [comment]
Thanks for commenting @danielchang 👍

Could you please share your `serverless.yml` file so that we can look into it? Thanks!

**Comment by dihmuzikien** [comment]
Hi, 
Is this still an issue? If so, I'm happy to work on it.

**Comment by goliatone** [comment]
@pmuens @dihmuzikien I just ran into this issue today. Using an arn to reference an authorizer function, the **arn** being:

```
arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:531815025279:function:Prod_Firmware_client_api_auth/invocations
```

I think it does not like the underscores.

**Comment by 07Gond** [comment]
Hey guys!
Is this issue still relevant? @pmuens @HyperBrain

**Comment by horike37** [comment]
@07Gond 
Yes, this is still an issue.
Would be great if you can take care of it 👍

**Comment by 07Gond** [comment]
Cool!
On my way! 😃 
@horike37 I will post any updates(doubts and questions) here.

**Comment by pmuens** [comment]
Closing since changing this behavior would result in a breaking change. We'll re-visit it once we work on `v2`.
