### ISSUE TITLE
Add KMS Encryption ARN to Environment variables.

### ISSUE THREAD

**Issue by marcfielding1** [serverless/serverless#3667]
# This is a Feature Proposal

## Description
Would it be possible to look at adding KMS support when defining environment variables? Currently you can specify variables but can't select to have them KMS encrypted.

The CF formation for defining env vars is(note the KMS key arn) so the option is certainly available!

```
{
  "Type" : "AWS::Lambda::Function",
  "Properties" : {
    "Code" : Code,
    "DeadLetterConfig" : DeadLetterConfig,
    "Description" : String,
    "Environment" : Environment,
    "FunctionName" : String,
    "Handler" : String,
    "KmsKeyArn" : String,
    "MemorySize" : Integer,
    "Role" : String,
    "Runtime" : String,
    "Timeout" : Integer,
    "VpcConfig" : VPCConfig,
    "Tags" : [ Resource Tag, ... ]
  }
}
```

* ***Serverless Framework Version 1.5.0***:

**Comment by pmuens** [comment]
Hey @marcfielding1 thanks for opening! 👍 

Yes, we're currently discussing this in https://github.com/serverless/serverless/issues/2996. Closing this one for now since we're discussing the implementation details in #2996.

**Comment by marcfielding1** [comment]
Ahh sorry I didn't spot that!

**Comment by pmuens** [comment]
> Ahh sorry I didn't spot that!

No worries! Feel free to chime in over there!
