### ISSUE TITLE
The 'azure-nodejs' template creates a function that has no output

### ISSUE THREAD

**Issue by RichardSlater** [serverless/serverless#3669]
# Bug Report
The 'azure-nodejs' template creates a function that has no output

### Steps to Reproduce

Following the [Azure Quickstart](https://serverless.com/framework/docs/providers/azure/guide/quick-start/):
1.  `serverless create --template azure-nodejs --path my-service`
2.  `cd my-service`
3.  `npm install`
4.  `serverless deploy -v`
5.  `serverless invoke -f hello`

Steps 1 - 3 resulted in a `serverless.yml` as follows:

    # <snip>

    service: my-service-f5dc29

    # <snip>

    provider:
      name: azure
      location: West US

    plugins:
      - serverless-azure-functions

    # <snip>

    functions:
      hello: 
        handler: handler.hello
        events: 
          - http: true
            x-azure-settings:
              authLevel : anonymous

    # <snip>

When `invoke` is executed the following is emitted:

    [PS] my-service> serverless invoke -f hello
    Serverless: Logging in to Azure

    [PS] my-service>

### Expected Output

    [PS] my-service> serverless invoke -f hello
    Serverless: Logging in to Azure
    "Please pass a name on the query string or in the request body"
    [PS] my-service>

### Root Cause Analysis

Upon investigation of the issue the output variable is set to `$return` which appears to be the default, for azure functions; the function in `handler.js` does not return a value, however, instead it updates the `context` with a `res` variable.

To evidence this I updated the `functions` definition in `serverless.yml` to match the following:

    functions:
      hello:
        handler: handler.hello
        events:
          - http: true
            x-azure-settings:
              authLevel : anonymous
          - http: true
            x-azure-settings:
              diections: out
              name: res

Specifically adding an additional HTTP `event` with a `direction` of **out** and a **name** of `res`.

Similar or dependent issues:

* None Known

## Proposed Solutions

1. Update the templated `serverless.yml` to include the appropriate out variable (as above).
2. Update `handler.js` to return the `res` object rather than assigning it to `context`.

Happy to submit a PR for either option.

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2
* ***Operating System***: Microsoft Windows [Version 10.0.15063]
* ***NodeJS Version***: v7.10.0
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by pmuens** [comment]
@RichardSlater thanks for reporting! 👍 

> Happy to submit a PR for either option.

that would be really nice! Don't know which option to pick though, so feel free to choose whatever you feel is the best 💪

**Comment by RichardSlater** [comment]
Unless I hear otherwise, I am going to change the `serverless.yml` template as this does a good job of presenting the Azure Functions [MCVE](https://stackoverflow.com/help/mcve).  I have a train journey home tonight so I shall start work on then.

**Comment by pmuens** [comment]
> Unless I hear otherwise, I am going to change the serverless.yml template

Great. That sounds good. Thanks for jumping in @RichardSlater 👍
