### ISSUE TITLE
List of all lifecycle events

### ISSUE THREAD

**Issue by Puneeth-n** [serverless/serverless#3671]
Hi,

Is there any complete list of all `lifecycle` events in `serverless`? I am especially interested in `package` events.

**Comment by HyperBrain** [comment]
See here https://gist.github.com/HyperBrain/bba5c9698e92ac693bb461c99d6cfeec#package

**Comment by Puneeth-n** [comment]
@HyperBrain Sweet! Thanks!

**Comment by pmuens** [comment]
Thanks for helping out @HyperBrain 👍 

Dropping this PR by @dougmoscrop here as a reference where a visualization of plugin hooks was implemented.

Might be worthwhile to publish it as a plugin so that it's easier to develop plugins: https://github.com/serverless/serverless/pull/2821

**Comment by tommedema** [comment]
Shouldn't this be in the docs instead of the gist? I also have a hard time understanding the gist, as the events do not seem to be in a chronological order.

**Comment by HyperBrain** [comment]
The lifecycles of each command should be in order (they are awaited promises). I agree that having a dedicated developer documentation that includes the contents of the gist would be much better to find.

**Comment by HyperBrain** [comment]
BTW: This is the correct gist for all the lifecycles: https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406

The other one was only the kick off document for my package/deploy implementation.

**Comment by anwarhamr** [comment]
Can I get some help with this issue? https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406#gistcomment-2879761
trying to copy a file to the project directory when sls deploy is called.
