### ISSUE TITLE
Update docs to show how Serverless can be installed and used locally

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3677]
# This is a Feature Proposal

## Description
Instead of globally installing Serverless, could we only globally install a CLI shim that checks the current directory's `node_modules` for Serverless? This way we can add a `devDependency` directly to our `package.json` and lock it from there rather than having to do it in `serverless.yml`. 

There should be little-to-no changes from a developer's perspective.

**Comment by HyperBrain** [comment]
What is the point against installing serverless on a project level, I mean as devDependency in the projects? We do not install SLS globally at all (and lock the versions there in our package.json).
Do you have any problems with installing SLS as project dependency?

**Comment by hassankhan** [comment]
I've never actually tried installing Serverless as a dependency, I've always upgraded my global install. I wasn't even sure that it worked, just wanted to start a discussion 😄

**Comment by HyperBrain** [comment]
:) So just try - it should work.

**Comment by DavidWells** [comment]
@hassankhan it should work installed in the project directory. 

You will need to run commands like `./bin/serverless deploy` (local bin in project) though. The quick global `serverless` or `sls` commands is one of the benefits of installing globally

**Comment by hassankhan** [comment]
@DavidWells Yep I figured that bit out myself 😉. The reason I asked was in the past there have been some breaking changes and some old projects were on an older version, which meant we'd have to replace our global install with whatever version was required for the project.

Perhaps we could add some documentation explaining how to do this (which is simple) and why you might want to?

**Comment by DavidWells** [comment]
@hassankhan yeah that would probably good to point out.

There is also a little known feature `frameworkVersion: ">=1.0.0 <2.0.0"`  in serverless yaml to lock down the version https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/. I haven't used `frameworkVersion` personally yet though.

**Comment by hassankhan** [comment]
I was aware of that feature and it was exactly that which got me wondering why I couldn't just specify it in `package.json` instead. Leave dependency/version management to the tools that do it best IMO.

**Comment by pmuens** [comment]
Nice discussion! I updated the title and added some labels.

I agree that it would be worth to have this somewhere in the docs.

/cc @brianneisler

**Comment by hassankhan** [comment]
Any recommendation on where it should live in the docs?

**Comment by ryanmurakami** [comment]
@hassankhan I would think in the [Getting Started](https://serverless.com/framework/docs/getting-started/) section, since it is a platform-agnostic concern.

**Comment by pmuens** [comment]
Shoot. Haven't read that. I added my 2 cents in the PR --> https://github.com/serverless/serverless/pull/3681#pullrequestreview-40215277

Open for other suggestions though!

**Comment by brianneisler** [comment]
@pmuens @hassankhan I agree that this should be made clear in the docs. I also think we could take this one step further. Perhaps if the global framework detects a local version of the framework installed it should execute that version of the framework instead of using the global one.

**Comment by pmuens** [comment]
@brianneisler sounds good.

Only concern I have is that it might be confusing for the user if he has Serverless v1.14 installed globally and wants to use the `rollback function` command but the project specifies v1.13 which doesn't implement that yet.

Maybe we can inform the user which Serverless version will be used if he runs a command and both (the local an global) Serverless versions are detected.
