### ISSUE TITLE
Stack cannot be removed after one errorneous attempt

### ISSUE THREAD

**Issue by StephanPraetsch** [serverless/serverless#3679]
# This is a Bug Report

## Stack cannot be removed after one errorneous attempt

For bug reports:
* What went wrong?
Tried to remove the complete stack with `serverless remove`. A configured bucket was not empty. Thus the stack ended up in DELETE_FAILED. Then I emptied the bucket and re-removed. But from now on serverless keeps saying "The specified bucket does not exist"
* What did you expect should have happened?
Remove the complete stack after all configured buckets are emptied.
* What was the config you used?
```service: my-lambda
provider:
  name: aws
  runtime: java8
package:
  artifact: target/hello-dev.jar
functions:
  hello:
    handler: com.serverless.Handler
resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: this-is-my-unique-bucket-5646524860
```

* What stacktrace or error message from your provider did you see?
At first with a non-empty bucket (error is correct)
```my-lambda> serverless remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
...Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: MyBucket
     - The bucket you tried to delete is not empty.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.9.1
     Serverless Version: 1.13.2
```

After emptying the bucket
```my-lambda> serverless remove
Serverless: Getting all objects in S3 bucket...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.9.1
     Serverless Version: 1.13.2
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
MAYBE serverless has a bug when the current state of the stack is DELETE_FAILED.

* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
     Node Version:       6.9.1
     Serverless Version: 1.13.2
* ***Operating System***:
     OS:                 linux
* ***Stack Trace***:
* ***Provider Error messages***:
     The specified bucket does not exist

**Comment by HyperBrain** [comment]
As `serverless remove` will remove the deployment bucket in any case (implicitly through the CF stack removal), it might be beneficial if the framework would empty the bucket before trying to remove the stack - we know that it will fail, in case the bucket is not empty.

From an UX/DX view, a `--force` flag could be added, because is is a destructive operation. So, if the flag is not given, but there are objects in the bucket, SLS could emit an error message (bucket not empty) and exit prematurely with a hint to specify the `--force` flag to detroy the data. If the flag is given, it should empty the bucket before trying to remove the stack.
There is still a kind of race condition here - the CF removal can still fail after the bucket has been emptied for other reasons. In this case no recovery would be possible - and even the stack delete rollback might fail. Maybe specifying `OnFailure: 'DELETE'` in the stack delete operation would be sufficient, as it will be deleted anyway then (this is my assumption, not verified). But if that happens SLS could show a warning that some resources might be orphaned due to a failure.

**Comment by pmuens** [comment]
Thanks for the feedback @HyperBrain 👍 

Refing https://github.com/serverless/serverless/issues/1609 here which also discussed a `--force` switch.

**Comment by StephanPraetsch** [comment]
Dont misinterprete. Im fine with the first error if the bucket isn't empty. But after I emptied on my own sls should be able to remove the stack. But it does not. It keeps the opinion it's not removable. Probably a force wouldn't help. The state of the stack seems to be misinterpreted.

**Comment by HyperBrain** [comment]
Understood. So the DELETE_FAILED is indeed the root of the error. Just read through the AWS CF docs. There is a special note on that state for the stack deletion. So Serverless should do exactly as proposed there. I.e. if SLS detects that a stack is in the DELETE_FAILED state, it should set the bucket resource to RETAIN in RetainResources. Then the delete should succeed afterwards:

> RetainResources.member.N

> For stacks in the DELETE_FAILED state, a list of resource logical IDs that are associated with the resources you want to retain. During deletion, AWS CloudFormation deletes the stack but does not delete the retained resources.

> Retaining resources is useful when you cannot delete a resource, such as a non-empty S3 bucket, but you want to delete the stack.

> Type: Array of strings

> Required: No

**Comment by StephanPraetsch** [comment]
I don't agree. IMHO remove is an invasive call. A user should be clear about it. Maybe add a "are you sure?" prompt ...

But if remove is called I'd expect serverless to remove anything. I wondered if serverless could not redeploy my stack after a remove just because of it only flagged each bucket to be removable (sometime).

either:
keep remove as implemented now but handle the DELETE_FAILED state as if it is a normal state. Just call cloudformation to delete (again). If it is still not possible then it is still not possible. But if the stack became removable then simply remove it. I could remove the stack via AWS console. So why shouldn't sls being able to?

or:
check before remove whether all resources are removable. If not throw an error before to start removing the stack. But checking all resources could be a pain.

**Comment by HyperBrain** [comment]
@eahefnawy What is your opinion on that? IMO it would be possible to treat the DELETE_FAILED state as valid entry state for the stack delete operation (within the remove command).

**Comment by StephanPraetsch** [comment]
Ah, I guess "the specified bucket does not exists" means the deployment-bucket does not exist (anymore). It was removed successfully during the first attempt. For the second attempt it crashes instantly because of missing the deployment-bucket.

**Comment by pmuens** [comment]
> Ah, I guess "the specified bucket does not exists" means the deployment-bucket does not exist (anymore).

@StephanPraetsch yes, that could be the root cause of the problem. I had the exact same error yesterday when my stack got into an inconsistent state. Had to remove it manually in the console and re-redploy.

**Comment by alexcasalboni** [comment]
@pmuens any update on this?
I've bumped into this problem a couple of times as well recently (and of course I blamed CloudFormation! ^_^).

**Comment by pmuens** [comment]
> @pmuens any update on this? I've bumped into this problem a couple of times as well recently (and of course I blamed CloudFormation! ^_^).

Thanks for pinging @alexcasalboni 👍

Unfortunately not yet. Adding the "backoff" mechanism @HyperBrain described above sounds like a good solution here.

However the discussed `--force` switch would be a great "universal" solution since it would fix / resolve a couple of related issues.

**Comment by alexcasalboni** [comment]
It makes sense to me. Maybe we could document the issue somewhere, compile a couple of possible temporary solutions, and then update them then once `--force` is available?

I'm not quite sure how many projects define an additional bucket and then DON'T write anything into it. I sort of agree with @StephanPraetsch here (i.e. "_If I run `sls remove` the stack should disappear, eventually with a warning_").

**Comment by pmuens** [comment]
> It makes sense to me. Maybe we could document the issue somewhere, compile a couple of possible temporary solutions, and then update them then once --force is available?

@alexcasalboni Sounds like a good solution for now 👍. Maybe a simple addition to the [`remove` CLI documentation](https://serverless.com/framework/docs/providers/aws/cli-reference/remove/) might be sufficient.

**Comment by dev-head** [comment]
My understanding is that serverless will create a deployment bucket if the user does not define one, this should apply to removing the bucket. If that is the case, Serverless should not remove a bucket it did not create, perhaps at most only the content it uploaded. 

The reason is that if users must maintain their own custom bucket outside of serverless configuration, serverless created that separation and should follow it. If serverless could create the s3 bucket of the users's choosing, that would negate my feedback (and is part of another request already). 

- 2cents

**Comment by alexcasalboni** [comment]
@dev-head I think the problem is already solved for the deployment bucket. We've been discussing the problem for other buckets, which are created by Serverless, but are not empty on `sls remove`. If you create a bucket, you will probably write something into it, right? And when I want to remove the service, eventually with an additional confirmation or explicit option, the bucket should be removed too.

**Comment by johnsgp** [comment]
Would it help to make the other buckets depend on the deployment bucket so that the latter is deleted last?  That way, if there's a failure because of a non-empty bucket, at least the remove can be retried after emptying the buckets.

**Comment by loren** [comment]
What is the workaround for folks like me who find themselves in this state?

**Comment by ryanwmarsh** [comment]
@loren it appears the [serverless-s3-remover](https://github.com/sinofseven/serverless-s3-remover) plug-in that may help

**Comment by loren** [comment]
Thank you @ryanwmarsh for the suggestion. Unfortunately, it doesn't help get me out of this un-place. When I run `sls s3remove`, it says `S3 Remover: Faild: your-bucket-name may not be empty.` That's a surprising message given the plugin's purpose.

I will try creating a new repo with everything renamed. Maybe a fresh start is the only way to work around this issue.

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue. Furthermore there are some potential solutions discussed in the issue thread.

Feel free to re-open if this is still a problem.

**Comment by ffxsam** [comment]
@pmuens Maybe for those of us stumbling upon this via search, you could please list the ways to handle this? I just ran into it myself (a Cognito pool failed to delete, then `sls remove` wouldn't work since the deployment bucket it expects to be there is gone).

**Comment by hashbrown** [comment]
I also just ran into this today, and same condition as @ffxsam, serverless IAM didn't have DeleteCognitoPool so the `sls remove` failed.  I also can't do a force deploy to try and get out of it either. Totally stuck.

**Comment by ffxsam** [comment]
@hashbrown The workaround is to simply remove the stack manually via AWS.

**Comment by hashbrown** [comment]
Thanks, I just ran across that here, https://github.com/serverless/serverless/issues/3964
Appreciate the response!

Not sure if you were trying to accomplish the same thing as me, but I purposely did not want to allow my serverless IAM user to delete the Cognito User Pool.  Seems dangerous that someone could be trying to fix some deployment issue, then blow away all my users with a remove.

**Comment by ffxsam** [comment]
I actually did want to take everything down. 😄 (it was a dev environment stack)

**Comment by kiddrew** [comment]
I got frustrated trying to debug a CF that was failing to delete, so I just deleted it manually. Now I have an orphaned service. Would be very nice to have a `--force` option
