### ISSUE TITLE
Encrypt / obfuscate variables pulled via Serverless "s3:" Variables

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3688]
# This is a Feature Proposal

## Description

The recently introduced Serverless Variable enhancement which enables users to pull values via `s3` makes it possible to e.g. get secrets from an S3 variable and load them in `serverless.yml` / the generated CloudFormation template.

However the common use case to use it to fetch security credentials is currently introducing security implications since the values are inserted as plain text and can be read by anyone who has read permissions for CloudFormation.

It could be solved like @shortjared pointed out here:

> The quickest fix for that would be to inject cloudformation params to the template with no echo flag, and then on deploy pass in the values for those params pulled from s3. This means those params would be "write only", the secrets would not be exposed plaintext in the template, then the env vars on lambda would require KMS key access to run the decryption helpers in the console. I wouldn't suggest encouraging it for usage with credentials right now without mentioning the caveats so people are at least aware.

Thanks @shortjared for bringing this up!

---

In the meantime one should consider @svdgraaf https://github.com/svdgraaf/serverless-parameters plugin or adding parameters via the `resource` section (as pointed out by @hauboldj [here](https://github.com/serverless/serverless/issues/3688#issuecomment-304291248)) to solve this issue.

/cc @eahefnawy @brianneisler

**Comment by hauboldj** [comment]
This plugin is unnecessary, you can just add parameters like this.
```
resources:
  Parameters:
    Test:
      Type: String
      Description: this is a Test
      Default: Some default here
      NoEcho: true
```

**Comment by aoskotsky-amplify** [comment]
Why not KMS encrypt the values before storing them in S3 so that Serverless is injecting encrypted text into the variables?

**Comment by hauboldj** [comment]
You could, you need to decrypt at runtime then.

**Comment by svdgraaf** [comment]
@hauboldj Woosh! ha, I missed that option completely :D

**Comment by S3B4S** [comment]
@hauboldj @svdgraaf How did you guys decrypt it at runtime? I'm struggling with this a lot right now :frowning_face:

**Comment by pmuens** [comment]
Closing since other AWS services should be used when dealing with sensitive information.
