### ISSUE TITLE
Log information about the event when sending invoking a Lambda via "sls invoke"

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#3691]
# This is a Feature Proposal

## Description

Over the last couple months a sometimes ran into the issue of sending a string to instead of a JSON object when running `sls invoke`. I believe we can improve DX by informing people what actually gets sent.

### Current Issue

`sls invoke --log -s dev -f updateDesc --data '{ "id": "abc", "description": "test" }'` -> Data is a JSON

In the case above the a JSON ist dedected and converted by `sls invoke`.

`sls invoke --log -s dev -f updateDesc --data '{ "id": "abc", description: "test" }'` -> Data is a String

In the case above it's not valid JSON, because the description key doesn't have quotes. In this case the whole thing is sent as string.

Suggestion we improve the CLI experience by doing the following:

```
sls invoke --log -s dev -f updateDesc --data '{ "id": "abc", "description": "test" }'

Serverless Request:
{ "id": "abc", "description": "test" } 
Serverless Response:
{
    "id": "abc",
    "name": "test-name"
    "description": "test"
}
```

```
sls invoke --log -s dev -f updateDesc --data '{ "id": "abc", description: "test" }'

Serverless Request:
'{ "id": "abc", "description": "test" }'
Hint: The data you sent is a String. If you want to send an object all keys must have quotes.
Serverless Response:
{
    "id": "abc",
    "name": "test-name"
    "description": "test"
}
```

**Comment by pmuens** [comment]
That's pretty nifty! I like that (ran into the issue a couple of times 😞 ).

So the response would be still the same we have right now (basically the same AWS Lambda would return). We just add the "Serverless Request" part and the "Serverless Response" heading?!

**Comment by nikgraf** [comment]
@pmuens yep, I believe we need a distinction there. We can also add the headline for the log. This is also sometimes confusing to see where it starts or stops e.g.

```
sls invoke --log -s dev -f updateDesc --data '{ "id": "abc", "description": "test" }'

Serverless Request:
{ "id": "abc", "description": "test" } 
Serverless Response:
{
    "id": "abc",
    "name": "test-name"
    "description": "test"
}

Serverless Log:
START RequestId: b9852bbd-4218-11e7-84bd-297dbace60c3 Version: $LATEST
END RequestId: b9852bbd-4218-11e7-84bd-297dbace60c3
REPORT RequestId: b9852bbd-4218-11e7-84bd-297dbace60c3	Duration: 34.64 ms	Billed Duration: 100 ms 	Memory Size: 1536 MMax Memory Used: 118 MB	
```

**Comment by brianneisler** [comment]
Hmm, something seems off about all of this. JSON is a string... so it seems like there is either a bug somewhere or our treatment of the data parameter is a little off... will have to investigate it a bit further to understand what's going on in that command.

That being said, I like the output with headers. The hints are kind of nice but I think type information should just be part of the output
```
Object {
  a: 123
}

String '{ "a": 123 }'
```

**Comment by pmuens** [comment]
I like that @brianneisler 👍 

We're parsing everything into JSON here https://github.com/serverless/serverless/blob/4d6dfed58796bfc7e02772cdb1ce904d148385d9/lib/plugins/aws/invoke/index.js#L77 since the AWS SDK expects JSON --> http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property

**Comment by nikgraf** [comment]
@pmuens we try to parse the data argument as JSON [here](https://github.com/serverless/serverless/blob/4d6dfed58796bfc7e02772cdb1ce904d148385d9/lib/plugins/aws/invoke/index.js#L56-L62), but if you provide invalid JSON it is just a string. We could also throw an error in this case. Right now I'm not sure what the expected behaviour should be. Just sending a string is a valid Lambda event …

**Comment by pmuens** [comment]
@nikgraf ah yes, we parse there and then stringify the payload. Missed that  🤦‍♂️ 

Yes, maybe throwing and error might be a good idea since AWS expects JSON.

**Comment by nikgraf** [comment]
Throwing an error sounds good to me. @eahefnawy @brianneisler What do you think?

**Comment by brianneisler** [comment]
@nikgraf yep, throwing an error makes sense to me.

**Comment by pmuens** [comment]
We should also take this comment into account here: https://github.com/serverless/serverless/pull/2701#pullrequestreview-42083774

**Comment by pmuens** [comment]
Closing since this issue is quite old and there are no plans to support this in the foreseeable future.
