### ISSUE TITLE
Default variable syntax detection conflicts with variable syntax used by AWS

### ISSUE THREAD

**Issue by azurelogic** [serverless/serverless#3693]
# This is a Bug Report

## Description

There are a number of places where AWS uses `${stuff}`, `${aws:stuff}`, and `${iot:stuff}` syntax for variables (see https://docs.aws.amazon.com/iot/latest/developerguide/iot-substitution-templates.html and https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html for examples). This is problematic as the existing default regex used for variable syntax detection cannot distinguish these AWS variables from Serverless variables.

Similar or dependent issues:
* #3565 talks about an escape syntax which is unnecessary if the regex is improved

**Comment by pmuens** [comment]
Closing since this issue is quite old and we've shipped newer versions with fixes in the past.

Feel free to re-open if this issue is still around...
