### ISSUE TITLE
Simplify quickstart and include http event

### ISSUE THREAD

**Issue by luebken** [serverless/serverless#3708]
# Docs / Feature Proposal

## Description

The current [quickstarts](https://serverless.com/framework/docs/providers/aws/guide/quick-start/
) suggests to use the template `aws-nodejs`. Which has two drawbacks:

a) It doesn't show an end2end experience. 
b) Has a bloated serverless.yml. Even if it's just the comments.

## Proposal

I would suggest using the `hello-world` template in the quickstart including the http get event. As it

a) Shows the simplest end2end experience. Including an event.
b) Has the most simple serverless.yml without overwhelming the user. Additionally the cors code could be removed.

**Comment by pmuens** [comment]
@luebken thanks for the feedback!

Yes, that makes sense. That's why we've included the `hello-world` template in the first place.

Only thing I'd add here is that this (of course) only applies for the AWS quickstart.

Would be nice to get a PR for that 💯 

/cc @DavidWells

**Comment by luebken** [comment]
> Only thing I'd add here is that this (of course) only applies for the AWS quickstart.

Interestingly the [azure](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/azure-nodejs/serverless.yml#L40) and the [google](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/google-nodejs/serverless.yml#L23) templates include a http event. Where as [openwhisk](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/openwhisk-nodejs/serverless.yml#L46) doesn't.

**Comment by pmuens** [comment]
> Only thing I'd add here is that this (of course) only applies for the AWS quickstart.
>> Interestingly the azure and the google templates include a http event. Where as openwhisk doesn't.

Yes, sorry for the confusion. I meant that only the quickstart guides for the AWS docs needs to be updated with the new `hello-world` template.

**Comment by luebken** [comment]
> Yes, sorry for the confusion. I meant that only the quickstart guides for the AWS docs needs to be updated with the new hello-world template.

Hmm. I'm not sure if I can follow. Do you suggest [AWS quickstart](https://serverless.com/framework/docs/providers/aws/guide/quick-start/) should use the `hello-world` template? This sounds confusing since it neither references aws nor nodejs.

Meanwhile I learned about `install`. And now I'm wondering what the longterm ideas of templates are and the differente to install.

**Comment by pmuens** [comment]
> Hmm. I'm not sure if I can follow. Do you suggest AWS quickstart should use the hello-world template? This sounds confusing since it neither references aws nor nodejs.

Yes, I'd suggest that the AWS quickstart guide should be updated so that the `hello-world` template is used there (as you mentioned in your porposal). I agree with the confusing part that it's missing information about the provider and runtime though.

> Meanwhile I learned about install. And now I'm wondering what the longterm ideas of templates are and the differente to install.

The `install` command is the recommended way to download and use a pre-existent service.

The core templates we ship with serverless are really stripped down mini services which should always be used when starting a project since they only include the bare minimum.

More complex template / services (e.g. boilerplates with opinionated test frameworks, or boilerplates in general) will not be included in the core and should be installed with the help of the `install` command.

**Comment by luebken** [comment]
@pmuens I started a [PR](https://github.com/serverless/serverless/pull/3721) to make the discussion more concrete. let me know what you think.

**Comment by pmuens** [comment]
Nice. Thanks @luebken 👍 I'll look into it.

**Comment by pmuens** [comment]
Closing since this issue got quite stale and we've updated the docs a couple of times in the meantime.

Thanks again for opening and working on this @luebken 👍
