### ISSUE TITLE
Add TypeScript support in FunctionCreate

### ISSUE THREAD

**Issue by nillis** [serverless/serverless#371]
I would like to implement TypeScript support in the lambda functions. I would like some advice on which solution to choose:

1) Add an *enableTypeScript* option to the FunctionCreate action

When enabled the following files would be copied to the generated function:
* tsconfig.json 
* tsd.json 
* typings (empty folder)
* ts (empty folder)

In the ts folder, users can add their ts files which will be compiled to the lib folder

2) Write custom plugin

**Comment by ac360** [comment]
@nillis That would be AWESOME.  I think you should write it as a Plugin.  Our process for now is to keep the core lean, and encourage plugins.  ...If the Plugins are in high demand, we'll merge them into the core.

**Comment by nillis** [comment]
Great, thx for the response!

**Comment by jwulf** [comment]
Awesome! I totally want to use Typescript with serverless too!

Where will the typescript compile take place? Does it rely on Visual Studio, or will it be part of the server less build / run / publish toolchain?

**Comment by nillis** [comment]
I currently use tsc from the command line. Based on the tsconfig.json file it will compile/watch your ts files and publish it to the right directory.
I will share my workflow later today or tomorrow.

**Comment by nillis** [comment]
I currently have this workflow to build serverless modules with TypeScript.

**Prerequisites**
```
npm install -g typescript
npm install -g tsd
```

**Setup**
I create my serverless module using the usual command
```
sls module create
```

1) src folder
Under the module folder I add a src folder where I put my ts files. These files will be compiled into js to the lib folder.

<img width="181" alt="screen shot 2015-12-15 at 20 13 30" src="https://cloud.githubusercontent.com/assets/2675228/11821140/6e9f147c-a368-11e5-8784-21985a273a47.png">

2) tsconfig.json

I add a tsconfig.json file with the TypeScript configuration. When I run tsc from the module directory it'll use this configuration file to compile the ts files from the src files to the lib folder.

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": true,
        "declaration": true,
        "outDir": "lib",
        "watch": true
    }
}
```

3) tsd.json

Just run the following command from the module directory to init tsd. With tsd you can easily pull declaration files. The declaration files will be stored into the typings directory.

```
tsd init
tsd install node --save
```

**Run, Forest, Run!**
Just run the tsc command from the module folder and see the ts files under src been compiled to the lib folder into js.
```
tsc
```

If you have any questions, I'm glad to help.

**Comment by nillis** [comment]
If you translate this workflow into a serverless plugin this would mean the plugin does the following:
Extend the FunctionCreate, add a tsconfig.json and tsd.json file to the module directory and creates a src folder with the ts files.

**Comment by ac360** [comment]
@nillis I haven't tried TypeScript yet, so you're the export here.  I have a few thoughts on Plugin development though.  I think the Plugin you write should absolutely create a POST hook on FunctionCreate to add the Typescript files.  You can also write PRE hook on FunctionDeploy to run the compiling (although I'm unclear as to how all of this works).  Further, every `s-project.json`, `s-module.json` and `s-function.json` includes a `custom` property where Plugins can store config data.  I recommend you check that out as an alternative to creating more JSON files.  We will be starting work on the Serverless Dashboard project soon and it will help people visualize the data in those `custom` properties.   Hope this helps and I'm really looking forward to this @nillis.  This will prompt me to start playing with TypeScript.  Also don't forget to log the `evt` object to see what cool Action-specific data is passed into your Plugin Hooks.  Lots of useful stuff in there, we made sure of that :)

**Comment by nillis** [comment]
Great, thanks for the guidelines aboit plugins. Are their any
docs/resources available with this documentation?
If you could use any help with developing the dashboard, I would be glad to
be involved in this.

**Comment by pietrasiak** [comment]
I've created example of serverless lambda with typescript with local development support - https://github.com/pietrasiak/serverless-typescript-starter

It's based on `serverless-webpack` and `serverless-offline`
