### ISSUE TITLE
Do not overwrite ENV VARS if there isn't any

### ISSUE THREAD

**Issue by mt-sergio** [serverless/serverless#3716]
# This is a Feature Proposal

## Description
My `serverless.yml` looks like:
```
provider:
  ***
  environment: ${file(serverless-env-${self:custom.myStage}.yml)}
```
`serverless-env-localhost.yml` exists, but `staging` or `production` does not. However, instead of deploying everything using `sls deploy`, I configured CircleCI to only deploy individual functions. This design works very well as we can set the ENV VARS directly in the lambda and no developers have access to it. You also don't have to worry about performance issues as they are directly in Lambda service or keep them in a secret S3, or expose them into a github (even we use KMS), etc.

The problem is that if we execute again `sls deploy` because we changed any resource, this overwrites the ENV VARS in Lambda, so the result is empty ENV VARS.

Is it possible to keep what is there if that file (`serverless-env-production.yml`) is not found??

Update: The ENV VARS are kept, but in the previous version while the new version is empty. What about copying them to the newest one by default?

**Comment by mt-sergio** [comment]
**My solution:**
I created a bash script for a full deploy, with this content:
```
## Copy ENV VARS from deployed version
aws lambda get-function --function-name arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:${LAMBDA} | jq -r '.Configuration.Environment.Variables | to_entries[] | .key + ": " + .value' > ./app/serverless-env-${STAGE}.yml

# deploy
../node_modules/.bin/sls deploy -s ${STAGE} -r ${REGION}

rm ./app/serverless-env-${STAGE}.yml
```
(you need to set the VARs. Be careful as LAMBDA must exist in the project. Also doublecheck the path for your included .yml file!)

**Comment by pmuens** [comment]
@mt-sergio thanks for opening 👍 

> Is it possible to keep what is there if that file (serverless-env-production.yml) is not found??

You could define a fallback value which should be used instead (https://serverless.com/framework/docs/providers/aws/guide/variables#overwriting-variables).

This could solve your problem.

**Comment by mt-sergio** [comment]
@pmuens right, I already use the fallback on the variable `custom.myStage`, but in this case I really want to have it empty (with a wrong expectation of keeping my old values).

I guess this issue is not 100% related to serverless, it how CloudFormation updates the lambda and overwrite the value. You cannot do nothing else than ensure all VAR ENVs are the same as what they are already deployed.

**Comment by pmuens** [comment]
> I guess this issue is not 100% related to serverless, it's about how CloudFormation updates the lambda and overwrite the value. You cannot do nothing else than ensure all VAR ENVs are the same as what they are already deployed.

Right, that sounds reasonable. Thanks for sharing your solution @mt-sergio 👍
