### ISSUE TITLE
DX: Add serverless version check when a command is run

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3724]
# This is a Feature Proposal

## Description
serverless should check for new version on startup. 

If the latest version is newer than the current version, display a message with the new version number, and instructions on how to update. 

### Example:
```sh
Serverless 1.16.0 is available! (you're using 1.15.0)
To upgrade, run "npm upgrade --global serverless"
```

**Comment by rupakg** [comment]
@brianneisler In the above example if I am using 1.16.0, why would I see any message. I have the latest version! Did you mean - "(you're using 1.14.0)" ?

Btw, just realized the iPhone keyboard doesn't have the 'tick' symbol...

**Comment by DavidWells** [comment]
We should probably just use https://github.com/yeoman/update-notifier instead of rolling this ourselves for the time being

Pretty cool how it works https://github.com/yeoman/update-notifier#how

**Comment by pmuens** [comment]
Thanks for opening @brianneisler 👍 

Looks like it's a duplicate of / related to https://github.com/serverless/serverless/issues/2118

**Comment by brianneisler** [comment]
@rupakg whoops, good catch! Lol, yes sorry about. Updated the example.

**Comment by brianneisler** [comment]
@pmuens good catch! missed that one. Will close this ticket as a duplicate.
