### ISSUE TITLE
README refers to non-existent issue labels

### ISSUE THREAD

**Issue by humphd** [serverless/serverless#3726]
# This is a Bug Report

## Description

The README has a nice section on Contributing, which mentions a number of labels that interested developers can use to find things:

> Check out our [exp/beginner](https://github.com/serverless/serverless/labels/exp/beginner), [exp/intermediate](https://gi\
thub.com/serverless/serverless/labels/exp/intermediate) or [exp/expert](https://github.com/serverless/serverless/labels/e\
xp/expert) labels to find issues we want to move forward on with your help.

However, none of these labels exist, nor do they seem to have ever existed.

In the Contributing doc, there is something similar, but this time the labels do exist:

> Check out our [help-wanted](https://github.com/serverless/serverless/labels/status/help-wanted) or [easy-pick](https://github.com/serverless/serverless/labels/status/easy-pick) labels to find issues we want to move forward on with your help.

It would be good if the two docs pointed to the same [help-wanted](https://github.com/serverless/serverless/labels/status/help-wanted) and [easy-pick](https://github.com/serverless/serverless/labels/status/easy-pick) labels.

## Additional Data

It's great that you've gone to the trouble of labeling issues like this, and providing entry points for developers to get involved.  Thanks for doing it.

**Comment by pmuens** [comment]
Nice catch! 👍 

Thanks for opening and thanks for the kind words @humphd . Really appreciate it 💯 !

Might be a good time for an update of this section! PRs for this are highly welcomed 💪

**Comment by humphd** [comment]
OK, I'll do a PR.  Your Contributing doc seemed to indicate you preferred issues before PRs, so I filed first.

**Comment by pmuens** [comment]
> Your Contributing doc seemed to indicate you preferred issues before PRs, so I filed first.

@humphd exactly 👍 that's always a good start!

This way we can discuss things first before the first line of code is written which helps us to find the best implementation possible and avoid unnecessary work 👍 

Thanks for submitting the PR! We'll look into it now 👍
