### ISSUE TITLE
Option to remove aws-sdk from local node_modules before deploy

### ISSUE THREAD

**Issue by davepwsmith** [serverless/serverless#3733]
# This is a (Feature Proposal)
Option to remove aws-sdk from local node_modules before deploy
## Description
aws-sdk alone is a huge node module (over 20mb unzipped) and along with all its dependencies it weighs in sufficiently to prevent in-browser code edits on the lambda platform. 

A user may want to use something which depends on aws-sdk (e.g. `@awspilot/dynamodb`) - but this will run fine with lambda's native aws-sdk module.

Currently you can manually remove aws-sdk and its dependencies and thus shrink your function package.zip by, using my case as an example, a factor of 25.

Could it be an option for serverless to remove these unnecessary modules before packaging/deploying?

## Additional Data
N/A

**Comment by pmuens** [comment]
Hey @davepwsmith thanks for opening 👍 

You can use the `exclude` / `include` rules to define globs which will describe what should be excluded / included in your deployment package (see: https://serverless.com/framework/docs/providers/aws/guide/packaging#exclude--include).

We're also working on #2709 which might be related.

**Comment by yuyokk** [comment]
@ChristianUlbrich Thanks for sharing!
Just shaved off 9mb of package size with moving `aws-sdk` to `devDependency` 🔥

**Comment by JoshuaAlzate** [comment]
@yuyokk how did you do it? I included the `@aws-sdk` to `devDependency`, but it is still included in the package.
