### ISSUE TITLE
Getting Started deploy tutorial for Google-Functions fails

### ISSUE THREAD

**Issue by vpsouza** [serverless/serverless#3738]
# This is a Bug Report

## Description
Following the tutorial at [Google Cloud Functions Quick Start Guide](https://serverless.com/framework/docs/providers/google/guide/quick-start/) is given an error when trting to deploy a new function

For bug reports:
* What went wrong?
Following error when running serverless deploy

> Object.keys(...).includes is not a function

* What did you expect should have happened?
Deploy the new function

* What was the config you used?
serverless v1.14.0

* What stacktrace or error message from your provider did you see?
`Serverless: Packaging service...
Serverless: Compiling function "first"...
 
  Type Error ---------------------------------------------
 
     Object.keys(...).includes is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 

## Additional Data

  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.7.3
     Serverless Version: 1.14.0`

**Comment by HyperBrain** [comment]
Using lodash throughout the code base should solve the problem (e.g. `_.includes()`) and guarantee support for node 4. As long as AWS offers Node 4 as runtime, we should expect people to use that for deployment to have the same environment locally and remote.

**Comment by kingchad** [comment]
supported node runtimes
>Node.js runtime v6.10 (runtime = nodejs6.10)
Node.js runtime v4.3 (runtime = nodejs4.3)
Node.js runtime v0.10.42 (runtime = nodejs)

**Comment by pmuens** [comment]
@HyperBrain yes, using Lodash in the codebase sounds like a good solution.

Thanks for the table with all the runtimes @kingchad 

One thing to keep in mind here is that it's the Google plugin which breaks since we've used `includes` in that codebase.

**Comment by kingchad** [comment]
Whoops for some reason I thought it was AWS, so I posted their runtimes.

**Comment by ramitsurana** [comment]
For upgrading npm and nodejs:

$ sudo npm cache clean -f
$ sudo npm install -g n
$ sudo n stable

$ sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/nodejs

**Comment by pmuens** [comment]
Closing since this is quite a stale issue and we've published lots of fixes addressing this in the past.
