### ISSUE TITLE
serverless.yml should be allowed to be a symlink

### ISSUE THREAD

**Issue by maikokuppe** [serverless/serverless#3755]
# This is a Feature Proposal

## Description

Given this project structure

```
serverless.yml -> config/serverless.yml
config
  - serverless.yml
```

Serverless does not find the serverless.yml. E.g. running `serverless package` does nothing.
If `config/serverless.yml` is moved to root, it **does** package my stuff.

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2
* ***Operating System***: Ubuntu 16.04
* ***Stack Trace***: -
* ***Provider Error messages***: -

**Comment by pmuens** [comment]
Closing since this issue is quite old and we've published never versions with lots of fixes in the past.

Feel free to re-opn if this is still a problem.

**Comment by roenschg** [comment]
This is still an issue

Framework Core: 1.52.0
Plugin: 2.0.0
SDK: 2.1.1

**Comment by piersatdoshii** [comment]
This is still a current issue, can this be reopened please? Have to admit I've never seen software unable to handle symlinks before, not sure why it's checking for that explicitly.
```
Framework Core: 3.34.0 (local) 3.34.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
