### ISSUE TITLE
DX: Improve handler validation in serverless.yml

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#3758]
# Improve handler validation in serverless.yml

## Description

* When parsing the serverless.yml file or when packaging the function there could be some basic validation on the handler. For example check if the file exists and the method exist.

## Additional Data

* **1.13.0**:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for the suggestion @juanjoDiaz 👍 

Just want to add here real quick that we should keep in mind that this could be implemented in a provider independent way which might be challenging.

**Comment by juanjoDiaz** [comment]
Testing whether a handler is valid or not should be independent of the vendor since it's just checking whether the file exist and the method exist within the file or not.

It will be language dependent though. Javascript is trivial but other languages might be trickier.

**Comment by pmuens** [comment]
> Testing whether a handler is valid or not should be independent of the vendor since it's just checking whether the file exist and the method exist within the file or not.

Yes. The main issue is that Google for example has no concept of a handler so in theory we cannot re-use the AWS related checks to check the `serverless.yml` against the exported module. I think the same is true for Azure 🤔 

> It will be language dependent though. Javascript is trivial but other languages might be trickier.

True. That is another important thing to keep in mind when working on an implementation for this.

**Comment by pmuens** [comment]
Closing since this is a stale issue and it's rather hard to abstract and implement this for all the runtimes.

**Comment by juanjoDiaz** [comment]
I agree that it might be challenging to implement it for all the runtimes.
But I think that's still relevant and valid.
And it should be trivial to implement for node (others runtime are another thing).

This was also requested in #5570.

Implementing very useful features like #3270 (#4075) completely loses its value if we don't check the basic thing: that the handler is there 🙂
