### ISSUE TITLE
How do you hook into the lambda kinesis stream event

### ISSUE THREAD

**Issue by grandmore** [serverless/serverless#376]
I have a dynamoDB routine that gets triggered from new records in the kinesis stream. I wanted to move my code over to Serverless because of version management etc.

How do I hook the event into Serverless? I have installed the serverless-plugin-boilerplate and can trigger it via the CLI, but I need help understanding the plugin

Thanks.

**Comment by grandmore** [comment]
Are we waiting on merging the Event Sourcing PR https://github.com/serverless/serverless/pull/214 to do this?

**Comment by eahefnawy** [comment]
yep! we're currently working on supporting this. Stay tuned!

**Comment by grandmore** [comment]
Thanks for letting  me know.

**Comment by eahefnawy** [comment]
you can also monitor our progress on our [Trello Board](https://trello.com/b/EX6SxBJJ/serverless)

**Comment by grandmore** [comment]
Thanks for the heads up.

**Comment by grandmore** [comment]
Is there any documentation on how to call serverless from Kinesis events?
