### ISSUE TITLE
unable to login to azure

### ISSUE THREAD

**Issue by si458** [serverless/serverless#3774]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong? serverless wont login to azure
* What did you expect should have happened? login to azure
* What was the config you used? default, no chances at all
* What stacktrace or error message from your provider did you see?
SiMacBookPro:MyPingCheck Simon$ serverless deploy
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: XXXXXXXX

it just seems to sit there after i auth in browser and nothing happens

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.1
* ***Operating System***: OSX 10.12.5
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @si458 thanks for opening 👍 

Could you please re-open this issue in the Azure Functions Provider plugin repo (https://github.com/serverless/serverless-azure-functions/issues) since the Microsoft Team might know more?

Thanks in advance!

**Comment by si458** [comment]
after much hard work today i managed to get it working by setting up the credentials manually from the credentials page and using exports at cmd line

**Comment by pmuens** [comment]
> after much hard work today i managed to get it working by setting up the credentials manually from the credentials page and using exports at cmd line

Thanks for sharing the solution @si458 👍

**Comment by Alber70g** [comment]
@si458 Could you point me to a step-by-step guide for this. I'm really struggling with it 😞

**Comment by si458** [comment]
@Alber70g i cant remember how i did it
but if you do an npm install inside your project folder, it will now download the updated serverless-azure-functions package which has fixed this issue now :)
