### ISSUE TITLE
(Google Cloud Functions) Deploy Fails the service's name is too long ?

### ISSUE THREAD

**Issue by El-Fitz** [serverless/serverless#3775]
# This is a (Bug Report)

## Description

* sls deploy failed on "Creating Deployment" when the service name was long (_WSLeadsIntakeDexi_ and _WS-LeadsIntake-Dexi_), but not when it was short (_efoz_)
* Maybe it can't take such names (provider limitations), but in this case it would be nice to state the service's name constraints on failure (and explicit them in the getting started too) instead of letting us brute / random-force a valid name :-)

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.2
* ***Operating System***: macOS 10.12.4
* ***Stack Trace***:

Serverless: Packaging service...
Serverless: Compiling function "first"...
Serverless: Creating deployment...

  Error --------------------------------------------------

  Error: Invalid value for field 'resource.name': 'sls-WebsitesLeadsIntakeDexi-dev'.  Name of the resource 'sls-WebsitesLeadsIntakeDexi-dev' is not valid

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.2.0
     Serverless Version:     1.15.2

* ***Provider Error messages***: ? Where do I get this ?

**Comment by pmuens** [comment]
Hey @El-Fitz thanks for opening! 👍 

🤔 yes, the name could be too long. Not 100% sure though (maybe there's something in the Google Cloud docs --> https://cloud.google.com/docs/).

Could you re-open this issue in the Google Cloud Functions Provider plugin repo (https://github.com/serverless/serverless-google-cloudfunctions) since this is the core Serverless Framework repository?

Thanks in advance!

**Comment by El-Fitz** [comment]
Sure, as soon as I get back to my computer :-)

**Comment by pmuens** [comment]
> Sure, as soon as I get back to my computer :-)

Great! Thanks @El-Fitz 👍
