### ISSUE TITLE
CLI Autocomplete duplicates some commands/options

### ISSUE THREAD

**Issue by ryanmurakami** [serverless/serverless#3777]
# This is a Bug Report

## Description

CLI Autocomplete appears to duplicate some entries when hitting <tab><tab>. The `autocomplete.json` file does not contain these duplicates. I've tried both Iterm and Terminal and get the same results. Not sure if the bug is in the CLI, tabtab, or my setup.

<img width="856" alt="screen shot 2017-06-10 at 12 59 09 pm" src="https://user-images.githubusercontent.com/767105/27013552-d9bcce50-4e9a-11e7-9ae5-ffa1d0b70e56.png">

<img width="859" alt="screen shot 2017-06-10 at 12 59 18 pm" src="https://user-images.githubusercontent.com/767105/27013554-dfc57162-4e9a-11e7-9424-b8f5a2156368.png">

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.2
* ***Operating System***: macOS 10.12.5
* ***iTerm2 Version you're using***: 3.1.beta.4
* ***Terminal Version you're using***: 2.7.2 (388.1)

**Comment by pmuens** [comment]
Thanks for opening @ryanmurakami 👍 

🤔 that's interesting. Might have smth. todo with the caching.

Could you share your `serverless.yml` file?

/cc @eahefnawy

**Comment by ryanmurakami** [comment]
Yep, it's super basic, I was just trying to play with the new autocomplete stuff. :-D

Also including the `autocomplete.json`. I've deleted the cache a few times to start from scratch, just to make sure it wasn't messing that up. 

```yaml
# serverless.yml

service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
```

```json
# autocomplete.json
{
  "commands": {
    "config": [
      "credentials"
    ],
    "create": [
      "--template",
      "--path",
      "--name"
    ],
    "install": [
      "--url",
      "--name"
    ],
    "package": [
      "--stage",
      "--region",
      "--package",
      "function"
    ],
    "deploy": [
      "--stage",
      "--region",
      "--package",
      "--verbose",
      "function",
      "list"
    ],
    "invoke": [
      "--function",
      "--stage",
      "--region",
      "--path",
      "--type",
      "--log",
      "--data",
      "local"
    ],
    "info": [
      "--stage",
      "--region",
      "--verbose"
    ],
    "logs": [
      "--function",
      "--stage",
      "--region",
      "--tail",
      "--startTime",
      "--filter",
      "--interval"
    ],
    "login": [],
    "logout": [],
    "metrics": [
      "--function",
      "--stage",
      "--region",
      "--startTime",
      "--endTime"
    ],
    "remove": [
      "--stage",
      "--region",
      "--verbose"
    ],
    "rollback": [
      "--timestamp",
      "--verbose",
      "function"
    ],
    "slstats": [
      "--enable",
      "--disable"
    ]
  },
  "validationHash": "6b0a191c3d82511b73bd8c70611e8daf0ead60b826e26606a7a582d026f39141"
```

**Comment by pmuens** [comment]
Thanks for sharing the details @ryanmurakami 👍 

We'll look into it!

**Comment by ryanmurakami** [comment]
@pmuens Awesome! Thanks! Let me know if you need anymore info. I'll also try it on my work laptop tomorrow and see if it repros there as well.

**Comment by brianneisler** [comment]
@ryanmurakami seems possible that completion command is getting run twice. Can you check your `~/.zshrc` and look for possible duplicates?

**Comment by ryanmurakami** [comment]
@brianneisler Good idea! I do see two entries for `tabtab`, but I believe they're attaching separately to the `serverless` and `sls` command. Below is my entire `.zshrc`. I was also about to get the exact same results on my work computer.

```bash
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/rylewis/.oh-my-zsh

ZSH_THEME=""

plugins=(git)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U promptinit; promptinit
prompt pure

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/rylewis/Documents/Dev/Repo/globalcontactus/renderService/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/rylewis/Documents/Dev/Repo/globalcontactus/renderService/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/rylewis/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/rylewis/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
```

**Comment by ryanmurakami** [comment]
I also tried removing everything from my `.zshrc` file, running vanilla, and had the exact same experience.

**Comment by eahefnawy** [comment]
interesting observation. Might be an issue with tabtab and `.zshrc`, do you have access to a `.bashrc` setup where we can validate that?

**Comment by jazen** [comment]
FYI I've noticed that running

```
node ~/.config/yarn/global/node_modules/serverless/scripts/postinstall.js
```

won't do/output anything if there are already the mentioned `tabtab` lines in `~/.zshrc` (even if outcommented) — removing them and re-running does work here.

The "duplicates" bug is still there though.
