### ISSUE TITLE
DX: Commands should be listed alphabetically in help

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3784]
# This is a Bug Report

## Description
Commands should be listed alphabetically when running `sls --help`

* What went wrong?
Not all commands are listed in alphabetical order.

<img width="695" alt="hyper" src="https://user-images.githubusercontent.com/1471972/27046538-ade7089e-4f59-11e7-931e-87819bb9d7d9.png">

## Additional Data

* Serverless Framework Version: 1.15.3
* Operating System: OSX 10.12.4

**Comment by HyperBrain** [comment]
Currently the commands are listed by the order of their definition. This leads to the commands being grouped by their defining plugins implicitly. IMO neither an alphabetic nor a plugin based order is right or wrong as both are discussable.
What if we'd add a sort option to the help command, with alphabetic being the default.

**Comment by ryanmurakami** [comment]
I wonder if there are any metrics on which are used the most? Plugins might make that awkward, but I'd rather order a more logical way than alphabetic.

**Comment by brianneisler** [comment]
> Currently the commands are listed by the order of their definition. This leads to the commands being grouped by their defining plugins implicitly.

@HyperBrain good insights as usual 👍 

I'm not sure that the plugin based ordering is immediately obvious to the greater chunk of the user base (mainly because they're unaware that plugins and commands are related until they've really dug in to the code). I've seen this a few times now watching new users of the framework explore the commands. Their comments are "hey, your commands are out of order"

> What if we'd add a sort option to the help command, with alphabetic being the default.

I like this as being an option. Potentially it would be nice to have them displayed under plugin headers. This seems like a feature that power users would get the most use out of, specifically plugin authors and framework maintainers.

Maybe something to this effect? 
```
Commands by plugin

AwsConfigCredentials
  config credentials ............ Configures a new provider profile for the Serverless Framework

Config
  config ........................ Configure Serverless

Create
  create ........................ Create new Serverless service

Deploy
  deploy ........................ Deploy a Serverless service
  deploy function ............... Deploy a single function from the service
  deploy list ................... List deployed version of your Serverless Service
   deploy list functions ......... List all the deployed functions and their versions

Info
  info .......................... Display information about the service

Install
  install ....................... Install a Serverless service from GitHub

Invoke
  invoke ........................ Invoke a deployed function
  invoke local .................. Invoke function locally

Login
  login ......................... Login or sign up for the Serverless Platform
  logout ........................ Logout from the Serverless Platform 

Logs
  logs .......................... Output the logs of a deployed function

Metrics
  metrics ....................... Show metrics for a specific function

Package
  package ....................... Packages a Serverless service

Remove
  remove ........................ Remove Serverless service and all resources

Rollback
  rollback ...................... Rollback the Serverless service to a specific deployment
  rollback function ............. Rollback the function to the previous version

SlStats
  slstats ....................... Enable or disable stats
```

**Comment by brianneisler** [comment]
> I wonder if there are any metrics on which are used the most? Plugins might make that awkward, but I'd rather order a more logical way than alphabetic.

@ryanmurakami any thoughts around more useful ways of ordering? I can't think of much else other than alphabetical and grouping by plugin.

**Comment by HyperBrain** [comment]
I like the idea with the plugin headers, Looks very structured and explanatory to me. This would also reveal quickly which plugins are installed/active.

**Comment by ryanmurakami** [comment]
@brianneisler Yep, love what you did. Plugin ordering makes the a lot of sense.

**Comment by pmuens** [comment]
Also +1 for the headers. Only downside could be that most of our provider plugins are prefixed with the provider name. So e.g. `AwsDeploy` or `AwsMetrics` which could look a little bit ugly.

**Comment by HyperBrain** [comment]
@pmuens A pragmatic solution for the names would be that every plugin gets a `displayName` property that is set to a human-readable name and used in the help screen instead of the class names.

**Comment by pmuens** [comment]
> @pmuens A pragmatic solution for the names would be that every plugin gets a displayName property that is set to a human-readable name and used in the help screen instead of the class names.

Thats sounds like a good solution 👍

**Comment by darkowlzz** [comment]
I would like to work on this, if no one else is already working on it 😊

**Comment by pmuens** [comment]
> I would like to work on this, if no one else is already working on it 😊

Awesome @darkowlzz 👍 Let us know if you need any assistance!
