### ISSUE TITLE
Don't automatically parse input to JSON when using invoke and invoke local

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3788]
# This is a Feature Proposal

## Description

Currently we're assuming that the input for the `invoke` and `invoke local` command is a string which can be parsed (and will be parsed) into JSON.

However some AWS services assume other inputs.

We should update the `invoke` and `invoke local` command to reflect that (see: https://github.com/serverless/serverless/issues/2833#issuecomment-264207737 and https://github.com/serverless/serverless/issues/2833#issuecomment-306232952).

Thanks @wxs and @dzimine for bringing this up 👍

**Comment by dzimine** [comment]
Please take a look at the PR #4036 and see if you're ok with:
1) parsing by default - my reason is "not break current user's experience", someone may be using it already. 
2) `--raw` - happy to take a better suggestion

**Comment by pmuens** [comment]
> Please take a look at the PR #4036 

Great! Thanks for taking a stab at it @dzimine 🎉. The implementation sounds reasonable 👍.

We'll look into it ASAP!
