### ISSUE TITLE
Can't read file from scoped javascript package

### ISSUE THREAD

**Issue by lylethompson** [serverless/serverless#3790]
# This is a (Bug Report / Feature Proposal)

## Description

Attempting to use a file macro, e.g.

environment:
  myVariable: ${file(./node_modules/@ mycompany/myscript.js)} 

results in no error and just puts the text (e.g.${file(./node_modules/@ mycompany/myscript.js)}) into the target environment instead of executing the function in the file and putting that in the target environment.

expected the return value of the myscript() function to be placed in the environment variable OR an error message that the script was not found.

I suspect the @ sign fools the parser.

## Additional Data

* ***Serverless Framework Version you're using***:  1.14.0
* ***Operating System***: Centos 7
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by lylethompson** [comment]
Note: I had to put an extraneous space after the '@' above for it to show the full path.

**Comment by pmuens** [comment]
Hey @lylethompson thanks for opening.

You need to specify the exported function you want to use here.

So e.g. `${file(./node_modules/mycompany/myscript.js):helloWorld}`

That should do the trick.

You can find more about this feature in the docs about Serverless Variables:
https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files
