### ISSUE TITLE
Add global.json to csharp template

### ISSUE THREAD

**Issue by vgaltes** [serverless/serverless#3795]
# This is a bug report

## Description
.Net core has changed the way they define projects and solutions. The CSharp template created by the framework works well as long as you can build it with an older SDK version. So, if you've just dowload the last version of .Net core, create a CSharp project using serverless and try to run commands like `dotnet restore` or `dotnet build` you will get an error. 

The way to avoid it is to create a build.json file with the following contents:
```
{
    "sdk": {
        "version": "1.0.0-preview2-003131"
    }
}
```
When you run a dotnet command, the CLI tries to find this file in your current folder or any parent folders. The recommendation is to put the file at solution level, not at project level. So, it would be great if your framework creates the file in the folder that the user run the create command, not in the created folder.

To check that the CLI is using the right version:
- Install the right version of the SDK (https://github.com/dotnet/core/blob/master/release-notes/download-archive.md)
- Run dotnet --version (you should see 1.0.0-preview2-003131 in your terminal window)

I'm using the version 1.15.3 of the serverless framework.

**Comment by pmuens** [comment]
Thanks for mentioning that @vgaltes 👍 

Could yo submit a quick PR for that? Thanks in advance!

**Comment by vgaltes** [comment]
Thanks @pmuens, I can submit a quick PR to add the global.json to the csharp template, but that will create the file in the project folder. I think it would be better to create the file at the solution level. Is that something easy to do?

Thanks!

**Comment by pmuens** [comment]
> I can submit a quick PR

@vgaltes That would be super nice 👍 

> I think it would be better to create the file at the solution level. Is that something easy to do?

What exactly do you mean when you say solution level? Isn't the solution level the root directory where you'll also find the `serverless.yml` file?

**Comment by vgaltes** [comment]
What I mean (probably I'm wrong) is that if, for example, I want to develop several lambdas, I will have a structure like:
```
- Main folder
    - Lambda 1 folder
        - serverless.yml
        - scr folder
             - code
        - test folder
              - code
    - Lambda 2 folder
        - serverless.yml
        - scr folder
             - code
        - test folder
              - code
```
In this case, the global.json only needs to be under the main folder, not in every lambda. But I guess that it doesn't hurt if we add the file under each lambda folder. I'll submit the PR 😃

**Comment by vgaltes** [comment]
Hi @pmuens . Sorry, is there any guide on how to run the integration tests around the templates? Thanks!

**Comment by pmuens** [comment]
Hey @vgaltes yes, adding them to every Lambda (so basically in the root of the template) would be the best solution. Power-Users could change that later if they want.

Instructions on how to test the templates can be found here: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#testing-templates

You might also want to update the test and check for the existence of the new file in the [tests](https://github.com/serverless/serverless/blob/a15f980a44d426d8806ce6f63ca61db509f46676/lib/plugins/create/create.test.js#L102-L122) for the `create` plugin.

**Comment by vgaltes** [comment]
Yep, that was what I wanted to do... I'm having an error after executing the tests:
```
Creating Application
Creating network "serverless_default" with the default driver
module.js:487
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/lib/Serverless.js:3:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by vgaltes** [comment]
Hi @pmuens , sorry for bothering you again. I've been investigating and testing a little bit and it's possible to use the last version of .Net Core (the one with the .csproj instead of the project.json). I've wrote an article about it: https://www.youtube.com/watch?v=pNI-xkN_h0Y&t=452s

I think that instead of adding the global.json we should change the template so that we can use the last version of .Net Core. I can add a template for a F# project as well.

Thanks,
Vicenç

**Comment by pmuens** [comment]
Hey @vgaltes that sounds reasonable 🤔 

We had an update for the toolings in the making by @slang25 in #3391. He also PRed the F# template in #3045.

Unfortunately the changes failed on my machine.

Would be really nice if we could get the tooling update and a F# template up and running. 👍

**Comment by slang25** [comment]
Hello again

Good news, I have found what was causing the issues on the previous PRs, when zipping up the package the aws dotnet lambda sdk would use `zip` if it found it on your path, if not it would use the built in .NET compression library, when it did the latter the files in the zip had the wrong permission.

I will resurrect both PRs later today and bring them up to scratch. I think pinning the sdk version a global.json is a good idea, as the sdk on the machine will move forwards while we'll need to match what AWS support.

**Comment by vgaltes** [comment]
Hello both,

that's awesome. I agree it would be good idea to pin the SDK version in the global.json. Things change quickly in the .Net core land :P

So I think we can close this issue waiting for @slang25 PR? Let me know if I can help you.

I've noticed that there's no C# or F# template when using the Azure provider. It would be great to add one there as well.

Thanks!

**Comment by pmuens** [comment]
> I will resurrect both PRs later today and bring them up to scratch.

@slang25 that sounds fantastic! Thanks for taking the time to look into this. Really looking forward to the PRs 👍 

> So I think we can close this issue waiting for @slang25 PR? Let me know if I can help you.

Yes, I agree. I'll close this one for now. But thanks @vgaltes for opening to discuss this enhancement 👍 

> I've noticed that there's no C# or F# template when using the Azure provider. It would be great to add one there as well.

Yes 👍 PRs are always welcomed 😊
