### ISSUE TITLE
DynamoDB Autoscaling

### ISSUE THREAD

**Issue by simplesteph** [serverless/serverless#3803]
# This is a Feature Proposal

## Description

Recently AWS announced autoscaling for DynamoDB https://aws.amazon.com/blogs/aws/new-auto-scaling-for-amazon-dynamodb/
It would be amazing to have the ability to create DynamoDB tables with autoscaling on by providing the rights parameters

**Comment by pmuens** [comment]
@simplesteph thanks for opening up this issue!

Serverless supports the definition of DynamoDB tables as CloudFormation resources in the `resources.Resources` section of your `serverless.yml` file.

This way you can use everything AWS provides through CloudFormation.

Right now Serverless doesn't have a direct integration with DynamoDB through an abstraction layer.

But if setting the autoscaling parameters through CloudFormation is supported you should be able to set them.

Here's how such a table definition looks like: https://github.com/serverless/examples/blob/f9e98e8d8113a882d0068c4edf4ec42b9aade626/aws-node-rest-api-with-dynamodb/serverless.yml#L64-L79

**Comment by simplesteph** [comment]
@pmuens amazing! Can the example you quoted be augmented to show autoscaling just for future reference?

**Comment by pmuens** [comment]
It seems like autoscaling was not added to the DynamoDB Table CloudFormation resource yet. But you could use everything which is described here as soon as it's made globally available by AWS:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html

**Comment by sbstjn** [comment]
@simplesteph I published a [serverless-dynamodb-autosclaing](https://github.com/sbstjn/serverless-dynamodb-autoscaling) plugin to handle Auto Scaling. In the repository is an example how to create a DynamoDB table as well.

**Comment by shawnemullen** [comment]
i installed the plugin and created configs, but nothing seems to happen when I deploy.  The deployment runs with no errors but the autoscaling settings in the dynamodb console do not change.  Am I missing something?

**Comment by pmuens** [comment]
@shawnemullen thanks for commenting! Could you open up an issue in the plugin repository so that it's tracked there (https://github.com/sbstjn/serverless-dynamodb-autoscaling/issues)? Thanks in advance

/cc @sbstjn

**Comment by ronkot** [comment]
Now CloudFormation seems to support DynamoDB table autoscaling (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html). I'm not very familiar with serverless, CF, roles, policies and stuff. If someone could provide a miniman working example, I'd be super gratefull!! 🙏

**Comment by garethmcc** [comment]
That link doesn't seem to indicate that auto scaling is supported. There's no definition of the configuration options for CF to do so. We have been able to do this for a while though using the serverless plugin at https://github.com/sbstjn/serverless-dynamodb-autoscaling but it does so outside of CF. So if you really need to support defining autoscaling settings on deployment of your service I can recommend that plugin, I've been using it for a few months.

**Comment by delprofundo** [comment]
ive been doing this manually via Resources for about 9 months. Are you after an example like that or a plugin? I can try and pull out some yaml over the weenend, i think i may have made a vid for a client about it too which ill look for.

**Comment by ronkot** [comment]
@garethmcc As I said, I'm not very deep in CF magic, but this section of the previously mentioned page seems like autoscaling is supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-examples-application-autoscaling

@delprofundo I'd like to use autoscaling without a plugin. If that's possible, a working yaml would be very helpful! That could maybe be also added to serverless repo examples.

**Comment by pmuens** [comment]
Closing since this can be done via custom resources or plugins.

Feel free to conitnue the discussion.
