### ISSUE TITLE
Serverless config should allow override of profiles

### ISSUE THREAD

**Issue by simplesteph** [serverless/serverless#3809]
# This is a Feature Proposal

## Description

When trying to setup an existing profile I get an error
```
serverless config credentials --provider aws --key XXX --secret YYY --profile serverless-admin
Serverless: Setting up AWS...
Serverless: Saving your AWS profile in "~/.aws/credentials"...
Serverless: Failed! ~/.aws/credentials exists and already has a "serverless-admin" profile.
```

At the very least I would expect a prompt asking me if I want to override credentials as existing ones have already been found

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.3
* ***Operating System***: Mac

**Comment by pmuens** [comment]
Hey @simplesteph thanks for opening 👍 

The main purpose for the error message is that we don't want to manipulate existing configurations due to potential loss / corruption of data.

Allowing only the creation of non-existent profiles enables us a way to streamline the onboarding process while still maintaining a safe way to deal with the `credentials` file.

**Comment by medhoover** [comment]
@pmuens 
An overwrite option is also a clean and simple solution.
I would be happy to help in this 👍

**Comment by pmuens** [comment]
> An overwrite option is also a clean and simple solution.

@medhoover Yes, that would be a good solution. This should be forced by the user so that he's aware of "potential damage".

> I would be happy to help in this 👍

Great! I'll update the status of the issue. Let us know if you need any help with the implementation 👍

**Comment by medhoover** [comment]
@pmuens I had a quick look at the possible options to update the credentials file and It seems that we have to implement all the logic as I could not find a suitable package to handle this. We could imitate the [aws-cli config writer](https://github.com/aws/aws-cli/blob/e2295b022db35eea9fec7e6c5540d06dbd6e588b/awscli/customizations/configure/writer.py)
For the option flag, I suggest: ` --overwrite | -o`

**Comment by pmuens** [comment]
Hey @medhoover thanks for researching and working on the proposal 👍 

> For the option flag, I suggest: --overwrite | -o

Yes, that sounds like a good choice for the flag.

> we have to implement all the logic as I couldn't find a suitable package to handle this. We could imitate the aws-cli config writer

That sounds good to me 👍. Is there maybe smth. in the AWS Node.js SDK we could utilize?

**Comment by pmuens** [comment]
> We could use the SharedIniFileCredentials to check if the profile exists and to load the existing properties, this should reduce the amount of work.

@medhoover that sounds like a good plan.

> I'll start the work.

Great to hear that! 👍

Let us know if you need any help / face any problems!
