### ISSUE TITLE
Openwhisk sequence actions cannot be deployed

### ISSUE THREAD

**Issue by cjelger** [serverless/serverless#3820]
Openwhisk supports so-called `sequence` actions, where a sequence only defines a chain of actions. The check recently introduced in https://github.com/serverless/serverless/pull/3729 prevents Openwhisk sequences to be deployed because by definition, a sequence does not have any code, so when packaged individually, the deployment of a sequence fails.

cc: @alexcasalboni and @pmuens, and also @jthomas for serverless-openwhisk

For bug reports:
* What went wrong? Deployment failed.
* What did you expect should have happened? Deployment should have succeeded.
* What was the config you used?

```
service: test

# We package each function in a separate zip
package:
  individually: true
  exclude:
    - ./**

provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true

plugins:
  - serverless-openwhisk

functions:

  action1:
    handler: src/action1/index.main
    package:
      include:
        - src/action1/**

  action2:
    handler: src/action2/index.main
    package:
      include:
        - src/action2/**
        
  actionSequence:
    sequence:
      - action1
      - action2
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

  No file matches include / exclude patterns

  Stack Trace --------------------------------------------

ServerlessError: No file matches include / exclude patterns
    at Package.zipDirectory (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:45:21)
    at Package.packageFunction (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:77:17)
    at _.map.functionName (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:39:21)
    at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9571:14)
    at Package.packageService (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:34:31)
From previous event:
    at Object.package:createDeploymentArtifacts [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/package/package.js:62:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:266:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:88:48)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:86:8)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:273:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:105:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:92:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:30:50)
```

**Comment by alexcasalboni** [comment]
Hi @cjelger, that message shows up only when nothing on the file-system matched your include/exclude patterns. I guess something went wrong with this configuration:

```yml
package:
  individually: true
  exclude:
    - ./**
```

Do you actually need to exclude _everything_ to make individual packaging work?

**Comment by cjelger** [comment]
Actually the error happens because of https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/zipService.js#L72-L76 which means the 'globby' function call didn't match any file. This is correct because an OpenWhisk sequence doesn't have any file. I think the code should only check if the function has a sequence attribute: in this case it can even entirely skip the packaging phase (not sure if this is then needed for the deployment, @jthomas do you know that?).

**Comment by alexcasalboni** [comment]
Agreed! If no package is needed we should just NOT invoke the zipService.

**Comment by cjelger** [comment]
I did a quick fix [here](https://github.com/cjelger/serverless/commit/edad55e763f1b1c1771c211f1577d267b17428f5), does it make sense to you?

**Comment by alexcasalboni** [comment]
It looks like it'd work fine.

Just wondering.. is this something the [serverless-openwhisk](https://github.com/serverless/serverless-openwhisk) plugin could take care of, without adding this special case to the core?

**Comment by pmuens** [comment]
Thanks for opening @cjelger 👍 

> Agreed! If no package is needed we should just NOT invoke the zipService.

That looks like the way to go. I'd also love to see this in the OpenWhisk plugin (as @alexcasalboni mentioned above) if possible since this is a really provider specific behavior.

**Comment by cjelger** [comment]
Yes it makes sense, but the serverless-openwhisk plugin doesn't yet have any code and hooks for the 'package' phase so it will require more work. I don't know anything about the "lifecycle" hooks in serverless, but if it's possible to override in the plugin the default package:createDeploymentArtifacts hook, and still call the core parent hook, then yes it should be easy to add the extra test and skip the core package:createDeploymentArtifacts hook if it's a sequence. Is this feasible?

**Comment by jthomas** [comment]
Hello 👋.

Thanks for the investigation on this @cjelger, another user also reported this recently and I have an open ticket to look into this:
https://github.com/serverless/serverless-openwhisk/issues/62

I agree with @pmuens that this should be fixed in the provider plugin. I will dig into the provider code soon and work out if this can be fixed without any upstream changes.

**Comment by pmuens** [comment]
Thanks for looking into this @jthomas 👍 

Sorry for the inconveniences. We were not aware of the sequence feature until @cjelger brought it up in the "exclude dev dependencies" PR.

Let us know if you need any help / more context for the OpenWhisk plugin.

**Comment by jthomas** [comment]
Looking at the serverless code and the openwhisk plugin, I don't think there's a nice way to fix this without an upstream change.

My solution would be this change, which is close to what @cjelger suggested. 
https://github.com/serverless/serverless/compare/master...jthomas:master

Functions would now support the following option.
```
functions:
  hello_world:
    package:
      ignore: true
```

These functions would not trigger the `packageFunction` call or set the `packageService` flag to true. 

I've used the `ignore` flag as I think there might be future scenarios where providers want the ability to stop packaging from the framework. It should be less vendor specific than `seq`. 

If we support this change, I will modify the openwhisk provider plugin to automatically add this flag to all sequence functions using a pre-process hook. 

Without this upstream modification, I will have to try and monkey patch code in the framework or manually remove the functions from memory before the packaging plugin is ran and restate them afterwards. Neither of these feels as sensible as the change outlined above. 

@pmuens @alexcasalboni what do you think? I can open the PR if you agree with this.

**Comment by alexcasalboni** [comment]
I like the idea of a generic solution that might cover new scenarios in the future.

The only alternative I can think of (to avoid a new config param) would be adding a whole new hook so that plugins can jump in and disable packaging if/when needed. But that would be a more complex implementation, and harder to use without a plugin.

**Comment by HyperBrain** [comment]
I would prefer `disable` as option name, as it effectively disables packaging of the particular function. Imo packaging cannot be 'ignored' - sounds strange.

**Comment by cjelger** [comment]
I think being able to ignore/disable (what about simply having `true|false`) the packaging for other providers might also be useful in the future if something like an Openwhisk sequence also appears on another platform so +1 for me to implement this in the core.

**Comment by jthomas** [comment]
Good suggestion on using `disable` rather than `ignore` @HyperBrain. That makes more sense. 

I'll open the PR referencing this discussion.

**Comment by pmuens** [comment]
Thanks for the conversation everyone! And thanks for the PR @jthomas 👍 

We'll look into it ASAP.
