### ISSUE TITLE
Excluding dev dependencies throws Error

### ISSUE THREAD

**Issue by ryanmurakami** [serverless/serverless#3827]
# This is a Bug Report

## Description

When packaging a serverless project, the dev dependency exclusion does not happen. It throws an Error that is caught with no action. 

The `excludeNodeDevDependencies` function in `/lib/plugins/package/lib/zipService.js` throws when it calls:

```js
const prodDependencies = childProcess
        .execSync('npm ls --prod=true --parseable=true --silent', {
          maxBuffer: 2000*1024
        })
        .toString().trim();
```

When catching the thrown error, it seems that the command is partially run, as there are some directories listed in `stdout`, but they stop in the middle. The `error` property is null, but the `status` is `1`. Here's a stack trace:

```sh
Error: Command failed: npm ls --prod=true --parseable=true --silent

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at _.forEach (/Users/rylewis/Documents/Dev/Repo/serverless/lib/plugins/package/lib/zipService.js:145:10)
    at arrayEach (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/lodash/lodash.js:9359:14)
    at excludeNodeDevDependencies (/Users/rylewis/Documents/Dev/Repo/serverless/lib/plugins/package/lib/zipService.js:136:7)
    at Package.excludeDevDependencies (/Users/rylewis/Documents/Dev/Repo/serverless/lib/plugins/package/lib/zipService.js:30:25)
    at Package.tryCatcher (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/rylewis/Documents/Dev/Repo/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I've tried increasing the `timeout` and `maxBuffer` options, but no change. Running the command `npm ls --prod=true --parseable=true --silent` in my shell works correctly and returns all the directories.

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.0
* ***Operating System***: macOS

**Comment by ryanmurakami** [comment]
I've also tried pulling the dependencies/devDependencies into a fresh project's `package.json`. This issue does not reproduce. It seems like it's only happening for existing projects. I can try it with a few other services we have tomorrow.

**Comment by pmuens** [comment]
Thanks for the in-depth analysis @ryanmurakami 👍 

That's really helpful. We'll try to reproduce it as well.

**Comment by cjelger** [comment]
Try to replace the code with `childProcess.execSync('npm ls --prod=true --parseable=true || true);` which ensures that the npm command returns 0 to the shell. Somehow `npm ls` returns 1 as soon as a minor issue happens when parsing the dependencies.

**Comment by pmuens** [comment]
Thinking through this once again, my assumption is that the `execSync` buffer is just full since there a dozens of packages which should be excluded in large projects.

Will try to reproduce it tomorrow by adding a bunch of dev dependencies and running the `serverless package` command. That should break it once there are too many dev-dependencies. This should hold true for just one `package.json` file in the root directory.

I'll report back once I tested it out.

**Comment by ryanmurakami** [comment]
I tried setting a crazy high buffer limit on `execSync` and the same thing happened. 

One thing I notice, the exact same project works fine when building on our Jenkins server. The code is the same, just the environment is different. I wonder if the real issue is maybe something outside of what Serverless is doing here. I'll try cloning my project somewhere clean locally and see if I can repro the issue.

**Comment by ryanmurakami** [comment]
For the record, cloning into a different directory didn't change the result, still no exclusions.

**Comment by pmuens** [comment]
Thanks for the further investigation @ryanmurakami 👍 

> One thing I notice, the exact same project works fine when building on our Jenkins server.

That's interesting 🤔 

I have one question. Does this really throw an error where Serverless exits the process? I wrapped it in a `try` / `catch` so that it should fail silently when an error pops up. Failing loudly would be really bad.

**Comment by pmuens** [comment]
Ok. So I debugged this behavior today. Here are my findings:

- Everything works fine if you've got only one `package.json` with dozens of dev dependencies
- It breaks if you add another `package.json` files in a nested dir and keep the one which has dozens of dev dependencies

I also refactored the code to be promise based because I thought that it might be something with the `cwd` and the sync execution. However it still fails after the refactoring.

I'll PR the refactored changes soon because I think that they're more elegant compared the current solution.

---

Other solution would be to use a directory traversal and reproduce the stuff `npm ls` does, but I'm not sure if this adds too much complexity.

**Comment by pmuens** [comment]
Holy cow! I think I've found the problem!


Let's assume we have the following directory structure:

```
|__ package.json
|__ node_modules
|__ 1st_level
    |__ package.json
```

In my case I had installed the packages in the root, but not in the `1st_level` dir.

`npm ls --prod=true --parseable=true --silent` will return the correct result of prod dependencies in the root dir (including the path of the root directory).

However when you've not installed packages (like it's the case in the `1st_level` dir) and run the command in that dir you'll get the path of the directory back, but no packages (since you've not installed anything).

It seems like `npm` returns an exit code 1 in that case, so the solution `|| true` @cjelger suggested should do the trick.

BTW. Is `|| true` OS independent? Is it supported on Windows?

Could you reproduce / confirm this behavior @ryanmurakami @cjelger ?

In the meantime I'll work on a PR which implements that fix (and adds async support).

**Comment by cjelger** [comment]
@pmuens I finally created a small dummy project to show you the problem. Check [here](https://github.com/cjelger/serverless-dev-dependencies)

Don't forget to `npm install` the top project and the 2 sub-projects under `src/`. Then globally install `serverless@1.16.0`, run `serverless package`, and have a look at the generated zip files in `.serverless`. They contain far too many dependencies!

**Comment by pmuens** [comment]
Nice! Thanks for compiling that @cjelger 👍 

Don't know if you saw it already, but I too did some research and came up with some observations in https://github.com/serverless/serverless/issues/3827#issuecomment-310638489 and https://github.com/serverless/serverless/issues/3827#issuecomment-310640142

**Comment by ryanmurakami** [comment]
@pmuens Here are some quick answers to previous questions/comments:

> I have one question. Does this really throw an error where Serverless exits the process? I wrapped it in a try / catch so that it should fail silently when an error pops up. Failing loudly would be really bad.

It's throwing from that `execSync` call and then being caught by your catch. So, not failing loudly, just completely silently. It might be a nice DX improvement to announce that error somehow, just so users know that their dev dependencies weren't excluded.

In reference to the nested package.json, for our project specifically, we don't have a nested structure like that. We do have several peer service directories, but each are packaged/deployed individually.

I'll keep messing around and try out @cjelger's test project too.

Thanks!

**Comment by ryanmurakami** [comment]
@cjelger Thanks for making the dummy project!
I gave it a shot, and it looks like serverless is packaging it correctly on my setup. The dev dependencies `mocha` and `mocha-jenkins-reporter` are not included in the zipped package that Serverless creates. So, it makes me think there is something specific with this project and your environment that is causing the issue.

**Comment by ryanmurakami** [comment]
I'm still working on it, but this issue seems exactly like what I'm experiencing:
https://github.com/nodejs/node/issues/12921

I've tried mixing up the type of output from that `npm ls` command and it always breaks off at 8192 bytes for the `stdio` buffer. @pmuens, what kind of environment are you running? I'm:
macOS: 10.12.5
Node.js: v6.10.3
npm: 5.0.3

Our Jenkins slave is running some linux distro with:
Node.js: v6.9.4
npm: v4.3.0

I'm wondering if this is a mac bug like that issue above describes...

**Comment by pmuens** [comment]
Nice findings! Thanks for yet another deep dive @ryanmurakami 👍 

nodejs/node#12921 could definitely be related!

> @pmuens, what kind of environment are you running?

My setup is the following:

```
Mac OS X: 10.12.5
Docker version: Version 17.03.1-ce-mac12 (17661) Channel: stable d1db12684b
Linux distro: Linux 1b2ae1b5b55e 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 GNU/Linux
node: v8.1.0
npm: 5.0.3
```

> It might be a nice DX improvement to announce that error somehow

That's a good idea. We could catch the error and see if it's related to `dev` dependency exclusion and print the log message. Otherwise it should still fail silently IMHO.

Next up I'll give @cjelger repo a spin.

**Comment by ryanmurakami** [comment]
@pmuens Hmm... so, running it in that Docker instance might be why it's working. This seems to be macOS only. Unless you can't repro it locally either.

So, I was thinking of some possible work arounds:
- Import the `npm` code and use the `ls` module itself to get the dependencies through that API. Not sure if this is even possible and is going to be horrible to maintain.
- Use the `package-lock.json` as a fallback if the `npm ls` command fails. I've noticed each dependency in the `package-lock.json` file has a `dev` property that we could use to filter them out. Not sure if that property means it isn't used in `prod` though.
- Pipe the `npm ls` output into a file and then parse that file. I'm thinking this might be the best way, but would require a little file i/o.

**Comment by pmuens** [comment]
> @pmuens Hmm... so, running it in that Docker instance might be why it's working

@ryanmurakami 🤔 it also failed in the container. The main reason is when I don't have the dependencies installed (no `node_modules` dir) or I don't have dev dependencies at all. My assumption is that `npm ls` returns with a process 1 in that case (see also https://github.com/serverless/serverless/issues/3827#issuecomment-310640142).

IMHO the first proposal (use the `npm ls` module itself) and the last one (pipe it into a file) would be possible solutions here.

The last one is pretty interesting. How would you pipe the data into the file if we still rely on `exec`? Or is the main problem the exceeded buffer for the console output?

**Comment by pmuens** [comment]
Just a quick update. Seems like @arabold found the root cause of this. He added a comment in the feature-PR here: https://github.com/serverless/serverless/pull/3737#issuecomment-312124143

Thanks for looking into it @arabold 👍

**Comment by pmuens** [comment]
Just another quick update on this one.

We've just started a PR which will include a fix for this (will be updated frequently). It can be found here: https://github.com/serverless/serverless/pull/3889
