### ISSUE TITLE
null (Service: AWSLambdaInternal; Status Code: 503; Error Code: ServiceUnavailableException

### ISSUE THREAD

**Issue by kijeungc** [serverless/serverless#3834]
Suddenly got this error msg on AWS lambda function console.
I got 'Internal server error' on the console before getting above msg.

**Comment by pmuens** [comment]
@kijeungc thanks for opening 👍 

Could you please provider more info about your config (`serverless.yml` file) and the Serverless version you're using?

Thanks!

**Comment by pmuens** [comment]
Ok. Just investigated further.

This seems to be related to an recent AWS Lambda outage.

I'll close this issue for now since this was smth. on AWS end and we cannot do smth. about it (it should've been resolved in the meantime).

Thanks again for opening @kijeungc 👍
