### ISSUE TITLE
Adding support for dotnetcore1.1

### ISSUE THREAD

**Issue by barfet** [serverless/serverless#3836]
Hello,

Thank you for your efforts!
I have a question regarding supporting `dotnetcore1.1`.
Is there any plans for this?

Thanks.

**Comment by slang25** [comment]
Lambda doesn't yet support `dotnetcore1.1`, so that would be a question to ask [here](https://github.com/aws/aws-lambda-dotnet). When/if it supports it, I would expect that aws-lambda-dotnet gets updated, and someone could then look at updating this template.

**Comment by pmuens** [comment]
Thanks for the question @barfet 👍 

And thanks for jumping in @slang25 👍 I'll close this for now since it's something which will be done in https://github.com/aws/aws-lambda-dotnet.

Feel free to continue the discussion.

**Comment by barfet** [comment]
Thanks for the replies!
Will use 1.0 version for now.
