### ISSUE TITLE
slss function run is not working correctly

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#384]
There are a few issues in the FunctionRun.js file.

1- The test event is not correctly populated
2- When run with the --name parameter, the function object is incorrectly set

I've made some modifications to this and can submit a pull request when I'm done if this is helpful. However, I do have few questions about the s-function.json format and where it is best to extract the function name, or if the SUtils.getFunctions should be parsing and populating it.

**Comment by ac360** [comment]
Thanks we'll get this fixed today!

**Comment by visualasparagus** [comment]
ok, sounds good. just let me know if you want me to submit a pull request later with what I've done. I've got to run for a bit now though.

**Comment by eahefnawy** [comment]
i just reproduced the issue....to make it more clear, whenever we try to run a function by name...another random function gets run instead.

as for the test event, is that what you're seeing:

```
{
  undefined: {}
}
```

if so, we've fixed the event.json issue, if it's something else....could you clarify a bit more?

**Comment by eahefnawy** [comment]
the name option issue is now resolved! thanks for reporting! Please keep it coming! :wink:

**Comment by visualasparagus** [comment]
Yes. I'll submit a pull request later as I'm now not at my computer. That way you can easily asses the issues. I'll also add a more thorough description of the issue.

Is the event.json fix in master?

**Comment by eahefnawy** [comment]
nope not yet...I'll push now

**Comment by eahefnawy** [comment]
done

**Comment by visualasparagus** [comment]
I've created a pull request related to this at #386

**Comment by visualasparagus** [comment]
I do have a few additional comments / questions regarding this.

**event.json**
it seems redundant to have the method/function name as the root element of the event.json. Why not just have it be the event itself. 
So instead of:
```
{
  "ModuleFunction": {"foo": "bar"}
}
```
Just:
```
{
  "foo": "bar"
}
```

**Function name**
This is confusing for 2 reasons.
1- when running `function run --name functionname` the match on [line 122](https://github.com/visualasparagus/serverless-function-run/blob/master/lib/actions/FunctionRun.js#L122) is misleading because you need to concatenate and PascalCase the module name and function name.
2- if the module and function name need to be combined for uniqueness I would suggest simply using the relative URI/path as the name w/o case changes. 

So `module/function` instead of `ModuleFunction`. 

This becomes even more apparent when the function name contains a hyphen as it becomes less readable. 

For instance `module/function-name` is now `ModuleFunction-name`

**Comment by ac360** [comment]
**event.json**
@visualasparagus Because you can have multiple functions in a `s-function.json`, therefore you need a way to specify multiple event properties.

**Function name**  
This is confusing.  I think we need to get rid of the Moudule names.

**Comment by vlamic** [comment]
@ac360 how about having multiple event.json?

**Comment by visualasparagus** [comment]
I've created a pull request #390 that removes the module prefix from the function name and also allows for function specific event.json files.

**Comment by visualasparagus** [comment]
happy to be of help. i like the project!

**Comment by visualasparagus** [comment]
@ac360 - I'm looking at this name thing again, and maybe it is actually good to include the module name, but in a way that is more clear, along with some general best practice guidelines. For instance if you had a users and posts module and then CRUD functions for each, you'd have collisions in the lambda naming. My initial reaction was to the naming conventions in the event.json and required by function run. They need to be namespaced though when deployed.

For naming, is it an idea to recommend camelCasing for module and function names and then we convert these to lower case hyphenation for the initial endpoint paths?

If you agree I can open a new issue for this and take a look at it.
