### ISSUE TITLE
C# missing documentation details

### ISSUE THREAD

**Issue by trondhindenes** [serverless/serverless#3853]
# This is a Bug Report

## Description
Trying to create a .Net core function using serverless.
1. The installation documentation doesnt mention anything about supported versions of .Net core
2. The documentation states run "build.cmd" with powershell, that file doesn't exist in a create project
3. `Serverless create` seems to create a project based on `project.json` - this is outdated (but since there's no mention of the .Net core versions supported there's no way to know if this should work or not.
4. Running `build.ps1` errors out stating that the working dir does not contain a project or solution file (I'm running .Net core 1.0.4)

In general, we need way better documentation before Serverless can be used with .Net core-based lambda functions.

**Comment by trondhindenes** [comment]
any movement on this?

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
