### ISSUE TITLE
Resource DynamoDb Error on deploy in another region

### ISSUE THREAD

**Issue by rdehnhardt** [serverless/serverless#3868]
# Bug Report

## Description

Deploy crashes when I try to deploy in multiple regions.

Ex: An error occurred while provisioning your stack: LocalesDynamoDbTable - locales-dev already exists.

**Comment by rdehnhardt** [comment]
I try use sa-east-1 region! (https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/)

**Comment by pmuens** [comment]
Hey @rdehnhardt thanks for opening 👍 

Could you please share your `serverless.yml` file and the steps you took to deploy so that we can dig into this?

Thanks!

**Comment by pmuens** [comment]
Ok. I took another look at your error messages.

This seems to be a duplicate of https://github.com/serverless/serverless/issues/3183.

I'll close this one since we track the progress in #3183. Feel free to chime in over there 👍
