### ISSUE TITLE
Function deploy in non-interactive mode

### ISSUE THREAD

**Issue by katspaugh** [serverless/serverless#387]
When I run this command on CircleCI:

    serverless function deploy

It gives the following error:

    serverless function deploy returned exit code 1

    { [ServerlessError: Sorry, this is only available in interactive mode] name: 'ServerlessError', messageId: undefined } Action failed: serverless function deploy

Am I missing some parameter?

**Comment by katspaugh** [comment]
In the source code I can see that the command [checks the `nonInteractive` option](https://github.com/serverless/serverless/blob/221a275bbc7b29a59d3ac1e6a18fd6ca27dacea4/lib/actions/FunctionDeploy.js#L102-L103), but I don't see this option to be passed from CLI anywhere.

**Comment by katspaugh** [comment]
Figured it out. Non-interactive mode means that you need to specify *stage* and *region* and which function (`-a` for all). So this command works without problem:

    serverless function deploy -s development -r eu-west-1 -a

**Comment by ac360** [comment]
Sorry about the confusion here @katspaugh.  This week we are improving our docs, which will help mitigate these issues in the future.  Thanks for being part of the community :)

**Comment by katspaugh** [comment]
No problem! You guys rock tremendously!
