### ISSUE TITLE
Fix dev dependency exclusion bug when too many node modules are used

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3874]
# This is a Bug Report

## Description

Right now we do a glob exclude of the whole `node_modules` directory and include only prod dependencies by using `npm ls` to identify them and a glob to re-include them.

However there's a bug with the maximum number of characters the buffer can hold.

Furthermore we should switch the behavior. We should list the dev dependencies and exclude them (while still including the whole `node_modules` directory) to ensure that the whole `node_modules` directory is still in included. Even if the command fails.

---

**Quick fix / other addition**

Add a config parameter which allows people to opt out of this feature.

---

Related #3827

**Comment by pmuens** [comment]
Quick update. "opt-out" support was added in #3877

**Comment by arabold** [comment]
Yes, that's exactly the issue we were running into. The size of the buffer seems to be 8k and thus a lot of our dependencies are missing. The opt-out support works around that.

**Comment by pmuens** [comment]
Just cross-referencing @arabold comment from the PR here: https://github.com/serverless/serverless/pull/3737#issuecomment-312124143

Thanks for looking into it 👍

**Comment by pmuens** [comment]
Adding a note here that we've just started a PR which will include a fix for this (will be updated frequently).

It can be found here: https://github.com/serverless/serverless/pull/3889
