### ISSUE TITLE
Reworking our integration tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3881]
# This is a Feature Proposal

## Description

Our current integration test setup got a little bit stale and needs some refreshments. This issue is meant to collect some feedback and ideas how we can improve our integration tests / testing and therefore ensure that the stability of our codebase is thoroughly exercised.

### Status quo

Right now Serverless has 2 main branches of integration tests

#### `Simple` integration tests

This test does the following:

1. Create a service with a template
2. Deploy the service
3. Update the code
4. Re-Deploy the service
5. Run a rollback
6. Remove the service

This integration test is executed for every PR and branch we submit to the Serverless repository.

The code can be found [here](https://github.com/serverless/serverless/blob/master/tests/simple-suite/tests.js).

You can run it with `serverless run simple-integration-test`.

#### `Complex` integration tests

This branch of tests is a collection of more complicated integration tests. Most of them are `aws` specific and test the correctness of different `event` source usages.

Furthermore they include tests for e.g. custom plugins.

Those integration tests take a very long time (up to an hour) and are executed whenever a branch is merged into `master`. However they often fail because of some quirks which occur during deployments to AWS.

The code can be found [here](https://github.com/serverless/serverless/tree/master/tests/integration).

You can run the tests with `serverless run complex-integration-test`.

---

### The proposal

We should rework our integration tests so that they are reliable and cover all the important pieces Serverless provides as a tool.

Here are some thing we can do to improve the tests:

#### Remove integration test for AWS events

The test suite for AWS events takes forever since we deploy real services to AWS and verify that the AWS services are performing as expected.

Why we should remove the tests for `events`:

- They're currently AWS specific (and we now have support for other providers) 
- They take forever to run (since we deploy a real serverless service)
- We already validate that the correct CloudFormation template is compiled through unit tests
- We completely rely on AWS and one quirk makes the tests fail

If we still want to test the events on AWS we could write one super large serverless service which tests all the events and different setups rather than having one dedicated service for each event and event configuration.

#### Add integration tests for critical features Serverless provides

We should add integration tests for critical features.

Those include:

- Packaging / Zipping with all the different configs
- Service creation
- Plugin usage (with different lifecycle event usages)
- CLI tests
- Heavy Serverless variable usages
- ...

**We should constantly refactor and enhance our integration tests so that they're always reliable and up-to date ( 👈  kind of obvious, but IMO important to remember)**

---

Feel free to chime in and add other tests / test cases.

/cc @brianneisler @eahefnawy

**Comment by danielbh** [comment]
Hi Phillip,  the second link you put, under **Complex integration tests** links back to this page. Also where could I find the CloudFormation unit test you are talking about? Thanks.

**Comment by hassankhan** [comment]
I do think there's value in keeping the complex tests around, but perhaps we could move them to a separate repository altogether and run them from there? 

PS: Another thought - could the `serverless-examples` repo be used for integration testing? It probably does have a lot of stale services (and next to no tests), but they're mostly simple and they do cover quite a few different things.

**Comment by pmuens** [comment]
> Hi Phillip, the second link you put, under Complex integration tests links back to this page. Also where could I find the CloudFormation unit test you are talking about? Thanks.

Hey @danielbh thanks for pointing me in that direction. Somehow I forgot to fill out the Markdown for the link 🤦‍♂️ . Just updated the description. So the link should work.

The CloudFormation unit tests can be found in the different plugins [here](https://github.com/serverless/serverless/tree/master/lib/plugins/aws/package/compile/events). They're basically spread across all those `*.test.js` files.

---

> I do think there's value in keeping the complex tests around, but perhaps we could move them to a separate repository (serverless/aws-integration-tests?) altogether and run them from there?

That's an interesting idea! We had this plan in the past (and already got a repo in place). However we decided to put it into the core repo so that the tests are always shipped with the main codebase and we don't forget about them.

> PS: Another thought - could the serverless-examples repo be used for integration testing? It probably does have a lot of stale services (and next to no tests), but they're mostly simple and they do cover quite a few different things.

👍 We already discussed this. It's actually a pretty interesting idea. The only downside could e.g. be that we have to keep all the tests updated which could be a burden to maintain.

However one similar idea could be to fetch different services (e.g. looking for a `serverless.yml` file via the GitHub API) and then run different tests against those OpenSource projects. Could be done randomly. We could do this before releasing a new Serverless version to verify that our version will work on arbitrary "wild" projects (A prerequisite would be that the service itself works as expected).

**Comment by pmuens** [comment]
Closing since we did some changes to our integration tests and everything is fine for now. We'll re-visit this once problem pop up again.
