### ISSUE TITLE
Option to configure stage without using process.argv

### ISSUE THREAD

**Issue by martinheidegger** [serverless/serverless#3895]
# This is a Bug/Problem Report

## Description

It is currently not possible to specify the state when you instantiate `Serverless` without using command line arguments.

```javascript
var sls = new Serverless({ stage: 'develop' })
sls.init()
```

will [`loadAllPlugins`](https://github.com/serverless/serverless/blob/4514bb01c3758c7e729e6eeb64eb1d1551068e8c/lib/Serverless.js#L68) with the [`cli options`](https://github.com/serverless/serverless/blob/4514bb01c3758c7e729e6eeb64eb1d1551068e8c/lib/Serverless.js#L62) that uses [`process.argv`](https://github.com/serverless/serverless/blob/4514bb01c3758c7e729e6eeb64eb1d1551068e8c/lib/classes/CLI.js#L33) which will then be passed on to [`getStackInfo`](https://github.com/serverless/serverless/blob/4514bb01c3758c7e729e6eeb64eb1d1551068e8c/lib/plugins/aws/info/getStackInfo.js#L13).

Everything resulting to the  `AWSInfo.getStackInfo` having no stage unless its passed through the `process.argv`.

We can workaround this somehow like this:

```javascript
process.argv.push('--stage')
process.argv.push('develop')
var sls = new Serverless({})
sls.init()
```

but that is super-weird, right?

It seems like there shouldn't be a difference between options & cliOptions. But even if that is not the preferred way of action it could be simply fixed by changing:

[`this.cli = new CLI(this);`](https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L60)

into

`this.cli = new CLI(this, this.options.inputArray)`

effectively adding a `inputArray` optional property to ServerLess.

```javascript
var sls = new Serverless({
  inputArray: ['--stage', 'develop']
})
```

Similar or dependent issues:
* Fixing this might be fixing #2631 as well?  

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1

**Comment by pmuens** [comment]
Thanks for opening @martinheidegger 👍 

Right now Serverless has no first-class support for programmatic access (although you can do that the way you've described it). The feature is discussed in https://github.com/serverless/serverless/issues/1678 and is definitely on our roadmap!

**Comment by pmuens** [comment]
Closing since this is quite a stale issue and Serverless Framework v1 was not built to be used programatically first.

Additionally there are some existing solutions / workarounds to this kind of problem.
