### ISSUE TITLE
(Potentially) Feature Proposal about a Swagger Document Server?

### ISSUE THREAD

**Issue by syang** [serverless/serverless#3905]
I would like to have a documentation and mock-up server of my api, like the swagger document service provides for a server (in contract to serverless) setup environment, please click this http://petstore.swagger.io for what I meant here.

My customer(s) can use the above link to experience my API in an intuitive way. Does AWS API-Gateway provide such functionality?

I thought about it at high-level and I felt it's probably hard (after, we are server-less now, and where can Swagger document server exist?), but this is a great feature we want to have to communicate with our customers in a transparent way.

**Comment by pmuens** [comment]
Hey @syang thanks for opening this issue! 👍 

Have you seen the plugins https://github.com/temando/serverless-openapi-documentation and https://github.com/9cookies/serverless-aws-documentation?

Do they solve your specific problem here?

**Comment by syang** [comment]
@pmuens thanks for sharing the pointers. These projects seem to be able to generate static documents, but (maybe I missed anything) they do not seem be able to provide the live documentation serving service mechanism -- see what I mean below

http://petstore.swagger.io 
   1) it serves live documentation lookup
   2) it can serve live Rest calls with mock data response.

Neither of the above two can be achieved by the above projects, if I understand them correctly, is that right?

**Comment by pmuens** [comment]
> Neither of the above two can be achieved by the above projects, if I understand them correctly, is that right?

@syang 🤔 yes, that's right.

Right now there are no direct plans to integrate Swagger / OpenAPI with the Serverless Framework. However this could be a nice community project and work in conjunction with the Serverless Framework.

I'll close this issue for now. @syang thanks again for proposing this feature 👍. We'll revisit it once we have a plan if / how we tackle Swagger / OpenAPI support.
