### ISSUE TITLE
Quick-start documentation pages links broken in Github

### ISSUE THREAD

**Issue by Pixep** [serverless/serverless#3916]
# This is a Bug Report

## Description

From master, when browsing [documentation from Github](https://github.com/serverless/serverless/tree/master/docs), platform specific quick-start guides links are broken, showing a 404. For example AWS Quick-start is
```https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/quick-start```
While the file is named
```https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/quick-start.md```

So this is working fine from Serverless docs site https://serverless.com/framework/docs, but it would be great to avoid a 404 when consulting it from Github.

**Comment by pmuens** [comment]
Thanks for reporting @Pixep 👍 

Would you be open to fix this via a PR?

**Comment by Pixep** [comment]
Sure no problem.

However simply adding ".md" at the end of the link is causing a full page refresh (and flashes the home page too) when testing on https://serverless.com/framework/docs. Would that still be acceptable ?

**Comment by pmuens** [comment]
Thanks for getting back @Pixep :+1:

:thinking: so do you mean that this is only the case for this specific page or for the whole homepage? If it's the former I'd say that it's ok.

Maybe @DavidWells knows more why that's the case.

**Comment by Pixep** [comment]
Hello Philipp,
The problem shows up for this(ese) specific page(s) if I change the link from `quick-start` to `quick-start.md`.  It's a bit ugly :)

**Comment by pmuens** [comment]
> The problem shows up for this(ese) specific page(s) if I change the link from quick-start to quick-start.md. It's a bit ugly :)

@Pixep gotcha. Maybe it's best if we'll just leave it as it is for now.

We should troubleshoot why the page is reloaded. After fixing that we can add the file extension and fix this documentation issue.

cc @DavidWells

**Comment by tk120404** [comment]
@pmuens i hope this can be closed now
