### ISSUE TITLE
Package excludes all node modules if long=true in .npmrc

### ISSUE THREAD

**Issue by eoinsha** [serverless/serverless#3918]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  * Deploying multiple examples (including `aws-node-auth0-custom-authorizers-api` from `serverless/examples`) resulted in missing package errors on AWS (e.g., `Cannot find module 'jsonwebtoken')
  * Inspecting the ZIP archive produced by `sls package` showed that no production `node_modules` were present
* What did you expect should have happened?
  * Modules specified in `node_modules

* What was the config you used?
  * `serverless/examples.git` - `aws-node-auth0-custom-authorizers-api` - unmodified - 1e42394bc
  * `long=true` is present in `~/.npmrc`
  * Tested and reproduced this issue with NPM 4.6.1, 5.0.0 and 5.1.0

* What stacktrace or error message from your provider did you see?
```
{
  "errorMessage": "Cannot find module 'babel-runtime/regenerator'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/list.js:76:18)",
    "__webpack_require__ (/var/task/list.js:20:30)",
    "Object.<anonymous> (/var/task/list.js:172:20)",
    "__webpack_require__ (/var/task/list.js:20:30)",
    "/var/task/list.js:63:18",
    "Object.<anonymous> (/var/task/list.js:66:10)"
  ]
}
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
  * Serverless version `1.17.0`
* ***Operating System***:
  * macOS 10.12.5
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by eoinsha** [comment]
## Analysis
- `long=true` in `.npmrc` results in a different output for `npm ls --prod=true --parseable=true --silent` as invoked by `lib/plugins/package/lib/zipService.js`
- Removing this line from `.npmrc` results in the correct package being produce with `dependencies` packaged (workaround)

**Comment by sidthe** [comment]
@eoinsha could you please explain how you managed to have the workaround working?

I have the long true set by default in cli configs, and I am not sure there is a way to remove that
```
npm config ls -l
; cli configs
long = true
```

**Comment by eoinsha** [comment]
@sidthe You can remove the `long=true` setting by either manually editing npmrc or by executing 
```
npm config set long false
```

**Comment by sidthe** [comment]
thanks @eoinsha 
I did the `npm config set long false` before, and `npm config get long` returns `false` but doing `serverless deploy` with that still does not solve the `"Cannot find module 'babel-runtime/regenerator'"` issue :( any ideas?

running the `npm config ls -l` shows that apparently the `false` value is overridden however

```
npm config ls -l
; cli configs
long = true
user-agent = "npm/3.10.8 node/v6.9.1 linux x64"

; userconfig /home/rarcea/.npmrc
; long = false (overridden)

; globalconfig /etc/nodejs/npmrc
; long = false (overridden)
```

**Comment by pmuens** [comment]
First of all: Thanks @eoinsha for opening this issue and providing a fix (sorry that you had to update it frequently 😬).

@sidthe FYI: we're currently facing a bug with the dev dependency exclusion which might be related to the issue you're facing here: https://github.com/serverless/serverless/issues/3972

There's already a PR in the pipeline which fixes the bug: https://github.com/serverless/serverless/pull/3975. It will be merged and patch-released soon.

After that we should definitely review the PR with the fix for this issue 👍
