### ISSUE TITLE
Tests resolve with unhandled rejection errors

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#3920]
# This is a Bug Report

## Description

While tests pass, they resolve with unhandled rejections, which indicates something went wrong

![screen shot 2017-07-10 at 11 17 43](https://user-images.githubusercontent.com/122434/28011058-55fdd0e0-6561-11e7-88d0-4668ee868fa5.png)

## Additional Data

* Serverless @ master (https://github.com/serverless/serverless/commit/f0b1474f1e49d69c39e27e3c8def929569e20bed)
* macOS v10.12.5
* Node.js v6.10.3 & v8.1.3

**Comment by horike37** [comment]
The same happens to me. Umm..
