### ISSUE TITLE
Unable to run the "serverless depoly" cmd in the npm for windows 10

### ISSUE THREAD

**Issue by dineshsaib** [serverless/serverless#3927]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dineshsaib** [comment]
please help us on this to rectify

**Comment by pmuens** [comment]
Hey @dineshsaib thanks for opening!

Could you please provide more information about your set?

Which version of Serverless are you using? How does your `serverless.yml` file look like?

**Comment by pmuens** [comment]
Closing this one for now since it's been a while and we've pushed a couple of fixes in the meantime.

Feel free to re-open / comment if this problem is still around...
