### ISSUE TITLE
unable to make parameterizable paths works

### ISSUE THREAD

**Issue by dege88** [serverless/serverless#393]
After the migration from jaws to serverless I wasn't able to make serverless work with parameterizable paths ({var_name} in urls)

If in the path of one endpoint in s-function.json there's a parametrizable path I always get as a result:

```json
{
  "message": "1 validation error detected: Value 'arn:aws:lambda:eu-west-1:<xxxxxxxxxxxx>:function:<lambda name>:' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?"
}
```

**Comment by Nopik** [comment]
This seems to be `sls dash` issue. Try deploying all your functions by `sls function deploy`. It helped me today.

**Comment by dege88** [comment]
It happens also when deploying the endpoints with `sls endpoint deploy` but once the name of the lambda function got corrected by hand everything works fine again.
Also as pointed by @Nopik using `sls function deploy` after this correction let you deploy faster than using `sls dash deploy` and correcting manually every time.

**Comment by ac360** [comment]
@dege88 Is this still an issue for you?  Are you still having to correct the function names?  If so, could you give me any more details so we can jump in and try to fix this.  Sorry about the inconvenience :\

**Comment by dege88** [comment]
@ac360 thanks now it's fixed!
