### ISSUE TITLE
Install and configure 3rd party plugins automatically (based on serverless.yml)

### ISSUE THREAD

**Issue by ansarada-dantan** [serverless/serverless#3930]
# This is a Bug Report
When updating the plugins section of serverless.yml dynamically, it doesn't actually install and configure the required plugins.

Here's a snippet of serverless.yml config:
`
plugins: ${file(utils/combineServerlessConfig.js):plugins}
`

utils/combineServerlessConfig.js:
`
module.exports.plugins = () => {
  return [ 'serverless-plugin-aws-alerts', 'serverless-plugin-warmup' ]
}
`

## Description

* What went wrong?

The .serverless/serverless-state.json pulls in the required plugins, but the plugins doesn't seem to load.

* What did you expect should have happened?

I would have expected serverless install and deploy serverless-plugin-aws-alerts and serverless-plugin-warmup but it does not.

* What was the config you used?

serverless.yml
`
service: aws-python3-example

plugins: ${file(utils/combineServerlessConfig.js):plugins}

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hello
`

utils/combineServerlessConfig.js:
`module.exports.plugins = () => {
  return [ 'serverless-plugin-aws-alerts', 'serverless-plugin-warmup' ]
}
`

* What stacktrace or error message from your provider did you see?
Does not output any errors; but it doesn't deploy / configure any of the required packages.

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: macOS Sierra 10.12.5
* ***Stack Trace***: N/A
* ***Provider Error messages***:  N/A

**Comment by pmuens** [comment]
Hey @ansarada-dantan thanks for opening 👍

I'd propose to only add the plugin at the end of to the `plugins` array in the `serverless.yml` file.
But we should print an info that it was added automatically at the end of the `plugins` array since users might want to re-arrange it (because plugins are loaded in the order they are defined).

Configuring the plugins is smth. we cannot provide since it differs from plugin to plugin.

**Comment by J-Rojas** [comment]
This would be a nice feature to have for CI/CD systems using the serverless tool for integration testing and deployment. I don't want to have to check in plugin modules into my project source tree so automatic installation when a plugin is missing would be a nice feature.

**Comment by kamzil** [comment]
I'm also interested in finding a solution to this. I am currently loading stuff to my serverless.yml dynamically based on logic in a separate config JS file that is loaded under custom section and am forced now to include all the potentially needed plugins into the base file. It would be great to just to be able to do

plugins: ${self:custom.config.plugins}

**Comment by rickalm** [comment]
What is the status of this request ?? I don't understand the purpose of the plugins being listed in the serverless.yaml file if they are not used to satisfy environment setup. Having to custom code a buildspec file to perform a series of "serverless plugin install XX" for each plugin is counter-initiative and actually violates the DRY principal by mandating configuration information exist in two different places

**Comment by pmuens** [comment]
Closing since the `plugin` command can auto-install plugins for you. Other than that it's required to install and configure plugins on your own since there are many different ways to use and confugre plugins.

**Comment by lsorber** [comment]
> Closing since the plugin command can auto-install plugins for you. Other than that it's required to install and configure plugins on your own since there are many different ways to use and confugre plugins.

@pmuens How do you auto-install plugins with the `plugin` command? If I run `sls plugin install` it tells me I need to provide a plugin name to install:
```
This command requires the --name option / -n shortcut. Usage: The plugin name
```
The help information doesn't mention any other options for auto-installing the plugins specified in `serverless.yml`.

**Comment by adilnaimi** [comment]
>Closing since the plugin command can auto-install plugins for you. Other than that it's required to install and configure plugins on your own since there are many different ways to use and confugre plugins.

I confirm, same as @lsorber mentioned, the plugin command doesn't auto-install plugins specified in serverless.yml.

**Comment by defaultbr** [comment]
Is there any solution for this? Someone can reopoen, i have to do a workaround or add some plugins to dependencies part of package.json, since there is no way to "get serverless.yml plugin and than install"

**Comment by defaultbr** [comment]
@pmuens can help us? The plugin command doesnt install

**Comment by ChrisLanks** [comment]
Same issue. We end up parsing the yaml in order to install the plugins 1 by 1, or npm installing. Can we run 1 command to install all plugins. It would make CI/CD much simpler.  @pmuens or whoever has a better solution.

**Comment by koliyo** [comment]
> Closing since the `plugin` command can auto-install plugins for you. Other than that it's required to install and configure plugins on your own since there are many different ways to use and confugre plugins.

What does auto-install plugins mean? I still have to manually install all the plugins listed in the serverless.yml? Why was this issue closed?
