### ISSUE TITLE
SyntaxError in postinstall script with version 1.17.0 on Mac OSX 10.12.5

### ISSUE THREAD

**Issue by jeff-savin** [serverless/serverless#3936]
# This is a (Bug Report)

## Description

* What went wrong?
Trying to install serverless on my mac with `npm install -g serverless` and get following error with the postinstall.js script:

```
> serverless@1.17.0 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

/usr/local/lib/node_modules/serverless/scripts/postinstall.js:3
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
* What did you expect should have happened?
Complete install without issues

* What was the config you used?

* What stacktrace or error message from your provider did you see?
Supplied above.

Similar or dependent issues:

## Additional Data
* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: MAC OSX 10.12.5
* ***Stack Trace***: Shown above
* ***Provider Error messages***: Shown above.

**Comment by jeff-savin** [comment]
Upgraded npm from version `2.10.1` to `3.10.10` and retried serverless install with success.

**Comment by pmuens** [comment]
Thanks for opening and sharing the solution @jeff-savin 👍 

Glad to hear that you were able to resolve it in the meantime!
