### ISSUE TITLE
Documentation table wider than screen width

### ISSUE THREAD

**Issue by ezramorris** [serverless/serverless#3937]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference
Table is too wide for most screen sizes, and is not scrollable.
![serverless table error](https://user-images.githubusercontent.com/17853493/28206372-81ed1b88-687d-11e7-8954-745020fd975f.PNG)

* What did you expect should have happened?
Table to fit in screen width (preferable) or be scrollable.

* What was the config you used?
Google Chrome; also seen in Edge.

* What stacktrace or error message from your provider did you see?
N/A

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
N/A
* If there is additional config how would it look
N/A

Similar or dependent issues:
* N/A

## Additional Data

* ***Serverless Framework Version you're using***:
N/A
* ***Operating System***:
Windows 10
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by usmandap** [comment]
May be there is some css issue. Can I try to fix this issue?

**Comment by pmuens** [comment]
Thanks for opening this issue @ezramorris :+1:

Could you re-open this issue over at https://github.com/serverless/site/issues since this is the core Framework codebase and website for the documentation can be found there.

Thanks in advance!

/cc @DavidWells
