### ISSUE TITLE
Add commandline flag for specifying state file

### ISSUE THREAD

**Issue by simonhjoerg** [serverless/serverless#3945]
# This is a Feature Proposal
## Description
Add a command line option for specifying a specific state file, such as --state-file serverless-dev.yml
This is kinda stolen from hashicorps terraform, which also generates a state file.
In the event where i have multiple people working on the same environment, and want to enable them to deploy into the same cloudformation stack (without a build server) I git commit my state file.

It also helps in the event my pc is stolen or br0ken or when i change between my desktop or laptop, i can git pull and continue to do deployments on the same stack.
This is all fine and good until i bring up a second stack.
For example the project i have at the moment has a dev, staging and prod stack.
Lets say ive been working on dev stack, i reach a point where i want to deploy it into staging.
If i change my stage in serverless.yml, it overwrites my .serverless/serverless-state.json 
When it builds a new stack.

At this point if i want to go back to my dev stack i have to completely rebuild, eg destroy the cloudformation stack, or before hand when deploying the new stack.
I have alot of "glue" around my serverless stacks, such as extra cloudfront deployments with custom domains, custom domains associated with my API gateway and so on and not all are contained within my serverless.yml.

Due to this i dont really want to fully recreate my stacks each time i deploy.
This could be solved by allowing me to choose which state file to use, for example:

sls deploy --stage prod --state-file serverless-prod.json

I could then switch between environments easily, allowing me to deploy into specific cloudformation stacks at will.

**Comment by HyperBrain** [comment]
The state file is purely internal and temporary, to transfer the state from the package phase to the deploy phase. It is not meant to keep the current dev state or any other state. It must not be changed manually.
It is an integral part of the artifacts created by the package phase (so to say the internal restore manual). This is also why you only can specify an artifact (package) directory and not a state file - the files belong together.

I think your feature request should be handled with a completely different approach (maybe exporting an explicit persistent state that can be resumed). As the requested feature seems to be granular and self-contained, it might be even better be implemented as a plugin.

**Comment by jmbcpi** [comment]
I'd like to be able to `serverless deploy list` and `serverless remove` even if I no longer have my original working copy. Maybe deployments could be tracked more globally on my dev system, for example, so that I can list and remove any or all of my deployments across multiple services/projects. Or maybe each project has a file that can be included in the repo, specifying only enough info to support those types of tasks. 

In any case, it's a shame that deleting a working copy deletes serverless state as well, leaving a developer to manually go and remove everything from the stack in the cloud. A way to protect against that would be welcome.

**Comment by pmuens** [comment]
Closing since the state file is something the user shouldn't care about.

A way to delete "everything at once" even if the state file is lost is to go to the CloudFormation console and start a removal process.
