### ISSUE TITLE
SLS Reports Stack Removal Finished after AWS CF UPDATE_ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by JP-Dhabolt** [serverless/serverless#3948]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
Serverless reported `Serverless: Stack removal finished...` when executing `sls remove -s dev`, despite CloudFormation Stack reporting a `UPDATE_ROLLBACK_COMPLETE` due to an Export in use.
This dependency was left intentionally to validate Serverless behavior with dependent CF Stacks.

* What did you expect should have happened?
Serverless should have reported an error with deleting the Stack.

* What was the config you used?
Basic Hello World AWS Node.js template with an Export of the HelloLambdaFunction ARN added.
Dependent service was also the same basic template with an Import (to an ENV variable, just to establish the dependency between Stacks).

* What stacktrace or error message from your provider did you see?
None

Similar or dependent issues:
* None that I could find

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: win32 (Windows 7)
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by pmuens** [comment]
Thanks for reporting @JP-Dhabolt 👍 

This was recently fixed with https://github.com/serverless/serverless/pull/3935 so I'm closing this issue.

Let us know if this is still an issue (this fix will be shipped with the upcoming Serverless version v1.18).
