### ISSUE TITLE
CLI won't display help text when serverless.yml declares an unknown plugin

### ISSUE THREAD

**Issue by plfx** [serverless/serverless#3956]
# This is a Bug Report

## Description

- Alter serverless.yml to have the following entry
```
plugins:
  - garbage
```
- Run `sls --help`
- You will receive the error `Cannot find module 'garbage'`

## Additional Data

Framework version 1.17

**Comment by horike37** [comment]
I agree with @plfx. Curently, the message is not kind for users.

It can be implemented by adding error handling here
https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L63-L69

**Comment by RafalWilinski** [comment]
I've submitted a pull request resolving that issue, however I'm not sure whether it's good approach. In my opinion, adding a non-existing plugin and providing a wrong confiuration/serverless.yml should render tool unusable.

**Comment by pmuens** [comment]
Thanks for opening @plfx! That's a really good idea 👍

Thanks for submitting the fix @RafalWilinski 🎉 💯

**Comment by plfx** [comment]
@RafalWilinski  One of the things the help page displays is the list of installed plugins. Displaying the help page should be independent of your serverless.yml's contents. I think your fix is good.
