### ISSUE TITLE
"self signed certificate in certificate chain" - how to add self-signed cert to trusted store

### ISSUE THREAD

**Issue by beb-bang** [serverless/serverless#3958]
Hi - Similar to #3230, I've just run into the same issue today. I'm using the latest version of Serverless, 1.17.0, and I know exactly what the issue is just not how to correct it.

I've recently begun testing deep packet inspection in my network. The firewall is decrypting, inspecting, and re-encrypting my SSL traffic for malware and such. There is a firewall generated, self-signed certificate deployed to the local CA trust store, and for other applications that don't use the OS's trust store I've had to add the self-signed cert somewhere/somehow.

For example, git requires:
`git config --global http.sslCAInfo <path to cert.pem>`

npm has a similar functionality for adding a reference to the cert or strict checking can be disabled with:
`npm config set strict-ssl false`

So... question is: how might I add or reference the self-signed cert in serverless?

```
Serverless: Packaging service...
  Serverless Error ---------------------------------------
  ServerlessError: self signed certificate in certificate chain
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.10.3
     Serverless Version:     1.17.0

```
In the serverless documentation for OpenWhisk, there is a reference to a property of the provider called "ignore_certs" that can be set to true. I'm using AWS, but tried this anyway and it did not change the result.
![image](https://user-images.githubusercontent.com/19676403/28395584-f6d59256-6ca9-11e7-913a-3f63c65d5df6.png)
https://serverless.com/framework/docs/providers/openwhisk/guide/credentials/#register-with-openwhisk-platform-self-hosted

Any suggestions would be greatly appreciated.

Cheers!
Bryan

**Comment by geofflancaster** [comment]
Seems like this is needed by many people. Any ideas how/when this can be achieved?

**Comment by pmuens** [comment]
> Seems like this is needed by many people. Any ideas how/when this can be achieved?

Thanks for commenting @geofflancaster 👍

The next step here would be a quick writeup / proposal on how we could implement this for Serverless. This way we could discuss it and settle on an implementation plan!

**Comment by geofflancaster** [comment]
I just made the code change to follow the path of the .npmrc file and set an environment variable that provides either an array or string containing a valid CA's cert.

PR incoming today.

**Comment by pmuens** [comment]
> I just made the code change to follow the path of the .npmrc file and set an environment variable that provides either an array or string containing a valid CA's cert.

> PR incoming today.

That super nice @geofflancaster 👍 💯! Thanks for PRing the change!

**Comment by yowainwright** [comment]
Where is PR at in regards to getting merged? 

...Is this no longer an issue for those that know what's up (which I clearly don't 😵)?

----

## My steps to producing this issue

Here's my best attempt at documenting how I got to the problem listed above:
1. Install Serverless
   ```sh
    npm i -g serverless
   ```
2. Try to follow the [hello world example](https://serverless.com/)
    ```sh
    serverless login
    # (still going well)
    serverless create -t hello-world
    # (really fired up 🔥)
    ```
3. Set up my creds
    ```sh
    serverless config credentials -p aws -k <numbersnstuff> -s <morenumbersnstuff> -o
    # adding that -o, I'm still good
4. Deploy and get blocked 😔
    ```sh
    serverless deploy
    ```
    Here's what is logged
    ```sh
    Serverless: Excluding development dependencies...

    Serverless Error ---------------------------------------

    self signed certificate in certificate chain

    Get Support --------------------------------------------
      Docs:          docs.serverless.com
      Bugs:          github.com/serverless/serverless/issues
      Forums:        forum.serverless.com
      Chat:          gitter.im/serverless/serverless

    Your Environment Information -----------------------------
      OS:                     darwin
      Node Version:           6.10.3
      Serverless Version:     1.24.0
    ```
----

Here's what I think is valid in my AWS Setup
-  My user setup with group
    ![iam_management_console](https://user-images.githubusercontent.com/1074042/32413350-f9598db6-c1cc-11e7-80fc-90874e67658b.jpg)
-  My priviledges, id, & keys
    ![iam_management_console](https://user-images.githubusercontent.com/1074042/32413366-0328fe06-c1c5-11e7-814a-4d9528ceefcf.jpg)
   ![iam_management_console](https://user-images.githubusercontent.com/1074042/32413358-d203301c-c1c4-11e7-8f52-69c5506fb3cf.jpg)

----

Please halp! Or, let me know how I can help. 🙏

**Comment by yowainwright** [comment]
**Update**

I ran:
```sh
npm i -g serverless@latest
``` 
Then, re-ran:
```sh
serverless deploy
```
I was able to deploy.

**Comment by geofflancaster** [comment]
This has nothing to do with AWS and everything to do with the network that you're running on when you try to deploy.

Just for kicks, @yowainwright when it did not deploy successfully were you on a different network (potentially a corporate network?) versus when it did deploy successfully?

**Comment by yowainwright** [comment]
@geofflancaster thanks for your correction and insights. 🙏

---

-  When I was not able to deploy successfully, I was on my work computer at home. 
-  When I was able to deploy successfully, I was on my work computer at work.
   -  It failed initially, then when I ran `npm i -g serverless@latest`, then `serverless deploy` it worked.

**Comment by bence-takacs** [comment]
There is an existing workaround: 
`export NODE_TLS_REJECT_UNAUTHORIZED=0 sls deploy`
But the issue still persists in serverless 1.26.1

**Comment by babureddy** [comment]
export NODE_TLS_REJECT_UNAUTHORIZED=0
serverless create --template aws-nodejs --path test
cd test
serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occurred (self signed certificate in certificate chain), sleeping for 5 seconds.  
  Serverless Error ---------------------------------------
 
  ServerlessError: self signed certificate in certificate chain
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.8.0
     Serverless Version:     1.30.1

**Comment by snnehal** [comment]
Hi,
I am still facing this issue in 2019. What is the solution ?
I am behind a corporate firewall and on windows.
I have tried -
1. Installing the aws cli, configuring it and then trying serverless deploy
2. SET NODE_TLS_REJECT_UNAUTHORIZED=0, upgraded npm.
3.secureendpoint: false in serverless.yml

none of these have worked. Please help.

serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occurred (self signed certificate in certificate chain), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (self signed certificate in certificate chain), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (self signed certificate in certificate chain), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (self signed certificate in certificate chain), sleeping for 5 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  ServerlessError: self signed certificate in certificate chain

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              8.11.2
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.8
     Platform SDK Version:      2.1.0

**Comment by corydorning** [comment]
same issue as @snnehal

**Comment by abdulhub** [comment]
I got the same issue.  but it worked after upgrading NodeJS to 10.x and SET NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by marcelloromani** [comment]
This worked for me on MacOS:
```bash
export NODE_TLS_REJECT_UNAUTHORIZED=0
serverless
```

**Comment by usualiron6413** [comment]
Hi there, I'm getting a similar issue when trying to run serverless create:

`serverless create --template aws-nodejs-typescript --path aws-serverless-typescript-api`

Result:

```
(node:6029) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Environment: darwin, node 14.20.1, framework 3.24.1, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Could not download template. Ensure that you are using the latest version of Serverless Framework: self signed certificate in certificate chain
```

I've set `NODE_TLS_REJECT_UNAUTHORIZED=0` and updated serverless to latest. I'm probably also behind some company firewall or Netskope client. Trying to explain my problem to my IT department but they don't really understand.

Any ideas?
