### ISSUE TITLE
Question: back/modules folder structure

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#396]
Wondering what the reason is for this nesting? Seems like the `back` directory could be scraped.

**Comment by Nopik** [comment]
I guess that the original idea was also to have `front/` folder for front-end code. I dont think it will work (I keep frontend code in different location, for example), but, who knows.

**Comment by visualasparagus** [comment]
ok. i suppose that would make sense. just seems like an unneeded complexity to me.

i've also noticed something else that could be an issue with the function directory structure. as it is now we cannot create functions with the names 'lib', 'package' or 'node_modules'. Perhaps it's an idea to place all module functions in a 'functions' directory at the same level as 'lib', etc

**Comment by eahefnawy** [comment]
adding to @Nopik awesome answer, I can't think of a scenario where you'd need to create a function named after any of these three folders. These are just there for their own purposes to make the code more reusable.

**Comment by Nopik** [comment]
Also, please note, that folder where ther function is (or module name) is pretty irrelevant. You can create function in `foo` folder but deploy endpoint under different path. Also, I think that the function name (as visible in AWS console) is taken from json file.

**Comment by eahefnawy** [comment]
:+1:

**Comment by ac360** [comment]
Thanks for the input.  We have lots of plans to make this Framework versatile, and having this extra level is important to that versatility.  In Serverless `v0.1.0`, projects will be shareable, as well as the modules.  Who knows how the community will hack/evolve Serverless Projects.  But we want to encourage them to do so.  Hopefully, the existence of the `back` folder will spark some creativity...
