### ISSUE TITLE
Travis should publish only when integration tests pass

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#3966]
Right now Travis tries to publish a new version of the framework on every build job. Travis should only publish new versions of the framework when all integration tests (jobs) pass instead.

**Comment by RafalWilinski** [comment]
I've researched this issue a bit and it doesn't seem as easy as I thought. 

My first idea was to add `condition: $TRAVIS_TEST_RESULT = 0` to `deploy.on` object in `.travis.yml`, however, deploy operation is executed on every worker from matrix and it checks only the result from local env. There's no official way to invoke just one deployment procedure after executing tests on all runtimes from `matrix`. It's well known issue: https://github.com/travis-ci/travis-ci/issues/929

However, there are few alternative approaches:
1. [Use build stages](https://docs.travis-ci.com/user/build-stages) which are currently in beta. They allow to define multiple test scripts (and runtimes/versions) and one deployment procedure.
2. Use custom community solution like https://github.com/dmakhno/travis_after_all

**Comment by pmuens** [comment]
Closing since we've made this fix in the past.
