### ISSUE TITLE
Dependencies aren't included when they are a dependency of devDependencies

### ISSUE THREAD

**Issue by maximede** [serverless/serverless#3972]
# This is a Bug Report 

## Description
Serverless package doesn't correctly add node_modules when a node module is also a dependency of a devDependency

I have a package.json that contains this : 

```
{
  "name": "myapp",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "bluebird": "^3.5.0",
    "moment": "^2.18.1"
  },
  "devDependencies": {
    "aws-sdk": "*",
    "serverless": "^1.18.0"
  }
}

```

When I run `serverless package` then extract the resulting zip file, the `node_modules` folder only contains a `.bin` folder.

I think that this is due to the way the `excludeDevDependencies` functionality works.

I'm wondering if the issue might be coming from the fact that, as the `serverless` module relies on `moment` and `bluedbird` they are in the list of dependencies when running `npm ls --dev=true` but not added back when running `npm ls --prod=true`.

## Similar or dependent issues:
This is probably related to  #3889

## Additional Data

* Serverless 1.18.0
* MacOS Sierra
* package is created correctly ( but with the devDependencies) if I use `excludeDevDependencies: false`

**Comment by pmuens** [comment]
Thanks for opening @maximede 👍

We'll look into this ASAP.

**Comment by kennu** [comment]
I noticed the same problem with `node-fetch` as a dependency, and worked around it by adding:

    package:
      include:
        - node_modules/encoding/**
        - node_modules/iconv-lite/**
        - node_modules/is-stream/**
        - node_modules/node-fetch/**

In this case `node-fetch` was also inherited through some devDependency. It seemed to be the different version, if that affects anything.

Btw aside from this bug, the feature to automatically exclude devDependencies is really awesome.

**Comment by davidgovea** [comment]
Added a [pull request](https://github.com/serverless/serverless/pull/3975) #3975 for this. In short, a second temporary file is used for the `--prod=true` dependencies, and then lodash's `.difference()` is used to make sure we preserve any explicitly-needed dependencies:  

```js
const dependenciesToExclude = _.difference(devDependencies, prodDependencies)
```

**Comment by pmuens** [comment]
Thanks for the workaround @kennu 👍

Thanks @davidgovea for providing a fix! 🎉 That sounds promising! We'll review it ASAP!

**Comment by pmuens** [comment]
For everyone who is reading this right now / is blocke day this bug.

There's a config available to opt-out of dev dependency exclusion you can use in the meantime:

```yml
package:
  excludeDevDependencies: false
```

https://serverless.com/framework/docs/providers/aws/guide/packaging/#development-dependencies

**Comment by pmuens** [comment]
Everyone who's reading this: It would be super nice if you could give #3975 a spin.

Just tested it and it works for my config. However more proof that the fix applies in general to different configs would be really beneficial 💪

**Comment by kennu** [comment]
:+1: #3975 seems to be working for me. I had the problem with node-fetch.

I used this to test it (hadn't tried installing PRs with yarn previously):

    yarn add serverless/serverless#3975/head

**Comment by pmuens** [comment]
> 👍 #3975 seems to be working for me. I had the problem with node-fetch.

Nice! Thank you very much for testing it @kennu 👍
