### ISSUE TITLE
CLI option aws-profile overriden by env var AWS_PROFILE

### ISSUE THREAD

**Issue by mpuittinen** [serverless/serverless#3979]
# This is a Bug Report

## Description

If both the aws-profile CLI option and AWS_PROFILE env vars are defined, the env vars are used. CLI options should always have highest priority.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: MacOS X
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by mpuittinen** [comment]
@pmuens I'm fixing this, PR coming right up.

**Comment by pmuens** [comment]
> @pmuens I'm fixing this, PR coming right up.

Great! Thanks for working on this @mpuittinen 👍

**Comment by mpuittinen** [comment]
Fixed in https://github.com/serverless/serverless/pull/3980

**Comment by pmuens** [comment]
> Fixed in #3980

Thanks @mpuittinen 👍 🎉
