### ISSUE TITLE
Ignore check for unchanged files after failed deployment

### ISSUE THREAD

**Issue by sbstjn** [serverless/serverless#3983]
After a failed deployment due to remote (CloudFormation) error I have to use `sls deploy --force` to trigger a new deployment with the same configuration because serverless skips the deployment with the `Service files not changed. Skipping deployment...` notice per default.

### Expected behaviour

If a deployment failed due to a remote (CloudFormation) error, a new `sls deploy` should trigger a deployment even if the service files have not changed. The check for unchanged configuration should only matter after a successful deployment.

**Comment by horike37** [comment]
@sbstjn 
Good point. I agree with you.

**Comment by tom10271** [comment]
This is kind of silly... I need to change my project name to another one if it fails in order to bypass this wrong checking.

**Comment by sbstjn** [comment]
Have you tried to use `sls deploy --force` @tom10271 ?

**Comment by maplion** [comment]
+1

**Comment by derwaldgeist** [comment]
Funny thing: The --force flag ignores forced webpack excludes and thus fails due to missing packages.

**Comment by mrcoles** [comment]
I’ve encountered this issue numerous times now when a previous deploy failed because of a misconfiguration. It’s really confusing when deploys seem to be successful, but they’re really quick and then nestled in between a bunch of other output text I see:

```bash
Serverless: Service files not changed. Skipping deployment...
```

**Comment by emmanuelnk** [comment]
+1 Bump on this issue. Serverless should be able to clean up failed deployments. Using `--force` doesn't seem like a very stable solution.

**Comment by prr19776** [comment]
the solution without --force would be a great addition

**Comment by prr19776** [comment]
I would also say given a lot of releases looking like a major upgrade to me, is there any plan to bump up SLS to 2.x? @pmuens

**Comment by blakedietz** [comment]
+1 bump on this

**Comment by timtubescience** [comment]
Ran into this while configuring circleci for Serverless deployments, one can always expect lots of build fails going from zero to continuous.

+1 please

**Comment by cmsd2** [comment]
> Question, what is the use case for running w/o --force? To ask it another way, why would we ever run sls deploy and not want it to actually deploy?

deploying to lambda@edge counts as a cloudfront distribution change which takes ages.
if we can avoid doing that unnecessarily, e.g. just deploy the lambdas that have actually changed that'd be a big help.

**Comment by c0d3d** [comment]
#6520 Covers this. It looks at last modified dates to determine if changes to the s3 objects aren't represented in the lambda.
