### ISSUE TITLE
Tracking functionality in invoke should be a separate lifecycle event

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#3985]
# This is a Feature Proposal

## Description

Currently the command tracking hooks [after the invoke lifecycle event variants - L77-L78](https://github.com/serverless/serverless/blob/master/lib/plugins/invoke/invoke.js#L77-L78). Imo this is bad design, as the `invoke plugin` defines the invoke command and the tracking is definitively a separate step that belongs to the invoke lifecycle. So it should be a separate event, and not a post-event trigger.

I suppose to add a separate `tracking` event into the lifecycles and define them properly.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0

**Comment by pmuens** [comment]
Thanks for opening @HyperBrain 👍

AFAIK that was a "quick hack". But yes, you're right. We could /should get into more detail here.

/cc @DavidWells

**Comment by pmuens** [comment]
Closing since this issue is quite stale and we've made some fixes in the past working on this.
