### ISSUE TITLE
Permission error when using serverless deploy

### ISSUE THREAD

**Issue by priyankasudhindra** [serverless/serverless#3993]
**sls deploy --verbose**

  Error --------------------------------------------------

     EACCES: permission denied, unlink '/Users/gadgetsoftware/.serverless/cloudformation-template-create-stack.json'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.6.1

**Comment by akirashimosoeda** [comment]
This might be a npm permission issue rather than Serverless (I assume from the message received from the error log shown). If you are using npm with sudo. Permission is the issue.

I recommend using nvm or some sort or version manager to ease your pain.

**Comment by priyankasudhindra** [comment]
I fixed the permission issue and tried again.

sudo sls deploy --verbose
Serverless: Packaging service...

<--- Last few GCs --->

  164971 ms: Scavenge 1397.7 (1454.0) -> 1397.7 (1454.0) MB, 0.3 / 0 ms (+ 2.4 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  166190 ms: Mark-sweep 1397.7 (1454.0) -> 1397.6 (1454.0) MB, 1219.4 / 0 ms (+ 3.2 ms in 2 steps since start of marking, biggest step 2.4 ms) [last resort gc].
  167412 ms: Mark-sweep 1397.6 (1454.0) -> 1397.6 (1454.0) MB, 1222.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2a62777b4629 <JS Object>
    1: _readdirEntries [/Users/gadgetsoftware/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/glob/sync.js:~295] [pc=0x10bddfa0f50] (this=0x33d2f8513911 <a GlobSync with map 0x2b4ff121f489>,abs=0x64b96743659 <String[217]: /Users/gadgetsoftware/Library/Containers/com.apple.PhotoIngestService/Data/Library/Mail/V3/72267B97-AB87-44DB-81DC-87CD0839017E/[Gmail].mbox/All Mail.mbox/0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by akirashimosoeda** [comment]
Try using this `sls deploy --verbose > your_log_name.log`. Why are you using `sudo` if you are using nvm? Maybe the log might reveal something useful.

**Comment by priyankasudhindra** [comment]
Not using sudo gives me the initial error even after fixing the permission issue.

**Comment by akirashimosoeda** [comment]
> Not using sudo gives me the initial error even after fixing the permission issue.

Maybe your `$HOME/.nvm` folder's owner requires root permission. In normal situations that folder's owner should be $USER.

**Comment by pmuens** [comment]
Thanks for opening @priyankasudhindra and thanks for jumping in @akirashimosoeda 👍

🤔 I agree. this looks like a permission error.

The second error you posted looks different though. Could you please provide more information about your service? How does your `serverless.yml` file look like?

Thanks in advance 👍

**Comment by priyankasudhindra** [comment]
My serverless.yml looks like this.

cat serverless.yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: forex

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
gadgetsoftware@Gadgets-MacBook-Pro:~$

**Comment by priyankasudhindra** [comment]
cat serverless.yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: forex

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
gadgetsoftware@Gadgets-MacBook-Pro:~$

**Comment by priyankasudhindra** [comment]
cat serverless.yml

service: forex


provider:
  name: aws
  runtime: nodejs4.3


functions:
  hello:
    handler: handler.hello

**Comment by pmuens** [comment]
@priyankasudhindra thanks for posting the `serverless.yml` 👍.

Everything looks good so far so I'd say that it's an issue with your Node setup and not an issue with Serverless in general.

**Comment by priyankasudhindra** [comment]
**sls deploy -v**

Serverless: Packaging service...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: Unknown system error -102: Unknown system error -102, open '/Users/priyankasudhindra/Library/Application Support/Google/Chrome/App Shim Socket'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/priyankasudhindra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:58:25
    at Array.forEach (native)
    at WriteStream.<anonymous> (/Users/priyankasudhindra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:49:13)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at WriteStream.<anonymous> (fs.js:1846:10)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by priyankasudhindra** [comment]
I still am not able to deploy my service. 
It would be great if I can get some help here.

Thanks in advance.

**Comment by nipuntanay** [comment]
Try deleting the '.serverless' directory and deploying again. For me, It resolved the issue mentioned by you. Although I got a different issue 'Access Denied' but I think it is something to do with my AWS credentials.

**Comment by dfloresgonz** [comment]
No success, I'm trying to deploy with non-admin credentials

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue. Additionally there are some helpful comments in this issue thread.

Serverless needs admin access on AWS to manage resources on your behalf.

Feel free to re-open if this is still a problem.

**Comment by dcworldwide** [comment]
FYI.

sudo chmod 777 .serverless
rmdir .serverless

Then you are good to go.

**Comment by LaundroMat** [comment]
I have this error every time I try to deploy

    EACCES: permission denied, open '/home/xxxxxxx/.cache/serverless-python-requirements/downloadCacheslspyc/requirements.txt'

I `sudo rm -r` the downloadCacheslspyc directory and then it works.

**Comment by makrandp** [comment]
i did sudo -s and it solved the issue

**Comment by dalvaro74** [comment]
> i did sudo -s and it solved the issue

Makrandp,

Really awesome... It works for me too, but I don't know why...
Can you help me to understand?

Thank you very much.

**Comment by StefanoA1** [comment]
If anyone is using webpack serverless plugin (`"serverless-webpack"`), the latest version `"^5.7.0"` fixes the problem

**Comment by lahdo** [comment]
sudo chmod 777 .serverless

**Comment by SELVAKUMARU** [comment]
Just delete the .serverless folder because the error message mentions an issue related to cleaning up temporary directories. It's possible that a previous deployment attempt left some temporary files in the .serverless directory that are causing conflicts. Try manually deleting the .serverless directory before running the sls deploy command again. Try this which may helpful to you.

**Comment by matiasvallejosdev** [comment]
Run it with:

`sudo serverless deploy`

**Comment by olzh-yess** [comment]
> Run it with:
> 
> `sudo serverless deploy`

This worked for me! God bless you!
