### ISSUE TITLE
Lambda versions leaking and eating up space

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#400]
I am having problems with a Serverless project that is exceeding the AWS Lambda code limit of 1.5GB per region. After deploying there's often extra Lambda versions left around eating up space. Deleting them manually is fairly tedious, so I guess Serverless should be doing that automatically after deploying each function and updating the stage tag?

![screen shot 2015-12-17 at 22 58 32](https://cloud.githubusercontent.com/assets/13944/11881820/e05ca8ae-a511-11e5-8128-95798f82f49b.png)

**Comment by zuhair-naqvi** [comment]
+1

**Comment by thedevkit** [comment]
+1

Just spent a good 20 minutes cleaning up lambda versions. A huge pain.

**Comment by ac360** [comment]
Sorry.  We will work on this within the framework.  I have also just brought this to AWS's attention.

**Comment by ac360** [comment]
A problem that could result from auto-deleting versions is that it hurts your rollback ability. 

However, I think we can help this with the framework.  We can store version, stage and date to each Lambda backup in your project bucket.  We could also slip `s-function.json` into your lambda codebase, which would allow the Framework to rollback a lambda WITH its config settings.  This could actually be super cool...

**Comment by jankei** [comment]
+1
so, using the cli can help
https://docs.aws.amazon.com/cli/latest/reference/lambda/delete-function.html
i can loop with the qualifier flag
lambda delete-function --function-name myFuncName --qualifier 21
and ignore the errors of not deleting the latest and aliased functions

**Comment by Nopik** [comment]
I wrote some plugin for this: https://github.com/Nopik/serverless-lambda-prune-plugin - it will go over all your functions in the AWS account (not only those declared in project!) and delete old versions in kind of controlled manner (aliased versions wont be deleted, and N most recent versions are kept).

**Comment by ebsbk** [comment]
Is there native sls way to delete old aws lambda versions?

**Comment by pmuens** [comment]
Hey @ebsbk here's a plugin which will help you with that: https://github.com/claygregory/serverless-prune-plugin

**Comment by onkar27** [comment]
```
import json
import boto3
from collections import Counter

client = boto3.client('lambda')

def lambda_handler(event, context):
    response = None
    nextMarker = None
    while (response is None or nextMarker is not None):
        if nextMarker is None:
            response = client.list_functions(FunctionVersion='ALL', MaxItems=50)
        else:
            response = client.list_functions(FunctionVersion='ALL', MaxItems=50, Marker=nextMarker)
        nextMarker = response['NextMarker']
        functions = response['Functions']
        print (response)
        for function in functions:
            if function['Version'] != '$LATEST':
                try:
                    response = client.delete_function(FunctionName=function['FunctionName'], Qualifier=function['Version'])
                    print("Deleted ",function['FunctionName']," Version ",function['Version'], sep = "->")
                except Exception as e:
                    print("Failed to delete ", function['FunctionName'], " of version ", function['Version'])
```

**Comment by shengslogar** [comment]
This issue was closed as completed, but I just ran into this issue today and rectified it by installing [`serverless-prune-plugin`](https://github.com/claygregory/serverless-prune-plugin) mentioned above. Is that considered the official solution or am I missing something obvious (old framework version, too much coffee, etc.)?
