### ISSUE TITLE
Stack removal fails due to a stage being associated to a usage plan

### ISSUE THREAD

**Issue by antanasbrazenas** [serverless/serverless#4006]
# This is a Bug Report

## Description
Stage is not getting dissociated from `UsagePlan` resource when deleting the stack. On a rare occasion dissociation succeeds but most of the time stack removal completes with the following error:

> Cannot delete Usage Plan ****** because there are API Stages associated with it, including...

This leads me to believe there is a race condition with the API call that serverless issues to remove stage association from usage plan at the begginning of `sls remove` command.

For bug reports:
* What went wrong?
Stack removal fails when api keys are created using serverless notation.

* What did you expect should have happened?
Stack to be removed successfully.

* What was the config you used?
Basic service with a single `apiKeys` entry within the `provider` section.

* What stacktrace or error message from your provider did you see?
> Cannot delete Usage Plan ****** because there are API Stages associated with it, including...

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
N/A

* If there is additional config how would it look
N/A

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: MacOS X 10.11.6
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by bsdkurt** [comment]
I think this is fixed now. At least I don't see the issue with 1.24.1 and usage plans depend on ApiGatewayDeployment<randnumber> which should address the ordering issue described in this bug.

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
