### ISSUE TITLE
Have "single point of truth" for stage and region

### ISSUE THREAD

**Issue by sbstjn** [serverless/serverless#4008]
Is there a "single point of truth" which `region` and `stage` serverless uses to deploy the service? 

When I write a plugin, I receive a `serverless` and `options` object and must always check if `options` overwrites the information in `serverless.service.provider.stage`. Maybe I'm holding it wrong, but if not, it would be great to have one variable to rely on.

### Basic plugin

```js
class Plugin {
  constructor (serverless, options) {
    if (options && options.region) {
      this.region = options.region
    } else {
      this.region = serverless.service.provider.region
    }

    if (options && options.stage) {
      this.stage = options.stage
    } else {
      this.stage = serverless.service.provider.stage
    }
  }
}
```

Of course the if-checks can be written more sexy, but `serverless` should do this in one place and it should not be needed in every plugin. 

If there is already somewhere a configuration I can access, please point me to it :)

Thanks!

**Comment by pmuens** [comment]
Hey @sbstjn thanks for opening 👍

Yes, that's a pretty nasty problem. Currently the `stage` / `region` is set [here](https://github.com/serverless/serverless/blob/df60412c254c849c5497bb950b0e2f29e3916c3f/lib/plugins/aws/lib/validate.js#L12-L17) and helper methods are [here](https://github.com/serverless/serverless/blob/df60412c254c849c5497bb950b0e2f29e3916c3f/lib/plugins/aws/provider/awsProvider.js#L224-L231) and [here](https://github.com/serverless/serverless/blob/df60412c254c849c5497bb950b0e2f29e3916c3f/lib/plugins/aws/provider/awsProvider.js#L246-L253).

I agree, that a more convenient method for plugin development would be nice here :+1:

Might be related to https://github.com/serverless/serverless/issues/2631

**Comment by sbstjn** [comment]
The `getStage()` function works fine. Having this somewhere in the docs would be enough 👍

**Comment by pmuens** [comment]
> The getStage() function works fine. Having this somewhere in the docs would be enough 👍

Great 👍. Glad to hear that this resolves your problem!

Do you want to PR the change to the docs (could be added to the plugin docs) since you brought this up? Or should we take care of that?

Right now, only the [AWS plugin documentation](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/plugins.md) needs to be updated (since only this `provider` plugin implementation provides the functionality):

**Comment by medikoo** [comment]
Closing in favor of https://github.com/serverless/serverless/issues/8628
