### ISSUE TITLE
400 error when doing Method Test from API Gateway UI

### ISSUE THREAD

**Issue by agentmilindu** [serverless/serverless#401]
I get this error when I use the 'Test' option in API Gateway for an endpoint I have deployed with 'Serveerless'.

```
{"message": "1 validation error detected: Value \'arn:aws:lambda:us-west-2:xxxxxxxxxxx:function:Maturify-UserSignup:\' at \'functionName\' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?"}
```

This is a POST request and I'm sure I gave the needed request body JSON when testing. 

But when I do a request using Postman, I get the expected output. 

However, I'm having trouble calling this endpoint from a webpage, I get an `No 'Access-Control-Allow-Origin' header is present on the requested resource.` error. Actually I'm debugging this error, and found out this Testing problem too.

**Comment by eahefnawy** [comment]
For the testing issue in the AWS console, it's actually an AWS bug. They have an issue with their regex validation.

As for calling the endpoint from a webpage, I'm guessing maybe it's because it's a POST request, and calling from a webpage is a GET request? For this particular case, if it's working from Postman, you should be good to go :+1:

**Comment by agentmilindu** [comment]
Thanks a lot about that issue in the AWS console :) 

I'm using jQuery to do a POST request with a JSON string as data. Following is the error I get when making the POST request. When I checked the response header, there was no `Access-Control-Allow-Origin` actually. 

I think Postman does not check CORS like browsers do, that's why it is not giving any error.  

>XMLHttpRequest cannot load https://xxxxxxxx.execute-api.us-west-2.amazonaws.com/prod/user/signup. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yyyyyyyyyy.s3-website-us-east-1.amazonaws.com' is therefore not allowed access.

**Comment by visualasparagus** [comment]
The issue calling from a webpage is an issue that CORS has not been setup for that method on that resource. At the moment it looks like this is on the roadmap for serverless. Until then, the AWS console offers an easy way to do it *by hand*. If you select a resource you can click **Enable CORS** and it will create the additional settings required. (See screenshots)

![cors-select](https://cloud.githubusercontent.com/assets/4904741/11892729/2f390a0e-a56b-11e5-950c-ae1a5b684cbb.png)

![cors-options](https://cloud.githubusercontent.com/assets/4904741/11892743/45ec7114-a56b-11e5-84c4-c9927d587e61.png)

**Comment by agentmilindu** [comment]
thanks, but I tried that too, and still no difference.

**Comment by eahefnawy** [comment]
@visualasparagus good catch! Thanks for clearing this up. It's in the road map and we'll fix it asap!

**Comment by visualasparagus** [comment]
@agentmilindu seems like a CORS issue though and not a serverless one though.

maybe check this? http://www.html5rocks.com/en/tutorials/cors/

**Comment by agentmilindu** [comment]
I asked about this on AWS forum and got to know some other bugs in AWS API Gateway. Here is the thread ihttps://forums.aws.amazon.com/thread.jspa?messageID=691884

**Comment by agentmilindu** [comment]
thanks @visualasparagus I'll go though that.
thanks @eahefnawy, I'm looking forward for the fixes :)

**Comment by contractorwolf** [comment]
ahh, I am getting the same issue testing in the Amazon API Gateway:

{"message": "1 validation error detected: Value \'arn:aws:lambda:us-east-1:237169730438:function:ServerlessAPI-show:\' at \'functionName\' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?"}

The weird thing is that my endpoints were working fine from the API Gateway just last night, now nothing works.  I thought it was something else I had done in the resources-cf.json file when I was trying to add my DynamoDB stuff and ended up backing out everyone of my changes in the project until I was back to square one with no fix.  I then decided to start with a fresh project with just a single module and a single GET endpoint but it still doesn't work.

Even weirder is the fact that I looked back at my JAWS project and I can still test all of my endpoints using the API Gateway without issue.  It is only my Serverless code that cant be tested via the API Gateway right now.  It all works without issue just using the browser, I just cant test via the API Gateway, which I find extremely unsettling.  

I tried @visualasparagus change to set the CORS in the AWS console but that didnt fix it for me either, any other tricks or work-arounds that you guys have found?

**Comment by ac360** [comment]
@contractorwolf Sorry about this, but the bug is on AWS's end.  See https://github.com/serverless/serverless/issues/344  AWS recommended we use stage variables in the Lambda ARN for the optimal workflow, but it breaks their Dashboard's regex.  Yet the endpoints still work. :\

**Comment by contractorwolf** [comment]
thanks @ac360 that was driving me crazy trying to figure out why my project wouldnt test in AWS console anymore

**Comment by shalzz** [comment]
Hello, I'm now getting this issue even when calling the endpoint directly. The endpoint no longer works and gives the OP's error for every request no matter from where it's called.
