### ISSUE TITLE
Fail instead of just warn when variables are broken

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#4012]
# This is a Feature Proposal

## Description

When running `serverless deploy` and an environment variable is not set the framework logs out a warning, but doesn't exit with a failure. Therefor my CI system indicated a successful build while my deployed infrastructure was broken.

```
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:SOME_SECRET' could not be found.
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0

**Comment by pmuens** [comment]
Hey @nikgraf thanks for opening 👍

We had a similar discussion in https://github.com/serverless/serverless/issues/3491 and https://github.com/serverless/serverless/pull/3891 is a PR which adds an implementation for that.

Do you think this solves your problems?

**Comment by pmuens** [comment]
Closing for now since this issue got quite stale and changing this would result in a breaking change.
