### ISSUE TITLE
Improve Serverless.yml Reference in the document

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4016]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When searching available properties in serverless.yml, I usually read [Serverless.yml Reference Page](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/#serverlessyml-reference). However, Several available properties are not listed.

IMO, we should list all available properties and write up more detail of each properties in the page so that the page makes it easy for users to understand how to use the yaml file.

The page is the most important to get a syntax of the yaml file.

* If there is additional config how would it look
The doc format would be something like:
```
# Serverless.yml Reference
## Available properties
Here is a list of all available properties

## The detail of all top-level propertoes
### provider
Here is a detail of top level property

### pakage

### function

```

**Comment by pmuens** [comment]
Thanks for creating the issue! That's a good idea @horike37 👍

Do you want to take a first stab at it? Maybe it's worthwhile to introduce this for the other providers as well!

**Comment by horike37** [comment]
>Do you want to take a first stab at it?

Yup. That's a great idea :sunglasses:

**Comment by pmuens** [comment]
> Yup. That's a great idea 😎

@horike37 great! Let us know if you need any help here!
