### ISSUE TITLE
Optimize AWS CloudFormation handling

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#4028]
# This is a Feature Proposal

## Description

Performance of processing of CloudFormation stacks (creation/update/removal) is far from great, and while (as I investigated) main issues are on AWS side, there's also a room for improvement in how Serverless handles things.

1. Creation of stack in SLS is combination of two calls: `createStack` and `updateStack`. While it can be just covered by `createStack` call, and in such case it'll run faster (in same cases it goes down to 10-20 seconds faster)

2. Update of stack invokes following superfluous updates:
- Each function even if not changed, is repackaged, reuploaded to new folder in S3 bucket, and marked with new version (if versioning is turned on). This could be improved, by:
  - Creating deterministic archives (it can be achieved  by passing `date` option that follows file modification date in [archiver's `zip.append`](https://archiverjs.com/docs/module-plugins_zip-Zip.html#append)), following that, on basis of generated file hash, we can decide whether we need to pursue with new S3 upload.
  - Same with function configuration, it could be hashed, and on that basis compared to currently published version, and decided whether template and version of that function should change
- On every update the `AWSGatewayDeployment` receives [new logical id](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js#L151), while it's probably not necessary in some update cases (still I'm not certain on which exactly constraints this one depends)

Ideally, when no changes to functions and configuration was made, the same CF template should be generated.

* ***Serverless Framework Version you're using***: v1.19.0
* ***Operating System***: macOS v10.12.6

**Comment by pmuens** [comment]
Thanks for opening and doing this great analysis / writeup @medikoo 👍 🥇

We've pushed some changes in the past which should mitigate the problem of re-depoying stuff that hasn't changed. As the API Gateway part we need to re-generate the id because of a quirk on AWS end (otherwise API Gateway changes are not picked up).

I'll close this issue for now since it's quite old and we've addresses some of the very valid points mentioned here.
