### ISSUE TITLE
serverless invoke local with clientContext

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#4031]
# This is a Feature Proposal

## Description

When running "invoke local" I would need the addition to include clientContext. In our Lambdas we are using clientContext to provide additional/routing information that is needed for our Lambdas to run.

It is great that we can supply the `event` when testing/running locally with the `--path` flag but in addition to the event we would need to supply the handlers `context` as well.

**Comment by horike37** [comment]
What about adding `--context` flad to `invoke local` ?

For example:
```
$ sls invoke local -f hello --context '{"functionName":"hello","clientContext":....}'
```
and
```
$ sls invoke local -f hello --context-path context.json
```

**Comment by RafalWilinski** [comment]
Looks nice, I can try implementing that.
cc @horike37 @pmuens

**Comment by QAnders** [comment]
You make me so happy @RafalWilinski!

I agree with @horike37 's suggestion. It would be very convenient to have the option for both JSON as (--context) and a file (--context-path).

Please make sure that the context is always loaded as a JSON object though as context should always have to be JSON!

Now when using --path (for `event`) with a file it is loaded as "string" so we must always add `if (typeof event === 'string') event = JSON.parse(event);` which is a nuisance...

**Comment by QAnders** [comment]
Question, will this also work for webpack invoke?

`sls webpack invoke --function myFunction --path ../json.test`

**Comment by HyperBrain** [comment]
@QAnders The upcoming v3 version of serverless-webpack fully integrates with `serverless invoke local`, i.e. the `webpack invoke` command has been deprecated. The new integration automatically offers anything added to the native `invoke local` command, so this should be working automatically - if not just file a bug with the plugin and I'll handle it 😄 

You can try the version already in the [`v3.0.0`](https://github.com/elastic-coders/serverless-webpack/tree/v3.0.0) branch there.

**Comment by QAnders** [comment]
@HyperBrain , will v3 include the context as discussed above or would I have to merge that anyway into the current Servless version?

**Comment by HyperBrain** [comment]
@QAnders v3 will only use Serverless, so if Serverless supports it (e.g. by using the PR here) it will be supported by the plugin too. 
So, to verify and use it you have to use Serverless with the PR merged and v3 of the plugin.

**Comment by QAnders** [comment]
Cool! Thanks so much!
I just installed v3 of webpack and `invoke local` runs fine but I get an error for missing module. I'll raise an Issue in webpack instead.

**Comment by itsphat** [comment]
Hi everyone, 
I try to use `--context` and `--contextPath` flags, but it doesn't seem to pass the context to the function when I run `sls invoke local --context ....`.
When I check the value, it's alway `None`.
Here is my servesless version.
```
 sls -v                                                                                                                                                           1 ↵
Running "serverless" from node_modules
Framework Core: 3.21.0 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
If you have an idea how I should do, please help. Thanks!
