### ISSUE TITLE
"serverless package" requires AWS access if deploymentBucket provider config is used

### ISSUE THREAD

**Issue by adcreare** [serverless/serverless#4040]
# This is a (Bug Report)

## Description

The ```serverless package``` command requires AWS access if and only if deploymentBucket provider configuration is used. 

#### What went wrong?
When calling `serverless package` where the serverless.yml file contains the configuration `deploymentBucket` serverless will go and check if that bucket exists using the aws api and will fail if that bucket doesn't exist or if there is no access or if there are no aws access credentials are available.

However the same command when combined with a serverless.yml file that doesn't have deploymentBucket set, will work correctly and package. This also applies there are no aws credentials available on the machine performing the package. 

####  What did you expect should have happened?
The package function should behave exactly as without the configuration value of deploymentBucket and package the code assuming the bucket exists and will be accessible when deployed. 
Then serverless deploy should be the command that would fail when supplied with a package that attempts to use a deploymentBucket that doesn't exist or is unavailable. 

####  What was the config you used?
Example serverless.yml file using deploymentBucket

```
service: my-awesome-service

provider:
  name: aws
  runtime: nodejs6.10
  deploymentBucket: serverless-deployment-bucket-001

functions:
  engine:
    handler: awesome.handlerequest

```

####  What stacktrace or error message from your provider did you see?
```
 serverless package --verbose

  Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: The specified bucket does not exist
```

## Additional Data

* ***Serverless Framework Version you're using***:
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.19.0

* ***Operating System***:
Linux and OS X

**Comment by horike37** [comment]
Thank you for opening this up @adcreare !
Why do you need this? We'd like to know the case which the check when packaging a deployment is a something impediment.

**Comment by adcreare** [comment]
Hi @horike37 

The reason we stumbled into this is we use serverless package as part of our build process to create a deployment zip, then a separate release engine runs the deploy command. 

We have been moving to a single bucket for all our serverless stacks and hence discovered our package was failing after adding the deployment bucket configuration because the build agents don't have AWS access for security reasons. 

Hope that makes sense

**Comment by horike37** [comment]
Thank you for getting back @adcreare !
We have been discussing this on #4048 PR thread. Then in conclusion, if you can not access the internet or AWS for any reasons, we will change not to check the existence of deployment bucket.

If it is implemented and merged, your problem would be resolved.

**Comment by adcreare** [comment]
Yup @horike37 that sounds like a good solution to the issue.
