### ISSUE TITLE
DRY / refactor check for valid providers in helper function

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4043]
# This is a Feature Proposal

## Description

Right now we have different places where we check if the `provider` which is used in the service is valid (e.g. in the [config plugin](https://github.com/serverless/serverless/blob/793ef87b158f915d610114cd98fdcd25b48f4464/lib/plugins/config/config.js#L7-L9)).

We should DRY / refactor this check into one place so that we don't have code duplication and can add / remove providers easily.

/cc @brianneisler @eahefnawy

**Comment by medikoo** [comment]
It doesn't seem to be still relevant  as technically plugins are expected to define in a constructor a [`provider` property](https://github.com/serverless/serverless/blob/793ef87b158f915d610114cd98fdcd25b48f4464/lib/plugins/aws/deploy/index.js#L27), having that plugin manager [checks if that matches service provider, if not, plugin is not loaded](https://github.com/serverless/serverless/blob/793ef87b158f915d610114cd98fdcd25b48f4464/lib/classes/PluginManager.js#L36-L49).

Probably this issues dates before above handling was introduced.
