### ISSUE TITLE
Add possibility to exclude module (aws-sdk), even if other modules depend on it

### ISSUE THREAD

**Issue by vokrik** [serverless/serverless#4063]
# This is a Feature Proposal

## Description
When deploying to AWS, you want to omit the whole aws-sdk, because it is already present. The recommended way to deal with that is to put the aws-sdk into devDependencies. However when you use a package, that depends on aws-sdk, then it gets packed again. 

It would be great, if instead of
```
package: 
 exclude: /path/to/a/file
```
you could also write
```
package: 
 excludeModule: aws-sdk (maybe it should also specify a range of versions)
```
That would exclude aws-sdk from the final package even if other libraries depend on it.

Since the size of the sdk is quite significant, this will result in smaller zip files, which should translate to lower cold starts

**Comment by medikoo** [comment]
@vokrik it can be simply done via:

```
package:
  exclude: node_modules/aws-sdk
```

I'm closing this, but if you feel that's not sufficient for some reason please elaborate further
