### ISSUE TITLE
Serverless Run:  Please improve colors

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#4065]
# This is a Feature Proposal

## Description
The Event Gateway blue color is mostly unreadable.  Would prefer if light colors were used for the prefix and the text was white.

**Comment by DavidWells** [comment]
⚡️ ✨✨✨✨✨ https://github.com/bokub/chalk-animation#available-animations ✨✨✨✨✨

**Comment by nikgraf** [comment]
Rainbow all the things!!!

![rainbow](https://media.giphy.com/media/3o7TKDMPKsakcn9NU4/giphy.gif)

**Comment by nikgraf** [comment]
@ac360 this is the latest state after a bit of experimentation. I'm considering to color some parts of the right side as well, but not sure which ones.

Ideas? Feedback?

![screen shot 2017-08-10 at 16 58 45](https://user-images.githubusercontent.com/223045/29176898-7fc2bd42-7ded-11e7-8e3d-e3aff1e4d60f.png)

**Comment by horike37** [comment]
hooooo!!!⚡️⚡️⚡️
![m5z8nmv](https://user-images.githubusercontent.com/1301012/29176886-1e1170c6-7e28-11e7-9891-74f63499e8ba.gif)

**Comment by pmuens** [comment]
@eahefnawy is this completely done? Can we close this issue here?

**Comment by pmuens** [comment]
Closing since `serverless run` was discontinued for now...
