### ISSUE TITLE
Display Stack Name with `sls info -v`

### ISSUE THREAD

**Issue by alexdebrie** [serverless/serverless#4078]
# This is a Feature Proposal

## Description

It's difficult to configure variables using the [CloudFormation output syntax](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs) (`${cf:stackName.outputKey}`) as it's unclear where to find the stack name and output key.  I've found it's easiest to find the output key using `sls info -v` and then looking at the Stack Outputs, but you still need to figure out your stack name.

I propose adding the stack name with `sls info -v` and then updating the docs to make it easier to understand this. It should be pretty straightforward to implement but I just wanted to get feedback on display.

Current output of `sls info -v`:

```bash
$ sls info -v
Service Information
service: my-service
stage: prod
region: us-west-2
api keys:
  None
endpoints:
  POST - https://34jfj01jkf.execute-api.us-west-2.amazonaws.com/prod/hello
functions:
  hello: my-service-prod-hello

Stack Outputs
TrackLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:123110001234:function:my-service-prod-hello:23
ServiceEndpoint: https://34jfj01jkf.execute-api.us-west-2.amazonaws.com/prod
ServerlessDeploymentBucketName: my-service-prod-serverlessdeploymentbucket-4qhsgfdht2da
```
In the terminal _Service Information_ and _Stack Outputs_ are underlined.

I'm proposing to change `Stack Outputs` to `CloudFormation Stack` with Stack Name and Stack Outputs below it:

```bash
$ sls info -v
Service Information
service: my-service
stage: prod
region: us-west-2
api keys:
  None
endpoints:
  POST - https://34jfj01jkf.execute-api.us-west-2.amazonaws.com/prod/hello
functions:
  hello: my-service-prod-hello

CloudFormation Stack
Stack Name: my-service-prod

Stack Outputs:
  TrackLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:123110001234:function:my-service-prod-hello:23
  ServiceEndpoint: https://34jfj01jkf.execute-api.us-west-2.amazonaws.com/prod
  ServerlessDeploymentBucketName: my-service-prod-serverlessdeploymentbucket-4qhsgfdht2da
```

Open to better ideas on display -- I'm not a designer 😄

**Comment by tobyhede** [comment]
How about something like this?
Fits in quite nicely with the current output:
<img width="538" alt="screenshot 2017-08-14 16 58 25" src="https://user-images.githubusercontent.com/28390/29261277-09dcfce6-8112-11e7-89ff-0abeec1c7159.png">
