### ISSUE TITLE
Adding documentation/support for connecting to Mongodb client/DB cluster from Serverless

### ISSUE THREAD

**Issue by loremIpsum1771** [serverless/serverless#4086]
I'm currently implementing an app that uses AWS lamda functions to interact with AWS Lex chatbot. I need to get data from a database for it to be sent from Serverless back to the client side (the chatbot). It appears that this is fairly straightfoward [when using DynamoDB](https://www.youtube.com/watch?v=TGHppZnbGCY&t=0s) (presumably because it's already in AWS), but I need to use Mongodb effectively doing something similar to [this](https://www.mongodb.com/blog/post/serverless-development-with-nodejs-aws-lambda-mongodb-atlas) except using the Serverless Framework.

I started using the framework very recently so maybe this is already been implemented. If it has, can there be some specific tutorials/documentation created to show how to call MongoDB functions on a Mongo cluster or a local db? I've done a fair amount of googling and haven't been able to find anything yet.

*More information [here](https://stackoverflow.com/questions/45665574/how-to-call-mongodb-functions-from-an-aws-lambda-in-the-serverless-framework)*

Thanks!

**Comment by horike37** [comment]
Great proposal! @loremIpsum1771 
How about adding how to integrate with Mongodb to [Example Repo](https://github.com/serverless/examples)?
There are many samples and explanations for how to use and integrate with other products/services there.

**Comment by loremIpsum1771** [comment]
You mean I should recreate the issue for that repo? Sure.

**Comment by horike37** [comment]
Maybe no need.
If you want to introduce the example to Example Repo, I think that you would directly send Pull Request.

**Comment by loremIpsum1771** [comment]
I don't know how integrate serverless with MongoDB. I created the issue because I thought that someone who might know how to do it could add documentation for it.

**Comment by horike37** [comment]
Oh, sorry. I misunderstood...

I just found the MongoDB example here.
https://github.com/serverless/examples/tree/master/aws-node-rest-api-mongodb

How about trying this?

**Comment by pmuens** [comment]
Thanks for opening @loremIpsum1771 and thanks for helping out @horike37 👍

Closing this for now since it's a stale issue and @horike37 pointed to a valid MongoDB example.

Feel free to comment / re-open if there's still a problem with this.
