### ISSUE TITLE
Inherting Variable definations

### ISSUE THREAD

**Issue by srizzling** [serverless/serverless#4089]
cc @iambridgetkate

# This is a Feature Proposal

## Description

I did a quick search and wasn't able to find what I wanted. 

We have a bunch of lambdas deployed to AWS using serverless. Each lambda has its own `serverless.yml` file.  Most of these yaml files have the same core definitions with minor differences. Is there any way to inherit these variable definitions or would this need to be a process outside of serverless.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I want a way to inherit variable definations from another yaml template.

* If there is additional config how would it look
N/A

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @srizzling 👍

> We have a bunch of lambdas deployed to AWS using serverless. Each lambda has its own serverless.yml file. Most of these yaml files have the same core definitions with minor differences. Is there any way to inherit these variable definitions or would this need to be a process outside of serverless.

You could outsource the repeating definitions in separate `.yml` file and re-import them with the help of the `file` syntax using Serverless Variables.

Inheritance is currently not supported by Serverless so you need to define the inheritance outside of Serverless.

**Comment by srizzling** [comment]
Is there a way to also have local templates, similar to how you generate the template for AWS for example?

**Comment by pmuens** [comment]
> Is there a way to also have local templates, similar to how you generate the template for AWS for example?

Hey @srizzling what exactly do you mean with "local templates"? You can have templates hosted on e.g. GitHub and install them with the help of the `serverless install` command.

Installing templates from a local directory is not supported yet. So right now you could have a script which copies the boilerplate over into your directory of choice (this could potentially be an interesting 3rd party plugin 🤔).

**Comment by pmuens** [comment]
Thanks again for opening @srizzling 👍

I'll close this issue for now since it got quite stale and there are no plans to add this kind of enhancement anytime soon. We'll definitely re-visit it when we plan to re-work the whole variable system.
