### ISSUE TITLE
npm-shrinkwrap.json should be published, not package-lock.json

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#4096]
# This is a Bug Report

## Description

As stated in the NPM docs https://docs.npmjs.com/files/shrinkwrap.json
> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies

Serverless is clearly in the "command-line" tool category.

Also stated in the docs is that package-lock.json will be ignored if found anywhere other than the top level project and should not be published to npm. https://docs.npmjs.com/files/package-lock.json

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json, which is essentially the same file, but allows publication.

Believe this issue was introduced in this PR https://github.com/serverless/serverless/pull/3690

**Comment by cardoni** [comment]
> **From**: https://docs.npmjs.com/files/package-lock.json

> [The `package-lock.json` file] describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

> **This file is intended to be committed into source repositories, and serves various purposes [...]**

@brianneisler, as you mentioned, the `package-lock.json` file shouldn't be published to the npm registry—but should be kept in version control.

**Comment by pmuens** [comment]
Thanks for opening @brianneisler 👍

So the solution here would be that we keep `package-lock.json` in the repo and let travis generate the `npm-shrinkwrap.json` before publishing since having both in the repo would mean that `package-lock.json` will be ignored in favor of `npm-shrinkwrap`, correct?
