### ISSUE TITLE
OPTION with Mock Request

### ISSUE THREAD

**Issue by base2arthur** [serverless/serverless#410]
Guys

Have you considered adding a Mock Options end point with a default set of cors enabled when creating a new function?

**Comment by supagroova** [comment]
:+1: Am battling with the API Gateway CORS setup right now, trying to enable XHR requests from the browser, and it's a total nightmare. Would be amazing to have this in by default :-)

**Comment by eahefnawy** [comment]
I'm not sure about mocking requests, but CORS support is definitely our focus right now. Would love to hear your thoughts on what's the best way to implement it.

**Comment by jimmyn** [comment]
It would be nice to have some flag like --cors on function generator, that would create a basic blueprint for CORS with options request, like aws console button "enable CORS" does. Really wait for this feature.

**Comment by visualasparagus** [comment]
+1

**Comment by joostfarla** [comment]
I’ve been working on a CORS plugin which takes care of adding the right headers and preflight requests. Will probably publish something later today. Already looking forward to your feedback.

**Comment by joostfarla** [comment]
Just released the first version of the CORS plugin: https://github.com/joostfarla/serverless-cors-plugin

**Comment by LukeSwart** [comment]
:+1: Just confirming that the serverless-cors-plugin resolved my missing `'access-control-allow-origin': '*'` header. Thank you @joostfarla!
