### ISSUE TITLE
Serverless Run: Whitelisting Function Properties sent to the Event Gateway

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#4105]
# This is a (Bug Report / Feature Proposal)

## Description

`cors: true` makes the Event Gateway error when running `serverless run`. We should not pass it to the gateway and use a property whitelisting approach to only send to the Event Gateway the properties it accepts.

**Comment by pmuens** [comment]
Closing since `serverless run` was discontinued for now...
