### ISSUE TITLE
Serverless Run: Improve reading in stdout and stderr from subprocesses

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#4107]
# This is a Bug Report

## Description

To read stdout and stderr from the Event Gateway we split the lines by `\n`. I haven't tested, but believe this currently breaks if there is a `\n` inside the content. We should test and if necessary fix it.

This might help: https://github.com/jahewson/node-byline

**Comment by pmuens** [comment]
Closing since `serverless run` was discontinued for now...
