### ISSUE TITLE
Serverless Run: Cleanup Event Gateway Output

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#4108]
# This is a Bug Report

## Description

In favour of the demo we removed a handful of important Event Gateway messages here https://github.com/serverless/serverless/pull/4034/commits/fca3015a5ec63f166df5567ba7b05def45cbdf7f and here https://github.com/serverless/serverless/pull/4034/commits/35499a5e89d7c1d861a4eec14fdd51fb56846582

I suggest the following approach
- [ ] Check for all existing log on info, debug, error and warn level e.g. https://github.com/serverless/event-gateway/search?utf8=%E2%9C%93&q=log.Info&type=
- [ ] Implement a whilelist matching to format each log
- [ ] Create a proper test-suite covering each of these logs
- [ ] Create fallback to see the raw event if we messed up (better to show something bad formatted than nothing)

**Comment by pmuens** [comment]
Closing since `serverless run` was discontinued for now...
