### ISSUE TITLE
deploy list functions returns no functions

### ISSUE THREAD

**Issue by awildturtok** [serverless/serverless#4109]
# This is a Bug Report

## Description

After having invoked `sls deploy` to deploy to AWS and checking that functions are in fact on lambda. Using `sls deploy list functions` nothing gets shown beside:

```
Serverless: Listing functions and their last 5 versions:
Serverless: -------------
```

## Additional Data

* ***Serverless Framework Version you're using***:  1.18.0

* ***Operating System***: Windows10

**Comment by pmuens** [comment]
Hey @awildturtok thanks for opening 👍!

I believe that I fixed this bug in one of the last versions of Serverless. Could you please update and try again? Thanks in advance!

**Comment by awildturtok** [comment]
You are right! Thanks for that. This issue can be closed.

While I have someones attention, is there a way to remove/disable the `Serverless:` prefix from the CLI output? I am parsing some parts of sls' output, but having to remove that makes it kind of annyoing to work around.

**Comment by pmuens** [comment]
> You are right! Thanks for that. This issue can be closed.

Great! Thanks for getting back and confirming @awildturtok 👍. I'll close this issue then 😊.

> While I have someones attention, is there a way to remove/disable the Serverless: prefix from the CLI output? I am parsing some parts of sls' output, but having to remove that makes it kind of annyoing to work around.

Unfortunately there's no way to do this right now. However we have another issue open which will tackle this problem: https://github.com/serverless/serverless/issues/3089.
