### ISSUE TITLE
Add appveyor integration

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4121]
# This is a Feature Proposal

## Description

@lorengordon was kind enough to fix the tests so that they can be executed on Windows. Furthermore he added support for Appveyor builds (all done via https://github.com/serverless/serverless/pull/4059).

We should add the Appveyor integration ASAP so that one can see the Appveyor build in the merge dialogue. This way we can ensure that Serverless builds on UNIXiod systems alongside Windows.

/cc @brianneisler

**Comment by pmuens** [comment]
Was added by @brianneisler yesterday (thanks for doing that) 👍!

Closing...

**Comment by lorengordon** [comment]
Very nice! Thanks! 💯

**Comment by pmuens** [comment]
Thanks for helping here @lorengordon 👍 💯
