### ISSUE TITLE
Can't set project domain

### ISSUE THREAD

**Issue by JoshZA** [serverless/serverless#413]
Once I enter my project name, Serverless skips domain entry, and goes straight to email entry.

This means all my projects are stuck on myapp.com :pensive: 

Windows 8.1 x64

![image](https://cloud.githubusercontent.com/assets/136638/11917688/e4e0ddd2-a719-11e5-8928-ff17487cf6c4.png)

**Comment by eahefnawy** [comment]
@JoshZA is this still an issue? could you try out using our master branch (not our npm release)?
