### ISSUE TITLE
"npm install serverless" is failing for >=1.20.0

### ISSUE THREAD

**Issue by Kosta-Github** [serverless/serverless#4131]
# This is a Bug Report

## Description

Unable to install `serverless` via `npm install serverless`; failing with this error message:

```
npm ERR! 401 Unauthorized: @serverless/fdk@^0.3.0
```

This was introduced in `1.20.0`: https://github.com/serverless/serverless/blob/1669569374c8ab3e54619d76e73c7806f724470c/package.json#L89

There shouldn't be a scoped package reference `@serverless/fdk` within `package.json`, right?

**Comment by pmuens** [comment]
Thanks for opening @Kosta-Github 👍

The scoping is correct. 🤔 that's an interesting one since the repo is publicly accessible: https://www.npmjs.com/package/@serverless/fdk

Are you sitting behind a proxy or smth.?

/cc @nikgraf

**Comment by nikgraf** [comment]
Interesting, @Kosta-Github do you mind sharing your npm version?

**Comment by Kosta-Github** [comment]
This is the output (with working working stuff stripped away) of `npm install --verbose`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--verbose' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose npm-session 4ea6b55bd16c2049
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall aws-xray-sdk-test@1.0.0
7 info lifecycle aws-xray-sdk-test@1.0.0~preinstall: aws-xray-sdk-test@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 304 https://registry.npmjs.org/aws-serverless-express 276ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/aws-sdk 280ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/serverless-plugin-optimize 285ms (from cache)
17 silly pacote range manifest for aws-serverless-express@^3.0.2 fetched in 287ms
18 silly pacote range manifest for aws-sdk@^2.80.0 fetched in 290ms
19 silly pacote range manifest for serverless-plugin-optimize@^3.0.3-rc.1 fetched in 328ms

...

1524 silly resolveWithNewModule uuid@2.0.3 checking installable status
1525 silly pacote range manifest for write-file-atomic@^2.1.0 fetched in 5ms
1526 silly resolveWithNewModule write-file-atomic@2.3.0 checking installable status
1527 http fetch GET 401 https://registry.npmjs.org/@serverless%2ffdk 571ms
1528 silly fetchPackageMetaData error for @serverless/fdk@^0.3.0 401 Unauthorized: @serverless/fdk@^0.3.0
1529 verbose stack Error: 401 Unauthorized: @serverless/fdk@^0.3.0
1529 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
1529 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1529 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
1529 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
1529 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1529 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1529 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
1529 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
1529 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
1529 verbose stack     at runCallback (timers.js:781:20)
1529 verbose stack     at tryOnImmediate (timers.js:743:5)
1529 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
1530 verbose cwd /Users/kosta/devel/fluent/min-xray-repo-case
1531 verbose Darwin 16.7.0
1532 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "i" "--verbose"
1533 verbose node v8.4.0
1534 verbose npm  v5.3.0
1535 error code E401
1536 error 401 Unauthorized: @serverless/fdk@^0.3.0
1537 verbose exit [ 1, true ]
```

As you can see at the top of the logs I am using:
* node: `8.4.0`
* npm: `5.3.0`
* OS: `uname -a`: `Darwin bla 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`

**Comment by RafalWilinski** [comment]
Looks like caching issue, `https://registry.npmjs.org/@serverless%2ffdk` returns `200` for me. Have you tried running `npm cache clean` and then trying to install serverless?

It *might* help but it seems that it's cached somewhere else, on a  HTTP layer.

What happen if you try accessing https://registry.npmjs.org/@serverless%2ffdk in your browser? And in private mode?

**Comment by Kosta-Github** [comment]
mh, that is interesting:
* cleaning the `npm cache` doesn't help,
* I can access the file via the URL from the browser,
* I can `curl` the file via the URL from the commandline,
* installing it via `npm install @serverless/fdk --verbose` is still giving me `401 Unauthorized: @serverless/fdk@latest`

**Comment by Kosta-Github** [comment]
I found the issue: I am using an `~/.npmrc` file with content like this for accessing packages from within our companies `npm scope` (`my_scope` in the example below):
```
_auth = <token deleted>
email = <email deleted>
@my_scope:registry=https://<my_host>.com/artifactory/api/npm/npm-virtual
```
If I remove that file `@serverless/fdk` can be installed without issues.

Now I need to figure out how to make that working together with the ability to also access my companies private repos via the `my_scope` scope. Any ideas?

**Comment by Kosta-Github** [comment]
solution found: I need to reformat my `.npmrc` file like this, so that the `auth` token gets only applied to the `company scope`:
```
email=<email deleted>
@my_scope:registry=https://<my_host>.com/artifactory/api/npm/npm-virtual
//<my_host>.com/artifactory/api/npm/npm-virtual:_auth="<token deleted>"
```

**Comment by pmuens** [comment]
Great that you were able to resolve this one @Kosta-Github 👍!

Thanks for posting the solution and thanks for helping out @RafalWilinski 💯
