### ISSUE TITLE
serverless remove fails due to managed policies automatically added to IAM Roles

### ISSUE THREAD

**Issue by deanpeterson** [serverless/serverless#4141]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
serverless remove did not finish due to an error
* What did you expect should have happened?
The serverless remove should have finished successfully
* What was the config you used?
The default aws-nodejs template
* What stacktrace or error message from your provider did you see?
An error occurred while provisioning your stack: IamRoleLambdaExecution - Cannot delete entity, must detach all policies first..

## Additional Data
This is an AWS environment set up for the State of MN. When the serverless service is deployed, roles automatically get extra managed policies attached that prevent the "serverless remove" command from running successfully. See image below:
![image](https://user-images.githubusercontent.com/1156788/29598912-b31572ae-8791-11e7-8652-2372f6ad0467.png)

* ***Serverless Framework Version you're using***: 1.20.2
* ***Operating System***: Windows 7
* ***Stack Trace***: 
  Serverless Error ---------------------------------------

  An error occurred while provisioning your stack: IamRoleLambdaExecution - Cannot delete entity, must detach all policies first..
* ***Provider Error messages***:

**Comment by WanderingBrooks** [comment]
I'm experiencing this as well. Deploy goes smoothly and everything in the removal process is taken down except for roles with policies created by serverless. The error I'm getting is "An error occurred while provisioning your stack: RoleName - Cannot delete entity, must delete policies first..". The user trying to remove has full access to IAM and through the AWS CLI, I am able to delete these roles without a problem. Any help is appreciated.

**Comment by bobjamin** [comment]
It won't delete the policies because they were attached by something else unrelated to the stack created by serverless.
The solution is to explicitly define the IAM Role with those policies in the serverless yml.
I have seen the same issue with managed policies and am hoping this issue will resolve it (Issue - #3751)

**Comment by aantillonl** [comment]
I had something similar happening during a STACK_UPDATE operation, the strange thing is that although errors were reported during the operation due this policies, the IAM Role and policies were in fact removed by the update operation. In my case just re-running the update worked fine.

**Comment by pmuens** [comment]
Closing this one since it's quite old and it looks like the reason for this is that something else attached the IAM role. The Serverless Framework only manages resources it creates and has ownership over.

**Comment by bo-bac** [comment]
it seems can be reprodused (in my case it was)
1 deploy stack with lambda `cloudformation create-stack` + `package `+ `deploy`
2 turn on x-ray tracing in console  **<- that must be a problem**
3 delete stack `cloudformation delete-stack`

fact:
1 lambda is deleted
2 stack is not deleted with mentioned error
3 there is lambda role in IAM with AWSLambdaTracerAccessExecutionRole-....  permission

Should `cloudformation delete-stack` delete lambda role even it has additional permissions added during runtime?
