### ISSUE TITLE
Variables: Pass CLI params to JS file resolvers

### ISSUE THREAD

**Issue by awildturtok** [serverless/serverless#4143]
# This is a Feature Proposal

## Description

The functionality to include and evaluate JavaScript files is pretty neat, though it seems to be kinda inflexible. My proposal would be to pass the options object that is already available into the handler, when evaluating the js file.

The only change necessary seems to be adding the options [here](https://github.com/serverless/serverless/blob/33431cb45ad273e760f19a7eb9c127e7c2bc15f1/lib/classes/Variables.js#L263).

It's obviously debatable wether this strays too far into the territory of plugins, but it would make my life right now a lot easier without any (for me) obvious drawbacks.

**Comment by martinjlowm** [comment]
Any news on this issue? 

My current situation is that I need to know provider information in a JavaScript file. A smart way would be to simply pass that information with something like `${file(config.js):someVariable(${self:provider.region})`. - obviously, that is not yet possible.

A hacky workaround is to pass arguments as environment variables, but that would (to be dynamic) require region in `serverless.yml` to be set with `${env:REGION}` and then reference `process.env.REGION` in the JavaScript file.

**Comment by medikoo** [comment]
I think it's doable to pass CLI params (so what internally is often called `options`) to JS file variable resolvers, and we'll take it into account when rewriting variable resolver, which is covered here: https://github.com/serverless/serverless/issues/7207

**Comment by medikoo** [comment]
It's solved with new variables resolver. Check https://www.serverless.com/framework/docs/providers/aws/guide/variables#exporting-a-function
