### ISSUE TITLE
Hide api key generated by sls from the serverless console output

### ISSUE THREAD

**Issue by shahpawan** [serverless/serverless#4156]
# This is a Feature Proposal

## Description
Serverless allows generating api key with usage plans.
Here is the serverless document which explains the config for this 

https://serverless.com/framework/docs/providers/aws/events/apigateway/#setting-api-keys-for-your-rest-api

The api key generated gets printed in the console output as mentioned in the link above, which is not a great practice for prod.
So if serverless is running in a common CD tool, someone with readonly access can get the api token by just looking at logs. 
So will be great if serverless can have some option / flag to hide api key generated.

**Comment by timstott** [comment]
I have started to work on this feature 🎉. The api key names will still be displayed in the output however the values will blank.

```console
$ serverless deploy --obfuscate-api-keys

Service Information
service: helloworld
stage: production
region: us-west-1
api keys:
  production-helloworld-user1-key
endpoints:
  POST - https://example.com/say
functions:
  say: helloworld
```

Any thoughts on this proposal? Flag name suggestions are also welcomed 😊

**Comment by shahpawan** [comment]
hi, may be some flag in server config file will be great than adding flag in deploy command as this is a small feature. thoughts?

**Comment by horike37** [comment]
That's awesome @timstott 💯  Thank you for moving forward 👍 
Let us know if you need any helps to go ahead!

**Comment by timstott** [comment]
@shahpawan I didn't consider having this options in the config file. I liked it at first. Then realised this options is only concerned with CLI output. In contrast *serverless.yml* is concerned with our application definition.

@horike37 Thanks for the motivation 🎉 ! I'm torn with the option name. All `deploy` options have one word currently (awesome). I wanted to propose  `--conceal-api-keys` but perhaps it can be more universal; to conceal all secrets/tokens displayed on deploy. Then `--obfuscate` or `--conceal` would be more sensible.

I would however only work on concealing the API key values on the upcoming PR. But the universal option would be available for anyone to use.

```console
# Example with --conceal-api-keys (limited output for conciseness)
serverless deploy --help
Plugin: Deploy
deploy ........................ Deploy a Serverless service
    ...
    --verbose / -v ..................... Show all stack events during deployment
    --force ............................ Forces a deployment to take place
    --function / -f .................... Function name. Deploys a single function (see 'deploy function')
    --conceal-api-key .................. Conceal API keys values in output
```

Any thoughts or comments :bowtie: ?
