### ISSUE TITLE
context.getRemainingTimeInMillis() increments when called from a locally invoked function

### ISSUE THREAD

**Issue by e-e-e** [serverless/serverless#4159]
# This is a Bug Report

## Description

* What went wrong? `context.getRemainingTimeInMillis()` increments when called from a locally invoked function 

* What did you expect should have happened? This should decrement from the number of seconds declared in the functions serverless.yml settings.

* What was the config you used?
```yml
functions:
  test:
    handler: apiWorker.test
    memorySize: 128
    timeout: 10
```
* What stacktrace or error message from your provider did you see?

```js
module.exports.test = (event, context, callback) => {
  setInterval(() => {
    const remaining = context.getRemainingTimeInMillis()
    console.log('remaining time =', remaining)
    if (remaining < 10) callback(null, {})
  }, 100)
}
```
gives the following output:
```sh
remaining time = 104
remaining time = 207
remaining time = 310
remaining time = 412
remaining time = 516
...
remaining time = 1352
remaining time = 1457
remaining time = 1560
remaining time = 1666
remaining time = 1770
remaining time = 1875
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.2
* ***Operating System***: Mac OSX 10.10.5

**Comment by RafalWilinski** [comment]
Thanks @e-e-e for reporting issue!

The problem that you've mentioned has been already addressed here: https://github.com/serverless/serverless/pull/4047

It's going to be released in version 1.21.0 so hopefully in a next few days.

**Comment by pmuens** [comment]
Thanks for opening @e-e-e and thanks for jumping in @RafalWilinski 👍

@RafalWilinski is correct.

This feature is already in `master` and will be shipped with the upcoming release 💯.

**Comment by e-e-e** [comment]
Ah! Thanks @RafalWilinski and @pmuens. I had a quick look to see if I could fix it and saw that it looked ok here - (https://github.com/serverless/serverless/blob/df5764dd4b6de6aba2e6c79c0d17648b019b0e15/lib/plugins/aws/invokeLocal/index.js#L245). But also was not sure if the issue was perhaps more complicated - so its nice to know that it had already been fixed. Thanks so much for the prompt reply!
