### ISSUE TITLE
Variables don't work in the plugins section of serverless.yml

### ISSUE THREAD

**Issue by vkarponen** [serverless/serverless#4161]
# This is a Bug Report

## Description

Variables don't seem to work in the plugins section of serverless.yml. Perhaps the plugins are loaded before the variable system has a chance to modify the configuration? Or perhaps the variable system does not support arrays at all.

* What went wrong?
I tried to populate the plugins section of serverless.yml file by using variables. Specifically I use the serverless-offline plugin, but I don't think the actual plugin used is of significance.  I failed to populate the section both from a commandline option as well as via the custom section (as well as by populating individual array items).

* What did you expect should have happened?
The offline version of serverless should have started. Aka exactly the same if I manually write 
```
plugins:
  - serverless-offline
```
to the serverless.yml file and launch `serverless offline`

* What was the config you used?
1. Using the commandline:
```
plugins: ${opts:plugins}
```
with a call to `serverless offline --plugins [serverless-offline]`

2. Using the custom section to populate the whole array
```
custom:
  plugins:
    - serverless-offline
plugins: ${self:custom.plugins}
```
with a call to `serverless offline`

3. Using the custom section to populate array items
```
custom:
  plugin1: serverless-offline
plugins:
  - ${self:custom.plugin1} 
```
with a call to `serverless offline`

* What stacktrace or error message from your provider did you see?
**_Serverless command "offline" not found_** 
for cases 1 & 2.
**_Serverless plugin "${self:custom.plugin1}" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file._** 
for case 3

Similar or dependent issues:
* -

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.2
* ***Operating System***: Windows 10
* ***Stack Trace***: -
* ***Provider Error messages***:  -

**Comment by alexdebrie** [comment]
Hey @vkarponen, sorry so long to respond on this. You're correct in this part: `Perhaps the plugins are loaded before the variable system has a chance to modify the configuration?`. Serverless loads all plugins first, _then_ parses the `serverless.yml`.

I've seen a few other people request the ability to do dynamic plugins based on config, but it would be a pretty big change to the way Serverless works and could break other workflows. As such, I'm going to close this issue, but we'll keep it in mind for future versions of Serverless. Please let me know if you have any questions on it.
