### ISSUE TITLE
Release Serverless as downloadable binaries

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4171]
# This is a (Bug Report / Feature Proposal)

## Description

The Serverless Framework should be offered as a downloadable binary so that it's easier to install and work with.

This could be done with the help of: https://github.com/zeit/pkg

## Todos

- `curl` install script
- `brew tap` support

/cc @brianneisler @eahefnawy

**Comment by pmuens** [comment]
Just tried `pkg` out today and it's pretty slick!

The following is a quick analysis if this is suitable for our needs.

**General impression / thoughts:**

Building binaries is as easy as `pkg .` in the root of the Serverless project. `pkg` will use the `package.json` file to figure out the entrypoint for the application (it also honors additional `npm` related configs).

However we need to tweak it a little bit since we got some `Warnings` when packaging it (see output below). Most of those warnings are `stat` warnings. We also have `dynamic` requires we need to resolve manually (see [here](https://github.com/zeit/pkg#config)).
Some files are included in the binary which might be better excluded (e.g. the `.test.js` files).

After building in a Docker container I was able to use the produced `macOS` binary on my local machine (I don't have Node.js installed on `macOS`). The size of the binary is 82 MB.

**Next steps:**

The next steps would be to resolve all the warnings.

After that we should build and distribute the binaries within the team for a test flight.

The final step would be to automate this process through Travis so that binaries are built for every release. We could start to ship binaries for the next release as an **experimental** feature people should try out (we should call that out in the corresponding release blog post).

---

**The output when building it**

```
root@aff53d71ad58:/app# pkg .     
> pkg@4.2.4
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.0.0-linux-x64     [====================] 100%
  fetched-v8.0.0-macos-x64     [====================] 100%
  fetched-v8.0.0-win-x64       [====================] 100%
> Warning Cannot stat, ENOENT
  /app/lib/classes/XYZ.json
  The file was required from '/app/lib/classes/Utils.test.js'
> Warning Cannot resolve 'referencedFileFullPath'
  /app/lib/classes/Variables.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'absolutePath'
  /app/lib/plugins/aws/invokeLocal/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot find module 'serverless-webpack' from '/app/lib/plugins/create/templates/aws-nodejs-ecma-script'
  /app/lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js
> Warning Cannot stat, ENOENT
  /app/lib/plugins/create/templates/aws-nodejs-ecma-script/.webpack
  The file was required from '/app/lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js'
> Warning Cannot find module 'serverless-webpack' from '/app/lib/plugins/create/templates/aws-nodejs-typescript'
  /app/lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
> Warning Cannot stat, ENOENT
  /app/lib/plugins/create/templates/aws-nodejs-typescript/.webpack
  The file was required from '/app/lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js'
> Warning Cannot stat, ENOENT
  /app/lib/utils/fs/XYZ.json
  The file was required from '/app/lib/utils/fs/fileExists.test.js'
> Warning Cannot stat, ENOENT
  /app/lib/utils/fs/XYZ.json
  The file was required from '/app/lib/utils/fs/fileExistsSync.test.js'
> Warning Cannot stat, ENOENT
  /app/lib/utils/fs/XYZ.json
  The file was required from '/app/lib/utils/fs/readFileIfExists.test.js'
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/lib/plugins/create/templates/aws-nodejs-ecma-script/first.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/lib/plugins/create/templates/aws-nodejs-ecma-script/second.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/node_modules/lodash-es/lodash.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/lib/plugins/create/templates/aws-nodejs-ecma-script/first.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/lib/plugins/create/templates/aws-nodejs-ecma-script/second.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/app/node_modules/lodash-es/lodash.js
> Warning Failed to make bytecode node8-x64 for file C:\snapshot\app\lib\plugins\create\templates\aws-nodejs-ecma-script\first.js
> Warning Failed to make bytecode node8-x64 for file C:\snapshot\app\lib\plugins\create\templates\aws-nodejs-ecma-script\second.js
> Warning Failed to make bytecode node8-x64 for file C:\snapshot\app\node_modules\lodash-es\lodash.js
```

**Comment by HyperBrain** [comment]
@pmuens The templates should be excluded (as they are complete projects that are extracted on create).
Would it be possible, to host the templates in general somewhere and let `serverless create`  download and install them to the target folder of the create operation? This would mean that there is a template registry and templates could be added transparently, regardless of the Serverless version running.
Similar to the plugin registry and `serverless install plugin`.

Additionally, it has to be made sure, that all public functions have to be available on all objects are still available in case a plugin is loaded by pluginManager. (E.g. pluginManager.spawn(), etc).

**Comment by pmuens** [comment]
Thanks for the input @HyperBrain 👍

Installing templates with the help of `create` or `install` is a good enhancement and already on our radar. Although we've no direct plans to offer a template registry yet 🤔.

> Additionally, it has to be made sure, that all public functions have to be available on all objects are still available in case a plugin is loaded by pluginManager. (E.g. pluginManager.spawn(), etc).

That's a good concern! We definitely need to test-drive this with different plugins, setups, etc.

Looks like there's more we need to keep in mind when working on support for that.

**Comment by pmuens** [comment]
Here's just a quick update on the current status quo.

I tested it again today and it turns out that the error with the `pipesCount` is related to a regression in `Node.js v8.x` (see: https://github.com/archiverjs/node-compress-commons/issues/25). Specifying the compilation target with the correct `Node.js` runtime solves the problem:

```bash
pkg . --targets node7-macos-x64
```

After doing that and running it on my Mac I can confirm that `package`, `deploy`, etc. works 🎉 (however we still need to take a deeper dive into this).

I also looked into homebrew as a way to distribute the binary. We could try to get our PR into the main ["Homebrew Core" repo](https://github.com/Homebrew/homebrew-core) (see [here](https://github.com/Homebrew/homebrew-core/tree/master/Formula) for all the furmlas) or use our own tap repository (like [this](https://github.com/caarlos0/homebrew-tap)) which we'll need to update accordingly.

My suggestion would be that we start with a simpler approach and upload the binaries to a dedicated `S3` bucket. We could automate this process with Travis.

Running `curl https://install.serverless.com | sh` would the "installation" script which will download the correct binary based on the users OS. We can add this line to the [Serverless homepage](http://serverless.com) later on.

**Comment by jfdesroches** [comment]
Thanks for the context. I've been playing with Tap for Sketch plugins via Homebrew, and it's pretty straightforward. But there's nothing quite like a generic "download and install" button or command :)

**Comment by pmuens** [comment]
Closing since this is not a focus right now and early experiments showed some downsides. We'll re-open this one once this is a priority again.

**Comment by pmuens** [comment]
Re-opening as we'll evaluate this further.
