### ISSUE TITLE
Add plan command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4179]
# This is a Feature Proposal

## Description

It would be nice to have a `serverless plan` command which shows a diff of all the changes which would be applied when `serverless deploy` will be executed.

The `plan` plugin could be implemented in a provider-independent way where it only does a JSON diff against the corresponding local and remote resource templates (CloudFormation, Google Deployment Manager, etc.).

Right now we cannot use CloudFormations capabilities here since they would introduce a breaking change and would tie the implementation to a specific provider (therefore we would need > two plugins (one general `Plan`, and a `Plan` plugin for the respective provider (such as `AwsPlan`, `GooglePlan`)).

**Comment by horike37** [comment]
what benefit does the command have?

**Comment by pmuens** [comment]
@horike37 thanks for jumping in 👍

Good question! You could see what infrastructure changes would be applied w/o actual deploying. It's basically similar to Terraforms plan command: https://www.terraform.io/docs/commands/plan.html

**Comment by RafalWilinski** [comment]
Many people, including myself, commit many mistakes in `serverless.yml` file (e.g. Arn instead of Name or string instead of object)

Example use case:
Assume a team member does a change to `serverless.yml` file. CI runs `serverless plan` and outputs CFN JSON Diff as a comment in PR. This way, code reviewer can validate whether created `serverless.yml` file is correct and does what creator wanted to achieve.

**Comment by pmuens** [comment]
Great good feedback! Thanks @RafalWilinski 👍

**Comment by horike37** [comment]
@pmuens @RafalWilinski 
That makes sense!
It would be great if let users know whether serverless.yml syntax is correct by `serverless plan` before deploying.

**Comment by eahefnawy** [comment]
👎 I know the value here is to provide users some feedback on their config to make sure everything is ready for deployment. But why can't this feedback come during deployment? So if there's something invalid, you'd get an error. Imo adding an additional step before deployment is unnecessarily bad DX.

If this is about seeing how your config or CF would look like before deployment, imo `sls package` is good enough for that. There's also the `print` command in #4169 which could also help here.

**Comment by pmuens** [comment]
> I know the value here is to provide users some feedback on their config to make sure everything is ready for deployment. But why can't this feedback come during deployment? So if there's something invalid, you'd get an error. Imo adding an additional step before deployment is unnecessarily bad DX.

> If this is about seeing how your config or CF would look like before deployment, imo sls package is good enough for that. There's also the print command in #4169 which could also help here.

The main idea here is to see what infrastructure changes would be applied before actually applying them. This is especially helpful if you work on a production environment with a larger team since you won't overwrite anything by accident and can see what has changed in the meantime.

**Comment by nicka** [comment]
This one is still working https://github.com/nicka/serverless-plugin-diff. However I think "plan" should be focosed around CloudFormation Change Sets.

**Comment by kbariotis** [comment]
The PR example that @RafalWilinski uses, seem to me that it's the same as looking the actual diff of the `serverless.yml` file. What would be the benefit of seeing the diff of the CloudFormation JSON file?

**Comment by pmuens** [comment]
> This one is still working https://github.com/nicka/serverless-plugin-diff. However I think "plan" should be focosed around CloudFormation Change Sets.

Oh, yes! That's a great plugin. Thanks for linking @nicka 👍. Smth. like this could be used to make it cloud provider independent.

**Comment by kbariotis** [comment]
> This command is helpful when working with a larger team and you have no idea how the current status of the deployment looks like since many developers could've deployed something in the meantime.

> Furthermore it could be beneficial to see what exactly will change before applying the changes (e.g. other plugins might change the CloudFormation template as well, you want to see what will be destroyed, etc.).

Ok, that makes more sense. Then its essential to compare the CloudFormation JSONs since the deployed one is the absolute source of truth.

**Comment by dev-head** [comment]
As a new user this was the first feature I looked for which wasn't there. It's a good habit to allow users to see what will be changing before actually changing it. For example ```--dry-run``` is used on a number of projects and is intended to provide verification that what I told the program to do is what the program is going to do. Without this step, this tool increases the risk of something dangerous happening with your deployment. 

I fully support OP in validating this use case should be supported.

**Comment by kbariotis** [comment]
@pmuens @RafalWilinski do you think a simple CloudFormation JSON Diff will work for this? Would the diff be sufficient enough to make conclusions on whether the change is good or was intended or anything else?

**Comment by RafalWilinski** [comment]
I think that JSON Diff is totally sufficient.

**Comment by pmuens** [comment]
Thanks for the feedback @dev-head 👍

@kbariotis I agree with @RafalWilinski 🔝. I think that a JSON diff is the easiest implementation (@nicka already implemented the raw logic for JSON diffing in his plugin).

We could extend this later on if we need more functionality...

**Comment by kbariotis** [comment]
Is anyone currently working on this? I would be happy to get my hands on it.

**Comment by pmuens** [comment]
> Is anyone currently working on this? I would be happy to get my hands on it.

Nice @kbariotis 👍. Right now nobody is working on this as far as I know. I'll change the label to `in-progress`.

**Comment by RafalWilinski** [comment]
I think this feature might pave a way for another feature which might make deployments faster.

My idea is to change the way `serverless deploy` function works. 

Right now, `deploy` rebuilds Cloudformation template and updates stack which takes the most time, no matter if changes were made in `serverless.yml`. My suggestion is to check whether `serverless plan` returns any changes and if it doesn't, `serverless deploy` switches to `serverless deploy function` foreach function which has changed. Following pseudocode might illustrate that in a better way:

```js
if (serverless.plan.result === null || !this.options['force']) { // serverless.yml is up to date with remote state
    foreach f in functions {
       if (f.remoteHash !== f.localhash) { // deployed code is outdated 
           serverless deploy function -f f
       }
    }
} else {
    serverless deploy // perform full deploy with CloudFormation template update
}
```

What do you think? @pmuens @eahefnawy

**Comment by HyperBrain** [comment]
@RafalWilinski I think this will break plugins that hook into the deployment. Plugins might do changes to the generated template in the deploy lifecycle that will be messed up by such a change.

Additionally, function deploy is only a half-way deployment which currently bypasses all CF control and uses the REST API to update the function code. So functions deployed with `deploy function` are not tracked in any way and a stack rollback will revert them and lead to unpredictable results. That's also the reason why `deploy function` MUST ONLY be used for debug deployments right now.
The single function deployment has to be changed to a real CF deployment first (maybe by using CF change sets), to have it work correctly. => Again, plugins rely on a CF template available that reflects the state that will be deployed.

For now, I think it would be a very bad idea to mix up the two things and change any functional behavior of deploy, that is currently given as guarantee for all plugins. Such a change must be absolutely non-breaking.

**Comment by HyperBrain** [comment]
See also my comment here: https://github.com/serverless/serverless/issues/4269#issuecomment-329752667

**Comment by RafalWilinski** [comment]
Reasonable arguments, thanks for analysis.

**Comment by kbariotis** [comment]
@pmuens So here's what im thinking of implementing this

* create two plugins, a general Plan that will emit an event and an AWS specific plugin that will do the actually diff with the AWS provider.
* the plan implementation will be done by first compiling the current serverless file and creating a package and fetching the package template from AWS
* once those two are in place, I will do a diff (not sure how yet, suggestions are welcomed) between them and show the results on the terminal

Sounds good?

**Comment by pmuens** [comment]
Thanks for taking the initiative @kbariotis 👍

>create two plugins, a general Plan that will emit an event and an AWS specific plugin that will do the actually diff with the AWS provider.
> the plan implementation will be done by first compiling the current serverless file and creating a package and fetching the package template from AWS
> once those two are in place, I will do a diff (not sure how yet, suggestions are welcomed) between them and show the results on the terminal

That's sounds good. So in summary you'll create a `Plan` plugin which is simply a "skeleton plugin" which provides the lifecycles and the commands (similar to our [`Deploy` plugin](https://github.com/serverless/serverless/blob/master/lib/plugins/deploy/deploy.js)). And then you implement a `AwsPlan` plugin which will implement the actual logic (maybe re-using logic from the `json-diff` plugin from above).

I'd say that we could implement the actual logic (in the `AwsPlan` plugin) in an AWS dependent way (write all the logic in that plugin) and don't need to overcomplicate it right now so that it's easy for other providers to integrate with that. AFAIK the only other plugin which uses a deployment manager (like CloudFormation) behind the scenes is the Google plugin.

IMHO We could refactor and extend this later on.

Thanks for jumping in here 💪 💯.

**Comment by nicka** [comment]
For me, a Plan plugin on top of AWS should use CloudFormation changesets, this would already give you a "true" based on what Cloudformation is planning to change during a deployment. The diff plugin is already better than nothing... But it the topic is a Plan plugin, CF changesets seems to better fit this goal.

**Comment by pmuens** [comment]
Thanks for the feedback @nicka 👍

Yes, I agree. Changesets are nice! Is its possible to use changesets optionally or do I need to go all-in. I played around with changesets when I was looking into SAM but it looked like you need to go all-in with your CloudFormation deployments which would be could / would (?!) be a breaking change in Serverless v1.

**Comment by HyperBrain** [comment]
@nicka @pmuens In general, working with changesets make the most sense for me, for the "manual" deployments like `deploy function`, but not in any other area of Serverless, because it will break all plugins that act in the deployment phase - additionally a changeset expresses a _change_ which is exactly the case in this kind of deployment.

For the plan plugin I'd rather go for downloading the current _original_ CF template that is available with the **getTemplate()** REST API function. It does not take long and you just jave to fetch the difference between the local template (available after the package phase) and the downloaded one. I use the function frequently in the alias plugin and it does not add a big delay - the download is really fast.
I'm even quite sure that it would only be a few lines of code doing the compare with some of lodash's functions.
This fetch of the deployed CF template could even be put in a central location like `pligins/aws/lib` and `function deploy` could use it too, to get it CF integrated.

**Comment by nicka** [comment]
@pmuens I believe that change sets are optional and still allow for updating stacks directly (needs to be confirmed)

@HyperBrain Not sure if I follow you correctly, but this sounds like https://github.com/nicka/serverless-plugin-diff.

Personally, I would like the following:

1. `serverless plan --name foo`, which packages the service, generates the template, uploads everything and creates a new changeset.
1. `serverless plan review --name foo`, which outputs the changes between the current state and new state.
1. `serverless plan execute --name foo`, executes the changeset and shows the "normal" deployment outputs.
1. `serverless plan cancel --name foo`, to remove a changeset.

This will probably conflict with the deployment artifacts and rollbacks 😊

**Comment by kbariotis** [comment]
Allright! I stumbled upon this interesting caveat and I wanted to ask your opinion. Here's an example of a diff output from one of my projects:

```
{
   Resources: {
-    InstallLambdaVersionH61J5TwyNcAPPhTdVFG8JYPtqozY7zHo7mUvVlhNzU: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "InstallLambdaFunction"
-        }
-        CodeSha256: "H61J5TwyNcAP+PhTdVFG8JYPtqozY7zHo7mUvVlhNzU="
-      }
-    }
+    InstallLambdaVersionIR0Xa0oOSgD1HRTXalF6S687HDzyWTPuCjxQDgveYHY: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "InstallLambdaFunction"
+        }
+        CodeSha256: "IR0Xa0oOSgD1HRTXalF6S687HDzyWTPuCjxQDgveYHY="
+      }
+    }
     InstallLambdaFunction: {
       Properties: {
         Code: {
-          S3Key: "serverless/janitr/develop/1507140902412-2017-10-04T18:15:02.412Z/janitr.zip"
+          S3Key: "serverless/janitr/develop/1507320787025-2017-10-06T20:13:07.025Z/janitr.zip"
         }
       }
     }
   }
   Outputs: {
     InstallLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "InstallLambdaVersionH61J5TwyNcAPPhTdVFG8JYPtqozY7zHo7mUvVlhNzU"
+        Ref: "InstallLambdaVersionIR0Xa0oOSgD1HRTXalF6S687HDzyWTPuCjxQDgveYHY"
       }
     }
   }
 }
```

In the above example there aren't really usefull information as CF changes some hashes and the S3 bucket's paths. What would be a possible solution to overcome this? Or is it ok to leave it like this?

**Comment by kbariotis** [comment]
@pmuens is this issue still on? :)

**Comment by dougmoscrop** [comment]
This is a warning to anyone who attempts to implement this; CloudFormation has really bad supports for nested stacks; many Serverless people use nested stacks to support larger services. CloudFormation will *always* return detected-changes on a nested stack.  They expect you to do a complex userland diff.

I make use of change sets in my bootstrap plugin (https://github.com/dougmoscrop/serverless-plugin-bootstrap) which currently suffers if you put nested stacks in it. I plan to implement this `recursive-stack-diff` at some point, and will try to make it a node module itself rather than internal to my plugin, in case it's useful to others.

**Comment by IamGabrielWu** [comment]
How is it now ? Do we have a plan for serverless yet ？

**Comment by pmuens** [comment]
Closing this issue since this is not a feature we're looking for right now. Additionally it would likely introduce breaking changes due to our lifecycle-based plugin architecture.

**Comment by dougmoscrop** [comment]
I am |_| this close to releasing a library that would make this a lot easier; I think putting it in core would be most likely breaking, yeah. I'll post here when I do release for more investigation.

**Comment by simlu** [comment]
Come to love the "terraform plan" command, so would really love to see this!

**Comment by drc-nkovalenko** [comment]
This is closed so I am assuming my question of "Is this still being considered or in the works?" is already answered but I will ask it again. Is this still being considered or in the works?

Coming from Terraform, looking for functionality like -plan to plan out in our prod account before deploying.
