### ISSUE TITLE
Local Plugin Development

### ISSUE THREAD

**Issue by patrickheeney** [serverless/serverless#4180]
# This is a Bug Report / Feature Proposal

## Description

Right now, the process to developing a local plugin seems to center around developing a module inside `.serverless_plugins`. This is not ideal because its a hidden dot-folder, gets deleted occasionally while testing, doesn't work with existing folder structures. 

It is the last one that is my pain point. I have yarn workspace repo with some packages and I either have to clone into the `.serverless_plugins` and develop within there, symlink (issues with nested dependencies), or run a script to copy into it. 

Here is what I tried (apparently plugins can't use variables?):

```
plugins: ${file(./config.js)}

module.exports = () => return [ path.resolve('../../../../module') ];
```

I also tried using relative path (doesn't work due to execution context):

```
plugins:
  - ../../../../module
```

However, if you trace where the code is executed from you can nest it `../../../../../` 5 times and it seems to work. 

Reaching out to see if there is any concrete plans for this or what options I could look into? I looked into `path.resolve()` but that seems to break plugins from `node_modules`. Maybe a new config entry like `pluginServicePaths` to add another directory to `module.paths`?

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by kbariotis** [comment]
So what I do when developing a plugin, is having a separate folder with `serverless.yml` and a `package.json` that contains a dependency using [a local path](https://docs.npmjs.com/files/package.json#local-paths) pointing to my plugin folder. NPM@5 actually creates symlinks when a dependency points to the local file system, so when I do changes to the plugin, it automatically changes to the folder with serverless.

Would that work for you @patrickheeney ?

**Comment by patrickheeney** [comment]
@kbariotis Sort of, but I don't know that it is an ideal solution to the problem. In this case I would have to duplicate the `serverless.yml`, `package.json` and errors that can come up with circular dependencies with symlinks. This one particular plugin is meant for internal use and may never be a public package. Ideally it could reside along with the rest of the code since it can't be used without the plugin.

**Comment by kbariotis** [comment]
Having a plugin that is only meant to be used with the current serverless.yml makes sense, though you could put the separate folder I mentioned in my previous comment in the same folder and have it install through npm.

That would be a great feature imo. I believe Serverless should search for plugins on a folder instead of just looking at `node_modules` folder.

**Comment by pmuens** [comment]
Closing since this is a rather old issue and there were some discussions in the issue thread. Furthermore we have another issue which is focused on documentation improvements for plugin development.
