### ISSUE TITLE
Unpublish from platform.serverless.com

### ISSUE THREAD

**Issue by dschep** [serverless/serverless#4187]
# This is a Bug Report

## Description
If you deploy a service after logging into platform.serverless.com it also automatically publishes your service there (I have since found the `service.publish` option and set it to `false`). However it isn't deleted when you `sls remove` and there's no way to remove it as far as I can tell.

For bug reports:
* What went wrong? `sls remove` didn't remove the service from [platform.serverless.com](https://platform.serverless.com)
* What did you expect should have happened? I expected it to be removed or at least that it be removable in some way.
* What was the config you used? Can't share, but default `sls create -t aws-nodejs` template features the same problem (assuming your `.serverlessrc` has [platform.serverless.com](https://platform.serverless.com) credentials in it.)
* What stacktrace or error message from your provider did you see? N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.21
* ***Operating System***: Ubuntu Linux
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by nikgraf** [comment]
Hi Daniel,

From today on you can remove a service from the Serverless Platform via the user interface. This will only remove it from the Serverless Platform. You service will continue to be functional. To remove it first click on settings of your service and then delete as seen in the screenshots.

<img width="804" alt="screen shot 2017-09-06 at 12 13 03" src="https://user-images.githubusercontent.com/223045/30107278-868d00c6-92fe-11e7-8dc9-4969d803bc1c.png">
<img width="763" alt="screen shot 2017-09-06 at 12 13 35" src="https://user-images.githubusercontent.com/223045/30107279-868d32ee-92fe-11e7-95fd-59e230255a10.png">

As a next step we are going to implement archiving a service whenever you run `sls remove`.

Let me know if you have any question :)

**Comment by dschep** [comment]
Awesome. Thanks @nikgraf.
