### ISSUE TITLE
Add Node.js v8.x to Travis and AppVeyor config files

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4191]
# This is a Feature Proposal

## Description

Node.js v8.x is the next LTS release (see [here](https://github.com/nodejs/LTS#nodejs-release-working-group) for the schedule) and starts in October 2017.

We should update our Travis and AppVeyor config files so that Node.js 8.x replaces the current v6.2 setup. However v6.2 should still run the unit tests.

**Comment by horike37** [comment]
This has been already done.
