### ISSUE TITLE
Region Selection Error

### ISSUE THREAD

**Issue by himadriganguly** [serverless/serverless#4201]
I am changing the region to region: us-west-2 but still while deploying to AWS Lambda, it is deploying it to us-east-1. I am using Serverless v1.21.0.

**Comment by eahefnawy** [comment]
how are you changing the region?

**Comment by himadriganguly** [comment]
In the serverless.yml file.

**Comment by eahefnawy** [comment]
could you share your config file?

**Comment by himadriganguly** [comment]
Sorry just checked i made a mistake. I missed the tab before the stage and region. Really sorry for my mistake. Please don't mind.
