### ISSUE TITLE
Module initialization error

### ISSUE THREAD

**Issue by himadriganguly** [serverless/serverless#4209]
I am using **virtualenv** and **serverless-python-requirements** for my Python deployment in AWS Lambda using serverless framework. But after upload when I am calling the function it is giving “module initialization error: [Errno 22] Invalid argument” error.

Here is my serverless.yml file [https://gist.github.com/himadriganguly/f9571c09a3c01c79ebf920034f5e5e55](https://gist.github.com/himadriganguly/f9571c09a3c01c79ebf920034f5e5e55)

I have also added import unzip_requirements to the top of my handler's .py file

Here is the list the file contents of the zip serverless uploads

```
-SERVICENAME
  - node_modules
  - venv
  - handler.py
  - package.json
  - requirements.py
  - unzip_requirements.py
  - .requirements.zip
```

And following is the details of the requirements.txt

```
boto3==1.4.7
botocore==1.7.3
docutils==0.14
jmespath==0.9.3
python-dateutil==2.6.1
s3transfer==0.1.11
six==1.10.0
unicodecsv==0.14.1
xlrd==1.1.0
```

**Comment by pmuens** [comment]
Hey @himadriganguly thanks for opening :+1:

It looks like this is related to https://github.com/serverless/serverless/issues/4182 which was fixed yesterday. We'll do a patch release the upcoming hours which should fix this problem!

**Comment by himadriganguly** [comment]
@pmuens thanks for the reply. Waiting for the release. Struggling with it for two days. :smile:

**Comment by pmuens** [comment]
@himadriganguly we've just published the patch release `v1.21.1` (see: https://github.com/serverless/serverless/releases/tag/v1.21.1). Should be out in a couple of minutes...

**Comment by himadriganguly** [comment]
Yes, it is fixed now. Thanks to all the members of Serverless framework team for their good work. Wish you all the best. Take care. :+1:

**Comment by pmuens** [comment]
> Yes, it is fixed now. Thanks to all the members of Serverless framework team for their good work. Wish you all the best. Take care. 👍

Great! Thanks for confirming @himadriganguly 👍

Thanks for using Serverless and the kind words! Really appreciate that 💯 💪
