### ISSUE TITLE
Regression - v0.0.15 swallows errors in resources-cf.json on resources deploy

### ISSUE THREAD

**Issue by thedevkit** [serverless/serverless#421]
There seems to be a regression in v0.0.15 where errors in your CloudFormation template may be swallowed up and serverless outputs success when in fact an error occurred. 

Output in v0.0.15:

>$ serverless resources deploy
Serverless: Which stage are you deploying to: 
  > 1) development
    2) staging
    3) production
Serverless: Which region are you deploying to: 
  > us-east-1
Serverless: Deploying resources to stage  "development" and region "us-east-1" via Cloudformation.  This could take a while depending on how many resources you are updating...  
Serverless: Resource Deployer:  Successfully deployed development resources to us-east-1

Output in v0.0.13:

>$ serverless resources deploy -s development -r us-east-1
Serverless: Deploying resources to stage  "development" and region "us-east-1" via Cloudformation.  This could take a while depending on how many resources you are updating...  
Serverless: | { [ValidationError: Template format error: Every Condition member must be a string.]
  cause: 
   { [ValidationError: Template format error: Every Condition member must be a string.]
     message: 'Template format error: Every Condition member must be a string.',
     code: 'ValidationError',
     time: Tue Dec 22 2015 17:08:11 GMT-0800 (PST),
     requestId: 'a26da202-a911-11e5-96f3-6de4ce48f407',
     statusCode: 400,
     retryable: false,
     retryDelay: 30 },
  isOperational: true,
  code: 'ValidationError',
  time: Tue Dec 22 2015 17:08:11 GMT-0800 (PST),
  requestId: 'a26da202-a911-11e5-96f3-6de4ce48f407',
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }

**Comment by thedevkit** [comment]
[resources-cf.json.zip](https://github.com/serverless/serverless/files/70380/resources-cf.json.zip)

**Comment by thedevkit** [comment]
[resources-cf.json.zip](https://github.com/serverless/serverless/files/70384/resources-cf.json.zip)

**Comment by thedevkit** [comment]
[resources-cf.json.zip](https://github.com/serverless/serverless/files/70386/resources-cf.json.zip)

**Comment by eahefnawy** [comment]
Thanks for reporting. Was a tiny issues in the promise chain... now it's fixed :wink:

**Comment by jagthedrummer** [comment]
I'm still seeing this issue in the latest release.

**Comment by jagthedrummer** [comment]
Oops, the latest release is the same one mentioned in the issue (0.0.15). I'm guessing it's fixed in the master branch and will be available in the next release.
