### ISSUE TITLE
Local HTTP server for a python project?

### ISSUE THREAD

**Issue by prakashraman** [serverless/serverless#4222]
I am playing around with serverless and AWS Lambda. The main point of discussion is how easy it is to test the HTTP endpoints locally.

Is there a way to do this currently?

**Comment by RafalWilinski** [comment]
Thanks for asking a question.

I think it's possible. You can use `serverless invoke local -f <function-name>` to run your python function locally but that's far from perfect.

For Node.js projects, I use https://github.com/dherault/serverless-offline which works very well. Digging through issues I found a fork which supports Python: https://github.com/dsvictor94/serverless-offline but I haven't tested it yet.

You simply need to add
```yml
plugins:
  - serverless-offline
```
to your serverless.yml file and run `serverless offline`.

Also, AFAIK Serverless team is working on [Emulator](https://github.com/serverless/emulator) which should emulate your API behavior in a local environment but I'm not sure if it works for Python. @pmuens?

**Comment by prakashraman** [comment]
Thanks for the quick reply!

`servlessless invoke local -f <function-name>` is an option. Although would need to test the HTTP endpoints.

Shall take a look the at https://github.com/dsvictor94/serverless-offline

Although - I started writing my own plugin to work with Python. Shall let you know when its done!

thanks! :)

**Comment by pmuens** [comment]
Thanks for opening @prakashraman and thanks for helping out @RafalWilinski 👍

For Python support the bestsellers solution right now is to use one of the offline plugins.

However we're also working on ways to improve our `Serverless run` command which will provide a fully fledged local dev experience without the need to install and setup plugins beforehand.
