### ISSUE TITLE
Receive the event body to be in a dictionary for an api endpoint

### ISSUE THREAD

**Issue by prakashraman** [serverless/serverless#4227]
I am using Lambda and the API Gateway. I am able to read the GET parameters via

`event["queryStringParameters"]` 

it returns a dictionary. Although the event["body"] of the POST http request looks like this

`
"body": "------WebKitFormBoundary8e5yg3kFu3P2MGQo\r\nContent-Disposition: form-data; name=\"sex\"\r\n\r\nmale\r\n------WebKitFormBoundary8e5yg3kFu3P2MGQo--\r\n",
`
when Content-Disposition: form-data
and is 
`
"body": "name=prakashraman",
`
when the "content-type": "application/x-www-form-urlencoded",

How can I have the body key hold a DICTIONARY ? 

I read that I can mention the "template mapping" but I would then need to mention it for every API ?

**Comment by horike37** [comment]
Thank you for opening this issue @prakashraman!

I guess you use `LAMBDA-PROXY` integration type.
Could you switch to `LAMBDA` integration type and try again?

This way you should be able to use the request templates.

The `LAMDBA-PROXY` integration type is a pretty minimal setup where most of the heavy lifting needs to be done in application code.

**Comment by prakashraman** [comment]
Thanks!

**Comment by prakashraman** [comment]
Ah damn. In the above comment of mine, the "\" have been removed.

**Comment by prakashraman** [comment]
My bad! It is working fine. Although do I need to mention
`
integration: lamdba
` 
to every function in serverless.yml

Is there a way I set set that as the default type for all http-event-functions?

**Comment by pmuens** [comment]
@horike37 thanks for helping and @prakashraman thanks for confirming 👍

> Is there a way I set set that as the default type for all http-event-functions?

Yes, you need to set this on a per-function level. However you could use Serverless Variables to control this "globally".

so you would do smth like:

```yml
custom
  integration: LAMBDA

functions:
  foo:
    events:
      - http:
          path: foo
          method: GET
          Integration: ${self:custom.integration}
# ... other functions
```

And everytime you change the value in the `custom` section all your integrations in the functions  will be changed.

I'll close this issue for now since the main issue was resolved. Feel free to comment / re-open.

**Comment by prakashraman** [comment]
Great @horike37 and @pmuens looks good :) Love the framework BTW! Shall keep you guys updated of how things are going. We are building an extremely large system based on Serverless! Hence all the questions :)

Yes - please do close the issue.

Thanks

**Comment by pmuens** [comment]
> Great @horike37 and @pmuens looks good :) Love the framework BTW! Shall keep you guys updated of how things are going. We are building an extremely large system based on Serverless! Hence all the questions :)

Great! Thanks for confirming and the kind words @prakashraman 👍:pray:

BTW: Feel free to ping us if you want to write a blog post about the system on our [Serverless Blog](http://blog.serverless.com)!
