### ISSUE TITLE
application/json not being converted into a dictionary

### ISSUE THREAD

**Issue by prakashraman** [serverless/serverless#4229]
I have created an POST API Endpoint + Lambda function. Although when I send 

`"content-type": "application/json"`

with raw body as

`
{
	"name": "Prakash Raman"
}
`

I get the following in the "event" object.

`
"input": {
        "body": "{\n\t\"name\": \"Prakash Raman\"\n}",
`

The documentation says 

> Serverless ships with the following default request templates you can use out of the box:
> 
> application/json
> application/x-www-form-urlencoded

Was wondering what I am doing wrong.

Thanks!

**Comment by horike37** [comment]
Hey @prakashraman.
This cause would the same as #4227. Could you switch the integration type?

**Comment by prakashraman** [comment]
Closing the issue. #4227 has provided the information. Thanks!

**Comment by pmuens** [comment]
> Closing the issue. #4227 has provided the information. Thanks!

Thanks @prakashraman 👍. Glad to hear that the issue has been resolved.
