### ISSUE TITLE
list parameter for stage, region, module and function

### ISSUE THREAD

**Issue by ringods** [serverless/serverless#423]
The documentation lists a number of parameters:

https://serverless.readme.io/docs/commands-overview

Like `env`, it would be handy to have `list` functionality for the following types too:
* `stage`
* `region`
* `module`
* `function`

**Comment by eahefnawy** [comment]
Interesting! Thanks for suggesting. There are tons of other actions we want to implement but we're just short in time :unamused:

**Comment by ialmetwally** [comment]
Is there any other way to get the list of functions/endpoints? 
I'm building a deployment server using jenkins and I want to allow users to choose which functions/endpoints to deploy.

**Comment by eahefnawy** [comment]
@ialmetwally we're working on a big internal refactor for our API that should make it easy for you to list components, functions, endpoints...etc. For now you can check our [API References in the docs](http://docs.serverless.com/docs/serverless)

**Comment by ialmetwally** [comment]
@eahefnawy thanks for the fast response but I don't see how is it possible to list all the functions using the API.

Anyway I'm waiting for this feature and as a workaround solution I just use this:
find  "component_path" -name 's-function.json' -print0 | xargs -0 -n1 dirname | sort --unique

which will list paths for all functions

**Comment by flomotlik** [comment]
We're planning on better development/debugging integration in the next release that will also allow you to inspect functions and your resources on Lambda easily
