### ISSUE TITLE
Trigger bug in exists cognito user pool.

### ISSUE THREAD

**Issue by xkguq007** [serverless/serverless#4237]
# This is a Feature proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
When I apply trigger to exists user pool like below configs, It ALWAYS create new userpool. Even I set same pool name. I searched thread in forum, but there is no solution.

`
functions:
  cognitoPreSignup:
    handler: serverless/index.cognitoPreSignup
    events:
      - cognitoUserPool:
          pool: postfactorytest_userpool_MOBILEHUB_126797092
          trigger: PreSignUp
`

* If there is additional config how would it look

`
functions:
  cognitoPreSignup:
    handler: serverless/index.cognitoPreSignup
    events:
      - cognitoUserPool:
          arn: <my user pool arn>
          trigger: PreSignUp
`

Similar or dependent issues:
This is the thread what I found in forum.
[https://forum.serverless.com/t/how-to-specify-an-existing-cognito-user-pool-in-servreless-yml/2412]

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.2
* ***Operating System***: ubuntu linux 16.04
* ***Stack Trace***: Nope
* ***Provider Error messages***: Nope

**Comment by pmuens** [comment]
Thanks for opening @xkguq007 👍

Might be related to https://github.com/serverless/serverless/pull/3799

**Comment by xkguq007** [comment]
yep! I resolved!

**Comment by pmuens** [comment]
Thanks for getting back @xkguq007 👍

Could you please provide some information on how you were able to resolve the issue? Thanks in advance!

**Comment by xkguq007** [comment]
Oh, yep.
I used this framework wrong.
Because my userpool was made in AWS Console, not serverless.yml. So, It was not in CloudFormation.
That's why they can't recognize my userpool.

So, just create userpool using serverless.yml, then using Ref: userpoolname, problem solved.
Here's the sample of my userpool

`
CognitoUserPoolPostFactoryUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: ${self:provider.environment.USERPOOL_NAME}
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        AliasAttributes:
          - 'phone_number'
          - 'email'
        AutoVerifiedAttributes:
          - 'phone_number'
          - 'email'
        SmsConfiguration:
          ExternalId: 86c14429-ace2-4e50-a732-404468ad24ec
          SnsCallerArn: 'arn:aws:iam::691233575878:role/service-role/postfactorytest_smsverification_MOBILEHUB_126797092'

    CognitoUserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: ${self:provider.environment.USERPOOL_NAME}-RN
        GenerateSecret: false
        ReadAttributes: 
          - 'phone_number'
          - 'email'
        RefreshTokenValidity: 7
        UserPoolId:
          Ref: CognitoUserPoolPostFactoryUserPool
        WriteAttributes: 
          - 'phone_number'
          - 'email'
`

p.s
There are two resources, one of top is userpool, the other is userpool client for my project.
Now, I changed SmsConfiguration hardcoded to made role using Fn:GetAtt

p.s2
DO NOT SETTING PASSWORD RULE LIKE THIS.
it just test, you can change above code, PasswordPolicy.

;D

**Comment by pmuens** [comment]
Great! Thank you very much for getting back and posting the steps to fix this problem @xkguq007 👍
