### ISSUE TITLE
Add Amazon S3 Transfer Acceleration support

### ISSUE THREAD

**Issue by alexcasalboni** [serverless/serverless#4252]
# This is a Feature Proposal

## Description

The framework could optionally enable S3 Transfer Acceleration and use the s3-accelerate endpoint to upload heavy deployment packages.

* **Use case**: heavy deployment packages or "remote" regions

## Additional Data

Feature announcement/description [here](https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/).

I have tested the transfer speed with the AWS CLI, uploading a 43MB file to us-west-2 from western Europe.

### Without transfer acceleration
```bash
$time aws s3 cp ./my-big-file.zip s3://my-bucket/my-big-file.zip
real	0m33.990s
user	0m2.044s
sys	0m0.608s
(peak: 1.7 MiB/s)
```

### With transfer acceleration
```bash
$time aws s3 cp ./my-big-file.zip s3://my-bucket/my-big-file.zip --endpoint-url http://s3-accelerate.amazonaws.com
real	0m6.867s
user	0m1.303s
sys	0m0.346s
(peak: 10.5 MiB/s)
```

## What's needed?

We'd need to enable transfer acceleration (no CloudFormation support yet).
This is how you do it with the CLI:

```bash
aws s3api put-bucket-accelerate-configuration --bucket bucketname --accelerate-configuration Status=Enabled
```

And then simply append the `--endpoint` option when uploading.

Eventually, it could be a simple plugin, but it sounds simple and useful enough to be an option in the core.

**Comment by alexcasalboni** [comment]
P.s. You can also run a multi-region test, wherever you are in the world :)

http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html

(I got a +9000% improvement for the Sydney region!)

**Comment by alexcasalboni** [comment]
@horike37 not sure if by default is the best for everybody because of additional data transfer costs (around $0.04/GB), but I would personally agree :)

This is also interesting (taken from the [pricing page](https://aws.amazon.com/s3/pricing/)):

> Each time you use Transfer Acceleration to upload an object, we will check whether Transfer Acceleration is likely to be faster than a regular Amazon S3 transfer. If we determine that Transfer Acceleration is not likely to be faster than a regular Amazon S3 transfer of the same object to the same destination AWS region, we will not charge for that use of Transfer Acceleration for that transfer, and may bypass the Transfer Acceleration system for that upload.

**Comment by HyperBrain** [comment]
@alexcasalboni @horike37 If we'd enable the setting by default, there should be a config option (globally?) to turn it of for a whole system.

Example: We build and deploy our projects with CI/CD and it does not really matter if the deployment takes 5 seconds or 30 seconds, but what does matter is, if we generate costs for an "improvement" that we do not need. The size of all project deployments resulting from the CI/CD approach, is quite big, so there will be noticable costs (I'm ignoring the statement of AWS quoted below, because that's not reliable and who knows if it is disabled or not).

So there should be a way to disable the behavior on the server (maybe through an environment variable). Having a switch in the project config is for such a behavior imo not the right place.

**Comment by wenderjean** [comment]
I agree with that proposal once we're fighting a bit with large packages in our project.

@HyperBrain What about It be disable by default and provide an inline option to use.

**Comment by HyperBrain** [comment]
@wenderjean A command line option instead of an environment variable would also be ok, as it can be even set for specific builds. But how would it be named best? `--s3-accel`?

**Comment by horike37** [comment]
What about `--use-s3-acceleration`? it would be a too long word a little bit, but we have the CLI Autocomplete functionality.
I feel this is understandable and well-sounding 😄

**Comment by wenderjean** [comment]
```bash
--s3-accel
--s3 accelerate
```
I think the first one (yours) is a good choice.

**Comment by pmuens** [comment]
Nice discussions 👍

Given the fact that this may increase costs I'd propose to make this opt-in. I'd vote for `--aws-s3-accel` or `--aws-s3-accelerate`.

**Aside:** We just need to prefix this with AWS since this is a provider-dependent CLI option.

**Comment by alexcasalboni** [comment]
+1 for making it opt-in

It's a great feature if your deployment packages are above 10MB or 20MB, or if you really must use remote regions (which you can often workaround during prototyping), or for live demos with terrible WiFi (true story!).

I might have time to work on a PR sometime around late next week, if nobody else wants to jump in earlier :)

**Comment by alexcasalboni** [comment]
@pmuens could you have a look at the PR? I still have a couple of TODOs related to the command line options. And documentation is missing too.

**Comment by pmuens** [comment]
Thanks for taking the time to work on a a PR @alexcasalboni 🎉

We'll take a look into it ASAP 💯:+1:

**Comment by dannolan** [comment]
Would absolutely be keen for this if it's possible and in the pipeline? I'm getting munched on 10MB uploads to S3 capping out at 100KB/S on my side.

**Comment by alexcasalboni** [comment]
@dannolan I can feel your pain :)

My PR is currently blocked for two reasons:

1.  @horike37 raised some doubts about multi-provider and autocomplete support (ping @pmuens)
2. AWS recently announced CloudFormation support for S3 Transfer Acceleration (just in time!), therefore I want to update my code and avoid unnecessary API calls.
