### ISSUE TITLE
Access CLI arguments in YAML

### ISSUE THREAD

**Issue by dscis** [serverless/serverless#4253]
Hello,

I have a question regarding using/accessing CLI arguments in my serverless.yml. I am currently using template literals. More specific I access the provider.stage in my environment variables. And depending on the stage the database connection URI for mongodb changes.

However this requires to set the correct stage in my serverless.yml everytime I am deploying. I am curious whether I can access the CLI argument when I deploy the API like: serverless deploy --stage dev.

Best Regards,
Dscis

**Comment by eahefnawy** [comment]
Yes you can! with `${opt:stage}`. here are the relevant docs:

https://serverless.com/framework/docs/providers/aws/guide/variables/#referencing-cli-options

Hope this helps! 😊

**Comment by dscis** [comment]
Awesome
