### ISSUE TITLE
Deploy local option that allows you to run invoke local without packaging to lambda

### ISSUE THREAD

**Issue by achadee** [serverless/serverless#4277]
I can't seem to run something like this:

`serverless invoke -f ingest_product -l --path data/ingest_product.json `

without running this:

`serverless deploy -v`

to submit changes. 

Which makes dev work very slow, Am I doing it wrong? or is there no option to work purely offline

**Comment by RafalWilinski** [comment]
Hi @achadee,

Right now, there are few options to test your functions locally:
- `serverless invoke local -f ingest_product -l --path data/ingest_product.json` - there's a `local` word just after `invoke`
- [Serverless-offline](https://github.com/dherault/serverless-offline) - this one is great if you'd like to test your HTTP-based functions
- [Emulator by Serverless team](https://github.com/serverless/emulator), works with many providers and supports Python

If you'd like to test your functions on AWS Lambda, not locally, you can use command `serverless deploy function -f ingest_product` - this way only code would be deployed without modifying CloudFormation template. That's much faster than regular deployment.

**Comment by pmuens** [comment]
Hey @achadee thanks for opening and @RafalWilinski thanks for helping out 👍

@RafalWilinski compiled list should answer your question. There are different ways how you could run your code locally. We've just introduced the `serverless run` command which uses the [Emulator](https://github.com/serverless/emulator) and the [Event Gateway](https://github.com/serverless/event-gateway) behind the scenes.

We're currently iterating on this to further improve the local development experience.

**Comment by achadee** [comment]
So for being stupid, but whats the difference between `-l` and the `local` option?

**Comment by pmuens** [comment]
> So for being stupid, but whats the difference between -l and the local option?

Thanks for asking @achadee 👍

`-l` will print out the logs (and is only available for the `invoke` command) --> https://serverless.com/framework/docs/providers/aws/cli-reference/invoke/

`invoke local` is a separate command and emulates a local function invocation --> https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/
