### ISSUE TITLE
Centralize dependency management

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#428]
Each module has its own `package.json` and `node_modules` directory now. In many cases, you would also want a `package.json` in the `plugins` dir and in the root of the project or `back` dir.

This approach is very uncommon and introduces the following issues:

- When doing a fresh checkout of a project (especially when working in teams), it's not easy to install all dependencies of all modules, plugins and sometimes also global dependencies. Obviously, there could be written a command for this, but I don't think this solves the problem of maintainability. This will also become an issue when you want to update all your dependencies to new (minor) versions.

- When creating plugins, you want to be able to do stuff with or based on the Node modules (globally) installed in the project. By spreading all these module roots across the project, modules and plugins won't be able to find each others dependencies. Example issue: https://github.com/serverless/serverless-optimizer-plugin/pull/1/files#r48463508

- Lots of dependencies are needed in multiple modules. This results in a lot of duplication in the working directory while developing. Also a lot of the same steps have to be repeated for each module to install, update or configure dependencies.

Example use case: Let's say I want to build a RESTful API. It would make a lot of sense to create a module for each *resource*, containing all CRUD operations for that resource. A lot of dependencies, like DB access, error handling, logging etc are needed across all resources/modules.

I'm feeling the decentralized approach adds extra unnecessary complexity and confusion. My proposal would be to centralize the dependency management, having a single `package.json` and `node_modules` in the root of the project.

**Comment by jimmyn** [comment]
Totally agree with you +1

**Comment by visualasparagus** [comment]
I kind of agree but that kind of kills the concept of reusable modules, doesn't it? Unless the command to install a new module did some kind of merge of dependencies across all project modules.

**Comment by prestonvanloon** [comment]
:+1:

**Comment by joostfarla** [comment]
@visualasparagus I don't think it kills the concept of reusable modules. We just have to make the installer more clever. To get this working seamlessly, it will definitely affect the way modules are built right now. I think we have to get this thing straight pretty soon as people are already creating modules right now.

**Comment by shortjared** [comment]
> When doing a fresh checkout of a project (especially when working in teams), it's not easy to install all dependencies of all modules, plugins and sometimes also global dependencies.

This in particular is becoming a problem in a rapidly growing project with multiple people working on it. Test suites start breaking, I have to go figure out where I need to run or re-run `npm i` to get dependencies in sync.

@joostfarla Do you know how this would impact wanting different versions of dependencies in different modules?

**Comment by joostfarla** [comment]
@shortjared I agree to what you're saying. Even with convenience commands for updating all these different dependency graphs, it just makes it overcomplex.

Multiple module dependencies with version conflicts are not a problem for NPM, even not in NPMv3. In version 3, your `node_modules` dir is flattened, which means all dependencies are put on the same directory level (which makes sub-dependencies accessible). Only when a version conflict with an existing dependency occurs, it will use the classical nested approach for this single dependency (`node_modules/{package}/node_modules`).

**Comment by joostfarla** [comment]
Recently found out there was already some discussion going on in one of the PRs: https://github.com/serverless/serverless/pull/367#issuecomment-164172581. Because these issues are very similar, I would like to comment on the reasons mentioned in this PR. Hopefully we can work something out soon!

> Plugin & Module Dependency Separation - JAWS used to have 1 package.json for all Module dependencies. This is where Plugin dependencies were going to go too. Since this is standard practice for Node projects, like you pointed out. However, as we realized how powerful plugins were going to be, and how likely a project could use several of them, I decided to change this behavior. The way our Lambda packaging works, it would end up grabbing npm Plugin dependencies and adding them to the deployed Lambdas unless we allowed excluding them. Since Lambda performance is affected by file size, this would be a very bad thing to do. We could offer better Exclusion config, so that authors could specifically target Plugin dependencies they want to exclude. But I want to lessen the config in this project, not increase it. Further, everyone who makes custom packaging Actions will have to deal with the unnecessary burden of excluding the Plugin dependencies as well. Combining Plugin and Module dependencies into a single package.json seemed neat on the surface, but is actually messy.

I believe using the optimizer plugin for packaging should be a standard practice (and should be included and configured by default on project creation). This would automatically deal with excluding unneeded stuff and thus solve most concerns related to large packages and slow cold startups.

> NPM Loading - NPM loading happens by checking for node_module in several parent folders. If we have a package.json just for plugins in the root, when you run your NodeJs Lambda functions locally, they may work, even if they don't have the npm dependency installed in the package.json in their module/back folder. This will result in your Lambda functions being broken when they are deployed and felt like an inconvenient, recurring bug.

From my point of view all dependencies (plugins and module/project dependencies) should all be stored in the root's package.json (the real root, not the `back` dir). I think the current approach will even introduce nasty dependency lookup conflicts rather than making things more flexible. For an example, look at https://github.com/serverless/serverless-optimizer-plugin/pull/1/files#r48463508. The plugin needs to make use of module dependencies and they cannot find each other. In the JAWS framework, we also had lots of dependency issues and confusion due to a similar approach.

> Plugins Folder Offers Designation, Isolation & Clarity - This is neater (to me at least). As the Framework and Plugin system grow more powerful and span programming languages, I believe that keeping plugin logic/dependencies in a separate folder will be much cleaner than cluttering the project root further.

If we can come up with a standard naming convention for Serverless additions / plugin (starting with the `serverless-` prefix, they can easily be recognized in the `node_modules` folder. Other platforms can use their own native package manager with the associated folder layout.

> Convenience Methods Are Coming - This project is going to span multiple programming languages and the ability to mix languages in the same project will come. We are going to rely less on using the individual commands of package managers and instead wrap with convenience methods that will ship with the framework and allow you to manage dependencies across all plugins and modules (and their languages) with single commands. So you won't have to cd into the plugins folder much longer. You will simply serverless plugins search optimize-plugin serverless plugins install optimize-plugin. Or something like that. Our registry is in the works!

My fear is that convenience methods for handling this dependency approach will only increase complexity and introduce magical background stuff which might get people confused.

I’m sorry to keep pushing this, but I’m pretty confident this would take away a lot of annoyance and confusion (at least for me :smile:). Hopefully this will eventually lower the barrier for the citizen developer.

Very curious about your feedback!!

@ac360 @eahefnawy @Nopik @shortjared

**Comment by ac360** [comment]
@joostfarla We just had a long discussion about this in Gitter this morning.  @ryansb is currently working on the Python branch which gives him a different perspective and he had some great points.  Most interesting was this principle he suggested:

```
We should support module-level sharing only (across functions), anything else should use the language packaging
```

Basically, everything people want to put in `back/lib` should be a language-specific module (e.g., npm, pip).  Dependency management would be simplified if your app was simply an `npm` module.  You just require that into your Serverless Modules.  This translates well to the other languages too.  What do you think?

**Comment by joostfarla** [comment]
@ac360 I just scanned this whole discussion. Interesting to read how platforms differ!

What strikes me is that people have different definitions of what is a module. I heard people saying each module is a "microservice", which I think is not quite valid because they should be 100% independent. In my opinion microservices should be different projects in different repositories and should be tested, versioned, released en deployed independently.

For me (at least until now), modules are just a way of grouping functions. Simple example is a RESTful API. It seemed obvious to put each resource in its own module and implement one function per method. Lots of shared code sits in a `back/lib` directory. It would become quite messy to put all resources with all methods in one big module. 

So I guess we might first have to agree on the definition of what is a module and continue the discussion from there? Same goes for plugins I guess!

**Comment by ryansb** [comment]
I think plugins are less important, since if anyone disagrees with a plugin's definition of how big/what a module should be, they can skip the plugin. 

For modules, here's my reasoning that they should only share code via their language packaging

1. Runtime (python2.7, nodejs, java, probably more in the future) is attached at the module level
1. Modules are a grouping of related functionality, whether you want to call that a "grouping" or a "microservice" the point is that they have an enforced consistency of language and an ideological consistency of functionality.
1. The `lib` directory for sharing code is at the module level to make it easy to share code between functions of the same runtime
1. Since modules in the same project can have different runtimes, nothing language-specific should happen above the module level. The alternative is to have a mix of Node, Python, Java, and more at the project level which sounds (to me) like a recipe for confusion.

I think the decision of whether to support a `back/lib/` or /back/modules/lib` directory is less about "what is a module" than it is about "what can we support if we really want to support all languages". If we want to allow that kind of cross-module sharing, we'd have to make the runtime decision project-level, which I'm not against but would require a lot of changes.

**Comment by joostfarla** [comment]
This discussion is being continued in https://github.com/serverless/serverless/issues/460.
