### ISSUE TITLE
How come the production deploy creates a completely new API gateway rather than branching on the dev

### ISSUE THREAD

**Issue by achadee** [serverless/serverless#4290]
My development endpoint looks like this:
`https://pb0hx3d5gi.execute-api.ap-southeast-2.amazonaws.com/dev/get_products`

so I should expect my production endpoint to look like this right:
`https://pb0hx3d5gi.execute-api.ap-southeast-2.amazonaws.com/prod/get_products`

instead it creates a completely new API gateway:
`https://oxwfuestf2.execute-api.ap-southeast-2.amazonaws.com/prod/get_products`

**Comment by HyperBrain** [comment]
Hi @achadee ,
with Serverless, the stages that you deploy are completely independent from each other, so if you deploy with `--stage=dev` and `--stage=prod` you'll end up with separated deployments. There are Lambda functions for dev as well as for prod. The same is true for the APIG APIs. A Serverless stage must not be mistaken as an APIG stage.

However there are means to put the different stages under one API with the SLS stage as path element:
(1) Use a custom domain mapping in APIG, that maps the 2 APIs to 2 different root paths of one domain (e.g. my.domain.com/prod/... and my.domain.com/dev/...)
(2) Use the `serverless-aws-alias` plugin which will let you deploy aliases, where an alias maps to one API stage and each function deployment maps to one aliased function version.

**Comment by achadee** [comment]
My thoughts were along the lines of point(1). Thanks for clarifying

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍

Looks like this questions was answered so I'll close this issue. Feel free to continue the discussion...
