### ISSUE TITLE
Naming conflicts for Lambda functions

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#431]
When having two (or more) modules containing functions with the same name, they get overwritten because the name overlaps. Can we change the name generation by including the module name?

Current naming:
```
{project}-{function}
```

Proposed naming:
```
{project}-{module}-{function}
```

**Comment by prestonvanloon** [comment]
:+1: for this

**Comment by joostfarla** [comment]
Added a PR: https://github.com/serverless/serverless/pull/436

**Comment by visualasparagus** [comment]
This is partially related to #390. I adjusted the issue but only realized the further overwrite issues until later.

+1 on this request

**Comment by cnatis** [comment]
+1 makes sense to include the module in the name since modules are npm packages and there is no one enforcing unique function names across modules.

**Comment by joostfarla** [comment]
Seems to be fixed in `v0.1.0` branch.

**Comment by pmuens** [comment]
Resurrecting it right now. I'm on Serverless 0.4.2 and have the described problem (seems to be a problem again because modules are dropped).
