### ISSUE TITLE
sls plugin fails if plugin is referenced within file but not installed yet

### ISSUE THREAD

**Issue by simplesteph** [serverless/serverless#4316]
# This is a Bug Report

## Description

If I create a template with the following snippet in `serverless.yaml`:
```
plugins:
  - serverless-python-requirements
```

and then do 
```
sls plugin install -n serverless-python-requirements
```

I get 
```

  Serverless Error ---------------------------------------

  Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------

     OS:                     darwin
     Node Version:           8.2.1
     Serverless Version:     1.23.0
```

It seems the sls framework checks for plugin existence even before they can be installed.
I would expect two things:
1) On `sls plugins install -n <name of plugin>`, don't check for anything. Just install the plugin and modify serverless.yaml if need be
2) A command named `sls plugins install` to install all of the missing plugins. 

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Mac OSX latest
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for reporting @simplesteph :smile: This is the related issue of #4259
We have recognized the bug. so we will fix this in the upcoming release.
Currently, if you add plugins array to serverless.yaml in the situation that you have not installed a plugin yet, serverless commands fails.

**Comment by horike37** [comment]
Just closing this issue since the duplication of #4259
Feel free to comment / re-open if there's anything else which needs to be done here.
Thanks  @simplesteph!
