### ISSUE TITLE
serverless invoke local not reading profile in serverless.yml

### ISSUE THREAD

**Issue by jackmusick** [serverless/serverless#4317]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong? 

When running `serverless invoke local`, serverless doesn't respect the profile I have specified in serverless.yml. To confirm this was an issue with serverless reading my profile, I copied my credentials from the named profile to the default. After running `serverless invoke local` again, it worked. Oddly enough, on another project, the profile seems to be working as expected.

Additionally, I'm able to read things such as my SSM variables. It isn't until I change my default profile's credentials to my custom profile's that I'm able to upload to S3.

Lastly, I can run `export AWS_PROFILE=CustomProfile` and then run `serverless invoke local` to get the results I'm expected. I can't set the environment variable in serverless.yml and have it work, however.

* What did you expect should have happened?

My file should have uploaded to S3.
* What was the config you used?

```
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: 'CustomProfile'
  memorySize: 128
  timeout: 15
```

```
[default]
aws_access_key_id=AABBCCDDEEFFGG1111
aws_secret_access_key=asdfasdfasdfasdfasdfasdfasdfasdfasdf
region=us-east-1

[CustomProfile]
aws_access_key_id=AABBCCDDEEFFGG11112222
aws_secret_access_key=asdfasdfasdfasdfasdfasdfasdfasdfasdf333333
region=us-east-1
```
* What stacktrace or error message from your provider did you see?
```
{"message":"Access Denied","code":"AccessDenied","region":null,"time":"2017-09-27T04:11:02.413Z","requestId":"CF84A01DE8EEF54E","extendedRequestId":"oVj+zEoiErjtm8qvJTGYKdAXOY1YktKk+qg8nph25GMAhDaTJ6h+1qOSWtAMpkub3gg/HHF+re0=","statusCode":403,"retryable":false,"retryDelay":77.76290402877812}
```
## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: macOS 10.13

**Comment by taylor-knapp** [comment]
The docs specify that Invoke Local uses the `default` profile in your AWS credentials configuration, but, like @jackmusick I found this to be counterintuitive and lost a few hours troubleshooting why cognito was rejecting my local tests.

I propose that Invoke Local should use the profile set in the serverless config, and if the user wants to create a specific profile to reflect the IAM role itself they can still do so. In this case, it will allow my testing to proceed with more permissions than necessary that I can refine when I deploy via the iamRoleStatements. As I _never_ use the default AWS credentials, this is a confusing paradigm.

Current description of functionality is at the bottom of this page: https://github.com/serverless/serverless/blob/master/docs/providers/aws/cli-reference/invoke-local.md
