### ISSUE TITLE
Can't reference roles in lambda functions in 1.23.0. Works fine in 1.21.1 version.

### ISSUE THREAD

**Issue by michaelr524** [serverless/serverless#4318]
----------------------------------
sls deploy -f sms-service
Serverless: Packaging function: sms-service...
Serverless: Excluding development dependencies...
Serverless: Uploading function: sms-service (869 B)...
Serverless: Successfully deployed function: sms-service
 
  Serverless Error ---------------------------------------
 
  1 validation error detected: Value 'SNSRoleForSMS' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws|aws-us-gov):iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.1
     Serverless Version:     1.23.0
 -------------------------------------

  sms-service:
    handler: src/sms/service.handler
    role: SNSRoleForSMS
    events:
      - http:
          path: "sms"
          method: post
          cors: true
    package:
      include:
        - src/sms/service.js

---------------------------------------

    SNSRoleForSMS:
      Type: AWS::IAM::Role
      Properties:
        RoleName: SNSRoleForSMS
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "CognitoSNSPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action: "sns:publish"
                  Resource: "*"

**Comment by horike37** [comment]
Thank you for opening @michaelr524 😊

You need to specify `ARN` to the `role` section. The more info is the following for you.
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

Could you fix it that using `ARN` and try again? 
If that doesn't work after fixing, Could you share your serverless.yml file? We will look into it based
 on the file 💪

**Comment by povloid** [comment]
After upgrading to 1.23.0 from 1.21.1 version, I have the some problem

**Comment by povloid** [comment]
@horike37, with clear arn string it is work without this problem. The problem has only when we try to set RoleName

**Comment by michaelr524** [comment]
@horike37 
Thanks for the fast reply. 
I understood that I should reference the role using it's ARN instead of it's name.
I used an environment variable for the account-id part, like this:

    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/SNSRoleForSMS

Works great, thank you!

**Comment by horike37** [comment]
Thank you for jumping in it @povloid !
Ok, Could you share serverless.yml which reproducing the problem?
We will take a look into it with the provided setup.

@michaelr524

**Comment by horike37** [comment]
@michaelr524 
Glad to hear that your problem has been resolved 💯

**Comment by michaelr524** [comment]
Just to sum this up:

The docs here mention three ways to assign a role to a function: https://serverless.com/framework/docs/providers/aws/guide/iam#one-custom-iam-role-for-all-functions

In version 1.23.0  this syntax works with `sls deploy` but not with `sls deploy -f..`

```Yaml
role: SNSRoleForSMS
```

The third way also worked with `sls deploy -f..`, BTW:
```Yaml
    role:
      Fn::GetAtt:
        - SNSRoleForSMS
        - Arn
```
Will use this one instead of specifying the ARN, as it's more convenient.

**Comment by michaelr524** [comment]
@RafalWilinski Hi. 
Could you tell why did you close the issue? 
Is this not a bug that you are going to fix?

**Comment by RafalWilinski** [comment]
Oh, sorry, I thought this issue is resolved, reopening.

**Comment by RafalWilinski** [comment]
After re-reading issue and analyzing code a bit, it is clear to me that change introduced by me introduced this regression: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deployFunction/index.js#L101 

Will submit a fix asap.

**Comment by michaelr524** [comment]
Thanks @RafalWilinski !
