### ISSUE TITLE
Allow camelcasing for module and function names

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#432]
Can we make it possible to use camelCasing in the module and function names? Currently they are transformed to the lowercase version, but since Lambda functions are not managed by Cloudformation anymore this shouldn't be a problem, right?

**Comment by Adam-Goldman7** [comment]
+1

**Comment by joostfarla** [comment]
Added a PR: Added a PR: https://github.com/serverless/serverless/pull/437

**Comment by joostfarla** [comment]
Recreated PR on branch `v0.1.0`: https://github.com/serverless/serverless/pull/456

**Comment by joostfarla** [comment]
This is already merged and released :+1:
