### ISSUE TITLE
Add a correct keyword suggestion feature when typo

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4328]
# This is a Feature Proposal

## Description
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

If users make a typo when typing any commands, It would be great if there is a feature which provides supposably a correct keyword suggestion something like this: (would be trigged by hitting enter key)
```
$ serverless deploi
Do you mean "deploy"?
```

I have seen the feature when using other command line tools. I think if that would be introduced to the framework, it would be great and being more helpfully for users.

However, I don't have a detailed plan how to work on this and what libraries to introduce so far.
If introducing, we need to decide these stuff at first.

* If there is additional config how would it look
Turn on it as a default

**Comment by RafalWilinski** [comment]
Great idea @horike37!

I always thought that my shell is so smart that it's proposing autocorrections 🙈 

Quick google search - this might be useful: https://github.com/node-modules/auto-correct

**Comment by TrentBartlem** [comment]
@RafalWilinski Check out https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance for the algorithm
