### ISSUE TITLE
Bluebird promises performance problem

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#4331]
# This is a Bug Report
## Description

Today I was investigating performance issue I observed of `deploy` command: In project I work with `deploy` when run, always stalls for about 6 seconds before real commands are invoked.

I narrowed that this 6 seconds is taken by [`populateObject`](https://github.com/serverless/serverless/blob/fd285d3010592044eaafd8a12a812f8d16e2b265/lib/classes/Variables.js#L43) which resolves variables and creates tons of promises when doing so (in many cases it's just wrappers to confirm to return value contract, as most of the operations are sync).

By further profiling the thing, I found that main cause are not bluebird promises on its own, but `longStackTraces` functionality, which is [hardcoded](https://github.com/serverless/serverless/blob/fd285d3010592044eaafd8a12a812f8d16e2b265/bin/serverless#L13-L15) to be on at all times.

When I manually removed that configuration, those __6 seconds, dropped to 200ms__ (!), so difference is dramatic.

I believe that option as `longStackTraces` should not be hardcoded, as it is now. Generating error stack traces is expensive and should not be done recklessly especially in prod environement.

At best it should be turned on only if `SLS_DEBUG=*` is set.

Let me know your stance on that. I'll be happy to propose a PR If needed.

## Additional Data

* ***Serverless Framework Version you're using***: v1.23
* ***Operating System***: macOS v10.12.6
* ***Node.js***: v8.5

**Comment by HyperBrain** [comment]
@medikoo Great find 👍 . It seems that creating all the backtraces for each and every promise is really counter-productive - especially if you use tons of promises.
For me, the `SLS_DEBUG` approach makes a lot of sense, as stack traces are mostly needed only in that case (we even direct people to rerun commands again with SLS_DEBUG set, if they post issues).

**Comment by HyperBrain** [comment]
Here's the statement in the bluebird API docs that confirms the issue:

> Long stack traces imply a substantial performance penalty, around 4-5x for throughput and 0.5x for latency.

See http://bluebirdjs.com/docs/api/promise.longstacktraces.html

**Comment by RafalWilinski** [comment]
Thanks for bug report and thoughtful analysis @medikoo 👍 

After reading the docs, it seems that in Bluebird, `longStackTraces` are enabled only when using `BLUEBIRD_DEBUG=1` env variable or when specifying `NODE_ENV` to `development` - [source](http://bluebirdjs.com/docs/api/promise.longstacktraces.html). 

In my opinion Serverless should work quite the same - long stack traces should be enabled only if `SLS_DEBUG` is set. Totally agree.

Would you like to submit a PR @medikoo?

**Comment by HyperBrain** [comment]
Very interesting is the performance evaluation reported on the bluebird page (comment):

> Bluebird 3.5.0 without long stack traces, arrSize=100: under 5ms
> Bluebird 3.5.0 without long stack traces, arrSize=1000: around 10ms
> Bluebird 3.5.0 without long stack traces, arrSize=10000: under 20ms
> Bluebird 3.5.0 with long stack traces, arrSize=100: under 15ms, 3x penalty
> Bluebird 3.5.0 with long stack traces, arrSize=1000: around 100ms, 10x penalty
> Bluebird 3.5.0 with long stack traces, arrSize=10000: around 1000ms, 50x penalty

**Comment by medikoo** [comment]
> Would you like to submit a PR @medikoo?

Sure, it's on the way!

**Comment by HyperBrain** [comment]
@medikoo Additionally bluebird should be upgraded to `^3.5.0` in the package.json (currently `^3.4.0` is in there) to make sure the latest version (and thus the latest improvements) are in.

**Comment by medikoo** [comment]
Addressed at #4333
