### ISSUE TITLE
"sls invoke local" gives unhandled exception with missing python version

### ISSUE THREAD

**Issue by candlerb** [serverless/serverless#4332]
# This is a Bug Report

## Description

Reproducing test case under Ubuntu 16.04 with nodejs 6.11.3-1nodesource1 (from deb.nodesource.com) and serverless 1.23.0

serverless.yml

~~~
service: my-service-simple

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1

package:
  exclude:
    - "**"
  include:
    - handler.py

functions:
  hello:
    handler: handler.hello
~~~

handler.py

~~~
def hello(event, context):
    body = {
        "message": "Hello lambda world",
        "input": event
    }

    response = {
        "statusCode": 200,
        "body": str(body),
    }

    return response
~~~

`sls invoke local -f hello` gives the following result:

~~~
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn python3.6 ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
~~~

Unfortunately this is really hard to interpret, especially as I cannot find any file called `event.js` on my system, and it doesn't say what filename corresponds to the ENOENT error.

The underlying problem that the runtime specifies python3.6, but ubuntu 16.04 doesn't have this.  It has `python3.5`, with `python3` available as an alias.

This means you need to do something like this:

~~~
sudo ln -s /usr/bin/python3.5 /usr/bin/python3.6
~~~

but a more helpful error message for this scenario would be good.

(Aside: would be nice if I could tell serverless to use a different python version when running locally)

**Comment by horike37** [comment]
Thank you for the reporting the issue @candlerb 👍 
IMO, it would get better to allow users to use different versions from specified one in serverless.yml.
In nodejs runtime, it works fine with different versions.
