### ISSUE TITLE
 - serverless-webpack error

### ISSUE THREAD

**Issue by anoora17** [serverless/serverless#4335]
Y A M L Exception --------------------------------------

  end of the stream or a document separator is expected 

# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by RafalWilinski** [comment]
Thanks for reporting issue @anoora17.

Could you please provide more details? Like serverless.yml file that you've used. Without that, we're unable to reproduce your issue.

**Comment by anoora17** [comment]
Thanks for responding

This is my code https://github.com/anoora17/serverlessStartwithReactexample
please look at my webpack I am trig to use you documentation

**Comment by HyperBrain** [comment]
@anoora17 Can you execute the `SLS_DEBUG=* serverless deploy --verbose`? With this env var and switch, the error message should contain a complete stack trace and we should be able to see where exactly it happens.

BTW: There is an error in [webpack.conf.js#L7](https://github.com/anoora17/serverlessStartwithReactexample/blob/master/webpack.config.js#L7). The `slsw.lib.entries` must be written _without_ quotes.

**Comment by HyperBrain** [comment]
@anoora17 , any update on this issue? Where you able to resolve it? If not, please provide the information I requested above.
