### ISSUE TITLE
globby.sync = 5 seconds

### ISSUE THREAD

**Issue by mvayngrib** [serverless/serverless#4337]
# This is a Optimization Proposal

* What went wrong?

excludeDevDependencies takes a while (10 seconds) for my project
`globby.sync` takes 5 of those 10 seconds

* What did you expect should have happened?

faster!

suggested change: add node_modules paths to glob pattern
see: https://github.com/serverless/serverless/commit/44a92e1a12dda0479e712dd5d3e1332301a990c7

this takes the globby.sync call down to 0.5 seconds for my project

```js
    const packageJsonPaths = globby.sync([
      '**/package.json',
      '!**/node_modules/**',   // < --------------
    ], {
      cwd: servicePath,
      dot: true,
      silent: true,
      follow: true,
      nosort: true
    });
```

seems like it would require the tests in zipService to be rewritten substantially though

**Comment by horike37** [comment]
Thank you for opening this issue @mvayngrib 👍 
That looks great 💯 I was wondering if it would be possible for you to send PR with the suggested code so that we can test it on our end?

**Comment by pmuens** [comment]
Closing since AFAIK we've fixed this with a PR in the past and it should be included in one of the recenent releases. Feel free to re-open if this is not fixed.
