### ISSUE TITLE
Proposal - Database migrations

### ISSUE THREAD

**Issue by kbariotis** [serverless/serverless#4338]
# This is a Feature Proposal

## Description

This issue is of two tales. First I would like to know how do you handle Database migrations along with a serverless infrastructure.

Second, I wanted to start a discussion on how the Serverless framework can help with DB migrations.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

My serverless config creates a DynamoDB instance. Of course it could be any AWS DB service/instance. My goal is to migrate data and/or DB schema before/after/alongside with the functions deployment.

What are your thoughts?

**Comment by horike37** [comment]
Thank you for opening this issue @kbariotis 👍 
Curious what others who've migrated data and/or DB schema think how this should look like... 
/cc @serverless/vip

**Comment by erikerikson** [comment]
My initial instinct:
Seems out of scope.

**Comment by andymac4182** [comment]
We use DbUp https://dbup.github.io/ for our database migrations. Personally this feels like something that would be best handled by a dedicated framework.

**Comment by RafalWilinski** [comment]
+1 for out of scope. This is very complex and broad topic which should be handled per case.

**Comment by kbariotis** [comment]
Aw Im sorry for that guys. I would be happy to close the issue (or for you to close it) if that's not the right place to discuss it.

**Comment by RafalWilinski** [comment]
No worries @kbariotis. I'd wait until someone from core expresses their opinion.

**Comment by horike37** [comment]
Closing this issue since we couldn't get any answers.
Feel free to reopen if you want to do something :+1:
