### ISSUE TITLE
Proposal: Add ability to override default commands

### ISSUE THREAD

**Issue by austinfrey** [serverless/serverless#4346]
# This is a (Bug Report / Feature Proposal)
Feature Proposal

## Description
If a provider provides a duplicate hook to a default command, the provider hook will be respected and override the default.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

It would be great if we had the ability to override the default CLI commands when adding a provider plugin. Not all providers will package or deploy a function the same way, but would like to maintain the default and familiar `serverless` CLI interface. 

* If there is additional config how would it look

`serverless` would "dedupe" hooks for certain commands and respect the current provider hook over the default. i.e. a provider plugin provides a `package` command with a `createDeploymentArtifacts` hook, `serverless` would only use the hook for the current provider and not run both.

* ***Serverless Framework Version you're using***:
`sls -v` 1.22.0
* ***Operating System***:
Ubuntu

**Comment by horike37** [comment]
Thank you for sending a great proposal @austinfrey 💯 
We are likely to need more feedback from someone else so that we know the necessity of this feature or how to implement.

**Comment by austinfrey** [comment]
@horike37 thanks for the response! I can work on getting more details and information if that would be helpful. What specifics would you be looking for?

**Comment by horike37** [comment]
Thank you for the response @austinfrey :+1: 

> I can work on getting more details and information if that would be helpful.

That's awesome :100: Thanks in advance!

I agree with introducing the ability since that allows plugin developer (seems mainly providers plugin) to get more powerful and highly customizable.
Then I am interested in the following two points.

- How can we implement without any breaking changes(don't affect the existing plugins and providers)
- We would change the code base of the framework, so we need to keep it simple

Let us know if you have any our helps :+1:

**Comment by HyperBrain** [comment]
I have additional points:
* It should work with existing plugins that support all providers (like serverless-webpack)
* It should not prevent plugins that hook into the framework to fail
* With such a diversion there has to be a mechanism for plugins to be ignored for certain providers they do not support

**Comment by austinfrey** [comment]
@horike37 @HyperBrain thanks for the comments! gives me something to work with 👍
