### ISSUE TITLE
Multi-API Deployment or Serverless Solution Deployment

### ISSUE THREAD

**Issue by n8sabes** [serverless/serverless#435]
**SCENARIO**
My current system is divided into an Operational API and a SysAdmin API, both mapped to respective Lambda functions in a larger shared library. Each "side" of the system is secured with different API URLs, API Keys, sub-system security methodologies, etc. The pain point is that I must manage two different Serverless projects for what is one solution and it's moderately tedious moving back and forth between them.

Two ideas that would make life easier for such a public / private API architecture project:

**IDEA 1**
Specify (override) the deployment API Name within the s-module.json and / or s-function.json. Whichever definition is closest to the endpoint wins. This would enable a single project to deploy endpoints across multiple API’s, each of which may be secured differently in AWS.

**IDEA 2**
An Sls Solution Deploy package which would deploy multiple sub-projects simultaneously. This would be similar to Xcode Workspaces or other IDE Solutions with multiple sub-projects.

There may be other strategies to solve this problem that I’ve not considered yet, such a multi-stage management but that seems more messy.

Food for thought.

**Comment by joostfarla** [comment]
@n8sabes the next major version (v0.1) will introduce a new system for handling configuration variables. It looks like this will be eventually possible by overriding configuration variables (like `restApiId`) in each module or function. Discussion on the implementation is here: https://trello.com/c/D5u8g4fb/166-project-variables-module-templates

Ping @ac360 @eahefnawy

**Comment by ac360** [comment]
@n8sabes What about this...

Allow for a `restApiId` property to be specified in `s-function.json` which will override the project's default REST API with the REST API specified in `restApiId`.

I haven't thought this through and as always I fear unintended consequences, but it seems like it could work.  With the new Project Variable feature coming in `v0.1.0`, you could use a variable as the ID and switch it out to be whatever you'd like.  The only inconvenience is that you would have to manually create the REST APIs in API Gateway first in your desired region(s), then copy their IDs and set them as variables within your project.

**Comment by n8sabes** [comment]
Thanks Austen. Two things to consider:

1) `restApiId` should be supported at each level (e.g. Project, Module, and Function), whereas children inherit from the parent, unless they override their parent, resulting in the nearest to the endpoint winning.

2) To handle the case of functions in disparate lineage (different paths) targeting the same `restApiId`, Sls might need to either a) concatenate endpoint definitions from all paths before deployment, or b) prohibit disjointed API definitions, forcing one downline lineage instance of a `restApiId`.

I think this would answer the gap to merge multiple Serverless projects into a single tidy project solution.

**Comment by ac360** [comment]
@n8sabes This is a bit more challenging than I thought, but still doable.  I think I can implement this today in `v0.1.0`.  We'll use REST API names instead of IDs which will allow the creation of the REST API if it does not exist, eliminating the need to create things manually in the API Gateway Dashboard.

**Comment by ac360** [comment]
I tried to implement this for over an hour today.  It's more challenging than I thought.  I ended up throwing away my work since the complexity cost was too big.  I'm going to keep thinking about this, but I also feel there may be other ways to implement a public and private API on the same API Gateway REST API through IAM.  Have you investigated IAM solutions to this issue @n8sabes?  I want this feature, it's a good one.  But it can't diminish the overall developer experience, and there is inevitable complexity that comes with multiple REST APIs.

**Comment by n8sabes** [comment]
@ac360, I've been away for a few days and just catching up on Serverless topics.

Thanks for taking some time to look at this. The simplest things often require the most careful architectural thought process. I think this would add value when you have time to tackle it.

For now, during development, I have one Serverless project using the same endpoint for both client and admin. As a basic security measure, I've implemented an IP whitelist within my Admin Lambda operational router to reject requests from IP's not whitelisted. Before production deployment, I'll plan to split the Serverless project and deploy to different endpoints and add additional security measures. I've considered alternatives, but not fully explored IAM options between API Gateway and Lambda, caller identity, nor certs. What are you thinking and I'd be happy to explore it?

**Comment by flomotlik** [comment]
We're looking into your proposals for the next release of Serverless. I will close this issue for now and open up if we come back to them.
