### ISSUE TITLE
resolveFilePathsFromPatterns takes > 1min

### ISSUE THREAD

**Issue by mvayngrib** [serverless/serverless#4355]
# This is an Optimization opportunity

## Description

resolveFilePathsFromPatterns takes ~67s for my project
if I turn off excludeDevDependencies, it takes 12s

For bug reports:
* What went wrong?

deploy is super slow

* What did you expect should have happened?

faster

* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

i think either serious optimization is needed or a tiered project structure should be recommended, e.g.:

```sh
outer/
  package.json
  node_modules/ # devDependencies
  inner/
    package.json  # dependencies
    serverless.yml
    node_modules/
```

* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: OSX 10.12.6
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by mvayngrib** [comment]
also, it would be cool to adopt the style that `yarn` uses, and time all significant internal operations, and print the times to the screen. It might be painful at first, but it exposes places for optimization!

**Comment by mvayngrib** [comment]
another thought: dependencies/devDependencies don't change that often. If there's a lockfile in the project, then a cache for the resolveFilePathsFromPatterns can be used, and invalidated when a change in the lockfile is detected. Obviously paths not in node_modules will need to be recomputed, but those are the minority

**Comment by mvayngrib** [comment]
another thought: some functions don't have any dependencies, or depend solely on `aws-sdk`. Currently they're still punished with the one two punch of `excludeDevDependencies` + `resolveFilePathsFromPatterns`. Maybe is `exclude` is passed as an empty array, then only `include` can be used, which can speed things up.

**Comment by pmuens** [comment]
Closing since we've released versions which should address this issue.

Feel free to re-open if this is not fixed.
