### ISSUE TITLE
how to resolve  Cannot read property 'then' of undefined ?

### ISSUE THREAD

**Issue by balakrishna222111** [serverless/serverless#4356]
var AWS = require('aws-sdk');
var fs = require('fs');

var s3 = new AWS.S3();

var myBucket = 'dev-tenant-test';

var myKey = "test"
var fileName = './test1.txt'
var fs = require("fs");

exports.uploadFile = function uploadFile() {
    console.log("hitiing in exports.upload file")
    return new Promise(function (resolve, reject) {
        fs.readFile(fileName, function (err, data) {
            console.log("hitting in readFile function")
            if (err) { console.log(err); reject(err); }
            console.log(data.toString('ascii'));
            var params = { Bucket: myBucket, Key: myKey, Body: data };
            resolve(data);
            s3.putObject(params, function (err, data) {
                if (err) {
                    console.log("error while uploading text file ", err);
                    reject(err);
                }
                else {
                    console.log("Successfully uploaded text1 file ");
                    resolve(true);
                }
            });
        });
    });
}

exports.deletetheFile = function deletetheFile(key) {
    var params = { Bucket: myBucket, Key: myKey };
    //deleting the file
    s3.deleteObject(params, function (err, data) {
        return new Promise(function (resolve, reject) {
            if (err) {
                console.log("error due to ", err);
                reject(err)
            }
            else {
                console.log("Successfully deleted");
                resolve(true);
            }
        });
    });
}

exports.readtheFile = function readtheFile(key) {
    //get the file
    var params = { Bucket: myBucket, Key: myKey };
    s3.getObject(params, function (err, data) {
        return new Promise(function (resolve, reject) {
            if (err) {
                console.log(err);
                reject(err);
            }
            else {
                console.log("hitting in getobject")
                console.log(data.toString());
                resolve(true);
            }
        });
    });
}

exports.awscrud =function awscrud(myKey) {
    uploadFile()
        .then(function (r) {
            exports.readtheFile(myKey)
                .then(function (r) {
                    exports.deletetheFile(myKey)
                        .then(function (r) {
                            console.log("Successfully called the aws crud")
                        })
                        .catch(function (e) {
                            console.error("error while deleting the file", e)
                        });
                })
                .catch(function (e) {
                    console.error("error while reading the file", e)
                });
        })
        .catch(function (e) {
            console.error("error while uploading the file", e)
        });

}
// exports.awscrud(myKey)

**Comment by balakrishna222111** [comment]
i hv to call the return promise function in calling method too

**Comment by laardee** [comment]
@balakrishna222111 hi, I presume that you have problems with readtheFile and deletetheFile functions? 

I uncommented the last line `// exports.awscrud(myKey)`, then changed the 
```
exports.awscrud =function awscrud(myKey) {
  uploadFile()
```
to 
```
exports.awscrud = function awscrud(myKey) {
  exports.uploadFile()
```
and removed `resolve(data);` from uploadFile function, because it resolved the promise before file was uploaded to S3 and because of that the read fails in awscrud every second time.

Then I refactored the readtheFile and deletetheFile functions like this:
```
exports.deletetheFile = function deletetheFile(key) {
  //deleting the file
  var params = { Bucket: myBucket, Key: myKey };
  return s3.deleteObject(params).promise()
    .then(function(data) {
      console.log("Successfully deleted");
      return true;
    })
    .catch(function(err) {
      console.log(err);
      return Promise.reject(err);
    });
}

exports.readtheFile = function readtheFile(key) {
  //get the file
  var params = { Bucket: myBucket, Key: myKey };
  return s3.getObject(params).promise()
    .then(function(data){
      console.log("hitting in getobject")
      console.log(data.toString());
      return true;
    })
    .catch(function(err) {
      console.log(err);
      return Promise.reject(err);
    });
}
```
If you are using AWS SDK v2.3.0 or later, it supports promises almost in all modules. You could refactor your code to use that feature.

Anyways, with those changes, I managed to upload a text file (containing "hello world!") to S3, read, and delete it.
Here is the log:
```
hitiing in exports.upload file
hitting in readFile function
hello world!

Successfully uploaded text1 file
hitting in getobject
[object Object]
Successfully deleted
Successfully called the aws crud
```
