### ISSUE TITLE
Dev dep exclusion does not exclude bins

### ISSUE THREAD

**Issue by arichiardi** [serverless/serverless#4359]
# This is a Bug Report

## Description

I am using `lumo-cljs` in my `devDependencies` and expecting it to be completely excluded. However, it seems that my zip still contains the binary file.

```
 unzip -lf .serverless/my.zip  | grep lumo
      543  1980-01-01 00:00   node_modules/.bin/lumo
```

The package correctly [sets](https://github.com/anmonteiro/lumo/blob/master/packages/lumo/package.json#L28) the `"bin"` key in `package.json`

## Additional Data

* ***Serverless Framework Version you're using***: `1.23.0`

**Comment by horike37** [comment]
Thank you for the reporting @arichiardi 👍 
I was able to reproduce that on my end too. It seems that the process for excluding `.bin` doesn't include the one for excluding `devDependencies` in the packaging.

**Comment by daviskoh** [comment]
I created a PR to fix this issue, would love some feedback!

**Comment by arichiardi** [comment]
I can try it out and give you feedback :) Thanks for working on this!
