### ISSUE TITLE
Accessing S3 resources when lambda functions are executed inside a VPC

### ISSUE THREAD

**Issue by sharathm** [serverless/serverless#4362]
# This is a Bug Report
## Description
Consider the following lambda function
```
module.exports.backupDataToS3 = (event, context, callback) => {
	const AWS = require('aws-sdk');
	const S3 = new AWS.S3();
	const allParams = event.Records.map((record) => {
		const fileName =  record.kinesis.partitionKey;
		const fileLocation = process.env.S3_BUCKET_NAME;
		const buf = Buffer.from(record.kinesis.data, 'base64').toString();
		const params = {
			'Body': buf,
			'Bucket': fileLocation,
			'Key': fileName
		};
		return params;
	});
	const allPromises = allParams.map((p) => {
		return S3.putObject(p).promise();
	});

	Promise.all(allPromises)
		.then((results) => {
			callback(null, 'saved ' + results.length + ' records');
		})
		.catch((err) => {
			callback(err);
		});
};
```
It uses `Promise` to backup data coming from a kinesis stream to a pre-defined S3 bucket as per `process.env.S3_BUCKET_NAME`. 
If this lambda were to be run inside a VPC, with the required `iamRoleStatements`, it will timeout. 
```
iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "<insert_bucket_arn_here>" 
```
The reason for this is because a new VPC end point is to be created for accessing s3 resources  as part of the VPC's configuration. 
(https://aws.amazon.com/blogs/aws/new-access-resources-in-a-vpc-from-your-lambda-functions/). Please refer to "Things to Know" section in the linked article. 

I think it would be a good idea to include this information as part of documentation. Please let me know if I am correct in my bug report, and I can send a PR with the updated docs. 
I was not sure if this was a "Bug" in the framework, but flagged it in this way so that documentation can get updated.

## Additional Data

* Serverless Framework: 1.19.0
* Operating System: MacOS High Sierra

**Comment by horike37** [comment]
Thank you for the suggestion @sharathm 💯 
I agree with adding the restriction to a part of the documentation. 

It would better to add it to the section as a note 👍 
https://serverless.com/framework/docs/providers/aws/guide/functions/#vpc-configuration

> I can send a PR with the updated docs

Great 👍 Thanks in advance!
