### ISSUE TITLE
AWS 100 bucket account limit

### ISSUE THREAD

**Issue by achadee** [serverless/serverless#4366]
This isn't an issue for us atm, but maybe something for you guys to think about.

http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

AWS has hard restrictions on the number of buckets you are allowed to have. After that you have to apply to have more. We are planning on developing 100's of lambda apps. Maybe an optional folder structure would be ideal for people with this use case.

**Comment by horike37** [comment]
Thank you for opening this issue @achadee 👍 
We recommend specifying `deploymentBucket` in the case. 
https://serverless.com/framework/docs/providers/aws/guide/deploying/#tips

`deploymentBucket` allows you to specify one bucket which your deployment is stored, and you can reference from multiple services 👍 
Therefore, we don't need to worry about restrictions on the number of buckets.

Closing this issue for now. Feel free re-open if you want to discuss more or have any suggestions!

**Comment by achadee** [comment]
perfect, missed this in the docs!
