### ISSUE TITLE
  Serverless Error ---------------------------------------        An error occurred while provisioning your stack: S3BucketServerlesschatbotdevuploadsyourinitialshere      - serverless-chatbot-dev-uploads-your-initials-here      already exists.

### ISSUE THREAD

**Issue by rachelwu11** [serverless/serverless#4368]
I've got this issue:
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: S3BucketServerlesschatbotdevuploadsyourinitialshere
     - serverless-chatbot-dev-uploads-your-initials-here
     already exists.

Any ideas?

**Comment by RafalWilinski** [comment]
Hi @rachelwu11 

Have you tried renaming your stack and running `serverless deploy` again?

**Comment by rachelwu11** [comment]
Hey @RafalWilinski , @DavidWells he helped me out. If the custom variable was called uploadBucket, then there was a conflict. so i've renamed it to be bucket, and it worked. Thanks a lot. :)
      
     UPLOAD_BUCKET: ${self:custom.bucket
      bucket: ${self:service}-${self:provider.stage}-uploads-xw

**Comment by RafalWilinski** [comment]
Glad to see this resolved, closing ❤️
