### ISSUE TITLE
Warn user if function timeout is set to value bigger than 30 seconds and it's attached to API Gateway

### ISSUE THREAD

**Issue by RafalWilinski** [serverless/serverless#4371]
# This is a Feature Proposal

## Description
While AWS Lambda has max timeout of 300 seconds, API Gateway has only 30. It would be nice if Framework could warn the user that they set timeout to value bigger than 30 but function is attached to Gateway so effective timeout would be 30 seconds.

Similar or dependent issues: https://github.com/serverless/serverless/pull/4348#issuecomment-335456883

**Comment by Toosick** [comment]
👍
