### ISSUE TITLE
Installing serverless-python-requirements leads to error Serverless plugin "serverless-python-requirements" not found

### ISSUE THREAD

**Issue by nabihach** [serverless/serverless#4375]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

I installed serverless using 
`sudo npm install -g serverless --unsafe-perm`
which didn't result in any errors.

But now, whatever I try to do, I get:
`Serverless plugin "serverless-python-requirements" not found`

Even when I try to install serverless-python-requirements using
`sls plugin install -n serverless-python-requirements`
I get
`Serverless plugin "serverless-python-requirements" not found.`

* What did you expect should have happened?
* What was the config you used?
Not sure what this means
* What stacktrace or error message from your provider did you see?
No stacktrace error

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
*

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: linux (ubuntu 16.04)
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by RafalWilinski** [comment]
Thanks for reporting an issue @nabihach!

Could you please share your `serverless.yml` file and `requirements.txt`/`package.json` file?

Also pinging @dschep as he's the main contributor of https://github.com/UnitedIncome/serverless-python-requirements.

**Comment by nabihach** [comment]
Ok so I figured out why this happened.
The plugin was already listed in `serverless.yml`. This is why whatever I did, it threw the error above. I removed the plugin from the file, then ran the plugin installation. It worked.

Please feel free to close this.

**Comment by RafalWilinski** [comment]
Glad to see your problem resolved! 💯
