### ISSUE TITLE
Resource name "ApiGatewayDeployment{randomNumber}" should be "ApiGatewayDeployment"

### ISSUE THREAD

**Issue by jimle-uk** [serverless/serverless#4379]
# This is a Bug Report

## Description
The APIGatewayDeployment resource name has a random number appended which prevents user ability to override ApiGateway::deployment properties.

For bug reports:
* What went wrong?
Trying to override "stageName" for resource "AWS::ApiGateway::Deployment"

* What did you expect should have happened?

Defining the following resource in `serverless.yml` [1] should override the default stage name in the packaged cloudformation template [2]. Instead an additional ApiGateway::Deployment resource is created.

```
// [1] serverless.yml
Resources:
    ApiGatewayDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            StageName: "v1"
```
```
// [2] .serverless/cloudformation-template-update-stack.json
    ...
    "ApiGatewayDeployment": {
        "Type": "AWS::ApiGateway::Deployment",
        "Properties": {
            "RestApiId": {
                "Ref": "ApiGatewayRestApi"
            },
            "StageName": "v1"
        }
    },
    ...
    "ApiGatewayDeployment1507897423790": {
        "Type": "AWS::ApiGateway::Deployment",
        "Properties": {
            "RestApiId": {
                "Ref": "ApiGatewayRestApi"
            },
            "StageName": "dev"
        },
        ...
    }
    ...
```

* What stacktrace or error message from your provider did you see?
None

Similar or dependent issues:
[#4028](https://github.com/serverless/serverless/issues/4028)
[#2233](https://github.com/serverless/serverless/issues/2233)

## Additional Data
Documentation: https://serverless.com/framework/docs/providers/aws/guide/resources/
Tested on `sls@1.23.0` MacOS Sierra 10.12.6 (16G29)

**Comment by horike37** [comment]
Thank you for reporting @jimle-uk :+1: 

Hey, @pmuens Do you know the reason that the random number is added automatically?
I guess that's intentionally by the framework.

**Comment by jimle-uk** [comment]
@horike37 Thanks. I think I found out why in issue #2233.
Coincidently my issue is a dupe of #2233 as well. Apologies, I found the issue through google search where github search failed.

**Comment by pmuens** [comment]
Thanks for opening @jimle-uk and thanks for chiming in @horike37!

Yes, the random number is added automatically because of an issues on AWS end (otherwise the changes are not picked up).
