### ISSUE TITLE
 Override Global VPC configuration in function level to no VPC

### ISSUE THREAD

**Issue by Dmdl** [serverless/serverless#4387]
# Override Global VPC configuration in function level with no VPC

I have defined VPC configurations at the provider level (AWS) and VPC configurations applied to all the functions correctly. Now I want one function to not to have VPC configurations but there is no way to override this in function level. Can this be done with serverless framework?

`provider:`
  `name: aws`
  `runtime: nodejs6.10`
  `profile: mclaim-deploy`
  `vpc:`
      ` securityGroupIds:`
       `  - sg-4566666`
      ` subnetIds:`
       `  - subnet-12222222`
       `  - subnet-85555665`

**Comment by horike37** [comment]
Thank you for opening this issue @Dmdl :+1: 
Currently, Serverless has the functionality what you want :cry: 
However, I think the functionality would be cool. I agree with introducing that into Serverless core.

**Comment by TrentBartlem** [comment]
Perhaps override with null? e.g. :
    
    vpc: ~

**Comment by alyhegazy** [comment]
This works:

```
vpc:
  securityGroupIds: []
  subnetIds: []
```

**Comment by joebernard** [comment]
The config posted by @alyhegazy removes the VPC from my individual function successfully.

**Comment by XaeroDegreaz** [comment]
I concur that the config @alyhegazy posted works initially, but as @contrarianaupong mentioned, subsequent full deployments use the global VPC configuration (strangely).

Also, forcing null with `~` did not work for me.

**Comment by solsglasses** [comment]
👍

**Comment by ferflores** [comment]
same problem, override ignored

**Comment by solsglasses** [comment]
You have to :1: the original post to get the maintainers attention

**Comment by nomanhassan092** [comment]
Has anyone found a solution to this? Having the same problem

**Comment by YannicEl** [comment]
> Has anyone found a solution to this? Having the same problem

https://github.com/serverless/serverless/issues/4387#issuecomment-403909668

**Comment by disbelief** [comment]
This seems like a pretty simple change. I'm surprised it hasn't been included in the serverless framework 3 years after request. Any update on the status of this feature?

**Comment by gilad-embryonics** [comment]
@alyhegazy's solution seems to be working on subsequent deploys as well

**Comment by medikoo** [comment]
It'll be nice to support `vpc: false` or `vpc: null` as an override.

PR that implements that is welcome!

**Comment by marcosmribeiro** [comment]
Any solution ? Same problem here... The @alyhegazy config didn't work for me...

**Comment by pgrzesik** [comment]
Hello @marcosmribeiro - we'd be happy to accept a PR implementing this change :raised_hands:
