### ISSUE TITLE
Allow symlinks as custom variable files in serverless.yml

### ISSUE THREAD

**Issue by BasileTrujillo** [serverless/serverless#4388]
# This is a Feature Proposal
## Description
`serverless.yml` allows to include variables from external `json` files using the following syntax:
```yml
custom: ${file(./config.json)}
```
But if the file is a symlink, Serverless Framework considers it as a non-existing file.

This is due to the use of `fs.lstat()` instead of `fs.stat()` inside the `fileExists()` function (`lib/utils/fs/fileExists.js`).

## Solving solution proposal
Because I do not know why `lstat` has been used instead of `stat` and to avoid potential side effect here is my proposal : 
https://github.com/serverless/serverless/compare/master...BasileTrujillo:custom-variable-file-symlink

**Comment by horike37** [comment]
Thank you for reporting the issue @BasileTrujillo :+1: 

>Because I do not know why lstat has been used instead of stat and to avoid potential side effect >here is my proposal :
>master...BasileTrujillo:custom-variable-file-symlink

Looks good solution for me :100:  the fix would not have potentially serious side effects.
I was wondering if there is any chance you could send pull request with the fix?
