### ISSUE TITLE
CodeSha256 will different every time after upgrade from 1.20.2 to 1.21.0

### ISSUE THREAD

**Issue by Pjack** [serverless/serverless#4392]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

No source code is changed. But the "CodeSha256" will change every time.

* What did you expect should have happened?

We expect the "CodeSha256" will not change if the source code is identical.
1.19.0 and 1.20.2 do not have this issue.

* What was the config you used?

<pre>
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3

package:
  individually: true
  exclude:
    - function1/**
    - function2/**
    - function3/**
    - test/**
    - Makefile
  include:
    - config.yml

functions:
  function1:
    handler: function1/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function1/**

  function2:
    handler: function2/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function2/**
</pre>

* What stacktrace or error message from your provider did you see? 
nope

Similar or dependent issues: nope

## Additional Data

* ***Serverless Framework Version you're using***:  1.21.0 and 1.23.0

* ***Operating System***:  Ubuntu 14.04

* ***Stack Trace***: nope

* ***Provider Error messages***: nope

We cannot reproduce it in v1.19.0 and v1.20.2
I suspect this issue is caused by the graceful-fs in this file.
https://github.com/serverless/serverless/commits/v1.21.0/lib/plugins/package/lib/zipService.js

**Comment by RafalWilinski** [comment]
Thanks for submitting this bug @Pjack 💯 

I suppose it was already fixed here: https://github.com/serverless/serverless/pull/4299

It should be included in next release (1.24) which is supposed to be released quite soon.

**Comment by horike37** [comment]
@RafalWilinski is right :+1: 
Closing this issue. Feel free to re-open if @Pjack wants to do more discusstion :smile:
