### ISSUE TITLE
Stop deployment if size limit is exceeded

### ISSUE THREAD

**Issue by iaforek** [serverless/serverless#4399]
# This is a Feature Proposal

## Description

When doing `sls deploy` if the ZIPPED package **exceeds** AWS lambda limits (right now it is 50MB) then the deployment should be stopped and appropriate warning message should be displayed to user. If you can't / don't want to stop deployment at least warning about size limits should be displayed.

## Additional Data
http://docs.aws.amazon.com/lambda/latest/dg/limits.html
```
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.2
     Serverless Version:     1.21.1
```

**Comment by RafalWilinski** [comment]
Thanks @iaforek for feature proposal! 💯 

Definitely makes sense. I'll try to come up with solution asap.

**Comment by shatgupt** [comment]
I have successfully deployed a package of ~52MB multiple times since last 6 months. Even though it is mentioned in the docs, AWS doesn't have a hard limit of 50MB.

Please do not error out in the framework, let AWS handle it.

**Comment by jaikdean** [comment]
Agreed, @shatgupt!

**Comment by iaforek** [comment]
That’s why I proposed to add a warning message instead of stopping deployment as alternative solution.

**Comment by vladgolubev** [comment]
@shatgupt looks like you have the case from this comment https://github.com/serverless/serverless/pull/4404#issuecomment-339432953

**Comment by dougmoscrop** [comment]
AWS also changes these limits from time to time. You're just opening the door to "raise limit to xyz" down the road.

**Comment by medikoo** [comment]
Closing, as it appears it's difficult to handle properly (see https://github.com/serverless/serverless/pull/4404#issuecomment-339438735) and how things are handled on AWS side is not as straightforward (see https://github.com/serverless/serverless/pull/4404#issuecomment-339380284).

Trying to handle this, we're likely to fall into implementation which produces false positives and does not warn when expected.

Great thanks for raising the issue and all the provided insight
