### ISSUE TITLE
Allow tests to run offline

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#440]
To be able to run the tests on Travis CI (or similar), they have to run offline. We could record the responses from AWS and mock them by using https://github.com/pgte/nock.

**Comment by michaelwills** [comment]
I have an initial WIP at #355 but will need to bring that up to date with the current code base. The initial work is just to make sure the buckets used are accessible to other collaborators.

**Comment by joostfarla** [comment]
@ac360 @eahefnawy Is there any interest in making the tests run offline (optionally)?

**Comment by flomotlik** [comment]
We're currently working on this and have integrated the build with CI as well. @michaelwills and @joostfarla would be great to get your input.
