### ISSUE TITLE
'deploy --function' produces "Member must satisfy regular expression pattern" while normal 'deploy' doesn't

### ISSUE THREAD

**Issue by mmagician** [serverless/serverless#4400]
I'm getting something related to #2036, I think.
When I run 'deploy' all works smoothly, however when I run 'deploy --function myFunction' I get this error regarding matching regular expression as specified in title.

My serverless.yml:

```
functions:
  myFunction:
    handler: uploader.myFunction
    runtime: python3.6
    events:
      - http:
          path: my/path
          method: post
          cors: true
    role: LambdaUploadToS3Role

resources:
  Resources:
    LambdaUploadToS3Role:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: xyz
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: policy-name-1
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*
                - Effect: Allow
                  Action:
                    - s3:putObject
                    - s3:putObjectAcl
                  Resource: arn:aws:s3:::my-bucket

```

My error:

1 validation error detected: Value 'LambdaUploadToS3Role' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws|aws-us-gov):iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+

I tried a workaround of use a Fn::GetAtt, but again, works in normal deploy but not with individual function deploy.

Thanks for help!

**Comment by RafalWilinski** [comment]
Hi @mmagician, thanks for reporting issue 💯 

This regression was introduced in 1.22 and already addressed here: https://github.com/serverless/serverless/pull/4320.

This bug fix will be released in 1.24. You can wait for 1.24 release (~week) or use <1.21 version.

**Comment by RafalWilinski** [comment]
Duplicate: https://github.com/serverless/serverless/issues/4318

**Comment by mmagician** [comment]
Thanks a lot for clarifying! Appreciate quick support.
