### ISSUE TITLE
Turn of SLS_DEBUG

### ISSUE THREAD

**Issue by chasebleyl** [serverless/serverless#4402]
This is probably a super simple issue to be resolved, but I can't turn off SLS_DEBUG to save my life. I turned it on by submitting `export SLS_DEBUG=*` via terminal. I have tried to use `export SLS_DEBUG=false` but that doesn't prevent the logs from continuing. How do I resolve this? It has to be easier than the amount of time I have spent trying to figure this out.

Thanks.

**Comment by RafalWilinski** [comment]
@chasebleyl I guess `unset` is the command that you're looking for 😄 

Try this:
```bash
unset SLS_DEBUG
```

Let me know if it helps.

**Comment by chasebleyl** [comment]
That was it! Thank you.
