### ISSUE TITLE
`sls remove` silently exits 0 if serverless.yml is missing

### ISSUE THREAD

**Issue by brettdh** [serverless/serverless#4406]
# This is a Bug Report

## Description

`sls deploy` prints a helpful error message if `serverless.yml` is missing:

```
➜ $(npm bin)/sls deploy -v
 
  Error --------------------------------------------------
 
  This command can only be run in a Serverless service directory
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.2
     Serverless Version:     1.23.0
```

`sls remove` does not:

```
➜ $(npm bin)/sls remove -v
(silence; exits 0)
```

In my case, I had forgotten to render a template file to `serverless.yml` (done in a `deploy` wrapper script omitted above, but not done when running plain `sls remove` as above. This was confusing and tricky to troubleshoot; a message like the one above would make it much more obvious in the future.

For bug reports:
* What went wrong?  **`sls remove` exited silently with success**
* What did you expect should have happened? **It should have printed an error and exited nonzero**
* What was the config you used? **n/a; see above**
* What stacktrace or error message from your provider did you see? **n/a; see above**

Similar or dependent issues:
* n/a

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Alpine Linux (in docker)
* ***Stack Trace***: n/a; see above
* ***Provider Error messages***:  n/a; see above

**Comment by RafalWilinski** [comment]
Thanks @brettdh for bug report! We'll try to include a fix in future releases.

**Comment by brettdh** [comment]
@alexdebrie though #4407 resolves this for `sls remove`, this issue also applies to `sls invoke`; maybe others?

Seems worth having a test for each command without a `serverless.yml`.
