### ISSUE TITLE
Run "pre" hook after CLI prompting

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#441]
I'm working an a CORS plugin and I want to let this plugin auto-create preflight requests on `endpoint deploy`. This means that I want to be able to dynamically add extra (OPTIONS) endpoints based on the endpoints that are selected by the user.

Ideally I want to do add these before the actual deployment starts, so I tried leveraging the `endpointDeployPre` hook. However, it seems that this hook is executed before the user input is given. Hence, the `evt` object is empty (`undefined`). What I would expect is that the `evt` object contains a collection of all endpoints that are going to be deployed, based on the user input. If that would be the case, I could easily add some extra endpoints before the actual deployment starts.

So what I would like to propose is to make a split between the "input" stage and the "execute" stage, so that the `pre` hook could be executed in between. I presume the same goes for all other actions.

You can have a look at the current implementation to see the issue:
https://github.com/joostfarla/serverless-cors-plugin

Looking forward to your feedback!

**Comment by eahefnawy** [comment]
:+1: I think prompts/inputs shouldn't be part of the action. In most actions, our very first step is to prompt anyway. But we'll need to refactor all our actions to separate them from user input, still not sure how we can do that yet.

**Comment by joostfarla** [comment]
Fixed with new plugin architecture :+1:
