### ISSUE TITLE
Print warning when 2 functions have same handler

### ISSUE THREAD

**Issue by vladgolubev** [serverless/serverless#4414]
# This is a Feature Proposal

## Description

Whenever I add a new ƛ I copy-paste last lines of code in `serverless.yml` file. Most of the time they are similar, so I just write a new handler and rename it (in `.yml`). 

But omg, it's too damn often when I forget to change the path of handler. When deployed I end up in a bizarre situation when I call 1 lambda but another is invoked. My coworkers often catch this during PR review, but still, not always.

I'd like to see at least a warning during deployment when 2 fns have exactly same path and handler.

Please tell me if this is a valid feature request or is it only my unique problem?

![2017-10-25 at 18 47](https://user-images.githubusercontent.com/3817380/32008621-5a4def06-b9b5-11e7-8d56-1f54d2803e6f.gif)

**Comment by KnupMan** [comment]
True story! :+1: 
Waiting for this feature!

**Comment by horike37** [comment]
Hey, @vladgolubev! Thank you for reporting this issue :+1: 
I think that's a valid feature request :100: 

Could you share the `serverless.yml` when you face the bizarre situation so that we can take a look into it?

**Comment by HyperBrain** [comment]
The validation should be done when importing the serverless.yml imo. Then it can break out at the earliest possibility.
@horike37 This is not a bug. It is an enhancement to warn about "user-generated" errors. I'll change the tag.

**Comment by vladgolubev** [comment]
@horike37 Just added a GIF to the description.  @HyperBrain is right, this is kind of enhancement to catch dumb user errors and improve DX

**Comment by HyperBrain** [comment]
@vladgolubev 🥇 for the great animated GIF 😄
