### ISSUE TITLE
Support for azure java functions

### ISSUE THREAD

**Issue by mozinrat** [serverless/serverless#4420]
For feature proposals:
* Azure recently started supporting java as lambda functions, just wanted to check if there is work for the active support of that.
* If there is already a ticket to track that progress, would be nice if I can get hold of that to follow on.

**Comment by horike37** [comment]
Thank you for opening this issue @mozinrat :+1: 
This repository is for Serverless core + AWS provider feature.
Azure provider plugin repo is here --> https://github.com/serverless/serverless-azure-functions/issues

Could you please open up the issue in there again?
Seems that a issue for supporting Java is not opened yet :thought_balloon:
