### ISSUE TITLE
Feature Request: Mixing lambda-proxy and lambda Integration

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4425]
Referencing: https://serverless.com/framework/docs/providers/aws/events/apigateway/

Currently we can choose between `lambda-proxy` or `lambda` integration.

The `lambda-proxy` integration is convenient for accessing request information. However we are forced to write the response as:

```
    callback(null, {
      statusCode: 200,
      headers: ...,
      body: JSON.stringify({ "message": "Hello World!" })
    })
```

while `lambda ` allows us to write 

```
    callback(null, { "message": "Hello World!" })
```

Most APIs do not return their true status code, but instead always return 200 and wrap the actual status code in their body (compare e.g. twitter api). This is so clients can always handle and utilize the response body.

It would be great if we could mix request and response templates for these two integration. Most importantly, allow for a short form when using the `lambda-proxy` integration.

**Comment by kbariotis** [comment]
> Most APIs do not return their true status code, but instead always return 200 and wrap the actual status code in their body (compare e.g. twitter api). This is so clients can always handle and utilize the response body.

@simlu Are you suggesting of using the `lambda-proxy` mode but calling the callback as if you were in the `lambda` mode?

The first response that you wrote (the `lambda-proxy` case) is specifically written to inform the API Gateway for what HTTP status code to return, what headers and body. The client will only see the `body` as the response and the headers and the status code of the HTTP response.

If you would like a fixed response while in `lambda-proxy` the simplest thing you could do is wrap the response in a function and always calling that.

Did I get it correctly?

**Comment by simlu** [comment]
@kbariotis That is entirely correct and what you suggested is actually what we ended up doing.

The problem was really that it didn't play nicely with our test framework to test lambda functions locally. But I have addressed this since. It would still be nice to combine the lambda-proxy or lambda, but it's not essential for us anymore.

Appreciate your response. Cheers!

**Comment by dougmoscrop** [comment]
Please don't design APIs that always return 200! (and I don't see evidence that Twitter does..) HTTP is an application level protocol. Use it!

**Comment by simlu** [comment]
@dougmoscrop Not going to get into a big discussion here, but it really depends on your use case. There are still quite a few clients out there that are not able to process the response message for non 400 status codes, which is the main argument against using them. But if you are sure your api is only going to be used by clients that can handle those, I fully agree. Unfortunately that is not the case for me.

Twitter seems to have recently switched over, but here is a reference from 2014: https://github.com/23/resumable.js/issues/160#issuecomment-37246635

**Comment by dougmoscrop** [comment]
Fair enough on legacy clients; I suggest using a library or something to achieve the boilerplate reduction you want.

**Comment by simlu** [comment]
I think this can be closed now. My use case seems isolated. Can re-open if it comes up again.
