### ISSUE TITLE
Authorizer of the type `request` is not deploying correctly

### ISSUE THREAD

**Issue by berdyshev** [serverless/serverless#4428]
# Bug Report

## Description

I'm trying to setup an authorizer by request's query string parameter with this config:
```
authorizer:
    name: apiKeyAuthorizer
    type: request
```

After deploying the configuration, in API GW console I see it has `token` type:

![image](https://user-images.githubusercontent.com/539090/32216226-1ed8d388-be2d-11e7-8b4e-dcaf33127fec.png)

When I'm trying to specify the `identitySource` to validate `key` parameter in query string with such config:
```
authorizer:
    name: apiKeyAuthorizer
    type: request
    identitySource: method.request.querystring.key
```
it fails to deploy with such error: ` An error occurred: ApiKeyAuthorizerApiGatewayAuthorizer - Invalid token source expression: method.request.querystring.key. The source must be a method request header, matching 'method.request.header.[a-zA-Z0-9._-]+'.`

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version***: 1.23.0
* ***Operating System***: MacOS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for reporting @berdyshev :+1: 
The functionality is not released yet(The documentation is already published though)
The release day of next version will be today :tada: Just a while.
