### ISSUE TITLE
Feature Proposal: DynamoDB CRUD scaffold generator

### ISSUE THREAD

**Issue by jagthedrummer** [serverless/serverless#443]
I'm really liking serverless and would love to work on a scaffold generator for generating all of the functions and endpoints for a full set of CRUD operations on a dynamodb table. I just wanted to get a little feedback as to how the maintainers feel this would best be accomplished.

I'm thinking the interface would be something like this:

```
serverless scaffold create
```

Then you'd be prompted for the name of the resource. Let's say `users`.

Then it would add a dynamodb resource block to `cloudformation/resources-cf.json`, add dynamodb actions to the `PolicyDocument.Statement` array (also in `cloudformation/resources-cf.json`), and then generate a `users` module (in `back/modules`) with the following functions:

```
users/index
users/create
users/update
users/show
users/delete
```

I could see this being a core part of serverless, much like scaffold generation is a core part of rails. I could also see an argument to be made for having this be a plugin or maybe even a stand alone project. Either way I'm happy to work on this and am just looking for a little direction on the best way to proceed. What do you all think?

**Comment by zevmo** [comment]
I like it!

**Comment by apaatsio** [comment]
Just for inspiration here's an example of a quite clean Lambda function that can handle all CRUD operations with DynamoDB: https://gist.github.com/apaatsio/f9f2b408fe02e415629f

It depends on the use case whether an all-in-one function or separate function for each CRUD operation is better.

**Comment by jagthedrummer** [comment]
Yeah, I've seen that example in the lambda quick start samples. I have two main complaints about that format.

1) It's not RESTful and depends on the 'operation' being passed in as part of the data payload. I'd rather have something that conforms to the REST pattern, which will mean that we need separate endpoints to match up to the different HTTP 'verbs'.

2) It requires that your data payload be in dynamodbs extended/verbose format. I'd rather have something that will consume/output regular json data objects and have the lambda functions translate between the two formats.

**Comment by apaatsio** [comment]
1) The operation is not part of the payload. You would create separate endpoints for each operation. E.g. create and read operations:

```json
{
  "handler": "modules/users/rest/handler.handler",
  "endpoints": [
    {
      "path": "users",
      "method": "POST",
      "requestTemplates": {
        "application/json": "{\"operation\":\"create\",\"user\":$input.json('$')}"
      }
    },
    {
      "path": "users/{id}",
      "method": "GET",
      "requestParameters": {
        "integration.request.path.id": "method.request.path.id"
      },
      "requestTemplates": {
        "application/json": "{\"operation\":\"read\",\"id\":\"$input.params('id')\"}"
      }
    }
  ]
}
```

2) Agreed. The example should be extended to handle a simpler data format.

**Comment by remicastaing** [comment]
You can also pass the http method through:
```
...
"requestTemplates": {
            "application/json": "{\"httpmethod\": \"$context.httpMethod\", \"id\": \"$input.params('id')\"}"
          },
```

**Comment by jagthedrummer** [comment]
@apaatsio & @remicastaing, thanks for the info on the operation param and http method pass through. 

Does a single handler create any issues with using `sls function run`? Specifically, it seems like there's a 1 to 1 mapping between `event.json` and `s-function.json`.

**Comment by joostfarla** [comment]
@jagthedrummer Thanx for this! I think this would be a seriously valuable addition to the framework! 

Here is my feedback:

- `serverless scaffold create` might be too implicit. While DynamoDB is great for lots of purposes, people might want to use other platforms like Amazon RDS, Elasticsearch, MongoLab or CouchBase. So if this would be a core function, I think it should be platform-agnostic.

-  Users should be able to select which methods have to be scaffolded. Furthermore, I think one of the options has to be scaffolding API gateway endpoints with empty handlers.. 

- Not sure whether I like the approach of merging all CRUD functions in one `s-function.json` (as stated in https://github.com/serverless/serverless/issues/398). From a RESTful perspective, it might make sense to create one module per resource. This depends on the direction the framework is taking on modularity though!

The basis of this might be a core component of the framework. If you want to collaborate on this issue, let me know!

**Comment by jagthedrummer** [comment]
Hey @joostfarla, thanks for the feedback.

I totally agree that it should aim to cover additional storage back ends, and like the idea of choosing which endpoints to scaffold and the option to build empty handlers.

I've just been playing around with the idea of all CRUD functions in one `s-function.json` and there are some challenges to that approach. It seems like serverless expects a 1 to 1 mapping of `event.json` to `s-function.json`, so that makes it weird to do `serverless function run`. From a performance standpoint it seems like it would be preferable for each handler to be seperate and for each of them to `require` as little code as possible. For instance, the `create` method probably needs to `require` a UUID generator, but all the other handlers would not need that code. Lambda spin up time would definitely be helped by splitting them up. On the other hand, if they're all lumped together, then when someone calls `index`, then all of the other CRUD operations are already 'warmed up'. Maybe the right choice depends on your usage patterns and we should offer options for both?

**Comment by jagthedrummer** [comment]
Similarly to the multiple storage platform idea, people may want to use different JSON payload structures. JSON API vs the traditional Rails structure, for instance.

**Comment by joostfarla** [comment]
@jagthedrummer I fully agree on your arguments!

To be honest, I don't fully understand the idea of putting multiple functions/endpoints in one `s-function.json`. Each function can point to a different handler (which removes your performance concerns), but I still feel like this overcomplicates things.

**Comment by jagthedrummer** [comment]
@joostfarla Ah yeah, separate handlers with a single `s-function.json` would fix the performance issue. So, in that case I could see the single `s-function.json` acting kind of analogously to `config/routes.rb` in Rails. But the issue with `event.json` is still there.

It would also be nice if there was an option to generate tests for the scaffolded code.

**Comment by joostfarla** [comment]
@jagthedrummer The core developers just commented they will probably remove the multi-function support in v0.1, which is a good thing if you ask me :+1:

**Comment by jagthedrummer** [comment]
@joostfarla Welp, I suppose that answers that question. :smile:

I'm currently working on a demo project just to model what simple dynamo based CRUD should look like. I'll post it here when I have something worth discussing.

**Comment by joostfarla** [comment]
@jagthedrummer Great! Looking forward!

**Comment by remicastaing** [comment]
@jagthedrummer , I'm also trying to add a dynamo based CRUD to my [serverless-examples](https://github.com/remicastaing/serverless-examples).

**Comment by jagthedrummer** [comment]
@remicastaing Thanks for pointing out your repo. I hadn't come across that one yet.

Here's what I have going so far on my demo. 

https://github.com/jagthedrummer/serverlessDynamoCrudExample

I've deployed it all to my AWS stack and used this Ember app to test that all the endpoints actually work the way I expect.

https://github.com/jagthedrummer/serverless-dynamo-crud-example

This is still a very rough sketch, but I'd love to hear comments on the general structure there. Once that's looking nice I'll use it as the basis for what the scaffolding generator should produce.

cc @joostfarla

**Comment by remicastaing** [comment]
@jagthedrummer , you have come farther than me. And I didn't try to implement the client side, relying on [postman](https://www.getpostman.com/) to perform test.

**Comment by jagthedrummer** [comment]
Ok, so thinking about how to do this in a modular way I'm thinking that we'd need 4 main parts to allow people to mix and match their choice of storage back end with their choice of wire format (rails json vs json api).

1. ResourceGenerator - This would be responsible for modifying `cloudformation/resources-cf.json` to add the appropriate resource and policy statements for a given backend. There might be `DynamoDbResourceGenerator` and `SimpleDbResourceGenerator` etc...

2. InputAdapter - This would be responsible for accepting the request payload in a particular wire format and transforming it into standard json data objects representing the abstract model and/or request params. There might be `RestInputAdapter` and `JsonApiInputAdapter`. This would be a "serverless internal data model" structure of some sort. It might make sense to adopt JsonAPI as the standard and have other input adapters be responsible for translating requests in their given format to JsonAPI.

3. StorageAdapter - This would take the data objects from the InputAdapter, perform any transformations that are needed for a given backend, and then perform the actual data operations. There might be `DynamoDbStorageAdapter` and `SimpleDbStorageAdapter` etc... After the operation is performed it would create data objects in whatever format we're using as the internal data structure.

4. OutputAdapter - This would take the output from the storage adapter and translate it into the needed wire format. `JsonApiOutputAdapter`, `RestOutputAdapter`, etc...

I'm thinking that Input/Output Adapters would be developed in pairs, as would the ResourceGenerator and StorageAdapter.

Another possibility, though less flexible, would be to ditch the 4 part approach and treat each backend/wire-format pair as a unique thing. So there's an option for `DynamoRest` or `DynamoJsonApi` or `SimpleDbRest` or `SimpleDbJsonApi` etc...

I'd love to hear any thoughts, comments, or criticisms anyone has on this.

**Comment by flomotlik** [comment]
We would love to have this generator, though I think the best place would be in a plugin. Let me know if you're still interested in looking into this and creating a plugin. I will close this issue for now.

**Comment by dankelleher** [comment]
Hi, resurrecting an old thread - did anyone ever make a plugin for this? It seems like a good enhancement to have.

**Comment by DavidWells** [comment]
I agree this would be pretty cool

**Comment by dankelleher** [comment]
So I was thinking about this a bit and I think there are two options. Which of these would people find the most useful?

## 1. A CRUD scaffold generator 
...basically as described in the issue so far, you type something like `serverless crud-scaffold create MyEntity`and the plugin creates the handlers and db connectors etc from a template. Of course to be properly useful it should add the API Gateway routes to the serverless.yml too. Are we okay with a plugin editing the serverless.yml like this?

**Pros**
- Easily configurable
- Understandable

**Cons**
- Code Generation is icky.
- Automatically editing the serverless.yml file is nasty

## 2. A dynamic CRUD plugin
... in this version, you would add some property to serverless.yml such as: 

```
entities:

  - MyEntity1
  - MyEntity2
```
and the plugin would create the appropriate lambdas and API Gateway routes at deploy time using the AWS client. The developer would never see the actual code. There would need to be some properties of course for DB connection details etc.

**Pros**
- You could create an entire CRUD app without a single line of code and with a tiny .yml file
- Implementation details hidden from developer
- Can make configuration changes (e.g. switch out DB providers) without having to change the code

**Cons**
- Too much magic?
- Harder to integrate with locally running code, e.g. tests
- Tracking changes in the yml file would be difficult (e.g. what to do if an entity is removed from the entities list)

Even though option 2 sounds attractive, I am leaning towards option 1. What do others think?

**Comment by buggy** [comment]
I think this would make more sense as a separate framework. There's a lot more to a simple CRUD app than reading/writing to the database. Look at how much work has gone into Rails. You need to deal with persisting the data, input validation, relationships, etc. What happens when someone needs to perform more than trivial validation?

There's also issues around:

1. Which platform/language is support? Do we support every one that Serverless supports?
2. What happens if code needs upgrading - either to fix a bug or because an API has changed?

**Comment by horike37** [comment]
I agree with @buggy.
scaffold generator is useful for developers. However Generated code should be guaranteed safty and its quality and should support many  kinds of platform/language.

We should consider about scaffold generator after sorting out these problems.

**Comment by dougmoscrop** [comment]
Some people use things like `slush` combined with console prompts to make an intelligent generator - I've done this before, it worked okay but not great.

Other people use skeleton repos, where you use Git to pull in updates to the 'foundation' (i.e you have your files that import other files, those files mostly say 'you code here' etc.)

I think serverless has some decent support for this, you can define a serverless.yml file that imports whatever you want in another yml file for custom resources, you can define the app structure, etc. and all of this is just a matter of someone doing a git clone on your base repo. Any updates are handled via normal merge/conflict resolution.

I would say if serverless supported creating from URLs ([I thought it did already!] e.g. `sls create -t github:user/skeleton`) I would hope that's all that serverless has to care about. The rest is just your choice of convention and configuration over top of source control.

**Comment by hutchic** [comment]
@buggy I think it's important to balance not over complicating things vs doing zero planning.

> Which platform/language is support? Do we support every one that Serverless supports?
Make small incremental positive changes. So first iteration support one language, ideally the language that will have the most people contribute back to have a better chance at succeeding.

> What happens if code needs upgrading - either to fix a bug or because an API has changed?
Neither is a new problem to automatic crud / scaffold generators I'd suggest investigating how other languages / frameworks have resolved these problems.

My $0.02: nodejs, scaffold generator. Feed it your swagger it pukes out a serverless.yml file that includes cognito, dynamodb and apigateway.

**Comment by pmuens** [comment]
Closing this one since it would be better to have this as a separate, community-drive project. Feel free to continue the discussion though...
