### ISSUE TITLE
Cannot find module Error when testing URL after deployment

### ISSUE THREAD

**Issue by ddausch** [serverless/serverless#444]
I am just starting out with Serverless framework. I followed the instructions in "Installing Serverless" and then "Introducing Modules". Seemed pretty straight forward. I successfully did an endpoint deploy and then tested the URL. I received the following error:
{"errorMessage":"Cannot find module 'modules\\greetings\\hello\\handler'",,"errorType":"Error","stackTrace":["Function.Module._resolveFilename (module.js:338:15)","Function.Module._load (module.js:280:25)","Module.require (module.js:364:17)","require (module.js:380:17)"]}

I also followed another set of directions at: 
http://blog.zerosharp.com/serverless-framework-part-1-up-and-running/

and I received the same issue, although different URL. Are the directions not specific enough? Did I miss something here? The directories all seem correct under the project.

**Comment by joostfarla** [comment]
Looks like you are working on Windows? There are other people having the same issue here: https://github.com/serverless/serverless/issues/235

**Comment by ddausch** [comment]
Yes, I am working on Windows. Thanks for pointing me to issue #235. Do you have any knowledge of a work-around or if this will be addressed in v0.1.0 release? It seems like a pretty significant issue.

**Comment by joostfarla** [comment]
@ddausch nope sorry, I have not heard of any workaround yet. But I can imagine it has something to do with differences in path resolution (`/` vs `\`).

**Comment by ddausch** [comment]
Thanks for the info. I am very new to Serverless. What would be the recommended process or who to reach out to in order to determine if it will be addressed in v0.1.0 release?

**Comment by joostfarla** [comment]
@ddausch I think I figured out what's going wrong, although I don't have a Windows machine to test on.

Would you be so kind to test my `windows` branch on your environment? It's based on the `master` branch, because `v0.1.0` is quite unstable at the moment. If this fix works, I will submit it for both `master` and `v0.1.0`.

https://github.com/joostfarla/serverless/tree/windows

**Comment by joostfarla** [comment]
Oh, forgot to mention, my change only affects newly generated functions. If you want to test this for existing functions, you should change all backslashes in the `handler` property in your `s-function.json` files to forward slashes.

**Comment by ddausch** [comment]
Thanks so much for working on this! I will test. I am just in learning/experimentation mode so I will start out with new functions - not a problem.

**Comment by sixlettervariables** [comment]
@joostfarla if you go and reference my work in #219, you'll see that all AWS paths should be generated using `path.posix.*` (or make use of `path.posix.sep`). All local paths should be generated using `path.*` (or make use of `path.*`). Simply using `path.join` everywhere or including the path separator explicitly will eventually lead to failures.

**Comment by joostfarla** [comment]
@sixlettervariables :+1:  exactly, that is the fix I added in my branch. (was not familiar with the `posix` mode though, will change that if the fix seems to work)

**Comment by sixlettervariables** [comment]
`path.posix.*` and `path.win32.*` allow you to generate paths for known platforms, they're just platform specific versions of `path.*`.

**Comment by ddausch** [comment]
Great news Joost! I was able to successfully deploy and then hit the website successfully. Thanks again for taking the time to look at this and provide a resolution. Much appreciated!

**Comment by joostfarla** [comment]
Great! Have submitted the PRs! :+1:

**Comment by ddausch** [comment]
Awesome! Thanks again.
