### ISSUE TITLE
Amazon API Gateway Endpoint type

### ISSUE THREAD

**Issue by whyvez** [serverless/serverless#4440]
# This is a Feature Proposal

## Description
AWS just added endpoint types in API Gateway. Currently, there are two endpoint types you can choose from. Edge-optimized and regional. With Regional you can attach your own CloudFront distribution. I'm not sure if this is supported in CloudFormation yet.

The AWS CLI command to select an endpoint type looks like:

```terminal
aws apigateway create-rest-api \
        --name 'Simple PetStore (AWS CLI, Regional)' \
        --description 'Simple regional PetStore API' \
        --region us-west-2 \
        --endpointConfiguration '{ types: ["REGIONAL"] }'
```

It would be nice to have this as a provider level configuration.

**Comment by HyperBrain** [comment]
@whyvez Can you please use the issue template, shown when creating a new issue, and fill out the resp. sections instead of just using a one-sentence description for an issue? This makes it a lot easier for us to organize incoming requests - may it be bugs or features. Thank you.

**Comment by whyvez** [comment]
@HyperBrain Sorry about that. How does that look?

**Comment by HyperBrain** [comment]
@whyvez Much better 😄 Thank you for updating.

**Comment by alexdebrie** [comment]
@whyvez Agree that this would be a great addition! Unfortunately, this is not supported in CloudFormation yet. I propose we keep this issue open until it is supported, but there is a workaround below.

**Manual workaround:**

Another user reported that if you update the configuration of your REST API to a Regional endpoint, the configuration won't be overwritten on subsequent deploys. Deploy your service once, update the config, and it'll stay like that forever 💥 .

Check out the documentation for [updating your REST API endpoint type](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-api-migration.html#migrate-api-using-console) to see the different ways you can change your endpoint type.

**Comment by jaikdean** [comment]
+1 for this when it's supported by CloudFormation. Regional Endpoints allow you to use your own CloudFront distribution, so you have more control over things like allowed encryption protocols (we'll need to remove TLS <1.2 from our APIs in the coming months).

**Comment by pierreis** [comment]
This is now supported in CloudFormation, via the `EndpointConfiguration RestApi` parameter. The docs are [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html).

I'm crucially missing this feature to automate deployment of multi-region API failover.

**Comment by HyperBrain** [comment]
@pierreis Good find 👍 . 
I will have a look. Adding the support should be quite trivial.

**Comment by pierreis** [comment]
`EndpointConfiguration` is both a possible parameter of `RestApi` and `DomainName`, hence the precision.
