### ISSUE TITLE
Plugin not found (but is installed and in package.json)

### ISSUE THREAD

**Issue by richburdon** [serverless/serverless#4443]
# This is a Bug Report

## Description

I have a monorepo where my plugin is a peer of the test project that will use it. 

~~~~
project/
  node_modules/
    serverless-my-plugin/
    serverless-webpack/
  packages/
    my-plugin/
      package.json
    my-test/
      package.json     // Contains: {"devDependencies": {"serverless-my-plugin": "0.0.1"}}
      serverless.yaml  // Contains: plugins: - "serverless-my-plugin"
~~~~

The plugin is installed according to node/yarn. I.e., in `my-test/` I can do the following:

~~~~
babel-node
> require('serverless-my-plugin')
{ default: [Function: ServerlessMyPlugin] }
~~~~

But when I run `sls` I get the following error:

~~~~
Serverless plugin "serverless-my-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
~~~~

NOTE: I'm using the same mono-repo to install and use `serverless-webpack`, which works fine. Is there an additional "install" step (outside of node) that is required?

## Additional Data

* ***Serverless Framework Version you're using: 1.22.0***:
* ***Operating System: OS/X***:

**Comment by richburdon** [comment]
Mistake: I was doing:

~~~~
export default class MyPlugin {}
~~~~

Rather than:

~~~~
class MyPlugin {}
module.exports = MyPlugin
~~~~

**Comment by RafalWilinski** [comment]
I'd also suggest renaming your class from `MyClass` because it might clash with another plugin and end up being de-duplicated.
