### ISSUE TITLE
`sls run` outputs `console.log` to response body

### ISSUE THREAD

**Issue by kbrandwijk** [serverless/serverless#4446]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description
When using `serverless run`, any `console.log(...)` statements in my function are sent to the HTTP response. This causes callers that expect a certain body to fail.

For bug reports:
* What went wrong?
The `console.log` output was sent to the HTTP response.
* What did you expect should have happened?
The `console.log` should not be part of the HTTP response.
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.0
* ***Operating System***: Windows 10 Pro
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Closing since this issue got quite stale. Feel free to re-open if this is still a problem.
