### ISSUE TITLE
Does the way of organizing lambda functions affect how functions behave from hot/warm perspective?

### ISSUE THREAD

**Issue by syang** [serverless/serverless#4449]
I understand that cold-start is something we need to put efforts/tricks to avoid, particularly for lambda handling user facing API endpoints.

From this perspecitve, (here is my idea) if all the handling functions are packaged into a large execution package, and use a self-made constant GET to hit one endpoints, then we ought to be able to keep all the functions in that package 'warm'. **Question: if functions are defined in a single file, and one function is called constantantly (say, once per second); would other functions defined in that file automatically have a 'hot' start even they are called very sparsely (say every 45 mins)?**

```
/serverless.yml (defines 4 endpoints of GET "/"; POST "/msgs"; GET "/msgs"; GET "/msgs/{msgID}") 
/handler.js (defines 4 handler functions in a single file)
```

But from software engineering perspective, it would be great to put different handlers into separate files to handle different endpoints, as show below.
```
/serverless.yml (defines 4 endpoints of GET "/"; POST "/msgs"; GET "/msgs"; GET "/msgs/{msgID}") 
/handler.js (service the endpoint of "/")
/restful_services/
      post_a_msg.js
      get_messages.js
      get_a_msg.js
```

PS: Does the above consideration has anything to do with ```serverless package``` https://serverless.com/framework/docs/providers/aws/guide/packaging/?

**Comment by HyperBrain** [comment]
Hi @syang, there is [`serverless-plugin-warmup`](https://github.com/FidelLimited/serverless-plugin-warmup) which does the job of keeping selected lambdas warm perfectly and automatically creates calls that are triggered by CF event rules properly.

But in case you run into cold-start scenarios, the rule of thumb is, the bigger your ZIP files (service packages) are, the longer it takes for a cold-start. AWS unpackages your lambda's code packages on the first run.

**Comment by syang** [comment]
@HyperBrain thanks for giving the answer about the cold-start time rule-of-thumb, "the bigger your ZIP files (service packages) are, the longer it takes for a cold-start." - very clear and thanks.

My original question, though was, whether packaging an infrequently-called handler with a frequently-called handler together can help avoiding or doing away the cold-start of the  infrequently-called handler.

**Comment by dougmoscrop** [comment]
The "package" that Serverless produces is ephemeral. Lambda copies the function source code in to a private storage area - which the current limit is 75GB for "function code storage" and it does this for each function. So the fact all the functions are in the same zip file, is, as far as I can tell, irrelevant, except that it might hurt cold start type as @HyperBrain mentioned. One function running from the source file does not make another function that targets the same source file also warm. Those functions can have very separate characteristics - IAM execution roles, memory allocation, environment variables, VPC attachments -- they're totally separate things.

It's usually best to package individually, unless total network transfer is a problem (your connection is slow/metered).

**Comment by pmuens** [comment]
Closing since this is an old issue and the issue thread includes some answers / insights here.
