### ISSUE TITLE
serverless update check failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by AWegnerGitHub** [serverless/serverless#4452]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? When installing with `sudo npm install -g serverless` on Ubuntu 16.04, locally, I get the following message:

```andy:/home/andy$ sudo npm install -g serverless
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.24.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js


┌────────────────────────────────────────────────────────┐
│             serverless update check failed             │
│          Try running with sudo or get access           │
│          to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/andy/.config │
└────────────────────────────────────────────────────────┘
+ serverless@1.24.0
added 296 packages in 7.444s
```

Running the `sudo chown -R $USER:$(id -gn $USER) /home/andy/.config` command and rerunning, does not change the output.

I have confirmed that .config and everything in it is owned by the user running the command.

* What did you expect should have happened? Since I ran this with `sudo`, I expected the install to complete without this warning. 
* What was the config you used? I don't believe this is applicable. I'm not to the point of configuring serverless yet. I'm just trying to install it.
* What stacktrace or error message from your provider did you see? I have provided the entire output, above.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: Attempting to install 1.24.0
* ***Operating System***: 
```
andy:/home/andy$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
* ***Stack Trace***: Entire output provided at the top of this issue
* ***Provider Error messages***: Entire output provided at the top of this issue

**Comment by AWegnerGitHub** [comment]
@horike37  Thanks for the response.

I initially tried to do `npm install -g serverless` and received the following output:

```
andy:/home/andy/my_repos/smoke_detector_aws$ npm install -g serverless
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/serverless/node_modules/aws-sdk
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/serverless
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/serverless/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules/serverless/node_modules/aws-sdk
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/serverless/node_modules/aws-sdk'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/serverless/node_modules/aws-sdk'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules/serverless/node_modules/aws-sdk\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/serverless/node_modules/aws-sdk' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andy/.npm/_logs/2017-11-08T05_18_07_833Z-debug.log
```

The recommendation in that error is to try running the command again as root/Administrator.

**Comment by HyperBrain** [comment]
@AWegnerGitHub How about if you install the Node version manager (nvm) and select the Node version you'd like to have as default with it? With nvm the globally installed node apps and modules can redise in user space and there is no need to have them installed under `/usr/lib/node_modules` anymore, and so you'd not need to use sudo.
Could you give that a try and install serverless afterwards without `sudo`?

**Comment by AWegnerGitHub** [comment]
@HyperBrain I used nvm to install the same version of Node that I already had installed. It seemed to work. I reran the serverless install, without `sudo`, I didn't get the error.

At this point, I'm going to assume that means it was a Node problem and not a Serverless Framework problem. Does that seem accurate? 

Thanks for your help.

**Comment by HyperBrain** [comment]
@AWegnerGitHub I think so. At least strange things might happen if you install node applications globally with `sudo` 😄 . Good to hear that it is solved and works for you now.

**Comment by jadhavmanoj** [comment]
@HyperBrain @AWegnerGitHub   I am facing same issue. I tried with nvm as well. but no luck. is there any workaround for this? I think its specific to Ubuntu 16.

Thanks.

**Comment by alexkli** [comment]
Happening for me inside Docker on Debian 8, with node 10.9 and npm 6.4.0 and serverless 1.30.1, see below.

Note that I have to install it globally because using it as a dependency of another cli tool. The command below is just to simply reproduce the issue, but the error of the actual npm install command I am using is exactly the same.

None of the suggestions from the error message work, neither callling `sudo npm install -g serverless`, nor `sudo chown -R $USER:$(id -gn $USER) /root/.config` (and followed by either normal or `sudo` install again).

```
> npm install -g serverless
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless

> serverless@1.30.1 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js


┌───────────────────────────────────────────────────┐
│          serverless update check failed           │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
+ serverless@1.30.1
updated 1 package in 3.027s
```

**Comment by alexkli** [comment]
Is it safe to ignore this error? After all, it's just an "update check", right?

**Comment by atz** [comment]
Same on a basic Alpine docker build.  E.G. `Dockerfile`:
```
FROM alpine
RUN apk add --update nodejs nodejs-npm
RUN npm install -g serverless
ENTRYPOINT ["/bin/sh"]
```
Running `docker build .`:
```
Sending build context to Docker daemon  1.882GB
Step 1/4 : FROM alpine
latest: Pulling from library/alpine
bdf0201b3a05: Already exists 
Digest: sha256:28ef97b8686a0b5399129e9b763d5b7e5ff03576aa5580d6f4182a49c5fe1913
Status: Downloaded newer image for alpine:latest
 ---> cdf98d1859c1
Step 2/4 : RUN apk add --update nodejs nodejs-npm
 ---> Running in d08017742022
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/8) Installing ca-certificates (20190108-r0)
(2/8) Installing c-ares (1.15.0-r0)
(3/8) Installing libgcc (8.3.0-r0)
(4/8) Installing http-parser (2.8.1-r0)
(5/8) Installing libstdc++ (8.3.0-r0)
(6/8) Installing libuv (1.23.2-r0)
(7/8) Installing nodejs (10.14.2-r0)
(8/8) Installing npm (10.14.2-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 55 MiB in 22 packages
Removing intermediate container d08017742022
 ---> ec6ab96355c4
Step 3/4 : RUN npm install -g serverless
 ---> Running in 09cfd5403f0f
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.41.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js


┌───────────────────────────────────────────────────┐
│          serverless update check failed           │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
+ serverless@1.41.0
added 392 packages from 277 contributors in 20.224s
```
Alpine runs everything as root, and I confirmed the directory exists with correct owner and permissions. I have to conclude the warning is generated falsely.

**Comment by arizonatribe** [comment]
Why is this issue closed if many of us are still experiencing it - especially through Docker?

And it doesn't make sense for us to use nvm inside of a Docker image. Most of the time we want light images that are quick to build, so Alpine with just a couple of bare bones packages is necessary for those of us that are juggling a lot of applications that are built multiple times per day.

Please re-open this issue since users have been reporting that it is _not_ solved for the past 18 months.

Thanks
