### ISSUE TITLE
[feature request] add option "--force" to command "serverless remove"

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4455]
# This is a (Feature Proposal)

## Description

Can we have an option `--force`  when running `serverless remove`. So if without this option, give some prompts, such as the service name, region, stage, etc and ask for [Yes/No] for confirmation.

**Comment by horike37** [comment]
Thank you for the suggestion @ozbillwang :+1: 
We've discussed a related feature in #3679 and #1609 and 3928. But still not be implemented yet.
