### ISSUE TITLE
UsagePlan is not created unless apiKeys are defined

### ISSUE THREAD

**Issue by bsdkurt** [serverless/serverless#4459]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
UsagePlan not created when apiKeys are not defined
* What did you expect should have happened?
UsagePlan should create if specified in config
* What was the config you used?

service: device-v1

custom: ${file(../custom-properties-${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.region}
  usagePlan:
    throttle:
      burstLimit: 200
      rateLimit: 100

* What stacktrace or error message from your provider did you see?
no stacktrace or error message. Just UsagePlan not created

## Additional Data
I have two use cases for creating UsagePlans without ApiKeys:
1) I have a custom resource and lambda's that manage the creation and deletion of ApiKeys. It is not possible to create a UsagePlan in the Resources section due to the ApiGatewayDeployment random number, so I want serverless to do it, but I currently need to create an an ApiKey to force the UsagePlan to create.
2) I have an api that doesn't use ApiKeys but I want to create a BasePathMapping resource which requires a DependsOn ApiGatewayDeployment, but since there is a random number in that, I can depend on a unused UsagePlan (which does depend on ApiGatewayDeployment). 

* ***Serverless Framework Version you're using***:
1.24.1
* ***Operating System***:
Ubuntu 16.04.3 LTS
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by bsdkurt** [comment]
The change to make this work is trivial, please see attached one liner diff that I'm using.

[usagePlan.js.diff.txt](https://github.com/serverless/serverless/files/1454615/usagePlan.js.diff.txt)

**Comment by horike37** [comment]
Thank you for reporting and putting the code for resolving it @bsdkurt :+1: 
I have tried your code and great to see working fine :100: 

For further verification, cloud you send pull request with your fix?
Additionally, we need to fix test code related to that as well.
