### ISSUE TITLE
Feature request: Enable API Gateway logs 

### ISSUE THREAD

**Issue by kbariotis** [serverless/serverless#4461]
# This is a Feature Proposal

## Description

So, I started today looking about how I can enable the logs on API Gateway. After some googling, I concluded that there isnt a way currently to do it with Serverless. I found a [year old discussion here](https://github.com/serverless/serverless/issues/1918) and that from an [external plugin](https://github.com/HyperBrain/serverless-aws-alias/issues/57).

Both of these require external plugins to be added and that's something I don't want to do and I would be much happier if that was something that this framework provided outside the box.

I would like to start a conversation on how we can provide this feature and also learn more about why haven't provided this feature. It may be something quite difficult and I am missing it.

### What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

[Enable API Gateway logs](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/) that I can later view from Cloudwatch.

### If there is additional config how would it look

Per service or per function configuration. Just a boolean would be nice.

```yaml
provider:
  enableAPIGLogs: true
```

### Similar or dependent issues:
* #1918
* External: https://github.com/HyperBrain/serverless-aws-alias/issues/57

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @kbariotis ,

I'd propose a similar solution as in my plugin 😄 . There it is possible to configure all APIG stage settings (not only the logs) and that on all possible levels (per service, per function, per endpoint). The reason why I think a possible native SLS solution should be of the same functionality is, that in practice you'd need this fine-grained sttings especially for development stages. Additionally it is not really good to have only a per service setting, as a service with many endpoints/methods suddenly generates quite big costs...

**Comment by HyperBrain** [comment]
Here's where I commented the current configurability in the plugin: https://github.com/HyperBrain/serverless-aws-alias/issues/57#issuecomment-310364055

**Comment by kbariotis** [comment]
@HyperBrain absolutely! I am not arguing about the implementation. I am stating that this is something that SLS should provide imo. 🙂

**Comment by horike37** [comment]
I think there is no reason for not supporting the functionality.
We can add that to SLS Core if CloudFormation supports for API Gateway logs.

**Comment by HyperBrain** [comment]
@horike37 This needs some deeper planning and evaluation, because the APIG stage configuration can only be set if there is a dedicated `AWS::Stage` resource available in the template.
Currently the stage is implicitly created by setting the literal string stage name at the `Deployment` resource. This has to be changed (which is a *breaking change*, because users will have to manually delete their stages first - you'll receive a "stage already exists" error). There is no workaround to make that non-breaking.
I'll try to look up the issues where the separate stage was already discussed.

**Comment by kbariotis** [comment]
@HyperBrain I see the issue now. Given that the main goal here is to separate the creation of the `Stage` resource before the `Deployment` resource, in order to be able to add properties(such as APIG Logs) we need to keep backward compatibility for the deployments that have already created a `Stage` implicitly.

In a scenario where there is a fresh deployment, everything will work fine.

In a scenario with an existing deployment, we have to find a way to update the previously implicitly created `Stage` resource.

If we add the `Stage` resource to the CF template pointing to the `Deployment` (through [the `DeploymetId` property](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-deploymentid)) would that make CF assume that we want to update the resource and not re-create it?

**Comment by HyperBrain** [comment]
> If we add the Stage resource to the CF template pointing to the Deployment (through the DeploymetId property) would that make CF assume that we want to update the resource and not re-create it?

No. I faced exactly that problem in my alias plugin. The "old" stage resource created by Serverless is completely separated, and there is no way to "reassign" or update it. A new manages `AWS::Stage` resource can only be created if the old one is deleted. The stage created with the string name only, seems to be treated as "unmanaged" from CF side.

**Comment by ozbillwang** [comment]
Thanks @HyperBrain to point out the problem `stage already exists`, I deal with this issue the whole weekend, until I saw your comment.

https://forum.serverless.com/t/how-to-enable-cloud-watch-logs-for-api-gateway-using-serverless/2067/4?u=bill

Very happen to hear Serverless team plan to support as core service.

**Comment by kbariotis** [comment]
@ozbillwang you will find more information about this [here](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/). The Role that manages the API Gateway needs an extra policy.

**Comment by ozbillwang** [comment]
@kbariotis 

Thanks, finally I got it, this role need be managed separately. 

To all here, 

By the way, any progresses for this feature? 

In fact, I am more interesting on how to generate the access logs to DynamoDB directly.

**Comment by ozbillwang** [comment]
For anyone who is still stuck with this issue and can't wait for this feature to be implemented in Serverless framework core server, I wrote a detail document on how to do it with plugin:

https://forum.serverless.com/t/knowledge-sharing-enable-cloud-watch-logs-for-api-gateway-using-serverless/3287

**Comment by dnalbach** [comment]
Where did this land? Is this going to be added to Serverless Core?

**Comment by mitshubh** [comment]
Its being added to SAM
@dnalbach -- https://github.com/awslabs/serverless-application-model/issues/516

**Comment by jordanboston** [comment]
I'm also wondering " Is this going to be added to Serverless Core?"
Not wanting to use SAM.  I like that Serverless is not married to AWS, even though that is what we are using. 😉 
_Thanks for all the hard work on this great framework BTW!_

**Comment by chrisyorkston** [comment]
Is there any update on this?

**Comment by marv72** [comment]
Any news on this?

**Comment by et304383** [comment]
A plugin shouldn't be required for basic configuration such as enabling logging of CW metrics.

**Comment by eahefnawy** [comment]
looking into this, I'm guessing we're gonna need to manage stages under their own Stage template (since APIG logging is a stage property) rather than implicitly with the Deployment template, which would break existing APIGs. As explained here:
https://github.com/serverless/serverless/pull/5692#issuecomment-469238505

@HyperBrain based on your experience, do you think we could introduce this feature without breaking changes? Or it would work only for new APIGs?

**Comment by drissamri** [comment]
What are people using to work around this issue? 

Does the following link still have the latest information: https://forum.serverless.com/t/knowledge-sharing-enable-cloud-watch-logs-for-api-gateway-using-serverless/3287

**Comment by waynerobinson** [comment]
Should the `StageName` value in `AWS::ApiGateway::Deployment` be swapped out for at least a basic configuration of `AWS::ApiGateway::Stage` so that it can be overridden later by the user?

**Comment by waynerobinson** [comment]
For example, replace the definition in https://github.com/serverless/serverless/blob/11ff95912921eb3a8431ad576c5fd4499e520f83/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js with the following.

This would allow overriding ApiGatewayStage with anything in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html including the logging configurations.

```js
    _.merge(this.serverless.service.provider.compiledCloudFormationTemplate.Resources, {
      [this.apiGatewayDeploymentLogicalId]: {
        Type: 'AWS::ApiGateway::Deployment',
        Properties: {
          RestApiId: this.provider.getApiGatewayRestApiId(),
          StageName: this.provider.getStage(),
          Description: this.provider.getApiGatewayDescription(),
        },
        DependsOn: this.apiGatewayMethodLogicalIds,
      },
      ApiGatewayStage: {
        Type: 'AWS::ApiGateway::Stage',
        Properties: {
          StageName: this.provider.getStage(),
          RestApiId: {
            Ref: 'ApiGatewayRestApi'
          },
          DeploymentId: {
            Ref: this.apiGatewayDeploymentLogicalId
          },
        },
        DependsOn: this.apiGatewayDeploymentLogicalId,
      },
    });
```

**Comment by tanduong** [comment]
If I manually added cloudwatch log, redeploy will not undo it, right?

**Comment by jordanboston** [comment]
@tanduong No, I don't think it should.

**Comment by waynerobinson** [comment]
Only if the resource gets replaced. An update shouldn’t remove the config.

**Comment by duro** [comment]
Any update here?

**Comment by camhart** [comment]
@waynerobinson @tanduong I'm finding that it does NOW undo it when I redeploy.  Not sure what's changed.

**Comment by rjamesnw** [comment]
I noticed the same thing. A deployment clears the log setting so CloudWatch is no longer enabled for the API; so annoying.

**Comment by arthurmf** [comment]
Any news on this issue?

**Comment by syzhakov** [comment]
Any update about this one?

**Comment by ahummel25** [comment]
Any way to fix this error after enabling API GW logs:

```
CloudWatch Logs role ARN must be set in account settings to enable logging
```


```yml
logs:
  restApi:
    accessLogging: true
    executionLogging: true
    role: 'arn:aws:iam::#{AWS::AccountId}:role/${self:custom.commonPrefix}-apigw-role'
    roleManagedExternally: true
```
