### ISSUE TITLE
Disabling SNI on API gateway

### ISSUE THREAD

**Issue by achadee** [serverless/serverless#4462]
I know this isn't the place to probably post this, but I'm hoping some AWS guru might be able to shed some light onto this.

I currently have a lambda integration with Ebay which does not support SNI (server name indication). I was wondering what YML settings I might have to add to disable this. API gateway enables this by default using cloudfront. 

Im not sure if I tweak settings in the AWS console that they will be overwritten the next time I deploy the function

Any help or links that point me in the right direction would be much appreciated

**Comment by gaurav-narra** [comment]
aws api gateway sits behind the cloud front and you would need to pass in the server name for it to work.
I had similar problem, we where resolving the server name to ip and calling using the ip which was failing, solution was to pass the server name with the request.

**Comment by horike37** [comment]
Thanks @achadee for posting your problem :+1: 
However, your question would not the range of Serverless Framework.

You might want to post it to AWS support.
Closing for now.
