### ISSUE TITLE
serverless deploy fails after adding properties to a lambda event stream

### ISSUE THREAD

**Issue by dylanhillier** [serverless/serverless#4471]
# This is a Bug Report

## Description

I have a serverless.yml file which defines a lambda function which fires based on kinesis stream events. This would successfully deploy when running `sls deploy`.  An example snippet of this is shown below.

```
...
functions:
  whos-got-the-func:
    handler: handler.WhosGotTheFunc
    timeout: 60
    environment:
      ...
    events:
      - stream:
          type: kinesis
          arn:
            Fn::ImportValue: ${env:KINESIS_FUNC_UPDATE}
...
```

If i then add some additional properties to the kinesis stream event, such as a `batchSize`, `startingPosition` and `enabled` then the `sls deploy` fails. Example of the changes shown below:
```
...
functions:
  whos-got-the-func:
    handler: handler.WhosGotTheFunc
    timeout: 60
    environment:
      ...
    events:
      - stream:
          type: kinesis
          arn:
            Fn::ImportValue: ${env:KINESIS_FUNC_UPDATE}
          batchSize: 100
          startingPosition: LATEST
          enabled: true
...
```

The error message output is as follows:

```
11:54:20.545 sls deploy -v
11:54:21.828 
11:54:21.846 Serverless: Updating Log Forwarding Resources...
11:54:21.847 Serverless: Log Forwarding Resources Updated
11:54:21.853 Serverless: Packaging service...
11:54:22.695 Serverless: Uploading CloudFormation file to S3...
11:54:22.810 Serverless: Uploading artifacts...
11:54:23.427 Serverless: Validating template...
11:54:24.206 Serverless: Updating Stack...
11:54:25.480 Serverless: Checking Stack update progress...
11:54:30.742 CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - MyCloudStack
11:55:02.387 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - whos-got-the-func
11:55:02.387 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - i-got-the-func
11:55:02.387 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - you-got-the-func
11:55:02.387 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - i-got-the-func
11:55:02.387 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - whos-got-the-func
11:55:02.387 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - we-got-the-func
11:55:02.387 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - shes-got-the-func
11:55:02.387 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - you-got-the-func
11:55:02.388 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - we-got-the-func
11:55:02.388 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - shes-got-the-func
11:55:07.633 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::EventSourceMapping - WhosGotTheFuncEvenSourceMappingKinesisABCDUpdateKinesisArn
11:55:07.633 CloudFormation - UPDATE_FAILED - AWS::Lambda::EventSourceMapping - WhosGotTheFuncEvenSourceMappingKinesisABCDUpdateKinesisArn
11:55:12.857 CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - MyCloudStack
11:55:18.107 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - i-got-the-func
11:55:18.107 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - whos-got-the-func
11:55:18.107 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - shes-got-the-func
11:55:18.108 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - we-got-the-func
11:55:18.108 CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - you-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - whos-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - i-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - shes-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - you-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - we-got-the-func
11:55:18.108 CloudFormation - UPDATE_COMPLETE - AWS::Lambda::EventSourceMapping - WhosGotTheFuncEvenSourceMappingKinesisABCDUpdateKinesisArn
11:55:28.582 CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - MyCloudStack
11:55:28.582 CloudFormation - DELETE_COMPLETE - AWS::Lambda::EventSourceMapping - WhosGotTheFuncEvenSourceMappingKinesisABCDUpdateKinesisArn
11:55:28.582 CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - MyCloudStack
11:55:28.583 Serverless: Operation failed!
11:55:28.587 
11:55:28.588   Serverless Error ---------------------------------------
11:55:28.588 
11:55:28.588   An error occurred: WhosGotTheFuncEvenSourceMappingKinesisABCDUpdateKinesisArn - 
The event source arn (arn:aws:kinesis:ap-southeast-2:6969696969:stream/Update-Kinesis)  
and function (MyCloudStack-whos-got-the-func) provided mapping already exists. 
Please update or delete the existing mapping with UUID 666666-7777-8888-9999-000000000000.
11:55:28.588 
11:55:28.588   Get Support --------------------------------------------
11:55:28.588      Docs:          docs.serverless.com
11:55:28.589      Bugs:          github.com/serverless/serverless/issues
11:55:28.589      Forums:        forum.serverless.com
11:55:28.589      Chat:          gitter.im/serverless/serverless
11:55:28.589 
11:55:28.589   Your Environment Information -----------------------------
11:55:28.589      OS:                     linux
11:55:28.589      Node Version:           6.11.3
11:55:28.589      Serverless Version:     1.22.0
11:55:28.589 
11:55:28.596 make: *** [_deploy] Error 1
11:55:30.069 make: *** [deploy] Error 2
11:55:30.078 [go] Current job status: failed.
```

To solve this problem you need to manually remove the existing/previous trigger from the lambda function via the console. However, the behaviour i would expect here is that the deploy succeeds overriding the initial trigger but just defining the additional properties. Ie. no manual intervention required.

**Comment by mrowles** [comment]
For those wondering how to do this manually: 
1. Go to AWS Console > Services > Lambda
2. Select function in question
3. In the Configuration Designer, the DynamoDB trigger will be on the left
4. Click the 'X' & 'Save'
5. Redeploying your serverless stack should now work

**Comment by OscarGalindo** [comment]
Well... that's a bit awkard...

My function was deleted so I need to create a new one, delete the mapped trigger and the delete the function again ^^ 

Amazing..

**Comment by gnomezgrave** [comment]
@OscarGalindo : Your solution worked for me. Thanks.

**Comment by evanderkoogh** [comment]
The workaround of creating a new function with the same name just to delete the mapping did work for me too. But it would indeed be very good if serverless did the right thing in the first place.

**Comment by emmanuelnk** [comment]
As mentioned earlier, if you're serverless deploy is failing because a source mapping already exists, just go to the lambda function's console and delete the problematic trigger on the left. Then re-deploy. It should work.

**Comment by pmuens** [comment]
Closing since this issue is quite stale and we've pushed some changes in the past. Furthermore one can find some workarounds in this thread.

Feel free to conitnue the discussion...

**Comment by ian** [comment]
Confirmed this is still happening in 1.40.0, please reopen.

**Comment by ian** [comment]
The expected behavior is that `serverless` corrects the erroneous binding (removes then readds).

This is pretty easy to reproduce, just deploy a simple example like https://github.com/DavidWells/serverless-workshop/tree/master/lessons-code-complete/events/kinesis/kinesis-basic and then go to CloudFormation and delete the stack.  Make sure it's deleted and then re-deploy.  It errors 100% of the time for me.

**Comment by apoorvavinod** [comment]
Possible work-around through aws-cli:
`aws lambda delete-event-source-mapping --uuid <UUID from error message>`

**Comment by stevesuh** [comment]
Can we reopen this?  It's makes the event mapping worthless via Serverless.com.

**Comment by nocon** [comment]
Please consider reopening. Manual or even scripted workarounds make serverless much less of an interesting proposition for managing lambda infrastructure. If you handle creation of mappings via config, you automatically create expectation of being able to handle the updates, too.

**Comment by bradacina** [comment]
please reopen

**Comment by LEscobar-Driver** [comment]
Attempting to deploy a lambda function with an sqs trigger 

    An event source mapping with SQS arn (" arn:aws:sqs:us-west-2:xxxxxxxx:lambda-stack-test-MyQueue-xxxxxxx ") and function (" lambda-stack-test-LambdaStackFunction-xxxxxxx ") already exists. lease update or delete the existing mapping with UUID xxxxxxxxxx



`aws lambda delete-event-source-mapping --uuid <UUID from error message>`

yields 

`An error occurred (ResourceNotFoundException) when calling the DeleteEventSourceMapping operation: The resource you requested does not exist.`

Ridiculous

**Comment by RampantLions** [comment]
Since this issue still exists, I appreciate the (manual) workaround, but long-term requiring manual effort for CloudFormation and Serverless templates is anti-thetical to the purporse of these services.
Not addressing this customer impacting root cause really is not acceptable (not sure why this was ever closed). Please reopen.

**Comment by 75lb** [comment]
i just lost hours of my life trying to understand, debug and fix this issue.. thanks to @OscarGalindo for the workaround. I don't use Serverless myself but had the same issue using AWS Lambda and SAM/Cloudformation directly.

**Comment by kinan-ellevation** [comment]
Are there any plans to fix this issue? Requiring the manual deletion of event source triggers for Lambda functions before re-deploying using serverless framework is not an attractive proposition.

**Comment by TABTheoBreuerWeil** [comment]
This problem is making it hard for us to deploy code into our production environment - would be great if this issue were re-opened!

**Comment by nojohnny101** [comment]
We are also facing this for deployments with SAM/Cloudformation. Thanks to @OscarGalindo I would have never found the solution.

**Comment by isgallagher** [comment]
We are also having an issue with this.  The kinesis event on the lambda was deleted and recreated.  Now we are getting the same error.  Not sure how to handle it yet, but this bug definitely needs reopened.

**Comment by PatrykMilewski** [comment]
The same problem here, we cannot update stack with DynamoDB event source mapping

**Comment by nojohnny101** [comment]
FYI we solved this by being more diligent in specifying the "DependsOn" field where appropriate. After establishing proper relationships between our resources, this problem never appeared again.

**Comment by Aposhian** [comment]
> FYI we solved this by being more diligent in specifying the "DependsOn" field where appropriate. After establishing proper relationships between our resources, this problem never appeared again.

@nojohnny101 Could you be a little more specific about what you did? It appears that Serverless declares the EventSourceMapping to depend on the IamRoleLambdaExecution only.

**Comment by Aposhian** [comment]
This doesn't seem to be a serverless issue as much as an issue with CloudFormation. It appears that serverless is generating the EventSourceMapping correctly according to the [Cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html):

    "MyLambdaFunctionEventSourceMappingDynamodbMyTable": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
      "Properties": {
        "BatchSize": 50,
        "EventSourceArn": {
          "Fn::GetAtt": [
            "MyTable",
            "StreamArn"
          ]
        },
        "FunctionName": {
          "Fn::GetAtt": [
            "MyLambdaFunction",
            "Arn"
          ]
        },
        "StartingPosition": "LATEST",
        "Enabled": "True",
        "MaximumBatchingWindowInSeconds": 60,
        "MaximumRetryAttempts": 2
      }
    }

[This issue](https://github.com/serverless/serverless/issues/7236) also mentions that this is a known issue with cloudformation currently.

**Comment by nojohnny101** [comment]
@Aposhian Just to be clear, we are not using Serverless per say but I came across this post when researching a very similar error in our CloudFormation deploy process. So I agree with you, it was/is a CloudFormation bug, not specific to serverless.

Unfortunately his was a while ago and I can't remember with what specific resources we were facing a problem with but as I stated previously, are you properly specifying "dependson" conditions in your template? Since we have applied that, this problem as not resurfaced.

**Comment by JessicaBarclay** [comment]
Another workaround is to delete the mapping in the command line via the aws-cli. This worked for me:
```
aws lambda delete-event-source-mapping --uuid abc123-def456-xyz-987-11111EXAMPLE
```
Docs:
https://docs.aws.amazon.com/cli/latest/reference/lambda/delete-event-source-mapping.html

Make sure you've got your credentials set up to use the aws-cli for your OS:
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

**Comment by marksiano** [comment]
Why closed? This is still an issue

**Comment by Fiiii** [comment]
I faced with the similar issue:
`
Rate exceeded for operation 'EventSourceMappingDynamodb Rate exceeded (Service: Lambda, Status Code: 429)
`

With deploying 2x functions based on streams :/

**Comment by chuck-g** [comment]
@pmuens Care to weigh in again after all the request to re-open this issue?

**Comment by EdanSneh** [comment]
still happening 👎

**Comment by dls314** [comment]
Leaving breadcrumbs :-)

I've seen this issue when there was no actual change to the event source mapping, but the syntax of the template changed around the use of `Fn::GetAtt` from the short-form with dot-notation to the long form with array notation. This was for an SQS event source mapping.

**Comment by MatteoGioioso** [comment]
In our case the stack went in `UPDATE_ROLLBACK_FAILED` 🤦 . 
Someone could please confirm if this is a serverless framework or cloudformation bug? I would like to establish the root cause of this problem, thanks.

**Comment by MatteoGioioso** [comment]
This error appear also with the latest version of serverless framework:

```

  ServerlessError: An error occurred: BuggedFunctionEventSourceMappingKinesisBuggedKinesis - The event source arn (" arn:aws:kinesis:ap-southeast-1:000000000:stream/buggedKinesis ") and function (" sls-event-source-mapping-bug-dev-buggedFunction ") provided mapping already exists. Please update or delete the existing mapping with UUID 63d82040-db27-4ae2-a58b-12e0a2700945 (Service: Lambda, Status Code: 409, Request ID: 2626ce4d-4ce4-4c27-998c-bb223e6d141e, Extended Request ID: null).
      at /Users/user/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:99:23
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at /Users/user/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.11.0
     Framework Version:         2.12.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2
```

I have created a repro: https://github.com/MatteoGioioso/sls-event-source-mapping-bug
Could we please re-open?

**Comment by medikoo** [comment]
Let's move all the discussion to https://github.com/serverless/serverless/issues/8550 which has a reproducible test case against latest Framework version.

This issue was opened 3 years ago, when our internals were different, so I consider it out of date
