### ISSUE TITLE
Support openwhisk java runtime

### ISSUE THREAD

**Issue by junoyoon** [serverless/serverless#4491]
# This is a (Feature Proposal)

## Description

Openwhisk supports [java runtime](https://github.com/apache/incubator-openwhisk-runtime-java).
However there is no openwhisk java runtime template in serverless framework.
It's necessary to add openwhisk-java-gradle here and make serverless-openwisk support java runtime
the usecase is like following.

```
serverless create --template openwhisk-java-gradle --path my-service
```

**Comment by horike37** [comment]
Thank you for your suggestion @junoyoon  :+1: 
That's a good idea. We can introduce any new templates which are related to supporting providers to the framework core without any discussions :100: 

You might want to send a pull request for that if you have skills and hope to do that.
We are always welcome and can help you :smile:

**Comment by kameshsampath** [comment]
@horike37  - wondering this might help https://github.com/serverless/serverless/pull/4758
