### ISSUE TITLE
Remove redundant keywords from aws-scala-sbt handler template 

### ISSUE THREAD

**Issue by girichards** [serverless/serverless#4502]
# This is a Bug Report

## Description

I hope to make my first simple contribution to the project. There are some redundant keywords that can be removed from the `aws-scala-sbt` template.

In the file [`lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala`](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala#L9)

the following function in the `Handler` class
```
	def handleRequest(input: Request, context: Context): Response = {
		return new Response("Go Serverless v1.0! Your function executed successfully!", input)
	}
```
 the `return new` keywords are redundant and can be removed

`Response` is a case class, so we don't need to use `new` to construct it. `Response` is the last unassigned value, so will automatically be returned without the need for the `return` keyword.

The function can be rewritten as
```
	def handleRequest(input: Request, context: Context): Response = {
		Response("Go Serverless v1.0! Your function executed successfully!", input)
	}

```
In the same file, the `ApiGatewayHandler` class has a handler function already written in this way

```
  def handleRequest(input: Request, context: Context): ApiGatewayResponse = {
    val headers = Map("x-custom-response-header" -> "my custom response header value")
    ApiGatewayResponse(200, "Go Serverless v1.0! Your function executed successfully!",
      JavaConverters.mapAsJavaMap[String, Object](headers),
      true)
  }
```

The 
For bug reports:
* What went wrong?
redundant keywords in template
* What did you expect should have happened?
* What was the config you used?

> template: aws-scala-sbt
> runtime: java8
> provider: aws

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Creating boilerplate Serverless Scala Sbt project for AWS
 `sls create --template aws-scala-sbt`
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Ubuntu 16.04
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for your first awesome contribution :+1: :100: 
Your help always goes ahead the framework project :tada: 
>Response is a case class, so we don't need to use new to construct it. Response is the last >unassigned value, so will automatically be returned without the need for the return keyword.

Looks like reasonable. Is it possible to send a pull request with your improvement?
If you can do that, we can review it and introduce the framework core.

Let us know if you have any question or problem :smile:

**Comment by girichards** [comment]
Thanks! PR #4505  created
