### ISSUE TITLE
~/.aws/credentials created on npm install (even if we do not rely on AWS)

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#4506]
# This is a Bug Report

After introduction of  #3866 due to [`ensureFileSync`](https://github.com/serverless/serverless/blob/192f80ccf4a0cdb1f062a1986be570f605829e74/lib/plugins/aws/configCredentials/awsConfigCredentials.js#L57-L58) run  in plugin constructor, the `~/.aws/credentials` file creation attempt is pursued on every SLS command, and also when serverless is installed due to [`serverless.init()`](https://github.com/serverless/serverless/blob/192f80ccf4a0cdb1f062a1986be570f605829e74/scripts/postinstall.js#L14) invoked in `scripts/postinstall.js`

It also happens when serverless is not intended to be used with AWS, therefore I believe it's a bug.

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: 10.12.6
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
@medikoo , thanks for reporting this 👍 . The creation of AWS related files indeed should take place during the execution of an AWS plugin, but never in it's constructor, as that will affect all providers.

I see the location of the implementation as simply wrong. Plugin constructors should only establish hooks and commands, but never execute anything related to a specific provider. That makes sure that the provider dependent stuff is only done, when the provider that is targeted by the plugin is actually invoked and used.
