### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by RafalWilinski** [serverless/serverless#4507]
# This is a Feature Proposal

## Description

AWS Lambda now supports Golang: https://twitter.com/mthenw/status/936302935478358016
We should add `aws-golang` template.

**Comment by horike37** [comment]
It was pre-announcement at re-invent. We should wait for the official release a couple of weeks.

**Comment by horike37** [comment]
Finally!
https://aws.amazon.com/jp/about-aws/whats-new/2018/01/aws-lambda-supports-go/

**Comment by yunspace** [comment]
I can spend some time looking at this and potentially consolidate of the things I've been doing in https://github.com/yunspace/serverless-golang into the official repo. Happy to collaborate on this if anyone has already started

**Comment by horike37** [comment]
AWESOME @yunspace :100: Thank you for jumping in !!!
I know your plugin :smile: That is one of the most popular plugins of the framework!

AFAIK, nobody started working on this, so it would be great if you can do that :smile: 
To introduce this new feature, we need to implement the following stuff.
1. Specify golang runtime to CloudFormation template generated by the framework.
2. Add golang template when running `sls create --template aws-golang`.
3. Add test template with docker-compose.
4. Add it to the framework documentation.

Additionally, we need local invoke functionality as well, but it would be good to separate another issue.

You can refer to the past PR for introducing other templates something like this
https://github.com/serverless/serverless/pull/3483/
https://github.com/serverless/serverless/pull/3849/

Let us (@serverless/framework-maintainers) know if you have any other questions!

**Comment by flemay** [comment]
Looking at the documentation [Lambda Handler in Go](https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-handler-types.html) , it seems the `handler.go` would only be for 1 lambda (1 `main()` function to start the lambda) so I was wondering how would Serverless use the same code for more than 1 function. 🤔

**Comment by HyperBrain** [comment]
@flemay Opposed to other languages, Go exports a main() function as entry point for the executable - so it should be one executable per handler, which is perfectly fine.
I see code sharing here on a Go library level. If you want to share code, create multiple libraries and import them into your handlers.

**Comment by franciscocpg** [comment]
right @HyperBrain  :+1: 
But in this case this also means that we need one folder per handler.

**Comment by HyperBrain** [comment]
@franciscocpg That should be easy to achieve. If the runtime is "go", it should be disallowed to specify handlers without a relative path in the `serverless.yml`.

```yaml
# serverless.yml
functions:
  okfunc:
    handler: myfunc/handler
  invalidfunc:
    handler: handler
```

Does that sound feasible?

**Comment by flemay** [comment]
So I've tried with 1 function only with different approaches: in folder, not in folder
Also tried with handler executable matching the name of the function generated by serverless i.e `myproject-stage-functionname` because according to AWS doc

> Note that your function-name must match the name of your Lambda handler name

So I've got errors similar to the following

```
{
    "errorMessage": "fork/exec /var/task/myproject-dev-handler: no such file or directory",
    "errorType": "PathError"
}
```

**Comment by flemay** [comment]
I got it working! Thanks to this [serverless blog](https://serverless.com/blog/framework-example-golang-lambda-support/)

**Comment by joekr** [comment]
In order to get `serverless create -u https://github.com/serverless/serverless-golang/ -p myservice` to work from the blog post I had to do a few things first:

1. run `npm install -g serverless` to upgrade to `serverless@1.25.0`
2. run `go get github.com/aws/aws-lambda-go/lambda` before running `GOOS=linux go build -o bin/main`

Thought this might help some others out.

**Comment by yunspace** [comment]
thanks @flemay for the good find. Following @mthenw's template makes things a lot easier. I should be able to get a draft PR in by end of the day.

**Comment by yunspace** [comment]
smashed out PR #4669 on a 4 hour bus ride to Canberra... should be ready soon!
