### ISSUE TITLE
CloudFormation Stack Validation

### ISSUE THREAD

**Issue by laardee** [serverless/serverless#4511]
# This is a Feature Proposal
To avoid unsuccessful deployments, validating the Cloudformation template would be useful before deploying the generated stack to AWS. There may be typos or similar syntax errors in CF resources etc., which leads to an unsuccessful deployment. These cases could be tackled with pre-deploy validation.

Validation could be invoked with e.g. `sls validate` or `sls validate stack` command. 
Or as a part of the deployment process. Maybe with optional flag `sls deploy --validate`? 

The validation takes few moments, but the time that is saved when deploying valid stack vs. time spend waiting e.g. CloudFront to rollback, could be worth it.

Similar or dependent issues:
* #4179

## Additional Data
There was some discussion about this in the Serverless Contributors Slack earlier today. Is this something that could be core feature or would a plugin be a better option?

**Comment by HyperBrain** [comment]
Hi @laardee ,

thanks for the proposal. Serverless currently does a template validation before deploying the template.
The template is checked by CF with the validateTemplate API function and any errors are reported.

**Comment by laardee** [comment]
Oh yes, so it does. It was obviously too late last night when I opened this issue.

**Comment by dashmug** [comment]
@HyperBrain Can we validate without deploying?

**Comment by ebisbe** [comment]
As @dashmug suggested, Is this option available @HyperBrain ? In my particular case I deploy from commits so if I could validate the template before make the commit would improve my CI process.

**Comment by tribet84** [comment]
This command does the job @dashmug @laardee :
```
sls deploy --noDeploy --stage dev --region ap-southeast-2 
```

Found [here](https://nellysattari.ghost.io/validate-serverless-yml-firl-for-lambda-aws-before-deployment/)

**Comment by eldos-dl** [comment]
@tribet84 
The suggested command is not validating the entire template. For example, it seems to not validate things defined in `resources` section.

**Comment by joffarex** [comment]
I don't really see a point of not implementing this for on demand usage. I mean if API already exists... 

This would've been really useful feature. 
For example, you might have set up CI/CD pipeline which deploys serverless application, and also AWS is set up in a way that only that pipeline can deploy things, that means, if i have some mistake in my serverless.yml file which does not get caught by `sls deploy --noDeploy` command, i will have to trigger that pipeline on every error I've got in my yml file.

**Comment by Colstuwjx** [comment]
Agree with @0xtoko, I really need this feature! Since we do have `--noDeploy` option, how about make it fully support aws cloudformation template? Is there any problem that we need to resolve?
