### ISSUE TITLE
Bug: Tags do not update

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4513]
Lambda specific tags as defined in https://github.com/serverless/serverless/pull/3548 do not update when re-deploying existing function.

Mentioned as a deficit in https://github.com/serverless/serverless/pull/3548#issuecomment-323970128.

**Comment by horike37** [comment]
Thanks @simlu opening up :+1: 
Did you use `sls function deploy` when  re-deploying?
`sls function deploy` deploy only a source code but not a configuration, so specific tags are not updated.

**Comment by simlu** [comment]
I've used 'sls deploy - - stage=...'

Should I have used a different command?

**Comment by simlu** [comment]
This was a problem with how I declared tags. I prefixed the tags with dashes and that didn't get picked up.
