### ISSUE TITLE
Add maxAge option for CORS preflight requests in API Gateway

### ISSUE THREAD

**Issue by pshendry** [serverless/serverless#4517]
# This is a Feature Proposal

## Description

As a developer using CORS for cross-origin usage of my API, I don't want the extra latency that results from CORS preflight requests happening all the time. I'd like to be able to configure Serverless to set the `Access-Control-Max-Age` header on preflight responses so that they may be cached for as long as the browser will allow.

Some background on the topic:

Serverless Framework has [CORS support](https://serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors) for controlling access to resources on different origins. Under CORS, non-simple requests can't be made until a "preflight request" is made to check if CORS rules permit the original request; it's an OPTIONS query and the response has a bunch of "Access-Control-*" headers which describe the rules. One of these headers that can be returned from these preflight requests is `Access-Control-Max-Age`: this defines the time in seconds that the results of a preflight request may be cached. Browsers cut this off at varying points (24hrs for Firefox, 10min for Chrome AFAIK), but one preflight request every 10 minutes is substantially better than the default.

To implement, `serverless.yml` would need a `maxAge` option in the `cors` section, like this:

```
cors:
  origin: 'https://mydomain.com'
  maxAge: 86400
  headers:
    - Authorization
    - Content-Type
```

and the corresponding implementation [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js#L25) would need to conditionally set the `Access-Control-Max-Age` setting based on that value.

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Solus
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by HyperBrain** [comment]
@pshendry Good catch 👍 . I agree that SLS should support the `max-age` header on CORS preflight calls.
