### ISSUE TITLE
can't invoke scala locally

### ISSUE THREAD

**Issue by zydeco** [serverless/serverless#4526]
# This is a Bug Report

## Description

* What went wrong? Function was not invoked
* What did you expect should have happened? Function was invoked
* What was the config you used? newly generated project from aws-scala-sbt template
* What stacktrace or error message from your provider did you see? n/a

Similar or dependent issues:
#2864 

## Additional Data

This happens because the handler takes an object as input, but InvokeBridge is trying to call it with a `Map<String,Object>` (AWS supports [other types](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html) too).
I'm working on a patch that will instantiate the object and set its properties via reflection using java beans.

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: macOS 10.13.1 (17B1003)
* ***Stack Trace***:
```
~/D/I/s/aws-scala-sbt ❯ sls invoke local -f hello
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
java.lang.IllegalArgumentException: argument type mismatch

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:61)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:32)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:86)
```

**Comment by RafalWilinski** [comment]
Thank you for reporting this bug @zydeco! 💯 

Glad that you're willing to fix it. Shoot me questions if anything is unclear. I'm not Java pro but I might help with SLS internals.
