### ISSUE TITLE
Confirm project name change at creation if theres a folder colision

### ISSUE THREAD

**Issue by DoWhileGeek** [serverless/serverless#453]
If you are attempting to create a new project `foobar`, but already have a directory called `foobar`, serverless will automatically create the project as `foobarSOME_UNIQUE_ID` locally, and on aws. I think a simple "are you sure you want to create this project with a compromised project name?" dialogue should be implemented, if not just throwing an exception and breaking out of the creation.

**Comment by DoWhileGeek** [comment]
@eahefnawy It would be nice if you explained why you're closing an issue, so those involved are not left in the dark.

**Comment by eahefnawy** [comment]
@DoWhileGeek oh really sorry! I just close outdated/inactive issues to keep our backlog clean :) ... Your feedback is always appreciated :blush:
