### ISSUE TITLE
Documentation on SLS_DEBUG=*

### ISSUE THREAD

**Issue by AlecBenzer** [serverless/serverless#4540]
https://github.com/serverless/serverless/blob/cb822ad505d817ee6230e0d149bc85177f6ac808/lib/classes/Error.js#L51

Running `SLS_DEBUG=*` in (some versions of?) bash sets `SLS_DEBUG` to the contents of the current directory:

```shell
$ ls
bar     baz     foo
$ SLS_DEBUG=*
$ echo $SLS_DEBUG
bar baz foo
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Since it seems like serverless only checks for the presence of the environment variable and not its contents, this should be fine, but seems kind of odd/maybe confusing. It also might cause an issue if run in an empty directory.

Should documentation be modified to suggest doing `SLS_DEBUG="*"` or `SLS_DEBUG=1`?

**Comment by HyperBrain** [comment]
Hey @AlecBenzer , good catch 👍 .

You're right. Right now the variable is only checked for its presence (and the shell glob will make it exist ;-) regardless of its then present value).
I'm not sure why exactly the asterisk was chosen as value that is documented everywhere - maybe just noone thought about the implications when using it in a shell that resolves wildcards for the file system entries.
If the value will later be used to determine the scope of the logging by plugins, like `SLS_DEBUG="AWSDeploy, AWSPackage"` your proposal `SLS_DEBUG="*"` to mean "log everything" makes more sense than the numerical value. Imo a selective approach is in the Serverless framework better than a level approach.
So we should adjust the documentation and add the quotes around the asterisk.

**Comment by Fourfingerz** [comment]
Hello folks! I'm new to open source contributions and use SLS_DEBUG quite often in Serverless and was wondering if I can help with appending to these docs for debug.

**Comment by HyperBrain** [comment]
Hi @Fourfingerz , thanks for asking 😄 . Of course you can provide a PR that extends the documentation, highly appreciated. You should check the docs for the other providers (in the `./docs` directory) too, because some of the generic documentation is replicated there.

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
