### ISSUE TITLE
Create Resource with random string postfix (like deployment bucket)

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4550]
How can I access the random string that serverless uses to create the deployment bucket and use it in the name for a resource that I create in the serverless.yml?

I'm pretty sure the random post fix is the physical stack id of the cloud formation stack. However I had no luck accessing it with e.g. ${cf:PysicalStackId}. 

Is this possible? What do other people do? Goal is to create a bucket and to prevent collision.

**Comment by simlu** [comment]
Reference to things I found:
- https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs
- https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L343

**Comment by HyperBrain** [comment]
Hi @simlu , good question 👍 .

My feature request #4542 addresses the problem of referencing the automatically generated names that the Serverless framework creates. With that, it will be possible to reference these with Serverless variables in any part of the `serverless.yml`.
Right now, it is only possible to retrieve the value of an existing stack output with the `${cf:...}` reference variable. Of course this leads to problems when trying to reference the service's own stack...

**Comment by simlu** [comment]
I like your pr a lot! However I'm not sure it would allow me to solve the issue of getting the physical stack id? Or is that not correct?

Clearly the information is available in sls internally, but not exposed. I'm not very familiar with the different syntax and conventions of accessing variables. So how would we best expose this?

**Comment by pmuens** [comment]
Closing since this is an old issue and the issue thread includes some answers / cross-references to other issues.

**Comment by simlu** [comment]
Never solved this unfortunately. But yeah it's an old issue ;)

**Comment by serverlesspolska** [comment]
But still valid

**Comment by jonathan-kosgei** [comment]
Could it be the same id exposed via `${sls:instanceId}`?

```
service: new-service
provider: aws

functions:
  func1:
    name: function-1
    handler: handler.func1
    environment:
      APIG_DEPLOYMENT_ID: ApiGatewayDeployment${sls:instanceId}
```

**Comment by thenickdude** [comment]
No, since instanceId changes every time deploy is called.

**Comment by alvincrisuy** [comment]
Hope this can be implemented
