### ISSUE TITLE
aws-nodejs-typescript template should utilize @types/aws-lambda

### ISSUE THREAD

**Issue by jamestharpe** [serverless/serverless#4551]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Similar to other strongly typed languages (e.g. Java, C#), the TypeScript template should use TypeScript's strong typing features by adding `@types/aws-lambda` as a dev dependency and utilizing the defined types in `handler.ts` so that the TS compiler and IDEs can better validate the code and provide additional features (e.g. code completion).

* If there is additional config how would it look

In `tsconfig.json` under `compilerOptions` (per the [aws-sdk-js documentation](https://github.com/aws/aws-sdk-js#usage-with-typescript)):

```json
    "lib": [
      "es5",
      "es2015.promise"
    ]
```
In `package.json`:

```json
"devDependencies": {
    "@types/aws-lambda": "0.0.22",
...
```

Similar or dependent issues:
* None

## Additional Data

None

**Comment by HyperBrain** [comment]
@jamestharpe I am a bit confused.... wasn't this handled in #4546 ?

**Comment by jamestharpe** [comment]
@HyperBrain No, that added Node types. This adds AWS Lambda types. I'd have combined them, but I'm only working 1-2 hours/day on this hobby project of mine, sorry! :-)

**Comment by HyperBrain** [comment]
Sorry for the confusion, that's fully ok ;-)
