### ISSUE TITLE
SNS gets deleted

### ISSUE THREAD

**Issue by agandhinit** [serverless/serverless#4553]
# This is a Bug Report

## Description

* What went wrong? - I have a lambda which i deploy, It refers to a SNS which is created during the deployment. In this lambda i create the SNS through serverless. The lambda and the SNS both  belong to the same stack.
Now i deploy another lambda which uses the same SNS, however now I refer to the SNS as an existing topic providing arn. During this deployment serverless deletes the topic.
SNS gets deleted with deployment
* What did you expect should have happened? - The SNS stays intact.
* What was the config you used? Providing the config for the second lambda - 

`

    step-trigger:

      handler: lambdas/stepfn-trigger/index.handler

      memorySize: 1536

      timeout: 30

      events:

        - sns:

           arn: arn:aws:sns:us-east-1:12323223232:recordingassets

           topicName: recordingassets

           displayName: recordingassets

`

**Comment by horike37** [comment]
Hi @agandhinit. Thank you for reporting.

Let us confirm what happens on your end.
- You have the deployment which creates lambda and SNS. We call that the first deployment
- You have the other deployment creates lambda and refers to the existing SNS at the first one. We call that the second deployment

Currently, do you mean that the SNS topic at the first deployment is deleted accidentally when you remove the second deployment via `sls remove`?

**Comment by agandhinit** [comment]
The SNS topic gets removed once i do a `sls deploy` on second lambda

**Comment by pmuens** [comment]
Closing this issue since it's quite stale and we've fixed a couple of issue related to that in the past. Feel free to re-open if this is still a problem.
