### ISSUE TITLE
Step function deployment updates code for running executions

### ISSUE THREAD

**Issue by agandhinit** [serverless/serverless#4554]
# This is a Bug Report

## Description

* What went wrong? I deployed a step functions with lambdas for the step. Whenever i make code changes to the lambda and deploy my step, already running executions pick the latest code. Causing those executions to fail. This could cause production failures on each deployment.
* What did you expect should have happened? 
Running executions should pick old code and not the recently deployed code. New executions should pick latest code.

**Comment by horike37** [comment]
Hi, thank you for reporting @agandhinit :+1: 
Are you using Serverless Step Functions plugins? If so, could you please open up an issue on https://github.com/horike37/serverless-step-functions/issues since the step functions functionality is provided by the external plugin?
