### ISSUE TITLE
Impossible to create plugins that depend on event flow but are asynchronous

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#4557]
Take the following example plugin:

```
'use strict'

class SubstituteCertificateValid {
  constructor(serverless) {
    this.serverless = serverless
    
    this.provider = this.serverless.getProvider('aws')
    
    this.log = this.log.bind(this)
    this.beforeWritingCfTemplate = this.beforeWritingCfTemplate.bind(this)
    
    this.hooks = {
      'before:aws:package:finalize:saveServiceState': this.beforeWritingCfTemplate
    }
  }
  
  beforeWritingCfTemplate() {
    this.log('before writing cf template')
    
    setTimeout(() => {
      this.log('async logic') // THIS RUNS AFTER THE EVENT WE SUBSCRIBED TO
    }, 1000)
  }
  
  log(msg) {
    this.serverless.cli.log(msg)
  }
}

module.exports = SubstituteCertificateValid
```

This illustrates a very common practice where you need to do something just before `aws:package:finalize:saveServiceState`. Now, whenever you depend on something asynchronous (such as making a AWS SDK call), your code is likely to be executed AFTER the event you subscribed to has already happened.

This makes it impossible to do things like transforming the compiled cloudformation template prior to it being written to disk.

For me this is a critical issue, am hoping there is a quick solution or workaround.

**Comment by tommedema** [comment]
@HyperBrain excellent, thanks!

**Comment by lielran** [comment]
here is an full example if you need async action in the plugin: https://gist.github.com/lielran/31c8e2b7f940539585c9f7b913affa7a

**Comment by s1mrankaur** [comment]
@lielran  Thanks for sharing. I followed your example and have something similar: It looks as follows:

`'use strict';

const AWS = require('aws-sdk');
const BbPromise = require('bluebird');


class ServerlessPlugin {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;
    this.log = this.serverless.cli.log.bind(this);

    this.commands = {};

    this.hooks = {
      //'after:aws:deploy:deploy:updateStack': this.updateVersionToSsm.bind(this)
      'after:deploy:deploy': () => BbPromise.bind(this)
                .then(this.updateVersionToSsm)
    };
  }

  updateVersionToSsm() {
    this.serverless.cli.log('SSM API version: Acquiring info...');
    const { stage, region } = this.options;
    const provider = this.serverless.getProvider('aws');
    const awsCredentials = provider.getCredentials();
    const SSM = new AWS.SSM({
      region,
      credentials: awsCredentials.credentials
    });

    const getSsmParameter = (name) => new Promise((resolve, reject) => {
      var params = {
        Name: name
      };
      SSM.getParameter(params, (err, data) => {
        if (err) {
          this.serverless.cli.log(`get Parameter err is '${err}'`);
          resolve("");
        }
        else {
          this.serverless.cli.log(`get Parameter res is`, JSON.stringify(data));
          resolve(data.Parameter.Value);
        }
      });
    });

    const incrementVersion = (version) => {
      this.serverless.cli.log(`Current version is '${version}'`);
      let currentDate = new Date();
      const year = currentDate.getUTCFullYear()
      const month = currentDate.getUTCMonth()
      const date = currentDate.getUTCDate()
      var newVersion = "".concat(year, ".", month, ".", date, ".", "0")
      this.serverless.cli.log(`Default new version is '${newVersion}'`);
      if (version && (typeof version === 'string' || version instanceof String) && version.includes('.')) {
        let currentVersionArr = version.split('.')
        if (year == currentVersionArr[0] && month == currentVersionArr[1] && date == currentVersionArr[2]) {
          let dayIncrement = parseInt(currentVersionArr[3]) + 1
          newVersion = "".concat(year, ".", month, ".", date, ".", dayIncrement)
          this.serverless.cli.log(`Incremented new version is '${newVersion}'`);
        }
      }
      return newVersion
    }

    const putSsmParameter = (name, value) => new Promise((resolve, reject) => {
      var params = {
        Name: name,
        Type: 'String',
        Value: value,
        Overwrite: true
      };
      this.serverless.cli.log(`Incrementing SSM version`, name, value);
      SSM.putParameter(params, (err, data) => {
        if (err) { reject(err); }
        else { 
          resolve(data);
         }
      });
    });

    const ssmPrefix = (this.serverless.service.custom
      && this.serverless.service.custom.ssmApiVersion
      && this.serverless.service.custom.ssmApiVersion.ssmPrefix)
      ? this.serverless.service.custom.ssmApiVersion.ssmPrefix.replace(/<stage>/g, stage)
      : `/app/${stage}/versions/`;
    const ssmParameterName = ssmPrefix + this.serverless.service.service;

    let promise = BbPromise.fromCallback(cb => {
      getSsmParameter(ssmParameterName)
      .then(value => {
        this.serverless.cli.log(`SSM API version: current version`, value);
        const incrementedVersion = incrementVersion(value.toString())
        this.serverless.cli.log(`SSM API version: Updating new version '${incrementedVersion}' to SSM with key '${ssmParameterName}' at region ${region}`);
        putSsmParameter(ssmParameterName, incrementedVersion);
        cb();
      });
    });
    
    return promise;

  }
}

module.exports = ServerlessPlugin;
`

The plugin updates the value in SSM just fine however, It looks like the framework does not await on the hook but I am returning an awaitable promise as recommended. Thoughts?
