### ISSUE TITLE
Add a new property which specify RetentionInDays with CloudWathcLogs to serverless.yml

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4564]
# This is a (Feature Proposal)

## Description
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Currently, RetentionInDays with CloudWathcLogs is 30 days as default. It can be overridden by writing up a new value within resources section of serverless.yml.
https://serverless.com/framework/docs/providers/aws/guide/resources/#override-aws-cloudformation-resource

However, It's too much hassle to override it every time you add a new function. 
In many cases, it is overridden since 30 days is too long.

My suggestion is creating a new property which you can specify default value for RetentionInDays.

* If there is additional config how would it look

it would be good to something like this within serverless.yml

```
provider
  retentionInDays: 5
```

**Comment by HyperBrain** [comment]
Wonderful idea. However, I would name it
```
provider
  logRetentionInDays: 5
```
with a prepended "log" to make clear that it is for the log streams.

**Comment by horike37** [comment]
Thanks @HyperBrain for the feedback.

>with a prepended "log" to make clear that it is for the log streams.
Yup. that’s better :+1:
