### ISSUE TITLE
Unable to download template from a private repo or an internal path

### ISSUE THREAD

**Issue by ChristopheBougere** [serverless/serverless#4566]
# This is a Feature Proposal

## Description

* When doing a `serverless create`, we can specify a `template-url` to fetch the template from a git repo. However this does not works with private repositories because it only use HTTPS and not SSH. There is no option to specify a local path for the template.
* We could add a new option `--template-path` that would avoid downloading the template from a repo by copying files from the local path. Let me know if that makes sense, I could create a PR to add this feature.

## Additional Data

* ***Serverless Framework Version you're using***: 8.8.0
* ***Operating System***: darwin
* ***Stack Trace***: `HTTPError: Response code 404 (Not Found)`

**Comment by HyperBrain** [comment]
Hi @ChristopheBougere ,

thanks for the feature request. So you have the original use case where you wanted to fetch a template via a git ssh url (`ssh://git@....`) and the follow up use case where you want to read a template source from a local directory?

For me both use cases make sense (the first one in general in a company, the second one rather for a developer working local).
