### ISSUE TITLE
Variables Should Cache Resources as Appropriate for the Variable Type

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#4587]
# This is a Feature Proposal

As per discussion under #4527, it would be appropriate and helpful to provide per-variable-type caching that is semantically grounded in the type of resource being referenced.

## Description

Caching not only of variable values but also assets such as files retrieved from S3 or disk, the results of executing a referenced script, the content of an SSM parameter.  Each of these has different semantics and caching will appropriately mean a different thing and hold different expectations.  For example, a `${self:...}` reference should probably not have any additional caching, since no active loading occurs in populating that variable type.  For scripts on the other hand, it might be that one wants re-execution (or not!) and would want to specify this somehow.

In one sense, this issue is about having a well documented and intentionally selected policy for how to handle multiple references to parts the same underlying resource.  An example might be the variable `${file(path/to/my/file):value1}` and a second `${file(path/to/my/file):value2}` would we really want to load the file multiple times?  What if that file is asynchronously loading auto-incrementing values from a database to provide a version id across the service deployment?  Multiple fetches risk creating an inconsistency in the service.

**Comment by medikoo** [comment]
Closing, as it's solved with new variables resolver which caches resolved values
