### ISSUE TITLE
Adding CognitoUserPool trigger causes two pools to be created ....

### ISSUE THREAD

**Issue by jamesladd** [serverless/serverless#4588]
# This is a Bug Report

## Description
When I add a CognitoUserPool trigger I get two user pools created (with the same name).
One with the trigger and the other with the rest of the definition from my Resources section.

For bug reports:
* What went wrong?
New Cognito Use Pool Created when I have assigned a trigger
* What did you expect should have happened?
Trigger assigned to same pool and not create a new one
* What was the config you used?
  preSignup:
    handler: src/main/js/handler.preSignup
    memorySize: 128
    timeout: 10
    events:
       - cognitoUserPool:
           pool: CognitoUserPool    <-- Using name from Resources section or UserPoolName has same result. 
           trigger: PreSignUp

* What stacktrace or error message from your provider did you see?
None.

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Ubuntu

**Comment by horike37** [comment]
Hi, @jamesladd thank you for reporting :+1: 
Cloud you please share the whole serverless.yml you are using so that we can reproduce it on our end too?

**Comment by kjvenky** [comment]
I am able to replicate this bug.

**Comment by hassankhan** [comment]
Hi all,

The `pool` property you specify under `cognitoUserPool` is just the name of the User Pool. Instructions for overriding the resource correctly [are here](https://serverless.com/framework/docs/providers/aws/events/cognito-user-pool/#overriding-a-generated-user-pool).

**Comment by jamesladd** [comment]
But that results in two pools

**Comment by hassankhan** [comment]
It shouldn't, if you are overriding it correctly. In your example, you've named the user pool `CognitoUserPool`.

Serverless will, by default, prefix those user pools with `CognitoUserPool` as the logical resource ID, which means you need to use `CognitoUserPoolCognitoUserPool` under `Resources` to override it correctly.

**Comment by jamesladd** [comment]
I have the following:

functions:

  preSignup:
    handler: src/main/js/handler.preSignup
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: api/presignup
          method: post
          integration: lambda
          cors: true
      - cognitoUserPool:
          pool: ${{self:provider.custom.userPoolName}}
          trigger: PreSignUp

Where ${{self:provider.custom.userPoolName}} is "my-users"

Later in the resources section I have:

resources:

  Resources:

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${{self:provider.custom.userPoolName}}
        MfaConfiguration: "OFF"
        AutoVerifiedAttributes:


With what I have currently above I get two cognito user pools called
"my-users" one with the triggers
set and the other without.

*Are you saying I need to set / prefix the
${{self:provider.custom.userPoolName}} to *
*CognitoUserPool${{self:provider.custom.userPoolName}}  ??*

- James.

**Comment by hassankhan** [comment]
Your `resources` sections should look like this:

```yaml
resources:

  Resources:

    CognitoUserPoolCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${{self:provider.custom.userPoolName}}
        MfaConfiguration: "OFF"
        AutoVerifiedAttributes:
```

**Comment by jamesladd** [comment]
Now that you have mentioned this the documentation is more clear.

**Comment by jamesladd** [comment]
Yep - that works. Thank you.

**Comment by horike37** [comment]
Thanks @hassankhan for following up 👍 

@jamesladd Glad to hear that your problem has been resolved 🎉 
Closing...

**Comment by ahmetcetin** [comment]
#6362

**Comment by ahmetcetin** [comment]
Better solution with new release, check PR #6362

**Comment by michael-kiley-verified** [comment]
@jamesladd [This](https://michael-kiley.medium.com/one-step-aws-cognito-user-pool-with-lambda-triggers-using-serverless-framework-d3bdf07b62c1) article also describes how to add custom triggers to a cognito pool that you have added in custom resources in more detail.
