### ISSUE TITLE
Remote env variable collision?

### ISSUE THREAD

**Issue by tmilewski** [serverless/serverless#459]
I was running into some issues with authentication when passing my AWS keys to the AWS SDK via environment variables.

When I ran `console.log(process.env);`, I found that two (not all) of the environment variables were incorrect despite being correct when running `sls env list` and in the S3 env file.

I then went ahead and renamed the environment variables that I had set and everything was :+1:.

It seems as if something is colliding with the following ENV variables:

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

![1](https://cloud.githubusercontent.com/assets/26691/12125580/1188994a-b3ba-11e5-9da9-2c4f390128af.png)
---
![2](https://cloud.githubusercontent.com/assets/26691/12125582/169ae56e-b3ba-11e5-8f1f-ae02e55b0cfc.png)

**Comment by hauboldj** [comment]
I believe the lambda runtime sets AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN to values that are valid for using the IAM role that the lambda function has been assigned. As far as I can tell you are overwriting just the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, but the AWS_SESSION_TOKEN remains.

I would recommend not using Access Keys in environment variables and just the the lambda function role to provide access to AWS resources. In the event that you need to access resources in another account you should have your lambda function assume a cross account role.

See http://docs.aws.amazon.com/IAM/latest/UserGuide/walkthru_cross-account-with-roles.html and http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRole-property for information about assuming a role via the AWS-SDK.

**Comment by tmilewski** [comment]
Looking into this now. Thanks a lot for the help!
