### ISSUE TITLE
1.20.1: sls CLI says security token is invalid despite credentials being correct

### ISSUE THREAD

**Issue by laurenfb** [serverless/serverless#4592]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
In all serverless projects, attempting to use serverless CLI to interact with AWS returns error message `ServerlessError: The security token included in the request is invalid`, despite credentials being correct. Does this happen to anyone else? I have spent nearly the full day trying to figure out why to no avail. In addition, I have found this to be true across multiple accounts -- I cannot talk to any of my AWS accounts with the serverless CLI. I have also tried to create a new project from scratch -- the creation works, but the instant I try to deploy the same error shows up. I have tried with Python 2.7 and 3.6, but no other languages.

Example commands:
`sls deploy --aws-profile <profile-name>`
`sls invoke -f <function-name> --aws-profile <profile-name>`

* What did you expect should have happened?
It should deploy/invoke/etc without permissions issues. I know the credentials (stored in `~/.aws/credentials`) are correct because I can use the AWS CLI and do not have permissions issues. For instance, `aws --profile <profile-name> iam list-users` or `aws --profile <profile-name> ec2 describe-instances` both work just fine. 

* What was the config you used?
This is true of all my serverless projects  but here is one example.
```yml
service: <service-name>
provider:
  name: aws
functions:
  send:
    handler: handler.send
    events:
      - http:
          path: send
          method: post
          cors: true
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
```

* What stacktrace or error message from your provider did you see?
```
sls deploy --aws-profile <profile-name> --verbose
Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Docker Image: lambci/lambda:build-python2.7
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Unlinking required Python packages...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The security token included in the request is invalid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.2
     Serverless Version:     1.20.1
```
Similar or dependent issues:
* #1518 is similar, but I've tried everything listed there and not been resolved. plus, I am able to use AWS CLI with these credentials, so I don't think that is the problem. 

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.1
* ***Operating System***: mac os Sierra 
* ***Stack Trace***:  see above
* ***Provider Error messages***: see above

**Comment by laurenfb** [comment]
Updating to 1.25.0 eliminated this error. I'll leave the issue open since it seems like a pretty significant bug in 1.20.1.

**Comment by HyperBrain** [comment]
I changed the subject to have the version in, so that anyone doing a search will find the issue even if it is closed.
Keeping it open for long does not make any sense as it is fixed already.

**Comment by HyperBrain** [comment]
I will close it now. People can wasily find it by searching open and closed issues.

... and thank you for testing with the band new 1.25 😃

**Comment by maxalmonte14** [comment]
I have the exact error with a superior version

![problem](https://user-images.githubusercontent.com/12385704/37914520-62e98ab0-30e5-11e8-85e0-df28f98e36f0.png)

**Comment by joemocha-coxauto** [comment]
I have the exact error with version 1.26.1

<img width="955" alt="screen_shot_2018-03-26_at_11_08_23_am" src="https://user-images.githubusercontent.com/33699155/37914922-5a814a56-30e6-11e8-85e4-d2051bdec955.png">

**Comment by orverduzco** [comment]
any news with this? I'm facing the same problem with the same configuration as above

**Comment by jhachtel** [comment]
+1 - Me too

**Comment by actsasgeek** [comment]
I'm having the same problem. I can confirm that using boto3 in .py scripts to talk directly to AWS works like a charm.

**Comment by satyaki1** [comment]
I am using following configuration 
`OS:                     win32,     Node Version:           8.11.1,     Serverless Version:     1.27.2`
I was facing same issue, problem for me was while setting up the AWS keys. I used quotes.
instead of this : 
```
D:\Git\hello-world>set AWS_ACCESS_KEY_ID= ':access_key'
D:\Git\hello-world>set AWS_SECRET_ACCESS_KEY=':secret_key'
```
use this
```
D:\Git\hello-world>set AWS_ACCESS_KEY_ID= :access_key
D:\Git\hello-world>set AWS_SECRET_ACCESS_KEY= :secret_key
```

**Comment by dileephell** [comment]
I am having the same error.

![serverlesserror](https://user-images.githubusercontent.com/2589018/41146163-17e5a0c4-6b20-11e8-9356-e07c6f8b60b1.png)

**Comment by kenzotan95** [comment]
Same issue here
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The security token included in the request is invalid
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.14.2
     Serverless Version:     1.27.3

**Comment by laurenfb** [comment]
I haven't seen this issue since updating to the latest version when I posted it. But, there's a steady stream of new folks with superior versions chiming in. @HyperBrain, would it make sense to reopen this issue? Or should they open new issues?

Thanks!

**Comment by kenzotan95** [comment]
@dileephell use 
export AWS_ACCESS_KEY_ID=AWSID
export AWS_SECRET_ACCESS_KEY=AWSKEY
export AWS_DEFAULT_REGION=REGION

You should be able to bypass the security issue.

**Comment by burbelohugo** [comment]
I'm getting this issue as well - is there any update on this? Exporting the environment variables works, but it's a poor solution long-term...

**Comment by anil1712** [comment]
I am getting the same error.

Did anyone get the solution?

**Comment by softprops** [comment]
having the same issue in with the latest release in travis.

```
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.12.0
     Serverless Version:     1.28.0
```

**Comment by data1435** [comment]
![image](https://user-images.githubusercontent.com/36028430/43007551-48343d88-8c56-11e8-9b21-d97bcd9342ab.png)
I'm also facing the same issue. This was working fine about 3 months before with the same set of access keys.

**Comment by soda29** [comment]
I'm too having this problem:

![image](https://user-images.githubusercontent.com/2402059/43467017-2ddf23da-94b7-11e8-963d-7fb613901cfd.png)

**Comment by atedja** [comment]
I am also having this problem with version 1.29.2 because I was using `aws-vault` which is using `AWS_SECURTY_TOKEN` and `AWS_SESSION_TOKEN`.

It seems I'd have to hardcode my own `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` into the environment. Less than ideal.

**Comment by maityneil001** [comment]
This happened to me as well on the latest version a few minutes back. It was working until today morning suddenly giving the error. @kenzotan95's suggestion worked.

**Comment by sovanc** [comment]
Even after I exported the variables, I'm still getting the same error.  I received the same error using older versions as well.  BTW, I ran this in GovCloud.  Inside commercial region, I have no problem at all.

Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  ServerlessError: The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.1.0
     Serverless Version:     1.34.1

**Comment by Ray-B** [comment]
Also encountering this issue, while needing to use AWS_SESSION_TOKEN.

ServerlessError: The security token included in the request is invalid.

 Get Support --------------------------------------------
 Docs: docs.serverless.com
 Bugs: github.com/serverless/serverless/issues
 Issues: forum.serverless.com
 Your Environment Information -----------------------------
 OS: linux
 Node Version: 8.11.0
 Serverless Version: 1.39.0

Attempted exports: 
```
export AWS_ACCESS_KEY_ID= blah
export AWS_SECRET_ACCESS_KEY= blah
export AWS_SESSION_TOKEN=blah
export AWS_DEFAULT_REGION=blah
```

to no avail. Also tried setting AWS_REGION and that also did not work. 

Seems like various permutations of this bug have been cropping up since at least 1.20....This should be reopened.

**Comment by janober** [comment]
Having exactly the same problem on:
Ubuntu 18.04
Node Version:           10.16.0
Serverless Version:     1.45.1

Credentials are correctly set in file: `~/.aws/credentials` (even created via serverless) but unless I set the environment variables  AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
I get the error message:
```
ServerlessError: The security token included in the request is invalid.
```

**Comment by janober** [comment]
No sorry, not true. Was my fault. There was a difference in the credentials after all. A script which did set the credentials via serverless added them surrounded with quotes. So it did set them to: "SECRET" instead of SECRET and that made them invalid.
I thought before that serverless simply sets them differently than the aws cli does. But that was obviously wrong. So just in case somebody else makes similar wrong assumptions. So serverless is working all fine.

**Comment by DanielWFrancis** [comment]
Having this problem when trying to switch my serverless provider to a different region.

**Comment by proxy-project** [comment]
My workaround was to provide the AWS profile I intend to use. 
```
sudo serverless deploy --aws-profile testADM
```
and having the testADM in my _~/.aws/credentials_ file

**Comment by DanteDX** [comment]
I could fix this error, I installed latest version of serverless with (npm install -g serverless), save the aws credentials like access key, secret and in case of educate account also the session token in the .aws/credentials file, after that generate a serverless project by (serverless create --template aws-nodejs --path yourProjectName), open serverless.yml file and under provider add (profile: default), save it
this will just use the credentials in your .aws/credentials..... then on the terminal, write "sls deploy", you are done....
![serverless](https://user-images.githubusercontent.com/53355883/104131950-3d1d3b80-53a4-11eb-9f6d-bfef0aa0a7e6.JPG)

**Comment by markcastle** [comment]
For anyone that comes across this issue even with the latest versions of serverless... you can also get this error if your credentials in the serverless dashboard are incorrect and it's not altogether obvious that that is the issue.. I spent a number of hours trying to resolve this so hoping to just help others.
