### ISSUE TITLE
Development/Testing Plugins Always Included in Deployment Package

### ISSUE THREAD

**Issue by matttowerssonos** [serverless/serverless#4598]
# This is a Bug Report + Feature Proposal
(it's a little of both)

#### For bug reports:
* What went wrong?

*Plugin packages that are only applicable at development time are always included in the deployment package, which can cause package size limits to be exceeded.*

* What did you expect should have happened?

*Development only plugins should not be included in deployment packages.*

* What was the config you used?

*Here's the plugins section for our `serverless.yml`*
```yml
plugins:
    - serverless-dynamodb-local
    - serverless-mocha-plugin
    - serverless-offline-sns
    - serverless-offline
```
* What stacktrace or error message from your provider did you see?

*n/a*

#### For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

*In our case several plugins are only applicable in a development environment and including them in the deployment package adds about 40MB to the upload size.  I think there are a few ways this problem could be addressed (see related issue links below) but as an isolated solution, I would like to be able to conditionally include plugins based on runtime environment and/or stage.*

### Idea 1
Allow development-only plugins to be declared separately in `serverless.yml` and exclude them and their dependencies from the deployment package.  For example:
```yml
devPlugins:
    - serverless-dynamodb-local
    - serverless-mocha-plugin
    - serverless-offline-sns
    - serverless-offline
plugins:
    - serverless-awesome-plugin
```
>In my case, I've added the development plugins to `devDependencies` in my `package.json`.  Before I do a deploy, I do an `npm prune --production` to remove them from `node_modules` and then comment out the relevant lines in my `serverless.yml -> plugins` section.  It's not ideal, but it gets the job done for now.  

### Idea 2
Allow plugins to be included conditionally based on stage.  As I understand it, this is not currently possible as the `plugins` section is evaluated _before_ `yml` variables and references are resolved.  For example:
```yml
plugins: ${file(plugins.yml):${self:provider.stage}}
```

### Idea 3
Add a command line switch to pass in the path to the `serverless.yml` to use.   This option has been discussed at length in other feature requests and issues.  While it would solve for my use case, it would mean that I would have to maintain two separate config files with nearly identical content.   i.e.  not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) enough.

## Similar or dependent issues:
* #4473 - Allow explicitly specifying `serverless.yml` file in CLI options or env var
* #4124 - Feature Proposal: Serverless should support being able to supply path to .yml file to use for configuration
* #4071 - Feature Proposal: Improvements to `serverless deploy`/`serverless deploy function

## Additional Data

* ***Serverless Framework Version you're using***:  `"serverless": "~1.24.1"`
* ***Operating System***:  MacOS 10.12.6 (Development), AWS Lambda (Production)

**Comment by matttowerssonos** [comment]
⚠️  Right after I posted this, I realized I was actually using an old version of serverless (1.14).   Among other things, this seems to have prevented serverless from honoring `excludeDevDependencies: true`.  I think you can close this one as [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC).

**Comment by HyperBrain** [comment]
Hey @matttowerssonos , thanks for the feedback. I didn't know about the abbrev. PEBKAC until now 😄 .

Closing.
