### ISSUE TITLE
S3 Transfer Acceleration is not working properly for custom deployment buckets

### ISSUE THREAD

**Issue by alexcasalboni** [serverless/serverless#4605]
# This is a Bug Report

## Description

As reported in #4293 by @waynerobinson, S3 Transfer Acceleration doesn't work when custom deployment buckets are used.

I've performed some tests and everything works fine for new services. The current implementation doesn't handle properly the case of already-deployed services with a custom deployment bucket.

I'm going to work on a fix and add tests to cover this case.

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0

**Comment by waynerobinson** [comment]
Thanks for this.

**Comment by alexcasalboni** [comment]
@waynerobinson in the meantime, you could check if everything works fine for you by using the `issue4605-s3-transfer-acceleration-custom-bucket` branch of my forked repo: https://github.com/alexcasalboni/serverless/tree/issue4605-s3-transfer-acceleration-custom-bucket

**Comment by waynerobinson** [comment]
Cool… I'll check it out when I get a chance. Thanks for the quick response on this… especially during the holiday season.
