### ISSUE TITLE
AccelerateConfiguration invalid in cn-north-1

### ISSUE THREAD

**Issue by gongzili456** [serverless/serverless#4609]
How selectively turn off this configuration?

The `AccelerateConfiguration` should is `{}` in cn-north-1

```
this.serverless.service.provider.compiledCloudFormationTemplate
      .Resources.ServerlessDeploymentBucket.Properties = {
        AccelerateConfiguration: {
          AccelerationStatus:
            isS3TransferAccelerationEnabled ? 'Enabled' : 'Suspended',
        },
      };
```

**Comment by horike37** [comment]
Thank you for asking @gongzili456 :smile: 
Currently, there is no way that you define `{}` in `AccelerateConfiguration` even if you want to disable S3TransferAcceleration.

Do you mean `AccelerateConfiguration` itself cannot be specified in cn-north-1 region?

**Comment by gongzili456** [comment]
Yes, I confirmed with their customer service staff, Invalid in cn-north-1 region currently.

**Comment by horike37** [comment]
just opened up [another issue](#4615) for supporting cn-north region so closing this issue for now.
