### ISSUE TITLE
Uploading Static Content Related to a Project

### ISSUE THREAD

**Issue by Spannella** [serverless/serverless#461]
In my use case I am often deploying front end content at the same time that I am deploying my back end logic. I was wondering if there is an easy way to have serverless upload my content to an S3 bucket for web hosting and setup a cloudfront distribution at the same time for the bucket. At the moment I am using a script first call serverless to do the deployment of my back end and then have the rest of the first script do the deployment of my front end. Ideally I would like to merge these processes either using serverless directly or working on a plugin to serverless that could do this added functionality.

**Comment by JamieCressey** [comment]
+1 this. I could see a use case whereby EmberJS (or similar, which can be hosted statically) is used as a frontend to the endpoints Serverless currently creates. I'm not sure if it's outside of the scope of this project but it would be a massive benefit to me to have additional `sls` commands to manage a serverless frontend too.

**Comment by visualasparagus** [comment]
Definitely seems like a plugin to me.

**Comment by Spannella** [comment]
Ok so I would be really interested in creating a plugin project for this. Does anyone have any advice on how to make a plugin for Serverless? The documentation has not gotten to this topic yet.

**Comment by ryansb** [comment]
@Spannella there's a [boilerplate project](https://github.com/serverless/serverless-plugin-boilerplate) and some (kinda sparse) [plugin docs](http://docs.serverless.com/docs/installing-plugins)

Hope that helps

**Comment by pmuens** [comment]
+1 Also facing this issue

**Comment by grandmore** [comment]
@Spannella have you progressed with your plugin? I have a similar need. 

I'm using react and would like to upload the complied files to S3 ( the root of cloud front) to be severed to the lambda function using normal `<script>x.js</script>` tags. The I can load the x.js map alongside and do chrome browser debugging.

I'm experimenting with having the files loaded via lambda as well but I think a CDN would be more sensible.

Thanks,

**Comment by pmuens** [comment]
https://github.com/serverless/serverless-client-s3 was started to tackle those issues
