### ISSUE TITLE
I found some problems about how to use Serverless in China AWS region cn-north

### ISSUE THREAD

**Issue by gongzili456** [serverless/serverless#4610]
### background:
cn-north lambda function currently supported. We very much hope can use here.

### problems:
* The config below must set
```
provider:
  region: cn-north-1
```
> if not set will occur error is
`ServerlessError: The security token included in the request is invalid.`

* All AWS service of region cn-north arn prefix is `arn:aws-cn:` not `arn:aws:`

* S3 domain address is `s3.cn-north-1.amazonaws.com.cn` not `s3.amazonaws.com`
> Error at here will occur `bucket does not exist`

>**And very important**
Lambda function can not be created by CloudFormation currently, But coming soon.

We very much hope use Serverless in China at next version :)

**Comment by horike37** [comment]
Thank you for providing us cn-north region infomation :smile: 
We really want to support for the region, but we need to wait that CloudFormation supports necessary resources for running the framework, and then add extra changes to the codebase for that(e.x switch to arn prefix when running in cn-north).

Do you know what else should we do other than stuff you provided on this issue?

**Comment by gongzili456** [comment]
I want to find a way to use AWS lambda in cn-north-1 easily, Including and not limited to packaging files, upload files to S3, update functions, manage functions and a series of workflow.

**Comment by horike37** [comment]
just opened up [another issue](#4615) for supporting cn-north region so closing this issue for now.
