### ISSUE TITLE
Git LFS not supported by sls install command

### ISSUE THREAD

**Issue by araines** [serverless/serverless#4611]
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong?
`sls install --url https://github.com/araines/serverless-php`

* What did you expect should have happened? 
Expected that the PHP binary which is stored using Git LFS should have been downloaded, it was not.

* What was the config you used?
N/A

* What stacktrace or error message from your provider did you see?
N/A

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
It would be nice for the `sls install` command to download files stored in Git LFS, similar to how `git` behaves when you do `clone` with LFS installed.

* If there is additional config how would it look
N/A

Similar or dependent issues:
* None found

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: macOS 10.13.2
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by horike37** [comment]
Thank you for the proposal @araines :smile: 
Looks good idea :100:

**Comment by medikoo** [comment]
Closing as `sls install` is kind of deprecated now, and to setup new projects users are expected to use just `sls`
