### ISSUE TITLE
AWS account limits ?

### ISSUE THREAD

**Issue by f0ster** [serverless/serverless#4614]
I have been working through changes to migrate from `lambda` to `lambda-proxy`, and all of the sudden my API gateway routes are returning `502 Internal Server Error`

My cloudwatch logs show no errors, I also reverted to a working tag, redeployed, and same issue.  Is this the result of some service limit on AWS?

**Comment by horike37** [comment]
Thank you for asking @f0ster :smile: 
It wouldn't be any limits on AWS end.

https://serverless.com/framework/docs/providers/aws/events/apigateway#lambda-proxy-integration
When using `lambda-proxy`, you need to return like the following response so that Lambda will be automatically mapped to your response code, headers and body for API.

```javascript
const response = {
  statusCode: 200,
  headers: {
    "x-custom-header" : "My Header Value"
  },
  body: JSON.stringify({ "message": "Hello World!" })
};
callback(null, response);
```

Did you correctly return the response? if correct, could you please tell us the pointer where your functions code and serverless.yml setting is, so that we can take a look into it?

**Comment by f0ster** [comment]
Thanks @horike37 .  After trying my code again this morning (no changes), it is now working as expected.

This is really alarming though, I am trying to build a production system on serverless and having non deterministic errors like this (or at least ones I can't debug because it is running on AWS), makes me want to abandon using it entirely :(

**Comment by f0ster** [comment]
Thanks @horike37 .  It turned out my code was crashing, and AWS is returning a 502 which might be related to CORS.  When my code does not crash, I am getting the correct response.

However, I still have CORS errors in the browser (but it is not a blocking problem)

I have `cors: true` in sls yml, and I get the correct response body, however in the browser I still get this error when testing the endpoint
"Failed to load https://my-aws-endpoint: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

I can see `OPTIONS` returns the correct headers
```
access-control-allow-credentials:false
access-control-allow-headers:Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent
access-control-allow-methods:OPTIONS,POST
access-control-allow-origin:*
```

Any idea why I am still getting errors about CORS on the client side?

**Comment by HyperBrain** [comment]
@f0ster Do you also add the CORS headers to your resource endpoint methods (I mean not only OPTIONS)?

**Comment by f0ster** [comment]
@HyperBrain I am using the default `lambda-proxy` integration, and specifying `          cors: true` on the route definition, so I am not explicitly setting anything differently for OPTIONS vs GET/POST.

How can I add that as well ?

**Comment by wonathanjong** [comment]
@f0ster did you ever figure out the issue? I am having the same problem

**Comment by f0ster** [comment]
@wonathanjong I have it working with the above explicit response settings, and these serverless settings:
```
  whatever:
    handler: src/handlers/whatever
    events:
      - http:
          path: whatever
          method: get
          authorizer: auth # See custom authorizer docs here: http://bit.ly/2gXw9pO
          cors: true   
```
Also, If your error path callbacks to the handler do not have the same headers on the response, then it will also show up as a CORS issue and not a 4/500, etc
