### ISSUE TITLE
Support for China AWS region cn-north

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4615]
# This is a Feature Proposal

## Description
Currently, the Serverless Framework cannot work in cn-north region since it seems like some necessary resources(Lambda, APIGateway) don't support yet for CloudFormation.

Then, arn or S3 bucket URL schema is different from other regions, so we should fix that corresponding to the schema

At least, we need to wait that those resources would support for CloudFormation.

Here is the task list which we caught up so far.

- All AWS service of region cn-north arn prefix is `arn:aws-cn:` not `arn:aws:`.
- S3 domain address is `s3.cn-north-1.amazonaws.com.cn` not `s3.amazonaws.com`.
- The `AccelerateConfiguration` statement with CloudFormation for `ServerlessDeploymentbucket` should be `{}`.

Similar or dependent issues:
* #4463 #4479 #4609

**Comment by gongzili456** [comment]
And aws cn-north-1 lambda version has some bugs, I committed that to aws and they are fixing now, I change some code and test serverless use cloudformation in cn-north-1 is can used almostly.

**Comment by yidag** [comment]
@horike37 hi，when will you serverless support for cn-north-1？

**Comment by ijustyce** [comment]
@horike37 @gongzili456  @yidag     Hi, I also want to known when will serverless support cn-north-1, and is there any solution now. We want to deploy to cn-north-1 this week, please help me.

**Comment by brianneisler** [comment]
I believe `cn-north` is now supported. Closing this issue.

**Comment by newbaluku** [comment]
is there a guide somewhere in serverless's documentation on what to change/adapt if I'm deploying to AWS China?
