### ISSUE TITLE
TypeError: event.cloudwatchLog.logGroup.replace is not a function

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4616]
# This is a (Bug Report Proposal)

## Description

For bug reports:
* What went wrong?

Get the error when reference a log group.

    TypeError: event.cloudwatchLog.logGroup.replace is not a function

* What did you expect should have happened?

replace the reference log group name with real one.

* What was the config you used?

```
functions:
  pushCustomAccesslogs:
    handler: logs/logs.handler
    events:
      - cloudwatchLog:
          logGroup: { "Ref": "CustomAccessLogs" }

resources:
  Resources:
    CustomAccessLogs:
      Type: AWS::Logs::LogGroup

```

* What stacktrace or error message from your provider did you see?

```
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
LogGroupName:  { Ref: 'CustomAccessLogs' }      # <=== Here is the name

  Type Error ---------------------------------------------

  event.cloudwatchLog.logGroup.replace is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: event.cloudwatchLog.logGroup.replace is not a function
    at functionObj.events.forEach.event (/usr/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js:48:59)
```

The error line is:

               LogGroupName = event.cloudwatchLog.logGroup.replace(/\r?\n/g, '');

https://github.com/serverless/serverless/blob/c345e9a9bfb5dd49a13788009430e24c400243f2/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js#L48

## Additional Data

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.3
     Serverless Version:     1.25.0

I added a debug line before replace function:

              console.log("LogGroupName: " , event.cloudwatchLog.logGroup);

from deploy debug log, seems the logGroup name is not referenced properly:

    LogGroupName:  { Ref: 'CustomAccessLogs' }

**Comment by HyperBrain** [comment]
Hi @ozbillwang ,

> What did you expect should have happened?
> replace the reference log group name with real one.

As you use "Ref", which is a CloudFormation reference, Serverless cannot replace the name within the template but would have to wait for CF to do that during the stack update.

However, the crash is not expected. It seems that the cloudwatchLog event does not accept CF references yet. As a workaround you should set a CW log name as string in the event, so that Serverless can create the log group accordingly.

BTW: I think your CW log definition in resources is incomplete - there are some mandatory properties that have to be set.

**Comment by ozbillwang** [comment]
@HyperBrain 

>However, the crash is not expected. It seems that the cloudwatchLog event does not accept CF references yet. As a workaround you should set a CW log name as string in the event, so that Serverless can create the log group accordingly.

Thanks to confirm the bug. I can hard code the log group name directly, but that's not my user case, I need the log group to be created on fly with different name.
 
>BTW: I think your CW log definition in resources is incomplete - there are some mandatory properties that have to be set.

In fact, it is correct, the Properties can be missed, that cloudformation will set the log group name randomly with the format: `{service_name}-{stage_name}-{resource_name}-{Random_string}`

**Comment by ozbillwang** [comment]
>As you use "Ref", which is a CloudFormation reference, Serverless cannot replace the name within the template but would have to wait for CF to do that during the stack update.

If it can't use cloudformation reference, then I try to use the serverless variables: 

```
    events:
      - cloudwatchLog:
          logGroup: /aws/apigateway/${self:custom.service}-${self:custom.stage}-CustomAccessLogs
```

But I got this error: 

>Trying to populate non string value into a string for variable ${opt:stage, self:provider.stage}. Please make sure the value of the property is a string.

**Comment by ozbillwang** [comment]
I check the deployment processes, seems the logGroupName is defined too early.

```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
LogGroupName:  /aws/apigateway/serverless-staging-CustomAccessLogs
Serverless: Uploading CloudFormation file to S3...
```

From the output, the LogGroupName is defined before cloudformation stack started. Of course, it can't reference the cloudformation resource.

**Comment by alanionita** [comment]
Running in this issue too, whereby we are deploying into multiple accounts and want to dynamically replace the region and account

```yaml
read-cloudwatch:
  handler: build/read-cloudwatch.handler
  timeout: 30
  events:
      - cloudwatchLog:  
        - Fn::Sub:
          - sns/${AWS::Region}/${AWS::AccountId}/DirectPublishToPhoneNumber
```

**Comment by pgrzesik** [comment]
Hello @alanionita, thanks for reporting that you're running into this as well. At the moment, `cloudwatchLog` event does not support CF intrinsic functions but we'd be happy to accept a PR adding that functionality :tada:

**Comment by akzincsystems** [comment]
What is ETA for resolution of this bug?  It is clearly broken as it doesn't work with the rest of CF functionality and is therefore at best a retarded piece of functionality and at worst, next to useless. And 4 years after initial report and no fix?

For anyone else looking to implement this type of (potentially useful) functionality, take a look at https://github.com/ACloudGuru/serverless-plugin-aws-alerts. It may serve you better.

**Comment by medikoo** [comment]
I'm closing as it's not really a bug. It's just we do not support CF intrinsic functions at `logGroup` property, as to properly handle the event we need to have log group name resolved.

This issue was kept open initially as we didn't have proper error reporting in place, but now that's solved with configuration validation backed by schema, and schema clearly indicates we accept an only plain string as an input.

If you feel we can maintain the same functionality while extending the support for CF intrinsic functions at `logGroup` property, please open a new feature request, detailing the idea. If it'll promise desired results we will definitely welcome the PR.
