### ISSUE TITLE
Question: Is there a reason why we use "s-function.json" files instead of a "js" file which exports the same json?

### ISSUE THREAD

**Issue by swarajgiri** [serverless/serverless#463]
Was trying out optional query params for an endpoint and needed a mapping template.
This is what i started with.
```
"requestTemplates": { "application/json": "{\n\"limit\": \"$input.params('limit') \", \n\"position\": \"$input.params('position') \"}" }
```

Notice there is a empty space before the ending curly. This caused apigateway to throw up parsing errors, which got resolved when i used
```
{\n\"limit\": \"$input.params('limit')\", \n\"position\": \"$input.params('position')\"\n}
```

A simple mapping template resulted in at least 20 mins of head scratching, imagine what would happen if someone required a rather long mapping template.

#### Suggestion:
We would be in a better position if we used a `s-function.js` file and export the required config out. This would help anyone writing a non-trivial mapping template.

**Comment by Nopik** [comment]
Generally, I hate code like `require( "./foo.json" )` and consider it as antipattern, too. Especially when I'm writing CoffeeScript and have `.coffee` registered in Node so `require( "./foo" )` would correctly read my `foo.coffee`. I'm very often exporting json config from js/coffee files and surprisingly many frameworks have json import hardcoded. Indeed, I'd prefer to have framework to `require( "s-function" )` instead of `require( "s-function.json" )` to properly use Node mechanism for filetype recognition, potentially allowing people to use dynamic json generation or some other languages.

**Comment by erikerikson** [comment]
+1, I've wondered this too.  Json is necessarily static whereas js/coffee/et cetera can be just as static or do something interestingly/helpfully/compactly dynamic.

I do think that the implied "don't hack this too much, it's a config file" is a simpler message that avoids the craziness (and specifically supporting the craziness) that could be created by providing people dynamicity.

**Comment by swarajgiri** [comment]
@eahefnawy - Why was this closed?

**Comment by eahefnawy** [comment]
@swarajgiri Just closed for inactivity/cleanup :) ... Thanks for your feedback as always :blush:

btw, we're thinking of maybe replacing JSON with YAML, or maybe supporting both!

**Comment by TCMiranda** [comment]
Pure js objects export would definitely be a better solution, since it would be possible to merge default settings and operate on them before exporting the js object.

**Comment by dherault** [comment]
+1 for pure JS object export, it would support multiline Velocity templates out of the box, which was the purpose of YAML support. Also, no more template parsing (`s-templates.json`), thanks to `require` everything goes in userland, that place we developers like :palm_tree:.

**Comment by HyperBrain** [comment]
You can define your templates as `s-templates.yaml` in 0.5.5 with embedded VTL.

**Comment by TCMiranda** [comment]
@HyperBrain what about pure JS objects? Is it planned?

**Comment by HyperBrain** [comment]
I don't know. In my opinion there is one point against JS objects. It may make the framework itself more unstable as you would have direct access to the global context there. You could break things by accident very easily.

**Comment by dherault** [comment]
Good point, yet it seems unlikely that anyone would to that. And if they do, it is their problem not ours ^^. JS object would make the framework more flexible, less frameworky, and allow lots of crazy manipulations (crazy good) on variables, etc... But it would also make basic JavaScript a prerequisite.

**Comment by TCMiranda** [comment]
Yes, it is a concern, yet it wouldn't be that easy to break things only with global scope access.
Webpack would be an example of library who allow both json and js objects with the same format

**Comment by HyperBrain** [comment]
Another thing that came into my mind: with required JS files it also would be possible for a developer who has restricted access rights to the AWS account to inject code to get an access token for the build server's credentials and execute stuff just by cheking in a configuration file -> and CI will do the rest.
I know, that most guys are honest but some companies might see that as big security issue.

**Comment by TCMiranda** [comment]
Yeah, this is serious.. Good to know you do realize those problems.. 
Can we solve it somehow? 
What would it mean to have an optional syntax that may be insecure under some conditions?
