### ISSUE TITLE
Support for tags in Amazon API Gateway

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#4644]
# This is a Feature Proposal

## Description

On AWS tags are commonly used for logically associating resources with each other and simplifying billing. Amazon's API Gateway stages support tags now 🎉 . However, those don't seem to be populated by Serverless yet:

![image](https://user-images.githubusercontent.com/1548229/34832452-e0f42dc4-f69e-11e7-8b91-24ed871202d6.png)

Serverless already supports tags for Lambda functions as well as a stack-wide tags (`stackTags`). As an API Gateway stage can only have one set of tags I suggest to automatically assign the `stackTags` to the API Gateway stages during deployment.

**Comment by arabold** [comment]
I've created this feature request in the `aws-alias` plugin as well, as that's pretty much a must have for anybody using API Gateway in my opinion: https://github.com/HyperBrain/serverless-aws-alias/issues/93

**Comment by horike37** [comment]
Thank you for the proposal @arabold 😄 
Looks a good idea 🎉 
Has CloudFormation already supported for the API Gateway stages tag?
If so, we can introduce this feature.

**Comment by softprops** [comment]
+1

**Comment by ciaranmoran** [comment]
+1

**Comment by mk13d** [comment]
+1

**Comment by Kyefer** [comment]
+1

**Comment by joeyvandijk** [comment]
> Thank you for the proposal @arabold 😄
> Looks a good idea 🎉
> Has CloudFormation already supported for the API Gateway stages tag?
> If so, we can introduce this feature.

@horike37 I see at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html that you can add tags to a stage, so the answer is yes.

**Comment by bryaningl3** [comment]
+1

**Comment by zephrax** [comment]
+1

**Comment by danhumphrey** [comment]
+1

**Comment by eapesa** [comment]
Hello. 

May I know if there are any updates regarding this? Currently using serverless to deploy a Lambda function with API Gateway as trigger but the tags I place for Lambda does not appear in Gateway. I'm using `stackTags` to define my tags.

Thanks!

**Comment by onebytegone** [comment]
@eapesa If you are looking for a *temporary* workaround, I've been running https://github.com/silvermine/serverless-plugin-apigateway-stage-tags in production for a few months. No issues so far. The plugin is not as nice as using CloudFormation (the plugin was written before CF had native APIGW tagging support), but it works for now. Of course, once Serverless supports this tagging, I'll be switching to the natively supported solution!

**Comment by mlg-rbalhorn** [comment]
adding my support for this feature as well.
