### ISSUE TITLE
Question: Documentation on endpoints configuration in s-function.json

### ISSUE THREAD

**Issue by davidgtonge** [serverless/serverless#465]
Hi,

This is a really interesting framework - I'm using it for a side project and want to start using it at work. I've struggled to find documentation / blog posts / examples on all the configuration options for endpoints in the s-function.json. For example some of the questions I have are:

 - How can I pass http headers through to the lambda event?
 - How can I pass query strings through to the lambda event?
 - How can I set headers on the return request?

And many more. I'd like to get involved with this project and would be happy to start documenting the configuration options - but it would be great if someone could point me in the right direction towards any existing resources.

Thanks

**Comment by c-knowles** [comment]
See https://github.com/serverless/serverless/issues/466 for the first two. The pattern is similar for the return request.

**Comment by eahefnawy** [comment]
we've updated the docs to reflect the `s-function.json` config. [Check it our here](http://docs.serverless.com/docs/templates-variables)

**Comment by coltonone20** [comment]
@eahefnawy That page 404's now

**Comment by pmuens** [comment]
Hey @coltonone20 here's a working link to the page @eahefnawy posted: https://serverless.readme.io/docs/templates-variables

Note that we've discontinued the support for Serverless `v0.X`. Serverless v1 is now the most recent version.

**Comment by coltonone20** [comment]
Thanks @pmuens !
