### ISSUE TITLE
Can't have dot in custom variable's key - could not be found.

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4652]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?

If the variable in custom has dot, serverless will always report `could not be found.`

* What was the config you used?

```
$ cat dev.yml
version:
  v1.0: value-1
  v2.0: value-2
```

When I reference the variable `${self:custom.version.v1.0}`, always got the error:

    could not be found.

I understand that custom variable use dot (.) as splitter, but how to escape dot when reference it?

**Comment by ozbillwang** [comment]
Ok, I fix it by myself. Excape with backslash.

    ${self:custom.version.v1\.0}

**Comment by ozbillwang** [comment]
Above way (excape dot) can pass cloudformation validate, but can't be deploy. 

If `serverless print`, I can't see the variable is replaced by the real value.

**Comment by rupakg** [comment]
Can you just use v1_0 instead of a . ?

**Comment by HyperBrain** [comment]
@ozbillwang There is currently no escape syntax for Serverless variable names, i.e. it is not possible to use dots in names for other things than separating subobjects.
Although it seems like a corner case for me, I agree that this would be an useful enhancement for these cases.

**Comment by ozbillwang** [comment]
Thanks, @rupakg @HyperBrain 

At the moment, I use other characters to replace dot for these keys
