### ISSUE TITLE
Setuptools missing from lambda

### ISSUE THREAD

**Issue by gcampionpae** [serverless/serverless#4657]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
When deploying a service with the package aws-xray-sdk 0.95 I would see the error "Unable to import module 'lib/chargebee_listener': No module named pkg_resources"

I expected that setuptools would be included in the package that is uploaded to s3

Unable to import module 'lib/chargebee_listener': No module named pkg_resources

Is it itentional that setuptools is not included in the package that is used for the Lambda function?

serverless 1.20 running in a docker container on linux.

This issue was reported with the xray project and the solution was to include setuptools in the requirements.txt file.

https://github.com/aws/aws-xray-sdk-python/issues/16#issuecomment-356779916

**Comment by HyperBrain** [comment]
Hi @gcampionpae. Thank you for raising this. Unfortunately, I do not use Python modules in our projects, so we'd need someone who is used to do that here, to have some further feedback and ideas for the proper solution.
@serverless/vip Any ideas that could help here?

**Comment by ryansb** [comment]
The Lambda environment is pretty stripped down - usually for versioning I include a `myapp.__hash__` that gets filled in with the git hash or tag in CI.

**Comment by svdgraaf** [comment]
@gcampionpae Are you using the `serverless-python-requirements` plugin to bundle your package? https://github.com/UnitedIncome/serverless-python-requirements

By default, no (additional) packages will be zipped in your lambda zip file, only the ones that you explicitly configure manually. By default, you get a couple from AWS, but those are very slim (mainly `boto3`). See here: https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

The plugin takes care of zipping all your virtualenv (pipenv) requirements from the `requirements.txt`file and making sure that they are available for your function.

**Comment by gcampionpae** [comment]
I am using that plugin and when I add setuptools to the requirements.txt then serverless-python-requirements will include them and the x-ray package works but I just was wondering if this is the desired behaviour.

**Comment by ryansb** [comment]
The lack of setuptools is desired - typically the recommendation is to avoid depending on it, or you can include it (using sls-python-requirements or similar).

**Comment by gcampionpae** [comment]
Ok, thanks for the information @ryansb !

**Comment by Nomane** [comment]
Doesn't work whatever I add setuptools in requirements.txt

requirements.txt
```
- setuptools
- aws-xray-sdk
```

sls version `1.40.0`

plugins:
```
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-plugin-tracing
```

**Comment by Nomane** [comment]
It seems that under .serverless build directory `setuptools` dependancy is removed ?!

requirements.txt on GIT
```
pytz
requests
requests_aws_sign
setuptools
aws-xray-sdk
```

requirements.txt on .serverless
```
pytz
requests
requests_aws_sign
aws-xray-sdk
```

**Comment by Nomane** [comment]
Ok, got it ... plugin serverless-python-requirements intent to omit already dependancies managed by lambda, setuptools is one of them.

Then in serverless.yml you have to add this section to the custom chapter:

```
  pythonRequirements:
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      # - setuptools
      - six
```
That's the trick, but that's not an elegant way to solve this issue, there is 2 questions 

1. Why aws-xray-sdk need setuptools ?
2. Why setuptools is not reachable from aws-xray-sdk since it's under Lambda runtime responsability ?
