### ISSUE TITLE
Pass Headers to Lambda?

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#466]
Is there a way to pass request headers from the API Gateway to Lambda using Serverless? I can see it is possible within the API Gateway UI by creating input mappings, but cant see any obvious methods of configuring it through, presumably the `s-function.json` config.

Thanks!

**Comment by picsoung** [comment]
What is possible to do on the API gateway UI, is available in the `s-function.json` file.

To pass headers to the Lambda you will need to modify the `requestTemplates` part of the file and add your own mapping in it.

**Comment by c-knowles** [comment]
It wasn't entirely clear from the current docs as those are being worked on still but here's an example I have working. In s-function.json, I'm passing through a "dummyParam" in the query string but you can replace "querystring" with "header" as per the attribute names on http://docs.aws.amazon.com/apigateway/latest/developerguide/create-api-using-import-export-api.html.

```
"requestParameters": {
  "integration.request.querystring.dummyParam": "method.request.querystring.dummyParam"
},
"requestTemplates": {
  "application/json": "{ \"dummyParam\": \"$input.params('dummyParam')\" }"
}
```

**Comment by ialmetwally** [comment]
you can do the following: 
"requestTemplates": {
            "application/json": "{\"auth\":\"$input.params().header.get('Authorization')\"}"
 },

this will send the header as a param, then you can read it in your lambda by using event.auth

**Comment by jaminto** [comment]
```
"requestTemplates": {
"application/json": "{\"auth\":\"$input.params('Authorization')\"}"
}
```
Will also work and it's less to type ;).

As a side note, we abandoned using `Authorization` as a custom header for OAuth and similar custom authorization schemes and instead use something like `X-ProjectName-Auth`.

The way that serverless deploys headers (at least in v 0.0.15) allows the `Authorization` header to be passed through to lambda, and lambda interprets it as a [SIG4 signing request](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) and your call will always fail.   you can get this header to work if you do not tell serverless about it in your `s-function.json`, but then if you're using the [mobile sdk generation](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk.html) feature of API gateway, your exported SDK will not contain parameters for the `Authorization` header, and is therefore unusable.
