### ISSUE TITLE
Fails to install when going through Docker and volume

### ISSUE THREAD

**Issue by nbigaouette-eai** [serverless/serverless#4660]
# This is a Bug Report

## Description

I want to setup a Docker image for our project that will contains some build dependencies (including nodejs and npm) for newcomers quick bootstraping and reproductibility. For this, I plan to mount our code working directory as a volume inside the Docker container. By using this volume from inside the container `npm install`'s output can be reused between runs and changes to the code outside the container will be visible from inside.

#### What went wrong?

Unfortunately, serverless fails to install that way when using macOS (Linux seems fine). I don't know why.

#### What did you expect should have happened?

Serverless installed in `$(PWD)/node_modules`.

#### What was the config you used?

Default, empty one, as created with `npm init`.

```
> uname -a
Darwin m.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
> docker --version
Docker version 17.12.0-ce, build c97c6d6
```

### To Reproduce

I can reproduce it with a simple setup. For this I'll use the official `node` Docker image (version 9.4.0, based on Alpine Linux):

1. Create an empty package somewhere, accepting defaults:

    ```
    > mkdir ~/tmp/issue
    > cd ~/tmp/issue
    > docker run -it --rm --volume $(PWD):/cwd --workdir /cwd node:9.4.0-alpine npm init --yes
    ```

    Wrote to /cwd/package.json:

    ```
    {
      "name": "cwd",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "keywords": [],
      "author": "",
      "license": "ISC"
    }
    ```
2. Attempt to install serverless:
    ```
    > cd ~/tmp/issue
    > docker run -it --rm --volume $(PWD):/cwd --workdir /cwd node:9.4.0-alpine npm install serverless
    npm WARN cwd@1.0.0 No description
    npm WARN cwd@1.0.0 No repository field.

    npm ERR! path /cwd/node_modules/serverless/bin/serverless
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall chmod
    npm ERR! enoent ENOENT: no such file or directory, chmod '/cwd/node_modules/serverless/bin/serverless'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2018-01-16T20_39_12_811Z-debug.log
    ```

Similar or dependent issues:
* https://github.com/docker/for-mac/issues/2296
* https://github.com/docker/for-mac/issues/76

## Additional Data

* ***Serverless Framework Version you're using***: Trying to install 1.25.0 (latest at time of writing)
* ***Operating System***: macOS High Sierra 10.13.2 (17C205)
* ***Stack Trace***: None
* ***Provider Error messages***: None

EDIT: Here are the logs (in gzip format):
* [2018-01-16T20_53_57_045Z-debug.log.gz](https://github.com/serverless/serverless/files/1636775/2018-01-16T20_53_57_045Z-debug.log.gz)
* [npm_install_verbose_serverless_20180116_15h53.log.gz](https://github.com/serverless/serverless/files/1636780/npm_install_verbose_serverless_20180116_15h53.log.gz)

**Comment by pjlittle** [comment]
+1 ran into the same. Tried various flavors of node/npm images, but no dice. 

Other packages build just fine, likewise if I remove the serverless dependency, everything else installs as expected.

**Comment by laurenfb** [comment]
I've also run into this intermittently. Oddly, it worked on a colleague's box and not mine despite identical configuration. After several hours yesterday the error abruptly stopped appearing (maybe around 3:30pm PST). So @pjlittle maybe try again? ¯\\\_(ツ)\_/¯

**Comment by laurenfb** [comment]
Oh hey, this fun issue is back with no explanation. @pjlittle and @nbigaouette-eai, did you ever figure out what caused it? Or how to mitigate it?

**Comment by nbigaouette-eai** [comment]
I've never been able to figure this out... :( I've passed too much time on this before creating that minimal example above.

I'm not familiar enough with npm to understand what is causing this. The error message above seems to be something happening _after_ the real problem; it complains it cannot chmod the binary, but there is just no binary at all! A copy somewhere (or maybe a link creation?) is failing but the error is caught later on...

**Comment by laurenfb** [comment]
Thanks. It is surprising because it's so intermittent.

**Comment by laurenfb** [comment]
I've been able to solve this by removing serverless from my `package.json`, then running `npm install -g serverless`, then `npm install` to install the rest of the package.

**Comment by nbigaouette-eai** [comment]
I'm re-trying this using docker `18.03.0-ce-mac60 (23751)` on High Sierra 10.13.4.

I've been running this 10 times:
```
rm -fr node_modules/ package* && \
    docker run -it --rm -v $(PWD):/cwd -w /cwd node:9.4.0-alpine npm init -f && \
     docker run -it --rm -v $(PWD):/cwd -w /cwd node:9.4.0-alpine npm install --verbose serverless
```
and it failed 7 time (serverless 1.26.1).

**Comment by james-w-arnold** [comment]
I'm having the same issue. I'm running npm install (serverless is not included in the packages) then npm install -g serverless. It either gets stuck on this step or installs after a very long period (30mins plus).

**Comment by gauravve** [comment]
Seems to work on 10.10.0

![image](https://user-images.githubusercontent.com/2516564/45252678-f2d3bc00-b39d-11e8-80ac-50685404c991.png)

**Comment by pmuens** [comment]
Closing since this is an issue with the used Docker image and not Serverless itself. Feel free to continue the discussion...
