### ISSUE TITLE
sls deploy may not work after failure

### ISSUE THREAD

**Issue by joebowbeer** [serverless/serverless#4667]
# This is a Bug Report

## Description

`sls deploy` of AWS Lambda claimed to succeed, but then failed because of a permission issue.

Then the bug happened..

* What went wrong?

A subsequent `sls deploy` also claimed to succeed because the package was already deployed, when in fact it had not been deployed.

> Service files not changed. Skipping deployment...

Is `sls deploy --force` the recommended workaround in this situation?

* What did you expect should have happened?

Subsequent `sls deploy` should have deployed the lambda.

* What was the config you used?

sls version 1.25.0
aws / nodejs6.10 / us-west-2

* What stacktrace or error message from your provider did you see?

> Service files not changed. Skipping deployment...

Similar or dependent issues:
* #3679 ?
* #3964 ?

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: macOS 10.13.2 
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by horike37** [comment]
Hi @joebowbeer.

>Is sls deploy --force the recommended workaround in this situation?

Yes, you are right.

In general, the framework skip deployment if you didn't update both of functions code and content of serverless.yml.

**Comment by derwaldgeist** [comment]
This is kinda strange. I changed my serverless.yml file to change the security settings of an S3 bucket, but it won't change it. Even if I change some code in my func, it won't do it. Forcing fails, too, because it does not seem to be compatible with the includeModules / forceExcludes option for AWS packages.

**Comment by derwaldgeist** [comment]
Update: After I changed the bucket name, it worked. But not if I just changed the IAM access right settings.

**Comment by naingyelin** [comment]
After a failed deployment and on the next run serverless will first complain that the stack is in the rolled back state, you have to delete the stack which is in the rolled back state. After if serverless says nothing has changed so it will skip the deployment, you should empty the deployment bucket.

**Comment by ctranstrum** [comment]
This is still a problem.

```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service nodejs-test.zip file to S3 (11.18 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......................................
Serverless: Operation failed!


  Serverless Error ---------------------------------------

  An error occurred: TestDynamoDB - User: sls is not authorized to perform: dynamodb:DescribeTimeToLive on resource: TestDynamoDB (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: AccessDeniedException.
```
At this point I updated the permissions on the user account, and then:
```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
```

**Comment by medikoo** [comment]
@joebowbeer I believe this was fixed wit https://github.com/serverless/serverless/pull/6520

Please close if it's the case
