### ISSUE TITLE
Deploying with transfer acceleration to eu-west-2 fails due to auth mechanism used

### ISSUE THREAD

**Issue by serenitus** [serverless/serverless#4670]
# This is a Bug Report

## Description

When deploying to eu-west-2 with transfer acceleration enabled I receive the following error:

`The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

At this point the deployment aborts. I expected to see the deployment succeed.

I believe this might be related to the following comment in the implementing issue (#4252) where it is stated:

> Apparently because of an SDK issue (discussed [here](https://github.com/aws/aws-sdk-js/issues/281#issuecomment-314045508)), I also had to force signatureVersion = 'v2'.

According to https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html, AWS regions opened after January 30, 2014 will only support v4 signatures. London (eu-west-2) was created in late 2016 and therefore has no support for this forced v2 signature.

Obviously preferably this should be fixed but otherwise should at least be noted in the docs.

## Additional Data

* ***Serverless Framework Version you're using***:

1.25.0

* ***Operating System***:

OSX High Sierra

* ***Stack Trace***:

n/a

* ***Provider Error messages***:

`The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

**Comment by HyperBrain** [comment]
Hi  @serenitus , thanks for submitting the issue 👍 

We should check if the AWS SDK bug mentioned in the discussion you referenced above is still present. If not, we should move to v4 signatures, as otherwise more regions might stop working.

**Comment by und3fined** [comment]
Error `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.` available on:

- Asia Pacific (Mumbai) - ap-south-1
- Asia Pacific (Seoul) - ap-northeast-2
- Canada (Central) - ca-central-1
- US East (Ohio) - us-east-2

**Comment by serenitus** [comment]
@und3fined well... yes... that's the first thing I did. In my case, having seen the changelog, I experimentally enabled the option on an existing deployment to see if there were any improvements - there were not; quite the opposite :)

**Comment by und3fined** [comment]
This is bug =))

https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L331
