### ISSUE TITLE
CLI autocomplete not working with Serverless "shortcuts" slss, sls

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#4671]
# This is a bug report

## Description

When typing `slss [TAB][TAB]` or `sls [TAB][TAB]` Serverless autocompletion does not work, I see my files and folders instead. I expect autocompletion should have worked exactly like it works with `serverless [TAB][TAB]`.

## Additional Data

* ***Serverless Framework Version***: 1.25.0
* ***Operating System***: Xubuntu 17.04
* ***Bash***: GNU bash 4.4.7(1)
* ***Terminal***: xfce4-terminal 0.8.4

**Comment by HyperBrain** [comment]
Hi @lorenzos , good catch 👍 

I assume that the tabtab configuration done on installation only respects "serverless" as targeted command, but not sls or slss. I agree that this should be added to produce a consistent behavior.
