### ISSUE TITLE
ServerlessError

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [serverless/serverless#4679]
# Serverless Error

I am facing this issue when I run `serverless deploy -v`  can someone help me?

`
 ServerlessError: Signature not yet current: 20180124T021406Z is still later than 20180123T131609Z (20180123T131109Z + 5 min.)
`
### Environment Information
* Serverless Version:     1.25.0:
* Node Version:           8.9.3:
* OS:                     win32:

**Comment by horike37** [comment]
Hi @Abdul-majid-ashrafi :smile: 
You may misconfigure the server time on the laptop the Serverless run.

Would be same error: https://forums.aws.amazon.com/thread.jspa?threadID=134543
