### ISSUE TITLE
SLS not working with aws-java-gradle template

### ISSUE THREAD

**Issue by itonics-tbeauvais** [serverless/serverless#4680]
All I do is install sls globally and excute the following

```
BacMook-of-Terror:serverless tbeauvais$ sls create --template aws-java-gradle
Serverless: Generating boilerplate...
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.25.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-java-gradle"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name
```
Then build with the Gradle Wrapper that was downloaded

```
BacMook-of-Terror:serverless tbeauvais$ ./gradlew build
Parallel execution is an incubating feature.
:compileJava
:processResources
:classes
:jar
:assemble
:buildZip
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 1.01 secs
```
And then try to invoke a simple "hello" function
```
BacMook-of-Terror:serverless tbeauvais$ sls invoke local --function hello
Serverless: Building Java bridge, first invocation might take a bit longer.
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:
```

It looks like it is trying to call `mvn` which I do not have, nor was specified. Any ideas guys?

**Comment by horike37** [comment]
Hi @itonics-tbeauvais. It seems like you don't have maven installed, it's required to build the Java bridge.

**Comment by HyperBrain** [comment]
@itonics-tbeauvais Did @horike37 's suggestion solve your problem?

**Comment by drkmullins** [comment]
We experienced this issue on Win10 (with maven installed), and it looked like this was the root cause:
https://github.com/nodejs/node-v0.x-archive/issues/2318

One fix that seems to work is adding the `{ shell: true }` option to the `spawn` at:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L232-L236

```
const mvn = spawn('mvn', [
  'package',
  '-f',
  path.join(javaBridgePath, 'pom.xml'),
], { shell: true });
```

Should be able to get a PR up for it if I get a few over the next couple days. For now, we've worked around by manually running the `mvn package` command inside `.../serverless/lib/plugins/aws/invokeLocal/java`

**Comment by kdavisk6** [comment]
This should be added to the documentation.  Those that use Gradle may not have Maven installed as well.

**Comment by cardosomarcos** [comment]
@drkmullins nice, this worked!
