### ISSUE TITLE
Passing params? (GET/POST, querystring, anything!)

### ISSUE THREAD

**Issue by Jonovono** [serverless/serverless#469]
Hi. Exploring this library right now. 

Something that I am still puzzled about is working with params / querystrings. 

I've figured out I need to do something like this:

              "requestParameters": {"integration.request.querystring.foo": "method.request.querystring.foo"},
          "requestTemplates": {
          "application/json": {"foo": "$input.params('foo')"}
          },

Is this correct? But how do I then access this?

    module.exports.handler = function(event, context) {
	console.log("hello")
	console.log(event)

Also how would this be defined for post params and what not?

If there is a good demo somewhere that would work too! Thanks.

**Comment by remicastaing** [comment]
Hello @Jonovono , take a look at at [this examples](https://github.com/remicastaing/serverless-examples).

If you want to access to logs, try with Cloudwatch. Maybe you will find your console logs there.

**Comment by Jonovono** [comment]
@remicastaing Great, thanks! This is what I was looking for. Seem to have gotten it working. :)

**Comment by marckaraujo** [comment]
Or just use:     let data = event.queryStringParameters;

**Comment by peterbraden** [comment]
are there any docs about this? This is very confusing. event.queryStringParameters is null for me.

**Comment by marckaraujo** [comment]
@peterbraden `event.queryStringParameters` only works for 1.0+

**Comment by buggy** [comment]
@peterbraden Also queryStringParameters is null if there are no query string parameters.

**Comment by jamesmoriarty** [comment]
https://forum.serverless.com/t/can-you-define-a-url-query-string-parameter-for-a-get-request/292/10

e.g.

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          method: get
          path: whatever
          request:
            template:
              application/json: >
                {
                  "foo" : "$input.params('foo')",
                  "someData": "$input.params('some_data')"
                }
```

**Comment by ozbillwang** [comment]
Seems above codes don't work with http-proxy integration (#3953)
