### ISSUE TITLE
[help wanted] Serverless says docker is not installed but it is.

### ISSUE THREAD

**Issue by SomeNerdNamedSteve** [serverless/serverless#4695]
I am running into issues with Docker.  While docker is installed,  I get the error that `docker not found! Please install it.`.  However, docker is installed.  Here is my yml file:

service: image-bot

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.image
    events:
      - http:
        path: /image
        method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
`

Is there anything else I need?  I have a requirements.txt file as well.

**Comment by waylanwong** [comment]
Had the same problem until I created and activated a virtualenv as described in this documentation page:

https://serverless.com/blog/serverless-python-packaging/

**Comment by brianneisler** [comment]
Closing this as @waylanwong has a suggested answer with no response. Will reopen if there are further issues.

**Comment by estahn** [comment]
For everyone coming here with this issue. The error message is misleading, the docker command execution failed and everything is munched into this single error message. In my case, the `Dockerfile` had an issue and wasn't building: `Error: `docker build -f Dockerfile -t sls-py-reqs-custom .` Exited with code 1`.

**Comment by diman82** [comment]
> For everyone coming here with this issue. The error message is misleading, the docker command execution failed and everything is munched into this single error message. In my case, the `Dockerfile` had an issue and wasn't building:
> 
> ```
> Error: `docker build -f Dockerfile -t sls-py-reqs-custom .` Exited with code 1`.
> ```

This is the true reason, real shame on serverless framework not to propagate the true error.
