### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by senseibaka** [serverless/serverless#4697]
# This is a Bug Report

## Description
After upgrading to `serverless@1.26.0`, I am now receiving the following error during `serverless deploy`:
```
Cannot read property 'name' of undefined
```

My `serverless.yml` has not changed since the upgrade (previous version is `1.25.0`. It's a fairly big config, but I can attempt to provide a cut-down version if required. In the meantime, you can find the trace below.

## Additional Data

* ***Stack Trace***:
```
<...snip...>
Serverless: Packaging service...

  Type Error ---------------------------------------------

  Cannot read property 'name' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'name' of undefined
    at AwsCompileApigEvents.getResourceName (%AppData%\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\apiGateway\lib\resources.js:251:42)
    at _.forEach (%AppData%\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\apiGateway\lib\cors.js:10:33)
    at %AppData%\npm\node_modules\serverless\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (%AppData%\npm\node_modules\serverless\node_modules\lodash\lodash.js:3001:24)
    at %AppData%\npm\node_modules\serverless\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (%AppData%\npm\node_modules\serverless\node_modules\lodash\lodash.js:9359:14)
    at AwsCompileApigEvents.compileCors (%AppData%\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\apiGateway\lib\cors.js:9:7)
From previous event:
    at Object.package:compileEvents [as hook] (%AppData%\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\apiGateway\index.js:55:12)
    at BbPromise.reduce (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
    at PluginManager.spawn (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:390:17)
    at Deploy.BbPromise.bind.then.then (%AppData%\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (%AppData%\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:113:10)
    at BbPromise.reduce (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
    at PluginManager.run (%AppData%\npm\node_modules\serverless\lib\classes\PluginManager.js:403:17)
    at variables.populateService.then (%AppData%\npm\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (%AppData%\npm\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (%AppData%\npm\node_modules\serverless\bin\serverless:42:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.11.3
     Serverless Version:     1.26.0
```

**Comment by HyperBrain** [comment]
@senseibaka Thanks for letting us know.

It seems that the CORS preflight creation now fails for you and does not find a previously (in 1.25) existing resource anymore. @horike37 This looks to me like a side-effect of the shared ApiGateway implementation that moved some name resolutions into `getXXXX` functions.

**Comment by marlomgirardi** [comment]
I have the same issue...

In my case, the problem was the documentation...

The doc suggests something like this:
```yml
apiGateway:
    restApiId: xxxxxxxxxx
    restApiRootResourceId: xxxxxxxxxx
    restApiResources:
      '/users': xxxxxxxxxx
      '/users/create': xxxxxxxxxx
```

when de code waits this:

```yml
apiGateway:
    restApiId: xxxxxxxxxx
    restApiRootResourceId: xxxxxxxxxx
    restApiResources:
      'users': xxxxxxxxxx # Without "/"
      'users/create': # Without "/"
```

So, when the code comes to `this.apiGatewayResources[path].name` inside the `getResourceName` will get this error: ` Cannot read property 'name' of undefined`.

* Sugestion:
Accept both cases, or only with "/". Would be more suggestive, at least for me.

Doc with problem:
- [Serverless.yml](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)
- [ApiGateway](https://serverless.com/framework/docs/providers/aws/events/apigateway/#lambda-proxy-integration)

**Comment by dpwrussell** [comment]
I think I am also seeing this issue. It does not seem to actually fail deployment though, but it's disconcerting.

```yaml
  apiGateway:
    restApiId: xxxxxxxxxx
ApiGatewayRestApiId
    restApiRootResourceId: xxxxxxxxxx
ApiGatewayRestApiRootResourceId
    restApiResources:
      /image/{uuid}: xxxxxx
```

Then at the end of the deployment process

```bash
...
Serverless: Checking Stack update progress...
..............
Serverless: Stack update finished...
Serverless: Cannot read property 'id' of undefined
...
```

It seems to deploy normally, but I'd like to get rid of this error. I tried running in debug mode, but there was no more pertinent information.

If I remove the entire `apiGateway` and let my deployment build a new API Gateway for my function+endpoint, then that error does not appear.

Happy to provide any further information required.

**Comment by senseibaka** [comment]
I ended up switching to writing plain old SAM+CloudFormation templates, so this is no longer an issue for me.

For me, it turned out CloudFormation templates are pretty easy to write, and much easier for me to bend to my will than a framework which generates them for me.

**Comment by dpwrussell** [comment]
Also confirmed on
```bash
$ serverless --version
1.29.2
```

**Comment by naingyelin** [comment]
The same for version 1.32.0
I was able to get it to work with the serverless template below.

`service: shared-api-gateway
provider:
  name: aws
  profile: default
  stage: dev
  region: ap-southeast-2
  apiGateway:
    restApiId: 
      Ref: SharedApiGw
    restApiRootResourceId:
      Fn::GetAtt: 
        - SharedApiGw
        - RootResourceId 
    restApiResources:
      hello: 
        Ref: Hello
package:
  individually: true
  excludeDevDependencies: true
functions:
  hello: # A Function
    handler: handler.hello # The file and module for this specific function.
    description: hello world function # The description of your function.
    runtime: nodejs6.10 # Runtime for this specific function. Overrides the default which is set on the provider level
    package:
      include: # Specify the directories and files which should be included in the deployment package for this specific function.        
        - handler.js
        - package.json
        - package-lock.json
      exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
        - .git/**
        - serverless.yml
    events: # The Events that trigger this Function
      - 
        http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.  Learn more in "events/apigateway"
          path: hello # Path for this endpoint
          method: get # HTTP method for this endpoint
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
resources: # you can add CloudFormation resource templates here
  Resources:
    SharedApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: SharedApiGateway.${self:provider.region}
    Hello:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: 
          Ref: SharedApiGw
        PathPart: hello
        ParentId: 
          Fn::GetAtt:
            - SharedApiGw
            - RootResourceId
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: SharedApiGw
      Export:
        Name: sharedApiGateway-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
         Fn::GetAtt:
          - SharedApiGw
          - RootResourceId
      Export:
        Name: sharedApiGateway-rootResourceId
`

**Comment by ccarnero** [comment]
Hi,

Trying to automate our deployment process I came across with this code: https://github.com/pavelvlasov/serverless-js-config-example which uses a Javascript's configuration file; and I faced with this issue. 

Digging into serverless code I found the function [resources.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js); based on @marlomgirardi  comment, I replaced every occurrence of the path variable from line  **234 to 243** to `$/path` and the issue goes away, once I deploy my stack to AMZ everything seems to be right

Because of my lack of knowledge related to amazon's APIG, and how serverless interact with it I'm not sure if this change could impact negatively in other services; that's why I didn't create a new PR; do all these things have some sense? is there a bug or I missing something? 

Best Regards
Christian

**Comment by 300LiterPropofol** [comment]
> I have the same issue...
> 
> In my case, the problem was the documentation...
> 
> The doc suggests something like this:
> 
> ```yaml
> apiGateway:
>     restApiId: xxxxxxxxxx
>     restApiRootResourceId: xxxxxxxxxx
>     restApiResources:
>       '/users': xxxxxxxxxx
>       '/users/create': xxxxxxxxxx
> ```
> 
> when de code waits this:
> 
> ```yaml
> apiGateway:
>     restApiId: xxxxxxxxxx
>     restApiRootResourceId: xxxxxxxxxx
>     restApiResources:
>       'users': xxxxxxxxxx # Without "/"
>       'users/create': # Without "/"
> ```
> 
> So, when the code comes to `this.apiGatewayResources[path].name` inside the `getResourceName` will get this error: ` Cannot read property 'name' of undefined`.
> 
> **Observation:** Now the don't have this error, but we have a ConflicktException `Method already exists for this resource (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: bd6740c0-6644-11e8-beec-fd91d4baa58b).`
> 
> **Suggestion:** Accept both cases, or only with "/". Would be more suggestive, at least for me.
> 
> Doc with problem:
> 
> * [Serverless.yml](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)
> * [ApiGateway](https://serverless.com/framework/docs/providers/aws/events/apigateway/#lambda-proxy-integration)

Hi @marlomgirardi , I am running on serverless 2.41.2 and having exactly the same issue still, with a `/`  there is error ` Cannot read property 'name' of undefined`, without `/` there is error `An error occurred: ApiGatewayMethodPatsDashreportsOptions - Method already exists for this resource (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: d93b6d8a-cfc7-40fd-ac05-b8102b3c0028; Proxy: null).` I wonder how did you fix the code in the end? Thanks : )
