### ISSUE TITLE
Deploy node and Java lambdas within same project

### ISSUE THREAD

**Issue by emaRaf** [serverless/serverless#4698]
Hi, At the moment if  i use serverless-webpack plugin it deploys node js lambdas only, else java lambdas only. Is there some config to deploy both at the same time?

**Comment by HyperBrain** [comment]
There is a pull request open https://github.com/serverless-heaven/serverless-webpack/pull/256 that will allow mixed projects. But I cannot merge it as long as it is not properly tested. Additionally there seem to be some issues left with the PR.

**Comment by pmuens** [comment]
Closing this issue since it's not related to the Serverless Framework but the serverless-webpack plugin. Furthermore @HyperBrain has an open PR (see above) which fixes this.
