### ISSUE TITLE
AWS Go Hello World example docs: sample code and yml missing?

### ISSUE THREAD

**Issue by whoyawn** [serverless/serverless#4707]
# This is a Bug Report

## Description

Browsing the [Go example](https://github.com/serverless/serverless/tree/master/docs/providers/aws/examples/hello-world/go), I don't see any sample code + `.yml`. For the other languages there's a sample handler, so I was wondering if I was missing something or it hasn't been implemented yet.

**Comment by pmuens** [comment]
Hey @whoyawn thanks for opening 👍

The readme file is just a tutorial. You can find all the examples in https://github.com/serverless/examples.
