### ISSUE TITLE
Git BASH on Windows serverless install error

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [serverless/serverless#4717]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? On Windows using git bash install fails. Looks like it's a git bash to windows path issue.
* What did you expect should have happened? The install to work.
* What was the config you used? N/A.
* What stacktrace or error message from your provider did you see?
$ npm install serverless -g
C:\Users\Michal Hobbs\AppData\Roaming\npm\sls -> C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\bin\serverless
C:\Users\Michal Hobbs\AppData\Roaming\npm\serverless -> C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\bin\serverless
C:\Users\Michal Hobbs\AppData\Roaming\npm\slss -> C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\bin\serverless

> spawn-sync@1.0.15 postinstall C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\spawn-sync
> node postinstall

> serverless@1.26.0 postinstall C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless
> node ./scripts/postinstall.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\scripts\C:\Program Files\Git\usr\bin\bash.sh'
    at Object.fs.openSync (fs.js:646:18)
    at fs.readFileSync (fs.js:551:33)
    at Complete.script (C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\src\complete.js:373:14)
    at Installer.writeTo (C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\src\installer.js:91:34)
    at Installer.handle (C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\src\installer.js:80:21)
    at Commands.install (C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\src\commands\index.js:75:22)
    at Object.<anonymous> (C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\src\cli.js:33:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
Could not auto-install serverless autocomplete script.
Please copy / paste the script above into your shell.
+ serverless@1.26.0
added 302 packages in 31.531s

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: Windows 10 Pro
* ***Stack Trace***: See Above
* ***Provider Error messages***: See Above
* ***Work Around***: Open windows command line and run install then you can go back to using git bash.

**Comment by HyperBrain** [comment]
It seems that the tabtab installation fails because of a wrong path substitution in postinstall.
We should check if there are any OS dependent path handlings in there.
`Error: ENOENT: no such file or directory, open 'C:\Users\Michal Hobbs\AppData\Roaming\npm\node_modules\serverless\node_modules\tabtab\scripts\C:\Program Files\Git\usr\bin\bash.sh'`

**Comment by infernocloud** [comment]
Existing issue with some discussion and a possible workaround:
#3914

**Comment by zenlor** [comment]
It's a postinstall problem in serverless.

https://github.com/serverless/serverless/issues/4069

**Comment by regina-work** [comment]
is there a workarouind? i am having same problem git-bash and windows7

**Comment by infernocloud** [comment]
@regina-work I found that the installation still works, you just don't get the tabtab autocompletions.

**Comment by Nnxoxo** [comment]
Have you tried guys to use cmd? I also encountered this issue, but just running this command in cmd, seems, solving the issue.

**Comment by medikoo** [comment]
Closing as since then `tabtab` installation was refactored to be opt-in, and we rely on upgraded version which install differently. So bug is no longer relevant
