### ISSUE TITLE
Trivial: add a log line to the hello world action for the quick start guide

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless#4721]
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* To facilitate understanding of the `serverless logs -f hello -t` feature described in https://serverless.com/framework/docs/providers/openwhisk/guide/quick-start/ , add a log line to https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/openwhisk-nodejs/handler.js
* It would enable users to use the quick start as it is and see the actual logs come through.

Similar or dependent issues:
* #12345

## Additional Data

* 1.26.0
* Mac OSX
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by tharun208** [comment]
Hi, I wanted to work on this issue.
