### ISSUE TITLE
--template-path out of memory error when referencing the home dir (~/...)

### ISSUE THREAD

**Issue by gbleu** [serverless/serverless#4724]
# This is a Bug Report

## Description

* What went wrong?
Trying `--template-path` with local `aws-nodejs` template ends up in out of memory error and an empty `my-service` folder :
```
$ serverless create --template-path ~/AppData/Roaming/nvm/v6.10.3/node_modules/serverless/lib/plugins/create/templates/aws-nodejs --path ./my-service
```

* What did you expect should have happened?
A fully functional service in the `my-service` folder.

* What was the config you used?
node v6.10.3 installed with [nvm-windows](https://github.com/coreybutler/nvm-windows)

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Windows 10
* ***Stack Trace***:
```
<--- Last few GCs --->

  146731 ms: Mark-sweep 1410.9 (1444.1) -> 1411.1 (1444.1) MB, 617.8 / 0.0 ms [allocation failure] [scavenge might not succeed].
  147311 ms: Mark-sweep 1411.1 (1444.1) -> 1415.9 (1428.1) MB, 579.6 / 0.0 ms [last resort gc].
  147886 ms: Mark-sweep 1415.9 (1428.1) -> 1420.6 (1428.1) MB, 574.9 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000387AFACFB49 <JS Object>
    1: captureStackTrace [native messages.js:~686] [pc=0000023CEC36154A] (this=00000047A4C95BE9 <JS Global Object>,Q=00000039197FDF01 <an Error with map 000001541681DB11>,bp=00000387AFAB73B9 <JS Function Error (SharedFunctionInfo 00000387AFA79B81)>)
    2: new constructor(aka Error) [native messages.js:639] [pc=0000023CEC39F9D1] (this=00000039197FDF01 <an Error with map 000001541681DB11>,bn=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
@gbleu Does thos only happen, if you reference the template from within node_modules? Can you try to copy the template folder somewhere else and check if that makes a difference?

**Comment by gbleu** [comment]
@HyperBrain Seems related to the `~/` 
Working fine with `--template-path ./templates/aws-nodejs`, but same error with `--template-path ~/Desktop/templates/aws-nodejs`.

**Comment by HyperBrain** [comment]
Ok. That's a good explanation. I will adapt the issue subject accordingly and set proper labels. Then someone can fix it.

**Comment by ajschmidt8** [comment]
this was discussed in a Node discussion here: https://github.com/nodejs/node/issues/684

some people think `~` expansion shouldn't be handled by Node since it's not a shell. any comments on this, @HyperBrain?

**Comment by SusanESmith** [comment]
Is this still relevant to others?  If so, I'd like to put a fix in.
