### ISSUE TITLE
Question - packaging of all modules together for a project

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#473]
Is it expected that all modules/functions are packaged together for a entire project? As I started to add more functions and modules, I noticed that all the code sizes for the lambdas within that project are all the same so I downloaded a few of the zip files only to find that every function and modules is packaged with every other one.

I assume this makes execution less efficient when AWS is initialising the environment as they have to download the code for every function in a project even if they don't depend on each other.

**Comment by joostfarla** [comment]
To ensure all dependencies are included, the full contents of the `back` dir is included in the package by default. To reduce the code size, you can have a look at the [optimizer plugin](https://github.com/serverless/serverless-optimizer-plugin), which bundles the code using `browserify`. I would recommend using the `master` branch for now, because the plugin is work-in-progress.

**Comment by c-knowles** [comment]
Thanks, will give that a go.

All of my modules are completely separated in terms of dependencies, I thought that's how it was supposed to be. I've been loading my dependencies into each module by going to the appropriate directory with the package.json and using ```npm install DEP --save```, is that not the expected method to add dependencies? Just wondering which ones you mean.

**Comment by joostfarla** [comment]
This was one of the main concerns of the current version (v0.0). V0.1 addresses this issue and introduces a new concept called `components`. The `back` dir will be dropped in favor of components. In the new setup, all modules within a component share a single dependency configuration.

**Comment by c-knowles** [comment]
Understood, thanks for the update. I'll plug away with the plugin for now then as I realise the next big update is coming.

**Comment by c-knowles** [comment]
Now that 0.1.x is out, I'm assuming the best way to get everything packaged separately is to create a component for each module/function. The project I'm going through is this roughly:
- all the same node.js runtime
- several endpoints which provide various pieces of functionality under the same software project (but all do quite different things)
- not a lot of shared npm dependencies between the modules although there is a few common ones

At first it seems like I'd want to set those up as separate functions within a component since they are all lambda functions, but taking into account the above perhaps a component per function is better. Then I end up with something like project/function-name/function-name/function-name/handler.js!

SLS generates the same handler linked to lib/index.js each time although obviously this can be updated - is that what most people are doing? Trying to figure out the best way to share some local code between lambda functions without packaging the entire thing together when deploying.

**Comment by eahefnawy** [comment]
@c-knowles for your use case, I think it'd be better to create a single component for nodejs, where you can write all your modules/functions logic in the component `lib` folder. You're free to organize your modules and their functions the way you want, but you must have at least one module (you can't have functions directly inside components). These functions can then use the logic in the component `lib` folder.

You'll definitely need to update the `handler.js` for each function to work for you the way you want it. The boilerplate code you see inside is just for demo. Just keep in mind to keep as much logic as you could in the component `lib` folder to make your code easy to test, and keep the `handler.js` file as lean as possible (ie. just initializing classes and calling methods from the `lib` folder).

Hope this helps! and if you have any suggestions, please let us know! :blush:

**Comment by c-knowles** [comment]
Cool, thanks! Will go on that basis and for now just assume everything will be packaged together and perhaps I'll use the optimizer plugin as well when I get a chance.

**Comment by c-knowles** [comment]
I see in 0.4.0 that the concept of Modules has been deprecated. I was wondering for a while how introducing Components helped the original question around everything being packaged together, it seemed to add another layer but one where again everything is packaged together. Now Modules are going, it seems like Modules have just been replaced with Components but the concepts stay very similar?

I think it would be good to be able to have a bunch of shared code in a project but only package the appropriate pieces up for each function and only the relevant npm dependencies. Maybe that means representing the dependencies of each function although that could be overly complex compared with just using optimizer plugin. I'm interested to hear views on what is considered best practice for sharing private code between functions and between projects. The documentation mentions some simple examples so I'd be interested in some more complex scenarios.

**Comment by pmuens** [comment]
@c-knowles you could still use a module like structure. Resources you use (e.g. DynamoDB) can be added to the `s-resources-cf.json` file which can be placed in a component or it's subfolders.

This makes it easier to share code in a module related fashion.

This release note will outline it:
https://github.com/serverless/serverless/releases/tag/v0.4.0

Just my 2 cents about it.

**Comment by c-knowles** [comment]
That's quite interested, I was just reading some of that. I actually prefer to keep infrastructure pre-requisites in a completely separate CloudFormation template due to reasons like the AWS handling of updates to those, like described in https://github.com/serverless/serverless/issues/515. I'm not sure there would be much serverless could do to handle such situations.

In terms of sharing JS code and libs that are not in the public npm domain, any thoughts there? Say we had a few ongoing projects currently all wanting to share some code, we could combine all of those projects into a single Component with each project being a Module but that would mean everything gets packaged together and any updates mean multiple projects all have to update at the same time etc. I suppose private npm has potential or placing lib code outside of the Component directory (although not sure if serverless supports that).

**Comment by pmuens** [comment]
@c-knowles Yes that's also a valid point I haven't thought about yet. Maybe we could build something to support that.

Aside: https://github.com/serverless/serverless/issues/597 describes the motivation of the resources templates a little bit

**Comment by c-knowles** [comment]
I heard in https://github.com/serverless/serverless/issues/751 that Components are going. I'm curious whether they are being replaced or not so I can work out what changes I'll need to do to migrate. Looking for the VPC and multi account support.

I believe this is the structural changelog:
* 0.0.x had Modules and Functions
* 0.1.x introduced Components so had Components, Modules and Functions
* 0.4.x dropped Modules so had Components and Functions
  * Unfortunately each previously working 0.3.x project I tried didn't work with 0.4 as we got hit by various issues such as https://github.com/serverless/serverless/issues/631. Wasn't too hard to update.
* 0.5.x seems to be dropping Components so does that mean we just end up with Functions or are there alternative concepts coming?

**Comment by ac360** [comment]
@c-knowles I just added a response in #751 about why Components have been removed.  The functionality still exists, we just found a way to implement it more simply without the "concept" of Component, which is just unnecessary to learn at the end of the day.

**Comment by c-knowles** [comment]
Thanks for the explanation, I just saw https://github.com/serverless/serverless/issues/748 too. It sounds as though the changes might resolve this question since it's possible to package lambdas individually or actually any way a user wishes. Will wait for the latest docs and do the upgrade to confirm.

While learning Components is out, learning how the magic handlers work is in so people can understand where their root folder is, how their functions get packaged etc. Will you have any best practice layout examples in the docs? If we need some, I could work on a few example use cases to put there.
