### ISSUE TITLE
Error: Error: Resource has an ongoing conflicting operation

### ISSUE THREAD

**Issue by Vadorequest** [serverless/serverless#4738]
I ran `sls deploy` and killed it using `ctrl+c` during the process because I noticed I had made a mistake and it would fail. It was at the step where the dots `...` are displayed, and it had lasted for more than a minute.

Now, when I want to deploy again, I get this error message:

```
Error: Error: Resource 'projects/simulator-194400/global/deployments/sls-simulator-feedback-dev' has an ongoing conflicting operation: 'projects/simulator-194400/global/operations/operation-1518383973661-564f65161f948-86797fcc-ac814a5d'.
```

**Comment by Vadorequest** [comment]
By waiting a few more minutes, I was able to run `sls remove` to cleanup (it failed also when I tried before). 

But I guess doing a `sls deploy` would have worked too. I guess GCF needed a few minutes to do some internal cleanup after the first deployment had failed.

**Comment by mrdulin** [comment]
same issue. Any explain abou this?
