### ISSUE TITLE
Java template uses non-recommended version of Log4j

### ISSUE THREAD

**Issue by johnsgp** [serverless/serverless#4739]
# This is a Bug Report

## Description

* **What went wrong?** Lambda functions duplicate each log entry in CloudWatch when using Log4j
* **What did you expect should have happened?** There should be one entry in CloudWatch per call to logger.info(), logger.debug(), etc.
* **What was the config you used?** I ran `serverless create --template aws-java-maven` to create boilerplate code that included the Log4j dependencies and sample code.
* What stacktrace or error message from your provider did you see? Not applicable

The bug is with the boilerplate code created by `serverless create` which follows the pattern described in the [AWS documentation for Log4j 1.2](https://docs.aws.amazon.com/lambda/latest/dg/java-logging-log4j1.html). The heading of that page says that this is not recommended.

The solution would be to change the boilerplate to follow the pattern described in the [AWS documentation for Log4j 2](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html).  I've noticed that that page adds dependencies for `log4j-core` and `log4j-api` which are not required to be explicitly listed as they will be brought in by `aws-lambda-java-log4j2`.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by bwinant** [comment]
I looked into updating the aws-groovy-gradle and aws-java-gradle templates to Log4J2. Problem is there are some workarounds needed to incorporate Log4J2 into a shaded jar. There are known steps to handle this with Maven (the AWS docs have the extra Maven config necessary) but less so with Gradle. Found some references online of people trying to make it work and a couple of Github projects that looked promising, but didn't know how far I should go to make it work. If there is interest, I could have another go at it and update those templates as well
