### ISSUE TITLE
resources-cf template size max 51,200 bytes

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#474]
Amazon imposes a hard 51,200 byte limit on the size of a cloudformation template in the body of the request (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html). I recently ran into an issue where the resources-cf.json file used in my project exceeded this size. Even though this size had been exceeded, serverless seemed to indicate that the resources deployed succesfully but in fact amazon ended up rolling back the cloudformation stack.

I have two questions:
1. Shouldn't serverless have picked up on this issue and notified in the output?
2. What is the best way to get around this issue? I see that amazon allows nested stacks (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html) but I don't see anyway to easily integrate this functionality into my serverless project.

Thanks.

**Comment by tmilewski** [comment]
I was running into a few different, but somewhat similar issues, and decided to write a plugin to catch some of what you're talking about:

https://github.com/tmilewski/serverless-resources-validation-plugin
