### ISSUE TITLE
Unable to make work the hello function

### ISSUE THREAD

**Issue by wascou** [serverless/serverless#4747]
# This is a Bug Report

## Description

Just tried out of the box the hello function deployment, it does not work, here is my 

$ serverless deploy -v --force

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - xxx
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - xxx
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (409 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - xxx
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - xxx
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - xxx
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - xxx
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFor xxx
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: IamRoleLambdaExecution - xxx-us-east-1-lambdaRole already exists.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.5.0
     Serverless Version:     1.26.0

**Comment by pmuens** [comment]
Hey @wascou thanks for opening 👍

It looks like you've already deployed a service in the past to the AWS account. 
Additionally it seems that the created IAM role was not removed properly.

Once you go to your AWS console and remove the IAM role `IamRoleLambdaExecution - xxx-us-east-1-lambdaRole` you should be good and be able to re-deploy the service.
