### ISSUE TITLE
Deploy function not update function code in AWS Lambda but just deploy updates

### ISSUE THREAD

**Issue by fazelmk** [serverless/serverless#4748]
This is a Bug Report

## Description

if I try to deploy a single function ( only one function is giving me problem) the deploy process is finished with success but no event is generated in cloud Formation for the service and the code for the function is not updated. But if I deploy the whole service with serverless deploy the function is deployed without a problem.

I think only functions that are too big for inline change directly in aws console have this problem. Not sure, this is the second function that I have problem with and the first was too big to see the code in  aws console too.

For bug reports:
* What went wrong?
serverless deploy function return success and didn't update the code but serverless deploy updates the code

* What did you expect should have happened?
the code to be updated after deploy function funish

* What was the config you used?
serverless version 1.24.1
node.js 6.10

* What stacktrace or error message from your provider did you see?
No erros. Serverless on debug mode don't show any errors. and there is no event at cloud formation ( so no errors there too )

## Additional Data

* ***Serverless Framework Version you're using***:
serverless version 1.24.1

* ***Operating System***:
ubuntu 16.04

* ***Stack Trace***:
```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command webpack:invoke
Serverless: Load command webpack:watch
Serverless: Load command webpack:serve
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: Load command prune
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy:function
Serverless: Bundling with Webpack...
<<webpack output>>
Serverless: Invoke package:function
Serverless: Packaging function: getResource...
Serverless: Uploading function: getResource (661.61 KB)...
Serverless: Successfully deployed function: getResource
Serverless: Successfully updated function: getResource
Serverless: Invoke aws:common:cleanupTempDir
```

* ***Provider Error messages***:
No logs at aws. The deploy process to AWS probably was never started.

**Comment by HyperBrain** [comment]
Hi @fazelmk , thanks for reporting.

Can you first try to update Serverless (at least to 1.25) and serverless-webpack (to 4.3.0) and check if the problem is fixed then?

**Comment by fazelmk** [comment]
is the pull request #4247 in version 1.25? Because I'm using a custom branch with that function.

**Comment by fazelmk** [comment]
serveless on 1.26.0 (master branch)
serverless-webpack on  4.3.0

Still the same problem.

**Comment by HyperBrain** [comment]
Thanks, and the PR is in 1.26.

`serverless deploy --function` uses the AWS REST API to update the function and bypasses CloudFormation completely. So we cannot compare `deploy` with `deploy function` at all. BTW: deploy function should not be used in production systems as it leaves the CF state inconsistent and any rollback in your stack will have unexpected results.

That's also the reason why you do not see anything happen in the CloudFormation event tab.

From the logs it looks ok though: 
```
Serverless: Packaging function: getResource...
Serverless: Uploading function: getResource (661.61 KB)...
Serverless: Successfully deployed function: getResource
Serverless: Successfully updated function: getResource
```

Did you try to invoke the function after you deployed it separately?

**Comment by fazelmk** [comment]
I invoked. and the result is the same as before the deploy.

So if i shouldn't deploy production with deploy function am I supposed to use serverless deploy for production? 

For now it's only a prototype so I will keep using deploy function because it is way faster. And for some reason deploy gives me socket timeout, so deploy only works in my mobile network ( have no clue why, maybe port block from my internet provider, didn't look into it yet ).

**Comment by fazelmk** [comment]
Ok. I removed the whole stack, re deployed and now deploy function works.
There is automatic rollback when deploy fails? 
I got one deploy failure yesterday. maybe an automatic rollback with deploy messed with the stack state.

**Comment by HyperBrain** [comment]
> I got one deploy failure yesterday

Yes, that will have eliminated the function deploys because they are not tracked by CF.

A general approach is, to use "function deploy" for debugging (as you said it's much faster if you just want to test a debug version or some changes) and only use "deploy" for production.

**Comment by fazelmk** [comment]
Got it. 

Thanks for the help and quick response @HyperBrain
