### ISSUE TITLE
Java invoke local support for handlers that implement RequestStreamHandler

### ISSUE THREAD

**Issue by rcbass** [serverless/serverless#4750]
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:

When using Java to write a Lambda function, the handler can implement the RequestStreamHandler interface (see https://docs.aws.amazon.com/lambda/latest/dg/java-handler-using-predefined-interfaces.html and https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html#api-gateway-proxy-integration-lambda-function-java).

However, invoke local does not work in this case. It only currently works if the handler implements RequestHandler or does not use any of the predefined interfaces. 

This feature proposal is to add invoke local support for RequestStreamHandler.

Similar or dependent issues:
* None

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Windows 10
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by rcbass** [comment]
Please let me know if this makes sense, I am new to Serverless and AWS Lambda. If it does, I have a proposed solution ready, and can create a PR.

**Comment by HyperBrain** [comment]
Hi @rcbass . Thanks for the suggestion. Honestly, I do not use Java with AWS Lambda, so I'd yell at @serverless/vip ! Maybe there's someone out there who can rate this idea.
