### ISSUE TITLE
More documentation needed on apiGateway configuration

### ISSUE THREAD

**Issue by superandrew** [serverless/serverless#4753]
# This is a request for improved documentation:
## Description
It is pretty difficult from serverless documentation to understand how to configure 

    restApiRootResourceId
    restApiId

see: https://forum.serverless.com/t/multiple-services-under-directory/3803

A little more examples in the documentation section would help a lot.

**Comment by HyperBrain** [comment]
@superandrew Good catch!

**Comment by rohitshetty** [comment]
I have been experimenting with new apiGateway. The easiest way I found to configure this automatically is to have one service that deploys a resource of type `AWS::ApiGateway::RestApi` (using cloudformation template) and then we use serverless `Outputs` to make `restApiId` and `restApiRootResourceId` available as cloudformation variables to other services (or same in same service) to use. I would be happy to write more if you think this is the write way to do it.

**Comment by rohitshetty** [comment]
@HyperBrain Does the above solution sound good? If yes where can I document it? I am a beginner and really love serverless and want to contribute back. Any help would be appreciated. Thanks!

**Comment by HyperBrain** [comment]
Hi @rohitshetty , great that you try to help out here. 💯 

@horike37 As we do not used shared API Gateways, but you do, can you please give some advise here, so that @rohitshetty can proceed improving the docs?

**Comment by horike37** [comment]
@rohitshetty 
Sounds pretty good solution!
Could you please send a pull request with the explanation and example so that we can review and test?

**Comment by rohitshetty** [comment]
@horike37 Thank you! would be happy to make a PR. Where would be a good place to add details about this? I can fork, add the content and make a PR. (Sorry if this question sounds silly)

**Comment by horike37** [comment]
@rohitshetty 
I think would be good to add "Example the easiest way to configure" section at the end of https://github.com/serverless/serverless/blob/master/docs/providers/aws/events/apigateway.md#share-api-gateway-and-api-resources 

What do you think?

**Comment by rohitshetty** [comment]
Thank you @horike37 This is a good idea, Will update this and send a PR

**Comment by rohitshetty** [comment]
@horike37 I have updated the docs and made a PR. Let me know if it looks good or if it would need any changes. Thanks!
