### ISSUE TITLE
Unable to share provider config across services

### ISSUE THREAD

**Issue by estyh** [serverless/serverless#4761]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I have many unrelated lambda (aws) functions - each interacting with different api endpoints from external providers and then saving info to my db. There is no reason to group these functions together in a single cloudformation template, and certainly no reason to deploy them all if some environment variable or other configuration changes for a single function. The only way I see to do this is to have different services for each function, each with their own serverless.yml files, but I would like them to share provider info, as that doesn't change across my functions. 
I created a config.yml file in the root folder, with the provider info, and then each subfolder (representing a single function) has a serverless.yml file.
In the provider section, I am referencing the config.yml at the root.
This doesn't work. sls deploy -v (with debug var on) doesn’t show me any errors, it just stops after "Excluding development dependencies…" It creates the zip file, but it doesn’t go any further. It seems to me that the provider gets set up before the file variable gets interpolated, something like that.
If I copy/paste the provider info directly into the serverless.yml file, then it works as expected.

* What did you expect should have happened?
I expected the provider section to get fill with the values of the provider object in the file I was referencing.

*UPDATE*
I just found https://github.com/serverless/serverless/pull/4173 and after looking through the comments and source code there, I see that deploy function will actually update the function configuration as well - this is so very not clear from the docs!! But, my questions still stands, since I don't think it makes sense to put unrelated functions into one serverless file - for instance, when I create a new function, I don't see any need to re-deploy all the existing functions, but you can't just deploy the single function without running the general sls deploy first. I also have an issue that each function has to be it's own service (because if I have two serverless.yml files but they share a service name, when you deploy the second function, it will delete the first!!) - I really don't like that requirement, but maybe it's a separate feature request.

* What was the config you used?

This is the folder structure
```
lambda
  config.yml
  func1
    serverless.yml
    index.js
    package.json
    node_modules
```

the relevant part of func1/serverless.yml looks like this:
`provider: ${file(../config.yml):provider}`

and config.yml looks like this
```
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 300
  region: us-east-1
  ...and vpc stuff, role, etc...
```

* What stacktrace or error message from your provider did you see?
There was no error.

* ***Serverless Framework Version you're using***:
1.26.0

* ***Operating System***:
windows 10

* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @estyh . There have been major fixes and improvements in the variable system (esp. ordered and predictable resolution of variables). Can you try with the current master, if the file reference is now populated?

**Comment by pmuens** [comment]
Closing since we've made progress on this front. Feel free to reopen if this is still an issue.
