### ISSUE TITLE
memorySize changes not deployed

### ISSUE THREAD

**Issue by mashbourne** [serverless/serverless#477]
Seems like you have to run sls function deploy **twice** for function memorySize to update.

1) Update `s-function.json` function "memorySize"
2) sls function deploy
3) check aws console -> lambda function memory size has not changed
4) sls function deploy
5) check aws console -> lambda function memory size has updated

**Comment by ac360** [comment]
I can't recreate this either in `v0.1`.  Please let me know if it's still a problem for you @mashbourne and thank you for your input :)
