### ISSUE TITLE
Can't run "serverless deploy" due to missing openwhisk configuration property OW_APIHOST

### ISSUE THREAD

**Issue by vuxuanlai** [serverless/serverless#4777]
The below is log message when i run "serverless deploy". Could someone help me  to resolve this problem?

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling Functions...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiling Triggers & Feeds...
Serverless: Deploying Functions...

  Error --------------------------------------------------

  **Missing mandatory openwhisk configuration property: OW_APIHOST. Check .wskprops file or set environment variable?**

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.1
     Serverless Version:     1.26.0

**Comment by dchucks** [comment]
Facing same issue.

**Comment by sang-d** [comment]
you may need to set up credential for openwhisk
https://serverless.com/framework/docs/providers/openwhisk/guide/credentials/

**Comment by ahansson89** [comment]
Did you find the answer to this? I have the same issue. I did set up credentials as described

**Comment by juanestebanj** [comment]
Same here. Did you find the answer to this? I set up credentials as described

**Comment by darkFunction** [comment]
Also having this issue. `login` command does not create a `~/.wskprops` file.

**Comment by welkie** [comment]
I had this same issue. Running the command in the comment above fixed it. I'm going to submit a PR for the docs.

**Comment by welkie** [comment]
PR created: https://github.com/serverless/serverless/pull/5625

When merged, this issue can be closed.
