### ISSUE TITLE
AWS lambda, getting '/' for __dirname 

### ISSUE THREAD

**Issue by teebu** [serverless/serverless#4778]
# This is a question

## Description

For bug reports:
* What went wrong?

__dirname is returning `/` instead of the actual full path.

* What did you expect should have happened?

Without serverless, `__dirname` returns full path of current file.

* What was the config you used?

AWS, webpack. 

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:

1.26.1

* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pavelvlasov** [comment]
@teebu if you're using webpack to combine assets, you might need to add these lines to your `webpack.config` to have proper `__dirname` value
```js
target: 'node',
node: {
  __dirname: true,
},
```

**Comment by teebu** [comment]
Setting it to true made it blank. Setting it to false gave a path. I did some searching other people are confused about this as well. 

Is this not well documented or something?

**Comment by pavelvlasov** [comment]
Correct, [setting __dirname to true should fallback to default node.js](https://webpack.js.org/configuration/node/#node-__dirname) behavior, but it's not related to serverless.

**Comment by teebu** [comment]
Thank you pavel, you are right it's not related to serverless, its webpack. But it seems like setting it to `fasle` makes it fallback to nodejs.
