### ISSUE TITLE
add .nvmrc and specify node version for contributing

### ISSUE THREAD

**Issue by Vadorequest** [serverless/serverless#4780]
I want to contribute by adding a template, but I don't know which node version to use. There should be a `.nvmrc` file at the project root and it should also be told in the CONTRIBUTING.md file.

**Comment by HyperBrain** [comment]
Hi @Vadorequest, thanks for the suggestion. Serverless officially supports any Node version from 4.4.x on, so all code must be compliant for these versions. To ensure compliance, the unit tests are run with Node 4, 6 and 8.

The support of these versions originally comes from the Node versions that are supported on AWS and the fact that a lot of people use exactly the same version locally to have proper test results (especially when using "serverless invoke local").

However, it is a good idea to add that to the CONTRIBUTING.md file.

**Comment by Vadorequest** [comment]
I understand for 4 and 6, but why 8? It's definitely not supported by AWS.

Even thought there isn't just AWS to support, maybe other provider actually use node 8?

**Comment by HyperBrain** [comment]
I'm not sure and do not remember exactly why 8 is used. Maybe it was just for performance of the integration tests on Travis. @horike37 Do you remember?

**Comment by pmuens** [comment]
Closing this for now since several node versions are supported and `nvm` is not a specific tool we enforce. Feel free to continue the discussion...
