### ISSUE TITLE
Make the cloudformation template generated from serverless more readable

### ISSUE THREAD

**Issue by dankuchler** [serverless/serverless#4781]
# This is a Feature Proposal

## Description

By default or with a parameter could the JSON.stringify space parameter be used within serverless to generate the cloudformation template in a more readable format.

Currently the generated cloudformation template does not have whitespace to make it readable (I believe because we aren't providing any space parameter on the JSON.stringify call that is used to generate the CF template.  Using a space parameter might make it easier to review configuration and research issues within the CF template.

**Comment by exoego** [comment]
This feature seems already landed.

As least in v1.36.1, the JSONs in .severless directory already formatted with indents.
* cloudformation-template-create-stack.json
* cloudformation-template-update-stack.json
* serverless-state.json

Example: 

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/aws-nodejs-dev-hello"
      }
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": 
....
```

**Comment by dschep** [comment]
Agreed, @exoego, this is already implemented.
