### ISSUE TITLE
severless deploy erases existing functions in aws lambda, and replaces them with the functions defined in serverless.yml

### ISSUE THREAD

**Issue by lexax666** [serverless/serverless#4782]
if I have function_1, function_2 in my serverless.yml, like the following:
functions:
  get_near_bars_lambda:
    handler: handler.get_near_bars_lambda
  get_facebook_event_data_lambda:
    handler: handler.get_facebook_event_data_lambda

And there are function_3, function_4 on aws lambda, different from function_1, function_2:
function_3,
function_4

If I do serverless deploy, then function_3 and function_4 would be erased from lambda, and only function_1 and function_2 exist on aws lambda.

how should I config serverless so when I do serverless deploy the existing functions on aws lambda doesn't get erased? I don't have access to function_3 and function_4 in the above example because I am collaborating with someone else on the same aws lambda account.

Thank you in advance!

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
