### ISSUE TITLE
Serverless fails to deploy - Webback error, "Invalid configuration object"

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#4788]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?

Deploy won't work, webpack config is invalid.

* What did you expect should have happened?

I expected deploy to work.

* What was the config you used?

Fresh creation of a project:

```sh
$ sls create -u aws-nodejs-ecma-script -n mytest
$ sls plugin install -n serverless-webpack
$ sls deploy
```

* What stacktrace or error message from your provider did you see?

```
  Webpack Options Validation Error -----------------------

  Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by ffxsam** [comment]
Never mind, this is an issue with the `serverless-webpack` plugin.

**Comment by HyperBrain** [comment]
Hi @ffxsam , thanks for the report 👍 

It seems that the webpack config contains a `module.loaders` property which has been deprecated by webpack and is replaced by a `module.rules` property now. It can be that the `plugin install` command now installed webpack 4 where this is removed now.

The reason is an unlimited peer dependency version specifier in serverless-webpack that will be fixed with the next release.

**Comment by ffxsam** [comment]
Yep, no worries! I've just modified `package.json` to use webpack 3.3.0.
