### ISSUE TITLE
Create Project without AWS?

### ISSUE THREAD

**Issue by phillip-haydon** [serverless/serverless#480]
How can I create a project without any AWS creation.

I want to use:

https://github.com/Nopik/serverless-serve

To run/test Lambda's / Gateway API locally, and leave the current deployment process I have in place. serverless-serve depends on serverless. But serverless requires a project to create all the unnecessary stuff.

**Comment by phillip-haydon** [comment]
http://docs.serverless.com/docs/project-create

Also, most of these commands do not work on Windows. 

```
C:\Source\git\test\API\Server>serverless project create -n test -d localhost -r us-west-2 -p ~/.aws/credentials -e
test@test.com -c true -i true
C:\Users\phill_000\AppData\Roaming\npm\node_modules\serverless\lib\utils\index.js:667
  if (match.length >= 2) {
           ^

TypeError: Cannot read property 'length' of null
    at pathToContext (C:\Users\phill_000\AppData\Roaming\npm\node_modules\serverless\lib\utils\index.js:667:12)
    at Object.exports.getRegionConfig.exports.sDebug (C:\Users\phill_000\AppData\Roaming\npm\node_modules\serverless\lib
\utils\index.js:617:19)
    at Serverless.command (C:\Users\phill_000\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:132:12)
    at Object.<anonymous> (C:\Users\phill_000\AppData\Roaming\npm\node_modules\serverless\bin\serverless:13:36)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```
```
C:\Source\git\test\API\Server>serverless project create -c true -i true
{ [ServerlessError: Missing required properties] name: 'ServerlessError', messageId: undefined }
```

**Comment by arabold** [comment]
If you don't want to use Serverless, then you can try [lambda-local](https://github.com/ashiina/lambda-local) for local testing of your Lambda functions. It works well for my non-Serverless projects.

**Comment by phillip-haydon** [comment]
@arabold I'm actually trying to test the API Gateway which calls the lambda functions. Not run individual lambda's.

**Comment by erikerikson** [comment]
Will the -c flag work for your purposes?

sls project create -c

You can use -h or --help on most commands to get assistance

**Comment by phillip-haydon** [comment]
@erikerikson it may solve the problem but nothing I do prevents errors being thrown in Windows. As per my original question.

**Comment by erikerikson** [comment]
the addendum to your question, sure.
looks like a platform specific path delimiter problem.  try editing the directory delimiters to see if it fixes your problem.  Location in your stack trace.

**Comment by phillip-haydon** [comment]
@erikerikson thanks, I'll give it a go over the next couple of days and see if I can fix it.

**Comment by phillip-haydon** [comment]
OK I think I got it installed:

Updated the regex to `let pathRegex = /(\/|\\)((lib|tests|bin)(\/|\\).*?)\.js$/i;`

i.e `\/` is now `(\/|\\)` on both sides. Now to figure out how to run this stuff.

Thanks.
