### ISSUE TITLE
More than one table in dynamo.

### ISSUE THREAD

**Issue by fchevitarese** [serverless/serverless#4807]
Hey guys! 

I'm having some troubles to set more than 1 table in my serverless.yml 
If i set it with two, i got an error about the ports. 

I imagine that its trying to start 2 services, and both are set to use the same port. 
There´s a way to make it work? 

Here goes my yml config file. 
https://gist.github.com/fchevitarese/02faa38cca49e5b07e13f6e925763b94

Any help is appreciated! 

Thanks in advance!

**Comment by mataide** [comment]
@fchevitarese You should put your stacktrace, Serverless version, please use the Bug Report template.

**Comment by fchevitarese** [comment]
I'm sorry for that, i totally forgot that i made it work. 
It was not a bug, and i forgot to close the issue! 

Thanks and sorry for this.
