### ISSUE TITLE
Test failures against current Master branch

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4818]
Planning to do my first contribution, but getting test failures when running zip related tests. Anyone has an idea what is going on? See screenshot

![error](https://user-images.githubusercontent.com/1539747/37236328-449052a6-23bb-11e8-8288-0c918c93295a.png)

Running Ubuntu 16.04. I'd be happy to run tests in a docker container as well if that would fix this.

**Comment by horike37** [comment]
>Planning to do my first contribution

Awesome! Looking forward to seeing your contribution!

The tests have been flaky for a long time... but we have not found the root cause yet..
Does that error occur every time running the tests?

**Comment by simlu** [comment]
I can consistently reproduce and can do more digging later.

**Comment by simlu** [comment]
So I've set up a docker container to run the tests and that seems to work fine now. I'm assuming there is some hidden dependency missing since I'm using [Ubuntu 16.04 minimal cd install](https://help.ubuntu.com/community/Installation/MinimalCD). Unfortunately I couldn't find a docker image for that to make this reproducible.

**Comment by simlu** [comment]
For future reference, if you run into this problem do the following:
(1) create file `docker/Dockerfile` containing
```dockerfile
FROM ubuntu:16.04

WORKDIR /project

RUN apt-get update

RUN apt-get install git curl -y \
  && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash \
  && . ~/.nvm/nvm.sh \
  && nvm install 6.11.3 \
  && npm install -g npm grunt serverless npm-check-updates

ENTRYPOINT . ~/.nvm/nvm.sh && bash
```
then create file `manage.sh` with content
```shell
#!/bin/sh

sudo docker build -t test-environment ./docker &&
sudo docker run -v $(pwd):/project -it test-environment
```

and run `. manage.sh`.

After the build has completed (it will be slow first time), you can run `npm test` and the tests should pass.

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
