### ISSUE TITLE
Lambda assigned incorrect IAM role after creating new stage

### ISSUE THREAD

**Issue by mashbourne** [serverless/serverless#482]
This bug seems to be related to #477 as it manifests in a similar way.

Existing project with one stage, stageA
1) create a new stageB
2) dash deploy
3) check stageB aliased function IAM role -> it is assigned IamRoleLambda for stageA 
4) sls function deploy -> new stageB function version has proper IamRoleLambda for stageB

**Comment by ac360** [comment]
Thanks @mashbourne we'll look into this today :)

**Comment by ac360** [comment]
@mashbourne I can't seem to recreate this issue in `v0.1`.  Please let me know if you still run into it in `v0.1` and thanks for your help :)
