### ISSUE TITLE
Load plugins in serverless.js

### ISSUE THREAD

**Issue by nordyc** [serverless/serverless#4832]
# This is a (Bug Report)

## Description

do not load the section of plugins into serverless.js, someone has an example of how to use serverless.js correctly. Thank you

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
