### ISSUE TITLE
Is it possible to enable / disable the scheduler for a specific lambda functions, in the serverless.yml file ?

### ISSUE THREAD

**Issue by josenrihernand** [serverless/serverless#4834]
Hi everyone,

How could I to include a "condition" to turning on / off the schedule of a lambda function, in the serverless.yml file ?

For example, I need to enable the schedule for a specific(s) function(s), depending on the account. That is to say, I want to enable the scheduler only under specific conditions. 

Is that possible ?

...
...
functions:
  my_function_01:
    handler: src/my_folder/my_function.lambda_handler
    role: my_user_role
    events:
      - schedule:
          rate: rate(12 hours)
          **enabled: true | false ----> I need to enable / disable it under curtains conditions**
...
...

I could pass a command-line argument (example the account_id and the function_name) to the "serverless deploy" (sls deploy) command, so that in some "condition" in the serverless.xml, I could enable / disable the corresponding schedule, but I don't know how to specify the condition to take that action...

thanks in advance!

**Comment by jamesdixon** [comment]
@josenrihernand not sure if you found a solution, but I found this thread with a handful of options: https://forum.serverless.com/t/conditional-serverless-yml-based-on-stage/1763/9

**Comment by josenrihernand** [comment]
@jamesdixon. 
Actually, it is a very useful info. 
Thanks for your help!

**Comment by ohadperry** [comment]
```
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true / false
```
