### ISSUE TITLE
Feature Request: Allow Lambda deployment without S3 bucket creation

### ISSUE THREAD

**Issue by jdk339** [serverless/serverless#4840]
# This is a Feature Proposal

## Description

Allow deployment to Lambda without having to create an S3 bucket.

Example config:

```
custom:
  disableS3BucketCreation: true
```

Similar or dependent issues:
* None

## Additional Data

None

**Comment by jdk339** [comment]
True. This is unlikely to happen, so I'll just close for now.

**Comment by silky** [comment]
why is it unlikely to happen? it would be really convenient.

**Comment by simlu** [comment]
What's the benefit? Why would it be convenient?

**Comment by silky** [comment]
because, i have a pre-existing bucket into which i would like to upload files, and then trigger my function from those file uploads.

i do not want to have to reconfigure the bucket that i upload to every time i deploy the function!

**Comment by simlu** [comment]
So you are using an existing bucket. Sounds like this feature already exists? You can specify the deployment bucket in the configuration. Is that maybe what you want here?

**Comment by jdk339** [comment]
I think what I was trying to do may actually be possible already, according to the [Serverless Docs](https://serverless.com/framework/docs/providers/aws/guide/deploying#deploy-function). I am no longer using Serverless (I'm just using the AWS CLI to upload the .zip file now), so I haven't tested it out, but according to the docs it should do what I was trying to achieve.

Also, @silky, if you just want to upload to an S3 bucket, I would recommend using the AWS CLI.

**Comment by silky** [comment]
it's not the deployment bucket i'm interested in, it's a different bucket.

**Comment by simlu** [comment]
@silky I don't understand. What do you mean by "a different bucket"?

**Comment by silky** [comment]
@simlu i can't comprehend how this is hard for you to understand; i've opened a new issue.

**Comment by simlu** [comment]
@silky Haven't gone into detail, but what you are describing there should work. That's why I was confused.
