### ISSUE TITLE
'sls resources deploy' doesn't pick up resource changes in s-module

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [serverless/serverless#485]
I am running sls version 0.1.0. I am trying to create my DynamoDB table through CloudFormation and then deploy it via 
```
sls resources deploy
```
If I add table definition to s-module, changes are not detected on resources deploy, and I get a 400 error saying *'No updates are to be performed.'* However, if I add table definition to s-project, table gets created successfully.

**Comment by eahefnawy** [comment]
Thanks for reporting @Alua-Kinzhebayeva ... we're looking into it right now :)

**Comment by Alua-Kinzhebayeva** [comment]
thanks a lot!

**Comment by eahefnawy** [comment]
@Alua-Kinzhebayeva Thank you! and please let us know if you face anymore issues. We're not gonna sleep tonight! :D
