### ISSUE TITLE
serverless package --stage dev --package dotnetcore-sls-pkg-dev

### ISSUE THREAD

**Issue by firojasha** [serverless/serverless#4855]
HI, 

I was using serverless package --stage dev --package dotnetcore-sls-pkg-dev for packaging in serverless for dotnet core., when it is packaged, it is packaging under [ bin/Debug/netcoreapp2.0/publish/* ] path, but we needed the dll's in the Root folder in package other wise it gives error like .csproj should be root project., i  have been trying to sort it out, but serverless package is not supporting to copy dll's in to Root folder when it is packaged., can you please tell what could be done to achieve my requirement?

Error message  - "errorMessage": "Could not find the required 'dotnetcore_package.deps.json'.  This file should be present at the root of the deployment package.

Handler in serverless.yml  -     handler: dotnetcore.serverless::dotnetcore.serverless.Handler::ContentHandler

## Additional Data

Serverless Framework Version you're using***: - 1.26
Operating System***: - Windows

Regards,
Firoj Shaik

**Comment by firojasha** [comment]
HI, If there any solution for this issue? please let me know.

Regards,
Firoj shaik

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
