### ISSUE TITLE
V0.1.0: Changing an endpoint path breaks Serverless project

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#486]
After creating a new project with Serverless 0.1.0, when I change an endpoint's path in s-function.json and try to run sls, I see this error:

    ServerlessError: Endpoint was not found: articles/api/query@api/query~GET

(I changed the endpoint path from "api/query" to "articles".)

Without having too much knowledge of the codebase, this seems to be caused by the code in: https://github.com/serverless/serverless/blob/master/lib/ServerlessFunction.js#L47:

    _this.endpoints.push(new _this._S.classes.Endpoint(_this._S, {
      component:      _this._config.component,
      module:         _this._config.module,
      function:       _this._config.function,
      endpointPath:   _this._config.module + '/' + _this._config.function,
      endpointMethod: 'GET'
    });

It seems like the endpoint path is fixed to "module/function", not read from s-function.json.

**Comment by ac360** [comment]
@kennu Always appreciate your help :)  Someone mentioned this issue this morning and we put it on our Road Map.  I'm about to solve it in 1 hour.  Thanks for describing it in more detail, it helps :)

**Comment by kennu** [comment]
Well, thanks for a great project :-) I have a bunch of apps waiting to be migrated to 0.1.0, pretty much using Serverless for all AWS projects now. The features in the release notes look really nice.

**Comment by ac360** [comment]
@kennu Just pushed a fix for this in 5a5590732f690e0973e70925f57bafc147d3f601 You can update from the Master branch or wait until we publish `v0.1.0` later today.  Thanks for the supportive comments, they really help :)  In fact, could we quote you on, " pretty much using Serverless for all AWS projects now".  It would really help us.

**Comment by kennu** [comment]
Thx for the fix, master branch seems to be working for me now. Can't find a way to deploy the whole project at once though, like with "sls function deploy -a -s development" previously. :-(

The quote is OK, as a private person without affiliations.

**Comment by ac360** [comment]
Awesome thanks!

Also, I'm fixing the `--all` option at this very moment and almost done!  It was removed accidentally, but it will be back within the hour, sorry!

**Comment by ac360** [comment]
@kennu Ok, the all option is back and it's in the Master branch.

**Comment by kennu** [comment]
I can confirm -a is working in master, thanks again. :-)

**Comment by kennu** [comment]
Still having problems deploying using master though. For some reason, the generated lambda .zip file does not contain a .env file with my environment variables.

**Comment by kennu** [comment]
I guess it's because of this line:
https://github.com/serverless/serverless/blob/9aca1859a9850728ba071ffc298401f08c72607e/lib/actions/CodePackageLambdaNodeJs.js#L258

                // Skip .env
                if (pathInZip === '.env') return;

Not sure how that's supposed to work, I figure that .env is needed in the .zip?

**Comment by ac360** [comment]
Ah, ok thanks :)  On it right now!

**Comment by ac360** [comment]
@kennu I just removed that line of code and pushed changes to the Master.  Please let me know if this still isn't working for you.  I'll be watching this issue all day :)  Sorry about the inconvenience and thank you for your help!

**Comment by kennu** [comment]
It's working in master. :) Great to have all this stuff fixed on the fly. My first module seems to be working now, going to migrate the rest of them to 0.1 next.
