### ISSUE TITLE
Java invoke local NoSuchMethodException in abstract handlers

### ISSUE THREAD

**Issue by robertoestivill** [serverless/serverless#4867]
# This is a Bug Report

## Description

For bug reports:

* What went wrong?

The configured handler class does not implement the method `handleRequest`, but it's parent does.
The workaround is to re-implement it on the subclass, and just call the parent like so

```
  @Override public ApiResponse handleRequest(ApiRequest req, Context ctx) {
    return super.handleRequest(req, ctx);
  }
```

However this can be problematic if the parent abstract class declares it final, so the subclasses can't override it.

* What did you expect should have happened?

The Java invoke local is able to detect that the configured handler class has a parent class that implements the `handleRequest` method and is able to execute it correctly.

* What was the config you used?

https://github.com/robertoestivill/serverless-bugreport/blob/master/serverless.yml

* What stacktrace or error message from your provider did you see?

See below.

* Sample Project to reproduce issue

```
$ git clone https://github.com/robertoestivill/serverless-bugreport/

$ mvn install 

$ serverless invoke local --function handler-broken
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
java.lang.NoSuchMethodException: Could not find handler for handleRequest in com.example.serverless.bugreport.HandlerBroken

	at com.serverless.InvokeBridge.findHandlerMethod(InvokeBridge.java:105)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:63)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:36)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:133)

$ serverless invoke local --function handler-fixed
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
Request Start
Request End
status: 200
```

~For feature proposals:~
* ~What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.~
* ~If there is additional config how would it look~

~Similar or dependent issues:~
* #

## Additional Data

* ***Serverless Framework Version you're using***:

```
$ serverless -version
1.26.1
```
* ***Operating System***:

```
macOS High Sierra
Version 10.13.3 (17D47)
```
* ***Stack Trace***:

`See above.`

* ***Provider Error messages***:

`N/A`

**Comment by spinwards** [comment]
I fixed this locally by updating findHandlerMethod() in InvokeBridge.java to:

```
  private Method findHandlerMethod(Class clazz, String handlerName) throws Exception {
    Method candidateMethod = null;
    for(Method method: clazz.getMethods()) {
      if (method.getName().equals(handlerName) && !method.isBridge()) {
        // Select the method with the largest number of parameters
        // If two or more methods have the same number of parameters, AWS Lambda selects the method that has
        // the Context as the last parameter.
        // If none or all of these methods have the Context parameter, then the behavior is undefined.
        int paramCount = method.getParameterCount();
        boolean lastParamIsContext = paramCount >= 1 && method.getParameterTypes()[paramCount-1].getName().equals("com.amazonaws.services.lambda.runtime.Context");
        if (candidateMethod == null || paramCount > candidateMethod.getParameterCount() || (paramCount == candidateMethod.getParameterCount() && lastParamIsContext)) {
          candidateMethod = method;
        }
      }
    }

    if (candidateMethod == null) {
      throw new NoSuchMethodException("Could not find handler for " + handlerName + " in " + clazz.getName());
    }

    return candidateMethod;
  }
```

**Comment by lasanthak** [comment]
Submitted a fix https://github.com/serverless/serverless/pull/6791
