### ISSUE TITLE
[question] How to handle the services which doesn't support in Cloudformation currently?

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4868]
# This is a (question)

## Description

AWS added new features quickly, when I try to use these new announced features, I can't find out the related cloudformation key to use. 

(Serverless framework can use Cloudformation templates directly if some extra resources required).

For example, currently I want to control the setting for below features

### Point-in-time recovery in DynamoDB

https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-continuous-backups-and-point-in-time-recovery-pitr/

With this feature, we can enable/disable point-in-time recovery to restore the table at any times in last 35 days.

But I can't find anyway to control it (enable/disable) via Cloudformation/SLS.

How do you deal with this situation in serverless project?

**Comment by HyperBrain** [comment]
Hi @ozbillwang . We'll have to wait until CloudFormation support is available. We should create a feature request and tag it with the "wait-for-cf-support" label.

**Comment by ozbillwang** [comment]
Thanks @HyperBrain 

Seems I have to wait. 

By the way, there is another feature I can't manage with automation codes. 

https://forum.serverless.com/t/how-to-setup-custom-access-logging-for-api-gateway-using-serverless/3288

In this case, it is little bit different. 

The cloudformation doesn't support the key word `accessLogSettings`, but it is appeared in API document: https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/#accessLogSettings

So are there any way in serverless framework we can set it via API directly? 

Why I ask for is, in Terraform, we can define `null_resource` and `local-exec` to work around these situation.

**Comment by ymenesesAL** [comment]
Some way to enable access login using CloudFormation was found? because accessLogSettings key doesn't work
` property accessLogSettings not defined for resource of type AWS::Serverless::Api`
