### ISSUE TITLE
Update aws-nodejs template with Node.js 8

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4871]
# This is a Feature Proposal

## Description
AWS Lambda has supported for Node.js 8 runtime, so we should update aws-nodejs template with that which is created by `sls create -t aws-nodejs`.
https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

Native nodejs starter code is in the following article. Would be good to update the template with the one.
https://serverless.com/blog/aws-lambda-node-8-support-what-changes-serverless-developers/

**Comment by emaildano** [comment]
HMB 🍺 

I got this.

**Comment by horike37** [comment]
Awesome @emaildano :smile: 
Let @serverless/framework-maintainers know if you need any our help!

**Comment by vdanniel** [comment]
thanks. Eagerly.

**Comment by pmuens** [comment]
Closing since this was already done via https://github.com/serverless/serverless/pull/5088.
