### ISSUE TITLE
C# example for Azure

### ISSUE THREAD

**Issue by PsidomPC** [serverless/serverless#4875]
# This is a (Bug Report / Feature Proposal)
Feature Proposal

## Description
Add example for Azure C# 

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
#### Azure Functions supports C# languages but find it hard to use it with serverless frame without a template or example

* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Mac OS
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by evandrom** [comment]
Does anyone have this example?

**Comment by pmuens** [comment]
Closing since this is related to the `serverless/examples` repository. Please take a look over there and open up an issue in this repository if no example exists.
