### ISSUE TITLE
bash: serverless: command not found

### ISSUE THREAD

**Issue by the94air** [serverless/serverless#4889]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
After installing the package globally and running `serverless login` I got an error.
* What did you expect should have happened?
Ask me for the credentials.
* What was the config you used?
N/A
* What stack trace or error message from your provider did you see?
`bash: serverless: command not found`

## Additional Data

* ***Serverless Framework Version you're using***:
v1.26.1
* ***Operating System***:
Mac OS - high sierra
* ***Stack Trace***:
* ***Provider Error messages***:
`bash: serverless: command not found`

**Comment by HyperBrain** [comment]
@the94air Is your global Node module's binary folder in your PATH? Otherwise you could try to execute serverless with `npx serverless ...` which might resolve the folder correctly.

**Comment by the94air** [comment]
Thanks, @HyperBrain. You're right. the commands are working now with npx.

**Comment by yiyufenfei** [comment]
> npx serverless
Can I see the reason for my error，Response code 400 (Bad Request)
