### ISSUE TITLE
Reference Variables in Javascript Files

### ISSUE THREAD

**Issue by phstc** [serverless/serverless#4891]
I'm using serverless 1.26.1, and I'm trying to follow this example [Reference Variables in Javascript Files](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-javascript-files):

```javascript
module.exports = (serverless) => {
  serverless.cli.consoleLog('You can access Serverless config and methods as well!');

  return {
    property1: 'some value',
    property2: 'some other value'
  }
}
```

But `serverless` is always undefined. Has it changed since it was documented?

**Comment by dboune** [comment]
@phstc: That functionality will be available in release 1.27 which appears to be waiting for a few more items. Following the docs yesterday I ran into the same issue and found the necessary code change to be only in master. Looks like the docs are updated ahead of releases.

https://github.com/serverless/serverless/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.27

**Comment by phstc** [comment]
@dboune thanks 🍻 that `serverless` param will be very handy for me, I hope 1.27 goes out soon. 

It is a bit annoying that the docs don't not align with the latest.

**Comment by pwagener** [comment]
@phstc If, like me, you lack patience and want to play around with the feature, remember you can install off of the `master` branch and use it.   I'm using that right now with good success.  In `package.json` ...

```
  ...
  "devDependencies": {
    "serverless": "git+https://git@github.com/serverless/serverless.git#master",
  ...
```

I'm currently convincing myself to _not_ deploy anything using that to production, but YMMV.

**Comment by ryanwmarsh** [comment]
Ran into this today. How can I help us not deploy docs before code? Happy to devote some time to helping sort this out.

**Comment by pwagener** [comment]
I'm using `1.27.2` and am able to use the functionality.  What issues are you seeing @claudenm ?

**Comment by claudenm** [comment]
I 😊had updated serverless but not globally.  It's working as expected sorry for the disturbance!

**Comment by pwagener** [comment]
Awesome -- Looks like we're all agreed this issue can be closed @HyperBrain.

**Comment by HyperBrain** [comment]
@pwagener That sounds great 🎉 . I'll close this now. Thanks for your patience, it took some while.
