### ISSUE TITLE
Feature request: More informative error when no serverless.yml file found

### ISSUE THREAD

**Issue by wheresrhys** [serverless/serverless#4894]
## Description
When a serverless.yml file isn't present (e.g. I just had a typo in my file's name) the errors give no hint that the problem is a missing config file. e.g. 

```
 Serverless Error ---------------------------------------

  Serverless command "offline" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.26.1
```
I'd be happy to submit a PR to print a warning/error if someone can point me in the roughly the right direction

**Comment by GuruRAM** [comment]
@wheresrhys Hi, you can start looking here:
`serverless\lib\classes\Utils.js` for `findServicePath` and `PluginManager.js` for `getCommand`.

If serverless.yaml (yml, json, js) file is not found, `this.serverless.config.servicePath` field will be set to null.
If the command is not found in `getCommand` exception message can be extended with information regarding whether or not serverless.yaml file is loaded.

**Comment by pgrzesik** [comment]
This has been resolved and error message now says:

```
This command can only be run in a Serverless service directory. Make sure to reference a valid config file in the current working directory if you're using a custom config file
```
