### ISSUE TITLE
gcloud function with multiple functions issue

### ISSUE THREAD

**Issue by Madthumb** [serverless/serverless#4896]
# This is a (Bug Report / Feature Proposal)

## Description
I am trying to organize folder/file structure for multiple functions with V1.26.1, but it seems like the sub-folder is not supported. I've try the solution from other post, but no luck. Does anyone know what I am doing wrong here?

Big thanks if you could give me some tips here.

Similar or dependent issues:
* #2372

## Additional Data
![1523318496318](https://user-images.githubusercontent.com/13104722/38537178-26b88b28-3c5b-11e8-97d2-a39e3be06e79.jpg)

**Comment by jpirkey** [comment]
All the examples I have seen use `module.exports.hello` instead of just `exports.hello`.  Not sure if that matters or not .. still learning this stuff myself.

**Comment by pmuens** [comment]
Hey @Madthumb thanks for opening 👍

With Google Cloud Functions you're supposed to have an `index.js` file in the root of your zip file which exports all the modules (so you can e.g. re-export everything there) or you can use the `main` property in `package.json` to point to such a file.
