### ISSUE TITLE
Using MySQL (with RDS), Redis(Elasticache), and Elasticsearch

### ISSUE THREAD

**Issue by justinmealey** [serverless/serverless#49]
I've adapted this to use MySQL as the backend along with elasticsearch and redis.  Is it interesting to this project at all to submit a pull request with how I'm doing it?

**Comment by austinrivas** [comment]
I would be VERY interested in seeing how you integrated RDS.

**Comment by ac360** [comment]
What!?!?  Please submit a PR!

**Comment by onyxraven** [comment]
+1 - should provide a path to RDS hosted Postgres as well, which I'm sure will be in high demand.

Memcached would be nice as well.

**Comment by ac360** [comment]
@justinmealey In our specifications for JAWS v1.0.0, we are moving toward making the framework more modular, so that people can plug-in different stacks, like the one you are discussing.  

If this works out, you will be able to make your set-up a module, and people can plug it into their JAWS project.

More than ever, I'd love to see what you've come up with.

**Comment by justinmealey** [comment]
It's nothing fancy, since it's not integrating directly with the RDS/elasticache services, but rather using the connections strings just as you would any other mysql database.  It does, however, provide for separating read/write queries so you can designate a master and read slaves for operations.  One thing that might turn folks off is that I use the SQL directly (with the mysql module), instead of using an ORM.  That could probably be another thing to take a look at for improvement.

I actually had my Amazon account manager and a site engineer come out to visit my startup a few weeks back, and I went over my current setup and how I was moving to an API Gateway (when it was in preview), Lambda, Elasticache, RDS, and another experimental service.  I love that your project makes this transition much easier, as I'm doing the rewrites right now, so I'll contribute back anything I make for my use case.

I'll get the PR submitted either today or tomorrow.

**Comment by vsochinsky** [comment]
Just wanted to point that you currently can't use Elasticache without connecting it to EC2 instances. That would be really great feature for serverless architectures though, I hope they're working on this.

**Comment by nirmalgoswami** [comment]
planning to use RDS(mysql) with serverless,how can use RDS(mysql) with serverless

**Comment by contractorwolf** [comment]
@justinmealey or @ac360 is there any code samples on anyone who has tried integrating this with memcached or elasticache I would love to see it. I am thinking that just looking at the documentation on connecting via node.js docs:
https://github.com/3rd-Eden/memcached
and I would assume that the urls for whatever AWS elasticache could be used with permissions correctly set from the Lambda instance to the Elasticache instance.  I am not sure what configuration will need to be set in the config however, so if anyone has some advice I would love to hear it.
Thanks!

**Comment by flomotlik** [comment]
@contractorwolf looks like this should help: http://docs.aws.amazon.com/lambda/latest/dg/vpc-ec.html
