### ISSUE TITLE
Connection timed out after 120000ms in function deployment

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#490]
I can't deploy my function when the resulting ZIP package is ~4.4MB: I have a *Connection timed out after 120000ms* error. Please note that the time it hangs before this error is longer that 2 minutes! The package is so big because it have `googleapis` dependency, which is around 20MB uncompressed.

My connection is quite slow in upload, so at first I thought it was a problem with the underlying `aws-sdk`'s code that upload the ZIP to S3, but then I tried [uploading the same package using the SDK directly](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html#Amazon_S3__Uploading_an_arbitrarily_sized_stream__upload_), and I got no errors.

**Update:** After many many retries, making sure network is 100% at rest, I finally managed to deploy my function. So, I'm pretty sure is a network-related issue. Anyaway having a timeout for uploads it's not a great idea, and really a problem for some. If this came out to be not in power of Serverless, tell me and I'll be happy to report it to AWS JS SWK.

Here is a **complete reproducible test**, got the same error with `0.1.0` and `0.1.1` on two different machines and two different networks (both ~0.6Mbit/s in upload):

```sh
cd /tmp
slss project create
cd serverless*
slss component create -c default -m default -f default
cd default
npm install --save googleapis q lodash
slss function deploy default/default/default --debug
```

Here is the **`slss function deploy --debug` output**:

	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/ProjectCreate.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ProjectCreate plugin loaded +10ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/ComponentCreate.js +3ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ComponentCreate plugin loaded +4ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/ModuleCreate.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ModuleCreate plugin loaded +3ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/FunctionRun.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionRun plugin loaded +6ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/FunctionCreate.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionCreate plugin loaded +4ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/FunctionRunLambdaNodeJs.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionRunLambdaNodeJs plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionDeploy plugin loaded +3ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/CodePackageLambdaNodeJs.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.CodePackageLambdaNodejs plugin loaded +5ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.CodeDeployLambdaNodejs plugin loaded +30ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/CodeEventDeployLambda.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.CodeEventDeployLambda plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EndpointDeploy.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointDeploy plugin loaded +6ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointBuildApiGateway plugin loaded +7ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/DashDeploy.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.DashDeploy plugin loaded +6ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointDeployApiGateway plugin loaded +5ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/StageCreate.js +2ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.StageCreate plugin loaded +6ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/RegionCreate.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.RegionCreate plugin loaded +5ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EnvList.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EnvList plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EnvGet.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EnvGet plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EnvSet.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EnvSet plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/EnvUnset.js +0ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EnvUnset plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /usr/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ResourcesDeploy plugin loaded +1ms
	  serverless:lib.node_modules.serverless.lib.Serverless CLI raw input:  +1ms { _: [ 'function', 'deploy', 'default/default/default' ],
	  debug: true }
	  serverless:lib.node_modules.serverless.lib.Serverless CLI processed input:  +4ms { context: 'function',
	  action: 'deploy',
	  options: { stage: null, region: null, aliasFunction: null, all: null },
	  params: { paths: [ 'default/default/default' ] },
	  raw: 
	   { _: [ 'function', 'deploy', 'default/default/default' ],
		 debug: true } }

	Serverless: Deploying functions in "development" to the following regions: eu-west-1  
	Serverless: Loading...   serverless:lib.node_modules.serverless.lib.actions.CodePackageLambdaNodeJs "development - eu-west-1 - default": Copying in dist dir /tmp/default@1453194634186 +62ms
	  serverless:lib.node_modules.serverless.lib.utils.aws.S3 Getting ENV Vars: serverless.eu-west-1.xxx.lorenzostanco.com - serverless/xxx/development/eu-west-1/envVars/.env +470ms
	  serverless:lib.node_modules.serverless.lib.actions.CodeDeployLambdaNodeJs "development - eu-west-1 - default": Compressed file created - /tmp/default@1453194634186/package.zip +2s
	  serverless:lib.node_modules.serverless.lib.actions.CodeDeployLambdaNodeJs "development - eu-west-1 - default": Uploading to project bucket... +4ms
	  serverless:lib.node_modules.serverless.lib.utils.aws.S3 Uploading Lambda Zip File: serverless/xxx/development/lambdas/default@1453194636856.zip +28ms
	  serverless:lib.node_modules.serverless.lib.actions.CodeDeployLambdaNodeJs "development - eu-west-1 - default": Updating Lambda configuration... +537ms
	  serverless:lib.node_modules.serverless.lib.actions.CodeDeployLambdaNodeJs "development - eu-west-1 - default": Updating Lambda function... +2s
	Done!
	Serverless: ------------------------  
	Serverless: Failed to deploy the following functions in "development" to the following regions:  
	Serverless: eu-west-1 ------------------------  
	Serverless:   default/default/default: Connection timed out after 120000ms  
	  serverless:lib.node_modules.serverless.lib.actions.FunctionDeploy TimeoutError: Connection timed out after 120000ms
		at ClientRequest.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/http/node.js:56:34)
		at ClientRequest.g (events.js:260:16)
		at emitNone (events.js:67:13)
		at ClientRequest.emit (events.js:166:7)
		at TLSSocket.emitTimeout (_http_client.js:536:10)
		at TLSSocket.g (events.js:260:16)
		at emitNone (events.js:67:13)
		at TLSSocket.emit (events.js:166:7)
		at TLSSocket.Socket._onTimeout (net.js:318:8)
		at _runOnTimeout (timers.js:524:11)
		at _makeTimerTimeout (timers.js:515:3)
		at Timer.unrefTimeout (timers.js:584:5)
	From previous event:
		at /usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:260:37
	From previous event:
		at /usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:250:16
	From previous event:
		at Deployer._provision (/usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:206:10)
		at Deployer.<anonymous> (/usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:73:42)
	From previous event:
		at Deployer.deploy (/usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:72:10)
		at CodeDeployLambdaNodejs.codeDeployLambdaNodejs (/usr/lib/node_modules/serverless/lib/actions/CodeDeployLambdaNodeJs.js:48:23)
	From previous event:
		at /usr/lib/node_modules/serverless/lib/Serverless.js:177:25
		at Array.reduce (native)
		at Serverless._execute (/usr/lib/node_modules/serverless/lib/Serverless.js:176:26)
		at Object.actions.(anonymous function) [as codeDeployLambdaNodejs] (/usr/lib/node_modules/serverless/lib/Serverless.js:378:20)
		at FunctionDeploy.<anonymous> (/usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:299:44)
		at processImmediate [as _immediateCallback] (timers.js:383:17)
	From previous event:
		at /usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:286:20
	From previous event:
		at /usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:267:31
		at replenish (/usr/lib/node_modules/serverless/node_modules/async/lib/async.js:191:21)
		at /usr/lib/node_modules/serverless/node_modules/async/lib/async.js:208:15
		at Object.async.eachLimit (/usr/lib/node_modules/serverless/node_modules/async/lib/async.js:168:12)
		at /usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:263:15
	From previous event:
		at FunctionDeploy._deployCodeByRegion (/usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:256:14)
		at FunctionDeploy.<anonymous> (/usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:239:24)
	From previous event:
		at FunctionDeploy._processDeployment (/usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:236:10)
	From previous event:
		at FunctionDeploy.functionDeploy (/usr/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:108:10)
	From previous event:
		at /usr/lib/node_modules/serverless/lib/Serverless.js:152:29
		at Array.reduce (native)
		at /usr/lib/node_modules/serverless/lib/Serverless.js:151:30
		at processImmediate [as _immediateCallback] (timers.js:383:17)
	From previous event:
		at Serverless._execute (/usr/lib/node_modules/serverless/lib/Serverless.js:149:10)
		at Serverless.actions.(anonymous function) (/usr/lib/node_modules/serverless/lib/Serverless.js:378:20)
		at Serverless.command (/usr/lib/node_modules/serverless/lib/Serverless.js:347:38)
		at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:16:12)
		at Module._compile (module.js:435:26)
		at Object.Module._extensions..js (module.js:442:10)
		at Module.load (module.js:356:32)
		at Function.Module._load (module.js:313:12)
		at Function.Module.runMain (module.js:467:10)
		at startup (node.js:136:18)
		at node.js:963:3 +8m

**Comment by ac360** [comment]
@lorenzos Yeah, that's not good.  We have't set the timeout anywhere, so it must be in the AWS SDK.  I recommend using the [serverless-optimizer-plugin](https://www.github.com/serverless/serverless-optimizer-plugin) if you aren't already.  In the interim, we have to figure out how to improve this because 4.4mb is not big at all.

**Comment by lorenzos** [comment]
I'll try to make more tests to confirm this is network-dependent (i.e. artificially limiting upload speed even more) and AWS-related (i.e. by calling `updateFunctionCode()` directly from the AWS SDK). I'll let you know if I'll end up reporting this to AWS.

**Comment by arabold** [comment]
I'm uploading a 20 MBytes zipped Lambda (`geoip-lite`) via a 80 MBit network connection. That's working fine and as expected. It takes about 2 minutes or so.

**Comment by lorenzos** [comment]
@arabold The issue here is the existence of the timeout. I'm pretty sure that with a 80Mbit connection I can manage to upload all I need without problems. Suppose I have to upload your 20MB function with a crappy connection, because I'm not at office, and I'm willing to wait hours. As if I'm uploading a big file on S3 or a long HD video on YouTube. I don't get why I should be limited by an arbitrary timeout. 

But, again, the more I think about it, the more I'm sure it's an AWS issue, and not related to Serverless.

**Comment by arabold** [comment]
Yes, it seems to be a timeout caused by a slow/bad network connection - not related to the size of the Lambda. As @ac360 stated, there's no timeout code in Serverless, so this looks like a problem with the AWS SDK.

**Comment by connaryscott** [comment]
Yes I am now blocked, and apparently done as I cannot upload anymore using the serverless interface.   I guess 18MB is too big for our network.  I do not believe an optimizer is available for python?

**Comment by pwagener** [comment]
@connaryscott I'm seeing the same thing attempting to upload a ~ 9 MB file over a slow network (thanks Time Warner).  The consistent upload speed I see is ~ 300 KB/s, which should be able to complete between 3 and 5 minutes [this conversion table](http://www.meridianoutpost.com/resources/etools/calculators/calculator-file-download-time.php) is useful in guessing how long it should take).  So the default two-minute timeout in the AWS client kills me every time.  When I switch from my cable connection to my cell phone connection (which is amusingly faster at uploads), it completely easily.

I suspect we could provide a different time out by setting `AWS.Config.httpOptions.timeout` as described [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html).  Skimming the `serverless` source, `libs/ProviderAws.js` looks like the right place.  We're already looking for `HTTP_PROXY`/`HTTPS_PROXY` environment variables to globally configure a proxy.  I haven't built & modified the `serverless` code locally since way back in the `JAWS` days, but will give it a try & see if I can put together a Pull Request with this minor tweak.

**Comment by pwagener** [comment]
Just filed Pull Request #937 to allow a user to set `AWS_CLIENT_TIMEOUT` as an environment variable to configure how long to wait for a timeout.  This works for my particular situation, and I expect will be a good enough work-around for most people.  @connaryscott Feel free to pull down & install my fork to see if it works for you if this is not pulled in quickly.

**Comment by connaryscott** [comment]
@pwagener thanks for the timeout support.   I did mitigate my immediate situation for the near term as a recent proxy configuration (http_proxy/https_proxy) has given me a better network performance (which serverless 0.5 supports now).   I do suspect I will need this at some point in the future and will review accordingly.

**Comment by Josh-a-e** [comment]
also for reference AWS has some of their own limits here: 
AWS Lambda Deployment Limits

- Lambda function deployment package size (.zip/.jar file)	**50 MB**
- Size of code/dependencies that you can zip into a deployment package (uncompressed zip/jar size)	**250 MB**

http://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by RichardSilveira** [comment]
I'm trying to set AWS_CLIENT_TIMEOUT=200000000 too, but on windows, and the timeout expiration time appears not be updating...

How to do it exactly, please?

i'm doing
SET AWS_CLIENT_TIMEOUT=200000000
and then
sls deploy

My serverless cli version is 1.22.0

My package has 8.5mb (was made in koltin language)

**Comment by pmuens** [comment]
Thanks for commenting @RichardSilveira 👍

See the comment in https://github.com/serverless/serverless/issues/2988#issuecomment-333056458.
