### ISSUE TITLE
Define more finely the Regular Expression of Serverless Variables

### ISSUE THREAD

**Issue by SkxNMDI5** [serverless/serverless#4903]
# This is a Feature Proposal

## Description

* I would like to be able to reuse easily Cloudformation templates with their own syntax (${AWS::Region}, ${MyVar}) without conflicts with the serverless variables syntax
* Natively : without requiring plugins or changing the variables syntax in each of my templates

## Additional Data

Here is the regex compatible with the Serveless Variables syntax :
```
"\\${((?=self:|env:|opt:|ssm:|s3:|cf:|file\\()[ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}"
```
I've used it in a lot of templates and descriptors.

* ***Serverless Framework Version you're using***: 1.26.1

**Comment by HyperBrain** [comment]
@SkxNMDI5 Thanks for the proposal. Can you check if that still works with the current master where the variable resolution has been reworked to support cyclic dependencies (including with `${self:service}`) and better references when using these.
If we decide to change the global regex we have to make sure that everything continues to work as expected, also for more complicated setups.
/cc @erikerikson

**Comment by medikoo** [comment]
Closing as it was already solved. In old resolver we've fined tuned the regex to not collide  with AWS pseudo params, and same way new variable resolver respects them
