### ISSUE TITLE
Installing serverless errors node 8.1.1 npm 5.8 

### ISSUE THREAD

**Issue by jeygith** [serverless/serverless#4904]
#npm install serverless -g errors
[2018-04-12T07_43_03_330Z-debug.log](https://github.com/serverless/serverless/files/1902560/2018-04-12T07_43_03_330Z-debug.log)

## Description

For bug reports:
Installing serverless via npm install serverless -g in node 8 and npm 5.8 installs then rollbacks everything and an ENOENT error thrown as per the attached npm log file

Serverless 1.26
Linux Mint 18

error enoent ENOENT: no such file or directory, chmod
error enoent This is related to npm not being able to find a file.

**Comment by pmuens** [comment]
Thanks for opening @jeygith 👍

This sounds like an issue with `npm`, so I'll close this issue for now.
