### ISSUE TITLE
'npm install serverless' is failing for npm install serverless@latest -g

### ISSUE THREAD

**Issue by chrisyorkston** [serverless/serverless#4907]
Hi, I am unable to install serverless via `npm install serverless@latest -g`

I get the following error:

    npm ERR! path /usr/local/lib/node_modules/.staging/aws-sdk-aced1a2e/node_modules/base64-js
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall rename
    npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sdk-aced1a2e/node_modules/base64-js'-> '/usr/local/lib/node_modules/.staging/base64-js-14d7cbfe'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

I can install the following successfully `npm install -g serverless@1.15.0` but can't go any higher than `1.15.0` without getting the above error. Any ideas?

**Comment by ethanherbertson** [comment]
Sounds similar to an npm bug I've seen before, though not specifically with Serverless. I recommend reading through the thread here to see if it helps: https://github.com/npm/npm/issues/13528

**Comment by pmuens** [comment]
Thanks for opening @chrisyorkston 👍

Yes, that looks like an npm related bug. I'll close this issue for now since @ethanherbertson corss-linked to the corresponding npm issue.
