### ISSUE TITLE
Feature Request: Allow Executable Params files

### ISSUE THREAD

**Issue by fantapop** [serverless/serverless#4909]
# This is a Feature Proposal

## Description

Now that serverless config file can be javascript, it would be really great if invoke parameter files could be js as well.  Besides nicer syntax this would allow templating, code sharing and dynamic test cases.  In our lambda's we're often passing data about the logged in user via the authorizer context.  If we could execute our param files, we could actually look up a user in our local database to provide as the user in the event.

Another interesting use case is testing our authorizer function directly.  When I want to test it with valid credentials, I need to generate credentials with a script and then copy the up to date ones into the config file and run my tests.  Code here would allow me to generate validate credentials on each execution.

**Comment by fantapop** [comment]
Another great use case for this is being able to JSON.stringify() a request body.

**Comment by dschep** [comment]
Just making sure I understand your proposal, you want `sls invoke -f FuncName -p someScriptInsteadOfJson.js` support?

If so, you can achieve this with the `sls invoke`'s ability to read an event from STDIN. For example:

`generateEvent.js` - script to generate the input:
```javascript
console.log(JSON.stringify({foo: 'bar'}))
```
Then invoke like this:
```shell
$ sls invoke local -f hello -d "$(node generateEvent)"
{
    "statusCode": 200,
    "body": "{\"message\": \"Go Serverless v1.0! Your function executed successfully!\", \"input\": {\"foo\": \"bar\"}}"
}
```

**Comment by fantapop** [comment]
Oh good call. I’ll try this out!

**Comment by pmuens** [comment]
Thanks for opening @fantapop 👍

I'll close this one since it looks like you were able to resolve it. Feel free to re-open if this issue was not fixed.
