### ISSUE TITLE
Command to recreate the `_meta` folder

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#491]
Sharing a whole project via Git is not handy at the moment, because of the gitignored `_meta` folder. I understand the reason `_meta` is ignored, but IMHO we need a tool to recreate it at any time, since (if I'm not wrong) the content of the folder is build upon project settings.

I suggest something like `project init`:

```sh
git clone https://github.com/me/my-slss-project
cd my-slss-project
ls -l _meta # Not found
serverless project init
ls -l _meta #Found!
```

*(I've already reported this issue in chat, I'm rewriting here for tracking purposes, I hope it's ok)*

**Comment by ac360** [comment]
Thanks @lorenzos.  Awesome feedback today.  We have the `Project Install` command in `v0.1.2`.  Do you think this could be used instead?

**Comment by lorenzos** [comment]
I'll look into `install` ASAP, eventually closing this issue.

**Comment by cnatis** [comment]
@ac360 `project install` won't work as it also throws the same `ServerlessError: Meta could not be loaded because no _meta/variables folder exists`

**Comment by kennu** [comment]
@ac360, I'm also facing this situation now. When I try to run "sls project install" in the project directory I've cloned from git, I get:

    ServerlessError: Meta could not be loaded because no _meta/variables folder exists

Should it work just like that or is some preparation needed for the project?

**Comment by ac360** [comment]
@lorenzos @kennu I have a `ProjectInit` command in the works right now.  Should come out in tonight's release.

**Comment by kennu** [comment]
That's great, I'll try it out if still awake here in Helsinki. :-)

**Comment by kennu** [comment]
@ac360 I guess it didn't make it in the release yet?

**Comment by ac360** [comment]
@kennu Sorry :(  Got swamped with a few other things (Python Support and Project Install) fixes.  This is almost finished.  I'm pretty sure we can get this in, in 24 hours.  Sorry for the delay!

**Comment by ac360** [comment]
Ok, this is in f430e0acd2e27c03992cd1d3ece62f23a80c327f  Thanks everyone @kennu and @lorenzos

**Comment by kennu** [comment]
I was able to try project init/remove now and it works very nicely for me, so thanks again @ac360 :)

**Comment by ac360** [comment]
Of course @kennu!  Always glad to have your input :)  Many more features coming...
