### ISSUE TITLE
Name of component/module/function limited to 20 characters

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#492]
There's an [hard-coded 20 characters limit](https://github.com/serverless/serverless/blob/7085b33d13c0c3563481e97f67dc04a244ca74dc/lib/utils/index.js#L571) for the name of components, modules and functions. Is it an AWS limitation? If not, can it be removed or increased? If yes, user should know it someway, because now a 20+ characters name [leads to a misleading error message](https://github.com/serverless/serverless/blob/3ca85189cead053341c88b49e2dde4d7e58391d4/lib/actions/ComponentCreate.js#L123).

*(I've already reported this issue in chat, I'm rewriting here for tracking purposes, I hope it's ok)*

**Comment by ac360** [comment]
Lambda names are generated by combining project, component, module and function.  This is the reason for the 20 char limit.  The lambda name limit looks to be 64 chars.  So I think we may have to shorten this actually.  Any ideas @lorenzos?

**Comment by dege88** [comment]
What about a warning for names longer than 15 characters and a nice error on deploy of lambdas with longer than 64 characters names?

**Comment by ac360** [comment]
I think the solution here is to keep the limit, but allow for custom names instead, especially custom names defined via Project Variables.
