### ISSUE TITLE
Update aws-sdk to the latest version

### ISSUE THREAD

**Issue by haruharuharuby** [serverless/serverless#4930]
# This is a Feature Proposal
Integration with serverless-domain-manager.
Serverless will be able to deploy API gateway as REGIONAL optimized API.

## Description
latest serverless-domain-manager can not work.
This is the cause of AWS-SDK version(2.75.0) that serverless framework use.

This AWS-SDK version was released before adding REGIONAL optimized API feature in API Gateway.
So that, In AWS-SDK, apigateway.createDomainName API doesn't have the endpointConfiguration parameter.

https://serverless.com/blog/api-gateway-multiple-services/

Now I stacked 
For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

all above is putted on  [here on severless-domain-manager](https://github.com/amplify-education/serverless-domain-manager/issues/104)

For feature proposals:
*  Purpose of this issue is to be able to deploy this article with using the latest serverless-domain-manager plugin
https://serverless.com/blog/api-gateway-multiple-services/

* If there is additional config how would it look

Similar or dependent issues:
* [here on severless-domain-manager](https://github.com/amplify-education/serverless-domain-manager/issues/104)

## Additional Data

* ***1.23.0***:
* ***mac os high siera***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Hey @haruharuharuby :smile: 
Will this problem be resolved by updating aws-sdk to the latest version?
If so, could you send a PR with the update?

**Comment by horike37** [comment]
@HyperBrain 
Yes, agree. aws-sdk still keep 2.x version and it seems that they also follow semver.
