### ISSUE TITLE
Serverless deploy throw exception

### ISSUE THREAD

**Issue by AhmedRagheb** [serverless/serverless#4936]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
I'm using TeamCity and want to deploy my nodeJs lambdha function on AWS.
So, I create two build configuration. One for build and one for deploy.
build step: I use serverless package --package package and join node_modules serverless and .bin\serverless 
deplpoy step **& ".bin\serverless" deploy --stage master**
* What did you expect should have happened?
deploy to master function
* What was the config you used?
* What stacktrace or error message from your provider did you see?
 module.js:471 throw err;

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: Windows
* ***Stack Trace***:
* ***Provider Error messages***:
 module.js:471
throw err;
^
Error: Cannot find module 'bluebird'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at require (internal/module.js:20:19)
at Object.<anonymous> .. \serverless\lib\Serverless.js:4:19)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by montao** [comment]
I experience a similar problem today. "Cannot find module bluebird"

**Comment by pmuens** [comment]
Closing since we've published a couple of new releases with bugfixes. Also please ensure that Serverless was installed correctly via `npm install --global serverless`.
