### ISSUE TITLE
Which step update environment variables when I change provider.runtime in serverless.yml

### ISSUE THREAD

**Issue by cncolder** [serverless/serverless#4941]
# This is a (Bug Report / Feature Proposal)

## Description

I'm testing master branch on aws `cn-north-1` region.

The `cn-north-1` region is buggy and missing some features. But It basically works if I install [serverless-aws-cn plugin](https://github.com/vitarn/serverless-aws-cn). This region cannot set environment variables. And I can prevent it in my `serverless.yml` config file.

Recently, aws support `nodejs8.10`. I try to change `provider.runtime` to new version. But cloud formation fail update:

UPDATE_FAILED | AWS::Lambda::Function | UserCreateLambdaFunction | EnvironmentVariablesFeature is not supported in cn-north-1 region. For more information, please visit the AWS Lambda documentation on Environment Variables.
-- | -- | -- | --

**I understand this is not the issue of serverless. But I want to know which step update environment variables when I change provider.runtime only? I search in `.serverless/cloudformation-template-update-stack.json` but there's no env relation settings.**

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: master
* ***Operating System***: aws lambda
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for testing @cncolder :+1: 
Umm :thinking: That behavior is very weird but I don't hit on any possible causes of the problem.
Serverless just changes`Runtime` proverty inside `AWS::Lambda::Function` Resource when you change `provider.runtime` in serverless.yml.

You might want to ask it to AWS support or forum if the problem is seen on only `cn-north-1`

**Comment by metrue** [comment]
Same issue. 😞

**Comment by metrue** [comment]
@cncolder 

Just got a response from AWS support:

> 尊敬的客户您好，

>欢迎您与亚马逊云服务技术支持团队联系，我是工程师XXX，很高兴能为您解答疑问。

> 我了解到您在使用CloudFormation对Lambda函数进行更新时遇到"EnvironmentVariablesFeature is not supported in cn-north-1 region"的问题。

> 正如您所知，由于中国区lambda不支持环境变量，尽管您在CloudFormation模板中没有使用环境变量，但是CloudFormation在更新Lambda函数时对于Lambda API的操作与全球区是一致的，因此会首先尝试调用Lambda API获取这个Lambda函数的所有配置，包括环境变量配置，但是由于中国区lambda不支持环境变量，因此CloudFormation在获取环境变量配置时会出现错误。目前我们的CloudFormation团队已经发现了这个问题并正在着手处理，还请您随时关注我们的官方博客来获取最新的信息。

> 目前我为您想到了一个替代方案来解决这个问题，您可以尝试首先将模板中Lambda函数的名字修改为其他的名字进行一次更新，然后再在模板中把名字改回来，然后再进行一次更新即可。

> 对于这个问题给您造成的困扰我们深表歉意，同时也非常感谢您向我们反馈这个问题，目前我们也在积极优化我们的服务以为您提供更好的用户体验。希望我的回答能够帮到您，如果您还有任何想要了解的问题，欢迎您随时与我们联系，我将非常乐意为您提供帮助！

> 此致 (Best Regards)，

**Comment by cncolder** [comment]
Thanks @metrue. Did you sent email or request business support ticket?

我是通过微信联系的客服，起先不承认这个是BUG，还说反馈问题需要 business support。后来按照我提供的步骤重现了问题后，给我的解决办法是手工在 AWS Console 里修改 Lambda 版本。

**Comment by metrue** [comment]
@cncolder 

Yes, above response was come from aws china' support ticket.

I tried but changing lambda function name did not help actually, so I ended up with delete whole stack then deploy a brand new one with the same name.

**Comment by cncolder** [comment]
@metrue You need change ALL function names and runtime version at same time. Then `sls deploy`. Then change back function names.

Delete stack is not my opinion. I have S3 and DynamoDB in my `serverless.yml`

**Comment by metrue** [comment]
@cncolder I see, thank.
