### ISSUE TITLE
  Serverless plugin "serverless-azure-functions" initialization errored: Cannot find module '../build/Release/keytar.node'

### ISSUE THREAD

**Issue by gerschinner** [serverless/serverless#4944]
Bug Report

root@devops-jenkins-server-01d:~/my-service# serverless deploy

  Serverless Error ---------------------------------------

  Serverless plugin "serverless-azure-functions" initialization errored: Cannot find module '../build/Release/keytar.node'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.14.2
     Serverless Version:     1.26.1

**Comment by pmuens** [comment]
Hey @gerschinner thanks for opening 👍

Could you re-open this issue in the Azure Functions plugin repository (also in the `serverless` org)? Thanks!
