### ISSUE TITLE
Add Support for Cloudflare Workers

### ISSUE THREAD

**Issue by zackbloom** [serverless/serverless#4948]
# This is a Feature Proposal

## Description

I'm an engineer on the [Workers](https://developers.cloudflare.com/workers/about/) team at Cloudflare. We'd like to start a conversation around adding support for deploying to Workers to serverless.

Workers is similar to Lambda, but your code runs on Cloudflare's edge around the world (155 data centers at the moment). This means you can run your application directly on what most people would think of as the CDN layer.

It's JavaScript based, but built on V8 directly, rather than Node, meaning its environment is more lightweight and more similar to that in a browser. The API to write a Worker is based on the Service Worker spec, and you can use build tools like Webpack to assemble files and dependencies into a Worker.

We're of the opinion that in the future people will choose to deploy not just serverless-ly, but 'originless'; That the default will be having your code run close to all your users, not in a single location. The storage infrastructure isn't necessarily there yet to accomplish that goal fully, but for things like API Gateways and stateless applications it's possible now.

**Comment by horike37** [comment]
@zackbloom 
Awesome!
When adding a new provider for Serverless Framework, you need to do the following 2 step
- create and publish the provider plugin like serverless-google-cloudfunctions, serverless-azure and so on
- send a pull request with the documentation and `serverless create` command for the provider like https://github.com/serverless/serverless/pull/4934

Ping @serverless/team

**Comment by deadcoder0904** [comment]
Any updates on this? 

Cloudfare Workers are game changing & I would love to see it combined with Serverless

**Comment by tmikaeld** [comment]
Please, @zackbloom assign someone to this, because you're missing out on companies looking to go into serverless and choosing this framework - they won't be waiting for cloudflare worker support, they will go with a different provider.

**Comment by pinkerton** [comment]
Hey @zackbloom, I'm happy to take this over and make sure it gets done soon 🚀

**Comment by zackbloom** [comment]
🔥 Let's make it happen!

**Comment by pinkerton** [comment]
Update: we've built an integration with the Serverless components framework (https://github.com/serverless/components/pull/232), and are now working on a provider plugin for the main Serverless CLI tool.

Shoutout to @nirvik and @EverlastingBugstopper for their hard work on this!
