### ISSUE TITLE
Wrong ARN in IAM Policy prevents Lambda function to write into the standard CloudWatch log

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#495]
The IAM policy in the project CF template [misspells the log's ARN name](https://github.com/serverless/serverless/blob/d743e94e68ee38286760f480712de255d9e965e5/lib/ServerlessProject.js#L76):
 
```
arn:aws:logs:${region}:*:   <-- Wrong
arn:aws:logs:${region}:*:*  <-- Correct
```

No logs were written by my Lambdas, until I found out this. I tested the fix myself, both with the IAM Policy simulator and modifying and redeploying resources from my Serverless project. I thought it was not appropriate to make a PR just for this.

**Comment by ac360** [comment]
Thanks @lorenzos!  All fixed in 4ff4cfa4efc27e237a53430263fd81c56729c401 and will be in `v0.1.2` which will be released tonight.
