### ISSUE TITLE
Support selective deployment of functions based on region and stage

### ISSUE THREAD

**Issue by rohitshetty** [serverless/serverless#4958]
# This is a Feature Proposal

## Description

For feature proposals:
* There should be some way to enable or disable deployment of certain functions depending on a attribute value. Maybe a 
```
functions:
  TestFunction:
    deploy: true
``` 

This is quite useful in case of multi-region deployments. You have Master database in one region and slave databases in other regions. You want to deploy only those functions that do read operations in slave regions, because deployment other type of functions is quite useless. 
Also in multi-region environment, it is necessary to deploy cron/scheduler functions only once.
This would be a quite useful functionality in such scenarios!

## Additional Data
Right now I can emulate this using a different configuration file (`functions.yml`) which has function seggregated under operations it does (Like PUT, POST, DELETE would be `Write`, GET would be `Read`, SNS, S3 event triggered lambdas under `Event` etc). Then use a js script as config file as described [here](https://serverless.com/framework/docs/providers/aws/guide/variables/) and return only those functions required. You also define the region, stage data in the `functions.yml` from where the data is picked by js config file and returned to the `functions` in serverless.yml.
This although works, is an overhead and is something maybe serverless can support natively.

I am new to serverless and would love to contribute back, If this feature request makes sense, then I can try making a PR.

**Comment by firecode9** [comment]
👍

**Comment by dschep** [comment]
You can leverage the variable system to do this:
```
service: sls-4958

provider:
  name: aws
  runtime: nodejs8.10

custom:
  stage: ${opt:stage, self:provider.stage}
  funcsPerStage:
    primary:
      write:
        handler: handler.write
      read:
        handler: handler.read
    replica:
      read:
        handler: handler.read

functions: ${self:custom.funcsPerStage.${self:custom.stage}}
```

See sls deploy output below:
```
$ sls -s replica deploy && sls -s primary deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................
Serverless: Stack update finished...
Service Information
service: sls-4958
stage: replica
region: us-east-1
stack: sls-4958-replica
api keys:
  None
endpoints:
  None
functions:
  read: sls-4958-replica-read
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................
Serverless: Stack update finished...
Service Information
service: sls-4958
stage: primary
region: us-east-1
stack: sls-4958-primary
api keys:
  None
endpoints:
  None
functions:
  write: sls-4958-primary-write
  read: sls-4958-primary-read
```

**Comment by pmuens** [comment]
Closing since the variable system approach (see above) is the best way to do this...

**Comment by rs-sathya** [comment]
I believe the solution to this should be a documentation page, as it was a bit hard to find this information by just googling.

**Comment by darylteo** [comment]
For future internet travellers - while searching for a solution I also came across this plugin. But sls plugins tend to be ... quickly abandoned I've found.  YMMV.

https://www.npmjs.com/package/@govtechsg/serverless-selective-functions

**Comment by GKosheev** [comment]
I recently created a plugin which deploys the function based on the boolean condition. You can read more about it here:
[https://www.npmjs.com/package/serverless-selective-function-deploy](https://www.npmjs.com/package/serverless-selective-function-deploy)
