### ISSUE TITLE
Asterisk in default variable value leads to value interpreted as string and not interpolated

### ISSUE THREAD

**Issue by aldarund** [serverless/serverless#4959]
```allowedOrigin: ${opt:allowedOrigin, 'beta.blabla.net'}```
works fine
```allowedOrigin: ${opt:allowedOrigin, '*.blabla.net'}``` 
 doesnt work

in second case allowedOrigin will be interpreted as a string e.g. its value will be ${opt:allowedOrigin, '.blabla.net'} instead of *.blabla.net

**Comment by beeceej** [comment]
It looks like the regex's used to match on the `${opt: this.that, 'def'}` pattern are not allowing the character `*`.

I can take this issue if no one else has begun work.
