### ISSUE TITLE
'Serverless: Code not changed. Skipping function deployment.' message on sls deploy -f hello

### ISSUE THREAD

**Issue by tom-thorne** [serverless/serverless#4970]
When using the built-in `aws-nodejs-typescript` template, changes in typescript files don't get propagated to webpack output when you try and deploy the function.

To Reproduce
```
> sls create -t aws-nodejs-typescript -p my-typescript
> cd my-typescript
> sls deploy 
> sls invoke -f hello

# ....all good at this point

# now edit the handler.ts file and save it

# then try to re-deploy...

> sls deploy -f hello
Serverless: Removing /Users/tomthorne/code/hello-serverless/my-typescript/.webpack
Serverless: Bundling with Webpack...
ts-loader: Using typescript@2.8.3 and /Users/tomthorne/code/hello-serverless/my-typescript/tsconfig.json
Time: 1294ms
         Asset    Size  Chunks             Chunk Names
    handler.js  125 kB       0  [emitted]  handler
handler.js.map  149 kB       0  [emitted]  handler
   [1] ./node_modules/source-map/lib/source-map-generator.js 14.4 kB {0} [built]
   [2] ./node_modules/source-map/lib/base64-vlq.js 4.71 kB {0} [built]
   [3] ./node_modules/source-map/lib/array-set.js 3.2 kB {0} [built]
   [4] multi ./source-map-install.js ./handler.ts 40 bytes {0} [built]
   [5] ./source-map-install.js 41 bytes {0} [built]
   [6] ./node_modules/source-map-support/source-map-support.js 17.2 kB {0} [built]
   [7] ./node_modules/source-map/source-map.js 405 bytes {0} [built]
  [10] ./node_modules/source-map/lib/source-map-consumer.js 40.6 kB {0} [built]
  [12] ./node_modules/source-map/lib/quick-sort.js 3.62 kB {0} [built]
  [13] ./node_modules/source-map/lib/source-node.js 13.8 kB {0} [built]
  [14] external "path" 42 bytes {0} [not cacheable]
  [15] external "fs" 42 bytes {0} [not cacheable] [optional]
  [16] ./node_modules/buffer-from/index.js 1.59 kB {0} [built]
  [17] external "module" 42 bytes {0} [not cacheable] [optional]
  [18] ./handler.ts 338 bytes {0} [built]
    + 4 hidden modules
Serverless: Zip service: /Users/tomthorne/code/hello-serverless/my-typescript/.webpack/service [23 ms]
Serverless: Packaging function: hello...
Serverless: Code not changed. Skipping function deployment.
```
The deployment is skipped since the webpack files are unchanged.
I would expect the files to be updated and the function to be deployed.

Anyone know what I'm doing wrong here?

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.2

**Comment by gulbinas** [comment]
@tom-thorne do you use any plugins or packaging in custom way your sources?

**Comment by pmuens** [comment]
Closing this for now since it's a stale issue and it looks like an external plugin is used which could interfere with the Serverless Framework. Feel free to re-open if this issue still persists.

**Comment by LosD** [comment]
@pmuens I'm having this exact issue, also in TypeScript. Weirdly enough, it only started happening after  I updated from 1.32.0 to 1.36.2 

Webpack:
```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry:  slsw.lib.entries,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  externals: [nodeExternals()],
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
};
```
Only special Serverless plugin (besides serverless-offline and serverless-webpack) is serverless-pseudo-parameters, which probably isn't touching the deployment phase at all.

**Comment by LosD** [comment]
Nevermind. The issue (and possibly also @tom-thorne's) was that another tool had compiled the JavaScript at some point, creating a new .js file right next to the .ts file. Since both matched the handler specification, Serverless just picked the .js file, which didn't get updated, making Serverless think nothing had changed.

**Comment by LosD** [comment]
Is there a way to get Serverless to consider multiple matching handlers an error? Maybe it should be an error by default, it's pretty easy to miss the warning, and I can't why it would be desirable to allow it.

**Comment by simsketch** [comment]
Make sure your typescript is getting compiled.
