### ISSUE TITLE
unable to get endpointType: regional working with serverless version 1.27.1

### ISSUE THREAD

**Issue by rohitshetty** [serverless/serverless#4972]
# This is a (Bug Report)

## Unable to set API gateway type to regional using serverless.yml -> provider -> endpointType: regional 

For bug reports:
* What went wrong?
I have a service that I use to deploy API gateway (and export rootResourceId and restApiId using cloudformation to other services to share api gateway). I wanted to enable REGIONAL endpoint, hence set the provider.endpointType to regional. But even after deployment I see the API gateway type to be edge optimized and not regional
* What did you expect should have happened?
Expected API gateway to be deployed with REGIONAL endpoint type. This [PR](https://github.com/serverless/serverless/pull/4531) suggest to look at `cloudformation-template-update-stack.json` RestAPI resource after running `serverless package` here is what I see
```
"xxxxxxxxxxxApiGateway": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "xxxxxxxxxApiGateway-xx-xxxx-xxxxx"
      }
    }
```
* What was the config you used?
* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.1
* ***Operating System***: Linux/Mint
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by a-h** [comment]
I'm not sure when the changes were merged in, but I've been migrating some existing APIs to use `endpointType: regional` with version 1.27.2 and it is working for me.

<img width="398" alt="screen shot 2018-06-14 at 13 11 41" src="https://user-images.githubusercontent.com/1029947/41411372-85d96ef4-6fd4-11e8-9032-3da44df0c0b7.png">

**Comment by pmuens** [comment]
Closing this one since it seems to be fixed in recent releases.
