### ISSUE TITLE
DX: Documentation style and consistency

### ISSUE THREAD

**Issue by rbrtmrtn** [serverless/serverless#4975]
# This is a Feature Proposal

## Description

* I feel like one of the strengths of this project is the documentation, which has a lot of helpful content and is easy on the eyes 😊 I did notice there are some things that could be cleaned up in terms of style and grammar -- capitalization, punctuation, consistent terminology, things like that. I have some experience in technical writing and would be happy to submit my suggestions, but wanted to run it by the team first. Thanks and hope that sounds helpful!

## Additional Data

n/a

**Comment by HyperBrain** [comment]
Hi @rbrtmrtn , awesome 👍 

If you have any improvements for the documentation, you can just submit PRs. We will review them the same way as code PRs and eventually they are merged.
If you do changes in the documentation, be aware that there are some identical parts of it in the documentation of the different providers, so some improvements have to be added to multiple files to keep the docs consistent.

**Comment by rbrtmrtn** [comment]
@HyperBrain sounds good, I'll submit a PR when I have some time to go over the docs! And thanks for the heads up, I'll keep an eye out for the repeated parts.

**Comment by pmuens** [comment]
Thanks for opening and thanks for the kind works @rbrtmrtn ! Really appreciate that 👍

Great suggestions as well. Feel free to submit individual PRs. That would be super helpful! Thanks again for putting this together 💯
