### ISSUE TITLE
sls deploy: endless loop on credential error in CI

### ISSUE THREAD

**Issue by hinnerk** [serverless/serverless#4976]
# This is a Bug Report

## Description

I set up a `sls deploy` in CicleCI. As there are currently no credentials configured the build is supposed to fail.

Instead goes into an endless loop: `Serverless: Recoverable error occured (AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.), sleeping 5 seconds`

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.2
* ***Operating System***: Linux, CircleCI default
* ***Stack Trace***: Nope
* ***Provider Error messages***: Serverless: Recoverable error occured (AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.), sleeping 5 seconds

**Comment by HyperBrain** [comment]
@hinnerk Thanks for the report.

This was introduces with #4877 and relates to #4957 .
As I just fixed that bug, I'll append a fix for this one to my PR (#4986 ) too, so that we can get it out in a hotfix release asap.
