### ISSUE TITLE
Response template in s-function.json generated incorrectly

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#498]
In 0.1.2 I think the default response template in s-function.json is generated slightly incorrectly:
```
"responseTemplates": {},
"application/json": ""
```

I believe it should be:
```
"responseTemplates": {
   "application/json": ""
},
```

So https://github.com/serverless/serverless/blob/de538306775e6107ca960eb4c9e51aba76816493/lib/ServerlessEndpoint.js#L47 which reads ```_this.responses['default']['application/json'] = '';``` should be ```_this.responses['default']['responseTemplates']['application/json'] = '';``` or could just include it in line 45 as ```responseTemplates: {'application/json':''}```

**Comment by eahefnawy** [comment]
great catch! thanks tons! @c-knowles :blush:
