### ISSUE TITLE
serverless project install serverless-starter does not run with '.' in path to folder

### ISSUE THREAD

**Issue by grandmore** [serverless/serverless#501]
When i run 
```serverless project install serverless-starter ```

The project fails with this message

```
Serverless: Installing Serverless Project "serverless-starter"...  
Serverless: Enter a custom name for this project:  (serverless4yulp) xxx
Serverless: Enter a custom domain for this project (used for the Serverless Project Bucket):  (serverless4yulp.com) xxx.com
Serverless: Enter an email to use for AWS alarms:  (me@serverless4yulp.com) xxx@xxx.com
Serverless: Select a region for your project: 
  > us-east-1
    us-west-2
    eu-west-1
    ap-northeast-1
Serverless: Select an AWS profile for your project: 
  > default
Serverless: Downloading project...  
{ [ServerlessError: Error: ENOENT: no such file or directory, stat '/Users/x/code.js/lambda/node_modules'] name: 'ServerlessError', messageId: undefined }
```
If I start from a project without a dot it runs correctly

I changed the path from this:
```
/Users/x/code.js/lambda
```

to this:
```
/Users/x/lambda
```

and it installs correctly.

**Comment by ac360** [comment]
@grandmore I can't recreate this issue.  Are you using Windows?

**Comment by grandmore** [comment]
Mac Yosamite
Node version 4.2

**Comment by neaghfoz** [comment]
The same problem here.
I try to create a empty folder and run 
```serverless project install serverless-starter```
then it say: **no such file or directory**

When I create the node_modules directory by myself and run again, the starter project is installed but also all of my nodejs packages are created in the same directory!

**Comment by eahefnawy** [comment]
We made huge updates and I think it includes a fix for this. Could you guys confirm?
