### ISSUE TITLE
Can't use --aws-s3-accelerate with individual function deployment

### ISSUE THREAD

**Issue by nomex26** [serverless/serverless#5010]
# This is a (Bug Report / Feature Proposal)

## Description

First of all,  thanks to everyone who's contributed to this project, Serverless is one of my favorite frameworks!

I've been very happy to discover the existence of `--aws-s3-accelerate`, which has solved the problem for me of deploying large APIs (20mb+) over poor internet connections without timeouts. However, I would also like to see this flag apply when deploying a single function, either using `-f` or `deploy function`. I've tried it out and it seems it currently ignores the `--aws-s3-accelerate` flag, e.g.:

`serverless deploy --aws-s3-accelerate -f someFunction`

As it stands, over a poor internet connection, my individual function deployments fail so I'm having to redeploy the entire service, which isn't as fast and efficient.

Similar or dependent issues: None found.

## Additional Data

* Serverless version: 1.27.3.
* OS: macOS 10.13.14.
* No stack trace.
* No provider error messages.

**Comment by medikoo** [comment]
Closing, as I belive it's fixed now, although CLI param is not recognized for all commands, and that's covered in https://github.com/serverless/serverless/issues/9812
