### ISSUE TITLE
json-cycle is causing problems with $ref in CF template

### ISSUE THREAD

**Issue by dougmoscrop** [serverless/serverless#5014]
# This is a Bug Report

## Description

If a serverless plugin reads some configuration from the .yml file and writes it in to the template multiple times (for example, for each function, create a resource) _and_ it has a property that is a complex type (such as `Fn::Join`), `json-cycle` sees these as two copies of the 'exact same' (`===`) object and replaces all but the first with `$ref`. This is invalid CF syntax.

The workaround is to _.cloneDeep everything you're inserting in to the compiledCloudformationTemplate. This isn't ideal, I don't think CF can *ever* support cyclic JSON anyway, so writing it out using `json-cycle` seems like it only breaks things at best.

And as far as I can tell, there isn't even a cycle. `json-cycle` is actually doing more than it should.

I guess serverless could clone the template deep in its entirety but I don't think it's going to matter or help.

## Additional Data

This is a self-contained reproducible example: https://github.com/dougmoscrop/serverless-example-json-ref-issue

* ***Serverless Framework Version you're using***:
latest; bug does NOT happen with 1.24.1

* ***Operating System***: OSX
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by rkdavidson** [comment]
This issue is preventing deployments without hard coding a string literal value for properties we're using `join`, `sub`, or `ref`, etc for.

I've been manually deploying outside our pipelines, which obviously is an absolute last resort workaround.

**Comment by dougmoscrop** [comment]
Just to reiterate, hopefully in brief:

- If you have a cycle, `json-cycle` will *always* output invalid CloudFormation
- If you do not have a cycle `json-cycle` will *sometimes* output invalid CloudFormation that would otherwise stringify just fine

I see no reason to use `json-cycle` in any methods dealing with writing file output.

**Comment by rkdavidson** [comment]
<img width="360" alt="screen shot 2018-06-05 at 11 50 48 am" src="https://user-images.githubusercontent.com/1812955/40996467-b9552cac-68b6-11e8-870e-55638adbdf6a.png">

@dougmoscrop, I took a glance through the uses of `json-cycle` in serverless and it's in the core utils for writing files.

Are you proposing it's safe to remove `json-cycle` step altogether, without adverse side-effects?

Seems like the solutions are:
- `_.cloneDeep` everything being inserted into `compiledCloudFormationTemplate` (not ideal)
- Use [`json-cycle#decycle`](https://www.npmjs.com/package/json-cycle#decycle) method to parse back the `$ref`s to full qualified values (which seems redundant, compressing data just to almost immediately decompress?)
- Remove `json-cycle` altogether

Couldn't figure out off-hand what purpose it serves...
Could it have been added as a premature optimization?

I'd like to take a stab at fixing this issue and opening a PR.

**Comment by HyperBrain** [comment]
@rkdavidson `json-cycle` is IMO used to serialize the serverless state (the `this.serverless.service` object). This object can have self-references at any level if you use the `self:service` variable in your configuration, which is quite common. I am sure that everything serializing and deserializing will break if you remove it without a proper replacement (in fact at all locations you posted above).

**Comment by rkdavidson** [comment]
Thanks for chiming in @HyperBrain, that makes sense — actually just read the comments in code about that, so I should have thought about that.

In that case, could a `decycle` call before outputting final compiled cloud formation template solve?

**Comment by dougmoscrop** [comment]
Decycyle is the problem.

It's not replacing "duplicate references that are part of a cycle" it's replacing *all" duplicate references with $ref

There's no scenario I can think of where the utility provided by json-cycle will be of use when dealing with the cf templates. Other serializations.. maybe, sure... But the cf template output is at best only sometimes broken by json-cycle.

**Comment by dougmoscrop** [comment]
I've proposed a strawman solution for the issue via PR - only use cycle support when opt in. I don't know if there are other places than the serverless state file that need to support cycling stuff, when writing files.
