### ISSUE TITLE
Issue in installing serverless on node 8.9.4 version

### ISSUE THREAD

**Issue by rs2712** [serverless/serverless#5018]
Bug report

Not able to install serverless with setting proxy as well as without setting proxy

For bug reports:
* What went wrong?
I am trying to install serverless and getting following issues:
1) Within office network:
   a) Installed node.js 8.9.4
   b) Set the http_proxy and https_proxy in environment variables.
   c) executed the command npm install serverless -g
   d) Getting error as follows:
        _**npm ERR! code E418
        npm ERR! 418 I'm a teapot: serverless@latest**_

2) Outside of office  network:
   a) Installed node.js 8.9.4
   b) Removed http_proxy and https_proxy in environment variables.
   c) executed the command npm install serverless -g
   d) Getting error as follows:
       **_npm ERR! code E405
       npm ERR! 405 Method Not Allowed: serverless@latest_**

* What did you expect should have happened?
I expected to get the serverless installed without any issue

* What was the config you used?
I used node.js 8.9.4

* What stacktrace or error message from your provider did you see?
**Stacktrace while installing within office network:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'serverless',
1 verbose cli   '-g' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session d817087eb0f2c3a5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 418 http://registry.npmjs.org/typescript/serverless 401ms
8 silly fetchPackageMetaData error for serverless@latest 418 I'm a teapot: serverless@latest
9 verbose stack Error: 418 I'm a teapot: serverless@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd C:\Users\429923
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "serverless" "-g"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E418
16 error 418 I'm a teapot: serverless@latest
17 verbose exit [ 1, true ]

Stacktrace while installing outside office network:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'serverless',
1 verbose cli   '-g' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 57b11f849f2272f0
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 405 http://registry.npmjs.org/typescript/serverless 562ms
8 silly fetchPackageMetaData error for serverless@latest 405 Method Not Allowed: serverless@latest
9 verbose stack Error: 405 Method Not Allowed: serverless@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd C:\Users\429923
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "serverless" "-g"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E405
16 error 405 Method Not Allowed: serverless@latest
17 verbose exit [ 1, true ]

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: Windows 64 bit
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @rs2712 👍

We've pushed some changes include a fix for such issues. Closing this for now since newer versions of the Serveless Framework should solve this problem.
