### ISSUE TITLE
Can't login via GitHub

### ISSUE THREAD

**Issue by djalmaaraujo** [serverless/serverless#5020]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

I typed `serverless login`, browser opened, I accept the github login

* What did you expect should have happened?
To be logged in

* What was the config you used?

default, installed serverless cli and typed login

* What stacktrace or error message from your provider did you see?

![image](https://user-images.githubusercontent.com/3402/40944762-dc3dfcee-684d-11e8-845c-d4cd9b2257ea.png)

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3

* ***Operating System***: macOS
* ***Stack Trace***:
* ***Provider Error messages***:
![image](https://user-images.githubusercontent.com/3402/40944762-dc3dfcee-684d-11e8-845c-d4cd9b2257ea.png)

**Comment by pmuens** [comment]
Closing since this is quite an old issue and we've fixed related issues in the past.

Feel free to re-open if this is still a problem.
