### ISSUE TITLE
API Gateway not being configured properly (I think)

### ISSUE THREAD

**Issue by bencooper222** [serverless/serverless#5022]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
My AWS function worked locally but failed when deployed to AWS - the get request responded with "Internal Server Error"
* What did you expect should have happened?
The same response that I got locally
* What was the config you used?
You can find the whole repo and the config [here](https://github.com/hacksecure/utility-serverless-functions/blob/master/serverless.yml)
* What stacktrace or error message from your provider did you see?
Just the normal three logs on Cloudwatch with the start, end and billing details of the function execution

Similar or dependent issues:
* #4705 - I'm fairly certain that I'm having this issue but the mitigations specified there aren't doing anything

## Additional Data

* ***Serverless Framework Version you're using***:
1.25.x and 1.27.3 failed.
* ***Operating System***:
WSL and macOS High Sierra both failed
* ***Stack Trace***:
* ***Provider Error messages***:
I wish.

**Comment by bencooper222** [comment]
Turns out this is an error with `serverless-offline` being overly generous about stringifying JSONs. I'm still not sure if this could be related to an API Gateway error in terms of configuring response body type.

**Comment by pmuens** [comment]
Thanks for opening @bencooper222 👍

I'll close this since it's an error in `serverless-offline` and therefore not related to the Serverless Framework itself.
