### ISSUE TITLE
Support AWS Secrets Manager

### ISSUE THREAD

**Issue by pharindoko** [serverless/serverless#5024]
For feature proposals:
The use case is the same as for SSM Parameter Store. 
Storing secrets like database connection parameters / api keys  etc.

Would be nice to choose between SSM Parameters Store and the AWS Secrets Manager for storing configs and secrets.

**Comment by e-e-e** [comment]
Is there any progress on this proposal? I am currently working on a project which would benefit from a simple interface to AWS secrets manager.

**Comment by ronkorving** [comment]
Yes, this please! 💯

**Comment by eahefnawy** [comment]
@ronkorving thanks for pitching in. Could you explain how you intend to implement this? and what the experience would be like for using this feature?

**Comment by pharindoko** [comment]
Same behaviour and implementation as for the Parameter Store (SSM).
Just the option to choose between one or the other....

**Comment by eahefnawy** [comment]
@pharindoko I like that. We'd def appreciate a PR! 😊

**Comment by e-e-e** [comment]
This might not be as trivial as mirroring the SSM syntax.

Secrets manager stores multiple key values in the secrets as text. Commonly key values are stored in text as JSON, but this is not necessarily the only way they are stored. Users can use any serialisation that they want. 

If we ignored the alternative ways of storing the key values, and assume secrets are always key/value JSON, then we could use the syntax `{secret:name_of_secret.key}`.

But given users are charged each time a key is decrypted we would also probably need to cache the secret so that `{secret:name_of_secret.foo}` and {secret:name_of_secret.bar} don't make two requests unnecessarily.

Just some quick thoughts.

**Comment by ronkorving** [comment]
Excellent points. To be honest, I've kinda changed strategies here. Pulling in secrets and storing them locally in a cloud formation file sort of goes against keeping these secrets really secret in the first place. I'm going to change my strategy.

**Comment by e-e-e** [comment]
@ronkorving I really agree - really SSM shouldn't be used for encrypted values either for the reasons you mentioned. 

We ended up storing env vars that point to the secret key, and then in our lambda's we fetch and cache them before executing the hander.

**Comment by ronkorving** [comment]
@e-e-e I was thinking of doing exactly that

**Comment by pharindoko** [comment]
I used both methods:
- request at runtime
- request via env vars directly

The question is how secure or risky it is to implement this solution.

My Assumption:
As far as I understand a cloudfornationfile will be transmitted and uploaded having the secrets already injected, when you do **serverless deploy**. 
The package itself will be immediately created in .serverless folder and destroyed after successful upload.
This upload is hopefully encrypted right ? at least with ssl.

That would be ok for my solutions.
If someone accesses these files on my laptop I have a bigger issue.

I would not use this solution for a cashcow service where I make millions.
But in my eyes then you would have a different setup (k8s, fargate, docker) even because of costs.

So yes I still would like to have it :)
Key:Value Pair Style...

**Comment by BethanyBerkowitz** [comment]
I haven't tried this yet, but it looks like you can now access secrets from the Secrets Manager via the SSM Parameter Store, so this may be supported with no code changes. 

https://aws.amazon.com/about-aws/whats-new/2018/07/aws-systems-manager-parameter-store-integrates-with-aws-secrets-manager-and-adds-parameter-version-labeling/

https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html

**Comment by Imran99** [comment]
+1. Secrets manager also supports key rotation via a custom lambda, not sure if SSM can do that.

**Comment by q42jaap** [comment]
@agonbina `${ssm:/aws/reference/secretsmanager/my/key~true}` doesn't work for me,
`${ssm:/aws/reference/secretsmanager/my~true}` does work, but gives back the whole secret as a json serialized thing. I need to get usernames and passwords out of the json to individual parameters.
Can this be done in serverless.yml?

**Comment by agonbina** [comment]
@q42jaap I don't think you can access individual keys even with secrets manager itself. You have to parse the entire secret and extract what you need from it.

**Comment by q42jaap** [comment]
@agonbina I thought so too, is that something that can be done in the `serverless.yml` file?

**Comment by agonbina** [comment]
I am not aware of a serverless feature where you can use(or create) some sort of functions to parse and extract values such as in this case (but this would be a nice feature for sure!)

**Comment by revmischa** [comment]
An easy way to use secrets manager with serverless would make my life easier

**Comment by dschep** [comment]
There's nothing builtin @revmischa, but you can always use serverless' support for javascript files in variables:

in `secret.js`:
```javascript
const AWS = require('aws-sdk')
const secretsmanager = new AWS.SecretsManager()
module.exports.foobar = () => secretsmanager.getSecretValue({SecretId: "YOURSECRETID"})
  .promise()
  .then(({SecretString}) => SecretString)
```

in `serverless.yml`:
```yaml
custom:
  foobar: ${file(secrets.js):foobar}
```

**Comment by bradennapier** [comment]
This should actually be added to support the case you want ot read many files to stop reading the secret many times (you pay per decrypt). 

It should parse it once and re-use the secret any time requested during a deployment.

**Comment by jmsg1990** [comment]
You can do this by adding a secrets section to your serverless.yml like this:

```
custom:
  secrets: ${ssm:/aws/reference/secretsmanager/my-secrets~true}
```
Then, you can reference your secrets stored in ssm anywhere in you yml using something like this: `${self:custom.secrets.db_root_username}`

The name `secrets`, `my-secrets` and `db_root_username` are used here just as an example.
Also, I like naming the secret store using variables so I can do this:

```
custom:
  secrets: ${ssm:/aws/reference/secretsmanager/${self:service.name}-${self:provider.stage}~true}
```

**Comment by rakeshsehgal1** [comment]
Did the above work for anyone? It did not work for me, could someone please share a complete example of the yml file they used to get it work?
Thanks!

**Comment by jmsg1990** [comment]
@rakeshsehgal1  I think that it is weird that the error message mentions `A valid file`. There might be a typo in your settings, so serverless is looking for a file instead of accessing ssm.
I've seen errors in relation to SSM such as `A valid service attribute to satisfy the declaration 'self:custom.settings.ssm.test' could not be found.` or `A valid SSM parameter to satisfy the declaration 'ssm:/aws/reference/secretsmanager/my-secrets~true' could not be found.`
I don't have a full yml to share (I split most into several parts) but if you share yours I could help you.

**Comment by rakeshsehgal1** [comment]
Thanks @jmsg1990, here is my yml:
`service: my-checks
 provider:
   name: aws
   runtime: nodejs12.x
   stage: prod
   custom:
     secrets: ${ssm:/aws/reference/secretsmanager/my_check_secrets~true}
functions:
  myCheckLambda:
    handler: handler.myCheckLambda
    environment:
      myCreds: ${self:custom.secrets}
`
The my_check_secrets is in AWS Secret manager as a json. And then in my code trying to access _process.env.myCreds_ to get the json or the value. Thanks for helping out!

**Comment by jmsg1990** [comment]
@rakeshsehgal1 the problem is the indentation. Your `custom` section ended up inside the `provider` section. I guess this should work (haven't tested it though)

```
service: my-checks  
provider:
   name: aws
   runtime: nodejs12.x
   stage: prod
custom:
   secrets: ${ssm:/aws/reference/secretsmanager/my_check_secrets~true}
functions:
  myCheckLambda:
    handler: handler.myCheckLambda
    environment:
      myCreds: ${self:custom.secrets}
```

I hope it helps!

**Comment by rakeshsehgal1** [comment]
Thanks @jmsg1990 this works, that was the only indentation I had not tried :) .
Just to make it easier for someone else, in the final yml I directly used my key from the secret:
```
    environment:
      envKey1: ${self:custom.secrets.key1}
      envKey2: ${self:custom.secrets.key2}
```
when the AWS secret is stored as:
{
  "key1": "value1",
  "key2": "value2"
}
and then in your code directly access `process.env.envKey1`. Not sure if it's possible to use the entire custom object or not.

**Comment by 300LiterPropofol** [comment]
> Thanks @jmsg1990 this works, that was the only indentation I had not tried :) .
> Just to make it easier for someone else, in the final yml I directly used my key from the secret:
> 
> ```
>     environment:
>       envKey1: ${self:custom.secrets.key1}
>       envKey2: ${self:custom.secrets.key2}
> ```
> 
> when the AWS secret is stored as:
> {
> "key1": "value1",
> "key2": "value2"
> }
> and then in your code directly access `process.env.envKey1`. Not sure if it's possible to use the entire custom object or not.
It is really kind of you for sharing this!! Really helps me. Thank you a lot @raakasf

**Comment by gazal-k** [comment]
we have a secret with JSON value like

```json
{
  "encrypt.key": "123",
  "encrypt.initVector": "456"
}
```

Referencing it in serverless like:

```yaml
custom:
  secrets: ${ssm:/aws/reference/secretsmanager/secret-name~true}
```

In the generated `serverless-state.json`, I can see that the JSON value is retreived correctly

```json
    "custom": {
      "secrets": {
        "encrypt.key": "123",
        "encrypt.initVector": "456"
      }
    }
```

I've tried a few different ways to read that into the environment variables of our lambda fns

```yml
  environment:
    ENCRYPT_KEY: ${self:custom.secrets.encrypt.key}
    ENCRYPT_INIT_VECTOR: ${self:custom.secrets.encrypt.initVector}
```

results in the following in the state file

```json
      "Environment": {
        "Variables": {
          "ENCRYPT_KEY": {},
          "ENCRYPT_INIT_VECTOR": {}
        }
      }
```

Also tried:
```yml
  environment:
    ENCRYPT_KEY: ${self:custom.secrets['encrypt.key']}
    ENCRYPT_INIT_VECTOR: ${self:custom.secrets['encrypt.initVector']}
```

but that produces

```json
      "Environment": {
        "Variables": {
          "ENCRYPT_KEY": "${self:custom.secrets['encrypt.key']}",
          "ENCRYPT_INIT_VECTOR": "${self:custom.secrets['encrypt.initVector']}"
        }
      }
```

Any suggestions on how we can extract the secret values?

**Comment by gazal-k** [comment]
I think I fugured it out. I used a js file (https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-javascript-files) to transform the secret.


`transformSecretsManagerResponse.js`
```js
module.exports = serverless => {
	const actualFn = serverless.variables.getValueFromSsm;

	const wrapper = async variableString => {
		const response = await actualFn.call(serverless.variables, variableString);

		if (typeof response === 'object') {
			const transformedResponse = {};
			Object.keys(response).forEach(key => {
				transformedResponse[key.replace('.', '_')] = response[key];
			});
			return transformedResponse;
		}
		return response;
	};

	const ssmResolver = serverless.variables.variableResolvers.find(
		variableResolver => variableResolver.serviceName === 'SSM'
	);
	ssmResolver.resolver = wrapper;

	return 'nothing';
};

```

and in `serverless.yaml`

```yaml
custom:
  transformSecrets: ${file(transformSecretsManagerResponse.js)}
```
