### ISSUE TITLE
AWS Lambda Serverless Error: Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by tanvirheer** [serverless/serverless#5026]
# Error when deploying server on serverless lambda (pip3 package).

## Description
I followed the "How to handle your python packaging in lambda with serverless plugins" tutorial and it worked perfectly with no errors. Link: https://serverless.com/blog/serverless-python-packaging/.

However, when I started creating my own project that has pip3 packages that needed to be installed, I ran into some issues. Everything was fine up to the point when I had to do **'serverless deploy'.** 

I have **two** packages that need to be installed. **Pybind11** and **pythonexample2**. When I did **'pip3 install pybind11'** in my (venv), that worked perfectly and caused no issues. However, **"pythonexample2"** is a **local folder** that I have added to current working directory that needs to be built in order for it to work. **"pip3 install ./pythonexample2/"** must be executed for it to work. So, I executed that command within my (venv) and did:

**(venv) $ pip freeze > requirements.txt
(venv) $ cat requirements.txt**

**Output:** 

pybind11==2.2.3
pythonexample2==0.0.1

Everything seemed fine and I continued following the tutorial and did **'serverless deploy'**. This is what I ran into, error shown below.

## Error:
Serverless: Installing requirements of requirements.txt in .serverless...
Serverless: Docker Image: lambci/lambda:build-python3.6
 
  Error --------------------------------------------------
 
    Could not find a version that satisfies the requirement pythonexample2==0.0.1 (from -r .serverless/requirements.txt (line 2)) (from versions: )
No matching distribution found for pythonexample2==0.0.1 (from -r .serverless/requirements.txt (line 2))

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.3.0
     Serverless Version:     1.27.3

## Debugging

When I got this error, I double checked **.serverless/requirements.txt** for the version number and also checked **requirements.txt.** They were both **same**, i'm not sure what's going on.

Also, here is the output when I did pip3 installed the packages I needed:

**(venv) python_example2$ pip3 install pybind11**
Collecting pybind11
  Using cached https://files.pythonhosted.org/packages/12/90/0f92a575dc60c8fba6d0c91d6b45abdb1058da9ebed40400cbcfad2ac0a7/pybind11-2.2.3-py2.py3-none-any.whl
Installing collected packages: pybind11
Successfully installed pybind11-2.2.3

**(venv) python_example2$ pip3 install pythonexample2/**
Processing ./pythonexample2
Requirement already satisfied: pybind11>=2.2 in ./venv/lib/python3.6/site-packages (from pythonexample2==0.0.1) (2.2.3)
Building wheels for collected packages: pythonexample2
  Running setup.py bdist_wheel for pythonexample2 ... done
  Stored in directory: /private/var/folders/...
Successfully built pythonexample2
Installing collected packages: pythonexample2
Successfully installed pythonexample2-0.0.1

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: Mac OS
* ***Stack Trace***:
* ***Provider Error messages***:
Also, I am using python 3.6.4 and pip 10.0.1.

**Comment by tanvirheer** [comment]
Fixed issue by editing version in serverless.yaml

**Comment by foxish** [comment]
Ran into this also. Was using the wrong Python version in serverless.yaml.

```
provider:
  name: aws
  runtime: python2.7
-----------------------^
```
