### ISSUE TITLE
Error on create project

### ISSUE THREAD

**Issue by boadude** [serverless/serverless#505]
When i try to create a project give me this error:

<code>
Serverless: Deploying resources to stage "development" and region "us-east-1" via Cloudformation.  This could take ~5 minutes depending on how many resources you have...
Serverless: / { [SignatureDoesNotMatch: Signature expired: 20160121T201911Z is now earlier than 20160121T201946Z (20160121T202446Z - 5 min.)]
  cause:
   { [SignatureDoesNotMatch: Signature expired: 20160121T201911Z is now earlier than 20160121T201946Z (20160121T202446Z - 5 min.)]
     message: 'Signature expired: 20160121T201911Z is now earlier than 20160121T201946Z (20160121T202446Z - 5 min.)',
     code: 'SignatureDoesNotMatch',
     time: Thu Jan 21 2016 17:19:12 GMT-0300 (Hora est. Sudamérica Pacífico),
     requestId: '03198ffe-c07d-11e5-b803-7d4ad7fb9258',
     statusCode: 403,
     retryable: true },
  isOperational: true,
  code: 'SignatureDoesNotMatch',
  time: Thu Jan 21 2016 17:19:12 GMT-0300 (Hora est. Sudamérica Pacífico),
  requestId: '03198ffe-c07d-11e5-b803-7d4ad7fb9258',
  statusCode: 403,
  retryable: true }
</code>

**Comment by ac360** [comment]
@boadude Did you follow the configuration instructions int eh documentation?  I believe this issue is usually caused by a mistyped Access or Secret key.  Could you give me any other information about this?  Thanks :)

**Comment by boadude** [comment]
> " believe this issue is usually caused by a mistyped Access or Secret key"

I don't think so, because serverless create the bucket... but went go to the state

> "Deploying resources to stage "development" and region "us-west-2" via Cloudformation.  This could take ~5 minutes depending on how many resources you have..."

Give me the error. I try in different regions, different buckets, and nothing. I follow the instruction for **"Create An Administrative IAM User"**

**Comment by boadude** [comment]
**FIXED**

For some reason the time of my time was wrong (UTC -03:00). The clock was 5 minutes late. I came to that because the error say:

> Signature expired: 20160121T201911Z is now earlier than 20160121T201946Z (20160121T202446Z - 5 min.

Manually I change the hour, and done is all good now.

Greatting!

**Comment by sehgal-kanika** [comment]
Thanks alot @codingandfitness , i m digging the issue for more than 2 hours

**Comment by adir1661** [comment]
I'm having the same issue...
can someone help me how to solve it

`Serverless: Recoverable error occurred (Signature expired: 20190606T073158Z is now earlier than 20190606T073238Z (20190606T073738Z - 5 min.)), sleeping for 5 seconds. Try 2 of 4
`

**Comment by tanrax** [comment]
```
Serverless: Recoverable error occurred (Signature expired: 20190423T131857Z is now earlier than 20190820T143217Z (20190820T143717Z - 5 min.)), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (Signature expired: 20190423T131906Z is now earlier than 20190820T143226Z (20190820T143726Z - 5 min.)), sleeping for 5 seconds. Try 2 of 4
...
```
