### ISSUE TITLE
CLI argument being converted to number and rounded up

### ISSUE THREAD

**Issue by JmeG** [serverless/serverless#5050]
# This is a Bug Report

## Description

Command line argument '2060451113271393738' is being converted to a number and then rounded up to 2060451113271393800 in options array.

* What went wrong?  
Calling KMS Secrets plugin, the string value '2060451113271393738' is being converted by the CLI processInput function to 2060451113271393800. The use of the minimist(inputArray) function appears to be causing the problem.

https://github.com/serverless/serverless/blob/master/lib/classes/CLI.js#L37

Here's the line in the minimist package that converts the argument to a number. https://github.com/substack/minimist/blob/master/index.js#L59

* What did you expect should have happened?
It should have treated my value as a string. 

* What stacktrace or error message from your provider did you see?

```sh
sls encrypt -n TEST_ENCRYPT -v '2060451113271393738' -s dev -r us-east-1

DEBUG Before call to minimist(inputArray);
[ 'encrypt',
  '-n',
  'TEST_ENCRYPT',
  '-v',
  '2060451113271393738',
  '-s',
  'dev',
  '-r',
  'us-east-1' ]

DEBUG After call to minimist(inputArray);
{ _: [ 'encrypt' ],
  n: 'TEST_ENCRYPT',
  v: 2060451113271393800,
  s: 'dev',
  r: 'us-east-1' }

```

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3

* ***Operating System***:
macOS Sierra

**Comment by AjinkyaChalke** [comment]
Hi, can I work on this? Or is anyone working on it currently?
Thanks!

**Comment by 07Gond** [comment]
Hi @RafalWilinski it is still relevant this issue?
@JmeG I play around with the code and I think that I have a workaround with the code.
Do you still need it? Pass all tests so, I can push into my fork for your testing.

**Comment by JmeG** [comment]
Hi @07Gond I am still able to reproduce this bug using SLS version 1.31.0.  I believe this is a bug that needs to be resolved. I've worked around it myself for now but this should be fixed in the Serverless platform with how it handles command line arguments.

What's the approach in your workaround?

**Comment by 07Gond** [comment]
Hi! @JmeG 
I notice that when the CLI parse the args always pass the numbers like strings. So whether it is a number or a string(of numbers) the 'minimist' is the one that always converts it to numbers even if you want it like string.
So, after the CLI get the args, before the pass to the 'minimist' I'm handling the string values and encoding to a base64 string like a workaround. After the minimist process, I get again the values and decoding again to get the original values.

**Comment by 07Gond** [comment]
@RafalWilinski I just send a PR to review with this workaround. :)
