### ISSUE TITLE
[question] Agnosticly invoke other function from js function

### ISSUE THREAD

**Issue by cyrilchapon** [serverless/serverless#5056]
Is there a way to invoke another function from a function js code ?

I mean, I know about `aws-sdk` ways but not about an agnostic way to accomplish that.

Though, the cli is able to do it.. with `serverless invoke`

Can we use the cli internal code to accomplish the same thing ?

**Comment by pmuens** [comment]
Hey @cyrilchapon thanks for opening 👍

There are a couple of different ways how you could do it. Some people add SQS / SNS event sources to their functions and then send an event via the other function there to invoke the function(s) in question. Another "idiomatic" way is to use the `aws-sdk` to invoke the function via an SDK call.

We've used direct function invocations in the past and it worked quite fine. However I you need DLQ / more reliability and stuff like that you might be better off with an intermediary service.
