### ISSUE TITLE
Support for new Endpoint type " PRIVATE"

### ISSUE THREAD

**Issue by chamathsilva** [serverless/serverless#5063]
# This is a  Feature Proposal

## Description

For feature proposals:
Using Amazon API Gateway, we can now create private REST APIs that can only be accessed from your Amazon Virtual Private Cloud (VPC) using an interface VPC endpoint. 

To do that we have to set up "Endpoint Type": PRIVATE. But Serverless framework does not allow to use this Endpoint Type (Only allow "REGIONAL" or "EDGE" ). Can you Include support for this new Endpoint type via Serverless framwork. 

For more details please refer this: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version ***: 1.27.3
* ***Operating System***: linux
* ***Stack Trace***:
* ***Provider Error messages***:   endpointType must be one of "REGIONAL" or "EDGE". You provided PRIVATE.

**Comment by chamathsilva** [comment]
Is this feature relevant? If so I like to contribute

**Comment by horike37** [comment]
@chamathsilva 

>Is this feature relevant?

Yes! However, a status of this issue may be wait-for-cloudformation. To start implementation, CloudFormation will be supported for this feature.

**Comment by theburningmonk** [comment]
CloudFormation just announced support for this! https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

:-D
