### ISSUE TITLE
Document how to access config & methods of Serverless instance passed to variable reference function in Javascript file

### ISSUE THREAD

**Issue by aneilbaboo** [serverless/serverless#5064]
# This is a Feature Proposal (Documentation Request)

## Description

Is there any documentation of the Serverless class itself? The main use case is how to use the instance that's passed to Javascript files by the variable system.

For example, in the docs, there's this code snippet, which suggests you can access config and instance methods:
https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files

```js
// config.js
module.exports = (serverless) => {
  serverless.cli.consoleLog('You can access Serverless config and methods as well!');

  return {
    property1: 'some value',
    property2: 'some other value'
  }
}
```

Is there any documentation on how to do this? For example access config values, resolve variables, access options, available methods.

**Comment by sorachan** [comment]
While this is far from being any sort of documentation of the Serverless class, I've found a workaround that at least lets you have a closer look at the details of your Serverless object:

### step 1: create a JavaScript file

Create a file `workaround.js` with contents

```javascript
module.exports.test = (serverless) => {
    // replace '...' by the element you need information on, for example 'serverless'.
    serverless.cli.consoleLog(...);
    return {};
}
```
### step 2: reference said file in your `serverless.yml`

```yaml
[...]
provider:
  [...]
  environment:
    TEST: ${file(workaround.js):test}
  [...]
[...]
```

### step 3: run `serverless package`

This will do roughly the same thing as `serverless deploy` without changing anything in your cloud.

Your `test` function will be run, giving you some console output like this:

```
Serverless {
  providers:
   { aws:
      AwsProvider {
        naming: [Object],
        options: [Object],
        provider: [Circular],
        serverless: [Circular],
        sdk: [Object],
        requestCache: {},
        requestQueue: [Queue],
        cachedCredentials: null } },
  version: '1.41.1',
  yamlParser: YamlParser { serverless: [Circular] },
  utils: Utils { serverless: [Circular] },
  service:
   Service {
     serverless: undefined,
     service: 'example-service',
     serviceObject: { name: 'example-service' },
     provider:
      { stage: 'dev',
        region: 'eu-central-1',
[...]
```

### step 4: back to step 1

Repeat the previous steps, modifying the argument of `consoleLog` until you've either found the information you need or hit a dead end. For example, I wanted to have a look at whether references are already resolved by the time the script is called. (Spoiler alert: the answer seems to be no.) Therefore I've had a look at the output of

    serverless.cli.consoleLog(serverless)

to find an attribute called `service.provider.environment` which in turn became the next thing I've tried:

    serverless.cli.consoleLog(serverless.service.provider.environment)

and so on...

(This workaround is ugly, but I feel that might be slightly more useful than no documentation at all and slightly less frustrating than trying to understand the source files in `lib/node_modules/serverless`.)

**Comment by medikoo** [comment]
Closing as recently we've introduced a new variables resolver. And all access means are documented at: https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-other-files
