### ISSUE TITLE
Vulnerabilites Report for Serverless

### ISSUE THREAD

**Issue by swetamohapatra** [serverless/serverless#5067]
Post npm audit run, few high vulnerabilities have been reported.

  High            Denial of Service

  Package         https-proxy-agent

  Patched in      >=2.2.0

  Dependency of   serverless [dev]

  Path            serverless > https-proxy-agent

  More info       https://nodesecurity.io/advisories/593

But, on check Serverless is up-to-date.
Please let us know what needs to be done to fix these vulnerabilities

**Comment by backdoorcodr** [comment]
Thank you @swetamohapatra for opening up this issue. The same issue is for me. 

Waiting for the contributors to respond on how to fix this issue.

**Comment by pbadeer** [comment]
Master branch of serverless is not representative of the latest release of serverless, which is 1.27.3.

In the latest release of serverless the https-proxy-agent package is still on "^1.0.0"
https://github.com/serverless/serverless/blob/v1.27.3/package.json

I think we would all appreciate this fix being released as a patch (1.27.4) as soon as possible. Thank you!

**Comment by abmohan** [comment]
Any updates on this? 

Is it just a matter of bumping the `https-proxy-agent` version and running the tests to make sure nothing broke? If so, I'm happy to do that.

**Comment by abmohan** [comment]
This is resolved in v1.28.0
