### ISSUE TITLE
1.27.3 is not properly tagged

### ISSUE THREAD

**Issue by odedniv** [serverless/serverless#5076]
Sorry, this is not a bug report nor a feature proposal so I removed the template...

https://github.com/serverless/serverless/pull/4197/commits/eac5ab5f045babc8370577fc02a3224efe4b6742 is in `master` but not in the tag `v1.27.3`.

The [release notes](https://github.com/serverless/serverless/releases/tag/v1.27.3) and the [changelog](https://github.com/serverless/serverless/blob/master/CHANGELOG.md) both specify this feature was taken into `v1.27.3`.

Running `npm install serverless` (which gives me `v1.27.3`) includes the piece of code added in that commit:

```javascript
// node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js

...

      if (http.authorizer.type && http.authorizer.authorizerId) {
        return {
          Properties: {
            AuthorizationType: http.authorizer.type,
            AuthorizerId: http.authorizer.authorizerId,
          },
        };
      }
```

My conclusion is that `npm publish` and `git tag` were executed on different commits.

**Comment by alexander-alvarez** [comment]
I concurr with this assesment -- the `PluginManager` is at least 3 months outdated in `v1.27.3`
https://github.com/serverless/serverless/blob/438cfca829a6f531ba13f8432b0c7e62746a2101/lib/classes/PluginManager.js

**Comment by alexander-alvarez** [comment]
Also `1.27.0`, `1.27.1` and `1.27.2` are wrong

https://github.com/serverless/serverless/commits/master/lib/classes/PluginManager.js hasn't been touched since April yet going back to npm installing `1.27.0` yields:

```diff
// commit from last change of plugin manager
$ curl https://raw.githubusercontent.com/serverless/serverless/b9c7260881d0696153f6b06952d627f68ea21cde/lib/classes/PluginManager.js > out.txt && sha1sum out.txt
+ fd30e338f15d79bcce85ab276176d3eecc6155f2

$ npm install -g serverless@1.27.2
$ sha1sum node_modules/serverless/lib/classes/PluginManager.js
- 202a2148e60d64361fd6be2e1aec2c67d64d0a62
-// same results for 1.27.1, and 1.27.0
```

**Comment by pmuens** [comment]
Thanks for opening @odedniv 👍

Good catch! ccing @dschep and @eahefnawy here. Closing this for now since our release process should cover this issue.
