### ISSUE TITLE
Terminal colors

### ISSUE THREAD

**Issue by lpinca** [serverless/serverless#508]
Hello,
I use a black on white terminal and when I run `--help` some text is unreadable.
Here is a screenshot:
![screen shot 2016-01-22 at 08 48 41](https://cloud.githubusercontent.com/assets/1443911/12505223/27ce8272-c0e5-11e5-9da0-a915bffb7563.png)

Maybe it makes sense to use a different background color here:
https://github.com/serverless/serverless/blob/72489fd884542d6be749771c36b3d8e0a12f04a1/lib/utils/cli.js#L343
https://github.com/serverless/serverless/blob/72489fd884542d6be749771c36b3d8e0a12f04a1/lib/utils/cli.js#L363

**Comment by ac360** [comment]
Thanks @lpinca.  I just pushed a fix for this in 2ae8f0accf4047756cc718ccb947483efee2dc05 which makes those black boxes black text against the white bg.

This will be in `v0.1.3` which will be released tomorrow.  Or you can install from the Master branch, but it might be unstable.
