### ISSUE TITLE
 Failed to deploy function (openwhisksauce-dev-app) due to error: PUT

### ISSUE THREAD

**Issue by bhaskarndas** [serverless/serverless#5081]
my serverless.yml file
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: openwhisksauce

provider:
  name: openwhisk
  runtime: nodejs:10.3.0

functions:
  app:
    handler: handler.openwhisksauce
    # The `events` block defines how to trigger the http events
    
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
# remember to run npm install to download the provider plugin.        
plugins:
    - serverless-openwhisk

handlers.js file

const serverless = require("serverless-http");
const hbs = require("hbs");
const express = require("express");
const bodyParser = require("body-parser");

const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
// parse application/json
app.use(bodyParser.json());
app.set("view engine", "hbs");

app.get("/", function(req, res) {
  res.status(200).render("index");
});

module.exports.openwhisksauce= serverless(app);

The issue comes when I run serverless deploy command.

**Comment by pmuens** [comment]
Thanks for opening @bhaskarndas 👍

This is definitely weird. Could you re-open this issue in the Serverless Examples repository? Thanks!
