### ISSUE TITLE
Update aws-nodejs runtime to nodejs8.10

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#5087]
# This is a Feature Proposal

## Description

We should update the default runtime from `nodejs6.10` to `nodejs8.10`.

The LOC which sets the runtime can be found [here](https://github.com/serverless/serverless/blob/b10c649ff68d6142ec5aa1c7136493d564ccc4dc/lib/plugins/create/templates/aws-nodejs/serverless.yml#L22)

Similar or dependent issues:
* #4992 
* #4911

**Comment by kevinrambaud** [comment]
Submitted a PR #5088

**Comment by pmuens** [comment]
> Submitted a PR #5088

Awesome1 Thanks @kevinrambaud ! 💯 👍
