### ISSUE TITLE
Breaking change in 1.28.0: Environment variable ... must contain string

### ISSUE THREAD

**Issue by timrog1** [serverless/serverless#5094]
# This is a Bug Report

## Description

After updating today to 1.28.0, Serverless (or a dependency) now expects all environment variables to be strings. This sounds reasonable, but it's a breaking change so I'm making people aware.

In YAML, if a string is unquoted then it gets interpreted as a number if it only contains digits. E.g.

```
AWS_ACCOUNT_ID: 1234567890
```
is different to 
```
AWS_ACCOUNT_ID: '1234567890'
```

Our CI pipeline uses YamlDotNet to generate the Yaml which contains the environment variables. This has an  [open issue](https://github.com/aaubry/YamlDotNet/issues/237) where it cannot serialize numeric strings properly.

Running `serverless deploy` now gives 

```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

  Environment variable AWS_ACCOUNT_ID must contain string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.11.1
     Serverless Version:     1.28.0
```

Working around for us is not trivial. If it's easy for Serverless to resolve this breaking change, it may help others. I've solved this for now by fixing Serverless version to 1.27.1

Similar or dependent issues:

## Additional Data

* 1.28.0:
* win64:

**Comment by githubflub** [comment]
Seconded.

**Comment by marztierney** [comment]
Thirded.

**Comment by cdelgadob** [comment]
Same here... fourthed?

**Comment by lbalceda** [comment]
+1

**Comment by footballencarta** [comment]
+1 had to downgrade to 1.27.3, serious breaking bug.

**Comment by mzvrzg** [comment]
+1

**Comment by adamdmharvey** [comment]
+1 (also thumbed up 👍 the initial comment).  We had multiple pipelines begin failing late last week, and traced it back to this breaking update.  May make us rethink our pinning serverless versus vs. leading latest, but hoping 1.28.1 is coming soon. Also wonder regarding any future alignment to semver versioning for the package? We'd love to understand when breaking changes are coming (2.x) to make a decision, and let us pin to 1.x for all backward-compat feature enhancements, security patches, etc.

**Comment by horike37** [comment]
This bug was unintentionally introduced by #4890.
My possible solution to the problem is here

- Remove [only contain string check](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/functions/index.js#L265-L267) when `sls deploy`. This cause the breaking.
- Add single-quotation to env value itself just before deploying to avoid the Lambda API error if it contain only number when `sls deploy function`

We should cut a patch release as soon as possible.

cc: @serverless/framework-maintainers

**Comment by HyperBrain** [comment]
@horike37 Agree. We should put that into 1.28.1. I will create a patch branch and cherry pick as soon as a solution is ready.

> Add single-quotation to env value itself just before deploying to avoid the Lambda API error if it contain only number when sls deploy function

Is this enough, or do we have to cover cases where an env var is set to an object too?

**Comment by mzvrzg** [comment]
I'm trying to add environment variable to lambda function, no matter what I do, I keep running into variable must be string error message.  What should the syntax look like to force env param into string?

so far I've tried below syntax, but they all failed
    environment: 
        SAMPLE_PARAM: "${opt:dxc-aws-account,self:provider.custom.dxc-aws-account}"

    environment: 
        SAMPLE_PARAM: '${opt:dxc-aws-account,self:provider.custom.dxc-aws-account}'

    environment: 
        SAMPLE_PARAM: {Fn::Join : ['', [${opt:dxc-aws-account,self:provider.custom.dxc-aws-account}]]}

**Comment by mzvrzg** [comment]
this is the combination that seem to work for me...

    environment: 
        SAMPLE_PARAM: {Fn::Join : ['', ["${opt:dxc-aws-account,self:provider.custom.dxc-aws-account}"]]}

**Comment by Gerst20051** [comment]
This also happens during `sls package` not just `sls deploy`.

**Comment by horike37** [comment]
@HyperBrain @dschep 
>Is this enough, or do we have to cover cases where an env var is set to an object too?
>Don't forget null, true, false, and any other non-number & non-string field types.

Thank you for the advice. Yes, we should cover those cases with checking the behavior of previous versions.

@mzvrzg

Thank you for testing and sharing the result 👍

**Comment by malcyL** [comment]
I've had to downgrade to serverless 1.27.3 due to this too.

We use environment variables as optional overrides so quite often had them blank.

**Comment by timgivois** [comment]
I'm having this issue too

**Comment by jamesdixon** [comment]
Even when using a string, this can cause issues with libraries that are expecting a number or some other data type.

**Comment by mr-beerkiss** [comment]
@jamesdixon that doesn't sound right to me.  These values should be read from `process.env` which always returns a string from what I can tell.  Thus I would expect those libraries to coerce the string values into the required type.   

However, I still think having a breaking change in 1.28 is not ideal!

**Comment by jamesdixon** [comment]
@mr-beerkiss you could be right. however, if it's left up to the library, we can't assume. either way, i agree...let's go back to the way it was!

**Comment by timgivois** [comment]
@mr-beerkiss the breaking change is that configuration has to be rewritten (even though all env vars are passed as strings, we need to add `"`) I believe it should be a warning not an error. I'm with @jamesdixon, we should change it.

**Comment by mr-beerkiss** [comment]
@timgivois I 100% agree the breaking change is in Serverless, and I would even go so far as to say it shouldn't even be a warning and should quietly coerce all primitive types to a string.

**Comment by malcyL** [comment]
In 1.27.3 it was possible to refer to environment variables in the serverless.yml file which were not set to any value. 

This allowed for environment variables to be used to override default settings in our CI and CD pipelines. Specifically, this was done in the environment section of the lambda configuration:
```yml
    lambda:
       ...
        environment:
            OVERRIDE_ENV_VAR: ${env:OVERRIDE_ENV_VAR}
```

If the override_env_var was not set, then this was not set on the lambda. This is really useful in complex environments. Losing this feature is going to leave us pinned to 1.27.3

Is it necessary to enforce a value?

I can see that there are other use cases where it might be useful to enforce a value, but this does seem to me to be an example where not doing so is useful. It's not an uncommon pattern to use environment varibales in this way and to have code which checks for the existance or none existance of an env var.

**Comment by eahefnawy** [comment]
Hey all, we just released v1.29.2 patch that includes a fix for this. Thanks to everyone for reporting, and special thanks @horike37 for the fix! 😊

**Comment by juvaly** [comment]
I'm getting this with v1.29.2.
It only happens on package or deploy, but works great when debugging with offline.

serverless.yml:

`environment: ${file(config/env.yml):${self:provider.stage,'local'}}`
...
`arn: ${self:provider.environment.events.crm.my-event}`

env.yml:

```
default_env: &default_env
   events: ${file(config/event-names-${self:provider.stage}.yml):events}

local:
  <<: *default_env
  aws:
    sns:
      endpoint: "http://127.0.0.1:4002"
      region: "us-east-1"

dev:
  <<: *default_env
  
prod:
  <<: *default_env
```

event-names-local.yml:

```events:
  crm:
    my_event: "arn:aws:sns:us-east-1:8xxxxxxxxx...."
```

Error message when trying to deploy:

> Environment variable events must contain string

**Comment by ZhangVic** [comment]
LGTM
I met the situation that, I used an boolean variable and got such error.
After I change true to 'true' , it works for me

**Comment by ptrhck** [comment]
I would like to point to [this ](https://stackoverflow.com/questions/52640684/how-to-configure-serverless-yml-to-read-python-boolean-values-correctly/53520349#53520349) issue on stackoverflow as I am having the same one. How can this be resolved in serverless.yml?

**Comment by jvguillen** [comment]
This makes importing variables from files impossible... seems like a pretty big issue to me.

**Comment by dschep** [comment]
@ptrhck I'm not sure what that SO post is really pointing out? This isn't an issue with serverless. Environment variables are strings. always.

@jvguillen, care to share what problem you're actually having? Importing variables from files works just fine afaict:
```
[:sls-5094] 1 $ cat > serverless.yml
service: test
provider:
  name: aws
  environment: ${file(${self:provider.stage}.yml):env}
[:sls-5094] $ cat > dev.yml
env:
  FOO: bar
  BAR: bar
[:sls-5094] $ sls print
service: test
provider:
  name: aws
  environment:
    FOO: foo
    BAR: bar
```
