### ISSUE TITLE
Contributing Guide minor issues

### ISSUE THREAD

**Issue by ashack293** [serverless/serverless#51]
I hate to put two issues in one... but here we go:

1. Some text to clarify the relationship between installation guide and this guide would be really helpful. I had both open at once, but a definitive statement on the matter would be great.

2. Under **Step 3: Commit**, users are advised to make global git config commands. These configs should be local to this repository only, as contributors may also use their workstation for other organizations.

**Comment by ac360** [comment]
:+1:  Will fix this shortly.

**Comment by ashack293** [comment]
Also I think the Contributing Guide is now out of date with the new 1.0 roadmap.

**Comment by ac360** [comment]
Good point.  I'll get on it.
