### ISSUE TITLE
Function boilerplate json should include requestModels property

### ISSUE THREAD

**Issue by justonian** [serverless/serverless#513]
The standard boilerplate text created by s-function.json does not include the requestModels property, though it does include the responseModels property. This boilerplate text should be expanded to include requestModels for clarity of functionality.

**Comment by cdichiara** [comment]
I definitely appreciate this request ... I've been searching for hours on the proper syntax for adding models to s-function.json, and if it wasn't for this request I'd probably still be searching.

Based on these resources:
http://docs.aws.amazon.com/apigateway/api-reference/resource/method/
http://docs.aws.amazon.com/apigateway/api-reference/resource/model/

I should have something like this in my s-function.json?
```
{
  "responseModels": {
    "application/json": "myModel"
  },
  "models": [
    "myModel": {
      "name": "MyModel",
      "description": "This is my model",
      "contentType": "application/json",
      "schema": "{   \
        "$schema" : "http://json-schema.org/draft-04/schema#", \
        // etc etc
      }"
    },
    "theirModel": {
      // etc etc
    }
  ],
```

So, two questions:

1) Is this correct? If not, does anyone have an example of a working model usage?
2) Will serverless take care of the "id" field for me?

Thanks in advance!

**Comment by atzbert** [comment]
Did you find a solution to this? Does it even work yet?

**Comment by cdichiara** [comment]
Oh, I think there might not be an implementation of loading models into the API Gateway yet ... so I've just been loading them manually and referring to them in requestModels and responseModels. I looked in the code base, didn't find a call to this: http://docs.aws.amazon.com/cli/latest/reference/apigateway/create-model.html

I could be wrong, though ... I think the workaround now is to load them manually and refer to them in ```requestModels[]``` and ```responseModels[]``` it's been working for me ...

**Comment by cdichiara** [comment]
Here's a solution @atzbert, thanks to @HyperBrain: #856

**Comment by atzbert** [comment]
Yay, thanks for letting me know! Looks promising!

**Comment by HyperBrain** [comment]
As the `s-function.json` boilerplate only makes sense with a working model functionality in Serverless core. I'll put the link to my models plugin here. The plugin solves exactly this problem and supports `requestModels` and `responseModels`. So this information can be part of this discussion.
As a general solution the plugin could be integrated in Serverless core.
https://github.com/HyperBrain/serverless-models-plugin
