### ISSUE TITLE
deploy fails with error "socket hang up" when node is 10.7.0

### ISSUE THREAD

**Issue by constb** [serverless/serverless#5138]
Hi. I'm using serverless + serverless-webpack to deploy to aws lambda.

Here's what happens when node=10.7.0

```
Serverless: Bundling with Webpack...
   141 modules
Serverless: WARNING: Could not determine version of module aws-lambda
Serverless: Excluding external modules: aws-sdk@^2.270.1, aws-lambda
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: …
Serverless: WARNING: Could not determine version of module aws-lambda
Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Here's how it goes with node=10.6.0

```
Serverless: Bundling with Webpack...
   141 modules
Serverless: WARNING: Could not determine version of module aws-lambda
Serverless: Excluding external modules: aws-sdk@^2.270.1, aws-lambda
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: …
Serverless: WARNING: Could not determine version of module aws-lambda
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (15.7 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................................................................................
Serverless: Stack update finished...
Service Information
…
Serverless: Removing old service artifacts from S3…
```

This might be related to https://github.com/nodejs/node/commit/949e8851484c016c07f6cc9e5889f0f2e56baf2a

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: MacOS High Sierra

**Comment by jbonachera** [comment]
Just ran into the same problem. It seems that serverless fails to establish an https connection to tracking.serverlessteam.com (saw that using `strace`).

If downgrading nodejs is not possible, disabling tracking worked for me (by setting "trackingDisabled" to true in ~/.serverlessrc).

**Comment by mnapoli** [comment]
@jbonachera thank you that works!

**Comment by aldarund** [comment]
should be same as https://github.com/serverless/serverless/issues/5133 which was fixed

**Comment by rodel-talampas** [comment]
@jbonachera thank you that saved my day!!!

**Comment by skylarmb** [comment]
I was on Node 10.11 and Serverless v1.28 and this was happening. I upgraded to Serverless v1.32.0 and everything is working.

**Comment by rj1061** [comment]
Disabling tracking in the `~/.serverlessrc` file did the trick for me

**Comment by abhi1851** [comment]
I disabled the tracking in by using `nano ~/.serverlessrc` and it worked for me
