### ISSUE TITLE
Does the responseTemplates supported?

### ISSUE THREAD

**Issue by neaghfoz** [serverless/serverless#514]
I'm using serverless V0.1.5 and define some error template in ```s-project.json``` like that:

```
  "apiResponseTemplate": {
    "application/json": {
      "code": "$input.path('$').errorMessage.code",
      "message": "$input.path('$').errorMessage.message",
      "status": "$input.path('$').errorMessage.status"
    }
  }
```

Then I use it in the ```s-function.json```:

```
      "responses": {
        ".*\"UnprocessableEntity\".*": {
          "statusCode": "422",
          "responseParameters": {
          },
          "responseTemplates": "$${apiResponseTemplate}"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
```
After run dash deploy,  it say: ```Expected params.responseTemplates['application/json'] to be a string```

I know the responseTemplates can be a one-line json string, but the requestTemplates can be defined by ```"requestTemplates": "$${apiRequestTemplate}"```, why the responseTemplates properties can't do that?

**Comment by jordanmack** [comment]
Try moving the `apiResponseTemplate` declaration from `s-project.json` to a new file named `s-templates.json`. Place this new file in the same folder as `s-project.json`.

**Comment by markusklems** [comment]
Hi, I am running into a similar error on serverless v0.4.2.

Given the following code:

// component/subfolder/function/s-templates.json
{
...
  "apiResponseTaskReadTemplate": {
    "application/json": {
      "task" : {
        "id" : "$input.path('$').Item.id",
        "content" : "$input.path('$').Item.content"
      }
    }
  },
...
}

// component/subfolder/function/s-function.json
...
      "requestTemplates": "$${apiRequestTaskReadTemplate}",
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": "$${apiResponseTaskReadTemplate}"
        }
      }
    },
...

When I try ro execute "serverless endpoint deploy ...", the following deployment error is shown:

Expected params.responseTemplates['application/json'] to be a string

Looks like "responseTemplates" won't accept json, unlike "requestTemplates" (which works fine).
