### ISSUE TITLE
AWS rate limits are hit when other processes are also talking to AWS

### ISSUE THREAD

**Issue by e-e-e** [serverless/serverless#5142]
# This is a Bug Report

## Description

AWS rate limits are hit when other processes are also talking to AWS.

For bug reports:
* What went wrong?
We occasionally hit this error on when using CI to deploy our serverless stack. It happens because we also have parallel processes running which also use the aws sdk.

* What did you expect should have happened?
Deployment should automatically handle pulling back if AWS sends throttle errors.

* What was the config you used?

There is nothing special in our config that would cause this issue.

* What stacktrace or error message from your provider did you see?

```
 Serverless Error ---------------------------------------
 
  An error occurred: OurLambdaFunction - Your request has been throttled by EC2, please make sure you have enough API rate limit. EC2 Error Code: RequestLimitExceeded. EC2 Error Message: Request limit exceeded. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: b8b4ac4c-8afc-11e8-8e5b-c354762b39bc).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.28.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: CI
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by e-e-e** [comment]
It looks like its an issue with AWS cloud formation - https://forums.aws.amazon.com/thread.jspa?threadID=240384

**Comment by pmuens** [comment]
Thanks for opening @e-e-e and for taking the time to provide a fix 👍

I'll close this for now since there's little we can do and it seems to be related to CloudFormation.
