### ISSUE TITLE
Deploy and maintain environment variables

### ISSUE THREAD

**Issue by ronkorving** [serverless/serverless#5152]
# This is a Feature Proposal

## Description

On some lambda deployments, environment variables are managed through the AWS dashboard. We don't want to add secrets to our serverless files in our project repositories after all. Because of this, I find that there's a need to add a step to deployment: first download the environment variables from the existing deployment (`aws lambda get-function --function-name $LAMBDA` returns this data in an object on `.Configuration.Environment.Variables`), include it in my serverless configuration that I use to deploy, and only then actually deploy. If this is a scenario that a lot of people hit, maybe we can build this into `serverless` as a deployment option?

Eg:

```sh
serverless deploy --maintain-environment
```

This could first download the environment variables and include them in the cloudformation file (except the ones overwritten by serverless configuration) so that they are not wiped out during deployment.

Would love to hear people's thoughts on this. Thanks.

**Comment by crash7** [comment]
Hi! I think you should take a look to SSM variables, we use that to manage secrets and we just reference the variables in the yml file.
