### ISSUE TITLE
Call to `serverless logs -f hello -t` never returns

### ISSUE THREAD

**Issue by johnlim** [serverless/serverless#5157]
# This is a Bug Report

## Description
Following the instructions at https://serverless.com/framework/docs/providers/aws/guide/quick-start/,
running `serverless logs -f hello -t` on the console never returns. 

## Additional Data

* ***Serverless Framework Version you're using***:
1.28
* ***Operating System***:
masOS
* ***Stack Trace***:
none
* ***Provider Error messages***:
no error messages

**Comment by jleskovar-tyro** [comment]
The "-t" flag will tail log output indefinitely, resulting in the command never returning. Although I do wonder if the "Invoke the Function" step should be after "Fetch the Function Logs" step, as the logs won't necessarily be returned for invocations that have happened in the past..

**Comment by pmuens** [comment]
Thanks for opening @johnlim 👍

As @jleskovar-tyro pointed out it's a feature since we `tail` the logs.

**Comment by johnlim** [comment]
@pmuens Thanks. Re-reading the document, I realized I misunderstood the documentation. I was under the impression that it would "fetch" the logs (once) and not "stream" the logs. Thanks for the clarification.
