### ISSUE TITLE
AWS provider error: Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by alexjurkiewicz** [serverless/serverless#5168]
Note: the above error is from node10. Under node6 or 8, the error shown is "the header content contains invalid characters".

**Summary**
When I run `AWS_PROFILE=testaccount yarn run sls deploy` from terminal, everything works. When I run `yarn run sls deploy` from a Python script with the AWS_PROFILE env var set, I get the above error. 

`SLS_DEBUG` Snippet:

```
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Recoverable error occurred (Invalid character in header content ["Authorization"]), sleeping for 5 seconds. Try 1 of 4
```

Stack trace:

```
ServerlessError: ServerlessError: Invalid character in header content ["Authorization"]
    at AwsDeploy.BbPromise.bind.then.catch (/project/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:90:15)
From previous event:
    at AwsDeploy.createStack (/project/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:81:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/project/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/project/node_modules/serverless/lib/classes/PluginManager.js:390:55)
```

I can work around this by adding `profile: ${env:AWS_PROFILE}` to the provider section of `serverless.yml`. Then invocation directly or via my script works.

I have no idea what is different about the invocation from my Python script. Everything should be the same, but clearly something is not.

Other posts I've found on the internet suggest this is related to bad AWS credentials, or the Authorization header having bad data in it (a newline or some other invalid character). Unfortunately I can't figure out how to modify serverless to `console.log` the header to check this.

I'm opening this ticket to help others who run into this problem and ask for help dumping the `Authorization` header to diagnose further.

**Comment by alexjurkiewicz** [comment]
I found the problem was a trailing newline in my region specification (eg `us-east-1\n` instead of `us-east-1`). I figured it out by adding `console.log(AWS.config);` towards the end of AwsProvider's constructor `lib/plugins/aws/provider/awsProvider.js`.

**Comment by allen-n** [comment]
I had the same issue, ended up being a newline in my AWS access ID in my production environment variable

**Comment by developersenthil** [comment]
What is the solution for this? I am also having the same issue.

**Comment by jarenella** [comment]
I had the same issue but for me the invalid character was a / in front of my access key ID. The solution is to run 'aws configure' and then you'll be prompted to re-enter your access key ID, secret access key, default region, and default output format. If one of those is the issue, which it likely is, re-entering them should fix it. You can also try to check which one has the invalid character by doing what alexjurkiewicz said and running console.log(AWS.config);
