### ISSUE TITLE
Support for other API Gateway endpoint types

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#517]
Besides functions, AWS API Gateway supports three other endpoint types:

* Mock Integration: For mocking a Lambda function, HTTP proxy call or AWS service proxy. Can also be used to return a static response without the need for having a function (e.g. this is how APIG does CORS by default).

* HTTP Proxy: Proxy the request to another (non-Serverless) HTTP server. It can be powerful to mix your Serverless function endpoints with existing API's on the same hostname using this endpoint type.

* AWS Service Proxy: Easy performing of simple AWS service API calls without having to use Lambda.

To support these types, we could add support for `s-endpoint.json` files, which can live in the module dirs next to `s-module.json` and `s-templates.json`.

**Comment by JamieCressey** [comment]
+1 we have a number of HTTP proxy endpoints (CloudSearch etc) which are currently being served using another API gateway, being able to merge those into our Serverless API Gateway would be much cleaner

**Comment by orthodoc** [comment]
:+1: 
It was possible to create the endpoint for the HTTP proxy endpoint, except that SLS threw an error about not finding the integration method. On AWS side, the endpoint did get created but the URL was missing. The moment the URL was provided, the integration was complete. Filling the key:value pair in `s-function.json` didn't make any difference.

**Comment by dijitalmunky** [comment]
+1 for this also.  This also needs to be able to change the proxy url by stage (we do it through stage variables ATM), as the endpoints for us change hosts between stages.

**Comment by dijitalmunky** [comment]
Another solution for Proxies is in #950

**Comment by cdichiara** [comment]
+1 I'm planning to do a service proxy, wish I could integrate it with our serverless structure...

**Comment by nicka** [comment]
What's the latest news on?

> Mock Integration: For mocking a Lambda function, HTTP proxy call or AWS service proxy. Can also be used to return a static response without the need for having a function (e.g. this is how APIG does CORS by default).

I need to add support for an `OPTIONS` and I don't want it to trigger my Lambda function. Not sure how to proceed.

**Comment by joostfarla** [comment]
@nicka MOCK endpoints are supported today. Just add a `type` property:

```
"endpoints": [
    {
      "path": "foo",
      "method": "OPTIONS",
      "type": "MOCK",
      ...
```

**Comment by nicka** [comment]
@joostfarla Woehoe! Thanks for the update.

**Comment by franz-josef-kaiser** [comment]
@joostfarla Is there some documentation for that?

**Comment by joostfarla** [comment]
@franz-josef-kaiser Unfortunately not. It should be somewhere in this chapter:

https://serverless.readme.io/docs/function-configuration#section-endpoint-configurations

**Comment by franz-josef-kaiser** [comment]
@joostfarla Could you please add a paragraph about this there?

**Comment by dijitalmunky** [comment]
Just submitted a suggestion on the docs site for that @franz-josef-kaiser, I expect it'll get approved in the next day or two. :)

**Comment by flomotlik** [comment]
We're currently working on the next version of serverless that will allow to create resources through Cloudformation directly, including different types for API Gateway. I will close this issue for now as we're targeting it in a future release. Definitely heard your feedback about this.

**Comment by Si1kIfY** [comment]
Looks like AWS Service Proxy still isn't supported buy the current buildm can only see "AWS", "MOCK" and "HTTP" as supported types (and I can't seem to get HTTP working either, consistently says invalid http endpoint encoding for the uri).

Is it worth re-opening this task or creating a new one?

**Comment by flomotlik** [comment]
@Si1kIfY we're currently working on this in the V1.0 branch. In there you're able to define your own resources that will be deployed together with the rest of your stack to cloudformation. This branch is still experimental and in alpha phase but we'd definitely like to get feedback on it.

We're going to move this over to the master over the next weeks once we release 0.5.6 from master and share more information on this.

**Comment by Si1kIfY** [comment]
I'll check it out thanks @flomotlik

**Comment by aburnett** [comment]
Where does this stand as of Serverless 1.16.0? It does not appear that non-serverless managed HTTP endpoints are supported today.

**Comment by pmuens** [comment]
Hey @aburnett. Thanks for getting back.

We've recently added different API Gateway endpoint types: https://serverless.com/framework/docs/providers/aws/events/apigateway/
