### ISSUE TITLE
Windows deploy --package does not handle slashes in path (or in package.path of serverless.yml)

### ISSUE THREAD

**Issue by dbellandi** [serverless/serverless#5172]
# This is a Bug Report

## Description

On a windows machine, `deploy --package sub1/sub2` or package.path in serverless.yml does not handle forward slashes properly. The command `package --package sub1/sub2` works as expected.

This is a problem when the same project is being used on both Windows and non-Windows boxes.

### Reproducing

From a Windows command shell (SLS_DEBUG=*):
* Execute:
```
git clone https://github.com/serverless/examples test-serverless-examples
cd test-serverless-examples\aws-node-simple-http-endpoint
serverless package --package pkg/sub
dir /b pkg\sub\serverless-state.json
```
* Output:
```
cloudformation-template-create-stack.json
cloudformation-template-update-stack.json
serverless-simple-http-endpoint.zip
serverless-state.json
```

#### (Package produced successfully)

* Execute:
```
serverless deploy --package pkg/sub
```
* Output:
```
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:moveArtifactsToTemp

  Serverless Error ---------------------------------------

  No serverless-state.json file found in the package path you provided.

  Stack Trace --------------------------------------------

ServerlessError: No serverless-state.json file found in the package path you provided.
    at AwsDeploy.extendedValidate (C:\Users\Dan\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\extendedValidate.js:17:13)
``` 

### Problem Location

The problem can be traced to the code here: https://github.com/serverless/serverless/blob/master/lib/utils/fs/copyDirContentsSync.js#L11

```javascript
  const relativeFilePath = fullFilePath.replace(srcDir, '');
  ```

What happens is `fullFilePath` equals `pkg\sub\serverless-state.json` but `srcDir` equals `pkg/sub/serverless-state.json` so that `fullFilePath.replace()` does not actually remove `srcDir` from the string.

### Proposed Fix

I suggest that the above code replace backslashes with forward slashes in `srcDir` before the above line. (I am currently handling it with a custom plugin.)

I would be happy to create a PR for either the above approach or another suggested idea.

## Additional Data

```
     OS:                     win32
     Node Version:           8.9.4
     Serverless Version:     1.29.0
```

**Comment by janjanarnaldo** [comment]
Hi @dbellandi how did you go with this issue, may I have an idea of the custom plugin you used to make it work?

**Comment by dbellandi** [comment]
@janjanarnaldo I did this in a custom plugin:

In the constructor:

```js
this.hooks = {
      'before:aws:common:validate:validate': this.beforeAwsDeploy.bind(this)
}
```

Code:

```js
  beforeAwsDeploy() {

    // change package path slashes to backslashes on windows -- https://github.com/serverless/serverless/issues/5172
    if (process.platform === 'win32') {
      if (this.serverless.service.package && this.serverless.service.package.path) this.serverless.service.package.path=this.serverless.service.package.path.replace(/\//g,'\\')
      if (this.options.package) this.options.package=this.options.package.replace(/\//g,'\\')
    }

```

**Comment by dschep** [comment]
Thanks for sharing the workaround @dbellandi! And I would absolutely love a PR fixing this :)
