### ISSUE TITLE
Fn::ImportValue in cfnRole does not work

### ISSUE THREAD

**Issue by rupertbg** [serverless/serverless#5173]
# This is a Bug Report

## Description
If you use `Fn::ImportValue` in `provider.cfnRole` then you get this error:
```
  Serverless Error ---------------------------------------

  Expected params.RoleARN to be a string
```
The value I'm importing is a string of the ARN of the IAM Role I want to use.
## Additional Data
```
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.7.0
     Serverless Version:     1.29.0
```

**Comment by et304383** [comment]
cfnRole is passed to the create stack API call.  It's not part of CloudFormation and thus you cannot use CloudFormation references to resolve its value.

**Comment by pmuens** [comment]
Thanks for opening @rupertbg and thanks for chiming in @et304383 👍

Yes, you can only use CloudFormation references to resolve values. I'll close this one since it's a limitation due to CloudFormation...

**Comment by rupertbg** [comment]
@pmuens @et304383 - I'm really confused now, I'm reading this as "You can't use Fn::ImportValue because it's not part of CloudFormation" and "Yes, you can only use CloudFormation references to resolve values".... Which is too contradictory statements. @et304383 can you clarify for me what you mean when you say "It's"? Do you mean cfnRole is not part of CF or ImportValue is not?
