### ISSUE TITLE
Deployments fail with `{"errorMessage":"invalid_request"}` error at @serverless/platform-sdk/src/login/refreshToken.js

### ISSUE THREAD

**Issue by sugarandmagic** [serverless/serverless#5177]
# This is a Bug Report

## Description

I've had no issues with my credentials up until now but for the last couple of days I'm unable to deploy any of my Lambda services to live.

When I run `serverless deploy` I see: 

```Serverless: Load command offline
Serverless: Load command offline:start

  Error --------------------------------------------------

  {"errorMessage":"invalid_request"}

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: {"errorMessage":"invalid_request"}
    at _callee$ (/Users/carriebeesley/.nvm/versions/node/v8.11.3/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/login/refreshToken.js:18:11)
    at tryCatch (/Users/carriebeesley/.nvm/versions/node/v8.11.3/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/carriebeesley/.nvm/versions/node/v8.11.3/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/carriebeesley/.nvm/versions/node/v8.11.3/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:117:21)
``` 

My serverless.yml: 

```service: my-service
custom:
    secrets: '${file(secrets.json)}'
provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    environment:
        SECRET_KEY: '${self:custom.secrets.secretKey}'
functions:
    createCharge:
        handler: handler.createCharge
        events:
            - {http: {path: charges, method: post, cors: true}}
plugins:
    - serverless-offline
```
This is working fine offline. 

I regenerated a new IAM keypair but it made no difference

## Additional Data

* ***Serverless Framework Version you're using***: 1.29.2
* ***Operating System***: Mac OS 10.13.4 (17E199)
* ***Node version v8.11.3

![image](https://user-images.githubusercontent.com/38294284/43445055-43012444-949d-11e8-8b39-5fe2041204f8.png)

This is also happening wen I try to redeploy my other services that are already live

**Comment by sugarandmagic** [comment]
I was able to work around this by running `serverless login` and reauthenticating in my browser. Still - this looks like a bug to me

**Comment by eahefnawy** [comment]
@sugarandmagic this is related to our own credentials, not AWS. We've changed the infra behind how login happens, so your old login token no longer works. After relogin things should be ok.

Now that you've logged in, please let us know if you face this issue again.

**Comment by sugarandmagic** [comment]
Thanks for getting back to me and letting me know @eahefnawy - I will. Had me scratching my head for a few hours but it's been fine since I got a new token

**Comment by neilbts** [comment]
@eahefnawy FYI I just received this error while running v1.29.2 and attempting to deploy to AWS. It was previously working fine for a couple of months and I have never logged into the serverless platform (we've always deployed to AWS). I also tried upgrading to 1.31 but received the same error. I had to downgrade to v1.28 for it to work.

**Comment by infinity1975** [comment]
I can't login due to wrong password, and I can't reset my password cause I don't get any reset password email, therefor I'm stuck unable to deploy, sigh!!!!

**Comment by jsphkhan** [comment]
> I was able to work around this by running `serverless login` and reauthenticating in my browser. Still - this looks like a bug to me

You saved my day. Thanks
