### ISSUE TITLE
"npm i serverless" fails due @serverless/platform-sdk@^0.2.0 missing

### ISSUE THREAD

**Issue by jussikinnula** [serverless/serverless#5179]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  `npm i serverless` fails to install
* What did you expect should have happened?
  `serverless` should have been installed normally
* What was the config you used?
  no config used
* What stacktrace or error message from your provider did you see?
  See below

Similar or dependent issues:
* Issue in @serverless/platform-sdk side https://github.com/serverless/platform-sdk/issues/9

## Additional Data

* ***Serverless Framework Version you're using***: latest
* ***Operating System***: macOS 10.13.6
* ***Stack Trace***: -
* ***Provider Error messages***: 
```
$ npm i serverless
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @serverless/platform-sdk@^0.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'serverless'
npm ERR! notarget
```

**Comment by saileshkotha** [comment]
I'm having the same issue, did you resolve it?

**Comment by ohimors** [comment]
I'm having the same issue:
```
npm ERR! code E404
npm ERR! 404 Not Found: @serverless/platform-sdk@^0.2.0
```

**Comment by juank11memphis** [comment]
Having the same issue here! Any fix for this soon?

**Comment by pmuens** [comment]
Closing this for now since it's an issue with `npm`. Please refer to the solution posted above by @alexdebrie (--> https://github.com/serverless/serverless/issues/5179#issuecomment-409784052) to fix this issue.
