### ISSUE TITLE
ApiGateway Deployment missing when function does not have events

### ISSUE THREAD

**Issue by manjirinamjoshi** [serverless/serverless#5181]
Hello,

AWS::ApiGateway::Deployment is not created in the compiled template if none of lambda functions have a "events" trigger.

I have a usecase where I need define "cacheKeyParameters" for my endpoints. For the cache key params, I had to define the APIGateway resources and methods and specify the "uri" as the lambda functions.

So, all my functions have no triggers (no events).

For this scenario I get an error -

TypeError: Cannot read property 'Properties' of undefined
    at BindDeploymentId.fixUpDeploymentStage (/et/repo/serverless/channel/node_modules/serverless-plugin-bind-deployment-id/lib/index.js:75:32)
    at BindDeploymentId.bindDeploymentId (/et/repo/serverless/channel/node_modules/serverless-plugin-bind-deployment-id/lib/index.js:51:35)

This is because the compiled template is missing the "ApiGateway Deployment"

This is my serverless.yml - 
https://gist.github.com/manjirinamjoshi/ca3900cd814d654e955af9ed069a0b35

I have tried adding a "events" trigger to one function, and then it works. But, then that doesnt work for me because that 1 function has to have a separate resource base path.

Thank you

Sincerely,
Manjiri

**Comment by pmuens** [comment]
Hey @manjirinamjoshi thanks for asking 👍

That's actually the expected behavior. You can workaround this by defining the required resources in the `resources.Resources` section.
