### ISSUE TITLE
Fn docs contain links that 404

### ISSUE THREAD

**Issue by pinkerton** [serverless/serverless#5193]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Visiting the Services and Functions links on https://serverless.com/framework/docs/providers/fn/ throw 404s.
* What did you expect should have happened?
Should have been directed to pages containing documentation.
* What was the config you used?
Visited the live serverless.com using the latest Chrome.
* What stacktrace or error message from your provider did you see?

<img width="545" alt="screen shot 2018-08-06 at 3 18 13 pm" src="https://user-images.githubusercontent.com/778344/43738948-fb9430e4-998b-11e8-9096-e10fbb84461c.png">

Similar or dependent issues:
* N/A

## Additional Data

* ***Serverless Framework Version you're using***: N/A
* ***Operating System***: N/A
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Thanks for opening @pinkerton 👍

Looks like this is related to #5320 where we gather that kind of information. Closing this for now...
