### ISSUE TITLE
Code storage limit exceeded

### ISSUE THREAD

**Issue by ashish8833** [serverless/serverless#5194]
# Code storage limit exceeded

I am try to serverless application deploy to **AWS**.
I have error *Code storage limit exceeded* deploy to *HelloLambdaFunction*.

![screen shot 2018-08-07 at 2 27 58 pm](https://user-images.githubusercontent.com/16094870/43765674-22b93d46-9a4e-11e8-86b0-c5733e3cb54f.png)

Code storage limit exceeded error fire when serverless application zip file more than **50 MB**, but for my case it's only **409 B**. 

Limitation of lambda function [Link](https://docs.aws.amazon.com/lambda/latest/dg/limits.html)

**Comment by dougmoscrop** [comment]
The storage limit also applies to functions overall. If you go to your Lambda dashboard, you will see something like "Code storage | 230.8 MB (0% of 75.0 GB)"

Serverless' message about removing older function versions is a bit misleading, it actually doesn't clean up this stuff.

Try using: https://www.npmjs.com/package/serverless-prune-plugin

but you have to use it on all the different services you've deployed

**Comment by pmuens** [comment]
Thanks for opening @ashish8833 and thanks for providing a solution @dougmoscrop 👍

I'll close this for now since the proposed solution should fix the problem.

**Comment by mubi-janjua** [comment]
An error occurred: 3NestedStack - Embedded stack arn:aws:cloudformation:us-east-1:999547879032:stack/chex-backend-development-3NestedStack-BDRPNBU7YD22/73fa0520-8fe5-11eb-a0bb-0ece9c9311f7 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [UpdateUserStatusLambdaFunction]. .


also my code storage limit is exceeded.
