### ISSUE TITLE
Is Knative in your roadmap?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [serverless/serverless#5212]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

I know that as of today you support kubeless which is also basically archiving the same goal. Although I would like to ask if you are planning to support Knative in Serverless.

Reason is that is currently baked by Google, Pivotal, Red Hat and many other organizations which are trying to converge on the serverless approach doing it in one way on Kubernetes.

I would really like to see this adopted as it would vastly open the doors to an easy serverless experience ( I love Serverless CLI! ) and smooth migration, doesn't matter if you use Google Cloud, AWS EKS, Pivotal PKS and so on.

Similar or dependent issues:
* N/A

## Resources
* https://cloud.google.com/knative/

Thank you in advance for any reply given.

Best regards.

**Comment by debianmaster** [comment]
interested to know if there a plan

**Comment by gilluan** [comment]
I would like to contribute.

**Comment by billfine** [comment]
Here at Serverless we've been watching the Knative project since its inception and have had some discussions with the Google team re how to best work together.  Has anyone here implemented Knative?  Can you share your experience?  What is your use case for adopting Knative and how mature have you found the project to be?

**Comment by marziman** [comment]
@billfine there is ONE big advantege with the combination of ServerlessFramework and Knative:
Having the freedom of choice to use any Serverless Cloud Provider or use your on-prem Serverless infrastructure. So I really think you should tackle this. I was confused to see that you mention K8s on your homepage, but you actually refer to Kubeless? The native on-prem Serverless will most probalby go to the direction Knative. So it would be helpfull to have support by the Serverless Framework.
We are planning to use Serverless Framework with Knative and been suprised that it isnt supported yet.

BR Mehmet

**Comment by dvins** [comment]
@billfine This also alleviates a number of issues we run into with spotty/bugg coverage in plug-ins like `serverless-offline`. At least with Knative approach we can run local on minikube and theoretically avoid the minefield we jump around today between different degrees of coverage and support across a myriad of plugs-ins needed to truly enable a developer to work the full stack locally.

**Comment by dvins** [comment]
Is there any update or guidance on this?

**Comment by dirkmoors** [comment]
+1

**Comment by theluk** [comment]
+2

**Comment by intellix** [comment]
How about Google Cloud Run, as opposed to GKE/Anthos?

**Comment by billfine** [comment]
Knative provider plugin beta is [here](https://github.com/serverless/serverless-knative). And, an example is [here](https://github.com/pmuens/serverless-knative-example).
