### ISSUE TITLE
aws-go uses dep

### ISSUE THREAD

**Issue by bwright1558** [serverless/serverless#5220]
# This is a Bug Report

## Description
After creating an aws-go project, running `make build` fails due to missing Gopkg.toml

* What went wrong?
`make build` failed with error.

* What did you expect should have happened?
`make build` to succeed without dep dependency.

* What was the config you used?
The default project created using `serverless -t aws-go -p helloworld`

* What stacktrace or error message from your provider did you see?
No error from provider. Error came from `make build`. The error was

      dep ensure -v
      could not find project Gopkg.toml, use dep init to initiate a manifest
      make: *** [build] Error 1

Similar or dependent issues:
* #5144 
* #5145 

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.0
* ***Operating System***: macOS High Sierra Version 10.13.5

**Comment by sebito91** [comment]
Thank you very much for bringing this up! This was a poor copy/paste on my part and you've rightfully caught it.

If you remove those lines from the `Makefile` does the rest of the example hold up for you?

**Comment by bwright1558** [comment]
Removing `dep ensure -v` from the Makefile fixes my problem. May I also recommend changing `rm -rf ./bin ./vendor Gopkg.lock` to `rm -rf ./bin` since ./vendor and Gopkg.lock are only ever created by dep init?

**Comment by sebito91** [comment]
The fix attached to this Issue does just that, removes the extra components for the non-dep version.

Glad it’s working for you!
