### ISSUE TITLE
Consul provider/plugin

### ISSUE THREAD

**Issue by brahama** [serverless/serverless#5223]
# This is a  Feature Proposal

## Description

For feature proposals:
* Having Consul as the KV store, similar to wht it is with SSM.

**Comment by brahama** [comment]
Guys, FYI we did a plugin, and we are testing it now. It just gets the values from the KV path specified like SSM does. we added it to the plugins list repo.  
https://github.com/zephrax/serverless-consul-variables

**Comment by exoego** [comment]
I think this issue can be closed since the mentiond plugins is now listed on 
https://github.com/serverless/plugins
