### ISSUE TITLE
Can not use variable lookup in yaml file array - inline. 

### ISSUE THREAD

**Issue by brettswift** [serverless/serverless#5228]
# This is a Bug Report

## Description

This does not work in a template: 

'Fn::Equals': [ ${self:custom.cloudfront_enabled}, 'false' ]

but this does:

'Fn::GetAtt': [ CfnResourceName, DomainName ]

Currently I have to write it like this: 

```
    CloudfrontEnabled: 
      'Fn::Equals':
        - ${self:custom.cloudfront_enabled}
        - 'true'
```

This makes for awkward authoring and refactoring of templates as I can't easily put variables into places where there is inline code without uglifying it. 

Similar or dependent issues:
* don't think any yet. 

## Additional Data

* ***Serverless Framework Version you're using***:1.30.0
* ***Operating System***:OSX
* ***Stack Trace***:
* ***Provider Error messages***:
```
 missed comma between flow collection entries in ....
 'Fn::Equals': [ ${self:custom.cloudfront_enabled} ...
```

**Comment by michellemalaski-powerschool** [comment]
Also having this issue

`Engine:
            Type: Map
            Iterator:
              StartAt: MappedEngine
              States:
                MappedEngine:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [${cf:engine-lambda-${self:provider.stage}.oEngine}, Arn]
                  End: true
            Next: Done`

I receive this error: 

`missed comma between flow collection entries in "/sa-serverless/serverless.yml" at line 209, column 35:
                          Fn::GetAtt: [${cf:engine-lambda-${self:pr ...`

**Comment by hugomn** [comment]
Do we have any solutions for using variables in arrays inside serverless.yml?

**Comment by medikoo** [comment]
Closing, as that should be fixed with a new variables resolver
