### ISSUE TITLE
deploymentBucket does not work for s3 buckets in another account

### ISSUE THREAD

**Issue by knizami** [serverless/serverless#5238]
* What went wrong?
When specifying a bucket name for a bucket that was created in another account, even if the current credentials have full access to the bucket via bucket policies and IAM permissions, you get:

  Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: Access Denied

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.1
     Serverless Version:     1.24.1

* What did you expect should have happened?
s3 buckets in other accounts should work if the current credentials have the necessary permissions, is the current account assumed when user specifies a deploymentBucket name?

When using profile dev, which is an account that has full s3:* rights and the s3 bucket policy for infrastructure-203433-prod provides the account with full s3 rights, the error occurs.

When using profile prod, which is the account where the s3 bucket was created, the error doesn't occur.

* What was the config you used?
serverless.yml
=============
provider:
  name: aws
  region: ${file(config/config.yml):region}
  deploymentBucket: infrastructure-203433-prod
  profile: ${file(config/config.yml):profile}
functions:
  HelloWorld:
    name: '${file(config/config.yml):asset-id}-${file(config/config.yml):product-name}-Lambda-${file(config/config.yml):environment}'
    handler: hello_world_handler
    runtime: python2.7
    description: 'Hello World Example created by PipelineFactory'
    timeout: 300
    memorySize: 128
    package:
      exclude:
        - '**/*'
      include:
        - 'hello-world.py'

config.yml
===========
product-name: 'Serverless'
environment: 'Development'
environment-type: 'DEVELOPMENT'
region: 'us-east-1'
profile: dev

* What serverless version are you using?
1.24.1

**Comment by vdanniel** [comment]
What was the fix here. thanks

**Comment by AnthonyWC** [comment]
This sounds like a really terrible idea to allow a deployment bucket to be in another account.

**Comment by eexit** [comment]
Hi @knizami,

I'm facing the same issue. How did you fix this?

Thanks!

**Comment by Ariit0** [comment]
For those who have stubbled across this. It is in fact possible to have a deployment bucket in another account. You just need to make sure that the role in account B that is deploying the stack has permissions to access s3 account A (which has the deployment bucket) so check your bucket policies and iam role policies! 

If you're stumped completely ignore serverless and setup a scenario where you have a bucket in account A, and you got a role in account B. Assume role in account B, now following the principle of least privilege what permissions do I need at a minimum where i can 
1. search what buckets are in account A
2. access specific bucket in account A

From there you should be able to figure out the permissions required through trial and error based on how your AWS accounts are setup. The permission errors should give away what permissions you need (ofc there are cases where AWS doesn't give a helpful error message to my memory...)
