### ISSUE TITLE
Getting started / searchable AWSM and Plugin registry

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#524]
Hey guys,
I just started with the Serverless framework and I'm very excited about it.

I had a hard time finding any resources for Serverless so I started an awesome list to collect all the relevant stuff (https://github.com/justserverless/awesome-serverless).

Maybe it would be great if we could write a simple getting started guide for the absolute beginners which describes how to implement e.g. a Twitter clone or smth. like that.

Another great thing would be if we have a searchable registry (e.g. a static page hosted on GitHub with a simple client side search) where a user can search for available AWSM modules / Serverless Plugins.

What do you think?

**Comment by ac360** [comment]
@pmuens So glad to have you in the community.   You are such an awesome help!!!

Yes, we are lacking in examples, documentation, etc.  To make Serverless easier to adopt, we now allow Project files to be shared for others to install.  As long as they are published to npm you can install them.  `serverless project install serverless-starter`.  It would be great if we could get some more neat projects going.  We have a few coming out soon.

**Comment by pmuens** [comment]
@ac360 Thank you for the kind words and the pointer to the example project installation functionality!

I'll start a blog soon where I'll document my way with Serverless (this should help beginners as well).
Really excited about the technology. Looking forward to contribute additional stuff.

**Comment by eahefnawy** [comment]
@pmuens it's been awesome seeing all the progress you've been making in the past few months :) ... We're really happy to have you and your help is much appreciated 😊

**Comment by pmuens** [comment]
Hey @eahefnawy 
Thank you very much for the kind words. It's really great to be a part of this awesome and welcoming community!
