### ISSUE TITLE
Can not debug application using serverless frame work

### ISSUE THREAD

**Issue by saikumar-madana** [serverless/serverless#5273]
I have been trying to debug aws application which is created using the serverless framework. I don't find anywhere how to do so. I have tried something like 

`serverless invoke local --function helloworld --debug-port 5858`

But I can't debug this way. Please help me how to do so.

Thank you...

**Comment by khaledosman** [comment]
This is a caveat with building lambdas in general, you can't debug them similar to how you would use the --inspect flag in NodeJS afaik... sls invoke only calls the function with the given input.

What I usually do for local development is use the serverless offline plugin https://github.com/dherault/serverless-offline then test my function locally using Postman, that way I can have direct access to the stdout including console.logs and the error stack on my console.

to view the logs in the deployed lambda you can either access them from cloudwatch/x-ray or use the serverless logs command

I also found this trick if you're using vscode, but I haven't tried it out myself https://hackernoon.com/running-and-debugging-aws-lambda-functions-locally-with-the-serverless-framework-and-vs-code-a254e2011010

**Comment by dschep** [comment]
Have you tried the following? This is usually how I debug lambdas:
```
node --inspect $(which sls) invoke local --function helloworld
```

**Comment by dschep** [comment]
Also, AFAICT sls doesn't have a `--debug-port` option for invoke local. Where did you find that flag documented?
```
Plugin: Invoke
invoke local .................. Invoke function locally
    --function / -f (required) ......... Name of the function
    --path / -p ........................ Path to JSON or YAML file holding input data
    --data / -d ........................ input data
    --raw .............................. Flag to pass input data as a raw string
    --context / -c ..................... Context of the service
    --contextPath / -x ................. Path to JSON or YAML file holding context data
    --env / -e ......................... Override environment variables. e.g. --env VAR1=val1 --env VAR2=val2
```

**Comment by dschep** [comment]
Another option is to use the inspector module from nodejs. Just pop this where you want to connect a debugger. It'll block until you connect with the chrome debugger:
```javascript
require('inspector').open(9229, "localhost", true)
```

**Comment by dangerousdan** [comment]
@dschep `--debug-port` is a node flag, not sls, so this arg is used similarly to `--inspect` in your example above

We use serverless-offline, and have serverless isn't included locally, so we run
`node --inspect-brk --debug-port=9229 node_modules/serverless/bin/serverless offline`.

Or for VSCode users using launch.json:
```json
    {
      "name": "Lambda",
      "type": "node",
      "request": "launch",
      "runtimeArgs": ["--inspect-brk", "--debug-port=9229"],
      "program": "${workspaceFolder}/node_modules/serverless/bin/serverless",
      "args": ["offline"],
      "port": 9229,
      "console": "integratedTerminal"
}
```
