### ISSUE TITLE
Variable Lookup Conflict when importing cloudformation template into resources.

### ISSUE THREAD

**Issue by brettswift** [serverless/serverless#5279]
# This is a Bug Report

## Description

**Edit: This only happens with yaml templates that have `!Sub: ${var_name}`  lines in them.  In json it works as expected.** 

I have a template exported from troposphere, that I wanted to use in the resources block of a serverless app. 

My use case is to have a simpler way of deploying step functions and their lambda's,  but have them integrated into code pipeline. 

Roughly this is what I'm doing: 

1. `python codepipeline_template.py  > codepipeline.yaml`  (generate yaml or json template)
2. serverless brings that in: 

serverless.yaml
```
resources:
   Resources: ${file(codepipeline.yaml):Resources}
```

It would be nice if we could do this.  Having said that my workflow might be best to wrap both in a deploy script and deploy independently. 
Somehow I would have to export the state machine ARN and parse it, to pass it into the pipeline, but that's not a big deal. 

My thoughts were if these two worlds worked better together, maybe it would make them both more powerful.

Is this for some reason a pattern that we don't want to support with serverless? 

Similar or dependent issues:
* ?

## Additional Data

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.1.0
     Serverless Version:     1.30.3

* ***Provider Error messages***:
Invalid variable reference syntax for variable myvar. You can only reference env vars, options, & files. You can check our docs for more info.

**Comment by medikoo** [comment]
Closing as I believe this works as expected with new variable resolver
