### ISSUE TITLE
Lambda scheduled event fails to create when using cloudformation parameter reference

### ISSUE THREAD

**Issue by grittershub** [serverless/serverless#5280]
# This is a Bug Report

## Description

* What went wrong?

scheduled event is not created when using a reference to a cloudformation parameter from within the Resource section

* What did you expect should have happened?

Rule should be created in the same way it would by using raw text instead of a parameter
This is a working rule: 

  sendreallocate:
    handler: sendreallocate/sendreallocate.handler
    role: SendReallocateRole
    runtime: python3.6
    events:
    - schedule: rate(24 hours)

* What was the config you used?

  sendreallocate:
    handler: sendreallocate/sendreallocate.handler
    role: SendReallocateRole
    runtime: python3.6
    events:
    - schedule:
      Ref: ReallocateTimer

* What stacktrace or error message from your provider did you see?

Silent failure (success), but rule is not created at all

## Additional Data

* ***Serverless Framework Version you're using***:
     OS:                     darwin
     Node Version:           6.11.3
     Serverless Version:     1.21.1

* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
Silent failure (success), but rule is not created at all

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...

**Comment by mduthilleul** [comment]
Same problem here using serverless 1.32 with a simple: 
`- schedule:
      rate: cron(54 * * * ? *)
      input:
        key1: value1`

Seems to be related to https://github.com/serverless/serverless/pull/5268

**Comment by pmuens** [comment]
Hey @grittershub thanks for opening 👍

This should've been fixed so updating the Framework should do the trick. Let us know if it's not fixed and we'll reopen...
