### ISSUE TITLE
Provider Environment Variables

### ISSUE THREAD

**Issue by wowi42** [serverless/serverless#5284]
# This is a Feature Proposal

## Description

When you are using provider.environment inside serverless.yml, you have no way to know which variable was loaded, especially if you have variables chained:
```SUPER_VARIABLE: ${env:SUPER_VARIABLE, ssm:/${self:provider.stage}/super_variable,  'awesome'}```

It could be nice to have a summary of all provider.environment variables loaded.

**Comment by medikoo** [comment]
Closing, as (1) it's an old issue, (2) use case is not clear to me (3) we have a new variables resolver, which solved most of the issues.

@wowi42 if that's still an issue on your side. Please elaborate a bit more on the use case, and we'll figure out best approach
