### ISSUE TITLE
Support OpenStack Qinling as a cloud provider

### ISSUE THREAD

**Issue by eggyal** [serverless/serverless#5286]
# This is a Feature Proposal

## Description

* Support [OpenStack Qinling](https://www.openstack.org/software/releases/rocky/components/qinling) as a cloud provider.

Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: n/a
* ***Operating System***: n/a
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by medikoo** [comment]
Closing, as support for any other providers should be simply introduced as plugins, and that's not in scope of Framework core implementation.
