### ISSUE TITLE
Tail on logs not working anymore

### ISSUE THREAD

**Issue by jleppert** [serverless/serverless#5295]
Hello,

Can someone please tell me why tailing logs is broken? This used to work then I upgraded to the new CLI and it's not working anymore. The logs are properly configured and are writing to CloudWatch properly, I can see them in the AWS console and also they are output when just running the logs command with the -t switch.

Running with the -t switch just sits there and produces no output whatsoever. Anyone have any ideas on what could go wrong?

**Comment by vikeri** [comment]
The issue I'm seeing is that I can't go back in time in the logs anymore. New logs will appear but any logs before when I started the script. This is due to this commit: https://github.com/serverless/serverless/commit/4873ebf1c3cbd1b88a47ee008b8bae3b7e21afa0

A solution is to add  `--startTime 1h` to add logs for the last hour.

**Comment by joebernard** [comment]
Slightly different behavior here. Running `serverless logs -f myFunc -t` just returns another command prompt. No output at all. Happens with or without `-t`. The same command used to work.

```
$ serverless version
1.32.0
```

**Comment by nfabacus** [comment]
I have the same issue as @joebernard ..

**Comment by utajum** [comment]
Same here, no output with version 1.33.1, while version 1.32.0 works fine

**Comment by dschep** [comment]
I've released 1.33.2 which fixes this

**Comment by batjko** [comment]
I'm encountering the same issue with the latest version:

Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7

**Comment by mrashidse** [comment]
I'm encountering the same issue with the latest version:
`Framework Core: 2.35.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2`
