### ISSUE TITLE
Serverless plugin "serverless-google-cloudfunctions" not found. Make sure it's installed and listed in the "plugins" section of yourserverless config file.

### ISSUE THREAD

**Issue by saishav7** [serverless/serverless#5300]
This is the error message while deploying a google cloud function. I have included the plugin in my config file but it still doesn't seem to work

**Comment by mugglmenzel** [comment]
Same for me!

**Comment by Chaddhaji** [comment]
Write:
> npm install
It will install all the dependencies.
@Chaddhaji

**Comment by brianneisler** [comment]
I believe @Chaddhaji has a fix here. @saishav7 and @mugglmenzel please let us know if that suggestion solved your issue. We'll reopen if not.
