### ISSUE TITLE
Handler name should be updated while deploying a single function (`deploy -f`)

### ISSUE THREAD

**Issue by bzemms** [serverless/serverless#5302]
# This is a (Bug Report & Feature Proposal)

## Description

For bug reports:
* What went wrong? handler name is not changing while deploying a single function `deploy -f`
* What did you expect should have happened?  handler name should be updated  
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
handler name is not changing while deploying a single function `deploy -f`

* If there is additional config how would it look

Similar or dependent issues:
* #5301 

## Additional Data

* ***Serverless Framework Version you're using***: 1.31.0
* ***Operating System***: mac os
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by brianneisler** [comment]
Believe this was solved with PR #5301
