### ISSUE TITLE
You are running an outdated version of the Serverless Framework. Error reference WSM6MQXX2G02

### ISSUE THREAD

**Issue by elouizbadr** [serverless/serverless#5307]
# This is a Bug Report

## Description

I'm facing this issue when I try to deploy using serverless framework.
I tried to update the serverless package but that didn't help since it's the latest at this moment.

## Additional Data

* ***Serverless Framework Version you're using***: 1.31.0
* ***Operating System***: win32
* ***Stack Trace***:
```
  Error --------------------------------------------------

  {"errorMessage":"You are running an outdated version of the Serverless Framework. Please update and try again. - Please contact support and provide this identifier to reference this issue - WSM6MQXX2G02"}

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.1
     Serverless Version:     1.31.0
```
* ***Provider Error messages***:
```
{"errorMessage":"You are running an outdated version of the Serverless Framework. Please update and try again. - Please contact support and provide this identifier to reference this issue - WSM6MQXX202"}
```

**Comment by Guildgreg** [comment]
@elouizbadr I've just started experiencing this as well, I believe it's related to the event-gateway plugin. Commenting out the app, tenant, and event-way plugin fields in my serverless.yml file allowed me to deploy my service.

**Comment by elouizbadr** [comment]
Thanks for your reply @Guildgreg , however I don't recall using such app, tenant or plugin fields in my serverless.yml file!

**Comment by iosley** [comment]
Update to serverless 1.32.0 and remove "~/.serverless" and "~/.serverlessrc".
Solve for me.

**Comment by Guildgreg** [comment]
Thanks @iosley - that helped me deploy again without having to remove event-gateway.

I still do receive this error, even though the functions deploy properly:
`{"errorMessage":"Something went wrong. - Please contact support and provide this identifier to reference this issue - WSXCGQNTNG83"}`

**Comment by iosley** [comment]
> Thanks @iosley - that helped me deploy again without having to remove event-gateway.
> 
> I still do receive this error, even though the functions deploy properly:
> `{"errorMessage":"Something went wrong. - Please contact support and provide this identifier to reference this issue - WSXCGQNTNG83"}`

try remove the .serverless folder in yout project.
Check if still exist stack (previous deploy) in your cloudformation

**Comment by Caleb-Ardern** [comment]
{"errorMessage":"You are running an outdated version of the Serverless Framework. Please update and try again. - Please contact support
 and provide this identifier to reference this issue - WSPDF03D190P"}

**Comment by Caleb-Ardern** [comment]
@elouizbadr I have a similar issue with a different error code 
`{"errorMessage":"You are running an outdated version of the Serverless Framework. Please update and try again. - Please contact support and provide this identifier to reference this issue - WSPDF03D190P"}`

**Comment by Caleb-Ardern** [comment]
@elouizbadr @maplesteve @Guildgreg 
Try going back a few versions with `npm install -g serverless@1.26.1`
Worked for me

**Comment by ranneyd** [comment]
> @iosley Thanks for your reply, updating to 1.32.0 and removing ".serverless" folder worked for me as well. But I'm facing another error now:
> 
> ```
> 
> 
>   Error --------------------------------------------------
> 
>   The CloudFormation template is invalid: Template format error: Number of resources, 236, is greater than maximum allowed, 200
> 
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> 
>   Stack Trace --------------------------------------------
> 
> Error: The CloudFormation template is invalid: Template format error: Number of resources, 236, is greater than maximum allowed, 200
>     at provider.request.catch (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\validateTemplate.js:25:13)
> From previous event:
>     at AwsDeploy.validateTemplate (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\validateTemplate.js:20:12)
> From previous event:
>     at AwsDeploy.BbPromise.bind.then (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:121:39)
> From previous event:
>     at Object.aws:deploy:deploy:validateTemplate [as hook] (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:117:10)
>     at BbPromise.reduce (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
> From previous event:
>     at PluginManager.invoke (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
>     at PluginManager.spawn (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:408:17)
>     at AwsDeploy.BbPromise.bind.then (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:95:48)
> From previous event:
>     at Object.deploy:deploy [as hook] (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:91:10)
>     at BbPromise.reduce (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
> From previous event:
>     at PluginManager.invoke (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
>     at PluginManager.run (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
>     at variables.populateService.then.then (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)
> From previous event:
>     at Serverless.run (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
>     at serverless.init.then (C:\Users\dell\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
>     at <anonymous>
> 
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com
> 
> 
>   Your Environment Information -----------------------------
>      OS:                     win32
>      Node Version:           8.9.1
>      Serverless Version:     1.32.0
> ```

https://serverless.com/blog/serverless-workaround-cloudformation-200-resource-limit/

**Comment by johnlim** [comment]
I've deleted `~/.serverless`, `~/serverlessrc` and the `.serverless` folder in my project directory. However, when I deploy I get the following error 

```Event Gateway Plugin
 
  Error --------------------------------------------------
 
  Failed to fetch the event types list due the error: API key not set.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
``` 
I've logged out and re-login but the results are still the same. Any help here guys? Thanks

**Comment by pmuens** [comment]
Closing this issue since we've fixed this in the past. Feel free to re-open if this is still a problem.
