### ISSUE TITLE
Add a variable for executing a local command

### ISSUE THREAD

**Issue by justyns** [serverless/serverless#5318]
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This feature proposal is to request a new "[variable](https://serverless.com/framework/docs/providers/aws/guide/variables/)" type that can execute local commands and return the output.

An example use case is that we use the git branch name as part of the service name in our serverless.yml config.  We do that currently by using a custom javascript file with a function that returns the output of `git rev-parse --abbrev-ref HEAD` and a variable like `${file(./dynamic.js):branch}`.

It would be preferable to be able to use a syntax similar to this:

```
service: my-service${exec('git rev-parse --abbrev-ref HEAD')}
```

* If there is additional config how would it look

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by medikoo** [comment]
Closing, as it's a questionable use case with very controversial solution proposed, also we do not see any other requests asking for same.

Service configuration is considered as something portable that should not be repository dependent. I would probably re-dicscuss whether it's a good idea to make repository branch an important variable in service configuration (what really was the use case to follow such route ?)
