### ISSUE TITLE
Deploy the same lambda function version to different stages

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#532]
Is it possible to deploy the same function version to different stages? I tried to do this but didn't seem able to get different aliases to point at the same version using the serverless CLI.

**Comment by kenji-siu-bitgamelabs** [comment]
Stages are currently not configured. For the current stage, one thing I'm sure is that the environment variable `'IS_PRODUCTION'`must be set to appropriate values before using. If you find anything that is not working, please show me and I'll correct it as soon as possible.

**Comment by connaryscott** [comment]
my aliasFunction seems to be ignored.  I have a function already aliased.  I execute function deploy and pass the -f option and it does nothing......

currently aliased here:

```
[ec2-user@ip-10-155-170-114 echo]$ aws --region us-east-1 --profile services lambda list-aliases --function-name euclid-services-elements-echo
{
    "Aliases": [
        {
            "AliasArn": "arn:aws:lambda:us-east-1:REDACTED:function:euclid-services-elements-echo:services", 
            "FunctionVersion": "17", 
            "Name": "services", 
            "Description": "Project: euclid-services Stage: services"
        }
    ]
}
```

run deploy using another alias:

```
[ec2-user@ip-10-155-170-114 echo]$ serverless function deploy -f anotherAlias
Serverless: Deploying all functions in: elements/echo...  
Serverless: Deploying functions in "services" to the following regions: us-east-1  
Serverless: ------------------------  
Serverless: Successfully deployed functions in "services" to the following regions:   
Serverless: us-east-1 ------------------------  
Serverless:   elements/echo (euclid-services-elements-echo): arn:aws:lambda:us-east-1:REDACTED:function:euclid-services-elements-echo:services  
```

And we see that the new alias is not there:

```
[ec2-user@ip-10-155-170-114 echo]$ aws --region us-east-1 --profile services lambda list-aliases --function-name euclid-services-elements-echo
{
    "Aliases": [
        {
            "AliasArn": "arn:aws:lambda:us-east-1:946611947052:function:euclid-services-elements-echo:services", 
            "FunctionVersion": "18", 
            "Name": "services", 
            "Description": "Project: euclid-services Stage: services"
        }
    ]
}
```

**Comment by ac360** [comment]
@connaryscott I just pushed a fix for this in the `v0.5` branch.  Could you please confirm if it works for you?

**Comment by flomotlik** [comment]
@connaryscott let us know if you have an update to this, otherwise I will close for now.

**Comment by c-knowles** [comment]
Anyone know of a way to link different stages to the same function version as in my original question?
