### ISSUE TITLE
Official site 404 pages

### ISSUE THREAD

**Issue by mrdulin** [serverless/serverless#5320]
https://serverless.com/framework/docs/providers/events
https://serverless.com/framework/docs/providers/cli-reference/deploy
https://serverless.com/framework/docs/providers/guide/functions
https://serverless.com/framework/providers/fn/guide/quick-start
https://serverless.com/framework/providers/google/events

...to be continued

**Comment by eahefnawy** [comment]
@mrdulin thanks a lot for reporting. I'm seeing the same! Investigating...

**Comment by pmuens** [comment]
Closing this issue since it's related to the `serverless/site` repository. Please open up an issue over there.

Navigating to the docs with the navigation works on my end.
