### ISSUE TITLE
Authorize a lambda to access a ressource protected with cognito (no authentication)

### ISSUE THREAD

**Issue by KrifaYounes** [serverless/serverless#5321]
I have a lambda developed in node js.
I have to allow my lambda to access a Java Api protected with cognito.
My lambda is a job run each hour and there is no login form.
How my lambda can access the ressource without authentication on my protected JavaApi with cognito thanks.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
