### ISSUE TITLE
Cannot assign to read only property 'noDeprecation' of object '#<process>'

### ISSUE THREAD

**Issue by naturalethic** [serverless/serverless#5323]
# This is a Bug Report

## Description

The `serverless` script fails when trying to set `process.noDeprecation = true`.  If I remove `use strict` from the script, it works as expected.

For bug reports:
* What went wrong?
`serverless` script fails with TypeError

* What did you expect should have happened?
For it to not fail.

* What was the config you used?
No config.

* What stacktrace or error message from your provider did you see?
```
§ serverless

node_modules/serverless/bin/serverless:24
process.noDeprecation = true;
                      ^
TypeError: Cannot assign to read only property 'noDeprecation' of object '#<process>'
    at Object.<anonymous> (node_modules/serverless/bin/serverless:24:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

## Additional Data

* ***Serverless Framework Version you're using***:
`"serverless": "^1.32.0"`

* ***Operating System***:
MacOS 10.14

* ***Node Versions***:
8.11.3
10.7.0

**Comment by pmuens** [comment]
Thanks for opening @naturalethic 👍

This seems to be an issue out of the scope of the Framework. What are you trying to accomplish by setting `process.noDeprecation = true`?

**Comment by dschep** [comment]
@pmuens that line is right here: https://github.com/serverless/serverless/blob/master/bin/serverless#L23

but it is very odd that it's causing an issue and we only have one report of it 😕

**Comment by naturalethic** [comment]
Sorry I should have closed this a while ago.  It turned out to be something local about my node installation, some environment variable I had set and forgotten about.

**Comment by it-is-wednesday** [comment]
![image](https://user-images.githubusercontent.com/4103412/182876454-d0685011-d35d-4df2-bd5f-00f3facbcdf1.png)

The problem for me was indeed in the `NODE_OPTIONS` environment variable, which was set to `--no-deprecation`. Setting it to an empty string solved it :)
