### ISSUE TITLE
[FEATURE REQUEST] multi-region support

### ISSUE THREAD

**Issue by zhenyulin** [serverless/serverless#5330]
# This is a Feature Proposal

Currently deploy to multiple region would require running `sls deploy -r ${region}` multiple times, and in case of a deployment failed on a certain region, rolling back or retrying deployment isn't convenient to keep lambdas consistent across different regions.

Can I propose to have a feature of `sls deploy -r eu-west-1 -r us-west-1` to consolidate the multi-region deploy and rollback in one action?

**Comment by pmuens** [comment]
Closing this issue since it's a duplicate of https://github.com/serverless/serverless/issues/4123
