### ISSUE TITLE
Support enterprise Github with 'serverless install'

### ISSUE THREAD

**Issue by bstascavage** [serverless/serverless#5332]
# This is a Feature Proposal

## Description
Right now the command `serverless install` statically checks if the url being passed is from `github.com`, `bitbucket.com`, or `gitlab.com`.  This means that it is impossible to run `serverless install` for an Enterprise Github repo.  `serverless install` should be expanded to support more potential domains, or a smarter validation should be done than just checking the hostname of the url.

[Code in question: ](https://github.com/serverless/serverless/blob/master/lib/utils/downloadTemplateFromRepo.js#L155-L169)

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Mac OSX
* ***Stack Trace***: `none`
* ***Provider Error messages***: 

```
sls install --url https://<redacted_enterprise_github_url>/<org>/<repo>

  Serverless Error ---------------------------------------

  The URL you passed is not one of the valid providers: "GitHub", "BitBucket".
```

**Comment by r5sec5cyl** [comment]
Given that `parseGitHubURL`, `parseBitbucketURL`, and `parseGitlabURL` are identical functions, it seems that only one parse function is needed. Most, if not all, will parse the same way, including GitHub Enterprise. 

I think a better validation would be to check if a git origin exists at the remote address:
```
GIT_TERMINAL_PROMPT=0 git ls-remote https://<origin_server>/<org>/<repo>
```

As the original poster stated, the current state makes it impossible to certain functionalities in an enterprise environment, including `sls install` and `sls create`, and this impacts using Serverless Framework templates.

**Comment by dschep** [comment]
This should be made possible by #5715 which was released in v1.36.3

**Comment by dschep** [comment]
Oops, misread. this is a github server other than github.com, not private repos 🤦‍♂️

**Comment by kalote** [comment]
Hello,
I'm running into this error after setting up some templates that i wanted to use from our github entreprise setup.

`sls create --template-url https://githubentreprise.mydomain.com/serverless-template/serverless/tree/master/non-prod/aws-nodejs --path test`

The above command returns:

`The URL you passed is not one of the valid providers: "GitHub", "Bitbucket", or "GitLab".`

I'm using sls version 1.43.0

Any information on how / when this can be possible? Can i help somehow?

/kalote
