### ISSUE TITLE
The 'google-api-core' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by luisdemarchi** [serverless/serverless#5333]
## Description

I'm using the DialogFlow library and started getting a lambda startup error, claiming the lack of the 'google-api-core' library. This started happening about 7 days ago.

I saw reference in another repository claiming the same error, saying that to fix just put the version range of serverless. But that did not work.

## additional data

* *** Framework serverless version ***: 1.32.0
* *** Operating System ***: Mac 10.14
* *** Language ***: Python 3.6
* *** Supplier error messages ***:

> START RequestId: cb5f158a-c1ce-11e8-bb2e-31a9c67b8990 Version: $LATEST
> module initialization error: The 'google-api-core' distribution was not found and is required by the application
> 
> END RequestId: cb5f158a-c1ce-11e8-bb2e-31a9c67b8990
> REPORT RequestId: cb5f158a-c1ce-11e8-bb2e-31a9c67b8990	Duration: 48.36 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 32 MB	
> module initialization error
> The 'google-api-core' distribution was not found and is required by the application

* *** requirements.txt ***:
`dialogflow==0.4`

* *** oi.py ***:
```
import dialogflow

def oi(event, context):
    return {
        "statusCode": 200,
        "body": "ahhh hiiii"
    }

```

**Comment by AmitChotaliya** [comment]
I am having the same issue while using Google Cloud Firestore. Here's the details.

AWS Lambda
Python: 3.6
Library: Google Cloud Firestore.
Used : serverless-python-requirements
Here's the error.

```log
module initialization error: The 'google-cloud-firestore' distribution was not found and is required by the application
```

**Comment by luisdemarchi** [comment]
Hello everyone. 

@pmuens AWS Lambda
@AmitChotaliya 
The problem is low-level libraries that are not packaged. The solution is to use Docker with the plugin serverless-python-requirements

**Comment by dschep** [comment]
Ah.. yeah, if they are python dependencies, you'll need to manage that yoruself or use [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) and if they are compiled dependencies, you'll need to use the [`dockerizePip` option](https://github.com/UnitedIncome/serverless-python-requirements#cross-compiling)

**Comment by AmitChotaliya** [comment]
I had tried that but it still did not work. I even tried `non-linux` without understanding it which also did not work. I just tried removing `slim: true` and IT WORKED. What could be the reason?

**Comment by dschep** [comment]
Ah, yeah, thats why the `slim` option isn't default. It _can_ break things. Glad you got it working @AmitChotaliya!

**Comment by dschep** [comment]
@AmitChotaliya feel free to open a bug for `slim` breaking the specific packages it broke for you over in the [serverless-python-requirements repo](https://github.com/unitedincome/serverless-python-requirements).

**Comment by tonio-m** [comment]
I also had this problem when installing python dependencies manually on the current directory.
If you delete the **.dist-info** folders this will error will happen to the google.cloud library. 

Maybe that's what `slim` does behind the curtains to reduce size, delete dist-info and other stuff.
