### ISSUE TITLE
Allowed to deploy dashboard-linked service without logging in

### ISSUE THREAD

**Issue by plfx** [serverless/serverless#5334]
# This is a Bug Report

## Description

The Serverless Framewwork is not enforcing the requirement of login for deployments linked to the Dashboard. To reproduce, create a service and add an `app` and `tenant` property to the YML. Then perform `sls logout` followed by `sls deploy`. The framework should not attempt the deploy:
```
jeremy@workhorse:~/Code/test$ sls logout
Successfully logged out.
jeremy@workhorse:~/Code/test$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

## Additional Data

Tested on v1.28.0 and v1.32.0

**Comment by pmuens** [comment]
Thanks for opening @plfx 👍

Is this still a thing? @eahefnawy @dschep do you guys know the current state of affairs here?

**Comment by dschep** [comment]
Yup.. this would now be an issue in [serverless/enterprise-plugin](https://github.com/serverless/enterprise-plugin), but I think it's ok in it's current state because it does print a warning:
```
Serverless Enterprise: Warning: You are not currently logged in.  All enterprise features will be disabled.  To log in, use: $ serverless login
```
