### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#535]
It would be great if a parameter such as `--verbose` is supported so that users know what happens behind the scenes when e.g. such an error is thrown

```
The following resource(s) failed to create: [DynamoDB]
```

**Comment by mt-sergio** [comment]
Just run it with --debug
--> https://github.com/serverless/serverless/blob/master/bin/serverless#L7

**Comment by pmuens** [comment]
Thanks! Didn't knew that
