### ISSUE TITLE
Improve issue tracking project management using separate github issue templates

### ISSUE THREAD

**Issue by softprops** [serverless/serverless#5350]
# This is a  Feature Proposal

## Description

Use github separate issue templates to manage feature requests and bug reports separately.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Having been though the issue submission process once, I seem room for improvement that could be had using native github issue tracking integrations. In particular I believe this project should consider using githubs [separate issue template feature](https://blog.github.com/2018-05-02-issue-template-improvements/) At the movement there is [one issue template](https://github.com/serverless/serverless/blob/master/.github/ISSUE_TEMPLATE.md) that is shared for two types of issue tracking. This puts a burden of understanding what's desired on the person doing the reporting. An example of github's system in practice can be found with [github's pull request vscode integration repo](https://github.com/Microsoft/vscode-pull-request-github/issues/new/choose). 

* If there is additional config how would it look

An example of the conventions that make that work can be found [here](https://github.com/Microsoft/vscode-pull-request-github/tree/master/.github/ISSUE_TEMPLATE)

Github them renders these as follows when someone clicks the "New issue" button.

![screen shot 2018-10-03 at 11 14 29 am](https://user-images.githubusercontent.com/2242/46420225-8b3f3100-c6fd-11e8-9855-5dc0d6937b2c.png)

**Comment by softprops** [comment]
I would be willing to take the first cut at this is this seems useful for the serverless project

**Comment by softprops** [comment]
I just tried this one of my own repos https://github.com/softprops/shiplift/pull/104 and no repo setting changes were necessary despite what [this post](https://blog.github.com/2018-05-02-issue-template-improvements/) suggests. All that is needed are the presence of the files and the markdown front matter ( [example](https://raw.githubusercontent.com/Microsoft/vscode-pull-request-github/master/.github/ISSUE_TEMPLATE/bug_report.md) ) at the top of the markdown files

```
---
name: display name
about: display description
---
```

**Comment by brianneisler** [comment]
@softprops this is awesome. Totally agree this would be a great improvement. If you feel like opening a PR I would be happy to merge it.

**Comment by softprops** [comment]
@ brianneisler pull is up for grabs
