### ISSUE TITLE
The final policy size is bigger than the limit (20480)

### ISSUE THREAD

**Issue by Jaystified** [serverless/serverless#5357]
# This is a Bug Report

## Description

* What went wrong? **Stack update failed. Removing and redeploying did not help.**
* What did you expect should have happened? **Stack update should complete successfully.**
* What was the config you used? **serverless.yml contains a single function with dozens of event sources as subscription filters to CloudWatch Logs.**
* What stacktrace or error message from your provider did you see? `The final policy size (size here differs between deployments) is bigger than the limit (20480)`

Similar or dependent issues:
* None?

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Ubuntu 18.04
* ***Stack Trace***:
* ***Provider Error messages***: 
```
  Serverless Error ---------------------------------------
 
  An error occurred: SubscriptionFilterLambdaLambdaPermissionLogsSubscriptionFilterCloudWatchLog28 - The final policy size (20623) is bigger than the limit (20480). (Service: AWSLambda; Status Code: 400; Error Code: PolicyLengthExceededException; Request ID: a87d245a-c85c-11e8-a18a-af6f9fead152).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.1
     Serverless Version:     1.32.0
```
The issue seems to have been reported on the [forums](https://forum.serverless.com/t/aws-lambda-permission-policy-size/3952) however the linked solution does not work.

**Comment by exoego** [comment]
This issue is very frustrating for me, too.

Currently, `AWS::Lambda::Permission` object are created for every `cloudwatchLog` events.
If one `CloudFormation` stack has many `AWS::Lambda::Perission`, `CF` raises `The final policy size is bigger than the limit` error.
The issue forces users to split `cloudwatchLog` subscriber services into separate `serverless.yml`.

I will open PR for this.
