### ISSUE TITLE
Create AWS::Lambda::Permission failed in China region.

### ISSUE THREAD

**Issue by beary** [serverless/serverless#5365]
# This is a Bug Report

## Description
Create `AWS::Lambda::Permission` failed when deployed in region `cn-north-1`, but it works fine in `ap-southeast-1` or any other regions.
> An error occurred: HelloLambdaPermissionApiGateway - The provided principal was invalid. Please check the principal and try again.

I checked the event logs on cloudtrail:
```json
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "xxxxx",
        "arn": "arn:aws-cn:iam::9999999:user/xxxxx",
        "accountId": "9999999",
        "accessKeyId": "xxxxxxx",
        "userName": "xxxxxx",
        "sessionContext": {
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2018-10-08T06:25:19Z"
            }
        },
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2018-10-08T06:25:39Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "AddPermission20150331v2",
    "awsRegion": "cn-north-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "InvalidParameterValueException",
    "errorMessage": "The provided principal was invalid. Please check the principal and try again.",
    "requestParameters": {
        "statementId": "serverless-sample-dev-HelloLambdaPermissionApiGateway-YHITVS5HX6JW",
        "action": "lambda:InvokeFunction",
        "functionName": "arn:aws-cn:lambda:cn-north-1:9999999:function:serverless-sample-dev-hello",
        "principal": "apigateway.amazonaws.com.cn",
        "sourceArn": "arn:aws-cn:execute-api:cn-north-1:9999999:aaaaaaa/*/*"
    },
    "responseElements": null,
    "requestID": "fffffff",
    "eventID": "fffffff",
    "eventType": "AwsApiCall",
    "recipientAccountId": "9999999"
}
```
the problem is *apigateway.amazonaws.com.cn*, although [aws document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-urlsuffix) says
> the suffix for the China (Beijing) region is amazonaws.com.cn.

But in fact, `amazonaws.com` is the only valid value even if in China.

![iam](https://user-images.githubusercontent.com/6630583/46597076-380c1a80-cb11-11e8-94c1-88d26ef257c4.png)

After replace all the `AWS::URLSuffix` to hardcoded amazonaws.com on my computer, the problem was resolved. I'd like to make a PR to fix it.

Similar or dependent issues:
* #4665 

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Ubuntu 18.04
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by beary** [comment]
I wrote [a plugin](https://github.com/beary/serverless-plugin-aws-cn-principal) to resolve this problem.

**Comment by beary** [comment]
I close this issue because this problem is caused by AWS China. If anyone else meet this problem in AWS China, just replace this pseudo variable: `AWS::URLSuffix`.

**Comment by dattatrayhkulkarni** [comment]
> I wrote [a plugin](https://github.com/beary/serverless-plugin-aws-cn-principal) to resolve this problem.

I was able to resolve the issue by using the plugin, The deployment in  AWS China region was successful. But when I tried to access the APIs (GET methods), I got "403 forbidden" error

**Comment by beary** [comment]
@dattatrayhkulkarni What's the response body, `{"Message": "null" }`?

**Comment by beary** [comment]
@dattatrayhkulkarni Take a look https://github.com/serverless/serverless/issues/4703#issuecomment-431765116

**Comment by activeliang** [comment]
I have resolved it. https://github.com/serverless/serverless/issues/4703#issuecomment-1625810017
