### ISSUE TITLE
Option to fail fast on unresolved variables

### ISSUE THREAD

**Issue by r1b** [serverless/serverless#5369]
# Feature Proposal

## Description

* The user should have the option to treat an unresolved variable as a fatal error. The user may wish to correct these issues at build time instead of building an artifact with missing values.
* This could be an option on `sls package` e.g `--strict`.

## Additional Data

* ***Serverless v1.30.0***

**Comment by kiesel** [comment]
I would second this. When a variable ultimately cannot be resolved, I'd like to have an option (commandline?) to make this an error.

I do inject application configuration settings at build time, a missing value means I messed up the build pipeline or similar. Today, the broken app would be deployed and break the stage.

What I alternatively would consider is the following: in the build pipeline do a `serverless print` do have the config be generated; however, `print` does not evaluate a `--stage` parameter, so the config is not what it would be when deploying.

**Comment by medikoo** [comment]
Closing as new variables resolver fails on first resolution error
