### ISSUE TITLE
serverless update check failed

### ISSUE THREAD

**Issue by liuronaldo9** [serverless/serverless#5373]
┌─────────────────────────────────────────────┐
                          │             serverless update check failed              │
                          │          Try running with sudo or get access        │
                          │          to the local update config store via          │
                    │ sudo chown -R $USER:$(id -gn $USER) /Users/Joe/.config │
└─────────────────────────────────────────────┘
+ serverless@1.32.0
updated 1 package in 5.807s

Does anyone have this problem?  How to fix that?  Thanks

**Comment by u84six** [comment]
Yeah, I'm having the same problem on mac. The latest version installs, but I see the same "check failed" error. The ownership on the directory is fine, too. I suppose I should ignore it for now until something goes wrong.

**Comment by haydenlingle** [comment]
Same issue. Attempted the command they gave.. No luck.

**Comment by mimoYmima** [comment]
same - anyone know how to fix this?

**Comment by pmuens** [comment]
Thanks for opening @liuronaldo9 👍

It looks like this is an issue with the `update-notifier`. A related issue can be found here: https://github.com/yeoman/update-notifier/issues/76

Closing since this is something which cannot be fixed in the Serverless Framework project.
