### ISSUE TITLE
AWS Lambda timeout increased to 15 minutes

### ISSUE THREAD

**Issue by waynerobinson** [serverless/serverless#5374]
The AWS Lambda function timeout has been increased to 15 minutes today.

https://docs.aws.amazon.com/lambda/latest/dg/history.html

Is there any changes required in the framework to support this increase?

**Comment by softprops** [comment]
I haven't tried this but it may just work specify a function timeout in that many seconds. Serverless just cloudformation to create and update resources. If cloud formation supports the new timeout, serverless should https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#w2ab1c21c10d887b9

**Comment by pmuens** [comment]
Hey @waynerobinson thanks for opening.

Since we complie to CloudFormation you should be able to use the new timeout and should be good (so no changes necessary in the Framework code).

Feel free to re-open if this is not possible...

**Comment by scamden** [comment]
@pmuens can you comment on https://github.com/serverless/serverless/issues/5374#issuecomment-441319467

i see this as well. even though the lambda invoke continues, serverless hangs up and keeps "retrying" (which as far as I can tell does nothing..)
