### ISSUE TITLE
servless nodejs function runs fine locally, but returns null on aws

### ISSUE THREAD

**Issue by vmetayer** [serverless/serverless#5380]
I created a nodejs serverless function using the general template.  the function has a few private functions.  The handler simply calls a callback function which makes an api call.  This works find when I invoke local.  However, after deploying and running, when i invoke the aws version i receive "null" immediately.

AWS Lambda doesn't even log the first "Started" message in the async function.

```
module.exports.newOrder = async (event, context, callback) => {

  console.log("Started"); 
  var orders = getOrders(catalogUUID,"Adidas",callback);

};

function getOrders(supplier,vendor,callback){

     requestOrders(function(error, res) {

            //console.log(JSON.stringify(res));
            console.log('final order object length: ' + res.length);
            //console.log('final sku object: ' + JSON.stringify(skuObject));
            processOrders(res);
    });

    //return;

}
```

**Comment by pmuens** [comment]
Hey @vmetayer thanks for opening 👍

This looks like a race condition. Could you call the `callback` function passed into the handler to make sure that you properly handle the async event flow?

That should fix the issue.
