### ISSUE TITLE
Deprecated: Use Buffer.from() instead

### ISSUE THREAD

**Issue by nogut0123** [serverless/serverless#5394]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

According to the Node.js officail documents, `new Buffer()` is deprecated because there are security vulnerabilities in it.

`Buffer.from()` might support Node.js v4.x, so have to convert `Buffer.from()` from `new Buffer()` to be more secure.

https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_class_buffer
https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html#buffer_class_buffer

```
Stability: 0 - Deprecated: Use Buffer.from(array) instead.
```

```
Stability: 0 - Deprecated This feature is known to be problematic, and changes may be planned. Do not rely on it. Use of the feature may cause warnings to be emitted. Backwards compatibility across major versions should not be expected.
```

The following classes are concerned.

- `new Buffer(array)`
- `new Buffer(buffer)`
- `new Buffer(arrayBuffer[, byteOffset [, length]])`
- `new Buffer(size)`
- `new Buffer(string[, encoding])`

### Reference

https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html
https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html
https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html
https://nodejs.org/dist/latest-v10.x/docs/api/buffer.html

**Comment by piraces** [comment]
Hi, I would like to contribute and make my first PR to the project.

I will investigate further to convert `Buffer.from()` from `new Buffer()` to be more secure as @nogut0123 suggested.

**Comment by piraces** [comment]
As I commented in the PR (https://github.com/serverless/serverless/pull/5730#issuecomment-455872114), it seems that Node.js v4.4.7 has no reference to Buffer.from() method and uses the deprecated constructor.

Do you consider deprecating support for Node.js v.4.4 and set minimum version v4.5?

If you want to maintain the current Node.js minimum version, then this issue can not solved...

**Comment by pmuens** [comment]
Thanks again for opening @nogut0123 and thanks for working on a fix @piraces 👍

As we've discovered and discussed this would result in a breaking change so this can only be tackled in `v2`. I'll close this issue for now since `v2` will drop Node.js 4 support anyways.
