### ISSUE TITLE
development dependencies are not excluded

### ISSUE THREAD

**Issue by sixmen** [serverless/serverless#5396]
# This is a Bug Report

## Description

Sample program is:

```
$ serverless --version
1.32.0

$ cat serverless.yml 
service: test

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256

functions:
  app:
    handler: app.handler

plugins:
  - serverless-plugin-typescript

$ cat package.json 
{
  "devDependencies": {
    "serverless-plugin-typescript": "^1.1.5"
  }
}
```

When I run `serverless package`, I hope the package does not include any module, but it has many modules include typescript module.

node_modules tree is:
```
$ npm ls
/tmp/sl
└─┬ serverless-plugin-typescript@1.1.5
  ├─┬ fs-extra@5.0.0
  │ ├── graceful-fs@4.1.11
  │ ├─┬ jsonfile@4.0.0
  │ │ └── graceful-fs@4.1.11 deduped
  │ └── universalify@0.1.2
  ├─┬ globby@7.1.1
  │ ├─┬ array-union@1.0.2
  │ │ └── array-uniq@1.0.3
  │ ├─┬ dir-glob@2.0.0
  │ │ ├── arrify@1.0.1
  │ │ └─┬ path-type@3.0.0
  │ │   └── pify@3.0.0 deduped
  │ ├─┬ glob@7.1.3
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ ├── once@1.4.0 deduped
  │ │ │ └── wrappy@1.0.2
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ minimatch@3.0.4
  │ │ │ └─┬ brace-expansion@1.1.11
  │ │ │   ├── balanced-match@1.0.0
  │ │ │   └── concat-map@0.0.1
  │ │ ├─┬ once@1.4.0
  │ │ │ └── wrappy@1.0.2 deduped
  │ │ └── path-is-absolute@1.0.1
  │ ├── ignore@3.3.10
  │ ├── pify@3.0.0
  │ └── slash@1.0.0
  ├── lodash@4.17.11
  └── typescript@2.9.2
```

but zipService.excludeDevDependencies excludes only serverless-plugin-typescript.

```
Serverless: Excluding development dependencies...
{ exclude: 
   [ '.git/**',
     '.gitignore',
     '.DS_Store',
     'npm-debug.log',
     'serverless.yml',
     'serverless.yaml',
     'serverless.json',
     'serverless.js',
     '.serverless/**',
     '.serverless_plugins/**',
     '/tmp/sl/.build/.serverless_plugins',
     'node_modules/serverless-plugin-typescript/**' ],
  include: [] }
```

Is this a bug, or am I missing something?

**Comment by emmanuelnk** [comment]
Same issue. I've tried multiple times but devDependencies (including the very heavy aws-sdk) are NOT excluded when deploying.
version: 1.30.1

**Comment by sbkn** [comment]
I've ran multiple sls apps with mulptiple sls versions and have never been able to exclude devDependencies from the packaged file. Would be very interested in a solution!

**Comment by ManfredLange** [comment]
One alternative solution to this problem is using Webpack. Here is an example by The Code Barbarian:  http://thecodebarbarian.com/bundling-a-node-js-function-for-aws-lambda-with-webpack

The additional beauty of using Webpack is that the resulting bundle file is very small and can even include dependencies extracted from your ./node_modules folder

**Comment by gwiesing** [comment]
I did a direct comparison of serverless 1.34.1 and 1.35.0. With 1.34.1 a serverless package leads to a zip file of 1.6MB and with 1.35.0 the same packaging results in a files size of more than 10MB.

**Comment by nnyegaard** [comment]
We multiple people having this issue

**Comment by deltafactory** [comment]
I haven't found the exact version where the issue began, but I have found one source of the issue for Windows users.

* The npm ls output returns the OS path separator, \
* globby's file list uses the path separator /, regardless of OS

The patterns generated for exclusion don't match and therefore aren't excluded.

**Comment by deltafactory** [comment]
Related? https://github.com/sindresorhus/globby/issues/84

**Comment by pmuens** [comment]
Thanks for opening @sixmen 👍

It looks like this is related to the TypeScript project / plugin since core still excludes dev dependencies just fine. Could you open up an issue in the plugins repository? Thanks!

**Comment by deltafactory** [comment]
@pmuens Have you looked at my comments above? I had found a specific issue affecting core on Windows. I am not using any plugins. Seems like closing this is premature.

**Comment by jderose9** [comment]
This should be open. On Windows, 1.37.1 does not exclude dev dependencies. On 1.34.1, they are excluded as expected.

**Comment by exoego** [comment]
@deltafactory @jderose9 
If you are using serverless on Windows, the issue may be resolved in PR #5808 which is merged to master.

Could you install serverless from master branch by the below command, then confirm your issue is fixed?
```
npm install -g serverless/serverless
```

**Comment by aviadsteps** [comment]
Tried it on windows, doesn't seem to be solved

**Comment by deltafactory** [comment]
After installing 1.37.1 and running `sls package`, the resulting zip file worked as expected.

@aviadsteps can you give more details about what's going on?

**Comment by aviadsteps** [comment]
Sure, I'm on window, version is 1.37.1.

Running `sls package` would create a zip file, but the zip file is too big than it was in the previous versions. 

Checking the zip contents, I see actually that the node modules that are included in the devDependencies are also included in the zip file.

**Comment by exoego** [comment]
@aviadsteps 
Did you test after installing via `npm install -g serverless/serverless` ?
If not, the changes in PR #5808 is not applied.

BTW, the changes in PR #5803 is going to be released in `v1.38.0`.

**Comment by aviadsteps** [comment]
@exoego 
Yep, this seemed to solve the issue, I got confused because I was using the wrong sls version even after updating (Shame...).

All others, please learn from my case and make sure you update and use the right version.

**Comment by mrchief** [comment]
I'm using serverless@1.44.1 and this issue still happens.

**Comment by mrchief** [comment]
Nevermind. I had 

```
include: 
  - node_modules/**/*
```

After removing that, it correctly excludes dev deps.

**Comment by henrikbjorn** [comment]
I have been trying to get started with `serverless` and `typescript` and have trouble with dev packages being included. 

I don't have any `include` in my file. Any ideas?

**Comment by henrikbjorn** [comment]
Reproducable https://gist.github.com/henrikbjorn/bae6d54c772890ebf30157ef041d7681

**Comment by mulib** [comment]
any workaround for this?
does bundling help? can i downgrade to resolve it?

**Comment by henrikbjorn** [comment]
> any workaround for this?
> does bundling help? can i downgrade to resolve it?

I switched to `serverless-webpack` there is a PR on the typescript plugin repository but it seems abandoned.

**Comment by dev7machine** [comment]
I had the same problem Used the following yml and it excluded the node_modules


Replace 
```
exclude:
    - node_modules/**
    - venv/**
```

With the following
```
package:
  individually: true
  excludeDevDependencies: true
  browser: false
  exclude:
    - node_modules/**
    - venv/**
```

**Comment by Siyabonga-Gregory** [comment]
[dev7machine](https://github.com/dev7machine)

> I had the same problem Used the following yml and it excluded the node_modules
> 
> Replace
> 
> ```
> exclude:
>     - node_modules/**
>     - venv/**
> ```
> 
> With the following
> 
> ```
> package:
>   individually: true
>   excludeDevDependencies: true
>   browser: false
>   exclude:
>     - node_modules/**
>     - venv/**
> ```

Thanks , It works for me but has to remove this line " individually: true"
