### ISSUE TITLE
Wrong error when S3 bucket name starts with an upper-case character

### ISSUE THREAD

**Issue by kalevalp** [serverless/serverless#5406]
# This is a Bug Report

## Description

When an S3 bucket name starts with an upper case character, the following error message is displayed:

    Bucket name must start with a letter or number. Bucket-dev

The error message should either explicitly state that the "bucket name must start with a *lower-case* letter or number", or instead state that capital letters are not allowed (as is the case when the upper-case character is in the middle of the name: `Bucket name cannot contain uppercase letters. bucKet-dev`)

**Comment by RafalWilinski** [comment]
Fix: https://github.com/serverless/serverless/pull/5409
