### ISSUE TITLE
Unable to import module 'functions/interface/case-reply': Error

### ISSUE THREAD

**Issue by desmond-phonegap** [serverless/serverless#5407]
The serverless framework directory structure is as bellow

![image](https://user-images.githubusercontent.com/12242790/47253161-44ce2e00-d482-11e8-9dae-39cb549e489e.png)

My function definition in serverless.yaml is as bellow.
![image](https://user-images.githubusercontent.com/12242790/47253173-75ae6300-d482-11e8-8ac3-9471d49dec49.png)

Since my system is large I have folder structure for each lambda function. 

```
the error that prompts is as shwon bellow
Unable to import module 'functions/interface/case-reply': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at /var/task/node_modules/graphql-tag/lib/graphql-tag.umd.js:7:14
at /var/task/node_modules/graphql-tag/lib/graphql-tag.umd.js:2:65
at Object.<anonymous> (/var/task/node_modules/graphql-tag/lib/graphql-tag.umd.js:5:2)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
```

After inspecting the error i find that Lambda is nto able to import the graphql-tag module.  I am not using webpack plugin since some of the lambdas are written in python. 

Please help me resolve this as early as you can. thanks.

**Comment by pmuens** [comment]
Thank for opening @desmond-phonegap 👍

Could you share some more information like your `serverless.yml` file?

**Comment by pmuens** [comment]
Closing this issue since there's not enough information available. Feel free to re-open once more information is available.
