### ISSUE TITLE
Calling `sls invoke local -f myfunction` is very slow to complete

### ISSUE THREAD

**Issue by GazEdge** [serverless/serverless#5410]
# This is a (Bug Report / Feature Proposal)

## Description
Calling `sls invoke local -f myfunction` is very slow to complete when using serverless 1.32 and python 3.6.5 on OSX 10.12

For bug reports:
* What went wrong?
Call takes a long time to finish (2-5s) even when using a 'hello world' simple handler

* What did you expect should have happened?
I would expect the call to return much quicker in local environment (less than 1s)

* What was the config you used?
service: test
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
functions:
  hello:
    handler: handler.hello
    events:
      - http: get hello

* What stacktrace or error message from your provider did you see?
na

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Make invoke run quicker

* If there is additional config how would it look
na

Similar or dependent issues:
na

## Additional Data

* ***Serverless Framework Version you're using***:
1.32
* ***Operating System***:
OSX 10.12
* ***Stack Trace***:
na
* ***Provider Error messages***:
na

**Comment by Jordan-Eckowitz** [comment]
I'm running into the same issue. When running inside a docker container it takes even longer. It can take up to **20s** to get a "hello world" response.
