### ISSUE TITLE
npm install serverless generating error

### ISSUE THREAD

**Issue by kunalnhes** [serverless/serverless#5412]
npm ERR! Unexpected end of JSON input while parsing near '...rmidable":"^1.0.17","'

**Comment by pwagener** [comment]
@kunalnhes can you provide the full `package.json` you're using?  This is likely a typo in that file that NPM is choking on.

**Comment by pmuens** [comment]
Closing since it's quite stale and we've shipped some fixes in the meantime. Feel free to re-open if this issue still persists...
