### ISSUE TITLE
Passing Existing Role ARN to step function API Trigger like we passing existing role arn for lambda function

### ISSUE THREAD

**Issue by sreemas** [serverless/serverless#5415]
Description
1. As part of use case i am deploying step function which triggers multiple lambda function. To trigger step function i am enabling API Trigger. 
2. I pre created role with required permission and passed the role ARN for lambda function. This worked!!!
3. I was able to do the same for step function (Passing an existing role ARN). This Worked!!!
4. But the same is not working for API Trigger. It is not able to consume existing Role , it is asking for IAM permission to create a new role for API Gateway service. 
5. I do not want serverless framework to create roles as i would like to pass an existing roles as part of security recommandations
Is there way to pass an existing role to API Gateway as part of step function trigger?

**Below is the code**

service: step-functions-example3

provider:
  name: aws
  runtime: nodejs6.10
  stackName: aws-stack-stepfunctions-test3
  region: us-east-1
  deploymentBucket:
   name: xxyyyy
   serverSideEncryption: AES256 # when using server-side encryption
  role: arn:aws:iam::xxxxyyy:role/Lambdarolename

functions:
   ciao:
    handler: handler.ciao
stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: 'hello1'
      role: arn:aws:iam::xxyyy:role/StepFunctionrolename
      events:
        - http:
            path: hello1     
            method: GET
             role:arn:aws:iam::xxyyy:role/APIrolename
      definition:
        Comment: "A Hello World example"
        StartAt: CiaoWorld1
        States:
          CiaoWorld1:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:{AWS::AccountId}:function:${self:service}-${opt:stage}ciao"
            End: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
