### ISSUE TITLE
Cannot deploy new stacks - "Template error: IAM role [role] doesn't exist"

### ISSUE THREAD

**Issue by DianaIonita** [serverless/serverless#5418]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I'm trying to deploy the Hello World example as shown here: https://serverless.com/framework/docs/providers/aws/examples/hello-world/node/
The deployment fails with the following error message:
```HelloLambdaFunction - Template error: IAM role myHelloWorld-dev-us-east-1-lambdaRole doesn't exist.```
I then removed the failed deployment using `sls remove` then tried again; I got the same error message.
I initially tried deploying a new stack that I was working on and it failed with the same error message (different role name). __I have not been able to deploy any new stacks.__

* What did you expect should have happened?
Deployment should have succeeded.

* What was the config you used?
Exactly as specified in the Hello World template. I have made no modifications to code or config.

* What stacktrace or error message from your provider did you see?
```HelloLambdaFunction - Template error: IAM role myHelloWorld-dev-us-east-1-lambdaRole doesn't exist.```

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Windows 10 Pro
* ***Stack Trace***:
* ***Provider Error messages***:
```HelloLambdaFunction - Template error: IAM role myHelloWorld-dev-us-east-1-lambdaRole doesn't exist.```

**Comment by a-zharkov** [comment]
I have the same issue with 1.32.0 on linux and osx, when trying to create sqs role for lambda function.

**Comment by markfreeman** [comment]
I'm getting the exact same error this morning:

`Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: UpdateLambdaFunction - Template error: IAM role notes-app-api-prod-us-west-2-lambdaRole doesn't exist.`

**Comment by ejweiler** [comment]
This happens to me as well. I see the role was created in the cloud formation events and then right after the lambdas fail for the role not existing.

**Comment by a-zharkov** [comment]
Maybe this is an issue in AWS, because role creating exists in formation template and it created role.

![stack detail 2018-10-25 18-05-39](https://user-images.githubusercontent.com/3436805/47518061-961b5a80-d892-11e8-861e-cd92a8f0d355.png)

**Comment by a-zharkov** [comment]
Now it works for me. Looks like AWS fixed it.

**Comment by markfreeman** [comment]
Confirmed that it works for me as well. I did have to run 'sls remove' prior to deploying again.

**Comment by DianaIonita** [comment]
Now it works for me too, closing this issue.
