### ISSUE TITLE
Can't install dynamodb "sls dynamodb install"

### ISSUE THREAD

**Issue by arsenal120496** [serverless/serverless#5426]
Serverless Error ---------------------------------------

  Serverless command "dynamodb" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           11.0.0
     Serverless Version:     1.32.0

- I cant install dynamodb through sls command. Anybody help? I add plugins into serverless.yml already.

plugins:
  - serverless-dynamodb-local
  - serverless-offline

**Comment by shanehandley** [comment]
Hi @arsenal120496, if you are having trouble with serverless-dynamodb-local, they have a repo for support here: https://github.com/99xt/serverless-dynamodb-local/issues

But it looks as though the installation command `npm install --save serverless-dynamodb-local` was not performed or failed.

**Comment by pmuens** [comment]
Thanks for opening @arsenal120496 👍

Looks like this is an issue with the `serverless-dynamodb-local` plugin. Please open up an issue in their repository.

**Comment by jackiemunroe** [comment]
I had this issue and just solved it. For posterity, I am putting it here, since this is where the google sent me when I searched for an answer. Installing the plugin with the following command resolved the issue for me:
`serverless plugin install --name serverless-dynamodb-local`

**Comment by majindageta** [comment]
I had this issue too and was a very trivial problem:
the `yml` file should be called `serverless.yml` unless you specify a different name during the "sls dynamodb install" command.

**Comment by oussamabouchikhi** [comment]
> I had this issue and just solved it. For posterity, I am putting it here, since this is where the google sent me when I searched for an answer. Installing the plugin with the following command resolved the issue for me:
> `serverless plugin install --name serverless-dynamodb-local`

And how to run dynamodb? <br/>
I tried `serverless-dynamodb-local start` and `dynamodb start` but both didn't work

**Comment by mdrijwan** [comment]
The solution is you either install it for `serverless.yml`:
```
serverless plugin install --name serverless-dynamodb-local
```

or for a different yml file like `serverless.local.yml`:
```
serverless dynamodb install -c serverless.local.yml
```
