### ISSUE TITLE
Unable to use privately scoped package dependencies

### ISSUE THREAD

**Issue by AdamBarnwell** [serverless/serverless#5429]
# This is a Bug Report

## Description

Unable to package privately scoped packages during the serverless package phase (as part of the deploy workflow).

I have a serverless project which has a number of public NPM dependencies hosted on the NPM registry. This project also has a couple of private scoped NPM dependencies. I run my `npm install` on my CI environment with the following config in the project level `.npmrc` file:

```
@myscope:registry=https://myplatform.jfrog.io/myplatform/api/npm/npm-local/
```

Everything installs fine. I get my public NPM dependencies straight form the NPM registry and my scoped packages (`@myscope`) from my private NPM registry, not a problem.

However, when I then run `serverless deploy`, it builds everything and then begins a packing phase. At this point it stop and errors. I've run the `serverless deploy` command with `DEBUG` and `verbose` on and can see clearly that during this package phase:

```
npm http fetch GET 404 https://registry.npmjs.org/@myscope/myprivaterepo 664ms
```

Obviously, this private package doesn't exist on the public NPM registry as it's only hosted on my private NPM JFrog registry, which then makes the deploy job stop and it can't continue. I expected the `serverless package` to honour the project level `.npmrc` in the same way `npm install` does and therefore it should attempt to get the package from `https://myplatform.jfrog.io...` and not the public NPM registry.

I've literally tried everything but am now officially stuck.

Similar or dependent issues:
None Found

## Additional Data

* Serverless Framework - 1.31.0
* CI - BitBucket Pipeline

**Comment by AdamBarnwell** [comment]
Anyone have an input on this? :-)

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
