### ISSUE TITLE
AWS API gateway Time out for same condition

### ISSUE THREAD

**Issue by mehul21star** [serverless/serverless#5430]
I am using AWS lambda + API Gateway. API is created in .net core.

When i try to call same API it sometimes returns result within 2-3 seconds,while in some time it gives endpoint time error. I am not changing any condition or parameter of API. Everything remains same. still the response time is random. I read in AWS document that there is limitation in API Gateway up to 29 seconds. but this is a awkward behavior i face of API gateway.

I also want to know the reason behind this. why it responds with random time frame.

**Comment by pmuens** [comment]
Thanks for openingg @mehul21star 👍

🤔 this sounds like a cold-start issue with your Lambda functions.

Could you provide more context regarding your project setup so that we can look into that? Thanks 👍

**Comment by pmuens** [comment]
Thanks again for opening @mehul21star 👍

Looks like this issue got quite stale so I'll close it for now. Feel free to re-open if you still face problems with this.
