### ISSUE TITLE
AWS region not taken into account when deploying

### ISSUE THREAD

**Issue by dherault** [serverless/serverless#5434]
Hi fellow Serverless lovers.

In my `serverless.yml` file in have:
```yaml
region: eu-west-3
```
But when I run `serverless deploy` I end up with a different region. --> `https://x.execute-api.us-east-1.amazonaws.com/dev`.

Is this a normal behavior ? How can I have an endpoint at the proper region ?

Happy Halloween,

**Comment by darrenhgc** [comment]
`serverless deploy -r eu-west-3`
