### ISSUE TITLE
Unable to login: site cannot be reached

### ISSUE THREAD

**Issue by 0mars** [serverless/serverless#5436]
# This is a Bug Report

## Description

* What went wrong? unable to login
* What did you expect should have happened? successfull login after filling in the credentials
* What was the config you used?
* What stacktrace or error message from your provider did you see? no trace, the login console keeps listening but the browser cannot resolve the host
Getting 'This site can’t be reached'
The webpage at http://localhost:8000/?code=XXXXXX might be temporarily down or it may have moved permanently to a new web address.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0

* ***Operating System***: Mac OSX High Sierra
* ***Stack Trace***:
* ***Provider Error messages***: This site can’t be reached at http://localhost:8000/?code=XXXXXX

**Comment by 0mars** [comment]
@pmuens I think the problem was that the port was already in use, but it did not complain about that

**Comment by pmuens** [comment]
Great! Thanks for getting back @0mars 👍

Yes, 8000 is a pretty popular port 🤔 😅. Definitely smth. we need to address.

**Comment by pmuens** [comment]
Looks like we have to update this --> https://github.com/serverless/platform-sdk/blob/1c589d1cf431e986b1325e1cbda4baf35bafbbfb/src/login/login.js#L32

**Comment by pmuens** [comment]
Closing this since I just opened https://github.com/serverless/platform-sdk/issues/67 in the `platform-sdk` repo where this issues should be fixed.
