### ISSUE TITLE
sls invoke local process hangs when using async Lambda func

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#5446]
# This is a Bug Report

## Description

* What went wrong?

When using `async` for the Lambda handler func, testing with `sls invoke local` hangs at the end rather than exiting cleanly.

* What did you expect should have happened?

The process should exit.

* What was the config you used?

Not sure what this is referring to specifically.

* What stacktrace or error message from your provider did you see?

N/A

Similar or dependent issues:
* #4912 

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: macOS 10.13.6
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by dschep** [comment]
@pmuens, @ffxsam linked the issue that was supposed to fix it.

I've tried to replicate the issue(the aws-nodejs template uses an async function), but it seems to work as expected. @ffxsam, could you provide an example that reproduces the issue you've described?

**Comment by dschep** [comment]
Also, you're using sls 1.32.x. Please upgrade to fix or confirm this issue still exists.

**Comment by ffxsam** [comment]
Oh, strange. `npm outdated -g` didn't show me that sls was out of date, I wonder why. Now that I'm at 1.36.3, I'll give it another shot. Thanks!

**Comment by ffxsam** [comment]
Yep, fixed! Sorry for the false alarm. 😁

**Comment by ffxsam** [comment]
This seems to be OK now, thanks!
