### ISSUE TITLE
auto configuring a generic lambda function to ping all lambda functions every 10 minutes to prevent cold start

### ISSUE THREAD

**Issue by davidjnelson** [serverless/serverless#545]
I'm wondering if it would make sense to provide a generic lambda function to ping all lambda functions every 10 minutes to prevent cold start.  It could be auto generated based on all the lambda functions that are going to be deployed to a region/stage.  There could also be some generic way for the actual lambda functions to uniformly respond to messages from the "keep alive" auto generated lambda function.  Lambda scheduled tasks could be used to run the auto generated "keep alive" lambda function.

At some number of lambda functions, the auto generated functions would need to be split into multiple auto generated functions to ensure that all real lambda functions got invoked within the 10 minute window.

I'm thinking of implementing this in a prototype app I'm playing with to prevent issue with cold start of lambda containers.  I'd love to hear your feedback and if you think this would be a useful addition to serverless.  Cheers :-)

**Comment by jeremydaly** [comment]
@davidjnelson Not a bad idea. I've seen cold startup times for larger functions take several seconds, while subsequent warm calls complete in less than 200ms. Assuming you built a standard response to a "keep alive" type request, you'd probably reduce that warm execution time down even more.

I think this is something that is detached from Serverless, however. You could deploy the function with your project, but it would make more sense for this to just be a standalone function. Using the AWS-SDK should allow you to just list the functions in a region and then send your "keep alive" request to the appropriate versions with the stage tags.

**Comment by flomotlik** [comment]
I think this would be a great addition as an external plugin. Let us know if you're planning to look into this. I will close this issue for now.

**Comment by pkassonss** [comment]
Was thinking the same thing earlier, but to avoid writing yet another bit of code, there is an event handler that is defined in CloudWatch, which can call any Lambda or other services, and effectively wakeup a frozen lambda.  20 second setup and done.

**Comment by HyperBrain** [comment]
@pkassonss [serverless-plugin-warmup](https://github.com/FidelLimited/serverless-plugin-warmup) is your friend here 😃 . It also works together with other plugins like `serverless-webpack` and `serverless-aws-alias`.
