### ISSUE TITLE
`sls invoke local -e/--env` does not pass environment variables to python runtime

### ISSUE THREAD

**Issue by pydo** [serverless/serverless#5479]
### Description
According to the CLI [documentation](https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/#environment) I can pass environment variables locally to my function using the CLI. I can confirm that his does not work for python runtimes.

**Repro steps**
1. Create basic [serverless.yml](https://gist.github.com/pydo/ed6a19d357ee3305551023c31a71d29a) config
2. Create a simple function that prints an environment variable
```
import time
import os
def hello(event, context):
    time.sleep(100)
    print(os.environ.get('DEBUG'))
```
3. `sls  invoke local -f handler -l -d '{"abc":123}'  -e DEBUG=1`
4. `cat /proc/$(pgrep python -n)/environ | grep -i --binary-files=text debug`
- ^ This command checks all the environment variables associated with the python process ^
- The sleep gives me time to grep the env vars before the process exits

**Expected behavior**
3. Should print `DEBUG` to stdout
4. Should print `DEBUG`  to stdout

**Actual behavior**
3. Prints `None` to stdout
4. Does not log anything to stdout because no string matches

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Linux Ubuntu 18.04

**Comment by dschep** [comment]
This feature isn't in version `1.32.0`. It'll be in the next version however. I'll get the docs site build modified so it's documenting the latest version, not master.

**Comment by pydo** [comment]
Thanks for the quick response and for updating the docs! But aren't the env vars being passed to the child process here https://github.com/serverless/serverless/blob/v1.32.0/lib/plugins/aws/invokeLocal/index.js#L178 ? (not a js guy so I might be missing something)

**Comment by dschep** [comment]
That still works because `process.env` is updated here, before it gets to that line in `invokeLocal`: https://github.com/serverless/serverless/blob/4cf2db57f9372730b50c3ea20de207f90232a7dc/lib/plugins/invoke/invoke.js#L128

closing the issue btw since serverless/site#385 was merged and the docs no longer list this feature.

**Comment by dschep** [comment]
also, I tested it against master and it works as expected, @pydo
