### ISSUE TITLE
base64 encoding: Serverless command "LS12ZXJib3Nl" not found

### ISSUE THREAD

**Issue by jkozera** [serverless/serverless#5491]
# This is a Bug Report

## Description

The following error:

```
Serverless command "ZHluYW1vZGI=" not found. Did you mean "plugin"? Run "serverless help" for a list of all available commands.
```

happens when `serverless --service=foo dynamodb install` is called.

It can also be reproduced with a simpler command like `serverless --no-color --verbose info`, which outputs:
```
Serverless command "LS12ZXJib3Nl" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.
```
## Additional Data

It happens only with the `1.33.0` version, which was released today. It is caused by the changes from https://github.com/serverless/serverless/pull/5361

**Comment by Enase** [comment]
the same for [serverless-mocha-plugin](https://github.com/nordcloud/serverless-mocha-plugin) plugin for example

```
> sls invoke test
Serverless command "invoke test" not found. Did you mean "invoke"? Run "serverless help" for a list of all available commands
```

**Comment by jkozera** [comment]
> the same for [serverless-mocha-plugin](https://github.com/nordcloud/serverless-mocha-plugin) plugin for example

It's a different issue. Sounds like you need to reinstall the plugin? [I've checked and this is what happens when I try to run `invoke test` without having the plugin installed, and after installing it it works even in `1.33.0` without my patch.]

**Comment by Enase** [comment]
@jkozera 
I found the reason and it has nothing to do with any plugin. it relates to options processing.

STEPS TO REPRODUCE:
1. Use any serverless command, e.g. `sls deploy` or `sls invoke local`
2. Add two options in a way when the first option goes without any value and second option set a value. Example: `sls deploy --option1 --option2 optionValue`

Current result:
```
sls deploy --option1 --option2 optionValue
 
  Serverless Error ---------------------------------------
 
  Serverless command "deploy optionValue" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.33.0
```

**Comment by jkozera** [comment]
> I found the reason and it has nothing to do with any plugin. it relates to options processing.

You are right, it was caused by base64 encoding of `--option2`, which then made the parser think that `optionValue` is a subcommand.
