### ISSUE TITLE
Error when the function name exceed a certain longer

### ISSUE THREAD

**Issue by cscetbon** [serverless/serverless#550]
There is an issue when the length of a function's name exceeds a certain length. The error returned is also misleading :

```
Serverless: Enter a new function name:  test1234567890123456
Serverless: Successfully created function: "test1234567890123456"
 [env] $ sls function create -c filerenderer -m file -r python2.7
Serverless: Enter a new function name:  test12345678901234567
error:   Invalid input for Enter a new function name:
error:   Function name must contain only letters, numbers, hyphens, or underscores.
```

**Comment by flomotlik** [comment]
Thanks for reporting, we'll look into this and fix it in an upcoming version

**Comment by tobyhede** [comment]
I am happy to investigate if no-one else has picked this up yet

**Comment by tobyhede** [comment]
I can confirm that this does not happen in the current 1.0 Alpha. 

I have created a Lambda function with the name `test12345678901234561234567890123456-dev-hello`.

**Comment by cscetbon** [comment]
So I guess it has been fixed by the new code.
