### ISSUE TITLE
Update cli examples in documentation to use npx

### ISSUE THREAD

**Issue by softprops** [serverless/serverless#5506]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

It is no longer recommended to install and manage node executables globably. Npm 5.2 ( released in July 2017 ) shipped with a new built in executable called npx which facilitates better practices for installing and running node packaged executables. This facilitates managing serverless as a dev dependency which can more easily be pinned to a target version on a project level.

* If there is additional config how would it look

https://link.medium.com/8G7zaNViZR

Similar or dependent issues:
* This prevents issues like https://github.com/serverless/serverless/issues/4889

I'm willing to open a PR on this but wanted to gauge interest first

**Comment by dschep** [comment]
I think it's a good idea. Feel free to open a PR 👍

**Comment by hom-bahrani** [comment]
Would love to help on this

**Comment by wenindoubt** [comment]
Setting up a brand new project to have `npx` use the `serverless` CLI is kind of janky at the moment.

If you follow these steps:

```
$ mkdir new-serverless-proj
$ cd new-serverless-proj
$ npm init -y
$ npm install --save-dev serverless
$ npx serverless create --template aws-nodejs-typescript
```

You will get the following error:

```
Serverless: Generating boilerplate...

  Serverless Error ---------------------------------------

  The file "package.json" already exists, and serverless will not overwrite it. Move the file and try again if you want serverless to write a new "package.json"

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.3
     Framework Version:         1.57.0
     Plugin Version:            3.2.3
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

To work around this and still use `npx` to invoke the `serverless` CLI, create your project in a sub-directory:

```
$ npx serverless create --template aws-nodejs-typescript --path my_api
```

Change into your `my_api/` directory and re-install `serverless` as a devDependency:

```
$ cd my_api/
$ npm install --save-dev serverless
```

Now - to clean things up, remove the following from the **top-level directory**:

```
$ cd ../
$ rm -rf node_modules/ package.json package-lock.json
```

You should be left with this:

```
new-serverless-proj
└── my_api
    ├── handler.ts
    ├── package.json
    ├── serverless.yml
    ├── tsconfig.json
    ├── vscode
    │   └── launch.json
    └── webpack.config.js
```

**Now** - when you navigate into your `my_api/` directory, you can run your `serverless` commands with `npx`.

**Comment by medikoo** [comment]
Closing as after we've introduced a _local fallback mechanism_ (where global installation of `serverless` will invoke one that's installed in local `node_modules` if it's found), having globally installed `serverless` in all cases is preferred (and documentation should refer to that).

Problem with `npx` is that it'll install`serverless` in some temporary folder (if it's not found neither locally or global)  and going that way is not efficient
