### ISSUE TITLE
Enhancement: Multiple Test Cases for `function run`

### ISSUE THREAD

**Issue by byron70** [serverless/serverless#551]
Like to see a feature where event.json could be specified as an array of objects with the testing parameters and values.  

This would be good for patterns where you have multiple endpoints being services by one lambda handler. 

It would be good if these could maybe be name, so you could run all or a single set of tests. 

`function run test1 test2 ....`

`{[
{ "test1" : { "httpmethod": "GET", "id": "123" }},
{ "test2" : { "httpmethod": "GET", "id": "badID" }},
.....
]}`

Alternate pattern would maybe be to name the event.json with a prefix of the test name.

test1.event.json
test2.event.json

This may be a bit more readable. 

Yet another pattern may be to have a _test folder within your Serverless project, which could house individual JSON files with all the parameters for executing any given function, so you would not need to run a function from within the function folder. 

Many options for the design.

**Comment by eahefnawy** [comment]
More discussion of this issue has been done in #576 ... Closing this one for now. 

Thanks for reporting @byron70 and sorry for the late reply :/ ... we've been busy on a big refactor and a new release is coming soon :)
