### ISSUE TITLE
Python 3.7 runtime not supported

### ISSUE THREAD

**Issue by revmischa** [serverless/serverless#5526]
https://aws.amazon.com/blogs/compute/python-3-7-runtime-now-available-in-aws-lambda/

If I specify python3.7 as my runtime and do a local invoke I get the error:

`  You can only invoke Node.js, Python & Java functions locally.`

**Comment by softprops** [comment]
Support for this was merged [about a week ago](https://github.com/serverless/serverless/pull/5505). It hasn't been rolled up into [a release](https://github.com/serverless/serverless/releases) yet. Expect it in 1.33.3 or later
