### ISSUE TITLE
Handling of operationId field

### ISSUE THREAD

**Issue by zannis** [serverless/serverless#5530]
Hello, on nodejs services, I make extensive use of the "operationId" field that is part of the OpenAPI specification. When deploying services to AWS using serverless, I set the field under s-functions.json like so:

```
...
"events": [
        {
            "http": {
                "path": "/token",
                "method": "get",
                "cors": true,
                "operationId": "getToken",
                "documentation": {
                    "summary": "Returns a JWT token",
                    "description": "Returns a JWT token",
                    "requestBody": {
                        "description": "Not required"
                    },
                    "methodResponses": [
                        {
                            "statusCode": "200",
                            "description": "OK",
                            "responseBody": {
                                "description": "token for using services"
                            },
                            "responseModels": {
                                "application/json": "AccessTokenResponse"
                            }
                        }
                    ]
                }
            }
        },
...
```

However, the operationId field is not pushed to AWS API Gateway when the service is deployed using serverless. The issue is only reproducible on serverless deployments, that's why I'm opening the issue here. So the question is, since I couldn't find a reference to, am I using the framework wrong or is the operationId field no supported yet on serverless?

**Comment by zannis** [comment]
Hmm, actually I'm working on a project that is using serverless 0.7.2 which
I then upgraded to 1.1.0 in an attempt to resolve the {{operationId}} issue
but kept the {{s-functions.json}} configurations as references in my
{{serverless.yaml}}.

Does that mean that ^1.0.0 versions support the {{operationId}} field under
a different configuration? If so, please advise because I couldn't find any
information so far.

**Comment by zannis** [comment]
Kind bump :) Could you please provide some further info on the topic?

**Comment by dschep** [comment]
I don't think it's currently supported by the framework. I'd be happy to merge a PR adding it. I don't think it should be too difficult. I was gonna suggest a starting point (regardless, it'll be i somewhere in [`lib/plugins/aws/package/compile/events/apiGateway`](https://github.com/serverless/serverless/tree/master/lib/plugins/aws/package/compile/events/apiGateway)) but I can't find the API Gateway CFN docs for this option? Is it on [`AWS::ApiGateway::Method`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html) or elsewhere

**Comment by zannis** [comment]
Hello @dschep, in response to your question, I contacted the AWS Support for official advice on how to handle this and will update this issue as soon as I have solid input from their side.

**Comment by zoellner** [comment]
Just happened to look into this as well. If it's of any help, the operationId is mapped to the operationName of the method when importing from a swagger file
see https://docs.aws.amazon.com/apigateway/api-reference/resource/method/#operationName

**Comment by pmuens** [comment]
Closing since this issue has been resolved. Feel free to continue the dicussion.
