### ISSUE TITLE
Regression: Serverless 1.33 does not properly support integers as external values

### ISSUE THREAD

**Issue by Jaystified** [serverless/serverless#5534]
# This is a Bug Report

## Description

* What went wrong? 
A `logRetentionInDays should be an integer over 0` error interrupts deployment when the logRetentionInDays value is provided externally (in my case via a shell command)
* What did you expect should have happened? 
Externally provided integer is properly interpreted and deployment completes successfully.
* What was the config you used? 
Trying to deploy a 60-day expiration log retention lambda to AWS.
* What stacktrace or error message from your provider did you see?
`logRetentionInDays should be an integer over 0`
Node version is 8.10.0

Similar or dependent issues:
[This forum post](https://forum.serverless.com/t/variables-from-external-javascript-file-seem-to-be-internally-cast-to-string/5792)
[This stackoverflow post](https://stackoverflow.com/questions/49645453/using-ssm-parameter-to-set-logretentionindays-in-serverless-yml?rq=1)
Not mine, but assuming same issue

## Additional Data

* ***Serverless Framework Version you're using***: 1.33.[0,1,2] (Error occurs in all three versions. 1.32 and earlier work as expected.)
* ***Operating System***: Linux (Xubuntu 18.04)
* ***Stack Trace***: 
* ***Provider Error messages***:  `logRetentionInDays should be an integer over 0`

**Comment by dschep** [comment]
Could you provide the relevant parts of your `serverless.yml` please?

**Comment by dschep** [comment]
Ah.. What if you do:
```
  logRetentionInDays: ${opt:logRetentionInDays, self:custom.defaultLogRetentionInDays}
```
(remove the quotes)

**Comment by dschep** [comment]
Tho I wouldn't expect `${opt:logRetentionInDays}` to work :disappointed: I'm not sure how this is dealt with for other options that must be integers. IMO because of the `${opt:adsflajdf}` feature (and other variable sources like SSM) it makes sense to attempt to cast values to the right type. Thoughts @pmuens @eahefnawy @horike37?

**Comment by Jaystified** [comment]
Confirming that removing the quotes does not change the outcome.

Was the `${opt:adsflajdf}` feature modified in `1.33`?

**Comment by dschep** [comment]
does `logRetentionInDays: ${self:custom.defaultLogRetentionInDays}` alone with an integer at `custom.defaultLogRetentionInDays` work? I don't think the opt option has ever coerced values to different types :/

**Comment by Jaystified** [comment]
Yes, `${self:custom.defaultLogRetentionInDays}` alone does work (as does the full line when the var isn't provided).
Since the original serverless.yml did work as-is in previous versions, the variables were coerced somehow at some point :\

**Comment by dschep** [comment]
Thanks for the details @Jaystified
