### ISSUE TITLE
Neptune DB instance error after sls deploy

### ISSUE THREAD

**Issue by chriscarex** [serverless/serverless#5537]
# This is a Bug Report

## Description

* What went wrong?
Trying to generate a Neptune DB running sls deploy, got an Invalid master password error
Adding MasterUserPassword, gives a Encountered unsupported properties in {/}: [MasterUserPassword error

* What did you expect should have happened?
There should have been no error and the NeptuneDB should have been generated (the serverless user has all admin rights at the moment)

* What was the config you used?
The serverless.yml is generating SNS and S3 buckets with no problems so there is no reason for posting the entire file 

Without Master Password:

Resources:
  testName:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.r4.large
      DBInstanceIdentifier: testName

With master.password

Resources:
  testName:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.r4.large
      DBInstanceIdentifier: testName
      MasterUserPassword: whatever

* What stacktrace or error message from your provider did you see?
Without master password:
An error occurred: PbClassifyNeptuneDB - Invalid master password (Service: AmazonNeptune; Status Code: 400; Error Code: InvalidParameterValue; Request ID: bc5c51fd-357b-4d4f-bd44-7d610570c2f7).

With master password:
Property validation failure: [Encountered unsupported properties in {/}: [MasterUserPassword]

## Additional Data

* ***Serverless Framework Version you're using***:
1.33.2

* ***Operating System***:
MacOS Mojave

**Comment by dschep** [comment]
Hmm.. I don't see any password properties in the docs for Neptune+CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbinstance.html#aws-resource-neptune-dbinstance-prop

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.

**Comment by PatMyron** [comment]
misleading error message if anyone else is running into this, setting the [`DBClusterIdentifier`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbinstance.html#cfn-neptune-dbinstance-dbclusteridentifier) property circumvents this:

```yaml
Resources:
  DBCluster:
    Type: AWS::Neptune::DBCluster
  DBInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.r5.xlarge
      DBClusterIdentifier: !Ref DBCluster
```
