### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by jagthedrummer** [serverless/serverless#5540]
# This is a Feature Proposal

## Description

With the release of Ruby as a supported run-time for lambda it would be great to have support for it in serverless.

https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/

Similar or dependent issues:
* #5476 might be related, but seems to be asking about something different than the native Ruby support that AWS just announce.

**Comment by dschep** [comment]
Yup! We definitely should support all the new runtimes announced. #5476 isn't particularly related since it's for openwhisk, not aws.

**Comment by dschep** [comment]
I've created a PR for the template & made an issue for invoke local support. But! you can already use it! Use `sls create -t aws-nodejs` and then replace `runtime: nodejs8.10` in `serverless.yml` with `ruby2.5` and then create a handler based off of the `handler.rb` in the PR: https://github.com/serverless/serverless/blob/09f7b10594b6b1b5f58be744239ee4d519b5d70c/lib/plugins/create/templates/aws-ruby/handler.rb

**Comment by jagthedrummer** [comment]
Awesome, @dschep! I'll give it a try.

**Comment by j105** [comment]
Any chance you guys figure out how to include gem "pg". It's a native extension.

**Comment by dschep** [comment]
@j105 I recommend a combination of docker (with the [docker-lambda images](https://github.com/lambci/docker-lambda/)) to compile it and then maybe publish it as a [layer](https://serverless.com/blog/publish-aws-lambda-layers-serverless-framework). You might be able to use my SQLite native python extension layer as a starting point: [dschep/sqlite-lambda-layer](https://github.com/dschep/sqlite-lambda-layer) (check out the `build.sh` and `Dockerfile` in that project)

More generally, I don't really know how packaging with ruby works and if it'll be as straight forward as nodejs deps with serverless or justify the development of a plugin like [`serverless-python-requirement`](https://github.com/UnitedIncome/serverless-python-requirements)

**Comment by jagthedrummer** [comment]
Holy smokes, y'all are fast! 🤘

**Comment by j105** [comment]
@dschep awesome, works well. thanks for those info.

**Comment by j105** [comment]
@dschep thanks for helping.

I created a simple repo to demo how to include a native gem for ruby

https://github.com/DevHubCo/ruby-pg-lambda
