### ISSUE TITLE
Ruby Invoke Local support

### ISSUE THREAD

**Issue by dschep** [serverless/serverless#5545]
# This is a Feature Proposal

## Description
We should support `sls invoke local` for ruby.

Similar or dependent issues:
* #5540 - initial request for ruby support
* #5544 - PR implementing a ruby template

**Comment by rupakg** [comment]
@dschep are you working on this issue?

**Comment by dschep** [comment]
I am not. I don't really know enough ruby to do this quickly & confidently.

**Comment by rupakg** [comment]
@dschep I guess @dholdren got to it first. Nice work. I just added a few comments to the PR.
