### ISSUE TITLE
Lambda Layers support

### ISSUE THREAD

**Issue by ericofusco** [serverless/serverless#5548]
# This is a Feature Proposal

AWS released a feature called Lambda Layers to share code across multiple functions.

https://aws.amazon.com/blogs/aws/new-for-aws-lambda-use-any-programming-language-and-share-common-components/

With this feature available we can simplify the packaging process by just adding layers to functions.

**Comment by dschep** [comment]
Yup. What @evgenykireev  said. Update to v1.34.0 for that.

**Comment by ericofusco** [comment]
Nice! I'm glad the feature was ready for the release. Thank you, great job!
