### ISSUE TITLE
Silent completion on missing serverless.yml

### ISSUE THREAD

**Issue by jspri** [serverless/serverless#5569]
# This is a Bug Report

## Description

* What went wrong?

I ran `sls package` or `sls deploy` in a folder with no `serverless.yml`. There was no output to indicate that I had made a mistake.

* What did you expect should have happened?

The program should exit with an error code and output that a config file can not be located.

* What was the config you used?

Go to an empty directory or a subfolder of a serverless project. Run `sls package`.

```bash
sls deploy --verbose
Serverless: Packaging service...
Justins-MBP:foo justin$
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.34.1
* ***Operating System***: OSX Mojave

**Comment by dschep** [comment]
I've also run into this. Not sure when that stopped printing out an error 🤔

**Comment by shanehandley** [comment]
I can't reproduce this. I think this PR fixed it about a month after this report:

https://github.com/serverless/serverless/pull/5636
