### ISSUE TITLE
Check handlers exist

### ISSUE THREAD

**Issue by Crazometer** [serverless/serverless#5570]
# This is a Feature Proposal

## Description

Running `sls package` or `sls deploy` should alert the user if their chosen handler does not exist. Typos eg `handler: wrongfile.wrongfunction` should be detected where possible.

The reason for this is I want to be able to do basic checks that my `serverless.yml` is correct on CI.

**Comment by dschep** [comment]
That's a good idea, but a bit tricky to implement as it's different for ever language.

**Comment by exoego** [comment]
I think this issue duplicates #3758.

**Comment by Crazometer** [comment]
Yup! Thanks.
