### ISSUE TITLE
module initialization error: Error

### ISSUE THREAD

**Issue by A-Atrash** [serverless/serverless#5590]
Hello, 
I'm getting this error but I'm not able to relate to any of the solutions proposed for it anywhere here:
> module initialization error: Error
>   at Error (native)
>   at Object.Module._extensions..node (module.js:597:18)  
>   at Module.load (module.js:487:32)
>   at tryModuleLoad (module.js:446:12)
>   at Function.Module._load (module.js:438:3)
>   at Module.require (module.js:497:17)
>   at require (internal/module.js:20:19)
>   at bindings (/var/task/node_modules/bindings/bindings.js:84:48)
>   at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:34)
>   at Module._compile (module.js:570:32)

It's in a Node app with TypeScript in Lambda. It was working well with 'Canvas' package installed but when I needed to add image validation using the package 'ImageMagick' I started getting this error. 

My serverless.yml and package.json: https://github.com/A-Atrash/forfilesharingtohandleerror

Can you help please?

**Comment by Botre** [comment]
I have encountered this issue twice, yesterday and today, across two different projects.

This is what fixed it for me.

- Update to the latest serverless version

- Make sure the depedency in question is not declared inside "devDependencies", as those are excluded during packaging.

- Delete your package-lock.json and node_modules and run "npm install"

- Redeploy the function

**Comment by A-Atrash** [comment]
@Botre Thanks for the answer! I actually ran some tests and realised that a dependency is causing the error. The dependency is sharp:
```
{
  "errorMessage": "/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)",
  "errorType": "Error",
  "stackTrace": [
    "Object.Module._extensions..node (module.js:597:18)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "bindings (/var/task/node_modules/bindings/bindings.js:84:48)",
    "Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:34)",
    "Module._compile (module.js:570:32)"
  ]
}
```
Any idea?

**Comment by dschep** [comment]
Thanks for the input @Botre. Have you tried that @A-Atrash

**Comment by A-Atrash** [comment]
@Botre Thank you! 
@dschep Yes I tried what Botre said. What he said solved a problem I used to have before this problem. But this problem turned out to be because of a weird dependency that requests to be imported first before other dependencies, and the reason is that it changes something in a common sub-dependency. I ended up removing it and using an alternative. Now it is solved.
Thanks!
