### ISSUE TITLE
Unable to create pass-through endpoints

### ISSUE THREAD

**Issue by jeremydaly** [serverless/serverless#560]
AWS API Gateway gives you the ability to create "pass-through" endpoints that simply relay your API call to another external API. You can manipulate both the "request" and the "response" objects using Apache velocity templates. This is a great way for you to merge multiple service APIs into a single, unified interface, or to "patch" an existing API with new endpoints that map to Lambda functions by creating pass-throughs to endpoints that haven't been converted yet.

Serverless only allows you to map endpoints to your lambda function in the s-function.json file. It would be great if Serverless had a method of creating pass-through endpoints that didn't map to Lambda functions allowing you to maintain (and recreate) your entire API. Perhaps this could live in the s-project.json file?

**Comment by doapp-ryanp** [comment]
I'd like this feature too.  [aws-apigateway-importer](https://github.com/awslabs/aws-apigateway-importer) uses ["type":"http"](https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/swagger/apigateway.json#L186) to indicate this, so serverless could do something similar.

**Comment by flomotlik** [comment]
In an upcoming version you will be able to create resources directly through cloudformation which will support this. I will close this issue as this use case will be handled in the future.
