### ISSUE TITLE
Parent paths no longer working for package inclusions/exclusions

### ISSUE THREAD

**Issue by dpecos** [serverless/serverless#5600]
# This is a Bug Report

## Description

* What went wrong?

I have my `serverless.yml` in a subfolder of my repo, and it's pointing to files to include / exclude in one of its parent folders. This used to work, but not anymore since version 1.35.0

* What did you expect should have happened?

To work as with previous version (1.34.1)

* What was the config you used?

```
package:
  exclude:
    - ./**
  include:
    - ../../bin/api_**
    - ../../bin/internal_**
```

* What stacktrace or error message from your provider did you see?
```
$ sls package                                                
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  No file matches include / exclude patterns

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.13.0
     Serverless Version:     1.35.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.0
* ***Operating System***: MacOSX
* ***Stack Trace***: -
* ***Provider Error messages***: No file matches include / exclude patterns

**Comment by dschep** [comment]
That's likely a regression caused by #5574. Any chance you could take a look at this @MacMcIrish? Would it be possible to have all the includes on [this line](https://github.com/MacMcIrish/serverless/blob/23c37b7543238e4a98ab605c2cf8146a3095bcce/lib/plugins/package/lib/packageService.js#L191) with out causing the performance issues?

**Comment by vicpon** [comment]
Also have the same issue. This broke our production site for a bit until we realized what had happened. We upgraded from 1.32 because of performance issues with dependencies (package was taking 12-30min). 1.35 didn't have that issue but this happened.

**Comment by MacMcIrish** [comment]
@dschep it's for sure a regression, I'd be happy to have a look :) including files outside the current directory was not a use case I foresaw.
As far as I've seen, the include pattern list is not dynamically generated, so adding it there _should not_ cause any performance issues, so your solution should work. I'll go ahead and create a PR and see about setting up a test case around including files that are outside the project directory.

**Comment by dschep** [comment]
Thanks! Yeah, I didn't realize it was a supported use case either.

**Comment by MacMcIrish** [comment]
@dpecos @vicpon I've created a PR for this (seen above), would you mind pulling it in and taking a look to see if this solves both of your use cases? It's small enough you should even be able to easily modify the file locally :)

**Comment by dpecos** [comment]
I've tested locally and works great! 

Thx a lot!
