### ISSUE TITLE
Variables/Templates substitution should be handled for plugins

### ISSUE THREAD

**Issue by cscetbon** [serverless/serverless#561]
Currently, there is no substitution of variables for plugins. It means that a plugin gets a string like `"$project-blabla"` and no `"myproject-blabla"` if project is defined as **myproject** in `_meta/variables/s-variables-common.json`

**Comment by ac360** [comment]
Thanks @cscetbon.  All plugins can access the class instances for project assets which expose `get()` or `getPopulated()` methods.  It is up to the plugins whether they want the unpopulated data, or the populated data.  There is value in being able to get both, and it's easy.  [More info on that here](http://docs.serverless.com/v0.4.0/docs/state)
