### ISSUE TITLE
Where to find tenant name?

### ISSUE THREAD

**Issue by daryn-k** [serverless/serverless#5612]
What is tenant name and where to find it?

**Comment by garethmcc** [comment]
@daryn-k This is only needed if you plan on having your services register themselves with the Serverless Dashboard (dashboard.serverless.com). Otherwise its not needed.

**Comment by dschep** [comment]
@garethmcc is correct. Are you using the dashboard, @daryn-k?

**Comment by daryn-k** [comment]
Yes, you're right. I'm using serverless first time. It requires some "tenant" everytime. Now I know the reason on this problem.
