### ISSUE TITLE
Support for Websockets on AWS

### ISSUE THREAD

**Issue by dested** [serverless/serverless#5615]
# This is a Feature Proposal

## Description

* Support for the new API Gateway websocket routing

Similar or dependent issues:

Do you see this as something that Serverless core will handle directly or can it be built better as a plugin? Is this currently on the roadmap?

**Comment by dschep** [comment]
CloudFormation is not available for this yet, but we are working on a plugin. Keep an eye on our twitter account & blog where we'll announce it's release when ready. I Will leave this open however, because we do want to bring that into core once CFN supports it.

**Comment by dschep** [comment]
And it's available now!! https://serverless.com/blog/api-gateway-websockets-example/

**Comment by hotgazpacho** [comment]
AWS now allows you to configure via CloudFormation: https://aws.amazon.com/about-aws/whats-new/2019/02/automate-websocket-api-creation-in-api-gateway-with-cloudformation/

**Comment by dschep** [comment]
@hotgazpacho et al, @eahefnawy is working on this in #5824

**Comment by eahefnawy** [comment]
UPDATE: the PR is now ready for testing. I've added some validation steps in the PR description, and would love feedback from anyone in the community! Feel free to test it out!
