### ISSUE TITLE
Plugins list should be possible to provide via configuration file when starting serverless-offline

### ISSUE THREAD

**Issue by ovirta** [serverless/serverless#5622]
# This is a Feature Proposal

## Description

* There are several serverless.yml variables that can be parametrized from commandline options or from configuration files. Unfortunately plugins list can not be provided in such manner when running serverless-offline.

* Our plugins section in serverless.yml looks like following:
```
plugins:
    - serverless-plugin-scripts
    #- serverless-offline
```

To debug locally we need to remove the comment from serverless-offline. It would be a great benefit if we could to it in via config files that we have for local, dev, test and prod work.  We are often pushing this modified serverless.yml file to repository creating unnecessary problems.

This is the proposal:

```
plugins:
    ${{file(./config/config-${{opt:stage}}.js):pluginsList}}
```
config-local.js would have following export:
```
module.exports.pluginsList = () => {
  return [
    'serverless-plugin-scripts',
    'serverless-offline'
  ];
};
```
and the rest would return 
```
module.exports.pluginsList = () => {
  return [
    'serverless-plugin-scripts'
  ];
};
```

Currently when using the proposed approach serverless responds with error:
```
>node --inspect-brk ./node_modules/serverless/bin/serverless offline -s local

  Serverless Error ---------------------------------------
 
  Serverless command "offline" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.
 
  Stack Trace --------------------------------------------
 
ServerlessError: Serverless command "offline" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.
    at _.reduce (C:\Users\trestromol\iop\backend-container\node_modules\serverless\lib\classes\PluginManager.js:352:13)
    at arrayReduce (C:\Users\trestromol\iop\backend-container\node_modules\lodash\lodash.js:683:21)
    at Function.reduce (C:\Users\trestromol\iop\backend-container\node_modules\lodash\lodash.js:9683:14)
    at PluginManager.getCommand (C:\Users\trestromol\iop\backend-container\node_modules\serverless\lib\classes\PluginManager.js:340:14)
    at PluginManager.validateCommand (C:\Users\trestromol\iop\backend-container\node_modules\serverless\lib\classes\PluginManager.js:430:10)
    at Serverless.run (C:\Users\trestromol\iop\backend-container\node_modules\serverless\lib\Serverless.js:107:24)
    at serverless.init.then (C:\Users\trestromol\iop\backend-container\node_modules\serverless\bin\serverless:44:28)
    at <anonymous>
From previous event:
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at C:\Users\trestromol\iop\backend-container\node_modules\serverless\bin\serverless:29:46
    at Object.<anonymous> (C:\Users\trestromol\iop\backend-container\node_modules\serverless\bin\serverless:66:4)
    at Module._compile (module.js:650:14)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.12.0
     Serverless Version:     1.34.1
```

What is bit inconsistent is that when creating a package it is possible to include plugins via configuration file as proposed.
```
>npx sls package --stage local
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```
./serverless/serverless-state.json -file contains following lines after package is created.
```
    "plugins": [
      "serverless-plugin-scripts",
      "serverless-offline"
    ],
```

**Comment by ovirta** [comment]
Serverless-offline creator @dherault commented on the case: 
https://github.com/dherault/serverless-offline/issues/563#issuecomment-452297059


> Yes the plugin is loaded by the Serverless framework but is only used with CLI. So serverless-offline will not cause any problem during lifecycles of your application. So it is loaded, but never used during deployment, bundling, etc...

We are happy with this comment and will leave serverless-offline in the yaml file until a there is a straightforward way to include it depending on e.g. stage.

**Comment by exoego** [comment]
As far as I tested, severless 1.3.61 already supports [nesting variable](https://serverless.com/framework/docs/providers/aws/guide/variables#nesting-variable-references).

The proposed syntax `${{file(./config/config-${{opt:stage}}.js):pluginsList}}` seems invalid.  
It should be `${file(./config/config-${opt:stage}.js):pluginsList}`

Suppose we have `severless.yml`

```yml
service:
  name: test
provider:
  name: aws
  runtime: nodejs8.10 
plugins: ${file(./${opt:stage}.yml):pluginsList}
functions:
  functionA:
    handler: handler.hello
``` 

and `dev.yml`


```yml
pluginsList:
  - serverless-plugin-scripts
  - serverless-offline
```

Then, `sls print` works at least.
`plugins` are populated from the external file.

```bash
$ sls print --stage dev
service:
  name: test
provider:
  name: aws
  runtime: nodejs8.10
plugins:
  - serverless-plugin-scripts
  - serverless-offline
functions:
  functionA:
    handler: handler.hello
```

**Comment by exoego** [comment]
But yes, `sls offline --stage dev` or similar seem not work.

**Comment by marcelpanse** [comment]
> Then, `sls print` works at least.

It works for sls print, but doesn't work when actually running anything. It seems the plugins are loaded before any includes happen. 

I currently have the same problem, where I want to load certain plugins only for certain regions I deploy to and now I have to manually comment/uncomment them before deploying...

**Comment by medikoo** [comment]
Closing, as with new variables resolver it's possible to configure `plugins` section behind variabels
