### ISSUE TITLE
sls cannot create buckets from resources section: <bucketname> already exists

### ISSUE THREAD

**Issue by bresheske** [serverless/serverless#5632]
# This is a Bug Report

## Description

* What went wrong?
Serverless cannot deploy even with a very simple "create a bucket with a custom name" configuration.

* What did you expect should have happened?
Serverless should create a bucket with a custom name.

* What was the config you used?
package.json:
```
{
  "name": "stupid",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "deploy": "sls deploy -s dev",
    "clean": "sls remove"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "^1.35.1"
  }
}
```

serverless.yml:
```
service: stupid

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2

resources:
  Resources:
    MahBukkit:
      Type: AWS::S3::Bucket
      Properties:
        # note - it doesn't matter what you change this to, it will always "already exist"
        BucketName: mahbukkit

package:
  exclude:
    - "**"
```

* What stacktrace or error message from your provider did you see?

## Additional Data

*Error messages*

```
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: MahBukkit - mahbukkit already exists.
```

*When changing the name to something else:*
```
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: MahBukkit - hihihi already exists.
```

**Comment by dschep** [comment]
> `# note - it doesn't matter what you change this to, it will always "already exist"`

change to any bucket that exists, or anything? Because I changed it to `mahbukkit-test` and it deployed just fine.

**Comment by bresheske** [comment]
@dschep Thanks for the feedback - I changed it to include "-test" and cloudformation has been creating the bucket for the last 10 minutes.... hopefully won't take too long here.

![image](https://user-images.githubusercontent.com/4560428/50520999-0c9e2980-0a89-11e9-88ab-aecaff89545e.png)

**Comment by dschep** [comment]
yup, that's one of the downsides of s3 :(
