### ISSUE TITLE
_meta directory no longer ignored

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#564]
In [this commit](https://github.com/serverless/serverless/commit/66816804c800d07d8d0b10309790f44694759022) was the git ignore of _meta supposed to be removed? The docs at http://docs.serverless.com/docs/templates-variables still say "the _meta folder is gitgnored by default" so not sure if this was intended or just a documentation issue.

**Comment by pmuens** [comment]
There was a discussion about the _meta folder:
https://github.com/serverless/serverless/issues/491

I think that it should be ignored because it it includes account specific values (the account id in "iamRoleArnLambda"). And as mentioned in #491 you could recreate the project with the help of the `project install` command.

**Comment by c-knowles** [comment]
If it's ignored I think a higher level project init may be needed which just takes the AWS profile and the bucket name and then recreates all the existing ARNs/stages etc. Projects are slightly less shareable when there is no way to easily recreate all of that. Unless of course the new project init command succeeds if one tries to create a stage/region/domain combination that already exists and happens to already know all the stage names. Not tried it quite yet so wondering if that's how it works or not.

**Comment by doapp-ryanp** [comment]
I personally do not think `_meta` should be `.gitignore`d because it prohibits team(s) of people working on a serverless proejct.

Instead I think development stages should be ignored.  Stages such as `prod` should not be ignored because a team of people will need to collaborate on it.

I have encapsulated this in https://github.com/serverless/serverless/pull/684

**Comment by ruhkopf** [comment]
In our setup, the team shares the `dev` stage. But team members can create their own stages, as described in [Creating-your-project-stages](http://docs.serverless.com/docs/workflow#creating-your-project-stages). Personally I think it would be ideal to ignore those local/person stages. Not sure how to implement this, though. Maybe differentiate between "local" stages and "shared" stages?

The issue that I see with just ignoring `dev` is that if 2 people share the same AWS account and they both work on `dev`, they will still end up sharing resources. This might be confusing...

**Comment by doapp-ryanp** [comment]
@ruhkopf if you team needs to share development stages, just name them something that does not start with `dev`. Ex: `newFeatureDev`

IMO using convention will avoid a bunch of un-needed configuration complexity AND will provide standardization (you hire new employee who is familiar with Serverless, they will know stages that start with `dev` are gitignored)

**Comment by ruhkopf** [comment]
@doapp-ryanp  Sure, a convention sounds good. This would work for us. My point was more about the need to ignore multiple stages, not just one single `dev`. But I can see you already have that covered in you PR #684. :+1:

**Comment by doapp-ryanp** [comment]
I gotcha. I should have been more explicit on my note in this thread, so people would not have to dive in to my PR.

In short the PR gitignores `_meta/**/*-dev*` will prevent the tracking of the metadata of stages that start with `dev`.

This will give the flexibility for teams to collaborate on projects while also being able to have ones that are not shared.  This technique will allow for a straight forward convention based mechanism vs a more complex (and less standardized) configuration mechanism.

**Comment by ac360** [comment]
FYI In `v0.5` we removed the auto-creation of the *dev* stage.  We also now have support for separate AWS Profiles for each stage.  @doapp-ryanp This PR looks good.  I'm just going to add it into v0.5 real quick.
