### ISSUE TITLE
AWS Lambda Layer package files missing first character in their name

### ISSUE THREAD

**Issue by s16h** [serverless/serverless#5646]
When adding layer path to `serverless.yml`, if the path ends in `path.sep` (e.g. `/`), then when the files are packages, they all miss their first character.

This is because in https://github.com/serverless/serverless/blob/c826183eefa96546ef853d2574dff6ddcd6e36b5/lib/plugins/package/lib/zipService.js#L86 there's an assumption that the layer path doesn't have a `path.sep` already.

Perhaps that line can change to something like, to be more forgiving:

```js
const prefixHasSep = prefix.endsWith(path.sep);
const prefixWithoutSep = prefixHasSep ? prefix.slice(0, -1) : prefix;
const name = file.filePath.slice(prefix ? prefixWithoutSep.length : 0);
```

**Comment by dschep** [comment]
Good catch! I've created a PR fixing this. Didn't quite take the same approach. Could you check that it's fixed for you too with this? `npm i serverless/serverless#sls-5646`

**Comment by angryzor** [comment]
This also happens when you use `.` as the path for a layer, but then it removes the first 2 letters.

**Comment by khalilgharbaoui** [comment]
No really flexible instead of:

```
layers:
  hello:
    path: ./vendor
```
we are forced to do:

```
layers:
  hello:
    path: vendor
```
This not really a path...
It also does not like hidden files starting with a `.` 
Hope this helps someone, it took me a while to figure out!

**Comment by dschep** [comment]
Hey all, I've updated #5656 to address these various issues. You can test it with:
```
npm i -g serverless/serverless/#sls-5646
```
