### ISSUE TITLE
serverless-http: Unsupported Framework Error

### ISSUE THREAD

**Issue by Rajan** [serverless/serverless#5672]
# This is a Bug Report
Yes
## Description
Getting Unsupported Framework error.
* What went wrong?
Unable to initialize serverless-http module for some reason.

* What did you expect should have happened?
Expected to run the `sls offline` an app which directly works with `npm run dev`

* What was the config you used?
Nuxt+AWS Lambda with serverless.yml (all latest version)

* What stacktrace or error message from your provider did you see?

Not much but the file is attached.

Similar or dependent issues:
* #12345
<img width="573" alt="screenshot 2019-01-10 at 7 08 35 pm" src="https://user-images.githubusercontent.com/60307/50972091-acd56300-150b-11e9-9cc0-530f883c6c78.png">

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.1
* ***Operating System***: MacOS Mojav 10.14
* ***Stack Trace***: Attached
* ***Provider Error messages***: Unsupported Framework

**Comment by dschep** [comment]
This is more likely an issue with one of the plugins

**Comment by julian-linux** [comment]
any update about this?
