### ISSUE TITLE
Setting --profile or --aws-profile keeps stack from getting deployed from version 1.36.0

### ISSUE THREAD

**Issue by bweigel** [serverless/serverless#5673]
# This is a Bug Report

## Description

* What went wrong?

Using `serverless deploy --aws-profile xyz` or `serverless deploy --profile xyz` keeps stack from getting deployed in version **1.36.0**. (works in version 1.35.1)
Serverless stops just after the sts-assumerole-call was made:

```
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS sts 200 0.546s 0 retries] assumeRole({ RoleArn: 'arn:aws:iam::012345678912:role/xyz',
  RoleSessionName: 'aws-sdk-js-1547158630501' })
```

see details below.

* What did you expect should have happened?

Should still work the same as in version 1.35.1 (i.e. stack deployment to AWS via Cloudformation)

* What was the config you used?

**serverless.yml**
```yml
service: bugs-serverless-issue-5474

provider:
  name: aws
  runtime: python3.6
  # profile: ${opt:profile}
  region: eu-central-1

package:
  exclude:
    - '*/**'
  ínclude:
    - 'handler.py'

functions:
  function-one:
    handler: handler.lambda_handler
    events:
      - http:
          method: GET
          path: info
```

* What stacktrace or error message from your provider did you see?

![serverless_profile](https://user-images.githubusercontent.com/6681272/51000651-0484c600-152e-11e9-8a9f-858ad3c9587f.png)

<details>

Debug output from `./node_modules/serverless/bin/serverless deploy --aws-profile ep_dev_role`:

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS sts 200 0.546s 0 retries] assumeRole({ RoleArn: 'arn:aws:iam::012345678912:role/xyz',
  RoleSessionName: 'aws-sdk-js-1547158630501' })
```

</details>

* Similar or dependent issues:

Probably not really related, but these are some issues I wanted to start working on to ease some CI/CD pains we have been having:

*  #5474, #5039, https://github.com/aws/aws-sdk-js/issues/2071

## Additional Data

* ***Serverless Framework Version you're using***:
1.36.0
* ***Operating System***:
Linux XXX 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04)
* ***Stack Trace***:
no stack trace => exit code 0
* ***Provider Error messages***:

**Comment by Nadock** [comment]
Just want to add I'm having the same issue in **1.36.1**

**Comment by Zainabmaleki** [comment]
I am having the same issue, spending the whole day yesterday thinking there was something wrong in my code

**Comment by johnf** [comment]
Can confirm that #5739 fixes this for me
