### ISSUE TITLE
v1.36.0: Template Variables Parsing issue 

### ISSUE THREAD

**Issue by jspreddy** [serverless/serverless#5674]
# This is a Bug Report

## Description

* What went wrong?
Parsing of template variables is erroring out.

* What did you expect should have happened?
The variable gets evaluated and proper value is put in.

* What was the config you used?
```
custom:
    local: 
        stage: local
    stage: ${self:custom.${opt:target}.stage}

provider:
    stage: ${self:custom.stage}

```
* What stacktrace or  message from your provider did you see?
![variable_parsing_error_with_1_36_0](https://user-images.githubusercontent.com/2302194/51002391-1d2ab700-1501-11e9-84ec-bf1bcf211feb.jpg)

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.0
* ***Operating System***: darwin
```
>npm run start

> my_proj@0.0.0 start ******************************
> AWS_PROFILE=my-profile DEBUG=serverless* npx serverless offline --target local --region us-east-1 start


  Serverless Error ---------------------------------------

  Serverless plugin "/****/my_proj/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${self:custom.stage}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.36.0
```

This issue does not occur on `1.35.1`, it started in `1.36.0`

**Comment by exoego** [comment]
I think this issue duplicates https://github.com/serverless/serverless/issues/5655 which is being addressed in https://github.com/serverless/serverless/pull/5658

**Comment by dschep** [comment]
Yup, what @exoego said.
