### ISSUE TITLE
function deploy gives SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by NickBlow** [serverless/serverless#568]
Hi, I just upgraded to the latest version of serverless. We were previously using something pre v 0.1 so I was hit by the breaking change.
I made a new project, with `project create -c`. 
I then ran `sls component create` and created a component, module, and function.
I then changed the bucket name in _meta/s-variables-common.json as instructed. 
When I cded into the function, and ran `sls function deploy`, I received the following error :
```
/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

SyntaxError: Unexpected token
```

Even changing the _meta/s-variables-common.json back to what it was doesn't prevent this error from occurring. Is this a bug or am I doing anything wrong?  This happens every time I follow the above steps.

**Comment by pmuens** [comment]
@NickBlow What is the solution to this one?

**Comment by NickBlow** [comment]
@pmuens if you're on OS X you have to delete all .DS_Store files, if you're not then you're having a separate issue. I opened a new issue for the DS store issue. :)

**Comment by pmuens** [comment]
@NickBlow Thanks! Good to know.
