### ISSUE TITLE
Serverless Error Concerning Stage Name in V1.36

### ISSUE THREAD

**Issue by nickelstar** [serverless/serverless#5683]
## Description

* What went wrong?
An error occurs when trying to execute any serverless command in my project using Serverless V 1.36. This error does not occur with V1.35. The error complains about my stage name which is simply 'dev'. Specifically the error is:
$ sls --version

  Serverless Error ---------------------------------------

  Serverless plugin "/home/ec2-user/.config/yarn/global/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${self:custom.env.stage}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.
* What did you expect should have happened?
That serverless commands can be executed without errors occurring with a stage name of 'dev'
* What was the config you used?
provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  versionFunctions: false
  stage: ${self:custom.env.stage}

Where ${self:custom.env.stage} = 'dev'

* What stacktrace or error message from your provider did you see?
See above

**Comment by efimk-lu** [comment]
See https://github.com/serverless/serverless/pull/5658

**Comment by gs-jackal** [comment]
I have same issue as well, specifying default stage name also show that error
`stage: ${opt:stage, 'dev'}`

**Comment by dschep** [comment]
closed by #5686
