### ISSUE TITLE
Is there a way to exclude dev-dependencies from being packages in node components?

### ISSUE THREAD

**Issue by assaflavie** [serverless/serverless#569]
I noticed deployment becoming quite slow, and it seems to be because of the size of the node_modules dir. Most of the dependencies I have are dev-dependencies (e.g. babel) and they are not needed when running in Lambda. Can I exclude them from being packaged somehow?

**Comment by assaflavie** [comment]
I found the `excludePattern` function config, which is very handy. However, it would be even more useful to have that configuration on a module level. As it is now, I have a module with various functions, and I have to replicate my `excludePattern`s for every function in order to exclude common npm packages.

Alternatively (or additionally) the packaging logic could be enhanced to use something like [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to package only non-dev dependencies.

**Comment by martinmicunda** [comment]
+1

**Comment by aliatsis** [comment]
+1

**Comment by jonathannaguin** [comment]
+1

**Comment by philltomlinson** [comment]
+1

**Comment by HyperBrain** [comment]
This should only happen on deployments from developer machines. On automated build and deployment systems you should use `npm install --production` to exclude the development packages from deployments.

**Comment by jonathannaguin** [comment]
I agree that this should happen only from developer machines, but still, the size of the lambda package is massive comparing to the production version, which slows down the deployment in development.
The only way of managing this is using custom>exclude.

**Comment by HyperBrain** [comment]
As a quick fix you could run `npm prune --production` before you deploy and a `npm install` afterwards. This is not a final solution, but might just hit the spot.

**Comment by flomotlik** [comment]
Currently we don't plan to provide a deeper integration with package.json for deployment. Especially when we create better support for various languages implementing this directly causes a lot of work. Our thoughts at the moment are that the best way to do this is (as @HyperBrain mentioned) to prune before deploying in case your dev dependencies are large enough to cause massive issues.

Removing specific dependencies and integrating tightly with the dependency management system can just easily break so we'd rather you define in your folder structure directly what you want to have deployed.

**Comment by brandonmp** [comment]
if you use webpack, you can use dead code elimination to take care of a lot of this.  specifically, it's an `uglifyJS` option.  the plugins in my `webpack.config.js` looks like this:

```
plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      comments: false,
      compress: {
        unused: true,
        dead_code: true,
        warnings: false,
        drop_debugger: true,
        conditionals: true,
        evaluate: true,
        drop_console: true,
        sequences: true,
        booleans: true,
      }
    })
  ],
```

a single lambda function of mine, when compiled with webpack, went from 220 KB to 77KB with these config options, but YMMV.

**Comment by mfonsen** [comment]
A simple solution was to put devDependencies to parent folder's package.json. This way I never deploy devDependencies even if I would happen to require those in production code. I didn't immediately notice any negative effects.

I consider using globally installed packages as a bad practice.

**Comment by jdrydn** [comment]
See https://github.com/serverless/serverless/issues/2709#issuecomment-263016387

**Comment by bo01ean** [comment]
I was able to work around this by renaming/stuttering the devDependencies section in package.json  to dddevDependencies so serverless wouldn't pick it up: 
![image](https://user-images.githubusercontent.com/1684343/33460819-c93a0080-d5e4-11e7-9f66-ed7303a3bd2a.png)

**Comment by aviggiano** [comment]
Hey, does anyone have a definitive solution for this yet?

**Comment by HyperBrain** [comment]
@aviggiano You can try [`serverless-webpack`](https://github.com/serverless-heaven/serverless-webpack). It will do its own packaging and handle everything correctly.

**Comment by ugnb** [comment]
I ended up using [serverless-plugin-scripts](https://github.com/mvila/serverless-plugin-scripts) and an ugly shell script that runs on `after:package:createDeploymentArtifacts` hook: [serverless.yml](https://gist.github.com/ugnb/0ca7d9ac5c3efe4171d0f33e48a34189#file-serverless-yml)

**Comment by throrin19** [comment]
It's weird serverless can't make his proper npm install and deploy in temporary directory with only production packages. ClaudiaJS make this like a charm

**Comment by marceloemanoel** [comment]
FWIW I've used serverless-webpack as pointed out by @HyperBrain. That worked when I also installed the `webpack-node-externals` package. The configuration that I used also imports package.json and whitelists the packages from dependencies while excludes all devDependencies.

```js
const nodeExternals = require("webpack-node-externals");
const package = require("./package.json");

module.exports = {
   ...,
   externals: [
     nodeExternals({
       whitelist: Object.keys(package.dependencies)
     })
   ],
   ...
```

Hope it also help you guys :)

**Comment by juuyan** [comment]
Hey @marceloemanoel , does your team use monorepo? I have tried your approach in yarn workspace but it only works if I keep node_modules local. Have you figured a way to exclude dependencies without "nohoist"?

**Comment by roni-frantchi** [comment]
Hey @juuyan have you looked into https://github.com/Butterwire/serverless-plugin-monorepo ?  
Does the trick for us

**Comment by juuyan** [comment]
@roni-frantchi thx, would try it!

**Comment by ahallora** [comment]
> FWIW I've used serverless-webpack as pointed out by @HyperBrain. That worked when I also installed the `webpack-node-externals` package. The configuration that I used also imports package.json and whitelists the packages from dependencies while excludes all devDependencies.
> 
> ```js
> const nodeExternals = require("webpack-node-externals");
> const package = require("./package.json");
> 
> module.exports = {
>    ...,
>    externals: [
>      nodeExternals({
>        whitelist: Object.keys(package.dependencies)
>      })
>    ],
>    ...
> ```
> 
> Hope it also help you guys :)

That worked. FYI as of 2020 `whitelist` has been replaced with `allowlist` 👍

**Comment by raphaelpreston** [comment]
For those experiencing issues with webpack caring about conditional imports even when the specific conditions aren't met, the IgnorePlugin may work well:
```
const webpack = require('webpack');
const escapeRegex = require('escape-string-regexp');
const packageJson = require("./package.json");

const devDependencies = Object.keys(packageJson.devDependencies);
const devDependencyExprs = devDependencies.map((x) => `^${escapeRegex(x)}$`);
const devDependenciesMatcherRegexStr = devDependencyExprs.join('|');
const ignorePluginRegex = new RegExp(devDependenciesMatcherRegexStr);

module.exports = {
   ...,
   plugins: [
      new webpack.IgnorePlugin({resourceRegExp: ignorePluginRegex}),
    ],
   ...
}
```
