### ISSUE TITLE
Update Insecure Dependencies?

### ISSUE THREAD

**Issue by nelsonic** [serverless/serverless#570]
Hi @ac360,

We are investigating using Serverless for re-writing a high profile web app.
So far our impressions are *really good* (*on the whole*) and we are *excited* about your forthcoming [`events`](https://github.com/serverless/serverless/blob/b7ac8452f75957707323902dea069c3190c0eeb7/lib/actions/EventDeploySNSLambda.js) release, *however* we are concerned that the project dependencies are not keeping up with the latest *security* releases: [![Dependency Status](https://david-dm.org/serverless/serverless.svg)](https://david-dm.org/serverless/serverless)
![serverless-dependencies-insecure](https://cloud.githubusercontent.com/assets/194400/12823464/0d2de03c-cb64-11e5-87dc-bf19d86c11e5.png)
> https://david-dm.org/serverless/serverless

We note that *none* of the dependencies are *that* far behind that upgrading them to latest versions would cause (*major*) breakage, would you accept a PR updating these to latest (*I will ensure the Tests all pass before submitting it*) ?

Also, does the the project have a policy/guideline for updating dependencies going forward to avoid security issues?

Thanks!

**Comment by pmuens** [comment]
@nelsonic Thanks :+1: ! Good catch.

**Comment by ac360** [comment]
@nelsonic Thanks for pointing this out.  This is helpful.   We have a big release coming out at the beginning of next week.  We'll do these dependency upgrades ourselves because we'd like to test updating them in the context of the new release.  These will be addressed right away.  Thanks again, @nelsonic

**Comment by nelsonic** [comment]
@ac360 thanks for your prompt reply. Very reassuring that you plan to update dependencies in next week's release. :+1:

**Comment by ac360** [comment]
Fixed in upcoming v0.4
