### ISSUE TITLE
Can't subscribe SQS queue to SNS topic

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5701]
How do I subscribe an SQS queue to an SNS topic using serverless?

**Comment by luanmuniz** [comment]
@cyberfox1 
https://www.jeremydaly.com/how-to-use-sns-and-sqs-to-distribute-and-throttle-events/
https://medium.com/build-succeeded/aws-lambda-with-sam-template-to-subscribe-an-sqs-to-an-sns-topic-52102b6e4bae
https://sbstjn.com/serverless-sqs-worker-with-aws-lambda.html
https://serverless.com/framework/docs/providers/aws/guide/resources/

**Comment by pmuens** [comment]
Closing since @luanmuniz provided some helpful links which should address this question...

**Comment by lm778** [comment]
There's an example template here:

[https://carova.io/snippets/serverless-aws-sqs-queue-subscribed-to-sns-topic](https://carova.io/snippets/serverless-aws-sqs-queue-subscribed-to-sns-topic)

[https://serverless.com/framework/docs/providers/aws/guide/resources/](https://serverless.com/framework/docs/providers/aws/guide/resources/)
