### ISSUE TITLE
Hidden files in variables folder cause syntax error in all serverless functions

### ISSUE THREAD

**Issue by NickBlow** [serverless/serverless#571]
I had an issue whenever I edited a file inside the variables folder with sublime that it would cause a SyntaxError whenever I ran any sls command. Turns out since I opened the file with a GUI, it created a .DS_Store file in that folder, which serverless then tries to parse and crashes.

Solution is to ignore ~~.DS_Store~~ all hidden files when parsing variables.

**Comment by msimpson** [comment]
I'd imagine this is a larger problem considering the wealth of other applications creating temporary or hidden files, like VIM. An ignore list is going to get pretty long.

**Comment by NickBlow** [comment]
@msimpson good point - I'll check with other hidden files and see if they also cause a problem.

**Comment by NickBlow** [comment]
@msimpson Ok. This applies to all hidden files in the variables folder. Steps to reproduce :
`cd _meta/variables`
`echo 'blah' > .test`
Now go back to the root and run `sls dash deploy`. You'll get a syntax error.

**Comment by MrRio** [comment]
You could attempt to parse them first, then skip if unparseable with a warning.

**Comment by ac360** [comment]
Fixed in a95d434d4ed73fac3744ef22dc739fe58f157cbf  Please let me know if this does not work for you

**Comment by NickBlow** [comment]
Works great! Thank you for the speedy fix :+1: @ac360
