### ISSUE TITLE
How to get the ARN of a resource not defined in serverless.yaml?

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5712]
There is an SNS topic already created, how can reference it by ARN?

**Comment by Fiiii** [comment]
Basically, this is the path `arn:aws:service:region:accountid:resourceType or topicName` , so is should be looks like: `arn:aws:sns:us-east-1:5321321321:cb-to-slack`

**Comment by pmuens** [comment]
Closing since @Fiiii provided some helpful answers here 👍
