### ISSUE TITLE
Self-referential variable resolution in included files

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5716]
Suppose we are including a file as a custom variable in serverless.yaml:

    custom:
        site: ${file(../site.yml)}

And in that file we have two variables defined:

    SOMEVAR: foobar
    OTHERVAR: http://abc.com/${self:custom.site.SOMEVAR}

Essentially we are referring to a dict (custom.site) from the same file that is parsed to build the dict.

Actually the above works, I just want to make sure it is known to be a desirable feature in case it works by accident. I assume lazy variable resolution makes it possible.

**Comment by brianneisler** [comment]
Might be good to document this as a feature.

**Comment by cyberfox1** [comment]
Also just to be clear, the lack of variables in YAML is what makes this so useful.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
