### ISSUE TITLE
No login command on macOS

### ISSUE THREAD

**Issue by samjmckenzie** [serverless/serverless#5737]
I ran `sudo npm i -g serverless` on my laptop with macOS 10.14.2, and it does install but it does give me this message: 
```
sudo npm i -g serverless
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.36.2 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js


┌────────────────────────────────────────────────────────────────┐
│                 serverless update check failed                 │
│              Try running with sudo or get access               │
│              to the local update config store via              │
│ sudo chown -R $USER:$(id -gn $USER) /Users/sammckenzie/.config │
└────────────────────────────────────────────────────────────────┘
+ serverless@1.36.2
```

I suspect this has something to do with the main issue, which is that I can't run `serverless login`. I receive this message when I attempt to do so:
```
Serverless command "login" not found. Did you mean "logs"? Run "serverless help" for a list of all available commands.
```

**Comment by dschep** [comment]
Hey @samjmckenzie, we just updated our platform/dashboard offering, now called Serverless Enterprise on Monday. All Enterprise features are now in `@serverless/enterprise-plugin` (including `sls login`). If you aren't using the dashboard, you can skip `sls login`. Or, to get started with dashboard/enterprise, check out the docs here: https://github.com/serverless/enterprise

**Comment by samjmckenzie** [comment]
Ah, right. I'm guessing the main website still needs to be updated, as those instructions aren't listed there.
