### ISSUE TITLE
Run tests on AWS when deploying

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#574]
1. If the user has tests create a testing environment (via CloudFormation files in the Serverless project) on AWS, so that the production environment is recreated.
2. After that spin up Lambdas and run the tests
3. If everything is fine remove the testing environment and everything test related from AWS and deploy the code like a normal deployment would do. Otherwise don't deploy the new version and show an error message in the command line

Don't know if this would be to expensive / too slow, but we could recreate some kind of CI this way.

Refs  #327

**Comment by flomotlik** [comment]
I don't think we'll include this in Serverless directly, but we'd love to have more test tooling in place so users have a better time testing their applications. I will close this for now.
