### ISSUE TITLE
Cached credentials in getCredentials() cause offline testing to fail

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#5747]
Running the tests locally might cause tests to fail due to the caching behavior of credentials.

They credentials from the local file system will show up in tests. This is not the case on our CI system since they don't have AWS setup.

**Comment by ng95junwei** [comment]
Hello! I would like to try to tackle this issue. is there a reliable way to replicate this failure?

**Comment by pmuens** [comment]
Hey @ng95junwei thanks for taking the initiative here.

Yes, the easiest way is to setup your `aws` credentials on your local machine and dive into the tests here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.test.js#L841 (and all other tests in that file calling `getCredentials()`).

I updated some tests and access properties dircetly like we do [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.test.js#L833). However if you remove the direct property access you'll see that your local AWS setup kicks-in, so this part should be mocked.

**Comment by kvnam** [comment]
Hello @ng95junwei and @pmuens, is this still being worked on? If not may I give it a go?

**Comment by medikoo** [comment]
Thanks for the discussion I assume it's no longer an issue, therefore I'm closing this. If It's not the case and you believe it still needs to be addressed, please comment
