### ISSUE TITLE
Upload size of AWS go lambda's doubles with 1.36.xx

### ISSUE THREAD

**Issue by kempeng** [serverless/serverless#5748]
# This is a Bug Report
I have noticed that the size of the zip files created by Serverless to upload Golang lambdas to AWS have doubled in size with the update of Serverless from 1.34.xx to 1.36.xxx, any reason for this or is it a bug?

## Description

* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by jkrajniak** [comment]
We've noticed the same issue. Basically, the files in .zip are duplicated;

```
Archive:  service-function.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 35564224  1980-01-01 00:00   ./bin/api
 29804640  1980-01-01 00:00   ./bin/authorizer
 29706272  1980-01-01 00:00   ./bin/notify
 30120192  1980-01-01 00:00   ./bin/scan
 35564224  1980-01-01 00:00   bin/api
 29804640  1980-01-01 00:00   bin/authorizer
 29706272  1980-01-01 00:00   bin/notify
 30120192  1980-01-01 00:00   bin/scan
---------                     -------
250390656                     8 files
```
The service is written in Go. 

I have checked the zip produced for freshly created service with templates: aws-go-mod and aws-python3. For go, the zip produced by sls contains duplicated files, whereas for python there is no issue.

Here is the example freshly created from aws-go-mod template:
```
Archive:  service-demo-go-2.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  6599296  1980-01-01 00:00   ./bin/hello
  6599296  1980-01-01 00:00   ./bin/world
  6599296  1980-01-01 00:00   bin/hello
  6599296  1980-01-01 00:00   bin/world
---------                     -------
 26397184                     4 files
```

and the one created for Python (added additional file with second handler to have two lambda functions):
```
Archive:  service-demo-2.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      497  1980-01-01 00:00   handle2.py
      497  1980-01-01 00:00   handler.py
---------                     -------
      994                     2 files
```


My version of SLS and Node:
```
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.15.0
     Serverless Version:     1.36.3
 
```

**Comment by jkrajniak** [comment]
One more comment, it looks like the issue is due to the `package` section in `serverless.yml`. Namely, for aws-go the template contains following part:
```yaml
package:
 exclude:
   - ./**
 include:
   - ./bin/**
```
which I assume  causes that the handlers are copied two times. 
The first time because of the `include` parameter and the second time because of the `handler: bin/hello`

**Comment by ZotyoNegentropics** [comment]
If you use
`package:
 exclude:
   - ./**
 include:
   - bin/**`
instead of
`package:
 exclude:
   - ./**
 include:
   - ./bin/**`
there will be no duplicated files
