### ISSUE TITLE
Standardised documentation for AWSM modules

### ISSUE THREAD

**Issue by cangoektas** [serverless/serverless#575]
Hi guys, sorry if this was mentioned and discussed before. I'm new to this project but a few things grabbed my attention. Here are my thoughts:

- Microservices are all abut APIs and each API should have its own documentation
- If we expect other people to use our code, it should be documented
- AWSM modules group multiple microservices together, but it would be cool to see examples on how these services can be used together to do certain tasks (some simple illustrations for example)
- There should be a standardised way to document code for microservices
- It would be really cool if there was a standardised way to showcase how the services could be used together
- All this could then be used in a public searchable registry for AWSM modules (related to #524 and #525)

Regarding the documentation of services I think JSDoc could be a good solution. Regarding the illustrations I don't have any ideas yet. What do you think?

**Comment by cangoektas** [comment]
Actually after reading about the new Serverless Module System I realized my suggestion to use JSDoc is stupid. We should have a non-language specific way to describe modules and its services. I'll be looking and reading more about Swagger now.

**Comment by flomotlik** [comment]
We're currently moving away from the Module concept itself in V1. We're going to introduce more documentation about it in the future and this will be covered. I will close this issue for now as it is already planned to be resolved in the future.
