### ISSUE TITLE
AWS: ${ssm} should throw error when the referenced parameter is not found and no fallback

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#5757]
# This is a Bug Report

## Description

* What went wrong?
   * When `${ssm}` specifiyes non-existant parameter, `sls deploy` or other command just output warning and continue, instead of throwing error.

* What did you expect should have happened?
   * If parameter is not found and no fallback found, serverless should abort to prevent broken deployment.
   * Note: `${cf}` and `${s3}` can abort if not found.

* What was the config you used?
```yml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

custom:
  ssmVar: ${ssm:/path/to/service/myParam}
```

* What stacktrace or error message from your provider did you see?

```
$ sls print
 
 Serverless Warning --------------------------------------
 
  A valid SSM parameter to satisfy the declaration 'ssm:/path/to/service/myParam' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid SSM parameter to satisfy the declaration 'ssm:/path/to/service/myParam' could not be found.
 
service: aws-nodejs
provider:
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
custom:
  envVar: fallback
  optVar: fallback
  selfVar: fallback
  fileVar: fallback
```
    

Similar or dependent issues:
* #3367: Serverless Variables should throw error when the referenced file is not found
* #4447: Feature Request: CLI command to check that all SSM params are present
* #5369: feature: option to fail fast on unresolved variables
* https://github.com/serverless/serverless/issues/3491#issuecomment-311601716: Serverless would end up with an error in case it finds any variable that does not exist

**Comment by Ehsan70** [comment]
Yeah this would be really beneficial. Prevents misconfiguration while pushing to production

**Comment by abhivijay89** [comment]
While installing serveless plugins, throwing below warning (even though the param exists in SSM):
`serverless plugin install --name serverless-step-functions`

```
11:09:47  Serverless Warning --------------------------------------
11:09:47  
11:09:47   A valid SSM parameter to satisfy the declaration 'ssm:emrApiKey' could not be found.
11:09:47  
11:09:47 Serverless: Creating an empty package.json file in your service directory
11:09:47 Serverless: Installing plugin "serverless-step-functions@latest" (this might take a few seconds...)

11:10:02 Serverless: Successfully installed "serverless-step-functions@latest"

```

**Comment by exoego** [comment]
@abhivijay89 
I think, "ssm warning while installing plugin" is different issue which requires different fix.
Could you open a new issue for that, with configuration to reproduce?

**Comment by abhivijay89** [comment]
Sure @exoego 
Will open up a new issue for this

**Comment by nkowdley** [comment]
Is there any updates on this?

**Comment by jeremiahlukus** [comment]
not great to error out if you have multiple stages on different aws accounts

**Comment by hello-josh** [comment]
I just ran into this today. I was explicitly testing to see what happens if the ssm parameter doesn't exist. It generates partial cloudformation and keeps on going. Is there a flag to have `serverless` exit on a warning?

**Comment by bryantbiggs** [comment]
bump - almost 2 years now, any word on if this will be addressed or not?

**Comment by medikoo** [comment]
This will be covered at https://github.com/serverless/serverless/issues/5757
