### ISSUE TITLE
Support for multiple events in function run

### ISSUE THREAD

**Issue by dijitalmunky** [serverless/serverless#576]
When doing a serverless application following the multiple endpoints -> single lambda pattern, `sls function run` falls a little short because you can only have a single payload in `event.json`.

For example, If I want to support `GET` within my lambda, I would need the `event.json` to look something like this:  
```
{
  “httpMethod”: “GET”,
  “id”: 1273912
}
```

However, if I also want the lambda to support `POST` I may need `event.json` to look more like this:
```
{
  “httpMethod”: “POST”,
  “firstName”: “john”,
  “lastName”: “doe”,
  “phone”: “555-555-5555”
}
```

Renaming, re-linking files to `event.json` or editing `event.json` becomes  a pain very quickly.

It would be nice if serverless had a better way of supporting this.

**Comment by dijitalmunky** [comment]
A few solutions come to mind:

1. Support specifying the event file on `sls function run` command, For example `sls function run <function path> <event-file>`
1. Support mapped events in event.json that you then specify on the command line.  For example event.json would look like this:
```
{
  "default": {
    “httpMethod”: “GET”,
    “id”: 1273912
  },
  "post": {
    “httpMethod”: “POST”,
    “firstName”: “john”,
    “lastName”: “doe”,
    “phone”: “555-555-5555”
  }
}
```
then if ran `sls function run <function-path>` it would pass the "default" in, otherwise you could run `sls function run <funciton-path> <action>` and serverless would grab the element by key out of the event.json file.  This option also has the element of being able to have special keywords like "all" that could loop through and invoke one at a time.

**Comment by erikerikson** [comment]
This has come to mind on occasion, thanks for raising it.

event.json is peer to s-function.json, the pair of which gets their own folder (by file name uniqueness).  Both files lists one or more functions and the arguments/configuration (respectively) for them.  Currently each function can have one or more endpoints defined.  I think the solution is to have those same endpoints mirrored within event.json.

As events are supported, a similar events collection seems appropriate.:

{
"method": {
"endpoints": [
{ "method": "GET", "params": {} }
{ "method": "POST", "params": {} }
],
"events": [
{ "source": "[NAME0]", "params": {} }
{ "source": "[NAME1]", "params": {} }
]
}
}

This would change as the representation in s-function.json evolves.

**Comment by erikerikson** [comment]
That or the test event could be specified in the function definition

**Comment by dijitalmunky** [comment]
Hrm...that could work.  How would that change if I wanted to invoke my 'GET' with two different payloads?  For example, my GET needs to respond differently if the ID exists vs. if it does not.  When I run locally, I have a local datastore backing my lambda that I'm able to reset with a single command, so having this ability would make it really easy to set-up my whole round trip tests.

I am still leaning heavily to wanting something very simple where I can simply specify a key on the command line to invoke the one I want.

**Comment by erikerikson** [comment]
Hrm.  Good point.  That would just kick the can down the road.  I'd guess that in such a case, you could use project templates but that isn't dynamic in the fashion that could be useful for doing something silly like running test suites. ;)

I've primarily iterated using the local event by specifying what I want *right now* and working from there.  My test suites handle the rest by providing the specific event definitions that I want to call each function with.  Because this more involved capability of mocha-chai-sinon serves my purposes better, I've seen event.json as a transitory debugging tool rather than something for extensive, planned, and structured use.

**Comment by dijitalmunky** [comment]
Good point about using mocha-chai-sinon...I haven't actually looked much into that because I am so under the gun right now, but that sounds like it is probably worth a look for me ATM.

Perhaps the right approach for serverless is to do the simplest thing, which would be to allow someone to sepcify an alternate .json on the CLI and recommended "proper" testing be done my mocah-chai-sinon.

**Comment by erikerikson** [comment]
That is a totally reasonable request, for sure.  The general approach so far has been to enable users while avoiding being opinionated.

**Comment by dijitalmunky** [comment]
That is why I am loving this Framework so far!

**Comment by kddeisz** [comment]
Just putting this here in case it sparks any discussion, I've been using this to run functions internally:

```
#!/bin/bash

cat << EOF > nodejs/resource/slackbot/event.json
{
  "body": {
    "token": "<token>",
    "text": "$@"
  }
}
EOF

PATH="$(npm bin):$PATH"
sls function run nodejs/resource/slackbot
```

The problem was, I have a slackbot running on my lambda that serverless deploys, so there are a lot of possible text variants. I run this like `./slack command option1 option2`. In that way I don't have to keep changing event.json.

**Comment by flomotlik** [comment]
In the future function run will support the ability to point to a specific event.json file. This is already planned in our specs. I will close this issue for now as the resolution is already in our plan.
