### ISSUE TITLE
AWS lambda layers deployment does not keep old version

### ISSUE THREAD

**Issue by kodart** [serverless/serverless#5765]
# This is a Bug Report

## Description

* What went wrong?
Old layer got deleted
* What did you expect should have happened?
Old layer should remain by default
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.35.1
* ***Operating System***:
MacOS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by johnwongapi** [comment]
Please correct me if im wrong. During a update action, CF will create a new `Lambda:LayerVersion` and replace(delete) the previous one regardless of `DeletePolicy`. So at this moment, old layer version cannot be keep due to issue of CF.

**Comment by kodart** [comment]
I didn't analyze it deeper, but it looks like SAM can handle that.
Anyways this should be resolved otherwise it is unusable. Layer is shared
with others, even from different accounts.
They would be surprised to see lambda failing just because we've released a
new version of the layer.
They should be able to continue using old version and update when they want
to

пт, 1 февр. 2019 г., 11:13 johnwongapi notifications@github.com:

**Comment by johnwongapi** [comment]
thanks @kodart , i found out how SAM do this: [link](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template.html#serverless-sam-template-layerversion)

> When a serverless layer version is transformed, AWS SAM also transforms the logical ID of the resource so that old layer versions aren't automatically deleted by AWS CloudFormation when the resource is updated.

It is possible to do it by serverless🎉🎉

**Comment by dschep** [comment]
Agreed that it is possible via that technique @johnwongapi, but I fail to see the real advantage to doing so.

One downside AFAICT is that it would make it difficult to use sls to publish layers meant for consumption in a different service since the name to export wouldn't be predicable.

The other, not so much downside, but lack of upside, is that if you are using the layer within the same service, you still have odd name issues potentially. But more importantly, you'll still be publishing a new version of the layer everytime you deploy, so I'm not sure what the benefit in that case is of old layers.

**Comment by kodart** [comment]
@dschep logical id of a resource and layer name are two different things. logical id is only used by CF to update the resources it manages. 
when we create layer version, we don't need to remove old resource, so logical id should be different.

**Comment by kodart** [comment]
> so I'm not sure what the benefit in that case is of old layers
@dschep if you have a lambda function that uses that old layer version, it will start failing.

**Comment by dschep** [comment]
> @dschep logical id of a resource and layer name are two different things. logical id is only used by CF to update the resources it manages.

true, but CF refs & exports are a useful way to use layers

> @dschep if you have a lambda function that uses that old layer version, it will start failing.

huh, I'll have to look into that. That's not what I remember being told by AWS when layers were first introduced.

**Comment by johnwongapi** [comment]
> > @dschep if you have a lambda function that uses that old layer version, it will start failing.
> 
> huh, I'll have to look into that. That's not what I remember being told by AWS when layers were first introduced.

@dschep if the layer version is deleted, lambda is still runnable with it. But there will be a error when having code change to the lambda.

**Comment by et304383** [comment]
This should be resolved by having serverless always create layer version resources with a deletion policy of retain, and changing the name when generating a new layer.

**Comment by kingtut** [comment]
I think this error is related:

`
  Serverless Error ---------------------------------------
 
  An error occurred: my-dev - Export MyLayerArn cannot be updated as it is in use by my-other-stack-dev.
`

Currently, the way layers are being destroyed on update prevents cross-stack imports entirely:

`
functions:
  my-function:
    ...
    layers:
      - 'Fn::ImportValue': ActivityDataLayerArn
`

**Comment by ReidWeb** [comment]
+1 to getting this behaviour changed

**Comment by AnthonyWC** [comment]
I think this behavior needs to change, or at least give us the choice to retain old layer.
