### ISSUE TITLE
[Python] Environment variables not being passed to Lambda

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#577]
I've started testing with a Python2.7 function and it appears Serverless environment variables aren't being passed to Lambda. I've set new Env Vars using:

`sls env set -s dev -r eu-west-1 -k jcTest -v 123`

And to show all available variables I ran:

```
for key in os.environ.keys():
    print("{} - {}".format(key, os.environ[key]))
```

Which returned:

```
LAMBDA_CONSOLE_SOCKET
AWS_SECRET_ACCESS_KEY
LAMBDA_SHARED_MEM_FD
AWS_LAMBDA_FUNCTION_MEMORY_SIZE
LAMBDA_CONTROL_SOCKET
LAMBDA_RUNTIME_DIR
AWS_LAMBDA_FUNCTION_VERSION
PYTHONPATH
AWS_LAMBDA_LOG_GROUP_NAME
AWS_REGION
AWS_DEFAULT_REGION
AWS_ACCESS_KEY_ID
AWS_SESSION_TOKEN
LAMBDA_RUNTIME_LOAD_TIME
LAMBDA_TASK_ROOT
AWS_SECURITY_TOKEN
LAMBDA_LOG_FD
AWS_LAMBDA_LOG_STREAM_NAME
PATH
LD_LIBRARY_PATH
AWS_LAMBDA_FUNCTION_NAME
```

I also expected `SERVERLESS_PROJECT_NAME` and `SERVERLESS_STAGE` to be included as a minimum, is there anything I'm missing?

**Comment by gepoggio** [comment]
A workaround is to use python-dotenv: https://github.com/theskumar/python-dotenv

`import os
import dotenv

dotenv_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "../.env")
dotenv.load_dotenv(dotenv_path)`

This doesn't work locally, for that I just use:

`env $(cat .env | xargs) sls function run component/function`

**Comment by ryansb** [comment]
@gepoggio This is now covered as part of [serverless-helpers-py](https://github.com/serverless/serverless-helpers-py), and it can load CloudFormation outputs into the env as well. 

```
import serverless_helpers
serverless_helpers.load_envs(__file__)
serverless_helpers.load_cfn_outputs() # separate call because it requires time for network roundtrip
```
