### ISSUE TITLE
How To Add Multiple Targets cloudwatchEvent

### ISSUE THREAD

**Issue by mqasim-st** [serverless/serverless#5771]
Hi,

Below is my serverless YAML

        service: CloudTrailEnabler-1

        provider:
        name: aws
        runtime: python2.7
        region: us-east-1
        role: arn:aws:iam::XXXXXXXXX:role/service-role/CloudTrailEnabler
        stage: ${self:provider.region}
        stackName: ${self:service}

        functions:
        enabler:
            handler: handler.lambda_handler
            name: ${self:service}
            memorySize: 128
            timeout: 3
            events:
            - cloudwatchEvent:
                name: ${self:service}
                event:
                    source:
                    - "aws.cloudtrail"
                    detail-type:
                    - "AWS API Call via CloudTrail"
                    detail:
                    eventSource:
                        - "cloudtrail.amazonaws.com"
                    eventName: 
                        - "StopLogging"

It created one Target which is lambda, I just need to add one more target which is SNS.
I am unable to find docs how should i add SNS with it

Thanks

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
