### ISSUE TITLE
Improve error messages for ssm permission issue

### ISSUE THREAD

**Issue by gauntface** [serverless/serverless#5781]
# This is a Feature Proposal

## Description

When setting environment variables with `${ssm:abcd}` variables I was getting the following error message:

```
 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:abcd' could not be found.
```

When I try to access the variable with the AWS CLI, I get more information:

```
$ aws ssm get-parameter --name abcd                                                                255 ↵

An error occurred (AccessDeniedException) when calling the GetParameter operation: User: <user info> is not authorized to perform: abcd on resource: <param info>
```

After adding permissions to the serverless IAM policy, everything started to work as you'd expect.

Adding an error message, either a custom error regarding permissions OR passing through the AWS error would have been super helpful.

**Comment by gauntface** [comment]
I agree with everything you've said. Finding a way to pipe through any errors sounds like the sanest approach to me. You also filter this based on the --verbose flag.

**Comment by exoego** [comment]
> Do you think we can somehow have a catchall mechanism and print the actual error of why a variable was not resolved?

I believe my PR https://github.com/serverless/serverless/pull/5770 address this and improve DX 💪 

Currently, if a request to SSM fails due to status code `400`, `${ssm}` syntax
* will populate `undefined` as fallback
* will warn `A valid SSM parameter to satisfy the declaration 'ssm:abcd' could not be found`
* will NOT ouput the reason why `400` returned, as @gauntface mentioned.

See below for the error JSONs returned by AWS when `400` on SSM.

```json5
{
  "code":"UnrecognizedClientException",
  "message":"The security token included in the request is invalid.",    
  // continue
}
```

```json5
{
  "code":"AccessDeniedException",
  "message":"User: <USER_ARN> is not authorized to perform: ssm:GetParameter on resource: <SSM_RESOURCE_ARN>",
  // continue
}
```

Which means, we already retrieves enough reason of error from AWS.
I think we do not require **error translations** (which can be tech debt) for every error situations for different providers.
It is only required to simply log the retrieved error message.

* `${s3}` already do so.
* `${ssm}` is being fixed in PR #5770 to do so.
* `${cf}` requires a separete PR but it is trivial

**Comment by simlu** [comment]
Basically this won't be implemented until version 2.x.x (see pr). Really unfortunate behavior...

**Comment by stephan-nordnes-eriksen** [comment]
Does anyone know what the minimum permission policy required in IAM is to get this to work?

**Comment by jswift** [comment]
> Does anyone know what the minimum permission policy required in IAM is to get this to work?

It would appear to be:
```javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:DescribeParameters"
            ],
            "Resource": "*"
        },
        {
            "Sid": "123456789",
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameters",
                "ssm:GetParameter"
            ],
            "Resource": [
                "arn:aws:ssm:<REGION>:<ACCOUNT_ID>:parameter/<PARAMETER_NAME>"
            ]
        }
    ]
}
```

**Comment by phmasek** [comment]
Remember to provide policy allowing usage of `kms` keys if the parameter is a `SecureString`. Otherwise AWS will deny access when running `ssm:GetParameter`


````
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "kms:Decrypt"
      ],
      "Resource": [
        "arn:aws:kms:<REGION>:<ACCOUNT_ID>:key/<KEY_ID>"
      ]
    }
  ]
}
````

**Comment by bitsofinfo** [comment]
please fix the error message

**Comment by dijonkitchen** [comment]
Seems a bit better now:

```
$ sls offline
Serverless: Running "serverless" installed locally (in service node_modules)
 
  Serverless Error ---------------------------------------
 
  User: arn:aws:iam::123xxx is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-west-2:123xxx
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.3
     Framework Version:         2.13.0 (local)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2
 
 
 Serverless Warning --------------------------------------
 
  A valid SSM parameter to satisfy the declaration 'ssm:/dev-scribe/common/LOGGING_DESTINATION_ARN' could not be found.
 
$ aws ssm get-parameter --name 123xxx

An error occurred (AccessDeniedException) when calling the GetParameter operation: User: arn:aws:iam::123xxx is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-west-2:123xxx
```

**Comment by medikoo** [comment]
Closing, as it's fixed with a new variables resolver
