### ISSUE TITLE
API Gateway deployment name changes when it shouldn't

### ISSUE THREAD

**Issue by spacanowski** [serverless/serverless#5783]
# This is a Bug Report

## API Gateway deployment name changes when it shouldn't

CF ApiGatewayDeployment logical id is always regenerated and causes API Gateway redeployment without any changes. Name generation uses `new Date()).getTime().toString()` as name postfix where it should be calculated based on API Gateway config.

e.g
run `sls deploy --stage dev --region eu-west-1` (or similar) twice without any changes. Instead of `Serverless: Service files not changed. Skipping deployment...` info deployment is executed and API Gateway deleted and created (redeployed).

## Additional Data

* serverless version: 1.36.3

**Comment by eahefnawy** [comment]
Thanks @spacanowski ... left some feedback in the PR!

**Comment by pmuens** [comment]
Closing this issue since https://github.com/serverless/serverless/pull/5885 already resolved it.
