### ISSUE TITLE
Failed to deploy openwhisk function

### ISSUE THREAD

**Issue by karanrk** [serverless/serverless#5790]
# This is a Bug Report

## Description

* What went wrong?
 I have followed all the documentation mentioned to set up serverless and also set up credentials on IBM Cloud Functions (Openwhisk), but i am unable to deploy any function to openwhisk through serverless.

* What did you expect should have happened?
My function should have been deployed without any errors through serverless.

* What was the config you used?
All default configuration was used, didn't bother to edit any config.

* What stacktrace or error message from your provider did you see?
Failed to deploy function (MyFunctionName) due to error: Unknown Error From API: socket hang up

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.36.3
* ***Operating System***: linux
* ***Stack Trace***:
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling Functions...
Serverless: Compiled Function (greeting): {"actionName":"python-service-dev-greeting","overwrite":true,"action":{"exec":{"main":"endpoint","kind":"python","code":"<hidden>"},"limits":{"timeout":60000,"memory":256,"concurrency":1},"parameters":[],"annotations":[]}}
Serverless: Compiling Packages...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiling Triggers & Feeds...
Serverless: Compiling Service Bindings...
Serverless: Deploying Functions...
Serverless: Deploying Function: python-service-dev-greeting

* ***Provider Error messages***:
Failed to deploy function (MyFunctionName) due to error: Unknown Error From API: socket hang up

**Comment by pmuens** [comment]
Hey @karanrk thanks for opening this issue 👍

It looks like this is related to the IBM OpenWhisk provider plugin. Could you open up an issue in that repository? Thanks!
