### ISSUE TITLE
problem with updating to 1.36.3 and other issue with the yml file

### ISSUE THREAD

**Issue by mohamedelephant** [serverless/serverless#5795]
Hi,

I have a few problems that occur at the same time:

1- Changing the region in yml file is not working:

I've changed the region to `eu-west-1` but when I deployed it, it shows me that the resources are in `us-east-1`. No idea why?

2- I thought it might be because of the version I was using `1.33.something`, I've tried to run the regular command for update `npm install -g serverless`, nothing happened as I got `write permission error`, So I run it as `sudo  npm install -g serverless`, it gave me `illegal operation on a directory, open '/usr/local/lib/node_modules/....` a lot. 

I end up with using `sudo npm install -g serverless@1.36.3`, this command deleted the framework from my laptop. So, now I can't use the framework. 

What did I do to make this happened? Is there any bug or something makes the update fails and/or a problem in the yml file that ignored my entered region??

Thanks,

**Comment by mohamedelephant** [comment]
I solved the issue with using the steps in this link: https://gist.github.com/DanHerbert/9520689

got another issue but its easier to deal with, that the `sls` command is not working globally.

**Comment by dschep** [comment]
ah yes.. homebrew. making live easier and harder for developer every day 😕
