### ISSUE TITLE
Simpler PlugIn installation process

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#580]
Wouldn't it be great if one could add a plugin simply with a `npm install --save XYZ`?

So that we omit the step of adding the plugin name to section 'plugins' in the s-project file.

**Comment by ac360** [comment]
:+1:

**Comment by eahefnawy** [comment]
@pmuens Philipp sorry for the late reply on this issue. We're loving this PR! v0.5 is now stable, and we'll be releasing soon (we're currently testing it). Could you please update your PR to work with these new changes and submit it to the v0.5 branch? We'll merge it right away :)

We'll keep the project plugins array for backward compatibility reasons like you mentioned, so please keep your code aware of it :)

Thanks a lot for all of your contributions within our community :blush:

**Comment by pmuens** [comment]
Hey @eahefnawy 
Thank you for the kind words and thanks for getting back.
I'll work on this issue next week and submit a PR!

Have a nice weekend!

**Comment by pmuens** [comment]
I started the work on this today. However I'll postpone it until the major refactoring of v0.5 is done (so I don't have to deal with that much flux).

**Comment by eahefnawy** [comment]
Closing since we're now tracking an updated issue in #978

Thanks @pmuens 👍

**Comment by pmuens** [comment]
Alright. I'll look into this!
