### ISSUE TITLE
Easy to access PlugIn API

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#581]
Some functionality such as

https://github.com/tmilewski/serverless-resources-validation-plugin/blob/master/src/index.js#L80 (_prompt)

or

https://github.com/tmilewski/serverless-resources-validation-plugin/blob/master/src/index.js#L104 (_validateAndPrepare)

are very useful when developing a plugin. Maybe we could expose such an API which is easy accessible for PlugIn developers.

**Comment by flomotlik** [comment]
The plugin system will be revamped for the next release, we'll consider this then.
