### ISSUE TITLE
Invoking serverless local -f <function_name> from WebStorm, using npm or Node.js configuration, doesn't provide output

### ISSUE THREAD

**Issue by kaxax** [serverless/serverless#5810]
# This is a Bug Report

## Description

I wanted to run lambda function locally in WebStorm, so I wrote "start" script in the package.json and created Npm run configuration

package.json :

```
... 
"scripts": {
     "start": "serverless invoke local -f testFunction",
 },
... 
```

Npm run configuration:
![capture](https://user-images.githubusercontent.com/17899334/52454511-70764080-2b65-11e9-8d2d-a22bd64b6bac.PNG)

After creating the configuration, clicking Run button must have resulted executing lambda function locally, but lambda function didn't execute.

Run window result:
![capture1](https://user-images.githubusercontent.com/17899334/52456096-bc78b380-2b6c-11e9-8af0-314511e31c4d.PNG)

 **when executing `serverless invoke local -f <function_name>`  from cmd terminal, everything works fine.**

I started debugging serverless library, when `serverless local -f <function_name>` command is invoked, in the `invokeLocal\index.js`  file a promise is called on the 66's line but it isn't resolved and also exeption is not caught.

```
     try {
         stdin().then(input => {
             this.options.data = input;
              resolve();
          });
      } catch (exception) {
           // resolve if no stdin was provided
           resolve();
      }
```

`stdin()` calls `get-stdin\index.js` package's promise function with an if clause in it:

```
if (stdin.isTTY) {
    resolve(ret);
    return;
}
```

when `serverless invoke local -f <function_name>` is called from cmd terminal `stdin.isTTY` is `true` and it does resolve the promise but when it is invoked from WebStorm's run window `stdin.isTTY` is `undefined` and promise is never resolved, this results not executing lambda function.

## My Solution

My custom solution is to make`process.stdin.isTTY;` allways true  in  `invokeLocal\index.js` file so code will look like:

```
     try { 
         //my code goes here
         if(!process.stdin.isTTY){
             process.stdin.isTTY = true;
         }
          //end of my code
          stdin().then(input => {
             this.options.data = input;
              resolve();
          });
       } catch (exception) {
           // resolve if no stdin was provided
           resolve();
       }
```
 

## Additional Data

* ***Serverless Framework Version: 1.27.3***:
* ***Operating System: Windows 10 64x***:
* ***Node Version: v8.12.0***:
* ***Npm Version: 6.0.1***:
* ***get-stdin Package: https://www.npmjs.com/package/get-stdin***:

**Comment by Aciid** [comment]
I just replicated this issue with and used the fix @kaxax provided with the following configurations where I have the same issue.

macOS Mojave 10.14
- Webstorm: 2019.1, 2018.3.6, 2018.2.8
- Serverless: 1.40.0
- Node: 6.10.2 ( AWS )

- Webstorm: 2019.1, 2018.3.6, 2018.2.8
- Serverless: 1.40.0
- Node: 8.10 ( AWS )

I vouch for @kaxax fix to be added to serverless upstream. It's really a crossplatform issue and version agnostic.

I'm unable to pinpoint when did this started. But the issue is same no output and no breakpoints triggering on debug for local invokes in webstorm. Same commands on terminal work correctly.

**Comment by tegomass** [comment]
bump

**Comment by kinowarrior** [comment]
Any update?

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.

**Comment by danketrotzdem** [comment]
I also have this problem. How can we proceed here?

**Comment by tegomass** [comment]
Good question...
