### ISSUE TITLE
EACCES: permission denied, open '/home/travis/.aws/credentials' on TravisCI

### ISSUE THREAD

**Issue by alexbeletsky** [serverless/serverless#5811]
# This is a Bug Report

Serverless fails to deploy running on TravisCI.

## Description

* What went wrong?

In TravisCI setup I have a deployment script which is executed on TravisCI virtual machine,

```yml
deploy:
  - provider: script
    script: sls deploy --stage stage --verbose --conceal
    skip_cleanup: true
    on:
      repo: blogfoster/channel-metrics-collector
      branch: develop
```

The `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are exposed as environmental varibles. 

When it runs actually, I see the following error message:

```
  Serverless plugin "/home/travis/build/ddd/channel-metrics-collector/node_modules/serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.js" initialization errored: EACCES: permission denied, open '/home/travis/.aws/credentials'
```

I don't get why the plugin is trying to access that file and tried to write it. Moreover, the issue is kind of floating. Sometimes it happens (90% of cases), sometimes it doesn't.

One important note, I have `serverless` package as `devDependency` in my project, since I use `serverless-offine` for tests,

```js
  "devDependencies": {
    // ...
    "serverless": "^1.37.0",
    "serverless-offline": "^4.2.0",
    "serverless-offline-sqs": "^1.6.0",
    // ..
  },
```

* What did you expect should have happened?

Deployment is successful.

* What was the config you used?
* What stacktrace or error message from your provider did you see?

```
Serverless Error ---------------------------------------
 
  Serverless plugin "/home/travis/build/ddd/channel-metrics-collector/node_modules/serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.js" initialization errored: EACCES: permission denied, open '/home/travis/.aws/credentials'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.15.0
     Serverless Version:     1.37.0
 
Script failed with status 1
```

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
