### ISSUE TITLE
Config should also be read from serverless.config.js file.

### ISSUE THREAD

**Issue by csimi** [serverless/serverless#5822]
# This is a Bug Report

## Description

* What went wrong?
When using a js config file (serverless.js) "npx serverless" opens this file in my editor instead of running the serverless executable.
I guess this is why for example webpack uses webpack.config.js by default as the name of config files.
* What did you expect should have happened?
npx serverless should run the executable no matter if you use a yml or json or js config.
I think the js-type config file should be read both from serverless.js for backward compatibility and serverless.config.js to avoid this issue.
* What was the config you used?
Doesn't matter as long as your config file is js.
* What stacktrace or error message from your provider did you see?
N/A

## Additional Data

* ***Serverless Framework Version you're using***:
1.37.1
* ***Operating System***:
Windows 10

**Comment by dschep** [comment]
That's an unfortunate conflict! I've tagged this as being closed by #5589 which will allow you to use any config file name you like 🙂

**Comment by lostcodingsomewhere** [comment]
is there any update on when #5589 will be merged in? looks like there is one review comment blocker, other than that is there anything remaining?

**Comment by dschep** [comment]
I've been trying to fix up that PR myself, but have run into all sorts of weird testing issues. Hopefully I'll be able to wrap up that feature soon once I figure out what's going on with the tests

**Comment by medikoo** [comment]
@csimi does npx still works for you that way?

As I test now `npx serverless` doesn't  pick the config now, but actual SLS installation. Therefore it looks as fixed (on npx side)
