### ISSUE TITLE
Unable to refer variable from other yml file in serverless.yml,deployment fails

### ISSUE THREAD

**Issue by sunkhanna** [serverless/serverless#5828]
I am trying to refer a variable in serverless.yml from another yml file,but when I run serverless deploy it does nothing.

**Serverless.yml

provider:
  name: ${file(./constants.yml):name}
  runtime: ${file(./constants.yml):runtime}
  region: ${file(./constants.yml):region}**

I have refereed variable in provider.

constants .yml is in same folder as serverless. 

D:\code\structuringserverless\serverless_sftp_workingcode>sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...

It does nothing after these two steps and just terminates without any error info.

**Comment by pmuens** [comment]
Hey @sunkhanna thanks for opening 👍

What version of serverless are you using?

**Comment by blissboy** [comment]
I am seeing the same behavior in 1.37.1

**Comment by sunkhanna** [comment]
I am using 1.36.3....and I realised I am able to refer to other files but when I am adding the reference in provider I am not able to refer and it abruptly terminates as above.

But I want it to refer in provider as well,whats wrong with that... :(

**Comment by medikoo** [comment]
Fixed with #8987
