### ISSUE TITLE
For project remove action, allow us to specify the profile to use.

### ISSUE THREAD

**Issue by yaochen** [serverless/serverless#583]
Seems every other action for ```project``` allows us to specify the profile; why not remove.

**Comment by pmuens** [comment]
Hey @yaochen the new release will enable project removement!

https://github.com/serverless/serverless/blob/master/lib/actions/ProjectRemove.js

**Comment by yaochen** [comment]
@pmuens 

I'm on 3.1 and I do see the project remove action. For each stage, I have separate accounts, and the remove action seems to take the default keys to invoke which ran into ```AccessDenied``` error.

**Comment by eahefnawy** [comment]
Now that profiles are associated with stages not projects, this should be possible in v0.5.

Thanks guys! Closing...
