### ISSUE TITLE
Secrets manager JSON not accessible

### ISSUE THREAD

**Issue by claygorman** [serverless/serverless#5838]
The documentation does not show how to access secrets from aws secrets manager stored in JSON. Is there an ETA to add this ability? If you have many secrets its very cost prohibitive to have 1 secret to 1 plain text value.

**Comment by exoego** [comment]
[${ssm} is a syntax to refer AWS Systems Manager Parameter Store](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store).
Parameter Store supports [String, StringList and SecureString](https://docs.aws.amazon.com/ja_jp/systems-manager/latest/userguide/param-create-console.html), but not JSON, if I understand correctly.

Perhaps, do you want to refer [AWS Systems Manager Documents](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-ssm-docs.html), which is in the form of JSON or YAML, like below ?

```json
{
  "schemaVersion" : "2.2",
  "description" : "Command Document Example JSON Template",
  "parameters" : {
    "Message" : {
      "type" : "String",
      "description" : "Example",
      "default" : "Hello World"
    }
  },
  "mainSteps" : [ {
    "action" : "aws:runPowerShellScript",
    "name" : "example",
    "inputs" : {
      "runCommand" : [ "Write-Output {{Message}}" ]
    }
  } ]
}
```

**Comment by claygorman** [comment]
@exoego I am referring to the aws secrets manager reference for the ${ssm} 

https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-using-aws-secrets-manager

This works fine when the secret is plain text but the default in aws console for secrets manager is JSON string (key/value). When using the default key/value for storing many secrets at once I am unable to decode it.

**Comment by exoego** [comment]
Opened a PR #5842.

**Comment by claygorman** [comment]
Wow thank you very much!
