### ISSUE TITLE
Choose Specific Lambda Function Roles for Specific Lambda Functions

### ISSUE THREAD

**Issue by msteckyefantis** [serverless/serverless#585]
This is a rehash of issue #174. Things have changed a lot since September, in a very positive way (good job Serverless crew, you rock for real!!).

 **I am trying to accomplish the following task:** To be able to choose specific lambda function roles for specific lambda functions.

I know how to set a role that will be set for all lambda functions when deployed, I do the following:

in my Serverless project file structure, for the file in bold,

/serverlessProject
----/nodejscomponent
----/meta
--------/_tmp
--------/resources
--------/variables
------------/**s-variables-dev-useast1.json**

I put the following:

```
{
  "region": "us-east-1",
  "iamRoleArnLambda": "arn:aws:iam::696969696969:role/role_A",
  "apiGatewayApi": "serverlessProject"
}
```

Now, when I deploy **any** function using Serverless, it will have role_A associated with it. But what if I want to have certain functions in my Serverless project to have role_B instead? Is there a way to make this happen? If so, how? If not, will this be fixed anytime soon? 

I think having the ability to choose specific lambda function roles for specific lambda functions would be immensely helpful for many Serverless users.

Any help would be greatly appreciated, thank you very much for your time!

-Michael

**Comment by ac360** [comment]
Hi Michael, 

We have just added support for this in `v0.4`.  Please use the `customRole` attribute in `s-function.json`

**Comment by msteckyefantis** [comment]
Just tested it out, works great. Thank you very much @ac360!
