### ISSUE TITLE
Prefixing logs

### ISSUE THREAD

**Issue by vernak2539** [serverless/serverless#5853]
I'm trying to use `serverless` and `serverless-artillery` to do load tests.

I have the following access for logs, based on my role.

```
{
  "Effect": "Allow",
  "Action": [
    "logs:DescribeLogGroups",
    "logs:CreateLogGroup",
    "logs:DeleteLogGroup"
  ],
  "Resource": "arn:aws:logs:eu-west-1:XXX:log-group:serverless-artillery-*"
}
```

Is there a way to prefix the logs serverless generates to accommodate for this access?

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
