### ISSUE TITLE
Add option to set Websocket API name

### ISSUE THREAD

**Issue by mekwall** [serverless/serverless#5874]
# This is a Feature Proposal

## Description

Please iplement similar options for WebSockets API as the ones that already exist for REST API (`apiName` and `apiGateway`).

**Comment by eahefnawy** [comment]
Thanks @mekwall ... will include that in the next release

**Comment by eahefnawy** [comment]
@mekwall you can specify a custom name with the following property:

```yml
provider:
    websocketsApiName: custom-websockets-api-name
```

We're just missing the docs for it, which I've added in #5867
