### ISSUE TITLE
Not able to deploy lambda function & stepfunctio getting error  Serverless plugin "serverless-step-functions" initialization errored: Unexpected token [

### ISSUE THREAD

**Issue by anudeepsinghpatelgithub** [serverless/serverless#5879]
Not able to deploy lambda function & stepfunctio getting error  Serverless plugin "serverless-step-functions" initialization errored: Unexpected token [

serverless deploy --region <region-name>--verbose

 Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-step-functions" initialization errored: Unexpected token [
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           4.2.2
     Serverless Version:     1.38.0
 
Build step 'Execute shell' marked build as failure

**Comment by anudeepsinghpatelgithub** [comment]
we install below dependencies before running serverless deploy command. 

#-- Install dependencies
npm install --only=production
npm install serverless
npm install serverless-external-s3-event
npm install serverless-plugin-existing-s3
npm install serverless-plugin-external-sns-events
npm install serverless-offline --save-dev

**Comment by pmuens** [comment]
Hey @anudeepsinghpatelgithub thanks for opening 👍

It looks like this is a bug in the step functions plugin and not in Serverless Framework core. It would be great if you could file an issue in the plugins repository.

/cc @horike37

**Comment by z3dtech** [comment]
@anudeepsinghpatelgithub  Your node version is 4.22 which is not supported!
