### ISSUE TITLE
Invoke command not recognizing AWS profile

### ISSUE THREAD

**Issue by BigChief45** [serverless/serverless#5882]
# This is a Bug Report

#### What went wrong?

Serverless is unable to recognize the specified profile using the `--profile` option with the `invoke` command. When using the command, it mistakenly uses the `default` profile configured in `~/.aws/credentials`

I have tried all the following combinations without any success:

`serverless invoke --profile production -s production -f my_function`
`serverless --profile production invoke -s production -f my_function`
`serverless invoke -s production -f my_function --profile production`

#### What did you expect should have happened?

Function on the specified AWS profile and stage to be invoked.

#### What stacktrace or error message from your provider did you see?

```
Function not found: arn:aws:lambda:us-west-1:<account_id>:function:<service>-<stage>-<function_name>
```

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: Ubuntu 14.04
* ***Stack Trace***:
* ***Provider Error messages***: `Function not found: arn:aws:lambda:us-west-1:<account_id>:function:<service>-<stage>-<function_name>`

**Comment by snurmine** [comment]
Did you try with `--aws-profile` e.g. 

`serverless invoke --aws-profile production -s production -f my_function`

**Comment by dschep** [comment]
What @snurmine said. `--aws-profile` is the option to set the AWS profile. you can also use the `AWS_PROFILE` environment variable (my preferred way )

**Comment by BigChief45** [comment]
Got it! Silly mistake, closing.
