### ISSUE TITLE
cloudformation:PreviewStackUpdate is not a valid IAM action

### ISSUE THREAD

**Issue by domdomegg** [serverless/serverless#5895]
# This is a Bug Report

## Description

The default [IAM credentials template for AWS](https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8) contains the permission `cloudformation:PreviewStackUpdate` which doesn't exist.

![image](https://user-images.githubusercontent.com/4953590/53702472-424fed80-3dff-11e9-86f0-096435ef254b.png)

[AWS docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html)

## Additional Data

* ***Serverless Framework Version you're using***: Following [docs](https://serverless.com/framework/docs/providers/aws/guide/credentials/) version 1.38.0, and gist version [2012-10-17](https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8)
* ***Operating System***: NA
* ***Stack Trace***: NA
* ***Provider Error messages***: "IAM does not recognize one or more actions"

**Comment by pmuens** [comment]
This has been addressed (see the [revisions](https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8/revisions)).

**Comment by domdomegg** [comment]
Thanks :tada:
