### ISSUE TITLE
Failed Deployment not resulting in Failed AWS Codebuild

### ISSUE THREAD

**Issue by craig-dae** [serverless/serverless#5897]
# This is a Bug Report

## Description

- Running serverless deploy in AWS Codebuild
- CloudFormation error occurred as a result of two plugins not combining well together (serverless-pseudo-parameters and serverless-plugin-split-stacks)
- CloudFormation Roles Back
- Codebuild does not treat this as a failure. Codebuild shows Success. 
- Presumably, the failure has an exit code of 0

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: Codebuild, which is Ubuntu
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

This has resulted in us taking longer to realize that we had a bug than we would have, since we were using Codebuild as a litmus test.

**Comment by pmuens** [comment]
Hey @craig-dae thanks for opening 👍

Based on your description it looks like you're using 2 separate plugins which might cause the problem you're describing here. Could you open up separate issues in the plugins repositories? Thanks!

**Comment by craig-dae** [comment]
The issue isn't the two different plugins. The issue is that, as a result of an invalid ARN, the serverless deploy failed, but we thought it was succeeding for a couple days because Codebuild returned a success. This is entirely a serverless issue, and I've already opened tickets for the actually issues with the plugins separately.

**Comment by kaitlynbrown** [comment]
I'm encountering this problem is well, and I am not using either of the plugins that @craig-dae is using. Why is this issue closed?
