### ISSUE TITLE
Azure Proxy Integration

### ISSUE THREAD

**Issue by rubenabix** [serverless/serverless#5901]
# Work with Azure Functions Proxies

## Description

* Azure Function Proxies is that it allows us to define a single API surface for multiple function apps.
* Reference: https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies

Similar or dependent issues:
https://github.com/serverless/serverless/issues/5901

**Comment by pmuens** [comment]
Hey @rubenabix thanks for opening 👍

Could you re-open the issue in the Azure Serverless Provider plugin so that we can track it there? Thanks in advance!
