### ISSUE TITLE
Missing files should be an error, not a warning.

### ISSUE THREAD

**Issue by undsoft** [serverless/serverless#5915]
# This is a Bug Report

## Description

I made a mistake when including one of the files and tried to include a file that doesn't exist:
```yaml
resources:
  - ${file(./serverless-cognito.yml)}
```

When running ``sls package`` this produces a warning.
I believe it should produce an error.

sls will exit with 0 code when there are only warnings, which will not stop execution when you are running sls deploy or package in CI.

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***:  macOS 10.14.1 (18B75)
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening 👍

Yes, I agree. This should definitely be an error. Unfortunately we cannot introduce this in v1 since this would result in a breaking change. We'll add this issue to the list of features for v2.
