### ISSUE TITLE
Give warning on invalid event definition

### ISSUE THREAD

**Issue by cameroncf** [serverless/serverless#5916]
# This is a Feature Proposal
A warning should be given when an event is defined with improper indentation. See linked issue.

## Description
It is surprisingly easy to miss an indentation on creating an event and result in function being created but the event silently fails to create. I don't know enough about Serverless Framework's architecture to use the perfect words here but I feel like when the YAML file is parsed by the Serverless Engine and the "events" element exist there should be some validation and a warning if the indention is incorrect, or perhaps more generally if an event appears to be defined but is incomplete.

Similar or dependent issues:
* #4884
https://github.com/serverless/serverless/issues/4844

**Comment by sthuber90** [comment]
What needs to be extended for this to work? Really looking forward to verifying that my _serverless.yml_ is valid before deploying changes. I think https://github.com/serverless/serverless/pull/7335 was a good first step, but does not cover "events"

**Comment by pgrzesik** [comment]
Hello @sthuber90 - what version of the Framework are you currently using? I believe all events have been already covered by schema validation

**Comment by sthuber90** [comment]
Yes. Sorry, I just tested with the latest version and saw that it works now as expected. How would I go ahead if I have warnings on properties required by plugins?

**Comment by pgrzesik** [comment]
Hey @sthuber90, no worries, happy to hear that it's now working as expected for you :tada: As for plugins - they also have the ability to define schema for their properties - please see the section of plugins docs for more details: https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema 

Do you have any specific examples of plugins that are causing warnings?

**Comment by sthuber90** [comment]
Hej @pgrzesik , thank you. We receive warnings for the _serverless-plugin-bind-deployment-id_ and _serverless-plugin-aws-alerts_ plugin. However, the current issue with https://github.com/serverless/serverless/issues/8392 is holding us back from upgrading at the moment.

**Comment by pgrzesik** [comment]
Hey @sthuber90 - thanks for listing the problematic plugins. As for the #8392 - I'm afraid the only option to migrate  through that issue is to follow the suggestions in that issue thread - the hashing algorithm changed, the best way to move forward would be to adapt to the newest hashing algorithm with upgrade to the latest version of the framework + setting `provider.lambdaHashingVersion: 20201221`.

**Comment by sthuber90** [comment]
Hej @pgrzesik , thank you but I tried with the recommended hashing version and the problem still exists. Didn't have any time yesterday to dig into the issue, if the problem persists I will comment it at #8392 or open a new issue.

**Comment by pgrzesik** [comment]
Understood :+1: Thank you and sorry for the trouble @sthuber90

**Comment by mnapoli** [comment]
@pgrzesik should we close this issue now?

**Comment by pgrzesik** [comment]
Yes, I think we can close it @mnapoli 👍
