### ISSUE TITLE
Deploy after param change fails

### ISSUE THREAD

**Issue by adriangabardo** [serverless/serverless#5917]
# This is a Bug Report

## Description

* What went wrong?
Every time I change the params on my serverless.yml file, the next deployment fails. For example, I have a path param called {id}, if I just change that to {username} the next deploy will fail. 
* What did you expect should have happened?
The next deploy should just happen and update the params.
* What was the config you used?
Function declaration with HTTP event and parameters set in the endpoint.
* What stacktrace or error message from your provider did you see?
An error occurred: ApiGatewayResourceApiRolesGroupnameVar - A sibling ({id}) of this resource already has a variable path part -- only one is allowed (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 0ce86ae7-45c6-11e9-bc6f-a5fe9cd72397).

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***: 1.37.1
* ***Operating System***: MacOS Mojave
* ***Stack Trace***: Serverless with AWS Lambdas
* ***Provider Error messages***:See the ApiGatewayResourceApiRolesGroupnameVar error above.

**Comment by pmuens** [comment]
Thanks for opening @adriangabardo 👍

This could be related to https://github.com/serverless/serverless/issues/3785.

**Comment by adriangabardo** [comment]
Sorry I didn't find that issue before. Yes they are related.
The problem is... the deploy first and CloudFormation delete old resource after results in having two pathParams in the same API endpoint at once, which is the reason it fails. Now, were it simply a matter of deleting old resources before doing a new deploy, it would be easy. But the issue is that if we do that, I believe in case of issues, the UPDATE-ROLLBACK would require for there to be the old resource to do the rollback.

Do you know if that's an issue fixable on Serverless or is it a CloudFormation/API Gateway issue?

**Comment by rodrigodgm** [comment]
Any solutions on this ?

**Comment by adriangabardo** [comment]
@rodrigodgm I'm afraid the issue is related to how the Serverless deploys are done. The only solution I have found so far for the pathParam issue is actually to delete the CloudFormation, which in turn deletes the API Gateway too. After deleting, a new deploy will work. The downside of this is that your function endpoints get altered.

**Comment by ColdFire87** [comment]
The solution I use when renaming a path param for a lambda is:
- rename path param
- comment out the function definition in `serverless.yaml` (or comment out the file import if you define it externally)
- `sls deploy`
- uncomment the fn definition & redeploy (`sls deploy`)

This has minimal impact...just a small downtime for the endpoint between deploys.

**Comment by Alan-Graton** [comment]
> The solution I use when renaming a path param for a lambda is:
> 
> * rename path param
> * comment out the function definition in `serverless.yaml` (or comment out the file import if you define it externally)
> * `sls deploy`
> * uncomment the fn definition & redeploy (`sls deploy`)
> 
> This has minimal impact...just a small downtime for the endpoint between deploys.



> The solution I use when renaming a path param for a lambda is:
> 
> * rename path param
> * comment out the function definition in `serverless.yaml` (or comment out the file import if you define it externally)
> * `sls deploy`
> * uncomment the fn definition & redeploy (`sls deploy`)
> 
> This has minimal impact...just a small downtime for the endpoint between deploys.

That was just perfect, thanks man ^-^
