### ISSUE TITLE
Move provider-specific logic from core/package plugin to aws/package plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#5918]
Right now lots of provider specific (mostly AWS) logic can be found the core, provider-agnostic `package` plugin.

We should refactor this so that the logic is encapsulated in the AWS specific `package` plugin.

**Comment by viegasdom** [comment]
Hi, is this issue still relevant? If so I'd like to jump in.

**Comment by medikoo** [comment]
Closing, as that, will eventually be covered with https://github.com/serverless/serverless/issues/6580
