### ISSUE TITLE
"serverless plugin create" command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#593]
It would be great if one could run `serverless plugin create` from the command line so that a new blank plugin is setup in the project.

This command should download the Plugin Boilerplate and do the setup command (linke linking, adding the plugin to the plugins array in s-project) automatically.

**Comment by ac360** [comment]
:+1:

**Comment by pmuens** [comment]
@ac360 https://github.com/serverless/serverless-plugin-boilerplate is not used here (I've modified the files from this repository and create a directory in the `templates` directory). This makes it independent from the boilerplate repository.

I think that there should be some automated test added.

**Comment by ac360** [comment]
Nice work @pmuens !!!  In v0.5!
