### ISSUE TITLE
Error after upgrading it to 1.39.0

### ISSUE THREAD

**Issue by prr19776** [serverless/serverless#5930]
The same code and deploy was working on 1.38.0

13:34:16 Serverless: Packaging service...
13:34:16 Serverless: Excluding development dependencies...
13:35:03 Serverless: Warning: Not deploying alerts on stage dev
13:35:03  
13:35:03   Type Error ---------------------------------------------
13:35:03  
13:35:03   Cannot read property 'substr' of undefined
13:35:03  
13:35:03      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
13:35:03  
13:35:03   Get Support --------------------------------------------
13:35:03      Docs:          docs.serverless.com
13:35:03      Bugs:          github.com/serverless/serverless/issues
13:35:03      Issues:        forum.serverless.com

**Comment by dschep** [comment]
Could you please provide some more details such as your `serverless.yml`?

**Comment by Kennytian** [comment]
My workaround is downgrade 1.38.0,  `yarn global add serverless@1.38.0`

**Comment by ReidWeb** [comment]
Looks to duplicate #5927 in which further detail is given by myself and others.

**Comment by pmuens** [comment]
Yes, this looks like a duplicate of #5927
