### ISSUE TITLE
Bitbucket pipeline fail

### ISSUE THREAD

**Issue by teddynted** [serverless/serverless#5932]
My pipeline just started failing out of the blue, I didn't install any new package nor make to the yaml file

I am getting this error:

ENOENT: no such file or directory, stat '/opt/atlassian/pipelines/agent/build/.serverless/.serverless/yalu.zip'

**Comment by ReidWeb** [comment]
Looks like a duplicate of #5928 - the issue not being with your BB pipeline, but the version of serverless you are using - roll back to using an older version for now.

```
yarn global add serverless@1.38.0
```
or
```
npm install -g serverless@1.38.0
````

**Comment by teddynted** [comment]
Hey ReidWeb,

Thanks for your timeous response, my serverless package is 1.26.1.

**Comment by teddynted** [comment]
I fixed it by changing serverless to serverless@1.37.1, Thanks ReidWeb.

**Comment by pmuens** [comment]
Just reverted #4188 which seems to be the root cause. Patch release should be out in ~30 minutes...
