### ISSUE TITLE
Enable Setting Amazon API Gateway API Key Value

### ISSUE THREAD

**Issue by laardee** [serverless/serverless#5935]
# This is a Feature Proposal

## Description

Finally, AWS added support for defining API Key value using CloudFront. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html#cfn-apigateway-apikey-value

This will help in the cases if you need to retain the same API key value and remove the stack and deploy it again, and with multi-region deployments where you need to define same API key for multiple API gateways.

**Comment by laardee** [comment]
I can take this one

**Comment by pmuens** [comment]
Great! Thanks @laardee :+1:

**Comment by laardee** [comment]
@pmuens this is now ready for review https://github.com/serverless/serverless/pull/5982

What I noticed is that the API key names must be unique when deploying with CloudFormation. From the console, you can create as many keys with the same name as you want, so it is a CF limitation.

For example, if I have a serverless.yml like this.

```
provider:
  name: aws
  runtime: nodejs8.10
  apiKeys:
    - keyOne
    - keyTwo
```

The generated CloudFormation then has `keyOne` which logical id is `ApiGatewayApiKey1` and `keyTwo`'s logical id is `ApiGatewayApiKey2`.

Then if I change the order of the keys

```
provider:
  name: aws
  runtime: nodejs8.10
  apiKeys:
    - keyTwo
    - keyOne
```
`keyTwo`'s logical id is now `ApiGatewayApiKey1` and `keyOne`'s `ApiGatewayApiKey2`.

The name change requires removal, so CF starts to create those resources, but it fails because both of the keys are already in the stack, waiting for removal.

The same thing happens with value change. If the value is changed CF tries to create a new API key and fail because if a key with the same name exists in the stack. 

I added an option only to add value for the key so that CF then create a name for the key. That way when the value is changed the key can be replaced. I don't usually care about the name of the key; only the value is what matters.

The reason for this limitation could be asked from AWS. Obviously, the unique name restriction is something that is implemented to CloudFormation but doesn't exist when creating API keys with the console or the CLI.
