### ISSUE TITLE
CloudFormation template normalization for WebSockets deployment resource

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#5940]
The WebSockets deployment logical id has a random number attached to it.

We should normalize it like it was done in https://github.com/serverless/serverless/pull/5885 for the Api Gateway deployment logical id so that re-deployments without config changes are skipped.

**Comment by gabrielrumiranda** [comment]
Can I take this issue ?

**Comment by preshetin** [comment]
I hope this issue is still relevant. Here is PR that should solve it.

Please let me know what you think about it.
