### ISSUE TITLE
Better support for users that uses multiple AWS accounts for each stage?

### ISSUE THREAD

**Issue by yaochen** [serverless/serverless#596]
For each stage I have, I create a separate account. For a few of the commands, I see the "-p" option to pass in the profile name when using the command. Commands such as ```resources deploy```, ```dash deploy```, ```env set``` always defaults to the first key we used which is the dev keys.

Ideally, all commands that deals with AWS; deploy, env, etc, should allow user to enter the profile so we can use different keys.

Anyone else using multiple accounts for multiple stages? How do you get around this? Any recommendation is appreciated.

PS: if this -p option is implemented for all possible AWS interacting commands, do we still need a admin.env? To my understanding, admin.env only contains the access/secret keys.

**Comment by martinmicunda** [comment]
+1

**Comment by ac360** [comment]
This is our main priority for v0.5

**Comment by brentax** [comment]
Awesome, I was just thinking of this! Would love to be able to `sls function deploy --profile prod`.

**Comment by eahefnawy** [comment]
added to v0.5. once we release (soon) you can have multiple stages in different aws accounts/profiles. You can then deploy your functions (or basically do anything) to these stages.

Closing...

**Comment by yaochen** [comment]
@eahefnawy 

is this committed to 0.5 branch or still pending merge?

**Comment by rehrumesh** [comment]
Any updates on this?

**Comment by wamoyo** [comment]
I'm a little unclear on this. I'm reading the documentation and it says "At the very least, use a dev and production stage. Use different AWS accounts for stages" here: https://serverless.com/framework/docs/providers/aws/guide/workflow/#using-stages 

Is this a requirement of the framework that we open a new AWS account for each stage? If not, how do we work with dev and production stages? I noticed a flag in the deploy command in the CLI, I assume that overrides what's in the serverless.yaml provider field.

If this is all wrapped up, I'm happy to update the documentation with what's above. Let me know, and I'll set up a pull request.

**Comment by mthenw** [comment]
@wamoyo

> Is this a requirement of the framework that we open a new AWS account for each stage?

No, it's not required. It's only recommendation.

> I noticed a flag in the deploy command in the CLI, I assume that overrides what's in the serverless.yaml provider field.

 `provider.stage` is a default stage use when you are running `sls deploy` without `--stage` param.

> If not, how do we work with dev and production stages?

By default framework use distinct names for Lambda function between environments so there should be no issue with deploying different stages under one account.

**Comment by wamoyo** [comment]
@mthenw Thanks! Most of that is really clear.

> By default framework use distinct names for Lambda function between environments so there should be no issue with deploying different stages under one account.

So stages in serverless don't map to stages in AWS: https://aws.amazon.com/blogs/compute/using-api-gateway-stage-variables-to-manage-lambda-functions/ ?

I'm going to dig in some more, and throw up a few more examples. Thanks again!
