### ISSUE TITLE
Doc Request: Working example of MOCK integration

### ISSUE THREAD

**Issue by sime** [serverless/serverless#5960]
# This is a Documentation Proposal

## Description

Serverless officially supports the `MOCK` integration method. Though documentation has no information about it. It only mentions that it is 'supported'.

> Use `http` for integrating with an HTTP back end, `http-proxy` for integrating with the HTTP proxy integration or **`mock`** for testing without actually invoking the back end.

The last point is false, as setting an endpoint with integration type `mock` returns 500.

A working example should be provided.

**Comment by xavivars** [comment]
I tried to use the `MOCK` integration, trying to figure out from the code how to use it, and I had to give up. Documentation on this would be awesome.

**Comment by resmall** [comment]
I'm looking for my first PR, I can take a look at it.
