### ISSUE TITLE
Shell substitution in serverless.yml

### ISSUE THREAD

**Issue by j3pic** [serverless/serverless#5965]
# This is a Feature Proposal

## Description

In https://github.com/serverless/serverless/issues/1801, which seems to be where things like `${opt:stage}` came from, it was proposed that there by a `${exec('command'}}` variable. This was not implemented, for whatever reason.

I have a service which depends on an AWS Certtificate Manager certificate, which is manually created. Which certificate it depends on depends on which AWS account I'm deploying to, and of course the certificates expire from time to time. AWS resources that depend on it will need the certificate's ARN.

But because there's no `exec` variable, I'm left with only these highly unpleasant ways to specify the ARN:

1. Hard-code the ARNs of the certificates into various `serverless.yml` files, making commits to update them as needed.
2. Instead of using a regular CloudFormation resource, write a custom Lambda-backed resource that looks up the ACM certificate and deploys the resource that needs it using the AWS SDK.
3. Introduce a preprocessing step to my Serverless deploy process, probably involving Jinja or something similar. In the preprocessing step, I'd use a shell script to look up the ARN of the certificate.

**Comment by herebebogans** [comment]
@j3pic another approach might be to use a[ javascript files reference](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-javascript-files) variable.

Then use aws-sdk in the reference to dynamically look up the certificate (acm.listCertificates()) based on a tag via the stage / environment name etc.

**Comment by medikoo** [comment]
Closing, as allowing to arbirtrary call system commands from Framework variables feels as controversial idea, and use case can already be solved with JS function file references
