### ISSUE TITLE
Resource templates inside component subfolders

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#597]
Components can have multiple subfolders. it would be great to add a resource.json file inside each subfolder to define what resources (e.g. DynamoDB, S3, ...) are used inside that component / subfolder (previously known as a module).

Should work nearly the same as with `s-templates.json`.

```
project
    component
    |_ s-resources.json
        users
            |_ s-resources.json
                function
                    |_ s-resources.json
```

---

Taken from Gitter:

> Let's say one component is called `nodejs` and this component has many functions (instead of modules). Now I have this structure `nodejs/posts/create` where `create` is the function and `posts` is a new subfolder I have added (to encapsulate it). It would be great to add a resource definition file for `posts` so that e.g. a DynamoDB is populated when I run `serverless resources deploy`.

---

Possible names:
- s-resources-cf.json
- s-resources.json
- s-resource-cf.part.json
- s-templates.ext.json
- s-resources-cf.ext.json

**Comment by ac360** [comment]
Keep in mind, we want to add Terraform support because they are doing great work over there at HashiCorp.  Hence the `s-resources-cf.json`.  It allows `s-resources-tf.json` to follow that convention.

**Comment by ac360** [comment]
We managed to get this in `v0.4`!!!  Thanks @pmuens

**Comment by pmuens** [comment]
@ac360 awesome! Thanks :+1:

**Comment by bennybauer** [comment]
Hey, is Terraform support still on the roadmap?
