### ISSUE TITLE
Unsettled promises :(

### ISSUE THREAD

**Issue by jamesdixon** [serverless/serverless#5972]
# This is a Bug Report

## Description

* What went wrong?

Upgraded serverless from 1.36.3 to the latest (1.40). Ran `sls deploy --stage=[stage]` and I got an error.

* What did you expect should have happened?

Expected the deployment to deploy without error.

* What was the config you used?
https://gist.github.com/jamesdixon/a951a605cf7d84e24e19e9246914bd65

* What stacktrace or error message from your provider did you see?

```
  ##########################################################################################
  # 2500: 0 of 1 promises have settled
  # 2500: 1 unsettled promises:
  # 2500:   file(config/variables.yml) waited on by: undefined
  # This can result from latent connections but may represent a cyclic variable dependency
  ##########################################################################################
```

Similar or dependent issues:
* #5675 

## Additional Data

Note that reverting to 1.36.1 resolved the issue. I also tried 1.37.x, 1.38.x and 1.39.x and all gave the same error.

* ***Serverless Framework Version you're using***:
1.40
* ***Operating System***:
OSX 10.14.4

**Comment by jamesdixon** [comment]
Hi, was just curious if there's an update on this? Was trying to upgrade to the latest version of Serverless and still running into this bug, unfortunately.

Thank you!

**Comment by itrathnasekara** [comment]
Hi, I am also getting a similar issue when accessing ssm parameters. My serverless version is 1.47.0 

Error : 

Serverless Information ----------------------------------
#####################################################################
  # 2502: 13 of 14 promises have settled
  # 2502: 1 unsettled promises:
  # 2502:   ssm:/vpc/devlocal/subnetId waited on by: undefined
  # This can result from latent connections but may represent a cyclic variable dependency
  ####################################################################

**Comment by k1tzu** [comment]
Getting this error continuously if I'm offline/not authorized.
Tried to set ```${ssm:MONGO_HOST~true, "mongodb://localhost:27017"}``` to serverless.yml
But it didn't help.

```Serverless: [AWS ssm undefined 0.133s 3 retries] getParameter({ Name: 'TELEGRAM_TOKEN', WithDecryption: true })
Serverless: Recoverable error occurred (Inaccessible host: `ssm.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS ssm undefined 0.425s 3 retries] getParameter({ Name: 'MONGO_USERNAME', WithDecryption: true })
Serverless: Recoverable error occurred (Inaccessible host: `ssm.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for 5 seconds. Try 1 of 4
 
 Serverless Information ----------------------------------
 
  ##########################################################################################
  # 2503: 1 of 6 promises have settled
  # 2503: 5 unsettled promises:
  # 2503:   ssm:TELEGRAM_TOKEN~true waited on by: undefined
  # 2503:   ssm:MONGO_USERNAME~true waited on by: undefined
  # 2503:   ssm:MONGO_PASSWORD~true waited on by: undefined
  # 2503:   ssm:MONGO_HOST~true waited on by: undefined
  # 2503:   ssm:MONGO_DB_NAME~true waited on by: undefined
  # This can result from latent connections but may represent a cyclic variable dependency
  ##########################################################################################
 
 
 Serverless Information ----------------------------------
 
  ##########################################################################################
  # 5003: 1 of 6 promises have settled
  # 5003: 5 unsettled promises:
  # 5003:   ssm:TELEGRAM_TOKEN~true waited on by: undefined
  # 5003:   ssm:MONGO_USERNAME~true waited on by: undefined
  # 5003:   ssm:MONGO_PASSWORD~true waited on by: undefined
  # 5003:   ssm:MONGO_HOST~true waited on by: undefined
  # 5003:   ssm:MONGO_DB_NAME~true waited on by: undefined
  # This can result from latent connections but may represent a cyclic variable dependency
  ##########################################################################################
 
Serverless: [AWS ssm undefined 0.241s 3 retries] getParameter({ Name: 'TELEGRAM_TOKEN', WithDecryption: true })
Serverless: Recoverable error occurred (Inaccessible host: `ssm.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS ssm undefined 0.525s 3 retries] getParameter({ Name: 'MONGO_USERNAME', WithDecryption: true })
Serverless: Recoverable error occurred (Inaccessible host: `ssm.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for 5 seconds. Try 2 of 4
```

**Comment by vmasule** [comment]
In my case it was due to `proxy` connectivity issue. I think error shown by serverless is misleading.

Please correct that in logging. It should show there is connectivity issue or something like that.

**Comment by phalverson** [comment]
> Please correct that in logging. It should show there is connectivity issue or something like that.

The message begins with "This can result from latent connections..", so that should've been your first clue.

**Comment by jamesdixon** [comment]
Any update on this issue? I can confirm this is still a problem in 1.5.8.

The only way I can `sls deploy` to run is to downgrade to 1.36.3...

**Comment by mikezange** [comment]
Ran into this today, upgrading to 1.58.0 give slightly different messages:

`Serverless Information ----------------------------------
 
  ############################################################################################
    # 2505: 36 of 37 promises have settled
    # 2505: 1 are taking longer than expected:
    # 2505:   ssm:/aws/reference/secretsmanager/.....~true waited on by: ${ssm:/aws/reference/secretsmanager/......~true}
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
 
 
 Serverless Information ----------------------------------
 
  ############################################################################################
    # Completed after 2615ms
    # 41 promises are in the following states:
    #   resolved: 41
    #   rejected: 0
    #   pending:  0
    ##########################################################################################
 
`

**Comment by gndelia** [comment]
Same issue here. I cannot retrieve a secrete manager and I'm getting this error

**Comment by clar-cmp** [comment]
I've been having issues running `serverless-s3-local` with errors like:

```
# 2502:   ssm:/infra/bucket/serverless waited on by: ${ssm:/infra/bucket/serverless, ''}
```

It appears that only s3-local has these issues, and only with SSM keys under provider. But, this only happens when no valid AWS credentials are available, and even if the credentials yougive don't have access to SSM, it still works.

**Comment by hqtsky** [comment]
problem for me using 1.65.0:
 Serverless Information ----------------------------------

  ############################################################################################
    # 10012: 23 of 28 promises have settled
    # 10012: 5 are taking longer than expected:
    # 10012:   ssm:/...-cognito/prod/COGNITO_USER_POOL_ARN waited on by: ${env:COGNITO_..._APP_USER_POOL_ARN, ssm:/...-cognito/prod/COGNITO_USER_POOL_ARN} ${env:COGNITO_..._APP_USER_POOL_ARN, ssm:/...-cognito/prod/COGNITO_USER_POOL_ARN}
    # 10012:   ssm:/...-admin-cognito/prod/COGNITO_USER_POOL_ID waited on by: ${env:COGNITO_USER_POOL_ID, ssm:/...-admin-cognito/prod/COGNITO_USER_POOL_ID}
    ...
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################

**Comment by simsketch** [comment]
Also dealing with this issue intermittently on the latest serverless 1.66.0

**Comment by phmasek** [comment]
Getting this issue when deploying through bitbucket-pipelines but not locally. Serverless version `1.73.1`


````bash
    #########################################################################################
    # 62554: 4 of 11 promises have settled
    # 62554: 7 are taking longer than expected:
    # 62554:   ssm:<redacted>-dev waited on by: ${ssm:<redacted>-dev}
    # 62554:   ssm:<redacted>-dev waited on by: ${ssm:<redacted>-dev}
    # 62554:   ssm:<redacted>-dev~true waited on by: ${ssm:<redacted>-dev~true}
    # 62554:   ssm:<redacted>-dev waited on by: ${ssm:<redacted>-dev}
    # 62554:   ssm:<redacted>-dev~true waited on by: ${ssm:<redacted>-dev~true}
    # 62554:   ssm:<redacted>-dev waited on by: ${ssm:<redacted>-dev}
    # 62554:   ssm:<redacted>-dev~true waited on by: ${ssm:<redacted>-dev~true}
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
````


My bitbucket-pipelines.yml:

````yaml
image: node:11.13.0-alpine

pipelines:
  branches:
    development:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Deploy to AWS
          caches:
            - node
          script:
            - SLS_DEBUG=1 ./node_modules/serverless/bin/serverless.js config credentials --stage dev --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
            - SLS_DEBUG=1 ./node_modules/serverless/bin/serverless.js create_domain
            - SLS_DEBUG=1 ./node_modules/serverless/bin/serverless.js deploy --stage dev
            
````

**Comment by aegbert5** [comment]
Have you set up your access keys via AWS IAM? It could be that AWS is not allowing you to access SSM because you do not have the right permissions. I had a similar problem, but these are the steps I took to remediate it.

1) Go to AWS IAM and generate an access key for your user.
2) Copy the access key credentials, run 'aws configure' on your local machine, and insert them there.

**Comment by phmasek** [comment]
@aegbert5 I successfully deployed it with the same credentials locally so I do not believe it is the IAM permissions.

Could it have something to do with the network?

**Comment by koshyviv** [comment]
I think I am having a similar issue but seems to be with cyclical dependency

```
  ############################################################################################
    # 15000: 0 of 0 promises have settled
    # 15000: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
```

The entire pipeline log/repo is here - https://gitlab.com/koshyviv/coda-learn/-/jobs/1079048104

**Comment by s1mrankaur** [comment]
Is there an update here?

**Comment by simsketch** [comment]
@s1mrankaur are you using the latest version of serverless?

**Comment by s1mrankaur** [comment]
@simsketch  I am , yes!

**Comment by simsketch** [comment]
I haven't run into this issue recently, but in my experience it was only happening intermittently, and it may have been dependent on a solid network connection. Is it happening consistently for you or just once in a while?

**Comment by s1mrankaur** [comment]
@simsketch  Consistently. With other team members as well. Also, we have MFA enabled and we are using lerna to run sls deploy command in each of the services. Lerna does not ask for user input so we use it as follows:

    "deploy:local": "eval \"`aws-auth-helper` lerna run deploy:sandbox --stream\"",


aws-auth-helper prompts for the MFA code and we input it. I believe this was working okay until very recently.  Is there a better way to do it?

**Comment by medikoo** [comment]
Closing, as new variables engine has very different engine and it's unlikely to share same issues
