### ISSUE TITLE
Add environment variable with lambda function's name

### ISSUE THREAD

**Issue by orwell1984** [serverless/serverless#5976]
# This is a Feature Proposal
## Description
For usage in tracing, I need to be able to access lambda function's name. It would be very handy to have it set as environment variable and relatively easy to implement, I presume.

Similar or dependent issues:
## Additional Data

* ***Serverless Framework Version you're using***:
latest
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by powelli** [comment]
More generally, we have been trying to find a way to get access to attributes of a function to pass in as environment variables and tags.

Our standard tagging convention uses the function name as part of a tag for cost reporting purposes. And as the @orwell1984 suggests we would also like to pass the function name as an env var to allow it's usage within the function execution itself.

We are attempting to do something similar by referencing the function attributes directly, but this means repeating the function name e.g.
```functions:
  function_one:
    handler: handlers.function_one.main
    name: ${self:provider.stage}-function_one
    timeout: 30
    memorySize: 128
    environment:
      name: ${self:functions.function_one.name}
    tags:
      billing: something-${self:functions.function_one.name}
  function_two:
    handler: handlers.function_two.main
    name: ${self:provider.stage}-function_two
    timeout: 30
    memorySize: 128
    environment:
      name: ${self:functions.function_two.name}
    tags:
      billing: something-${self:functions.function_two.name}```

It would be great if there was a pseudo-parameter or placeholder to refer to the function/resource that was being defined, so you could do something like:
```    environment:
      name: ${self:current_item.name}
    tags:
      billing: something-${self:current_item.name}```

**Comment by Tanax** [comment]
Why not just use the CloudFormation default name of a Lambda?
It's something like `stackName-CFResourceName-randomStuff`, example `MyStack-MyFunction-ABC123`. Makes it extremely easy to debug and look up logs. In addition, it's already built into CloudFormation so Serverless doesn't even need to do any naming of the Lambda function :)

**Comment by herebebogans** [comment]
Might be misunderstanding the idea but you can already get the function name from the [lambda context object](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html).

eg in node 

```
module.exports.handler = async (event, context) => {
  console.log('lambda function is ', context.functionName);
}
```

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.

**Comment by ronyeh-lb** [comment]
please reopen
we need this ability to reference itself
name: ${self:current_item.name}
