### ISSUE TITLE
24 error 404 Not Found - GET https://registry.npmjs.org/serverless-g- Not found

### ISSUE THREAD

**Issue by reyesvicente** [serverless/serverless#5979]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'serverless-',
1 verbose cli   'g' ]
2 info using npm@6.9.0
3 info using node@v11.12.0
4 verbose config Skipping project config: /Users/highcenoid/.npmrc. (matches userconfig)
5 verbose npm-session 633f05d255a66eb2
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/g 499ms (from cache)
9 silly pacote tag manifest for g@latest fetched in 503ms
10 http fetch GET 404 https://registry.npmjs.org/serverless- 1078ms
11 http fetch GET 404 https://registry.npmjs.org/serverless- 613ms
12 silly fetchPackageMetaData error for serverless-@latest 404 Not Found - GET https://registry.npmjs.org/serverless- - Not found
13 timing stage:rollbackFailedOptional Completed in 1ms
14 timing stage:runTopLevelLifecycles Completed in 6332ms
15 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/serverless- - Not found
15 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
15 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
16 verbose statusCode 404
17 verbose pkgid serverless-@latest
18 verbose cwd /Users/MY_USER
19 verbose Darwin 18.5.0
20 verbose argv "/usr/local/Cellar/node/11.12.0/bin/node" "/usr/local/bin/npm" "install" "serverless-" "g"
21 verbose node v11.12.0
22 verbose npm  v6.9.0
23 error code E404
24 error 404 Not Found - GET https://registry.npmjs.org/serverless- - Not found
25 error 404
26 error 404 'serverless-@latest' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
28 error 404 Note that you can also install from a
29 error 404 tarball, folder, http url, or git url.
30 verbose exit [ 1, true ]

**Comment by exoego** [comment]
There is no package named `serverless-`.
`serverless` is correct.

**Comment by reyesvicente** [comment]
> There is no package named `serverless-`.
> `serverless` is correct.

I meant serverless-g
