### ISSUE TITLE
Enable CAPABILITY_AUTO_EXPAND on CloudFormation deploys

### ISSUE THREAD

**Issue by pofallon** [serverless/serverless#5995]
# This is a Feature Proposal

## Description

We're working on a plugin that adds a `Transform` directive to the compiled CloudFormation template (in order to comply with some organizational standards).  However, a serverless project that leverages this plugin fails to deploy with the error: `Requires capabilities : [CAPABILITY_AUTO_EXPAND]`.  From [looking through the code](https://github.com/serverless/serverless/blob/15ca8ace6b22a5c1b9f22c9f310c591ca03eb2ea/lib/plugins/aws/lib/updateStack.js#L67-L70) it appears that the CloudFormation `Capabilities` cannot be manipulated prior to updating the stack.

It would be great to have a way for this additional capability to be specified prior to stack updates.  For example:

* Allow the list of capabilities to be manipulated via a plugin prior to deploy, or ...
* Provide a command line option (`--aws-cfn-capabilities`?) that takes a list of strings (although there's only one additional one at the moment) and merges these capabilities into those already present in the code.

I'm happy to submit a PR for this, just let me know.  Thank you!

**Comment by pofallon** [comment]
I just realized that the `Transform` directive can be added directly to the `serverless.yml` file (so no plugin is necessary on our part).  While this results in the same error, a more obvious solution is to just add this Capability if a transform is detected in the template.  This is a simple addition, so I'll submit a PR for discussion.  Thanks again!

**Comment by dr-robert** [comment]
This would be a huge benefit for my company and then community. This also would help enable broader adoption of the Serverless Framework.
