### ISSUE TITLE
Solution to  CloudFormation's 200 Resource Limit

### ISSUE THREAD

**Issue by etc-tiago** [serverless/serverless#5999]
I'm looking for a solution of the limitation of Cloudformation resource limits. Currently the stack I am working on is over 300 resources, the API has 64 endpoints endpoints, but more will be needed. 

I would like to know if I can create two files that make the serverless.yml function, something like stack-a.yml, stack-b.yml? And when the `deploy` command is run, indicate which stack I'm referencing.

Examples of use in this "separation:
`sls deploy --stage prod --file stack-a.yml` // Create a part of API
`sls deploy --stage prod --file stack-a.yml` // Create another part of API
`sls deploy --stage prod --file stack-b.yml` // ...

Is this possible these days? If not, I'd like to know the yours opinion so that I can work to add this to serverless framework (a preview version).

**Comment by eahefnawy** [comment]
Thanks for thinking about a solution to this tough problem @etc-tiago! Do you think this would be a breaking change?

**Comment by darrenhgc** [comment]
FWIW, we're currently using the [split stacks plugin](https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/15) to work around the cloud formation resource limit.

Shortly after, we ran up against a limit on the number of outputs allowed in the `APINestedStack` [#15](https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/15).

We also considered using the [domain manager plugin](https://github.com/amplify-education/serverless-domain-manager) to break the project up.

**Comment by garethmcc** [comment]
Would it not be possible to break up this very large service into smaller ones. Kind of lean on the micro of microservices a little?

**Comment by pmuens** [comment]
Yes, splitting up the stack (e.g. via the aforementioned plugin) should be the way to go here.

Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
