### ISSUE TITLE
[SPEC V1] SNS subscriptions

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#60]
At the moment SNS subscriptions - event sources - are lost when redeploying lambdas.

So a file that has sns subscription descriptors, and sns.subscribe() as part of `jaws deploy` would be good.

**Comment by jwulf** [comment]
What would work is an SNS subscription function that takes a list of SNS subscriptions during deploy, and then just sets them up.

Something like this, but iterating over an array of objects:

```
module.exports.registerSNS(freq) {
  Lambda.getFunctionConfiguration({ FunctionName: thisLambdaFunctionName },
    function (err, data) {
      if (err) return console.log(err);
      var params = {
        Protocol: 'lambda',
        TopicArn: freq,
        Endpoint: data.FunctionArn
      };
      sns.subscribe(params, function (err, data) {
        if (err) return console.log(err, err.stack); // an error occurred
        if (!data.SubscriptionArn) {
          var confirm_params = {
            Token: 'STRING_VALUE', /* required */
            TopicArn: freq,
            AuthenticateOnUnsubscribe: 'STRING_VALUE'
          };
          sns.confirmSubscription(confirm_params, function (err, data) {
            if (err) return console.log(err, err.stack); // an error occurred
            else console.log(data);           // successful response
          });
        } else console.log('Note: Already subscribed to ' + data.SubscriptionArn);
      });
    });
}
```

Where would I specify the SNS subscriptions? In `lambda.json`? Or does it need a separate `wiring.json` file?

I'll probably extend it with other things as well, like registering workflow types, etc...

**Comment by jwulf** [comment]
Pre- and post- deployment hooks in `jaws deploy` would allow easy prototyping and extensibility.

**Comment by doapp-ryanp** [comment]
Pretty sure this will be fixed in the v1.0.0 branch. Current deploy deletes then re-creates lambda which is causing SNS breakage. New code will do update and preserve.  I like the idea of hooks.

**Comment by jwulf** [comment]
Cool. We also need a mechanism to create them initially (and to function as documentation of the app's structure).

**Comment by doapp-ryanp** [comment]
I don't think hooking up SNS to invoke lambda is in the scope of JAWS. Just my opinion though.

**Comment by ac360** [comment]
I do like the idea of the pre/post deploy hooks.  I'm going to think about that.  Maybe those are just functions you can specify in the JSON file located in the lambda's folder.  Super simple.

**Comment by jwulf** [comment]
This request is fulfilled by https://github.com/jaws-framework/JAWS/pull/214

**Comment by ac360** [comment]
Event support is in v0.4
