### ISSUE TITLE
AWS Billing increase everyday but CloudFormation, Lambda deleted?

### ISSUE THREAD

**Issue by kimthangatm** [serverless/serverless#6003]
1. Serverless use Mongo . MongoDB run on EC2
2. Remove EC2 MongoDB, Remove CloudFormation, Lambda, ApiGateway, **all AWS services on Account are empty**
3. Billing increase everyday for **Lambda compute time**

4. Another account use DynamoDB. Same bug like this.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
