### ISSUE TITLE
Skipped CF step prevents plugin from working

### ISSUE THREAD

**Issue by cscetbon** [serverless/serverless#6009]
I'm using plugin https://github.com/svdgraaf/serverless-pseudo-parameters/issues, however it does not work when deploying only one function cause CloudFormation is skipped by updateFunctionConfiguration
see https://github.com/serverless/serverless/pull/4173/files#diff-4cbb6c3b54085f7b84b5aea9b859bb1eR141. 

Can you think of any way to make it possible for a plugin in that case ? by updating that function and allowing it to use CF ? See https://github.com/svdgraaf/serverless-pseudo-parameters/issues/15#issuecomment-481220518 for  more details.

**Comment by pmuens** [comment]
Hey @cscetbon thanks for opening :+1:

Can you please file an issue in the plugin repository since this is something which needs to be fixed in the plugin and not in core? Thanks!

**Comment by cscetbon** [comment]
@pmuens that was the question. The author means it can't be changed cause it uses CF to get this information but the function update are done directly and not through CF if I understand correctly what he said. Are you saying it's something that also can't be done in the core ?
