### ISSUE TITLE
Support wild-cards in cors multiple origins

### ISSUE THREAD

**Issue by tdmartino** [serverless/serverless#6012]
# This is a Feature Proposal

## Description
Allow passing wildcards in origins (example https://*.mydomain.com) so that the behaviour is similar to what you can achieve with an actual server.

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Many setups use multiple sub-domains, in which case you want to  simply allow all sub-domains from a specific domain. This is a common paradigm in htaccess files, s3 configurations, etc. The CORS spec does not allow for wildcards, but building on top of this pr  will make https://github.com/serverless/serverless/pull/5740 it fairly easy to match the requesting domain to the wildcard value, and use the requesting domain in the template.

* If there is additional config how would it look

Similar or dependent issues:
* https://github.com/serverless/serverless/pull/5740

**Comment by exoego** [comment]
@tdmartino Could you fix hyperlinks to PR? 
https://github.com/serverless/serverless/pull/5740https://guides.github.com/features/mastering-markdown/ seems broken.

**Comment by tdmartino** [comment]
fixed links

**Comment by tdmartino** [comment]
@exoego I am not 100% sure of the process, it says we should open an issue before submitting a pr, this is the issue. If nobody comments on it, it mean you guys are not interested? When can/should I start working on this? Thank you!

**Comment by exoego** [comment]
@tdmartino 
I would like you to understand that core develeopers may not dedicate themselves 100% to watch every activities on repository for reasons,  so it may take a weeks or even months to get resnponse from them.

It is all right 👍  to open a PR without waiting response, to the best of my relief.
Based on my experience, I had opened many PRs to servereless framework and other OSSs without waiting responses on issue. 
Most of all maintainers took PR seriously but happily, found a time for review, and merged PRs.

It would be very helpful if you find a solution to this issue and open a PR !!

**Comment by tdmartino** [comment]
@exoego thanks for the response. Sorry if I sounded impatient, I was just trying to figure out the process. I have a pr ready locally but I cannot push my branch. Can you create a branch for me so I can push my code for review?
