### ISSUE TITLE
https://serverless.com is not working!

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [serverless/serverless#6020]
https://serverless.com/ is not working. The page is not opening at all.

**Comment by eahefnawy** [comment]
hmmm seems to be working for me 🤔

**Comment by ahmed-abdulmoniem** [comment]
I have tried from WIFI / Mobile data ... all is not working!

Other websites are working just fine!

May be it is only me?

Any one can confirm?

**Comment by delprofundo** [comment]
slow but its there

**Comment by ahmed-abdulmoniem** [comment]
I am trying but I am not able to open it at all!

**Comment by ahmed-abdulmoniem** [comment]
Asked another friend .. and it is not working at his side as well!

**Comment by delprofundo** [comment]
its networking. looks like routing issues inside megaport or somewhere

**Comment by eahefnawy** [comment]
https://downforeveryoneorjustme.com/serverless.com

**Comment by ahmed-abdulmoniem** [comment]
OK thanks @eahefnawy

**Comment by pmuens** [comment]
@ahmed-abdulmoniem Quick update that it seems to be related to https://twitter.com/netblocks/status/1118112833366102016

**Comment by ahmed-abdulmoniem** [comment]
@pmuens Seems that this is the problem!

Any way to read the docs from another place other than using VPN?

**Comment by eahefnawy** [comment]
@ahmed-abdulmoniem our website fetches the docs directly from here:
https://github.com/serverless/serverless/tree/master/docs

Keep in mind though this these docs in master can sometimes reflect changes that was not yet released. In other words, it's "too updated" 😅

**Comment by ahmed-abdulmoniem** [comment]
Thanks @eahefnawy
