### ISSUE TITLE
Variables: Introduce access to resolved `stage` via `sls:stage`

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#6031]
At the moment to reference the region or stage you have to do:

```
${opt:stage, self:provider.stage, 'dev'}
${opt:region, self:provider.region, 'us-east-1'}
```

Since this is pretty common, it would be awesome to have simple variables that aliase that, e.g.

```
${sls:stage}
${sls:region}
```

--- 

_Maintainer note_

`region` is AWS specific, therefore it's expected to be handled in other proposal: https://github.com/serverless/serverless/issues/9005

**Comment by mnapoli** [comment]
@pmuens you added the `needs feedback` label, are you waiting for feedback from me? Let me know if I need to do anything to make the issue clearer.

**Comment by mnapoli** [comment]
I have opened a PR: #6049

**Comment by medikoo** [comment]
This is pretty easy now to implement with a new variables resolver. It's a question of extending the `sls` source configured here: https://github.com/serverless/serverless/blob/master/lib/configuration/variables/sources/instance-dependent/get-sls.js.

All properties that are passed to `resolve` are listed here: https://github.com/serverless/serverless/blob/5392a7dce2a325d3f93d8e8508d63d16d93c6f51/lib/configuration/variables/resolve.js#L464-L474

Therefore e.g. `stage` can be resolved as:

```javascript
module.exports = (serverlessInstance) => {
  return {
    resolve: async ({ resolveConfigurationProperty, options }) => {
      let stage = options.stage;
      if (!stage) stage = await resolveConfigurationProperty(["provider", stage"]);
      if (!stage) stage = "dev";
  }
};
```
   
PR's welcome!

**Comment by mnapoli** [comment]
Ohh yeah, and thanks a lot for the guidance! I'll try to work on this tomorrow! (famous last words)

**Comment by mnapoli** [comment]
@medikoo I'm confused by the fact that `${sls:XXX}` variables are defined in 2 places:

- the one you mentioned
- [Variables.js](https://github.com/serverless/serverless/blob/d26e2ae4b8db944bb6f9de55043b46285f08e726/lib/classes/Variables.js#L586-L593)

Should I edit both?

Regarding tests as well: should I also add tests in `Variables.test.js`?

So far I'm editing `get-sls.test.js`, are there functional tests to edit/create somewhere?

**Comment by medikoo** [comment]
@mnapoli `Variables.js` is old resolver which will be removed with v3, we keep it just for legacy compliance but do not extend with new features. So let's not update that one.

Concerning testing, all related need to be put it into `get-sls.test.js` (it'll be nice to keep there 100% tests coverage)

**Comment by mnapoli** [comment]
OK thanks, that answers my questions. Because I need to run tests in different scenarios:

- without options nor `provider.stage`
- without options but with `provider.stage` defined
- with CLI options

I need to edit the test a little bit. I'll open the PR and feel free to let me know how to reorganize things the way you prefer.

**Comment by mnapoli** [comment]
I've opened #9296
