### ISSUE TITLE
Unintuitive behavior for package exclude globs

### ISSUE THREAD

**Issue by earksiinni** [serverless/serverless#6033]
# This is a Bug Report

## Description

* What went wrong?

I wanted to exclude every subdirectory in my project root _except_ for `node_modules` when packaging. The glob I originally used was `!node_modules/**` under `exclude` (see below), but this actually has the opposite effect (includes `node_modules`) due to this code: https://github.com/serverless/serverless/blob/5d73e815efbe24242e9624c9e04ade67a14d7752/lib/plugins/package/lib/packageService.js#L215-L221

I get the reasoning behind the current implementation (e.g., "exclude means not include, so exclude exclamation point means not include not this, which in boolean logic means include this"), but it seems to contradict common sense (e.g., "exclude means reject, so exclude exclamation point means reject everything but this.")

I'm able to work around this behavior by using the following glob: `!!!node_modules/**` Another potential workaround would be to use `!node_modules/**` under `include`, but then you don't get the benefit of Serverless trimming dev dependencies since the trimming occurs after excluding and before including.

* What did you expect should have happened?

Using `!node_modules/**`, I expected that every directory except for node_modules would have been excluded from my package.
* What was the config you used?

*serverless.yml*

```
package:
  exclude:
    - "!!!node_modules/**"
```

* What stacktrace or error message from your provider did you see?

Subdirectories other than `node_modules` got included into my package.

## Additional Data

* ***Serverless Framework Version you're using***: 1.40.0
* ***Operating System***: macOS 10.14.3
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
