### ISSUE TITLE
Template validation error: Template parameters must be a map

### ISSUE THREAD

**Issue by sajjad207** [serverless/serverless#6037]
i am learning to write Cloudformation code in yaml and i cant seem to figure out whas the issue in this code  the error is "Template validation error: Template parameters must be a map"
heres my yaml Code
===========================================================

---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  My Frist Yaml Stack for cloudformation

Metadata:

Parameters:

Mappings:

Conditions:

Resources:
    myVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16     # required
        EnableDnsHostnames: true     # optional
        EnableDnsSupport: true     # optional
        Tags:                # optional, list of Tag
          - Key: Name
            Value: myVPC

    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:                # optional, list of Tag
          - Key: Name
            Value: InternetGateway
    VPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        InternetGatewayId:
          - Ref: InternetGateway     # optional
        VpcId:
          - Ref: myVPC     # required
    EC2Subnet:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-2a     # optional
        CidrBlock: 10.0.10.0/20     # required
        MapPublicIpOnLaunch: true     # optional
        Tags:                # optional, list of Tag
          - Key: Name
            Value: EC2Subnet
        VpcId:
          - Ref: myVPC     # required
    RDSSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-2b     # optional
        CidrBlock: 10.0.30.0/20     # required
        Tags:                # optional, list of Tag
          - Key: Name      # optional
            Value: RDSSubnetA     # optional
        VpcId:
          - Ref: myVPC     # required
    RDSSubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-2c     # optional
        CidrBlock: 10.0.70.0/20     # required
        Tags:                # optional, list of Tag
          - Key: Name     # optional
            Value: RDSSubnetB     # optional
        VpcId:
          - Ref:  myVPC     # required
    RDSSubnetGroupA:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: This is the Subnet group for subnet A and B     # required
        SubnetIds:                # required, list of String
          - Ref:  RDSSubnetA
          - Ref:  RDSSubnetB
        Tags:                # optional, list of Tag
          - Key: Name      # optional
            Value: RDSSubnetGroupA     # optional
    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        Tags:                # optional, list of Tag
          - Key: Name      # optional
            Value: RouteTable     # optional
        VpcId:
          - Ref: myVPC     # required
    InternetRoute:
      Type: AWS::EC2::Route
      DependsOn: VPCGatewayAttachment
      Properties:
        DestinationCidrBlock: 0.0.0.0/0     # optional
        GatewayId:
          - Ref:  InternetGateway     # optional
        RouteTableId:
          - Ref:  RouteTable     # required
    EC2SubnetARouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          - Ref:  RouteTable     # required
        SubnetId:
          - Ref:  EC2Subnet     # required
    RDSSubnetARouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          - Ref:  RouteTable    # required
        SubnetId:
          - Ref:  RDSSubnetB     # required
    RDSSubnetBRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          - Ref:  RouteTable     # required
        SubnetId:
          - Ref:  RDSSubnetB     # required
    RDSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: RDS Security Group
        SecuriyGroupIngress:
          - IpProtocol: tcp
            FromPot: 3306
            ToPort: 3306
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
        VpcId:
          - Ref:  myVPC
        Tags:
          - Key: Name      # optional
            Value: RDSSecurityGroup     # optional
    EC2SecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: EC2 Security Group
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: '-1'
            CidrIp: 0.0.0.0/0
        VpcId:
          - Ref:  myVPC
        Tags:
          - Key: Name
            Value: EC2SecurityGroup
    RDSInstanceA:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 7     # optional
        AllowMajorVersionUpgrade:  false    # optional
        AutoMinorVersionUpgrade: false     # optional
        BackupRetentionPeriod: 7     # optional
        DBInstanceIdentifier: RDSTest     # optional
        DBName: YamlRDS    # optional
        DBSubnetGroupName:
          - Ref:  RDSSubnetGroupA     # optional
        Engine: MYSQL     # optional
        EngineVersion: 5.7.22     # optional
        MasterUserPassword: sajjad1234     # optional
        MasterUsername: sajjad     # optional
        MultiAZ: false     # optional
        Port: 3306     # optional
        PubliclyAccessible: false     # optional
        StorageEncrypted: false     # optional
        StorageType: gp2    # optional
        Tags:                # optional, list of Tag
          - Key: Name     # optional
            Value: RDSInstanceA     # optional
        VPCSecurityGroups:                # optional, list of String
          - Ref:  RDSSecurityGroup
    EC2InstanceA:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-02bcbb802e03574ba     # required
        InstanceType: t2.micro     # optional
        KeyName: mykey     # optional
        Monitoring: false     # optional
        SecurityGroupIds:                # optional, list of String
          - Ref:  EC2SecurityGroup
        SubnetId:
          - Ref:  EC2Subnet     # optional
        Tags:                # optional, list of Tag
          - Key: Name     # optional
            Value: Ec2Instance     # optional
        UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -ex
            - |
              sudo yum install -y mysql
Outputs:

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
