### ISSUE TITLE
ResourcesDiff: Show differences between local CF template and a deployed staged/regional template

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#604]
A handy command to show the differences in the CLI between your project's CloudFormation template and a CloudFormation template from a deployed stack in a project stage and region.

- [ ] Create new Action called ResourcesDiff, it should require `stage` and `region` options.
- [ ] Call ResourcesDeploy first with the `noExeCf` option to produce a populated and complete CF template in the `_meta` folder.
- [ ] Use this [AWS-SDK method](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#getTemplate-property) to get the deployed template
- [ ] Perform a diff and create an object of the differences.  Remember, this Action should be used via CLI and programmatically, so it must add the *difference object* to `evt.data` before it returns.
- [ ] Detect if the CLI is being used.  If so, loop through the object and print out the differences nicely.  Try to group them in related ways if possible.

**Comment by minibikini** [comment]
Done, please review.

Here is an example of the action output:

![screen shot 2016-02-11 at 9 36 08 pm](https://cloud.githubusercontent.com/assets/439309/12979586/b8ac4cae-d10a-11e5-8c70-6770efe68bf2.png)

**Comment by pmuens** [comment]
@minibikini Awesome :+1:

**Comment by ryansb** [comment]
:100:

**Comment by ac360** [comment]
In V0.5!
