### ISSUE TITLE
Tags overwrite problem

### ISSUE THREAD

**Issue by zxdong262** [serverless/serverless#6046]
# This is a Bug Report

## Description

How to reproduce it:
- Deploy with serverless.yml, no tags in function
- Add some tags in AWS lambda console(there is only stage tag)
- Deploy with same serverless.yml again
- The tags added in AWS lambda console are overwritten, removed.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: Linux Ubuntu 16.04.3
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by garethmcc** [comment]
@zxdong262 This kind of behavior doesn't just occur for tags and could affect you across the stack. Once you create a stack using serverless, and by extension AWS CloudFormation, you should not make any changes to that infrastructure manually as you will see the issue you have just described. 

If you need to have tags, you should probably add them in your serverless.yml configuration as per the documentation: https://serverless.com/framework/docs/providers/aws/guide/functions#tags. Then each time you deploy they will not be removed and if you need to change them you can do so in the serverless.yml and re-deploy them.

**Comment by zxdong262** [comment]
@garethmcc Thanks. Close it.
