### ISSUE TITLE
Enabling tracing in a multi-service setup throws ApiGatewayStage already exists

### ISSUE THREAD

**Issue by duro** [serverless/serverless#6055]
# This is a Bug Report

## Description

* What went wrong?: 

After enabling tracing and deploying my services, I begain getting the following error:

```
An error occurred: ApiGatewayStage - dev already exists.
```

* What did you expect should have happened? 

The deploy of my services should have succeed as it had before I enabled tracing

* What was the config you used?

```
provider:
  tracing:
    apiGateway: true
    lambda: true
```

* What stacktrace or error message from your provider did you see?

See above

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: linux
* ***Stack Trace***:
* ***Provider Error messages***: An error occurred: ApiGatewayStage - dev already exists.

## More info

My setup is a shared API Gateway, multi-service (multi-stack) configuration. I have a service which defines an API gateway and exports the API ID and Root Resource ID, which is shared by other services when deploying. This setup has been working perfectly for many weeks, and then I decided to try enabling tracing in the API gateway (new with 1.41) and this error happens. I even tried removing tracing with 1.41, redeploying all my services, and deploy went through just fine. But when I teardown, enable tracing, and deploy I get this error every time.

**Comment by pmuens** [comment]
Thanks for opening @duro 👍

This is an issue on AWS end and a limitation which is documented in the API Gateway docs --> https://serverless.com/framework/docs/providers/aws/events/apigateway/#api-gateway

The only way around this is to remove the API Gateway and re-deploy it with tracing enabled.

**Comment by j0b0sapi3n** [comment]
I'm running into this issue too trying to enable tracing. I've never removed and re-deployed a stack before so I'm a little hesitant. Will this change the URL for my API gateway aka the URL my client points to if I `sls remove` and then `sls deploy` again?
