### ISSUE TITLE
Links in docs are not obvious

### ISSUE THREAD

**Issue by pangolingo** [serverless/serverless#6059]
# This is a Bug Report

## Description
When reading the Serverless documentation, links are not differentated from regular text. That means it's not always obvious when you can click to find more information.

Expected: links are underlined or colored or bolded to make them obvious.
Actual: links look exactly the same as the other text, and are only underlined on hover.

This page has two links, but you wouldn't know just from looking at it.
https://serverless.com/framework/docs/providers/aws/events/
![image](https://user-images.githubusercontent.com/1423865/56823670-232b7600-681a-11e9-8729-0d331825c32d.png)

**Comment by cnufed** [comment]
Is this issue prevalent only for this page. I see other pages also has similar convention. What is the expectation here? Is it to match the style to something like [this](https://serverless.com/blog/serverless-express-rest-api/).

**Comment by pangolingo** [comment]
This issue occurs on multiple pages in the documentation.

If the links in the docs used the red underline from the blog, that would be a great solution.

**Comment by Perlkonig** [comment]
Appears to be fixed in the current version of the docs.

**Comment by medikoo** [comment]
Closing, website was redesigned few times since that issue was open, and now definitely links stand out
