### ISSUE TITLE
AWS TypeScript template does not produce ES2017 code

### ISSUE THREAD

**Issue by sime** [serverless/serverless#6060]
# This is a Bug Report

## Description

* What went wrong?
Code generated by webpack in the `aws-nodejs-typescript` template does not produce ES2017 code as specified in `tsconfig.json`.

* What did you expect should have happened?
A `handle.js` file with ES2017 code.

* What was the config you used?
```yaml
service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
```

Similar or dependent issues:
* #5607

## Additional Data

```bash
$ sls create -t aws-nodejs-typescript -p sls-ts-es2017
$ cd sls-ts-es2017
$ yarn install
$ sed -i 2d handler.ts # For a cleaner test, removing line "import 'source-map-support/register';"
$ sls package
$ unzip -d webpack-build .serverless/sls-ts-es2017.zip
$ wc -c webpack-build/handler.js # Output: 1244 webpack-build/handler.js
$ ./node_modules/.bin/tsc
$ wc -c lib/handler.js # Output: 313 lib/handler.js
```

Handler generated by webpack is 4 times larger then plain old `tsc`.

For reference contents of `lib/handler.js`
```javascript
export const hello = async (event, _context) => {
    return {
        statusCode: 200,
        body: JSON.stringify({
            message: 'Go Serverless Webpack (Typescript) v1.0! Your function executed successfully!',
            input: event,
        }, null, 2),
    };
};
//# sourceMappingURL=handler.js.map
```

Contents of `webpack-build/handler.js`: https://gist.github.com/sime/597eb409d942db25fae58258cfe898b2

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: OS X

Pinging contributors to the `aws-nodejs-typescript` template: @janvanzoggel,
@franciscocpg, @mlecoq, @jamestharpe, @Xenonym, @therockstorm, @uneco, @gabrielkaputa, @gmadar and @drexler.

**Comment by sime** [comment]
Force reference, when `import 'source-map-support/register';` is not removed the webpack handler file size is as follows:
```bash
$ wc -c webpack-build/handler.js # Output: 34342 webpack-build/handler.js
```

**Comment by medikoo** [comment]
Closing as this template was improved numerous times since this issue is open, and I'm pretty sure it's all good now
