### ISSUE TITLE
FunctionDeploy: Remove _tmp Folder

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#607]
In the beginning of FunctionDeploy we create a `_tmp` folder where we temporarily store the functions we are deploying.  This needs to be automatically deleted at the end (or during an error) of FunctionDeploy.  It's a simple task, we just haven't gotten to it.

**Comment by mt-sergio** [comment]
What about if we don't delete it when we pass --debug ?

**Comment by minibikini** [comment]
@ac360 fixed, please review.

@mt-sergio I've added `--dontRemoveTmp` option.

**Comment by mt-sergio** [comment]
Thanks! :ship:

**Comment by ac360** [comment]
Added in 98c1c2eef6df8e86c5ad6f841ea35bc0b05a6f9f  Thanks @minibikini!!!

**Comment by BernhardLenz** [comment]
I'm running 'serverless dash deploy --debug --dontRemoveTmp' but it still removes the tmp directory. What am I doing wrong?
