### ISSUE TITLE
Drop Node.js 4 and 6 support

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#6076]
The major cloud providers deprecated such Node.js versions. Since the Framework alwasy supports Node.js versions the major cloud providers support we should deprecate such Node.js versions as well due to security implications and lack of new features.

**Comment by jplock** [comment]
Does this also mean dropping bluebird in favor of native Promises and being able to use async/await?

**Comment by pmuens** [comment]
> Does this also mean dropping bluebird in favor of native Promises and being able to use async/await?

Yes, I think so! I'd be so happy if we finally use `async` / `await`. We had so many bugs just because of race conditions or tests simply not testing what they should due to problems with proper Promise handling.

**Comment by Chrischuck** [comment]
If you need help with this, I'd be happy to jump on!
