### ISSUE TITLE
AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException

### ISSUE THREAD

**Issue by fredmararac** [serverless/serverless#6087]
* What went wrong?
After successful deployment of stack. Deployment of succeeding code changes causes error.
* What did you expect should have happened?
Successful deployment of code changes, stack will be updated.
* What was the config you used?
NodeJS 8.10
* What stacktrace or error message from your provider did you see?
Serverless Error ---------------------------------------

  An error occurred: LambdaFunction - An error occurred and the request cannot be processed. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ).

## Additional Data

* ***Serverless Framework Version you're using***:
     Serverless Version:     1.40.0	 
* ***Operating System***:
     OS:                     win32
     Node Version:           8.10.0
* ***Provider Error messages***:
Serverless Error ---------------------------------------

  An error occurred: LambdaFunction - An error occurred and the request cannot be processed. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ).

### Captured event from CloudTrail
**Request Parameters:** 
"functionName": "arn:aws:lambda:us-east-1:000000000000:function:FunctionName",		                 
"publish": false,
"s3Key": "serverless/AppName/dev/1557215784081-2019-05-07T07:56:24.081Z/LambdaPackage.zip",
"s3Bucket": "dropfolder",
"dryRun": false

Based from the reference below, I can't find anything wrong in the configuration:
https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html#API_UpdateFunctionCode_RequestSyntax

_Note: Account specific data masked_

**Comment by fredmararac** [comment]
Hi all, this issue is already resolved.
I was able to find out that the missing tag value in _serverless.yml_ caused the errors

**Comment by jhtobav** [comment]
Hi dear fredmarac,

What missing that will be that you found? I'm having the same issue when creating lambda functions using cloud formation templates.

Best regards!

**Comment by fredmararac** [comment]
Hi @jhtobav,

If I remember this issue correctly, I just added a `tag`, and its values in my function declaration.

Hope this will help you in your issue.

Thanks!

**Comment by bkilrain** [comment]
@jhtobav were you able to solve you issue with CFN templates?

**Comment by corydorning53** [comment]
> Hi @jhtobav,
> 
> If I remember this issue correctly, I just added a `tag`, and its values in my function declaration.
> 
> Hope this will help you in your issue.
> 
> Thanks!

having the same issue. not sure i follow how you fixed this...

**Comment by fredmararac** [comment]
> > Hi @jhtobav,
> > If I remember this issue correctly, I just added a `tag`, and its values in my function declaration.
> > Hope this will help you in your issue.
> > Thanks!
> 
> having the same issue. not sure i follow how you fixed this...

Hi @corydorning53 ,

In our case, our function has tags. And in our yaml file, due to incorrect environment configuration, the **Environment**'s  value is `null` hence causing the error.

Here is our sample configuration, the tag:  **Environment** has no value.

```
functions:
  Audit:
    handler: AuditLog/index.handler  
    name: ${self:custom.prefix}_Audit
    description: function that will Log the Failed Messages 
    tags:
      Application: ${self:custom.application}
      Environment: ${self:custom.configFile.environmentVariables.serverlessStage}
      Description: ${self:functions.Audit.description}
```
