### ISSUE TITLE
[JAWS V1] Cross-compiling native modules

### ISSUE THREAD

**Issue by jwulf** [serverless/serverless#61]
http://iswwwup.com/t/5dc20214b79f/node.js-cross-compile-node-module-with-native-bindings-with-node-gyp.html

Contextify (and other native modules compiled with node-gyp) fail when deployed from a Mac. It looks like this:

START RequestId: 6b6c620b-4585-11e5-b7c3-f9f9cd8db2ee 
module initialization error: Error at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at bindings (/var/task/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44) at Object.<anonymous> (/var/task/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12)

**Comment by jwulf** [comment]
Here's one solution:

`jaws lambda-deploy`

0. Check if you a JAWS builder is deployed in the AWS account. 
1. If not, deploy it.
2. Send the function code to the JAWS builder lambda, and have it build and deploy it up there.

The only problem would be with things that take more than 60 seconds to build...

**Comment by jwulf** [comment]
...and also custom npm repositories

**Comment by ac360** [comment]
:+1: This is an interesting and great idea.

**Comment by jwulf** [comment]
And someone built it:

https://github.com/node-hocus-pocus/thaumaturgy

**Comment by jwulf** [comment]
Also this: http://bitbucket.aerobatic.com/blog/lambda-continuous-deployment.html

**Comment by johntitus** [comment]
Howdy - thaumaturgy is my project. Been watching JAWS for awhile and it was funny to see it pop up.  Let me know if I can help.

**Comment by jwulf** [comment]
Hi @johntitus. I reckon there is a powerful synergy between JAWS and thaumaturgy. There has been discussion around it in the Gitter room [1] and also in the JAWS roadmap [2]. It would be great to have your input! 

[1]  https://gitter.im/jaws-framework/JAWS 
[2] https://docs.google.com/document/u/2/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit?usp=sharing

**Comment by doapp-ryanp** [comment]
@johntitus I haven't had time yet to dig into your code, but from a high level we were going to start making something very similar to this.  @ac360 and I have been in talks with folks at AWS about this painpoint, so we should definitely touch base.  Give me a few days to look at what you got (I'm backed up on other stuff) and I'll reach out to you for next steps. Sound good?  Those 2 links @jwulf mention are good starting points.

**Comment by ac360** [comment]
This will be supported as a plugin

**Comment by tamlyn** [comment]
Any update on this? Is a plugin available or is there another recommended approach?
