### ISSUE TITLE
"serverless function deploy" doesn't work on v0.4

### ISSUE THREAD

**Issue by mt-sergio** [serverless/serverless#610]
`serverless function deploy -r "us-west-2" -s "staging" -a`

v0.3.3
```
Serverless: Deploying functions in "staging" to the following regions: us-west-2  
Serverless: Loading... Done!
Serverless: ------------------------  
Serverless: Successfully deployed functions in "staging" to the following regions:   
Serverless: us-west-2 ------------------------  
Serverless:   .... function information  
```

v0.4
```
Serverless: Deploying functions in "staging" to the following regions: us-west-2
Serverless: Loading... Done!
Serverless: ------------------------
```

On this line: https://github.com/serverless/serverless/blob/master/lib/actions/FunctionDeploy.js#L114
Both `_this.failed` and `_this.deployed` are undefined.

https://github.com/serverless/serverless/blob/master/lib/actions/FunctionDeploy.js#L269
v0.3.3
```
_this.evt.options.paths= [ 'a/b/c',
  'a/b/d',
  'a/b/e',
  'a/f/g']
```
v0.4
```
_this.evt.options.paths= []
```

**Comment by mt-sergio** [comment]
https://github.com/serverless/serverless/blob/master/lib/actions/FunctionDeploy.js#L269
v0.3.3
```
_this.evt.options.paths= [ 'a/b/c',
  'a/b/d',
  'a/b/e',
  'a/f/g']
```
v0.4
```
_this.evt.options.paths= []
```

**Comment by ac360** [comment]
@mt-sergio I think I've fixed this.  Could you update to `0.4.1` and try again?

**Comment by ac360** [comment]
Please re-open if this still does not work.  Thanks for finding this :)

**Comment by mt-sergio** [comment]
Fixed! Thank you :)
