### ISSUE TITLE
Sudden CORS Configuration Error when switching to version 1.42.0

### ISSUE THREAD

**Issue by nikwerhypoport** [serverless/serverless#6102]
# This is a Bug Report

## Description

* What went wrong?
We are using serverless in the context of an AWS codeBuild Pipeline.
Serverless is installed via npm and a package.json.
When executing `serverless deploy` for AWS Lambdas we suddenly got a 
message about cors misconfiguration.
Switching back to 1.41.1 'fixed' the error and we could deploy regularly.

The commands are:
```
npm install
./node_modules/.bin/serverless deploy --stage STAGE --deploymentBucket BUCKET --customDomain DOMAIN
```

* What did you expect should have happened?
Deployment went smooth with version 1.41.1

* What stacktrace or error message from your provider did you see?
```
Serverless: (updated) Function 'XXX-lambda' XXXConfig.TargetArn: arn:aws: XXXX
  
  Serverless Error --------------------------------------- 
  
  You can only use "origin" or "origins", but not both at the same time to configure CORS. Please check the docs for more info. 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     OS:                     linux 
     Node Version:           8.2.1 
     Serverless Version:     1.42.0 
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.0 
* ***Operating System***: linux ubuntu 18.04 image (provided by aws)

**Comment by trilom** [comment]
Same issue found in https://github.com/serverless/serverless/issues/6098
