### ISSUE TITLE
API Gateway "Enable Detailed CloudWatch Metrics"

### ISSUE THREAD

**Issue by davidfarinha** [serverless/serverless#6112]
# This is a Feature Proposal

## Description

I saw it's possible to configure the "Enable CloudWatch Logs" setting in an API Gateway stage with [this PR](https://github.com/serverless/serverless/issues/4461), however it's not still currently possible to configure the "Enable Detailed CloudWatch Metrics" setting.

Similar or dependent issues:
* #4461
* #1918
* https://github.com/serverless-heaven/serverless-aws-alias/issues/57

**Comment by pmuens** [comment]
Hey @davidfarinha have you tried to setup logs via:

```yaml
provider:
  logs:
    restApi: true
```

**Comment by davidfarinha** [comment]
Hey @pmuens, yes I'm using the latest version and have API Gateway logs enabled. This enables "Enable CloudWatch Logs" but not "Enable Detailed CloudWatch Metrics" (see below). 
![image](https://user-images.githubusercontent.com/3890344/57533359-7aab0500-7335-11e9-889c-f0afad4edb52.png)

**Comment by Ignigena** [comment]
Seeing the same thing here, would love a way to be able to enable the Detailed CloudWatch Metrics in addition to the standard CloudWatch Logs option that is currently supported.

**Comment by praveenkumarchetty** [comment]
Hello, Any one able to enable the cloudwatch metrics? I am also stuck in enabling the cloudwatch logs.

**Comment by praveenkumarchetty** [comment]
I would like to enable the cloudwatch metrics.

**Comment by MichaelMitchellM** [comment]
@pmuens Any update on this?

**Comment by jastsai** [comment]
any update on this? thanks!

**Comment by mooniker** [comment]
+1 bump

**Comment by cseli** [comment]
+1

**Comment by oscarwest** [comment]
Still waiting for this :)

**Comment by arthurmf** [comment]
+1

**Comment by varuna-v** [comment]
+1

**Comment by apedzko** [comment]
Waiting for this as well.

**Comment by shilnew** [comment]
+1

**Comment by alipsidikp** [comment]
+1

**Comment by lkolchin** [comment]
any update on this?

**Comment by bunchito** [comment]
Also looking for news related to this. Thanks!

**Comment by vincentleekp** [comment]
+1

**Comment by diogocapistrano** [comment]
+1

**Comment by medikoo** [comment]
Addressed with #7754
