### ISSUE TITLE
Creating s-resources-cf.json in the root directory leads to skipping all nested s-resources-cf.json files from being merged into role

### ISSUE THREAD

**Issue by kpotehin** [serverless/serverless#614]
In the last update you encourage us to move `cloudFormation` syntax from `s-project.json` to `s-resources-cf.json` in the root directory. I did it and discovered that doing that leads to skipping all nested `s-resources-cf.json` files from being merged into role. I was able to fix it myself, but I'm not familiar with Promises, so I just want to file it here. You should look here: `ServerlessProject.js`, lines 183-192. Merging takes place at 240-263 lines, but if you have `s-resources-cf.json` in the root directory you never get there.

Thanks!

**Comment by ac360** [comment]
Thanks @kpotehin :)  I believe I fixed this in 99f2bdea3d17b48aa09d0d2246096c2544acc917 Please upgrade to 0.4.2 and let me know what you think
