### ISSUE TITLE
Support Node.js v10 runtime in AWS Lambda

### ISSUE THREAD

**Issue by ceefour** [serverless/serverless#6144]
# Support Node.js v10 runtime in AWS Lambda

## Description

Since May 13, 2019 [AWS Lambda has supported Node.js v10](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/) (with auto-upgrade of minor versions).

I bet many users, myself included, are very eager to upgrade. We've been waiting for a **long** time! ^_^

Similar or dependent issues:
* #6076 
* #5249

**Comment by jplock** [comment]
I was able to set `runtime: nodejs10.x` in my Serverless 1.40.0 project and it worked fine.

**Comment by ceefour** [comment]
@jplock Thanks!
