### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by wajdan846** [serverless/serverless#6153]
Im getting this output on serverless deploy

```
Syntax Error -------------------------------------------
 
     Unexpected token {
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.2.6
     Serverless Version: 1.6.1

```

**Comment by herebebogans** [comment]
Can you include your serverless.yml to aid in troubleshooting?

**Comment by wajdan846** [comment]
I updated my NodeJS to the latest version and reinstalled a different serverless version, and the problem is solved.These are my current versions

```
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           12.2.0
     Serverless Version:     1.42.3

```

**Comment by wajdan846** [comment]
Im sorry my serverless.yml file is confidential, I hope this solution might help others who face the same problem

**Comment by pmuens** [comment]
Hey @wajdan846 thanks for opening :+1:

Unfortunately there's way too little meaningful information available to help you here. Please share parts of your `serverless.yml` or other configuration which makes it possible to help troubleshooting here.

**Comment by ajaiswal-apptio** [comment]
Just for reference,
I had exactly same issue.
This problem for me was due to version missmatch from awscli and python boto3,
I had to manually download the compatible version between these 3 packages; i.e is if awscli(1.19.33), then  boto3(1.17.33) and botocore(1.20.33).  looks like the minor version shall be equal.
