### ISSUE TITLE
Serverless python requirements -  path must be a string or Buffer

### ISSUE THREAD

**Issue by arafatheds** [serverless/serverless#6166]
Here is the error..

Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...

  Type Error ---------------------------------------------

  path must be a string or Buffer

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at go$readFile (/home/backend/node_modules/graceful-fs/graceful-fs.js:85:14)
    at Object.readFile (/home/backend/node_modules/graceful-fs/graceful-fs.js:82:12)
    at Object.readFile (/home/backend/node_modules/universalify/index.js:5:67)
    at injectRequirements (/home/backend/node_modules/serverless-python-requirements/lib/inject.js:23:6)
    at ServerlessPythonRequirements.injectAllRequirements (/home/backend/node_modules/serverless-python-requirements/lib/inject.js:120:12)
    at ServerlessPythonRequirements.BbPromise.bind.then.then.then (/home/backend/node_modules/serverless-python-requirements/index.js:183:43)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.40.0

Any idea why error occurs ?

   "serverless-python-requirements": "4.3.0"

**Comment by pmuens** [comment]
@arafatheds thanks for opening :+1:

Looks like this bug is related to the Python requirements plugin. Please re-open the issue in the plugins repository.
