### ISSUE TITLE
Cannot return undefined or null from yml referenced javascript file

### ISSUE THREAD

**Issue by Josh-a-e** [serverless/serverless#6168]
# This is a Bug Report

## Description

* What went wrong?

I included this line in my serverless.yml file:

`BucketName: project-name-${file(./yml-helpers.js):opt.stage.lowercase, 'dev'}-whatever`

Necessary as s3 bucket names can include only lowercase letters

And got this error:

```
Serverless Warning --------------------------------------

 A valid file to satisfy the declaration 'file(./yml-helpers.js):opt.stage.lowercase' could not be found.


 Serverless Error ---------------------------------------

 Trying to populate non string value into a string for variable ${file(./yml-helpers.js):opt.stage.lowercase}. Please make sure the value of the property is a string.

 Get Support --------------------------------------------
    Docs:          docs.serverless.com
    Bugs:          github.com/serverless/serverless/issues
    Issues:        forum.serverless.com

 Your Environment Information ---------------------------
    OS:                     linux
    Node Version:           8.10.0
    Serverless Version:     1.42.3
```

* What did you expect should have happened?

`${file(./yml-helpers.js):opt.stage.lowercase, 'dev'}` should resolve as `"dev"` if `opt.stage.lowercase` evaluates to `null` or `undefined` (i.e. no stage option is supplied - the default case).

* What was the config you used?

n/a

* What stacktrace or error message from your provider did you see?

see above

Similar or dependent issues:

## Additional Data

* ***Serverless Version: 1.42.3***:
* ***Operating System: MacOS running lambci/lambda:build-nodejs8.10 on Docker***:
* ***Stack Trace: none***:
* ***Provider Error messages:  see above***:

**Comment by medikoo** [comment]
Closing, as this will work as expected with new variables resolver
