### ISSUE TITLE
problem with tags including german umlauts

### ISSUE THREAD

**Issue by Lostbrokenkey** [serverless/serverless#6170]
I tried to add a tag with an german umlaut but it wasn't working, serverless said:

![Bildschirmfoto 2019-05-24 um 10 59 41](https://user-images.githubusercontent.com/5960337/58316342-99b89500-7e13-11e9-8ead-fe2e25278537.png)

If i add this tag directly in the lambda-function it is working.

![Bildschirmfoto 2019-05-24 um 11 02 56](https://user-images.githubusercontent.com/5960337/58316343-99b89500-7e13-11e9-9202-c8122d7052c5.png)

Every sign i'm able to set in a tag-value should be usable in the serverless.yml
<img width="433" alt="Bildschirmfoto 2019-05-24 um 11 12 49" src="https://user-images.githubusercontent.com/5960337/58317072-56f7bc80-7e15-11e9-8643-ed8344d2b344.png">

**Comment by exoego** [comment]
I think this is resolved by PR #6139
