### ISSUE TITLE
Is graphql.serverless.com down?

### ISSUE THREAD

**Issue by kamilkp** [serverless/serverless#6175]
# This is a Bug Report

## Description

I tried deploying a service using the `serverless deploy` command and it fails repeatedly due to the following error:

```
Serverless: Couldn't publish this deploy information to the Serverless Platform.
 
  Error --------------------------------------------------
 
  Network error: request to https://graphql.serverless.com/graphql failed, reason: getaddrinfo ENOTFOUND graphql.serverless.com graphql.serverless.com:443
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Mac OS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by ikrauchanka** [comment]
```
$ dig graphql.serverless.com @8.8.8.8

; <<>> DiG 9.10.6 <<>> graphql.serverless.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64339
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;graphql.serverless.com.		IN	A

;; AUTHORITY SECTION:
serverless.com.		899	IN	SOA	ns-365.awsdns-45.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 277 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri May 24 23:52:31 +03 2019
```

**Comment by sanddevil** [comment]
Upgrading to the latest version of serverless from 1.26.0 to 1.44.1 fixed it for me.

**Comment by pmuens** [comment]
Closing since it seems like updating the Serverless version fixes the problem. Feel free to re-open if this is still an issue.

**Comment by csmobile** [comment]
you may want to try:
sls logout

this fixed the issue for me.  Recommended by David Wells - Serverless forum

**Comment by sshadmand** [comment]
Severless seems to be down. I am getting the same message as OP. 

Tried:
- Upgrading to latest 1.83.0
  - DIdn't work got same as OP.
- sls logout
  - Logging back in took my to this page

![Screen Shot 2020-09-12 at 2 00 38 PM](https://user-images.githubusercontent.com/68735/93004910-9b263900-f500-11ea-856a-f6a2a98d7591.png)

**Comment by sshadmand** [comment]
FYI Upgrading to `"serverless-domain-manager": "^2.6.13"` seemed to fix the issue.
