### ISSUE TITLE
How can I write nested IF in serverless.yml using yaml format file while using it for cloud formation?

### ISSUE THREAD

**Issue by GurpreetSingh5** [serverless/serverless#6177]
I'm trying to access secrets created in secrets manager(https://aws.amazon.com/secrets-manager/) via SSM (Systems Manager- https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html ) i.e. AWS Parameter store, and store it in a custom YAML variable in serverless.yml file? 
I am trying to implement cloud formation through serverless framework(https://serverless.com/), and I am trying to implement a nested if statement in cloud formation for implementing the above using the code below.

     stage: &stage 'dev' #Hardcoded for now
     rdsMasterPassword:
     !If
      - !Equals [*stage,"prod"]
      - ${ssm:/aws/reference/secretsmanager/cred-prod~true:rdsMasterPassword}
      - !If 
          - !Equals [*stage,"staging"]
          - ${ssm:/aws/reference/secretsmanager/cred-staging~true:rdsMasterPassword}
          - ${ssm:/aws/reference/secretsmanager/cred-dev~true:rdsMasterPassword}

I have tried Cloud formation instrinsic functions Fn::If for this but facing this errror :
`Fn::If requires a list argument with the first element being a condition`

https://stackoverflow.com/questions/56319766/how-can-i-write-nested-if-in-serverless-yml-using-yaml-format-file-while-using-i

**Comment by delprofundo** [comment]
I use an environment file that includes the SSM paths and deploy each stage to a different account and a single script per project to populate each new account with the initial variables (some are then updated with values from stack creation). This way the paths to the vars are uniform across accounts which makes a CircleCi integration dead simple.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
