### ISSUE TITLE
Output variables for resources created by CF cannot be used in serverless projects

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#618]
If you create resources using CF templates some properties of these resources are set to partially random values (e.g. if you create a Kinesis stream the name is only known after creation and can be grabbed as output variable in the CF template). Currently only iamRoleArnLambda is persisted in the stage template variables.
Arbitrary variables should be persisted while allowing the user to define a whitelist to exclude sensitive data written into publicly visible files. Afterwards the variables can easily be used in any project related json configuration files by using the ${} template notation.

A second step should be to make these variables available at runtime for specific functions.
There are some ideas how that could work (list is not complete):
(1) persist the values within the function's environment
(2) Store these values in a separate file on S3 and retrieve it at function start
(3) Extend serverless-helpers to get CF output variables on demand
... and many more

**Comment by ac360** [comment]
Merged into v0.5.  Thank you!!

**Comment by HyperBrain** [comment]
My commit solved the persistence of the CF output variables into the serverless stage variables.

Now we should discuss the second part here, i.e. how to realize the runtime part.

**Comment by ryansb** [comment]
I think of these, I like option 3 the best. 

Using `serverless-helpers` as a repository for these kinds of features would be the way to go, since I've been needing information from CFN to have my functions work properly. For example, the ARN of a per-serverless-project errors/notification topic is something I've had to take out of CFN and create manually. 

Maybe others don't want the latency of querying CloudFormation, and we could provide a part of the `function deploy` process that sets the CFN stack outputs in the .env file. It wouldn't get updates automatically, but it would cut down start time for apps where resources are long-lived.

**Comment by HyperBrain** [comment]
@ryansb I will now extend serverless-helpers-js to expose an CF object additionally to the local .env handling that will read the CF output variables from the lambda's CF stack and make them available as environment variables as SERVERLESS_CF_XXXXXXX.

**Comment by HyperBrain** [comment]
Regarding the start-up time: This will also be solved by the extra object because it will only be queried if, and as soon you call the CF object's getenv() in your lambda handler. Storing the outputs statically in the `.env` doesn't seem a good idea for me as it would create the need to redeploy on any resource change.

**Comment by HyperBrain** [comment]
ok, nearly finished - I will create a PR later today or tomorrow

**Comment by HyperBrain** [comment]
https://github.com/serverless/serverless-helpers-js/pull/2

**Comment by HyperBrain** [comment]
## CF Output variables
To have your lambda access the CF output variables you have to give it the `cloudformation:describeStacks` access rights in the lambda IAM role.

The CF.loadVars() promise will add all CF output variables to the process'
environment as *SERVERLESS_CF_`OutVar name`*. It will add a few ms to the
startup time of your lambda.

Change your lambda handler as follows:

```
// Require Serverless ENV vars
var ServerlessHelpers = require('serverless-helpers-js');
ServerlessHelpers.loadEnv();

// Require Logic
var lib = require('../lib');

// Lambda Handler
module.exports.handler = function(event, context) {
  ServerlessHelpers.CF.loadVars()
  .then(function() {
    lib.respond(event, function(error, response) {
      return context.done(error, response);
    });
  })
};
```

**Comment by eahefnawy** [comment]
@HyperBrain again, thanks for your awesome work here :blush: ... we're releasing v0.5 soon, closing issue now that it's resolved :)

**Comment by ryansb** [comment]
P.S. This functionality is also available in [serverless-helpers-py](https://github.com/serverless/serverless-helpers-py)

**Comment by HyperBrain** [comment]
@ryansb :clap:

**Comment by d4goxn** [comment]
Excellent! The docs say that using CF output variables in Lambda functions is flat out impossible:

> **Templates & Variables are for Configuration Only**

> Templates and variables are used for configuration of the project only. This information is not usable in your lambda functions. To set variables which can be used by your lambda functions, use environment variables.

Should that statement be replaced with @HyperBrain's comment?

**Comment by ryansb** [comment]
Yeah, but do mention that it requires an extra API call since the outputs may change and that means your function takes longer to run.

**Comment by HyperBrain** [comment]
@d4goxn Since Serverless 0.5.x the project variables can be used to set values for environment variables in the `s-function.json -> environment` property. Now the CF output variables are automatically added to your project variables.
So the serverless-helpers package has been obsoleted - the CF extension there was used before to retrieve the CF variables dynamically from a stack. Now it is only helpful when you explicitly need to query the stack at runtime introducing some overhead (as @ryansb  already said)

**Comment by d4goxn** [comment]
All right, I got this working! Thanks for the tips, guys. My `s-resources-cf` and the `s-function` for making a CF-created Redis cluster available to a Lambda function are in a [gist](https://gist.github.com/d4goxn/7322250ffe89f8a8a5c5d62804a8da2a).

I would be happy to update the documentation, but this is my first day here, and I haven't been able to find the repo for http://docs.serverless.com :)
