### ISSUE TITLE
serverless/enterprise-plugin not found

### ISSUE THREAD

**Issue by aaleksandrov** [serverless/serverless#6181]
# This is a Bug Report

## Description

I install SLS globally using `yarn`
```
11.25s$ yarn global add serverless
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "serverless@1.44.0" with binaries:
      - serverless
      - slss
      - sls
Done in 10.78s
```

 After upgrade to 1.44 local invocations started to fail:
```
  Serverless Error ---------------------------------------
 
  Serverless plugin "@serverless/enterprise-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
```

serverless.yml doesn't contain any plugina

## Additional Data

* ***Serverless Framework Version you're using***: 1.44.0
* ***Operating System***: Ubuntu 16.04

**Comment by medikoo** [comment]
@aaleksandrov what exactly command are you trying? `invoke local --function` ?

Can you prepare some minimal test case through which we can reproduce it?

**Comment by aaleksandrov** [comment]
@medikoo 
yes, I do `invoke local`
I guess problem is that I install SLS globally
```
11.25s$ yarn global add serverless
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "serverless@1.44.0" with binaries:
      - serverless
      - slss
      - sls
Done in 10.78s.
```

And then invoke locally
```
ENVIRONMENT=test serverless invoke local -f ${FUNCTION_NAME} 
```

Will provide some more code tomorrow if its not enough

**Comment by aaleksandrov** [comment]
Also in `serverless.yml` there is no plugins at all. I'll update my first message

**Comment by dschep** [comment]
Ahh.. I suspect the issue is using yarn. Let me check that.

**Comment by medikoo** [comment]
Ok, thanks. It's related purely to `yarn` (it installs global modules a bit differently). Still it's a bug on our side.

**Comment by dschep** [comment]
hey @aaleksandrov, does version 1.44.1 fix your issue?

**Comment by aaleksandrov** [comment]
Thanks, it works fine now!
