### ISSUE TITLE
Enterprise login required after updating to v1.44.1

### ISSUE THREAD

**Issue by alfaproject** [serverless/serverless#6184]
# This is a Bug Report

## Description

* What went wrong?
I use Renovate bot to update dependencies automatically. It just updated serverless to v1.44.1 and now I get this in my CI pipeline: `Serverless plugin "@serverless/enterprise-plugin" initialization errored: You are not currently logged in. To log in, use: $ serverless login`

* What did you expect should have happened?
The update shouldn't make me change anything since there are no reported breaking changes for this version.

## Additional Data

GitLab CI runner using `cypress/base:8` docker image:
```
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.44.1
```

**Comment by django-wong** [comment]
having the same issue in my deployment pipeline..

**Comment by medikoo** [comment]
Do you by chance have an `app` or `tenant` param within your `serverless.yaml` (in root context) ?

**Comment by alfaproject** [comment]
I have both `app` and `tenant`

**Comment by medikoo** [comment]
@alfaproject are you a customer of Serverless Enteprise? If so, then this message is correct, you need to login via `sls login` to be able to use the functionality.

Otherwise (if you're not a customer of Serverless Enteprise) then why do you have those options in config? They apply strictly to Serverless Enterprise

**Comment by viktorlarsson** [comment]
Experiencing the same issue. I have app and tenant as well, it's been working for all this time, @medikoo. What has changed? Where is it suppose to know where to deploy if you don't have them?

**Comment by medikoo** [comment]
> @medikoo. What has changed?

Serverless Enterprise support was added, and `app` and `tenant` are recognized within Serverless as its options.

What feature do `app` and `tenant` options serve on your side? Why do you have them setup?

**Comment by alfaproject** [comment]
I set them up a few months ago because serverless wasn't working otherwise, so maybe I setup things incorrectly when I was fiddling with it. I'll remove and check again

**Comment by medikoo** [comment]
> I set them up a few months ago because serverless wasn't working otherwise

Maybe you were testing some old version of Serverless Enterprise at earlier stage?

At least I do not recognize the moment of those options being mandatory in configuration (I believe all SLS versions worked well without them being set)

Anyway just remove those options and all should work fine.

**Comment by alfaproject** [comment]
Yup, all good after removing `app` and `tenant`. Thank you (:
