### ISSUE TITLE
Cannot use ${component} in customName (s-function.json)

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#620]
In order to keep the Lambda names as they were in SLS < 0.4 (for a current project), I need to use the component in the Lambda name. However, it's not being populated when deploying.

**Comment by HyperBrain** [comment]
On my side the component name is still part of the automatically generated lambda name, wheras the module nor the directory names are not. I changed the function names/directories to include the former module name and it works as before. E.g. module-function/* so my lambda names are as before project-component-module-function.

**Comment by joostfarla** [comment]
@HyperBrain did you remove the `s-module.json` files already?

**Comment by HyperBrain** [comment]
Yes, I cleaned up the whole project and removed the module stuff

**Comment by HyperBrain** [comment]
... and also set "profile": "serverless-v0.4.0" in my s-project.json

**Comment by HyperBrain** [comment]
as a starting point I just created an empty project with v0.4.0 (`sls project init`) and created one component and one function in there to see what exactly has changed within the json files.
