### ISSUE TITLE
how to disable warnings while running serverless print command

### ISSUE THREAD

**Issue by saumilsdk** [serverless/serverless#6203]
When I run serverless print command, some variables are yet to be resolved are popping as warnings which is messing my output of serverless print. I need to use serverless print --format json with no warnings. Is there a way to disable warnings.

**Comment by saumilsdk** [comment]
anyone please help

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.

**Comment by pmuens** [comment]
As an update to this issue: There's now a way to suppress warnings.

You can see the name of the environment variable by running `serverless --help`.

**Comment by saumilsdk** [comment]
serverless --help won't work as i'll have multiple stages and based on stage env variables differs. I wanted dump of all serverless variables in my code.

**Comment by cwells** [comment]
Yep, this command is useless for gathering information. Can't parse malformed YAML =(

```
  SLS_WARNING_DISABLE='*' sls print
```

```
 Serverless Information ----------------------------------
 
  ############################################################################################
    # 2502: 17 of 19 promises have settled
    # 2502: 2 are taking longer than expected:
    # 2502:   [redacted] waited on by: [redacted] 
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
 
 
 Serverless Information ----------------------------------
 
  ############################################################################################
    # Completed after 3259ms
    # 19 promises are in the following states:
    #   resolved: 19
    #   rejected: 0
    #   pending:  0
    ##########################################################################################
```

(Lots of output truncated).

Whether or not this is considered a bug, there ought to be some way to get parseable output from sls. In general, I'd expect warnings and errors to go to stderr, and output to go to stdout. Not sure why that's not the case here.

**Comment by saumilsdk** [comment]
serverless print --format json

**Comment by cwells** [comment]
@saintmalik Thanks, but has the same issue.

**Comment by esuico** [comment]
I'm also looking for a solution on same topic. There needs to be a way to display output of print without warnings.

**Comment by theo-bittencourt** [comment]
Same here. Output can't be parsed.

**Comment by snbeynon** [comment]
Thanks @cwells `export SLS_WARNING_DISABLE='*'` saved me a lot of time!

**Comment by mikewolfd** [comment]
`export SLS_DEPRECATION_DISABLE ='*'` is also necessary in some cases for the same issue.

As a side note, I don't know why this ticket is closed. A print command shouldn't be polluting it's output with warning errors.

**Comment by pgrzesik** [comment]
Hello @mikewolfd - I believe the reason for this ticket being closed is that it was reported a long time ago - since then we had a few other similar reports and all of it is going to be addressed by https://github.com/serverless/serverless/issues/8731 and/or https://github.com/serverless/serverless/issues/1720 

All feedback on the above is welcome :raised_hands:

**Comment by mikewolfd** [comment]
> Hello @mikewolfd - I believe the reason for this ticket being closed is that it was reported a long time ago - since then we had a few other similar reports and all of it is going to be addressed by #8731 and/or #1720
> 
> All feedback on the above is welcome 🙌

Thanks for the update/follow-up!

**Comment by arashilmg** [comment]
@pmuens could you reopen this issue?

>In general, I'd expect warnings and errors to go to stderr, and output to go to stdout. Not sure why that's not the case here.

**This bug is still valid.**

**Comment by arashilmg** [comment]
@pgrzesik #8731 and/or #1720 don't cover this bug

**Comment by pgrzesik** [comment]
Hello @arashilmg - we're currently working on revamping the logging engine and that issue will be covered by that change as well - the main initiative is available here: https://github.com/serverless/serverless/issues/9860
