### ISSUE TITLE
Ability to add resources to the API Gateway Deployment Depends On

### ISSUE THREAD

**Issue by ed-sparkes** [serverless/serverless#6210]
# This is a Feature Proposal

## Description

I have implemented API gateway as an S3 proxy in CloudFormation script in my Resources section. I am adding it as a resource to the same API as my functions using the naming convention to add it to `ApiGatewayRestApi`. 

The problem is it doesn't get deployed unless i run `sls deploy` twice. I am guessing this is because the first time the deployment is run before the additional resource is added to the API because the `ApiGatewayDeployment<instanceId>` does not `DependsOn` my additional `ApiGatewayMethod`

Is there any way to force the deployment to be dependent on this too? 

If not could this be a feature to add into the apiGateway config. 

e.g. 

```
apiGateway:
    deploymentAlsoDependsOn:
        - myAdditionalMethod #where this is a resource specified elsewhere in my yaml
```

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
