### ISSUE TITLE
Example serverless framework, google cloud functions and apollo server

### ISSUE THREAD

**Issue by MatteoGioioso** [serverless/serverless#6213]
# This is a Feature Proposal
More documentation for `google cloud functions` , `Apollo server/graphQL`, `typescript` and `function emulator`

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Hello, I have searched a bit around but seems there are no examples and lack of documentation on using "serverless framework" with google cloud functions and Apollo server. Also nothing about the emulator and typescript.

I am really sorry to bother you here, but I have written a post on your forum and unfortunately I have received no answers.

Thanks

**Comment by AdamZaczek** [comment]
I had the same experience. I have given up on using google cloud with serverless for now :/

**Comment by MatteoGioioso** [comment]
Actually I have just discoverd that is much simpler to setup by not using serverless framework. `firebase-tools` CLI does pretty much everything for you out of the box with typescript and function emulator and no need to setup billing account

**Comment by MatteoGioioso** [comment]
No update on this?

**Comment by MatteoGioioso** [comment]
Up

**Comment by evghenip** [comment]
This is Firebase plugin for Serverless in replace of standard Google Cloud Functions support.
https://www.npmjs.com/package/serverless-firebase-functions

And next my example of GraphQL server usage, there i used "type-graphql", but i think anyway is clear how to make it:
`import "reflect-metadata";
import * as TypeGraphQL from 'type-graphql';
import { ApolloServer as ApolloServerMicro } from 'apollo-server-micro';
import { DealResolver } from './graphql/deals.resolver';
import { GraphQLSchema } from 'graphql';
import { HotelsResolver } from './graphql/hotels.resolver';
import { getMetadataStorage } from 'type-graphql/dist/metadata/getMetadataStorage';

const schema = TypeGraphQL.buildSchemaSync({
    resolvers: [
        DealResolver,
        HotelsResolver
    ]
}) as GraphQLSchema;

getMetadataStorage().clear();

const microServer = new ApolloServerMicro({
    schema,
    playground: true
});
exports.graphqlHandler = microServer.createHandler({path:'/api'});
`
