### ISSUE TITLE
how to rebuild/pull the .serverless folder 

### ISSUE THREAD

**Issue by komushi** [serverless/serverless#6223]
After deploying to aws the local .serverless folder was deleted by mistake. 

The resources deployed through cloudformation are correct. How can I manage to rebuild/pull the cloudformation stack info so that I can continue to use the existing stack?

**Comment by rdsedmundo** [comment]
The `.serverless` doesn't need to be versioned in the repository, there's no problem of deleting it. It's always generated according to the current changes on your repository and includes all the previous state.

You can just do an `sls package` and it will create the folder again without triggering a deployment.

**Comment by komushi** [comment]
Thanks
