### ISSUE TITLE
Creating CNAME for Api gateway

### ISSUE THREAD

**Issue by DivyaPraveen** [serverless/serverless#6235]
I deployed an api gateway using functions and I need a CNAME to map to the apigateway url. Could you give some insight?

Here is the code which I have tried which deploys the code but the cname is not added.

This is the snippet in serverless.yml
functions:
  find_styles:
    handler: base_seite_lookup.find_styles
    events:
      - http:
          path: /
          method: get
    CNAME: "base-seite.dev.emea.com"

**Comment by DivyaPraveen** [comment]
Any help is appreciated. I am stuck here.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
