### ISSUE TITLE
Use AWSLambdaBasicExecutionRole instead of adding CW Logs permissions manually 

### ISSUE THREAD

**Issue by rdsedmundo** [serverless/serverless#6241]
# This is a Feature Proposal

## Description

Issue for following up https://github.com/serverless/serverless/issues/6236#issuecomment-501302974

I suggest we use `AWSLambdaBasicExecutionRole` instead of adding CW Logs permissions manually.

See: https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html
> AWSLambdaBasicExecutionRole – Permission to upload logs to CloudWatch.

This is its content as of today:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
```

[For what it's worth, we're already using one AWS Managed Policy, `AWSLambdaVPCAccessExecutionRole`, when the `vpc` option is set.](https://github.com/serverless/serverless/blob/f0b3d9f42abbe4d4b26fdbfdcbe5cbf36bca5775/lib/plugins/aws/package/lib/mergeIamTemplates.js#L173)

@medikoo 
> I take AWSLambdaBasicExecutionRole is something that AWS setups automatically.

Yes, it's an AWS Managed Policy, which means that AWS team who controls it. If one day it happens to have a CW Logs permission in order to the basic logging to work, AWS will add it, and no changes on the codebase would be required.

> Are all accounts ensured to have that role? Isn't it provided only if user generates it after some AWS suggestion?

All accounts have all the AWS Managed Policies yes, always. They are read-only, i.e cannot be edited or deleted. But this is a Policy, not a role. We should still create the role, but we attach the AWS Managed Policy instead of adding the CW Logspermissions manually.

**Comment by weeniearms** [comment]
@rdsedmundo I see one potential issue with this managed policy. Since it uses `"Resource" : "*" `, it violates the least privilege principle. While it might be ok for testing, it's sort of an antipattern for production use. It'd be better to generate a custom managed policy and attach it to the role in order to avoid inline policy size issues.

**Comment by medikoo** [comment]
@rdsedmundo great thanks for valuable feedback. 

As we already rely on `AWSLambdaVPCAccessExecutionRole`, it's indeed worth a discussion.

Either it's wrong we rely on  `AWSLambdaVPCAccessExecutionRole` (which grants same, very premissive, rights, plus some others), or if it's fine, we could provide an option to rely on `AWSLambdaBasicExecutionRole`.

Why actually you've closed the issue?

**Comment by medikoo** [comment]
@pmuens what's your stance on that?

**Comment by rdsedmundo** [comment]
Sorry, that should have been a misclick, I didn't mean to close.

I agree with what @weeniearms stated. I actually double-checked the AWS Console to see what it does and if you choose the option "Create a new Lambda with basic permissions" it will attach the AWSLambdaBasicExecutionRole, but it restricts its resource to only the log stream of the own Lambda that was created and doesn't let a wildcard.

**Comment by azizur** [comment]
AWS Lambda Monitoring tab is showing this message for me.
```
Missing permissions
Your function doesn't have permission to write to Amazon CloudWatch Logs. To view logs, add the AWSLambdaBasicExecutionRole managed policy to its execution role.
```
<img width="1539" alt="Screenshot 2019-09-15 at 13 25 40" src="https://user-images.githubusercontent.com/114551/64921535-721f7b00-d7bc-11e9-96dc-ff2f37122fa2.png">

**Comment by azizur** [comment]
I fixed it with this:
```
provider:
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
```
