### ISSUE TITLE
async-await methods timeout

### ISSUE THREAD

**Issue by coulson84** [serverless/serverless#6246]
# This is a Bug Report

## async-await methods timeout when wrapped in serverlessSDK.handler

* What went wrong?
There is an async handler that is completing but the severlessSDK.handler method does not seem to detect that the handler has completed so the method times out
* What did you expect should have happened?
When the promise returned from the async handler resolves the lambda should complete
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data
Hope I haven't missed any documentation stating that async is fully supported anywhere or duplicated any other issue. I tested this out by manually editing the code in the AWS Lambda console from this
```
try {
  const userHandler = require('./daily.js')
  module.exports.handler = serverlessSDK.handler(userHandler.digest, handlerWrapperArgs)
} catch (error) {
  module.exports.handler = serverlessSDK.handler(() => { throw error }, handlerWrapperArgs)
}
```
to this
```
try {
  const userHandler = require('./daily.js')
  module.exports.handler = userHandler.digest
} catch (error) {
  module.exports.handler = serverlessSDK.handler(() => { throw error }, handlerWrapperArgs)
}
```

once the `serverlessSDK.handler` wrapper was removed the lambda function completed as soon as the promise returned userHandler.digest resolved.

* ***Serverless Framework Version you're using***: 1.45.1 (I don't think this issue occurred in 1.36.1 which I was using previously)
* ***Operating System***: Mac OSx
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by medikoo** [comment]
@coulson84 great thanks for report.

Is there any chance you can prepare for us a minimal test case, so we can fully reproduce the issue.

From example you posted I hardly see what can go wrong, e.g. it definitely works as expected for typical async functions (support for async/await is ensured)

**Comment by coulson84** [comment]
Okay. I am having trouble getting a minimum test case that replicates the issue which points to a deeper issue (probably not related so serverless) however the code that was running was definitely completing but there may have been something else going on (due to webpacking and minification) that caused the issue. As the code below should have replicated the issue

module-1.js
```
export function wait() {
    return new Promise(y => setTimeout(() => y(), 1000);
}
```

handler.js
```
import {
    wait,
} from 'module-1.js';

export function main() {
    const anArray = [0,1,2,3];
    for(const i of anArray) {
        await wait();
    }

    console.log('complete'); // this console.log was firing but the lamda would sit and timeout unless the serverless wrapper was removed. Cannot replicate with this simple example though which points to an alternative cause
    return 'success';
}
```

**Comment by alfaproject** [comment]
I'm having the same issue actually. I wrap my handlers in a `sentryfy` method that looks like this:

```ts
import * as Sentry from '@sentry/node';
import { Handler } from 'aws-lambda';

/** Decorates the given handler for capturing errors to Sentry. */
export function sentryfy<T extends Handler>(handler: T): Handler {
  return (event, context, callback) => {
    // Wrap the original callback if it exists
    if (callback) {
      const originalCallback = callback;
      callback = (error, result) => {
        if (error) {
          Sentry.captureException(error);
          originalCallback(error);
        } else {
          originalCallback(error, result);
        }
      };
    }

    // Execute the handler
    const promise = handler(event, context, callback);
    if (promise && promise.then) {
      return promise.catch(async error => {
        // Capture error
        Sentry.captureException(error);
        try {
          await Sentry.flush(2000);
        } catch (err) {
          console.log('Error while sending Sentry report', err);
        }

        return Promise.reject(error);
      });
    }
  };
}
```

**Comment by caiocutrim** [comment]
I have the same issue after create a function that calls a model with async-await
