### ISSUE TITLE
Websocket loop

### ISSUE THREAD

**Issue by biljecki** [serverless/serverless#6249]
I'm not too experienced with websockets, especially on serverless, so a lot of stuff are foggy to me: I want to make a simple real time game where a function would be invoked say 30 times a second and each time emits the data to the clients (basically mimicking a 30fps game loop).

I tried a simple example by adding a setInterval (at 1000ms) in one of the handlers and it works - but only for 6 seconds according to the logs (guessing that is a maximum lifespan of a lambda function?) :

> { "action":"sendMessage", "data":"emitting every second" }
>< emitting every second
>< emitting every second
>< emitting every second
>< emitting every second
>< emitting every second
>< {"message": "Internal server error", "connectionId":"bOE0QeuzoAMAbSQ=", "requestId":"bOFcfEZMoAMF17A="}

Is there an elegant way to overcome this issue with serverless websockets? 
I wouldn't like to have this function check how many seconds passed and then have it somehow invoke itself again or some similar hacky solution...

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
