### ISSUE TITLE
Internal Architectural Refactor:  Improve Our Class Architecture and Class Methods For Better Plugin Development

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#625]
In the `v0.5` we are switching classes around for better separation of concerns and we are adding better methods.  This will not break projects, but it will affect plugins.

- [x] Remove ServerlessState class
- [x] Add Project directly to Serverless instance
- [x] Remove Meta class
- [x] Create Stage class
- [x] Create Region class
- [x] Create Runtime classes

**Comment by Nopik** [comment]
I have some work in progress on it, among tons of small cleanups I'm removing ServerlessState class (as 90% of its stuff belongs to project, logically). The current work can be found at https://github.com/Nopik/JAWS/tree/auth-refactor-2 - once it will be ready, I'll do a PR and rebase to newest v0.5 commit. 

My plans for future are also including introducing proper Stage and Region classes, eliminating Meta class, improving performance of load/save operations and few more details.

My general topic is to make those core classes behaving fully as objects, with public interface and hidden internals. For example I'll refactor stuff like `component.functions[ i ]._config.sPath` so e.g. nobody except the owner will talk to `_config`. Most importantly, the biggest issue is that I'll work on separation of concerns, to make sure that one class, and one class only has responsibility to manipulate on its data. For example right now Endpoint is reading/writing s-function.json files, whereas the very existence of s-function.json file should be known only to ServerlessFunction class, and nobody else.

Hopefully, all of those changes will result in a cleaner architecture, which will allow for better velocity when adding new features to the codebase, as well as less amount of bugs and increased readability of the code.

**Comment by ac360** [comment]
:+1:

**Comment by Nopik** [comment]
I've just created #632 with the current status of my work. It should be good to be merged, preferably asap, to avoid conflicts ;) /cc @ac360 @eahefnawy

Almost all items from my list are done. I'm not sure if I will be able to continue on Monday, maybe I will have to stop here. What is left is mostly the Stage/Region/State/Meta classes to get some love.
