### ISSUE TITLE
Upgrading since 1.41 to any more recent version broken with shared API gateway

### ISSUE THREAD

**Issue by duro** [serverless/serverless#6251]
# This is a Bug Report

## Description

* What went wrong?

When trying to upgrade my project which is running 1.41, which implements the shared API gateway pattern, I get a series of errors, and have since 1.42 and every version since.

* What did you expect should have happened?

I should be able to upgrade

* What was the config you used?

I have a service which describes my API gateway, and exports the `RestApiId` and `RestApiRootResourceId`. These values are then used by the services.

Examples: https://gist.github.com/duro/45a8fb108b64465a34475b1bb23a9c8c

* What stacktrace or error message from your provider did you see?

First time:

```
An error occurred: ApiGatewayStage - Deleting stage dev failed. Please remove all base path mappings related to the stage in your domains: api.fbird.dev (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 15bc8e44-8d66-11e9-bafd-a37831796ed3).
```

Then if I actually manually clear my base path mappings:

```
Rest API could not be resolved. This might be casued by a custom API Gateway setup. With you current setup stage specific configurations such as `tracing`, `logs` and `tags` are not supportedPlease update your configuration or open up an issue if you feel that there's a way to support your setup.
```

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/6140

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: darwin

**Comment by duro** [comment]
@pmuens and the entire Serverless team. I'm getting pretty desperate on this issue. It, and variants of it, have been reported multiple times in multiple reports.

Any update on whether it's being looked into? Any info I might be able to provide to help move the process along.

**Comment by pmuens** [comment]
Hey @duro thanks for opening this issue :+1:

Sorry for the slow response on our end. We're looking into this right now...
