### ISSUE TITLE
Wider `logs:CreateLogStream`/`logs:PutLogEvents` permissions in policy for Lambda functions with manual names (v1.45.1)

### ISSUE THREAD

**Issue by onebytegone** [serverless/serverless#6262]
# This is a Bug Report

## Description

* What went wrong?

   When a service contains only custom named functions, the policies for `logs:CreateLogStream` and `logs:PutLogEvents` created using v1.45.1 have a wider set of permissions than they previously did with v1.44.1.

   ### Resource access allowed when using v1.44.1

   * `logs:CreateLogStream`:
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-custom-named-fn:*`
   * `logs:PutLogEvents`:
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-custom-named-fn:*:*`

   ### Resource access allowed when using v1.45.1

   * `logs:CreateLogStream`:
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-dev*:*`
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-custom-named-fn:*`
   * `logs:PutLogEvents`:
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-dev*:*:*`
      * `arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/log-group-policy-custom-named-fn:*:*`

* What did you expect should have happened?

   Based on the principle of least privilege, the additional permissions for `/aws/lambda/log-group-policy-dev*` should not have been added to the IAM policy.

* What was the config you used?

   Full source: [log-group-policy.zip](https://github.com/serverless/serverless/files/3296986/log-group-policy.zip)

   ```yaml
   service: log-group-policy

   provider:
      name: aws
      runtime: nodejs8.10

   functions:
      testFunction:
         name: ${self:service}-custom-named-fn
         handler: index.handler
   ```

   #### To compare output between v1.44.1 and v1.45.1

   ```
   unzip log-group-policy.zip
   cd log-group-policy
   echo '{}' > package.json
   npm i serverless@1.44.1
   ./node_modules/.bin/sls package
   cp .serverless/cloudformation-template-update-stack.json cf-update-stack-v1.44.1.json
   npm i serverless@1.45.1
   ./node_modules/.bin/sls package
   cp .serverless/cloudformation-template-update-stack.json cf-update-stack-v1.45.1.json
   diff cf-update-stack-v1.44.1.json cf-update-stack-v1.45.1.json
   ```

Similar or dependent issues:
* #6236 (PR #6240)
* #6212

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.1
* ***Operating System***: macOS 10.14
* ***Stack Trace***: n/a
* ***Provider Error messages***: none

**Comment by rdsedmundo** [comment]
This was done to avoid a hard AWS limit of the size of a single role.

We can make the least-privileged permission as an option if some users find the wider troublesome. Another option is to have each function to have its own role, but the statements added via the `iamRoleStatements` would need to be duplicated on each of them.

**Comment by onebytegone** [comment]
@rdsedmundo Yep, that's what I gathered from the original PR (#6212). The concept behind those changes makes sense. My main concern is serverless now allows access to `/aws/lambda/log-group-policy-dev*` when it is not actually needed (i.e. when the service does not contain any functions that are using the default serverless naming scheme).

Looking at the changes in #6240, is seems like it might be fairly straight forward to add a check that only adds the new "merged/wildcard" permission when it is actually needed (i.e. when there is at least one function using the default naming pattern). I'm happy to submit a PR to change this. However before I did so, wanted to get your all's stance on the matter.

**Comment by rdsedmundo** [comment]
Oh ok, you're talking only about the functions with custom names, that's fair enough. I agree with that.

[Here](https://github.com/serverless/serverless/pull/6240/files#diff-bb02cdd69514f709dc6a204a5d0dc376R114) we're already looping in all the functions and adding an entry for each of the custom names, so I agree that the wildcards are not necessary in this case. 

I wouldn't even bother of trying to detect when there's more than one fn starting with the same pattern and trying to use a wildcard for these cases. In my opinion, we can leverage the wildcard just for the default Serverless naming pattern, and if a user chooses to use custom names he has to bear in mind that this is going to grow his/her the role size. For hitting the limit the user would need to have like 40+ custom functions.
