### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by JonathanWilbur** [serverless/serverless#6267]
# This is a Bug Report

## Description

* What went wrong? `Cannot read property 'split' of undefined` with certain uncaught exceptions.
* What did you expect should have happened? Just see the `errorMessage`, `errorType`, and `stackTrace`.
* What was the config you used? Irrelevant.
* What stacktrace or error message from your provider did you see? `Cannot read property 'split' of undefined`

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.1
* ***Operating System***: Mac OS X 10.14.5
* ***Stack Trace***: None.
* ***Provider Error messages***:

The issue is that I am using the `ajv` library to validate JSON. It throws an error, and because this error does not have a `stack`. It crashes here at `.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:551:33` because `err.stack` is `undefined`, but Serverless tries to `split()` `err.stack`. Even the TypeScript definition shows that `err.stack` can be undefined.

**Comment by medikoo** [comment]
@JonathanWilbur great thanks for reporting, by any chance do you know why there's no `stack` property on this error? Can you point us to point where such "error" is generated on AJV side?

It's very weird as in V8 every error instance by design is accompanied with a stack.
TypeScript defines `stack` as possibly `undefined` purely because it's not a standard property and some JavaScript engines may not provide it, still it's not the case in Node.js

**Comment by JonathanWilbur** [comment]
I think it is probably because of the strange way that AJV seems to create subclasses of `Error`:

https://github.com/epoberezkin/ajv/blob/ab841b462ec4baff37d2a7319cef13820b53d963/lib/compile/error_classes.js#L5-L15

Then further down:

https://github.com/epoberezkin/ajv/blob/ab841b462ec4baff37d2a7319cef13820b53d963/lib/compile/error_classes.js#L30-L34

I will write up an issue there, too, but this still should be fixed in Serverless too, rather than assuming that it will always be there.

**Comment by medikoo** [comment]
> I will write up an issue there, too

I would consider it as a bug on AJV side, so definitely worth reporting there

> Still should be fixed in Serverless too, rather than assuming that it will always be there.

It's fine to patch it, but probably more proper fix, would be to improve our error instance detection.

`instanceof` is easily hackable and doesn't work cross realms. It passes here only bacause object was derived from `Error.prototype`, even though it was not created via `Error` or its subclass constructor.

We may e.g. rely on [type/error/is](https://github.com/medikoo/type#erroris) which I'm pretty sure will not validate that "error" object.

Still that's not a dependency we use in SLS (at least yet), no it introduces some disruption into our conventions. @pmuens what do you think?
