### ISSUE TITLE
instanceId cannot be used in a CloudFormation resource name

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#6271]
resources:
      Resources:
        myApiGatewayDeployment${sls:instanceId}:
          Type: AWS::ApiGateway::Deployment

leads to:

     The CloudFormation template is invalid: Template format error: Resource name 
    myApiGatewayDeployment${sls:instanceId} is non alphanumeric.

**Comment by pmuens** [comment]
Hey @cyberfox1 thanks for opening :+1:

Keys cannot contain Serverless Variables, that's why you're seeing this error. Here's the main issue which discusses Serverless Variable usage for keys: https://github.com/serverless/serverless/issues/2892

**Comment by ashwinsaval** [comment]
But what is the solution? There are use cases where we need to override resource names that use serverless variables.

**Comment by jorgearellano19** [comment]
> But what is the solution? There are use cases where we need to override resource names that use serverless variables. In my case `ApiGatewayDeployment{instanceId}` which I need to override `AccessLog` settings

 @ashwinsaval  Di you figure out a way to make that? I have the same problem as you
