### ISSUE TITLE
serverless deploy from aws vpc without access to internet 

### ISSUE THREAD

**Issue by shahollik** [serverless/serverless#6276]
Hello,

running a serverless deploy from a jenkins pipeline in an AWS vpc without any access to internet fails due to the getCallerIdentity() call made to STS.  Currently STS does not have a VPC endpoint as so deploying from an aws vpc without internet does not work.

**Comment by jplock** [comment]
Are you able to add a VPC Endpoint to STS?

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_sts_vpce.html

**Comment by shahollik** [comment]
Yup, that's the problem, right now STS VPC endpoints are only supported in us-west-2 and we are in a different region.  Contacted AWS support and they do not know when it will be available in different regions.

**Comment by shahollik** [comment]
the call is being made in the awsProvider.js in the `getAccountInfo()` method.  can we just add a configuration property for the iam user ARN such that, if it is configured, we can bypass the call to STS and use the property instead?

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
