### ISSUE TITLE
AWS and local invoke payload differences

### ISSUE THREAD

**Issue by jpetitcolas** [serverless/serverless#6287]
# This is a Bug Report

## Description

We are currently facing a behavior difference between AWS and serverless when using local invokes. 

Let's consider the following Python handler:

```py
def get_greetings(event, context):
    # it may raise a KeyError if no name param is provided
    name = event['name']

    return {
        'hello': name
    }
```

Executing this lambda on AWS console provides the following outputs:

```
# Event: {}
{
  "errorMessage": "'name'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 3, in get_greetings\n    name = event['name']\n"
  ]
}

# Event: { name: "John" }
{
  "hello": "John"
}
```

Now, when I invoke locally my function, using following code:

``` js
const lambda = new Lambda({
    endpoint: process.env.IS_OFFLINE ? 'http://lambdas:6500' : null,
});

const response = await lambda
    .invoke({
        FunctionName: `acme-${config.ENV}-get_greetings`,
        LogType: 'Tail',
        Payload: JSON.stringify(payload),
    })
    .promise();

console.log(response);
```

I got different outputs:

```
# Payload: {}
{ StatusCode: 200, Payload: '' }

# Payload: { name: "John" }
{ StatusCode: 200, Payload: '' }
```

Yet, if I wrap my responses in a `body` parameter such as:

```py
return {
    'body': json.dumps({ 'hello': name })
}
```

I get the following payload:

```js
{
    StatusCode: 200,
    Payload: '{"body":"{\\"hello\\": \\"John\\"}"}'
}
```

I didn't take a look on it for now: can you confirm that's indeed a bug? :)

I found a workaround to let me work with almost the same code on both local and AWS:

```py
def return_value(value):
    if 'IS_OFFLINE' in os.environ:
        return {
            'body': json.dumps(value)
        }

    return value
```

And on the consumer side, I'm using:

```js
let payload = null;
if (config.TINT_ENV === 'dev') {
    payload = JSON.parse(response.Payload).body;
} else {
    payload = response.Payload;
}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.1
* ***Operating System***: Docker: Amazon Linux AMI 2017.03 / Host: Ubuntu 18.10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pgrzesik** [comment]
Closing due to long inactivity
