### ISSUE TITLE
VPC Support

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#629]
Research and implement...

**Comment by eahefnawy** [comment]
This should be simple to implement. It's just a new parameter to be added to the `createFunction` and `updateFunction` methods on the `Lambda` class. We'll just have a new property in `s-function.json` file that we use when we create the lambda function using the AWS SDK.

I'm on it! :)

**Comment by staceymoore** [comment]
@eahefnawy  Here are my notes after setting up my sls project with VPC and NAT Gateway. Thought I would share in case any of it is helpful for you or anyone else using sls with VPC.

**Notes from my adventures with Lambda and VPC _(before it was built in to sls)_**
* Remember to update your aws cli to the latest version
* Update s-resources-cf.json (or s-project.json for older versions of sls) to give IamPolicyLambda permission to manage network interfaces. Lambda in VPC creates an ENI for each lambda instance.

```javascript
// IAM policy statement required to give Lambda execution role VPC access
{
  "Effect": "Allow",
  "Action": [
    "ec2:CreateNetworkInterface",
    "ec2:DescribeNetworkInterfaces",
    "ec2:DeleteNetworkInterface"
  ],
  "Resource": "*"
}
```

* Lambdas are launched into subnets that are specified in the config. If you want your lambda to scale and have high availability, use subnets in multiple availability zones with plenty of IPs available in each.
* Lambda essentially runs inside the security group(s) you specify in the config. If you don't already have it, create a security group with proper inbound/outbound rules.
* If your Lambdas need internet access, create a NAT Gateway in your VPC. If you need your outbound requests to be whitelisted somewhere, assign an EIP to your NAT Gateway.
* Run the command below to update the lambda config for each function that you want to have VPC access (once this is built into sls you won't need to do this anymore)

```bash
# command to give Lambda function VPC access
aws lambda update-function-configuration --function-name <lambda function name> --vpc-config SubnetIds=[ <subnets> ],SecurityGroupIds=[ <security groups> ]
```

**Steps to set up VPC to use NAT Gateway (required if function in VPC needs to access the Internet)**
* Create VPC with public and private subnet(s)
* Associate Internet Gateway with VPC
* Create NAT Gateway(s) in public subnet(s)
* Create route table for public subnet(s) with outbound internet traffic going to Internet Gateway
* Create route table for private subnet(s) with outbound traffic going to NAT Gateway
* Create security group(s) with appropriate rules for your use

**Lambda config**
Configure the Lambda to launch in the private subnet(s) and in whatever security group(s) you set up

**Comment by eahefnawy** [comment]
Oh wow, thanks a lot @staceymoore! Do you mind if we borrow some of these notes into our official docs on our next release? :blush: ... I think they're gonna be very helpful!

**Comment by staceymoore** [comment]
@eahefnawy Yes, go ahead! That's why I shared them. There was a bit of a learning curve. I hope this can help reduce it for other people.

**Comment by JamieCressey** [comment]
+1

**Comment by erikerikson** [comment]
@staceymoore One of our groups found itsself needing "ec2:DetachNetworkInterface" as well:

// IAM policy statement required to give Lambda execution role VPC access
{
  "Effect": "Allow",
  "Action": [
    "ec2:CreateNetworkInterface",
    "ec2:DescribeNetworkInterfaces",
    "ec2:DetachNetworkInterface",
    "ec2:DeleteNetworkInterface"
  ],
  "Resource": "*"
}

**Comment by c-knowles** [comment]
+1 - the policy above with ec2:DetachNetworkInterface matches the one that AWS auto generates if you ask for a basic lambda execution role with VPC.

**Comment by thedevkit** [comment]
ec2:DetachNetworkInterface is not part of the AWS managed policy AWSLambdaVPCAccessExecutionRole. Their policy statement is as follows:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface"
      ],
      "Resource": "*"
    }
  ]
}
```

I wonder if ec2:DetachNetworkInterface is actually necessary...

**Comment by JamieCressey** [comment]
I don't believe Lambda detaches an ENI, rather deletes it upon completion of the run.

**Comment by JamieCressey** [comment]
Hey @eahefnawy are there any docs on how to implement this new functionality? My understanding is within `s-function.json` it will be something like:

```
{
  "name": "testFunction",
  "handler": "test/testFunction/handler.handler",
  "runtime": "nodejs",
  "timeout": 6,
  "memorySize": 128,
  "VpcConfig": {
    "SecurityGroupIds": [
      "sg-foo"
      "sg-bar"
    ],
    "SubnetIds": "subnet-baz"
  }
  ...
}

```

**Comment by eahefnawy** [comment]
@JamieCressey no docs because it wasn't released yet :) ... what you described is very close, but it differs slightly, here's how your `s-function.json` should look like:

```
{
  "name": "testFunction",
  "handler": "test/testFunction/handler.handler",
  "runtime": "nodejs",
  "timeout": 6,
  "memorySize": 128,
  "vpc": {
    "securityGroupIds": [
      "sg-foo",
      "sg-bar"
    ],
    "subnetIds": "subnet-baz"
  }
  ...
}
```

**Comment by JamieCressey** [comment]
Awesome, thanks @eahefnawy !

**Comment by eahefnawy** [comment]
we should close this issue now that it's included in v0.5 (releasing soon) ... but I'll keep it open to remember to put @staceymoore awesome notes to the docs. Thanks again @staceymoore :blush:

**Comment by SantourA** [comment]
Can the VPC configuration be different based on the stage?  Our DEV/QA targets one VPC; meanwhile our production would target another.  I would like to manage one code base but have the stage drive the VPC configuration.  We build our lambda functions based on ${stage}-${project}-${name} function names.

**Comment by eahefnawy** [comment]
@SantourA you can use variables for that purpose. VPC config are in `s-function.json` and this is where you can reference variables and templates

**Comment by eahefnawy** [comment]
Just referenced @staceymoore notes on our v0.5 docs. Closing this issue...
Thanks guys!

**Comment by picsoung** [comment]
Something that was not mentioned on @staceymoore notes. To apply changes you have to redeploy resources using `sls resources deploy` command line.

Thanks to @HyperBrain on gitter for this tip :)

**Comment by stevecaldwell77** [comment]
If anyone's interested, here's a cfn snippet I'm using to setup a VPC for my lambda functions:

https://gist.github.com/stevecaldwell77/b2e9f9179b4e52235fcee24cf37c8dc9
