### ISSUE TITLE
Update serverless from 1.37.0 fails due to 404 of @serverless/enterprise-plugin

### ISSUE THREAD

**Issue by vikre** [serverless/serverless#6303]
# This is a Bug Report

## Description

* What went wrong?

When trying to update `serverless` from `1.37.0` with `npm install -g serverless` I get a 404 on the dependency `@serverless/enterprise-plugin`. It also happens locally in every app obv.
 
* What did you expect should have happened?
That I get to update `serverless`

* What was the config you used?
- `node v.12.4.0` (have also tried `8.16.0` and `11.15.0`)
- `npm v6.9.0`
- `serverless v1.37.0` which i'm trying to update

* What stacktrace or error message from your provider did you see?
```bash
npm verb node v12.4.0
npm verb npm  v6.9.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverless%2fenterprise-plugin - Not Found
npm ERR! 404
npm ERR! 404  '@serverless/enterprise-plugin@^1.0.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'serverless'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## Additional Data

* ***Serverless Framework Version you're using***: `1.37.0`
* ***Operating System***: `Mac os Mojave 10.14.5`

**Comment by medikoo** [comment]
@vikre it must be some problem with your npm/network setup. I'm pretty sure you use some custom registry, or have some proxy caching on the way, that doesn't ensure to be up to date with npm.

(or maybe you have rerouted scoped packages to some other registry?)

Other possible scenario is that maybe there's some downtime on npm side.

Anyway you can confirm that `@serverless/enterprise-plugin` exists just by going to its npm page: https://www.npmjs.com/package/@serverless/enterprise-plugin

**Comment by vikre** [comment]
@medikoo Thanks for heads up! Forgot that I had some local config to a project repo in `~/.npmrc` that caused trouble, altho I had `registry=https://registry.npmjs.org/`. Thanks for leading me in the right direction!
