### ISSUE TITLE
Could not find component in endpoint (0.4.2)

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#631]
When deploying a project that has two Components, I'm getting this error from ServerlessFunction.js:

    Could not find component for endpoint  

The problem seems to be this function, which matches both of the two components and throws an error because length === 2:

    getComponent() {

      let components = this._S.state.getComponents({
        paths: [this._config.sPath.split('/')[0]]
      });

      if (components.length === 1) {
        return components[0];
      }

      console.log(components);
      throw new SError('Could not find component for endpoint');
    }

(The project has been created with an older version of Serverless. Deploying with 0.3.3 still works.)

**Comment by eahefnawy** [comment]
hmmm let me guess, one of your component names string is a substring of the other component name? :smile:  (i.e. `component` & `componentTwo`)

We should do **exact matching** to fix this issue, but if I remember correctly we're keeping it flexible for a reason.

**Comment by kennu** [comment]
That's right, other is *api* and other is *apidocs*.

**Comment by ac360** [comment]
Shoot.  Didn't think of this.  Let me look into a fix right now

**Comment by Nopik** [comment]
The whole codebase have few `path1.indexOf( path2 ) != -1` - each time I see such construct, an alert goes off in my mind ;)

**Comment by kennu** [comment]
Apparently this substring problem also applies to function names, because I get errors when I try to create these two functions:

    unit/unit-query
    unit/unit-query-my

Incidentally, it is now a bit inconvenient that you have to individually prefix all of those function names with "unit-" to make them unique. Previously it was enough create a Module called "unit" and Serverless would combine the names automatically:

    unit/query
    item/query

Now I need to use this style to keep names unique:

    unit/unit-query
    item/item-query

Serverless doesn't really warn about these conflicts when generating the functions either.

**Comment by ruhkopf** [comment]
:+1: 

This one got me as well. It's really common to name REST resources (and therefore its functions) in plural and singular, e.g. `GET users` returns all users and `GET user` returns a single user. I therefore had two functions `getUsers` and  `getUser` and this seems to break serverless. Really hope this gets fixed soon.

**Comment by vkreal** [comment]
:+1: Got me as well. Please fix soon.

**Comment by cscetbon** [comment]
@ac360 any idea when it'll be fixed ?

**Comment by eahefnawy** [comment]
@cscetbon we've removed the concept of components starting at Serverless v0.5. So you shouldn't face this issue anymore :)
