### ISSUE TITLE
AWS_REGION environment variable `undefined` in 1.46.0

### ISSUE THREAD

**Issue by nathanchapman** [serverless/serverless#6313]
# This is a Bug Report

## Description

Upgrading to v1.46.0 results in the `AWS_REGION` environment variable not getting set to the default `us-east-1` value (and even overwrites it if set). Prior versions including v1.45.1 correctly left the environment variable alone if set, and if unset, let it default to `us-east-1`.

This is breaking for serverless-offline (and possibly other plugins too)

Manually setting `provider.region` to `"us-east-1"` seems to address the issue, but this still seems like a breaking change based on the documentation here: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

Similar or dependent issues:

- #6200

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.0
- **_Operating System_**: macOS Mojave 10.14.5
- **_Stack Trace_**: N/A
- **_Provider Error messages_**: `getaddrinfo ENOTFOUND lambda.undefined.amazonaws.com`

**Comment by medikoo** [comment]
> This is breaking for serverless-offline (and possibly other plugins too)

@nathanchapman  thanks for report.

I which exactly scenario `serverless-offline` is broken? I just tested some basic usage with 1.46.0 and it worked without issues

**Comment by nathanchapman** [comment]
@medikoo I guess this is only breaking (at least for my scenario) when serverless-offline is used in combination with [aws-sdk](https://github.com/aws/aws-sdk-js). For instance, calling `lambda.invoke(...)` on another lambda, requires that the `AWS_REGION` environment variable be set if `region` is not explicitly passed in. `AWS_REGION` is set once the lambda is deployed, but not with serverless-offline anymore as of serverless@1.46.0

**Comment by medikoo** [comment]
Thanks @nathanchapman for details. That should be fixed with https://github.com/serverless/serverless/pull/6317

**Comment by nathanchapman** [comment]
Thank you @medikoo!
