### ISSUE TITLE
Getting "Unable to locate the configuration file for your cluster" for serverless

### ISSUE THREAD

**Issue by bdervishi** [serverless/serverless#6329]
Hi

I'm new at the serverless topic.
I've done the stuff in the turorial at https://serverless.com/framework/docs/providers/kubeless/guide/services/ and by deploying it i get the issue "Unable to locate the configuration file for your cluster"

Where can I set them?

Thx

**Comment by pmuens** [comment]
Hey @bdervishi thanks for opening :+1:

This seems to be related to the Kubeless plugin. Could you open up an issue in such repository (https://github.com/serverless/serverless-kubeless) thanks!
