### ISSUE TITLE
Exclude common Yarn log files

### ISSUE THREAD

**Issue by henrikbjorn** [serverless/serverless#6333]
# This is a Feature Proposal

## Description

Currently serverless excludes the common `npm-debug.log` file which makes sense. With `Yarn` being extremely popular and gaining marketshare I believe it should also ignore:
- `yarn-debug.log`
- `yarn-error.log`

**Comment by medikoo** [comment]
> Currently serverless excludes

Excludes from where? Lambda packaging?

**Comment by henrikbjorn** [comment]
Yes from the packaged zip file.

**Comment by medikoo** [comment]
It might be nice to rely on what's in`.gitignore`, and then imo that should be covered automatically.

Still question is whether it'll not break packaging which relies on interim files (which may be referenced in `.gitignore` then)

**Comment by colonelpopcorn** [comment]
I can definitely see several files being ignored that you would want to be uploaded `target` folders in Java projects and `dist` folders in typescript projects would fail to be uploaded if we just used a gitignore file.

**Comment by CSP197** [comment]
@medikoo - Would it make sense to exclude all log files from the packaged lambda zip file?

**Comment by medikoo** [comment]
> @medikoo - Would it make sense to exclude all log files from the packaged lambda zip file?

I think such generalization may unexpectedly bite in some corner cases.

Still adding `yarn-*.log` to fixed ignore list, seems safe, and we definitely can do that (we're open for PR's).

We also plan some extensive packaging improvements (explained in #6580), which include option of packaging only files that are used by lambda (that will naturally strip yarn log files)
