### ISSUE TITLE
 "provider" property is missing in serverless.yml

### ISSUE THREAD

**Issue by felixchan** [serverless/serverless#6340]
# This is a Bug Report

## Description

- What went wrong?

Serverless deploy throws error

- What did you expect should have happened?

Deploys

- What was the config you used?

```
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           11.10.1
     Serverless Version:     1.46.1
```

- What stacktrace or error message from your provider did you see?

``` "provider" property is missing in serverless.yml```

Similar or dependent issues:

- #12345

## Additional Data

```
service: aws-nodejs 
provider:
	name: aws
	runtime: nodejs10.x
functions:
  	hello:
    	    handler: handler.hello
	    events:
		    - http:
			    path: users/create
			    method: get
```

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by bedamatta05** [comment]
Hey how to solve this. ?

**Comment by felipevyg** [comment]
If you're here and using a TypeScript file for serverless (serverless.ts), then make sure you're not exporting the module as: `export default ...`. Use `module.exports = {}` instead.
