### ISSUE TITLE
Isolated serverless process

### ISSUE THREAD

**Issue by msudgh** [serverless/serverless#6341]
I'm wondering serverless process isolated or not. as the following screenshot, i got signals of the old process in the new process.

the old process signal: `Serverless: Got SIGINT signal. Offline Halting...`

![carbon](https://user-images.githubusercontent.com/11756815/60806420-2935bf80-a198-11e9-9791-acc82f2327a9.png)

**Comment by medikoo** [comment]
@msudgh isn't more for [serverless-offline](https://github.com/dherault/serverless-offline)?

**Comment by msudgh** [comment]
@medikoo logs printed out by that package but i think it's not `serverless-offline` job to be isolated.

**Comment by msudgh** [comment]
@davegariepy No unfortunately

**Comment by medikoo** [comment]
Please move it to `serverless-offline` repo. If you feel that some improvement can be made in Framework, please open a feature request report specyfing exactly the use case.
