### ISSUE TITLE
Variable for the uploaded zip file

### ISSUE THREAD

**Issue by drieshooghe** [serverless/serverless#6357]
# Uploaded Zip reference variable

It would come in handy if the serverless variables would contain a reference to the uploaded zipfile's s3 bucket and s3key.
This way the file can be referenced in other CloudFormation Resources

**Comment by medikoo** [comment]
@drieshooghe Thanks for proposal. Can you clarify the use case?

**Comment by drieshooghe** [comment]
@medikoo I honestly can't remember 😅 closing this issue.
