### ISSUE TITLE
How to target create lifecycle event?

### ISSUE THREAD

**Issue by ZebraFlesh** [serverless/serverless#6374]
How can I target the [create lifecycle event](https://serverless.com/framework/docs/providers/aws/cli-reference/create/) using a plugin? This seems to be different from other lifecycle events and is non-obvious to me. For example, when I run `sls create --template-path /some/path --path new-service-from-template`, how do would serverless even know about my plugin so it could execute it? I tried [asking this on gitter](https://gitter.im/serverless/serverless?at=5d251c72acab0914d8dc8bf1), but did not receive a response.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
