### ISSUE TITLE
Feature Request: Allow same bucket+event multiple times when adding events to existing S3 Bucket

### ISSUE THREAD

**Issue by tcastelli** [serverless/serverless#6390]
Now that 1.47.0 supports adding events ( https://github.com/serverless/serverless/pull/6290 to existing s3 buckets ), it could be really helpful to also allow something like https://github.com/matt-filion/serverless-external-s3-event/issues/62
so that we can add the same bucket+event trigger multiple times on different prefixes (I've just tried and only the first one was created as stated on the docs)

**Comment by pmuens** [comment]
Thanks for opening @tcastelli :+1:

Unfortunately I cannot access the linked issue anymore. We're currently working on a fix for that which is tracked via https://github.com/serverless/serverless/issues/6461.
