### ISSUE TITLE
AWS Credentials with "+" are not allowed

### ISSUE THREAD

**Issue by roemhildtg** [serverless/serverless#6392]
The `serverless` cli utility does not allow you to create aws credentials that have "+" characters in the secret key. My aws secret key generated had 2 + sign characters. After removing them and the utility allowed me to save the credentials. Afterwards I was able to manually paste in my correct secret key to the ~/.aws/credentials file.

I'm on Windows 7 x64.
I'm running the serverless command from git bash 4.4.19

**Comment by medikoo** [comment]
Great thanks for report! It was already fixed in https://github.com/serverless/serverless/pull/6387

Will be published with next release.
