### ISSUE TITLE
NoSuchBucket & Stage exists

### ISSUE THREAD

**Issue by raineroviir** [serverless/serverless#640]
I manually removed my S3 bucket.  Is there a way to manually remove the Stage dev? My API gateway on AWS has no stages

When I run ` sls stage remove`      
```
Serverless: Removing stage "dev"...  
Serverless: Removing region "us-east-1" in stage "dev"...  
{ [NoSuchBucket: The specified bucket does not exist]
```

When I run `sls project init`
```
ServerlessError: Stage dev already exists
    at new ServerlessError (.../serverless/lib/ServerlessError.js:17:11)
```

**Comment by raineroviir** [comment]
fixed by deleting meta folder.

**Comment by contractorwolf** [comment]
I am getting that error too, why does deleting the _meta folder solve the issue?

**Comment by raineroviir** [comment]
I'd assume because the meta folder saves references to your external AWS account

**Comment by contractorwolf** [comment]
and then you re-ran "sls project init" to recreate the folder?

**Comment by raineroviir** [comment]
Yeah, re-setting the whole thing and starting over :)
