### ISSUE TITLE
How to debug line-by-line using WebStorm?

### ISSUE THREAD

**Issue by rborja-visp-net** [serverless/serverless#643]
I'm in this point of examining how my code behaves but in order to go deep, I need to perform line-by-line execution. Is there any debugging configuration to setup when using serverless?

**Comment by n8sabes** [comment]
1) Use WebStorm and write Mocha unit tests. Run the Mocha unit tests in debug mode with break points and step line-by-line. You can have the unit test hit live services such as DynamoDB, or local instances of DynamoDB. One shortcoming is that you cannot use API Gateway for full end-to-end tests.

2) When deployed, log, log, log to CloudWatch.

3) There may be a possibility of debugging via a lightweight server such as @Nopik's, but I have not taken the time to setup the environment and work through the details. When I looked at his server it was not a full Sim, but still an excellent tool.

If you're looking for Lambda execution environment-level information, logging to CloudWatch or an S3 file is likely the primary tool. You might checkout how native golang code is run in Lambda for additional ideas and insights about execution environment behavior.

There are likely other techniques.

**Comment by eahefnawy** [comment]
We're trying to make debugging much easier. `sls function run` can now run your lambda locally **or the deployed function if you provide a stage and region**. On top of that, we have a new `sls function logs` action that fetches the logs from CW, and we're now working on an `sls endpoint run` action to test your endpoints as well.

If you have any suggestions on how to make debugging easier for you, please let us know! :blush:

**Comment by rborja-visp-net** [comment]
**Warning**: tl;dr

@n8sabes Thank you for the thoughtful feedback and my team appreciates the insightful points you give! Generally, unit tests are done before implementing and testing the actual integration of the functionality (Please correct me if I'm wrong). We do understand that we can't perform tests on an actual API Gateway environment but I would really like to emphasize the question that **is it really possible to specify breakpoints on Lambda handlers and use them in WebStorm to debug and simulate the execution of the code line-by-line?** We may experience at some point that monitoring on CloudWatch is infeasible (while still considering it helpful). #3 you mentioned, it piques my interest to ask if there's a possible link to its documentation because that would really solve our problem. :)

@eahefnawy Wow! A lot of commands that we didn't know they exist! But even still, it would be really helpful if Serverless would support IDE's on breakpoints and an interactive line-by-line debugging. While monitoring on CW is an option, it would literally save us more time by analyzing the code and replicating the issue through a common method which we all know what I'm referring to. :) 

Serverless has to catch up a lot of brilliant ideas that are still not yet integrated! I would be willing to suggest more whether they are ideas, suggestions, questions or in combination!

**Comment by grandmore** [comment]
You can debug line by line by line in web storm. I currently use ``serverless-serve`` to run the function (it is not perfect but allows debugging while coding)

Select Edit Configuration in Webstorm and do the following:
1) node interpreter: ```/usr/local/bin/node```
2) working directory : (set to the folder of your serverless code)
3) application Parameters: ```/usr/local/bin/serverless  serve start --prefix dev```

Then just run the debugger and you can debug line by line.

**Comment by rborja-visp-net** [comment]
Hi @grandmore! This is a really helpful info and what I'm actually looking for! Will try that the next morning at the office. Thanks! :) 

I'm closing this issue now. Thank you guys for the responsive feedback and the assistance! Wishing everyone's success!

**Comment by ngothanhtai** [comment]
@grandmore Excellent! :+1: Thanks for your instruction.

**Comment by KowalskiTom** [comment]
To get this working on a copy of Webstorm running on Windows here is the following configuration that I had to use:

Select Edit Configuration in Webstorm and do the following:
1) node interpreter: C:\Program Files\nodejs\node.exe
2) working directory : (set to the folder of your serverless code)
3) JavaScript file: C:\Users\username\AppData\Roaming\npm\node_modules\serverless\bin\serverless
4) application Parameters: serve start

Hope this helps someone! It took me a while to figure it out.

**Comment by rehrumesh** [comment]
Any idea how to do this with visual studio code or atom?

**Comment by prad9** [comment]
Would be awesome if we can debug the application by running command like sls function debug

**Comment by sscarduzio** [comment]
How to do this in serverless 1.x ?

**Comment by gregholland** [comment]
Any updates for how to do this with 1.x?

**Comment by pmuens** [comment]
@gregholland right now there's no native support for debugging function code from within the Serverless CLI.

However you could use `serverless invoke local`, intercept this command and use breakpoints in e.g. Visual Studio Code to debug your functions code.

Other than that you might call your function via node and use the v8 debugging capabilities.

**Comment by OneMuppet** [comment]
I'm not sure if it helps but I have a working example of this using vscode as IDE. I know many people including myself have been looking for it so I'd thought I'd take the time to set it up. Hopefully it will help someone. I know it isn't web storm but I've been hitting this page when googling for debugging solutions.  
https://github.com/OneMuppet/local-lambda-debug

I wrote a small post regarding this also: 
https://medium.com/@OneMuppet_/debugging-lambada-functions-locally-in-vscode-with-actual-break-points-deee6235f590

**Comment by uslperera** [comment]
This is the method I used to debug using VS Code. For this solution you need to have **node-debug** installed.

- First add a debugging configuration **Launch via NPM**. 
- Next change the package.json like shown below.
![image](https://user-images.githubusercontent.com/6910356/27346593-54db8938-560b-11e7-9e61-16c32236fff8.png)

**Comment by johnwenaus** [comment]
Our code is run via serverless + aws.  The following instructions are to enable debugging in VS.Code with these constrains.

- Enable debugger in VS.Code user setting
  - [Menu] -> Code -> Preferences -> Settings
  - On the Top Right corner, select "User Settings"
  - Add the following section
```
{
    "window.zoomLevel": 1,
    "files.trimTrailingWhitespace": true,
    "editor.tabSize": 2,
    "launch": {
        "version": "0.2.0",
        "configurations": [
          {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}"
          },
          {
            "name": "Attach by Process ID"
          }
        ]
      }
}
```

- In terminal, do your usual `awsauth` (if you are using aws) and `npm start` (`start` is a script in package.json)
- Set break point in your code
- Start debugger via [Menu] -> Debug -> Start Debugger 
  - Pick a process to attach. VS.Code is smart enough to default the process to your terminal running serverless

**Comment by lucasklaassen** [comment]
Anyone that comes across this thread and uses the serverless-webpack plugin, you are not alone: https://www.lucasklaassen.com/post/1/debugging-lambdas-serverless-webpack

**Comment by macs91** [comment]
@lucasklaassen have you managed also to make it working with dynamodb local?

**Comment by lucasklaassen** [comment]
@macs91 good question, I've used dynamodb in some past projects but I'm not sure if I've used debugging within VSCode on those projects.

For reference here are the local dynamoDB npm packages I've used in the past:
[serverless-dynamodb-local](https://github.com/99xt/serverless-dynamodb-local#readme)
[This fork](https://github.com/Vin65/dynamodb-localhost) allows you to run dynamoDB on a different port specified in your serverless.yml. It's a dependency of serverless-dynamodb-local, so you just have to include it in your package.json.

Here's what the serverless.yml custom config looks like:
```yml
custom:
  dynamodb:
    start:
      port: 8000
      migrate: true
```
`serverless offline start` then takes over starting dynamoDB on port 8000 and your local serverless functions run on port `3000`.

**Comment by macs91** [comment]
@lucasklaassen I have your same config (with different ports). Unfortunately, when I use the `start` command in my `launch.json` neither the serverless offline nor dynamodb local are started.. I tried to play with different settings but I've had no luck, so for now I'm sticking to `console.log` 😅

**Comment by apostrophedottilde** [comment]
You can debug locally using the offline plugin.

First you install the npm package 'serverless-offline' and add the plugin to your serverless.yml with

plugins:
  - serverless-offline

So then you would create a new nodejs run configuration in WebStorm / intelliJ and set the serverless project root as the project root, then set the application parameters to 

node_modules/serverless/bin/serverless offline --skipCacheInvalidation

You can now run this in debug mode and you'll be able to debug locally like any other app.

I hope this helps somebody because it took me a while to figure it out.

**Comment by snolangps** [comment]
@apostrophedottilde how do you invoke the lambda function you want to test locally? e.g. `invoke local -f someFunc --path ./path/to/data.json`

Your explanation is great, but feel its missing some info. I'm using WebStorm and trying to invoke a function and test the logic locally, is this the same methodology you're using?

**Comment by Vadorequest** [comment]
@apostrophedottilde Awesome! Thanks, had to use `sls offline start` to run my dynamodb too, otherwise it would only start the server itself (no different from what my "yarn start" actually does so figured it out pretty fast)

![image](https://user-images.githubusercontent.com/3807458/47397074-d3b2a300-d72d-11e8-8fb8-145cc7c6d95d.png)

**Comment by nsrau** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
WebStorm 2021.2.1

Node interpreter: Project node(C:\Program Files\nodejs\node.exe)
Node parameters:
Working directory: path_project\sls
JavaScript file:
Application parameters: C:\Users\myUser\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js offline
Environment variables:

this debugging configuration worked for me
