### ISSUE TITLE
Deploying a Method to an Existing AWS API Gateway Resource

### ISSUE THREAD

**Issue by pputra** [serverless/serverless#6437]
How do I deploy a method to an existing API Gateway without recreating the whole resource? 
For example, previously, I already had a resource that was already deployed without using Serverless. Now, using Serverless, I want to add a new method under that existing resource.

**Comment by pmuens** [comment]
Closing this issue since it's more like general question rather than a bug / feature request. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
