### ISSUE TITLE
event deploy puts AWS Lambda in an error state (AWS returns http 500)

### ISSUE THREAD

**Issue by assaflavie** [serverless/serverless#644]
Added an event source to a function's `s-function` file, as in the example:
```
"events": [
    {
      "name": "schedule",
      "type": "schedule",
      "config": {
        "schedule": "rate(5 minutes)"
      }
    }
  ],
```

Deployed using `sls event deploy -s dev` from my node.js component.
After deploying, AWS Lambda console is unable to display the list of event sources. It receives HTTP 500 when tries to access:
`https://console.aws.amazon.com/lambda/services/functions/reports-node-reports-triage/integrations/event-source/id/scheduled-event?qualifier=dev`
```
{
cause: null,
stackTrace: [ ],
message: "Unable to list event sources.",
status: 500,
localizedMessage: "Unable to list event sources.",
suppressed: [ ]
}
```

[Screenshot](https://www.dropbox.com/s/b7i4d478sit33ct/Screenshot%202016-02-14%2011.25.40.png?dl=0)

**Comment by assaflavie** [comment]
I must say, this puts the whole "use different stages for the same function as a way to separate production from staging/dev" concept in a different light. If a bug or a human error when deploying to the `dev` stage can basically smoke a Lambda function (currently I can't really do anything with it - it has to be deleted and recreated) then a stronger separation has to exist between "stages".
This is a severe issue, IMO.

**Comment by eahefnawy** [comment]
ouch! thanks for reproting @assaflavie :blush ... could you please check the monitoring tab of your lambda function and see if it was invoked multiple times (every 5 mins)? Maybe this is just a bug in the AWS console because I've seen a similar one before that didn't have anything to do with running the lambda function.

**Comment by thedevkit** [comment]
+1

I get a similar problem for SNS Events. Here's my event template: 

`"events": [
    {
      "name": "dev-ProjectName-SNSApnsAddedEvent",
      "type": "sns",
      "config": {
        "topicName": "dev-ProjectName-EndpointCreatedTopic"
      }
    }
  ]`

And the response from AWS:

Request URL: https://console.aws.amazon.com/lambda/services/functions/ProjectName-snsapnsadded/integrations/event-source/id/sns?qualifier=dev

Response: `{"cause":null,"stackTrace":[],"message":"Service error.","status":500,"localizedMessage":"Service error.","suppressed":[]}`

If this helps - it doesn't appear to matter if I point my alias to a different function version, which leads me to believe that the event source was deployed to the alias (which is actually a good thing).

**Comment by thedevkit** [comment]
This may be an AWS bug: https://forums.aws.amazon.com/thread.jspa?threadID=225308

**Comment by c-knowles** [comment]
Also just had this with a scheduled event and behaviour definitely seems to indicate an AWS issue. When viewing the alias on the AWS Lambda console I get `Unable to list event sources` but trying to manually add it to that alias on the same console says it is already added so can't be added again.

**Comment by icrtiou** [comment]
I have this unable to list event sources problem too. So I file a ticket to aws support. Here the response:
> Thanks for reaching out to AWS Support. It looks like your Lambda resource policies are very broad (function can be invoked by any Event Source of any account) and not actually listing the event source ARN (the CloudWatch Event Schedule) and this is why it can't list the source. It's better to add permission to the specific Event Source only. With this approach the Lambda function can then List the source and is more secure.

I don't know where to modify to make this right in `serverless`. anyone?

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
