### ISSUE TITLE
Make multiline templates easier than storing in JSON

### ISSUE THREAD

**Issue by peterfox** [serverless/serverless#645]
To me it seems a bit odd that the templates are stored as a string in s-function.json

I'd advise either a) allow for the use of JSON or YAML (the YAML would be a lot more human readable than the JSON) and provide support for multiline strings to be made or b) instead of placing the template in as a string value, make it possible to reference a Velocity template file from the JSON like so:

```
"requestTemplates": {
        "application/json": {
           "templateFile": "./templates/function.vtl"
         }
      },
```

**Comment by dherault** [comment]
:+1:

**Comment by jeremydaly** [comment]
Referencing a Velocity template would be awesome! +1

**Comment by ac360** [comment]
:+1: to the velocity templates

**Comment by KAJed82** [comment]
I'm truly surprised this isn't already supported. Please add this so my templates can look sane.

**Comment by flomotlik** [comment]
We're currently working on V1 and with that we'll have an improved way of managing templates so you don't just have to put them in as strings.

**Comment by jdavidls** [comment]
I'm very interested in this feature, I think it would be good idea to include VTL in the offline plugin, as a Integration Response. Anyone working in the offline plugin for v1? if not, I could contribute.

**Comment by flomotlik** [comment]
We currently have proposals in #1694 to add your custom templates in an easy way and we're generally trying to include templates for most used content types so you don't actually have to set them up yourself. I'll close this issue in favour of other ones
