### ISSUE TITLE
NPM install of serverless fails

### ISSUE THREAD

**Issue by stephenhandley** [serverless/serverless#6451]
# This is a Bug Report
NPM install fails due to missing dependency version 

## Description
NPM install of serverless failed due to a missing dependency version of `@types/lodash@^4.14.123` for `@serverless/event-mocks`

- What went wrong?
`npm install serverless --global` failed 

- What did you expect should have happened?
For install to work

- What was the config you used?
N/A

- What stacktrace or error message from your provider did you see?
```
$ npm install serverless --global
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/lodash@^4.14.123
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@serverless/event-mocks'
npm ERR! notarget 
```

## Additional Data
Serverless 1.48.4
OS X 10.14.5
Node 10.16.0

**Comment by garethmcc** [comment]
@pmuens @medikoo Is there a recent release that caused this?

**Comment by stephenhandley** [comment]
Going back to serverless@1.42.0 worked for me

**Comment by pmuens** [comment]
Hmm. That's weird. Let me try to reproduce that...

**Comment by pmuens** [comment]
@stephenhandley I tried to reproduce this issue by running the installation process in a dedicated Docker container. Here's my output:

```
Philipps-MacBook-Pro:~ philipp$ docker run -it node:latest bash
root@f5ed7be5b5b5:/# npm install --global serverless
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.48.4 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

 +--------------------------------------------------+
 |                                                  |
 |  Serverless Framework successfully installed!    |
 |  To start your first project, run “serverless”.  |
 |                                                  |
 +--------------------------------------------------+

+ serverless@1.48.4
added 536 packages from 346 contributors in 41.584s
root@f5ed7be5b5b5:/# 
```

Apparently there are no issues on my end. Can you try to re-install it?

**Comment by stephenhandley** [comment]
@pmuens still seeing the same issue on this machine. that said, i'm able to get it to successfully install within `docker run -it node:lts bash`

**Comment by stephenhandley** [comment]
Turns out this is due to an out of date enterprise npm registry. Sorry for the noise.

**Comment by kweros** [comment]
> Turns out this is due to an out of date enterprise npm registry. Sorry for the noise.

How did you update npm registry and solved this situation?
