### ISSUE TITLE
Not able to perform Asynchronous Invocation on lambda with Scheduling

### ISSUE THREAD

**Issue by pramodrwt** [serverless/serverless#6452]
I am not able to Asynchronous Invocation on lambda with Scheduling

` "InvocationType": "Event"`

By default it is synchronously invoking lambda due to that it's not performing retries on lambda
when it is failing 

I have tried:
  

- Update `mexRetries` property in config
- Add `type: Event` inside function config in `serverless.yml`

Want to automate this command 

```
$ aws lambda invoke --function-name my-function  --invocation-type Event --payload '{ "key": "value" }' response.json
{
    "StatusCode": 202
}
```

 Still doesn't work for me 

 https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html

## Additional Data

- **_Serverless Framework Version I am using_**:  "serverless": "^1.32.0",
- **_Operating System_**: Mac

**Comment by pmuens** [comment]
Closing this issue since it's more like general question rather than a bug / feature request. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
