### ISSUE TITLE
How to resolve ApiLambdaFunction error using serverless to deploy Angular app to AWS

### ISSUE THREAD

**Issue by damosull** [serverless/serverless#6453]
I am trying to deploy my Angular app to AWS using the serverless package, following the steps in [this](https://www.youtube.com/watch?v=N-6LtzJezsk) tutorial.

I've followed the steps correctly, & ran `npm run build:serverless:deploy`, but rather than the app being successfully deployed I get the following error message in the console:

> An error occurred: ApiLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: dba0ade8-1f2c-4dc7-8ddc-c2966a54a67c).

When I run node -v in my command line, I see that it's version 10.14.1.

However, I did find the following `nodejs6.10` reference `in serverless.yml`:

    provider:
      name: aws
      runtime: nodejs6.10
      memorySize: 192
      timeout: 10
      stage: production
      region: eu-central-1

Can someone please tell me why this is occurring & how to resolve it?

Here is a [link](https://github.com/damosull/serverless-issue) to the github repo of my code

**Comment by pmuens** [comment]
Closing this issue since it's more like general question rather than a bug / feature request. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
