### ISSUE TITLE
FetchError: network timeout on tracking.serverlessteam.com

### ISSUE THREAD

**Issue by michelem09** [serverless/serverless#6454]
# This is a Bug Report

## Description

- What went wrong?
-- Timeout error randomly when invoking functions locally

- What did you expect should have happened?
-- I did not expect the error

- What was the config you used?
-- I run a command like this `SLS_DEBUG=* serverless invoke local --function checkEpub --path test_sns.json `

- What stacktrace or error message from your provider did you see?
-- Here is the full error

```
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/Users/michele/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
```

## Additional Data

```
  Your Environment Information 
   ---------------------------
     Operating System:          darwin
     Node Version:              8.10.0
     Serverless Version:        1.48.4
     Enterprise Plugin Version: 1.3.2
     Platform SDK Version:      2.1.0
```

**Comment by MacRonin** [comment]
I'm receiving the same error at diff software release and diff command (sls deploy)


$ sls deploy
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - SLS_DEBUG
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: WarmUp: no functions to warm up
Serverless: Invoke webpack:validate
Serverless: Legacy configuration detected. Consider to use "custom.webpack" as object (see README).
Serverless: WARNING: More than one matching handlers found for 'src/hello'. Using 'src/hello.js'.
Serverless: WARNING: More than one matching handlers found for 'src/hello'. Using 'src/hello.js'.
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Serverless: 
User stats error: Request network error: FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/Cellar/serverless/1.48.3/libexec/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout'
}
Serverless: 
User stats error: Request network error: FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/Cellar/serverless/1.48.3/libexec/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout'
}

<--- Last few GCs --->

[8236:0x110000000]    28387 ms: Mark-sweep 2033.1 (2053.7) -> 2032.3 (2053.5) MB, 783.6 / 0.0 ms  (average mu = 0.078, current mu = 0.005) allocation failure scavenge might not succeed
[8236:0x110000000]    29533 ms: Mark-sweep 2033.3 (2053.5) -> 2032.7 (2053.2) MB, 1143.3 / 0.0 ms  (average mu = 0.034, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10071ab19]
Security context: 0x0da5461c0911 <JSObject>
    1: setParentPointers(aka setParentPointers) [0xda58fa97931] [/Users/macronin/Documents/serverless/nwp/nwpPrototype/node_modules/typescript/lib/typescript.js:~31109] [pc=0x3301bdd690d2](this=0x0da5e9f804d1 <undefined>,0x0da5a40c2b99 <NodeObject map = 0xda5a15ddcd9>,0x0da5ad901b39 <NodeObject map = 0xda5f5b9a179>)
    2: bindChildrenWorker(aka bindChildrenWor...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20190727.125419.8236.0.001.json
Node.js report completed
 1: 0x100078b00 node::Abort() [/usr/local/bin/node]
 2: 0x100078c38 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10016ad65 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016ad07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1002c3471 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1002c4318 v8::internal::Heap::HasLowYoungGenerationAllocationRate() [/usr/local/bin/node]
 7: 0x1002c2619 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1002c0f81 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1002c813a v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x1002c8184 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1002a79e2 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0x10049c254 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x10071ab19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
14: 0x3301bdd690d2 
15: 0x3301bdee69b2 
Abort trap: 6
$ 

>   Your Environment Information ---------------------------
>      Operating System:          darwin
>      Node Version:              12.6.0
>      Serverless Version:        1.48.3
>      Enterprise Plugin Version: 1.3.2
>      Platform SDK Version:      2.0.4

**Comment by kenpachiii** [comment]
I believe you get this error when you don't have the free monitoring service enabled.

`serverless dashboard` <- command to enable

otherwise if everything else is fine you should still be able to deploy even without it being enabled. But since you have have verbose flag enabled you'll see the error when it's not enabled.

**Comment by etc-tiago** [comment]
I use the serverless framework for over a year and I never needed it … right now is required to have a key to do deploy? Why did that change now?

**Comment by anujjope** [comment]
Same error I have tried every possible thing, I have even used VPN to check if its related to the network.
Still, the error remains the same
User stats error: Request network error: { FetchError: network timeout at: https://serverless.com/api/framework/track
    at Timeout._onTimeout (C:\Users\cis\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:126:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'FetchError',
  message:
   'network timeout at: https://serverless.com/api/framework/track',
  type: 'request-timeout' }

**Comment by MacRonin** [comment]
I couldn't find a correct way to fix it so I ended up disabling **slsstats** so it would no longer make the call

`serverless slstats --disable`

https://serverless.com/framework/docs/providers/aws/cli-reference/slstats/

**Comment by roboweaver** [comment]
I just noticed the same error, thanks for the disable command - Since I'm not doing anything on the SLS provided service, was surprised that it would be trying to send data back there.

**Comment by deepak7093** [comment]
Facing simliar issue

**Comment by franz-josef-kaiser** [comment]
Honestly, this should be disabled per default.

**Comment by rsshilli** [comment]
I'm on AWS and I see it.  Super annoying.  I agree it should be disabled by default.

**Comment by medikoo** [comment]
The `User stats error: Request network error` is logged only with `SLS_DEBUG=*` and it's purely to report that Framework stats request didn't resolve in expected time frame.

You can safely ignore it, as it doesn't affect in anyway Framework functionality.

We will also improve it, to probably not display this error at all.

**Comment by medikoo** [comment]
@davinerd stack you posted (while not complete) seems unrelated, and it's probably about this issue: https://github.com/serverless/serverless/issues/6667
