### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#647]
AWS IOT offers web socket support. Maybe we can built something around it so that Serverless applications have real time functionality.

**Comment by eahefnawy** [comment]
Hell yeaaah!!!! :smile:

**Comment by trek10-suretint** [comment]
I think that all Serverless needs to handle is creating an IOT rule with an action that invokes a lambda function. It could handled similarly to the way Serverless handles events.

**Comment by hauboldj** [comment]
I think that all serverless needs to do is add support for creating IOT rules with a lambda action.
This could be added into the events section.

**Comment by Aciid** [comment]
This seems to be a more open route to #735. So as per what I've learned from AWS Lambda it seems that anything you can deploy succesfuly to lambda and talks TCP, is not using port 25 should work.

So Serverless just needs the correct event additions if you are planning to work with them inside your deployment.

**Comment by nelsonic** [comment]
Hi we wrote a Demo of using IoT (mqtt) to build **Chat**: https://github.com/dwyl/chat 
***try it***: https://dwyl.s3.amazonaws.com/index.html

IoT _works_.
But there's an ***Elephant in the Room***: ***Cost***. see: https://github.com/dwyl/chat/issues/26
If your app has a network effect e.g. chat or a multi-player online game where you have to distribute messages across many connected users it will cost you a _fortune_. 

P.S: I _really_ hope the priority for WebSockets gets elevated with the vendors.

**Comment by flomotlik** [comment]
Imho we can only really support Websockets once its a proper feature of API Gateway. We can definitely support IOT in the future, but supporting Websockets through IOT for web applications sounds like it wouldn't be a great experience. Will close this issue for now until AWS moves ahead with WS support.

**Comment by trek10-healthsmart** [comment]
You should add IOT rules as an event for the lambda functions, similar to s3 notifications, sns notifications, or scheduled events.

**Comment by flomotlik** [comment]
@trek10-healthsmart we know of a team who has been building an IOT integration for serverless and we're waiting for them to drop it basically. Fully agreed that we want IOT support in serverless

**Comment by tonytamps** [comment]
@flomotlik any news on that integration?

**Comment by pmuens** [comment]
@tonytamps we've added the `IoT` event recently which you can give a spin:

https://serverless.com/framework/docs/providers/aws/events/iot/#iot

**Comment by tonytamps** [comment]
I did give that a go, it doesn't suit my scenario. Cheers anyway @pmuens

**Comment by pmuens** [comment]
Thanks for the response @tonytamps what's your exact use case?

**Comment by tonytamps** [comment]
@pmuens I essentially want a _serverless_ router / translation from WS messages to http requests. 

I need to connect a websocket client to a server I don't control. IoT doesn't have a hosted client, just a hosted server and I can't connect it to an external WS server.

**Comment by pmuens** [comment]
@tonytamps thanks for the insights. I'll reopen this issue so that we can look into more ways how we can make websockets work with Serverless...

**Comment by tonytamps** [comment]
Honestly it doesn't seem possible, it's just not how websockets are supposed to be used. 

The best option I've thought of is to find a saas ws provider who lets you connect to arbitrary ws server and connect it to a serverless function somewhere.

**Comment by pmuens** [comment]
Hey @tonytamps thanks for the feedback!

Yes, you're right. Right now it doesn't seem to be possible. I'll close this issue for now. We'll reopen it once we find new ways to introduce WebSockets.

**Comment by aada** [comment]
Hey @tonytamps have you checked [http://pushpin.org/](url).
I think it could be used as layer in front of api gateway to provide websockets to lambda functions.
Or something like [https://www.graph.cool](url) to support realtime.

**Comment by tonytamps** [comment]
@aada There are two issues with pushpin. 
It's not serverless, it's self hosted and it is targeted at the server-side. 

In my case there is an existing websocket server I want to connect to as the client (using vanilla websockets). When messages are sent down the line from the server I want to execute lambdas.

**Comment by jkarneges** [comment]
In case it's of interest, Fanout (https://fanout.io) offers a cloud version of Pushpin, so it can be used serverlessly. It'll translate WebSocket messages to HTTP requests.

Example here: https://github.com/fanout/serverless-chat

**Comment by tonytamps** [comment]
@jkarneges Thanks for that. I might take a look and see what I can get out of it.
