### ISSUE TITLE
Warning regarding runtime nodejs10.x not permitted

### ISSUE THREAD

**Issue by jeffski** [serverless/serverless#6475]
I just installed the latest version of serverless framework (1.48.4 (Enterprise Plugin: 1.3.3, Platform SDK: 2.1.0)) and ran `serverless` to create a new NodeJS project. 

The serverless.yml sets the runtime as `runtime: nodejs10.x` which is what I want.

When I `serverless deploy` I get the following warning:

```
   2) Warned - Runtime of function label not in list of permitted runtimes: ["nodejs8.10","nodejs6.10","python3.7","python3.6","ruby2.5","java-1.8.0-openjdk","go1.x","dotnetcore2.1","dotnetcore2.0"]
      details: http://slss.io/sg-allowed-runtimes
      Limit the runtimes that can be used.
```
It seems like nodejs10.x hasn't yet been added?

**Comment by dschep** [comment]
We'll make sure the default gets updated, but to resolve this issue, update your safeguard config to include node 10 on dashboard.serverless.com:
![image](https://user-images.githubusercontent.com/667763/62128622-ccaf5700-b2a2-11e9-8fcd-f43a785c3c17.png)
