### ISSUE TITLE
s3 event on existing bucket role

### ISSUE THREAD

**Issue by Frikitrok** [serverless/serverless#6492]
# This is a Bug Report

## Description

- What went wrong?
Moving from serverless-plugin-existing-s3 plugin to native new feature, i see that SLS trying to create AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution. My user do not have permissions to do this action. What the purpose of this role? Current user have permissions to add events to s3, so why i need this role?
- What did you expect should have happened?
All deploying without any new role
- What was the config you used?

custom: bucket: bucket-name
s3:
        bucket: bucket-name
        events:
          - s3:ObjectCreated:*
        rules:
          - prefix: some/path
          - suffix: .xlsx
        existing: true

- What stacktrace or error message from your provider did you see?
Do not have permissions

I am not sure should it be feature request to not creating this role. Please write more information about hove you implement s3 events on existing bucket, because with serverless-plugin-existing-s3 plugin i easy managed to create events

## Additional Data

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.15.3
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.6
     Platform SDK Version:      2.1.0

**Comment by pmuens** [comment]
Hey @Frikitrok thanks for opening this issue :+1:

The implementation for existing S3 buckets is based on custom CloudFormation resources to ensure reliability and resilience. This way we can use one stack to deploy everything rather than relying on raw SDK calls which could cause the stack to drift / get out of sync.

Since a custom resource is orchestrated by a Lambda function we need to add a permission for the Lambda to do the infrastructure setup.

Unfortunately there's no way around that.

**Comment by Frikitrok** [comment]
Maybe i can create this role on my own and specify it in config?

**Comment by ajfisher** [comment]
This is an issue for me as well. As a result of having existing S3 buckets and wanting to attach events to them, serverless wants to create this role. This then updates a considerable number of other functions to want to be managed under that role as well. All my permissions etc come from roles defined in Terraform so this is not really ideal in this scenario.

**Comment by hanikesn** [comment]
@pmuens This is a real issue in enterprise enviroments where role creation might be restricted. E.g. by requiring a naming convention, permission boundary or just completely for developers.
