### ISSUE TITLE
Unit testing lambda functions

### ISSUE THREAD

**Issue by ollierattue** [serverless/serverless#65]
JAWS is going to need unit testing to be considered production ready. I came across https://github.com/SamVerschueren/aws-lambda-mock-context - wondering how others are doing this.

**Comment by flomotlik** [comment]
With our next release we're going to introduce better testability. Sorry for the very late reply

**Comment by ecoruh** [comment]
@flomotlik this is great to hear. Our team's most urgent expectation is test-ability. At the moment we are using ```serverless-mocha-plugin``` (which had some bugs that I created a pull request for). Even though this plugin creates a nice template there are gaps remaining, such as how would you mock end-points (S3 for instance), test internal functions etc. Looking forward to your team's work in the test area. Thanks.
