### ISSUE TITLE
S3 events do not support Filter rules.

### ISSUE THREAD

**Issue by hauboldj** [serverless/serverless#651]
S3 events do not support filter rules.

This should be easy to fix. Just add a bucketFilter property to the events object in s-function.json and just pass it through to the putBucketNotificationConfigurationPromised params here https://github.com/serverless/serverless/blob/master/lib/actions/EventDeployS3Lambda.js#L99

**Comment by eahefnawy** [comment]
Thanks for reporting @hauboldj , I missed that one! Will be available in the next release :blush:

**Comment by JamieCressey** [comment]
Am I right in thinking this will add support for events triggered by prefix or suffix filter rules, and configured as follows:

```
"config": {
        "bucket": "foo",
        "bucketEvents": ["s3:ObjectCreated:Post"],
        "filterRules": [
            "prefix": "bar",
            "suffix": "baz"
        ]
      }
```

**Comment by hauboldj** [comment]
That should do it.

**Comment by mzorzella** [comment]
When are you expecting to commit 8be4595? 

Thanks a lot for you great work with serverless!

**Comment by eahefnawy** [comment]
Should be in our next release (v0.5)...we're aiming to release it by this weekend :) Sorry it took too long :/ we've been super busy on a huge refactor.

**Comment by eahefnawy** [comment]
closing now to keep things clean :) ... Thanks for your help guys!
