### ISSUE TITLE
Published documentation out of date from markdown files in GitHub repo

### ISSUE THREAD

**Issue by mbacchi** [serverless/serverless#6522]
# This is a Bug Report

## Description
Documentation on the [Serverless Documentation site](https://serverless.com/framework/docs/) is severely out of date with the markdown in the docs section of the [Serveless GitHub repository](https://github.com/serverless/serverless/tree/master/docs). I appears the documentation markdown has not been built, parsed, rendered or whatever the term for your build process is, thus not  [published on Netlify](https://github.com/serverless/serverless/issues/3450#issuecomment-293485065) properly.

This same issue [has been raised recently](https://github.com/serverless/serverless/issues/5981), with labels added by @pmuens, but has not received a response, nor resolved.

Another [issue from 2017 has this problem](https://github.com/serverless/serverless/issues/3450), shares the same root cause, was commented on by @pmuens but not resolved. In this specific case the CloudFormation policy document version was correctly written in the markdown [since the document was created](https://github.com/serverless/serverless/blame/master/docs/providers/aws/guide/iam.md#L106), but is apparently not displaying properly still to this day on the [documentation page](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/iam.md).

This [issue](https://github.com/serverless/serverless/issues/6431) opened 18 days ago is related to the same problem. The [markdown](https://github.com/serverless/serverless/blob/master/docs/providers/aws/cli-reference/logs.md) is very verbose about how to properly provide the `--startDate` argument. But the [docs](https://serverless.com/framework/docs/providers/fn/cli-reference/logs/#fn---logs) are absolutely shameful regarding what they neglect to display. The [Examples](https://serverless.com/framework/docs/providers/fn/cli-reference/logs#examples) section does not really show any useful examples. If the docs had been updated the question would not have reached your issue tracker, both the user and the development team would have been able to focus on what they want to be doing rather than dealing with outdated documentation.

I'm guessing if I dug just a little deeper, I'd find more documentation out of date. But what I've uncovered is already pretty depressing.

Please fix your docs, most users don't know that the markdown in the source is even there. This does a disservice to them and yourselves. Many people don't think kindly of a project that has documentation problems.

Similar or dependent issues:

- #5981

**Comment by pmuens** [comment]
@pdaryani isn't this something we've enabled recently? Or was this removed with the docs overhaul?

**Comment by tomchiverton** [comment]
This should be reopened. https://www.serverless.com/framework/docs/providers/fn/cli-reference/logs/#fn---logs is still terrible

Should it just redirect to what seems more complete docs @ https://www.serverless.com/framework/docs/providers/aws/cli-reference/logs ?
