### ISSUE TITLE
Unnecessary deployments with retained lambda layer

### ISSUE THREAD

**Issue by mokamoto12** [serverless/serverless#6532]
# This is a Bug Report

## Description

- What went wrong?
If you specify "retain" in the LambdaLayer, the deployment is performed without modifying the source.
- What did you expect should have happened?
I expect `sls deploy` to skip deployment, when without modifying the source.
- What was the config you used?
lambda layer with retain
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #5765

## Additional Data

- **_Serverless Framework Version you're using_**: 1.49.0 (Enterprise Plugin: 1.3.8, Platform SDK: 2.1.0)
- **_Operating System_**: macOS Mojave 10.14.4
- **_Stack Trace_**: -
- **_Provider Error messages_**: -

I think that the suffix sha for layerLogicalId should be computed with the exception of S3Key.
https://github.com/serverless/serverless/blob/1f1e5c05efb8f061a8b12393e327a9c764d5bbaa/lib/plugins/aws/package/compile/layers/index.js#L54-L61

**Comment by medikoo** [comment]
@mokamoto12 thanks for report. Still I think deployment in such case is expected.

While nothing resource-wise was changed, the CloudFormation instruction have been changed and that has implications on its own.

Imagine the scenario, when after deployment we decide to remove the stack, if prior deployment was skipped, the LambdaLayer will be deleted as _DeletionPolicy_ was not recorded on AWS side.

**Comment by mokamoto12** [comment]
@medikoo Please allow me to check that my understanding is correct or not.
Is the case you are talking about the following flow?

1. Deploy without layer retention
2. Configure to retain the layer and deploy it

I'm sorry if the understanding is wrong. I think it should be deployed in this case.
However, I don't think you need to deploy in the following cases.

1. Deploy with layer retention
2. Deploy as the layer is retained without modifying the source code

I'm sorry if something went wrong.

**Comment by medikoo** [comment]
In following:

> 1. Deploy with layer retention
> 2. Deploy as the layer is retained without modifying the source code

Do you suggest that no configuration changes are made (at 2) after deployment (1) and still further depoyment is fully made?
If not, please clarify _"Deploy as the layer is retained without modifying the source code"_ as it's not clear to me.

**Comment by mokamoto12** [comment]
@medikoo Sorry, I rewrite it as follows.

I don't think you need to deploy in the following cases.
1. `sls deploy` with layer retention
2. `sls deploy` with layer retention, without modifying the source code

I don't think the deployment should be done (at 2).
Am I making sense?

**Comment by medikoo** [comment]
> I don't think the deployment should be done (at 2).

Ok, so you mean that doing two consecutive deploys (with no changes to configuration or source code between them), invokes two full stack deployments, while you expect the second one to be skipped right?

So we can also put it as:

_When layer retention is set, then deployment is never skipped_

Right?

**Comment by mokamoto12** [comment]
@medikoo Tank you!

> Ok, so you mean that doing two consecutive deploys (with no changes to configuration or source code between them), invokes two full stack deployments, while you expect the second one to be skipped right?

Yes! I expect the second one to be skipped!
But It doesn't make sense to me about the following.

> When layer retention is set, then deployment is never skipped

I think this should also be skipped.
Is this wrong?

**Comment by medikoo** [comment]
> But It doesn't make sense to me about the following.

Here I just explained the problem in other words, to ensure we have same understanding.

In all cases if no changes are made the deployment should be skipped, that's expected behavior
