### ISSUE TITLE
Setting IAM policies for Google HTTP functions

### ISSUE THREAD

**Issue by therefromhere** [serverless/serverless#6538]
# This is a Feature Proposal

## Description

Google now supports IAM policies on HTTP cloud functions, and from November 1st new HTTP functions will be private by default.

Does Serverless have any way of supporting this? Eg to explicitly give HTTP functions “Cloud Invoker=allUsers”, which is currently the default, or to set other IAM policies.

This is being phased into the GCloud sdk (see 258.0.0 release notes https://cloud.google.com/sdk/docs/release-notes#25800_2019-08-13 )

```
  Cloud Functions
      ▪ Changed gcloud beta functions deploy to disallow unauthenticated
        callers of new functions by default. The GA gcloud functions deploy
        command remains the same.
```

See forum thread: https://forum.serverless.com/t/setting-iam-policies-for-google-http-functions-since-all-new-gcloud-http-functions-after-nov-1-2019-will-default-private/8686

**Comment by pmuens** [comment]
Thanks for opening this @therefromhere :+1:

Could you re-open this issue in the Google Cloud provider plugin repository (can also be found under the `serverless` GitHub org). Thanks!
