### ISSUE TITLE
Tenant not found when running serverless command

### ISSUE THREAD

**Issue by stefanminch** [serverless/serverless#6541]
# This is a Bug Report

## Description

- What went wrong?
I received the following while running serverless command
 Error --------------------------------------------------

  {"errorMessage":"Tenant not found. - Please contact support and provide this identifier to reference this issue - XTT8RLTDMCLC"}

- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by dschep** [comment]
Can you share your `serverless.yml` and what email/github you signed up for dashboard.serverless.com with?

**Comment by stefanminch** [comment]
> Can you share your `serverless.yml` and what email/github you signed up for dashboard.serverless.com with?

There you are:
service: planning-module-backend
app: planning-module-backend
org: South Gate Tech

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

functions:
  registeredOnly:
    handler: handler.hiUsers
    events:
      - http:
          path: /hiUsers
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - arn:aws:cognito-idp:eu-west-1:976388261287:userpool/eu-west-1_OCydMUsdl

**Comment by RutujaWanjari** [comment]
Hello Team,

I am facing exact same issue while executing this ->
 `sls invoke local -f <function_name>`

**Comment by RutujaWanjari** [comment]
Now it started showing same error for -

`sls --help`  and `serverless --help`

![sls_help](https://user-images.githubusercontent.com/19467081/63034980-ee7e2000-bed7-11e9-9aad-0b034a44c2bf.png)

**Comment by stefanminch** [comment]
Found the problem.

It is wrong org in the serverless.yml, this should match the ortanisation set in your serverless.com account.

**Comment by rfinner** [comment]
I saw a "bug" like this myself. I had to set the org: value in serverless.yml to the name of the profile this project was using and then it worked.

**Comment by CJohnsonLehi** [comment]
Get a better error message.

**Comment by Mikejackson-code** [comment]
org: isn't required, you can also just delete it.

**Comment by yuklia** [comment]
> Found the problem.
> 
> It is wrong org parameter in serverless.yml, this should match the ortanisation set in your serverless.com account.
> 
> ![image](https://user-images.githubusercontent.com/19931102/63043037-018ef100-bed4-11e9-8131-73b7f198a5c4.png)

Thanks! You saved my time =)
