### ISSUE TITLE
1.50.0 custom resource bug

### ISSUE THREAD

**Issue by ihorfito** [serverless/serverless#6544]
# This is a Bug Report

## Description

After deploying severless application with multiple s3 events on existing bucket, serverless application creates additional function `my-project-custom-resource-existing-s3`
And serverless deploys folder `custom-resources` to AWS

I don't have `custom-resources` in my project, it is part of serverless.

## Additional Data
node10.x

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by medikoo** [comment]
@ihorfito this is intentional, as CloudFormation doesn't support attachments to existing buckets, so it's solved via custom resources, which require deployment of extra lambda function

**Comment by ihorfito** [comment]
@medikoo okay

**Comment by benhoyt** [comment]
@medikoo I'm running into this too. Can you please provide a few more details: what does this extra lambda function actually do, and why is it needed?

**Comment by medikoo** [comment]
> what does this extra lambda function actually do

Lambda serves a custom resource configured within a CloudFormation template (custom resources are naturally backed by lambdas, it's where its logic sits)

> and why is it needed

It's because CloudFormation on its own doesn't support attachment to existing S3 bucket, therefore we solve it via custom resource configuration

**Comment by benhoyt** [comment]
@medikoo Thanks for the response. Unfortunately that doesn't help me much. What is this custom resource for, and what is it getting created automatically by Serverless? After reading some [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html), it seems custom resources are for creating/updating/deleting resources that are not supported in Cloudformation. My serverless.yml doesn't have any such resources (it doesn't even have any `resources` section at all -- it's just code which executes against an existing S3 bucket).

Can you send a bit more info about what these custom resources are for, and why a Serverless project needs them even when we don't have any resources, let alone custom ones?

I've tried to dig into the source code of the custom resource function, but it's a bit opaque to me: looks like it's adding S3 bucket events, and adding/removing certain Lambda permissions.

**Comment by medikoo** [comment]
> My serverless.yml doesn't have any such resources (it doesn't even have any resources section at all 

`resources` section is for manually configured resources by users.

Custom resources are added by framework, when you configure your serverless.yml with settings that imply features that can only be achieved in CloudFormation via custom resources (e.g. attaching lambdas to existing S3 buckets).

**Comment by benhoyt** [comment]
That's helpful, thank you!

**Comment by ofercaspi** [comment]
But shouldn't that lambda be removed once the deployment is done (for me it isn't)?

**Comment by medikoo** [comment]
@ofercaspi custom resource lambda is part of a service, it's invoked whenever there's an update to resource in question, or when stack is removed (then of course it'll be also removed)

**Comment by ofercaspi** [comment]
@medikoo thanks, I appreciate your quick reply.

The reason I'm asking is that I'm hitting the resource limit of the stack, mostly because I get a custom resource lambda for each function that triggers from an existing bucket.
Together with it's own role it incurres 2 additional resources for each such triggered function.

I'd imagine that one such lambda can be used to manage all of those functions.
Does that make sense?

**Comment by medikoo** [comment]
> The reason I'm asking is that I'm hitting the resource limit of the stack, mostly because I get a custom resource lambda for each function that triggers from an existing bucket.

That's indeed bad. There's an improvement planned, to have just one lambda handling all custom resources. See https://github.com/serverless/serverless/issues/6598

We also may consider to have one custom resource handling all existing bucket cases
