### ISSUE TITLE
FunctionDeploy: If 1 Lambda Fails, Throw Error

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#655]
Throw error even if any lambda function fails during `sls function deploy`.  This is necessary for CI systems to know when something has gone wrong.

**Comment by thedevkit** [comment]
Can we make this optional, at least until project variables are supported in `customRole` of `s-function.json`?

**Comment by eahefnawy** [comment]
@thedevkit I don't think this will really affect your workflow much, you'll still be able to successfully deploy the other lambdas, but the difference is at the end of the code execution we'll throw an error to send a signal to CI tools that something went wrong.
