### ISSUE TITLE
Uploading large app on slow connection times out

### ISSUE THREAD

**Issue by unapologetic1** [serverless/serverless#6551]
Sometimes I need to upload an app via a mobile connection.  It almost always times out, sometimes with a different error message.

It's always either:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service app.zip file to S3 (188.08 MB)...
Serverless: Recoverable error occurred (Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.), sleeping for 5 seconds. Try 1 of 4
```

Or:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service app.zip file to S3 (188.08 MB)...
Serverless: Recoverable error occurred (write ECONNRESET), sleeping for 5 seconds. Try 1 of 4
```

I've tried increasing the `AWS_CLIENT_TIMEOUT` env var but that doesn't seem to help.

It says "Try 1 of 4" but never actually retries.  Is there any way to resume the upload so that it can be completed when this happens?

**Comment by unapologetic1** [comment]
This is an extremely flawed way to update applications.  Why do we need to upload a zip every time we update an app?  Why isn't it git, or even simply plain files?  Is it a limitation by Amazon?

**Comment by unapologetic1** [comment]
Is there a way to redeploy without packaging step if I know no changes have been made?

**Comment by unapologetic1** [comment]
Another related question: Is there a way to redeploy without packaging and reuploading?  E.g., if there's an IAM permissions issue that prevents `sls` from completing the deployment, I need to add the policy and then redeploy, which takes an hour and a half.

**Comment by unapologetic1** [comment]
Wow this is ridiculous.  Why is this a thing?

```
An error occurred: OrderDashreadLambdaFunction - Unzipped size must be smaller than 262144000 bytes
```

**Comment by unapologetic1** [comment]
Okay I just saw that both `.dynamodb` (local dev instance) and `node_modules` were included in the package.  I can sort of understand `node_modules` being included by default... but the local `.dynamodb` instance?  That should probably excluded by default.

In any case, I reduced the package size by from 180 MB to 50 MB by adding this to `serverless.yml`:
```yml
package:
  exclude:
    - .dynamodb/**
    - node_modules/**
```

So that's progress, I guess...

**Comment by unapologetic1** [comment]
This is so unbelievably bad... wow.

After yet another long upload, I receive yet another error:
```
  Serverless Error ---------------------------------------

  An error occurred: UserIndexPhoneTable - app-dev-user--index--phone already exists.
```

Do I need to go into AWS console and manually remove each table?  Or should I just remove everything via `sls remove`, which doesn't always work because the stack status is sometimes stuck on `UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS` for hours - and in which case, I just rename the service to something else?

How can anyone possibly think this is an acceptable development + deployment process?

**Comment by unapologetic1** [comment]
K apparently `sls remove` doesn't remove the tables, so it looks like I will in fact need to remove the alllllll of the tables manually.

**Comment by unapologetic1** [comment]
I have no idea what changed, but after another deployment, my package is suddenly just 3.9 MB, which seems about right and obviously wayyy better.  Hopefully the update was actually successful...

**Comment by unapologetic1** [comment]
AWS and serverless is configuration hell.  This is some of the worst shit I've ever seen.  I've never wasted so much time and energy trying to figure out how to do the simplest of things.  Everyone at Amazon should be fired for going full retard with this bullshit.

I highly recommend to anyone else going down this infinite rabbit hole of retardation to cut your losses now and never even give it a second thought.  You'll thank me later.

I'm done.  Good riddance.

**Comment by mlg87** [comment]
_unapologetic_ is right
