### ISSUE TITLE
Failing to Create a Trigger in aws Lambda using Cloud Formation

### ISSUE THREAD

**Issue by bvijay57** [serverless/serverless#6552]
I Have created a serverless lambda function using cloud formation scripts which includes events for trigger. The script is executing fine without any issues and the Lambda function creating but the trigger is not creating. Find the script below. Kindly help me to fix the issue.

AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
TestBucket:
Type: AWS::S3::Bucket
TestLambdaFunction:
Type: AWS::Serverless::Function
Properties:
CodeUri: 's3://lambdabucket/lambdafunction.zip'
Handler: lambda_function.lambda_handler
Runtime: python3.7
Policies:
- CloudWatchLogsFullAccess
- AmazonEC2ContainerServiceforEC2Role
- AmazonSSMFullAccess
- AmazonS3FullAccess
- AWSStepFunctionsFullAccess
- AWSLambdaBasicExecutionRole
Events:
S3bucketEvent:
Type: S3
Properties:
Bucket:
Ref: TestBucket
Events:
- 's3:ObjectCreated:*'
Filter:
S3Key:
Rules:
- Name: suffix
Value: .txt1

**Comment by exoego** [comment]
> I Have created a serverless lambda function using cloud formation scripts which includes events for trigger.

Closing since this sounds not an issue to `serverless framwork` but general question to AWS.
You may ask and get help in https://forums.aws.amazon.com/
Feel free to reopen if this issue is about sreverless framework and more context is added.
