### ISSUE TITLE
v1.48.1 triggers Bluebird promise warning when NODE_ENV=development

### ISSUE THREAD

**Issue by nathanchapman** [serverless/serverless#6555]
# This is a Bug Report

## Description

- What went wrong?

Upgrading to `serverless@1.48.1` results in a Bluebird warning `a promise was created in a handler but was not returned from it`

- What did you expect should have happened?

No warning written to the console 😄 

- What was the config you used?

`NODE_ENV=development` triggers these warnings to be written to the console by Bluebird. I was also running locally with `serverless-offline`.

- What stacktrace or error message from your provider did you see?

```
(node:5687) Warning: a promise was created in a handler at domain.js:126:23 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/<redacted>/node_modules/bluebird/js/release/method.js:30:9)
```

Similar or dependent issues:

- No directly related issues

## Additional Data

- **_Serverless Framework Version you're using_**: `v1.48.1` and above
- **_Operating System_**: macOS Mojave 10.14.5
- **_Stack Trace_**: Shown above
- **_Provider Error messages_**:

**Comment by nathanchapman** [comment]
Okay, after looking at [the warning from Bluebird](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) and taking a look at `bluebird/js/release/method.js:30:9` from the stacktrace, I was able to track this down to this function released in v1.48.1: https://github.com/serverless/serverless/pull/6410/files#diff-c6a9b60de5c074445c02ce6523318a45R83

Setting `"trackingDisabled": true,` in `~/.serverlessrc` (documented [here](https://serverless.com/framework/docs/providers/aws/cli-reference/slstats#disable-statistics-and-usage-tracking)) did the trick to remove the warning, but isn't really a viable approach.

**Comment by fgheorghe** [comment]
Interesting about tracking, and it being enabled by default - certainly this violates a user's privacy? I suddenly discovered this was enabled, thanks to this error - at no stage during the install process was i notified about it.

**Comment by medikoo** [comment]
> Interesting about tracking

Current naming is unfortunate, it's actually purely about usage statistics (how many installs, deployments we have in general), and not about who does what and where.

We will update this, so it's not confusing

**Comment by fgheorghe** [comment]
Thank you for the clarification. Most open source products will ask for consent even for sending such stats. I would be happy to send them personally, but my client feels a bit alarmed about these being collected without prior consent. Ubuntu for instance asks for a confirmation even for their popularity contest. I understand this provides with valuable intel, but a package that collects even stats without an agreement beforehand is worrying.
