### ISSUE TITLE
Support custom role setting for custom resources

### ISSUE THREAD

**Issue by gordianberger** [serverless/serverless#6595]
# This is a Bug Report

## Description

- What went wrong?

We use our own role which is specified at the provider level. This role is used for every lambda. Since we added the Eventbridge event to a Lambda it fails to try to create a custom role (which it should not do since we use our predefined one).

I looked at the generated Cloudformation JSON and noticed that it is trying to create a Lambda using the handler (eventBridge/handler.handler) from custom resources. Additionally, it is creating a new role for this lambda called "IamRoleCustomResourcesLambdaExecution". For every other Lambda, it is using our predefined Role so I think this is wrong.

- What did you expect should have happened?

Custom-resources lambda should use the default role we specified. 

- What was the config you used?

```

provider:
  role: our ARN
​
functions:
​
  # Log from event bus
  LogEvent:
    handler: lambda.handler
    events:
      - eventBridge:
          eventBus: custom-saas-events
          pattern:
            source:
              - saas.external

```

- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: Framework Core: 1.50.0
- **_Operating System_**: windows
- **_Stack Trace_**: 
- **_Provider Error messages_**:

**Comment by medikoo** [comment]
@gordianberger thanks for that report.

> Since we added the Eventbridge event to a Lambda it fails to try to create a custom role (which it should not do since we use our predefined one).

Why exactly it fails? Relying on custom resources is expected to work seamlessly with custom role setting

> Custom-resources lambda should use the default role we specified.

Custom resource lambdas have very specific permission requirements, and those are in most cases very different from ones needed by service lambdas. I think it wouldn't be nice if we would automatically assume that same role should be used for those and regular lambdas.

Still I think a worthwhile improvement would be to support a `customResourceRole` setting, through which you may state that existing, externally maintained, role should be used. Having that you may assign same ARN here as to `role` setting.

What do you think?

**Comment by gordianberger** [comment]
@medikoo Thanks for the quick response.

Agreed. I understand a little bit more about custom resources now, so I also think that it is a better practice to have two roles.

Also, a small setup still can share the role so I like this approach.

**Comment by olafur-palsson** [comment]
Hello, I'm interested in solving this issue, can anyone point me in the right direction?

**Comment by medikoo** [comment]
@olafur-palsson here's a place where we create a dedicated role internally: https://github.com/serverless/serverless/blob/91ae8bcc17d3ab7874507c8192375b4a28627592/lib/plugins/aws/customResources/index.js#L86

Still, allowing to provide custom role for that, is a bit controversial, as what polices are required may vary across versions (even minor updates), while role as provided by user will have to unconditionally support all of them for successful stack deployment

Do you have a valid use case for that?

**Comment by hanikesn** [comment]
See https://github.com/serverless/serverless/issues/6492#issuecomment-533476635

>This is a real issue in enterprise enviroments where role creation might be restricted. E.g. by requiring a naming convention, permission boundary or just completely for developers.

Allowing a custom role here would let people work around that issue. Even it that requires a bit more effort.

**Comment by hanikesn** [comment]
```
resources:
    IamRoleCustomResourcesLambdaExecution:
      RoleName: name
      PermissionsBoundary: name
```
So naming convetions and permissions boundaries can be overridden in the generated template, which works as a workaround for us.

**Comment by medikoo** [comment]
> So naming convetions and permissions boundaries can be overridden in the generated template, which works as a workaround for us.

Yes, it can be sorted that way

**Comment by aster-anto** [comment]
> ```
> resources:
>     IamRoleCustomResourcesLambdaExecution:
>       RoleName: name
>       PermissionsBoundary: name
> ```
> 
> So naming convetions and permissions boundaries can be overridden in the generated template, which works as a workaround for us.

@hanikesn Could you please point me to a full example? Thanks

**Comment by kinan-ellevation** [comment]
> ```
> resources:
>     IamRoleCustomResourcesLambdaExecution:
>       RoleName: name
>       PermissionsBoundary: name
> ```
> 
> So naming convetions and permissions boundaries can be overridden in the generated template, which works as a workaround for us.

I am unable to get this workaround to work with the latest serverless version. Has anybody found a solution for this?

**Comment by medikoo** [comment]
> I am unable to get this workaround to work with the latest serverless version

It definitely should work, assuming custom resources and `IamRoleCustomResourcesLambdaExecution` resource is generated for you by the Framework

**Comment by kis25791** [comment]
@medikoo @hanikesn I am facing this issue when defining an Event Rules of EventBridge, it keeps to create a new Role (my deployment account doesn't have enough permission to create new Role).
Could you guys plz provide a full example of your workaround? 
Thanks in advance and stay safe.

**Comment by jmb12686** [comment]
@medikoo @pmuens 
What is the status of this issue?  It says it's closed, but I can find no documentation detailing how to set the role ARN to an existing IAM Role for use by the custom resources Lambda (IamRoleCustomResourcesLambdaExecution).  I am operating in a high compliance environment where I am unable to create IAM roles in the same context as AWS infrastructure.  Therefore, I have pre-created my function and CustomResources IAM roles, and I need to specify somewhere in the serverless.yml to *use* the pre-defined role ARNs.  This exists on a per function bases, by specifying `role` under each function, but where can we do it for the framework created Custom Resource frunction?

Thanks.

**Comment by medikoo** [comment]
> but I can find no documentation detailing how to set the role ARN to an existing IAM Role for use by the custom resources Lambda 

@jmb12686 it's `provider.cfnRole` setting (role with which deployment of a stack should be handled). Still I agree documentation could be more informative on that (PR's welcome

**Comment by jmb12686** [comment]
@medikoo Thanks for the clarification.  I did notice that in the code as well, `provider.cfnRole` is being leveraged as the execution role for the Custom Resource Lambda.  

I am operating in a managed high security compliance boundary in AWS, and unfortunately this makes Serverless Framework incompatible for our environment when Custom Resources are required.   This is due to IAM role segmentation and dedication.  Effectively, I am forced to utilize 3 separate roles:
* Dedicated role for the application Lambda to assume
* Dedicated role for any Custom Resource lambda to assume
* Dedicated role for executing serverless deploy (aws cloudformation deploy....)

Since I am able to create these roles (manually) outside of Serverless, I would be able to leverage the framework if the ability existed to plug these 3 distinct roles into the `serverless.yml`.  However, allowing another attribute in the yml configuration for the Custom Resources IAM role is quite a leaky abstration.  Since this probably only affects a few unfortunately people such as myself, and requires a lot of hand crafting Lambda roles that the framework should be responsible for, it's probably not worth muddying up the framework configuration...

**Comment by medikoo** [comment]
@jmb12686 Technically it's about 2 roles, as in Serverless framework we use same role for _executing serverless deploy_ and _invoking Custom Resource lambdas_.
And that role can be customized via `provider.cfnRole` setting.

Reason for that is that we use custom resources purely to workaround a CloudFormation limitations. So any updates that are made in custom resources, would normally go via CloudFormation template deployments (if that would be possible).

**Comment by a3linux** [comment]
@medikoo 
So I have a quick question here according to what I tried those two days.
In my case, we have a dedicated cfnRole which only have CloudFormation permissions. 
And by default this role is assigned to the CustomDashresourceDashexistingDashs3LambdaFunction 
lambda, which caused CloudFormation errors when creating this custom lambda 
as 
"The role defined for the function cannot be assumed by Lambda. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException"

I tried to create a new IAM Role with the name, 
IamRoleCustomResourcesLambdaExecution
in resources section, which will have assumeRole of lambda. 
But in the cloud formation template generated, it still uses the cfnRole for the CustomDashresourceDashexistingDashs3LambdaFunction

Could I know that the IamRoleCustomResourcesLambdaExecution should override the cfnRole also, or it is dedicated for customResources lambda in such case?

**Comment by medikoo** [comment]
> which caused CloudFormation errors when creating this custom lambda

You need to ensure that role you provide with `cfnRole` setting has "lambda.amazonaws.com"  listed as one of the trusted principal services. Having that, all will work without issues

**Comment by a3linux** [comment]
The problem here, I can NOT change that role as enterprise security settings.
The Role is dedicated for CF usage. 
In such case, could I have split cfnRole and customResources one at this time?

**Comment by medikoo** [comment]
@a3linux if indeed there's a scenario where one role cannot be used for both, we're definitely open to support another setting dedicated for custom resources (I would probably name it `cfnCustomResourcesRole`.

PR's welcome

**Comment by a3linux** [comment]
@medikoo In my case as I studied those two days, this might be the case.
We can NOT create CF role or change it as it is managed by admin team because of security issue, that's the one can ONLY be used as cfnRole in serverless then. 
No-one has such situation before?

**Comment by jmb12686** [comment]
> @a3linux if indeed there's a scenario where one role cannot be used for both, we're definitely open to support another setting dedicated for custom resources (I would probably name it `cfnCustomResourcesRole`.
> 
> PR's welcome

@medikoo 
I am in this same situation.  Effectively I am forced to utilize a different role for the Custom Resource vs the role utilized to deploy the CF stack.  For the latest project I was on, I had to quickly pivot and utilize CDK instead for this reason.  

If you look at my prior comment, I am in a heavily regulated environment with specific guard rails and I wasn't sure if customizing the cloudformation custom resource role was fitting for a higher abstraction framework like Serverless.  It's quite a leaky abstraction.  However, if I have the time this week I may submit a PR to tackle this concern.

**Comment by medikoo** [comment]
@a3linux @jmb12686 Thanks for input! We're definitely open for a PR that introduces  `cfnCustomResourcesRole` setting which would help in addressing your case

**Comment by a3linux** [comment]
When we can test the cfnCustomResourcesRole PR? I am willing to help to test it.

**Comment by medikoo** [comment]
@a3linux First we need a contributor that will help preparing an implementation.

Is anyone up for that?

**Comment by vdanniel** [comment]
Best way so far found is the upgrade to the latest version of SLS. 1.72 (tested)

Use extensions something like the below. Extensions are used to override the stack CF resources, Just get the name of the resource right and you are all good .

resources:
  extensions:
    IamRoleCustomResourcesLambdaExecution:
      Properties:
        PermissionsBoundary: !Sub arn:aws:iam::#{AWS::AccountId}:policy/{name_of_ur_policy}

**Comment by mt-kelvintaywl** [comment]
hi @medikoo, sorry to ping you directly but has there been any progress on this issue?

**Comment by medikoo** [comment]
@mt-kelvintaywl there's no, but we're open for PR. Also it'll be great to have a different issue report for it (note that we're commenting on related but slightly different issue that was addressed long time ago)
