### ISSUE TITLE
Deploy application resources to provisioned AWS services

### ISSUE THREAD

**Issue by eggyal** [serverless/serverless#662]
From my reading of the documentation, [`serverless resources deploy`](http://docs.serverless.com/docs/resources-deploy) generates template(s) that are then deployed to CloudFormation.

However, whilst CloudFormation will then provision and configure the desired AWS resources, it will not deploy any application assets to them.  In particular, our app depends upon a number of (static) assets that must be **publicly**-accessible over HTTP/S—and we need to upload them into an S3 bucket _as part of our deployment workflow_.

1. Is there some best practice, or recommended approach, to this problem?  Traditional deployment/configuration management tools like Chef, Puppet and Ansible seem like tremendous overkill for applications based on a Serverless architecture (and, notionally at least, are attempting to solve similar problems to Serverless itself—managing/provisioning/configuring resources and deploying one's application code).

2. Is there any intention of adding such asset deployment functionality into Serverless itself (and thereby avoid supplementing Serverless with some other tool/plugin, which only increases the number of moving parts involved in deployment)?  After all, Serverless already uploads/maintains its own Project Bucket in S3.

3. Or have I massively overlooked/misunderstood something fundamental and what I'm after is already provided by Serverless or massively out-of-scope for the project?

**Comment by pmuens** [comment]
Do you mean static assets such as the frontend?
Behause this might not be stored directly in the serverless bucket (as this bucket contains sensitive information).

Here are some other discussions about this topic:
https://github.com/serverless/serverless/issues/461
https://github.com/serverless/serverless/issues/15

**Comment by eggyal** [comment]
Yes, I did mean frontend assets—looks very much like this is a dupe of #461 (sorry, my search-fu is clearly getting rusty).  I'll close this issue in favour of that one.
