### ISSUE TITLE
Updating Google Cloud Functions support

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [serverless/serverless#6627]
# This is a Feature Proposal

## Description

It appears Serverless is using the legacy Google Cloud Functions event triggers. For example, in this GCP documentation page  https://cloud.google.com/functions/docs/calling/pubsub#functions-deploy-command-node8, it states `providers/cloud.pubsub/eventTypes/topic.publish` is a legacy trigger and they use recommend using trigger topic.

Will Serverless add support for trigger topics?

**Comment by pmuens** [comment]
Hey @miguel-a-calles-mba thanks for opening! :+1:

This seems to be related to the Serverless Google Cloud Functions provider plugin. Could you re-open the issue in that repository?

Thanks in advance!

**Comment by miguel-a-calles-mba** [comment]
Sounds good. I created the issue in that repository. Thanks.
