### ISSUE TITLE
Error pushing data to Api-Gateway with Websockets

### ISSUE THREAD

**Issue by gravitycode** [serverless/serverless#6629]
Error pushing data to Api-Gateway with Websockets

## Description

Im having an error with Serverless Websocket when i send it data to subscribers with postToConnection. This problem only occurs in Linux, not in MacOS.

AWS_API_GATEWAY_ENDPOINT::  http://locahost:4001

My fragment of the serverless.yml where i configure the ports:
```
  serverless-offline:
    port: 4000
    websocketPort: 4001
```

##Logs

Serverless: POST /2015-03-31/functions/ws-server-dev-defaultHandler/invocations (λ: defaultHandler)
wsHandler :: Action received: SEND
SENDING MESSAGE TO :: connectionId: ck050jth4000fstw50uov81te

 Credentials Error --------------------------------------

 Error: connect EHOSTUNREACH 169.254.169.254:80
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

 Your Environment Information ---------------------------
    Operating System:          linux
    Node Version:              10.15.3
    Framework Version:         1.51.0
    Plugin Version:            1.3.10
    SDK Version:               2.1.0

¿Why this ip 169.254.169.254:80? I dont understand that. 
And what does the trace 'Credentials Error' mean? 

Thanks

**Comment by pmuens** [comment]
Hey @gravitycode thanks for opening :+1:

This seems to be related to the `serverless-offline` plugin. Can you open up the issue in their repo? Thanks!

**Comment by gravitycode** [comment]
Ah, ok :) thank you!
