### ISSUE TITLE
 Read-only file system error while trying to download file in directory using serverless

### ISSUE THREAD

**Issue by mithunph** [serverless/serverless#6644]
Hi, 
 I get Read-only file system error while trying to download file in directory using serverless framework.It works fine in local but getting error after deployment

Below is the code snippet:
Realm.open({schema: [schema1, schema2], path: './offline' + '/' + 'filename.realm', schemaVersion: 1})
        .then(realm => {
            realm.write(() => {
                console.log('completed 2nd file==');
            });
            realm.close();
        })
        .catch(error => {
        console.log(error);
        });
}

**Comment by pmuens** [comment]
Hey @mithunph thanks for opening :+1:

Are you writing and reading files within your Lambdas? There's a volume attached to each Lambda but it's not guaranteed that this volume will stick around. Every Lambda should be written in a stateless way. State should be persistet on e.g. DynamoDB.

**Comment by mithunph** [comment]
Hi @pmuens,
Yes, I am using Lambda function . How to write it in stateless way?

**Comment by pmuens** [comment]
Hey @mithunph this is a very helpful article which should shed some more lights into your issues --> https://medium.com/@tjholowaychuk/dos-and-don-ts-of-aws-lambda-7dfcab7ad115
