### ISSUE TITLE
posix_fallocate() failed: Operation not permitted while opening .realm file

### ISSUE THREAD

**Issue by mithunph** [serverless/serverless#6647]
I get the below error when i try to open and download .realm file in /tmp directory of serverless framework. 
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: posix_fallocate() failed: Operation not permitted" }

Below is the code:
let realm = new Realm({path: '/tmp/custom.realm', schema: [schema1, schema2]});
realm.write(() => {
                console.log('completed==');
            });

**Comment by medikoo** [comment]
Closing, as we miss necessary details.

@mithunph if you still observe it please open a new bug report, answering all template questions carefully
