### ISSUE TITLE
_meta/_tmp directory not cleaned up after function deploy

### ISSUE THREAD

**Issue by jeremydaly** [serverless/serverless#665]
When you publish a function using `dash deploy` in v0.4.2 the `_meta/_tmp` directory does not get cleaned up. I am running the latest version of the optimizer plugin, so I don't if that has anything to do with it.

**Comment by eahefnawy** [comment]
Thanks for reporting. This has been fixed in the `v0.5` branch, but not yet merged/released ... we'll probably release v0.5 this weekend :blush:

**Comment by ac360** [comment]
Fixed in v0.5
