### ISSUE TITLE
Use fixed versions in package.json dependencies.

### ISSUE THREAD

**Issue by jakobnordztrom** [serverless/serverless#6666]
# This is a Feature Proposal

## Description

- Most dependencies in package.json allow for minor version updates, ie are prefixed with ^.  This allows bugs in new releases of dependencies to break existing serverless releases (e.g what happened in issues #6659).   To ensure a stable and immutable release do not allow for version updates in package.json. Use fixed versions instead.

Similar or dependent issues:

- #6659

**Comment by medikoo** [comment]
@jakobnordztrom Great thanks for proposal, still I don't think it's a path we we should follow.

It's a project installed usually as one of dependencies and applying this practice may imply a numerous nasty side effects to projects that rely on it. Also we need to be able to update framework dependencies without a need of producing framework releases for every such case.

A fine grain control of a dependencies versioning should rather be done on a project level instead, and over there you can easily control that with `package-lock.json` or `yarn.lock`.

--- 
#6659 was fixed on `aws-sdk` side, also with today's release we've ensured that buggy version will not install with a new version of the framework.
