### ISSUE TITLE
A default API Gateway endpoint is created when s-function.js is missing "endpoint" variable

### ISSUE THREAD

**Issue by JeremyFrederick** [serverless/serverless#667]
In a function, if the user removes the "endpoints" variable completely from s-function.json, a default API Gateway endpoint is still created.

Repro Steps:
1) Remove "endpoints" from the s-function.json file in any function
2) Run `serverless dash deploy`

Bug:
Notice that the function stills shows in the deployment as a GET request

Expected Results:
The function should not be deployed

Workaround:
If the user leaves "endpoints" in the s-function.json file, but defines it as [], they will get the expected behavior where the function is not deployed.

**Comment by ac360** [comment]
Good catch @JeremyFrederick. Thank you.

**Comment by eahefnawy** [comment]
Thanks for reporting @JeremyFrederick ... This has been fixed in v0.5 ... Closing...
