### ISSUE TITLE
AWS Events - Cognito User Pool Trigger for deleting a user

### ISSUE THREAD

**Issue by glitch100** [serverless/serverless#6695]
# New Cognito User Pool Trigger - Deleting a User

## Description
We have a scenario where we would remove a user from the User Pool, and as such would like to trigger something so we can delete associated data stored against that user. 

I think the current triggers cover a lot of use cases just not this one and it would be a great addition.

Is there any particular reason this doesn't exist, or perhaps a way to leverage the existing features?

**Comment by glitch100** [comment]
I am a dummy.

**Comment by Ciul** [comment]
Is there a Cognito trigger for this?
Would be useful to send a confirmation email to the user to let they know the account has been successfully deleted.
