### ISSUE TITLE
zipService does not set executable flag correctly for golang binaries on Win32

### ISSUE THREAD

**Issue by noreabu** [serverless/serverless#6704]
# This is a Bug Report

## Description

- What went wrong?
The zipService on win32 does not correctly set the executable flag for golang binaries
- What did you expect should have happened?
executable flag is set

## Possible fix

Normalize both maps of files before comparison inside function `zipFiles`

Similar or dependent issues:

- #6482

**Comment by medikoo** [comment]
Looks related (or similar) to https://github.com/serverless/enterprise-plugin/issues/273

**Comment by noreabu** [comment]
fix is in on the way. Just need some minutes :)
