### ISSUE TITLE
Add support for VPC Endpoint associations in AWS.

### ISSUE THREAD

**Issue by HarryCaveMan** [serverless/serverless#6715]
# This is a Feature Proposal

## Description
Amazon API Gateway support [associating your API with an interface VPC endpoint](https://docs.aws.amazon.com/apigateway/latest/developerguide/associate-private-api-with-vpc-endpoint.html). This is supported in cloudformation via `EndpointConfiguration`. Associating your API with the VPCE creates a custom DNS alias which allows you to access your private gateway through the VPCE without the need of a `Host` header, which is necessary in certain situations, particularly if you want to make ajax calls to your private API from a browser.

What would be ideal would be to just have a `vpcEndpointIds` attribute which can be set just like `endpointType`, since both are a part of the `endpointConfiguration`. Here is a cloudformation example:
```json
"endpointConfiguration": {
        "types": [
            "PRIVATE"
        ],
        "vpcEndpointIds": [
            "vpce-0212a4ababd5b8c3e",
            "vpce-0393a628149c867ee"
        ]
    }
```

**Comment by HarryCaveMan** [comment]
## Update
I found today that, though the aws api supports this, it has not yet been brought to cloudformation. I imagine this would happen here before there unless it's with a 3rd party plugin.

**Comment by dininski** [comment]
Any news on this one?

**Comment by mthota15** [comment]
Looking at the CFT docs, looks like the VpcEndpointIds property is supported now. It was added on Nov 21, 2019

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html
