### ISSUE TITLE
AWS Pseudo params + SSM Combination not working

### ISSUE THREAD

**Issue by prr19776** [serverless/serverless#6720]
While using an SSM param and use the pseudo param (serverless-pseudo-parameters plugin ) for the region it doesn't work properly, here is the slim down version of the sls yml, what i want to know is how  does the sls parse the SSM and when the actual vales are replaced. 

We have over 100 repos and unable to run the sls in any new region or different account 

pRegion: ${self:custom.${self:custom.pEnvironment}-region}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: "#{AWS::Region}" ## Orginally this was like region: ${self:custom.pRegion} 

  environment:
    LOG_LEVEL: ${ssm:${self:custom.pOwner}-${opt:stage}-log-level}

**Comment by medikoo** [comment]
Closing, as I believe this is solved with a new variables resolver
