### ISSUE TITLE
Function Deploy fails when the function name is a prefix of another function name

### ISSUE THREAD

**Issue by thedevkit** [serverless/serverless#673]
If you have two functions in the same component and same subdirectory, and one of the function's name is a prefix of the other function's name, deployment of the "prefix" function will fail.

For example, the two functions are:

/Project/nodejscomponent/foo/bar
/Project/nodejscomponent/foo/barbazz

Running `serverless function deploy -s dev -r us-east-1 nodejscomponent/foo/bar` results in the following:

```
Serverless: Failed to deploy the following functions in "dev" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   nodejscomponent/foo/bar: Could not find function for endpoint
```

The error message is curious considering the command used is `serverless function deploy`.

**Comment by kennu** [comment]
Seems like the same problem as I reported in https://github.com/serverless/serverless/issues/631 (had Components called api and apidocs).

**Comment by thedevkit** [comment]
You are correct. Closing as Duplicate of #631
