### ISSUE TITLE
Required options / environment variables

### ISSUE THREAD

**Issue by alexjurkiewicz** [serverless/serverless#6759]
# Feature Proposal

## Description

Often I build stacks that have parameters that must be set. For example:

```yaml
provider:
  name: aws
  env:
    DB_PASSWORD: ${env:DB_PASSWORD}
```

It would be nice to have a way to require this env var to exist and to fail the deploy process if it's not defined. Currently users are shown a warning:

```
A valid option to satisfy the declaration 'env:DB_PASSWORD' could not be found.
```

Syntax ideas:

- `${env:DB_PASSWORD:required}`
- `${env:required:DB_PASSWORD}`
- `${env_required:DB_PASSWORD}` This is a less flexible format but would be completely compatible with current syntax.

It would be good if this solution was general and worked for all variable sources. But the most important (for me) are `env` and `opt`.

**Comment by synap5e** [comment]
+1 This would be useful for me as well

**Comment by medikoo** [comment]
Closing, as it'll crash as expected with a new variables resolver
