### ISSUE TITLE
Expose stage name as a CloudFormation stack parameter

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#6774]
# Feature Proposal

Provide stage name as stack parameter to CloudFormation

## Description

I would like to generate the CloudFormation template for a given deployment by running `sls package` and apply the generated template in each of my stages; test/stage/prod. However the serverless stage (i.e. dev) is currently hard-coded in the generated CloudFormation templates.

Rather than hardcoding the stage name into the template, is it possible to expose it as a stack parameter so the same template can be applied in each environment, with a different stage parameter value?

**Comment by medikoo** [comment]
@JamieCressey thanks for report. It's something we consider to support, but requires a bit more thought.
I'll close it, as we have already other request open, which is about same thing.
Follow https://github.com/serverless/serverless/issues/6568 for the progress on that
