### ISSUE TITLE
Can someone please give a rundown of what "An error occurred while provisioning your stack: ApiGatewayResourcePathvarVar. A sibling ({pathvar}) of this resource already has a variable path part -- only one is allowed." means?

### ISSUE THREAD

**Issue by colemars** [serverless/serverless#6783]
I've encountered this error several times now, and despite being able to work around it, I don't understand what the error is.

**Comment by exoego** [comment]
Please use https://forum.serverless.com, StackOverflow or other forums for Q&A .

**Comment by colemars** [comment]
@exoego just a heads up the template isn't actually displayed if you select the "Don’t see your issue here? Open a regular issue." option. So that comment isn't super helpful.

**Comment by exoego** [comment]
Ah, actually `Please use https://forum.serverless.com, StackOverflow or other forums for Q&A` is in **Bug report** issue template.
Will add a `Q&A` template.
