### ISSUE TITLE
An error occurred: Unzipped size must be smaller than 262144000 bytes 

### ISSUE THREAD

**Issue by khrazy5150** [serverless/serverless#6792]
# Bug Report

## Description
When running sls deploy to deploy my website to AWS, I get an error

What did you do?
Found from the forum that graceful-fs needed to be upgraded. So I did. I also needed to upgrade my version of serverless.

What happened?
It still did not work. Then I found that node_modules needed to be explicitly excluded in Serverless.yml (something I didn't have to do before). Still same error. I finally explicitly included ONLY the functions folder. STILL NOT WORKING.

1. What should've happened?
Project should have been deployed

1. What's the content of your `serverless.yml` file?

service: homepage

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  siteMainDomain: mydomain.com
  siteName: www.${self:custom.siteMainDomain}
  siteDescription: "Homepage for My Domain"
  hostedZoneName: ${self:custom.siteName}
  aliasHostedZoneId: Z3BJ6K6RIION7M    # us-west-2
  aliasDNSName: s3-website-${self:provider.region}.amazonaws.com
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: views
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: app.mydomain.com
    dev: dev-app.mydomain.com
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: ${self:custom.siteMainDomain}
  capacities:
    - table: ${self:provider.environment.TABLE_1}  # DynamoDB Resource
      read:
        minimum: 1        # Minimum read capacity 
        maximum: 1000     # Maximum read capacity 
        usage: 0.75       # Targeted usage percentage 
      write:
        minimum: 1       # Minimum write capacity 
        maximum: 1000      # Maximum write capacity 
        usage: 0.5        # Targeted usage percentage
    - table: ${self:provider.environment.TABLE_2}  # DynamoDB Resource
      read:
        minimum: 1        # Minimum read capacity 
        maximum: 1000     # Maximum read capacity 
        usage: 0.75       # Targeted usage percentage 
      write:
        minimum: 1       # Minimum write capacity 
        maximum: 1000      # Maximum write capacity 
        usage: 0.5        # Targeted usage percentage
    - table: ${self:provider.environment.TABLE_3}  # DynamoDB Resource
      read:
        minimum: 1        # Minimum read capacity 
        maximum: 1000     # Maximum read capacity 
        usage: 0.75       # Targeted usage percentage 
      write:
        minimum: 1       # Minimum write capacity 
        maximum: 1000      # Maximum write capacity 
        usage: 0.5        # Targeted usage percentage
  # websiteBucketOrigin: S3-${self:custom.siteName}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    TABLE_1: ${self:service}-${opt:stage, self:provider.stage}-leads
    TABLE_2: ${self:service}-${opt:stage, self:provider.stage}-landing-page
    TABLE_3: ${self:service}-${opt:stage, self:provider.stage}-site
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_1}"
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_2}"
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_3}"

functions:
  get-elements:
    handler: functions/html/elements.all
    description: GET /elements
    events:
      - http:
          path: elements
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  get-page:
    handler: functions/html/template.handler
    description: GET /page
    events:
      - http:
          path: page
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  create-page:
    handler: functions/html/template.new
    description: POST /page
    events:
      - http:
          path: page
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  create-site:
    handler: functions/builder/save.handler
    description: POST /save
    events:
      - http:
          path: save
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  update-page:
    handler: functions/html/template.change
    description: PATCH /page/{id}
    events:
      - http:
          path: page/{id}
          method: patch
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  get-one-page:
    handler: functions/html/template.handler
    description: GET /page/{id}
    events:
      - http:
          path: page/{id}
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  create-search-ad:
    handler: functions/skag/create.handler
    description: POST /skag
    events:
      - http:
          path: skag
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  render-thankYou:
    handler: functions/html/thankYou.handler
    description: GET /thank-you
    events:
      - http:
          path: thank-you
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  create-lead:
    handler: functions/leads/create.handler
    description: POST /lead
    events:
      - http:
          path: lead
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  update-lead:
    handler: functions/leads/update.handler
    description: PATCH /lead
    events:
      - http:
          path: lead
          method: patch
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  delete-lead:
    handler: functions/leads/delete.handler
    description: DELETE /lead/d/{id}
    events:
      - http:
          path: lead/d/{id}
          method: delete
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  get-one-lead:
    handler: functions/leads/get-one.handler
    description: GET /lead/g/{id}
    events:
      - http:
          path: lead/g/{id}
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  get-many-leads:
    handler: functions/leads/get-many.handler
    description: GET /leads
    events:
      - http:
          path: leads
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

resources:
  Resources:
    LeadsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.TABLE_1}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    pagesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.TABLE_2}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    siteTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.TABLE_3}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

    SiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000
    SiteBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      DependsOn: "SiteBucket"
      Properties:
        Bucket: ${self:custom.siteName}
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                - "arn:aws:s3:::${self:custom.siteName}/*"

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-s3-sync

package:
  include:
    - functions/**
    # - node_modules/**
    # - venv/**

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

ServerlessError: An error occurred: GetDashoneDashpageLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2dfe28bd-9764-4e06-b2f5-e16172c52940).
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:122:33
  From previous event:
      at AwsDeploy.monitorStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:28
  From previous event:
      at AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:8)
  From previous event:
      at AwsDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:35)
  From previous event:
      at AwsDeploy.updateStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:113:33)
  From previous event:
      at AwsDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:505:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:17)
      at AwsDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:505:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:540:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:540:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:115:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:72:30
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqCallback.oncomplete (fs.js:153:20)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:72:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:57:4)
      at Module._compile (internal/modules/cjs/loader.js:759:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
      at Module.load (internal/modules/cjs/loader.js:628:32)
      at Function.Module._load (internal/modules/cjs/loader.js:555:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
      at internal/main/run_main_module.js:17:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.1.0
     Framework Version:         1.53.0
     Plugin Version:            3.1.1
     SDK Version:               2.1.1
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3

Similar or dependent issues:

- #343

**Comment by khrazy5150** [comment]
Similar issue: https://github.com/UnitedIncome/serverless-python-requirements/issues/343

**Comment by medikoo** [comment]
Error indicates that bundled size of `get-one-page` lambda, exceeds 250MB.

Do you know what may cause such lambda size on your side?

**Comment by khrazy5150** [comment]
I deleted that function from the folder. It was not there when I ran it.

**Comment by medikoo** [comment]
>I deleted that function from the folder. It was not there when I ran it.

It is listed in `serveless.yml` you cite, and also error refers to this function directly

**Comment by khrazy5150** [comment]
I commented out EVERY FUNCTION, except the one that serves the homepage. It is definitely less than 250MB but still get the same error for this function.

'use strict';

const AWS = require('aws-sdk');
AWS.config.update({ region: 'us-west-2' });
const db = new AWS.DynamoDB.DocumentClient();
const tableName = process.env.TABLE_1;

const baseUrl = 'mydomain.com';
let html = '';
let name = '';

module.exports.handler = async (event) => {
    if (event.queryStringParameters && event.queryStringParameters.name) {
        name = event.queryStringParameters.name;
    }

    name = name === '' ? 'Great!' : name;
    console.log(name);

    html = `
    <!doctype html>
    <html class="no-js" lang="en">
        <head>
            <base href="${ baseUrl }/" />
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
            
            <title>Attorneys, Roofers, Restaurants, Nightclubs, and more - Junior Bay</title>
            <meta name="description" content="Find small businesses for entertainment, retail, or services near you." />
            
            <link rel="shortcut icon" href="images/icon/favicon.png">
            
            <link rel="stylesheet" href="css/animate.css" />
            
            <link rel="stylesheet" href="css/bootstrap.min.css" />
            
            <link rel="stylesheet" href="css/font-awesome.min.css" />
            
            <link rel="stylesheet" href="css/themify-icons.css" />
            
            <link rel="stylesheet" href="css/owl.transitions.css" />
            <link rel="stylesheet" href="css/owl.carousel.css" /> 
            
            <link rel="stylesheet" href="css/magnific-popup.css" /> 
            
            <link rel="stylesheet" href="css/base.css" /> 
            
            <link rel="stylesheet" href="css/elements.css" />
            
            <link rel="stylesheet" href="css/responsive.css" />
            
            
            <style>
                    th {
                        text-align: right; 
                        padding-right: 10px;
                    }
                    h1 {
                        color: #fff;
                        font-family: Ubuntu;
                        font-size: 55px; 
                        font-weight: 600;
                        line-height: 6rem;
                    }
                    h {
                        color: rgb(255, 131, 9);
                        font-weight: bold;
                    }
            </style>
            
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145379442-1"></script>
            <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-145379442-1');
            </script>

            
            <script type="text/javascript">
                var onloadCallback = function() {
                    widget = grecaptcha.render('reCaptcha-element', {
                        'sitekey' : '6LfrwakUAAAAADInLSLA-sgGQdakpaVmfkCw_rOQ'
                    });
                };
            </script>
        </head>
        <body>
            <div id="page" class="page">
                <section class="bg-white builder-bg border-none hero-style25" id="hero-section25" data-selector=".builder-bg">
                    <div class="container-fluid">
                        <div class="row">
                            
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 no-padding xs-no-padding-15 bg-gray tz-builder-bg-image cover-background one-fifth-screen" data-img-size="(W)1050px X (H)961px" style="padding-top: 0px; padding-bottom: 0px; background-image: url(./images/frontpage/landscape/26.jpg);" data-selector=".tz-builder-bg-image" id="ui-id-24"></div>
                            
                            
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 bg-orange builder-bg one-fifth-screen xs-height-auto display-table xs-text-center" data-selector=".builder-bg" style="padding: 0px 15px; border-color: rgb(112, 112, 112); background-color: rgb(11, 82, 148) !important;" id="ui-id-37">
                                <div class="display-table-cell-vertical-middle padding-twenty-five sm-padding-seven xs-padding-twenty no-padding-tb xs-no-padding-lr">
                                    <h1>Junior <h>Bay</h></h1>
                                    <div class="input-group">
                                        <input autocomplete="off" name="search" id="search" type="text" placeholder="" class="extra-big-input border-none">
                                        <div class="input-group-btn">
                                            <button type="submit" class="contact-submit tz-text btn btn-large propClone bg-white text-white xs-width-100 xs-margin-thirteen-bottom" data-selector=".tz-text"><i class="fa fa-search icon-small no-margin text-orange"></i></button>
                                        </div>
                                    </div>
                                    <div class="title-small xs-title-small display-block text-white text-center">&nbsp;                        
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </section>
                <footer id="footer-section11" class="padding-30px-tb bg-dark-gray builder-bg">
                    <div class="container">
                        <div class="row equalize">
                            
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 xs-text-center xs-margin-four-bottom display-table">
                                <div class="title-small xs-title-small display-block"><a href="#" class="inner-link btn btn-small propClone bg-light-green text-black border-radius-0 font-weight-400 sm-padding-nav-btn sm-display-inline-block">JOIN US</a></div>
                                <div class="title-small xs-title-small display-block"><a href="#" class="inner-link btn btn-small propClone bg-white text-black border-radius-0 font-weight-400 sm-padding-nav-btn sm-display-inline-block">SIGN IN</a></div>
                            </div>
                            
                            
                            <div class="col-md-6 col-sm-6 col-xs-12 text-right xs-text-center display-table">
                                <div class="display-table-cell-vertical-middle">
                                    <div class="text-light-gray tz-text"><a class="text-light-gray" href="http://www.juniorbay.net/privacy-policy/">Privacy Policy</a></div>
                                    <div class="text-light-gray tz-text"><a class="text-light-gray" href="http://www.juniorbay.net/terms-of-service/">Terms of Service</a></div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </footer>
            </div>


            
            <script type="text/javascript" src="js/jquery.min.js"></script>
            <script type="text/javascript" src="js/jquery.appear.js"></script>
            <script type="text/javascript" src="js/smooth-scroll.js"></script>
            <script type="text/javascript" src="js/bootstrap.min.js"></script>
            
            <script type="text/javascript" src="js/wow.min.js"></script>
            
            <script type="text/javascript" src="js/owl.carousel.min.js"></script>        
            
            <script type="text/javascript" src="js/imagesloaded.pkgd.min.js"></script>
            
            <script type="text/javascript" src="js/jquery.isotope.min.js"></script> 
            
            <script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
            
            <script type="text/javascript" src="js/jquery.nav.js"></script>
            
            <script type="text/javascript" src="js/equalize.min.js"></script>
            
            <script type="text/javascript" src="js/jquery.fitvids.js"></script>
            
            <script type="text/javascript" src="js/jquery.countTo.js"></script>
            
            <script type="text/javascript" src="js/counter.js"></script>
            
            <script type="text/javascript" src="js/twitterFetcher_min.js"></script>
            
            <script type="text/javascript" src="js/main.js"></script>
            
            <script type="text/javascript" src="js/formData.js"></script>
            
            <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
            
            <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
        </body>
    </html>
    `;

    const response = {
        statusCode: 200,
        headers: {
            'Content-Type': 'text/html',
            'Access-Control-Allow-Origin': '*'
        },
        body: html
    };

    return response;
}

**Comment by medikoo** [comment]
Closing as it's outdated issue, and more Q&A than bug report
