### ISSUE TITLE
Base Path Mappings of Custom Domain Names are removed

### ISSUE THREAD

**Issue by gleidsonh** [serverless/serverless#6796]
# Bug Report

In my integration tests, when I remove function `- serverless remove --stage staging`, Base Path Mappings of Custom Domain Names are removed too. On next integration test, an error will occur. How can I remove function correctly?

**Serverless version**
```
git:(develop) serverless --version
Framework Core: 1.53.0
Plugin: 3.1.1
SDK: 2.1.1
Components Core: 1.1.1
Components CLI: 1.2.3
```

**Comment by medikoo** [comment]
`serverless remove` removes whole stack deployment, not just function.

For function to be removed, you just need to remove it from your serverless config.

**Comment by api-spinner** [comment]
Thanks for your reply.

I'm doing this on CI/CD. I can't just remove function from serverless.yml. What is the best way to do that?
