### ISSUE TITLE
Serverless Package - Method Not Found

### ISSUE THREAD

**Issue by mtt-g** [serverless/serverless#6797]
# Bug Report

## Description

1. What did you do?

I attempted to perform a `serverless package` as described in the following documentation:

https://serverless.com/framework/docs/providers/aws/cli-reference/package/

2. What happened?

The process failed with the following output:

```
# serverless package

  error:
  Error:   method package not found
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:207:15)
```

3. What should've happened?

According to the documentation the infrastructure should have been packaged into the .serverless directory

4. What's the content of your `serverless.yml` file?

```
serverless-nextjs-demo:
  component: serverless-next.js
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
# SLS_DEBUG=* serverless package

  error:
  Error:   method package not found
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:207:15)
```

**Comment by tharun208** [comment]
I want to work on this!
