### ISSUE TITLE
[Website] 404 Resources

### ISSUE THREAD

**Issue by ChaiBapchya** [serverless/serverless#6800]
# Bug Report
On page - https://serverless.com/framework/docs/providers/aws/guide/resources/
I wish to go to Resources
https://serverless.com/framework/docs/providers/aws/guide/intro.md#resources
returns 404
## Description

1. What did you do? Clicked on resources link
1. What happened? Corresponding link for resources should have opened
1. What should've happened?
1. What's the content of your `serverless.yml` file?
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
Great thanks for report @ChaiBapchya! Issue has been fixed
