### ISSUE TITLE
AddFilterPolicyLambdaFunction is still nodejs6

### ISSUE THREAD

**Issue by RichardOlrichs** [serverless/serverless#6804]
# Bug Report
Lambda no longer supports nodejs6

## Description
Lambda no longer supports nodejs6, but sls package still adds the lambda 'AddFilterPolicyLambdaFunction' in its resources. The resources still define runtime nodejs6.10. 
The deployment now crashes because of the runtime nodejs6. 

1. What did you do?
sls deploy
1. What happened?
Error occured
1. What should've happened?
Deployed
1. What's the content of your `serverless.yml` file?
doesn't matter for this bug. 
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
ServerlessError: An error occurred:
 AddFilterPolicyLambdaFunction 
 - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ).

**Comment by DaphneOlrichs** [comment]
I'm having the same problem, please fix :)

**Comment by medikoo** [comment]
@RichardOlrichs I don't think serverless framework adds such lambda (you can even search the codebase for `nodejs6.10` string, and [you won't find any occurrence](https://github.com/serverless/serverless/search?q=nodejs6.10&unscoped_q=nodejs6.10)).

I guess it's probably added by one of the plugins you use (?)

**Comment by RichardOlrichs** [comment]
Hi @medikoo,

Thanks for your quick reply.
I see the code comes from the serverless-sns-filter plugin. 

I notice the plugin is deprecated, so we will stop using it and the issue will go away :).

Cheers,
Richard
