### ISSUE TITLE
SLS test - TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by ValGeorgiev** [serverless/serverless#6812]
# Bug Report
SLS test - TypeError: Cannot read property 'toUpperCase' of undefined

## Description
I am trying to setup a simple integration test with Serverless Framework. Following this tutorial https://serverless.com/framework/docs/dashboard/testing/

When I execute `sls test` - error is logged 

![image](https://user-images.githubusercontent.com/12056467/66512816-6cc6ff00-eae2-11e9-9614-32127cddb97a.png)

- Summary should be provided with failed/passed test

serverless.yml:
![image](https://user-images.githubusercontent.com/12056467/66513015-df37df00-eae2-11e9-9511-d091b6710ec6.png)

serverless.test.yml:
![image](https://user-images.githubusercontent.com/12056467/66513043-ebbc3780-eae2-11e9-8bea-2fdbb6184230.png)

With `SLS_DEBUG=* serverless test`
![image](https://user-images.githubusercontent.com/12056467/66513161-1d350300-eae3-11e9-86ab-a18718222f50.png)

Similar issues:

https://github.com/serverless/serverless/issues/6384
https://github.com/dherault/serverless-offline/issues/105

**Comment by drexler** [comment]
Looks like you're using enterprise plugin and the failure is from your function name not being found: https://github.com/serverless/enterprise-plugin/blob/master/lib/test/index.js#L53. Hmmm, silly to ask but does your function deploy sucessfully?

**Comment by dschep** [comment]
Ah.. I'll need to add support for the `http: ANY /` short hand. For now update you sls yaml to use the long form:
```yaml
functions:
  hello:
    events:
     - http:
         path: /
         method: ANY
```

**Comment by ValGeorgiev** [comment]
@dschep Thanks for the fast response! It's working :) I will close this issue
