### ISSUE TITLE
Updating function doesn't update changes in serverless.yml

### ISSUE THREAD

**Issue by shubsaini09** [serverless/serverless#6815]
I made some changes in my function's serverless.yml file and I ran
`sls deploy function -f function-name`
but it gave me below output
```
...
Serverless: Code not changed. Skipping deployment.
...
```
then I ran below
`sls deploy function -f function-name`
and got the output as 
```
...
Serverless: Uploading function..
Serverless: Successfully updated function
...
```
When I went and checked my changes, it was not there because I didn't do any code change but made changes in my yml file. 
Question - Is this the default behavior? Is there any alternative?

Solution - `sls deploy` will deploy everything but time-consuming specially if you are working on a big project.

**Comment by medikoo** [comment]
> I made some changes in my function's serverless.yml file

What exactly you've changed?

**Comment by shubsaini09** [comment]
@medikoo I made some changes in package-include/exclude property. Also, I made changes in http event, changed mapping templates for api gateway.

**Comment by neverendingqs** [comment]
@shubsaini09 - are you able to provide example `serverless.yml` files for before and after?

**Comment by medikoo** [comment]
Closing due to lack of details
