### ISSUE TITLE
Serverless Framework Package/Bundle/Distribution?

### ISSUE THREAD

**Issue by Cinderhaze** [serverless/serverless#6819]
# Feature Proposal
A fully bundled, 'All In One' distribution option for the serverless framework

## Description

1. In enterprise environments with restrictive security policies around bringing in software, a single 'All-in-one' style package (like Puppet's [All-In-One](https://beryju.org/en/blog/my-thoughts-about-puppet-4), or Chef's [Omnibus](https://github.com/chef/omnibus) model) allow the software and all of it's dependencies to be bundled together for a single piece of 'software' from a security/process perspective, greatly reducing the amount of process required, in addition to bundling together the known/tested components.  
1. This was recently brought up by[ Corey Quinn](https://twitter.com/QuinnyPig) on [Screaming in the Cloud: Going Serverless with AJ Stuyvenberg](https://www.screaminginthecloud.com/episodes/going-serverless-with-aj-stuyvenberg), and mentioned as a possible future enhancement.  I am writing this feature request to help capture interest.

**Comment by medikoo** [comment]
Thanks @Cinderhaze for interest!

We're actually already covering it here: https://github.com/serverless/serverless/pull/6342 and it should be released soon!

**Comment by Cinderhaze** [comment]
Awesome! My search-fu wasn't strong enough, thanks!
