### ISSUE TITLE
Nicer Display Of All Available Templates

### ISSUE THREAD

**Issue by JimLynchCodes** [serverless/serverless#6821]
Hi, nice meeting everyone at serverlessconf 2019 nyc! wooooo! :)

Anyway, my issue is that I don't have a nice way to see ALL the available serverless templates. Currently, the way I like to view all the templates is just to call "sls create -t" with a non-existent template name: 

<img width="1051" alt="Screen Shot 2019-10-11 at 5 17 40 PM" src="https://user-images.githubusercontent.com/5354163/66686038-22fa2800-ec4c-11e9-90d5-778a9950af25.png">

However, there are may reasons why this output is not ideal:

1. ugly formatting - All these things jammed into one giant block of text is kind of ugly. It would be nice to use some line breaks and possibly different coloring?

2. no descriptions - It would be nice to have a short description describing each template. For example, what's the difference between "aws-go", "aws-go-mod", and "aws-go-dep"? I still don't even really know!

3. Missing templates - it seems that not all serverless templates are present in this list. For example, why isn't the [serverless-rust](https://github.com/softprops/serverless-rust) project listed here?

Anyway, it would be awesome if there was a nice place to see and understand the full list of available templates. Let me know what you all think about these suggestions and if you'd like me to help in making these changes. Thanks!

**Comment by JimTheMan** [comment]
^ actually I meant [serverless-aws-rust](https://github.com/softprops/serverless-aws-rust).

**Comment by medikoo** [comment]
Closing as it was improved a longer while ago
