### ISSUE TITLE
Create resource group for project

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#683]
It would be great when all resources are tagged so that a resource group for each project is available in the AWS console.

http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/what-are-resource-groups.html

**Comment by hauboldj** [comment]
I wish all AWS resources supported tags.

**Comment by flomotlik** [comment]
Going forward we will implement deployment through Cloudformation and custom naming rules for resource deployments so this will be possible. I'm closing this issue now as it is already in the plan.
