### ISSUE TITLE
Security:  npm audit issue for https-proxy-agent dependency

### ISSUE THREAD

**Issue by thetumper** [serverless/serverless#6868]
# Bug Report
When npm audit is run, serverless' latest release has a vulnerability:

High:  Machine-In-The-Middle
Package:  https-proxy-agent
Patched in:  >=3.0.0
Dependency of:  serverless [dev]
Path:  serverless > https-proxy-agent

package.json on master shows:

"https-proxy-agent": "^2.2.2",

Anything preventing upgrading, to resolve this issue?

## Description

1. What did you do?  Ran npm audit
1. What happened?  See above
1. What should've happened?  serverless should use a non-vulnerable version of https-proxy-agent
1. What's the content of your `serverless.yml` file?  N/A
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`) . N/A

Similar or dependent issues:  N/A

**Comment by pmuens** [comment]
Closing this as a duplicate of https://github.com/serverless/serverless/issues/6863.
