### ISSUE TITLE
Error when rate limited by AWS API

### ISSUE THREAD

**Issue by NickCorbett** [serverless/serverless#688]
Sometimes when I run:

serverless endpoints deploy -a -s xxx

I get the following error:

`
ReferenceError: SUtils is not defined
    at /usr/lib/node_modules/serverless/lib/utils/index.js:685:13
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:354:18)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
... etc
`

Looking at the code, it looks like I am being rate-limited by the AWS API; SUtils is being used to record a debug message (in usr/lib/node_modules/serverless/lib/utils/index.js:685).  I'm guessing SUtils hasn't been initialised.

**Comment by ajagnanan** [comment]
+1 Having this issue when i run it on a cloud CI environment, not locally. Is it really rate-limiting?

**Comment by ac360** [comment]
:+1: Thanks will fix this in `v0.5`

**Comment by ac360** [comment]
Actually, this was already fixed in `v0.5`.  Closing now!

**Comment by ajagnanan** [comment]
Thanks!
