### ISSUE TITLE
To capture exception on dashboard i am using serverless_sdk import  capture_exception issue

### ISSUE THREAD

**Issue by ranjan-baral** [serverless/serverless#6885]
to capture exception on dashboard i am using serverless_sdk import but i am getting below error :

cannot import name 'capture_exception' from 'serverless_sdk' (/var/task/serverless_sdk/__init__.py)

Please let me know on this.how can i import capture exception

**Comment by pmuens** [comment]
Hey @ranjan-baral thanks for opening this issue :+1:

You need to call the `capture_exception` function on `context` which is passed-into the Lambda function handler. There's no need to import anything on your end.

You can find an example here: https://github.com/serverless/serverless/blob/master/docs/dashboard/sdk/python.md#capture_exception

**Comment by dschep** [comment]
Should work the way you did it per the docs @pmuens linked. Could you share the output of `sls --version`?

**Comment by ranjan-baral** [comment]
sls  --version is giving below details

Framework Core: 1.55.1
Plugin: 3.2.0
SDK: 2.1.2
Components Core: 1.1.2
Components CLI: 1.4.0


@pmuens still i am getting an error if i do context.capture_exception(exc)..throwing error cature_exception is not available attribute

**Comment by ranjan-baral** [comment]
After updating on serverless framework version, I am able to solve above issue thank you @pmuens and @dschep
