### ISSUE TITLE
Ignore 200 CF resource limit

### ISSUE THREAD

**Issue by celicoo** [serverless/serverless#6887]
Hello,

Would it be possible to ignore the CF resource limit validation? I’ve managed to increase the limit from 200 to 500 resources (through AWS support), but the deploy still fails because it looks like the framework also validates locally the number of resources in a stack.

Thank you.

**Comment by medikoo** [comment]
@celicoo 200 resources per stack is a fixed, not adjustable, limit on AWS grounds (also I don't think framework implies any extra validation on that).

I believe you've increased some other limit (e.g. maximum number of stacks)

**Comment by celicoo** [comment]
@medikoo you're right. Sorry for not replying earlier.
