### ISSUE TITLE
github.com/serverless/serverless/issues

### ISSUE THREAD

**Issue by u3208950** [serverless/serverless#6914]
# Bug Report github.com/serverless/serverless/issues

## Description github.com/serverless/serverless/issues

1. What did you do?
1. What happened?
1. What should've happened?
1. What's the content of your `serverless.yml` file?
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #12345

**Comment by exoego** [comment]
Closing since no information given.
