### ISSUE TITLE
Deploying in parallel is causing an occasional error `no such file or directory, unlink '~/.serverless/tracking-cache/1055c4d0-f995-11e9-707e-210785d36311'

### ISSUE THREAD

**Issue by philiiiiiipp** [serverless/serverless#6917]
# Bug Report

## Description

We are having a monorepo with multiple stacks using their own serverless.yml file. When we deploy we are deploying some of the stacks in parallel and slowly resolve the dependency graph to save time.

We ~5% of the time see deployments failing with:
```
Error --------------------------------------------------
 
  Error: ENOENT: no such file or directory, unlink '/Users/philipp/.serverless/tracking-cache/1255c4d0-f995-11e9-707e-220785d36311'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.0
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

If it helps I could build all the time with `SLS_DEBUG=*` if you think that adds valueable info, but I am thinking that this is probably an issue of the same id being used for all projects ?

I also asked about it on slack and it seems like someone else experiences this as well while deploying parallel stacks `https://serverless-contrib.slack.com/archives/C6ETEFWDT/p1572275913081600`

**Comment by medikoo** [comment]
@philiiiiiipp great thanks for that report. It'll be fixed with https://github.com/serverless/serverless/pull/6920

**Comment by kesavab** [comment]
@philiiiiiipp I am in the same situation as yours. We have a mono repo with multiple serverless files. I am running sls deployments from a make file and calling the make target with -j flag that runs multiple process in parallel. Doing so I am facing error like below.

May I know how are you running your deployments parallelly ?

<html>
<body>


STDERR: find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/aws_lambda_powertools-1.24.0.dist-info': No such file or directory
--
471 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/numpy-1.21.5.dist-info': No such file or directory
472 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/boto3-1.18.65.dist-info': No such file or directory
473 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/wrapt-1.13.3.dist-info': No such file or directory
474 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/idna-3.3.dist-info': No such file or directory
475 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/pytz-2021.3.dist-info': No such file or directory
476 | find: '/root/.cache/serverless-python-requirements/a92be47b63e9e4444f3ed7b447b3a846a5de81273cb952775bb672275a820a07_slspyc/six-1.16.0.dist-info': No such file or directory
477 |  
478 | at /codebuild/output/src472528929/src/node_modules/serverless-python-requirements/lib/pip.js:331:13
479 | at Array.forEach (<anonymous>)
480 | at installRequirements (/codebuild/output/src472528929/src/node_modules/serverless-python-requirements/lib/pip.js:318:28)
481 | at installRequirementsIfNeeded (/codebuild/output/src472528929/src/node_modules/serverless-python-requirements/lib/pip.js:576:3)
482 | at ServerlessPythonRequirements.installAllRequirements (/codebuild/output/src472528929/src/node_modules/serverless-python-requirements/lib/pip.js:655:29)
483 | at ServerlessPythonRequirements.tryCatcher (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/util.js:16:23)
484 | at Promise._settlePromiseFromHandler (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/promise.js:547:31)
485 | at Promise._settlePromise (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/promise.js:604:18)
486 | at Promise._settlePromise0 (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/promise.js:649:10)
487 | at Promise._settlePromises (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/promise.js:729:18)
488 | at _drainQueueStep (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/async.js:93:12)
489 | at _drainQueue (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/async.js:86:9)
490 | at Async._drainQueues (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/async.js:102:5)
491 | at Immediate.Async.drainQueues [as _onImmediate] (/codebuild/output/src472528929/src/node_modules/bluebird/js/release/async.js:15:14)
492 | at processImmediate (internal/timers.js:461:21)


</body>
</html>
