### ISSUE TITLE
Security vulnerability WS-2019-0063 shows up in my project due to json-refs ^2.1.7

### ISSUE THREAD

**Issue by davidwilde** [serverless/serverless#6929]
# Bug Report

## Description

1. What did you do?
Switched on Security alerts in Github for my project
1. What happened?
I received an email from Github advising me about json-refs ^2.1.7. I then investigated and found that this is a dependency of serverless
1. What should've happened?
The advisory should not have been sent to me

1. What's the content of your `serverless.yml` file?
In this case I don't believe that this relevant

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Not relevant

**Comment by sleepwithcoffee** [comment]
hi @medikoo I think we can close this ticket

**Comment by medikoo** [comment]
Indeed, Thanks @sleepwithcoffee for heads up!
