### ISSUE TITLE
pathParameters, queryStrings, etc. should be passed from authorizer to target function by default

### ISSUE THREAD

**Issue by juicetin** [serverless/serverless#6950]
Related to https://github.com/serverless/serverless/pull/4773.

Currently, when using a custom authorizer (either token OR request), *none* of the critical defined parameters for a function, e.g. path parameters and query parameters, are passed to the target function when an authorizer is used, which should happen by default as I can't imagine the intention ever being that they are _not_ passed to the target function.

**Comment by medikoo** [comment]
Closing, as I'm not sure if it's still actual. If it is, please open a new issue providing a simple service example where lambda doesn't receive expected data.
