### ISSUE TITLE
Environment variables not updating in new lambda function version

### ISSUE THREAD

**Issue by poulomighosh08** [serverless/serverless#6956]
# Bug Report

## Description

Environment variables not updating in new lambda function version

1. What did you do?
Modified the environment variable of lambda function from AWS console with incorrect value

2. What happened?
Ran the serverless deployment which had correct values for the environment variables.
The value remains unchanged even if lambda function has published newer version

3. What should've happened?
The modified values in step one should have been replaced with correct values after running serverless deployment for stack.

4. What's the content of your `serverless.yml` file?
startEventLambda:
    name: ${self:service}-start-event-lambda-${opt:stage}
    description: "An event lambda."
    handler: Lambda::Lambda.Event.Lambda::HandleAsync
    role: lambdaEventRole
    events:
      - externalSNS: ${self:resources.Resources.topic.Properties.TopicName}
    environment:
      ENABLED: ${self:custom.lambda.execution.enabled}
      SUBJECT: ${self:custom.lambda.xyz}
    timeout: 120
    memorySize: 256

Similar or dependent issues:
 https://github.com/serverless/serverless/issues/4638

**Comment by medikoo** [comment]
@poulomighosh08 This is hard to address reliably.

Thing is that any updates to lambda created via CloudFormation stack, which are not made through CloudFormation stack update, are not visible to CloudFormation engine.
CloudFormation applies changes on basis of comparision between current and previously deployed stack, and in your case nothing have changed, hence no update.

Best way to address that is to ensure that resources created through CloudFormation stacks are handled purely in context of CloudFormation and not externally.

**Comment by poulomighosh08** [comment]
Agreed. Hence , closing this.
