### ISSUE TITLE
Separating packaging step and template creation step for multi-region deployment

### ISSUE THREAD

**Issue by andrewcyhuang** [serverless/serverless#6958]
# Feature Proposal

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Currently, the serverless deployment process involves repackaging the project every deployment. In workflows which require multi-region deployment, the only differences between the deployments should be configuration (ex: environment configurations / stage) and the actual code should remain the same. If there was a way of separating the package step, and the cloudFormation template creation step, it would allow multi-region deployment workflows to ensure deployment from a single packaged project to avoid problems like mismatched versions.

Similar or dependent issues:

**Comment by medikoo** [comment]
@andrewcyhuang great thanks for request!

We already have opened issue for that: https://github.com/serverless/serverless/issues/6568

It's definitely possible, but also requires significant effort, any help is welcome.

I'm going to close this as duplicate
