### ISSUE TITLE
Upgrade version of nanomatch

### ISSUE THREAD

**Issue by yavrib** [serverless/serverless#6970]
# Bug Report

## Description

According to [https://github.com/advisories/GHSA-4g88-fppr-53pp](https://github.com/advisories/GHSA-4g88-fppr-53pp) one of the dependencies ([nanomatch@1.2.13](https://github.com/micromatch/nanomatch/blob/7058998c9ff16fb10e3ed2b411261c7fe3d4f0d1/package.json#L37) > [snapdragon@0.8.1](https://github.com/here-be/snapdragon/blob/1433d322d00a989984cc58de87ea3c4dac600988/package.json#L28) > [base@0.11.1](https://github.com/base/base/blob/d860297eb6b98f6f5b10b40ec43d8550eba07499/package.json#L32) > [cache-base@0.8.4](https://github.com/jonschlinkert/cache-base/blob/38bec2e70f8fbd041ded5fea817551b7f890df9e/package.json#L30) > set-value@0.3.3) of Serverless Framework is vulnerable.

1. What did you do?
Security alerts revealed that one of the children dependencies of the Serverless Framework is vulnerable.
1. What happened?
I tried to upgrade the Serverless Framework version, however there were no suitable versions that would fix the issue.
1. What should've happened?
A safer version of the package should be introduced in order to reduce the security vulnerabilities of the framework.
1. What's the content of your `serverless.yml` file?
n/a
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
n/a

Serverless version (currently): 1.27.2
Also, as stated, tried the latest version

**Comment by medikoo** [comment]
@yavrib thanks for report. 

We're currently using latest version of `nanomatch`. If there's a security issue with it, I believe we need to report it at their repository (?)

**Comment by yavrib** [comment]
Following the thread in https://github.com/micromatch/nanomatch/issues/22, I managed to get the more secure version of the library.

I am closing the issue.
