### ISSUE TITLE
Support for node12

### ISSUE THREAD

**Issue by kabo** [serverless/serverless#6974]
# Feature Proposal

## Description

1. Support for node12

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/

**Comment by kabo** [comment]
Ah, it already works, just set runtime to `nodejs12.x`.

**Comment by medikoo** [comment]
Yes, and defaults will be bumped with today's release. See: https://github.com/serverless/serverless/pull/6983
