### ISSUE TITLE
Deploying scheduled events

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#698]
I've created a new function called "foo" and added the following to the s-function.json:

```
"events": [
    {
      "name": "schedule",
      "type": "schedule",
      "config": {
        "schedule": "rate(5 minutes)"
      }
    }
  ]
```

I then ran `sls dash deploy` and used it to deploy my new "foo" function, followed by `sls event deploy` which appears to have created the "foo" Lambda function, and CloudWatch event schedule, but the event is showing as disabled within the CloudWatch console and no events appear to have been associated to the Lambda function within the Lambda console.

Are there any docs on how I should create new scheduled events using Serverless?

**Comment by boaf** [comment]
You have to set `enabled` to `true` in the `config` object:

```
"events": [
    {
      "name": "schedule",
      "type": "schedule",
      "config": {
        "enabled": true,
        "schedule": "rate(5 minutes)"
      }
    }
  ]
```

**Comment by JamieCressey** [comment]
That worked perfectly, thanks @boaf!
