### ISSUE TITLE
Error: Cannot find module '/root/.nvm/versions/node/v10.16.3/lib/node_modules/serverless/scripts/postinstall.js'

### ISSUE THREAD

**Issue by jastsai** [serverless/serverless#6989]
Hi I am trying to upgrade the serverless version by running npm install serverless -g and I got error.
npm -v = 6.13.1
node -v = v10.16.3

> serverless@1.58.0 postinstall /root/.nvm/versions/node/v10.16.3/lib/node_modules/serverless
> node ./scripts/postinstall.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v10.16.3/lib/node_modules/serverless/scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/serverless/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.58.0 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless@1.58.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-21T01_20_07_129Z-debug.log

**Comment by chocnut** [comment]
I've tried to replicate the same node and npm version but it's working fine on my end. Can you please try to uninstall and install serverless again?

**Comment by medikoo** [comment]
@jastsai there must be some issue with you're setup as `scripts/postinstall.js` is definitely there, you may confirm here: https://npmview.now.sh/serverless@1.58.0

**Comment by jastsai** [comment]
it looks like it is working after I run the installation using sudo.
Thank you for the responses and help.

**Comment by EtherAuthority** [comment]
> it looks like it is working after I run the installation using sudo.
> Thank you for the responses and help.

sudo worked for me!

**Comment by Dirvann** [comment]
> it looks like it is working after I run the installation using sudo.
> Thank you for the responses and help.

Even when I was logged in as root I had to use sudo, then it worked.
