### ISSUE TITLE
demo site and response time ?

### ISSUE THREAD

**Issue by grosser** [serverless/serverless#7]
demo site would be great to see it in action / have a starting app ...
I'm also curious what the average response time of these lambda functions is, do you guys have any data / graphs to share ?

**Comment by shankscoder** [comment]
+1 for a demo of this platform in action. Amazing effort. Really hope to build with this soon.

**Comment by brianklaas** [comment]
+1 for the demo.

Lambda response time is dependent on the nature of the work being done by the function. Image processing naturally takes a lot longer than JSON unpacking and manipulation. The AWS console gives you metrics about response time for each of your functions, so the overall computational time is largely dependent on what you write. There is a basic overhead of ~300ms if the Lambda function hasn't been called in a while and the container in which the Lambda function runs needs to be spun up. Lambda is pretty good about reusing containers where possible but if you have infrequently-called functions or a low traffic app, you're going to see that spin up time pretty often.

**Comment by austinrivas** [comment]
+1

I would also be happy to help with the demo if you need some more hands on deck. 

Just an idea, but if you would like to focus on your swagger implementation I can but together a fun JAWS themed ui demo that consumes your api.

**Comment by remicastaing** [comment]
> but if you have infrequently-called functions or a low traffic app, you're going to see that spin up time pretty often

Perhaps, a mechanism to wake up all lambda functions could be implemented at the first call. Thoughts?

**Comment by ac360** [comment]
We will have a demo site soon!  I'm going to put this on the JAWS Road Map which will be published this weekend.

@grosser @brianklaas @remicastaing With regards to response times and Lambda optimization, JAWS should and will implement all best practices when it comes to Lambda optimization.  This is a priority. 

Myself and many others have optimization techniques for Lambda.  However, when interest in JAWS exploded over the last few days, a few engineers from AWS contacted me with offers to assist.  Next week, I'm hopeful I will be having a conversation with them and one of the first things I'd like to discuss is Lambda optimization in general and optimization specifically for Lambda powered APIs/back-ends.  Hopefully, I can get the best advice, directly from the source, which I will publish in the Jaws Optimization page and implement throughout JAWS.  

Once we have some clear Lambda optimization standards, we can start tracking/publishing average response times and continue to optimize everything further.
