### ISSUE TITLE
Subscribing function to multiple topics - only first one is subscribed

### ISSUE THREAD

**Issue by vlamic** [serverless/serverless#700]
Hi,

As always - thanks for amazing product! 

I've got an issue here when subscribing a lambda to multiple topics. My s-function contains the following events:
```
  "events": [
      {
          "name" : "sns",
          "type": "sns",
          "config": {
              "topicName": "topic1-${stage}"
          }
      },
      {
          "name" : "sns",
          "type": "sns",
          "config": {
              "topicName": "topic2-${stage}"
          }
      }
  ]
```

However, when I deploy events with `sls event deploy -s dev` the lambda is subscribed to the first topic in the list only. Am I doing something wrong?

Thanks a lot!

**Comment by eahefnawy** [comment]
@vlamic really sorry for the late reply on this one. We've made huge changes since February and there's a good chance this has been fixed as a result.

Is this still an issue for you in v0.5.5? If so I can dig into it right away :)

**Comment by flomotlik** [comment]
@vlamic can you check if this is fixed? I will close this issue for now.
