### ISSUE TITLE
Assign Private API Gateway to a specific VPCE

### ISSUE THREAD

**Issue by gkelly642** [serverless/serverless#7005]
It appears that whenever you configure a API Gateway to have a type of 'PRIVATE' and deploy it within a VPC that it randomly selects one of the relevant VPCE's.
Is there a way to control which VPCE the API Gateway sits behind?

**Comment by dininski** [comment]
This seems related to https://github.com/serverless/serverless/issues/6715

**Comment by medikoo** [comment]
Closing as this tracker is restricted to bug reports and feature requests
