### ISSUE TITLE
How to pass API gateway context variable to proxy lambda

### ISSUE THREAD

**Issue by shaheer-k** [serverless/serverless#7006]
Hi

I am looking for guidance on how to pass the API Gateway context variable (for example: $context.RequestTime) to the proxy lamba.

Basically I want to send the time request has reached in Api gateway to my lambda proxy method as a request header.

Note that I am using serverless framework (serverless.com)

I tried the following but it does not work

    events:
     - http:
         path: /{proxy+}
         method: ANY
         request:
          parameters:
            paths:
              proxy: true
            headers: 
              requestTime: $context.requestTime

Regards,

Shaheer

**Comment by benarena** [comment]
I believe this was addressed by #6911
