### ISSUE TITLE
Allow for the removal of default request mapping templates

### ISSUE THREAD

**Issue by sihutch** [serverless/serverless#7008]
Currently [default request mapping templates are created ](https://github.com/serverless/serverless/blob/v1.58.0/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js#L189) both for application/json and application/x-www-form-urlencoded. There does not appear to be a simple method for overriding this default. In our application we only support the application/json content type however application/x-www-form-urlencoded is being automatically created even though it is not supported by our application. Even worse, when generating swagger documentation via the AWS API Gateway this forces us advertise that we consume both:

"consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],

IMO, there really should be a way of overriding defaults in any application. If you can suggest any workaround to this it would be great

**Comment by medikoo** [comment]
Indeed there seem no way to override that.

Some kind of fix would be to allow `null`  for configuration properties placed in `resources.Resources` and translate them to deletions.

We welcome PR on that

**Comment by sihutch** [comment]
My personal opinion is that application/x-www-form-urlencoded is not a particularly useful default anyway. It seems a pity to have to null it everywhere. Would it not be nicer to simply use what IS defined in the .yml? i.e default unless something is specified.

**Comment by medikoo** [comment]
If there's a general agreement we could remove that default. But I think it'll mean a breaking change, and in that case cannot be shipped until we're ready to publish v2 (of which delivery date is uncertain)

**Comment by sihutch** [comment]
Fair point. Maybe a more global setting to turn defaults off. This would reduce the need to keep nulling on every usage whilst maintaining backward compatibility (if defaulted to keep them on)

**Comment by medikoo** [comment]
> Maybe a more global setting to turn defaults off

Yes, we can address that specifically with some configuration option.

Still when proposing special `null` handling, I was thinking about more generic way in which we can tweak generated configuration (it could serve as meantime workaround also for other similar problems, and not just that specific one).

**Comment by Nemo64** [comment]
I just noticed this too and want to wake this back up.

How about just disabling the default if a custom one is defined? This is still breaking... but I don't know a situation where you would rely on it.

I see 2 use cases:
1. You want a generic request with parameters in which case you actually do not care if the request body was json or url-encoded as long as the lambda gets the correct body.
2. You want a to actually map the request to the event object. In which case: any mapping you didn't define would be wrong and at best would result in some undefined error and at worst would create undefined behavior.

I currently experiment with use case 2 and also with validation on the apiGateway side. And there I have an additional problem, validation is also bound to the Content-Type so I now have a potential way of going around the validation wich isn't good either.

I look into it and see how easy it is to get a feature flag there.

**Comment by medikoo** [comment]
> How about just disabling the default if a custom one is defined?

I've just checked and I believe you can override the default as following (what you can't do, is to remove the template completely):

```yaml
functions:
  someFunction:
    events:
      - http:
          request:
            template:
              application/json: 'custom template'
```

**Comment by Nemo64** [comment]
Yes, you can override them but the `application/x-www-form-urlencoded` is still present.
and @sihutch want(ed) to disable them completely for the passthough behavior.
I want to limit them to only `application/json` so I don't have potential security holes in my application though undefined behaviour.

So there needs to be some way to set [useDefaults](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js#L203) to false.
The simplest way I suggested is to simply disable it when `typeof http.request.template === 'object'` (which is already present a few lines below that) but that would potentially be breaking if someone relied on adding an additional template to the defaults.

I'm fairly new to api gateway and therefore probably don't know all use cases but I know of at least 2 where the current behaviour is either dangerous or unusable.

**Comment by medikoo** [comment]
@Nemo64 Assuming that overriding default with some value, is not good enough, I think non breaking way, is to support notation as:

```yaml
functions:
  someFunction:
    events:
      - http:
          request:
            template:
              application/x-www-form-urlencoded:  null
```

Through which we may indicate that we do not wish the default to be applied for given request type.

I think it's an acceptable solution, taking into account how invasive defaults are applied.

For v2.0 we may consider what you suggest, so to not apply defaults at all when `http.request` is provided, but I'd like to have more info on whether that's indeed desirable for all cases

**Comment by Nemo64** [comment]
Well one case I could think of where removing the defaults is not desirable is if you actually use the defaults and want to add for example `text/csv` and then parse that down to the same format as the other defaults would provide.

That would be a lot of template though as the default template emulates the lambda proxy behaviour and building one for another format that is compatible with the defaults... I don't know, I'd probably build a custom one for each format with just what I need as it would be a lot more obvious what I'm doing.

**Comment by bondezbond** [comment]
This is definitely an issue I'm having. It would be nice to not have default templates added if I defined the templates I want

**Comment by Catastropha** [comment]
Are there any updates on this one?

**Comment by medikoo** [comment]
@Catastropha PR's welcome!

**Comment by jormaechea** [comment]
@medikoo I'll take this one! :raised_back_of_hand: 

Which approach do you guys think is best?

1. Setting each `[...].request.template['content-type']` to `null` or `false`
2. Setting `[...].request.ignoreDefaults` to `true`
3. Any third non-breaking idea?

**Comment by jormaechea** [comment]
I chose the first one as it was the one proposed by you.

Let me know what you think.

**Comment by medikoo** [comment]
@jormaechea I believe we should stick to what's proposed here: https://github.com/serverless/serverless/issues/7008#issuecomment-654185286

`false` introduces another _type_ for value, which doesn't seem clean. `null` I believe quite clearly signals an intent for not having value at this point.

Thanks for giving that a spin!
