### ISSUE TITLE
Expose new ParallelizationFactor option for Kinesis streams

### ISSUE THREAD

**Issue by michael-ar** [serverless/serverless#7019]
Add support for the new Kinesis config option ParallelizationFactor which allows you to scale the concurrency of a shard up to 10 (currently set to 1). More info here:

https://aws.amazon.com/blogs/compute/new-aws-lambda-scaling-controls-for-kinesis-and-dynamodb-event-sources/

Should be fairly simple to follow existing patterns for where you've exposed similar options and am happy to pick it up.

**Comment by medikoo** [comment]
@michael-ar thanks for request! PR is definitely very welcome
