### ISSUE TITLE
Using websockets (mqtt)

### ISSUE THREAD

**Issue by mehdi-cit** [serverless/serverless#702]
Hello everyone.
JAWS seems interesting but from what I can see it can only handle the REST (ish) protocol.
Would it be conceivable/desirable to use something like http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html#mqtt-ws
to achieve realtime bidirectional communication between client/servers ?
Any thoughts?
Some people seem to have achieved something close (uni-directional):
https://medium.com/@jparreira/receiving-aws-iot-messages-in-your-browser-using-websockets-9b87f28c2357#.5wfysld0j

**Comment by pmuens** [comment]
Hey @mehdi-cit thanks for mentioning that.

Here's another issue where this is discussed:
https://github.com/serverless/serverless/issues/647
