### ISSUE TITLE
Update docs regarding AWS support for triggering a Lambda function from an SQS FIFO queue

### ISSUE THREAD

**Issue by faheel** [serverless/serverless#7023]
# Bug Report

## Description

The [AWS documentation for SQS](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html) states that:

> Lambda event source mappings support standard queues and FIFO (first-in, first-out) queues.

whereas the [Serverless documentation for SQS](https://serverless.com/framework/docs/providers/aws/events/sqs/) has not been updated to reflect this, and it still states:

> **IMPORTANT**: AWS is not supporting FIFO queue to trigger Lambda function so your queue(s) must be a standard queue.

**Comment by medikoo** [comment]
@faheel thanks for pointing! PR's welcome
