### ISSUE TITLE
Support GCP Cloud Function connect to VPC network

### ISSUE THREAD

**Issue by bao1018** [serverless/serverless#7028]
# Feature Proposal

## Description

We would like to allow GCP cloud function to connect to a service in a VPC network, the native`gcloud beta functions deploy` command support this feature via adding `--vpc-connector` argument.

but unfortunately can not figure out how to use serverless framework to deploy the cloud function as vpc connection supported.

We need to add below argument for GCP CF as
1. vpcConnectionName:
pass the name of the vpc connection

2. clearVpcConnector
pass `TRUE` or `FALSE` to clean up the VPC connection from settings

**Reference Link:**
https://cloud.google.com/functions/docs/connecting-vpc

**Comment by pmuens** [comment]
Thanks for opening @bao1018 👍

Could you re-open this issue in the Google Cloud Functions [provider plugin](https://github.com/serverless/serverless-google-cloudfunctions)? Thanks!

**Comment by bao1018** [comment]
Thanks @pmuens, I move this issue to
https://github.com/serverless/serverless-google-cloudfunctions/issues/190
