### ISSUE TITLE
dynamodb issue

### ISSUE THREAD

**Issue by vkreal** [serverless/serverless#703]
Hi all,
I am getting error below I trying to require dynamodb. Anyone know the proper way to make this work?
Thanks for any help! 

var doc = require('dynamodb-doc');
var dynamodb = new doc.DynamoDB();

{"errorMessage":"Cannot find module '/Users/kreal/Desktop/yaya-serverless/_meta/_tmp/create@1456611476011/node_modules/aws-sdk/apis/metadata.json'","errorType":"Error","stackTrace":["Function.Module._resolveFilename (module.js:338:15)","Function.Module._load (module.js:280:25)","Module.require (module.js:364:17)","require (module.js:380:17)","i (/var/task/multi/create/handler.js:1:497)","/var/task/multi/create/handler.js:1:688","n (/var/task/multi/create/handler.js:1:1681)","Object.i [as services] (/var/task/multi/create/handler.js:1:2137)","Object.<anonymous> (/var/task/multi/create/handler.js:3:5605)","Object../api_loader (/var/task/multi/create/handler.js:3:5790)"]}

**Comment by camhart** [comment]
@vkreal What were you doing wrong?

**Comment by vkreal** [comment]
Adding below to s-component.json fixed the issue for me.

"custom": {
    "optimize": {
      "exclude": [
        "aws-sdk"
      ]
    }
