### ISSUE TITLE
expose Bisect on Function Error prop for Kinesis Streams

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [serverless/serverless#7041]
# Feature Proposal

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-failure-handling-features-for-kinesis-and-dynamodb-event-sources/

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
1. **Optional:** If there is additional config how would it look

Similar or dependent issues:

- https://github.com/serverless/serverless/pull/7024

**Comment by jchaasis** [comment]
@WIZARDISHUNGRY Are you working on an implementation for this? If not, I'd like to give it a go

**Comment by WIZARDISHUNGRY** [comment]
No, go for it
