### ISSUE TITLE
Unsupported ParallelizationFactor parameter for given event source mapping type

### ISSUE THREAD

**Issue by alfaproject** [serverless/serverless#7049]
I started getting this error after last serverless release: 1.59.0

It seems to work fine in `us-east-1` where I run my CI stack, but it fails in `eu-west-1` with that error ):

**Comment by medikoo** [comment]
@alfaproject can you share related `serverless.yml` config?

**Comment by alfaproject** [comment]
@medikoo all you need is a lambda with a kinesis stream attached to it. We never added this property. Serverless is adding it by default with a value of 1: https://github.com/serverless/serverless/blob/f1d2d0038c650f9629fbec76cede42e289290f8a/lib/plugins/aws/package/compile/events/stream/index.js#L92

I'm sorry, but I can not share our `serverless.yml`. We don't actually use that anyway and we have hundreds of services that just stopped deploying with that error after last release ):

I've made a patch to not include that property and all is good but the question remains why even add the property if it's not declared in the configuration file?

**Comment by alfaproject** [comment]
Example of a deployed lambda with such a Kinesis trigger in `us-east-1` which works fine: https://puu.sh/ELO0z/a13d4695d1.png

That attribute should NOT be set

**Comment by medikoo** [comment]
>  @medikoo all you need is a lambda with a kinesis stream attached to it. 

I've just successfully deployed this service: https://github.com/medikoo/test-serverless/tree/kinesis

Technically `1` is a valid value for [`ParallelizationFactor`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-parallelizationfactor), so it's hard for me to say why it fails for you (having reproducible test case would help)

Still, I totally agree, we shouldn't set this (optional) property when it's not explicitly configured.
We'll patch it shortly.

**Comment by alfaproject** [comment]
Our basic listeners are pretty much like that. It could be that AWS started to support in the meanwhile or there was some downtime of some service. Bad luck maybe, but still. I'll try again tomorrow
