### ISSUE TITLE
configuring root paths and text/html responses in serverless

### ISSUE THREAD

**Issue by davidjnelson** [serverless/serverless#705]
I'd like to have a universal react app running in api gateway / lambda, from the root path and also from nested paths.

I'm not sure how to configure the root path in serverless, or how to configure api gateway endpoints to return a content type of text/html or how to setup the mapping template for that in serverless.  I see how to do both here from the aws console:

https://www.toptal.com/aws/service-oriented-architecture-aws-lambda

I looked around the serverless docs but couldn't find anything, and also googled around a bit.

Is this currently supported, or is this something that would need to be implemented as a plugin or just added to the docs?

Thanks!

**Comment by dherault** [comment]
I'm doing the exact same thing :)
My goal is you have one lambda for React server-side rendering, one lambda for data fetching (graphql), and many other lambdas (auth, images, etc...)

The tricky parts with SSR are:
- Getting the URL from APIG (event object config)
- Serving HTML from lambda (response object config)
- Serving 404 pages with the correct statusCode (super tricky, I found a solution, but it's quite opiniated, I add a `<!-- 404 -->` comment on top of my HTML response, so the APIG regex magick can operate and answer 404 statusCode). If you find anything better, I'm begging you, tell me, thanks :)

The SSR lambda is under `comp_main/lambda_rendering`.
https://github.com/dherault/Aquest

**Comment by davidjnelson** [comment]
Oh awesome, thanks!  I'll try it out.

**Comment by flomotlik** [comment]
I will close this issue for now as it seems the question was resolved
