### ISSUE TITLE
Feature for using kaniko for knative provider

### ISSUE THREAD

**Issue by pavankumarkatakam** [serverless/serverless#7073]
# Feature Proposal
It  seems in the provider knative, if we mention the function handler as docker file, server less use the host docker deamon and build the image and push to docker hub (given the username and password in env), But my feature request is to build the image using the Kaniko (https://github.com/GoogleContainerTools/kaniko) it is googles docker build system in kubernetes. Ans also if possible  support for private container registries.
## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

 Here using the kaniko build system means, the developer need not to have install the docker in his system as well as for larger images the CPU power at developer system is not sufficient, if we implement this feature our image builds will be in kubernetes cluster rather than developing system.

1. **Optional:** If there is additional config how would it look

Similar or dependent issues:
No issues i found.

**Comment by pmuens** [comment]
Hey @pavankumarkatakam thanks for opening! :+1:

Could you migrate this issue over to the [`serverless-knative`](https://github.com/serverless/serverless-knative) plugin repository? This repository contains all the issues related to the Serverless Framework core project.

Thanks in advance!

**Comment by pavankumarkatakam** [comment]
Ok, Moved to [here](https://github.com/serverless/serverless-knative/issues/5)
