### ISSUE TITLE
Error at install on MacOS 10.15.1

### ISSUE THREAD

**Issue by mattpackwood** [serverless/serverless#7077]
# Bug Report

## Description

1. What did you do? Try to install
1. What happened? Got error "Serverless: Unable to store serverless config due to EACCES error"
1. What should've happened? No errors
1. What's the content of your `serverless.yml` file? I do not have one
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`) Not applicable

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@mattpackwood it's more a warning than error, it doesn't affect framework functionality

Still can you share how do you install the framework? What command exactly do you use?

**Comment by hcancelik** [comment]
I'm having the same issue with running `sudo npm install serverless --global`
