### ISSUE TITLE
Deploying to a second stage delete's lambda's from first stage

### ISSUE THREAD

**Issue by ElectroMW** [serverless/serverless#7081]
# Bug Report

## Description
As described above, once I deployed a different stage, the lambda functions from the first stage were deleted. The rest of the deployment worked correctly.

I have removed all traces of all deployments from aws using sls remove and started again. 

serverless create_domain --env production --stage production
serverless deploy -c serverless.yml --env production --stage production --verbose
Production deployed and was working.

Then ...

serverless create_domain --env staging --stage staging
serverless deploy -c serverless.yml --env staging --stage staging --verbose

Staging deploys correctly, except that it deletes production's lambda methods (they are correctly namespace-d) after existing together for about a minute.

Seems as though the cleanup is mistaking a different stage's lambda's as old ones.
Even more disturbing, there is no error message when this happens.

---serverless.yml
service: #####
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: ${env:AWS_REGION_STRING}
  stackName: ####
  apiName: ####
  memorySize: 128
  timeout: 30
  logRetentionInDays: 7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
  environment:
    ####: ${env:####}
   ####: ${env:####}
    ####: ${env:####}

functions:
  ####:
    handler: resources/###.##
    events:
      - http:
          path: ###/###
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  #########:
    handler: resources/#####.####
    events:
      - http:
          path: ###/######
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  ######:
    handler: resources/######.#####
    events:
      - http:
          path: #####/#####
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

resources:
  Resources:
    #########:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ##########
        AttributeDefinitions:
          - AttributeName: ####
            AttributeType: N
          - AttributeName: #######
            AttributeType: N
        KeySchema:
          - AttributeName: ###
            KeyType: HASH
          - AttributeName: ######
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ########:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ######
        AttributeDefinitions:
          - AttributeName: ##
            AttributeType: N
          - AttributeName: ##########
            AttributeType: N
        KeySchema:
          - AttributeName: ##
            KeyType: HASH
          - AttributeName: #######
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    #########:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: #########
        AttributeDefinitions:
          - AttributeName: #####
            AttributeType: S
          - AttributeName: #####
            AttributeType: S
        KeySchema:
          - AttributeName: ####
            KeyType: HASH
          - AttributeName: #####
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    #########:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:##########}
        AttributeDefinitions:
          - AttributeName: ####
            AttributeType: S
          - AttributeName: #########
            AttributeType: N
        KeySchema:
          - AttributeName: ####
            KeyType: HASH
          - AttributeName: ###########
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
  serverless-offline:
    port: 4000
  customDomain:
    domainName: ${env:############}
    certificateArn: ${env:############}
    stage: ${self:provider.stage}
    endpointType: regional
    createRoute53Record: true

Any help or workarounds much appreciated

**Comment by medikoo** [comment]
@ElectroMW thanks for report.

This doesn't look as Serverless Framework issue, but one of the plugins you rely on.

Create a minimal test case that exposes the issue. It should help you find which plugin is responsible for that, then please open an issue in its bug tracker

**Comment by ElectroMW** [comment]
OK, i'm trying the command again with plugin's disabled one by one. I'll let you know what I find.

**Comment by ElectroMW** [comment]
Disabled all plugins, same issue..
Here is the verbose output from the CLI from update complete onwards...

CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - xxx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - xx
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - xx
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - xx
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - xx
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Deployment - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - xx
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - xx
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - xx
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - xx
Serverless: Stack update finished...

**Comment by medikoo** [comment]
Can you paste minimal `serverless.yml` (one that doesn't list any plugins) with which we can reproduce that?

**Comment by ElectroMW** [comment]
I've run this simple config and I've reproduced the error.
1) serverless deploy --stage production --verbose
2) serverless deploy --stage staging --verbose # and modify serverless.yml to set stage to staging

Production lambda gets deleted, same output in logs.
SLS version = 1.59.3



service: Test

provider:
  name: aws
  runtime: nodejs10.x
  stage: staging # production first 
  region: eu-west-1
  stackName: Test
  apiName: Test
  memorySize: 128
  timeout: 30
  logRetentionInDays: 7


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  testFunction:
    handler: resources/test.func
    events:
      - http:
          path: test/func
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

resources:
  Resources:
    testTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: testtable
        AttributeDefinitions:
          - AttributeName: param1
            AttributeType: N
          - AttributeName: param2
            AttributeType: N
        KeySchema:
          - AttributeName: param1
            KeyType: HASH
          - AttributeName: param2
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

**Comment by medikoo** [comment]
@ElectroMW thanks. This issue occurs because you override CloudFormation stack name (see `stackName`) and do not change it, between stages.

In result same CloudFormation stack is used (that makes stages ineffective).

We could probably handle that in a framework with some error (best if covered under: https://github.com/serverless/serverless/issues/6562 )

**Comment by ElectroMW** [comment]
Doh! - All sorted now. Thank you for your help, +1 pivo.
