### ISSUE TITLE
Environment variables are not resolved same way for remote and local invocations

### ISSUE THREAD

**Issue by master-of-null** [serverless/serverless#7087]
# Bug Report

## Description

Given: 
```
  environment:
    events_store_table:
      Ref: EventsStoreEncryptedDynamoDBTable
```

When invoking a function locally `sls invoke local ...`, which makes a dynamoDB API call with `TableName` referencing `process.env.events_store_table` the following error occurs:

```
1 validation error detected: Value '[object Object]' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+\
```

**Comment by medikoo** [comment]
@master-of-null thanks for report.

Do you find those variables propagated as expected to deployed lambdas? 

To me it looks as configuration issue. CloudFormation instructions are not normally supported in `serverless.yml` config (it's only when support for that was ensured internally, and when value ends as is in CloudFormation template)

**Comment by master-of-null** [comment]
Up until recently it's worked just fine. Thankfully it works in deployed lambdas, but it makes local invocation a nightmare

**Comment by medikoo** [comment]
> Up until recently it's worked just fine

Can you confirm with which exactly Serverless version it stopped working?

**Comment by master-of-null** [comment]
1.57.0

**Comment by master-of-null** [comment]
> > Up until recently it's worked just fine
> 
> Can you confirm with which exactly Serverless version it stopped working?

1.57

**Comment by medikoo** [comment]
@master-of-null few more questions

1. Does `Ref: EventsStoreEncryptedDynamoDBTable` point as `AWS::DynamoDB::Table` resource?
2. In deployed lambda what actually ends at `process.env.events_store_table`? A table name? Do you rely on any plugins?

**Comment by master-of-null** [comment]
1. Yes, it does point to an `AWS::DynamoDB::Table` resource
2. it's the table Name, I use that (`process.env.events_store_table`) as the parameter, in aws-sdk `DocumentClient` as the `TableName`

**Comment by medikoo** [comment]
I've looked into it, and situation is as follows:

It works on deployed lambdas, only by chance of not documented magic on AWS side. Technically if we follow [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html) it's strings that should be assigned as environment variables.

In example you reference, you pass an object to environment variable value. Object is an CloudFormation instruction which links to other resource object. CloudFormation internals resolve referenced resource and then resolve meaningful string that matches that resource.

We cannot do that with local invocation, as rules which are followed by CloudFormation internally are not disclosed anywhere, technically it's a black box we don't have access to.

I've contacted AWS about that, and they've responded:

_Unfortunately, there is no internal documentation of this resolution rules (...) I have created an internal ticket with the AWS documentation team to update the Lambda function environment documentationto avoid confusion. As a support engineer I can't provide ETA when this documentation will be updated, we apologize for the inconvenience caused._

I believe the right way to approach it on a Framework level to ensure uniform behavior for both local and remote invocation, it to explicitly not allow an object references to be configured as environment variables.

I'll leave this issue open until we do that, still that'll be a breaking change, so it'll make take a while.

On your side just ensure that you do not define objects as environment variables. In this specific case you may point directly the TableName property of defined resource (via `self:` variable)

**Comment by nkeating-mutualofenumclaw** [comment]
If there are other's like me who leverage AWS References, Attributes and ImportValues, I've written a workaround for this issue and created a plugin which will resolve AWS resources for aws (currently limited to DynamoDB, Lambda, S3, SNS, SQS, StepFunctions, SecretsManager and Parameter Store).

Here is the GitHub Repo where its been implemented, and instructions on how to install and use the plugin from npm.
https://github.com/mutual-of-enumclaw/serverless-plugin-local-env

This plugin overrides the existing implementation of how environment variables are setup for local debugging, and leverage the AWS Stack to resolve values which are requested following the AWS Documentation on CloudFormation for each service.

If there are other services which you need feel free to add them, or let me know as I can add them fairly easily.

**Comment by medikoo** [comment]
I've re-discussed this with AWS support, and it appears there was a confusion. They've initially stated that resolution rules remain not documented, but they've probably meant that it's not outlined on this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html

They agreed after all, that rules can be secluded from `Return Values --> Ref` documentation for each resource respectively.

In light of that I agree it's good to bring support for that into the framework, resource by resource, on demand basis.

Follow https://github.com/serverless/serverless/pull/7147 for implementation details

**Comment by jorenvh1** [comment]
What's the progress on this? I would like to use my apigateway url in my serverless code using env variables like this: http://www.goingserverless.com/blog/api-gateway-url

Anyone that can help me with a fix or workaround?

**Comment by medikoo** [comment]
> What's the progress on this? 

Follow #7147

**Comment by medikoo** [comment]
Closing as support for `Ref` resolution wash brought with #8198, also we've added support for `Fn::ImportValue`with #8157.

If there's a demand to support other CF functions please open a new feature request. Thank you!

**Comment by katlim-br** [comment]
how would you try this:

```
environment:
    MY_QUEUE_NAME:
      Fn::GetAtt: [MySQS, QueueName]
```

**Comment by maghirardelli** [comment]
I have looked at https://github.com/serverless/serverless/pull/8157.
How would these changes be used within a `serverless.yaml` file? I am currently using it as this and still getting my env variable set as `[object Object]`:
```
custom:
  backendTools:
    environmentOverrides: 
      lambdas:
        lambdaName:
          environment:
            LOCAL_ARN:
              'Fn::ImportValue': '${AuthenticationLayerHandlerRoleArn}'
```

**Comment by bvanderdrift** [comment]
For anyone who bumps their head against this. I've created a `patch-package` file to allow passing a fallback value for such cases

```diff
diff --git a/node_modules/serverless/lib/plugins/aws/invoke-local/index.js b/node_modules/serverless/lib/plugins/aws/invoke-local/index.js
index b227110..4df570a 100644
--- a/node_modules/serverless/lib/plugins/aws/invoke-local/index.js
+++ b/node_modules/serverless/lib/plugins/aws/invoke-local/index.js
@@ -179,6 +179,8 @@ class AwsInvokeLocal {
             );
           } else if (value.Ref) {
             configuredEnvVars[name] = await resolveCfRefValue(this.provider, value.Ref);
+          } else if(this.options.functionObj.unresolvedEnvValueFallback){
+            configuredEnvVars[name] = this.options.unresolvedEnvValueFallback
           } else {
             throw new ServerlessError(
               `Unsupported environment variable format: ${inspect(value)}`,
```

Example config:

```yml
  some-function:
    handler: some-function.handler
    unresolvedEnvValueFallback: 'not-supported'
```
