### ISSUE TITLE
Use subfolder name in function name

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#710]
I have one component which is called `nodejs` an two folder in this component. One `user` folder and one `post` folder.

For every folder I have a lambda function called `create`.

However if I deploy those functions to AWS one function overlaps the other because they share the same name.

Maybe we can add the folder name to the function name so that we get something like this:

`project-component-subfolder1-functionname`

instead of this:

`project-component-functionname`

and functions can share the same name.

This relates to https://github.com/serverless/serverless/issues/431

**Comment by pmuens** [comment]
I've just moved the `posts` and `users` into own component files. This will reduce the file size dramatically. Although it feels odd when you come from the old "modules" days.

**Comment by eahefnawy** [comment]
@pmuens starting at v0.4 you can set a `customName` property in your `s-function.json` to solve this issue. This is where you can control and specify the exact name of your deployed lambda. Sorry that this is not well documented, we'll be updating our docs post v0.5 :)

**Comment by pmuens** [comment]
@eahefnawy Thank you. Yes, I just stumbled upon this one as I looked through the source. This will fix the above mentioned problem!
