### ISSUE TITLE
Enhance security of S3 event triggered Lambdas

### ISSUE THREAD

**Issue by john-aws** [serverless/serverless#7103]
# Feature Proposal

Enhance the security of the default function policy for all Lambda functions that include S3 event based triggers.

## Description

Use case: prevent [confused deputy attack](https://en.wikipedia.org/wiki/Confused_deputy_problem) where *your* Lambda function may be triggered by an object dropped into a bucket owned by a *different* AWS account.

While admittedly an extremely unlikely occurrence, it is technically possible for your Lambda function to be triggered from someone else's AWS account. One path that makes this possible is as follows:

- sls deploy an S3 bucket and a Lambda function triggered on S3 events from that bucket
- outside of CloudFormation and serverless, delete the S3 bucket
- another AWS account creates the same-named bucket
- the other AWS account configures a new event trigger on the bucket pointing at *your* Lambda

Example of serverless Lambda function declaration:

```
  photoupload:
    handler: photoupload.handler
    description: Process images dropped into S3
    runtime: python3.7
    events:
    - s3:
        bucket: mybucket
        event: s3:ObjectCreated:*
```

Current Lambda function policy example (this is auto-generated by serverless):

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "autogensid",
      "Effect": "Allow",
      "Principal": {
        "Service": "s3.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:999999999999:function:photoupload",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:s3:::mybucket"
        }
      }
    }
  ]
}
```

Proposed changes to function policy (specifically inject condition on AWS:SourceAccount):

```json
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "999999999999"
        },
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:s3:::mybucket"
        }
      }
```

**Comment by medikoo** [comment]
Sounds good to me. @pmuens do you see any issues it may introduce?

**Comment by pmuens** [comment]
Interesting. Thanks for raising this @john-aws :+1:

Yes, that makes sense and right now I too don't see any issues with that. Looks like it should be backwards compatible.

**Comment by pmuens** [comment]
I'm wondering if there are other event sources which could be abused like this.

@john-aws do you know about more event sources exposing this security risk?

**Comment by john-aws** [comment]
Not immediately, but I will update if I come across others.

The issue here is related to the fact that S3 bucket ARNs do not contain AWS account numbers. It would affect SQS queues and SNS topics (rounding out the supported destinations for S3 events) in a similar fashion. If serverless auto-generates resource policies on SQS queues or SNS topics, then a similar policy condition would seem to be appropriate.
