### ISSUE TITLE
Add support for all CloudWatch Event Rule types

### ISSUE THREAD

**Issue by sidewinder12s** [serverless/serverless#713]
Can support be added for all the CloudWatch Event Rules available? Would make configuring Lambda's with Rules much easier. It appears that Scheduled rules are effectively what is already supported.  

The other types would be: 

* AWS API Call
* EC2 Instance State Change Notification
* Autoscaling

AWS API Call would be the big one we would be looking for support for. It also appears that part of the required support for these types has been done in #661 as each of these event types would also have these input parameters available.

**Comment by sidewinder12s** [comment]
I'd also add that supporting AWS API Calls would be the highest priority wish list since that should let you get the functionality of some of the other options.

**Comment by flomotlik** [comment]
@sidewinder12s We're going to implement extended support for Events through Cloudformation in the next version of the framework. I will close this issue as we already have this planned and will have issues about this in upcoming milestone definitions
