### ISSUE TITLE
AWS EventBridge with CloudFormation template

### ISSUE THREAD

**Issue by ngoyal16** [serverless/serverless#7148]
eventbridge now support directly by the cloudformation. this way the bridge connection can be created using aws cloudformation only.

**Comment by ngoyal16** [comment]
@pmuens can you help me with this.

**Comment by codingdiaz** [comment]
This would be huge, we are having an issue with this and using the `cfnRole` setting which would be fixed using the actual cloudformation resources.

**Comment by medikoo** [comment]
Closing, as it was addressed a while ago
