### ISSUE TITLE
Changing DynamoDB schema causes error

### ISSUE THREAD

**Issue by dominikkukacka** [serverless/serverless#716]
Hi,

when i run the `sls resources deploy` twice I get

```
CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename tim-users-dev and update the stack again.
```

any ideas how to fix that?
cheers
Dominik

**Comment by c-knowles** [comment]
The info in https://github.com/serverless/serverless/issues/515 may help. I'm guessing you've changed something that AWS requires replacement for? See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html for details.

**Comment by dominikkukacka** [comment]
thanks for the fast reply!
so i am only adding a new property:
```
    "AttributeDefinitions": [
          {
            "AttributeName": "id",
            "AttributeType": "S"
          }
        ]
```

to

```
    "AttributeDefinitions": [
          {
            "AttributeName": "id",
            "AttributeType": "S"
          },
          {
            "AttributeName": "email",
            "AttributeType": "S"
          }
        ]
```

should this require a replacement?

**Comment by TheSharpieOne** [comment]
According to the documentation posted above, yes. Changing the AttributeDefinitions will require replacing the table.

**Comment by dominikkukacka** [comment]
puh ok, i overlooked that. thanks!
