### ISSUE TITLE
Upgrade https-proxy-agent to v4

### ISSUE THREAD

**Issue by AndrewBarba** [serverless/serverless#7168]
# Bug Report

Serverless currently relies on https-proxy-agent v3, which in turn relies on agent-base v4.

There's a critical bug in agent-base v4 which patches the internal https library incorrectly on Node v12 and later. This causes any package using the new apis in https to break. 

https-proxy-agent (and agent-base) both released updates to fix the problem but Serverless still relies on the older version.

Updated release is here - https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/4.0.0

Example of issue in `got` http library - https://github.com/sindresorhus/got/issues/951

**Comment by medikoo** [comment]
Thanks for report. Addressed in https://github.com/serverless/serverless/pull/7182
