### ISSUE TITLE
SS are considered as List in lambda

### ISSUE THREAD

**Issue by juuyan** [serverless/serverless#7184]
# Bug Report

## Description

1. What did you do?
I created a lambda func to update a SS attribute via ADD
```
UpdateExpression: 'ADD VS :newVersion',
        ExpressionAttributeValues: {
          ':newVersion': ['test'],
        },
```

2. What happened?
The operand is taken as List.
```
Incorrect operand type for operator or function; operator: ADD, operand type: LIST
```

3. What should've happened?
`['test']` should be SS. Have I missed something?

**Comment by medikoo** [comment]
@juuyan thanks for report. Still I don't understand it.

Do you have problems with your lambda not working as expected, or do you feel Serverless framework doesn't respect the configuration (in `serverless.yml`) you provided?

If it's the latter then please provide the configuration you have, and outline exactly which settings you feel were not respected.

If it's an issue with how you're lambda works, then most likely it's not an issue of Serverless Framework

**Comment by juuyan** [comment]
@medikoo thanks for the explanation. The issue I am facing is:
When I make the following call
```
dynamoDbLib.call('update', {
        TableName: tableName,
        Key: {
          PI: projectId,
          SI: 'a',
        },
        UpdateExpression: 'ADD VS :newVersion',
        ExpressionAttributeValues: {
          ':newVersion': ['test'],
        },
        ReturnValues: 'UPDATED_NEW',
```
I got 500 error `Invalid UpdateExpression: Incorrect operand type for operator or function; operator: ADD, operand type: LIST`

I think the `['test']` here should be considered as SS type instead of LIST. I am not sure if it is a bug occurs on the creation of cloudformation...or I have missed something...

**Comment by medikoo** [comment]
@juuyan `dynamoDbLib` is not a part of Serverless Framework

**Comment by juuyan** [comment]
@medikoo srr my fault.
