### ISSUE TITLE
After 1.59.3 canary plugin deployments fail with 500 "Execution failed due to configuration error: Invalid permissions on Lambda function"

### ISSUE THREAD

**Issue by pda75** [serverless/serverless#7185]
# Bug Report

## Description

1. What did you do?
 Upgraded to newest version of serverless and ran our automated build process.
1. What happened? 
Every API call generated a 500; AWS gateway log says: Execution failed due to configuration error: Invalid permissions on Lambda function
1. What should've happened? 
API calls should work.  Somehow the LambdaPermission generated for each function is not correct.  I suspect it is related to the work on lambda provisioning (which requires an alias to work).
1. What's the content of your `serverless.yml` file? We use the "serverless-plugin-canary-deployments" which generates a Lambda Alias.  I've tried to attach a zip file of it.
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`).  If needed, I can generate this, let me know.  I could also generate a diff of the before and after cloudformation json.

NOTE:  Once I used serverless version 1.59.3 (which is what was working before I went on vacation) everything worked again.  I noticed that several cloudformation deletes were skipped if I used the latest serverless version.   I can send more data if needed, but have a work-around for the moment.
Also, if I turned off canary deployments (which stops generating a lambda alias), everything worked with the latest serverless version (1.60.5 is what I was using).  I strongly suspect the recent work for lambda provisioned concurrency is the reason based on the change log descriptions.  

[serverless.zip](https://github.com/serverless/serverless/files/4032496/serverless.zip)

**Comment by medikoo** [comment]
@pda75 See report at the plugin: https://github.com/davidgf/serverless-plugin-canary-deployments/issues/71

**Comment by pda75** [comment]
Thanks.  I did not think to look at the plugin issues.  There were no changes to it recently, so I just looked at the serverless code.  Next time I'll check the issues of the plugin to avoid the dupes.
