### ISSUE TITLE
does serverless support configuring ssl client certificate using serverless.yml file? 

### ISSUE THREAD

**Issue by SonalikaMishra** [serverless/serverless#7198]
Please use https://forum.serverless.com, StackOverflow or other forums for questions.
This issue tracker is dedicated for bug reports and feature requests. Question issues might be closed immediately.

**Useful links:**

- [Official Serverless Forum](https://forum.serverless.com)
- [Official Serverless Slack Workspace](https://serverless.com/slack)
- [StackOverflow `serverless-framework` tag](https://stackoverflow.com/questions/ask?tags=serverless-framework) (need login)

**Comment by medikoo** [comment]
@SonalikaMishra Please use https://forum.serverless.com, StackOverflow or other forums for questions. Thank you!
