### ISSUE TITLE
Multiple Resource Stacks Per Project

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#721]
In `v0.5` we've paved the way for multiple resource stacks.  Not done yet, but will be ready for `v0.6`.  

The goal is to follow microservice concepts more closely and keep resources in small, isolated groups, which teams can work on without affecting project-wide resources.

**Comment by flomotlik** [comment]
With V1 we will have resource stacks per service, so users can easily distinguish between different services. Closing for now as it will be resolved in the next version.

**Comment by kkozmic-seek** [comment]
Is there any way to get multiple stacks per service? Due to 3rd party integration I need some resources to live in a different region, therefore it must be under a different stack. Is there any way to achieve that?

**Comment by rowanu** [comment]
@kkozmic-seek not natively, you'd have to write a plugin for that.

**Comment by kkozmic-seek** [comment]
fair enough. [There already appears to be one,](https://github.com/SC5/serverless-plugin-additional-stacks) which doesn't seem to support multiple regions, but it should be simple to add that.
