### ISSUE TITLE
v0.5: dash summary doesn't resolve template

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#722]
running "sls dash summary" results in the following:

```
...
Serverless: 1 components --------------------------  
Serverless:     |_ [component] (9 functions)  
Serverless:         |_ $${functionName} (1 endpoints - 1 events)  
Serverless:             |_ GET customers/$${functionName} (endpoint)  
Serverless:             |_ mySchedule (schedule event)  
Serverless:         |_ functionEke83 (0 endpoints - 0 events)
...
```
Although defined in a s-template file in the same directory $${functionName} above corresponds with a s-function with the following contents:
```
{
  "name": "$${functionName}",
  "customName": "$${functionNameTemplate}",
  "customRole": "$${roleNameTemplate}",
  "handler": "$${handlerTemplate}",
  "timeout": "$${timeout}",
  "memorySize": "$${memorySize}",
  "custom": "$${customTemplate}",
  "endpoints": "$${endpointsTemplate}",
  "events": "$${eventsTemplate}"
}
```

On the other hand, "functionEke83" above corresponds with the following s-function contents:
```
"$${functionTemplate}"
```
$${functionTemplate} is defined in a s-template at the root of the project with the value in the s-function above (I was trying to unwind the error to see the limitations).

**Comment by eahefnawy** [comment]
@erikerikson FYI, starting in v0.5, all functions in the project should have unique names. With that in mind it wouldn't make sense to have the function name be in templates.

Generally, we can't resolve templates/variables in dash summary, because you'll have to pass in a stage and region, and that wouldn't make sense for this particular action. Templates shouldn't be related to stage and region, but right now we're resolving both variables (which require stage/region) and templates using the same utility function...we should change that an resolve templates and variables separately, that would make it possible to resolve templates in dash summary (but still not variables).

I hope that makes sense :)

**Comment by erikerikson** [comment]
@eahefnawy Don't mean to beat a dead horse but here starts the whipping: it makes sense to have the function name in templates because it would enable me to only need to ground the name in my s-templates file and have (almost) everything else generated using that given name (except where there's custom config).  I'd prefer s-project < s-component < s-function based inheritance/merging so that I could partially define the contents of s-function so long as I've strongly defined the missing items at a higher level in the inheritance tree.  I'm not sure this would be quite as straightforward as I might like to think.

I agree that you have templates and variables are tied together in the code and that it should change.  This is part of why I opened https://github.com/serverless/serverless/issues/681.  As a bonus, I discuss   reasonably coherent thoughts about multi-pass resolution in a comment on that issue: https://github.com/serverless/serverless/issues/681#issuecomment-186377093

As I understand your construction of them, templates and variables are inherently different things with different usage patterns.  Templates are non variable and not based or contingent upon runtime supplied information.  They can thereby be completely grounded at file loading/resolution time (taking file load context into account).  Variables on the other hand are expected to be resolved at execution/action time and can be based on runtime supplied configuration.  Please let me know if I misunderstand.

I would expect the classes that represent the file resources to have a loading, resolution, and usage pattern like:
1. load physical file, assign string representation to "raw" attribute
2. Ground all templates on that string representation and supply the modified string represented results as an (enforced by convention) immutable "base" attribute
3. Ground all variables using the additional runtime knowledge provided for execution before providing them through the prototypical methods used to interrogate the asset.

The trickiest thing here is the contextuality of templates and variables.  I'd advise a settings hive comprising a tree of templates and variables (corresponding with the directory and region/environment hierarchy structures) that you interrogate with the current path/region/et cetera to get a merged resulting value set for that context.  The flow is "what are the settings for my current context", reply: "here's everything you could possibly want to know that is true for that context".  I'd expect that to be internal to the asset implementation classes so that plugins can be blissfully unaware and will automagically do the right thing with the right data.  They could, of course, access the raw/base/settings hive/et cetera components but the bar for understanding would be far higher.

The general approach I'm describing fits into the old Mort, Elvis, Einstein use pattern (http://blog.codinghorror.com/mort-elvis-einstein-and-you/):
1. make the default thing the highly probably use case
2. allow a few more general and powerful but "within the rails" use cases to cover more advance usage scenarios
3. allow for more advanced and raw usage at the cost of increased knowledge investment and awareness

Hope it was worth your time to read all of this.

**Comment by erikerikson** [comment]
The TL;DR: these alterations of the things that matter in Serverless should be very clearly separated and dealt with at a very general and pervasive level.

**Comment by erikerikson** [comment]
To be very concrete, I had been able to cut my s-function down to:
```
"$${functionTemplate}"
```
And my s-template down to:
```
{
  "functionName": "[NAME]",
  "endpointsTemplate": [
    "$${endpointsGetTemplate}"
  ],
  "requestParametersTemplate": {
    "integration.request.header.[HEADER_1]":     "method.request.header.[HEADER_1]",
    "integration.request.path.[PATH_PARAM_1]":   "method.request.path.[PATH_PARAM_1]"
  },
  "requestTemplatesTemplate": {
    "application/json": {
      "[HEADER_1]":     "$input.params().header.get('[HEADER_1]')",
      "[PATH_PARAM_1]": "$input.params('[PATH_PARAM_1]')"
    }
  }
}
```

Therein specifying only what was different from the rest of my API's endpoints.  This is as opposed to the 200 line monstrosity, per method, of not using templates liberally.  There are a few endpoints with more custom response behaviors but otherwise, this would cover most of the api in a simple and clear, least-duplication, way.
