### ISSUE TITLE
whitespace characters are removed from variable names of custom variable types

### ISSUE THREAD

**Issue by mpvosseller** [serverless/serverless#7223]
# Bug Report

## Description

I implemented a serverless plugin that supports a [custom variable type](https://serverless.com/framework/docs/providers/aws/guide/plugins/#custom-variable-types) and found that whitespace characters are removed from the variable names before they are sent to the plugin to be resolved.

Using the [EchoTestVarPlugin](https://serverless.com/framework/docs/providers/aws/guide/plugins/#custom-variable-types) from the documentation as an example:
- `${echo:foo bar}` resolves to `foobar` rather than `foo bar` as I expected.

Also if double quotes or single quotes are used the plugin will not be used to resolve the variable at all.
- `${echo:"foo bar"}` will not be sent to the plugin and resolves to `echo:"foo bar` 
- `${echo:'foo bar'}` will not be sent to the plugin and resolves to `echo:''foo bar`

Code to demonstrate / reproduce the issue is here:
https://github.com/mpvosseller/sls-variable-bug

## Context / motivation
I was interested in writing a plugin to support a custom variable type called `system:` which would get resolved by executing the variable name as an external command. For example: `${system:curl http://example.com/some-value}` or `${system:./myscript somearg otherarg}` 

As a more concrete example of what I'm trying to do. My `serverless.yml` creates a CloudFrontDistribution resource which requires the ARN of a certificate in ACM (which was manually created in the AWS console). Currently I need to hardcode the ARN. A neat alternative would be to dynamically look up the ARN using the domain name which is already in my `serverless.yml`. Such a script might look like this: `aws acm list-certificates | jq -r '.CertificateSummaryList[] | select ( .DomainName == "mydomain.com") | .CertificateArn'` In this way the ARN would no longer need to be hardcoded and would "just work" if the certificate changes or if I switch domains.

If whitespace were supported I might be able to do something approaching:
```yaml
custom:
   domainName: mydomain.com
   certificateArn: ${system:./scripts/find-certificate-arn ${self:custom.domainName}}
```

**Comment by medikoo** [comment]
@mpvosseller Thanks for report. I see it as bug in a Framework, that's worth fixing.

PR's welcome!

**Comment by rdsedmundo** [comment]
See #7304.

**Comment by medikoo** [comment]
Closing as new variables resolver, fixed all that kind of issues
