### ISSUE TITLE
Resources with conditions: dependent resources should also have conditions

### ISSUE THREAD

**Issue by tim-elliott** [serverless/serverless#7224]
When creating a resource (such as an AWS Lambda function) and it has a `condition` statement, the `Condition:` associated with the resource is not also being associated to its dependent resources.  For example, when a versioned Lambda function is created, the associated `AWS::Logs::LogGroup` and `AWS::Lambda::Version` resources aren't created with that same condition, which results in errors.  The proposed solution is that any resource that has a condition should have that same condition applied to any resource definitions generated by Serverless that are associated to that resource.

**Comment by medikoo** [comment]
@tim-elliott I agree, `condition` should also make all resources as influenced by lambda configured with same _condition_.

We're definitely open for PR that'll fix that

**Comment by preshetin** [comment]
I am planning to dive into this. Hopefully, there will be a PR within a couple of days.

**Comment by medikoo** [comment]
Duplicate of #7070
