### ISSUE TITLE
`IS_LOCAL` environment variable is not exposed when invoke an AWS Lambda function on docker

### ISSUE THREAD

**Issue by totem3** [serverless/serverless#7227]
# Bug Report

## Description

`IS_LOCAL` environment variable is not set when invoke an AWS Lambda function on docker.

#### 1. What did you do?

Invoked an AWS Lambda function with `sls invoke local -f hello --docker` or invoked an AWS Lambda function whose runtime is executed by docker such as `go1.x`.

steps to reproduce: 

```
git clone git@github.com:totem3/sls-is-local-report.git
cd sls-is-local-report
sls invoke local -f hello --docker
```

expected output is: 

```
{"statusCode":200,"body":"{\n  \"message\": \"IS_LOCAL: true\",\n  \"input\": \"\"\n}"}
```

but got:

```
{"statusCode":200,"body":"{\n  \"message\": \"IS_LOCAL: undefined\",\n  \"input\": \"\"\n}"}
```

I have confirmed that I get the expected output without `--docker` option.

#### 2. What happened?

`IS_LOCAL` environment variable is not set in docker.

#### 3. What should've happened?

`IS_LOCAL` environment variable is also set when invoke function on docker.

#### 4. What's the content of your `serverless.yml` file?

```yaml
service: sls-is-local-report

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
```

####  5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
❯ SLS_DEBUG=* sls invoke local -f hello --docker
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke invoke:local
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Building Docker image...
START RequestId: f0171145-233f-1f50-d52a-66a6949256ac Version: $LATEST

END RequestId: f0171145-233f-1f50-d52a-66a6949256ac
REPORT RequestId: f0171145-233f-1f50-d52a-66a6949256ac	Init Duration: 182.05 ms	Duration: 8.20 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 38 MB


{"statusCode":200,"body":"{\n  \"message\": \"IS_LOCAL: undefined\",\n  \"input\": \"\"\n}"}
```

## possible cause

`IS_LOCAL` environment variable is set in [`loadEnvVarsForLocal`](https://github.com/serverless/serverless/blob/db4ff0b1cf62f371c610b31666c7872698b2bc77/lib/plugins/invoke/invoke.js#L118-L123). In this function, `IS_LOCAL` is set to `process.env`.

In [`InvokeLocalDocker`](https://github.com/serverless/serverless/blob/db4ff0b1cf62f371c610b31666c7872698b2bc77/lib/plugins/aws/invokeLocal/index.js#L392-L399), only `configuredEnvVars ` and `envVarsFromOptions ` are passed to `docker run` by `--env` option. They do not include `IS_LOCAL=true` because `IS_LOCAL` is only set in `process.env`. 

##  Similar or dependent issues:

- #3639
- https://github.com/softprops/serverless-rust/issues/34

**Comment by medikoo** [comment]
@totem3 thanks for report. I believe `IS_LOCAL` is exposed to lambdas, when it's run directly in local environment, and it's not the case when it's run in docker container.

@pmuens what do you think of supporting `IS_LOCAL` when pursuing docker invocations?

**Comment by techdragon** [comment]
@medikoo / @pmuens  - This is the documented behaviour of the `invoke local` command. 
> The invoke local command sets reasonable environment variables for the invoked function. All AWS specific variables are set to values that are quite similar to those found in a real "physical" AWS Lambda environment. Additionally the IS_LOCAL variable is set, that allows you to determine a local execution within your code.
It should simply be supported and I cant understand why this was even a question.

**Comment by medikoo** [comment]
> It should simply be supported and I cant understand why this was even a question.

@techdragon we welcome a PR that fixes that

**Comment by marekpiotrowski** [comment]
Reproduced it, would like to work on this one. Let me know if it's okay. Thanks.

**Comment by medikoo** [comment]
That'll be great @marekpiotrowski, Thank you!

**Comment by marekpiotrowski** [comment]
Pull request created, I'm not sure if my reasoning is correct, though: https://github.com/serverless/serverless/pull/8372. 

Would be much obliged for confirmation, thanks!
