### ISSUE TITLE
Support setting RedrivePolicty for AWS::SNS::Subscription when using sns as a trigger for a function

### ISSUE THREAD

**Issue by tcastelli** [serverless/serverless#7229]
Similarly to the option of using a FilterPolicy when defining a sns topic as the trigger of a function, it would be useful to allow to define the dead letter target (the name or the arn) so the generated code looks something like 
````
{
                  Type: 'AWS::SNS::Subscription',
                  Properties: {
                    TopicArn: topicArn,
                    Protocol: 'lambda',
                    Endpoint: endpoint,
                    FilterPolicy: event.sns.filterPolicy,
                    RedrivePolicy: {
                        deadLetterTargetArn: {"Fn::GetAtt": [event.sns.dlqName, "Arn"]}
                    }
                    Region: region,
                  },
 },
````

**Comment by medikoo** [comment]
Thanks @tcastelli for suggestion. We're definitely open for PR that provides that

**Comment by tcastelli** [comment]
I've opened a PR #7239 but not sure if that would be enough and what kind of tests can be introduced for this case
