### ISSUE TITLE
expose Destination on Failure prop for Kinesis Streams

### ISSUE THREAD

**Issue by ghost** [serverless/serverless#7236]
# Feature Proposal

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-failure-handling-features-for-kinesis-and-dynamodb-event-sources/

**Destination on Failure**
Now your Lambda function can continue processing a shard even when it returns an error. When a data record reaches the Maximum Retry Attempts or Maximum Record Age, you can send its metadata like shard ID and stream ARN to one of these two destinations for further investigation: an SQS queue or SNS topic. 

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us. - Useful for sending stream failures to a DLQ for monitoring, reporting, or other retry strategies.  

Similar or dependent issues:

- #7024
- #7105

**Comment by medikoo** [comment]
Thank you @SydneyKereliuk for request, we're definitely open for PR's that implements that

**Comment by preshetin** [comment]
@SydneyKereliuk are you working on the implementation of this? If not, I would love to give it a try

**Comment by SydneyKereliuk** [comment]
I have everything but tests here: https://github.com/SydneyKereliuk/serverless/commit/5dbff09b2768aadf28f82d4e54ca75bca37d2626

**Comment by SydneyKereliuk** [comment]
@preshetin I also haven't added any code to create the SNS or SQS resources if they don't already exist.

**Comment by preshetin** [comment]
@SydneyKereliuk thanks for the update! Okay, I will look for something else then.

I wish you success with your efforts!

**Comment by SydneyKereliuk** [comment]
Information from AWS support regarding issues with updating stacks:

> it is a known issue that the following properties: ('BisectBatchOnFunctionError', 'MaximumRetryAttempts', 'MaximumRecordAgeInSeconds' and 'DestinationConfig') of AWS::Lambda::EventSourceMapping are not updating correctly. I found that there is already an escalation to the CloudFormation Service Team and I have also added your voice to this.
