### ISSUE TITLE
Nanoservice example in docs does not work

### ISSUE THREAD

**Issue by dominikkukacka** [serverless/serverless#724]
Hi,

I am not sure if I understood it correctly but my folder structure looks now like this:
![filetree](http://dsh.re/283a6)

the problem is that serverless creates this lambdas:
![filetree2](http://dsh.re/ffc9f)

so the module (subfolder) is not integrated into the lambda name.
Is there a solution for that other than uniquely naming the functions.

cheers and keep up the good work!
Dominik

**Comment by ac360** [comment]
Hi @dominikkukacka 

Sorry about the confusion.  Subfolders are no longer included in the name.  FYI, as of Serverless V0.5, we will be enforcing unique Lambda function names and not prefixing anything to the deployed function name.

In the interim, check out how our [Templates and Variables](http://docs.serverless.com/docs/templates-variables) work.  I would create a function name template and use it in `customName`.  The docs in the link will tell you how

**Comment by dominikkukacka** [comment]
Super! Thanks
