### ISSUE TITLE
Serverless Error: Could not unzip uploaded file

### ISSUE THREAD

**Issue by OG84** [serverless/serverless#7242]
# Bug Report

## Description
I just upgraded to `1.16.3` and got the following error when running `sls deploy`:

```
 Serverless Error ---------------------------------------

An error occurred: CustomDashresourceDashapigwDashcwDashroleLambdaFunction - **Could not unzip uploaded file**. Please check your file, then try to upload again. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ...).
```

Then i tried to open the `custom-resources.zip` myself and got an unexpected end of archive type of error.

With `1.16.2` i got no problems though, so it's not critical for me.

1. What did you do?
- deploy with latest version `1.16.3`
1. What happened?
- AWSLambdaInternal error (Could not unzip uploaded file)
1. What should've happened?
- success like with previous version  `1.16.2`

**Comment by OG84** [comment]
that's strange because the latest release didn't change much, did it?

**Comment by medikoo** [comment]
@OG84 yes, nothing really changed. I believe your issue is not related to  1.61.3 upgrade

**Comment by OG84** [comment]
ok if no one else has the problem, then i can close for now 👍

**Comment by andreigec** [comment]
+1

**Comment by medikoo** [comment]
@andreigec please provide more details, what OS you're on, what version of Framework are you using, and when did error occurred (was it after updating the Framework to new version) ?

**Comment by lima02** [comment]
+1
Mac 10.14.6. It happens during stack deployment.

> serverless --version
Framework Core: 1.69.0
Plugin: 3.6.10
SDK: 2.3.0
Components: 2.30.7

**Comment by medikoo** [comment]
@lima02 thanks for details. I believe removing `~/.serverless/cache/custom-resources` will allow you to recover.

Still I think I know what could lead to that issue, fix is on the way
