### ISSUE TITLE
Minimal IAM policy for Serverless

### ISSUE THREAD

**Issue by dherault** [serverless/serverless#726]
Hi,

I love this framework, I can see that you guys work daily on it and it feels great as a user.
You must know that the road to maturity stretches still far ahead, here's another step:

*What is the minimal IAM policy that the frameworks needs ?*

On the console, I can see that Serverless uses the following AWS services:
![image](https://cloud.githubusercontent.com/assets/4154003/13489211/12acc2c6-e126-11e5-8037-7a07a8b384d3.png)

Can you provide (in the docs also) a JSON IAM policy file for Serverless? One that doesn't grant anything not needed. Thanks!

PS : tell me exactly what the framework does (in terms of AWS actions) and I'll post a policy here.

**Comment by JamieCressey** [comment]
+1 and I think its being covered in #588

**Comment by dherault** [comment]
Oh my bad, I'll close this one and focus on the other one.
