### ISSUE TITLE
Failed To Find CloudFormation Resources For Domain

### ISSUE THREAD

**Issue by Gerst20051** [serverless/serverless#7263]
# Bug Report

## Description

**Works** With Serverless Framework Version: `1.61.1`
**Errors** With Serverless Framework Version: `1.61.2` and `1.62.3`

`Error: Failed to find CloudFormation resources for example.domain.com at ServerlessCustomDomain.<anonymous> (/builds/build/node_modules/serverless-domain-manager/dist/index.js:558:23)`

Similar or dependent issues:

- https://github.com/amplify-education/serverless-domain-manager/issues/306
- https://github.com/serverless/serverless/issues/7225

This still seems to be an issue even when using the latest version `serverless-domain-manager@3.3.1` after they merged in the changes to fix the issue. Maybe there is another issue that hasn't been identified yet? https://github.com/amplify-education/serverless-domain-manager/pull/307

**Comment by medikoo** [comment]
@Gerst20051 it looks as issue on a side of a plugin. Can you report it there?

**Comment by Gerst20051** [comment]
Let me double-check that it was using `3.3.1` it might have still been on `3.3.0` even though I have the version set to `^3.3.0` in the package.json file.

**Comment by Gerst20051** [comment]
I can confirm that the updates you made in the latest release of `serverless-domain-manager` did fix this issue. 🎉

**Comment by claudio-petrini** [comment]
Hello,
we're having this issue when using:
- serverless version `1.66.0`
- serverless-domain-manager `3.3.1`

And an a websocket API gateway. 
Is this supported? It seems that the plugin only looks for REST API Gateway.

Thank you.

**Comment by medikoo** [comment]
@claudio-petrini please report it at https://github.com/amplify-education/serverless-domain-manager/

**Comment by claudio-petrini** [comment]
@medikoo yep, thank you. 
I'm following [this](https://github.com/amplify-education/serverless-domain-manager/pull/319) PR.
