### ISSUE TITLE
Ability to customize the value of NUM_CONCURRENT_UPLOADS

### ISSUE THREAD

**Issue by ibrt** [serverless/serverless#7266]
# Feature Proposal

Ability to customize the value of [NUM_CONCURRENT_UPLOADS](https://github.com/serverless/serverless/blob/5e0c612a3d8ef73ddbb9cef3a5037abf2e8b6af7/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L11) when deploying artifacts to S3.

## Description

I have a fairly large serverless template (~70 functions, which for the record is achieved using the serverless-plugin-split-stacks plugin). I package functions individually for various reasons, one of them being faster cold start, which means I get many fairly small (~7MB) zip files. I am already using the S3 transfer acceleration flag.

My problem: The deploy to S3 does not saturate my bandwidth and takes forever. 

I tracked this down to the source file linked above, where NUM_CONCURRENT_UPLOADS is set to 3. I think being able to set this to a higher value would speed up my deploy. I'd be happy with a workaround using a local serverless plugin, but I don't think it's possible now because that is a const.

Thank you!

**Comment by medikoo** [comment]
@ibrt thanks for report!

What concurrency will work best in your case (have you done some testing)?

**Comment by ibrt** [comment]
In this specific case it peaks at around 10 but I think it's heavily dependent on the number and average size of the files and on my internet connection.

**Comment by medikoo** [comment]
It's probably related to internet connection. I assume that running all uploads concurrently may stuff the transfer and be slower then with that controlled concurrency.

Anyway we're definitely open for PR, I think we can control it with `SERVERLESS_MAX_CONCURRENT_UPLOADS` env var
