### ISSUE TITLE
Make number of deployment artifacts to keep configurable.

### ISSUE THREAD

**Issue by eeroniemi** [serverless/serverless#7275]
# Feature Proposal

## Description

It would be nice feature if we could configure number of deployment artifacts to keep on S3 bucket. Currently this number is [hard-coded to 5](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js#L10).

We have CI deployment job which makes deployment and after that runs smoke tests. These smoke tests tend to be flaky (depend on 3rd party service), and this causes multiple `serverless deploy`'s to be executed until these tests pass. Problem is that if we have to repeat the deployment 5 times or more we lose our ability to rollback to previous good deployment because it was already cleaned up by [this script](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js).

This feature could be implemented without breaking BC. There could be new optional configuration file property (for example `deploymentArtifactsToKeep`) which would have default value of 5.

**Comment by medikoo** [comment]
@eeroniemi thanks for proposal. It's definitely a good idea.

I think we can support tweaking it directly in `serverless.yml` as e.g.

```yaml
provider:
   preservedLastStackVersionsCount: 5 # default
```

PR that implements it, is definitely welcome!

**Comment by rdsedmundo** [comment]
See #7283
