### ISSUE TITLE
Redrive Policy not properly referencing queue

### ISSUE THREAD

**Issue by tcastelli** [serverless/serverless#7276]
## Description

Recentely, I have been able to test serverless 1.62 which includes the option to use redriverPolicy for sns events. However, when I submited a PR for that feature, I overlooked the param specificacion format on the queuePolicy that is created. To be more specific, the Resource part needs to be an ARN but the Queue needs to be defined by URL.
````
Resource: event.sns.redrivePolicy.deadLetterTargetArn -> should be a Fn::GetAtt [deadLetterTarget, Arn]
````

````
Queues: [event.sns.redrivePolicy.deadLetterTargetArn], -> should be a Ref: deadLetterTarget
````

This translates in using GetAtt Arn for one thing and Ref for the other, while now both use the ARN (which leads to deployment errors). Also, the documentation says that Ref can be used which is wrong since it would only provide one of the needed values.

In this case, what I think would be easier is just to pass the queue resource name to the sns event redrivepolicy section (like myDLQ), and build the GetAtt and Ref inside.
Other solutions would involve more complex things like trying to generate the url from the Arn. I'm open to whatever you think is best and will start a PR as soon as there's consensus

#7239

**Comment by medikoo** [comment]
> In this case, what I think would be easier is just to pass the queue resource name to the sns event redrivepolicy section (like myDLQ), and build the GetAtt and Ref inside.

That's true, but it'll work well only, if given `deadLetterTarget` is also configured in context of same stack, isn't? Wouldn't that be limiting?

**Comment by tcastelli** [comment]
That's true, maybe then we can ask for the url and the arn both as parameters for the redrivePolicy, so people can reference other stacks and directly give what they want to use. What do you think?

**Comment by medikoo** [comment]
@tcastelli I think best would be if we support input in either ref or arn format, and just detect by format if it's arn (starts with `arn:`) and eventually generate url out of `arn` (is it straightforward?)

**Comment by tcastelli** [comment]
@medikoo I think in that case we should stick with receiving the Arn (since what is requested is deadLetterTargetArn) either as a string or using Fn:GetAtt and then generate the queueUrl. I'll submit a PR soon

**Comment by cfbao** [comment]
I just encountered this bug today. Looking forward to the fix.
