### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].

### ISSUE THREAD

**Issue by gautham553** [serverless/serverless#7286]
# Bug Report

## Description

1. What did you do?

sls create -t azure-python -p deploydtu
sls plugin install -n serverless-azure-functions
sls deploy

1. What happened?

The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].

export template is showing phpVersion instead python version
`{
                "numberOfWorkers": 1,
                "defaultDocuments": [
                    "Default.htm",
                    "Default.html",
                    "Default.asp",
                    "index.htm",
                    "index.html",
                    "iisstart.htm",
                    "default.aspx",
                    "index.php"
                ],
                "netFrameworkVersion": "v4.0",
                "phpVersion": "5.6",
                "requestTracingEnabled": false,
                "remoteDebuggingEnabled": false,
                "httpLoggingEnabled": false,
                "logsDirectorySizeLimit": 35,
                "detailedErrorLoggingEnabled": false,
                "publishingUsername": "$sls-weur-dev-tabarlow-azure-python",
                "scmType": "None",
                "use32BitWorkerProcess": true,
                "webSocketsEnabled": false,
                "alwaysOn": false,
                "managedPipelineMode": "Integrated",
                "virtualApplications": [
                    {
                        "virtualPath": "/",
                        "physicalPath": "site\\wwwroot",
                        "preloadEnabled": false
                    }
                ],
                "loadBalancing": "LeastRequests",
                "experiments": {
                    "rampUpRules": []
                },
                "autoHealEnabled": false,
                "cors": {
                    "allowedOrigins": [
                        "https://functions.azure.com",
                        "https://functions-staging.azure.com",
                        "https://functions-next.azure.com"
                    ],
                    "supportCredentials": false
                },
                "localMySqlEnabled": false,
                "managedServiceIdentityId": 4749,
                "ipSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 1,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 1,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictionsUseMain": false,
                "http20Enabled": false,
                "minTlsVersion": "1.2",
                "ftpsState": "AllAllowed",
                "reservedInstanceCount": 0
            }
        },`
1. What should've happened?

it should set python version

1. What's the content of your `serverless.yml` file?

(https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/azure-python/serverless.yml)

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

The deployment is successful, the error only happens after deployment. The errors are not logged in the serverless dashboard, for some reason

Similar or dependent issues:

- #12345

**Comment by ihmu** [comment]
I have the same problem ;(

**Comment by FirstInternetUser** [comment]
Is there an update as to how to resolve this issue? I am experiencing it too.

**Comment by FirstInternetUser** [comment]
Solved the problem. I had missed the step 
` npm install`

**Comment by medikoo** [comment]
Closing, as `sls create` is no longer recommended for project setup. Rely on `sls` and npm dependencies will be auto installed for you
