### ISSUE TITLE
`sls logs` while printing long log strings messed up next strings

### ISSUE THREAD

**Issue by VadimGuslistov** [serverless/serverless#7289]
![image](https://user-images.githubusercontent.com/753282/73743693-3a5fa280-4760-11ea-8b92-d45a94537126.png)

**Comment by medikoo** [comment]
@VadimGuslistov thanks for report. What exactly is _Messed Up_?

Do you expect to see timestamps at start of each line? Note they do come up from logs, so if logs do not show timestamps `sls logs` also won't output them.

**Comment by VadimGuslistov** [comment]
@medikoo thank for help. There is a part of ClowdWatch Logs:

2020-02-04T11:36:57.676Z	c1338c83-f493-4bd2-8395-8fcb84bb87e1	INFO	Validator: Request routing by URL from QR-code
2020-02-04T11:36:57.677Z	c1338c83-f493-4bd2-8395-8fcb84bb87e1	INFO	Logic: Request SPOT context
2020-02-04T11:36:57.696Z	c1338c83-f493-4bd2-8395-8fcb84bb87e1	INFO	Adapter: Request SPOT context by type-subtype & id: { id: [32m'HkP0JNJk1l'[39m, type: [32m'item'[39m }
2020-02-04T11:36:57.696Z	c1338c83-f493-4bd2-8395-8fcb84bb87e1	INFO	Repository: Request SPOT context by type & id
2020-02-04T11:36:57.696Z	c1338c83-f493-4bd2-8395-8fcb84bb87e1	INFO	Client DB: Executing query:
{ ExpressionAttributeNames: { [32m'#typesubtype'[39m: [32m'type-subtype'[39m },
  ExpressionAttributeValues: { [32m':id'[39m: [32m'HkP0JNJk1l'[39m, [32m':typesubtype'[39m: [32m'item'[39m },
  KeyConditionExpression: [32m'#typesubtype = :typesubtype and id = :id'[39m,
  TableName: [32m'restocks-dev'[39m }

**Comment by medikoo** [comment]
@VadimGuslistov If I see correctly your logs contain ANSI codes, hence then it messes output of `sls logs` (as it doesn't have any builtin stripping of ANSI codes).

Ideally logs as output to CloudWatch should be free from ANSI codes (there's no support there for it), and to avoid any side issues, or extra complexity, I wouldn't add any ANSI codes stripping functionality to `sls logs`

**Comment by VadimGuslistov** [comment]
Thanks a lot @medikoo.
I solved the problem by changing the runtime version from version 10 of NodeJS to 11.
I found a solution to the problem in this article:
https://medium.com/@hichaelmart/aws-lambda-nodejs10-x-fixed-e99ba0575bd2

**Comment by medikoo** [comment]
Thanks @VadimGuslistov for info. If you feel you're issue was solved, please close the issue.
