### ISSUE TITLE
ALB event Target Group names should have a prefix and not be completely random

### ISSUE THREAD

**Issue by isen-ng** [serverless/serverless#7292]
# Feature Proposal

## Description

Context:
I see the issue: https://github.com/serverless/serverless/issues/6320 and the original implementation is to use the `<lambda-function-name>-<stage>` and this resulted in non-unique names for target groups.

I also see the fix: https://github.com/serverless/serverless/pull/6322 to simply use a fixed length hash to generate the target group's name.

Problem:
The problem with this approach is that we no longer have (semi) predictable names. From a resource management point of view, an AWS account admin would require additional AWS API calls to retrieve target group tags before he/she can manage them properly. In a large AWS account, these additional API calls may amount to significant costs and even account-wide API call throttling.

The second problem with this approach is that we cannot give granular permissions to our user/codebuild continuous deployment to only create or delete target groups for restricted names.

eg. a target group arn created by serverless looks like: `arn:aws:elasticloadbalancing:us-east-1:<redacted>:targetgroup/9ff09e8a342a4186247803c28a7b67a3/f7eb2224b059657e`

This means that I MUST give permissions of `*`.

```
  statement {
    actions = [
      "elasticloadbalancing:CreateTargetGroup",
      "elasticloadbalancing:DeleteTargetGroup",
    ]

    resources = [
      "arn:aws:elasticloadbalancing:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:targetgroup/*",
    ]
  }
```

This will not sit well with security audits. They would prefer a more restrictive policy like

```
"arn:aws:elasticloadbalancing:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:targetgroup/${my_resource_prefix}*"
```

Proposal:
Introduce an `alb.targetPrefix` to be prepended to your fixed length hash. Total length should still be truncated to 32 characters and `alb.targetPrefix` should have a max length of... maybe 10 or 15 characters.

Similar or dependent issues:

- https://github.com/serverless/serverless/pull/6322
- https://github.com/serverless/serverless/issues/6320

**Comment by medikoo** [comment]
@isen-ng thanks for report.

Indeed this could be improved.

Maybe good middle ground would be to do: `` `${serviceName}${md5hash}`.slice(0, 32) `` ?

**Comment by isen-ng** [comment]
The problem with using `${serviceName}${md5hash}.slice(0, 32)` is that, if the serviceName itself exceeds 32 characters, you will still end up with duplicate target group names.

**Comment by medikoo** [comment]
@isen-ng Maybe then do:

```javascript
const prefix = userPrefix || serviceName.slice(0, 16);
targetGroupName = `${prefix}${md5hash}`.slice(0, 32)
```

**Comment by isen-ng** [comment]
@medikoo Your proposed solution works.

Just curious, why did you propose to want to continue to use the `serviceName` as a prefix as opposed to no prefix?

eg

```
md5hash = md5(serviceName);
targetGroupName = `${userPrefix}${md5hash}`.slice(0, 32);
```

**Comment by medikoo** [comment]
> Just curious, why did you propose to want to use the (truncated) serviceName as a prefix as opposed to no prefix?

As this for most cases will address issue you're reporting without any extra configuration tweaks (you may rely on service name as prefix, instead of setting your own).

> This behaviour is backward compatible with the current implementation.

 But indeed, my proposal could be breaking. If it is, we definitely should go with what you proposed.
