### ISSUE TITLE
Error: Export 'mynube-api-dev-ServerlessAliasReference' does not exist.

### ISSUE THREAD

**Issue by bryanowen7** [serverless/serverless#7302]
# Bug Report

1. What did you do?
I created a Serverless project and when I try to deploy it, I get the error: "Export 'mynube-api-dev-ServerlessAliasReference' does not exist."

1. What happened?
I get the error: "Export 'mynube-api-dev-ServerlessAliasReference' does not exist."

1. What should've happened?
It should have deployed my function correctly.

1. What's the content of your `serverless.yml` file?
`service: mynube-api

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: us-west-2
    memorySize: 128
    deploymentBucket:
        name: mynube-lambdas
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
            - 'ses:SendTemplatedEmail'
            - 'ses:SendRawEmail'
            - 's3:GetObject'
            - 's3:GetObjectAcl'
            - 's3:PutObject'
            - 's3:PutObjectAcl'
            - 's3:DeleteObject'
          Resource:
            - '*'

package:
    excludeDevDependencies: false
    individually: true
    exclude:
        - '*/**'
    include:
        - 'src/utils/funciones.js'
        - 'src/utils/reportError.js'
        - 'src/utils/reportAltError.js'
        
functions: ${file(./serverless-config/lambda-functions.yml)}

# Lista de plugins para Serverless Framework
plugins:
    - serverless-aws-alias # Alias (Versioning)
    #- serverless-layers # Lib management.`

**Comment by akantcheff** [comment]
I have this same issue with serverless 1.63.0. Downgrading to 1.61.2 solves the problem. An issue is also opened on serverless-aws-alias github: https://github.com/serverless-heaven/serverless-aws-alias/issues/181

**Comment by bryanowen7** [comment]
> I have this same issue with serverless 1.63.0. Downgrading to 1.61.2 solves the problem. An issue is also opened on serverless-aws-alias github: [serverless-heaven/serverless-aws-alias#181](https://github.com/serverless-heaven/serverless-aws-alias/issues/181)

This worked, thanks for the help, you probably saved me a few hours of research

**Comment by lkolchin** [comment]
Why was this issue closed if no bugfix provided?

**Comment by bryanowen7** [comment]
> Why was this issue closed if no bugfix provided?

This issue was a duplicate of [serverless-heaven/serverless-aws-alias#181](https://github.com/serverless-heaven/serverless-aws-alias/issues/181)
