### ISSUE TITLE
deploy too slow 部署太慢了!可以手动传然后给url部署吗？

### ISSUE THREAD

**Issue by birdsofsummer** [serverless/serverless#7308]
uploading  too slow!
can i upload the .severless/xxx.zip file manully to cos or somewhere else
then
serverless --debug --url https://xxxx/xxx.zip 
😰😰😰

**Comment by tinafangkunding** [comment]
hi 您好，感谢反馈！您使用中文提issue也可以的。这边的维护者可以通过google 翻译，或者中文的社区开发者来和您一起解决问题。

部署慢有可能是以下一些原因造成的：
- 网络问题
- 依赖的npm包比较大
- 代码包或者资源比较大，上传慢
...

您可以提供一下具体的部署项目地址，以及您的对应配置吗？这样可以方便进一步查看在哪里比较慢。
另外，使用serverless --debug的时候，您可以给最慢的步骤当前的命令行截图反馈下，有利于进一步查看。

后面也有计划通过云端托管component，以及增加cos上传的进度条等，优化部署慢的问题，敬请期待！

**Comment by birdsofsummer** [comment]
我卡在cos上传那一步了
我那个压缩包是7兆 
但是传不动
重试了n次才部署上

建议全部采用cos分片上传sliceUploadFile 
或者调小一下阈值,打印一下进度
你们现在是
<20兆普通上传
>20兆分片上传

node_modules/@serverless/tencent-scf/library/deployFunction.js
285行

```javascript
    if (fs.statSync(filePath).size <= 1 * 1024 * 1024) {
      const objArgs = {
        Bucket: cosBucketNameFull,
        Region: region,
        Key: key,
        Body: fs.createReadStream(filePath),
        ContentLength: fs.statSync(filePath).size
      }
      handler = util.promisify(this.cosClient.putObject.bind(this.cosClient))
      try {
        await handler(objArgs)
      } catch (e) {
        throw e
      }
    } else {
      const sliceArgs = {
        Bucket: cosBucketNameFull,
        Region: region,
        Key: key,
        FilePath: filePath
      }
      handler = util.promisify(this.cosClient.sliceUploadFile.bind(this.cosClient))
      try {
        await handler(sliceArgs)
      } catch (e) {
        throw e
      }
    }
    return {
      CosBucketName: bucketName,
      CosObjectName: '/' + key
    }

```

**Comment by tinafangkunding** [comment]
很赞的建议，非常感谢! @anycodes 辛苦看一下

**Comment by medikoo** [comment]
@birdsofsummer  thanks for report. To allow all community members to participate, can we use just English in context of this repository, when reporting issues?
