### ISSUE TITLE
Capture Node.js 8.10 as provider runtime when deploying AWS Lambda function 

### ISSUE THREAD

**Issue by luomanke** [serverless/serverless#7313]
# Feature Proposal
Capture Node.js 8.10 as provider runtime when deploying AWS Lambda function since AWS Lambda deprecated this version as runtime. 

## Description
When deploying AWS Lambda function with Node.js 8.10 as runtime, no error was reported, but the function is not updated. 

Reference: [Node.js 12.x runtime now available in AWS Lambda](https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/) -> After January 6, 2020, you can no longer create a Node.js 8.10 Lambda function and the ability to update will be disabled after February 3, 2020.

**Comment by rdsedmundo** [comment]
I believe the best behavior is to let it as-is, which is to allow the deployment and let AWS Lambda service fail by itself. There's no check for previous runtimes either (4.x, 6.x).

**Comment by luomanke** [comment]
Right. It should be handled on AWS side.
