### ISSUE TITLE
Binary Version install is slow in China

### ISSUE THREAD

**Issue by tinafangkunding** [serverless/serverless#7332]
# Feature Proposal

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When using Binary version to install serverless, I use `curl -o- -L https://slss.io/install | bash` command, and it succeeds, while when I want to upgrade to the latest version, it takes a very long time and the connection failed in China. The logs look like this:

安装二进制的 serverless framework 可以成功，但是使用升级命令很慢，卡在了下面的步骤：

```
$ serverless upgrade
Serverless: Downloading new version...
```

After that, I want to remove the old binary version and try to install the latest version via `npm install`, but it failed. When the Framework version is "standalone", I cannot uninstall nor switch to npm version. Do we have plans to `remove` standalone serverless framework, or accelerate the upgrade process, and get more detailed outputs?

此外，在升级失败后，我希望切换成npm的方式安装，但是不生效。而且没有办法移除掉二进制的安装包。后续是否会支持类似 remove的命令，删除二进制包呢？或者让升级命令更快一些，输出更多的日志？

```
$ serverless -v
Framework Core: 1.60.5 (standalone)
Plugin: 3.2.7
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by medikoo** [comment]
@tinafangkunding thanks for report.

> When using Binary version to install serverless (...) it succeeds, while when I want to upgrade to the latest version, it takes a very long time and the connection failed in China

Technically in both cases binary is downloaded from same url, so it's wierd that performance of both methods is different for you (do you reproduce it in all cases, or maybe it's just occasional glitch?)

> When the Framework version is "standalone", I cannot uninstall

You can uninstall _standalone_ with `sls uninstall` command. Still note that if you had npm installed version, it'll surface then (so technically `sls` command may still be available but then it'll be from global npm installation)

> it takes a very long time and the connection failed in China

I think due to nature of China internet, best would be to provide special mirror for China, and rely on it for all installs and upgrades from China, it's just not that trivial to setup, so it may take some time to have it (please raise it in Slack).

**Comment by tinafangkunding** [comment]
Thanks for replying! Now I can uninstall serverless standalone version. It would be better if I can find the command in docs, or in `serverless -h`.
https://serverless.com/framework/docs/getting-started/

**Comment by medikoo** [comment]
>  It would be better if I can find the command in docs, or in serverless -h.

It is listed in `serverless -h` (still appears only when you're using standalone), but yes we can improve online docs to have it as well.

**Comment by AnthonyWC** [comment]
> Technically in both cases binary is downloaded from same url, so it's wierd that performance of both methods is different for you (do you reproduce it in all cases, or maybe it's just occasional glitch?)

Looks like the bash script grabs the binary directly from github; does sls upgrade do the same?  If it does, maybe sls upgrade does some sort of check that is timing out?

**Comment by medikoo** [comment]
>  If it does, maybe sls upgrade does some sort of check that is timing out?

It first checks what's the latest version: https://github.com/serverless/serverless/blob/9eba2187f9565b39d31e88572c06ea2ccaa4bade/lib/plugins/executable/index.js#L45 

Then if it's not newest it downloads: https://github.com/serverless/serverless/blob/9eba2187f9565b39d31e88572c06ea2ccaa4bade/lib/plugins/executable/index.js#L81-L83
          
Hence maybe `https://api.github.com` calls are subject to delays

**Comment by medikoo** [comment]
@tinafangkunding I think we can improve situation in China, if Tencent on your side prepares some simple API, which we could use to upload binaries directly to China, and then download it from there for Chinese users.

I imagine a possible API endpoints as:

#### `POST /release`

Publish a release, where release is e.g. following object:

```json
{
  "version": "1.65.0",
  "tag": "latest",
}
```

On server side it should create a new release with `latest` tag and remove that tag from any previous release that had it.

Returns release meta as:

```json
{
  "id": "{releaseId}",
  "version": "1.65.0",
  "tag": "latest",
  "assets": []
}
```

#### `POST /release/{releaseId}/assets?name=${assetName}`

Upload a release asset (binary), where name reflects filename, and is also used to differentiate between OS distributions, e.g. `serverless-mac` or `serverless-win.exe`.

Returns asset meta as:

```json
{
  "id": "{assetId}",
  "name": "serverless-mac",
  "url": "https://..."
}
```

**Note:** URL to binary must be publicly accessible (installation scripts on developer machines will attempt to download binary from that location)

#### `GET /release/latest`

Return metadata of release that's tagged as `latest`, where response could be as:

```json
{
  "id": "{releaseId}",
  "version": "1.65.0",
  "tag": "latest",
  "assets": [
    { "id": "{assetId}", "name": "serverless-linux", "url": "https://..." },
    { "id": "{assetId}", "name": "serverless-mac", "url": "https://..." },
    { "id": "{assetId}", "name": "serverless-win.exe", "url": "https://..." }
  ]
}
```

**Comment by tinafangkunding** [comment]
Got it, thanks @medikoo, our engineer @yugasun will review the solution and we'll get further discussion about it.

**Comment by yugasun** [comment]
@tinafangkunding Now， I‘m developing a solution:
1. I create a `mirror` of `serverless` repo on `Coding`, and it provide an `api trigger` method.
2. When `serverless` deploy a new version, the deploy script can request the `mirror` repo ci
3. The mirror repo ci will auto run `pkg:build`, and auto upload `binary` to `tencent cos`
4. Then we will provide a `cos download link` for China developers.

**Comment by medikoo** [comment]
@yugasun I think it'll be better here if we upload a binaries to both GitHub and Tencent COS, from same point (we do it exactly here: https://github.com/serverless/serverless/blob/ee290018bba3eae95aa9951131dbe8af5ba00bf8/.travis.yml#L207 so in this context we eventually need to configure second upload destination in this script: https://github.com/serverless/serverless/blob/ee290018bba3eae95aa9951131dbe8af5ba00bf8/scripts/pkg/upload.js

Otherwise, if package binary twice, it imposes a risk of binaries being different (one being ok, other broken by bug etc).

So ideally if you just prepare above API, and then it'll be very easy to adapt the change in a Framework

**Comment by yugasun** [comment]
@medikoo Yeah, I tested on Travis CI, I just uploaded binary file to Tencent COS directly. Unfortunately it go through a timeout problem. So I think make a mirror repo and build in China CI Server can solve this problem.

This is the CI test: https://travis-ci.com/github/serverless-plus/serverless/jobs/301461847

**Comment by medikoo** [comment]
Thanks @yugasun for clarification. Indeed in that case we can't probably count that we'd be able to upload binary from Travis CI to COS.

As you suggested, prepare on your side a binary packager and uploader that'll work in China region, and which should be triggered by GitHub release (not by commit to `master`).

Then just provide a us with a single url endpoint which in all cases should point to latest binary builds.

As Windows binary installation is handled by Chocolatey package manager, I believe we need to focus here purely on `serverless-macos-x64` and `sererless-linux-x64` binary builds

**Comment by tinafangkunding** [comment]
Hi @medikoo I wonder after we provide the mirror of the binary package, how to recognize which URL to use when they run the command `curl -o- -L https://slss.io/install | bash`? Will we add some code in the script to identify the Chinese users?

**Comment by medikoo** [comment]
@tinafangkunding I think we can follow similar check as it's done  in `serverless-tencent-tools` https://github.com/serverless-tencent/serverless-tencent-tools/blob/3c1cabbdb21c0b3ba37248b9c2f609ec552bf8fc/sdk/others/isInChina.js#L12

So in bash script I will confirm on timezone of a user, if it's a China timezone we will assume user is in China.

That's I guess best we can do

**Comment by medikoo** [comment]
btw what do following command outputs for you (?):

```bash
date +"%Z %z"
```

**Comment by yugasun** [comment]
@medikoo `CST +0800`

**Comment by medikoo** [comment]
> @medikoo CST +0800

Thanks @yugasun. are you in China? Your output is suprising, as `CST` is a timezone in US.

And what value do you have in `LC_CTYPE` variable?

Are you on macOS or linux?

**Comment by yugasun** [comment]
@medikoo Because I use English for my Mac. And my `LC_CTYPE` is `UTF-8`.

**Comment by medikoo** [comment]
Sorry, I take it back CST can easily be confused. It appears timezone in China is named same way

**Comment by medikoo** [comment]
In script we will probably confirm both `CST` and `+0800` part, that should work best

**Comment by yugasun** [comment]
> confirm

That's great.

**Comment by medikoo** [comment]
@yugasun great thanks for preparing a mirror! PR with support for new mirror: https://github.com/serverless/serverless/pull/7521 we will publish it with next release
