### ISSUE TITLE
maximumRetryAttempts for AWS Lambdas

### ISSUE THREAD

**Issue by cortopy** [serverless/serverless#7334]
# Feature Proposal

After the release of maximumRetryAttempts for [AWS Lambda Functions](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-max-retry-attempts-event-age-asynchronous-invocations/), it would be nice to have this as an option in the serverless config file

I can see that  this options was added for [streams](https://github.com/serverless/serverless/pull/7040), but it would be nice to have it for Lambdas too.

**Comment by medikoo** [comment]
@cortopy thanks for report. I believe it's a duplicate of #7012, therefore I'm closing it
