### ISSUE TITLE
Load local credential config when invoke local --docker

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#7343]
# Feature Proposal

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

If there is the proper credential setting in local, the handler which access to AWS service like the following should work when `invoke local --docker`.

```
"use strict";

const AWS = require("aws-sdk");

module.exports.hello = async event => {
  const ssm = new AWS.SSM();
  console.log(await ssm.getParameter({ Name: "test" }).promise());
};
```

`invoke local` (without `--docker`) and [sam local invoke](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-invoke.html) support this, but `invoke local --docker` doesn't.

**Comment by medikoo** [comment]
I believe it comes from fact that docker is a different isolated environment, therefore it doesn't share same env variables as CLI environment in which you're running `sls invoke local --docker`

**Comment by frozenbonito** [comment]
It is possible to load credentials into the container via  `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` environment variables.
`AWS SAM CLI` also uses docker, and loads credentials in this way.

Let me crete a pull request.
