### ISSUE TITLE
Application Load Balancer Cognito Authorization

### ISSUE THREAD

**Issue by shadrech** [serverless/serverless#7354]
# Feature Proposal

## Description

You can configure an ALB to have built in authentication (https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/) but is there a way to configure this via `serverless.yml`?

**Comment by medikoo** [comment]
I don't think it's supported now: https://serverless.com/framework/docs/providers/aws/events/alb/

PR's welcome!

**Comment by shadrech** [comment]
I can attempt at a PR. Any guidelines on how to contribute to serverless project?

**Comment by medikoo** [comment]
Thank you @shadrech 

> Any guidelines on how to contribute to serverless project?

Follow: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md

And ensure to read and follow PR template when proposing an improvement: https://github.com/serverless/serverless/blob/master/.github/PULL_REQUEST_TEMPLATE.md (be sure to expand "Useful scripts" section)

**Comment by shadrech** [comment]
Working on it 👍🏾

**Comment by shadrech** [comment]
https://github.com/serverless/serverless/pull/7372
