### ISSUE TITLE
eventBridge generated rule name exceeds max length (64 chars)

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#7356]
# Bug Report

## Description

eventBridge custom resource provisioning generates eventBridge rules whose name can exceed the maximum allowed 64 chars
![image](https://user-images.githubusercontent.com/23530626/74729148-43fb0700-5244-11ea-86a9-a8ccf049bec1.png)

The current name generation function uses `${service.name}-${stage}-${function.name}-rule-${increment}` which might easily violates AWS eventBridge rules validation constraints.

Would be happy to help with a PR on that specific matter. My idea would be to implement truncate of generated ruleName at this point 
https://github.com/serverless/serverless/blob/59634e7d926e1c7d5173e34e07e14bfdebf49dc9/lib/plugins/aws/package/compile/events/eventBridge/index.js#L41

WDYT ?

**Comment by medikoo** [comment]
@fredericbarthelet thanks for reporting! PR is highly welcome.

I believe that to not break things, we need to ensure same name (if it fits 64), and propose a trimmed alternative only if it's othwerise (note that `{idx}` should probably fit in, to ensure no duplicate rule names)
