### ISSUE TITLE
serverlessrc keeps changing

### ISSUE THREAD

**Issue by c0d3d** [serverless/serverless#7369]
# Bug Report

Seems like every time I do anything with serverless, it changes my `~/.serverlessrc`

## Description

I have all my rc files in source control, and I want this one in source control as well because I want to set `trackingDisabled`. Annoyingly, every time I do anything with serverless, the file changes. My `frameworkId` changes, and it **resets** `trackingDisabled` to `false`. This is borderline malicious. I've gone out of my way to opt out of user tracking (some would say opt-out is already malicious), and serverless automatically re-enables it silently.

I don't think the file should change after creation (looks like userId/frameworkId are UUIDs, why are they changing anyways?), and I especially don't think that it should be re-enabling tracking.

Example change:
```diff
 {
   "userId": null,
-  "frameworkId": "<redacted>",
-  "trackingDisabled": true,
-  "enterpriseDisabled": true,
+  "frameworkId": "<different redacted>",
+  "trackingDisabled": false,
+  "enterpriseDisabled": false,
   "meta": {
-    "created_at": 1581697504,
+    "created_at": 1582149473,
     "updated_at": null
   }
-}
+}
```

**Comment by medikoo** [comment]
@c0d3d thanks for reporting. That's indeed weird.

I do not observe such behavior on my side. Does it happen after you toggle some settings, or every time even if you do not touch the file?

If so, can you describe the flow (which commands force file to be recreated), and say which version of `serverless` exactly you're using?

**Comment by c0d3d** [comment]
It actually happens *any* time I use serverless for anything.
Even running `sls --version` causes this issue for me (so I can get 2 birds with one stone with this example xD)
```
$ sls --version
Framework Core: 1.52.0
Plugin: 2.0.0
SDK: 2.1.1
```

Here is the output with `SLS_DEBUG`:
```
$ SLS_DEBUG="*" sls --version
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command create
Serverless: Load command create:test
Serverless: Load command create:function
Serverless: Load command invoke
Serverless: Load command invoke:test
Serverless: Load command deploy
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Framework Core: 1.52.0
Plugin: 2.0.0
SDK: 2.1.1
```

Some more environment info:
```
Operating System:          darwin
Node Version:              12.12.0
```

**Comment by c0d3d** [comment]
@medikoo I found the issue, my .serverlessrc is actually a symlink, and the check to see if it exists is done using `lstat` which doesn't follow symlinks. I've made a PR to allow symlinks for the config file.

**Comment by medikoo** [comment]
> @medikoo I found the issue, my .serverlessrc is actually a symlink

@c0d3d thanks for reporting. Why do you have it as symlink? Note that Framework when updating the config will save file at this specific path (it won't follow symlink), so even if we relax validation check, then you're symlink at first update attempt will be replaced with file

**Comment by c0d3d** [comment]
@medikoo, the file is symlinked into a directory that i have in source control. I just clone the repo and symlink all the necessary files into it.

What do you mean by "updating it"? Whatever it was doing before was not overwriting the file (it was writing through the symlink, which is why i was able to see the changes when i was about to commit my dotfiles repo. I think it will, in general, not break the symlink.

If a process opens the file for writing, it just truncates the file, and writes new bytes into it, so it still stays linked. Just about the only thing that it could do to break it is delete the link and then open the file so that it gets created.

**Comment by medikoo** [comment]
> it was writing through the symlink

To be honest I didn't expect that (was sure it'll overwrite the symlink with file), but you're right `writeFile` follows symlinks.

Great thanks for claryfing that. In light of that your patch makes perfect sense.

**Comment by RichardBronosky** [comment]
@c0d3d what is `frameworkId` and why did you redact it?

**Comment by c0d3d** [comment]
@RichardBronosky I don't know what it is, and I wasn't sure if it was sensitive, so I removed it from my diff.
