### ISSUE TITLE
The dependency gradle-wrapper.jar has a number of security flaws as identified by a VeraCode static scan

### ISSUE THREAD

**Issue by iamle0pard** [serverless/serverless#7370]
# Bug Report

## Description

If you run a VeraCode static security scan against the serverless folder and files within 'node_modules' you will see that there are a number of flaws identified due to 'gradle-wrapper.jar'.  

Here are all the locations that 'gradle-wrapper.jar' exists:

- node_modules\serverless\lib\plugins\create\templates\aws-clojure-gradle\gradle\wrapper
- node_modules\serverless\lib\plugins\create\templates\aws-clojurescript-gradle\gradle\wrapper
- node_modules\serverless\lib\plugins\create\templates\aws-groovy-gradle\gradle\wrapper
- node_modules\serverless\lib\plugins\create\templates\aws-java-gradle\gradle\wrapper
- node_modules\serverless\lib\plugins\create\templates\aws-kotlin-jvm-gradle\gradle\wrapper
- node_modules\serverless\lib\plugins\create\templates\aws-kotlin-nodejs-gradle\gradle\wrapper

The following flaws have been identified:
- http://cwe.mitre.org/data/definitions/73.html
  - CWE-73: External Control of File Name or Path
- http://cwe.mitre.org/data/definitions/327.html
  - CWE-327: Use of a Broken or Risky Cryptographic Algorithm
- http://cwe.mitre.org/data/definitions/404.html
  - CWE-404: Improper Resource Shutdown or Release

From the scan report, these are the filenames identified:
- ExclusiveFileAccessManager.java
- GradleUserHomeLookup.java
- GradleWrapperMain.java
- Install.java
- PathAssembler.java
- WrapperExecutor.java

Here are the 19 specific locations identified where the flaws exist:
- org/.../wrapper/PathAssembler.java 65
- .../ExclusiveFileAccessManager.java 39
- .../GradleUserHomeLookup.java 29
- .../GradleUserHomeLookup.java 32
- .../GradleUserHomeLookup.java 34 
- org/.../GradleWrapperMain.java 101
- org/.../GradleWrapperMain.java 117
- org/.../wrapper/Install.java 50
- org/.../wrapper/Install.java 59 
- org/.../wrapper/Install.java 224 
- org/.../wrapper/Install.java 227 
- org/.../wrapper/Install.java 228 
- org/.../wrapper/Install.java 231  
- org/.../wrapper/PathAssembler.java 43
- org/.../wrapper/PathAssembler.java 44
- org/.../wrapper/PathAssembler.java 95
- org/.../WrapperExecutor.java 70
- org/.../wrapper/Install.java 171
- org/.../wrapper/Install.java 174

Currently using serverless version: **1.61.3**

**Comment by medikoo** [comment]
@iamle0pard great thanks for reporting. We're definitely open for PR that improves template so it doesn't share any security issues.

**Comment by d3pr3553d** [comment]
> # Bug Report
> ## Description
> If you run a VeraCode static security scan against the serverless folder and files within 'node_modules' you will see that there are a number of flaws identified due to 'gradle-wrapper.jar'.
> 
> Here are all the locations that 'gradle-wrapper.jar' exists:
> 
> * node_modules\serverless\lib\plugins\create\templates\aws-clojure-gradle\gradle\wrapper
> * node_modules\serverless\lib\plugins\create\templates\aws-clojurescript-gradle\gradle\wrapper
> * node_modules\serverless\lib\plugins\create\templates\aws-groovy-gradle\gradle\wrapper
> * node_modules\serverless\lib\plugins\create\templates\aws-java-gradle\gradle\wrapper
> * node_modules\serverless\lib\plugins\create\templates\aws-kotlin-jvm-gradle\gradle\wrapper
> * node_modules\serverless\lib\plugins\create\templates\aws-kotlin-nodejs-gradle\gradle\wrapper
> 
> The following flaws have been identified:
> 
> * http://cwe.mitre.org/data/definitions/73.html
>   
>   * CWE-73: External Control of File Name or Path
> * http://cwe.mitre.org/data/definitions/327.html
>   
>   * CWE-327: Use of a Broken or Risky Cryptographic Algorithm
> * http://cwe.mitre.org/data/definitions/404.html
>   
>   * CWE-404: Improper Resource Shutdown or Release
> 
> From the scan report, these are the filenames identified:
> 
> * ExclusiveFileAccessManager.java
> * GradleUserHomeLookup.java
> * GradleWrapperMain.java
> * Install.java
> * PathAssembler.java
> * WrapperExecutor.java
> 
> Here are the 19 specific locations identified where the flaws exist:
> 
> * org/.../wrapper/PathAssembler.java 65
> * .../ExclusiveFileAccessManager.java 39
> * .../GradleUserHomeLookup.java 29
> * .../GradleUserHomeLookup.java 32
> * .../GradleUserHomeLookup.java 34
> * org/.../GradleWrapperMain.java 101
> * org/.../GradleWrapperMain.java 117
> * org/.../wrapper/Install.java 50
> * org/.../wrapper/Install.java 59
> * org/.../wrapper/Install.java 224
> * org/.../wrapper/Install.java 227
> * org/.../wrapper/Install.java 228
> * org/.../wrapper/Install.java 231
> * org/.../wrapper/PathAssembler.java 43
> * org/.../wrapper/PathAssembler.java 44
> * org/.../wrapper/PathAssembler.java 95
> * org/.../WrapperExecutor.java 70
> * org/.../wrapper/Install.java 171
> * org/.../wrapper/Install.java 174
> 
> Currently using serverless version: **1.61.3**

I agree. Same findings. Is there a patched version or is it still in progress?

**Comment by medikoo** [comment]
@d3pr3553d PR with patch is welcome

**Comment by cgomestw** [comment]
somebody? :(

**Comment by medikoo** [comment]
@cgomestw you? :)

**Comment by cgomestw** [comment]
I not using java/gradle template on my project.

But I think this need to upgrade the AWS SDK on this line https://github.com/serverless/serverless/blob/5c1b006317fdc230db4a669eb4691ddd51801522/lib/plugins/create/templates/aws-java-gradle/build.gradle#L12 with this package updated https://mvnrepository.com/artifact/com.amazonaws/aws-lambda-java-core.

For gradle, I think it need to change jar on the lib folter to the last version and change this line too: https://github.com/serverless/serverless/blob/5c1b006317fdc230db4a669eb4691ddd51801522/lib/plugins/create/templates/aws-java-gradle/build.gradle#L41

For workaround on Sonar, I delete this template folder, because I not need it.

**Comment by cgomestw** [comment]
This fix on groovy fixed the problem: https://github.com/serverless/serverless/commit/5e2e1a366a4894bd1c33123bae6fe99cfc9ded7f
