### ISSUE TITLE
openapi (swagger codegen)

### ISSUE THREAD

**Issue by jgroom33** [serverless/serverless#7376]
# openapi (swagger codegen)

## Description

Generate a set of scaffolded files based on an openapi spec.

Features:

* Generate lambda functions (controllers)
* Generate serverless.yml
* Request/response validation: [python validation](https://github.com/p1c2u/openapi-core/issues/204)

Single page app scaffolding:

* Generate Vue App
* S3 sync and resource example
* Dynamo table resource

Similar or dependent issues:

- #7052

**Comment by jgroom33** [comment]
related: https://github.com/p1c2u/openapi-core/issues/204

This issue if implemented would provide openapi request/response validation

**Comment by wing328** [comment]
You may consider using OpenAPI Generator instead. 

[Q&A](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md)

Disclosure: I'm the top contributor to both Swagger Codegen and OpenAPI Generator.

**Comment by jgroom33** [comment]
Thanks @wing328 ... I plan on issuing a PR to open API generator.  I noticed there is quite a bit of bifurcation in the codegen world.  And it is not clear what each online tool uses as a codegen source.

Can you provide guidance on each of these:
https://editor.swagger.io
https://app.swaggerhub.com
https://mermade.github.io/openapi-gui/

Specifically, how does each project receive its codegen source?
Said another way, if a PR is issued to OpenAPI Generator, which online tools will be able to leverage that?

**Comment by wing328** [comment]
> https://editor.swagger.io
> https://app.swaggerhub.com

From what I know, these 2 use Swagger Codegen. I would suggest checking with them directly to confirm as I can't speak on their behalf.

> https://mermade.github.io/openapi-gui/

I think this one is using OpenAPI Generator (but of course better check with the tool owner to confirm).

We (OpenAPI Generator) also have online services (but without GUI): https://github.com/OpenAPITools/openapi-generator#33---online-openapi-generator. Please check it out to see if it meets your requirement.

**Comment by exoego** [comment]
> Generate serverless.yml

For this purpose, I am using [serverless-import-swagger](https://www.npmjs.com/package/serverless-import-swagger) which generates one or multiple `serverless.yml` from Swagger/OpenAPI files.
