### ISSUE TITLE
v0.5 component create requires interaction

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#738]
TL;DR:
Executed: ```slsDev component create -h```
Observed: 
```
Creates scaffolding for a new serverless component.
usage: serverless component create

  -r, --runtime 
	Runtime of your new component. Default: nodejs
```
Expected:
```
Creates scaffolding for a new serverless component.
usage: serverless component create

  -n, --name 
	The name for your new component.
  -r, --runtime 
	Runtime of your new component. Default: nodejs
```

Maybe this is a choice that was intentionally made but the command "slsDev component create -h" only lists the "-r" option to supply the runtime.  This means you must go through interactive mode.  Not a big deal, the automated creation of projects, functions, et cetera seems of little value but it used to be a possibility, if only so that you could get a sense of how to use the command before embarking upon its use.

**Comment by ac360** [comment]
Thanks @erikerikson 

We're making a change in V0.5 to remove components in favor of something better.

**Comment by erikerikson** [comment]
Cool, what's the "better"?

**Comment by ac360** [comment]
Almost done with it.  Will show you shortly :)
