### ISSUE TITLE
Creating Access Role in Serverless Dashboard does not detect serverless deploy for project

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [serverless/serverless#7399]
I created an Access Role in Serverless Dashboard. I gave it a name and then successfully linked it to my AWS Account. In fact, it created an IAM Role, with an ARN that looks something like the following:

arn:aws:iam::xxxxxxxx:role/xxxxRole

where 'x' replaces the actual characters.

But when I run sls deploy for my project, I get the following error:

$  sls deploy --verbose --stage dev --region us-east-2

  Serverless Error ---------------------------------------
 
  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.

So I added the following to ~/.aws/credentials:

[default]
source_profile = my-profile
role_arn = arn:aws:iam::xxxxxxxx:role/xxxxRole

That did not help anything. According to the Serverless Documentation, once I create the Access Role, then it should automatically "identify the deployment profile associated with the application or stage and it will generate the AWS Access Keys using the associated AWS Access Role automatically."

Note in apps > stages, I configured a stage called dev and linked it to the profile as well.

But this did not happen. How am I supposed to get Serverless working with Access Roles?

**Comment by medikoo** [comment]
@lovefamilychildrenhappiness thanks for report.

Did you configure your service to rely on dashboard (it needs to be setup with `app` and `org` settings)? Without that any settings you made in Dashboard will not be in effect for your service

**Comment by lovefamilychildrenhappiness** [comment]
@medikoo I don't see an org setting in the documentation: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/ Because I don't see it in the documentation, I don't know how to populate this org setting.

**Comment by lovefamilychildrenhappiness** [comment]
I also generated a serverless access key and added it to my environment $SERVERLESS_ACCESS_KEY. That does nothing either.

**Comment by medikoo** [comment]
@lovefamilychildrenhappiness check: https://serverless.com/framework/docs/dashboard#enabling-the-dashboard-on-existing-serverless-framework-services

**Comment by lovefamilychildrenhappiness** [comment]
I found the org on the dashboard and added it to serverless.yml as so:

service:
  org: my-user
  name: my-api

But still it does not work.

**Comment by kanelv** [comment]
@medikoo OP asked the A problem, and you blame to the B problem. Please focus on his question.
@lovefamilychildrenhappiness Do you have any new progress?
