### ISSUE TITLE
Vulnerable dependancy

### ISSUE THREAD

**Issue by robinMcA** [serverless/serverless#7402]
# Bug Report

## Description

If a yarn or npm audit is part of the CI/CD builds will fail.
Raising the issue here because there has been no action on the issue in the library.

1. What did you do?
npm audit or yarn audit
1. What happened?
serverless fails because of this https://www.npmjs.com/advisories/1217
1. What should've happened?
serverless passes
1. What's the content of your `serverless.yml` file?
N/A
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
N/A

Similar or dependent issues:

- https://github.com/kevva/decompress/issues/71

**Comment by medikoo** [comment]
@robinMcA thanks for reporting.

PR that patches that in a framework is highly welcome

**Comment by medikoo** [comment]
cc @richarddd (dependency on `decompress` was added with latest docker invocation improvements)

**Comment by robinMcA** [comment]
Looks like the issue will be in download as well, [download use](https://github.com/serverless/serverless/blob/da69527d1d850fc62651d96ad0d40bdb88f4b5a7/lib/utils/downloadTemplateFromRepo.js#L303)

**Comment by Nikhilkapoor20** [comment]
any update on this guys ?

**Comment by medikoo** [comment]
I've opened also issue at `download`: https://github.com/kevva/download/issues/189

I'd give a moment for package authors to recover. If that'll turn dragging I believe we need to replace them with alternatives.

**Comment by singhemant** [comment]
Shouldn't you change it in your package.json? https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L173
&
https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L174

**Comment by rajbir123** [comment]
Any update resolution on this guys?

**Comment by em0ney** [comment]
Any news? It looks like decompress is no longer maintained. Any plans to move to an alternative?

**Comment by medikoo** [comment]
> Any news? It looks like decompress is no longer maintained. Any plans to move to an alternative?

It's quite easy to get rid of `decompress` (it's question of reverting part of https://github.com/serverless/serverless/commit/f6d9bfd6c6bb5cd49ee67ce20e35e78090c18ab3)

Still we also depend on `download` (which depends on `decompress`).

PR that reliably get rids of both of those dependencies is welcome!

**Comment by bhtandev** [comment]
Hi, unsure if I should create another brand new issue or tag into this existing issue since this issue's title seem generic enough. ( my first time )

There are 2 more security vulnerable dependencies. `minimalist` and `dot-prop` found by SYNK on top of decompress. 

Both can be easily remediated by 

1.  Upgrading `mkdirp` package which uses `minimalist`.
2. Upgrading `update-notifier` which uses `dot-prop`.

<img width="1078" alt="Screen Shot 2020-03-13 at 11 53 21 am" src="https://user-images.githubusercontent.com/41136804/76579872-e3e54100-6521-11ea-8d06-27dc9bf742e2.png">
<img width="1077" alt="Screen Shot 2020-03-13 at 11 53 08 am" src="https://user-images.githubusercontent.com/41136804/76579912-08411d80-6522-11ea-9130-a75c43a34a96.png">

**Comment by richarddd** [comment]
Hi everyone!

Let's replace decompress with something else! Maybe https://www.npmjs.com/package/adm-zip
?

**Comment by Nikhilkapoor20** [comment]
any update on this ?

**Comment by medikoo** [comment]
> There are 2 more security vulnerable dependencies

@bhtandev for that I've created another dedicated issue: https://github.com/serverless/serverless/issues/7486

**Comment by medikoo** [comment]
> Maybe https://www.npmjs.com/package/adm-zip
?

@richarddd that'll be great. Still just replacing `decompress` won't fix it. We also need to replace `download` (which uses `decompress` as well)

**Comment by medikoo** [comment]
There's a `decompress` fork:   https://github.com/Atomic-Reactor/decompress that apparently has a fix. However we still need to replace `download` as well.

**Comment by neverendingqs** [comment]
It looks like the original package also got an update: https://github.com/kevva/decompress/pull/73#issuecomment-607268177

**Comment by neverendingqs** [comment]
PR to merge the change into `download`: https://github.com/kevva/download/pull/192

**Comment by neverendingqs** [comment]
The latest versions of both [decompress](https://github.com/kevva/decompress/pull/73#issuecomment-607967856) and [download](https://github.com/kevva/download/pull/192) should resolve this issue. The NPM advisory has been updated as well: https://www.npmjs.com/advisories/1217

**Comment by preshetin** [comment]
@neverendingqs thanks! I'll prepare the PR that updates both decompress and download dependencies

**Comment by medikoo** [comment]
It's great to hear that! With next release (coming today or on Monday latest) we'll have those dependencies bumped.

**Comment by medikoo** [comment]
Closing as that was addressed with one of latest releases
