### ISSUE TITLE
NPM audit is giving a security advisory around decompress

### ISSUE THREAD

**Issue by davidwilde** [serverless/serverless#7406]
# Bug Report

## Description

NPM audit is advising that a serverless dependency `decompress` is a high vulnerability. There is no patch available at this time so you would need to seek out an alternative dependency. `decompress` has not had an update for about 3 years

https://www.npmjs.com/advisories/1217

Similar or dependent issues:

- https://github.com/kevva/decompress/issues/71

**Comment by davidwilde** [comment]
Sorry, this is a duplicate of https://github.com/serverless/serverless/issues/7402

**Comment by singhemant** [comment]
Shouldn't you change it in your package.json? https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L173

**Comment by davidwilde** [comment]
> Shouldn't you change it in your package.json?
> 
> https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L173
> 
> 
> rather than closing the ticket?

I'm not a contributor to serverless, I just wanted to report this to them, but I later discovered that they already had an open ticket for this.

**Comment by rajbir123** [comment]
Any update resolution on this guys?

**Comment by singhemant** [comment]
> > Shouldn't you change it in your package.json?
> > https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L173
> > 
> > rather than closing the ticket?
> 
> I'm not a contributor to serverless, I just wanted to report this to them, but I later discovered that they already had an open ticket for this.

In that case, my bad!

**Comment by rajbir123** [comment]
> > Shouldn't you change it in your package.json?
> > https://github.com/serverless/serverless/blob/0ed52f61de98101fd570bc6e7794a74ab7afa0ff/package.json#L173
> > 
> > rather than closing the ticket?
> 
> I'm not a contributor to serverless, I just wanted to report this to them, but I later discovered that they already had an open ticket for this.

If changes also does it makes any sense? There must be alternative solution to resolve this as too many people raising this issue everywhere but still no result yet. Decompose library Contributor are sleeping from long time...
