### ISSUE TITLE
v0.5 CLI doesn't walk you through project build out

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#741]
You can create a project but a project isn't usable (secretly without a component and then one or more functions).

If you then try to create a function you get an unfriendly error.

The project creation process could walk users through [optionally?] making a component and then a first function.  Alternatively, the final text of that command could suggest that the next step is to create a component (and explain what role components serve in Serverless projects).

**Comment by erikerikson** [comment]
probably an enhancement

**Comment by ac360** [comment]
:+1:
