### ISSUE TITLE
BUG: Scheduled Schema validation fails 

### ISSUE THREAD

**Issue by smil2k** [serverless/serverless#7413]
# Bug Report

## Description

1. What did you do?

When adding a schedule expression in the correct form:
```yaml
  backup:
    handler: backend.BackupFunction
    events:        
    - schedule: 
        name: backup
        rate: rate(1 minutes)
```
Same applies to:

```yaml
  backup:
    handler: backend.LambdaFunction
    events:        
    - schedule: rate(1 minutes)
```

1. What happened?

The following validation error is thrown:
>   ServerlessError: "rate" property for schedule event is missing or invalid in function backup. The correct syntax is: `schedule: rate(10 minutes)`, `schedule: cron(0 12 * * ? *)` OR an object with "rate" property. Please check the docs for more info: https://serverless.com/framework/docs/providers/aws/events/schedule/

1. What should've happened?

The above snippet is valid, so a cron expression trigger should have been created.

1. What's the content of your `serverless.yml` file?

See above

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: "rate" property for schedule event is missing or invalid in function backup. The correct syntax is: `schedule: rate(10 minutes)`, `schedule: cron(0 12 * * ? *)` OR an object with "rate" property. Please check the docs for more info: https://serverless.com/framework/docs/providers/aws/events/schedule/
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:48:23
      at Array.forEach (<anonymous>)
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:34:28
      at Array.forEach (<anonymous>)
      at AwsCompileScheduledEvents.compileScheduledEvents (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:29:47)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:504:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:504:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:524:17)
      at Deploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:504:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:504:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:539:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:539:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:115:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:67:28
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:67:6
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:53:39)
      at Module._compile (internal/modules/cjs/loader.js:1151:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.7.0
     Framework Version:         1.52.0
     Plugin Version:            2.0.0
     SDK Version:               2.1.1

Similar or dependent issues:

- #4844 

This style gets validated, but then events not created:
```yaml
  backup:
    handler: backend.LambdaFunction
    events:        
    - schedule: 
      name: backup
      rate: rate(1 minutes)
```
(wrong behavior endorsed by the validator)

- #6562 
Probably caused by this.

**Comment by medikoo** [comment]
@smil2k have you tried `rate(1 minute)`?

**Comment by smil2k** [comment]
True.
