### ISSUE TITLE
AWS: Extend ${ssm} syntax to get output from another region

### ISSUE THREAD

**Issue by joshuanapoli** [serverless/serverless#7416]
# Feature Proposal

## Description

1. It is sometimes useful to deploy serverless to one AWS region, configuring it with an SSM value read from another region. For example, a serverless project using Lambda@Edge must be deployed in us-east-1, even if it is mainly interfacing with infrastructure and configuration defined in a different region. If we extend the ssm variable syntax to optionally specify the region, then it would be much easier to reference ssm values in another region.
1. We can extend the ssm variable syntax to match the cf syntax: `${ssm.REGION:key}`, e.g. `${ssm.us-east-1:/servers/blue/url}`. If region is omitted, default region is used, as same as current `${ssm}`.
1. While this feature could be implemented by a plugin, it seems more natural to include it in the core serverless platform. It improves the similarity cf and ssm variable syntax, which should work towards making the serverless.yml easier for developers to use.

Similar or dependent issues:

- This change is similar to https://github.com/serverless/serverless/pull/5579

**Comment by medikoo** [comment]
@joshuanapoli thanks for report. We're open for PR that implements that
