### ISSUE TITLE
v0.5 stage specific .gitignore exclusions?

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#742]
The .gitignore file is auto populated with the line:
`_meta/**/*-[STAGE]*`

where `[STAGE]` is replaced by the default stage of the project (supplied during project create).

After creating other stages, there are no lines corresponding to those stages.  Should there be?

**Comment by flomotlik** [comment]
I'm currently thinking about ways how we could remove the meta folder completely in V1. It still looks like quite a bit of a hack to me, and I'd love to get it removed completely and replaced with something better than can be shared easily across the team.

**Comment by erikerikson** [comment]
This issue was partly created out of my ignorance for how the _meta folder was being used elsewhere.  I have, ever since it was introduced, removed the gitignore entry excluding it.

The idea that security is provided by keeping them out of git strikes me as a farce.  The zip that is produced can be downloaded by anyone on your team and the secrets extracted.  Additionally your secrets would be written to a set of any number of unaudited discs accessible by who knows who.

I guess that for an open source project keeping these things out of a public repo but more difficult to steal at least raises the cost of obtaining them.

In the end, a lot of what is written to _meta is required for properly interpreting and deploying the project so not sharing it was inherently creating a problem.

Not that secrets can be unprotected.  What we store in _meta is references to the locations from which you can obtain the secrets that are gated by the access rights we assign and revoke.  This allows for scenarios (in thewhere paranoid cases) where only audited code ever touches the production secrets.  One Lambda for producing them.  The other, audited, Lambdas only ever loading those into memory for use.  Development and test environments needing less paranoia allow for engineer access for debugging use cases.  Lots of more permissive inbetween levels of paranoia for cases of less risk.

**Comment by flomotlik** [comment]
This also sounds like the perfect use case for #472 I will close this issue then add the topic is discussed over there
