### ISSUE TITLE
v1.65.0 changed the naming of AWS IAM roles which might be a breaking change?

### ISSUE THREAD

**Issue by imflamboyant** [serverless/serverless#7424]
I faced an error due to change in the naming of serverless-generated IAM roles. Everything works fine in 1.63.0 (for 1.64.x not sure) but in 1.65.0 the below described situation occurs. 

So far the names of generated IAM roles were taking the service name from serverless.yml and appending stack and stage etc. This seems to be changed in v1.65.0 to **stack name instead of service name**, so it is basically destroying the previously created role and creating the one with the new name. This is causing deployments to fail, as deleting the role resource is not always possible (due to it having relations perhaps to other resources etc). But even if the roles are successfully deleted and new ones created, they might cause breaking changes in case old roles had some **additional policies defined manually**, which this newly created policy will not have obviously. 

1. What did you do?
Deployed (updated) my existing serverless stack after updating the to serverless v1.65.0
1. What happened?
Deployment failed due to a 409 error stating that it's failing to delete my existing IAM Role related to the stack.
1. What should've happened?
It should not failed as my code was not changed at all.
1. What's the content of your `serverless.yml` file?
Content consists of http-event-triggered function definitions i.e.:
```
  getMyItems:
    handler: src/handler.getMyItems
    events:
      - http:
          method: get
          path: me/items
          cors: true
          authorizer: ...
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
N/A

Could someone please advise on this? I've also posted this question on the forum but so far no answers.

**Comment by medikoo** [comment]
@imflamboyant thanks for report.

In clean SLS environment, in case like that change of role name should be harmless (old one will get deleted and new one with same policy setup will be used instead).

Enhancing externally resources created with a stack is not recommended practice. It can easily become source of errors, which we cannot prevent.

I think you need to manually recover, and minimize any changes to given resources being made outside of a stack (ideally all setup should be done in context of `serverless.yml` configuration, so all everything is propagated with CloudFormation template).

**Comment by imflamboyant** [comment]
Thank you, I will close this then as it was expected behavior.
