### ISSUE TITLE
v0.5 function create cli arg for endpoint and/or event

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#743]
Executed:
`slsDev function create -h`
`slsDev function create [component]/[function]`

Observed:
```
Creates scaffolding for a new function.
usage: serverless function create <function>
```
```
Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
  > Create Endpoint
    Create Event
    Just the Function...
```
Expected:
```
Creates scaffolding for a new function.
usage: serverless function create
  -c, --component 
	required: blah blah
  -f, --function 
	required: blah blah
  -a, --apiEndpoint 
	optional: generate endpoint boilerplate
  -e, --event 
	optional: generate event boilerplate
```
```
function [function] successfully created [with endpoint] [with event]
```

**Comment by erikerikson** [comment]
low priority

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
