### ISSUE TITLE
Add plan command to AWS provider

### ISSUE THREAD

**Issue by edgarpoce** [serverless/serverless#7449]
# Feature Proposal
Add serverless plan command to AWS provider

## Description
It would be useful to have a plan command that shows a detailed log of the changes from a CloudFormation changeset. Similar to `terraform plan`, see https://www.terraform.io/docs/commands/plan.html

#  What is the use case that should be solved?
As a developer, I want to see a detailed log of changes before executing the deployment to AWS CloudFormation so that I don't deploy unintended changes.

# Implementation proposal
- create a new AWS provider-specific command called plan
- when plan is called then do the following
  - spawn serverless deploy preventing the execution of the stack update
  - create a changeset from the stack update
  - print the changeset details to the console
  - destroy the changeset and its corresponding files

# Contribution
There's a fork that I'd like to use to gather feedback before creating a pull request as recommended in the contribution guidelines. Changes can be reviewed in the last commit of the branch at https://github.com/edgarpoce/serverless/commits/feature/awsplan

Code from other open source projects was included and refactored as necessary. These projects are distributed under MIT license and the refactored files contain the corresponding copyright notice
https://github.com/trek10inc/serverless-cloudformation-changesets 
https://github.com/sjakthol/cfn-execute-change-set

# Similar issues:

- #4179

**Comment by medikoo** [comment]
@edgarpoce great thanks for that proposal! I think it's a valid use case, and idea is worth exploring.

Still, before we agree on implementation (btw. I know that you've already prepared PR) let's discuss first how do we think it should work.

My idea of this command is that:

1. In context of a Framework, we should just focus on AWS case
2. In AWS case this command should purely output a diff of generated CloudFormation template
3. Any other provider plugin should be able to configure own `plan` command without issue (in other words: implementation of `plan` in Framework should not introduce a collision for other provider plugins which may already provide this command)

If we agree on above, then I believe the implementation should follow steps of `sls package` (not `sls deploy`) dbut without generating any physical templates on disk (and lambda packages) if possible.

Other question: Is `plan` a best name? I personally do not have any other good idea, and as terraform has `plan` command, it looks as something self explanatory (altough with no terraform background I would have no idea that `plan` can be about that, that's my only concern here :)

Let me know your thoughts

**Comment by edgarpoce** [comment]
Hi @medikoo, many thanks for your feedback!

I'll investigate removing the dependency on sls deploy and use sls package instead ASAP. 

> In context of a Framework, we should just focus on AWS case

Agreed. I think this is done by setting the provider in the plugin constructor with the code below. Please let me know if there's any other implementation requirement to make the command provider specific.

`this.provider = this.serverless.getProvider('aws');`

>  In AWS case this command should purely output a diff of generated CloudFormation template

Makes sense, in the current PR it's also printing the info command output. I'll fix it.

> Any other provider plugin should be able to configure own plan command without issue (in other words: implementation of plan in Framework should not introduce a collision for other provider plugins which may already provide this command)

Agreed. My understanding is that by setting the provider as shown above then the plugin is not available to other providers. Is there any other implementation requirement to achieve this?

> If we agree on above, then I believe the implementation should follow steps of sls package (not sls deploy) dbut without generating any physical templates on disk (and lambda packages) if possible.

Makes sense. I think we'd still need lambda packages and physical templates created in order to get a consistent update template and the correct code hash that goes into the lambda version.

> Other question: Is plan a best name?

Not sure, I'll discuss it with my colleagues and will let you know if we come up with a better name.

Thanks!

**Comment by edgarpoce** [comment]
Hi @medikoo, I investigated the approach we discussed and prepared a new PR (#7509) which contains the following lifecycle for the plan command

- 'package', spawn sls package
- 'checkForChanges', from deploy command (cancel if no changes)
- 'uploadCloudFormationFile', from deploy command
- 'createChangeSet', new module
- 'waitForChangeSetCreateComplete', new module
- 'runAnalysis', new module
- 'deleteChangeSet', new module
- 'deleteChangeSetFromS3', new module
- 'printAnalysis', new module

According to my tests it's necessary to run package as a previous step because it generates all the necessary files to create the cloudformation update file, including the version hash corresponding to the lambda functions. 

About the naming of the command, I got feedback from a colleague and he proposed diff instead of plan, wdyt?

**Comment by gnomeria** [comment]
I think for the name if we want to still use deploy, we could at least put a `--dry-run` command on deploy. Although for some of us who's already familiar with terraform would think `plan` is more intuitive.

**Comment by gnomeria** [comment]
Or perhaps could we have a confirmation to deploy after seeing stack? That I think could be put on the deploy command. Basically waiting for yes after outputting the change plan

**Comment by medikoo** [comment]
> About the naming of the command, I got feedback from a colleague and he proposed diff instead of plan, wdyt?

@edgarpoce @gnomeria I took a look at Terraform, and I think `plan` over there is something more. It outlines a list on necessary setup steps (execution plan) to achieve a switch to newly configured stack.

Here it'll be more about outlining a diff on generated CloudFormation template. So I guess `diff` or `cloudformation-diff` will be more accurate (`diff` may be to vague, diff of what, config.. etc?).

Therefore what do you think of `cloudformation-diff`?

Otherwise I think we have everything right, I'll take a look at PR shortly (sorry for delay)

**Comment by gnomeria** [comment]
I think not using `plan` to differentiate the scope on the serverless is okay. But I agree the `diff` keyword might be too vague. What about `preview` ? Or something like `dry-run` ?

**Comment by edgarpoce** [comment]
cloudformation-diff sounds good, I don't have a strong preference about the naming. I'll keep an eye on the PR to make the required changes. Thanks for reviewing!

**Comment by medikoo** [comment]
As indicated in https://github.com/serverless/serverless/pull/7509#issuecomment-625867140 we've decided to welcome it as external plugin.
