### ISSUE TITLE
'Schedule' type Event is always using the latest lambda function deployed, not using stage it was deployed to.

### ISSUE THREAD

**Issue by pickerguitar** [serverless/serverless#746]
When using the 'Schedule' type Event it is always using the latest lambda function deployed ($LATEST), and not using the stage it was deployed to.

**Comment by pickerguitar** [comment]
v 0.4.2

**Comment by pickerguitar** [comment]
Inexplicably, after a bunch of fiddling, was able to get the Event to link to a particular stage in the lambda, but now other stage's events do not get deployed. (a different bug?)

**Comment by pickerguitar** [comment]
as a work-around we set a variable in s-variables-common.json and use the following in our s-function.json. seems to give us what we want
  "events": [
    {
      "name": "five-minute-schedule",
      "type": "schedule",
      "config": {
        "schedule": "rate(5 minutes)",
        "lambdaArn": "${lambdaArn}:${stage}"
      }
    }
  ]

**Comment by eahefnawy** [comment]
@pickerguitar I just looked into this, and it seems that it's an AWS bug. Or not really a bug, but I guess CloudWatchEvents (which is pretty new in itself) doesn't yet support function aliases/qualifiers, which is how we assign stages to functions. I asserted this by making sure we're passing the correct full ARN to AWS API, and it looks like we do, but AWS completely ignores the qualifier substring. Even if you're gonna add the Lambda as a target using the AWS Console UI, there's really no option to choose the function alias/version.

I'm also very curious on how setting a `lambdaArn` in the `config` property worked for you?! We generate the lambda ARN dynamically and don't require it as input from the user, so our framework should ignore this new property. Maybe it's just a coincidence.

**Comment by pickerguitar** [comment]
Hi Eslam,

Thanks for the information.  What we’re doing it to take the lambdaArn and adding it to our s-variables-common.json, here’s an example:

{
  "project": "dvtl-index-service",
  "projectBucket": "serverless.us-west-2.dvtl-sb.mheducation.com",
  "domain": "dvtl-sb.mheducation.com",
  "notificationEmail": "david.larocque@mheducation.com",
  "lambdaArn": "arn:aws:lambda:us-west-2:711200063112:function:dvtl-index-service-rolling-indexRoller”
}

In our s-function.json we include the variable in the events section as follows:

"events": [
  {
    "name": "five-minute-schedule",
    "type": "schedule",
    "config": {
      "schedule": "rate(5 minutes)",
      "lambdaArn": "${lambdaArn}:${stage}"
    }
  }
]

We haven’t done extensive testing, but this does seem to work for the several different stages to which we deployed this function.


Warm regards,

Dave



David LaRocque | Senior Developer | Digital Platform Group

McGraw-Hill Education | 281 Summer St, Boston, MA 02210
P: 617-859-6127 | C: 508-250-5944 | david.larocque@mheducation.com<mailto:aj.brown@mheducation.com>

http://www.mheducation.com<http://www.mheducation.com/>

**Comment by staceymoore** [comment]
@eahefnawy I get around this by using a unique function name for each stage. If you wanted to work around it in sls, you could append the stage name at the end of the event name. Each event needs a unique name so it doesn't get overwritten.

**Comment by eahefnawy** [comment]
@staceymoore yeah that's how we used to work with stages at the very beginning, we'd simply have a completely different lambda for each stage. But when AWS introduced versioning and aliasing we switched to using those.

**Comment by mashbourne** [comment]
@eahefnawy 
EventLambdaSchedule.js configures schedule Targets Id to functionName. The api call is a PUT, so multiple stage event deploys overwrite the same target. I think Targets Id should be functionName+stage
https://github.com/serverless/serverless/blob/v0.5/lib/actions/EventLambdaSchedule.js#L104

**Comment by mashbourne** [comment]
also seems like you can't use templates in the events configuration

**Comment by eahefnawy** [comment]
@mashbourne you're right! I miss understood the issue. Sorry about that :blush: . I just pushed a fix for this and we released it.
