### ISSUE TITLE
sls create with template-path or template-url can NOT copy into working directory

### ISSUE THREAD

**Issue by pjcav** [serverless/serverless#7461]
Running

```
sls create --template-url githuburl --name my-service
```
will create a subfolder `my-service` when it should just create the project in the working directory.
Same issue when using --template-path

https://github.com/serverless/serverless/blob/f822ae7e4c4062178b9f6843104fb33f0a586ef5/lib/plugins/create/create.js#L182
Should only do above check if `--path` is provided

**Comment by medikoo** [comment]
@pjcav great thanks for report. We will welcome a PR with a fix!

**Comment by s-kikuchi** [comment]
@medikoo 
Hi, I have summarized
- current command execution result
- the expected results I think

in the table below.
If you have any suggestions, please write them down.

### sls create --template-path

| --path | --name | result | expect |
| ------------- | ------------- | ------------- | ------------- |
| ○ | ✗ |1. Extract template to `--path` directory | No need to change |
| ✗ | ○ |1. Extract template to `--name` directory<br>2. Change the service name in serverless.yml to `--name` | 1. Extract template to current directory<br>2. Change the service name in serverless.yml to `--name` |
| ○ | ○ |1. Extract template to `--path` directory<br>2. Change the service name in serverless.yml to `--name` | No need to change |

### sls create --template-url
| --path | --name | result | expect |
| ------------- | ------------- | ------------- | ------------- |
| ○ | ✗ | 1. Extract template to `--path` directory<br>2. Change the service name in serverless.yml to `--path` | 1. Service in serverless.yml should not be changed |
| ✗ | ○ | 1. Extract template to `--name` directory<br>2. Change the service name in serverless.yml to `--name` | 1. Extract template to current directory<br>2. Change the service name in serverless.yml to `--name` |
| ○ | ○ | 1. Extract template to `--path` directory<br>2. Change the service name in serverless.yml to `--name` | 1. Extract template to `--path` directory<br>2. Change the service name in serverless.yml to `--name` |

**Comment by medikoo** [comment]
@s-kikuchi Thanks for this summary, yes I believe you got it right. PR with fix will be very appreciated!

**Comment by medikoo** [comment]
Closing as we're replacing `sls create` with `sls` (which will setup project interactively), and I believe there are no such issues there.

(Note we're keeping `sls create` simply to not be breaking, and that it's still referenced in old blog posts)
