### ISSUE TITLE
folder deleted after execute serverless deploy 

### ISSUE THREAD

**Issue by hseghetti** [serverless/serverless#7463]
# Bug Report

## Description

After execute serverless deploy --verbose and receive an error ALL the local folder where the command was executed is deleted. 

**1. What did you do?**
 I executed "serverless deploy --verbose"

**1. What happened?**
I received the error: Cannot find module './node/NodeTemplatePlugin' and the project folder was deleted. ALL the folder with all the files. I reproduced the error more than one time

**1. What should've happened?**
Even receiving an error the local folder should not be delete.

**1. What's the content of your `serverless.yml` file?**

service: serviceNameHere
app: appNameHere
org: nameHere
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true
functions:
  site:
    handler: handler.site`

**1. What's the output you get when you use the `SLS_DEBUG=*` environment variable**

$SLS_DEBUG=* serverless deploy --verbose
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
platform-sdk fetching: POST https://api.serverless.com/core/tenants/hseghetti/applications/tiwss/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Using configuration:
{
  "includeModules": true,
  "webpackConfig": "webpack.config.js",
  "packager": "npm",
  "packagerOptions": {},
  "keepOutputDirectory": false
}
Serverless: Removing /Users/mema/development/tiwss_project/tiwss-serverless/tiwss
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...

  Error --------------------------------------------------

  Error: Cannot find module './node/NodeTemplatePlugin'
  Require stack:
  - /Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/webpack/lib/WebpackOptionsApply.js
  - /Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/webpack/lib/webpack.js
  - /Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/serverless-webpack/lib/compile.js
  - /Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/serverless-webpack/index.js
  - /snapshot/serverless/lib/classes/PluginManager.js
  - /snapshot/serverless/lib/Serverless.js
  - /snapshot/serverless/lib/utils/autocomplete.js
  - /snapshot/serverless/bin/serverless.js
  1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
      at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
      at Function.Module._load (internal/modules/cjs/loader.js:688:27)
      at Module.require (internal/modules/cjs/loader.js:850:19)
      at Module.require (pkg/prelude/bootstrap.js:1166:31)
      at require (internal/modules/cjs/helpers.js:74:18)
      at WebpackOptionsApply.process (/Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/webpack/lib/WebpackOptionsApply.js:101:27)
      at webpack (/Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/webpack/lib/webpack.js:57:48)
      at ServerlessWebpack.compile (/Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/serverless-webpack/lib/compile.js:12:22)
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/snapshot/serverless/lib/classes/PluginManager.js:510:17)
      at ServerlessWebpack.<anonymous> (/Users/mema/development/tiwss_project/tiwss-serverless/tiwss/node_modules/serverless-webpack/index.js:101:51)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.65.0 (standalone)
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        2.22.3

**Comment by hseghetti** [comment]
More information: 
I made it work changing the webpack.config.js file from: 

module.exports = {
    entry: path.resolve(__dirname, 'handler.js'),
    output: {
        path: path.join(__dirname),
        filename: 'bundle.js'
    },
    node: {
        __dirname: false
    },
    externals: [nodeExternals()]
};

to: 

module.exports = {
    entry: './handler.js',
    target: 'node'
};


It meas that it is related to the issue. Anyway as you can see in the console output all the folder is deleted before invoke webpack:compile: 

Serverless: **Removing /Users/mema/development/tiwss_project/tiwss-serverless/tiwss**
Serverless: Invoke webpack:compile

**Comment by medikoo** [comment]
@hseghetti Thanks for report, still I think it is not a problem with a Framework, but most likely with [Webpack](https://github.com/serverless-heaven/serverless-webpack) plugin.

Can you please report it there.

**Comment by hseghetti** [comment]
Thank you @medikoo. I will report it to Webpack.
