### ISSUE TITLE
Question - Are there intentions to become platform agnostic?

### ISSUE THREAD

**Issue by 0xc00010ff** [serverless/serverless#747]
AWS is obviously not going anywhere anytime soon but the recent Parse shutdown has some of us skeptical about relying on closed proprietary platforms. Does the serverless team have ideas about adapting the platform to work on other cloud providers, or perhaps being provider agnostic?

**Comment by erikerikson** [comment]
the precursors to multi provider capabilities are being released in days.

**Comment by flomotlik** [comment]
@0xc00010ff yes. Closing this issue for now. We'll release more info on that in the future.

**Comment by 0xc00010ff** [comment]
Very cool! Good stuff guys.
