### ISSUE TITLE
Upgrade vulnerable dependencies

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7486]
We need to upgrade following dependencies.

- [x] `boxen` (see https://github.com/serverless/serverless/pull/7226) (Addressed with https://github.com/serverless/serverless/pull/8163)
- [x] `update-notifier` (see https://github.com/serverless/serverless/pull/7226 and #8008) (Addressed with https://github.com/serverless/serverless/pull/8182)
- [x] `mkdirp` (see https://github.com/serverless/serverless/issues/7455) - Replace with `fs-extra`'s `ensureDir` (Addressed with #8183)

Ideally each upgrade should be addressed with different PR.

PR's should be based against [`v2`](https://github.com/serverless/serverless/tree/v2) branch

**Comment by exoego** [comment]
We may remove mkdirp dependency since Node.js 10 adds recursive option to fs.mkdir.

**Comment by exoego** [comment]
How about removing `update-notifier`?
IMHO, update notification is less valuable nowadays,
because there are many ways to update dependencies automatically, e.g. dependabot, greenkeeper and so on.

One example of npm module that removed update-notifier.
https://github.com/palantir/tslint/pull/2262

**Comment by medikoo** [comment]
@exoego thanks for suggestion. Still it doesn't apply that much in `serverless` case as it's top level package (not typical dependency)

Many developers use just global (or _standalone_) installation and naturally in such case they're not tracking new updates via some external means

**Comment by exoego** [comment]
Ah, thats true.
I forgot about global installation.

**Comment by instantlinux** [comment]
I have an enterprise installation of this for which `dot-prop` and `update-notifier` really need to be cleared of high-severity vulnerabilities like [advisory #1213](https://www.npmjs.com/advisories/1213).

**Comment by Trott** [comment]
I can think of a few ways around this for `update-notifier` (which has `dot-prop` as a vulnerable dependency), but I'm not sure if they'll be acceptable to the serverless maintainers or not.

Easiest option might be to bump `update-notifier` to the current version but don't load it if the user is running Node.js 6. On the one hand, I guess it's a little rude to not tell Node.js 6 users when they can/should update serverless. On the other hand, perhaps this is snobbish or something, but Node.js 6 went EOL almost a year-and-a-half ago as of this writing, so maybe they're not very likely to upgrade stuff anyway for whatever reason. (Yes, I'm making assumptions that if they can't/don't update Node.js, they can't/don't update serverless, and that assumption may be wrong.)

There are other options, but I'd start with that one. I'll open a PR for that and see what happens with it.

**Comment by Trott** [comment]
> There are other options, but I'd start with that one. I'll open a PR for that and see what happens with it.

Well, the PR template has this:

>  ⚠️⚠️ Do not propose PR's without prior agreement on solution in corresponding issue

So maybe I'll wait for a maintainer to comment.....

**Comment by Trott** [comment]
Here's the change I'm suggesting: https://github.com/serverless/serverless/compare/master...Trott:update-notifier?expand=1

**Comment by medikoo** [comment]
@Trott thanks for proposal.

I think the right approach is simply to drop support for Node.js v6 & v8 and release a new major, I will discuss it internally, and hopefully by end of this month we will have that sorted out.

**Comment by Trott** [comment]
Good news: dot-prop@4.2.1 has been published with the security fix. https://github.com/sindresorhus/dot-prop/issues/63#issuecomment-674513678

**Comment by Trott** [comment]
> Good news: dot-prop@4.2.1 has been published with the security fix. [sindresorhus/dot-prop#63 (comment)](https://github.com/sindresorhus/dot-prop/issues/63#issuecomment-674513678)

Whether the automated tools that report the issue pick that fact up or not remains to be seen....

**Comment by instantlinux** [comment]
Before jumping on dot-prop@4.2.1 hastily, please double-check the integrity of the upstream. I see that the source repo on github has not been updated (see the commit history of https://github.com/sindresorhus/dot-prop where the latest 4.x tag is 4.2.0) yet there's a new version 4.2.1 posted at npmjs. I don't know how to account for this discrepancy but for a high-popularity repo like that with ~15M downloads weekly I'd like to know why it exists.

**Comment by medikoo** [comment]
I'm glad to announce that we will release v2 next week. PR that upgrades vulnerable dependencies is welcome (I've updated main description)!
