### ISSUE TITLE
Create multiple lambda roles for a project

### ISSUE THREAD

**Issue by JohnDzialo** [serverless/serverless#750]
Hi!

I have a project with multiple components and functions.  I would like to be able to create a lambda role for each function with unique policies specific to each function's needs.

It appears that the s-resources-cf.json file only supports one lambda role, with multiple policies.  I would like multiple lambda roles with specific policies that could be applied at the project, component or function level.

Am I missing this functionality in the docs?
If not is that planned in a future release?

**Comment by ac360** [comment]
Hi @JohnDzialo 

This is possible.  Just add new IAM Roles to your s-resources-cf.json file, deploy them, then add the role ARN to `customRole` in `s-function.json`

**Comment by rorlig** [comment]
How does when do this in v1. I want to give my lambda functions different IAM roles and policies

**Comment by thkapasi** [comment]
https://github.com/functionalone/serverless-iam-roles-per-function
