### ISSUE TITLE
How to pass integer value for variables with a fallback

### ISSUE THREAD

**Issue by tobilg** [serverless/serverless#7501]
Is it possible to actually use integer default values for variables when using a syntax like this in the `serverless.yml`:

```yaml
${file(config/example.yml):scaling.pause.secondsUntilAutoPause,'900'}
```

If omitting the quotes for the default value, the following warning is produced and the value itself is ignored in the output:

```bash
 
 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(config/example.yml):scaling.pause.secondsUntilAutoPause,900' could not be found.
```

**Comment by medikoo** [comment]
@tobilg thanks for report. Unfortunately currently only strings are accepted as plain fallback values. See dedicated issue: https://github.com/serverless/serverless/issues/7462

I'm going to close this as duplicate
