### ISSUE TITLE
[HTTP API] API doesn’t include a route with path /*

### ISSUE THREAD

**Issue by matheus-figueiredo-bw** [serverless/serverless#7508]
I am trying to use the HTTP API GW feature implemented here: https://github.com/serverless/serverless/pull/7274.

The problem is that the AWS Console for my lambda seems to say that there is an error with my API GW. **_The endpoint does work, and it reaches the lambda function just fine. So, is this a bug with AWS Console, AWS HTTP GW or with serverless?_**

![Screenshot from 2020-03-25 15-33-01](https://user-images.githubusercontent.com/54188494/77572847-75ec3280-6eae-11ea-9d39-4024a5110cb2.png)

Here is my serverless.yml

```service: http-api-lambda-test

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 10
  memory: 128

functions:
  simpleHttp:
    handler: build/handler.simpleHttp
    events:
      - httpApi: '*'
```

**Comment by matheus-figueiredo-bw** [comment]
Well, in the same day I submitted a case to AWS tech suport and got an answer, I'll leave it here just for archive purposes and in case someone find stuck in this problem:

> Hi there,
> 
> This is most likely just a bug. I have had a look at some of my API gateway integrations that are still working and they still operate. I will cut a ticket to the API Gateway team to see if they can have a look at this. Thank you for bringing this to our attention.

**Comment by PawelFaron** [comment]
Is there any solution for this? I'm facing the same issue.

**Comment by JustinPullen** [comment]
I am not sure anyone has solved this. Seems there is still an outstanding issue.  I am opening a ticket with AWS Support as we speak.

**Comment by Hastalavistababy** [comment]
Same issue.

**Comment by phuc1012000** [comment]
For me, I only have problem with 'GET' method while other working fine.

**Comment by dnitsch** [comment]
The easiest work around I found it to supply an identity policy to APIGateway directly as opposed to adding a permission to Lambda for now.

**Comment by antonxo** [comment]
I had the same error message when I published a lambda version, but forgot to add a resource-based policy to it. I described it in more detail here - https://stackoverflow.com/a/76009086/10369131.

**Comment by laksh-parab** [comment]
@antonxo tried your solution. I added resource based policy using Terraform. Did not work.  API can invoke lambda but cosole show error

resource "aws_lambda_permission" "api_gw" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = data.aws_lambda_function.existing.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.lambda.execution_arn}/*/*"
  qualifier     = data.aws_lambda_alias.lambda_alias.name
}

**Comment by laksh-parab** [comment]
In AWS Console, for lambda there is `Triggers` tab at each level. For Function, Alias and Version. Depends on how your API integration is setup you will see API source mapping at different places.  In API integration If you are using Lambda's default ARN then check the `Triggers` tab at Function level.  If you are using Alias or Version with Lambda ARN then check `Triggers` tab for Alias or Version respectively.  If you update the integration from, for example, default ARN to Alias then you will see error on Triggers tab of function

**Comment by zhex900** [comment]
> identity policy

@dnitsch Can you provide an example of the identity policy you applied to API gateway? Did you create a role and put it in the `Lambda Invoke Role` ?
