### ISSUE TITLE
v0.5 installs wrong version of serverless-helpers-js with component create

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#751]
If you create a new component with `component create` the installed boilerplate installs the wrong serverless-helpers-js version 0.1.0 into the new component.
The correct version should be `0.2.0`.

**Comment by ac360** [comment]
Components have been removed in `v0.5`.  Thanks anyway @HyperBrain!

**Comment by HyperBrain** [comment]
@ac360 Ok, after updating the sources the create components vanished out of v0.5.
But: If components have been removed (as modules had been before), what would then be the means of structuring projects into multiple packages with different dependencies, roles, etc.? E.g. currently I have some projects that are split into multiple components. Each component belongs to the project and uses its global resources (CF). The resources are e.g. Kinesis streams that are written to by the functions within one component (producer) and exposed via a public API, wheras there is also a consumer component that accesses the same stream but is only used privately in the backend.
The connecting point was until v4 the CF stack that provided the stream's name.
I like to keep the "components" distinct by concerns with having the ability to use these two-ended shared resources.
If I would split them up into multiple projects, only one of them can be the owner of the stream - if the stream is recreated I would have to transfer the new name into the other project as runtime resolution of the name from CF in that case is a bad solution as the consuming lambda is triggered by a stream event (that is set up in the s-function by using a template variable with the name of the stream).
The general question is: How should this be handled, without dumping all code into one place and having the same dependencies for everything?

**Comment by ac360** [comment]
@HyperBrain Though Components are gone in `V0.5`, the functionality still exists through a simple new feature called "magic handlers".  

Basically, the Framework looks at the `handler` for each function in `s-function.json` and uses it to determine the root folder of the Lambda function.  Whatever the handler specifies as the root is what's zipped up into the Lambda function.  In this case:
```
project
  component1
    package.json
    function1
    function2
  component2
    package.json
    function3
    function4
```
If the handler in `function1` is `function1/handler.handler`, then `component1` will be the root folder of the lambda function. But if the handler of `function1` is `handler.handler`, then `function1` will be the root folder of the lambda function.

This allows people to specify their Lambda root folder in a flexible way, enabling the same easy code sharing or zipping up only the lambda function, if that's desired.

So, you can still have this:
```
project
  component1
    package.json
    function1
    function2
  component2
    package.json
    function3
    function4
```

But now, you can also have this:
```
project
  functions
    component1
       package.json
       function1
       function2
    component2
       package.json
       function3
       function4
```

Or this:
```
project
  function1
  function2
```
Or infinite nesting!

**Comment by HyperBrain** [comment]
Thanks for the detailed explanation :-) 
But with such a "magic" in place it should really be well documented...

**Comment by ac360** [comment]
@HyperBrain Docs for `v0.5` are being updated at this very moment!  Plus, we will have a full write-up of this in the Release Notes for `v0.5`.  There is a ton of great functionality in this release.
