### ISSUE TITLE
AWS s3 sync for lambda layers

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#7516]
# Feature Proposal

## Description

When there are no updates to the lambda layer package (.zip file), do not upload it for every deployment.  Issue an s3-object-head request to get back some information about the existing lambda layer on s3 and compare it with the local filesystem resource.  When it's clear that the s3 object has the same content size (or md5) as the local filesystem resource, skip the upload.

**Comment by medikoo** [comment]
@dazza-codes that's great idea! We're open for PR that improves our internals with it.

**Comment by exoego** [comment]
I think it is difficult to head-object the zip file of previously uploaded layer, because object name contains timestamp.
How should s3 key (the path to zip) be retrieved?
I am considering to fetch CloudFormation stack to retrieve s3 key.

**Comment by dazza-codes** [comment]
It seems like serverless-plugins uses a local cached archive of layers to detect local changes.  The `.serverless/layer_cache.json` could simply keep track of .zip file names and their md5 or similar hash fingerprints.  If there are no local-file-system changes, then don't upload the layer again.  (It doesn't solve the s3-consistency problem, when a team are all pushing to the same deployment target that might be sharing layers on s3; haven't really thought that through entirely.).
