### ISSUE TITLE
NPM audit finds low vulnerabilities

### ISSUE THREAD

**Issue by quirkles** [serverless/serverless#7525]
# Bug Report

## Description

There are vulnerabilities regarding minimist

Minimist, vie the seemingly dead tap-tap module, has multiple low vulnerabilities.

What did you do?
I ran an npm audit in a project that has serverless: 1.67.0 installed.
What happened?
Audit failed.
What should've happened?
Audit passed.

**Comment by medikoo** [comment]
@quirkles thanks for report. We're open for upgrading/replacing any dependencies as far as we do not break support for Node.js v6 (we need to maintain that in v1.0.0 version).

Any PR that helps us with that is welcome

**Comment by medikoo** [comment]
@quirkles we neither use `minimist` or `tap-tap` modules directly. Can you clarify for which direct Framework dependency you see the vulnerability reported ?

**Comment by joolfe** [comment]
Hi,

Im getting an audit error also, using the serverless version  "^1.71.1",

<img width="581" alt="Screen Shot 2020-05-19 at 15 30 10" src="https://user-images.githubusercontent.com/1319632/82339182-aa2f2b80-99e5-11ea-9c55-891a4f41226f.png">

The lib `socket.io-stream` is using a very old version of debug.

**Comment by medikoo** [comment]
@joolfe can you report it at https://github.com/serverless/utils-china/ ?

**Comment by medikoo** [comment]
Closing as that was addressed
