### ISSUE TITLE
V0.6 Endpoints should properties of project, not functions

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#753]

**Comment by erikerikson** [comment]
Love it.  Maybe even the project's API?

A disabled use case in the prior formulation was API Gateway proxying to other AWS services.

**Comment by ac360** [comment]
Yep, that use-case will be enabled by this change, and much more...

**Comment by HyperBrain** [comment]
Also API GW model support which heavily depends on shared (project based) models would be enabled by this -> GW models are represented by classes in the generated GW SDKs and should refer to the same class if the same model is used.

**Comment by flomotlik** [comment]
Event/Endpoint handling in V1 will supersede this issue as endpoints will be created for a particular service and all functions in is, so I'm closing it here.
