### ISSUE TITLE
Settings a Profile in serverless.yml doesn't override Environment Variable Settings.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [serverless/serverless#7573]
# Bug Report

## Description

I have AWS environment variables set for one project on my computer.
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY

For a different project I have the profile variable set within my serverless.yml file. 

When I attempt to deploy my solution it uses the environment variables even if I have the profile set within my serverless.yml file. 

I'm not sure if this is intentionally or not.

**Comment by et304383** [comment]
That's intended behaviour of all AWS SDKs and subsequently tools made using the SDK (NodeJS SDK in this case).

Environment variables have the highest precedence in terms of sourcing credentials (other than directly passing them to a constructor):

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html
