### ISSUE TITLE
@serverless/utils-china globalTunnel breaks AWS SDK proxy

### ISSUE THREAD

**Issue by awill1988** [serverless/serverless#7578]
# Bug Report

## Description

Hello, I want to start out saying that I really appreciate the time reviewing this issue.

The issue is caused by a dependency that is maintained by this group, but not part of the code maintained here. Because it is such a disruptive bug, I thought it would be useful to bring up with the main repo. It is due to the code that is maintained in [serverless/utils-china](https://github.com/serverless/utils-china).

FYI, I also opened an issue there: https://github.com/serverless/utils-china/issues/2

#### What did you do?

Set an `HTTP_PROXY` environment variable to be picked up for use by the AWS SDK when executing serverless hooks. The command was as such:

```bash
...
http_proxy='http://localhost:3128' \
https_proxy='http://localhost:3128' \
SLS_DEBUG=* node --inspect-brk ./node_modules/.bin/serverless deploy --stage dev;
```

#### What happened?

The `HTTP_PROXY` environment variable did not exist when debugging lines 147-152 located in _this_ repository serverless/lib/plugins/aws/provider/awsProvider.js

Working backwards, `HTTP_PROXY` is clobbered on line 27 in `serverless/bin/serverless.js`.

Working through the chain of `require`, I have found the culprit, which exists _outside_ of this codebase:

`@serverless/utils-china/library/global-tunnel/index.js` *deletes* any http proxy environment variables during it's library initialization. The culprit is on lines 7 & 84 of the `findEnvconstProxy`:

*Line 7*

```
const ENV_const_PROXY_SEARCH_ORDER = ['https_proxy', 'HTTPS_PROXY', 'http_proxy', 'HTTP_PROXY'];
```

*Lines ~84*

```
function findEnvconstProxy() {
  let result = ''
  for (let i = 0; i < ENV_const_PROXY_SEARCH_ORDER.length; i++) {
    const key = ENV_const_PROXY_SEARCH_ORDER[i]
    const val = process.env[key]
    if (val !== null && val !== undefined) {
      result = result || val
      delete process.env[key] <---- right there
    }
  }

  return result
}
```

Here is the problematic file for the team's review:
https://github.com/serverless/utils-china/blob/master/library/globel-tunnel/tunnel.js

#### What should've happened?

From my standpoint, the environment variable should have not been deleted. It has completely broken the AWS provider when executed within a corporate proxy.

I'm not sure if that would break the use case that is being addressed in `@serverless/utils-china`.

I would usually create a PR with an issue, but without knowing more about the china use case, I wouldn't feel confident to submit a merge request that would preserve both use cases.

We will create a workaround, but I figured this group would want to fix this ASAP.

#### What's the content of your `serverless.yml` file?

N/A as this is outside the scope of serverless.yml

#### What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

When we attempt to deploy our code in a private subent without a direct internet connection (as we force http proxy settings to communicate with AWS services), we get timeouts:

```
Serverless: Fetch dependency graph from /codebuild/output/src029299486/src/package.json
Serverless: No external modules needed
Serverless: Zip service: /codebuild/output/src029299486/src/.webpack/service [395 ms]
Serverless: Packaging service...
Serverless: Remove /codebuild/output/src029299486/src/.webpack
Serverless: Recoverable error occurred (connect ETIMEDOUT 100.25.112.140:443), sleeping for ~5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (connect ETIMEDOUT 100.25.112.135:443), sleeping for ~6 seconds. Try 1 of 4
```

Similar or dependent issues (maybe?):
- #7404

**Comment by medikoo** [comment]
@awill1988 great thanks for reporting that. We'll look into it shortly!

**Comment by medikoo** [comment]
@awill1988 this was fixed in underlying package. Ensure to update `serverless` via `npm update` and issue should be gone

**Comment by awill1988** [comment]
@medikoo, thank you for a quick turn around. I have verified the proxy env variables are no longer being removed via debugging on the latest version, and I see that the proxy settings are being set with the AWS SDK.

Since I had to install the same version of serverless on npm, I played it safe and did:

```
$ rm -rf node_modules/serverless node_modules/@serverless
$ npm i serverless
```

or for those on the global install:

```
$ rm -rf `npm get prefix`/lib/node_modules/serverless `npm get prefix`/lib/node_modules/@serverless
$ npm i -g serverless
```

Cheers,
Adam
