### ISSUE TITLE
First serverless deploy fails

### ISSUE THREAD

**Issue by smillerj** [serverless/serverless#7583]
Ran a fresh angular project deploy with npm run build:serverless:deploy. The deploy failed and the console threw this message:

```
Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-api-compression" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.3
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.3

```
The content of my yml file is 

`# generated by @ng-toolkit/serverless
service: serverlessapp

plugins:
  - serverless-apigw-binary
  - serverless-api-compression

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 192
  timeout: 10
  stage: production
  region: eu-central-1

package:
  exclude:
   - src/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

custom:
  contentCompression: 1024
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
`

**Comment by JeremiGendron** [comment]
you need to add the `serverless-api-compression` dependency to your project:
`npm install --save-dev serverless-api-compression`

**Comment by medikoo** [comment]
@smillerj have you run `npm install...`, can we close the issue?

**Comment by zatchgordon** [comment]
npm install fixed the issue for me

**Comment by medikoo** [comment]
Closing due to missing details
