### ISSUE TITLE
deployment failed for cloudwathc log event in cn-north-1 region

### ISSUE THREAD

**Issue by Wayne-Shen** [serverless/serverless#7589]
# Bug Report

## Description

1. What did you do?
Trying to deploy Lambda function  via `sls deploy -v`
1. What happened?
Deployment failed for event cloudwatchLog, but succeed for other events like sqs/s3 etc.
1. What should've happened?
Deployment should success.
1. What's the content of your `serverless.yml` file?
`service: lambda-oims-mssql

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  region: cn-north-1
  iamManagedPolicies:
    - 'arn:aws-cn:iam::aws:policy/AWSLambdaFullAccess'
  logRetentionInDays: 7
  stage: prod
  deploymentBucket:
    name: sls-lambda-deployment-1
    tags:
      PROJECT:mssql-17063

functions:
  notifyAll:
    handler: handler.notifyAll
    events:
      - cloudwatchLog: 'loggroup'
`
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
ServerlessError: An error occurred: NotifyAllLambdaPermissionLogsSubscriptionFilterCloudWatchLog - The provided principal was invalid. Please check the principal and try again. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 233536d0-8a47-4756-b889-1a62c5785b7b).

**Comment by medikoo** [comment]
@Wayne-Shen Can you update description of your issue with proper formatting, so proper syntax blocks are use for content of `serverless.yml` and console output (follow https://guides.github.com/features/mastering-markdown/)
