### ISSUE TITLE
Serverless deployment on cloudbees fails.

### ISSUE THREAD

**Issue by aravindvalkodai** [serverless/serverless#759]
I had already mentioned about this issue in the glitter chat room.

I am trying to do serverless deployment using cloudbees into AWS. I am able to deploy the "resources" and "functions" successfully. However when I try to deploy the "endpoint" using the following command
"serverless endpoint deploy --all -s mystage" I end up with a stack with the first few lines of the stack like this:
ReferenceError: SUtils is not defined at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/utils/index.js:685:1

Any ideas what this could be? Is it anyways related to the API call rate associated with AWS?

Full Stack trace can be found here:
http://pastebin.com/wJuHpDWQ

Severless version used: 0.4.2

**Comment by ajagnanan** [comment]
Tracked on #688, looks fixed in 0.5 :smile:

**Comment by ac360** [comment]
Should be fixed in `v0.5`.  Thanks @aravindvalkodai and @ajagnanan
