### ISSUE TITLE
Allow support for external authorizer to an httpApi event

### ISSUE THREAD

**Issue by et304383** [serverless/serverless#7598]
# Feature Proposal

Allow support for external authorizer to an httpApi event.  Right now, serverless only supports specifying authorizer names referencing an authorizer created in the same serverless.yml file.

This is obviously not going to work when Cognito and the HTTP API are defined in another stack.

What's really bad about this, is that this was implemented with the same mistake as when Cognito authorizer support was added for the original API Gateway: no ability to specify an external authorizer on functions.

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
HTTP API and authorizer defined in another stack, as is typical in large serverless projects due to the CFN resource limit.

1. **Optional:** If there is additional config how would it look
I suspect the same config value could be used.  If the given name doesn't reference an authorizer in the same serverless file, assume it's a direct ID to be given to the CloudFormation value for Authorizer ID.

**Comment by medikoo** [comment]
@et304383 thanks for report

> Right now, serverless only supports specifying authorizer names referencing an authorizer created in the same serverless.yml file. This is obviously not going to work when Cognito and the HTTP API are defined in another stack.

That's not exactly true. What is created with a stack is _API Gateway Authorizer_, but otherwise  referenced JWT issuer (e.g. Cognito user pool) totally can be external. e.g. check our integration test that first generates a Cognito pool, and then creates an independent HTTP API service which attaches to it for authorization: https://github.com/serverless/serverless/blob/946d32cb48dbcdc3f02a8c1521b7f5cabf1eb1f9/tests/integration-all/http-api/tests.js#L39-L109

Let me know if I missed something.

**Comment by et304383** [comment]
Could you give the yaml in serverless.yml that makes this possible?

**Comment by medikoo** [comment]
> Could you give the yaml in serverless.yml that makes this possible?

It's well documented on our website, also you can see it in our integration tests. Nonetheless this is other example: https://github.com/medikoo/test-serverless/blob/fe0a2741f5e54ea1ed5724dfbf2a7852a5bdf523/serverless.yml

**Comment by medikoo** [comment]
See also https://serverless.com/blog/serverless-auth-with-aws-http-apis/

**Comment by et304383** [comment]
@medikoo  the example you posted is referencing an authorizer defined in the same file.  That's not what I'm asking for.  I'm asking for an easy way to have serverless reference an authorizer defined elsewhere, using Ref, a name, or ID.

**Comment by medikoo** [comment]
>  I'm asking for an easy way to have serverless reference an authorizer defined elsewhere, using Ref, a name, or ID.

You originally mentioned that both Cognito and HTTP API needs to be setup in same stack, and that's not true. I was answering to that.

Concerning HTTP API Authorizer (so `AWS::ApiGatewayV2::Authorizer` resource) it is specific to given HTTP API instance (afaik you cannot share it among different HTTP API's), so ideally needs to be defined in same place where HTTP API instance is defined.

Why do you wish to keep it separate? Also how do you imagine it to work? Can you setup a working example of few independent CloudFormation templates where for given HTTP API instance, HTTP API authorizer is defined in other template?

**Comment by et304383** [comment]
> You originally mentioned that both Cognito and HTTP API needs to be setup in same stack, and that's not true. I was answering to that.

I said no such thing.  I said that if Cognito and HTTP API are in a different stack then you cannot easily have serverless reference an authorizer by name or ID on a given function.  Serverless insists on creating the authorizer itself.

As per the title of my request, I want a way to specify an httpApi event and reference an authorizer by ID/Name, not just a reference to an authorizer created by serverless in the same stack under the provider.httpApi.authorizers section.

> Concerning HTTP API Authorizer (so `AWS::ApiGatewayV2::Authorizer` resource) it is specific to given HTTP API instance (afaik you cannot share it among different HTTP API's), so ideally it needs to be defined in same place where HTTP API instance is defined.

Of course.  That's not what I was asking about.

> Why do you wish to keep it separate? Also how do you imagine it to work? Can you setup a working example of few independent CloudFormation templates where for given HTTP API instance, HTTP API authorizer is defined in other template?

I never suggested specifying the authorizer separately from the API.  I asked specifically about referencing an authorizer from anywhere to use as the authorizer for an httpApi **event**.  IE - on a function.

**Comment by medikoo** [comment]
@et304383 sorry maybe I misunderstood you. Honestly I'm starting to be a bit lost. Let's maybe first clarify the players, as probably I may miss something.

In my understanding there are three different resources:
 - Cognito User Pool (independent of HTTP API.)
- HTTP API instance
- HTTP API authorizer specific to given HTTP instance (naturally to be defined together with a HTTP API instance)

Is that correct?

> I asked specifically about referencing an authorizer from anywhere to use as the authorizer for an httpApi event. IE - on a function.

So you want to be able to define in one stack HTTP API with its authorizers, and then in other stack endpoints for given HTTP API that rely on its authorizers? Is that correct?

**Comment by et304383** [comment]
@medikoo correct.

Cognito, HTTP API, and authorizer are all in one stack.

In another stack, I create functions and map them to API endpoints using the httpApi events.  I want to reference the authorizer from the other stack.

**Comment by medikoo** [comment]
Ok, thanks, glad we have that clarified out.

In that case, indeed there's no baked in support. I believe we can fix that by treating strings as passed to `authorizer` as external authorizer ids in case user is referring to external HTTP API

PR's welcome!

**Comment by benheymink** [comment]
@medikoo I've just hit this too. We use a shared API Gateway service that multiple other lambda services reference. If you're able to point me in the right direction with a few pointers, I'll have a stab at a PR?

**Comment by medikoo** [comment]
@benheymink thank you, we will appreciate it.

The way I see it, following needs to be done:
1. In [`resolveConfiguration`](https://github.com/serverless/serverless/blob/b6e54f06e26bffcb69360ad89edb9d07d78c624f/lib/plugins/aws/package/compile/events/httpApi/index.js#L180-L428) we need to:
   - Throw if there's `provider.httpApi.id` set (so we deal with external HTTP API) and some `authorizers` are configured in general `provider.http.authorizers` section
   - Accept `authorizer` settings on `httpApi` events as authorizer ids if we deal with external HTTP API (currently it'll throw not finding relevant authorizer in `provider.http.authorizers` section
2. In [`compileEndpoints`](https://github.com/serverless/serverless/blob/b6e54f06e26bffcb69360ad89edb9d07d78c624f/lib/plugins/aws/package/compile/events/httpApi/index.js#L139-L174) recognize external authorizer ids
3. Cover with tests in https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/httpApi/index.test.js

**Comment by mannharleen** [comment]
I've  just hit this as well! @benheymink  are you working on a PR? Else, I could take a stab

**Comment by benheymink** [comment]
@mannharleen Sorry, no - not had chance to. I actually worked around it by fudging some CF syntax into my serverless config:

```
# Attach an authorizer by ID to the route
resources:
  Resources:
    HttpApiRouteGetMy_func: # Note name is specific to this function if you're copying this block
      Type: AWS::ApiGatewayV2::Route
      Properties:
        AuthorizationType: JWT
        AuthorizerId: ${cf:some_name.apiAuthorizerId}
        RouteKey: 'GET /my_func' # Note RouteKey is specific to this function if you're copying this block
        ApiId: ${some_exported_api_id}
functions:
  my_func:
    handler: handler. my_func
    events:
      - httpApi:
          path: /my_func
          method: GET
```

**Comment by Michsior14** [comment]
> @benheymink thank you, we will appreciate it.
> 
> The way I see it, following needs to be done:
> 
> 1. In [`resolveConfiguration`](https://github.com/serverless/serverless/blob/b6e54f06e26bffcb69360ad89edb9d07d78c624f/lib/plugins/aws/package/compile/events/httpApi/index.js#L180-L428) we need to:
>    
>    * Throw if there's `provider.httpApi.id` set (so we deal with external HTTP API) and some `authorizers` are configured in general `provider.http.authorizers` section
>    * Accept `authorizer` settings on `httpApi` events as authorizer ids if we deal with external HTTP API (currently it'll throw not finding relevant authorizer in `provider.http.authorizers` section
> 2. In [`compileEndpoints`](https://github.com/serverless/serverless/blob/b6e54f06e26bffcb69360ad89edb9d07d78c624f/lib/plugins/aws/package/compile/events/httpApi/index.js#L139-L174) recognize external authorizer ids
> 3. Cover with tests in https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/httpApi/index.test.js

@medikoo 
Regarding the 1st point of proposed changes:
- Are we sure we don't want to allow creation of additional authorizers on the external `httpApi`? I think there will be some use cases where creation of separate authorizer for one http event would be nice.
- Shouldn't we handle external authorizer in similar way as it is in `restApi` section? From my point of view not doing it will just unnecessarily increase complexity.

**Comment by medikoo** [comment]
> Are we sure we don't want to allow creation of additional authorizers on the external httpApi?

I think it's better that API-wide uthorizers are defined together with the API, as that matches their scope (after all they can be used by all of HTTP API endpoints)

> Shouldn't we handle external authorizer in similar way as it is in restApi section?

Can you elaborate, how exactly? I think what I proposed is quite simple to implement and conflict-free.

**Comment by Michsior14** [comment]
> I think it's better that API-wide authorizers are defined together with the API, as that matches their scope (after all they can be used by all of HTTP API endpoints)

Ok ;)

> Can you elaborate, how exactly (?) I think what I proposed is quite simple to implement and conflict-free.

I meant by usage of `authorizerId` as in docs for [ApiGateway shared authorizer](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#share-authorizer).

**Comment by medikoo** [comment]
> I meant by usage of authorizerId as in docs for ApiGateway shared authorizer.

That's a good idea. Still let's use just `id` as property (same as we use `httpApi.id` and not `httpApi.httpApiId`).

**Comment by mannharleen** [comment]
@Michsior14 are you still working on this PR? Good work so far

**Comment by Michsior14** [comment]
> @Michsior14 are you still working on this PR? Good work so far

Just resolved the final suggestion. Hope it will be merged soon.
