### ISSUE TITLE
Turn off CloudWatch Log Group creation for _specific_ functions.

### ISSUE THREAD

**Issue by milesgranger** [serverless/serverless#7599]
# Feature Proposal
[Per documentation](https://serverless.com/framework/docs/providers/aws/guide/functions/):

> By default, the framework will create LogGroups for your Lambdas. This makes it easy to clean up your log groups in the case you remove your service, and make the lambda IAM permissions much more specific and secure.

Two points here:
1. It doesn't seem possible to turn this off in general, though it eludes it _can_ by the statement _"By default,"_

2. Could it be possible to deactivate log group creation for specific functions?

## Description
I have many `Custom::` resources in the template and some of these functions are cleanup type functions and thus run _after_ their log group is deleted by CloudFormation. Thereby leaving behind another log group. 

Then, redeploying with the same stage (say `production`) it will fail with the already existing log group. It would be super-duper if for the function used in this scenario to _not care_ if the log group exists by not bothering about creating it in the first place.

--> Manual deleting of log groups is not an option. <--

If there is a way to 'hook in' to the initial stack creation step and thereby have a custom resource to delete any pre-existing log groups with some known prefix would also be great, but that doesn't appear to be supported either.

**Comment by medikoo** [comment]
> It doesn't seem possible to turn this off in general, 

Yes that's true, but we will be happy to accept PR that enables opting out from this.

> Could it be possible to deactivate log group creation for specific functions?

We can add support for an option through logging for given functions could be turned off (e.g. via `disableLogs: true` setting

Other solution would be to add support for `resources.deletions` (as we support `resources.extensions` https://serverless.com/framework/docs/providers/aws/guide/resources#override-aws-cloudformation-resource) through that you'd be able to prevent given resource from being created.
But that'll serve more as dirty workaround.

Anyway we're open for PR's

**Comment by AhmedFat7y** [comment]
@medikoo 
check here if the flag is set and not create the log groups?
https://github.com/serverless/serverless/blob/e9726e2f7a831028738cb0f9e2358185d15dfa01/lib/plugins/aws/package/lib/mergeIamTemplates.js#L20-L42

**Comment by medikoo** [comment]
> @medikoo check here if the flag is set and not create the log groups?

@AhmedFat7y yes, it looks as right way to go!

**Comment by AhmedFat7y** [comment]
@medikoo 
I will need to add a test to check for `disableLogs` flag. Should I use the [@serverless/test/docs/run-serverless](https://github.com/serverless/test/blob/master/docs/run-serverless.md#run-serverless)? Or extend the current test suite following the its methodology? (Something like this](https://github.com/AhmedFat7y/serverless/commit/e0dc6882e11004882f42cefc25ca73839fab7d98#diff-c7d92d2a785047f47493a473cae48abe)

**Comment by medikoo** [comment]
@AhmedFat7y Ideally of you can use `run-serverless` (at some point we will probably rewrite current tests to it). You may put those in entirely new `describe` if it doesn't fit current setup well
