### ISSUE TITLE
AWS authentication handling is broken

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7605]
Currently we resolve AWS auth credentials from Framework specific env variables, and then to avoid eventual [process lock imposed by `aws-sdk`](https://github.com/aws/aws-sdk-js/issues/2983) we do not perfectly reliable checking on whether user is authenticated: https://github.com/serverless/serverless/blob/b3b51c1a50874eea85fdb72bedaf14928069baaa/lib/plugins/aws/lib/validate.js#L31-L55

Ideally, we should just ensure that authentication check on `aws-sdk` is not subject to process lock (that possibly will be fixed with https://github.com/aws/aws-sdk-js/pull/3204) and let AWS authentication go without any prior validation on our side.

**Comment by BogdanKushnirTR** [comment]
Current version 1.76.1 has breaking change for "sls package" command. Now it requires AWS credentials.
My question is this fix related to the problem?

**Comment by medikoo** [comment]
> Current version 1.76.1 has breaking change for "sls package" command

@BogdanKushnirTR I'm not aware of such change in v1.76.1, and I don't think above issue could influence how `sls package` works.

If you feel there's a bug, please open a bug report (respecting all its template remarks)
