### ISSUE TITLE
how to set up serverless for server side rendering webapp using lambda@edge and how to setup cloudfront distribution for it

### ISSUE THREAD

**Issue by sarathAvantari** [serverless/serverless#7611]
Please use https://forum.serverless.com, StackOverflow or other forums for questions.
This issue tracker is dedicated for bug reports and feature requests. Question issues might be closed immediately.

**Useful links:**

- [Official Serverless Forum](https://forum.serverless.com)
- [Official Serverless Slack Workspace](https://serverless.com/slack)
- [StackOverflow `serverless-framework` tag](https://stackoverflow.com/questions/ask?tags=serverless-framework) (need login)

**Comment by sarathAvantari** [comment]
this is my yml file..
service: angular-ssr

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  env: production
  region: us-east-1
  memorySize: 1920
  timeout: 29
  role: LambdaEdgeRole

package:
  exclude:
    - src/**
    - .idea/**
    - yarn.lock
    - babel.config.js
    - yarn-error.log
    - README.md
    - .gitignore
    - serverless.copy.yaml
    - .git
    - node_modules/**
    - node_modules/
    - '!node_modules/aws-serverless-express/**'
    - '!node_modules/binary-case/**'
    - '!node_modules/mime-types/**'
    - '!node_modules/type-is/**'
    - '!node_modules/media-typer/**'

functions:
  CloudfrontLambda:
    handler: lambda.ssrserverless
    events:
      - cloudFront:
          eventType: viewer-request
          origin: ${self:custom.origins.myWebsiteOrigin}
custom:
  origins:
    myWebsiteOrigin:
      DomainName: smartdhyana.com
      OriginPath: /test
      CustomOriginConfig:
        OriginProtocolPolicy: match-viewer

resources:
  Resources:
    LambdaEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          - PolicyName: LambdaEdgeExecutionRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:*:*:*"

**Comment by medikoo** [comment]
@sarathAvantari this issue tracker is reserved for bug reports and feature requests. Please use https://forum.serverless.com, StackOverflow or other forums for questions.
