### ISSUE TITLE
How to add `IncludeBody` parameter for Lambda@edge

### ISSUE THREAD

**Issue by kingkong123** [serverless/serverless#7614]
I am trying to create a few Lambda@edge functions, and found that there is no instruction on setting the `IncludeBody` value.

I understand that under the `behavior` section can set the behavior of the cloudFront and in the `resources` section can define the `DistributionConfig` of CloudFront

Is there any way to set the `IncludeBody` value?

**Comment by medikoo** [comment]
@kingkong123 as I see there's currently no support for this option in the Framework, still I believe it can easily be added. PR's welcome!

**Comment by kingkong123** [comment]
@medikoo, thank for the reply, let me take a look and see if I have time to make a PR, still checking if I need this in my project.
