### ISSUE TITLE
automating dash deploy ?

### ISSUE THREAD

**Issue by connaryscott** [serverless/serverless#763]
what do these options do?

Would providing such options on the command line avoid interactive execution so that it can be automated.  If so, are there any examples of what arguments the would take?  It is not even clear that they arguments, but that goes for all of your documentation thus far,.

```
 -f, --aliasFunction 
        Optional - Provide a custom Alias to your Functions

  -e, --aliasEndpoint 
        Optional - Provide a custom Alias to your Endpoints

  -a, --aliasRestApi 
        Optional - Provide a custom Api Gateway Stage Variable for your REST API
```

there does not seem to be any examples.  Would be nice...

**Comment by flomotlik** [comment]
With an upcoming version of Serverless we will make sure that all actions can be run in a non-interactive mode. I will close this issue for now as this feature is already planned.
