### ISSUE TITLE
https://serverless.com certificate error

### ISSUE THREAD

**Issue by bnusunny** [serverless/serverless#7636]
When I open https://serverless.com, Chrome reports "Your connection is not private". 

The certificate name is china.serverless.com, which does not match the URL. 

<img width="795" alt="serverless_website_issue" src="https://user-images.githubusercontent.com/12918/80556600-a6bc0c00-8a06-11ea-9b3f-bdae2d590f9b.png">

**Comment by medikoo** [comment]
@bnusunny thanks for report. We were updating DNS configuration of our domain, and I believe error should now be gone.

Can you confirm all is well on your side now?

**Comment by bnusunny** [comment]
Yes, it is back to normal now.
