### ISSUE TITLE
AWS templates no longer available when creating a new project in China

### ISSUE THREAD

**Issue by bnusunny** [serverless/serverless#7637]
# Bug Report

## Description

1. What did you do?

   Create a new project for AWS Lambda using serverless framework. 

1. What happened?

AWS templates no longer available as options. All three options require Tencent cloud accounts. 

```bash

$ sls
Serverless: 当前未检测到 Serverless 项目，是否希望新建一个项目？ Yes
Serverless: 请选择你希望创建的 Serverless 应用 (Use arrow keys)
❯ Express.js app
  SCF Function
  Website app

```

3. What should've happened?

I expected to be able to select AWS templates as before. 

```bash

$sls
Serverless: No project detected. Do you want to create a new one? Yes
Serverless: What do you want to make? (Use arrow keys)
❯ AWS Node.js
  AWS Python
  Other

```

It seems you are directing all users in China to Tencent cloud. There are many AWS users in China. They are confused. Can you please add AWS options for Chinese users? 

https://github.com/serverless/components/pull/567

**Comment by medikoo** [comment]
@bnusunny thanks for report. Indeed we should provide a way to trigger an AWS interactive CLI from China as well.

We'll sort out some option that will allow to bring back previous behavior

**Comment by hkbarton** [comment]
@bnusunny thanks for the feedback! you can actually put `SERVERLESS_PLATFORM_VENDOR=aws` in your `.env` file, and `sls` will use AWS as provider. Although seems like there is no on-boarding flow for AWS provider, and we'll look into that.

**Comment by bnusunny** [comment]
@hkbarton  This is bad user experience for anyone not using Tencent cloud in China. Not sure what on-boarding flow you are talking about. The previouse behavior is good, no need to add additional steps.

**Comment by medikoo** [comment]
@bnusunny you can restore AWS interactive CLI via setting `SERVERLESS_PLATFORM_VENDOR=aws` env var.

**Comment by bnusunny** [comment]
Would appreciate to add this in the documentation.

**Comment by medikoo** [comment]
@bnusunny that'll be improved with https://github.com/serverless/serverless/pull/7717
