### ISSUE TITLE
v0.5 - s-function.runtime doesn't support template

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#764]
low priority, probably worth delaying until https://github.com/serverless/serverless/issues/681 is resolved by universal template and variable support.

s-template:
`    "runtimeTemplate": "nodejs"`
s-function:
`    "runtime": "$${runtimeTemplate}"`

$sls dash summary
/src/serverless/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^

ServerlessError: Runtime $${runtimeTemplate} is not supported!
    at new ServerlessError (/src/serverless/lib/Error.js:17:11)
    at Function.setRuntime (/src/serverless/lib/Function.js:159:13)
    at new Function (/src/serverless/lib/Function.js:44:10)
    at /src/serverless/lib/SerializerFileSystem.js:72:24
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by flomotlik** [comment]
I will close this specific issue as universal template/variable support will be implemented and cover this then. Its tracked in separate issues
