### ISSUE TITLE
sls rollback function does not recognize version input

### ISSUE THREAD

**Issue by aizulhussin** [serverless/serverless#7645]
Hi,

Appreciate any feedback on this. Is it a known bug or something wrong with the way i execute 
this command?
`sls rollback function --function -f test-sls-rollback-dev-hello --version 8`

returns error:
` "8" is not a valid sub command. Run "serverless rollback function" to see a more helpful error message for this command.`

serverless framework details:
-   Operating System:          linux
-      Node Version:              10.19.0
-      Framework Version:         1.69.0
-      Plugin Version:            3.6.9
-      SDK Version:               2.3.0
-      Components Version:        2.30.4

**Comment by medikoo** [comment]
@aizulhussin great thanks for that report.

Technically it's a bug, that's a side effect result of applying fix for other bug here: https://github.com/serverless/serverless/pull/7131

Situation now is, that `--version` conflicts with core `--version` param, which is boolean (a request to show version of a framework)

Real fix for that would be to rename `--version` param of this command into `--function-version`

**Comment by medikoo** [comment]
PR that fixes that is welcome.

It should be as easy as updating this internal plugin: https://github.com/serverless/serverless/blob/bd9fbfb392afc2dc95f7d83864bfdc4dc1602728/lib/plugins/aws/rollbackFunction/index.js

**Comment by AhmedFat7y** [comment]
I would like to apply that fix

**Comment by medikoo** [comment]
@AhmedFat7y that'll be great, thank you!
