### ISSUE TITLE
v0.5 dash summary displays events that aren't defined

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#765]
1 function with 1 endpoint is defined.  events is set to an empty array:
s-template:
`  "eventsTemplate": []`
s-function
`  "events": "$${eventsTemplate},`

Observed:
```
$slsDev dash summary
[...]
Serverless: 1 functions --------------------------  
Serverless:     |_ [FUNCTION] (1 endpoints - 1 events)  
Serverless:             |_ GET [PATH] (endpoint)  
Serverless:             |_ mySchedule (schedule event)  
```
Expected:
```
$slsDev dash summary
[...]
Serverless: 1 functions --------------------------  
Serverless:     |_ [FUNCTION] (1 endpoints - 0 events)  
Serverless:             |_ GET [PATH] (endpoint)  
```

**Comment by erikerikson** [comment]
Probably to be pushed off until https://github.com/serverless/serverless/issues/681 is resolved.  This does not occur if templates are not used.

**Comment by eahefnawy** [comment]
For progress on this issue, and probably other related issues as well, we've decided to switch to JSON-REF for template handling starting in v1 (can't believe we haven't done so long time ago!). This will probably solve a lot of painful template handling issues we've been having.

**Comment by pmuens** [comment]
Thanks for reporting! @eahefnawy could reproduce this one on my windows machine.

**Comment by flomotlik** [comment]
As this bug should be resolved implicitly by the V1 syntax and changes I will close it here.
