### ISSUE TITLE
Missing required key 'deploymentId' in params

### ISSUE THREAD

**Issue by allexxis** [serverless/serverless#7650]
# Bug Report

## Description

1. What did you do?
 SLS_DEBUG=* serverless deploy
1. What happened?
The stack and cloudformation resource was created but i'm recieving the erro on the title  and error in serverless dashboard.

![error](https://user-images.githubusercontent.com/17753023/80825004-c8e79280-8b9c-11ea-9e41-5d92350c1d1d.png)

![unknown](https://user-images.githubusercontent.com/17753023/80824868-81f99d00-8b9c-11ea-8baa-c86ed00d2c24.png)
1. What should've happened?
Recieve no errors from the deploy
1. What's the content of your `serverless.yml` file?

[serverless.txt](https://github.com/serverless/serverless/files/4565456/serverless.txt)

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

[serverless_bug.txt](https://github.com/serverless/serverless/files/4565418/serverless_bug.txt)

Similar or dependent issues:
- #7610

**Comment by medikoo** [comment]
@allexxis great thanks for report. Will be fixed with #7663
