### ISSUE TITLE
CodePipeline working fine but code build giving issue

### ISSUE THREAD

**Issue by asitP9** [serverless/serverless#7653]
# 7641

## I am just making a dynamodb and linking my codecommit with code pipeline and code build, but in code build its giving an issue inside buildspec.yml inside build (sls deploy -v -s  $ENV_NAME)

1. What did you do?
I only created pipeline with my local code, already committed through code commit
1. What happened?
Error in buildspec.yml file, "Access Denied, Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: serverless deploy --verbose --stage prod. Reason: exit status 1"
1. What should've happened?
It should have successfully created the pipeline
1. What's the content of your `serverless.yml` file?
`version: 0.2

phases: 
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless

  pre_build:
    commands:
      - echo Install source NPM dependencies...
      - npm install  

  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the serverless Framework
      # - sls deploy -v -s $ENV_NAME
      - sls deploy --verbose

  post_build:
    commands:
      - echo Deployment completed on `date``
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Not yet did this
Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@asitP9 are you sure it's a report for Serverless Framework? Note that content you provided for ` serverless.yml` doesn't resemble a known configuration format.

**Comment by AhmedFat7y** [comment]
@asitP9 
It seems like you're trying to deploy a service from within `aws-code-build`. The `Access Denied` error means you're missing permissions in the role assigned  to the `aws-code-build` project

**Comment by medikoo** [comment]
Closing as it does not seem to belong into this repository

**Comment by ASHRAF-BEHLIM** [comment]
Go to IAM and create a role and give full  permission to codecommit and codepipeline it will work
