### ISSUE TITLE
Installation of serverless using npm failed for global option

### ISSUE THREAD

**Issue by jayachandranm** [serverless/serverless#7654]
# Bug Report

## Description

Tried to install serverless on Ubuntu-19.10 using node/npm option. 

Node version: 10.20.1
npm version: 6.13.3

The installation did not succeed.

Trying to install locally without the -g option was successful.

1. What did you do?

Run command,
sudo npm install -g serverless

1. What happened?

Failed with error,
--
Failed at the core-js@3.6.5 postinstall script.
--

1. What should've happened?

serverless successfully installed.

1. What's the content of your `serverless.yml` file?
NA

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Relevant installation log file attached.
[serverless_install_err.log](https://github.com/serverless/serverless/files/4567052/serverless_install_err.log)

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@jayachandranm thanks for report.

It appears it's due to unexpected dependency on `core-js`. I've opened dedicated issue at the source: https://github.com/serverless/components/issues/620

Please follow it for the progress on that

**Comment by jayachandranm** [comment]
Hi @medikoo, thanks for following up. I saw the fix from [https://github.com/serverless/components/issues/620](https://github.com/serverless/components/issues/620). Tried again today. Now I have new error,

> error Failed at the serverless@1.69.0 postinstall script.

Should I file a new issue?

**Comment by medikoo** [comment]
> Should I file a new issue?

Yes, you may. Please then provide all system info (OS type, Node.js and npm version) and full output from `npm install`
