### ISSUE TITLE
"Packaging: No files found" when package individually

### ISSUE THREAD

**Issue by TheMechanic** [serverless/serverless#7670]
Hi,

I juste migrate my serverless project into multi microservices, kept in a "services" folder. But now, trying to deploy each one, it doesn't deploy if I set package individually to true in my serverless.yml file, giving error : "Packaging: No files found". This appears just after webpack finishes its work.
 Is it a bug or am I missing something ?

Thanks !

**Comment by TheMechanic** [comment]
Ok, here is the thing :

my tree:

```
authorizer.js
services/
     todo/
         handler.js
         serverless.yml
```

in the serverless.yml:
```
usersauthorize:
  handler: ../../authorizer.authorize
createtodo
  handler: handlers.create
 ....
```

in this, case, the authorizer.js is not built inside the .webpack folder, but set at the same level than handler.js. In .webpack folder, we just find a authorizer folder empty, causing the error.

To fix it, I move the call of the authorizer inside my handler.js, which call internally the authorizer.js file.

So, is it an expected behaviour, and my first attempt a bad practice, or a bug ?

**Comment by medikoo** [comment]
@TheMechanic I believe this question belongs to Webpack plugin repository. Can you move it there?

**Comment by medikoo** [comment]
Closing as it does not seem to belong into this repository
