### ISSUE TITLE
Env variables are included in CloudFormation template for lambda@edge

### ISSUE THREAD

**Issue by alexblackby** [serverless/serverless#7671]
Lambda@edge restrictions do not allow environment variables for functions. When environment variables are set in global "provider" section there is no way to clear environment variables on the function level. 
It will be nice if serverless will not include VPC or Env.vars in the CloudFormation template for function when this function is aimed to be lambda@edge

**Comment by medikoo** [comment]
@alexblackby great thanks for pointing that, and what exactly happens now, when they're included? Does deployment fail with an error, or are they just ignored?

**Comment by alexblackby** [comment]
@medikoo sls deploy failed with error "VPC is not allowed for this function" or "environment variables is not allowed for this function". 
Workaroud - to move environment variables from "provider" section to custom and set for each other lamdas manually.

**Comment by medikoo** [comment]
Thank you. It's definitely a bug, PR that fixes that issue is welcome!

**Comment by AhmedFat7y** [comment]
@medikoo Is it acceptable to attach a `isLambda` variable to function object? or this is intended to reflect the actual configuration only?
The function is prepared first by the `cloudfront` event, then env vars are added later. I'm trying to pass info from `cloudfront` event preparation to mark this function as `lambda@edge` so we can make more decisions later on if needed

**Comment by medikoo** [comment]
> Can I give it a try?

@AhmedFat7y definitely, Thank you!
