### ISSUE TITLE
AWS_DEFAULT_PROFILE seems not supported by profile resolver

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#7676]
There is no `[default]` in the `~/.aws/credentials` or `~/.aws/config`, to set and change profiles, the `AWS_DEFAULT_PROFILE` environment variable is used for `awscli`.  But something in `sls package` is defaulting back to a `default` profile?

```
Serverless: Installing dependencies for custom CloudFormation resources...
 
  Serverless Error ---------------------------------------
 
  Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.20.1
     Framework Version:         1.68.0
     Plugin Version:            3.6.9
     SDK Version:               2.3.0
     Components Version:        2.30.4
 
```

**Comment by medikoo** [comment]
@dazza-codes can you clarify in more details what's exactly your setup, and what you expect to happen?

Do you have e.g. `foo` profile configured in `~/.aws/credentials` and `~/.aws/config`, and `AWS_DEFAULT_PROFILE` set to `foo`, and you see it not resolved in a Framework?

**Comment by dazza-codes** [comment]
> Do you have e.g. `foo` profile configured in `~/.aws/credentials` and `~/.aws/config`, and `AWS_DEFAULT_PROFILE` set to `foo`, and you see it not resolved in a Framework?

Yes, exactly.

```sh
export AWS_DEFAULT_PROFILE=foo
```

```
##  ~/.aws/credentials
##  NO [default]
[foo]
... etc etc ..
```

**Comment by medikoo** [comment]
@dazza-codes is `AWS_DEFAULT_PROFILE` env var supported naturally by AWS SDK?

**Comment by dazza-codes** [comment]
@medikoo - yes, the `AWS_DEFAULT_PROFILE` is sufficient for `awscli` to get everything required from `~/.aws/credentials`

**Comment by medikoo** [comment]
@dazza-codes thanks for further details. I believe problem lies in this line: https://github.com/serverless/serverless/blob/b53f080a4dfc8439333090d2a177ac0272b6d1fe/lib/plugins/aws/provider/awsProvider.js#L369

As there we assume that _default_ profile is `default`, where I believe we should respect `AWS_DEFAULT_PROFILE`.

PR with fix is welcome!

**Comment by marekpiotrowski** [comment]
I'd like to take this one. Seems relatively easy, change in the implementation should be small, I will focus on tests, though. Let me know.  Thank you.

**Comment by medikoo** [comment]
@marekpiotrowski great to hear that! We look forward

**Comment by marekpiotrowski** [comment]
Pull request created: https://github.com/serverless/serverless/pull/8354
Thanks.
