### ISSUE TITLE
Installation of serverless using npm failed for global option (2)

### ISSUE THREAD

**Issue by jayachandranm** [serverless/serverless#7681]
Tried to install serverless on Ubuntu-19.10 using node/npm option checking the fix related to core-js [https://github.com/serverless/components/issues/620](https://github.com/serverless/components/issues/620). 

`sudo npm install -g serverless`

Still installation failed, but this time with error,

> error Failed at the serverless@1.69.0 postinstall script.

Node version: 10.20.1
npm version: 6.13.3

Relevant log file attached.
[serverless_install_err_2.log](https://github.com/serverless/serverless/files/4586293/serverless_install_err_2.log)

**Comment by medikoo** [comment]
@jayachandranm Can you paste full output of `sudo npm install -g serverless` (that include both stdout and stderr output)

Log you've attached seem to contain only some debug log which goes to stdout. While all valuable error information is in stderr

**Comment by jayachandranm** [comment]
@medikoo I have separated the stdout and stderr. Attached the two log files.
[serverless_install_err.log](https://github.com/serverless/serverless/files/4590134/serverless_install_err.log)
[serverless_install_out.log](https://github.com/serverless/serverless/files/4590135/serverless_install_out.log)

**Comment by medikoo** [comment]
@jayachandranm Thanks, still those logs do not expose what happens in child processes as `./scripts/postinstall.js`. Without having that information, we're still not able to diagnose anything.

See below screenshot on how usually in normal setup such errors are reported (see "Some error" stack trace)

![Screenshot 2020-05-07 at 10 51 09](https://user-images.githubusercontent.com/122434/81274652-deebcc00-9050-11ea-98d8-1be38999cd6f.png)

**Comment by jayachandranm** [comment]
@medikoo somehow I don't see those stack traces. Do I have to enable the debug option somewhere? I just run the command,

`npm install -g serverless > out log 2> err.log`

**Comment by medikoo** [comment]
@jayachandranm what OS you're using? Maybe just show the screenshot from terminal as I did above

**Comment by jayachandranm** [comment]
@medikoo I am using Ubuntu 19.10. Attached the screenshot of my terminal.

![serverless_install_screenshot](https://user-images.githubusercontent.com/8652282/81360998-c8f11080-910f-11ea-97e7-eb42abebf7ad.png)

**Comment by medikoo** [comment]
@jayachandranm see the `cmd_run.go:95` warning. it signals there are either permissions issues or you have broken node installation (`nonexistent/snap/node` sounds alarming).

It looks as some issue with your setup and not Framework itself.

**Comment by jayachandranm** [comment]
@medikoo thanks for that tip. I looked at my node installation. I installed the nodejs from Ubuntu's snap packages and there seems to be a problem for installing global dependencies with snap based packages. Now I have to figure out the best approach for installing serverless. 

I really appreciate your time and of others in attending to this issue and for maintaining this great tool!

Should I now close this issue?

**Comment by medikoo** [comment]
> Should I now close this issue?

Yes, I take we coined the source of the issue, and is not in the scope of this project, therefore please close it. Thank you!

**Comment by jayachandranm** [comment]
The issue is related to the installation of nodejs using the snap package on Ubuntu.

**Comment by jayachandranm** [comment]
Just to help anyone who faces the same issue, I uninstalled the snap version of **nodejs** and installed using the deb file from nodesource. Now serverless installs without any failures.
