### ISSUE TITLE
serverless cron is not working with type error 'path'

### ISSUE THREAD

**Issue by fengo4142** [serverless/serverless#7683]
Hi, I wanted to run a schedule job on serverless offline, but not able to run due to below error.

https://stackoverflow.com/questions/61625597/serverless-offline-schedule-error-typeerror-err-invalid-arg-type-the-path

I think that error is just because there are no type checking for path of 'serverless.yml' which indicates handler function. 
As you see below code, customPath can be string or array of strings when I run depending on the number of lamda functions in each service. 
string case: 'serverless.local.yml'
arrary case: ['serverless.local.yml', 'serverless.local.yml'] 
```

> /node_modules/serverless/lib/classes/Utils.js

findServicePath(customPath) {
    let servicePath = null;
    console.log(customPath, "----------")

    if (customPath) {
      if (fileExistsSync(path.join(process.cwd(), customPath))) {
        servicePath = process.cwd();
      } else {
        throw new Error(`Config file ${customPath} not found`);
      }
    } else if (fileExistsSync(path.join(process.cwd(), 'serverless.yml'))) {
      servicePath = process.cwd();
    } else if (fileExistsSync(path.join(process.cwd(), 'serverless.yaml'))) {
      servicePath = process.cwd();
    } else if (fileExistsSync(path.join(process.cwd(), 'serverless.json'))) {
      servicePath = process.cwd();
    } else if (fileExistsSync(path.join(process.cwd(), 'serverless.js'))) {
      servicePath = process.cwd();
    }

> /node_modules/serverless/lib/Serverless.js

    // use the servicePath from the options or try to find it in the CWD
    this.cliInputArgv = process.argv.slice(2);
    configObject.servicePath =
      configObject.servicePath ||
      this.utils.findServicePath(resolveCliInput(this.cliInputArgv).options.config);
```

**Comment by medikoo** [comment]
@fengo4142 Thanks for report. Indeed `config` should be validated in `resolveCliInput`, and crash if more than one input is detected.

PR's welcome!

**Comment by AhmedFat7y** [comment]
@fengo4142 Could you possible provide the command that raised this issue?

@medikoo There are 2 ways to validate this

1. Disable this flag `duplicate-arguments-array` in `yargs-parser`. [Reference](https://github.com/yargs/yargs-parser#duplicate-arguments-array). This will just take the latest value provided
```bash
node example.js -x 1 -x 2
{ _: [], x: 2 }
```
1.  Check the value of `config` after parsing to make sure it's a single string. We can then crash on multiple values

**Comment by medikoo** [comment]
@AhmedFat7y I would go with second one. First one indeed will help in this given case (where same config option was provided twice), but we still need to be resilient to case where two different values are provided, and also I think it's not that bad to report with an error on duplicate input

**Comment by AhmedFat7y** [comment]
will work on it
