### ISSUE TITLE
Superfluous `async` dependency

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7686]
https://github.com/serverless/serverless/blob/3a8014089033887621de32b57eed4511616b635f/package.json#L164

We're relying on `async`, while ideally we should purely resort to promises.

Code that depends on `async` should be  refactored to rely on native `Promise` (or if that's proven difficult, then to `bluebird`)

**Comment by andrewpuleo** [comment]
Hi @medikoo, new contributor here. May I make a PR for this?

**Comment by medikoo** [comment]
> Hi @medikoo, new contributor here. May I make a PR for this?

Absolutely! Thank you

**Comment by andrewpuleo** [comment]
Looks like the only `async` dependency is a call to `whilst` in `lib/plugins/aws/lib/monitorStack.js`. I looked at the `whilst` implementation and am working on writing a replacement. Any advice is welcome!

**Comment by medikoo** [comment]
@andrewpuleo I think it can be refactored into recursive promise returning function:

```javascript
const recursivePromiseFn = () =>
  logic().then(() => {
    if (shouldContinue()) return recursivePromiseFn();
  });

recursivePromiseFn().then(onSuccess);
```
