### ISSUE TITLE
v0.5 - s-template ignored if not at root or peer of s-function

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#769]
Structure:
```
~/s-project.json
  ...
  myApi/s-template.json
        myFunc/
               get/s-function.json
                   ...
```
Executed: sls function deploy ...

Observed:
Many "Serverless: WARNING: the following template is requested but not defined: [template] in [function]" messages

Expected:
templates that are defined in the single s-template.json should be used to hydrate the function data.

Workaround:
move the s-template.json file to the root of the project.

Consequence:
applying your s-template to only a limited scope (so as to apply to a single aspect of the project) is not allowed.

**Comment by HyperBrain** [comment]
I used the following setup (on `#master`) and it worked.
```
s-project.json
s-templates.json
myComponents/
  myFunc1/s-template.json
  myFunc2/s-template.json
```
All templates were merged correctly within the correct scopes `myFunc1` and `myFunc2`
I did not try to add an additional level at `myComponents` though

**Comment by Whoaa512** [comment]
@HyperBrain yes that setup seems to work even on the published v0.5.5. I believe is issue presents itself when you try to add a template at the `myComponents/` level

**Comment by eahefnawy** [comment]
For progress on this issue, and probably other related issues as well, we've decided to switch to JSON-REF for template handling starting in v1 (can't believe we haven't done so long time ago!). This will probably solve a lot of painful template handling issues we've been having.

@erikerikson @HyperBrain @Whoaa512 what do you think about this change? do you think it might affect your workflow in any negative way?

**Comment by HyperBrain** [comment]
In general that's a great idea and will lead to better control over the templates.
There is one caveat: Currently the templates are hierarchical, i.e. the function templates extend the project templates, and every function can set similar named templates to make function definitions easier. If we'd completely drop the inheritance and replace it by JSON-REF we have to define the order/origin, where templates are started to be evaluated for functions.
IMHO the JSON-REF semantics would dictate a templates files evaluation starting within the function folder, as the more specialized template files should ref the global ones.
Example: myFunc1 from above
So, if you have a "$ref": "myTemplate" reference in your myFunc1/s-function.json it should begin the search in myFunc1/s-templates.json and then proceed further to the outside until it is in the project root. This should work, even if the reference is redirected in the referenced file.

@eahefnawy One central question. Would we allow unqualified references, or only file references or both as JSON-REF targets (event remote references are scope of the standard!)? I think this should be defined as it might change or even invalidate my statement from above.

**Comment by erikerikson** [comment]
Been meaning to reply on this one for along time...

Thanks for checking this out @HyperBrain.  The point that @Whoaa512 made is relevant.  Originally, I had s-templates.json files at all three levels (for some cases) and the middle tier was being ignored.  If I recall correctly, I tried to isolate further and found the more general behavior described herein.

@eahefnawy Frank's caveat identifies a useful feature that would be lost.  The overriding multi-level inheritance/merge pattern provides value and brevity to project specifications.  That said, it definitely creates value to allow for JSON-REF capabilities so that something like a VTL transform can be specified as a piece of independent logic with its own "living space" as given by the file.  Do I misunderstand your proposed change?

Sorry for the delay in following up.

**Comment by erikerikson** [comment]
@eahefnawy @ac360 Do you believe that someone implementing a solution like I described in https://github.com/serverless/serverless/issues/722#issuecomment-191952747  sufficiently resolve the template and variable resolution problems?  Would it cause other problems that would be difficult to resolve?

**Comment by erikerikson** [comment]
Also, if I poorly communicated the notion there, let me know and I can attempt greater clarity

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
