### ISSUE TITLE
Duplicated logic due to `@serverless/inquirer` seclusion

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7690]
Some of the [logic](https://github.com/serverless/serverless/blob/763a9a3a36212638197eb360e77cc2f477f3fcf5/lib/plugins/interactiveCli/inquirer.js) was secluded to [@serverless/inquirer](https://www.npmjs.com/package/@serverless/inquirer).

Repo should be updated to rely on `@serverless/inquirer` instead of internal `lib/plugins/interactiveCli/inquirer.js` module

**Comment by AhmedFat7y** [comment]
It seems like a case of find all and replace, no?

**Comment by medikoo** [comment]
Yes, it's simply about removing internal module, and using `@serverless/inquirer` instead. Straightforward, with no surprises on the road :)

**Comment by AhmedFat7y** [comment]
Will do
