### ISSUE TITLE
Outdated `json-refs` dependency

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7691]
https://github.com/serverless/serverless/blob/3a8014089033887621de32b57eed4511616b635f/package.json#L189

We're relying on v2, while we can [safely](https://github.com/whitlockjc/json-refs/blob/master/RELEASE_NOTES.md#v300-2017-04-25) (without breaking support for Node.js v6) upgrade to v3

By changelog it may seem that upgrade requires no changes, still when I tried to update tests started to fail. Therefore it needs to be done with care with complete understanding of what changed and why update to code is needed

PR's welcome!

**Comment by fredericbarthelet** [comment]
It is not listed as a breaking change, but json-refs changelog states that from v3 onwards : `Removed options.relativeBase as it's too confusing and easier to get right using options.location`. The `relativeBase` option is being used in `lib/classes/YamlParser.js`, will make a PR and check if that's the only BC.

**Comment by medikoo** [comment]
Thank you @fredericbarthelet !
