### ISSUE TITLE
Set unreserved concurrency for AWS Lambda

### ISSUE THREAD

**Issue by DavidEspinosa42** [serverless/serverless#7695]
### Use case description

Hi, in AWS Lambda we have 3 possible reserved concurrent executions, A max limit, Zero(will disable the execution) and unreserved(will use the AWS account concurrency limit).
With serverless we can only explicitly define the first two. 

### Proposed solution

I would like to be able to use "-1", the same parameter that terraform uses for this: https://www.terraform.io/docs/providers/aws/r/lambda_function.html#reserved_concurrent_executions

This will be really useful for my team because we need to set unreserved for some environments and limit the concurrency for others.
Can I submit a pull request to add this feature?

**Comment by medikoo** [comment]
@DavidEspinosa42 great thanks for that proposal

I believe in Framework not setting `reservedConcurrency` (or setting it to `null` or `undefined`) would actually set _unreserved_ concurrency. Isn't that the case?

**Comment by DavidEspinosa42** [comment]
Interesting!
Setting reservedConcurrency to undefined threw this error:

> You should use integer as reservedConcurrency value on function: xxxxxxxxxxxx

But setting it to null worked perfectly.
Thanks!

**Comment by medikoo** [comment]
> Setting reservedConcurrency to undefined threw this error:

I'd call it a bug.

Anyway, not setting `reservedConcurrency` at all, should have same effect
