### ISSUE TITLE
Security Vulnerabilities of Serverless Dashboard (no SERVERLESS_ACCESS_KEY needed?)

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [serverless/serverless#7697]
I find the org option in the serverless.yml file to be very unclear. I know that I created a Serverless Dashboard account. Inside the Dashboard account, I created a 'profile' to connect to my AWS account, which created an AWS IAM Role specific for the Serverless Framework to do temporary access roles. In fact, when I look at the profile in the Serverless Dashboard, I notice the IAM role. Then in 'applications' in Serverless Dashboard, I added a stage 'dev' and linked it to the 'deployment profile' which has the information of the AWS IAM role. And I created an 'Access Key' in Serverless Dashboard as well. 

When I create a new Serverless Project on my local machine (OSX) and specify org as the same org in Serverless Dashboard, my application is able to gain access to aws (e.g. ssm in serverless.yml can communicate with AWS ) without any additional credentials. It seems 'app' and 'org' in serverless.yml is all that you need to gain access to serverless dashboard and thus my AWS account. I find that scary. Why isn't the SERVERLESS_ACCESS_KEY required? I don't have SERVERLESS_ACCESS_KEY anywhere in my environment (e.g. echo $SERVERLESS_ACCESS_KEY produces nothing ) yet my app can still talk to the serverless dashboard.

One of the reasons why I am bringing this up is because I tried to run serverless-offline inside Docker locally and it complains it has no access to SSM. So it's not clear what the 'org' is doing.

**Comment by lovefamilychildrenhappiness** [comment]
I was able to get it running through Docker by explicitly adding SERVERLESS_ACCESS_KEY to .env of dotenv. So interesting that it needs this value inside the container and it needs this value when executing in a container on AWS CodeBuild. But it does not need this value when executing from my terminal on my OSX. It doesn't make sense. But I am 100 percent sure I do not have this SERVERLESS_ACCESS_KEY environment variable in my OSX shell.

**Comment by medikoo** [comment]
@lovefamilychildrenhappiness please use https://forum.serverless.com/ for questions.
One of our member will be happy to clarify for you how it works and that there's no security issue.
