### ISSUE TITLE
AWS Events - PreSignUpCustomCognitoUserPool1 - Failed to create resource.

### ISSUE THREAD

**Issue by adir1661** [serverless/serverless#7711]
when deploying my sls project, i am having an error that prevents me from deploying:
 ```
ServerlessError: An error occurred: PreSignUpCustomCognitoUserPool1 - Failed to create resource. Cannot read property 'Id' of null See details in CloudWatch Log: 2020/05/10/[$LATEST]026a573177ec4f98878
74ab1cc9a66e4.
```

<details>
<summary><code>serverless.yml</code></summary>

```
service: test
custom:
  userPoolName: cover-${self:provider.stage}
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'} 
functions:
  preSignUp:
     handler: confirm.preSignUp
     events:
     - cognitoUserPool:
        pool: CoverUserPool
        trigger: PreSignUp
        existing: true  
resources:
  Resources:
    CognitoUserPoolCoverUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        MfaConfiguration: OFF
        UserPoolName: ${self:custom.userPoolName}
        UsernameAttributes:
        - email
        AutoVerifiedAttributes:
        - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: False
        Schema:
        - AttributeDataType: String
          Mutable: true
          Name: role
          Required: false
          DeveloperOnlyAttribute: true
        - AttributeDataType: String
          Mutable: true
          Name: providerId
          Required: false
          DeveloperOnlyAttribute: true
```

</details>

<details>
<summary><b><code>deploy</code> output</b></summary>

```
sls deploy --stage prod
```

</details>

<b>Installed version</b>

```
??/??>sls -v
Framework Core: 1.66.0
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3
```

**Comment by medikoo** [comment]
@adir1661 you're not using latest version of a Framework. Please update

**Comment by adir1661** [comment]
after upgrading to this version:

```
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.1
     Framework Version:         1.70.1
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10

```

still exact same error @medikoo

**Comment by slink1811** [comment]
I have the same error:

 ```
     Operating System:          darwin
     Node Version:              14.2.0
     Framework Version:         1.70.1
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10
```
` An error occurred: PostConfirmationCustomCognitoUserPool1 - Failed to create resource. Cannot read property 'Id' of null See details in CloudWatch Log`

**Comment by medikoo** [comment]
@adir1661 please respect all template remarks, and all answer questions in full, e.g. content of `serverless.yml` you provided doesn't seem to be complete

**Comment by slink1811** [comment]
as in #6579 i use the pool name and it works

**Comment by adir1661** [comment]
@medikoo can you adress me more specificly i don't think i understand you, do you weant me to posy my whole serverless yml file?

**Comment by medikoo** [comment]
@adir1661 yes, please respect all issue template remarks. If something is not clear in it, please cite the confusing part with some explanation (we're open to improve the template if needed)

**Comment by adir1661** [comment]
@medikoo i dont understand what is missing in my yml file even after rereading the all issue template remarks.
and specificly also didn`t understand what is "• Has sensitive parts masked out" means.

**Comment by medikoo** [comment]
> @medikoo i dont understand what is missing in my yml file

You can easily find by e.g. running `serverless -v` against it.

We need a reproducible test case, this file doesn't resemble one.

> also didn`t understand what is "• Has sensitive parts masked out" means.

You shouldn't share any personal data or secrets openly, instead mask it with e.g. `xxx`

**Comment by adir1661** [comment]
thank you!
i will check it out in sunday!

**Comment by adir1661** [comment]
@medikoo 
i was checking and all what was missing is the service name to be bale to run serverless -v is that what u mean?

**Comment by adir1661** [comment]
I fixed it with a little workaround:
istead of : 
```
preSignUp:
     handler: confirm.preSignUp
     events:
     - cognitoUserPool:
        pool: CoverUserPool
        trigger: PreSignUp
        existing: true
```

i tried:
```
preSignUp:
    handler: confirm.preSignUp
    events:
    - cognitoUserPool:
        pool:  ${self:custom.userPoolName}
        trigger: PreSignUp
        existing: true
```

**Comment by medikoo** [comment]
@adir1661 so if I understand correctly, issue was incorrect nesting in a configuration (?)

Such issues will shortly be immediately exposed. See: https://github.com/serverless/serverless/issues/6562

**Comment by sweeetland** [comment]
same issue and I tried @adir1661 suggestion above but no luck.

Any ideas?

**Comment by medikoo** [comment]
Closing, as it was configuration formatting issue

**Comment by gruckion** [comment]
I don't feel this thread explains what the issue actually was..

**Comment by medikoo** [comment]
> I don't feel this thread explains what the issue actually was..

@gruckion There was incorrect properties nesting in service configuration.

In latest version such errors are well communicated with warnings, and that's scheduled to be error by default at some point.

**Comment by desoss** [comment]
@medikoo I got the same issue with the latest framework version _2.54.0_, using:

``` 
signup-trigger:
    handler: functions/cognito-to-dynamodb.handler
    events:
    - cognitoUserPool:
          pool: ${self:custom.GlobalTable.name}
          trigger: PostConfirmation
          existing: true
```

Without any better communicated warning.
`An error occurred: SignupDashtriggerCustomCognitoUserPool1 - Received response status [FAILED] from custom resource. Message returned: Cannot read property 'Id' of null See details in CloudWatch Log: 2021/08/16/[$LATEST]79066eb1e1e84571b30f2c8217de0e15 (RequestId: 3da801b4-8c35-49bd-9560-e0a34813a628).`

**Comment by medikoo** [comment]
> @medikoo I got the same issue with the latest framework version 2.54.0

@desoss please open a new bug report (with respect to all its remarks)

**Comment by farhah** [comment]
> @medikoo I got the same issue with the latest framework version _2.54.0_, using:
> 
> ```
> signup-trigger:
>     handler: functions/cognito-to-dynamodb.handler
>     events:
>     - cognitoUserPool:
>           pool: ${self:custom.GlobalTable.name}
>           trigger: PostConfirmation
>           existing: true
> ```
> 
> Without any better communicated warning. `An error occurred: SignupDashtriggerCustomCognitoUserPool1 - Received response status [FAILED] from custom resource. Message returned: Cannot read property 'Id' of null See details in CloudWatch Log: 2021/08/16/[$LATEST]79066eb1e1e84571b30f2c8217de0e15 (RequestId: 3da801b4-8c35-49bd-9560-e0a34813a628).`

Did you manage to get it working? I'm experiencing the same error too.

**Comment by iam-dev0** [comment]
Facing this issue today on both latest of v4 and v3.

![image](https://github.com/serverless/serverless/assets/24081860/4de29611-221c-43a9-8492-8006a72ac3d4)
