### ISSUE TITLE
  Error: ENOENT: no such file or directory, open 

### ISSUE THREAD

**Issue by shadhanu** [serverless/serverless#7716]
I am trying sls package. In some modules, this works but not in others. It seems like a sporadic issue.

Any clues ?

Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  Error: ENOENT: no such file or directory, open '/node_modules/.bin/components'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.4.0
     Framework Version:         1.70.0
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10

**Comment by medikoo** [comment]
@shadhanu please respect all issue template remarks and fill answers for all questions.

**Comment by medikoo** [comment]
Closing as we didn't receive enough details to process this further
