### ISSUE TITLE
Support the creation of API Gateway API keys with CustomerId

### ISSUE THREAD

**Issue by gcampionpae** [serverless/serverless#7749]
### Use case description

When creating an API key with serverless, I'd like to also be able to add a customerId to it so that I can associate the ID with specific customers. Here is the AWS reference for this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html

### Proposed solution

Add this as a field that can be filled out in the serverless template and will then be added to the cloudformation tempalte that's uploaded to AWS.  This seems like a fairly easy fix and I wouldn't mind giving it a crack but this would be my first time trying to contribute to Serverless so I may need some help :)

It seems like it would just be a matter of changing some things here:

https://github.com/serverless/serverless/blob/3fe2e98f15d3a78571b3aa0894be1632e2f5ab51/lib/plugins/aws/info/getApiKeyValues.js

and here:

https://github.com/serverless/serverless/blob/3fe2e98f15d3a78571b3aa0894be1632e2f5ab51/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js

and maybe here:

https://github.com/serverless/serverless/blob/6780415c08c52b10fdabb60e2ad71008e933e652/lib/plugins/aws/info/display.js

**Comment by medikoo** [comment]
@gcampionpae great thanks for proposal! It's indeed a worthwhile enhancement and we'll be happy to welcome a PR that adds it.

Concerning implementation, you're on a right track

Actually implementation should be done here: https://github.com/serverless/serverless/blob/3fe2e98f15d3a78571b3aa0894be1632e2f5ab51/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js

Updates in `info` command (so in `lib/plugins/aws/info` folder) are needed if we want to expose customer ID info by a key in a summary after deployment. I think it'll be helpful if they are provider there. What do you think?

We also need a documentation updates here:
- https://github.com/serverless/serverless/blob/69f368f7ddb48f4ab6d6fdba7e2a9d466e61a5dc/docs/providers/aws/events/apigateway.md
- https://github.com/serverless/serverless/blob/69f368f7ddb48f4ab6d6fdba7e2a9d466e61a5dc/docs/providers/aws/guide/serverless.yml.md

**Comment by gcampionpae** [comment]
@medikoo Ok, I think this is ready for review :)
