### ISSUE TITLE
Doesn't install on Ubuntu18, nvm with node12.16.1

### ISSUE THREAD

**Issue by tirthaguha** [serverless/serverless#7756]
Q1: What's wrong with it
Doesn't install on Ubuntu18, nvm with node12.16.1

Q2: System Description
Win10, WSL Ubuntu18.x
nvm
node v12.16.1

<details>
<summary><code></code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>npm install -g serverless</code> output</b></summary>

```bash
username@username:/mnt/f/JS_WORKSPACE/lambda-express$ npm install -g serverless
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /home/username/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/rxjs
npm ERR! dest /home/username/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/.rxjs.DELETE
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/home/username/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/rxjs' -> '/home/username/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/.rxjs.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-05-20T19_21_08_093Z-debug.log
```

</details>

<b>Installed version</b>

```
Serverless Not installed
```

**Comment by medikoo** [comment]
@tirthaguha great thanks for report. Still it looks as either problem with your setup, or a bug in npm. Note that no `serverless` logic was invoked. It's purely `npm install -g serverless` that crashed in a middle when trying to setup dependencies for the project

**Comment by chrisVillanueva** [comment]
@tirthaguha 
Can you confirm the node version?  I ran `nvm ls -remote` and don't see v12.6.1.  It could be a mistake on my side--not sure.  Here's the output:

![Screenshot from 2020-05-19 00-52-34](https://user-images.githubusercontent.com/1554280/82567615-99002f00-9b4b-11ea-90ef-232a28c4ec28.png)

**Comment by tirthaguha** [comment]
Typo, it is v12.16.1.

**Comment by chrisVillanueva** [comment]
I was able to install as a global npm package.

![serverlessInstall1](https://user-images.githubusercontent.com/1554280/82576628-e4203f00-9b57-11ea-9fde-24ae75b37dbc.png)

**Comment by tirthaguha** [comment]
Here's what I did
I went to the following directory 
`/home/username/.nvm/versions/node/v12.16.1/lib/node_modules/`
then I ran 
`rm -rf serverless`

then I ran 
`npm install -g serverless` again

This time it worked.

**Comment by chrisVillanueva** [comment]
Glad it worked.  I noticed issues with my nvm install--not related to this project.  I had issues with nvm and `emcc` on Ubuntu.
