### ISSUE TITLE
0.5 - Endpoint.getName inconsistency

### ISSUE THREAD

**Issue by dherault** [serverless/serverless#776]
Hi, in v0.5

Those commands: `sls dash deploy` (when choosing an endpoint) and `sls endpoint deploy` are called with this arg as the endpoint's name: `function_name#HTTP_method`. But Endpoint.getName returns `function_name~HTTP_Method` (notice `~` instead of `#`). 

This creates errors like `ServerlessError: Endpoint "lambda_graphql#GET" doesn't exist in your project` (only `lambda_graphql~GET` can be found).

Thanks for fixing it (I didn't PR because I do not know whether to go with ~ or #).

**Comment by ac360** [comment]
Thanks for this @dherault
