### ISSUE TITLE
API Gateway response template mapping issue - Is there any limitation?

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [serverless/serverless#7776]
Hi, 

I'm using the latest version of the serverless framework. When I used an API gateway response mapping template for more than 12 endpoints it's started breaking. I've tried with an older version also it wasn't working. There is no error message in the log also. It's not mapping to the API gateway failing silently. 
But after manual deployment from API gateway it starts working. It's completely strange.

**Comment by medikoo** [comment]
@BhuvaneshwaranR please respect all template remarks and answer all template questions.

**Comment by BhuvaneshwaranR** [comment]
@medikoo my bad
