### ISSUE TITLE
I want to contribute, but I don't understand how the software works under the hood well enough

### ISSUE THREAD

**Issue by skyzyx** [serverless/serverless#7781]
### Use case description

I am interested in doing some contributions, fixing bugs, etc. But I'm finding it difficult to get started because it isn't clear how the software works.

* [ ] I know how to write JavaScript, but I'm not a "JavaScript Developer". Not everyone is familiar with Node-centric things, and providing a little more context can be useful.

* [ ] If I fork/clone the repo, what's next? Is there a build step? How do I run my local version of `serverless` that's not pulled from npm? I see that there is a [userguide for AWS](https://www.serverless.com/framework/docs/providers/aws/guide/), but it doesn't _appear_ to answer most of my questions below about developing the software itself and things to pay attention to.

* [ ] What is the _flow_ of the internals of the software? Are there layers (software layers, not Lambda layers) I should be aware of? I know that in a `serverless.yml` file there is a resources section which supports CloudFormation-as-YAML. But what about the other parts of the config? How is the config file parsed and what do you do with the data you find?

* [ ] `CONTRIBUTING.md` talks about the process of determining what to work on, generally, but not _how_ to work on the project. `README.md` appears to be focused on the end-user, not a potential developer/contributor. `tests/README.md` appears to assume that everyone has the same context as the author. I've written a TON of unit tests over the years, but what test framework(s) are you using (the docs don't say), and where can I go to read more about how those frameworks work?

* [ ] [tests/README.md#testing-templates](https://github.com/serverless/serverless/blob/master/tests/README.md#testing-templates) appears to assume that I have an `~/.aws/credentials` file on my system, which I don't because I use [aws-vault](https://github.com/99designs/aws-vault) to encrypt my credentials and there are [better ways to pass credentials into Docker containers](https://ryanparman.com/posts/2019/running-aws-vault-with-local-docker-containers/). Without going in and reverse-engineering the code, will the tests work with my setup? Or do they make assumptions that may or may not be true?

* [ ] I've spent a little time looking at the source code, and now it seems even more opaque how to get started. What's the difference between `classes`, `plugins`, and `utils`? There's an awful lot of code in `utils`. Comments like [this](https://github.com/serverless/serverless/blob/85e9cd4455bb631be921a12a37f2174fd50ecec6/lib/classes/Variables.js#L18-L44) are (I assume) helpful. I don't expect that level of detail throughout the codebase, but if we could at least get some signposts so that we can get a sense of how the pieces fit together, that would be helpful.

To be clear, I don't blame you. Most onboarding documentation in OSS is lacking. My suggestion is to think about this like a job, and you've just hired a new person who's a smart engineer, but doesn't know anything about your application. Their previous projects had their own idiosyncrasies. You want them to have a good onboarding experience and to get up and running quickly. Write documentation as through you are explaining the system to a developer on their first day, and you can have some really good results.

Thank you.

**Comment by medikoo** [comment]
@skyzyx thanks for those questions

>  If I fork/clone the repo, what's next? Is there a build step? 

Setup is as regular as you can imagine. After cloning you just need to ensure that all dependencies are installed via `npm install` and you're ready to go.

I think we can add note about that to https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md

> What is the flow of the internals of the software?

I'll add some explanations about that into https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md (if not this wekk, then hopefully next one)

> but what test framework(s) are you using (the docs don't say),

Indeed docs do not list that, but I think it's pretty straightforward to obtain an answer to that.
Just follow configuration of `test` npm script:

https://github.com/serverless/serverless/blob/af3fbf0402054d39be2b758568553381ff0246d2/package.json#L73

And rest can also be read from tests directly by seeing what dependency it relies on.

Nonetheless it won't harm to add one sentence about that to the doc.

> I've spent a little time looking at the source code, and now it seems even more opaque how to get started. 

We deal with significant technical debt (Note the some code has 3+ years) and we plan to gradually revert from some decisions (made by different people in different moments of time).

So unfortunately it is as it is, but I'll try to add general description of a flow that puts more light on how things work internally. 

Otherwise you need to acknowledge that this project was coming through different hands and there's a history factor (like in a city you may wonder what this old building is doing aside a modern one - it wasn't built in a day).

I'll keep this issue open, until I feel that all that can be sensibly addressed was addressed.

Thanks for sharing that!

**Comment by skyzyx** [comment]
@medikoo: Thank you for the explanation.

> We deal with significant technical debt (Note the some code has 3+ years) and we plan to gradually revert from some decisions (made by different people in different moments of time).
> 
> So unfortunately it is as it is, but I'll try to add general description of a flow that puts more light on how things work internally.

I get it. I've worked on those kinds of projects myself. That said, gaining a better understanding of how the internals work (e.g., the internal flow of the software) would help tremendously in getting people (like me, anyway) to _be able_ to reasonably get started in contributing.

> Otherwise you need to acknowledge that this project was coming through different hands and there's a history factor (like in a city you may wonder what this old building is doing aside a modern one - it wasn't built in a day).

Certainly. Acknowledged. While I don't know the history of ownership (many projects are managed by the same small team for many years, for example), I can understand situations like this.

Thanks!

**Comment by preshetin** [comment]
@skyzyx let me share my experience in contributing to this repo. I've done a few contributions in the past several months.

### How to run a local version of Serverless CLI
1. Fork or clone this repo. Then `cd` into it.
2. Install dependencies by running `npm install`
3. Then inside your _project_ directory (it's where your `serverless.yaml` file lives) run `node /path-to-cloned-serverless-repo/bin/serverless.js  deploy` 
4. Congrats! You've just run a local copy of Serverless framework!


### What

**Comment by medikoo** [comment]
@skyzyx I've added more documentation with this PR: https://github.com/serverless/serverless/pull/7902

Answering point by point

> I know how to write JavaScript, but I'm not a "JavaScript Developer"

I don't think this repository should contain any information on how to work with JavaScript ecosystem in general, also we do not have resources to host and maintain here any general documentation like that.

Nonetheless if you have some more specific concerns, doubts, please elaborate. That'll help us understand what exactly you're missing.

>  If I fork/clone the repo, what's next? Is there a build step

I've added a clarification note on that here: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#setup

> What is the flow of the internals of the software?

I've introduced a document that describes [anatomy of the Framework](https://github.com/serverless/serverless/blob/master/docs/anatomy.md). That should give you a good idea how internals are organized.

We're also definitely open for improvements in that area

> CONTRIBUTING.md talks about the process of determining what to work on, generally, but not how to work on the project. 

To be honest I believe CONTRIBUTING.md shares a lot of information on how to work with the project. What exactly are you missing there?

> tests/README.md#testing-templates appears to assume that I have an ~/.aws/credentials

This is part, with which I'm also not perfectly familiar at this point, and at this point I do not have resources to invest my time into that, but any help on that is welcome!

> What's the difference between classes, plugins, and utils? 

This should be well covered now in [anatomy of the Framework](https://github.com/serverless/serverless/blob/master/docs/anatomy.md).

**Comment by medikoo** [comment]
> tests/README.md#testing-templates appears to assume that I have an ~/.aws/credentials file on my system, which I don't because I use aws-vault to encrypt my credentials and there are better ways to pass credentials into Docker containers. Without going in and reverse-engineering the code, will the tests work with my setup? Or do they make assumptions that may or may not be true?

This part I think is well documented. Also [docker-compose.yml](https://github.com/serverless/serverless/blob/master/docker-compose.yml) is pretty self explanatory.

if you feel there's a room for improvement PR is definitely welcome.

I'm going to close this, as I believe most concerns were addressed. Anyway I remain open for further suggestions.
