### ISSUE TITLE
aws-sdk cannot find module 'dynamodb/handler'

### ISSUE THREAD

**Issue by camhart** [serverless/serverless#779]
I'm currently having issues calling any AWS SDK commands.  Here's the exact error:

```
{"errorMessage":"Cannot find module 'dynamodb/handler'","errorType":"Error","stackTrace":["Function.Module._resolveFilename (module.js:338:15)","Function.Module._load (module.js:280:25)","Module.require (module.js:364:17)","require (module.js:380:17)"]}
```

I've tried the setting s-component.json custom as follows:
```
  "custom": {
  	"optimize" : {
  		"exclude" : [
  			"aws-sdk"
  		]
  	}
  },
```

I've viewed in _meta/_tmp and the function package has aws-sdk in the node_modules directory.
I've read through the following issues, and can't seem to find any solution to this.

- http://stackoverflow.com/questions/32707970/how-do-you-bundle-aws-sdk-js-into-a-serverless-framework-optimized-package
- https://github.com/serverless/serverless-optimizer-plugin/issues/2
- https://github.com/serverless/serverless/issues/156

**Comment by jordanmack** [comment]
@camhart Do you have a folder or function called "dynamodb" somewhere?

**Comment by varunvairavan** [comment]
I think your parameter name or the file is wrong. JAWS/Serverless/Optimizer have changed rapidly. So maybe you ran into issues with older documents. I just had the same issue. You should follow,

https://github.com/serverless/serverless-optimizer-plugin#common-pitfalls

Your `s-component.json` file inside the node-js folder should look like,

```
{
  "name": "nodejs",
  "runtime": "nodejs",
  "custom": {
    "optimize": {
    	"exclude": ["aws-sdk"]
    }
  }
}

```
It's fine if the aws-sdk is in the node_modules directory. There will be a file called bundled.js inside the _meta/_tmp/{function_name} directory. Open the file and search for `node_modules`. If you find the file path of the aws-sdk then you have the same issue as the questions you have posted.

**Comment by camhart** [comment]
This was a user error.  I had attempted to rename the function, and even though I changed the name in the json file I must have missed somewhere else that needed changed.  I now have it working, thanks to @jordanmack's comment.
