### ISSUE TITLE
Add checks for API Gateway resource policy structure

### ISSUE THREAD

**Issue by glb** [serverless/serverless#7795]
### Use case description

I spent 2 days trying to figure out why API Gateway was rejecting my resource policy because I had simply pasted it into the `provider.resourcePolicy` section of my `serverless.yml` file without thinking.

<details>
<summary>Example "incorrect" resource policy</summary>

```yaml
provider:
  name: aws
  resourcePolicy:
    {
      "Version": "2012-10-17",
      "Statement":
        [
          {
            "Effect": "Allow",
            "Principal":
              {
                "AWS":
                  [
                    "arn:aws:iam::123456789012:root",
                  ],
              },
            "Action": "execute-api:Invoke",
            "Resource": "execute-api:/*/POST/api/sample",
          },
        ],
    }
```

</details>

It turns out that the Serverless Framework helpfully wraps the provided resource policy in the necessary `{ "Version": "2012-10-17", "Statement": [ ... ] }` bits, so API Gateway didn't like the result.

I thought that my policy document was just fine, and in fact it was copied directly from a working one in the console, so it was very difficult to understand until I looked at the generated CloudFormation. Twice, really, because the first time everything looked OK, and it took a re-read to notice the wrapping around my policy.

<details>
<summary>Generated CloudFormation excerpt</summary>

```json
    "ApiGatewayRestApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "sample",
        "Policy": {
          "Version": "2012-10-17",
          "Statement": {
            "Version": "2012-10-17",    <-- THIS IS WHERE THINGS GO BAD
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": [
                    "arn:aws:iam::123456789012:root"
                  ]
                },
                "Action": "execute-api:Invoke",
                "Resource": "execute-api:/*/POST/api/sample"
              }
            ]
          }
        }
      }
    },
```

</details>

Each attempted deploy took 20 minutes and failed with the message `Invalid policy document. Please check the policy syntax and ensure that Principals are valid.`. Because I'd taken the policy document from a working version in the console, I was stumped for quite a long time.

### Proposed solution

It would be super-helpful if the Serverless Framework checked that the provided `resourcePolicy` value was the right shape (even just checking for `Version` and `Statement` attributes or simply checking if the value is an object instead of an array) and failed quickly, or if it didn't add the wrapper if there were already `Version` and `Statement` attributes or if the value was an object.

Thoughts? If folks agree with this idea, I'm happy to try implementing a solution.

**Comment by nirwandogra** [comment]
Hi, 
I tried to deploy the below basic stack (in BOLD) with the policy you mentioned, and instantly got "Invalid policy document" while deploying. I tried it 3 times and the error was instantaneous.  Maybe there are some other non-apigw resources in your stack which are taking more than 20 minutes before failures ?

**AWSTemplateFormatVersion: 2010-09-09
Description: 'Basic rest api'
Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: sample
      Policy:
        Version: '2012-10-17'
        Statement:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              AWS:
              - arn:aws:iam::123456789012:root
            Action: execute-api:Invoke
            Resource: execute-api:/*/POST/api/sample**

**Comment by glb** [comment]
Thanks @nirwandogra ... I can't explain why CloudFormation / API Gateway are behaving the way they are and have an open support ticket with AWS trying to find that out. I do know that the only difference in my environment between a stack that updates almost instantaneously and one that takes >20min to fail is the resource policy. 

The behaviour of CloudFormation and API Gateway is not the real issue here.

I'd like to understand if this project is open to making a change to the way that it handles the `provider.resourcePolicy` attribute, so that if the value is an object then that object is used as the resource policy document (proposed new behaviour) and if the value is an array then that array is used as the array of statements in the resource policy document (current behaviour).

This proposed change will make it possible for folks to take a working resource policy from the console, paste it into `serverless.yml`, and have it work. Currently you can't do that; you end up with a malformed policy, an error and a lack of clarity as to what your error was. At least, that's what happened to me.

I have a [branch with changes to implement, test, and document this proposal](https://github.com/glb/serverless/commit/cfc3b97f92dfe36aecc963a6f0aa8af9d1c6348d) but have not opened a PR out of respect for the project's request not to open PRs until there is agreement on a path forward.

Comments, suggestions, and questions are welcome.

**Comment by medikoo** [comment]
@glb such errors should be well handled with https://github.com/serverless/serverless/issues/6562 which already has nearly finalized PR and should land soon (altough validation for this specific case will also need to be configured in)

**Comment by glb** [comment]
@medikoo thanks! Having a schema check would be great. I've subscribed to that issue and would be happy to try adding basic validation for `resourcePolicy` when the capability is available.
