### ISSUE TITLE
Unable to load dash deploy tool when s-template exclusively locked

### ISSUE THREAD

**Issue by keithmgould** [serverless/serverless#780]
I use [mac Vim](https://github.com/macvim-dev), and I believe that mVim places a lock on files while it has a buffer open. This yields tmp files like so:

```
.s-templates.json.swp
```

During this time, when I tried to deploy, the tool would not even load ( as in show me the menu), yielding:

```
$ sls dash deploy
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

SyntaxError: Unexpected token b
```

As soon as I closed the buffer, the tool worked as expected. This is reproducible.

Note also that if I just create the dot file `touch .s-templates.json.swp` the same problem happens, so this has more to do with the existence of this file than with mac vim.

**Comment by jordanmack** [comment]
I did a `touch .s-templates.json.swp` in my project root and `sls` would still run fine. I'm on Linux and I don't use vim. I suspect it might be related to a locked file. Could you check if there is a file lock on `s-templates.json` when you reproduce this error? Here is a page on [checking locked files on osx](http://apple.stackexchange.com/questions/22259/how-to-check-whats-locking-a-file).

**Comment by keithmgould** [comment]
Thx @jordanmack. I took a look and did not find the files locked (or I possibly made a mistake when looking). To clarify, Vim was not running during my test. I just touched/created the dot file. Here are details for me to reproduce:

```
$ sls dash deploy // works
$ $ ps aux | grep Vim // nothing running
$ touch .s-templates.json.swf
$ lsof | grep s-templates.json // no results
$ lsof | grep .s-templates.json.swf // no results
$ sls dash deploy
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
$ rm ./.s-templates.json.swp
$ sls dash deploy // works
                           ^

SyntaxError: Unexpected end of input
```

**Comment by jordanmack** [comment]
This could be related to #692.

**Comment by flomotlik** [comment]
This should already be resolved and will be definitely resolved in an upcoming version as we're changing the config file syntax and handling. I will close this issue for now
