### ISSUE TITLE
serverless has a number of potential security flaws as identified by a VeraCode static scan

### ISSUE THREAD

**Issue by iamle0pard** [serverless/serverless#7850]
If you run a VeraCode static security scan against the serverless folder and files within 'node_modules' you will see that there are a number of flaws identified.

The following flaws have been identified:

http://cwe.mitre.org/data/definitions/259.html
CWE-259: Use of Hard-coded Password

utils.js: 140
Context.js: 124
Context.js: 123
utils.js: 119
Context.js: 110
utils.js: 141
Context.js: 129

http://cwe.mitre.org/data/definitions/321.html
CWE-321: Use of Hard-coded Cryptographic Key

sign.js: 23
client.js: 65

http://cwe.mitre.org/data/definitions/798.html
CWE-798: Use of Hard-coded Credentials

index.spec.js: 212

http://cwe.mitre.org/data/definitions/201.html
CWE-201: Exposure of Sensitive Information Through Sent Data

CLI.js: 130
utils.js: 99
index.js: 493
index.js: 578
CLI.js: 189
getUserAuthInfo.js: 43
index.js: 495
index.js: 580

Currently using serverless version: 1.72.0

Please note that VeraCode often finds the word "pass" or "secret" and assumes those are hard coded values of real passwords.  I am filing this so you are aware of the issue(s) and can fix them, if needed.  If they are false positives, please let me know so I can triage any issues in our scan results identified as such.

**Comment by medikoo** [comment]
@iamle0pard thanks for report, still I have problems coining real issues.

Firstly this information is not specific enough, e.g. we have numerous `utils.js` files in various folders. It's not clear to which ones exactly report applies (full file paths, ideally links to specific lines will definitely help)

Secondly, I've checked some of those that can be coined, and e.g. in  `CLI.js` at line 130 there's totally safe code: https://github.com/serverless/serverless/blob/v1.72.0/lib/classes/CLI.js#L130

So I have problems in understanding what's the point of those warnings, they do not look valid.

**Comment by iamle0pard** [comment]
I'm not saying all of these issues are 100% true security issues.  I am simply reporting what VeraCode has indicated.  What you will find is that many times their algorithm only looks for keywords and then flags it.  For instance anywhere the word '**Secret**', '**Pass**', or '**Password**' are in the code it will flags as '**Use of Hard-coded Password**'.  In 99% of the cases this is a false positive.  There may be many more like this.

Since it is a static code analysis done by their internal AI/algorithms it doesn't have the ability to process the preceding lines to see if the flagged line number is actually being protected by code that precedes it.  I believe they error on the side of "flag it and then let the end user determine if it is a true issue or a false positive".

I'm just reporting these items as a notification to everyone on the project.  If it is determined that there are no real security issues, then that is great!  Internally I can flag them in our own VeraCode scan report as such to remove them from the results.  We do this to ensure we don't ship code that has vulnerabilities in it, so that is also why I'm reporting it; if one of these was an actual security issue, it would be good to get it fixed.

Here are the specific files (with paths and code at that line number) for each item they reported:

**Use of Hard-coded Password**
/components/src/cli/commands-cn/utils.js: 140
providers.tencent.TENCENT_SECRET_ID = 'SecretId';

/cli/src/Context.js: 124
providers.tencent.TENCENT_SECRET_KEY = 'SecretKey'

/cli/src/Context.js: 123
providers.tencent.TENCENT_SECRET_ID = 'SecretId'

/components/src/cli/commands/utils.js: 119
providers.aws.AWS_SECRET_ACCESS_KEY = 'secretAccessKey';

/cli/src/Context.js: 110
providers.aws.AWS_SECRET_ACCESS_KEY = 'secretAccessKey'

/components/src/cli/commands-cn/utils.js: 141
providers.tencent.TENCENT_SECRET_KEY = 'SecretKey';

/cli/src/Context.js: 129
providers.docker.DOCKER_PASSWORD = 'password'

**Use of Hard-coded cryptographic key**
 /utils-china/library/common/sign.js: 23
const hmac = crypto.createHmac(signMethodMap[signMethod], secretKey || '');

/utils-china/library/tencent-cloud/client.js: 65
const hmac = crypto.createHmac('sha1', this.credentials.SecretKey || '');

**Use of Hard-coded Credentials**
/event-mocks/dist/index.spec.js: 212
userName: "notAJ",

**Exposure of Sensitive Information Through Sent Data**
/components/src/cli/CLI.js: 130
process.stdout.write(color(content));

 /platform-client-china/src/utils.js: 99
req.write(options.data);

/platform-client-china/src/index.js: 493
self.intercepts.stdout.write(...logs);

/platform-client/src/index.js: 578
self.intercepts.stdout.write(...logs)

/components/src/cli/CLI.js: 189
process.stdout.write(white(msg));

/utils-china/sdk/account/getUserAuthInfo.js: 43
req.write(requestData);

/platform-client-china/src/index.js: 495
self.intercepts.stderr.write(...logs);

/platform-client/src/index.js
self.intercepts.stderr.write(...logs)

**Comment by medikoo** [comment]
@iamle0pard this belongs to other repositories

`components` is https://github.com/serverless/components
`cli` is https://github.com/serverless/cli
`utils-china` is https://github.com/serverlessinc/utils-china/
`eent-mocks` is https://github.com/serverless/event-mocks

`platform-client-china` and `platform-client` are actually hidden behind private repos, but you can report about that at https://github.com/serverless/components (it's their dependencies).

Can you open issues over there?

**Comment by iamle0pard** [comment]
Thanks for directing me in the right locations.  I've opened up a new issue in each of the respective repos:

https://github.com/serverless/components/issues/674
https://github.com/serverless/cli/issues/15
https://github.com/serverlessinc/utils-china/issues/36
https://github.com/serverless/event-mocks/issues/19

Closing this issue as new issues have been raised in the correct repos.
