### ISSUE TITLE
Feature request: create separate env files for different components

### ISSUE THREAD

**Issue by hauboldj** [serverless/serverless#787]
An alternative could be to only include environment variables specified in the s-function.custom.envVars list in the deploy for each function.

**Comment by ac360** [comment]
@hauboldj Thanks.  ENV handling was totally overhauled today in V0.5.  You now include ENV vars in `s-function.json` in an `environment` property.  You can use Project Variables as the values too.  We're going to merge this in to the `v0.5` branch tomorrow.  Please let me know what you think :)

**Comment by hauboldj** [comment]
Will this still support separate values for different stages?
