### ISSUE TITLE
v0.5 - python2.7 Deployment with Shared Dependencies

### ISSUE THREAD

**Issue by michaelorionmcmanus** [serverless/serverless#789]
Hi All,

After spending a week hacking together my own solution for managing a lambda/apig service, I've seen the light and an very excited about serverless! I'm currently in the process of serverless-ifying my app and I'm running into a few hiccups with managing and deploying shared dependencies for `python2.7` runtime functions. After a decent amount of digging and trial and error I've come up with two possible approaches. Both seem to have issues, though, and I think that there is room for improvement. I'd love to see if there is any consensus on a best practice here and also hear what others think. 

## Background

I started porting my project with v0.4 and followed along with this write-up in order get my function's `pip` dependencies packaged and correctly pathed: https://serverlesscode.com/post/python-on-serverless-intro/. The approach described in this post can be reliably reproduced in v0.4. However, I quickly realized that v0.5 was just around the corner. With the eminent removal of components, I decided to start building on v0.5 rather than have to migrate from v0.4. I discovered two possible approaches that work with v0.5, which I will outline.

### Include all the things

As you might guess, the approach outlined in the blog post does not work with v0.5. I took a look at the v0.5 docs and found the callout "The Handler Property Is Very Flexible" under "[Function Configuration](http://docs.serverless.com/v0.5.0/docs/function-configuration)." Taking this information as a starting point I created a new function in the following location:
```
project /
  - app /
    - functions /   
      - collection /
        - function1 /
          - event.json
          - handler.py
          - s-functions.json
    - vendored /  <- pip dependencies
    - shared /    <- non 3rd party shared utilities used by modules in functions
```

In order to package and deploy `function1` the `handler` parameter in `s-function.json` must specify `functions/collection/function1/handler.handler`. The resulting package will look like:

```
    - functions /   
      - collection /
        - function1 /
          - event.json
          - _serverless_handler.py
          - handler.py
          - s-functions.json
    - vendored /  <- pip dependencies
    - shared /    <- non 3rd party shared utilities used by modules in functions
```

And, `_serverless_handler.py` will look something like:

```python
import os, sys
os.environ['SERVERLESS_STAGE'] = str('dev')
os.environ['SERVERLESS_DATA_MODEL_STAGE'] = str('dev')
os.environ['SERVERLESS_PROJECT_NAME'] = str('sls-v05')
from handler import handler
```

Execution of this package in Lambda will fail and you'll get an error stating that the `functions/collection/function1/_serverless_handler` module can't be imported because the module `handler` isn't found. 

Huh?

If I understood python's import scheme a little better, perhaps this would be obvious, but as best as I can tell, in the Lambda environment python is looking for the `handler` module in the root of the package. As such, it is not found. 

In order to add the function directory to the environment's import path, I altered `_afterCopyDir` in `serverless/lib/RuntimePython2.7` to add the correct path before attempting to import `handler`. I altered the method by altering the following after ~ line 111:

```js
  _afterCopyDir(func, pathDist, stage, region) {        
        // code above
        let loader = ['import os, sys'];
        loader = loader.concat(_.map(envVars, (value, key) => `os.environ['${key}'] = str('${value}')`));
        loader.push('here = os.path.dirname(os.path.realpath(__file__))');
        loader.push('sys.path.append(here)');
       // code below
}
```
For an accurate and complete diff, see the following: https://github.com/michaelorionmcmanus/serverless/commit/985c4b4f6adeb1fc66ec49bb0b320c95370389c5

This causes the packaged `_serverless_handler` module to look like:

```python
import os, sys
os.environ['SERVERLESS_STAGE'] = str('dev')
os.environ['SERVERLESS_DATA_MODEL_STAGE'] = str('dev')
os.environ['SERVERLESS_PROJECT_NAME'] = str('sls-v05')
here = os.path.dirname(os.path.realpath(__file__))
sys.path.append(here)
from handler import handler
```
Huzzah! This will execute properly in Lambda.

But note: In order to use modules in the shared directories when running the function locally, you'll have to add something along the lines of the following to your handler module:

``` python
import sys, os
here = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(here, "../../../vendored"))
sys.path.append(os.path.join(here, "../../../shared"))
```

### The Alternative

This is actually what I got working initially, because it took me a while to understand why `handler` failed to load in `_serverless_handler` in the Lambda environment. Also, I was convinced that I should be able to get this work without modifying the serverless source :smile:.

Assume the same project structure outlined above. 

For the function at `functions/collection/function1`, user the default value for the `handler` parameter in `s-function.json`: `handler.handler`. In addition, explicitly specify `includePaths` so that the packager is directed to include just the local function directory and any other directories.

```json
  "custom": {
    "includePaths": [
      ".",
      "../../../app/vendored",
      "../../../app/shared"
    ],
    "excludePatterns": [],
    "envVars": []
  },
```

In `handler.py` alter the system path so that shared dependencies can be loaded locally and in Lambda:

```python
here = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./shared"))
sys.path.append(os.path.join(here, "../../../vendored"))
sys.path.append(os.path.join(here, "../../../shared"))
# Now safe to import shared libraries.
```

This function can now be deployed and executed on Lambda.

### Discussion

The former approach seems to hew closer to the practice outlined in the documentation, which is why I felt that it was important to understand how to get it to work. The downside is that, as your project grows you'll end up packaging and shipping all your functions in each deployment. This isn't the end of the world but it seems like an easy optimization to make so, why not?

In the later approach, the big win is that the deployment package includes only what is necessary. The downside is that there is much more configuration that needs to be maintained for each function because you have to:

1. Keep track of `custom.includePaths`
1. Maintain the system path in each function handler
1. Be aware that this packaging strategy differs from the "standard" used for nodejs runtime functions. In other words, might a future change totally bork this? That could cause the need for a pretty unpleasant refactor. 

In either case, I hope that others have thoughts and feedback to share. It'd be great for serverless newcomers to know where to start when they build `python2.7` runtime functions with shared dependencies. 

More than happy to followup with a PR if it seems appropriate.

Thank you!

**Comment by michaelorionmcmanus** [comment]
A few trailing thoughts:

In general, the official documentation is heavily geared toward `nodejs` runtime functions. This makes a lot of sense, since serverless initially only supported node. Confession: I didn't even realize that serverless supported python after my first glance at the project. 

My quick take is that either there should be explicit discussion of differences between `nodejs` and `python2.7` functions or the "defaults" should be agnostic and support both runtimes equally as well. I mean this is in the most sincere way and with a desire to help: from an on-boarding and marketing perspective, the `python2.7` runtime support feels a little second-class. 

I totally recognize that this probably comes down to decisions about roadmap focus and the reality that time and money are limited. Nonetheless, I think that this might be important feedback to hear. 

Now that I've dug around in the serverless source, it's clear that some significant foundation work has been laid and that's very promising. 

Again, looking forward to contributing in whatever way I can!

**Comment by michaelorionmcmanus** [comment]
Updated original comment with ref to forked repo with code change that modifies `_serverless_hander.py` to include the local directory in the import path: https://github.com/michaelorionmcmanus/serverless/commit/985c4b4f6adeb1fc66ec49bb0b320c95370389c5

**Comment by ac360** [comment]
@michaelorionmcmanus Great write-up.  We will look into this tomorrow.  Thank you!

**Comment by godd9170** [comment]
I'm currently struggling with this issue, I'm running Serverless v 0.5.6. Have subsequent updates to sls rendered @michaelorionmcmanus' solution pointless?

My dir:

```
├── api
│   ├── account
│   │   ├── event.json
│   │   ├── handler.py
│   │   └── s-function.json
│   ├── lib
│   │   ├── Salesforce.py
│   │   └── account.py
│   └── vendored
```

relevant part of `s-function.json`

```
"handler": "handler.handler",
  "timeout": 6,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "includePaths": [
      ".",
      "../../api/vendored",
      "../../api/lib"
    ],
    "excludePatterns": []
  },
```

and my `account/handler.py`

```
from __future__ import print_function

import json
import logging
import sys, os

here = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(here, "./vendored"))
sys.path.append(os.path.join(here, "./lib"))
sys.path.append(os.path.join(here, "../../vendored"))
sys.path.append(os.path.join(here, "../../lib"))

log = logging.getLogger()
log.setLevel(logging.DEBUG)

from account import get_contacts

log.debug("After import")
```

and I get the following error:

`Unable to import module '_serverless_handler': No module named account`

I've tried changing the handler in the `s-function.json` to `account/handler.handler` with no luck. Am I importing the 'account' module wrong?

**Comment by flomotlik** [comment]
@godd9170 we're currently working on the next iterations of Serverless V1.0 that will have far better support for Node, python, Java, ...

We plan to release a new alpha with good support by the end of the month.

At this point we're not planning to do any updates to 0.5.x so it would probably be a better approach to update to the V1 alphas as soon as we release something new at the end of the month and support python fully.

**Comment by godd9170** [comment]
@flomotlik ah ok awesome. I'm looking forward to that. Appreciate the quick response.

**Comment by frangeris** [comment]
@godd9170 Did u get this working using `0.5.6`?
