### ISSUE TITLE
Upgrading XML Parser

### ISSUE THREAD

**Issue by amitguptagwl** [serverless/serverless#7906]
### Use case description

Upgrading XML parser to achieve higher performance.

### Proposed solution

As we're currently using xml2js, I wanted to request upgrading to [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) due to performance;

file size | fxp 3.0 validator (rps) | fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- | -- | -- | --
1.5k | 16581.06758 | 14032.09323 | 4615.930805
1.5m | 14918.47793 | 13.23366098 | 5.90682005
13m | 1.834479235 | 1.135582008 | -1
1.3k with CDATA | 30583.35319 | 43160.52342 | 8398.556349
1.3m with CDATA | 27.29266471 | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype | 27690.26082 | 41433.98547 | 7872.399268
98m | 0.08473858148 | 0.2600104004 | -1

-1 indicates the error.

**Comment by medikoo** [comment]
@amitguptagwl Thanks for proposal, we definitely welcome a PR that upgrades it.

Still note, we use XML parser only to create Chocolatey package meta file, it's not a part of Serverless Framework logic

**Comment by amitguptagwl** [comment]
Thanks @medikoo for your response. Do we have the tests to verify the logic of creating Chocolatey package meta file? So that I can confirm if nothing is breaking.

**Comment by medikoo** [comment]
@amitguptagwl we don't have tests for that, but you can easily confirm by running script manually (it just creates the package, doesn't attempt to publish it), and confirm that outcome from both versions matches

**Comment by medikoo** [comment]
Closing, as XML parser is used only for standalone generation, and it's not used in the core. Therefore upgrading it won't bring any real improvement
