### ISSUE TITLE
AWS HTTP API: Switch default payload mode to 2.0

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7917]
### Use case description

Version 2.0 is more powerful and should be set as default

#### Phase 1

<details>
Configure a deprecation warning for all HTTP API event deployments with no explicitly configured `payload` property. Message should be as: _Default HTTP API Payload version will be switched to 2.0 with next major release. Configure "payload" explicitly to hide this message_, See https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations
</details>

_Done with #7919_

#### Phase 2

Remove deprecation warning, and change default of `payload` to `2.0`

PR should be based against [`v2`](https://github.com/serverless/serverless/tree/v2) branch

**Comment by andreizet** [comment]
I can grab it.

**Comment by medikoo** [comment]
@andreizet thank you, it's yours!

**Comment by medikoo** [comment]
@andreizet Thanks for asking, I'd hold off for now. It's easy to add, while currently it's not clear when we'll be ready to release v2.

**Comment by medikoo** [comment]
We plan to release v2 next week, Therefore we're open to take PR that implements _second phase_! I've updated description with details on that
