### ISSUE TITLE
listen EACCESS: permission denied:5000

### ISSUE THREAD

**Issue by achuthabs** [serverless/serverless#7926]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 5000;
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1425:5)

no matter which port number i choose i am still getting this node error. need Help!!

**Comment by medikoo** [comment]
@achuthabs please use bug report template, respect all its remarks and answer all questions

**Comment by medikoo** [comment]
Not enough details were provided to let us process the issue. Therefore I'm closing this
