### ISSUE TITLE
Conditionally create deployment bucket

### ISSUE THREAD

**Issue by thetumper** [serverless/serverless#7943]
Problem:  we had a deploy fail due to reaching the account limit on number of S3 buckets.  For serverless, we are using an already-existing shared bucket, not creating a new one.  But it seems that serverless is trying a create-bucket and failed with "TooManyBuckets" in this scenario.

Proposal:  do a list-buckets first, before attempting create-bucket; presumably when the bucket is already existing, this failure could be avoided, and proceed with puts to the existing bucket, as needed during the deploy process.

**Comment by medikoo** [comment]
@thetumper please respect all bug template remarks, and answer all its questions

**Comment by thetumper** [comment]
Apologies!  Found that there is an additional script being used by our Jenkins deploy, not purely doing an "sls deploy".  This is a "black box" to us, and obscured the way that the bucket was attempted to be created, not to mention the deploy overall:

exited with code [255]. stderr:. . An error occurred (TooManyBuckets) when calling the CreateBucket operation: You have attempted to create more buckets than allowed
 at /var/opt/sourcecontrol/prod/src/bin/slsaws_deploy_create_s3_bucket.pl line 96.

Sorry for the trouble.  :(
