### ISSUE TITLE
Serverless plugins rely on node_packages directory in $CWD and not on NODE_PATH

### ISSUE THREAD

**Issue by takeda** [serverless/serverless#7976]
Is there a reason why serverless doesn't use `NODE_PATH` and instead requires `node_packages` directory in the project? I am trying to use serverless as a CLI command in a Python project and this requirement greatly complicates the work. I can cheat serverless by adding a symlink in root, but I wish I didn't need to.

**Comment by medikoo** [comment]
@takada `NODE_PATH` is kept in Node.js only for historic reasons. Otherwise it is not promoted but discouraged way for affecting resolution of dependent modules (you can read about it here: https://nodejs.org/api/modules.html )

So yes `NODE_PATH` is not supported but otherwise resolution of plugins works per Node.js rules, and that (for all known cases to me) is good enough.

Can you shortly describe your use case? What do you want to achieve via `NODE_PATH`

**Comment by takeda** [comment]
Basically for my development project (written in Python) serverless is only used as a deployment tool. I'm trying to package it up in a way that is self contained including necessary plugins. The goal is that developer doesn't need to run `node ci` s/he doesn't even need to know that serverless is nodejs application. Similarly to how not everyone knows that `aws` command from `awscli` is written in Python.

The developer only calls `sls deploy [arguments]` command and it supposed to deploy the application. I run into issues where I had working serverless, but it couldn't find the plugins. I reported it in this issue: https://github.com/svanderburg/node2nix/issues/197

Yesterday I realized that my problem was because serverless expects `node_packages` in $CWD. I was wondering if there's a way to provide path through environment variable, seemed like `NODE_PATH` was the way, but looks like it is not respected by serverless, I'm wondering if maybe there's another environment variable that I can define to tell serverless to look for plugins there. I know serverless has a field in `serverless.yml` to point to plugins location, but unfortunately that won't work for me, since in Nix (the tool that I use to package it) generates paths with cryptographic cash based on dependencies and architecture it is built on. So updating `serverless.yml` would be more troublesome than just creating `node_modules` symlink.

If there was an environment variable that I could define, or maybe an extra flag that I could pass to `sls` I could simply make a wrapper that could point to the right place.

**Comment by medikoo** [comment]
> Yesterday I realized that my problem was because serverless expects `node_packages` in $CWD.

If you mean `node_modules`. Then it follows same rules as Node.js. There's nothing custom in that.

> I was wondering if there's a way to provide path through environment variable, seemed like NODE_PATH was the way

Path to what? 

1. How do you reference plugins in `serverless.yml`?
2. Where is your service located?
3. Where are plugins you reference in `serverless.yml` located ?

**Comment by takeda** [comment]
> If you mean node_modules. Then it follows same rules as Node.js. There's nothing custom in that.

Yeah, I mean `node_modules` sorry.

> Path to what?
> 1. How do you reference plugins in serverless.yml?
> 2. Where is your service located?
> 3. Where are plugins you reference in serverless.yml located ?

Path to the `node_modules` containing serverless plugins. Basically, I don't want to have `node_modules` in $CWD. I don't want the user need to invoke `npm ci` since nix can do it for them. All I need is to tell serverless somehow that instead of using local `node_modules` directory it should look it up in another place (either through an environment variable or a command line option)

**Comment by medikoo** [comment]
> All I need is to tell serverless somehow that instead of using local node_modules directory it should look it up in another place (either through an environment variable or a command line option)

You can also use relative path, e.g. `../../path-to-plugin`

**Comment by takeda** [comment]
That also doesn't work for me. I could make wrapper to do a symlink on invocation, but I would prefer not to modify user's working directory. I would prefer if serverless + plugins could be self contained and I could invoke the `sls` command on any place on the disk.

**Comment by medikoo** [comment]
It looks to me that you're trying to host plugin outside of service folder, this is generally not supported by the Framework. 

Technically plugins should be in context of service folder

**Comment by takeda** [comment]
Can such support be added? The `node_modules` is acceptable if one works on nodejs project since it is needed anyway, but when serverless is used as a tool it becomes a hindrance.

If one would for example try to package serverless using rpm, deb or other packages, I believe this again could become a problem.

Any of these would probably work:
- respecting `NODE_PATH` environment variable
- custom variable e.g. `SLS_PLUGINS`
- extra option, e.g. `--plugins-path` option

**Comment by medikoo** [comment]
@takeda that doesn't seem safe, as you don't have any version control.

When plugins are installed with npm, you indicate (in `package.json`) which version of plugin you expect to be used 

How do you want to handle such validation in your approach?

**Comment by takeda** [comment]
It's a little hard to explain since nix is not as common tool, but what I'm doing is something like this:

```nix
{ makeWrapper
, nodejs
, pkgs
, stdenv
}:

{
  packageJSON ? ./package.json,
  packageLock ? ./package-lock.json,
  publishBinsFor ? []
}:

let
  package = builtins.fromJSON (builtins.readFile packageJSON);
in stdenv.mkDerivation {
  name = "${package.name}-nodejs-${package.version}";
  buildInputs = [ makeWrapper nodejs ];
  phases = [ "configurePhase" "buildPhase" "installPhase" "fixupPhase" ];

  configurePhase = ''
    runHook preConfigure
    export HOME=$PWD/npm_home
    npm config set color false
    npm config set progress false
    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    cp ${packageJSON} ./package.json
    cp ${packageLock} ./package-lock.json
    npm ci
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin $out/libexec
    mv node_modules $out/libexec
    for bin in ${pkgs.lib.concatStringsSep " " publishBinsFor}; do
      makeWrapper "$(realpath $out/libexec/node_modules/.bin/''${bin})" "$out/bin/''${bin}" --set NODE_PATH "$out/libexec/node_modules"
    done
    runHook postInstall
  '';

  fixupPhase = ''
    runHook preFixupPhase
    for bin in ${pkgs.lib.concatStringsSep " " publishBinsFor}; do
      patchShebangs --host $(realpath $out/libexec/node_modules/.bin/''${bin})
    done
    runHook postFixupPhase
  '';
}
```

Essentially I place in `$out` whatever I need to package. The `makeWrapper` script then creates a wrapper that looks like this:
```shell script
$ cat /nix/store/l2w7lfkkpmlg80kf43y6z9zlan07bmcf-amiman-nodejs-0.1.0/bin/sls                                                                                                                                                                            #! /nix/store/knd85yc7iwli8344ghav3zli8d9gril0-bash-4.4-p23/bin/bash -e
export NODE_PATH='/nix/store/l2w7lfkkpmlg80kf43y6z9zlan07bmcf-testapp-nodejs-0.1.0/libexec/node_modules'
ln -sf /nix/store/l2w7lfkkpmlg80kf43y6z9zlan07bmcf-testapp-nodejs-0.1.0/libexec/node_modules
exec "/nix/store/l2w7lfkkpmlg80kf43y6z9zlan07bmcf-testapp-nodejs-0.1.0/libexec/node_modules/serverless/bin/serverless.js"  "$@"
```

This ensures that the serverless and plugins are exact version that I requested, the only piece that's missing for me is to make serverless respect `NODE_PATH`.

**Comment by medikoo** [comment]
Why do you want to keep `node_modules` out of service folder? It looks that this approach causes issues on your side.

**Comment by takeda** [comment]
I explained this in previous comment, the reason is because my application is not a nodejs application. The directory is only use by nodejs and having it required being present in the same place where serverless.yml breaks separation between tool that is used and configuration of my project.

Imagine that if you were writing a nodejs application and wanted to use awscli with your project you were required to have virtualenv in your project directory. Or in order to have a gcc or clang compiler present you would need a copy of /usr/includes directory. What if you also use tools written in ruby, perl, etc. and each of them requires multiple directories to work?

Even in the link you provided https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders even though they mentioned `NODE_PATH` "is still supported, but is *less* necessary" (emphasis added), acknowledging that there are still use cases where it is needed. Similarly nodejs also scans `$PREFIX/lib/node`. All these things are still available to facilitate packaging of node applications.

I have specific use case that I want to achieve, typically this is done with other nodejs projects through `NODE_PATH`, if this is not the correct way is there a way achieving what I want? If not, can this issue turn into an issue needing fixing?

**Comment by takeda** [comment]
I didn't even think of it but I just accidentally realized that serverless using node_packages in project directory will affect reproducibility (this is the primary reason for I'm using nix). I want serverless to be packaged with necessarily plugins, but if an user would created `node_modules` directory in his or parent folder and had wrong versions there it would affect the running code.

I think our misunderstanding comes from looking at this from different perspectives. You appear of thinking of serverless as a 
(node) project dependency, for which it makes perfect sense to keep it in `node_modules`. I'm coming at this from the perspective of using serverless as a tool such as `awscli`, `jq`, `aws-vault`.

I don't want to force user (developer) to understand nodejs if they do development in let say python, or making them run extra `npm ci` to create and populate `node_packages` directory. It breaks the workflow. I want user to simply specify in their project that they need this version of serverless with needed plugins each having given version and the serverless is available together with other project dependencies. The ultimate benefit is that everything will be available through unified configuration and with a single command.

**Comment by medikoo** [comment]
@takeda I still have problems understanding your use case (let's focus on that, and not on solution proposals as that blurs the picture)

Do you want to package (with help of nix) a Serverless CLI together with some plugins, so it can work as some standalone binary for Python projects?
So e.g. someone installs your nix package and then out of a box has access Serverless CLI which also internally recognizes the plugins that are bundled with it?

**Comment by takeda** [comment]
That sounds about right.

BTW: I currently place plugins in the same location as serverless, so if it would scan for plugins in location it started from, that probably would work too.

**Comment by medikoo** [comment]
@takeda ability to package Framework with a plugins seems as valid use case.

I think the way to coin it would be to support a resolution of plugins from same location where framework is (as you suggested), but on if it's not resolvable at service location.

This should be added here: https://github.com/serverless/serverless/blob/03531d8bc6bce44a445e34e5046eaef6d95d0aa1/lib/classes/PluginManager.js#L26

PR is welcome!
