### ISSUE TITLE
AWS auth is broken when run in docker on EC2 instance

### ISSUE THREAD

**Issue by augusttown** [serverless/serverless#7978]
Facing "Could not locate deployment bucket..." error in serverless deploy since 1.76.0+. Running the exactly same deploy with 1.75.1 works without any issue. The error message is like below:

Could not locate deployment bucket. Error: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

We tried both export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, or EC2 role for deployment server for authentication, and same problem always exists in 1.76.0+. Nothing changed and simply switching back to 1.75.1 works without any issue.

**Comment by medikoo** [comment]
@augusttown please respect all bug template remarks and answer all its questions

**Comment by andreaadams11** [comment]
I ran into a similar issue with 1.76 and had to yum install bind-utils to install nslookup and that resolved the issue. This was in a docker container running on an EC2 instance running with an instance role.

**Comment by medikoo** [comment]
@andreaadams11 great thanks for info, that explains a lot. It should be fixed with next release

**Comment by ctudball** [comment]
Adding this fix means that serverless now has a requirement to have bind-utils/dnsutils installed, which currently none of our containers use.  Is having this package installed going to be a requirement moving forward?

**Comment by medikoo** [comment]
>  Is having this package installed going to be a requirement moving forward?

No, it'll be fixed today, so no such requirement is implied. It was definitely unintended.

**Comment by etaoins** [comment]
This didn't fix the issue for us: #7997
