### ISSUE TITLE
v0.5 - Deploy function include multiple subfolder throw ENAMETOOLONG

### ISSUE THREAD

**Issue by neaghfoz** [serverless/serverless#798]
I'm trying to deploy a function in folder like a/b/c and set the handler in ```s-function.json``` like that:
```
 "handler": "authorizers/usersAuthorizer/handler.handler"
```

it throw an exception:
```
usersAuthorizer: ENAMETOOLONG: name too long, open '/Users/peyton/ptt/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/_meta/_tmp/usersAuthorizer@1458015052852/.git/hooks/applypatch-msg.sample'
```

Then I try to make the folder structure like a/b and set handler like this:
```
 "handler": "usersAuthorizer/handler.handler"
```
It work!  But I want to reference another folder in the root dir, how to fix it? Or it's a bug?

**Comment by neaghfoz** [comment]
Hmm...I check the sources code right now and found that it doesn't support share lib function accross the functions in the root dir because if the handler is the begin with root path function, packageRoot will be the project's root, so it will copy the whole project in the ```_tmp``` dir by recursive.

I think it's better to give some exception about recursive copy file here. @ac360

**Comment by ac360** [comment]
Thanks @neaghfoz.  @minibikini Could you take a look at this?
