### ISSUE TITLE
Cannot install serverless via npm

### ISSUE THREAD

**Issue by shashank-sri** [serverless/serverless#7980]
I am facing the following problem while trying to install serverless on my machine via npm:

npm ERR! Unexpected end of JSON input while parsing near '...fc918327eba98fb","tar'

**Comment by shashank-sri** [comment]
the command I have used for global install is: 
sudo npm i serverless -g

the problems seems to be related to mkdirp dependency

**Comment by medikoo** [comment]
@shashank-sri it doesn't looks as issue on Framework side. It's probably some problem with your setup. Maybe network issues introduced some corrupted state, which exposed some npm bug.

You can confirm at https://npmview.now.sh/serverless that package is accessible as it should in a registry
