### ISSUE TITLE
Empty String Variable Value leaves variable name in generated s-resources-stage-region.json

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#799]
For one of my stages, I need the variable to be a zero length string. Right now, serverless interprets this as a false (missing) value and fails to replace the variable placeholder in the generated s-resources-stage-region.json file. I feel like this is a valid use case and that only `null` and `undefined` variables should fail to replace.

Using Serverless 0.4.0

**Comment by erikerikson** [comment]
This should be fixed by https://github.com/serverless/serverless/pull/792
