### ISSUE TITLE
Kotlin Gradle KTS

### ISSUE THREAD

**Issue by diegomarzo** [serverless/serverless#7991]
### Use case description

The current Kotlin template generate old fashioned Gradle files in Groovy only

### Proposed solution

Add a template to generate Kotlin KTS, we do not need to remove the existing one, just add a new one

**Comment by diegomarzo** [comment]
This is an enhancement and I already have the code working locally, so I'm more than happy to share in a PR

**Comment by medikoo** [comment]
@diegomarzo PR would be very welcome!

**Comment by diegomarzo** [comment]
Rolling it in!!
