### ISSUE TITLE
1.76.1 'sls package' requires AWS credentials with "ssm:" syntax

### ISSUE THREAD

**Issue by BogdanKushnirTR** [serverless/serverless#7993]
Looks similar to #6034

Running "serverless package" command stopped working in github actions where AWS credentials are not accessible.
Os: Ubuntu: 18.04 (github actions:   runs-on: ubuntu-18.04)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: myservice

custom:
  credentials: ${ssm:/aws/reference/secretsmanager/mysecret~true}

provider:
  name: aws
```
</details>

<details>
<summary><b><code>serverless package</code> output</b></summary>

```
  Serverless Error ---------------------------------------
 
  Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.2
     Framework Version:         1.76.1
     Plugin Version:            3.6.17
     SDK Version:               2.3.1
     Components Version:        2.33.0
 
##[error]Process completed with exit code 1.
```

</details>

<b>Installed version</b>

```
Framework Core: 1.76.1
Plugin: 3.6.17
SDK: 2.3.1
Components: 2.33.0
```

**Comment by medikoo** [comment]
@BogdanKushnirTR `sls package` requires all properties to be resolved in `serverless.yml`. Therefore if resolution depends on AWS SSM service the AWS credentials are required for command run

**Comment by BogdanKushnirTR** [comment]
@medikoo 
I can see two issues here:
1. it is a breaking change that was not reported
2. How to verify my package offline? In our case it is github actions run

**Comment by medikoo** [comment]
> it is a breaking change that was not reported

It never changed. `sls package` always was resolving variables prior packaging. If it worked for you before it could be that it worked only due to bug in framework, which introduced side effect of not presenting you with an error.

> How to verify my package offline? In our case it is github actions run

What exactly do you mean by _verify_?

Serverless Framework to be able to operate on service, needs to have it config resolved upfront, if resolution of your config implies a dependency on remote services, then it means that Framework cannot reason about your config offline.

**Comment by BogdanKushnirTR** [comment]
@medikoo 
Thanks for reply,
"Verifying" in my case means-testing for correctness. I would be happy to have the possibility to *mock* secret manager value just to perform an automated consistency check for my YAML. 

*Breaking change* term was used because literally dozens our CI checks started to fail in different repose after this release

**Comment by medikoo** [comment]
@BogdanKushnirTR sometimes it's the case that accidentally users rely on bug side effects. It's unfortunate, but it's hard to justify not fixing such bugs, especially if they're significant.

I think you may rewrite config parts that reference `ssm:` with some static values, and that way you'd have the config that works offline.

**Comment by BogdanKushnirTR** [comment]
@medikoo 
Ideally, I'd like to have some mocking functionality but `sed` will work for me too.
Thank you!
