### ISSUE TITLE
Deploying lambdas which attach to Event Bridge against "default" stage fails

### ISSUE THREAD

**Issue by TheEdgeOfCat** [serverless/serverless#7994]
I am setting up a multiple stage application. Currently, I have only the default dev stage, but now we need one more. The "default" stage as our MVP production environment and a dev one for deployments and testing. I'm using the name "default" because it's the name of the default terraform workspace and that's what the rest of the infrastructure is managed by.

Our architecture is multiple lambdas that communicate with events through the EventBridge service, currently the default event bus. My plan is to have a dev event bus that will be used by the dev env and have the default env use the default one. The problem arises when trying to deploy the default env. The deployment fails during the CloudFormation stack update due to missing IAM permissions on adding the routing rule on the default event bus. Deploying to dev works just fine (the event bus itself is created externally), it's only when deploying with the default event bus ARN that it fails. When ommiting the `eventBridge` key from the events config it works just fine. It seems to me that it doesn't create the STS permissions correctly when deploying to the default event bus, but I might be wrong.

I'm not sure whether I'm doing something wrong, but I've been through the whole documentation and haven't found anything.

Also, if there there is another way to deploy to different event busses based on the `stage`, that could work for me as well.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
    service: test

    provider:
      name: aws
      runtime: python${self:custom.pythonVersion}
      stage: dev
      region: us-east-1

    custom:
      stage: ${opt:stage, self:provider.stage}
      accountId: XXXXXXXXXXXX
      eventBus: arn:aws:events:${self:provider.region}:${self:custom.accountId}:event-bus/${self:custom.stage}
      pythonVersion: 3.7

    functions:
      main:
        handler: main.handler
        timeout: 30
        memorySize: 256
        events:
          - eventBridge:
              eventBus: ${self:custom.eventBus}
              pattern:
                detail:
                  test:
                    - arst
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* serverless deploy -s default</code> output</b></summary>

    /bin/sh: nslookup: command not found
    Serverless: Load command interactiveCli
    Serverless: Load command config
    Serverless: Load command config:credentials
    Serverless: Load command config:tabcompletion
    Serverless: Load command config:tabcompletion:install
    Serverless: Load command config:tabcompletion:uninstall
    Serverless: Load command create
    Serverless: Load command install
    Serverless: Load command package
    Serverless: Load command deploy
    Serverless: Load command deploy:function
    Serverless: Load command deploy:list
    Serverless: Load command deploy:list:functions
    Serverless: Load command invoke
    Serverless: Load command invoke:local
    Serverless: Load command info
    Serverless: Load command logs
    Serverless: Load command metrics
    Serverless: Load command print
    Serverless: Load command remove
    Serverless: Load command rollback
    Serverless: Load command rollback:function
    Serverless: Load command slstats
    Serverless: Load command plugin
    Serverless: Load command plugin
    Serverless: Load command plugin:install
    Serverless: Load command plugin
    Serverless: Load command plugin:uninstall
    Serverless: Load command plugin
    Serverless: Load command plugin:list
    Serverless: Load command plugin
    Serverless: Load command plugin:search
    Serverless: Load command config
    Serverless: Load command config:credentials
    Serverless: Load command rollback
    Serverless: Load command rollback:function
    Serverless: Load command upgrade
    Serverless: Load command uninstall
    Serverless: Load command login
    Serverless: Load command logout
    Serverless: Load command generate-event
    Serverless: Load command test
    Serverless: Load command dashboard
    Serverless: Load command output
    Serverless: Load command output:get
    Serverless: Load command output:list
    Serverless: Load command param
    Serverless: Load command param:get
    Serverless: Load command param:list
    Serverless: Load command studio
    Serverless: Load command dev
    Serverless: Invoke deploy
    Serverless: Invoke package
    Serverless: Invoke aws:common:validate
    Serverless: Invoke aws:common:cleanupTempDir
    Serverless: Packaging service...
    Serverless: Excluding development dependencies...
    Serverless: Installing dependencies for custom CloudFormation resources...
    Serverless: Invoke aws:package:finalize
    Serverless: Invoke aws:common:moveArtifactsToPackage
    Serverless: Invoke aws:common:validate
    Serverless: Invoke aws:deploy:deploy
    Serverless: [AWS cloudformation 200 0.567s 0 retries] describeStacks({ StackName: 'test-default' })
    Serverless: [AWS cloudformation 200 0.533s 0 retries] describeStackResource({
      StackName: 'test-default',
      LogicalResourceId: 'ServerlessDeploymentBucket'
    })
    Serverless: [AWS s3 200 0.563s 0 retries] listObjectsV2({
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Prefix: 'serverless/test/default'
    })
    Serverless: [AWS s3 200 0.517s 0 retries] headObject({
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849131098-2020-07-27T11:25:31.098Z/test.zip'
    })
    Serverless: [AWS s3 200 0.575s 0 retries] headObject({
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849131098-2020-07-27T11:25:31.098Z/custom-resources.zip'
    })
    Serverless: [AWS s3 200 0.524s 0 retries] headObject({
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849131098-2020-07-27T11:25:31.098Z/compiled-cloudformation-template.json'
    })
    Serverless: [AWS lambda 404 0.565s 0 retries] getFunction({ FunctionName: 'test-default-main' })
    Serverless: [AWS sts 200 0.667s 0 retries] getCallerIdentity({})
    Serverless: Uploading CloudFormation file to S3...
    Serverless: [AWS s3 200 0.571s 0 retries] putObject({
      Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 4595 more bytes>,
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/compiled-cloudformation-template.json',
      ContentType: 'application/json',
      Metadata: { filesha256: '6hVZjGELQUrdZKb+q5BZUvns5lHta0ZnFv/qwtLwbxU=' }
    })
    Serverless: Uploading artifacts...
    Serverless: Uploading service test.zip file to S3 (210.99 KB)...
    Serverless: [AWS s3 200 1.215s 0 retries] putObject({
      Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 16 00 00 00 2e 6d 79 70 79 5f 63 61 63 68 65 2f 2e 67 69 74 69 67 6e 6f ... 216007 more bytes>,
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/test.zip',
      ContentType: 'application/zip',
      Metadata: { filesha256: 'WtWZi9f1/Dts4Sa7XqCobBqzG0kL8UA4sBfg84R8YX8=' }
    })
    Serverless: Uploading custom CloudFormation resources...
    Serverless: [AWS s3 200 0.573s 0 retries] createMultipartUpload({
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/custom-resources.zip',
      ContentType: 'application/zip',
      Metadata: { filesha256: 'ASH3AzdyZ7aR1/cHATYqv/+VNc2A7P/oMjUb9rlX1dY=' }
    })
    Serverless: [AWS s3 200 1.836s 0 retries] uploadPart({
      Body: <Buffer d6 fa 85 c6 7d dd 5c 87 b8 a9 c4 6b 8b e2 3f ed e1 84 25 b3 37 d9 df a3 43 57 07 96 c1 55 a5 7f f5 99 65 02 c6 ec 97 ee a5 b1 c3 e1 67 43 f7 58 1c 97 ... 1890507 more bytes>,
      ContentLength: 1890557,
      PartNumber: 2,
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/custom-resources.zip',
      UploadId: 'hy2QQqsiV3k30GQeXznk8RFrFX75uqmf7aW4Zts0Mm3b6xKDkzq5odnuH5i.sDowhO4NsX9KsBdiYvo4NTt74uxurH5UjfnuZwqAiYq54jHxkZe9wRdeUeCyf8hqkUse'
    })
    Serverless: [AWS s3 200 2.055s 0 retries] uploadPart({
      Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 77 42 fb 50 00 00 00 00 00 00 00 00 00 00 00 00 09 00 00 00 52 45 41 44 4d 45 2e 6d 64 8d cd c1 09 80 30 0c 46 e1 7b a7 ... 5242830 more bytes>,
      ContentLength: 5242880,
      PartNumber: 1,
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/custom-resources.zip',
      UploadId: 'hy2QQqsiV3k30GQeXznk8RFrFX75uqmf7aW4Zts0Mm3b6xKDkzq5odnuH5i.sDowhO4NsX9KsBdiYvo4NTt74uxurH5UjfnuZwqAiYq54jHxkZe9wRdeUeCyf8hqkUse'
    })
    Serverless: [AWS s3 200 0.729s 0 retries] completeMultipartUpload({
      MultipartUpload: {
        Parts: [
          { ETag: '"f71a75ac912858f464438ba7b038650a"', PartNumber: 1 },
          { ETag: '"30bec8b09158c239f144b66620d1c3be"', PartNumber: 2 },
          [length]: 2
        ]
      },
      Bucket: 'test-default-serverlessdeploymentbucket-pe18n244hsx9',
      Key: 'serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/custom-resources.zip',
      UploadId: 'hy2QQqsiV3k30GQeXznk8RFrFX75uqmf7aW4Zts0Mm3b6xKDkzq5odnuH5i.sDowhO4NsX9KsBdiYvo4NTt74uxurH5UjfnuZwqAiYq54jHxkZe9wRdeUeCyf8hqkUse'
    })
    Serverless: Validating template...
    Serverless: [AWS cloudformation 200 0.702s 0 retries] validateTemplate({
      TemplateURL: 'https://s3.amazonaws.com/test-default-serverlessdeploymentbucket-pe18n244hsx9/serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/compiled-cloudformation-template.json'
    })
    Serverless: Updating Stack...
    Serverless: [AWS cloudformation 200 0.894s 0 retries] updateStack({
      StackName: 'test-default',
      Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
      Parameters: [ [length]: 0 ],
      TemplateURL: 'https://s3.amazonaws.com/test-default-serverlessdeploymentbucket-pe18n244hsx9/serverless/test/default/1595849415643-2020-07-27T11:30:15.643Z/compiled-cloudformation-template.json',
      Tags: [ { Key: 'STAGE', Value: 'default' }, [length]: 1 ]
    })
    Serverless: Checking Stack update progress...
    Serverless: [AWS cloudformation 200 0.952s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    .....Serverless: [AWS cloudformation 200 1.593s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    ...Serverless: [AWS cloudformation 200 0.884s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    Serverless: [AWS cloudformation 200 1.309s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    ......Serverless: [AWS cloudformation 200 0.918s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    .....Serverless: [AWS cloudformation 200 0.802s 0 retries] describeStackEvents({
      StackName: 'arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/test-default/2da65d80-cffb-11ea-9d11-0a34514375d1'
    })
    ....
    Serverless: Operation failed!
    Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3AXXXXXXXXXXXX%3Astack%2Ftest-default%2F2da65d80-cffb-11ea-9d11-0a34514375d1
     
      Serverless Error ---------------------------------------
     
      ServerlessError: An error occurred: MainCustomEventBridge1 - Failed to create resource. User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/test-default-IamRoleCustomResourcesLambdaExecution-1JCASNC6SJL2S/test-default-custom-resource-event-bridge is not authorized to perform: events:PutRule on resource: arn:aws:events:us-east-1:XXXXXXXXXXXX:rule/test-default-main-rule-1 See details in CloudWatch Log: 2020/07/27/[$LATEST]6588df80f4ca4199a1cd1bc538778756.
          at /usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33
      From previous event:
          at AwsDeploy.monitorStack (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
          at /usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:134:28
      From previous event:
          at AwsDeploy.update (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:134:8)
      From previous event:
          at AwsDeploy.<anonymous> (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:148:35)
      From previous event:
          at AwsDeploy.updateStack (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:144:33)
      From previous event:
          at AwsDeploy.<anonymous> (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
      From previous event:
          at Object.aws:deploy:deploy:updateStack [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
          at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:483:55
      From previous event:
          at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:483:22)
          at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:503:17)
          at AwsDeploy.<anonymous> (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
      From previous event:
          at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
          at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:483:55
      From previous event:
          at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:483:22)
          at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:518:24
      From previous event:
          at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:518:8)
          at /usr/lib/node_modules/serverless/lib/Serverless.js:133:33
      From previous event:
          at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:120:74)
          at /usr/lib/node_modules/serverless/scripts/serverless.js:54:26
          at processImmediate (internal/timers.js:458:21)
      From previous event:
          at Object.<anonymous> (/usr/lib/node_modules/serverless/scripts/serverless.js:54:4)
          at Module._compile (internal/modules/cjs/loader.js:1236:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
          at Module.load (internal/modules/cjs/loader.js:1085:32)
          at Function.Module._load (internal/modules/cjs/loader.js:950:14)
          at Module.require (internal/modules/cjs/loader.js:1125:19)
          at require (internal/modules/cjs/helpers.js:75:18)
          at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:41:1)
          at Module._compile (internal/modules/cjs/loader.js:1236:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
          at Module.load (internal/modules/cjs/loader.js:1085:32)
          at Function.Module._load (internal/modules/cjs/loader.js:950:14)
          at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
          at internal/main/run_main_module.js:17:47
     
      Get Support --------------------------------------------
         Docs:          docs.serverless.com
         Bugs:          github.com/serverless/serverless/issues
         Issues:        forum.serverless.com
     
      Your Environment Information ---------------------------
         Operating System:          linux
         Node Version:              14.6.0
         Framework Version:         1.76.1
         Plugin Version:            3.6.17
         SDK Version:               2.3.1
         Components Version:        2.33.0

</details>

<b>Installed version</b>

```
/bin/sh: nslookup: command not found
Framework Core: 1.76.1
Plugin: 3.6.17
SDK: 2.3.1
Components: 2.33.0
```

**Comment by medikoo** [comment]
@TheEdgeOfCat thanks for reporting. It looks it fails only when you deploy against _default_ event bridge, which seems to be pre-created by AWS.

It appears that in such case rule arn points account wide rule and not event bus specific one. At least removing `/${eventBusName}`, here: https://github.com/serverless/serverless/blob/f325d1b0596e72185ce41cd5120b67b1d63fad4b/lib/plugins/aws/package/compile/events/eventBridge/index.js#L159  fixes the case for `default` stage here, but then again it makes it not working for other stages.

I'll be happy to accept PR that properly addresses that and fixes

**Comment by TheEdgeOfCat** [comment]
Thank you for pointing me in the right direction, it would have taken me ages to find that. I have opened #7995, although I am not sure whether you meant it like that.
