### ISSUE TITLE
Allow common variables `domain` and `projectBucket` to be overridden in s-variables-dev-region.json

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#800]
I have a use case where the project bucket name and domain is different in our production stage. It actually exists under a different aws account id entirely. It would be nice if all of the different serverless commands could support the `s-variables-dev-region.json` containg the `domain` and `projectBucket` variables so that they override what is in the `s-variables-common.json` file. Every time I need to deploy to production, I have to modify those two vars in the `s-variables-common.json` file

And in case you're wondering, yes, when I deploy to production, I have to switch out my credentials manually right now since serverless has no way to support the AWS "assume role" feature.

**Comment by ac360** [comment]
@edclement We are removing Project Buckets in `v0.5`.  We used to rely on them more in the past to make up for missing Lambda features.  But AWS, has added those features and now project buckets introduce more complexity than value.

**Comment by edclement** [comment]
:+1:
