### ISSUE TITLE
The Kotlin template is lacking a dependecy for logging

### ISSUE THREAD

**Issue by diegomarzo** [serverless/serverless#8007]
One dependency is missing in the Kotlin template, we need to add 

`api("org.slf4j:slf4j-simple:1.7.30")`

The current configuration is missing this dependency and when a Lambda is running only logs in the handler work.

And also will be convenient to add the JUnit for Test (won't be packaged)

**Comment by diegomarzo** [comment]
I have the stuff fixed in my local fork, I can submit a PR

**Comment by medikoo** [comment]
@diegomarzo thanks for report. PR will be much apprieciated

**Comment by diegomarzo** [comment]
PR in place @medikoo
