### ISSUE TITLE
Config schema: Define AWS "provider" properties (top level only)

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8016]
### Use case description

Part of #8022

### Proposed solution

Define schemas for following properties:

__*Note:*__ _As that's a lot, proposed PR's may cover just some of them (or even just single one)_

- [ ] `stage` 
- [ ] `region`
- [ ] `stackName`
- [ ] `profile`
- [ ] `logRetentionInDays`
- [ ] `deploymentBucket`
- [ ] `deploymentPrefix`
- [ ] `rolePermissionsBoundary`
- [ ] `cfnRole`
- [ ] `stackTags`
- [ ] `iamManagedPolicies`
- [ ] `iamRoleStatements`
- [ ] `stackPolicy`
- [ ] `notificationArns`
- [ ] `stackParameters`
- [ ] `rollbackConfiguration`
- [ ] `tags`
- [ ] `logs.frameworkLambda`

Configuration should be done directly in: `lib/plugins/aws/provider/awsProvider.js`:

https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/provider/awsProvider.js#L141-L142

**Comment by glb** [comment]
@medikoo I'd like to take a crack at `resourcePolicy` to address #7795 ... any pointers on how to write tests for this?

I am able to get an error when I run manually:

```
Serverless: Configuration error at 'provider.resourcePolicy': should be array
```

:tada: but I'm trying to figure out the right magic to add a unit test to validate the validation. If I'm lucky you will see this before I pour too much more time into figuring out all the wrong ways to do it. 🙂

**Comment by medikoo** [comment]
@glb great to hear that!

>  any pointers on how to write tests for this?

I'm not sure if we should write tests for schema. AJV (validation engine) is extensively tested on it's own, so e.g.  testing that adding field to `required` array, will make it _required_ feels unnecessary and quite costly from maintenance perspective.

I believe we should just test a valid configuration (that'll confirm that by accident we do not invalidate a valid format), and it's ok to invalid cases purely in scope of schema rules (without further tests).

We may eventually write a single tests, that confirms on bad format in all properties and that unwanted properties are not sneaked, and if we do that, I will set `configValidationMode: error` for `runServerless` run, so intended action is pursued and there's just validation error that we deal with
