### ISSUE TITLE
Config schema: Define AWS "websocket" function event properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8019]
### Use case description

It'll be nice to have `websocket` event fully covered by schema validation

### Proposed solution

1. Define schema for following properties at `provider` level (that's part of #8022)

- [ ] `websocketsApiName`
- [ ] `websocketsApiRouteSelectionExpression`
- [ ] `apiGateway.websocketApiId`
- [ ] `logs.websocket`

Should be done directly in: `lib/plugins/aws/provider/awsProvider.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/provider/awsProvider.js#L141-L142

2. Define schema of all `websocket` event properties

Should be done directly in: `lib/plugins/aws/package/compile/events/websockets/index.js`:

https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/websockets/index.js#L54-L57

**Comment by zaldanaraul** [comment]
Hi,

I can try to tackle this if no one else is working on it. It'd be my first issue but I think I can do it!

**Comment by medikoo** [comment]
@zaldanaraul that'll be great! We look forward
