### ISSUE TITLE
Config schema: Define AWS "s3" function event properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8031]
### Use case description

It'll be nice to have `s3` event fully covered by schema validation

### Proposed solution

1. Define schema for following properties at `provider` level (that's part of #8022)

- [ ] `s3`

Should be done directly in: `lib/plugins/aws/provider/awsProvider.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/provider/awsProvider.js#L141-L142

2.  Define schema of all `s3` event properties

Should be done directly in: `lib/plugins/aws/package/compile/events/s3/index.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/s3/index.js#L14-L16

**Comment by chrisVillanueva** [comment]
@medikoo 

I should have time to work on this issue.  
Can you please share additional requirements / resources?

**Comment by medikoo** [comment]
> I should have time to work on this issue.

@chrisVillanueva great to hear that, Thank you!

> Can you please share additional requirements / resources?

What exactly do you miss? For examples on how schema can be filled see e.g. this PR: https://github.com/serverless/serverless/pull/8068

**Comment by chrisVillanueva** [comment]
I will have time this weekend to address.

I'll post any questions if they arise.

Thanks!

**Comment by medikoo** [comment]
Thank you @chrisVillanueva we're looking forward!

**Comment by chrisVillanueva** [comment]
Thanks medikoo.  I'm excited to move forward with this.

**Comment by thewizarodofoz** [comment]
Hey @chrisVillanueva did you take this one?
I have some time on my hands but wouldn't want to step on your toes.

**Comment by medikoo** [comment]
@thewizarodofoz I'm pretty sure you can take it. It'll be great to have that event covered
