### ISSUE TITLE
Config schema: Define AWS "schedule" function event properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8032]
### Use case description

It'll be nice to have `schedule` event fully covered by schema validation

### Proposed solution

Follow up to https://github.com/serverless/serverless/issues/6562, with which only schema placeholder for event was configured.

 Define schema of all `schedule` event properties

Should be done directly in: `lib/plugins/aws/package/compile/events/schedule/index.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/schedule/index.js#L17-L20

**Comment by andyjduncan** [comment]
Hi.  I've had a go at adding this validation.  I've tried to cover the validation with tests, but I'm not very happy with the Json string property validation.  I've left the [inline validation](https://github.com/serverless/serverless/pull/8143/files#diff-7efc760eaebd10dfdc553d056336cf08L81-L86) in place to avoid uncaught errors after validation.  I think to do this validation properly would need a custom format being [added to AJV](https://github.com/ajv-validator/ajv#api-addformat) but I don't see a mechanism for that.

**Comment by medikoo** [comment]
> I've tried to cover the validation with tests,

@andyjduncan Great thanks for giving it a go! Note, that we agreed to not write tests for validation (as schema validation engine is extensively tested on its own there seems not much value added in such tests, and it adds significant maintenance burden).

Technically with addition of a schema it's good to remove any inline validation (which will now be covered with schema) and it's related tests. For reference you may check how PR's that added other schemas, looked, e.g. for `cognito` event: https://github.com/serverless/serverless/pull/8105

**Comment by andyjduncan** [comment]
@medikoo Okay, I'll remove the tests and push an updated commit.  I've only left the Json parsing test as that's going to be difficult to test with pattern matching.  If the pattern I've added is sufficient (`^\{.*\}$`) I can take that out as well.
