### ISSUE TITLE
Config schema: Define AWS "sns" function event properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8035]
### Use case description

It'll be nice to have `sns` event fully covered by schema validation

### Proposed solution

Follow up to https://github.com/serverless/serverless/issues/6562, with which only schema placeholder for event was configured.

 Define schema of all `sns` event properties

Should be done directly in: `lib/plugins/aws/package/compile/events/sns/index.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/sns/index.js#L14-L17

**Comment by teamdraftbox** [comment]
@medikoo  I would like to take up this issue,Could you pls provide me with some more details on the issue as to what is needed

**Comment by medikoo** [comment]
@teamdraftbox great thanks for jumping in!

> Could you pls provide me with some more details on the issue as to what is needed

We just need a complete JSON schema for `sns` events to be configured here:

https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/sns/index.js#L14-L17

- No need for writing tests for that (AJV schema validation engine is extensively tested on its own)
- Documentation for JSON Schema: https://ajv.js.org/keywords.html also for reference you may check an already existing schemas (e.g. base one is here: https://github.com/serverless/serverless/blob/master/lib/configSchema.js)
