### ISSUE TITLE
No error is thrown when a plugin is specified in s-project.json, but doesn't exist

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#804]
No error is thrown when a plugin is specified in s-project.json, but the plugin does not exist. It seems more intuitive that this would result in a hard error.

**Comment by ac360** [comment]
@jordanmack Thanks for pointing this out.  Your help is always greatly appreciated :)

Fixed in 72e28c40759c2c1fa68d450fc51e457c295bcbfc
