### ISSUE TITLE
Serverless Error 

### ISSUE THREAD

**Issue by cgkbharadwaj** [serverless/serverless#8049]
sls deploy
 
  Serverless Error ---------------------------------------
 
  This command can only be run in a Serverless service directory. Make sure to reference a valid config file in the current working directory if you're using a custom config file
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.7.0
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.1

**Comment by medikoo** [comment]
@cgkbharadwaj for general support please use https://forum.serverless.com/ or https://www.serverless.com/slack
