### ISSUE TITLE
code E404 (npm i serverless) unable to install serverless framework

### ISSUE THREAD

**Issue by Ali-Dalal** [serverless/serverless#8054]
installing serverless framework fails and gives 404

not sure if the last published on npm has something to do with it

![image](https://user-images.githubusercontent.com/12471526/89515855-40ffcd00-d80a-11ea-8fbb-9eee4d747ead.png)

before this hour, I made 2 deployments and all went smoothly.

full trace:
```

npm ERR! code E404
--
25 | npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverless%2fcomponents - Not found
26 | npm ERR! 404
27 | npm ERR! 404  '@serverless/components@^2.33.4' is not in the npm registry.
28 | npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
29 | npm ERR! 404 It was specified as a dependency of 'serverless'
30 | npm ERR! 404
31 | npm ERR! 404 Note that you can also install from a
32 | npm ERR! 404 tarball, folder, http url, or git url.


```

**Comment by pradheepap** [comment]
Facing the same issue as well. 
Please suggest

**Comment by tomaszdudek7** [comment]
Same, my CI/CD pipeline fails to install it.

**Comment by akshaymishi** [comment]
facing same problem,

**Comment by exoego** [comment]
This seems issue on npm, not specific to serverless framework.
https://status.npmjs.org

**Comment by medikoo** [comment]
Closing as it's issue on npm side

**Comment by rghorpade-mdsol** [comment]
$ npm i serverless                                                                                                                                                                                                 npm ERR! code E404                                                                                                                                                                                                 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverless%2fcomponents - Not found
--

**Comment by medikoo** [comment]
Reopening (temporarily) so users see this and do not create duplicates.

Will close once issue on npm side in solved.

**Comment by chandanmca24** [comment]
Facing same issue.

**Comment by prajapat21bharat** [comment]
Facing same issue 

C:\Users\Thread Team\ab>npm i serverless@1.78.1-1f9eae98
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code E404
npm ERR! 404 Not Found: @tencent-sdk/capi@^0.2.17

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thread Team\AppData\Roaming\npm-cache\_logs\2020-08-06T10_34_16_645Z-debug.log

**Comment by exoego** [comment]
According to https://status.npmjs.org npm is now operational so issue might be gone.

**Comment by bharadwaj-poduri** [comment]
Yup issue resolved now!
