### ISSUE TITLE
"npm install -g serverless" throws error

### ISSUE THREAD

**Issue by Ksmike** [serverless/serverless#8055]
<details>
<summary><b><code>⚠️⚠️ Describe the issue</code></summary>

 I was just redeploying a version of my app to AWS via circleCI when my build failed because `npm install -g serverless` threw and error, I've attached a screenshot
![Screenshot 2020-08-06 at 11 30 24](https://user-images.githubusercontent.com/7250341/89516104-4ba16e80-d7d8-11ea-9c9a-2ebdbc8005f7.png)

Tried to run the line of code locally and got the same issue,

My local is using using Node: v14.3.0, and my build container is using Node:  v12,13 and it was working earlier today,

I messaged members of my team to see if they were having the same issue and it seems it fails in various different places,
</details>

Steps to reproduce:
 1) run `npm install -g serverless`
 2) see console error

**Comment by M1ke** [comment]
I'm experiencing this too, on local machine and on CI. Is there a reason it was closed?

**Comment by medikoo** [comment]
Duplicate of #8054
