### ISSUE TITLE
Allow file() variable to support TypeScript format

### ISSUE THREAD

**Issue by dl748** [serverless/serverless#8071]
### Use case description

Allow file() to accept more than just ".js" files to be executed.  e.g. .ts and .coffee
This can require an optional module for support

serverless.json
``` json
{
  "service": "${file(./config.ts)}",
  "functions": "${file(./config.coffee)}"
}
```

### Proposed solution

Use the interpret package to attempt to use a "require" loader (based on extension), if not, fall back to current processing.

**Comment by medikoo** [comment]
@dl748 thanks for request. What is the use case? You've just explained what you want, but not _why_ you want it.

Also what value do you see in supporting CoffeeScript?

**Comment by dl748** [comment]
Personally, I don't have value in that.  But I do have value in TypeScript, where I already have WebPack, and Gulp in full TypeScript, and I'd like to add this support to serverless in the effort of having all executed files as TypeScript.

.e.g. Webpack, i have all my files as webpack.config.ts, and my gulp configuration as gulpfile.ts

Otherwise, I have some typescript and some javascript (untyped).

**Comment by medikoo** [comment]
> Personally, I don't have value in that

I don't think we should invest time in things that are just _nice to have_ and doesn't address any real world use case at given point (note that currently we lack resources to address real needs)

I'm going to close this now, but we're definitely open to revisit that when eventual demand will appear

**Comment by dl748** [comment]
So what about TypeScript support, which I DO want?

**Comment by medikoo** [comment]
> So what about TypeScript support, which I DO want?

Sorry that was not perfectly clear to me. I'll reopen this. As we support TypeScript as top file configuration file format, it definitely makes sense to support TS in variable _file_ service scope.

PR that provides that is welcome!

**Comment by dl748** [comment]
The PR that i provided does that as well, it just happens to also give support for several other files as well.

**Comment by medikoo** [comment]
>  the PR doesn't add ANY transpilers or preprocessors as a dependency

Indeed, it just adds dependency of `interpret`, which on its own doesn't bring any transpilers.

> Why do you want to limit a developers choice when you don't have to?

As I mentioned due to limited resources we're focused on addressing only real world (and not "nice to have") use cases, as we agreed, there's only one real use case to address here (support TS files via variable extensions) and we're open for PR on that.

**Comment by dl748** [comment]
Closing, I've found my workaround for this feature.

**Comment by G-Rath** [comment]
@medikoo I'm interested in this, and might try to land a PR for it in the near future - just want to confirm first that this is still true: 

> Currently the only flaw is that we do not support TS file as file var scope extensions (and PR that brings that is definitely welcome)

It should in theory be a pretty straightforward patch as it should be the same logic as what's used for `serverless.ts`, but don't want to do the work if there's no interest in landing it :)

**Comment by medikoo** [comment]
@G-Rath I think as we support TS files being top level, it makes sense to supporting then in `file:` variables. Still any work on that should be done with consideration for following:

1. Currently we're discussing moving TS support to external repository -> https://github.com/serverless/typescript/issues/28#issuecomment-779286001
2. Currently we're rewriting variables parser and resolver from scratch (it's in context of https://github.com/serverless/serverless/issues/8364, and PR with new resolver will posted within few days).

Having that it's probably worth to wait a bit, until above matters settle, and implementing this in current variables resolver context doesn't make much sense, as it's about to be ditched completely.

**Comment by G-Rath** [comment]
Fair enough - I don't mind waiting if there's something actually in the works that's expected to land in a few weeks.

When it does land, feel free to ping me - I'd be happy to get this feature landed asap as I'm in need of it :)

**Comment by medikoo** [comment]
Great thanks @G-Rath for raising an interest! I'll definitely update this issue, once we will settle on recommend approach on solving this issue

**Comment by pushred** [comment]
@medikoo This still seems to be an issue following the #8364 changes which I understood were to be a new starting point for whatever solution addresses this particular need. But is a new issue warranted now? I'm not seeing that #28 would address this and also appears stuck.

When I reference a TS file with the `file()` variable syntax I get an error that doesn't quite make sense:

```
Cannot resolve serverless.ts: Variables resolution errored with:
  - Cannot resolve variable at "example.path": Value not found at "env" source
```

`Environment: darwin, node 18.14.2, framework 3.27.0 (local), plugin 6.2.3, SDK 4.3.2`

**Comment by medikoo** [comment]
@pushred in my eyes best way to support it is via introducing extensions as proposed here: https://github.com/serverless/serverless/issues/9311

Yet,  I'm no longer with Serverless Inc., and I'm not familiar with current roadmap and priorities I also don't have any rights to accept and release any further updates here (as far as I know it's @Danwakeem that takes care of Framework maintenance now)

**Comment by pushred** [comment]
@medikoo ah thank you for such a quick update on where this stands! #9311 does look sensible, will watch that
