### ISSUE TITLE
@types/serverless Doesn't Export `Plugin`

### ISSUE THREAD

**Issue by shellscape** [serverless/serverless#8080]
My upfront apologies if this is not the proper place to report this, but issues on DeinitelyTyped might as well be yelling into the abyss, and some of the contributors on that package are also contributors here (Like @ThomasAribart). So here's hoping...

The `@types/serverless` package has a glaring type error. Namely, `Plugin` is never exported from the index. See the import and lack of export (or use) here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/index.d.ts#L12

_(Sorry, not sure how to list a reproduction here. It's more of a code error than something that can be reproduced.)_

_(See above, there really isn't a command to run per se)_

**Comment by dl748** [comment]
You should be able to access this 1 of 2 ways. Note: not all types needs to be exposed through the default namespace.

```
type ServerlessPlugin = import('serverless/classes/Plugin')
const myPlugin: ServerlessPlugin = {
  ...
}
```
OR
```
import * as ServerlessPlugin from 'serverless/classes/Plugin'
const myPlugin: ServerlessPlugin = {
  ...
}
```

**Comment by shellscape** [comment]
@dl748 thanks, but that's not the point of this issue.

**Comment by dl748** [comment]
Can I ask what is then?  None of the other types are defaulted exports either, like Service, PluginManager, YamlParser, and Utils?  This seems to be by design more than error.  I could argue a change in the design so that they are also exported in the main namespace, but its hardly an "error".

**Comment by shellscape** [comment]
@dl748 sure thing. The point is that the typedef is importing `Plugin` and doing absolutely nothing with it. Do a quick search in that file for `Plugin` and you'll see what I mean. The import serves no purpose. On the flip side, `PluginManager` is imported and [is subsequently exposed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/index.d.ts#L75)

There's a mistake here and probably one of two possibilities:

1. The `Plugin` type was never exposed, along side `PluginManager`
1. The import was left there erroneously.

I really hope it's #1, and that it'll be corrected soon. That's an incredibly useful type for plugin authors. If it's #2 then hey no worries, and I hope the import gets cleaned up and the types are better for it.

**Comment by dl748** [comment]
> @dl748 sure thing. The point is that the typedef is importing `Plugin` and doing absolutely nothing with it. Do a quick search in that file for `Plugin` and you'll see what I mean. The import serves no purpose. On the flip side, `PluginManager` is imported and [is subsequently exposed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/index.d.ts#L75)

That line is a variable exposed, not the type.  There is a big difference.  Even if you added a line "_dummy: Plugin", the type wouldn't be "usable", just like "PluginManager" isn't usable.  The PluginManager type is exposed through  type PluginManager = import('serverless/classes/PluginManager');

> There's a mistake here and probably one of two possibilities:
> 
> 1. The `Plugin` type was never exposed, along side `PluginManager`
> 2. The import was left there erroneously.
> 
> I really hope it's #1, and that it'll be corrected soon. That's an incredibly useful type for plugin authors. If it's #2 then hey no worries, and I hope the import gets cleaned up and the types are better for it.
> 
> _Side note: FWIW accessing modules (or types) from a package's subdirectory is a long-standing Node anti-pattern that is widely discouraged. It makes for tough upgrade paths and maintainers are not required to notify users of file system refactoring between semver versions, even patch versions. That's a very brittle way of working._

Note: Plugin isn't a class that is defined by serverless, it just uses whatever is passed in. There is no OO in it.  So Plugin is just an interface to what is used by Serverless.

**Comment by shellscape** [comment]
Doesn't matter which ribbons you try to wrap this in, there's still an orphaned import in that file that shouldn't be there if the imported value wasn't intended to be used. I'm not sure what you're smoking, but I want some of it. Sounds like a party.

I'm gonna disengage with you now and wait for a maintainer to put eyes on this.

**Comment by medikoo** [comment]
@shellscape please report at https://github.com/DefinitelyTyped/DefinitelyTyped/ this doesn't belong to this repository

**Comment by shellscape** [comment]
That's disappointing. There's 3400k issues open there. That's where issues go to die.
