### ISSUE TITLE
Prototype pollution in dot-prop@4.2.0 which is used in update-notifier@2.5.0

### ISSUE THREAD

**Issue by sumit-tw** [serverless/serverless#8082]
A security check fails for Serverless in versions 1.71.1 to 1.78.1

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by instantlinux** [comment]
Dup? Check #7486

**Comment by medikoo** [comment]
Duplicate of https://github.com/serverless/serverless/issues/7486
