### ISSUE TITLE
Use dedicated deprecation logger for httpApi.timeout and eventually remove support for it

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8087]
### Use case description

Deprecation of `httpApi.timeout` was added before we had dedicated deprecations logger.

It'll be nice to use dedicated mechanism, that way change will not be accidentally lost when we will release new major.

Having that in branch for next major we should remove support for `httpApi.timeout`

#### v1

Replace deprecation logs in [lib/plugins/aws/package/compile/events/httpApi/index.js](https://github.com/serverless/serverless/blob/01a03d103bde0476690ab2e61c81a9f00ae607df/lib/plugins/aws/package/compile/events/httpApi/index.js), with deprecation log as documented here: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations

#### v2

Remove support for `httpApi.timeout` and deprecation log

**Comment by Yogendra0Sharma** [comment]
@medikoo Can i work on this issue? please assign it to me.

**Comment by medikoo** [comment]
@Yogendra0Sharma sure, thank you!
