### ISSUE TITLE
Auto update global Serverless installation behind the scenes (as opt-in)

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8088]
### Use case description

With globally installed version it'll be nice to provide a mechanism to auto update whenever new (_patch_ or _minor_) version is released

### Proposed solution

As it's intended to work also in Components CLI, I believe we need to implement core parts in [@serverless/utils](https://github.com/serverless/utils)

1. Introduce `autoUpdate` config option (`false` by default)
2. Support `sls config --autoupdate` and `sls config --no-autoupdate`, through which `autoUpdate` can be set.
    Note: If user is relying on global npm installation and tries to enable auto updates, we should confirm it's writable. If not we should reject the request with meaningful message
3. if new _minor_ or _patch_ release is detected pursue following:
    1. If `autoUpdate` is not set. Expose same information as now, but add note that Framework can autoupdate itself via `sls config --autoupdate`
    2. If `autoUpdate` is set try to auto update the installation (outlined below)

#### Auto update global npm installation

1. Check if global npm installation is writable (via e.g. attempting to rewrite `LICENCE.txt` file in framework folder). If it's not issue a warning, expose an info about new version, and do not follow with next steps
2. Install new version of serverless to temporary folder 
3. If serverless commands ends before intiailized installation ends, stop installation and cleanup, and write `forceUpdate` to config (to reattempt on next command)
4. After new version is successfully installed, wait for serverlress command to end
5. Remove old installation. Move new installation in place
6. Issue a log that serverless was successfully update to vX

#### Auto update standalone installation

1. Download new version to temporary file
3. If serverless commands ends before download succeeds, stop download and cleanup, and write `forceUpdate` to config (to reattempt on next command)
4. After download completes, wait for serverless command to end
5. Remove old installation. Move new installation in place
6. Issue a log that serverless was successfully update to vX

Additionally:
- Prevent new version check (and auto update) on `sls plugin install` command - to avoid parallel run of npm commands

**Comment by georgesbiaux** [comment]
Hi! Is it ok if I try to work on this issue ?

**Comment by medikoo** [comment]
@georgesbiaux definitely! I initially didn't mark it with _help wanted_ as felt that it might be too sophisticated, but you feel you can implement it, it's definitely welcome.

There's just one thing that I believe should be implemented independently (in other PR) before tackling this task as a whole.

It's to address _wait for serverlress command to end_ constraint - for that we need some clear and accessible indicator that _serverless_ did its job and it's about to exit.

I propose to introduce a `serverless.onExitPromise` (better name welcome) promise property [here](https://github.com/serverless/serverless/blob/5f85543d8e47a9afaec6811a57e1235e82949550/scripts/serverless.js#L49).
It should be created right after instance intialization and resolved in same places where `resolveServerlessExecutionSpan` is resolved. I would also remove `resolveServerlessExecutionSpan` and provide a `serverless.onExitPromise` to `sendPending`, as it's about same thing.

Let me know if you have any other questions towards that

**Comment by georgesbiaux** [comment]
@medikoo Here is the first PR too to address wait for serverlress command to end constraint: https://github.com/serverless/serverless/pull/8146

Do you think I need to add some tests? Or is it fine this way, since it is basically a refactor of the `resolveServerlessExecutionSpan` ?

**Comment by medikoo** [comment]
> Do you think I need to add some tests? Or is it fine this way, since it is basically a refactor of the resolveServerlessExecutionSpan ?

It's totally fine the way you've implemented it. This script is invoked by few integration tests, so eventual issue would be exposed

**Comment by georgesbiaux** [comment]
Hello @medikoo, do you think it will be possible to re-use the [upgrade](https://github.com/serverless/serverless/blob/master/lib/plugins/standalone/index.js#L44) function that already exists? It seems suitable for the standalone auto-update.

**Comment by medikoo** [comment]
> do you think it will be possible to re-use the upgrade function that already exists

@georgesbiaux thanks for asking. What exactly do you want to re-use this function for?

afaik that the only command that is involved into this feature, is one through which user updates it's configuration setting (on whether he wants to have an auto-update working or not), and we already have dedicated `config` command, for user configuration updates.

**Comment by medikoo** [comment]
@georgesbiaux now it got to me, that you've proposed to invoke internally `sls upgrade` whenever we detect update.

I think this high level approach won't work well in this case. What we could do though it to seclude some eventually reusable parts from `sls upgrade` internals to reusable methods or utils. Otherwise I would strictly stick to implementation proposal as outlined in main description
