### ISSUE TITLE
Add support for eu-central-1

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#810]
[Frankfurt supports Lambda](https://twitter.com/awscloud/status/709526472751325186)! Would be great if we add it!

**Comment by eahefnawy** [comment]
Done! Thanks for the heads up @pmuens. You rock!!

**Comment by pmuens** [comment]
Awesome @eahefnawy thank you very much!

![you_rock_you_rule](https://cloud.githubusercontent.com/assets/1606004/13914465/ce34ab5e-ef4e-11e5-963c-ffc9f2845282.jpeg)

**Comment by bastibense** [comment]
I came here to request support for eu-central-1, too, since Lambda is (afaik) fully supported there now and it's way closer to my customers and me than Dublin (eu-west-1). So...

+1
