### ISSUE TITLE
Sticky duration picker on app.serverless.com

### ISSUE THREAD

**Issue by harshchau** [serverless/serverless#8104]
On the dashboard at app.serverless.com, when we pick a time duration, the duration is not sticky. That is, as we navigate back and forth, it always resorts to the default last 24 hours

Does not involve serverless.yml 

Not related to CLI

Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.6

**Comment by medikoo** [comment]
@harshchau thanks for reporting. Still dashboard UI issues should be reported via "support" link (in bottom left corner).

Can you report your issue over there?

**Comment by harshchau** [comment]
Done
