### ISSUE TITLE
add support in credentials for aws_session_token

### ISSUE THREAD

**Issue by martinlindenberg** [serverless/serverless#811]
We are using temporary credentials to grant access to aws.
therefore aws requires the client to submit accessKeyId, secretAccessKey and sessionToken

see: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#constructor-property

Serverless currently only supports to submit accessKeyId and secretAccessKey.

**Comment by hauboldj** [comment]
It's coming in v0.5.0. I'm using v0.5.0 now with SessionTokens

**Comment by martinlindenberg** [comment]
ok - i think this topic can be postponed to 0.5.0
