### ISSUE TITLE
Support for Asynchronous Configuration Files

### ISSUE THREAD

**Issue by dl748** [serverless/serverless#8113]
### Use case description

Currently serverless requires that exports be a plain object, and doesn't allow for any possible asynchronous processing which many other third party modules do.

Examples of configurations that export asynchronous functions to do some kind of processing.

js
```
module.export = () => {
  return new BbPromise((res) => {
    // Do async stuff in here
    res({
      service: {
        name: "myservice"
      }
      ...
    })
  })
}
```

ES6/TypeScript
```
export default async() => {
  ... await async stuff here
  return {
    service: {
      name: "myservice"
    }
  }
}
```

A lot of newer third party modules are all promises/async, so in order to use those modules we would need a way to do async configs.

### Proposed solution

The underlying system is already Promised based, just a few lines need to be added to support this.

https://github.com/serverless/serverless/blob/b0938c7d9bd946c5c9af6bae99ae6f7931242ba6/lib/utils/getServerlessConfigFile.js#L120

```
      return (isJSOrTsConfigFile
        ? handleJsOrTsConfigFile(configFilePath)
        : readFile(configFilePath)
      ).then(config => {
        if (typeof(config) === "function") return BbPromise.resolve(config(serverless));
        if (_.isPlainObject(config) && typeof(config.default) === "function")
          return BbPromise.resolve(config.default(serverless))
        return config
      }).then(config => {
        if (_.isPlainObject(config)) return config;
        throw new ServerlessError(
          `${path.basename(configFilePath)} must export plain object`,
          'INVALID_CONFIG_OBJECT_TYPE'
        );
      });
```
Adding a second then before the first, and then check to see if config or config.default is a function and call it. Then resolves the returned value, otherwise return the original to the chain, would allow normal as well as async functions to be processed.

Note: I am also passing in the serverless object, I think this is nice feature as well in case the config wants to do something based on serverless settings, command line options, or variable access.

**Comment by medikoo** [comment]
> exports variable is not available via typescript

In TS it's equivalent to exporting an object that has `property` property. Please discuss on support forums on how to achieve that.

> and .ts files do not work with file().

This is handled here: https://github.com/serverless/serverless/issues/8071

**Comment by dl748** [comment]
I still cannot get this to work... I created a serverless.ts file and its being imported

serverless.ts
```
console.log('here');
```

I see the 'here' when i run serverless.

```
export const service = {
  name: '1234'
}
```

seems to work, the serverless sees the name property.  But I can't seem to do any async in the serverless.ts file.

**Comment by medikoo** [comment]
Configuration file is expected to export JSON structure, and _async_ resolution can only be achieved via variable file imports as pointed here https://github.com/serverless/serverless/issues/8113#issuecomment-678298912

**Comment by dl748** [comment]
> Configuration file is expected to export JSON structure, and _async_ resolution can only be achieved via variable file imports as pointed here

I know that, that's the whole point of this issue.  To get first class support for configuration files that are coded.

The mere fact that its a 4 lined addition with 100% backwards compatibility, but not even considered or taken seriously is very sad.  The fact that the "solution" is to have developers manage 2 configuration files is not a real solution.

Because of that, I'm closing this issue.

For those that look at this issue, I was able to achieve a semi-desired effect with a plugin that reloads the configuration AFTER its promise has been resolved.  Unfortunately, it comes with some "warnings/errors" that get bypassed

serverless.ts
```
const sleep = (ms: number) => new Promise<void>((res) => setTimeout(res, ms))

export default async() => {
  console.log('START')
  await sleep(60000)
  console.log('END')
  return {
    service: {
      ...service,
    },
    provider: {
      ...provider,
      runtime: 'nodejs12.x',
      memorySize: '512',
    },
    plugins: plugins,
    functions: {
      handleTest: {
        name: 'handleTest',
        handler: 'index.handleTest',
        description: 'test',
        events: [
          {
            http: {
              path: '/api/test',
              method: 'GET',
            }
          }
        ]
      }
    }
  }
}

export const service = {
  name: 'Test',
}

export const provider = {
  name: 'aws'
}

export const plugins = [
  './mymodules/serverless_hijack',
  'serverless-webpack',
  'serverless-offline',
]
```

My module is in TypeScript which i had to compile separately for serverless to recognize it as a plugin. But my plugin forces all the other plugins to halt and wait for the async configuration.  Unfortunately, i have to export service, provider (so it doesn't error out for an invalid configuration), and plugins to force my use of plugins.  A super horrible hack, but it works as expected and doesn't require me to manage multiple files.

```
$ npx serverless offline start
Serverless: Configuration warning at root: unrecognized property 'default'
Serverless:
Serverless: If you prefer to not continue ensure "configValidationMode: error" in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with "configValidationMode: off" setting
Serverless:
Serverless: The only way to achieve a coded dynamic configuration is to hijack serverless code
SSTART
END
Serverless: Bundling with Webpack...

Time: 13240ms
Built at: 09/14/2020 6:48:23 PM
       Asset      Size  Chunks                   Chunk Names
    index.js  3.94 KiB   index  [emitted]        index
index.js.map  3.74 KiB   index  [emitted] [dev]  index
Entrypoint index = index.js index.js.map
[./index.ts] 136 bytes {index} [built]
Serverless: Watching for changes...
offline: Starting Offline: dev/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002

   ┌──────────────────────────────────────────────────────────────────────────────┐
   │                                                                              │
   │   GET | http://localhost:3000/dev/api/test                                   │
   │   POST | http://localhost:3000/2015-03-31/functions/handleTest/invocations   │
   │                                                                              │
   └──────────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3000 🚀
offline:
offline: Enter "rp" to replay the last request
```

As you can see, i get an error/warning on startup because "default" is not apart of the configuration spec.
Note: between my "START" and "END" i have a 60 second wait, and it does wait before trying to continue, and you can see that my function was added as well as the provider runtimes.

Print worked good too

```
$npx serverless print
START
END
service:
  name: Test
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: '512'
plugins:
  - ./mymodules/serverless_hijack
  - serverless-webpack
  - serverless-offline
functions:
  handleTest:
    name: handleTest
    handler: index.handleTest
    description: test
    events:
      - http:
          path: /api/test
          method: GET
```

**Comment by medikoo** [comment]
@dl748 thanks for a feedback. If we will see increased demand to support asynchronous resolution of service configuration we will definitely consider that.

For now I think asynchronous resolution through variable extensions should be good enough, as at least in all cases known to me, it's just some parts of config that may require asynchronous resolution, and not config as a whole

**Comment by alanning** [comment]
For those running into this same issue, here is a way to access command line args in the `settings.ts` file:

```
import type { AWS } from '@serverless/typescript'
import { program } from 'commander'

program
  .option('--stage <n>', 'stage')
  .option('--region <n>', 'region')
  .option('--bucket <n>', 'bucket')
  .parse()

const options = program.opts()

const stage: string = options.stage
const region: string = options.region
console.log(`[serverless.ts] stage: '${stage}', region: '${region}'`)

const serverlessConfiguration: AWS = {
  service: 'myService',
  // ...
}

module.exports = serverlessConfiguration

```

Basically we get the CLI args directly from `process.argv` instead of relying on serverless.
 
======
UPDATE 2026-02-25:
The latest version of `commander` no longer works like this so we use a simple function to parse argv instead:
`const options = parseArgvLongOptions(process.argv)`
Function source + tests: https://gist.github.com/alanning/e3fb9343e020008cb322da22e28a3175


Original source:
https://medium.com/@pvlasov/power-up-serverless-framework-with-javascript-configurations-9cf4b9c6ee76
