### ISSUE TITLE
Remove support for `maximumEventAge` and `maximumRetryAttempts` at `functions[].destinations`

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8119]
### Use case description

With #7987 we've deprecated `maximumEventAge` and `maximumRetryAttempts`  as set on `functions[].destinations` level.

For v2 release support should be removed

### Proposed solution

PR should be based against [`v2`](https://github.com/serverless/serverless/tree/v2) branch

Remove deprecation message and support for `maximumEventAge` and `maximumRetryAttempts`  as set on `functions[].destinations` level.

**Comment by pgrzesik** [comment]
I would be happy to work on this one if there's help needed :raised_hands: Should I just prepare a PR or there's a separate process of introducing breaking changes for V2 release that I should follow?

**Comment by medikoo** [comment]
@pgrzesik I've just created a [`v2`](https://github.com/serverless/serverless/tree/v2) branch, and PR should be based against it. Great thanks upfront!
