### ISSUE TITLE
Feature Request: IoT Event Source

### ISSUE THREAD

**Issue by hauboldj** [serverless/serverless#812]
Something like
{
"name" : "myIotRule",
"type": "iotRule",
"config": {
  "sql" : "SELECT * FROM my/topic WHERE someValue == True",
  "description": "Receive messages from my/topic",
  "ruleDisabled": false
}

**Comment by shortjared** [comment]
https://github.com/serverless/serverless/pull/1061

**Comment by flomotlik** [comment]
closing as this has been merged
