### ISSUE TITLE
Remove support for provider.alb.authorizers[].allowAuthenticated

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8120]
### Use case description

With https://github.com/serverless/serverless/issues/7773 we've deprecated `allowUnauthenticated` in favor of `onUnauthenticatedRequest`. For v2 support for `allowUnauthenticated` should be removed

### Proposed solution

Remove support for `allowUnauthenticated` and its deprecation notice.

PR should be based against [`v2`](https://github.com/serverless/serverless/tree/v2) branch

**Comment by morgan-sam** [comment]
Hi I've started to work on this one

**Comment by medikoo** [comment]
Thank you @morgan-sam !
