### ISSUE TITLE
Files that contain dots are ignored during packaging

### ISSUE THREAD

**Issue by crash7** [serverless/serverless#8125]
I have a serverless service that contains files that starts with something like `[...file].js`. When running `sls package`, those files don't end in the zipfile because they are being ignored.

So, given a file structure like this:
```
folder/
  other.js
  [...file].js
handler.js
```
The end result is:
```
Archive:  .serverless/my-service.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-1980 00:00   folder/other.js
      442  01-01-1980 00:00   handler.js
---------                     -------
      442                     2 files
```

The problem, at least one part of it, lies in the `dot` parameter that the library use for `globby`: https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L252

Using `dot: false`, makes globby output the file as part of the list.

Trying to use directly something like `folder/[...file].js` as part of my inclusion list doesn't work either.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  runtime: nodejs12.x

package:
  excludeDevDependencies: true
  exclude: 
    - '**/*'
  include:
    - handler.js
    - folder/**

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>yarn serverless package</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.7
```

**Comment by crash7** [comment]
Just found that this fix from `serverless-components` works fine: https://github.com/serverless-components/aws-lambda/pull/26/files. I'm currently porting it to `serverless` and should have a PR soon.

**Comment by medikoo** [comment]
@crash7 thanks for report!

Interestingly, it worked, and got broken when addressing https://github.com/serverless/serverless/issues/7689

We had same request before (https://github.com/serverless/serverless/pull/7550) but we rejected as we could not reproduce, still then we used globby v6

**Comment by crash7** [comment]
@medikoo my search-fu needs work, sorry for raising a new issue - I clearly didn't find #7550.
It's strange that it worked with half of the changes in that PR (I changed the packageService.js in `my-service` project). I can upload the project in a repo, but since I'm just using the quickstart template and just adding an empty file, should be easy to reproduce.

Let me know how I can help.

Thanks!
