### ISSUE TITLE
A Python app with dependancies deploys broken because of wrong architecture of packages

### ISSUE THREAD

**Issue by mooperd** [serverless/serverless#8140]
On OSX, if you don't have this -> https://www.serverless.com/blog/serverless-python-packaging 

then it will happily, silently deploy a broken app. It would probably be quite easy to have some logic to test that the package is compatible with the target environment.

I guess it "just works" on Linux.

**Comment by medikoo** [comment]
@mooperd can you respect all bug template remarks and fill answers to all questions?

**Comment by mooperd** [comment]
Erh, nevermind.
