### ISSUE TITLE
AWS S3 Deployment fails with custom deploymentBucket

### ISSUE THREAD

**Issue by marcelalburg** [serverless/serverless#8154]
After some months of no deployment, i updated to the latest version of serverless. A new deployment is not working anymore and stops with an error that my localhost:443 is not reachable. I debugged this issue and figure out that the reason is my custom deploymentBucket name. If i replace the dots with dashes in the name, it works. 

Even i tried to deploy without AWS S3 Acceleration `sls deploy --stage staging --no-aws-s3-accelerate`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
  versionFunctions: false

  region: eu-central-1

  deploymentBucket:
    name: serverless.${self:provider.region}.deploys
```

</details>

<details>
<summary><b><code>Error Output</b></summary>

```
Serverless: [AWS s3 undefined 0.488s 3 retries] getBucketLocation({ Bucket: 'serverless.eu-central-1.deploys' })
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:443), sleeping for ~5 seconds. Try 1 of 4
Serverless: [AWS s3 undefined 0.275s 3 retries] getBucketLocation({ Bucket: 'serverless.eu-central-1.deploys' })
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:443), sleeping for ~6 seconds. Try 2 of 4
Serverless: [AWS s3 undefined 0.415s 3 retries] getBucketLocation({ Bucket: 'serverless.eu-central-1.deploys' })
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:443), sleeping for ~4 seconds. Try 3 of 4
Serverless: [AWS s3 undefined 0.615s 3 retries] getBucketLocation({ Bucket: 'serverless.eu-central-1.deploys' })
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:443), sleeping for ~7 seconds. Try 4 of 4
Serverless: [AWS s3 undefined 0.232s 3 retries] getBucketLocation({ Bucket: 'serverless.eu-central-1.deploys' })
```
</details>

<b>Installed version</b>

```
Framework Core: 1.80.0
Plugin: 3.8.1
SDK: 2.3.1
Components: 2.34.9
```

**Comment by medikoo** [comment]
@marcelalburg Can you show complete content of `serverless.yml`? You've shown just `provider` section excerpt, that doesn't allow to reproduce issue on our side

**Comment by marcelalburg** [comment]
Hello, 

i was preparing the serverless.yml for you and tried to reproduce the error and it's working now (i didn't change anything or updated packages). I guess there was maybe a small issue at AWS side. 

Thanks a lot for your time
Marcel
