### ISSUE TITLE
v0.5 when updating an authorizer authorizerCredentials is not patched

### ISSUE THREAD

**Issue by michaelorionmcmanus** [serverless/serverless#817]
If an authorizer is created without specifying the `authorizerCredentials` property the property cannot be specified during an update because `EndpointDeployApiGateway._updateAuthorizer` does not look for the `authorizerCredentials` property in the endpoint's `authorizer` property.

**Comment by flomotlik** [comment]
Thank you, we are looking into changing how we deal with resource setup, so this should be less of an issue going forward. i've put this into our bug queue
