### ISSUE TITLE
SNS schema validation fails with string : wrong Fn::Sub definition

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8173]
Since #8112 , when using `sns.arn` with a string, the schema validation fails.
This is due to the fact that :
- this property is required to be either a string starting with `arn:` or any CF function - exclusively
- CF function `Fn::Sub` schema specify it can be a string (this is the problem)
- both schema are matched when using any string starting with `arn:`, thus resulting in a schema violation

<details>
<summary><code>serverless.ts</code></summary>

```ts
import type AWS from 'serverless/aws';

const serverlessConfiguration: AWS.Serverless = {
  service: {
    name: 'tmp',
  },
  configValidationMode: 'error',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true
    }
  },
  plugins: ['serverless-webpack'],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
  },
  functions: {
    hello: {
      handler: 'handler.hello',
      events: [
        {
          sns: {
            arn: 'arn:123'
          }
        }
      ]
    }
  }
}

module.exports = serverlessConfiguration;
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
  Serverless Error ---------------------------------------

  Configuration error at 'functions.hello.events[0].sns.arn': unsupported configuration format

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.0
     Framework Version:         1.80.0
     Plugin Version:            3.8.1
     SDK Version:               2.3.1
     Components Version:        2.34.9
```

</details>

<b>Installed version</b>

```
Framework Core: 1.80.0
Plugin: 3.8.1
SDK: 2.3.1
Components: 2.34.9
```

**Comment by fredericbarthelet** [comment]
@medikoo this issue might extends to some other definition.
It is very important to make sure `oneOf` keywork for JSON Schema validation is used where we explicitly want something to be one **XOR** the other
All other occurrences of `oneOf` should be replaced with `anyOf` keywork. WDYT ? Separate issue for this, I counted 18 occurrences worth a deeper look within the framework

**Comment by medikoo** [comment]
> All other occurrences of oneOf should be replaced with anyOf keyword. WDYT?

I'm not sure if we have any other constraint where multiple instances of `oneOf` can happen. I'm aware of this constraint and making sure weather it's safe, there are also places where we take advantage of that.

Do you see any vulnerable parts, which definitely should be updated?
