### ISSUE TITLE
Allow to compile AWS CloudFormation templates minified

### ISSUE THREAD

**Issue by jormaechea** [serverless/serverless#8179]
### Use case description

AWS CloudFormation templates have a hard limit of 460,800 bytes ([Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)). So size is a limited resource. Meantime, the templates are being pretty printed, wasting almost a 20% of that space in some cases.

### Proposed solution

Make a either the default behavior to write the templates without pretty formatting (maybe not backwards compatible?) or make a setting to disable it.

This setting (or new default) should apply here: https://github.com/serverless/serverless/blob/e120fd55d0d27fb55c8c0902c38a0d8d68cdf929/lib/plugins/aws/package/lib/saveCompiledTemplate.js#L16-L19

And pass a new parameter all the way down to:
https://github.com/serverless/serverless/blob/e120fd55d0d27fb55c8c0902c38a0d8d68cdf929/lib/utils/fs/writeFileSync.js#L8-L19

I can make a PR for this, but wanted to hear your opinion on whether this should be a default behavior or a configurable one.

**Comment by medikoo** [comment]
@jormaechea thanks for proposal. Did you approach this limit?

**Comment by jormaechea** [comment]
@medikoo we passed this limit some time ago (we're using APIs with non-proxy lambda integrations, so request templates use a bunch of chars).

We implemented a plugin to split stacks, but I think that we can improve our deployment times by reducing the amount of nested stacks, which we can achieve reducing their size.

I think that we can delay some time the nested stacks need for the community by reducing the templates sizes.

**Comment by medikoo** [comment]
> @medikoo we passed this limit some time ago

Have you passed this limit before reaching `200` resources in a stack? As maximum resources limit is a limit that users usually approach, and which can be worked around with split stacks plugin

**Comment by jormaechea** [comment]
Not our case, but you could easily do that I guess. When using lambda integration, you must define request template (default until yesterday was 2 request templates: json and form-urlencoded). And you must define a response template for each status code you need to implement. With all that we have each HTTP method using ~20K. If you have 23 HTTP methods, you reach the 460K limit.

With the fix from #7008, we reduced the size a bit by removing one request template we weren't using, but according to my tests (running `wc -c [file]` on a template, and then `cat [file] | jq -c . | wc -c`) I found that compressing the JSON without fancy indentation saves us about 20% of the size.

I have some other approaches to reduce template size, but I found this to be the easiest one and less risky by far.

**Comment by medikoo** [comment]
@jormaechea thanks for clarifications. Still if I read correctly we haven't yet approached the case, where introducing new behaviour will fix the issue for anyone.

At this point it's just an assumption, that it may fix an issue in some rare case scenario when someone will approach this limit before approaching maximum resources limit

As this project is already very heavy and we deal with significant technical debt, we prefer to not add features that are just _"nice to have"_ and doesn't address any real existing problem or use case.

**Comment by jormaechea** [comment]
@medikoo sorry for the delay. I will fix the issue for me :rofl: 

As this is an issue that didn't change any feature, it's just about formatting I thought it would be nice.
As a side effect, templates should be uploaded faster since they will be reduced in size by ~20%.

If this is not being accepted right now I could go with a plugin approach, but I think it's overkill.

**Comment by medikoo** [comment]
@jormaechea Let's wait for more votes. We will be totally open to accept once it appears as an issue for some users.

Otherwise we prefer to not add features of which real value is not confirmed, purely to avoid extra maintenance cost that comes with it.

**Comment by mrbrianevans** [comment]
This issue is affecting our deploys. We have hit the limit on template size, and there is plenty of wasted space in the compiled JSON template. 
```
✖ Stack data-api-brian failed to deploy (564s)
Environment: linux, node 18.13.0, framework 3.26.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: AppSyncResolverNestedStack (AWS::CloudFormation::Stack)
Template may not exceed 1000000 bytes in size.
```

I'm willing to contribute a fix (with a little bit of guidance) if it will be accepted.

**Comment by medikoo** [comment]
@mrbrianevans I think we can welcome this feature but behind the flag. Having templates well formatted is actually desired as many developers when approaching unexpected issue inspect the generated stack,
