### ISSUE TITLE
HttpApi Gateway Detailed Metrics

### ISSUE THREAD

**Issue by funkel1989** [serverless/serverless#8190]
### Use case description
I would like the ability to either enable or extend the HttpApiStage RouteSettings to turn on DetailedMetrics to enable the tracking of metrics for HttpApi gateway in the same way that was enabled by default for the Rest Gateway

### Proposed solution

Add a flag to the Providers.httpApi.metrics = true or allow extending the RouteSettings of the HttpApiStage at deploy time.

**Comment by medikoo** [comment]
@funkel1989 we're definitely open for a PR. Can you specify how the configuration will look on CloudFormation level?
