### ISSUE TITLE
 ENOENT: no such file or directory node_modules

### ISSUE THREAD

**Issue by whitecolor** [serverless/serverless#8193]
If folder with serverless project doesn't contain `node_modules` folder it gives an error.

![image](https://user-images.githubusercontent.com/736697/92326564-777c7200-f06c-11ea-8427-0f5e630d1272.png)

To get rid just need to create empty `node_modules` folder.

<b>Installed version</b>

```
Framework Core: 1.82.0
Plugin: 3.8.3
SDK: 2.3.1
Components: 2.34.9
```

**Comment by medikoo** [comment]
@whitecolor please respect all bug template remarks. Also it looks as if you're relying on plugins. Note that bug reports as posted here should describe cases where no plugins are used in service. All plugin related issues should be reported at its repositories.

**Comment by whitecolor** [comment]
Hah right, I even created the issue in the plugins repo, but forgot about this. https://github.com/prisma-labs/serverless-plugin-typescript/issues/210
