### ISSUE TITLE
Support `Condition` attribute on resources

### ISSUE THREAD

**Issue by glb** [serverless/serverless#8208]
### Use case description

#8139 introduced a schema for AWS Resources. It didn't include the `Condition` resource attribute.

Similarly, #7352 introduced `resources.extensions` without support for the `Condition` attribute.

[reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)

### Proposed solution

Extend the schema for resources and update `mergeCustomProviderResources.js` to support extending framework-created resources to set the `Condition` property.

https://github.com/serverless/serverless/blob/d9b91e97fb81b6f19c9f95920b509d623bdca37d/lib/plugins/aws/package/lib/mergeCustomProviderResources.js#L37

**Comment by medikoo** [comment]
@glb great thanks for pointing that. Indeed we missed that, as we were relying on https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html which doesn't mention `Condition`.

It's a pity there's no good source of information which would list all possible top level _resources_ properties.`Condition` seems to be documented on its own here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html

Anyway PR with a fix is welcome!
