### ISSUE TITLE
better type checking of command line args

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#823]
Not paying attention fully, I typed this command:
```
sls function deploy -s dev -region us-east-1
```

Which resulted in the following output:
```
Serverless: Deploying all functions in: some/path...
Serverless: Deploying functions in "dev" to the following regions: true
Serverless: ------------------------
Serverless: Failed to deploy the following functions in "dev" to the following regions:
Serverless: true ------------------------
Serverless:   some/function1: region.split is not a function
Serverless:   some/function2: region.split is not a function
```

After debugging some of the serverless code, I realized I was using the `-region` argument instead of `-r`. This somehow ended up passing a value of `true` for the aws region within `node_modules/aws-sdk/lib/region_config.js`. It really threw me for a loop...

**Comment by HyperBrain** [comment]
I will add the same check to the other deployment related actions if the fix is agreed upon

**Comment by franz-josef-kaiser** [comment]
153899f LGTM

**Comment by flomotlik** [comment]
We're currently rethinking stage/region in V1 and validation will be a part of that. Closing this issue therefore
