### ISSUE TITLE
Provisioned concurrency is not working with SQS lambda event

### ISSUE THREAD

**Issue by grozdz** [serverless/serverless#8249]
Hello,

There is an issue while deploying Lambda function with provisionedConcurrency enabled which uses SQS as event source. The error message is following:
```
An error occurred: LambdaEventSourceMappingSQSqueue - Invalid request provided: Function does not exist (Service: Lambda, Status Code: 400, Request ID: 2774b672-c894-4a5a-b478-79d2230ad64e, Extended Request ID: null).
```
It seems that SLS is not injecting DependsOn for Event Source Mapping into CFN template which expects alias to be present while creating this event source mapping (here template generated):
```
"LambdaEventSourceMappingSQSqueue": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": [],
      "Properties": {
        "BatchSize": 10,
        "EventSourceArn": "arn:aws:sqs:XXXXX:XXXXXXXXXX:lambda",
        "FunctionName": {
          "Fn::Join": [
            ":",
            [
              {
                "Fn::GetAtt": [
                  "LambdaLambdaFunction",
                  "Arn"
                ]
              },
              "provisioned"
            ]
          ]
        },
        "Enabled": true
      }
    },
```
If I deploy Lambda with events section commented but with provisionedConcurrency enabled, and after that I uncomment events section and redeploy - it works fine. So my conclusion is, that there is missing dependency for _provisioned_ alias that is expected for CFN. The error message _Function does not exist_ is confusing, but it apparently means that alias _provisioned_ is not yet created. I think that might be related to this: https://github.com/serverless/serverless/pull/8059. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
lambda:
  name: lambda
  handler: handler.execute
  role: arn:aws:iam::XXXXXXXXXXX:role/lambda
  provisionedConcurrency: 2
  events:
    - sqs: arn:aws:sqs:XXXXXXX:XXXXXXXXXXX:queue
```

</details>

<details>
<summary><b><code>serverless deploy --stage dev --config serverless.yml --conceal</code> output</b></summary>

```
Serverless Error ---------------------------------------
 
  An error occurred: LambdaEventSourceMappingSQSqueue - Invalid request provided: Function does not exist (Service: Lambda, Status Code: 400, Request ID: 2774b672-c894-4a5a-b478-79d2230ad64e, Extended Request ID: null).
 
```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.0 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```

**Comment by medikoo** [comment]
@grozdz great thanks for openning that. Indeed it's likely that alias needs to be added, in same manner as it's done here: https://github.com/serverless/serverless/blob/e136d8bfd4d299a4faa31cf33dd804d3cc1096bc/lib/plugins/aws/package/compile/events/alb/lib/permissions.js#L32-L35

PR with a fix is welcome!

**Comment by radove** [comment]
We had issues where Provisioned Concurrency would not get setup for an API Gateway.  We had to roll back to an older version to get our Provisioned Concurrency to work again via serverless.  I don't have too much time or expertise at the moment to track down the bug like @medikoo did, but wanted to report this.

**Comment by medikoo** [comment]
@radove if you have a scenario where provisioned concurrency setup worked with older Framework version, and it's not working with latest version, if possible please open new bug report with all the details

AFAIK This report describes case where provisioned concurrency never worked (when it was introduced, it didn't come with necessary changes to SQS event)

**Comment by pgrzesik** [comment]
I'm happy to pick this one up :100:
