### ISSUE TITLE
iamRoleStatements no longer work per function

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#8254]
Using v2.0.0.

When placed under provider, the permissions appear in the deployed IAM role.

When placed under the function, they do not.

This used to work.

**Comment by medikoo** [comment]
@cyberfox1 please respect bug template remarks and answer all questions carefully

**Comment by jack1902** [comment]
@cyberfox1 isn't this related to https://www.serverless.com/plugins/serverless-iam-roles-per-function which is a plugin specific issue

**Comment by cyberfox1** [comment]
@jack1902 i have no idea, is a plugin required for this to work? serverless did not complain about having iamRolePerStatement at the function level, so I assumed it was supposed to work.

**Comment by medikoo** [comment]
@cyberfox1 please use use https://forum.serverless.com/ or https://www.serverless.com/slack

This issue tracker is purely for bug reports and feature request (and all of such requests should be posted with respect to all template remarks)
