### ISSUE TITLE
Subfolders are ignored when deploying functions

### ISSUE THREAD

**Issue by plbrault** [serverless/serverless#826]
Let's say that I have a component containing two subfolders. Each subfolder contains functions like "create", "read", "update" and "delete", e.g.:

* restApi
    * users
        * create
        * read
        * update
        * delete
    * posts
        * create
        * read
        * update
        * delete

The [doc](http://docs.serverless.com/docs/application-architectures) suggests that this kind of architecture is valid. However, when deploying, it seems that a single "create" function will be created and both users and posts endpoints will use it. Same, obviously, for "read", "update" and "delete" functions. 

EDIT:
I just found out that this issue had already been reported by #710. I understand that you suggest using the customName parameter as a workaround. However, I still believe it would be better to include subfolder names in the generated lambda names, as forcing the user to provide a custom name could be a source of errors, e.g. inconsistent function names, forgetting to update the custom name when changing the name/location of the function or when copy-pasting from another function, etc.

**Comment by ac360** [comment]
Thanks for your input @plbrault.  We're trying to keep names fairly simple now.  Lambda has strict character limits and this ultimately caused more problems.
