### ISSUE TITLE
configuration validation: Ref / Fn::Joins

### ISSUE THREAD

**Issue by markvp** [serverless/serverless#8287]
Configuration validation is complaining about a Ref in provider.vpc.securityGroupIds (warning: "should be a string") and an Fn::Join in a function environment variable definition (warning: "unsupported configuration format").

Both of these function just fine - it's just that the validator warns about them unnecessarily.

**Comment by medikoo** [comment]
Duplicate of https://github.com/serverless/serverless/issues/8282
