### ISSUE TITLE
Type definitions for serverless are not upto-date and causing typescript project fail (need type definitions for msk)

### ISSUE THREAD

**Issue by gurbaj5124871** [serverless/serverless#8288]
When serverless project is created by `sls create --template aws-nodejs-typescript`, the type definitions from `@types/serverless` are incompatible with the `serverless version 2.3.0`. 

<details>
<summary><code>serverless.yml</code></summary>

```typescript
const serverlessConfiguration: Serverless = {
  service: {
    name: 'test-serverless',
    // app and org for use with dashboard.serverless.com
    // app: your-app-name,
    // org: your-org-name,
  },
  frameworkVersion: '2',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true
    }
  },
  // Add the serverless-webpack plugin
  plugins: ['serverless-webpack'],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    apiGateway: {
      minimumCompressionSize: 1024,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
  },
  functions: {
    hello: {
      handler: 'handler.hello',
      events: [
        {
          http: {
            method: 'get',
            path: 'hello',
          }
        }
      ]
    }
  }
}
```

</details>

<details>
<summary><b><code>sls create --template aws-nodejs-typescript</code> output</b></summary>

```
Serverless: Generating boilerplate...
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v2.3.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-nodejs-typescript"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name
```

</details>

<b>Installed version</b>

```
Framework Core: 2.3.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.5
```
![Screenshot 2020-09-25 at 4 37 32 PM](https://user-images.githubusercontent.com/25197675/94260270-7c3a9480-ff4d-11ea-83f8-f5a440dc960f.png)

![Screenshot 2020-09-25 at 4 37 15 PM](https://user-images.githubusercontent.com/25197675/94260253-75138680-ff4d-11ea-9366-1b4a8269f4e2.png)

**Comment by medikoo** [comment]
@gurbaj5124871 thanks for report. Still in context of this project we do not maintain any TypeScript definitions (afaik it's done in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/index.d.ts purely as external community effort).

Note that config schema is validated internally with help of JSON schemas, and schema for `msk` event is defined here: https://github.com/serverless/serverless/blob/2eebf5194aabda0f8eabc68b16902d5e7f9d298e/lib/plugins/aws/package/compile/events/msk/index.js#L14-L43

**Comment by gurbaj5124871** [comment]
@medikoo Thanks for clarifying the issue. I can open the issue there and might get pr opened for the support of msk. This definition schema helps.

**Comment by medikoo** [comment]
Thanks @gurbaj5124871! I'm going to close this issue here then
