### ISSUE TITLE
API Gateway Custom Authorizer Returns Unauthorized

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#829]
This may seem obvious, but make sure you are testing with a Header.  Specifically, the header you put in  your authorizer config `identitySource` attribute.  Otherwise, "Unauthorized" will always be returned, and your Custom Authorizer Lambda Function will never be called

**Comment by ajagnanan** [comment]
Also, if calling with JS, it might error out saying its because of CORS. This isn't the case, look at the response headers that Cloudfront returns to see the actual error. It'll be something like this:

`x-amzn-ErrorType:AuthorizerConfigurationException`

**Comment by ac360** [comment]
:+1: Thanks @ajagnanan

**Comment by cspeer** [comment]
Hi,

I'm fairly new to all this, so chances are I might be at fault here.
So I'm getting exactly the error message @ajagnanan posted. But I'm not really sure why or what is exactly happening. All I can say that my custom authorizer is never being called.

This is my authorizer:
```json
{
  "name": "secure",
  "runtime": "nodejs4.3",
  "description": "Serverless Lambda function for project: Atameo",
  "customName": false,
  "customRole": false,
  "handler": "secure/handler.handler",
  "timeout": 60,
  "memorySize": 1024,
  "authorizer": {
    "type": "TOKEN",
    "identitySource": "method.request.header.Authorization",
    "authorizerResultTtlInSeconds": "0"
  },
  "custom": {
    "excludePatterns": []
  },
  "endpoints": [],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "${project}",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```
and here is a function that references/uses it:
```json
{
  "name": "Traveller",
  "runtime": "nodejs4.3",
  "description": "Serverless Lambda function for project: Atameo",
  "customName": false,
  "customRole": false,
  "handler": "Traveller/handler.handler",
  "timeout": 6,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": []
  },
  "endpoints": [
    {
      "path": "Traveller",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "CUSTOM",
      "authorizerFunction": "secure",
      "apiKeyRequired": false,
      "requestParameters": {},
            "requestTemplates": {
        "application/json": ""
      },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {
            "application/json;charset=UTF-8": "Empty"
          },
          "responseTemplates": {
            "application/json;charset=UTF-8": ""
          }
        }
      }
    }
  ],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "${project}",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```
On API Gateway the config looks like this: 
![screen shot 2016-06-20 at 00 17 31](https://cloud.githubusercontent.com/assets/326824/16180130/6ef091d8-367c-11e6-957e-a262bc6c1010.png)

If you could take a look and maybe help, that would be terrific. Thanks a lot!


Cheers,
Chris

**Comment by cspeer** [comment]
Only now discovered #797, however I'm not sure how this is supposed to help with this.

**Comment by cspeer** [comment]
Apparently I have to connect the custom authorizer manually like this:
![okeh](https://cloud.githubusercontent.com/assets/326824/16189875/cce100d8-36dc-11e6-92a3-46306d9fefd2.png)

When I then run a test with AWS I get the following very strange response:
```
Execution log for request test-request
Mon Jun 20 09:48:06 UTC 2016 : Starting authorizer: tezqx6 for request: test-request
Mon Jun 20 09:48:06 UTC 2016 : Incoming identity: test-token
Mon Jun 20 09:48:06 UTC 2016 : Endpoint request URI: https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:556353107954:function:Atameo-secure/invocations
Mon Jun 20 09:48:06 UTC 2016 : Endpoint request headers: {x-amzn-lambda-integration-tag=test-request, Authorization=************************************************************************************************************************************************************************************************************************************************************************************************************************ecef61, X-Amz-Date=20160620T094806Z, x-amzn-apigateway-api-id=70pu9jdux8, X-Amz-Source-Arn=arn:aws:execute-api:us-east-1:556353107954:70pu9jdux8/authorizers/tezqx6, Accept=application/json, User-Agent=AmazonAPIGateway_70pu9jdux8, Host=lambda.us-east-1.amazonaws.com, X-Amz-Content-Sha256=83c93379f9f1c269b1694e57cd3215e1738b90c1688d9e85360614dc79838a26, Content-Type=application/json}
Mon Jun 20 09:48:06 UTC 2016 : Endpoint request body after transformations: {"type":"TOKEN","authorizationToken":"test-token","methodArn":"arn:aws:execute-api:us-east-1:556353107954:70pu9jdux8/null/GET/"}
Mon Jun 20 09:48:06 UTC 2016 : Authorizer result body before parsing: {"message":"lets auth"}
Mon Jun 20 09:48:06 UTC 2016 : Execution failed due to configuration error: Invalid JSON in response: {"message":"lets auth"}
Mon Jun 20 09:48:06 UTC 2016 : AuthorizerConfigurationException
```

**Comment by cspeer** [comment]
@ac360 Would you mind taking a look?

**Comment by avish-3pg** [comment]
@cspeer were you able to solve the problem you had faced. If yes, can you please share your setup or s-function.json, as I am facing an issue with it. Thank you.

**Comment by sajeetharan** [comment]
@cspeer  same here! please provide the solution if you have solved it

**Comment by YarekTyshchenko** [comment]
One year on... please @cspeer share a solution if you found it

**Comment by cspeer** [comment]
Sorry guys, I'm sure I solved it because I remember having a working endpoint in the end, but  I absolutely can't remember how. I left the serverless realm a while ago and am now back with monolithic architectures. This was configuration hell. Sorry!

**Comment by shailu2006** [comment]
I was facing a similar issue. The problem for me was that trying to fetch the token using "event.headers.Authorization" instead of "event.authorizationToken". After struggling and searching for sometime I came across the [test-invoke-authorizer](https://docs.aws.amazon.com/cli/latest/reference/apigateway/test-invoke-authorizer.html). 

It is my opinion that, the **test-invoke-authorizer** is the best way to test the authorizer lambda.The syntax for trying this as follows. 
"aws apigateway test-invoke-authorizer --rest-api-id <rest-api-key>--authorizer-id <authorizer-id> --headers Authorization='Value'". Any errors will directly show up on the console were you are running the command.

**<rest-api-key>**: The key of the API Gateway where your authorizer is created. 
**<authorizer-id>**: The ID of the authorizer you want to test.

**Comment by binarymist** [comment]
I got this to work with Cognito User Pool via curl using the access token, but strangly the test functionality of the Authorizer in the API Gateway console fails with unauthorized.
