### ISSUE TITLE
sls deploy prompts for Path[0] in VS Code

### ISSUE THREAD

**Issue by itsamia** [serverless/serverless#8293]
![Capture](https://user-images.githubusercontent.com/45797601/94403137-6b289800-0186-11eb-911b-da8d5b078813.PNG)

 I created a serverless project and it prompts for a path while 'sls deploy'.  

<details>
<summary><code>serverless.yml</code></summary>

```yaml

```

</details>

<details>
<summary><b><code>cmdlet Select-String at command pipeline position 1
Supply values for the following parameters:
Path[0]:
Select-String : Cannot bind argument to parameter 'Path' because it is an empty array.
At line:1 char:1
+ sls deploy
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Select-String], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyArrayNotAllowed,Microsoft.PowerShell.Commands.SelectStringCommand</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Framework Core: 2.3.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.5</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by medikoo** [comment]
@itsamia please respect all bug template remarks and provide answers for all questions.

**Comment by cbp123** [comment]
`sls` conflicts with the alias for the Powershell Select-String command.

You can use `serverless deploy` instead.

**Comment by nageshbk** [comment]
thanks

**Comment by anujChauhan-7838** [comment]
using serverless deploy command , it gives the error like 

serverless : The term 'serverless' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ serverless deploy
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (serverless:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pgrzesik** [comment]
@anujChauhan-7838 are you sure you have `serverless` installed? Your report suggests that the command is not recognized so it's either not installed or your shell does not recognize it

**Comment by ant7575** [comment]
If you are trying on windows try the below command
"serverless deploy" instead of "sls deploy"

**Comment by medikoo** [comment]
Closing. Source of an issue is that `sls` alias cannot work in Windows powershell, and users have to use `serverless`

**Comment by anirudhVasistha** [comment]
> using serverless deploy command , it gives the error like
> 
> serverless : The term 'serverless' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> 
> * serverless deploy
> * ```
>     + CategoryInfo          : ObjectNotFound: (serverless:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

You can use -> Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted     for reference see ->https://stackoverflow.com/questions/41117421/ps1-cannot-be-loaded-because-running-scripts-is-disabled-on-this-system

**Comment by rai-n** [comment]
> > using serverless deploy command , it gives the error like
> > serverless : The term 'serverless' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> > 
> > * serverless deploy
> > * ```
> >     + CategoryInfo          : ObjectNotFound: (serverless:String) [], CommandNotFoundException
> >     + FullyQualifiedErrorId : CommandNotFoundException
> >   ```
> 
> You can use -> Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted for reference see ->https://stackoverflow.com/questions/41117421/ps1-cannot-be-loaded-because-running-scripts-is-disabled-on-this-system

Thanks

**Comment by toskypd** [comment]
Use git bash for this.
