### ISSUE TITLE
Cleanup invalid variable examples from doc

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8306]
As reported here https://github.com/serverless/serverless/pull/8279#issuecomment-701323291 we have some invalid variable examples in doc as `${self:}` and `${env:}`.

I've learned they're not _invalid_ still they're controversial, and use case feels dubious. I would definitely not market them, simply to not confuse. So let's remove them from documentation.

**Comment by dsuarezlogans** [comment]
Hello good day, can I help with this issue?

**Comment by medikoo** [comment]
@dsuarezlogans Hello, certainly, that'll be very welcome!

**Comment by dsuarezlogans** [comment]
@medikoo for me to be clear on what is required, I need to remove the `${self:}` and `${env:}` parts of the variables in documentation for each provider right? like in [here](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/variables.md)

**Comment by medikoo** [comment]
I've learned today,that this notation is actually valid, still it's controversial, and I would still not use it in examples.

So yes, it's about removing it from docs, but it should not be removed if it's the place where this specific notation is documented (I think we don't have such place, but I write this just in case)

**Comment by duytrandev** [comment]
Hi @medikoo just want to check if this is still open and valid? I might be able to help

**Comment by medikoo** [comment]
@duytrandev Yes I believe it's valid. PR's welcome!
