### ISSUE TITLE
Workaround "Rate exceeded" errors in custom resources

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8333]
### Use case description

[Custom resources](https://github.com/serverless/serverless/tree/5851bcadcf6016914013d447de899cc98efb8346/lib/plugins/aws/customResources/resources) use plain AWS SDK calls, without any intelligent error handling.

Single "Rate exceeded" error, may fail whole stack upload (as we can observe in this CI fail: https://github.com/serverless/serverless/runs/1198178909)

It'll be great imply retry logic on such recoverable errors

### Proposed solution

We probably should add `awsRequest` util (like one here [@serverless/test/aws-request](https://github.com/serverless/test/blob/7dfc92e1d0d93c91f1c9affc872afa41fcb1c89b/aws-request.js)), with implemented recovery logic, to [utils.js](https://github.com/serverless/serverless/blob/5851bcadcf6016914013d447de899cc98efb8346/lib/plugins/aws/customResources/resources/utils.js) and rely on this in all places where we invoke AWS SDK

**Comment by pratik-vii** [comment]
@medikoo I can pick up this task!

**Comment by medikoo** [comment]
Thank you @pratik-vii ! Go for it

**Comment by pratik-vii** [comment]
@medikoo Let's close this issue. Sorry I forgot to add `closes` tag in PR.

**Comment by medikoo** [comment]
@pratik-vii closing, thanks for pointing!
