### ISSUE TITLE
Support for different Lambda awsRequestId generation strategies

### ISSUE THREAD

**Issue by pags** [serverless/serverless#8340]
As far as I can tell, locally invoked Lambda functions will always have a static value "id" for `context.awsRequestId`. In AWS, this value is not static, and is useful for identifying duplicate invocations that can occur in some scenarios (e.g. "at-least-once" invocation sources)

A common pattern is to surround a function with a gate that checks for a never-before-seen `context.awsRequestId` before proceeding with execution. Obviously this will not work well with local invocation due to behavior outlined above.

It would be great if the value of `context.awsRequestId` were configurable on a per-service and per-function basis Off the top of my head, I can think of a few potential options:

1. Current behavior (static `id` value)
2. Specify arbitrary custom value
3. Specify that value should be randomized to a likely-unique value (uuid or similar)

**Comment by medikoo** [comment]
@pags thanks for proposal.

I'm definitely after randomizing (with respect to format as used by AWS). I'm not sure if there's a value in allowing to customize by user. If it's a _nice to have_, I would not consider this at this point, if we have a strong real world use case, let's outline an implementation proposal.

**Comment by pags** [comment]
Sure, those were just suggestions. For my immediate use case, having this value randomized (or not) is what's important.

**Comment by medikoo** [comment]
@pags ok, so at this point, let's just randomize it and ensure same format as it's on AWS side (I guess it's UUID). 

PR is welcome!
