### ISSUE TITLE
AWS HTTP API: Documentation Contains Incorrect Payload Version Number

### ISSUE THREAD

**Issue by trevorrobertsjr** [serverless/serverless#8345]
[Documentation](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/httpapi-access/log-events/m11lww2md8_.default-2020-10-05-14-09) specifies that Payload version 1.0 is the default. That is not the case. If there is no payload parameter specified globally, the deployed HTTP APIs will be set to use Payload version 2.0.

This is a documentation problem only.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by medikoo** [comment]
@trevorallred Framework defaults Payload to version 2.0, and indeed we have an error in docs: https://www.serverless.com/framework/docs/providers/aws/events/http-api/

This should state that default is `2.0` and that i can be downgraded to `1.0` if needed. PR with a patch is welcome!
