### ISSUE TITLE
When PROFILE environment variable is missing, null is set in cloudformation

### ISSUE THREAD

**Issue by franciszabala** [serverless/serverless#8357]
Currently trying to deploy a serverless app using this command inside Codebuild.

```
serverless deploy --aws-profile $AWS_ACCESS_PROFILE --stage $STAGE --region $REGION --config serverless.yml
```

This is the output:

```
Error: The CloudFormation template is invalid: [/Resources/RegisterUnderscoretokenLambdaFunction/Type/Environment/Variables/PROFILE] 'null' values are not allowed in templates
```

It was working before except with this warning:

```
Serverless: DOTENV: Could not find .env file.
Serverless Warning --------------------------------------
 A valid environment variable to satisfy the declaration 'env:PROFILE' could not be found.

```

<b> Serverless version is 2.5.0 (2020-10-07) </b>
Please note that I could perform serverless --version as everything is running inside Codebuild and the devs would be get annoyed if I change something in the pipe,

Installed in Codebuild using

```
npm install -g serverless && npm install -g mocha && npm install
```

To fix this issue, we had to add a blank PROFILE and solved this issue. It might break some deployment.

**Comment by medikoo** [comment]
@franciszabala thanks for report. Still can you please respect all template remarks and answer all its questions. Provided information is not good enough for me answer what could go wrong

**Comment by medikoo** [comment]
@franciszabala it's not possible for me to handle issue if necessary details are not provided. Please close if you're not able to provide any extra information

**Comment by franciszabala** [comment]
Closing issue.

**To fix build issue, please make sure that PROFILE environment variable is declared. It doesn't have to contain a value.**
