### ISSUE TITLE
Configure all promise returning functions as async functions

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8368]
### Use case description

Paves path to https://github.com/serverless/serverless/issues/7171

Ideally we should use just native promises and async/await syntax. Still refactor of whole code seems as too big and problematic task for single PR, it's better to divide it into smaller clear tasks.

As a first distinct step I believe it'll simply be good to configure all promise returning functions as _async_ functions (**with no adjustments to its bodies**, the internal promise flow should remain configured as-is)

### Proposed solution

Search for all functions which return an outcome of any `BbPromise*` (bluebird), `Promise*` or `x.then()` operation, and (1) confirm weather it's justified that function returns promise. if there are no _async_ calls (with exception to fs _sync_ variants which we should refactor in next step to _async_) (2a) Reconfigure function so it doesn't return promises. If it's otherwise (2b) add `async` keyword in front of `function` keyword (that's all, do not adjust function body content)

To avoid making this PR too problematic to review, __nothing more should be covered in PR__.

It's likely this PR will already expose some issues, as Framework has logic parts where promise returning functions are in some scenarios treated as _sync_ and in other as _async_. All handling like that should be fixed with this PR.

As project covers a lot of files, let's split this work into multiple PR's each covering following areas:

- [x] Files put directly into `lib` and `lib/classes`
- [x] `lib/plugins/aws/customResources` (https://github.com/serverless/serverless/pull/8698)
- [x] `lib/plugins/aws/deploy` (https://github.com/serverless/serverless/pull/8698)
- [x] Files put directly into `lib/plugins/aws` (https://github.com/serverless/serverless/pull/8871)
- [x] `lib/plugins/aws/info` (https://github.com/serverless/serverless/pull/8875)
- [x] `lib/plugins/aws/invokeLocal` (https://github.com/serverless/serverless/pull/8876)
- [x] `/lib/plugins/aws/lib` (https://github.com/serverless/serverless/pull/8872)
- [x] `lib/plugins/aws/package/compile/events/alb`, `lib/plugins/aws/package/compile/events/lib`, `lib/plugins/aws/package/compile/events/s3` and files put directly into `lib/plugins/aws/package/compile/events` (https://github.com/serverless/serverless/pull/8873)
- [x] `lib/plugins/aws/package/compile/events/websockets` (https://github.com/serverless/serverless/pull/8874)
- [x] `lib/plugins/aws/package/compile/events/apiGateway` (https://github.com/serverless/serverless/pull/8869)
- [x] Files put directly into `lib/plugins/aws/package/compile` (https://github.com/serverless/serverless/pull/8870)
- [x] `lib/plugins/aws/package/lib` and files put directly into `lib/plugins/aws/package` (https://github.com/serverless/serverless/pull/8870)
- [x] `lib/plugins/aws/remove`
- [x] `lib/plugins/aws/utils`
- [x] Files put directly into `lib/plugins` (https://github.com/serverless/serverless/pull/8875)
- [x] `lib/plugins/create` (https://github.com/serverless/serverless/pull/9683)
- [x] `lib/plugins/interactiveCli` _(was addressed with extensive feature refactor)_
- [x] `lib/plugins/package` (https://github.com/serverless/serverless/pull/9644)
- [x] `lib/plugins/plugin`
- [x] `lib/utils` (https://github.com/serverless/serverless/pull/9809)
- [x] `scripts`
- [x] `test/integration`
- [x] Files put directly into following folders:`test`, `test/unit/lib`, `test/unit/lib/plugins`
- [x] `test/unit/lib/classes`
- [x] `test/unit/lib/plugins/aws/common`
- [x] `test/unit/lib/plugins/aws/deploy`
- [x] Files put directly into `test/unit/lib/plugins/aws`, `test/unit/lib/plugins/aws/package`, `test/unit/lib/plugins/aws/package/compile`
- [x] `test/unit/lib/plugins/aws/info`
- [x] `test/unit/lib/plugins/aws/lib` and `test/unit/lib/plugins/aws/invokeLocal`
- [x] `test/unit/lib/plugins/aws/package/compile/events/s3`, `test/unit/lib/plugins/aws/package/compile/events/alb` and `test/unit/lib/plugins/aws/package/compile/events/lib`
- [x] `/test/unit/lib/plugins/aws/package/compile/events/apiGateway`
- [x] Files put directly into `test/unit/lib/plugins/aws/package/compile/events`
- [x] `test/unit/lib/plugins/aws/package/compile/events/websockets`
- [x] Files put directly into `test/unit/lib/plugins/aws/package/compile`
- [x] `test/unit/lib/plugins/aws/package/lib` and files put directly into `test/unit/lib/plugins/aws/package`
- [x] `test/unit/lib/plugins/aws/remove`
- [x] `test/unit/lib/plugins/aws/utils`
- [x]  `test/unit/lib/plugins/create` and files put directly into `test/unit/lib/plugins`
- [x] `test/unit/lib/plugins/interactiveCli`
- [x] `test/unit/lib/plugins/package`
- [x] `test/unit/lib/plugins/plugin`
- [x] `test/unit/lib/utils`
- [x] `test/utils`

**Comment by JeremyScott-IO** [comment]
Hey,
I'd like to take this on! 

Just to make sure I understand, don't modify the functions, aside from changing the method to async. However if after changing these I find problems where calling functions can't handle the now async method, I should fix these calling functions in this same PR?

**Comment by medikoo** [comment]
@JeremyScott-IO that'll be great go for it! And yes your understanding is perfectly correct

**Comment by Maxgit3** [comment]
If you need any more help, I would be willing to chip in.

**Comment by JeremyScott-IO** [comment]
Hi @medikoo,

I've noticed a lot of methods that return promises aren't async, and some ()=> module.exports are also returning Promises. Should I be converting methods and these module.exports to async as well?

**Comment by medikoo** [comment]
>  I've noticed a lot of methods that return promises aren't async, and some ()=> module.exports are also returning Promises. Should I be converting methods and these module.exports to async as well?

Ideally functions/methods which do not involve any _async_ operations (but e.g. simply return `BbPromise.resolve(..)`) should be configured as _sync_ (so have `return BbPromise.resolve(x)` replaced with `return x` and `return BbPromise.reject(e)` replaced with with `throw e`). Still you may approach situations that making them _sync_ breaks things in a way that more sophisticated refactor is needed, keep such cases _async_ to not overcomplicate this PR (let's add `async` keyword and `TODO` comment explaining future intent of having them _sync_)

**Comment by medikoo** [comment]
@JeremyScott-IO if it appears as too large task for one PR, we may splt it. so e.g. with one PR we cover only designated folders. Let me know, I'll be more than happy to outline such roadmap if needed. Then more of us can help covering it.

Great thanks again, for looking into it!

**Comment by JeremyScott-IO** [comment]
@medikoo, I'm going to have a fair amount of time across the course of this week. I can give it a go, but I'm totally fine if you guys want to split it out and allow other contributors :)

Let me know!

**Comment by medikoo** [comment]
@JeremyScott-IO Let's see how it goes then :) If it'll appear challenging we'll propose to seclude some areas to other PR's

**Comment by KishorBudhathoki10** [comment]
Hello Everyone. I am new to working with open source projects. I want to contribute to this project and this issue seems the right place for me to get started. I have questions regarding the folder structure. Should I also make an update inside the plugins folder? I have refactored some code inside ./lib/plugins/aws/invokeLocal/index.js to use async/await which I have attached below. Should I push it for check? Also which are the main folders that should be refactored? 

[index.js.zip](https://github.com/serverless/serverless/files/5401333/index.js.zip)

Thank you in Advance.

**Comment by medikoo** [comment]
@KishorBudhathoki10 great thanks for reaching out to help! Still this one is already being covered by @JeremyScott-IO (note the assignment). Please search other issues with _good first issue_ label (which have no one assigned), and see if you can help with those (?)

Concerning code attachments, please use compare links (e.g. you may create a branch in your fork and send us link to its compare view). Sharing _zip_ archives doesn't feel safe

**Comment by Edu93Jer** [comment]
Hi guys, I am new at open source and would like to contribute to the project, this issue looks find to get started, but please guys could you please let me know how is it going? I saw @JeremyScott-IO has started, but any update, can I help with something, how should I start working on it, please could you explain to me a little more @medikoo ...

**Comment by medikoo** [comment]
@Edu93Jer it appears it got stuck, and it's not surprising as this covers quite a lot.

To make it easier I've split the work into multiple areas. Please see updated description. With that approach we should be able to move it effectively forward.

PR's welcome!

**Comment by ifitzsimmons** [comment]
@Edu93Jer which part of this issue did you tackle. I have some time over the next few days and was going to clean some of this up but I don't want to step on any toes.

**Comment by Edu93Jer** [comment]
Hi @ifitzsimmons I took `lib` and `lib/clases` go ahaed and take another files, actually I made a mistake on my PR, you can check it, for not to do the same hehehe, I will correct my PR, but go ahead with the other files if you want.
Cheers, and a Happy New Year!

**Comment by jkklapp** [comment]
@medikoo added one PR for `lib/plugins/aws/remove` folder #9284

**Comment by MelanieGehrke** [comment]
Hey,
I´d like to work on it. Can I work on lib/plugins/create? I think this is file not done by now.

**Comment by medikoo** [comment]
@MelanieGehrke that'll be great! We look forward the PR

**Comment by MelanieGehrke** [comment]
@medikoo perfect! Thank you.

**Comment by MelanieGehrke** [comment]
@medikoo added the PR for lib/plugins/create in folder #9390

**Comment by nyamba** [comment]
Hello there, can I work on one of theme? and please tell me which one?

**Comment by pgrzesik** [comment]
Hello @nyamba - totally, we'd be happy to accept PRs for that. The list in the issue should be up-to-date - you can pick one from the list that you like and work on it :+1:

**Comment by nyamba** [comment]
Thanks @pgrzesik, I'm going to work on `lib/plugins/interactiveCli` in #9642

**Comment by nyamba** [comment]
@pgrzesik it looks that there is no functions which is returning a promise  in `lib/plugins/interactiveCli`. Please correct me If I'm wrong :-)

**Comment by pgrzesik** [comment]
@nyamba Yes, looks like it's the case indeed - we had some extensive refactoring implemented recently for that module so it might've changed with that. I'm going to cross it out from the list

**Comment by matheus-fongaro** [comment]
Hello, I'm also new to open source development, is this issue still active? Can I still work on it?

**Comment by medikoo** [comment]
@matheus-fongaro definitely! please pick folder from the list. PR's welcome!

**Comment by mdanyalkhan** [comment]
Hello! Currently very interested in understanding the whole Serverless eco-system. I've taken the liberty to address one of the tasks in this issue (specifically on `lib/plugins/aws/utils`) as a first if that's okay?

**Comment by medikoo** [comment]
@mdanyalkhan that's great, thank you!

**Comment by Iamhashim92** [comment]
Hi, I am new to Open source. I see there are lots of files still left for refractoring. Can i start working on those?

**Comment by medikoo** [comment]
@Iamhashim92 yes, that's very welcome!

**Comment by sleepwithcoffee** [comment]
can cross out `test/unit/lib/plugins/interactiveCli` since there is no async tests under it

**Comment by medikoo** [comment]
Thank you @sleepwithcoffee for finalizing that, Outstanding work 👏 🎉
