### ISSUE TITLE
CF stack name randomized on project init

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#838]
When you do a `project init`, specify a name and stage for the project, the initially created CF stack is named with a randomized part, instead of the project name.
In my tests I named the project `testp1` and this is the created stack:
![image](https://cloud.githubusercontent.com/assets/5524702/13898925/9c501eca-ede1-11e5-89bf-76d36109059d.png)

**Comment by neaghfoz** [comment]
When create a new project using ```sls project create```, the name which entered at the prompt also not pass to ```s-variables-common.json```, still the default random characters name in that file.

**Comment by HyperBrain** [comment]
Analyzed and found the reason:
ProjectInit checks if a project already exists in the directory.
If not, it creates an instance of the `Project` class.
Next it is checked if the project instance already has a name (implicitly it is assumed that any new project instance does not have a name set):
```
          // If no project exists, set it
          if( !S.hasProject() ) {
            S.updateConfig({
              projectPath: path.resolve(path.join(path.dirname('.'), _this.evt.options.name))
            });
            S.setProject(new S.classes.Project());
          }

          // Fill in project attributes
          _this.project          = S.getProject();
          _this.project.name     = _this.project.name ? _this.project.name : _this.evt.options.name;
```
But instead of fulfilling the assumption, the project class sets a random name itself, so `ProjectInit` assumes that this is set from the outside and does not actually set the one from the interactive session.
```
      // Default properties
      this.name      = 'serverless' + S.utils.generateShortId(6);
```

**Comment by HyperBrain** [comment]
Now the CF stack is created as expected:
![image](https://cloud.githubusercontent.com/assets/5524702/13904893/3b98d35e-eeb0-11e5-91de-ce3370319ba0.png)

**Comment by ac360** [comment]
Thanks @HyperBrain :)
