### ISSUE TITLE
Typescript definition from JSON schema definitions for serverless service file

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8386]
### Use case description

Today, Typescript definition of serverless service file properties are maintained within [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/serverless) as part of a community effort.
Those definition, being mostly right, are sometimes outdated. In addition, some recently added fields are missing.
For exemple :
- `provider.httpApi.cors` property is defined as boolean only, no definition for the object form containing `allowedOrigins`, `allowedMethods` and `allowedHeaders` propeties
- no support for AWS intrinsic functions were properties are enforced a `string` type (what we defined as `awsCfInstruction` in JSON schema)

Typescript Serverless user rely both on those definition to get instant feedback from IDE as they write their `serverless.ts` file, as well as recently implemented JSON schema definition, for which validation occurs at runtime of any serverless command. They might get conflictual information from both those sources.

It would be so great to have Typescript definition actually generated from the Serverless code base (unfortunately, this is only the case for typescript written projects).

### Proposed solution

Automating typescript definition generation from JSON schema existing in Serverless code base.
Outputing definitions within Serverless framework codebase rather than relying on DefinitelyTyped definitions.

It can be done programmatically using librairies like [json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript) or statically using librairies like [
json-schema-to-ts](https://github.com/ThomasAribart/json-schema-to-ts).

I actually use it a lot on my serverless projects, where I defined JSON schema for api gateway validation, that I statically infer into typescript types to type my event in my lambda's handler.

While this issue focus on Typescript definitions, similar types could be generated for other language, in order to keep Serverless as much language-agnostic as possible and give types for all available runtime typed-languages.

**Comment by medikoo** [comment]
@fredericbarthelet great thanks for opening that.

I think it makes a big sense to auto generate TS definition out of configured schema, still one culprit is, that it probably be quite hard to make it equivalent, e.g. in current schema handling we apply following normalization rules:
- Automatic coercion per [AJV rules](https://ajv.js.org/coercion.html)
- Automatic coercion to array, when primitive is passed, and what's expected is an array of primitives (also other way around)
- We allow explicit `null` and `undefined` at any property (even those not defined) - those properties are hidden from AJV for a moment of schema validation

It's likely that generated TS definition won't match what we accept as valid in Serverless Framework, and I'm afraid of receiving an issue reports that try to battle that, To avoid drain of our core resources, we would prefer that this effort is taken exclusively in community land.

_Note: that just adding support for `serverless.ts` file, triggered issue reports in many cases purely related to TypeScript language, we don't want to have this effect bigger in context of this repository_

Ideally, would be if we would open a dedicated repository for TS definitions, that would autogenerate them out of latest Framework version. We could even host it in context of [serverless](https://github.com/serverless/) organization, still with maintenance purely in context of a community (I'll be more than happy to assign you with any needed rights). Having that we may direct all users with TS related problems to this repository

**Comment by fredericbarthelet** [comment]
thank you for your reply @medikoo 

I fully understand your concern regarding strict segregation of issues related to the framework itself and issues related to the typescript definitions.

It would be a great idea to start a dedicated serverless organization repository for the purpose of hosting those definitions. Would love to start it if you can set it up.

I'll need to address the following:
- typescript developers are used to the `@types/...` namespace for types dependancies. Meaning that for every JS library, you usually proceed with `npm install serverless && npm install @types/serverless`. However `@types/serverless` currently points to DefinetlyTyped repository. Will have to look into that.
- serverless/serverless pipeline to compute and generate latest definitions without the normalization rules. Would be great to have an event sourced system triggering a computation on this new repo side rather than having it included within the main repo pipeline.

I will update this issue with my findings. Feedbacks are welcome on the above points :)

**Comment by medikoo** [comment]
@fredericbarthelet what name do you think would be good for this new repo. Do you think `serverless/typescript` will work well?

**Comment by fredericbarthelet** [comment]
@medikoo Ok for `serverless/typescript` :)

**Comment by fredericbarthelet** [comment]
@medikoo , I currently have the following plan to trigger definition build at release:

## If release webhook can be used from repo to repo within the organization
- subscribe a new GitHub action in `serverless/typescript` repository to trigger on `release` event `published` action from `serverless/serverless` repository

## If release webhook is not scoped to the whole GitHub organization
- update `scripts/pkg/upload/world.js` in order to POST to the new `serverless/typescript` repository `repository-dispatch-event` endpoint with event `released` and payload containing release tag and/or commit id (https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) - TOKEN to be created accordingly to be able to access this endpoint
- subscribe a new GitHub action in `serverless/typescript` repository to trigger on `repository_dispatch ` event `released` action from `serverless/typescript` repository

I'll proceed with some testing on my GitHub organization to check wether preferred solution #1 is feasible. I'll update you on that matter.

**Comment by medikoo** [comment]
@fredericbarthelet sorry for delayed response. I've just created [serverless/typescript](https://github.com/serverless/typescript/) and provided you with admin rights. Let me know if there's anything else you may need.

Great thanks for taking care of that, I'm sure a lot of contributors will be very thankful for having properly managed TS definitions!

**Comment by fredericbarthelet** [comment]
@medikoo invitation accepted, thanks :) !

**Comment by fredericbarthelet** [comment]
@medikoo first definitions generated for version 2.11 of the framework. Definitions generation process automated with Github Actions.
Remaining work include :
- posting to `dispatch_repository` endpoint of https://github.com/serverless/typescript in the release pipeline of this repository - will open the PR
- publishing a new NPM package `@serverless/typescript` to host the definitions. Could you help me on that matter ? Or would you have me host those definition under my NPM account ?

**Comment by medikoo** [comment]
> first definitions generated for version 2.11 of the framework.

@fredericbarthelet great to hear that!

> publishing a new NPM package @serverless/typescript to host the definitions. Could you help me on that matter ?

Definitely! I believe we need to publish first version in scope of our organizaion, and having first version published we would be able to give you the rights to publish all following versions. Therefore:
- Can you point me what would make a good first release (I'll just publish it)
- Let me know your npm nick name. After publishing it I'll ensure you have all necessary rights to publish all future versions

**Comment by fredericbarthelet** [comment]
Thanks for helping out @medikoo :)
- You can publish [tag v2.11.1](https://github.com/serverless/typescript/releases/tag/v2.11.1) - i'll follow serverless/serverless versioning
- My NPM nickname is fredericb - I'll then use my NPM token in github action workflow to automate publishing

**Comment by medikoo** [comment]
@fredericbarthelet I've just published v2.11.1 -> https://www.npmjs.com/package/@serverless/typescript

I've also invited you to our npm org. Once you accept the invitation I will ensure you have necessary rights to publish following versions

**Comment by fredericbarthelet** [comment]
@medikoo thanks for the invitation. I do see the serverless organization on my NPM home page. However, I cannot see any package in the organization page. And I tried to publish v2.12.0 of the @serverless/typescript package, without success. Are you sure my NPM user is allowed to publish for this package ?

**Comment by medikoo** [comment]
@fredericbarthelet I've just ensured you have write access to `@serverless/typescript`. I believe it should be working know. Let me know

**Comment by fredericbarthelet** [comment]
@medikoo confirmed :) ! It's now working as expected, thanks 🚀 !

**Comment by medikoo** [comment]
In light of that, I'm going to close this issue, as I believe concern was addressed.

@fredericbarthelet if you have any other concerns, questions, let me know, and great thanks for all your effort on that!

**Comment by fredericbarthelet** [comment]
@medikoo, 2 things are remaining in this issue I believe :

- the updated version of the aws-nodejs-typescript with the new definition repository
- the automated trigger for the repo release - coming soon

**Comment by medikoo** [comment]
@fredericbarthelet thanks for info. I will review the PR shortly, and concerning the second part can we open a corresponding issue in `@serverless/typescript` repository? Ideally if we handle all TypeScript related traffic over there.

**Comment by fredericbarthelet** [comment]
Sure thing, will do from now on :) Thanks @medikoo
