### ISSUE TITLE
V0.5 - Slash (/) path separator is not handled correctly in Windows environments

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#839]
When i try to create function with folder with this command `serverless function create abc/xyz`

then command is prompting create endpoint,create event,just the function.. , but when i hit create endpoint i am getting following error

C:\Users\username\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Only letters, numbers, dashes and underscores are allowed in function names
    at new ServerlessError (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Error.js:17:11)
    at FunctionCreate._validateAndPrepare (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\actions\FunctionCreate.js:182:33)
From previous event:
    at FunctionCreate.functionCreate (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\actions\FunctionCreate.js:69:10)
From previous event:
    at C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:181:31
    at Array.reduce (native)
    at C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:180:32
From previous event:
    at Serverless._execute (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:424:20)
    at Serverless.command (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:393:38)
    at C:\Users\username\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by HyperBrain** [comment]
In Windows environments '\' has to be used as path separator character on the command line.
So specifying `sls function create abc\def` works as expected.

**Comment by nirmalgoswami** [comment]
it works with `serverless function create abc\def` but not with `serverless function create abc/def`

**Comment by HyperBrain** [comment]
Analyzed the problem. Currently the path is extracted from the function name argument by using the path NPM's `path.sep` variable, which is '/' on Unix systems and '\' on Windows systems.
So only the native path separator is honored and '/' will be passed on Windows systems as part of the function name. This of course will lead to an exception as '/' is not allowed as part of the function name.

See `FunctionCreate.js` line 166:
```
      if (_this.evt.options.path) {
        // extract function name from path regardless of how deep the path is
        _this.functionName = _.last(_this.evt.options.path.split(path.sep));
      } else {
```

**Comment by HyperBrain** [comment]
There is still a possible issue regarding path parsing on line 176:
```
          // the following line makes sure we include all subfolders if any
          _this.evt.options.path = process.cwd().replace( S.getProject().getRootPath() + '/','') + '/' + _this.functionName;
```
I will check the `Project.getRootPath` method about further platform dependent code.

**Comment by eahefnawy** [comment]
Yeah we weren't sure if we should follow the convention of each OS, or just stick to one. I was favoring to just stick to forward slash in this particular case because I don't really think what we're passing is the "function path" per say, but rather our own syntax for identifying functions and their locations. This should make it easier to communicate commands in the docs (otherwise we'd have to mention both Unix and Windows version). Not sure which direction to go from here, what u guys think?

**Comment by HyperBrain** [comment]
IMHO as long as the function path is mapped to a physical folder structure on disk, the behavior should be OS agnostic and so support '/' on Unix and '/' or '\' on Windows systems, which is handled by the path module pretty well out of the box (of course using the methods .join, .parse and not hard-coded path.sep or '/' characters.

**Comment by jjercx** [comment]
Is this really closed? because I tried to name a function `abc/def` and it was having a webpack error, which disappeared as I renamed it to `abd#def`

I'm using webpack with typescript, using serverless typescript template (`sls create --template aws-nodejs-typescript`)
