### ISSUE TITLE
Allow pseudo parameter AWS::AccountId in cfnRole config

### ISSUE THREAD

**Issue by FergusMcGlynn** [serverless/serverless#8395]
### Use case description

I would like to be able to specify a `cfnRole` that references an `AWS::AccountId`. The account Id is a common part of a role arn, and I'd like to be able to use this to deploy to different AWS accounts that have a role with the same name set up. I want to be able to specify a `cfnRole` like this:

```
  cfnRole: arn:aws:iam::--AWS-ACCOUNT-ID-HERE--:role/SomeRole
```

I have tried to use pseudo parameters as described in the [documentation](https://www.serverless.com/framework/docs/providers/aws/guide/variables#pseudo-parameters-reference):

```
  cfnRole:
    Fn::Join:
      - ':'
      - - 'arn:aws:iam:'
        - Ref: 'AWS::AccountId'
        - 'role/SomeRole'
```

But on `serverless deploy` I get the error `Expected params.RoleARN to be a string`. This looks to be similar to [this issue](https://github.com/serverless/serverless/issues/5173).

I have also tried using [serverless-pseudo-parameters](https://github.com/svdgraaf/serverless-pseudo-parameters):

```
  cfnRole: 'arn:aws:iam::#{AWS::AccountId}:role/SomeRole'
```

But that fails to substitute `#{AWS::AccountId}` with the account id. I have opened [an issue about that](https://github.com/svdgraaf/serverless-pseudo-parameters/issues/75) in the Serverless Pseudo Parameters github repo, but I see that the plugin is [now marked as deprecated](https://github.com/svdgraaf/serverless-pseudo-parameters) because this functionality should be handled natively in Serverless as of v2.3.0. 

### Proposed solution

Allow reference to AWS pseudo variables in `cfnRole` configuration. For example:

```
  cfnRole: 'arn:aws:iam::${aws::AccountId}:role/SomeRole'
```

**Comment by medikoo** [comment]
@FergusMcGlynn thanks for report.

`cfnRole` is used to deploy a stack, and it's provided in `createStack` or `updateStack` params, and those are not part of CloudFormation template, hence any CF intrnsic functions of pseudo parameters simply do not apply there.

CF intrinsic functions and AWS pseudo params are supported only in settings which are passed through as-is to CloudFormation template, and it's not the case with `cfnRole`

**Comment by zachwhaley** [comment]
@FergusMcGlynn Did you find a workaround for this?  We did by using the new `file` function to call a JS script that just calls sts to get the current account ID, but I was wondering if there is a Serverless native way to do this.

I found this PR which makes it seem like pseudo params are supported #9103

**Comment by medikoo** [comment]
>  I was wondering if there is a Serverless native way to do this.

It will be soon: https://github.com/serverless/serverless/issues/9005

**Comment by FergusMcGlynn** [comment]
@zachwhaley The workaround that I used was to incorporate an environment variable holding the `AWS_ACCOUNT_ID` and include that in the `cfnRole` value:
```
cfnRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/SomeRole
```
Therefore I need to ensure that I've set that environment variable whenever I deploy. 

(As an aside, for local development I have defined this environment var in my `.bashrc` file so that I don't have to remember to set it, and for production this environment var is set in the CI/CD pipeline)

@medikoo - that sounds promising!

**Comment by faucherb94** [comment]
A workaround I figured out is, add to the `custom` block:
```yaml
custom:
  ExecRole: !Sub arn:aws:iam::${AWS::AccountId}:role/SomeRole
```

then reference this in the function-level settings:
```yaml
functions:
  MyFunc:
    role: ${self:custom.ExecRole}
```

This raises `unsupported configuration format` warnings during packaging, but it _does_ substitute correctly in the CF template output. Hopefully #9005 will be added soon so this won't have to be used for long.

**Comment by medikoo** [comment]
> This raises unsupported configuration format warnings during packaging

If this format is valid for given property, then it's a bug on a Framework side that it shows such warning. Can you open an issue describing this problem?

Note that from a new major it'll be a crash and not a warning

**Comment by faucherb94** [comment]
Submitted: https://github.com/serverless/serverless/issues/9199
