### ISSUE TITLE
Error when deploying without `--config` flag

### ISSUE THREAD

**Issue by foxxor** [serverless/serverless#8401]
I'm getting the error reported here: https://github.com/serverless/serverless/issues/7736

```
Got 2 config paths: [, ].Expected single value
```

But I get it, if the `--config file.yml` flag is not passed with the `serverless deploy` command:

I'm getting this only when deploying from a Docker instance in my CI, with the latest version of the Framework **2.7.0** , executing this full command:

```
serverless deploy --region $AWS_DEFAULT_REGION --aws-profile $CREDENTIALS_PROFILE_NAME --stage $SERVERLESS_STAGE --verbose --conceal
```

Passing the `--config serverless.yml` additional flag fixes the issue, although this flag is not mandatory and the error is missleading as I didn't pass any config when I got the error.

<b>Installed version</b>

```
Serverless Framework version:
Framework Core: 2.7.0
Plugin: 4.1.0
SDK: 2.3.2
Components: 3.2.1
```

**Comment by medikoo** [comment]
@foxxor it looks as some issue in your docker CI setup. I cannot reproduce anything like that locally. You can try to debug it by inspecting `process.argv` in Serverless process. As this error comes from parsing CLI params (read from `process.argv`)

**Comment by foxxor** [comment]
@medikoo Thanks for the fast response, I originally fixed the issue by providing the `--config` flag, but I tried deploying to other stage and it's failing with this error.

```
  Serverless Error ---------------------------------------
 
  Got 3 config paths: [serverless.yml, , ].Expected single value
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.1
     Framework Version:         2.8.0
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.3
```

I'm not sure if this is the exact info you request, but I modified the `node_modules/.bin/serverless` file to print the args I'm passing to it, and this was the info I got:

```
[
  '/usr/local/bin/node',
  '/var/jenkins_home/workspace/..../node_modules/.bin/serverless',
  'deploy',
  '--region',
  'eu-west-1',
  '--aws-profile',
  'accProfile',
  '--stage',
  'acc',
  '--config',
  'serverless.yml',
  '--verbose',
  '-conceal'
]
```

Please let me know if I can get you more info.

**Comment by foxxor** [comment]
I just realized the problem was with the flags/arguments I am passing after the `--config` flag, by switching the arguments from:

`node_modules/.bin/serverless deploy --region $AWS_DEFAULT_REGION --aws-profile $CREDENTIALS_PROFILE_NAME --stage $SERVERLESS_STAGE --config serverless.yml --verbose -conceal`
To:
`node_modules/.bin/serverless deploy --region $AWS_DEFAULT_REGION --aws-profile $CREDENTIALS_PROFILE_NAME --stage $SERVERLESS_STAGE --verbose -conceal --config serverless.yml`

I don't get the error anymore.

Although that doesn't really explain why I got the error described originally if I don't pass the `--config` flag.

**Comment by medikoo** [comment]
@foxxor problem lies in `-conceal` part. It's treated as equivalent to `-c -o -n -c -e -a -l` and `-c` is an alias for `--config`. Lack of option passed to config results with `''` resolved for config, and hence final value for config option is `['serverless.yml', '', '']` (result of `--config serverless`, `-c` and `-c`)

I'm not sure exactly how it can work for you by reordering the params, it shouldn't really make a difference

**Comment by foxxor** [comment]
@medikoo I switched the `-conceal` to `--conceal` and switched the order of the flags and can confirm it's now working fine.

I think the issue was mainly because of that wrong conceal configuration that missed the double dashes `--`. Although I think there's some incorrect validation on Serverless side as the `--config` tried to parse the extra flags starting with dash as extra config arguments `--config serverless.yml --verbose -conceal`.

**Comment by medikoo** [comment]
@foxxor on args parsing side it follows [yargs-parser](https://github.com/yargs/yargs-parser#yargs-parser) internal rules.

I agree the design could be better and we may eventually upgrade to other one assuming we agree that it improves resolution (any proposal are welcome)

**Comment by foxxor** [comment]
@medikoo You guys know more than me on this regard. At the moment there's nothing else to add from me.

Since it was mostly an error in our configuration, I think we can close this issue.

Thanks for the support 👍 !
