### ISSUE TITLE
V0.5 - Can not add vpc support in project

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#842]
my code

`s-function.json` file

```
"vpc": {
    "securityGroupIds": ["sg-123"],
    "subnetIds": ["subnet-123","subnet-456","subnet-789"]
  }
```

`s-resources-cf.json` file 

```
"IamPolicyLambda": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "${stage}-${project}-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:${region}:*:*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface"
              ],
              "Resource": "*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambda"
          }
        ]
      }
    }
```

i have read this [info](https://github.com/serverless/serverless/issues/629#issuecomment-184472421) before trying this...

but i got following error during deployment of project

`Your access has been denied by EC2, please make sure your function execution role have permission to CreateNetworkInterface. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.`

**Comment by nirmalgoswami** [comment]
after debugging i have found that  execution role must have permissions to create ENIs `AWSLambdaVPCAccessExecutionRole` but i need to do this manually in managed policies of roles by using aws console to solve my issue,how can we add `AWSLambdaVPCAccessExecutionRole` using serverless code ?

**Comment by eahefnawy** [comment]
Yikes!! @nirmalgoswami have you tried adding it to the `s-resources-cf.json` file? I see you already have some policies there, maybe it's just missing another policy?

Generally speaking we can't really make assumptions on policies and permissions because they're different for each user. We have a similar issue in event source support. The user just need to know what kinda resources and permissions he'll need and update CF :)

**Comment by olegZastavnyi** [comment]
I am using serverless 1 beta. How can I manage this AWSLambdaVPCAccessExecutionRole  over yaml file ?

**Comment by pmuens** [comment]
Hey @olegZastavnyi you can add custom IAM role statements. Here's the documentation on how to do this:

https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-iam-role-statements
