### ISSUE TITLE
CloudFormation resource limit has been increased from 200 to 500

### ISSUE THREAD

**Issue by neverendingqs** [serverless/serverless#8430]
### Use case description

[CloudFormation resource limit has been increased from 200 to 500](https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/). The [warning in the display plugin](https://github.com/serverless/serverless/blob/2d6824cde531ba56758f441b39b5ab018702e866/lib/plugins/aws/info/display.js#L17-L22) can be updated.

### Proposed solution

Update the plugin to show an error only at 375+ resources instead of 150+ (remains at 75%) (e.g.: https://github.com/serverless/serverless/commit/b9af5dd205662bcd2c3eb9d23535edc38fdd0042). However, it is unclear how you want to coordinate with changes to the [linked blog post](http://bit.ly/2IiYB38). Should a new post be written ([existing one in `serverless/blog`](https://github.com/serverless/blog/blob/944cfaff09d18afc82d104a3dd066863dabe4ff3/posts/2018-03-07-serverless-workaround-cloudformation-200-resource-limit.md))?

**Comment by medikoo** [comment]
@neverendingqs great thanks for that. Your proposal looks very good. I wouldn't update blog post though, it's historical and that should be clear.

PR that updates the warning is very welcome!

**Comment by medikoo** [comment]
Closing as it was actually addressed by https://github.com/serverless/serverless/pull/8433
