### ISSUE TITLE
@serverless/template broken under Yarn 2 (berry)

### ISSUE THREAD

**Issue by brandonbloom** [serverless/serverless#8436]
I tried to send the @serverless/template repository a PR, but it is archived and I can't find where the package now lives.

The issue is due to an implicit dependency on rambda.

Here's the patch: https://github.com/brandonbloom/template/commit/80aad1aedc089acbc8ac18c65b6b8e54c09dc01b

**Comment by medikoo** [comment]
@brandonbloom thanks for reporting.

Indeed, there was actually a PR with a fix for that: https://github.com/serverless/template/pull/11 (cc @eahefnawy )

Anyway, I've just released v1.1.4 with this patch, so issue should be gone now
