### ISSUE TITLE
Use log retention settings for AWS custom resources log group

### ISSUE THREAD

**Issue by FilipPyrek** [serverless/serverless#8439]
### Use case description

When I was studying AWS custom resources in Serverless Framework, I've noticed that there is no log retention being set for the custom resources lambda functions. And when I took a look at AWS Console I could see there "Never expire" in the log retention field even though I've set the `logRetentionInDays: 30` in `serverless.yml`.

### Proposed solution

Here: https://github.com/FilipPyrek/serverless/commit/cd79dc96e0ea5620b2ff0e4c634da7c0d8684a49

[![Commit diff](https://user-images.githubusercontent.com/6282843/97105088-da77a600-16b8-11eb-83e6-febe076fd0eb.png)](https://github.com/FilipPyrek/serverless/commit/cd79dc96e0ea5620b2ff0e4c634da7c0d8684a49)

**Comment by medikoo** [comment]
@FilipPyrek good call! Please propose a PR with your change, we're definitely open to take it
