### ISSUE TITLE
v0.5 - Function boilerplate still includes custom.envVars

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#844]
When you create a new function with `sls function create <pathAndName>` the generated `s-function.json` still includes the `custom.envVars` array.
As environment variables in v0.5 are defined with the `environment` object, we would not need the custom entry anymore and it should be removed from the boilerplate.

**Comment by ac360** [comment]
Thanks @HyperBrain.  You've been a great help lately :)  Fixed in 383494941186aebe248689dfd8324c58b1bb6fe9
