### ISSUE TITLE
Refactor: Seclude "lib/utils/log.js" (general logging) util

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8444]
### Use case description

Currently base logging function is configured as `CLI` plugin instance method, which is part of `Serverless` instance.

That makes it hard to rely on it when we have no clear access to `Serverless` instance.

There's technically no reason why this part of logic should be configured as method of `Serverless` dependent instance.

Having it configured as standalone util, will allow to refactor other logic parts into standalone utils

### Proposed solution

Seclude implementation of `CLI#log` (specifically https://github.com/serverless/serverless/blob/2d6824cde531ba56758f441b39b5ab018702e866/lib/classes/CLI.js#L404-L416 into `lib/utils/log.js`), but improve it's signature to `message, options = {}` (and make `entity` as one of the `options`)

Instead of `this.consoleLog(message)` do ``process.stdout.write(`${message}\n`)``.

In  `lib/utils/log.test.js` configure few tests with help of [`process-utils/override-stderr-write`](https://github.com/medikoo/process-utils#override-stdout-write--override-stderr-write)

Convert `CLI#log` method to rely on newly created util, and from `#log` tests leave there just one sanity test that method remains working

**Comment by michiboo** [comment]
Hi! Can I try to have a go at this issue?

**Comment by medikoo** [comment]
@michiboo definitely! Please go for it!

**Comment by michiboo** [comment]
@medikoo I couldn't find the file log.test.js, should I create a new one?

**Comment by medikoo** [comment]
> @medikoo I couldn't find the file log.test.js, should I create a new one?

Yes, the `log` util doesn't exist same as test file for it. We should create both files

**Comment by michiboo** [comment]
@medikoo At the moment consoleLogSpy is used to assert there is message output to the console, but it can test on cli object. How can I test if there is message output if log is function?

**Comment by medikoo** [comment]
> How can I test if there is message output if log is function?

@michiboo In tests for new util you can use https://github.com/medikoo/process-utils#override-stdout-write--override-stderr-write to surpass logging and confirm on the output (I noted that in issue main description)

Or do you refer to test that remain in `CLI.test.js` ?

**Comment by pgrzesik** [comment]
Hello @michiboo, thanks a lot for your interest in handling this issue. Unfortunately, it is impacting another issue that we're working on internally, and the decision was made to refactor and move this utility into https://github.com/serverless/utils project. As it's currently blocking progress on another ticket, would you be okay with me taking over this refactoring? Sorry for any trouble caused and thank you for your contribution.

**Comment by michiboo** [comment]
@pgrzesik  Sure, thanks for help!

**Comment by pgrzesik** [comment]
Thank you for understanding @michiboo :bow:

**Comment by medikoo** [comment]
Closing as:
- We've introduced a generic (no strings attached) util in `@serverless/utils/log`
- We decided to not refactor existing code to rely on it, as same parts are scheduled for refactor (with  additional namespace and level tuning) after we have #1720 in)
