### ISSUE TITLE
Test: Refactor lib/plugins/aws/provider/awsProvider.test.js

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8446]
_Most of the tests that currently cover core functionalities depend heavily on (and sometimes test) internal implementation characteristics. While they should be testing whether given implementation produces desired outcome (treating its implementation more as  a black box)._

_Current state of things is problematic for eventual internal improvements and refactors which occasionally we want to introduce, as in most of such cases proposed improvements need to be accompanied with counterproductive numerous updates to tests which are covering otherwise not altered functionalities ._

_At some point we've introduced a new (black box based) way of testing the internals. It's through `runServerless` utlity, which allows us create natural (as in real world) `serverless` instance, and inspect the produced outcome for chosen command. More details here: https://github.com/serverless/serverless/tree/master/test#unit-tests_

--- 

This is issue is about refactoring [lib/plugins/aws/provider/awsProvider.test.js](https://github.com/serverless/serverless/blob/2d6824cde531ba56758f441b39b5ab018702e866/lib/plugins/aws/provider/awsProvider.test.js) to `runServerless` based variant.

It's needed, so we cleanly move forward with https://github.com/serverless/serverless/pull/8415

A preliminary step for this task is seclusion of `request` util, which is being handled here: https://github.com/serverless/serverless/issues/8445 This task should be addressed after that.

To make the task bearable, below I propose a  spec for a new version test file, with necessary details in comments.

If there are any more questions, doubts, I'll be happy to answer all of them. PR that brings the change is welcome!

```js
describe('AwsProvider', () => {
  // Cover following two tests with single `runServerless` run
  // `sls -v` command in context of AWS service ("aws" fixture)
  it('`AwsProvider.getProviderName()` should resolve provider name', () => {
    // Instance of awsProvider can be accessed via serverless.getProvider('aws');
  });
  it('should retain sessionToken eventually updated internally by SDK', () => {
    // For the purpose of this test "aws-sdk" should be mocked completely through `modulesCacheStub`
    // We need to configure fake AWS service which modifies input params
    // as here: https://github.com/serverless/serverless/blob/2d6824cde531ba56758f441b39b5ab018702e866/lib/plugins/aws/provider/awsProvider.test.js#L878
    // and then in test confirm that serverless.getProvider('aws').getCredentials(); returns affected object
  });

  describe('#getCredentials()', () => {
    // Each test to be covered with single `runServerless` run, unless indicated
    // - Home folder for test run is pointed to temporary directory therefore it's safe to create
    //   fake `~/.aws/credentials and confirm it's effective (note it needs to be cleared in afterEach)
    // - Configure `process.env` vars via "env" option and not via operating on `process.env` directly)
    //   https://github.com/serverless/test/blob/master/docs/run-serverless.md#env-optinal
    it('should get credentials from default AWS profile', () => {});

    it('should get credentials from custom default AWS profile, set by AWS_DEFAULT_PROFILE', () => {});

    it('should get credentials from `provider.credentials`', () => {});

    // Cover following two tests with single runServerless run
    it('should get credentials from `provider.profile`', () => {});
    it('should accept a role to assume on credentials', () => {});

    it('should get credentials from environment variables', () => {});

    // Cover following two tests with single runServerless run
    it('should get credentials from AWS_PROFILE environment variable', () => {});
    it('should get credentials from AWS_SHARED_CREDENTIALS_FILE environment variable', () => {});

    it('should get credentials from stage specific environment variables', () => {});

    it('should get credentials from AWS_{stage}_PROFILE environment variable', () => {});

    // Cover following two tests with single runServerless run
    it('should get credentials "--aws-profile" CLI option', () => {});
    it('should set the signatureVersion to v4 if the serverSideEncryption is aws:kms', () => {});

    it('should throw an error if a non-existent profile is set', () => {});
  });

  describe('#getRegion()', () => {
    // Each test to be covered with single `runServerless` run
    // `sls -v` command in context of AWS service ("aws" fixture)
    // Confirm result by inspecting serverless.getProvider('aws').getRegion()
    it('should default to "us-east-1"', () => {});
    it('should allow to override via `provider.region`', () => {});
    it('should allow to override via CLI `--region` param', () => {
      // Test with `provider.region` and `--region` CLI param set
      // Confirm that `--region` overrides
    });
  });

  describe('#getProfile()', () => {
    // Each test to be covered with single `runServerless` run
    // `sls -v` command in context of AWS service ("aws" fixture)
    // Confirm result by inspecting serverless.getProvider('aws').getProfle()
    it('should allow to set via `provider.profile`', () => {});
    it('should allow to set via CLI `--profile` param', () => {
      // Test with `provider.profile` and `--profile` CLI param set
      // Confirm that `--profile` overrides
    });
    it('should allow to set via CLI `--aws-profile` param', () => {
      // Test with `provider.profile` `--profile` and `--aws-pofile` CLI param set
      // Confirm that `--aws-profile` overrides
    });
  });

  describe('#getDeploymentPrefix()', () => {
    it('should put all artifacts in namespaced folder', () => {
      // Run "sls package" on regular "function" fixture
      // Confirm that all "S3Key" property values are prefixed with: "serverless/"
    });

    it('should support custom namespaced folder', () => {
      // Configure custom `provider.deploymentPrefix`
      // Run "sls package" on regular "function" fixture
      // Confirm that all "S3Key" property values are prefixed with custom prefix
    });
  });

  describe('#getAlbTargetGroupPrefix()', () => {
    // Configure this test in lib/plugins/aws/package/compile/events/alb/index.test.js
    it('should support `provider.alb.targetGroupPrefix`', () => {
      // Extend "function" fixture with alb event and custom provider.alb.targetGroupPrefix
      // Run "sls package"
      // Confrm on generated resources that prefix was used
    });
  });

  describe('#getStage()', () => {
    // Each test to be covered with single `runServerless` run
    // `sls -v` command in context of AWS service ("aws" fixture)
    // Confirm result by inspecting serverless.getProvider('aws').getStage()
    it('should default to "dev"', () => {});
    it('should allow to override via `provider.stage`', () => {});
    it('should allow to override via CLI `--stage` param', () => {
      // Test with `provider.stage` and `--stage` CLI param set
      // Confirm that `--stage` overrides
    });
  });
});
```

In addition to that, let's introduce a simple integration test, where we confirm that `provider.deploymentBucket.name` setting is effective, and that deployment happens to designated bucket. For that we may deploy simple empty service (an `aws` fixture). For more info on integration tests see: https://github.com/serverless/serverless/tree/master/test#aws-integration-tests

**Comment by AlinoeDoctari** [comment]
@medikoo looks like work for #8845 is done :slightly_smiling_face: Is it ok to get started on this issue now? If so is it possible to submit smaller PR than a full resolution? Like going on by one through the `describe` clauses?

**Comment by medikoo** [comment]
@AlinoeDoctari yes, it's definitely ready to take now, and it's totally fine to address one describe case per PR. Any PR that covers even smallest part of it, is very welcome. Great thanks for helping with that!

**Comment by AlinoeDoctari** [comment]
@medikoo I've had a look into the `getCredentials` part and I'm not sure how to cover multiple tests with only one runServerless. Is there any example out there where I can draw inspiration from? Thanks for your help :slightly_smiling_face: :bowing_man:

**Comment by medikoo** [comment]
> @medikoo I've had a look into the getCredentials part and I'm not sure how to cover multiple tests with only one runServerless.

@AlinoeDoctari I believe each of those tests have to be covered with different `runServerless` run. Probably my comment in snippet is not perfectly clear, but I'm pretty sure I meant _Each test to be covered with its own dedicated`runServerless` run, unless indicated differently_ :)

**Comment by AlinoeDoctari** [comment]
@medikoo Yes, this part is ok :) I was wondering more about 
``` 
// Cover following two tests with single runServerless run
    it('should get credentials "--aws-profile" CLI option', () => {});
    it('should set the signatureVersion to v4 if the serverSideEncryption is aws:kms', () => {});
```
Does that also means that each test should have one serverless run?

**Comment by medikoo** [comment]
> Does that also means that each test should have one serverless run?

I think in case of those two tests idea was to cover them with single `runServerless` run, as they test two different properties.

The way to do that is to wrap it with `describe` block. Ofc organization wise it's a bit confusing, as otherwise there's nothing special about those tests to be secluded in single group. I think we can title describe with something as `(cumulated run) #1`

**Comment by AlinoeDoctari** [comment]
Sounds good :+1: I'll try that out :)

**Comment by AlinoeDoctari** [comment]
@medikoo Thanks for the help so far :bow: I've started to have a look at the integration test in order to close that issue and I need a final push :slightly_smiling_face: . I have a couple question in order to move further:
- The current integration test use `deployService()` and as far as I can tell, it could be replaced by `runServerless()` in our case with the added benefit of the fixture management. Is it something I should go for or should I use the same structure as for the other integration tests?
- I've noticed there is already an `integrationBasic.test.js` does it make sense to integrate into it? Or should I create a new test file in `test/integration`?

**Comment by medikoo** [comment]
@AlinoeDoctari good questions, let me clarify

> The current integration test use deployService() and as far as I can tell, it could be replaced by runServerless() in our case with the added benefit of the fixture management. Is it something I should go for or should I use the same structure as for the other integration tests?

Integration tests benefit from very same fixtures, still we just use _fixtures engine_ directly, and then run `serverless` command in generated service folder, as here: 
https://github.com/serverless/serverless/blob/aa89357a0ba654af2312cc039ab92abb5c864d91/test/integration/s3.test.js#L24-L40

`runServerless` should not be used, as it just initializes `Serverless` instance in same process, it's not real e2e test then, and integration tests should test `serverless` CLI command in full capacity.

> I've noticed there is already an integrationBasic.test.js does it make sense to integrate into it? Or should I create a new test file in test/integration?

It's older test, which technically tests a setup of simple service via `sls create` deploying it, invoking a function and removing. So it tests very basic Framework usage flow, and not specific deployment case as _regular_ integration tests. I would probably keep it as it is.

For this case I'd probably create `test/integration/custom-deployment-bucket.test.js` test file
