### ISSUE TITLE
Add custom descriptions

### ISSUE THREAD

**Issue by ajagnanan** [serverless/serverless#845]
Can we add the ability to customize descriptions on functions and apis?

**Comment by HyperBrain** [comment]
First step:
Added `description` parameter to `s-function.json` which can be used to set the lambda description as follows (including variable references):
```
{
  "name": "testfct",
  "runtime": "nodejs",
  "description": "My test function for project ${project} deployed in stage ${stage}",
  "customName": false,
  "customRole": false,
  "handler": "handler.handler",
  "timeout": 6,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": [],
    "envVars": []
  },
  "endpoints": [
  ],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "testp1",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```
This will lead to the description shown in the AWS lambda console:
![image](https://cloud.githubusercontent.com/assets/5524702/13905377/24ddef2e-eebe-11e5-949f-63c103774d9d.png)

If the description is missing, the default description as before will be used:
_Serverless Lambda function for project ..._
