### ISSUE TITLE
Test: Refactor lib/plugins/aws/package/compile/events/eventBridge/index.test.js

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8455]
Most of the tests that currently cover core functionalities depend heavily on (and sometimes test) internal implementation characteristics. While they should be testing whether given implementation produces desired outcome (treating its implementation more as  a black box).

Current state of things is problematic for eventual internal improvements which occasionally we want to introduce, as in most of such cases proposed improvements need to be accompanied with counterproductive numerous updates to tests which are in many cases not related to improved functionality.

Additionally as it was proven already few times, such tests may hide existing issues and introduced refactor helped discovering and fixing existing bugs

At some point we've introduced a new way of testing the internals. It's through `runServerless` utlity, which allows us create natural (as in real world) `serverless` instance, and inspect it at desired points in time. More details here: https://github.com/serverless/serverless/tree/master/test#unit-tests

--- 

This is issue is about refactoring [lib/plugins/aws/package/compile/events/eventBridge/index.test.js](https://github.com/serverless/serverless/blob/b6ae44e4cd5b7fbf9bbb893fc8e088435dde6221/lib/plugins/aws/package/compile/events/eventBridge/index.test.js) to `runServerless` based variant.

It's needed, so we cleanly move forward with https://github.com/serverless/serverless/pull/8437

Technically we should remove tests written here: https://github.com/serverless/serverless/blob/b6ae44e4cd5b7fbf9bbb893fc8e088435dde6221/lib/plugins/aws/package/compile/events/eventBridge/index.test.js#L18-L1148 and ensure scope they cover is covered in already started `runServerless` group of tests here:
https://github.com/serverless/serverless/blob/b6ae44e4cd5b7fbf9bbb893fc8e088435dde6221/lib/plugins/aws/package/compile/events/eventBridge/index.test.js#L1150-L1208

Below is a spec I propose for test file to have after the refactor:

```js
describe('EventBridgeEvents', () => {
  before(() => {
    // Single run serverless run, with service that covers all tested cases
    // Let's extend function fixture
    // Example of similar approach: https://github.com/serverless/serverless/blob/80e70e7affd54418361c4d54bdef1561af6b8826/lib/plugins/aws/package/compile/events/alb/lib/healthCheck.test.js#L18-L127
  });

  // Exactly tests as we have here:
  // https://github.com/serverless/serverless/blob/b6ae44e4cd5b7fbf9bbb893fc8e088435dde6221/lib/plugins/aws/package/compile/events/eventBridge/index.test.js#L1189-L1206
  // Eventually we may extend them to cover few other core properties
  it('should create the correct execution role', () => {});
  it('should create the necessary resource', () => {});

  it('should register created and delete event bus permissions for non default event bus', () => {});

  it("should ensure rule name doesn't exceed 64 chars", () => {});

  it('should support input configuration', () => {});

  it('should support arn at eventBus', () => {});
  it('should support inputPath configuration', () => {});

  it('should support inputTransformer configuration', () => {});
});

```

**Comment by caiobessa** [comment]
Hey, @medikoo is it still relevant? I would like to work on it if is possible.

**Comment by medikoo** [comment]
@caiobessa yes it's definitely relevant. We look forward for the PR. Thank you!

**Comment by medikoo** [comment]
@caiobessa did yo have a chance to look into it? :) 

Currently this is blocking for https://github.com/serverless/serverless/pull/8437 So if for some reason you don't have resources to address it right now, it's totally fine, just let us know, so we can take over.

/cc @stuartforrest-infinity

**Comment by caiobessa** [comment]
@medikoo Hi, I will submit the PR today, It is missing just one test to be finished

**Comment by medikoo** [comment]
@caiobessa great to hear that. We look forward 👍

**Comment by caiobessa** [comment]
@medikoo @stuartforrest-infinity  The PR is in #8484 . Thanks a lot for wait.
