### ISSUE TITLE
Refactor: Clear "that = this" pattern from codebase

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8457]
### Use case description

`that = this` Resembles questionable and heavily outdated pattern.

It was used before we had arrow functions, to maintain access to `this` across nested function references, with arrow functions `this` is shared and cases can be referenced directly

### Proposed solution

Simply remove `const that = this` and replace all `that` references with `this` (mind eventual non-arrow function expressions which rely on top level `that` if there are any upgrade them to arrow functions)

**Comment by MatthewBerk** [comment]
Hello, I am new to contributing. I am not well versed in JavaScript, though I would like to help with this issue since it seems to be a simple find and replace. Could you guide me through this issue?

**Comment by medikoo** [comment]
@MatthewBerk it's simply about searching for `that = this` and clearing this out.

Anyway it was already perfectly addressed by @telenord you may check the PR
