### ISSUE TITLE
Deprecate an object notation of `service`

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8465]
### Use case description

Once we've deprecated `service.awsKmsKeyArn`, there seems no reason to support object notation for `service` property.
We do not intent adding support for any properties in it.

### Proposed solution

[Deprecate](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations) usage of object notation form at: https://github.com/serverless/serverless/blob/92b269024a7adc6e062129dd7a9f8df11f10fa03/lib/classes/Service.js#L133

**Comment by A-5ingh** [comment]
@medikoo I can pick it up, if you can guide a little on the proposed solution.

**Comment by medikoo** [comment]
@A-5ingh that'll be great! What exactly seems unclear?

**Comment by A-5ingh** [comment]
> @A-5ingh that'll be great! What exactly seems unclear?

What should be the deprecated code and message ? and the deprecated._logDescription should be called just before the if statement. I'm very new to serverless and open source contribution so the questions might be obvious.

**Comment by medikoo** [comment]
> What should be the deprecated code and message

I propose: `SERVICE_OBJECT_NOTATION` and _Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name._

> and the deprecated._logDescription should be called just before

We call deprecation when deprecated functionality is being used. In issue description I've linked code point where that happed

**Comment by A-5ingh** [comment]
@medikoo I have made the required changes for logging deprecated message. Please let me know if anything else is required.

**Comment by JacobvanP** [comment]
What about publish: #3950.
This still seems to be in use (lib/plugins/platforms.js)

**Comment by medikoo** [comment]
@JacobvanP this functionality was removed from the Framework a longer time ago. Note there's no [`lib/plugins/platforms.js`](https://github.com/serverless/serverless/blob/master/lib/plugins/platforms.js) plugin

**Comment by JacobvanP** [comment]
@medikoo Apologies, I seem to have looked at an older version. Thanks for the reply.
