### ISSUE TITLE
AWS alarms email format validation improperly flags email addresses with a plus symbol as invalid

### ISSUE THREAD

**Issue by mattccrampton** [serverless/serverless#847]
Plus symbols are valid characters in email addresses.  When running "serverless project create" and entering an email address with a plus symbol (+), an error of "error:   Please enter a valid email" is thrown.

![image](https://cloud.githubusercontent.com/assets/1310017/13907369/c00b5564-eea9-11e5-938d-70783eee413a.png)

Plus symbols are especially useful for gmail users: https://support.google.com/mail/answer/12096?hl=en

**Comment by ac360** [comment]
Thanks @mattccrampton  We've moved this email feature in `V0.5`, which we will be releasing on Monday.
