### ISSUE TITLE
Improve schema definition methods

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8481]
### Use case description

We allow to extend schemas with new properties via dedicated methods. Still currently they silently treat eventual overrides. e.g. one can override `functions[].events` property, which could be breaking for internals.

Ideally those methods should not allow overrides and crash whenever it is attempted. It'll also signal eventual collision between plugins if they try to define same properties

### Proposed solution

Ensure that an attempt to override an existing property crashes with meaningful error in:
- [`defineTopLevel` method](https://github.com/serverless/serverless/blob/2fffb168bc7f957ed9e8e048fd08dfb9669e8eca/lib/classes/ConfigSchemaHandler/index.js#L149-L151)
- [`addPropertiesToSchema` internal function](https://github.com/serverless/serverless/blob/2fffb168bc7f957ed9e8e048fd08dfb9669e8eca/lib/classes/ConfigSchemaHandler/index.js#L255-L261)
- [`defineFunctionEvent` method](https://github.com/serverless/serverless/blob/2fffb168bc7f957ed9e8e048fd08dfb9669e8eca/lib/classes/ConfigSchemaHandler/index.js#L204-L217) - Here ensure that event of same name is not already configured (we need to search for same event in an array)

**Comment by vinod-tahelyani** [comment]
@medikoo I'd like to take this

**Comment by medikoo** [comment]
@vinod-tahelyani thank you! Go for it
