### ISSUE TITLE
AWS S3 buckets created by Serverless do not deny listing over HTTP

### ISSUE THREAD

**Issue by gwynnarth** [serverless/serverless#8489]
Hello,

As a result of #5621, Serverless-created buckets include a bucket policy that is supposed to deny any `s3:*` Action over that bucket, unless it is performed over HTTPS.

Unfortunately that Bucket policy is incomplete and still allows listing the Bucket content over insecure HTTP connection, if the Principal has permissions to perform that action.

Incorrect (current) Bucket Policy:
```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::BUCKET_NAME/*",
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
}
```

Correct (proposed) bucket policy would look like that:
```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::BUCKET_NAME",
                "arn:aws:s3:::BUCKET_NAME/*",
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
}
```

In other words, what's missing is `"arn:aws:s3:::BUCKET_NAME"` in the `"Resource"` section.

The easiest way to verify the bug is to:
1. Temporarily assign public `List` permissions to a Serverless-created bucket (for example via ACL).
1. Observe that the bucket listing is accessible both via https://BUCKET_NAME.s3.amazonaws.com/ (expected) as well as http://BUCKET_NAME.s3.amazonaws.com/ (unexpected).
1. Modify the bucket policy as described above, to fix the issue, and re-test: this time listing over HTTP will return `AccessDenied`.
1. Don't forget to revoke public listing from the bucket afterwards ;-) 

PS. This misconfiguration is picked up and reported by this [Prowler](https://github.com/toniblyx/prowler ) check: https://github.com/toniblyx/prowler/blob/master/checks/check_extra764

<b>Installed version</b>

```
Framework Core: 2.8.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.4
```

**Comment by medikoo** [comment]
@gwynnarth great thanks for that report!

We're open for PR that patches that. Assuming that change is not breaking (will not break further deployments) we can just apply a change to policy. Otherwise it'll has to be introduced behind the option and deprecation notice (so we can make it default from next major)

**Comment by as19ish** [comment]
@medikoo Can i pick this one?

**Comment by medikoo** [comment]
@as19ish yes, definitely, go for it. Thank you!
