### ISSUE TITLE
CLI: Remove help --verbose option and improve general help output

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8497]
### Use case description

Currently `sls --help --verbose` simply outputs CLI commands grouped by plugins.

Where _plugins_ are also internal plugins, which resemble characteristcs of internal implementation which should not be interesting in anyway for regular users.

If read properly in an [issue](https://github.com/serverless/serverless/issues/3784) with which it was introduced, it seemed helpful for Framework contributors back then, when Framework was frequently extended with new command.

I doubt there's a value for it now (but ofc that's open for discussion).

I believe that all commands that come with Framework (and dashboard plugin) should be listed as they're listed now in regular help. While all commands as introduced by external plugins could be listed as they are when w use `--verbose` mode.

And that could all be covered under regular `--help`, making `--verbose` option obsolete

### Proposed solution

1. In `lib/classes/PluginManager.js` ensure that commands coming from external commands are recognizable:
  - Support `isExternal` option in [`pluginManager.addPlugin()`](https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/lib/classes/PluginManager.js#L93), and pass it through to `this.loadCommands()`
   - In [`pluginManager.loadCommands()`](https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/lib/classes/PluginManager.js#L262) support `isExternal` option, and ensure to mark all produced `command` with `isExternal: true` if that option was passed
   - In [`pluginManager.loadAllPlugins()`](https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/lib/classes/PluginManager.js#L127-L129) ensure to pass `isExternal: true` for all plugins resolved via `resolveServicePlugins()` method
1. In context of [cli.generateMainHelp()](https://github.com/serverless/serverless/blob/786809e262b56490a78a923b0b031378badb18c0/lib/classes/CLI.js#L184-L256) ensure to not list external plugin commands in main listing, but instead (if there are any external plugins) add _"Commands by plugin"_ section below _"Plugins"_ and list all those commands there in same manner as they're displayed now with `--verbose` option.
2. In _"Plugins"_ section do not list internal plugins. If there are no external plugin, do not present this section at all.

As we're simply affecting CLI help output, I think it's ok to not consider this change as breaking, it has no influence for deployment or any application setup/processing process.

**Comment by vinod-tahelyani** [comment]
@medikoo Can I take this?

**Comment by medikoo** [comment]
@vinod-tahelyani definitely! That'll be very welcome
