### ISSUE TITLE
2.11.1: serverless create with --template-path and shouldStartNameWithService gets overwritten with bad value

### ISSUE THREAD

**Issue by bitsofinfo** [serverless/serverless#8504]
If the following is in the `serverless.yml` template within `--template-path` during `serverless create`

```
  serverless create \
    --template-path templates/mytemplatedir \
    --path myservicename \
    --name myservicename
```

templates/mytemplatedir/serverless.yaml contains...
```
provider:
  apiGateway:
    shouldStartNameWithService: true
```

... you end up with this in the resulting service....

```
provider:
  apiGateway:
    shouldStartNameWithservice: myservicename
```

**Comment by medikoo** [comment]
@bitsofinfo great thanks for reporting. Will be fixed with https://github.com/serverless/serverless/pull/8508
