### ISSUE TITLE
not authorized to perform: cloudformation:DescribeStacks on resource

### ISSUE THREAD

**Issue by SaidBenaissa** [serverless/serverless#8509]
WebRTC_AWS_Websocket % serverless deploy --stage websocket
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  User: arn:aws:iam::301117383147:user/Said is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:eu-central-1:301117383147:stack/awswebrtc-websocket/*

**Comment by medikoo** [comment]
@SaidBenaissa please respect all bug report template remarks

**Comment by osmenia** [comment]
@medikoo 
Today I started sls deploy and got the same error as above. Nothing has changed in the config or user. why do i have error?

User has AdministratorAccess

Can you pls help me?

```
Serverless: Excluding development dependencies...
@Serverless Error ---------------------------------------
 
 User: arn:aws:iam::xxxx :user/xxxx is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:eu-central-1:xxxx :stack/rest-api-dev/xxxx with an explicit deny
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.4
     Framework Version:         1.76.1
     Plugin Version:            3.6.17
     SDK Version:               2.3.1
     Components Version:        2.32.0
```

**Comment by medikoo** [comment]
@osmenia for general support please visit:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

Otherwise if you're confident it's a bug in a Framework, please open new issue respecting all bug template remarks.

I'm closing this one, as it was unanswered by original author
