### ISSUE TITLE
Print timestamp on completion of deployment of cloudformation stack

### ISSUE THREAD

**Issue by senor-coder** [serverless/serverless#8519]
### Use case description

As a developer, a lot of time during context switching I forget if I ran the serverless deploy or not  after some code changes locally. Having terminal always open, seeing the timestamp of completion can be really helpful. Otherwise I end up deploying it again, or check the cloudformation log.  We face the above scenario once in a while,  since for quick prototyping at early stages, we deploy things from our local not using any CI/CD tool. Also having metrics around time taken to deploy , and time take by each step , build, deployment can be useful too. 

### Proposed solution

After the completion of deployment, Just a statement saying process completed at <time> can be really helpful. For the metrics part we can show them by default or adding optional cli params can be another approach

**Comment by senor-coder** [comment]
Happy to raise a PR, if the above request seem useful for a wider audience.

**Comment by medikoo** [comment]
@senor-coder `sls deploy` logs clearly indicate that deployment is finalized with `Stack update finished...` log and `Service Information` being output.

What exactly do you miss?

**Comment by senor-coder** [comment]
@medikoo It does tell me when the deployment finished. But along with that a timestamp of completion and other metrics like total time taken for deployment to complete, with a breakdown of packaging time, deployment time and total time will be nice to have. When I am working on multiple projects, I run the serverless deploy multiple times on each project. After sometime, I ask myself a question did i deploy all the changes in this project ? And I go to terminal and I just see Stack update finished... But I don't know when it was triggered though >_< . It may be inefficiency in the way I do things, I will certainly look in to improving on that. But if you find this as a good enhancement, then please let me know :)

**Comment by medikoo** [comment]
@senor-coder this I believe will be neatly solved with: https://github.com/serverless/serverless/issues/1720

Proposed solution is to switch to [log](https://github.com/medikoo/log) library for all logs generation, and that library supports output of timestamps by logs, configurable by [`LOG_TIME`](https://github.com/medikoo/log#timestamps-logging).

And that I think will provide you with all the information you miss

**Comment by senor-coder** [comment]
@medikoo That looks perfect. Thank you 👍
