### ISSUE TITLE
Enhancement: Better labeling of github issues

### ISSUE THREAD

**Issue by mwawrusch** [serverless/serverless#852]
It's really hard to get an overview of the project status because of the labeling of the issues. This is a problem for people like me who use/are going to use serverless in a production environment. It also makes it harder for you to track velocity and focus on the important stuff.

I think Google angular and angular-material have a better labeling system, might be worth checking out: https://github.com/angular/material2/labels

**Comment by eahefnawy** [comment]
@mwawrusch I hope you like our new labeling system 😊 

Thanks for your suggestion :)
