### ISSUE TITLE
Tests: Refactor lib/plugins/aws/package/lib/mergeIamTemplates.test.js

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8524]
_Most of the tests that currently cover core functionalities depend heavily on (and sometimes test) internal implementation characteristics. While they should be testing whether given implementation produces desired outcome (treating its implementation more as  a black box)._

_Current state of things is problematic for eventual internal improvements and refactors which occasionally we want to introduce, as in most of such cases proposed improvements need to be accompanied with counterproductive numerous updates to tests which are covering otherwise not altered functionalities ._

_At some point we've introduced a new (black box based) way of testing the internals. It's through `runServerless` utlity, which allows us create natural (as in real world) `serverless` instance, and inspect the produced outcome for chosen command. More details here: https://github.com/serverless/serverless/tree/master/test#unit-tests_

--- 

This is issue is about refactoring [lib/plugins/aws/package/lib/mergeIamTemplates.test.js](https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js) to `runServerless` based variant.

It's needed, so we cleanly move forward with https://github.com/serverless/serverless/issues/8396

To make refactor relatively easy:
- Spec for new tests is fully defined and is already committed in. It's in scope of this _describe_ block: https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js#L774
- Each test slot indicates which test it is about to replace
- It is indicated where (and how many) exactly `runServerless` runs are expected to happen, against which fixture and command they should be based
- Necessary hints are provided

For every refactored test, the old test should be removed

Refactor can be submitted with one PR, but partial refactors that cover some of below listed parts are also very welcome:

- [ ] __No default role__: https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js#L776-L793
- [ ] __Default role with defaults__: https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js#L808-L828
- [ ] __Provider properties__: https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js#L839-L865
- [ ] __Function properties__: https://github.com/serverless/serverless/blob/aa42b3bb899b1b770aeea013b51a4a3f2916427e/lib/plugins/aws/package/lib/mergeIamTemplates.test.js#L890-L893

**Comment by caiobessa** [comment]
Hi @medikoo  is it still relevant? I would like to work on it.

**Comment by medikoo** [comment]
@caiobessa yes, it's still very relevant. Contribution will be highly appreciated!
