### ISSUE TITLE
Fix isLocal variable

### ISSUE THREAD

**Issue by KuNman** [serverless/serverless#8529]
Hello guys.

We are facing an issue with building app.
Currently we are using `slsw.lib.webpack.isLocal` variable in webpack config.
Unfortunatelly, when I console.log this variable on my localhost for some reasons it returns `false` so webpack does production build each time when we want to test something locally. 
Same case repeats for CI. We have few environments and ONLY production should have optimized build. 

Can you explain how `isLocal` is working and how can we change it on the fly p.ex. depending on  `${self:provider.stage}`.

**Comment by medikoo** [comment]
@KuNman I think it doesn't belong to this repository.

If you believe it does, please get familiar and respect all issue template remarks, before posting
