### ISSUE TITLE
.gitignore - should vendored and _meta directory be in version control?

### ISSUE THREAD

**Issue by JDFagan** [serverless/serverless#853]
I just started using serverless and love it - great project!  I didn't notice a rule for vendored in the generated .gitignore for serverless project.  Should we be adding vendored contents for Python projects (e.g., if I added SQLAlchemy as dependency to my project, I followed recommendations and pip installed -t vendored/)?  My intuition is no for things that get generated (i.e., via pip install) but figured I double check.

Ditto for _meta?  I noticed lots of pyc files in _meta/_tmp but perhaps useful to version the .json files located at _meta/resources and _meta/variables?

**Comment by c-knowles** [comment]
For the _tmp folder there's #665 and #607 which is fixed in the upcoming 0.5.0. Not sure about the Python vendor part, will leave that to a contributor. For serverless with node, libraries are controlled via npm modules and the node_modules folder is git ignored.

**Comment by ac360** [comment]
`_meta` should not be in git as of V0.5.  Please check out the [Meta Sync Plugin](https://github.com/serverless/serverless-meta-sync)
