### ISSUE TITLE
Lambda can't put logs into logs stream

### ISSUE THREAD

**Issue by Werter12** [serverless/serverless#8549]
Hi, Team!
After upgrading the cli. I've made several deploys of my service and notices that Lambdas actually don't put logs into logs stream. 

Thats how permissions looks for UpdateCard labda *before*
![Screenshot 2020-11-26 at 00 27 15](https://user-images.githubusercontent.com/24315669/100288015-74fc2b00-2f7e-11eb-8d47-fe679c4302c6.png)

*After*

![Screenshot 2020-11-26 at 00 28 09](https://user-images.githubusercontent.com/24315669/100288028-7b8aa280-2f7e-11eb-890f-7cf082f7a4c0.png)

<b>Installed version</b>

```
Framework Core: 1.83.2 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```

**Comment by MatteoGioioso** [comment]
I think is because Kinesis is down in `us-east-1`: https://status.aws.amazon.com/

**Comment by medikoo** [comment]
@Werter12 I believe it was caused by AWS outage. Please confirm

**Comment by Werter12** [comment]
@MatteoGioioso @medikoo Thanks! You are absolutely right. Now logs working fine.
