### ISSUE TITLE
Double characters when typing in stage name using "sls project init" in v0.5 branch

### ISSUE THREAD

**Issue by kevinold** [serverless/serverless#855]
Using v0.5 at a12301d463ece30968cec613616a755e067b9dae against a serverless project without a _meta folder run: `sls project init`

Typing at the "Serverless: Enter a new stage name for this project" prompt, the characters entered are doubled, so "development" becomes "ddeevveellooppmmeenntt" and is ultimately written to _meta files and deployed once the user and region are chosen.

![screen shot 2016-03-21 at 9 45 29 pm](https://cloud.githubusercontent.com/assets/21967/13940852/4d72f726-efaf-11e5-8a65-a38c0fe20466.png)

![screen shot 2016-03-21 at 9 53 27 pm](https://cloud.githubusercontent.com/assets/21967/13940865/62c88438-efaf-11e5-9984-9f25e90b21b7.png)

**Comment by HyperBrain** [comment]
Seems like a duplicate of #834

**Comment by kevinold** [comment]
Closing as duplicate of #834
