### ISSUE TITLE
Using semantic versioning rules on private git repos within package.json causes dev deps to get packaged

### ISSUE THREAD

**Issue by NozzerFX** [serverless/serverless#8556]
Have come across an issue when using `sls package` when our package.json contains a dependency that is a private git repository.

We recently added a private git repository reference to one of our serverless projects.  An example of this reference is:

`"some-private-library": "git+ssh://git@gitplace.org:example/some-private-library.git"`

This reference was added to the projects `dependencies`.

This all works fine, when running `sls package` the normal behaviour occurs and all of the `devDependencies` get stripped from the package.

We then decided we wanted to support minimum versions of the private repo and have the package manager upgrade the package automatically using semantic versioning matching.  This is supported by NPM using the following syntax i.e. `#semver:^1.0.0` so our reference changed to:

`"some-private-library": "git+ssh://git@gitplace.org:example/some-private-library.git#semver:^1.0.0"`

This worked as expected but when running `sls package` we had issues where devDependencies were being included in the zip, specifically serverless itself bloating the package by over 200MB.

As luck would have it we use YARN as our package manager so were able to change the string to: 

`"some-private-library": "git+ssh://git@gitplace.org:example/some-private-library.git#^1.0.0"`

essentially removing the `semver:` part of the string.  This still works with YARN and `sls package` behaves as expected and excludes all devDependencies.

I believe this is a bug within sls when parsing the package.json to identify devDependencies in some way.  

NOTE: We also explicitly set:

`package:
      excludeDevDependencies: true`

to force dev dependencies to be excluded, even though this is the default behaviour when the environment is set correctly.

**Comment by medikoo** [comment]
> I believe this is a bug within sls when parsing the package.json to identify devDependencies in some way.

@NozzerFX Thanks for report. The only thing we do internally, which can be influenced is running `npm ls` -> https://github.com/serverless/serverless/blob/9399f2b89c8a841d1d7d96a22a8de640d8214479/lib/plugins/package/lib/zipService.js#L186

(we do not scan `package.json`)

Maybe this notation brings different results, or breaks `npm ls` ?

**Comment by NozzerFX** [comment]
@medikoo Thanks for your prompt response.

I can confirm what you have said.  With the `semver:` string included that command fails to output any lines.  I shall report this to the NPM team.
