### ISSUE TITLE
serverless create with template and frameworkVersion:

### ISSUE THREAD

**Issue by bitsofinfo** [serverless/serverless#8557]
I have serverless 2.12.0 and am running

```
serverless create --template-path <mytmplpath>
```

Inside the `<mytmplpath>/serverless.yml` i have 

Once I run other serverless cmds within the new project created from the template I get 

```
  The Serverless version (2.12.0) does not satisfy the "frameworkVersion" (2.13.0) in serverless.yml
```

How can I control that the new project created from the template is pulling down the correct version of serverless and not always the "latest"

**Comment by medikoo** [comment]
@bitsofinfo AFAIK `serverless create` does not interfere with template `frameworkVersion` property.

 It must be that original template has it fixed to `2.12.0`, in such case template should be fixed to refer to `^2.12.0`

**Comment by bitsofinfo** [comment]
? i don't understand. 

The CLI I am running `serverless create` with reports 2.12.0.

The template I am creating from requires 2.12.0

Somehow during the installation of plugins, I end up with 2.13.0

**Comment by medikoo** [comment]
I assume it's the template that you use that has hardcoded `frameworkVersion: 2.12.0` (`sls create` doesn't adjust this template property).

It's a bug on a template side, which needs to be fixed.

**Comment by bitsofinfo** [comment]
@medikoo the template is fine and nothing is changing the template the project is created from

How is it possible that my `Framework Version:         2.13.0` yet I get the error `  The Serverless version (2.14.0) does not satisfy the "frameworkVersion" (2.13.0) in serverless.yml`

```
Installing serverless plugin: serverless-stage-manager@1.0.5
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
 
  Serverless Error ---------------------------------------
 
  The Serverless version (2.14.0) does not satisfy the "frameworkVersion" (2.13.0) in serverless.yml
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.0
     Framework Version:         2.13.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2
```

**Comment by bitsofinfo** [comment]
`serverless plugin install` is causing the issue, if I monitor the package.json in the project the devDependencies slowly keeps getting changed eventually to to 2.13.0, then 2.14.0

`
  "devDependencies": {
    "serverless": "^2.13.0"
  }
`

**Comment by medikoo** [comment]
@bitsofinfo warning you see, is not related to `package.json` but to `frameworkVersion` property in a service configuration

It appears you have it set `2.13.0`, which  means that only v2.13.0 of Framework that is assumed as valid for operating on given service. That's pretty restrictive, and not natural. Update `frameworkVersion` setting to use relaxed version range (as e.g. `^2.13.0`) and there will be no issue.

**Comment by bitsofinfo** [comment]
I don't think you are understanding my point of what the issue is. When your installed serverless CLI is version X and your `frameworkVersion: X`, after project creation and installation of plugins... the package.json has the potential to "drift" for the serverless dev dependency to "!= X" leading to this error.

The framework provides and documents a feature that lets the operator declare a specific `frameworkVersion` in a serverless project to enforce governance with regards to version of serverless being used to do operations against a given project. Setting this to an explicit value, range of values or whatever is completely reasonable and "natural" for many reasons in an automated environment where you want to ensure consistency and repeatability for package generation/ deployments etc.  If the serverless project does not want people to list a specific `frameworkVersion` then the documents should reflect that or just get rid of the property all together.

For anyone else encountering this issue when installing plugins into a project where you have an explicit `frameworkVersion` in your serverless.yml ensure that when your project is created your template project has a package.json declared who's dev dep of serverless matches the version in your `frameworkVersion` + the specific plugin versions you want. Then after creation of your project, just run `npm install .` and don't use the `serverless plugin install ...` method

```
{
    "name": "<name of app>",
    "description": "",
    "version": "0.0.0",
    "dependencies": {},
    "devDependencies": {
      "serverless": "<specific version you want>",
      "serverless-plugin-y": "<specific version you want>"
      "serverless-plugin-z": "<specific version you want>"
    }
  }
  
```

**Comment by medikoo** [comment]
> after project creation and installation of plugins... the package.json has the potential to "drift"

`sls plugin install` uses regular `npm install <plugin-package-name>` command behind the scenes.

It's npm that eventually upgrades the `serverless` version range in `package.json`.

If your intention is to fix `serverless` to specific version, you need to state it `package.json, by fixing it as `"serverless": "2.13.0"`, having such config, npm will definitely not attempt to install any other `serverless` version for you.
