### ISSUE TITLE
Quick start video link gives 404

### ISSUE THREAD

**Issue by daverayment** [serverless/serverless#8559]
The main [https://github.com/serverless/serverless/blob/master/README.md](https://github.com/serverless/serverless/blob/master/README.md) page includes a link to a Quick Start video on the serverless site at [https://serverless.com/framework/](https://serverless.com/framework/). This currently redirects to [https://www.serverless.com/cli/](https://www.serverless.com/cli/) which comes up with a 404.

If the video is no longer available, could the README.md file be updated with alternative instructions for beginners?

**Comment by medikoo** [comment]
@daverayment great thanks for reporting!

I've just removed the problematic link with https://github.com/serverless/serverless/commit/d34f452034642b0f380e055db498f78ca20d085f.  It was highly outdated
