### ISSUE TITLE
Where should model definitions go in s-function.json?

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#856]
Hi,

Been looking around for a while now, can't find any examples of where model definitions should reside in s-function.json to get parsed and used in endpoint requests.

I've already figured out: 
```
      "requestModels": {
        "application/json": "eventCreateModel"
      },
```

What I can't figure out is where to place:

```
    {
      "name": "eventCreateModel",
      "description": "Create event model",
      "contentType": "application/json",
      "schema": "$${eventCreateExtSchema}"
    },
```

It seemed logical to me to put it inside a:
```
"models": [
]
```

But it doesn't seem to be the right place ... I've attached the error output, but to me it just looks like "model doesn't exist", which makes me think I put the model definitions in the wrong place for serverless to create them prior to creating the endpoint...
[Error.txt](https://github.com/serverless/serverless/files/183454/Error.txt)

Does anyone have any ideas, or examples? I'd love to see one...

**Comment by HyperBrain** [comment]
@cdichiara I published the first version of my new models plugin. It adds the missing model support for Serverless 0.5.x. See https://www.npmjs.com/package/serverless-models-plugin

**Comment by cdichiara** [comment]
Nice work, @HyperBrain! Very clean, and a better solution than what I was imagining. Thanks! I'll let you know if I run into any difficulties.

**Comment by cdichiara** [comment]
Works like a charm.

**Comment by HyperBrain** [comment]
Glad to hear that :-). The only thing that you should keep in mind, is that models are global in an API (which is by APIG design), so if you change a model and deploy to dev, you should take care that you do not remove properties used by the API deployed on production. But I think that is a general problem with APIG models that cannot be solved currently.

**Comment by cdichiara** [comment]
Interesting ... I hadn't tested that, but I was starting to feel the uncertainty about which of my development changes were making it through to the staged test API and which were not. Glad to get the confirmation that models are not staged the same way as the resources.

**Comment by HyperBrain** [comment]
At least that's my experience. Maybe you can dig deeper into that. It would be worth a feature request at AWS then.

**Comment by cdichiara** [comment]
Ah, gotcha. I just tested it ... changes made to one of my models were only reflected in a stage's exported swagger when I redeployed the stage. So perhaps AWS got it right. :smile:

Same went for model deletion (post-resource deletion, rather than post-resource unassignment, but seemed thorough enough of a test).

**Comment by cdichiara** [comment]
Oh, I see what you mean - models have to preserve the features of production models if you plan to redeploy production, there's no easy way to version models other than changing their names...

**Comment by flomotlik** [comment]
As it seems the question was answered I'm going to close this issue. For further discussion you can also look into [our Gitter room](https://gitter.im/serverless/serverless)
