### ISSUE TITLE
Expose all cloud provider options to all users despite their geolocations

### ISSUE THREAD

**Issue by xiqi** [serverless/serverless#8565]
### Use case description

Serverless Framework is currently using timezone to detect users whose geolocation is in China, and if it determines the user is in China, it will only give the user options to use Tencent Cloud, instead of AWS and Google Cloud when the user executes "serverless".

However, there are indeed many people located in China using Serverless Framework expecting to deploy their functions to AWS, Google Cloud, etc.

https://github.com/serverless/serverless/blob/6fccedea4ac5a3a546d36b19d2e0701defd9ed85/scripts/pkg/install.sh#L33-L47

I think it is not the optimal choice to give users completely different options based on their current geolocations.

### Proposed solution

Expose all options to all users, do not differentiate users according to their geolocations. Give users the ability to choose among different cloud providers.

**Comment by medikoo** [comment]
@xiqi In script you list we use different server when user is located in China, simply because downloads from GitHub server are very slow in China (due to its firewall)

Otherwise functionality remains exactly same

**Comment by xiqi** [comment]
I couldn’t locate the piece of code where the functionality actually differs, but there is a simple way to see it in action — set your system clock’s timezone to Beijing, China and then run “serveless” to create a new project. After answering “Y”, the given options are completely different.

**Comment by medikoo** [comment]
> After answering “Y”, the given options are completely different.

Yes it's for interactive setup. Currently it's either AWS or Tencent based setup that's been run.

It can be overriden via `SERVERLESS_PLATFORM_VENDOR` environment variable, setting it to `aws` will enforce AWS setup and setting it to `tencent` will enforce the tencent.

We're working on CLI unification effort, and that in a long run should ensure a more consistent approach across locations.
In initial phase we're preparing internals for it, check https://github.com/serverless/serverless/issues/8364 for more details

**Comment by xiqi** [comment]
Thanks for your quick response and explanation!
