### ISSUE TITLE
AWS Lambda: Container Image Support

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8570]
### Use case description

Answering the AWS announcement: https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

Provide a means to configure lambdas pointing container images. In initial phase let's focus on basic support that paves the path for eventual more extensive support (to be provided by community, when there's a demand)

### Proposed solution

Full deployment flow cannot be configured just through CloudFormation, as most of the setup involves using the Docker CLI on developer machine. It technically can be baked in in the Framework internals (prior deploying the CloudFormation stack) but it'll be very different from how other Framework features work.

Process is as follows. After developer (1) prepared (per AWS instructions a docker image that is ready to be used as lambda target) and (2) locally built a docker image, following steps need to be taken to have it deployed to AWS Lambda environment:

1. _[via AWS CLI]_: (if it doesn't already exist) Create a repository for corresponding lambda in AWS ECR
2. _[via AWS CLI and Docker CLI]_:  Login Docker CLI to AWS ECR
3. _[via Docker CLI]_: Tag locally created image to image in context of AWS ECR repository 
4. _[via Docker CLI]_: Upload the image to AWS ECR repository
5. _[via AWS CLI]_: If Lambda doesn't exist create lambda and point to image, if it exists update the lambda code pointing the image

Still, in initial implementation let's just simply pave the path to make referencing AWS ECR images in lambda configurations possible.

Let configuration be as follows:

```yaml
functions:
  <functionName>:
    # Note: `image` is to be used exchangeably with `handler` property
    image: <account>.dkr.ecr.<region>.amazonaws.com/<repository>@<digest>
```

At packaging step, do not attempt any packaging logic for lambdas configured with `image` (follow similar route as if they have preconfigured `package.artifact`)

**Comment by mojimi** [comment]
Absolutely stoked about this feature, I've had so many hours wasted building a custom runtime Lambda

Unfortunately in the short term this makes many current tools obsolete, but the future is amazing for this feature, local testing is actually trustworthy now
