### ISSUE TITLE
Replace fs-ext with equivalent native fs when possible

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#8605]
These are the functions that I've found in the codebase which are in fs and can be used from fsPromise or using util.promisify directly

- [x] exists (https://github.com/serverless/serverless/pull/8788)
- [x] realpath (https://github.com/serverless/serverless/pull/8853)
- [x] writeFile (https://github.com/serverless/serverless/pull/9870)
- [x] rename (https://github.com/serverless/serverless/pull/9605)
- [x] chmod (https://github.com/serverless/serverless/pull/9647)
- [x] createWriteStream (https://github.com/serverless/serverless/pull/9687)
- [x] unlink (https://github.com/serverless/serverless/pull/9754)
- [x] readdir (https://github.com/serverless/serverless/pull/9780)
- [x] stat (https://github.com/serverless/serverless/pull/9845)
- [x] access (https://github.com/serverless/serverless/pull/9915)
- [x] readFile (https://github.com/serverless/serverless/pull/9935)

**Comment by medikoo** [comment]
@juanjoDiaz Thanks for opening that. Yes, we definitely can rely on `fs` in that case.

Fact that in those places `fs-extra` is used, I believe is purely for convenience of using one `fs` collection in module. Note that `fs-extra` aliases all `fs` functions. It's like `fs` with extras, such usage is actually advertised in `fs-extra` documentation.

Anyway I'm totally after relying on `fs.promises` directly instead (with exclusion of _sync_ variants and `createWriteStream`, as those are not promise returning functions)

PR is welcome!

**Comment by sdas13** [comment]
Hello,
Can I work on some of the areas?

**Comment by medikoo** [comment]
@sdas13 definitely! PR's welcome

**Comment by pgrzesik** [comment]
Hello @sdas13 :wave: Looks like all refactors from the list has been covered thanks to your contributions :bow: Do you see any other potential refactorings from `fse` that could be replaced by native utilities?

**Comment by sdas13** [comment]
Hey @pgrzesik 
Couple of async fse functions that can be refactored are `access` and `readFile`. There are few fse functions like `ensureFile`, `ensureDir`, `readJson`, `remove`, `mkdirs` which are not fs native. Although `remove` and `mkdirs` can be replaced by `rm` and `mkdir` respectively. Also all the sync counterparts can be refactored.

**Comment by medikoo** [comment]
>  Also all the sync counterparts can be refactored.

That is in scope of https://github.com/serverless/serverless/issues/8604

**Comment by pgrzesik** [comment]
@sdas13 I think that the functions that don't have a direct native replacement are okay to stay, what do you think? cc @medikoo

**Comment by medikoo** [comment]
> @sdas13 I think that the functions that don't have a direct native replacement are okay to stay, what do you think? cc @medikoo

yes definitely I wouldn't touch them (there's no goal to get rid of `fs-extra` completely)

Therefore it appears that `fse.access` and `fse.readFile` are still missing refactor (I've added them to top list)

**Comment by sdas13** [comment]
> yes definitely I wouldn't touch them (there's no goal to get rid of `fs-extra` completely)

Agreed !

**Comment by pgrzesik** [comment]
PR https://github.com/serverless/serverless/pull/9935 marks the last piece of the refactoring as a part of this task, I think we're fine to close it, what do you think @sdas13 @medikoo ?

**Comment by medikoo** [comment]
@pgrzesik definitely! Great thanks @sdas13 for making that happen!
