### ISSUE TITLE
Add filter to sls dash deploy when more than 10 endpoints

### ISSUE THREAD

**Issue by mwawrusch** [serverless/serverless#861]
The current UI becomes unusable with more than 10 or so functions, depending on screen size. I propose adding a filter to match by names and show only those matching the filter

To reproduce: Make your shell window small and try to select the first items...

**Comment by jordanmack** [comment]
@mwawrusch If you group your functions in separate subfolders, then use dash deploy within that subfolder, it will only show the functions contained within. This is kind of like filtering.

**Comment by mwawrusch** [comment]
that's a great idea, thanks.
