### ISSUE TITLE
Relocate usagePlan, apiKey and resourcePolicy from provider to apiGateway

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8617]
Following discussion in https://github.com/serverless/serverless/issues/8488#issuecomment-727846762, this issue aims to deprecate and move to the right location `provider` specific attributes `usagePlan`, `apiKey` and `resourcePolicy`.

- `resourcePolicy` is used in API Gateway V1 provisioning, to hydrate `Policy` property of `AWS::ApiGateway::RestApi` resource - no equivalent in V2
- `apiKey` is used in API Gateway V1 provisioning, to create `AWS::ApiGateway::ApiKey` resources - no equivalent in V2
- `usagePlan` is used in API Gateway V1 provisioning, to create `AWS::ApiGateway::UsagePlan` resources - some intersection in V2 (described hereafter)

The proposal is to move all those properties from `provider` level down to `provider.apiGateway` level. This relocation is done by creating the new property and deprecating the old one. Next major release of Serverless will remove the `provider` level properties.

Some property defined in current shape of those parameter could be used to provision API Gateway V2, but their current shape is very specific to cloudformation syntax for V1, i.e. : `usagePlan.Throttle` defines both `BurstLimit` and `RateLimit`. API Gateway V2 allow similar throttling parameters through `RouteSettings` property on `AWS::ApiGatewayV2::Stage` which contains `ThrottlingBurstLimit` and `ThrottlingRateLimit` parameters. The correct way of evolving those could be to have a nomenclature distinct from both V1 and V2 configuration, and use this configuration at the correct location on both versions.

**Comment by medikoo** [comment]
Thanks @fredericbarthelet for openning that. It's a good call, and PR is welcome.

I believe we need to move those properties, and [deprecate](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations) them at old location

**Comment by Edu93Jer** [comment]
Hi guys, I am new at open source and would like to contribute to the project, this issue looks good to get started, but please guys could you please let me know how to start attacking the issue? 
Could you please explain to me a little more @fredericbarthelet or @medikoo  so I can get the full context, or look at where is the issue exactly, thanks!

**Comment by pgrzesik** [comment]
Hello @Edu93Jer, thanks for your interest in this issue :raised_hands:. As it looks like, @fredericbarthelet already prepared a PR that will close it: https://github.com/serverless/serverless/pull/8670. We have a few other issues with the "Good First Issue" label that could serve as your starting point when it comes to contributions. :raised_hands:
