### ISSUE TITLE
Support Google Functions + Other Lambda Like Infrastructures.

### ISSUE THREAD

**Issue by cphoover** [serverless/serverless#862]
I think the paradigm behind lambda, is going to be widespread across different providers. As we see more and more alternatives to Lambda, it would be beneficial to keep this library abstracted to the point it can be used on providers like google. Google already has their Cloud Function service. 

This ticket is intended as a point of discussion, and not necessarily something that is actionable/urgent in it's current state.

**Comment by knpwrs** [comment]
[OpenWhisk](https://developer.ibm.com/openwhisk/) is another similar service.

**Comment by domderen** [comment]
There is one more now: https://azure.microsoft.com/en-us/services/functions/ ;)

**Comment by MrRio** [comment]
The main ones are:
AWS Lambda
Google Cloud Functions
IBM OpenWhisk
Azure Functions
Iron.io
Webtask

**Comment by cphoover** [comment]
Thanks @MrRio for that list.

**Comment by sedouard** [comment]
hey @MrRio from Microsoft! We'd love to contribute to making this work with Azure functions but I think the question from just surfing the code base is where to get started.

I'm not super-duper familiar with the code base by I noticed there's a [ProviderAws](https://github.com/serverless/serverless/blob/d79e586ba0ea89ba61218ed129aa861f20587d2c/lib/Serverless.js#L35). Does it make sense to implement other vendor providers similarly?

Do you think we're in a place where vendor-specific contributions make sense to start or should we wait until some work is done on serverless to make it more 'pluggable' to other Lambda-like cloud services?

**Comment by cphoover** [comment]
looping in @ac360

**Comment by cphoover** [comment]
I'd also be happy to help with this in some capacity. Perhaps we should talk about what a unified design for the interface across providers would look like. Obviously they have different configurations, and probably varying feature sets. Would like to hear opinions and ideas from others.

**Comment by domderen** [comment]
Sounds like there's a need for a standard ;)

**Comment by rajington** [comment]
If they do make a standard I hope it's the promise-based style that [runtime-babel](https://github.com/serverless/serverless-runtime-babel) uses.

also: 

https://github.com/siscia/effe
https://weblab.io/

**Comment by JamieCressey** [comment]
+1 for Google and Azure

**Comment by ryuheechul** [comment]
Yeah it would be very nice if serverless can work with other cloud providers, too.

**Comment by jthomas** [comment]
Would be happy to help providing OpenWhisk provider implementation.

**Comment by eahefnawy** [comment]
@jthomas Thanks for pitching in! We're definitely interested in supporting OpenWhisk. Could we setup a call with you soon to talk about this further? We'll send an email to your james@jamesthom.as address 😊 

Looking forward!

**Comment by flomotlik** [comment]
Support for multiple providers is planned for future releases. I'm going to close this issue as we will open other issues and milestones to track this.
