### ISSUE TITLE
AWS Lambda: Support referencing images via tags

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8621]
### Use case description

Currently we support only referencing images via ECR URI with hash postfix (`<account>.dkr.ecr.<region>.amazonaws.com/<repository>@<digest>` ). It'll be nice to support tags, so updating image behind the scenes doesn't require an update to service configuration

### Proposed solution

1. Extend the [`functions[].image`](https://github.com/serverless/serverless/blob/a8be1d1776a26b033d821d70e99ad654a39a4158/lib/plugins/aws/provider.js#L946-L950) property schema so tag format is supported
1. In `lib/plugins/aws/package/compile/functions.js` introduce a memoized method `resolveImageShaFromTag` which for input image tag uri should resolve from AWS (rely on `this.provider.request`) an image sha uri
1. If tag format is used resolve sha through `resolveImageShaFromTag` method for [`Code.ImageUri`](https://github.com/serverless/serverless/blob/a8be1d1776a26b033d821d70e99ad654a39a4158/lib/plugins/aws/package/compile/functions.js#L177)

**Comment by joshburt** [comment]
I put together a solution yesterday leveraging this new functionality.  The largest issue I ran into was image reference by digest and maintaining this going forward.  Came here to put in a request and was happy to see @medikoo beat me to it. :)

**Comment by LtTempletonPeck** [comment]
> I put together a solution yesterday leveraging this new functionality. The largest issue I ran into was image reference by digest and maintaining this going forward. Came here to put in a request and was happy to see @medikoo beat me to it. :)

What he said
