### ISSUE TITLE
AWS Lambda: Auto create and push docker images to ECR repository

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8622]
### Use case description

Currently user has to create and deploy an image to ECR in his own capacity. It'll be nice if in a Framework user can point directory with a `Dockerfile` and let Framework does the rest behind the scenes

### Proposed solution

As we want to make images reusable across lambdas and also need to coin some image repository naming convention for AWS ECR I believe we need to introduce dedicated location for configuring images out of function context. For that I propose to introduce `provider.images` property.

1. Define `provider.images` property, where we should support following notations:

```yaml
provider:
  images:
    image1: ./path/to/image1-content
    image2:
      path: ./path/to/image2-content
    image3:  <account>.dkr.ecr.<region>.amazonaws.com/<repository>...
    image4:
      uri: <account>.dkr.ecr.<region>.amazonaws.com/<repository>...
```
1. In `lib/plugins/aws/package/compile/functions.js` introduce following updates:
   1. Introduce a memoized method `loginDockerToEcr`. in context of this method we need to retrieve ECR session password and pass it to `docker login`. As I briefly changed this password can be obtained only via AWS CLI with command as `aws ecr get-login-password --region <region>`. If it's indeed the case, we need to retrieve it that way (ensuring AWS CLI relies on same AWS auth credentials as we do when calling AWS SDK programmatically). Having password resolved we call `docker login --username AWS --password <password> <account>.dkr.ecr.<region>.amazonaws.com`.
   1. Introduce a memoized method `resolveImageShaFromPath` which for (2) input image name and (2) path to image content should in final turn resolve sha of image in AWS ECR registry. For that following steps need to be taken (note that it's optimal to run some of them in parallel(:
      1. Ensure that `${path}/Dockerfile` file exists
      1. Run `this.loginDockerToEcr()` to ensure we're logged in
      1. via AWS SDK confirm that `{service}-{stage}-{imageName}` repository exists
      1. Build the docker image locally with `docker image -t  <service>-<stage>-<region>-<imageName> <path>`
      1. Tag the local `latest` tag of an image to `latest` in contextr of ECR repository, via `docker tag <service>-<stage>-<region>-<imageName> <path>:latest <account>.dkr.ecr.<region>.amazonaws.com/<service>-<stage>-<region>:latest`
      1. Push tagged image to ECR via ` docker push <account>.dkr.ecr.<region>.amazonaws.com/<service>-<stage>-<region>:latest`, resolve returned sha from command output and return it from a method.
   1. Support referencing image name at `functions[].image` property.
   1. If function references image from a `provider.images` group that is defined with a path, run `this.resolveImageShaFromPath(imageName, path)` to resolve the target sha (to be used for [`Code.ImageUri`](https://github.com/serverless/serverless/blob/a8be1d1776a26b033d821d70e99ad654a39a4158/lib/plugins/aws/package/compile/functions.js#L177))
1. Ensure unit tests but with `spawn` calls mocking
2. Document new feature

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by pgrzesik** [comment]
Hello @GG-Sheridan, as for this issue, while I think a lot of newcomers would be able to successfully tackle this issue, I would argue that it might be a bit too "big" to be a "Good First Issue" label worthy. For newcomers to the project, I would recommend starting with something simpler first. Good luck with your research :raised_hands:
