### ISSUE TITLE
Ensure docs consistency

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#8629]
### Use case description

A lot of the docs are pretty much the same for all providers.
However, they seem to have diverted over time.

For example, if we compare `docs/providers/aws/guide/packaging.md` and `docs/providers/azure/guide/packaging.md`.
* The Azure docs use `sls` and the  AWS docs use `serverless`
* The Azure docs says `deployment artifacts in the .serverless directory:` and the  AWS docs says `deployment artifacts in the service's .serverless directory:`
* The AWS docs document the `--package` flag but the Azure docs don't.
* The AWS docs document in details the inclusion/exclusion logic and the Azure docs don't.
* The AWS docs document single function packaging but the Azure docs don't.
* `serverless-webpack` plugin is documented in the Azure docs but not in  the AWS docs
* Some headers are different.
* The are small differences like new lines and extra spaces.

The same kind of differences happen between the different providers

### Proposed solution

As a minimum, we should compare the docs of the different side by side and ensure consistency.
Of course, some parts are provider-specific but the common parts should be the same for all of them.

A better solution would be to use some sort of templating engine to generate the docs for the different providers from the templates so content consistency is ensured.

**Comment by medikoo** [comment]
@juanjoDiaz There's a plan is to seclude parts that are common to every provider out of provider context -> https://github.com/serverless/serverless/issues/8085

Just that should ensure, that we should be free mostly from duplicated content which is written with different convention (by simply not following same updates)

We also plan to remove all non AWS provider documentation to provider plugins -> https://github.com/serverless/serverless/issues/8097

**Comment by juanjoDiaz** [comment]
Seems to be covered by those two issues.
Closing this one.
