### ISSUE TITLE
CloudFormation increased resource limits (200 > 500) warning.

### ISSUE THREAD

**Issue by rsd-raul** [serverless/serverless#8630]
I'm running 1.83.2 and deploying stacks with 200+ resources as AWS [recently increased](https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/) the 200 resources hard-limit to 500.

But I'm getting the warning:

> You have 269 resources in your service.
  CloudFormation has a hard limit of 200 resources in a service.
  For advice on avoiding this limit, check out this link: http://bit.ly/2IiYB38.

Wondering if that can get fixed in V1, and while I'm at it, if it might be a problem in V2 too, as I've been looking at the changelogs but haven't found any info in that regard (probably to small a detail).

My current version is:

Framework Core: **1.83.2**
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9

**Comment by medikoo** [comment]
@rsd-raul please upgrade to latest version of a Framework

**Comment by rsd-raul** [comment]
Hi @medikoo, if I'm not mistaken I'm on the latest version for V1. Sadly we haven't looked into moving to V2 yet, but if that's fixed on 2.+, we definitely will look into it.

ps: My initial idea was to jump directly to 3.+ when it released, but we might have to reconsider.

**Comment by medikoo** [comment]
> but if that's fixed on 2.+

Yes, it's for a long while filxed in v2

> ps: My initial idea was to jump directly to 3.+ when it released,

By all means, you should always upgrade 1 by 1, so first to v2 and then v3. Otherwise you won't benefit from automated notifications of what breaking changes you may expect from next major.

**Comment by rsd-raul** [comment]
@medikoo Perfect, thanks a lot for the info regarding v2, and also the 1by1 recommendation, will definitely keep it in mind, you are absolutely right about the breaking changes info :S

Ps: I'll proceed to close this ticket, as I'm assuming v1 will only receive important fixes at this stage, and this is understandably not one of them.
