### ISSUE TITLE
Streaming analytics support for AWS Kinesis + DynamoDB Streams

### ISSUE THREAD

**Issue by waynerobinson** [serverless/serverless#8631]
This new Lambda feature for AWS Kinesis + DynamoDB Streams allows for consistent aggregations across streams by consistent time-window.

https://aws.amazon.com/blogs/compute/using-aws-lambda-for-streaming-analytics/

**Comment by pgrzesik** [comment]
Hello @waynerobinson, thanks a lot for submitting that feature request. It is an interesting feature and we'd definitely like to have support for it. 

After checking out the current documentation, it seems like the `TumblingWindowInSeconds` configuration parameter is currently not supported by CloudFormation (ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html). Given that, we should wait for CloudFormation support for the mentioned parameter, but in the meantime, we could decide on the implementation proposal and as soon as CloudFormation support is added, we'd be happy to accept a PR adding that functionality.

All feedback is welcome :100:

**Comment by pgrzesik** [comment]
Hello, by mistake I've created a duplicate issue for it with proposed spec: https://github.com/serverless/serverless/issues/8815 As the other one has spec inlcuded, I'll close this one - sorry for the confusion!
