### ISSUE TITLE
Allow clientContext to be used with AWS invoke

### ISSUE THREAD

**Issue by lewgordon** [serverless/serverless#8644]
### Use case description

At our company, we have a team that maybe has a different use case than most when it comes to providing data for our lambda functions.  They'll provide authorization details, such as user id in a client context passed to the invoked function.  This is easy to test locally by running `sls invoke local --context ...` / `sls invoke local --contextPath`.  However, I noticed when I deployed my lambda I wasn't able to use a custom context with just `sls invoke`.  In this case, I tend to revert back to the use of the AWS CLI to invoke the lambda with the custom context.  It'd be nice if I could provide this same information through the Serverless framework directly.

### Proposed solution

My proposal is simple, which is to add `context` and `contextPath` similar to how it's represented for `sls invoke local`.  I also have a [branch in my fork](https://github.com/lewgordon/serverless/tree/implement-invoke-client-context) that includes most of the implementation.

**Comment by pgrzesik** [comment]
Hello @lewgordon :wave: Thanks a lot for submitting your proposal. I believe it makes a lot of sense to support `context` and `contextPath` also for `invoke` command. We'd be more than happy to accept a PR that adds the following functionality. If you'd like to prepare the final PR, please keep in mind a few things:
1. It is recommended to use `async/await` syntax if possible - we're currently trying to migrate to `async/await`
2. When writing tests, please take advantage of `runServerless` utility, all new functionality is supposed to be covered by tests with `runServerless` and we're slowly migrating all older tests to use it as well. 
3. Currently, `invoke` function also supports global setting `--config / -c` - if we'd add support for `-c` for `context`, we would end up with clashing shortcuts - let's try to avoid it which means we probably shouldn't support shortcut for context parameter in this case. 

Feel free to reach out if you have any concerns, comments or questions :100:
