### ISSUE TITLE
EndpointDeploy: Handle non-deployed authorizer functions more gracefully

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#865]
When trying to deploy endpoints, custom authorizers are created first.  If a function that is serving as a custom authorizer has not been deployed, and EndpointDeploy is trying to find it, the following error will be thrown:

```
ResourceNotFoundException: Cannot find alias arn: arn:aws:lambda:us-east-1:14812831093:function:serverless-auth:mystage
```

At the very least, we should better explain what's happening if this error is thrown.

**Comment by eahefnawy** [comment]
@ac360 is this still an issue?
