### ISSUE TITLE
HttpApi in cloudformation stack output

### ISSUE THREAD

**Issue by captainsano** [serverless/serverless#8650]
### API Gateway HttpApi not present in cloudformation stack output

I'd like to import the HttpApi id in another cloudformation stack for creating cloudwatch alarms. This is currently not exported.

### Proposed solution

Export the value of HttpApi cloudformation resource along with the currently exported url

**Comment by medikoo** [comment]
@captainsano thanks for proposal. We're definitely open for it. PR that implements that is welcome!

**Comment by captainsano** [comment]
@medikoo Thanks! I'd love to take this up :-D Here's how I thought I would go about this,

- Add the output for HttpApi in `httpApi.js`, also add a corresponding test in `httpApi.test.js` expecting the output to have value. These files are under `lib/plugins/aws/package/compile/events/`.

**Comment by medikoo** [comment]
@captainsano you've got it perfectly. PR is welcome!
