### ISSUE TITLE
bashrc modified without notice or consent

### ISSUE THREAD

**Issue by jasonkarns** [serverless/serverless#8651]
I cloned and set up a client's node project. Without any notice and _particularly_ without my consent. Modifying core system preference files is out of bounds for an npm package. It borders on malicious activity.

Node's package system is built around the idea of _local_ packages. Global installation is not recommended. And this package, even when installed as a _local development dependency_, modifies a global configuration file _by default and **without consent**_. What's more, it now invokes additional third party code that runs on my machine on EVERY SHELL INSTANCE. This is unacceptable for a _project-specific dependency_.

If users understand and want this feature, it is completely within their capability to opt-in. But to have this installed and running in _all_ shell instances is a massive security vulnerability waiting to happen. Unconscionable.

<details>
<summary><code>serverless.yml</code></summary>

not relevant

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

n/a
</details>

<b>Installed version</b>

```
$ $(npm bin)/serverless --version
Framework Core: 1.53.0
Plugin: 3.1.1
SDK: 2.1.0
Components Core: 1.0.0
Components CLI: 1.2.3
```

**Comment by medikoo** [comment]
@jasonkarns you're relying on heavily outdated version of a Framework. Please upgrade

**Comment by jasonkarns** [comment]
I'm not sure which release between 1.53.0 and 1.83.3, but as of 1.83.3, the issue is resolved.
