### ISSUE TITLE
Tests: Refactor lib/plugins/aws/invoke.test.js

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8662]
_Most of the tests that currently cover core functionalities depend heavily on (and sometimes test) internal implementation characteristics. While they should be testing whether given implementation produces desired outcome (treating its implementation more as  a black box)._

_Current state of things is problematic for eventual internal improvements and refactors which occasionally we want to introduce, as in most of such cases proposed improvements need to be accompanied with counterproductive numerous updates to tests which are covering otherwise not altered functionalities ._

_At some point we've introduced a new (black box based) way of testing the internals. It's through `runServerless` utlity, which allows us create natural (as in real world) `serverless` instance, and inspect the produced outcome for chosen command. More details here: https://github.com/serverless/serverless/tree/master/test#unit-tests_

--- 

This is issue is about refactoring [test/unit/lib/plugins/aws/invoke.test.js](https://github.com/serverless/serverless/blob/b72a910604b4e7d3dc3da267f47e5ed41a34d551/test/unit/lib/plugins/aws/invoke.test.js#L456) to `runServerless` based variant.

To make refactor relatively easy:
- Spec for new tests is fully defined and is already committed in. It's in scope of this _describe_ block: https://github.com/serverless/serverless/blob/b72a910604b4e7d3dc3da267f47e5ed41a34d551/test/unit/lib/plugins/aws/invoke.test.js#L303-L467
- Each test slot indicates which test it is about to replace
- It is indicated where (and how many) exactly `runServerless` runs are expected to happen, against which fixture and command they should be based

For every refactored test, the old test should be removed

Refactor can be submitted with one PR, but partial refactors that cover some of tests are also very welcome!

**Comment by js-cha** [comment]
Hi @medikoo - I was wondering if it's okay to pick up some of these remaining tests that need to be refactored?

**Comment by medikoo** [comment]
@js-cha yes, definitely! We'll be grateful to have that part sorted out.
