### ISSUE TITLE
Interoperate with Terraform DynamoDB locks (plugin?)

### ISSUE THREAD

**Issue by nl-brett-stime** [serverless/serverless#8663]
### Use case description

When using the Terraform S3 'backend', it's possible to configure a DynamoDB table for locking:

https://www.terraform.io/docs/state/locking.html
https://www.terraform.io/docs/backends/types/s3.html#dynamodb_table

This TF feature attempts to perform a conditional write to a DynamoDB table before making changes to the resources protected by the lock. If some other user has already begun modifying the protected resources through Terraform, the write condition will fail and the second user will have to wait until the first user has finished making their modifications. This prevents two users from trying to modify the controlled resources at the same time.

Some Serverless features such as Cognito User Pool trigger events modify existing resources. It'd be a good safety feature to tell Serverless to take a list of arbitrary locks that are compatible with Terraform to ensure that resources that are partially managed by both SLS and TF aren't being modified at the same time.

### Proposed solution

Add a section in serverless.yml like the following:

```
terraformDynamoDbLocks:
  - someLockName:
      table: someTableName
      bucket: someBucketName
      workspace_key_prefix: someKeyPrefix
      workspace: someWorkspace
      key: someKey
```

When running e.g., `serverless deploy` if Serverless is unable to acquire any of the declared locks it should throw an error message like, "Unable to acquire lock for 'someBucketName/someKeyPrefix/someWorkspace/someKey' the lock was acquired by other.user@your.org at 2020-12-22T15:22:43.960627Z. If you're sure they're done managing the remote state, you can force an unlock by running the following command: `serverless terraform-force-unlock someLockName 1a756b9b-93b2-91c3-3811-098b884033aa`". It's already possible to use Terraform itself to force the unlock so that part of the feature would be less urgent but convenient for users who didn't also already have easy access to a configured Terraform installation.

Serverless should revert any locks it's created once it's done attempting it's modifications.

**Comment by pgrzesik** [comment]
Hello @nl-brett-stime, thank you for the request. It makes a lot of sense for that specific use case, but I feel like it's way too specific to be a part of the core framework and is instead a good candidate for a dedicated plugin. Related repository: https://github.com/serverless/plugins

**Comment by nl-brett-stime** [comment]
Moved to https://github.com/serverless/plugins/issues/356 .

**Comment by nl-brett-stime** [comment]
@pgrzesik : I already moved the Terraform interop portion to the plugins repo. However, as an afterthought, I'm wondering if Serverless provides it's own method for locking that's compatible with AWS. It seems like it might still be useful for the Serverless core to e.g., standardize `acquire_lock` and `release_lock` stages, even if they do nothing by default so that different plugins e.g., Azure or GCP only have to fill in their respective details to get called at the right time in the Serverless' deploy lifecycle.

**Comment by pgrzesik** [comment]
Hello @nl-brett-stime :wave: There's not standard locking method as far as I'm concerned, however, I believe if there would be such a need, there are existing hooks `before:deploy:deploy` and `after:deploy:finalize` which I believe could be successfully used to implement it. What would be the benefit of adding e.g. additional lifecycle events in this case? Thanks in advance :bow:

**Comment by nl-brett-stime** [comment]
As long as `after:deploy:finalize` is called irrespective of any exceptions that should probably be fine. It'd probably also be good to make sure the state of the deploy is available at that time (either full success or some/partial failures) in case the plugin wanted to retain the lock for some types of incomplete deploys.
