### ISSUE TITLE
Improve documentation around deprecations

### ISSUE THREAD

**Issue by pgrzesik** [serverless/serverless#8665]
At the moment, while we have the ability to disable deprecations via `SLS_DEPRECATION_DISABLE` environment variable, it is not documented which makes it hard to use. The goal of this issue is to improve deprecations documentation which will make it easier for people to disable deprecations if such need arises.

### Implementation proposal

1. Add reference to `SLS_DEPRECATION_DISABLE` in `sls --help` output, under `Environment Variables` section
2. At the top of [docs/deprecations](https://github.com/serverless/serverless/blob/master/docs/deprecations.md), add a section explaining the use of `SLS_DEPRECATION_DISABLE` to disable specific deprecations.
3. In [docs/deprecations](https://github.com/serverless/serverless/blob/master/docs/deprecations.md), list deprecation codes for each deprecation to serve as a reference for users wanting to disable it.

We'd be more than happy to accept a PR for this improvement :tada: Feel free to reach out if anything is not clear :100:

**Comment by vinothmdev** [comment]
Hello,  I have create a PR for this proposed change.  Please review and let me know if it can be accepted or if any correction required.  This is the first time I am contributing to this project, let me know if I missed anything.

Thank you.
