### ISSUE TITLE
User authenticate with aws lambda, cognito and mongodb

### ISSUE THREAD

**Issue by pchauhan77** [serverless/serverless#8667]
### Use case description

I need a boilerplate with AWS Node.js Lambda, AWS Cognito, JWT, MongoDB (to save user information), Cloudformation for user authentication and authorization

**Comment by pgrzesik** [comment]
Hello @pchauhan77, would you be willing to prepare such a template in form of a Pull Request? We'd be happy to consider such a contribution, but in general, we do not track such template requests as issues on this tracker.

**Comment by sundardsTechMind** [comment]
same issue we are getting (AWS Node.js Lambda, AWS Cognito)
Node version 12
serverless framework  2
AWS SDK version 2.528.0
aws-amplify version 2.1.0

**Comment by pgrzesik** [comment]
@sundardsTechMind What issue are you getting exactly? Could you describe your problem?

**Comment by sundardsTechMind** [comment]
Solved my issue instead of using Cognito-identity.js to AWS service provider for node.js serverless template.

**Comment by pchauhan77** [comment]
May I know GitHub link

**Comment by pgrzesik** [comment]
As it's not bug/feature request related, I'm closing this issue. For similar further requests and conversations, I'd recomment to use forum.serverless.com or Github Discussions. Thanks :bow:
