### ISSUE TITLE
AWS Lambda: Ensure support for image tags in function deploy

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8691]
### Use case description

With https://github.com/serverless/serverless/pull/8683 we've provided support for image tags when full service deployment is concerned, but we missed to ensure same tag to sha resolution for singular function deployments (as made through `sls deploy function`)

### Proposed solution

Ensure that resoluition of `ImageUri` in [`deployFunction.js`](https://github.com/serverless/serverless/blob/3d15223dcd046c35e6b09829c1f9380bd3c3d00c/lib/plugins/aws/deployFunction.js#L215) follows same rules as with regular deployment

**Comment by pgrzesik** [comment]
During testing and discussion together with @medikoo we figured out that deployFunction does not need to resolve imageUri and is currently working correctly.
