### ISSUE TITLE
`provider.kmsKeyArn` and `functions[].kmsKeyArn` are not supported with single function deployment

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8692]
We overlooked with https://github.com/serverless/serverless/pull/8277 that `sls deploy function` has separate function update logic, and over there we still support just old version (`service.awsKmsKeyArn` and `functions[].awsKmsKeyArn`) of properties

(/cc @fredericbarthelet)

### Proposed solution

Update [function update](https://github.com/serverless/serverless/blob/e2802820079a4c0645a87e6ab0d3b9dca6b6bbf8/lib/plugins/aws/deployFunction.js#L106-L110) logic to support new properties in same way as it happens with regular deployment

**Comment by ifitzsimmons** [comment]
@medikoo If it's alright with you, I'd like to take a crack at this

**Comment by medikoo** [comment]
@ifitzsimmons that'll be great. Thank you!

**Comment by pgrzesik** [comment]
It was addressed via: https://github.com/ifitzsimmons/serverless/commit/d67a0ad47b8115a1d7eb6031d3bc7ee66e2e4ad4
