### ISSUE TITLE
`sls deploy`  remove lambda function configuration set in AWS console

### ISSUE THREAD

**Issue by somuch** [serverless/serverless#8702]
⚠️⚠️ `sls deploy` started to remove all the configuration we manually set in lambda function configuration page in AWS console. We have been using the same serverless CLI version without any upgrade for half year. It used to be fine until our last deployment around 22nd of Dec 2020 where all our lambda function settings in AWS console are gone after a `sls deploy`.

I understand that we can set most of the configuration in serverless.yml, but sometimes need to dynamiclly update Env var in AWS console to control the behaviour of a function, without the need to redeploy the code. Now we see all the manually set Env vars are removed after a sls deployment.

It also removes the Timeout value we manually set for each function in different Stage.

It has been causing multiple issues to our services. It would be so much appreciated if this problem can be investigated.

Many thanks! 

<b>Installed version</b>

```
Framework Core: 1.51.0
Plugin: 1.3.11
SDK: 2.3.1
```

**Comment by pgrzesik** [comment]
Hello @somuch, thanks for reporting your issue. I think we will need a little bit more detail. I'm seeing that you're using an older version of the Framework (1.51.0, currently we're on 2.17.0), did you upgrade the Framework version in the meantime, and after that upgrade, you experienced these issues? Would it be possible for you to test out the current version of the Framework to see if the problem appears as well?

**Comment by somuch** [comment]
Hi @pgrzesik , thanks for your comment.
I tried different serverless CLI versions today and they all worked well. I believe that something went wrong before Xmas, but anyhow it has been fixed.

**Comment by pgrzesik** [comment]
Hey @somuch, glad to hear everything is working as expected for you :raised_hands:
