### ISSUE TITLE
Refactor CLI logic as a class

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#871]
Currently we have `utils/cli.js` containing CLI utility methods, and we have a `cli` property on the main serverless instance that contains CLI state information.  

We need a single CLI class that can hold the state information as well as methods for the logic in `utils/cli.js`.  An instance of this class should be kept in the `cli` property of the main serverless instance.

**Comment by flomotlik** [comment]
This is superseeded by #1118 , so I'm closing it
