### ISSUE TITLE
Security vulnerability in axios v0.19.2

### ISSUE THREAD

**Issue by GrantPerkins** [serverless/serverless#8712]
axios v0.19.2 has known Server-Side Request Forgery vulnerability. Should move to v0.21.1

Not applicable.

Not applicable.

Not applicable.

<b>Installed version</b>

Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.17.0 (local)
Plugin: 4.4.1
SDK: 2.3.2
Components: 3.4.3

**Comment by anantsharma1310** [comment]
+1. 
Need an update in SLS module ASAP.

**Comment by agailevictor** [comment]
+ 1
I second that.

**Comment by pgrzesik** [comment]
Thanks for reporting @GrantPerkins, we'll be taking care of it shortly

**Comment by robertfmurdock** [comment]
Anybody have an interim workaround to force the old packages to use the updated axios? Could be useful while we wait.

**Comment by TastefulElk** [comment]
@robertfmurdock You can add a resolution to your package.json as a workaround

```json
  "resolutions": {
    "axios": ">=0.21.1"
  }
```

**Comment by wilhen01** [comment]
@TastefulElk I think that's only available if you're using `yarn`?

For NPM users I _think_ adding `axios` as a direct dependency using the latest version will resolve it, but it's a bit mucky compared to waiting for the resolution from serverless.

**Comment by WillGibson** [comment]
@pgrzesik Are you able to give an indication of when this will be resolved?

Is there anything the rest of us can do to help?

**Comment by pgrzesik** [comment]
@WillGibson Thanks, we aim to release upgraded version tomorrow.

**Comment by pgrzesik** [comment]
Thanks everyone for being patient, we just released `v2.18.0` that should have it resolved.

**Comment by WillGibson** [comment]
Thank you @pgrzesik, I can confirm it's working now.

**Comment by pgrzesik** [comment]
Thanks for reporting back @WillGibson :+1:

**Comment by danielnaab** [comment]
@pgrzesik Will this be back-ported to 1.x?

**Comment by pgrzesik** [comment]
Hello @danielnaab, at the moment there are no plans for that and it is recommended to upgrade to `v2` instead. Is there something that is preventing you from updating to the latest version?
