### ISSUE TITLE
Cant use throttling without quota in API gateway usage plan

### ISSUE THREAD

**Issue by rkaihatu** [serverless/serverless#8717]
2.17

I searched and I didnt find anything related to this

If I set throttle only in usage plan, values are ignored. throttling remains disabled in AWS.

Suggested solution:
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
line: 133
from master branch
commit hash: 66aa66fbfe363edeb4123d709890a7c78f74b571

Minor copy and paste issue, please replace variable quotaProperties by throttleProperties in the if statement
    if (Object.keys(quotaProperties).length) {
      _.merge(template, {
        Properties: {
          Throttle: _.merge(
            { BurstLimit: throttleProperties.burstLimit },
            { RateLimit: throttleProperties.rateLimit }
          ),
        },
      });
    }

<details>
<summary><code>serverless.yml</code></summary>

service:
  name: my-service

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    metrics: true
  apiKeys:
    - testApi:
        - ${opt:stage}-testApi
  usagePlan:
    - testApi:
        throttle:
          burstLimit: 2
          rateLimit: 1

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
  stages:
    - dev

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

Not applicable, no errors in output, configuration is just ignored

</details>

<b>Installed version</b>

Framework Core: 2.16.1
Plugin: 4.4.1
SDK: 2.3.2
Components: 3.4.3

**Comment by pgrzesik** [comment]
Hello @rkaihatu :wave: Thanks for reporting the issue, good catch! We'd be happy to accept a PR with this change. 

Changes:
1. Update logic in line: https://github.com/serverless/serverless/blob/44603830a6c004672da5f8544ba272eed57cdca7/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js#L85
2. Add tests based on `runServerless` that confirm proper values are set for `Throttle`

**Comment by cemenson** [comment]
Hi! I'm looking to make a contribution, would it be OK if I pick this up? I take it the tests to be added are here:
https://github.com/serverless/serverless/blob/44603830a6c004672da5f8544ba272eed57cdca7/test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js

**Comment by pgrzesik** [comment]
Sure @cemenson, we'd love to accept a PR for this one. There are some tests for `Throttle`, but they don't cover a case where `quotaProperties` are not defined, so the bug is not exposed.
