### ISSUE TITLE
Kinesis Event not enabled by default. AWS UI doesn't show the attached events

### ISSUE THREAD

**Issue by neostorm** [serverless/serverless#872]
The Kinesis Event doesn't show up in the UI when created via serverless. 
Serverless docs state enabled is true if enabled isn't provided. It actually deploys as disabled this way. So it looks like nothing was created and it's not working. 
Running "aws lambda list-event-source-mappings" will show you your event and that it's disabled.

I'm not sure if anything can be done about the way it's deployed to fix the ui but being enabled by default would help.

**Comment by kerux2222** [comment]
make sure your event config has "enabled": true (example bellow).

The event not showing on the lambda is an unusual behavior I've seen as well. If you click on 'show aliases' and go to the latest version of your stage there, you should see the event. 

let me know how it goes.

**Comment by eahefnawy** [comment]
Could you make sure you include an `enabled` property set to `true` as @kerux2222 suggested? Also, it won't be shown in the main lambda event sources page, but rather in appropriate stage/alias lambda page. I've experienced this as well and thought it's rather confusing from AWS :/
