### ISSUE TITLE
Command line action to add or remove Serverless variables

### ISSUE THREAD

**Issue by jonathannaguin** [serverless/serverless#873]
All of the Serverless variables are defined inside the _meta/variables folder, which usually is git ignored.

Right now the only way off adding a new variable is editing the JSON file, this file is per stage and region.
For example, s-variables-dev-useast1.json.

For cases where Serverless is invoked from a CI tool or from a IT automation tool, it would be useful to have an Action that allow us to add new variables without having to modify the JSON file directly.

For example:
```
$ serverless variables set -k myVariableKey -v myVariableValue -r us-east-1 -s dev
```
Would create a new variable:

```
{
  "region": "us-east-1",
  "resourcesStackName": "projectName-dev-r",
  "iamRoleArnLambda": "arn:aws:iam::AWSaccount:role/projectName-dev-r-IamRoleLambda-someRole",
  "myVariableKey": "myVariableValue"
}
```

This will make accessible the variable from "${myVariableKey}" from any configuration file.

I have already coded this new action (and another one to unset variables). I am happy to do a PR if it is useful for the community.

Thanks!

**Comment by ac360** [comment]
Love it.  And it sounds like an easy PR... :)

**Comment by kerux2222** [comment]
thanks @jonathannaguin! I'm currently using a gulp task to do something similar. This will be a huge help for us.

**Comment by HyperBrain** [comment]
@ac360 @jonathannaguin I added a `variables list` action that can list the variables in a region/stage or just show them all across all stages and regions with an --all switch. This complements the set/unset pair.
