### ISSUE TITLE
Can't install sls for Apple Silicon M1 McBookAir 

### ISSUE THREAD

**Issue by moadij** [serverless/serverless#8737]
It seems like it isn't possible to install sls on the new macs with the M1 chip. I got this error when I tired to install it:
"Sorry, there's no serverless binary installer available for arm64 architecture."

**Comment by pgrzesik** [comment]
Hello @moadij, thanks for reporting. This is a known problem and we already have a similar issue reported: https://github.com/serverless/serverless/issues/8696 let's keep the whole discussion on the original issue.

**Comment by pgrzesik** [comment]
Duplicate of: #8696
