### ISSUE TITLE
Issues with updating single lambdas when using provisionedConcurrency

### ISSUE THREAD

**Issue by jugglingjsons** [serverless/serverless#8752]
Q1: Describe the issue
When I do changes in the handlers and a full deploy (sls deploy) everything works fine.
When I do sls deploy -f hello the invoked lambda is still the old lambda.

My guess it the mapping betwen the provisionedConcurrency and lambdas doesn't take lambda versioning into consideration. After https://www.serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions

Q2: 
<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    provisionedConcurrency: 1
    events:
      - http:
          path: /test
          method: get
```

</details>

Q3: Not applicable
Q4: Versions
-->

<b>Installed version</b>

```
Framework Core: 2.4.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

I haven't had time to pinpoint it in the code yet, but happy to help if someone is willing to lead, I will have more time to look at this from next Monday 18.01.2021

To reproduce
1. Deploy the provided serverless.yml
2. update the handler code
3. deploy using sls deploy -f hello
4. observe that the responses don't contain your changes

Sorry in advance if that's how it's supposed to work.

**Comment by jugglingjsons** [comment]
Checked what happens after setting
```
  versionFunctions: false
```
The issue persists.

**Comment by pgrzesik** [comment]
Hello @jugglingjsons, thanks for reporting your issue. In fact, at the moment the highlighted use case is not possible. During `deploy function` command, we're only issuing updates to function code and configuration via AWS SDK, while alias is configured to point at a specific version of function via CloudFormation, so any updates only take effect during full deploy. As for supporting it, I will have to consult @medikoo as I'm not sure if we should consider supporting it. What is your opinion on that?

**Comment by jugglingjsons** [comment]
> Hello @jugglingjsons, thanks for reporting your issue. In fact, at the moment the highlighted use case is not possible. During `deploy function` command, we're only issuing updates to function code and configuration via AWS SDK, while alias is configured to point at a specific version of function via CloudFormation, so any updates only take effect during full deploy. As for supporting it, I will have to consult @medikoo as I'm not sure if we should consider supporting it. What is your opinion on that?

For me it would be great if it would work at least in the:
```
  versionFunctions: false
```
scenario.
It's also worth checking if the the provCon lambda can point to some dynamic version - think any package manager. / docker and @latest

**Comment by medikoo** [comment]
`sls deploy function` is currently strictly about update of function _code_ or it's _configuration_ (in sense of AWS function configuration scope).

Provisioned concurrency is configured on _function alias_ which points specific _function version_ and that configuration is beyond _function_ itself.

AFAIK same way `sls deploy function` won't create a new version of a function, when function versioning is turned on (but haven't deeply tested that)

`sls deploy function` is more a _dev_ command that allows to quickly update functions content during development, and should not be used to update production stack (as it also puts CloudFormation stack out of sync). In light of that I also think there's no use case for it to update _provisioned_ functions.

What we probably should do, is to either issue a warning (or throw, if it's about to create a broken setup) whenever user  tries to deploy a function that's either _versioned_ or has _provisioned concurrency_ setup via `sls deploy function`, @pgrzesik what do you think?

**Comment by jugglingjsons** [comment]
> Provisioned concurrency is configured on _function alias_ which points specific _function version_ and that configuration is beyond _function_ itself.

If you want to keep the loose coupling a AWS like resource separation on that I understand, is this the only way forward you see though? For me it's confusing. I mean I get the reasoning, but the configuration seems to be happening within the Function itself in Serverless. Similarly to memorySize - which if I am not mistaken gets updated with
```
sls deploy -f
```
I would say a warning in the output is the least it needs:
```  
lambda:
    handler: handler.process
    timeout: 30
    memorySize: 512
    events:
      - sqs:
          arn: ....
    provisionedConcurrency: 1
```

**Comment by jugglingjsons** [comment]
If I may also drop another question here - this simple template takes a long time to provision this alias - as in the deploy time grows significantly. Is it something I am doing or wrong or is there an explanation for that (that is one of the reasons it would be good to have it working in separation as well , think if you have 20 lambdas with provCon - you won't get updates until you do a full on deployment, you loose the flexibility of per lambda deployment entirely.)

**Comment by medikoo** [comment]
@jugglingjsons Aside of code, these are the properties on AWS side which we may update via `sls deploy function`: https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html

**Comment by medikoo** [comment]
e.g. same way any updates to `events` configurations is not applied in anyway with `sls deploy function`.

What probably be good is to show a permanent notice, indicating that:
- Such deployment puts CF stack out of sync
- Is limited to update only of properties: _...list_
- Advise to do it only for dev purposes and do not practice in production environment

**Comment by jugglingjsons** [comment]
May I ask why not use the abstraction you guys suggest to update more than one AWS resource when there is need to do that? Much as I agree with the CF constraints, we are discussing an abstraction layer here, does it need to respect all the limitations of the target? This is a genuine question, don't read this as any irony please

**Comment by medikoo** [comment]
@jugglingjsons CloudFormation stack should be treated as single source of truth, if it's out of sync, many things can go wrong. The farther we will try to put it out of sync, the weirder issues we may be forced to deal with, and we already have bad experiencies when trying to do updates aside (e.g. it's currently possible to update that way API Gateway stage settings, and there were tens of issues introduced by that)

So, we definitely do not want to introduce other ways to derive deployments further.

I believe that if we stick to CloudFormation deployments, the deployments should be done trhough it. Otherwise best would be to not deploy via CloudFormation at all, and handle everything via AWS SDk directly, and  it's the case with Serverless Components, there's no such problems there.

**Comment by pgrzesik** [comment]
:100: agree with what @medikoo set. At the moment, we're relying on CloudFormation for state management. As soon as we start introducing modifications via other means, we will end up with an inconsistent state that is hard to track.  

As for the improvements, I agree with doing a better job of communicating to users limitations of `deploy function` command :+1:
