### ISSUE TITLE
Configuration warning when defining authorizer via type=custom and authorizerId

### ISSUE THREAD

**Issue by DASPRiD** [serverless/serverless#8769]
When trying to deploy a function with an authorizer defined via `type=custom` and an authorizerId, Serverless' new JSON schema validation will throw a warning:

```
Serverless: Configuration warning:
Serverless:   at 'functions.create.events.0.http.authorizer.type': unsupported configuration format
```

This will not stop the deployment and will actually deploy correctly, so it seems like the schema validation is incomplete. If I see this correctly, it's because those two properties are missing here:

https://github.com/serverless/serverless/blob/cf7b25e4580290f4f6720a46ba4dbecdaf6e13cf/lib/plugins/aws/package/compile/events/httpApi.js#L64-L75

If someone can confirm my assumption, either I or someone else can make a pull request to get those two properties added.

**Comment by pgrzesik** [comment]
Hello @DASPRiD, thanks for submitting your issue. I'd like to unpack a few things here.

1. From the warning message, it seems like you're not using `httpApi`, but rather `http` event, is that correct? The code you linked is for `httpApi` event. 
2. Would you be able to share the sample `serverless.yml` of the setup you're using? (can be dumbed down and of course anonymized) 
3. Did you check https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers for working with custom authorizers? `type: custom` is not a valid setting, I believe `token` is the proper one for what you're trying to achieve here (please correct me if I'm wrong)

**Comment by DASPRiD** [comment]
Ah right, I linked the wrong one, I'm using the http event indeed. There's already an example on the serverless forum by other people with the same issue:

https://forum.serverless.com/t/bug-in-api-gateway-authorizer-schema-for-authorizer-type-custom/13171

They also explain the issue, type TOKEN is for the authorizer function, not for linking authorizers. I suggest reading that thread :)

**Comment by pgrzesik** [comment]
Hello @DASPRiD - thanks a lot, I misunderstood the described case a little bit - thanks for linking the thread, I'll try to get back to you as soon as possible :100:

**Comment by pgrzesik** [comment]
Thanks for being patient @DASPRiD - I just had a chance to properly review this issue. It seems like there's a small issue with the nomenclature used. CUSTOM is a proper type, but it's for `authorizationType`, not for `authorizerType`. It's working as expected (but produces a warning) because it's properly resolved internally https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js#L56 when `authorizerId` is provided. So in such case, the `type` can be totally omitted as the `type` field is not required in schema. Do you feel like we should allow setting it to `CUSTOM` for such cases?

**Comment by DASPRiD** [comment]
I just tried omitting the type and only have the `authorizerId` set an `Fn::ImportValue`. While packing the services, the following error was reported by Serverless:

```
Please provide either an authorizer name or ARN
```

Maybe that's just another bug, but I'd recommend to allow setting the type to CUSTOM, yeah.

**Comment by pgrzesik** [comment]
Hello @DASPRiD, you're correct that in such a situation there will be an error thrown - I think we could support the `CUSTOM` type for `authorizer` to support such cases. @medikoo Do you see anything against that approach?

**Comment by medikoo** [comment]
> @medikoo Do you see anything against that approach?

I looked deeply in the code, and I think it should be fine. Although I'm not 100% sure weather our support for `CUSTOM` authorization type, was fully acklowledged, or works by chance This PR: https://github.com/serverless/serverless/pull/4197 (check comment: https://github.com/serverless/serverless/pull/4197#issuecomment-399546469 ) suggests the later.

Anyway, it looks we can do it, and it'll comply

**Comment by pgrzesik** [comment]
Thanks @medikoo :bow: I've also checked for potential edge cases in the code and I believe we're safe to allow it as `CUSTOM` won't be passed to CF (as we won't attempt to compile an Authorizer Resource).

**Comment by DASPRiD** [comment]
> We'd be more than happy to accept a PR with that adjustment tada

I'd probably make one, If i knew in which file to look for that. On my first go I was unable to locate it.

**Comment by pgrzesik** [comment]
Thanks @DASPRiD :bow: The schema for authorizer is available here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/index.js#L51 

It also would be good to confirm support for authorizer with `custom` type via a new test case. Details on how to write tests are available here: https://github.com/serverless/serverless/blob/master/test/README.md

If you have any other questions, I'm happy to help so please let me know if you need anything :raised_hands:
