### ISSUE TITLE
Invalid "--config" value: config cannot be nested in sub-directory

### ISSUE THREAD

**Issue by matthieudesprez** [serverless/serverless#8800]
The last version of serverless 2.20.0 introduced a bug during our deployment pipeline

```
sls deploy -v -s staging --config serverless/xxx/serverless.yml
```

Invalid "--config" value: config cannot be nested in sub-directory

It seems related to this commit -> https://github.com/serverless/serverless/commit/8451b8908c080bcbe839949d0bf1ae4280a5697a#diff-ee8d960c138001f166279eb4dc6d13bc87071ba32a10ae23e8e1eb93542790a2

**Comment by medikoo** [comment]
@matthieudesprez thanks for reporting.

Configurations by design should not be nested, as all paths in a config are always resolved against service directory.

It's true we didn't crash before on that, but it lead to unexpected config properties resolution behavior. Technically update you list helps expose the issue.

**Comment by matthieudesprez** [comment]
@medikoo thanks for your quick answer.

The project that is currently facing the issue with the last release is a monorepo containing multiple stacks.

During our CI, we deploy them sequentially
```
sls deploy --config serverless/stack_a/serverless.yml
sls deploy --config serverless/stack_b/serverless.yml
...
```

If I understand correctly, we must now have our differents sls configurations at the root of the project ?

**Comment by medikoo** [comment]
> If I understand correctly, we must now have our differents sls configurations at the root of the project ?

Yes, ideally they should have been there since beginning, again note that all paths in service configuration are resolved against service directory.
So e.g. if you've used variable as `${file(./myCustomFile.yml)}` in `./serverless/stack_a/serverless.yml`, it's `./myCustomFile.yml` and not `./serverless/stack_a/.myCustomFile.yml` that was resolved. Same applies to lambda handlers paths etc.

**Comment by matthieudesprez** [comment]
> > If I understand correctly, we must now have our differents sls configurations at the root of the project ?
> 
> Yes, ideally they should have been there since beginning, again note that all paths in service configuration are resolved against service directory.
> So e.g. if you've used variable as `${file(./myCustomFile.yml)}` in `./serverless/stack_a/serverless.yml`, it's `./myCustomFile.yml` and not `./serverless/stack_a/myCustomFile.yml` that was resolved. Same applies to lambda handlers paths etc.

Ok, it's already covered as we are only using absolute path in the configuration files

**Comment by ankon** [comment]
> It's true we didn't crash before on that, but it lead to unexpected config properties resolution behavior. 

We handled that by requiring an environment variable in the configuration that would point to the root directory. 2.20 now broke our deployments. :(

I really think you're walking in the wrong direction here, and rather would have liked to see a behavior that would resolve paths relative to the configuration file -- for "all in one directory" structures that would give the same result, but it would allow also more flexible structures. I cannot find the reasoning for the change anywhere though to expand on our case, please point me to it if you have it at hand.

I suspect I will now try to refactor our deployment structure to get it compliant with this requirement, but probably that will just be a log of copying of content around.

**Comment by medikoo** [comment]
> I cannot find the reasoning for the change anywhere though 

@ankon reasoning is that paths within a service configuration are always resolved against service directory. Therefore putting service configuration anywhere else is confusing, and may produce unexpected behavior.

It's like putting `package.json` in some nested directory of a package.

**Comment by ankon** [comment]
For posterity my current use case:
1. We have a source serverless configuration (using the appsync plugin, using file: variable references)
2. We have the graphql schema and transform that into a "build" directory
3. We copy serverless config etc into that "build" directory
4. We run the serverless deploy using the build/serverless.yml configuration from the root directory (which has the node_modules needed for serverless)

I suspect the new world means I need to link the node_modules into the build directory, and then run serverless from there. 

FWIW: I'm further automating our build right now, so if this is the direction, then it will be that -- but the breakage right now meant that I first needed to fight that fire before focusing back on the automation part.

**Comment by medikoo** [comment]
@ankon I understand you're putting configuration into `<service-path>/build/serverless.yml`. Why not to `<service-path>/serverless/yml` ?

**Comment by jgeurts** [comment]
Much like @matthieudesprez, our structure was mono repo with multiple services and separate config files for each environment (production, review, etc) in each service directory:

```
sls deploy --config ./services/stack_a/production.yml
sls deploy --config ./services/stack_b/production.yml

or

sls deploy --config ./services/stack_a/review.yml
sls deploy --config ./services/stack_b/review.yml
```

The config files sat next to the lambdas they related to. Now having to move those config files to the root seems clunky. So now the root will be full of stack_a_production.yml, stack_a_review.yml, stack_b_production.yml, stack_b_review.yml, etc files, in addition to service folders those relate to. We're on the relative small side but still have ~20 services and multiple environments.

**Comment by ankon** [comment]
> @ankon I understand you're putting service configuration into <service-path>/build/serverless.yml. Why not to <service-path>/serverless.yml ?

Actually that exists, but is "the source". The files in `build` are supposed to be the "processed, ready to deploy" files.

I've been thinking about this a bit now, and I think what I need to do is not to configure the "root" directory through an environment variable, but rather configure the "build" directory. This would then lead to a single `serverless.yml` in the root of the project, which includes the generated snippets from the "build" directory.

From what I gather the idea is to define a "serverless project" as "serverless.yml is in the root, and it has dependencies that should be 'below' that root". Right now the implementation enforces that by saying that serverless.yml must be in cwd(), and node_modules etc must be in cwd() as well.
This requirement however isn't needed for the definition, it's just one way of trying to enforce it. You can also go and reverse it: Whereever `serverless.yml` is, must be the root, and therefore relative paths inside it must be relative to that root.

**Comment by marcelomarra** [comment]
Same here as @jgeurts and @matthieudesprez, we use an internal generic Serverless as a component for all different applications.

For me it seems like a breaking change. Projects that use that pattern would be impossible to update to 2.2.0 and above.

**Comment by Srujankumar99** [comment]
Downgraded the serverless version to 20.18.0 and I was able to resolve the issue

**Comment by medikoo** [comment]
Thanks for the feedback!

As it's affecting a lot of projects, tomorrow we will release a patch, that ensures Framework no longer crashes in such case, and behaves as before.

Instead we will issue a deprecation warning, to indicate we will bring strict handling with a new major release

**Comment by medikoo** [comment]
> Much like @matthieudesprez, our structure is a mono repo with multiple services and separate config files for each environment (production, review, etc) in each service directory:

@jgeurts thanks for explanation. Still in such case how to do you configure paths in service config, e.g. handlers for lambda?

I assume that e.g. for `./services/stack_a/serverless.yml` service, if you keep lambdas configured in `./services/stack_a/` the handlers need to be referenced with full path to that directory, as below:

```yaml
functions:
  function:
    handler: services/stack_a/path-to-handler.handler
```

Or do you rely on some custom packaging that sorts that out?

**Comment by jgeurts** [comment]
> @jgeurts thanks for explanation. Still in such case how to do you configure paths in service config, e.g. handlers for lambda?
> 
> I assume that e.g. for `./services/stack_a/serverless.yml` service, if you keep lambdas configured in `./services/stack_a/` the handlers need to be referenced with full path to that directory, as below:
> 
> ```yaml
> functions:
>   function:
>     handler: services/stack_a/path-to-handler.handler
> ```

Yep, the handler path is relative to the root of the project. Package excludes are also relative to the root of the project. Instead of preventing or deprecating the usage of a nested config, could there be a documentation note for that case to clarify things for others trying the same?

**Comment by medikoo** [comment]
>  Instead of preventing or deprecating the usage of a nested config, could there be a documentation note for others trying to use a nested config?

We had reports from users being confused that for nested configurations paths are still being resolved against root of a service. e.g. it can be surprising to find that references as `${file(./some-path)}` go down to `../../some-path`

It's the reason we consider a nested configurations an anti-pattern, and I believe it'll save us all trouble if we just practice service root configurations.

@jgeurts Why exactly it is problematic to put service configurations at root of a service?

**Comment by jgeurts** [comment]
As mentioned previously, we would like to keep the serverless config files contextually next to the functions they are associated with. Mashing all service config files to the root of the project precludes this. 

It sounds like the recommended migration and future approach would be to have multiple serverless projects, rather than a single project with service sub directories, is that accurate?

**Comment by medikoo** [comment]
> It sounds like the recommended migration and future approach would be to have multiple serverless projects, rather than a single project with service sub directories. Is that a valid assessment?

If in your case, there's nothing that services need from root folder. Then technically should assume that their individual folders are service folders and do deployments from there

**Comment by jgeurts** [comment]
I feel like I ran into issues with trying to deploy serverless from a sub directory rather than the project directory. Maybe plugins didn't load correctly or dependencies weren't bundled properly - I don't remember anymore. I give it another shot, though!

If this change is purely from new user confusion when setting up a project, I would rather see the documentation be augmented rather than deprecate and disable nested configs. As I mentioned, we have ~20 services and its not hard to imagine others with much more. With nested configs being deprecated, I will now need to maintain 20 copies of package.json, typescript config, test config, and lint & style config files, rather than one.

**Comment by medikoo** [comment]
> I feel like I ran into issues with trying to deploy serverless from a sub directory rather than the project directory. Maybe plugins didn't load correctly or dependencies weren't bundled properly - I don't remember anymore. I'll give it another shot, though!

Yes, in that case all things that service depend on (like plugins and dependencies) also need to be installed into service directory. Service cannot rely on things in parent folders.
