### ISSUE TITLE
`serverless print` is useless because warnings/errors are written to stdout

### ISSUE THREAD

**Issue by ankon** [serverless/serverless#8808]
I'm trying to use `serverless print` to further process information from the stack. Ultimately I need the outputs of the stack, in my program, and I cannot (for the purpose of this issue) control the contents of the serverless configuration.

I'm trying to use `serverless print` therefore to get either the stack name, or the service/stage fields to guess it myself.

This is unfortunately a hard problem, because the `serverless` CLI prints warnings, informational messages, and errors onto stdout, so I am not able to learn where exactly the output I care about is, and which lines/bytes(?) I can ignore.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice
provider:
  region: eu-west-1

custom:
  value: ${opt:value}
```

</details>

<details>
<summary><b><code>npx serverless print --path provider --format json 2>/dev/null</code> output</b></summary>

```
 
 Serverless Warning --------------------------------------
 
  A valid option to satisfy the declaration 'opt:value' could not be found.
 
{
  "stage": "dev",
  "region": "eu-west-1",
  "variableSyntax": "\\${([^{}:]+?(?:\\(|:)(?:[^:{}][^{}]*?)?)}"
}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

**Comment by ankon** [comment]
Work-around I'm going to try is to print the whole file as JSON, and hope that warnings are not appearing intermixed but just at the beginning -- in other words, as soon as a I find a `{` as single character on a line, I know that the JSON output starts.

**Comment by pgrzesik** [comment]
Thanks for reporting that @ankon, we're aware of that issue and it was reported previously: https://github.com/serverless/serverless/issues/8656 

We also have to initiatives open that should allow to `print` with all warnings and errors disabled:
- https://github.com/serverless/serverless/issues/8731
- https://github.com/serverless/serverless/issues/1720

For now I'm going to close this one, if you have suggestions on that topic please contribute them to one of the existing issues. :bow:
