### ISSUE TITLE
Runtime._processExcludePatterns excludes project files

### ISSUE THREAD

**Issue by krzysu** [serverless/serverless#881]
something is wrong with your regex to exclude project files from deployment, as it also excludes function files that matches 'meta' or 'env', see below:

Serverless: Deploying functions in "development" to the following regions: eu-west-1  
  serverless:lib.node_modules.serverless.lib.Runtime "development - eu-west-1 - get": Copying in dist dir /home/user/project/_meta/_tmp/get@1458810727534 +13ms
  serverless:lib.node_modules.serverless.lib.Runtime "development - eu-west-1 - get": **Excluding** - /home/user/project/function/node_modules/aws-sdk/lib/credentials/ec2**_meta**data_credentials.js +43ms
  serverless:lib.node_modules.serverless.lib.Runtime "development - eu-west-1 - get": **Excluding** - /home/user/project/function/node_modules/os**env** +105ms
Serverless: \   serverless:lib.node_modules.serverless.lib.actions.CodeDeployLambda "development - eu-west-1 - function-get": Compressed file created - /home/user/project/_meta/_tmp/get_development_eu-west-1.zip +6s

**Comment by ac360** [comment]
Thanks for finding this @krzysu.

**Comment by minibikini** [comment]
Fixed by 45e64a94f824e2125d2969595f0c9e3d6517b670 and dc5011c19d74d90f1099368a1068851523445b6e (#889)
