### ISSUE TITLE
Serverless validation false warning on stackTags with tag names including hyphens

### ISSUE THREAD

**Issue by lindseycarriere** [serverless/serverless#8811]
I noticed a configuration validation warning when moving from serverless 1.70 to 2.20.1.

When declaring:

`
provider:
  stackTags:
    product-id: widget
`

> Serverless: Configuration warning at 'provider.stackTags': unrecognized property 'product-id'

Note if using a (:) like **company:product: widget**, this validates which is good.  Just the hyphen in the tag name throws the warning.

[AWS tagging best practices](https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf) suggest using lowercase hyphenated tag names. 

Would like to allow this convention in the validator as this tag schema works.

**Comment by pgrzesik** [comment]
Hello @lindseycarriere, thanks for reporting. We already have a similar issue reported: https://github.com/serverless/serverless/issues/8764 and there's a PR pending with a solution for that: https://github.com/serverless/serverless/pull/8766.

I'm going to close that issue and if there's still anything to discuss, please move that discussion to linked issue. Thanks :bow:
