### ISSUE TITLE
serverless stage create does not work

### ISSUE THREAD

**Issue by BryanCrotaz** [serverless/serverless#8820]
Followed instructions here:
https://serverless.readme.io/docs/commands-overview

`serverless stage create -s dev -r us-east-1`

```
Serverless Error ---------------------------------------

  Serverless command "stage" not found. Did you mean "create"? Run "serverless help" for a list of all available commands.
```

The docs and the code appear to be out of sync.

**Comment by pgrzesik** [comment]
Hello @BryanCrotaz, these are very outdated docs for version `0.5.0`, please follow the documentation available under: https://www.serverless.com/framework/docs/

**Comment by BryanCrotaz** [comment]
Can I suggest that you delete them then or replace with a redirect to the current docs?
They are high up in google ranking.

**Comment by pgrzesik** [comment]
Sure thing, I've already reached out about that. Thanks @BryanCrotaz :bow:

**Comment by pgrzesik** [comment]
Just an update - we've provided extra information about the docs being only for older versions on serverless.readme.io. Thanks once again for reporting that :bow:
