### ISSUE TITLE
Serverless deploy command with --packagePath parameter gives "Could not find serverless service definition file."

### ISSUE THREAD

**Issue by antoniogiordano** [serverless/serverless#8833]
I'm trying to deploy a service as I always did with previous SLS versions, but now it stopped working with last one.
These are the commands:

`
serverless --config serverless-services/shared.json package --package ../.serverless-output --stage prod
serverless --config serverless-services/shared.json deploy --package ../.serverless-output --stage prod
`

Even without specyfing a package path at all, package works, deploy fails!

My shared.json file didn't change, only SLS version changed from 2.16.0 to the latest one! (2.21.0)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
serverless --config serverless-services/shared.json deploy --package ../.serverless-output --stage prod
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Prune: myapp-shared-prod-cognito has 0 additional versions published and 0 aliases, 0 versions selected for deletion
Serverless: Prune: myapp-shared-prod-_serverless-mongo-proxy has 0 additional versions published and 0 aliases, 0 versions selected for deletion
Serverless: Prune: Pruning complete.
Serverless: Invoke aws:deploy:finalize
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 0.442s 0 retries] getCallerIdentity({})
Serverless: Publishing service to the Serverless Dashboard...
Error: Could not find serverless service definition file.
    at getServerlessFilePath (/Users/antoniogiordano/.nvm/versions/node/v12.20.0/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/getServerlessFilePath.js:20:13)
    at parseDeploymentData (/Users/antoniogiordano/.nvm/versions/node/v12.20.0/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:28:30)
    at /Users/antoniogiordano/.nvm/versions/node/v12.20.0/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/errorHandler.js:20:24
    at /Users/antoniogiordano/.nvm/versions/node/v12.20.0/lib/node_modules/serverless/scripts/serverless.js:82:9

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.0
     Framework Version:         2.21.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.5.1

```

</details>

<b>Installed version</b>

```
Framework Core: 2.21.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1

```

**Comment by medikoo** [comment]
@antoniogiordano thanks for reporting. Indeed there's a bug when processing nested service configuration. It'll be fixed shortly.

Still, please notice that using nested configurations is deprecated and will no longer be supported with v3

**Comment by antoniogiordano** [comment]
Thanks @medikoo ! What do you mean by nested configurations? Config files in subfolders? Or config files sharing AWS references?

**Comment by medikoo** [comment]
> What do you mean by nested configurations? Config files in subfolders

@antoniocaiazzo exactly that. Check https://www.serverless.com/framework/docs/deprecations#service-configurations-should-not-be-nested-in-service-sub-directories

**Comment by antoniogiordano** [comment]
Ok great thank you @medikoo
