### ISSUE TITLE
Ability to specify a version in standalone installer

### ISSUE THREAD

**Issue by alegonz** [serverless/serverless#8855]
### Use case description

It would be helpful to have the ability to install a specific version of serverless when using the standalone installer. This is useful for reproducibility, e.g. if you use it as part of your CI workflow, or when you are on-boarding a new teammate and want to make sure they use the same version as others.

### Proposed solution
This could be achieved by setting a `VERSION` variable

```bash
curl -o- -L https://slss.io/install | VERSION=X.Y.Z bash
```

or perhaps passing it as an argument (though it results in a bit longer command)

```bash
curl -o- -L https://slss.io/install | bash -s -- --version X.Y.Z
```

If the above sounds sensible I could throw a PR. I'd be glad to contribute :)

**Comment by pgrzesik** [comment]
Hello @alegonz, thanks a lot for submitting your request. I believe it makes sense to support specifying version exactly for the use cases you mention. 

@medikoo Do you see any objections to supporting specifying version for standalone installer?

**Comment by medikoo** [comment]
@alegonz @pgrzesik I think it's a very good idea. Thanks for bringing this up!

**Comment by alegonz** [comment]
@pgrzesik @medikoo 
Thank you!
I'll work on a PR and get back to you once I get it working.

**Comment by medikoo** [comment]
Thank you @alegonz !

**Comment by alegonz** [comment]
Hi again,

It seems the latest version of the script is not available from `https://slss.io/install`. [The docs seem to reflect the latest version though](https://www.serverless.com/framework/docs/getting-started#macoslinux).

Did I miss to update a CI deploy rule or something?

**Comment by medikoo** [comment]
@alegonz Thanks for pinging. Indeed this script is not updated automatically at it's location. I've just updated it, and now latest version should be resolved

**Comment by alegonz** [comment]
@medikoo 
I could confirm the new script from my side. Thank you!
