### ISSUE TITLE
Parent s-resources-cf.json file and subfolders s-resources-cf.json files are not merged together

### ISSUE THREAD

**Issue by martinmicunda** [serverless/serverless#888]
I have upgraded my project to `v0.5.0` and if I define `s-resources-cf.json` files in multiple folders they are not merged together.  The `_meta/resources` file only contains parent CloudFormation however subfolders CloudFormation are missing (NOTE: this used to work in `v0.4.x`).

*This is my project structure:*
```
|-function1
   |-s-resources-cf.json
|-function2
|-s-resources-cf.json 
|-s-project.json 
```

**Comment by eahefnawy** [comment]
@martinmicunda As of Serverless v0.5 we removed the nested resources functionality, and instead built the foundational work for supporting multiple resource stacks per project, but it's not finished yet.

Really sorry for the confusion there :blush:
