### ISSUE TITLE
Cannot specify name of default AWS IAM Role

### ISSUE THREAD

**Issue by matthewpoer** [serverless/serverless#8887]
### Use case description

Currently the default AWS IAM Role is named with a static naming convention that cannot be customized,

https://github.com/serverless/serverless/blob/61dd3bde8d17cdd995fdd27259a689d12bee1e42/lib/plugins/aws/lib/naming.js#L93-L105

It would be beneficial to many projects to provide a name (e.g. the service name and/or stage name combine to a long string, opening potential issues with the AWS Role name length limit of 64 characters. 

Allowing the name to be customized would solve the issue as reported in #4918, #2856.

Similar solutions appear to have been proposed and either disagreed on or otherwise abandoned (#7821).

### Proposed solution

Introduce a **new** configuration item `provider.iamRoleName` to allow for specifying a name other than the default generated one.

The new item would should be backwards-compatibile as it will be optional and continue to default to the existing name scheme.

**Comment by matthewpoer** [comment]
This differs from previous issues filed in that it has a concrete proposal _and_ will be accompanied by a pull request shortly.

**Comment by pgrzesik** [comment]
Hello @matthewpoer, as I described in corresponding PR I believe it should wait before we finalize https://github.com/serverless/serverless/issues/8681

**Comment by pgrzesik** [comment]
Hello @matthewpoer - issue that moves all iam-related properties under a single namespaces has been closed: https://github.com/serverless/serverless/issues/8681 which means that this issue can be unblocked :100:

**Comment by matthewpoer** [comment]
Thanks @pgrzesik , I've just rebased that branch from serverless/master and I think it's ready for your review

**Comment by PatrykMilewski** [comment]
Hey, I'm also waiting for this one, because the default generated role name is invalid in our case. It doesn't include full stack name, which causes name collision with stacks, that have the same service and stage name.

@matthewpoer Could you open the PR?

**Comment by pgrzesik** [comment]
Thanks for bumping that issue @PatrykMilewski - I've missed the update and I've just added a comment on the PR.

**Comment by Borduhh** [comment]
Waiting for this to be released. Any idea when a new minor will be cut?

**Comment by pgrzesik** [comment]
Hey @Borduhh - no exact date but I believe that it will be released either this week or at the beginning of next one.

**Comment by mrowles** [comment]
I cannot find out if this has gone into a release or not yet, is it this one? https://github.com/serverless/serverless/releases/tag/v2.43.0 @pgrzesik
