### ISSUE TITLE
Support of NodeJs 14 runtime

### ISSUE THREAD

**Issue by stefan-rode** [serverless/serverless#8893]
### Use case description

AWS announced that the Lambda 14 runtime is available: https://aws.amazon.com/about-aws/whats-new/2021/02/aws-lambda-now-supports-node-js-14/

### Proposed solution

Would be nice if the NodeJs 14 runtime is also supported by the Serverless Framework.

**Comment by pgrzesik** [comment]
Hello @stefan-rode, we would definitely like to support Node 14 - it should be a fairly small change and we'd be happy to accept a PR for that :100:

**Comment by pgrzesik** [comment]
It's closed via: https://github.com/serverless/serverless/pull/8894
