### ISSUE TITLE
Non-actionable deprecation documentation

### ISSUE THREAD

**Issue by BryanCrotaz** [serverless/serverless#8895]
```
Serverless constructor config.configuration requirement
Deprecation code: MISSING_SERVICE_CONFIGURATION

Serverless constructor was refactored to depend on service configuration being resolved externally and passed to its constructor with config.configuration. Starting from v3.0.0 configuration will not be resolved internally.
```

Questions not answered by the documentation:
1. what is the "service configuration"? serverless.yaml?
2. how do I pass anything to the serverless constructor? I'm not constructing a serverless instance in my code.
3. where do I find `config.configuration` and what do I have to put there?

Guessing...

It needs a path to `serverless.yaml`. But that's where I put configuration, so if I add 
```yaml
config:
  configuration: something??
```
and that somehow tells serverless where to find my serverless.yaml, how did it load it in the first place?

**Comment by medikoo** [comment]
@BryanCrotaz thanks for report. This deprecation is a bug that was mostly fixed with https://github.com/serverless/serverless/pull/8864 (published with last release).

It can happen when you're using older global version with more recent service local version of a Framework (Upgrading the local installation of `serverless` to latest should be good enough to make this deprecation gone)

**Comment by BryanCrotaz** [comment]
That wasn't the point. The documentation is meaningless to anyone other than a member of the internal serverless team.

**Comment by medikoo** [comment]
@BryanCortaz This deprecation is intended for the user that attempts to use Framework (`Serverless` constructor) programmatically, and I think in this context is meaningful enough.

Note that wee do not document and promote anywhere, as Framework at current shape was not designed to used programmaticaly (although that's likely to change in a future), still we decided to not be breaking here, just in case.

**Comment by BryanCrotaz** [comment]
Well I'm getting the deprecation message by just running sls deploy and I still have no idea what it means I have to do.

**Comment by medikoo** [comment]
> Well I'm getting the deprecation message by just running sls deploy and I still have no idea what it means I have to do.

Yes, as I [mentioned above](https://github.com/serverless/serverless/issues/8895#issuecomment-773403258) it's due to a bug, that was fixed with latest release.

**Comment by BryanCrotaz** [comment]
ok, so maybe update the documentation to say that? and what to do about it?

**Comment by medikoo** [comment]
> ok, so maybe update the documentation to say that? and what to do about it?

We do not document bugs in main documentation. Technically this issue serves perfectly as that I believe

**Comment by BryanCrotaz** [comment]
I'm not asking you to document the bug. Just to tell the poor sucker that hits the problem what to do about it. 

Eg "this is a bug in version x.xx which was fixed in y.yy. Upgrade to y.yy to get rid of the warning. "
Simples.

**Comment by medikoo** [comment]
> I'm not asking you to document the bug. Just to tell the poor sucker that hits the problem what to do about it.

Best way is to search the presented deprecation code, I'm pretty sure this discussion will pop-up, providing necessary explanation

Let me close this issue, as I don't think we can add any new valuable information here.

**Comment by BryanCrotaz** [comment]
All I'm asking is that you add one sentence to the deprecation message! It contains a link to the documentation - why should the developer have to search through source code and forums, when the link provided by you isn't informative?
