### ISSUE TITLE
No S3 Project Bucket

### ISSUE THREAD

**Issue by aliatsis** [serverless/serverless#890]
The Serverless docs explain that an S3 "Project Bucket" should be created in AWS along with the serverless project. I've created a project and deployed a few lambda functions. The lambda functions make it into AWS fine, but I am not seeing any new S3 bucket. My user account has AdministratorAccess, so it can't be the bucket permissions.

Is the Project Bucket still a thing?

**Comment by ac360** [comment]
Hi @aliatsis,  project buckets have been removed in `v0.5`.  We clearly need to update our docs!  Sorry about the confusion here.

**Comment by pmuens** [comment]
@ac360 I've just read over the docs and submitted some changes recently (The change about the S3 bucket removal is also submitted).

**Comment by ac360** [comment]
@pmuens Thanks :)  I believe these were added in a day ago too.  I wonder where @aliatsis is reading about the project bucket.

**Comment by c-knowles** [comment]
There's a few references to a `-b <bucket>` parameter still in the 0.5.0 docs.

**Comment by ac360** [comment]
Thanks @c-knowles :)

**Comment by aliatsis** [comment]
The docs I was reading were found through the Documentation link on the readme. The docs are updated now. Thanks for the help!
