### ISSUE TITLE
Cant deploy nodejs runtime with v14x

### ISSUE THREAD

**Issue by MeRahulAhire** [serverless/serverless#8906]
currently the sls framework is giving me option unto NodeJS v12 and it doesn't gets deployed with latest 14th version with now AWS is supporting. So, could you please update the framework to support the latest stable version of NodeJS for aws?

**Comment by pgrzesik** [comment]
Hello, this has already been addressed by: https://github.com/serverless/serverless/pull/8894 and you can expect a release in the coming days.
