### ISSUE TITLE
@jer-sen Technically we support only `true`, as we want to remove this setting starting with new major (without ability to turning off `.env` auto load behavior)

### ISSUE THREAD

**Issue by wchizm83** [serverless/serverless#8907]
@jer-sen Technically we support only `true`, as we want to remove this setting starting with new major (without ability to turning off `.env` auto load behavior)

In `serverless.yml` we list it to document it, but by convention we also show default setting, `false` is to kind of express  the default (still real default is lack of this setting, technically we could express ith with `null`)

_Originally posted by @medikoo in https://github.com/serverless/serverless/issues/8566#issuecomment-736844761_

**Comment by pgrzesik** [comment]
Looks like an issue opened by mistake, I'm closing it - if you feel like you want to report something, please use our standard template and describe your problem. Thanks
