### ISSUE TITLE
sls event remove --all not working

### ISSUE THREAD

**Issue by kerux2222** [serverless/serverless#891]
removing events by name works as expected. however, when the --all option is on, the following error occurs (--debug included). 

Command ran: serverless event remove -s ainacio -r us-east-1 --all --debug

> serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/s-project.json... +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ProjectCreate.js +272ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ProjectCreate plugin loaded +4ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ProjectInstall.js +5ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ProjectInstall plugin loaded +19ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ProjectInit.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ProjectInit plugin loaded +4ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionRun.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionRun plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionCreate.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionCreate plugin loaded +4ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionDeploy.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionDeploy plugin loaded +6ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/CodePackageLambda.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.CodePackageLambda plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/CodeDeployLambda.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.CodeDeployLambda plugin loaded +70ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EndpointDeploy.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointDeploy plugin loaded +4ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointBuildApiGateway plugin loaded +11ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventDeploy.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventDeploy plugin loaded +3ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventLambdaStream.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventLambdaStream plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventLambdaS3.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventLambdaS3 plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventLambdaSNS.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventLambdaSNS plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventLambdaSchedule.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventLambdaSchedule plugin loaded +3ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/DashDeploy.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.DashDeploy plugin loaded +7ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/DashSummary.js +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.DashSummary plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointDeployApiGateway plugin loaded +6ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/StageCreate.js +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.StageCreate plugin loaded +4ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/RegionCreate.js +8ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.RegionCreate plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ResourcesDeploy plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ResourcesRemove.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ResourcesRemove plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/RegionRemove.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.RegionRemove plugin loaded +3ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/StageRemove.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.StageRemove plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ProjectRemove.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ProjectRemove plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionLogs.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionLogs plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/ResourcesDiff.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.ResourcesDiff plugin loaded +11ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/PluginCreate +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.PluginCreate plugin loaded +3ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionRemove.js +0ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionRemove plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventRemove.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EventRemove plugin loaded +2ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EndpointRemove.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.EndpointRemove plugin loaded +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/FunctionRollback.js +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless serverless.core.FunctionRollback plugin loaded +11ms
>   serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/ainacio/dev/lambda/logging-service/node_modules/serverless-optimizer-plugin +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless com.serverless.ServerlessOptimizer plugin loaded +309ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/s-project.json... +10ms
>   serverless:lib.node_modules.serverless.lib.Serializer deserializeProject: Load functions +4ms
>   serverless:lib.node_modules.serverless.lib.Serializer deserializeProject: Load function: /Users/ainacio/dev/lambda/logging-service/functions/log-digester/s-function.json +30ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-digester/s-function.json... +0ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-digester/s-function.json... +6ms
>   serverless:lib.node_modules.serverless.lib.Serializer deserializeProject: Load function: /Users/ainacio/dev/lambda/logging-service/functions/log-entry-post/s-function.json +1ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-entry-post/s-function.json... +0ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-entry-post/s-function.json... +2ms
>   serverless:lib.node_modules.serverless.lib.Serializer deserializeProject: Load function: /Users/ainacio/dev/lambda/logging-service/functions/log-search-options/s-function.json +2ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-search-options/s-function.json... +0ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-search-options/s-function.json... +0ms
>   serverless:lib.node_modules.serverless.lib.Serializer deserializeProject: Load function: /Users/ainacio/dev/lambda/logging-service/functions/log-search-post/s-function.json +1ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-search-post/s-function.json... +0ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/functions/log-search-post/s-function.json... +1ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/_meta/variables/s-variables-common.json... +1ms
>   serverless:lib.node_modules.serverless.lib.utils.index Reading file: /Users/ainacio/dev/lambda/logging-service/s-resources-cf.json... +1ms
>   serverless:lib.node_modules.serverless.lib.Serverless CLI raw input:  +2ms { _: [ 'event', 'remove' ],
>   s: 'ainacio',
>   r: 'us-east-1',
>   all: true,
>   debug: true }
>   serverless:lib.node_modules.serverless.lib.Serverless CLI processed input:  +2ms { context: 'event',
>   action: 'remove',
>   options: { stage: 'ainacio', region: 'us-east-1', all: true },
>   params: { names: [] },
>   raw:
>    { _: [ 'event', 'remove' ],
>      s: 'ainacio',
>      r: 'us-east-1',
>      all: true,
>      debug: true } }
> /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
>         fn = function () { throw arg; };
>                            ^
> 
> ServerlessError: Stage is required
>     at new ServerlessError (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Error.js:17:11)
>     at EventRemover._validateAndPrepare (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventRemove.js:167:15)
> From previous event:
>     at EventRemover.eventRemove (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventRemove.js:95:10)
>     at Function.run (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventRemove.js:83:22)
>     at EventRemove.eventRemove (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EventRemove.js:65:27)
> From previous event:
>     at /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:181:31
>     at Array.reduce (native)
>     at /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:180:32
> From previous event:
>     at Serverless._execute (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:178:12)
>     at Serverless.actions.(anonymous function) (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:424:20)
>     at Serverless.command (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:393:38)
>     at /Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/bin/serverless:19:16
>     at processImmediate [as _immediateCallback] (timers.js:383:17)
> From previous event:
>     at Object.<anonymous> (/Users/ainacio/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/bin/serverless:18:4)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Function.Module.runMain (module.js:467:10)
>     at startup (node.js:136:18)
>     at node.js:963:3

**Comment by eahefnawy** [comment]
@kerux2222 I can't reproduce this issue. `sls event remove --all` works fine with me. Are you sure the stage name you're passing exists in the project?

**Comment by kerux2222** [comment]
@eahefnawy I was able to narrow down the issue to the fact that I was running the command after clearing out my _meta variables (effectively removing the deployed event ID).
If the intended behavior is to remove all events listed in the _meta vars,  we can go ahead and close this. However, if the action is intended to remove all currently deployed stage events from AWS, we may need some extra functionality to list out the current stage events from AWS and than delete them.

**Comment by eahefnawy** [comment]
We use variables to keep track of which events were deployed with Serverless. If we list and delete stage events that will result in also deleting any other events that are configured for your lambda.
