### ISSUE TITLE
Lambda - Docker CMD override not applying

### ISSUE THREAD

**Issue by dmacdo02** [serverless/serverless#8919]
I'm utilizing the new docker command override fields. I set it to my custom handler.
However - the lambda logs saying the handler is not found.
Going into the lambda UI, the value IS set to the correct value.
Clicking edit and save in the UI makes it work.

![image](https://user-images.githubusercontent.com/5991853/107417231-5ae4da00-6ae3-11eb-8867-a0802a2cc0f8.png)
^Shows correct value

![image](https://user-images.githubusercontent.com/5991853/107417294-6e904080-6ae3-11eb-9e65-b38ecbc9021d.png)
^doesn't work though until I press "Edit" and "Save" (not changing any values)

Cloudwatch logs until I press edit and save:
`IMAGE Launch error: Couldn't find valid bootstrap(s): [my/awesome/thing.handler] Entrypoint: [] Cmd: [my/awesome/thing.handler] WorkingDir: [/var/task] `

<details>
<summary><code>serverless.yml</code></summary>

```yaml
  myFunction:
    image:
      name: myImage
      command: my/awesome/thing.handler
```

</details>

<details>
<summary><b><code>sls deploy -s <stage></code> output</b></summary>

</details>

<b>Installed version</b>

```
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.2
```

**Comment by pgrzesik** [comment]
Hello @dmacdo02, thanks for reporting. This is a limitation of CloudFormation at this point - when deploying you should see either a warning about missing `image.entryPoint` or there should be an error if you're using `configValidationMode: error`. Could you please post full output of `sls deploy`? 

Additionally, there's a note about that in our docs: https://www.serverless.com/framework/docs/providers/aws/guide/functions/#referencing-container-image-as-a-target

As soon as CloudFormation announces better support, it will be possible to override command without having to specify `entryPoint` as well.

**Comment by dmacdo02** [comment]
Sorry for the oversight - Thank you for the feedback and I'll give that a shot explicitly defining the entrypoint.

**Comment by pgrzesik** [comment]
No worries :100: It's definitely annoying that it's currently not possible to specify just `command` via CloudFormation as it's clearly possible to do via UI console - hopefully that will be addressed soon :crossed_fingers:

**Comment by dmacdo02** [comment]
Found the Orange text warning me about it:
Serverless:   at 'functions.<functionanem>.image': should have property entryPoint when property command is present

Was just lost in a sea of orange as we have other things that populate tonnes of orange text that still lets us deploy happily.
You did all the right things :) 

Thanks again for the very fast response and this feature! :)

**Comment by dmacdo02** [comment]
Would it make sense if `command` is provided but no `entrypoint` is provided that we assume the `entrypoint` override and set it to the default?

That would enable the interface to be what we want and the end result be hopefully what we want.

**Comment by pgrzesik** [comment]
Hello @dmacdo02 - that would be perfect and it was under consideration, the problem with that approach is that we don't know the default `entrypoint` for images that are not based on official AWS images and we cannot make that assumption because it will introduce a whole new class of errors for people with fully custom images. :(
