### ISSUE TITLE
Function deploy with invalid stage fails but doesn't exit with error

### ISSUE THREAD

**Issue by haack** [serverless/serverless#893]
Attempting to deploy with an invalid stage will fail however the exit status doesn't indicate so. Could be a problem for CI tool's that try to deploy automatically.

E.g:
```
$ sls function deploy -a --stage stagethatdoesntexist
...
Serverless: Failed to deploy...
...
$ echo $?
0
```

**Comment by HyperBrain** [comment]
Duplicate of #773

**Comment by ac360** [comment]
Closing because this is aduplicate
