### ISSUE TITLE
Add support for arm64 architecture

### ISSUE THREAD

**Issue by maks-avana** [serverless/serverless#8930]
<!--
Q1: Describe the problem (use case) that needs to be solved
Installation on Mac mini 2020 throwing error message 'Sorry, there's no serverless binary installer available for arm64 architecture. Please open request for it at https://github.com/serverless/serverless/issues'.

### Use case description

Description is stated as above.

### Proposed solution

Please add support for arm64 architecture

**Comment by pgrzesik** [comment]
Hello @maks-avana - could you provide a bit more details about what exactly you have in mind? Serverless Framework should work without any issues on `arm64` - I'm personally using it from time to time on `aarch64` device (Jetson Xavier NX) and it works just fine, similarily, it should work without any issues on machines with AWS Graviton(2) CPUs as well. If you're referring to having an option for a binary installer for M1 Macs, please refer to this issue. https://github.com/serverless/serverless/issues/8696

**Comment by bm-are** [comment]
Running the install command gets this prompt:

```
$ curl -o- -L https://slss.io/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    339      0 --:--:-- --:--:-- --:--:--   339
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3897  100  3897    0     0   1410      0  0:00:02  0:00:02 --:--:--  2099

 Installing Serverless!

\033[31m Sorry, there's no serverless binary installer available for arm64 architecture. Please open request for it at https://github.com/serverless/serverless/issues.\033[0m
```

I'm running macOS Big Sur v11.1, 2020 MacBook Pro with M1 (which is what's causing the issues)

**Comment by bm-are** [comment]
@maks-avana according to https://github.com/serverless/serverless/issues/8696 if you also have the same issue on a Mac then you'd need to just run the Terminal in Rosetta mode

**Comment by mark-brooks-roostify** [comment]
Agreed.  Given how many devs us M1 Macs there's no reason to not support ARM64.

**Comment by mnapoli** [comment]
It seems to me that we could close this in favor of #8696?

**Comment by pgrzesik** [comment]
Yes @mnapoli - it seems like it's only about providing a standalone binary for `arm64` architecture :+1: I'm closing it and let's continue discussing in #8696
