### ISSUE TITLE
CI/CD GitHub App installation URL redirects to a 404

### ISSUE THREAD

**Issue by benlongmire** [serverless/serverless#8940]
When connecting a GitHub account in "ci/cd" section of https://app.serverless.com/ the redirect URL is incorrect.

**Current behaviour:**
After authorizing your account, you are redirected to https://github.com/apps/serverless/installations/new?state=XXX. This results in a 404 page, and you're not able to configure and install the app.

**Solution:**

1. Change the redirect to https://github.com/apps/serverless-ci-cd/installations/new?state=XXX. I have tested and this works, I'm able to select a repo, where before I couldn't. 

_**NOTE:** There was also a callback redirect to https://app.serverless.com/git/callback after installing the app and this seems incorrect, however I'm unsure what it should be changed to._

**Comment by darbio** [comment]
I can confirm that this is an issue for me too.

**Comment by benlongmire** [comment]
Dunno if this is the correct place for it, but it seemed like a good way to make it known I found a hacky fix for anyone having trouble getting it installed until it's fixed 👍

**Comment by darbio** [comment]
Yeah - I used your workaround. Good Macguivering! Cheers

**Comment by pgrzesik** [comment]
Thank you @benlongmire :bow: I've passed it to internal team for further processing :100:

**Comment by pgrzesik** [comment]
Hello @benlongmire - I believe it was fixed internally - do you still happen to bump into that problem?

**Comment by benlongmire** [comment]
Hey @pgrzesik, yep I can confirm it now works when auth removed and app uninstalled i.e starting from blank.

Good stuff 👍
