### ISSUE TITLE
Exception when I have wrong layer name

### ISSUE THREAD

**Issue by gn01036238** [serverless/serverless#8960]
Exception:
TypeError: Cannot read property '_serverlessLayerName' of undefined 

How it happened:
    Those are the layers in my project:
layers:
  py_odbc:
    path: pyodbc-layer

In one of my function I referenced it with this:
    layers:
      - {Ref: PyodbcLambdaLayer}
  
When in fact the correct name for the layer should be "pyodbc" instead of "pyodbc-layer"
Took me a day to figure this out. Maybe some exception handling for this on next version?

**Comment by medikoo** [comment]
@gn01036238 can you post a full output as you receive from a CLI.

Also what version of `serverless` are you using? Ideally please answer all bug report questions

**Comment by pgrzesik** [comment]
Hey @gn01036238 - I believe it's a similar problem to what was described in this issue: https://github.com/serverless/serverless/issues/8915#issuecomment-775801962 As @medikoo mentioned, please post the full output + list the used version, ideally following our issue template (when you create a new issue, you see the template).
