### ISSUE TITLE
Documentation for `env set` is broken; unable to figure out how to set environmental variables

### ISSUE THREAD

**Issue by brettneese** [serverless/serverless#898]
The page just 404's. 

http://docs.serverless.com/docs/env-set

I'm able to set a variable locally using "variables set" but it's not propagating to AWS. I noticed that serverless-slack used a module to help with this and I'm going to try and figure it out on my own but the docs should still be updated. :-O

**Comment by eahefnawy** [comment]
@brettneese as of v0.5 we ditched the env var commands. You can instead define env vars for each function in the `environment` property of `s-function.json` like this:

```js
"environment": {
    "NON_CIRITCAL_ENV_VAR": "nonCriticalValue",
    "CIRITCAL_ENV_VAR": "${criticalValue}", // uses serverless variables to protect sensitive data
}
```

Hope this helps, and really sorry for the confusion :)

**Comment by brettneese** [comment]
How do I do so in a way that they don't get checked in to version control
though?

El sábado, 26 de marzo de 2016, Eslam λ Hefnawy <notifications@github.com>
escribió:

> @brettneese <https://github.com/brettneese> as of v0.5 we ditched the env
> var commands. You can instead define env vars for each function in the
> environment property of s-function.json like this:
>
> "environment": {
>     "NON_CIRITCAL_ENV_VAR": "nonCriticalValue",
>     "CIRITCAL_ENV_VAR": "${criticalValue}", // uses serverless variables to protect sensitive data
> }
>
> Hope this helps, and really sorry for the confusion :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/serverless/serverless/issues/898#issuecomment-201981931>
>


-- 
Brett Neese
563-210-3459

**Comment by eahefnawy** [comment]
that's where Serverless variables comes in ... variables in the `_meta` folder are not checked in version control by default.

**Comment by brettneese** [comment]
Do I still need to reference them with process.env.$VARIABLE?

Maybe I missed it but I don't see anything in the docs about this.

El domingo, 27 de marzo de 2016, Eslam λ Hefnawy <notifications@github.com>
escribió:

> that's where Serverless variables comes in ... variables in the _meta
> folder are not checked in version control by default.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/serverless/serverless/issues/898#issuecomment-202052517>
>


-- 
Brett Neese
563-210-3459

**Comment by eahefnawy** [comment]
nope you can just reference it with `process.env.CRITICAL_ENV_VAR` as usual, that's why it's a key in the `environment` object.

**Comment by brettneese** [comment]
Ok, that worked.

Even so, this doesn't appear to be documented very well and what little documentation there is still points to the old documentation so this should be re-opened and fixed.

**Comment by notmessenger** [comment]
What is the pre v0.5 of achieving the same?

**Comment by eahefnawy** [comment]
@notmessenger before we used to do it like this:

```
sls env set -k KEY -v VALUE
sls env unset -k KEY
```

@brettneese I'm gonna reopen a separate issue for this 😊
