### ISSUE TITLE
Deprecation docs: typo in YAML key

### ISSUE THREAD

**Issue by clar-cmp** [serverless/serverless#8982]
There's a typo on the deprecation page: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS

> `provider.cfnRole` -> `provider.iam.role.deploymentRole`

should be:

> `provider.cfnRole` -> `provider.iam.deploymentRole`

**Comment by pgrzesik** [comment]
Thank you for reporting - great catch, I've already prepared a fix for it :+1:
