### ISSUE TITLE
Deprecate `configValidationMode: warn` default

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8985]
### Use case description

Warning by default on schema errors was introduced only to allow  gentle migration to config schema validation.
Otherwise the goal was to throw by default whenever configuration error is discovered, and that ideally should happen with v3. For that we need to deprecate `configValidationMode: warn` default

### Proposed solution

If there's no `configValidationMode` set in service configuration (we can confirm reliably by inspecting `serverless.configurationInput.configValidationMode`)  and there are some schema errors (we now that at this logic point: https://github.com/serverless/serverless/blob/4f64e560b9157dc8700328686a778ebd2a78ba9e/lib/classes/ConfigSchemaHandler/index.js#L118-L119), [show a deprecation](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations) stating that from next major by default Framework will throw on any error, and suggest to adapt to new behavior by setting `configValidationMode: error`

**Comment by yumeixox** [comment]
@medikoo Can I take this?

**Comment by medikoo** [comment]
@yumeixox yes, thank you!

**Comment by yumeixox** [comment]
@medikoo I'm running into some unexpected behavior with runServerless. Maybe you know what might be wrong?

For some reason when I execute runServerless, if I leave configValidationMode unconfigured, it behaves as if it was set to 'error'. For example:

```
runServerless({
  cliArgs: ['package'],
  config: {
    service: 'service',
    provider: 'aws',
    fakeProp: true
  },
}).then(({ serverless, stdoutData, cfTemplate }) => {
  console.log(stdoutData);
});
```
throws:
```
UnhandledPromiseRejectionWarning: ServerlessError: Configuration error at root: unrecognized property 'fakeProp'
    at ConfigSchemaHandler.handleErrorMessages
```

If I set the configValidationMode to warn, it works as expected:
```
runServerless({
  cliArgs: ['package'],
  config: {
    service: 'service',
    provider: 'aws',
    fakeProp: true,
    configValidationMode: 'warn',
  },
}).then(({ serverless, stdoutData, cfTemplate }) => {
  console.log(stdoutData);
});
```
shows:
```
Serverless: Configuration warning at root: unrecognized property 'fakeProp'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
```

Same goes for:
```
runServerless({
  cliArgs: ['package'],
  fixture: 'configInvalid',
}).then(({ serverless, stdoutData, cfTemplate }) => {
  console.log(stdoutData);
});
```
throws:
```
(node:8043) UnhandledPromiseRejectionWarning: ServerlessError: "service" property is missing in serverless.yml
```

Any ideas?

**Comment by medikoo** [comment]
> For some reason when I execute runServerless, if I leave configValidationMode unconfigured, it behaves as if it was set to 'error'. For example:

Yes, it's intentionally, It's enforced here: https://github.com/serverless/test/blob/3a7bd0e119f1a327a2fd51bc81ab370b528f495d/run-serverless.js#L109, as ideally when testing we should use only defined configuration properties (unless we test that this validation works)
