### ISSUE TITLE
Variable resolution error logged when loading config from files with fallbacks since v2.26

### ISSUE THREAD

**Issue by coyoteecd** [serverless/serverless#9007]
This is an issue somewhat similar to #8999, but now with files. To help with multi-stage deployments, we are using "nested" variable resolutions based on stage name, but loading variables from a js file, like this:

```
custom:
  # import environment-specific settings
  config: ${file(serverless-config/config-${self:provider.stage}.js):config, file(serverless-config/config-dev.js):config}
```

Idea being that it would resolve variables from the stage-specific config file for prod and staging, while in dev it would have a shared "dev" config for all individual developer stages.
This worked fine until v2.25; after update to v2.27 it logs the following error:

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.config": Cannot load "serverless-config\config-mystage.js": File not found,
              - Cannot resolve variable at "custom.config": Cannot load "serverless-config\config-mystage.js": File not found,
              - Cannot resolve variable at "custom.config": Cannot load "serverless-config\config-mystage.js": File not found,
```
The file indeed does not exist, because I want to share the same dev config for all stages. Either remove the error, or provide a way to disable it without disabling other legitimate resolution errors.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
custom:
  config: ${file(config-${self:provider.stage}.js):config, file(config-dev.js):config}
```

<summary><code>config.dev.js</code></summary>
```js
module.exports.config = (context) => {
  return {
     myVariable: 'value'
  }
}
```

</details>

<details>
<summary><b><code>serverless deploy --stage mystage</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.config": Cannot load "config-mystage.js": File not found,
              (repeated as many times as the variable custom.config.myVariable is referenced)
```

</details>

<b>Installed version</b>

```
Framework Core: 2.27.0 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

**Comment by medikoo** [comment]
@coyoteecd great thanks for report.

Indeed in new variable resolver, the configured behavior is to report with an error (and not a missing value) a missing file.

I wonder weather it's safe to assume missing files as missing values, at least it raises the danger of typos in configured filenames coming unnoticed, but I guess what you present is quite valid use case, and it's hard to achieve it in some other way. Therefore we will probably adjust to it shortly (@pgrzesik what do you think?)

Otherwise, I believe deployments should work as they worked for you, at least if new variable errors, then by default resolution is fallback to old resolver (it's just deprecation error you're prompted with)

**Comment by pgrzesik** [comment]
I was thinking about this a bit too and while it opens up potential bugs as you mention @medikoo with simple typos for filenames, I don't see a good way of achieving the same result in some alternative way. So I think we should missing files as missing values in this case.

**Comment by coyoteecd** [comment]
I am open to reconfiguring my environment if there is a better way. What I have now is something I built based on on v1.5x (with limited knowledge), and Serverless evolved since then.

What I need is a way to have per-environment configuration (dev, staging, prod) since each uses its own AWS account, and for dev to share the same config across multiple stages, so that each dev has their own account. Furthermore, I needed to be able to tweak each config property with simple operations (conditionals based on stage name, string replace). 

What I came up with is moving off the config to a js file and loading it as shown above, as the "cleanest" way. Is there other way to achieve it?

**Comment by medikoo** [comment]
@coyoteecd I think what you're doing is fine. Still as you already resolve config dynamically, you may simply have one resolver:

```yaml
variablesResolutionMode: 20210219
custom:
  config: ${file(stage-config.js)}
```

```javascript
// stage-config.js
module.exports = async ({ options, resolveConfigurationProperty }) => {
  const stage = options.stage || await resolveConfigurationProperty(['provider', 'stage']) || 'dev';

  // Resolved expected config for stage
  // ...
}
```
