### ISSUE TITLE
0.5.1 function naming bug

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#901]
This does not work:
![image](https://cloud.githubusercontent.com/assets/5667395/14082745/a73ab606-f4df-11e5-9c07-122627075af8.png)

but this does:
![image](https://cloud.githubusercontent.com/assets/5667395/14082754/b5cbcc46-f4df-11e5-97a4-5084fc2e4eca.png)

**Comment by eahefnawy** [comment]
@edclement the first screen you're prompted for functoin **name not path**, so you should only provide `idp-get`, and the function will be created in the CWD (so u have to make sure you're in the `idp` folder), while, in the second screen, you're providing a function **path**.

This is just to give users more options, so u can create a function by path, or if you don't want to type the full path, you can just `cd` into it and create the function interactively. 

We realize this is not at all clear from the CLI output nor the docs. We will release a minor release soon that includes better CLI output for this. Really sorry about this :blush:
