### ISSUE TITLE
Introduce "deprecationsNotificationMode"

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9024]
### Use case description

There are cases when it's nice to have deprecations reported with errors, e.g. in our test suite, it'll be good to ensure that all tests (aside of those testing deprecated feature) are also updated to not work with deprecated feature, and best way to discover it's the case, to report deprecations with crashes

### Proposed solution

Introduce `deprecationsNotificationMode` top level setting, with two possible options `'warn'` (default), `'error'`

1. Configure schema for it in [`configSchema.js`](https://github.com/serverless/serverless/blob/fdaba7117f076eef68c2735deca3eda3bb2a9c9a/lib/configSchema.js)
2. Document it in:
   - [docs/providers/aws/guide/serverless.yml.md](https://github.com/serverless/serverless/blob/fdaba7117f076eef68c2735deca3eda3bb2a9c9a/docs/providers/aws/guide/serverless.yml.md)
   - [docs/deprecations.md](https://github.com/serverless/serverless/blob/fdaba7117f076eef68c2735deca3eda3bb2a9c9a/docs/deprecations.md)
3. Handle new setting in [lib/utils/logDeprecation.js](https://github.com/serverless/serverless/blob/fdaba7117f076eef68c2735deca3eda3bb2a9c9a/lib/utils/logDeprecation.js)
4. Update tests:
   - Ensure all [fixtures](https://github.com/serverless/serverless/tree/fdaba7117f076eef68c2735deca3eda3bb2a9c9a/test/fixtures) have this setting set to `'error'`
   - Ensure it's set to `'error'` (if not set) in [`@serverless/test/run-serverless.js`](https://github.com/serverless/test/blob/12b914818e642ea963bb9d933615ca12ffb92bc8/run-serverless.js#L110) - still here we need to ensure it's not set if for testing we use `serverless` version that does not define it (it'll trigger error) - we can confirm that by require'ing `lib/configSchema.js` from `serverless` path
   - Confirm that `serverless` unit tests pass
   - Confirm that `serverless` integration tests pass
   - Confirm that `@serverless/enterprise-plugin` tests pass
   - Confirm that `@serverless/enterprise-plugin` integration tests pass

**Comment by azwan80033** [comment]
can help me, my phone huawei nova 7 5G
google playstore can't use. any some one can help me??

**Comment by HarshavardhanK** [comment]
Hey @medikoo I'd like to work on this!

**Comment by medikoo** [comment]
@HarshavardhanK Great to hear that. We look forward!

**Comment by medikoo** [comment]
In https://github.com/serverless/serverless/pull/9035 integration test were updated to not rely on deprecated features.

Still there's [custom resource based`eventBridge` test](https://github.com/serverless/serverless/pull/9035) which intentionally tests deprecated feature. When addressing this issue, configuration for this test need to be extended with `deprecationsNotificationMode: warn`

**Comment by HarshavardhanK** [comment]
Hey, @medikoo I configured the schema for it, but not able to figure out how to handle the new setting in lib/utils/logDeprecation.js . And confirming that deprecationsNotificationMode needs to be set to 'error' in the serverless.yml of each fixture.

**Comment by medikoo** [comment]
> Hey, @medikoo I configured the schema for it, but not able to figure out how to handle the new setting in lib/utils/logDeprecation.js

This util receives a service configuration with `serviceConfig` option. So you should throw if `serviceConfig.deprecationsNotificationMode === 'error'`

Still (sorry I forgot about that in spec) you also need to port `deprecationsNotificationMode` to `serviceConfig` (that's being passed to util) in context of `Service.js` class. You need to follow same way as with this properties: https://github.com/serverless/serverless/blob/225146f812969face51c0e7c4f78097b50719b52/lib/classes/Service.js#L140-L141

> And confirming that deprecationsNotificationMode needs to be set to 'error' in the serverless.yml of each fixture.}

In each fixture that you can find in https://github.com/serverless/serverless/tree/225146f812969face51c0e7c4f78097b50719b52/test/fixtures, and which presents a valid service config, just set `deprecationsNotificationMode: error`

**Comment by HarshavardhanK** [comment]
Thanks! Got it.

> In each fixture that you can find in https://github.com/serverless/serverless/tree/225146f812969face51c0e7c4f78097b50719b52/test/fixtures, and which presents a valid service config, just set `deprecationsNotificationMode: error`

Any pointers on knowing how it is a valid service config?

**Comment by medikoo** [comment]
> Any pointers on knowing how it is a valid service config?

It's indicated by fixture name, e.g. `configInvalid` signals it's an example of an invalid config

**Comment by medikoo** [comment]
I'm going to cover it, as it'll be really helpful to have it for sound migration into v3
