### ISSUE TITLE
Enable DynamoDB Streams Custom Checkpointing

### ISSUE THREAD

**Issue by imewish** [serverless/serverless#9030]
### Use case description

Enable custom checkpointing for dynamodb streams. There was a recent [announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-launches-checkpointing-for-amazon-kinesis-and-amazon-dynamodb-streams/) from AWS. This feature lets users add a checkpoint to the failed message in the batch by which successfully processed messages prior to the failed messages won't be reprocessed on the next retry.

### Proposed solution

As per AWS [Documentation](https://aws.amazon.com/blogs/compute/optimizing-batch-processing-with-custom-checkpoints-in-aws-lambda/) setting this option `functionResponseTypes: ReportBatchItemFailures` on dynamodb stream event source for lambda will enable the function(additional code changes need in the function code) to do custom checkpointing when there is an error.

**Comment by pgrzesik** [comment]
Hello @imewish, thanks a lot for submitting your request. How do you think that configuration should be exposed in the Framework? Via `functionResponseTypes` property on an `event`?

**Comment by imewish** [comment]
I would love to open a PR for this change. Kind of tested locally and works as expected.

**Comment by imewish** [comment]
Thanks, @pgrzesik. I will work on the PR. To answer your question, as per cloudformation [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-functionresponsetypes), they are expecting `(Streams) A list of current response type enums applied to the event source mapping.`. So yes it should be an array of strings. And for now, the only valid value is `ReportBatchItemFailures`. They might add more in the future.

**Comment by imewish** [comment]
@pgrzesik created a PR. https://github.com/serverless/serverless/pull/9056. Awaiting your review and feedback. Thanks
