### ISSUE TITLE
Error deploying endpoint 

### ISSUE THREAD

**Issue by jschr** [serverless/serverless#905]
Serverless v0.5.1

Getting the following error when running `sls endpoint deploy sendContactEmail#POST -s production`

```
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Endpoint "sendContactEmail#POST" doesn't exist in your project
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/Project.js:172:30
```
After some console.logging in Project.js I figured out it was looking for `sendContactEmail~POST` so running  `sls endpoint deploy sendContactEmail~POST -s production` worked.

Maybe this is just a doc error? http://docs.serverless.com/docs/endpoint-deploy

**Comment by ac360** [comment]
Yo @jschr!  It's good to see you.  Yes, it's a doc error.  Sorry about that!  I'll fix it now :)

**Comment by jschr** [comment]
Hey Austen - no problem! Great work on the latest release, I'm liking the changes.

**Comment by ac360** [comment]
:beers: Let me know what else you need.  I'm also going to invite you to a separate project we're working on.  Would love your input on the React side.

**Comment by PHPTrude** [comment]
still the same error

**Comment by eahefnawy** [comment]
@PHPTrude are u still using `sendContactEmail#POST`? if so you should use `sendContactEmail~POST` instead.

Also, what version of Serverless are you running?

**Comment by PHPTrude** [comment]
it was my fould, i doploy mutch functions and in one i have the path /xyz/{id} and in another /xyz/{id}/set
so serverless dosent have here a bug :) sorry

**Comment by PHPTrude** [comment]
>and in another /xyz/{oid}/set 
i mean this dynamic param have to be the same

**Comment by eahefnawy** [comment]
awesome! :)
