### ISSUE TITLE
Feature Request: project init --profile property should not be required (look for env credentials first)

### ISSUE THREAD

**Issue by kerux2222** [serverless/serverless#906]
When doing a 'project init', if -p is not specified, serverless should look for the SERVERLESS_ADMIN_AWS_* env variables before throwing an error. 
This would make for much easier CI deployments. 
@ryansb, great idea! 
Could we try to make this part of 0.5.2?

**Comment by xzyfer** [comment]
We've also run into this issue.

**Comment by kerux2222** [comment]
@xzyfer did you find any work around?

**Comment by xzyfer** [comment]
No. I just added junk data and later deleted the profile variable it created. It then fallsback to ENV credentials.

**Comment by leslie-fugue** [comment]
Also an issue for me. I like the proposed solution.

**Comment by flomotlik** [comment]
As this is handled differently on service creation now in V1 I'm going to close this issue
