### ISSUE TITLE
TypeError: AWS.request(...).then(...).return is not a function --- on export-env

### ISSUE THREAD

**Issue by Pehel** [serverless/serverless#9064]
On running npm run sls -- export-env 
it returns an error:
Type Error ---------------------------------------------
  TypeError: AWS.request(...).then(...).return is not a function

Checked the logs which returned:
1```
7 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session 221e0e99d50bd7fd
20 timing npm:load Completed in 11ms
21 timing command:run-script Completed in 2202ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
```

**Comment by pgrzesik** [comment]
Hello @Pehel - that's an issue with the plugin - it was alredy fixed in the plugin but it seems like the new version wasn't relased yet: https://github.com/arabold/serverless-export-env
