### ISSUE TITLE
feature request: create upgrade script if deploying a breaking change

### ISSUE THREAD

**Issue by karlsburg** [serverless/serverless#907]
Great project all!

A small feature request, when deploying new versions of Serverless, provide an upgrade script also to bring old projects up to date.

**Comment by erikerikson** [comment]
Very glad you appreciate it.

The owners of the project may have different ideas, but the norm is that for 0.* versions, breaking changes are accepted.  See http://semver.org/#spec-item-4.  We generally wish we could do better but all projects must prioritize finding the right shape and factoring of the project, its code, and its assets against stability.

**Comment by flomotlik** [comment]
as @erikerikson already mentioned we simply don't have the resources to automatically update all projects. We're minimising the necessary configuration to make sure its very easy to move applications over, but before 1.0 we simply can't give guarantees that things will keep working as they do now. We are working on 1.0 now though and there we can give more guarantees.
