### ISSUE TITLE
Some environment variables in admin.env ignored

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#908]
Using admin.env to inject proxy settings into the SLS environment doesn't work for all variables.  The reason for this is that the [ProviderAws constructor that uses the value](https://github.com/serverless/serverless/blob/master/lib/ProviderAws.js#L27) is [loaded before Serverless.init() is called](https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L35) and thereby before [the values defined in admin.env are loaded into the environment](https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L92).  The loading of environment variable "PROXY" (and variants) is the primary concern but "AWS_PROFILE_PREFIX" would also be impacted (although I think the use case for that variable avoids the problem).

**Comment by erikerikson** [comment]
a.k.a. '`init`'s are contagious

**Comment by erikerikson** [comment]
This is resolved by PR https://github.com/serverless/serverless/pull/909.

**Comment by eahefnawy** [comment]
Merged! Thanks tons @erikerikson :blush:

**Comment by erikerikson** [comment]
PR https://github.com/serverless/serverless/pull/909 merged with fix.
