### ISSUE TITLE
v0.5 Outputs Added to CFT

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#910]
I "doctored up" the cloudformation template produced by default for the project.  In particular, I removed the "`Outputs`" section and changed the name of the "`IamRoleLambda`" resource to something else.

Then I issued the command `sls resources deploy -s [stage] -r [region] -c`.

I expected to see my CFT with variables replaced (and I did) but the following CFT snippet was added to the resulting s-resources-cf-[stage]-[region].json:
```
  "Outputs": {
    "IamRoleArnLambda": {
      "Description": "ARN of the lambda IAM role",
      "Value": {
        "Fn::GetAtt": [
          "IamRoleLambda",
          "Arn"
        ]
      }
    }
  }
```

This has the consequence that the `Fn::GetAtt` statement references a resource that isn't defined.

**Comment by HyperBrain** [comment]
Currently the IamRoleLambda is fixed by name in the code as it is used to declare and deploy functions that have no custom role assigned. Letting this be variable (on the behalf of the user) it would not be clear how to access the name within the serverless deployment chain.
Also, if the role name is not specified as output role at all in the CF template how would serverless know the generated role name?

**Comment by erikerikson** [comment]
@HyperBrain I am well aware of the current usage.  Ours is a "we know what we're doing" scenario.  We define customRole in s-function to provide the framework the name of the role.  This is possible via a role naming standard that we use in definition.

**Comment by HyperBrain** [comment]
Maybe a solution could be that there is some kind of ko-switch on `project create` that completely disables the standard behavior and does not create any roles in the initial CF-template like `project create --no-roles`. This setting could be persisted in the project settings and fix the project forever to that. Then it would internally just end up in 0/1 decisions and would not require any additional sophisticated logic, but make the use of custom roles in the `s-function.json` mandatory.
According to your use case such a solution could match.

**Comment by erikerikson** [comment]
@HyperBrain This is an interesting idea that could avoid some errors proactively.

I only mentioned `project resources`.  Personally, I don't care if the initial s-resources-cf.json contains the boilerplate that gets a first time explorer started.  I believe that's valuable for first time users.  I wrote up this issue because far after that point my CFT is being modified with an artifact that breaks my ability to use the tool.

Maybe I misunderstand but my belief is that SLS currently outputs any variables in the CFT's `Outputs` into the relevant `~/_meta/variables/s-variables-[stage]-[region].json`.  Is this not what it does?  I guess I'm wondering why this behavior should be controlled by a config item when the instantiation of the CFT and then persistence of its output can so easily be properly implemented in a general form.

**Comment by HyperBrain** [comment]
Yes, exactly. So, if you add your own auto-generated resources into your CFT and expose the names with output variables they will be available as project vars after your `resources deploy` which is quite handy as you do not even know the generated resource names. These project variables can directly be used in any project configuration file (e.g. we use that to inject the resource names automatically into environment variables).
So the behavior should only affect the role itself as the resources are already out of serverless logic and fully under control of the user.

**Comment by erikerikson** [comment]
Actually, we know the names of the auto-generated resources by using externally mandated consistent naming standards.

Do you disagree that it is problematic to add an output "`IamRoleArnLambda`" variable despite the lack of definition of a resource with that name?

**Comment by erikerikson** [comment]
@ac360 for the record, this issue is blocking me from deploying our roles and tables via serverless in the upcoming demo.  We are instead deploying those in parallel.

**Comment by HyperBrain** [comment]
@eahefnawy @erikerikson I think we should discuss the whole resource/variables topic here to come to a final solution that allows to have more control over the resource creation for the hands-on people and define a "default happy path" (@erikerikson great wording :) ) for the beginners.

**Comment by erikerikson** [comment]
@HyperBrain definitely thinking on this one.  It didn't impact me positively or negatively when CFT output was auto-added to the environment (we haven't been able to use the SLS resource workflow) but I think it was a big win for others.  The general pattern of being able to reference the resources in your code is a basic necessity unless one uses variable based naming conventions.  The former approach feels cleaner.

Some issues I see in resource creation:

1. One (combined) or many (individual) CFTs?  (a question for both configuration and again for deployment)
2. Any level of SLS-provided assistance in definition?
3. Any level of SLS-provided assistance in managing the rights of defined resources?
4. How will SLS manage or facilitate the management of relationships across assets (CFT=>CFT, CFT=>s-*, s-*=>s-*)?

**Comment by flomotlik** [comment]
@erikerikson @HyperBrain it looks like the Resource management in V1 we discussed should resolve this issue? I'm going to close it for now unless you think it doesn't resolve the issue then please open back up and discuss here.
