### ISSUE TITLE
Feature request: Create multiple API Gateway API's from one Serverless project

### ISSUE THREAD

**Issue by cluda** [serverless/serverless#911]
It would be very useful to be able to deploy/ create multiple API Gateway API's from one Serverless project.

Now I have to create one Serverless project per API Gateway API.

Currently, I have one project with public endpoints and one for hooks, etc. I want to keep them separate, partly because I want to use the API Gateway SDK Generator to create SDK's for my public endpoints that does not include all the hooks etc.

**Comment by flomotlik** [comment]
In a future version of serverless you will be able to define this by creating your own resources with our Cloudformation integration directly. For the integrated syntax we do not plan to support multiple endpoints in one service as it would complicate the code and configuration a lot. But its definitely going to be possible. I will close this issue as this will be resolved in the future.
