### ISSUE TITLE
serverless "eu-south-1" region is not supported by dashboard

### ISSUE THREAD

**Issue by bayraak** [serverless/serverless#9117]
### Use case description

Serverless deploy fails due to unsupported AWS zone `Italiy/Milan` aka `eu-south-1`

Error while deploying:

```
serverless "eu-south-1" region is not supported by dashboard
```

### Proposed solution

Add the `eu-south-1` to the list of supported AWS zones

**Comment by medikoo** [comment]
@bayraak can you use "support" section in Dashboard to report that?

This issue tracker is purely for issues in Serverless Framework CLI

**Comment by bayraak** [comment]
> @bayraak can you use "support" section in Dashboard to report that?
> 
> This issue tracker is purely for issues in Serverless Framework CLI

Sure, I will do that

**Comment by medikoo** [comment]
@bayraak Thank you!
