### ISSUE TITLE
provider.sdk is undefined as of v2.30

### ISSUE THREAD

**Issue by coyoteecd** [serverless/serverless#9126]
Similar to #9099, today I've noticed that updating to latest serverless v2.30 is breaking the serverless-s3-sync plugin that we use to copy files to our S3 buckets. Source of the error is likely the fact that this plugin tries to instantiate an S3 client through the `provider.sdk` property. This is no longer available; I checked that it is working fine in v2.29.

It's likely the property was intentionally removed through refactoring, and the plugin should be fixed to cope with this.  Normally I try to use `provider.request()` function because this lets Serverless manage the credentials, but in this particular case it appears that the plugin author really needs to tweak the s3 instance in offline mode.

Is there a recommended way to instantiate an AWS SDK client when writing plugins? E.g. are we supposed to use new AWS.S3() instead? 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test
plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: my-s3-bucket
      localDir: dist
```

</details>

<details>
<summary><b><code>serverless s3sync</code> output</b></summary>

```
S3 Sync: Syncing directories and S3 prefixes...

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'S3' of undefined
      at ServerlessS3Sync.client (node_modules\serverless-s3-sync\index.js:98:39)
      at node_modules\serverless-s3-sync\index.js:205:35
      at new Promise (<anonymous>)
      at node_modules\serverless-s3-sync\index.js:161:18
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Promise.all (index 0)
```

</details>

<b>Installed version</b>

```
Framework Core: 2.30.1 (local)
Plugin: 4.5.0
SDK: 4.2.0
Components: 3.7.3
```

**Comment by tommy31** [comment]
Hey, problem seems to come from this function ```const provider = this.serverless.getProvider('aws'); ```

**Comment by medikoo** [comment]
@coyoteecd great thanks for report!

> Is there a recommended way to instantiate an AWS SDK client when writing plugins?

I think best way is if simply plugins rely on `provider.request` (note that it behind the scenes caches and reuse AWS SDK clients

Do you think `serverless-s3-sync` can be updated to do that?

**Comment by alexander-zheleznov** [comment]
I've got this error from serverless-domain-manager plugin after the update to 2.30.1 – `Cannot read property 'config' of undefined at ServerlessCustomDomain.initializeVariables (in serverless-domain-manager/dist/index.js:176:47)`, and it's due to 2.30.x as well since it's not reproducible on 2.29.x (I specifically checke). Seems like not only s3-sync plugin is affected.

**Comment by coyoteecd** [comment]
@medikoo Well if you look through the plugin code, they jump through a lot of hoops just [to override a property on the S3 client](https://github.com/k1LoW/serverless-s3-sync/blob/9628ca6fe190c9c58109249fcc3b2d6685e84db8/index.js#L98-L106).
I don't see how I could do that via `provider.request`?

**Comment by medikoo** [comment]
@coyoteecd indeed, currently `provider.request` doesn't provide a mean for that (it should).

Let me ensure `provider.sdk` is accessible. We will probably drop it then with v3, but in controlled way, with proper deprecation, and offering a reliable alternative.

Sorry for mess it created, PR is coming.

**Comment by clarkritchie** [comment]
Thank you for the fast turnaround!  :clap:
