### ISSUE TITLE
Serverless 2.30 breaks sls deploy

### ISSUE THREAD

**Issue by debugguru** [serverless/serverless#9128]
latest update of serverless breaks sls deploy with following error

 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'ACM' of undefined
      at new DomainConfig

It works fine with 2.18

I am using following plugins with serverless 

```
service: backend-services

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-domain-manager
```

**Comment by medikoo** [comment]
@debugguru I believe it's a duplicate of https://github.com/serverless/serverless/issues/9126 which was just fixed (new release is being rolled out).

Otherwise you're report missing answers to questions needed to be able to investigate it properly.

**Comment by coyoteecd** [comment]
@debugguru it helps if you narrow down the plugin that's failing, either by removing them or just searching for the failing line of code in node_modules...

For what is worth, `new DomainConfig()` shows up in serverless-domain-manager plugin, [here](https://github.com/amplify-education/serverless-domain-manager/blob/master/src/index.ts#L118).

**Comment by debugguru** [comment]
Thanks @medikoo  and @coyoteecd. I can confirm that 2.30.3 fixes this.
