### ISSUE TITLE
Support optional flag for request parameters

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#913]
Currently Serverless makes all request parameters defined mandatory. There is no way to specify parameters as optional in `s-function.json`.

*Reason*:
The current implementation sets all parameter properties before the deployment to *true* internally. According to the AWS API GW - REST API documentation this value is used to specify if a parameter is optional or mandatory. Optional API GW parameters should be supported as well.

`EndpointBuildApiGateway.js`:
```
        // Format them per APIG API's Expectations
        for (let prop in _this.endpoint.requestParameters) {
          let requestParam                = _this.endpoint.requestParameters[prop];
          requestParameters[requestParam] = true;
        }
```

**Comment by flomotlik** [comment]
Added to V1 milestone

**Comment by flomotlik** [comment]
optional parameters are possible now in V1.

**Comment by olegZastavnyi** [comment]
@flomotlik is it possible to specify requestParameters section in 1.0.0rc (yml configuration) ?
I am looking into this code https://github.com/serverless/serverless/blob/1.0.0-rc.1/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
And looks it is not possible. 

Any help or suggestion. 
Thanks!

**Comment by flomotlik** [comment]
@olegZastavnyi at the moment it isn't. We're currently working on a larger overhaul of the system and there is this PR going into more details on the parameters: https://github.com/serverless/serverless/pull/2056

**Comment by olegZastavnyi** [comment]
@flomotlik any workaround ? We need to specify query params for request.

**Comment by flomotlik** [comment]
Sorry that might have been a misunderstanding on my part. You should already be able to specify query parameters in the request and they should be coming through to the Lambda function. Are they not coming through?

**Comment by olegZastavnyi** [comment]
Not sure how exactly do this. I've not found how the solution. That's why I am asking. Can you suggest something ?
