### ISSUE TITLE
API Gateway: When external REST API is used, warn if not applicable settings are configured

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9139]
Settings as `provider.tracing.apiGateway` & `provider.logs.resteApi`, are applied to API Gateway, only if it's created with a stack (no `provider.apiGateway.restApiId` pointing externally setup REST API is configured).

In situation when they're setup together with `provider.apiGateway.restApiId` , they're silently ignored, and may raise confusion, as reported here: https://github.com/serverless/serverless/issues/7036#issuecomment-800362691

### Proposed solution

1. Improve documentation in [docs/providers/aws/guide/serverless.yml.md](https://github.com/serverless/serverless/blob/d8dde513f3fe3f83ecdccd2fa127eb06197c273c/docs/providers/aws/guide/serverless.yml.md) pointing that those settings are effective only when API Gateway is created with a stack
2. Report a [deprecation](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations)  warning, when such situation occurs. Inform that setting is ineffective and announce that with next version Framework will crash on such setup

**Comment by jkklapp** [comment]
take
