### ISSUE TITLE
Enable configuration validation for "$<<" property

### ISSUE THREAD

**Issue by iianev** [serverless/serverless#9157]
Serverless: Configuration warning at 'provider.environment': unrecognized property '$<<'

This is used by the Serverless Merge Config plugin

https://github.com/CruGlobal/serverless-merge-config

I use it to merge several environment files, I have not found a suitable feature in core framework 
Example:

provider:
  environment:
    $<<:
      - ${file(../services.env.yml)}
      - ${file(./diet-tracking.env.yml)}

**Comment by pgrzesik** [comment]
Thank you for reporting @iianev - it looks like an issue on the plugin side (missing schema extension) and I see it has already been reported there: https://github.com/CruGlobal/serverless-merge-config/issues/8

I'm going to close this one and let's track this in plugin's repository
