### ISSUE TITLE
failed: Deploy Your Serverless API

### ISSUE THREAD

**Issue by cyclexuxu** [serverless/serverless#9165]
Deployed SST CDK App successfully, but when comes to deploy Serverless API, encountered some issue.
firstly, I ran the "serverless deploy -v" gave me "command not found: serverless" error, then I ran the "npx deploy -v", it gave me the following error:
Error ---------------------------------------------------
 
  Error: npm ls -prod -json -depth=1 failed with code 1
      at ChildProcess.<anonymous> (/Users/path/path/serverless/notes-api/services/notes/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:467:12)
      at maybeClose (internal/child_process.js:1048:16)
      at Socket.<anonymous> (internal/child_process.js:439:11)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at Pipe.<anonymous> (net.js:673:12)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.30.3
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.7.6

Any ideas where went wrong.

**Comment by cyclexuxu** [comment]
Solved. I think the reason the "serverless deploy -v" didn't work was that I didn't have npm serverless installed locally. I ran the following instead:

npm install serverless --save-dev
node ./node_modules/serverless/bin/serverless deploy -v

and the problem was fixed.

**Comment by mellson** [comment]
For me I was using [serverless-bundle](https://github.com/AnomalyInnovations/serverless-bundle) and I had to set [my packager](https://github.com/AnomalyInnovations/serverless-bundle#options) to `yarn` because I'm using yarn workspaces.
