### ISSUE TITLE
when deploying to lambda 70% less expensive api protocol could be used

### ISSUE THREAD

**Issue by liesislukas** [serverless/serverless#9189]
just tried to deploy express app to lambda with serverless npm package and it seem to work yet while it deployed aws api gateway service and it picked REST protocol. Why? It just uses lambda as proxy. HTTP would provide ~70% discount in price for such config. Is there an option to pick api protocol?

**Comment by pgrzesik** [comment]
Hello @liesislukas :wave: Yes, it's possbile via use of `httpApi` event type: https://www.serverless.com/framework/docs/providers/aws/events/http-api/
