### ISSUE TITLE
Support for global plugin configuration in s-project.json

### ISSUE THREAD

**Issue by dijitalmunky** [serverless/serverless#919]
In Serverless before 0.5.0, one could configure plugins for a bunch of functions in the s-component.json file.  This was useful for things like the serverless-optimizer, especially if you had many functions.  Now with the removal of the component concept in 0.5 (which I fully support), one needs to copy configuration for plugins into every s-function.json file, or use templates.  It would be nice if there was an option to put a global configuration in s-project.json, rather than having to remember to put configuration in each s-function.json file.

**Comment by erikerikson** [comment]
+1 for property inheritance between s-project.json and s-function.json.

**Comment by martinmicunda** [comment]
same request like for optimizer-plugin [issue](https://github.com/serverless/serverless-optimizer-plugin/issues/30)

**Comment by dijitalmunky** [comment]
Good catch @martinmicunda!

**Comment by martinmicunda** [comment]
@eahefnawy is this already released?

**Comment by eahefnawy** [comment]
yep! There's now the `custom` property in `s-project.json` to configure the plugin at the project level.

**Comment by martinmicunda** [comment]
@eahefnawy this doesn't seem to work for optimizer plugin ( I am using serverless version `0.5.5`) ... I still need to add `optimize` settings to each `s-function.json` file to deploy mu function properly.. There is also open [issue](https://github.com/serverless/serverless-optimizer-plugin/issues/30) against optimizer-plugin.

*s-project.json - this doesn't work*
```json
{
  "name": "test",
  "custom": {
    "optimize": {
      "exclude": [
        "aws-sdk"
      ],
      "transforms": [
        {
          "name": "babelify"
        }
      ],
      "minify": false
    },
    "serverless-offline": {
      "babelOptions": {}
    }
  },
  "plugins": [
    "serverless-offline",
    "serverless-optimizer-plugin",
  ]
}
```

**Comment by vmadman** [comment]
I am experiencing the same problem as @martinmicunda, does each plugin need to add support for global config via `s-project.json` or should it "just work"?

**Comment by martinmicunda** [comment]
@flomotlik this issue should be reopen as it still doesn't work.
