### ISSUE TITLE
Naming inconsistency: permissionBoundary versus permissionsBoundary

### ISSUE THREAD

**Issue by Android3000** [serverless/serverless#9215]
The [serverless.yml example page](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/) shows the available role property named `permissionsBoundary`. This is as expected, as it matches up with the [CloudFormation IAM Role property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html) `PermissionsBoundary`.

Unfortunately, this property does not work. I noticed within the specific [Serverless IAM page](https://www.serverless.com/framework/docs/providers/aws/guide/iam/), it calls out the property as `permissionBoundary` (note the missing plural form of permission) -- and this appears to be the valid property that Serverless is looking for.

I think the documentation pages should be made consistent -- but I do wonder if it's worth thinking about supporting `permissionsBoundary` as that is the matching attribute to the CFT. Maybe `permissionBoundary` could be maintained as a fallback to avoid breaking changes? Or maybe the Serverless property name / CFT property name alignment isn't super important, in which case this would just be a documentation update :)

<details>
<summary><code>serverless.yml</code></summary>

```provider:
  iam:
    role:
      permissionsBoundary: arn:aws:iam::123456789012:policy/boundaries # This will not work
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'provider.iam.role': unsupported configuration format
```

</details>

<b>Installed version</b>

```
Framework Core: 2.32.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```

**Comment by pgrzesik** [comment]
Hello @Android3000 :wave: That's a nice catch :+1: I think that at this point as it would be a breaking change, we should make the documentation consistent with the actual expected property. We'd be happy to accept a PR that clears that out.

**Comment by Android3000** [comment]
Thanks @pgrzesik -- do you think it is worth supporting **both** forms for consistency without a breaking change (with maybe the eventual deprecation of the `permissionBoundary` attribute), or just go for the documentation update and keep as-is? I would be happy to look into either option. Thanks!

**Comment by pgrzesik** [comment]
Hey @Android3000 - that's a great question and to be honest I'm not sure, because the `permissionBoundary` attribute is itself a new recommended replacement of a deprecated `rolePermissionsBoundary` on provider level. Having three different fields for the same setting seems a bit too much, but on the other hand having consistency is also a nice property. @medikoo What is your opinion? Should we deprecate the `permissionBoundary` in favor of `permissionsBoundary` and create a bit of a confustion of having three separate properties for the same thing or stick to `permissionBoundary` here?

**Comment by medikoo** [comment]
It looks as design bug on our side that we've introduced `permissionBoundary` and not `permissionsBoundary`.

To me it feels that second one is correct, and I would ensure we support it, and deprecate `permissionBoundary`. I agree that it feels overwhelming to now handle three properties, but on implementation level it's probably not that problematic to implement, and I think it's still a good moment to fix it

**Comment by pgrzesik** [comment]
Yes, that was definitely a mistake on our side during the refactoring/deprecation. Thanks @medikoo :bow:

**Comment by Ruhrpottattacke** [comment]
Hi! I will update documentation :smile:

**Comment by pgrzesik** [comment]
Hello @Ruhrpottattacke - thanks for submitting a PR, however, as agreed above, we'd like to deprecate the `permissionBoundary` notation and go with `permissionsBoundary` instead to be consistent with CF and also with previous approach. Are you interested in implementing these changes?

**Comment by Android3000** [comment]
I can try to take a look at that full change this weekend unless @Ruhrpottattacke responds before then - don't want to step on your toes here if you were hoping to do this. Thanks!

**Comment by pgrzesik** [comment]
That would be awesome @Android3000, thank you :bow:
