### ISSUE TITLE
v0.5 Deploying S3 events to Frankfurt fails

### ISSUE THREAD

**Issue by hmeltaus** [serverless/serverless#922]
In Frankfurt region, when deploying event that uses S3 bucket as a event source fails with following error message:

> The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

Stacktrace begins:

> Serverless:   myS3Event: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.  
>   serverless:lib.node_modules.serverless.lib.actions.EventDeploy InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
>     at Request.extractError (/Users/henri/.nvm/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:328:35)
>     at Request.callListeners (/Users/henri/.nvm/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit

**Comment by eahefnawy** [comment]
Fixed in master
