### ISSUE TITLE
v0.5 Install project with another name

### ISSUE THREAD

**Issue by mpuittinen** [serverless/serverless#923]
v0.4 had an (undocumented) option -n which could be used to install a project with another name than the original package name (e.g. sls project install -n="serverless-blog" sc5-serverless-boilerplate created a new project "my-serverless-project" based on the sc5-serverless-boilerplate). 

This was handy when using boilerplates such as the sc5-serverless-boilerplate (see our serverless tutorial at http://hackathon-blog.sandbox.sc5.io/walkthrough.pdf for an example). Without the option, the developer needs to rename and re-init the project manually.

Would it be possible to revive the option as a documented and supported feature (can do the change myself if needed) or is there plans to implement similar functionality differently?

**Comment by mpuittinen** [comment]
An alternative to "project install -n" could also be "project create -t" (i.e. create a new project based on a template)

**Comment by laardee** [comment]
I think the "project create" with -t (template) and -n (name) parameters would be a good idea, then there would be no need for -n parameter in project init and install.

**Comment by marksteele** [comment]
+1 on using -t/-n to create based on boilerplate.

Would template be a git url (with tag/git hash) or locally installed boilerplate somewhere in the filesystem?

**Comment by mpuittinen** [comment]
I'm happy with NPM packages (as currently for project install) for project templates. Shorter to write and easier to remember than git URLs :)

**Comment by eahefnawy** [comment]
Just pushed this functionality back to master! Could you guys try it out and let me know if u face any issues? I've tested it and it should be good to go :)

**Comment by mpuittinen** [comment]
Hi Eslam!

I updated our sc5-serverless-boilerplate (v0.5.0 of the boiler is now in the npm registry) to use 0.5 compatible modules, tested project install with the -n switch (serverless project install -n “testproject” sc5-serverless-boilerplate) and everything seems to be working as expected.
Thanks for the quick turnaround on the issue. 

Best regards,

Mikael

**Comment by laardee** [comment]
Excellent, I tested two different boilerplates with node v.5.10.1 and v.4.4.2 and both versions worked fine.
