### ISSUE TITLE
v0.5 sls function remove is not using the correct endpoint name

### ISSUE THREAD

**Issue by affablebloke** [serverless/serverless#925]
As of v0.5, when calling ```sls function remove``` with an associated endpoint, ```endpointRemove()``` is being passed endpoint names with the old format ```foo#GET``` instead of the new format ```foo~GET```.

**Steps to reproduce:**

``` $ sls function create foo``` _(with endpoint)_
``` $ sls function remove foo``` _(will fail)_

**Comment by eahefnawy** [comment]
Fixed by @affablebloke PR. Closing...
