### ISSUE TITLE
Telemetry: Report any command usage

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9257]
### Use case description

Currently we send anonymous usage info only with _deploy_ command.

What we miss is usage information of other commands, it'll be great to have that reported as well.

#### Strategy

- Keep sending analytics request only during deploy command (to not affect user's UX)
- Send only command names (to avoid leaking any private data we should not send command options)
- Upgrade analytics server to accept batch requests (so multiple events can be send with one request)
- With commands that work in _service_ context, send exactly same payload as currently is send with `deploy` command. With commands invoked not in _service_ context, send only following properties: `ciName`, `cliName`, `dashboard.userId`, `firstLocalInstallationTimestamp`, `frameworkLocalUserId`, `installationType`, `isAutoUpdateEnabled`, `isTabAutocompletionInstalled`, `timestamp`, `timezone`, `versions`.
- Do not port to v1 (to avoid time-taking implementation and bugs introduction)

##### External

1. [x] Upgrade payload validator/normalizer to accept events with no `config` and without other properties which are service specific.
1. [x] Upgrade platform service to accept payload as send from Framework in form of an _array_:
   - If it's an _array_ treat it as batch request, where each item is an individual event.
   - Configure batch request to mixpanel to send all events with one request.
   - For notification resolver, process last event (in all cases it'll be a `deploy` event)
1. [x] Upgrade platform mixpanel port to accept other command events. I take it'll imply following updates:
   - Report each command with different event as: `framework.command.<commmand-name>`
   - To each event add `is_in_service_context` boolean property, which should be true if framework payload had `config` property (it'll allow us to easily filter commands depending on whether they were invoked in a context of a service or not)

##### Local

_Address each top level point with individual PR, in given order_

1. [x] Refactor to be updated functionalities to async/await:
   - [`lib/utils/analytics/index.js`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/utils/analytics/index.js)
   -  [`pluginManager.run`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/classes/PluginManager.js#L582-L587)
1. [x] Refactor [`sendPending`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/utils/analytics/index.js#L119-L173) to send all events with one batch request:
    - Array of events should be passed with `payload`
    - In `request` options `id` should be refactored into `ids`
    - Remove handling of `serverlessExecutionSpan` option and related functionality (as in all cases it'll be one request, this functionality is now obsolete)
    - Ensure to return `request` result from `sendPending`
1. [x] Rename `lib/utils/analytics` to `lib/utils/telemetry`
1. [x] Store locally usage data for each triggered command, send only at deploy:
   1. Remove sending analytics report from [internal deploy plugin](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/plugins/deploy.js#L56-L58)
   1. Rename [`sendPending`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/utils/analytics/index.js#L119) to `send`
   1. Rename [`report`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/utils/analytics/index.js#L92) to `storeLocally` (better name welcome - this method will just store event in local `~/.serverless` dir)
   1. Update `storeLocally` to not run `request` but just store the event
   1. Upgrade `generatePayload`:
      - Do not set service specific properties on payload if (1) there's no `config.servicePath` _or_ (2) command is listed as service independent (is included in [`lib/cli/commands-schema/no-service`](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/cli/commands-schema/no-service.js) map with no `serviceDependencyMode` listed)
      - Set `command` property on payload to `serverless.processedInput.commands.join(" ")`
   1. Remove  `send` invocation from [current location](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/scripts/serverless.js#L34-L37)
   1. Invoke `storeLocally`, after [`initialize` lifecycle event hooks](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/classes/PluginManager.js#L585) are complete but before [any other lifecycle event is triggered](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/classes/PluginManager.js#L586). 
   1. if command is `deploy`, right after `storeLocally`, invoke `send` to send analytics for locally stored events to backend server. Handle it very same way as it was so far in [_deploy plugin_](https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/plugins/deploy.js#L56-L58):
      - Store result promise to `deferredBackendNotificationRequest` local variable (do not _await_ it)
      - After all lifecycle event hooks will be propagated, pass resolved value of `deferredBackendNotificationRequest` to `processBackendNotificationRequest`
1. [ ] Introduce "Telemetry" documentation page, which documents:
   - Purpose
   - Clarifies that only anonymous data is stored and that we do not identify and track users through it
   - Documents how user can opt-out
 
--- 

@pgrzesik let me know what you think

**Comment by pgrzesik** [comment]
Thanks @medikoo for an extensive proposal :+1: I agree with pretty much everything that is outlined above. One thing that needs to be considered is the fact that with `track` or `trackBatch`, we can only send events that are up to 5 days old, which suggest that in this case we might need to change the approach and use `import` API. The only caveat here is that it's not documented anywhere if that API has any Rate Limits in place - I'm waiting for a response from Mixpanel support to make that clear.

**Comment by medikoo** [comment]
> One thing that needs to be considered is the fact that with `track` or `trackBatch`, we can only send events that are up to 5 days old

This means that we probably should update our borderline from up to 7 days in the past to up to 5 days in the past.
