### ISSUE TITLE
use Cached credentials for sls deploy command

### ISSUE THREAD

**Issue by s1mrankaur** [serverless/serverless#9258]
I am caching my credentials with aws-vault but sls deploy still prompts for the MFA code. Is there a way to use the cached credentials instead of being prompted for MFA code on every deploy?

**Comment by mikayla95** [comment]
have you looked into using an sts token? That's what I had to do to bypass MFA

**Comment by pgrzesik** [comment]
Hello @s1mrankaur - as this is more of a support question, I'm moving it to "Discussions" - this tracker is dedicated to feature requests and/or bugs reports.
