### ISSUE TITLE
Integration Testing in Serverless - Discussion

### ISSUE THREAD

**Issue by mwawrusch** [serverless/serverless#927]
it seems to me there is room for a plugin for serverless that handles integration testing. Let's discuss

**Comment by eahefnawy** [comment]
depending on how this plugin is designed, that could be really useful for us too. Since our unit tests are actually integration tests (we don't do mocking, we test on a real AWS test account).

**Comment by mwawrusch** [comment]
@eahefnawy Same here. Can you elaborate about the features you need / want  a bit.

**Comment by Spannella** [comment]
This sounds really interesting, some things I have been thinking of doing as I get time was to get into a pattern where I can do something like `sls interation-test <module>` which would load the stack to AWS and run it under a test stage for API Gateway, then pretty much there would be a pretest part of the script that would initialize stateful parts like putting some data in DynamoDB or S3. Then have a test part of the script to call the API run whatever tests for that state, then a post-test part of the script to clean up the state. Then report back the results of the tests. Then remove the stack. 
It should also be able to test API's that require authentication.

A bit beyond the core scope of serverless I have been thinking of end to end tests but that would include coordination with the static content plugin. And for that I was thinking of using Selenium to mess with full website.

Finally, I have been thinking of having a test suite triggered in the cloud on github pushes listening to github's webhook. The webhook would trigger API Gateway which would trigger a lambda function which would either mock what serverless does or just have serverless actually compiled in the /tmp directory, run serverless to run the integration tests then in the post tests part call SES to email me the results of the tests. If the results all passed then the email would include a button to setup a canary deployment routing maybe 10% of the traffic to the new version and setup cloudwatch alarms and finally, setup a scheduled lambda to SES me again after a fixed time the result of some predefined cloudwatch metrics and a button to do a full switch over. I haven't thought out DB migration for this much. I am pretty much shooting for a Blue/Green deployment pattern.

**Comment by flomotlik** [comment]
At the moment we don't plan to integrate a separate integration-test command into Serverless. in #1582 we're discussing different ways to make the developer tooling better with Serverless. One of the things that have vastly improved through the new CF deployment in V1 is that its now easy to deploy to a separate stage and then run integration tests against it.

As we do not plan to do anything in this direction at the moment I'm going to close this issue. But if somebody is interesting to take this up and implement something we'd be very open to it.
