### ISSUE TITLE
Make s-templates.json content accept Apache VTL in template definitions

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#929]
Currently it is very hard to code endpoint definitions like VTL enriched response template into a string.
The resulting string value for e.g. `responseTemplates` is hardly readable and even harder to debug.

An idea would be to allow VTL commands (e.g. `#set`) in the `s-templates.json` that would just copied verbatim into the stringified and escaped template reference. Then it would be easily possible to just state `"responseTemplate": $${myResponseTemplate}` and edit the template without cooking one's brain.

**Comment by HyperBrain** [comment]
CC @ac360 @eahefnawy

**Comment by erikerikson** [comment]
There was another issue written up that suggested that VTL snippets be loadable from files.  Something like... templates are expressed as "$T{TEMPLATE}", variables are expressed as "$V{VARIABLE}", and files are expressed as "$F{FILE_PATH}" and where the file's content would be stringified.

Adding this directly to the s-templates.json file would disrupt parsing and using the templates themselves unless the file was preprocessed as a VTL document first.  That might be a very good end state but I think the above is a simpler to implement iterative approach in that direction.  Just my 2 cents though.

**Comment by erikerikson** [comment]
see https://github.com/serverless/serverless/issues/645
I thought there were others but they aren't popping up.

**Comment by HyperBrain** [comment]
Maybe preprocessing the VTL enriched template file would do the trick. As every internal consumer uses the populate functionality to get the final configurations this would be a central place for a possible solution. Personally I do not like the idea of having different template variable specifiers. Despite of an easier implementation it would make the use more complex and error-prone (of course any solution would be better than the current state from the user side).

**Comment by HyperBrain** [comment]
I had another idea for a possible solution:

Alternatively we could add support for YAML. I mean that in a manner that one can use a `s-templates.yaml` instead of a `s-templates.json`.
The big advantage is, that YAML allows multiline verbatim declarations that even contain VTL statements (use of the `|` continuation token), so you can define your template like this:

```
...
    requestTemplate:
      application/json: |
        {
          "myvar": "test"
        #set( $date = $input.params('date') )
        #if( $date.toString() != "" )
          ,"date": "$input.params('date')"
        #end
        }
...
```

Internally we could use `js-yaml` to transform the yaml transparently to a JSON object which could be used in the existing pipeline throughout populate. This would be little effort to implement. One could then mix yaml and json template files which would just be merged and handled like it is now with json only.
I could try to implement this in a private branch to see how it would work.
@eahefnawy @erikerikson What do you think?

**Comment by HyperBrain** [comment]
@erikerikson @eahefnawy @ac360 
Ok, I did an implementation that only has changes in the Serializer class. With that you can now use `s-templates.yaml` instead of `s-templates.json` in any place of your project structure and even mix them if necessary.
The only condition is, that per directory only a `JSON` or a `YAML`may exist. If you have both, the JSON will be used.
With that change it is really easy to create templates that contain VTL (as mentioned in my prior post).
Could you please try my branch? (see the commit above).

**Comment by rajington** [comment]
Awesome, I'll check out your branch. YAML could have a lot of advantages over CloudFormation JSON, you could reuse components using anchors and references, and there's extensions to do importing. A YAML configuration describing an AWS project could be a lot more concise and even autogenerate things like roles and policies.

**Comment by HyperBrain** [comment]
The CF template is currently not supported yet, but I can try to add that too. `s-templates` is in my opinion the most urgent one as the APIG VTL definitions are really a PITA.

**Comment by HyperBrain** [comment]
Tested by @dijitalmunky.

**Comment by dijitalmunky** [comment]
Yes, yes it was!  Good work @HyperBrain!

**Comment by jonathannaguin** [comment]
Thanks @HyperBrain, this looks great!

**Comment by ac360** [comment]
Thanks @HyperBrain and everyone else.  We're going to review this internally and talk about a broader YAML/JS strategy for the config files.
