### ISSUE TITLE
Add ability to specify lambda version description

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#930]
currently `sls function deploy` hard codes the `s-function.json:description` as the description for the lambda version that is auto-created.  This is a good default, but I it would be cool if there was a flag to specify a description for the version you are about to deploy.  Sort of like how git works. Ex:

`sls function deploy show -m 'added cool functionality'`

Does this exist functionality exist already and I'm just missing it? If not I'm willing to write.

**Comment by HyperBrain** [comment]
I like the idea, but think that it should be separated from the function description as this is used in the AWS Lambda console's function overview.
Could this be a command line only thing, as it would be used most likely by CI/CD?

**Comment by doapp-ryanp** [comment]
@HyperBrain as it sits today, its already tied to `s-function.json`'s `description` attribute - you have no control.  The lambda version description is listed in the console UI below each version and the `$LATEST` version description is bubbled up to the lambda overview console UI.

My proposal is to separate the setting of this string away from just `s-function.json`.  However we still need a default to fall back to - IMO `s-function.json`'s `description` attribute is a good fallback.

> Could this be a command line only thing, as it would be used most likely by CI/CD

Isn't command line the only way currently to deploy a serverless function?  Even if there is eventually some web UI to do it, I'd still want the ability to set the description text for the lambda version im deploying.

**Comment by HyperBrain** [comment]
@doapp-ryanp Ok. I think the easiest way would just be a new option (like the -m you mentioned) to `function deploy` that will overwrite the description coming from the `s-function.json`. Then the old way would still work, but you have full control during deployment.

**Comment by doapp-ryanp** [comment]
Cool. Hope to make a PR with this function later today

**Comment by HyperBrain** [comment]
Regarding the option name: maybe -d and --desc would be better than -m as it overrides the description attribute?

**Comment by doapp-ryanp** [comment]
Yea thats a good idea. `-m` was just a copy from `git` and doesn't fit well in this scenario

**Comment by doapp-ryanp** [comment]
So turns out because serverless is using the atomic `Publish` (which I think it should be) there is no way to set the description for the version without changing the overall function description.

Said another way, the [createFunction](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property) and [updateFunctionCode](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionCode-property) APIs don't allow a distinction between the overall lambda description and the description for the version it will publish.

😢 

I have submitted a feature request [here on the forums](https://forums.aws.amazon.com/thread.jspa?threadID=228688)

**Comment by flomotlik** [comment]
As it seems we can't really fix this I will close this issue. I do like the feature though, @doapp-ryanp can you keep us up to date and reopen if you hear back from AWS?
