### ISSUE TITLE
Allow to opt-out from backend notifications

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9303]
### Use case description

Currently back-end notifications are shown unconditionally, which adds unwanted noise to CI systems. It'll be good to improve the experience and allow to hide them 

#### Strategy

We have two kind of notifications (1) Ones that promote new functionalities (2) Ones that indicate that used version is outdated. I believe we should be able to mute first ones but leave the ability to stick to latter ones.

I propose to introduce support for `SLS_NOTIFICATIONS_MODE` environment variable, with three possible settings:
  - `0` - All notifications off
  - `1` - Only present notifications that inform of new releases
  - `2` - Allow all notifications
 
Additionally in CI environment I would default the setting to `1`

#### Tactics

Apply necessary changes in [`lib/utils/processBackendNotificationRequest.js`](https://github.com/serverless/serverless/blob/ef25d681372d1ef16cdba24981a41eb957e59821/lib/utils/processBackendNotificationRequest.js)

Detect CI environment with help of `ci-info` package (which we already use when constructing telemetry payload)

Notifications that inform of new releases can detected by inspecting `notification.code` which would be either `OUTDATED_MINOR_VERSION` or `OUTDATED_MAJOR_VERSION` in such case

**Comment by medikoo** [comment]
@pgrzesik let me know what you think

**Comment by pgrzesik** [comment]
Thanks for the proposal @medikoo - it looks good in my opinion. I believe we should also add information about it as a part of documentation that will be introduced in https://github.com/serverless/serverless/issues/9257. What do you think?

**Comment by medikoo** [comment]
> I believe we should also add information about it as a part of documentation that will be introduced in #9257. What do you think?

That's good idea. I believe that definitely in telemetry document we need to mention fact that turning it off, also effectively turns off backend notifications. We probably should make this `Telemetry / Announcements service` page and introduce there two sections

**Comment by pgrzesik** [comment]
Hello again :wave: I've went with the implementation in Framework, however, I've noticed that main processing of the notifications happens in `serverless/utils` repository and even if we skip showing the notification on Framework side, the notification will be still marked in `.serverlessrc` as displayed due to logic in https://github.com/serverless/utils/blob/master/process-backend-notification-request.js

What do you think about placing the logic about disabling notifications as a part of that module?

**Comment by medikoo** [comment]
> What do you think about placing the logic about disabling notifications as a part of that module in serverless/utils?

it's a great idea. That way it'll also apply to all CLI's

**Comment by pgrzesik** [comment]
This has been addressed in https://github.com/serverless/utils/pull/80
