### ISSUE TITLE
Serverless starter cannot install when used with Node 5

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#931]
If you try `serverless project install serverless-starter` the install will not succeed when using Node v5 with NPM 3.x.
```
Serverless: Downloading project and installing dependencies...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
fn = function () { throw arg; };
^
ServerlessError: This plugin could not be found: serverless-optimizer-plugin
```
The reason is that the project install cannot handle the new optimized and flattened `node_modules` directory structure created by NPM 3.xx.

To make it work with the newer version `npm install` should be called with the `--legacy-bundling` option within the install command to create the legacy `node_modules` directory structure as long as Serverless is not fully compliant.

**Comment by HyperBrain** [comment]
BTW: The Node v5 incompatibilities/instructions should be explicitly mentioned in a separate `compatibility` section of the documentation as also `browserify` has some issues in that area.

**Comment by eahefnawy** [comment]
This has been addressed and fixed in #904 but not released yet. Could you try using master to install and see if it works?

**Comment by HyperBrain** [comment]
@betarelease Could you use the master branch of serverless and try again with your Node 5?

**Comment by flomotlik** [comment]
It looks like this was fixed. Closing for now.
