### ISSUE TITLE
CLI: Deprecate `sls deploy -f <function-name>`

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9312]
### Use case description

There's a dedicated CLI command `deploy function -f <function-name>` for single function deployment. Still same can theoretically be achieved via `deploy -f <function-name>`.

It's problematic alias as both commands accept different options:
- https://github.com/serverless/serverless/blob/712a569d5258f7770d4c23d8f0803c3d0062b79e/lib/cli/commands-schema/aws-service.js#L10-L36
- https://github.com/serverless/serverless/blob/712a569d5258f7770d4c23d8f0803c3d0062b79e/lib/cli/commands-schema/aws-service.js#L52-L65

Also they're backed with different lifecycle events, therefore there's a wide room for both variants to not behave perfectly same.

Ideally we should drop support for `sls deploy -f functioname`

### Proposed solution

1. Remove [`function` option](https://github.com/serverless/serverless/blob/712a569d5258f7770d4c23d8f0803c3d0062b79e/lib/cli/commands-schema/aws-service.js#L28-L31) from schema of `deploy` command
2. [Show deprecation](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations) if user invokes `sls deploy --function`. I believe it should be configured in [`deploy`](https://github.com/serverless/serverless/blob/712a569d5258f7770d4c23d8f0803c3d0062b79e/lib/plugins/deploy.js#L42) internal plugin, in newly introduced `initialize` hook

PR's welcome

**Comment by medikoo** [comment]
@pgrzesik let me know what you think about proposed solution

**Comment by jkklapp** [comment]
I'd like to take on this one if we have a green light on the proposal

**Comment by pgrzesik** [comment]
Thanks for proposal @medikoo - I fully agree that it's a problematic option. The proposal looks great, I don't have anything to add there.

**Comment by medikoo** [comment]
@jkklapp please do! We look forward
