### ISSUE TITLE
Serverless: Cannot process Stack Output: Cannot find module 'undefined/deploy/serverless/output'

### ISSUE THREAD

**Issue by camtechnet** [serverless/serverless#9336]
We use serverless-stack-output to store AWS CloudFormation Stack in JSON. We are driving our deploys through gitlab-ci

We have observed an error with serverless-stack-output after adopting serverless v 2.36.0 

We have reverted to serverless v 2.35.0 and the error is no longer appearing

I realise this may be an issue with the existing serverless-stack-output no longer with with v 2.36.0, but thought I should start by flagging the issue here

### 1. ERROR WITH SERVERLESS 2.36.0
Stack Outputs
$$$$$$FunctionQualifiedArn: arn:aws:lambda:$$$$$$:function:$$$$$$:10
ServicePrivateEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15/
ServiceEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15
ServerlessDeploymentBucketName: $$$$$$-serverlessdeploymentbucket-dfyyr09n4549
**Serverless: Cannot process Stack Output: Cannot find module 'undefined/deploy/serverless/output'**
Require stack:
- /builds/$$$$$$/node_modules/serverless-stack-output/dist/plugin.js
- /builds/$$$$$$/node_modules/serverless-stack-output/dist/index.js
- /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js
- /usr/local/lib/node_modules/serverless/lib/Serverless.js
- /usr/local/lib/node_modules/serverless/scripts/serverless.js
- /usr/local/lib/node_modules/serverless/bin/serverless.js!
$ cp .serverless/stack.json ./stack.json
**cp: cannot stat '.serverless/stack.json': No such file or directory**
Cleaning up file based variables
00:00
ERROR: Job failed: command terminated with exit code 1

### 2. CORRECT BEHAVIOUR WITH SERVERLESS 2.35.0
Stack Outputs
$$$$$$FunctionQualifiedArn: arn:aws:lambda:$$$$$$:function:$$$$$$:10
ServicePrivateEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15/
ServiceEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15
ServerlessDeploymentBucketName: $$$$$$-serverlessdeploymentbucket-dfyyr09n4549
Received Stack Output {
  $$$$$$FunctionQualifiedArn: arn:aws:lambda:$$$$$$:function:$$$$$$:10
  ServicePrivateEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15/
  ServiceEndpoint: https://$$$$$$.amazonaws.com/dev-mr-15
  ServerlessDeploymentBucketName: $$$$$$-serverlessdeploymentbucket-dfyyr09n4549
}
**Serverless: Stack Output processed with handler: deploy/serverless/output.handler
Serverless: Stack Output saved to file: .serverless/stack.json**
Serverless: Removing old service artifacts from S3...
**********
Serverless: Update available. Run "npm install -g serverless@^2.36.0" to update
            You may turn on automatic updates via "serverless config --autoupdate"
**********
$ cp .serverless/stack.json ./stack.json
Uploading artifacts for successful job
00:00
Uploading artifacts...
**stack.json: found 1 matching files and directories** 
Uploading artifacts as "archive" to coordinator... ok  id=52535 responseStatus=201 Created token=6DRFLrys
Cleaning up file based variables
00:00
Job succeeded

### 3 .gitlab-ci.yml
merge-request:serverless-deploy-api:
  image: node:latest
  extends: .template.generic-aws-assume-role
  stage: deploy-api
  variables:
    <<: *dev_variables
    STAGE: dev-mr-$CI_MERGE_REQUEST_IID
  environment:
    # git lab uses review/ to mark environment as ephemeral - this is tied to git branch name
    name: review/$CI_COMMIT_REF_NAME   
  script:
    - 'aws sts get-caller-identity'
    - 'npm install -g serverless@2.35.0'
    - 'npm install serverless-stack-output'
    - 'serverless -v'
    - 'npm view serverless-stack-output version'
    - 'sls deploy --config "$CI_PROJECT_DIR/deploy/serverless/api/serverless.yml" --verbose --stage $STAGE --artifact "$CI_PROJECT_DIR/artifacts/services-products-api.zip" --db $DB --db-username $DB_USERNAME --dbstage $DB_STAGE'
    ########## COMMAND THAT FAILS ##########
    - cp .serverless/stack.json ./stack.json
  dependencies:
    - lambda-package
  rules:
    - if: $CI_MERGE_REQUEST_IID
  artifacts:
    paths:
      - stack.json
     
### 4. serverless.yml 
custom:
  output: # serverless-stack-output
    handler: deploy/serverless/output.handler
    file: .serverless/stack.json

**Comment by pgrzesik** [comment]
Hello @camtechnet - could you please try using `2.37.0`? There was a bug in `2.36.0` that might be causing the above issue.

**Comment by camtechnet** [comment]
Good Morning @pgrzesik - thanks for the update. I have updated to `2.37.0` and it seems to be working fine. I will advise another our devs and just confirm from others. 
Thanks for the speedy response

**Comment by pgrzesik** [comment]
Thanks for letting us know @camtechnet that `2.37.0` resolved the issue. I'm going to close this one but feel free to reach out again if you experience more problems.
