### ISSUE TITLE
ENOENT: no such file or directory, stat '/github/workspace/.build/.serverless'

### ISSUE THREAD

**Issue by adamlass** [serverless/serverless#9337]
After release `2.37.0` I'm getting following error when building my project on Github Actions: `ENOENT: no such file or directory, stat '/github/workspace/.build/.serverless'`. This wasn't a problem before release `2.36.0` yearlier today, but this release caused me other building issues reported in [here](https://github.com/serverless/serverless/issues/9333). My suspicion is that something was changed in one of these releases that is breaking my build. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: xxx

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

provider:
  name: aws
  lambdaHashingVersion: xxx
  runtime: nodejs12.x
  stage: dev
  region: xxx
  apiGateway:
    shouldStartNameWithService: true
  environment:
    ...
  vpc:
    ...
  logs:
   ...
functions:
  ...

```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.environment.REDIS_DB": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.REDIS_PORT": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.REDIS_HOST": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.API_KEY_FACADE": Value not found at "env" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - REFETCH_FREQUENCY
Serverless: 	 - SHORT_LENGTH
Serverless: 	 - LONG_LENGTH
Serverless: 	 - API_KEY_LENGTH
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
 Error ---------------------------------------------------
 
  Error: ENOENT: no such file or directory, stat '/github/workspace/.build/.serverless'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.37.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.37.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```

**Comment by pgrzesik** [comment]
Hello @adamlass, thanks for reporting - do you have the ability to run the command with `SLS_DEBUG=*` env var for more extensive output log? That would help out with debugging :bow:

**Comment by hoangenouvo** [comment]
@adamlass got the same error too.

**Comment by adamlass** [comment]
> Hello @adamlass, thanks for reporting - do you have the ability to run the command with `SLS_DEBUG=*` env var for more extensive output log? That would help out with debugging 🙇

Yes I'm trying to figure out how to inject it into the Github Action script, im using the `serverless/github-action@master` action. Have any ideas?

**Comment by hoangenouvo** [comment]
Hi guys, FYI I try with serverless@2.32.1 and it worked. 👯

**Comment by adamlass** [comment]
> Hi guys, FYI I try with serverless@2.32.1 and it worked. 👯

Yes, i was even able to go up to `2.35.0`, but its not ideal 😃

**Comment by adamlass** [comment]
> Hello @adamlass, thanks for reporting - do you have the ability to run the command with `SLS_DEBUG=*` env var for more extensive output log? That would help out with debugging 🙇

I think i have `SLS_DEBUG=*` working now... Here is my current output:

Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.environment.REDIS_DB": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.REDIS_PORT": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.REDIS_HOST": Value not found at "env" source,
              - Cannot resolve variable at "provider.environment.API_KEY_FACADE": Value not found at "env" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.37.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - REFETCH_FREQUENCY
Serverless: 	 - SHORT_LENGTH
Serverless: 	 - LONG_LENGTH
Serverless: 	 - API_KEY_LENGTH
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
 Error ---------------------------------------------------
 
  Error: ENOENT: no such file or directory, stat '/github/workspace/.build/.serverless'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.37.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3

**Comment by adamlass** [comment]
> > Hello @adamlass, thanks for reporting - do you have the ability to run the command with `SLS_DEBUG=*` env var for more extensive output log? That would help out with debugging 🙇
> 
> I think i have `SLS_DEBUG=*` working now... Here is my current output:
> 
> Serverless: Deprecation warning: Variables resolver reports following resolution errors:
> - Cannot resolve variable at "provider.environment.REDIS_DB": Value not found at "env" source,
> - Cannot resolve variable at "provider.environment.REDIS_PORT": Value not found at "env" source,
> - Cannot resolve variable at "provider.environment.REDIS_HOST": Value not found at "env" source,
> - Cannot resolve variable at "provider.environment.API_KEY_FACADE": Value not found at "env" source
> From a next major this will be communicated with a thrown error.
> Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
> More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
> Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.37.0")
> 
> Serverless: Load command interactiveCli
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command config:tabcompletion
> Serverless: Load command config:tabcompletion:install
> Serverless: Load command config:tabcompletion:uninstall
> Serverless: Load command create
> Serverless: Load command install
> Serverless: Load command package
> Serverless: Load command deploy
> Serverless: Load command deploy:function
> Serverless: Load command deploy:list
> Serverless: Load command deploy:list:functions
> Serverless: Load command invoke
> Serverless: Load command invoke:local
> Serverless: Load command info
> Serverless: Load command logs
> Serverless: Load command metrics
> Serverless: Load command print
> Serverless: Load command remove
> Serverless: Load command rollback
> Serverless: Load command rollback:function
> Serverless: Load command slstats
> Serverless: Load command plugin
> Serverless: Load command plugin
> Serverless: Load command plugin:install
> Serverless: Load command plugin
> Serverless: Load command plugin:uninstall
> Serverless: Load command plugin
> Serverless: Load command plugin:list
> Serverless: Load command plugin
> Serverless: Load command plugin:search
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command upgrade
> Serverless: Load command uninstall
> Serverless: DOTENV: Loading environment variables from .env:
> Serverless: - REFETCH_FREQUENCY
> Serverless: - SHORT_LENGTH
> Serverless: - LONG_LENGTH
> Serverless: - API_KEY_LENGTH
> Serverless: Load command offline
> Serverless: Load command offline:start
> Serverless: Load command login
> Serverless: Load command logout
> Serverless: Load command generate-event
> Serverless: Load command test
> Serverless: Load command dashboard
> Serverless: Load command output
> Serverless: Load command output:get
> Serverless: Load command output:list
> Serverless: Load command param
> Serverless: Load command param:get
> Serverless: Load command param:list
> Serverless: Load command studio
> Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
> - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache"
> Please report this issue in plugin issue tracker.
> Starting with next major release, this will be communicated with a thrown error.
> More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
> Serverless: Invoke deploy
> Serverless: Invoke package
> Serverless: Invoke aws:common:validate
> Serverless: Invoke aws:common:cleanupTempDir
> Serverless: Compiling with Typescript...
> Serverless: Using local tsconfig.json
> Serverless: Typescript compiled.
> Serverless: Packaging service...
> Serverless: Excluding development dependencies...
> 
> Error ---------------------------------------------------
> 
> Error: ENOENT: no such file or directory, stat '/github/workspace/.build/.serverless'
> 
> Get Support --------------------------------------------
> Docs: docs.serverless.com
> Bugs: github.com/serverless/serverless/issues
> Issues: forum.serverless.com
> 
> Your Environment Information ---------------------------
> Operating System: linux
> Node Version: 14.16.1
> Framework Version: 2.37.0
> Plugin Version: 4.5.3
> SDK Version: 4.2.2
> Components Version: 3.8.3

Oh btw, i have removed the `"serverless":"^2.37.0"` declaration from my `package.json` now (in this output) so it uses the one from from `serverless/github-action@master`

This gives me following `serverless --version` output: 

```
Framework Core: 2.37.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```

**Comment by pgrzesik** [comment]
Thanks a lot @adamlass for additional details - looks like it's an issue with `serverless-plugin-typescript` in this particular case as it depends on internal properties that were changed with the release `2.36.0` (https://github.com/prisma-labs/serverless-plugin-typescript/blob/424fe4906bd15ceeeda6139dfe9e0f8bf873c4c3/src/index.ts#L145). Unfortunatelly, looks like the `serverless-plugin-typescript` is no longer maintained and most of the community members use `serverless-webpack` instead. I'll dig a bit more and in the meantime you will need to pin version to `2.35.0`. Sorry for inconvenience

**Comment by adamlass** [comment]
Thanks for the response and investigation! It's probably a good idea to migrate to `serverless-webpack` for my case then. Have a good evening!

**Comment by pgrzesik** [comment]
Hello @adamlass - we've released `2.37.1` that should address that issue (https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2371-2021-04-21)

**Comment by adamlass** [comment]
> Hello @adamlass - we've released `2.37.1` that should address that issue (https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2371-2021-04-21)

Okay, perfect! I will check it tomorrow and give you feedback then! Thank you for looking in to the issue!😊

**Comment by adamlass** [comment]
@pgrzesik - So I have tested it now, and everything seems to work as before `2.36.0`! Again, thank you for looking into the issue! 🥳

**Comment by adamlass** [comment]
Closing issue

**Comment by pgrzesik** [comment]
Thanks for following up :bow: happy to hear that issue is not resolved for you :+1:

**Comment by anil1712** [comment]
@adamlass I am still getting the same issue

```
Framework Core: 2.69.1
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```

**Comment by mvargas33** [comment]
I'm having this issue now, trying to run `sls deploy` with the following:

```
Environment: darwin, node 20.10.0
framework 3.38.0 (local) 3.30.1v (global)
plugin 7.2.0
SDK 4.5.1
```
