### ISSUE TITLE
Allow us to provide custom CFN stack name

### ISSUE THREAD

**Issue by carolynnvu** [serverless/serverless#934]
Right now it seems Serverless only allows the format $project-$stage-r.

**Comment by erikerikson** [comment]
@carolynnvu This is already possible.  The code looks for the variable `resourcesStackName` (see https://github.com/serverless/serverless/blob/master/lib/actions/ResourcesDeploy.js#L259). If you define that, you should get what you're asking for.  Heads up that you might run into https://github.com/serverless/serverless/issues/791.

**Comment by flomotlik** [comment]
As its already answered I'm closing this issue
