### ISSUE TITLE
Allow overriding default IAM Role Path

### ISSUE THREAD

**Issue by Android3000** [serverless/serverless#9347]
### Override default IAM Role Path

Currently, the default role, IamRoleLambdaExecution, is generated with a Path of "/". It would be nice to be able to override this Path to a chosen value. There was actually a similar change proposed and made over in CDK as some organizations require role paths to be present for enforcement logic.

### Proposed solution

Add a `path` property like so:
```
provider:
  iam:
    role:
      path: /your-custom-path/
```

The role name currently can be overridden using the approach above (but with `name` instead of `path`). Under [naming.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js), the `getRoleName` function either uses the provided value or a default value, whereas `getRolePath` just returns `/` -- but this could be easily customized to return the user provided path.

Are there any reasons why changing the default path could cause issues with other Serverless functionality? If not, I could make this change and submit a PR.

**Comment by pgrzesik** [comment]
Hello @Android3000 - thanks for the proposal. I believe it makes sense and I don't see anything preventing us from allowing to accept an optional path. PR would be more than welcome, thank you :bow:

**Comment by Android3000** [comment]
That sounds great @pgrzesik , I will try to get a PR in this weekend. Thanks!

**Comment by bargerE69** [comment]
> ### Override default IAM Role Path
> Currently, the default role, IamRoleLambdaExecution, is generated with a Path of "/". It would be nice to be able to override this Path to a chosen value. There was actually a similar change proposed and made over in CDK as some organizations require role paths to be present for enforcement logic.
> 
> ### Proposed solution
> Add a `path` property like so:
> 
> ```
> provider:
>   iam:
>     role:
>       path: /your-custom-path/
> ```
> 
> The role name currently can be overridden using the approach above (but with `name` instead of `path`). Under [naming.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js), the `getRoleName` function either uses the provided value or a default value, whereas `getRolePath` just returns `/` -- but this could be easily customized to return the user provided path.
> 
> Are there any reasons why changing the default path could cause issues with other Serverless functionality? If not, I could make this change and submit a PR.

[]()
