### ISSUE TITLE
CLI: Seclude interactive setup from internals

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9354]
### Use case description

Back when most of the CLI logic was hosted in `Serverless` side classes and utils, it felt easiest to configure the interactive CLI as one of the internal `Serverless` plugins.

Even though from start it imposed issues, as setting up a new service and for further steps assuming we're in context of just created service required hacking, which couldn't be 100% bulletproof (corresponding issue: https://github.com/serverless/serverless/issues/8257)

Now, when most of the CLI handling was refactored out out Framework internals it should be pretty straightforward to also move handling of this command out of `Serverless` class. it'll also pave the path to call multiple commands (as `create` and `deploy`) naturally in context of a interactive setup flow, and we need that, to further improve on-boarding experience

### Proposed solution

Let's seclude interactive setup internals from `Serverless` internal plugins, into `lib/cli/interactive-setup`

#### How to implement it?

1. Move implementation of each interactive CLI step to  `lib/cli/interactive-setup` folder. So each step is configured  in individual module, which exports `isApplicable` and `run` functions.
Both functions should take as input data object, with following properties: `configuration`, `serviceDir`, `configurationFilename`, `options`
1. Create a main interactive CLI module ( `lib/cli/interactive-setup/index.js`) which exports a function which:
   -  Accepts data object, with following properties: `configuration`, `serviceDir`, `configurationFilename`, `options`
   -  In internally specified order, invokes each interactive setup step, by first invoking `isApplicable(data)` and if it resolves with true, invoking `run(data)` of same step
   - It also runs interactive CLI setup steps, as implemented in new version of `@serverless/dashboard-plugin` (https://github.com/serverless/enterprise-plugin/issues/563)
1. In [`scripts/serverless.js`](https://github.com/serverless/serverless/blob/154351f1a5925a745873895014ed31f03b2842b3/scripts/serverless.js#L358-L359) if `!isHelpRequest` and `command === ''`, instead of creating a new `serverless` instance, run created in previous steps main interactive CLI module, and abort to not trigger any further flow
1. Update [lib/plugins/interactiveCli/index.js](https://github.com/serverless/serverless/blob/154351f1a5925a745873895014ed31f03b2842b3/lib/plugins/interactiveCli/index.js), so it's `constructor` is empty, while `asyncInit` maintains same resolution logic, but at logic point where [interactive CLI request was recognized and enforced](https://github.com/serverless/serverless/blob/154351f1a5925a745873895014ed31f03b2842b3/lib/plugins/interactiveCli/index.js#L82), instead throw error with request to update global installation to latest version (as we can end at this point only, if older global version fallen back to new local version). Mark whole plugin with _TODO_ comment so it's removed with next major
1. Tests for all the steps need to be maintained, they just need to be refactored so they work against `serverless` command directly

**Comment by medikoo** [comment]
@pgrzesik let me know what you think about that, and https://github.com/serverless/enterprise-plugin/issues/563

**Comment by pgrzesik** [comment]
Thanks for great proposal @medikoo. I have only minor question

> In scripts/serverless.js if !isHelpRequest and command === '', instead of creating a new serverless instance, run created in previous steps main interactive CLI module, and abort to not trigger any further flow

So in this case, we won't be at all falling back to local installation, is that correct? What about a situation where global installation is older and tries to fall back to local which no longer support `interactive` flow as it is implemented right now?

**Comment by medikoo** [comment]
>  What about a situation where global installation is older and tries to fall back to local which no longer support interactive flow as it is implemented right now?

@pgrzesik good question. I've outlined the solution for that in point (4), idea is to throw and request user to upgrade global installation

**Comment by pgrzesik** [comment]
Thanks, I've somehow missed that explanation but it makes total sense and should cover that situation well :+1:
