### ISSUE TITLE
AWS profile doesn't seem to be configured 

### ISSUE THREAD

**Issue by tweekes** [serverless/serverless#9366]
Hi!

This issue looked like #9190 but it's not. 
Running on Windows 10 and running cmd shell under current user - not running as Administrator.

Ran the following to ensure aws credentials are being picked-up
C:\Users\Tom\Documents\home\mydev\aws\lambdav2\hello-world-nodejs>aws s3 ls --profile serverless_admin
2021-04-22 22:06:51 2021-22-04-tw-test

serverless.yml: 
service: hello-world-nodejs
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1
  profile: serverless_admin  
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello

Run: 
C:\Users\Tom\Documents\home\mydev\aws\lambdav2\hello-world-nodejs>serverless deploy -v

Result: 
Serverless: Packaging service...
Serverless: Excluding development dependencies...

 Serverless Error ----------------------------------------

  **AWS profile "serverless_admin" doesn't seem to be configured**

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.13.0
     Framework Version:         2.37.2
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0

Thanks in advance!
..Tom

**Comment by medikoo** [comment]
@tweekes Framework doesn't support `--profile` option, it's `--aws-profile`. Run `sls deploy --help` to see list of all supported options

**Comment by tweekes** [comment]
@medikoo  I am not using `--profile` option. I ran `aws s3 ls --profile serverless_admin`  just to demonstrate that my aws environment was setup correctly.  Just ran `sls deploy -v`  again and still get the same result. 

```
service: hello-world-nodejs
frameworkVersion: '2'
provider:
  name: aws
  region: eu-west-1
  profile: serverless_admin
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
```
```
C:\Users\Tom\Documents\home\mydev\aws\lambdav2\hello-world-nodejs>sls deploy --verbose
credentialsFilePath: C:\Users\Tom\.aws\credentials
Serverless: Packaging service...
Serverless: Excluding development dependencies...

params: {"profile":"default"}

 profileCredentials.accessKeyId:undefined

 profileCredentials.sessionToken:undefined

 profileCredentials.roleArn:undefined

params: {"profile":"serverless_admin"}

 profileCredentials.accessKeyId:undefined

 profileCredentials.sessionToken:undefined

 profileCredentials.roleArn:undefined

 Serverless Error ----------------------------------------

  AWS profile "serverless_admin" doesn't seem to be configured

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.1
     Framework Version:         2.37.2
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0

```

**Comment by medikoo** [comment]
@tweekes indeed I misread your description.

Internally we read profile credentials via `aws-sdk` through [`new AWS.SharedIniFileCredentials({ profile })`](https://github.com/serverless/serverless/blob/7a0fbf7143ab9901517f9a67fcd228155fa8e47b/lib/plugins/aws/provider.js#L127) call and it appears that in your case it doesn't resolve the `serverless_admin`. Do you understand why it's the case?

**Comment by tweekes** [comment]
@medikoo, firstly thanks for engaging with my issue. 
I do not know why it doesn't resolve. I have just re-install serverless ... it went up a version but the problem is the same. :( 

Folder: C:\Users\Tom\.aws\credentials
contains:
[serverless_admin]
aws_access_key_id=AKIAXRQCZL--------24
aws_secret_access_key=Sv/--------R2iZZx8ArlSdrr+OfUQ3HyWe/s8

(I have obfuscated the keys.)

**Comment by medikoo** [comment]
@tweekes do you have maybe `AWS_SHARED_CREDENTIALS_FILE` environment variable set?

Can you confirm what output you get with following script:

```javascript
const AWS = require("aws-sdk");

console.log(new AWS.SharedIniFileCredentials({ profile: "test" }));
```

(just be sure to have `aws-sdk` npm package installed in location where you will run this script)

**Comment by tweekes** [comment]
@medikoo your suggestion gave me great foundation find the problem. I ended up getting this error:

Error: connect ENETUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:131:14)
aws-test1.js:6

which lead me to:
https://forums.aws.amazon.com/thread.jspa?threadID=299018

advised: 
set AWS_SDK_LOAD_CONFIG=1

Which resulted in: 
Error: ENOENT: no such file or directory, open 'C:\Users\Tom\Documents\home\.aws\config'

which meant looking in 'C:\Users\Tom\Documents\home\.aws\config' and not 'C:\Users\Tom\.aws\config'

Solution: copied 'C:\Users\Tom\.aws' to 'C:\Users\Tom\Documents\home\.aws'

Yes!!! I do have a **home** folder on my windows machine and this caused aws-sdk to look in the wrong place for the credential and config files.

Thanks again!

**Comment by medikoo** [comment]
@tweekes great to hear, that's sorted out!
