### ISSUE TITLE
opt:some_var Detected unrecognized CLI options

### ISSUE THREAD

**Issue by Wurstnase** [serverless/serverless#9371]
An opt:some_var produce a deprecation warning. The cf template looks ok.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
app: aws-python-rest-api
service: aws-python-rest-api

custom:
  runtime: python3.8

provider:
  name: aws
  runtime: ${opt:runtime, self:custom.runtime}
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* npx sls package --runtime python3.8</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.38.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Detected unrecognized CLI options: "--runtime".
            Starting with the next major, Serverless Framework will report them with a thrown error
            More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
Framework Core: 2.38.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by pgrzesik** [comment]
Hello @Wurstnase - support for custom CLI options is going to be deprecated in `3.0.0` and we recommend using e.g. environment variables in order to supply these type of custom parameters. Please see the deprecation notice documentation: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

**Comment by Wurstnase** [comment]
OK, I understand.
The part here: https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-cli-options
may need an update?
`some_option` looks like I can still make my own.

However, thanks for clarification.

**Comment by pgrzesik** [comment]
Thanks @Wurstnase - I'll try to adjust it a bit to not suggest that you can provide your own CLI options.

**Comment by uclaeamsavino** [comment]
If I have to use environment variables to replace the cli options I'm using now, it will increase the number of AWS codebuild projects I have to create by an order of magnitude. Is there any other solution to feed variable information to serverless.yml at run time vs. baked into a local environment variable?

**Comment by pgrzesik** [comment]
Hello @uclaeamsavino - could you please clarify why would you have to increase the number of AWS codebuild projects due to that? You can pass options via environment variables in a similar way as with options, e.g. instead of

```
sls deploy --some-option optionvalue
```

you can go with 

```
SOME_OPTION=optionvalue sls deploy
```

and then you can access that option via `${env:SOME_OPTION}`

so it shouldn't really require you create additional projects, but maybe I'm missing something here?

**Comment by uclaeamsavino** [comment]
I didn't think of that method of getting environment variables into the script. I will give it a try. Thanks.

**Comment by mike-suggitt** [comment]
> Hello @Wurstnase - support for custom CLI options is going to be deprecated in `3.0.0` and we recommend using e.g. environment variables in order to supply these type of custom parameters. Please see the deprecation notice documentation: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

Really disappointing decision. Backwards step

**Comment by mike-suggitt** [comment]
> Hello @Wurstnase - support for custom CLI options is going to be deprecated in `3.0.0` and we recommend using e.g. environment variables in order to supply these type of custom parameters. Please see the deprecation notice documentation: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

Would you be able to tell me the last serverless version that supports custom CLI options at all please? I want to lock my package.json

**Comment by lehmat** [comment]
There is no easy way to use environment variables on PowerShell without writing custom scripts. Any chance you could support this going forward? Really cripples windows users since WSL 2 is out of the question due to slowness of reading files from host.

**Comment by pgrzesik** [comment]
Hey @lehmat :wave: At the moment there are no plans, since supporting freeform variables via CLI flags will require us to disable schema validation for command options. We briefly discussed possibility of adding support for such vars via additional flag, but nothing concrete yet

**Comment by lehmat** [comment]
I would appreciate if you could take the powershell ecosystem into consideration in your plans. I trust your judgment.

**Comment by pgrzesik** [comment]
Will do, thanks for reporting this @lehmat :bow:

**Comment by pgrzesik** [comment]
Hello @lehmat and everyone that contributed to this thread - I've created a separate ticket along with proposal on how we can support custom CLI options moving forward. Please feel free to share your feedback there, thanks in advance :bow: 

Link: https://github.com/serverless/serverless/issues/9817
