### ISSUE TITLE
aws ecr support for scan on push configuration option

### ISSUE THREAD

**Issue by wwwehr** [serverless/serverless#9377]
### Use case description
As a sec ops engineer, when a ECR repository is created, I want to be able to have scanOnPush option set so that we can comply with our security considerations.

### Proposed solution
Enable configuration pass through to the ECR creationg; default (according to aws api) is `false`

**Comment by pgrzesik** [comment]
Thank you for proposal @wwwehr. I was considering to maybe nest this property under `ecr.repository` namespace in setting, but at the moment it would be the only property nested so it doesn't make sense yet. If there will be more repository-related properties in the future, we can rename that property.

**Comment by wwwehr** [comment]
@pgrzesik related to this, I saw the feature request for kms key selection and the like. Absolutely, having these options grouped together make sense. If I get some time, I might tackle that feature - it was certainly more complicated as we'd want to handle the available config options. When you introduce a new property "grouping" like that, do you still have to support the old property (ungrouped)?

**Comment by pgrzesik** [comment]
Hello @wwwehr :wave: I'm assuming this is the ticket you have in mind - https://github.com/serverless/serverless/issues/9083

Usually, when we group properties under a single namespace, we configure deprecation for the old notation, while still supporting it and remove support for old notation with next major version. Grouping `iam`-related properties is one of such examples: https://github.com/serverless/serverless/blob/master/docs/deprecations.md#grouping-iam-settings-under-provideriam

In this case, however, while it might be nice to group it at some point in the future, having both encryption and `scanOnPush` properties on `ecr` level will also be fine I think :+1:
