### ISSUE TITLE
Telemetry: Report used command options

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9385]
### Use case description

Having knowledge of what options were used with a command, will allow us to:
- Distinguish between `sls deploy` and `sls deploy --help`
- Distinguish `sls deploy -f` (which technically is an alias for `sls deploy function`
- Options reflect some functionalities, so knowing they're usage we would know what's the usage of given functionality

### Proposed solution

- Report just option names, no values, to not leak any user sensitive data
- Report only options which are covered by schema (so by accident we do not leak user personal data, and simply to avoid noise of typos in data)
- Send with `commandOptionNames` property

### How to implement it?

@pgrzesik I think we  may jump to implementation directly, but if you prefer to coin implementation spec, that's totally good, I'll leave it to you this time :)

**Comment by pgrzesik** [comment]
Thanks @medikoo. I don't think we need detailed implementation spec in this particular case. I have one question though - what's your opinion on recording commands with `--help` option? Should we skip them or should we record them?

**Comment by medikoo** [comment]
> Should we skip them or should we record them?

That's a good question. My first thought is that it's nice to have them, as a way to see the user journey. Still when I think of all the data that's send with event (which in case of `help` is pretty meaningless) I have a second though, and think that maybe it'll be cleaner to discard them. It's like user looking for documentation.

I suggest to confirm with @ac360 on Slack
