### ISSUE TITLE
Generated Scheduled Event configuration should explicitly include `enabled: false`

### ISSUE THREAD

**Issue by ianserlin** [serverless/serverless#939]
v0.5.1

When generating a new scheduled-type event, the resulting snippet added to `s-function.json` is:

_Current_
```
  "events": [
    {
      "name": "mySchedule",
      "type": "schedule",
      "config": {
        "schedule": "rate(5 minutes)"
      }
    }
  ],
```

_Proposed_
```
  "events": [
    {
      "name": "mySchedule",
      "type": "schedule",
      "config": {
        "enabled": false,
        "schedule": "rate(5 minutes)"
      }
    }
  ],
```

For anyone not well versed in AWS (some large proportion of serverless's target userbase), it's non-obvious that the event, when deployed, will not be enabled. I believe this also does not match the deployed enabled/disabled state of other triggers like DynamoDB streams. While this flag is mentioned in the guide, adding the line `"enabled": false` by default will help make it easier for people to reason about what is happening when they expect to see their lamdba running/events hooked up in the AWS Console after deployment, but have not enabled the CloudWatch Event yet.

**Comment by flomotlik** [comment]
We're going to completely change how to set this up in V1, so I'm going to close this issue for now. But thanks for reporting @ianserlin
