### ISSUE TITLE
Support S3 URI format for package artifact

### ISSUE THREAD

**Issue by zachwhaley** [serverless/serverless#9403]
### Use case description

Serverless supports downloading and using a package artifact from an S3 bucket, but it only allows the outdated global legacy path style S3 URL format (e.g. `s3.amazonaws.com/bucket/path`) which can be confusing when the AWS web console will give a URL like `bucket.s3.us-west-2.amazonaws.com/path`.

There are other S3 bucket URI formats.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html

### Proposed solution

Under the hood, Serverless is just parsing this string for the bucket and path, and then making a call to AWS JS SDK `S3.getObject()`

I propose Serverless should add support for the more basic and easier to parse S3 URI format: `S3://bucket-name/key-name` and docs should suggest using this format instead of the legacy format.

**Comment by pgrzesik** [comment]
Hello @zachwhaley - I believe this was just addressed by: https://github.com/serverless/serverless/pull/9380

Could you confirm that's the case?

**Comment by zachwhaley** [comment]
Oh wow, merged 4 hours ago 😄

The changes do not seem to account for Region in the old URL style, but that’s a big deal since the new S3 URI is preferred.

**Comment by pgrzesik** [comment]
Thanks for bringing that up @zachwhaley - we should definitely support and properly handler old-style URLs with region in mind. Would you be interested in submitting a PR for that?

**Comment by zachwhaley** [comment]
Sure thing!  I’ll give it a go :)

**Comment by bishtawi** [comment]
It should be fairly easy to update the regexes to support region urls.

In `lib/plugins/aws/utils/parse-s3-uri.js `:
The regex `([^/]+)\\.s3\\.amazonaws\\.com/(.+)` becomes `([^/]+)\\.s3(?:(?:\\.|-).+)?\\.amazonaws\\.com/(.+)`
And `s3\\.amazonaws\\.com/([^/]+)/(.+)` becomes `s3(?:(?:\\.|-).+)?\\.amazonaws\\.com/([^/]+)/(.+)`

**Comment by bishtawi** [comment]
You can even replace the `(?:(?:\\.|-).+)?` with just `.*` to keep the regex a little more simple I suppose.
