### ISSUE TITLE
Changelog: Patch changes

### ISSUE THREAD

**Issue by goncaloneves** [serverless/serverless#941]
This is a **documentation** _enhancement_ request.

Can we have logs of patch releases so we can keep following of what's changing/fixed in the src without needing to go through the commits ? This will make things easier for maintenance purposes in the long run.

Edit: Meant only patch releases not minor.

Thank you.

**Comment by dherault** [comment]
Yes +1, it took me some time to find the differences between v0.5.3 and v0.5.5. A change log or better usage of Github's release feature would be awesome.

**Comment by martinmicunda** [comment]
same here .. A change log or some notes in Github releases would be nice as going through every commit in master branch is not always ideal :). @ac360 @eahefnawy

**Comment by HyperBrain** [comment]
Maybe a list of issues that have merged PR's and are considered fixed would be enough as release notes.

**Comment by JamieCressey** [comment]
+1. I have no idea what's in 0.5.5 and if it's worth my time upgrading from 0.5.3.

https://github.com/skywinder/github-changelog-generator seems to work quite well.

**Comment by flomotlik** [comment]
Agreed, will think about a way to do this with the release of V1
