### ISSUE TITLE
Security vulnerability in xmlhttprequest-ssl (via engine.io-client)

### ISSUE THREAD

**Issue by anthonyangel** [serverless/serverless#9431]
I have serverless pinned to version 2.39.2 in my project, Dependabot is showing the following security alert with a transitive dependency `serverless@2.39.2 requires xmlhttprequest-ssl@~1.5.4 via a transitive dependency on engine.io-client@3.5.1`

engine.io-client had a breaking change and skipped from 3.5.1 to 5.0.0, the latest version there is 5.1.0

<b>Installed version</b>

```
2.39.2
```

**Comment by bdo** [comment]
Engine.IO client have released version 4.1.4 which fixes the dependency:
https://github.com/socketio/engine.io-client/releases/tag/4.1.4

**Comment by pgrzesik** [comment]
Hello everyone :wave: Fresh installation of the Framework should no longer install the faulty dependency. I'm closing this issue but if you're still experiencing issues, please feel free to reach out :100:

**Comment by julien-HAM** [comment]
Hi @pgrzesik,
I just installed serverless@2.40.0 and then run an audit and the vulnerability is still there.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary Code Injection                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ xmlhttprequest-ssl                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.6.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ serverless                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ serverless > @serverless/components >                        │
│               │ @serverless/platform-client-china > @serverless/utils-china  │
│               │ > socket.io-client > engine.io-client > xmlhttprequest-ssl   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1665                        │
```

**Comment by pgrzesik** [comment]
How did you install it @julien-HAM? What OS are you using? I've just verified once again with a fresh installation of `serverless` via `npm i serverless` and there are not security vulnerabilities reported - the `xmlhttprequest-ssl` is installed in `1.6.2` version.

**Comment by julien-HAM** [comment]
Hi @pgrzesik,
Thanks for your fast reply.

The issue was with yarn cache.

I had serverless@2.40.0 already installed before the lastest package update.

I had to run `yarn remove serverless` then `yarn cache clean` to get the updated version of the package with your fix.

I can confirm that this is now working and that there are no security vulnerabilities reported for the xmlhttprequest-ssl.

**Comment by pgrzesik** [comment]
Perfect, thanks for letting me know @julien-HAM :bow:
