### ISSUE TITLE
Function remove broken

### ISSUE THREAD

**Issue by carolynnvu** [serverless/serverless#945]
Hi, 

I'm having trouble with the ```sls function remove myFunction``` command. Serverless is returning the following output:

```
Serverless: Removing functions in "myStage" from the following regions: us-east-1
Serverless: ------------------------
Serverless: Failed to remove the following functions in "myStage" from the following regions:
Serverless: us-east-1 ------------------------
Serverless:   myFunction: Endpoint "myFunction#GET" doesn't exist in your project
```

However, my endpoint does exist. I've deployed it with ```sls endpoint deploy``` and it appears/works fine in API Gateway. 

Thanks in advance.

**Comment by HyperBrain** [comment]
Which version of Serverless do you use?

**Comment by HyperBrain** [comment]
This has been fixed by https://github.com/serverless/serverless/commit/577de00b7e0fe7ce199dd1a6a23ea8ae1682878c

Most likely it is not yet published.

**Comment by flomotlik** [comment]
This was released now, closing this issue
