### ISSUE TITLE
Options shortcuts of common commands are no more parsed for no AWS providers

### ISSUE THREAD

**Issue by CorentinDoue** [serverless/serverless#9452]
Common commands defined by the framework and which schema are defined in `lib/cli/commands-schema/aws-service.js` can't be used with a shortcut with another provider than AWS. 

This PR https://github.com/serverless/serverless/pull/9151 breaks it.

Example:
I try to add the support of `sls invoke local` for in the [GCP plugin](https://github.com/serverless/serverless-google-cloudfunctions). To test support with compiled code I use https://github.com/serverless-heaven/serverless-webpack. 

I compared the behavior between AWS and GCP.

```bash
yarn sls invoke -f <my-function-name>
```

**AWS**
1. The schema of command is resolved in `scripts/serverless.js:252` before the instantiation of `serverless` and the options are parsed
2.  `serverless = new Serverless()` is instantiated with the parsed options `{function: "<my-function-name>"}`
3. The plugin serverless-webpack is loaded with the parsed options
4. The plugin `AwsInvokeLocal` is loaded with the parsed options
5. Everything goes well

**GCP**
1. The schema of command is never resolved because the provider is not `'aws'` (`scripts/serverless.js:252`)
2.  `serverless = new Serverless()` is instantiated with the raw options `f: "<my-function-name>"}`
3. The plugin serverless-webpack is loaded with the raw options
4. My new plugin `GoogleInvokeLocal` is loaded with the raw options
5. Serverless-webpack crash because is designed to work with `function` option

I read the comment of @medikoo in https://github.com/serverless/serverless/pull/9151 and tried to explicitly declare the command `invoke local` in the context of `GoogleInvokeLocal` but it changes nothing because the options are resolved before loading any plugin.

I can reprocess the options to resolve the shortcut in `GoogleInvokeLocal` but I can't in serverless-webpack.

Do you consider this as a bug or should I drop the support of shortcuts?

**Comment by CorentinDoue** [comment]
Ok 

So the good practice is to not use the options provided to the constructor because they are not the final options but to set the options in the `initialize` hook.

```js
class GoogleInvokeLocal {
    constructor(serverless, options) {
        this.serverless = serverless;
        this.options = options; // <-- this are raw options they should not be used to unsure compatibility with no-AWS provider
        this.provider = this.serverless.getProvider('google');

        this.hooks = {
            'initialize': () => {
                    this.options = this.serverless['somePath'].options;  // <-- this are parsed options which should be used
            },
            'invoke:local:invoke': async () => this.invokeLocal(),
        };
    }
}
```

And I should open an issue in `serverless-webpack` to implement the options resolution in `initialize` to make the plugin compatible with GCP.

Am I right?

**Comment by medikoo** [comment]
> So the good practice is to not use the options provided to the constructor because they are not the final options but to set the options in the initialize hook.

Technically it's ok to read those options in constructor, but final format (_boolean_, _string_ or _array_) is not guaranteed to reflect the specified option type, e.g. if plugin defines an option as _multiple_, the option as passed here, may be a _single string_, or _array_. 

In `initialize` hook, options are fully resolved and reflect configured types, they're accesible at `this.serverless.processedInput.options`

**Comment by CorentinDoue** [comment]
There is nothing more to do here. Except perhaps document it in a "how to write a plugin". 

The magic snipet to create a plugin with a non-AWS provider or non-standard command is:

```js
this.hooks = {
      initialize: () => {
        this.options = this.serverless.processedInput.options;
      }
}
```

**Comment by medikoo** [comment]
> There is nothing more to do here. Except perhaps document it in a "how to write a plugin".

We will definitely improve our doc on that. Thanks for input

**Comment by CorentinDoue** [comment]
I reopen the issue because the shared `invoke` plugin uses `env`. The shortcut (`-e`) of this option is not parsed when it is used with non-AWS providers.

Example:
```sh
sls invoke local -f myFunction -e MY_VAR=myValue
```
will not inject environment variable if used with google provider.

I fix it in the following PR
