### ISSUE TITLE
Serverless 2.4.1 - "Could not resolve path to locally installed serverless."

### ISSUE THREAD

**Issue by rolfsynthesis** [serverless/serverless#9462]
Since upgrading from 2.4.0 to 2.4.1 sls, the following issue below was detected:

serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
 
 Serverless Error ----------------------------------------
 
  Could not resolve path to locally installed serverless.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.41.0
     Plugin Version:            4.6.0
     SDK Version:               4.2.2
     Components Version:        3.9.2

**Comment by pgrzesik** [comment]
Thanks for reporting @rolfsynthesis - it will be fixed with next release.
