### ISSUE TITLE
Files named ".env*" are removed from deployed zip

### ISSUE THREAD

**Issue by Nyholm** [serverless/serverless#9484]
When I run `serverless deploy` with `useDotenv: true` then all the `.env*` files are missing from the zip archive that are uploaded to AWS. 

If I remove `useDotenv: true` it all works. 
I still need the .env files in my deployed application, even though `serverless` will read them. 

Also, I would like to note that Im not happy with `useDotenv: false` is not working..

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ... 
useDotenv: true
# Other irrelevant stuff
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service xxxxx.zip file to S3 (3.58 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: xxxx
stage: prod
region: us-east-1
stack: xxxx
resources: 12
api keys:
  None
endpoints:
  ANY - 
functions:

...
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: Removing old service artifacts from S3...

```

</details>

<b>Installed version</b>

```
❯ serverless -v
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.41.2 (local)
Plugin: 5.0.0
SDK: 4.2.2
Components: 3.9.2
```

**Comment by pgrzesik** [comment]
Hello @Nyholm, thanks for reporting. Not including `.env` files with `useDotenv` enabled was introduced as a safety measure, to not include static files that might potentially have sensitive information stored in them, however, it should still be possible to force including them via `patterns` property., e.g.

```
package:
  patterns:
    - '.env'
```

As for the:
> Also, I would like to note that Im not happy with useDotenv: false is not working..

Could you please clarify what is problematic here? Is there a use case that is not possible due to loading env variables locally automatically? Could you please describe it here: https://github.com/serverless/serverless/issues/8566 as it's the place where we discuss the potential reason to implement a solution that will allow to disable this behavior

**Comment by pgrzesik** [comment]
I'm going to close this one and please let's continue the discussion in https://github.com/serverless/serverless/issues/8566 :bow:

**Comment by Nyholm** [comment]
Thank you for the workaround. 

From my point of view: 
I have an application with two files in the root: 
1. `.env`
2. `.env.local.php`

None of them is needed for Serverless. The `.env.local.php` is needed for my production environment. 

I dont mind that Serverless is reading `.env`, but I dont see that it is necessary. And I am surely surprised that `.env.local.php` was removed. 

I have been following the discussions in  #8566 for a while. 

I'll follow up with a comment in the other thread.
