### ISSUE TITLE
Support creating APIG HTTP proxy endpoints

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#950]
Currently the creation of APIG HTTP proxy endpoints does not work (only half-way).
If you set the endpoint type to `HTTP` the correct endpoint type is generated, but the target URI is not set.

_Solution_:
To support this, the endpoint definition should have an `uri` property that would be propagated as is to the APIG REST API during creation of the endpoint and it should work out of the box.

Example:
```
  "endpoints": [
    {
      "path": "testfct2",
      "method": "GET",
      "type": "HTTP",
      "uri": "https://www.google.com/",      <----- new property
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": ""
      },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ]
```

**Comment by eahefnawy** [comment]
Released! Thanks @HyperBrain :blush:

**Comment by flashsnake-so** [comment]
Actually, I am using the one above as an example.  But getting "Proxy endpoints need an "uri" property." error.  The reason is 
```json
"targetMethod" : "POST"
```
is required.
