### ISSUE TITLE
Getting `InvalidSignatureException` when running serverless in Jenkins

### ISSUE THREAD

**Issue by corydorning** [serverless/serverless#9515]
Everything is working fine locally, but when i attempt to run `sls package` in my Jenkins environment, i'm getting the error below. I realize it's a setting somewhere in my environment, but trying to figure out what my cause this so i know where to look. I know the aws creds are right because the `serverless-vpc-discovery` plugin are able to fetch my vpc id. Any thoughts on things to consider would be greatly appreciated.

```
Serverless: Invoke aws:package:finalize
 
 Serverless Error ----------------------------------------
 
  ServerlessError: InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'. 
```

NOTE: I asked on the forums but get zero response.

**Comment by pgrzesik** [comment]
Hello @corydorning :wave: Could you please follow the issue template that is visible when you try to create a new one? What version of the Framework are you using? Is there a significant difference in used AWS Credentials between your local env and Jenkins?

**Comment by corydorning** [comment]
No difference. Using latest version

**Comment by corydorning** [comment]
I can repost using the template though

**Comment by pgrzesik** [comment]
Thanks @corydorning - it would be much appreciated and will help us debug that problem. One additional question - did it work previously or it just started happening after e.g. an upgrade to the Framework?

**Comment by pgrzesik** [comment]
I'm going to close this one in favor of: https://github.com/serverless/serverless/issues/9548
