### ISSUE TITLE
npm wrench is depricated

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#952]
@see https://github.com/ryanmcgrath/wrench-js

Looks like serverless should migrate to https://github.com/jprichardson/node-fs-extra

**Comment by doapp-ryanp** [comment]
Code hits: https://github.com/search?l=&q=wrench+user%3Aserverless&ref=advsearch&type=Code&utf8=%E2%9C%93

Looks like `node-fs-extra` has already been vetted by serverless team so I will try to send some PRs to upgrade

**Comment by HyperBrain** [comment]
@doapp-ryanp Please take care that you set the `dereference: true` option when `fs-extra.copyAsync()` is used, otherwise symlinks won't be followed.
See my comments at the end of https://github.com/serverless/serverless/issues/896

**Comment by doapp-ryanp** [comment]
@HyperBrain good catch. will do!

**Comment by doapp-ryanp** [comment]
K got em all. @HyperBrain good find on `dereference` its totally un-documented. If you get a chance can you review my code @ https://github.com/serverless/serverless-optimizer-plugin/pull/34/files to make sure this is what you intended?

**Comment by doapp-ryanp** [comment]
@ac360 sure u want to close this before https://github.com/serverless/serverless/pull/957 gets merged?
