### ISSUE TITLE
`serverless deploy` removes subscription filter outside CloudFormation stack

### ISSUE THREAD

**Issue by os1ma** [serverless/serverless#9528]
`serverless deploy` removes subscription filter outside CloudFormation stack.

This issue is similar to the closed issue https://github.com/serverless/serverless/issues/3447 and pull request https://github.com/serverless/serverless/pull/5554, but the AWS specification have changed since then.

At that time, only 1 subscription filter could be created for a log group, but now, 2 subscription filters can be created for a log group.

Therefore, there is a practical use case of adding a new subscription filter by Serverless Framework to a log group that already has one subscription filter.

The subscription filter that `serverless deploy` removes should be limited to the ones included in the related CloudFormation stack.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws-node-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: helloLogGroup
          filter: hello
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

A simple process to cause this problem is to run `serverless deploy` in different stages.

```
$ export SLS_DEBUG=*
```

```
$ aws logs create-log-group --log-group-name helloLogGroup
```

```
$ serverless deploy --stage dev
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-node-project.zip file to S3 (1.63 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: aws-node-project
stage: dev
region: us-east-1
stack: aws-node-project-dev
resources: 8
api keys:
  None
endpoints:
  None
functions:
  hello: aws-node-project-dev-hello
layers:
  None
Serverless: Invoke aws:deploy:finalize

***********************************************************************************************************************
Serverless: Announcing Metrics, CI/CD, Secrets and more built into Serverless Framework. Run "serverless login" to activate for free..
***********************************************************************************************************************
```

```
$ aws logs describe-subscription-filters --log-group-name helloLogGroup
{
    "subscriptionFilters": [
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-dev-HelloLogsSubscriptionFilterCloudWatchLog1-E3B7FL7BG61D",
            "creationTime": 1622233654960,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-dev-hello",
            "distribution": "ByLogStream"
        }
    ]
}
```

Currently, there is a subscription filter named `aws-node-project-dev-HelloLogsSubscriptionFilterCloudWatchLog1-E3B7FL7BG61D`.

```
$ serverless deploy --stage prod
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-node-project.zip file to S3 (1.63 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: aws-node-project
stage: prod
region: us-east-1
stack: aws-node-project-prod
resources: 8
api keys:
  None
endpoints:
  None
functions:
  hello: aws-node-project-prod-hello
layers:
  None
Serverless: Invoke aws:deploy:finalize
```

```
$ aws logs describe-subscription-filters --log-group-name helloLogGroup
{
    "subscriptionFilters": [
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-prod-HelloLogsSubscriptionFilterCloudWatchLog1-5D4KMYDXRPGC",
            "creationTime": 1622233883236,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-prod-hello",
            "distribution": "ByLogStream"
        }
    ]
}
```

Now there is a subscription filter named `aws-node-project-prod-HelloLogsSubscriptionFilterCloudWatchLog1-5D4KMYDXRPGC`, but `aws-node-project-dev-HelloLogsSubscriptionFilterCloudWatchLog1-E3B7FL7BG61D` has been removed.

</details>

<b>Installed version</b>

```
Framework Core: 2.43.1
Plugin: 5.1.4
SDK: 4.2.2
Components: 3.10.1
```

### Implementation proposal

The concern that we should not remove the subscription filter outside of Cloud Formation stack has been mentioned in comments on previous pull requests https://github.com/serverless/serverless/pull/5554#issuecomment-443844521.

The relevant part of the source code is the following method.

https://github.com/serverless/serverless/blob/a1fcaa6c96952e907cd76126e047eb2997f33b9d/lib/plugins/aws/deploy/lib/checkForChanges.js#L263

We should add a process to check if the subscription filter is included in the Cloud Formation stack.

### Related past issues and pull requests

- https://github.com/serverless/serverless/issues/3447
- https://github.com/serverless/serverless/pull/5554
- https://github.com/serverless/serverless/issues/5700
- https://github.com/serverless/serverless/pull/6471

I'm sorry, but this issue may be substantially the same as the following issue.

https://github.com/serverless/serverless/issues/8276

**Comment by pgrzesik** [comment]
Hello @os1ma, thanks for a very detailed issue description. I think the proposed solution makes sense, also based on the original PR that implemented the change, it was in order to prevent duplication of subscriptions from the same stack. 

We'd be happy to accept a PR fixing this :bow:

**Comment by benb1983** [comment]
We're getting this problem after switching between serverless-plugin-log-subscription and serverless-plugin-datadog. the only solution seems to be to manually remove the subscription but that causes many issues. We currently have lots of deployment issues in development and production environments

**Comment by pgrzesik** [comment]
Could you describe in more detail what is the problem @benb1983? Is there something additional that the proposed solution would not solve?

**Comment by benb1983** [comment]
> Could you describe in more detail what is the problem @benb1983? Is there something additional that the proposed solution would not solve?

Hi @pgrzesik - I am confident this will fix the problem

**Comment by os1ma** [comment]
Hello @pgrzesik 

Thanks for your comment and labeling. I will try to fix this issue.

I understand how to fix it, but I still don't understand the testing code, so it may take a few weeks and I may need some help.

If anyone needs a fix in a hurry, I would be happy to have someone else fix this.

**Comment by pgrzesik** [comment]
We'd also be happy to assist if anyone has any questions related to implementation/testing, so if someone is interested, please feel free to reach out :raised_hands:

**Comment by os1ma** [comment]
I started working on a fix for this issue and added some small code and tests. As it is not yet complete, I have put the code only in my forked repository without PR (https://github.com/os1ma/serverless/commit/4826229c35a9b9880ddd62c2342da7905208ecd9).

However, I realized that in order to properly resolve this issue, I also needed to resolve the issue that supports multiple subscription filters (https://github.com/serverless/serverless/issues/8276).

As shown in code below, the current code only supports one subscription filter, so just checking CloudFormation stack name may not work well when repeatedly running `serverless deploy`.

https://github.com/serverless/serverless/blob/a1fcaa6c96952e907cd76126e047eb2997f33b9d/lib/plugins/aws/deploy/lib/checkForChanges.js#L281

For a radical solution, we need to modify the code to work with multiple subscription filters as well.

I will also implement a fix to support multiple subscription filters and send a PR with this issue along with the fix for #8276.

**Comment by pgrzesik** [comment]
Thanks for the update @os1ma and thanks for working on this one :bow: 

> so just checking CloudFormation stack name may not work in some cases.

Could you clarify why that would be the case?

**Comment by os1ma** [comment]
Hello @pgrzesik

I'm very sorry for the late reply.

I have created and tested a simple fix code (https://github.com/os1ma/serverless/commit/8da3cd172b37f0a3fa3b6ceca525667e53389fae) for this issue and found that it has problems in some cases.

For example, prepare a serverless.yaml like the following.

```yaml
service: aws-node-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: helloLogGroup
          filter: hello
```

Deploy to 2 stages, dev and prod.

```
$ serverless deploy --stage dev
$ serverless deploy --stage prod
```

At this point, if you check the subscription filters, you will see the following.

```
$ aws logs describe-subscription-filters --log-group-name helloLogGroup
{
    "subscriptionFilters": [
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-dev-HelloLogsSubscriptionFilterCloudWatchLog1-1BY65URE3RR9S",
            "creationTime": 1624195209727,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-dev-hello",
            "distribution": "ByLogStream"
        },
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-prod-HelloLogsSubscriptionFilterCloudWatchLog1-EUFXZAHO6JTD",
            "creationTime": 1624195333251,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-prod-hello",
            "distribution": "ByLogStream"
        }
    ]
}
```

After that, edit the serverless.yml and change the function name to hello-v2.

```yaml
service: aws-node-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello-v2:
    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: helloLogGroup
          filter: hello
```

After this, `serverless deploy --stage dev` will succeed.

At this point, if you check the subscription filters, you will see the following.

```
$ aws logs describe-subscription-filters --log-group-name helloLogGroup
{
    "subscriptionFilters": [
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-dev-HelloDashv2LogsSubscriptionFilterCloudWatchLog1-1A3OZTUH4W9LY",
            "creationTime": 1624195437195,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-dev-hello-v2",
            "distribution": "ByLogStream"
        },
        {
            "filterPattern": "hello",
            "filterName": "aws-node-project-prod-HelloLogsSubscriptionFilterCloudWatchLog1-EUFXZAHO6JTD",
            "creationTime": 1624195333251,
            "logGroupName": "helloLogGroup",
            "destinationArn": "arn:aws:lambda:us-east-1:{My AWS Account ID}:function:aws-node-project-prod-hello",
            "distribution": "ByLogStream"
        }
    ]
}
```

However, `serverless deploy --stage prod` will fail.

```
$ serverless deploy --stage prod
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-node-project.zip file to S3 (32.97 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A{My AWS Account ID}%3Astack%2Faws-node-project-prod%2F50c6fff0-d1ca-11eb-b662-0e2e9aec3a21

 Serverless Error ----------------------------------------

  An error occurred: HelloDashv2LogsSubscriptionFilterCloudWatchLog1 - Resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: 3565bd95-03e8-4fa0-bafb-9a166e3b0357; Proxy: null).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.0
     Framework Version:         2.47.0 (local)
     Plugin Version:            5.4.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

The cause of this error is that in the following part of the code, only the first filter associated with the same log group is taken out.

https://github.com/serverless/serverless/blob/a1fcaa6c96952e907cd76126e047eb2997f33b9d/lib/plugins/aws/deploy/lib/checkForChanges.js#L281

According to the [AWS documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeSubscriptionFilters.html), describe-subscription-filters returns values in ascii sorted by filter name. Therefore, it works properly when the filter to be removed is in the front of the ascii order, but when they are in the back, it causes LimitExceededException.

In order to avoid this problem, it would be preferable to implement support for multiple subscription filters, as shown in other issue (https://github.com/serverless/serverless/issues/8276), before fixing this issue.

I tried to work on a fix that would support multiple filters, but it turned out to require a lot more code changes than I had imagined.

Unfortunately, if I were to work on fixing it, it would take a long time. I would be very happy if someone else could work on it.

**Comment by poerty** [comment]
👍 on issue!! looking forward for it

As @os1ma said, finding exact subscription filter(by logical Id or smth) from response.subscriptionFilters should be implemented before solve this issue.

In addition, isnt it better to throwing a error or warning instead of just returning false?
or iit will be just fine with cloudformation error you will see at the actual deploy?

**Comment by pgrzesik** [comment]
Thanks a lot for the extensive update and all your work @os1ma. So it looks like this issue will be blocked until https://github.com/serverless/serverless/issues/8276 is implemented.

**Comment by os1ma** [comment]
Hi, @poerty 

I’m happy you’re working on #8276, which is what I was hoping to resolve.
I’d be very happy, if you write follow up code with this issue too!

Thanks for the great working!
