### ISSUE TITLE
Integration with infrastructure as code libraries

### ISSUE THREAD

**Issue by mhahn** [serverless/serverless#953]
More of a question about when/where/if this is on the roadmap.

I'm using (and also work on) a library that manages cloudformation templates via yaml & python: https://github.com/remind101/stacker. Very similar to something like terraform.

Right now I have stacker bring up the VPC, setup nat gateway etc. but then have to manually hook those up within serverless.

I noticed terraform was mentioned here: https://github.com/serverless/serverless/issues/597 but wanted to find out more about any plans related to this so I can help out if possible.

**Comment by eahefnawy** [comment]
@mhahn thanks for suggesting this! We are discussing supporting other solutions beside CF, but so far it's not in the road map and we're not super clear about it yet either. But we definitely think it's an interesting option.

Great work on Stacker btw! :wink: (starred!)

**Comment by ac360** [comment]
@mhahn Nice work!  We're definitely going to look into stacker.

**Comment by flomotlik** [comment]
@mhahn in the future we will support integrating your CF stack files directly into the serverless config, so basically you can create your stack file through stacker, compile it into a CF file, then we use it and add all the other resources we need to run your app and then deploy it. This will give you a lot more flexibility. As its already in the plan for the next release I will close this issue and we'll track the progress in a separate issue.
