### ISSUE TITLE
Better examples for export function behavior

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#9541]
### Use case description

The export function behavior for the v2 -> v3 transition is sparsely documented.  Trying to follow the documentation leads to errors in resolving the exported function object.

https://www.serverless.com/framework/docs/providers/aws/guide/variables/#exporting-a-function

That documentation is confusing.  It does not provide a complete end-to-end example and the documentation mentions that functions should declare two parameters while the description notes there are `options` and then two different resolution functions.

### Proposed solution

Please elaborate the documentation with full end-to-end examples that work as expected.  Please provide examples that cover a matrix of use-cases:

- sync function
- async function (and why use sync vs. async)
- export simple variables
- export objects with nested data structures

A full document could provide complete before and after examples, but the complete after-examples are valuable.

### Refs

- https://forum.serverless.com/t/resolved-a-js-function-not-confirmed-to-work-with-a-new-parser-falling-back-to-old-resolver/15160

### Examples

```yaml
# serverless.yml

custom:
  dynamicOpts: ${file(./serverless-helpers.js):dynamic}
  #  API deployment stage and settings by api-org
  api_org: ${self:custom.dynamicOpts.api_org}
  api_stage: ${self:custom.dynamicOpts.api_stage}
  apiOrg: ${self:custom.dynamicOpts.apiOrg}
  apiStage: ${self:custom.dynamicOpts.apiStage}
```

The following works but it flips to the previous resolution algorithm.

```javascript
// serverless-helpers.js

function toTitleCase(word) {
  let lower = word.toLowerCase();
  return lower.replace(lower[0], lower[0].toUpperCase());
}

module.exports.dynamic = (serverless) => {
  // The 'stage' is expected to contain '{org}-{env}' strings
  // where the 'org' is an organization deployment and
  // 'env' is a set of values like 'test', 'dev', 'prod';
  // the 'org' and 'env' should not contain '-'.

  const input_options = serverless.processedInput.options;
  const stage = input_options.stage;
  const stageComponents = stage.split("-");
  const api_org = stageComponents[0];
  const api_stage = stageComponents[1];

  return {
    api_org: api_org,
    api_stage: api_stage,
    apiOrg: toTitleCase(api_org),
    apiStage: toTitleCase(api_stage)
  };
};
```

The following function attempts to apply the example from the documentation, but it fails.  What is wrong with it?  (Apologies if there are any javascript errors, most of my work is in python.  I think it compiles and runs.)

```javascript

module.exports.dynamic = async ({ options, resolveVariable }) => {
  const stage = await resolveVariable('sls:stage');
  // const region = await resolveVariable('opt:region, self:provider.region, "us-east-1"');

  // also tried using `options.stage` directly and that failed

  const stageComponents = stage.split("-");
  const api_org = stageComponents[0];
  const api_stage = stageComponents[1];
  const apiOrg = toTitleCase(api_org);
  const apiStage = toTitleCase(api_stage);

  return Promise.resolve({
    api_org: api_org,
    api_stage: api_stage,
    apiOrg: apiOrg,
    apiStage: apiStage
  });
};
```

error message

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.dynamicOpts": Cannot resolve "dynamic" out of "serverless-helpers.js": Resolved a JS function not confirmed to work with a new parser, falling back to old resolver
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

**Comment by medikoo** [comment]
@dazza-codes great thanks for those comments. I've created a PR (https://github.com/serverless/serverless/pull/9545) in which I improve our documentation, and fix the deprecation message you receive, as it actually should say:

_Approached a JS function resolver, confirm it's updated to work with a new parser by setting "variablesResolutionMode: 20210326" in service config.  Falling back to old resolver_

It was an error, that in some cases we show this and in other limited version of message that was presented to you.

The documentation also states the need of `variablesResolutionMode: 20210326` setting for this case, but it was not as eminent, and I believe I've improved.

If you feel that it still doesn't answer some questions, can you prepare a PR that improves that further?
