### ISSUE TITLE
How to include binaries within generated function zip?

### ISSUE THREAD

**Issue by nicka** [serverless/serverless#956]
I can't figure out how to store binaries within the generated function zip. 

For example:
```
functions/ffmpeg
  - event.json
  - ffmpeg(binary)
  - handler.js
  - s-function.json
```

Only thing present on AWS is the `_serverless_handler.js` file.

**Comment by eahefnawy** [comment]
could you deploy your function again with `sls function deploy -t` (notice the `-t` flag) ... after deployment is complete you should see a `meta/tmp` folder that contains the package that was uploaded to AWS. Could you show us what you got inside that folder?

**Comment by nicka** [comment]
Wow, thanks for the quick reply. ![screen shot 2016-04-06 at 2 43 30 pm](https://cloud.githubusercontent.com/assets/195404/14316923/fd1a6bd4-fc05-11e5-89bb-12d25ff7d185.png)

**Comment by nicka** [comment]
Current `s-function.json`:
```
{
  "name": "fetcher",
  "runtime": "nodejs",
  "description": "Serverless Lambda function for project: foo",
  "customName": false,
  "customRole": false,
  "handler": "handler.handler",
  "timeout": 300,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": [],
    "optimize": {
      "exclude": [
        "aws-sdk"
      ]
    }
  },
  "endpoints": [],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "${project}",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```

**Comment by nicka** [comment]
My bad something like this works:
```
{
  "name": "fetcher",
  ...
  "custom": {
    "excludePatterns": [],
    "optimize": {
      "exclude": [
        "aws-sdk"
      ],
      "includePaths": [
        "binaries"
      ]
    }
  },
  ...
}
```
Other than that it would be awesome if https://github.com/serverless/serverless-optimizer-plugin could support something like the example below and put those files to the root of the zip:

```
"includeFiles": [
  "binaries/ffmpeg"
]
```

**Comment by eahefnawy** [comment]
oh yeah I was just gonna ask you about the optimize plugin! :smile:

Please let me know if there's anything else I can help you with :blush:

**Comment by nicka** [comment]
Haha thanks man!

How would you feel about something like?
```
"includeFiles": [
  "binaries/ffmpeg"
]

**Comment by eahefnawy** [comment]
hmmmm I'm not sure I completely understand what you mean by "put those files in the root of the zip", but generally we really hate changing the directory/file structure of our users projects (they may have this structure for a strict reason). So I'm not sure if moving files around to the root of the zip would be a great idea.

**Comment by nicka** [comment]
That's completely understandable. The binary is now part of the zip, next problem is permissions.
```
[Error: Command failed: /bin/sh: /var/task/binaries/main/ffmpeg: Permission denied
```
If I zip the dir myself Lambda triggers the function without any problems. Could it be that the optimize plugin is not respecting original file permissions?

**Comment by nicka** [comment]
Fixed the permissions issue in https://github.com/serverless/serverless/pull/960

**Comment by eahefnawy** [comment]
@nicka thanks for keeping us updated! Is everything working for u now? :)

**Comment by nicka** [comment]
@eahefnawy No problem! Only thing left is for serverless to retain original file permissions while generating the zip. But that should be fixed once #960 is approved :smile:

**Comment by eahefnawy** [comment]
wow thanks a lot for the PR! :blush:

**Comment by peterschwarz21** [comment]
Is there an update for this for serverless.yml? Using serverless webpack I;m not sure how to include binaries.

**Comment by pmuens** [comment]
@peterschwarz21 that should be possible with `include` https://serverless.com/framework/docs/providers/aws/guide/packaging#exclude--include

The usage of globs can help here!

How does your `serverless.yml` look like? Where do you face problems?

**Comment by peterschwarz21** [comment]
I must be missing something really easy lol. Here is my dir structure:

Myapp
   /node_modules
       aws-sdk
    /bin
         pdftk (this is the binary)
    function1.js
    function2.js

Now when I deploy it to AWS (or run serverless deploy -t), the /bin dir is not included. i just need to include that directory in the zip file before it gets uploaded to AWS. I feel like this should be easy, but it isn't. 

The serverless.yml file is like this: 

service: myapp-app-api
package:
  include:
    - bin/**
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
.... etc

**Comment by peterschwarz21** [comment]
Success! Using the copy-webpack-plugin I was able to upload a static file to AWS. 

https://github.com/kevlened/copy-webpack-plugin

**Comment by pmuens** [comment]
@peterschwarz21 awesome! Thanks for keeping us posted on this one! Glad to hear that it has been resolved 👍

**Comment by laardee** [comment]
@peterschwarz21 you might face permission [issues](https://github.com/kevlened/copy-webpack-plugin/issues/68#issuecomment-276519949) if you use copy-webpack-plugin with binaries that you need to execute in lambda environment. I had to use serverless-plugin-optimize to get ffmpeg working in my [project](https://github.com/laardee/video-preview-and-analysis-service/tree/master/video-service).

**Comment by boazdejong** [comment]
@laardee Can you elaborate? I'm currently facing permission issues with ffmpeg in lambda using the copy-webpack-plugin.

**Comment by laardee** [comment]
@boazdejong nice, I need to check out that plugin also.

**Comment by HyperBrain** [comment]
@boazdejong With the upcoming V3 version of the webpack plugin copying the file right into the `.webpack` folder might not work anymore, because of the individual packaging support there might be multiple subfolders now where the artifacts/handlers are built and packaged.
I see great value in a raw file import functionality for the webpack plugin that would just copy given files as is to the handler's package folder. Can you please create a feature request within the repo and I'll schedule the feature as soon as possible. (https://github.com/elastic-coders/serverless-webpack/issues)

**Comment by boazdejong** [comment]
@HyperBrain That would be a great feature! I just added the request. Thank you.
https://github.com/elastic-coders/serverless-webpack/issues/205
