### ISSUE TITLE
Crash when packaging custom resource zip when two separate projects are packaging at the same time

### ISSUE THREAD

**Issue by NoxHarmonium** [serverless/serverless#9565]
If you use a tool like yarn workspaces to package multiple (unrelated) projects in parallel
you can get crash that looks like the following during the "Serverless: Installing dependencies for custom CloudFormation resources..." step.

```
➤ YN0000: [xxxx]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [yyyy]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:  Error ---------------------------------------------------
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:   Error: dest already exists.
➤ YN0000: [xxxx]:       at /var/lib/jenkins/workspace/xxxx-build_develop/node_modules/fs-extra/lib/move/move.js:41:31
➤ YN0000: [xxxx]:       at /var/lib/jenkins/workspace/xxxx-build_develop/node_modules/fs-extra/node_modules/universalify/index.js:22:54
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

It has also been reported at https://github.com/serverless/serverless/issues/5002#issuecomment-737519692

The line that seems to be crashing is https://github.com/serverless/serverless/blob/ae67bf448950b199eaf2a0ec406349d63f60424c/lib/plugins/aws/customResources/generateZip.js#L21

I'm pretty sure the reason is that the ensureArtifact function is not thread safe. The custom CloudFormation resources are built once and cached in a shared folder in the home drive:

https://github.com/serverless/serverless/blob/ae67bf448950b199eaf2a0ec406349d63f60424c/lib/utils/ensureArtifact.js#L9

It seems that when there are multiple serverless instances building the artifacts and trying to cache them in the shared folder the crash happens.

To reproduce you need to make sure you delete the serverless cache directory at "$HOME/.serverless/artifacts/"

I'll create a test repo to reproduce the issue

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-issue-9565-repro-1

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # These options should force a custom resource lambda to be packaged
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: # Enables INFO level logging of API Gateway requests
      accessLogging: true
      fullExecutionData: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: v1/hello
          method: get

```

</details>

<details>
<summary><b><code>yarn build-all #(yarn sls package)</code> output</b></summary>

```
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-4]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-4]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-1]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-1]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-3]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-3]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-2]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-2]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:  Error ---------------------------------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Error: dest already exists.
➤ YN0000: [serverless-issue-9565-repro-3]:       at /var/home/seandawson/Development/work/ai-media/serverless-issue-9565-repro/node_modules/fs-extra/lib/move/move.js:41:31
➤ YN0000: [serverless-issue-9565-repro-3]:       at /var/home/seandawson/Development/work/ai-media/serverless-issue-9565-repro/node_modules/universalify/index.js:22:54
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Get Support --------------------------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:      Docs:          docs.serverless.com
➤ YN0000: [serverless-issue-9565-repro-3]:      Bugs:          github.com/serverless/serverless/issues
➤ YN0000: [serverless-issue-9565-repro-3]:      Issues:        forum.serverless.com
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Your Environment Information ---------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:      Operating System:          linux
➤ YN0000: [serverless-issue-9565-repro-3]:      Node Version:              12.20.1
➤ YN0000: [serverless-issue-9565-repro-3]:      Framework Version:         2.44.0 (local)
➤ YN0000: [serverless-issue-9565-repro-3]:      Plugin Version:            5.2.0
➤ YN0000: [serverless-issue-9565-repro-3]:      SDK Version:               4.2.3
➤ YN0000: [serverless-issue-9565-repro-3]:      Components Version:        3.11.0
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: Done in 3s 515ms
```

</details>

```
Framework Core: 2.44.0 (local)
Plugin: 5.2.0
SDK: 4.2.3
Components: 3.11.0
```

**Comment by NoxHarmonium** [comment]
I've created a repo that reproduces the issue: https://github.com/NoxHarmonium/serverless-issue-9565-repro

**Comment by NoxHarmonium** [comment]
I have created a fix in a fork: https://github.com/NoxHarmonium/serverless/commit/152a953b227161671cd3d4ad76af33edd3e249e0

I'm not sure if it is the preferred approach. Happy to raise a PR if it looks good.

**Comment by pgrzesik** [comment]
Thanks a lot for reporting @NoxHarmonium :bow: 

As for the proposed fix - I'm not entirely sure about that as it's making the cache service-specific, which means that we might have multiple custom resources artifacts that are exactly the same, which caching was supposed to address. I think it would be better to either introduce a locking mechanism or allow the download process to just gracefully continue if during copy the artifact already exist. What do you think?

@medikoo I'd love to hear your opinion on that as well :bow:

**Comment by NoxHarmonium** [comment]
Are you referring to this API function? https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback

Sounds like a good plan to me! It seems simple so not much can go wrong. It shouldn't matter if the file gets overwritten multiple times, since this is an edge case anyway and all the files should have the same content.

I don't _think_ there will be any issue with open files. At least [on the Linux platform](https://man7.org/linux/man-pages/man2/rename.2.html) It sounds like any process using the old file will still have a handle to it when it is overwritten, and it will be cleaned up once no process is referencing it. Similar to how you can update libraries and applications on Linux while they're running.

I'm not sure how it will go on Windows however, I don't have much experience with that but I can try it out.

I'll try and get another branch up sometime this week.

**Comment by pgrzesik** [comment]
Yes, I'm refering to this function, but preferrably let's use promise-based version: https://nodejs.org/api/fs.html#fs_fspromises_rename_oldpath_newpath

Thanks a lot @NoxHarmonium :bow:

**Comment by NoxHarmonium** [comment]
Current status:

https://github.com/serverless/serverless/compare/master...NoxHarmonium:issue-9565-concurrency-crash?expand=1

I implemented the change and wrote tests around it, however other tests are failing with errors like:

```
Error: EXDEV: cross-device link not permitted, rename '/tmp/tmpdirs-serverless/3d50/79f146039f39ec82/resource-lambda.zip' -> '/var/home/seandawson/.serverless/artifacts/2.45.1/my-service-custom-resources.zip'
```

I think this is because rename doesn't work across filesystems and the temp directory (at least on my machine) is stored in ram.

https://stackoverflow.com/a/43206576/1153203

Will have to have a think about whether we should use a different approach.

**Comment by NoxHarmonium** [comment]
The fs-extra module has an overwrite option for the copy file operation but I'm not sure if the check for existing file and copy operation are atomic (there might be a tiny window where the file is created after the exist check and before the copy) but I'd have to double check.

Maybe we could just use https://nodejs.org/api/fs.html#fs_fspromises_copyfile_src_dest_mode it seems to overwrite by default

**Comment by medikoo** [comment]
@NoxHarmonium we need to rely on move as it's instant, and it doesn't introduce a possibility of ending with state were we have just incomplete file at the path.

I think your case it quite specific, and I imagine many other places could be affected. Anyway we can workaround it: If we detect `EXDEV` error, then we may copy file to `custom-resources-<some-random-string>` in target location, and then rename it to `custom-resources.zip`

**Comment by NoxHarmonium** [comment]
> we need to rely on move as it's instant, and it doesn't introduce a possibility of ending with state were we have just incomplete file at the path.

Oh yeah, I didn't notice this from the documentation:

> No guarantees are made about the atomicity of the copy operation. If an error occurs after the destination file has been opened for writing, an attempt will be made to remove the destination.

> I think your case it quite specific, and I imagine many other places could be affected. 

Although Ubuntu and Debian don't use tmpfs by default, other popular distributions like Fedora do I would say it is a less common configuration but not an edge case.

>  Anyway we can workaround it: If we detect EXDEV error, then we may copy file to custom-resources-<some-random-string> in target location, and then rename it to custom-resources.zip

That's exactly what fs-extra does! https://github.com/jprichardson/node-fs-extra/blob/master/lib/move/move.js#L57

I think I'll just switch over to using that method.

**Comment by NoxHarmonium** [comment]
Oh oops, sorry I just re read your comment. That would work.

fs-extra falls back to `copy` which brings us back to our last problem. So I might have to write a utility function. I'll see how I go

**Comment by NoxHarmonium** [comment]
Current status: https://github.com/serverless/serverless/compare/master...NoxHarmonium:issue-9565-concurrency-crash?expand=1

Does that approach look OK?

I'll have to write some tests that simulate the EXDEV error.

**Comment by medikoo** [comment]
@NoxHarmonium what I see in this branch looks great, I would just test EXDEV case only in context of util you've introduced (which is a great call). Please post it as PR, and we'll take it from there

**Comment by NoxHarmonium** [comment]
Thanks @medikoo [PR is now raised ](https://github.com/serverless/serverless/pull/9616)

**Comment by NoxHarmonium** [comment]
As a side note, I wonder if the above PR merges, if we should change existing instances of `rename` to the safe version (E.g. https://github.com/serverless/serverless/pull/9605/files)
Might not be worth it unless someone has reported an issue in the past.
