### ISSUE TITLE
Deprecate Node.js v10

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9586]
### Use case description

Node.js v10 is EOL, and it should not be supported with next major release.

In context of current release we need to inform all Node.js v10 users that it's usage is deprecated

### Proposed solution

Implementation should be very similar to one we've introduced in v1 (when deprecating Node.js v8) -> https://github.com/serverless/serverless/pull/7903/files

I think it's fine we rely on same deprecation code. Still let's update the description of it to list Node.js v12 as minimum required

**Comment by vaidyamilind** [comment]
Hi @medikoo
I wanted to take this.

**Comment by medikoo** [comment]
@vaidyamilind that'll be great. We look forward the PR!
