### ISSUE TITLE
Unable to deploy a CW event into multiple stages

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#961]
Imagine you have a function that needs to be triggered by a CloudWatch event.
You configure the event like this:
```
  "events": [
    {
      "name": "Trigger",
      "type": "schedule",
      "config": {
        "schedule": "rate(15 minutes)",
        "enabled": true
      }
    }
  ],
```
Now run a `sls event deploy --stage dev` the event will be deployed correctly and the lambda gets fired periodically.

If you now deploy your function and event to an other stage, e.g. `sls event deploy --stage prod`, the event will get deployed with the same name and will just overwrite the event deployed for the dev stage.
Can be easily checked in the AWS console `CW/Events/Rules`.

The expected behavior would be (assuming the example above):
Either (not my recommendation):
(1) First the event should be created and the dev stage lambda should be attached
(2) On deploy of the prod stage the prod stage lambda should be added as target to the already existing event.
*Or*, if the schedule is templated in the function definition like `"schedule": "${stageSpecificSchedule}"
one event should be created for each stage like "Trigger-dev" and "Trigger-prod" as the user's intention here is to have different schedules per stage.

**Comment by eahefnawy** [comment]
Thanks for reporting this @hyperBrain :blush:  ... We actually had a bug in how we populate variables for events. I just fixed it. Other than that I included the stage in the Rule name as u suggested. I tried it out and it's working. Could u try it out as well?

**Comment by HyperBrain** [comment]
I'll do - but can take 'til tomorrow
