### ISSUE TITLE
Right way to test Serverless Plugins?

### ISSUE THREAD

**Issue by ubaniabalogun** [serverless/serverless#9621]
### Discussed in https://github.com/serverless/serverless/discussions/9614

<div type='discussions-op-text'>

<sup>Originally posted by **ubaniabalogun** June 16, 2021</sup>
Hi there, what's the right way to test a serverless plugin? 
So far, I've written a plugin and have unit-tests for my business logic. However, I'm unsure how to write tests to ensure that my plugin behaves correctly when called as part of Serverless frameworks lifecycle. 

I stumbled on the [runServerless util](https://github.com/serverless/test/blob/master/docs/run-serverless.md#run-serverless). Should framework plugins be using this utility as well? Or is it purely for testing Serverless framework internals? If it is purely internal, is there an alternative that plugin developers should use
Thanks,</div>

**Comment by medikoo** [comment]
Closing, as already same discussion is opened
