### ISSUE TITLE
Fix advisory 1755 for normalize-url library

### ISSUE THREAD

**Issue by uninstallit** [serverless/serverless#9634]
normalize-url library had a security vulnerability patched in v6.0.1. 

Previous version of this library is inherited via the path in the audit - and needs to be upgraded or replaced. 

```
high:  Regular Expression Denial of Service   
Package: normalize-url 
Patched in: >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1     
Dependency of: serverless   
Path: serverless > download > got > cacheable-request > normalize-url 
More info: https://www.npmjs.com/advisories/1755   
```

**Comment by pgrzesik** [comment]
Hello @uninstallit - could you please list for which version of serverless did you got to this warning? Recent versions of `serverless` no longer depend on `download` package.

**Comment by uninstallit** [comment]
@pgrzesik - looks like I am on v2.35.0. Can you provide a version when download was dropped - I couldn't go through all release notes.

**Comment by pgrzesik** [comment]
Could you try installing the latest framework version? It's `2.48.0` - I've just tried to `npm install` it and it does not show any security vulnerabilities. 

```
+ serverless@2.48.0
added 618 packages from 384 contributors and audited 770 packages in 39.449s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by kpeters-cbsi** [comment]
On a fresh install of Serverless 2.52.1, I still see a dependency on a vulnerable version of `normalize-url`.

```
$ mkdir tmp
$ cd tmp
$ yarn init -y
$ yarn add serverless
$ npm ls normalize-url
tmp@1.0.0 /home/kit/work/serverless/tmp
└─┬ serverless@2.52.1
  ├─┬ @serverless/cli@1.5.2
  │ └─┬ @serverless/core@1.1.2
  │   └─┬ package-json@6.5.0
  │     └─┬ got@9.6.0
  │       └─┬ cacheable-request@6.1.0
  │         └── normalize-url@4.5.1
  └─┬ got@11.8.2
    └─┬ cacheable-request@7.0.2
      └── normalize-url@6.1.0
```

**Comment by sleepwithcoffee** [comment]
I think this issue can be close @medikoo @pgrzesik

**Comment by medikoo** [comment]
@sleepwithcoffee thanks for pointing 👍
