### ISSUE TITLE
Supporting SASL/PLAIN auth with Kafka events 

### ISSUE THREAD

**Issue by overbit** [serverless/serverless#9663]
### Use case description
There is a serveless application running in AWS that needs to react to events published on a Kafka topic and a Kafka (self-managed or not) that only support SASL/PLAIN auth.

Since yesterday, AWS Lambdas support SASL/PLAIN authentication for functions triggered from self-managed Apache Kafka.
https://aws.amazon.com/about-aws/whats-new/2021/06/aws-lambda-now-supports-sasl-plain-authentication-for-functions-triggered-from-self-managed-apache-kafka/

To add, currently Confluent Cloud (the biggest Kafka Saas solution) only supports SASL/PLAIN and without this feature the solution is to setup a KafkaConnector to the Serverless application lambdas but it is less maintainable and way more expensive

**Comment by pgrzesik** [comment]
Thanks for reporting @overbit - it looks like it's not yet supported by CloudFormation, or the docs are not yet updated (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-sourceaccessconfiguration.html. After CF supports it, we'd be more than happy to support this functionality.

**Comment by overbit** [comment]
CloudFormation seem to support it. I've created a pull request 🔝 and also test that the serverless deploy creates all the necessary bits in AWS
