### ISSUE TITLE
Replace local runtimes with AWS Lambda compatible ones

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#9681]
### Use case description

Replace local runtimes with AWS Lambda compatible ones

### Proposed solution

I am trying to use `libxmljs` in a AWS NOde.js (v12) Lambda but get the error:
```json
{
    "errorType": "Error",
    "errorMessage": "/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/node_modules/libxmljs/build/Release/xmljs.node)",
    "stack": [
        "Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/node_modules/libxmljs/build/Release/xmljs.node)",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at bindings (/var/task/node_modules/libxmljs/node_modules/bindings/bindings.js:84:48)",
        "    at Object.<anonymous> (/var/task/node_modules/libxmljs/lib/bindings.js:1:37)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]
}
```

From checking up on `libxmljs` they use some nativly compile MacOS libs that needs to be rebuilt but this is not done in the deployment. I run it fine locally on Ubuntu 20.04.

I found this issue https://github.com/serverless/serverless/issues/308 which points to something similar and suggests using:
```yaml
custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - npm_config_platform=linux npm_config_arch=x64 yarn add sharp
```

I've tried a bunch of different setups but can't get it running still... Anyone managed or have some pointers?

**Comment by pgrzesik** [comment]
Hello @QAnders - could you please format your issue following the issue template that is visible when you create a new one? 

As for the problem, this is always going to be tricky when it comes to environment-specific dependencies, did you try using docker via `--docker` flag (I'm assuming you're running `sls invoke local` command)

**Comment by QAnders** [comment]
Ah, yes, thanks!

I found the solution a few minutes ago... Just step into your project directory and run:
`docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm install libxmljs`

This will replace the package with a compile one from a "Lambda Linux" one.

I am using Serverless and after this I could just run `sls deploy -s test` and it runs fine in AWS.

Interestingly enough, the built `libxmljs` from AWS Linux also works fine on my Ubuntu so I don't have to recompile between running locally and deploying!

**Comment by pgrzesik** [comment]
Thanks for sharing @QAnders :bow:
