### ISSUE TITLE
--verbose option unsupported warning for sls info

### ISSUE THREAD

**Issue by daveykane** [serverless/serverless#9691]
When running `sls info --verbose --stage development` you get the following warning:

```
Serverless: Deprecation warning: Detected unrecognized CLI options: "--v".
            Starting with the next major, Serverless Framework will report them with a thrown error
            More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
```

Does this mean that in the next major release the `verbose` option to get `Outputs` on `sls info` will be removed? Or does it need adding to the options lists for the `info` command here? https://github.com/serverless/serverless/blob/master/lib/cli/commands-schema/aws-service.js#L81

**Comment by medikoo** [comment]
@daveykane thanks for reporting. Indeed, it seems this option was never properly documented, will be fixed with: https://github.com/serverless/serverless/pull/9695
