### ISSUE TITLE
CLI: Deprecate `-v` as an alias for `--verbose` option

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9694]
### Use case description

`-v` is already predefined as an alias for `--version`, which can be used in any command context.

Therefore applying this for any other option introduces collision (currently to avoid that we do not support `-v` as `--version` alias in any command context)

### Proposed solution

Deprecate usage of `-v` as an alias for `--verbose` option in all commands that support it (`deploy`, `remove`, `info`, `rollback`)

**Comment by alias-rahil** [comment]
Would this be a breaking change? Many people (including me) use ```sls deploy -v```  in CI/CD config file.
