### ISSUE TITLE
Add options to specify Node.js 4.3 

### ISSUE THREAD

**Issue by martinmicunda** [serverless/serverless#970]
AWS [announced](https://aws.amazon.com/about-aws/whats-new/2016/04/aws-lambda-supports-node-js-4-3/?sc_channel=sm&sc_campaign=launches_2016&sc_publisher=tw_go&sc_content=lambda_supports_nodejs_4_3&sc_country=global&sc_geo=global&sc_category=lambda&adbsc=social_launches_20160407_60266766&adbid=718162644394311681&adbpl=tw&adbpr=66780587) support for Node.js 4.3 today so is there option to set node runtime version in function as "nodejs4.3"?

**Comment by TheSharpieOne** [comment]
Something like #958 ?

**Comment by martinmicunda** [comment]
@TheSharpieOne thanks I have missed that ...
