### ISSUE TITLE
Add support for the node 4.3.2 runtime

### ISSUE THREAD

**Issue by jamesw201** [serverless/serverless#971]
Providing the new runtime: 

"runtime": "nodejs4.3"

Throws an error. Would be great to use the new runtime.

Cheers

**Comment by HyperBrain** [comment]
Already implemented, see #958 
The next release should contain the support

**Comment by ac360** [comment]
@jamesw201 It is in V0.5.3.  Thanks :)

**Comment by jamesw201** [comment]
Excellent, thank you!

**Comment by HyperBrain** [comment]
@jamesw201 One hint. If you want to upgrade existing functions to Node 4.3, you have to delete them first and then redeploy with `sls function deploy`.
Otherwise it won't work.

**Comment by jamesw201** [comment]
@HyperBrain thanks, will do
