### ISSUE TITLE
Add `s3` configuration options to AWS `serverless.yml` docs

### ISSUE THREAD

**Issue by corydorning** [serverless/serverless#9713]
### Use case description

When searching for how to create an S3 bucket using the serverless framework, most examples seem to use the `Resources` section. I did find an example using the `provider` however, but didn't see it documented in the AWS `serverless.yml` file.

S3 Provider example:
https://www.serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration

AWS serverless.yml reference:
https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

### Proposed solution

Add the `s3` example in the AWS serverless.yml reference.

**Comment by medikoo** [comment]
@corydorning that's definitely missing. We're open for PR that adds it!

It's simply about updating: https://github.com/serverless/serverless/blob/b86f8cd71571196fa6558d2d6f1c7602bd0a07c9/docs/providers/aws/guide/serverless.yml.md

**Comment by nme077** [comment]
I’d like to tackle this issue.

**Comment by pgrzesik** [comment]
Thanks @nme077, we're looking forward to the PR :raised_hands: Please let us know if you have any questions
