### ISSUE TITLE
Discussion: Deploy all vs deploy individual (aka overwrite vs merge)

### ISSUE THREAD

**Issue by breandr** [serverless/serverless#973]
Disclaimer: I am new to serverless and thus ignorant.

This discussion began in the thread discussing utilising the recently launched APIG Swagger Importer https://github.com/serverless/serverless/issues/963 and is important for community best practices, docs, defaults, etc.

TLDR:
I am interested in the use-cases for deploying individual resources/methods/endpoints (APIG merge import), instead of deploying your entire APIG configuration each time (APIG overwrite import). Thanks to @doapp-ryanp for getting the conversation started and providing the following 3 reasons why he deploys individual endpoints rather than deploying everything:

> 1. Imagine there was some bug introduced in your config/template accidentally when you were working on GET /users that applied to all endpoints
2. during the APIG update it craps out updating endpoint 10 out of 250. They dont have transaction/rollback support
3. speed. We have 250 endpoints, I have to run update logic to 249 to update just one. More time executing the more time your code is in limbo as well.

With import, points 2 and 3 go away since the importer is fast and will not modify your configuration if any errors are encountered. Open to discussion if anyone disagrees.

I am very interested in point 1: fear of breaking a random endpoint when you modify a different endpoint (two endpoints walk into a bar; an endpoint in an entirely different bar falls over https://twitter.com/thomasfuchs/status/493790680397803521). This is not a good state to be in (I've been there). Is this a common sentiment in the serverless community? What can we add/change to reduce this fear?

In this scenario you're just delaying the inevitable: eventually you're going to want to deploy other endpoints; they will break and you will have no context as to why (because it was a month ago when you changed `GET /users`).

If anyone has additional reasons why they deploy individual endpoints (that they think are valid after moving to import), let's discuss those also.

**Comment by breandr** [comment]
### Pros of deploy all/overwrite
**Immutability**: Your serverless configuration becomes your single source of truth. Any external modifications will be destroyed. This is important for deploying your API in additional regions or sharing your serverless configuration with other developers.

**Synchronisation**: If you delete an endpoint from your serverless configuration, it will automatically be removed from APIG. Currently you need to manually do this.

**Comment by doapp-ryanp** [comment]
Some data points pertinent to this discussion:

- I have a swagger file that consists of roughly 400 methods (1/2 of them are OPTIONS methods).  File is `1.1M`
- `aws apigateway put-rest-api --mode overwrite` takes about 30 seconds to complete
- deploying the API to a stage takes about 30 seconds as well

Some non-pertinent but nice to know info:

- APIG does [not sort the resources in the APIG console UI](https://forums.aws.amazon.com/thread.jspa?threadID=222384&tstart=0). This gets nasty when you have lots of resources/methods
- APIG console UI preforms slower, but useable when you get to this level of resources/methods
- I have requested a feature for [catch all CORS](https://forums.aws.amazon.com/thread.jspa?threadID=229732&tstart=0)
- I have [requested a feature to support the full swagger 2.0 spec](https://forums.aws.amazon.com/thread.jspa?threadID=229230&tstart=25), specifically [response objects](http://swagger.io/specification/#responsesObject) not supporting Reference Objects.

**Comment by flomotlik** [comment]
As discussed in the other issue we're currently looking into CloudFormation to manage all of this. This should resolve most of the issues here I think as Cloudformation will make sure we're not replacing anything and only what needs to be will be updated. Or do I have a misunderstanding on what you mean @breandr

**Comment by flomotlik** [comment]
With V1 and our move to Cloudformation this should be resolved. Closing
