### ISSUE TITLE
SimpleDB Stage Support

### ISSUE THREAD

**Issue by jgilbert01** [serverless/serverless#974]
We use simpledb for something and want to be able to prefix the domain names to support stages.
However, the simpledb cloudformation resource type is unique in that it has no properties and the alphanumeric resource name is used as the domain name.
Thus we get this error:
`      ServerlessError: ServerlessError: Template format error: Resource name ${stage}${project}Domain1 is non alphanumeric.`

When we try this:
```
    "${stage}${project}Domain1": {
      "Type": "AWS::SDB::Domain"
    },
```

and this:
```
    "${stage}${project}Domain1": {
      "Description": "ARN of the Domain1",
      "Value": {
        "Fn::GetAtt": [
          "${stage}${project}Domain1",
          "Arn"
        ]
      }
    },
```
Can serverless add support for parameterized resource names?
Or is there some kind of workaround?
Or do I need to look at creating a plugin.

**Comment by BlueBlock** [comment]
I believe SimpleDB is deprecated. It may be advisable, to migrate to using DynamoDB.

**Comment by JamieCressey** [comment]
Agreed. SimpleDB is deprecated and not available to new AWS users.

**Comment by stockholmux** [comment]
@JamieCressey and @BlueBlock Do you have a source on the deprecation of SimpleDB?

**Comment by flomotlik** [comment]
@stockholmux Its not officially deprecated, just not linked in any of the product pages and there haven't been news/updates in a while. Which isn't necessarily a bad thing per se. In an upcoming version of Serverless we're going to change the way we do resource handling through Cloudformation quite a bit. Until then your best bet is probably going with either variables (e.g. hardcoding it in the variables file directly) or generally hardcoding the names. Not an ideal solution, but we won't be changing this before we're releasing the new CF integration.

I will close the issue for now, if you have any further questions regarding a plugin let me know

**Comment by jgilbert01** [comment]
To support our current need I have created a simpledb plugin:

- https://www.npmjs.com/package/serverless-simpledb-plugin

**Comment by flomotlik** [comment]
Oh very cool!
