### ISSUE TITLE
SSM variable resolution issue for SecureString

### ISSUE THREAD

**Issue by mars-lan** [serverless/serverless#9742]
After migrating to the new variable resolution mode (`variablesResolutionMode: '20210326'`), we noticed that the a SSM variable got rounded if it's stored as a `SecureString`. The rounding doesn't happen if the variable is stored as a standard `String`. Also this only happens if the value looks like a very large number (e.g. `12345678901234567890` got rounded to `12345678901234567000`), which suggests that the resolver incorrectly treated it as a floating point number instead of a string.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: app
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TEST_VARIABLE: '${ssm:test_variable}'

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
// Assume there's a SSM test_variable with value 12345678901234567890 stored as SecureString 
$ serverless package
$ cat .serverless/cloudformation-template-update-stack.json | grep TEST_VARIABLE
            "TEST_VARIABLE": "12345678901234567000"

// After changing test_variable to a String with the same value
$ serverless package
$ cat .serverless/cloudformation-template-update-stack.json | grep TEST_VARIABLE
            "TEST_VARIABLE": "12345678901234567890"
```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.2 (local)
Plugin: 5.4.3
SDK: 4.2.4
Components: 3.13.4
```

**Comment by medikoo** [comment]
@mars-lan thanks for report. 

Is it exactly `12345678901234567000`  that you store at SSM storage?

The only difference with `SecureString` that by default we treat string as JSON which we parse, So what's resolved is result of `JSON.parse(ssmValue)`

Still in case of `"12345678901234567000"` it returns `12345678901234567000` number (no digits are truncated).

You may avoid JSON parsing by passing `raw` param as: `${ssm(raw):test_variable}`

**Comment by mars-lan** [comment]
@medikoo the value stored in SSM is `12345678901234567890` which got resolved to `12345678901234567000`. Since `12345678901234567890` isn't strictly a correct JSON, what would be behavior be in this case?

**Comment by medikoo** [comment]
`"12345678901234567890"` JSON resolves to `12345678901234567000` number (as it's beyond safe number range, accuracy of number type degrades at this point).

You can solve it in two ways
- Add `raw` flag to avoid parsing, then you'll get `"12345678901234567890"` string (not number) result,
- Store value as JSON string not number (so with `"` quotes): `"\"12345678901234567890\""`

**Comment by mars-lan** [comment]
Got it. That's fair enough. Please consider updating [this part of the doc](https://www.serverless.com/framework/docs/providers/aws/guide/variables#auto-decrypting-of-securestring-type-parameters) to include a caveat on numbers-like strings.

**Comment by medikoo** [comment]
@mars-lan  I believe it's already mentioned:

> All SecureString type parameters are automatically decrypted, and automatically parsed if they export stringified JSON content (Note: you can turn off parsing by passing raw instruction into variable as

Note that value you were storing was a valid _stringified JSON content_, and quirk you've observed is very not specific to SSM resolution, but simply to how JSON parsing (and JavaScript language in general) works.

**Comment by mars-lan** [comment]
Actually on that point, why is the automatic JSON pasring only applied to `SecureString` not `String`?

**Comment by medikoo** [comment]
@mars-lan Most common case for `SecureString` is AWS Secrets Manager, and afaik it in all cases stores a stringified JSON object.

It's actually first time I've observed something else stored that way. How did you store that secure string?

**Comment by mars-lan** [comment]
You're correct that AWS Secret Manager stores stringified JSON in SSM. However, one can always directly create a SSM SecureString without going through AWS Secret Manager: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html

**Comment by medikoo** [comment]
Probably we can improve the experience by not attempting to `JSON.parse` when we detect that string doesn't represent serialized object

**Comment by mars-lan** [comment]
> Probably we can improve the experience by not attempting to `JSON.parse` when we detect that string doesn't represent serialized object

Sounds like a good idea.

**Comment by medikoo** [comment]
@mars-lan Indeed after thinking this through, I think we should auto parse only JSON object notation. I've prepared a fix that will improve that experience, you may expect it with next version
