### ISSUE TITLE
Serverless Cloud

### ISSUE THREAD

**Issue by chris-calo** [serverless/serverless#9745]
I'm Chris, a Designer at Serverless. As a team, we're actively working on a new product and would love some early feedback. Have a quick 2-3 minute introduction and questionnaire to it for anyone who has a few moments: https://t.maze.co/44470881. Cheers!

**Comment by slaytr** [comment]
Cool idea, filled out the questionnaire for ya.

**Comment by psvnlsaikumar** [comment]
The issue is open, but the questionnaire is not accessible.

**Comment by pgrzesik** [comment]
Thanks @psvnlsaikumar - I'm closing it for now.
