### ISSUE TITLE
Security vulnerability in nested dependency @serverless/platform-client -> adm-zip

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/serverless#9775]
I'm not sure where to post this, as @serverless/platform-client doesn't have a repository linked to it from its page on npmjs.

According to Snyk, the version of adm-zip used by @serverless/platform-client, 0.4.16, is vulnerable to a directory traversal vulnerability. This is fixed in versions 0.5.2 or later, which means that serverless itself is fine (it's pinned to a minimum of 0.5.5).

If there's more information needed (or a better spot for me to post this), please let me know.

**Comment by pgrzesik** [comment]
Thanks for reporting it @ROSeaboyer :bow: I've published a PR internally to fix it - I'm going to close this one.
