### ISSUE TITLE
2.52.1: ServerlessDeploymentBucket creation fails due to long service.name with erroneous CreateBucket permission issue message

### ISSUE THREAD

**Issue by bitsofinfo** [serverless/serverless#9800]
This is still an issue: why can't auto-truncation occur?
https://github.com/serverless/serverless/issues/2791

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.52.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
```

I have a long service name like 

```
service: 
  name: xxxxxx-xxxx-ingress-xxxxxxx-updater
```

When I do the initial serverless deploy, I get a error 
```
An error occurred: ServerlessDeploymentBucket - API: s3:CreateBucket Access Denied
```

If I shorten the service name, then it works.

**Comment by pgrzesik** [comment]
Thanks for reporting @bitsofinfo - we have the solution for that specified and tracked as a part of https://github.com/serverless/serverless/issues/7056 so I'm going to close this one as a duplicate. Please feel free to continue discussion in the linked issue, thanks :bow:
