### ISSUE TITLE
during patch endpoint deployment, when a single deployment fail, all the following deployments fail as well

### ISSUE THREAD

**Issue by orthodoc** [serverless/serverless#981]
With `--debug` option the endpoints are deployed along with the stage. Right after that sls halts with a no integration method available error. AWS console reveals that the endpoints have not been deployed.

**Comment by orthodoc** [comment]
Out of 18 endpoints in the project, a single one pointed to an HTTP proxy. Adding an HTTP type of endpoint was added recently via PR #951 which didn't make it to v0.5.3. So it was obvious that creating this endpoint would fail. What was interesting was that deploying any other endpoint (even the AWS type) would also fail even when deploying individually using the `path~ACTION` parameter.

Steps were taken to overcome:

1. `npm uninstall serverless -g`
1. `npm cache clean`
1. `npm install git+https://github.com/serverless/serverless.git#master -g`
1. `sls endpoint deploy 'labs/{labId}~GET' -s v2 --debug` -- endpoint with http and url parameters
1. `sls endpoint deploy 'labs/byDist~GET' -s v2 --debug` -- aws type of endpoint

The order of the last two commands was necessary for a successful deployment. Presence of a failed endpoint deployment prevented any other endpoint from being deployed. Not sure if this is an expected behaviour.

**Comment by eahefnawy** [comment]
hmmmm any other endpoints also fail because we throw an error whenever we have any failure, rather than making it fail silently. We're doing that for CI tools to know that something went wrong.

However, thinking about it again, I think you're right...that's not super convenient for the user (which is what we care about most). Maybe it's best to throw an error AFTER all endpoint deployments fail.

**Comment by eahefnawy** [comment]
@orthodoc when you say `prevented any other endpoint from being deployed` does that mean that Serverless display them as deployed or as failed?

**Comment by orthodoc** [comment]
@eahefnawy serverless displays all as failed.

**Comment by eahefnawy** [comment]
hmmm well in that case I think the issue is something else. I thought it'd just throw an error and not even display anything.

Are you able to reproduce this issue now? if u can could you show me the full Error stack? I'm finding it a bit hard to reproduce.

**Comment by orthodoc** [comment]
Serverless version: 0.5.3
Node version: 4.2.3
NPM version: 3.8.3

`sls endpoint deploy 'labs/{labId}~GET' -s v2 -r us-east-1 --debug`
Error stack when attempting to deploy endpoint with http type of integration in this [gist](https://gist.github.com/orthodoc/176b3f8f46aba6cfe4d5f0a0fcf9b191)

`sls endpoint deploy 'labs~GET' -s v2 -r us-east-1 --debug`
Error stack when attempting to deploy endpoint right after this with aws type of integration in this [gist](https://gist.github.com/orthodoc/86b96daf3a73240c2cdc8f807e4c4aac)
This endpoint had a successful deploy previously.

The master branch of serverless enables successful deployment of both the endpoints as I have detailed in the [comment](https://github.com/serverless/serverless/issues/981#issuecomment-207860082) above.

**Comment by orthodoc** [comment]
The failed deployment of endpoints with `HTTP` type of integration is resolved by the latest release of serverless v 0.5.5. Am closing this issue as a result.

Thanks @eahefnawy for taking time out on this one.
