### ISSUE TITLE
sls package --aws-s3-accelerate

### ISSUE THREAD

**Issue by JamesKyburz** [serverless/serverless#9812]
Using version `2.53.0`

When executing `sls package --aws-s3-accelerate` we get an incorrect deprecation warning.

```sh
Serverless: Packaging service...
Serverless: Deprecation warning: Detected unrecognized CLI options: "--aws-s3-accelerate".
```

However the cloudformation output contains the correct s3 bucket configuration.

```json
"AccelerateConfiguration": {
  "AccelerationStatus": "Enabled"
}
```

If the option is removed from the package command prior to a deploy it fails.

```sh
sls package
sls deploy --package .serverless --aws-s3-accelerate
 Serverless Error ----------------------------------------
 
  S3 Transfer Acceleration is not configured on this bucket
```

</details>

<b>Installed version</b>

```
2.53.0
```

**Comment by JamesKyburz** [comment]
Am happy to submit a `PR` but was not sure if the code should be added to the `lib/cli/commands-schema/aws-service.js`

**Comment by pgrzesik** [comment]
Hello @JamesKyburz, thanks for reporting. It looks like that option was ommitted when options schema was introduces and yes, it should be added to the module you've linked. We'd be more than happy to accept a PR :bow:

**Comment by JamesKyburz** [comment]
Thanks, will send a `PR`.

**Comment by JamesKyburz** [comment]
Sent a simple PR and have verified it works locally with npm link.

**Comment by JamesKyburz** [comment]
with v3 `package` fails with `--aws-s3-accelerate`, and `deploy` fails with `--aws-s3-accelerate` if package hasn't configured the bucket with accelerate.

**Comment by pgrzesik** [comment]
@JamesKyburz could you provide the repro steps? There was a change from warn to error in some of such cases
