### ISSUE TITLE
Missing generate-event CLI command in docs

### ISSUE THREAD

**Issue by m-radzikowski** [serverless/serverless#9823]
Documentation does not contain the `generate-event` CLI command. I expected to see it at least in under the AWS -> CLI reference (https://www.serverless.com/framework/docs/providers/aws/cli-reference/) since all events available right now are for the AWS.

`generate-event` command defined here:
https://github.com/serverless/serverless/blob/f1a288ce2c30e1377d8b411a90db3b1b2857d4fb/lib/cli/commands-schema/no-service.js#L137

I'm happy to add this to the docs and raise a PR, just please let me know this is not omitted on purpose.

**Comment by pgrzesik** [comment]
I believe this was just an omission and we'd be happy to accept PR with the adjustment :bow: 

Please correct me if I'm wrong @medikoo as I know you were handling that part.

**Comment by medikoo** [comment]
@m-radzikowski @pgrzesik This command was added in scope of our dashboard-plugin a longer while ago. I think it served some dashboard functionality (possibly UI was showing CLI examples using that command). I believe back then nobody thought of properly documenting it.

PR with documentation is definitely welcome! It probably belongs in this scope: https://www.serverless.com/framework/docs/providers/aws/cli-reference/

**Comment by pgrzesik** [comment]
Thanks for clarification @medikoo :bow:
