### ISSUE TITLE
Scan codebase and add structured inline docs for all methods/functions

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#983]

**Comment by akalra** [comment]
Are you envisioning something like JsDoc? 

Some related conversations:
https://github.com/sindresorhus/module-requests/issues/31
https://www.quora.com/Are-there-are-any-standards-for-inline-documenting-of-Node-js-packages-like-JSDoc

**Comment by eahefnawy** [comment]
@akalra yep exactly ... our code base is already easy to read, but it'd be nice to at least know the data type of the params and return 😄

**Comment by flomotlik** [comment]
Imho not as important any more with new architecture. Its pretty clear from our documentation and adding comments everywhere will imho lead to more outdated docs. Better to have clearer names for everything
