### ISSUE TITLE
Environment variables should be managed centrally for a project

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#985]
I would like to raise the point that currently, adding a new environment variable to a project is a tedious process, requiring you to:

1. add it manually to s-variables-dev.json
2. add it manually to every single s-function.json in the environment section (requiring dozens or hundreds of manual changes)
3. sync it manually with sls meta sync

Especially step 2 is error-prone. It's easy to forget to add it somewhere and then s-function.json files get out of sync, having different environment variables defined for different functions. It would be *much* more convenient to manage environment variables centrally in a single place for the whole project.

**Comment by ajagnanan1** [comment]
It is possible to create a template for environment variables. Config like this should work:

`s-template.json`
``` JSON
...
"environmentTemplate": {
        "region": "${region}"
}
...
```

`s-function.json`
```
...
"environment": "$${environmentTemplate}",
...
```

**Comment by kennu** [comment]
Thanks @ajagnanan1 I'll try that and see if the workflow gets easier.

**Comment by kennu** [comment]
Well, the template approach is easier than editing all s-functions manually. But I still have to add a new environment variables in multiple places (compared to the old "sls env set" workflow). And newly generated functions also won't use the $${environment} template by default.

So I would say that this is pretty confusing for someone who just wants to configure their app in a simple way.

**Comment by JamieCressey** [comment]
+1 `sls env set` was much easier. Integrating a similar feature with SLS Meta Sync would be cool

**Comment by kennu** [comment]
I wonder if there is any big reason why Serverless couldn't just export all s-variables as environment variables to all Lambda functions by default? There could then be optional manual overrides for edge cases where that causes problems.

**Comment by JamieCressey** [comment]
There's certainly cases where you wouldn't want all env vars accessible to all your lambda functions

**Comment by HyperBrain** [comment]
For us e.g. it is important that each lambda only gets the env vars important for the specific lambda.
Regarding the project variables: you can manage them with `sls variables set|unset|list` and set them afterwards per lambda (or store them within a template)

**Comment by kennu** [comment]
For some reason, "sls variables list" only shows me the contents of **s-variables-dev-euwest1.json**, while "sls meta sync" only synchronizes the contents of **s-variables-dev.json**. So I've put everything in s-variables-dev.json and can't use the "sls variables" command. Am I doing something wrong?

PS. I'm curious, why is it important to hide some environment variables from some Lambda functions? In all my projects they are global settings/secrets and there's no reason not to share them.

**Comment by HyperBrain** [comment]
Did you try `sls variables list --all` to show all regions and stages? If it's still missing then it's a bug that the vars are not shown. Feel free to create an issue for the list command then (and mention me in the comment). I'll then have a look.

**Comment by flomotlik** [comment]
We're going to centralise this in the future which will resolve this issue. Closing it here for now as we're going to open new issues once we create all the milestones for the V1 release.
