### ISSUE TITLE
Packaging support for ECR Images

### ISSUE THREAD

**Issue by ngoue** [serverless/serverless#9856]
### Use case description

When building images locally during deployment (e.g. `provider.ecr.image.myimage.startswith('./')`), it would be helpful if serverless still packaged my code and made it available for me to reference in the `Dockerfile`.  That way, I could still rely on `package.patterns` in my serverless.yml file for generating a slimmer build, as well as being able to get plugin packaging changes (i.e. have the serverless dashboard plugin still generate my `s_*.py` handler files).

### Proposed solution

When a local image is built, still generate package files and make them available as usual in the `.serverless` output directory.  Then, users can copy the build output to their image using regular `Dockerfile` directives:

```
# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/python:3.8

RUN yum update -y && yum install unzip -y
COPY .serverless/MyService.zip .
RUN unzip MyService.zip && rm MyService.zip

CMD ["s_api.handler"]
```

I started hacking together my own solution for a specific application I have, but decided this might be a good feature to include here and I'd be happy to work on it too - I just need some guidance to see if this is the right idea first.

**Comment by pgrzesik** [comment]
Hello @ngoue, thanks for opening that issue. While it sounds like a potentially useful feature, I'm afraid it might be a bit challenging to make it fit into current packaging logic, but most likely still doable. Would you be able to share the approach you took in your solution?

**Comment by ngoue** [comment]
Basically what I wrote above - before generating the docker image from the `Dockerfile`, first make a regular zip of the code as if it were being deployed as a zip package, but then run the docker image creation process.

My solution involves adding my own script to build the wrapper handler files for my functions manually.  I just copied the code from the dashboard plugin that generates the `s_*.py` wrapper and then filled in my own values before copying the generated files to the docker container during the image build.

Being able to package the service as a zip like it would for a regular handler would solve this.  I also realize that another solution could be to add a new plugin-specific command to the dashboard plugin - something like ` sls dashboard wrap api.handler` which would then generate a `s_api.py` file.  Maybe I should go that route instead?

I'm okay if serverless doesn't package my files for me (i.e. I have to use my Dockerfile to specify which files to include in the image), but it's such a big issue losing the dashboard features for my function by deploying it as an image.

**Comment by pgrzesik** [comment]
Thanks for clarification @ngoue - I thought that you may
be started writing some kind of plugin that hooks into the current Framework's packaging logic. I'm going to dive deeper into potential solutions for this issue as supporting Dashboard functionality in such cases would definitely be great.

**Comment by pgrzesik** [comment]
Hey @pop-srw - I'm going to close this issue as it's a duplicate and I will respond in https://github.com/serverless/dashboard-plugin/issues/614. Let's continue potential discussion there
