### ISSUE TITLE
Add functions to convert string to int or float

### ISSUE THREAD

**Issue by ctrlaltdev** [serverless/serverless#9868]
### Use case description

Some configurations require the value to be an integer, but if we want to fetch the value from somewhere else (like ssm), the value will be a string. A function similar to strToBool to cast a string to integer or float would solve this.

Example of configurations:
For aws provider, for functions, the memorySize, timeout and reservedConcurrency require an integer value.

### Proposed solution
I suggest adding functions similar to strToBool: strToInt and strToFloat that will parse the value to the requested type, return an error if incorrect.

so we could use something like `${strToInt(ssm:/my/param/is/string)}`

**Comment by ctrlaltdev** [comment]
I have a potential solution at the ready: https://github.com/serverless/serverless/compare/master...ctrlaltdev:master

**Comment by medikoo** [comment]
@ctrlaltdev Thanks for request. In latest Framework versions, for defined properties the coercion occurs automatically, so e.g. if your variable source returns numeric string where number is expected, it'll be automatically coerced to number.

Do you observe it not working as expected?

**Comment by ctrlaltdev** [comment]
Alright then - guess this is not required then.
