### ISSUE TITLE
Serverless synth that only generates cloudformation

### ISSUE THREAD

**Issue by luchees** [serverless/serverless#9871]
### Use case description

When using a linting tool to validate all the resources created by serverless ( naming lengths ,..) it takes a long time to generate the cloudformation with the `serverless package` command.

I wonder if it would be possible to have a `serverless synth` command that only generates the cloudformation.

### Proposed solution

`serverless synth` command that only generates the cloudformation.

**Comment by pgrzesik** [comment]
Hello @luchees :wave: Thanks for the proposal. Unfortunatelly, the CloudFormation that is generated also contains values that can only be generate during packaging process (e.g. hashes for versions, SHA hashes for container images, etc) so we cannot really reliably generate CF template without running package step. 

Could you share more about your use case? What are you trying to validate exactly? Maybe there's a way to do this kind of validation without actually generating full CF template?

**Comment by medikoo** [comment]
@luchees I also assume that you are drawn by slow packaging performance, and if it'll be working fast it wouldn't pose the issues (?)

If that's the case track https://github.com/serverless/serverless/issues/6580 we're looking forward to address this problem that at some point

**Comment by luchees** [comment]
Hello @pgrzesik ,
Thanks for your prompt explanation. 
Our use cases are mostly naming size restriction like:
Loadbalancer name, IAM role name, Lambda functionname and other resources created by Serverless.
Most names are generated only when the cloudformation is generated, it would be awesome if we could check this in Serverless already. When the package is being created for example that the naming size limitations are being checked. 

Hello @medikoo,
I am indeed drawn by slow package performance. We use ESbuild for our builds which goes relatively fast but still too slow. It would waste time and money in our github actions to run the full package command to run the validations.

**Comment by medikoo** [comment]
Thanks @luchees for explanations. I assume that if with ESBuild you still observe slow performance, there might be not much further room to optimise it.

Concerning issues where Framework generates too long names, please see https://github.com/serverless/serverless/issues/7056 - we plan to tackle that at some point, but there's no ETA at this point. Still if community will share interest it'll definitely help to bump this up.
Still it's about names as generated by Framework internals, if you have issues with names as generated by your local plugins or some external plugins, it may not cover this fully

**Comment by medikoo** [comment]
Nonetheless I see value in ability of doing `sls package` but without generation of artifacts. Still I'd rather see it configurable via some CLI flag to `sls package` command and not a new command. Also while we could adapt our internal packaging to that, it may not be possible to automate it for packaging plugins. it might be that each of them will need to recognize this flag in its own scope (that's to be investigated)

**Comment by pgrzesik** [comment]
@medikoo How do you think should such generation work without producing artifacts? The issue I see here is that CloudFormation configuration depends on generated artifacts e.g. for version hashes and in such scenario we cannot really generate the template.

**Comment by luchees** [comment]
Thanks @medikoo for the clarifications. I understand that a configurable cli flag with sls package would make sense. 

I understand you are working on the validation part and for some resources the validation is in Serverless already. I know you support more then one cloud provider so this can become complicated fairly quickly. 

Currently we are working on a workaround with the serverless-esbuild plugin where we would "disable bundle" so our packaged lambda will only contain the `handler.js` file and no dependencies. This will make the `sls package` command a lot faster but the packaged zip's won' work when uploaded to AWS. As we do not need that for validation that would be enough for our use-case. Not 100% sure how the developers will proceed but it seems to be possible they said.

**Comment by medikoo** [comment]
> The issue I see here is that CloudFormation configuration depends on generated artifacts e.g. for version hashes and in such scenario we cannot really generate the template.

@pgrzesik indeed good point, I missed that when writing last comment. 

In light of that, I believe we can agree that there's no real way to produce 1:1 CF template without generating artifacts, and that makes this feature really questionable.

**Comment by luchees** [comment]
I understand die complications. I guess our workaround will be the way to go. 
Anyways thanks for your input guys. Really enjoy working with Serverless Framework.

**Comment by pgrzesik** [comment]
Thanks @luchees :bow: I just want to mention one thing about your workaround - with the approach you're taking, the CF template that is being produced is not 1:1 the same as the one that would be produced with actual proper bundle - the reason for that is that version hashes are different due to different zip contents in your case - just something to keep in mind when going that route.
