### ISSUE TITLE
Exponential retry delay for recoverable errors from the AWS API

### ISSUE THREAD

**Issue by avnerenv0** [serverless/serverless#9893]
### Use case description
We are heavy Serverless users, running multiple stages through automation, with lots of functions and resources.
We are frequently getting throttling errors from AWS.
The current retry scheme is not sufficient.

### Proposed solution
Implement an exponential delay between retries.
Looking at https://github.com/serverless/serverless/blob/master/lib/aws/request.js this shouldn't be too hard.

We can define a new environment variable - `SLS_AWS_REQUEST_RETRY_DELAY_EXPONENT`
It will default to `1` (or `0` depending on the implementation), preserving the existing behavior.
When it will be `>1` - each `backOff` will be exponentially bigger (relative to `numTry` and `SLS_AWS_REQUEST_RETRY_DELAY_EXPONENT`, with some `jitter`).

If this is acceptable, we can work on a PR.
Would love to hear feedback or alternative solutions.

BTW documenting `SLS_AWS_REQUEST_MAX_RETRIES` as well as any new tweakable environment variable can/should also be part of this.

Thanks 🙏

**Comment by mnapoli** [comment]
Hi, would it make sense to improve the existing retry mechanism directly? (rather than introducing a new option)

**Comment by avnerenv0** [comment]
Hi @mnapoli 

I'm not sure what you mean by "improve the existing retry mechanism directly".
Could you elaborate please?

I also wouldn't feel comfortable making a 'breaking change' to existing behavior.

Thanks

**Comment by mnapoli** [comment]
Sorry, I meant improving the existing retry mechanism with exponential retries (or anything else).

What can we do that don't involve adding new options or logic branch?

**Comment by avnerenv0** [comment]
Well we can make the current retry mechanism wait times exponential to the number of retries, but that would change current behavior - which I'm not comfortable with.

Otherwise we have to introduce some kind of new configuration - since we are adding new behavior. 
It's not that much of a new logic branch - since the new configuration will default to a value that sets the exponent to 1, meaning the delay times will stay the same way the are today. So it's "changing the formula" without adding a conditional. 
The only conditional would be to set the default value of the new configuration variable, if it's not set.

**Comment by mnapoli** [comment]
Sure, I'm interested to learn why you prefer not to do that?

What would be the practical impact for users? I see that as making the CLI more robust, so I consider it a win for everyone. I'm guessing I'm missing some strong negative impact for some users?

**Comment by pgrzesik** [comment]
I believe that we could improve the existing mechanism by introducing an extra variable that by default does not change anything in the current logic. I don't think we need two separate retry mechanisms as it would only complicate things without introducing much value. 

> We can define a new environment variable - SLS_AWS_REQUEST_RETRY_DELAY_EXPONENT
It will default to 1 (or 0 depending on the implementation), preserving the existing behavior.
When it will be >1 - each backOff will be exponentially bigger (relative to numTry and SLS_AWS_REQUEST_RETRY_DELAY_EXPONENT, with some jitter).

I think the approach similar to this one could be the way to go - by default, the behavior would be the same but you could set an env var to adjust it to your needs. 

What do you guys think?

**Comment by mnapoli** [comment]
TBH I'm still wondering why not improve the retry logic for everyone? Are there different use cases?

**Comment by pgrzesik** [comment]
But isn't it an improvement for everyone if they can use that setting to adjust their retry delay/backoff if needed? I don't think we had any other reports about the current retry mechanism. I don't have a strong opinion here as I don't think it's going to be an impactful change for more than a fraction of users.

**Comment by mnapoli** [comment]
> But isn't it an improvement for everyone if they can use that setting to adjust their retry delay/backoff if needed?

Totally, but as a user I'd rather have that improvement automatically, rather than have to do anything.

But it seems the discussion depends on: what would change for users? Once we know that, then it may be easier to answer "is it a good thing for everyone or not?"

Maybe it would help to compare actual numbers (in seconds or minutes):

- what are the retry timeouts right now?
- what would you suggest they be @avnerenv0?

**Comment by medikoo** [comment]
@avnerenv0 can you provide a bit more details about your use case?

Why exactly current retry mechanism is not great?
Does it stops too early, when in your case you need to wait a bit longer for env to become stable is needed?

Why simply using a bigger value for `SLS_AWS_REQUEST_MAX_RETRIES` doesn't work as a right solution to the problem?

**Comment by avnerenv0** [comment]
@medikoo You are correct
A bigger value for `SLS_AWS_REQUEST_MAX_RETRIES` will work.
It just seems more "correct" to "back off" after getting consecutive throttling errors.
 
So I think I'll go ahead and close this issue, I guess the only one "hurt" by this is AWS's API and I think they'll manage :)

**Comment by medikoo** [comment]
@avnerenv0 yes, we intentionally didn't setup exponential back off's, as we weren't aware in this specific case of a real benefit (it's not a server overload that we deal with)

"Rate exceeded" errors afaik are triggered purely by successful responses, and when keeping retries relatively often we provide means to recover from them more quickly then it would be with exponential back offs

**Comment by avnerenv0** [comment]
Thanks for the help from everyone ☝️ 
Sorry for the bother.
