### ISSUE TITLE
run lambda function with input parameter

### ISSUE THREAD

**Issue by lhj1982** [serverless/serverless#990]
Hi. I have started a aws project with help of serverless framework, but i have one question regarding run lambda function.

How can I run lambda function with input parameters? I can do it via amazon console, lambda test configuration->test event. but I cannot find a correspondning function in serverless.

Thanks!

**Comment by eahefnawy** [comment]
if you mean running your function for testing, there's an `event.json` file inside your function folder that you can put your sample data (input params) in so that when you run `sls function run` it'll be passed to the function.

Hope that helps! Is that what u mean?

**Comment by lhj1982** [comment]
Hi, eahefnawy
Thanks for quick reply! it did work after i update event.json. and now I have another question, 

I have a lambda function getProductCatalog which can either take no parameter (fetch all products) or id as parameter (fetch one product by id), can I somehow use event.json as my test data for both cases? Or i'd better split them into 2 lambda method?

**Comment by stanyq4** [comment]
Trying to figure out the same question, how do I pass array of input params? Would input: [1,2,3,4,5] work?

**Comment by pmuens** [comment]
Hey @stanyq4 you could use `invoke` or `invoke local`.

Here are the docs which shows you how to use both functions:

- https://serverless.com/framework/docs/providers/aws/cli-reference/invoke/
- https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/
