### ISSUE TITLE
Custom Authorizers outside of the Serverless project

### ISSUE THREAD

**Issue by mwielansky** [serverless/serverless#991]
Serverless expects the authorizer function to be part of the project, but is this necessary? We use a shared custom authorizer lambda function for multiple serverless projects. I'd like to request a new feature to allow authorizer.authorizerUri to be specified in s_function.json and simply be passed to aws similar to authorizer.name and authorizer.type.

**Comment by ajagnanan** [comment]
+1

**Comment by spardo** [comment]
+1

**Comment by flomotlik** [comment]
This was implemented in #1620
