### ISSUE TITLE
Add support for Amazon MQ RabbitMQ event source

### ISSUE THREAD

**Issue by liegeandlief** [serverless/serverless#9924]
Lambda now supports Amazon MQ RabbitMQ queues as an event source. Support should be added to the Serverless Framework. Support for Amazon MQ ActiveMQ queues already exists (see https://github.com/serverless/serverless/pull/8840) and so can be used as the basis for adding RabbitMQ support.

**Comment by liegeandlief** [comment]
PR for this is now open - https://github.com/serverless/serverless/pull/9919

**Comment by pgrzesik** [comment]
Thank you @liegeandlief for proposing the issue and the PR as well :bow: I'm a bit swamped at the moment but I'll try to test it out by the end of the week (unfortunately integration tests are a bit lengthy to test them out).

**Comment by liegeandlief** [comment]
Addressed by https://github.com/serverless/serverless/pull/9919
