### ISSUE TITLE
Broken link in the header of the readme

### ISSUE THREAD

**Issue by Pigius** [serverless/serverless#9932]
I would like to report a bug in the readme of the project. At the very top there is information about a job offer:

![Screenshot 2021-09-09 at 11 14 47](https://user-images.githubusercontent.com/8863200/132658467-b2f841fa-8d48-4cfe-b2c6-ed2690ad3943.png)

After you click the link, it will redirect to 404 page:
![Screenshot 2021-09-09 at 11 14 41](https://user-images.githubusercontent.com/8863200/132658519-4d9bb02d-ee30-4b63-811e-908019dc7e25.png)

Please do fix it :)

**Comment by mnapoli** [comment]
Thanks, I've reported that internally. We recently launched a new version of the website, it's probably a redirect that's missing.

**Comment by mnapoli** [comment]
That's fixed, thanks!

https://www.serverless.com/company/jobs/
