### ISSUE TITLE
`Could not parse JSON in file` after adding kinesisstream as event source to s-function.json

### ISSUE THREAD

**Issue by theburningmonk** [serverless/serverless#994]
Hi, I' running serverless v0.5.3, and after adding the Kinesis stream example from the [documentation](http://docs.serverless.com/docs/function-configuration) I started to get this error for every command (even `serverless help`):

```
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^
ServerlessError: Could not parse JSON in file: /Users/yancui/SourceCode/{omitted}/processors/new-user/s-function.json
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Object.module.exports.readFileSync (/usr/local/lib/node_modules/serverless/lib/utils/index.js:196:15)
    at /usr/local/lib/node_modules/serverless/lib/Serializer.js:64:38
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

this is what the s-function.json's events field looks like:
```
"events": [
    {
      "name" : "myKinesisStream",
      "type": "kinesisstream",
      "config": {
        "streamArn": "${newUserStreamArn}", // required!
        "startingPosition": "LATEST", // default is "TRIM_HORIZON" if not provided
        "batchSize": 50, // default is 100 if not provided
        "enabled": true // default is true if not provided 
      }
    }
  ],
```

I have tried changing `name`, `streamArn`, `startingPosition`, `enabled` values, but nothing makes a difference.

**Comment by eahefnawy** [comment]
@theburningmonk did you leave off the comments? JSON doesn't support comments ... we just put them in the docs for demo purposes. It's not intended to be copy/pasted right away :) ... could you try to remove the comments and see if it'll work?

**Comment by theburningmonk** [comment]
of course that'll be it, I'm such an idiot! :-P
