### ISSUE TITLE
Error: EPERM: operation not permitted, unlink '..../.build/node_modules'

### ISSUE THREAD

**Issue by trevorgillis** [serverless/serverless#9947]
Running `serverless package` results in the error `Error: EPERM: operation not permitted, unlink '..../.build/node_modules'` and I can't move forward. Here's the information about my system:

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.6
     Framework Version:         2.58.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0

I am using the `serverless-plugin-typescript` plugin and the problem seems to stem from that. I've tried a number of different things: downgrading the plugin to 1.1.7 per [this issue](https://github.com/serverless/serverless-plugin-typescript/issues/170), deleting `.serverless/`, `.build/`, `node_modules/`, and `yarn.lock` and running `yarn` for a fresh start, and upgrading serverless and node, but nothing helps.

Here is my `tsconfig.json` file:

```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"lib": ["es6", "dom"],
		"moduleResolution": "node",
		"rootDir": "./",
		"sourceMap": true,
		"allowJs": true,
		"noImplicitAny": true,
		"noUnusedLocals": true,
		"noImplicitThis": true,
		"strictNullChecks": true,
		"noImplicitReturns": true,
		"preserveConstEnums": true,
		"suppressImplicitAnyIndexErrors": true,
		"forceConsistentCasingInFileNames": true
	},
	"exclude": ["node_modules", "build", "webpack"],
	"types": ["typePatches"]
}
```

Please let me know if you need any more information from me.

**Comment by trevorgillis** [comment]
I opened an issue [here](https://github.com/serverless/serverless-plugin-typescript/issues/251) instead since it seems to be an issue with the plugin rather than serverless core.

**Comment by pgrzesik** [comment]
Thanks @trevorgillis - indeed, it seems like the issue with plugin.
