### ISSUE TITLE
Event Names Shouldn't be Unique Project-Wide

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#995]
We're heavily using scheduled events in our setup. With SLS 0.5.x it seems the behavior changed and is now inconsistent in best case.

The problem is the new requirement of naming events uniquely across the whole project. I'm talking about the `name` parameter here:
```
  "events": [
    {
      "name": "schedule",
      "type": "schedule",
      "config": {
        "schedule": "rate(1 day)",
        "enabled": true
      }
    }
  ]
```

In the past it was perfectly fine to use `"schedule"` as a name, or leave it out completely if you only had one event per function (in which case it would be called "mySchedule" automatically).

Now it seems that this event name must be unique among all functions in the project. If you reuse a name in different functions, then SLS will actually not even complain but will only deploy the one of the events and skips the rest without notifying/complaining to the user.

I consider the requirement of having unique event names a bug, not a feature. My reasons are:
* The user can omit the event name in which case it is set to "mySchedule" automatically. This wouldn't work anymore if every event needs to have a unique name.
* The final name of the event in CloudWatch is `<function-name>-<event-name>` and thus already is unique. There's no need to make `<event-name>` itself unique in this case.
* The length of event names in CloudWatch is limited to 64 characters. Requiring unique event names makes it way too easy to hit this limit, especially as the function name is prepended anyway.
* Even the current documentation states that event names need to be unique _per function_, but not per project.

**Comment by rifflock** [comment]
I hit this issue too, so I put together a minor change to support non-unique event names for schedules.

**Comment by erikerikson** [comment]
If SLS is munging the name, we'll need a customName here too.

**Comment by shortjared** [comment]
This just burned us hard too.

Not sure how feasible it is, but it would also be nice to have shared events, as many functions could all run on the same "schedule" without having a bunch of duplicate CW Scheduled events.

**Comment by flomotlik** [comment]
In V1 events are handled differently through Cloudformation and they don't have to be unique in this way any more. Closing therefore.
