### ISSUE TITLE
New typescript template throws "Outdated global installation of 'serverless'"

### ISSUE THREAD

**Issue by staff0rd** [serverless/serverless#9953]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

With a fresh install, creating a new typescript template and running `serverless` after `npm i` throws:

> Outdated global installation of 'serverless'. Please upgrade. It's needed to ensure desired interactive CLI experience

### Service configuration (serverless.yml) content

```
N/A
```

### Command name and used flags

```
npm i -g serverless
serverless create --template aws-nodejs-typescript --path my-test
cd my-test
npm i
serverless
```

### Command output

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION

  Serverless Error ---------------------------------------

  Outdated global installation of 'serverless'. Please upgrade. It's needed to ensure desired interactive CLI experience

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         2.8.0 (standalone)
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.3
```

### Environment information

```shell
Framework Core: 2.58.0 (local)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```

**Comment by medikoo** [comment]
@staff0rd Error message states that your global installation of `serverless` is outdated (by log output it looks it's at v2.8.0). 

Please upgrade

**Comment by pgrzesik** [comment]
One note to what @medikoo said - it looks like you're using globally installed version that was installed as a standalone binary, not with `npm`, so upgrading via `npm` won't work there.

**Comment by staff0rd** [comment]
> it looks like you're using globally installed version that was installed as a standalone binary

Thanks, I'd completely forgotten that was possible. 

After running the following, the problem was resolved:

```
rm -rf ~/.serverless
```
