### ISSUE TITLE
sls variables command uses region-specific files and meta sync does not

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#998]
When I use the `sls variables` command to list or set variables, it uses the file **s-variables-dev-euwest1.json** and ignores the contents of file **s-variables-dev.json**. --all does not seem to affect this, it just shows all the stages but still uses the region-specific files.

This is problematic, because `sls meta sync` only seems to synchronize the file **s-variables-dev.json** to S3.

Overall I'm confused about which files I should be using for my variables, which files should be excluded from Git, and which files `sls meta sync` is intended to synchronize.

The way that I'm currently using these files is that I exclude **s-variables-dev.json** from Git, put my secrets in it, and synchronize it with `sls meta sync`. However, that requires new team members to first create dummy files with {} as their contents, because otherwise `sls meta sync` won't recognize the stage existing.

If there is a better way to do all this, I would be very happy to hear it.

(Discussed with @HyperBrain in #985 )

**Comment by HyperBrain** [comment]
Tested this -> Bug confirmed.
The `sls variables xxx` commands work perfectly with the `s-variables-common.json` and `s-variables-{stage}-{region}.json` files, but do not evaluate the `s-variables-{stage}.json` files.
This should be fixed.

**Comment by HyperBrain** [comment]
The documentation should be also adapted to honor the variables command changes. (see `sls variables [set|unset|list] --help).
