### ISSUE TITLE
ReadMe's team at serverless email is bouncing. 

### ISSUE THREAD

**Issue by mikeumus** [serverless/serverless#999]
Hello Serverless,

I just tried emailing team @ serverless dot com and it bounced back. If I knew the correct email I'd have just provided a simple pull-request with the errata fix. I hope this is a legit issue and that it helps.

Specifically in the ReadMe link: "...please send us a message."

If this mailto link in ReadMe is broken then the "Contact Us" link in the "Links" section at the bottom of the ReadMe needs attention as well.  

Best,
_Mike_

**Comment by flomotlik** [comment]
thanks @mikeumus will fix
